### ISSUE TITLE
New Feature : Gmap

### ISSUE THREAD

**Issue by zamrokk** [primefaces/primeng#100]
Are you planning to add Gmap feature like we have for Primefaces JSF ?

**Comment by cagataycivici** [comment]
Yes we have plans indeed to make common tasks easier. Thanks for your feedback and creating the issue.

**Comment by cagataycivici** [comment]
Will be available next week with 1.0.0-beta.1

**Comment by cagataycivici** [comment]
Implemented gmap with common features like events, overlays and so on.

**Comment by zamrokk** [comment]
Fantastic !
