### ISSUE TITLE
P-Chips 508 Issue

### ISSUE THREAD

**Issue by SDvlpr** [primefaces/primeng#10009]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
p-chips is not 508 compliant because there is No accessibility markup found for this Element.
--

**Expected behavior**
When Chips element is accessed, the accessibility software should be able to access the markup for the p-chips.

![image](https://user-images.githubusercontent.com/30119190/111311733-f1ea0800-8634-11eb-9773-04c0b7583a51.png)

**What is the motivation / use case for changing the behavior?**
508 Accessibility.

**Please tell us about your environment:**
VS Code, Chrome

* **Angular version:** 
V8

* **PrimeNG version:** 5.X
11.3.1

* **Browser:** 
Chrome

 
* **Language:** TypeScript 

* **Node (for AoT issues):** `node --version` =    10

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
