### ISSUE TITLE
Password meter not working when used in input group and/or form

### ISSUE THREAD

**Issue by Skuriles** [primefaces/primeng#10000]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

**Current behavior**

pPassword meter not working in formgroup
**Expected behavior**

show password-meter on entering characters
**Minimal reproduction of the problem with instructions**
See Stackblitz:
https://github-axqz6x.stackblitz.io

* **Angular version:** 11.2.3

* **PrimeNG version:** 11.3.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome (not tested in others) 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS

**Comment by yigitfindikli** [comment]
pPassword is deprecated. You can use p-password component instead of pPassword. You can get more information at https://primefaces.org/primeng/showcase/#/password .

**Comment by Skuriles** [comment]
Then please remove directive from  documentation:

> Getting Started
> Component is defined using p-password element with a mask and two-way value binding is enabled with standard ngModel directive.
> <input type="password" pPassword />
