### ISSUE TITLE
Dropdown rendering behind the control in a datatable column

### ISSUE THREAD

**Issue by vvvttt** [primefaces/primeng#1000]
Hello,

I have created following template to show one of the columns of a datatable as a dropdown. But this code expands the dropdown behind another control. The expansion is not visible. Any idea on what is missing here?

  <p-column  header="CM" sortable="true" [filter]="true" filterMatchMode="contains"> 
                <template  pTemplate type="body"   >
                    <p-dropdown [options]="cl" ></p-dropdown>
                </template>
            </p-column> 

Thanks.

Update: I resolved it.

**Comment by tapas4java** [comment]
@vvvttt Can you please share the fix? I am getting similar issue when using PrimeNG Dropdown component inside Material2 Card component.

**Comment by vvvttt** [comment]
This is how added the style in the column

  <p-column  header="UO" sortable="true" [filter]="true" filterMatchMode="contains" [style]="{'overflow': 'visible'}"  [editable]="true"> 
        <template  pTemplate type="body"   >
            <p-dropdown [options]="List" (onChange)="onInputChange($event)"></p-dropdown>
        </template>
    </p-column>
