### ISSUE TITLE
Error when using Badge on Avatar

### ISSUE THREAD

**Issue by markasalinas** [primefaces/primeng#10005]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Using the following avatar:
     `   <p-avatar label="U" pBadge styleClass="p-mr-5" value="4" size="xlarge" [style]="{'background-color': '#4caf4f', 'color': '#ffffff'}"></p-avatar>`

Throws the following error
`DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
`

**Expected behavior**
I expect to see an avatar with the badge.

* **Angular version:**
11.2.1

* **PrimeNG version:**
11.3.1

* **Browser:**
ALL
 
* **Language:**
Typescript 4.1.5

**Comment by yigitfindikli** [comment]
I couldn't replicate it with [v11.3.1](https://stackblitz.com/edit/primeng-avatar-demo-txvm59).
