### ISSUE TITLE
Pcalendar reset is not clearing filter while reset table state 

### ISSUE THREAD

**Issue by MohamedSahir** [primefaces/primeng#10004]
primeng version:9.0.6

i am using primeng table one of the coulmns using pcalendar , that is not setting  in filter and clearout filter in tablestate local 
I have clearReset button to clear all filter value.when i try to reset the table all fields are resetting except the calendar filter.But result is resetted but in filter it still keep a value. And also same for Setting the value for calendar . suppose i have filter the value in localstate and refresh the page i could see the result but it is not selected in pcalendar.

```

   <th>
        <p-calendar (onSelect)="onDateSelect($event)" (onClearClick)="dt.filter('', 'date', 'equals')"
          [showButtonBar]="true" styleClass="p-column-filter" placeholder="Registration Date" [readonlyInput]="true"
          dateFormat="yy-mm-dd"></p-calendar>
      </th>
```
``

clearFilter(){
   this.table.reset();
    this.table.clearState();
}
```
![image](https://user-images.githubusercontent.com/20682302/111167660-59696e80-85c7-11eb-8e58-faa4bf1c83d0.png)

Demo:
[demo](https://stackblitz.com/edit/primeng-tablefilter-demo-evtxvu?file=src%2Fapp%2Fapp.component.html)

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.3.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
