### ISSUE TITLE
Dataview is not applied multiple filters

### ISSUE THREAD

**Issue by AlbaSS18** [primefaces/primeng#10008]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-dataview-demo-mjr5cw?file=src/app/app.component.ts

**Problem**
I have a project where I use the dataview component. I want to do is that the user can filter by several fields at the same time, in this case name and category. The problem is that it only filters by one.

**Minimal reproduction of the problem with instructions**
This is the complete dataview.
![image](https://user-images.githubusercontent.com/46462037/111298891-9aa56100-864f-11eb-9d81-471154d69121.png)
Now, I select a category in the multiselect, for example, _Accesories_ , and only it shows products with this category. 
![image](https://user-images.githubusercontent.com/46462037/111298935-a2fd9c00-864f-11eb-9921-23da8e2d1369.png)
Now, I write in the input. The dataview shows products with a category different from 'Accesories'. Here is my problem. Multiple filters aren't applied.
![image](https://user-images.githubusercontent.com/46462037/111298953-a729b980-864f-11eb-86e0-774a84153182.png)

**Please tell us about your environment:**

* **Angular version:** 11

* **PrimeNG version:** 11

* **Browser:** Chrome

 
* **Language:** TypeScript

**Comment by dmitri678** [comment]
I am also having this issue.

**Comment by cetincakiroglu** [comment]
Hi,

We couldn't replicate the issue with the latest PrimeNG release, if the issue still exists with the latest PrimeNG version, please provide a StackBlitz example by using [PrimeNG Issue Template ](https://stackblitz.com/github/primefaces/primeng-issue-template) and re-open the issue.

Regards
