### ISSUE TITLE
LazyLoad Support for p-dropdown

### ISSUE THREAD

**Issue by VarunAnandK** [primefaces/primeng#10006]
Hi team,
      First thank for the wonderfull ui component, i facing missing option for p-dropdown lazy load, because i m loading the 1+ million record from api there is the good option is there named as virtual scroll but my data cost is more so please try to impelement the lazy load option 

sorry for my english.

**Comment by crazyjavatricks** [comment]
Please consider the same in **p-multiSelect** also.

**Comment by kareljuricka** [comment]
+1

**Comment by almasry2011** [comment]
+1

**Comment by piratenlk01** [comment]
+1

**Comment by leandroheidemann** [comment]
In p-autocomplete too.

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
