### ISSUE TITLE
Table Edit Showcase Stackblitz bug on website

### ISSUE THREAD

**Issue by mikethibault** [primefaces/primeng#10007]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
The Stackblitz for https://www.primefaces.org/primeng/showcase/#/table/edit differs from what is on the page.
The last line of the onRowEditCancel function references products2 instead of the correct clonedProducts.

**Expected behavior**
Stackblitz link code should be identical to the website's.

**Comment by yigitfindikli** [comment]
Fixed https://stackblitz.com/edit/primeng-tableedit-demo
