### ISSUE TITLE
p-toast: long detail text hides closing icon

### ISSUE THREAD

**Issue by Hexaflexagon** [primefaces/primeng#10012]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://primeng-toast-demo-hjqpdq.stackblitz.io

**Current behavior**
A long detail text hides the closing icon
![image](https://user-images.githubusercontent.com/6772159/111329665-91c48780-866f-11eb-9faf-e821bb41e19f.png)
![image](https://user-images.githubusercontent.com/6772159/111329759-a739b180-866f-11eb-9239-03d6b537d897.png)

**Please tell us about your environment:**

* **Angular version:** 11.0

* **PrimeNG version:** 11.3

* **Browser:** Chrome 89 | Firefox 78.8.0esr | Edge 89
 
* **Language:** TypeScript 4.0.2

**Comment by waratah** [comment]
I tweaked my toast to break lines more using CSS:


.p-toast .p-toast-message .p-toast-message-content .p-toast-summary {
  white-space: pre-line;
  font-size: smaller;
}
.p-toast .p-toast-message .p-toast-message-content .p-toast-detail {
  white-space: pre-line;
  font-size: smaller;
}

**Comment by buchatsky** [comment]
Same bug
- Angular 13.2.2
- PrimeNg 13.2.0

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by eruslan44** [comment]
Hi!
Same bug

Angular 16.1.5
PrimeNg 16.0.2

**Comment by Abziz** [comment]
> Same bug
> 
> * Angular 13.2.2
> * PrimeNg 13.2.0
>   The following helped me:
> 
> ```
> .p-toast-message-text {
>     overflow-wrap: break-word;
>     max-width: 18.5rem;
> }
> ```

I find using this to behave better: 
```css
.p-toast-message-text {
  overflow-wrap: break-word;
  min-width: 0;
}
```
