### ISSUE TITLE
PInputNumber NgModel not updating

### ISSUE THREAD

**Issue by OPunktSchmidt** [primefaces/primeng#10017]
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Plunkr Case (Bug Reports)**

https://stackblitz.com/github/OPunktSchmidt/PrimeNG-PInputNumberNgModel-Issue

**Current behavior**

The input in a PInputNumber **_is not_** immediately reflected in the binded variable through NgModel.

**Expected behavior**

When you enter a value in PInputNumber the value should appear immediately  in the typescript code.

**Minimal reproduction of the problem with instructions**

1. Open Stackblitz demo
2. Enter value in "Text input". You can see the value appears immediately next to the input field
3. Enter value in "Number input". You can see the value appears **_not_** immediately next to the input field. You have to leave the input field by clicking somewhere else

![image](https://user-images.githubusercontent.com/7362709/111596845-e5e57e00-87cd-11eb-9641-1aff465ada03.png)

* **Angular version:** 11.2.1

* **PrimeNG version:** 11.3.1

**Comment by yigitfindikli** [comment]
InputNumber's model Is updated when blur or hitting enter by design.
