### ISSUE TITLE
firstDayOfWeek is broken in 11.3.1

### ISSUE THREAD

**Issue by WillooWisp** [primefaces/primeng#10013]
This works in 11.3.0, but not after upgrading to 11.3.1.

**Comment by denny99** [comment]
![image](https://user-images.githubusercontent.com/1826849/111494618-e97df400-873e-11eb-8895-25d1e7e4388f.png)

![image](https://user-images.githubusercontent.com/1826849/111494645-f0a50200-873e-11eb-8ca6-c9c39bd04bb1.png)

It works when you change the order in your i18n data. But the code for the whole @Input is still in place and even generates the correct weekDay array. But in the rendering process it just uses the i18n Data

**Comment by WillooWisp** [comment]
I don't use the i18n data but rely on the firstDayOfWeek property that I bind to region settings.

`<p-calendar [(ngModel)]="date" [firstDayOfWeek]="firstDayOfWeek" inline="true"`
