### ISSUE TITLE
p-inputMask displaying black border when loading and then removes after in some milliseconds

### ISSUE THREAD

**Issue by jainAdijain** [primefaces/primeng#10011]
Using prime-ng version - 5.2.0
browser - chrome

p-inputMask displaying black border when loading for some time and then the border is removed in some milliseconds.
When looking on the Developer tools options it is found that it is due to user agent stylesheet.

Please look at the screen shots below:

![image](https://user-images.githubusercontent.com/27722458/111325750-ff81ab00-8691-11eb-848f-dab39c1f43a7.png)

![image](https://user-images.githubusercontent.com/27722458/111325809-11634e00-8692-11eb-90db-466ab5475192.png)

![image](https://user-images.githubusercontent.com/27722458/111325859-1b854c80-8692-11eb-836c-32ee157109db.png)

How to hide this black border when the p-inputMask is loaded.

I have tried using p-inputMask:focus { outline: transparent 1px sold } , but that also wont work and displays the black border at the initial load time.

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.
