### ISSUE TITLE
P-Dropdown attribute set as readonly:readonly 508 Accessibility

### ISSUE THREAD

**Issue by SDvlpr** [primefaces/primeng#10010]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

**Current behavior**
When using 508 tools, the P-dropdown had readonly attribute set as readonly.
When p-dropdown is used in our application, though the dropdown is editable, because of this attribute set as readonly, the 508 Accessibility tool is reading it as readonly and is causing confusion in users.

**Expected behavior**
Readonly attribute must not be set to readonly always.

**Minimal reproduction of the problem with instructions**

![image](https://user-images.githubusercontent.com/30119190/111313544-ded83780-8636-11eb-91ce-155bf4e7ce52.png)

**What is the motivation / use case for changing the behavior?**

508 Accessibility

**Please tell us about your environment:**

VSCode

* **Angular version:** 5.X
8

* **PrimeNG version:** 5.X
11.3.1

* **Browser:** 
Chrome

 
* **Language:** 
Typescript

* **Node (for AoT issues):** `node --version` =  
10

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
