### ISSUE TITLE
Picklist cannot add all on first render

### ISSUE THREAD

**Issue by xadhoom** [primefaces/primeng#1001]
When initializing a picklist for the first time, pressing the "add all" button does nothing.
You have to select any item, then the add all works.

Verified also on http://www.primefaces.org/primeng/

**Comment by xadhoom** [comment]
still present on beta17

**Comment by cagataycivici** [comment]
Fixed today via https://github.com/primefaces/primeng/commit/afa673bc3d71225d683cda42c869b9bcceecd61c
