### ISSUE TITLE
pTooltip on pInputText not visible when disabled

### ISSUE THREAD

**Issue by OPunktSchmidt** [primefaces/primeng#10014]
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Current behavior**

When pInputText is disabled the pTooltip  is not visible. On other controls like Calendar, Number-Input etc. it is still visible even the control is disabled.

**Expected behavior**

Tooltip should be visible even the control is disabled.

**Minimal reproduction of the problem with instructions**

`<input type="text" pInputText pTooltip="a text" [disabled]="true" />`

* **Angular version:** 11.X
* **PrimeNG version:** 11.X

* **Browser:** Chrome. Not testet in other Browsers

**Comment by yigitfindikli** [comment]
This is expected. You can override `pointer-events: none `from CSS.
