### ISSUE TITLE
P-table is missing dependency only in Docker

### ISSUE THREAD

**Issue by Zaknarfen** [primefaces/primeng#10028]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
![error](https://user-images.githubusercontent.com/4223973/111890561-3ffe6300-89c9-11eb-8e13-578d8d927b76.jpg)

**Expected behavior**
No dependency errors.

**Minimal reproduction of the problem with instructions**
Clone [https://github.com/nitin27may/mean-docker](this) and hook the PrimeNG table module (install the PrimeNG libraries and dependencies). When you add the selector in one of the components the error should show up. It only happens inside docker, outside everything works fine.

This is the dockerfile:
![dockerfile](https://user-images.githubusercontent.com/4223973/111890630-f19d9400-89c9-11eb-9bbb-ff3f9ea7bdca.jpg)

**Please tell us about your environment:**

* **Angular version:** 11.2.6

* **PrimeNG version:** 11.3.1

 
* **Language:** TypeScript 4.1.5

* **Node (for AoT issues):** `node --version` = v14.16 .0

**Comment by yigitfindikli** [comment]
You need to install @angular/cdk. You can find more info at https://primefaces.org/primeng/showcase/#/dropdown

**Comment by Zaknarfen** [comment]
I did already, as I mentioned @yigitfindikli, everything works fine outside Docker. I don't know what to do. All the builds work, the app runs fine, and when I move to Docker that dependency keeps missing.

**Comment by Zaknarfen** [comment]
If anyone runs into this with PrimeNG or another library, I changed the volume in the docker-compose.debug.yml to this:

![change](https://user-images.githubusercontent.com/4223973/112766276-5c148c80-8fe7-11eb-965e-032fa6a9efdc.jpg)

Now it builds without any problems.
