### ISSUE TITLE
p-columnFilter does not take into account the locale for type date

### ISSUE THREAD

**Issue by jducos33** [primefaces/primeng#10033]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Code**
`<p-columnFilter dateFormat="dd/mm/yy" type="date" [matchModeOptions]="filtreDate" field="date"
                                [showMenu]="true"></p-columnFilter>`

**Current behavior**
Display a p-calendar component using the default date format.

**Expected behavior**
Should display a p-calendar component using the date format specified

**Minimal reproduction of the problem with instructions**
The problem is in the p-columnFilterFormElement component who does not share the format with the p-calendar component in the switch over the type.

**What is the motivation / use case for changing the behavior?**
Bug fix

**Please tell us about your environment:**

* **Angular version:** 11.2.3

* **PrimeNG version:** 11.3.1

* **Browser:** all
 
* **Language:** all

* **Node (for AoT issues):** `node --version` =   12.14.1

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
