### ISSUE TITLE
AutoComplete does not display 0 as value when preselected

### ISSUE THREAD

**Issue by Timmeeeey** [primefaces/primeng#10031]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-autocomplete-demo-w4apqj

**Current behavior**
When using AutoComplete with objects and a numeric value then objects with value 0 are not displayed when preselected.
This is because 0 is a falsy value and therefore it is ignored in the first line of `updateInputField()`.

```
updateInputField() {
  let formattedValue = this.value ? (this.field ? ObjectUtils.resolveFieldData(this.value, this.field)||'' : this.value) : '';
  ...
}
```

I solved this by replacing `||` with `??`.

This is related to but not solved by #9628.

**Expected behavior**
When an object with value 0 (e.g. `{ name: 'test', value: 0}`) is preselected then 0 should be displayed.

* **Angular version:** 11

* **PrimeNG version:** 11

**Comment by yigitfindikli** [comment]
Hi @Timmeeeey,

Thanks for your suggestion, unfortunately '??' is not compatible with IE 11.
