### ISSUE TITLE
Error: Not working option "group" in p-listbox

### ISSUE THREAD

**Issue by angeltg83** [primefaces/primeng#10039]
![err-list-box](https://user-images.githubusercontent.com/8096392/112352658-f21f7e80-8c98-11eb-8ccf-34922aecf651.png)

 this.groupedCities = [
      {
        label: "Germany",
        value: "de",
        items: [
          { label: "Berlin", value: "Berlin" },
          { label: "Frankfurt", value: "Frankfurt" },
          { label: "Hamburg", value: "Hamburg" },
          { label: "Munich", value: "Munich" }
        ]
      },
      {
        label: "USA",
        value: "us",
        items: [
          { label: "Chicago", value: "Chicago" },
          { label: "Los Angeles", value: "Los Angeles" },
          { label: "New York", value: "New York" },
          { label: "San Francisco", value: "San Francisco" }
        ]
      },
      {
        label: "Japan",
        value: "jp",
        items: [
          { label: "Kyoto", value: "Kyoto" },
          { label: "Osaka", value: "Osaka" },
          { label: "Tokyo", value: "Tokyo" },
          { label: "Yokohama", value: "Yokohama" }
        ]
      }
    ];

help!!

**Comment by angeltg83** [comment]
![html-list](https://user-images.githubusercontent.com/8096392/112353004-4a568080-8c99-11eb-9a90-9d16e1219fa8.png)

**Comment by angeltg83** [comment]
please!! help your..

regards,
At.

**Comment by yigitfindikli** [comment]
Please use the forum for questions or help requests.

**Comment by angeltg83** [comment]
please with link the forum..

regards,
At.
