### ISSUE TITLE
<p-editor /> is writing an object when empty

### ISSUE THREAD

**Issue by TCMiranda** [primefaces/primeng#1003]
Hey guys

I couldn't find the reason why is the rich text editor writing an empty object to my model when empty.
I have just updated my packages, including Quill

_What I see when not empty is:_
`<p>something</p>`

_What I see when empty:_
`{}`

My code is just:

```
<p-editor
  [(ngModel)]="model.employee_summary">
</p-editor>
```

I am sure that no other components are writing to its attribute.
Could it be something else on my environment causing the misbehavior?

Using Angular2 - 2.0.1, Webpack, Babel6

Thanks!

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
