### ISSUE TITLE
p-treenode component doesn't apply p-treenode-content-selected class on selected item

### ISSUE THREAD

**Issue by chekit** [primefaces/primeng#10034]
**I'm submitting a ...** 
```
[x] bug report
[ ] feature request
[ ] support request
```
**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-treeselection-issue-report?file=src/app/app.component.ts

**Current behavior**
If we want to define preselected item or even if we select one by clicking it on we are getting it highlighted by populating class list with `p-highlight` css class, but not with `p-treenode-content-selected` as stated in documentation. Even if you check the base component (for example https://github.com/primefaces/primeng/blob/master/src/app/components/tree/tree.ts#L26) there won't be any `p-treenode-content-selected` class.

> For example in version 6.1.3 it was `ui-treenode-content-selected`:  `'ui-treenode-content-selected':isSelected()}`

**Expected behavior**
`p-treenode-content-selected` is added to selected item. Or documentation should be updated with appropriate class pointed for selected item.

**What is the motivation / use case for changing the behavior?**
To have behavior according to documentation

**Please tell us about your environment:**
- Windows 10
- Visual Studio Code

* **Angular version:** 11.2.5

* **PrimeNG version:** 11.3.1

* **Browser:** Chrome 89
 
* **Language:** TypeScript 4.1.5

* **Node (for AoT issues):** `node --version` =  v14.16.0

**Comment by yigitfindikli** [comment]
Thanks for your report.

Fixed in https://github.com/primefaces/primeng/commit/f9ff1b6a3a442610a073835df3c193206896b7ad
