### ISSUE TITLE
Add a spinner or loading message into dropdown component

### ISSUE THREAD

**Issue by sechouaya** [primefaces/primeng#10038]
Hello ,

Could you take in consideration adding a spinner or a loading message into dropdown component when using a lazy loading .

Thanks .

**I'm submitting a ...**
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Comment by sechouaya** [comment]
Any news regarding this request .

**Comment by Jacques-eMediaIT** [comment]
> Any news regarding this request .

You can use:

[dropdownIcon]="isLoading ? 'pi pi-spinner pi-spin' : 'pi pi-chevron-down'"

From https://github.com/primefaces/primeng/issues/5052

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
