### ISSUE TITLE
Picklist dragdrop input can't disable drag and drop

### ISSUE THREAD

**Issue by ramonvanbezouw** [primefaces/primeng#10037]
**Issue**
Docs specify the `dragdrop` input for enabling / disabling drag and drop for the Picklist component:

dragdrop | boolean | false | Whether to enable dragdrop based reordering.
-- | -- | -- | --

This feature does not work.

**Expected behavior:**
Setting `[dragdrop]="false"` on `<p-picklist>` should disable drop behaviour for the items.

**Actual behavior:**
Drag and drop of items in `<p-picklist>` always works, regardless of the setting.

**Minimal reproduction of the problem with instructions**
In the showcase change ` [dragdrop]="true"` to ` [dragdrop]="false"`, drag will still work.

**Proposed fix:** (PR: #10036)
The dragdrop Input is not being used by the component. Adding `[cdkDropListDisabled]="!dragdrop"` to the source and target `cdkDropList`, the dragdrop input works as expected.

Fix was tested in Windows Chromium 89, Windows Firefox 87, iOS Safari 14.

**Comment by cm-noesis** [comment]
I was also looking for this. If the picklist is disabled, drag&drop is still allowed.
