### ISSUE TITLE
Button click not working in p-toolbar

### ISSUE THREAD

**Issue by rickdecker** [primefaces/primeng#10040]
After upgrading Ultima Template to latest version with Primeng 11.3 I noticed a strange behavior with1 button on the p-toolbar not firing.  However, it did work while clicking on the button in debug mode.   It appears if you have primeng toolbar with left-group and right-group, In the right-group the right most button will not work.  Was able to create this action in several components in my application.   It appears to be a Primeng  then an Ultima template issue.   I was going to send you some code but found an working example in Primeng Demo Table CRUD.  The Import works but the Export does not.  If duplicate the the Export button on the component you will see the Export to left works but the one at the end (right) does not.  Awesome Primeng components and Templates!

**Comment by yigitfindikli** [comment]
Hi @rickdecker,

This repo there are for core PrimeNG issues or feature requests. You can use the [ultima-ng ](https://forum.primefaces.org/viewforum.php?f=45)forum for this issue.
