### ISSUE TITLE
Table State - Value is not displayed in multiselect label

### ISSUE THREAD

**Issue by ProfEibe** [primefaces/primeng#10046]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Saving a filter-value with state in local- or session-storage is working great.
The problem is with the multi-select filter. After page-reload the value is taken correctly and the filter is set, but the selected elements are not shown in the Form-Input Element (without dropdown).

I have an stackblitz example here:
https://stackblitz.com/edit/primeng-tablestate-demo-qbhqfw?file=src/app/app.component.html

Reproduce:
Selete one or more elements. They are now listed in the form. But after page-reload only the placeholder is shown. In my private project it even shows 'empty' instead my placeholder and I don't know why.
Also the ```[ngModel]="value"``` has the correct data, but it is not displayed

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
