### ISSUE TITLE
Clear button doesn't work correctly on Multiselect component

### ISSUE THREAD

**Issue by mjohnny44** [primefaces/primeng#10049]
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Type anything in multi select component and try to remove it by clicking on x button. It's not clearing input just hide its modal. 

**Expected behavior**
Clicking on x button should remove input in multi select and not hide its modal.

**Minimal reproduction of the problem with instructions**
1. Go to primeNG docs site: https://primefaces.org/primeng/showcase/#/multiselect
2. Click on the first multiselect
3. Type 'Rom' and then click x button

**What is the motivation / use case for changing the behavior?**
It's not working correctly

* **Angular version:** 5.X
11.2.5

* **PrimeNG version:** 5.X
^11.3.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome Version 89.0.4389.90 (Official Build) (x86_64)
Safari Version 14.0.3 (16610.4.3.1.4)
Firefox 87.0 (64-bit)
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 4.1.5

* **Node (for AoT issues):** `node --version` =   
v10.23.2

**Comment by yigitfindikli** [comment]
The current behavior is correct. X icon there is for closing.

**Comment by EngAhmedShehatah** [comment]
how can i (as a developer) use this close icon to clear selected items ?

**Comment by hugovlc** [comment]
This behavior does not make any sense. All the other third party providers have a button to clear the selection.
Is very annoying to have to do 2 clicks in order to clear the list. Is there anything in the roadmap to do this?

**Comment by hugovlc** [comment]
> how can i (as a developer) use this close icon to clear selected items ?

I overwrote the behaviour to close it.
