### ISSUE TITLE
Global filter 

### ISSUE THREAD

**Issue by kumar0906** [primefaces/primeng#10054]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

[Stackblitz](https://stackblitz.com/edit/primeng-treetablefilter-demo-7qiml8?file=src/assets/filesystem.json)

**Current behavior**
Global Filters doesn't fetches all the records from primeng treetable. For ex. If we search for 'Temperature'(https://primeng-treetablefilter-demo-7qiml8.stackblitz.io/) it fetches only one record where as there is one more record that misses out. In the first record 'Temperature' is present in two columns and in second record ' Temperature' is present only in first column. If we modify the value in second row second column value to 'Temperature' then Global filter fetches both records.    

**Expected behavior**
Global filter should fetch all the records from tree table even if it matches a single cell value with filter criteria.

**Minimal reproduction of the problem with instructions**
search on the Global filter with filter criteria('=Temperature)

**What is the motivation / use case for changing the behavior?**
n/a

**Please tell us about your environment:**
Stackblitz provided above

* **Angular version:** 5.X
11.1.4

* **PrimeNG version:** 5.X
11.2.0.tgz

**Comment by yigitfindikli** [comment]
Issue is not clear, please feel free to reopen with a stackblitz example.
