### ISSUE TITLE
Carousel does not always display dynamically added items

### ISSUE THREAD

**Issue by szape89** [primefaces/primeng#10051]
**I'm submitting a ...** 
```
[x] bug report
[ ] feature request
[ ] support request
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-carousel-bug

**Current behavior**
Carousel does not always display dynamically added items.

**Expected behavior**
Carousel should always display added items.

**Minimal reproduction of the problem with instructions**
- Configure 3 items per page and 3 items to scroll.
- Have 5 items in the carousel.
- Scroll to the end to see updates.
- Add new item to the carousel: 6th item is not displayed.
- Add new item to the carousel: both 6th and 7th item are displayed.

**Angular version:** 11.x.x (tested: 11.0.9 and 11.2.0)

**PrimeNG version:** 11.x.x (tested: 11.2.3 and 11.3.0)

**Browser:** Chrome, Firefox

**Comment by nishant203** [comment]
Hi @yigitfindikli 
The PR https://github.com/primefaces/primeng/pull/10073 fixes the bug. 

P.S. - This will be my first open source contribution if the PR gets accepted :)

**Comment by yigitfindikli** [comment]
Hi @nishant203,

You're PR gonna accepted :)
