### ISSUE TITLE
Icon support for TriStateCheckBox

### ISSUE THREAD

**Issue by davisb10** [primefaces/primeng#10052]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

Unable to change the classes for the True and False icons

**Expected behavior**

Ability to change the icons of the True and False states in the same way the standard Checkbox icon allows.

**Comment by iuribezerra** [comment]
#10072
