### ISSUE TITLE
Column resize and reorder support for Scrollable DataTable

### ISSUE THREAD

**Issue by ctrl-brk** [primefaces/primeng#1005]
DataTable. As soon as you set scrollable="true" you can't resize or reorder. Just nothing happens. Cursor changes but that's it.
If you don't specify 'scrollable' but set both resizableColumns & reorderableColumns to true - the behavior is weird. It kinda works but to resize you have to click, than start dragging than release mouse, than move to the position, thank click... Not what you would expect.

**Comment by cagataycivici** [comment]
Resize and Reorder are not supported for Scrollable table but we'll work on it for 1.0 final.

**Comment by jayeffaar** [comment]
Hi. Any update on when we can expect this fix now? We can't release without a scrollable table, but we also need adjustable column widths.

**Comment by cagataycivici** [comment]
This is delayed after 1.0 final which is due next week. We only do bug fixes now until then. Our expectation is at most end of november for this functionality. If you consider PrimeNG PRO support service that will speed up the process, if not end of november is the plan on our side.

**Comment by jayeffaar** [comment]
Thanks for the update!

**Comment by listerp** [comment]
Any update on when this will be done?

**Comment by stavn1** [comment]
would also appreciate to have this feature!

**Comment by sittingbool** [comment]
Any update on this? I really need this to work

**Comment by Sizzahandz** [comment]
Let's kick up some dough and make it worth it for these guys to move faster.  I think it's worth it ill support.

**Comment by dpac4u** [comment]
Any update on this? We need it badly. Thanks in advance ..

**Comment by Sizzahandz** [comment]
It's coming yay!! PrimeNG rules!

-
Sizzahandz
CEO Crooklyn Clan Inc.
www.crooklynclan.net

**Comment by mikebm** [comment]
This was supposedly fixed in 4.0.3 but it is still busted. Resizing the window will now correctly align the columns to the grid row columns, but resizing doesn't work at all. Re-ordering doesn't work at all.

If [scrollable]="true" is removed, then resizing works. Regardless of [scrollable]="true" reordering doesn't work at all.

[responsive]="true" is also completely busted when scrollable is enabled. It smashes everything into like 75-100 pixels.

My grid configuration:
                    [value]="$records | async"
                    dataKey="UniqueKey"
                    [rowTrackBy]="trackBy"
                    [selection]="ds.currentRecord"
                    [resizableColumns]="true"
                    [reorderableColumns]="true"
                    [responsive]="true"
                    selectionMode="single"
                    [scrollable]="true"
                    [lazy]="true"
                    [totalRecords]="$totalRecordCount | async"
                    [rows]="rows"
                    [virtualScroll]="true"
                    scrollHeight="450px"
                    [loading]="$loading | async"
                    (onLazyLoad)="loadData($event)"
                    (onRowSelect)="selectRow($event)"

**Comment by huineng** [comment]
indeed scrollable in combination with resize 'expand' and 'fit' works, reorder doesn't work at all

**Comment by ARandomDude** [comment]
@huineng: I'm experiencing the same behavior.
