### ISSUE TITLE
Scroll Panel hides bottom content in FireFox (since PrimeNG v10)

### ISSUE THREAD

**Issue by nkerr** [primefaces/primeng#10053]
**I'm submitting a ...**  
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://primefaces.org/primeng/showcase/#/scrollpanel
View your showcase demo (scrollpanel) in FireFox 87.0 (64-bit) on Windows.

**Current behavior**
You will notice that it is impossible to scroll to the very bottom of the scrollpanel in FireFox. 
The last line of content is almost entirely hidden from view:
![image](https://user-images.githubusercontent.com/791075/112892631-8d549180-90a7-11eb-95ff-fa50ef239b60.png)

The issue appears to be caused by the 18px that are added to the height of p-scrollpanel-content:
![image](https://user-images.githubusercontent.com/791075/112893038-22578a80-90a8-11eb-9407-c161e0553d9b.png)

Changing the CSS to be 100% for height appears to resolve the problem in FireFox (but breaks Chrome):
![image](https://user-images.githubusercontent.com/791075/112893204-5c289100-90a8-11eb-93f6-26a12aa21262.png)

**Expected behavior**
It should be possible to reveal the bottom of the scrolling content by dragging the scrollbar to the bottom of its track, even when using FireFox.

**Minimal reproduction of the problem with instructions**
View your showcase demo (scrollpanel) in FireFox 87.0 (64-bit) on Windows and attempt to scroll to the bottom of the scrollable content:
https://primefaces.org/primeng/showcase/#/scrollpanel

**What is the motivation / use case for changing the behavior?**
Scrollpanel is fundamentally broken in Firefox in version 10+ of PrimeNG.

**Please tell us about your environment:**
Windows 10, FireFox 87.0 (64bit)

* **Angular version:** 11.2.2
* **PrimeNG version:** v10.1.0-lts and v11.3.1
* **Browser:** [ Firefox 87.0 ]
* **Language:** [TypeScript 4.0.5]
* **Node (for AoT issues):** `node --version` =  v12.18.0

**Comment by ES-Six** [comment]
Encountered this too with primeng version : 13.4.1

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
