### ISSUE TITLE
Change global configuration for calendar

### ISSUE THREAD

**Issue by kkovac1** [primefaces/primeng#10059]
This is not yet merged?
I really need to change dateformat from mm/dd/yyyy to dd/mm/yyyy when using p-columnfilter

![image](https://user-images.githubusercontent.com/75999845/113144744-e1897e00-922d-11eb-955e-4c47c129dbaf.png)

But there is a PR waiting as I see
https://github.com/primefaces/primeng/pull/9387

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
