### ISSUE TITLE
In the safari browser, Incorrect search characters in dropdown input box

### ISSUE THREAD

**Issue by hjc0826** [primefaces/primeng#10062]
In the safari browser, the dropdown search box will automatically enter English characters in the input box when inputting through the Chinese input method, and superimpose

The official website also has this problem

**Comment by yigitfindikli** [comment]
![image](https://user-images.githubusercontent.com/19997575/113256376-c708e080-92d1-11eb-8a06-053679063c5c.png)

Unable to replicate with latest PrimeNG, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
