### ISSUE TITLE
p-picklist drag and drop not working correctly with filtered item

### ISSUE THREAD

**Issue by fabioportieri** [primefaces/primeng#10067]
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

from the ufficial showcase
https://www.primefaces.org/primeng/showcase/#/picklist
if i type Bamboo and proceed to drag and drop the item, another item will be dropped instead!

**Expected behavior**
the selected item should be dropped in the target list

* **PrimeNG version:** 
11.3.0 - 11.3.1

**Comment by yigitfindikli** [comment]
Fixed in https://github.com/primefaces/primeng/issues/10048

**Comment by fabioportieri** [comment]
thank you for the great work
