### ISSUE TITLE
Global filter not fetching matching data

### ISSUE THREAD

**Issue by kumar0906** [primefaces/primeng#10066]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

[Stackblitz](https://stackblitz.com/edit/primeng-treetablefilter-demo-7qiml8?file=src/assets/filesystem.json)

Current behavior
If you use term 'temp' in the global filter in the stackblitz provided above, you will get only one result:
![image](https://user-images.githubusercontent.com/81545113/113287337-115a8380-930b-11eb-93b1-b9f43d189ea3.png)

If you use term 'temp' in the 'Name' column filter in the same stackblitz, you will get two results:

image
![image](https://user-images.githubusercontent.com/81545113/113287373-20d9cc80-930b-11eb-9852-9888dd586a70.png)

It looks like if the value that if being searched via global filter is being found in multiple columns, it will return only the rows where the value is being found in all the columns.
Expected behavior: the global filter should return two rows too.

Expected behavior
Global filter should fetch all the records from tree table even if it matches a single cell value with filter criteria.

Minimal reproduction of the problem with instructions
search on the Global filter with filter criteria('=Temperature)

What is the motivation / use case for changing the behavior?
n/a

Please tell us about your environment:
Stackblitz provided above

Angular version: 5.X
11.1.4

PrimeNG version: 5.X
11.2.0.tgz

Also find the [link](https://github.com/primefaces/primeng/issues/10054) of issue which got closed due to insufficient details

**Comment by RomainLefeuvre** [comment]
Hello,
It seems that the problem is similar to the one I reported: 
https://github.com/primefaces/primeng/issues/9281
Sincerly,
Romain

**Comment by RomainLefeuvre** [comment]
@kumar0906 If you found a workaround I'm interested.

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
