### ISSUE TITLE
[Question] How do you manage the different versions in the deployed showcase 

### ISSUE THREAD

**Issue by dlarr** [primefaces/primeng#10060]
Is it just one big app hosted ?
Do you have as many showcases as versions hosted, the selecting a version just serves different app through DNS ?

I am curious about this, because sharing librairies includes that kind of features with the version selectionnable it's just perfect
* Demo
* Docs

I just don't know how to realize this.

**Comment by yigitfindikli** [comment]
Hi @dlarr,

Actually, every version is a different app.

**Comment by dlarr** [comment]
Right thank you for answering, but then 

When you're here : https://www.primefaces.org/primeng/v4.3.0/#/inputgroup

How come there are all superior versions ?
