### ISSUE TITLE
Picklist - Ability to disable double click to transfer 

### ISSUE THREAD

**Issue by dasco144** [primefaces/primeng#10064]
**I'm submitting a ...** 
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**What is the motivation / use case for changing the behavior?**
I have a number input with showButtons enabled.
![image](https://user-images.githubusercontent.com/10575019/113254458-e4847d00-92c6-11eb-80a7-8c18aba35561.png)
When clicking too fast on these buttons the double click functionality is invoked on the picklist item and the item is transferred to the other list. I have tried cancelling the event but from what I have checked in the current code, it doesn't look like cancelling the event would prevent this.

**Please tell us about your environment:**
Windows 10
VSCode
npm

* **Angular version:** 11.2.7

* **PrimeNG version:** 11.3.1

* **Browser:** all

 
* **Language:** TypeScript 4.1.5

* **Node (for AoT issues):** `node --version` =  v12.20.1

**Comment by john8329** [comment]
Being not a documented feature it took me 20 minutes to realize that a rapid click in a field was triggering the removal of the element with this event. It'd be really nice to be able to disable it or at least know it's there from the docs.

**Comment by ashub1118** [comment]
Any update on this. how can we disable transfer of items on double clicks

**Comment by sujeetjaiswara** [comment]
Any update for this feature?

**Comment by dasco144** [comment]
It would be nice to get some feedback on this from the repo maintainers. @yigitfindikli
If there any adjustments I need to make to my MR let me know 👍
I will try resolve the conflicts on the MR later today

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by jorda24** [comment]
still can't find any documentation about it, can anyone help?
