### ISSUE TITLE
Table sort multiple not working when lazy

### ISSUE THREAD

**Issue by yelhouti** [primefaces/primeng#10069]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
When using sort multiple the MultiSort Metadata only sort with one column.
I suspect this is the case only also for non lazy as when clocking on a column in https://primefaces.org/primeng/showcase/#/table/sort only number 1 is used (you can't enable many columns).

**Expected behavior**
Multi sort to work.

**Minimal reproduction of the problem with instructions**
https://primefaces.org/primeng/showcase/#/table/sort

this used to work on some old version...

**Comment by yigitfindikli** [comment]
I couldn't replicate it. 
![image](https://user-images.githubusercontent.com/19997575/113395788-12d78a80-93a3-11eb-9132-688fea99c8fc.png)

**Comment by fbaldo31** [comment]
Same issue here using Chrome : demo is not working for multisort

**Comment by yelhouti** [comment]
You need to shift click or Ctrl click I don't remember.
