### ISSUE TITLE
MultiSelect - Input Component

### ISSUE THREAD

**Issue by ersandeepranjit** [primefaces/primeng#1006]
[formControl] is not  working as expect , didn't validate the required filed 
`this.apiAccessForm = this._formBuilder.group({
                "routeApi": ['', Validators.required],
                "roleName": ['', Validators.required],
                "active": ['']
            }
        );`

`<p-multiSelect [options]="objRoleList"
                               formControlName="roleName"
                               [(ngModel)]="objApiAccess.roleName"></p-multiSelect>`

```
```

**Comment by leoxgnr93** [comment]
Same issue here, 
whenever I try to validate an  multiselect does not validate it even  using minLength

**Comment by ric-cardo** [comment]
i had the same issue. i solved it by using a custom validator function instead of validators.required; 

```javascript
    multiSelectRequired(): ValidatorFn {
        return (control: AbstractControl): {[key: string]: any} => {
            const selections = control.value;
            const isValid = selections.length > 0;
            const msg = 'selection required';
            
            return isValid ?  null : {'multiSelectRequired': {msg}};
        };
    }

this.myForm = this._formBuilder.group({  
          'locations':[model.locations,this._multiSelectService.multiSelectRequired()],
      });
```

**Comment by cagataycivici** [comment]
A custom validator seems to be necessary for MultiSelect.
