### ISSUE TITLE
No cancel callback in p-confirmPopup (willing to help out)

### ISSUE THREAD

**Issue by arnochauveau** [primefaces/primeng#10071]
**I'm submitting a ...**  (check one with "x")

- [ ] bug report => Search github for a similar issue or PR before submitting
- [x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
- [ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

Hi, 

First of all thank you for maintaining the library! 

Currently when using a `p-confirmPopup` there is no option to provide a callback for the **cancel** action (for example when the user clicks next to the popup). 

We have a backdrop overlay that needs to be hidden on either action, including a click next to the popup. This is only one use case but I'm sure there are more. So I believe this would be a useful addition to the library. 

**I'm more than happy to help out with this feature by opening a PR if you are open to that.**

Thanks in advance!

**Comment by moussa-b** [comment]
This is how I managed to call my callBack when the `p-confirmPopup` get closed : 
1. HTML side, identify the `p-confirmPopup` with a templateRef
`<p-confirmPopup #confirmPopup></p-confirmPopup>`
2. In the component's typscript add `implements AfterViewInit`
3. In the component's typscript add ViewChild declaration `@ViewChild('confirmPopup') confirmPopup: ConfirmPopup;`
4.In the component's typscript add in the fonction `ngAfterViewInit` add this code : 

```
ngAfterViewInit(): void {
  this.confirmPopup.hide = function() {
    yourCallBack();
    this.visible = false;
  };
}
```

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
