### ISSUE TITLE
In the safari browser, the input event that searches for input through the Chinese input method in the dropdown component drop-down search box will continue to be punished

### ISSUE THREAD

**Issue by hjc0826** [primefaces/primeng#10070]
In the safari browser, the input event that searches for input through the Chinese input method in the dropdown component drop-down search box will continue to be punished

The official website also has this problem, and it is the latest version

[stackblitz](https://stackblitz.com/edit/github-kwzqsj-i2vmnn?file=src%2Fapp%2Fapp.component.html)

**Comment by yigitfindikli** [comment]
I couldn't replicate it.
![image](https://user-images.githubusercontent.com/19997575/113416278-a58b2000-93c9-11eb-95e4-2f6669f71e2a.png)
