### ISSUE TITLE
p-Table: Filters w/ lazy loading.  Clicking "Add Rules" in filter menu fires off load event.

### ISSUE THREAD

**Issue by briangullo** [primefaces/primeng#10075]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
I'm using a p-table with lazy loading and filters (using built in menu).   When the user clicks "Add Rule" this fires off the lazy load event to reload the data. There does not seem to be a straight forward way to ignore this event.

**Expected behavior**
When using the filter menu, lazy load event should only be called when "Apply" or "Clear" is clicked.

**What is the motivation / use case for changing the behavior?**
Excessive calls against the database.  

**Please tell us about your environment:**
Angular version: 11.0.5

TypeScript: 4.2.3

PrimeNG version: 11.2.3

Browser: [Chrome 89]

**Comment by yigitfindikli** [comment]
This is expected behavior. When the user clicks the add rule button then the table trying to filter with the first rule.
