### ISSUE TITLE
Unable to compile the project: Unexpected value 'ButtonModule' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by BRsmover** [primefaces/primeng#1007]
I have an Angular 2.0.1 program with Angular CLI and AOT compilation + PrimeNG 1.0.0 Beta 17. You can find it here: https://github.com/BRsmover/angular2-primeng-problem

If I compile it, I get the error message below (Attached file). Can someone tell my, what's the problem or if it's my own fault? I've followed the getting started tutorial.

[output.txt](https://github.com/primefaces/primeng/files/506036/output.txt)

**Comment by adrienverge** [comment]
@BRsmover primeng is not AOT-compatible yet. See #1004 for a potential solution.

**Comment by BRsmover** [comment]
Thank you for your answer @adrienverge. I'll check it out.

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with them and if issue persists drop a comment and we'll reopen.
