### ISSUE TITLE
Feature Request: Upgrade to ChartJS 3

### ISSUE THREAD

**Issue by KeithGillette** [primefaces/primeng#10078]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
`p-chart` requires `chart.js^2.7`

**Expected behavior**
`p-chart` requires `chart.js^3.0`

**What is the motivation / use case for changing the behavior?**
[Chart.js 3.0](https://www.chartjs.org/docs/latest/getting-started/v3-migration.html) supports tree-shaking for smaller bundle sizes, as well as multiple bug fixes and performance improvements.

**Comment by s4m0r4m4** [comment]
Also, the setup instructions for charts says to run `npm install chart.js --save`, which doesn't work because it installs v3.1.1, not the required version of 2.7.x. At a bare minimum the setup instructions should be updated: https://www.primefaces.org/primeng/showcase/#/chart or just update to the latest version.

**Comment by kek-Sec** [comment]
docs remain outdated and support only available for 2.7.3

**Comment by denes16** [comment]
Any updates on this?. The 3 version has new features and better performance

**Comment by satoshisound** [comment]
Could definitely use 3 for a project I am working on... pretty please. :)

**Comment by MVDeveloper1** [comment]
We really need this update.

**Comment by jellemdekker** [comment]
I'm currently attempting to do the update myself in #10438 if anyone wants to help out.

**Comment by jellemdekker** [comment]
Looks like this is on its way: #10452

**Comment by KeithGillette** [comment]
Working since release 12.1. Thanks!
