### ISSUE TITLE
p-columnfilter multiple instances on same field

### ISSUE THREAD

**Issue by Hafnernuss** [primefaces/primeng#10074]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
[Stackblitz](https://primeng-tablefilter-demo-bqpevt.stackblitz.io)

**Current behavior**
When creating a second column filter for the same field, the behaviour of the filter is weird/undefined, and the log prints the following error:
`preview-e2b44a68570359ddfd71b.js:1 ERROR Error: Cannot find a differ supporting object '[object Object]' of type 'object'. NgFor only supports binding to Iterables such as Arrays.`

**Expected behavior**
Simply a second, working column filter.

**Minimal reproduction of the problem with instructions**
In the posted stackblitz, app.component.html, lines 20 and 21

**What is the motivation / use case for changing the behavior?**
When developing with responsiveness in mind, filters could be shown as `row` on larger devices and as `menu` on smaller devices. No matter how you try this (hiding via responsive css classes, or completly removing from the DOM with `*ngIf`, or changing the `display` property dynamically via property, the error is always the same.

* **Angular version:** 
Angular: 11.0.0

* **PrimeNG version:** 
Prime: 11.3.0

* **Browser:** 
At least chrome, but I suspect this is an issue directly with prime.

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
