### ISSUE TITLE
support single dialogservice to open dialog in dialog scenarios

### ISSUE THREAD

**Issue by kongshu612** [primefaces/primeng#10088]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

We have a component poped up by some dialogservice instance, in this component, we may have some requirements to open another dialog component above this. But if we use the same dialogservice instance, we will loose the reference of the first component. we will be met with issue when we close this.

Current workaround is we inject another isolated dialogservice instance to achieve this behavior.

**Expected behavior**

We hope dialogservice is not per component. we can use the same service intance to open multi components at the same time

**Please tell us about your environment:**

* **Angular version:** 9.1.0

* **PrimeNG version:** 9.1.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript 3.8.3 | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =  8

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
