### ISSUE TITLE
p-autoComplete adds "searchBox" role attribute to child input element, which is not supported by JAWS, particularly in IE11

### ISSUE THREAD

**Issue by b-fisher** [primefaces/primeng#10082]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
No need to illustrate using stackblitz as we can easily reproduce the issue by looking at the autocomplete documentation here: https://www.primefaces.org/primeng/showcase/#/autocomplete

**Current behavior**
Steps:
- Please access https://www.primefaces.org/primeng/showcase/#/autocomplete using IE11
- Open up JAWS
- Tab to the "Basic" usage of p-autocomplete
- Tab to the next form control
- Shift-tab back to the "Basic" form control

Actual Results:
- When we tab back to the "Basic" p-autocomplete form control, JAWS reads out the description of the previous form control, not the current one.  In fact JAWS will never read out the description of the "Basic" form control, only the previous input element you focused on.

Cause:
- The reason for this is because when we create a basic p-autocomplete, i.e. we don't configure it as a drop down, grouped, or multiple type, PrimeNG creates a child input element and gives it a "role" attribute with value "searchbox".
- JAWS doesn't support the "searchbox" role.  See here: https://freedomscientific.github.io/VFO-standards-support/aria.html
- The fix is very simple, just remove the "searchbox" role in this case.  No role is needed at all.
- By omitting the role, this input will implicitly be treated as a textbox since this input element has a type of text.  See here: https://w3c.github.io/aria/#textbox.  Note the textbox role of course isn't needed as it would otherwise be redundant, so removing it entirely addresses it.

**Expected behavior**
On navigating to/from a "Basic" type of p-autocomplete component, i.e. one that isn't a drop down, grouped, or multiple type, the description of the "Basic" element should be read by JAWS.  This is most prominent when using IE11.

**Minimal reproduction of the problem with instructions**
Please see steps above

**Please tell us about your environment:**
Windows 10, IE11, JAWS 18

* **Angular version:** 11.0.9

* **PrimeNG version:** 11.3.1

* **Browser:** IE11

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
