### ISSUE TITLE
Clear filter does not clear the global filter

### ISSUE THREAD

**Issue by Gaurang2811** [primefaces/primeng#10089]
If we clear all the active filters using the clear method of Table, 
* It clears all the active column filters
* It does not clear the global filter
* Pagination is also breaking

Screenshots from the documentation( https://www.primefaces.org/primeng/showcase/#/table/filter).
added global filter for **prop**. now we have filtered records( count: 29)
![image](https://user-images.githubusercontent.com/20419166/113972156-cd5e0600-9857-11eb-92da-b5d3525a8a21.png)
after clicking on clear button ( filler is not clear and pagination also incorrect)
![image](https://user-images.githubusercontent.com/20419166/113972191-dfd83f80-9857-11eb-9d15-5740f41f0eb4.png)
filtered records were 29 if we jump to 4th page:
![image](https://user-images.githubusercontent.com/20419166/113972345-157d2880-9858-11eb-9e47-4fec35e46537.png)

Ideally, it should remove filters from the global filter also and pagination should not break.

* **Angular version:** 10.X
* **PrimeNG version:** 5.X
* **Browser:** all

**Comment by ProfEibe** [comment]
As a workaround you could reset the global filter manually like this.
Add the following to the clear-method:
```javascript
clear(table: Table) {
    table.filters.global = {
      value: null,
      matchMode: "contains",
      operator: "and"
    };
    table.clear();
  }
``` 

This should overwrite the current global filter with a null value. Pagination is working too on my side.

**Comment by Gaurang2811** [comment]
Thanks, This resolves the issue with the pagination and data.
But not sure why the input box still has the text.

I have added a small trick to clear the input box value.
Passed the reference of globalFilter input element and on component and added **globalFilter.value = null**

html:
```
<button pButton label="Clear" (click)="clear(dt, gb)"></button>
<input pInputText type="text" #gb (input)="dt.filterGlobal($event.target.value, 'contains')" />
```
Component:
```
  clear(table: Table, globalFilter) {
    globalFilter.value = null;
    table.filters.global = {
      value: null,
      matchMode: 'contains'
    }
    table.clear();
  } 
```
