### ISSUE TITLE
[Enhancement] Optimize the official documentation for search engines

### ISSUE THREAD

**Issue by pascalporedda** [primefaces/primeng#10083]
[x ] feature request

**Current behavior**

Whenever I'm googling for a PrimeNG component like "primeng autocomplete" for example, the first result on Google is the "PrimeNG Angular UI Component Library" website, which is at least something.

**Expected behavior**
I would expect to be able go navigate to the component documentation directly from google, like all other component libraries do. It's really annoying to open the PrimeNG website, click on documentation and go to the according component.

I guess working on SSR for these components (like the stuff that's on your roadmap would probably spill into this).

**What is the motivation / use case for changing the behavior?**
Probably every developer that uses PrimeNG would benefit from this. It's just a nice to have, but good for the SEO of PrimeNG as well.

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
