### ISSUE TITLE
p-editor - HTML binding fails

### ISSUE THREAD

**Issue by dloprodu** [primefaces/primeng#10081]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When we have some browser extension, like Grammarly, the HTML binding fails, as you can see in the image below,

![image](https://user-images.githubusercontent.com/664947/113733455-64a94900-96f2-11eb-97e6-5d335220fbb8.png)

**Expected behavior**
The HTML binding should work, even if the user has some extension for the text areas installed.

**Please tell us about your environment:**

* **Angular version:** 11.2.0

* **PrimeNG version:** 11.3.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.3.2, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Comment by dloprodu** [comment]
@yigitfindikli the issue persists. The problem is the higlighted line in red in your code. You have to select by class, no select the first element. I think the problem is very clear.

![image](https://user-images.githubusercontent.com/664947/116528585-e8122080-a8d3-11eb-88f6-47ba9720665e.png)
