### ISSUE TITLE
PanelMenu: add separator as top level panel

### ISSUE THREAD

**Issue by jBuchholz590** [primefaces/primeng#10080]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```

**Current behavior**
`MenuModel` provides a way to define a separator for a menu. In panelmenu this is only available for submenus (i.e. in `PanelMenuSub`-component). When used as a top level panel it is rendered as an empty (clickable) panel.
It would be nice to be able to use the separator as would be expected on all hierarchies.

**Workaround**
Use `styleClass` to append a class that
* hides the `<a>` tag within the `p-panelmenu-header` of the `p-panelmenu-panel` and 
* style the separator appropriatly (e.g. setting background-color and height)

* **Angular version:** 11.X

* **PrimeNG version:** 11.3

* **Browser:** Chrome 89

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
