### ISSUE TITLE
Bug Report: tabMenu progomatically changing MenuItem 'disabled' property does not have visual affect until one of the tab is clicked

### ISSUE THREAD

**Issue by Alexandre791** [primefaces/primeng#10091]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-m7xmwy-jktl6v

**Current behavior**
MenuItem 'disabled' flag is toggled (through the 'Toggle Disabled' button in the example), but there is no visual affect. (if the user click on any tabs, the visual is updated).

**Expected behavior**
View should be updated immediately when the 'disabled' flag of MenuItem is changed.

**Minimal reproduction of the problem with instructions**
- Open the stackblitz example
- Press the 'Toggle Disabled' button
- Click on any tabs below the 'TabMenu (not working as expected)' menu title

**What is the motivation / use case for changing the behavior?**
N/A

**Please tell us about your environment:**

* **Angular version:** 10.0.14

* **PrimeNG version:** 11.3.2

* **Browser:** Firefox, Chrome (most probably all of them)
 
* **Language:** TypeScript

**Extra information**
This bug looks very similar to the one reported in #9367 (PrimeNG 10.0.1), which has been already fixed according to the v11.1.0 changelog. (it seems it has been only fixed for the TabView)

**Comment by yigitfindikli** [comment]
This is about Array's change detection. You need to trigger the change like;

`this.items = [...this.items]`
