### ISSUE TITLE
[p-tree] event.accept() not available on first drop

### ISSUE THREAD

**Issue by mrsegen** [primefaces/primeng#10093]
Thank you for the fix of #9991 with the release of 11.3.2. However, we're blocked by a related issue:

Even though, the event is now triggered. The first fire of the event doesn't have an `accept()` method. Thus our current implementation's attempt to utilize that method throws an error.

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-treedragdrop-demo-4bbf54?file=src%2Fapp%2Fapp.component.ts
![2021-04-09-no-accept-method](https://user-images.githubusercontent.com/3103203/114231606-a7645e80-9948-11eb-84f3-a0d98a04dac5.gif)

**Current behavior**

1. The `accept()` method is not present the first time we drop the item. (It is there the second time we drop the item.)
2. Apparently event.accept() _**does**_ get called on/before/after this first drop to an empty list (Evidence: nodes get removed from source and added to target) event though it's not triggered by/accessible to the onDrop function.

**Expected behavior**

1. The `event.accept()` is present on the event on the first drop.
2. If the user onDrop method we provide, doesn't call the `event.accept()` method, the dropped node does not leave the source and get added to the target.

**Minimal reproduction of the problem with instructions**

See stackblitz and gif above

**What is the motivation / use case for changing the behavior?**

We need to:
a. validate the note and NOT `accept()` if criteria aren't met
b. copy and restore the dragged item in the source list before `accept()`
c. change the `type` of the dropped node
```TypeScript
onDrop(event) {
  try {
    //
    const tentativeParent = // custom logic utilizing event.dragNode, event.dropNode

    // validation
    if (failureCondition) {
      // tell user
      return; // don't accept()
    }

    // copy and restore in source
    const copy: MyClass = new MyClass(event.dragNode);
    this.listOfSourceNodes.push(copy);
    this.listOfSourceNodes.sort((a, b) => this.mySourceNodeSorter(a, b));

    // approve drop
    event.accept();

    // transform
    event.dragNode.parentMyValue = tentativeParent.myValue;
    event.dragNode.draggable = true;
    event.dragNode.type = 'myTemplateString';
    tentativeParent.expanded = true;
  } catch (error) {
    // Report error
  }
}
```

**Please tell us about your environment:**

Windows 10, Visual Studio Code, NPM 7.9

* **Angular version:** 11.2.9

* **PrimeNG version:** 11.3.2

* **Browser:** Only tried on Chrome 89

 
* **Language:** TypeScript 4.0.5

* **Node (for AoT issues):** `node --version` =   14.15.3

**Comment by yigitfindikli** [comment]
Fixed in https://github.com/primefaces/primeng/commit/4a275dd6339a39bdd445e230bc0f24d75f4c96b0
