### ISSUE TITLE
Small typo with status

### ISSUE THREAD

**Issue by mbiesiad** [primefaces/primeng#10094]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
Displayed 'stats' instead of 'status'.

**Expected behavior**
Display 'status' (correct).

**Minimal reproduction of the problem with instructions**
Go into the:
https://stackblitz.com/edit/primeng-tablerowexpansion-demo?file=src%2Fapp%2Fapp.component.html
Search for 'stats' word.

Fixed with PR #10095 

Best wishes,

**Comment by yigitfindikli** [comment]
https://github.com/primefaces/primeng/commit/2b339a129b60313b31109027f614f183f0a5adb0
