### ISSUE TITLE
Muliselect maxSelectedLabels not working in 11.3.1 and 11.3.2 

### ISSUE THREAD

**Issue by maxwellfargoseCactus** [primefaces/primeng#10090]
https://stackblitz.com/edit/primeng-multiselect-demo-2rikee?file=src%2Fapp%2Fapp.component.ts

In this maxSelectedLabels is set to 1 ([maxSelectedLabels]="1") but not working also try  maxSelectedLabels="1"

primeng default maxSelectedLabels = 3 is also not working

**Comment by yigitfindikli** [comment]
You need to give selectedItemsLabel. https://stackblitz.com/edit/primeng-multiselect-demo-pmk5sj
