### ISSUE TITLE
Generic way of binding the column name and value in primeng

### ISSUE THREAD

**Issue by MohamedSahir** [primefaces/primeng#10096]
The idea is we have 100 grids on different pages, only column key and cell values is different that is dynamically receives from server.

Here is the stackoverflow question:
[stackoverflow](
https://stackoverflow.com/questions/67034773/how-to-generic-way-to-dynamically-bind-columnname-and-value-in-primeng-databale).

i am using primegrid for  couple of years now we have different  resposne structure.. i need to know this structure will support for prime grid

idea behind :

I have primengDatatable in angular, Here is the server model. I need to display the grid header based on column key and set the value-based cell value.This is the generic column names and values based on that need to display the grid. currently i have provided productName,ProductSKu, and price ,but that is not a column it will change based on response

```
 getDataFromServer(){
               let serverResponse: any = {
                gridRows: [{
                   gridColumns: [{
                        columnKey: 'ProductName',
                        cellValue: 'samsung',
                    },
                    {
                        columnKey: 'ProductSKU',
                        cellValue: '123',
                    },
                    {
                        columnKey: 'ProductPrice',
                        cellValue: '100',
                    }],
                },
                {
                   gridColumns: [{
                        columnKey: 'ProductName',
                        cellValue: 'nokia',
                    },
                    {
                        columnKey: 'ProductSKU',
                        cellValue: '889',
                    },
                    {
                        columnKey: 'ProductPrice',
                        cellValue: '12344',
                    }],
                },
                ],
                }
            }.




**Here is the component.html**
<p-table #dt stateStorage="local"
 stateKey="statedemo-local"
[responsive]="true" 
appendTo="body" styleClass="ui-table-customers" dataKey="id" [rowHover]="true" [value]="gridLists" [paginator]="true" [rows]="10" [columns]="cols" scrollHeight="100px" [showCurrentPageReport]="true"
   currentPageReportTemplate="Showing 1   to 10  out of {totalRecords} entries"
   [lazy]="false"
   [resizableColumns]="true" [autoLayout]="true">
   <ng-template pTemplate="caption">
       <div class="ui-helper-clearfix" style="text-align: left">
       </div>
   </ng-template>
   <ng-template pTemplate="header" let-columns>
       <tr>
         
           <th *ngFor="let col of columns">
               {{col.header}}  
           </th>
       </tr>
     
   </ng-template>
   <ng-template pTemplate="body" let-rowData let-columns="columns" let-i="rowIndex">
           <td>
               <p-cellEditor>
                   <ng-template pTemplate="input">
                       <input pInputText type="text" [(ngModel)]="rowData.columnKey">
                   </ng-template>
                   <ng-template pTemplate="output">
                       {{rowData.cellvalue}}
                   </ng-template>
               </p-cellEditor>
           </td>


   </ng-template>
</p-table>
```

here column key  is display but value is not dispalying because of structure of response to bind the data is 

  ```
  {  columnKey: 'ProductName',
                        cellValue: 'nokia',
                    },
```

[stackblitz with generic response.](https://stackblitz.com/edit/github-za58gp-g1zu3h?file=src%2Fapp%2Fapp.component.html).

based on my analysis  this is the way found in your documentation:

dummy demo:
```
import {Component} from '@angular/core';
import { ProductService } from './productservice';
import { Product } from './product';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent { 
    products: Product[];

    cols: any[];

    constructor(private productService: ProductService) { }

    ngOnInit() {
        this.productService.getProductsSmall().then(data => this.products = data);

        this.cols = [
            { field: 'code', header: 'Code' },
            { field: 'name', header: 'Name' },
            { field: 'category', header: 'Category' },
            { field: 'quantity', header: 'Quantity' }
        ];
    }
}
```
in hml:
```
<p-table [columns]="cols" [value]="products">
    <ng-template pTemplate="header" let-columns>
        <tr>
            <th *ngFor="let col of columns">
                {{col.header}}
            </th>
        </tr>
    </ng-template>
    <ng-template pTemplate="body" let-rowData let-columns="columns">
        <tr>
            <td *ngFor="let col of columns">
                {{rowData[col.field]}}
            </td>
        </tr>
    </ng-template>
</p-table>
```

demo working with the below structure:
`[stackblitz with structure data](https://stackblitz.com/edit/primeng-tabledynamic-demo?file=src%2Fapp%2Fapp.component.ts)`.

Note: i want to know whether I can able to do the binding based on the above response.

if not : can i able to reconstruct the response after recieving from server .

`[{ProductName:'samsung',ProductSKU:'123',ProductPrice':'100'}, {ProductName:'nokia',ProductSKU:'456',ProductPrice':'1244'} {....} ]`

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
