### ISSUE TITLE
Getting default value from dropdown

### ISSUE THREAD

**Issue by erikaoctavia** [primefaces/primeng#1010]
I am using v 1.0.0-beta.16 of primeNg. I am having trouble getting the default value in the dropdown. I am able to get the value on a change event. 

I have a p-dropdown that is populated with values returned from a database:
public mySelectList: SelectItem[] = [];
public selectedItem:string;
//..get values from database into listItems array
this.listItems.forEach(item=> {
	this.mySelectList.push({label: item.description, value: item});
});

Html:
`<p-dropdown` name="myList" [options]="mySelectList" [(ngModel)]="selectedItem" `(onChange)="selectMyItem(selectedItem.name)"></p-dropdown>`

I've tried changing my ngModel to a object and also a select item, but the value is always undefined when I submit the form. Is there a way to get that default value? Right now there is only one value in my dropdown list so right now I have had to add a --select an item--- null value in my dropdown to force them to select so I can get the value on the change event.

**Comment by An0d** [comment]
Same problem here.
2 way databinding with [(ngModel)] is not working...

When choosing a value in the Dropdown, the "binded object" is properly updated.
Programmaticaly set the "binded object" has no effect on the Dropdown ...

Any idea ? Any workaround until fix ?

Thanks

**Comment by Krustie101** [comment]
I notice that in the code of the dropdown, no model change events are fired in the following 2 cases:

- If the options change (ngDoCheck) and the value cannot be found in the selectedItems, the first value is selected but no model change event is fired.
- On a key down event, if no value was selected. Again the first value is selected but no model change event is fired.

Aside: Looking at the first line of the onKeyDown function, I would expect a nullpointer in some cases because the selectedOption might be null.

**Comment by erikaoctavia** [comment]
@An0d how are you accessing the default value when setting the item as a string or int? I've tried updating my dropdown to use a string value and I still get undefined. I've also tried accessing through the FormGroup and it's still undefined. 
`
<FormControl>this.loginForm.controls['myList'].value;
`

**Comment by therealcodesailor** [comment]
An0d's solution worked for me.

**Comment by erikaoctavia** [comment]
Thanks @An0d. I see you are hard coding your first option and that is what I was trying to avoid. But I can just store the first option of my array.

**Comment by jayordway** [comment]
I wouldn't call this a solution. It would be ideal to be able to retrieve the id with the event call. It wouldn't be practical to search for a value in an array of considerable length.

**Comment by trivian118** [comment]
primeng p-dropdown sucks to be honest
