### ISSUE TITLE
Autocomplete List-Scroll only works occasionally

### ISSUE THREAD

**Issue by EliasDerHai** [primefaces/primeng#10104]
**I'm submitting a ...**
```
[x ] bug report 
```

https://user-images.githubusercontent.com/19493409/114502420-0e756200-9c2c-11eb-9587-67111c1ba24b.mp4

**Current behavior**
scroll only works occasionally 

**Expected behavior**
scroll the autocomplete on hover not the whole page

**Minimal reproduction of the problem with instructions**
create <autocomplete> and scroll

* **Angular version:** 10.1.6

* **PrimeNG version:** 10.0.3

* **Browser:** [Firefox 87.0]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.3.2, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
