### ISSUE TITLE
Parent dialog restricts child's dialog max-width

### ISSUE THREAD

**Issue by gbourant** [primefaces/primeng#10105]
When the parent dialog contains a child dialog then the child's max width is restriced by parent's width.

From the developer's point of view we could move the child outside the parent and it would work, but that's not always the case.
Sometimes we are using other components inside the parent dialogs that contain a dialog which we cannot move.

In the following example, the child componet's width is 100vw but it won't go beyond the parent's width.

working example: https://stackblitz.com/edit/primeng-dialog-demo-undqd9?file=src/app/app.component.html

**Comment by AMP3D** [comment]
Same thing is happening with the child component's height.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
