### ISSUE TITLE
reopening #9568 - breaking change accordion custom header

### ISSUE THREAD

**Issue by pmo1948** [primefaces/primeng#10100]
**I'm submitting a ...**  REOPENING [#9568](https://github.com/primefaces/primeng/issues/9568#issue-749818427)
```
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-a7mpm3?file=src/app/app.component.html

**Current behavior**
PAccordionTab is disabled, so it disables all elements in header. Meaning, if I have a toggle to enable/disable the tab from within the header, disabling the header means I cannot re-enable it

**Expected behavior**
Disabling the tab should not disable the header

**Minimal reproduction of the problem with instructions**
Open [demo repo](https://stackblitz.com/edit/github-a7mpm3?file=src/app/app.component.html). Toggle the disable. Now you cannot re-enable it

**What is the motivation / use case for changing the behavior?**
Not break existing behavior

* **Angular version:** 11.0
From stackblitz template in your new issues template

* **PrimeNG version:** 11.3.0
From stackblitz template in your new issues template

**Comment by yigitfindikli** [comment]
Hi,

This is expected behavior. Thanks for your report.
