### ISSUE TITLE
ViewEncapsulation.ShadowDom Support

### ISSUE THREAD

**Issue by thuannv98** [primefaces/primeng#10114]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-shadowdom-issue

**Current behavior**
Some PrimeNG's components is not working properly when used in the component that apply ShadowDom encapsulation option. Some of these are Dropdown, OverlayPanel, Multiselect, Carlendar, ...
Also, when interacting with these component, the console throw an error: 
"TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'."

**Expected behavior**
These components should be working as they did in Emulated mode.

**Minimal reproduction of the problem with instructions**
Embed these component into a component and set ViewEncapsulation.ShadowDom as encapsulation option.

**What is the motivation / use case for changing the behavior?**
Possibility to use the library in Micro Frontends, where using ShadowDom is crucial.

* **Angular version:** 5.X
11.2.1

* **PrimeNG version:** 5.X
11.2.3

* **Browser:** all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
probably all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
probably all

**Comment by thuannv98** [comment]
#10001

**Comment by dom380** [comment]
@mertsincan this issue still occurs on 14.2.3, is it fixed on the 15.x branch?

**Comment by mertsincan** [comment]
@dom380, could you please check it? If the problem persists, please reopen this issue.

Best Regards,

**Comment by dom380** [comment]
@mertsincan Unfortunately not easily as my app is tied to Angular14 due to other dependencies at the moment.
