### ISSUE TITLE
[Angular] inputNumber cursor jump at the end for negative numbers

### ISSUE THREAD

**Issue by BizzottoClaudio** [primefaces/primeng#10110]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Can be tested on the current showcase https://primefaces.org/primeng/showcase/#/inputnumber

**Current behavior**
When writing a `negative number`, the `curson` jumps at the end
![hUe6W1WIAR](https://user-images.githubusercontent.com/20600987/114693190-a56c1800-9d19-11eb-828c-3684ae66024f.gif)

This happens for:
- `Min-Max Fraction Digits`
- All the `locale`
- All the `currencies`

**Expected behavior**
The cursor should not jump at the end

**Minimal reproduction of the problem with instructions**
write the following: -1 (writing from left to right)
without pressing any other button: the cursor will jump to the end

**What is the motivation / use case for changing the behavior?**
It's uncanny that i have to move with arrow keys (or point with the mouse) to write `-1.1`

**Please tell us about your environment:**
Angular, Chrome

* **Angular version:** 11.1

* **PrimeNG version:** 11.3.2 (the last available as of now)
The same issue happens on older version

**Comment by mertsincan** [comment]
Hi,

I think this issue has been fixed in 12.1.1.

For now, closed. If the problem persists, please reopen this ticket.
Best Regards,
