### ISSUE TITLE
Table selection not updating when items have been removed from table

### ISSUE THREAD

**Issue by kwebster16** [primefaces/primeng#10116]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-5hddpb?file=src/app/app.component.html

**Current behavior**
When the value of the data table is updated (items removed), the bound selection is not updated to match.  E.g. if you have an item selected and it's removed from the table the item remains "selected" even though it no longer exists.

**Expected behavior**
Items should be removed from selection if they are removed from the table.

**Minimal reproduction of the problem with instructions**
See stackblitz 

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 11.x

* **PrimeNG version:** 11.3

* **Browser:** all

 
* **Language:** all

* **Node (for AoT issues):** `node --version` =

**Comment by yigitfindikli** [comment]
Hi,
Stackblitz example not working. 
![image](https://user-images.githubusercontent.com/19997575/114885413-4b4d7e80-9e0f-11eb-8a1a-c2f8215921e3.png)

And these changes should do on your side.
