### ISSUE TITLE
Can we have a generic type option for MenuItem interface

### ISSUE THREAD

**Issue by lallenfrancisl** [primefaces/primeng#10118]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
MenuItem interface does not have any generic type defintions

**What is the motivation / use case for changing the behavior?**
MenuItem would have a generic type for specifying the automationId and some other fields that are specified as any like state. So, what would the ideal case will be
`export interface MenuItem<T = any, U = any> {
  automationId: T
  /** changes to to other fields **/
}`

Now why should this be done is just for the intellisense used by the LSP server, I think this is a great help for developers.

**Comment by lallenfrancisl** [comment]
Since this is a fairly simple issue, can I work on it ?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
