### ISSUE TITLE
Timeline gets broken when using events with long values

### ISSUE THREAD

**Issue by pehchevskip** [primefaces/primeng#10129]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/primeng-timeline-demo

**Current behavior**
Timeline with horizontal layout gets broken when long values are used.

**Expected behavior**
Timeline with horizontal layout should work properly even with long values and the events should  be properly connected to the lines (connectors).

**Minimal reproduction of the problem with instructions**
- On the stackblitz demo: https://stackblitz.com/edit/primeng-timeline-demo
- Find the events2 array used for horizontal timelines and append some more words to the last event value (you can also extend the values of the previous events, but much longer, actually until the text doesn't reach the next event)
- The blue circle (event-marker) will go slightly up or down depending on the align property and will not be connected to the line

Example: https://stackblitz.com/edit/primeng-timeline-demo-q6bkas?file=src/app/app.component.ts

* **Angular version:** 11

* **PrimeNG version:** 11

**Comment by rhegner** [comment]
Same here with PrimeNG 12:

![image](https://user-images.githubusercontent.com/2563997/122613710-98ef9d00-d085-11eb-8ed3-1e464ffba06b.png)

```
<p-timeline [value]="history" layout="horizontal" align="bottom">
	<ng-template pTemplate="content" let-event>
		{{event.label}}
	</ng-template>
	<ng-template pTemplate="opposite" let-event>
		<div>{{event.version}}</div>
		<button *ngIf="event.updateButton" pButton type="button" [label]="event.updateButton" class="p-button-success p-mt-2"></button>
	</ng-template>
</p-timeline>
```

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by Yurcek** [comment]
> Hi,
> 
> So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!
> 
> Best Regards,

Hello @mertsincan,  unfortunately, the issue is still there.

**Comment by mubinahmed** [comment]
`this improvement may have been developed in another issue ticket without realizing it` - this was a very easy to test issue for which the team need not depend on community. 
The issue still exists in v16.0.2
Please re-open this, or point us to another issue where this is being handled.
