### ISSUE TITLE
I18N API doesn't change translations of dayNamesMin

### ISSUE THREAD

**Issue by AlbaSS18** [primefaces/primeng#10126]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When language change, the i18N API doesn't change translations of dayNamesMin while the rest works fine. 

There are more comments in this [issue ](https://github.com/primefaces/primeng/issues/5151) but it is close, so I decided open one new.

**Please tell us about your environment:**

* **Angular version:** 11

* **PrimeNG version:** 11.3.2

* **Browser:** Chrome

**Comment by yigitfindikli** [comment]
I couldn't replicate it with v11.3.2. See https://stackblitz.com/edit/primeng11-localization-bug-vk3yam
