### ISSUE TITLE
Binding multiple calendars to same property can reset property when editing date

### ISSUE THREAD

**Issue by Urtgard** [primefaces/primeng#10127]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-uedqzv

**Current behavior**
If you bind one date property to multiple calendars, which show either date or time, editing one calendar resets the date property.

Editing a date only calendar resets the time.
Editing a date only calendar manually resets the time.
Editing a time only calendar doesn't reset the date.
Editing a time only calendar manually resets the date.
Editing a date and time calendar works fine.

**Expected behavior**
Editing one calendar shouldn't reset the date property.

* **Angular version:** 11

* **PrimeNG version:** 11.3.2

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
