### ISSUE TITLE
Menubar Mobile Menu Improvements (icon alignment right, custom template, custom breakpoint)

### ISSUE THREAD

**Issue by vdbongard** [primefaces/primeng#10124]
**I'm submitting a ...**
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**StackBlitz**
https://stackblitz.com/edit/feature-primeng-menubar-button-right

**Description**
I think the menubar is a great component but I would like to suggest a few improvements that would make it even better.

First one is the alignment of the mobile menu icon which is left aligned by default. It would be great to have a component property to change it to be right aligned.
![image](https://user-images.githubusercontent.com/13508962/115055231-83bd8d00-9ee1-11eb-974f-d3a8a01e6b9b.png)

Next one is that there is currently no possibility to customize the content of the mobile menu overlay. In the normal menubar you can add start/end templates for custom content but the mobile menu overlay does not have this option.

And lastly it would be great to be able to customize the breakpoint at which the mobile menu is shown. The default breakpoint is also different than the default breakpoints of Primeflex (960px vs 992px lg in Primeflex)

**Comment by Hazzard17h** [comment]
As a workaround for the alignment of the mobile menu icon to the right, you could use:
```html
<p-menubar styleClass="p-menubar-button-right">
</p-menubar>
```

```scss
p-menubar > .p-menubar.p-menubar-button-right {
  .p-menubar-button {
    margin-left: auto;
  }
  .p-menubar-end {
    margin-left: unset;
  }
}
```

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
