### ISSUE TITLE
inputMask - properties for currency are missing

### ISSUE THREAD

**Issue by leonhardt** [primefaces/primeng#1012]
I have updated to beta.17 and mask for currency is not working or properties are missing in documentation.

**Comment by wilsonmoraes** [comment]
i have the same problem after updated

**Comment by leonhardt** [comment]
How can i change  options for this component?
Ex:[options]="{groupSeparator:'',digits:2,prefix:'R$ ',digitsOptional:false,autoGroup:true}"

**Comment by cesarrew** [comment]
You can use this component:

https://www.npmjs.com/package/ng2-currency-mask
