### ISSUE TITLE
StackBlitz example does not work in Chart documentation for version LTS-9

### ISSUE THREAD

**Issue by twopelu** [primefaces/primeng#10121]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
The StackBlitz example does not work in Chart documentation for version LTS-9:
https://www.primefaces.org/primeng/v9-lts/#/chart/line
https://stackblitz.com/edit/primeng-linechart-demo?file=src%2Fapp%2Fapp.component.html

**Current behavior**
It shows an error in browser console:
"ERROR Error: Chart__namespace is not a constructor"

**Expected behavior**
The chart example should load as per the documenation.

**Minimal reproduction of the problem with instructions**
Open the StackBlitz and run, nothing is shown, open console and see error.

**What is the motivation / use case for changing the behavior?**
It would be useful to solve this in the documentation to be able to test it properly.

**Please tell us about your environment:**
Windows 10

* **Angular version and PrimeNG version:**
"@angular/compiler": "9.0.4"
"primeng": "^10.0.0",
"chart.js": "2.9.3",
(see StackBlitz package.json)

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS Tested on browsers:
Edge Versión 89.0.774.68 (Compilación oficial) (64 bits)
Chrome Versión 89.0.4389.128 (Build oficial) (64 bits)

**Comment by yigitfindikli** [comment]
Seems to be there is an issue with StackBlitz. But the doc will be updated next release. Thanks for your report.
