### ISSUE TITLE
Table sticky - header border problem in firefox

### ISSUE THREAD

**Issue by stefanozaccaria-centropaghe** [primefaces/primeng#10120]
I have notice that the table, with sticky rows/columns, have some problem with header border.
If you open https://www.primefaces.org/primeng/showcase/#/table/sticky and use "rhea" theme with "chrome" there are not problems. 
![image](https://user-images.githubusercontent.com/81638601/114984782-5e556280-9e92-11eb-803c-9942f4842918.png)

If you open with "firefox" the border go away. 
![image](https://user-images.githubusercontent.com/81638601/114984928-804ee500-9e92-11eb-9f43-b7ab70f10f32.png)

This happens both with columns and rows.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
