### ISSUE TITLE
Table: primeng/table - Issue with last page if changing number of records per page

### ISSUE THREAD

**Issue by sekurufarayi** [primefaces/primeng#10131]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
```

**Current behavior**
https://www.primefaces.org/primeng/showcase/#/table
select Last page (>> icon) -> system goes to the last page

![image](https://user-images.githubusercontent.com/74071887/115227246-84883600-a110-11eb-955b-268ee1dfc462.png)

change number of records to 25 -> system shows the last page as expected
![image](https://user-images.githubusercontent.com/74071887/115227350-a5508b80-a110-11eb-9926-432c29594fe6.png)

change number of records to 10  ->  2 pages before last page is displayed

![image](https://user-images.githubusercontent.com/74071887/115227434-c0230000-a110-11eb-9298-d9f21eb0ad4b.png)

**Expected behavior**
system is forwarded to page 1, number of pages is recalculated
actual result: 2 pages before last page are displayed

**What is the motivation / use case for changing the behavior?**
The pagination is not calculating correctly

**Please tell us about your environment:**
Windows 10
Angular: 10.2.3
PrimeNG version:** 11.3.2
Browser: [ Chrome 89  ]

**Comment by yigitfindikli** [comment]
This is expected behavior. Paginator is trying to go minimum.
