### ISSUE TITLE
Crash when changing Button Icon 

### ISSUE THREAD

**Issue by denny99** [primefaces/primeng#10138]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-5mkgtv?file=src/app/app.component.html

**Current behavior**
Using a button that has no icon initially fails as the Dom Element won't be generated but is tried to be update when chaning the icon on the fly.

**Expected behavior**
Buttons without any icon can get a new icon after rendering

**What is the motivation / use case for changing the behavior?**
In our use case, we wrapped the primeng buttons, disable them on click and show a progress spinner to avoid double clicks.

* **Angular version:** 11.X
* **PrimeNG version:** 11.3.1

* **Browser:** [all]
 
* **Language:** [TypeScript 4.2]

**Comment by yigitfindikli** [comment]
Fixed in https://github.com/primefaces/primeng/commit/b037db9cbef0f7ef8f050eaf9674bb4b0ab82877
