### ISSUE TITLE
Calendar property "yearRange" not working properly

### ISSUE THREAD

**Issue by WilsonPM96** [primefaces/primeng#10135]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://primeng-calendar-demo.stackblitz.io

**Current behavior**
Currently if you set yearRange as the example "2000:2030" and you change the year to  2000 or 2030 and then change with the left or right arrow then if you check again the year range it changes to the next 30, in this case.

**Expected behavior**
When you set yearRange it must not change its value or maybe you cannot navigate with left and right arrows when you are in the min and max dates.

**Minimal reproduction of the problem with instructions**
First set yearRange. 
Then go to the last or the first year in that range.
After that change with the left or right arrow.
Finally review date range and it must have changed.

**What is the motivation / use case for changing the behavior?**
I need to use it to specify year ranges with birth dates.

**Please tell us about your environment:**
Operating system: Windows 10 Pro 
IDE: Webstorm 
Package manager: npm, node 

* **Angular version:** 5.X
11.2.6

* **PrimeNG version:** 5.X
11.3.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 89.0.4389.128
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 4.1.2
* **Node (for AoT issues):** `node --version` =   
v14.15.1

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
