### ISSUE TITLE
InputMask not formatting input that already has a value, does work after focusing on input

### ISSUE THREAD

**Issue by tbertran** [primefaces/primeng#1013]
I'd expect `InputMask` to correctly mask an input whose value is bound to an already populated property but it doesn't. However, clicking on the input will immediately format it.
See this [plunker](http://plnkr.co/edit/ndNPscFwkzlEoN6xJnMo?p=preview).

**Comment by gilsondev** [comment]
I have the same problem:


![image](https://cloud.githubusercontent.com/assets/265653/22165068/0e691a92-df41-11e6-87c8-a8babedf6685.png)

PrimeNG: 1.1.4

**Comment by mertsincan** [comment]
Please try this issue with PrimeNg 2.0.R1 version.

**Comment by tbertran** [comment]
The problem is still occurring.

**Comment by An0d** [comment]
Encountering the same problem and just upgraded to 2.0.R1.

**Comment by sudheerj** [comment]
I'am not able to replicate the issue with PrimeNG 2.0.2 version.It formats properly for both string or number type input.

```
<p-inputMask id="basic" mask="(99)-999999" name="simple" [size]="50" [maxlength]="9"
                         [(ngModel)]="simple" placeholder="99-999999">
simple: number=12345678;
```

**Comment by tbertran** [comment]
I can confirm this is now fixed.
