### ISSUE TITLE
TypeError: this.colorSelectorViewChild is undefined

### ISSUE THREAD

**Issue by borjaeguia** [primefaces/primeng#10148]
```
[x ] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
I have not been able to reproduce the error but Sentry is throwing this message to me from the library:

```
TypeError: this.colorSelectorViewChild is undefined
```

from /node_modules/primeng/fesm2015/primeng-colorpicker.js in pickColor at line 116:20:

```
pickColor(event) {
        let rect = this.colorSelectorViewChild.nativeElement.getBoundingClientRect();
        let top = rect.top + (window.pageYOffset || document.documentElement.scrollTop || document.body.scrollTop || 0);
        let left = rect.left + document.body.scrollLeft;
        let saturation = Math.floor(100 * (Math.max(0, Math.min(150, (eve...
```

does anyone look familiar?

* **Angular version:** 11.2.7

* **PrimeNG version:** 10.0.0

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.4.0, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
