### ISSUE TITLE
Inputmask beta.17 - email

### ISSUE THREAD

**Issue by moxival** [primefaces/primeng#1014]
Can somebody give an example how to set an InputMask that can cover email address, i cannot seem to find a correct way to use variable number of characters?

**Comment by moxival** [comment]
@cagataycivici can you please just tell if this is not possible with the current implementation so i can move on

**Comment by sudheerj** [comment]
In my opinion the whole point of using input mask is to force the user to enter certain characters at certain positions.So email kind of masking won't suite for inputmask component .

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.

**Comment by malbarmawi** [comment]
@sudheerj  the input mask also use to force the user to enter an correct email format like `Validators.email` as an examble something like this https://robinherbots.github.io/Inputmask/  is it possible in primeng v7 to mask email address` _@_._`  or just use another third party component
