### ISSUE TITLE
InputNumber on mobile works like textinput

### ISSUE THREAD

**Issue by adriancoca** [primefaces/primeng#10142]
**I'm submitting a bug**  
```
[ x] bug report 


```

**Current behavior**
Chrome Android
When trying to write something in a InputNumber the full keyboard is open, also the validation that on desktop is working fine do not seem to apply on mobile.

**Expected behavior**
the input should have -> inputmode="decimal" (now i created a directive that add this attribute on input)
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode
In this way on mobile the number keyboard will be shown.

The same validation logic like on desktop should run when user is entering values in input.

**Minimal reproduction of the problem with instructions**

try to fill inputs in this page android chrome

https://primefaces.org/primeng/showcase/#/inputnumber

* **Angular version:** 
11.1.2

* **PrimeNG version:** 
11.3.2

* **Browser:** 
Android Chrome

![nr](https://user-images.githubusercontent.com/7643185/115388093-288ee180-a1e4-11eb-84bd-f00632982fe6.jpg)

**Comment by SRQCarlosAraujo** [comment]
I was using inputNumber in my application and I came across a similar error even today. The mask works perfectly on the desktop, unlike on mobile, where the user can type periods and commas, breaking the model defined by the developer.


![WhatsApp Image 2024-04-15 at 17 06 39](https://github.com/primefaces/primeng/assets/150136482/b67919eb-4ecd-4d6b-a728-35c6cd65fec8)
