### ISSUE TITLE
Datatable Reorder - reorderableColumns="false"

### ISSUE THREAD

**Issue by ethemsulan** [primefaces/primeng#1015]
i have a datatable and i set reorderableColumns="false" but it is not work. reorderableColumns="true" or reorderableColumns="false" is same behaviour. 
This is example url: http://www.primefaces.org/primeng/#/datatablecolreorder

**Comment by wk198553** [comment]
I had the same issue, and fixed by adding square brackets. Try use [reorderableColumns]="false"

**Comment by ethemsulan** [comment]
Thank you, it is working.
