### ISSUE TITLE
ConfirmDialog and ConfirmPopup Button Order

### ISSUE THREAD

**Issue by peaverok** [primefaces/primeng#10154]
I'm submitting a

[ ] bug report
[X] feature request
[ ] support request

**Current behavior**
Buttons are in the order of reject then accept on the confirmdialog and confirmpopup.

**Expected behavior**
It would be nice to be able to reorder them with a flag to make them accept then reject (accept to the left of reject). Yes you can label the accept to reject text (No) and the reject to the accept text (Yes) but then you are responding to the accept method with reject code and the reject method with accept code which is backwards.

**What is the motivation / use case for changing the behavior?**
Many applications don't follow the format of reject then accept. Instead they put accept/positive action buttons on the left and reject/negative action buttons on the right.

* **Angular version:11

* **PrimeNG version: 11.4.0

* **Browser: All Browsers

**Comment by nangai-source** [comment]
Any idea if the buttons can be reordered from the default standard. I need Accept first followed by Reject labels. Please suggest. Migrating to the latest PrimeNG version leads to this UI change.

Please reply ASAP.

Thanks.

**Comment by nangai-source** [comment]
Hi yigitfindikli,

Is this going to be an enhancement for the upcoming releases? Please Suggest.Thanks.

**Comment by thiemohaller-din** [comment]
It boggles my mind that such an important feature for UX and UI design is hardcoded.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by vstiebe** [comment]
This feature request is still valid. The reject and accept buttons order shouldn't be hardcoded.
Please consider creating a way to config the button order.

**Comment by Thf772** [comment]
What is the status on this feature request? As of March 2024 there is still no way to swap the button positions in a confirmation dialog.

**Comment by jmuehlenhoff** [comment]
Please reopen this issue @mertsincan as it is not fixed.

**Comment by robindepobin** [comment]
I would very much like this option as well. I know there is a lot of discussion on the subject of button sequence, but that is all the more reason to allow us to decide for ourselves.
