### ISSUE TITLE
p-columnFilter not work with async values

### ISSUE THREAD

**Issue by Tr1monster** [primefaces/primeng#10158]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-async-column-filter?file=package.json

**Current behavior**
After 5 seconds the data is loaded and displayed in the table. When I type something in the column filter that should matches, the data disappears.

**Expected behavior**
When I type something in that matches, the data is displayed. When I type something that not matches, the data disappears.

**Minimal reproduction of the problem with instructions**
I created an fakeHttp that return one value after 5 seconds. Type my username into the column filter and apply the filter.

**What is the motivation / use case for changing the behavior?**

I have to display data in a table. For one column i have to do for each row a http call to fetch more data. The service provide a Promise and the data is displayed via an async pipe.

* **Angular version:** 11.0.5

* **PrimeNG version:** 11.1.0-rc.1

* **Browser:** [all]

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
