### ISSUE TITLE
relationships for p-tree 

### ISSUE THREAD

**Issue by rezaokhravi** [primefaces/primeng#10166]
Can you  identify parental and child relationships for p-tree ?
like the image :
![tree](https://user-images.githubusercontent.com/42868109/116212338-f9372200-a759-11eb-9286-6ff69dddc270.png)

* **PrimeNG version:** 11.4.0

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
