### ISSUE TITLE
Support lazy/dynamic import for quill

### ISSUE THREAD

**Issue by Exlord** [primefaces/primeng#10164]
```
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
```

**Current behavior**
Quill is imported statically `import * as Quill from "quill";` 

**Expected behavior**
import quill dynamically to reduce bundle size
`const Quill = await import('quill')` OR  
Don't import it at all and ask the user to provide the quill instance to the ditor  

**What is the motivation / use case for changing the behavior?**
Quill is big, and its not used in every page, so it makes sence to delay its loading to reduce main bundle size

* **primeng@11.3.2

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
