### ISSUE TITLE
PrimeNG Table Filter on Mobile Device [Bug] - Text Input not possible (Android & Chrome)

### ISSUE THREAD

**Issue by max-x-1000000** [primefaces/primeng#10163]
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Trying to apply a text column filter here:
https://www.primefaces.org/primeng/showcase/#/table/filter

Selecting the input field to enter a text field for filtering, the element gains focus, keyboard launches, element looses focus, keyboard closes as does the filter window.


**Expected behavior**
The user should be able to enter text in the filter window on a mobile device.

**Minimal reproduction of the problem with instructions**
1. Go to: https://www.primefaces.org/primeng/showcase/#/table/filter on an Android running the Mobile Chrome browser.
2. Select a text column's filter and try to enter text in the input field

**Comment by yigitfindikli** [comment]
This caused by demo classes. If you remove the p-datatable-customers class filter gonna work as expected. You can design your own table using with p-table component.

**Comment by max-x-1000000** [comment]
> table

Negative. Have loaded the demo page on Stackblitz and removed the class. Error still present. See below on Android running Mobile Chrome:

https://stackblitz.com/edit/primeng-tablefilter-demo-35eaqc?file=src/app/app.component.html

**Comment by max-x-1000000** [comment]
> This caused by demo classes. If you remove the p-datatable-customers class filter gonna work as expected. You can design your own table using with p-table component.

Negative. Have loaded the demo page on Stackblitz and removed the class. Error still present. See below on Android running Mobile Chrome:

https://stackblitz.com/edit/primeng-tablefilter-demo-35eaqc?file=src/app/app.component.html

![image](https://user-images.githubusercontent.com/51189766/116254895-a5ccd000-a769-11eb-9526-08c3de560ee1.png)

**Comment by max-x-1000000** [comment]
@yigitfindikli I've made a workaround using drop-downs for each column instead of string filtering. Please do take a look at the stackblitz page above, this bug is very much still alive

**Comment by vinniefm** [comment]
This bug is still very much alive. Table filtering is broken as described above. My particular use case is on MSFT Surface tablets, no external keyboard attached for our users.
