### ISSUE TITLE
p-radioButton not remove class ".p-highlight"

### ISSUE THREAD

**Issue by rezaokhravi** [primefaces/primeng#10161]
In the version 11.4.0, when select an items from RadioButtoon with  it adds a class with name of ".p-highlight" to this item , but when select another item, it not remove ".p-highlight" from previews selected item.

**Example**
```
<p-radioButton name="rdbtest" value="1" label="item-one"></p-radioButton>
<br>
<p-radioButton name="rdbtest" value="2" label="item-tow"></p-radioButton>
```

**Try in**
https://stackblitz.com/edit/primeng-radiobutton-demo-mhzq37 

* **Angular version:** 9.X

* **PrimeNG version:** 11.4.0

**Comment by yigitfindikli** [comment]
Fixed in https://github.com/primefaces/primeng/issues/9631

**Comment by rezaokhravi** [comment]
Thanks
