### ISSUE TITLE
DataTable selection broken with version 1.0.0-beta.17

### ISSUE THREAD

**Issue by vaibhavcodegeek** [primefaces/primeng#1016]
Hi,

We have updated our project to primeng version "1.0.0-beta.17". After the update datatable selection is not working properly,

1) We set login user as selected user in the users datatable on page load.
- After update, login user is not reflected as selected on UI.

2) We allow user to select multiple roles from roles table. 
- After update, multiple row selection is not working

Both the features are working fine with earlier version "1.0.0-beta.16".

Please look into it.

**Comment by cagataycivici** [comment]
We can't replicate it with RC4, please try with the latest version.
