### ISSUE TITLE
Paginator does not properly change pages when reducing totalRecords

### ISSUE THREAD

**Issue by Tortenschachtel** [primefaces/primeng#10162]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
The following contains a paginator and two buttons. The buttons set the totalRecords to either 3 or 10. The metrics below the buttons are the values from the latest event that was send by the paginators onPageChange.

Check any page in the following example. If you checked page 2 and reduce the totalRecords to 3 the selected page will change to 1. However, if you select page 3 or 4 and set the total to 3 the page will not change.
https://github-cfsxbe.stackblitz.io

**Current behavior**
When the total number of elements for a paginator changes the component updates the current page. However, the current implementation will only ever move one page down if there are less total elements, this is not appropriate under all circumstances.

The problem is located in the paginator.ts, method "updateFirst()".
```
updateFirst() {
    const page = this.getPage();
    if (page > 0 && this.totalRecords && (this.first >= this.totalRecords)) {
        Promise.resolve(null).then(() => this.changePage(page - 1));
    }
}
```

**Expected behavior**
The paginator should calculate how many pages are actually available and switch to the last one.

Suggested change:
```
updateFirst() {
    const page = this.getPage();
    if (page > 0 && this.totalRecords && (this.first >= this.totalRecords)) {
        const newPage = Math.floor(this.totalRecords / this.rows);
        Promise.resolve(null).then(() => this.changePage(newPage));
    }
}
```

**Minimal reproduction of the problem with instructions**
Select a sufficiently high page in a paginator, then change the totalRecods so that the currently selected page is at least 2 pages beyond the new last page. The paginator will not switch pages as it should.

**What is the motivation / use case for changing the behavior?**
Fix a bug in our applications, that use primeng.

**Please tell us about your environment:**
Windows 10 Version 1903
Visual Studio Code 1.55.2
npm 6.14.8

* **Angular version:** 11.2.4

* **PrimeNG version:** 11.4.1-SNAPSHOT

* **Browser:** all
 
* **Language:** Type Script

* **Node (for AoT issues):** `node --version` =   v14.15.0

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by michelAlexis** [comment]
Hi,

Just wanted to say the bug still exists in the master branch.
Is there any plan to add this to the roadmap ?

Thanks
