### ISSUE TITLE
 Click on Checkbox p-table is not selected on the table row

### ISSUE THREAD

**Issue by rezaokhravi** [primefaces/primeng#10168]
In p-table when use  selectionMode="multiple" and  [pSelectableRow]="product"  In Mode Checkbox Selection or RadioButton , only click in row then Selection Checkbox , but if click on Checkbox  it 's not working , Just out of here it 's working.

**Example ** 
```
<p-table 
    [value]="products" 
    selectionMode="multiple"
     [(selection)] ="selectedProducts3" 
     dataKey="code">
        <ng-template pTemplate="header">
            <tr>
                <th style="width: 3rem">
                    <p-tableHeaderCheckbox></p-tableHeaderCheckbox>
                </th>
                <th>Code</th>
                <th>Name</th>
                <th>Category</th>
                <th>Quantity</th>
            </tr>
        </ng-template>
        <ng-template pTemplate="body" let-product>
            <tr 
            [pSelectableRow]="product"
            >
                <td>
                    <p-tableCheckbox [value]="product"></p-tableCheckbox>
                </td>
                <td>{{product.code}}</td>
                <td>{{product.name}}</td>
                <td>{{product.category}}</td>
                <td>{{product.quantity}}</td>
            </tr>
        </ng-template>
    </p-table>
```

* **Angular version:** 9.X

* **PrimeNG version:** 11.4.0

**Comment by brmc** [comment]
@yigitfindikli, why was this labeled as a new feature? This is definitely not the intended behavior, and I'm experiencing this bug as well. 

To add more details:

* When everything is unselected, selecting a top-level node by clicking on the _label_ selects the node itself. Children are not selected
  * At this point, toggling the selection by clicking the label does not affect anything other than the node itself
* When everything is unselected, selecting a top-level node by clicking on the _checkbox_ selects all of the children but the parent is not selected
  * At this point, attempting to toggle the selection of the parent node by clicking on the checkbox does not work at all
  * Clicking on the label of the parent toggles the selection status of the parent node only
  * If you select the parent node by clicking on the label, and THEN clicking on the checkbox, all of the children are deselected but the parent remains selected. Further clicks on the checkbox have no effect until the label is clicked

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
