### ISSUE TITLE
p-calendar [required] attribute not working in the presence of [readonlyInput] attribute

### ISSUE THREAD

**Issue by ahmedderkaoui** [primefaces/primeng#10169]
**I'm submitting a ...**
```
[x] bug report 
[ ] feature request https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request 
```

**Minimal reproduction of the problem with instructions**
component.html
```
<form id="test" (submit)="test()">
    <p-calendar [(ngModel)]="testmodel" [name]="testname" [required]="true"></p-calendar>
    <button type="submit">submit</button>
</form>
```
component.ts
```
test() {
        console.log((document.getElementById("test") as HTMLFormElement).checkValidity())
    }
```
Executing this code, and submit the form without filling the calendar returns `false` in console, which is expected since the calendar has `required` attribute true.

But, when we add the `[readonlyInput]="true"` to p-calendar as below:
```
<form id="test" (submit)="test()">
    <p-calendar [(ngModel)]="testmodel" [name]="testname" [required]="true" [readonlyInput]="true"></p-calendar>
    <button type="submit">submit</button>
</form>
```
And by doing the same submission without filling the calendar input, here we get a `true` in console, which means the form is valid. 

It seems that adding `[readonlyInput]="true"` to p-calendar makes `[required]="true"` ignored or not working correctly.

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
