### ISSUE TITLE
table.reset() doesn't clear table.filters

### ISSUE THREAD

**Issue by AlejandroFlorin** [primefaces/primeng#10179]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
calling the table.reset() doesn't clear the table.filters property. Now have to clear the filters manually before calling reset via:
table.filters = {};

**Expected behavior**
table.reset() should clear the table.filters property. This used to work in 11.2.0 but seems to have stopped working since that version

**Minimal reproduction of the problem with instructions**
Setup any table and enter filtering information
Call tabe.reset()
The table shows the same filtered data instead of non-filtered data

Note that my tables DO NOT have state management turned on (not sure if it makes a difference)

**What is the motivation / use case for changing the behavior?**
This was a breaking change. I was forced to add the table.filters = {} line to the reset code of every table in my app.

**Please tell us about your environment:**
Windows 10 Pro
Visual Studio 2019 Community

* **Angular version:** 5.X
11.2.0

* **PrimeNG version:** 5.X
11.4.0 (also issue in 11.3.0)

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All tested browsers
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS 4.1.5

* **Node (for AoT issues):** `node --version` =   
v14.15.4

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
