### ISSUE TITLE
Dynamic generated options in dropdown can't be selected

### ISSUE THREAD

**Issue by kareljuricka** [primefaces/primeng#10171]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-yqtqpy

**Current behavior**
Dynamic generated options in dropdown can't often be selected, especially those whose are reachable with scroll
Static options works without problems

**Expected behavior**
All options are selectable, regardless are dynamic or not

**Minimal reproduction of the problem with instructions**
Just generate options as shell copy of static array and problem occurres.
I also tried combinations with dataKey or optionValue (combination using dataKey and optionValue fail in every selection)

**What is the motivation / use case for changing the behavior?**
Filtering options dynamically

**Please tell us about your environment:**
MacOS

* **Angular version:** 11.2.9

* **PrimeNG version:** 11.4.0

* **Browser:** [ Chrome 90 | Firefox 88 ]
 
* **Language:** [ TypeScript 4.1.5 ]

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
