### ISSUE TITLE
Improve menubar positioning against viewport

### ISSUE THREAD

**Issue by zbrukas** [primefaces/primeng#1017]
![untitled](https://cloud.githubusercontent.com/assets/1688557/19079263/a7b9cb02-8a18-11e6-9f60-4eb53e5ef325.png)

It's not a new issue, I think contextmenu has the same issue.

Before the element turns visible, a check can be made to make sure it doesn't go off screen. Something in the lines of (elem.getBoundingClientRect().left + elem.getBoundingClientRect().width) > document.body.getBoundingClientRect().width then left would be auto and right would be 0.

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
