### ISSUE TITLE
p-dropdown leaves a <ul> which creates a bar under the dropdown when dropdown items are empty.

### ISSUE THREAD

**Issue by shiny12348** [primefaces/primeng#10177]
![image (4)](https://user-images.githubusercontent.com/83347761/116503669-4a6b2100-a8d4-11eb-8f09-08b90ac5a034.png)

If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
In <p-dropdown> if dropdown values are empty like data=[]; Then it shows a bar beneath the text field.

**Expected behavior**

It is expected not to show that empty bar as there are no values in dropdown. (By inspecting that element I see that a ul is getting left behind, this ul element should be cleared if dropdown values are empty.)

**Minimal reproduction of the problem with instructions**
Make the data field empty array and click on the p-dropdown. Attached the screenshot.

**What is the motivation / use case for changing the behavior?**
Our UI is not looking good with this extra empty bar when values are empty.

**Please tell us about your environment:**

* **Angular version:** 11.0.3

* **PrimeNG version:** 11.2.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by yigitfindikli** [comment]
Hi,

There's a new empty template coming with v11.4.1. That feature will be covering this issue.
