### ISSUE TITLE
[PrimeNg Splitter] Splitter.onResize TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by rsohi** [primefaces/primeng#10176]
When splitter gutter is moved to the left most edge of the browser window, then the above mention error is reproduced. This causes the application to break.

I have not noticed the similar error to the right.

core.js:6014 ERROR TypeError: Cannot read property '0' of undefined
    at Splitter.onResize (primeng-splitter.js:84)
    at HTMLDocument.mouseMoveListener (primeng-splitter.js:133)
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Object.onInvokeTask (core.js:39680)
    at ZoneDelegate.invokeTask (zone-evergreen.js:390)
    at Zone.runTask (zone-evergreen.js:168)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:465)
    at invokeTask (zone-evergreen.js:1603)
    at HTMLDocument.globalZoneAwareCallback (zone-evergreen.js:1629)

If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.X

* **PrimeNG version:** 5.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.

**Comment by Blafy** [comment]
This issue still occurs on 11.4.2   
Try with the following [stackblitz](https://stackblitz.com/edit/primeng-splitter-demo-xwz81m?file=src%2Fapp%2Fapp.component.html).
I am on Edge, if that matters

It's quite random. You need to drag the splitter from right to the very far left (further than the div) several times (a dozen) to make it happen.
Happens on Firefox too.

**Comment by Blafy** [comment]
This issue still occurs on 11.4.2   (Angular 11)
Try with the following [stackblitz](https://stackblitz.com/edit/primeng-splitter-demo-xwz81m?file=src%2Fapp%2Fapp.component.html).
I am on Edge, if that matters

It's quite random. You need to drag the splitter from right to the very far left (further than the div) several times (a dozen) to make it happen.
Happens on Firefox too
