### ISSUE TITLE
PanelMenu: pressing Enter button

### ISSUE THREAD

**Issue by KurinIllia** [primefaces/primeng#10183]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```

**Current behavior**
Clicking on item in PanelMenu emits specified command, but pressing Enter button doesn't do this.

**Expected behavior**
When clicking on item in PanelMenu specified command should be emitted. 

**What is the motivation / use case for changing the behavior?**
Currently to do some command by clicking on PanelMenu item, it is needed to catch keydown/keyup event using @HostListener.

**Please tell us about your environment:**

* **Angular version:** 11.X

* **PrimeNG version:** 11.X

* **Browser:** all

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
