### ISSUE TITLE
Group the rows of tables in a tree by drag and drop the table columns to header of the p-table

### ISSUE THREAD

**Issue by rezaokhravi** [primefaces/primeng#10188]
Add the possibility of group the rows of tables in a tree by drag and drop the table columns to header of the p-table .
Like the following image :

![gridview_grouprowsapi_finalresult119176](https://user-images.githubusercontent.com/42868109/116770550-0d309b80-aa5a-11eb-9fd2-883baadfae4a.png)

* **Angular version:** 9.X

* **PrimeNG version:** 11.4.0

**Comment by harith-a** [comment]
Hi, is there any change someone is working on this?

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
