### ISSUE TITLE
Paginator showAll - number of pages inconsistent when using table filtering

### ISSUE THREAD

**Issue by fca1613** [primefaces/primeng#10190]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Standard example can be used:
https://stackblitz.com/edit/primeng-tabledoc-demo
Just need to replace `[rowsPerPageOptions]="[10,25,50]"`  in line 2 of app.component.html with `[rowsPerPageOptions]="[10,25,{showAll: 'All'}]"`

**Current behavior**
When using filtering feature of the table and change rows per page option value, some combinations can lead to have ALL (rows in one page) selected while there is several pages....
Steps to reproduce:
1. in Global Search input, enter "bu" => 7 entries are filtered
2. select "All" in pagination to display all entries on a single page
3. in Global Search input, remove the "u" => 106 entries are filtered on several pages even if "All" is selected

**Expected behavior**
on step 3, all items should be displayed on a **single** page because "All" is selected

**Minimal reproduction of the problem with instructions**
See Steps to reproduce in current behavior

**What is the motivation / use case for changing the behavior?**
Bug to fix... When All is selected in paginator, only one page should be displayed.

**Please tell us about your environment:**
No specific environment - official https://stackblitz.com/edit/primeng-tabledoc-demo

* **Angular version:** 5.X
No specific environment - official https://stackblitz.com/edit/primeng-tabledoc-demo

* **PrimeNG version:** 5.X
No specific environment - official https://stackblitz.com/edit/primeng-tabledoc-demo

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
No specific environment - official https://stackblitz.com/edit/primeng-tabledoc-demo

**Comment by cetincakiroglu** [comment]
Hi,

We couldn't replicate the issue with the latest PrimeNG release, if the issue still exists with the latest PrimeNG version, please provide a StackBlitz example by using [PrimeNG Issue Template ](https://stackblitz.com/github/primefaces/primeng-issue-template) and re-open the issue.

Regards
