### ISSUE TITLE
In IE the autocomplete dropdown alignments are not proper

### ISSUE THREAD

**Issue by srikanthrapolu** [primefaces/primeng#10191]
![image](https://user-images.githubusercontent.com/7527142/116879035-c4d1d300-ac3d-11eb-9e98-422d9ed4ccd8.png)

The overlay is coming out of dropdown width even when there is not option string that doesnt have that much width

**Comment by yigitfindikli** [comment]
This by demo, because some items label is very long. You can set your own width with panelStyle.
![image](https://user-images.githubusercontent.com/19997575/116879692-9f3ace80-ac29-11eb-91aa-1ca65d0ace79.png)

**Comment by srikanthrapolu** [comment]
Even when there are no items with that much width its coming like that
