### ISSUE TITLE
Missing focus style on p-tree with material design theme #10196

### ISSUE THREAD

**Issue by PeterHewat** [primefaces/primeng#10197]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Keyboard navigation using TAB to focus to a p-tree doesn't have a focused style making navigation blind. This is specific to all material design themes.

**Expected behavior**
Focus state should have a specific style.

**Minimal reproduction of the problem with instructions**
Use one of the material design themes then try to set focus to a p-tree using TAB navigation.

**What is the motivation / use case for changing the behavior?**
Better accessibility.

* **Angular version:** 11.2.12

* **PrimeNG version:** 11.4.0

* **Browser:** all
 
The lack of specific focus style in meterial design themes also occurs on p-inputSwitch (see #10196) and p-calendar (see #10195) and probably other components.

**Comment by yigitfindikli** [comment]
Moved to https://github.com/primefaces/primeng/issues/10195
