### ISSUE TITLE
optionValue for p-checkbox

### ISSUE THREAD

**Issue by ProfEibe** [primefaces/primeng#10194]
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Checkboxes with multiple Values don't work with arrays of objects. Arrays with copies of the same object are not recognized as the same value.
It would be great if there was a possibility to define an optionValue like in the dropdown-Element, where you can choose a key which will be compared during the recognition-process.

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by ProfEibe** [comment]
Is not implemented yet.
