### ISSUE TITLE
p-editor: Previous data was not retained in correct format which I had saved before in the form. It should be retained correctly in the form so that user can see the saved data then tries to edit and save the form.

### ISSUE THREAD

**Issue by Prasanth-FrontEnd** [primefaces/primeng#10193]
Intalled:
"quill": "^1.3.7",
"primeicons": "^1.0.0-beta.10",
"primeng": "^6.1.0",

"dependencies": {
    "@angular/animations": "^8.2.14",
    "@angular/cdk": "^8.2.3",
    "@angular/common": "^8.2.14",
    "@angular/compiler": "^8.2.14",
    "@angular/core": "^8.2.14",
    "@angular/forms": "^8.2.14",
    "@angular/material": "^8.2.3",
    "@angular/platform-browser": "^8.2.14",
    "@angular/platform-browser-dynamic": "^8.2.14",
    "@angular/platform-server": "^8.2.14",
    "@angular/router": "^8.2.14"
}

Configured Css:

     "styles": [
       "node_modules/primeicons/primeicons.css",
       "node_modules/primeng/resources/themes/omega/theme.css",
       "node_modules/primeng/resources/primeng.min.css",
        "node_modules/quill/dist/quill.core.css",
        "node_modules/quill/dist/quill.snow.css"
      ],
      "scripts": [
          "node_modules/quill/dist/quill.js"
      ]

Problem:
I was working on the large form with more than 100 fields. In that, I was using the primeng library to use editor field, everything was working fine but the data was not retained in the correct format. For example, If I used the right align, center align and left align in three lines means it comes in single line. That is not what I had saved before. Please help me out with this scenario. Below is my code,

import { FieldType } from '@ngx-formly/core';
import { Component } from '@angular/core';

@Component({
    selector: 'editor',
    template: `<div>
    <p-editor name="p-name" [(ngModel)]="htmlText" (onTextChange)="change($event)" [formControl]="formControl" [style]="{'height': ''}">
    <p-header>
        <span class="ql-formats">
            <button class="ql-bold" aria-label="Bold"></button>
            <button class="ql-italic" aria-label="Italic"></button>
            <button class="ql-underline" aria-label="Underline"></button>
        </span>
        <span class="ql-formats">
        <select title="Text Color" class="ql-color" defaultValue="rgb(0, 0, 0)">
        </select>
        <span class="ql-format-separator"></span>
        <select title="Background Color" class="ql-background" defaultValue="rgb(255, 255, 255)">
        </select>
        </span>
        <span class="ql-formats">
            <button class="ql-link"></button>
            
        </span>
        <span class="ql-formats">
            <button class="ql-list" value="ordered"></button>
            <button class="ql-list" value="bullet"></button>
            <button class="ql-align" value=""></button>
            <button class="ql-align" value="center"></button>
            <button class="ql-align" value="right"></button>
            <button class="ql-align" value="justify"></button>
        </span>
    </p-header>
    </p-editor>
    </div>`
})
export class FormlyEditorFieldComponent extends FieldType {
  htmlText `="<ol><li><strong>Heading </strong></li><li><em>Italic </em></li><li><u>Underlined </u></li></ol><p><br></p><ul><li><span style=\"color: rgb(230, 0, 0);\">Colour </span></li><li><span style=\"background-color: rgb(0, 138, 0);\">Background-colour </span></li><li><a href=\"Link\" rel=\"noopener noreferrer\" target=\"_blank\">Link</a></li></ul><p><br></p><p class=\"ql-align-right\">Right Align</p><p>Left Align</p><p class=\"ql-align-center\">Justify</p>"`
    change(event) {
        if (event) {
            this.to.change(this);
        }
    }
}

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
