### ISSUE TITLE
Missing focus style on p-inputSwitch, p-tree, p-calendar with material design theme

### ISSUE THREAD

**Issue by PeterHewat** [primefaces/primeng#10196]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
With the saga-blue theme: Setting focus to a p-inputSwitch using TAB keyboard navigation does indeed change the style of it.
https://stackblitz.com/edit/primeng-11-4-0-input-switch-focus-theme-saga-blue?file=src/app/app.component.html

Issue: With the mdc-light-indigo theme (or any other MD): Setting focus to a p-inputSwitch using TAB keyboard navigation does not change the style of it.
https://stackblitz.com/edit/primeng-11-4-0-input-switch-focus-theme-mdc-light-indigo?file=src/app/app.component.html

**Minimal reproduction of the problem with instructions**
Use one of the material design themes then try to set focus to a p-inputSwitch using TAB navigation.

**What is the motivation / use case for changing the behavior?**
Better accessibility.

* **Angular version:** 11.2.12

* **PrimeNG version:** 11.4.0

* **Browser:** all

**Comment by PeterHewat** [comment]
The lack of specific focus style in meterial design themes also occurs on p-calendar (see #10195) and p-tree (see #10196) and probably other components.

**Comment by yigitfindikli** [comment]
Moved to https://github.com/primefaces/primeng/issues/10195
