### ISSUE TITLE
Allow to customize only the form creation in FileUpload

### ISSUE THREAD

**Issue by j-be** [primefaces/primeng#10198]
Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
## Current state

Currently, the only possibility to customize the form uploaded by `FileUpload` based on the files  seems to be `customUpload="true" (uploadHandler)="photoUploader($event)"`. But that requires to re-implement a whole lot of features otherwise available out of the box, like `progress`, or `abort`, or stuff like that.

Alternatively, there is `onBeforeUpload`, but that does not allow to modify the file itself, nor does it have access to the files, so one needs to inject `FileUpload` and access the files from there. Works, but cumbersome and kind-of hacky.

## Feature request

I propose to add an additional property `formFactory` which is a function of type `formFactory(files: File[]): FormData`. If not given, the default would kick in, which is basically [this hunk of code](https://github.com/primefaces/primeng/blob/293a4788d29b7ac59d67979b75170730112b0aac/src/app/components/fileupload/fileupload.ts#L365-L373).

I'd be happy to prepare a PR in case this feature proposal is accepted.

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
