### ISSUE TITLE
Showcase page fails to load (related to TreeDemo)

### ISSUE THREAD

**Issue by TekSiDoT** [primefaces/primeng#102]
Attempting to load [main showcase page](http://www.primefaces.org/primeng/) results in:
`EXCEPTION: Component "AppComponent" has no route named "TreeDemo". in [['TreeDemo'] in AppComponent@44:39]`
on Chrome 49.0.2623.87and Firefox 44. Edge on W10 works fine.

**Comment by cagataycivici** [comment]
Please try with clearing your cache. It works for me.

**Comment by TekSiDoT** [comment]
Confirmed, problem was cache related.

**Comment by cagataycivici** [comment]
Thank you.
