### ISSUE TITLE
Disabled p-checkbox can still be toggled with keyboard in beta.17

### ISSUE THREAD

**Issue by ats17** [primefaces/primeng#1020]
To reproduce, add `<p-checkbox binary="true" [disabled]="true"></p-checkbox>` to a page and tab to it. Press the space bar to toggle its checked state.

**Comment by sudheerj** [comment]
Not able to replicate the issue. You can't get the focus to trigger any keyboard events. Please comment out or reopen if you still can replicate the issue.
