### ISSUE TITLE
Multiselect customize header filter

### ISSUE THREAD

**Issue by aliraza923** [primefaces/primeng#10203]
Facing an issue in customizing the multi-select filter section. 
How we can add another filter I have tried to add in <p-head> section but it's not working.
![image](https://user-images.githubusercontent.com/15232866/117140673-1bb6e400-adc7-11eb-933f-42447dc27641.png)

**Comment by yigitfindikli** [comment]
You can use the header template.  `<ng-template pTemplate="header">...`

Please use the forum or discord channel for questions and help requests.

**Comment by Gykonik** [comment]
Hey @yigitfindikli , sorry for asking here but one small question:
As far as i can tell, by using the `template`-part  we can only prepend something. However, the author and I wanted to insert a custom element between the "selectAll-Checkbox" and the "search-Field".
Is this possible somehow?
