### ISSUE TITLE
Badge with circle-like avatar not visible

### ISSUE THREAD

**Issue by pholik** [primefaces/primeng#10202]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

* **Angular version:** 11.2
* **PrimeNG version:** 11.4

I suppose that badge with circle avatar should be available to use. Although badge is hidden when used with avatar styled as circle. Probably something like this should be in the styling of the following class:

```
.p-avatar.p-avatar-circle {
  overflow: visible !important;
}

```

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
