### ISSUE TITLE
p-tabview should allow custom horizontal alignment of tabs

### ISSUE THREAD

**Issue by mattpenner** [primefaces/primeng#10200]
**I'm submitting a ...**  
[x] feature request 

**Expected behavior**
It would be great if the tab positions on p-tabview could be styled such as centered, right, horizontally distributed to fill the width, etc.

**What is the motivation / use case for changing the behavior?**
Currently tabs are formatted only to the left.  This only meets basic behavior for tab components. Allowing for multiple alignments across the tabview would expand the ease and flexibility similar to many of the other components.

* **Angular version:** 11.2.8

* **PrimeNG version:** 11.3.0

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
