### ISSUE TITLE
Tooltip doesn't work on the smaller viewports

### ISSUE THREAD

**Issue by Sampath-Lokuge** [primefaces/primeng#10209]
Hi,

[X ] bug report

Tooltip doesn't work on the smaller viewports. You can see that on your Stackblitz demo too.

Link: https://primeng-tooltip-demo.stackblitz.io/

You can set `iPhoneX` or whatever smaller viewport size. But it is working fine on desktop view.

`package.json`

```

    "@angular/animations": "^11.2.13",
    "@angular/common": "~11.2.0",
    "@angular/core": "~11.2.0",
    "@angular/forms": "~11.2.0",
    "@angular/platform-browser": "~11.2.0",
    "@angular/platform-browser-dynamic": "~11.2.0",
    "@angular/router": "~11.2.0",
    "@capacitor/core": "2.4.7",
    "@ionic/angular": "^5.5.2",
     "primeicons": "^4.1.0",
    "primeng": "^11.4.0",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },

```

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
