### ISSUE TITLE
<p-overlayPanel> in <th> is not displayed button and opened information in small view (<768px) after primeNG update

### ISSUE THREAD

**Issue by evelyscha** [primefaces/primeng#10218]
When using the <p-overlayPanel> component in the table header <th> in small view (<768px), the component is no longer visible and clickable. I can no longer open the information overlay. There is only a little unclickable Button which I can just recognize because of the handcursor.
In desktop-view the component works and has arisen with the Prime NG update.

**Comment by yigitfindikli** [comment]
Issue is not clear, please feel free to reopen with a stackblitz example.

**Comment by evelyscha** [comment]
Because I cant found where to add an stackblitz example I write the code here instead to clearify the problem.
Code:
**<p-table [value]="cars" [paginator]="true" [rows]="5"> <ng-template
		pTemplate="header">
	<tr>
		<th>Id
			<button (click)="op2.toggle($event)" image="information"
				class="icon" title="Informationen"></button>
		</th>
		<th>Brand</th>
		<th>Color</th>
		<th>Year</th>
	</tr>

	</ng-template> <ng-template pTemplate="body" let-rowData let-car>

	<tr [ngClass]="rowData.year > 2017 ? 'color_pale_rose' : null">
		<td>abc</td>
		
		<td><a
			routerLink="/doc">{{car.brand}}</a></td>
		<td>{{car.color}}</td>
		<td [ngClass]="car.year < 2018 ? 'dp_color2' : null"
			class="textAlignRight">{{car.year}}</td>
	</tr>
	</ng-template> </p-table>
<p-overlayPanel #op2 [showCloseIcon]="true" [dismissable]="true"
		ariaCloseLabel="Close"> <ng-template pTemplate>
	This is an information text. Lorem ipsum dolor
	</ng-template> </p-overlayPanel>**
