### ISSUE TITLE
Excel export support for DataTable

### ISSUE THREAD

**Issue by vvvttt** [primefaces/primeng#1021]
Hello,

Currently primeng datatable supports exporting data in csv format. Is there any way this can be exported to excel as well?

Thanks

**Comment by sreverdy** [comment]
That would indeed be great. Also PDF Export would be amazing.

**Comment by Mrtcndkn** [comment]
This feature is on our roadmap we will implement this for sure.

**Comment by cagataycivici** [comment]
Dup of #534
