### ISSUE TITLE
exportPDF doesn't working

### ISSUE THREAD

**Issue by tugbayavuzz** [primefaces/primeng#10210]
<button  type="button" pButton pRipple icon="pi pi-file-pdf" (click)="exportPdf()" class="p-button-warning p-mr-2" pTooltip="PDF" tooltipPosition="bottom"></button>

exportPdf() jsPdf doesnt working. I imported jsPdf

**Comment by yigitfindikli** [comment]
Seems to work in https://primefaces.org/primeng/showcase/#/table/export. And pdf not a built-in feature for PrimeNG it's just an example.

Lastly, please use the forum or discord channel for questions and help requests.
