### ISSUE TITLE
p-table with resizeableColumns="true" does not display p-columnFilters properly

### ISSUE THREAD

**Issue by cosmin19** [primefaces/primeng#10214]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
For p-table with resizeableColumns=true, p-columnFilter with custom templates like _list_ or _multiSelect_ , is displayed boxed indside its cell and is only ~5% visible. If resizeableColumns is set to false, the filters are displayed correctly.

**Expected behavior**
p-columnFilters to be displayed in the same way, no matter if resizeableColumns is true or false

**Minimal reproduction of the problem with instructions**
See stackblitz: https://stackblitz.com/edit/primeng-tablecolresize-filter-demo?file=src%2Fapp%2Fapp.component.html
1. Click on the Code filter and observe how it's displayed
2. Set [resizableColumns]="false"
3. Click again on the Code filter and observe how it's displayed (this time is displayed correctly)

* **Angular version:** 11.1.1

* **PrimeNG version:** 11.4.0

* **Browser:** Chrome
 
Thanks!

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
