### ISSUE TITLE
p-multiSelect - Not showing labels when using optionGroupChildren

### ISSUE THREAD

**Issue by stanislavKacmarik** [primefaces/primeng#10221]
**I'm submitting a ...** 
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-multiselect-demo-jaf3nw

**Current behavior**
In `p-multiSelect` using `[group]="true"` and `optionGroupChildren="data"` leads to undesired behavior such as not showing labels of selected items and not showing labels in search result.

**Expected behavior**

Show currently selected items and filtered items.

**Minimal reproduction of the problem with instructions**
Select any option from `p-multiSelect` with label `Grouped using optionGroupChildren` (first multiselect is there only to compare behavior, when data structure has option labels in field called `items`)
```
<p-multiSelect [options]="groupedCitiesUsingOptionGroupChildren" [group]="true"
  [(ngModel)]="selectedCitiesUsingOptionGroupChildren" defaultLabel="Select a City" scrollHeight="250px"
  optionGroupChildren="data">
</p-multiSelect>
```

**What is the motivation / use case for changing the behavior?**
Properly working with data where options field of an option group are not defined in field `items`

* **Angular version:** 11.0.0

* **PrimeNG version:** 11.3.0

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
