### ISSUE TITLE
p-treetable selection bug

### ISSUE THREAD

**Issue by anton-nikitsiuk** [primefaces/primeng#10228]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://primeng-treetableedit-demo-4dq3zc.stackblitz.io
Check it here for Applications/Angular/backup-1.zip and then open Cloud

**Current behavior**
If you have 2 elements with the same combination of fields, they will be selected everywhere without changing of parent checkbox

**Expected behavior**
Selections should be applied to only one element in a list at once

**Minimal reproduction of the problem with instructions**
https://primeng-treetableedit-demo-4dq3zc.stackblitz.io

* **Angular version:** 11.0.9

* **PrimeNG version:** 11.3.0

* **Browser:** Chrome 90.0.4430.93 (Official Build) (64-bit)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by yigitfindikli** [comment]
If you gonna use checkbox selection with editable you need to use another column.

**Comment by anton-nikitsiuk** [comment]
> If you gonna use checkbox selection with editable you need to use another column.

This bug is totally not about editing, but about selection. And I used your example to reproduce it, just updated the data. You can reproduce it yourself by using the same data for 2 different subvalues
