### ISSUE TITLE
Feature request: Add more abilities to filter Dropdown list

### ISSUE THREAD

**Issue by ctrl-brk** [primefaces/primeng#1022]
As of today it only filters by startsWith. Contains is a must and a custom one would be also helpful.

**Comment by philip-spark5** [comment]
It would be greate if filtering is also performed on the value, not only the label..

**Comment by philip-spark5** [comment]
Maybe You could add the possibility to disable certain options...

Would be much appreciated !

**Comment by Kaffiend** [comment]
I have data sets that are alpha/mixed/numeric and this would be very helpful. something like the column filterMatchMode would be fantastic. with a numeric data set a startsWith or contains is not ideal.

**Comment by yigitfindikli** [comment]
You can use filterMatchMode with the latest PrimeNG.
