### ISSUE TITLE
Opening a nested dialog breaks the escape key to close for the parent dialog

### ISSUE THREAD

**Issue by dasco144** [primefaces/primeng#10225]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-dynamicdialog-demo-msbhbq?file=src/app/productlistdemo.ts

**Current behavior**
When opening a dialog from within another dialog component, the escape key to close the dialog for the first dialog will break.
When trying to close the first dialog without opening a second dialog, the escape key will close the dialog as expected.

**Expected behavior**
When opening a dialog from within another dialog component, the escape key will close the dialog of both the secondary and the parent dialog in order.

**Minimal reproduction of the problem with instructions**

- Click the button to open the first dialog.
- Click the button inside the dialog to open a secondary dialog.
- Press the escape key. The secondary dialog will close
- Press the escape key. The first dialog will not close.
- Close the dialog via the header button
- Click the button to open the first dialog
- Press the escape key. The first dialog will close

**What is the motivation / use case for changing the behavior?**
Nested dialogs should not break functionality of parent dialogs and the escape key should still close the parent dialog

**Please tell us about your environment:**
Windows 10
VSCode
npm

Angular version: 11.2.13

PrimeNG version: 11.4.0

Browser: all

Language: TypeScript 4.1.5

Node (for AoT issues): node --version = v12.20.1

**Comment by dasco144** [comment]
Seems to be related to the zIndex that is being set in the DomHandler.
It fails the check on dynamicdialog.ts#255

**Comment by dasco144** [comment]
Thank you for the update @yigitfindikli. I've checked the v12 milestone and I don't see the issue there. Is there an issue on this repo I can subscribe to for updates?

**Comment by LeonteDenismsgDev** [comment]
Completely unprofessional @yigitfindikli. Was the issue ever fixed since im also having it on the latest primeng version?
