### ISSUE TITLE
tooltip throws error when in ShadowDom

### ISSUE THREAD

**Issue by mdagit** [primefaces/primeng#10227]
See https://stackblitz.com/edit/primeng-tooltip-demo-xk3wa5?file=src/app/app.component.ts

All i did is change to ViewEncapsulation.ShadowDom and the demo breaks with:

Error in /turbo_modules/primeng@11.4.0/bundles/primeng-dom.umd.js (471:70)
Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by omsix** [comment]
Hi, I am facing the same issue in primeng 17.8.11. 
zone.js:1159 Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at a (primeng-dom.mjs:198:47)
    at r.getScrollableParents (primeng-dom.mjs:212:46)
    at Ote.bindScrollListener (primeng-dom.mjs:732:45)
    at r.bindScrollListener (primeng-tooltip.mjs:571:28)
    at r.show (primeng-tooltip.mjs:401:14)
    at r.activate (primeng-tooltip.mjs:306:22)
    at r.onMouseEnter (primeng-tooltip.mjs:271:18)
    at e.invokeTask (zone.js:398:33)
    at ne.runTask (zone.js:158:47)

in primeng-dom.mjs
...
static getScrollableParents(element) {
        let scrollableParents = [];
        if (element) {
            let parents = this.getParents(element);
            const overflowRegex = /(auto|scroll)/;
            const overflowCheck = (node) => {
                let styleDeclaration = window['**getComputedStyle**'](node, null);
                return overflowRegex.test(styleDeclaration.getPropertyValue('overflow')) || overflowRegex.test(styleDeclaration.getPropertyValue('overflowX')) || overflowRegex.test(styleDeclaration.getPropertyValue('overflowY'));
            };
            for (let parent of parents) {
                let scrollSelectors = parent.nodeType === 1 && parent.dataset['scrollselectors'];
                if (scrollSelectors) {
                    let selectors = scrollSelectors.split(',');
                    for (let selector of selectors) {
                        let el = this.findSingle(parent, selector);
                        if (el && overflowCheck(el)) {
                            scrollableParents.push(el);
                        }
                    }
                }
                if (parent.nodeType !== 9 && overflowCheck(parent)) {
                    scrollableParents.push(parent);
                }
            }
        }
        return scrollableParents;
    }
node is a #document-fragment not en element when the element on which the tooltip is defined is nested under a shadow-root node (because of the use of the shadow-dom view encapsulation).
