### ISSUE TITLE
Custom button and function on middle controller of Picklist 

### ISSUE THREAD

**Issue by linhfpt** [primefaces/primeng#10238]
[] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

![image](https://user-images.githubusercontent.com/78027794/118263071-fc633980-b4df-11eb-9884-705f425eb536.png)

I want to custom a new button, and function in middle controller of picklist.
But there is no options like that. So i create this Feature Request, if any one want one, please comment here. 
Thank you guys so much.
So sorry for my bad English.

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
