### ISSUE TITLE
multiselect.show() method won't the dropdown programarly

### ISSUE THREAD

**Issue by irekBudzowski** [primefaces/primeng#10235]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-multiselect-demo-fhtdak

**Current behavior**
`show()` method cant open the dropdown programarly

**Expected behavior**
`show()` method will open the dropdown, as in previous versions of the library

**Minimal reproduction of the problem with instructions**
Use the newest version of the library and try to open the dropdown programarly

**What is the motivation / use case for changing the behavior?**
I was using show method to open the dropdown by other button.

**Please tell us about your environment:**

* **Angular version:** 11.X

* **PrimeNG version:** 11.X

* **Browser:** [all]

 
* **Language:** [all]

**Comment by mountpoint** [comment]
same issue. 
@yigitfindikli can you look at this?

**Comment by ronbiter** [comment]
would be really useful feature. we need this :)

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
