### ISSUE TITLE
Button rounded icon-only large has the wrong size and is stretched, button rounded small icon-only does not change size

### ISSUE THREAD

**Issue by demike** [primefaces/primeng#10230]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/primeng-button-demo-luv8pq?file=src%2Fapp%2Fapp.component.html

**Current behavior**

Button rounded icon-only large has the wrong size and is stretched
Button rounded small does not change size
The stackblitz example shows this behaviour and how it should be 

**Expected behavior**

p-button-lg and p-button-sm on an icon only rounded button should be sized like the non icon-only versions.

**Minimal reproduction of the problem with instructions**

use a  p-button-lg or p-button-sm on a rounded icon-only button
```
<button pButton pRipple type="button" icon="pi pi-check" class="p-button-rounded p-button-lg"></button>
```
https://stackblitz.com/edit/primeng-button-demo-luv8pq?file=src%2Fapp%2Fapp.component.html

* **Angular version:** 11.X

* **PrimeNG version:** 11.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by Bogatejc** [comment]
@cetincakiroglu I think this is still an issue, if open stackblitz from https://www.primefaces.org/primeng/button and make the following buttons:
```
<div class="sizes">
  <button pButton pRipple icon="pi pi-check" class="p-button-sm p-button-rounded"></button>
  <button pButton pRipple icon="pi pi-check" class="p-button p-button-rounded"></button>
  <button pButton pRipple icon="pi pi-check" class="p-button-lg p-button-rounded"></button>
</div>
```
They look like this: 
![image](https://user-images.githubusercontent.com/31507012/207252026-ec062c45-1a30-4ede-a5f8-87616895bef7.png)
