### ISSUE TITLE
Sidebar - ngOnDestory throws an exception

### ISSUE THREAD

**Issue by dloprodu** [primefaces/primeng#10247]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
In version 11.4.1 and 11.4.2, the Sidebar componenet throws an exception on its ngOnDestory method when the appendTo input is defined.

![image](https://user-images.githubusercontent.com/664947/118492920-77af3000-b718-11eb-8de1-979f13dd9945.png)

* **Angular version:** 11.2.4

* **PrimeNG version:** 11.4.2

* **Browser:** [all ]

 
* **Language:** [TypeScript 4.0.2]

* **Node (for AoT issues):** `node --version` =

**Comment by jonnomk** [comment]
Can this please be fixed for version 11?  We can't upgrade Angular to 12 yet...

**Comment by ShrihariMohan** [comment]
A simple hack I used for this we're using the `drawyerVisible` to show/hide the sidebar. The same goes for `[appendTo]` also. 
``` 
<p-sidebar position="bottom" [appendTo]="drawyerVisible?'body':''"  [(visible)]="drawyerVisible" [showCloseIcon]="true">

```
