### ISSUE TITLE
primeng-dropdown.d.ts.Dropdown.html:21 ERROR Error: Expecting instance of DOM Element

### ISSUE THREAD

**Issue by JulyJuli** [primefaces/primeng#10240]
I try to use paginator dropdown in the table. On element click I receive the next error.
![![image](https://user-images.githubusercontent.com/34139003/118295355-6a116480-b4e4-11eb-850f-00cc3d43336b.png)](https://user-images.githubusercontent.com/34139003/118295230-48b07880-b4e4-11eb-802f-9afb94c613bf.png)
![image](https://user-images.githubusercontent.com/34139003/118295267-52d27700-b4e4-11eb-82f4-0cf05610a1a4.png)

I tried to debug paginator example on [Stackbiz](https://stackblitz.com/edit/primeng-paginator-demo-z6fcke) but here is another renderer for this component:
![image](https://user-images.githubusercontent.com/34139003/118295493-9927d600-b4e4-11eb-8cd6-fa77a454c1ba.png)

Frankly, I can't understand how this renderer can be changed.

Use Angular 11.

Can somebody help?

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.

**Comment by capc0** [comment]
@JulyJuli did you found a fix for this? We are having the same problem with Prime 11 and Angular 11

**Comment by JulyJuli** [comment]
@capc0 The problem was related to **enableIvy** configuration. It is required to set it as 'true', otherwise, you won't be able to work with some of the animation-related components! 
I hope it helps
