### ISSUE TITLE
Datatable : Expand by clicking on a row

### ISSUE THREAD

**Issue by harilalinapp** [primefaces/primeng#1024]
Is it possible to expand by clicking on a particular row?

**Comment by patriknil90** [comment]
This worked for me: [http://forum.primefaces.org/viewtopic.php?f=35&t=47145](http://forum.primefaces.org/viewtopic.php?f=35&t=47145)

**Comment by johnmanko** [comment]
You can also add `selectionMode="none" ` to get the nice hover styling.

```
<p-dataTable [value]="list" 
            #myTable
            expandableRows="true"
            selectionMode="none" 
            (onRowClick)="myTable.toggleRow($event.data)">
```

**Comment by cagataycivici** [comment]
Please use forum for support requests.
