### ISSUE TITLE
Angular 12 support

### ISSUE THREAD

**Issue by Rotzbua** [primefaces/primeng#10242]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
npm 7 throws an error because peer dependency does not include new angular version 12.
Release news about angular 12: https://blog.angular.io/angular-v12-is-now-available-32ed51fbfd49

**Expected behavior**
no error

**Minimal reproduction of the problem with instructions**
> npm install

**What is the motivation / use case for changing the behavior?**

Support of angular 12 and usage without `--force`.

**Please tell us about your environment:**

* node 16.1.0
* npm 7.13.0
* angular 12.0.0

No compile errors / incompatibilities observed.
File to change: 
https://github.com/primefaces/primeng/blob/dcb17a4cf52a2c3b1faddd8862d86d6687261305/src/app/components/package.json#L18

**Comment by yigitfindikli** [comment]
Hi @Rotzbua,

Angular 12 is our priorty. Thanks for the feedback and PR. PrimeNG v12 is coming soon.

Best Regards.
