### ISSUE TITLE
Tree node is selected on route canDeactivate false

### ISSUE THREAD

**Issue by johnmanko** [primefaces/primeng#10241]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/tree-node-select-on-candeactivate-false?file=src/app/app.component.html

**Current behavior**
When a navigation route is cancelled via a false `canDeactivate`, a tree node remains selected.

**Expected behavior**
Hook into navigation events and don't select a node if a navigation is cancelled.

**Minimal reproduction of the problem with instructions**
Run StackBlitz example above.  Expand the tree and select "Page 2".  The console will show the message "Page 2 not allowed from page 1" but the tree's "Page 2" node is selected.

![image](https://user-images.githubusercontent.com/3154748/118301321-ebe79a80-b4b0-11eb-930b-508a4627efe6.png)

**What is the motivation / use case for changing the behavior?**
Use the tree to navigate an application's routes.

**Please tell us about your environment:**
Ubuntu Linux 12.10, Netbeans 12.3, VSCode 1.56.2

* **Angular version:** 5.X
11.2

* **PrimeNG version:** 5.X
11.4.0

* **Browser:** 
Chromium 90.0.4430.212, Firefox 88.0.1
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 4.1.5

* **Node (for AoT issues):** `node --version` =   
v14.15.1

**Comment by johnmanko** [comment]
Just writing to say that I'm still interested in a fix for this if that's any consideration for prioritizing.  Thanks for your effort!  :)

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by johnmanko** [comment]
@cetincakiroglu This is still an issue.
