### ISSUE TITLE
Datatable: editable property not working with selection prperty

### ISSUE THREAD

**Issue by vishal3007** [primefaces/primeng#1025]
If selectionMode is on for datatable, editable is not working.

Please see the below code snippet.

```
<p-dataTable [value]="roles" [headerRows]="headerRows"
    selectionMode="single" [(selection)]="selectedRole" (onRowSelect)="onRoleSelected()"
    (onRowUnselect)="onRoleUnSelected()" [editable]="true">
    <p-column field="name" [editable]="true"></p-column>
    <p-column field="description" [editable]="true"></p-column>
</p-dataTable>
```

**Comment by vvvttt** [comment]
The way I got it worked is by adding an extra column (check box) and setting selectionMode property on it rather than on the dtatable.

<p-column [style]="{'width':'38px'}" selectionMode="multiple"></p-column>

**Comment by vishal3007** [comment]
thanks vvvttt...I am trying to do the same thing but I only want to edit the selected row. 
How did you restrict the user to edit the column of non selected row?

**Comment by vvvttt** [comment]
Hey vishal3007,

I haven't implemented this feature since I am not restricting users
 from editing non selected rows.

Thanks.

**Comment by GopiAnnan** [comment]
I do have the same issue, Editable is not working

**Comment by hiteshanchan** [comment]
Same issue for me as well. I want to allow user to select multiple rows to delete in an editable table.

**Comment by cagataycivici** [comment]
This combination is not supported, better use a radio-checkbox because both bind to click event causing the conflict. Selection with a separate column like radio-checkbox-button will be the better solution. Even if we support it, I see a UX issue down the road.

**Comment by mniederkofler** [comment]
Even though this seems like a rare usecase, we have also run into this problem:

In our application we want to highlight the currently selected row (single select), to emphasize which row the user is currently working on. The application will also display additional information of the selected row in the footer (detail section). At the same time the application should allow to edit certain fields.

I would like to ask for your reasons to close this as an unsupported usecase, when the workaround described in https://github.com/primefaces/primeng/issues/1011 works and looks reasonably well:
![image](https://user-images.githubusercontent.com/2385453/26880118-b097b378-4b93-11e7-8ce8-e3c03ca7b976.png)

For us this workaround would be sufficient for our usecase to have editable=true and selectionMode=single at the same time.

Please reconsider your decision, if you have some time. Other than that, keep up the great work. :-)

**Comment by fxmfr** [comment]
@mniederkofler I do absolutely agree.
For us it's even a very common usecase having the row selected which is currently being edited. Especially when working in master detail scenarios.

I have seen this in a lot of applications and think it's much better UX than clicking a checkbox or radio somewhere in the datatable.

Would be great to have this feature.
Thanks for your great work!

**Comment by SpiderPork** [comment]
I vote for this.

**Comment by mmlitvin** [comment]
My vote as well

**Comment by sviswanathjcet** [comment]
I vote for it
