### ISSUE TITLE
ForceSelection doesn't work

### ISSUE THREAD

**Issue by AuthorProxy** [primefaces/primeng#10250]
`forceSelection` doesn't work with objects in `selectedValue`/`suggestions`, even when the `field` is provided

`Grouped` and `Multiple` on the example below

https://codesandbox.io/s/gifted-kowalevski-24jic?file=/src/demo/AutoCompleteDemo.js

**Comment by yigitfindikli** [comment]
You're reporting the wrong project. You can report at https://github.com/primefaces/primereact :)
