### ISSUE TITLE
Trigger an event on primeng multiselect dialog close

### ISSUE THREAD

**Issue by zubair-saif** [primefaces/primeng#10251]
i want to send request to api when multiselect dialog closed i try it these method but not working for me 

![image](https://user-images.githubusercontent.com/11749126/118626696-87944600-b7e4-11eb-8744-e6cad6539e5e.png)

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
