### ISSUE TITLE
InputNumber: Can't type zero after decimal point

### ISSUE THREAD

**Issue by Ravatsaas** [primefaces/primeng#10253]
https://www.primefaces.org/primeng/showcase/#/inputnumber

In the Min-Max Fraction Digits input, try to change the value from 2,351.35 to 2,351.35001

It will not let you input the zero characters.

**Comment by mertsincan** [comment]
Hi,

I think this issue has been fixed in 12.1.1.

For now, closed. If the problem persists, please reopen this ticket.
Best Regards,
