### ISSUE TITLE
PanelmMenu : Problem with ARIA[role] Accessiblity

### ISSUE THREAD

**Issue by hamza-aniba** [primefaces/primeng#10254]
**Current behavior**
The problem appears when I use **Lighthouse** to test the **accessibility** of the showcase web application : 
**ARIA** - These are opportunities to improve the usage of ARIA in your application which may enhance the experience for users of assistive technology, like a screen reader.

- Elements with an ARIA [role] that require children to contain a specific [role] are missing some or all of those required children:

>  Some ARIA parent roles must contain specific child roles to perform their intended accessibility functions.

- [ role ]s are not contained by their required parent element:

> Some ARIA child roles must be contained by specific parent roles to properly perform their intended accessibility functions.

**Expected behavior**
 Without the bug we will have **100%** at the Lighthouse test level for **Accessiblity** .

**What is the motivation / use case for changing the behavior?**
We need a solution to be successful at level A of the rule : **Meaningful Sequence** of the **Accessiblity** and to be **W3C** compliant.

**Please tell us about your environment:**

* **Angular version:** 9 / 11
Windows 10 Pro, VSCode

* **PrimeNG version:** 9 / 11

* **Browser:** all 
 
* **Language:** TypeScript

**Comment by yigitfindikli** [comment]
Upcoming versions focus on accessibility where each component will get new sections for keyboard and screen reader support along with the improvements. We'll be checking with accessibility tools for 100% compliancy.
