### ISSUE TITLE
p-tree horizontal filter 

### ISSUE THREAD

**Issue by linhfpt** [primefaces/primeng#10265]
`[ ] bug report => Search github for a similar issue or PR before submitting

[*] feature request => Please check if request is not on the roadmap already 
https://github.com/primefaces/primeng/wiki/Roadmap

[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
`

Does the current filter work with horizontal one?
In my case its does not work at all.
Have any one have any idea for this situation?
Thank you guys for reading this.
If anyone have any ideas for this. please advice me.
The idea is when filter has fill, the node will expand and highlight.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
