### ISSUE TITLE
LazyLoadEvent is legacy interface, not current

### ISSUE THREAD

**Issue by PHuhn** [primefaces/primeng#10269]
[X] bug report

**Current behavior**

I have an application that uses Lazy and also uses column filters.  I also can demo the application using hard coded mock data.  I have written stuff to emulate the backend.  But the LazyLoadEvent interface and the output in my option differ.  The observed output is as follows:

```filters:
NoteTypeDesc: Array(1)
0: {value: "ISP", matchMode: "contains", operator: "and"}
length: 1
__proto__: Array(0)
NoteTypeShortDesc: Array(1)
0: {value: "I", matchMode: "startsWith", operator: "and"}
length: 1
__proto__: Array(0)
```

The declaration of the interface is as follows:

```import { SortMeta } from './sortmeta';
import { FilterMetadata } from './filtermetadata';
export interface LazyLoadEvent {
    first?: number;
    rows?: number;
    sortField?: string;
    sortOrder?: number;
    multiSortMeta?: SortMeta[];
    filters?: {
        [s: string]: FilterMetadata;
    };
    globalFilter?: any;
}
```

As I see it the output has an array of FilterMetadata, but the interface doesn't.  If I am reading your code correctly the interface represents a legacy implementation.

**What is the motivation / use case for changing the behavior?**

Angular is moving towards strict, and it is hard to impossible to pass strict when the output does not match the interface declarations.

**Please tell us about your environment:**

- Windows 10 Pro: 20H2 - 19042.985
- Angular version: 11.2.9
- PrimeNG version: 11.4.1
- Browser: Chrome: 90.0.4430.212  
- TypeScript: 4.1.5
- Node: 14.15.5

**Comment by m11t** [comment]
I think this is a duplicate of #10055

**Comment by PHuhn** [comment]
Hey I agree with m11t that this is a duplicate.  I'm glad that someone else agreed with my observation.  I liked the suggested solution.
