### ISSUE TITLE
TurboTable sort not working on first row

### ISSUE THREAD

**Issue by jmhg92** [primefaces/primeng#10268]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**

When sorting TurboTable using default mode the first row doesn't seem to display in the correct order. I have checked the data using `onSort` function and the array is correctly sorted, it's just the first row that's not displayed in the correct order.

I thought this could be an problem with just this table (bad coding or something) but it seems that another table in the same project suffers from the same issue.

And I can't update to the latest version so I'm stuck with 8.1.1 (no LTS because of licensing).

**Expected behavior**

Correct sorting order for all rows.

**Minimal reproduction of the problem with instructions**

Here is a snippet of my code:

    <p-table id="dtTest" #dtTest[value]="listnData" dataKey="id" [responsive]="true" [paginator]="true" [rows]="5" (onSort)="onSort($event)">
      <ng-template pTemplate="header">
        <tr>
          <th [pSortableColumn]="'id'" style="width: 70px;" [attr.rowSpan]="2">
            ID
            <p-sortIcon [field]="'id'"></p-sortIcon>
          </th>
          <th [pSortableColumn]="'name'">
            Name
            <p-sortIcon [field]="'name'"></p-sortIcon>
          </th>
        </tr>
        <tr>
          <th>
            <input type="text" pInputText [ngStyle]="{'width': '100%'}" placeholder="Search" (input)="dtTest.filter($event.target.value, 'name', 'contains')" (click)="clickOnFilter($event)"/>
          </th>
        </tr>
      </ng-template>
      <ng-template pTemplate="body" let-rowData>
        <tr>
          <td>{{rowData.id}}</td>
          <td>{{rowData.name}}</td>
        </tr>
      </ng-template>
    </p-table>

Example 1: Sorting from greatest to least
![error_table_sort_g-l](https://user-images.githubusercontent.com/20491257/119162594-2d7fc480-ba20-11eb-8db9-ac6ce81d8aa7.png)

Example 2: Sorting from least to greatest
![error_table_sort_l-g](https://user-images.githubusercontent.com/20491257/119162611-32447880-ba20-11eb-8262-aca8932e2c6a.png)

**Please tell us about your environment:**

* **Angular version:** 8.2.14

* **PrimeNG version:** 8.1.1

* **Browser:**

Chrome: 90.0.4430.212 (Official Build) (64-bit)
Firefox: 88.0.1 (64-bit)
Edge (Chromium): 90.0.818.66 (Official build) (64-bit)
 
* **Language:**
TypeScript: 3.5.3

* **Node (for AoT issues):** `node --version` =  v14.16.0

**Comment by yigitfindikli** [comment]
Unable to replicate with latest PrimeNG, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again
