### ISSUE TITLE
Sidebar header text in the wrong place

### ISSUE THREAD

**Issue by 2ne** [primefaces/primeng#10266]
[x ] bug report

https://primefaces.org/primeng/showcase/#/sidebar (12.0.0-rc1)

Affects 11.3.2 - 12.0.0-rc1

**Current behavior**
Header is appended to the wrong place in the markup

**Expected behavior**
Was working fine here.

https://primeng-sidebar-demo.stackblitz.io (11.3.0)

**Comment by yigitfindikli** [comment]
The sidebar is remastering for new versions. This is by design.

**Comment by 2ne** [comment]
![sidebar](https://user-images.githubusercontent.com/2843638/119221701-6b482000-bae8-11eb-91e3-e9485180a1a3.PNG)

Ok so the text and the close icon are purposely not aligned as seen here https://primefaces.org/primeng/showcase/#/sidebar ?

**Comment by pclancy** [comment]
Any workaround for this "feature"?
