### ISSUE TITLE
p-calendar internal format

### ISSUE THREAD

**Issue by ilianiv** [primefaces/primeng#1026]
Existing `dateFormat` input is nice because I can transform and display my model's dates (that are in ISO 8601) as dd.mm.yy which is more user friendly. 

The problem is when I use p-calendar to edit the model. It breaks my model because calendar component sets my dates as dd.mm.yy which is not compatible with angular2's DatePipe, my API, etc ...

Maybe an additional input like `internalFormat` will help. This may be the format that binds with ngModel.

jQuery UI Datepicker has this feature: [dateFormat](http://api.jqueryui.com/datepicker/#option-dateFormat) for parsing and diplaying and an optional [altFormat](http://api.jqueryui.com/datepicker/#option-altFormat) that overrides format shown to the user.

**Comment by cagataycivici** [comment]
So you want to use dd.mm.yy for dateFormat when displaying and need an alternative format? Does 1230 and 1231 help your case as well? Can you give us a detailed example with dateFormat, internalFormat and so on.

**Comment by ilianiv** [comment]
Yes. The idea was Calendar component to be able to work with 2 formats (display format and binded model format). #1230 & #1231 seem to fix this. I'll try it when rc4 gets released.

**Comment by cagataycivici** [comment]
Thanks, closing for now, please drop a comment if necessary after RC4 (tomorrow)
