### ISSUE TITLE
Wrong information in documentation regarding carousel component

### ISSUE THREAD

**Issue by Greeshmareji** [primefaces/primeng#10264]
showIndicators and showNavigators default value of carousel component is provided as false in documentation(https://www.primefaces.org/primeng/showcase/#/carousel), but in reality, the default value is true.

**Comment by mshnajar** [comment]
Exactly right, even in the code they ware default to true.
Also there is another major problem: When you put them to false they don't work:
[showIndicators]="false" [showNavigators]="false"

**Comment by yigitfindikli** [comment]
Fixed for next release.
