### ISSUE TITLE
OverlayPanel inside a Dialog is shifted with some offset

### ISSUE THREAD

**Issue by Jin-K** [primefaces/primeng#10279]
**I'm submitting a ...** 
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/primeng-overlaypanel-demo-uffhnq

**Current behavior**
The OverlayPanel has an extra offset when opened inside a Dialog, the OverlayPanel receives a wrong absolute position.

**Expected behavior**
The OverlayPanel should be positioned correctly

**Minimal reproduction of the problem with instructions**
1. Create a visible p-dialog as wrapper
2. Add a p-button, a p-overlayPanel and bind the toggle/open method
3. If you click on the button, you should notice that the panel is shifted to the right.

**Please tell us about your environment:**

* **Angular version:** 11.0.9

* **PrimeNG version:** 11.3.0

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
