### ISSUE TITLE
Is it a < p-inputnumber > bug or a Microsoft Pinyin input method bug？？？？

### ISSUE THREAD

**Issue by LuoYingxiong** [primefaces/primeng#10276]
In the Chinese mode of Microsoft Pinyin input method, when I input numbers in <p-inputnumber>, the oninput event cannot be triggered. But Sogou input method is no problem!!!!

My environment

Operating system version: Windows 10 professional

Primeng version: 8.0.2

The < p-inputnumber > component is copied from the source code of V10 lts to the project. At first I suspected that it was replication. Later, the < p-inputnumber > test of V10 lts version also failed to trigger the (oninput) event

**Comment by yigitfindikli** [comment]
Issue is not clear, please feel free to reopen with a stackblitz example.

**Comment by LuoYingxiong** [comment]
Without writing a demo, the demo on the official website can test the above bugs. Even the latest version
