### ISSUE TITLE
p-dialog breakpoints is not working

### ISSUE THREAD

**Issue by szabto** [primefaces/primeng#10270]
[x] bug report

**Current behavior**
Cannot use the correct form of `breakpoints` in `p-dialog` component because of its type.
The type is currently an `any[]` which should be an `object`.

`[breakpoints]="{'960px': '75vw', '640px': '100vw'}"`
Got error: Object literal may only specify known properties, and '"960px"' does not exist in type 'any[]'.

**Expected behavior**
The type of the breakpoints property should be changed to `{}`

**What is the motivation / use case for changing the behavior?**
I wanted to make my dialog responsive, like in the example.

**Please tell us about your environment:**
* **Angular version:** 11.2.4
* **PrimeNG version:** 11.3.2
* **Browser:** all
* **Language:** TypeScript 4.1.5
* **OS:** MacOS Big Sur

**Comment by jerrypp** [comment]
I have the same problem

**Comment by seralej** [comment]
Hello all, im new at developing and having the reported issue, how can i solve it?

**Comment by Szanik** [comment]
+1

**Comment by mohdsaad17** [comment]
@seralej Just make sure that you are using primeng version 12 or above and it will be resolved.(Check in your package.json file).
