### ISSUE TITLE
pInputNumber poor behavior

### ISSUE THREAD

**Issue by ghost** [primefaces/primeng#10283]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request 
```
I read in this issue that pInputNumber not update ngModel everytime:
https://github.com/primefaces/primeng/issues/9223

Is it possible to revert to previous behavior or leave this choice to the developer? It's the basic behavior that a input update the ngModel when the user type.
I read I can use the "onInput" event and I know I can write something like
```
<p-inputNumber [ngModel]="myModel" (onInput)="myModel = $event.value">
</p-inputNumber>
```
But this bypass the validation of course.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
