### ISSUE TITLE
Ptime NG node module issues

### ISSUE THREAD

**Issue by neha18saxena** [primefaces/primeng#10288]
Hi  I am facing issue while integrating Prime ng with Angular all node modules of prime ng are failing . However i have deleted and reinstall but issue not solved
My package.json is below
{
  "name": "cnx-query-designer",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~11.2.12",
    "@angular/common": "~11.2.12",
    "@angular/compiler": "~11.2.12",
    "@angular/core": "~11.2.12",
    "@angular/forms": "~11.2.12",
    "@angular/platform-browser": "~11.2.12",
    "@angular/platform-browser-dynamic": "~11.2.12",
    "@angular/router": "~11.2.12",
    "font-awesome": "^4.7.0",
    "primeicons": "^4.1.0",
    "primeng": "^12.0.0-rc.1",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^12.0.2",
    "@angular/cli": "~11.2.11",
    "@angular/compiler-cli": "~11.2.12",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.1.5"
  }
}

Please help me

**Comment by yigitfindikli** [comment]
Please use the forum or discord channel for questions and help requests.

**Comment by neha18saxena** [comment]
Hi Team , I am not able to integrate Prime ng library.getting following error of nodemodules.
Error: node_modules/primeng/tooltip/tooltip.d.ts:75:21 - error TS2694: Namespace '"C:/QueryDesigner/CNX-Query-Designer/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

75     static ɵfac: i0.ɵɵFactoryDeclaration<TooltipModule, never>;
                       ~~~~~~~~~~~~~~~~~~~~


Error: node_modules/primeng/tooltip/tooltip.d.ts:76:21 - error TS2694: Namespace '"C:/QueryDesigner/CNX-Query-Designer/node_modules/@angular/core/core"' has no exported member 'ɵɵNgModuleDeclaration'.

76     static ɵmod: i0.ɵɵNgModuleDeclaration<TooltipModule, [typeof Tooltip], [typeof i1.CommonModule], [typeof Tooltip]>;       
                       ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/primeng/tooltip/tooltip.d.ts:77:21 - error TS2694: Namespace '"C:/QueryDesigner/CNX-Query-Designer/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectorDeclaration'.

77     static ɵinj: i0.ɵɵInjectorDeclaration<TooltipModule>;
                       ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/primeng/tristatecheckbox/tristatecheckbox.d.ts:35:21 - merror TS2694: Namespace '"C:/QueryDesigner/CNX-Query-Designer/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

35     static ɵfac: i0.ɵɵFactoryDeclaration<TriStateCheckbox, never>;
                       ~~~~~~~~~~~~~~~~~~~~


Error: node_modules/primeng/tristatecheckbox/tristatecheckbox.d.ts:36:21 - error TS2694: Namespace '"C:/QueryDesigner/CNX-Query-Designer/node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDeclaration'.

36     static ɵcmp: i0.ɵɵComponentDeclaration<TriStateCheckbox, "p-triStateCheckbox", never, { "disabled": "disabled"; "name": "name"; "ariaLabelledBy": "ariaLabelledBy"; "tabindex": "tabindex"; "inputId": "inputId"; "style": "style"; "styleClass": "styleClass"; "label": "label"; "readonly": "readonly"; "checkboxTrueIcon": "checkboxTrueIcon"; "checkboxFalseIcon": "checkboxFalseIcon"; 
}, { "onChange": "onChange"; }, never, never>;
                       ~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/primeng/tristatecheckbox/tristatecheckbox.d.ts:39:21 - error TS2694: Namespace '"C:/QueryDesigner/CNX-Query-Designer/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

39     static ɵfac: i0.ɵɵFactoryDeclaration<TriStateCheckboxModule, never>;
                       ~~~~~~~~~~~~~~~~~~~~


Error: node_modules/primeng/tristatecheckbox/tristatecheckbox.d.ts:40:21 - error TS2694: Namespace '"C:/QueryDesigner/CNX-Query-Designer/node_modules/@angular/core/core"' has no exported member 'ɵɵNgModuleDeclaration'.

40     static ɵmod: i0.ɵɵNgModuleDeclaration<TriStateCheckboxModule, [typeof TriStateCheckbox], [typeof i1.CommonModule], [typeof TriStateCheckbox]>;
                       ~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/primeng/tristatecheckbox/tristatecheckbox.d.ts:41:21 - error TS2694: Namespace '"C:/QueryDesigner/CNX-Query-Designer/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectorDeclaration'.

41     static ɵinj: i0.ɵɵInjectorDeclaration<TriStateCheckboxModule>;
