### ISSUE TITLE
Table with scrollHeight set will always show scrollbar even if no or only a few records

### ISSUE THREAD

**Issue by olingerc** [primefaces/primeng#10289]
**I'm submitting a ...**  (check one with "x")
```
x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-pg9dvz

![image](https://user-images.githubusercontent.com/5046645/120338647-b9350300-c2f4-11eb-84f9-41b9b73c92a3.png)

**Current behavior**
As soon as scrollHeight is set on a table, a scrollbar is always shown even if no or only a few records

**Expected behavior**
Only show scroll bar if there is scrolling possible
I am on the latest 11.x.x versions for primeng and angular

I guess the problem comes from this line in the primeng code:
`html
            <div #scrollBody class="p-datatable-scrollable-body" [ngStyle]="{'max-height': dt.scrollHeight !== 'flex' ? scrollHeight : undefined, 'overflow-y': !frozen && dt.scrollHeight ? 'scroll' : undefined}">
`
`overflow-y` should be "auto" and not "scroll" I guess

[Here ](https://github.com/primefaces/primeng/blob/003d8eb55ffa4d121300d9b9875aa809b69ad1d3/src/app/components/table/table.ts#L2320)is the link

**Comment by yigitfindikli** [comment]
Hi @olingerc, 

New ScrollTable covers this issue too and we'll introduce the new ScrollTable in v12.1.0.
