### ISSUE TITLE
overlay of each calendar input appears when user presses enter in one of the form's input fields

### ISSUE THREAD

**Issue by stiekemaj** [primefaces/primeng#10287]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
We can reproduce the issue on PrimeNG's calendar demo page:

https://primefaces.org/primeng/showcase/#/calendar

**Current behavior**
When opening the calendar showcase and changing the focus to one of input fields, all calendar overlays appears when the user presses the enter key.
We can reproduce this issue only on some of our environments, specifically macos machines which are running on Macos 11.3.1 and Google Chrome 91.0.4472.77. 
On Macos 11.4 and 11.2.3, we weren't able to reproduce this issue. 

**Please tell us about your environment:**

Macos 11.3.1
Chrome  91.0.4472.77. 

<img width="1680" alt="Screenshot 2021-06-01 at 14 11 49 (2)" src="https://user-images.githubusercontent.com/5552137/120323376-b7177800-c2e5-11eb-9546-74ed3953eb50.png">

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
