### ISSUE TITLE
Splitter error : Cannot read property '0' of undefined at Splitter.onResize

### ISSUE THREAD

**Issue by Blafy** [primefaces/primeng#10286]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/primeng-splitter-demo-xwz81m

**Current behavior**
Moving the splitter to the left repeatedly throws an error 
"TypeError: Cannot read property '0' of undefined
at Splitter.onResize (splitter.ts:147)

**Expected behavior**
No error thrown

**Minimal reproduction of the problem with instructions**
Like I said in https://github.com/primefaces/primeng/issues/10176, you need to drag the splitter from right to the very far left (further than the div) several times (a dozen) to make it happen.

**What is the motivation / use case for changing the behavior?**
I'm not sure here, but it seems that 'event.changedTouches' is undefined sometimes

**Please tell us about your environment:**
Windows 10

* **Angular version:** 
11.0.9

* **PrimeNG version:** 5.X
11.4.2

* **Browser:** 
Edge 91.0.864, Firefox 88.0.1
 
* **Language:**
TypeScript 4 

* **Node (for AoT issues):** `node --version` =  12

**Comment by rsohi** [comment]
As pointed by @Blafy the issue still persist in the new version. One tip to replicate keep the dragging to outside the div and do not mouseup
