### ISSUE TITLE
bug with ConfirmPopup

### ISSUE THREAD

**Issue by sourdoth** [primefaces/primeng#10285]
[ X] bug report => Search github for a similar issue or PR before submitting

hi, when there are multiple buttons that call the method to open the confirmPopup dialog, it does not close and leaves the focus on the first button

for example, I have a delete button in each row of the table that calls this.confirmationService.confirm (object) and sends it the rowdata. Clicking on another button in another row does not close the first dialog but I changed the value of rowdata

![image](https://user-images.githubusercontent.com/29101756/120245920-c2629900-c23c-11eb-84d9-cdc196b0fb42.png)

i try to execute method close but not work
      this.confirmationService.close();

I hope that clicking on another button that calls the confirm method closes the previous popup, thanks

**Comment by yigitfindikli** [comment]
Issue is not clear, please feel free to reopen with a stackblitz example.
