### ISSUE TITLE
How to Positioning DynamicDialog into a container div

### ISSUE THREAD

**Issue by lenichols** [primefaces/primeng#10292]
I want to attach my dynamic popup too a container so that it centers correctly on my page with a sidebar.

```
    const ref = this.dialogService.open(PrintexportComponent, {
        data: {
            id: '51gF3'
        },
        header: 'Export/Print',
        width: '25%'
    });
```

How would i do that?

**Comment by yigitfindikli** [comment]
Please use the forum or discord channel for questions and help requests.
