### ISSUE TITLE
PrimeNG Compiled under strict mode

### ISSUE THREAD

**Issue by PHuhn** [primefaces/primeng#10297]
[X] feature request

**Note **

I do not know where the roadmap is, and you do not instruct where it is. 

**Feature**

I would like the PrimeNG library created using strict mode.

**What is the motivation / use case for changing the behavior?**

Angular CLI is pushing the use of strict mode.

**Please tell us about your environment:**

- Windows 10 Pro: 20H2 - 19042.985
- Angular version: 12.0.1
- PrimeNG version: 12.0.0-rc.1
- Browser: Chrome: 90.0.4430.212
- TypeScript: 4.2.3
- Node: 14.15.

**Comment by ccit-spence** [comment]
Base on this request, is it safe to say you can't use PrimeNG in strict mode?  I have tried a few Prime Blocks in strict mode and it will not compile.

**Comment by PHuhn** [comment]
I am building my applications in strict mode.  In a few case I find I can't test because of problems with your code.  I outlined one of those in the following request: [LazyLoadEvent is legacy interface, not current #10269](https://github.com/primefaces/primeng/issues/10269)

**Comment by ccit-spence** [comment]
I am not with PrimeTek, I am here because I have had the same problem.  Many examples and the new PrimeBlocks don't play well with strict mode.  At least that has been my experience.  I usually end up turning off strict mode.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
