### ISSUE TITLE
bug confirmPopUp

### ISSUE THREAD

**Issue by sourdoth** [primefaces/primeng#10291]
[ X] bug report => Search github for a similar issue or PR before submitting

hi, when there are multiple buttons that call the method to open the confirmPopup dialog, it does not close and leaves the focus on the first button

stackblitz example:

https://stackblitz.com/edit/primeng-confirmpopup-demo-bu3qdh?file=src/app/app.component.html

demo:

https://primeng-confirmpopup-demo-bu3qdh.stackblitz.io

I hope that clicking on another button that calls the confirm method closes the previous popup, thanks

**Comment by yigitfindikli** [comment]
Hi @sourdoth,

Thanks for your report. 12.1.0 will be covering this issue too. Stay tuned!
