### ISSUE TITLE
Autocomplete in datatable expands for all the rows.

### ISSUE THREAD

**Issue by vvvttt** [primefaces/primeng#1029]
Hello,
I am rendering autocomplete in datatable. When I expand the Autocomplete for one row, it expands autocomplete  for all the rows of the datatable. Do I need to to set some property so that it expands only for the selected row?

![image](https://cloud.githubusercontent.com/assets/22157158/19129067/bc44fe92-8afa-11e6-8d67-3693ca81b5c0.png)

Appreciate your help!

Thanks.

**Comment by ralexandrec** [comment]
Seems to be a kind of component isolation. I get this fixed by using an filteredItems to each items of the list.
But it looks like a code smell...

**Comment by cagataycivici** [comment]
Unable to replicate without a plunkr. Please provide a plunkr if issue happens again.

http://plnkr.co/edit/VZbdZfQ7SuTV87tTkbYR
