### ISSUE TITLE
Error: Angular structure loaded both synchronously and asynchronously

### ISSUE THREAD

**Issue by vnykSJ** [primefaces/primeng#10293]
**Current behavior**
When I use the latest primeNG version 12.0.0-rc-1 on the Angular version 12.0.1 app and building the app using the `ng build` command its throwing this error
``` 
× Compiling TypeScript sources through NGC
ERROR: Angular structure loaded both synchronously and asynchronously
An unhandled exception occurred: Angular structure loaded both synchronously and asynchronously
See "C:\Users\sun\AppData\Local\Temp\ng-wtTTRw\angular-errors.log" for further details.
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file C:\WINDOWS\system32\cmd.exe
npm ERR! errno ENOENT
npm ERR! matrix-ui-core-ng@3.10.5-pre.0 build: `npm run index && ng build --configuration production --project core`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the matrix-ui-core-ng@3.10.5-pre.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sun\AppData\Roaming\npm-cache\_logs\2021-06-02T06_51_49_794Z-debug.log

Process finished with exit code 1
```

**Expected behavior**
The app should build without any error.

**Minimal reproduction of the problem with instructions**

1. create a new angular app with the latest version 12.0.1
2. include the latest primeng version 12.0.0-rc-1 in the package.json 
3. run `npm i`
4. build an app using the command `ng build --configuration production`

**Please tell us about your environment:**
OS: Windows 10
IDE: WebStorm
Node: v14.15.0

* **Angular version:** 12.0.1

* **PrimeNG version:** 12.0.0.rc-1
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` = 14.15.0
![image](https://user-images.githubusercontent.com/31762046/120445325-20f75680-c3a6-11eb-9317-892ead73df81.png)

**Comment by yigitfindikli** [comment]
I couldn't replicate it with https://github.com/primefaces/primeng-quickstart-cli and a new project which is created with angular-cli v12.
