### ISSUE TITLE
p-dialog layout is weird when the size is very smaller

### ISSUE THREAD

**Issue by wangpan22** [primefaces/primeng#10307]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
When resizing a dialog, the layout will become weird if the size is very small. Maybe this is working as design?
![image](https://user-images.githubusercontent.com/19985303/120962004-790ccf00-c791-11eb-96c1-e289ec200da7.png)

**Expected behavior**
The layout should keep the same, may add scroll bars if the dialog is too small to show all content.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
I noticed this when learning how to create a dialog on PrimeNG website.

**Please tell us about your environment:**

* **Angular version:** 11.1.0
yes

* **PrimeNG version:** 11.2.0
yes, I used the examples on PrimeNG website

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all browsers
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by yigitfindikli** [comment]
This is by design. We suggest using the "breakpoints" property for responsive dialog.
