### ISSUE TITLE
Tree add disabled property

### ISSUE THREAD

**Issue by PHuhn** [primefaces/primeng#10306]
[X] Feature Enhancement

**Feature**

Add disabled property to the Tree component

**Reason**

The Tree component is inconsistent with other control, additionally I would like to have read-only forms for specific users.

**Please tell us about your environment:**

- Windows 10 Pro: 20H2 - 19042.985
- Angular version: 12.0.1
- PrimeNG version: 12.0.0-rc.1
- Browser: Chrome: 90.0.4430.212
- TypeScript: 4.2.3
- Node: 14.15.5
-

**Comment by PHuhn** [comment]
This is one of the reason why I would like tree to be consistent with the other controls.

[[StackOverflow] PrimeNG Disable Directive](https://stackoverflow.com/questions/67797625/angular-input-set-programmatically-for-3rd-party-controls)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
