### ISSUE TITLE
Regression with p-float-label and p-dropdown if selected value is falsy, but neither null, nor undefined

### ISSUE THREAD

**Issue by j-be** [primefaces/primeng#10315]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://github-fnjo2c.stackblitz.io

**Current behavior**

`false` and `0` are treated as `empty`.

**Expected behavior**

`false` and `0` are treated as themselves, and only `null` and `undefined` are treated as `empty`.

**Minimal reproduction of the problem with instructions**

* Open the https://github-fnjo2c.stackblitz.io
* See the second (`false`) and the fourth (`0` as in "zero") option

**What is the motivation / use case for changing the behavior?**

This was introduced in 11.4.1 (all versions up to including 11.4.0 exhibit the expected behavior described above). As that is a minor version increment I suspect this is a regression, and not a feature.

**Please tell us about your environment:**

Whatever StackBlitz is running at the time of writing, so only putting it there for completeness sake. Locally discovered on:

* **Angular version:** 11.2.14
* **PrimeNG version:** >= 11.4.1
* **Browser:** at least the following, all on Linux Mint 20, up to date with the respective official repo at the time of writing:
  * Firefox 89.0
  * Chromium 90.0.4430.212
  * Opera 76.0.4017.177
  * Microsoft Edge Version 92.0.902.8
* **Language:** TypeScript 4.1.5
* **Node (for AoT issues):** `node --version` =  v15.12.0

**Comment by yigitfindikli** [comment]
Duplicate https://github.com/primefaces/primeng/issues/10245
