### ISSUE TITLE
Menubar - what if we want to set some custom content to center also??

### ISSUE THREAD

**Issue by aruyc** [primefaces/primeng#10318]
Menubar: has facility to set custom content in left and right but  not in center. any option or way to set custom content in center?

like below:

`<p-menubar [model]="items">`
    `<ng-template pTemplate="start">`
        `<button pButton class="p-mr-2 p-button-success" icon="pi pi-home"></button>`
        `<button pButton icon="pi pi-arrow-left" class="p-mr-2 p-button-secondary"></button>`
  `  </ng-template>`
 `  <ng-template pTemplate="center">`
        ` <span>App Title</span>`
 `   </ng-template>`
   ` <ng-template pTemplate="end">  `     
       ` <div>`
          `  <button pButton class="p-mr-2 p-button-success" icon="pi pi-check"></button>`
       `     <img src="assets/images/logo.png" width="45" class="p-pl-2">`
 `       </div>`
   ` </ng-template>`
`</p-menubar>`

Here in code : i want something like - application title in center of menubar. how can i do that?? may be possible like below code:

` <ng-template pTemplate="center">
         <span>App Title</span>
    </ng-template>`

**Comment by yigitfindikli** [comment]
Please use the forum or discord channel for questions and help requests.
