### ISSUE TITLE
p-tree toggler focus highlight cut off

### ISSUE THREAD

**Issue by Urtgard** [primefaces/primeng#10312]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
When using a theme, wich has a thick border to highlight the togglers focus, the border will be cut off at the left and top.
This happens with the Saga, Nova and Rhea theme and can be tested with the showcase:
https://www.primefaces.org/primeng/showcase/#/tree
 
![image](https://user-images.githubusercontent.com/13890391/121157538-f267f880-c849-11eb-9fd3-046d74b3cf57.png)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
