### ISSUE TITLE
Filtering non existing item in p-dropdown [filter=true, group=true] and pressing key down generates error: ERROR TypeError: Cannot read property 'items' of undefined

### ISSUE THREAD

**Issue by gintskrastins** [primefaces/primeng#10325]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-dropdown-demo-bhxswt?file=src/app/app.component.html

**Current behavior**
After filtring non-existing item and pressing the key down occurs error:

```
ERROR TypeError: Cannot read property 'items' of undefined
    at Dropdown.getOptionGroupChildren (dropdown.ts:433)
    at Dropdown.onKeydown (dropdown.ts:809)
    at Object.eval [as handleEvent] (VM4214 Dropdown.ngfactory.js:138)
    at handleEvent (view.ts:138)
    at callWithDebugContext (services.ts:641)
    at Object.debugHandleEvent [as handleEvent] (services.ts:381)
    at dispatchEvent (util.ts:135)
    at eval (element.ts:208)
    at HTMLInputElement.eval (dom_renderer.ts:66)
    at ZoneDelegate.invokeTask (zone.js:431)
```

**Expected behavior**
Error is not expected

**Minimal reproduction of the problem with instructions**
 * Open the https://stackblitz.com/edit/primeng-dropdown-demo-bhxswt?file=src/app/app.component.html
 * Filter for "abc" and press key down

**What is the motivation / use case for changing the behavior?**
Application users expects no errors in this case

**Please tell us about your environment:**
Version equal to StackBlitz is running at the time of writing

* **PrimeNG version:** v12.0.0-rc.1

* **Browser:** [Chrome  91.0.4472.77 | Firefox 89.0 (64-bit)]
 
* **Language:** [TypeScript 4.0.2]

**Comment by yigitfindikli** [comment]
Unable to replicate with latest PrimeNG, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
