### ISSUE TITLE
InputNumber: Add option to enforce "step points" to be to multiples of step value, rather than directly relative to current value

### ISSUE THREAD

**Issue by MaximSagan** [primefaces/primeng#10324]
### I'm submitting a...

```
[ x ] feature request
```

### Current behavior

https://stackblitz.com/edit/primeng-inputnumber-demo-znh6z4?file=src/app/app.component.html

Step: 0.25
Current value: 20.81
Value resulting from clicking "down spinner button" or pressing "down key": **20.56** (a bit awkward)
Value resulting from clicking "up spinner button" or pressing "up key": **21.06** (a bit awkward)

### Desired behavior (only when new option is set to "multiple")**

Step: 0.25
Current value: 20.81
Value resulting from clicking "down spinner button" or pressing "down key": **20.75** (much nicer)
Value resulting from clicking "up spinner button" or pressing "up key": **21.00** (much nicer)

### What is the motivation / use case for changing the behavior?

We can use the step to jump to clean round values, rather than awkward values that are not even multiples of the step.

### Suggested feature

Add new property to InputNumber, titled something like **"stepPoints"**. The default value would be **"relative"** (current behavior), but would also accept the value **"multiples"** which would take you to the nearest multiple of the step value (unless the min or max values are closer, in which case you would land on those values).

### Side note about input[type="number"] step behavior

The behavior of the standard input[type="number"] actually does not match either the current behavior of PrimeNg's InputNumber nor the behavior suggested here. It is closer to the behavior suggested here, but the step points are offset by the "min" value. This means that if the min is not a multiple of the step, the step points can get a bit ugly.
e.g.
**Min: 0.05**
Step: 0.25
Current value: 20.81
Value resulting from clicking "up spinner button" or pressing "up key": **20.80** ( 20.75 (multiple of step) + 0.5 )
Value resulting from clicking "up spinner button" or pressing "up key": **21.05** ( 21.00 (multiple of step) + 0.5 )

Despite the fact that I personally don't like this behavior, it could be desired by PrimeNg users who want to replace an input[type="number"] with a PrimeNg InputNumber component while retaining existing step behavior. Therefore, we could introduce a third "stepPoints" option called **"multiplesOffsetByMin"**.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
