### ISSUE TITLE
PrimeNG Calendar: Missing ChangeDetection

### ISSUE THREAD

**Issue by denny99** [primefaces/primeng#10321]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Super rare case, that is not easy to reproduce.

**Current behavior**
Usually a calendar works just fine and opens on input focus.  

We have one single case, where this behaviour does not work. 

**Expected behavior**
Should always open properly

**Minimal reproduction of the problem with instructions**

![image](https://user-images.githubusercontent.com/1826849/121378228-4b678780-c943-11eb-8319-f9b123e85caa.png)

I am not quite sure how to reproduce it. The image above shows the calendar on the form, that doesn't open on focus.
To fix this bug i've overwritten the `showOverlay` function and added a addtional `this.cd.detectChanges()`.

```javascript
const x = Calendar.prototype.showOverlay;
Calendar.prototype.showOverlay = function () {
  x.bind(this)();
  this.cd.detectChanges();
};
```

A `markForCheck` won't work. The `hideOverlay` function already triggers a change detection. So this might just be missing.

* **Angular version:** 11.2.x

* **PrimeNG version:** 11.4.2

* **Browser:** [all]

**Comment by yigitfindikli** [comment]
Issue is not clear, please feel free to reopen with a stackblitz example.

**Comment by denny99** [comment]
I will try to create a case. The problem is that i not quite sure why that happens. All I know is, that three change detection for the ngIf at the overlay does not work.

**Comment by denny99** [comment]
Yeah i have no idea. It just happens at this one single place. i'm using a cdr.detectChanges() onFocus. So it works now...
