### ISSUE TITLE
primeng - table - resize: On resize the last column with resizeMode="expand" the column-border leaves an afterimage of itself or vanishes

### ISSUE THREAD

**Issue by MuhSchaf** [primefaces/primeng#10328]
**I'm submitting a ...** 
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://www.primefaces.org/primeng/showcase/#/table/colresize

**Current behavior**
On resizing (making it smaller) the last column with columnResizeMode="expand" the colum-border leaves an afterimage of itself
On resizing (making it bigger) the last column with columnResizeMode="expand" the colum-border vanishes

**Expected behavior**
On resizing the last column with columnResizeMode="expand" the colum-border leaves

**Minimal reproduction of the problem with instructions**
Use the given colresize-Example on https://www.primefaces.org/primeng/showcase/#/table/colresize

Resize -> make it smaller (afterimage)
![image](https://user-images.githubusercontent.com/46820453/121548589-6d2d4100-ca0d-11eb-86d5-4b8d55be904c.png)
Resize -> make it bigger (vanishing)
![image](https://user-images.githubusercontent.com/46820453/121548633-77e7d600-ca0d-11eb-8d8b-346047b7904d.png)

**What is the motivation / use case for changing the behavior?**
I want a table thats not irritating with additional borders or vanishing borders

* **PrimeNG version:** 12.0.0.-rc1

* **Browser:** [Chrome 91.0.4472.77 64-Bit | Edge Chromium  91.0.864.41 64-Bit] 
TheProblem does not appear on Firefox.

**Comment by yigitfindikli** [comment]
![image](https://user-images.githubusercontent.com/19997575/121656923-a36bce80-caa8-11eb-8375-947573536e25.png)
Issue is not clear, please feel free to reopen with a stackblitz example.

**Comment by MuhSchaf** [comment]
I forked the documentation example here:
https://stackblitz.com/edit/primeng-tablecolresize-demo-expand-bug?file=src%2Fapp%2Fapp.component.html

Browsers with this problem are Edge and Chrome (Firefox) 

Thank you for your fast reply.
