### ISSUE TITLE
Prime AutoComplete gives inputwrapper Focus change detection error 

### ISSUE THREAD

**Issue by madhumita** [primefaces/primeng#10323]
Hello Team,

We are using Prime AutoComplete from Prime NG 10 . We have a requirement where we need to show a OK alert pop up on autoComplete lookup . I can see following error message in console when we try to display our own bootstrap pop up modal on an event from Prime Autocomplete lookup.This is causing  a dark flicker for a second which is quite noticeable on the UI and we are trying to get rid of that.
While analysing I found that it is due to Autocomplete failing to detect valuechange for 'p-inputwrapper-focus'....cd.detectChanges is missing from p-autocomplete component in prime source .The issue is similar to what we had seen for p-dropdown and was fixed by adding the cd.detectchanges to dropdown component.

core.js:4352 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value for 'p-inputwrapper-focus': 'true'. Current value: 'false'.
    at throwErrorIfNoChangesMode (core.js:5625)
    at bindingUpdated (core.js:13964)
    at checkStylingProperty (core.js:16715)
    at ɵɵclassProp (core.js:16623)
    at AutoComplete_HostBindings (primeng-autocomplete.js:717)
    at setHostBindingsByExecutingExpandoInstructions (core.js:7089)
    at refreshView (core.js:7366)
    at refreshEmbeddedViews (core.js:8421)
    at refreshView (core.js:7344)
    at refreshComponent (core.js:8467)
Please can u help in fixing this issue at the earliest.
That will help us deliver abetter user experience in prod.

Thanks and Regards,
Madhumita

**Comment by yigitfindikli** [comment]
Unable to replicate with latest PrimeNG, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
