### ISSUE TITLE
onlazyloading not working

### ISSUE THREAD

**Issue by juststarted** [primefaces/primeng#10322]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
onLazyLoad get triggered 2x upon ngOninit.  However, as I scroll, it doesn't trigger again after setting [virtualRowHeight].  Also set [rows]=2 and that doesn't work.  I have played around with virtualRowHeight but nothing has changed.  It only loads the records set per page.  Adding pagination in works.

**Expected behavior**
onLazyload gets triggered as I scroll to load subsequent data.  

* **Angular version:** 10.2.5

* **PrimeNG version:** 10.0.2

* **Browser:** Chrome Version 90.0.4430.93
 
* **Language:**  TypeScript 4

* **Node (for AoT issues):** `node --version` =   v10.24.0

**Comment by yigitfindikli** [comment]
Unable to replicate with latest PrimeNG, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
