### ISSUE TITLE
Demo code for Custom Constraint in Filter Service looks wrong

### ISSUE THREAD

**Issue by papb** [primefaces/primeng#10327]
In [this page](https://primefaces.org/primeng/filterservice):

https://github.com/primefaces/primeng/blob/cfe585d5efcb6b84942a0985bec946b39308c762/src/app/showcase/components/filterservice/filterservicedemo.html#L68-L84

The name of the custom filter is `isPrimeNumber` but the actual logic has nothing to do with prime numbers, has it?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by papb** [comment]
Hi @mertsincan the problem still exists, although the link to the page changed to [this](https://primefaces.org/primeng/filterservice). I've edited the original post.

I can't reopen the issue on my own, please reopen it for me, thanks.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
