### ISSUE TITLE
<p-multiSelect> accessibility not working

### ISSUE THREAD

**Issue by John12x** [primefaces/primeng#10320]
I'm using Primeng multiselect control given below.

https://www.primefaces.org/primeng/showcase/#/multiselect

I want to make multiselect control accessible compliant, I'm using primeng version 11.4.2

As shown below, multiselect seems to be accessible compliant (even though I found few issues) when I test in https://www.primefaces.org/primeng/showcase/#/multiselect website using below keys.

Space bar Key -> Open multiselect control options.
Tab Key -> Navigate among options.
Enter Key -> Select option.

![image](https://user-images.githubusercontent.com/31477143/121356486-83c09300-c94e-11eb-8630-ea874700bf8a.png)

Above are working in official primeng portal, but when I integrate same control in my angular application, it seems to be not working.  Only Space bar Key working to open multiselect options but when I use Tab key to navigate between options, I'm unable to do that. When I press Tab key, instead of navigating between options, focus moved to other control.

I'm not getting what else need to be added to make primeng controls to be compliant for accessibility.

Pls suggest.

**Comment by yigitfindikli** [comment]
Upcoming versions focus on accessibility where each component will get new sections for keyboard and screen reader support along with the improvements. We'll be checking with accessibility tools for 100% compliancy.
