### ISSUE TITLE
Feature request: remove limit of 2 filter rules in menu for p-columnFilter

### ISSUE THREAD

**Issue by papb** [primefaces/primeng#10330]
[x] *This feature request is not on [the roadmap](https://github.com/primefaces/primeng/wiki/Roadmap) already*

----

The *Add Rule* button only disappears after adding one extra rule:

![image](https://user-images.githubusercontent.com/20914054/121624914-d2eaee80-ca48-11eb-9119-65602806d418.png)

![image](https://user-images.githubusercontent.com/20914054/121624942-e0a07400-ca48-11eb-9eb3-5b882f947bed.png)

Could this limit be removed? Could PrimeNG allow me to add as many rules I want?

Note: in case you're wondering, the option in the top to choose between *Match All* and *Match Any* is still perfect, no need to change that. I don't need more complex ways to combine each rules, such as *"match first and second or match the third"* or anything like that.

**Comment by caiootaviano** [comment]
Nice feature, looking for exactly the same =)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by papb** [comment]
Hello @mertsincan the issue still exists. Please reopen.

**Comment by geoeki** [comment]
Just ran into that same problem on our app based on user feedback...needed to add at least two filter rules and found it's limited to just 1. This makes extensive table filtering impossible!

**Comment by bloigge** [comment]
Any progress on this feature? We are also looking for a way to extend the filter rule amount.

**Comment by cetincakiroglu** [comment]
Hi,

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 
For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
