### ISSUE TITLE
Support Inputtext features for Autocomplete

### ISSUE THREAD

**Issue by dom380** [primefaces/primeng#10331]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Currently a number of the features available for the `InputText` component can't be used with the embedded input field of the `AutoComplete` component. E.g. Icons, help text, input masking and so on.

Would it be possible for these features to supported by `AutoComplete` or even the ability to define the input field ourselves directly?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
