### ISSUE TITLE
How to listen for ctrl key while dragging?

### ISSUE THREAD

**Issue by JakeSummers** [primefaces/primeng#1033]
I am using the Drag and Drop module.  Overall works great but having one issue that I can't figure out.  

Typically when dragging an item, I want to do a move operation.  However when the user presses ctrl, I would like to do a clone operation.  

It seems like the drag and drop framework is swallowing all keyboard events and not exposing them anywhere.  Normally if I put this in my template, I will get keyboard events:

```
<div (window:keydown)="doSomething($event)"></div>
```

When I am dragging something and I press `a` or `b` or `ctrl`, no events are triggered.  

This is an important usecase for me because the places that you can move an item are different than the places that you can clone an item to.  For example, you can move an item to the trash but you cannot clone an item to the trash.

**Comment by cagataycivici** [comment]
Please use forum for support requests.
