### ISSUE TITLE
Menu: pressing Enter button

### ISSUE THREAD

**Issue by KurinIllia** [primefaces/primeng#10344]
**I'm submitting a ...**
```
[x] bug report 
```

**Current behavior**
Clicking on item in p-menu executes command, specified in model parameter, but pressing Enter button doesn't do this.

**Expected behavior**
When clicking on item in p-menu specified command should be emitted.

**Please tell us about your environment:**

* **Angular version:** 11.X

* **PrimeNG version:** 11.X

* **Browser:** all
 
* **Language:** all

**Comment by Da13Harris** [comment]
This is specifically a keyboard accessibility issue. A mouse user can access a menu item that calls a `command`, but a keyboard-only user can't.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
