### ISSUE TITLE
Tabmenu with Fluent UI  Light theme shows vertical scroll bars

### ISSUE THREAD

**Issue by rafparedis** [primefaces/primeng#10341]
I'm submitting a 

[X ] bug report => Search github for a similar issue or PR before submitting

**Current behavior**
The tabmenu component shows the vertical scroll bar when using the Fluent UI Light theme. Other themes do not have this issue

**Expected behavior**
No vertical scroll bar

**Minimal reproduction of the problem with instructions**
In the primeng showcase open the showcase for the TabMenu and select Fluent UI Light theme. 

* **PrimeNG version:** 12.0.0

* **Browser:** 
Tested with Edge Chromium and Firefox
 
![primeng_tabmenu](https://user-images.githubusercontent.com/25713571/122223384-668e4600-ceb3-11eb-9aa9-3cdf8ae0c4e7.png)

**Comment by rafparedis** [comment]
![image](https://user-images.githubusercontent.com/25713571/122370171-26849d00-cf5f-11eb-8bf9-3ad47615c581.png)

Toggling this off made the scroll bar disapear

**Comment by rafparedis** [comment]
![image](https://user-images.githubusercontent.com/25713571/122371114-e70a8080-cf5f-11eb-9be7-4f5ed2b962c4.png)

Toggling this setting off in .p-tabmenu made the vertical scroll bar disappear

**Comment by rafparedis** [comment]
I found a css value in the theme.css that caused this behavior
by setting the -2px to 0 the tabs display normally

![image](https://user-images.githubusercontent.com/25713571/127344023-e7dafb71-01cb-4484-a79b-476d681f03f4.png)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
