### ISSUE TITLE
Confirm popup doesn't change target

### ISSUE THREAD

**Issue by Alexandre-Luquet** [primefaces/primeng#10343]
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Stackblitz Case (Bug Reports)**
https://stackblitz.com/edit/primeng-confirmpopup-demo-h5z7me?file=src/app/app.component.ts

**Current behavior**
Currently when I try to use confirm-popup when I put several buttons on the same page that call the same function (eg: I call the same function with different parameters for each item in the ngfor loop).

As soon as I click on the first button it opens the popup and I am forced to either click outside the popup or make a choice so if I click on other buttons the target does not change.

Using the [key] property doesn't work because I am forced to click twice in this case. 
I tried to add this.confirmationService.close(); for each function to close the old target if it is open but it didn't work

**Expected behavior**
Clicking on any other button should clear the old target 

**What is the motivation / use case for changing the behavior?**
Improve UX

* **Angular version:** 10

* **PrimeNG version:** 12.0.0

**Comment by sushil-suthar** [comment]
I am also facing this issue

**Comment by MightLin** [comment]
Will this bug be fixed? I also facing this issue


Angular version: 10

PrimeNG version: 12.0.0

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by aparkertg** [comment]
I'm experiencing this exact bug. Additionally this can be reproduced on PrimeNG's confirm pop up page using the stackblitz embedded on the page.

https://primeng.org/confirmpopup

**Comment by MatZil** [comment]
You are using exactly 1 p-confirmPopup instance and expect it to be attachable to multiple elements.

Solution: Have 1 p-confirmPopup instance **for each** element you expect the popup to attach to (with each instance having a unique key property).

In your case, you would need to:

- Add a second instance of p-confirmPopup
- Set arbitrary but unique keys for both p-confirmPopup instances
- Specify the key when invoking .confirm() method.

Here's a working version: https://stackblitz.com/edit/primeng-confirmpopup-demo-xtuy6a?file=src%2Fapp%2Fapp.component.html
