### ISSUE TITLE
P-Table resize columns when row is expanded

### ISSUE THREAD

**Issue by CorentinPacaud** [primefaces/primeng#10347]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://www.primefaces.org/primeng/showcase/#/table/rowexpansion
https://stackblitz.com/edit/primeng-tablerowexpansion-demo?file=src%2Fapp%2Fapp.component.html

Put a a p-Table **with only 2 or 3 columns. Make it expandable.

**Current behavior**
When you click on the expandable row arrow, it expands, but the main columns are resized. This behavior is not here when you have like 5 or 6 columns.

**Expected behavior**
Columns should not be resized when row is expanded.

**Minimal reproduction of the problem with instructions**
Before expanding
![image](https://user-images.githubusercontent.com/10416367/122577296-e9013c00-d052-11eb-8df0-dcbaa4129fcf.png)

After expanding : 
![image](https://user-images.githubusercontent.com/10416367/122577427-0f26dc00-d053-11eb-846f-aa4ffa0b1dab.png)

* **Angular version:** 5.X
Current version on PrimeNG website

* **PrimeNG version:** 5.X
Current version on PrimeNG website

* **Browser:** At least Chrome.

**Comment by yigitfindikli** [comment]
Issue is not clear, please feel free to reopen with a stackblitz example.

**Comment by CorentinPacaud** [comment]
Hello,
The stackblitz is on your own website !
Just remove 2 or 3 <th> in head table to keep only 2 or 3 columns.
I published screeshot of what happened when you deploy a rowexpansion.

What do you need more ?

**Comment by xszbencex** [comment]
I resolved it by setting the white-spce style of td element in the rowexpansion to normal.
`  <ng-template pTemplate="rowexpansion" let-rowData>
    <tr>
      <td [colSpan]="getColNumber()" **style="white-space: normal"**>
        ...
      </td>
    </tr>
  </ng-template>`
