### ISSUE TITLE
Filtering in DataTable using MultiSelect 

### ISSUE THREAD

**Issue by tamatcho** [primefaces/primeng#1034]
Hi,
It would be nice to have a feature allowing filtering a DataTable using MultiSelect as in Primefaces.
I attached a screenshot to illustrate it.
![screen shot 2016-10-06 at 10 44 51](https://cloud.githubusercontent.com/assets/22147189/19146061/169aab64-8bb2-11e6-9369-66d860b37eb2.png)

**Comment by cagataycivici** [comment]
This is on our roadmap, please see;

https://github.com/primefaces/primeng/wiki/Roadmap
