### ISSUE TITLE
p-calendar unable to select all times when time period is less than an hour

### ISSUE THREAD

**Issue by jchurchley** [primefaces/primeng#10358]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://github-ylt3an.stackblitz.io

**Current behavior**
p-calender when you set a max/min date and set the initial value to within that range you not able to select all time ranges within the period when less than an hour

**Expected behavior**
When you step through the minutes should be a property which you can set to either increase or decrease the hour when you increment above 60 minutes or before 0 minutes.

**Minimal reproduction of the problem with instructions**
p-calender
Set MinDate to 8:45
Set MaxDate to 9:30
Set Inital value to 9:30

You are unable to select a time of between 8:45-8:59

**What is the motivation / use case for changing the behavior?**
See example above

**Please tell us about your environment:**
N/A

* **Angular version:** 5.X
12.0.5

* **PrimeNG version:** 5.X
12.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
N/A

* **Node (for AoT issues):** `node --version` =   
N/A

**Comment by jchurchley** [comment]
Alternately onMinuteChange and onHourChange could be exposed events and this issue could be handled by the user of the component

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by cetincakiroglu** [comment]
Fixed in https://github.com/primefaces/primeng/pull/14196
