### ISSUE TITLE
Include documentation in code functions for better usability with IDE

### ISSUE THREAD

**Issue by john8329** [primefaces/primeng#10351]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report 
[x] feature request 
[ ] support request 
```

**Current behavior**
Autocompletion doesn't show any documentation on my IDE when I trigger it:
<img width="867" alt="Screenshot 2021-06-21 at 09 25 57" src="https://user-images.githubusercontent.com/42315498/122723198-f6950c80-d272-11eb-9046-642f5fe754e2.png">

**Expected behavior**
It'd be nice to not have to go to the documentation website every time and see directly a brief description of what the function or directive does.

**What is the motivation / use case for changing the behavior?**
Far better usability with IDEs, because they supposedly look for descriptions in the library's source code, if I'm not wrong.

**Please tell us about your environment:**
WebStorm 2021.2 EAP

* **Angular version:** 12

* **PrimeNG version:** 12 beta

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by john8329** [comment]
It's still the same, but I guess it's not important.
