### ISSUE TITLE
Picklist and OrderList Virtual Scroll Support

### ISSUE THREAD

**Issue by thang1160** [primefaces/primeng#10350]
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

In the document, picklist doesn't have virtual scroller so with my current data (>30,000) it took quite amount of time for rendering. Which, pretty bad for UX

**Expected behavior**

Picklist support virtual scroller, reduce DOM rendering

**What is the motivation / use case for changing the behavior?**

 Improve UX

**Please tell us about your environment:**

* **Angular version:** 12.0.0

* **PrimeNG version:** 12.0.0

**Comment by ikupresanin** [comment]
Any updates?

**Comment by Zaknarfen** [comment]
I need this also

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by thang1160** [comment]
I checked the documentation and there is still no improvement in this

**Comment by cetincakiroglu** [comment]
Hi,

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 
For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
