### ISSUE TITLE
p-inputNumber if value out of range (min-max) the cursor is set back behind currency label after correction

### ISSUE THREAD

**Issue by ABSTRACT123** [primefaces/primeng#10353]
<p-inputNumber [(ngModel)]="value20" mode="decimal" [showButtons]="true" inputId="minmax-buttons" mode="currency" currency="EUR" locale="de-DE" [min]="0" [max]="100"></p-inputNumber>

When clicking the field the cursor is set before the currency label (in the input zone) but if an out of range value is entered, the cursor is set after the currency label. It is then necessary to click the field to be able to enter data.

**Comment by mertsincan** [comment]
Hi,

I think this issue has been fixed in 12.1.1.

For now, closed. If the problem persists, please reopen this ticket.
Best Regards,
