### ISSUE TITLE
Main table columns aligned with child table columns when row expanded p-table.

### ISSUE THREAD

**Issue by CorentinPacaud** [primefaces/primeng#10352]
[X] bug report
[ ] feature request
[ ] support request 

https://stackblitz.com/edit/primeng-tablerowexpansion-demo-qzkcbf?file=src/app/app.component.html

Current behavior
When you click on the expandable row arrow, it expands, but the main columns are resized. This behavior is not here when you have like 5 or 6 columns.
In fact, if you have 3 columns on the "main" table and more columns on the rowexpansion child table, the columns of the main table will be resized to be aligned with the child columns.

Expected behavior
Columns should not be resized when row is expanded.

Minimal reproduction of the problem with instructions
Before expanding
![image](https://user-images.githubusercontent.com/10416367/122739469-4e3b7400-d283-11eb-9cc6-61e84312807e.png)

After expanding :
![image](https://user-images.githubusercontent.com/10416367/122739595-6c08d900-d283-11eb-942f-bd9f35e62f27.png)

Angular version: 5.X
Current version on PrimeNG website

PrimeNG version: 5.X
Current version on PrimeNG website

Browser: At least Chrome.

**Comment by yigitfindikli** [comment]
You need to use colspan="4" not colspan="7". Please use the forum or discord channel for questions and help requests.
