### ISSUE TITLE
Selection with pagination: p-table with selectionMode="multiple" and lazy loading

### ISSUE THREAD

**Issue by noebug** [primefaces/primeng#10357]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-me2euc?file=src%2Fapp%2Fapp.component.ts

**Current behavior**
The "select all" header checkbox in a p-table with lazy loading enabled and selectionMode="multiple" selects the data only from the current page and remains selected for the next ones, however in the next pages the elements are not selected.
<img width="197" alt="p1" src="https://user-images.githubusercontent.com/86043498/123046877-4a375f80-d405-11eb-99e8-225c726c68d0.PNG">
<img width="219" alt="p2" src="https://user-images.githubusercontent.com/86043498/123046886-4c99b980-d405-11eb-9026-21c25fc66fa5.PNG">

**Expected behavior**
It would be great to customize the "select all" in the header checkbox for all the pages or by page when we use a table with lazy loading.
If we want to keep the behaviour from the p-table without lazy loading, then we would do a select all only for the data we have in the current page, but as we would navigate to page 2, we could add to the already selected elements all the elements selected from page 2, using the header checkbox.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/github-me2euc?file=src/app/app.component.ts
To reproduce the issue click the header checkbox on the first page then navigate to page 2, page 3
On page 1 - all the elements are selected
On page 2 - only the header checkbox is selected, but the elements are not selected

**What is the motivation / use case for changing the behavior?**
The current behaviour works consistently for p-table without lazy loading, when all the elements get selected.
But if we use lazy loading and retrieve the data from backend, as we navigate from page to page, there is inconsistency.
Because even if we click the select all header checkbox, only the data from first page gets selected and the data from the other pages stays unselected with the select all header checkbox selected. 
It is really misleading for a user, because we have two different behaviours here.

**Please tell us about your environment:**
Node: 14.15.1
Package Manager: npm 6.14.8
OS: win32 x64

* **Angular version:** 5.X
Angular: 12.0.5

* **PrimeNG version:** 5.X
"primeng": "^12.0.0",

* **Browser:** [all]

 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =   v14.15.1

**Comment by mertsincan** [comment]
Hi,

Fixed in https://github.com/primefaces/primeng/issues/10951. Also, I added a demo related to it on next version.

Best Regard,
