### ISSUE TITLE
DropDown don't select with uppercase

### ISSUE THREAD

**Issue by morula** [primefaces/primeng#10366]
```
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://primefaces.org/primeng/showcase/#/dropdown

**Current behavior**

1. focus on dropdown element
2. key shift+r

**Expected behavior**
Should select first entry with leading "r" like the following steps:
1. focus on dropdown element
2. key r

**Please tell us about your environment:**
* **Angular version:** 9.x - 12.x

* **PrimeNG version:** 9.x - 12.x

**Browser:** 
*** Firefox
*** Chrome

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
