### ISSUE TITLE
AutoComplete - selectedItem

### ISSUE THREAD

**Issue by sourdoth** [primefaces/primeng#10360]
Hi, Please add the use of the template "selectedItem" when [multiple] = false (or enable it in all cases), because the "field" only supports one attribute which is detrimental to the display as more attributes appear in the list. For example: name and lastname in the list of options, but when selecting only the name can be placed

![image](https://user-images.githubusercontent.com/29101756/123129001-9a202180-d419-11eb-8ca0-b734706d1332.png)

**Comment by yigitfindikli** [comment]
AutoComplete already has a selectedItemTemplate. You can find under the Templating at https://primefaces.org/primeng/showcase/#/autocomplete

**Comment by sourdoth** [comment]
hi, I know that the selectedItem template exists, but as the documentation indicates "this template is not supported in single mode", what is expected is that it works for all cases, single and multiple mode
