### ISSUE TITLE
Disabled item on slidemenu not showing tooltip

### ISSUE THREAD

**Issue by ljupchoristovski** [primefaces/primeng#10368]
**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/slidemenutest?file=src%2Fapp%2Fapp.component.html

**Current behavior**
When we have slide menu implemented and disabled one of the items, tooltip is not shown on hover on the disabled item

**Expected behavior**
Tooltip should be shown on disabled item of the slide menu

**Minimal reproduction of the problem with instructions**
This issue appears after upgrading primeng version to v11.4.2. When using the primeng version v10.0.3 there was no issue, tooltips were shown on hover on the disabled item.

**Please tell us about your environment:**
Windows 10

* **Angular version: ^11.0.4

* **PrimeNG version: ^11.4.2

* **Browser:** Chrome, Mozilla
 
* **Language:** [TypeScript]

* **Node (for AoT issues):** `node --version` =   16.3.0

**Comment by yigitfindikli** [comment]
Hi @ljupchoristovski,

This is by design. You can manipulate the pointer-events with custom CSS.

Example: https://stackblitz.com/edit/slidemenutest-9qsc1e

```
:host ::ng-deep .p-slidemenu .p-menuitem-link.p-disabled {
        pointer-events: auto;
}
```

**Comment by montelyno** [comment]
Perfect, thanks for the solution! Had the same issue.
