### ISSUE TITLE
New Table Filter Menu doesn't maintain "Match Any" in Primeng: 11.4.2

### ISSUE THREAD

**Issue by fdlj-operanov** [primefaces/primeng#10365]
[x ] bug report => Search github for a similar issue or PR before submitting

Angular CLI: 11.0.7
Node: 14.17.0
Primeng: 11.4.2
Mirage: 11.0.0

follow to this post:  https://github.com/primefaces/primeng/issues/9651, Unfortunately the problem is still present.

When I change Match All to Match Any, the event.fiters for the column is at operator: "or", but when I re open filter by click on the icon filter for the column, it  display Match All . And if y change nothing in the menu, but just click to apply button, the event.filter  for the column is still at operator: "or".
To change I need to chose Match Any, then chose Match All, then click to apply button. So the event.filters is refresh with the right operator : 'and'.

To resume:
first action: open filter menu
![![image](https://user-images.githubusercontent.com/86430918/123383689-c3fd5380-d593-11eb-99f2-f399d25fa003.png)](https://user-images.githubusercontent.com/86430918/123383658-bb0c8200-d593-11eb-8fc9-caad669b68b4.png)

==> event.filters (is ok)

![image](https://user-images.githubusercontent.com/86430918/123383689-c3fd5380-d593-11eb-99f2-f399d25fa003.png)

re open filter (not right)

![image](https://user-images.githubusercontent.com/86430918/123383729-ce1f5200-d593-11eb-9301-165dd103c397.png)

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
