### ISSUE TITLE
p-columnFilter type="date" display=menu with template calendar for monthly date picker return an event.filters with null value 

### ISSUE THREAD

**Issue by fdlj-operanov** [primefaces/primeng#10367]
[ ] bug report 

Angular CLI: 11.0.7
Node: 14.17.0
Primeng : "^11.4.3",
Mirage: "11.0.0",

When i code a column filter type date with a template to obtain a monthly calendar, the menu display well the monthly calendar, but event.filters return values as  null

The html code
![image](https://user-images.githubusercontent.com/86430918/123394746-c36aba00-d59f-11eb-8d28-e6a85e5e0e4f.png)

The menu for the column filter is ok
![image](https://user-images.githubusercontent.com/86430918/123392497-666e0480-d59d-11eb-8523-5909f0f5825a.png)

The date YYYY-MM is ok
![image](https://user-images.githubusercontent.com/86430918/123392554-7a196b00-d59d-11eb-9916-7fa365c8b8db.png)

But filters for the column return null for value
![image](https://user-images.githubusercontent.com/86430918/123392666-9e754780-d59d-11eb-9dc6-fbe2cb451aba.png)

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
