### ISSUE TITLE
Calendar model not updated if maxDate or minDate modifies the date

### ISSUE THREAD

**Issue by ilianiv** [primefaces/primeng#1036]
jQuery UI Datepicker modifies selected date if new min/maxDate is set and current date doesn't fit.  https://github.com/jquery/jquery-ui/blob/master/ui/widgets/datepicker.js#L1931. 

In this case jQuery Datepicker does not trigger 'onSelect' event and p-Calendar doesn't update it's model but the actual input value gets changed.

**Example:***

```
date = '13.03.2013';
maxDate = '23.03.2013';
```

```
<p-calendar [(ngModel)]="date" [maxDate]="maxDate" dateFormat="dd.mm.yy"></p-calendar>
```

![image](https://cloud.githubusercontent.com/assets/3925630/19157238/5b480f32-8bed-11e6-91c0-2a886770fb60.png)

Then we change: `maxDate = '11.03.2013'` and `console.log(date)`:

```
'13.03.2013'
```

but 
![image](https://cloud.githubusercontent.com/assets/3925630/19157300/8ad2079e-8bed-11e6-84d4-8219a6cd827e.png)

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/VZbdZfQ7SuTV87tTkbYR
