### ISSUE TITLE
p-columnFilter filtering is not responsive

### ISSUE THREAD

**Issue by mdababi1989** [primefaces/primeng#10378]
Hello,

I'm submitting a ... (check one with "x")

[ ] bug report
[ x] feature request
[ ] support request
Current behavior
The filtering with p-columnFilter is not responsive, I must click on the enter key to show the result. 

Expected behavior
The filtering with p-columnFilter can become responsive, It shows the results only by typing without the need to click on the enter key liker it was with this code 

```
**```
<input type="text"
                 (input)="dt.filter($event.target.value, 'endEntityProfile', 'contains')">
```**
```

Minimal reproduction of the problem with instructions
Every time.
What is the motivation / use case for changing the behavior?
Better UX

Angular version: 12

PrimeNG version: 12

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
