### ISSUE TITLE
Editor displays empty

### ISSUE THREAD

**Issue by valeriemaite** [primefaces/primeng#1037]
I'm trying to add an editor to my angular 2 project, and after following the primeng documentation (http://www.primefaces.org/primeng/#/editor) most of the editor seems incomplete:

![image](https://cloud.githubusercontent.com/assets/4131500/19157432/e7a31bfe-8baa-11e6-882c-bcbabb798136.png)

I have installed primeng, quill, really don't know what is going on.  In the example above I juts paste what the  example has, I have also have the imports in place.

**Comment by valeriemaite** [comment]
Just more info, this is my code:

HTML:


<h3>Custom Toolbar</h3>
<p-editor [(ngModel)]="text2" [style]="{'height':'320px'}">
    <header>
        <span class="ql-formats">
            <button class="ql-bold"></button>
            <button class="ql-italic"></button>
            <button class="ql-underline"></button>
        </span>
    </header>
</p-editor>
<p>Value: {{text2||'empty'}}</p>

TS:
import {FormsModule} from '@angular/forms';
import {EditorModule, InputTextModule,DataTableModule,ButtonModule,DialogModule} from 'primeng/primeng'; 
import {MenuItem,SelectItem} from 'primeng/components/common/api';

export class Sample {
     text1: string = '<div>Hello World!</div><div>PrimeNG <b>Editor</b> Rocks</div><div><br></div>';
    
    text2: string;
}

**Comment by NithyaJayapal** [comment]
Im also getting the same blank editor mentione on the issue #1037 when im trying to bind the content with the 'HTML' content in the .html page.
![capture](https://cloud.githubusercontent.com/assets/22683297/19195127/1db5542c-8c7e-11e6-82c4-b4d1420be214.PNG)
![capture](https://cloud.githubusercontent.com/assets/22683297/19195139/301eea92-8c7e-11e6-90f4-71d252e01601.PNG)

**Comment by valeriemaite** [comment]
The issue happens because the css file is not loaded.  For some reason Angular was not loading the file from its location.  I changed it to point to the cdn and it loaded, then changed the file one level down in the folder structure and it worked as well.

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
