### ISSUE TITLE
Material Input Component Is NOT Material Input Component!

### ISSUE THREAD

**Issue by sourvinos** [primefaces/primeng#10371]
I'm submitting a 

[x] bug report 
[ ] feature request
[ ] support request

Steps to reproduce:
1. - Visit https://www.primefaces.org/designer-ng/#/
2. - Select Material Light or Material Dark

Result: The input fields look as in bootstrap, not as in material. To see the obvious difference visit: https://material.angular.io/components/input/overview

Thank you!

**Comment by yigitfindikli** [comment]
You need to select the filled option. 
Like this:
![image](https://user-images.githubusercontent.com/19997575/123419373-d347c580-d5c2-11eb-92fa-8353f26daa2f.png)

**Comment by sourvinos** [comment]
If all things were that simple! Thank you!
