### ISSUE TITLE
Sass: Breaking Change: Slash as Division

### ISSUE THREAD

**Issue by FabienDehopre** [primefaces/primeng#10374]
### Sass currently treats __/__ as a division operation in some contexts and a separator in others. This makes it difficult for Sass users to tell what any given __/__ will mean, and makes it hard to work with new CSS features that use __/__ as a separator.

Today, Sass uses complex heuristics to figure out whether a __/__ should be treated as division or a separator. Even then, as a separator it just produces an unquoted string that’s difficult to inspect from within Sass. As more and more CSS features like [CSS Grid](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-row) and the [new rgb() and hsl() syntax](https://drafts.csswg.org/css-color/#rgb-functions) use __/__ as a separator, this is becoming more and more painful to Sass users.

Because Sass is a CSS superset, we’re matching CSS’s syntax by redefining __/__ to be only a separator. __/__ will be treated as a new type of list separator, similar to how , works today. Division will instead be written using the new `math.div()` function. This function will behave exactly the same as __/__ does today.

Read more here: https://sass-lang.com/documentation/breaking-changes/slash-div

**Comment by StefanCardnell** [comment]
Multiple SCSS compiler warnings are produced when using PrimeNG (Serenity in particular) due to this change.

**Comment by TheTiGuR** [comment]
Just to add to the ticket, Ultima gets errors (including my whole blob, just for reference):

`Generating browser application bundles (phase: building)...WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($shade, 100)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
164 │                     #{$prop}: #{"rgba(#{$colorValue},#{$shade / 100})"} !important;
    │                                                        ^^^^^^^^^^^^
    ╵
    node_modules\primeflex\src\_mixins.scss 164:56  rgba-color-class()
    node_modules\primeflex\src\_colors.scss 14:1    @import
    node_modules\primeflex\primeflex.scss 4:9       @import
    src\styles.scss 2:9                             root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($shade, 100)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
174 │                         #{$prop}: #{"rgba(#{$colorValue},#{$shade / 100})"} !important;
    │                                                            ^^^^^^^^^^^^
    ╵
    node_modules\primeflex\src\_mixins.scss 174:60  rgba-color-class()
    node_modules\primeflex\src\_colors.scss 14:1    @import
    node_modules\primeflex\primeflex.scss 4:9       @import
    src\styles.scss 2:9                             root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($shade, 100)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
184 │                         #{$prop}: #{"rgba(#{$colorValue},#{$shade / 100})"} !important;
    │                                                            ^^^^^^^^^^^^
    ╵
    node_modules\primeflex\src\_mixins.scss 184:60  rgba-color-class()
    node_modules\primeflex\src\_colors.scss 14:1    @import
    node_modules\primeflex\primeflex.scss 4:9       @import
    src\styles.scss 2:9                             root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($shade, 100)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
194 │                         #{$prop}: #{"rgba(#{$colorValue},#{$shade / 100})"} !important;
    │                                                            ^^^^^^^^^^^^
    ╵
    node_modules\primeflex\src\_mixins.scss 194:60  rgba-color-class()
    node_modules\primeflex\src\_colors.scss 14:1    @import
    node_modules\primeflex\primeflex.scss 4:9       @import
    src\styles.scss 2:9                             root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(nth($inputPadding, 1), 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
13 │         padding: nth($inputPadding, 1)/2 nth($inputPadding, 2);
   │                  ^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    src\assets\sass\theme\designer\components\input\_autocomplete.scss 13:18  @import
    src\assets\sass\theme\designer\_components.scss 6:9                       @import
    src\assets\sass\theme\_theme_dark.scss 4:9                                @import
    src\assets\theme\msmu-glue\theme-dark.scss 13:9                           @import
    src\styles.scss 8:9                                                       root stylesheet

WARNING: 24 repetitive deprecation warnings omitted.`

**Comment by tobiasmuecksch** [comment]
@yigitfindikli I'd suggest to add this to the v13 milestone https://github.com/primefaces/primeng/milestone/189

**Comment by ErikVeland** [comment]
Slashes being confusing is a problem with CSS, not SASS. You are not fixing anything by introducing a function for a single mathematical operator and adding confusion between div/div instead.

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
