### ISSUE TITLE
treeTable globalFilter doesn't work with changeDetection OnPush

### ISSUE THREAD

**Issue by gonzalad** [primefaces/primeng#10373]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/primeng-treetablefilter-demo-s7dsun

**Current behavior**

When I enter a value in the global filter area, the treeTable isn't immediately filtered.
The filter is done only when I click on one of the nodes.

**Expected behavior**

Filtering should be done immediately when changing the value.
Please note that if I remove OnPush detection strategy, the filtering works as expected.

**Minimal reproduction of the problem with instructions**

See https://stackblitz.com/edit/primeng-treetablefilter-demo-s7dsun

I tried to use changeDetectorRef.detectChanges(), but it doesn't fix the issue.

**What is the motivation / use case for changing the behavior?**

My treeTable is displaying many nodes, I need to use OnPush detection strategy to avoid performances issues.

**Please tell us about your environment:**

* **Angular version:** 11.0.9
* **PrimeNG version:** 11.3.0

* **Browser:** [Chromium 91.0.4472.114 | FireFox 89.0.1]

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
