### ISSUE TITLE
Calendar picker is not displaying by default the next month when no available dates exist in this month

### ISSUE THREAD

**Issue by PalaioGG** [primefaces/primeng#10376]
Hello,

**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
When on the last day of the month, having today disabled, date-picker is not displaying the available dates
![image](https://user-images.githubusercontent.com/20303027/123935480-f1d00700-d99c-11eb-8f8c-2839ca9783e8.png)

**Expected behavior**
Calendar should display the next month with available dates. It would be expected to display July instead of June so that the user can select an available date.

**Minimal reproduction of the problem with instructions**
On the last day of the month set today as disabledDate and minDate as today.

**What is the motivation / use case for changing the behavior?**
Better UX

* **Angular version:** 11.2

* **PrimeNG version:** 11,4

**Comment by yigitfindikli** [comment]
Issue is not clear, please feel free to reopen with a stackblitz example.
