### ISSUE TITLE
Table column automatic hiding

### ISSUE THREAD

**Issue by lbroker** [primefaces/primeng#10375]
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

PrimeNG table component [https://primefaces.org/primeng/showcase/#/table/responsive](url)
is missing functionality "Automatic column hiding"

**Expected behavior**

When making screen width smaller, some not very important columns should hide:
Examples:
[https://datatables.net/extensions/responsive/examples/display-control/auto.html](url)
[https://www.primefaces.org/showcase/ui/data/datatable/responsive.xhtml?jfwid=d3b97](url)

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by lbroker** [comment]
Have checked latest version, and do not see this feature created. As requested will create new request.
