### ISSUE TITLE
Time picker for format set to 12 hours, but p calendar does not support AM/PM localisation

### ISSUE THREAD

**Issue by tryinitout** [primefaces/primeng#10383]
I'm submitting a ... (check one with "x")

[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
Note: Time Picker means Calendar Picker set to time only.

Current behavior
When the time picker is clicked, the component that appears sets the time in 12 hour format

Expected behavior
When the time picker is clicked, the component that appears sets the time in 12 hour format but it is not localised to the am/pm accroding to browser locale

Minimal reproduction of the problem with instructions
Click anywhere on the time picker with any 12 hor supported language like ko or ja and see the timepicker sets and displays in english only..

Please tell us about your environment:
Windows 10, VSCode

Angular version:
9.0.3

PrimeNG version:
9.0.0

Browser:
all

Language:
TypeScript 3.7.5

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
