### ISSUE TITLE
p-table customSort not working when [virtualScroll]="true"

### ISSUE THREAD

**Issue by NicolasHofmann** [primefaces/primeng#10385]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/primeng-tablevirtualscroll-bug-q23hkh?file=src/app/app.component.html

**Current behavior**
When using both virtual scroll and a custom sort on p-table, no sorting occurs when column headers are clicked.
Disabling either the virtual scroll or the custom sort causes the sorting behavior to work as expected again.

**Expected behavior**
When using both virtual scroll and a custom sort on the same p-table, sorting occurs when column headers are clicked.

**Minimal reproduction of the problem with instructions**
Click any table header in the example  provided above.

**What is the motivation / use case for changing the behavior?**
App needs to display a large data set and allows users to sort by column using non standard sorting algo.
A workaround has been found but it may be suboptimal regarding performance.

**Comment by yigitfindikli** [comment]
You need to build your own sort for the virtual scroll. The custom sort function just an example for the non-virtual scroll tables. You need to sort your value array.
