### ISSUE TITLE
p-splitter drag bar has no style

### ISSUE THREAD

**Issue by zhaoyuxin2018** [primefaces/primeng#10390]
Primeng version: 12.0.0
angualr version:12.1.1
![image](https://user-images.githubusercontent.com/39890241/124605262-4f34ee00-de9e-11eb-88f4-dcdaf31d8537.png)
![image](https://user-images.githubusercontent.com/39890241/124605282-54923880-de9e-11eb-98d8-a52532700838.png)
![image](https://user-images.githubusercontent.com/39890241/124605346-6247be00-de9e-11eb-9fff-17cb487dc11b.png)

**Comment by yigitfindikli** [comment]
Please use the forum or discord channel for questions and help requests.
