### ISSUE TITLE
Virtual Scroll with Lazy Loading from a Remote Datasource Does not Display Data in p-table inside p-dialog

### ISSUE THREAD

**Issue by dnsathrwa** [primefaces/primeng#10399]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**
reproduced the bug here: 
https://github-9mc3hb.stackblitz.io/
 https://stackblitz.com/edit/github-9mc3hb?file=src/app/test-dialog.component.ts

**Current behavior**

When a p-table with virtual scroll enabled is used inside a p-dialog, the data loads and shows one row on the table until you scroll and adjust the screen or inspect then all the rows show on the dialog. 

**Expected behavior**

When you open the dialog and the data is loaded, p-table should show all rows without having to adjust the screen or inspect the page 

**Minimal reproduction of the problem with instructions**
p-dialog
add p-table with virtual scroll enabled 
load data on show of the dialog 
check the view. (doesn't show anything until you scroll)
adjust the screen or inspect then all the data shows on the table 

**Please tell us about your environment:**

windows 10

* **Angular version:** 12.0.1

It's still an issue in angular 12.0.1

* **PrimeNG version:** 12

It's still an issue in primeng 12

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript: 4.3.4

* **Node (for AoT issues):** `node --version` =   14.15.5

**Comment by kirk-clawson** [comment]
This also happens with a p-tree component using virtual scroll + lazy load in 11.4.3

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
