### ISSUE TITLE
Accessible p-dialog: reach closing button and keep focus 

### ISSUE THREAD

**Issue by moma1806** [primefaces/primeng#10392]
[x ] feature request 

**Current behavior**
P-dialog opens a modal dialog. As a blind user I want to get read a header ant the closing button, after opening the dialog. When I close the p-dialog by saving or aborting, I want to continue working from this position of the page.

**Expected behavior**
**Acceptance criteria for Accessible p-dialog** 

**Screenreader can reach close-button**
**Given** An opened p-dialog with a "close"-Button at the right top and Jaws 2021 and Google Chrome **then** the close-button can be tabbed with the keyboard (no tabindex -1) **When** the close-button is tabbed with the keyboard, **then** the screenreader reads the text "close". 

**Close-button has mouse over text**
**When** the mouse pointer is moved over a button "close" **then** a popup with the labelling of the button is displayed (title-attribute). 

**Screenreader can identify title**
**Given** An opened p-dialog with a "close"-Button at the right top and Jaws 2021 and Google Chrome. **Then** the title "XYZ" is marked as a HTML-h2 Element and screenreaders identifie them als title 

**Screenreader keep focus after closing p-dialog**
**When** p-dialog is closed, then the focus is located on the button that opened p-dialog **and** the button that opened p-dialog is focused graphically perceptible **and**  the identifier of the button should be read out by the screenreader 

**Minimal reproduction of the problem with instructions**
https://www.primefaces.org/primeng/showcase/#/dialog
example „modal“

**What is the motivation / use case for changing the behavior?**
Web Content Accessibility Guidelines (WCAG) 2.1 requirements 
   1.1.1 Non-text Content
   1.3.1 Info and Relationships
   2.1.1 Keyboard
   2.4.3 Focus Order
   2.4.6 Headings and Labels

**Please tell us about your environment:**
Windows, Linux, Android, iOS, IDE: Eclipse, HTTP Server: Apache Tomcat
* **Angular version:** 11.1.4
* **PrimeNG version:** primeng 11.0.0
* **Browser:** Chrome, Firefox, Edge, Safari, Safari on IOS, Chrome on Android; all browsers in newest version
* **Language:** typescript  4.1.3
* **Node (for AoT issues):** node --version 12.5.0

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
