### ISSUE TITLE
Accessible p-panel advanced: identifier for title and close-button, no mark as "tab"

### ISSUE THREAD

**Issue by moma1806** [primefaces/primeng#10394]
[x ] feature request 
**Current behavior**
As blind user I expect that a page is structured in sections. Every section should be marked with a header. Labels of buttons to open or hide a section should be read to me. When I close or open a section, I want to continue my work at the same point.

**Expected behavior**
**Acceptance criteria : Accessible p-panel advanced**

**Screenreader can identify title**
**Given** A p-panel with a "close-Button" on the right side and Jaws 2021 und Google Chrome, **then** the title of the section, for example "XYZ", is marked as a HTML-h2 Element and screenreaders identifies it als title. 

**Screenreader can identify individual custom close-button**
**When** the open respectively close-button is tabbed with the keyboard, **then** the screenreader reads the text "open (or close) section XYZ" **and** the section ist not marked as tab for screenreader (<button aria-expanded=true>Close Header</button> without role="tab"). 

**Close-button has mouse over text**
**When** the mouse pointer is moved over a button "close section XYZ" ore "open section XYZ" **then** a popup with the labelling of the button is displayed "close section XYZ" or "open section XYZ" (title-attribute). 

**Minimal reproduction of the problem with instructions**
https://www.primefaces.org/primeng/showcase/#/panel
example „advanced“

**What is the motivation / use case for changing the behavior?**
Web Content Accessibility Guidelines (WCAG) 2.1 requirements 
   1.1.1 Non-text Content
   1.3.1 Info and Relationships
   2.1.1 Keyboard
   2.4.6 Headings and Labels  

**Please tell us about your environment:**
Windows, Linux, Android, iOS... IDE: Eclipse, HTTP Server: Apache Tomcat
* **Angular version:** 11.1.4
* **PrimeNG version:** primeng 11.0.0
* **Browser:** Chrome, Firefox, Edge, Safari, Safari on IOS, Chrome on Android; all

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
