### ISSUE TITLE
Issues building from source

### ISSUE THREAD

**Issue by ryanwawr** [primefaces/primeng#1039]
I reforked the repository a few releases ago, and the "Build from Source" instructions on the wiki page don't seem quite accurate since then.

The dependencies section that needs to be pasted into the package.json file to run the demo site is missing the webpack-dev-server package, but, even once I add that and get it to build, the styling on the site looks way off, as you can see in the screenshots below.

Dropdown page: http://screencast.com/t/iCwNe7fe6HE
DataTable page: http://screencast.com/t/aVN9dj8yM06
MegaMenu page: http://screencast.com/t/INyomjlHw

It's hard to report issues accurately without this working, as I am unable to reliably test whether the issue is with primeng code or with my implementation of it.

**Comment by JakeSummers** [comment]
Agreed.  This is really tricky to do.  I don't think this is an issue if you use the instructions here:

https://github.com/JakeSummers/primeng/tree/updatedReadme

Additionally, I was having trouble using my PrimeNg fork in my project, so I logged a issue #818.

**Comment by qjlee** [comment]
Or you can check out my answer here https://github.com/primefaces/primeng/issues/2301

**Comment by sudheerj** [comment]
The issue is because it requires SASS to CSS conversion.Either install SASS or node-sass to convert all theme CSS files.

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
