### ISSUE TITLE
When trying to lose focus from a calendar input (calendar view is shown), focus move to the calendar icon 

### ISSUE THREAD

**Issue by Neyra13** [primefaces/primeng#10397]
**Current behavior**
When click on a calendar input and click on another input or any part of screen to lose or change focus, the focus move to the calendar icon.

**Expected behavior**
When click on a calendar input and click on another input, the second one gains the focus.
When click on a calendar input and click on any part of the screen, the calendar icon loses focus.

**Minimal reproduction of the problem with instructions**
I have a p-calendar with those events and properties  : 
` <p-calendar
                          showButtonBar="true"
                          [showIcon]="true"
                          [focusTrap]="true"
                          appendTo="body"
                          id="date"
                          #date
                          (onClose)="setDateFocus(date,'button')"
                          (onShow)="setDateFocus(date, 'button', false)"
                          [disabled]=""
                          formControlName="date"
                          [required]=""
                        >
                        </p-calendar>` 
and `setDateFocus(element, value, isClosing = true) {
    this.featureService.setFocus(
      isClosing ? element.el : element.contentViewChild,
      value
    )
  }` 

**- What is the motivation / use case for changing the behavior?**
Improve user accessibility.

- **Please tell us about your environment:**

Windows 10 Pro , VSCode

- **Angular version:**

11.2.12

- **PrimeNG version:**

11.4.2

- **Browser:** 

All

**Comment by yigitfindikli** [comment]
Input components should focus on the main input. So it's by design.
