### ISSUE TITLE
How to always open a dropdown downwards

### ISSUE THREAD

**Issue by Nebojsa1005** [primefaces/primeng#10398]
Current behavior
Is there a way for a dropdown to always open downwards, is there maybe an option for controlling that behavior using PrimeNg?

Expected behavior
Dropdown to open downwards

What is the motivation / use case for changing the behavior?
At some screens the dropdown opens upwards and it is getting over the header

Please tell us about your environment: 
Windows 10 Pro , VSCode

Angular version: 
11.2.10

PrimeNG version: 
11.3.2

Browser: All

**Comment by yigitfindikli** [comment]
Please use the forum or discord channel for questions and help requests.
