### ISSUE TITLE
New DataTable Scrolling

### ISSUE THREAD

**Issue by yigitfindikli** [primefaces/primeng#10395]

**Comment by lf-novelt** [comment]
hello @yigitfindikli , since 12.1 my table does not display anymore the frozenColumns passed as Input parameters to the p-table element. I had to rollback to 12.0.1 to make them work again.

Is that expected? Are there any changes I am supposed to apply to my existing templates?

See my issue #10838

**Comment by yigitfindikli** [comment]
Yes, this is expected. Our Scrolling structure changed at 12.1.0-rc.1. You can see the "Breaking Change" label at https://github.com/primefaces/primeng/issues/10395. You can use pFrozenColumn directive instead of frozenColumns. 

Showcase examples: 
https://primefaces.org/primeng/showcase/#/table/scroll
https://www.primefaces.org/primeng/v12/#/table/scroll

Migration Guide: https://github.com/primefaces/primeng/wiki/Migration-Guide

**Comment by lf-novelt** [comment]
ok thanks, I saw the label but did not find anything like this wiki explaining it was intended, nor how to fix it.

So if `<p-table [frozenColumns]="myFrozenCols" columns="myScrollableCols"` is not supported anymore, could you hint us on how to migrate? Do I need to define a new template for frozenCols? Or is there a simple way to enable the pFrozenColumn  directive in my common column template? 

Thanks for the change anyway, as we noticed a few bugs with the old 2 tables behavior, but it would have been great to add some log or JS errors if if the old way of doing was detected and how to fix, like angular does in their breaking migrations.

**Comment by pheimill** [comment]
anything happen with this bug ?   how would we implement ngFor loop on frozen columns without this ?  we are trying to upgrade primeng to 12, but this is a major downgrade if this is not fixed.
