### ISSUE TITLE
FileUpload Component

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#104]

**Comment by pratikthecook** [comment]
Definitely needed component

**Comment by cagataycivici** [comment]
We've done it for PrimeFaces before, it will be more or less similar;

Advanced
http://www.primefaces.org/showcase/ui/file/upload/single.xhtml

Basic
http://www.primefaces.org/showcase/ui/file/upload/basic.xhtml

**Comment by GraemeSMiller** [comment]
Yeah the existing Angular 2 landscape doesn't seem to offer anything great for fileupload.Adding it would be a really boost for us as we could just rely on PrimeNG.

**Comment by cm0s** [comment]
@GraemeSMiller, I confirm there is no great file upload component available at the moment. I ended up building my own. Hope you guys gonna come up with a component as great as the other one you already built ;).

**Comment by cemremengu** [comment]
This should be on top of the priority list. It's a really crucial feature to be absent.

**Comment by cagataycivici** [comment]
Scheduled for beta14 (next one). FileUpload has the highest priority now.

**Comment by cagataycivici** [comment]
Almost done with it.
