### ISSUE TITLE
PrimeNg p-menu Label with image is not including style or class tag

### ISSUE THREAD

**Issue by vsawant18** [primefaces/primeng#10400]
I am using Angular 12, **p-menu** from **PrimeNg** which allows you to specify html as label using **escape:false**.
PrimeNg is picking up control but not style/class provided along with it.

(PrimeNg Reference : https://primefaces.org/primeng/showcase/#/menumodel)

**example.component.html**

`<p-menu #menu [model]="userMenu" [popup]="true"></p-menu>`

**example.component.ts**

```
this.username = this.authenticateService.getUsername();
this.userMenu = [{
          label: '<img src="' + this.userPhoto+ '" class="photo"></img><div style = "text-align:center">' + this.username + '</div>',
          escape: false,
          items: [{
                  separator:true
            },{
              label: 'Logout',
              icon: 'pi pi-sign-out',
              command: () => {
                  this.logout();
              }
          }]
```

**After launching application, HTML generated**

```
<li class="p-submenu-header ng-tns-c24-5 ng-star-inserted" style="">
   <span class="ng-tns-c24-5 ng-star-inserted">
      <img src="/assets/535324.jpg">
      <div>Vaibhav Sawant</div>
   </span>
</li>
```

Above generated HTML doesn't contains styling. Can you please here.

**Steps to Reproduce**

1) Pass HTML div/img with style tag in label attribute for menu model with escape:false
2) Run Application,
3) Style passed in label attribute are not applied

[Screenshots and Issue Details](https://stackoverflow.com/questions/68302371/primeng-p-menu-image-with-style)

**Comment by yigitfindikli** [comment]
You can use escape property of MenuItem.

**Comment by vsawant18** [comment]
As per given code, I am already using that. Still it's not picking up the style/class from html mentioned
