### ISSUE TITLE
Lazy loading service

### ISSUE THREAD

**Issue by PHuhn** [primefaces/primeng#10406]
**I'm submitting**
```
[X] feature request
```

**Request**
Don't Repeat Yourself (DRY).

I see that you have imbedded lazy-loading on table, treeTable, tree, virtualScroller and dataView.  I would like more lazy-loading on drop-down, list-box and multi-select, but I would like a more generic service that can be attached to any of the data list type of controls.  I think a more robust filter-service would be perfect.

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
