### ISSUE TITLE
Accessibility is not working properly in p-accordion component

### ISSUE THREAD

**Issue by prasadkhegade** [primefaces/primeng#10407]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-accordion-demo-2khtc8?file=src/app/app.component.html

**Current behavior**
Adding tabIndex="0" in content of <p-accordion> component causing accessibility issue. Tabbing traverse even accordion is in collapsed mode.

**Expected behavior**
If the accordion is collapsed mode then by pressing tab key it should go to next accordion. It should not go inside content.

**Minimal reproduction of the problem with instructions**
Steps:
1. Visit https://stackblitz.com/edit/primeng-accordion-demo-2khtc8?file=src/app/app.component.html
2. Make sure all tab are in collapsed mode
3. start pressing tab key.
 
It should jump to accordion to accordion but it reads the content from first tab where we have added tabIndex="0" 

**What is the motivation / use case for changing the behavior?**
To support accessibility compliance tabbing should work properly. Fixing this issue helps user for smooth keyboard interaction

**Please tell us about your environment:**
Windows

* **Angular version:** 5.X
11.2.9

* **PrimeNG version:** 5.X
11.4.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Version 84.0.4147.89
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript: 4.1.5

* **Node (for AoT issues):** `node --version` =   
node: v14.17.2
npm: 7.19.1

**Comment by prasadkhegade** [comment]
This was working in version 11.4.2

**Comment by denise1009** [comment]
We are encountering the same issue as stated above.  If the accordion is in collapsed mode then by pressing tab key it should go to next accordion. Currently, it tabs through each control within the accordion even when collapsed.

These are the versions we are using in our application.  
Angular 14.1.2
PrimeNG 9.1.3
NODE 16.16.0
NPM 8.11.0

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
