### ISSUE TITLE
Multi-select checkbox doesn't work on lazy loaded grids.

### ISSUE THREAD

**Issue by bilpor** [primefaces/primeng#10401]
**Current behavior**
in a lazy loaded grid when the select all checkbox in the header is selected, then for the first page this correctly checks all row checkboxes. If you move to another page, all row checkboxes are unselected, but the header checkbox remains selected.  For non-lazy loaded grids this works fine. If you go to a second page, header is selected and all rows are selected.

I have also tried declaring the table with:
<p-tableHeaderCheckbox #thc></p-tableHeaderCheckbox>
and introducing an onPage event
Hooking the code behind up with:
@ViewChild('thc') tblHeaderCheck: TableHeaderCheckbox;

and trying various forms of either checking all child checkboxes or unckecking the header with:

 ```
public PageChange() {
    if (this.tblHeaderCheck.checked) {
      this.tblHeaderCheck.checked = false;
     
     // this.tblHeaderCheck.updateCheckedState();
    }
    //if (this.tblHeaderCheck.checked) {
    //  this.tblHeaderCheck.checked = false;
    //  this.chkbox.forEach(function (value) {
    //    value.checked = true;
    //    value.value = true;
    //  });
    //}
  }
```
no combination of this works. My test for tblheaderCheck works, and at this point it appears to set header to false, but when rendered is still checked.

**Expected behavior**
On a lazy loaded grid either the header should untick or all the rows should tick.

**What is the motivation / use case for changing the behavior?**
It's not correct UI functionality. 

**Please tell us about your environment:**
Using Windows Server 2012 R2, with IIS

* **Angular version:** 9.1.7

* **PrimeNG version:** 9.0.6

* **Browser:** all 
 
* **Language:** All

* **Node (for AoT issues):**  V12.16.3

**Comment by yigitfindikli** [comment]
Issue is not clear, please feel free to reopen with a stackblitz example.

**Comment by bilpor** [comment]
Sorry, I may not have given a stackblitz example, but the issue is clear. There are plenty of other stackbitz examples in earlier versions where this issue persisted. To see the issue watch this example. First page is selected, when user demos going to second page. header checkbox is selected and the rows are not:  https://gitmemory.com/issue/primefaces/primeng/6482/491287012 this is the behaviour I am getting
