### ISSUE TITLE
p-tree with virtualscroll provide a method to scroll to particular node

### ISSUE THREAD

**Issue by ivan-artkod** [primefaces/primeng#10410]
**I'm submitting a ...**
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/ptree-virtualscroll-selected-node

The example shows how to perform scroll to element in tree the regular way, and how the same cannot be achieved when using `[virtualScroll]="true"`

**Current behavior**
No ability to "scroll to particular node" when using `[virtualScroll]="true"`, not even a workaround.

**Expected behavior**
Have a method to invoke virtual scroller positioning on a particular Node.

i.e.
```typescript
@Component(...)
export class FooComponent {
    ...
    @ViewChild('tree') tree!: Tree;
    ...
    scrollToNode(node: TreeNode) {
        this.tree.scrollIntoView(node);
    }
}
```

As a bonus, it would be nice that method works both with virtual scroll and without it (i.e. wrapper for DOM scrollIntoView and CDK virtual scroller)

**Minimal reproduction of the problem with instructions**
Check the stackblitz example

**What is the motivation / use case for changing the behavior?**
I.e. it is just not very useful to have a tree with virtual scroll where user has to scroll manually to get to the selected node.

**Please tell us about your environment:**
not-relevant

* **Angular version:**
not-relevant

* **PrimeNG version:**
not-relevant

* **Browser:**
not-relevant
 
* **Language:**
not-relevant

* **Node (for AoT issues):**
not-relevant

**Comment by ivan-artkod** [comment]
45+ days passed... no reaction, no interest?

**Comment by Architrixs** [comment]
@ivan-artkod is there any work-around for this?

**Comment by ivan-artkod** [comment]
> @ivan-artkod is there any work-around for this?

@Architrixs  I was unable to find one so far.

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
