### ISSUE TITLE
Double password meter after input

### ISSUE THREAD

**Issue by BillyCottrell** [primefaces/primeng#10415]
**I'm submitting a ...**
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://angular-ivy-gbyxsk.stackblitz.io
(I tried using the provided template, but wasn't able to 

**Current behavior**

When you click in the password field it shows the password meter but as soon as you start typing a second meter is being displayed if you then click outside of the field the first meter disappears but the second one doesn't.

**Expected behavior**

This duplicate meter shouldn't appear and that duplicate meter doesn't even disappear or work properly (neither does the original meter as both are conflicting with each other.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Having this duplicate meter causes multiple issues:
1. The password strength meter is displayed properly in the normal meter, but not in the duplicate one.
2. The password strength text is displayed properly in the duplicate meter, but not in the normal meter.
3. The duplicate meter does not disappear.

Because the duplicate meter is not disappearing the login process becomes really annoying/irritating as it hides the checkboxes or buttons or other fields underneath that field and ends up behind that meter.

**Please tell us about your environment:**

* **Angular version:** 12.1.1

* **PrimeNG version:** 12.0.0

* **Browser:** [Chrome XX | Firefox XX ]

 
* **Language:** [TypeScript 4.3.2]

* **Node (for AoT issues):** `node --version` =   v14.17.3

If I didn't provide enough information my apologies in that case and I will try to give the remaining info asap.

Thanks in advance,

Billy Cottrell

**Comment by yigitfindikli** [comment]
You don't need the pPassword directive and your style overriding the meter div. 

Example: https://stackblitz.com/edit/angular-ivy-obx3ow?file=src%2Fstyles.scss
