### ISSUE TITLE
Feature Request: onDblClick event for Dropdown component (and others?)

### ISSUE THREAD

**Issue by nicholas-ochoa** [primefaces/primeng#10420]
I know it's not a typical UI use case, but I'm trying to emulate the UI of a desktop application which currently supports double click on the Dropdown components to pop up a modal select list with advanced filtering. There are other components in PrimeNG that currently support onDblClick (notably the Listbox and Table components).

Is it possible to add onDblClick as a supported event to the Dropdown Component?

**Comment by nicholas-ochoa** [comment]
It looks like I'm able to accomplish this myself using @ViewChild:

```typescript
    ngOnInit() {
      setTimeout(() => {
        this.dropdown.containerViewChild.nativeElement.ondblclick = this.dblClickHandler;
      }, 0);
    }
```

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
