### ISSUE TITLE
BUG: Javascript error in Table when row element has Subject

### ISSUE THREAD

**Issue by gcorsaro** [primefaces/primeng#10421]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-tablestate-demo-gas9tr

**Current behavior**
In my project I have a table where, for each element, I add an async operation given by a Subject. The table has also a local storage (it also happens with session storage) and selection active. When I select one row I have the following error

`
ERROR TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'SafeSubscriber'
    |     property '_teardowns' -> object with constructor 'Array'
    |     index 0 -> object with constructor 'Subscription'
    --- property '_parentage' closes the circle
    at JSON.stringify (<anonymous>)
    at Table.saveState (table.ts:2071)
    at Table.handleRowClick (table.ts:1040)
    at SelectableRow.onClick (table.ts:2764)
    at Object.eval [as handleEvent] (VM10885 AppComponent.ngfactory.js:241)
    at handleEvent (view.ts:138)
    at callWithDebugContext (services.ts:641)
    at Object.debugHandleEvent [as handleEvent] (services.ts:381)
    at dispatchEvent (util.ts:135)
    at eval (element.ts:208)
`

I think this error is caused by storing the selection in the local storage. 
Nevertheless is happens only when both selection and storage are active. I tried to remove the storage, keeping the selection, and it works (no error). I also tried to remove the selection, keeping the storage, and it works as well.

**Expected behavior**
No error should be raised

**Minimal reproduction of the problem with instructions**
Just click one row in the plunker and you'll see the error

**What is the motivation / use case for changing the behavior?**
See the current behavior

**Please tell us about your environment:**
Windows 10, Eclipse, npm, weblogic

* **Angular version:** 5.X
9

* **PrimeNG version:** 5.X
9.1.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Tested on Chrome and FF

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
