### ISSUE TITLE
Tooltip support for advanced form components

### ISSUE THREAD

**Issue by sslee** [primefaces/primeng#1042]
Hover as the event works fine, but no tooltip is displayed if 'focus' is used. This is on the latest 1.0.0-beta.17

**Comment by cagataycivici** [comment]
This is expected since autocomplete is not a simple input component and tooltip attaches events to host, p-autoComplete event has no focus/blur, we'll review to see how this is possible.

**Comment by yigitfindikli** [comment]
We'll reconsider if there is more community feedback on this. Thank you for your report.
