### ISSUE TITLE
Splitter component: minSizes documentation inconsistencies and Stackblitz examples not rendering

### ISSUE THREAD

**Issue by Adit-COCO-Garg** [primefaces/primeng#10437]
**I'm submitting a feature request | Note: No access to the roadmap wiki** 
```
[ ] bug report => Search GitHub for a similar issue or PR before submitting
[X ] feature request => Please check if the request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
For the splitter component, the current [Stackblitz examples ](https://stackblitz.com/edit/primeng-splitter-demo) don't render anything within the canvas/ containers. It's just empty whitespace.  
![image](https://user-images.githubusercontent.com/23007265/126528045-39009e49-9090-4eaf-9fbf-976ff8a1be4e.png)

Moreover, the documentation is lackluster, minSizes has a type of number instead of number[] and the description for the property is somewhat confusing.

**Expected behavior**
Stackblitz would load in properly with the gutters, thumbs, and panels loading in as shown in the examples on the primeng page.

Better documentation for the splitter component.

**What is the motivation/use case for changing the behavior?**
When implementing this component in TS I used the type declaration `number` instead of `number[]` and the doc on primeNg and the examples were inconsistent. To verify the actual type, I checked the Stackblitz examples and since they didn't work I had to check the source code. This could have been avoided if the docs were consistent and the descriptions were simple.

**Please tell us about your environment:**
Chrome: Version 91.0.4472.124 (Official Build) (64-bit) (windows 10)

**Comment by yigitfindikli** [comment]
You need to use with "pTemplate" or "pTemplate="panel"". Thanks for the notice, stackblitz example is updated.
