### ISSUE TITLE
[PrimeNg][v11.4.3] P-Table unfrozen part default styleClass is undefined

### ISSUE THREAD

**Issue by LeonVay** [primefaces/primeng#10434]
Hello, same issue as described here:
https://github.com/primefaces/primeng/issues/3279

Code lines are not changed:
https://github.com/primefaces/primeng/blob/a48c3dcd2194e88aa9f1712b569c1ef9d8a4db26/src/app/components/table/table.ts#L2321
In case of no tableClass passed - unfrozen part p-datatable-body > table will be rendered with class="undefined"
PrimeNg version: v11.4.3

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
