### ISSUE TITLE
Getting error with angular 12 

### ISSUE THREAD

**Issue by akashgupta-1** [primefaces/primeng#10433]
I have already imported all module but still getting this error 

Error: src/app/home/view-all/view-all.component.html:6:83 - error NG8002: Can't bind to 'paginator' since it isn't a known property of 
'p-table'.
1. If 'p-table' is an Angular component and it has 'paginator' input, then verify that it is part of this module.
2. If 'p-table' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

6 <p-table [value]="tracksAndCourses"  [resizableColumns]="true" responsive="true"  [paginator]="true" [rows]="pageSize"
                                                                                    ~~~~~~~~~~~~~~~~~~

  src/app/home/view-all/view-all.component.ts:10:16
    10   templateUrl: "./view-all.component.html",
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component ViewAllComponent.

Error: src/app/home/view-all/view-all.component.html:6:102 - error NG8002: Can't bind to 'rows' since it isn't a known property of 'p-table'.
1. If 'p-table' is an Angular component and it has 'rows' input, then verify that it is part of this module.
2. If 'p-table' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

6 <p-table [value]="tracksAndCourses"  [resizableColumns]="true" responsive="true"  [paginator]="true" [rows]="pageSize"
                                                                                                       ~~~~~~~~~~~~~~~~~

  src/app/home/view-all/view-all.component.ts:10:16
    10   templateUrl: "./view-all.component.html",
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component ViewAllComponent.

Error: src/app/home/view-all/view-all.component.html:7:3 - error NG8002: Can't bind to 'lazy' since it isn't a known property of 'p-table'.
1. If 'p-table' is an Angular component and it has 'lazy' input, then verify that it is part of this module.
2. If 'p-table' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

 "dependencies": {
    "@angular/animations": "^12.1.2",
    "@angular/cdk": "^12.1.2",
    "@angular/common": "12.1.2",
    "@angular/compiler": "12.1.2",
    "@angular/core": "^12.2.0-next.2",
    "@angular/forms": "12.1.2",
    "@angular/http": "7.2.4",
    "@angular/material": "^12.1.2",
    "@angular/platform-browser": "12.1.2",
    "@angular/platform-browser-dynamic": "12.1.2",
    "@angular/platform-server": "12.1.2",
    "@angular/router": "12.1.2",
    "@azure/storage-blob": "^12.6.0",
    "@fortawesome/angular-fontawesome": "^0.3.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.8",
    "@fortawesome/free-regular-svg-icons": "^5.5.0",
    "@fortawesome/free-solid-svg-icons": "^5.5.0",
    "@microsoft/microsoft-graph-client": "^1.4.0",
    "@ng-bootstrap/ng-bootstrap": "^10.0.0",
    "@nguniversal/module-map-ngfactory-loader": "^5.0.0-beta.5",
    "@types/angular": "^1.7.0",
    "@types/quill": "^2.0.9",
    "angular-6-social-login": "^1.1.1",
    "aspnet-prerendering": "^3.0.1",
    "bootstrap": "^5.0.2",
    "chart.js": "^2.9.4",
    "chartjs-plugin-datalabels": "^0.7.0",
    "core-js": "^2.4.1",
    "file-saver": "^2.0.2",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "html2canvas": "^1.0.0-rc.3",
    "jquery": "^3.5.1",
    "jspdf": "^1.4.1",
    "ng-file-upload": "^12.2.13",
    "ng2-charts": "^2.2.3",
    "ng2-file-upload": "^1.3.0",
    "ngx-toastr": "^14.0.0",
    "primeicons": "^4.1.0",
    "primeng": "^12.0.1",
    "quill": "^1.3.7",
    "reframe.js": "^2.2.5",
    "rxjs": "~6.6.7",
    "rxjs-compat": "^6.3.3",
    "tslib": "^1.9.0",
    "xlsx": "^0.15.5",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^12.1.2",
    "@angular/cli": "^12.2.0-next.2",
    "@angular/compiler-cli": "12.1.2",
    "@angular/language-service": "12.1.2",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/jquery": "^3.3.22",
    "@types/node": "^6.0.118",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~6.3.4",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~7.0.0",
    "ts-node": "~4.1.0",
    "tslint": "~6.1.3",
    "typescript": "4.3.5"
  },
  "optionalDependencies": {}
}

**Comment by yigitfindikli** [comment]
Issue is not clear, please feel free to reopen with a stackblitz example.
