### ISSUE TITLE
p-tree draggable from root not working when in filter mode

### ISSUE THREAD

**Issue by rebelchris** [primefaces/primeng#10436]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/primeng-treedragdrop-demo-mjsrsj?file=src%2Fapp%2Fapp.component.html

**Current behavior**
- Type `h` in search filter 
- Drag documents into Movies
- - This is now duplicated?
- Drag Home into Movies
- This is correct 
- Remove filter
- dragged elements are now completely gone?

**Expected behavior**
I expect the draggable from root to work the same as how it works for dragging from children to children (this works)

**Minimal reproduction of the problem with instructions**
See current behaviour on provided stackblitz: 
https://stackblitz.com/edit/primeng-treedragdrop-demo-mjsrsj?file=src%2Fapp%2Fapp.component.html

**What is the motivation / use case for changing the behavior?**
This is a bug, it can't be solved otherwise then in the root project

**Please tell us about your environment:**
Angular, using Chrome 91 for the Stackblitz (MAC OS M1)

* **Angular version:** 5.X
Tested on 11 and 12

* **PrimeNG version:** 5.X
11.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All

https://user-images.githubusercontent.com/554874/126491769-e931b3be-6ae6-4883-b2f6-7e8b1cf9a411.mp4

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
