### ISSUE TITLE
Is dragging a row data from P-table to a tree view to different nodes and that drag data should be dropped to that particular node only. Is it possible?

### ISSUE THREAD

**Issue by Shanik09** [primefaces/primeng#10443]
Dragging data from table to a particular div I have already achieved but while trying to drag to different div's creating issue .
What I was trying to achieve is that a user can drag a row and drop to any tree node like manager david under manager or any other node. The row data will come and save on the particular node. Actual Link: stackblitz.com/edit
Before directly jumping into that I tried to drag a table row and save in different elements. Draging from table to a particular element like blue box is working fine. But when I am trying to create more elements for droping I am facing issue. The droppable elements are not fixed in number. So if you can tell how I can handle more than one element as droppable. Link: stackblitz.com/edit/primeng-treedragdrop-demo-zg9ujt?file=src/…

**Comment by yigitfindikli** [comment]
Please use the forum or discord channel for questions and help requests.
