### ISSUE TITLE
How to get index of element if we reorder it using drag and drop in the Primeng orderlist????

### ISSUE THREAD

**Issue by hamidh2** [primefaces/primeng#10445]
I'm using the OrderList for rendering a list of categories.
I want to change the order of each category in that list via drag and drop but it seems there is no way to detect the index of each element in that list before and after reordering via drag and drop!!!
by the way is there any way to detect such a thing???

Angular version: 11.1.1
PrimeNg version: 11.4.3

**Comment by yigitfindikli** [comment]
Please use the forum or discord channel for questions and help requests.

**Comment by hamidh2** [comment]
> Please use the forum or discord channel for questions and help requests.

I used those channels but unfortunately nobody answered me!!
