### ISSUE TITLE
PrimeNg custom validation using CSS

### ISSUE THREAD

**Issue by vchouksey54** [primefaces/primeng#10455]
I am using validationFlag in my TS code. Based on this I want to validate and focus PrimeNG elements (p-dropdown, p-autocomplete). I have tried below approach seems not working. However if I try similar on HTML elements then it works. Has anyone faced similar issues? None of below working -

<p-dropdown placeholder="1" [ngStyle]=" {'border-color':'red'}" >

<p-dropdown placeholder="2" [style]="{'border-color':'red'}" >

<p-dropdown placeholder="3" name = "val" id = "val" [style] =" mandatoryFlag=='set' ? {'border-color':'red'} : {'border-color':'blue'} " >

<p-dropdown placeholder="4" name = "val" id = "val" [ngStyle] =" mandatoryFlag=='set' ? {'border-color':'red'} : {'border-color':'blue'} " >

**Comment by yigitfindikli** [comment]
Use like this;
```

<p-dropdown [options]="cities" [style]="{'border-color': check ? 'red' : 'blue'}" [(ngModel)]="selectedCity1" placeholder="Select a City" optionLabel="name"
	[showClear]="true"></p-dropdown>
```
