### ISSUE TITLE
How to use [dateType]="string"  for calendar and in which format should be string?

### ISSUE THREAD

**Issue by genabush** [primefaces/primeng#10459]
<p-calendar [dateType]="string" [showIcon]="true" inputId="icon"
            formControlName="hotelOpenedDate">
  </p-calendar>

for hotelOpenedDate I tried:
'11/11/2019',
'2019-11-11',

**Comment by yigitfindikli** [comment]
You need to use dataType not dateType.

And please use the forum or discord channel for questions and help requests.
