### ISSUE TITLE
feature request: json api support

### ISSUE THREAD

**Issue by remmeier** [primefaces/primeng#1045]
it would be great to see some help to bind primeng to backend applications. Compare to Java Server Faces this is still a major pain point and results in a lot of extra work. JSON API and OData are two specifications that standardize resource-based rest apis. They allow to do sorting, filtering, paging, loading of related resources and validation. For this kind of APIs it is really easy to allow frontend compontents bind to them in a generic fashion without having to manually write the binding in every use case from scratch.

Both json api and odata are quite similar and maybe the implementation could be generic enough to support both and maybe others in the future. There sould be some basic building blocks that allow to quickly add support for such a specification.

json api is a bit closer to pure rest-style application than odata. With Katharsis there is a Java implemention that has quite some momentum lately and is progressing fast. And since primefaces has its root in the java world, json api could be the first target for a generic binding mechanism.

**Comment by cagataycivici** [comment]
Don't understand, JSON is first-class citizen for PrimeNG, all demos use it as well.
