### ISSUE TITLE
BUG: [v12.0.1 With Other versions ] Tree Selection Multiple Selection Add [filter]="true" ERROR !!!

### ISSUE THREAD

**Issue by MrZc** [primefaces/primeng#10450]
`<h5>Multiple Selection with Checkbox</h5>
<p-tree [filter]="true" [value]="files3" selectionMode="checkbox" [(selection)]="selectedFiles2"></p-tree>`

 **[filter]="true"**  The selected return is wrong after screening.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
