### ISSUE TITLE
Primeng v12 and primeflex v3 are incompatible

### ISSUE THREAD

**Issue by Jagan-P** [primefaces/primeng#10469]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

[https://stackblitz.com/edit/primeng-dataview-demo-f6fbie](url)

**Current behavior**
The PrimeNG components are still using the primeflex v2 css classes in the html (*.component.html file in Angulars). This makes it incompatible with primeflex v3. PrimeNG components has to be updated and a version has to be released.

**Expected behavior**
PrimeNG components should be useable with primeflex v3.

**Minimal reproduction of the problem with instructions**
I have included the stackblitz demo to reproduce this issue. 
* Basically use any primeng component as shown in primeng examples. 
* In your project update primeflex to v3.
* Migrate the html in your project (demo html) according to the migration guide here [https://www.primefaces.org/primeflex/migration](url)
* You will see that the layouts doesn't work since the core primeng components (eg: DataViewModule) still uses primeflex v2 classes.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Will occur on all environments

* **Angular version:** 5.X
Irrespective of Angular version

* **PrimeNG version:** 5.X
PrimeNG version 12 (will happen on all versions)

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by yigitfindikli** [comment]
Hi,

This issue exists in our roadmap. Thanks for the reporting.

**Comment by Jagan-P** [comment]
@yigitfindikli its been 5 months. Any idea on when this will be done?
