### ISSUE TITLE
#issues-10461 is not really working for me

### ISSUE THREAD

**Issue by akash0990** [primefaces/primeng#10463]
as suggested I have tried p-messages tag instead  of p-message

still it is not working for me 

PFA link for non working sample/example

https://stackblitz.com/edit/primeng-messages-demo-4safrl?file=src%2Fapp%2Fapp.component.html

**Comment by akash0990** [comment]
any update on this @yigitfindikli @DerekLiang

**Comment by akash0990** [comment]
Hi @yigitfindikli 
Any update on this ?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
