### ISSUE TITLE
PrimeNG Radio Button and Checkbox collapsed browser to top when the controls are in beyond scrollable viewport

### ISSUE THREAD

**Issue by KarthikDev81** [primefaces/primeng#10462]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```
**Current behavior**
While Clicking the PrimeNG Radio Button and Checkbox beyond the browser viewport, browser collapses to top.

**Expected behavior**
Browser should not collapse to top

**Minimal reproduction of the problem with instructions**
[Stackblitz](https://stackblitz.com/edit/github-dbbnss?file=src%2Fapp%2Fapp.component.html)

* **Angular version:** 10.2.X

* **PrimeNG version:** 10.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   
@cagataycivici

**Comment by yigitfindikli** [comment]
Unable to replicate with latest PrimeNG, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Comment by KarthikDev81** [comment]
Hope you didn't review my issue fully... Already included Stackblitz link https://stackblitz.com/edit/github-dbbnss?file=src%2Fapp%2Fapp.component.html
