### ISSUE TITLE
Primeng 11 Nova :- P-toast message background is transparent 

### ISSUE THREAD

**Issue by adwrakesh** [primefaces/primeng#10468]
Angular version 12
Primeng version 11
Theme Nova(primeng/resources/themes/nova/theme.css)

Issue :- P-toast message showing transparent background
![image](https://user-images.githubusercontent.com/63918684/127775358-f89948c4-dd7b-4be9-b506-f36664b6b490.png)

I have tried update/delete the opacity of background colour however its not resolving the issue

**Comment by yigitfindikli** [comment]
Nova is a legacy theme for v10, v11, and v12. You can override it.
