### ISSUE TITLE
ng template message is not working 

### ISSUE THREAD

**Issue by akash0990** [primefaces/primeng#10461]
message with image not working 

Ng template message feature is not working 
i have checked through stackblitz

no one example regarding this

want to use message with image but isn't support message with image

add for more reference 
https://primefaces.org/primeng/showcase/#/messages

Example ::
![image](https://user-images.githubusercontent.com/88134812/127467270-3d6b4996-537a-4de3-a05d-6a24e9c49af2.png)

```
<p-messages severity="info">
   <ng-template pTemplate>
       <img src="https://user-images.githubusercontent.com/88134812/127467270-3d6b4996-537a-4de3-a05d-6a24e9c49af2.png" width="32" />
       <span class="custom-message">I am the one who knocks.</span>
   </ng-template>
</p-messages>
```

paste it on https://stackblitz.com/edit/primeng-messages-demo but not working

if anything missed please let me know

**Comment by yigitfindikli** [comment]
p-messages do have template support, p-message doesn't have it.
