### ISSUE TITLE
Static content is not working in primeNg Angular

### ISSUE THREAD

**Issue by akash0990** [primefaces/primeng#10460]
click https://primefaces.org/primeng/showcase/#/messages
go to scroll down - static content

Static content is not working in primeNg

like

<p-messages severity="info">
    <ng-template pTemplate>
        <img src="assets/showcase/images/primeng.svg" width="32" />
        <div class="p-ml-2">Always bet on Prime.</div>
    </ng-template>
</p-messages>

**Comment by yigitfindikli** [comment]
The issue is not clear.
