### ISSUE TITLE
p-scrollPanel not updating scrollbar position when width of scrollpanel changes

### ISSUE THREAD

**Issue by dschencke** [primefaces/primeng#10479]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

This issue seems to be strongly related to this existing albeit closed previous issue: https://github.com/primefaces/primeng/issues/9727

**Current behavior**
When the width of the scrollpanel changes due to a change in width of the surrounding container element, then the scrollbar remains in the previous, now invalid, position until a scroll is performed or the mouse is moved outside of the scrollpanel.

![image](https://user-images.githubusercontent.com/28691558/128326273-5c1b459d-037c-451c-bb5a-e706102f69e2.png)

**Expected behavior**
The scrollbars position should be updated immediately when the size of the scrollpanel changes.

**Minimal reproduction of the problem with instructions**

* Open example at: https://stackblitz.com/edit/angular-ivy-awvvxd
* Click the "Toggle Width" Button to increase the width of the surrounding container element
* The scrollbar will now be in an invalid place until either a scroll is performed or the mouse is moved outside of the scrollpanel

**What is the motivation / use case for changing the behavior?**
I have an application where the width of the container element that surrounds the scrollpanel is changed due to a menu appearing or disappearing. I want to have the scrollbar in the correct position to not confuse users.

**Please tell us about your environment:**

* **Angular version:** 12.1.4

* **PrimeNG version:** 12.0.1

* **Browser:** [Chrome 92 | Firefox 90 | Edge 92] Does not seem to be browser-dependent though.

**Comment by Dzerominik** [comment]
+1

**Comment by dschencke** [comment]
Any updates on this? Any idea how this issue is prioritized?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
