### ISSUE TITLE
p-inputMask does not work with type=number

### ISSUE THREAD

**Issue by steigerm** [primefaces/primeng#10470]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://github-jkrgb2.stackblitz.io/

**Current behavior**
If a p-inputMask has
`type="number"`
set, it fails with 

> Error: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('number') does not support selection.

No value is displayed and the error message can be seen in the console

**Expected behavior**
no error

**Minimal reproduction of the problem with instructions**
See stackblitz

**What is the motivation / use case for changing the behavior?**
Want to use p-inputMask with type="number"

**Please tell us about your environment:**
Windows 10

* **Angular version:** 
See stackblitz

* **PrimeNG version:**
See stackblitz

* **Browser:** 
Chrome, Edge
 
* **Language:** 
See stackblitz

* **Node (for AoT issues):** 
See stackblitz

**Comment by BergkampHUN** [comment]
Without PRO Support: ~8-12 weeks.

2 Aug 2021 was 63 weeks ago... And still no fix for this bug.

**Comment by steigerm** [comment]
And that's only "Current Queue Time for Review" which never started.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by BergkampHUN** [comment]
@mertsincan 
The bug is still exists! Please reopen this case!

[https://angular-ivy-q3fgui.stackblitz.io](https://angular-ivy-q3fgui.stackblitz.io)
Here is the same example but updated to the latest primeNG and Angular

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
