### ISSUE TITLE
p-dropdown selection with FormControl.patchValue - always selects the first value

### ISSUE THREAD

**Issue by noamyg** [primefaces/primeng#10478]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/angular-ivy-xknudv?file=src/app/app.module.ts

**Current behavior**
I'm binding the value of a dropdown selection to a FormControl. To simplify client-server communication, I want to bind the id to the p-dropdown model and not the whole selection object. When I programmatically try to change the value of the selection, it doesn't matter what value I patch, the first value is being selected. In the example above, clicking "Choose Two" chooses "One" instead of "Two". Manual selection works as expected, of course.

**Expected behavior**
The selection will pick the right option (Clicking "Two" in the example above would select "Two")

**Minimal reproduction of the problem with instructions**
1. Add a `p-dropdown`, bound to a formControl
2. Configure the selection to have the value as the id and not the object (`dataKey="id" optionValue="id"
  optionLabel="name"`)
3. Try to change the value by `FormControl.patchValue` 

* **Angular version:** 11.X.X

* **PrimeNG version:** 11.X.X

* **Browser:** a;ll
 
* **Language:** Typescript (4.X.X)

**Comment by souhailharrati** [comment]
it works without datakey 

<p-dropdown
  #dropdown
  [options]="options"
  [attr.id]="'dropdown_id'"
  [filter]="true"
  appendTo="body"
  [showClear]="true"
  [formControl]="control"
  [placeholder]="placeholder"
  [style]="{ width: '100%' }"
  optionValue="id"
  optionLabel="name"
>

**Comment by sanchay-22** [comment]
Hello could you all hel me....lets say i have form with the drop down and i have filled the form and if i want to edit the form how should i path the previous dropdown selected value.
