### ISSUE TITLE
P-dialog cannot be dragged vertically if the page is scrolled down

### ISSUE THREAD

**Issue by heyaheyaho** [primefaces/primeng#10471]
I've reproduced the bug where it sticks to the top, although in my app it sticks to the bottom:

https://stackblitz.com/edit/github-kcqdmu?file=src/app/app.component.html

Anyway I don't want it to stick to edges, I want to be able to drag it where I want.

**Comment by frastam** [comment]
The same problem is present on demo PrimeNg dialog
https://www.primefaces.org/primeng/v11-lts/#/dialog

**Comment by frastam** [comment]
The problem was cause by this commit https://github.com/primefaces/primeng/commit/2aa494e2eb339350f267243b943267c6d093635b
Calculate wrong the offset for the dialog when scroled

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
