### ISSUE TITLE
p-table exportCSV with { selectionOnly: true } does not maintain current sort order

### ISSUE THREAD

**Issue by kirk-clawson** [primefaces/primeng#10475]
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
When exporting table contents via `exportCSV({ selectionOnly: true })`, the output's sort order is not the same as the current table's sort order. Without the options parameter, the sort order is maintained.

**Expected behavior**
Sort order should be maintained.

I'm assuming the reason for the bug is that [table.ts](https://github.com/primefaces/primeng/blob/11.4.4/src/app/components/table/table.ts#L1475) lines 1475-1477 are using `this.selection`, which does not get altered during order or filter operations.

A usable workaround for now is to filter the table by selected state, export without the options parameter, then unfilter the table.

* **Angular version:** 11.x
* **PrimeNG version:** 11.X, though the code appears the same in the 12.x branch, so I assume the issue persists there as well.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
