### ISSUE TITLE
In a Dynamic Dialog that is opened from another Dynamic Dialog, we can not press Tab to focus on the next field

### ISSUE THREAD

**Issue by phuctvt** [primefaces/primeng#10472]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Stackblitz Case (Bug Reports)**
https://stackblitz.com/edit/primeng-dynamicdialog-demo-adhpi8

**Current behavior**
1. Open a Dynamic Dialog from another Dynamic Dialog.
2. There are some input fields in the dialog, when I press Tab, it will not focus on the next field.

You can try the issue by the link Stackblitz above.

**Expected behavior**
It should focus on the next input field.

**What is the motivation / use case for changing the behavior?**
If the dialog I mentioned is the dialog of filling some fields, the tab-focus-next-field behavior should works.

**Please tell us about your environment:** Stackblitz

* **Angular version:** 11.0

* **PrimeNG version:** 11.3.0

* **Browser:** I tested on Chrome and Firefox
 
* **Language:** TypeScript

**Comment by tisys-parceiros** [comment]
was this problem resolved?

**Comment by miguelarcjr** [comment]
I have the same problem

**Comment by nev-21** [comment]
me too, same problem

**Comment by mselerin** [comment]
This seems related to #9329 for which I have a [workaround](https://github.com/primefaces/primeng/issues/9329#issuecomment-1276432459) :-)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by jayee** [comment]
This is still a problem in 17.3.3.

The tab-key does not cycle between focusable elements correctly. It gets stuck on the close-x when using tab-key. It can shift-tab one step.
