### ISSUE TITLE
Try to contact your commercial team

### ISSUE THREAD

**Issue by ybarbaria** [primefaces/primeng#1048]
Hello,

Sorry for this post :(

I try to contact your commercial team for some questions.

I am interested in buy the template ultimate for angular2 (primeNg) in commercial version, I wonder if it is possible to test this template on our project. 
Do you have a lite version to test? Or can I try the full version ?

If is it not possible to try the template, is it possible to buy the non commercial version and after I we like our template buy the commercial version without the price of the non-commercial version? 

Thx 

Yvan

**Comment by cagataycivici** [comment]
Please send an email to contact at primetek.com.tr.
