### ISSUE TITLE
aria 508c accessibility - p-multiselect prevents focus to select-all checkbox

### ISSUE THREAD

**Issue by kwc-scopeinfotech** [primefaces/primeng#10486]
This is a bug/issue unable to penetrate

All inputs to the p-multiselect were exercised to enable the select-all checkbox for aria 508c accessibility NAVIGATION

this checkbox remains disabled 100% of the time for KEYBOARD navigation which is essential for the disabled blind users.
this checkbox responds well to mouse left button clicks to check/uncheck

To reproduce create a template similar to this one        

```
<div #container [ngClass]="{'p-multiselect p-component':true,
            'p-multiselect-open':overlayVisible,
            'p-multiselect-chip': display === 'chip',
            'p-focus':focus,
            'p-disabled': disabled}" [ngStyle]="style" [class]="styleClass"
            (click)="onMouseclick($event,in)">
            <div
                itemLabel="Checkbox"
                class="p-hidden-accessible">
                <input #in type="text" readonly="readonly" [attr.id]="inputId" [attr.name]="name" (focus)="onInputFocus($event)" (blur)="onInputBlur($event)"
                       [disabled]="disabled" [attr.tabindex]="tabindex" (keydown)="onKeydown($event)" aria-haspopup="listbox" [attr.aria-expanded]="overlayVisible"
                       [attr.aria-labelledby]="ariaLabelledBy"
                       itemLabel="Checkbox"
                       [attr.aria-roledescription]="'Select all items'" aria-live="polite"
                       role="checkbox" tabindex="0"
                       aria-atomic="true" aria-label="" aria-describedby="checkboxDrama" >
                <span [hidden]="true" aria-label="checkbox"  value="Checkbox" for="Checkbox"></span>
            </div>

```
What is the motivation / use case for changing the behavior?
508c govt compliance

Impact
Blind user cannot navigate to select ALL

Please tell us about your environment:
MACOS + google screen reader

Angular version: 11

PrimeNG version: 11.4.2

Browser: CHROME

kennethcolassi@Scope-2021-010 primeng % ng --version
Your global Angular CLI version (12.1.3) is greater than your local version (11.0.7). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.0.7
Node: 14.17.3
OS: darwin x64

Angular: 11.0.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1100.7
@angular-devkit/build-angular      0.1100.7
@angular-devkit/build-ng-packagr   0.1002.0
@angular-devkit/core               11.0.7
@angular-devkit/schematics         11.0.7
@angular/cdk                       11.0.4
@angular/cli                       11.0.7
@schematics/angular                11.0.7
@schematics/update                 0.1100.7
ng-packagr                         11.0.3
rxjs                               6.6.7
typescript                         4.0.8

kennethcolassi@Scope-2021-010 primeng % node --version
v14.17.3

**Comment by yigitfindikli** [comment]
We planned full accessibility support for the next versions of PrimeNG. Thank you for your report. PrimeNG will be fully accessible soon.
