### ISSUE TITLE
OverlayPanel target arrow points to the wrong position when target is on the right edge of the screen

### ISSUE THREAD

**Issue by thsoliveira** [primefaces/primeng#10484]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/angular-ivy-1asash

**Current behavior**
I'm having the same problem with the overlaypanel when it's called in the right edge of the screen the arrow shows out of the panel box. I don't know if it's an issue of my project or if it's a primeng thing because of the arrow position calculation it seems weird. This only happens when the overlaypanel is called on the right side of the screen, if I change the position of the element that calls the overlaypanel everything works just fine.

![image](https://user-images.githubusercontent.com/40253255/128383593-18f3e16d-7544-45b9-adb6-eb83fd6f1a27.png)

**Expected behavior**
Should open the overlaypanel with the arrow above the box

**Minimal reproduction of the problem with instructions**

1. Click on the button to open the overlaypanel

https://stackblitz.com/edit/angular-ivy-1asash

**What is the motivation / use case for changing the behavior?**
When the overlay panel is called on the edge of the right side of the screen the arrow is misplaced 

**Please tell us about your environment:**

* **Angular version:** 5.X
12.2.0

* **PrimeNG version:** 5.X
12.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

* **Node (for AoT issues):** `node --version` =   
all

**Comment by bgl3317** [comment]
I'm having the same issue in v11.

**Comment by moussa-b** [comment]
I would add also that the close icon is wrongly placed 

![image](https://user-images.githubusercontent.com/26151311/143888541-fa0a6e0c-946d-4426-ab8f-45e66a89888e.png)

**Comment by kunjan343** [comment]
Any progress? Hate to say PrimeNG library is not designed properly.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by cetincakiroglu** [comment]
fixed in https://github.com/primefaces/primeng/commit/f9f7e47ae1de95fa096e4aa0e76d335234c05255
