### ISSUE TITLE
Avatar - Image/Icon/Label priorities

### ISSUE THREAD

**Issue by Relic** [primefaces/primeng#10487]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
The Avatar component template behavior gives labels priority over icons & images, and icons priority over images.
```
// ...
<span class="p-avatar-text" *ngIf="label; else iconTemplate">{{label}}</span>
<ng-template #iconTemplate><span [class]="icon" [ngClass]="'p-avatar-icon'" *ngIf="icon; else imageTemplate"></span></ng-template>
<ng-template #imageTemplate><img [src]="image" *ngIf="image"></ng-template>
// ...
```
[Avatar Source](https://github.com/primefaces/primeng/blob/master/src/app/components/avatar/avatar.ts#L9)

**Expected behavior**
Would be nice for the priority to be the opposite - images should have priority over icons and icons over labels, so users can try to load images/icons and use icons/labels as fallbacks on failure.

**Minimal reproduction of the problem with instructions**
Default behavior - see source code above.

**What is the motivation / use case for changing the behavior?**
Being able to use the icon/label as a fallback for failure to load an image. In general labels would probably be constant or set dynamically in-app without any loading required, so it makes sense to use that as a fallback for a failed image/icon load.

**Please tell us about your environment:**

* **Angular version:** 5.X
latest

* **PrimeNG version:** 5.X
latest

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
