### ISSUE TITLE
Inconsistent filtering behavior in p-dropdown when options contain diacritics

### ISSUE THREAD

**Issue by lubobalogh** [primefaces/primeng#10482]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-mwxf96?file=src/app/app.component.ts

**Current behavior**
When trying to filter options containing letters with diacritics (especially `ˇ` character) e.g. `ľ`, `š`, `č`, `ť`, `ž`, `ď`, etc., by using their unaccented versions (`l`, `s`, `c`, ...) in filter input within p-dropdown component, these letters are not matched by the filter. Letters containing `´` character (`á`,`í`,`é`, ...) are matched correctly in this case using their unaccented versions (`a`, `i`, `e`, ...).

**Expected behavior**
Letters containing `ˇ` character should be also matched by the filter.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/github-mwxf96?file=src/app/app.component.ts

1. Open dropdown
2. Type `C` letter into filter input
3. Filter does not match `č` character and dropdown shows `No results found`
4. The same behavior is also with `D`, `L` letters

When you type `A`, `E` letters into filter input, the filter matches `Á`, `é` correctly and the result option is shown.

**What is the motivation / use case for changing the behavior?**
Consistent filtering behavior

* **Angular version:**
12.0.1

* **PrimeNG version:**
12.0.1

* **Browser:**
all
 
* **Language:**
TypeScript 4.0.2

**Comment by shaizel** [comment]
Perhaps it would be better to use a 3rd party package like [remove-accents](https://github.com/tyxla/remove-accents) instead of maintaining an in-house function.
If not, maybe go over the diacritics handled by the `remove-accents` package and add the ones that are missing to the `objectutils.removeAccents` function?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by lubobalogh** [comment]
Hi, this issue still persists in PrimeNG v.15.3.0. The major cause is that `objectutils.removeAccents()` method doesn't correctly match mentioned characters.

**Comment by mertsincan** [comment]
Hi @lubobalogh,

Could you please try the fix at https://github.com/primefaces/primeng/pull/11573? I'll merge it asap after it is updated.

Best Regards,

**Comment by lubobalogh** [comment]
Hi @mertsincan,
I created new PR, so it should be ready for merge.

Thank you.
