### ISSUE TITLE
OverlayPanel target arrow points to the wrong position when target is on the right edge of the screen

### ISSUE THREAD

**Issue by thsoliveira** [primefaces/primeng#10481]
I'm having the same problem with the overlaypanel when it's called in the right edge of the screen the arrow shows out of the panel box. I don't know if it's an issue of my project or if it's a primeng thing because of the arrow position calculation it seems weird. This only happens when the overlaypanel is called on the right side of the screen, if I change the position of the element that calls the overlaypanel everything works just fine. 

![image](https://user-images.githubusercontent.com/40253255/128383593-18f3e16d-7544-45b9-adb6-eb83fd6f1a27.png)
Duplicate of #

_Originally posted by @thsoliveira in https://github.com/primefaces/primeng/issues/9441#issuecomment-893582367_

**Comment by yigitfindikli** [comment]
Issue is not clear, please feel free to reopen with a stackblitz example.
