### ISSUE TITLE
p-table using ng-template cannot be switched between data or p-skeleton

### ISSUE THREAD

**Issue by BillyCottrell** [primefaces/primeng#10497]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

Using `<ng-template [ngIf]="isLoading">...</ng-template>` works to show the contents when isLoading is true but when updating that value in the ngOnInit method the ng-template keeps displaying even if the value would be false.
This way it is not possible to properly use the p-skeleton as mentioned in the docs.

I tried to use it outside the p-table and ng-template just works fine, is it possible that when using 2 ngTemplates the pTemplate cannot be the same name even though both contents should be displayed in the body but are not meant to be used in the body at the same time.

**Expected behavior**

It should be possible to switch between p-skeleton and data template.

**Minimal reproduction of the problem with instructions**

https://stackblitz.com/edit/github-ztod99

The above stackblitz example shows that the p-skeleton is always being shown even though that ngIf would result in false instead of true.

**What is the motivation / use case for changing the behavior?**

I want to use this when the data is loading or when the data is being refreshed.

**Please tell us about your environment:**

* **Angular version:** 12.1.1

* **PrimeNG version:** 12.0.0

* **Browser:** [ Chrome 92.0.4515.131 | Firefox 91.0 ]

 
* **Language:** [ TypeScript 4.3.2]

* **Node (for AoT issues):** `node --version` =  v14.17.3

**Comment by yigitfindikli** [comment]
You don't need 2 templates for the load control.

example:

```
  <ng-template pTemplate="body"  let-device>
    <tr *ngIf="isLoading">
      <td>
        <p-skeleton></p-skeleton>
      </td>
      <td>
        <p-skeleton></p-skeleton>
      </td>
      <td>
        <p-skeleton></p-skeleton>
      </td>
      <td>
        <p-skeleton></p-skeleton>
      </td>
    </tr>
    <tr *ngIf="!isLoading">
      <td>{{device.name}}</td>
      <td>{{device.type}}</td>
      <td>{{device.os}}</td>
      <td>{{device.ip}}</td>
    </tr>
  </ng-template>
```

**Comment by BillyCottrell** [comment]
@yigitfindikli I know that it makes sense to do it that way, but for some reason, this doesn't work either.
Using the code you provided it would rather result in the whole template not working, neither the skeleton nor the data is being shown, even updating the isLoading boolean doesn't work.

The weirdest part is that I can't recreate the issue in stackblitz, even though in my own project it doesn't want to work.
So I have no clue as to why that might be.
