### ISSUE TITLE
Data Table grouping rowspan

### ISSUE THREAD

**Issue by IvanPrytsko** [primefaces/primeng#1049]
Hi, all. Is it any way to group items by some category like a shown below?

```
___________________
| Category | Item |
--------------------
| music    | mp3 |
|          --------
|          | flac |
--------------------
| video     | mp4  |
|           ---------
|           | avi  |
--------------------
```

If there are no grouping options, like this, maybe at least `rowspan` for `table body`
In docs there are an example how to group columns in `header`, but for table body it doesn't work .
I tried to set `rowspan` to `p-column`, no changes. 
For now I'm using `1.0.0-beta.12`. Maybe on new versions it's able?
Thanks!

**Comment by cagataycivici** [comment]
This feature will be added in near future after 1.0.

**Comment by Parthchokshi** [comment]
http://stackoverflow.com/questions/40249952/primeng-datatable-rowspan-tbody-solution/40249953#40249953

I did my own solution. See if this can help you.

**Comment by cagataycivici** [comment]
RowGrouping is available for some time.
