### ISSUE TITLE
Find in Page Feature

### ISSUE THREAD

**Issue by sotoh** [primefaces/primeng#10496]
Currently there is no module or library to perform a Find in Page (like any browser's Find function used by shortcut CTRL + F) where inside the SPA you type a word and quickly gets highlight and jump to the location of matched word. I understand outside there are engines for web search (like Algolia) but the main goal of this is to perform a local search within the current site or SPA.

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
Greetings PrimeTek

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
