### ISSUE TITLE
Add compareWith attribute to p-dropdown

### ISSUE THREAD

**Issue by johnmanko** [primefaces/primeng#10498]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Only way to alter comparison is the `dataKey`.

**What is the motivation / use case for changing the behavior?**
Angular offers a `compareWith` feature that allows the app developer to customize how options are compared.  `p-dropdown` should offer something similar.

* **Angular version:** 5.X
12

* **PrimeNG version:** 5.X
12

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by Et3rnal** [comment]
This is still an issue. please add this so it can be used
im using auto complete instead when dealing with objects due to this limitation

**Comment by HarrisonCreates** [comment]
> This is still an issue. please add this so it can be used im using auto complete instead when dealing with objects due to this limitation

Use `dataKey` and tie it to the key of the property you want to compare against. Full documentation: https://primeng.org/multiselect#api.multiselect.props.dataKey

I know you mentioned it as the "only" current method, but is even dataKey insufficient for what you need?

**Comment by Et3rnal** [comment]
`compareWith` is needed when comparing different types/objects. So if the comparison is a bit complicated than a key matching on both then dataKey will be insufficient.

Anyway I think its an edge case, I have changed my options to work with dataKey way
