### ISSUE TITLE
Virtual scroll frozen row bug

### ISSUE THREAD

**Issue by curciot** [primefaces/primeng#10501]
there's an error on table component the frozen body for virtual scroll use the bodyTemplate instead of the frozenBody Template on table.ts row 120

old code:
  `<tbody class="p-datatable-tbody p-datatable-frozen-tbody" *ngIf="frozenValue||frozenBodyTemplate" [value]="frozenValue" [frozenRows]="true" [pTableBody]="columns" [pTableBodyTemplate]="bodyTemplate" [frozen]="true"></tbody>`

how it should be:
  `<tbody class="p-datatable-tbody p-datatable-frozen-tbody" *ngIf="frozenValue||frozenBodyTemplate" [value]="frozenValue" [frozenRows]="true" [pTableBody]="columns" [pTableBodyTemplate]="frozenBodyTemplate" [frozen]="true"></tbody>`

**Comment by yigitfindikli** [comment]
Our scrolling table changed in 12.1.0-rc.1. Fixed now.
