### ISSUE TITLE
Autocomplete in group mode

### ISSUE THREAD

**Issue by Dashti81** [primefaces/primeng#10502]
**I'm submitting a ...** 
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/angular-ivy-z8bmvs

**Current behavior**
Unselect the selection after click outside the autocomplete

**Expected behavior**
When you select an item from the dropdown should stay selected.

**Minimal reproduction of the problem with instructions**
The steps to reproduce:
- Type anything in de autocomplete field
- Then you see the results in de the dropdown
- navigate with your keyboard arrow to an item and press enter to select
- You see your selection in autocomplete field
- press tab or click outside the autocomplete
- at this moment the selection disappear  

**What is the motivation / use case for changing the behavior?**
Accessibility of the component 

* **Angular version:** 5.X
12

* **PrimeNG version:** 5.X
12

----

The issue is when I use combination of group and forceSelection. I think the bug is on line 801 in this file (https://github.com/primefaces/primeng/blob/master/src/app/components/autocomplete/autocomplete.ts).
```
let itemValue = this.field ? ObjectUtils.resolveFieldData(suggestion, this.field) : suggestion;
```
Here itemValue is empty because of property suggestion has a nested structure in group mode. In normal mode this is flat array. 

I hope this issue is clear, please let me know if you need more info or a pull request of the fix.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
