### ISSUE TITLE
Slider does not provide accessible role for assistive technology

### ISSUE THREAD

**Issue by brianhollings** [primefaces/primeng#10500]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
The Slider component is not providing a valid accessible role for assistive technology including screen readers. Correct information is not being provided for screen reader users. When the element is focused the role of "slider" and it's values are not announced.
`<span class="p-slider-handle ng-star-inserted" tabindex="0" aria-valuemin="0" aria-valuenow="2" aria-valuemax="100" style="left: 2.55102%; transition: none 0s ease 0s;"></span>`

**Expected behavior**
The component should announce as a slider and announce the min/max/current values.
`<span class="p-slider-handle ng-star-inserted" tabindex="0" aria-valuemin="0" aria-valuenow="2" aria-valuemax="100" style="left: 2.55102%; transition: none 0s ease 0s;" role="slider"></span>`

**What is the motivation / use case for changing the behavior?**
To improve the accessibility of the slider component.

**Please tell us about your environment:**
Windows with NVDA and JAWS. Mac with VoiceOver

* **Angular version:** 5.X
12

* **PrimeNG version:** 5.X
12

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 All

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
