### ISSUE TITLE
aria-label dropdown

### ISSUE THREAD

**Issue by dazilb** [primefaces/primeng#10508]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/primeng-dropdown-demo-udjs3u?file=src%2Fapp%2Fapp.component.html

**Current behavior**
specifying "ariaFilterLabel" prop on p-dropdown does not affect the component, and the input field within p-dropdown has no aria-label

**Expected behavior**
Give the input element in p-dropdown an aria-label, similar to the "ariaLabelledBy" prop (which does work as expected)

*STEPS TO REPRODUCE*
implement a p-dropdown and specify the "ariaFilterLabel". Notice the input tag doesn't have an aria-label.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 12

* **PrimeNG version:** 12.1 && 11.4.4

* **Browser:** [all]
Chrome  
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by yigitfindikli** [comment]
We planned full accessibility support for the next versions of PrimeNG. Thank you for your report. PrimeNG will be fully accessible soon.
