### ISSUE TITLE
calendar inside dialog cut of on scroll

### ISSUE THREAD

**Issue by keschr** [primefaces/primeng#10511]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/primeng-calendar-demo-pcg29f?file=src/app/app.component.html

**Current behavior**
Check out the plunker, click on the first button "Open Dialog". Inside the dialog, click inside the calendar field. The calendar opens and is aligned at the top of the page. 
Now close the dialog and scoll down to the button "Open Dialog" at the bottom of the page. Click on it and open again the calendar field. Now the calendar is cut up at the top. In my case it has top: 621.2px;, but it should be 770px because of the scrolled body.

**Please tell us about your environment:**

* **Angular version:** 12.2.1

* **PrimeNG version:** 12.1.0-rc.1

* **Browser:** all

**Comment by yigitfindikli** [comment]
Hi @keschr,

Try with `<p-dialog  appendTo="body...>`.

**Comment by keschr** [comment]
> Hi @keschr,
> 
> Try with `<p-dialog appendTo="body...>`.

Hi, do you checked the plunker? I added appendTo="body".

**Comment by yigitfindikli** [comment]
Hi @keschr,

Yes, I checked. 

I said for dialog not calendar.

See;

> Hi @keschr,
> 
> Try with `<p-dialog appendTo="body...>`.

Your dialog doesn't have an appendTo property.

Your code:

```
<p-dialog header="Header" [(visible)]="displayModal" [modal]="true" [style]="{width: '50vw'}" [draggable]="false"
    [resizable]="false">
```

**Comment by keschr** [comment]
I tried this but still same issue.

![image](https://user-images.githubusercontent.com/60967123/129885390-c3e720d5-1113-4519-97f7-e57039a936f2.png)

**Comment by piyush11031** [comment]
I am also facing the exact same issue. I am using appendTo = 'body' on both Dialog and Calendar component. I am currently using Primeng v13. Is there a fix to this?
