### ISSUE TITLE
Table keyboard navigation: fix arrow keys for inline-editing input fields

### ISSUE THREAD

**Issue by JauernigIT** [primefaces/primeng#10519]
**I'm submitting a bug**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When using a p-table with cell-based editing, I cannot choose dropdown/auto-complete items or increasing/decreasing number inputs by using the arrow up/down keys, since those will select the previous/next table row instead of manipulating the input.

**Expected behavior**
Inside a p-table, the arrow up/down keys should manipulate the input in a pEditableColumn as it's expected and working outside a p-table. Alternatively, there should be an option to completely deactivate the arrow navigation feature inside a p-table.

**Please tell us about your environment:**
* **Angular version:** 12.0.3
* **PrimeNG version:** 12.1.0-rc.1
* **Browser:** all
* **Language:** all

**Related**
[https://github.com/primefaces/primeng/issues/6982](https://github.com/primefaces/primeng/issues/6982)

**Comment by nbobelet** [comment]
I just updated my primeng and saw this "feature/bug". I didn't find on the internet or in the docs a way to fix this problem without touching the module itself. In "/node_modules/table/table.d.ts"  "class EditableColumn", we can see 4 new functions compared to an older version of primeng
    - onArrowDown(event: KeyboardEvent): void;
    - onArrowUp(event: ''KeyboardEvent''): void;
    - onArrowLeft(event: KeyboardEvent): void;
    - onArrowRight(event: KeyboardEvent): void;

Personally, I did a search for these functions in all the primeng folder and remove the calls to these functions in all the files of type *table.js

**Comment by maleet** [comment]
Really annoying

**Comment by aneesazam** [comment]
Please fix it. This feature look like a bug. My all invoices are not useable now so I decided to revert back to 10.1.4 Lts.

**Comment by mlabbayeasape** [comment]
Yes, really annoying, could you please fix it or create a property to disable it ?

**Comment by keschr** [comment]
Please fix it

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by maleet** [comment]
I can confirm that this problem still exists

**Comment by aneesazam** [comment]
Hi @maleet, I check it just now and it is still exist in PrimeNG 14.2.0

**Comment by bornedj** [comment]
Please fix, this issue is still present when using angular 15.2 and PrimeNG 15.4.1.

**Comment by AloveSoftwise** [comment]
How after two years is this still an issue?  Do the developers not use this stuff at all?  I'm using 15.2.0.

I promise you if you tried it, you'd say "This is not functional or workable at all"

**Comment by Yuri-Lima** [comment]
has this issue fixed? Any resolution so far?

**Comment by Yuri-Lima** [comment]
up ?

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
