### ISSUE TITLE
Primeng12 regression : not working anymore on angular libraries (Maximum call stack size exceeded)

### ISSUE THREAD

**Issue by adessilly** [primefaces/primeng#10515]
**I'm submitting a ...**  
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
It is not possible to demonstrate on stackblitz because it is a bug at compile time for an angular library.
Find a minimalistic library project here (it is just a ButtonModule importer on an empty library) : 
https://github.com/adessilly/primeng12libissues
You can check the build error here : https://github.com/adessilly/primeng12libissues/runs/3361155275?check_suite_focus=true

<img width="856" alt="Capture d’écran 2021-08-18 à 15 06 02" src="https://user-images.githubusercontent.com/10973554/129903211-4ecb3f48-08b3-498f-bb04-e4325377acd4.png">

**Current behavior**
`✖ Compiling with Angular in legacy View Engine compilation mode.
Maximum call stack size exceeded`

**Expected behavior**
The build should work (it works with primeng11)

**Minimal reproduction of the problem with instructions**
```
ng new primeng12libissues
cd primeng12libissues/
ng g library testlib
npm i primeng@12
```
Then import ButtonModule in the lib module

Then run : 
`ng-packagr -p projects/testlib/ng-package.json`

**What is the motivation / use case for changing the behavior?**
Our libraries don't compile anymore

**Please tell us about your environment:**
terminal

* **Angular version:** 12.2.1
It is the most recent version, but it works with primeng11, not with primeng12

* **PrimeNG version:** ^12.0.2
(also tested with rc, same issue)

* **Browser:** [none ]
no need of a browser
 
* **Language:** [TypeScript 4.3.5]

* **Node (for AoT issues):** `node --version` =  15.3.0 (but tested on 14 and 16)

**Comment by gzayat** [comment]
I have same problem using primeNG version 12 and ng-packagr generate module;

Maximum call stack size exceeded

**Comment by yigitfindikli** [comment]
View Engine is deprecated. See: https://angular.io/guide/updating-to-version-12.

**Comment by adessilly** [comment]
What do you mean about that ? In tsconfig, I can put "enableIvy": false or "compilationMode": "partial", the problem remains the same with your primeng12. But With primeng11, no issues at all, even in an angular12 libraries.

**Comment by yigitfindikli** [comment]
@adessilly

Try with:

package.json => scripts
`"build:lib": "ng build testlib"`

**Comment by adessilly** [comment]
@yigitfindikli thx :-)

**Comment by gzayat** [comment]
Using 
-ng serve
-ng build

no problem.

But i will use ng packagr for generate component Maximum call stack size exceeded

**Comment by gzayat** [comment]
Add in project one item of primeng
import {ButtonModule} from 'primeng/button/primeng-button';

Error  **'Maximum call stack size exceeded'**
persist to generate npm run packagr using in package.json  lib ng-packagr

using npm build not problem.
Problem persist using packagr for generate component

**Comment by gzayat** [comment]
@yigitfindikli 

problem solved using 
Using angular 12
ng-packagr 12.2.1
 with primeng version 11.4.0

**Comment by vittal288** [comment]
Still getting the same error **Maximum call stack size exceeded**

![image](https://user-images.githubusercontent.com/3775684/190080262-292ac9e3-8561-4479-82ea-27b9c7aeab08.png)
![image](https://user-images.githubusercontent.com/3775684/190080422-dce33bd2-a1fb-434c-964c-bb585d023476.png)
