### ISSUE TITLE
Frozen columns with scrolldirection=both doesn't work correctly

### ISSUE THREAD

**Issue by zypus** [primefaces/primeng#10514]
```
[x] bug report 
[ ] feature request
[ ] support request
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-tablescroll-demo-sxjgmj?file=src/app/app.component.html

**Current behavior**
Frozen columns stay fixed while scrolling horizontally only up to a certain point and then do not stay fixed anymore and scroll away. (Only happens to columns frozen to the left of the table)

**Expected behavior**
Frozen columns should always stay fixed no matter where the horizontal scrollbar is.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/primeng-tablescroll-demo-sxjgmj?file=src/app/app.component.html

Just add a frozen column and make the table scrollable in both directions.

**Please tell us about your environment:**

* **Angular version:** 12.X

* **PrimeNG version:** 12.1.0-rc1

* **Browser:** all
 
* **Language:** all

**Comment by yigitfindikli** [comment]
Fixed in https://github.com/primefaces/primeng/issues/10513
