### ISSUE TITLE
Tree is not refreshing when node is added programmatically and filter is enabled

### ISSUE THREAD

**Issue by averath** [primefaces/primeng#10518]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://primeng-treefilter-demo-jqtoyj.stackblitz.io/

**Current behavior**
When node is added programatically it appears on tree. 
When node is added programatically and filter is enabled it does not appear on tree.

**Expected behavior**
When node is added programatically and filter is enabled it appears on tree.

**Minimal reproduction of the problem with instructions**
Steps to reproduce:
1. Click add file button
1. new folder: 'file name' appears
1. In filter type 'fi'
1. Click add file button
1. Nothing happens
1. In filter type additional letter: 'l' (so the result is 'fil')
1. New folder 'file name' appears

Example:
https://primeng-treefilter-demo-jqtoyj.stackblitz.io

**What is the motivation / use case for changing the behavior?**
I would like to let user know that eveything work correctly after updating tree
~~I would like to not use workaround like:~~
~~`this.tree?._filter((document.getElementsByClassName('p-tree-filter')[0] as HTMLInputElement).value);`~~

**Tell us more about your environment**

* **Angular version:** 11.2.14 and 12.0.5

* **PrimeNG version:** 11.4.5 and 12.1.0-rc.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by matanbe4** [comment]
Having the same issue... The data sent to the onFilter callback is not updated until onFilter is triggered again.

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
