### ISSUE TITLE
*.metadata.json missing in version 12 and higher

### ISSUE THREAD

**Issue by majkers** [primefaces/primeng#10510]
Hello,
I am new to Angular and stuff but I have receantl updated my primeng version from 11.x to 12.x and using IntelliJ Idea I have noticed that suddenly my code completion stopped working. I have realised that it is due to the fact that there are no *.metadata.json eg. primeng-paginator.metadata.json in my node_modules folder with primeng. Is that a bug or shuld I do something else to generate them?

**Comment by yigitfindikli** [comment]
You need to update your IDE. I saw a similar issue on our Discord Channel.

PrimeLand: https://discord.com/invite/gzKFYnpmCY

**Comment by majkers** [comment]
Unfortunately I can't cause it costs a lot. There is no way You can add those files? In version 11 they were present...
