### ISSUE TITLE
Accordion programmatic change of tab.selected via ViewChild not updating visual state

### ISSUE THREAD

**Issue by Spiral1401** [primefaces/primeng#10512]
**I'm submitting a ...**  (check one with "x")

[x] bug report => Search github for a similar issue or PR before submitting

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-ulmgbj?file=src/app/app.component.ts

**Current behavior**
Changing the tab.selected property via ViewChild does not update the visual state of the accordion. See "Accordion 1" in stackblitz. (though it does appear to work the first time and the first time only)

**Expected behavior**
Tab visually opens or closes when ViewChild accordion.tab[x].selected changes

**Minimal reproduction of the problem with instructions**
Click the accordion 1 toggle button in stackblitz, then click the header a few times, then compare with the two-way bound [(selected)] tab in accordion 2

**What is the motivation / use case for changing the behavior?**
Changing the tab state this way used to work, seems like it should work? Also, I attempted to use two different internal methods to the accordion to update the visual state, but they didn't work (and probably weren't meant to be used by me so no big surprise).

**Please tell us about your environment:**
windows

* **Angular version:** 11.2.14

* **PrimeNG version:** 11.4.4
* For what it's worth, this also seems to happen in [PrimeNG 12](https://stackblitz.com/edit/github-r8grrz?file=src/app/app.component.ts)  (though the styling is messed up in this demo, the issue still occurs)

* **Browser:** Chrome

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
