### ISSUE TITLE
 TypeError: Cannot read property 'classList' of null     at Function.hasClass (primeng-dom.js:38)

### ISSUE THREAD

**Issue by elias-hjeir** [primefaces/primeng#10528]
Hi, the element comes as null in this class and lead to type error, can you please write null check before useing element.classList?

Many Thanks

**Comment by yigitfindikli** [comment]
Issue is not clear, please feel free to reopen with a stackblitz example.

**Comment by elias-hjeir** [comment]
@yigitfindikli  Oh sorry this is the first Issue I create, thanks
