### ISSUE TITLE
highlight selection row

### ISSUE THREAD

**Issue by rezaokhravi** [primefaces/primeng#10529]
![Screenshot (32)](https://user-images.githubusercontent.com/42868109/130605449-8e25a86d-6638-48c1-bed2-aa1dcc23a586.png)

when use row selection  and scrollbar , not highlight full width row selection

* **Angular version:** 12.X

* **PrimeNG version:** 12.1.0-rc1

**Comment by yigitfindikli** [comment]
Issue is not clear, please feel free to reopen with a stackblitz example.
