### ISSUE TITLE
Table Column width

### ISSUE THREAD

**Issue by deepaijantkar** [primefaces/primeng#1052]
Hello,
Is there anyway I can specify the width for the column or have the auto-fit option?

Thanks
Deepa

**Comment by ctrl-brk** [comment]
Unfortunately there's no autofit. All cells have equal size by default. But you can specify width.
`style="{'width': '100px'}"`

**Comment by deepaijantkar** [comment]
Thanks for the quick reply. When I apply the style on p-column, its will apply the style to table cell but not the header. How can I apply it to the header. 

<p-column field="DisplayName" header="Display Name" [style]="{'width': '200px'}"></p-column>

Thanks
Deepa

**Comment by ctrl-brk** [comment]
It works for me with header. And [style] attribute needs to be in square brackets. Do you have any other styles/settings on your table?

**Comment by deepaijantkar** [comment]
I don't have any other attributes. Following is my html

 <p-dataTable #dt [value]="Values" [resizableColumns]="true" columnResizeMode="expand" responsive="true">
    <p-column field="DisplayName" header="Display Name" [style]="{'width': '200px'}"></p-column>
...
 </p-dataTable>

**Comment by deepaijantkar** [comment]
Following is my code
`<p-dataTable #dt [value]="values" [resizableColumns]="true" columnResizeMode="expand" responsive="true">
    <p-column field="DisplayName" header="Display Name" [style]="{'width': '100px'}"></p-column>
...
</p-dataTable>`

**Comment by deepaijantkar** [comment]
Hi,
Thanks for your help! I could make table to auto fit 
`Css:
.ui-datatable table
{
    table-layout: auto !important;
}

Html:
<div *ngIf="values" class="pre-scrollable">
  <p-dataTable #dt [value]=values" responsive="true">
    <p-column field="DisplayName" header="Display Name"></p-column>
... rest of the columns
</p-dataTable>
</div>
`

**Comment by argnist** [comment]
If `[resizableColumns]="true" ` the columns do not use `[style]="{'width': '100px'}"`. Is it an expected behavior?

**Comment by bpbhat77** [comment]
How can we give dynamic width. I have width values in Component Class(controller).
I am trying to give like `[style]="{'width': col.width}"` and `[style]="{'width': {{col.width}}}"` . It is not working.

Any solution for this dynamic style issue?

**Comment by jmesa-sistel** [comment]
To add auto fit I've done
`<p-dataTable tableStyleClass="fixtable" .... `

in my local css I've added
`:host >>> .fixtable {
    table-layout: auto;
}`

Now the data table resize properly. I do not understand why in .ui-datatable table the table-layout is fixed.

@cagataycivici can you comment why table-layout:fixed is needed?

**Comment by cagataycivici** [comment]
Weird, resizing only works well to me it is fixed layout. Also layout:auto will break scrollable tables.

**Comment by ruchilabaruah** [comment]
Is there a way to get the current width of the column while we are resizing the columns? (Since the width change based on column resize)

**Comment by bgsavage** [comment]
Is there a planned fix to support table-layout:auto on scrollable tables? As you mentioned, it causes the columns to no longer be aligned with the data...

**Comment by cagataycivici** [comment]
No plans for table-layout:auto in scrollable tables due to technical reasons. Regarding the issue you can use style or styleClass option of column to specify width or tableStyle to set table-layout:auto if you are not using resize and/or scroll. Table-layout:auto will work fine except these two cases.

**Comment by saptarshi007** [comment]
'resizableColumns="true"' does work well for without frozen column. Say you have a table where you want to froze your first column and rest of the column you can expand. What would be the procedure? Can anybody faced the issue before

**Comment by tomvanh** [comment]
[tableStyle]="{'table-layout':'auto'}" works for the column width. thanks for it.

if you want it to work with scrolling you can add this to your css:
.ui-datatable-tablewrapper {
  overflow-x: auto;
}

**Comment by finalxcode** [comment]
+1

**Comment by lakerko** [comment]
@deepaijantkar thank you :)

**Comment by tiger5226** [comment]
If `[resizableColumns]="true"` the columns do not use `[style]="{'width': '100px'}"`. 

There should be a way to set the initial width of the columns from a `state`. Then when a user adjusts the width the callback can save the state.  Unfortunately, this is not possible because it is hardcoded into the style ( the initial width). Maybe this can be done with a directive. Not sure yet. Will edit comment with Plunkr if possible.

**Comment by Aaqib4021** [comment]
[style]="{ width: '100%' }" this works very well
