### ISSUE TITLE
Can't use KeyFilter with ngModel in Angular 12

### ISSUE THREAD

**Issue by cesarrew** [primefaces/primeng#10524]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-keyfilter-demo-zrojka?file=package.json
**-> Please select "Enable Ivy" option in settings to reproduce <-**

**Current behavior**
As the example in stackblitz shows, when using the KeyFilter with ngModel in Angular 12 with Ivy enabled, the following error appears on the console when starting the app:

The property and event halves of the two-way binding 'ngModel' are not bound to the same target.
Find more at https://angular.io/guide/two-way-binding#how-two-way-binding-works

**Expected behavior**
The app should start and the directive should work properly.

**Minimal reproduction of the problem with instructions**
Use the following code with Angular 12 with Ivy enabled (default when creating a new project):

<input pInputText pKeyFilter="pint" [(ngModel)]="myModel"  />

**Please tell us about your environment:**
Pop Os 20.04 and Node 14.

* **Angular version:** 12.2.2

* **PrimeNG version:** 12.1.0-rc.2

* **Browser:** all

* **Language:** TypeScript 4.3.5

* **Node (for AoT issues):** `node --version` =   14

**Comment by yigitfindikli** [comment]
Seems to work. Example: https://stackblitz.com/edit/primeng-keyfilter-demo-t3vrzu?file=src%2Fapp%2Fapp.component.html

**Comment by ryankugel** [comment]
@cesarrew I'm having the same issue:

- **Angular version:** 12.2.2
- **PrimeNG version:** 12.0.2
- **Language:** TypeScript 4.3.5

Copying and pasting the first example from @yigitfindikli's response does not work:
`<input type="text" [(ngModel)]="model" pInputText pKeyFilter="int" placeholder="Integers">`

This code worked fine with Angular 11 & PrimeNG 11, so not sure what the difference is.

**Comment by cesarrew** [comment]
#10535
