### ISSUE TITLE
Password meter not displaying when using pPassword directive

### ISSUE THREAD

**Issue by mohammadreza99** [primefaces/primeng#10525]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-1smhba?file=src%2Fapp%2Fapp.component.html

**Current behavior**
1- password strength meter not display when using `pPassword` directive instead of `p-password` component.
2- `p-password` doesn't have any output for blur event.

**Expected behavior**
1- display password meter as I typing.
2- notice when input blured

**Minimal reproduction of the problem with instructions**
Use the following code:
`<input type="password" pPassword>`

**Please tell us about your environment:**

* **Angular version:** 12.0.5

* **PrimeNG version:** 12.1.0-rc.1

* **Browser:** all
 
* **Language:** TypeScript 4.0.2

**Comment by yigitfindikli** [comment]
pPassword is deprecated. Use p-password component instead of pPassword directive.

**Comment by mohammadreza99** [comment]
@yigitfindikli I need a blur event but p-password doesn't have any output for blur.

**Comment by yigitfindikli** [comment]
Hi @mohammadreza99,

You can create a new ticket for onBlur and onFocus event. We can add it for the next release.
