### ISSUE TITLE
TypeError: Cannot read property 'classList' of null at Function.hasClass (primeng-dom.js:38)

### ISSUE THREAD

**Issue by elias-hjeir** [primefaces/primeng#10533]
Hi,
I have PrimeNG Table and in some column I have multiselect item as filter, when I select some option from the multiselect and then direct click out of the Table (anywhere in the page), I see this front-end exception.

![Anmerkung 2021-08-24 164113](https://user-images.githubusercontent.com/78030838/130637292-9ad54008-dbd9-4a90-ba10-72013079f666.png)

Can you help? thanks

**Comment by yigitfindikli** [comment]
Hi @elias-hjeir,

I couldn't replicate it with https://primefaces.org/primeng/showcase/#/table/filter. Can you create an example using https://stackblitz.com/edit/primeng-tablefilter-demo?file=package.json?
