### ISSUE TITLE
KeyFilter doesn't work with ngModel from Angular version 12.2 onwards (Angular PR 42601)

### ISSUE THREAD

**Issue by cesarrew** [primefaces/primeng#10535]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-keyfilter-demo-mrfdvo?file=package.json

**Current behavior**
As the example in stackblitz shows, when using the KeyFilter with ngModel in Angular 12.2 with Ivy enabled, the following error appears on the console when starting the app:

The property and event halves of the two-way binding 'ngModel' are not bound to the same target.
Find more at https://angular.io/guide/two-way-binding#how-two-way-binding-works

It seems that the change https://github.com/angular/angular/pull/42601 introduced in Angular version 12.2.0-next.2 is direct related to this problem.

**Expected behavior**
The app should start and the directive should work properly.

**Minimal reproduction of the problem with instructions**
Use the following code with Angular 12.2 with Ivy enabled (default when creating a new project):

<input pInputText pKeyFilter="pint" [(ngModel)]="myModel"  />

**Please tell us about your environment:**
Pop Os 20.04 and Node 14.

* **Angular version:** 12.2.2

* **PrimeNG version:** 12.1.0-rc.2

* **Browser:** all

* **Language:** TypeScript 4.3.5

* **Node (for AoT issues):** `node --version` =   14

**Comment by jimmylin212** [comment]
Got the same error using Galleria with the example code:

```html
<p-galleria [(value)]="images" [containerStyle]="{'max-width': '640px'}" [numVisible]="5" [circular]="true [showItemNavigators]="true" [showThumbnails]="false">
    <ng-template pTemplate="item" let-item>
        <img [src]="item.imageSrc" style="width: 100%; display: block;" />
    </ng-template>
</p-galleria>
```

**Comment by Primith** [comment]
Got the same error on KeyFilter with following configuration : 
Angular: 12.2.3
PrimeNg: 12.1.0
Typescript: 4.3.5
enableIvy: true
strictTemplates: true
Node: 14.17.1

Thanks.

**Comment by canberkardic** [comment]
Same here with
```js
        <p-galleria  [responsiveOptions]="responsiveOptions"  [containerStyle]="{'max-width': '640px'}"  [numVisible]="5" [(value)]="images"> 

          <ng-template pTemplate="item" let-item>
            <img [src]="item.previewImageSrc" style="width: 100%" />
          </ng-template>
          <ng-template pTemplate="thumbnail" let-item>
            <div class="p-grid p-nogutter p-justify-center">
              <img [src]="item.thumbnailImageSrc" />
            </div>
          </ng-template>
        </p-galleria>
        ```

**Comment by josuepiris** [comment]
Na versão 17 do primeng (angular 18), e o problema ainda persiste. :(
