### ISSUE TITLE
Picklist - [Feature Request]

### ISSUE THREAD

**Issue by mimoser** [primefaces/primeng#10539]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
Picklist:
Feature 1:

![Picklist_r1](https://user-images.githubusercontent.com/19664839/130762265-cf67d6ac-6845-469a-8a3a-405607475b1e.PNG)

Like you see in the picture in the target list Arabic is shown as last element, because i moved it from Source to Target.
Request: There should be an event, where we can declare what happens with the list, AFTER we moved the element.
afterMoveToTarget
afterMoveToSource

Feature 2:
![Picklist_r2](https://user-images.githubusercontent.com/19664839/130762828-c993e6f2-6938-457d-899e-b9e1606e11db.PNG)

In this case i clicked first on the 1st element and holding the "SHIFT" button and clicked to the 6th element. 
Current: Only 1st and 6th elements are selected
Should: Select element from 1st to 6th
![Picklist_r2_2](https://user-images.githubusercontent.com/19664839/130763259-63ab074e-b96b-4c03-a404-11d8dbbc2bbb.PNG)

Note: Duplicate to Feature Request #10537
Could´t figure out how to reopen.

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
