### ISSUE TITLE
The table column width is miss.

### ISSUE THREAD

**Issue by magicdict** [primefaces/primeng#10538]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**

the table column is same width @12.1.0-rc.2 
![image](https://user-images.githubusercontent.com/897796/130759739-8854ea2e-16e1-4e3d-8763-3887b86e1662.png)

**Expected behavior**
the table column will show with the width i setted in source code.

![image](https://user-images.githubusercontent.com/897796/130759507-2cdff7b4-46fd-4b19-b6c1-d21d32feffd7.png)

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 12.2.2

* **PrimeNG version:** 12.1.0-rc.2

* **Browser:** [all]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by yigitfindikli** [comment]
Seems to work. You can look at selection demos. https://stackblitz.com/edit/primeng-tableselection-demo and https://primefaces.org/primeng/showcase/#/table/selection.
