### ISSUE TITLE
Table Header Checkbox not working when lazy loading enabled

### ISSUE THREAD

**Issue by yigitfindikli** [primefaces/primeng#10532]

**Comment by Urtgard** [comment]
Is it possible to get the old behaviour back?

We use lazy loading and want to use the header checkbox to toggle the current page. We don't care about selections on other pages.

Now we can use the checkbox to select all rows on the active page, but we can't use the header check box to unselect the rows.
![rc2](https://user-images.githubusercontent.com/13890391/132015060-a0110ff2-f25b-41d3-8527-635a3175d248.gif)
![12](https://user-images.githubusercontent.com/13890391/132015226-e259f447-330f-412c-a6e6-2aa0b52dfd28.gif)

**Comment by jesuspa17** [comment]
+1

**Comment by fernandostein** [comment]
+1
Version: 13.0.2

**Comment by mertsincan** [comment]
Hi,

Thanks a lot for all feedbacks! You can track https://github.com/primefaces/primeng/issues/10951
Exp; https://www.primefaces.org/primereact/datatable/lazy/

**Comment by mertsincan** [comment]
Hi,

Fixed in https://github.com/primefaces/primeng/issues/10951. Also, I added a demo related to it on next version.

Best Regard,
