### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by mimoser** [primefaces/primeng#10537]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
Picklist:

1. It should be possible to sort the source and target lists after moving an item.
E.g. from list item "A" from Source to Target. "A" should appear now as first result in list Target.

2. Multiselect via shift
It shoud be possible to mutliselect the listitems via shift.

**Comment by yigitfindikli** [comment]
Issue is not clear, please feel free to reopen with more information about the feature requests.

**Comment by mimoser** [comment]
Feature 1:

![Picklist_r1](https://user-images.githubusercontent.com/19664839/130762265-cf67d6ac-6845-469a-8a3a-405607475b1e.PNG)

Like you see in the picture in the target list Arabic is shown as last element, because i moved it from Source to Target.
Request: There should be an event, where we can declare what happens with the list, AFTER we moved the element.
afterMoveToTarget
afterMoveToSource

**Comment by mimoser** [comment]
Feature 2:
![Picklist_r2](https://user-images.githubusercontent.com/19664839/130762828-c993e6f2-6938-457d-899e-b9e1606e11db.PNG)

In this case i clicked first on the 1st element and holding the shift button and clicked to the 6th element. 
Current: Only 1st and 6th elements are selected
Should: Select element from 1st to 6th
![Picklist_r2_2](https://user-images.githubusercontent.com/19664839/130763259-63ab074e-b96b-4c03-a404-11d8dbbc2bbb.PNG)
