### ISSUE TITLE
TypeError: Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by elias-hjeir** [primefaces/primeng#10540]
Hi, in the Demo of Table Filter
https://primefaces.org/primeng/showcase/#/table/filter
I have clicked on the Filter of "Name" for example, just clicked to open  it and I have direct clicked on the vertical scrollbar in the right, that makes the following error in Console: ERROR TypeError: Cannot read property 'classList' of null

Please see the attached images.

Thanks
![1](https://user-images.githubusercontent.com/78030838/130826072-a0b71e14-aa8b-434c-9e83-3422cbe33f1e.png)
![2](https://user-images.githubusercontent.com/78030838/130826097-c3fe6703-744c-472b-82b5-1d24842d730a.png)
![3](https://user-images.githubusercontent.com/78030838/130826114-322aa231-7809-483b-9fe9-bbc41266db2f.png)

**Comment by elias-hjeir** [comment]
Hi, I just wanted to ask if there is now some solution for this problem.
many thanks

**Comment by paulinaszablowska** [comment]
@yigitfindikli when the bug will be fixed? Is only null-check to add, but this is really necessary :)

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
