### ISSUE TITLE
p-dropdown with filter on disappears when selected

### ISSUE THREAD

**Issue by RivkaWeisz** [primefaces/primeng#10542]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
1. navigate to https://primefaces.org/primeng/showcase/#/dropdown on an iPad
2.  Try to open the dropdown with filter (Advanced with Templating, Filtering and Clear Icon)
3. The dropdown expands for an instant, then disappears.

**Expected behavior**
The dropdown should stay expanded and allow for filtering

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Testing this with an iPad pro, using Safari. I have seen previous mentions of this bug, for example 
https://stackoverflow.com/questions/55042435/primeng-dropdown-is-hidden-by-keyboard-on-a-mobile-device
https://forum.primefaces.org/viewtopic.php?t=57892

* **Angular version:** 10.2.3

* **PrimeNG version:** 6.14.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by rsjunior** [comment]
Same problem here.

**Comment by nev-21** [comment]
maybe this workaround will help you: https://github.com/primefaces/primeng/issues/10634#issuecomment-923164740
but it is for primeng 12.0.0

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
