### ISSUE TITLE
Add HTML anchors to the Documentation areas

### ISSUE THREAD

**Issue by juri-sinitson** [primefaces/primeng#10546]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
As example I'm unable to bookmark the document area `Change Detection` on https://primefaces.org/primeng/showcase/#/treetable 

**Expected behavior**
Every area of the documentation has its anchor, e.g. the area `Change Detection` would be
something like this: https://primefaces.org/primeng/showcase/#/treetable-change-detection

**Minimal reproduction of the problem with instructions**
Try to Bookmark `Change Detection` on https://primefaces.org/primeng/showcase/#/treetable or try to jump to `Change Detection` using the URL bar.

**What is the motivation / use case for changing the behavior?**
As an example other developers in our team should not forget to consider change detection when they use the components built on `TreeTable`.

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
