### ISSUE TITLE
Add more configuration to confirm method of ConfirmationService

### ISSUE THREAD

**Issue by thang1160** [primefaces/primeng#10545]
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

The `confirm` method of ConfirmationService, accepts the Confirmation interface which has many properties. It would be great if primeNG can use more of it. For instance, ConfirmPopup support header

**What is the motivation / use case for changing the behavior?**

Add more utility to primeNG

**Please tell us about your environment:**

* **Angular version:** 12.0.0

* **PrimeNG version:** 12.0.0

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
