### ISSUE TITLE
p-gmap component shows a grey map

### ISSUE THREAD

**Issue by jaurakunal** [primefaces/primeng#1055]
Hi,
I'm using the p-gmap component to plot a few addresses on the map. The Component loads but shows a grey square in the view instead of the plotted addresses. Here's the code I'm using.

**HTML**
```
<div class="w-section w-clearfix">
    <div class="w-section w-clearfix address-popup">
        <div class="list-group address-list">
            <a *ngFor="let item of addressList; let i = index" href="#" class="list-group-item list-group-item-action" (click)="handleAddressSelected(i)">
                <h5 class="list-group-item-heading">{{item.strAddr1 + (item.strAddr2 != null ? " " + item.strAddr2 : "")}}</h5>
                <p class="list-group-item-text">{{item.city + " " + item.state}}</p>
                <p class="list-group-item-text">{{item.country + " " + item.zipcode}}</p>
            </a>
        </div>
        <div class="address-map">
            <p-gmap [style]="{'width':'100%','height':'310px'}" [options]="mapOptions" [overlays]="mapOverlays"></p-gmap>
        </div>
    </div>
</div>
```
**Component Code**
```
import {Component, Input, EventEmitter, OnDestroy, OnInit, OnChanges, SimpleChanges} from "@angular/core";
import {IAddress} from "../../../profile/address.model";

declare var google: any;

@Component({
    moduleId: module.id,
    selector: 'pf-address-list',
    templateUrl: 'addressList.html',
    outputs: ['pfAddressSelected'],
    styleUrls: ['address.css']
})

export class AddressListComponent implements OnInit, OnDestroy, OnChanges {
    LOGGER_CLASS:string = "AddressListComponent";
    @Input('pfList') addressList:Array<IAddress>;
    response:JSON;
    error:JSON;
    pfAddressSelected:EventEmitter<IAddress>;
    mapOptions:any;
    mapOverlays:Array<any>;

    constructor() {
        this.pfAddressSelected = new EventEmitter();
        this.mapOverlays = new Array();
    }

    /**
     * In this function we init the map parameters
     */
    ngOnInit(): void {
        if(navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(this.setCurrentPosition.bind(this));
        } // End of if(navigator.geolocation)
    } // End of ngOnInit

    /**
     * This function clears the address list
     */
    ngOnDestroy(): void {
        this.addressList = null;
    } // End of ngOnDestroy

    /**
     * Once the list has been set from the parent, this is where we create the overlay for the map
     * @param changes
     */
    ngOnChanges(changes: SimpleChanges): void {
        if(this.addressList) {
            for(let i = 0; i < this.addressList.length; i++) {
                let addr:IAddress = this.addressList[i];
                this.mapOverlays.push(new google.maps.Marker({position: {lat: addr.latitude, lng: addr.longitude}, title: i}));
            } // End of for(let i = 0; i < this.addressList.length; i++)
        } // End of if(this.addressList)
    } // End of ngOnChanges

    /**
     * This function covers the flow after the user has selected an address
     * @param index
     */
    handleAddressSelected(index:string):void {
        let address:IAddress = this.addressList[index]
        this.pfAddressSelected.emit(address);
    } // End of handleAddressSelected

    /**
     * This function sets the current coordinates
     * @param position
     */
    setCurrentPosition(position) {
        this.mapOptions = {
        center: {lat: position.coords.latitude, lng: position.coords.longitude},
            zoom: 12
        };
    } // End of setCurrentPosition
} // End of export class AddressListComponent
```

**CSS**
```
.address-popup {
    float: left;
    display: flex;
    width: 100%;
}
.address-list {
    position: relative;
    width: 40%;
}

.address-map {
    position: relative;
    width: 60%;
}

.address-map-block {
    width: 100%;
    height: 310px;
}
```

Any help on this would be much appreciated.
Cheers
Kunal

**Comment by garethlewis** [comment]
What output do you get in the console?  And do you have a valid key?

**Comment by jaurakunal** [comment]
@garethlewis - I don't see any errors in the console. I'm attaching a screen shot of how the map shows up.
![p-gmap_error](https://cloud.githubusercontent.com/assets/12739201/19310659/114ea6be-9040-11e6-8f80-d4f5ec5b05d9.png)

**Comment by jaurakunal** [comment]
@garethlewis I do have a valid key

**Comment by garethlewis** [comment]
Okay, here is a very odd thing to try.  Use Ctrl + or - to change the viewport size of the webpage.  Does the map tile load?

**Comment by jaurakunal** [comment]
That didn't load the map tile. I've tried 2 different approaches
1. Use the example that is there on http://www.primefaces.org/primeng/#/gmap with hard coded values for options & overlays set in ngOnInit(). In that case I still see a grey map tile but i so see the Google logo on the bottom left of the map tile
2. My current approach (code pasted above) - in that case the options & overlay are populated a little later as I'm looking for the current position using the navigator.geolocation which requires a callBack function. In this case i don't even see the Google logo. One more thing I just noticed was that if I try and drag any portion of the map, i see multiple errors on the console. Sample pasted there

![p-gmap-console-error](https://cloud.githubusercontent.com/assets/12739201/19311079/b56c1f50-9041-11e6-99d1-0253888f2965.png)

**Comment by garethlewis** [comment]
And your index.html or whatever your landing page is called has the link to google maps?

**Comment by garethlewis** [comment]
Uhh, you just exposed your API key, unless you lock that down to your URL anyone can use that.

**Comment by jaurakunal** [comment]
@garethlewis The index.html has the link to google maps api. I actually just got it working. I think the issue was that while I was initializing the overlays array to a blank array the Options property was null. As soon as I initialized the options property to `{center: {lat: 0.00, lng: 0.00}, zoom: 4};`the map showed up properly. 

The only problem I have now is that the map remains centered at 0,0. I does not recenter itself to my location after the navigator.geolocation callBack function comes back. Any idea on how to do that?

**Comment by garethlewis** [comment]
this.gmap.map.setCenter(new google.maps.LatLng(position.lat, position.lng));

**Comment by jaurakunal** [comment]
@garethlewis - thx for pointing out the key thing and helping out with this. REALLY appreciate the super quick response on this :-)

**Comment by kcsahoo** [comment]
Refer to issue #924.
I have given the solution and it works.

**Comment by moudatsos** [comment]
@kcsahoo some pieces of info are not properly displayed in your answer. Could you resolve this, please?

**Comment by SanjeevKarki** [comment]
Hi.. I have a scenario where i need to use two maps ..displaying one at a time based on some condition.
I am using *ngif for hiding and showing the map.In my case when aaplication load map first time it load perfectly but the moment i hit again on the link..i only see a grey area nothing came...I have tried the trick which mention in above port click ctlr + and -..with this i can the see the map but how it can visible after loading...
