### ISSUE TITLE
npm install fails with dependency resolution

### ISSUE THREAD

**Issue by marob** [primefaces/primeng#10554]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Minimal reproduction of the problem with instructions**
Cloning the project (master and latest 12.1.0 release) and running `npm install` on it fails with dependency resolution:

```shell
git clone git@github.com:primefaces/primeng.git && cd primeng && npm i
```

or

```shell
git clone git@github.com:primefaces/primeng.git && cd primeng && git checkout 12.1.0 && npm i
```

**Current behavior**
`npm install` end with the following error on master:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: primeng@12.1.1-SNAPSHOT
npm ERR! Found: jspdf@1.5.3
npm ERR! node_modules/jspdf
npm ERR!   dev jspdf@"^1.5.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer jspdf@"^2.3.1" from jspdf-autotable@3.5.20
npm ERR! node_modules/jspdf-autotable
npm ERR!   dev jspdf-autotable@"^3.2.5" from the root project
```

and with this one for 12.1.0:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: primeng@12.1.0
npm ERR! Found: jspdf@1.5.3
npm ERR! node_modules/jspdf
npm ERR!   dev jspdf@"^1.5.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer jspdf@"^2.3.1" from jspdf-autotable@3.5.20
npm ERR! node_modules/jspdf-autotable
npm ERR!   dev jspdf-autotable@"^3.2.5" from the root project
```

**Expected behavior**
`npm install` should work.

Why don't the project have a `package-lock.json` file versioned?
Why has it been removed in this commit: https://github.com/primefaces/primeng/commit/3414833861799fbb703e7a3a33a115d61737e48f?

**Please tell us about your environment:**

```
> uname -rvspio
Linux 4.15.0-143-generic #147-Ubuntu SMP Wed Apr 14 16:10:11 UTC 2021 x86_64 x86_64 GNU/Linux
> node --version
v12.16.2
> npm --version
7.20.5
```

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
