### ISSUE TITLE
p-tree does not provide flexibility to lazy load data on scroll

### ISSUE THREAD

**Issue by chaitrashenoy33** [primefaces/primeng#10558]
p-tree has 4 level. Each level as lakhs of child nodes. so we wanted to handle lazy loading with scroll for 2nd, 3rd and 4th level  as well. 

*Current behavior*
lazy loading is currently possible for parent node(ie first level).

*Expected behavior*
for the second/third/fourth level we might have huge data nodes. so it will be easy if we have lazy loading with scroll for all child nodes 

*What is the motivation / use case for changing the behavior?*
Lazy loading on scroll to be handled for all child nodes

*Please tell us about your environment:*
Windows 10

* *Angular version:*
Angular 11

* *PrimeNG version:*
Primeng 9

* *Browser:* [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all 
 
* *Language:* [all | TypeScript X.X | ES6/7 | ES5]

* *Node (for AoT issues):* `node --version` =   12.18

**Comment by sridhark158** [comment]
+ 1 
it will be great if we get that

**Comment by DevInder1** [comment]
Even i am looking forward for the solution

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
