### ISSUE TITLE
Multiselect behavior issue when "chips" enabled

### ISSUE THREAD

**Issue by jsegarradev** [primefaces/primeng#10557]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
On multi-select with chips enabled: 
 If you "click" multi-select's input box on certain spot (when not all chips enabled are visible), it will close them as if you have clicked the cross icon even if that "chip" was not visible.

**Expected behavior**
When you "click" multi-select's input box, if you don't do it on a chip or a cross icon, it should just open the options panel.

**No Plunkr needed** since it is happening also in the examples at:  https://www.primefaces.org/primeng/v11/#/multiselect

Angular version: 11

PrimeNG version: 11.4.4

Browser: Chrome, Firefox

**Comment by yigitfindikli** [comment]
Hi @Jdevrra,

Thanks for your reprot. I couldn't replicate it. Can you share a video or more clear instructions?

**Comment by Jdevrra** [comment]
Hi @yigitfindikli.  
Thanks for your reply.
I attach a 70mb recorded screen video using primeng example multiselect from 11.4.4


[PrimeNG.zip](https://github.com/primefaces/primeng/files/7089145/PrimeNG.zip)

**Comment by jayee** [comment]
This is still an issue (13.3.2 https://www.primefaces.org/primeng/#/multiselect).
Select two cities, then the second city is not visible, only "...".
Click in the same position as the second close x would be visible if the select was wider.

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
