### ISSUE TITLE
Wrong auto zIndex in dynamic dialog

### ISSUE THREAD

**Issue by rezaokhravi** [primefaces/primeng#10569]
hi
when in Sidebar call DynamicDialog then dynamic dialog  zIndex  One number less than Sidebar  ZIndex.
for example : in pictures when click on " : " property "نوع دکمه"  (The first property on left Sidebar ) , 
then open  DynamicDialog  " مدیریت دکمه" , but open under Sidebar .
if Ctrl+F5 on page it is true.
please check.

can not example in stackblitz , because when update version primeng to v12.1.0  in Sidebar sample , It gives an update of the wrong version .

v12.1.0

**Comment by rezaokhravi** [comment]
![Screenshot (38)](https://user-images.githubusercontent.com/42868109/131635129-bbc8d775-e4fb-4465-86d9-6511005d7709.png)
![Screenshot (37)](https://user-images.githubusercontent.com/42868109/131635146-508e2825-2f74-4409-bf76-82a1e24201d4.png)

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue.
