### ISSUE TITLE
The equals method in DomHandler returns true when comparing two different dates

### ISSUE THREAD

**Issue by Krustie101** [primefaces/primeng#1056]
When comparing two different dates, the equals method returns true because a Date object apparently has no properties.

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/VZbdZfQ7SuTV87tTkbYR
