### ISSUE TITLE
Scrollable Table Always Occupying Full scrollHeight in v12.1.1

### ISSUE THREAD

**Issue by TheWrightDev** [primefaces/primeng#10566]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-tablescroll-demo-x9byly

**Current behavior**
The table always maintains the set scroll height even with less elements.

**Expected behavior**
The scroll height would be the max-height of the table not always the specific fixed height.
See 12.**0**.0 here: https://stackblitz.com/edit/primeng-tablescroll-demo-baudfr

**What is the motivation / use case for changing the behavior?**
Just how it's always always worked before, and when building a page with a bunch of tables you now have what appear to be large blank gaps between them but are just the table body always occupying the full height.

* **Angular version:** 12.2.3

* **PrimeNG version:** 12.1.1

**Comment by johnhwright** [comment]
Still an issue in 12.2.2. Is there some common workaround I'm missing for this one?

**Comment by TheWrightDev** [comment]
Still an issue in 12.2.2. Is there some common workaround I'm missing for this one?

**Comment by sdimitriadis** [comment]
Code workaround based on the above solution given by kirks:

```
  ngAfterViewInit() {
    let element = this.elementRef.nativeElement.querySelector('.p-datatable-wrapper');
    this.renderer.removeStyle(element, 'height');
    this.renderer.setStyle(element, 'max-height', '300px');
  }
```

using `ElementRef` and `Renderer2` from `@angular/core`.

**Comment by PranKe01** [comment]
That does only work on a "normal" table. When using the cdk-virtual-scroll-viewport this fix does not work :/

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
