### ISSUE TITLE
p-table renders badly with scrollable="true"

### ISSUE THREAD

**Issue by bartoszgebka** [primefaces/primeng#10560]
In the newest version of primeng the table with rowspan> 1 is drawn incorrectly. If I set scrollable = false everything is ok.

Example:

https://primeng-tablebasic-demo-uwy57j.stackblitz.io/

**Comment by yigitfindikli** [comment]
You need to use headergrouped and footergrouped like;

```
<ng-template pTemplate="headergrouped">
        <tr>
         ...
        <tr>
</ng-template>

<ng-template pTemplate="footergrouped">
        <tr>
         ...
        <tr>
</ng-template>
```
