### ISSUE TITLE
SpeedDial Within a Form

### ISSUE THREAD

**Issue by lazyeye73** [primefaces/primeng#10564]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
I've tried creating a stackblitz issue, but adding the SpeedDialModule to the template's app.module.ts causes an error that can't be resolved. I have included some code below instead.

**Current behavior**
When the SpeedDial component is used inside a form, clicking the associated button control submits the form.

**Expected behavior**
The form should not submit and the options associated with the SpeedDial component should appear.

**Resolution**
Adding `type="button"` to the button within the SpeedDial's template resolves the issue.
https://github.com/primefaces/primeng/blob/master/src/app/components/speeddial/speeddial.ts, lines 14 - 18

```
<button type="button" pRipple pButton [style]="buttonStyle" [icon]="buttonIconClass" [ngClass]="buttonClass()" (click)="onButtonClick($event)">
  <ng-container *ngIf="buttonTemplate">
    <ng-container *ngTemplateOutlet="buttonTemplate"></ng-container>
  </ng-container>
</button>
```

**Minimal reproduction of the problem with instructions**
app.component.html
```
<form [formGroup]="form" (ngSubmit)="submit()">
  <div class="p-fluid">
    <div class="p-grid">
      <div class="p-col-12">
        <p>Form Validity: <span>{{message}}</span></p>
        <input pInputText type="text" formControlName="name" />
        <button pButton label="Submit"></button>
        <p-speedDial [model]="items"></p-speedDial>
      </div>
    </div>
  </div>
</form>
```
app.component.ts
```
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { MenuItem } from 'primeng/api/menuitem';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent {
  form: FormGroup;
  items: MenuItem[];
  message: string = null;

  constructor(private formBuilder: FormBuilder) {}

  ngOnInit() {
    this.form = this.formBuilder.group({
      name: [null, [Validators.required]]
    });
    this.items = [
      {
        icon: 'pi pi-pencil',
        command: () => {
          this.message = 'Data Added';
        }
      }
    ];
  }

  submit() {
    this.message = this.form.valid ? 'Form Valid' : 'Form Invalid';
  }
}
```

* **Angular version:** 12.2.3

* **PrimeNG version:** 12.1.0

* **Browser:** [all]
 
* **Language:** [all]

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
