### ISSUE TITLE
Dropdown Accessibility Enhancements

### ISSUE THREAD

**Issue by yigitfindikli** [primefaces/primeng#10562]

**Comment by KapilSachdev** [comment]
Hello @yigitfindikli , I think this change caused the filter in [Dropdown](https://primefaces.org/primeng/showcase/#/dropdown) to close when searching while space is involved, so it has disabled filtering using multiple words.

Reproducible in `Advanced with Templating, Filtering and Clear Icon` on [Dropdown](https://primefaces.org/primeng/showcase/#/dropdown) page. Try `United States`, this will close the dropdown after `United ` is entered which is not expected.

**Comment by KapilSachdev** [comment]
I did not looked much for this issue, its already reported in #10621 with PR #10626 available.
