### ISSUE TITLE
Tree component do not remove node after dropping

### ISSUE THREAD

**Issue by sakshi456** [primefaces/primeng#10567]
Can we have a provision after drag and drop either from tree or drag&Drop component we do not remove the original node as we may have a possibility to be dropped to multiple places.

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by psavva** [comment]
Hi @cetincakiroglu   I'm also looking for this feature, and currently, the latest version of the DragDropModule does not support any options as not to remove the item dragged/dropped from the originating tree view.

Please can you review and re-open this ticket, adding the feature to the roadmap?
