### ISSUE TITLE
Menu is not positioned right with table

### ISSUE THREAD

**Issue by npradeep012** [primefaces/primeng#10576]
**Current behavior**

Menu options for each table row is not aligned properly. The position of menu is not aligned with the button when i use menu inside a  table and i have checked with [appendTo] attribute to it's still not aligned properly.

**Expected behavior**
Menu should be aligned with button

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/primeng-tablecrud-demo-pmqq17?file=src/app/app.component.html

**What is the motivation / use case for changing the behavior?**
Helps users to select options based on table information

**Please tell us about your environment:**
Visual studio code

* **Angular version:
12.2.3 

* **PrimeNG version:
12.1.0
![Capture](https://user-images.githubusercontent.com/25237006/131879150-8c3d0a34-e864-4992-9963-a2210be7b3d5.PNG)

* **Browser:** [all]

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
