### ISSUE TITLE
multiselect dropup position issue

### ISSUE THREAD

**Issue by rajasekar-pb** [primefaces/primeng#10572]
**Current behavior**
I'm using p-multiselect, in dropup after entering search value the dropup position looks floating from its original position ... this makes it looks like broken ... but the dropdown position is completely fine ...

**Expected behavior**
dropup was supposed to be in alignment with the select control, even after a search key is entered

**Environment:**
* **Angular version:** 12.2.1
* **PrimeNG version:** 12.0.0
* **Browser:** Chrome Version 92.0.4515.159 (Official Build) (64-bit)
* **Language:** TypeScript 4.3.5
* **Node:** 14.17.0   

![image_2021_09_01T10_09_33_048Z](https://user-images.githubusercontent.com/85222161/131655708-d083ab20-9355-4cd2-af98-851729869c55.png)

![image_2021_09_01T10_09_10_323Z](https://user-images.githubusercontent.com/85222161/131655720-cba7d57b-c40e-4772-9ad5-dc416334e936.png)

**Comment by irfan00007** [comment]
@rajasekar-pb  
facing the same issue any update on the Fix

**Comment by rajasekar-pb** [comment]
yes @irfan00007, 
This issue was resolved in the later minor version and even further refined in later major versions ... 
If possible try upgrading your primeng version to 13x or 14x based on your angular version ;)
ps: I am using v12.2.5-lts
