### ISSUE TITLE
Need Custom Sort Icon Support for p-table

### ISSUE THREAD

**Issue by dchiragbhansali** [primefaces/primeng#10579]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

Current behaviour does not allow the sorting icons to be modified, the three icons used are ["","",""]

**Expected behavior**

I would like to customize the sorting icons as per my design needs.

**Minimal reproduction of the problem with instructions**
1. Create a p-table component
2. Try to sort the columns. Notice the sorting icon. (these icons are not configurable).

**What is the motivation / use case for changing the behavior?**
1. While using the p-tables, we require to use a different set of sorting icons as per my application design.

* **Angular version:** 11.2.8

* **PrimeNG version:** 11.4.5

* **Browser:**: All
 
* **Language:** : All

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
