### ISSUE TITLE
ConfirmDialog closes immediately when opened shortly after another ConfirmDialog

### ISSUE THREAD

**Issue by DaBittna** [primefaces/primeng#10589]
**I'm submitting a ...**
```
[X] bug report
[ ] feature request
[ ] support request
```

**Plunkr Case**
https://stackblitz.com/edit/github-pga5co?file=src/app/app.component.ts

**Current behavior**
When opening a `ConfirmDialog` shortly after closing a previous `ConfirmDialog`, the second dialog disappears immediately.

**Expected behavior**
The second dialog should not disappear immediately.

**Minimal reproduction of the problem with instructions**
Here in this stackblitz I've simulated the problem:
https://stackblitz.com/edit/github-pga5co?file=src/app/app.component.ts
1. Click first button
2. Accept dialog
3. Second dialog disappears immediately

**What is the motivation / use case for changing the behavior?**
Concrete use case: 
1. A user wants to delete an item in the application
2. Confirmation dialog appears ("Are you sure?")
3. Call to API happens
4. Result from API: Can't delete item, but it is possible to force delete it
5. Second confirmation dialog appears ("Do you want to force-delete?")

**Please tell us about your environment:**

| OS | IDE | Package Manager |
| --- | ---- | ------------------- | 
| Windows 10 | JetBrains Rider 2021.2.1 | npm |

* **Angular version:** 12.1.1

* **PrimeNG version:** 12.1.0

* **Browser:** Edge 93, Chrome 93, Firefox 91
 
* **Language:** TypeScript 4.3.5, Target: ES2015

* **Node**: 16.4.0

**Comment by yelhouti** [comment]
I am facing the same issue,
This is because of of onHideAnimation that doesn't check if visible was changed back to true and proceeds to hiding... 
onOverlayHide specifically disableModality, should check if dialog is visible again before hidding the mask...

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
