### ISSUE TITLE
Change label of p-button produces TypeError

### ISSUE THREAD

**Issue by petrosD93** [primefaces/primeng#10585]
I'm submitting a 
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

When programatically changing label of button, I get the following error (see screenshot)
![image](https://user-images.githubusercontent.com/55806704/132216978-f0054422-4826-4d5d-8006-779c3a86fd83.png)
ERROR TypeError: Cannot read properties of undefined (reading 'trim')

On an action, I need to change the value of cancelLbl and I get the typerror.

TS:
`
  ngOnInit(){
    this.cancelLbl = 'Init'
  }

  onAction(){
    this.cancelLbl = 'New Value'
  }
`

HTML:

`
      <button
        pButton
        pRipple
        [label]="cancelLbl"
        type="button"
        class="p-button-rounded p-button-secondary mx-2"
        (click)="onCancel()"
      ></button>
`

**Comment by utraum** [comment]
Same Problem here. Using async pipe for label throws 'TypeError: Cannot read properties of undefined (reading 'trim')'

**Comment by finventario** [comment]
adding icon="pi" might fix the issue.
see https://forum.primefaces.org/viewtopic.php?p=193289#p193289

**Comment by adessilly** [comment]
We have the same issue, it occurs when we change the value of the label. Find below a reproduction of the regression : 
https://stackblitz.com/edit/primeng-calendar-demo-nhelhg?file=src%2Fapp%2Fapp.component.html

We found the regression in the commit : 
https://github.com/primefaces/primeng/commit/51a8426c9805e3689a4c0caea9ebac6fa6850129

setIconClass() is called when there is no icon on a  button, and so it sends null to DomHandler.addMultipleClasses(iconElement, this.getIconClass());

And DomHandler.addMultipleClasses tries to trim() a null value

![Capture d’écran 2021-10-05 170611](https://user-images.githubusercontent.com/10973554/136053515-43edd401-34ca-4006-a0a9-836ce917e302.png)

**Comment by yigitfindikli** [comment]
Unable to replicate with latest PrimeNG, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
