### ISSUE TITLE
Error on p-calendar with range mode and time pickers enabled

### ISSUE THREAD

**Issue by IreneTepe** [primefaces/primeng#10598]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
At the p-calendar component, combined with range mode, editable input and time pickers, we get an error when there are no selected days and we try to change the time via the p-calendar UI.
According to the console error, it refers to the the **updateTime()** function at the primeng-calendar.js file.

More specifically  we get ```this.value is null```, 
```
      if (this.isRangeSelection()) {
          value = this.value[1] || this.value[0];
      }
```

**Expected behavior**
An expected behavior could be for example to, disable the arrows of the time pickers in order to avoid unwanted error messages.

**Minimal reproduction of the problem with instructions**
- Create a p-calendar with **selectionMode="range"** and **[showTime]="true"**
- open the p-calendar UI and the browser console
- do not select any dates (also the input of the calendar will be empty)
- click on any of the time picker arrows to change the time
- console error is raised

**Please tell us about your environment:**

* **Angular version: 10.X

* **PrimeNG version: 10.X

* **Browser:** all
 
* **Language:** all

**Comment by lancechant** [comment]
I have the same issue, and the bug seems to be at least from V8 and this can be re-produced quite easily, this is the link for the calendar component on [stackblitz](https://stackblitz.com/edit/primeng-calendar-demo?file=src%2Fapp%2Fapp.component.html) can be found on prime ng component website as well. 

Changing this: 
`<div class="p-field p-col-12 p-md-4">
        <label for="time">Time</label>
        <p-calendar [(ngModel)]="date7" [showTime]="true" inputId="time"></p-calendar>
    </div>`

To this:
`<div class="p-field p-col-12 p-md-4">
        <label for="time">Time</label>
        <p-calendar [(ngModel)]="date7" [showTime]="true" inputId="time" selectionMode="range"></p-calendar>
    </div>`
**Note the addition of selectionMode="range"**
 causes the error to occur, can this be fixed just to check if:
`the.value !== undefined ` on the if statement

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
