### ISSUE TITLE
Bug : Paginator should stick to scrollable table on row number update

### ISSUE THREAD

**Issue by Torquin** [primefaces/primeng#10596]
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-tablescroll-demo-fkej1q?file=src/app/app.component.html

**Current behavior**
When using scrollHeight & paginator i'm getting some issues with paginator not sticking to bottom of table on paginator change / column filter

**Expected behavior**
As before, would like paginator to stick to bottom of table and not have empty space between the two.

**Minimal reproduction of the problem with instructions**
In stackblitz just change paginator from 10 to 5

* **Angular version:** 12.2.4

* **PrimeNG version:** 12.2.1

**Comment by sdimitriadis** [comment]
Code workaround based on the above solution given by kirks:

```
  ngAfterViewInit() {
    let element = this.elementRef.nativeElement.querySelector('.p-datatable-wrapper');
    this.renderer.removeStyle(element, 'height');
    this.renderer.setStyle(element, 'max-height', '300px');
  }
```

using `ElementRef` and `Renderer2` from `@angular/core`.

**Comment by yanli-yao** [comment]
Having the same problem in primeng 13.1.0.

**Comment by mmlitvin** [comment]
Same issue. What is the timeline for solving this defect?
