### ISSUE TITLE
Higher-order NgModules?

### ISSUE THREAD

**Issue by brian428** [primefaces/primeng#1060]
Just a suggestion: creating some higher-order NgModules (that export multiple component NgModules) would make importing and using the PrimeNG components a lot easier. Right now, you basically have to define a long list of module imports and/or shared exports (one for every component, as far as I can tell).

I can understand the current setup, where one only includes the modules they want and can omit the rest. But some of these (particularly the numerous form components) result in module import lists that are quite long. Maybe a parent module just for the form components would suffice, since that seems to be the one that can get the longest.

**Comment by cagataycivici** [comment]
Thank you, we'll review if there is more demand. Still I guess it would be better it this is done at application side by the application developer since they know what they need commonly.
