### ISSUE TITLE
Zeros in fractions

### ISSUE THREAD

**Issue by PetrJajtner** [primefaces/primeng#10606]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://primeng-inputnumber-demo.stackblitz.io

**Current behavior**
In "Min-Max Fraction Digits" I want to type text "0.00005" (which is allowed by maxFractionDigits) but it is imposible.

**Expected behavior**
Up to maxFractionDigits allow to type zeros in fractions.

**Minimal reproduction of the problem with instructions**
Go to https://primeng-inputnumber-demo.stackblitz.io, select all text in "Min-Max Fraction Digits" input box and try to type "0.00005" text.

**What is the motivation / use case for changing the behavior?**
The reason is obvious - the impossibility of writing a decimal part with zeros.

**Please tell us about your environment:**
Windows 10, Linux Mint 20

* **Angular version:** 12.2.4

* **PrimeNG version:** 12.1.0

* **Browser:** all
 
* **Node (for AoT issues):** `node --version` = v12.18.2

**Comment by mertsincan** [comment]
Hi,

I think this issue has been fixed in 12.1.1. Please try 12.1.1 version.

Best Regards,
