### ISSUE TITLE
p-InputNumber does not accept zeroes in decimal places past minFractionDigits

### ISSUE THREAD

**Issue by sev-svn** [primefaces/primeng#10602]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Plunkr Case (Bug Reports)**
https://github-zxlhk6.stackblitz.io/

**Current behavior**
When using InputNumber, zeroes input past minFractionDigits are ignored.

In the below example it is not possible to input zeroes past the first decimal place, e.g "1.101". 
```
<p-inputNumber mode="decimal" [minFractionDigits]="1" [maxFractionDigits]="10"></p-inputNumber>
```

**Expected behavior**
It should be possible to input zeroes past the minFractionDigits value

**What is the motivation / use case for changing the behavior?**
Numbers with zeroes in decimal places exists.

* **Angular version:** 11.1.1
* **PrimeNG version:** 11.2.0 (problem is present in v12.1.0)

* **Browser:** 93.0.4577.63 (Official Build) (64-bit)
 
* **Language:** TypeScript 4.0.2

**Comment by mertsincan** [comment]
Hi,

This issue has been fixed. Please try 12.1.1 version.

Best Regards,

**Comment by sev-svn** [comment]
> Hi,
> 
> This issue has been fixed. Please try 12.1.1 version.
> 
> Best Regards,

Hi, Thank you for a quick response! We will look into upgrading :-)
