### ISSUE TITLE
Wrong borders on scrollable table when upgrading to 12.1.0

### ISSUE THREAD

**Issue by 1bertillo** [primefaces/primeng#10603]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-tablecolresize-demo-gkg4nh?file=src/app/app.component.html

**Current behavior**
p-table on scrollable mode (scrollable = true) with all 4 borders set to 1px displays the borders of all cells twice (except for the bottom-border of the last row of the table and the left border of the first cell of all the rows). On the other hand, the behaviour in tables with no scroll is the same as before, when scrollable is set to false, the borders of the td on adjacent cells collapse and are shown as one border.
![image](https://user-images.githubusercontent.com/12542555/132695469-9454e2cc-1256-4d4b-ac1c-6e26131ea5e0.png)

This happened when updating primeng to 12.1.0, it does work as expected in 12.0.2, I suspect this is a side effect of the change of table to flex mode.

**Expected behavior**
Cell(td) borders should render the same border with no consideration if the table has scrolling enabled or not. 
![image](https://user-images.githubusercontent.com/12542555/132695561-8bd3d778-7449-42c5-8aa4-b8e95f2d38da.png)

**What is the motivation / use case for changing the behavior?**
Bad UX.

**Minimal reproduction of the problem with instructions**
In a scrollable table the effect described is observed. In the stackblitz, if the scrollable property is removed, it can be seen how the borders are rendered correctly, just once.

* **Angular version:** 12.0.5

* **PrimeNG version:** 12.1.0

**Comment by ManihtraA** [comment]
I'm also facing the same issue any fix for this?
