### ISSUE TITLE
'closeOnEscape' doesn't work for DynamicDialog

### ISSUE THREAD

**Issue by MaKCbIMKo** [primefaces/primeng#10604]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**
This is not a stackblitz link, but even here you can see it's not working - https://www.primefaces.org/primeng/showcase/#/dynamicdialog

**Current behavior**
Dynamic Dialog is configured as `{ closeOnEscape: true }` but pressing 'esc' doesn't close it.

**Expected behavior**
Dynamic Dialog is configured as `{ closeOnEscape: true }` and pressing 'esc' closes it.

**Notes**
Seems like regression after this commit (https://github.com/primefaces/primeng/commit/6c80340d42e34f61615794020698c3797d478a59): it changes `zIndex` calculation from `DomHandler.zindex` to `ZIndexUtils`, but `documentEscapeListener` still uses `DomHander`.

Also I noticed, that 'Dialog' and 'DynamicDialog' have slightly different `EscapeListener` logic - 'Dialog' just closes dialog on 'esc' event, but 'DynamicDialog' also checks if dialog instance is 'the top most' via `zIndex` comparison. Not sure if that by design or just missed point.

* **Angular version:** 12.2.4

* **PrimeNG version:** 12.1.0
 
* **Language:** TypeScript 4.3

**Comment by yigitfindikli** [comment]
Fixed in https://github.com/primefaces/primeng/commit/5d067084c884d47d0223fa800d75e90662ff441c#diff-3fed27d8c2f82a9912f6c74e80748912995a07d34dab3306fdeb02adc84b8b41
