### ISSUE TITLE
p-Table: resizing a scrollable table resizes the expanded row

### ISSUE THREAD

**Issue by Quacck** [primefaces/primeng#10609]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-tablerowexpansion-demo-te1jhb?file=src%2Fapp%2Fapp.component.html

**Current behavior**
Resizing a column in a table that has an expandable row, resizes the expanded row to the width of the first column of the parent-table. 

**Expected behavior**
The expanded row should have the width of the whole table. 

**Minimal reproduction of the problem with instructions**
- Go to the above stackblitz
- expand the first row. Notice how the width is still the same as the whole table.
- Also notice the column widths of the child-table
- Grab the resizer from 'Name', drag it to the left of 'Price'
- The expand row is now wrongly the size of the first column
- Scroll through the expanded row. The widths of the child-table's columns are also wrongly adjusted (they match the widths of the parent-table!)

**What is the motivation / use case for changing the behavior?**
We want to resize tables that have expanded rows. Resizing the parent table should not bleed into the child table.

**Please tell us about your environment:**

**Angular version:** 12

**PrimeNG version:** 12.1.0

**Browser:** Chrome Version 92.0.4515.159

**Language:** TypeScript

**Node (for AoT issues):** node --version = v14.15.4

**Comment by sandipchitale** [comment]
The rule like this:

```
#pr_id_1-table > .p-datatable-tbody > tr > td:nth-child(2)
```
seems to make an assumption that all rows of ```header```, ```body``` and ```rowexpansion``` templates have same column structure. But this may not be true for the ```rowexpansion``` template. For expansion rows we typically use:

```
<tr}>
  <td style="width: 3rem"><!-- whitespace in first column below the expansion icon --></td>
  <td colspan="N-1">
  ... expansion data which itself could be a table.
  </td>
<tr>
```
This needs to be fixed differently. At minimum srule can be:

```
#pr_id_1-table > .p-datatable-tbody > tr > td:not([colspan]):nth-child(2)
```
