### ISSUE TITLE
Contact | Security Issue 

### ISSUE THREAD

**Issue by hagaiwech** [primefaces/primeng#10601]
Hi @cagataycivici, @yigitfindikli and team,

I couldn't find anywhere an email address to report security issues to, nor did I find any of your private email addresses.
Can you please contact me back - hagai.wechsler@whitesourcesoftware.com

Thanks,
Hagai

**Comment by yigitfindikli** [comment]
Hi,

You can use https://www.primetek.com.tr/#contact.
