### ISSUE TITLE
Class [NAME]Module is not an Angular module ERROR!

### ISSUE THREAD

**Issue by alessandrolopopolo** [primefaces/primeng#10605]
Hi guys I don't have a PrimeNG PRO Support subscription, but I try to configure the new version of primeng with angular 12.
I have multiple errors when I try to import all modules into @NgModule imports like this one in the figure
![report](https://user-images.githubusercontent.com/4832345/132708702-2ccec3e6-651c-4e61-b8f5-82e69a594609.png)

if i run the angular server when i view the page with one of the components listed above i get an error for example: 'p-toast' is not a known element :! I also understand why, the system does not see my imports for the first error I assume but how can I find a solution?

Help me please!
![Catturaerrore](https://user-images.githubusercontent.com/4832345/132710446-566c29be-9ad2-4ae5-a8c9-2894e0a90599.PNG)

**Comment by raychz** [comment]
I am also seeing 'p-*' is not a known element for just about every primeng component.

**Comment by alessandrolopopolo** [comment]
I solved the error, the problem was given by Intellij (old version) I updated to the latest and magically prime is recognized
