### ISSUE TITLE
Table frozen columns not working inside flexible view

### ISSUE THREAD

**Issue by jaredmartinez** [primefaces/primeng#10615]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Frozen columns do act correctly in a flexible viewport. Smaller viewports do not keep the column(s) frozen.

First example below is with a single frozen column (primeng example). 2nd is with multiple frozen columns.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/primeng-tablescroll-demo-4wkcxz
https://stackblitz.com/edit/primeng-tablescroll-demo-dtpcr6

* **Angular version:** 12.1
Latest

* **PrimeNG version:** 12.1
Latest

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by andreihaiducu** [comment]
I can confirm this is happening in v12.1.1 .
I also opened an issue and it was closed as "working on v12.1.0". 
Still not working.

**Comment by jean-mickael** [comment]
I have a similar problem with the frozen columns not working when the table is in a p-dialog.

An example below, the 2 first columns are marked as frozen. Correct behavior in the main window and in the dialog only the 2nd column is frozen:
https://stackblitz.com/edit/primeng-tablescroll-demo-m4u5tz?file=src/app/app.component.html

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
