### ISSUE TITLE
Year Picker

### ISSUE THREAD

**Issue by zarija-gavrilovic** [primefaces/primeng#10616]
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

It would be great if you could make "Year picker" same as month picker.
![image](https://user-images.githubusercontent.com/58690622/133152400-86b3c05e-d5b1-4e00-928c-18eac35074d6.png)

**Comment by Kavindu-Gayantha** [comment]
> [ ] bug report => Search github for a similar issue or PR before submitting [x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap [ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
> 
> It would be great if you could make "Year picker" same as month picker. ![image](https://user-images.githubusercontent.com/58690622/133152400-86b3c05e-d5b1-4e00-928c-18eac35074d6.png)

is this still not possible? I have tried but cannot get only a year picker. It has a month as well.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
