### ISSUE TITLE
RadioButton under Material Theme - styling issue when selected

### ISSUE THREAD

**Issue by jiangyh1024** [primefaces/primeng#10628]
Obviously, after being selected, the dot isn't centered.

I referred to other themes and changed its length and width to 12px or 50%. It looks better now.

**Comment by jiangyh1024** [comment]
Why can't I upload image????

**Comment by jiangyh1024** [comment]
https://stackblitz.com/edit/primeng-radiobutton-demo-pyucuk?file=angular.json

go to this link

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
