### ISSUE TITLE
Tree onNodeSelect method emits wrong value when the [filter]="true"

### ISSUE THREAD

**Issue by gbourant** [primefaces/primeng#10620]
When the tree is filtered and you click on a node the onNodeSelect method emits wrong value.

Tried in both 11.4.0 and 12 versions.

**Comment by marcioggs** [comment]
It's emitting the parent root node instead of the selected node.

**Comment by rdrrichards** [comment]
I am seeing this same behavior. Filtering the tree and selecting a node emits the root node of the none filtered tree.

**Comment by andchir** [comment]
Pay attention to this answer:
https://github.com/primefaces/primeng/issues/9909#issuecomment-782009041
This solves the problem for me.

**Comment by rdrrichards** [comment]
Yes! Including a key value in the TreeNode hierarchy solves this. Thanks @andchir for pointing this out.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
