### ISSUE TITLE
pDroppableDisabled not updated while dragging

### ISSUE THREAD

**Issue by flkeller** [primefaces/primeng#10622]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/primeng-organizationchart-demo-s9rqn4?

**Current behavior**
when updating the pDroppableDisabled value while dragging an item, the drop area does not get enabled/disabled

**Expected behavior**
updates to pDroppableDisabled should be reflected to drag and drop behaviour

**Minimal reproduction of the problem with instructions**
go to https://stackblitz.com/edit/primeng-organizationchart-demo-s9rqn4?

function dropDisabled() is bound to pDroppableDisabled attribute.

drag any item, drop should be enabled on all droppable areas

**What is the motivation / use case for changing the behavior?**
Add drag and drop support for organization chart, drop in a tree should not be allowed for all items

* **Angular version:** 11

* **PrimeNG version:** 11.4.5

**Comment by hlesterJha** [comment]
After looking at the source, the Input property is only evaluated in AfterViewInit. I implemented a work-around by duplicating the html and using Ngif to hardwire the boolean value. Although it seems to work it is not ideal. Ideally the Input property would be a setter and bind/unbind dynamically.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
