### ISSUE TITLE
Data table with checkbox in template - checked value resets

### ISSUE THREAD

**Issue by dahlp** [primefaces/primeng#1062]
When using a checkbox element in a data table template the check mark for the checkbox disappears when I add a new row to the data table from a button click outside of the data table. 

The {{row[col.field]}} shows the correct value, either true or false depending on the state of the checkbox before the new row was added.

Is this even possible or am I missing something that's causing this issue?

`<p-dataTable [value]="bids" (onEditInit)="onBidEditInit($event)" [editable]="true" 
                                            [rows]="10" [pageLinks]="5" [paginator]="true" [rowsPerPageOptions]="[5,10,20]" [responsive]="true" >`

`<p-column field="qa" header="QA" [style]="{'width':'145px'}">`
`<template let-row="rowData" let-index="rowIndex" let-col pTemplate type="body">`
`<input type="checkbox" id="qa{{index}}" name="qa" #qa="ngModel" [(ngModel)]="row[col.field]" /> {{row[col.field]}}`
`</template>`
`</p-column>`

Using: 
angular2 - 2.0.0
primeng - 1.0.0-beta.17

Thank you

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with them and if issue persists drop a comment and we'll reopen.

We'd welcome a test case based on plunkr below;

http://plnkr.co/edit/VZbdZfQ7SuTV87tTkbYR

**Comment by mukeshkamboj** [comment]
@cagataycivici What can be the solution if we cannot upgrade to latest version?
Please guide. Thanks in advance.
