### ISSUE TITLE
Modal layer enter-leave transition

### ISSUE THREAD

**Issue by yigitfindikli** [primefaces/primeng#10639]
Details;
https://github.com/primefaces/primevue/issues/1491

**Comment by JacobSiegle** [comment]
@yigitfindikli this is causing a bug where when I open the sidebar and click an item (which then I toggle [visible]) it does not close destroy the modal correctly. Reverted to 12.1.0, will try to make a stackblitz later today.

**Comment by dasco144** [comment]
I'm getting the same behaviour on the Ultima template.
It looks like the animationend listener on the modal mask never fires.
