### ISSUE TITLE
Dropdown and Calendar don't work properly in Reactive Form with updateOn = 'blur'

### ISSUE THREAD

**Issue by lrydzkowski** [primefaces/primeng#10636]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/angular-ivy-zs8aah

**Current behavior**

When I initialize FormGroup object with option updateOn = 'blur' then [Dropdown](https://www.primefaces.org/primeng/showcase/#/dropdown) and [Calendar](https://www.primefaces.org/primeng/showcase/#/calendar) input components:

- don't trigger valueChanges event on FormControl object,
- don't propagate values to FormControl object despite that new values are visible in interface.

It works well for other types of input components like [InputText](https://www.primefaces.org/primeng/showcase/#/inputtext), [Textarea](https://www.primefaces.org/primeng/showcase/#/inputtextarea), [InputNumber](https://www.primefaces.org/primeng/showcase/#/inputnumber), [InputSwitch](https://www.primefaces.org/primeng/showcase/#/inputswitch) and [MultiSelect](https://www.primefaces.org/primeng/showcase/#/multiselect).

**Expected behavior**

Changing values in Dropdown and Calendar input components should trigger valueChanges event and should propagate values to FormControl. In other words, changed values should be present in control.value, where control is FormControl type.

**Minimal reproduction of the problem with instructions**

You can see this bug on https://stackblitz.com/edit/angular-ivy-zs8aah. I've created simple Reactive Form with option updateOn: 'blur'. The form contains 3 fields:

- Calendar input component for indicating a date.
- Calendar input component for indicating date and hour.
- Dropdown for choosing one of available values.

To see the incorrect behavior, you have to carry out the following steps:

- Date field: indicate a date by clicking on the calendar button and choosing any date from the calendar window. This operation writes a chosen date into the field. However, it doesn't trigger valueChanges event.
- DateTime field: do the same operation as in the previous point.
- Dropdown field: chose any value and then clear value by clicking x icon in the field. The first operation triggers valueChanges event. However, the operation of clearing value doesn't do that.
- Click Confirm button. You will see that values in the object built from values of FormControl are different than values in fields in the interface.

Additional remarks connected with Calendar input component:

- You can notice that when you change a value by writing it directly in the field, everything works according to expectations.
- You can also observe that after the first value change, next changes trigger valueChanges event. However, in these next events there are old values instead of current values.
 
Everything works properly with updateOn = 'change', which is the default value of this option.

**What is the motivation / use case for changing the behavior?**

I would like to build forms with updateOn = 'blur'. It's convenient to be able to attach to valueChanges event in order to trigger additional functionality on changing fields values.

**Please tell us about your environment:**

* **Angular version:** 12.0.5

* **PrimeNG version:** 12.1.1

* **Browser:** I've tested it on Chrome 93.0.4577.82 (Official Build) (64-bit) and Firefox 92.0 (64-bit).

**Comment by chamgda** [comment]
I just ran into the same issue but it's more than just a convenience thing.
I have a reactive form with an asyncValidator and two p-calendars with time selectors. Every time I click one of the arrows to increase or decrease the time by one hour/one minute, the asyncValidator is executed.
So I thought to myself "hey, let's just change the update strategy of the two date controls to blur so the validation only triggers once when I'm done changing the date".
Sometimes it works as expected, most of the time it doesn't (meaning the form value simply doesn't update despite the display value having updated). The behaviour is very inconsistent or I just haven't recognised a pattern yet.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by DcsKristianDittmar** [comment]
Hi.

The issue with the p-calendar component still exists in PrimeNG 14.2.2. In our application p-calendar behaves the way that lrydzkowski described in his bug report. But for us this only happens if the date picker is displayed. Adding the time picker by setting `[showTime]="true"` does not change the behaviour. But if you set `[showTime]="true"` and `[timeOnly]="true"` in order to display only the time picker the value is updated as expected when the time picker closes.

Our application is written using Angular 14.2.10. We tested the issue on Firefox 106.0.5 and Chrome 107.0.5304.110, both 64 bit.

Best regards.

**Comment by mehmetcetin01140** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.
