### ISSUE TITLE
DataTable: Expression has changed after it was checked

### ISSUE THREAD

**Issue by dboldureanu** [primefaces/primeng#1064]
Running Angular 2, through angular-cli, in _development mode:_

error_handler.js:47 EXCEPTION: Error in ./EntriesComponent class EntriesComponent - inline template:0:0 caused by: _Expression has changed after it was checked._ Previous value: ...

On selection DataTable adds the **"_$visited": true** which fails the verification _"that no bindings have changed since the end of the first, as this would indicate that changes are being caused by change detection itself."_

Please check https://github.com/angular/angular/issues/6005#issuecomment-165905348 for more details

When using the _enableProdMode();_ the verfication and thus the exception, as noted in the reference, is not triggered.

**Comment by dboldureanu** [comment]
One thing that worked for me was to call ChangeDetectorRef.detectChanges() inside the onRowSelect.

<p-dataTable [value]="entries" ... (onRowSelect)="onRowSelect($event)">

constructor(private changeDetectorRef: ChangeDetectorRef) { }

onRowSelect(event) {
        this.changeDetectorRef.detectChanges();
}

**Comment by br87m** [comment]
Call **ChangeDetectorRef.detectChanges()** into **onRowSelect()** method worked for me!

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.

**Comment by jonzrj** [comment]
don't need to modify templates, just add the following method to component:
`
ngAfterViewChecked() {
    this.changeDetectorRef.detectChanges();
  }
` 
also work for me

**Comment by zkewal** [comment]
This is still not working for me. I am using version 4.1.0-rc.2

**Comment by zkewal** [comment]
This issue still persists. I am on version 4.1.0-rc.2

**Comment by Mrtcndkn** [comment]
How can I replicate the problem @zkewal

**Comment by Mrtcndkn** [comment]
Glad to hear that. @zkewal

**Comment by brusselseGiraf** [comment]
I actually got this bug by doing {{ selectedRow | json }}
