### ISSUE TITLE
Add additional parameters to the Timeline content template.

### ISSUE THREAD

**Issue by johnhwright** [primefaces/primeng#10658]
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Currently no parameters seem to be provided beyond the implicit message value. Similar to the table it's often necessary to have special checks for the first/last items.

**What is the motivation / use case for changing the behavior?**
At a minimum it would be nice if it included the `rowIndex` parameter like the table body does (e.g. `<ng-template pTemplate="content" let-message let-rowIndex="rowIndex">`). But first and last would also be welcome additions.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
