### ISSUE TITLE
Table - Editable columns - Cell Editing

### ISSUE THREAD

**Issue by eXpertise7** [primefaces/primeng#10655]
```
[x] feature request
```

Hello guys,

With Cell Editing user can go through between cells with left and arrow keys.

Is it possible to add some property where we could disable that particular behavior, because in some cases it would be nice to go through the selected text in the Cell Editor item, not go through each every items in the rows?

So in that case user would go to other cell editor item with mouse click only, not with the arrow keys.

This one is not so important, if it's too complicated but: user would use left and right arrow keys only to go through the text in the selected cell.

Other than that, Keep up the good work PrimeNG!

Kind regards,
Robert

**Comment by LucaVazz** [comment]
Probably related to #10519.

Either way it'd be a great addition to be able to disable/enable this behavior - often times it makes more sense to allow the user to change the cursor position with the arrow keys, sometime quickly jumping between more fields makes more sense.

**Comment by kniffo80** [comment]
I see no progress. Anyone found a solution for this? Some sort of a workaround?

**Comment by homerchap** [comment]
This would be nice because the arrow navigation is acting like a bug right now.

**Comment by homerchap** [comment]
I think I have figured out a workaround for it. On the input filed I add this,

(keydown.ArrowRight)="doNothing($event)"

Then in the component I add this function.

doNothing(e: any) {
e.stopPropagation();
return;
}

This is stopping the code in the primeng-table.js from running. You can add ArrowLeft or anything else you want as well.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by LucaVazz** [comment]
@mertsincan This feature request still exists as described. While the workaround posted by @homerchap works, a first-party option would be preffered.

Could you please re-open this issue for consideration by the team?

**Comment by cetincakiroglu** [comment]
Hi,

We've recently implemented accessibility and it's not possible to disable keyboard behaviors or override them and we do not have such functionality in our backlog.
