### ISSUE TITLE
extra functions to TreeTable and Tree

### ISSUE THREAD

**Issue by jisqaqov** [primefaces/primeng#1066]
Good day. Could you please add below functions to TreeTable and Tree:
- scrollable
- pagination
- checkbox column
- resize
  Thanks a lot!

**Comment by jisqaqov** [comment]
Please add checkbox selection.

**Comment by cyberrranger** [comment]
i miss

- filter
- sortable

**Comment by cagataycivici** [comment]
Please create separate feature requests for each so we can track them in their seperate tickets. By the way, resize and checkbox are available in latest releases.
