### ISSUE TITLE
Fullcalendar: missing styles

### ISSUE THREAD

**Issue by Timmeeeey** [primefaces/primeng#10662]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
Missing styles for `fc-dayGridWeek-button` class for fullcalendar.

**Please tell us about your environment:**

* **PrimeNG version:** 12.1.1

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by Timmeeeey** [comment]
@mertsincan 
Hi, it's still missing in PrimeNg 14.2.2.
The style should be the same as `fc-dayGridMonth-button` class.
I am not able to reopen this issue.

**Comment by iiKuzmychov** [comment]
the same problem
