### ISSUE TITLE
Menu | Submenu Tooltip Support

### ISSUE THREAD

**Issue by mahmoudshahin1111** [primefaces/primeng#10675]
**Current behavior**
tooltip doesn't work on menu items
https://primefaces.org/primeng/showcase/#/menu

**Expected behavior**

after I define `tooltipOptions` in the menu items list I should see the tooltip when hover on the menu item has this `tooltipOptions` defined

**Minimal reproduction of the problem with instructions**
I need to show some information about a menu item before 
using it like navigate to another page I need to display another info about this page 

**What is the motivation / use case for changing the behavior?**

PrimeNG version: 12.1.1 & 12.2.0-rc.1
Browser: Chrome Version 93.0.4577.82

**Comment by yigitfindikli** [comment]
https://github.com/primefaces/primeng/commit/64a3fcb1e86760fcff37532f9a3a07b90453aa4f
