### ISSUE TITLE
Add ability to change icon next to label in TreeSelect component

### ISSUE THREAD

**Issue by Snip3rSVK** [primefaces/primeng#10677]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**What is the motivation / use case for changing the behavior?**
I can change via TreeNode API icons in overlay but I can't currently change icon next to label in TreeSelect component.
It would be great to have feature like for example [dropdownIcon] in Dropdown component also in TreeSelect component.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by Nabeeh-AlSawaf** [comment]
i can find the dropdown icon in the normal dropdown but not in the `tree select` dropdown 
using primeng v14.2.2
