### ISSUE TITLE
Table - Fixed column width with scrollable table

### ISSUE THREAD

**Issue by kkovac1** [primefaces/primeng#10688]
Hello, I am facing a problem with using scrollable table. I want to set fixed column width on few columns (2 columns in my example). Let's say I have a column with checkboxes, I tried this (code bellow), but style is not applying. Any solution for this?
```
<th style="width: 3rem">
     <p-tableHeaderCheckbox></p-tableHeaderCheckbox>
</th>
```

Also I have tried using template colgroup, still style isn't applied:
```
<colgroup>
     <col *ngFor="let col of columns" [style.width]="col.width">
</colgroup>
```

**Comment by yigitfindikli** [comment]
You can use flex-basis.

`<th [style.flex-basis]="col.width" ...>`

**Comment by kkovac1** [comment]
Well seems to work, but still is variable width, depends on window size.
Found one more problem with this when using resizable columns too. When I resized any column and than resized window, this happened: 
![image](https://user-images.githubusercontent.com/75999845/135230621-d5311180-7797-42a9-9cc5-7a26eb4a23ea.png)
