### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by Rohit-Nair296** [primefaces/primeng#10680]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
I build the primng library locally using command **npm run build-lib** after the successful build I install the /dist in 
Demo project and implemented the ButtonModule to the project.

../../primeng/dist/fesm2015/primeng-checkbox.js:6:0-44 - Error: **Module not found: Error: Can't resolve 'primeng/utils' in '\primeng\dist\fesm2015'**

**Expected behavior**
Should be run without any problem, if i use command "npm install primeng --save" it runs perfectly
but locally build doesn't  work.

**Minimal reproduction of the problem with instructions**
component should run

**What is the motivation / use case for changing the behavior?**
by build the library locally the primng component should work

**Please tell us about your environment:**
Windows 10

* **Angular version:** 5.X
12.0.5

* **PrimeNG version:** 5.X
12.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Tested on Chrome beta (64-bit)
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All

* **Node (for AoT issues):** `node --version` =   
v14.15.4

**Comment by Rohit-Nair296** [comment]
The Error show below having some path issue.
![pError 2](https://user-images.githubusercontent.com/65599090/135067165-36183cb5-0154-4745-81bb-488b4a58a661.png)

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template or example github repo.
