### ISSUE TITLE
V12 - sidebar doesn't remove mask

### ISSUE THREAD

**Issue by jiangyh1024** [primefaces/primeng#10682]
```
  disableModality() {
        if (this.mask) {
            DomHandler.addClass(this.mask, 'p-component-overlay-leave');
            this.animationEndListener = this.destroyModal.bind(this);
            this.mask.addEventListener('animationend', this.animationEndListener);
        }
    }

    destroyModal() {
        this.unbindMaskClickListener();
        document.body.removeChild(this.mask);

        if (this.blockScroll) {
            DomHandler.removeClass(document.body, 'p-overflow-hidden');
        }

        this.unbindAnimationEndListener();
        this.mask = null;
    }
```

doesn't trigger destroyModal()

**Comment by vimalraj-a** [comment]
This is still not fixed. **Try using a capture true**. Since mark element is after the sidebar when we set `appendTo="body"` Its still not working

**Comment by AmazingDreams** [comment]
I have looked into this a little. It appears that the `animationEndListener` that's supposed to destroy the overlay is removed before the panel is entirely hidden. This is done through `unbindGlobalListeners` 

```
    onAnimationEnd(event) {
        switch (event.toState) {
            case 'void':
                this.hide(); // Binds `destroyModal` to the mask `animationend`
                ZIndexUtils.clear(this.container);
                this.unbindGlobalListeners(); // Removes `destroyModal` from the mask immediately
                break;
        }
    }
```

A possible solution is to simply move the `hide` to after the `unbindGlobalListeners`.

**Comment by jiangyh1024** [comment]
seems fixed, when to release a new version

**Comment by jiangyh1024** [comment]
try what I did in #10715, I think it could fix this issue as a makeshift.

**Comment by KeithGillette** [comment]
Thanks for the suggestion, @jiangyh1024. I have added a `ViewChild(Sidebar)` and tried to call `hide()` on it manually prior to setting the `[(visible)]` binding to `false`  in our component controller per your recommended work-around, but the mask still remains after the sidebar closes.

I do not think that this issue should be closed.

**Comment by jiangyh1024** [comment]
Thx, that would be helpful

**Comment by ccit-spence** [comment]
Why is this closed if it is still broken? I have the problem with 12.2.2

**Comment by lufo88ita** [comment]
Still present in latest 12.x version. Please fix.

**Comment by markusvorraber** [comment]
Also still present for me with 12.2.2

**Comment by olaisen81** [comment]
Confirm, still presenti in 12.2.2

**Comment by akmal2409** [comment]
Still present in 13 RC2

**Comment by mmulligan5c** [comment]
Is this still present in 13.0.2?

**Comment by marcovmun** [comment]
I can confirm it still present in 13.0.2

**Comment by dev-thinks** [comment]
issue exists in v13 as well but why this is closed here.

**Comment by apunekar** [comment]
Issue still exists. Using 13.0.3. But thanks to @KeithGillette work around, else I was dead.

**Comment by francowhyline** [comment]
Issue still exists, I think that is a problem when I am paying for this project and you people don't event give an answer.
I am using the last version of angular and the last version of primeng and this is not working well. I don't want to use any workaround, this should be fixed by you in the core of the components.

**Comment by ddurham2** [comment]
happens for me in v13 as well

**Comment by QuickScoP3s** [comment]
For the people having this issue in V13, check the comment I put on my bug ticket: https://github.com/primefaces/primeng/issues/11587#issuecomment-1146774882

Make sure to check your theme css file

**Comment by Jagan-P** [comment]
> For the people having this issue in V13, check the comment I put on my bug ticket: [#11587 (comment)](https://github.com/primefaces/primeng/issues/11587#issuecomment-1146774882)
> 
> Make sure to check your theme css file

@QuickScoP3s the css solution that you gave only changes the background color and does not remove the overlay DOM?

**Comment by Jagan-P** [comment]
Yes. This solves the issue! Thanks!

**Comment by karlatt** [comment]
> For the people having this issue in V13, check the comment I put on my bug ticket: [#11587 (comment)](https://github.com/primefaces/primeng/issues/11587#issuecomment-1146774882)
> 
> Make sure to check your theme css file

To be fair and give back to Cesar ... , your comment is just a character for character quote of @smarrerof  fix , which you can find at the beginning of this thread ;)

**Comment by QuickScoP3s** [comment]
Oh woops, totally overlooked that comment. Well, all credits to @smarrerof :P

**Comment by flier268** [comment]
I found [this](https://forum.primefaces.org/viewtopic.php?t=60072)
```html
<p-sidebar ... [modal]="false">
</p-sidebar>
```
