### ISSUE TITLE
Upload progress bar extending past control

### ISSUE THREAD

**Issue by DavidRCulpJr** [primefaces/primeng#1068]
I have the upload control in an Overlay Panel and on upload the progress bar will (at times) extend past the area of the control and continue across the screen.

Similar behavior is seen with the upload control in a dialog -- with the exception of the bar staying within the dialog box (but not the upload control).

![upload progress bar](https://cloud.githubusercontent.com/assets/22840488/19392012/9227465a-91f4-11e6-9218-3d60e40f7446.png)

**Comment by cagataycivici** [comment]
I'm unable to replicate, any help is appreciated.

**Comment by DavidRCulpJr** [comment]
This is the template of the upload button (top-left of previous image)

![image](https://cloud.githubusercontent.com/assets/22840488/19574256/14e9d4d4-96cf-11e6-9be7-72eea89ae57b.png)

the component TypeScript is just a simple

**Comment by DavidRCulpJr** [comment]
As an additional note.  The length of the bar seems to be related to the time to upload -- not the size of the file being uploaded.  The screen shot in the first message was taken while running on a system that runs a on the slow side.

**Comment by cagataycivici** [comment]
Provide a plunkr please and we'll reopen after review.

**Comment by DavidRCulpJr** [comment]
Sorry, I am no longer working for that company or with PrimeNg.  If others are not seeing the issue closure is probably best.
David
Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Çağatay Çivici <notifications@github.com> Date: 6/6/17  9:11 AM  (GMT-05:00) To: primefaces/primeng <primeng@noreply.github.com> Cc: DavidRCulpJr <david.r.culp.jr@gmail.com>, Author <author@noreply.github.com> Subject: Re: [primefaces/primeng] Upload progress bar extending past control (#1068) 
Provide a plunkr please and we'll reopen after review.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/primefaces/primeng","title":"primefaces/primeng","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/primefaces/primeng"}},"updates":{"snippets":[{"icon":"PERSON","message":"@cagataycivici in #1068: Provide a plunkr please and we'll reopen after review."}],"action":{"name":"View Issue","url":"https://github.com/primefaces/primeng/issues/1068#issuecomment-306481498"}}}
