### ISSUE TITLE
migration guide wiki incorrect

### ISSUE THREAD

**Issue by gurnard** [primefaces/primeng#10681]
Looking at the primeng migration guide here:
https://github.com/primefaces/primeng/wiki/Migration-Guide

It states that versions 7 and 8 are direct drop ins from 6.  I just upgraded from 6 to 8 and I see that filterConstraints has been removed from the table. This should be added to the migration guide and state how to migrate it please.

For more information see this post.
https://stackoverflow.com/questions/49551003/filtering-turbotable-by-dates

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
