### ISSUE TITLE
Sidebar is shown on Dynamic Dialog

### ISSUE THREAD

**Issue by rezaokhravi** [primefaces/primeng#10684]
hi
Sidebar is shown on Dynamic Dialog 
example below:

![zindex](https://user-images.githubusercontent.com/42868109/135076827-81df7fc3-02c2-4589-8018-3c28a1ca89b1.png)

* **Angular version:** 12.X

* **PrimeNG version:** 12.X

**Comment by yigitfindikli** [comment]
Fixed in v13.
