### ISSUE TITLE
migration guide wiki - datascroller

### ISSUE THREAD

**Issue by gurnard** [primefaces/primeng#10686]
The migration Wiki here:

https://github.com/primefaces/primeng/wiki/Migration-Guide#1000

mentions nothing of the DataScroller being replaced with the VirtualScroller.  It needs to be added.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
