### ISSUE TITLE
pTable pReorderableColumn conflicts with pDroppable directive

### ISSUE THREAD

**Issue by silviagreen** [primefaces/primeng#10691]
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
pTable has reordable columns. In addition, I am trying to implement this behavior: drag a column of the table and drop it into a dedicated area, in order to remove it from the table.
The drop event is not triggered.

If the directive pReorderableColumn is removed, the drop of the column in the area works and the colums gets removed.

**Expected behavior**
I should be able to reoder column using drag and drop and also to remove columns using the pDroppable/pDraggable directives.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/primeng-tablereorder-demo-p7ikar?file=src/app/app.component.html
(please, open in dedicated tab in order to test the described behavior)

1) drag a column name into the area over the table

* **Environment**: Windows, Apache (Xamp)
* **Angular version:** 12.1.1
* **PrimeNG version:** 12.1.0
* **Browser:** all
* **Language:** all

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
