### ISSUE TITLE
p-multiselect: Performance issue when selecting all items (10000 records or more) 

### ISSUE THREAD

**Issue by ManojKChowdhury** [primefaces/primeng#10695]
In scenarios when there are huge numbers of records in the multiselect dropdown, activating virtual scroll enables smooth open-close of the dropdown. But upon clicking the select-all checkbox:

It takes around 13-14 seconds for the checkbox to be shown as selected and the dropdown to be usable again.
The page becomes unusable during this duration.
Closing the dropdown now and re-opening it with all items selected also takes a lot of time.
De-selecting all items by clicking on the checkbox again takes considerable time.

**Comment by TUSHAR4541** [comment]
Yes for me as well, Select all/Unselect all takes a lot of time. Here is a sample with 4000 records only https://stackblitz.com/edit/primeng-multiselect-demo-sghybu

Even with _virtualScroll_ option this fails.

**Comment by mertsincan** [comment]
Similar to https://github.com/primefaces/primereact/issues/2098. I think these options can be added to PrimeNG MultiSelect component. Demo;
https://www.primefaces.org/primereact/multiselect/ (VirtualScroller demo)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
