### ISSUE TITLE
Cell selection for datatable

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#107]

**Comment by TekSiDoT** [comment]
Perhaps attempt to unify it with editable cells:
in case a cell is both selectable and editable, 
* edit when the inner text box is hit
* select the cell when the space margins are hit
* edit the cell when a selected cell is selected again

**Comment by cagataycivici** [comment]
Issue tracker cleanup, moved to roadmap. Will reopen when it is picked up from our todo list.

https://github.com/primefaces/primeng/wiki/Roadmap
