### ISSUE TITLE
Allow for ColumnFilter-matchmode updates

### ISSUE THREAD

**Issue by ThomasPrikrylBE** [primefaces/primeng#10709]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
The match mode of a ColumnFilter seems to be a "default" and seems to not be changeable after setting it initially - from outside. I guess, because it only happens in the onInit part [here](https://github.com/primefaces/primeng/blob/56075a242c3ceb5c1a6b7a14e208d5eaef4afe0e/src/app/components/table/table.ts#L4395)

I found `onRowMatchModeChange` but since I didn't find that in the documentation, I wasn't sure if it might be replaced in a later update without knowing about it and therefore, I didn't want to rely on it.

**Expected behavior**
It would be cool to have a way to update this from outside - either via `[matchmode]` itself or a setter.

**What is the motivation / use case for changing the behavior?**
I have a table that I want to be able to filter by a date and wanted to introduce a dropdown within the header template of a datepicker overlay, that let's you select if the entries need to be before or after this date, without having to use the default ColumnFilter way, where you need the menu button (that has the match mode dropdown) AND the datepicker overlay. So I basically wanted to pull that dropdown functionality into the datepicker overlay. But then I encountered the problem, that the match mode didn't get updated.

* **Angular version:** 12.X

* **PrimeNG version:** 12.X

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
