### ISSUE TITLE
PickList in modal, dragged element goes behind

### ISSUE THREAD

**Issue by LouLeGrain** [primefaces/primeng#10703]
**I'm submitting a ...** 
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-aoh1dw?file=src/app/custom-dialog/custom-dialog.component.html

![2021-10-05 13 50 52](https://user-images.githubusercontent.com/9808953/136017786-38cb66da-b6fb-45a8-bf97-e11480c77c70.gif)

**Current behavior**
With a PickList component in a (dynamic)modal, when drag&dropping an item, the item goes behind the modal when dragged

**Expected behavior**
The dragged item stays on top of the modal

**Minimal reproduction of the problem with instructions**
See stackblitz & gif above.

**Please tell us about your environment:**
```json
"dependencies": {
    "@angular/animations": "~12.2.1",
    "@angular/cdk": "^12.2.3",
    "@angular/common": "~12.2.1",
    "@angular/compiler": "~12.2.1",
    "@angular/core": "~12.2.1",
    "@angular/forms": "~12.2.1",
    "@angular/platform-browser": "~12.2.1",
    "@angular/platform-browser-dynamic": "~12.2.1",
    "@angular/router": "~12.2.1",
    "@angular/service-worker": "~12.2.1",
    "@ngx-translate/core": "^13.0.0",
    "@types/file-saver": "^2.0.1",
    "angular-gridster2": "^11.0.1",
    "angular-oauth2-oidc": "^10.0.3",
    "chart.js": "^2.9.4",
    "file-saver-es": "^2.0.5",
    "ng-sidebar": "^9.4.2",
    "primeflex": "^2.0.0",
    "primeicons": "^4.1.0",
    "primeng": "^11.4.5",
    "rxjs": "~6.6.0",
    "tslib": "^2.3.1",
    "uikit": "^3.7.2",
    "xlsx": "^0.17.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^12.2.1",
    "@angular/cli": "12.2.1",
    "@angular/compiler-cli": "12.2.1",
    "@angular/language-service": "12.2.1",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "postcss": "^8.3.6",
    "typescript": "^4.3.5"
  }
```

* **Angular version:** 12.2.5

* **PrimeNG version:** 11.4.5

* **Browser:**
Chrome 94.0.4606.61
Safari  15.0 (15612.1.29.41.4, 15612)
Firefox 92.0b9 

 
* **Language:**
typescript : 4.3.5

* **Node (for AoT issues):** `node --version` =   
v14.15.4

**Comment by obarazan** [comment]
I have this issue too @LouLeGrain did you manage to WA it?

**Comment by nw-onediscovery** [comment]
Workaround style (set the z-index to whatever as long as it's higher than the dialog): 
```
::ng-deep .cdk-drag-preview {
  z-index: 9000 !important;
}
```

**Comment by critchie** [comment]
@mertsincan This is still happening in version 16.0.2. Feel free to reopen this issue.
