### ISSUE TITLE
Storybook to play with config properties reactively

### ISSUE THREAD

**Issue by juri-sinitson** [primefaces/primeng#10700]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
It's not possible to play with different config properties of e.g. Button, Badge, Knob, Dynamic Dialog reactively using UI-controls (toggles, increasers/decreasers, texboxes).

**Expected behavior**
UI-Elements of Prime(NG) are put to the storybook.
See examples of reactive UI control of UI elements on:
https://bbc.github.io/psammead/?path=/story/components-bulletin--tv-bulletin
https://5ccbc373887ca40020446347-geedzbiswp.chromatic.com/?path=/story/button--basic
https://5ccbc373887ca40020446347-geedzbiswp.chromatic.com/?path=/story/badge

See even more examples on https://storybook.js.org/docs/react/get-started/examples

**What is the motivation / use case for changing the behavior?**
Playing with properties  of UI-elements reactively saves time and communication. 

Real life example: a PO or a graphic designer with a very few development knowledge want to find out the optimal combination of properties of a Button/Badge or a Knob.
Currently they have to ask a frontend developer to 
1. Add Button/Badge or a Knob to a local Storybook story
1. As the case may be also to play around with the properties for them and/or give a control via e.g. MS Teams

With storybook a PO or a graphic designer can play with different properties e.g. of a Button/Badge or a Knob her/himself reactively on the documentation page of Prime(NG).

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
