### ISSUE TITLE
primeng-dynamicdialog Focus not getting returned to triggered element. 

### ISSUE THREAD

**Issue by sauravagnihotri94** [primefaces/primeng#10707]
primeng-dynamicdialog Focus not getting returned to triggered element.  It is focused at the start of the page

**Current behavior**
primeng-dynamicdialog Focus not getting returned to triggered element after closing.  It is focused at the start of the page

**Expected behavior**
It should return focus to triggered element after closing

**Minimal reproduction of the problem with instructions**
Go to stackblitz link of prime ng
https://stackblitz.com/edit/primeng-dynamicdialog-demo?file=src%2Fapp%2Fapp.component.html
add below code in html
<button > myButton </button>
<button > myButton 2 </button>

open modal, close modal , use tab to get the focus . focus will be on first button

Prime ng 11,  angular 12, node 12

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
