### ISSUE TITLE
Listbox enable/disable all when filtered does it on all

### ISSUE THREAD

**Issue by JhosenVinaNoa** [primefaces/primeng#10710]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already 
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Stackblitz example**
https://primeng-listbox-demo-khsbeq.stackblitz.io/

**Current behavior**
When it has been filtered and you use the check all, the operation is done on all the elements of the list instead of the filtered ones.

**Expected behavior**
When it's been filtered and you use the check all, it should only check or uncheck the filtered items, not all. Keeping the rest of the list unchanged.
This is very useful in long lists where we want to add or remove a subset to the selection.

**Minimal reproduction of the problem with instructions**
In the example do this steps:
1. Check France, Germany and Spain.
2. Filter by "Bra" and check all using then checkbox to check all.
3. Delete filter "Bra" and now you will see the countries of step1 unchecked.

**What is the motivation / use case for changing the behavior?**
In lists with many elements and wanting to mark or unmark in bulk is very useful.

* **Angular version:** 11.0.9 / 12.0.5
* **PrimeNG version:** 11.4.6  LTS / 12.1.0-rc.2
*

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
