### ISSUE TITLE
Listbox Group Template Doesn't Support Adding a Checkbox

### ISSUE THREAD

**Issue by grothem** [primefaces/primeng#10714]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-listbox-demo-wtm4xf?file=src/app/app.component.html

**Current behavior**
If you add a custom template for the list box group that includes a p-checkbox component, the list box items overflow the page and it become scrollable. Additionally, when I check one of the group check boxes, it's causing the page to scroll to the bottom.

**Expected behavior**
Adding the checkbox to the template shouldn't impact the overflow of the page and cause scrolling on selection.

**Minimal reproduction of the problem with instructions**
In the stackblitz link above, if you scroll down to the last group in the list box (Japan) and select the checkbox, notice the page scrolling to the bottom. Even without selecting the checkbox, you can see that the page allows scrolling because it's accounting for the list box items. If you remove the p-checkbox component from the group template, the issue goes away.

**What is the motivation / use case for changing the behavior?**
I want to add a checkbox to the group template to allow users to select all items within a particular group.

**Please tell us about your environment:**
MacOS, VSCode

* **Angular version:** 5.X
12.2.0

* **PrimeNG version:** 5.X
12.1.0

* **Browser:**
Chrome and Edge
 
* **Language:**
TypeScript 4.3.5

**Comment by eXpertise7** [comment]
@yigitfindikli can we get some feedback regarding this report?

@grothem

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
