### ISSUE TITLE
Sidebar - disableModality function isn't working in 12.2.0

### ISSUE THREAD

**Issue by dloprodu** [primefaces/primeng#10715]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
In the version 12.2.0 the modal state isn't removed even when the sidebar is hiden. In previous version, like 12.1.0, the function disableModality works fine.

**Expected behavior**

When the sidebar is close, the modal state should disappears.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 12.2.0

* **PrimeNG version:** 12.2.0

* **Browser:** [Chrome]

 
* **Language:** [TypeScript]

* **Node (for AoT issues):** `node --version` =

**Comment by dloprodu** [comment]
Hi @yigitfindikli , I don't call disableModality manually, I use the sidebar normally, only that debuggin the component I detected tht the problem was in that function and that destroyModal isn't being executed.

**Comment by jiangyh1024** [comment]
yes, that was reported by me
