### ISSUE TITLE
Is it possible to make all cells editable at once using PrimeNG with Angular 8 ?

### ISSUE THREAD

**Issue by rahul2810** [primefaces/primeng#10711]
Hi All,

I have a screen where I have an Edit button below which I have a PrimeNg table. My requirement is that when user clicks on Edit button, all the cells in the below grid should become editable(all rows and columns) at the same time.

I read through the PrimeNG documentation and did not find any support for this. There was only mention of single cell and single row edit. 

Can you please confirm if my requirement will be achievable through primeNG ?

Thanks in advance!

**Comment by morabeeh** [comment]
> Hi All,
> 
> I have a screen where I have an Edit button below which I have a PrimeNg table. My requirement is that when user clicks on Edit button, all the cells in the below grid should become editable(all rows and columns) at the same time.
> 
> I read through the PrimeNG documentation and did not find any support for this. There was only mention of single cell and single row edit.
> 
> Can you please confirm if my requirement will be achievable through primeNG ?
> 
> Thanks in advance!

Hi Rahul,
I too have the same requirement to implement, did you find any solution towards it? It will be really helpful if you share the code,
Thanks in advance,
Mohammed Rabeeh
