### ISSUE TITLE
Components are not Showing while building the primeng locally

### ISSUE THREAD

**Issue by Rohit-Nair296** [primefaces/primeng#10723]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
hii,

I have downloaded the latest primeng(v12) library from https://github.com/primefaces/primeng. I am using the primeng component and also wanted to add some components also. so, I build the library the locally by using
npm run build-lib you will find the command in libraries package.json file.
Build was success, then in used the dist folder that was created to install in my demo project
npm i "..path\primeng\dist" for installing. **install was also success**. But while implementing the component like button or multselect it gives error :

Error: ../../primeng/dist/button/button.d.ts:4:21 - error TS2307: Cannot find module 'primeng/ripple' or its corresponding type declarations.
4 import * as i2 from "primeng/ripple";

Error: ../../primeng/dist/multiselect/multiselect.d.ts:3:62 - error TS2307: Cannot find module 'primeng/api' or its corresponding type declarations.
3 import { FilterService, PrimeNGConfig, OverlayService } from 'primeng/api';

the error occurs for all the component that I uses.
![PError 3 ](https://user-images.githubusercontent.com/65599090/136545837-f10cc64f-0757-4378-a7b7-24e23fef50c2.png)

**Expected behavior**
I believe that if I build the primeng library locally like in the image bellow image it should work and I can also able to add new feature components, **The build was success**

![PError 4 ](https://user-images.githubusercontent.com/65599090/136544069-f406be41-f941-438d-a204-e238564b3663.png)

**What is the motivation / use case for changing the behavior?**
primeng is the best Component library, With the help of primeng components I want to customize and add more new components which are require in my projects
which I can handle it locally by converting it my own library. 

**Please tell us about your environment:**

* **Angular version:** 12

* **PrimeNG version:** 12

any other info needed let me know

Please if anyone can help me out will be great
Thanks

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.
