### ISSUE TITLE
The equals method in DomHandler return false when object contain an object property

### ISSUE THREAD

**Issue by loic49** [primefaces/primeng#1073]
When I compare the same object with equal method in DomHandler :

`this.equals({id:-1, code:'test', num: { id:1, nom:'test'}}, {id:-1, code:'test', num: { id:1, nom:'test'}} )`

It return always false.

The problem is on line 303 in domhandler.ts :

`if (obj1._$visited || !this.equals(obj1[p], obj2[p])) return false;`

I think it should be :

`if (obj1[p]._$visited || !this.equals(obj1[p], obj2[p])) return false;`

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with them and if issue persists drop a comment and we'll reopen.
