### ISSUE TITLE
Custom button to hide p-columnFilter

### ISSUE THREAD

**Issue by DucThuy2000** [primefaces/primeng#10732]
**Reason**
I'm working on a project, the client wants us to use p-columnFilter to filter data but your framework doesnt support yet in my case.

**My Case**
I have to adjust the clear and apply buttons to suit the client's wishes but when I clear or apply the overlayVisible stays true

**My Wish**
Can you add another @Input to ColumnFilter component so that when i click in my custom button, the overlayVisible property will be false, please...

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
