### ISSUE TITLE
Date component shows the Date (choo

### ISSUE THREAD

**Issue by Staticyassine** [primefaces/primeng#10740]
Hello, i want to share this issue for rectification ro clarification.
When selecting a date on the component the form controler receives it but minus 1 day. For instance when i choose the date 2020-02-01 the form conrtroller receives 2020-01-31.
it think its just an issue in the function that formats the date it has to be (day date) +1
Best regards

**Comment by yigitfindikli** [comment]
Issue is not clear, please feel free to reopen with a stackblitz example.
