### ISSUE TITLE
Z Index issue with TabPanel and MenuBar

### ISSUE THREAD

**Issue by davisb10** [primefaces/primeng#10744]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When a menu is opened over a TabView and TabPanel the 'X' from the TabPanel shows over the Menu

![image](https://user-images.githubusercontent.com/11411180/137484722-62d17453-3c67-42b9-b42f-94c616360be5.png)

**Comment by waratah** [comment]
I had a similar issue with megamenu and I had to override the style with:

```
body .p-megamenu-panel {
  z-index: 2;
}
```

I presume removing the 'mega' part (ie  .p-menu-panel)  will work around this issue.  worth a try.

**Comment by HassanNiazi** [comment]
Have the same issue when using the p-menu in the table, Is fixed using the z-index.
![image](https://user-images.githubusercontent.com/9024288/147365274-8c0f422e-ab39-49ba-bc22-7bfc97daa614.png)

**Comment by cetincakiroglu** [comment]
Hi,

Here is the working version of your example https://stackblitz.com/edit/primeng-tabmenu-demo-rzwm4m?file=src%2Fapp%2Fapp.component.html

We couldn't replicate the issue with the latest PrimeNG release, if the issue still exists with the latest PrimeNG version, please provide a StackBlitz example by using [PrimeNG Issue Template ](https://stackblitz.com/github/primefaces/primeng-issue-template) and re-open the issue.

Regards

**Comment by davisb10** [comment]
@cetincakiroglu This stackblitz shows it as still being an issue  https://stackblitz.com/edit/primeng-tabmenu-demo-stspjk

You may have to extend the preview wide enough to get it to fill out the menu instead of it being condensed. It doesn't happen on the condensed, but happens on the expanded view.
