### ISSUE TITLE
Add onCellClick to DataTable

### ISSUE THREAD

**Issue by pso-aeb** [primefaces/primeng#1074]
Similar to `onRowClick()`, add `onCellClick()` for cells in a specific column of DataTable.
So something like:

```
<p-column ... (onCellClick)="cellClicked($event)" >
```

Our current workarounds:
- Fill the cell with a `<div>` and assign a Angular2-(click). Works only for "normal" cells, not special cells like selection-cell or expand-cell.
- Use onRowClick() and check if the passed `event.originalEvent.target` is the desired cell. Of course this leads to a lot of undesirable code (especially CSS-classes in code).

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.

**Comment by taurus227** [comment]
You closed the issue before p-table was actually released. And didn't even explain how to actually do this with p-table.
