### ISSUE TITLE
table state is not working

### ISSUE THREAD

**Issue by CodeOutput** [primefaces/primeng#10748]
i use latest versiyon angular and primeng version; 12.X

stateStorage="**local**" stateKey="statedemo-local" OR stateStorage="**session**" stateKey="statedemo-session"

First of all, I want to pull this **stateKey**, **stateStorage** (local and session) setting from the service and print it.
but stateStorage does not support **none** tag.
stateStorage = session|local|**none** 
if i use none: ===>>Error: none is not a valid value for the state storage, supported values are "local" and "session".

**if your model is like this it works.**

` <input pInputText type="text" (input)="dt1.filter($event.target.value, 'name', 'contains')" [value]="dt1.filters['name']?.value" placeholder="Search by Name" class="p-column-filter">`

**my model is like this**
```
            <input pInputText type="text" [(ngModel)]="search.soyad"  placeholder="Soyad'a göre ara..."
                   (keyup.enter)="load(null)"
                   class="p-column-filter w-100 p-inputtext-sm">
```
if possible i have such models
  **[state]='true'** store this in local or session
```
            <input pInputText type="text" [(ngModel)]="search.soyad"  placeholder="Soyad'a göre ara..."
                   (keyup.enter)="load(null)"  **[state]='true'**
                   class="p-column-filter w-100 p-inputtext-sm">
```

I tried a different method. but that didn't work either... This method didn't even save when I entered data and refreshed the page.

            **<p-columnFilter type="text"
                            field="search.kullaniciAdi"
                            [showMenu]="true"
                            placeholder="Kullanıcı Adı'na göre ara..."></p-columnFilter>**

thanks you very much..

@cagataycivici @yigitfindikli

**Comment by yigitfindikli** [comment]
Issue is not clear, please feel free to reopen with a stackblitz example
