### ISSUE TITLE
InputNumber currency local problem

### ISSUE THREAD

**Issue by ProfEibe** [primefaces/primeng#10754]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

There is an issue with the p-inputnumber currency localization.
Using the currency "EUR" and locale "de-DE" everything works fine. But when I change the locale to "de-AT" for Austria, I can't input more than 4 digits

I have created an example stackblitz where you can see and test it:
https://stackblitz.com/edit/primeng-inputnumber-demo-eaone5?file=src/app/app.component.html

**Comment by ProfEibe** [comment]
Anything new here?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by ray-kay** [comment]
We have the exact same issue on PrimeNG 14.2.17-lts 
Would there be a fix available for PrimeNG 14 as it is a LTS Version?
