### ISSUE TITLE
p-treetable: gets error on node expand when virtual scroll for lazy load was handled programatically-> zone-evergreen.js:171 Uncaught TypeError: Cannot read properties of undefined (reading 'getDataLength')

### ISSUE THREAD

**Issue by chaitrashenoy33** [primefaces/primeng#10758]
I added virtual scroll programtically by setting  this.treeTable.virtualScroll = true/this.treeTable.virtualScroll = false where ever required(on node expand and on scroll for lazy loading second level data in p-treetable). But when i expand the node i get below error.

Uncaught TypeError: Cannot read properties of undefined (reading 'getDataLength')
    at TTScrollableView.hasVerticalOverflow (primeng-treetable.js:2010)
    at TTScrollableView.alignScrollBar (primeng-treetable.js:2016)
    at primeng-treetable.js:1881
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Zone.runTask (zone-evergreen.js:167)
    at invokeTask (zone-evergreen.js:480)
    at ZoneTask.invoke (zone-evergreen.js:469)
    at timer (zone-evergreen.js:2552)

Current behavior
lazy loading is happening for parent node(ie first level) and on node expand i was able to load second level data..but on console i do get the error

Expected behavior
on node expand the error should not populate in the console 

Please tell us about your environment:
Windows 10

Angular version:
Angular 11

PrimeNG version:
Primeng 9

Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

Language: [all | TypeScript X.X | ES6/7 | ES5]

Node (for AoT issues): node --version = 12.18

**Comment by yigitfindikli** [comment]
Unable to replicate with latest PrimeNG, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
