### ISSUE TITLE
Spelling and Grammar Fixes In Table Docs

### ISSUE THREAD

**Issue by jermylucas** [primefaces/primeng#10756]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

I would like to submit a bug report/improvement for the Table Documentation. This is one of the most commonly used components as I have seen, and there are some misspellings in the documentation. As I was reading over the docs, I thought I would improve some items as I came across.

**Comment by yigitfindikli** [comment]
Hi,

Merged. Thank you.
