### ISSUE TITLE
Primeng Table: Fix row hover and row selection highlight with row groups

### ISSUE THREAD

**Issue by pkpalanisamy** [primefaces/primeng#10752]
I am using the prime-ng version 11.2.0  and unable to highlight all the rows with row group when mouse over.
 
**Current behavior**

Create DataTable with [rowStyleClass]="rowStyle" and [rowHover]="true". Hover will be applied only on one tr tag.
datatable_rowspan_hover1
datatable_rowspan_hover2
![image](https://user-images.githubusercontent.com/42053845/138056646-d28b20bf-fb6f-4699-9ae6-863716176dc5.png)

![image](https://user-images.githubusercontent.com/42053845/138056834-82eaf298-82bb-4a33-a6c8-c059916acba7.png)

**Expected behavior**

Hover should apply on whole visible row, like this:
default
![image](https://user-images.githubusercontent.com/42053845/138056737-678f576a-7c6c-4bdb-8175-84b8d2a98c4d.png)

I have gone through the related bug but no fix in that.
https://github.com/primefaces/primeng/issues/3184

Please help me ti fix this issue.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
