### ISSUE TITLE
Tree drag and drop doesn't work with virtual-scroll

### ISSUE THREAD

**Issue by bhdr1** [primefaces/primeng#10759]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

**I will add stackblitz link.**

**Current behavior**
Drag and drop doesn't work when virtual-scroll is enabled. When I move the element it still appears in the old position. 

**Expected behavior**
Drag and drop should work when virtual-scroll is enabled

* **Angular version:** 
* 9.2.4
* **PrimeNG version:** 
* 9.1.0

**Comment by vagaganova** [comment]
internal drag index calculate wrong, so in processTreeDrop splice function  does not work

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
