### ISSUE TITLE
Slider handle can be dragged over the right edge with min/max boundaries

### ISSUE THREAD

**Issue by JanST123** [primefaces/primeng#10760]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-viiljn?file=src/app/app.component.html

**Current behavior**
With having a min boundary != 0 and a max boundary != 100 you are able to drag the handle over the right edge of the slider bar (horizontal mode)

**Expected behavior**
The slider handle should stop at the right edge, even if you drag it further.

**Minimal reproduction of the problem with instructions**
Use a slider with min=10 and max=80, drag over the right edge

**What is the motivation / use case for changing the behavior?**
Looks ugly

* **Angular version** 11.1.X

* **PrimeNG version:** 11.X

* **Browser:** all

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
