### ISSUE TITLE
While selecting month/year from the dropdown of p-calendar through keyboard navigation, the focus goes out from the dropdown 

### ISSUE THREAD

**Issue by abdulsoif** [primefaces/primeng#10765]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
This is the link of stackblitz. I am referring the Navigators calendar where there is month/year dropdown

https://stackblitz.com/edit/primeng-calendar-demo

**Current behavior**
When we open the navigators calendar and go to month dropdown and press spacebar to open the dropdown, then go to a month and select it by pressing enter, the month is selected but the focus goes away from the month dropdown. And pressing TAB the focus goes to the "<" button, instead of moving to the year dropdown.

**Expected behavior**
After selecting the month through keyboard navigation, the focus should remain there and not go away

**Minimal reproduction of the problem with instructions**

* **Angular version:** 
11.2.9

* **PrimeNG version:** 
Version 11.4.7 lts  (it is reproducible in higher version as well)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
