### ISSUE TITLE
Regression in 12.1.0 on scrollable p-table with colspan/rowspan (part 2)

### ISSUE THREAD

**Issue by marob** [primefaces/primeng#10776]
Issue https://github.com/primefaces/primeng/issues/10541 having been closed for 2 month while still not fixed, I'm opening a new issue.

There can still be some UI problem about columns alignment between thead and tbody of the table when content size mismatches.
See https://stackblitz.com/edit/primeng-tablecolgroup-demo-gdmbrj?file=src%2Fapp%2Fapp.component.ts: clicking on the checkbox enables scrollable mode and breaks the table.
In my project's use case, I was using CSS `width` on columns to manage the size of the different columns of my table. With table-row/table-cell display (12.0.2), it was working, but as the tbody is now (12.1.0) using flex display in scrollable mode, it's not "synced" with the thead anymore.

I've also added colspan/rowspan in the tbody in my example to show that it's not well taken into account in scollable mode.

_Originally posted by @marob in https://github.com/primefaces/primeng/issues/10541#issuecomment-906241844_

**Comment by gl3nnTP** [comment]
+1

**Comment by mcrtricolor** [comment]
I have the same problem, rowspan not working with scrollable table and virtual scrolling. I also use iconic framework.

**Comment by andzno1** [comment]
Here is another example of a scrollable table based on the example from [Issue 10541](https://github.com/primefaces/primeng/issues/10541#issuecomment-906204420). The first colum's `colspan` is `2` but it doesn't render correctly.

Example: https://stackblitz.com/edit/primeng-tablescrollcolgroup-demo-kzsrs5?file=src/app/app.component.html

**Comment by Mysame** [comment]
`headergrouped` has fixed `rowspan` not working, but `colspan` works in header but gets ignored in body. @yigitfindikli maybe knows more.

**Comment by andzno1** [comment]
`colspan` is not working in my example. It seems to only work if every cell in a row has the same `colspan` value. When there are cells with different `colspan` values in a single row the layout seems to be broken.

**Comment by yigitfindikli** [comment]
Seem it works with the latest PrimeNG.

https://stackblitz.com/edit/primeng-tablecolgroup-demo-wx8myr?file=src/app/app.component.ts

**Comment by andzno1** [comment]
`colspan` does not work in headers for different `colspan` values in a single row. Please have a look at this example:

https://stackblitz.com/edit/primeng-tablescrollcolgroup-demo-kzsrs5?file=src/app/app.component.html

The first header column has a `colspan` of `2` but it doesn't render correctly:

![primeng-colspan](https://user-images.githubusercontent.com/4320938/161036087-a15c6569-2efa-4f41-aef5-c2d8ec28c79f.png)

**Comment by marob** [comment]
> Seem it works with the latest PrimeNG.

What makes you think it's fixed?
On https://stackblitz.com/edit/primeng-tablecolgroup-demo-wx8myr?file=src/app/app.component.ts, it's clearly still broken:

![image](https://user-images.githubusercontent.com/3486231/161438251-bc732300-e585-471b-949b-6e46f0532768.png)

@yigitfindikli Please, reopen the issue.

**Comment by Mysame** [comment]
It's definitely not fixed, and I do hope they look at it quickly.

**Comment by mcrtricolor** [comment]
This is still an issue in primeng 14, if you use virtualScroll colspan doesn't work.

**Comment by marob** [comment]
This is (finally) fixed in 14.2.1
