### ISSUE TITLE
Autocomplete:Select first option with same field but different dataKey 

### ISSUE THREAD

**Issue by Mancioz** [primefaces/primeng#10773]
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Plunkr Case (Bug Reports)**

**app.component.html:**
```
	<p-autoComplete
			dataKey="code"
			[forceSelection]="true"
			[(ngModel)]="selectedUser"
			[suggestions]="filteredUsers"
			(onSelect)="selectUser($event)"
			(completeMethod)="filterUser($event)"
			field="name"></p-autoComplete>

```
**app.component.ts:**
```
 users: any[];
 selectedUser: any
 filteredUsers: any[];
 constructor() {
    super();
    this.users= [
      { name: 'David Mayer', code: 'DM' },
      { name: 'David Mayer', code: 'MD' },
      { name: 'Jhon Flint', code: 'JF' },
    ];
  }
  filterUser(event) {
        let filtered: any[] = [];
        let query = event.query;
        
        for (let i = 0; i < this.users.length; i++) {
	        let user= this.users[i];
	        if (user.name.toLowerCase().indexOf(query.toLowerCase()) == 0) {
		        filtered.push(user);
	        }
        }
        
        this.filteredUsers= filtered;
    }
   selectUser(event) {
        console.log(this.selectedUser.code)
   }

```
PS I couldn't create the StackBlitz because some errors occurs on the console and the application keeps stuck loading forever with the initial template:

**Current behavior**

When i keypress `RETURN `on the  second option (name: 'David Mayer', code: 'MD') on the list of suggestions 
the model (selectedUser) is first set with the correct value (name: 'David Mayer', code: 'MD' ) but after pressing the `tab `key the first value is selected (David Mayer', code: 'DM).
If I use the mouse click on the list of suggestions all works fine.
This behavior is only triggered with the `forceSelection=true`

**Expected behavior**
The correct model selection with the option chosen from the list

**Minimal reproduction of the problem with instructions**
On the input autocomplet press key D press key arrow two time press carriage return and tab at the end.
In the console.log you can see  print exact value when you press `return` but when component lose focus you can see
in the console error value 

**What is the motivation / use case for changing the behavior?**
If I select one item on the list the model must have this value 
even if the label has the same value

**Please tell us about your environment:**
Operating syste: Windows 10
IDE: IntelliJ
HTTP server: Angular live server
* **Angular version:** 12.2.11

* **PrimeNG version:** 12.2.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by Mancioz** [comment]
Any newS?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
