### ISSUE TITLE
p-blockui doesnt work on primeng 12.2.1

### ISSUE THREAD

**Issue by HeavyRainLQ** [primefaces/primeng#10777]
when i set the attribute blocked to false the blockui overlay remain.
I cant link example with stackblitz. It doesnt accept primeng 12.2.1

Just try the demo example locally with primeng 12.2.1

* **Angular version:** 12.2.11

* **PrimeNG version:** 12.2.1

**Comment by miki995** [comment]
@yigitfindikli Hello, any updates, any docs while upgrading primeng to spot this or we have to encounter an issue to actually see it?

**Comment by clopez1winsupply** [comment]
this same issue is present in Primeng 15, for anyone looking for a solution the same workaround above can be applied.
