### ISSUE TITLE
P-Dropdown is not hidden when Frozen cols scrolled in p-table

### ISSUE THREAD

**Issue by tigrenok00** [primefaces/primeng#10782]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

When using p-table with horizontal scrolling and frozen cols, when there is a p-dropdown in a scrolled cell - in floats above and is not hidden under the frozen cols.

![image](https://user-images.githubusercontent.com/23075641/139075920-3861f8b6-7136-4da4-9a57-c35897b0274e.png)

Similar issue:
https://github.com/primefaces/primeng/issues/10613

Angular 12.2.11
Primeng ^12.2.1

**Comment by dcanning** [comment]
stackblitz: https://stackblitz.com/edit/primeng-tablescroll-demo-g7xqkk?file=src%2Fapp%2Fapp.component.css,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
