### ISSUE TITLE
Incorrect properties names in toggle button, eg. "onLabel" or ""onIcon"

### ISSUE THREAD

**Issue by Krisuuuuuu** [primefaces/primeng#10786]
The component works properly, but there is a problem related to testing.

Uncaught Error: Template parse errors:
Binding to event property 'onLabel' is disallowed for security reasons, please use (Label)=...
If 'onLabel' is a directive input, make sure the directive is imported by the current module. ("
[(ngModel)]="val"></p-toggleButton> -->

Could you consider changing the names of these properties to a names which does not start for phrase "on"?

Running tests by jest are not possible, because all of the tests in this describe fails due to compilation error.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
