### ISSUE TITLE
Mouseevent for primeng colorpicker

### ISSUE THREAD

**Issue by ferily7** [primefaces/primeng#10785]
I noticed that when you look at the MouseEvent for colorpicker `onChange()`, I noticed that there is a MouseEvent for `mousedown` and `mousemove`, but there isn't one for `mouseup`? So when you move the slider and release it, there is no event for that...

I am trying to get the colorpicker value AFTER the user moves the colorpicker slider and selects the color. I think this use case would be a perfect example to have the `mouseup` event in the MouseEvent.... Unless there is already a way to do this already

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
