### ISSUE TITLE
p-table : Support both single and double click events 

### ISSUE THREAD

**Issue by sha-opentext** [primefaces/primeng#10780]
PrimeNg Version : 10 LTS
Angular version : 12

This is my p-table 
```
<p-table [value]="cars"(onRowSelect)="OnRowSingleClick($event)">
    <ng-template pTemplate="header">
            <tr>
                <th>Vin</th>
                <th>Year</th>
                <th>Brand</th>
                <th>Color</th>
            </tr>
        </ng-template>
        <ng-template pTemplate="body" let-car>
            <tr [pSelectableRow]="car" (dblclick)="onRowDblClick($event, car)">
                <td>{{car.vin}}</td>
                <td>{{car.year}}</td>
                <td>{{car.brand}}</td>
                <td>{{car.color}}</td>
            </tr>
     </ng-template>
</p-table>
```
And in component.ts file I have : 
```
onRowDblClick(event, car){
console.log("Row double click")

}
OnRowSingleClick(event, car){
console.log("Row single click")
}
```
Now if I double click on row, it shows  : 
Row single click
Row double click

But I want this only  : 
Row double click 

How do I catch single and double click row separately in different events ? 

Thanks,
Shashank

**Comment by peterblazejewicz** [comment]
Isn't that native behaviour? both 'single' and 'dbl' clicks are dispatched. `event.type` can be used to detect which one is currently handled.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
