### ISSUE TITLE
disable property on input doesn't work when input is within a form

### ISSUE THREAD

**Issue by decentaur** [primefaces/primeng#10791]
**I'm submitting a ...**  
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
when an input is within a form the disabled property doesn't work

**Expected behavior**
when setting the disabled property to true, the input field should be disabled

**Minimal reproduction of the problem with instructions**

https://stackblitz.com/edit/github-m27b8y-dg9jjr?file=src/app/app.component.html

**What is the motivation / use case for changing the behavior?**
making disabling fields consistent

**Please tell us about your environment:**

* **Angular version:** 5.X
12.0.5

* **PrimeNG version:** 5.X
12.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

* **Node (for AoT issues):** `node --version` =   
n/a

**Comment by carlos-hs** [comment]
There's another similar topic where it was discussed and it helped me with this issue.
Maybe this can help others as well:
https://github.com/primefaces/primeng/issues/9280#issuecomment-696929385

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
