### ISSUE TITLE
Sidebar with appendTo appears shortly during destruction

### ISSUE THREAD

**Issue by anaq1** [primefaces/primeng#10795]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
```

**Plunkr Case (Bug Reports)**

First click "Show sidebar", then "Switch panels". During the animation "Sidebar 1" is shown in panel 1 even it should not be visible.

https://github-a5chsh.stackblitz.io

**Current behavior**

After upgrade from 11 to 12 sidebars started to blink when I change the route. This is because there is an animation when the route is changed and during this animation the sidebar becomes visible even without any change of visibility.

I looked into sources and IMO the line causing this issue is this one in onDestroy:

```
if (this.appendTo && this.container) {
    this.el.nativeElement.appendChild(this.container);
}
```

I don't understand the motivation of this code, so I don't want to touch it...

This line exists also in version 11, but there is no issue. This is because the sidebar container has opacity 0, so it's there but not visible. In version 12 it has default opacity. 

**Expected behavior**

Sidebar is not visible during animation / onDestroy.

**Minimal reproduction of the problem with instructions**

1. Add at least 2 components which can be switched by ngIf or routing.
2. To first component add a sidebar with appendTo=body
3. Add a 1s animation to the switching.
4. Show and hide sidebar
5. Switch components -> you will see the sidebar container appearing in the first component during animation

**What is the motivation / use case for changing the behavior?**

It's simply a bug.

* **Angular version:** 5.X

Anuglar 12.2.12

* **PrimeNG version:** 5.X

PrimeNG 12.2.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
