### ISSUE TITLE
AutoComplete sugesstions' portion is transparent in Chrome browser

### ISSUE THREAD

**Issue by softbitsio** [primefaces/primeng#1079]
AutoComplete is barely visible in Chrome, however it looks OK in Safari. I had tried its behaviour in several starting projects and every time it has been the same. Those screenshots (attached) has been taken from project scaffolded with recommended Angular seed project from https://github.com/mgechev/angular-seed.

![zrzut ekranu 2016-10-18 o 19 39 00](https://cloud.githubusercontent.com/assets/22918651/19489347/357099aa-956b-11e6-9993-b9f3d23ae68f.png)
![zrzut ekranu 2016-10-18 o 19 38 50](https://cloud.githubusercontent.com/assets/22918651/19489348/3576f50c-956b-11e6-9166-4adea656d92c.png)

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
