### ISSUE TITLE
Feature Request: Multiselect Minimum Selection Limit Option

### ISSUE THREAD

**Issue by gcko** [primefaces/primeng#10790]
I'm submitting a ... 

[ ] bug report
[x] feature request
[ ] support request

A property that denotes the minimum number of items that **must** be selected in the multiselect would be greatly appreciated. If the minimum number of items are selected, The minimum number of items should be disabled
If property is not provided, then by default it is ignored.

What is the motivation / use case for changing the behavior?
There are use cases where we would want to limit the use cases where a user can deselect all items within a multiselect. We are currently using the `onChange` event to handle this now, however having it as a native option in PrimeNG would be preferred.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
