### ISSUE TITLE
lazy load not triggered after scroll

### ISSUE THREAD

**Issue by daniilzaonegin** [primefaces/primeng#10800]
Hi!

**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report 
```

Here is the code on stackblitz, but scrollHeight="flex" doesn't work there

https://stackblitz.com/edit/primeng-tablevirtualscroll-demo-pwydsq?file=src%2Fapp%2Fapp.component.html

**Current behavior**
p-table doesn't trigger onLazyLoad event when scrolled down to load next chunk of data to show the user.

**Expected behavior**
p-table should trigger onLazyLoad event when scrolled down to load next chunk of data to show the user.

**Minimal reproduction of the problem with instructions**

* Create an app 
https://stackblitz.com/edit/primeng-tablevirtualscroll-demo-pwydsq?file=src%2Fapp%2Fapp.component.html

* Press Reset button and then scroll down. It will stop on 50 rows and won't scroll further, although there is 256 records in total.

![p-table-test](https://user-images.githubusercontent.com/28781018/139929138-8f7c165a-96a2-45c5-af7e-965d4dcac86c.gif)

Code:

[primeNgTest.zip](https://github.com/primefaces/primeng/files/7463443/primeNgTest.zip)

**Please tell us about your environment:**

Angular version: 12.2.12
PrimeNG version: 12.2.2
Browser: Chrome 94.0.4606.71

**Comment by stephane-tessier** [comment]
I face the exact same issue

**Comment by daniilzaonegin** [comment]
Hi! 

I've noticed, that this behaviour happens only when you reset the p-table. When it loads without reset, everything works fine. When table loads rows without reset it requests rowsPerPage*2 rows. I have resolved the issue the following way. Every time request finishes successfully I store the lastLazyLoadEvent into variable.
When this.lastLazyLoadEvent is undefined, then it is the first request. And on first request I add manualy rowsPerPage one more time.

```js

 rowsPerPage: number = 50;
 lastLazyLoadEvent: LazyLoadEvent;

//... ommited other code

  resetGrid() {
        this.rows = undefined;
        this.columns = undefined;
//i set it undefinded, so that onLazyLoad loads not rowsPerPage, but rowsPerPage*2 rows
        this.lastLazyLoadEvent = undefined;
        this.selectedBookmark = null;
        this.jsonLazyLoadEventLast = null;

        this.selectedRows = [];
        this.disableDataDependendButtons();

        this.documentsGrid.reset();
    }

async onLazyLoad(event: LazyLoadEvent) {
        if (!this.request) {
            return;
        }

       //... ommited other code

       if (!this.lastLazyLoadEvent)
            event.rows += this.rowsPerPage;
        this.request.PagingFirstRow = event.first;
        this.request.PagingRowsCount = event.rows;
       try{

           //... load data from server

            if (event)
                this.lastLazyLoadEvent = event;

            this.request.callSuccess();
        } catch (e) {
            this.error.handleServiceException(e);
            this.lastLazyLoadEvent = undefined;
            this.request.callError();

        } finally {
            this.loading = false;
            this.operationInProgress = false;
        }
}
```

**Comment by yigitfindikli** [comment]
Hi @stephane-tessier @daniilzaonegin 

This is caused by array length. If you gonna reset your table data you need to update length as well.

Live example: https://stackblitz.com/edit/primeng-tablevirtualscroll-demo-rkcd6k (daniilzaonegin's example)

**Comment by stephane-tessier** [comment]
Hi @yigitfindikli 
In my github example I already set the array lenght (artificially) to 90:  
https://github.com/stephane-tessier/primeng-table-infinite-scroll/blob/master/src/app/app.component.ts
```
if (this.currentPage === 1) {
  this.orders = Array.from({length: 90});
}
    ```
