### ISSUE TITLE
selecting an item from the autocomplete panel triggers the onBlur method

### ISSUE THREAD

**Issue by jcastellscan** [primefaces/primeng#10808]
**I'm submitting a ...** 
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-u54oky-mva4yd?file=src/app/app.component.html

**Current behavior**
When SELECTING an item from the autocomplete panel the onBlur method is triggered and after that the onSelect method is triggered. 

**Expected behavior**
When SELECTING an item from the autocomplete panel just the onSelect method should be triggered, not the onBlur.

**Minimal reproduction of the problem with instructions**
you can check it in the plunkr or in the basic sample in primeng when you select an item form the autocomplete panel onBlur method is called first and then the onSelect method is called

**What is the motivation / use case for changing the behavior?**
I want to add custom validation for the autocomplete. Whenever we want to validate the value of the autocomplete we need to do it when we click out of the component (when onBlur). However when selecting an item the onBlur method is called first, and we can not validate properly as the value has not been updated yet.

**Please tell us about your environment:**
this can be seen anywhere, even in the sample in primeng

* **PrimeNG version:** 5.X
latest

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Everywhere

**Comment by waratah** [comment]
This is not a new problem, my work around for it.  (Note I used to use overlayVisible  on the component but it no longer available.)

` blur() {
    setTimeout(() => {
      if (this.autoComplete && !this.overlayVisible) {
        debugger;
        this.getSearchValue(this.isoGroup);
      }
    }, 30);
  }

  showDropdown() {
    this.overlayVisible = true;
  }
  hideDropdown() {
    this.overlayVisible = false;
  }`

` (onBlur)="blur()"
  (onShow)="showDropdown()"
  (onHide)="hideDropdown()"`

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by Niranth** [comment]
Hey, Do we have a proper solution for this issue now?
Unfortunately, work around doesn't solve the problem in my case

**Comment by oliP7** [comment]
When we click on the suggestions the item has hover effect so we can actually check if any of the items from our suggestion is hovered which in our case means that the onBlur should not happen.
In other words if we do not have any suggestion items hovered that we have the onBlur event.
onBlur(): void {
    const suggestions = document.querySelectorAll(".p-autocomplete-panel ul li:hover");
    if (suggestions.length === 0) code what should happen onBlur
  }
  
Hope this helps.
Best Regards
