### ISSUE TITLE
Wrong zIndex for p-toast

### ISSUE THREAD

**Issue by nlachancedev** [primefaces/primeng#10801]
Like this other issue #10767 who is fixed in #10762, it seems like "p-toast" has been forgotten too. When I'm in a modal dialog, all toast messages are hidden behind dialog overlay. 

My guess is that you got some code in toast.ts that uses DomHandler instead of ZIndexUtils (https://github.com/primefaces/primeng/blob/master/src/app/components/toast/toast.ts#L301).

**Comment by yigitfindikli** [comment]
Hi @nlachancedev,

Thanks for your investigation.
