### ISSUE TITLE
Picklist Filter with string array 

### ISSUE THREAD

**Issue by jorgebfrr** [primefaces/primeng#10805]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
[https://stackblitz.com/edit/primeng-picklist-demo-senfhd?file=src/app/app.component.ts](url)

**Current behavior**
The filterBy function is not working because the source and destination are a string [ ]. It only works for Objects because it's always necessary to add an object property to use the filterBy.

**Expected behavior**
Pikclist filter with string array functionality.

**Minimal reproduction of the problem with instructions**
![EWZm5D7s8B](https://user-images.githubusercontent.com/9919139/140105671-846155a8-454e-43e5-9e83-493954d55092.gif)

**What is the motivation / use case for changing the behavior?**
Allow to use the filterBy function with string[ ] instead of object[ ].

**Please tell us about your environment:**
Windows 10, npm@latest-7

* **Angular version:** 12.2.2

* **PrimeNG version:** 12.2.1

* **Browser:** all
 
* **Language:** TypeScript 4.4

* **Node (for AoT issues):** `node --version` =   v14.16.1

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
