### ISSUE TITLE
Can we have an AOT compatibility beta soon?

### ISSUE THREAD

**Issue by tapas4java** [primefaces/primeng#1081]
Hi,

Thanks for the hard work. Is there any tentative ETA for AOT compilation support?

**Comment by jmesa-sistel** [comment]
From [Pull request 1004](https://github.com/primefaces/primeng/pull/1004)

>  AOT support in 1.0.0-RC1 (end of october)

**Comment by cagataycivici** [comment]
Closing as this is a question.
