### ISSUE TITLE
chip: interactive remove icon element focus is not circular

### ISSUE THREAD

**Issue by peterblazejewicz** [primefaces/primeng#10816]
**I'm submitting a ...**
[x] bug report => Search github for a similar issue or PR before submitting

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/primeng-chip-demo

**Current behavior**
Use keyboard or any device that gives interactive element a focus
Notice that focus is rectangular like, not really aligned with interactive element itself

![chips-before](https://user-images.githubusercontent.com/14539/140625424-f2d2ec61-d76a-42d1-a95c-789a0e3bfec2.png)

**Expected behavior**
when using keyboard the focus should be aligned with shape of the interactive element, unless there
is a clean reason to not do this

![chips-after](https://user-images.githubusercontent.com/14539/140625410-0e80b971-e2f7-4fb8-b65d-c06d4f768798.png)

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
better usability

* **PrimeNG version:** 12.2.2

* **Browser:** Chrome Xx ]

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
