### ISSUE TITLE
PrimeNG Scroll Table doesn't change scroll position based on [(selection)]

### ISSUE THREAD

**Issue by jermylucas** [primefaces/primeng#10814]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request 
[ ] support request 
```

**StackBlitz Case (Bug Reports)**
https://primeng-tabledynamic-demo-wpvcnt.stackblitz.io

**Current behavior**
When a `[(selection)]` value is passed into a scroll table, the scrollbar position doesn't change to reflect where the currently highlighted item is. In the stackblitz below, the default product is item 6 in the table array (product[5]). However, since only the first 4 items are shown, there is no indication of the selected product's location. When using `tab` or arrowing up and down after a highlight, the scrollbar does change, but not when using the `[(selection)]` property. 

**Expected behavior**
The scroll bar should be positioned so the `[(selection)]` item is visible inside of the scroll table.

**Minimal reproduction of the problem with instructions**
Simply opening the StackBlitz you will be able to see that the selected item does not appear selected until you scroll down further.

**What is the motivation / use case for changing the behavior?**
This would allow passing in of values into a scroll table. This would also allow navigation through a table using arrow keys on a scroll table (this prompted the creation of feature request #10815 )

* **Angular version:** 5.X
12+

* **PrimeNG version:** 5.X
12+

* **Browser:** 
All

**Comment by jermylucas** [comment]
I was able to solve a work-around using a scrollTable() function. This relates somewhat to the closed issue 5762: https://github.com/primefaces/primeng/issues/5762 .
I made an updated directive in case someone is wanting to use this on multiple tables without repeating code. 
This directive works on any selectable table. It also works with table filtering by passing in the filtered items into the directive. The directive also handles all the navigation with arrow keys as requested in issue: #10815 so can be a workaround for that as well. You don't need to implement arrowkey navigation on a per-component basis with this addition.

[Full StackBlitz Here](https://stackblitz.com/edit/primeng-tabledynamic-demo-kgfjfp?file=src/app/tablenavigation.directive.ts) with Scroll Table implementation as well as a search filter.

```
import {
  Directive,
  ElementRef,
  OnInit,
  HostListener,
  Output,
  EventEmitter,
  Input,
} from '@angular/core';
import { Table } from 'primeng/table';

@Directive({
  selector: '[tableNavigation]',
})
export class TableNavigationDirective implements OnInit {
  /////////
  // You will need to have the table in focus for this to work (as expected)
  // You can use these event emitters to display and trigger events from within component
  // add `tableNavigation` to <p-table>
  // (selectProduct)="selectedProduct = $event"
  // and  (openProduct)="openProduct()"
  /////////
  @Output() selectProduct: EventEmitter<any> = new EventEmitter();
  @Output() openProduct: EventEmitter<any> = new EventEmitter();
  // If you want to include filtering, you'll want to use this input.
  _visibleItems: any;
  @Input('visibleItems') set visibleItems(items: any) {
    this._visibleItems = items;
    if (this._visibleItems) {
      this.rowIndex = 0;
      this.table.selection = this._visibleItems[0];
      this.selectProduct.emit(this.table.selection);
      this.scrollTable();
    }
  }

  rowIndex = 0;

  constructor(private table: Table, private el: ElementRef<HTMLElement>) {
    this._visibleItems = this.table.value;
  }

  ngOnInit() {
    this.el.nativeElement.tabIndex = 1;
  }

  @HostListener('keydown.ArrowUp', ['$event']) ArrowUp($event: KeyboardEvent) {
    $event.preventDefault();

    this.table.selection = this.navigateItem(-1);
    this.selectProduct.emit(this.table.selection);
    this.scrollTable();
  }

  @HostListener('keydown.ArrowDown', ['$event']) ArrowDown(
    $event: KeyboardEvent
  ) {
    $event.preventDefault();

    this.table.selection = this.navigateItem(1);
    this.selectProduct.emit(this.table.selection);
    this.scrollTable();
  }

  @HostListener('keydown.Enter', ['$event']) Enter($event: KeyboardEvent) {
    this.openProduct.emit();
  }

  navigateItem(num) {
    if (!this.table.selection) {
      return;
    }

    const i = this._visibleItems.indexOf(this.table.selection);
    const len = this._visibleItems.length;

    if (num > 0) {
      if (num > 0 && this.rowIndex === len - 1) {
        return this._visibleItems[len - 1];
      } else {
        this.rowIndex++;
        return this._visibleItems[(i + num) % len];
      }
    }
    if (num < 0) {
      if (num < 0 && this.rowIndex === 0) {
        return this._visibleItems[0];
      } else {
        this.rowIndex--;
        return this._visibleItems[(i + len + num) % len];
      }
    }
  }

  scrollTable() {
    let wrapper =
      this.table.el.nativeElement.children[0].getElementsByClassName(
        'p-datatable-wrapper'
      )[0];
    let rows = wrapper.getElementsByClassName('p-selectable-row');

    // No need to scroll if there aren't any products
    if (!rows.length) {
      return;
    }
    let rowEl = rows[this.rowIndex];

    // Scroll all the way to top if first item
    if (rowEl === rows[0]) {
      wrapper.scrollTop = 0;
    }

    // Change scroll position if not first item and at bottom of scrollbar
    if (rowEl.offsetTop + rowEl.offsetHeight > wrapper.offsetHeight) {
      wrapper.scrollTop +=
        rowEl.offsetTop +
        rowEl.offsetHeight -
        wrapper.scrollTop -
        wrapper.offsetHeight;
    }
  }
}
```

**Comment by jermylucas** [comment]
As a note to the pending-review, this is only necessary if the issue #10815 would be fulfilled. It doesn't really matter unless there's a built in method of navigating with keys instead of mouse. I should have submitted these two issues in the opposite order :)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
