### ISSUE TITLE
feature: Country code picker with phone no input

### ISSUE THREAD

**Issue by ashwinikumar01** [primefaces/primeng#10818]
**I'm submitting a** (check one with "x")
[ ] feature request 

It will be good if PrimeNg would have already a country code picker with the country flags & a input field where user can type the phone no
<img src="https://user-images.githubusercontent.com/69667369/140649361-03deb6f6-fa6a-481f-888f-ba8cb86be05f.jpg" width="400" height="200" />

**Comment by ashwinikumar01** [comment]
@yigitfindikli Any update on this feature?

**Comment by anonymousdplantgit** [comment]
A nice to have

**Comment by ashwinikumar01** [comment]
@yigitfindikli Any update on this feature?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
