### ISSUE TITLE
Allow built-in navigation of table rows with arrow keys

### ISSUE THREAD

**Issue by jermylucas** [primefaces/primeng#10815]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x ] feature request
[ ] support request 
```

I am submitting a feature request to allow navigation of a table with the arrow keys. Specifically, navigating the rows, but the columns (like ms excel/google sheets) could be valuable in the future. 

When a table is "in focus", allow the user to use arrow keys to navigate up and down across the table, highlighting table cells and being able to select a cell with `enter` keypress. This is possible somewhat by using the `tab` key on a standard keyboard -- pressing `tab` multiple times until a row is selected, but if there are multiple columns this takes far-too-many keypresses. 

For example of this feature, on arrow down, user could access the row and then click "enter" to make a selection. On the current tables, if a row is selected, and *then* a user uses the up and down arrows, this is accessible:

![image](https://user-images.githubusercontent.com/47125917/140578895-e28a4961-b66d-4717-9f1f-90529c0dd9c0.png)

I have also made a StackBlitz showing my current solution, where the `[(selection)]` is bound to a specific item in an array, and by using `@HostListener`, a user is able to press the arrow keys to change this "selection" and therefore move up and down throughout the table. This is the behavior I would be expecting if the above is not possible. Note, this does lead to a problem found in issue #10814  where the scroll bar wouldn't change position if using a scroll table. 

https://primeng-tabledynamic-demo-npakk7.stackblitz.io

Please note that to see the behavior in the stackblitz above, you will need to have the "search" input focused. You can also press `enter` to see the action (could be a row selection in this feature)

![image](https://user-images.githubusercontent.com/47125917/140579618-37aa5e97-85be-4c6a-95e0-a2adad7c5029.png)

Thank you for considering this feature.

**Comment by jermylucas** [comment]
As in issue #10814 , I have made a directive that handles the arrow key functionality as well as fixing the issue in the 10814. It would be great to have something like this built in with PrimeNG.

Please check out the bug issue for more details of this directive. You can view the stackblitz with a working directive [here](https://stackblitz.com/edit/primeng-tabledynamic-demo-kgfjfp?file=src/app/tablenavigation.directive.ts)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
