### ISSUE TITLE
ViewEncapulation.Native is not supported

### ISSUE THREAD

**Issue by yfain** [primefaces/primeng#1082]
While ViewEncapsulation.None and ViewEncapsulation.Emulated work fine,  ViewEncapsulation.Native removes styling from PrimeNG components. 

To reproduce, uncomment the encapsulation property line in the AppComponent in this project:
https://github.com/yfain/primeng_seed

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
