### ISSUE TITLE
Improve devexp decreasing number of linter errors

### ISSUE THREAD

**Issue by peterblazejewicz** [primefaces/primeng#10821]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**
n/a

**Current behavior**
There are so many linter errors when working with the project contribution, that's literally a limiting factor.
The exact number, can be shared if requested by PF folks

**Expected behavior**
Meaningful number of problems

**Minimal reproduction of the problem with instructions**
Open any of non-trivial implementaiton file within IDE like VSCode with current linter ('tslint') enabled or run:

> npm run lint

**What is the motivation / use case for changing the behavior?**
devexp improvment, lowering entry barier

**Please tell us about your environment:**
VSCode

* **Angular version:** 5.X
n/a

* **PrimeNG version:** 5.X
12.2.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS n/a

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
n/a

* **Node (for AoT issues):** `node --version` =   
n/a

**Comment by thetric** [comment]
PrimeNG currently uses the deprecated TSLint which was removed in Angular 12. So `npm run lint` does not work at all. I have provided a [pull request which migrates to ESLint](https://github.com/primefaces/primeng/pull/10793) which is the de facto standard linter for JavaScript and TypeScript.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
