### ISSUE TITLE
Table | Version update for export examples

### ISSUE THREAD

**Issue by sriniashok** [primefaces/primeng#10826]
after install jspdf and jspdf_ autoTable 
not working doc.autoTable

this.cols = [
      { field: 'bank_Name', header: 'Bank Name' },
      { field: 'short_Code', header: 'Short Code' },
      { field: 'country', header: 'Country' }
  ];
 this.exportColumns = this.cols.map(col => ({title: col.header, dataKey: col.field}));
this.bankLists= [{"bank_Name":"city bank","short_Code":"CIb","country":"American Samoa"},
{"bank_Name":"sena bank","short_Code":"db","country":"Antarctica"},
{"bank_Name":"dBS bank","short_Code":"dbs","country":"Singapore"}]
exportPdf() {
      import("jspdf").then(jsPDF => {
          import("jspdf-autotable").then(x => {
              const doc = new jsPDF.default(0,0);
              doc.autoTable(this.exportColumns, this.bankLists);
              doc.save('products.pdf');
          })
      })
  }

**Comment by yigitfindikli** [comment]
Hi @sriniashok,

Thanks for your report. But pdf and excel exports are not feature of primeng, they are just examples. Direct quote from our docs:

> PDF and EXCEL export are also available using 3rd party libraries such as jspdf. Example below demonstrates how to implement all three export options.

I'm gonna change your report to version update for jspdf.

**Comment by sriniashok** [comment]
i'm using  another type autoTable(doc, {head: heads, body: bodys})
but this type body not suporting json format 
aka. this.bankLists= [{"bank_Name":"city bank","short_Code":"CIb","country":"American Samoa"},
{"bank_Name":"sena bank","short_Code":"db","country":"Antarctica"},
{"bank_Name":"dBS bank","short_Code":"dbs","country":"Singapore"}]

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
