### ISSUE TITLE
Select All functionality in a Table doesn't visually work on a row that is already selected

### ISSUE THREAD

**Issue by vanhercksam** [primefaces/primeng#10829]
**I'm submitting a ...**  (
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/primeng-tableselection-demo-yd6inw?file=src/app/app.component.ts

**Current behavior**

Select All functionality from a ContextMenu in a Table doesn't visually work on a row that is already selected

**Expected behavior**

All rows in a Table should get visually selected

**Minimal reproduction of the problem with instructions**

1. Select a row by left-clicking
2. Right-click the selected row from step 1 to open the ContextMenu
3. Click the "Select All" option from the ContextMenu
= All rows are selected in the background but it's not visualized in grid

(Select All option does work when using it on a row that is not already selected)

**What is the motivation / use case for changing the behavior?**

Trying the implement a Select All option on the ContextMenu of a row

**Please tell us about your environment:**

Reproduced on Stackblitz

* **Angular version:**  12.0.5

* **PrimeNG version:** 12.1.0-rc.1

* **Browser:** Chrome
 
* **Language:** TypeScript ~4.0.2

* **Node:** /

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
