### ISSUE TITLE
Angular 13 Editor not loading properly "ERROR TypeError: ({get default(value}) is not a constructor" primeng-editor.mjs:29

### ISSUE THREAD

**Issue by lazar0303** [primefaces/primeng#10834]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template
Could load Angular 13, but not not PrimeNg 13 package on stackblitz.

**Current behavior**
![bad](https://user-images.githubusercontent.com/56915764/141180324-6a425439-3036-4f05-a066-5f54963c0d48.JPG)
![error](https://user-images.githubusercontent.com/56915764/141180357-ec580771-0f53-4acb-99c1-e3aa7168deb7.JPG)

**Expected behavior**
![good](https://user-images.githubusercontent.com/56915764/141180374-ded1408e-6e33-4bcc-a87a-fe135ff77550.JPG)

**Minimal reproduction of the problem with instructions**
default implementation of editor

**Please tell us about your environment:**
Fedora 35, local testing

* **Angular version:** 13.X

* **PrimeNG version:** 13.X

* **Browser:** Firefox Latest

* **Node (for AoT issues):** `node --version` =  16.11

**Comment by magicdict** [comment]
I have the same issue.

**Comment by osintsevvladimir** [comment]
And I have :(

**Comment by RolfVeinoeSorensen** [comment]
I have the same issue as @osintsevvladimir

**Comment by ccit-spence** [comment]
Same issue here with Angular 13

**Comment by ccit-spence** [comment]
Further information about the error I found during debugging

```
core.mjs:6495 ERROR TypeError: (quill__WEBPACK_IMPORTED_MODULE_0___namespace_cache || (intermediate value)(intermediate value)) is not a constructor
    at Editor.ngAfterViewInit (primeng-editor.mjs:29)
    at callHook (core.mjs:2533)
    at callHooks (core.mjs:2502)
    at executeInitAndCheckHooks (core.mjs:2453)
    at refreshView (core.mjs:9574)
    at refreshEmbeddedViews (core.mjs:10628)
    at refreshView (core.mjs:9527)
    at detectChangesInternal (core.mjs:10856)
    at ViewRef$1.detectChanges (core.mjs:21761)
    at InputText.ngAfterViewInit (primeng-inputtext.mjs:14)
```

**Comment by lcnmorais** [comment]
I am with the same error.

**Comment by SergeyMell** [comment]
Same for me

**Comment by SergeyMell** [comment]
As a quick fix, you can just copy the source code of editor component (https://github.com/primefaces/primeng/blob/master/src/app/components/editor/editor.ts) into your application and it will work correctly
