### ISSUE TITLE
Button iconPos different type in directive

### ISSUE THREAD

**Issue by Thiltal** [primefaces/primeng#10839]
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Current behavior**

    In Directive
    @Input() iconPos: 'left' | 'right' | 'top' | 'bottom' = 'left';

    In Component
    @Input() iconPos: string = 'left';

**Expected behavior**

    In Directive
    @Input() iconPos: 'left' | 'right' | 'top' | 'bottom' = 'left';

    In Component
    @Input() iconPos: 'left' | 'right' | 'top' | 'bottom' = 'left';

**Minimal reproduction of the problem with instructions**

not to reproduce

**What is the motivation / use case for changing the behavior?**

 bad typecheck

**Please tell us about your environment:**
 irrelevant

* **Angular version:** 5.X
 irrelevant

* **PrimeNG version:** 5.X
13.0.0-rc.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
 all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
 all

* **Node (for AoT issues):** `node --version` =   
irrelevant

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
