### ISSUE TITLE
TreeSelect value is the complete TreeNode instead of 'data'

### ISSUE THREAD

**Issue by cmglez10** [primefaces/primeng#10836]
**I'm submitting a ...**  
```
[ X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

When you select a field in a TreeSelect in the ngModel is setted the complete TreeNode (even with its children).

**Expected behavior**

It should be selected the contain of data, inside of the TreeNode

* **Angular version:** 12.X

* **PrimeNG version:** 12.2.X

**Comment by techmaster242** [comment]
I'm running into this exact same issue. I'm trying to use a lot of controls to build a dynamic array of filters, and then be able to grab all the currently applied filters, and save them as a "view". Then, the user can select from a list of saved views, and upon selection, it will apply the saved filters to the list of filter controls. This works for every single one we're using, except where we're using this treeselect control. We're using treeselect in a reactive form, so you basically have two important functions:

control.valuesChanges observable returns entire items with parent and children items, and circular references everywhere.
control.setValue seems to expect data back in the same format.

Ideally, valueChanges should return an array of selected keys, and setValue should accept the same array of keys. It would then recursively traverse the tree to find which items are in the array of keys, and enable them, and dynamically turn on selected or partialSelected for the container nodes. For the time being, we might have to find another solution, or possibly make a fork of the component that can work this way.

**Comment by ElesGergo** [comment]
same here... Any update on this one ?

**Comment by hieunv183534** [comment]
can i pass value for treeSelect ? the value ngModel of treeSelect is a node and very complex so i can't pass value for treeSelect?

**Comment by ivan-price-acted** [comment]
hi there i find myself here also, it seems accessing the data (setting or getting) is complicated, are we really required to construct the entire sub-tree in the model, matching the `options` (including parents/relationships !), to set existing values ?

this component doesn't seem to be up to the same standard as the other quality primeng components. i'd be interested to know if other users are managing to load selection data into the tree, or indeed use the component in ways other than single-node events.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by yarikwest** [comment]
this issue wasn't resolved

**Comment by situlindia** [comment]
Issue #16394 raised for the same.

**Comment by sergei202** [comment]
My workaround is using `onNodeSelect` event.  Definitely not ideal, but it works.

HTML:
```
<p-treeSelect class="w-full" containerStyleClass="w-full" [options]="categoryNodes" selectionMode="single" [(ngModel)]="categoryNode" placeholder="Select a Category" (onNodeSelect)="onCategorySelect()"/>
```

Typescript:
```
export class TransactionDetailPageComponent {
    transaction: Transaction;
    categoryNodes:TreeNode[];
    categoryNode:TreeNode;

    constructor(
        private transactionService: TransactionService,
        private categoryService: CategoryService,
        private route: ActivatedRoute, private router: Router) {
    }
        
    async ngOnInit() {
        const transactionId = this.route.snapshot.params['id'];
        this.transaction = await this.transactionService.getTransactionById(transactionId);
        this.categoryNodes = await this.categoryService.getCategoryTree();
        console.log('TransactionDetailPageComponent: transaction=%o, accounts=%o, contacts=%o, categories=%o, categoryNodes=%o', this.transaction, this.accounts, this.contacts, this.categories, this.categoryNodes);

        this.categoryNode = this.findNodeByKey(this.categoryNodes, this.transaction.category?.id);
        console.log('TransactionDetailPageComponent: categoryNode=%o', this.categoryNode);
    }

    findNodeByKey(nodes:TreeNode[], key:string) {
        for(const node of nodes) {
            if(node.key === key) return node;
            if(node.children) {
                const found = this.findNodeByKey(node.children, key);
                if(found) return found;
            }
        }
    }

    onCategorySelect() {
        const category = this.categoryNode?.data;
        console.log('TransactionDetailPageComponent.onCategorySelect: categoryNode=%o, category=%o', this.categoryNode, category);
        this.transaction.category = category;
    }
}
```
