### ISSUE TITLE
If Table is Lazy, all Column Filters trigger an emit of onLazyLoad when Table.clear() is Invoked

### ISSUE THREAD

**Issue by MerrittMelker** [primefaces/primeng#10833]
[ x] bug report => Search github for a similar issue or PR before submitting

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-tablelazy-demo-vh7b6b

**Current behavior**

Very simple: ColumnFilter subscribes to the reset event and calls table.__filter in the subscription. 

**Expected behavior**
Only one triggerr one onLazyLoad emit

**Minimal reproduction of the problem with instructions**
just create a lazy table with column filters and a clear button that calls table.reset/clear

**What is the motivation / use case for changing the behavior?**
It's a pretty big issue: clearing/resetting a table with filtering causes x number of onLazyLoad emits where x is equal to the number of column filters.

**Please tell us about your environment:**
Irrelevant.

* **Angular version:** - doesn't matter but 12.2.9
* **PrimeNG version:**  - 12.2.0 but still a problem in your master branch

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
