### ISSUE TITLE
Table: regression? are frozenColumns still supported with primeng 12.1/13?

### ISSUE THREAD

**Issue by lf-novelt** [primefaces/primeng#10838]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
The frozenColumns that used to work with angular12, primeng12 does not display.

**Expected behavior**
The frozenColumns that used to work with angular12, primeng12 should display.

**Minimal reproduction of the problem with instructions**
Using only the frozenColumns attribute on dynamic columns, not the pFrozenColumn directive
```html
    <p-table #dt sortMode="multiple" *ngIf="!reaped" (onLazyLoad)="loadLazy($event)" [lazy]="true" [paginator]="true"
        [alwaysShowPaginator]="false" [rowsPerPageOptions]="[5,10,15,20,50,100,200,500,1000]"
        paginatorDropdownAppendTo="body" [resizableColumns]="true" [columns]="scrollableCols"
        [frozenColumns]="frozenCols" [value]="visibleRows" [rows]="rowsPerPage" [totalRecords]="totalRecords"
        [loading]="loading" [scrollable]="true" [multiSortMeta]="multiSortMeta" [frozenWidth]="frozenWidth"
        styleClass="p-datatable-gridlines p-datatable-striped">
```

**What is the motivation / use case for changing the behavior?**
I cannot find any working demo example in the primeng **docs site**.
I can't find any reference anymore to the `@Input frozenColumns` in the **source code**, except in the `exportCsv` method 😨 
https://github.dev/primefaces/primeng/tree/13.0.0-rc.2

**Please tell us about your environment:**

* **Angular version:** 13.0.1

* **PrimeNG version:** 12 / 13 rc1/rc2

* **Browser:** [ Opera | Edge | not tested others]

 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =   v16.13.0

**Comment by lf-novelt** [comment]
I can't even find any use of the `frozenColumns` attribute  in https://github.dev/primefaces/primeng/tree/12.2.2

**Comment by yigitfindikli** [comment]
See https://github.com/primefaces/primeng/issues/10395#issuecomment-967249202

**Comment by lf-novelt** [comment]
is this a missed place where frozenColumns should have been removed? It feels like they will be duplicated in the CSV export
https://github.com/primefaces/primeng/blob/d31652a5eab237688d8810051d2e15ccdff1740b/src/app/components/table/table.ts#L1473
