### ISSUE TITLE
CI: Replace deprecated and non-functional travis-ci.org

### ISSUE THREAD

**Issue by thetric** [primefaces/primeng#10846]
travis-ci.org stopped working since June 2021:

> Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on. 
> - https://travis-ci.org/github/primefaces/primeng

This means that pull requests and other branches are not built and tested, thus creating a risk for code quality and reproducibility for this project. I suggest to either set up https://app.travis-ci.com/github/primefaces/primeng (note the other domain name) or switch to [GitHub actions](https://docs.github.com/en/actions/learn-github-actions).

**Comment by Rotzbua** [comment]
I opened two related PRs:
*  remove travis ci #10840 
*  add github actions (ci) #10845

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by Rotzbua** [comment]
@mertsincan The issue is only partially resolved. I have updated the related pull request which removes the outdated files. I can not reopen the issue. Should I open a new issue?

**Comment by Rotzbua** [comment]
Still relevant. Just a cleanup.

**Comment by Rotzbua** [comment]
@cetincakiroglu Any chance to get this simple 2 year old chore topic on the todo list? Feel free to C&P my PR  #12611.
