### ISSUE TITLE
DataTable not saving selection with objects inside

### ISSUE THREAD

**Issue by starostin** [primefaces/primeng#1085]
Hi. I have an issue with datatable. I have selection functionality with multiple selection mode. So when I select one item, I have an object:
`{
id:1,
name: 'Oleg',
homes: [
{
id: 1
}
]
}`

The issue, that when I go to second page and back to first page this item is unselected. I have investigated it a bit, and found that problem in domhandler.ts file in equals method. 
`
case 'object':
                        if (obj1._$visited || !this.equals(obj1[p], obj2[p])) return false;
                        break;
`  
so, first object marked as _$visited, and then we check properties inside this object. And if this property is object, then it always return false. I think that there should be && operator, not ||. If you have any other ideas for fixing this issue, please let me know. Thanks

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with them and if issue persists drop a comment and we'll reopen.
