### ISSUE TITLE
p-calendar with touchui=true in p-dialog no date selection possible

### ISSUE THREAD

**Issue by sf-gra** [primefaces/primeng#10857]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/primeng-accordion-demo-n4du41

**Current behavior**
If a calendar field with "touchui = true" is within an p-dialog, no date selection is possible. The calendar popup is visible but no date is selectable. 

**Expected behavior**
Select an date

**What is the motivation / use case for changing the behavior?**
For mobile friendly applications it is important to use the calendar touchui function within p-dialogs

Please tell us about your environment:
Angular version: 12.2.13
primeng version: 12.2.2
browser: Edge 95.0
node: 12.22.7

**Comment by tongilsoft** [comment]
**__I found a workaround solution for this:__** the problem is z-index for injected div containing the calendar date-picker is more than 1000, but should be less or equal than 1000, so the solution is to change programmatically the element's z-index value.

**__Install 'mutation-summary' package into the project from npm:__** 
```bash
$ npm i mutation-summary --save
```

**__Following typescript code for solution:__** 
```TypeScript
// Imports needed:
import { MutationSummary, Summary, IMutationSummaryOptions } from 'mutation-summary';

ngOnInit(): void {
    this.doDetectCalendar();
}

doDetectCalendar(): void {
    const calendarQuerySelector = 'div.p-component-overlay.p-datepicker-mask.p-datepicker-mask-scrollblocker';
    const detectCalendar = (summaries: Summary[]) => {
        summaries.forEach(
            (summary: Summary) => {
                const cal = document.querySelector(calendarQuerySelector);
                if (cal !== null) {
                    cal.removeAttribute('style');
                    cal.setAttribute('style', 'z-index:900;');
                }
            }
        );
    };
    const detectionConfig: IMutationSummaryOptions = {
        callback: detectCalendar,
        queries: [{ element: calendarQuerySelector }],
        rootNode: document.body
    };
    const ms = new MutationSummary(detectionConfig);
}
```

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
