### ISSUE TITLE
Carousel: make responsiveOptions#numScroll optional

### ISSUE THREAD

**Issue by TimeForANinja** [primefaces/primeng#10858]
**I'm submitting a ...**
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Using the `p-carousel` component with `responsiveOptions` errors out when not providing `numScroll` as part of the `responsiveOptions`

The Error is quite similar to #8300
```
ERROR RangeError: Invalid array length
    at Carousel.totalDotsArray (carousel.ts:466)
    at Object.eval [as updateDirectives] (VM11035 Carousel.ngfactory.js:196)
    at Object.debugUpdateDirectives [as updateDirectives] (services.ts:390)
    at checkAndUpdateView (view.ts:372)
    at callViewAction (view.ts:628)
    at execEmbeddedViewsAction (view.ts:593)
    at checkAndUpdateView (view.ts:373)
    at callViewAction (view.ts:628)
    at execComponentViewsAction (view.ts:572)
    at checkAndUpdateView (view.ts:383)
```

**Expected behavior**
i'd expect `numScroll` of `responsiveOptions` to default to the `numScroll` passed in the html

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/github-ljkvly
* no interaction required to produce the error
* it can be fixed by adding `, numScroll: 1` in `app.component.ts`

**What is the motivation / use case for changing the behavior?**
quality-of-life improvement

**Please tell us about your environment:**

* **Angular version:** 12.X

* **PrimeNG version:** 12.X

* **Browser:** all
 
* **Language:** all

* **Node (for AoT issues):** `node --version` =   n/a

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
