### ISSUE TITLE
P-Input number property [maxFractionDigits] not taking values dynamically changed.

### ISSUE THREAD

**Issue by soumyas98** [primefaces/primeng#10854]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
While using the primeng input number component, the component's property [maxFractionDigits] fails to read any change in value passed. As a result, if 2 is passed as the initial value and the value passed changes to 4 - the component is not allowing 4 decimals digits to be entered. 

**Expected behavior**
The change in value passed to the property should be read dynamically.

**Minimal reproduction of the problem with instructions**
1. Add an input field to define the precision.
2. The value entered in field (in step 1) to be passed as value to the [maxFractionDigits] of primeng <p-inputNumber> 
3. change the value in step 1 and observe how the component behaves

**What is the motivation / use case for changing the behavior?**
The precision for decimal input plays an important role. If this behaviour doesn't work properly - it'll have an impact on how decimal values are passed.

**Please tell us about your environment:**
Angular version: 9.1.15
primeng version: 9.0.5
browser: Chrome 95.0, Firefox 91.0
node: 12.21

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
