### ISSUE TITLE
InputGroup with AutoComplete Triggers Style with 1% Width

### ISSUE THREAD

**Issue by charleshall888** [primefaces/primeng#10852]
```
[X] bug report 
```

**Current behavior**
This code in the primeng.css is causing our auto-complete components to have a width of 1%.
```
.p-inputgroup .p-inputtext,
.p-fluid .p-inputgroup .p-inputtext,
.p-inputgroup .p-inputwrapper,
.p-inputgroup .p-inputwrapper > .p-component {
    flex: 1 1 auto;
    width: 1%;
}
```
![image](https://user-images.githubusercontent.com/47426470/141844021-9f585aad-7142-4c52-9dfe-e3a12199db97.png)

**Expected behavior**
I would expect that this style is supposed to be setting the width to 100%.
In previous versions of PrimeNG this was not being set to 1%.

**Minimal reproduction of the problem with instructions**
Place a p-inputgroup-addon next to a p-autoComplete inside of a p-inputgroup
```<div class="p-inputgroup">
    <span class="p-inputgroup-addon"><i class="pi pi-search"></i></span>
    <p-autoComplete> </p-autoComplete>
</div>
```

* **Angular version:** 13.0.2
* **PrimeNG version:** 13.0.0-rc.2

**Comment by AlbaSS18** [comment]
I have the same problem. Please, fixx it

**Comment by trytuna** [comment]
I am on version 13.3.2 but it's neither fixed nor does the workaround work. Any suggestions?

**Comment by mattlocker** [comment]
The bug applies also to p-dropdown when using it with p-inputgroup.
Please add both cases also to the demo page.

https://primefaces.org/primeng/inputgroup

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by gbarrionuevo** [comment]
this is still happening

**Comment by antoniobuyukluev** [comment]
@mertsincan still reproducible in 18.0.0

**Comment by Medioman92** [comment]
still a bug in 19, not that anybody at @primetek cares

**Comment by AlejandroFlorin** [comment]
This is still an issue for v19. It should be marked as open.  The workaround for v19 is to wrap the autocomplete in a div with class="w-full" (if using their flexbox css) or style="width: 100%". Setting the width to 100% using the styleClass and inputStyleClass on the autocomplete does not work.

There is a smilar issue with a dropdown in the input group if the dropdown has filter turned on. This css as a global fixes that issue:

.p-inputgroup .p-inputtext {
    width:100% !important;
}
