### ISSUE TITLE
We need to Add Extra Functionality in p-calendar Component

### ISSUE THREAD

**Issue by kevalpanchalHops** [primefaces/primeng#10868]
**Current behavior**
We need to add Some Extra Functionality for Our Project in p-calendar Component in Range
Example 
We need to add Button In Range Functionality 
Like
Today 
Yester Day
Last 7 Days
![image](https://user-images.githubusercontent.com/53170073/142862611-a9aad06a-24c3-49c3-b5f6-2b46504eaef1.png)

**Issue**
Currently we have no option to Modify Picker
or We got no Component of actual p-calendar

**Expected behavior**
Some How if we got Component of p-calendar or we have something that help to Modify p-calendar

**Please tell us about your environment:**
Windows 10

* **Angular version:** 11

* **PrimeNG version:** 11.1.0

* **Browser:** all

 
* **Language:** TypeScript

* **Node (for AoT issues):** `node --version` =   14.5.0

**Comment by yigitfindikli** [comment]
Issue is not clear. Please feel free to create a new ticket with a detailed explanation and example.
