### ISSUE TITLE
ListBox with shift select

### ISSUE THREAD

**Issue by giesmininkas** [primefaces/primeng#10867]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Expected Behaviour**:
It would be nice to be able to select multiple items at once with shift key like in Table component. 

**Current Behaviour**:
Shift key is ignored.

**Angular version**: 12.X
**PrimeNG version**: 12.2.1

**Comment by chao813** [comment]
@yigitfindikli Would love to tackle this, but I'm not sure how to test the component after updating the code. How can this be done?

**Comment by giesmininkas** [comment]
Currently using this as a substitute:

`
import {Directive} from '@angular/core';
import {Listbox} from 'primeng/listbox';

@Directive({
  selector: '[appPrimeListMultiselect]'
})
export class PrimeListMultiselectDirective {
  lastSelected?: any;
  lastShiftSelected?: any;
  selected: any[] = [];

  constructor(private list: Listbox) {
    list.onClick.subscribe((event: any) => this.onClick(event));
  }

  onClick(event: any): void {
    const allOptions = this.list.options;
    const dataKey = this.list.dataKey ?? this.list.optionLabel;

    const option = event.option;
    const pointerEvent: PointerEvent = event.originalEvent;

    if (allOptions.findIndex(value => value[dataKey] === option[dataKey]) == -1) {
      return;
    }

    if (!pointerEvent.ctrlKey && !pointerEvent.shiftKey) {
      this.selected = [option];
      this.lastSelected = option;


      this.list.writeValue(this.selected);
      this.lastSelected = option;
      this.lastShiftSelected = null;
    }

    if (pointerEvent.ctrlKey && !pointerEvent.shiftKey) {
      const index = this.selected.findIndex(value => value[dataKey] === option[dataKey]);
      if (index != -1) {
        this.selected.splice(index, 1);
        this.lastSelected = null;
      } else {
        this.selected.push(option);
        this.lastSelected = option;
      }

      this.list.writeValue(this.selected);
      this.lastShiftSelected = null;
    }

    if (!pointerEvent.ctrlKey && pointerEvent.shiftKey) {
      if (!this.lastSelected) {
        const index = this.selected.findIndex(value => value[dataKey] === option[dataKey]);
        if (index === -1) {
          this.selected.push(option);
          this.list.writeValue(this.selected);
        }

        this.lastSelected = option;
        this.lastShiftSelected = null;
      } else {
        if (this.lastShiftSelected) {
          let firstIndex = allOptions.findIndex(value => value[dataKey] === this.lastSelected[dataKey]);
          let lastIndex = allOptions.findIndex(value => value[dataKey] === this.lastShiftSelected[dataKey])

          if (firstIndex > lastIndex) {
            const tmp = firstIndex;
            firstIndex = lastIndex;
            lastIndex = tmp;
          }

          const itemsToUnselect = allOptions.slice(firstIndex, lastIndex + 1);
          this.selected = this.selected.filter(value => itemsToUnselect.findIndex(item => item[dataKey] === value[dataKey]) === -1);
        }

        let firstIndex = allOptions.findIndex(value => value[dataKey] === this.lastSelected[dataKey]);
        let lastIndex = allOptions.findIndex(value => value[dataKey] === option[dataKey]);

        if (firstIndex > lastIndex) {
          const tmp = firstIndex;
          firstIndex = lastIndex;
          lastIndex = tmp;
        }

        this.selected.push(...allOptions.slice(firstIndex, lastIndex + 1));
        this.selected = this.selected.filter((v, i, a) => a.indexOf(v) === i);

        this.list.writeValue(this.selected);
        this.lastShiftSelected = option;
      }
    }
  }
}
`

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
