### ISSUE TITLE
Question: Can I use Material UI and PrimeNG together?

### ISSUE THREAD

**Issue by kchojhu** [primefaces/primeng#10865]
I understand that ideally we want to just use one but getting rid of Material UI on existing code is out of the question (at this point).  Is there a way we can integrate with PrimeNG as well? I imagine if there's a way to generate PrimeNG with it's own CSS namespace then I'm guessing there shouldn't be any collisions.  Any feedback (or hope) would be very much appreciated!

**Comment by yigitfindikli** [comment]
Please use the forum or discord channel for questions and help requests.
