### ISSUE TITLE
readonly not working on p-inputNumber

### ISSUE THREAD

**Issue by ewuillai** [primefaces/primeng#10866]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When [readonly]="true" on p-inputText, the cursor is no more visible but the value stays modifiable.

**Expected behavior**
The value should not be modifiable.

**Minimal reproduction of the problem with instructions**

1. Open stackblitz on p-inputNumber page (https://www.primefaces.org/primeng/showcase/#/inputnumber), then:
2. Select app.component.html in the project explorer,
3. Add following attribute on the first p-inputNumber: [readonly]="true",
4. Click on the corresponding input field in the demo page,
5. The cursor does not appear, but the value can be modified.

**Please tell us about your environment:**
* **Angular version:** 12.2.12 (12.0.5 in stackbliz)

* **PrimeNG version:** 12.2.2

* **Browser:** Chrome / Firefox / Electron 12 (Chromium)
 
* **Language:** TypeScript 4.3.5

**Comment by panos-el** [comment]
I have the same problem

**Comment by chao813** [comment]
Could it be that the type attribute (`type=number`) is missing in the input tag in [inputnumber.ts]?(https://github.com/primefaces/primeng/blob/c60b65588d78ba3ca92be052595ff3d6eb8e11ae/src/app/components/inputnumber/inputnumber.ts#L19)
