### ISSUE TITLE
Responsive table breaking changes in v12

### ISSUE THREAD

**Issue by tigrenok00** [primefaces/primeng#10869]
Hi,

In version 12.2.2 there are some breaking changes caused by media queries to hide certain columns of the table and breaking table design and structure, for example:

```
 @media screen and (max-width: 960px) {
   #pr_id_3 .p-datatable-thead > tr > th,
   #pr_id_3 .p-datatable-tfoot > tr > td {
    display: none !important;
   }
```

We have our own media queries to support table structure for different devices based on older ui-p-1/ui-p-7 classes at th/td level.
I had to downgrade to primeng 11.4.5 after upgrading to 12 because it broke the table on mobile screens.
Please let me know the new media query classes you use so I could override them and reverse the new behavior, or is there a p-table parameter which would disregard any default responsive behavior so our old custom styling would continue working?
Thanks

**Comment by yigitfindikli** [comment]
Hi,
You need to override them or you can use our new responsive options;

https://www.primefaces.org/primeng/v12/#/table/responsive
https://www.primefaces.org/primeng/showcase/#/table/responsive

**Comment by tigrenok00** [comment]
@yigitfindikli I want to override them because we need to keep current behavior as it is the client UI design, the responsive options are not the same.
Where can I see the list of the media query classes you used so I can know what to override? It is really difficult to guess them as the display is none...
