### ISSUE TITLE
p-overlayPanel places dialogue far below button used for invokation

### ISSUE THREAD

**Issue by st-clair-clarke** [primefaces/primeng#1086]
Hi,
I posted this at the forum on  06 Oct 2016, 17:16 [http://forum.primefaces.org/viewtopic.php?f=42&t=47508](http://forum.primefaces.org/viewtopic.php?f=42&t=47508). However there has been no response from anyone. I did purchase this software mainly becuase the p-overlay-panel would be the workhorse of my application. To have an issue not sorted out for so long is rather unexpected.

Using windows 10, angular-cli

I have the following code:

**race-component.ts**
`import { Component, OnInit } from '@angular/core'
import {
    FormBuilder, FormGroup, AbstractControl
} from '@angular/forms'

import 'rxjs/add/operator/debounceTime'
import { Race } from '../race/'

@Component(
    {
      selector: 'epimss-race',
      templateUrl: './race.component.html',
      styleUrls: [ './race.component.scss' ]
    } )
export class RaceComponent implements OnInit {
  race: Race;
  btnIcon: string = 'ui-icon-error-outline';

  form: FormGroup;
  rase: AbstractControl;
  ethnicGroup: AbstractControl;

  constructor( private _fb: FormBuilder ) {
    this.race = new Race();

```
this.form = this._fb.group(
    {
      'rase': [ ''],
      'ethnicGroup': [ '' ]
    } );

this.rase = this.form.controls[ 'rase' ]
this.ethnicGroup = this.form.controls[ 'ethnicGroup' ]
```

  }

  ngOnInit() {
    this.form.statusChanges
        .debounceTime( 500 )
        .subscribe(
            status => {
              switch ( status ) {
                case 'VALID':
                  this.btnIcon = 'ui-icon-check';
                  break;

```
            case 'INVALID':
              // this.payload ); TODO => review error when line is                uncommented
              this.btnIcon = 'ui-icon-error-outline';
              break
          }
        } )
```

  }

  }
}
`

**race-component.html**
`<button
    [icon] = 'btnIcon'
    type = 'text'
    pButton
    label = 'Race'
    iconPos = 'right'
    (click) = 'op.show($event)'></button>

<p-overlayPanel
    #op
    [dismissable] = 'false'
    [showCloseIcon] = 'true'>

  <div
      class = 'card card-w-title shadow-box ui-shadow-5'>
    <h2>Race</h2>
    {{diagnostic}}
    <epimss-separator></epimss-separator>
    <form
        novalidate
        autocomplete = 'off'
        [formGroup] = 'form'>

```
  <div
      layout = 'column'
      layout-align = 'start start'>
    <section>
      <md-input
          required
          placeholder = 'Race'
          [(ngModel)] = 'race.race'
          formControlName = 'rase'></md-input>
    </section>

    <section>
      <md-input placeholder = 'EthnicGroup'
                [(ngModel)] = 'race.ethnicGroup'
                formControlName = 'ethnicGroup'></md-input>
    </section>
  </div>
  <epimss-separator></epimss-separator>
  <epimss-reset-button
      [formm] = 'form'></epimss-reset-button>
</form>
```

  </div>
</p-overlayPanel>

`
I have two problems
1. The UI does not display as expected - see image
![race](https://cloud.githubusercontent.com/assets/3227590/19562878/9c69f406-96a3-11e6-8488-377b204218e8.jpg)

The UI is not immediately under the button as expected.
1. How can I dynamically change the icon on the button. It does not change when the UI content becomes valid ( validation data has been removed)

Thanks

**Comment by st-clair-clarke** [comment]
Some attention please support!

**Comment by karthiks3000** [comment]
+1

**Comment by cagataycivici** [comment]
Please provide a plunkr to help us replicate and we'll review again. Right now issue is not clear on our side. You may use;

http://plnkr.co/edit/VZbdZfQ7SuTV87tTkbYR?p=preview
