### ISSUE TITLE
Table sorting/filtering does not work on smaller screens (stack mode)

### ISSUE THREAD

**Issue by ThomasPrikrylBE** [primefaces/primeng#10877]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
This is the standard table filter stackblitz from the demo page - no changes:
https://stackblitz.com/edit/primeng-tablefilter-demo

**Current behavior**
Currently filters only work on smaller screens if the table is using responsiveLayout="scroll". However while using "stack" all the p-columnfilter elements vanish and filtering/sorting is not possible anymore.

**Expected behavior**
The column filters are still visible at the top or change to a dialog based mode or something like that.

**Minimal reproduction of the problem with instructions**
Just use the default stackblitz provided above, make the window a bit smaller, till the input filters disappear and things change to the mobile mode. Then filtering seems to be impossible.

**What is the motivation / use case for changing the behavior?**
I would like to be able to use sorting and filtering on mobile devices, preferably the same/a similar way as on desktop.

* **Angular version:** 12.x

* **PrimeNG version:** 12.x

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
