### ISSUE TITLE
Tabview 13.0.0-rc.2 multiline layout broken

### ISSUE THREAD

**Issue by rekna1** [primefaces/primeng#10879]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Previous behaviour, tab items wrap on next line
![image](https://user-images.githubusercontent.com/739942/143194996-87a66e70-476a-4007-befa-862788158be7.png)

**Current behavior**
Wrapping is broken
![image](https://user-images.githubusercontent.com/739942/143195179-eb165495-dfb6-441a-8e7c-82088f1113bf.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/739942/143194996-87a66e70-476a-4007-befa-862788158be7.png)

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
Tabs should wrap like before

**Please tell us about your environment:**
windows 10

* **Angular version:** 5.X
angular 13.0.1

* **PrimeNG version:** 5.X
primeng 13.0.0-rc.2
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome, firefox, edge
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript

* **Node (for AoT issues):** `node --version` =

**Comment by rekna1** [comment]
Apparently in the previous version:

```
.p-tabmenu-nav {
    display: flex;
    flex-wrap: wrap;
```
And in the current version:    
```
.p-tabmenu-nav {
    display: flex;
    flex-wrap: nowrap;
}    
```

**Comment by rekna1** [comment]
Also, it seems overflow-x is set to auto on 

`<div class="p-tabmenu p-component">`

previous it overflow-x:visible

This causes the box-shadow of focused / active element to be cut off if it overlaps another element (in my case padding of containing element) (don't bother the rectangle on the label , which is from inspecting)
![image](https://user-images.githubusercontent.com/739942/143315533-1242f305-94c5-41ba-934f-fd32e91c9188.png)

![image](https://user-images.githubusercontent.com/739942/143315568-9e079647-9e18-400a-8823-2e06ff8bcc96.png)

**Comment by waratah** [comment]
This is definitely a bug.

Adding 

```
.p-tabview-nav {
    flex-flow: wrap;
}
```

Will work around the problem if you don't want to mix scrollable and non scrollable.

**Comment by cetincakiroglu** [comment]
Hi, 

Since there is a scrollable option for the tabview component, you don't need to use flex-wrap to display all tabs. You can check it from the link below.

[Tabview demo with scrollable](https://stackblitz.com/edit/primeng-tabview-demo-tncvz8?file=src%2Fapp%2Fapp.component.html
)
If you still want to display tabs as wrapped. You can use these styles in your stylesheet or *component.ts.

`
:host ::ng-deep .p-tabview{

    .p-tabview-nav-content{
        overflow: hidden;

        .p-tabview-nav {
            flex-wrap: wrap;

            .p-tabview-nav-link{
                margin-top:2px;
            }
        }
    }
}
`

**Comment by rekna1** [comment]
@cetincakiroglu I don't like the usability of scrollable tabs. Libraries shouldn't make breaking changes unless there is a real good reason for it... it's not for me to decide of course... at least I have a way to correct it in css
