### ISSUE TITLE
interactive cell edit mode (prevent switching to view mode)

### ISSUE THREAD

**Issue by keyone2693z** [primefaces/primeng#10876]
AS you can see here user will click on the daytime picker

![123123123](https://user-images.githubusercontent.com/85094404/142997602-0840ad34-1144-49ac-aa1d-a70fdc84362e.PNG)

then the user should choose the date but it will close the edit mode and before getting the data it is switching to view mode

![2222](https://user-images.githubusercontent.com/85094404/142997746-48e54f39-c77e-4cdd-ac00-4a9dfb7eb1c3.PNG)

**Comment by yigitfindikli** [comment]
Issue is not clear.

**Comment by keyone2693z** [comment]
> The issue is not clear.

you see the input is a DateTime picker so the edit mode will be closed on any click outside of the input right?
that's why when I'm going to pick a date from the opened daytime picker it actually thinks I clicked outs side the input and goes to view mode instead of waiting for me to choose the date and close it my self, and then click somewhere to close the edit mode

**Comment by keyone2693z** [comment]
؟
