### ISSUE TITLE
dynamicdialog keyboard navigation is not working in Internet explorer (Throwing console error).

### ISSUE THREAD

**Issue by avsrinivasa** [primefaces/primeng#10874]
When we open dynamic dialog using this URL : https://www.primefaces.org/primeng/v12/#/dynamicdialog in internet explorer and press tab we see below error in console

SCRIPT5022: SyntaxError
polyfills-es5.58f8aca2f0d758bc6f45.js (1,10563)

Can you please fix this issue?
Thanks in advance.

**Comment by yigitfindikli** [comment]
IE11 support is deprecated.
