### ISSUE TITLE
p-autocomplete highlight the selected item under dropdown

### ISSUE THREAD

**Issue by chaitrashenoy33** [primefaces/primeng#10870]
highlight the the item which is selected in dropdown of p-autocomplete

**Current behavior**
it doesnot highlight the item which is  selected from the dropdown

**Expected behavior**
the selected data should be highlighted in the dropdown

Please tell us about your environment:
Windows 10

Angular version:
Angular 11

PrimeNG version:
Primeng 9

Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

Language: [all | TypeScript X.X | ES6/7 | ES5]

Node (for AoT issues): node --version = 12.18

**Comment by yigitfindikli** [comment]
Unable to replicate with latest PrimeNG, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
