### ISSUE TITLE
p-calendar Multiple Months visible range / maxDate enhancements

### ISSUE THREAD

**Issue by nilsm0hr** [primefaces/primeng#10871]
[ ] bug report => Search github for a similar issue or PR before submitting
[ x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Current behavior**
In the current p-calendar module, I display multiple months with the range enabled. By default, I would like to display 2 months, and select the last 15 days as the selected range. I also set the maxDate to tomorrow, to prevent the user from selecting any future dates. 

If the two weeks are all in the current month, the p-calendar displays the current and next month. However the most of the dates are not selectable for my usecase.

![Display range on calendar with 2 months and 14 days selected](https://user-images.githubusercontent.com/25453204/142877789-aef5b5e4-0a9d-45c0-9c55-38e2c41862b9.png)

**Expected behavior**
I would like to have an option to define in which the calendar months are looking. Current behaviour could be _future_ and my desired behaviour would be _past_. This would allow me to configure p-calendar to display the previous and current month, rather than the current and next month. 

**What is the motivation / use case for changing the behavior?**
This enhancement would improve the usability of the Multiple Months feature, as it would permit per-selections. 

* **Angular version:** 13

* **PrimeNG version:** 13.0.0-rc.2

* **Browser:** all

**Comment by jonnomk** [comment]
I actually tried to implement this in a custom date range picker using the PrimeNG calendar and thought I had done successfully until you update the model programmatically and the createMonths method in the calendar reverts the 'extra' months as months in the future, even though they are set as not selectable using maxDate property.

Having the ability to define multiple months in the past or future would be a great improvement.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by jeweljacob387** [comment]
This issue is not resolved yet. When `[numberOfMonths]="2"` the right section always shows the next month. 

![Image](https://github.com/user-attachments/assets/8836de1e-314a-4412-aadd-c03c35b55414)

It would be better to give a provision for the `monthInView` or `defaultDate` for range selection also
