### ISSUE TITLE
could it possible to make p-colorPicker readonly?

### ISSUE THREAD

**Issue by KeithPoonNS** [primefaces/primeng#10878]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**

```
<input type="text" readonly="readonly" disabled="disabled"
class="p-colorpicker-preview p-inputtext" 
[style.background-color]="item.color">
```

**Expected behavior**

```
<p-colorPicker [(ngModel)]="..." readonly></p-colorPicker>
```

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

i use p-table for display the data set, i want to use color to present the approval status.
hope p-colorPicker would have something just like readonly in inputText or readonlyInput in p-calendar

**Please tell us about your environment:**

* **Angular version:** 12.0.2

* **PrimeNG version:** 12.2.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] Chrome 96.*

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5] TypeScript 4.2.4

* **Node (for AoT issues):** `node --version` =

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
