### ISSUE TITLE
We need to Add Extra Functionality in p-calendar Component

### ISSUE THREAD

**Issue by kevalForever** [primefaces/primeng#10875]
**Current behavior**
We need to add Some Extra Functionality for Our Project in p-calendar Component in Range
Example 
We need to add Button In Range Functionality 
Like
Today 
Yester Day
Last 7 Days
![image](https://user-images.githubusercontent.com/53170073/142996365-188cca5a-e005-4763-a50e-4be6953127c8.png)

if I Click **Today** then its Change to Current Day.
if I Click **Last 7 Days** than its Change to 16/11/2021 to 22/11/2021

**We Want This Type of Functionality in our Project**

**Issue**
Currently we have no option to Modify Picker
or We got no Component of actual p-calendar

**Expected behavior**
Some How if we got Component of p-calendar or we have something that help to Modify p-calendar

**Please tell us about your environment:**
Windows 10

* **Angular version:** 11

* **PrimeNG version:** 11.1.0

* **Browser:** all

 
* **Language:** TypeScript

* **Node (for AoT issues):** `node --version` =   14.5.0

**Comment by kevalForever** [comment]
@yigitfindikli  Its not issue in api But I need Component Object to Override Our new Functionality. That's i want to do.
if you have any thing to How can i do this than help me

**Comment by tburger** [comment]
This is not very difficult to do now with what they have provided Here is an image of a custom calendar control we have created out of the existing calendar control with just a few enhancments.
![image](https://user-images.githubusercontent.com/629105/144316553-6c39104f-bfaf-44ff-9cbf-e9073fca2147.png)

**Comment by kevalForever** [comment]
@tburger I am interested to Make Custom Calendar. 
Can you Please Share your Source Code.

**Comment by mbshingala28** [comment]
@tburger I am also interested to Make Custom Calendar.
Can you Please Share your Source Code?

**Comment by tburger** [comment]
[date-range-picker.zip](https://github.com/primefaces/primeng/files/8114392/date-range-picker.zip)

**Comment by mbshingala28** [comment]
@tburger Thank you.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
