### ISSUE TITLE
Error with the BlockUI, lock all document

### ISSUE THREAD

**Issue by jncalderon** [primefaces/primeng#10872]
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-c294wk?file=src/app/app.component.html

**Current behavior**
The problem is that block all document and not destroy when change the variable 

**Expected behavior**
Block only the panel, and when click on the button unblock then destroy the BlockIU

**Minimal reproduction of the problem with instructions**
Click on button block

* **Angular version:**  12.0.3

* **PrimeNG version:** 13.0.0-rc.2

**Comment by yigitfindikli** [comment]
Hi,

Actually, it's working correctly. But your stackblitz configuration is wrong. You need to hit the Enable Ivy checkbox from settings. 

I updated your example; https://stackblitz.com/edit/github-c294wk-dqqlvy?file=angular.json

And you can try our demos;

https://www.primefaces.org/primeng/v12/#/blockui
https://www.primefaces.org/primeng/showcase/#/blockui

**Comment by jncalderon** [comment]
@yigitfindikli what u refer with "Enable Ivy checkbox from settings" ? I review my example but not have changes and continues the issue

**Comment by klafbang** [comment]
I encountered issues with the component as well.  It was caused due to using a custom theme and not the PrimeNG themes after 12.2.1.  This release made the behavior of BlockUI crucially depend on CSS animations.  Without an animation, the BlockUI does not disappear.

IMO, this would be good to document, especially singe this is a quite substantial change in a minor version.

**Comment by jncalderon** [comment]
@klafbang thanks, you are right, I'm using MirageNG, have any idea how solve it?

**Comment by klafbang** [comment]
You need to have some leave animation, pretty much ay will do.  From one of the PrimeNG themes, you can add the below to your CSS:

`
.p-component-overlay {
	background-color: rgba(0, 0, 0, 0.4);
	transition-duration: 0.15s;
}

.p-component-overlay-enter {
	animation: p-component-overlay-enter-animation 150ms forwards;
}

.p-component-overlay-leave {
	animation: p-component-overlay-leave-animation 150ms forwards;
}

@keyframes p-component-overlay-enter-animation {
	from {
		background-color: transparent;
	}

	to {
		background-color: rgba(0, 0, 0, 0.4);
	}
}

@keyframes p-component-overlay-leave-animation {
	from {
		background-color: rgba(0, 0, 0, 0.4);
	}

	to {
		background-color: transparent;
	}
}
`

The enter animation can likely be ignored and you can change the animation/background-color if you prefer (it will possibly break if you reduce the duration to 0s).

**Comment by jncalderon** [comment]
@klafbang thanks is working!!!

**Comment by yigitfindikli** [comment]
Hi @jncalderon,

For templates, you need to update your designer folder. You can download it from https://primefaces.org/store. You didn't mention MirageNG so I just fix your stackblitz example.

Regards.

**Comment by jncalderon** [comment]
@yigitfindikli sorry for that, my bad.

I not update my assets folders because MirageNG rollback the theme selector, I don't like it.

I use the css in the last comment and works for me!

Thanks!
