### ISSUE TITLE
ToolTip for disabled Tab-Panel

### ISSUE THREAD

**Issue by MitkoMKD** [primefaces/primeng#10885]
Hi Prime-ng team,

First of all, thanks for a wonderful open-source and free component library. I have been using the library for few months.
But i need small help please.

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
Tool tip on a disabled tab panel does not work. I do not know if is a bug or not. But a need tooltip to show on hover on disabled tabPanel.

<p-tabPanel header="Deals"  tooltip="Assign the Brand to an affiliate program to be able to add deals" [disabled]="!alreadySelectedProgramFlag"  tooltipPosition="top" showDelay="1000">
            <ng-template pTemplate="content" >
                <app-deals-tab [showCreateDealPage]="false" [affiliateProgramId]="brand.affiliateProgramId"
                    [brandDealsForms]="brandsDealsForm" [brandId]="brand.id"></app-deals-tab>
            </ng-template></p-tabPanel>

**Expected behavior**
When a mouse hovers over the disabled tab header, the tooltip should appear. Or tell me workaround solution. 

* **Angular version:** 12.2.10

* **PrimeNG version:** 12.2.1

**Comment by yigitfindikli** [comment]
This is the behavior of p-disabled which is expected. You can override pointer-events like this:

```
:host ::ng-deep .p-disabled a {
    pointer-events: auto;
}
```

**Comment by MitkoMKD** [comment]
@yigitfindikli  thank you a lot :)
