### ISSUE TITLE
readonly not working on p-calendar

### ISSUE THREAD

**Issue by panos-el** [primefaces/primeng#10880]
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Current behavior**
When [readonly]="true" on p-inputText, the cursor is no more visible but the value stays modifiable.

**Expected behavior**
The value should not be modifiable.

**Please tell us about your environment:**
Angular version: 12.2.0
PrimeNG version: 12.2.1
Browser: Chrome
Language: TypeScript 4.3.5

**Comment by yigitfindikli** [comment]
The calendar component doesn't have readonly property. You need to use **readonlyInput**.

**Comment by panos-el** [comment]
I think when readonlyInput is true must be showOnFocus false
