### ISSUE TITLE
Multisel

### ISSUE THREAD

**Issue by CorentinPacaud** [primefaces/primeng#10889]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request
```

**Plunkr Case (Bug Reports)**
`<h5>Basic</h5>
<p-multiSelect [options]="cities" [(ngModel)]="selectedCities1" defaultLabel="Select a City" optionLabel="name">
	<ng-template let-items pTemplate="selectedItems">
<span
	*ngFor="let item of items"> item
</span>
</ng-template>
<ng-template pTemplate="empty">Sélectionner des restrictions</ng-template>
</p-multiSelect>
`

**Current behavior**
defaultLabel (tested with placeholder too) doesn't work when we add a <ng-template let-items pTemplate="selectedItems">

**Expected behavior**
placeholder (or defaultLabel) should be visible if no items are selected.

* **Angular version:** 5.X
Angular 12.2.7

* **PrimeNG version:** 5.X
PrimeNG 12.X.X, 13.0.0

* **Browser:** [Chrome XX  ]

**Comment by yigitfindikli** [comment]
Please see the docs;

>  defaultLabel: Label to display when there are no selections. Deprecated: Use placeholder instead.

**Comment by yigitfindikli** [comment]
Yes, this is expected. When you use the selectedItems template you need to create a placeholder yourself(If you want it of course).
