### ISSUE TITLE
Prime Blocks not working with Angular 13 and Ultima 11.0.11

### ISSUE THREAD

**Issue by kunalbackers** [primefaces/primeng#10881]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

We are trying to include the prime blocks hero code snippet for a page on our website.
**Please tell us about your environment:**

Angular CLI and Angular 12.2.13 
* **Angular version:** 5.X

12.2.13
* **PrimeNG version:** 5.X

 "pdfmake": "^0.2.2",
    "primeflex": "2.0.0",
    "primeicons": "4.1.0",
    "primeng": "^12.2.2",
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   
* Node 14.16.1

**Comment by yigitfindikli** [comment]
Ultime v11 is compatible with PrimeNG v11 and Angular v11.

**Comment by kunalbackers** [comment]
we came to the conclusion that we would need to update everything.
