### ISSUE TITLE
display: grid breaks responsiveness of p-table

### ISSUE THREAD

**Issue by dannybucks** [primefaces/primeng#10888]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/primeng-tableresponsive-demo-benuuw?file=src%2Fapp%2Fapp.component.html

**Current behavior**
As soon as I put 'style="display: grid; grid-template-columns: 200px auto;"' in the div at the very top, the table looses responsiveness: the scrollbar goes over the whole window instead of just the table like without display: grid.

**Expected behavior**
The table should be responsive with display grid too!

**What is the motivation / use case for changing the behavior?**
Is this a bug or am I missing something?

**Please tell us about your environment:**

* **Angular version:** 12.x

* **PrimeNG version:** 12.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All

**Comment by ninjavis** [comment]
I have the same issue.

Our layout in our project is built using CSS grid.
As soon as we render the latest primeng table ( v13 ) inside a router outlet in the 'view' area of our layout, it pushes the entire table way off to the right of the screen. We are then unable to see the right hand navigation menu.

**Comment by ninjavis** [comment]
@dannybucks I have something you can try. It's a bit of a hack.
I played around on your stackblitz example.

In your CSS file add:
.p-datatable.p-datatable-responsive{ max-width: calc( 100vw - 300px ); }

So in our project, I currently use:

<div style="display:grid;grid-template-columns: 1fr auto">
  <div style="max-width:calc( 100vw - 400px )">
    <router-outlet></router-outlet>
  </div>
  <app-right-sidebar-nav></app-right-sidebar-nav>
</div>

**Comment by waratah** [comment]
> @dannybucks I have something you can try. It's a bit of a hack. I played around on your stackblitz example.
> 
> In your CSS file add: .p-datatable.p-datatable-responsive{ max-width: calc( 100vw - 300px ); }
> 
> So in our project, I currently use:
> 
> `
> 
> ` EDIT: Doesn't seem like I am able to paste HTML here

use triple quotes to put code into your answer.

**Comment by waratah** [comment]
Am I missing something.   When I tweak your grid to 

```<div style="display: grid; grid-template-columns: 200px 350px">```

I get scroll bars I expect.

**Comment by ninjavis** [comment]
@waratah yes, that will work for a fixed width container. But we need a responsive layout, hence 'auto'. That is when the contents of the auto column overflows outside of the viewport

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by ilmoralito** [comment]
Hello. I am experiencing this same behavior in a project using version `16`. Is there a workaround to achieve this? Thanks
