### ISSUE TITLE
Editor bug collection for version 13.0.0

### ISSUE THREAD

**Issue by DwieDima** [primefaces/primeng#10883]
**Current behavior**

- The editor can still be edited if disabled is true (using reactive forms and when [disabled]="true" is set directly inside HTML).
- The Editor doesn't display invalid state using reactive forms, like other inputs (no red border).
- Using the modules attribute results in UI Bug `[modules]="quillModules"` (see image)

HTML:
```
        <p-editor
          formControlName="descriptionShort"
          [style]="{ height: '150px' }"
          [modules]="quillModules"
        >
        </p-editor>

```
TS:
```
  public quillModules = {
    toolbar: [
      ["bold", "italic", "underline", "strike"],
      [{ list: "ordered" }, { list: "bullet" }],
      [{ color: [] }, { background: [] }],
      [{ indent: "-1" }, { indent: "+1" }],
      ["clean"]
    ]
  };
```
Result:

![image](https://user-images.githubusercontent.com/26873275/143449121-a74107f8-d063-4392-8675-0b552f7a66eb.png)

**Expected behavior**

- Editor is disabled when disabled state is true for reactive and declarative form
- Editor has red border when invalid using reactive and declarative form
- Providing the modules attribute shouldn't display all options over the component (see image)

* **Angular version:** ^13.0.1

* **PrimeNG version:** ^13.0.0

* **Browser:** Chrome

**Comment by davidboothe** [comment]
For the bug with the toolbars, you can work around it by providing an empty header template
`<ng-template pTemplate="header"></ng-template>`

then you can provide your toolbar config in the `modules` property

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
