### ISSUE TITLE
Schedule eventRender issue

### ISSUE THREAD

**Issue by vacarsu** [primefaces/primeng#1089]
The full calendar documentation says the eventRender function should pass the event that is being rendered to the function. This doesn't seem to be the case in the Schedule attribute. logging event variable produces undefined.

``` html
<p-schedule *ngIf="events"
              [events]="events"
              [header]="header"
              [editable]="true"
              [eventRender]="eventRender(event)"
              (onDayClick)="handleDayClick($event)"
              (onEventClick)="handleEventClick($event)">
</p-schedule>
```

``` javascript
eventRender(event) {
    console.log(event);
}
```

**Comment by panto** [comment]
Just try:

```
<p-schedule [eventRender]="eventRender"></p-schedule>
```

```
eventRender(event, element, view) {
  console.log(event, element, view);
}
```

**Comment by sudheerj** [comment]
The above syntax is proper to invoke full-calendar functions. Hence this is not the issue.

**Comment by prairieapps** [comment]
Is there anyway to access component variables from within this eventRender(event,element,view) function? In my case, "this" is the function scope.
