### ISSUE TITLE
Documentation - Section Locale with wrong configuration

### ISSUE THREAD

**Issue by ropoko** [primefaces/primeng#10892]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

In the documentation (v11-LTS) in "Locale" section, when calling the translate service in the app component, it calls the service with wrong arguments:
![image](https://user-images.githubusercontent.com/49417432/143859887-6e62174a-30a6-4aa2-8d34-263c253065ac.png)

It should be just "primeng", like in the json file:
![image](https://user-images.githubusercontent.com/49417432/143859960-a9990acb-799e-4784-992d-f36b9b99ec3c.png)

**Comment by yigitfindikli** [comment]
Hi @ropoko,

Thanks for your report. Will be fixed in the next lts release.
