### ISSUE TITLE
version : 12.2.3 not found 

### ISSUE THREAD

**Issue by Inaamgharbi** [primefaces/primeng#10898]
I try to make a frozen column, but my js throws an error . It says it cannot resolve the style property ; (frozen column cannot read properties of undefined (reading 'style') at frozen column.update sticky position) The Error message look like this : Uncaught TypeError: Cannot read property 'style' of undefined

 npm ERR! code ETARGET npm ERR! notarget No matching version found for primeng@12.2.3. 
I hope someone can help me
Please tell us about your environment:

Angular version: 12 
Windows 10 Pro, VSCode

PrimeNG version: 11

Browser: all

Language: TypeScript

**Comment by Inaamgharbi** [comment]
npm ERR! code ETARGET
npm ERR! notarget No matching version found for primeng@12.2.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by yigitfindikli** [comment]
Hi @Inaamgharbi,
Because it is not released yet. This week will be released.

**Comment by Inaamgharbi** [comment]
thnx @yigitfindikli
