### ISSUE TITLE
MegaMenu to support deeper than 2 levels

### ISSUE THREAD

**Issue by LouieTian0209** [primefaces/primeng#10891]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
MegaMenu is only taking first two levels of MegaMenuItem and MenuItem into consideration. Any sub MenuItem deeper won't take effect.

**Expected behavior**
Sub MenuItem deeper than level 2 should be able to be collapsed and folded by clicking its parent MenuItem with a larger indentation indicating their depths. See an example below.
![2021-11-29_18-52](https://user-images.githubusercontent.com/53802606/143855383-f6b79104-9d5a-4bad-ac62-f3447035ddd4.png)

**What is the motivation / use case for changing the behavior?**
With this change the MegaMenu will be more versatile and flexible.

**Please tell us about your environment:**

* **Angular version:** 11.X

* **PrimeNG version:** 11.X

* **Browser:** [all]

 
* **Language:** [TypeScript 4.1.5]

* **Node (for AoT issues):** `node --version` =   12.22.1

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by majkers** [comment]
@LouieTian0209 can You please verify it in 14.2.1?

**Comment by LouieTian0209** [comment]
> @LouieTian0209 can You please verify it in 14.2.1?

Thanks for the update! The project now has been on hold for further development for a while and I'm quite busy with other projects so I probably won't get back on this right now. I'll get it tested and report my feedback as soon as I'm available. Thanks!

**Comment by majkers** [comment]
@mertsincan I can confirm that there is still no support for it. Test project is not necessary because it is a feature request.
