### ISSUE TITLE
Can't programmatically show context menu

### ISSUE THREAD

**Issue by psarno** [primefaces/primeng#10901]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/github-ge5uqc?file=src/app/app.component.ts

**Current behavior**

The Stackblitz example is rendering strange (not sure why) but it gets the idea across.

I need to programmatically show the context menu when the user clicks an ellipsis icon in a p-menubar component.

```
    this.toolbarMenuItems = [{
      icon: 'pi pi-ellipsis-h',
      label: 'Show Context Menu',
      command: () => this.contextMenu.show()
    }];
```

contextMenu is a ViewChild:

`@ViewChild('cm') contextMenu: ContextMenu;`

**Expected behavior**

The context menu is shown when the `.show()` method is called.

**Minimal reproduction of the problem with instructions**

https://stackblitz.com/edit/github-ge5uqc?file=src/app/app.component.ts

**What is the motivation / use case for changing the behavior?**

I need to show a context menu programatically.

**Please tell us about your environment:**
Operating system: Windows 11
IDE: VS Code
package manager: npm

* **Angular version:** 
12.2.13

* **PrimeNG version:** 
12.2.2

* **Browser:** 

all
 
* **Language:** 

TypeScript 4.3.5
module: es2020
target: es2015

* **Node (for AoT issues):** 

12.16.1

**Comment by yigitfindikli** [comment]
Hi @psarno,

Try with;

```
command: () => {
        setTimeout(() => this.contextMenu.show(), 1)
}
```
