### ISSUE TITLE
AutoComplete :focused state does not extend border past the textbox element

### ISSUE THREAD

**Issue by acheven** [primefaces/primeng#10907]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
![image](https://user-images.githubusercontent.com/5826145/144302114-e892bceb-9562-4cc3-96c8-1698ce20f575.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/5826145/144302907-3d17dcde-6c8c-43c0-aaae-2a8a271847d2.png)

Need a little CSS tweak to extend :focus to include outer drop down arrow

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
