### ISSUE TITLE
FocusTrap is stealing the focus from dialog-content and setting to the first element.

### ISSUE THREAD

**Issue by AkshayPatil03** [primefaces/primeng#10900]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/angular-aggrid-pagination-clmoqz?file=src%2Fapp%2Fapp.component.html

**Current behavior**
The keyboard accessibility does not works as it works without primeng dialog for ag-grid table.
When focus is on content cell, on Tab it navigates to Header and on SHIFT+TAB it navigates to dialog footer.
We expect it to navigate to next element on Tab and previous element on SHIFT+TAB
This is happening due to [focusTrap]. 
It works as expected when 'focusTrap' is disabled but focus goes out of the dialog content after first or last element.(When focus is on HEADER, on SHIFT+TAB focus shifts to cancel button in attached example.)

**Expected behavior**
Keyboard accessibility should work as expected for dialog content with 'focusTrap' as well.
Focus should remain within dialog DOM element and for dialog-content(Ag-grid table) keyboard accessibility should also work as it works without 'focusTrap'. 

**Minimal reproduction of the problem with instructions**
1.In given example, click on 'Show' button it will launch a dialog and autofocus on diaolg Header.
https://stackblitz.com/edit/angular-aggrid-pagination-37dsak?file=src%2Fapp%2Fapp.component.html
2.Now use 'TAB' button to navigate to ag-grid table.
3.On first TAB it will navigate to first cell but on second TAB press it will focus on Dialog-Header.
4.Now try this same behaviour with disabling the 'focusTrap'.
https://stackblitz.com/edit/angular-aggrid-pagination-clmoqz?file=src%2Fapp%2Fapp.component.html

**What is the motivation / use case for changing the behavior?**
Keyboard Accessibility for dialog-content with FocusTrap.

**Please tell us about your environment:**
 Operating system: Windows 10

* **Angular version:** 5.X
 Angular 9.x

* **PrimeNG version:** 5.X
PrimeNG 11.4.5 but issues is reproducible on latest version.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by yigitfindikli** [comment]
This is expected because clearly, your table cell's not using tab index. TrapFocus is searching tabIndex or input elements. Your cells don't have a tab index. You need to use without trap focus feature.
