### ISSUE TITLE
AccordionTab with [selected] and <ng-template> working with unexpected behavior

### ISSUE THREAD

**Issue by DimaKomoff** [primefaces/primeng#10904]
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

https://stackblitz.com/edit/primeng-accordion-demo-zkbpe9?file=src%2Fapp%2Fapp.component.html

Current behavior
If use <p-accordionTab> with passing any [selected] property in conjunction with <ng-template pTemplate="header"> or <ng-template pTemplate="content"> content and header are not render. Probably is because your change in AccordionTab component in
```
    set selected(val: any) {
        this._selected = val;
        
        if (!this.loaded) {
            if (this._selected && this.cache) {
                this.loaded = true;
            }

            this.changeDetector.detectChanges(); <<-- if change on markForCheck() or remove is working correct
        }
    }
```

Expected behavior
Accordion tabs should rendered correctly with each property in conjunctiuon with <ng-template>

Angular version: 10.x

PrimeNG version: 10.x

Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All

**Comment by yigitfindikli** [comment]
Seems to be working latest version of PrimeNG.

https://stackblitz.com/edit/angular-lzsudb-qs48vw?file=src%2Fapp%2Fapp.component.html

I think fixed with https://github.com/primefaces/primeng/issues/10509. Will be added primeng-lts too.
