### ISSUE TITLE
Prime MultiSelect: overlayVisible property does not work, if MultiSelect is dynamically loaded into a page

### ISSUE THREAD

**Issue by SaajRP** [primefaces/primeng#10905]
**I'm submitting a ...** 
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-sfzjtr?file=src%2Fapp%2Fapp.component.ts

**Current behavior**
When the MultiSelect component  is dynamically loaded into the page via an ngIf, through a parent element etc, and the overlayVisible property of the MultiSelect is set to true, the options panel is not visible 

**Expected behavior**
When the Multiselect component is dynamically loaded into the page via an ngIf, through a parent element etc, and the overlayVisible property of the MultiSelect component is set to true, the options panel should be visible 

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/github-sfzjtr?file=src%2Fapp%2Fapp.component.ts

**What is the motivation / use case for changing the behavior?**
I have a case where the MultiSelect is only loaded onto the screen if the end user clicks on a button. When it's loaded onto the screen I would like the options panel for the MultiSelect to be visible, instead of requiring the end user to perform an addtional click on the MultiSelect

**Please tell us about your environment:**

* **Angular version:** 12.1.2

* **PrimeNG version:** 12.1.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript 4.2.4 | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   v14.7.1

**Comment by yigitfindikli** [comment]
You need to call async for multiselect visiblity.

Live example: https://stackblitz.com/edit/github-sfzjtr-p1emqz?file=src%2Fapp%2Fapp.component.ts
