### ISSUE TITLE
Some menu components not supporting ctrl click to open new duplicate screen

### ISSUE THREAD

**Issue by waratah** [primefaces/primeng#10919]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Control click on a menu item does not open a new page with the menu item selected rendered.

**Expected behavior**
New tab opened with selected page showing.

**Minimal reproduction of the problem with instructions**

The issue is caused by prevent default being blocked when the router link is used and control key & click is pressed.

```
    onCategoryClick(event, item: MenuItem | MegaMenuItem) {
        if (item.disabled) {
            event.preventDefault();
            return;
        }

        if (!item.url) {
            event.preventDefault();
        }

        if (item.command) {
            item.command({
                originalEvent: event,
                item: item
            });
        }
```

Code change to stop hiding ctrl key being pressed:

```onCategoryClick(event: PointerEvent, item: MenuItem | MegaMenuItem) {
        if (item.disabled) {
            event.preventDefault();
            return;
        }

        if (!item.url && !event.ctrlKey) {
            event.preventDefault();
        }
```

**What is the motivation / use case for changing the behavior?**

My clients use this to open new screens from menus a lot.

**Please tell us about your environment:**

Windows chrome users

* **Angular version:** 5.X

Angular 12

* **PrimeNG version:** 5.X

Prime 12

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome and firefox
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by waratah** [comment]
Same problem exists in menu as well.

**Comment by waratah** [comment]
Pull Request:   https://github.com/primefaces/primeng/pull/10929

**Comment by yigitfindikli** [comment]
Hi @waratah,

Thanks for your investigation and PR.

Regards.

**Comment by waratah** [comment]
Please note that the line @ 149 is still missing so a menu item that it on the top bar does not have control click.
