### ISSUE TITLE
style in MenuItem dont work

### ISSUE THREAD

**Issue by rezaokhravi** [primefaces/primeng#10918]
"style" does not work inside "MenuItem" for "PanelMenu" , 
for example :

 {
        label: 'File',
        icon: 'pi pi-fw pi-file',
        style: {
            "background":"red",
            "color":"red"
        },
        items: [
          {.....}
        ],
 }
-----------------------------------------------------------------------------
https://stackblitz.com/edit/primeng-panelmenu-demo-met1va

**Comment by yigitfindikli** [comment]
Hi @rezaokhravi,

Style is working fine. You can be able to see in your example too (Look at the font size of the File header.). If you want a give background-color you need to give it to the child anchor element. You can achieve this with the styleClass property of MenuItem.
