### ISSUE TITLE
DOCUMENTATION ERROR - Tree Select has no "Selection" Property - Pain, Tears, Weeping.

### ISSUE THREAD

**Issue by mlembke1** [primefaces/primeng#10917]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
The Documentation says there is a "selection" property on the Tree Select Component.

**Expected behavior**
I expect there to be a selection property on the Tree Select Component.

**Minimal reproduction of the problem with instructions**
Using the Tree select component, attempt to use the "selection" property. It does nothing because there is no selection property.

**What is the motivation / use case for changing the behavior?**
This is extremely confusing. How do we as developers implement a preselection when the component loads? One would think with the "selection" property, which is not actually an `@Input` in the `treeselect.component.ts`.

**Please tell us about your environment:**
Windows 10, VS Code, Chrome

* **Angular version:** 5.X
12.1

* **PrimeNG version:** 5.X
12.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

* **Node (for AoT issues):** `node --version` =   14.6

**Comment by yigitfindikli** [comment]
You need to use [(ngModel)] for PrimeNG input components. Doc will be updated.
