### ISSUE TITLE
pButton disable is not prevent click event

### ISSUE THREAD

**Issue by spyasar** [primefaces/primeng#10924]
pButton disable is not prevent click event and loader button also

**Comment by yigitfindikli** [comment]
The issue is not clear, please feel free to reopen with a stackblitz example or example project.

**Comment by spyasar** [comment]
If i click the loader button spinner is loading and button background is disabled. but when spinner loading time i clicked again in disable stage click event not preventing. this is below code i used,

<p-button label="Save" icon="pi pi-check" styleClass="p-button-success me-2" (click)="saveCompany()" [disabled]="isLoading" [loading]="isLoading"></p-button>
