### ISSUE TITLE
Breadcrumb doesn't update when it's model is updated.

### ISSUE THREAD

**Issue by mrgopalakrishnan** [primefaces/primeng#10925]
Breadcrumb doesn't update when it's model is updated in runtime.
Rootcause is due to this [change](https://github.com/primefaces/primeng/commit/822d74eaf1b1bf9f9fd36790d048bfbbdf3f8af2#diff-3f5895a286b5c2cb8cf9bb028f86dbeecc11b68df82c3b2c0f99f03017263ad3)

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-pomngt?file=src/app/app.component.html

**Current behavior**
When a new item added to the model at runtime, breadcrumb doesn't update the UI automatically

**Expected behavior**
When there is an update on model, the same should reflect in UI

**Steps to reproduce**
Add new menu item to the model of a bread scrum.

* **Angular version:** 13.0.0

* **PrimeNG version:** 13.0.0-rc.2

* **Browser:** all

* **Language:** all

**Comment by Thorski** [comment]
All of the PrimeNG components use the OnPush change detection strategy, which means that you must change the object being passed in (create a new array).   Like this:
`  this.menuItems = [...this.menuItems, { label: 'Item' + this.counter++ }];
`

**Comment by mrgopalakrishnan** [comment]
Great!

It will be helpful if the example is given in the documentation :)

Thank you
