### ISSUE TITLE
Calendar not working in  1.0.0-beta.19 ( in Firefox 49)

### ISSUE THREAD

**Issue by user140547** [primefaces/primeng#1092]
on a local project with 1.0.0-beta.19 , I get an error when using the Calendar: 

Error in ./Calendar class Calendar - inline template:2:58 caused by: event is not defined

Also, the demo on http://www.primefaces.org/primeng/#/calendar is not working, with the same error.

edit: tested on Firefox 49, in Chrome it works

**Comment by yuri1969** [comment]
I can confirm this exception in *FF49* and beta.19. There are also problems with *IE10*
