### ISSUE TITLE
PrimeNg tree table sorting sort is not working using [lazy]="true" as simple tree table is working

### ISSUE THREAD

**Issue by Arraz** [primefaces/primeng#10928]
PrimeNg tree table sorting sort is not working using [lazy]="true" as simple tree table is working
Code:

 <p-treeTable #tt [loading]="loading" (onNodeExpand)="onNodeExpand($event)" [value]="listData" [lazy]="true"
            (onLazyLoad)="loadNodes($event)" [columns]="selectedColumn" sortMode="single" sortField="archived_on"
            [sortOrder]="-1" [frozenColumns]="frozenCols" frozenWidth="180px" [scrollable]="true"
            [style]="{ width: viewportSize.width + 'px' }" (onNodeSelect)="onTreeTableCheckboxToggle(true,false)"
            (onNodeUnselect)="onTreeTableCheckboxToggle(false,false)" [(selection)]="selectedProject"
            (onHeaderCheckboxToggle)="onTreeTableCheckboxToggle($event.checked, true)" [paginator]="true" [rows]="10"
            [rowsPerPageOptions]="[5,10,20,50]" [totalRecords]="totalRecords" [(first)]="firstPage" (onPage)="paginate($event)">
            
            
            
When ever i use [lazy]="true" property then sorting is not working if i remove the  [lazy]="true" then it breaks the lazy loaded node addition to the tree level.

**Comment by yigitfindikli** [comment]
You need to create your own sort when using the lazy option.

You can look Lazy Loading section at https://primefaces.org/primeng/showcase/#/treetable

**Comment by Arraz** [comment]
Is anyone implemented yet ? or you see a proper code that is working  on lazy option for sorting
