### ISSUE TITLE
Give options for slider handle size

### ISSUE THREAD

**Issue by skyleguy** [primefaces/primeng#10927]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Currently the slider handles seem a little too small for use (especially mobile use) 

**Expected behavior**
It would be great if there could be a size input that would increase the handle size so that it could fit the needs of our users. Currently the handles are smaller than a standard radio button.

**What is the motivation / use case for changing the behavior?**
Mobile users will be able to use the slider component more easily if the handles were larger

There are other libraries with slider components that have larger handles, such as @angular-slider/ngx-slider (although in my opinion these are too big, but thats why some sizing options would be nice 👍 )

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
