### ISSUE TITLE
Sizing of p-inputSwitch is not supported in new version

### ISSUE THREAD

**Issue by kishor-p** [primefaces/primeng#10921]
```
[x] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
In older version of PirimeNG (`6.x.x`) using following code could reduce Input-Switch button size.
```
.p-inputswitch { font-size: 7px; }
```
It does not work any more in version: 12.x.x

**Current behavior**
Following CSS has no effect
```
.p-inputswitch { font-size: 7px; }
```

**Expected behavior**
Using below CSS should reduce Input-Switch button size.
```
.p-inputswitch { font-size: 7px; }
```

**Comment by cetincakiroglu** [comment]
It's not ideal to use font-size to change the button ratio since there isn't a text element inside the inputSwitch component to target. To do it properly, you should target .p-inputswitch-slider element by using width and height attributes.

`.p-inputswitch{
      width:4rem;
      height:4rem;
}`

**Comment by kishor-p** [comment]
@cetincakiroglu 
That does not sound like a proper solution. Lot of things could go wrong.
1. even you change size in .p-inputswitch-slider it the white dot looks super weird as below:

![image](https://user-images.githubusercontent.com/14179249/146450422-7c769747-bcf0-423e-852b-89df4297e6a7.png)

2. Also there are lot of things could go wrong with transition as well

![image](https://user-images.githubusercontent.com/14179249/146450502-ab374174-2dda-4577-8f46-4c210ce4f4e5.png)

**Comment by 3zzy** [comment]
Is there a solution yet? Switch based on font-size isn't a great idea, they show up really small.

**Comment by 3zzy** [comment]
This works, but I'd really want the `size` option in the component.
```
.p-inputswitch {
   transform: scale(1.5);
}
```

**Comment by itamardavidyanLFO** [comment]
> This works, but I'd really want the `size` option in the component.
> 
> ```
> .p-inputswitch {
>    transform: scale(1.5);
> }
> ```

With this approach you get the required result (visually) but the input switch container is still on with the original scale and it can break layout flow in some cases

**Comment by itamardavidyanLFO** [comment]
My **not perfect** solution:
```

.p-inputswitch {
  @mixin scale-inputswitch {
    $reduce: 1 / $scale;
    width: 3rem / $reduce;
    height: 1.75rem / $reduce;

    .p-inputswitch-slider:before {
      width: 1.25rem / $reduce;
      height: 1.25rem / $reduce;
      left: 0.25rem / $reduce;
      margin-top: -0.625rem / $reduce;
    }

    &.p-inputswitch-checked .p-inputswitch-slider:before {
      transform: translateX(1.25rem / $reduce);
    }
  }

  $scale: 1;
  @include scale-inputswitch;
  
  &.p-inputswitch-small {
    $scale: 0.7;
    @include scale-inputswitch;
  }
}
```
