### ISSUE TITLE
Slider Stackblitz example not working

### ISSUE THREAD

**Issue by robson90** [primefaces/primeng#10932]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
On this Site, the Stackblitz example is not working. Not in Firefox, Safari or Chrome.
https://primefaces.org/primeng/showcase/#/slider

I tried to geht the Slider working without any success:
https://stackblitz.com/edit/github-cntfwb?file=src/app/app.component.html
The SliderBubble has the wrong shape and isn't moving.

**Comment by yigitfindikli** [comment]
You need to run with the IVY option. Click the cog and click Enable Ivy checkbox.

Example: https://stackblitz.com/edit/github-cntfwb-t9l2sz?file=src/app/app.component.html
