### ISSUE TITLE
p-dropdown onChange - return null when using keyboard navigation

### ISSUE THREAD

**Issue by AvshT** [primefaces/primeng#10935]
@yigitfindikli More info here:
https://github.com/primefaces/primeng/commit/94e7c5b3fdf816e3cd4f20afcf36467adb15a6bc#r61496329

**Comment by yigitfindikli** [comment]
Issue is not clear.

**Comment by AvshT** [comment]
Hi, More clearness:
When using the keyboard navigation in the dropdown dialog, the **onChange** emits on every Up/Down navigation.
The $event object values are:
**{originalEvent, value}**
The originalEvent returns null, it's supposed to have the keyboard event object.

@yigitfindikli Link to the specific line:
[94e7c5b#r61496329](https://github.com/primefaces/primeng/commit/94e7c5b3fdf816e3cd4f20afcf36467adb15a6bc#r61496329)

Thank you for you support.
