### ISSUE TITLE
p-calendar: Keyboard navigation breakage while navigating calendar dates

### ISSUE THREAD

**Issue by mchu-rf** [primefaces/primeng#10936]
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
https://www.primefaces.org/primeng/showcase/#/calendar

A. Inside Valid Date Range (via keyboard navigation)
<img width="362" alt="p-calendar-keyboard-navigation" src="https://user-images.githubusercontent.com/75351198/145093571-21508594-151d-4d52-bc77-074f78af5cbf.png">

B. Navigated Past Max Date (via keyboard navigation)
<img width="361" alt="p-calendar-keyboard-navigation-2" src="https://user-images.githubusercontent.com/75351198/145095328-a95a8130-5590-4047-b1f7-1522835e2990.png">

- Keyboard navigation loses control when navigating past min or max date.
- Keyboard navigation does not allow navigating around disabled dates.
  (In the example, January 2 - 7 are unreachable via keyboard navigation.)

**Expected behavior**
- Allow keyboard navigation back into valid date range.
- Allow keyboard navigation to all dates within the allowed date range.

**Minimal reproduction of the problem with instructions**
- Can be reproduced via PrimeNG component showcase.

**Comment by yigitfindikli** [comment]
Hi,

Thanks a lot for your report but this is expected. You need to use shift or shift + tab to navigate to the header buttons.
