### ISSUE TITLE
Feature Request: Make activate-on-Enter optional for Inplace

### ISSUE THREAD

**Issue by KeithGillette** [primefaces/primeng#10938]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Currently, the Inplace component always activates when `Enter` is pressed when the component has focus, even if its `preventClick` property is set to `true`.

**Expected behavior**
It would be preferable to make activation on `Enter` conditional to allow full programmatic control via the `activate` method, perhaps by changing `preventClick` to `activateManually` and applying it as an execution guard in the `onKeydown` method.

**What is the motivation / use case for changing the behavior?**
While [my previous feature request](https://github.com/primefaces/primeng/issues/8931) gratefully resulted in partial programmatic control by disabling activate-on-click, the remaining activate-on-enter behavior prevents full programmatic control via the `activate()` and `deactivate()` methods, as the component will always activate on `Enter` when it has focus, overriding manually selected activation and deactivation behavior. Having the option to disable activate-on-Enter using the `activate` method allows full programmatic control and completely custom semantics.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by KeithGillette** [comment]
As testing [the PrimeNG InPlace component demo](https://www.primefaces.org/primeng/inplace) shows, this feature has not been implemented, as pressing Enter will activate the InPlace editor when the element has focus. In our project, we have resorted to overriding the `onKeydown` method of the InPlace component with an empty function in `ngAfterViewInit()` of the containing component to prevent this behavior. Per the case made in my original post, disabling this default behavior would easily allow custom mechanics for activating InPlace using its `activate()` method called from a controller method bound to any event, so I think this would be an easy-to-implement and worthwhile enhancement to add to the PrimeNG Roadmap and ask that this issue be reopened, @mertsincan.

**Comment by ashikjs** [comment]
@KeithGillette  I don't get your point can explain it easy way ? please do not go on solution or code. Just try to explain feature or bugs.

**Comment by KeithGillette** [comment]
@ashikjs: I think the existing title is the simplest way I can state the “Feature Request: Make activate-on-Enter optional for Inplace”

**Comment by ashikjs** [comment]
So you want a option or flag to disable  keyboard `Enter` like `preventClick = true` .

so you can control Enter key press .

**Comment by ashikjs** [comment]
@KeithGillette ok, now understand.

I will try to add a pr for this feature .

**Comment by ashikjs** [comment]
@mertsincan  and @KeithGillette  

can you guess check my PR against this feature request.

**Comment by cetincakiroglu** [comment]
Hi,

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 
For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
