### ISSUE TITLE
ngModel is not working properly on p-input number

### ISSUE THREAD

**Issue by hamz4arif** [primefaces/primeng#10941]
ngModel is not working properly in p-input number it updates the value on focus out not on every input like other controls

**Comment by waratah** [comment]
I have a directive that verifies minimums and maximums (min and max of inp0utNumber truncate which I believe is a bad user experience).    This directive used to trigger on ngModel update after every keystroke so the maximum error appeared as soon as the value was exceeded.   it now does it only on blur.

**Comment by waratah** [comment]
I am also getting a situation where I enter 5, then clear 5 and the value is not being reset.

**Comment by waratah** [comment]
https://github.com/primefaces/primeng/pull/11093

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by hmoreras** [comment]
this still an issue when using it with Model Driven Forms - `formControlName` the validation of the form only happens `onBlur`
