### ISSUE TITLE
p-calendar: Calendar width is near 0 in dialog or sidebar 

### ISSUE THREAD

**Issue by ivankosenko** [primefaces/primeng#10943]
**I'm submitting a ...**
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/primeng-calenar-width-bug

**Current behavior**
Width of calendar is near 0.

**Expected behavior**
Width of calendar is correct.

* **Angular version:** ~13.0.0

* **PrimeNG version:** ~13.0.0

* **Browser:** all

**Comment by yigitfindikli** [comment]
You need to use pTemplate="content".

Like https://stackblitz.com/edit/primeng-calenar-width-bug-gz1gvn?file=src%2Fapp%2Fapp.component.html

**Comment by ivankosenko** [comment]
Thank you for explanation.
