### ISSUE TITLE
MultiSelect cant work with number values

### ISSUE THREAD

**Issue by skinnyskinner** [primefaces/primeng#10946]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

At the moment the multiSelect component has issues with an array of number values, when given as options.

There are 2 issues:
- The value 0 is recognised as empty.
- The filter only gives out null and undefined if you give it out in a custom filter. (default filter does not work as well)

**Expected behavior**

I expect it to work like a normal string value.

The filter should work when i enter 0.
Also i want to see the value 0 when its selected in the selectedOptions.

Its important that the value stays a number, since my form needs it to be a number.

**Minimal reproduction of the problem with instructions**

https://stackblitz.com/edit/angular-ivy-s7kphd?file=src%2Fapp%2Fapp.module.ts

**What is the motivation / use case for changing the behavior?**

I have a enum (generated from a swagger.json) that has numeric values.
The user should be able to select the enum by number.

**Please tell us about your environment:**

OS: Linux Manjaro

* **Angular version:** 12.1.1

* **PrimeNG version:** 12.0.0

* **Browser:** all

 
* **Language:** all

* **Node (for AoT issues):** `node --version` = 16 and 14.

**Comment by egziko** [comment]
"options" property take an array of objects.
One solution is to map your enum to an array of objects and use optionValue and optionLabel


```
this.dropdownOptions = Object.values(DemoTypes)
.filter((value) => typeof value === 'number')
.map((v) => ({ value: v }));
```


```
<p-multiSelect
    [options]="dropdownOptions"
    optionLabel="value"
    optionValue="value"
    [formControl]="control"
  ></p-multiSelect>
```

**Comment by yigitfindikli** [comment]
You need to use optionValue and optionLabel.
