### ISSUE TITLE
Tree shaking of unused features in a component

### ISSUE THREAD

**Issue by tuukkamustonen** [primefaces/primeng#10944]
```
[X] feature request
```

Although there is tree shaking these days and only used/declared components will be included in the resulting bundle, it still wraps lots of unnecessary code because all component-related code is embedded even if you use only subset of features of a component.

For example, drawing a very simple table with the Table component adds whopping 74kB (minified) to bundle size. If code for unused features (e.g. scrolling, filtering, data loading, whatever) could be dropped, the bundle size would be much much smaller.

Is there a technical reason why this could not be implemented? (For sure there is...)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by tuukkamustonen** [comment]
@mertsincan I understand you batch closed many tickets and for most it probably makes sense.

But this is fundamental one, which isn't fixed by tuning of current code. I'm not even sure if tree-shaking of _features_ (rather than components) is possible with Angular/PrimeNG, yet it's something that we need.

So, can you re-open?

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
