### ISSUE TITLE
Reordering of column not working if some are hidden

### ISSUE THREAD

**Issue by ludopak** [primefaces/primeng#10945]
**Plunkr Case (Bug Reports)**
 I fork stackblitz template done by kramar  ( #6714) and update it to latest primeng release:

https://stackblitz.com/edit/primeng-tablereorder-demo-mvsvpw

**Current behavior**
If you decide to hide some columns, the reordoring of columns will not work anymore.
On the template you can click on  _Is "Category" column hidden_ and you will see that reordoring will nor work anymore.

**Expected behavior**
The reordoring of columns should work even if there are hidden columns.

In the stackblitz  template I have added a possible fix, if you uncomment  //this.redefineOnColumnDrop(table); (line 39) it will override the onColumnDrop method of table.ts and it should work.
https://stackblitz.com/edit/primeng-tablereorder-demo-mvsvpw

What I did is that I replaced the reordering method

```
  ObjectUtils.reorderArray(
            table.columns,
            dragIndex,
            dropIndex
          );

```
By a more complex code to reorder with "real indexes" (index that will take into account hidden columns).
```

          const realIndexes: number[] = [];

          table.columns.forEach((col: any, index) => {
            if (!col.hidden) {
              realIndexes.push(index);
            }
          });
          ObjectUtils.reorderArray(
            table.columns,
            realIndexes[dragIndex],
            realIndexes[dropIndex]
          );
```

**Comment by iambiswa25** [comment]
Thanks @ludopak for the code
Here adding same modification for Tree Table of primeng

```
private redefineOnColumnDrop(table) {
	table.onColumnDrop = (event, dropColumn) => {
	  event.preventDefault();
	  if (table.draggedColumn) {
		const dragIndex = DomHandler.indexWithinGroup(
		  table.draggedColumn,
		  'ttreorderablecolumn'
		);
		let dropIndex = DomHandler.indexWithinGroup(
		  dropColumn,
		  'ttreorderablecolumn'
		);
		let allowDrop = dragIndex !== dropIndex;
		if (
		  allowDrop &&
		  ((dropIndex - dragIndex === 1 && table.dropPosition === -1) ||
			(dragIndex - dropIndex === 1 && table.dropPosition === 1))
		) {
		  allowDrop = false;
		}

		if (allowDrop && dropIndex < dragIndex && table.dropPosition === 1) {
		  dropIndex = dropIndex + 1;
		}

		if (allowDrop && dropIndex > dragIndex && table.dropPosition === -1) {
		  dropIndex = dropIndex - 1;
		}

		if (allowDrop) {
		  /**
		   * Modifications
		   */
		  const realIndexes: number[] = [];
		  table.columns.forEach((col: any, index) => {
			if (!col.hide) {
			  realIndexes.push(index);
			}
		  });
		  ObjectUtils.reorderArray(
			table.columns,
			realIndexes[dragIndex],
			realIndexes[dropIndex]
		  );
		  /**
		   * End of Modifications
		   */
		  table.onColReorder.emit({
			dragIndex,
			dropIndex,
			columns: table.columns,
		  });
		}

		table.reorderIndicatorUpViewChild.nativeElement.style.display = 'none';
		table.reorderIndicatorDownViewChild.nativeElement.style.display =
		  'none';
		table.draggedColumn.draggable = false;
		table.draggedColumn = null;
		table.dropPosition = null;
	  }
	};
}
```

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
