### ISSUE TITLE
p-calendar does not parse day of year correctly

### ISSUE THREAD

**Issue by bjansen** [primefaces/primeng#10949]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-zn2i2a?file=src/app/app.component.html

**Current behavior**
Formats like `yoo` are not parsed correctly. Inputting `21031` (the 31st day of 2021, i.e. 2021-01-31) automatically changes the value to `21032`. `21342` is automatically changed to `21346`.

**Expected behavior**
The date is not modified after being entered manually.

**Minimal reproduction of the problem with instructions**
Create a `p-calendar` with `dateFormat='yoo'`, type a value manually, the value is modified when the input loses focus.

I'll submit a PR to fix this.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by bjansen** [comment]
Thanks for the very generic comment, but this problem has not been fixed. I opened a PR which has been ignored for almost a year!
There's no conflict on the file so the problem is still present.

**Comment by bjansen** [comment]
No this issue is not fixed because nobody bothered to look at this trivial PR I opened 3 years ago! https://github.com/primefaces/primeng/pull/10950
