### ISSUE TITLE
Improve lazy loading and select all implementation on DataTable

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primeng#10951]
Like; https://www.primefaces.org/primereact/datatable/lazy/

**Comment by Davide-Agoletti** [comment]
but if i need to remain in angular 12 can i upgrade the library and still work ?

**Comment by ensgenc** [comment]
@mertsincan 

I am using 12.2.3 as primeng lts version and the table all Checkbox Selection error persists. Is there a solution for your LTS version?

https://stackblitz.com/edit/primeng-tableselection-demo-oapuip?file=src/app/app.component.html

**Comment by mertsincan** [comment]
Hi @ensgenc,

Could you please create a new issue for us? Thanks a lot!

Best Regards,

**Comment by ibrahimmdumann** [comment]
Is it still continuing ? is there a solution ? @mertsincan @yigitfindikli

**Comment by kaellandrade** [comment]
@ibrahimmdumann did you try to use the `[selectionPageOnly]="true"` attribute? It worked for me.
