### ISSUE TITLE
p-calendar documentation issue

### ISSUE THREAD

**Issue by waratah** [primefaces/primeng#10958]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

documentation for time calendar is this
```<p-calendar [(ngModel)]="value" showTime="true" hourFormat="12"></p-calendar>```

**Expected behavior**

should be :   ```<p-calendar [(ngModel)]="value" [showTime]="true" hourFormat="12"></p-calendar>```

Note the square brackets on the showtime as template checking will fail the compile.

**Minimal reproduction of the problem with instructions**

Only an issue if you enable tight template check in version 12 and up.

**What is the motivation / use case for changing the behavior?**

more correct documentation.

**Please tell us about your environment:**
WIndows, etc.

* **Angular version:** 5.X
12

* **PrimeNG version:** 5.X
12

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

not relevant
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

whatever 12 is...

* **Node (for AoT issues):** `node --version` =

**Comment by waratah** [comment]
Also flag locale as deprecated.   Warning comes up on console

**Comment by yigitfindikli** [comment]
Will be fixed in the next version. Thanks for your report.
