### ISSUE TITLE
GMap Component shows a grey map after re-centering

### ISSUE THREAD

**Issue by jaurakunal** [primefaces/primeng#1095]
Hi,

I'm able to get the map to load correctly the first time with a hard-coded center value of 0,0. However, after the navigator.geolocation.getCurrentPosition() returns I try and re-center the map to my current location and it just shows a grey map with the Google logo at the bottom.

If change the size of the browser then the map gets drawn correctly. Is there anything I can do to avoid this?
Cheers
Kunal

**Comment by garethlewis** [comment]
You need to fire a resize event on the google maps object.  This is not something that prime handles.

To execute this, execute this line after your recenter command.

google.maps.event.trigger(this.gmap.map, "resize"); 

As long as you don't resize the window, you won't need to create a window.onresize event handler, and the map should just redraw itself.

**Comment by garethlewis** [comment]
The problem you have is the Modal is part of your component, but its lifecycle isn't open to you.  So it will have a ngAfterInit and ngAfterViewChecked method which decides what to do. 

The call to resize outside of the timeout, is essentially asking the map to recenter itself, before it has redrawn itself.  It doesn't like that.  Usually it just leads to lots of angry red messages appearing in the console about null.  The timeout is allowing the map canvas to display and then your call to setcenter will work.

What is the reason for opening the map in a dialog?

**Comment by jaurakunal** [comment]
I have a application where the user is searching for a doctor and all known addresses for the doctor need to be shown. since I already have a form on the base page I've designed the search & the results to show up on a modal popup. With the code fix I pasted above its now working for me.

**Comment by garethlewis** [comment]
Actually for what you are doing, if all you need to do is show where the doctor is and don't need interaction, this is a perfect problem for the Static Map API.

https://developers.google.com/maps/documentation/static-maps/

This way, you don't even need to worry about loading google maps.  You just link to a URL that contains an image and Google create you an image upto 1024x768.

**Comment by kcsahoo** [comment]
Refer to issue #924.
I have given the solution and it works.

**Comment by jaurakunal** [comment]
Hi Kris. Thanks for the link to the other issue. But my issue was different than that one and I posted the code that worked for me.

**Comment by moudatsos** [comment]
@kcsahoo some pieces of info are not properly displayed in your answer (issue #924). Could you resolve this, please?
