### ISSUE TITLE
primeng-lts 9 floating label overlaps dropdown text if the selected SelectItem value is an empty string and label is not

### ISSUE THREAD

**Issue by The-MAZZTer** [primefaces/primeng#10969]
**I'm submitting a ...**
```
[x] bug report
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/github-ic9xfm (it looks like an internal stackblitz error is preventing it from properly adding packages so I can't run it)

**Current behavior**

In v9.2.8 if you have a SelectItem with a value of "" the floating label for the dropdown will show on top of it, even if it has a label that is not "".

Something similar seems to happen in v12 of non-LTS using the stackblitz template but I didn't look too closely at that one.

**Expected behavior**

Floating Label should be positioned based on value.

**Minimal reproduction of the problem with instructions**

See stackblitz demo app component.

**What is the motivation / use case for changing the behavior?**

Unreadable labels in certain circumstances.

**Please tell us about your environment:**

Windows 10

* **Angular version:** 8.2.14

* **PrimeNG version:** 9.2.8

Version on StackBlutz (v12 Angular and v12 PrimeNG) before I tried to downgrade it also seemed to have the same issue, though it corrects itself once you switch the option selection (in v9 the labels resume overlapping when switching back to the empty value option)

* **Browser:** 
Chrome Version 96.0.4664.110 (Official Build) (64-bit)
Other browsers untested

* **Language:** TypeScript 3.4.5

* **Node (for AoT issues):** 14.18.1

**Comment by yigitfindikli** [comment]
PrimeNG-LTS 9 support is dropped. PrimeNG-LTS 11 and 12 are supported now.
