### ISSUE TITLE
Add selectionPageOnly property to DataTable

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primeng#10967]
When enabled with paginator and checkbox selection mode, the select all checkbox in the header will select all rows on the current page.

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primeng/issues/10951

**Comment by jdsalasca** [comment]
Hi, i'm trying to use this property but it doesn't work, DataTable doesn't recognize the usage 

"<DataTable value={this.state.products} selection={this.state.selectedProducts9} onSelectionChange={e => this.setState({ selectedProducts9: e.value })} dataKey="id" responsiveLayout="scroll" selectionPageOnly paginator rows={5}>"
