### ISSUE TITLE
Accessibility issue on some primeng components paginator : A button is empty and  has no value text 

### ISSUE THREAD

**Issue by Inaamgharbi** [primefaces/primeng#10961]
Adds aria-label to first page, previous page, next page, and last page buttons on paginator
Wave : error : Empty button
A button is empty or has no value text.

Angular version: 12
Windows 10 Pro, VSCode

PrimeNG version: 12

Browser: all

Language: TypeScript

**Comment by yigitfindikli** [comment]
All accessibility issues will be fixed in 2022 Q1. Thanks for your report.
