### ISSUE TITLE
Slow initial load - table with frozen columns and large number of rows

### ISSUE THREAD

**Issue by ddarrell** [primefaces/primeng#10965]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/github-tkhhz1?file=src/app/app.component.ts

**Current behavior**
The initial load of a table with frozen columns is very slow when there is a large number of rows, sometimes haging the page in Chrome.

**Expected behavior**
The load is faster and doesn't hang the page.

**Minimal reproduction of the problem with instructions**
As you can see in the stackblitz, the page loads for a while before the content is displayed. You can play around with the number of rows to load in the code, but anything past a thousand takes a while.

**What is the motivation / use case for changing the behavior?**
Faster loading times.

**Please tell us about your environment:**

Windows, VS Code, Yarn, Angular dev server

* **Angular version:** 5.X
12.2.13

* **PrimeNG version:** 5.X
12.2.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 4.3.5

* **Node (for AoT issues):** `node --version` =   
14.18.1

**Comment by davide-github** [comment]
The rendering time gets even worse the more frozen columns you have.

This worked fine in Version 11 of primeng. There also large datasets > 1000 rows rendered fast.
In version 11 the forzen column scrollable table was built with 4 different table elements inside the DOM.
This changed in version 12 and above.

Please fix!

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
