### ISSUE TITLE
Accessibility: Toast close button needs aria- label

### ISSUE THREAD

**Issue by alankstewart** [primefaces/primeng#10970]
This is to add an aria-label to the close button in Toast messages.. This is similar to https://github.com/primefaces/primeng/issues/8947

**Comment by yigitfindikli** [comment]
All accessibility issues will be fixed in 2022 Q1. We're gonna publish accessibility scores as well. Thanks for your report.

**Comment by alankstewart** [comment]
Were all the accessibility issues fixed in Q1? Thanks

**Comment by jwhiller** [comment]
Was there a solution to making toast close buttons accessible to screen readers by adding an aria-label attribute to it?
