### ISSUE TITLE
TabView last tab not fully visible when scrollable= true

### ISSUE THREAD

**Issue by zawasp** [primefaces/primeng#10977]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When [scrollable]=true, the last tab of the p-tabView component is not fully visible.

**Expected behavior**
The last tab should be completely visible.

**Minimal reproduction of the problem with instructions**
It can be visible on PrimeNG [showcase](https://www.primefaces.org/primeng/showcase/#/tabview. ) page. In the "Scrollable" demo, click on the "Activate 50th" button. The last tab is not fully visible, as seen in the attached screenshot:
![Screenshot 2021-12-17 182646](https://user-images.githubusercontent.com/2464830/146576422-19ea73a2-0907-4e9e-a3b7-e3d61cb3bede.png)

What is the motivation / use case for changing the behavior?
Needs a fix, as this is a bug.

Please tell us about your environment:

PrimeNG version: 13.0.2

Browser: Chrome 96.0.4664.110  | Edge 96.0.1054.57

**Comment by caolgood** [comment]
This is not resolved as of version 14.2.1, I can reproduce on https://www.primefaces.org/primeng/tabview, but only on specific browser zoom levels like 75%
Chrome Version 107.0.5304.107

**Comment by brett-costello-hllmalta** [comment]
We had the same issue with 14.2.1, we found a 'workaround' by changing the font size from the default:
`:host ::ng-deep .p-tabview-nav-link {
  font-size: 1.1rem;
}`

**Comment by deathDog420** [comment]
I am having this issue with 16.4.1
The issue can also be seen on the official documentation for 17.1.0 -> https://primeng.org/tabview#scrollable

**Comment by MatthewBrenner1** [comment]
This is not working in primeng v18. Also its broken on the demo page: https://primeng.org/tabs

**Comment by volodymyr-kornetskyi** [comment]
The issue still exists. It doesn't matter do you have zoom or not.
And there is no way to fix.

Next button is always visible + last tab name is not full visible.

<img width="123" height="73" alt="Image" src="https://github.com/user-attachments/assets/34cf8d14-e53b-4e38-a4f6-8b1684f145e9" />
