### ISSUE TITLE
Calendar | Inline calendar inside a dialog is broken (width = 0px)

### ISSUE THREAD

**Issue by Urtgard** [primefaces/primeng#10978]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-calendar-demo-bjjlf9

**Current behavior**
When you place a calendar inside a dialog and then open the dialog, the calendar is squished together, if the dialogs visibility is initial set to false.

**Expected behavior**
Calendar should not be squished.

**Minimal reproduction of the problem with instructions**
```
<p-dialog [visible]="false">
  <p-calendar [inline]="true"></p-calendar>
</p-dialog>
```

* **PrimeNG version:** 13.0.2

![inlinecalendar](https://user-images.githubusercontent.com/13890391/146685675-0a57cee1-560d-404d-8c22-574edc3ed830.gif)

**Comment by yigitfindikli** [comment]
You need to use the content template of the dialog component.

```
<p-dialog [visible]="visible" [style]="{ width: '300px' }">
  <ng-template pTemplate="content">
    Initial state: hide
    <p-calendar [inline]="true" view="month"></p-calendar>
    <p-calendar [inline]="true"></p-calendar>
  </ng-template>
</p-dialog>
```

https://stackblitz.com/edit/primeng-calendar-demo-m6b5fa?file=src%2Fapp%2Fapp.component.html

**Comment by Urtgard** [comment]
Thanks, no problems with the template.

Can explain why the template is needed in this case? I used the the dialog multiple times without the template, but only with the inline calendar I got this problem.
