### ISSUE TITLE
Migration guide for version 13.*

### ISSUE THREAD

**Issue by VolodymyrKornetskyi** [primefaces/primeng#10975]
Please add migration guide for version 13.*

**Comment by woppa684** [comment]
And while you're at it, also add one for 14.* ;)

**Comment by sebeyruv** [comment]
At least mention that chart.js needs an update to 3.3.2 as also mentioned here https://primefaces.org/primeng/chart and while you're at it. And maybe for primeflex users a hint to this migration guide https://primefaces.org/primeflex/migration would help as well

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by sebeyruv** [comment]
Is this closed because it duplicates https://github.com/primefaces/primeng/issues/12036

I think what everybody is waiting for is an update to this migration guide where nothing about v13 or v14 is mentioned https://github.com/primefaces/primeng/wiki/Migration-Guide
