### ISSUE TITLE
style and styleClass attributes for TieredMenu MenuItem

### ISSUE THREAD

**Issue by aldialimucaj** [primefaces/primeng#1097]
i would like to pull-right a menu item but the class MenuItem does not have an attribute to extend the style.

**Comment by sudheerj** [comment]
We can have style and styleClass attributes for MenuItem interface.

**Comment by cagataycivici** [comment]
Agreed

**Comment by ratbeard** [comment]
Yea!

**Comment by Abhinav3414** [comment]
When can we expect the fix for this issue. Is it scheduled as part of any near releases ?
Thanks in Advance.

**Comment by BustyLoli-Chan** [comment]
So the interface for MenuItem definitely has a "style" and "styleClass" property. Am I correct to assume that they don't currently do anything? All of my efforts to get them to modify the dom in any way whatsoever have failed.

**Comment by Im-Harrison** [comment]
Any update on this, @cagataycivici, i still seem to find the problem that adding styleClass to a menu item in my ts component to set the options for my menu doesnt add in the class for the menu option?

Additional: I've seen a few logs closed where this has claimed to be fixed and working but it currently is not, if it is working - could you please provide a working example as my attempts to get this working have been, so far, futile.

**Comment by loschmitz** [comment]
Any news about the "styleClass" and "Style" property ? 
It still doesn't work ?

**Comment by nanoTitan** [comment]
Can this be opened back up? I see this as an issue still in primeng 8.0.4.
