### ISSUE TITLE
ProgressBar custom value range defined using min and max inputs

### ISSUE THREAD

**Issue by oliverschenk** [primefaces/primeng#10983]
**I'm submitting a feature request (with implementation)**
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
ProgressBar value is limited to a range of 0 to 100.

**Proposed behavior**
ProgressBar value can be limited to any numeric range defined by a min and max input value.

**What is the motivation / use case for changing the behavior?**
The ProgressBar component already allows changing the unit, but this does not add much value if the range cannot be changed to a custom range. For example, a temperature value could be displayed with a range of -20 to 130 and the units set to degrees Farenheit.

**Implementation**
I have implemented this feature including tests and documentation in the following repo https://github.com/oliverschenk/primeng. If you believe this would be of value to this component and project please let me know and I can open a pull request.

**Comment by Urtgard** [comment]
I would use this feature.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by oliverschenk** [comment]
I checked the documentation and this feature has not yet been implemented.

The  motivation behind this request is that a progress bar may not always be used to indicate a value that represents 0 -100% and may instead display a progress between some other arbitrary min and max value. By being able to specify the min and max it ensures the value and labels also match this context.

The primary use case in my instance is an indicator of a measurement such as temperature being able to be displayed as a visual control.

As already mentioned the code is pretty much done here: https://github.com/oliverschenk/primeng

In any case, there's probably other libraries that can do this. I also thought maybe a horizontal bar chart would work, but a bit more effort to get the data in the right format.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
