### ISSUE TITLE
Accessibility issue on some primeng components icons Button : A button is empty and has no value text

### ISSUE THREAD

**Issue by Inaamgharbi** [primefaces/primeng#10985]
Adds aria-label to icons  Buttons
Wave : error :empty button
A button is empty and has no value text

Angular version: 12
Windows 10 Pro, VSCode

PrimeNG version: 12

Browser: all

Language: TypeScript

**Comment by yigitfindikli** [comment]
All accessibility issues will be fixed in 2022 Q1. We're gonna publish accessibility scores as well. Thanks for your report.

**Comment by likwidgames** [comment]
@yigitfindikli this is still not fixed in v13.0.2
