### ISSUE TITLE
Radiobutton circle icon is not centered

### ISSUE THREAD

**Issue by VictoriaKalakustava** [primefaces/primeng#10982]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Possible to reproduce on the link https://www.primefaces.org/primeng/showcase/#/radiobutton 

**Current behavior**
When changing page scale, sometimes the radiobutton icon is not centered. For example on my device, 100% scale works fine, 90% - looks like the circle a bit shift.

**Expected behavior**
The radiobutton icon centered regardless of scale.

**Minimal reproduction of the problem with instructions**
![image](https://user-images.githubusercontent.com/17678017/146780592-b0054615-48b2-45f9-a3b3-450792f9db69.png)
![image](https://user-images.githubusercontent.com/17678017/146780698-536fe3d5-7a51-430f-9db5-4e8ad9b16520.png)

**What is the motivation / use case for changing the behavior?**
Just make the radiobutton look good

**Please tell us about your environment:**
Windows 10, Chrome Version 96.0.4664.93 (Official Build) (64-bit)
Display resolution: 1920 x 1080

* **Angular version:** 12.0.0

* **PrimeNG version:** 12.2.0

* **Browser:** Chrome Version 96.0.4664.93 (Official Build) (64-bit)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
