### ISSUE TITLE
Documentation: Table Resize partly not matching stackblitz example

### ISSUE THREAD

**Issue by MuhSchaf** [primefaces/primeng#10999]
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Hey there,
first and foremost: A blessed Christmas and a happy new year.
Secondly:

If you take a look at the documentation for the resize feature of the table at:
https://www.primefaces.org/primeng/showcase/#/table/colresize

the property responsiveLayout is passed to the table with the value "scroll".
![image](https://user-images.githubusercontent.com/46820453/147273412-4d33cf50-72b2-4a91-9273-c03a52595dfa.png)

But, if you open the stackblitz example, the responsiveLayout is not passed to the table
![image](https://user-images.githubusercontent.com/46820453/147273660-a9f16fb4-3234-4f70-af81-bd4fbf7ddbf1.png)

Additionally the Documentation states at headline "Scroll Layout", that 
>"Note that when scroll mode is enabled, table-layout automatically switches to auto from fixed as a result table widths are likely to differ and resizable columns are not supported"

**Current behavior**
The Documentation is not consistent onthe responsiveLayout property.

**Expected behavior**
The Documentation is consistent on the responsiveLayout property.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
1. My germaness
2. Well, i use the examples first and read the documentation after, if my table doesn't match the desired outcome.
In my case i used the responsiveLayout property - just to notice it does not change the behaviour as expected and was confused by diverging statements inside the documentation.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
