### ISSUE TITLE
p-dropdown causes page to horizontally scroll

### ISSUE THREAD

**Issue by rosenthalj** [primefaces/primeng#10992]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://primeng-dropdown-demo-vx9kqt.stackblitz.io

**Current behavior**
 In a page that has a horizontal scroll bar and an option has previously been selected, when a dropdown is clicked the page will automatically scroll.  This is new and undesirable behavior

The bug was induced in primeng v12.2.2.  The bug is in primeng v13.x

Issue: https://github.com/primefaces/primeng/issues/10976 was closed because it was not clearly described.  Hopefully this new issue provides clarity.  I'm assuming  the proposed solution in issue #10976 will fix this issue. From MrPollux issue report: 

> https://github.com/primefaces/primeng/blob/0fcf98162c19838cedaeed6bc2db49961d2af1cb/src/app/components/dropdown/dropdown.ts#L697
> 
> selectedListItem.scrollIntoView({ block: 'nearest' }); // does not create this problem
> 
> Version 12.2.1 did not have this problem.

**Expected behavior**
No scrolling.

**Minimal reproduction of the problem with instructions**

https://stackblitz.com/edit/primeng-dropdown-demo-vx9kqt?file=src%2Fapp%2Fapp.component.html
A simple modification to the primeng "single" dropdown demo.  I just added a div to insure that a horizontal scroll bar would be present.

* **Angular version:** 13.X

* **PrimeNG version:** 13.X

* **Browser:** all 
 
* **Language:** all

* **Node (for AoT issues):** `node --version` =

**Comment by eduardtyutyunik** [comment]
Hi. Sorry, but it doesn't really fixed the issue. If you put the dropdown to the right half of the page. In your example:
<p-dropdown [options]="cities" [(ngModel)]="selectedCity1" placeholder="Select a City" optionLabel="name"
	[showClear]="true" **style="margin-left: 300px;**"></p-dropdown>
then the horizontal scroll also happens. The same problem is in the paginator of tables. If the page has a horizontal scroll and the padinator of the table is on the right half of the page, the page scrolls horizontally when the paginator will be oppend.

**Comment by waratah** [comment]
if you get this issue,   use appendTo='body' to work around the bug.

**Comment by olechka-dev** [comment]
I'm using version 13.2.0 and appendTo="body" doesn't help to overcome the issue. The page is scrolled to the left when dropdown is opened

**Comment by wojo2020** [comment]
Same here.  I am using 13.4.1 and am still getting the horizontal scrolling behavior bug.  My dropdown is in the right half of the screen.  It seems to not jump when I place the dropdown in the left half.

**Comment by prodeep-c** [comment]
For 13.4.1  <p-dropdown appendTo="body"> fixed my problem. Thanks

**Comment by jamesleaf** [comment]
Put appendTo="self" in the dropdown and override the CSS of p-dropdown-panel, 

position: absolute;  (will be by default)
left: unset !important;
right: 0:

**Comment by caitlinrouille** [comment]
Any update on this issue? Nothing I do with appendTo works for this issue when there is a scroll.

**Comment by p-gaspar** [comment]
I was able to overcome this issue by setting `[virtualScroll]="true"` on the p-dropdown, and also setting a min-width on the dropdown panel:

`[panelStyle]="{ 'min-width': 'min(100vw, 250px)' }"`

I'm using primeng@14.1.2

**Comment by Chinnadurai312** [comment]
1) I am facing the same issue on clicking the paginator dropdown on primeng p-table. Primeng version used 15.1.0. Do we have any solution.

2) Also the same issue in some of the p-dropdown, tried above mentioned solutions. None of them worked. Can anyone help.

**Comment by mehulk-ba** [comment]
> 1. I am facing the same issue on clicking the paginator dropdown on primeng p-table. Primeng version used 15.1.0. Do we have any solution.
> 2. Also the same issue in some of the p-dropdown, tried above mentioned solutions. None of them worked. Can anyone help.

Hiiiii!!!!! did you find the solution for this issue ???? Please help

**Comment by eduardtyutyunik** [comment]
look here https://github.com/primefaces/primeng/issues/11046
p-dropdown  -> appendTo='body'
p-table          -> paginatorDropdownAppendTo='body'
this work for me.

**Comment by carcigenicate** [comment]
For me, the only fix here that "worked" was `[virtualScroll]="true"`, and that's not a very desirable fix.

For me, this issue was caused by a Bootstrap interaction, somehow. I'm still now sure how opening the dropdown triggered it though.

I had the `p-dropdown` inside of a Bootstrap `row` (`<div class="row">...</div>`). For some reason, opening the dropdown caused the negative margin gutters `row` adds to shift the page. The fix was to remove those gutters using `g-0`:

```html
<div class="row g-0">
    . . .
</div>

**Comment by rolandrybka-circeo** [comment]
I've found out that when you open and close the dropdown, a new div is added after the p-overlay element which position is out of the dropdown's parent client area. So if the parent can overflow, the scrollbars appear. With css I've hidden this new element, which looks like this btw:
`<div class="ng-tns-c23-6 p-overlay p-component ng-star-inserted" ng-reflect-ng-class="[object Object]" style="min-width: 472px; transform-origin: center top; top: 310px; left: 709px;"></div>`
As you can see the left position is a bit odd.
Given this style to the dropdown:
`p-dropdown .p-overlay {
        display: none;
    }`
fixed the issue for me.
