### ISSUE TITLE
Table Column Filtering By Date Should have Custom Date Format Option

### ISSUE THREAD

**Issue by Inaamgharbi** [primefaces/primeng#10998]
Table Column Filtering By Date Should have Custom Date Format Option
Default format is mm/dd/yyyy but I want to achieve dd/mm/yyyy
Angular version: 12
Windows 10 Pro, VSCode

PrimeNG version: 12

Browser: all

Language: TypeScript

**Comment by febymathews** [comment]
<p-calendar [(ngModel)]="dateValue" dateFormat="dd/mm/yy"></p-calendar>

**Comment by kragoth** [comment]
@febymathews that solution requires using a custom template. 

I should be able to do this:
`
<p-columnFilter style="margin-left:10px;" [type]="date" [field]="colInfo.column.field" display="menu" [dateFormat]="'dd/mm/yyyy'"></p-columnFilter>
`

Currently there is no way to utilise the component with a custom date format without having to write your own template.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
