### ISSUE TITLE
p-tree returns node erated when the filter is used.

### ISSUE THREAD

**Issue by Dobromir-Ivanov** [primefaces/primeng#10990]
**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-treefilter-demo

**Minimal reproduction of the problem with instructions**
![image](https://user-images.githubusercontent.com/6341309/146961282-3b9c98e3-e41a-4108-a8d4-535bd21ab6dd.png)

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 13.0.2

* **PrimeNG version:** ^13.0.0-rc.2

* **Browser:** Chrome Versione 96.0.4664.110

**Comment by yigitfindikli** [comment]
You need to use the key property of the Tree Node. And this key should be unique for each node.
