### ISSUE TITLE
control the table inline edit state

### ISSUE THREAD

**Issue by keyone2693z** [primefaces/primeng#11003]
I created this issue but unfortunately, I didn't get any response

https://github.com/primefaces/primeng/issues/10876#issuecomment-986959074

I was wondering if there is a way to control the state of the inline editing
currently, if I click on the cell it goes to edit mode and if I click outside it will go to view mode
I want to be able to say if I clicked on this button go to view mode
is that possible ?

**Comment by keyone2693z** [comment]
the hack for this issue is to use **isEditingCellValid**  to control the editing state

**Comment by waratah** [comment]
In order for this to be understood you would have to create a simple example to look at.

In my case I put the whole row in edit and keep it there until I save or cancel.  Perhaps that will work around your issue in the short term (if I understand it correctly)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
