### ISSUE TITLE
[p-tree] add possibility to distinguish drop target

### ISSUE THREAD

**Issue by ewokhias** [primefaces/primeng#11008]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-rsyuaf

**Current behavior**

There is no possibility to distinguish whether a droppoint or node was the target of a drop. 

**Expected behavior**

It should be possible to distinguish if a drop occured before, on or after a tree node.

**Minimal reproduction of the problem with instructions**

https://stackblitz.com/edit/github-rsyuaf
1. Drag node1 before node2 (droppoint)
2. Drag node1 on node2 (node)

The console will show index 1 in both cases.

**What is the motivation / use case for changing the behavior?**

In our case, we want to perform different API-requests for tree items depending on whether the drop occurred on or before/after a treenode.
If a node was dropped on another node, the API-Request would use the drop node's id as the parent id for the dragged node.
If a node was dropped before/after another node, the API-Requests would not change the parent id but the order instead.

* **Angular version:** 13.1.1

* **PrimeNG version:** 13.0.3

* **Browser:** all

 
* **Language:** all

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by gcorsaro** [comment]
Dears, could you please tell in which version this change has been released?
Looking to the code of the latest ones it seems that those modifications disappeared.
This change was VERY IMPORTANT to distinguish between nodes moved aside and nodes moved inside.
