### ISSUE TITLE
Disabled options remain selected in MultiSelect controls (p-multiSelect)

### ISSUE THREAD

**Issue by TheFabio** [primefaces/primeng#11002]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-qzl9eb

**Current behavior**
When an option is selected and after that programmatically disabled, the selected values (and associated FormControl) do not have the disabled option removed.

**Expected behavior**
disabled option should not be present in the associated form control and component selected values

**Minimal reproduction of the problem with instructions**
using https://stackblitz.com/edit/github-qzl9eb

1) click the second option "heb2"
2) click the third option "heb3"
3) click the second option "heb2"

-->  notice the option heb3 is now disabled, but it remains in the selected values (and associated FormControl). The latest form values are printed on console.

**What is the motivation / use case for changing the behavior?**
avoid having to build work-arrounds

**Please tell us about your environment:** any

* **Angular version:** as per stackblitz

* **PrimeNG version:** as per stackblitz

**Comment by cetincakiroglu** [comment]
The commented part in your code is the best approach to work with it since you need to use setValue to change a controlled form input.

**Comment by TheFabio** [comment]
The commented part of the code is a work-arround.
Shouldn't the disabled selected values on the component be removed from the formControl value? otherwise the displayed layout becomes misleading.
