### ISSUE TITLE
Dropdown - set form as touched after destroy (Expression changed after it was checked)

### ISSUE THREAD

**Issue by tskorvan** [primefaces/primeng#11019]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When binding FormControl inside FormArray to p-dropdown and call clear() function on FormArray. Dropdown set FormArray as touched. This may cause error Expression changed after it was checked, when form is inside tabpanel or accordition. 

Problem is inside p-dropdown. Where is  ngOnDestroy->onOverlayHide->onModelTouched. onModelTouched set parent FormArray after clear as touched.

**Expected behavior**
destroy of p-dropdown dont set form as touched

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/github-xgwn9u?file=src%2Fapp%2Fapp.component.ts

**Comment by sslobodian-iqmessenger** [comment]
Same problem here. We even don't use a FormArray, just destroying the component.

**Comment by davidediak** [comment]
did anyone found a workaround?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by davidediak** [comment]
bug still there, please reopen.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
