### ISSUE TITLE
Doughnut Chart has become too big , and manipulating its size is not possible

### ISSUE THREAD

**Issue by sechouaya** [primefaces/primeng#11016]
**I'm submitting a ...**  (check one with "x")

[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
Doughnut Chart has become too big , and manipulating its size is not possible , after upgrading chart js version to 3.4.1 .


* **Angular version:** 12.2.11

* **PrimeNG version:** 12.2.3
<!-- Check whether this is still an issue in the most recent Angular version -->

**Comment by yigitfindikli** [comment]
Issue is not clear, please feel free to reopen with a stackblitz example.
