### ISSUE TITLE
p-gmap : add some events for the Marker as well.

### ISSUE THREAD

**Issue by maurice85** [primefaces/primeng#11018]
Presently only the events `onMapClick`, `onMapDragEnd`,  `onOverlayDrag` and `onOverlayDragEnd` are available to listen to.
I would really like to be able to listen to events of the `google maps marker` as well. For instance an event `onMarkerDragEnd` could be very handy. Could you please add events for the following marker related events?

1. On marker click
2. On marker drag (so while it is being dragged)
3. On marker drag start / end (an event is fired when the dragging starts, a different event is fired after the marker has been dropped again)

Thank you

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
