### ISSUE TITLE
DynamicDialog - no (dismissable) mask shown in modal-mode

### ISSUE THREAD

**Issue by QuickScoP3s** [primefaces/primeng#11026]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Opening a DynamicDialog in PrimeNG v12.2.2 as a modal, does not show the dismissable mask (darkened background).
The mask is missing the class `p-component-overlay` (it only has `p-component-overlay-enter`) here:
https://github.com/primefaces/primeng/blob/942f6a358b3e6d1cd7fc2ab369a275533123c8db/src/app/components/dynamicdialog/dynamicdialog.ts#L23
This results in the background still being clickable, as if the dialog was not opened as a modal.

This bug was introduced with commit [5365533](https://github.com/primefaces/primeng/commit/53655339e40f012ea3c0ba8a6665b1fa48d08877)

**Expected behavior**
Using the default config, a DynamicDialog should open as a model (as shown in [this example](https://www.primefaces.org/primeng/v12-lts/#/dynamicdialog))

**Minimal reproduction of the problem with instructions**
1. Recreate the showcase dialog shown on the example page
2. Open the dialog and it won't show the dismissable mask (darkened background)

**Please tell us about your environment:**
Windows 11, VS Code Insiders

* **Angular version:** 12.2.13

* **PrimeNG version:** 12.2.2
-> This has been fixed in PrimeNG v13

* **Browser:** Chrome Dev, Edge Chromium (Stable and Dev), FireFox
 
* **Language:** TypeScript 4.3.5

* **Node (for AoT issues):** `node --version` =  v16.13.1

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template

**Comment by QuickScoP3s** [comment]
PrimeNG v12 is in LTS, but this issue will not be fixed?

I know it has been fixed in v13, but we can't upgrade to Angular 13 until all dependencies are updated...

I see there's a v12.2.3 branch, which has the same issue still.

Are external PR's being accepted? If so I'll gladly make one 😉

**Comment by MadebyAe** [comment]
Same issue on v12. Any update?

**Comment by QuickScoP3s** [comment]
I used this as a workaround on `ngOnInit`:
```js
const el = document.getElementsByClassName('p-dialog-mask');
el[0].classList.add('p-component-overlay');
```
