### ISSUE TITLE
P-Calendar allows year navigation beyond minDate and maxDate

### ISSUE THREAD

**Issue by jaggi510** [primefaces/primeng#11029]
Year picker goes beyond the decades of min date and max date.
This is confusing for the users that they can select a year but there is no dates/months available. It will be nice to disable all the years which are outside the minDate and maxDate.

**Comment by aki-kesulahti** [comment]
This was working with previous versions.
It used to set dates in disabled state beyond min and max dates.
So probably title should be "defect" instead of "enhancement"

**Comment by mcrtricolor** [comment]
+1

Also disable the months beyond min and max dates.

**Comment by mcrtricolor** [comment]
Hi, i think this is not an enhancement but a bug to fix. 

Because before the component showed a dropdown with the years to select and those respected the min and max date. Now the dropdown is gone and every option is enabled.

**Comment by mcrtricolor** [comment]
Any news on this fix? Thanks

**Comment by mcrtricolor** [comment]
This is still an issue.

Years and months outside the range are not disabled.

**Comment by mcrtricolor** [comment]
I updated to version 15.1.1 and saw that the months are now disabled if they are outside the range.

You can still select outside of range years, but maybe that is intended.

Thanks!

**Comment by rneto** [comment]
For consistency in the calendar component, just as out-of-range months are disabled when using the month picker, I think out-of-range years should also be disabled when using the year picker.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
