### ISSUE TITLE
TableHeaderCheckbox is checked when the selection array is empty

### ISSUE THREAD

**Issue by MrPollux** [primefaces/primeng#11025]
https://github.com/primefaces/primeng/blob/8e60cc4a1e7c5fb41372d69ecb6b0601eec31214/src/app/components/table/table.ts#L4090

**Cause**:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every
Note: Calling this method on an empty array will return true for any condition!

**Comment by mertsincan** [comment]
Good catch! Thanks a lot!

Best Regards,
