### ISSUE TITLE
p-calendar: Year Label does not change when navigating between years

### ISSUE THREAD

**Issue by gcko** [primefaces/primeng#11030]
**I'm submitting a ...** 
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

The issue is reproducible on PrimeNg's Calendar Demo page.
https://primefaces.org/primeng/showcase/#/calendar

**Current behavior**
1. Create a calendar input using the following:
```<p-calendar [(ngModel)]="dateValue" view="month" dateFormat="mm/yy"></p-calendar>```
2. click on the input field to open the calendar
3. Click on the "<" or ">" chevrons to navigate between years
4. The year does not update in the label

**Expected behavior**
1. The year will update in the label

**Minimal reproduction of the problem with instructions**
1. Go to https://primefaces.org/primeng/showcase/#/calendar
2. Find "Month Picker" in the demo fields
3. click on the input field to open the calendar
4. Click on the "<" or ">" chevrons to navigate between years
5. The year does not update in the label

OR
1. Create a calendar input using the following:
```<p-calendar [(ngModel)]="dateValue" view="month" dateFormat="mm/yy"></p-calendar>```
2. click on the input field to open the calendar
3. Click on the "<" or ">" chevrons to navigate between years
4. The year does not update in the label

**What is the motivation / use case for changing the behavior?**
Current functionality is broken.

**Please tell us about your environment:**

MacOS 12.1

* **Angular version:**
Angular 13.1

* **PrimeNG version:**
PrimeNG 13.0.4

* **Browser:** 
Chrome 97+
 
* **Language:**
TypeScript 4.4

**Comment by yigitfindikli** [comment]
Duplicate https://github.com/primefaces/primeng/issues/11024
