### ISSUE TITLE
<p-columnFilter missing full documentation

### ISSUE THREAD

**Issue by Omzig** [primefaces/primeng#11034]
**I'm submitting a ...**
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**

totality of documentation that i can find is located here
https://primefaces.org/primeng/showcase/#/table/filter

**Expected behavior**

the doc does not explain all the fields that this component can handle.

**Minimal reproduction of the problem with instructions**

go to the website 

**What is the motivation / use case for changing the behavior?**

i need to change the way the control behaves with more than examples

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
angular 12

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
