### ISSUE TITLE
TabMenu and Steps | ActiveItem should be override router highlight

### ISSUE THREAD

**Issue by yigitfindikli** [primefaces/primeng#11031]

**Comment by marcioggs** [comment]
@yigitfindikli In case this is helpful to you, this is the code I'm using to highlight the menu item corresponding to the activated route.
I set the return value to the `this.activeMenu` variable in the component class.


```
  /**
   * Gets from a list of menu items the item which corresponds to the activated route.
   *
   * @param route Activated route
   * @param menuItems List of menu items
   */
  getActiveMenuItemFromRoute(route: ActivatedRoute, menuItems: MenuItem[]): MenuItem | null {
    const childPath = route.snapshot.firstChild!.routeConfig!.path;

    const activeMenuItem = menuItems.find((menuItem) => {
      return menuItem.routerLink.some((path: any) => path === childPath);
    });

    if (!activeMenuItem) {
      this.toastService.fatal(
        $localize`:@@utilities.unknownChildPath:Child path "${childPath}:childPath:" is unknown and the application couldn't set the activated menu.`
      );
      return null;
    }

    return activeMenuItem;
  }
```

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
