### ISSUE TITLE
Primeng dropdown panel minwidth issue

### ISSUE THREAD

**Issue by BhupathiReddyGaddam** [primefaces/primeng#11032]
The minwidth of the dropdown panel is not matching with the dropdown field <p-dropdown> element.

When we add append to body to the dropdown element, the dropdown panel element is rendering outside of the p-dropdown element and not matching the minwidth to its parent <p-dropdown>. Refer the below image.
![image](https://user-images.githubusercontent.com/50251824/148246012-26664cfe-5222-4319-8179-73cf3db7f161.png)

When we remove append to body to the dropdown element, the dropdown panel element is rendering within the p-dropdown element and matching the minwidith to its parent <p-dropdown>, but here one issue is, when we open the dropdown panel it is going underneath of other elements. Refer the below image.
![image](https://user-images.githubusercontent.com/50251824/148246087-6dfb7e42-e1d4-4b72-a7f6-5f0b2da11779.png)

Thanks,
Bhupathi Gaddam

**Comment by cetincakiroglu** [comment]
Hi,

I couldn't replicate it as it seems in the example below, it works as expected.
https://stackblitz.com/edit/primeng-dropdown-demo-nmmbvx?file=src%2Fapp%2Fapp.component.html

Please provide a Stackblitz case for us using;
https://stackblitz.com/github/primefaces/primeng-issue-template
