### ISSUE TITLE
p-tree node toggler button is shrunk until not visible if label starts to not fit the node

### ISSUE THREAD

**Issue by anluik** [primefaces/primeng#11039]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[   ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[   ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When label of a p-tree node is long enough, the toggler button for the node is shrunk and eventually it is hidden. Pictures are from the [documentation](https://www.primefaces.org/primeng/showcase/#/tree).
![image](https://user-images.githubusercontent.com/59440870/148519030-aa5b66f7-748d-49cf-ba2d-fa711bd64523.png)
![image](https://user-images.githubusercontent.com/59440870/148519080-49ec2aa7-d9de-43c6-9424-38d170e8c9da.png)

**Expected behavior**
I believe current behavior is not what anyone would expect to happen. The toggler button should not be shrunk.

**Minimal reproduction of the problem with instructions**
Make the label of the node, that has children, long enough to not fit the maximum width of the p-tree.

**What is the motivation / use case for changing the behavior?**
Without this change, every developer who faces this issue must add extra css to fix it. As I believe this behavior should not exist, it should not be necessary for me to add this extra css to my project.
My css to fix:
`.p-tree {    
    .p-tree-toggler {    
        flex-shrink: 0;    
    }    
}`

* **PrimeNG version:** 5.X

* **Browser:** all

**Comment by aymennsalhi** [comment]
.p-tree-toggler {
    flex-shrink: 0 !important;
  }
