### ISSUE TITLE
InputTextArea: miss add p-filled class when bind value to "innerHtml" instead of value

### ISSUE THREAD

**Issue by mahvash86** [primefaces/primeng#11042]
Hi, I have an InputTextArea and bind my data to its "innerHtml" instead of "value" because I have  html tags in my data , but it doesn't get "p-filled" class even thought it has data in innerHtml.
tanx ;)

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
