### ISSUE TITLE
MultiSelect: Bubbling escape keydown 

### ISSUE THREAD

**Issue by mahvash86** [primefaces/primeng#11044]
Hi, If we use multiselect in dialogs, and set [closeOnEscape] to true for Dialog, when we open multiselect dropdown and check some items and press escape key to hide dropdown, it close dialog simultaneously, I think you could PreventDefault and StopPropagation when hiding multiselect dropdown.
tanx in advance ;)

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
