### ISSUE TITLE
MultiSelect :need checked or UnCheked state of option in OnChange event

### ISSUE THREAD

**Issue by mahvash86** [primefaces/primeng#11043]
Hi , In OnChange event, we have just list of cheked options as "value" and the option we've checked/unchecked as "itemValue" and if we want to know which one is it, check or uncheck, we must find itemValue in Value list and check if it exists in list or not  that has performance issue when clients use in a lot, but you could easily pass that action (check or uncheck) in event .
tanx in advance ;)

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
