### ISSUE TITLE
Table: pDraggable, pDroppable, pReorderable and pReorderableColumn not working on Chrome 97.0.4692.71 (Official Build) (64-bit) Linux

### ISSUE THREAD

**Issue by TheoMuffin** [primefaces/primeng#11047]
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
This bug is on Linux, but not on Windows or Mac. Apparently it's a Chrome/Chromium bug in Linux, I opened a new bug report for that: https://bugs.chromium.org/p/chromium/issues/detail?id=1286294

See the example page for table row and column reordering for demonstration of the bug. The problem affects reordering columns as well as pDraggable, pDroppable and pReorderable for rows. The problem persists in older versions of Primeng as well. Older Chrome versions such as Chrome 96 does not exhibit this problem, neither does Firefox.

https://primefaces.org/primeng/showcase/#/table/reorder

**Current behavior**
Css for when one row is dragged on another is not triggered, onDrop event is not emitted for pDroppable, rows and columns do not reorder on drop.

On further investigation it seems that the problem is with Chrome 97 on Linux because events such as dragover and dragleave are not fired. Dragstart and dragend work though.

See this example for demostration:
https://developer.mozilla.org/en-US/docs/Web/API/Document/dragover_event

**Comment by yigitfindikli** [comment]
Seems to be the problem with Chrome on Linux.
