### ISSUE TITLE
Table doesn't work with Content-security-Policies that enforce trusted-types

### ISSUE THREAD

**Issue by gjdev** [primefaces/primeng#11050]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

The table (p-table) element doesn't use TrustedHTML assignment, so is not compatible with Content-Security-Policies that want to enforce trusted types.

**Expected behavior**

Use of 'angular' trusted-type for assignmnets to innerHTML, so that having a Content-Security-Policy with "trusted-types angular; require-trusted-types-for 'script'" doesn't break the primeng table. For more information about angular trusted type, see: https://angular.io/guide/security#enforcing-trusted-types

**Minimal reproduction of the problem with instructions**

This is self explanatory. The assignments to 'innerHTML' in table.ts should use TrustedHTML instead of raw strings. This should be fixed at e.g. https://github.com/primefaces/primeng/blob/0faea1285f6ee29c82a49206d30c1776ce959f58/src/app/components/table/table.ts#L2467 There are other assignments to innerHTML inside the same file, that have the same issue, and require a TrustedHTML assignment as well to fix this. Note that Angular makes it very easy to fix this with its DomSanitizer.

**What is the motivation / use case for changing the behavior?**

Being able to lock down HTML manupilation with trusted-types makes your site much better secured against DOM XSS attacks.

**Please tell us about your environment:**

Trusted types CSP is supported by all browsers that PrimeNG targets, except for IE.

* **Angular version:** 13.1.1

* **PrimeNG version:** 13.0.4 and master

* **Browser:** all
 
* **Language:** all

**Comment by gjdev** [comment]
There are other components that have the same kind of issue. E.g. a pButton without a label (so when used as icon button), also assignes to innerHTML without using trsuted types: https://github.com/primefaces/primeng/blob/0faea1285f6ee29c82a49206d30c1776ce959f58/src/app/components/button/button.ts#L48

**Comment by gerjon-eatch** [comment]
we have the same issue with tooltips and with the messages component

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by gerjon-eatch** [comment]
This is not fixed. In fact the opposite: there are more components made incompatible with with Content-security-Policies that enforce trusted-types. IMHO, this makes it impossible to create secure applications with PrimeNG, and makes PrimeNG impossible to confirm with security guideliness for most companies I work for.
It would be really apprceiated if the PrimeNG team could have a closer look at their source code, and make sure that it is compatible with strict(er) Content Security Policies.
