### ISSUE TITLE
Unable to select current month with month navigator when min date as current date

### ISSUE THREAD

**Issue by nagavenkateshK** [primefaces/primeng#11057]
https://stackblitz.com/edit/primeng-calendar-demo

**Current behavior**
When set min date to specific date and click on month will navigate to month navigator there current month is disabled and unable to select

**Expected behavior**
When set min date to specific date and click on month needs to be selectable.

**Please tell us about your environment:**
I'm using Visual Studio Code with angular 13.0.0 and prime ng 13.0.0

* **Angular version:** 5.X
13.0.0

* **PrimeNG version:** 5.X
13.0.0

**Comment by cetincakiroglu** [comment]
@nagavenkateshK 

Hi,
This issue has been fixed with the v13.0.4 update.

**Comment by nagavenkateshK** [comment]
Hi @cetincakiroglu 

I've checked with the stackblitz link provided in prim ng(13.0.4) site itself. Do check the following snaps for reference

![dec day view](https://user-images.githubusercontent.com/49555160/149093721-06008bb1-f3c0-4fe1-982a-44d71d07dab1.PNG)
![dec month view](https://user-images.githubusercontent.com/49555160/149093739-1b428fb1-3c98-47d0-b812-2b293fa04448.PNG)
