### ISSUE TITLE
Breaking change on table interface setScrollableItemsWidthOnExpandResize

### ISSUE THREAD

**Issue by sotzdra** [primefaces/primeng#11052]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Table method **setScrollableItemsWidthOnExpandResize** does not exist anymore in PrimeNG v.13

**Expected behavior**
Interface is stable or there is a workaround

* **PrimeNG version:** v.13

* **Browser:** all
 
* **Language:** all

**Comment by yigitfindikli** [comment]
t is deprecated with our new Flex-based Table.
