### ISSUE TITLE
Improve p-dropdown focus visuals for Omega

### ISSUE THREAD

**Issue by kt215** [primefaces/primeng#1105]
When a p-dropdown control has focus, the blue focus rectangle is missing:

![image](https://cloud.githubusercontent.com/assets/14261464/19620348/e1ecdc82-9838-11e6-8cf4-ae92cdb7c52a.png)

Other controls, such as input/pInputText and p-checkbox, show the blue focus rectangle correctly:

![image](https://cloud.githubusercontent.com/assets/14261464/19620351/006a37b8-9839-11e6-90d9-edb7d6a94e3e.png)

Using PrimeNG 1.0.0 Beta 19, Omega Theme, and Chrome 53.0.2785.143

**Comment by cagataycivici** [comment]
It gets .ui-state-focus actually so focus visuals are there but not same as input, will do the same.

**Comment by kt215** [comment]
Thanks for improving this. It looks a lot better now, but the focus visuals still disappear on the p-dropdown after selecting an item from the list using the mouse.
