### ISSUE TITLE
Table multi sort aria attributes are not updated 

### ISSUE THREAD

**Issue by JulianFarhi** [primefaces/primeng#11051]
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Current behavior**
When clicking on the table header (multi sort options) that is currently in "ascending" order, the aria-sort value is still "ascending".

**Expected behavior**
The value of the aria-sort must change to "descending"

**Minimal reproduction of the problem with instructions**
It can be reproduced directly on the demo (v12.2.4):
https://www.primefaces.org/primeng/showcase/#/table/sort

**Comment by yigitfindikli** [comment]
All accessibility issues will be fixed in 2022 Q1. We're gonna publish accessibility scores as well. Thanks for your report.

**Comment by ben-lewis-wtw** [comment]
I am still experiencing this issue on v18, and can also reproduce it on the PrimeNG showcase page with the same steps: https://primeng.org/table#multiple-columns-sort

**Comment by mertsincan** [comment]
@ben-lewis-wtw Thanks a lot for your update! Could you please create a new issue for it? Thanks!
