### ISSUE TITLE
Dropdown input has incorrect accessibility role and parameters.

### ISSUE THREAD

**Issue by StefanCardnell** [primefaces/primeng#11054]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Minimal reproduction of the problem with instructions**

1. Download the free version of axe dev tools for chome here: https://chrome.google.com/webstore/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd
2. Please go to https://www.primefaces.org/primeng/showcase/#/dropdown and run axe dev tools against the page
3. Click the "Needs Review" issues on axe dev tools take note of the following for the dropdown:

- Certain ARIA roles must contain particular children (fix: Expecting ARIA children role to be added: group, option)

![image](https://user-images.githubusercontent.com/11324477/148996549-832811df-7d48-4cef-9fe4-8d9b4ee535f0.png)

**Current behavior**

- The `role` of the input in `p-dropdown` is `listbox`
- `aria-activedescendant` is set before `p-highlighted-option` exists on the page.

**Expected behavior**

- The `role` of the input in `p-autocomplete` should be `combobox`. `listbox` is only valid if the element contains elements with `role=option` inside, which `<input>` does not.

https://www.w3.org/TR/wai-aria-1.1/#listbox
https://www.w3.org/TR/wai-aria-1.1/#combobox

- `aria-activedescendant` should only be set to a value once `p-highlighted-option` exists on the page - i.e. when an option is highlighted.
- `aria-controls` should be set the the id of the list once it exists on the page - i.e. once the dropdown is visible.

**What is the motivation / use case for changing the behavior?**

Accessibility requirements.

* **PrimeNG version:** 13.0.4

* **Browser:** [Chrome - Axe devtools 4.3.5]

**Comment by yigitfindikli** [comment]
All accessibility issues will be fixed in 2022 Q1. Thanks for your report.
