### ISSUE TITLE
Autocomplete input has incorrect accessibility role and parameters.

### ISSUE THREAD

**Issue by StefanCardnell** [primefaces/primeng#11053]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Minimal reproduction of the problem with instructions**

1. Download the free version of axe dev tools for chome here: https://chrome.google.com/webstore/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd
2. Please go to https://www.primefaces.org/primeng/showcase/#/autocomplete and run axe dev tools against the page
3. Review the critical errors and take note of the following for the autocomplete:

- Elements must only use allowed ARIA attributes (fix: Invalid ARIA attribute value: aria-activedescendant="p-highlighted-option")
- ARIA attributes must conform to valid values (ARIA attribute is not allowed: aria-expanded="false").

![image](https://user-images.githubusercontent.com/11324477/148995487-e9df7645-0a2b-4d21-9fac-9330170b4694.png)

**Current behavior**

- The `role` of the input in `p-autocomplete` is `searchbox`
- `aria-haspopup` is set to `true`.
- `aria-activedescendant="p-highlighted-option`" is set before `p-highlighted-option` exists on the page.
- `aria-controls="pr_id_2_list"` is set before `pr_id_2_list` exists on the page.

**Expected behavior**

- The `role` of the input in `p-autocomplete` should be `combobox`. `searchbox` is more specific to an input element which is linked to a search button:

https://www.w3.org/TR/wai-aria-1.1/#searchbox
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search
https://www.w3.org/TR/wai-aria-1.1/#combobox

- `aria-haspopup="true"` should be set to `listbox` as a value of true indicates the popup is of role `menu`. Or it can be removed as `role=combobox` has `aria-haspopup="listbox"` by default.

https://www.w3.org/TR/wai-aria-1.1/#aria-haspopup

- `aria-activedescendant="p-highlighted-option"` should only be set once `p-highlighted-option` exists on the page - i.e. when an option is highlighted.
- `aria-controls="pr_id_2_list"` should only be set once `pr_id_2_list` exists on the page - i.e. once the dropdown is visible.

**What is the motivation / use case for changing the behavior?**

Accessibility requirements.

* **PrimeNG version:** 13.0.4

* **Browser:** [Chrome - Axe devtools 4.3.5]

**Comment by yigitfindikli** [comment]
All accessibility issues will be fixed in 2022 Q1. Thanks for your report.

**Comment by StefanCardnell** [comment]
@yigitfindikli Please, I desperately request that the PrimeNG team re-reads the issues laid out in the ticket here. I can see 13.2.0 released accessibility improvements for `p-dropdown` but it is now in a worse state than it was previously when using a screen reader. 

I can see in the latest commit to `p-dropdown` many aria attributes [were simply just taken out](https://github.com/primefaces/primeng/commit/885de3a5df395a95a4a62eb1106454956e9fc92b). This is not the solution, taking out these attributes might help accessibility tools pass the autocomplete but the component is now unusable for a screen reader.

I kindly request that a screenreader tool like NVDA or Orca is downloaded and tested against the autocomplete. The accessibility issues become are immediately clear. 

I can see the following issues against the autocomplete with the screenreader on `13.2.0`:

1) Screenreader doesn't mention autocomplete doesn't mention there is a list available
2) Screenreader doesn't mention when the list opens
3) When iterating over the list options, the currently highlighted option is not said. 

The suggestions laid out in the OP fixed these problems.

I had a similar issue for the `p-dropdown` component [here](https://github.com/primefaces/primeng/issues/11054) which was closed. But I can see the accessibility improvements to the dropdown do not help .

Our company uses Prime and we are trying to meet accessibility quotas. Right now we're having to override and re-write PrimeNG templates to fix these issues.
