### ISSUE TITLE
Drag and drop related events are not firing

### ISSUE THREAD

**Issue by igorthy** [primefaces/primeng#11065]
**I'm submitting a ...**
```
[x] bug report
```

**Current behavior**
Drag and drop related events are not firing: such as onDragEnter, onDragLeave, onDrop...

**Expected behavior**
Drag and drop related events should fire

**Minimal reproduction of the problem with instructions**
Even on PrimeNG own site with demo I can't drag products from left to right.
https://www.primefaces.org/primeng/showcase/#/dragdrop

**Please tell us about your environment:**
Ubuntu 18.04

* **PrimeNG** 13.0.4
* **Angular** 13
* **Browser:** Chrome (97.0.4692.71)

**Comment by yigitfindikli** [comment]
https://user-images.githubusercontent.com/19997575/149325022-dce267fb-86f4-4cce-b4ec-d6dac26671f6.mov


Seems to be working.

**Comment by igorthy** [comment]
It doesn't work for me.
See my   recording.
https://user-images.githubusercontent.com/3367584/149328605-fc9ba6fa-e0c2-4dd5-bc30-85762d610556.mp4
