### ISSUE TITLE
Drag and drop related events are not firing

### ISSUE THREAD

**Issue by igorthy** [primefaces/primeng#11068]
**I'm submitting a ...**
```
[x] bug report
```

**Current behavior**
Drag and drop related events are not firing: such as onDragEnter, onDragLeave, onDrop...

**Expected behavior**
Drag and drop related events should fire

**Minimal reproduction of the problem with instructions**
Even on PrimeNG own site with demo I can't drag products from left to right.
https://www.primefaces.org/primeng/showcase/#/dragdrop

https://user-images.githubusercontent.com/3367584/149334460-fd8ef926-80c0-478c-9fba-ac17b915fa3d.mp4

**Please tell us about your environment:**
Ubuntu 18.04

* **PrimeNG** 13.0.4
* **Angular** 13
* **Browser:** Chrome (97.0.4692.71)

**Comment by yigitfindikli** [comment]
This issue is related to Chrome's (97.0.4692.71) Ubuntu version.

Please see;

https://github.com/primefaces/primeng/issues/11065

https://user-images.githubusercontent.com/19997575/149325022-dce267fb-86f4-4cce-b4ec-d6dac26671f6.mov

**Comment by igorthy** [comment]
Why did you close my issues ?
