### ISSUE TITLE
[BUG] add menu item and infinite scroll to timeLine component doesn't work.

### ISSUE THREAD

**Issue by hsnrzv** [primefaces/primeng#11063]
**I'm submitting a ...** 
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/primeng-timeline-demo-8gguub?file=src/app/app.component.ts

**Current behavior**

using menu item and infinite scroll in timeLine component doesn't work right.

1- menu Item doesn't open in right position: 

![Bildschirmfoto 2022-01-12 um 22 58 32](https://user-images.githubusercontent.com/65459078/149229627-f57fe685-3680-4c85-9928-7af2acaa5542.png).

2- after scroll to end event will triggered, array will be filled with data but they will not be rendered in template until user click on menu Item Button in card.

**Expected behavior**

1- menu item opens in right position after menu button
2- scroll down render filled Array in template right

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 13.0.4

* **PrimeNG version:** 13.0.4

* **Browser:** [all]

 
* **Language:** [all]

**Comment by yigitfindikli** [comment]
You need to use with appendTo property.
