### ISSUE TITLE
When opening a menu after a delay, we need to click ouside the menu twice to close it

### ISSUE THREAD

**Issue by stephanebouget** [primefaces/primeng#11062]
**I'm submitting a ...** 
```
[X] bug report
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-slidemenu-demo-xfxe1d?file=src%2Fapp%2Fapp.component.ts

**Current behavior**
When opening a menu after a delay (after a setTimeout or an http request) we need to click ouside the menu twice to close it

**Expected behavior**
The menu must close after the first click outside

**Minimal reproduction of the problem with instructions**
see it in action here:
https://stackblitz.com/edit/primeng-slidemenu-demo-xfxe1d?file=src%2Fapp%2Fapp.component.ts

**What is the motivation / use case for changing the behavior?**
I need to construct the menu from my server content

**Please tell us about your environment:**
Win 10, VS Code

* **Angular version:** 13.0.0

* **PrimeNG version:** 13.0.1

* **Browser:** all
 
* **Language:** TypeScript 4.4.3

**Comment by cetincakiroglu** [comment]
Hi, 

You can use in this way to eliminate the need for a second click https://stackblitz.com/edit/primeng-slidemenu-demo-pzuvpr?file=src%2Fapp%2Fapp.component.ts
