### ISSUE TITLE
p-tableHeaderCheckbox can get stuck in checked state

### ISSUE THREAD

**Issue by johanrg** [primefaces/primeng#11074]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
[https://stackblitz.com/edit/github-b8pget?file=src/app/app.component.ts](https://stackblitz.com/edit/github-b8pget?file=src/app/app.component.ts)

**Current behavior**

The checkbox can always be checked, even if the [rowSelectable] function always return false. Once the button is checked, the state can not be undone.

**Expected behavior**

If none of the rows in the current table/paginated rows can be selected, then the p-tableHeaderCheckbox should not be set to checked. 

At least it should not get stuck in this state. In the provided example this bug manifest itself directly when setting the [(selection)] to an empty array, leaving the variable undefined does not set the checkbox to checked state, but once clicked it will get stuck in that state.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

It will confuse my users that it can be checked without actually having selected anything. Having the checked state based on the selection array being undefined is not a good solution. This state is also stuck  over multiple page reloads when using  stateStorage="session".

**Please tell us about your environment:**

* **Angular version:** 13.1.1

This is the latest version at this time

* **PrimeNG version:** 13.0.4

This is the latest version at this time

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
