### ISSUE TITLE
Filter over an array of plain strings in datatable

### ISSUE THREAD

**Issue by Nickath** [primefaces/primeng#11072]
I am trying to filter a plain array of strings which is presented through a `p-table`. I use `<p-columnFilter` to filter array of objects by `property value`, but I do not know how to do it for array of **plain strings** and I have not found any example in the official documentation. 

Could you please shed some light on this?

* **Angular version:** 12.2.3

* **PrimeNG version:** 12.1.0

**Comment by cmccoy98** [comment]
Also have run into this problem. Is it possible to iterate over an array of primitive type? Or must it be a key-value pair?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by cmccoy98** [comment]
Hey @mertsincan, thanks for the follow up. However, in regards to recent perf updates in PrimeNG, has anyone been able to look at #11775 ? It appears to still be an issue even in the newest version of PrimeNG but isn't an issue in PrimeReact.
