### ISSUE TITLE
Dropdown does not work properly inside OrderList

### ISSUE THREAD

**Issue by rhegner** [primefaces/primeng#11079]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case**

https://stackblitz.com/edit/primeng-orderlist-demo-kerca2?file=src/app/app.component.ts

**Current behavior**
Dropdown inside an OrderList does not open most of the time when clicking the arrow. If it does open (ocasionally), the dropdown panel is cropped to the area of the order list item.

**Expected behavior**
Dropdown opens properly when clicking the arrow, and the dropdown panel is not cropped.

**Minimal reproduction of the problem with instructions**
1) Open Stackblitz above
2) Try to open a Dropdown inside the list

**Angular version:** 13.1.1

**PrimeNG version:** 13.0.4

**Comment by cetincakiroglu** [comment]
Hi, 

To eliminate this problem we have **appendTo** input property for dropdown.

[Here you can check it.](https://stackblitz.com/edit/primeng-orderlist-demo-vvwifz?file=src%2Fapp%2Fapp.component.html)
