### ISSUE TITLE
p-dropdown template contains type attribute that breaks Content-Security-Policies with trusted-types declaration.

### ISSUE THREAD

**Issue by gerjon-eatch** [primefaces/primeng#11075]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

At https://github.com/primefaces/primeng/blob/7eedde511734912839e3acc2f56958a165a079ae/src/app/components/dropdown/dropdown.ts#L83 the declared div contains this in its defenition: `(@overlayAnimation.start)="onOverlayAnimationEnd($event)"onOverlayAnimationEnd`. Please note that `onOverlayAnimationEnd` is used in the value of the `(@overlayAnimation.start)`, as intended. But directly after the attribute assignment the word `onOverlayAnimationEnd` is repeated, which creates an attribute by that name. The attribute is a typo and functionally does nothing. However, sice the attribute starts with the prefix `on`, it will break pages that use a trusted types assignment in their Content-Security-Policy.

So please remove that...

**Expected behavior**

Remove the `onOverlayAnimationEnd` attribute from the div template, as it is a typo.

**Minimal reproduction of the problem with instructions**

Just open any example page with a p-dropdown, inspect the correct div in the template, and see that it has an attribute named `onOverlayAnimationEnd`, which serves no purpose.

**What is the motivation / use case for changing the behavior?**

It's breaks our pages when we use a Content-Security-Policy with trusted types assignment, since angular tries to assign an empty string value to the attribute, the attribute starts with `on`, so the browser deems it a script, and an empty string is not a trusted type.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
