### ISSUE TITLE
OrderList (drag&drop) does not work correctly in dialog

### ISSUE THREAD

**Issue by rhegner** [primefaces/primeng#11078]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case**

https://stackblitz.com/edit/primeng-dynamicdialog-demo-dwlwi2?file=src/app/productlistdemo.ts

**Current behavior**
Items in the OrderList are not visible while being dragged. They seem to be hidden behind the dialog (this can be verified by dragging the item outside of the dialog area).

**Expected behavior**
The item is in front of the dialog while dragging.

**Minimal reproduction of the problem with instructions**
1) Open the Stackblitz link above.
2) Click 'Show' to open the dialog.
3) Drag an item around and notice how it disappears behind the dialog.

**Angular version:** 13.1.1

**PrimeNG version:** 13.0.4

**Browser:** Chrome 97 (probably in any browser)
 
**Language:** TypeScript 4.5.4

**Comment by cetincakiroglu** [comment]
Hi,

Problem is caused by zIndex of dynamic dialog.

Here is the refactored and working version of your example.
https://stackblitz.com/edit/primeng-dynamicdialog-demo-xx3fkv?file=src%2Fapp%2Fapp.component.ts

Regards

**Comment by LuisAduana** [comment]
@cetincakiroglu  In your example you can drag only one element at once, not multiple
