### ISSUE TITLE
Include test harnesses

### ISSUE THREAD

**Issue by azaeng04** [primefaces/primeng#11087]
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
There are no test harnesses defined for any of the components

**Expected behavior**
Define test harnesses for all components

**What is the motivation / use case for changing the behavior?**
To be able to interact with components through a common API. This will allow for easy interaction with the relevant components.

**Comment by azaeng04** [comment]
How can I contribute to this? @yigitfindikli

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by azaeng04** [comment]
It is not included @mertsincan, but I guess there isn't much demand for interacting with the relevant components.

**Comment by jsdevtom** [comment]
This would be very helpful!

**Comment by cetincakiroglu** [comment]
Hi,

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 
For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
