### ISSUE TITLE
Bug: Error: Conflict: Multiple assets emit different content to the same filename primeicons.ttf

### ISSUE THREAD

**Issue by critical-pass** [primefaces/primeng#11081]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
I am upgrading an angular 12 app to angular 13. The app upgraded successfully as it compiled correctly and ran in the browser. I upgraded primeicons to v5 and primeng to v 13.0.4. After upgrading, I tried to run my app with `ng serve` I get the following errors:
```
Error: Conflict: Multiple assets emit different content to the same filename primeicons.eot

Error: Conflict: Multiple assets emit different content to the same filename primeicons.ttf

Error: Conflict: Multiple assets emit different content to the same filename primeicons.woff

Error: Conflict: Multiple assets emit different content to the same filename primeicons.svg
```
After installing primeicons@5 and primeng@13.0.4

**Expected behavior**
The app is expected to compile successfully and run

**Minimal reproduction of the problem with instructions**
```
npm i primeicons
npm i primeng
```

**What is the motivation / use case for changing the behavior?**
I was trying to upgrade primeng

* **Angular version:** 5.X
13.0.2

* **PrimeNG version:** 5.X
13.0.4

**Comment by Svancara** [comment]
The same here. It is an urgent problem for me. Please, fix. Thank you!

**Comment by yigitfindikli** [comment]
Remove your node_modules and install node_modules again.
