### ISSUE TITLE
Table layout issues

### ISSUE THREAD

**Issue by waratah** [primefaces/primeng#11086]
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

On master I have found a couple of issues:

a)   When calculating the width all TH are extracted from the header.   We currently use two tr records iwhich means results are doubled.    A Possible work around to this issue is to handle td records in the header in the same manner so that I can switch the second one from tr > th to tr > td fixing the selection issue:

      innerHTML += `
                        #${this.id} .p-datatable-thead > tr > th:nth-child(${index + 1}),
                        #${this.id} .p-datatable-thead > tr > td:nth-child(${index + 1}),     //   EXTRA LINE
                        #${this.id} .p-datatable-tbody > tr > td:nth-child(${index + 1}),
                        #${this.id} .p-datatable-tfoot > tr > td:nth-child(${index + 1}) {
                            ${style}
                        }

Note that this logic appears twice.

        @media screen and (max-width: ${this.breakpoint}) {
            #${this.id} .p-datatable-thead > tr > th,
            #${this.id} .p-datatable-thead > tr > td,   //   EXTRA LINE
            #${this.id} .p-datatable-tfoot > tr > td {
                display: none !important;
            }
    
A possibly better solution is to fix the two places that this logic occurs to only pull the first tr record.
    
      let headers = DomHandler.find(tableHead, 'tr > th');

and

     let headers = DomHandler.find(this.containerViewChild.nativeElement, '.p-datatable-thead > tr > th');
    
 b)   I am migrating from V8 to the current version the table width state that is recovered from the local storage is incorrect and since the changes are all delta the table width is calculated off.   One solution is when we are recovering the table state we can recalculate the widths on load.
 
    if (this.columnResizeMode === 'expand' && this.tableWidthState) {
                this.tableWidthState = widths.map((x) => Number(x)).reduce((a, b) => a + b, 0).toString();   //   EXTRA LINE
                this.tableViewChild.nativeElement.style.width = this.tableWidthState;
                this.tableViewChild.nativeElement.style.minWidth = this.tableWidthState;
                
If you get blanks at end of a table or a table being 'chopped off' this would be the issue here.  Currently once corrupted it is impossible to reset things.

c)  The selectAll flag appears to be set incorrectly.  This is worked around by changes to onchange but code is not correct: 

    @Input() get selectAll(): boolean | null {
        return this._selectAll;  // was return this._selection;
    }

    set selectAll(val: boolean | null) {
        this._selectAll = val;   // was this._selection = val;
    }
    
d) finally I had a layout bug which is not related to code but documenting it here:

I have an input box which appears to have a minimum size (no idea from CSS where...) and the input box was substantly larger than the column width.   In order to work around this issue I first had to hide the overflow, this truncated display and stopped the column being larger than the flex with (121px by table.ts but displaying 192px):

      <td *ngFor="let col of columns;trackBy:trackBy"
        style='overflow: hidden;'                                             // this line here....
        pReorderableColumn
        [ngSwitch]="col?.dataType"
        [ngClass]='{filtered: table.filters[col?.field]}'>

Next try as I might I could not get the input box to scale down with flex-1 in a flex layout.

     <input pInputText
            #inp
            style='width:5px'
            class='flex-1'

I had to add the style with a width to make the input tiny and the grow worked correctly,  the apparent shrink from flex-1 was not taking effect,  however grow worked correctly.

I feel this is a Chrome bug but I thought I would document it so that similar issues can be handled quickly.

**Comment by yigitfindikli** [comment]
Related fixes https://github.com/primefaces/primeng/issues/10951, https://github.com/primefaces/primeng/issues/10967, https://github.com/primefaces/primeng/issues/11082
