### ISSUE TITLE
TabView tabs do not show when a row in p-table is expanded

### ISSUE THREAD

**Issue by sandipchitale** [primefaces/primeng#11080]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at Stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewed in detail and assisted.

https://stackblitz.com/edit/primeng-tablerowexpansion-demo-u8ocly

**Current behavior**

The tabs do not show when the first row is expanded. When the second row is expanded the tabs in the first expanded row show, but the tabs in the second row do not show.

**Expected behavior**

The tabs should show when row is expanded.

**Minimal reproduction of the problem with instructions**

https://stackblitz.com/edit/primeng-tablerowexpansion-demo-u8ocly?file=src/app/app.component.html

**What is the motivation / use case for changing the behavior?**

Want to use Tab View in expanded row.

**Please tell us about your environment:**
Any

* **Angular version:** 5.X

11.0.X

* **PrimeNG version:** 5.X

13.0.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Any
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by sandipchitale** [comment]
![image](https://user-images.githubusercontent.com/3310939/149603194-5aa79d6e-ceae-42f5-8366-009bd457ccc5.png)

**Comment by cetincakiroglu** [comment]
Hi,

Here is a refactored & working example of your Stackblitz.

https://stackblitz.com/edit/primeng-tablerowexpansion-demo-lh1mwb?file=src%2Fapp%2Fapp.component.html

Regards
