### ISSUE TITLE
Scroll Table Footer and Header no longer inside of scrollbars

### ISSUE THREAD

**Issue by jermylucas** [primefaces/primeng#11085]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

It seems that on the more recent versions of PrimeNG, the `pTemplate` footer and header is no longer inside of the scrollbars. This makes the UI look worse (in my opinion) and if there's a vertical scroll, why should the user  While they stay in a fixed position, the scrollbars on the side are now showing around the footer and header, as if the elements are supposed to be scrolling. This adds a problem when using the `offsetTop` and `offsetHeight` properties of the table to get the scrollbar positions, as the header and footer are not taken into account. 

This does not seem to have been an issue on previous versions. I was able to find an older (v11) Stackblitz where they are outside of the scrollbars. 
![image](https://user-images.githubusercontent.com/47125917/149833396-ff82f028-ff44-44c4-bdb0-7d642952a886.png)
Compared to the current versions:
![image](https://user-images.githubusercontent.com/47125917/149833307-b53e0476-14ea-43d0-b413-8f86305254a6.png)

These are two identical sized browsers and content and html, with the only difference being the PrimgNG versions. Since the header and footer are _not_ scrolling, it would seem the older experience is correct. Maybe there's something else going on? If it is due to the scrollbars for smaller browsers or devices (where previously and as the docs and v11 screenshot shows, it used to be a flex design), is there a planned 'offset' addon for the scrollbar widths? Or is there an option to add a flex parameter?

[StackBlitz link](https://stackblitz.com/edit/primeng-tablescroll-demo-mdf51w?file=src/app/app.component.ts)

From the docs:
> Scrollable table uses flex layout so there are a couple of rules to consider when adjusting the widths of columns.

Am I misunderstanding, or is this an issue that can be fixed?

**Comment by yigitfindikli** [comment]
This is expected. Our scrolling table structure is changed to flex and sticky.
