### ISSUE TITLE
Table - widths going to zero when hidden

### ISSUE THREAD

**Issue by waratah** [primefaces/primeng#11094]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
```

**Current behavior**

Table is presented on tabs.   So at some stage it is hidden.

When hidden without filters and the 'value' changes,  no problem.

When hidden with fitlers in

```
ngOnChanges(simpleChange: SimpleChanges) {
    if (simpleChange.value) {
    ...
    this._filter();
    ...
```

_filters in turn calls save state.   The issue is that the table is hidden and all columns are zero width.  The state is saved with all zeros.

**Expected behavior**

This is the quick hack I came up with.    there is possibly a better one.

```
saveState() {
   ...
   if (state.tableWidth !== '0px') {
      storage.setItem(this.stateKey, JSON.stringify(state));
      this.onStateSave.emit(state);
    }
}
```

**Minimal reproduction of the problem with instructions**

* Apply filters
* Hide table visually.
* reload data (value change)

State is corrupted

**What is the motivation / use case for changing the behavior?**

Table in tabs.

* **Angular version:**  13
* **PrimeNG version:** 13
* **Browser:** all
* **Language:**  TypeScript

**Comment by yigitfindikli** [comment]
Issue is not clear, please feel free to reopen with a stackblitz example.
