### ISSUE TITLE
New Component: InputNumber

### ISSUE THREAD

**Issue by giovannistiwes** [primefaces/primeng#1109]
For ERP systems, this component is essential. It would be nice to have it in version

**Comment by jmachnik** [comment]
What's wrong with http://www.primefaces.org/primeng/#/spinner?

**Comment by giovannistiwes** [comment]
1 - allows you to turn enter letters
2 - does not allow mask to decimal

**Comment by cesarrew** [comment]
You can use this component:

https://www.npmjs.com/package/ng2-currency-mask

**Comment by mikosu3** [comment]
i want this feature from same reason!

**Comment by cagataycivici** [comment]
More examples please so we can gather requirements.

**Comment by mmlitvin** [comment]
Upvote. Use Case: provide input as a number between 0 and 367

**Comment by serlopez46** [comment]
Really need a component in PrimeNG similar to the one in [PrimeFaces](https://www.primefaces.org/showcase/ui/input/inputNumber.xhtml). The only alternative is ng2-currency-mask and it's not updated regularly.

**Comment by TheParad0X** [comment]
Same here. This component is really important.

**Comment by RobSchripsema** [comment]
Agreed. PrimeNG is so good at many things, this is an unfortunate weakness.

**Comment by mmlitvin** [comment]
Any updates? This requirement has been opened over a year ago. Was truly hoping it would be in production by now

**Comment by Zbulu** [comment]
Yeah that would be nice spinner is not good enough has to many bugs and its purpose is a bit different

**Comment by mknarula** [comment]
this feature alone makes primeng looks bad.

**Comment by Dargos69** [comment]
you can use [KeyFilter](https://www.primefaces.org/primeng/#/keyfilter)
`<input type="text" pInputText pKeyFilter="money" placeholder="Money">`

**Comment by hubslave** [comment]
Just checked, Spinner and KeyFilter doesn't works like [inputNumber](https://www.primefaces.org/showcase/ui/input/inputNumber.xhtml) from primefaces.
Please, add to the roadmap: we need inputNumber on PrimeNG!

**Comment by iftikharkhan89** [comment]
I agree keyFilter & Spinner do not serve the job as inputNumber in Primefaces. This is much need component in PrimeNg. I request to add in future versions.

**Comment by imfarhadk** [comment]
+1, please add this component

**Comment by CastelvaniaA** [comment]
It would be greate if you add component like in [PrimeFaces](https://www.primefaces.org/showcase/ui/input/inputNumber.xhtml). With ability to add number with only one possible dot or comma.

**Comment by earshinov** [comment]
For anyone coming across this ticket: [Spinner](https://www.primefaces.org/primeng/#/spinner) might be what you need.

![image](https://user-images.githubusercontent.com/52021/54232336-7c19a600-451b-11e9-87ab-c78fe9859b7e.png)

**Comment by Fridthjof** [comment]
What is the status for this?

**Comment by rborosak** [comment]
+1

**Comment by mickeyjohn** [comment]
One more vote for inputNumber in PrimeNG. It is an essential requirement for apps which support multiple languages. Has it in a roadmap or plan yet?

Thanks.

**Comment by zillog** [comment]
This request is still opened since October 2016
+1

**Comment by Fibonacci-Solucoes-Ageis** [comment]
+1

**Comment by judhra** [comment]
+1

**Comment by mikaelboff** [comment]
+1

**Comment by tommancini** [comment]
We **need** this too!

**Comment by quentinm3** [comment]
We need this too!

**Comment by danielsava** [comment]
+1

**Comment by GlenyR** [comment]
+1

**Comment by absantanna2412** [comment]
+1

**Comment by lucksjb** [comment]
+1

**Comment by markleppke** [comment]
+1

**Comment by cagataycivici** [comment]
Coming soon in 9.1.0.

**Comment by cagataycivici** [comment]
Really complex but we are on track.

<img width="1382" alt="Screen Shot 2020-04-13 at 23 14 48" src="https://user-images.githubusercontent.com/686247/79158318-c7694c80-7dde-11ea-834b-4205bcfa2ad3.png">
