### ISSUE TITLE
How to distinguish the event is on sibling or next level while tree node was dropped?

### ISSUE THREAD

**Issue by keyong19ryry** [primefaces/primeng#11090]
I'm try to invoke the drag&drop event of tree component. When I drag a node to another, there are two style to drop.One is on the sibling level, if this, the drop node will be the sibling node with the target. The other is on next level, then the drop node will be the child node of the drop node. How to distinguish them?

**Comment by yigitfindikli** [comment]
Please use the forum or discord channel for questions and help requests.
