### ISSUE TITLE
p-table sticky headers don't work with scrollable true

### ISSUE THREAD

**Issue by sandu-curagau** [primefaces/primeng#11099]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Here is a quick example, it's a ready playground to test both scenarios (with and without horizontal scroll), feel free to try to make headers sticky with scrollable true (without having fixed scrollHeight on table, use page scroll), it won't work.

https://stackblitz.com/edit/primeng-tablescroll-demo-qm2ndu?file=src/app/app.component.ts

When we pass [scrollable]="true" primeng applies certain styles, from what I've seen, overflow auto is applied to p-datatable-wrapper thus binding the vertical sticky stylings to that overflow, instead of having horizontal scroll on the tbody and thead and keeping vertical scroll on page so sticky headers would be bound to the page's scroll. Quite tricky...

I've tried the obvious things like moving the overflows around but nothing has worked. At this point I don't really have an idea for a solution that's not hard coding a lot of logic to force calculations for constantly setting the top attribute of the headers when we scroll on the page to fake having sticky headers, since they don't work.

I'd love to see primeng update this somehow and provide an easy way to implement the desired behavior.

**Current behavior**
If you have horizontal scrolling in your table (e.g. [scrollable]="true" scrollDirection="horizontal" ), sticky headers don't work on page vertical scroll, it only works if we set scrollHeight, which may not be the wanted behaviour. 

**Expected behavior**
Expected behaviour would be to be able to enable horizontal scrolling, and be able to have sticky headers on page scroll, exactly like it works when we don't have scrollable enabled. 

**Minimal reproduction of the problem with instructions**
1. Create p-table and populate with data
2. Implement sticky headers as intended on the docs, see them working
3. set [scrollable]="true" on the table so it has horizontal scroll, see sticky headers not working anymore

**What is the motivation / use case for changing the behavior?**
I need to have sticky headers have the same behavior with scrollable true, as when it has scrollable false. This bug has forced us to set an ugly undesired scrollHeight which was not the desired behavior in our project, infinite vertical scroll with sticky headers should be possible when we enable horizontal scrolling.

**Please tell us about your environment:**

* **Angular version:**
v13

* **PrimeNG version:** 
v13.0.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Tested on all major browsers
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
4.4

**Comment by chandan-bcsg** [comment]
I am also facing the same issue post primeng/angular upgrade to 13

**Comment by yigitfindikli** [comment]
You need to set scrollHeight. If you want full page scroll then you need to use scrolHeight="flex".

**Comment by danilobassi8** [comment]
> You need to set scrollHeight. If you want a full page scroll then you need to use scrolHeight="flex".

Hi, I'm using scrollHeihgt="flex", but in that case, sticky headers are not working. (They are working with a fixed height)

**Comment by rghv932** [comment]
Anu update on this yet?
