### ISSUE TITLE
Table with inline editing does not support column titles in stack layout

### ISSUE THREAD

**Issue by Wandmalfarbe** [primefaces/primeng#11106]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/github/primefaces/primeng-issue-template](https://stackblitz.com/edit/primeng-tableedit-demo-qtuls5?file=src/app/app.component.html)

![bug-primeng-responsive-table-column-title](https://user-images.githubusercontent.com/17237627/150956916-e035f68d-f928-4831-93c8-1d9624f3e03a.PNG)

**Current behavior**

When adding a responsive column title with `<span class="p-column-title">Some Title</span>` in front of the column content to the example *Table > Edit > Cell editing* it is completely ignored. The title should be hidden on large screens (it is not) and the title should be visible on small screens (it is always visible).

**Expected behavior**

The title should be hidden on large screens and the title should be visible on small screens.

**Minimal reproduction of the problem with instructions**

Add a responsive column title to a table with editable columns like in the following code. The value for `responsiveLayout` on the table has to be `stack`.

```html
<ng-template pTemplate="body" let-product>
            <tr>
                <td pEditableColumn>
                    <p-cellEditor>
                        <ng-template pTemplate="input">
                           <span class="p-column-title">Some Title</span><input pInputText type="text" [(ngModel)]="product.code">
                        </ng-template>
                        <ng-template pTemplate="output">
                           <span class="p-column-title">Some Title</span>{{product.code}}
                        </ng-template>
                    </p-cellEditor>
                </td>
...
```

**What is the motivation / use case for changing the behavior?**

Adding a title `<span class="p-column-title">` with the `responsiveLayout=stack` can't be used because the title is always visible even on large screens.

**Please tell us about your environment:**

* **OS:** Windows
* **Browser:** Firefox 95.0b8 (64-bit) / Chrome 97.0.4692.71 (64-Bit)
* **Angular version:** 13.0.3
* **PrimeNG version:** 13.0.4
* **Language:** TypeScript ~4.0.2
* **Node (for AoT issues):** v16.13.1

**Comment by cetincakiroglu** [comment]
Hi,

The problem is caused by extra span elements with `p-column-title` class. Here is the refactored and working version of your Stackblitz example.

https://stackblitz.com/edit/primeng-tableedit-demo-nmtxpm?file=src/app/app.component.html

Regards

**Comment by Wandmalfarbe** [comment]
> The problem is caused by extra span elements with `p-column-title` class.

Yes, I know. That's what I'm trying to do. The documentation for the example [Table > Responsive](https://primefaces.org/primeng/showcase/#/table/responsive) expects an element `<span class="p-column-title">???</span>` before the actual data. This element controls the label on small screens. The following code is from the showcase:

```
<p-table responsiveLayout="stack" [value]="products">
        <ng-template pTemplate="caption">
            Stack
        </ng-template>
        <ng-template pTemplate="header" let-columns>
            <tr>
                <th>Name </th>
                <th>Price</th>
                <th>Category</th>
                <th>Quantity</th>
                <th>Status</th>
                <th>Reviews</th>
            </tr>
        </ng-template>
        <ng-template pTemplate="body" let-product let-columns="columns">
            <tr>
                <td><span class="p-column-title">Name</span>{{product.name}}</td>
                <td><span class="p-column-title">Price</span>{{product.price | currency:'USD'}}</td>
                <td><span class="p-column-title">Category</span>{{product.category}}</td>
                <td><span class="p-column-title">Quantity</span>{{product.quantity}}</td>
                <td><span class="p-column-title">Status</span><span [class]="'product-badge status-' + (product.inventoryStatus ? product.inventoryStatus.toLowerCase() : '')">{{product.inventoryStatus}}</span></td>
                <td><span class="p-column-title">Reviews</span><p-rating [ngModel]="product.rating" [readonly]="true" [cancel]="false"></p-rating></td>
            </tr>
        </ng-template>
    </p-table>
```

It is currently not possible to use tables with inline editing and a stack layout because the element `<span class="p-column-title">???</span>` is not hidden on a large screen. It should only be visible on small screens.

**Comment by LimbersMay** [comment]
Any update of this? I'm trying to get something similar to what Wandmalfarbe wants
