### ISSUE TITLE
ListBox with multiple selection doesn't mimic native HTML multi-select behavior

### ISSUE THREAD

**Issue by marob** [primefaces/primeng#11102]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
ListBox with multiple selection doesn't mimic completely the native HTML multi-select behavior:
- selection of multiple options by clic (mousedown) + drag doesn't work
- selection of multiple options using shift key doesn't work

**Expected behavior**
Mimic native HTML component behavior as much as possible.

N.B.: native behavior can be a little different depending on the browser. For example, when CTRL+click+drag over already selected options, FF will toggle the selection of values while Chrome will pass to selected/deselected depending on the selection status of the first option clicked.

Firefox:
![ff](https://user-images.githubusercontent.com/3486231/150524697-c8bd4ee5-de44-44f6-a724-cbd036ee1789.gif)

Chrome:
![chrome](https://user-images.githubusercontent.com/3486231/150524695-90e39699-3a43-4367-803f-5c8514f2a7ef.gif)

**What is the motivation / use case for changing the behavior?**
Better user experience by making the component similar to a native HTML component.

* **PrimeNG version:** 13.1.0

**Comment by marob** [comment]
This extends https://github.com/primefaces/primeng/issues/10867 issue.
I am currently developing an implementation: https://github.com/marob/primeng/tree/fix_%2311102

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
