### ISSUE TITLE
p-table  scrollable= true ignores the column width and all columns getting evenly distributed .

### ISSUE THREAD

**Issue by chandan-bcsg** [primefaces/primeng#11109]
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.4
@angular-devkit/build-angular   13.1.4
@angular-devkit/core            13.1.4
@angular-devkit/schematics      13.1.4
@angular/cli                    13.1.4
@angular/flex-layout            9.0.0-beta.31
@schematics/angular             13.1.4
ng-packagr                      13.1.3
rxjs                            6.5.5
typescript                      4.5.5
------------------------------------------------------
Angular CLI: 13.1.4
Node: 14.18.3
Package Manager: npm 8.3.2
OS: win32 x64
-------------------------------------------
"primeng": "^13.0.4",

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
