### ISSUE TITLE
Dropdown in Table is cut off or closes automatically

### ISSUE THREAD

**Issue by Wandmalfarbe** [primefaces/primeng#11105]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

The Bug is reproducible on the PrimeNG example website (Table > Edit > Row Editing). Please see the attached GIF:

https://www.primefaces.org/primeng/showcase/#/table/edit

*Reproduction GIF with PrimeNG 13.1.0*

![bug-primeng-table-dropdown-version-13](https://user-images.githubusercontent.com/17237627/150948939-77b9c128-4685-4bea-b434-c2114b02eaa9.gif)

*Reproduction GIF with PrimeNG 12.2.4-lts*

![bug-primeng-table-dropdown-version-12](https://user-images.githubusercontent.com/17237627/150948930-ab07a889-25d8-429b-951f-ac728bb47c27.gif)

**Current behavior**

When opening a dropdown on the bottom of a row editing table, the dropdown extends outside the table, but it is cut off. Sometimes the dropdown doesn't even open completely and immediately. This occurs only when the dropdown content extends outside the table bounds.

**Expected behavior**

When a dropdown extends outside the table content, it is not cut off. The dropdown extends further and options outside the table can be clicked. The dropdown stays open until I click elsewhere.

**Minimal reproduction of the problem with instructions**

1. Open the PrimeNG example website (Table > Edit > Row Editing). https://www.primefaces.org/primeng/showcase/#/table/edit
2. Scroll to the example *Row Editing*.
3. Edit the last row.
4. Click on the now visible dropdown for *category* in the currently edited row.
5. The dropdown extends outside the table, but it is cut off. Sometimes it closes automatically.

**What is the motivation / use case for changing the behavior?**

This is a regression, since it doesn't occur with PrimeNG 11.4.9 (LTS). The described behavior is currently present in the versions > 11.4.9.

**Please tell us about your environment:**

* **OS:** Windows
* **Browser:** Firefox 95.0b8 (64-bit)
* **Angular version:** 12.0.5 (The issue is present regardless of angular version)
* **PrimeNG version:** 13.1.0 and 12.2.4
* **Language:** TypeScript ~4.4.2
* **Node (for AoT issues):** v16.13.1

**Comment by cetincakiroglu** [comment]
Hi,

To solve this issue, we have **appendTo** input property for dropdown.  You can use it like this with table edit.

`                    <td>
                        <p-cellEditor>
                            <ng-template pTemplate="input">
                                <p-dropdown appendTo="body" [options]="statuses" [(ngModel)]="product.inventoryStatus" [style]="{'width':'100%'}"></p-dropdown>
                            </ng-template>
                            <ng-template pTemplate="output">
                                {{product.inventoryStatus}}
                            </ng-template>
                        </p-cellEditor>
                    </td>`

**Comment by Wandmalfarbe** [comment]
@cetincakiroglu should this be mentioned in the documentation in the Table > Edit example (https://primefaces.org/primeng/showcase/#/table/edit)? The example is currently broken because it uses a Dropdown **without** `appendTo="body"`.

**Comment by FehGusto** [comment]
Thanks!
--- appendTo="body" --- solved the problem!
