### ISSUE TITLE
new freature "expandToNode" for TreeTable

### ISSUE THREAD

**Issue by jisqaqov** [primefaces/primeng#1110]
Good day. I would like to suggest new freature "expandToNode" for TreeTable like in Tree component.
Also could you please consider extra feature to move scroll position to selected item when selection changes programmatically.

**Comment by JakeSummers** [comment]
Hi @jisqaqov,

There already is an expandToNode method on the tree called expandToNode see here:

https://github.com/primefaces/primeng/blob/master/components/tree/tree.ts#L292

Jake

**Comment by mmlitvin** [comment]
I am confused here. Why was this suggestion closed? I also would love to see a new method "expandToNode" for TreeTable just like the one in Tree component.  Jake - the method you are pointing to is a method for a Tree and not a TreeTable component. Am I missing something ?
Thank you
