### ISSUE TITLE
Column filtering does not match characters with tones with the same character without tone

### ISSUE THREAD

**Issue by Nickath** [primefaces/primeng#11115]
I want to perform filtering into columns of a table that contains data in **Greek language**.

Unfortunately the `<p-columnFilter>` component internally **does not seem to recognize the characters with tones to be the same with the same character without a tone**. For example a vowel with a tone (ή) **is not matched with the same vowel witout tone** (η).

In most filters out there on the web, characters with tone are matched with the same characters without tone and vice versa. **Is this a bug or am I missing something?**

**Comment by Nickath** [comment]
I managed to fix that by overriding the filter service in the components that include the tables following [this](https://stackblitz.com/edit/primeng-filterservice-demo-qv3t3k?file=src%2Fapp%2Fapp.component.ts)

Example shown below:


` constructor(private filterService: FilterService) {

  }
  //1. OVERRIDE 'CONTAINS' FILTERING
    this.filterService.register('contains', (value: any, filter: any): boolean => {
      if (filter === undefined || filter === null || filter.trim() === '') {
        return true;
      }

      if (value === undefined || value === null) {
        return false;
      }

      let x: string = value.toString().toLowerCase();
      x = x.normalize("NFD").replace(/[\u0300-\u036f]/g, "")
      let f: string = filter.toString().toLowerCase();
      f = f.normalize("NFD").replace(/[\u0300-\u036f]/g, "")
      return localeIncludes(x, f, {
        usage: 'search',
        sensitivity: 'base',
      });
    });
    
    //2. OVERRIDE 'STARTS WITH'
    this.filterService.register('startsWith', (value: any, filter: any): boolean => {
      if (filter === undefined || filter === null || filter.trim() === '') {
        return true;
      }

      if (value === undefined || value === null) {
        return false;
      }

      let x: string = value.toString().toLowerCase();
      x = x.normalize("NFD").replace(/[\u0300-\u036f]/g, "")
      let f: string = filter.toString().toLowerCase();
      f = f.normalize("NFD").replace(/[\u0300-\u036f]/g, "")
      return x.startsWith(f);
    });
    
    `

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
