### ISSUE TITLE
Virtual Scroll behaviour is broken when combined with Row Expand

### ISSUE THREAD

**Issue by EzaBlade** [primefaces/primeng#11111]
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

**Current behavior**

When row expansion is used with virtual scrolling the table breaks. To confirm this I pulled the latest code from GitHub and made a simple change to the showcase example for virtual scrolling. In the the 'tablevirtualscrolldemo.html' file I added the template for an expanded row as follows:-

```
<ng-template pTemplate="rowexpansion" let-rowData>
    <tr>
        <td>Lorem ipsum dolor sit amet, consectetur.</td>
    </tr>
</ng-template>
```

and a console log of the loaded cars in the lazy load event:- 

```
loadCarsLazy(event: LazyLoadEvent) {       
      //simulate remote connection with a timeout 
      setTimeout(() => {
          //load data of required page
          let loadedCars = this.cars.slice(event.first, (event.first + event.rows));

          console.log(loadedCars);

          //populate page of virtual cars
          Array.prototype.splice.apply(this.virtualCars, [...[event.first, event.rows], ...loadedCars]);
          
          //trigger change detection
          this.virtualCars = [...this.virtualCars];
      }, Math.random() * 1000 + 250);
  }
```

With this set up I get the following errors multiple times in F12 when the table is loading. The lazy load event console output occurs in between the errors:-

![image](https://user-images.githubusercontent.com/1561611/151569343-b22b0471-630b-4396-986f-bf417aeadce2.png)

Please tell us about your environment:
Windows 10

Angular version: 12

PrimeNG version: 12.2.2

Browser: Chrome 95.0.4638.69 (Official Build) (64-bit)

Language: [all | TypeScript X.X | ES6/7 | ES5]

Node (for AoT issues): node --version =

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
