### ISSUE TITLE
Having Issue with group multi select with virtual scroll

### ISSUE THREAD

**Issue by mganigapeta** [primefaces/primeng#11116]
I had 2500 records for multi select with group option so that time page getting struck after some time page going to unresponsive and with small amount data dropdown not aligned properly 
<p-multiSelect [options]="groupedCars" [group]="true" [(ngModel)]="selectedCities4" defaultLabel="Select a City" scrollHeight="250px" display="chip" [virtualScroll]="true" [filter]="true" [itemSize]="34" >
	<ng-template let-group pTemplate="group">
			<div class="flex align-items-center">
					<span>{{group.label}}</span>
			</div>
	</ng-template>
</p-multiSelect>

**Comment by yigitfindikli** [comment]
Please use forum or discord channel for questions and help requests.
