### ISSUE TITLE
Primeng Table Scrollable=horizontal doesn't take width size

### ISSUE THREAD

**Issue by cangunaydin** [primefaces/primeng#11114]
* **Angular version:** 
     Angular v 13.1.0

* **PrimeNG version:** 
   Primeng v 13.1.0

Hello,
We use primeng table in our project, and now we updated the package to v13.1.0, we want to use scrollable, with only horizontal direction. According to docs I am quoting over here.

> Column Widths of a Scrollable Table
Scrollable table uses flex layout so there are a couple of rules to consider when adjusting the widths of columns.
Use min-width in vertical scrolling only so that when there is enough space columns may grow and for smaller screens a horizontal scrollbar is displayed to provide responsive design.
**When horizontal scrolling is enabled, prefer width instead of min-width.**
In vertical scrolling only, use flex to disable grow and shrink while defining a initial width. When horizontal scrolling is enabled, this is not required as columns do not grow or shrink in horizontal scrolling.

i believe i need to use width to adjust the size, but this doesn't change anything on p-table. i created a stackblitz for you to see the problem. here is the url. (this one is a fork from your examples, i have changed the scrollDirection property only)
https://stackblitz.com/edit/primeng-tablescroll-demo-tahpxq?file=src/app/app.component.html

when you open the example you can see that first column width is <th style="width:100px">Id</th> 100px but it gets the same size with other columns. Interestingly if i use min-width then it works as i expected.

So the question is, is there any downside of using min-width? and why the docs are saying vice versa? 

Thanks for the help and assistance.

**Comment by yigitfindikli** [comment]
This is the behavior of flex. You can use flex-basis and flex-grow instead of width.
