### ISSUE TITLE
Dropdown optionLabel improvement

### ISSUE THREAD

**Issue by luboslav** [primefaces/primeng#11110]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

We are using **ng-template** to translate label using ngx-translate pipe, so we do not have any value to set to optionLabel. 

```
<p-dropdown [options]="availableLanguages" [(ngModel)]="selectedLanguage">
  <ng-template let-lang pTemplate="selectedItem">
    {{ lang .name | translate }}
  </ng-template>
  <ng-template let-lang pTemplate="item">
    {{ lang .name | translate }}
  </ng-template>
</p-dropdown>
```
Dropdown component throws ```TypeError: this.getOptionLabel(...).toLocaleLowerCase is not a function``` when user type while dropdown component has focus.

**Expected behavior**

There should be an option to set **optionLabel** as observable or at least the dropdown should not throw error when optionLabel is not provided. 

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 13

* **PrimeNG version:** 13

* **Browser:** all

 
* **Language:** all

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
