### ISSUE TITLE
new features to TreeTable and Tree

### ISSUE THREAD

**Issue by jisqaqov** [primefaces/primeng#1111]
Good day. I would like to suggest new features to TreeTable and Tree:
1. scrollable
2. pagination
3. checkbox selection
4. column resize 
5. expandToNode
6. scroll to selection (programmatically)

**Comment by JakeSummers** [comment]
Hi @jisqaqov,

There already is an expandToNode method on the tree called `expandToNode` see here:

https://github.com/primefaces/primeng/blob/master/components/tree/tree.ts#L292

You can add checkbox selection using the [tree's template feature](http://www.primefaces.org/primeng/#/tree)

Jake

**Comment by jisqaqov** [comment]
Hello JakeSummers.
Regarding your reply, as for expandToNode it is needed in TreeTable. So the feature is essential.
As for checkbox selection it is should be implemented like in "primefaces". Checkbox selection is very crucial, for example if you check the parent node, all child nodes should be checked relatively. Look at the primefaces demo of TreeTable.

**Comment by cagataycivici** [comment]
Thanks but issue is to broad, each of these should better be files as different tickets.

**Comment by jisqaqov** [comment]
Ok. I have created new issues for each point separately.

**Comment by finalxcode** [comment]
+1
