### ISSUE TITLE
Skeleton loader doesn't work during VirtualScroller lazy loading

### ISSUE THREAD

**Issue by mblaze1986** [primefaces/primeng#11118]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

https://stackblitz.com/edit/primeng-virtualscroller-demo-6jumei?file=package.json

**Current behavior**
Skeleton loader doesn't work during VirtualScroller lazy loading.

**Expected behavior**

Skeleton loader should be displayed during VirtualScroller lazy loading.

* **Angular version:** 5.X
12.2.14

* **PrimeNG version:** 5.X
12.2.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 97.0.4692.99

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
