### ISSUE TITLE
Table Filters - Documentation Lacking

### ISSUE THREAD

**Issue by psarno** [primefaces/primeng#11123]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

n/a

Regarding: https://www.primefaces.org/primeng/showcase/#/table/filter

**Current behavior**
This is an issue with documentation for the Table filter controls.

I am unsure how to get access to the filtered data for export purposes, the documentation page is incomplete in that it doesn't list the events and properties of the filter controls, it only presents a sample of filtering and a code block without further explanation.

**Expected behavior**

We need access to the object after PrimeNG filtering has been applied.

**Minimal reproduction of the problem with instructions**

Filter a PrimeNG table component, attempted to subscribe to various filtering events but the documentation doesn't specify what to do in this case.

**What is the motivation / use case for changing the behavior?**

Exporting filtered results to CSV/XLS.

**Please tell us about your environment:**

n/a

* **Angular version:** 5.X
13.1.1

* **PrimeNG version:** 5.X
13.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

TypeScript 4.5.4
"target": "es2020",
"module": "es2022",

* **Node (for AoT issues):** `node --version` =   

16.13.1

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
