### ISSUE TITLE
p-scrollTop throwing an error when trying to run in an Angular Universal SSR environment.

### ISSUE THREAD

**Issue by ugumerie** [primefaces/primeng#11128]
I'm submitting a
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

Running the command `npm run dev:ssr` will throw a '`ReferenceError: window is not defined at ScrollTop.unbindDocumentScrollListener`' error on the browser when launch with the localhost URL, until the component `<p-scrollTop></p-scrollTop>` is commented out. **Note:** The application compiles on build.

**Expected behavior**

The `<p-scrollTop></p-scrollTop>` renders perfectly with all its behaviors on a SPA environment

**Minimal reproduction of the problem with instructions**

1. Installed angular universal on the SPA
2. Did `npm run dev:ssr` on the terminal
3.  Got `ReferenceError: window is not defined at ScrollTop.unbindDocumentScrollListener .....` on the browser when launched.
4. ![p-scrollTop error](https://user-images.githubusercontent.com/25312540/152182218-da74c6cc-2c5a-44d8-9f16-d7a5ba788db4.jpg)
5. [Little solution to by-pass the error on SSR environment](https://stackblitz.com/edit/github-khmatp)

**What is the motivation / use case for changing the behavior?**

Wanted to convert my web application to server-side for SEO purposes.

**Please tell us about your environment:**

Operating System: Windows 10
IDE: VSCode
Package manager: npm
Dev Server: nodejs

* **Angular version:** 13.2.0

* **PrimeNG version:** ^13.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

  [Chrome 96.X.X | Firefox 97.X.X  | IE 97.X.X]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
[TypeScript 4.5.2 | ES7]

* **Node (for AoT issues):** `node --version` =  16.3.1

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
