### ISSUE TITLE
Table | Row Expansion and Selection not Working Together

### ISSUE THREAD

**Issue by yigitfindikli** [primefaces/primeng#11129]
https://stackblitz.com/edit/primeng-tablerowgroup-demo-4wkgpe?file=src%2Fapp%2Fapp.component.html

**Comment by shahrishabhptechnical** [comment]
when is this expected to fix?

**Comment by shahrishabhptechnical** [comment]
any update on this?

**Comment by codehunter13** [comment]
any update?

**Comment by hohnworld** [comment]
checked one，checked all，but only the one clicked row is the selected Array

"primeng": "^13.1.0",

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by Fraser12345** [comment]
Still not working. For selecting is necessary to have dataKey as item id. But in that case grouping is not working.
