### ISSUE TITLE
VirtualScroll=true breaks rowspan table header grouping

### ISSUE THREAD

**Issue by EzaBlade** [primefaces/primeng#11131]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Grouping of the table headers using rowspan is broken by virtual scrolling. I had a table with grouped column headers and pagination. Then I had to change to virtual scrolling for the user's preference and now it is broken.

**Before**

![image](https://user-images.githubusercontent.com/1561611/152398724-5154bf3a-6d8a-46aa-bbe8-03af3f354d0d.png)

**After** - the two header rows are completely separate with no grouping

![image](https://user-images.githubusercontent.com/1561611/152399006-68eda454-9829-4d8a-bfcc-9abaad2756a7.png)

Also notice that the controls in my filtering row have been affected too

Is anything at all going to be done about this - I'm starting too see a pattern where virtualScrolling is being flagged up as a problem more than a few times.

Please tell us about your environment:
Windows 10

**Angular version**: 12

**PrimeNG version**: 12.2.2

**Browser**: Chrome 95.0.4638.69 (Official Build) (64-bit)

**Language**: [all | TypeScript X.X | ES6/7 | ES5]

**Node (for AoT issues)**: node --version =

**Comment by yigitfindikli** [comment]
Issue is not clear, please feel free to reopen with a stackblitz example.

**Comment by martinkasa** [comment]
We have the same issue. Problem is because of "new" way how table is rendered. Display type is flex instead of table-row and table-cell and it in this case rowspan is not working. 

So @yigitfindikli is there any way how to create header where some cells are 2 rows high and some not? (example below)
![i4q6M](https://user-images.githubusercontent.com/32707615/153004052-25c2b4a0-7afa-4237-ac73-92927ace2222.jpg)
