### ISSUE TITLE
PrimeNG Error in CI Environment but not in local

### ISSUE THREAD

**Issue by sundeepsapiens** [primefaces/primeng#11133]
Hi All,

   We have upgraded application from angular 7 to angular 12 version, upgraded PrimeNg version to 11.4.5 and using the licensed version of PrimeNg. After this upgrade, UI works fine with the new features of PrimeNg and specs/Test cases are running fine in local.
   
   Unfortunately in CI we see a test failure mentioned below and it is not part of any of the spec files, not able to reproduce this issue in local. And this particular error is repeatedly shown in CI
   
   I am not able to proceed further, so requesting any suggestions or help to proceed further.
   
   Error which we are seeing in CI is below
   
Thanks,
Sundeep
   
  Chrome Headless 92.0.4515.159 (Linux x86_64) ERROR: 'ERROR', TypeError: Cannot read property 'offsetHeight' of null
[INFO] TypeError: Cannot read property 'offsetHeight' of null
[INFO]     at Function.DomHandler.relativePosition (http://localhost:9876/base/node_modules/primeng/bundles/primeng-dom.umd.js:407:39)
[INFO]     at Menu.alignOverlay (http://localhost:9876/base/node_modules/primeng/bundles/primeng-menu.umd.js:392:32)
[INFO]     at Menu.onOverlayAnimationStart (http://localhost:9876/base/node_modules/primeng/bundles/primeng-menu.umd.js:378:30)
[INFO]     at Object.eval [as handleEvent] (ng:///MenuModule/Menu.ngfactory.js:189:27)
[INFO]     at handleEvent (http://localhost:9876/base/node_modules/@angular/core/bundles/core.umd.js:32556:106)
[INFO]     at callWithDebugContext (http://localhost:9876/base/node_modules/@angular/core/bundles/core.umd.js:33634:29)
[INFO]     at Object.debugHandleEvent [as handleEvent] (http://localhost:9876/base/node_modules/@angular/core/bundles/core.umd.js:33355:16)
[INFO]     at dispatchEvent (http://localhost:9876/base/node_modules/@angular/core/bundles/core.umd.js:24202:29)
[INFO]     at eval (http://localhost:9876/base/node_modules/@angular/core/bundles/core.umd.js:31768:42)
[INFO]     at eval (http://localhost:9876/base/node_modules/@angular/platform-browser/bundles/platform-browser-animations.umd.js:516:29)
[INFO]     at Array.forEach (<anonymous>)
[INFO]     at eval (http://localhost:9876/base/node_modules/@angular/platform-browser/bundles/platform-browser-animations.umd.js:514:57)
[INFO]     at ZoneDelegate.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?1a4a4ec98c820a83594ebcddc0d5c23fdaa2416a:400:30)
[INFO]     at ProxyZoneSpec.onInvoke (http://localhost:9876/base/node_modules/zone.js/dist/proxy.js?47841e0e92619c649f2967d0cc4975fe53b15ebe:126:43)
[INFO]     at ZoneDelegate.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?1a4a4ec98c820a83594ebcddc0d5c23fdaa2416a:399:56)
[INFO]     at Object.onInvoke (http://localhost:9876/base/node_modules/@angular/core/bundles/core.umd.js:29373:37)
[INFO]     at ZoneDelegate.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?1a4a4ec98c820a83594ebcddc0d5c23fdaa2416a:399:56)
[INFO]     at Zone.run (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?1a4a4ec98c820a83594ebcddc0d5c23fdaa2416a:160:47)
[INFO]     at NgZone.run (http://localhost:9876/base/node_modules/@angular/core/bundles/core.umd.js:29226:32)
[INFO]     at eval (http://localhost:9876/base/node_modules/@angular/platform-browser/bundles/platform-browser-animations.umd.js:513:33)
[INFO]     at ZoneDelegate.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?1a4a4ec98c820a83594ebcddc0d5c23fdaa2416a:400:30)
[INFO]     at ProxyZoneSpec.onInvoke (http://localhost:9876/base/node_modules/zone.js/dist/proxy.js?47841e0e92619c649f2967d0cc4975fe53b15ebe:126:43)
[INFO]     at ZoneDelegate.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?1a4a4ec98c820a83594ebcddc0d5c23fdaa2416a:399:56)
[INFO]     at Zone.run (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?1a4a4ec98c820a83594ebcddc0d5c23fdaa2416a:160:47)
[INFO]     at http://localhost:9876/base/node_modules/zone.js/dist/zone.js?1a4a4ec98c820a83594ebcddc0d5c23fdaa2416a:1318:38
[INFO]     at ZoneDelegate.invokeTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?1a4a4ec98c820a83594ebcddc0d5c23fdaa2416a:434:35)
[INFO]     at ProxyZoneSpec.onInvokeTask (http://localhost:9876/base/node_modules/zone.js/dist/proxy.js?47841e0e92619c649f2967d0cc4975fe53b15ebe:157:43)
[INFO]     at ZoneDelegate.invokeTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?1a4a4ec98c820a83594ebcddc0d5c23fdaa2416a:433:64)
[INFO]     at Zone.runTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?1a4a4ec98c820a83594ebcddc0d5c23fdaa2416a:205:51)
[INFO]     at drainMicroTaskQueue (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?1a4a4ec98c820a83594ebcddc0d5c23fdaa2416a:620:39)
[INFO]     at ZoneTask.invokeTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?1a4a4ec98c820a83594ebcddc0d5c23fdaa2416a:520:25)
[INFO]     at ZoneTask.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?1a4a4ec98c820a83594ebcddc0d5c23fdaa2416a:505:52)
[INFO]     at data.args.<computed> (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?1a4a4ec98c820a83594ebcddc0d5c23fdaa2416a:3063:36)

**Comment by yigitfindikli** [comment]
Please use the forum or discord channel for questions and help requests.
