### ISSUE TITLE
Number Input key handling breaks if the input's type is set to 'number'

### ISSUE THREAD

**Issue by Vernon-Accela** [primefaces/primeng#11130]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewed in detail and assisted.

**https://stackblitz.com/github/wmaiqvlqx?devtoolsheight=33&file=src/app/app.component.ts**

**Current behavior**

Currently, the Primeng Number Input fails accessibility scans since it has a `aria-valuenow` attribute but doesn't define the `type `attribute on the input. Consequently, screen readers can't identify the `aria-valuenow` attribute as valid since they check the input type first. To address this, we tried to set the input type properly.

Unfortunately, primeng's input handling behavior breaks if the input's `type `is ever set, creating a Catch22 scenario where you cannot pass client's accessibility checks but cannot correct the accesibility issue either without introducing a greater problem whereas your typed input doesn't appear in the expected positions in the field.

As you can see in the example, the input with the type set puts the client's entered text in the wrong place. 

**Expected behavior**

That the user can set the input type in line with accessibility standards and not have the input behavior break

**Minimal reproduction of the problem with instructions**
Outside of the attached StackBlitz, you can also reproduce by simply finding the `<input>` and setting a `type` of `number`. Then try to enter a number into the input

**What is the motivation / use case for changing the behavior?**

Our clients are required by law to meet accessibility standards. Currently, this is being listed as a serious breaking problem in both AXE and the client's accessibility scanners

**Please tell us about your environment:**
N/A
Reproduced in ASP.NET, NodeJs, and StackBlitz

* **Angular version:** 
12.2.14 - 13.0.3

* **PrimeNG version:** 
12.2.5 - 13.0.4

* **Browser:** [all  ]
Tested in Edge, Chrome, Firefox
 
* **Language:** [ES6]

* **Node (for AoT issues):** `node --version` =  14.15

**Comment by cetincakiroglu** [comment]
Hi,

By using Axe Devtools, we couldn't replicate the problem.

Regards

**Comment by rustam0533** [comment]
@cetincakiroglu could you please give feedback to the above issue? the issue still exists with primeng@17 ,Angular@17.
