### ISSUE TITLE
p-table, using rowGroupMode, rowexpansion with p-tableCheckbox seems not work

### ISSUE THREAD

**Issue by KeithPoonNS** [primefaces/primeng#11148]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/primeng-tablerowgroup-demo-8pyfgg?file=src%2Fapp%2Fapp.component.html

**Current behavior**

if i checked the box of tableCheckbox, then all the tableCheckboxes will going to be checked
```
<p-tableCheckbox [value]="customer" [index]="customer.name">
          </p-tableCheckbox>
```

**Expected behavior**

i am expecting the p-tablecheckbox will works like the p-checkbox in the demonstration.
```
<p-checkbox
            [value]="customer"
            [(ngModel)]="selectedInspectionTupleList"
          >
          </p-checkbox>
```

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 13.*

* **PrimeNG version:** 13.0.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5] TypeScript 4.0

* **Node (for AoT issues):** `node --version` =

**Comment by yigitfindikli** [comment]
Duplicate https://github.com/primefaces/primeng/issues/11129

**Comment by hohnworld** [comment]
checked one，checked all，but only the one clicked row is the selected Array
