### ISSUE TITLE
After resize, frozen column is abnormal when table is scroll.

### ISSUE THREAD

**Issue by HangZhouWan** [primefaces/primeng#11149]
**I'm submitting a bug report
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/github-b9qp98?file=src%2Fapp%2Fapp.component.html

**Current behavior**
frozen column border is gone when table scroll to right.

**Expected behavior**
frozen column border  should display well.

**Minimal reproduction of the problem with instructions**
open the demo by  https://stackblitz.com/edit/github-b9qp98?file=src%2Fapp%2Fapp.component.html
  step 1. resize any of column in the table.
  step 2. unselect some column by the multiselect in table header.
  step 3. drag the scrollbar to right  on the bottom of the table.

**What is the motivation / use case for changing the behavior?**
n/a

**Please tell us about your environment:** ubuntu

* **Angular version:** 13.0.3

* **PrimeNG version:** 13.1.0

* **Browser:** chrome 97.0.4692.99
 
* **Language:** TypeScript~4.0.2

* **Node (for AoT issues):** `node --version` =   12.22.9

**Comment by yigitfindikli** [comment]
We couldn't replicate it with your instructions and your stackblitz example. Feel free to open a new issue ticket with different instructions or a stackblitz example.

**Comment by HangZhouWan** [comment]
![image](https://user-images.githubusercontent.com/17522306/153159983-d6094265-735f-43f7-a998-9acd82266fab.png)
@yigitfindikli problem still there, please flow my steps to  replicate it
