### ISSUE TITLE
p-table drag column is not working

### ISSUE THREAD

**Issue by waratah** [primefaces/primeng#11156]
```
[X ] feature request => Please check if request is not on the roadmap already 
```
**Current behavior**

The following code make the presumption that all columns are draggable so it rearranges the wrong columns.  In my case I want my checkbox column and menu column to remain at the front of the columns at all times.   Simplest solution is to make them not dragable by not including the preorderablecolumn attribute

```
  let dragIndex = DomHandler.indexWithinGroup(this.draggedColumn, 'preorderablecolumn');
      let dropIndex = DomHandler.indexWithinGroup(dropColumn, 'preorderablecolumn');
```
**Expected behavior**

I don't want my first two column dragable so I don't flag them and it works.

**Please tell us about your environment:**
Windows 10
* **Angular version:** 13
* **PrimeNG version:** 13.1
* **Browser:** Chrome

**Comment by cetincakiroglu** [comment]
Hi,

You achieve this by using pReorderableColumnDisabled with array.slice as the example below:

```
    <div class="card">
        <p-table [value]="products" [columns]="cols" [reorderableColumns]="true" responsiveLayout="scroll">
            <ng-template pTemplate="header" let-columns>
                <tr>
                    <th style="width:3rem"></th>
                    <th *ngFor="let col of columns.slice(0,2)" pReorderableColumn>
                        {{col.header}}
                    </th>
                    <th *ngFor="let col of columns.slice(2,4)" pReorderableColumnDisabled>
                        {{col.header}}
                    </th>
                </tr>
            </ng-template>
            <ng-template pTemplate="body" let-rowData let-columns="columns" let-index="rowIndex">
                <tr [pReorderableRow]="index">
                    <td>
                        <span class="pi pi-bars" pReorderableRowHandle></span>
                    </td>
                    <td *ngFor="let col of columns">
                        {{rowData[col.field]}}
                    </td>
                </tr>
            </ng-template>
        </p-table>
    </div>
```

**Comment by waratah** [comment]
that makes no sense.On 16 Feb 2022 11:56 pm, Çetin ***@***.***> wrote:
Hi,
You achieve this by using pReorderableColumnDisabled with array.slice as the example below:
    <div class="card">
        <p-table [value]="products" [columns]="cols" [reorderableColumns]="true" responsiveLayout="scroll">
            <ng-template pTemplate="header" let-columns>
                <tr>
                    <th style="width:3rem"></th>
                    <th *ngFor="let col of columns.slice(0,2)" pReorderableColumn>
                        {{col.header}}
                    </th>
                    <th *ngFor="let col of columns.slice(2,4)" pReorderableColumnDisabled>
                        {{col.header}}
                    </th>
                </tr>
            </ng-template>
            <ng-template pTemplate="body" let-rowData let-columns="columns" let-index="rowIndex">
                <tr [pReorderableRow]="index">
                    <td>
                        <span class="pi pi-bars" pReorderableRowHandle></span>
                    </td>
                    <td *ngFor="let col of columns">
                        {{rowData[col.field]}}
                    </td>
                </tr>
            </ng-template>
        </p-table>
    </div>
