### ISSUE TITLE
Cannot find module 'xlsx' or its corresponding type declaration when exporting 

### ISSUE THREAD

**Issue by muldon** [primefaces/primeng#11165]
[ x ] bug report  
[ ] feature request 
[ ] support request 

**Reproduction case:**
https://stackblitz.com/edit/primeng-tableexport-demo?file=src%2Fapp%2Fapp.component.html

**Current behavior**
Instead of opening the demo table, a message is shown: 
"Error in src/app/app.component.ts (37:12)
Cannot find module 'xlsx' or its corresponding type declarations."

**Expected behavior**
demo table should be showed
 

* **Angular version:** 13.0.3 

* **PrimeNG version:** 13.0.04
 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by cetincakiroglu** [comment]
Hi,

Sorry for the missing dependencies. The demo is updated now you can use it without getting any module errors.

https://stackblitz.com/edit/primeng-tableexport-demo

Regards
