### ISSUE TITLE
Error in p-table when p-multiselect is used for Filtering

### ISSUE THREAD

**Issue by kishor-p** [primefaces/primeng#11162]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/github-mmzi8y?file=src/app/app.component.html

**Current behavior**
`p-Table` Colum filtering with Multi Select results in empty table with error in console.

**Expected behavior**
Filtering should happen.

**Minimal reproduction of the problem with instructions**
When: Any of the column values is an `Array` and `p-multiselect` is used for filtering. 
Issue: results in error

**Comment by cetincakiroglu** [comment]
Hi, 

This is not a bug, the problem is about your failing columnFilter properties.

Here is the refactored and working version of your example. 
https://stackblitz.com/edit/github-mmzi8y-nxsbc6?file=src%2Fapp%2Fapp.component.html

Regards.
