### ISSUE TITLE
Table: Add a new option for columnResizeMode

### ISSUE THREAD

**Issue by nicholas-ochoa** [primefaces/primeng#11163]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Currently, when using `columnResizeMode` with `expand` or `fit` the logic that PrimeNG performs internally heavily conflicts with the logic I am trying to implement for an application. My application manages the state of the grid including the visible columns, sorts, filters, selected row, grid data, column order and column sizes.

When I enable column resizing on the PrimeNG component, and attempt to resize a table column - the logic for both `expand` and `fit` conflict with the `width` attributes I am adding to all of the TD and TH cells in the column being resized. I am attempting to workaround this by using the `onResize` event but unfortunately due to when the event is fired I'm ending up with a weird "lag" between when I resize the column and when it actually resizes to the appropriate size.

**Expected behavior**

Is it possible to add a new `columnResizeMode` that simply does not perform any action aside from providing the column and the delta? 

https://github.com/primefaces/primeng/blob/afc0d2649f1badd522c6ab39af2a1d485c1765a9/src/app/components/table/table.ts#L1953-L1967

In this case it would just be an addtional `else if` statement when the value is `none` (or whatever other name seems appropriate) that simply does nothing. I am happy to submit a pull request if that would be considered and accepted.

Currently, I am using `expand` and removing the `width` styling added to the `table` element. This new `columnResizeMode` would eliminate that workaround.

**What is the motivation / use case for changing the behavior?**

Allow for handling table column resizing manually to enable better integration with the application using the PrimeNG component

**Please tell us about your environment:** N/A

* **Angular version:** 13.1

* **PrimeNG version:** 13.1

* **Browser:** all 

 
* **Language:** all

* **Node (for AoT issues):** `node --version` =   14.18

**Comment by nicholas-ochoa** [comment]
After posting this I tried setting `columnResizeMode` to `none` for the hell of it and it works - there is currently no validation or restriction on the value passed in. This bypassed all of the logic entirely. I was able to use this along with passing in a tableStyle of `[tableStyle]="{ minWidth: 'auto' }"` to accomplish what I needed in a clearer way.

Completely undefined behavior, but it works and might be worth just updating the documentation with this versus any code changes.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
