### ISSUE TITLE
Values do not refresh in table with flex

### ISSUE THREAD

**Issue by regis1512** [primefaces/primeng#11166]
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-xlez9c
https://github-xlez9c.stackblitz.io/

**Current behavior**
I use a table with scrollHeight="flex".
But when i add or remove an item in the array there are no change in the table.

**Expected behavior**
I expect that when i add an item there is one more row in the table
and when i remove an item the row disapear

**Minimal reproduction of the problem with instructions**
Click on "Create" button or "Delete" button.
You can see the number of rows (displayed in the table and on the first line near "Create") increase or decrease.
But in the table there are exactly the same row.

**What is the motivation / use case for changing the behavior?**
The motivation is to have a normal behavior.

**Please tell us about your environment:**
All the Operating system, All the IDE, All the HTTP server, ... -->

* **Angular version:** 5.X
13

* **PrimeNG version:** 5.X
13

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Firefox

**Comment by Phil-DS** [comment]
You don't mutate the original array, therefore there isn't any change detection.
Referencing from the table documentation on Change Detection:

>### Change Detection
>Table may need to be aware of changes in its value in some cases such as reapplying sort. For the sake of performance, this is only done when the reference of the value changes, meaning a setter is used instead of ngDoCheck/IterableDiffers which can reduce performance. So when you manipulate the value such as removing or adding an item, instead of using array methods such as push and splice, instead create a new array reference using a spread operator or similar.

Since you are adding to the array/removing from the array, you don't explicitly mutate the reference, therefore, it isn't checked on change detection.

The following works since it actually mutates the array:
```typescript
delete(index: number): void {
    this.cars = [...this.cars.slice(0,index),...this.cars.slice(index+1)]
}
```
```typescript
create(): void {
    let car = {
      vin: this.generateVin(),
      brand: this.generateBrand(),
      color: this.generateColor(),
      year: this.generateYear(),
    };
    this.cars = [...this.cars,car]
}
```

**Comment by cetincakiroglu** [comment]
Hi,

This problem is not about the PrimeNG, it's about your delete and create functions.

Here is refactored working example you can use. 

https://stackblitz.com/edit/github-xlez9c-zwspae?file=src%2Fapp%2Fapp.component.ts

Regards
