### ISSUE TITLE
Receiving a null LazyLoadEvent

### ISSUE THREAD

**Issue by SpiraMira** [primefaces/primeng#11164]
We recently switched to Angular 13 and updated to the latest primeng.  I now have a table emitting a null LazyLoadEvent.

In what case does this occur?

using "primeng": "^13.0.4"

**Comment by SpiraMira** [comment]
`                        <p-table
                            #dataTable
                            (onLazyLoad)="getRecordsIfNeeds($event)"
                            [value]="primengTableHelper.records"
                            rows="{{ primengTableHelper.defaultRecordsCountPerPage }}"
                            [paginator]="false"
                            [lazy]="true"
                            [responsive]="primengTableHelper.isResponsive"
                        >
`

**Comment by yigitfindikli** [comment]
Issue is not clear, please feel free to reopen with a stackblitz example.

**Comment by SpiraMira** [comment]
I can't provide code for our app (too large and proprietary) but as stated above our onLazyLoad event handler is sending a NULL event.  Why and when would that happen?  I can't state it any other way.  I don't see any reference to this type of use case in your documentation.
