### ISSUE TITLE
Virtual scroll +lazy load table with Route Reuse strategy

### ISSUE THREAD

**Issue by tigrenok00** [primefaces/primeng#11178]
Hi,
I'm using table with virtual scroll and lazy load and having issues when turning on angular route reuse strategy. When the table is not scrolled (first row visible) everything is fine, but when the table is scrolled to some point, coming back to the page results with the table cut to the scroll point - the headers are shown at the scroll point and the previously loaded data is missing. If I scroll a bit at this point, the data and headers are restored always from the top. Is there a fix for this, or even an event or table function that can be called to fix the table when returning to the page? (keeping the data and the scroll state, of course, this is the idea)

`    <p-table
      *ngIf="!loading"
      [value]="displayedUsers"
      [scrollable]="true"
      scrollHeight="flex"
      [virtualScroll]="true"
      [virtualRowHeight]="40"
      [lazy]="true"
      [rows]="50"
      (onLazyLoad)="lazyLoad($event)"
      [lazyLoadOnInit]="false"
      selectionMode="single"
      dataKey="userId"
    >`

![image](https://user-images.githubusercontent.com/23075641/153818159-dc25d163-7400-4ce3-98b7-1519c9ecc67b.png)

"primeng": "^13.1.0",
"@angular/core": "~13.1.3",

**Comment by yigitfindikli** [comment]
Issue is not clear, please feel free to reopen with a stackblitz example.

**Comment by tigrenok00** [comment]
@yigitfindikli 

Please let me try to explain better with another screenshot, perhaps it will be enough without stackblitz.

Before leaving the route the scrolled table looks like this:

![image](https://user-images.githubusercontent.com/23075641/153826230-8e8638b6-7571-429f-932f-3751a3da7ca6.png)


After returning to the route (we use route reuse strategy), instead of the table looking exactly the same at it was left, it looks like this:

![image](https://user-images.githubusercontent.com/23075641/153826345-cd92f83f-7de8-451f-9ddb-244a5969e48e.png)

**Comment by tigrenok00** [comment]
@yigitfindikli 

See stackblitz with route reuse: go to page B, scroll the table, go to page A, return to page B - table did not keep the state of scroll and data (shown blank). If you do this without scrolling the table, the data is kept upon returning.

Stackblitz:
https://stackblitz.com/edit/primeng-tablevirtualscroll-demo-dxvheu?file=src/app/app.module.ts
