### ISSUE TITLE
p-calendar overlay covers input field

### ISSUE THREAD

**Issue by VILLAN3LL3** [primefaces/primeng#11177]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
[Editor URL](https://stackblitz.com/edit/github-x5mwmn?file=src/app/my-dialog/my-dialog.component.html)
[Application URL](https://github-x5mwmn.stackblitz.io)

**Current behavior**
![grafik](https://user-images.githubusercontent.com/39371377/153718827-95d5d9ff-5d89-40ed-a766-9eb359d578dc.png)
Calendar overlay covers input field

**Expected behavior**
Calendar overlay opens on the bottom of the input field

**Minimal reproduction of the problem with instructions**
See stackblitz

**What is the motivation / use case for changing the behavior?**
It is not possible to change the date/time via input field

**Please tell us about your environment:**
n/a

* **Angular version:**
13.0.x

* **PrimeNG version:** 5.X
13.0.x

* **Browser:** 
Reproduced in Firefox and Edge (current version)

**Comment by yigitfindikli** [comment]
This is caused by the limited screen size. Your options are to change your theme(Etc: nano) or override the calendar's padding. Like: https://stackblitz.com/edit/github-x5mwmn-yzpbpr?file=src%2Fstyles.scss
