### ISSUE TITLE
Carousel [page] attribute doesn't work with [responsiveOptions]

### ISSUE THREAD

**Issue by adudzisz** [primefaces/primeng#11171]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/github-aqfhbb

**Current behavior**
On mobile it's impossible to display element with index 1 in carousel with 3 elements. (on start, without scrolling)

**Expected behavior**
On mobile it's possible to display element with index 1 in carousel with 3 elements. (on start, without scrolling)

**Minimal reproduction of the problem with instructions**
Minimal example:
https://stackblitz.com/edit/github-aqfhbb

What I want to achieve:
on desktop I want to display 3 elements (it works),
on mobile I want to have 1 displayed element but on start I'd like to see element with index 1 (2nd image).

Currently, when I resize window I can see element with index 0 (should be 1, but it's not big problem for me, it's rare case), but when I refresh window (with 'mobile' width), element with index 2 is presented (after refresh it should be index 1, as it's defined in [page] attribute in documentation).

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 12.1.2
Also tested on 13.0.3

* **PrimeNG version:** 12.1.0
Also tested on 13.0.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 97
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cetincakiroglu** [comment]
Hi, 

This is not a bug, here is the working example of your code.

https://stackblitz.com/edit/github-aqfhbb-ry9wrc?file=src%2Fapp%2Fapp.component.ts

Regards.

**Comment by adudzisz** [comment]
Hi,
Thank you for your response.

It's still doesn't work. Maybe I'm doing something wrong, but when I resize window size down to 560px and refresh screen I can still see first element (not second). After add '[page]="1"' third element is displayed.
It works when there are more elements displayed on screen (768px breakpoint), but I'm only interested in the case with one displayed element.

Regards

**Comment by cetincakiroglu** [comment]
> Hi, Thank you for your response.
> 
> It's still doesn't work. Maybe I'm doing something wrong, but when I resize window size down to 560px and refresh screen I can still see first element (not second). After add '[page]="1"' third element is displayed. It works when there are more elements displayed on screen (768px breakpoint), but I'm only interested in the case with one displayed element.
> 
> Regards

Hi,

Since you've defined numScroll and numVisible inside the responsiveOptions input prop, you don't need to use numScroll and numVisible input props of the p-carousel component. It causes the bug since the component receives 2 different values at the same time from different input props and it uses these values to calculate the number of items that should be displayed. I updated the example, here you can check and compare buggy and working versions.

https://stackblitz.com/edit/github-aqfhbb-ry9wrc?file=src%2Fapp%2Fapp.component.html

Regards

**Comment by adudzisz** [comment]
Ok, now I can see my mistake :-). I thought numScroll and numVisible defined in html are default values (for larger screens) and if I add responsiveOptions I'll just override settings for some resolutions. Indeed if I define 2 breakpoints (5000px with numScroll/numVisible = 3 and 640px with numScroll/numVisible = 1) it works as I would like.

It turns out the documentation is confusing - in the example given [here](https://www.primefaces.org/primeng/showcase/#/carousel) all 3 options are used in html, which as you say will not always work properly.

Or it's just some place for improvement in future versions :-).

Anyway, thanks for explanation and working solution. :-)

Regards
