### ISSUE TITLE
css resource files not imported by webpack

### ISSUE THREAD

**Issue by buchatsky** [primefaces/primeng#11172]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request 
[ ] support request 
```

**Github repo (Bug Reports)**
[Minimal repo](https://github.com/buchatsky/primeng-wp-test1)

**Current behavior**
Cannot import primeng/resources CSS files using webpack directly (without angular CLI).
1. When .css files from primeng/resources are imported in main.ts 
`import "/node_modules/primeng/resources/primeng.css";`
they are thrown out by webpack because  sideEffects is set to "false" in primeng/package.json.
2. When they are imported as a part of primeng package like
`import "primeng/resources/primeng.css"`
then webpack complains "Package path ./resources/primeng.css is not exported from package node_modules\primeng".

Note1: importing styles in app styles.css like `@import "~primeng/resources/primeng.css";` complies to the same rules (exports are respected).
Note2: it is still possible to import css in styles.css as files like `@import "/node_modules/primeng/resources/primeng.css";` but this hole may be patched in future
Note3: same behaviour with both JIT and AOT angular webpack config.

**Expected behavior**
1. .css files from primeng/resources not being thrown out y webpack when referenced as files: 
`import "/node_modules/primeng/resources/primeng.css";`
Webpack team [recommends](https://github.com/webpack/webpack/issues/8814#issuecomment-465223178) to set `"sideEffects": ["*.css"]` in library's package.json
2. primeng/resources be exported from package.json to be referenced as a part of primeng package:
`import "primeng/resources/primeng.css"`
Webpack team [recommends](https://webpack.js.org/guides/package-exports/) exporting them in  library's package.json, e.g. as a directory:  `"./resources/": "./resources/",`

**Minimal reproduction of the problem with instructions**
1. Clone [test repo](https://github.com/buchatsky/primeng-wp-test1)
2. npm install
3. npm run serve
(Starting from VSCode is also possible)

**What is the motivation / use case for changing the behavior?**
I need to use webpack directly because the application is a combination of ASP.Net MVC and SPAs. The recommended way to import css which are global to SPA is to import them in main.ts:
`import "primeng/resources/primeng.css";`
or 
`import "/node_modules/primeng/resources/primeng.css";`
as [webpack docs](https://webpack.js.org/guides/asset-management/#loading-css) states.

**Please tell us about your environment:**
Windows 10, Visual Studio 2022 / VSCode, NPM, webpack dev server

* **Angular version:** 13.2.2

* **PrimeNG version:** 13.1.1

* **Webpack version:** 5.68.0

* **Browser:** [all]
 
* **Language:** [TypeScript 4.5.5]

**Comment by cTSC** [comment]
@buchatsky can you give me a hint on what you mean by 'without Angular CLI' is there actually a way to import these css files? I've recently upgraded to PrimeNG 13 and then got the same problem as you did.

**Comment by buchatsky** [comment]
@cTSC AFAIK it is possible to import them via "styles" section in angular.json when Angular Cli is used

**Comment by jberndsen** [comment]
I have this same problem. I use a custom webpack config and npm command (so, nothing to do with Angular CLI) to build our styles. These styles try to import ~primeng/resources/primeng.min.css. The file does exist, but isn't exported in the primeng package.json, resulting in the error `Package path ./resources/primeng.min.css is not exported from package C:\DEV\fabric\node_modules\primeng`. If I remove the exports array of the node_modules/primeng/package.json for testing purposes, the compilation works correctly.

**Comment by jberndsen** [comment]
In addition to my above comment, I believe this issue started breaking our builds when we upgraded to Node 16.

**Comment by L2jLiga** [comment]
Hi there,
using Angular 14 with `browser-esbuild` builder leads me to the same error unless I manually change `package.json` of this package to export styles
Repo to reproduce: https://github.com/L2jLiga/angular-esbuild-primeng-issue
