### ISSUE TITLE
p-table: Paginator + Lazy Loading + Table State = No pagination links are visible.

### ISSUE THREAD

**Issue by StefanCardnell** [primefaces/primeng#11188]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/primeng-tablelazy-demo-htoenx?file=src/app/app.component.ts

See above for example

Set the `stateKey` to `undefined` to fix the issue

**Current behavior**
Table Pages buttons (e.g. 1, 2, 3) should display in the paginator.

**Expected behavior**
They do not display, only the left and right pagination icons appear.

**Minimal reproduction of the problem with instructions**

1) Create a lazy loaded table using a paginator
2) Make that table use local storage with `stateKey` and `stateStorage` specified.
3) Ensure the state location has some initial data (in the case of stackblitz this is done in `ngOnInit`
4) Open the table and notice no pagination links are visible (see stackblitz)

**What is the motivation / use case for changing the behavior?**

Can't use state storage on a lazy loaded table with pagination. So if I want to save my table widths, nope!

* **Angular version:** 13.0.3

* **PrimeNG version:** 13.0.4

* **Browser:** [Chrome latest]

* **FIX FOUND:** 

I can see the issue occurs here in `restoreStore` on `p-table`:

https://github.com/primefaces/primeng/blob/6b0917969b848c015ef9aaedc7e2d9415ee8539a/src/app/components/table/table.ts#L2199

I believe it should be `state.first !== undefined` instead of `this.first !== undefined`. Since `this.first` is `0` it is not undefined, but then it gets set to `state.first`, which is undefined. Once `this.first` is undefined, the paginator stops working.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
