### ISSUE TITLE
Table - Column Resize - Expand - Changes/disturbs width of other columns on resize of single column

### ISSUE THREAD

**Issue by HassanNiazi** [primefaces/primeng#11186]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-tvzyhc-roy84w?file=src/app/app.component.ts

**Current behavior**
One column resize in expand mode for table the width of all the columns is effected i.e. increases widths of all columns in the grid. This issue is not present in earlier version but present in 13.x. This can also be visualised in PrimeNg showcase example [here](https://www.primefaces.org/primeng/showcase/#/table/colresize). Also please check the attached stackblitz example for reproducing it. 

**Expected behavior**
Should not update the width of other columns which are not resized on resizing one column. Can be visualised in the earlier versions on PrimeNg showcase [here](https://www.primefaces.org/primeng/v12-lts/#/table/colresize).

**Minimal reproduction of the problem with instructions**
Open the above provided example resize all column to reduce the column widths.
Now resize one column to increase the column width. This will effect width of all columns which should not happen. 
Now to see the expected behaviour perform same action on the sample provided in Expected behavior section.

**What is the motivation / use case for changing the behavior?**
This is effecting our application user experience.

**Please tell us about your environment:**
MacOS/Windows, VS Code, Google Chrome.

* **Angular version:** 13.1.2
Yes

* **PrimeNG version:** 13.1.1
Yes

* **Browser:** [Chrome 98.0.4758.80]

 Chrome - 98.0.4758.80
* **Language:** [TypeScript 4.5.4]

**Comment by HassanNiazi** [comment]
@vincent Did the team got any opportunity to check this one? Its a blocker for us so it will be great if someone can check this out.

**Comment by OmarEnriqueCocaBuitrago** [comment]
I implemented the  "responsiveLayout="scroll"" property, then the error is gone, but i am having another problem is not taking the width that I am giving from the beginning. this also happens in PrimeNG 12.

**Comment by OmarEnriqueCocaBuitrago** [comment]
In my case is not taking the width size that I am giving for each column from the beginning.  In the elements inspector shows the correct value but in the GUI does not. 

 
![image](https://user-images.githubusercontent.com/20451736/157040119-6633b5fd-ce7e-42cc-97ec-b93679a96581.png)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
