### ISSUE TITLE
Set of feature requests

### ISSUE THREAD

**Issue by mohammadreza99** [primefaces/primeng#11194]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
I want to make some suggestions to improve these great components and I hope they are effective in improving the components:

- In `autoComplete` component we have two @inputs named `minLength` and `maxlength`. one is camelCase and another is lowercase.

- In `password` component we have no onInput , onChange, onKeydown and other input events as @Output and also have no disabled @Input property.

- Please add inputGroup support for input-like components (such as `cascadeSelect`, `dropdown`, `autoComplete`, ...). Text, icon, buttons and other content can be grouped next to an input.

- And pleas add size support for `cascadeSelect` component.

- Ability to accept size in `button` component when it has icon only.

thanks for your attention

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
