### ISSUE TITLE
Using p-calendar's defaultDate makes the calendar dialog read-only

### ISSUE THREAD

**Issue by yuri1969** [primefaces/primeng#11199]
**I'm submitting a ...** 
```
[x] bug report
[ ] feature request
[ ] support request
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/github-4w68i8?file=src/app/app.component.html

**Current behavior**
Setting `defaultDate` correctly pre-sets the calendar component to the given date but the component becomes read-only. It is not possible to select a different month, day, etc.

This doesn't seem to be intended.

**Expected behavior**
Pre-set the calendar component to the given date but allow further manipulation.

**Minimal reproduction of the problem with instructions**

1. Use `p-calendar`
2. Set `defaultDate`
3. Open the calendar
3. Try to change the pre-selected day

https://stackblitz.com/edit/github-4w68i8?file=src/app/app.component.html

* **Angular version:** 13.0.3

* **PrimeNG version:** 13.0.4

* **Browser:** [Chrome| Firefox]
 
* **Language:** [TypeScript 4.0.2] 

* **Node (for AoT issues):** `node --version` =   16.13.2

**Comment by cetincakiroglu** [comment]
Hi,

Here is a refactored and working version of your example. You don't need to use defaultDate prop to give the calendar a default value.
https://stackblitz.com/edit/github-4w68i8-wczu65?file=src%2Fapp%2Fapp.component.ts

Regards
