### ISSUE TITLE
p-panel renders wrong toggle option

### ISSUE THREAD

**Issue by jadrp** [primefaces/primeng#11205]
Hello,

Before update to 13.2.0, toggle option renders to the right side of the p-panel. After update to 13.2.0, the toggle option renders to the left side of the p-panel. Occurs the same behavior using the p-panel icons template.

Thanks.

**Comment by cetincakiroglu** [comment]
Hi,

You can use iconPos input property and align the icon as you wish. that we've implemented in v13.2.0

Correct values for iconPos are "left", "right", "center".  Default value is "right".

Regards
