### ISSUE TITLE
Enhancement for Table

### ISSUE THREAD

**Issue by jiangyh1024** [primefaces/primeng#11203]
```
 <p-table #table [loading]="isLoading" [value]="value" [styleClass]="styleClasses" [paginator]="paginator"
    [rows]="rows" [showCurrentPageReport]="showCurrentPageReport" [showJumpToPageDropdown]="showJumpToPageDropdown"
    [showJumpToPageInput]="showJumpToPageInput" [currentPageReportTemplate]="currentPageReportTemplate"
    [rowsPerPageOptions]="rowsPerPageOptions" [scrollHeight]="scrollHeight" [lazy]="lazy"
    (onLazyLoad)="onLazyLoad($event)" [lazyLoadOnInit]="lazyLoadOnInit" [scrollDirection]="scrollDirection"
    [scrollable]="scrollable" [columns]="columns" [totalRecords]="totalRecords" [dataKey]="dataKey"
    [responsiveLayout]="responsiveLayout" [(selection)]="selection" [selectionMode]="selectionMode"
    (onRowSelect)="onRowSelected($event)" [globalFilterFields]="globalFilterFields"
    [selectionPageOnly]="selectionPageOnly" [filterDelay]="filterDelay" (onRowUnselect)="onRowUnselected($event)">

....
</p-table>
```

this is what I have done right now. I am wondering if you could wrap all the options into a property call 'gridOptions'. 

so, we can use it like 

`<p-table #pt  [gridOptions]="gridOptions"></p-table>`

and provide functions to set datasource like
`
this.pt.setDatasource(someData, total)`

and in ts file

```
this.gridOptions = {
   columns: [],
   ...
}

```

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
