### ISSUE TITLE
Tabview - Cannot read properties of null (reading 'offsetWidth')

### ISSUE THREAD

**Issue by easyping** [primefaces/primeng#11202]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

URL for example
https://stackblitz.com/edit/github-s9uwhf?file=src/app/app.component.html

**Current behavior**

When the tabpanel list is loaded dynamically (in example dynTab) the error message appears in browser console
"Cannot read properties of null (reading 'offsetWidth')"

That is why the tabview is not displayed.

The error did not occur in PrimeNG 11 

* **Angular version:** 13.X

* **PrimeNG version:** 13.X

* **Browser:** test on Chrome 96 | Firefox 91

**Comment by cetincakiroglu** [comment]
Hi,

This is a life cycle problem.
Here is the working and refactored version of your example. 
https://stackblitz.com/edit/github-s9uwhf-yy9nq2?file=src%2Fapp%2Fapp.component.ts

Regards
