### ISSUE TITLE
Dynamic Dialog is not modal

### ISSUE THREAD

**Issue by AlbaSS18** [primefaces/primeng#11204]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-tablescroll-demo-7x8zqx?file=package.json

**Current behavior**
User can continue clicking in the background and open new dynamic dialogs.

**Expected behavior**
It shouldn't allow to make click in the background.

**Minimal reproduction of the problem with instructions**

1. Click on the button Show and the dialog opens.
2. Click on the button Show and other dialog opens when it shouldn't.

**Please tell us about your environment:**

* **Angular version:** 12.0.5

* **PrimeNG version:** It doesn't work in 12.2.3 and 12.2.2 but in previous version, it works. I don't know if it works in version 13 but in this moment, I can't update the version.

* **Browser:** Firefox

**Comment by cetincakiroglu** [comment]
Hi,

This issue was fixed in v13+
Here you can check https://www.primefaces.org/primeng/showcase/#/dynamicdialog

Regards
