### ISSUE TITLE
primeng 5.2  to primeng 11  how to migrate  and  from prime ng remove  p-datatble ..    is therey easy way to upgrade , any idia  

### ISSUE THREAD

**Issue by rsurendraidexcel** [primefaces/primeng#11200]
primeng 5.2  to primeng 11  how to migrate  and  from prime ng remove  p-datatble ..    is therey easy way to upgrade , 
can you help documentaion upgrading component

**Comment by cetincakiroglu** [comment]
Hi,

To upgrade PrimeNG and PrimeFlex versions

1- Change the versions from package.json with latest PrimeNG and PrimeFlex versions.
2- Remove node modules and install all packages again by `"rm -rf node_modules && npm install"`

Regards
