### ISSUE TITLE
DynamicDialog |  focusOnShow Support

### ISSUE THREAD

**Issue by zlodiak** [primefaces/primeng#11219]
**Plunkr Case (Bug Reports)**
https://www.primefaces.org/primeng/showcase/#/dynamicdialog

**Current behavior**
1. user click to blue 'show'-button
2. the dialog window opens
3. user press 'enter'-key on keyboard (or 'space'-key)
4. new dialog window opens again

**Expected behavior**
1. user click to blue 'show'-button
2. the dialog window opens
3. user press 'enter'-key on keyboard (or 'space'-key)
4. nothing happens

* **PrimeNG version:** 13.2.0

* **Browser:** 
chrome 98.0.4758.102

**Comment by zlodiak** [comment]
@yigitfindikli thanks, but in that commit you only fixed the pressing 'enter'-key, but not 'space'-key

**Comment by yigitfindikli** [comment]
Hi @zlodiak,

PR is created by @cetincakiroglu. I'm gonna edit your ticket to showOnFocus support for DynamicDialog.

**Comment by ikasparov** [comment]
Hi :) I have the same problem. The solution could be to set focus to some internal dialog component after opening. As an option, focus could be set to **nativeElement** while initializing of **p-dynamicdialog** in own OnInit hook

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by zlodiak** [comment]
Hi!

@mertsincan I have checked the latest version primeNg (i mean 14.2.1). After that i see that problem is not solved. That is case from start topic of this issue is leads to bug/error. 

Unfortunately, i dont have permissions for reopen this issue. Please do it because the bug still exists.

Thanks.

**Comment by jonnomk** [comment]
Hello @mertsincan and Prime team.

Can you please add 'focusOnShow' to the API for DynamicDialog and provide the ability to set it to false.  

The reason for this is that the way you apply focus overrides our ability to add focus to an element using the native autofocus attribute.

It's great that you add focus to the first element, but not great that we can't disable this functionality should we want to apply focus to our own input element contained in the dialog.

Many thanks.

**Comment by VolodymyrKornetskyi** [comment]
The same for me. Can you add focusOnShow to config?

**Comment by delvinwidjaja** [comment]
any update on this ticket? "focusOnShow" has been added in the DynamicDialog but it seems I can't use it in the config

**Comment by mass4441** [comment]
Any update on this thread ?

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
