### ISSUE TITLE
ng-template in p-tree doesn't work when filter applied

### ISSUE THREAD

**Issue by psarno** [primefaces/primeng#11216]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/primeng-treetemplating-demo-rtgjwm?file=src/app/app.component.ts

**Current behavior**

Click on any node in the tree and note the "Next" button, which is on a node via an ng-template.

Refresh and filter the tree first, then try to select a node again.  The template is not applied.

**Expected behavior**

The template should be applied whether or not the tree is filtered.

**Minimal reproduction of the problem with instructions**
- Expand a parent node
- Click on child node
- Note the "Next" button
- Refresh
- Apply a filter
- Do steps above, no "Next" button

**What is the motivation / use case for changing the behavior?**
Current behavior is incorrect.

**Please tell us about your environment:**

Windows 11

* **Angular version:** 5.X
13.1.1

* **PrimeNG version:** 5.X
13.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome Version 98.0.4758.102 (Official Build) (64-bit)
Firefox 97.0 (64-bit)
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

TypeScript 4.5.4
    "target": "es2020",
    "module": "es2022",

* **Node (for AoT issues):** `node --version` =   

n/a

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
