### ISSUE TITLE
p-splitter stops working when it contains an input with the pInputTextDirective

### ISSUE THREAD

**Issue by spectacularbob** [primefaces/primeng#11211]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-nr3len?file=src/app/app.component.html

**Current behavior**
The Splitter component stops working when it contains an input with a pInputText directive. It seems to prevent the p-splitter from adding the p-splitter-panel class to a div, causing the splitter module to think there's only 1 panel

**Expected behavior**
pInputText should not affect the p-splitter's behavior

**Minimal reproduction of the problem with instructions**
In a new angular project with primeng, import the SplitterModule and the InputTextModule. Paste this code in the app.component.html file:
```
<p-splitter>
    <ng-template pTemplate>
        Panel 1
        <input type="text" pInputText />
    </ng-template>
    <ng-template pTemplate>
        Panel 2
    </ng-template>
</p-splitter>
```

**What is the motivation / use case for changing the behavior?**
It breaks the functionality

**Please tell us about your environment:**
Windows, vscode,

* **Angular version:** 5.X
13.2.0

* **PrimeNG version:** 5.X
13.2.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 98.0.4758.102, Edge 98.0.1108.50, Firefox 97.0
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 4.5.2
Node 14.17.3

**Comment by cetincakiroglu** [comment]
Hi,

Here is the refactored and working version of your example. You can use "p-inputtext" css class instead of pInputText directive.
https://stackblitz.com/edit/github-nr3len-3njcmg?file=src/app/app.component.html

Regards
