### ISSUE TITLE
Table resizing broken for expandable tables

### ISSUE THREAD

**Issue by sbs101** [primefaces/primeng#11218]
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-tablerowexpansion-demo-nwbyqd?file=src/app/app.component.html

**Current behavior**
When an outer table with expandable rows has another (inner) table in the expansion section, resizing of the columns of the outer table also affects the column sizes of the inner table starting with orimeng 13.1.0. For 13.0.4 it still works.

**Expected behavior**
The columns of the outer table can be resized without an effect to the inner table. 

**Minimal reproduction of the problem with instructions**
- use the above stackblitz
- ensure the browser window is wide enough to see the normal (not stacked) version of the table
- expand one of the table entries to see an inner table
- resize one of the columns of the outer table
- the columns of the inner table get resized, too

**What is the motivation / use case for changing the behavior?**
Column width of the inner table should not change when resizing the outer table columns

**Please tell us about your environment:**
Windows 10

* **Angular version:** 5.X
angular 13.2.3

* **PrimeNG version:** 5.X
primeng 13.2, for 13.0.4 it is still working

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Firefox
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 4.0.2

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by sbs101** [comment]
Seems to be working in PrimeNg 14.2.0
