### ISSUE TITLE
P-table doesn't update when object passed into columns is updated

### ISSUE THREAD

**Issue by abadirf** [primefaces/primeng#11217]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**

updating columns attribute on p-table does not result in the table updating as a work around I'm using ngIf to destroy and recreate the table

**Expected behavior**

I would expect the table to update to match the column object

**Minimal reproduction of the problem with instructions**

p-table created with [columns]= "cols"
change value of cols, the table does not update

**What is the motivation / use case for changing the behavior?**

the main goal here is to have other components be able to manipulate column order.

**Please tell us about your environment:**

mac os 11.5, vscode, npm, local dev

* **Angular version:** 5.X

* **PrimeNG version:** 5.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

chrome 98
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cetincakiroglu** [comment]
Hi,

The issue is not clear, please provide a Stackblitz example and re-open the issue by using https://stackblitz.com/github/primefaces/primeng-issue-template

Regards
