### ISSUE TITLE
TreeSelect selection expands sibling nodes above the selection

### ISSUE THREAD

**Issue by dcbroad3** [primefaces/primeng#11224]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When a node is selected in the TreeSelect component, and the node is not at the root of the list of components, the component will expand any siblings of the node above it. This is because while iterating through children, it appends each sibling to the `path` as it iterates through instead of creating a new array with only the current iterating item added to the path.

**Expected behavior**
Only the selected node and its parents should be expanded.

**Comment by dcbroad3** [comment]
Any way I could get a review of this and the attached pull request? This still appears to be a bug in the latest version. We are working around this bug by using a wrapper component that overrides the method in question. The fix is just a one-line code change.

**Comment by cetincakiroglu** [comment]
> Any way I could get a review of this and the attached pull request? This still appears to be a bug in the latest version. We are working around this bug by using a wrapper component that overrides the method in question. The fix is just a one-line code change.

Hi,

There is no pull request linked with this issue, could you please link your pull request so I can review it?

Thanks
