### ISSUE TITLE
Suggestion: please add a way to print section with styles

### ISSUE THREAD

**Issue by ahmedabdelhafez** [primefaces/primeng#11222]
hello great prime ng team,
i am front end developer and using prime ng for more than 3 years and i want to suggest to add package or component to print sections or div and export to pdf for download or to print it

thanks

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
