### ISSUE TITLE
p-table in edit mode, can I stay in edit mode if there is an error in validation?

### ISSUE THREAD

**Issue by vicky-rain** [primefaces/primeng#11221]
![image](https://user-images.githubusercontent.com/16696067/154885444-8c35db9f-ed33-4d89-8a4b-17c20beec954.png)

in edit mode, can I stay in edit mode if there is an error in validation?
The current situation is to exit the edit mode

![image](https://user-images.githubusercontent.com/16696067/154885503-887b05a6-0a0f-4dd6-96ff-e1fc8b8f512d.png)

**Comment by cetincakiroglu** [comment]
Hi,

The issue is invalid please provide a Stackblitz example and reopen the issue.

Regards

**Comment by vicky-rain** [comment]
Hi,

https://stackblitz.com/edit/primeng-tableedit-demo

**Please see the red place in the picture below, when I click the edit button to edit the quantity above**

![image](https://user-images.githubusercontent.com/16696067/156489069-edd33198-e800-4316-a06b-1bfc774f0562.png)

**If the wrong information is entered, the current situation is that there is a problem with the entered information and the edit mode is exited.
The way I want to achieve this is: if you enter the wrong information, click the save button, prompting that there is a problem with the input information, but do not exit the editing mode.**

![image](https://user-images.githubusercontent.com/16696067/156490027-51e5bc48-a56a-4ebc-9dfe-099d46da7eef.png)

![image](https://user-images.githubusercontent.com/16696067/156490084-c2e52766-1d4a-428c-bb7d-3b5362a38287.png)
