### ISSUE TITLE
Calendar input field doesn't update when ngModel is changed programmatically - beta 19

### ISSUE THREAD

**Issue by raaaste** [primefaces/primeng#1122]
`<p-calendar [(ngModel)]="startDate" [showTime]="true" [locale]="fi" (onSelect)="startDatetimeSelected()" [maxDate]="maxDate" dateFormat="dd.mm.yy"></p-calendar>`

`<p-calendar [(ngModel)]="endDate" [showTime]="true" [locale]="fi" [maxDate]="maxDate" dateFormat="dd.mm.yy"></p-calendar>
`

`startDatetimeSelected() {
this.endDate = moment(this.startDate).add(10, 'minutes').toDate();
console.log(this.endDate);
}`

The value for this.endDate logs to console fine when the onSelect is fired, but the p-calendar element's input field doesn't reflect the change.

**Comment by arimus** [comment]
Yeah, this is problematic for re-use of widgets / resetting of forms. It seems to hold onto the initial object values. Looks like it sets the state of several internal fields based on the changes through itself, but when made externally that doesn't trigger it to update those? Best guess at the moment.

I was hoping that I could at least programmatically tell the component to reassess it's backing ngModel, but I haven't found a way yet.

**Comment by cagataycivici** [comment]
Fixed at 1140

**Comment by pauloegk** [comment]
Hello, I had the same problem, I managed to solve it this way.

import { Calendar } from 'primeng/primeng';
@ViewChild(Calendar) calendar: Calendar;

this.calendar.updateInputfield();
