### ISSUE TITLE
Table UI breaks with different columns widths

### ISSUE THREAD

**Issue by sayh** [primefaces/primeng#11232]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/primeng-tablevirtualscroll-demo-zkqyvz?file=src/app/app.component.ts

**Current behavior**
Table columns are not aligned (head + body) anymore when defining different column widths. It seems to be fine when using the same width (or min-width) for each column. 

We have a big data table and using different widths for each column, worked fine with primeng v11. After upgrading to a newer version the UI breaks. 

Might be related: https://github.com/primefaces/primeng/issues/10776

**Expected behavior**
Different widths for columns shouldn't break the UI.

**Minimal reproduction of the problem with instructions**

- Table with scroll enabled:  `[scrollable]="true"  scrollHeight="flex" [virtualScroll]="true"`
- Table head with `pTemplate="headergrouped"`
- Set different width (min-width) for columns
- Resize view that horizontal scroll is enabled

**What is the motivation / use case for changing the behavior?**
Blocks upgrade to a newer primeng version :(

**Please tell us about your environment:**

* **Angular version:** 13.2.0

* **PrimeNG version:** 13.1.0

* **Browser:** [Chrome Version 98.0.4758.102 |  Microsoft Edge Version 98.0.1108.56 ]

* **Language:** [TypeScript 4.5.5]

* **Node (for AoT issues):** `node --version` =   v14.16.0

**Comment by cetincakiroglu** [comment]
Hi,

Here is the working version of your example so you can inspect it.

https://stackblitz.com/edit/primeng-tablevirtualscroll-demo-qfvfaz?file=src%2Fapp%2Fapp.component.html

Regards.
