### ISSUE TITLE
Dynamic Dialog Ref crashes the App on close

### ISSUE THREAD

**Issue by mirzace** [primefaces/primeng#11230]
**I'm submitting a ...** 
```
[x] bug report
[ ] feature request
[ ] support request
```

**Plunkr Case (Bug Reports)**

Demo: https://github-xqz8yh.stackblitz.io

**Current behavior**

If you want to show a dialog until some action is done, the app will crash on dialog close.

**Expected behavior**

It should open a dialog for x amount of time and then close it without crashing the application.

**Minimal reproduction of the problem with instructions**

- Open the demo above.
- Click on the "Save Image" button.
- Open the console and red an error

**Please tell us about your environment:**

* **OS:** Windows 10

* **IDE:** Visual Studio Code

* **Package manager:** npm

* **Angular version:** 13.X

* **PrimeNG version:** 13.X

* **Browser:** [all]

 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =   14.17.5

**Comment by cetincakiroglu** [comment]
Hi,

I can't access the code of the example, could you please provide an editable Stackblitz link?

Regards

**Comment by mirzace** [comment]
Hi, can you check this one: https://stackblitz.com/edit/github-xqz8yh?file=src/app/app.component.ts

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by mirzace** [comment]
Hi @mertsincan , 

I have checked and apparently, the issue still persists.
I have created a PR for this one https://github.com/primefaces/primeng/pull/12218

**Comment by davodbeheshti** [comment]
Hello, I also encountered the same problem in Angular version 12

When **this.ref.close()** command was executed in the dialog, the page was refresh automatically

And my problem was solved in such a way that inside the buttons that executed this command

I gave them the **type "button"** and my problem was solved
