### ISSUE TITLE
Bug report: users are allowed to focus a speed dial action while the action panel is hidden

### ISSUE THREAD

**Issue by activedecay** [primefaces/primeng#11238]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/primeng-speeddial-demo-uhi5wr?file=src/app/app.component.html

**Current behavior**

Activating the speed dial with the keyboard, and pressing tab, focuses the first entry in the speed dial (correct)

The focus of the speed dial action is, however, *not* all that visible to the user (the demo has a black-on-black and it's really hard to see on my monitor -- this is beside the issue in this bug but just wanted to mention this)

Also, after activating the speed dial action with enter, the speed dial closes (correct); however, repeatedly pressing enter continues to activate the speed dial action item. It seems that tab index is not set to -1 when these speed dial actions are hidden (I believe they should not be tabbed to when hidden.) While tabbing, the user can change which speed dial action is activated, even while the list is hidden. Pressing enter while the list is hidden confirms this.

**Expected behavior**

Focus should be visible.
Tabbing should sometimes focus the speed dial actions (when open), and sometimes skip over the actions (when closed).

**Minimal reproduction of the problem with instructions**
Use the tab key and enter key only when operating the speed dial. You will run into usability issues described above.

**What is the motivation / use case for changing the behavior?**

Usability. User experience.

**Please tell us about your environment:**

N/A

* **Angular version:** 5.X

N/A

* **PrimeNG version:** 5.X

13.0.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

FF
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS

* **Node (for AoT issues):** `node --version` =   
N/A

**edits**
1. change the "not visible focus" issue to "not all that visible" because black on black is no good
2. attempting to clarify that it's allowing the user to change the focus to hidden speed dial action elements

**Comment by activedecay** [comment]
https://imgur.com/YAAOvRJ

**Comment by activedecay** [comment]
here's a workaround https://stackblitz.com/edit/primeng-speeddial-demo-uhi5wr?file=src%2Fapp%2Fapp.component.html

**Comment by APet74** [comment]
Working fix in #11239

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
