### ISSUE TITLE
Mouse Event binding cause performance issue

### ISSUE THREAD

**Issue by marshroomiv** [primefaces/primeng#1123]
I found Mouse Event binding (mouseenter)="hover = true" (mouseleave)="hover=false" cause the the Component status changes, it will trigger AppView.detectChanges to check changes endless.

testing code as following, once mouse move over the accordion tab, get name() function will be called

import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'test',
  providers: [],
  template: `

```
<input type="text" [(ngModel)] = "name" >

<p-accordion [multiple]="true">
    <p-accordionTab header="Test1">
        Test1
    </p-accordionTab>
    <p-accordionTab header="Test2">
        Test1
    </p-accordionTab>
</p-accordion>
```

  `
})
export class Test {

```
private _name: string = "Joe";

set name(name: string){
    this._name=name;
}

get name():string{
    return this._name;//set break point here, 
}
```

}

**Comment by marshroomiv** [comment]
Suggest to move the mouseover & mouseleave event to CSS

**Comment by cagataycivici** [comment]
PrimeNG 2+ uses CSS for these cases.
