### ISSUE TITLE
Input number bug - suffix '%'

### ISSUE THREAD

**Issue by jiangyh1024** [primefaces/primeng#11234]
<img width="148" alt="image" src="https://user-images.githubusercontent.com/34930870/155654423-51b5bab6-9032-466a-83fc-01139a6a2198.png">

after I enter '.' , it became like

<img width="191" alt="image" src="https://user-images.githubusercontent.com/34930870/155654451-ff7a7021-f77b-4321-a66c-7a9fab2a12d3.png">

**Comment by MohammadRayanShah** [comment]
I would like to work on this issue

**Comment by jiangyh1024** [comment]
OH thx 

> I would like to work on this issue

**Comment by MohammadRayanShah** [comment]
Is there any contribution.md file as I am getting errors while setting up this project on my local

**Comment by jiangyh1024** [comment]
this is a workaround I just did

<img width="754" alt="image" src="https://user-images.githubusercontent.com/34930870/156513406-3395b176-76db-4a5f-b655-f59d63ab2367.png">

**Comment by jiangyh1024** [comment]
I have no idea about your error, sorry, maybe you can turn to the primeng manager for helper

**Comment by MohammadRayanShah** [comment]
How can I get in touch with primeng manager


> I have no idea about your error, sorry, maybe you can turn to the primeng manager for help

**Comment by jiangyh1024** [comment]
> How can I get in touch with primeng manager
> 
> > I have no idea about your error, sorry, maybe you can turn to the primeng manager for help

@cagataycivici

**Comment by yigitfindikli** [comment]
Hi, @MohammadRayanShah  

PR template: https://github.com/primefaces/primeng/blob/master/.github/PULL_REQUEST_TEMPLATE.md. 

Simple we're accepting defect fixes, enhancements, and features are made by our team.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
