### ISSUE TITLE
Can't bind to 'headerRows' since it isn't a known property of 'p-dataTable'.

### ISSUE THREAD

**Issue by moxival** [primefaces/primeng#1124]
This is what i get after updating to beta20:

```
Can't bind to 'headerRows' since it isn't a known property of 'p-dataTable'.
```

Looking at the source code I really don't see any `headerRows` input property, but i still can find in the documentation?

**Comment by cagataycivici** [comment]
Please see;

http://www.primefaces.org/primeng/#/datatablegroup

and

http://blog.primefaces.org/?p=4156
