### ISSUE TITLE
InputNumber fails unit test with 'locale' set by translate pipe or instant() of '@ngx-translate/core' 

### ISSUE THREAD

**Issue by andrei0mihai** [primefaces/primeng#11241]
**I'm submitting a**
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

<p-inputNumber [(ngModel)]="value2" mode="currency" currency="USD" locale="en-US"></p-inputNumber>

**Expected behavior**

<p-inputNumber [(ngModel)]="value2" **[locale]="'translateKey'|translate"** currency="EUR" mode="currency"></p-inputNumber>

where the translateKey is 'en-US'/'de-DE'

**Minimal reproduction of the problem with instructions**

The problem occurs only in jasmine unit test:
```
RangeError: Incorrect locale information provided
            at new NumberFormat (<anonymous>)
            at InputNumber.constructParser (node_modules/primeng/fesm2015/primeng-inputnumber.mjs:72:29)    
            at InputNumber.ngOnInit (node_modules/primeng/fesm2015/primeng-inputnumber.mjs:57:14)
            at callHook (node_modules/@angular/core/fesm2015/core.mjs:2542:1)
            at callHooks (node_modules/@angular/core/fesm2015/core.mjs:2511:1)
            at executeInitAndCheckHooks (node_modules/@angular/core/fesm2015/core.mjs:2462:1)
            at selectIndexInternal (node_modules/@angular/core/fesm2015/core.mjs:8405:1)
            at ɵɵadvance (node_modules/@angular/core/fesm2015/core.mjs:8388:1)
```

I tried using 'translateService.instant('translateKey')' asigning it to a variable bounded to [locale] attribute with no success.
What worked was:
html: `[locale]="locale('translateKey'|translate)|async"`
ts: `locale = (locale: string) => locale === 'de-DE' ? of('de-DE') : of('en-US');`

**Please tell us about your environment:**

Windows 10, VSCode, NPM

* **Angular version:** 13.2.1

* **PrimeNG version:** 13.2

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
