### ISSUE TITLE
p-chips Comma Separator on mobile not working with comma

### ISSUE THREAD

**Issue by iamsajithsasi** [primefaces/primeng#11249]
Comma seperator is not working in mobile. It works good on desktop. Please have an insight on this issue.
`        
<p-chips [(ngModel)]="chipsValue" separator="," [allowDuplicate]="false" styleClass="customChip" placeholder="Enter your tags"></p-chips>
`

**Comment by cetincakiroglu** [comment]
Hi,

I couldn't replicate this issue with the latest PrimeNG and IOS, the component works fine.

Regards

**Comment by iamsajithsasi** [comment]
> Hi,
> 
> I couldn't replicate this issue with the latest PrimeNG and IOS, the component works fine.
> 
> Regards

It's not working with Android mobiles. linked [screenshot](https://ibb.co/zSKNrg1) for your reference.

below is the package.json reference
`
  "dependencies": {
    "@angular/animations": "^13.2.3",
    "@angular/cdk": "^13.2.2",
    "@angular/common": "~13.2.3",
    "@angular/compiler": "~13.2.3",
    "@angular/core": "~13.2.3",
    "@angular/forms": "~13.2.3",
    "@angular/platform-browser": "~13.2.3",
    "@angular/platform-browser-dynamic": "~13.2.3",
    "@angular/router": "~13.2.3",
    "bootstrap": "^4.6.1",
    "bootstrap-icons": "^1.8.1",
    "primeicons": "^5.0.0",
    "primeng": "^13.1.1",
    "rxjs": "~7.4.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  }
`

**Comment by NenadKaevik** [comment]
Hi, I am facing the same issue. The comma separator does not work on mobile. Instead, the chips are added on input blur (focus out). Has this issue been resolved or is still tracked?

**Comment by ErfKS** [comment]
Hi, try this:
https://github.com/ErfKS/taggle.js/blob/master/src/taggle.js
