### ISSUE TITLE
Calendar's 'Relative to today's year' yearRange doesn't work

### ISSUE THREAD

**Issue by hasham-rasheed** [primefaces/primeng#1125]
This simply prints all the numbers provided in range "-nn:+nn" in  a loop and doesn't give years relative to today's year i.e. for a year range "-0:+5" it simply prints the numbers from 0 to 5 and not years. See preview:

![calendar](https://cloud.githubusercontent.com/assets/8542752/19688282/89c62eda-9ae2-11e6-8026-34abc343fe96.png)

**Comment by GuskiS** [comment]
Same here.

**Comment by nont65** [comment]
+1

**Comment by FabioBentoLuiz** [comment]
Same here... working just with absolute values:
`[yearRange]="('1900:2016')"`

**Comment by jasonburrows** [comment]
+1

**Comment by davidkirolos** [comment]
+1

**Comment by KallumTanton** [comment]
+1 Can this be looked into please? I know the documentation only shows the example of absolute but this really isn't suitable for applications that require relative dates.

**Comment by KallumTanton** [comment]
Just to add to my last comment, here's my work around:

Create a string property:

`yearRange: string = (new Date().getFullYear() - 5) + ':' + (new Date().getFullYear() + 30);`

Then use this property as the value for the PrimeNG Calendar `yearRange` property:

`[yearRange]="yearRange"`

It's a bit long-winded for what could be simply `yearRange="c-5:c+30"` but it works.

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.

**Comment by mfish0005** [comment]
Seems to still exist for me?  Maybe I just don't know the syntax.  Here's what I've tried
```
maxBirthdate = new Date();
minBirthdate = new Date();                                                          

<p-calendar #dob="ngModel" name="dob" [yearNavigator]="true" [monthNavigator]="true" yearRange="this.minDate:this.maxDate" [minDate]="this.minBirthdate" [maxDate]="this.maxBirthdate"></p-calendar>                                                                 
```

**Comment by mfish0005** [comment]
This is deja vu...I was having the same problem again and apparently I already commented if the issue persists but I guess it went unnoticed.

**Comment by marob** [comment]
Have you tried wrapping yearRange in brackets?

```
<p-calendar inputStyleClass="input"
                    name="dob"
                    [yearNavigator]="true"
                    [monthNavigator]="true"
                    [yearRange]="yearRange"
                    required
                    placeholder="Select birthdate..."
                    [(ngModel)]="dob"
>
</p-calendar>
```

**Comment by mfish0005** [comment]
Yes that works!  I didn't understand the significance of the brackets before.  Thanks @marob

**Comment by Amit221060** [comment]
> Seems to still exist for me? Maybe I just don't know the syntax. Here's what I've tried
> 
> ```
> <p-calendar #dob="ngModel" name="dob" [yearNavigator]="true" [monthNavigator]="true" yearRange="this.minDate:this.maxDate" [minDate]="this.minBirthdate" [maxDate]="this.maxBirthdate"></p-calendar>                                                                 
> ```

Its Still there i am trying to pass two variables but its not working

**Comment by marob** [comment]
> > Seems to still exist for me? Maybe I just don't know the syntax. Here's what I've tried
> > ```
> > <p-calendar #dob="ngModel" name="dob" [yearNavigator]="true" [monthNavigator]="true" yearRange="this.minDate:this.maxDate" [minDate]="this.minBirthdate" [maxDate]="this.maxBirthdate"></p-calendar>                                                                 
> > ```
> 
> Its Still there i am trying to pass two variables but its not working

You should try this syntax: `[yearRange]="this.minDate + ':' + this.maxDate"`
