### ISSUE TITLE
Primeng table very slow with virtual scroll and expanded rows

### ISSUE THREAD

**Issue by wondie** [primefaces/primeng#11261]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-tablevirtualscroll-demo-s5ee62?file=src/app/app.component.html

**Current behavior**

The table loads super and editing is also slow to start when rowexpansion is added for large data 2000 rows by 64 columns and 10000 rows by 5 columns. It looks like lazy load is not implemented on it. I was thinking of just loading expanded rows only when the button is clicked. I tried to bind with *ngIf and the expand button click but it didn't expand. Even conditionally disabling using *ngIf for tables with no related record didn't work.
**Expected behavior**
 It is expected that, the rowexpansion are not rendered until clicking the expand button. Is there any way of making it lazy load?

**Minimal reproduction of the problem with instructions**

Create a table with large layer, with editing functionality and add row expansion.

**What is the motivation / use case for changing the behavior?**

Performance issues

**Please tell us about your environment:**

Windows 11, PyCharm, Node 16

* **Angular version:** 13.2.0

* **PrimeNG version:** 13.2.0

* **Browser:** All browsers

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by wondie** [comment]
I have a workaround for now expained here in the [stackoverflow](https://stackoverflow.com/a/71695499/3674573) but a bug fix would be great in the future.

**Comment by andredesousa** [comment]
In version 13, virtual scrolling is very slow.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
