### ISSUE TITLE
Doc for versions <11 is gone

### ISSUE THREAD

**Issue by Balastrong** [primefaces/primeng#11268]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Doc for versions <11 is gone

**Expected behavior**
Doc is available at the usual URL

**Minimal reproduction of the problem with instructions**
Since ages I had PrimeNG docs in my bookmarks, for example for V10: https://www.primefaces.org/primeng/v10-lts/#/
Today looks like it's gone.
If I search v11 I see the link is slightly different and doc for previous version is no longer in the dropdown

**What is the motivation / use case for changing the behavior?**
I would like to read the docs

**Comment by victorbarlac** [comment]
Same problem here, my team was relying on the documentations of v5 and v9...

**Comment by victorbarlac** [comment]
They just changed the routes and didn't add the older docs to the dropdown.
I was able to access the documentation for v10 and v9 under those URLs
https://www.primefaces.org/primeng-v10-lts/#/
https://www.primefaces.org/primeng-v9-lts/#/

**Comment by Balastrong** [comment]
Looks like they changed `primeng/v` with `primeng-v` for some versions, thank you!

Anyway, it could be helpful to add them back to the dropdown to make the pages easier to find.

**Comment by victorbarlac** [comment]
Although the v7 documentation lists v6 and v5 in the dropdown, they are still unreachable.

**Comment by yigitfindikli** [comment]
Hello All!

You can access new links from the top bar of the showcase.

https://www.primefaces.org/primeng-v12-lts/#/
https://www.primefaces.org/primeng-v11-lts/#/
https://www.primefaces.org/primeng-v10-lts/#/
https://www.primefaces.org/primeng-v9-lts/#/
https://www.primefaces.org/primeng-v8-lts/#/
https://www.primefaces.org/primeng-v7-lts/#/

**Comment by shubham-matale** [comment]
Above Links are not working they have removed the documentation below version 16

**Comment by erwrow** [comment]
it seems that the legacy documentation is nowhere to be found

**Comment by shubham-matale** [comment]
i think vercel stopped support for nodejs 16 that's why all version supporting it went down

**Comment by hamz4arif** [comment]
I don't found the documentation for version 11 anywhere
