### ISSUE TITLE
Dialog - unwanted line(s)

### ISSUE THREAD

**Issue by jiangyh1024** [primefaces/primeng#11266]
<img width="262" alt="image" src="https://user-images.githubusercontent.com/34930870/156507773-d62a8dff-6912-4000-be92-198325c6d7f8.png">

see image above, under small device, there'll be a line in header, sometimes a line in footer as well  from nowhere.

....

**Comment by jiangyh1024** [comment]
after I changed the background color of mask to red, the line became red....
<img width="730" alt="image" src="https://user-images.githubusercontent.com/34930870/156508724-7d0d63b7-bea8-43e8-b90d-a22c8601f15a.png">

![17EC155D6760B1F4DD6A4BA2449430D9](https://user-images.githubusercontent.com/34930870/156508755-a7481164-34d4-4424-9700-4d955eed3c5e.gif)

**Comment by yigitfindikli** [comment]
Hi,

The issue is not clear. Please provide a Stackblitz example and re-open the issue.

Regards.

**Comment by jiangyh1024** [comment]
Ok Will do

**Comment by jiangyh1024** [comment]
https://primeng-dialog-demo-g97b9l.stackblitz.io

here is the  Stackblitz example,

open it on your iphone or use chrome device tool

![Uploading image.png…]()


you will see the lines

**Comment by jiangyh1024** [comment]
I'm not able to re-open this issue.

**Comment by drake-steadymd** [comment]
I was also having this issue and was able to hide the transparent lines with the following CSS:

```
.p-dialog-footer, .p-dialog-header {
    margin: -1px;
    height: calc(100% + 2px);
    width: calc(100% + 2px);
}

.p-dialog-content {
    margin: 0 -1px 0 -1px;
}
```
The footer and header adjustments hid the lines, but ended up making the center of the modal look 1px too narrow on the sides. Adding the negative margin to `.p-dialog-content` filled that empty space.

**Comment by drakemartin91** [comment]
I was also having this issue and was able to hide the transparent lines with the following CSS:

```
.p-dialog-footer, .p-dialog-header {
    margin: -1px;
    height: calc(100% + 2px);
    width: calc(100% + 2px);
}

.p-dialog-content {
    margin: 0 -1px;
}
```
The footer and header adjustments hid the lines, but ended up making the center of the modal look 1px too narrow on the sides. Adding the negative margin to `.p-dialog-content` filled that empty space.
