### ISSUE TITLE
p-calendar |  maxDate & minDate are broken in month-picker

### ISSUE THREAD

**Issue by kingGstark** [primefaces/primeng#11264]
basically, the p-calendar when using the month-picker, changes the years, and it has the maxDate-minDate boundaries, but it doesn't apply the p-disabled class to the months

StackBlitz with reproducing the issue: [https://stackblitz.com/edit/primeng-tablescroll-demo-wdclen?file=src%2Fapp%2Fapp.component.ts](url)

**Comment by Viktor-36** [comment]
I have same issue after update from 13.0.0-rc.1 to 13.2.0.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
