### ISSUE TITLE
p-table in edit mode, can I stay in edit mode if there is an error in validation? #11221

### ISSUE THREAD

**Issue by vicky-rain** [primefaces/primeng#11265]
Hi,

previous question issues #11221

Below is the Stackblitz example address：

https://stackblitz.com/edit/primeng-tableedit-demo

**Please see the red place in the picture below, when I click the edit button to edit the quantity above**

![image](https://user-images.githubusercontent.com/16696067/156489069-edd33198-e800-4316-a06b-1bfc774f0562.png)

**If the wrong information is entered, the current situation is that there is a problem with the entered information and the edit mode is exited.
The way I want to achieve this is: if you enter the wrong information, click the save button, prompting that there is a problem with the input information, but do not exit the editing mode.**

![image](https://user-images.githubusercontent.com/16696067/156490027-51e5bc48-a56a-4ebc-9dfe-099d46da7eef.png)

![image](https://user-images.githubusercontent.com/16696067/156490084-c2e52766-1d4a-428c-bb7d-3b5362a38287.png)

_Originally posted by @vicky-rain in https://github.com/primefaces/primeng/issues/11221#issuecomment-1057628448_

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by hikkistudy** [comment]
Hello,
this improvement was not developed.

**Comment by nZeus** [comment]
The issue still persists indeed.
I checked the source-code and noticed this:
https://github.com/primefaces/primeng/blob/2f431599c6a27d7cc382449efe8bbc2caa3d2b6f/packages/primeng/src/table/table.ts#L2558

Currently it relies on the DOM of the row - if there is an html element with the `ng-invalid ng-dirty` class then it doesn't save; but it doesn't allow you to control the behavior from the onSave handler
