### ISSUE TITLE
p-chips Comma Separator on android mobile not working with comma

### ISSUE THREAD

**Issue by iamsajithsasi** [primefaces/primeng#11270]
It's not working with Android mobiles. linked [screenshot](https://ibb.co/zSKNrg1) for your reference.

below is the package.json reference
"dependencies": { "@angular/animations": "^13.2.3", "@angular/cdk": "^13.2.2", "@angular/common": "~13.2.3", "@angular/compiler": "~13.2.3", "@angular/core": "~13.2.3", "@angular/forms": "~13.2.3", "@angular/platform-browser": "~13.2.3", "@angular/platform-browser-dynamic": "~13.2.3", "@angular/router": "~13.2.3", "bootstrap": "^4.6.1", "bootstrap-icons": "^1.8.1", "primeicons": "^5.0.0", "primeng": "^13.1.1", "rxjs": "~7.4.0", "tslib": "^2.3.0", "zone.js": "~0.11.4" }

>>>>>>>>>>>

Hi,

I couldn't replicate this issue with the latest PrimeNG and IOS, the component works fine.

Regards

_Originally posted by @cetincakiroglu in https://github.com/primefaces/primeng/issues/11249#issuecomment-1055413223_

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by NenadKaevik** [comment]
Was this resolved? I am facing the same issue. Comma separator does not work on mobile. I am currently using `"primereact": "8.6.1",`
