### ISSUE TITLE
dialog - unwanted lines under small screen

### ISSUE THREAD

**Issue by jiangyh1024** [primefaces/primeng#11275]
https://primeng-dialog-demo-g97b9l.stackblitz.io/

![image](https://user-images.githubusercontent.com/34930870/156679215-e7f4be2b-5aaa-477e-bb73-638a89c0671e.png)

here is the Stackblitz example,

open it on your iphone or use chrome device tool

image

you will see the lines

**Comment by jiangyh1024** [comment]
problem solved 

<img width="521" alt="image" src="https://user-images.githubusercontent.com/34930870/156956430-fd5db95e-5115-4b58-8838-4c62a2ad3189.png">

add background color  (white) to 'p-dialog'

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
