### ISSUE TITLE
Error when combining any text input with a p-splitter 

### ISSUE THREAD

**Issue by Hoopou** [primefaces/primeng#11272]
**Error when combining any text input with a p-splitter. in primeng version 13.2.0 **

This is a duplicate of [11256](./11256 ) because it was closed without proper testing. **MAKE SURE PRIMENG VERSION IS SET TO 13.2.0**

I've tested **InputTextModule** and **TextAreaModule** and both of them don't work with a splitter.

see below the stackblitz example.

```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Here is an example of the error in stackblitz:
https://stackblitz.com/edit/angular-ivy-peq7s4?devtoolsheight=33&file=src/app/app.component.html

This code below currently doesn't work. **in primeng version 13.2.0**

```
<p-splitter
  [style]="{ height: '100%', width: '100%' }"
  styleClass="messageSplitter"
  [panelSizes]="[20, 80]"
  [layout]="'horizontal'"
>
  <ng-template pTemplate>
    <input type="text" pInputText />
  </ng-template>
  <ng-template pTemplate>
    ERROR WITH SPLITTER (check console logs)
  </ng-template>
</p-splitter>
```

**Current behavior**
Error showed in console:
Cannot read properties of undefined (reading 'style')

**Expected behavior**
The splitter should work properly and we should be able to add any input in the panels

**Minimal reproduction of the problem with instructions**

1. Install primeng **version 13.2.0**
2. Add styles references in angular.json
3. import SplitterModule and InputTextModule in app.module.ts
4. Add both of them in a component

* **PrimeNG version:** 13.2.0

**Comment by phamhoaithuong** [comment]
I have the same issue in my code, when I make child component to use input, it work for me

**Comment by Tovil-Toba** [comment]
The issue still exists in 14.0.0 version.

**Comment by Alexzerntev** [comment]
As a workaround if you put the input(s) in a separate angular component - it works.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by Asifnawazmiani** [comment]
Hi,
I am still facing the issue even in 14.x.x version, but I have found a solution for that, its a trick or if I say in Urdu (Jugaar). Well, you can do code like that,

` <p-splitter  [panelSizes]="[20,80]" styleClass="mb-5">
    <ng-template pTemplate>
        <div class="row flex align-items-center justify-content-center" style="width: 100%;">
            Panel 1
        </div>
    </ng-template>
    <ng-template pTemplate>
        <div style="width: 100%;">
          <div class="border-flex" fxLayout="row" fxLayoutAlign="space-between center">
            <div fxLayout="row" fxLayoutAlign="start center">
              
              <p-autoComplete inputStyleClass="custom-p-inputtext-sm" placeholder="{{SelectedSearchType.placeholder}}"></p-autoComplete>
          </div>`

Global CSS
`.custom-p-inputtext-sm {
  height: 45px;
  border-radius: 0px;
  width: 400px;
}
.custom-p-inputtext-sm {
  .p-autocomplete{
    .p-autocomplete-loader {
      display: none;
    }
  }
}
`

![html to splitter problem](https://user-images.githubusercontent.com/33758822/210124075-f3b11267-ab9f-4474-a521-4317d70f6ae6.jpg)
![css to splitter problem](https://user-images.githubusercontent.com/33758822/210124078-c0c73935-a7e9-42ef-90f8-98b31e981535.jpg)


I am not an expert of angular or primefaces, but I tried a thing to avoid the issue till it becomes fixed.
Thank you

**Comment by thelegendvkd** [comment]
I'm still facing this issue. Any resolved please let me know
