### ISSUE TITLE
New Calendar in beta20 doesn't take default-value

### ISSUE THREAD

**Issue by kcsahoo** [primefaces/primeng#1127]
If you select default date to say 15/11/2016,
the date shows correctly in input textbox and pop up.
But if you have selected yearNavigator and monthNavigator, the monthNavigator dropdown does not initialize.
The dropdown defaults to current month , not the default month  set.

Another issue: Not able set default date through defaultDate attribute, only possible by initializing model.

Use the following to simulate:

<p-calendar [(ngModel)]="date1" [showIcon]="true" dateFormat="dd/mm/yy" [monthNavigator]="true" [yearNavigator]="true" yearRange="1980:2050">
</p-calendar>

In component, use
this.date1=new Date('2018,9,15');
to set initial value

For the defaultValue attribute issue, use
<p-calendar [(ngModel)]="date1" [showIcon]="true" dateFormat="dd/mm/yy" [monthNavigator]="true" [yearNavigator]="true" yearRange="1980:2050" defaultValue="13/12/2015">
</p-calendar>

**Comment by elastictree** [comment]
I created a Demo at: http://plnkr.co/edit/HxeUXcnX8HxiqGqNnScQ?p=preview

The normal input-fields are filled with their default-value, but the Calendar component is empty!

**Comment by cagataycivici** [comment]
Fixed via 1140

**Comment by cagataycivici** [comment]
Also defaultDate is used which month-year to render, defaults to today if no value is defined or to value is there is a value.
