### ISSUE TITLE
Tree does not render items...

### ISSUE THREAD

**Issue by born2net** [primefaces/primeng#1128]
I am trying to use the TreeModule and while it "seems" to work it does not render anything on screen.
you can see from the snapshot that the Tab module for example above it works fine, but the tree does not, I used the same example as the primeng source:

```
import {TreeModule, TabViewModule} from 'primeng/primeng';
import {TreeNode} from 'primeng/primeng';

<p-tree [value]="files" selectionMode="single"></p-tree>

 files: TreeNode[] = [
        {
            "data":
                [
                    {
                        "label": "Documents",
                        "data": "Documents F
                        ...
                    
```

![tree](https://cloud.githubusercontent.com/assets/5090936/19694978/3917ddd6-9a96-11e6-9c5c-15efe85b6a7e.PNG)

regards,

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by cagataycivici** [comment]
Can you post your full files data please? Or can you just try with;

http://www.primefaces.org/primeng/showcase/resources/data/files.json

**Comment by born2net** [comment]
this is my data hard coded:

```
files: TreeNode[] = [
        {
            "data": [
                {
                    "label": "Documents",
                    "data": "Documents Folder",
                    "expandedIcon": "fa-folder-open",
                    "collapsedIcon": "fa-folder",
                    "children": [{
                        "label": "Work",
                        "data": "Work Folder",
                        "expandedIcon": "fa-folder-open",
                        "collapsedIcon": "fa-folder",
                        "children": [{
                            "label": "Expenses.doc",
                            "icon": "fa-file-word-o",
                            "data": "Expenses Document"
                        }, {
                            "label": "Resume.doc",
                            "icon": "fa-file-word-o",
                            "data": "Resume Document"
                        }]
                    },
                        {
                            "label": "Home",
                            "data": "Home Folder",
                            "expandedIcon": "fa-folder-open",
                            "collapsedIcon": "fa-folder",
                            "children": [{
                                "label": "Invoices.txt",
                                "icon": "fa-file-word-o",
                                "data": "Invoices for this month"
                            }]
                        }]
                },
                {
                    "label": "Pictures",
                    "data": "Pictures Folder",
                    "expandedIcon": "fa-folder-open",
                    "collapsedIcon": "fa-folder",
                    "children": [
                        {
                            "label": "barcelona.jpg",
                            "icon": "fa-file-image-o",
                            "data": "Barcelona Photo"
                        },
                        {
                            "label": "primeui.png",
                            "icon": "fa-file-image-o",
                            "data": "PrimeUI Logo"
                        }]
                }
            ]
        }
    ]
```

**Comment by born2net** [comment]
figured it out, closing, tx! and keep up the good work!

**Comment by cbgr** [comment]
Hi all, I have a similar situation only with p-dataTable. 
My code:
`
    <p-dataTable [value]="cars" [paginator]="true" [pageLinks]="10" [rowsPerPageOptions]="[20,50,100]" resizableColumns="true"
                 [loading]="loading" >
        <p-column field="Vin" header="Vin" [filter]="true"></p-column>
        <p-column field="Year" header="Year" [filter]="true"></p-column>
        <p-column field="Brand" header="Brand" [filter]="true"></p-column>
        <p-column field="Color" header="Color" [filter]="true"></p-column>
    </p-dataTable>
`
this is my data hard coded:
`
    cars: any[] = [{
        Vin: "55555",
        Year: "2012",
        Brand: "audi",
        Color: "red266666666666666666"
    }
....
];
`
the table looks working, but there is no items. But if you change the value of the page count, the items will be displayed. 

![pd2](https://user-images.githubusercontent.com/29457687/27630198-730d0d80-5bfd-11e7-90de-626286be1476.JPG)
![pd1](https://user-images.githubusercontent.com/29457687/27630199-7311f840-5bfd-11e7-8dc1-8dc60a9064b4.JPG)


what could be the problem?

**Comment by vidhyaneelakantan** [comment]
Hi @born2net, I am facing the same issue. Can you tell me how you got this resolved?
Thanks

**Comment by arien213** [comment]
Hey @born2net, kindly let know what was the fix.
I am facing the same issue. I have everything same as the Tree example from PrimNG and no issues compiling the code but nothing comes up in the UI.

**Comment by kiedd** [comment]
Hi @arien213 
I faced the same issue with component UI not rendering, and found a way to resolve it.
I looked at the imports in demo example here https://github.com/primefaces/primeng/blob/master/src/app/showcase/components/treetable/treetabledemo.module.ts
and put all missing imports into my module (don't forget to put them into NgModule imports as well).
For me they were: GrowlModule, TabViewModule, MultiSelectModule, ContextMenuModule and FormsModule (from angular)

**Comment by arien213** [comment]
Hi @kiedd 

Thanks for your response. I appreciate it.
It worked for me after i copied the styles from "\angular-tree-component\dist\angular-tree-component.css" into the styles.css of my project.
Not sure if this is a bug, because i did not have to add any additional missing imports like you did.
I will surely test with your suggestions and post the response.

Right now i am facing a different issue: i wanted to have the tree expanded when the page loads with a default selected value and it works but intermittently the tree does not expand and i see the below error on the console:

 ERROR TypeError: Cannot read property 'forEach' of undefined
    at TreeModel.expandAll (tree.model.js:280)
    at executeAction (mobx.module.js:911)
    at TreeModel.res (mobx.module.js:902)
    at NotificationComponent.onInitialized (notification.component.ts:55)
    at Object.eval [as handleEvent] (NotificationComponent.html:99)
    at handleEvent (core.js:13589)
    at callWithDebugContext (core.js:15098)
    at Object.debugHandleEvent [as handleEvent] (core.js:14685)
    at dispatchEvent (core.js:10004)
    at eval (core.js:12343)

so my code looks like this
HTML:
<tree-root #myTree [nodes]="nodes" [options]="options" (initialized)="onInitialized(myTree, $event)"></tree-root> 
Component:
  nodes = null;  
  options: ITreeOptions = { };

onInitialized(tree, event) {
    tree.treeModel.expandAll(); //this is the line 55 being pointed by the error above
   //for testing setting the default selected node to be number 10
    tree.treeModel.getNodeById('10').mouseAction('click', event);    
  }

Any suggestions are greatly appreciated.
