### ISSUE TITLE
PickList | Keep selection after moving an item

### ISSUE THREAD

**Issue by cetincakiroglu** [primefaces/primeng#11283]
Requested by a PRO User

**Comment by gkarapeev** [comment]
Hey there. There is a `keepSelection` option [in the component's API](https://www.primefaces.org/primeng/#/picklist), but I can't figure out if it's broken, or I just don't understand what it does. I was expecting it to keep the moved item selected, but [I get an error](https://stackblitz.com/edit/primeng-picklist-demo-4x89wb?file=src/app/app.component.html) that this isn't a known input.

**Comment by cloggy45** [comment]
Any update on this, keepSelection doesn't seem to be working.

**Comment by mertsincan** [comment]
Hi @gkarapeev and @cloggy45,

So sorry for the delayed response! Could you please create a new issue about it?

Best Regards,
