### ISSUE TITLE
Multiselect : Select all check box and search box not accessible by up/down arrow keys

### ISSUE THREAD

**Issue by nimanda** [primefaces/primeng#11294]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewed in detail and assisted.

https://primeng-multiselect-demo-64yru3.stackblitz.io
https://stackblitz.com/edit/primeng-multiselect-demo-64yru3?file=src/app/app.component.html

**Current behavior**
On the MultiSelect component , search text box and the selectall/toggleall check box are not accessible by keyboard. The options in the drowpdon 
**Expected behavior**
On the MultiSelect component , search text box and the select all check box should be accessible by keyboard similar to the options.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
Need this behavior to comply with WCAG 2.1 specifications

**Please tell us about your environment:**Windows, VSCode, Node

* **Angular version:**13.2.3

* **PrimeNG version:**11.4.5

* **Browser:**[all]
 
* **Language:** [TypeScript 4.5.5]

* **Node (for AoT issues):** `node --version` =

**Comment by yigitfindikli** [comment]
All accessibility issues will be fixed in 2022 Q2 Thanks for your report.
