### ISSUE TITLE
Calender shows incorrect week numbers (week 1 2022 starts at Jan 9th?!)

### ISSUE THREAD

**Issue by migael** [primefaces/primeng#11295]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewed in detail and assisted.

https://wmaiqvlqx.github.stackblitz.io

**Current behavior**
It applies to ALL primeng calendars that show week numbers
1st week of 2022 starts at Jan 9th.

**Expected behavior**

first week of 2022 is expected to start at Jan 2nd
"The ISO 8601 definition for week 01 is the week with the first Thursday of the Gregorian year"
https://en.wikipedia.org/wiki/ISO_week_date
in this case, 2022 falls under case "[B][A]"

**Minimal reproduction of the problem with instructions**
step 1: go to: https://www.primefaces.org/primeng/#/calendar
step 2: go to January

**What is the motivation / use case for changing the behavior?**
It has been incorrect since the new year started.
primeng states it's ISO-8601 complient, however looking at any other ISO-8601 will show inconsistencies.

Other information should not matter since the bug shows up on the primeng website itself.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by abhixkj** [comment]
Hi, this issue still exists. Was there any fix included for this ?

**Comment by citruspress** [comment]
This is still an issue. It's visible in the sample here: https://primeng.org/calendar#inline.

**Comment by abhixkj** [comment]
I had raised a separate issue for this, but that was marked as unable to replicate. Not sure how such a simple issue cannot be replicated as it is in plain sight on the demo page. I have even fixed it by adding an optional property and created a PR previously but no one bothered to check.
https://github.com/primefaces/primeng/pull/14823
I just merged it with the latest code and have raised it again. @citruspress, meanwhile you can check the changes and add the calendar control as an external module to your project and patch the src/app/components/calendar/calendar.ts file with my change and see if it helps.
