### ISSUE TITLE
PrimeNG 7 documentation

### ISSUE THREAD

**Issue by digit81** [primefaces/primeng#11304]
Documentation of PrimeNG 7 is not available any more. Last week I could check it under:
 [https://www.primefaces.org/primeng-7.1.3/#/](https://www.primefaces.org/primeng-7.1.3/#/) Now it redirects to blog post. 

I need old documentation for legacy app that my company still support.

Do you plan to bring back old documentation page?

**Comment by yigitfindikli** [comment]
Hi,

You can download locally v7 documentation from https://github.com/primefaces/primeng/tree/7.1.3. We don't have a plan about bringing un-lts documentation.

**Comment by Fkiesnh86** [comment]
I noticed that the documentation for the previous version has disappeared since the release of v18. How can I obtain the v7 documentation?

**Comment by rvalls-grupo-pinero** [comment]
Have they really deleted the documentation? This level of unprofessionalism is unprecedented.
