### ISSUE TITLE
Table UI breaks with different columns widths 

### ISSUE THREAD

**Issue by sayh** [primefaces/primeng#11303]
**I'm submitting a ...**  (check one with "x")
The original issue was closed, but as this is still an issue, I've created a new bug report.
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/primeng-tablevirtualscroll-demo-irqv2f?file=src%2Fapp%2Fapp.component.html

**Current behavior**
Table columns are not aligned (head + body) anymore when defining different column widths. It seems to be fine when using the same width (or min-width) for each column. 

We have a big data table and using different widths for each column, worked fine with primeng v11. After upgrading to a newer version the UI breaks.

Might be related: https://github.com/primefaces/primeng/issues/10776

Here is the original issue I opened: https://github.com/primefaces/primeng/issues/11232

If the content is too long. If I set the width to 200px for the "Color" column the UI breaks again. With the older primeng versions I configured the column width like this and didn't have the issues:

<ng-template pTemplate="colgroup" let-columns> <colgroup> <ng-container *ngFor="let column of columns"> <ng-container *ngIf="column.visible"> <col [ngStyle]="{'width.px': column.width}"> </ng-container> </ng-container> </colgroup> </ng-template>

**Expected behavior**
Different widths for columns shouldn't break the UI.

**Minimal reproduction of the problem with instructions**

- Table with scroll enabled:  `[scrollable]="true"  scrollHeight="flex" [virtualScroll]="true"`
- Table head with `pTemplate="headergrouped"`
- Set different width (min-width) for columns
- Resize view that horizontal scroll is enabled

**What is the motivation / use case for changing the behavior?**
Blocks upgrade to a newer primeng version :(

**Please tell us about your environment:**

* **Angular version:** 13.2.0

* **PrimeNG version:** 13.1.0

* **Browser:** [Chrome Version 98.0.4758.102 |  Microsoft Edge Version 98.0.1108.56 ]

* **Language:** [TypeScript 4.5.5]

* **Node (for AoT issues):** `node --version` =   v14.16.0

**Comment by yigitfindikli** [comment]
You can use word-break and bigger height for your rows like: https://stackblitz.com/edit/primeng-tablevirtualscroll-demo-vryqkf?file=src%2Fapp%2Fapp.component.html or you can use overflow for your table cells.

**Comment by sayh** [comment]
That's just a workaround, isn't it? Why shouldn't it be possible to define different width? This is totally working with older versions.

Using bigger height is not really an option in my case.
