### ISSUE TITLE
[Primeng : Table] Rowspan attribute is not working as expected when used along with scrollable attribute.

### ISSUE THREAD

**Issue by Aryan001** [primefaces/primeng#11310]
I'm using rowspan for a column and it seems to be working as expected with the below code.
[PrimengTable_WorkingScenario.txt](https://github.com/primefaces/primeng/files/8282185/PrimengTable_WorkingScenario.txt)

When I tried to freeze the rowspan column, I added the scrollable attribute to the table
It seems the scrollable attribute for frozen column is not working as expected for rowspan. 
[PrimengTable_NotWorkingScenario.txt](https://github.com/primefaces/primeng/files/8282199/PrimengTable_NotWorkingScenario.txt)

**Comment by cetincakiroglu** [comment]
Hi,

The issue is not clear, please provide a StackBlitz example and reopen the issue.

Regards
