### ISSUE TITLE
Calendar : range mode with option showTime display only one timepicker

### ISSUE THREAD

**Issue by sancaruso** [primefaces/primeng#11316]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Using `p-calendar` with `selectionMode="range"` and option `showTime` display only one timepicker, that set the time for the end date of the selected period.

**Expected behavior**
We should have two timepickers that respectively set the hour for the begin date and the end date.

**What is the motivation / use case for changing the behavior?**
With range mode it would be more consistant to select also a range of time and not only of date.

**Comment by cetincakiroglu** [comment]
Hi,

Currently the second timepicker would be unnecessary since you can select a time for both start and the end of the range.
You can inspect the behavior from here https://stackblitz.com/edit/primeng-calendar-demo-k3spj4?file=src%2Fapp%2Fapp.component.html

Regards

**Comment by El-Tommy** [comment]
@sancaruso Did you find any alternative to this behavior?

A lay user will not be able to easily identify when the start time is.
Even though there is a text field with it right above.
