### ISSUE TITLE
Add rows="flex" option when using a paginator on a table

### ISSUE THREAD

**Issue by mconner** [primefaces/primeng#11312]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/primeng-tableflexscroll-demo-gzwxus?file=src%2Fapp%2Fapp.component.html

**Current behavior**

When using a paginator, the rows are required, or nothing is displayed, and there's no way to specify use all available.

**Expected behavior**

If rows is set to "flex", rows would effectively be set to the number that can fit in the space available, based on the table headers, footers, etc, and the parent height, similar to scrollHeight="flex"

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

A table may be in a resizable component (e.g.: a dashboard widget).   It should use the space available, whether scrolling or paginating.

**Please tell us about your environment:**

Windows, IntelliJ, npm, JBoss

* **Angular version:** 13.X

* **PrimeNG version:** 13.X

* **Browser:** Chrome v16.14.0, Edge v16.14.0

 
* **Language:** TypeScript 4.5.X

* **Node (for AoT issues):** `node --version` =   v16.14.0

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
