### ISSUE TITLE
multiselect filter logic should be contains

### ISSUE THREAD

**Issue by kcsahoo** [primefaces/primeng#1131]
IN THE CURRENT VERSION, THIS WORKS ON STARTS WITH LOGIC.
MOST USERS IN FORUM WANT IT TO BE CONTAINS.
THIS IS A SMALL NON-BREAKING ONE-LINE CHANGE.
PLEASE ACCOMMODATE IT IN RC1.

**Comment by cagataycivici** [comment]
Please write in lower case when reporting issues. Switched to contains, note that more filtering methods are on the way like starts with, ends with and custom.
