### ISSUE TITLE
[p-orderlist] p-orderlist is not refresh correctly when it do push to list in component

### ISSUE THREAD

**Issue by smootyDev** [primefaces/primeng#11311]
[ x ] bug report => Search github for a similar issue or PR before submitting

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-orderlist-demo-qaquis

**Current behavior**
p-orderlist is not refresh correctly

**Expected behavior**
You should see the product when adding it to the component.

**Minimal reproduction of the problem with instructions**
When you click add button we do push to list in component but we don't see product in orderlist. Later, we search in orderlist "Bamboo" and product appear.

* **Angular version:** 13.2.6
* **PrimeNG version:** 13.3.0

**Comment by cetincakiroglu** [comment]
Hi,

The component works fine, here is the refactored and working version of your code sample.
https://stackblitz.com/edit/primeng-orderlist-demo-1j8mk3

Regards

**Comment by smootyDev** [comment]
Hi,

Thanks a lot.

Regards

**Comment by NuriDurmus** [comment]
Hi @cetincakiroglu 
Why this code "this.products.push(newItem);" doesn't work?

**Comment by nblum** [comment]
>  Why this code "this.products.push(newItem);" doesn't work?

Angular does not detect changes in nested objects or arrays by default when they are passed in an input field. The refactored approach creates a new array instead of changing the existing one
