### ISSUE TITLE
Column widths are not recalculated correctly on drag&drop for Scrollable tables with Columns Resize enabled

### ISSUE THREAD

**Issue by emamedov2** [primefaces/primeng#11326]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-table-scroll-resize-reorder?file=src%2Fapp%2Fapp.component.html

**Current behavior**
If user resizes column and drag/drops column to change the order then columns will not exchange the widths. The width of new position will be used for dropped column.

Reason of the issue: the table uses next styles for resize of flex tables that are not recalculated on column reordering

```
#pr_id_106-table > .p-datatable-thead > tr > th:nth-child(1) {
    flex: 0 0 100px !important;
}
```

**Expected behavior**
Column widths are moved together with columns

**Minimal reproduction of the problem with instructions**
STEPS TO REPRODUCE:
- Open https://stackblitz.com/edit/primeng-table-scroll-resize-reorder?file=src%2Fapp%2Fapp.component.html
- Expand third column, make it quite big
- Drag and drop it to first position
- First and Second columns will be shifted to the right (expected) but widths are unexpected (1st col width = old 1st col width, 2nd col width = old 2nd col width and etc):

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
* **Angular version:** 13.0.1
* **PrimeNG version:** 13.0.0-rc-2
* **Browser:** [all]
* **Language:** [all]
* **Node (for AoT issues):** `node --version` =

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template

**Comment by emamedov2** [comment]
Hi @yigitfindikli,

Thanks for the quick reply. Unfortunately still reproduceable on new version. Raised with latest version (13.3.2) [11372](https://github.com/primefaces/primeng/issues/11372)

To reproduce just resize 3rd column ("Country") to make it quite large and drag&drop it to first position. You will see that now "Name" column becomes the largest one while "Country" is now the same size as was "Id" column

Regards

**Comment by jiteshvdb** [comment]
@yigitfindikli How can you close the issue without getting a confirmation from users !
I'm still able to REPLICATE the issue and seems @emamedov2 has open a this issue again as soon as you marked it closed https://github.com/primefaces/primeng/issues/11372
