### ISSUE TITLE
p-inputNumber not working in editable TreeTable

### ISSUE THREAD

**Issue by thatsmeta** [primefaces/primeng#11323]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/primeng-treetableedit-demo-foktqr?file=src%2Fapp%2Fapp.component.html

**Current behavior**

In an editable TreeTable, if you use `<p-InputNumber>` instead of `<input type="number">`, the editing is not working properly. If you edit a cell and then tab to the next cell (without pressing enter), the new input value is not written back into the model and is also not given in the onEditComplete event.

I think it might have something to do with the `<p-InputNumber>` element being destroyed before it can write the new value to the model in onBlur.

**Expected behavior**

I would have expected `<p-inputNumber>` to work in an editable TreeTable.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 13.X

* **PrimeNG version:** 13.X

* **Browser:** [Chrome | Firefox]

 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =   14.15.4

Any help is appreciated.

**Comment by cetincakiroglu** [comment]
Hi,

This issue is due to misusage. Here is a refactored and working version of your StackBlitz example.
https://stackblitz.com/edit/primeng-treetableedit-demo-upvmgg?file=src%2Fapp%2Fapp.component.html

Regards

**Comment by thatsmeta** [comment]
Hi, sorry, it seems that my stackblitz was missing an ngModel. However, you refactored version is still not working. The user input ist not saved when tabbing from cell to cell. Can you please re-open this issue?
