### ISSUE TITLE
[FEATURE REQUEST]:  Gridster Component

### ISSUE THREAD

**Issue by rrekapalli** [primefaces/primeng#11337]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Expected behavior**
Any plans to provide Gridster ([https://dsmorse.github.io/gridster.js/](url)) like Component in this library.  Would be a great addition for dashboards!

**Comment by uebelmar** [comment]
there is already an angular package for gridster: https://www.npmjs.com/package/angular-gridster2

**Comment by rrekapalli** [comment]
Hi there,  Yes, we have seen this and is a pretty good one!  However, this is a third party package and wondering if this could be part of primeng itself.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
