### ISSUE TITLE
Table Scrollable documentation links to stackblitz with different source.

### ISSUE THREAD

**Issue by mconner** [primefaces/primeng#11334]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

The current documentation for [Table column resize](https://www.primefaces.org/primeng/#/table/colresize), under Scrollable with Variable Width, describes using flex-basis. However, the widths are all 25% (and so don't vary).  More importantly, the documentation links to a StackBlitz where it uses _width_, instead of flex-basis.  if you change the with of the columns and data, to see some difference, For Example: 

[25,10, 25, 35](https://stackblitz.com/edit/primeng-tablecolresize-demo-dkvpvs?file=src/app/app.component.html)
It does not work.  If I switch it to [flex-basis](https://stackblitz.com/edit/primeng-tablecolresize-demo-dkvpvs?file=src/app/app.component.html), it does.

Additionally, the documentation does not cover the issue of using columnResizeMode="expand" so that you can set widths that don't fit.

**What is the motivation / use case for changing the behavior?**
Documentation should point to the examples it describes.

**Please tell us about your environment:**

Windows 10, IntelliJ, npm 

* **Angular version:** 13.X

* **PrimeNG version:** 13.X

* **Browser:** [Edge, Chrome ]

**Comment by yigitfindikli** [comment]
Hi,

Thanks for your report. Will be fixed next Stackblitz update.
