### ISSUE TITLE
Calendar year range settings do not work in Beta-20

### ISSUE THREAD

**Issue by kcsahoo** [primefaces/primeng#1133]
As documented, you should be able to set 'c-nn:c+nn' and  '-nn:+nn'  relative to current century and year
This only works for absolute '-nnnn:+nnnn'
This was working with Jquery plugins.

**Comment by cagataycivici** [comment]
No plans to redo now, if more users demand it, we'll bring it back. Thank you.

**Comment by armved** [comment]
Can we get it back please?
