### ISSUE TITLE
Responsive Stack and add [scrollable]="true" not working responsive stack

### ISSUE THREAD

**Issue by Th14go** [primefaces/primeng#11331]
In responsiveLayout="stack" mode after adding [scrollable]="true" scrollHeight="800px" to work in responsive mode.

Example :
https://stackblitz.com/edit/primeng-tableresponsive-demo-2kkztw?file=src%2Fapp%2Fapp.component.html

Behavior:
After decreasing the screen size below 800px, the horizontal scrollable would be activated, and reaching the breaking point of 640px mobile, the responsive stack mode would enter

Chrome:   99.0.4844.82

**Comment by STIAANWOL** [comment]
I'm getting the same issue. 
adding scrollable to responsiveLayout="stack" will ignore scrollHeight="400px".

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
