### ISSUE TITLE
p-table selection in stateStorage does not change if [(selection)] array is changed directly in .ts code

### ISSUE THREAD

**Issue by dhamzic** [primefaces/primeng#11330]
I need to change  p-table [(selection)] dynamically in .ts code but the session storage doesn't want to update dynamically changed data. 
Why is that so?

HTML 
```
<p-table [value]="orders" [columns]="selectedColumns"
            [(selection)]="selectedOrders" 
            stateStorage="session" stateKey="statedemo-session">
```

.ts code
```
this.selectedOrders = [];
this.selectedOrders = this.selectedOrders.concat(selectedOrdersTemp);
```

**Comment by dhamzic** [comment]
The problem has been solved using #dt reference on p-table and changing its selection.

**HTML**

```
<p-table #dt [value]="orders" [columns]="selectedColumns"
            [(selection)]="selectedOrders" 
            stateStorage="session" stateKey="statedemo-session">
```

**.ts code**
`@ViewChild("dt") dataTableComponent: Table | null = null;`

```
someMethod(): void{
              this.dataTableComponent.selection = [];
              this.dataTableComponent.selection = [...selectedOrdersTemp];
              this.dataTableComponent.saveState();
}
```

**Comment by alimdi** [comment]
Not working on my side and it's driving me crazy as I've tried everything to make it work inside selectionChange event

- Updating [(selection])
- Updating with viewchild
- triggering chage detector
