### ISSUE TITLE
pDroppable directive does not follow scoping rules for Dragenter the way Drop does and cursor is incorrect

### ISSUE THREAD

**Issue by hlesterJha** [primefaces/primeng#11338]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
Drag elements with different scopes fire the DragEnter event and always display the copy icon.

**Expected behavior**
DragEnter should check for the correct scope, the same behavior in the Drop, and the cursor should not change when scopes do not match.

**Minimal reproduction of the problem with instructions**
see "https://stackblitz.com/edit/github-3rdczy?file=src/app/app.component.ts" for an example of two elements with differing scopes. The cursor will change to copy and the dragenter event will fire. The cursor is also incorrect since the dropeffect is move.

**What is the motivation / use case for changing the behavior?**
Need to control the cursor display for droppable zones. Also would make it easier if the only time the dragenter was fired was if scopes matched, the same as in drop.

**Please tell us about your environment:**
Windows, VS Code, npm, angular dev env

* **Angular version:** 12.x

* **PrimeNG version:** 12.2.1

* **Browser:** Chrome
 
* **Language:** TypeScript 4.3.5 | ES6

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
