### ISSUE TITLE
p-table [scrollable]="true" resize headers

### ISSUE THREAD

**Issue by E22T07** [primefaces/primeng#11340]
**Current behavior**
When I put the [scrollable] property in true the size of the header columns change and not match with the content columns.

**Expected behavior**
I expect that when the [scrollable] property is set in true, the table look the same but with a vertical scrolling.

In this link is the example that I was used to test it: https://stackblitz.com/edit/angular-ivy-wo3zjb
https://github.com/E22T07/PrimeNgTableExample

I am using Windows and I tested in Chrome and Firefox.

Angular version: 13.3.0
PrimeNg version: 13.3.0

**Comment by E22T07** [comment]
Hi, now it is working, thanks

**Comment by E22T07** [comment]
Hi, when I wrote it Is working I was talking about that you now could see
the example but not that the behavior change, the issue still happened.


Thanks

**Comment by opremicJohannes** [comment]
Can confirm this is happening for horizontal scrolling. If there are too many columns, the headers and table cells will be misaligned as in OP's stackblitz. If you use [scrollable]=false, the issue goes away.

The grouping in the header can be aligned by using pTemplate="headergrouped". But this won't do anything for the body.

Please advise.
