### ISSUE TITLE
Split button doesn't work with styleClass

### ISSUE THREAD

**Issue by pasevin** [primefaces/primeng#11349]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Your own Stackblitz has the same issue.
https://primeng-splitbutton-demo.stackblitz.io

**Current behavior**
Using ```styleClass``` doesn't work.

**Expected behavior**
Split button should work with the ```styleClass```.

**Minimal reproduction of the problem with instructions**
```
<p-splitButton
    [label]="label"
    [model]="items"
    [styleClass]="'p-button-lg p-button-raised'"
  ></p-splitButton>
```

* **Angular version:** 13.2.2

* **PrimeNG version:** 13.3.1

**Comment by yigitfindikli** [comment]
Seems to working: https://stackblitz.com/edit/primeng-splitbutton-demo
