### ISSUE TITLE
p-panel icons or buttons to be on the right (in the header)

### ISSUE THREAD

**Issue by MitkoMKD** [primefaces/primeng#11345]
Hi Prime-ng team,

First of all, thanks for a wonderful open-source and free component library. I have been using the library for few months.
But i need small help please.

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[x ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
I have updated the primeflex from v2 to v3.The icons/buttons that are inside my p-panel , in the header were on the right before the migration to v3. I have updated/migrated my project to v3 more than 90% succesfully, but i have difficulties moving the icons or buttons that are on the left right now. The primeplex version is v3, primeng version is 13.3.0.

**Expected behavior**
The icons to be on the right. Please write me with example.

**Comment by cetincakiroglu** [comment]
Hi,

I couldn't replicate the issue, could you please provide a StacBlitz example?

Regards

**Comment by MitkoMKD** [comment]
![image](https://user-images.githubusercontent.com/11562267/160375483-4f488721-9303-47da-8799-fe291e4e9b6b.png)

**Comment by MitkoMKD** [comment]
![image](https://user-images.githubusercontent.com/11562267/160375586-bd87b369-08d4-43a2-9375-cac56ca889a2.png)

**Comment by cetincakiroglu** [comment]
Hi,

You can use iconPos input property of panel component to align icons on the left, right(default), center. [StackBlitz Example](https://stackblitz.com/edit/primeng-panel-demo-raiqgu?file=src%2Fapp%2Fapp.component.html)

or

You can simply just change pTemplate="Icons" as pTemplate="icons"

Regards.

**Comment by MitkoMKD** [comment]
@cetincakiroglu  Hi again, sorry to bother but i still have the same problem. They are still in the left side next to the header(title).
Do i need to apply the property in here : 
`<p-panel header="Toplists" [iconPos] = "right">
    <ng-template pTemplate="icons" >
            <button pButton class="p-button-outlined p-button-rounded" pTooltip="Clear filters" tooltipPosition="left"
                icon="pi pi-filter-slash" (click)="clearFilters()"></button>
            <button [isEditor]="salesModule()" class="p-button-rounded p-button-success mr-1 ml-1" pButton
                type="button" icon="pi pi-plus" routerLink="./editor/0">
            </button>
    </ng-template>
<p-panel>`
Or : 
`<p-panel header="Toplists" iconPos = "right">
    <ng-template pTemplate="icons" >
            <button pButton class="p-button-outlined p-button-rounded" pTooltip="Clear filters" tooltipPosition="left"
                icon="pi pi-filter-slash" (click)="clearFilters()"></button>
            <button [isEditor]="salesModule()" class="p-button-rounded p-button-success mr-1 ml-1" pButton
                type="button" icon="pi pi-plus" routerLink="./editor/0">
            </button>
    </ng-template>
<p-panel>`
Or: 
`<p-panel header="Toplists">
    <ng-template pTemplate="icons"  iconPos = "right">
            <button pButton class="p-button-outlined p-button-rounded" pTooltip="Clear filters" tooltipPosition="left"
                icon="pi pi-filter-slash" (click)="clearFilters()"></button>
            <button [isEditor]="salesModule()" class="p-button-rounded p-button-success mr-1 ml-1" pButton
                type="button" icon="pi pi-plus" routerLink="./editor/0">
            </button>
    </ng-template>
<p-panel>`

**Comment by Syizuril** [comment]
same for me, i don''t know what happens but icon position still in the left side before header,  even though already using iconPos="right", iconPos="center" or iconPos="left"

**Comment by jc040993** [comment]
Same here.. Any update on this issue?

**Comment by Syizuril** [comment]
I think this is the problem, in the latest version of Primeng which is updated via npm in the panel.css file there is no css for .p-panel-icons-center .p-panel-icons-start or .p-panel-icons-end, exactly as said in this issue https://github.com/primefaces/primeng/issues/11642#issue-1278535790

**Comment by Syizuril** [comment]
so maybe a temporary solution i found, just copy css .p-panel-icons-start .p-panel-icons-end .p-panel-icons-center on https://github.com/primefaces/primeng/blob/ 6aa888c9b7937185cad973177031922ee23d16a0/src/app/components/panel/panel.css#L21 to your css component and apply one of those css to p-panel class, to change icon to right apply class .p-panel-icons-end

**Comment by uebelmar** [comment]
this bug still exist in 15.2.0

**Comment by Cliff-Morrison** [comment]
I believe the issue is when you define header in the p-panel definition.  If you use ng-template pTemplate="header" to define the header, then the icons will position as expected.
