### ISSUE TITLE
dragdrop p-draggable-enter class not removed when dropped out of scope

### ISSUE THREAD

**Issue by nicholasfoden** [primefaces/primeng#11343]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => Search github for a similar issue or PR before submitting
```

**Current behavior**
When pDraggable is dropped onto an out of scope pDropppable, .p-draggable-enter is not removed. 
Any styling applied to droppable elements remains in place.

**Expected behavior**
When dropped on an out of scope pDroppable, .p-draggable-enter is removed.

**Minimal reproduction of the problem with instructions**
Dragging the div labelled DRAG1 onto DROP2 causes it to retain a red border from the .p-draggable-enter class

[Stackblitz Reproduction](https://primeng-dragdrop-bug-1.stackblitz.io)

**What is the motivation / use case for changing the behavior?**

N/A

**Please tell us about your environment:**

N/A

* **Angular version:** 5.X

N/A

* **PrimeNG version:** 5.X

13.3.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

* **Node (for AoT issues):** `node --version` =

**Comment by cetincakiroglu** [comment]
Hi,

I can't see the editable version of your StackBlitz example, it's only a live demo could you please share it as editable?

Regards

**Comment by yigitfindikli** [comment]
https://github.com/primefaces/primeng/pull/11344#issuecomment-1082786999
