### ISSUE TITLE
pTooltip [escape]=false is not rendering the html contents since primeng@13.3.1

### ISSUE THREAD

**Issue by jaggi510** [primefaces/primeng#11355]
After updating the primeng@13.3.1, the pTooltips are not rendering the html. Working fine with primeng@13.3.0
We are using escape = false like below.
[pTooltip]="buildTooltip(filter)" tooltipPosition="bottom" [escape]="false"
This is how it is looking with primeng@13.3.1
![image](https://user-images.githubusercontent.com/39197764/160630151-61dcbc0b-fa4f-41a1-a594-2de39a559cd5.png)

This is the output with primeng@13.3.0
![image](https://user-images.githubusercontent.com/39197764/160631283-1571b481-9887-4ccd-9c20-8f043b90d105.png)

here is the html text
<ul><li>SL, G (NPI 1851307615)</li><li>GUETS, D (NPI 1851307615)</li></ul>

**Comment by cetincakiroglu** [comment]
Hi,

Here is a working example of the escape prop.
https://stackblitz.com/edit/primeng-tooltip-demo-8afuib?file=src%2Fapp%2Fapp.component.html

Regards

**Comment by jaggi510** [comment]
Hi, 
It is still the issue. In the working example primeng 13.3.0 is used. 
If you update the version of primeng 13.3.1, then you should be able to replicate. See the screenshots.

![image](https://user-images.githubusercontent.com/39197764/160644156-4214de62-074d-4d80-bb8c-650eeca43ed6.png)

![image](https://user-images.githubusercontent.com/39197764/160644251-832d90bd-adce-42ab-9eec-dc09dbb8d017.png)

**Comment by jaggi510** [comment]
@cetincakiroglu 
update your working exaple to use primeng@13.3.1 to replicate the issue.

**Comment by yigitfindikli** [comment]
Duplicate of https://github.com/primefaces/primeng/issues/11348.

**Comment by johnho70** [comment]
I have same issue for Tooltip escape parameter not working after update primeng from v17 to v19.
