### ISSUE TITLE
Tree should export SharedModule

### ISSUE THREAD

**Issue by h3llrais3r** [primefaces/primeng#1135]
When using the demo for the tree, I can't get the template logic working.
Reference: http://www.primefaces.org/primeng/#/tree
```
<p-tree [value]="files">
    <template let-node pTemplate type="default">
        <input [(ngModel)]="node.label" type="text" style="width:100%">
    </template>
</p-tree>
```

The input fields are never rendered... It always renders just the labels. It's like the template is not taking into account.

![image](https://cloud.githubusercontent.com/assets/1945295/19716595/f1c24b48-9b5c-11e6-9e7d-142258a38d28.png)

I've debugged the code and it seems that the templates is not initialized after init, so the templateMap is not filled and no template is loaded (always returns null for getTemplateForNode().
Am I missing something?

```
ngAfterContentInit() {
        if(this.templates.length) {
            this.templateMap = {};
        }
        
        this.templates.forEach((item) => {
            this.templateMap[item.type] = item.template;
        });
    }
...
 getTemplateForNode(node: TreeNode): TemplateRef<any> {
        if(this.templateMap)
            return node.type ? this.templateMap[node.type] : this.templateMap['default'];
        else
            return null;
    }
```

Do I need to add the default template somewhere?

**Comment by h3llrais3r** [comment]
Ok... after a day of investigation why it's not working, I finally found the reason...
You'll also need to import the SharedModule to get the templating working. 
```
import { TreeModule, SharedModule } from 'primeng/primeng';
```

Please add this in the docs so everyone should now that this module is needed for the template loading.

**Comment by cagataycivici** [comment]
I see, tree should have exported SharedModule so you don't need to import it. I've made the change on our side so it should now work without importing SharedModule.

**Comment by h3llrais3r** [comment]
Ok thanks for the change.
Until RC1 I'll import the SharedModule myself.
