### ISSUE TITLE
wrong in style Password Component

### ISSUE THREAD

**Issue by rezaokhravi** [primefaces/primeng#11356]
hi 
bug in style Password Component , At the time of a click on Password Component, style will be correct .
if switch to PrimeNG version: <=12.2.0 style will be correct !!!
Please fix it .

![Screenshot (24)](https://user-images.githubusercontent.com/42868109/160749356-ba18e9d6-8e6d-4ed5-b580-6fa24ece24ed.png)

* **Angular version:12.0.0

* **PrimeNG version:>=12.2.1

**Comment by yigitfindikli** [comment]
The issue is not clear, please feel free to reopen with a stackblitz example.

**Comment by rezaokhravi** [comment]
> The issue is not clear, please feel free to reopen with a stackblitz example.

https://stackblitz.com/edit/primeng-sidebar-demo-if1s7u?file=src%2Fapp%2Fapp.component.ts

**Comment by Hamidrezae** [comment]
By adding the following piece of code, the problem is solved

 styleClass=" p-password p-component p-inputwrapper p-input-icon-right"
