### ISSUE TITLE
DataTable lazy loading

### ISSUE THREAD

**Issue by bogdanvaduva** [primefaces/primeng#1136]
I created a component based on DataTable.
DataTable has filters and pagination.
First when I load the data, everything is fine. Then I enter something in one filter column, at this point everything goes crazy because onFilterKeyup -> filter -> onLazyLoad (which loads the data) -> ngDoCheck (which also does a filter) -> filter and stays here. I solved the problem by adding a property called filtered and changing the following in datatable.ts

DataTable.prototype.onFilterKeyup = function (value, field, matchMode) {
var _this = this;
this.filtered = false;
if (this.filterTimeout) {
clearTimeout(this.filterTimeout);
}
this.filterTimeout = setTimeout(function () {
_this.filters[field] = { value: value, matchMode: matchMode };
_this.filter();
_this.filterTimeout = null;
_this.filtered = true;
}, this.filterDelay);
};

and

DataTable.prototype.filter = function () {
if (!this.filtered)
this.first = 0;
if (this.lazy) {
if (!this.filtered)
this.onLazyLoad.emit(this.createLazyLoadMetadata());
}
....

Now it seems to work fine. Could someone tell me if I did somenthing wrong in my component or there is an issue in datatable.ts?

Regards.

**Comment by mwaltersva** [comment]
I'm also experiencing this issue. It works fine in beta.16, but once you enter a filter term in 17+, it repeatedly calls the lazyLoad function.

**Comment by ElaAlex** [comment]
Same issue here. Using Angular 2.1 together with primeng beta 20. Lazy loading works but as soon as I add filter capability and enter a value into one (contains-) filter a constant reloading circle starts.

**Comment by bogdanvaduva** [comment]
Hi @mwaltersva, @ElaAlex if you make the changes within the datatable.ts it should work fine, but I would like to have these changes into the main branch.
Regards.

**Comment by cagataycivici** [comment]
Please do a PR and we'll review.

**Comment by bogdanvaduva** [comment]
Thanks.
Regards
