### ISSUE TITLE
Custom toasts not stacked #2

### ISSUE THREAD

**Issue by KYRY001** [primefaces/primeng#11366]
```
[ x] bug report => Search github for a similar issue or PR before submitting
```
https://stackblitz.com/edit/github-1metrx

**Current behavior**
I implemented one default p-toast and one custom p-toast template, when i call both of them there are not stacked.

**Expected behavior**
Stacked toasts.

**Minimal reproduction of the problem with instructions**
Click on 1 button, then click on 2nd one.
Toasts are overlapping

primeNG13

original issue: https://github.com/primefaces/primeng/issues/9562

Screenshot example attached

![image](https://user-images.githubusercontent.com/60639223/160995703-344131c1-14bf-4bb7-86d8-873d0bfbaf1d.png)

**Comment by cetincakiroglu** [comment]
Hi,

Here is the refactored and working version of your example
https://stackblitz.com/edit/github-1metrx-ma9pkg?file=src%2Fapp%2Fapp.component.html

Regards.

**Comment by OliverDH** [comment]
Hi, I think here the problem is to use different keys for the toast.
Sample:
https://github-1metrx-yhbjas.stackblitz.io
