### ISSUE TITLE
Multiselect & Dropdown : widths growing automatically

### ISSUE THREAD

**Issue by creed-maxeta** [primefaces/primeng#11365]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-csd5h4?file=src/app/app.component.html

**Current behavior**
The multiselect and dropdown components grow automatically to fit either their selected option or longest option within the data source.

**Expected behavior**
The component width should not change based on the selected value. The options display panel width should be restricted in width and or scrollable rather than growing to fit the longest option within the data source.

**Minimal reproduction of the problem with instructions**
*STEPS TO REPRODUCE*
- Open stackblitz
- Select a different option from the first drop and observe the change in size
- Select one or more options from the multiselect and observe the size change
- Note the dropdowns in both are sized to fit the largest option rather than showings (...) or a scrollbar

**Please tell us about your environment:**

* **Angular version:** 12.2.6

* **PrimeNG version:** 12.2.1

* **Browser:** [all]
 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =   16.14.0

**Comment by cetincakiroglu** [comment]
Hi,

This is a natural behaviour, here is a refactored and working example of your code https://stackblitz.com/edit/github-csd5h4-m7o5n4?file=package.json

Regards
