### ISSUE TITLE
Primeng Tree structure does not working properly using VirtualScroll and Collapse All/Expand All methods

### ISSUE THREAD

**Issue by NimetKrgz** [primefaces/primeng#11369]
https://stackblitz.com/edit/primeng-treescroll-demo-9hwijc?file=src%2Fapp%2Fapp.component.html

When virtualScroll is true I got the image below as result;
![image](https://user-images.githubusercontent.com/56321613/161052077-7309b061-349b-4467-b4ff-8eb56ac7b28f.png)

When VirtualScroll is removed, the result in the image below is obtained;
![image](https://user-images.githubusercontent.com/56321613/161052153-bb43dac7-366c-4649-bdb1-a7850ca1dbf5.png)

https://stackblitz.com/edit/primeng-tree-demo-zrycor?file=src%2Fapp%2Fapp.component.html

When virtualScroll is true I got the image below as result;
![image](https://user-images.githubusercontent.com/56321613/161051398-a2b842dd-acf7-4a5e-b01a-f4a81d4cbf58.png)

When VirtualScroll is removed, the result in the image below is obtained;
![image](https://user-images.githubusercontent.com/56321613/161051521-b8977a25-6e29-4d39-8269-405e2c9c505a.png)

**Comment by mertsincan** [comment]
Hi,

Fixed for PrimeNG 14. We changed our virtualScroll implementation. We designed a new scroller API instead of Angular cdk and used it in all components.
https://github.com/primefaces/primeng/issues/11656
https://github.com/primefaces/primeng/issues/11662

Best Regards,

**Comment by mconner** [comment]
@mertsincan , I don't think this is working properly, With 13, 14, or 15.  When I add expand and collapse to the virtual scroll for each, and click expand, I get something like:
![image](https://user-images.githubusercontent.com/540402/232157153-3ee5559e-db2f-4df5-ae73-85d04f4120cb.png)

That is, marks the node as expanded, but does not add the rows for the children.

primeng 14 demo: https://stackblitz.com/edit/primeng-treescroll-demo-hpue31?file=src/app/app.component.ts

primeng 15:demo: https://stackblitz.com/edit/angular-mfnusu?file=.vscode/settings.json
