### ISSUE TITLE
Primeng p-calendar DisabledDate is selectable when Timepicker is visible and selects a time.

### ISSUE THREAD

**Issue by ramanacr** [primefaces/primeng#11377]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Plunkr Case (Bug Reports)**
[Stackblitz code](https://stackblitz.com/edit/primeng-calendar-demo-nccrpd)

**Current behavior**
Disabled dates are getting selected when showTime is set to true  and changing the time

**Expected behavior**
Disabled dates should also disable the time part (non-selectable)

**Minimal reproduction of the problem with instructions**

`<p-calendar [(ngModel)]="date7" [disabledDates]="invalidDates" [showTime]="true" inputId="time"></p-calendar>`

When [showTime]="true" and when Today date is disabled, then with the modification of time we could able to select the disabled date.
https://stackblitz.com/edit/primeng-calendar-demo-nccrpd

**Please tell us about your environment:**
Windows 11, VS Code, npm, IIS

* **Angular version:** 12.X
Not checked

* **PrimeNG version:** 12.X
Not checked

* **Browser:** [Chrome XX]
Chrome 99
 
* **Language:** [TypeScript X.X]
TypeScript 4.2

* **Node (for AoT issues):** `node --version` =   14.18.3

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
