### ISSUE TITLE
pTable row selection changes as table data is modified

### ISSUE THREAD

**Issue by mwraitt** [primefaces/primeng#11370]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/angular-ivy-7zpabi

**Current behavior**
After selecting a row, modifying underlying data will cause additional rows to appear selected.

**Expected behavior**
Additional rows should not change when modifying table data.

**Minimal reproduction of the problem with instructions**
Stackblitz selects first row on load and starts pushing data. This will show how the second row is selected as data is pushed. Selecting a different row or rows will show this behavior again.

**What is the motivation / use case for changing the behavior?**
I would like to be able to update the table data while rows are selected.

**Please tell us about your environment:**
Win11, VSCode, NPM, IIS/Node

* **Angular version:** 13.2.0

* **PrimeNG version:** 13.3.2

* **Browser:** Chrome XX | Firefox XX
Chrome Version 99.0.4844.82
 
* **Language:** Typescript 4.5

* **Node (for AoT issues):** `node --version` =   v16.13.1

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by mwraitt** [comment]
Still reproducible with latest angular and primeng https://angular-ivy-u46vng.stackblitz.io

**Comment by mwraitt** [comment]
Would you like me to open a new issue and reference this one? I cannot reopen this issue.
