### ISSUE TITLE
Column widths are not recalculated correctly on drag&drop for Scrollable tables with Columns Resize enabled

### ISSUE THREAD

**Issue by emamedov2** [primefaces/primeng#11372]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-x2kqfd

**Current behavior**
If user resizes column and drag/drops column to change the order then columns will not exchange the widths. The width of new position will be used for dropped column.

Reason of the issue: the table uses next styles for resize of flex tables that are not recalculated on column reordering

```
#pr_id_1 .p-datatable-thead > tr > th:nth-child(1),
#pr_id_1 .p-datatable-tbody > tr > td:nth-child(1),
#pr_id_1 .p-datatable-tfoot > tr > td:nth-child(1) {
    flex: 1 1 155px !important;
}
```

**Expected behavior**
Column widths are moved together with columns

**Minimal reproduction of the problem with instructions**
STEPS TO REPRODUCE:
- Open https://stackblitz.com/edit/github-x2kqfd
- Expand third column, make it quite big
- Drag and drop third column to first position
- First and Second columns will be shifted to the right (expected) but widths are unexpected (1st col width = old 1st col width, 2nd col width = old 2nd col width and etc). So now old 2nd column will be the largest one

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
* **Angular version:** 13.0.3
* **PrimeNG version:** 13.3.2
* **Browser:** [all]
* **Language:** [all]
* **Node (for AoT issues):** `node --version` =

**Comment by capc0** [comment]
@emamedov2 did you figure out any workaround for this issue?

**Comment by jiteshvdb** [comment]
@emamedov2  @capc0 anyone found any fix ! Any help is much appreciated !

**Comment by jiteshvdb** [comment]
@yigitfindikli

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by leliaflorina** [comment]
The issue still persists in 15.4.1. Do you have a solution for this?
