### ISSUE TITLE
Custom MatchMode in filters / Loose Translation interface

### ISSUE THREAD

**Issue by Xriuk** [primefaces/primeng#11373]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Currently it's technically possible to add custom Filters to the config
   ```
constructor(private config: PrimeNGConfig) {}

 ngOnInit() {
      this.config.filterMatchModeOptions = {
          text: [
              FilterMatchMode.STARTS_WITH,
              FilterMatchMode.CONTAINS,
              FilterMatchMode.NOT_CONTAINS,
              FilterMatchMode.ENDS_WITH,
              FilterMatchMode.EQUALS,
              FilterMatchMode.NOT_EQUALS
          ],
          numeric: [
              FilterMatchMode.EQUALS,
              FilterMatchMode.NOT_EQUALS,
              FilterMatchMode.LESS_THAN,
              FilterMatchMode.LESS_THAN_OR_EQUAL_TO,
              FilterMatchMode.GREATER_THAN,
              FilterMatchMode.GREATER_THAN_OR_EQUAL_TO
          ],
          date: [
              FilterMatchMode.DATE_IS,
              FilterMatchMode.DATE_IS_NOT,
              FilterMatchMode.DATE_BEFORE,
              FilterMatchMode.DATE_AFTER,

              'between' <----------------------------
          ]
      }
  }
```

But it's not possible to add its translation/display string, because the Translation interface is [strongly typed](https://github.com/primefaces/primeng/blob/master/src/app/components/api/translation.ts) and [does not allow adding new keys to it](https://github.com/primefaces/primeng/blob/master/src/app/components/api/primengconfig.ts#L99), and there is no other way of adding the label of the filter.

**Expected behavior**
Being able to add custom keys to the translation strings to translate custom filters (and other stuff), maybe you could add an `addTranslation()` method.

**What is the motivation / use case for changing the behavior?**
Adding custom filters easily

* **PrimeNG version:** 13.2.1

* **Browser:** all
 
* **Language:** all

**Comment by Xriuk** [comment]
Also adding custom filter types would be helpful, like this:
```
constructor(private config: PrimeNGConfig) {}

ngOnInit() {
   this.config.filterMatchModeOptions = {
       text: [
           FilterMatchMode.STARTS_WITH,
           FilterMatchMode.CONTAINS,
           FilterMatchMode.NOT_CONTAINS,
           FilterMatchMode.ENDS_WITH,
           FilterMatchMode.EQUALS,
           FilterMatchMode.NOT_EQUALS
       ],
       numeric: [
           FilterMatchMode.EQUALS,
           FilterMatchMode.NOT_EQUALS,
           FilterMatchMode.LESS_THAN,
           FilterMatchMode.LESS_THAN_OR_EQUAL_TO,
           FilterMatchMode.GREATER_THAN,
           FilterMatchMode.GREATER_THAN_OR_EQUAL_TO
       ],
       date: [
           FilterMatchMode.DATE_IS,
           FilterMatchMode.DATE_IS_NOT,
           FilterMatchMode.DATE_BEFORE,
           FilterMatchMode.DATE_AFTER,

           'between'
       ],
       'select': [ <----------------------------
           'in',
           'notIn'
       ]
   }
}
```

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
