### ISSUE TITLE
InputMask - Options missing, cannot upgrade from beta.16 to latest

### ISSUE THREAD

**Issue by leonhardt** [primefaces/primeng#1137]
We have a big problem.
We are using the primeng beta.16 on a big project and we are not able to update because of that.

Options that are missing:
[options]="{groupSeparator:'',digits:2,prefix:'R$ ',digitsOptional:false,autoGroup:true}"

any suggestion?

Thank's

**Comment by cagataycivici** [comment]
Please see;

http://forum.primefaces.org/viewtopic.php?f=35&t=47786
