### ISSUE TITLE
Schedule is very slow in IE11

### ISSUE THREAD

**Issue by CHOUAIAR** [primefaces/primeng#1138]
Hello every body,
When I test Schedule on IE 11 I must wait more than 10s to get my event displayed while it completely normal in Firefox and Chrome, Anybody has any idea please.
Thanks in advance.

**Comment by cagataycivici** [comment]
Do you experience the same at live showcase?

**Comment by CHOUAIAR** [comment]
Actually no the live showcase is working good for me, I don't if you use something like awesome-typescript-loader or Ahead of Time (AoT) compilation which can accelerate the compiling and the processing of the javascript code, specially that this task which take the majority of time about 20s in IE.

**Comment by cagataycivici** [comment]
Closing as we can't replicate, please post this to forum with your code, hopefully it will be resolved.
