### ISSUE TITLE
p-AutoCompleted

### ISSUE THREAD

**Issue by jsalaria** [primefaces/primeng#11386]
We are using p-autocompleted version 13.1.1

Issue - Suggestions are shown until we move the mouse
sample code
 <p-autoComplete formControlName="customer" [showEmptyMessage]="true" emptyMessage="No customer found" [suggestions]="filteredCustomers" field="name" (completeMethod)="filterCustomer($event)" [forceSelection]="true" pTooltip="Optional - Type a few letters of the customer" tooltipPosition="top"></p-autoComplete>

Please note - I am not able to recreate this issue using stackblitz template .

**Comment by cetincakiroglu** [comment]
Hi,

The issue is not clear and I'm unable to replicate it with the latest PrimeNG, if the issue persists please create a new ticket with a test case reproducing the issue e.g. Stackblitz/Codesandbox/etc. or a GitHub repo and it will be reviewed by our team once again.

Regards.
