### ISSUE TITLE
p-multiselect tabbing through items closes the multiselect

### ISSUE THREAD

**Issue by Quacck** [primefaces/primeng#11387]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
The multiselect closes if you use tab to cycle through the multiselect's items.

**Expected behavior**
By using tab. I want to be able to select each item.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/primeng-multiselect-demo-prdr9i?file=src%2Fapp%2Fapp.component.html

- open the multiselect
- use TAB to select the second item. 
- the multiselect closes.

**What is the motivation / use case for changing the behavior?**
For accessibilty, we need to be able to use the multiselect using only keyboard inputs.

**Please tell us about your environment:**

* **Angular version:** 13.0.4

* **PrimeNG version:** 13.3.2

* **Browser:** 
Chrome 100.0.4896.60 |
Firefox 98.0.2
 
* **Language:** TS

**Comment by volvachev** [comment]
Hi, I saw a similar problem #11088, and the original implementation was done as you described (move to the next item if it exists, otherwise just close the multiselect), but before the release the logic changed to just close the multiselect.
To be honest, I'm not sure why it happened.
