### ISSUE TITLE
p-autoComplete formControlName= doesn't work with dynamic forms when the options are objects rather than strings

### ISSUE THREAD

**Issue by lasimon** [primefaces/primeng#11381]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/angular-ivy-hd8dzu

**Current behavior**
When the form specified in <p-autoComplete formControlName= is a FormGroup rather than a simple formControl each character typed into the autoComplete generates an "NG01002: Must supply a value for form control with name: ..." error in the console and the matching option is never selected

**Expected behavior**
The autoComplete should not attempt to send the search string to populate the FormGroup.  FormGroup.setValue() which attempts to populate the form requires an exact match between the structure of the object to populate the form with and the structure of the formGroup.

**Minimal reproduction of the problem with instructions**
See attached StackBlitz.

**What is the motivation / use case for changing the behavior?**
p-autoComplete does not implement the forms interface correctly for other than simple formControls

**Please tell us about your environment:**
mac, IntelliJ

* **Angular version:** 13.2

* **PrimeNG version:** 13.3

* **Browser:** Only tried for Chrome
 
* **Language:** TypeScript 4.0.2 and 4.4

* **Node (for AoT issues):** `node --version` =   N/A

**Comment by lasimon** [comment]
I should have used formGroupName= rather than formControlName=.

**Comment by lasimon** [comment]
Actually that doesn't work either.

**Comment by volvachev** [comment]
Hi, I have looked at your example.
I think the problem is in your code.
`ControlValueAccessor` works with Control\ControlName\NgModel, not `Group`.
To solve your problem, it is enough to use `formGroupName` for any `parent element`:

```html
<div[formGroup]="fg">
  <div formGroupName="a">
    <p-autoComplete formControlName="a1" completeMethod="options">
    </p-autocomplete>
  </div>
</div>
```

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
