### ISSUE TITLE
P-Tree, second parent node not updated

### ISSUE THREAD

**Issue by Dashti81** [primefaces/primeng#11385]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-treeselection-demo-lhaa7t

**Current behavior**
The parent selection is not updated in case of duplicated nodes

**Expected behavior**
The second parent node selection should also be updated

**Minimal reproduction of the problem with instructions**
Open the stackblitz project,
Click on 'Work' node and you see that the second 'Work' node is also selected, however the second parent node 'Documents v2' is not selected or partial selected. 

** How should it works | "work around": **
Go to app.component.ts and remove 'return' on line 24, now start select child nodes and you see the parent nodes updated in a correct way.

Thanks
Dashti

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by Dashti81** [comment]
Hi,

Thanks for looking at this issue, however it's still not working, follow the steps in the description and you will see the issue. 

Dashti

**Comment by mehmetcetin01140** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.
