### ISSUE TITLE
Table columns do not fit table width after resize in expand mode followed by switching to fit mode

### ISSUE THREAD

**Issue by mconner** [primefaces/primeng#11388]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)** 

https://stackblitz.com/edit/github-cnsbpe-fvnp98?file=src/app/app.module.ts

**Current behavior**

Given a table that can toggle columnResizeMode: between "fit" and "expand", starting in "fit" mode, a resize of a column fits the columns into the size of the table, as expected.  However, If you then switch to "expand" mode and resize a column, then switch back to fit mode, the columns do not fit the size of the table.  They fit the size of the sum of the columns on leaving expand.  There's no way to get back to the behavior before you resized in expand mode.   Even if you manually resize (in "expand" mode) to fit the table width, it will not fit the table on resizing the table (e.g.: by resizing the window containing the table).

Possibly Related (?):  when you resize in "expand" mode, on mouse-up the column is not places where the cursor is.  This is more apparent on inner column dividers, as opposed to the last column end resize.  By contrast, In "fit" mode, the column is correctly resized (a few pixels right of the cursor).  Maybe this is a separate bug.

**Expected behavior**
On switching from columnResizeMode = "expand" to "fit", the columns should be adjusted to fit the table width, as they would have if   in resize mode, distributing the remaining space proportionally, or perhaps growing or shrinking the last column(s) as needed.  Granted this could get complicated with frozen columns or an adjustment size that spans multiple columns.

**Minimal reproduction of the problem with instructions**

Steps to reproduce are in the demo, but: 

1. Click the "Fitting" button to switch to expand mode.
2. Shrink one of the columns.
3. Click again to switch back to fit mode.
4. You can that see the gap remains, and subsequent column width adjustments fit to whatever the sum of column widths was at the point you went back to fit mode, and not to the size of the table, as it did before you resized in expand mode. There's no way to get back to a fit-to-table-width mode.

**What is the motivation / use case for changing the behavior?**

A user will typically wish to have a table columns size to fit available space, but may want to scroll horizontally, depending on the data and number of columns selected.  It should be possible to try "expand" mode and get back to the behavior of the "fit" mode.

**Please tell us about your environment:**

Windows 10, IntelliJ, npm, JBoss

* **Angular version:** 13.X

* **PrimeNG version:** 13.3.2

* **Browser:** [ Chrome XX | Edge]

 
* **Language:** TypeScript 4.5.5

* **Node (for AoT issues):** `node --version` =   v16.14.0

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
