### ISSUE TITLE
Overlapping submenu in Splitbutton on the righthand side of the screen

### ISSUE THREAD

**Issue by bernstar** [primefaces/primeng#11394]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/github-1icnwj?file=src%2Fapp%2Fapp.component.ts

**Current behavior**
If the splitbutton is on the righthand side of the screen and a label in a submenu is too long, the submenu is overlapping the parent menu, so you can't navigate back, once the child-menu is open.

**Expected behavior**
Submenu stays either in fixed width, so that the long label may be broken into more lines, or it is moved further to the left, so that the parent menu remains visible.  

**Minimal reproduction of the problem with instructions**
See stackblitz link above, create a Splitbutton displayed on the righthand side of the screen (so submenus need to open to the left) and provide a label for a submenu, which is very long. 

* **Angular version:** 13.3.2

* **PrimeNG version:** 13.3.2

**Comment by cetincakiroglu** [comment]
Hi,

This is a natural behavior of the menu inside the splitButton, it will open wherever the space is available. Overlapping happens naturally, only if there is no space to render menu content in the viewport.

Regards.

**Comment by cetincakiroglu** [comment]
Hi,

Here is an example that will help to overcome this issue with minimal effort, and shrink the screen.

https://stackblitz.com/edit/primeng-splitbutton-demo-k4ipfj

Regards.
