### ISSUE TITLE
TieredMenu AppendTo body not working

### ISSUE THREAD

**Issue by leamcg** [primefaces/primeng#11403]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-tieredmenu-demo-wd3se1?file=src/app/app.component.html

**Current behavior**
When using the default tieredMenu (= not the popup version), adding appendTo="body" to the TieredMenu element doesn't do anything, the submenu are still attached to the tieredMenu element. Therefore, it's not possible to add scrolling to a tieredMenu as the submenu are not visible after that.

**Expected behavior**
appendTo="body" should work on the default tieredMenu and attach the submenus to the body.
Things blocked: Adding overflow to the container hides the submenus.

**Minimal reproduction of the problem with instructions**
Simply add appendTo="body" (or anything else): the tieredsubmenus will still be appended to the tieredmenu

* **Angular version:** 
13.0.1

* **PrimeNG version:** 
13.1.0

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
