### ISSUE TITLE
wrong in style Password Component

### ISSUE THREAD

**Issue by rezaokhravi** [primefaces/primeng#11408]
#11356 
https://stackblitz.com/edit/primeng-sidebar-demo-if1s7u?file=src%2Fapp%2Fapp.component.ts

**Comment by volvachev** [comment]
Hi, I  created a fix and an explanation of why the problem had been occurred.

**Comment by cetincakiroglu** [comment]
Hi,

Invalid StackBlitz url, link is broken. Cannot replicate and closing the issue. Feel free to re-open with a VALID StackBlitz example.
