### ISSUE TITLE
Calendar Input Box Display

### ISSUE THREAD

**Issue by pdeason** [primefaces/primeng#1140]
Hi! Your components are fantastic so thanks for your work on them. I have noticed a couple of issues with the Calendar component surrounding the value shown in the input text box:

1) If the 'showTime' attribute is on so the input box/calendar displays the time, and a default Date/time value is provided for the model, the calendar input box only displays the date but not the time. When you open the calendar panel, the correct time is shown so it's just the default input box display.

2) If I change the model Date variable e.g. setting it to null, the input does not refresh and keeps the old value.

Thank you!

**Comment by kcsahoo** [comment]
I am also agreeing with these observations

**Comment by cagataycivici** [comment]
Thank you for the feedback, we'll review for upcoming RC1.

**Comment by raaaste** [comment]
Seems to be related to issue #1122.

**Comment by pauloegk** [comment]
Hello, I had the same problem, I managed to solve it this way.

import { Calendar } from 'primeng/primeng';
@ViewChild(Calendar) calendar: Calendar;

this.calendar.updateInputfield();
