### ISSUE TITLE
Reorder do not refresh in table with flex

### ISSUE THREAD

**Issue by regis1512** [primefaces/primeng#11400]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-xlez9c-4qhw5p
https://github-xlez9c-4qhw5p.stackblitz.io

**Current behavior**
I use a table with scrollHeight="flex".
But when i reorder the rows the table to not refresh.

**Expected behavior**
I expect that the order of lines in the table change like in the [example](https://www.primefaces.org/primeng/#/table/reorder) show with a table without flex.

**Minimal reproduction of the problem with instructions**
1. At the beginning the values in the '#' column correspond to values in 'Index' column and at the top of the page "First vin" and "Second vin" correspond to the first line and the second line
2. I take the first line to move it between the tenth and the eleventh line
3. Now for the first and the second lines the values in the '#' column do not correspond with the values in the 'Index' column and at the top of the page 'First vin' and 'Second vin' do not correspond to the order of the line in the table
4. For the first line, the '#' is still "1 / 30" and the 'Index' is now "10"
5. For the second line, the '#' is still "2 / 30" and the 'Index' is now "1"
6. For the third line, the '#' is still "3 / 30" and the 'Index' is now "2"
7. At the top of the page, the "First vin" is now the vin of the second line of the table and the "Second vin" is now the vin of the third line of the table

**What is the motivation / use case for changing the behavior?**
The motivation is to have a normal behavior.

**Please tell us about your environment:**
All the Operating system, All the IDE, All the HTTP server

* **Angular version:** 
Angular 13

* **PrimeNG version:**
PrimeNG 13

* **Browser:** 
All browsers i tested : Chrome, Firefox, Brave, Edge

**Comment by regis1512** [comment]
In case that it could help, when i modify the code like that
```typescript
  changeOrder($event: any) {
    this.cars = [...this.cars];
    let newOrder = 1;
    for (let value of this.cars) {
      value.index = newOrder++;
    }
  }
```

I suppose that the table is not able to detect the changes although the changes is done by the table.

Regards.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
