### ISSUE TITLE
SpeedDial: MenuItem.styleClass & MenuItem.badge not working

### ISSUE THREAD

**Issue by martin31821** [primefaces/primeng#11404]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://primeng-speeddial-demo-qmrysq.stackblitz.io

**Current behavior**
- Badge is not rendered, styleClass property is not honored

**Expected behavior**
- Badge should be rendered 
- StyleClass of the menuItem should be applied to the <a> element.

**Minimal reproduction of the problem with instructions**

- Set the `badge` or `styleClass` property to the SpeedDial, see that it is not being rendered.

**What is the motivation / use case for changing the behavior?**

I want to realize something like toggle buttons in the menu item, in which case it would be good to allow a checkmark as a badge or changing the background color.

**Please tell us about your environment:**

* **Angular version:**

```
Angular CLI: 13.2.5
Node: 17.9.0 (Unsupported)
Package Manager: npm 8.5.5
OS: linux x64

Angular: 13.2.4
... animations, cdk, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.5
@angular-devkit/build-angular   13.2.5
@angular-devkit/core            13.2.5
@angular-devkit/schematics      13.2.5
@angular/cli                    13.2.5
@schematics/angular             13.2.5
rxjs                            7.5.4
typescript                      4.5.5
```

* **PrimeNG version:** ^13.2.0

* **Browser:** all

 
* **Language:** all

* **Node (for AoT issues):** `node --version` =  17.9.0

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
