### ISSUE TITLE
Multi Select: Clear Button

### ISSUE THREAD

**Issue by denny99** [primefaces/primeng#11406]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

If we have a large multi select with a couple of options, like the one in the show case:

<img width="288" alt="image" src="https://user-images.githubusercontent.com/1826849/162770129-153e3e8c-bfef-4457-acab-93bb743582e6.png">

and select some data. Let's say 50 out of these 1000. 

To unselect everything i have to click all 50 items again. So there is no easy way to reset the data in the input.

**What is the motivation / use case for changing the behavior?**

A clear button would be nice, like the one in the dropdown component.

<img width="234" alt="image" src="https://user-images.githubusercontent.com/1826849/162770667-53900166-7372-418b-9eef-e1951c04ed96.png">

* **Angular version:** 13.X

* **PrimeNG version:** 13.X

* **Browser:** all

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by munkeywolf00** [comment]
@denny99 Hi. I'm wondering if you have found how to do this?

**Comment by denny99** [comment]
They just implemented a showClear Input

https://primeng.org/multiselect#api.multiselect.props.showClear

**Comment by munkeywolf00** [comment]
> They just implemented a showClear Input
> 
> https://primeng.org/multiselect#api.multiselect.props.showClear

Thank you! It seems it is not yet available in PrimeVue though. However, I appreciate the response!
