### ISSUE TITLE
Sizing of p-inputSwitch is not supported in new version

### ISSUE THREAD

**Issue by kishor-p** [primefaces/primeng#11407]
```
[x] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
In older version of PirimeNG (`6.x.x`) using following code could reduce Input-Switch button size.
```
.p-inputswitch { font-size: 7px; }
```
It does not work any more in version: 12.x.x

**Current behavior**
Following CSS has no effect
```
.p-inputswitch { font-size: 7px; }
```

**Expected behavior**
Using below CSS should reduce Input-Switch button size.
```
.p-inputswitch { font-size: 7px; }
```

One solution I tried was:

1. Even if I change size in .p-inputswitch-slider it the white dot looks super weird as below:

![image](https://user-images.githubusercontent.com/14179249/146450422-7c769747-bcf0-423e-852b-89df4297e6a7.png)

2. Also there are lot of things could go wrong with transition as well

![image](https://user-images.githubusercontent.com/14179249/146450502-ab374174-2dda-4577-8f46-4c210ce4f4e5.png)

3. Also I have tried this solution? It looks like a Target:
`.p-inputswitch-slider{ width:4rem; height:4rem; }`

![image](https://user-images.githubusercontent.com/14179249/146450676-8a056da3-c807-4c35-97ae-3d0a49937507.png)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
