### ISSUE TITLE
[Primeng : Table] Rowspan attribute is not working as expected when used along with scrollable & frozen columns.

### ISSUE THREAD

**Issue by Aryan001** [primefaces/primeng#11412]
I'm using rowspan for a column and it seems to be working as expected with the below code.
[https://stackblitz.com/edit/primeng-tablecolgroup-demo?file=src%2Fapp%2Fapp.component.ts](url)

When I tried to freeze the rowspan column, I added the scrollable attribute to the table and also the pFrozenColumn, its not working as expected and also unable to set a custom width for that column with rowspan
[https://stackblitz.com/edit/primeng-table-uxoaha?file=src%2Fapp%2Fapp.component.html](url)

**Comment by Aryan001** [comment]
[https://stackblitz.com/edit/primeng-table-uxoaha?file=src%2Fapp%2Fapp.component.html](url)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
