### ISSUE TITLE
Property 'visibleOptions' does not exist on type 'MultiSelect

### ISSUE THREAD

**Issue by vinacharya05** [primefaces/primeng#11419]
I was using PrimeNG version 9.1.3 and Angular version 9, there I had written a piece of code which was supporting the access of "visibleOptions" property on multiSelect. 

@ViewChild('recipeSelectComponent') recipeSelectComponent: MultiSelect;

**this.recipeSelectComponent.visibleOptions** ( I was able to access the visibleOptions like this) 

But now I migrated to Angular version 13, PrimeNG v13.3.2 and Node.js version 16.14.2. After the Migration the above line of code is throwing "Property 'visibleOptions' does not exist on type 'MultiSelect'" this Issue.

Can you please let me know what will be the possible replacement for this visibleOptions property in PrimeNG version 13.3.2 ?.

**Comment by cetincakiroglu** [comment]
Hi,

visibleOptions property was not a public property that you can use like other input props of the component. You're having this problem because the property you're trying to use has probably been renamed or deleted.

Regards
