### ISSUE TITLE
Can DataTable and PickList (Data Components) be used in model driven forms?

### ISSUE THREAD

**Issue by ShiraazMoollatjie** [primefaces/primeng#1142]
I have a form that makes use of a PickList and a DataTable. 

For the picklist, the user selects a bunch of artifacts to process.
For the datatable, the user adds a bunch of email address to this datatable.

I am trying to use these 2 components with Angular 2 Forms (Model Driven Forms), but I cannot seem to bind the ngModel or a formcontrol to these two components?

What I want to know is whether it is possible to do this with the current primeNG? At the moment I am just skipping the validation on these components.

**Comment by cagataycivici** [comment]
They are not input components, they deal with data so they don't have ngModel. Marking as closed as this is a question. We'll reconsider if we get more requests.
