### ISSUE TITLE
Suggestion - for dropdown menu

### ISSUE THREAD

**Issue by ahmedabdelhafez** [primefaces/primeng#11424]
hello dears,
for dropdown component i want to suggest to allow user to add the not found search value
such as:
if we have a list that have 3 values [1,2,3]
and user search for value 4 or 5  we want to show button or a way to allow user to click to open a modal to add this value from another screen

thanks

**Comment by cetincakiroglu** [comment]
Hi,

There is no need for this feature. You can achieve this by using template options of the dropdown component. Here is a Stackblitz example for you https://stackblitz.com/edit/primeng-dropdown-demo-eff2mr?file=src%2Fapp%2Fapp.component.html

Regards
