### ISSUE TITLE
when I select a year with a range, only the start year is highlighted.

### ISSUE THREAD

**Issue by kafelix496** [primefaces/primeng#11425]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
when I select a year with a range, only the start year is highlighted.

**Expected behavior**
when I select a year with a range, start year, end year and years between start year and end year should be highlighted

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
because date range is highlighted start date, end date and dates between start and end

**Please tell us about your environment:**
MacOS Monterey v12.3.1, Neovim v0.6.0.1, npm

* **Angular version:** 13.2.3

* **PrimeNG version:** 13.3.0

* **Browser:** all
 
* **Language:** all

* **Node (for AoT issues):** `node --version` =   v16.14.2

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
