### ISSUE TITLE
p-dropdown with SelectItems with undefined value selects the SelectItem, not the value

### ISSUE THREAD

**Issue by mconner** [primefaces/primeng#11420]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-snquat?file=src%2Fapp%2Fapp.component.html

**Current behavior**

Given a dropdown:
`  <p-dropdown [options]="selectItems" [(ngModel)]="selectedCity"></p-dropdown>
`

 where selectItems is:
```
    this.selectItems = [
      { label: 'None', value: undefined },
      { label: 'New York', value: 'NY' },
     ...
   ] 

The value set on selectedCity is the SelectItem when None is chosen from the dropdown.

Workaround:  This appears to work properly if optionValue="value" is explicitly defined.  But as is, it breaks any pre-existing code expecting the value to be undefined.


```
**Expected behavior**

Per the documentation, the default value for optionValue is the value attribute. If not defined for a SelectItem, the model should be set to a value of undefined.

**Minimal reproduction of the problem with instructions**

See the stackblitz

**What is the motivation / use case for changing the behavior?**

Existing code uses the idiom of an "unset" value representing no selected value in the dropdown.  This used to work properly.

**Please tell us about your environment:**

Windows 10, IntelliJ wildfly

* **Angular version:** 13.x

* **PrimeNG version:** 13.3.2

* **Browser:** Edge, Chrome

 
* **Language:** TypeScript

* **Node (for AoT issues):** `node --version` =   v16.14.0

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by TimUnderhay** [comment]
@mertsincan this issue is still valid with 16.3.x.
