### ISSUE TITLE
Regression in 12.1.0 on scrollable p-table with colspan/rowspan (part 3)

### ISSUE THREAD

**Issue by marob** [primefaces/primeng#11422]
https://github.com/primefaces/primeng/issues/10541 and https://github.com/primefaces/primeng/issues/10776 have been closed for no reason, so I'm reopening (again) an issue.
It's beginning to be annoying and doesn't seem to be an exception (https://github.com/primefaces/primeng/issues/11207 has also been closed with no reason).
Please do **not** close this issue before validating it's **really** been fixed.

**Comment by mcrtricolor** [comment]
This is still an issue in primeng 14, if you use virtualScroll colspan doesn't work.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by marob** [comment]
This is (finally) fixed in 14.2.1
