### ISSUE TITLE
p-fileupload opens Windows Explorer twice, only uploads on second open

### ISSUE THREAD

**Issue by taylor-burns** [primefaces/primeng#11439]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewed in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**

When clicking on the "+ Choose" button for an image upload;
1. windows explorer opens
2. select file
3. upload event handler not hit
4. windows explorer opens
5. select file
6. upload event handler hit

Note: This only happens when clicking on the  "+ Choose" button. If I click within the area below the button where the uploaded files are shown it works as expected.

**Expected behavior**

When clicking on the "+ Choose" button for an image upload;
1. windows explorer opens
2. select file
6. upload event handler hit

**Minimal reproduction of the problem with instructions**

See current behavior.

**What is the motivation / use case for changing the behavior?**

Unnecessary repeated steps when uploading.

**Please tell us about your environment:**

* **Angular version:** 5.X

12.2.7

* **PrimeNG version:** 5.X

11.4.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 all
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

* **Node (for AoT issues):** `node --version` =

**Comment by cetincakiroglu** [comment]
Hi,

We couldn't replicate the issue with the latest PrimeNG release, if the issue still exists with the latest PrimeNG version, please provide a StackBlitz example by using [PrimeNG Issue Template ](https://stackblitz.com/github/primefaces/primeng-issue-template) and re-open the issue.

Regards

**Comment by jkbngl** [comment]
Hi @taylor-burns I am currently facing the same issue, did you have any success solving it?
