### ISSUE TITLE
Error with initial empty array tabs in TabView

### ISSUE THREAD

**Issue by PashaTurok** [primefaces/primeng#11430]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
If we create tabView with initial empty array of tabs, then when we later push a new tab programmatically we get 

```
ERROR TypeError: el is null
    getWidth primeng-dom.mjs:303
    updateInkBar primeng-tabview.mjs:280
    set header primeng-tabview.mjs:62
```

**Expected behavior**

**Minimal reproduction of the problem with instructions**

HTML:

    <p-tabView [(activeIndex)]="activeIndex2" [scrollable]="true">
        <p-tabPanel *ngFor="let tab of tabs;" [header]="tab.title" [closable]="true">
        </p-tabPanel>
    </p-tabView>

TS:

```
class Component {
  tabs: any[] = [];
  activeIndex1: number = 0;
  activeIndex2: number = 0;
  ...
}
```
And when we do `this.tabs.push({title: "Hello"});` we get error. 

But if we have

```
class Component {
  tabs: any[] = [{title: "Hello"}];
  activeIndex1: number = 0;
  activeIndex2: number = 0;
  ...
}
```
and later `this.tabs.push({title: "Hello2"});` then everything is OK.

**What is the motivation / use case for changing the behavior?**

Tabs to tabview can be created not only statically, but also dynamically.

**Please tell us about your environment:**

OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
HTTP server - angular webpack
* **Angular version:** 13.3.2

* **PrimeNG version:** 13.3.3

* **Browser:** [Firefox: 95.0.1]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   17.3.0

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
