### ISSUE TITLE
confuse about paginator display

### ISSUE THREAD

**Issue by rqx110** [primefaces/primeng#11431]
after upgrade from 12.0.1 to 13.3.3, I found the paginator has different behavior:
when there is no record, in 12.0.1 it will show the first page as default,
![image](https://user-images.githubusercontent.com/1829209/163771070-5b083a23-db65-47ad-a0ff-a31483a8f309.png)

and in 13.3.3 it will show nothing
![image](https://user-images.githubusercontent.com/1829209/163771034-ac539a2c-00d5-4d81-ad4e-ff33db9ec90b.png)

Is it by design?

**Comment by cetincakiroglu** [comment]
Hi, 

I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our Stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template

Regards
