### ISSUE TITLE
Bootstrap theme. .ui-growl-item-container.ui-state-highlight.ui-growl-message-... is not defined

### ISSUE THREAD

**Issue by ctrl-brk** [primefaces/primeng#1143]
The .ui-growl-item-container.ui-state-highlight.ui-growl-message-... (success, error, etc) are not defined in the bootstrap theme css.

**Comment by garthmason** [comment]
Agree, be good if this is fixed. Also note this shows up on the PrimeNG Demo site when you select the bootstrap theme.

**Comment by Mrtcndkn** [comment]
Hi,

Currently we are working on a brand new bootstrap theme according to bootstrap 4.So all of the problems about growl will be solved after that we are trying to accomplish this to the 1.0.2.

**Comment by garthmason** [comment]
Sounds great, thanks for the update!
