### ISSUE TITLE
Except maxmonth, the other months are not greyed out and remain clickable

### ISSUE THREAD

**Issue by shreyas-wgs** [primefaces/primeng#11435]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/github-2kpjgt-mnooft

**Current behavior**
Except maxmonth, the other months are not greyed out and remain clickable. All Months look like clickable.

**Expected behavior**
Upto maxmonth remain clickable and others are disabled with greyed out.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Common

* **Angular version:** 13.3.0

* **PrimeNG version:** 13.3.1
* **Browser:** all
 
* **Language:** all

* **Node (for AoT issues):** `node --version` =   v14.17.0

**Comment by devildant** [comment]
+1 it's a bug with min and max

visually the other months outside the min/max range are not grayed out and are clickable

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
