### ISSUE TITLE
confuse about paginator display 

### ISSUE THREAD

**Issue by rqx110** [primefaces/primeng#11432]
after upgrade from 12.0.1 to 13.x, I found the paginator has different behavior:
when there is no record, in 12.0.1 it will show the first page as default,
![image](https://user-images.githubusercontent.com/1829209/163771070-5b083a23-db65-47ad-a0ff-a31483a8f309.png)
https://stackblitz.com/edit/primeng-paginator-demo-mofddx?file=src/app/app.component.html

and in 13.x it will show nothing
![image](https://user-images.githubusercontent.com/1829209/163771034-ac539a2c-00d5-4d81-ad4e-ff33db9ec90b.png)
https://stackblitz.com/edit/primeng-paginator-demo-kvq2qb?file=src/app/app.component.html

Is it by design?

**Comment by cetincakiroglu** [comment]
Hi,

It happens because totalRecords is 0, and there is nothing to display as the length in the paginator if there is no data.
Here is the refactored and working version of your example. https://stackblitz.com/edit/primeng-paginator-demo-vyra6d?file=src/app/app.component.html

Regards.
