### ISSUE TITLE
TabView Documentation is wrong and misleading.

### ISSUE THREAD

**Issue by mconner** [primefaces/primeng#11446]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-jujwgq-qvyfcr?file=src/app/app.module.ts

**Current behavior**

The documentation for TabView says to use `[selected]="i == 0"` for Dynamic tabs in the TabView.  However if you close a tab, you have to remove the item backing the tab from the collection. (Otherwise, if the tab panel contains a component, closing the tab does not trigger destruction of the component, and it may continue to consume resources; e.g.: rxjs timers, Http requests. )  but modifying the collection triggers updating of the tab panels, and (I assume) the binding is applied. The end result is that two tabs are selected simultaneously, and both are highlighted and the content of both is displayed.

See the stackblitz for more detail.

**Expected behavior**

The documentation should cover this and provide a better alternative.  This actually seems to be unnecessary, since the first tab is selected by default.  The documentation should also provide an example case where the Dynamic tabs need to be added and/or removed.  (And it should probably be point out that it is the  client's responsibility to modify the collection if using an ngFor.  The TabView does not do it -- nor should it, but there should be a way to for the client code to do it.

**Minimal reproduction of the problem with instructions**

See the Stackblitz

**What is the motivation / use case for changing the behavior?**

Any application where multiple tabs are data-dependent. For example.  A dashboard system with multiple dashboards, loaded one at a time. 

**Please tell us about your environment:**

Windows 10, IntelliJ, npm 

* **Angular version:** 13.X

* **PrimeNG version:** 13.3.2

* **Browser:** Edge 
 
* **Language:** TypeScript 

* **Node (for AoT issues):** `node --version` =  v16.14.0

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
