### ISSUE TITLE
p-inputNumber cannot use the decimal separator of the digital keyboard when the separator is a comma

### ISSUE THREAD

**Issue by jaffreg** [primefaces/primeng#11442]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Using p-inputNumber with locale="fr", when I want to type a number with digits, I cannot use the numeric keypad to type the decimal separator.
The component p-inputNumber is expecting a comma as a decimal separator, and the digital keyboard only provides points.

**Expected behavior**
Without the bug, we would be able to type numbers with digits using the digital keyboard, even with locales expecting commas.

**Minimal reproduction of the problem with instructions**
See https://stackblitz.com/edit/github-qhqhnr where the p-inputNumber is set with french locale.

```
  <p-inputNumber
    locale="fr"
    [minFractionDigits]="2"
    [maxFractionDigits]="2"
  ></p-inputNumber>
```

**What is the motivation / use case for changing the behavior?**
The decimal separator in the digital keyboard is not really a point, it is a decimal separator. So we should be able to use the decimal key whatever the locale. For instance, in Excel, when we use the digital keyboard, the decimal key gives a comma or a point, depending on the locale.

**Please tell us about your environment:**
Windows 10

* **Angular version:** 13.0.3

* **PrimeNG version:** 13.3.2

* **Browser:** Chrome
 
* **Language:** all

**Comment by vstiebe** [comment]
For clarity, this issue happens when using the numeric keyboard. Locale pt-BR here.

**Comment by JakobWl** [comment]
Still the case would love a solution

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
