### ISSUE TITLE
New Component: Splitter

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#1144]
Create p-splitter similar to;

http://blackgate.github.io/bg-splitter/

**Comment by rukshandangalla** [comment]
any progress on this? I am currently looking for this kind of component

**Comment by LeonardoX77** [comment]
still no progress??? at least any alternative solution?

**Comment by hhmultimediallc** [comment]
Does anyone know the status of this component? I could use one of these to replace the one we are using where I work.
Thanks.

**Comment by jllodra** [comment]
It would be nice to have, although I'm already using https://github.com/bertrandg/angular-split/ 3.0.0.rc0 without hassles.

**Comment by skormel** [comment]
We need a splitter panel and we've though on angular-split as @jllodra says.

**Comment by yelhouti** [comment]
@cagataycivici why not just use css grid, please do not provide components already offered vanilla css

**Comment by Fridthjof** [comment]
When is this feature implemented?

**Comment by cagataycivici** [comment]
[Ready](#9677) for 11.1.0-rc.1
