### ISSUE TITLE
Overflow within a p-carousel-item causes Incorrect display and paging

### ISSUE THREAD

**Issue by mconner** [primefaces/primeng#11440]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-fs54y9-m3rbew?file=src/app/app.component.scss

**Current behavior**

If you have content that is wider than the p-carousel-item, it grows beyond that allotted  by the flex style (based on numVisible), because there's no overflow.  As a result, subsequent items are pushed out of alignment.

**Expected behavior**

When numVisible is specified, that number of items should be displayed (even if all of each item cannot be displayed).

**Minimal reproduction of the problem with instructions**

See the stackblitz example.  The second item has a name that is too long. As a result, the carousel item is too wide and pushes the other items over, and so the paging is off.  

Workaround:
This can be corrected  by adding an `overflow: hidden` to the p-carousel-item but this requires an ng-deep (See the scss.  Aside: In StackBlitz, if I uncomment my scss that corrects this, it takes effect immediately, but if I comment it **out** again, I have to do a refresh to see the effect.  No idea why. ), 

**What is the motivation / use case for changing the behavior?**

The carousel should display and page correctly, and the items should have bounds it can display within.

**Please tell us about your environment:**

Win10, IntelliJ, 

* **Angular version:** 13.x

* **PrimeNG version:** 13.3.2

* **Browser:** Edge

 
* **Language:**  TypeScript 4.5.5

* **Node (for AoT issues):** `node --version` =   v16.14.0

**Comment by cetincakiroglu** [comment]
Hi,

It's not a bug or defect. You need to use responsiveOptions property.
You can inspect the behavior from here https://primefaces.org/primeng/carousel

Regards

**Comment by mconner** [comment]
@cetincakiroglu, I think you misunderstand what I'm saying.  

The responsiveOptions determinine the numVisible and numScroll for different breakpoints.  I'm not talking about that.  I've explicitly set the numVisible in the example to 3:
```
  [numVisible]="3"
  [numScroll]="3"

```
I would expect this to show three items, equally spaced, regardless of how much screen space there is, and I'm fine with that.  Instead, if an item is larger than that that 1/3 of the carousel, we, don't see 3 items, more like 2 1/2. 

Perhaps you aren't seeing what I mean because you are looking on a larger screen.  I've increased the length of one of the products so the problem is more exaggerated.  Here's a screenshot:
![image](https://user-images.githubusercontent.com/540402/165190014-010e1ce1-73b4-43d3-803b-7e137169f89c.png)

There should be 3 evenly spaced items.  There are not.  The carousel is not enforcing that.  I would think the styling rule you have:
```
#pr_id_1 .p-carousel-item {
    flex: 1 0 33.333333333333336%;
}
```
_should_ take care of that, but it does not.

Again, this can be fixed by adding styling to prevent the child elements from overflowing:
```
...
  .p-carousel-item {
    overflow: hidden;
  }  

```
