### ISSUE TITLE
[BUG] Dropdown items not reachable within a dialog component

### ISSUE THREAD

**Issue by LeonieWV** [primefaces/primeng#11445]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
When the user tries to open a dropdown which is on the bottom of the dialog component, they can’t select an option because the dropdown overlay is partly hidden behind the footer of the dialog. 

The overlay of the dropdown has a collision detection for the browser screen to make sure that if the overlay is below the browser screen it will be shown on top. (relativePosition() on the domhandler.ts)
However when a dropdown is placed at the bottom of a dialog or scrollable div it will still be shown below and will need to be scrolled down to show the items. But in this [issue](https://github.com/primefaces/primeng/issues/9324) the improvement made sure that overlay panels will be closed when you scroll in scrollable containers, therefor making it impossible to see and select items in the dropdown. 

**Expected behavior**
The user can select the options of the dropdown because the overlay will be above the dropdown label.

There are several ways to better manage this behaviour:
1. (hard) Instead of checking if the overlay will collide with the browser window boundaries, it will be checked with the container boundaries of the parent. However this hard to implement because you will not be sure which container to use to set the boundaries to.
2. (simpler) Give the dropdown a attribute that sets the overlay above the dropdown trigger. This will then override the [function relativePosition on the domhandler](https://github.com/primefaces/primeng/blob/616b9c5cd15c5296829039f7264bf24f76b78953/src/app/components/dom/domhandler.ts#L94). This can be used when you have a dropdown on the bottom of the dialog to always show the overlay on top. 

**Minimal reproduction of the problem with instructions**
In the stackBlitz you can see to situations with this problem:
1. In a scrollable div
Have a div (in stackblitz red) with a specific height that is smaller than it content. Add a dropdown to the bottom of the div. Below the div should be space that is bigger then the overlay of the dropdown. I have added some lorem ipsum text and another dropdown.
When you scroll the page down so that the bottom of the red div is on the bottom of the browser screen you can see the overlay to be shown above in the red div.
If you scroll all the way down you can see the bottom dropdown overlay to be shown above but now the dropdown in the red div will not be shown correct anymore

2. In a dialog
Have a dialog (basic dialog in stackblitz) that only takes up a third of the browser screen height. Put on the bottom the dropdown. 
I have also added a long dialog in which you can see on the bottom that the dropdown overlay will be shown on top.

[StackBlitz](https://stackblitz.com/edit/primeng-dropdown-demo-kggw8u?file=src/app/app.component.html)

**What is the motivation / use case for changing the behavior?**
With this bug it is impossible to use a dropdown at the bottom of a scrollable form or dialog.
But you can’t always know if this will happen because of size differences in screens, if it is smaller the dialog will probably as big as the screen but if you use a bigger screen it can be that I will be smaller and therefor higher than the bottom of the browswer screen and then not work anymore.
You can use appendTo=”body” but to show it above would be better because then it wouldn’t overflow the container it is in.

**Please tell us about your environment:**

* **Angular version:** 13.0.3 (problem also in newest version)

* **PrimeNG version:** 13.0.4 (problem also in newest version)

* **Browser:** all
 
* **Language:** all

**Comment by cetincakiroglu** [comment]
Hi,

You can use appendTo property of dropdown component. Here is the refactored and working version of your example https://stackblitz.com/edit/primeng-dropdown-demo-u5aqx1?file=src%2Fapp%2Fapp.component.html

Regards
