### ISSUE TITLE
Improve TabView tab close behavior

### ISSUE THREAD

**Issue by mconner** [primefaces/primeng#11453]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/github-d5e1qw?file=src/app/app.component.html

**Current behavior**

Currently, when closing the selected tab, TabView finds the first (left to right) non-closed, non-disabled tab, and selects that.  
**Expected behavior**

It should follow tab close behavior that we would see elsewhere, where the tab to the right of the closed tab becomes active, or to the left if there is none to the right. See Edge and Chrome browsers, Excel Spreadsheets  (though admittedly, google sheets picks the one to the left, for some reason).   (Also, an animation on the close would be nice.)

**Minimal reproduction of the problem with instructions**

See Stackblitz

**What is the motivation / use case for changing the behavior?**

Users have come to expect this behavior.  

**Please tell us about your environment:**

Windows 10, IntelliJ

* **Angular version:** 13.X

* **PrimeNG version:** 13.3.2

* **Browser:** Edge, Chrome

 
* **Language:** TypeScript 4.5.5

* **Node (for AoT issues):** `node --version` =   v16.14.0

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
