### ISSUE TITLE
p-slider: when clicking, onChange event emitter is not including the original event if slider uses steps

### ISSUE THREAD

**Issue by shdk** [primefaces/primeng#11452]
https://github.com/primefaces/primeng/blob/616b9c5cd15c5296829039f7264bf24f76b78953/src/app/components/slider/slider.ts#L297-L321
https://github.com/primefaces/primeng/blob/616b9c5cd15c5296829039f7264bf24f76b78953/src/app/components/slider/slider.ts#L323-L336
https://github.com/primefaces/primeng/blob/616b9c5cd15c5296829039f7264bf24f76b78953/src/app/components/slider/slider.ts#L411

Shouldn't the event received in setValueFromHandle be passed to the handleStepChange function and then to updateValue? If not the original event gets lost and cannot be retrieved.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
