### ISSUE TITLE
More than one dropdown can be opened at a time

### ISSUE THREAD

**Issue by PrashanthThomas** [primefaces/primeng#11455]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**PrimeNg Component Demo Page (Bug Reports)**
https://www.primefaces.org/primeng/dropdown

**Current behavior**
In a combination of keyboard events and mouse events, two dropdowns can have their lists shown at the same time.

**Expected behavior**
Once a dropdown looses focus, it should automatically hide its list, if open.

**Minimal reproduction of the problem with instructions**
![image](https://user-images.githubusercontent.com/87276096/165243385-74dccfc8-cdeb-40d6-b07b-7dc067b3f4b8.png)

1. Bring the Basic Dropdown to focus.
2. Use Space/Enter to open the dropdown list.
3. Click on any other dropdown

Notice that two dropdowns are open at the same time
![image](https://user-images.githubusercontent.com/87276096/165244230-34b21333-1c4e-41d9-ba70-483a20ada31a.png)

**What is the motivation / use case for changing the behavior?**
Our application works with forms, there are a lot of dropdowns which the customer can shift between. Customers prefer using the keyboard to shift through input fields. But in certain cases they may use the mouse to jump to another dropdown while one is already open. The visual result is not desirable.

* **Angular version:** 13.X

* **PrimeNG version:** 13.3.3

* **Browser:**Chrome, Firefox and more
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   16.13.2

**Comment by sridhark158** [comment]
+1

even I'm looking for the solution

i found this issue after upgrading prime NG
