### ISSUE TITLE
dropdown unexpected scroll behaviour in table

### ISSUE THREAD

**Issue by 123FLO321** [primefaces/primeng#11467]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
If a p-dropdown element is clicked inside a horizontal scrollable view the view scrollts the dropdown is instantly closed again, because of the scroll handler.
This requires users to click twice.

**Expected behavior**
The view should not scroll and the dropdown stay open

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/github-eh42jm?file=src/app/app.component.html

**Comment by cetincakiroglu** [comment]
Hi,

It's not a bug or defect. You should use appendTo property.
Here is a refactored and working version of your StackBlitz example.
https://stackblitz.com/edit/github-eh42jm-n6lbza?file=src%2Fapp%2Fapp.component.html

Regards
