### ISSUE TITLE
p-columnFilterFormElement with custom template can't adapt according to the matchMode

### ISSUE THREAD

**Issue by yelhouti** [primefaces/primeng#11466]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
I would like to be able to to use a switch case the same way the default implementation does based the matchMode:
If the matchMode is in: use a multiSelect if equals use a dropdown (this is a simple example).

**Expected behavior**
It would be great to have in the context the full filterConstraint :
https://github.com/primefaces/primeng/blob/c6691c9649cc03e307ab9c4ecf4867274a5f19e6/src/app/components/table/table.ts#L4233

**To reproduce**

```
ngAfterViewInit(): void {
      (<FilterMetadata[]> this.table.filters[name]).push({value: null, matchMode: FilterMatchMode.SPECIFIED})
}

```

They are displayed the same way

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by ThoSap** [comment]
Hi, can you **please reopen this ticket** as I have the same use case.

My use case is to implement a custom `ColumnFilterFormElement` where based on the type of the column (text, numeric, boolean, date) I show a custom filter menu where the user is also able to filter `is null` and `isNot null`.

For example if the type is `text`, I would like to show a editable autocomplete for all `matchMode`s except `is` and `isNot`, where only `null` filtering is possible (as `equals` and `notEquals` already exist for text equality checking).

For this to work, can you **please** add the full `filterConstraint` and `type` to the ColumnFilterFormElement `filterTemplate` context?
