### ISSUE TITLE
Keep overlay panel open on page scroll

### ISSUE THREAD

**Issue by olingerc** [primefaces/primeng#11470]
**I'm submitting a ...**
```
[x] bug report
[x] feature request
[ ] support request
primeng v13.3.0
```

Overlay panels are closed if the page is scrolled (cf relevant code snippet below). However, this is not the case on the [demo page](https://www.primefaces.org/primeng/overlaypanel).  This is why I marked this issue as a bug report as well.

I propose adding a configuration option to disable this. I tried to set the scrollHandler in the onShow() event to null but did not succeed.

[Relevant code](https://github.com/primefaces/primeng/blob/c6691c9649cc03e307ab9c4ecf4867274a5f19e6/src/app/components/overlaypanel/overlaypanel.ts#L315)

```
    bindScrollListener() {
        if (!this.scrollHandler) {
            this.scrollHandler = new ConnectedOverlayScrollHandler(this.target, () => {
                if (this.overlayVisible) {
                    this.hide();
                }
            });
        }

        this.scrollHandler.bindScrollListener();
    }
```

**Comment by jonatanpetersson** [comment]
Had the same issue and managed to solve it by overriding the method you mentioned:

`@ViewChild('overlay') overlay: OverlayPanel;

  ngAfterViewInit(): void {
    this.overlay.bindScrollListener = () => {
      if (!this.overlay.scrollHandler) {
        this.overlay.scrollHandler = new ConnectedOverlayScrollHandler(this.overlay.target, () => {
          this.overlay.align();
        });
      }
      this.overlay.scrollHandler.bindScrollListener();
    };
  }`
  
  I agree, this would be great to have as an option.

**Comment by jonatanpetersson** [comment]
Had the same problem and managed to solve it by overriding the method you quoted:
```
@ViewChild('overlay') overlay: OverlayPanel;

  ngAfterViewInit(): void {
    this.overlay.bindScrollListener = () => {
      if (!this.overlay.scrollHandler) {
        this.overlay.scrollHandler = new ConnectedOverlayScrollHandler(this.overlay.target, () => {
          this.overlay.align();
        });
      }
      this.overlay.scrollHandler.bindScrollListener();
    };
  }
  ```
  I agree, would be nice to have this as an option.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by sthompson-celerity** [comment]
I am on 14, and am having this problem as well.

**Comment by slavco86** [comment]
@mertsincan 
This is clearly still an issue. Can this be re-opened?

**Comment by matanarbel** [comment]
I'm using v18, and this issue still happens.
I also narrowed it down to the `bindScrollListener()` function, to which I saw that the `ConnectedOverlayScrollHandler`'s callback is called only when the scrolling is on a containing element, and not on the `body`.

For example, in this code the scroll will be on only the `body`, and when scrolling the `body`, the popover doesn't disappear:
```
<div>
  <button (click)="op.toggle($event)">share</button>
  <p-popover #op appendTo="body">
    <div> test </div>
  </p-popover>
  <div>Line</div>
  <div>Line</div>
  <div>Line</div>
  <div>Line</div>
  <div>Line</div>
  <div>Line</div>
</div>
... rest of the body
```

But in this code, when I set the parent `div` to be scrollable, and I'm scrolling the **div** the popover disappears on scroll (when scrolling the `body`, the popover doesn't disappear):
```
<div style="height: 100px; overflow-y: scroll">
  <button (click)="op.toggle($event)">share</button>
  <p-popover #op appendTo="body">
    <div> test </div>
  </p-popover>
  <div>Line</div>
  <div>Line</div>
  <div>Line</div>
  <div>Line</div>
  <div>Line</div>
  <div>Line</div>
</div>
... rest of the body
```

** I also tried it without the `appendTo="body"` and got the same results.
