### ISSUE TITLE
Calendar should reflect changes of dateFormat input on the fly

### ISSUE THREAD

**Issue by WillBoig** [primefaces/primeng#11473]
I'm submitting a ...
```
[x ] bug report 
[ ] feature request 
[ ] support request 
```

**Current behavior**
If the dateFormat input value is changed, the date format is not applied until the user clicks on the calendar input

**Expected behavior**
The dateFormat should change as soon as the property value is modified.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/github-lwu6zj?file=src/app/app.component.html
- Use the button  "set date format mm/dd/yy"
- Observe that the first calendar input (legacy) still has the old date format
- Observe that the second calendar input (fixed) has the new date format
- Click on the first calendar input and observe that the dateFormat has changed

**What is the motivation / use case for changing the behavior?**
In an application in which the user can change on the fly it's current language without reloading the page, date input formats should reflect the change without having to click on the input.

* **Angular version:** 13.2.5
* **PrimeNG version:** 13.3.3

**Comment by WillBoig** [comment]
Hello guys. Any news regarding my PR ? I would be happy to get any feedback and improve it if you feel it is needed.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
