### ISSUE TITLE
[ Feature request ] - Autocomplete | Allow to disable input while searching

### ISSUE THREAD

**Issue by maxcabourg** [primefaces/primeng#11479]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

It would be really nice if there was a boolean input attribute for the autocomplete component that would disable or freeze the input field while the method provided for the completeMethod output is working instead of having to do it manually.

**What is the motivation / use case for changing the behavior?**

Actually, we can cumulate completeMethod calls pretty easily and it combines the result of all the calls which is really bad for the user experience.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
