### ISSUE TITLE
[ DataTable ] CSV export doesn't work with a large amount of data

### ISSUE THREAD

**Issue by raaaste** [primefaces/primeng#1147]
CSV export doesn't work with a large amount of data. Tested this with 1.0.0-beta.8 and beta.19. Instead of offering a file for download, the browser opens a new blank tab. The biggest file I was able to download was 1,94 MB (7163 lines, about 284 characters each), so it could have something to do with the 2 MB mark.

**Comment by raaaste** [comment]
It seems to be a problem with Chrome. Tested with Firefox and the export worked fine on it, downloading a 14mb file without problems.

**Comment by cagataycivici** [comment]
Good to hear!
