### ISSUE TITLE
p-table filters

### ISSUE THREAD

**Issue by nchizhov** [primefaces/primeng#11475]
[*] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Current behavior**
Error when using p-table with [filters] and p-columnFilter input:
```
ERROR TypeError: Cannot set properties of undefined (setting 'value')
    at ColumnFilterFormElement.onModelChange (primeng-table.mjs:3964:9)
    at ColumnFilterFormElement_ng_template_1_input_1_Template_input_input_0_listener (primeng-table.mjs:3987:113)
    at executeListenerWithErrorHandling (core.mjs:14952:1)
    at wrapListenerIn_markDirtyAndPreventDefault (core.mjs:14996:1)
    at HTMLInputElement.<anonymous> (platform-browser.mjs:465:38)
    at ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.mjs:25444:1)
    at ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at ZoneTask.invokeTask [as invoke] (zone.js:487:1)
```

**Expected behavior**
Should work p-table [filters] and p-columnFilter

* **Angular version:** 13.1.0

* **PrimeNG version:** 13.3.3

* **Browser:** all

**Comment by olaisen81** [comment]
Same issue, any update Sir?

**Comment by cetincakiroglu** [comment]
Hi,

Could you please share a StackBlitz reproducer by using https://stackblitz.com/github/primefaces/primeng-issue-template

**Comment by olaisen81** [comment]
Hi Cetin, 
it's hard to create a stackblitz for me, i've got a complex situation where i'm adding and removing column dinamically, each header column has its own filter; when i revome a column and adding different type of column filter it's working ok, but when i remove and then add a column with the same type filter i reproduce the bug.
I'm using PrimeNg 14.0.1 and the interested line is on primeng-table.mjs:3998:28, can't read value of undefined.

**Comment by olaisen81** [comment]
I've fixed the issue wrapping the manipulating column function  in a settimeout(()=>{ ... }, 0) statement.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
