### ISSUE TITLE
`onLazyLoad` is also triggered multiple times when `sortField` and `sortMode` are specified.

### ISSUE THREAD

**Issue by AbdulRehman-IH** [primefaces/primeng#11489]
`onLazyLoad` is also triggered multiple times when `sortField` and `sortMode` are specified.
For example, I parse state of application from URL query parameters to variable `state` in component, because router is my single source of truth.

Component's template looks like this:
```html
<p-table [value]="items"
         [rows]="state.pageSize"
         [first]="state.pageOffset"
         [sortMode]="'single'"
         [sortField]="state.sortField"
         [sortOrder]="state.sortOrder"
         [rowsPerPageOptions]="[10, 20, 50]"
         [paginator]="true"
         [lazy]="true"
         [totalRecords]="totalCount"
         [responsive]="true"
         (onLazyLoad)="onLazyLoad($event)"
         class="break-word table-columns-auto-width"
         [rowHover]="true">
.
.
.
</p-table>
```
Table has multiple sortable columns (e.g createdAt, updatedAt...).

On first load, `state.sortField` and `state.sortOrder` are `null`.
Then user clicks on column header to sort results by this column.
Click triggers `sort()` which triggers `sortSingle()` and therefore `onLazyLoad`.
What we do in `onLazyLoad` is simple redirect to same page, with updated query parameters.
New values from query parameters are set to `state` variable and this causes change of `sortField` and `sortOrder` inputs on TurboTable. These inputs are implemented as setters. Each of setters calls `sortSingle()` which triggers `onLazyLoad`.

So, sort triggered by user (click) results in 3 `onLazyLoad` events.
From my point of view, setters should call `sortSingle()` only if new value differs from internal sort field/order.. **or even better, it shouldn't trigger events at all (for all inputs) in lazy mode.**

I would say, that our usecase is typical for other developers which use redux/ngrx architecture as well.

_Originally posted by @bossqone in https://github.com/primefaces/primeng/issues/5480#issuecomment-392568915_

**Comment by erincarignan** [comment]
+1

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
