### ISSUE TITLE
NgClass not updated correctly when using button label with translation

### ISSUE THREAD

**Issue by BRNTZN** [primefaces/primeng#11480]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/angular-esn4jk-u7ukcw?file=src/app/view-selector/view-selector.component.html

**Current behavior**
ngClass is not correctly updated when using button label with translation

workaround: instead of using label, put the content in between the button tags: 
`<button pButton>{{ 'green' | translate }}</button>`

**Minimal reproduction of the problem with instructions**
Click the button that says green => buttons are correctly updated, green button is now active
Click the button that says nl => red button is now active even though color should still be green

* **PrimeNG version: 13.3.3**

* **Browser:** [Chrome XX | Firefox XX]
 
* **Language:** [TypeScript X.X]

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
