### ISSUE TITLE
Table module contains unnecessary imports

### ISSUE THREAD

**Issue by DanialV** [primefaces/primeng#11484]
I am using only primeng table module in my project however when I checked my final bundle details I realized 257kb size of my bundle is belong to primeng but primeng table is only 70Kb

![image](https://user-images.githubusercontent.com/7758915/166889129-47553097-8736-4123-8bbb-02e93b428a8e.png)

As you can see in the image in primeng section there are unnecessary  sections like calendar, inputnumber, dropdown, and so on 
I only import table module in my project 
`import { TableModule } from 'primeng/table';`

I use Angular 13.0.2 with primeng 12.1.0

**Comment by cetincakiroglu** [comment]
Hi,

PrimeNG Table component has a complex structure and all of the imports are used within different table variations.
You can check https://primefaces.org/primeng/table to inspect features and you'll see why we import dropdown, calendar etc, in the table.

**Comment by jwrascoe** [comment]
@DanialV I agree with you its WAY too much, in our case we are just using a very simple table without all the bells and whistles.

@cetincakiroglu, is there a "slimmed down" p-table module that we can import somewhere in the PrimeNG code?

**Comment by vogloblinsky** [comment]
Same problem, too many imports for just a table with one column sorting option...
