### ISSUE TITLE
After restriction <p-calendar> also increment 1 hour in future time

### ISSUE THREAD

**Issue by HARSHA190599** [primefaces/primeng#11490]
* **Angular version: 10** 
* **PrimeNG version:10.0.1** 
*  If we have both date and time picker in calendar and user change time and there is restriction that future time should not be allow, also date not allow. This error is required when user changes time (user increment time). 
* 

- [ ] `<p-calendar [maxDate]="todayDate" dateFormat="dd-mm-yy"  [showTime]="true" hourFormat="24" [showIcon]="true"> 
  </p-calendar>`
-//In TypeScript
- [ ] `todayDate = new Date();`

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
