### ISSUE TITLE
TabMenu tab still active even when the routerLinkActiveOptions containc exact true.

### ISSUE THREAD

**Issue by vipinjn24** [primefaces/primeng#11495]
**I'm submitting a ...**  (check one with "x")
```
[--] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
The parent tab is still active when you are on different child route.
e.g. /parent is route for parent and /parent/child is route for child.
so if we are on child route the parent tab is still showing active.

**Current behavior**
described above.

**Expected behavior**
the parent tab should not be active when exact true is true.

**Problem code positions**
https://github.com/primefaces/primeng/blob/ca91dcc085eb2d3db21446e92cfa15566e7e7236/src/app/components/tabmenu/tabmenu.ts#L21
https://github.com/primefaces/primeng/blob/ca91dcc085eb2d3db21446e92cfa15566e7e7236/src/app/components/tabmenu/tabmenu.ts#L124

here we should use **exact** behavior option.

**What is the motivation / use case for changing the behavior?**
upgrading from previous version

**Please tell us about your environment:**

* **Angular version:** 5.X
v13.1.0

* **PrimeNG version:** 5.X
v13.0.4

* **Browser:** all
 
* **Language:** TypeScript 4.4.2

* **Node (for AoT issues):** `node --version` =   v14.17.1

**Comment by hanoldaa** [comment]
Also having this issue as well. The first tab is always active with the menu item's routerLink set to `'/'` despite the current route being `'/contact'`, which has its own menu item.

**Comment by JuanEL0** [comment]
I have the same issue here:

Angular: 14.0.5
PrimeNG: 14.0.1

```typescript
this.items = [
  { label: 'Employees', routerLink: ['/employees'], routerLinkActiveOptions: { exact: true }  },
  { label: 'Applicants', routerLink: ['/employees/applicants'], routerLinkActiveOptions: { exact: true }  },
];
```
```html
<p-tabMenu [model]="items"></p-tabMenu>
<router-outlet></router-outlet>
```

Selecting _employees_ option:
![image](https://user-images.githubusercontent.com/64238991/186062455-76a3fae5-ba3f-4a4b-9f56-6aa540ee8ec9.png)

Selecting _applicants_ option:
![image](https://user-images.githubusercontent.com/64238991/186062584-3cdb4ff5-5cbd-45ec-9fa7-5a4d20678296.png)

**Comment by atheros** [comment]
Same issue here.

Angular 14.1, using standalone components.

![image](https://user-images.githubusercontent.com/1220453/193448238-6cfb5cbe-2658-4c56-80b9-a26606855d7c.png)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
