### ISSUE TITLE
Dropdown items not being shown properly at the end of scrollable table

### ISSUE THREAD

**Issue by marcioggs** [primefaces/primeng#11501]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-tablescroll-demo-dmcwh4?file=package.json

**Current behavior**
The dropdown items are being hidden when at the end of the table.
![image](https://user-images.githubusercontent.com/2506127/167664497-3b6c3e3a-31ee-4f44-a3ef-e528fa1fc5b1.png)

**Expected behavior**
All dropdown items should be displayed.

**Minimal reproduction of the problem with instructions**
1. Click at one of the dropdowns at one of the last table rows;
2. Verify that the dropdown items are not being displayed.

* **Angular version:** 13.0.3
* **PrimeNG version:** 13.0.4
* **Browser:** [Chrome 101.0.4951.54 (Official Build) (64-bit) | Edge 101.0.1210.39 (Official build) (64-bit) ]

**Comment by cetincakiroglu** [comment]
Hi,

You can use appendTo property.

Here is the refactored and working version of your example https://stackblitz.com/edit/primeng-tablescroll-demo-tfydsa?file=src%2Fapp%2Fapp.component.html

Regards

**Comment by marcioggs** [comment]
Thanks, @cetincakiroglu !
I read about the `appendTo` property but thought it would change the dropdown position.
