### ISSUE TITLE
Column resize does not work properly with frozen columns

### ISSUE THREAD

**Issue by sotjdisc** [primefaces/primeng#11509]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-nylm9c?file=src/app/app.component.ts

**Current behavior**
Resizing column "Name" (increasing size) and then moving the horizontal scrollbar, has the effect that the column name does not maintain its new size.

**Expected behavior**
Resized column must maintain its new size.

* **Angular version:** 13.X

* **PrimeNG version:** 13.4.0

* **Browser:** [all]
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by nsaini-05** [comment]
Issue still persists in "16.3.1"

**Comment by KommuSoft** [comment]
I found a "workaround" for this. One can write the resizer manually, like:

```
<DataTable ref="dt">
  <Column :frozen="true">
    <template #header>
        <span @mousedown="onResizeStart" class="p-datatable-column-resizer" data-pc-section="columnresizer"/>
    </template>
  </Column>
</DataTable>
```

and then in the method, let the `DataTable` handle it:

```
methods: {
  onResizeStart (e) {
    this.$refs.dt.onColumnResizeStart(e);
  }
}
```
