### ISSUE TITLE
InputMask onComplete bug

### ISSUE THREAD

**Issue by smilovanovic** [primefaces/primeng#1151]
onComplete event is triggering too early, ngModel has bad value when onComplete is triggered.

`<p-inputMask mask="9999" [(ngModel)]="model" [placeholder]="placeholder" (onComplete)="onComplete()"></p-inputMask>`

For the example above when you type in 4 digits, let's say 1111, in onComplete method ngModel has value 111_ or what ever the slotChar option value is.

**Comment by cagataycivici** [comment]
This is also reported by a PrimeNG PRO user and we're on it for RC1. Thank you.

**Comment by cagataycivici** [comment]
This only happens for me when there is an optional part like mask="99?9", it works well for mask="9999" on beta20.
