### ISSUE TITLE
v13.4.0 scrollHeight not working

### ISSUE THREAD

**Issue by acklj1** [primefaces/primeng#11519]
v13.4.0 scrollHeight not working
angular

devDependencies:
    "primeicons": "^5.0.0",
    "primeng": "^13.4.0",

<p-treeTable
        [scrollable]="true"
        scrollHeight="flex">

not working

**Comment by acklj1** [comment]
v13.3.2 is working
v13.3.3, v13.4.0 not working

**Comment by acklj1** [comment]
out div style="height: 500px"
scrollHeight="flex"

v13.3.2
![image](https://user-images.githubusercontent.com/18612941/168408603-cb39c048-f003-49fe-95f9-537d310f433a.png)

v13.3.3, v13.4.0
![image](https://user-images.githubusercontent.com/18612941/168408626-a8593813-e747-4377-96c0-167c4ed409e7.png)

**Comment by cetincakiroglu** [comment]
Hi,

It's difficult to understand the problem from screenshots. Please re-open this issue by using https://stackblitz.com/github/primefaces/primeng-issue-template

Regards.
