### ISSUE TITLE
ConfirmDialog | keeps raising z-index in whole application

### ISSUE THREAD

**Issue by Hapcy** [primefaces/primeng#11523]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-sq8br6?file=src/app/app.component.html

**Current behavior**
ConfirmDialog z-index keeps infinitely rising when autoZIndex is true. This causes problems when for some reason you can't turn it off (stacking dialogs in my case) but something else has a set zIndex and has to stay above the confirmdialog. In the attached stackblitz there is a red square above the confirmDialog but after a few clicks it sinks under it. If the confirm dialog is stacking and there are tooltips involved as well then the z-index keeps rising in steps of 1000.

**Expected behavior**
It should work like a normal dialog and only raise the z-index while it's visible.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/github-sq8br6?file=src/app/app.component.html
Press the button and accept the confirmdialog a few times. Observe as the red square initially appears above the dialog then after a few confirmations appears below it.

**What is the motivation / use case for changing the behavior?**
Dialog works differently. Fixed in https://github.com/primefaces/primeng/issues/6857.

**Please tell us about your environment:**

* **Angular version:** 13
* **PrimeNG version:** 13
* **Browser:** all
* **Language:** all

**Comment by cetincakiroglu** [comment]
Hi @Hapcy,

Please correct me if I'm wrong, you want to use stacking dialogs with autoZIndex is true?

**Comment by cetincakiroglu** [comment]
Hi @Hapcy,

Thanks for your report, we'll review your pull request.

Regard.
