### ISSUE TITLE
InputMask optional mask after separator

### ISSUE THREAD

**Issue by flkeller** [primefaces/primeng#11531]
**I'm submitting a ...**  (check one with "x")

[x ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap

Don't know if you will treat this as a bug or feature request. more likely feature request.

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/github-z5adml-p6beby

**Current behavior**
Currently you can not configure the mask to make parts of the input value optional

**Expected behavior**
e.g. with mask '?99999/?****'
the value '123/as' should be valid

**Minimal reproduction of the problem with instructions**
open stackblitz and enter 123/as
Value is not saved in model

**What is the motivation / use case for changing the behavior?**
This would make the mask more flexible

* **Angular version:** 13.03

* **PrimeNG version:** 13.3.2

* **Browser:** all

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
