### ISSUE TITLE
center p-dialog in container

### ISSUE THREAD

**Issue by jawaher1** [primefaces/primeng#11539]
Hello, 
I am trying to center a p-dialog in its container but its' always centerd for the whole page.
is there any way to achieve this?
Thanks

**Comment by cetincakiroglu** [comment]
Hi,

Issue is not clear, please feel free to reopen with a StackBlitz example by using PrimeNG issue template https://stackblitz.com/github/primefaces/primeng-issue-template

Regards

**Comment by jawaher1** [comment]
Hi, 
I actually meant that the p-dialog is by default ceneterd for the whole page. Is it possible to center it only in its container div?
