### ISSUE TITLE
Scollable=true on p-table propagating to a p-table contained a expanded row of aforementioned p-table

### ISSUE THREAD

**Issue by regalme** [primefaces/primeng#11533]
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

https://github-1qpshc.stackblitz.io

**Current behavior**
When setting the parent p-table to scrollable=true the scrollable=true will propagate to a p-table thats in a RowExpand p-table. Even if you set scrollable=false in the p-table contained in the expanded row

**Expected behavior**
that a p-table in an expanded row table has its own scrollable property

**Minimal reproduction of the problem with instructions**
create a p-table and set scrollable=true
crreate a expandedRow p-table inside the p-table, and set scrollable=false. Notice that autoLayout is disabled in the sub table

**What is the motivation / use case for changing the behavior?**
Having a table with scrollable=true and a subtable in an expandedrow with scollable=false

**Please tell us about your environment:**
Intellij, ng serve

* **Angular version:** 13.3.9

* **PrimeNG version:** 13.4.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
firefox and edge
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5] ts 4.6.2

* **Node (for AoT issues):** `node --version` =

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
