### ISSUE TITLE
tabMenu | inkbar doesn't change when setting activeTab dynamically (material design themes)

### ISSUE THREAD

**Issue by aygunoz** [primefaces/primeng#11544]
Change active tabMenu programmatically tabMenu link-bar doesn't move below the picture
I update example project for you;
https://stackblitz.com/edit/angular-ivy-pdkjrr
![image](https://user-images.githubusercontent.com/74569642/169871425-84e977f1-6ca6-4908-b7a3-9a35ce8bbc6d.png)

**Comment by cetincakiroglu** [comment]
Hi,

It's not a defect, I've created a demo for you.

https://stackblitz.com/edit/primeng-tabmenu-demo-836u6u?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html

Regards

**Comment by aygunoz** [comment]
Merhaba Çetin Bey,
İngilizce durumu tam anlatamadığımı düşündüm, o yüzden türkçe yazmak istedim kusura bakmayın lütfen.
Buttonla aktif sekmeyi değiştiğimde, alttaki link-bar değişmiyor nedense, sadece üstteki yazı rengi değişiyor. Durumla ilgili bir video kaydettim. Sorun Safari'den kaynaklı mı diye kontrol ettim, chrome'da da aynı sorun var.
Video;

https://user-images.githubusercontent.com/74569642/170042955-87c26b6b-7473-4d17-a5f1-4c64dcb925e9.mov

**Comment by cetincakiroglu** [comment]
Hi @aygunoz,

Are you using tabMenu for routing or content display?
If the case is not routing, you can use tabView instead to change dynamic content.

https://primefaces.org/primeng/tabview

**Comment by aygunoz** [comment]
Hi @cetincakiroglu,
I am using for content display. I initialize the component and show them on the tabMenu like chrome browser and then you can close the tab or add new tab.
I will test the code.
Thank you very much 👍🏼

**Comment by cetincakiroglu** [comment]
Hi @aygunoz,

It seems you need to use tabView component for it not tabMenu. You can make dynamic changes easier in your case. 
Please let me know if it works.

**Comment by cetincakiroglu** [comment]
Closing and moving the issue since it's not a defect it's a new feature and it's not only related to material themes, tabMenu needs activeIndex support.

New issue: #11553
