### ISSUE TITLE
Dropdown keyboard-naviagtion inside table (with selectable entries) is not working 

### ISSUE THREAD

**Issue by koegelf** [primefaces/primeng#11542]
I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-tableselection-demo-hgasbv?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.module.ts

**Current behavior**
The dropdown inside the p-table (where selection is enbaled) can't be navigated correctly with the keyboard, because it loses focus after the first "Arrow-Down"-press

**Expected behavior**
The dropdown menu-keyboard-naviagtion should work like outside of the table

**Minimal reproduction of the problem with instructions**
Just try to naviagte through the dropdown menu with the keyboard

**Please tell us about your environment:**

* **Angular version:** 12.1.0

* **PrimeNG version:** 13.3.0

* **Browser:** [Chrome]

**Comment by cetincakiroglu** [comment]
Hi,

Please try to use shift + arrow keys to navigate inside dropdown without losing focus.

Regards
