### ISSUE TITLE
Change active tabMenu programmatically tabMenu link-bar doesn't move

### ISSUE THREAD

**Issue by aygunoz** [primefaces/primeng#11540]
Change active tabMenu programmatically tabMenu link-bar doesn't move below the picture
![image](https://user-images.githubusercontent.com/74569642/169776157-0e96abfe-e283-40d3-8188-289142770b5e.png)

**Comment by cetincakiroglu** [comment]
Hi,

This issue is invalid please provide a StackBlitz case for us using;

https://stackblitz.com/github/primefaces/primeng-issue-template

Regards
