### ISSUE TITLE
Improve icon search in the documentation

### ISSUE THREAD

**Issue by ajsaraujo** [primefaces/primeng#11550]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

# Description

PrimeIcons has grown to support a considerable amount of icons. That said, I think the experience of searching for icons in the documentation could see some improvement. Unless you know exactly the name of a given icon, it can be hard to find it. 

I'd like icons to be findable by different words, rather than just the ones used in it's definition. For instance, being able to find the icon `pi-bell` by searching for "notifications" or the icon `pi-sync` by searching for "refresh".

This could be implemented by having a set of tags associated to each icon, and then search would consider this tags. I believe this would greatly improve developer experience and I am willing to submit a PR implementing it if it's appropriate.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
