### ISSUE TITLE
The overlay elements automatically close on mobile devices

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primeng#11567]
The affected components;

- [x] Autocomplete
- [x] Calendar
- [x] CascadeSelect
- [x] ColorPicker
- [x] ConfirmPopup
- [x] Menu
- [x] MultiSelect
- [x] OverlayPanel
- [x] Password
- [x] SlideMenu
- [x] Table (columnFilter)
- [x] TieredMenu
- [x] TreeSelect

**Comment by Th14go** [comment]
The problem was solved ?
