### ISSUE TITLE
Table.FilterGlobal don't search for comma decimal separator on column with currency='BRL'

### ISSUE THREAD

**Issue by vstiebe** [primefaces/primeng#11568]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Table.FilterGlobal doesn't search for a currency value formatted as comma decimal separator. I.E: currency="BRL"

**Expected behavior**
Table.FilterGlobal should search for a currency value honoring the currency decimal separator.

**Minimal reproduction of the problem with instructions**
Try to search for a currency formatted decimal value as BRL. It formats data with comma as a decimal separator but the user must search for point instead of comma for filtering to work.

* **PrimeNG version:** 13.0.3

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
