### ISSUE TITLE
P-Table returning DUPLICATE rows for dynamic content

### ISSUE THREAD

**Issue by Randle-Lanre** [primefaces/primeng#11565]
Angular version: 13.2.6
Primeng version: 13.4

```html
<p-table [columns]="displayedColumns"  [value]="dataSource" >
  <ng-template pTemplate="header" let-columns>
    <tr>
      <th *ngFor="let item of dataSource">
        {{item.claim}}
      </th>
    </tr>
  </ng-template>
  <ng-template pTemplate="body" let-rowData   >
    <tr >
      <td  *ngFor="let row of dataSource">{{row.value}}</td>
    </tr>
  </ng-template>
</p-table>
```
```TS 
export class UserProfileComponent implements OnInit {



  displayedColumns: string[] = ['claim', 'value'];
 
  dataSource: Claim[] = [];
 ...

  constructor( private authService: MsalService, private msalBroadcastService: MsalBroadcastService) {
  }
```

>  <H1>expected output is supposed to be</h1>

| col1 | col2 | col3 | col4 | col5 |
|------|------|------|------|------|
| foo  | bar  | brr  | fizz | buzz |

>  <H1>But i get the following below</h1>

| col1 | col2 | col3 | col4 | col5 |
|------|------|------|------|------|
| foo  | bar  | brr  | fizz | buzz |
| foo  | bar  | brr  | fizz | buzz |
| foo  | bar  | brr  | fizz | buzz |
| foo  | bar  | brr  | fizz | buzz |
| foo  | bar  | brr  | fizz | buzz |

i have tried various variations of this but I don't either get any rows displayed or rows display under a single column 

could this be a possible bug? ?

**Comment by aboudard** [comment]
Hello @Randle-Lanre, could you add the full code with mocked data so it can be reproduced ?

**Comment by Randle-Lanre** [comment]
@aboudard  could put the full code here, so i created a new project to create a somewhat mocked code 

> <H2>profile.component.ts</H2>

```TS
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-profile',
  templateUrl: './profile.component.html',
  styleUrls: ['./profile.component.scss'],
})
export class ProfileComponent implements OnInit {
  displayedColumns: string[] = ['claim', 'value'];

  dataSource: Claim[] = [];

  constructor() {}

  ngOnInit(): void {

    this.dataSource=this.data
  }

  data = [
    { id: 0, claim: 'clo', value: 'value0' },
    { id: 1, claim: 'cl1', value: 'value1' },
    { id: 2, claim: 'cl2', value: 'value2' },
    { id: 3, claim: 'cl3', value: 'value3' },
    { id: 4, claim: 'cl4', value: 'value4' },
    { id: 5, claim: 'cl5', value: 'value5' },
    { id: 6, claim: 'cl6', value: 'value6' },
    { id: 7, claim: 'cl7', value: 'value7' },
    { id: 8, claim: 'cl8', value: 'value8' },
    { id: 9, claim: 'cl9', value: 'value9' },
  ];
}

export class Claim {
  id?: number;
  claim?: string;
  value?: string;
}



```

> <H2>profile.component.html</H2>

```html

<p> Profile</p>
<p-table [columns]="displayedColumns" [value]="dataSource">
  <ng-template pTemplate="header" let-columns>
    <tr>
      <th *ngFor="let item of dataSource">
        {{item.claim}}
      </th>
    </tr>
  </ng-template>
  <ng-template pTemplate="body" let-rowData>
    <tr>
      <td *ngFor="let row of dataSource">
        {{row.value}}</td>
    </tr>
  </ng-template>
</p-table>
```

![image](https://user-images.githubusercontent.com/19264390/172018059-389733b7-b86f-4be3-b8f9-844c5ff42f97.png)

**Comment by aboudard** [comment]
Ok, I'm sorry, but I think you missed some points of the configuration.
I made your data work from the PrimeNg example here :

https://primeng-tabledynamic-demo-fsvmqh.stackblitz.io

First, you make your loops on your dataSource, when you should loop on your cols, this way you can't access the proper data from your list.

This is wrong : `<th *ngFor="let item of dataSource">`
This is ok : `<th *ngFor="let col of columns">`

I hope this solves your problem.
Cheers.

**Comment by Randle-Lanre** [comment]
@aboudard  i will review and provide feedback. thanks

**Comment by Randle-Lanre** [comment]
@aboudard i looked at your solution, but it doesn't quiet hit the point 
values are "Rows" and not a column, please review your solution

**Comment by aboudard** [comment]
I see indeed that it's not your expected output, ok.
But how do you expect to have only one line of results if the provided datasource has `n` lines ? The provided `[value]` of the p-table is what defines the number of lines, no matter how you handle the columns, right ?

Source code says : 
```
[ngForOf]="value"
```

I don't understand how you figured your expected output from the documentation or the source code. If I had to reach this output with p-table, I would rearrange my input datasource.

Cheers :)

**Comment by Randle-Lanre** [comment]
@aboudard  i did the same thing with **raw** ngFor and arrived at the expected output 

then switched to `ng-zorro`  UI component and still got my expected output 


are you familiar with maps? or key value pairs?

and what  "td " vs "th" stands for in html ??

**Comment by aboudard** [comment]
Ok, looks like you figured all this out.
I'll let contributors to it.
Cheers.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by AnuragSriva** [comment]
We can use let-value or let-column and loop through dataSource.

<th *ngFor="let col of columns">
