### ISSUE TITLE
Why p-treeSelect filter doesn't work 

### ISSUE THREAD

**Issue by hero791** [primefaces/primeng#11579]
Why the p-treeSelect filter doesn't work properly? 
In the documentation there is the parameter and the example show how it works. 
But when I add the **[filter]="true"** parameter it doesn't work.

How can i fix it?

https://stackblitz.com/edit/primeng-treeselect-demo-acthc2?file=src%2Fapp%2Fapp.component.html

**Comment by volvachev** [comment]
Hi, this functionality has been added in release `13.3.3`, update the library to this version or higher.

**Comment by cetincakiroglu** [comment]
@hero791,

Here is an example of working version https://stackblitz.com/edit/primeng-treeselect-demo-yt8nwg?file=src%2Fapp%2Fapp.component.html

**Comment by situlindia** [comment]
There is a bug with the filter. If you perform a search and select a node, then once you open the panel the selected checkbox is not selected anymore. I could replicate with the stackblitz provided.

![image](https://user-images.githubusercontent.com/32801470/191240816-b8b3a69a-b4e7-4eb7-ae4b-ec7f5e4b5a07.png)

**Comment by greg0rym** [comment]
> There is a bug with the filter. If you perform a search and select a node, then once you open the panel the selected checkbox is not selected anymore. I could replicate with the stackblitz provided.
> 
> ![image](https://user-images.githubusercontent.com/32801470/191240816-b8b3a69a-b4e7-4eb7-ae4b-ec7f5e4b5a07.png)

I think that the "key" property is required but is missing from the documentation
