### ISSUE TITLE
Table | State, sortField and resizableColumns result in filter loading error

### ISSUE THREAD

**Issue by Kisters-BS** [primefaces/primeng#11577]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/github-dmq63c?file=src%2Fapp%2Fapp.component.html

**Current behavior**
When using a table with state, sortField and resizableColumns will result in error:
Firefox:
![](https://user-images.githubusercontent.com/84901454/171608716-2a155af0-db64-462f-bf3d-8176ac876b41.png)
ERROR TypeError: this.containerViewChild is undefined
Chrome:
![](https://user-images.githubusercontent.com/84901454/171610236-92844a26-9243-429f-996d-aeea11c6e312.png)
ERROR TypeError: Cannot read properties of undefined (reading 'nativeElement')

**Expected behavior**
No error

**Minimal reproduction of the problem with instructions**

- Use a table with state, sortField and resizableColumns
- Set filters
- Refresh the website so that the filters are loaded and the error occurs

**What is the motivation / use case for changing the behavior?**
Correct behaviour, no error

**Please tell us about your environment:**

* **Angular version:** 5.X
13.3.7

* **PrimeNG version:** 5.X
13.4.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome and Firefox (current versions)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
