### ISSUE TITLE
how to extend or composition original PrimeNG module?

### ISSUE THREAD

**Issue by hryktrd** [primefaces/primeng#1157]
Hi.

I'll use PrimeNG for my project.
But my project is too big, so I want to use your module after extend, because I want to make custom parts from PrimeNG. For example, I want to make special button from ButtonModule.

I write codes like this.

-------------------------------------------------------------------------------------------
import {NgModule,Directive,Inject, Injector, ElementRef,AfterViewInit,OnDestroy,HostBinding,HostListener,Input} from '@angular/core';
import {CommonModule} from '@angular/common';
import {ButtonModule} from 'primeng/primeng';
import {DomHandler} from "primeng/components/dom/domhandler";
import {Button} from "primeng/primeng";

@Directive({
  selector: '[mpButton]',  // special selector
  host: {
    '[class.ui-state-hover]': 'hover&&!isDisabled()',
    '[class.ui-state-focus]': 'focus',
    '[class.ui-state-active]': 'active',
    '[class.ui-state-disabled]': 'isDisabled()'
  },
  providers: [DomHandler]
})

export class MyButton extends Button {
  constructor( @Inject(ElementRef) elRef: ElementRef,
                  @Inject(DomHandler) domHandler: DomHandler){
    super(elRef, domHandler);
  }
}

@NgModule({
  imports: [CommonModule,ButtonModule],
  exports: [MyButton,Button],
  declarations: [MyButton]
})
export class MyButtonModule { }
-------------------------------------------------------------------------------------------

But it can't extends annotations, for example
@HostListener('mouseenter', ['$event'])
@HostListener('mouseleave', ['$event'])
@Input() get label(): string {
and so on...

Can I use my custom module from PrimeNG ?

**Comment by vanpouckesven** [comment]
I'm trying to extend the DataTable for a custom template but i'm having troubles because not all directives are exported by the module. Even if i fix that i still struggle to get past 

"No provider for ElementRef!" 

How did you solve this?

**Comment by cagataycivici** [comment]
Please use forum for support requests.
