### ISSUE TITLE
Dropdown needs two clicks to select a value

### ISSUE THREAD

**Issue by Pfreundt** [primefaces/primeng#11578]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-hx3wqs?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

**Current behavior**
Im using a method to get the options for the dropdown. It needs two clicks to select a value.

**Expected behavior**
Select an option with one click.

**Please tell us about your environment:**

* **Angular version:** 13.1.0

* **PrimeNG version:** 13.2.1

**Comment by volvachev** [comment]
Hi, I advise not to use the method inside the template, and in your case a new array is created after rendering.
Use `pure pipe` for example, or prepare the array before rendering and use it in the template.

**Comment by aboudard** [comment]
Totally agree with @volvachev, I would never load data to any kind of Input this way.
This is bad practice.

**Comment by cetincakiroglu** [comment]
Hi,

Wrong usage, component works as it should be.
Here is the refactored version of your example.

https://stackblitz.com/edit/github-hx3wqs-kgpwep?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

Regards
