### ISSUE TITLE
Fix import for Messages component - static template option

### ISSUE THREAD

**Issue by aboudard** [primefaces/primeng#11575]
**Hello, I'm submitting a**
```
[x] bug report
```

Original bug report here :
https://github.com/primefaces/primeng/issues/10461
It's marked as completed but the answer wasn't adressing the issue.

**Plunkr Case (Bug Reports)**
This stackblitz shows how importing SharedModule makes the p-messages work.

https://stackblitz.com/edit/primeng-messages-demo-duor76?file=src/app/app.module.ts

**Current behavior**
When you want to use the MessagesModule and the p-messages component with static content, your content won't show up because the QueryList is looking for PrimeTemplate directives :
https://github.com/primefaces/primeng/blob/master/src/app/components/messages/messages.ts#:~:text=%40ContentChildren(PrimeTemplate)%20templates%3A%20QueryList%3Cany%3E%3B
Since PrimeTemplate is exported in SharedModule, and SharedModule isn't imported in Messages component, the @ContentChildren(PrimeTemplate) won't find anything.

**Expected behavior**
The content should show without having to import SharedModule, because this module seems to be used only within the Prime components, devs should probably not use it.

**Minimal reproduction of the problem with instructions**
Make a very minimal App, install primeng, import MessagesModule in app.module.
Add in your template the static messages :
```html
<p-messages severity="info">
    <ng-template pTemplate>
        <div class="ml-2">Always bet on Prime.</div>
    </ng-template>
</p-messages>
```

Solve the issue with import :
```typescript
imports: [
    // this module should be imported in MessagesModule >> pTemplate directive
    SharedModule
]
```
You can also import any other module that imports SharedModule, like CardModule.

**What is the motivation / use case for changing the behavior?**
Not to interfere with SharedModule.

**Please tell us about your environment:**
Windows 10, NodeJs 14, Angular 13, PrimeNg 13

* **Angular version:** 13.X

* **PrimeNG version:** 13.X

* **Browser:** [ Chrome evergreen ]

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by kdwilich** [comment]
@mertsincan This is still an issue. The MessageModule needs to import and export the SharedModule for the static message template to work. The only reason the static message example in messagesdemo.html is working is because the messagesdemo.module.ts is importing the TabViewModule, which imports/exports SharedModule. This is how all of the other components using the PrimeTemplate directive are handling it.

Uncomment the TabViewModule import in app.module.ts to see the static message template load: https://stackblitz.com/edit/rhn1up-3zy9be?file=src%2Fapp%2Fapp.module.ts

**Comment by kdwilich** [comment]
@aboudard primeng@16.3.1

**Comment by kdwilich** [comment]
@aboudard Can you reopen this issue or does it need to be recreated?

**Comment by aboudard** [comment]
Sorry for the delay @kdwilich , I'll check that right away and reopen if needed !
