### ISSUE TITLE
Column filter event is emitted even though user does not click Apply button

### ISSUE THREAD

**Issue by sanket-thotange** [primefaces/primeng#11585]
**Question**

When lazyLoad is set as true, there are events related to filter, sort, pagination when gets emitted as onLazyLoad.

What I observed was, when we add new rule in column filter, it also emits the onLazyLoad event.
My expectation is when lazyLoad is set to true, this event should not get emitted until user clicks on Apply or Clear button.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
