### ISSUE TITLE
InputNumber control should allow increment or decrement value using mouse wheel

### ISSUE THREAD

**Issue by Balagii** [primefaces/primeng#11582]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
InputNumber control should allow increment/decrement using mouse wheel. (Similarly how Chrome browser handles the same thing in dev tools > Elements tab > Styles tab > numeric style properties, when the number is selected.)

**Current behavior**
Control does not trap mouse wheel input; it lets the page scroll.

**Expected behavior**
Control should trap and respond to mouse wheel input, but only when cursor hovers inside control's visible input area. One click up should increment input's numeric value by 1, one click down of the mouse wheel should decrement control's value by the same amount.

**Minimal reproduction of the problem with instructions**
n/a

**What is the motivation / use case for changing the behavior?**
Chrome's implementation is slick; it would be nice for PrimeNg to follow suit.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
