### ISSUE TITLE
p-dropdown: Not Changing my Values 

### ISSUE THREAD

**Issue by Queenferno** [primefaces/primeng#11594]
### Describe the bug

I have a templated p-dropdown that I'm binding to a FormGroup item. In the beginning, the FormGroup contains two drop-downs, one for the English and one for the Greek selected languages. Then I change the "Greek" into Romanian (taken from the "languages" collection) and enter "submit". Upon checking the values of my FormGroup, I see the previous English and Greek. No Romanian shown. For some reason the p-dropdown doesn't change my FormGroup's values. 

Here is my code: 

```
        <div class="display-block" *ngFor="let languagesFormGroup of languagesFormGroups; let i = index">
          <form data-qa="customEditorForm" [formGroup]="languagesFormGroup">
            <div class="form-item">
              <label class="form-label">Language {{ i + 1 }}</label>
              <!-- todo: needs testing -->
              <span class="language-management">
                <p-dropdown 
                  [styleClass]="'form-control'" 
                  [options]="languages" 
                  optionValue="languageID" 
                  formControlName="languageID" 
                  appendTo="body">
                    <ng-template let-item pTemplate="selectedItem">
                      <img src="{{item.icon}}"><span>{{item.name}}</span>
                    </ng-template>
                    <ng-template let-item pTemplate="item">
                      <img src="{{item.icon}}"><span>{{item.name}}</span>
                    </ng-template>
                </p-dropdown>
                <span class="icon-trash icon clickable" (click)="removeLanguage(languagesFormGroup)"></span>
              </span>
            </div>
          </form>
        </div>
```

And this is my Submit callback: 
```
  onSubmit(): void {
    this.languagesFormGroups.forEach(language => {
      //Should see English/Romaninan. Seeing the INITIAL English/Greek
      console.log(language.value); 
    });
  }
```

Is this a p-dropdown's bug? 

### Environment

Windows10 with Chrome

### Angular version

latest

### PrimeNG version

latest

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

latest

### Browser(s)

Chrome

### Steps to reproduce the behavior

I use my two dropdowns to change their values. The values do not change (upon hitting the `submit` button to check on the CHANGED (yeah right) values

**Comment by cetincakiroglu** [comment]
Hi @Queenferno,

Please provide a StackBlitz example for us by using;
https://stackblitz.com/github/primefaces/primeng-issue-template

**Comment by cetincakiroglu** [comment]
An example is not provided. Cannot replicate & closing the issue. If the problem exists, please re-open with StackBlitz example.
