### ISSUE TITLE
Add "Select parent only" & "Select children only" buttons to TreeSelect

### ISSUE THREAD

**Issue by sbouchex** [primefaces/primeng#11599]
### Describe the feature you would like to see added

TreeSelect do not allow to only select a single entry that has children : All children are also selected

In some cisconstance, it may be usefull select the entry only

### Is your feature request related to a problem?

No

### Describe the solution you'd like

Add 2 buttons on the rights: "Select the parent only" and "Select the children only"

![image](https://user-images.githubusercontent.com/2684878/172475792-3a549f4f-f16f-4e64-b215-7bd89b60f738.png)

### Describe alternatives you have considered

Don't know which one

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
