### ISSUE TITLE
Carousel: Default scroll behaviour for vertical scrolling

### ISSUE THREAD

**Issue by mbausche** [primefaces/primeng#11607]
### Describe the bug

We are using primefaces carousel to navigate through a list of items via swipe left/right on a mobile web page.

But swipe up/down to scroll page doesn't work over the carousel and because nearly all of the mobile's screen is covered with the carousel it's hard for the user to scroll down

How can we achieve to have both, carousel navigation with swipe left/right and page scrolling with swipe up/down?

(I you do a swipe down on the first carousel at the below mentioded stackblitz there is no scroll action)

We have tried to do what's proposed in https://stackoverflow.com/questions/62302234/cant-vertical-scroll-page-on-mobile-devices-with-full-width-primeng-carousel and added this to the constructor of our component:

`Carousel.prototype.onTouchMove = () => { };`

But after that we get the error 
```
ERROR in The target entry-point "primeng" has missing dependencies:
 - chart.js
```

### Environment

npm 6.13.4

### Reproducer

https://primeng-carousel-demo.stackblitz.io/

### Angular version

9.1.9

### PrimeNG version

9.1.3

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

10.18.1

### Browser(s)

Chrome

### Steps to reproduce the behavior

load stack blitz
switch to mobile view
swipe up/down on first carousel

### Expected behavior

Page  is scrolling up/down while vertically swiping on the carousel

**Comment by mbausche** [comment]
The scrolling is working if we do the following

- In AppComponent (constructor) `Carousel.prototype.onTouchMove = () => { };`
- `import {Carousel} from 'primeng/carousel';` **Important:** `import {Carousel} from 'primeng'; is not  working
- If the error  `in The target entry-point "primeng" has missing dependencies: - chart.js` occurs do a `npm run start`

**Comment by Rockstar311** [comment]
A better solution will be

```
Carousel.prototype.onTouchMove = function (event: TouchEvent) {
            const touch = event.touches[0];
            const deltaX = touch.clientX - this.startPos.x;
            const deltaY = touch.clientY - this.startPos.y;

            if (Math.abs(deltaX) > Math.abs(deltaY)) {
               console.log('Horizontal move');
                if (event.cancelable) {
                    event.preventDefault();
                }
            } else {
                console.log('Vertical move');
            }
        };
```
