### ISSUE TITLE
Table: error when clicking outside of an open filter panel

### ISSUE THREAD

**Issue by g1thuser** [primefaces/primeng#11604]
### Describe the bug

If an angular app is embedded inside another HTML element, a filter panel is open and the user clicks outside of the area of the angular app an exception is thrown:

ERROR TypeError: element is null
    hasClass domhandler.ts:70
    isOutsideClicked table.ts:4632
    documentClickListener table.ts:4642
    decoratePreventDefault dom_renderer.ts:168
    Angular 2
        invokeTask
        onInvokeTask

The error is caused by assuming that the event target always has a parent in isOutsideClicked (see snippet below)

```
  isOutsideClicked(event): boolean {
        return !(this.overlay.isSameNode(event.target) || this.overlay.contains(event.target)
            || this.icon.nativeElement.isSameNode(event.target) || this.icon.nativeElement.contains(event.target)
            || DomHandler.hasClass(event.target, 'p-column-filter-add-button') || DomHandler.hasClass(event.target.parentElement, 'p-column-filter-add-button')
            || DomHandler.hasClass(event.target, 'p-column-filter-remove-button') || DomHandler.hasClass(event.target.parentElement, 'p-column-filter-remove-button'));
    }
```

### Environment

see stackblitz

### Reproducer

https://primeng-tablefilter-demo-mmfyd4.stackblitz.io/

### Angular version

13.0.3

### PrimeNG version

13.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

x.x.x

### Steps to reproduce the behavior

1. Open any filter panel
2. Click below the black frame

=> error is shown in the browser console

### Expected behavior

No error.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
