### ISSUE TITLE
Topbar: Dropdown arrow in the list of versions anchor tag

### ISSUE THREAD

**Issue by vinnyab28** [primefaces/primeng#11602]
### Describe the feature you would like to see added

![Screenshot 2022-06-08 at 2 21 39 PM](https://user-images.githubusercontent.com/20514620/172575044-7511dc22-3d3d-4187-a189-42fcba6d92a6.png)

The versions on in the topper seem just like a selected version instead of signifying the user that it's a dropdown and the version can be changed.

To make the user more understandable, an angled-down-arrow would be much appreciated just like we have for the dropdown

### Is your feature request related to a problem?

The versions on in the topper seem just like a selected version instead of signifying the user that it's a dropdown and the version can be changed.

### Describe the solution you'd like

To make the user more understandable, an angled-down-arrow would be much appreciated just like we have for the dropdown

### Describe alternatives you have considered

Use [`p-dropdown`](https://www.primefaces.org/primeng/dropdown) instead

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
