### ISSUE TITLE
Calendar property "defaultDate" not working properly

### ISSUE THREAD

**Issue by dimassion** [primefaces/primeng#11608]
### Describe the bug

UTC date is Wednesday, June 8, 2022
My computer settings is Date&Time: Time zone is Fiji  date is Thursday, June 9, 2022

Try to highlight current date from UTC: this.defaultDate = this.dateTimeService.getDateAtMidnight();
<p-calendar [defaultDate]="defaultDate"

Expected result: June 8
Actual result: June 9

P.S. try to fix the method:  createMonth(month: number, year: number) {
let today = new Date();
but should be like 
let today = this.defaultDate || new Date();

### Environment

dev

### Angular version

11.2.11

### PrimeNG version

13.4.1

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

12.22.12

### Browser(s)

Chrome

### Steps to reproduce the behavior

UTC date is Wednesday, June 8, 2022
My computer settings is Date&Time: Time zone is Fiji  date is Thursday, June 9, 2022

Try to highlight current date from UTC: this.defaultDate = this.dateTimeService.getDateAtMidnight();
<p-calendar [defaultDate]="defaultDate"

Expected result: June 8
Actual result: June 9

P.S. try to fix the method:  createMonth(month: number, year: number) {
let today = new Date();
but should be like 
let today = this.defaultDate || new Date();

### Expected behavior

Expected result: June 8
Actual result: June 9

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
