### ISSUE TITLE
Component: Datatable - column filtering does not find all values when column data is formatted

### ISSUE THREAD

**Issue by edjm1971** [primefaces/primeng#11605]
### Describe the bug

Working on a project where values are passed to the datatable.
For example I'm using latitude and longitude values.
The data may look like this which is passed in.
`{
      "latitude": 02.61149634482493,
      "longitude": -016.171025955780882
}`

However, the values for the above would be formatted for the column entry which would look like this.
2.6115
16.171

A user would expect to use the column filter specifying
e.g. "STARTS WITH" : 2
Doing this filter results in 0 records.
User would need to do a filter in the column filter of "BEGINS WITH" : 02, but they never would being that they don't know of the leading 0 being omitted.
The same is true with the "ENDS WITH" column filtering
e.g. "ENDS WITH": 15 will not find the record, you would need to do
e.g. "ENDS WITH": 93 to find the display value of 2.6.115, this makes no sense to a user.

### Environment

Linux / Windows development environment.
Using VSCode

### Angular version

11.x

### PrimeNG version

11.4.x

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

12.22.11

### Browser(s)

Linux Chrome

### Steps to reproduce the behavior

Create a basic datatable using the data I provided and filter the view in the column to drop leading zeros and set the max numbers to 6 digits.

Then try and filter on Starts|Ends With.

Matches will not be found.

### Expected behavior

I would expect the filtering to filter based on what is visible to the user and not some value that is unknown to the user.

*** Updates ***********************
This is a problem in general for any type of filtration that occurs. Here is another example.

If this is your raw data
xyz12345678

And you were to format the raw value to display as 
#123456
The following unexpected issues are now present

- A search for all values with the # would result in 0 records found
    This is awkward to a user why nothing shows when clearly in the display the value is there in the datatable.
- A search for any of the values 7, 8, 78 would result in a match
    This is awkward to a user why a match shows when clearly in the display the value does not match but the raw data that the user does not know of contains the value.
- Things get a bit more complex if dealing with objects and number and lets say your display truncates a number and rounds the value. Now that the value 12345678 has been truncated and rounded you are left with 123457.
    Searching for the value 57 would not find any matches despite it being right there in the face of the user who is not aware of the raw data values and that the value was altered in the display to round the value up.

**Comment by edjm1971** [comment]
I put together a demo of this issue on StackBlitz.

The 2 columns to pay attention to are the YEAR and VIN.
Both fields contain in their raw data leading values which I have filtered out from the table display.
The YEAR uses the built in Starts With.
The VIN uses a custom filter for Starts With Custom Filter

https://stackblitz.com/edit/primeng-filterservice-demo-guymyn?file=src/app/app.component.ts

**Comment by edjm1971** [comment]
I'm working on something that would be configuration based on how things get formatted for the display but also being able to apply that exact same configuration to a generic method that will process the raw data when the configuration exists in order to format the data so that it will find what has been rendered.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
