### ISSUE TITLE
Dropdown: Allow the label to be selectable

### ISSUE THREAD

**Issue by davisb10** [primefaces/primeng#11609]
### Describe the feature you would like to see added

I would like to be able to click & drag inside the dropdown to be able to select the text label of the selected value.

### Is your feature request related to a problem?

A majority of our dropdowns contain contact names. Our users would like to be able to quickly select the label to be able to paste it into a different place.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
