### ISSUE TITLE
Calendar.ts need fix by this small peace of code

### ISSUE THREAD

**Issue by nexxoft** [primefaces/primeng#1161]
In version rc1, in file calendar.ts in line 32 position 91 need past this code:
, 'position': 'absolute'

finally line 32 must be like this:
[ngStyle]="{'display': inline ? true : (overlayVisible ? 'block' : 'none'), 'position': 'absolute'}" (click)="onDatePickerClick($event)" [@overlayState]="inline ? 'visible' : (overlayVisible ? 'visible' : 'hidden')">

without position:absolute space around calendar expanding instead overlaying

**Comment by cagataycivici** [comment]
I don't understand, position is not defined inline, it is defined at css classes;

.ui-datepicker.ui-datepicker-inline {
      position: static;
}
or

.ui-datepicker {
   position: absolute;
}

It is currently;

```
[ngStyle]="{'display': inline ? 'inline-block' : (overlayVisible ? 'block' : 'none')}"
```

**Comment by nexxoft** [comment]
Yes, its correct - in style calendar.css exists "position: absolute;".
But overload in other file css. We modified our file css and then work correct.
Sorry, it was our misstake.

**Comment by upmauro** [comment]
Problem solved, right @nexxoft ?
