### ISSUE TITLE
PrimeNG component animation trigger warnings since updating Angular to 14.x

### ISSUE THREAD

**Issue by nicholas-ochoa** [primefaces/primeng#11617]
### Describe the bug

Since updating my project to Angular 14, I've seen a number of animation trigger warnings in the console when running my application. For example when using a `p-panel` component:

```html
<p-panel [showHeader]="false">testing</p-panel>
```

I see the following in my console:

```
The animation trigger "panelContent" has built with the following warnings:
 - The following provided properties are not animatable: overflow
   (see: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_animated_properties)
```

Which seems to come from:
https://github.com/primefaces/primeng/blob/c9b61ffa107a7a59db3a4f55eb1a3353fb6eb9df/src/app/components/panel/panel.ts#L40-L56

Obviously not a huge issue, but reducing any additional noise in the console is always useful.

### Environment

Angular 14.0.1
PrimeNG 13.4.1

### Angular version

14.0.1

### PrimeNG version

13.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.15.0

### Browser(s)

Chrome 102

**Comment by davidmccoy-8451** [comment]
Seeing the same behavior.

**Comment by mountpoint** [comment]
It relates also to `p-messages` and `p-accordionTab` components. 
I think there are much more components with this warning.

And yes, this warning appeared after updating to Angular 14

**Comment by sthompson-celerity** [comment]
This should not be closed as it is still happening on accordionTab
