### ISSUE TITLE
Likely bad comparision in ObjectUtils.findIndexInList

### ISSUE THREAD

**Issue by Canos** [primefaces/primeng#11614]
### Describe the bug

ObjectUtils.findIndexInList functions expects objects and i using == as comparator.

Probably this == is not the right operator to use with objects.

### Environment

Angular app

### Angular version

12.2.24

### PrimeNG version

12.2.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

not related

### Steps to reproduce the behavior

Try to initialize a default list in an OrderList component.

// not initialize the orderlist 
this.selectedElements = [{name:'Product', value:'product'}]

// working (initialize the orderlist properly)
this.selectedElements = this.options.filter(p => p.value =='product');

### Expected behavior

Should be easier to initialize selected elements in a orderlist component

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
