### ISSUE TITLE
p-fieldset flickers when it's initialized collapsed [13.4.1]

### ISSUE THREAD

**Issue by doc-code-hub** [primefaces/primeng#11610]
### Describe the bug

#9179 An old trouble comes back!

The video in the description of linked issue show my problem just perfect.

> When p-fieldset component is added to DOM in collapsed state (with [collapsed]="true"), it shows its content for a brief moment, this is what makes it flicker.
> I have it collapsed by default on one of the pages, and it flickers when you route on that page.

Not sure when the problem came back... From the issue i see was solved when the major was v10 (as in the linked issue)

### Environment

WSL with Ubuntu-22.04

### Angular version

13.3.5

### PrimeNG version

13.4.1  (was there also in the 13.3.3)

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14.0

### Browser(s)

Chrome

### Expected behavior

When collapsed, the state should be that one from the beginning.

**Comment by doc-code-hub** [comment]
Somehow, trying to replicate my problem on stackbliz, all is working fine... (i've tryied different primeng v13 versions but nothing...)

I guess maybe it's also related with the content or the context of where i'm using the p-fieldset.

I have:
- Main fieldset
         > Several Fieldsets
                    >> Some Inputs of different type in each one
_And my component use ChangeDetectionStrategy.OnPush_

I will try to replicate the wrong behaviour i get and i'll be back to post it here!

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
