### ISSUE TITLE
p-Table not exporting text:  ",=cmd|' /C calc'!A0  correctly - security issue

### ISSUE THREAD

**Issue by waratah** [primefaces/primeng#11618]
### Describe the bug

The p-table exports the CSV file however it fails to escape double quotes correctly.  This has led to a security report on our system as the penetration expert pasted 

",=cmd|' /C calc'!A0

into one of our fields.  In new excel this will flag as an error.  In my opinion it is a total bug on Excel letting commands be imported at all howerver the base issue is the double quotes are not doubled.

output

...,"",=cmd|' /C calc'!A0",....

correct output
...""",=cmd|' /C calc'!A0",....

The important thing is the three double quotes on the second output rather than the two double quotes produced in version 13.1.2.

### Environment

Windows 
Chome
Angular 13 early upgrade code.

### Angular version

13.0.2

### PrimeNG version

13.1.2

### Build / Runtime

Angular CLI App

### Language

ES6

### Node version (for AoT issues node --version)

14.18.2

### Browser(s)

chrome

### Steps to reproduce the behavior

Paste the following into a text field:

",=cmd|' /C calc'!A0

create a table where above is one of the columns.

Export to CSV output.

Open in Excel latest -  security advisory that there is executable code.

output in CSV is as follows

...,"",=cmd|' /C calc'!A0",....

### Expected behavior

output should be as follows:

...""",=cmd|' /C calc'!A0",....

When opening above it will appear as harmless text in excel.

Note that current example has two double quotes and correct example has three double quotes.   to escape a double quote you put two into the data.

**Comment by waratah** [comment]
Issue is with this code:

  if (cellData != null) {
            if (this.exportFunction) {
              cellData = this.exportFunction({
                data: cellData,
                field: column.field,
              });
            } else cellData = String(cellData).replace(/"/g, '""');
          } else cellData = '';
          
          
          We should not expect the client to double quote the output
          
            if (cellData != null) {
            if (this.exportFunction) {
              cellData = this.exportFunction({
                data: cellData,
                field: column.field,
              }).replace(/"/g, '""');
            } else cellData = String(cellData).replace(/"/g, '""');
          } else cellData = '';

**Comment by waratah** [comment]
Note the above fix gave me an error that replace is not a function.  Therefore the same error probably exists in the non export functionality.   I tweaked my export function to always return a string so it was a non issue for me.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
