### ISSUE TITLE
"DialogService" (primeng/dynamicdialog) Issue.

### ISSUE THREAD

**Issue by mitul-projecttree** [primefaces/primeng#11632]
### Describe the bug

Open dialog using DialogService then click on **Spacebar or Enter**.
**Duplicate dialog will be created in system**

I check only two keys spacebar and enter from keyboard.
no idea about other keys of keyboard.

checkout in below link.
https://www.primefaces.org/primeng/dynamicdialog

https://user-images.githubusercontent.com/92772860/174224146-d988850b-f9c8-44f6-aca2-3d1dce11e6cf.mp4

### Environment

I'm an developer.

### Angular version

~12.1.1

### PrimeNG version

^12.0.0

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

^12.11.1

### Browser(s)

all

### Steps to reproduce the behavior

1. open dialog using Dynamic Dialog
2. without any action click on spacebar or enter key from keyboard.

https://user-images.githubusercontent.com/92772860/174224558-1d753592-be8f-4015-ae4b-2dc8ee4f5001.mp4

### Expected behavior

do not want duplicate dialog and it's wrong from developing pupose.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by mitul-projecttree** [comment]
still there is an issue.
i upload latest video of latest version of primeng

https://user-images.githubusercontent.com/92772860/200998563-50fd79a7-b565-4563-a88c-752dfc50a5db.mp4

**Comment by venkata82** [comment]
I too have same issue with V13.4.1

**Comment by shayan-ghzl** [comment]
i have fixed this problem 
https://github.com/primefaces/primeng/pull/12703

**Comment by mehmetcetin01140** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.
