### ISSUE TITLE
Issue with sorting dynamic column

### ISSUE THREAD

**Issue by iaakash** [primefaces/primeng#11636]
So i've got p-table with dynamic column setup and trying to put sorting on top of it. After adding pSortableColumn as mentioned here: https://www.primefaces.org/primeng/table/sort and clicking on header it gives error:
**Cannot assign to read only property '0' of object '[object Array]'** 

```
<p-table [columns]="cols" [value]="data" responsiveLayout="scroll">
      <ng-template pTemplate="header" let-columns>
        <tr>
          <th *ngFor="let col of columns" [pSortableColumn]="col.field">
            {{ col.header }}
            <p-sortIcon [field]="col.field"></p-sortIcon>
          </th>
          <th>Amount</th>
          <th *ngIf="userDetails?.role !== 'Player'">Action</th>
        </tr>
      </ng-template>

      <ng-template pTemplate="body" let-rowData let-columns="columns">
        <tr>
          <td *ngFor="let col of columns">
            {{ rowData[col.field] }}
          </td>
          <td class="amount">
            {{ rowData['formattedOrderTotal'] }}
            <ng-container *ngIf="rowData['isRefundExist']">
              <br />
              <i class="fa-solid fa-envelope-open-dollar"></i> &nbsp;
              <span>This transaction has a refund applied.</span>
            </ng-container>
          </td>
          <td class="refund" *ngIf="userDetails?.role !== 'Player'">
            <button (click)="openRefundModal(rowData['accountTransactionId'])">
              <i class="fa-solid fa-circle-info"></i>
            </button>
          </td>
        </tr>
      </ng-template>
    </p-table>
```
Any help would be highly appreciated

**Comment by gpanainte** [comment]
We have the same issue

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by GusBeare** [comment]
I am having the same issue with sort but I'm not using dynamic cols ( I thought that might be the issue). I think it's due to the way I am populating the table. Date filter is broken as well (may not be same issue).  Using latest 13.1.

My data comes from a store using ngRx.

    ngOnInit(): void {
        this.receipts$ = this.store.select(fromReceipts.selectReceipts);

**Comment by danirupe** [comment]
@GusBeare same issue here. Were you able to fix it?
