### ISSUE TITLE
Panel doesn't have some styles in a 13.4.1

### ISSUE THREAD

**Issue by Relaximus** [primefaces/primeng#11642]
https://github.com/primefaces/primeng/blob/6aa888c9b7937185cad973177031922ee23d16a0/src/app/components/panel/panel.css#L21

I might be missing something, but in the latest primeng@13.4.1 in the 
`node_modules/primeng/resources/components/panel/panel.css`
I see only:

```
.p-panel-header {
    display: flex;
    align-items: center;
}

.p-panel-title {
    line-height: 1;
    order:1;
}

.p-panel-header-icon {
    display: inline-flex;
    justify-content: center;
    align-items: center;
    cursor: pointer;
    text-decoration: none;
    overflow: hidden;
    position: relative;
}
```
Because of that after updating to the newer version some our panels were broken.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
