### ISSUE TITLE
PickList: Disable sorting via drag&drop

### ISSUE THREAD

**Issue by infe42** [primefaces/primeng#11644]
### Describe the feature you would like to see added

The PickList allows to hide the source and target controls which are used to sort the lists (with showSourceControls and shotTargetControls). If drag & drop is enabled, you can still sort the lists even if the controls are hidden.

I suggest to disable the sorting of the source or target lists via drag & drop when the respective sort controls are not shown.

### Describe the solution you'd like

This could easily be achieved by adding [cdkDropListSortingDisabled]="..." to #sourcelist and #targetlist. I can provide a PR if you're interested.

### Describe alternatives you have considered

An alternative solution would be to provide to additional properties to disable sorting via drag & drop on the source or target lists, e.g. disableDragdropSourceReorder and disableDragdropTargetReorder.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
