### ISSUE TITLE
Table: rowspan issue when the table is frozen and scrollable

### ISSUE THREAD

**Issue by bdi-gud** [primefaces/primeng#11640]
### Describe the bug

There is an issue with the rowspan attribute when the table is scrollable and frozen. The horizontal scroll breaks the layout for the forzen columns.

After debug it seems that the rowspan is ignored and the calculation of the left property is wrong for the second line.

### Environment

![image](https://user-images.githubusercontent.com/83651463/174553483-9c93ae5c-2ae0-4b56-ab2d-d497fb91888e.png)

### Reproducer

https://stackblitz.com/edit/primeng-tableselection-demo-712q71?file=src%2Fapp%2Fapp.component.html

### Angular version

13.0.3

### PrimeNG version

13.0.4

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.10.0

### Browser(s)

Chrome 102

### Steps to reproduce the behavior

Use the horizontal scroll. The second line of the header will ignore the rowspan and overflow the cell.

### Expected behavior

The second line of the header should take the rowpan in condsideration.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
