### ISSUE TITLE
Cannot manually set the date in Calendar when dataFormat is "mm/yy"

### ISSUE THREAD

**Issue by cesarrew** [primefaces/primeng#1164]
When I try to enter the date manually in Calendar (only typing) when dataFormat is "mm/yy", the date is not setted.

**Comment by cesarrew** [comment]
Code sample:

`<p-calendar [(ngModel)]="accountPlan.period" dateFormat="mm/yy"></p-calendar>`

**Comment by bogdanvaduva** [comment]
I have a similar problem when I am setting the date within the program. 
I solved the issue by adding ngDoCheck 
    Calendar.prototype.ngDoCheck = function () {
        if (!this.inline) {
            this.updateInputfield();
        }        
    };

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/VZbdZfQ7SuTV87tTkbYR
