### ISSUE TITLE
Range Slider: Model styles not applying correctly when clicking

### ISSUE THREAD

**Issue by portiaove** [primefaces/primeng#11646]
### Describe the bug

Instead of dragging, when clicking on the bar styles are not applied correctly to the `<span class="p-slider-range ng-star-inserted" style="left: minValue%; width: maxValue%">` element containing the styles for the range.

It updates correctly in the `<p-slider ng-reflect-model="minValue, maxValue">` parent element, but seems to not update its child element so they get unsync.

<img width="473" alt="image" src="https://user-images.githubusercontent.com/46445026/175023058-8434316d-e6fe-46f3-b1a8-1c55017bcb6a.png">

### Environment

Local development mode running `npm run start`

### Angular version

12.2.13

### PrimeNG version

13.0.2

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

12.16.2

### Browser(s)

Chrome

**Comment by volvachev** [comment]
Could you create an example on Strackblitz?

**Comment by portiaove** [comment]
Hi @volvachev I'm trying but can't seem to find the way (not used to stackblitz)... Seems the importing is right, and the elements appear through the console but it doesn't appear on the viewport
https://stackblitz.com/edit/angular-11-material-reactive-starter-ijpicf?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html

**Comment by volvachev** [comment]
Hi, you should add styles from the library to `angular.json`

```
"node_modules/primeng/resources/themes/saga-blue/theme.css",
"node_modules/primeng/resources/primeng.min.css",
"node_modules/primeicons/primeicons.css"
 ```

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
