### ISSUE TITLE
p-tree : wrong node selected with virtualScroll and filter

### ISSUE THREAD

**Issue by juberger** [primefaces/primeng#11641]
### Describe the bug

A p-tree with virtualScroll=true, filter=true and selectionMode=single. Using onNodeSelect output.

If I select any node in the tree without filter, the right node is send to the onNodeSelect.

![tree_select_1](https://user-images.githubusercontent.com/6807269/174749783-86e620c6-f9e0-4ab6-a775-944f572b3168.PNG)

If I filter the tree (with "Node1" for example) and select the node "Node 1.0" in the tree, The node "Node 0" is send to onNodeSelect instead of "Node 1.0".

![tree_select_2](https://user-images.githubusercontent.com/6807269/174749909-73b770f3-7082-4d95-bfe8-d47fb63fe1fd.PNG)

In général if the virtualScroll is activated and the tree is filtered, the selected node is still the first node of the tree.

### Environment

Project Angular 12.2.16 with PrimeNG 12.2.2

Also tested with PrimeNG 13.4.1 (stackblitz below)

### Reproducer

https://stackblitz.com/edit/primeng-treescroll-demo-5m3kbt?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

### Angular version

12.2.16

### PrimeNG version

12.2.2

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

14.17.0

### Steps to reproduce the behavior

1. Active virtualScroll, filter and selectionMode=single for p-tree
2. Add a method for onNodeSelect to trace the node selected
3. filter the tree to reduce the displayed nodes
4. select an other node than the first one in the tree
5. the trace of the onNodeSelect method display the first node of the tree

**Comment by mertsincan** [comment]
Hi,

You need to add an unique key option to your custom node. Please try;
```
createNode(i: number, children: number): TreeNode {
    let node: TreeNode = {
      key: 'Key' + i, 
      label: 'Node ' + i,
      data: 'Node ' + i,
      expandedIcon: 'pi pi-folder-open',
      collapsedIcon: 'pi pi-folder',
      children: Array.from({ length: children }).map((_, j) => {
        return {
          label: 'Node ' + i + '.' + j,
          data: 'Node ' + i + '.' + j,
          icon: 'pi pi-file-o',
        };
      }),
    };

    return node;
  }
```
Best Regards,
