### ISSUE TITLE
How to create a responsive menu like in primeng page?

### ISSUE THREAD

**Issue by mrgoos** [primefaces/primeng#1165]
Hi,
How can I create from primeNG components, a responsive menu that will behave the same as in your website?
Meaning a hamburger menu when the screen becomes smaller etc?
Thanks.

**Comment by cagataycivici** [comment]
Please use forum for questions. You need to use media queries.

http://forum.primefaces.org/viewforum.php?f=35

**Comment by lucashv** [comment]
Shit answer
