### ISSUE TITLE
Reimplement virtual scroll feature on AutoComplete

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primeng#11659]
Using Scroller API. The `cdk-virtual-scroll` API has been removed.

New Attributes;
- [x] virtualScrollOptions
- [x] virtualScrollItemSize
- [x] lazy

New Events;
- [x] onLazyLoad

New Templates;
- [x] loader

**Comment by mcrtricolor** [comment]
I'm having an issue with virtualScroll, te autocomplete not always show the suggestions, especially if the input is dirty. If I autocomplete on focus it works well. (using 15.1.1 version)

Does it has something to do with this reimplementation? Thanks in advance.
