### ISSUE TITLE
Table Summary / Aggregate Functions

### ISSUE THREAD

**Issue by davisb10** [primefaces/primeng#11667]
### Describe the feature you would like to see added

Ability to have a native aggregate / summary section added to the table, similar to
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/summaries

Additional feature to that would be to have the different types shown from a popout box like it does with filter where users are able to pick which of the aggregate functions they would like to see shown on the bottom.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
