### ISSUE TITLE
Calendar: Presetted Ranges

### ISSUE THREAD

**Issue by serdartaylan** [primefaces/primeng#11674]
### Describe the feature you would like to see added

We need to be able to set preset intervals to improve user experience. For example: Last 7 Days, Last Month, Last Year, Next Year etc.

### Describe alternatives you have considered

https://ng.ant.design/components/date-picker/en#components-date-picker-demo-presetted-ranges

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by yelhouti** [comment]
@serdartaylan or @mertsincan could you please reopen this. Thanks

**Comment by serdartaylan** [comment]
> @serdartaylan or @mertsincan could you please reopen this. Thanks

@mertsincan

**Comment by serdartaylan** [comment]
reopen.
