### ISSUE TITLE
Component: DynamicDialog

### ISSUE THREAD

**Issue by demike** [primefaces/primeng#11671]
### Describe the feature you would like to see added

the **position** option like present in  p-dialog would be very handy for dynamic dialogs too.

### Is your feature request related to a problem?

I wanted to position a dynamic dialog like I was used to with p-dialog

### Describe the solution you'd like

add the position option to DynamicDialog

### Describe alternatives you have considered

alternatively add
**maskStyleClass** (also present in p-dialog) to the options of DynamicDialog.
this would allow setting i.e.: "p-dialog-bottom" class on the mask. 
And that in turn would have the same effect as the position option

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
