### ISSUE TITLE
Component: Title p-dialog move incorrectly when using scroll

### ISSUE THREAD

**Issue by stealman364** [primefaces/primeng#11679]
### Describe the bug

all the pdialog after opening them and using scroll stays hooked at the bottom as if they could not move vertically happens in all versions higher than 10 (included)

### Environment

it happens on your main page too and can be reproduced from the web
https://www.primefaces.org/primeng-v10-lts/#/dialog

![image](https://user-images.githubusercontent.com/18161229/177289677-f7acc852-3a61-4051-bd09-46f2eaee5d49.png)

once used the scrol with the p-dialog is open you can not move the p-dialog vertically

![image](https://user-images.githubusercontent.com/18161229/177290062-8658382b-5118-4df9-aefb-3c2adac09018.png)

### Angular version

^10.0.0

### PrimeNG version

^10.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.0.4

### Browser(s)

all

### Steps to reproduce the behavior

open url
https://www.primefaces.org/primeng-v10-lts/#/dialog
press the show button (basic)
Once the p-dialog is opened without closing it.
 scroll down on the screen and it will no longer be possible to move vertically.
 
![image](https://user-images.githubusercontent.com/18161229/177291219-a0c50131-440c-46ee-97aa-b5ed308c1fd3.png)

### Expected behavior

Be able to move it vertically

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
