### ISSUE TITLE
p-steps: p-steps-complete and p-steps-incomplete class has been removed from primeng  version 11

### ISSUE THREAD

**Issue by chaitrashenoy33** [primefaces/primeng#11670]
### Describe the bug

in p-steps completed and incompleted steps should have different styles just to differentiate between them. .It was possbile with primeng9  version with **ui-steps-incomplete  and ui-steps-complete** classes. but after migrating to 11 these classes have been removed. is there any alternate way we could do this?

### Environment

Windows 10

Angular version: Angular 11

PrimeNG version: 11.4.5

node: 16.10

### Angular version

11

### PrimeNG version

11.4.5

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

16.10

### Steps to reproduce the behavior

![steps](https://user-images.githubusercontent.com/37924470/176668746-fed1af08-b150-416c-ad26-bb31fa1277c0.PNG)

go to p-steps and try to click next in steps . so that it shifts from step1 to step2, step2 to step3 etc

### Expected behavior

if the user  completes step1 and goes to steps2
step1(that is already completed should have some colors ie color1, background1 )
active one should have color2, background2
step3 ie next steps (incomplete one's) should have color3, background3
![stepsExpcted](https://user-images.githubusercontent.com/37924470/176670088-2bae6b84-3bbb-4599-a606-7486d8b2425b.png)

**Comment by sridhark158** [comment]
+1

**Comment by krchandan301** [comment]
I am also facing same issue.

**Comment by kiranredddy** [comment]
we are also facing the same issue please Anyone give me solution

**Comment by PrashanthThomas** [comment]
I faced this issue too, it would be good to add a class for elements after the active-element and another class for elements before the active-element.

**Comment by DevInder1** [comment]
+1

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by rugodata** [comment]
Was there any update on this? We are still unable to style completed steps
