### ISSUE TITLE
Component: prime-ng 14 p-panel collapsed

### ISSUE THREAD

**Issue by fensefernando** [primefaces/primeng#11687]
### Describe the bug

When set [collapsed]=true body doesn't hidden. On console describe style 

.p-panel-expanded .p-toggleable-content:not(.ng-animating) {
    overflow: visible;
}

This style, would be hidden

### Environment

I use primeng 14 

### Angular version

14

### PrimeNG version

14

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

v16.14.0

**Comment by yigitfindikli** [comment]
Fixed in https://github.com/primefaces/primeng/issues/11685
