### ISSUE TITLE
p-slider: In Range mode, the slider gets stuck if the range min value is equal or superior to the range max value

### ISSUE THREAD

**Issue by btournai** [primefaces/primeng#11682]
### Describe the bug

In the slider in range mode, if you define a max value different of the default value, when you move the start range control of the slider after the end range control , the slider crashes and display its end range to the infinity.

1. 
![image](https://user-images.githubusercontent.com/108737437/177330320-8b286110-b953-4851-b920-05c492e401aa.png)
 
2.
![image](https://user-images.githubusercontent.com/108737437/177330588-53761d59-8f28-46a7-9894-75318edbb155.png)

### Environment

Everywhere

### Reproducer

https://stackblitz.com/edit/github-b4kumc?file=src/app/app.component.html

### Angular version

13.3.8

### PrimeNG version

13.4.1

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

14.18.0

### Browser(s)

Chrome 103

### Steps to reproduce the behavior

1. Create a slider in range mode with min = 0, max = 1000 and ngModel = [20, 500]
2. Move the start range control after the end range control

**Comment by benjaminbekes** [comment]
Even if you specify the step input, it behaves buggy
![image](https://user-images.githubusercontent.com/29887220/183242549-70a7052f-6ab9-40ec-902b-27095342f48e.png)

**Comment by davidpawar** [comment]
Can confirm the same in our project.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by btournai** [comment]
Hi,
Thanks for your response.
The bug is still present on Prime NG 14.2.1. I open a new issue : #12175.
Best regards,
