### ISSUE TITLE
Component: p-calendar

### ISSUE THREAD

**Issue by Xample** [primefaces/primeng#11683]
### Describe the bug

`p-calendar` in "timeOnly=true" changes the date value to the current date if we enter the time manually.

### Environment

This is not related to the environment, check the [reproducer](https://stackblitz.com/edit/github-bpfldw?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts)

### Reproducer

https://stackblitz.com/edit/github-bpfldw?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

### Angular version

14.0.4

### PrimeNG version

14.0.0.-rc.1

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

v16.13.1

### Browser(s)

Chrome Version 103.0.5060.114 (Official Build) (arm64)

### Steps to reproduce the behavior

1. Create a timeonly p-calendar
```html
<p-calendar
[(ngModel)]=timestamp
[timeOnly]="true"
></p-calendar>
```
2. Create a component with the timestamp `timestamp = new Date("2000-01-01");` here it is initialized on the january 1st 2000.
3. Change the hour clicking on the p-calendar, type for instance "10:00" the timestamp will not be `2000-01-01T10:00` but someting like `2022-07-06T10:00` (simplified time for the example)

### Expected behavior

I expect p-calendar to keep the previous date. This is very likely due to the following line:
https://github.com/primefaces/primeng/blob/master/src/app/components/calendar/calendar.ts#L2289

i.e. every time we enter a time manually, a new date (and therefore a date of the current day) is created instead of cloning the current component's date (if any)

```typescript
        if (this.timeOnly) {
            date = new Date();
            this.populateTime(date, parts[0], parts[1]);
        }
```

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
