### ISSUE TITLE
p-table: In p-table with reorderableColumns = true, a column with pResizableColumnDisabled = true has column width permanently changed when reordering

### ISSUE THREAD

**Issue by GitHubStan** [primefaces/primeng#11693]
### Describe the bug

When a p-table is configured with [reorderableColumns]="true", and a source column is dragged to a target column, the source column inherits the width of the target column. If the source column has pResizableColumnDisabled = true, then after it is dropped and gets the width of the target column, its width cannot be changed.
 
The problem is exacerbated when column 2 is configured with pResizableColumnDisabled = true. In that case, the user is not able to resize the column back to a usable width.

### Environment

Angular and PrimeNg

### Angular version

13.0.3

### PrimeNG version

13.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.10.0

### Steps to reproduce the behavior

1. Configure a p-table with [reorderableColumns]="true"
2. Create column 1 with a certain width.
3. Create column 2 with a different width than column 1.
4. Drag column 2 in front of column 1.

### Actual Results
Column 2 gets the width of column 1.

The problem is exacerbated when column 2 is configured with pResizableColumnDisabled = true. In that case, the user is not able to resize the column back to a usable width.

### Expected behavior

Column 2 retains its width.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
