### ISSUE TITLE
OverlayPanel: Arrow Positioning

### ISSUE THREAD

**Issue by vinnyab28** [primefaces/primeng#11696]
### Describe the feature you would like to see added

When clicked on the OverlayPanel to display, the arrow for the panel is on the left of the `target`. 

### Is your feature request related to a problem?

I was using a button to display a tabular information in the overlay, which had a `chevron-down` icon on the right side of the label (Like a dropdown). But when opening the OverlayPanel, the arrow of the panel is on the left side of the `target` which was no in-line with the icon in the button.

### Describe the solution you'd like

Giving an option to let the user control the position of the arrow.

### Describe alternatives you have considered

Adding HTML content in tooltip. But a complex HTML with dynamic variables seemed extensive.

### Additional context

![image](https://user-images.githubusercontent.com/20514620/178105649-45af77f5-2279-4255-8d9c-0a7c43f468b5.png)

**Comment by LexanRed** [comment]
Generally speaking it would be great to define the alignment of any kind of dropdown / overlay. 

Whether it is a dropdown, multiselect, overlaypanel, confirm dialog. 

Settings like the following would ease development significantly:
- Orientation (bottom left, bottom right, top left, top right, right top, right bottom, left top, left bottom)
- Show arrow (true, false)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by Michael-Ziluck** [comment]
This was not completed and needs to be reopened @mertsincan
