### ISSUE TITLE
p-table with dynamic columns hides a half of the first row (14.0.0-rc1) 

### ISSUE THREAD

**Issue by arozdobudko-incomm** [primefaces/primeng#11699]
### Describe the bug

If primeng table has dynamic columns, it hides a half of the first row. I beleave it's because 'tbody' in a table has 'position: absolute' style. 

### Environment

OS: Windows 10

### Reproducer

https://stackblitz.com/edit/primeng-14rc1-ptree-bug-m3mbkh?file=src%2Fapp%2Fapp.component.ts

### Angular version

14.0.4

### PrimeNG version

14.0.0-rc1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14.2

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Open this example https://stackblitz.com/edit/primeng-14rc1-ptree-bug-m3mbkh?file=src%2Fapp%2Fapp.component.ts
2. Click 'add column' one or several times
3. Notice the first row in the table
![image](https://user-images.githubusercontent.com/93388416/178246278-44cc9760-eacd-40e4-8c4e-9d679faf392b.png)

### Expected behavior

 The first row in the table should be visible at full height.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
