### ISSUE TITLE
Unselect date event - p-calendar

### ISSUE THREAD

**Issue by LuisaRames** [primefaces/primeng#11692]
### Describe the feature you would like to see added

I have a selectionMode="multiple" calendar and I want to catch "deselect" dates. (onSelect) only works when selecting a date. Using ngModel it removes from the array, but I want to catch the event.

### Describe the solution you'd like

Create (onDeselect) or similar to catch a deselect date event from p-calendar when selectionMode="multiple"

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
