### ISSUE TITLE
Checkbox: Documentation error - Styling class typo fix

### ISSUE THREAD

**Issue by vinnyab28** [primefaces/primeng#11694]
### Describe the bug

According to the classes assigned to the elements are `p-checkbox-*` while in the documentation it is given as `p-chkbox-*`

![image](https://user-images.githubusercontent.com/20514620/178094923-53986999-e310-43db-bb76-3657d61b62b6.png)
![image](https://user-images.githubusercontent.com/20514620/178094967-969f5c03-0523-41a4-8b69-83526e084922.png)

### Environment

![image](https://user-images.githubusercontent.com/20514620/178094998-9af23976-940a-419f-9b3c-63326d820d25.png)

### Angular version

13.3.7

### PrimeNG version

14.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

16.15.0

### Browser(s)

Firefox 102.0.1 (64-bit)

### Expected behavior

Classes to be displayed in the document to be `p-checkbox-*`

**Comment by vinnyab28** [comment]
Also observed in other components with the similar typo.

1. [Radio Button](https://www.primefaces.org/primeng/radiobutton)
2. [TriStateCheckbox](https://www.primefaces.org/primeng/tristatecheckbox)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
