### ISSUE TITLE
Add readonly attribute on Input controls

### ISSUE THREAD

**Issue by jkumawat** [primefaces/primeng#117]
Hello Prime Team,

I would request you to add ready-only attribute on input controls if possible.

Disabled property is already implemented but disabled controls looks too much blur. 

Hope you guys implement in upcoming release.

Thank you for your quick implementation and support in forum.

**Comment by cagataycivici** [comment]
Thank you, we'll do it for sure.

**Comment by cagataycivici** [comment]
Issue is too common, we'll create a ticket for each one.
