### ISSUE TITLE
p-dropdown: onChange event is invoked even when you only navigate through the items

### ISSUE THREAD

**Issue by sameerthekhans** [primefaces/primeng#11703]
### Describe the bug

p-dropdown: `onChange` event is invoked even when you only navigate through the items, I am calling an API when this event is invoked and there are multiple unnecessary calls made.

### Why this is a bug?
There are multiple bugs already raised and not properly answered #8355, #5335, and #9864, quoting logical reasons from them below

> The problem is that value should only be changed on SELECTING a value, not while NAVIGATING with up/down arrow keys?

> this is a design flaw... dropdowns don't work this way. The user is free to "browse" the list before making a selection. A selection is made only by actively clicking on an item or pressing ENTER with the item highlighted.
> 
> The current implementation is very strange and non-intuitive.

> the onChange event of the p-dropdown component fires every time the user highlights a new item with the keyboard. This seems counterintuitive since merely highlighting a new item does not indicate the user actually intends to select it

> This ticket and My Issue - There are lots of unnecessary HTTP requests made because of this issue.

Lastly, I don't think people need the current behavior (ig)

### Environment

All, Stackblitz reproducer attached

### Reproducer

https://stackblitz.com/edit/primeng-dropdown-demo-5qswwf?file=README.md

### Angular version

13.0.3

### PrimeNG version

13.0.4

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

16.14.2

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Goto Stackblitz 2. Open console 3. Open the dropdown and navigate through items

### Expected behavior

`onChange` event should only emit when the user has selected the item and the dropdown overlay is closed

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
