### ISSUE TITLE
p-sortIcon does not update when set pSortableColumn does not match the display value

### ISSUE THREAD

**Issue by Leonardo-Olivo** [primefaces/primeng#11702]
### Describe the bug

The sort icon does not update according to the sort state when the pSortableColumn input value is not the same as the display value. The sorting itself is still working fine.
In the provided Reproducer I've created an example with the name column.

### Environment

This seems to happen on every environment.

### Reproducer

https://stackblitz.com/edit/primeng-tabledynamic-demo-sgzkfk?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fproduct.ts

### Angular version

12.2.11

### PrimeNG version

12.2.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.16.1

### Expected behavior

The sortIcon is supposed to update when the column is sorted in ascending/descending order.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
