### ISSUE TITLE
Tabbing problems by using p-steps nested in p-dialog

### ISSUE THREAD

**Issue by evelyscha** [primefaces/primeng#11709]
### Describe the bug

Hello,
I want to use the p-steps component and an input field in a p-dialog. The behavior should be such that when I tab through the p-dialog, first the active step, then the input element is triggered. But this does not work. The input element cannot be controlled.
Outside of a p-dialog the whole thing works.

### Environment

Used components:
- https://www.primefaces.org/primeng/dialog
- https://www.primefaces.org/primeng/steps/personal

### Angular version

^11.1.2

### PrimeNG version

^11.0.0

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

^12.11.1

### Browser(s)

ALL

**Comment by cetincakiroglu** [comment]
Hi,

Cannot replicate, please feel free to re-open with a StackBlitz example
