### ISSUE TITLE
bug: datatable filter function with lazy

### ISSUE THREAD

**Issue by lsa-shanghai** [primefaces/primeng#1170]
datatable.ts 
line: 524
if(this.hasFilter()) {
      this.filter();
}
When LazyLoadEvent fired, it will update the datatable's value and it will fire LazyLoadEvent in a circle.

**Comment by cagataycivici** [comment]
Same as #1145

**Comment by erkanerol** [comment]
I use     "primeng": "4.0.0-rc.2" and "@angular/core": "4.0.1". The bug still exists. The lazy load event is fired again and again when lazy=true. Should I check it in my code or set another parameter?

**Comment by AlexanderPruss** [comment]
+1. The bug still seems to be there in 4.0.0-rc.2.
