### ISSUE TITLE
Error: Binding to event property 'onLabel' is disallowed for security reasons, please use (Label)=... If 'onLabel' is a directive input, make sure the directive is imported by the current module.

### ISSUE THREAD

**Issue by theFasihTalha** [primefaces/primeng#11708]
### Describe the bug

i'am using karma jasmine to test a angular component and i'am getting this error with the p-toggleButton of primeng :

`Error: Binding to event property 'onLabel' is disallowed for security reasons, please use (Label)=...
If 'onLabel' is a directive input, make sure the directive is imported by the current module.`

it's about the " onLabel " property of primeng p-toggleButton
@cagataycivici can u help me plz

![unit test error](https://user-images.githubusercontent.com/69488447/178698962-7ee051e3-f89f-4460-a89e-959767fa6113.jpg)

### Environment

here is my package.json :
`"dependencies": {
    "@angular/animations": "~12.2.16",
    "@angular/cdk": "~12.2.13",
    "@angular/common": "~12.2.16",
    "@angular/compiler": "~12.2.16",
    "@angular/core": "~12.2.16",
    "@angular/forms": "~12.2.16",
    "@angular/localize": "^12.2.16",
    "@angular/platform-browser": "~12.2.16",
    "@angular/platform-browser-dynamic": "~12.2.16",
    "@angular/router": "~12.2.16",
    "@auth0/angular-jwt": "^2.1.0",
    "@fullcalendar/core": "^4.4.2",
    "@fullcalendar/daygrid": "^4.4.2",
    "@fullcalendar/interaction": "^4.4.2",
    "@fullcalendar/timegrid": "^4.4.2",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "@rxweb/reactive-form-validators": "^2.1.6",
    "assert": "^2.0.0",
    "bufferutil": "^4.0.1",
    "chart.js": "^3.7.1",
    "core-js": "^2.5.4",
    "crypto-browserify": "^3.12.0",
    "file-saver": "^2.0.2",
    "font-awesome": "^4.7.0",
    "https-browserify": "^1.0.0",
    "moment": "^2.29.3",
    "ng-sidebar": "^8.0.0",
    "os-browserify": "^0.3.0",
    "pdfmake": "^0.1.72",
    "primeflex": "^3.1.3",
    "primeicons": "^5.0.0",
    "primeng": "~12.2.0",
    "quill": "^1.3.7",
    "rxjs": "~6.6.7",
    "save": "^2.4.0",
    "sonar-scanner": "3.1.0",
    "stream-browserify": "^3.0.0",
    "tslib": "^1.9.0",
    "utf8": "^3.0.0",
    "xlsx": "^0.15.1",
    "zone.js": "~0.11.4",
    "next-tick": "~1.1.0"
  },`

### Angular version

12.2.17

### PrimeNG version

12.2.0

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

14

### Browser(s)

Chrome

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
