### ISSUE TITLE
P-Password display password scruffy icon

### ISSUE THREAD

**Issue by john182** [primefaces/primeng#11706]
### Describe the bug

icon misaligned when using a container with class "p-fluid"

![image](https://user-images.githubusercontent.com/10438644/178622313-ae21f160-fbf5-4e03-a9e5-072f147b0129.png)

### Environment

teste in example component 
https://www.primefaces.org/primeng

### Angular version

13.1.0

### PrimeNG version

13.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14.0

### Browser(s)

Chrome

**Comment by john182** [comment]
![image](https://user-images.githubusercontent.com/10438644/178615360-e5bf1a69-5e3e-420d-9283-245bbd7e5570.png)
![image](https://user-images.githubusercontent.com/10438644/178615382-230a4061-ebcb-48d2-aab4-47243f05db5c.png)

**Comment by john182** [comment]
Solution ?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
