### ISSUE TITLE
colspan has not effect in template groupheader and groupfooter -> PrimeNG Release 14.0.0-rc.1

### ISSUE THREAD

**Issue by eltigree** [primefaces/primeng#11705]
### Describe the bug

I have a table with scrollable, scrollheight and and template headergrouped. All works fine, but with the templates groupheader and groupfooter the colspan has no effect on the td tag....

### Environment

- PrimeNG Release 14.0.0-rc.1
- Angular Version 14.0.4

### Reproducer

https://stackblitz.com/edit/primeng-tablerowgroup-demo?file=src%2Fapp%2Fapp.component.html

### Angular version

14.0.4

### PrimeNG version

14.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

18.4.0

### Browser(s)

Firefox, Edge

### Steps to reproduce the behavior

in your stackblitz from your documentation, try to change the value of colspan -> no effect

problem is, that the cols are not synched with the headers (no nice for the users)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
