### ISSUE TITLE
pdialog: dismissableMask scroll cause dialog to close

### ISSUE THREAD

**Issue by sameerthekhans** [primefaces/primeng#11704]
### Describe the bug

For some reason, I need scroll outside the dialog, so I have changed the dialog's content to `overflow: visible` and added overflow scroll to the mask element, and when the user tries to scroll by pulling down the scrollbar, the dialog closes as I also have enabled `dismissableMask`.

I know what is causing that, [Here](https://github.com/primefaces/primeng/blob/1ae26948db66a51d3db153d69b73a93fc84b460b/src/app/components/dialog/dialog.ts#L357) we have `mousedown` event which is also triggered when clicked on the scrollbar.

I think `mousedown` is used to add support for touch devices? `click` also works fine in touch devices and the `click` event doesn't get triggered when the scrollbar is clicked

### Environment

All

### Reproducer

https://stackblitz.com/edit/primeng-dialog-demo-lw4qqo?file=src/app/app.module.ts

### Angular version

13.0.3

### PrimeNG version

13.0.4

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

16.14.2

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Goto stackblitz 2. Click on show button 3. Try to scroll by dragging the scrollbar

### Expected behavior

Dragging the scrollbar down should not close the dialog

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
