### ISSUE TITLE
Virtual scroll in grid view mode.

### ISSUE THREAD

**Issue by Raniabenkhalil** [primefaces/primeng#11700]
Hello,

I'm using dataview component and want to enable virtualScroll in both list and grid view. Is it possible using virtualscroller component or any other component ?
If there is a way , could you please provide me with an example or a how to.
Used versions:
Angular 12
Primeng 12.2.3

Many thanks.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
