### ISSUE TITLE
p-contextMenu: [triggerEvent]="'click'" menu not show after click (14.0.0-rc1)

### ISSUE THREAD

**Issue by aktet** [primefaces/primeng#11707]
### Describe the bug

If p-contextMenu override trigger Event for click event then menu not show (call hide after show immediately)

### Environment

mac os

### Reproducer

https://stackblitz.com/edit/angular-ivy-fqtxeh?file=src%2Fapp%2Fapp.component.html

### Angular version

14.0.5

### PrimeNG version

14.0.0-rc1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v17.9.0

### Browser(s)

chrome

### Steps to reproduce the behavior

click button , menu not show with primeng 14.0.0-rc1

### Expected behavior

it correct work on version 13.0.4
click button , menu is show 
[https://stackblitz.com/edit/angular-ivy-xclc1m?file=angular.json](https://stackblitz.com/edit/angular-ivy-xclc1m?file=angular.json)

**Comment by Xriuk** [comment]
Hi, wouldn't it be possible to integrate directly into the component without requiring to configure the button separately?
You already hook into the event so you could stop propagation, no?
