### ISSUE TITLE
p-table RowSpan Grouping does not work with [scrollable]=true

### ISSUE THREAD

**Issue by dcanning** [primefaces/primeng#11715]
### Describe the bug

when [scrollable] is set to true for a p-table, rowspan grouping does not work

### Environment

Angular version: 13.3.11
PrimeNG version: 13.4.1
Browser: Chrome/firefox

### Reproducer

https://stackblitz.com/edit/primeng-tablerowgroup-demo-3pwsdw?file=src/app/app.module.ts

### Angular version

13.0.3

### PrimeNG version

13.0.4

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

16.15.1

### Browser(s)

all

### Steps to reproduce the behavior

set [scrollable]=true when trying to use rowspan grouping

### Expected behavior

rowspan grouping functions properly when scrollable=true

**Comment by harryn** [comment]
Is there a fix or workaround?

**Comment by Phil-DS** [comment]
Is there any progress on this. It's currently a major blocking issue for us, and I was kinda hoping for some solution in the latest 14.1.0 release, yet it remains an issue. It's also not just rowspan, but colspan too.

**Comment by harryn** [comment]
I got colspan and rowspan to work in the header with scrollable table. For the header i used:
`<ng-template pTemplate="headergrouped">`

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
