### ISSUE TITLE
Tree: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by scurk1415** [primefaces/primeng#11713]
### Describe the bug

When a tree component has `[selectionMode]="'checkbox'"` and `[filter]="true"` the selection of any node (checkbox) when something is filtered throws **ERROR RangeError: Maximum call stack size exceeded**

### Environment

Doesn't really matter in this case

### Reproducer

https://stackblitz.com/edit/primeng-treefilter-demo-3rvpgn?file=src/app/app.component.html

### Angular version

13+

### PrimeNG version

13+

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.17.0

### Browser(s)

All

### Steps to reproduce the behavior

`<p-tree [value]="files2" [filter]="true" [selectionMode]="'checkbox'"></p-tree>`

Input something in the filter and select a checkbox

### Expected behavior

To not throw an error and the selection to work

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
