### ISSUE TITLE
Tabindex for columnFilter does not have any effect

### ISSUE THREAD

**Issue by flawesomesoft** [primefaces/primeng#11712]
### Describe the bug

Tabindex for PrimeNG Table with columnFilter cannot be modified.

p-columnFilter contains a button which does not inherit the tabindex from the parent.

If the tabindex of the button is modified manually in the browser it works as expected (refer to example below):
<img width="1269" alt="img" src="https://user-images.githubusercontent.com/102291054/178985202-561e9be8-a143-4325-a25a-0fc3790acff5.png">

### Environment

Provided Stackblitz example:

[https://stackblitz.com/edit/github-kfg65h-ghulsj?file=package.json](https://stackblitz.com/edit/github-kfg65h-ghulsj?file=package.json)

### Angular version

14.0.4

### PrimeNG version

14.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

8.9.5

### Browser(s)

Tested on Chrome, Mozilla, Edge

### Steps to reproduce the behavior

Tabindex for all columnFilter controls is set to "-1"

Tabbing through the provided Stackblitz example will still stop at each columnFIlter

### Expected behavior

Setting tabindex="-1" p-columnFilter should prevent from tab-navigate.
This should be inherited to the child components.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
