### ISSUE TITLE
p-table: Footer won't resize when header resized

### ISSUE THREAD

**Issue by aychia** [primefaces/primeng#11711]
### Describe the bug

before:
![image](https://user-images.githubusercontent.com/88313337/178957585-a6a55005-7781-4d1c-829f-9ad414a85b1f.png)
after:
![image](https://user-images.githubusercontent.com/88313337/178957656-61cff98a-4c95-4822-b282-a5cb5f19bb7f.png)

footer won't resize. after I tried to use virtual scroll in same table (resizing works fine previously)
[scrollable]="true" [rows]="100" scrollHeight="250px" [virtualScroll]="true" [virtualScrollItemSize]="34"

### Environment

Win 11

### Angular version

12.2.8

### PrimeNG version

12.2.0

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14.0

### Browser(s)

All

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
