### ISSUE TITLE
PrimeNG 6.1.7 Documentation

### ISSUE THREAD

**Issue by vixper** [primefaces/primeng#11710]
### Describe the feature you would like to see added

I use primeNG 6.1.7 in my project.
The documentation about that version is no more accessible.
Where can I find it?

Thanks

### Is your feature request related to a problem?

Missing documentation for 6.1.7 version

### Describe the solution you'd like

Link to 6.1.7 documentation

### Describe alternatives you have considered

add the documentation on 6.1.7 branch

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by vixper** [comment]
Hi, thanks for the response.
Anyway my problem is not solved.
I need the documentation for Verizon 6.1.7 and it is not accessible on the website.
