### ISSUE TITLE
Mismatched docs version and release version

### ISSUE THREAD

**Issue by bmarker1** [primefaces/primeng#11718]
### Describe the bug

We have a project based in primeng 9.1.3, and when I attempt to look at the documentation, there seems to be a discrepancy. On the releases (https://www.npmjs.com/package/primeng) the latest 9.x I see is 9.1.3. But when I go to the docs (https://www.primefaces.org/primeng-v9-lts/#/), I see 9.2.8-lts.

I looked into some of the source code and some things that are in the docs are not in the release...

Does that mean I should be using the docs for 8.2.9-lts since I'm beneath the docs version number?  Where does version 9.2.8 live if not?

Thanks!

### Environment

basic install

### Angular version

11.2.12

### PrimeNG version

9.1.3

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

16.15

### Browser(s)

all

### Steps to reproduce the behavior

We have a project based in primeng 9.1.3, and when I attempt to look at the documentation, there seems to be a discrepancy. On the releases (https://www.npmjs.com/package/primeng) the latest 9.x I see is 9.1.3. But when I go to the docs (https://www.primefaces.org/primeng-v9-lts/#/), I see 9.2.8-lts.

I looked into some of the source code and some things that are in the docs are not in the release...

Does that mean I should be using the docs for 8.2.9-lts since I'm beneath the docs version number?  Where does version 9.2.8 live if not?

**Comment by mertsincan** [comment]
Hi,

PrimeNG-LTS is different from the community version. Please see https://www.npmjs.com/package/primeng-lts
Details; https://www.primefaces.org/primeng/lts

Best Regards,
