### ISSUE TITLE
p-tree

### ISSUE THREAD

**Issue by jaggi510** [primefaces/primeng#11714]
### Describe the bug

Tree display is broken when expanded property is set to tree on nodes. It display each chidren under parent and also as separate node. See the data and the screenshot.
This is working fine with Primeng V13.4.1 or lower.

[data.txt](https://github.com/primefaces/primeng/files/9114267/data.txt)
![bug_screenshot](https://user-images.githubusercontent.com/39197764/179053893-cefbd484-821a-4196-a2c5-d8a09df866c4.png)

### Environment

Angular: 14.0.5
primeng: 14.0.0-rc.1

### Angular version

14.0.5

### PrimeNG version

primeng: 14.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v16.13.2

### Browser(s)

Chrome 103.0.5060.114

### Steps to reproduce the behavior

1. Use the data from the file attached and pass to <p-tree> like <p-tree [value]="treeNodes">
        </p-tree>
2. Render the ui
3. See the tree has seperate node for each childern and also under the parent.

### Expected behavior

Every parent and child should be displayed under same node hierarchy as defined in data.

**Comment by cetincakiroglu** [comment]
Hi @jaggi510,

Could you please provide a stackBlitz example by using PrimeNG issue template https://stackblitz.com/github/primefaces/primeng-issue-template

**Comment by jaggi510** [comment]
Hi, 
The issue is not happening with latest 14.0.0 version. Only reproducable using 14.0.0-rc.1.
As it is good with latest version, closing now.
Here is the reproducable slackblitz version for reference.

https://stackblitz.com/edit/github-hwyzwu?file=src%2Fapp%2Fapp.component.css,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html,package.json
