### ISSUE TITLE
contextMenu does not work with tabMenu

### ISSUE THREAD

**Issue by balkarov** [primefaces/primeng#11720]
### Describe the bug

My code:
```html
<p-tabMenu #tabs  [model]="tabItems" [activeItem]="selected" [scrollable]="true"></p-tabMenu>
<p-contextMenu [target]="tabs" [model]="items"></p-contextMenu>
```

And menu does not show. But If example with image works.
```html
<img #img src="assets/showcase/images/demo/nature/nature3.jpg" alt="Logo" aria-haspopup="true">
<p-contextMenu [target]="img" [model]="items"></p-contextMenu>
```

### Environment

Angular, windows, console, webstorm

### Reproducer
https://stackblitz.com/edit/primeng-tabmenu-demo-wpnvhf?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts

### Angular version

14.0.4

### PrimeNG version

14.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14.2

### Browser(s)

Chrome

### Steps to reproduce the behavior
Add tabMenu
Add contextMenu
Bind contextMenu to tabMenu
ContextMenu does not work

### Expected behavior
Works

**Comment by balkarov** [comment]
Any help?

**Comment by balkarov** [comment]
I added reproducer link

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
