### ISSUE TITLE
p-treeTable: frozen column does not scroll vertically when virtual scrolling is enabled

### ISSUE THREAD

**Issue by steffinchen** [primefaces/primeng#11722]
### Describe the bug

When having a p-treeTable with [virtualScroll]="true" and the first column is frozen, the frozen column does not scroll vertically at all and stays frozen while the rest scrolls. 
When turning off virtual scrolling the frozen column scrolls as expected. 

![prime-faces-14_0_0-frozen-col-not-scrolling-vertically](https://user-images.githubusercontent.com/5945974/179938875-f5ad4398-50e5-477b-ba16-7f95acd03f9e.gif)

### Environment

locally & on stackblitz, Angular 14, PrimeNG 14, Chrome 103 on Intel MacBook

### Reproducer

https://stackblitz.com/edit/primeng-treetablescroll-demo-ptvchb?file=src/app/app.component.html

### Angular version

14.0.6

### PrimeNG version

14.0.0

### Build / Runtime

TypeScript

### Language

ALL

### Node version (for AoT issues node --version)

16.15.1

### Browser(s)

Chrome 103 on OSX

### Expected behavior

Tree table with virtual scrolling enabled, the frozen column should still scroll along vertically with the rest of the table.

**Comment by vlnicolae** [comment]
Also this is valid for p-table: frozen column does not scroll vertically when virtual scrolling is enabled

https://primeng-tablevirtualscroll-demo-7o5tkb.stackblitz.io/

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by khang3052002** [comment]
How to fix it? Thanks all'
