### ISSUE TITLE
Component: p-table, p-dropdown filter

### ISSUE THREAD

**Issue by Svancara** [primefaces/primeng#11723]
### Describe the bug

p-dropdown filter is rendered incorrectly when there is a small number of rows in the table or there is a too small place above or below the p-table. The filter is unusable then.
The problem does not occur in versions 7,8,9,10,11.
The problem occurs in versions 12,13,14.

It looks like the filter is rendered with a wrong z-index.

See pictures. 

![image](https://user-images.githubusercontent.com/109393/180002512-802e0aa9-693e-403b-b634-81976b175947.png)

![image](https://user-images.githubusercontent.com/109393/180002567-f4e3a8ca-ea33-400d-89e9-be38eed36615.png)

### Environment

Chrome, Firefox, Bing

### Angular version

13.3.11

### PrimeNG version

12, 13, 14

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

14.17.0

### Browser(s)

Chrome, Firefox, Bing

### Steps to reproduce the behavior

Open your showcase. 
Open Table - Filter page.
Make your browser window low. 
Open one of dropdown filters.

### Expected behavior

The dropdown filter should be fully visible.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
