### ISSUE TITLE
Input: Repeater input or group input

### ISSUE THREAD

**Issue by tuannda** [primefaces/primeng#11724]
### Describe the feature you would like to see added

I want to the feature repeater of input or group input.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
