### ISSUE TITLE
Component: Title

### ISSUE THREAD

**Issue by lufo88ita** [primefaces/primeng#11737]
### Describe the bug

Set disabled property in a custom directive of pTooltip not work anymore (work in 12.x.x version)

### Environment

Angular with net core 3.1 server side

### Reproducer

https://stackblitz.com/edit/angular-ivy-zrfzmg

### Angular version

13.3.11

### PrimeNG version

13.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.16.0

### Steps to reproduce the behavior

Open the case demostration.
With the directive I add both of the text should not show the ptooltip ( , but only one version of the directive work.
Previous (primeng 12.x.x) work with this simple line of code 

`this.pTooltip.disabled = element.scrollWidth <= element.clientWidth;`

Now I must manually call setOption
```
this.pTooltip.setOption({
      disabled: element.scrollWidth <= element.clientWidth,
    });
```

Check the file directive.ts

### Expected behavior

Both version of the directive should work

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by lufo88ita** [comment]
13.4.1 is the latest 13.x version so the bug is still present in primeng@13

**Comment by mertsincan** [comment]
@lufo88ita Do you use any LTS version?

**Comment by lufo88ita** [comment]
Unfortunately not.

**Comment by mertsincan** [comment]
Hmm, we are unable to add retroactive fixes outside of LTS. Maybe you can test this issue with the latest version of PrimeNg.
