### ISSUE TITLE
textarea not working size textarea not working size with formControlName and ngModel 

### ISSUE THREAD

**Issue by SerhiiDerkach007** [primefaces/primeng#11738]
### Describe the bug

I am trying to connect textarea using formControlName. But crashes, any size settings and the form begins to uncontrollably expand in width. Until the bottom scroll appears, breaking everything in its path. I have tried a bunch of css options and settings. The only solution I have found is to set via [(ngModel)] and setValue to a form. But it looks like bad code and not best practice. But if there is no [ngModelOptions]="{standalone: true}" tag, I get an error. And as soon as I set the [ngModelOptions]="{standalone: true}" parameter, then all the width-wise input behavior in the layout immediately breaks again. how to be?

### Environment

{
  "name": "admin",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve -o",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^14.1.0",
    "@angular/cdk": "^14.1.0",
    "@angular/common": "^14.1.0",
    "@angular/compiler": "^14.1.0",
    "@angular/core": "^14.1.0",
    "@angular/forms": "^14.1.0",
    "@angular/platform-browser": "^14.1.0",
    "@angular/platform-browser-dynamic": "^14.1.0",
    "@angular/router": "^14.1.0",
    "@kolkov/ngx-gallery": "^2.0.1",
    "@ngx-formly/core": "^5.12.6",
    "@ngx-formly/primeng": "^5.12.6",
    "@ngx-formly/schematics": "^5.12.6",
    "@ngx-pwa/local-storage": "^13.0.5",
    "@types/lodash": "^4.14.182",
    "bootstrap": "^5.2.0",
    "eva-icons": "^1.1.3",
    "hammerjs": "^2.0.8",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "ngx-moment": "^6.0.2",
    "ngx-pagination": "^6.0.2",
    "ngx-spinner": "^14.0.0",
    "ngx-toastr": "^15.0.0",
    "normalize.css": "^8.0.1",
    "primeflex": "^3.2.1",
    "primeicons": "^5.0.0",
    "primeng": "^14.0.0",
    "quill": "^1.3.7",
    "rxjs": "~7.5.6",
    "tslib": "^2.4.0",
    "zone.js": "~0.11.6"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^14.1.0",
    "@angular-eslint/builder": "^14.0.2",
    "@angular-eslint/eslint-plugin": "^14.0.2",
    "@angular-eslint/eslint-plugin-template": "^14.0.2",
    "@angular-eslint/schematics": "^14.0.2",
    "@angular-eslint/template-parser": "14.0.2",
    "@angular/cli": "^14.1.0",
    "@angular/compiler-cli": "^14.1.0",
    "@types/jasmine": "~4.0.3",
    "@types/node": "^18.0.6",
    "@typescript-eslint/eslint-plugin": "^5.30.7",
    "@typescript-eslint/parser": "^5.30.7",
    "codelyzer": "^6.0.2",
    "eslint": "^8.20.0",
    "jasmine-core": "~4.2.0",
    "jasmine-spec-reporter": "~7.0.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.1.1",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "^5.1.0",
    "karma-jasmine-html-reporter": "^2.0.0",
    "protractor": "^7.0.0",
    "ts-node": "~10.9.1",
    "tslint": "~6.1.0",
    "typescript": "~4.7.4"
  }
}

### Angular version

14.1.0

### PrimeNG version

14.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v16.16.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

import { Component, Input, OnInit } from '@angular/core';
import { UntypedFormControl, UntypedFormGroup } from '@angular/forms';

@Component({
    selector: 'app-shared-form-el-descriptions-smoll',
    templateUrl: './form-el-descriptions-smoll.component.html',
    styleUrls: ['./form-el-descriptions-smoll.component.scss'],

})
export class FormElDescriptionsSmollComponent implements OnInit {

    @Input() form!: UntypedFormGroup;
    @Input() label: string;
    @Input() RUCtrl!: UntypedFormControl;
    @Input() UACtrl!: UntypedFormControl;
    @Input() controlName: string;

    public text = '';

    constructor() {
        this.controlName = '';
        this.label = '';
    }

    ngOnInit(): void {
    }

    public setTextareaValue(): void {
        // @ts-ignore
        this.form.get('smallDescriptionUA').setValue(this.text);
    }
}

            <textarea
                [autoResize]="false"
                [formControlName]="'smallDescriptionUA'"
                cols="30"
                pInputTextarea
                rows="4">
            </textarea>
            
            <textarea
                [autoResize]="true"
                [formControlName]="'smallDescriptionUA'"
                cols="30"
                pInputTextarea
                rows="4">
            </textarea>
            
            <textarea
                [autoResize]="false"
                [formControlName]="'smallDescriptionUA'"
                cols="30"
                pInputTextarea
                rows="4"
                style="resize: none;">
            </textarea>

             <div class="field">
                <textarea
                    (keyup)="setTextareaValue()"
                    [(ngModel)]="text"
                    [ngModelOptions]="{standalone: true}"
                    [autoResize]="true"
                    cols="30"
                    pInputTextarea
                    rows="4">
                </textarea>
            </div>

**Comment by cetincakiroglu** [comment]
Hi,

Cannot replicate the issue please feel free to re-open with a StackBlitz example.
