### ISSUE TITLE
Badge: Border not radius if the value is null or undefined

### ISSUE THREAD

**Issue by bozzelliandrea** [primefaces/primeng#11731]
### Describe the bug

When using a Badge component without any value, the border isn't radius

Without value
```
<p-badge [value]="" styleClass="p-mr-2"></p-badge>
```
![image](https://user-images.githubusercontent.com/74464364/180662161-77e2e0da-7935-4dcf-b9ae-9bd6bde972c4.png)

With value
```
<p-badge [value]="0" styleClass="p-mr-2"></p-badge>
```
![image](https://user-images.githubusercontent.com/74464364/180662184-5f480135-5bb3-4d94-bfe2-baf8f480c0ea.png)

currently, the only workaround is to set the value equals to an empty string 
```
<p-badge [value]="' '"></p-badge>
```

### Environment

Ubuntu

### Angular version

13

### PrimeNG version

13.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.15.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

Create a badge with empty or null value

### Expected behavior

Border radius with every value

**Comment by cetincakiroglu** [comment]
Hi, 

Here is a working example. https://stackblitz.com/edit/primeng-badge-demo-w6umw1?file=src%2Fapp%2Fapp.component.html,package.json

**Comment by bozzelliandrea** [comment]
@cetincakiroglu this issue will be fixed with https://github.com/primefaces/primeng/pull/11732

**Comment by cetincakiroglu** [comment]
Hi @bozzelliandrea 

Re-opened and will be reviewed.

**Comment by cetincakiroglu** [comment]
Hi,

You can use styleClass to give border radius as you wish.

https://stackblitz.com/edit/primeng-badge-demo-vcz8dm?file=src%2Fapp%2Fapp.component.html
