### ISSUE TITLE
Few HTMLDOM functions are  unavailable for pInputNumber component

### ISSUE THREAD

**Issue by RAMKI2** [primefaces/primeng#11746]
### Describe the feature you would like to see added

 - Few functions like autoFocus are unavailable to use with pInputNumber. This has to be enhanced.
 - Currency style inputs are available with pInputNumber, great, but instead of starting typing currencies from front, there are few scenerios, where we actually have to start filling with the cents positions (1's,10's, 100's...... so on). Keeping the pointer always at end.

 - Example 
    - initialy, 00.00 - Upon 1st number key press (say 2), value should be 00.02
    - next, press 5 - update value to 00.25
    - next press (637) - value should be 256.37 (push from right to left) 

Cents/ decimals limited to 2 fractions, but dollar values are optional entries.

If masked correctly and pointer positions are managed well, please name it as "RTL currency input" @

### Is your feature request related to a problem?

Found this as a difficulty, while handling casino transaction input cases.

### Describe the solution you'd like

 - pointer should always point to the end of the selection range.
 - Masks should allow optional characters at front.

This helps great for applications where mouse usage is minimal.

### Describe alternatives you have considered

IMASK.js

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
