### ISSUE TITLE
p-slider: Range slider with a step has the middle bar lag behind by one update

### ISSUE THREAD

**Issue by Phil-DS** [primefaces/primeng#11749]
### Describe the bug

The range bar, with a step size, breaks on clicking the bar. ONLY with a step size set. Not a range: fine. Default step size: fine.

### Environment

Standard angular setup. Bug reproducible in stackblitz (See the stackblitz)

### Reproducer

https://stackblitz.com/edit/github-ubq5gm?file=README.md

### Angular version

14.0.7

### PrimeNG version

14.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.13.0

### Steps to reproduce the behavior

1. Have a range slider, with a step size
2. click on the bar to move the handle to the latest point
3. notice the bar didn't change
4. click on the bar again
5. notice the handle moved to the new location, but the blue bar now reflects the prior positions.

### Expected behavior

The center bar follows the handles correctly.

**Comment by Phil-DS** [comment]
Seems to break with using the arrow keys as well, in the similar manner. Always 1 frame behind

**Comment by Phil-DS** [comment]
I think I see the issue. In a lot of the cases, updateValue triggers before updateHandleValue. Triggering them in this order sets the center bar's values first, before updating the values for the handles, therefore, lagging behind by 1 update.

**Comment by Adask023** [comment]
Hello, i'll try to fix that issue.
