### ISSUE TITLE
TreeSelect: Form has been submitted when click Close TreeSelect button

### ISSUE THREAD

**Issue by cuongdng** [primefaces/primeng#11742]
### Describe the bug

Implement TreeSelect component in a form. When click Close button when enable filter. It's cause form submit.
 ```
<button class="p-treeselect-close p-link" (click)="hide()">
         <span class="p-treeselect-filter-icon pi pi-times"></span>
</button>
```
I think, it's because Close button currently doesn't have attribute **type="button"**

### Environment

Production

### Angular version

14.0.3

### PrimeNG version

13.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.13.2

**Comment by cetincakiroglu** [comment]
Hi,

Cannot replicate the issue please feel free to re-open with StackBlitz example.
