### ISSUE TITLE
PrimengStyles Can't be used

### ISSUE THREAD

**Issue by alpayoguz** [primefaces/primeng#11745]
### Describe the bug

Whenever I tries to add primeng modules to my app, styles are not appyling.

I installed  ;
npm install primeng --save
npm install primeicons --save with cli and imported  all necessarry css files.

### Environment

I use Angular 14 and primen 14

### Angular version

14

### PrimeNG version

14

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

16.15.1

### Steps to reproduce the behavior

Import Module
Use in template
styles not aplying

### Expected behavior

I want styles to be applied

**Comment by volvachev** [comment]
Hi, can you do an example on stackblitz?

You have added styles to angular.json -
for example like this
```json
{ "styles": [
  "node_modules/primeng/resources/themes/lara-light-blue/theme.css",
  "node_modules/primeng/resources/primeng.min.css",
  "node_modules/primeicons/primeicons.css",
]
```

Example here (https://www.primefaces.org/primeng/setup)

**Comment by lliccien** [comment]
I have the same problem

angular 14.2.0
primeng 14.1.0
primeicons 14.1.0

node v16.16.0

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
