### ISSUE TITLE
P-Checkbox not able to check checkbox when default value null

### ISSUE THREAD

**Issue by Sonal824** [primefaces/primeng#11759]
### Describe the bug

After updating Primeng to latest version, my existing code stopped working.
P-Checkbox is appending , every time I click on checkbox.

**Working fine with earlier primeng version**
Stackblitz : https://stackblitz.com/edit/angular-primeng-p-checkbox-issue-hazng8

**Not Working with latest primeng version**
Stackblitz : https://stackblitz.com/edit/primeng-checkbox-demo-c2k41u

Note: My default model value is null, in earlier version p-checkbox was not appending commas.

### Environment

Angular 13
PrimeNg : 13.0.4

### Angular version

13.0.3

### PrimeNG version

13.0.4

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14

### Browser(s)

chrome

### Expected behavior

Should not append comma and checkbox should be selected even with null value.

**Comment by cetincakiroglu** [comment]
Hi, 

You can use the binary property of the checkbox or there is a triStateCheckbox component for three different boolean states (null, false, true). Note that the checkbox in binary mode only checks for strict equality with 'true' or 'false' values.

Here is the refactored and working version of your example
https://stackblitz.com/edit/primeng-checkbox-demo-rqak5x?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts
