### ISSUE TITLE
Panel component inside accordion is visible when collapsed

### ISSUE THREAD

**Issue by olegkap** [primefaces/primeng#11752]
### Describe the bug

When p-panel control placed inside p-accordion control and panel is taggable then when panel collapsed the content of the panel remains visible.

It looks like its overridden by accordion styles.

### Environment

Windows 11

### Reproducer

https://stackblitz.com/edit/github-n63h1u?file=src%2Fapp%2Fapp.component.html

### Angular version

14.1.0

### PrimeNG version

14.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.13.0

### Steps to reproduce the behavior

`<h5>Default</h5>
<p-accordion>
    <p-accordionTab header="Header I" [selected]="true">
        <h5>Advanced</h5>
        <p-panel header="Header" [toggleable]="true">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
                cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        </p-panel>

        <h5>Advanced</h5>
        <p-panel header="Header" [toggleable]="true">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
                cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        </p-panel>
    </p-accordionTab>
    <p-accordionTab header="Header II">
        <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi
            architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione
            voluptatem sequi nesciunt. Consectetur, adipisci velit, sed quia non numquam eius modi.</p>
    </p-accordionTab>
    <p-accordionTab header="Header III">
        <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati
            cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio.
            Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus.</p>
    </p-accordionTab>
</p-accordion>`

### Expected behavior

Collapsed panel inside accordion should not be visible as in previous versions

**Comment by cetincakiroglu** [comment]
Hi,

You can solve this by the styleClass property of the panel component. Here is the refactored and working version of your example.

https://stackblitz.com/edit/github-n63h1u-r6cqnt?file=src%2Fapp%2Fapp.component.html
