### ISSUE TITLE
PTable: Export CSV with row expansion data

### ISSUE THREAD

**Issue by kunalfleethawks** [primefaces/primeng#11751]
### Describe the feature you would like to see added

Currently, if we use a `p-table` with row expansion https://www.primefaces.org/primeng/table/rowexpansion and try to export to CSV we only get parent row data in the exported file. Is it possible to get data from an expanded row when we export csv? 

### Is your feature request related to a problem?

Yes. As we are not able to get expanded row data.

### Describe the solution you'd like

Get Expanded row data in csv file

### Additional context
reproducible issue.
[(https://stackblitz.com/edit/primeng-tableexport-demo-vvahrn?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts)](https://stackblitz.com/edit/primeng-tableexport-demo-vvahrn?file=src/app/app.component.html)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by Github743** [comment]
Any solution for this I am looking for similar requirement
