### ISSUE TITLE
Table: Colgroup header and footer are stuck

### ISSUE THREAD

**Issue by Kisters-BS** [primefaces/primeng#11755]
### Describe the bug

When using the pTable with scrollable, resizableColumns and colgroup (colspan), the header and the footer are stuck when trying to resize column
![tableIssue](https://user-images.githubusercontent.com/84901454/181749862-b8de1f1f-f9fa-4c6d-b02b-a798ad10a431.gif)

### Environment

See below stackblitz

### Reproducer

https://stackblitz.com/edit/github-ujnciz?file=src%2Fapp%2Fapp.component.html

### Angular version

14.0.7

### PrimeNG version

14.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.16.0

### Steps to reproduce the behavior

1. Add scrollable, resizableColumns and colgroup (colspan) to pTable
2. Try to resize a column -> Only td get resized and header and footer are stuck

### Expected behavior

Table header and footer should also resize

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
