### ISSUE TITLE
Component: Title

### ISSUE THREAD

**Issue by andrerauer** [primefaces/primeng#11758]
### Describe the bug

The Sorting of columns with null and undefined values doesn't work right. It does not sort the "empty" fields in correct position. This happens only if multiSort is set.

My guess is, that these else-part is always be used, if value1 is not a string, and this is the case if value1 is null or undefined.
https://github.com/primefaces/primeng/blob/14.0.0/src/app/components/treetable/treetable.ts#L792

### Environment

Stackblitz

### Reproducer

https://stackblitz.com/edit/github-pgkhsv

### Angular version

14.0.7

### PrimeNG version

14.0.0

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

the version you specified in stackblitz

### Steps to reproduce the behavior

1. Sort the "Date" Column
2. Sort the "Date" Column
3. Sort the "Date" Column

### Expected behavior

First sort should sort the data asc, the second desc and the third asc.

**Comment by cetincakiroglu** [comment]
Hi,

You can adapt your own custom sorting logic. See the example https://stackblitz.com/edit/primeng-tablesort-demo-qry9j1?file=README.md
