### ISSUE TITLE
MultiSelect: Scroll gets stuck when using virtualScroll and lazy mode

### ISSUE THREAD

**Issue by israeloriente** [primefaces/primeng#11753]
### Describe the bug

Scroll gets stuck when using virtualScroll and lazy mode. The problem only happens in the google chrome browser.

### Environment

-

### Angular version

14.1.0

### PrimeNG version

14.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.15.1

### Browser(s)

Chrome 103.0.5060.134

### Steps to reproduce the behavior

When add this attributes on p-multiSelect component: 
`[lazy]="true"
      [virtualScroll]="true"
      [virtualScrollItemSize]="40"
      [virtualScrollOptions]="{numToleratedItems: 50}"
      (onLazyLoad)="dispatchSomething($event)"`

https://user-images.githubusercontent.com/31784632/181581415-6e7ddf79-c8c2-4b91-9b4f-8c5e7f9e698d.mov

### Expected behavior

Firefox browser:

https://user-images.githubusercontent.com/31784632/181583809-3a881d9f-e14e-44bc-871d-66345712a7d9.mov

**Comment by cetincakiroglu** [comment]
Hi,

Cannot replicate the issue, feel free to re-open with a StackBlitz example, so I'm closing it.

I've tried to replicate your problem as I understand from the code sample you shared above. Here you can see it https://stackblitz.com/edit/github-pstonr?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html
