### ISSUE TITLE
Pagination: Patch not working

### ISSUE THREAD

**Issue by sigma-wadbude-tfs** [primefaces/primeng#11750]
### Describe the bug

we have created a patch to add elipses(...) support which was working with 11.4.2, now it braking the build with "javaScript heap ou of memory"

### Environment

we are using maven for buil

### Angular version

11.2.11

### PrimeNG version

11.4.5

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.17.4

### Browser(s)

Chrome 103

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
