### ISSUE TITLE
TreeSelect: style and type attribute of TreeNode API doesn't work

### ISSUE THREAD

**Issue by mortezabahrami** [primefaces/primeng#11761]
### Describe the bug

While using TreeSelect, the style and type attributes of TreeNode don't work.

I have this in my HTML template:
`
<p-treeSelect >
    <ng-template let-node pTemplate="temp"> TEMP ITEM </ng-template>
</p-treeSelect>
`

and these attributes on each item:
`
"type": "temp",
"style": "color:red;",
`

and also [this is ](https://stackblitz.com/edit/primeng-treeselect-demo-2a1e1f?file=src/app/app.component.html) stack blitz sample.

It would be great if anyone can suggest me a workaround for this.

### Environment

Primeng 13.4.1

### Reproducer

https://stackblitz.com/edit/primeng-treeselect-demo-2a1e1f?file=src/app/app.component.html

### Angular version

13.3.2

### PrimeNG version

13.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.16.0

**Comment by mortezabahrami** [comment]
I should mention that the "style" attribute neither doesn't work on the Tree component.
Like in [this link](https://stackblitz.com/edit/primeng-tree-demo-vg2wi9?file=src/assets/files.json).

**Comment by mortezabahrami** [comment]
About the type attribute, I've found that the TreeSelect does not pass the templates attribute to the Tree component.

**Comment by SHENGALTEC** [comment]
Issue still remain, type attribute is not working for tree select (p-treeSelect). Currently there are no way to make node template since type attribute does not work
