### ISSUE TITLE
Treetable - frozenColumns keyboard focus doesn't scroll the non frozen columns with a fixed scrollHeight

### ISSUE THREAD

**Issue by davesellersBG** [primefaces/primeng#11768]
### Describe the bug

Using the Treetable component with a frozen column and a scrollHeight. When the frozen column contains an element with a tabindex, and the element is tabbed to it scrolls the frozen column correctly, however the remaining columns do not scroll, meaning the rows become misaligned.

![image](https://user-images.githubusercontent.com/55135375/182387819-9eb62eb1-7518-421a-af65-5d3067df4e24.png)

Tested in Angular/Primeng v12, but the bug is still present in Primeng v14

### Environment

Angular 12/13/14 | PrimeNG 12/13/14. Testing with Chrome.

### Angular version

12.2.16

### PrimeNG version

12.2.3

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

14.17.0

### Browser(s)

Chrome 103

### Steps to reproduce the behavior

1. Create a scrollable Treetable with a frozenColumn.
2. Add a keyboard focusable element to the cells within the frozen column
3. Keyboard focus to the focusable element
4. The frozenColumn will scroll to show the focused element, the remaining columns will not. 

### Expected behavior

The scroll position of the remaining columns should match the scrolled frozenColumn

**Comment by cetincakiroglu** [comment]
Hi,

Accessibility is a major concern of the Prime UI libraries and PrimeNG is no exception. [PrimeTek](https://www.primetek.com.tr/) teams have initiated a significant process to review and enhance the accessibility features of the components. This guide documents the foundation of the general guidelines that PrimeNG will follow and each component documentation will have a separate Accessibility section that states the keyboard support, screen reader compatibility, the implementation details along with tips to achieve WCAG compliancy. This work has been initiated in Q2 2022 and planned to be completed by early Q3. PrimeNG will be the reference implementation which then will be ported to PrimeFaces, PrimeNG and PrimeVue.
