### ISSUE TITLE
p-tree: selection propagation for selectionMode="checkbox" does not work with virtual scrolling

### ISSUE THREAD

**Issue by randes73** [primefaces/primeng#11760]
### Describe the bug

Selection propagation does not work as expected when p-tree configured with selectionMode="checkbox" and virtualScroll="true".    The behavior can be observed using the stackblitz example link, adding virtualScroll="true" to the primeNG p-tree virtual scroll example, or using something similar to the following with some hierarchical data:
```
<p-tree
  [value]="files3"
  selectionMode="checkbox"
  [virtualScroll]="true"
  [virtualNodeHeight]="33"
  scrollHeight="220px"
></p-tree>
```

### Environment

Angular 13.3 using chromium based browser (Edge or Chrome)

### Reproducer

https://stackblitz.com/edit/github-zqg5s9?file=src/app/app.component.html

### Angular version

13.3.9

### PrimeNG version

13.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.13.2

### Browser(s)

Edge,Chrome

### Steps to reproduce the behavior

Select and/or deselect child nodes.  Parent node selection or partial selection is unaffected.

### Expected behavior

- When all child nodes are selected and the user deselects one of the child nodes, the parent should be partially selected
- When one or more child nodes are selected and the user deselects all of the child nodes, the parent should also be deselected
- When the parent is selected by the user, all child nodes should be selected
- When the parent is deselected by the user, all child nodes should be deselected
- When some child nodes are selected but not all child nodes and the user selects all of the child nodes, the parent should also be selected

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by randes73** [comment]
Hello,

I've received your response and have re-tested this issue with version 14.1.2 in our app.   Unfortunately, the undesired behavior still exists after the upgrade.  The stackblitz link in the reproducer in this issue still demonstrates the issue.  I am not able to reopen a github issue that the collaborator has closed.  Can you please reopen this issue?

Thank you!

**Comment by randes73** [comment]
Hello,

I have added the following comment to the issue:

I've received your response and have re-tested this issue with version 14.1.2 in our app.   Unfortunately, the undesired behavior still exists after the upgrade.  The stackblitz link in the reproducer in this issue still demonstrates the issue.  I am not able to reopen a github issue that the collaborator has closed.  Can you please reopen this issue?

Thanks,

Robin Andes | Software Engineer, Advisory | Jack HenryTM

**Comment by kkovac1** [comment]
Still have this issue, any updates for this?

**Comment by randes73** [comment]
Hello, thank you for your reply.  Yes, I indicated in my previous reply that I verified this was still an issue in 14.1.2.  Thanks again!!
