### ISSUE TITLE
Component: ConfirmDialog - Add boolean options showAcceptIcon and showRejectIcon

### ISSUE THREAD

**Issue by lightzane** [primefaces/primeng#11762]
### Describe the feature you would like to see added

As a developer,
I want to customize or hide the icons in the Yes/No button of ConfirmDialog
So that I will not have extra whitespaces when there is no PrimeIcon or icon is set to null or undefined

### Describe the solution you'd like

Add boolean options showAcceptIcon and showRejectIcon

### Additional context

> Just a note:  **PrimeNG** has default icons by default in the YES/NO button of `ConfirmDialog` while **PrimeReact** does not have default icons.

**Comment by bozzelliandrea** [comment]
Hi @lightzane, this feature already exist, there are 2 input called acceptVisible and rejectVisible.

Btw if you want there is an anuglar feature called content projection, you can add your own custom template to the modal, see Customization in https://www.primefaces.org/primeng/confirmdialog

**Comment by lightzane** [comment]
@bozzelliandrea the `acceptVisible` is not what I'm looking for as it will just remove the entire button:
```ts
this.confirmationService.confirm({
  message: 'Are you sure?',
  acceptVisible: false,
});
```
![image](https://user-images.githubusercontent.com/8446145/182510807-a12a8381-461c-44cd-820e-55c6bc7924f0.png)

I want an option to just remove the icon inside the buttons. Like how `PrimeReact` is doing by default:
![image](https://user-images.githubusercontent.com/8446145/182511089-a60aa6a5-e686-4581-808e-3a38f5724509.png)

**Comment by bozzelliandrea** [comment]
@lightzane Ok, now i understand what are you looking for, there are 2 Input called rejectIcon and acceptIcon, if you set the value empty or false for example, your result is exactly the same behavior of PrimeReact 

### Code

![image](https://user-images.githubusercontent.com/74464364/182542228-9b08a370-bd2f-4752-9c9e-2a8a3ecab3b5.png)

### Showcase

![image](https://user-images.githubusercontent.com/74464364/182542319-012bd089-543d-4933-a8cc-dd0f5b4c3cae.png)


However 2 new boolean input for handle a "show" flag could be good, but the behavior will be similar to that described above, unless the inputs are handled differently.

**Comment by lightzane** [comment]
@bozzelliandrea I think we're still going to stick with the template.

As providing false in `acceptIcon` or `rejectIcon` will still leave **_some extra whitespaces_** on the left of the **Yes** and **No** buttons.

![image](https://user-images.githubusercontent.com/8446145/183355904-a54cb70e-d67c-4fd9-9bc8-7e55e6357ad8.png)

Unlike using the template, will actually remove the icon without the extra whitespaces:

![image](https://user-images.githubusercontent.com/8446145/183356073-3adb7111-f32f-4811-a8a1-64c363beb5e3.png)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
