### ISSUE TITLE
P-table edit

### ISSUE THREAD

**Issue by AjeetUI** [primefaces/primeng#11776]
### Describe the bug

Using P Table "Edit" after click enter key. selection not appear on the cell.  
Please watch the below video.
[video-convert-1659694641100.webm](https://user-images.githubusercontent.com/87692474/183057107-62a34bb4-29d8-4f19-9adb-55cd13a4c2c7.webm)
Here I am using arrow keys of keyboards and press the enter key. after pressing the enter key selection not available on same column. 

Thanks in advance.
### Environment

P table edit mode

### Angular version

14.1.1

### PrimeNG version

14.0.0

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

14.19.3

**Comment by cetincakiroglu** [comment]
Hi,
