### ISSUE TITLE
P table column selection on arrow key

### ISSUE THREAD

**Issue by AjeetUI** [primefaces/primeng#11777]
### Describe the feature you would like to see added

I want to column selection on arrow key in prime table. 
Please watch the below video for better understanding. 
[video-convert-1659693605984.webm](https://user-images.githubusercontent.com/87692474/183054345-a889413f-042f-47b0-88c8-860e9b1fa89b.webm)

Here I am using arrow key instead of mouse cursor. 

Thanks in advance.

### Is your feature request related to a problem?

No

### Describe the solution you'd like

I want to column selection on arrow key in prime table same like google sheet

**Comment by cetincakiroglu** [comment]
Hi,

Accessibility enhancements are part of feature hours. If desired, we will be quoting you for an estimated time for this particular enhancement.
As a result, we will be giving you a feature hours proposal. We will be quoting you for an estimated time.

**Comment by cetincakiroglu** [comment]
Hi,

Accessibility is a major concern of the Prime UI libraries and PrimeNG is no exception. [PrimeTek](https://www.primetek.com.tr/) teams have initiated a significant process to review and enhance the accessibility features of the components. This guide documents the foundation of the general guidelines that PrimeNG will follow and each component documentation will have a separate Accessibility section that states the keyboard support, screen reader compatibility, the implementation details along with tips to achieve WCAG compliancy. This work has been initiated in Q2 2022 and planned to be completed by early Q3. PrimeNG will be the reference implementation which then will be ported to PrimeFaces, PrimeNG and PrimeVue.
