### ISSUE TITLE
Component: Table 

### ISSUE THREAD

**Issue by ElesGergo** [primefaces/primeng#11778]
### Describe the bug

Table Reorder does not work as intended. 
You have to move the columns outside of the header for the drop indicators to appear.

Even in the demo it is broken
https://www.primefaces.org/primeng/table/reorder

For some reason on StackBlitz, it works correctly.
https://stackblitz.com/edit/primeng-tablereorder-demo

### Environment

I have just started a new project.

### Angular version

14.0.0

### PrimeNG version

14.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.17.3

### Browser(s)

Chrome , Edge

### Steps to reproduce the behavior

Case 1
1. Visit the demo
https://www.primefaces.org/primeng/table/reorder
2. Grab a column and move it horizontally
3. Arrow indicator for dropping does not appear - dropping the column does not always trigger a reorder

Case 2
------
1. Visit the demo
https://www.primefaces.org/primeng/table/reorder
2. Grab a column and move it in-outside of the header where the indicator should be indicator appears correctly
3. Indicators appears

### Expected behavior

Works as the stackblitz demo.
https://www.primefaces.org/primeng/table/reorder

**Comment by ElesGergo** [comment]
Replication:

Not leaving the header:
https://gyazo.com/4347b8c030cfda32b5978850c49b66d4

Leaving the header:
https://gyazo.com/97e9389e5d07f74c161dc11124c55c00

**Comment by stefan2718** [comment]
This issue affects v14, but seems to be fixed in v15. Like @ElesGergo said, you can reproduce it on the v14 reorder page
https://www.primefaces.org/primeng-v14/table/reorder

Does PrimeNg continue pushing bugfix patches for older versions, or since v15 is out now, will v14 never receive a fix?
