### ISSUE TITLE
[Calendar] Month Calendar popup presenting different from the date on ngModel

### ISSUE THREAD

**Issue by fernandocode** [primefaces/primeng#1177]
Testing the `Calendar` realized that when setting a different date from the current month to the `ngModel` to open the popup calendar navigation month combobox the month date is showing incorrectly (always in the combo is showing the current month).

An example follows:

```
import { Component } from '@angular/core';

@Component({
  selector: 'my-app',
  template: `
  <p>{{date5|date}}</p>
  <p-calendar [(ngModel)]="date5" [monthNavigator]="true" [yearNavigator]="true" 
  yearRange="2000:2030"></p-calendar>
  `
})
export class AppComponent { 
  date5: Date = new Date();
  
  constructor(){
    this.date5.setMonth(this.date5.getMonth() - 14); // back one year and two months
    // Open the popup calendar and note the combobox month of navigation, 
    // the month of the date would be September and the selection displays
    // the current month (November), since the year is presented correctly.
  }
}
```

Bug image:
![calendar_error](https://cloud.githubusercontent.com/assets/3801304/19896945/3fbb44f0-a03d-11e6-812d-052b76fb7810.png)

[Live example in plunker. ](http://plnkr.co/edit/1rMLcG2TlHnAfGUE39Xi?p=preview)

In the example the month should be in September and the selection displays the current month (November), the year is presented correctly.

This seems to be a bug. For what followed the code seems to be some treatment in the construction of the Calendar (`createMonth` method).

**Comment by fernandocode** [comment]
Analyzing the current comparative code version I'm using [PrimeNG 1.0.0-beta.20], is the [line 301 of this commit](https://github.com/primefaces/primeng/commit/bf7b478ecedcf3c1e03859ff8005d1c45ee03abf#diff-54063d8c71eae94d97213573712fb57cR301) solves already my issue? Since we have [this line (line 45)](https://github.com/primefaces/primeng/blob/master/components/calendar/calendar.ts#L45) that selects the item that is in the variable `currentMonth`.

**Comment by chpasha** [comment]
it seems to be fixed in rc-1

**Comment by fernandocode** [comment]
@chpasha , when I posted's issue had not yet rc.1 release, now there rc.3, I think this releace candidate is not very stable ... hehe. Three versions published in just one day. = D
Later I will update my project to rc.3 and test this situation, if it is already resolved, close the issue.

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/VZbdZfQ7SuTV87tTkbYR
