### ISSUE TITLE
Fieldet and accordion are different from Official website

### ISSUE THREAD

**Issue by Epameinondas-Theodoropoulos** [primefaces/primeng#11770]
### Describe the bug

Fieldset and accordion do not work and do not appear as they appear on the Official page

![image](https://user-images.githubusercontent.com/49025564/182429243-2a6ad811-96d3-440a-9e81-43786e3a93f0.png)

### Environment

Angular CLI: 12.1.0
Node: 14.20.0
Package Manager: npm 6.14.17
OS: win32 x64

Angular: 12.1.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, google-maps, language-service, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.0
@angular-devkit/build-angular   12.1.0
@angular-devkit/core            12.1.0
@angular-devkit/schematics      12.1.0
@schematics/angular             12.1.0
rxjs                            6.6.2
typescript                      4.2.3

### Angular version

12.1.0

### PrimeNG version

13.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.20.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

Just install with the above dependencies and add the minimum code. 

```
<p-fieldset legend="Header">
    Content
</p-fieldset>
```

```
<p-accordion>
    <p-accordionTab header="Header 1">
       Content 1
    </p-accordionTab>
    <p-accordionTab header="Header 2">
        Content 2
    </p-accordionTab>
    <p-accordionTab header="Header 3">
        Content 3    
    </p-accordionTab>
</p-accordion>
```

### Expected behavior

The expected behavior is to show the components as they are in the official website

![image](https://user-images.githubusercontent.com/49025564/182430620-1b17fe42-d08f-43f4-8125-10ec4d7f8817.png)

![image](https://user-images.githubusercontent.com/49025564/182430752-4a5fb8d7-9d28-4159-aa04-2cfd1e8001d7.png)

**Comment by dionisis84** [comment]
Hello Epameinondas,

I noticed that you use PrimeNG v13.4.1 with Angular v12.1.0. I think that PrimeNG expects to have the appropriate Angular version installed in order to function properly. For example, PrimeNG v13.xx.xx needs Angular v13.xx.xx etc.

So try this, upgrade Angular to v13.xx.xx and then check if PrimeNG works as expected.

**Comment by Epameinondas-Theodoropoulos** [comment]
> Hello Epameinondas,
> 
> I noticed that you use PrimeNG v13.4.1 with Angular v12.1.0. I think that PrimeNG expects to have the appropriate Angular version installed in order to function properly. For example, PrimeNG v13.xx.xx needs Angular v13.xx.xx etc.
> 
> So try this, upgrade Angular to v13.xx.xx and then check if PrimeNG works as expected.

I tried this but the issue remains. I updated everything. But again these 2 components look like the print screens I posted above and like the official website
```
Angular CLI: 13.3.9
Node: 14.20.0      
Package Manager: npm 6.14.17
OS: win32 x64

Angular: 13.3.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.9
@angular-devkit/build-angular   13.3.9
@angular-devkit/core            13.3.9
@angular-devkit/schematics      13.3.9
@angular/cdk                    13.3.9
@angular/cli                    13.3.9
@angular/google-maps            12.2.13
@schematics/angular             13.3.9
rxjs                            6.6.2
typescript                      4.6.4
```


```
    "primeflex": "^3.2.1",
    "primeicons": "^5.0.0",
    "primeng": "^13.4.1",
```

**Comment by dionisis84** [comment]
@Epameinondas-Theodoropoulos I tried to use both the Components you mention in the StackBlitz demo of the Fieldset of PrimeNG and they work as expected!

1. After changing PrimeNG version in package.json, did you delete the "_node_modules_" folder and then "_npm install_" again?
2. Maybe there is some custom CSS rule(s) that affect the way those components render? If you remove all custom CSS, does the problem persists?
3. Could you provide a StackBlitz link that behaves just like your local dev environment?

**Comment by zachsteffens** [comment]
I included Bootstrap and that ended up breaking the fieldset header.
https://stackblitz.com/edit/rh4wr5?file=angular.json

I wonder if that was the impetus for most of these issues.
Anyone figure out a way around this one?
