### ISSUE TITLE
TabMenu: ActiveRoute not presented properly when using RouterLink and QueryParams

### ISSUE THREAD

**Issue by operta** [primefaces/primeng#11773]
### Describe the bug

Multiple items are shown as ActiveItem, when they have the same routerLink but different queryParams propertyy.

![activeLink](https://user-images.githubusercontent.com/15978525/182824160-c625085d-bca4-4f8b-9d01-b8db9d3c7609.png)

In the repository the isActive function does not check for queryParams
https://github.com/primefaces/primeng/blob/master/src/app/components/tabmenu/tabmenu.ts#L127

### Environment

Angular 14.1.0 browser app

### Angular version

14.1.0

### PrimeNG version

14.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.6.1

**Comment by cetincakiroglu** [comment]
Hi,

Cannot replicate the issue please feel free to re-open with a StackBlitz example.
