### ISSUE TITLE
Property [autofocus] not working on InputMask component

### ISSUE THREAD

**Issue by quranc** [primefaces/primeng#11783]
### Describe the bug

This is related to #10232 and #11781.
Autofocus do not have any effect.
Autofocus property is spelled as `autoFocus` for InputMask and `autofocus` for AutoComplete and Dropdown.
This could be more consist.

### Environment

OS: darwin arm64

### Reproducer

https://stackblitz.com/edit/github-ush22w?file=src/app/app.component.html

### Angular version

14.0.7

### PrimeNG version

14.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.13.1

### Steps to reproduce the behavior

`<p-inputMask mask="99-999999" [(ngModel)]="val1" placeholder="99-999999" [autofocus]="true"></p-inputMask>`

`<p-inputMask mask="99-999999" [(ngModel)]="val1" placeholder="99-999999" [autofocus]="false"></p-inputMask>`

Autofocus does not have any effect on the InputMask, no matter of values.

### Expected behavior

Autofocus should focus the InputMask on load when having the attribute `[autofocus]="true"`

**Comment by cetincakiroglu** [comment]
Hi,

Since this problem occurs across many components, I'm closing this issue and merging them into one https://github.com/primefaces/primeng/issues/11807. We'll fix them altogether.

Thanks for your support and report!
