### ISSUE TITLE
MenuItem disabled property as arrow function

### ISSUE THREAD

**Issue by lwestfall** [primefaces/primeng#11788]
### Describe the feature you would like to see added

Make MenuItem.disabled type of `boolean | () => boolean`. This would allow more dynamic disabling of menu items.

Not to scope creep, but this would be nice to have for other menu item properties as well, eg `label?: string | ( ) => string`, but I'm more interested in the disabled property at the moment.

### Is your feature request related to a problem?

Disabling/enabling MenuItems dynamically is a little painful at the moment. I have to get a reference to the MenuItem in my item array and change the disabled property if there is a state change that requires it. If we could provide an arrow function then we could do this in a single line.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
