### ISSUE TITLE
Datatable: How to style a cell based on rowdata?

### ISSUE THREAD

**Issue by Bulan** [primefaces/primeng#1178]
I want to style the cell in a Datatable based on the value of the cell, preferably by setting a class on it.
I can't figure out from the example page( http://www.primefaces.org/primeng/#/datatable/templating )  how to to this.

Its the `styleClass` below I would like to set to a different value depending on value of data (same as templates within the cell)
```
<p-column field="decided" header="Decided" styleClass="success">
  <template let-col let-rowData="rowData" pTemplate type="body">
    <template [ngIf]="rowData[col.field]">
      <span class="fa fa-check-square"></span> Yes
    </template>
    <template [ngIf]="!rowData[col.field]">
      <span class="fa fa-square-o"></span> No
    </template>
  </template>
</p-column>
```

**Comment by cagataycivici** [comment]
Please use forum for support requests, thank you.
