### ISSUE TITLE
PrimeFlex Grid inside DynamicDialog causes it to have a scrollbar

### ISSUE THREAD

**Issue by davisb10** [primefaces/primeng#11786]
### Describe the bug

When a PrimeFlex grid is added to the content of a DynamicDialog, a scrollbar will appear even though the contents do not take up the full default height.

### Environment

Able to replicate very simply in the Stackblitz

### Reproducer

https://stackblitz.com/edit/github-omr5jf

### Angular version

14.1.0

### PrimeNG version

14.0.0

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

x.x.x

### Expected behavior

The scrollbar should not be shown if the contents do not require it.

**Comment by cetincakiroglu** [comment]
Hi,

You can give a hight https://stackblitz.com/edit/github-omr5jf-zorbz6?file=src%2Fapp%2Fapp.component.ts

**Comment by davisb10** [comment]
@cetincakiroglu Please reopen this. The dialog should not show a scrollbar if the contents don't require it. In the stackblitz, that dialog **should not** have a scrollbar. From the css, .p-dialog has a max-height of 90%. If the contents of the .p-dialog / .p-dialog-content are less than that 90%, the scrollbar is not correct. Removing the -0.5rem margin-top on the grid seems to remove that scrollbar. So it appears that the PrimeFlex grid and the Dialog are fighting.

![image](https://user-images.githubusercontent.com/11411180/183409976-0fba2014-ee66-4cc4-83bd-6936d2bf5d93.png)

**Comment by davisb10** [comment]
Current workaround for this is:

.p-dialog .p-dialog-content .grid:first-of-type {
	margin-top: 0 !important;
}
