### ISSUE TITLE
PrimeNG popup attribute conflict with html popup attribute

### ISSUE THREAD

**Issue by YD1722** [primefaces/primeng#11794]
### Describe the bug

Got this error message, warning about the possible site breaking in the future.

`platform-browser.mjs:605 Found a 'popup' attribute. If you are testing the popup API, you must enable Experimental Web Platform Features. If not, note that custom attributes must start with 'data-': https://html.spec.whatwg.org/multipage/dom.html#custom-data-attribute. This usage will *likely cause site breakage* when the popup API ships: https://chromestatus.com/feature/5463833265045504. `

Seems like this will affect the following classes;

TabMenu
Menu
SlideMenu
TieredMenu

### Environment

Chrome : 104.0.5112.80 

### Angular version

13.3.11

### PrimeNG version

13.4.1

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

16.13.0

**Comment by cetincakiroglu** [comment]
Hi, 

Cannot replicate the issue please feel free to re-open with StackBlitz example

**Comment by shayl29** [comment]
Can confirm this is also happening on primeng `v9.1.3`
Happens on Chrome and Edge browsers as well
![image](https://user-images.githubusercontent.com/30566828/184087527-a82d3990-fae2-4d77-bfce-5749eded8dc7.png)

Can't be reproduced on stackblitz/CodeSandbox
