### ISSUE TITLE
BlockUI blocks entire page when blocked is true by default (again)

### ISSUE THREAD

**Issue by epaitz** [primefaces/primeng#11798]
### Describe the bug

The PrimeNG BlockUI (v13 and v14) blocks the whole page if blocked is set to true by default.

### Environment

Angular 14
PrimeNG 14
Node 18.7.0
NPM 8.15.0
VSCode 1.70
Windows 10
MS Edge Browser

### Reproducer

https://stackblitz.com/edit/github-mu8jjn

### Angular version

13 and 14

### PrimeNG version

13 and 14

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.7.0

### Browser(s)

Edge (latest)

### Steps to reproduce the behavior

See the attached stackblitz and change blocked to be true in app.component.ts and the BlockUI will cover the whole page.  The behavior is the same for Angular/PrimeNG v13 and v14. 

### Expected behavior

I would expect the BlockUI to be able to correctly block its target if the blocked boolean is set to true by defualt without having to use the described work-arounds in the stackblitz readme.

**Comment by sebeyruv** [comment]
Is there any progress on the topic? In our project we used this quite often and now with the update to Angular 14 and PrimeNG 14 it is pretty much unusable

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by epaitz** [comment]
I agree. I gave up on this awhile ago and created my own Angular container component that does what I needed the blockui to do.
