### ISSUE TITLE
p-slider: Entering a decimal value without a preceding number before decimal point gives error

### ISSUE THREAD

**Issue by vinnyab28** [primefaces/primeng#11790]
### Describe the bug

When an input box is mapped to the `p-slider` and when the step value is a decimal number, the number entered in the input box without a preceding number before the decimal such as `.5` or `.32` and change the slider after inputting the value and it throws an error during number conversion.

### Environment

Angular CLI: 14.0.7
Node: 16.16.0
Package Manager: npm 8.16.0 
OS: darwin x64

### Angular version

14.0.7

### PrimeNG version

14.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.6.0

### Steps to reproduce the behavior

1. Add a `p-slider` element in your application with a template reference `#slider`
2. Add a `p-inputtext` element in your application.
3. Connect the input box with the slider either by using `[(ngModel)]` or `formControlName`.
4. Set the `p-slider` attributes `[step]="0.1" [max]="1" [min]="0"`.
5. Enter value `.2` in the input box.
6. Move the slider with `.2` in the input box.

### Expected behavior

Value `.2` to be converted to `0.2` instead of throwing an error

**Comment by cetincakiroglu** [comment]
Hi,

Cannot replicate the issue please feel free to re-open with a StackBlitz example.

**Comment by vinnyab28** [comment]
> Hi,
> 
> Cannot replicate the issue please feel free to re-open with a StackBlitz example.

Kindly find the [Stackblitz](https://stackblitz.com/edit/primeng-slider-demo-4ueh8v?file=src/app/app.component.html) Example here with steps to reproduce. Reopen this if this is appropriate.

**Comment by cetincakiroglu** [comment]
Hi,

Thanks for sharing reproducer
