### ISSUE TITLE
Multiselect: Add search clear button

### ISSUE THREAD

**Issue by Kisters-BS** [primefaces/primeng#11795]
### Describe the feature you would like to see added

Currently when users search in the multiselect they have to manually clear the search box
![graphic](https://user-images.githubusercontent.com/84901454/183415771-9131fbd1-15d9-4c27-b2ad-94b2115d5f31.png)

### Describe the solution you'd like

I want that when a user writes something in the search input that it can be cleared by clicking on the search icon

![graphic](https://user-images.githubusercontent.com/84901454/183417531-e4875575-e8ab-4c48-a67e-3fc2546a183b.png)

For this there needs to be a new search icon which indicates that it can be cleared.
Something like this (I am not a designer!):

![graphic](https://user-images.githubusercontent.com/84901454/183417746-33852820-8b23-4171-bee7-3e6af5abc056.png)
pi-search-slash

**Comment by cetincakiroglu** [comment]
Hi,

You can use filter templating for custom content.

**Comment by Kisters-BS** [comment]
Hi,

thank you for your suggestion.
