### ISSUE TITLE
OverlayPanel | Close icon overflows in small screen (flipped)

### ISSUE THREAD

**Issue by AlejandraMorenoBS** [primefaces/primeng#11796]
### Describe the bug

When the overlapanel flips the space is not calculated properly and the close button is cut off.

### Environment

![6da08cf1-cdd6-4b2c-8cf6-026d014a1d77](https://user-images.githubusercontent.com/110832912/183436749-7c4a4288-dace-46e4-ae17-ea21275d0583.PNG)

### Angular version

13.0.2

### PrimeNG version

13.3.1

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

16.13.0

### Browser(s)

Chrome 103.0.5060.66, Firefox 97.0.2

### Steps to reproduce the behavior

Open an overlaypanel with not enough space below so that it flips. Adjust the view port until the overlaypanel window fits in the space above the target but not the close icon.

### Expected behavior

The close button should be taken into account when calculating the space the overlay needs.

**Comment by alejandra-moreno-espinar** [comment]
It's very easy to reproduce it using the PrimeNG overlaypanel example: https://stackblitz.com/edit/primeng-overlaypanel-demo.
Shrink the browser in height and the button icon will be cut off.
![610_511_1](https://user-images.githubusercontent.com/110832912/183451000-461df841-29ca-4c66-a97e-d4fa75e3016e.png)

**Comment by alejandra-moreno-espinar** [comment]
Great, many thanks!
