### ISSUE TITLE
Component: Dropdown, how use autoDisplayFirst by assigning string or null for placeholder value?

### ISSUE THREAD

**Issue by withleedh** [primefaces/primeng#11793]
### Describe the bug

I want to use autoDisplayFirst when options length is 1.
However to do that, placeholder should be null to apply autoDisplayFirst.

Then, How can I give null for placeholder? Below is not working
[autoDisplayFirst]="options.length===1"
[placeholder]="options.length>1?--- Select ---':null"

### Environment

primeNg13.0

### Angular version

13.3.6

### PrimeNG version

13.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v16.13.0

**Comment by cetincakiroglu** [comment]
Hi, 

You can achieve this by getters and setters, see the example below.

https://stackblitz.com/edit/primeng-dropdown-demo-ydgqri?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts
