### ISSUE TITLE
Time boundaries for Calendar

### ISSUE THREAD

**Issue by starostin** [primefaces/primeng#1179]
There is no minTime and maxTime options in new calendar. Could you please add them? Thanks.

**Comment by cagataycivici** [comment]
We should add minHour, maxHour, minSeconds and so on...

**Comment by gsbybb** [comment]
This new feature is more useful

**Comment by gsbybb** [comment]
@cagataycivici  There is not have  a callback to invoke when a time is changed ,please add it ! thank you!!

**Comment by cagataycivici** [comment]
PrimeNG 9 uses minDate maxDate for time boundaries.
