### ISSUE TITLE
BlockUI blocks entire page when blocked is true by default

### ISSUE THREAD

**Issue by epaitz** [primefaces/primeng#11792]
### Describe the bug

I believe this is related to the following issue.  [https://github.com/primefaces/primeng/issues/11035](https://github.com/primefaces/primeng/issues/11035) I have recently tried to upgrade our Angular/PrimeNG project from v12 to v14 when I encountered a very similar issue. It looks like the code was changed in PrimeNG at v13 or v14 to fix issue 11035 but it might not have covered all the cases. I have created a public GItHub repo that shows the issue. 
[https://github.com/epaitz/angular-primeng](https://github.com/epaitz/angular-primeng)

The project contains a flexing DIV with three rows top, middle, and bottom. The top DIV has a span that when clicked will toggle blocking the middle DIV. The bottom DIV was just added to show that when the blockUI works correctly it only blocks the middle DIV. Notice that in [app.component.ts blocked = false](https://github.com/epaitz/angular-primeng/blob/master/src/app/app.component.ts#L10) by default and [ViewChild in the blockable-container-div..component.ts](https://github.com/epaitz/angular-primeng/blob/master/src/app/blockable-container-div/blockable-container-div.component.ts#L11) is commented out. 

When the code is run in this configuration the middle DIV is not blocked at startup and clicking on the SPAN in the top DIV will toggle blocking the middle DIV. Now change blocked from false to true in app.component.ts and notice when the app reloads the whole page is blocked not just the middle DIV. The fix for for this is to uncomment the ViewChild in the blockable-container-div.component.ts and reload. Now the app will block the middle div at startup and the toggle will work correctly. 

The problem is this only works in two specific combinations. 

1.  In app.component.ts when blocked is false the ViewChild in blockable-container-div.component.ts must NOT be used.
2. In app.component.ts when blocked is true the VIewChild in blockable-container-div.component.ts must be used.

My blockable-container-div.component.ts/html is a generic blocking component used throughout our application and in some cases needs to be blocked by default and other unblocked by default. Due to the this bug in PrimeNG v14 I can not achieve this because when blocked is true by default I have to use the ViewChild but when blocked is false by default I must NOT use the VIewChid. 

The desired behavior is to be able to use my blockable-container-div.component.ts/html with the BlockUI where its blocked by default in some cases and in in other cases where its not blocked by default (in both cases it must only block the target and not the whole page).

Thanks

### Environment

Angular 14
PrimeNG 14
Node 18.7.0
NPM 8.15.0
VSCode 1.70
Windows 10
MS Edge Browser

### Angular version

14.0.1

### PrimeNG version

14

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.7.0

### Browser(s)

Edge

### Expected behavior

The desired behavior is to be able to use my blockable-container-div.component.ts/html with the BlockUI where its blocked by default in some cases and in in other cases where its not blocked by default (in both cases it must only block the target and not the whole page).

**Comment by cetincakiroglu** [comment]
Hi,

Cannot replicate the issue, please feel free to re-open with a StackBlitz example.
