### ISSUE TITLE
MenuButton: groups multiple items in a popup.

### ISSUE THREAD

**Issue by Rapster** [primefaces/primeng#11808]
### Describe the feature you would like to see added

Similar as https://www.primefaces.org/showcase/ui/menu/menuButton.xhtml

**Comment by cetincakiroglu** [comment]
So what's the difference?

https://stackblitz.com/edit/primeng-menu-demo-8b9lwo?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

**Comment by Rapster** [comment]
Looks great, didn't see you could do it that way. Thanks
