### ISSUE TITLE
Add autofocus to button element

### ISSUE THREAD

**Issue by quranc** [primefaces/primeng#11806]
### Describe the feature you would like to see added

Similar to how other existing components (Dropdown, InputMask, AutoComplete) are possible to have a autofocus property, this could also be a property to the button element.
This can today be done by using angular directives.

### Is your feature request related to a problem?

Instead of having to make a new class/file, this could instead be done by just adding a single attribute to the <p-button> element.

### Describe the solution you'd like

Autofocus enabled:
`<p-button [autofocus]="true"></p-button>`

![autofocus=on](https://user-images.githubusercontent.com/60426609/183604954-8dfd08a3-3a82-4251-b377-cb8e87c56132.png)

Autofocus disabled:
`<p-button [autofocus]="false"></p-button>`
`<p-button></p-button>`

![autofocus=off](https://user-images.githubusercontent.com/60426609/183604946-74608d3d-7eb8-4405-898e-993025f67ee3.png)

### Describe alternatives you have considered

New file/class with autodirectives

### Additional context

Should not be too much work since this is already implemented in other primeng components.

**Comment by cetincakiroglu** [comment]
Hi,

Since this problem occurs across many components, I'm closing this issue and merging them into one https://github.com/primefaces/primeng/issues/11807. We'll fix them altogether.

Thanks for your support and report!
