### ISSUE TITLE
Table/TreeTable：Does it support getting data from a backend server with the help of OData?

### ISSUE THREAD

**Issue by RobersonLuo** [primefaces/primeng#11800]
### Describe the feature you would like to see added

***Question***：
When the the dataset is to large, I want the **Table** or **TreeTable** to support Panination/Filtering with the help of **OData** solution, usually use a backend service (OData or GraphQL) .

Please reference the SlickGrid's solution below:
https://github.com/ghiscoding/Angular-Slickgrid/wiki/OData

Thanks.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
