### ISSUE TITLE
Parent checkbox state incorrect when TreeSelect is being filter

### ISSUE THREAD

**Issue by bon-vivant** [primefaces/primeng#11815]
### Describe the bug

On TreeSelect Filter, filtering selection so that a node with multiple children options is filtered down to displaying just one child option, then selecting the child, causes the parent checkbox to display fully-selected (checked) icon instead of the partially-select (minus) icon. Clearing the filter will redisplay the other children options but parent checkbox is still showing fully-selected (checked) icon:

https://user-images.githubusercontent.com/24819935/184046769-47d7ab26-2064-4563-b96e-f75de9acb8a6.mp4

 

### Environment

Found on 

PrimeNG 14.0.0
Angular 14.1.1

but it was probably an issue in PrimeNG 13 when filter was introduced to the TreeSelect component.

### Angular version

Angular 14.1.1

### PrimeNG version

14.0.0

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

16.14.0

### Steps to reproduce the behavior

1. Open TreeSelect dropdown
2. Filter a multiple children node down to so that at least one child option is filtered out
3. Select all available children in the node until parent checkbox shows fully-selected (checked) icon
4. Clear the filter so that all children are now visible and nothing is filtered out
5. Observe that parent checkbox is still displaying fully-selected (checked) icon

### Expected behavior

Parent checkbox should be displaying partially-selected (minus) icon either by step 3 or step 4.

If at least one but not all child options of a node are selected, parent checkbox should display partially-selected (minus) icon. Parent checkbox should only display fully-selected (checked) icon when all its children options are selected.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by LucasBurgat** [comment]
Hello,

This is still an issue as of version 16.0.2
Tested by adding [filter]="true" to the official documentation TreeSelect checkbox Stackblitz demo

**Comment by nur-kjaeger** [comment]
@bon-vivant 
Can you reopen this issue? This is still an issue in 17.6

[stackblitz](https://stackblitz.com/edit/4rtnwa?file=src%2Fapp%2Fdemo%2Ftree-select-basic-demo.html)

**Comment by bon-vivant** [comment]
I don't see a way to reopen the issue on the page (screenshot of what I'm seeing), just a Comment button (screenshot of what I'm seeing). 
@mertsincan are you able to reopen the issue or should a new issue typically be created in this situation?

![image](https://github.com/primefaces/primeng/assets/24819935/768fc421-9a6e-418c-ad88-e2a249502cd4)

**Comment by GabGuev** [comment]
Hi, I'm not sure if this will help anyone, but I had the same problem and the only thing that helped was to add a unique key in all the TreeNode.
The key should be mandatory, but technically is not. 

![Image](https://github.com/user-attachments/assets/638e2c48-0e51-4103-9e35-e9d74c3a8c96)

**Comment by sebastiandenis** [comment]
Still an issue with v20 :/
