### ISSUE TITLE
p-table with virtual scroll re-renders everything when scrolling up

### ISSUE THREAD

**Issue by Developer-Thing** [primefaces/primeng#11812]
### Describe the bug

When using p-table with virtual scroll enabled, and when scrolling to the, for example, half of the scrollbar, and then when scrolling up, the p-table will re-render all the items which will produce a flash-like effect. 

This is not happening when the table is scrolled down.

### Environment

macOS Monterey 12.3.1

### Reproducer

(https://stackblitz.com/edit/primeng-tablevirtualscroll-demo-mutewf?file=src%2Fapp%2Fapp.component.html,package.json,src%2Fapp%2Fapp.component.ts)

### Angular version

14.1.0

### PrimeNG version

14.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.13.0

### Browser(s)

Chrome 104.0.5112.79

### Steps to reproduce the behavior

1. Scroll down to half of the scrollbar. This will load the appropriate slice of data
2. Scroll up bit by bit until another slice of data has to be loaded
3. The table flashes and all the items are re-rendered, not only the missing ones from the top

### Expected behavior

1. Scroll down to half of the scrollbar. This will load the appropriate slice of data
2. Scrolling up bit by bit until another slice of data has to be loaded, will only render the missing items on the top

**Comment by Developer-Thing** [comment]
When I use this:
```
    this.virtualCars = Array.from({ length: 1000 }).fill({
      field: '',
      header: '',
    });
```
Instead of:
`    this.virtualCars = Array.from({ length: 1000 });`

Table cells are rendered first and the flash-like effect is gone.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
