### ISSUE TITLE
CascadeSelect:   some new features need to be supported

### ISSUE THREAD

**Issue by RobersonLuo** [primefaces/primeng#11828]
### Describe the feature you would like to see added

I have a hierarchical data below and want to use PrimeNG Component to show on UI:

1、I used **TreeSelect**，but it does not support **OptionValue/OptionLabel** to get the property value (eg. id or name). The **TreeSelect** always retrn the whole **TreeNode** object.   

The **TreeSelect**  use the **TreeNode** object, but I think the original object is ok, no need to convert the original object to the TreeNode, so I give it up and used the component **CascadeSelect**.

2、So, I used the 'CascadeSelect' and I found some features  need to be supported:

- support multi-selection like **MultiSelect** component with 'checkbox'.
- support selecting arbitray object, not only selecting the leaf object (the parent object can be selected too!)
- when used in **Dialog** component and the parent items are too many,  the "vertical scroll bar" does not appear (result in the last items can't be seen).

![image](https://user-images.githubusercontent.com/7013492/184780938-20b74abd-4032-4100-96f9-78d77aaf91d6.png)

***Json data***
    [
  {
    "id": 1,
    "parentId": null,
    "name": "A1",
    "children": [
      {
        "id": 2,
        "parentId": 1,
        "name": "A2",
        "children": []
      },
      {
        "id": 3,
        "parentId": 1,
        "name": "A3",
        "children": []
      }
    ]
  },
  {
    "id": 4,
    "parentId": null,
    "name": "A4",
    "children": [
      {
        "id": 5,
        "parentId": 4,
        "name": "A5",
        "children": [
          {
            "id": 6,
            "parentId": 5,
            "name": "A6",
            "children": []
          }
        ]
      }
    ]
  }
]

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
