### ISSUE TITLE
scrollable tabView not working with rtl

### ISSUE THREAD

**Issue by RezaMakvandi** [primefaces/primeng#11827]
### Describe the bug

the tabView component doesn't work correctly with scrollable as true in rtl direction

### Environment

Angular : 14.0.4
primeng : ^14.0.0-rc.1

### Angular version

14.0.4

### PrimeNG version

^14.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

4.17.5

### Browser(s)

chrome

### Expected behavior

The next and prev buttons must reversed (both in their position and their behavior)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
