### ISSUE TITLE
Accordion children elements still receive keyboard focus even when the panel is collapsed

### ISSUE THREAD

**Issue by rt701** [primefaces/primeng#11821]
### Describe the bug

This issue was originally closed here: https://github.com/primefaces/primeng/issues/4986 but it is still occurring.

**Current behavior**
The children of a collapsed panel receive keyboard focus.

**Expected behavior**
Items present inside a collapsed accordion panel should not receive keyboard focus.

### Environment

- **Angular version:** 9.1.13, 11.2.14
- **PrimeNG version:** 9.1.3, 11.0.0
- **Browser:** Tested on Microsoft Edge and Google Chrome

### Reproducer

https://stackblitz.com/edit/primeng-accordion-demo-zzuxkh?file=src/app/app.component.html

### Angular version

13.0.3

### PrimeNG version

13.0.4

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14.2 and later

### Steps to reproduce the behavior

1. Tab to a closed accordion tab with a focusable child element.
2. Tab again, and then you will see that the focus goes inside to the child element.
3. This is an error, since it should tab to the next non-hidden element.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by msftedad** [comment]
Hi @mertsincan, Issue is still repro'ing in the latest environment. Please reopen this issue
