### ISSUE TITLE
Table: Virtual scrollable table is not visible inside of a sidebar

### ISSUE THREAD

**Issue by markusvorraber** [primefaces/primeng#11835]
### Describe the bug

I have a table with virtualscroll and lazy set, but the table will not show up inside of a sidebar. Outside of a sidebar the table shows up as expected.
The problem is because of the new p-scroller component (starting with primeng v14).
The p-scroller div element has a height of 0 set.

### Environment

OS: Windows

### Reproducer

https://stackblitz.com/edit/angular-ivy-tuq23w

### Angular version

14.1.2

### PrimeNG version

14.0.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.7.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

Go to Stackblitz example, click button "open sidebar". the table is not rendered.

### Expected behavior

The table should also be rendered inside of a sidebar.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by markusvorraber** [comment]
Thanks, it seems with the new version 14.2.1 the issue is resolved!
