### ISSUE TITLE
Feature: Expose notation field on InputNumber

### ISSUE THREAD

**Issue by albert-m-willemsen** [primefaces/primeng#11830]
I understand that [InputNumber](https://www.primefaces.org/primeng/inputnumber) uses [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat) internally.
Would it be possible to expose the notation option to display the number as "scientific", "engineering" or "compact" when it's not being edited?

**Comment by albert-m-willemsen** [comment]
This would mean the input of E should be allowed.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by fbergmann** [comment]
I'm afraid it is still not possible to define the `notation` field on `InputNumber`. It would be really great if this would be possible. It would be great to enter / display values like `1e-9`, `1e-12` and the like.
