### ISSUE TITLE
p-inputSwitch placed in sticky headers table is being shown on top of header while scrolling

### ISSUE THREAD

**Issue by zozo8** [primefaces/primeng#11832]
### Describe the bug

p-inputSwitch placed in sticky headers table is being shown on top of header while scrolling, what makes strange, visual effect. Please see stackblitz attached:
https://stackblitz.com/edit/primeng-tablesticky-demo-ahfuna?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.module.ts

![image](https://user-images.githubusercontent.com/50959052/185041170-4c8ead0a-8cca-4c1d-84b2-c46dba3c3e73.png)

### Environment

Google Chrome 104.0.5112.81
Windows 11

### Reproducer

https://stackblitz.com/edit/primeng-tablesticky-demo-ahfuna?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.module.ts

### Angular version

11.0.4

### PrimeNG version

13.0.4

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

0.0.0.

### Browser(s)

Chrome

### Expected behavior

Switches should be hidden under the header as other controls

**Comment by quranc** [comment]
The problem occurs when not having a set z-index property that specifies the stack order of elements.
However, adding `z-index: 1;` to your styles will make it work.
```
styles: [
    `
        :host ::ng-deep .p-datatable .p-datatable-thead > tr > th {
            position: -webkit-sticky;
            position: sticky;
            top: 0px;
            z-index: 1;
        }

        @media screen and (max-width: 64em) {
            :host ::ng-deep .p-datatable .p-datatable-thead > tr > th {
                top: 0px;
            }
        }
  `,
  ],
```

This is probably something that should be added to the "Sticky Table" documentation.

**Comment by zozo8** [comment]
Thank you, it solves the issue!
