### ISSUE TITLE
p-confirmPopup: Does not show even with a valid target

### ISSUE THREAD

**Issue by psarno** [primefaces/primeng#11831]
### Describe the bug

My code looks like this:

```
    console.log(this.contextEvent.target);

    this.confirmationService.confirm({
      target: this.contextEvent.target ? this.contextEvent.target : undefined,
      message: 'Are you sure that you want to proceed?',
      icon: 'pi pi-exclamation-triangle',
      accept: () => { console.log('accepted')  }
    });
```

The console.log is properly showing a valid target that I want the confirmation pop-up to appear on.   However, it never shows up and no errors are shown in the console.

### Environment

Angular 14.0.3
PrimeNG 14.0.0

### Reproducer

https://stackblitz.com/edit/github-gz4bm8?file=src/app/app.component.ts

### Angular version

14.0.3

### PrimeNG version

14.0.0

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

16.13.1

### Steps to reproduce the behavior

The repro in Stackblitz shows the behavior.

1. Click on the ellipse button to show a context menu
2. Select "Email" on that menu
3. A confirmation dialog should appear, but it does not.

### Expected behavior

A confirmation dialog should appear at the location of the valid event target.

**Comment by volvachev** [comment]
Hi, could you please update the link(stackblitz)?

**Comment by psarno** [comment]
@volvachev The following should show the example.

In this case, I want the confirm popup to target the button after the context menu item has been clicked.   If I am approaching this wrong, let me know, but the console does show a valid event target.

https://stackblitz.com/edit/github-gz4bm8?file=src/app/app.component.ts

**Comment by volvachev** [comment]
> @volvachev The following should show the example.
> 
> In this case, I want the confirm popup to target the button after the context menu item has been clicked. If I am approaching this wrong, let me know, but the console does show a valid event target.
> 
> https://stackblitz.com/edit/github-gz4bm8?file=src/app/app.component.ts

Hi, I have updated the example (https://stackblitz.com/edit/github-gz4bm8-mrihjk). But you need to use `setTimeout` there to make it work. I also opened a fix in the library.
