### ISSUE TITLE
p-calendar: Inline mode does not work inside p-dialog

### ISSUE THREAD

**Issue by psarno** [primefaces/primeng#11837]
### Describe the bug

When attempting to show the `p-calendar` inside of a `p-dialog` in `inline` mode, the calendar does not render properly.

![Calendar Not Shown](https://user-images.githubusercontent.com/18640860/185150992-767bc84a-e8ed-440b-ba0b-743f9b218f90.png)

The code is very straightforward and can be reproduced with the link below.

### Environment

Angular 14.0.3
PrimeNG 14.0.0

### Reproducer

https://stackblitz.com/edit/github-5ggjdt?file=src/app/app.component.html

### Angular version

14.0.3

### PrimeNG version

14.0.0

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

16.13.1

### Steps to reproduce the behavior

1. Open Stackblitz repro
2. Click "Click Me" button

### Expected behavior

The calendar should be shown inline inside of the dialog component.

**Comment by Urtgard** [comment]
I don't know why, but it works with the content template: https://github.com/primefaces/primeng/issues/10978

**Comment by cetincakiroglu** [comment]
Hi,

Give a width and it will work.

https://stackblitz.com/edit/github-5ggjdt-kulnuu?file=src%2Fapp%2Fapp.component.html
