### ISSUE TITLE
Table: virtual scroll renders datasets smaller than scrollheight incorrectly

### ISSUE THREAD

**Issue by remackgeek** [primefaces/primeng#11840]
### Describe the bug

Table: virtual scroll renders datasets smaller than scrollheight incorrectly

I have a table that contain different sized datasets based on external controls.
When the dataset is smaller than the scrolling area, scrollbars appear and you can scroll the data up under the header.

This only happens with angular/primeng 14. angular/primeng 13 works as expected.

### Environment

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 14.1.3
Node: 14.20.0
Package Manager: npm 8.13.2
OS: win32 x64

Angular: 14.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1401.3
@angular-devkit/build-angular   14.1.3
@angular-devkit/core            14.1.3
@angular-devkit/schematics      14.1.3
@angular/cdk                    14.1.2
@schematics/angular             14.1.3
rxjs                            7.5.6
typescript                      4.7.4
    "@angular/cdk": "^14.1.2",
    "primeflex": "^3.2.1",
    "primeicons": "^5.0.0",
    "primeng": "^14.0.1",

### Reproducer

https://stackblitz.com/edit/angular-ivy-srcfz1

### Angular version

14.1.3

### PrimeNG version

14.0.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.20.0

### Browser(s)

chrome, firefox

### Steps to reproduce the behavior

1) using example, start with "Large Dataset"
2) scroll down a bit
3) click on "Small Dataset"

The newly-rendered data is scrolled down as far as possible, hiding the first row and most of the second.
If there was only one row returned, the user might not think there were any results.

### Expected behavior

The 2 returned rows displayed with no scrollbar

**Comment by edriburk** [comment]
This regression is a problem for my team also. This will block us from upgrading our project to v14.

**Comment by JamesSCADA98765** [comment]
This is an issue for me as well. It is delaying the launch of our project because we require feature enhancements of version 14 but tables are no longer scrolling properly.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by remackgeek** [comment]
I updated to the latest version(s) and this appears to be working correctly now. Thanks!
