### ISSUE TITLE
MenuBar : Parent menuItem does not get active when clicking on a child routerLink

### ISSUE THREAD

**Issue by alfredott** [primefaces/primeng#11847]
### Describe the bug

Hello :)

First, thanks for all the work you're doing on PrimeNg !
I'm currently working with the MenuBar component. It works quite perfectly, but I happen to stumble on something.

I explained my bug in the stackblitz below.

Can you please : 
- confirm me whether you think it's a bug or not ?
- tell me if you have any plan to fix it ?
- tell me if you know any better workaround than the one I found ?

Feel free to ask any more information.

Thanks in advance and have a nice day :)

PS : I also tried using the styleClass property, but I cannot pass a dynamic string to it.

### Environment

I tried on my personal project, plus made a stackblitz for you to reproduce it.

### Reproducer

https://stackblitz.com/edit/github-qk4thj-znr5qm

### Angular version

11 (on the stackblitz template), 13 (on my project), ...

### PrimeNG version

14 (stackblitz), 13 (my project), ...

### Build / Runtime

Angular CLI App

### Language

ES6

### Node version (for AoT issues node --version)

14.15.4

### Steps to reproduce the behavior

Instructions are listed in the stackblitz

### Expected behavior

Behavior is explained in the stackblitz

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
