### ISSUE TITLE
Bug when using input mask when run in mobile mode

### ISSUE THREAD

**Issue by ritox842** [primefaces/primeng#1185]
Hey all.

I'm building a mobile application and I want to use input mask.
When I start to type I get the following error:

![image](https://cloud.githubusercontent.com/assets/7280441/19920140/9646ab82-a0df-11e6-82fe-861b154abf63.png)

As i dag in a little bit, I saw that it because the ngPrime thinks its on android device and not on desktop in mobile development mode.
Moreover if a quit the mobile mode and using the app as desktop app, the error is gone.

How Can I add a fallback to desktop mode?

thanks,
Gili.

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/VZbdZfQ7SuTV87tTkbYR
