### ISSUE TITLE
[FEATURE REQUEST]:  Print Directive

### ISSUE THREAD

**Issue by rrekapalli** [primefaces/primeng#11854]
### Describe the feature you would like to see added

A "Print" directive to print a given DIV identified by an "id" to either an image or a PDF (format).   

### Describe the solution you'd like

E.g:

`<div p-print [format]="pdf" id="section-to-be-printed">...</div>`

**Comment by cetincakiroglu** [comment]
To simplfy,

You can achieve it by CSS without using any JavaScript https://www.tutorialspoint.com/css/css_printing.htm
