### ISSUE TITLE
table: column reorder indicator buggy

### ISSUE THREAD

**Issue by capc0** [primefaces/primeng#11860]
### Describe the bug

Indicators when columns are drag&dropped from left to right where the mouse does not leave the table header do not work. Most of the time there are invisible.

reproducable in the docs: https://www.primefaces.org/primeng/table/reorder

depending on the order of `onColumnDragLeave` & `onColumnDragEnter` it may work or not.

wrapping https://github.com/primefaces/primeng/blob/master/src/app/components/table/table.ts#L2060 in a `setTimeout` is a workaround

### Environment

see below

### Angular version

14

### PrimeNG version

14

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14

**Comment by alinalexandru-bi** [comment]
I can also reproduce this bug. See the attachment.

https://user-images.githubusercontent.com/30142414/191950405-21f85eb5-47b2-43ae-974b-c80e34b157d0.mp4

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
