### ISSUE TITLE
p-radioButton: Set preselection with a key instead of an object

### ISSUE THREAD

**Issue by mohammadreza99** [primefaces/primeng#11863]
### Describe the bug

Need to set a default value for `p-radioButton` with a specific key of provided values. but now we can preselect the component just by passing whole object. The ideal is to behave like p-dropdown.

### Environment

windows

### Angular version

14.1.0

### PrimeNG version

14.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.6.4

**Comment by cetincakiroglu** [comment]
Hi,

Same preselection logic applied to both components, cannot replicate your issue.

https://stackblitz.com/edit/primeng-dropdown-demo-oth3y2?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html
