### ISSUE TITLE
Autocomplete: input value renders null on SSR

### ISSUE THREAD

**Issue by Jonnyprof** [primefaces/primeng#11867]
### Describe the bug

Autocomplete shows null value when we come from server rendering, if there is no initialized value.
I've tested and fixed in localhost and the error is caused by `return data !== (null || undefined) ? data : '';` (line 630) because `(null || undefined)` is always undefined, so if `data === null` it returns `data`, which is null. The first time that autocomplete  is loaded `ObjectUtils.resolveFieldData(value, this.field)` returns `null`, so it will render null.
https://github.com/primefaces/primeng/blob/085a6040181e6a2c4091c56ff7b9be79111dbb71/src/app/components/autocomplete/autocomplete.ts#L628-L631
With `return data ?? ''` should be solved.

I paste and example of returned input in a SSR request, with null in the value property:
```html
<input aria-autocomplete="list" role="searchbox" class="p-element ng-tns-c125-2 p-autocomplete-input p-inputtext p-component ng-star-inserted" autocomplete="off" value="null" type="text" placeholder="Escribe para ver marcas y modelos" aria-label="Escribe para ver marcas y modelos">
```

Another problem is that when you bind value in angular view like this `[value]="inputFieldValue"` you must check null values or SSR render it like null. The solution is the same check as before: `[value]="inputFieldValue ?? ''"`

### Environment

Any environment

### Angular version

14.1.3

### PrimeNG version

14.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.17.0

### Steps to reproduce the behavior

In a project with SSR, place an autocomplete component and visit the page. The html returned is something like:
```html
<input aria-autocomplete="list" role="searchbox" class="p-element ng-tns-c125-2 p-autocomplete-input p-inputtext p-component ng-star-inserted" autocomplete="off" value="null" type="text" placeholder="Escribe para ver marcas y modelos" aria-label="Escribe para ver marcas y modelos">
```
and you can see "null" value inside the input of the component.

### Expected behavior

It should show placeholder value if it has or the input with no value

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by Jonnyprof** [comment]
This is still happening, so `resolveFieldData` method hasn't changed.

@mertsincan please reopen it

**Comment by cetincakiroglu** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.
