### ISSUE TITLE
Calendar | InputMask support

### ISSUE THREAD

**Issue by GhoshWorld** [primefaces/primeng#11874]
### Describe the feature you would like to see added

In p-calendar I'm not able to put masking behaviour. Example: If user enters 08262022, I want to change it to 08/26/2022. How is it possible? Please give any suggestions

**Comment by cetincakiroglu** [comment]
Hi,

Mask is not a feature of the calendar component. This feature will be implemented in the future. I'll change the topic and mark it as enhancement.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
