### ISSUE TITLE
Filter for null/empty values on table component

### ISSUE THREAD

**Issue by juulian98** [primefaces/primeng#11875]
### Describe the feature you would like to see added

It would be very useful if there was a way to filter empty or null/undefined values ​​separately for all filter types (string, date, number). The lines where certain fields are not filled are often particularly interesting. This cannot currently be realized with the table component.

### Is your feature request related to a problem?

My datasets often consist of rows whose value is null.

### Describe the solution you'd like

Either you could click on Apply for the filter type "equals" if the filter is empty.  Then it would be checked against empty values, so to speak.  A new filter type “Empty” would be even better.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
