### ISSUE TITLE
Multiselect Dropdown: Filter elements without select all option

### ISSUE THREAD

**Issue by ignatij** [primefaces/primeng#11879]
### Describe the feature you would like to see added

**Current Situation**:
Currently when the **filter** field is active on the multiselect dropdown, the panel to filter elements by an input text and the checkbox to select all items is shown:
![image](https://user-images.githubusercontent.com/12376229/187216481-75125cad-3907-4763-adca-ab5406c819e9.png)

**Desired Behaviour**
Add the possibility to filter the elements in the multiselect dropdown list, but without the option to select all items. Something like the following:
![image](https://user-images.githubusercontent.com/12376229/187216719-0fac98ef-c1c2-4bc8-92a5-38921ccac8ce.png)

### Is your feature request related to a problem?

Yes. We have a clear requirement from the client that they want to be able to select only few items from the multiselect dropdown, but to be able to filter the items by the input text due to the size of the list.
The reason is quite simple. The list of the items is pretty huge and selecting all of the items should not be possible because it would bring a heavy load on the backend system.

### Describe the solution you'd like

Be able to filter elements from the multiselect dropdown list but without the option to select all of the items because it will bring an enormous heavy load on the backend system.

### Describe alternatives you have considered

We can hide the checkbox using ng-deep (deprecated and not recommended for usage)

### Additional context

Angular: 14.0.3
PrimeNG: 14.0.2

**Comment by cetincakiroglu** [comment]
Hi,

Component already has that feature and it's called filterTemplate. You can customize the filter section as you wish, please read the docs (custom content section).
