### ISSUE TITLE
Error in Angular2 App after PrimeNG rc.1 upgrade

### ISSUE THREAD

**Issue by kcsahoo** [primefaces/primeng#1188]
I am getting this error after upgrade from beta.20 to rc.1. The application was working fine up to beta.20

zone.js:1382 GET http://localhost:2473/traceur 404 (Not Found)scheduleTask @ zone.js:1382ZoneDelegate.scheduleTask @ zone.js:245Zone.scheduleMacroTask @ zone.js:171(anonymous function) @ zone.js:1405send @ VM107:3fetchTextFromURL @ system.src.js:1051(anonymous function) @ system.src.js:1778ZoneAwarePromise @ zone.js:518(anonymous function) @ system.src.js:1777(anonymous function) @ system.src.js:2806(anonymous function) @ system.src.js:3384(anonymous function) @ system.src.js:3707(anonymous function) @ system.src.js:4099(anonymous function) @ system.src.js:4562(anonymous function) @ system.src.js:4831(anonymous function) @ system.src.js:407ZoneDelegate.invoke @ zone.js:232Zone.run @ zone.js:114(anonymous function) @ zone.js:502ZoneDelegate.invokeTask @ zone.js:265Zone.runTask @ zone.js:154drainMicroTaskQueue @ zone.js:401ZoneTask.invoke @ zone.js:339

zone.js:232 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:2473/traceur(…)ZoneDelegate.invoke @ zone.js:232Zone.run @ zone.js:114(anonymous function) @ zone.js:502ZoneDelegate.invokeTask @ zone.js:265Zone.runTask @ zone.js:154drainMicroTaskQueue @ zone.js:401ZoneTask.invoke @ zone.js:339

**Comment by cagataycivici** [comment]
Try with upcoming RC2 please, it will fix it. Related to #1186

**Comment by philwith** [comment]
I am getting this error with rc.2.  beta.20 working for me.
