### ISSUE TITLE
Dropdown selecting an unwanted option when pressing Control key on the keyboard

### ISSUE THREAD

**Issue by steffibreuer** [primefaces/primeng#11889]
### Describe the bug

similar to #10113, but with the control key instead of the meta key

This is especially a problem when pressing ctrl + s to save the form.

### Environment

Windows 10

### Angular version

14.1.2

### PrimeNG version

14.0.1

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

16.17.0

**Comment by jayee** [comment]
Yes, a real blocking issue that is affecting us too.

**Comment by cetincakiroglu** [comment]
Hi,

I've tried to reproduce the bug but it seems somehow it solved with PrimeNG +v13 however it can be reproducible with the previous versions such as https://github.com/primefaces/primeng/issues/10113 . I've updated the package.json is it still exist? If it is, please explain how to reproduce it. Here is the Stackblitz example https://stackblitz.com/edit/primeng-dropdown-demo-5bxegh?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html
