### ISSUE TITLE
P-Table: Resizer

### ISSUE THREAD

**Issue by mcwebdev** [primefaces/primeng#11880]
### Describe the bug

The **p-column-resizer-helper** is not positioned correctly when a grid has a header section `<ng-template pTemplate="caption">...</ng-template>`

It seems it should be querying `class="p-datatable-wrapper"` for positioning. 

### Environment

localhost

### Angular version

14

### PrimeNG version

14

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

latest

### Browser(s)

chrome

**Comment by cetincakiroglu** [comment]
Hi,

Cannot replicate the issue could you please provide a Stackblitz example by using PrimeNG Issue Template https://stackblitz.com/github/primefaces/primeng-issue-template

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
