### ISSUE TITLE
Table: Scrolling when the content fits in the viewport should be prevented

### ISSUE THREAD

**Issue by sotjdisc** [primefaces/primeng#11892]
### Describe the bug

On a table with virtual scrolling and lazy loading, scrollbars and scrolling is allowed, although the table contains only a few rows which fit on the given height.

### Environment

Windows 10, Chrome latest

### Reproducer

https://stackblitz.com/edit/primeng-tablevirtualscroll-demo-xebdjk?file=src/app/app.component.html

### Angular version

14.2.0

### PrimeNG version

14.0.2

### Build / Runtime

TypeScript

### Language

ALL

### Node version (for AoT issues node --version)

16.17

### Steps to reproduce the behavior

Open the stackblitz link and check out the table.

### Expected behavior

No scrollbars and no scrolling when content fits in the table.

**Comment by vstiebe** [comment]
If you change the scrollHeight to "flex" it shows nothing.
If you change the scrollHeight to "flex" without lazy loading the table grows infinitally.

https://primeng-tablevirtualscroll-demo-ogh1zq.stackblitz.io

Is this related to this issue?

**Comment by JamesSCADA98765** [comment]
This issue seems related (potentially identical) to [Issue 11840](https://github.com/primefaces/primeng/issues/11840).

I have the same issue as well and would greatly hope the bug gets fixed soon. It's slowing down a launch for me.
