### ISSUE TITLE
Uniquely ID stylesheets that are added to DOM.

### ISSUE THREAD

**Issue by mcwebdev** [primefaces/primeng#11891]
### Describe the feature you would like to see added

I would like any stylesheet dynamically added to DOM to have a unique ID.

Example: Resizing grid columns adds a stylesheet with widths specified with `!important`.

I have an eject button that resets the grids column widths in localStorage, but requires a page refresh because the styles are still there.

If the dynamically loaded stylesheets had an id, I could remove them from DOM.

### Is your feature request related to a problem?

I am unable to reset the grid to its default column widths after user has selected custom column widths.

### Describe the solution you'd like

<style id="columnWidths"></style>

### Describe alternatives you have considered

Forcing page refresh

**Comment by cetincakiroglu** [comment]
Hi,

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 
For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
