### ISSUE TITLE
DataTable: maximize attribute

### ISSUE THREAD

**Issue by adurmus** [primefaces/primeng#11899]
### Describe the feature you would like to see added

Similar to `dialog` maximize feature.  When maximize icon is clicked it will pop the data table in its own dialog from page and then the table can be maximized to full screen.

**Comment by cetincakiroglu** [comment]
Hi,

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 
For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
