### ISSUE TITLE
DataTable header & footer columns are not displayed when scrollable="true"

### ISSUE THREAD

**Issue by Krustie101** [primefaces/primeng#1189]
When the scrollable flag is set to true on the DataTable component, the header & footer columns are not shown if headerColumnGroup or footerColumnGroup is used.

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/VZbdZfQ7SuTV87tTkbYR
