### ISSUE TITLE
What is the best way to Reset pagination to 1st page in Lazy table?

### ISSUE THREAD

**Issue by kissy0205** [primefaces/primeng#11896]
Hi,

Trying to rewrite some legacy code. I wanted to reset the lazy table pagination on button click when user is on different page.

this is my [StackOverflow](https://stackoverflow.com/questions/73604730/how-to-refresh-the-lazy-table-and-reset-the-pagination-to-1-primeng-and-angula) question.

[STACKBLITZ](https://stackblitz.com/edit/primeng-tablelazy-demo-96eod3)

Requirement:

1. lazy table refreshing every time when user click on different page
2. when user is 4th page and click on refresh button both table and pagination reset to 1st page.

As am new to this PrimeNG, I'm not able to fine proper documentation for lazy table pagination reset. and stuck on same place for 2 days.

Thanks for helping me on this

@vincent @DerekLiang @csokun @Skyr @bossqone

**Comment by cetincakiroglu** [comment]
Here I refactored your example to reset table state on refresh click

https://stackblitz.com/edit/primeng-tablelazy-demo-prj1ye?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html
