### ISSUE TITLE
Global Filter on dataTable not working

### ISSUE THREAD

**Issue by TomVuillemin** [primefaces/primeng#119]
On the showcase, the global filter does not seems to work : http://www.primefaces.org/primeng/#/datatablefilter

I have reproduced the issue on a local installation with angular2 beta 9 and primeng 0.7

**Comment by cagataycivici** [comment]
It works for me online, maybe a cache issue?

**Comment by pravnviji** [comment]
I am using ng version 2.4.3. I have reproduced the same issue, even consuming service from online as well as local.
