### ISSUE TITLE
Button: lose style after changing label

### ISSUE THREAD

**Issue by paulstelzer** [primefaces/primeng#11900]
### Describe the bug

If you add the button styles conditionally and you change the label afterwards, the button loses the style.

In the example the button has outlined style by default. If you now switch the style to primary and change the label, the button  now has the outline style again. You have to press the button twice to get the correct style again.

https://user-images.githubusercontent.com/20501666/188579798-07f72479-25fd-4c41-9971-374c58961fa5.mov

### Environment

-

### Reproducer

https://stackblitz.com/edit/github-6b5i6s?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html

### Angular version

14

### PrimeNG version

14

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16

### Steps to reproduce the behavior

1. Tap on the Enable / Disable Filter Button
2. Style of Button has to be primary
3. Tap on the Change Label Button
4. Style of Button is outline (no primary anymore)

### Expected behavior

Button style should still be primary

**Comment by cetincakiroglu** [comment]
Hi,

There is a separate button component for this functionality. You can use "toggle button" for it.
https://primefaces.org/primeng/togglebutton
