### ISSUE TITLE
use tsconfig.json's "lib": ["es6"] instead of @types/core-js

### ISSUE THREAD

**Issue by ribizli** [primefaces/primeng#1191]
This is supported since typescript 2.0 and is used by `angular-cli` too.

If I use both I get `"Duplicate identifier"` error.

**Comment by cagataycivici** [comment]
Can you elaborate please, where to put it, what to change? What is the purpose of this change?

**Comment by ribizli** [comment]
My former tsconfig.json was containeng a `lib` entry (borrowed from `angular-cli`):
```
{
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es6", "dom"], <-- check out this
    "module": "es6",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5"
  }
}
```
In this case the dependency `@types/core-js` (!!!not the polyfill, just the typing) is not needed for typescript compiler.
However the current RC.1 version of PrimeNG `*.d.ts` files reference the core-js typings (wasn't the case before):
```
/// <reference types="core-js" />
```

This causes the error with my build.

My solution/workaround is now to also use `@types/core-js` and leave out the `lib` settings form the `tsconfig.json`.

**Comment by cagataycivici** [comment]
Good coincidence, we were trying the same solution and it worked as well. Will do RC2 with this so we can avoid core-js /// reference in npm package.
