### ISSUE TITLE
Component: Support to add icon as a rangeSeparator.

### ISSUE THREAD

**Issue by MohitChandane** [primefaces/primeng#11926]
### Describe the feature you would like to see added

Can we add the support to add an icon as a rangeSeparator ? Currently it only accepts value in string.

### Describe the solution you'd like

I need to add an icon instead of a '-', which a default rangeSeparator.

**Comment by cetincakiroglu** [comment]
Hi,

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 
For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
