### ISSUE TITLE
Table "Sticky" headers fail to "stick" when a table is placed inside an Accordion panel

### ISSUE THREAD

**Issue by rosenthalj** [primefaces/primeng#11924]
### Describe the bug

A p-table with "sticky" columns fail to "stick" when placed within a p-accordion. 

The following movie demonstrates the bug.   I reproduced the bug by modifying the [Table Sticky Demo](https://www.primefaces.org/primeng/table/sticky).  The left column contains a sticky table within a Accordion panel where the table column headers don't stick.  The right column contains a standalone sticky table where the table column headers stick.

https://user-images.githubusercontent.com/45439491/189695937-e3560fc7-3ef9-4bfa-a8eb-59610dff5538.mov

This bug was induced when bug #11617 was fixed.

![csschanges2](https://user-images.githubusercontent.com/45439491/189703202-fc970b2c-8fa0-40df-b326-e7934df208a7.gif)

### Environment

Happens in both stackblitz and local project

### Reproducer

https://stackblitz.com/edit/primeng-tablesticky-demo-bapq4c?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.css,src%2Fstyles.css,src%2Fapp%2Fapp.component.spec.ts

### Angular version

14.2.1

### PrimeNG version

14.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14+

### Browser(s)

All Browsers

### Steps to reproduce the behavior

https://primeng-tablesticky-demo-bapq4c.stackblitz.io/

Scroll up and down.

The column headers of the left table (within a p-accordion panel) will not stick. -- bad
The column headers of the right table (standalone) will stick. -  good

### Expected behavior

Sticky tables within an Accordion panel will have columns that stick.

**Comment by kAgotsi** [comment]
Hello, I'm facing same issue, I tried fix : 

```
.p-accordion-tab-active > .p-toggleable-content:not(.ng-animating) {
  overflow: visible;
}
```
But it doesn't work.
Can somebody help me ?
