### ISSUE TITLE
Component: Calendar

### ISSUE THREAD

**Issue by pudrik** [primefaces/primeng#11922]
### Describe the feature you would like to see added

Currently the range mode spawns months from today and onward. (example Aug-Sep) using numerOfMonths=2
but it would be more useful if you could tell it what month to start the display in. like Jul-Aug as if you utilize it in a maxdate=today there is no point in showing upcoming months as a loading default but instead you want to see previous months.

### Is your feature request related to a problem?

No point in showing next months if maxDate is inside this month.

### Describe the solution you'd like

attribute for instance startMonth=8

**Comment by cetincakiroglu** [comment]
Hi,

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 
For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
