### ISSUE TITLE
MenuItem visible property not working in Menu <p-menu> with sub items.

### ISSUE THREAD

**Issue by jonnomk** [primefaces/primeng#11928]
**Describe the bug**
If you set visible to false for a parent MenuItem when there are children, the children are hidden, but the parent is not.

**Environment**
Windows 11

**Angular version**
14.2.1

**PrimeNG version**
14.0.2

**Build / Runtime**
Angular CLI App

**Node version**
14.17.0

**Browser(s)**
Chrome 105.0.5195.102

**Steps to reproduce**
Using the below model for menu with sub items:

![image](https://user-images.githubusercontent.com/56191325/189907532-2844f496-c6b9-4427-92a9-96c052e24b71.png)

...results in the below output.

![image](https://user-images.githubusercontent.com/56191325/189907801-3b12645a-cba3-4c6e-833d-47cc6ed060f9.png)

**Expected behaviour**
The parent AND it's children should not be even rendered to the DOM, let alone hidden.

**StackBlitz**
https://stackblitz.com/edit/primeng-menu-visible-issue

**Comment by cetincakiroglu** [comment]
Hi,

Cannot replicate the issue could you please provide a Stackblitz example by using https://stackblitz.com/github/primefaces/primeng-issue-template

Regards

**Comment by jonnomk** [comment]
> Hi,
> 
> Cannot replicate the issue could you please provide a Stackblitz example by using https://stackblitz.com/github/primefaces/primeng-issue-template
> 
> Regards

Yes - here is a StackBlitz.  Did you test using PrimeNG 14.0.2?

https://primeng-menu-visible-issue.stackblitz.io
