### ISSUE TITLE
Component: Button dynamically disabling and enabling

### ISSUE THREAD

**Issue by Hamkoung** [primefaces/primeng#11923]
### Describe the bug

Setting the disable attribute to true has the expected outcome, but setting it back to false does not have any effect on the button element, it still looks  disabled. 
 

### Environment

Refer to stackblitz example

### Reproducer

https://stackblitz.com/edit/github-icv7xk-osnwca

### Angular version

14.0.7

### PrimeNG version

14.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.15.1

### Browser(s)

Firefox

### Steps to reproduce the behavior

1.    Typescript

 @ViewChild(Button)
    private button?: Button;

  public  testButton() {
      if (this.button !== undefined) {
          this.button.disabled = true;

          timer(5000).subscribe(() => {
              if (this.button !== undefined) {
                  this.button.disabled = false;
                  console.log('Test: ' + this.button.disabled);
              }
              }
          );
      }
  }

2. html

      <ng-template pTemplate="footer">
          <div class="grid grid-nogutter justify-content-end">
              <p-button class="p-button-lg" label="Speichern" (onClick)="testButton()" icon="pi pi-save" ></p-button>
          </div>
      </ng-template>

### Expected behavior

1. Clicking the button should desable it.
2. Enabled after 5 seconds.

**Comment by volvachev** [comment]
Hi, why don't you use `@Input disabled` but take a reference to a component and change its internals? (This way you break the correctness of the `changeDetection` mechanism)

**Comment by Hamkoung** [comment]
Hello Egor,

thank you for your answer.

We want to disable the button programmatically via custom directive and not via the disable attribute in the template. Disabling the button in the template would mean repetition of the same call to calculate the disabled state in every component which wants to use the same logic. This might look something like this in the template:
<button pButton label=”Go” disabled=”submitDisabled”></button>

And accordingly we need a definition like the following in every component:
get submitDisabled(): boolean {
                return this.submitProgessService.inProgress;
}

This is an inconvenient repetition and produces a lot of duplicated code. That’s why we want to create our own directive and use it like this:
<button pButton label=”Go” disableWhileSubmitting></button

I think this is a valid approach and it works perfectly fine in the Angular Material framework. See the following example of a working directive with injection of MatButton host element and manipulation of its color and disabled attributes. There is no problem with change detection in Angular Material.

import { Directive, Input, OnDestroy, OnInit, Self } from ***@***.***/core';
import { MatButton } from ***@***.***/material/button';
import { Subscription } from 'rxjs';
import { SubmitProgressService } from '../../services/submit-progress/submit-progress.service';

@Directive({
    selector: '[disableWhileSubmitting]'
})
export class DisableSubmitButtonDirective implements OnInit, OnDestroy {
    private progressSubscription: Subscription;

    private submitInProgress = false;

    private disabledOverwrite = false;

    ***@***.***() private button: MatButton, private submitProgressService: SubmitProgressService) {}

    ngOnInit(): void {
        this.button.color = 'accent';

        this.progressSubscription = this.submitProgressService.$submitProgress.subscribe((progress) => {
            this.submitInProgress = progress.inProgress;
            this.updateDisabledState();
        });
    }

    ngOnDestroy(): void {
        if (this.progressSubscription !== undefined) {
            this.progressSubscription.unsubscribe();
        }
    }

    @Input()
    set submitButtonDisabled(disabled: boolean) {
        this.disabledOverwrite = disabled;
        this.updateDisabledState();
    }

    get submitButtonDisabled(): boolean {
        return this.disabledOverwrite;
    }

    private updateDisabledState(): void {
        this.button.disabled = this.disabledOverwrite || this.submitInProgress;
    }
}



Von: Egor Volvachev ***@***.***>
Gesendet: Dienstag, 18. Oktober 2022 18:29
An: primefaces/primeng ***@***.***>
Cc: Hamkoung Nzeudie, Jean-Pierre ***@***.***>; Author ***@***.***>
Betreff: Re: [primefaces/primeng] Component: Button dynamically disabling and enabling (Issue #11923)


Hi, why don't you use @Input disabled but take a reference to a component and change its internals? (This way you break the correctness of the changeDetection mechanism)
