### ISSUE TITLE
NgOptimizedImage directive on p-image component

### ISSUE THREAD

**Issue by eXpertise7** [primefaces/primeng#11920]
### Describe the feature you would like to see added

[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

### Is your feature request related to a problem?

Apply new NgOptimizedImage directive to PrimeNG's Image component. NgOptimizedImage has Largest Contentful Paint and automatic lazy loading by default to <img> HTML element, that's a main part of p-image component.

### Describe the solution you'd like

Add NgOptimizedImage directive to <p-image> component. To be more specific add rawSrc instead of src attribute. When page/app will run the rawSrc will be  transformed to src automatically by Angular's directive.

### Additional context

https://developer.chrome.com/blog/angular-image-directive/

Hopefully someone notices this.

Thanks guys!

Kind regards,
Robert Medved

**Comment by eXpertise7** [comment]
@cetincakiroglu Sorry to bother you, if you see this please read this.

Here's is one good article about implementing NgOptimizedImage directive in Angular.

https://netbasal.com/using-angular-ngoptimizedimage-to-implement-image-loading-best-practices-e20a69d71ea3

**Comment by eXpertise7** [comment]
https://next.angular.io/api/common/NgOptimizedImage

**Comment by cetincakiroglu** [comment]
Hi,

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 
For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
