### ISSUE TITLE
Selected items on multiselect with lazy load

### ISSUE THREAD

**Issue by mperezd** [primefaces/primeng#11939]
### Describe the feature you would like to see added

We want to be able to select the items appearing in the chips without the need of loading them into the multiselect data options. With the actual behaviour, when we load the data from the server into a form, the items not present in the first load don't appear with the label, we can only see the crossmark.

We have seen in the source code of multiselect this fragment:

`<ng-container *ngIf="display === 'chip'">
                            <div #token *ngFor="let item of value; let i = index;" class="p-multiselect-token">
                                <span class="p-multiselect-token-label">{{findLabelByValue(item)}}</span>
                                <span *ngIf="!disabled" class="p-multiselect-token-icon pi pi-times-circle" (click)="removeChip(item, $event)"></span>
                            </div>
                            <ng-container *ngIf="!value || value.length === 0">{{placeholder || defaultLabel || 'empty'}}</ng-container>
                        </ng-container>` 

The function findLabelByValue searchs the item into the loaded data, and with lazy load, it is most likely that the data is not present yet.

### Is your feature request related to a problem?

When we need to update the selected options stored in the database showing a multiselect component, we can't show the current ones unless we have loaded all the possible options, so we can't really use lazy load and we have a huge dataset.

**Comment by cetincakiroglu** [comment]
Hi,

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 
For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
