### ISSUE TITLE
Enable FontAwesome as icon library next to primeIcons

### ISSUE THREAD

**Issue by LexanRed** [primefaces/primeng#11938]
### Describe the feature you would like to see added

PrimeNG offers on multiple occasions (e.g. pButton directive) the option to integrate icons into components. 

FontAwesome offers way more icons and variants than primeIcons at this time. Since we are heavily dependant on FontAwesome, we can not drop that. 

I found out, that in the case of `pButton directive` the method `createIconEl()` is responsible for creating a DOM element which then hosts the icon. 
Therefore it should be feasible to change that behaviour / add another one. 

Since FontAwesome is really popular other people would also profit from the ability to integrate this library and being able to use it as drop in replacement for primeIcons. 

### Is your feature request related to a problem?

PrimeIcons simply offers only a fraction from what FontAwesome is offering. 

### Describe the solution you'd like

It would be great, if we could either add another input to the directives which offer the icon directive. Maybe something like faIcon. 

`<button pButton faIcon="coffee"></button>`

Or add a configuration which could be set in the AppModule where we can choose which mode we want to use.

FontAwesome offers a Angular component. Their "Icon Library Approach" works similar to how icons are used in primeNG.
https://github.com/FortAwesome/angular-fontawesome/blob/master/docs/usage/icon-library.md

The method createIconEl() should render this `<fa-icon icon="coffee"></fa-icon>` instead of a span which is used to render the primeIcon. 

### Describe alternatives you have considered

I guess, since you supported FontAwesome in earlier versions and now developed your own library, it is not very likely an option like described above will be implemented. 

An alternative could be a guide how to build primeNG from source and add it afterwards back to the project. I would like to do that, but do not know how. Any help is very much appreciated!

**Comment by Urtgard** [comment]
If the FontAwesome CSS setup is an option for you, you can just use `icon="fa-solid fa-user"`.

**Comment by LexanRed** [comment]
Thanks for your quick reply! 

May I ask you for more details?
How would you setup FontAwesome to work like that? Can that be used in parallel to the FontAwesome Angular component?

**Comment by Urtgard** [comment]
1. Install FontAwesome npm package: https://fontawesome.com/docs/web/setup/packages
2. Add `"node_modules/@fortawesome/fontawesome-free/css/all.min.css"` to the styles array in _angular.json_

On StackBlitz it somehow doesn't work. But I'm pretty sure that was all I had to setup.

**Comment by LexanRed** [comment]
Thanks again for your proposal. 

It works for now. 

Regarding switching all icon styles: I found this solution out of the box by FontAwesome
https://fontawesome.com/docs/web/dig-deeper/style-switching

**Comment by Urtgard** [comment]
I'm not associated with PrimeNG so I can't decide whether your PR will be accepted.

But I would use your solution, if it's part of Prime. Who doesn't like a smaller bundle size?

**Comment by LexanRed** [comment]
Another problem raised during our transition to PrimeNG:

Components like the paginator or loading state depend on PrimeIcons. 
It would be great if there was some kind of alias list, where we can override the default icons used internally in the components. 

Or just an additional input to those components where we hand in the classes required by our icons. 

The first solution would be nicer, because it is less redundant.

Or is there any other option to override the default icons?

**Comment by LexanRed** [comment]
In case anyone comes across the question how to build from source, here is the answer. 

https://stackoverflow.com/questions/41310398/primeng-how-to-pack-or-build-the-project-after-making-changes

**Comment by webmozart** [comment]
This page says that custom icons are supported: https://primeng.org/customicons

Does that make this PR obsolete?

**Comment by ericvaroto** [comment]
Hi, do we have any updates about this new feature?

**Comment by cetincakiroglu** [comment]
Hi,

You can download Fontawesome to your app and use icon templating options of the components. We'll not add fontawesome as a dependency.
