### ISSUE TITLE
Dropdown: Clear button should set the control as touched

### ISSUE THREAD

**Issue by Foxandxss** [primefaces/primeng#11930]
### Describe the bug

A touched form control is a control that has been interacted with. Normally you mark it as touched when you blur out of the control. In a way of saying: I was here, now I am not. This has been marked as touched.

When I click the "clear button" I should get the same behavior. I click the X and that should mark the control as touched. 

### Environment

Nx application using latest angular and lates primeng

### Reproducer

https://stackblitz.com/edit/primeng-dropdown-demo-a1pmnq

### Angular version

14.2.0

### PrimeNG version

14.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.13.2

### Browser(s)

Chrome

### Steps to reproduce the behavior

Click the X to clear the field and read the message below it

### Expected behavior

I expect the control to be mark as touched when I clear its data by clicking the X button.

**Comment by cetincakiroglu** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.
