### ISSUE TITLE
Slider not working correctly with min value

### ISSUE THREAD

**Issue by mdymel** [primefaces/primeng#1193]
If I initialize slider with [min]=0 it works OK: 

![image](https://cloud.githubusercontent.com/assets/418910/19935657/1968737a-a11b-11e6-92f3-149d65b687ce.png)

If I set [min]=5 it sets the pointer as min was 0: 

![image](https://cloud.githubusercontent.com/assets/418910/19935699/41e19f84-a11b-11e6-9796-eaea5497411e.png)

When I click on the pointer, it moves to left, but it's not possible to move it anymore.

**Comment by brian428** [comment]
Yep, I'm seeing this as well. Something related to the slider got messed up in one of the newer builds. I know this worked at some point in the past but I'm not sure when the problem was introduced.
