### ISSUE TITLE
Error in rc.2

### ISSUE THREAD

**Issue by kcsahoo** [primefaces/primeng#1194]
I am still getting the following errors after upgrading to rc.2:
Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:21 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/traceur(…)

Can you please make your example in setup ot Quick Start example work with SystemJS?
Both the examples give the same error.

You closed my previous issue #1188 but it was not linked to core.js issue.

**Comment by mayusha** [comment]
+1

**Comment by kcsahoo** [comment]
I reported the error in rc.1 and the same error is in rc.2

**Comment by kcsahoo** [comment]
It works now.
Thanks
