### ISSUE TITLE
Dropdown component

### ISSUE THREAD

**Issue by Godsex** [primefaces/primeng#11941]
### Describe the feature you would like to see added

Dropdown component with filter feature should be focused when we closed the overlay.

### Is your feature request related to a problem?

when i press the 'esc' key, the dropdown lost focus.
<img width="700" alt="image" src="https://user-images.githubusercontent.com/29534170/190570412-2f092a18-f409-455e-a816-6de2743f1237.png">

### Describe the solution you'd like

The dropdown should be focused when we closed the overlay.

**Comment by cetincakiroglu** [comment]
Hi,

When you press 'ESC' key you tend to escape from that component which means you're done with everything. What is the point of keeping the focus on something the user wants to escape?

Also, this is an accessibility issue and we're fully focused on Accessibility. Our main goal is to consider all the components one by one and document the individual accessibility features. In doing so, it is to correct the deficiencies or faulty implementations of that component. For this reason, our team carries out a comprehensive and meticulous study. Of course, it will take some time to complete this process.
