### ISSUE TITLE
Table: Reset sorting to the default state

### ISSUE THREAD

**Issue by scurk1415** [primefaces/primeng#11940]
### Describe the feature you would like to see added

Table reset/clear method should set the sort properties of the lazy event to the default properties which were provided as the component @Input. Maybe this case should only affects tables with _lazy_ property set as true

We currently provide the _sortField_ and _sortOrder_ property to the table when rendered. The initial LazyLoadEvent is sent as 
`{ first: 0, rows: 10, sortField: 'create_date', sortOrder: -1 }` (omitted some properties which are not relevant for this case) but after we trigger the table.reset() method it changes to `{ first: 0, rows: 10, sortField: null, sortOrder: 1 }`, losing the sort properties provided in the beginning. 

### Is your feature request related to a problem?

This leads to wrong request being sent to the BE (via _onLazyLoad_ method), or better said the request and the data returned back are not the same as on the initially triggered(first) request. 

I know I can change the request manually, but it would be nice to not have to make some kind of workarounds.

### Describe the solution you'd like

Save the sortField and sortProperty to a private state and use that state on reset/clear.

### Describe alternatives you have considered

Maybe optional parameters/config for the reset method? 

`reset(config?: ConfigType) {...}`

and then reset it like
```
this._sortField = config?.sortField ?? null;
this._sortOrder = config?.sortOrder ?? this.defaultSortOrder;
```

I myself like the first solution more, but this way you won't really introduce any breaking changes.

You could also combine both solutions to `reset(resetToInitialState: boolean) {...}` and then use the state set in solution 1 instead of custom config object parameter.

### Additional context

The version of PrimeNg we use is 13.4.1 (but the example code above is from the master branch here on github)

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
