### ISSUE TITLE
The `scrollToVirtualIndex`method is not working as expected on Table

### ISSUE THREAD

**Issue by vlnicolae** [primefaces/primeng#11948]
### Describe the bug

navigating back with scrollToVirtualIndex leads to white screen on p-table

### Environment

latest primeng code. Make changes on showcase tablevirtualscrolldemo to reproduce the issue

### Angular version

14.0.0

### PrimeNG version

14.1.2-SNAPSHOT

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

16.15.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. call scrollToVirtualIndex(120)
2. call scrollToVirtualIndex(11)
3. p-table has white screen

### Expected behavior

1. call scrollToVirtualIndex(120)
2. call scrollToVirtualIndex(11)
3. p-table scroll show navigate to row 11

On stackblitz: 1. go to index 120; 2. go to index 11
https://primeng-tablevirtualscroll-demo-ifhtgr.stackblitz.io/

Also navigation to the index parameter of scrollToVirtualIndex(index) does not work well. The row with corresponding index is below the table header.

**Comment by cetincakiroglu** [comment]
Hi,

Great catch thanks for reporting the issue!

Regards

**Comment by PeterSteen** [comment]
Hi Have observed the same issue.

**Comment by viniciusrf** [comment]
I'm using primeng v15.4.0, angular 15.0.4 and I have the same issue, who was apparently fixed on 14.2.3.
My table has 5 visible items, if I scrollToVirtualIndex greater than currentIndex+6 the p-table becomes white, and I have to click again in the table to show the items again.

My start screen (index 1):
![Captura de tela 2023-11-17 093650](https://github.com/primefaces/primeng/assets/13909952/a16a538d-ff3b-496c-b01f-c18698109f04)

After scrollToVirtualIndex(8):
![Captura de tela 2023-11-17 093713](https://github.com/primefaces/primeng/assets/13909952/81214d70-6bc8-4499-99ce-e0284d9f427f)
