### ISSUE TITLE
Button: Render problem when using icons and text not via input

### ISSUE THREAD

**Issue by LexanRed** [primefaces/primeng#11942]
### Describe the bug

A normal button can be rendered with the following markup:
`<button pButton label="Nice Button with long text"></button>`
![Screenshot 2022-09-16 at 11 36 17](https://user-images.githubusercontent.com/57357219/190607282-4bc167b0-1dfa-4ad0-a8fa-e34cce57415e.png)

If you want to add an icon, it looks like this:
`<button pButton label="Nice Button with long text" icon="pi pi-user"></button>`
![Screenshot 2022-09-16 at 11 37 09](https://user-images.githubusercontent.com/57357219/190607438-a6ee13e3-3bb5-4042-8742-bbc9bfaf6110.png)

If you do not want to use the label input but place the text directly within the button tags, it looks like this:
`<button pButton>Nice Button with long text</button>`
![Screenshot 2022-09-16 at 11 38 48](https://user-images.githubusercontent.com/57357219/190607739-2d8c9a38-63aa-4995-80aa-749ddf28bf6b.png)
This button is already a few pixels wider than the label option. You can see it more clearly in the Stackblitz.
Also the styling is a bit off. Font weight is different.

If you now want to add an icon, the button is not rendered correctly anymore. Adding an icon and putting text between the brackets makes the layout crash:
`<button pButton icon="pi pi-user">Nice Button with long text</button>`
![Screenshot 2022-09-16 at 11 39 56](https://user-images.githubusercontent.com/57357219/190607981-b4148d4f-c54b-47e1-9baf-f2ec5f235ebb.png)

Why is this a problem? Adding the text within the brackets enables Angular's built in internationalisation to extract the text and translate it. 
`<button pButton icon="pi pi-user" i18n>Nice Button with long text</button>`

We prefer that solution over adding a package like ngx-translate, which is mentioned in the PrimeNG docs, because it is way cleaner markup and we want to have separate builds for different locales / languages. 

### Environment

Angular 14.2.1
PrimeNG 14.1.1
PrimeIcons 5.0.0

### Reproducer

https://stackblitz.com/edit/github-ngerg7?file=src/app/app.component.html

### Angular version

14.2.1

### PrimeNG version

14.1.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.17.0

### Browser(s)

Safari, Chrome, Firefox

### Steps to reproduce the behavior

See Stackblitz

### Expected behavior

Buttons should render correctly without collapsing in width. Additional styles like font weight should also be applied.

**Comment by LexanRed** [comment]
Thanks for working on this. 
Unfortunately, a part of this issue still exists. 

The styling of text inside a button is not the same when applied via label input or via content between the brackets. 

When text is rendered via the label input it looks like this: 
`<button pButton icon="pi pi-user" label="Button Test"></button>`
<img width="481" alt="Screenshot 2022-11-11 at 23 13 07" src="https://user-images.githubusercontent.com/57357219/201438061-6116bb69-1fdb-48c7-ad27-c8c3837be270.png">

When passing text via content: 
`<button pButton icon="pi pi-user">Button Test</button>`
<img width="454" alt="Screenshot 2022-11-11 at 23 14 41" src="https://user-images.githubusercontent.com/57357219/201438219-45f462cf-12dd-4807-933c-4e3b90a4def1.png">

Here the difference:
<img width="458" alt="Screenshot 2022-11-11 at 23 15 31" src="https://user-images.githubusercontent.com/57357219/201438306-f0b77dd8-bbca-4217-9ace-1cca6a48e4ab.png">

Font weight and spacing between text and the icon is still off.

**Comment by mertsincan** [comment]
> Font weight and spacing between text and the icon is still off.
- This is expected behaviour. You are trying to create a custom item from existing properties. That's why I think you should have a flexible structure except primeng's styles as much as possible.

Maybe, you can add the following CSS classes or change them according to your needs;
```
<button pButton icon="pi pi-user mr-2" class="font-bold">Button Test</button>
```

**Comment by LexanRed** [comment]
Of course it is possible to add custom CSS to achieve the same styling. 

But this is not a nice solution. If you decide to fix this then it will be off again and lot's of buttons need to be refactored. 

I forked the repo and will fix it myself. If you are interested in fixing it I can open a pull request.

**Comment by mertsincan** [comment]
Hi @LexanRed,

Thanks a lot for your update! But, you should not think that only text will come inside the button. Users can add any dom element to the button exp; icon. It would not be right to force them to our label's CSS styles.

**Comment by LexanRed** [comment]
Ok, that makes sense. 

There is actually a quite elegant solution. 

`<button pButton i18n-label label="Nice Button"></button>`

https://angular.io/guide/i18n-common-prepare#mark-element-attributes-for-translations

So no need to change anything.
