### ISSUE TITLE
primeng 14 treeselect filter not retaining the checkbox selection

### ISSUE THREAD

**Issue by situlindia** [primefaces/primeng#11954]
### Describe the bug

![image](https://user-images.githubusercontent.com/32801470/191240906-c74b837d-4ab2-486b-a99e-c8b327b66551.png)

### Environment

All

### Angular version

14.2.1

### PrimeNG version

14.1.0

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

16.13.0

### Browser(s)

All

### Expected behavior

It should retain the checkbox selection

**Comment by Adrii77** [comment]
Same problem here... how to retrieve selection state is not clear enough (and not easy :()
