### ISSUE TITLE
Chips | Clear icon is not visible with long text content

### ISSUE THREAD

**Issue by nick-d-dev** [primefaces/primeng#11957]
### Describe the bug

No obvious way to remove entries that are very long or if the width of the chips component has been limited in any way (this includes monitor width)

### Environment

Any

### Reproducer

https://www.primefaces.org/primeng/chips

### Angular version

^14

### PrimeNG version

^14

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.13.1

### Steps to reproduce the behavior

1 - go to the demoed chip component
2 - input a VERY long string (something that is beyond the width of the actual field)
3 - press ENTER to input said long string

----> There is no " X " visible to remove the entry and no way to scroll to it in order to see it.

### Expected behavior

There is an obvious way/button to remove the entry from the chips component.

Current workaround -> use backspace to remove the entry since the "X" button is not reachable

**Comment by cetincakiroglu** [comment]
Hi,

Good catch, issue is fixed in #11960 now you'll be able to scroll (shift+scroll) with large text. Thanks for reporting!
