### ISSUE TITLE
Does p-tableCheckbox work with reactive forms?

### ISSUE THREAD

**Issue by RaduGrama** [primefaces/primeng#11956]
Is `p-tableCheckbox` intended to work with reactive forms? Can I use `<p-tableCheckbox formControlName="myControlName"></p-tableCheckbox>` or `<p-tableCheckbox [formControl]="myControl"></p-tableCheckbox>` or is it not designed to be used that way?

My ultimate goal is to get the selections made in a `p-table` in a reactive form.

**Comment by vinnyab28** [comment]
Hi @RaduGrama 

Unfortunately, it is not intended to work that way. Regarding your query, there are multiple ways to achieve this.
1. If you look at the documentation for [Table -> Selection](https://www.primefaces.org/primeng/table/selection), you assign your selected row to a variable using two-way data binding with the help of `[(selection)]` property on your `<p-table>`. On submit, you can `patch` the value to your respective `formControl`.
2. You can also make use of `onRowSelect` and `onRowUnselect` events to `patch` or `remove` the value to your `formControl`
