### ISSUE TITLE
Component: Chips - Max number of entries limit not working

### ISSUE THREAD

**Issue by nick-d-dev** [primefaces/primeng#11961]
### Describe the bug

The limitation for the max number of entries into the chip field is not working at all.

### Environment

any

### Reproducer

https://www.primefaces.org/primeng/chips -> stackblitz part

### Angular version

^14

### PrimeNG version

^14

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

16.13.1

### Browser(s)

any

### Steps to reproduce the behavior

repro 1 :
1 - go to the demo link
2 - inside the "app.component.html" find the chip component ( i have used the comma separated one for example )
3 - add '  max="2"  ' to the chip component
4 - refresh (or let it reload)
5 - put in more than 2 chips

repro 2 :
1 - same
2 - go to app.component.ts
3 - add maxChips=2;
4 - bind the max from component.ts to a chip component in the template file (max="maxChips")
5 - put in more than 2 chips

### Expected behavior

There is a limit on how many chips can be added/put in

Putting in an actual number (as described in the docs eg: " max=2 ") will result in a type error

current workaround -> use the onAdd event to handle any existing and/or extra chips when they are added

**Comment by cetincakiroglu** [comment]
It works https://stackblitz.com/edit/primeng-chips-demo-xjahtj?file=src%2Fapp%2Fapp.component.html

**Comment by nick-d-dev** [comment]
must be something locally on my end then, sorry for wasting your time

thanks
