### ISSUE TITLE
MultiSelect : Invert Selection option

### ISSUE THREAD

**Issue by vikramt24** [primefaces/primeng#11964]
### Describe the feature you would like to see added

The feature will be very useful when we have the bigger list and selecting only few, like in google sheet filter

### Describe the solution you'd like

Invert selection

**Comment by seymanurgullu** [comment]
Hi, 

 We have such a properties.

You can use [showClear]="true" 

<p-multiSelect [options]="cities" [(ngModel)]="selectedCities1" defaultLabel="Select a City" [showClear]="true" optionLabel="name" selectedItemsLabel="{0} items selected"></p-multiSelect>

**Comment by cetincakiroglu** [comment]
Hi,

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 
For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
