### ISSUE TITLE
Component: Messages - automatic closing/dismissal

### ISSUE THREAD

**Issue by ndagovic** [primefaces/primeng#11969]
### Describe the feature you would like to see added

Message popups via service (or otherwise) are automatically dismissed after a set period of time.

### Is your feature request related to a problem?

Annoyance - manual implementation of automatic dismissal of success or info messages.

### Describe the solution you'd like

Ideal solution

Possibility to select if a particular type of message (success/error etc) will be automatically dismissed and set the time.

Bonus points - it can be independently set for any given message.

### Describe alternatives you have considered

Binding a displayed message to a timeout fn that will clear it after a set amount of time

### Additional context

Context - think of any notification settings on the big social networks (facebook, linkedin etc)

A notification (message) is displayed and then after a set amount of time (3-5 seconds) automatically hidden.

**Comment by ValentinKrigovsky** [comment]
Hello, @ndagovic , I will try to create PR for this issue today
