### ISSUE TITLE
Table: sortMode multiple

### ISSUE THREAD

**Issue by gabrielhpereira** [primefaces/primeng#11977]
### Describe the bug

When performing sorting, number 1 appears next to the icon

### Environment

The bug is appearing on the primeng website

### Reproducer

https://primefaces.org/primeng/table/sort

### Angular version

14

### PrimeNG version

14.1.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.17.1

### Browser(s)

Chrome, Chromium, Firefox

**Comment by gabrielhpereira** [comment]
Multiple Columns, when sorting, a number appears next to the column name

**Comment by juulian98** [comment]
Thats a feature, not a bug. It displays the sort order.

**Comment by gabrielhpereira** [comment]
if I choose sortMode="single" it doesn't happen, is that right?
![number](https://user-images.githubusercontent.com/69478282/192763359-1f605584-1b6a-421e-8a5a-0c63aca79d23.png)

**Comment by juulian98** [comment]
In single mode, it makes no sense to display a number, since only one column can be sorted at a time anyway.  Accordingly, there does not have to be any visualized prioritization in this case.

**Comment by gabrielhpereira** [comment]
Got it, thanks for the explanation
