### ISSUE TITLE
Component: MenuModel API autoDisplay option on

### ISSUE THREAD

**Issue by davpirelli** [primefaces/primeng#11979]
### Describe the feature you would like to see added

We are using the **MenuModel API** component.
Using the _autoDisplay_ functionality with _true_, it activate the hover on the menu _(only on the root level)_, it would be possible to have the same functionality on the MenuItem (the sub-items)?

Is there already a way to get a choice between click / hover on second level (and higher) menu items?

Thanks!

### Describe the solution you'd like

Use the same logic used for the root level

**Comment by cetincakiroglu** [comment]
Hi,

You can use the TieredMenu component for it. Here is an example, it opens submenu options on hover. https://stackblitz.com/edit/primeng-tieredmenu-demo-vuwvhu?file=src%2Fapp%2Fapp.component.html
