### ISSUE TITLE
Editor: change the theme of quill

### ISSUE THREAD

**Issue by micky008** [primefaces/primeng#11976]
### Describe the feature you would like to see added

I want to change the theme of quill.
I can to choose the theme (snow or bubble). 
or a agnostic variable => "do you want to see the toolbar ?" 

### Is your feature request related to a problem?

If i read a text in readonly mode. i don't want to see the toolbar.
the bubble theme "delete" the toolbar.

**Comment by micky008** [comment]
No for the moment. 
To fix this, I've create my own componant with a copy paste from the prime ng original code and I modify the lines.
it's a ugly workaround... 

It was very cool if primng made this feature :)

**Comment by carama-s** [comment]
Hello I'm also interested in this feature, it would be nice. 
Do you think you can share with us with solution @micky008, I'm really interested, thanks !

**Comment by micky008** [comment]
i wrote this "workaround" when i was in my older companie.
i've change now... 

but i have a few contact... 
I was not promising anything...

**Comment by micky008** [comment]
[myEditor.txt](https://github.com/primefaces/primeng/files/11136713/myEditor.txt)

this is the file.
it's the v8 of primeng because the project was in v8.

I put only an Input to choose the theme.

**Comment by stephcs13** [comment]
Thanks you @micky008 ! it will help me a lot !

**Comment by cetincakiroglu** [comment]
Hi,

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 
For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
