### ISSUE TITLE
Component: AutoComplete when is grouped empty message do not work

### ISSUE THREAD

**Issue by adopilot** [primefaces/primeng#11978]
### Describe the bug

If we autoComplete component set to be grouped  empty message do not shows any more.

```
 <p-autoComplete
        [formControlName]="props.id"
        [id]="props.id"
        [name]="props.id"
        [type]="'search'"
        [suggestions]="data"
        [group]="true"
        (completeMethod)="search($event)"
        field="label"
        showEmptyMessage="true"
        [emptyMessage]="'U forumu ne postoji  korisnik ili grupa pod odabranim uslovima pretrage'"
        >
        <ng-template let-group pTemplate="group">
            <div class="p-d-flex p-ai-center">
              <span>{{group.label}}</span>
            </div>
          </ng-template>
    </p-autoComplete>
```

### Environment

I am using sample from provided on https://primefaces.org/primeng/autocomplete to reproduce bug PrimeNG 14.1.1

### Reproducer

https://stackblitz.com/edit/primeng-autocomplete-demo-95nke6?file=src%2Fapp%2Fapp.component.html

### Angular version

13.0.3

### PrimeNG version

14.1.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

~8.3.0

### Browser(s)

Chrome, Firefox

### Steps to reproduce the behavior

If user type query term that server does not return , control shod display empty message

### Expected behavior

Empty message shod shown

**Comment by gucal** [comment]
Hi,

This issue has been fixed with version 14.1.2. Please upgrade primeng version.
