### ISSUE TITLE
Data Table skeleton not working 

### ISSUE THREAD

**Issue by BobbyGannard** [primefaces/primeng#11971]
### Describe the bug

I was trying to use the example given on the site for a table skeleton. I could not get it working.

```
  <p-table [value]="products">
    <ng-template pTemplate="header">
      <tr>
        <th>Code</th>
        <th>Name</th>
        <th>Category</th>
        <th>Quantity</th>
      </tr>
    </ng-template>
    <ng-template pTemplate="body" let-product>
      <tr>
        <td><p-skeleton></p-skeleton></td>
        <td><p-skeleton></p-skeleton></td>
        <td><p-skeleton></p-skeleton></td>
        <td><p-skeleton></p-skeleton></td>
      </tr>
    </ng-template>
  </p-table>
```

I decided to look at the StackBlitz and found that it was also not working on there either.
https://stackblitz.com/edit/primeng-skeleton-demo?file=README.md

### Environment

Production and StackBlitz

### Angular version

12

### PrimeNG version

12.0.2 and 14.1.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.17.0

### Browser(s)

All

### Steps to reproduce the behavior

1. Go to http://primefaces.org/primeng/skeleton
2. Scroll down to "Documentation" of The skeleton.
3. click on "Source" tab 
4. Click "Edit in StackBlitz"
5. Scroll to the bottom of the web page 
6. view that "DataTable" has no skeleton

### Expected behavior

![Screen Shot 2022-09-23 at 9 49 36 AM](https://user-images.githubusercontent.com/96073545/191988902-d933dfd8-d1e4-4414-80bb-5c5d0c20b35c.png)

**Comment by Urtgard** [comment]
You must provide a non-empty array for `products`.

If you click the GitHub icon on http://primefaces.org/primeng/skeleton you can see how the example are build.


```typescript
products: any[];

ngOnInit() {
    this.products = new Array(5);
}
```

https://github.com/primefaces/primeng/tree/master/src/app/showcase/components/skeleton

**Comment by BobbyGannard** [comment]
I did try that and I was able to see the skeletons but the part that I was missing was `responsiveLayout="scroll`
This is no mentioned in the documentation And also not added to the StackBlitz demo. I believe it should be. 

Thanks
