### ISSUE TITLE
Table: State on multiple tables

### ISSUE THREAD

**Issue by lucafulgenzi** [primefaces/primeng#11975]
### Describe the bug

I have one table component that can have data of various kinds, with changing columns and filters. It's basically a completely dynamic table. Wanting to save the filters in local storage or session storage I can then define different stateKeys one for each table, the tables however remain as 'linked', or rather the column filters are like all for one big table, so I end up in the situation where maybe I have a filtered column in a table that in another object I don't have and thus doing my search fail

### Environment

Docker therefore a therefore any unix operating system, but I doubt it comes from this

### Angular version

14.2.3

### PrimeNG version

14.1.1

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

16.13.1 

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Define 2 tables on the same page with different dataKeys
2. Filter one of the two tables
3. Reload page

### Expected behavior

Each table has its own associated filters

**Comment by juulian98** [comment]
Can you share your code snippet of the binding for the stateKey?

**Comment by lucafulgenzi** [comment]
```
<p-table [id]="globalSearchId"
           [lazy]="true"
           [columns]="dataTableSelectedColumns"
           [value]="dataTableValues | async"
           [(selection)]="dataTableSelectedRows"
           [rowHover]="true"
           [customSort]="true"
           (onSort)="this.sortChangedEmitter.emit($event)"
           (onFilter)="this.filterChangedEmitter.emit($event)"
           editMode="row"
           dataKey="id"
           [stateKey]="globalSearchId"
           stateStorage="session"
           styleClass="p-datatable-sm p-datatable-striped p-datatable-gridlines"
           responsiveLayout="scroll">
```

Where `globalSearchId` is unique for each page

**Comment by juulian98** [comment]
I also have several tables that all have different StateKeys, but it works great for me. Do you also change the value of globalSearchId when the table changes?

**Comment by lucafulgenzi** [comment]
No the StateKeys stays the same for each table, I think the problem is that the tables are destroyed and I think it can't get it back
