### ISSUE TITLE
Dialog: Use CSS resize to handle dialog resize

### ISSUE THREAD

**Issue by justiceo** [primefaces/primeng#11972]
### Describe the feature you would like to see added

Currently dialog resize is handled by a combination of mousedown (initResize) -> mousemove (resize) -> mouseup (endResize) events. Switching this to CSS resize (https://developer.mozilla.org/en-US/docs/Web/CSS/resize) could improve the reliability and accessibility of the feature.

### Is your feature request related to a problem?

There are 3 issues I'm seeing with the current approach which can be resolved with a CSS resize based approach.

1) If mouseup is trapped, the user is stuck in resize. This can happen if the dialog contains an iframe since mouse events over an iframe are not bubbled up to the containing document by default.

To reproduce this, try resizing a dialog like this one:
```
<p-dialog>
  <iframe src="https://example.org"   width="100%"   height="100%"></iframe>
</p-dialog>
```
During the resize, if you accidentally mouse over the iframe, you'll be stuck in resize.

I've verified CSS resize does not have this problem.

2) It is not RTL friendly. The resize handle is absolutely positioned at the bottom-right corner and there is no option to set/change the location of this handle. In my use-case, the dialog is position at right of the viewport, hence users can only resize in the left direction.

To reproduce this, add the following css to the dialog:
```
.p-dialog {
  direction: rtl;
}
```
You'll observe that the header controls are now on the left (which is great) while the resize handler is still on the right.

I've verified CSS resize will place the resize handler on the bottom-left position if RTL is enabled. It would be possible to implement RTL using the current Js approach but it'll certainly not be as trivial as having CSS do it for you.

3) The resize handle is not accessible. Users cannot see the handle and hence do not know that the dialog is resizable. There are easy fixes for this one (add color to the handle!). In my case I used the following CSS rules to make it more conspicuous on hover:

```
div.p-resizable-handle {
    height: 30px;
    right: 0px;
    bottom: -10px;
    transform: rotate(45deg);
    &:hover {
      background-color: #aaa;
}
```
With CSS resize, the resize handle is visible by default (my extra CSS is unnecessary), the developer can style or hide it if they wish. This part is the only user-visible change in switching to CSS resize and I think that for accessibility/discovery sake, visible by default is better than not-visible by default (just like in scrollbars).

### Describe the solution you'd like

Add the following CSS rule to dialog.css, which would automatically be activated if user enables resizable:

```
.p-dialog.p-dialog-resizable {
  resize: both; 
}
```

In [#bindDocumentResizeListeners](https://github.com/primefaces/primeng/blob/2ade62522c6267ae6ab8829857b3c15faac4f3b0/src/app/components/dialog/dialog.ts#L642), instead of listening for "mousemove" and "mouseup", listen for resize event on the dialog using ResizeObserver - https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver. On resize, update the dialog's lastX, lastY and any other relevant properties.

In #unbindDocumentResizeListeners, remove the listener by calling ResizeObserver#unobserve  https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver/unobserve

### Describe alternatives you have considered

- I considered wrapping the dialog with a resizable container (didn't go well at all).
- I tried the hacks for capturing mouse events over iframe like https://stackoverflow.com/q/5645485/3665475, none of the hacks worked for my specific use-case and none of them were appropriate to add to a shared code.

### Additional context

I can submit a PR for this issue if the proposal looks good. I want to get early feedback on it in case I'm missing something and to avoid wasting time if it has already been considered and rejected.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
