### ISSUE TITLE
Dropdown can be selected even after being disabled

### ISSUE THREAD

**Issue by victorschinaider** [primefaces/primeng#1198]
```html
<p-dropdown 
    [options]="orgaosExpedidores" 
    [(ngModel)]="DocumentoInfo.identidadeExpedidor" 
    [style]="{'width':'140px'}"
    [disabled]="onlyView" <!-- true -->
>
</p-dropdown>
```

![test](https://cloud.githubusercontent.com/assets/16581931/19966640/6ec06db0-a1ab-11e6-8279-e58615c4d641.png)

More details: It occurs when you use the "tab" keyboard.

**Comment by upmauro** [comment]
I don't know what it's the best solution for this. But maybe we need change tabIndex to -1 when input is disabled, but i think we need keep stored tab index in case of the user enable input again.

**Comment by cagataycivici** [comment]
Will review for next version.

**Comment by cagataycivici** [comment]
Can't replicate with 4.0.2.
