### ISSUE TITLE
Component: Chips

### ISSUE THREAD

**Issue by lemonCMS** [primefaces/primeng#11989]
### Describe the feature you would like to see added

Optionally always show the input placeholder, regarding if it is empty or not.

### Is your feature request related to a problem?

We have a component that always shows a default value, therefor the placeholder is never shown. We would like to have the option to always show the input placeholder.

### Describe the solution you'd like

An extra option on the component to allow this.

### Describe alternatives you have considered

With ViewChild get the component and then get the native input field and set the placeholder every time it is being reset.

But this could break easily in the future, and thus we did not implement it further.

**Comment by cetincakiroglu** [comment]
Hi,

Adding a secondary component to display placeholder is not ideal for UX/UI. Instead, you can use float label. Here is an example of how it works https://stackblitz.com/edit/primeng-chips-demo-796pdw?file=src%2Fapp%2Fapp.component.html

**Comment by lemonCMS** [comment]
Hi,

This has noting to do with adding a secondary component, right now we are able to display a placeholder with the provided placeholder attribute. The problem is the placeholder is only shown in the input when there are no values provided. After entering one value, the placeholder text is not provided anymore to the input field. See [source](https://github.com/primefaces/primeng/blob/master/src/app/components/chips/chips.ts#L24)

So to have an ability to have the placeholder bound to the input regardless if there are values would be appreciated.
