### ISSUE TITLE
TreeSelect | Add styleClass and style support for container and label

### ISSUE THREAD

**Issue by DarienF** [primefaces/primeng#11982]
### Describe the bug

If I try put on TreeSelect component `width: 100%` like this:

```
<div style="width: 400px; background-color: red;">
  <p-treeSelect
    [style]="{
      width: '100%'
    }"
    [(ngModel)]="selectedNode1"
    [options]="nodes1"
    placeholder="Select Item"
  ></p-treeSelect>
</div>
```
...it not woking.

Link to reproduce: https://stackblitz.com/edit/github-kmrarh?file=src%2Fapp%2Fapp.component.html

### Environment

"primeflex": "^3.2.1",
"primeicons": "^5.0.0",
"primeng": "^14.0.1",

### Angular version

14.0.0

### PrimeNG version

14.0.1

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

18.6.0

**Comment by cetincakiroglu** [comment]
Hi,

Thanks for reporting the issue, it seems the component needs styleClass & style properties for both container and label. I'll change the topic and add it to the milestone.
