### ISSUE TITLE
Splitter: Expand/Collapse feature for splitter

### ISSUE THREAD

**Issue by PranKe01** [primefaces/primeng#11984]
### Describe the feature you would like to see added

It would be nice to have a collapse/expand icon on the splitter, to maximize/minimize the splitter areas.

### Describe the solution you'd like

I think instead of the colored small area in the middle of each splitter, a expand/collapse icon would make sense. Lets assume a splitter with the sizes [25, 75]. As soon as one clicks on the collapse icon, the splitter could change to [0, 100] and the icon chnages to expand icon. When we click on that, the previous size would be restored ([25, 75] or maybe the size the user has set via movement of the splitter).

### Describe alternatives you have considered

Currently I have implemented by my own. When clicking a button, the flex-basis is set to 0% and 100% via jQuery.

**Comment by cetincakiroglu** [comment]
Hi,

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 
For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
