### ISSUE TITLE
Primeng Table with hidden attribute

### ISSUE THREAD

**Issue by the-bullbash** [primefaces/primeng#11988]
### Describe the bug

If a table component was initially hidden and then becomes shown - table body is incorrect(

### Environment

Simple angular project with latest version of angular and primeng

### Reproducer

https://stackblitz.com/edit/primeng-tablevirtualscroll-demo-dvrzlq?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

### Angular version

14.2.4

### PrimeNG version

14.1.2

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

16.17.0

### Browser(s)

Chrome 105

### Steps to reproduce the behavior

1. Create a table with [hidden]=true attribute
2. Make the table visible with [hidden]=false
3. See incorrect result - table rows and scrolling are broken(

**Comment by cetincakiroglu** [comment]
Hi,

Here is a refactored and working version of your example https://stackblitz.com/edit/primeng-tablevirtualscroll-demo-xkhryu?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

**Comment by the-bullbash** [comment]
I know that it works with *ngIf instead of [hidden]... But I need to use hidden attribute to have DOM in background and do not wait rendering each time it becomes visible.

Please reopen this issue
