### ISSUE TITLE
Component: Title

### ISSUE THREAD

**Issue by godfryd** [primefaces/primeng#11980]
### Describe the feature you would like to see added

There is not official way to trigger a table refresh 
after e.g. some record is changed or deleted.

### Describe the solution you'd like

Add a new method to table: refresh or reload.

**Comment by cetincakiroglu** [comment]
Hi,

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 
For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
