### ISSUE TITLE
VirtualScroller triggers onLazyLoad event even though there is no scroll event.

### ISSUE THREAD

**Issue by bnymncoskuner** [primefaces/primeng#11987]
### Describe the bug

VirtualScroller triggers onLazyLoad event even though there is no scroll event.

You can view the console on this [demo](https://stackblitz.com/edit/primeng-virtualscroller-demo-cqpv7h)

Open up the console and you will see the event being logged constantly.

### Environment

Simple angular project with latest version of angular and primeng

### Reproducer

https://stackblitz.com/edit/primeng-virtualscroller-demo-cqpv7h

### Angular version

14.2.3

### PrimeNG version

14.1.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14.2

### Steps to reproduce the behavior

1. Open up the console
2. You'll see the event being logged constantly.

### Expected behavior

I would expect the lazyLoad event to trigger when there is a scroll event.

**Comment by yelhouti** [comment]
Is this a regression ? I am facing the same issue in dropdowns, the same event shouldn't be triggered twice

**Comment by yelhouti** [comment]
@mertsincan I see that you are the one who worked on VirtualScoll. It is complitelly broken when lazy, specifically when working with dropdowns.
Even the primeng demo is broken...

**Comment by cetincakiroglu** [comment]
Hi,

Thanks for reporting the issue, I added it to the milestone

**Comment by mnhock** [comment]
We have the same issue triggering endless events for virtual scroll / lazyload modde in p-dialog component.

**Comment by yelhouti** [comment]
@mnhock I am working on a PR that also fixes lazy to work with filters

**Comment by yelhouti** [comment]
@mnhock I am just a user of the library like you :)

**Comment by yelhouti** [comment]
@mnhock for the dropdown, the issue was because of a scroll that triggered the reload, I suspect the same thing happens in your component. I am fixing dropdown and multiselect for now

**Comment by yelhouti** [comment]
@cetincakiroglu could you check the PR please, Also I an unable to run ng build locally:
> Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.

It seems like an issue witch package versions, could you please tell the node version you are using? and also can you ensure that when you remove node_modules and reinstall it keeps building.

Thanks in advance

**Comment by ThorstenKunz** [comment]
Same thing happens to us when with p-table when used with virtualscroll and lazy: endless calls of onLazyLoad method even when no scoll event is happening.

**Comment by mertsincan** [comment]
For performance, you can use `event.forceUpdate();` instead of `this.virtualProducts = [...this.virtualProducts];`.
