### ISSUE TITLE
Component: Splitter not working correctly for overflow hidded and white space: nowrap

### ISSUE THREAD

**Issue by lashisu** [primefaces/primeng#11990]
### Describe the bug

I am tring to use css **text-overflow: ellipsis;**, but it is not working.
![image](https://user-images.githubusercontent.com/1376383/193198333-71454aa2-1aa0-445b-9f7a-ea53508a6a0c.png)

### Environment

Development

### Reproducer

https://stackblitz.com/edit/primeng-splitter-demo-kfw7wm?file=src%2Fapp%2Fapp.component.html

### Angular version

11.0.9

### PrimeNG version

11.3.0

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

v16.17.o

**Comment by cetincakiroglu** [comment]
Hi,

This is not a defect. You can use panelStyle or panelStyleClass properties to truncate the text. Text truncate works with defined width values, you can't truncate the text inside a flex object. Here is the refactored and working version of your example

https://stackblitz.com/edit/primeng-splitter-demo-dqdtln?file=src%2Fapp%2Fapp.component.html
