### ISSUE TITLE
TabView rounding up names

### ISSUE THREAD

**Issue by aygunoz** [primefaces/primeng#12008]
### Describe the bug

Hi Dear,

I shared demo project for you. You can see so clear on the demo what's the issue. If you fix it, appreciate you.

Note: If you don't use '-' in the header or space, It's okay but other way title rounding up names.
link: https://stackblitz.com/edit/primeng-tabview-demo-vs4m8g?file=src%2Fapp%2Fapp.component.html
![image](https://user-images.githubusercontent.com/74569642/193751550-5cff6b5f-c488-4d8a-b90f-39b8b60d1c90.png)

Best regards

### Environment

https://stackblitz.com/edit/primeng-tabview-demo-vs4m8g?file=src%2Fapp%2Fapp.component.html

### Reproducer

https://stackblitz.com/edit/primeng-tabview-demo-vs4m8g?file=src%2Fapp%2Fapp.component.html

### Angular version

14

### PrimeNG version

14

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14

### Browser(s)

Chrome

**Comment by volvachev** [comment]
Hello, you can add ``[headerStyle]= {'white-space':'nowrap'}`` on ``p-tabPanel`` and it will display correctly as in your second example. I'm not sure yet if it's worth adding it explicitly inside the component.

**Comment by aygunoz** [comment]
> Hello, you can add `[headerStyle]= {'white-space':'nowrap'}` on `p-tabPanel` and it will display correctly as in your second example. I'm not sure yet if it's worth adding it explicitly inside the component.

Hello
It fix my problem. Thank you. I wanted to add inside the component bc of I want to add some icon header too. I think I need to learn more CSS 👍🏼 
![image](https://user-images.githubusercontent.com/74569642/195974033-60f819b2-a406-40f2-8f81-26a73f5920b5.png)

**Comment by volvachev** [comment]
> Hello It fix my problem. Thank you. I wanted to add inside the component bc of I want to add some icon header too. I think I need to learn more CSS 👍🏼 ![image](https://user-images.githubusercontent.com/74569642/195974033-60f819b2-a406-40f2-8f81-26a73f5920b5.png)

If I understand correctly, here is an example of how this can be done.
```html
<p-tabPanel *ngFor="let tab of scrollableTabs" [headerStyle]="{'white-space':'nowrap'}">
  <ng-template pTemplate="header">
    <span class="pi pi-user" style="margin-right: 5px;"></span>
    <span>{{ tab.title }}</span>
  </ng-template>
</p-tabPanel>
 ```
