### ISSUE TITLE
Incorrect package.json

### ISSUE THREAD

**Issue by kryzys69** [primefaces/primeng#1200]
Shouldn't **package.json** has more dependencies? Bold section added and the prjects comiles and runs fine.

{
  "name": "primeng",
  "version": "1.0.0-rc.4-SNAPSHOT",
  "scripts": {
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "webpack": "webpack",
    "webpack:w": "webpack -w",
    "webpack-dev-server": "webpack-dev-server",
    "start": "npm run tsc && npm run webpack-dev-server"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/primefaces/primeng.git"
  },
  "license": "Apache-2.0",
  **"dependencies": {
    "@angular/common": "2.1.2",
    "@angular/compiler": "2.1.2",
    "@angular/core": "2.1.2",
    "@angular/forms": "2.1.2",
    "@angular/http": "2.1.2",
    "@angular/platform-browser": "2.1.2",
    "@angular/platform-browser-dynamic": "2.1.2",
    "@angular/router": "3.1.2",
    "core-js": "2.4.1",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.21"
  },**
  "devDependencies": {
    "@types/node": "^6.0.45",
    "del": "^2.2.0",
    "gulp": "^3.9.1",
    "gulp-concat": "^2.6.0",
    "gulp-flatten": "^0.2.0",
    "gulp-rename": "^1.2.2",
    "gulp-uglify": "^1.5.3",
    "gulp-uglifycss": "^1.0.6",
    "ts-loader": "^0.9.5",
    "typescript": "^2.0.3",
    "webpack": "^1.13.1",
    **"webpack-dev-server": "^1.16.2"**
  }
}

**Comment by cagataycivici** [comment]
We'Ve added dev-server but no need for PrimeNG itself to depend on Angular 2 as it is a peer dependency. If we add them as dependency then there duplicate Angular 2 dependencies will be at node_modules/primeng/node_modules afaik.

Please see;

https://github.com/primefaces/primeng/wiki/Building-From-Source
