### ISSUE TITLE
Toast message dialog not clickable

### ISSUE THREAD

**Issue by namishraptc** [primefaces/primeng#12007]
### Describe the bug

The toast message popup that comes up is in the background and not clickable.

### Environment

The toast message popup that comes up is in the background and not clickable.

### Reproducer

https://stackblitz.com/edit/primeng-dialog-demo-xclyzv?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

### Angular version

14.2.4

### PrimeNG version

13.4.1

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

14.17.1

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Click the go icon.
2. Popup come in the background which is blur.

### Expected behavior

The popup must be clickable.

**Comment by seymanurgullu** [comment]
The feature of modal toast is that it is overlay. You can use others as they are not found in other toasts, you will not encounter this problem there. If you edit the css, you can still change this behaviour.
