### ISSUE TITLE
VirtualScroller: item template context parameters not exposed

### ISSUE THREAD

**Issue by giesmininkas** [primefaces/primeng#12006]
### Describe the bug

In VirtualScroller item template, parameters "index", "count", "first" and "last" are not exposed. They are listed as parameters in VirtualScroller documentation.

### Environment

PrimeNG 14.2.4

### Angular version

14.2.4

### PrimeNG version

14.1.2

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

18.10.0

**Comment by mertsincan** [comment]
Hi,

You can use options object for it. Exp;
```
<ng-template let-product let-options="options" pTemplate="item">
    {{options.index}}
```
