### ISSUE TITLE
Tree Table - Drag and drop for rows

### ISSUE THREAD

**Issue by guptarenu240489** [primefaces/primeng#12002]
### Describe the feature you would like to see added

**Draggable rows inside tree table**
columns are draggable in tree table but I can't drag tree nodes inside tree table. I can do it inside tree but not treetable. Requesting for draggable rows inside tree table

**Comment by alsinaleandro** [comment]
waiting for this

**Comment by cetincakiroglu** [comment]
Hi,

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 
For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
