### ISSUE TITLE
Component: Menu (Menu model)

### ISSUE THREAD

**Issue by guillaume-f** [primefaces/primeng#12010]
### Describe the bug

The property "badge" is not working for the menu model.
When I add a badge in the configuration of the menu, nothing appeared
https://stackblitz.com/edit/primeng-menu-demo-5vbv1c?file=src/app/app.component.ts

### Environment

Browser : Google Chrome, Firefix
Windows 10

### Reproducer

https://stackblitz.com/edit/primeng-menu-demo-5vbv1c?file=src/app/app.component.ts

### Angular version

13.0.3

### PrimeNG version

13.0.4

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

16.15.0

### Browser(s)

ALL

### Expected behavior

The badge is displayed on a menu item

**Comment by volvachev** [comment]
Hi, you need to upgrade to version 14+, this is fixed there.
