### ISSUE TITLE
p-table

### ISSUE THREAD

**Issue by vlnicolae** [primefaces/primeng#12015]
### Describe the bug

p-table with frozen column does not scroll vertically when virtual scrolling is enabled

### Environment

I created a p-table with frozen column and virtual scroll.

Vertical scrolling doesn't work well.

### Reproducer

https://primeng-tablevirtualscroll-demo-7o5tkb.stackblitz.io

### Angular version

14.2.4

### PrimeNG version

14.1.2

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

16.15.0

### Browser(s)

chrome

### Steps to reproduce the behavior

I created a p-table with frozen column and virtual scroll.

Vertical scrolling doesn't work well.

### Expected behavior

Vertical scrolling work well.

**Comment by vlnicolae** [comment]
Maybe helps...

This issue disappear if all stuff from 'updateStickyPosition' is called on a  setTimeout function.

updateStickyPosition() {        
        if (this._frozen) {
            setTimeout(()=> {
                if (this.alignFrozen === 'right') {
                    let right = 0;
                    let next = this.el.nativeElement.nextElementSibling;
                    if (next) {
                        right = DomHandler.getOuterWidth(next) + (parseFloat(next.style.right) || 0);
                    }
                    this.el.nativeElement.style.right = right + 'px';
                }
                else {
                    let left = 0;
                    let prev = this.el.nativeElement.previousElementSibling;
                    if (prev) {
                        left = DomHandler.getOuterWidth(prev) + (parseFloat(prev.style.left) || 0);
                    }
                    this.el.nativeElement.style.left = left + 'px';
                }
    
                let filterRow = this.el.nativeElement.parentElement.nextElementSibling;
    
                if (filterRow) {
                    let index = DomHandler.index(this.el.nativeElement);
                    if (filterRow.children && filterRow.children[index]) {
                        filterRow.children[index].style.left = this.el.nativeElement.style.left;
                        filterRow.children[index].style.right = this.el.nativeElement.style.right;
                    }
                }    
            });
        }
    }

**Comment by Daniel-M-A** [comment]
I am running in this issue in our project as well in every table with virtual scroll and frozen columns. 

The scrolling issue scales in intensity with how long it takes to render the page. 
Scrolling vertically makes the scroll bar/content go up and down erratically even more so in a busy page. 

The workaround above https://github.com/primefaces/primeng/issues/12015#issuecomment-1273150302 fixes the vertical scrolling issue, however when horizontal scrolling is also possible (scrollDirection="both") these steps causes a different issue.
1. Scroll right, there is no issue yet and the frozen column works as intended
2. Scroll down
3. the left frozen columns flicker as you scroll.

A fix or fix version would be appreciated for us to use virtual scrolling and frozen column.  Thanks

**Comment by jonathan-fortin** [comment]
Hi,

We have the same problem in my project. We have updated to the latest version due to the [Virtual Scroll Fix](https://github.com/primefaces/primeng/issues/10630). But we are still stuck because we used frozen columns.

Do you have any information or when this will be fixed?

Thanks!
