### ISSUE TITLE
Menu: Render items via HTML template

### ISSUE THREAD

**Issue by elvirusDE** [primefaces/primeng#12018]
### Describe the feature you would like to see added

1. It should be possible to render a menu's items via the HTML template and not only by having a model in the controller.

2. Moreover, it would be nice to not be restricted to just links with text labels and icons. It should be possible to have any HTML or component be rendered into the menu container like f. i. a `<p-slider>`.

### Is your feature request related to a problem?

Having a model in the controller for the sole purpose of displaying a menu in the template does violate the pattern of separation of concerns. So, if you're not implementing an application the reactive way, then this is not what you want to have in your controller. 

### Describe the solution you'd like

There should not be any issue to make 1. possible. Something like that:
```
<p-menu>
  <p-menuitem label="" icon="" ...></p-menuitem>
</p-menu>
```
This would involve having a component called MenuItem (`<p-menuitem>`) which can be added in the template manually. You would have to decide if it should be possible to have both methods in place (definition by model and definition by template) or to take one over the other. I would expect both to work at the same time like f. i. with the MenuBar component where this is currently possible. I wouldn't mind having the same approach working here as well.

Making 2. possible would be the best solution in my opinion. Something like that currently is working in MenuBar and I would expect it to be working here as well.
Suggestion a:
```
<p-menu>
    <input type="text" pInputText placeholder="Search">
    <button pButton label="Logout" icon="pi pi-power-off"></button>
</p-menu>
```
Suggestion b:
```
<p-menu>
    <ng-template pTemplate>
      <li class="p-menuitem">
        <let-me-have-anything-i-want-here />
      </li>
    </ng-template>
</p-menu>
```

### Describe alternatives you have considered

Because I want to implement a menu which does not only rely on having text-based menu items, I am not able to use the Menu component although it should be not much of a big deal to make it work.

Consider a menu like the application menu on the top bar in MacOS or even Windows (See the attached screenshots). There are items which are input elements. There should not be any restriction on what items to use as menu items. As long as it is valid HTML it should be a valid item. Styling the item (like a proper height and such) could be brought into the p-menuitem css base class but it would also be ok to let the developer be responsible for proper styling in that case.

<img width="314" alt="Bildschirmfoto 2022-10-06 um 22 50 08" src="https://user-images.githubusercontent.com/34682409/194416611-69b90621-a268-45c5-95c6-b1fc77f235b2.png">
<img width="210" alt="Bildschirmfoto 2022-10-06 um 22 49 48" src="https://user-images.githubusercontent.com/34682409/194416621-2c913eb4-ec60-4e82-a65d-95f194f43f94.png">

Sadly, there are no possible solutions available in the vast library of PrimeNG components to help me realize the concept described above.

### Additional context

I think it should _always_ be _template first_. View related stuff should always be made possible to be declared in the template where it belongs to. Having a model should be an optional nice to have. You should always be able to insert any valid HTML as a child in any component.

Please consider this as a pattern for current and upcoming developments.

**Comment by imaliouris** [comment]
any update on this?

**Comment by elvirusDE** [comment]
> any update on this?

Would still love to have that feature…

**Comment by Mvrlex** [comment]
I also need this feature for the context-menu.
It would be enough to just be able to add a template, like the p-tree already supports:

**p-tree:**
```html
<p-tree [value]="nodes">
    <ng-template let-node pTemplate="default">
        <b>{{ node.label }}</b>
    </ng-template>
</p-tree>
```

**p-contextMenu suggestion:**
```html
<p-contextMenu [model]="menu">
  <ng-template let-item pTemplate="menuitem">
    <b>{{ item.label }}</b>
  </ng-template>
</p-contextMenu>
```

I actually need this because otherwise the contextMenu does not support adding custom icons.

**Comment by cetincakiroglu** [comment]
Hi,

We've introduced item templating for menu components. https://primeng.org/menu#custom
