### ISSUE TITLE
`uploadLabel` is not working on basic mode of the FileUploadModule module

### ISSUE THREAD

**Issue by ruskovweb** [primefaces/primeng#12019]
### Describe the bug

I am using the FileUploadModule in basic mode and the `uploadLabel` prop is not working. It shows the file name instead of my custom label.

```typescript
 <p-fileUpload
      mode="basic"
      accept="image/*"
      chooseIcon="pi pi-folder-open"
      chooseLabel="Browse"
      styleClass="border-round-lg"
      uploadLabel="Upload"
      [multiple]="false"
      [customUpload]="true"
      [maxFileSize]="1000000"
      (onSelect)="onSelect($event)"
      (uploadHandler)="upload()"
    >
    </p-fileUpload>
 ```

### Environment

Firefox 102.3.0esr (64-bit)

### Angular version

~14.0.0

### PrimeNG version

^14.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.15.0

**Comment by volvachev** [comment]
Hi, `uploadLabel` works only for `advanced` mode, for `basic` use `chooseLabel`.

**Comment by ruskovweb** [comment]
I am using the `chooseLabel` but it is for a different button. I can't change the label of the upload button.

**Comment by volvachev** [comment]
> I am using the `chooseLabel` but it is for a different button. I can't change the label of the upload button.

There's only one button in this mode - it can't be both `choose` and `upload` - so it seems to me. Do you want `uploadLabel` instead of the name of the uploaded file?

**Comment by ruskovweb** [comment]
Yes I want a custom label instead of the uploaded file name.

**Comment by ruskovweb** [comment]
The `chooseLabel` works as expected:
![image](https://user-images.githubusercontent.com/24957807/195515222-ee0da6e8-f310-4847-86db-50408c0aa212.png)

but the upload button label can't be changed:
![image](https://user-images.githubusercontent.com/24957807/195515419-89def686-b73e-4af9-ae6e-c7538db3d8c4.png)

I can change the icon of that button with `uploadIcon`, but I can't change its label.

**Comment by volvachev** [comment]
I see your point, I am preparing a pull request for your request.
