### ISSUE TITLE
Toggeable P-PANEL under another toggeable P-PANEL overflow not handled for sub-panel

### ISSUE THREAD

**Issue by benamrou** [primefaces/primeng#12013]
### Describe the bug

Primeng version:   "primeng": "^14.1.1"

I have a toggeable p-panel panel with another toggeable p-panel, the sub-panel is not handling the overflow and is always displayed even on clicking the top right toggle button.

Here the code and after my workaround:

                <p-panel id="Schedule#{{indice}}" header="Schedule#{{indice}} {{periodStart | date:'MM/dd/yyyy' }} - {{periodEnd | date:'MM/dd/yyyy' }}" 
                         [toggleable]="true" [collapsed]="true">
                        
                    <div class="row">
                        <div class="ui-g-9"> 
                            <p-panel id="Schedule#{{indice}}_1" [toggleable]="true" [collapsed]="true" 
                                     header="Schedule applied on {{schedule.sites.length}} sites">
                                <div class="alternateColor">
                                    <ng-container *ngFor="let siteSchedule of schedule.sites">
                                        <div>
                                            <input type="checkbox" [(ngModel)]="siteSchedule.applyChanges" [ngModelOptions]="{standalone: true}"/>
                                            {{ siteSchedule.code }}  {{siteSchedule.description}} 
                                        </div>
                                    </ng-container>
                                </div>
                            </p-panel>
                        </div>
                    </div>
                </p-panel>

Workaround:
Force the toggeable-content to hidden.

.p-panel-toggleable .p-toggleable-content {
  overflow: hidden !important;
}

### Environment

Primeng & Angular version 
    "primeng": "^14.1.1"
    "@angular/animations": "^14.2.0",
    "@angular/common": "^14.2.0",
    "@angular/compiler": "^14.2.0",
    "@angular/core": "^14.2.0",
    "@angular/forms": "^14.2.0",
    "@angular/platform-browser": "^14.2.0",
    "@angular/platform-browser-dynamic": "^14.2.0",
    "@angular/router": "^14.2.0",

[15:47:41]@~ $npm --version
8.19.1

### Angular version

12.2.0

### PrimeNG version

14.1.1

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

8.19.1

### Browser(s)

Chrome

### Steps to reproduce the behavior

Create one toggeable p-panel and another toggeable p-panel inside the first p-panel.

Ensure you have content on the sub p-panel.

The sub p-panel content is always displayed even if the sub p-panel is closed. 

### Expected behavior

The sub-panel should be toggeable

**Comment by sbs101** [comment]
We are also affected by this bug. In our case we have a p-accordion element inside of a p-panel element. The accordion tabs also have the p-toggable-content class and are thus affected by the following inline rule aiming at p-panel 

```
.p-panel-toggleable.p-panel-expanded .p-toggleable-content:not(.ng-animating) {
      overflow: hidden;
    }
```

**Comment by uebelmar** [comment]
#12164 possible duplicate.

**Comment by benamrou** [comment]
right same issue as #12164 . Go ahead keep only one open.

**Comment by rafparedis** [comment]
I've also experienced this issue. Thanks @benamrou for the workaround !
