### ISSUE TITLE
Component: Calendar

### ISSUE THREAD

**Issue by btpy** [primefaces/primeng#12017]
### Describe the bug

Hi! With number of months greater than one `yearNavigator` and `monthNavigator`  seems not to be working.

`<p-calendar [(ngModel)]="dateModel"
                      #calendar
                      selectionMode="range"
                      (onShow)="onCalendarShow()"
                      [readonlyInput]="false"
                      [maxDate]="maxDate"
                      [dateFormat]="'dd/mm/yy'"
                      (ngModelChange)="calendarlChange($event)"
                      [numberOfMonths]="2">`

Thanks.

### Environment

macOS Monterey 12.5
Google Chrome `Version 105.0.5195.125 (Official Build) (arm64)`

### Angular version

14.2.3

### PrimeNG version

14.1.1

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

16.13.2

### Browser(s)

Chrome 105

**Comment by capc0** [comment]
this seems to be by design (https://github.com/primefaces/primeng/blob/master/src/app/components/calendar/calendar.ts#L1428), however I also think it would be nice if navigation is still supported when more than one month is showh.
