### ISSUE TITLE
Sidebar Header Template

### ISSUE THREAD

**Issue by mbarmettler** [primefaces/primeng#12025]
### Describe the feature you would like to see added

possibility to add a ` "pTemplate="header"` like in other primeNG components

### Is your feature request related to a problem?

currently the header is not customizable and stays as ugly as it is per default

### Describe the solution you'd like

like in other PrimeNG components: implement of "pTemplate="header" in order to be able to template the header section

### Describe alternatives you have considered

currently no way out of this....

**Comment by Tazaf** [comment]
Completely agree with this.

I was rather surprised to see it was not already the case, honestly, as most of the other components are very flexible and customizable.
