### ISSUE TITLE
[Feature Request] autocomplete "field" could be "fields" - Would like to display multiple properties in object

### ISSUE THREAD

**Issue by praveens4all** [primefaces/primeng#1202]
Currently autoComplete is accepting only one field in suggestion, I need to display multiple fields in suggestion.

example: 
Obejct : address fields: streetname, suburb, country
current : field = "streetname"
expected : fields = "streetname, suburb, country"

**Comment by cagataycivici** [comment]
I'd suggest using templating with item template and selected item template with 2.0.1.

**Comment by kavoos** [comment]
@cagataycivici , I use template for my dropdown item and it works perfectly. But when I choose an item, I want to have both firsname and lastname to be shown and not just one field. Can you give me some tips?

```
<p-autoComplete 
      formControlName="trader"
      [suggestions]="traders" 
      field="lastname"
      [dropdown]="true" 
      readonly="true"
      (onDropdownClick)="handleTradersDropdown($event)"
      placeholder="Trader">
            <ng-template let-trader pTemplate="item">
                  <div>{{trader.firstname }} {{trader.lastname }}</div>
            </ng-template>
</p-autoComplete>
```

**Comment by SinghManvir** [comment]
Another issue regarding this is open - https://github.com/primefaces/primeng/issues/4269

**Comment by minhdtb** [comment]
I have the same issue. Any update now?

**Comment by MarcosQ** [comment]
This is a very helpful feature. ¿Any progress or is it impossible for now?

**Comment by blosser** [comment]
We need it too.

**Comment by sourdoth** [comment]
I "solved" the problem in the following way, I hope it will help you until they implement the definitive option

HTML
`<!--  **NOT set/put "field" attribute** -->`
`<p-autoComplete #customId [(ngModel)]="value" (onSelect)="select($event)" [suggestions]="suggestions" (completeMethod)="filter($event)">`
   ` <ng-template let-v pTemplate="item">`
              `{{v.name}} {{v.lastname}} {{v.etc}}`
    `</ng-template>`
`</p-autoComplete>`

TS
@ViewChild('customId', {static: false}) auto:any;

select(v : any) {
    let allFilds:string = v.name+' '+v.lastname.....
    this.auto.inputFieldValue = allFilds.trim();
}
