### ISSUE TITLE
Table RowSpan Grouping & (Virtual) Scrolling

### ISSUE THREAD

**Issue by the-bullbash** [primefaces/primeng#12033]
### Describe the bug

P-table rowspan grouping does not work with [scrollable]="true" (or [virtualScroll]="true") (or vice versa)

### Environment

Simple angular project with latest version of angular and primeng

### Reproducer

https://stackblitz.com/edit/primeng-tablerowgroup-demo-q54pb7?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

### Angular version

14.2.4

### PrimeNG version

14.1.2

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

16.17.0

### Browser(s)

Chrome 105

### Steps to reproduce the behavior

1. Get example from Table RowSpan Grouping
2. Add scrolling properties
    [scrollable]="true"
    scrollHeight="600px"
or virtual scrolling properties
    [virtualScroll]="true"
    [rows]="20"
   

### Expected behavior

Scrolling (and virtual scrolling) works with row span grouping together

**Comment by JensUweB** [comment]
Can confirm the Bug for Angular v15.0.2 and Primeng v15.0.0-rc.1 (node v18.12).
