### ISSUE TITLE
[NPM] missing minor versions - v12.2.4 and v12.2.5

### ISSUE THREAD

**Issue by ampmonteiro** [primefaces/primeng#12035]
### Describe the bug

In NPM  is not listing this two minor version:

- v12.2.4 
- v12.2.5

which solve some important bugs.

![image](https://user-images.githubusercontent.com/31895754/195417973-018cddd1-c5e4-4ace-9806-4f1e6411836e.png)

### Environment

not relevant

### Angular version

12

### PrimeNG version

12

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

14

**Comment by aksdevac** [comment]
Hi @ampmonteiro it seems it was intentional its only available in LTS version which is commercial see following:
https://www.npmjs.com/package/primeng-lts
