### ISSUE TITLE
[Migration Guide] - missing for  v13

### ISSUE THREAD

**Issue by ampmonteiro** [primefaces/primeng#12036]
### Describe the bug

I read that you will publish the migration guide when v14 of Angular is released.

So when will be ?

Like you mention here:  
https://forum.primefaces.org/viewtopic.php?t=69986

I did today a the migration for v13 at the company i am currently worked, so far no problem,
But i need info if exist any breaking changes or minor changes, before finished the migration.

Thanks.

### Environment

no relevant

### Angular version

13

### PrimeNG version

13

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

14

**Comment by aksdevac** [comment]
Hi, I have also updated to primeng 14.x from 13.x without any issues it seems there are no major breaking changes, only found breaking changes list in 1st RC release:
https://github.com/primefaces/primeng/blob/master/CHANGELOG.md#1400-rc1-2022-06-29

**Comment by ampmonteiro** [comment]
> Hi, I have also updated to primeng 14.x from 13.x without any issues it seems there are no major breaking changes, only found breaking changes list in 1st RC release: https://github.com/primefaces/primeng/blob/master/CHANGELOG.md#1400-rc1-2022-06-29

I said about about migration from v12 to v13 of primeng.

**Comment by aksdevac** [comment]
Ok, there is no migration guide for it, but by looking at v13 changelog, it seems there are no primeng specific breaking changes in v13.x. just update angular to v13 & then you should be able to update to primeng v13.

**Comment by ampmonteiro** [comment]
Hi @aksdevac ,
since angular v14 is already released, this information about primeng v13 should be already available on changelog .md about migration between  v12 -> v13.
So someone of primeng team, please update that file and then close this issue.
Thanks.

**Comment by Kisters-BS** [comment]
Now PrimeNG 15 is released and we still have no migration guide for 13+. Can it please be updated any time soon?

**Comment by mmlitvin** [comment]
I have the same question.. Where is migration guide to PrimeNG 15

**Comment by mycahmason** [comment]
Please update the migration guide to include all the versions since 12. Even if there are no breaking changes etc. it would be nice if any steps were explicitly mentioned in the guide.

 Weird that the updates stopped after v12... 🤔
https://github.com/primefaces/primeng/wiki/Migration-Guide

**Comment by sthompson-celerity** [comment]
I guess we can make this the new migration guide:
v15
removes components:
  GMap #12781
  Recaptcha #12781
css classes removed:
  p-toolbar-group-right and p-toolbar-group-left in favor of p-toolbar-group-start and p-toolbar-group-end   #12364
v14
remove components:
 p-fullCalendar #12152
Something happened with these:
  p-chips #12089
  anything that is a virtual scroller
css changes:
  p-tables are odd #12047

There is something else, but I dont know what I just remember a few months ago I tried to upgrade to 14 and something was REALLY broken so good luck finding it!
v13
? I dont know

**Comment by Tantol** [comment]
Half a year and nothing new in guide.

**Comment by mycahmason** [comment]
Migration guide has still not been updated:

https://github.com/primefaces/primeng/wiki/Migration-Guide
