### ISSUE TITLE
Table CSS Improvements

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#12047]
### Describe the bug

Table uses min-width: 100% with table-layout: fixed but min-width makes table-layout to auto. Also responsiveLayout scroll uses table-layout: auto which we can avoid. responsive prop should be deprecated and table should default to scroll while stacked being the alternative.

While on it, we should also make css more strict e.g.

```css
.p-datatable table {}
```

should be;

```css
.p-datatable-table {}
```

Otherwise nested tables get effected.

Breaking changes are;

- responsive prop is obselete has no effect.
- responsiveLayout is now defaults to scroll.

### Environment

PrimeNG 14.2.0

### Angular version

14

### PrimeNG version

14

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

all

### Browser(s)

all

**Comment by eXpertise7** [comment]
@cagataycivici  @cetincakiroglu test of v14.2.2 from developer that uses p-table:

How's that all of suddenly on individual (single column) and dynamic columns (generated dyncamically *ngFor let variable in template) setting any widths (either width, or max-width, ...) doesn't work properly as it did on v14.0.2 and before?

My table is trying to auto-fit columns by comparing <td> text content probably. It ignores set up widths on either individual or either dynamic columns.

Why setting styles for width attributes or css class with width attributes doesn't work properly anymore, it gets set , as I can see on Inspector tab, but in the layout it's totally different situation.

`<th [style]="{ width: '300px', 'max-width': '300px' }"`

or

`<th*ngFor="let column of columns$ | async" [style]="{ width: '200px' }"`

Table properties:

![image](https://user-images.githubusercontent.com/17203747/207087704-d260b7ec-7996-4431-834e-a20866876618.png)

Thanks in advance. Any feedback would be helpful.


Kind regards,
Robert

**Comment by mountpoint** [comment]
Fully agree with @eXpertise7. I also added this piece of code and my scrollable tables work normally again. Before this scroll in tables did't work.

@cagataycivici look at this again

**Comment by nicholas-ochoa** [comment]
@eXpertise7 THANK YOU! I realized my column widths were screwed up and ended up on this issue to try and see what I would need to change / fix and your snipper solved the problem nicely.

**Comment by yelhouti** [comment]
I tracked an issue after update to this commit.
We `.p-table-wrapper` `overflow: auto` when I have an autocomplete, dropdown... in the footer, it gets cropped and I need to append to body which is not ideal for accessibility. Any idea how to fix this ?
