### ISSUE TITLE
Multiselect Dropdown Position issue

### ISSUE THREAD

**Issue by nikhilawasarikar** [primefaces/primeng#12053]
### Describe the bug

While using the PrimeNG Multiselect field on the Angular application, I came across this issue. While searching in the Multiselect field's search box, when the user types in any string in the box that doesn't match the dropdown records, the popup box's position changes and it goes upwards. It detaches with the Multiselect field while searching the records. Can you please let me know if there is any way to keep the dropdown popup always attached to the field? 
Please find the video to get the exact idea about the issue here - https://drive.google.com/file/d/1EaMXDS9evznvb8OX2K6FOQF_3WLMmdeu/view?usp=sharing
Waiting for your quick response.

### Environment

Localhost Environment

### Angular version

13.2.5

### PrimeNG version

11.4.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

2.0.15

### Browser(s)

Chrome

**Comment by nikhilawasarikar** [comment]
Can you check and reply ASAP on this issue?

**Comment by Chazing** [comment]
Also happens in version 14.2.3,
is there an update?
