### ISSUE TITLE
Primeng icons does not work as explained in the documentation

### ISSUE THREAD

**Issue by pavangayakwad** [primefaces/primeng#12065]
### Describe the bug

The icons doesn't show up as explained in the documentation, it is either wrong or missing important piece of configuration information: https://www.primefaces.org/primeng/icons

### Environment

OS Linux : Pop!_OS 22.04

### Angular version

14.2.6

### PrimeNG version

14.1.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.17.1

### Steps to reproduce the bug
Open command prompt do the following

`ng new primeng-icons-test-angular-app`

Answer the following queries as given below

```
? Would you like to add Angular routing? *No*
? Which stylesheet format would you like to use? *CSS*
```

after the project creation, 

`cd primeng-icons-test-angular-app`

`npm install primeicons --save`

`code .` [assuming VSCode editor is installed on the machine]

Go to `app.component.html` page, delete all HTML code and add this:

```
<i class="pi pi-check"></i>
<i class="pi pi-times"></i>
```

back to command prompt and run this
`npm start`

open browser and navigate to http://localhost:4200

You will see a page with no icons [blank]!

### Expected behavior

Prime NG icons should appear on the test page after following the above steps.

**Comment by gucal** [comment]
Hi,
Please import PrimeIcons file. 

In angular.json file find the styles array and add the following:
"node_modules/primeicons/primeicons.css",

Check out the PrimeNG document for details. https://www.primefaces.org/primeng/setup

**Comment by pavangayakwad** [comment]
yes, it did work after the node_modules inclusion (as you mentioned). my bad. thank you very much for the swift response.
