### ISSUE TITLE
Breaking change in `peerDependencies` from 14.1.1 to 14.1.2

### ISSUE THREAD

**Issue by papb** [primefaces/primeng#12064]
Hello, thank you for the great work in primeng!

I believe the 14.1.2 release of PrimeNG includes a breaking change. Until 14.1.1, PrimeNG 14 included `primeicons@^5.0.0` as a `peerDependency`. With PrimeNG 14.1.2, it changed to `primeicons@^6.0.1`. From the perspective of Semantic Versioning, this is a breaking change. It caused problems for me because I had `primeicons@^5.0.0` as an explicit dependency of my project, and attempting to upgrade PrimeNG from 14.1.1 to 14.1.2 caused an "invalid peer dependency" error.

Upon further investigation, [there doesn't seem to be any breaking changes from `primeicons` 5.0.0 to 6.0.0 though](https://github.com/primefaces/primeicons/issues/828), which is weird.

If possible, I'd like to suggest a new patch release of PrimeNG (currently it would be 14.1.3) in which that line is changed as follows:

```diff
- "primeicons": "^6.0.1"
+ "primeicons": "^5.0.0 || ^6.0.1"
```

This way it would no longer be a breaking change. However, this can only be done if PrimeNG 14.1.2 does not depend on anything added by primeicons 6.0.1.

**Comment by papb** [comment]
For those with the same `peerDependency` issue, I recommend just upgrading `primeicons` from 5 to 6, so the problem will vanish. This should be trivial because (for now) it seems there aren't any real breaking changes between the two versions.

**Comment by AlsGomes** [comment]
Had the same problem. 

Thanks for opening the issue and, upgrading from 5 to 6 the primeicons dependency, in fact, resolved the problem.
