### ISSUE TITLE
Component: Treetable (expanding rows)

### ISSUE THREAD

**Issue by maertz** [primefaces/primeng#12063]
### Describe the bug

In case the treetable has less rows then available space, all rows spread across the available space when **virtualization** is turned on.
Which is a weird behaviour since other tables without virtualization do not behave like that, they display rows as usual and do not occupy forcefully the whole "table viewport".

### Environment

https://stackblitz.com/edit/primeng-treetablescroll-demo-ibudhw?file=src/app/app.component.html

### Angular version

14.1.3

### PrimeNG version

14.0.2

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

LTS

### Steps to reproduce the behavior

- Simply create a tree table
- Turn on virtualization on
- Increase viewport (e.G. you wanna fulfill the available space and scroll only when the content exceeds)
- Set just few rows 

https://stackblitz.com/edit/primeng-treetablescroll-demo-ibudhw?file=src/app/app.component.html

### Expected behavior

Rows do not expand across available space like in the other examples without virtualization.

**Comment by dsubelman** [comment]
I'm having the same issue with the latest versions:

- Angular version: 15.1.5
- PrimeNG version: 15.2.0

Any news on this bug?

**Comment by kevindux** [comment]
@dsubelman removing min-height: 100% and position:absolute solved it completely for me.

**Comment by dsubelman** [comment]
@kevindux, unfortunately, setting the position to absolute didn't work for me.

Can you test expanding and collapsing branches? In my case, when I collapse a branch, it doesn't scroll. However, when I expand it, it allows scrolling again.

**Comment by kevindux** [comment]
@dsubelman the class .p-scroller-content already has position: absolute. So overriding it by `unset` for example helped me.
Scrolling is a whole nother thing, it's completely broken when having virtualscroll turned on.
I added a eventlistener with a workaround to manually set the scrollTop.
