### ISSUE TITLE
Spinner: No keyboard input when using the [size] attribute

### ISSUE THREAD

**Issue by ClementVidal** [primefaces/primeng#1207]
p-spinner is apparently not working correctly when used with **ONLY** the **size** parameter:

With this
`<p-spinner [(ngModel)]='dailyRate' min='0'></p-spinner>`
everything works fine.

But with 
`<p-spinner [(ngModel)]='dailyRate' min='0' size='10' ></p-spinner>`
the spinner do not seamns to intercept any keyboard input, only the arrows can be used.

The issue seams to come from the fact that _adding the **size** attribute automaticly add the **maxlength** attribute with a value of **0** to the p-spinner underlying input HTMLElement_.

One work around is to also add the maxlength attribute to the p-spinner with a value above 0.

So this: 
`<p-spinner [(ngModel)]='dailyRate' min='0' size='10' maxlength='10' ></p-spinner>`
Solve the problem.

---------

- PrimeNg rc.3
- Angular 2.1.2

**Comment by cagataycivici** [comment]
Fixed at #1197
