### ISSUE TITLE
p-inputNumber:Paste decimals doesnt work

### ISSUE THREAD

**Issue by neldrak** [primefaces/primeng#12079]
### Describe the bug

Reproducer:
https://stackblitz.com/edit/primeng-inputnumber-demo-r6aaxk?file=package.json
Enter a number without decimals (e.g. 1)
Select that number and ctrl +v (paste) a number with a decimal (e.g. 1.1).
The Paste gets ignored, although a number with one decimal should be allowed.
Also pasting after the number doesnt work, but should be allowed as the number 11.1 would be correct (one decimal).
After clearing the whole field, pasting the same number works fine.

### Environment

https://stackblitz.com/edit/primeng-inputnumber-demo-r6aaxk?file=src/app/app.component.html

### Angular version

13.0.3

### PrimeNG version

14.1.2

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

v16

### Steps to reproduce the behavior

Reproducer:
https://stackblitz.com/edit/primeng-inputnumber-demo-r6aaxk?file=package.json
Enter a number without decimals (e.g. 1)
Select that number and ctrl +v (paste) a number with a decimal (e.g. 1.1).
The Paste gets ignored, although a number with one decimal should be allowed.
Also pasting after the number doesnt work, but should be allowed as the number 11.1 would be correct (one decimal).
After clearing the whole field, pasting the same number works fine.

### Expected behavior

The pasted decimal number should show.

**Comment by jedsmith13** [comment]
This is still an issue. I am encountering it using version 15.4.1
