### ISSUE TITLE
Button: Directive class on label change

### ISSUE THREAD

**Issue by yelhouti** [primefaces/primeng#12083]
### Describe the bug

Button directives breaks [class.p-button-info] on label change
Class is not applied anymore if label changes

### Environment

Standard

### Angular version

14.2.3

### PrimeNG version

14.1.2

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

v16.13.0

### Steps to reproduce the behavior

```
<button pButton (click)="setMode('discount')" class="discount mode" [class.p-button-info]="mode === 'discount'"
            label="{{ saleProduct?.discountType === 'PERCENTAGE' ? 'Disc %' : 'Disc'}}"></button>
            
```
When the discountType changes even if mode doesn't change,  p-button-info is removed 

### Expected behavior

It should stay

**Comment by gucal** [comment]
Hi,
Try using `[ngClass]`. 

`<button pButton (click)="setMode('discount')" class="discount mode" [ngClass]="{'p-button-info':mode === 'discount'}" label="{{ saleProduct?.discountType === 'PERCENTAGE' ? 'Disc %' : 'Disc'}}"></button>
            `

**Comment by yelhouti** [comment]
@gucal doesn't work either, please reopen the issue
