### ISSUE TITLE
DataView: Bad Typo in showcase

### ISSUE THREAD

**Issue by uebelmar** [primefaces/primeng#12087]
### Describe the bug

There is a bad typo in the showcase 

p-dataview instead of p-dataView

### Environment

angular 14

### Angular version

14.1

### PrimeNG version

14.1.2

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14

### Browser(s)

all

### Steps to reproduce the behavior

https://primefaces.org/primeng/dataview

**Comment by uebelmar** [comment]
#12086

**Comment by gucal** [comment]
Fixed in https://github.com/primefaces/primeng/pull/12086. Closing the issue.
