### ISSUE TITLE
Component: Table

### ISSUE THREAD

**Issue by zozo8** [primefaces/primeng#12095]
### Describe the bug

When using p-table with stateStorage and resizableColumns the table is being extended over the size of container - in my p-card. This happens only after restoring state from local storage, so make sure you will resize any column then refresh the view.
I do believe it may be connected with adding style="width: XXXXpx;" property for first div under the p-table
Are there any known workarounds for that issue? Or maybe I've configured something wrongly.
Thank you in advance for helping me out.

Here is the screenshot of the issue:
Actual:
![image](https://user-images.githubusercontent.com/50959052/197764667-b05bc79b-d677-4e5a-8f66-d2263392430a.png)

Expected:
![image](https://user-images.githubusercontent.com/50959052/197765155-8b475678-dc5e-4840-8a70-ceadce550541.png)

### Environment

Windows 10 or 11

### Reproducer

https://stackblitz.com/edit/primeng-tablestate-demo-qdp7qc?file=src%2Fapp%2Fapp.component.html

### Angular version

11.0.4

### PrimeNG version

13.0.4

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

0.0.0

### Browser(s)

Chrome 106

### Steps to reproduce the behavior

1. Resize any column to be wider
2. Refresh view

### Expected behavior

The table should remain inside the card and should show scrollbar on the bottom

**Comment by mertsincan** [comment]
Hi,

I think this issue has already been fixed in 14.2.0. For now, closed. If the problem persists with 14.2.0, please reopen this ticket.

Best Regards,

**Comment by zozo8** [comment]
I can see version 14.2.0 was not released yet, but I managed to update the example to 14.1.2, which is the latest for now (please, see link: https://stackblitz.com/edit/primeng-tablestate-demo-kjwedr?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html,package.json).

The issue here is even with wider columns, they are being collapsed to the size of view, which is also unexpected behaviour. Could you please assure me, that in 14.2.0 the column widths will be restored properly?
Thank you!
