### ISSUE TITLE
Erro using Angular 2.1.0 with angular-cli 1.0.0-beta.18

### ISSUE THREAD

**Issue by aderbas** [primefaces/primeng#1209]
I installed with npm install and change this files:

angular-cli.json
```
...
"styles": [
      "styles.css",
      "../node_modules/primeng/resources/primeng.min.css",
      "../node_modules/primeng/resources/themes/omega/theme.css"
   ],
   "scripts": [
   "../node_modules/primeng/primeng.js"
 ],
...
```
app.module.ts

```
import { BrowserModule }    from '@angular/platform-browser';
import { NgModule }         from '@angular/core';
import { FormsModule }      from '@angular/forms';
import { HttpModule }       from '@angular/http';
import { DataGridModule }   from 'primeng/primeng';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    DataGridModule,
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

And I'm get this error: `Uncaught Error: Unexpected value 'undefined' imported by the module 'AppModule'`. 
**DataGridModule** is undefined?

ng build or serve does not report  any error

**Comment by cagataycivici** [comment]
@Mrtcndkn  What do you think?

Also have you checked out;

https://yakovfain.com/2016/10/28/adding-primeng-ui-components-to-angular-cli-project/
http://blogs.bytecode.com.au/glen/2016/10/27/primeng-with-angular-cli.html

**Comment by aderbas** [comment]
$ ng version
angular-cli: 1.0.0-beta.18
node: 6.9.1
os: linux x64

**Comment by aderbas** [comment]
I'm created a repo https://github.com/aderbas/teste-app

**Comment by jacobedawson** [comment]
@aderbas Hey - I'm fairly new to Angular2 and was running across the same problem. While carefully looking at the articles that @cagataycivici shared I noticed that neither of them explicitly added the primeng javascript file into angular.cli.json:


...
"styles": [
      "styles.css",
      "../node_modules/primeng/resources/primeng.min.css",
      "../node_modules/primeng/resources/themes/omega/theme.css"
   ],
   "scripts": [
   "../node_modules/primeng/primeng.js" // <<DON'T ADD THIS LINE IT'S NOT NEEDED FOR PRIMENG
 ],
...

Even though when using the Angular CLI it's common to add both the CSS & JS files into angular.cli.json, in the case of PrimeNG it's not necessary, and will cause the error you came across. 

I hope that helps!!

Cheers, 

Jake

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
