### ISSUE TITLE
Document Viewer : add onstart / oncomplete / onerror / ontimeout events

### ISSUE THREAD

**Issue by devmsaleh** [primefaces/primeng#12100]
### Describe the feature you would like to see added

I am using documentViewer with url attribute to load the document from a servlet, and I was hoping if you can add the following attributes 

- onstart : to show loading bar when loading starts
- oncomplete : to hide the loading bar when loading finish
- onerror : to show error message when there's an exception is thrown when loading the document
- timeout : define timeout for loading the document from the url
- ontimeout : to show timeout error message when loading timeout occurs

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
