### ISSUE TITLE
Calendar: change time by holding touch in mobile (now should tap)

### ISSUE THREAD

**Issue by mohammadreza99** [primefaces/primeng#12108]
### Describe the feature you would like to see added

Now by a single click and holding mouse, I can change time continuously, but in mobile devices this feature is not working

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
