### ISSUE TITLE
TreeSelect: add "selectedItemsLabel" and "toggleAll" for multiple/checkbox selection mode

### ISSUE THREAD

**Issue by Adrii77** [primefaces/primeng#12103]
### Describe the feature you would like to see added

As TreeSelect Filter component looks like MultiSelect, it should have almost the same API, such as `selectedItemsLabel` and `showToggleAll` when the component is used with multiple/checkbox selection mode.
Cherry on the cake if we can custom the label when all items are selected.

### Is your feature request related to a problem?

I implemented a form with a MultiSelect component for one of its control.
The UI/UX designer from my team added some changes on its sketch... until to became a "Filter TreeSelect". Problem -> I lost `selectedItemsLabel`  and `ToggleAll` features. It seemed strange to me to not find the same MultiSelect's API in multiple selection mode (as they look alike).

### Describe the solution you'd like

Retrieve a toggle all checkbox and allow to set `selectedItemsLabel`, as MultiSelect, when selectionMode is equal to "checkbox" or "multiple".

Also, that would be really cool if we can set a "allSelectedLabel", when all items are selected.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
