### ISSUE TITLE
JumpToPageInput Custom Template in p-paginator component

### ISSUE THREAD

**Issue by pouyababaie** [primefaces/primeng#12107]
### Describe the feature you would like to see added

It would be good that we can customize JumpToPageInput template.
like the paginators  

### Is your feature request related to a problem?

_No_

### Describe the solution you'd like

_No_

### Describe alternatives you have considered

Unfortunately There is just one option which is adding some custom CSS classes  via `Renderer2` or `document.getElementByClass() `  Decorator or customizing the primeng classes which isn't really a good practice

### Additional context

and by the way , why in p-paginator , there is no separation between p-component's Childs div , wouldn't be better if for example next and prev button where in a div instead o f flying around in p-component div.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
