### ISSUE TITLE
Component: PTable and VirtualScroll

### ISSUE THREAD

**Issue by lemonCMS** [primefaces/primeng#12113]
### Describe the bug

When having virtualScroll enabled on a table with many columns, the layout is broken. The width of the Headers and corresponding columns do not match anymore.

I would expect the width for the headers and columns would be the same.
 
![image](https://user-images.githubusercontent.com/4980003/199012293-fbd998ec-e944-4fbd-8f0d-3675863a10ee.png)

### Environment

Used the provided stack blitz template to reproduce the problem

### Reproducer

https://stackblitz.com/edit/github-r2bwhp?file=src%2Fapp%2Fapp.component.html

### Angular version

14.0.7

### PrimeNG version

14.0.2

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

14

### Steps to reproduce the behavior

Go to the provided example, you will see directly the mismatch between table header and table content.

### Expected behavior

The width of the table header and column should be the same when using virtual scroll.
This was working in primeNG 13 [example](https://stackblitz.com/edit/primeng-tablevirtualscroll-demo-u9w4la?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html).

**Comment by mertsincan** [comment]
This issue has already been fixed in v14.2.0+. Please update your primeng version. Exp;
https://stackblitz.com/edit/github-r2bwhp-mcg6nh?file=package.json

Best Regards,
