### ISSUE TITLE
Component: P-table  paginator manullay set rowsPerPageOptions

### ISSUE THREAD

**Issue by Saura81** [primefaces/primeng#12129]
### Describe the feature you would like to see added

We need a feature to add a custom value into the dropdown related to the paginator on the p-table. Manually the user should be able to insert a value into an editable field of the dropdown and add it to the rowsPerPageOptions

### Is your feature request related to a problem?

Is in relation to the checkAll/uncheckAll button no loading all elements when checked if a pagination of lazy loading is triggered. Solution asked by client is to be able to load X amount of records into table to be all check , some are fixed values but also wants a custom value

### Describe the solution you'd like

`@Input() rowsPerPageOptions = [10, 25, 50, 100, 250,{showAll:'All'}, {userCustomValue}];`

![image](https://user-images.githubusercontent.com/12398434/199773073-5df93f4c-9a56-40d7-8037-0c5f58b5b58d.png)

**Comment by Saura81** [comment]
If there is currently any alternative please let me know. Thanks

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
