### ISSUE TITLE
Table: Long text leads to misstyling

### ISSUE THREAD

**Issue by PranKe01** [primefaces/primeng#12139]
### Describe the bug

When having a long text in a column, the table layout gets misstyled. Can be tested here: https://www.primefaces.org/primeng/table/scroll
![image](https://user-images.githubusercontent.com/13560351/200015641-cffdb040-337f-47a9-891f-7ebf8a18b9e6.png)

### Environment

Windows

### Reproducer

https://www.primefaces.org/primeng/table/scroll

### Angular version

14.0.4

### PrimeNG version

4.1.2

### Build / Runtime

TypeScript

### Language

ALL

### Node version (for AoT issues node --version)

14

### Browser(s)

Google Chrome

### Steps to reproduce the behavior

Go to https://www.primefaces.org/primeng/table/scroll
Change the text of a single column value to a loooong value.

### Expected behavior

The text should be cut off (maybe with ellipsis), to make sure the table style will not break.

**Comment by PranKe01** [comment]
I could fix it in my project, by setting the tables tds max-width to 0. Anyhow, I think this should work in primeng table without any custom css fixes...

**Comment by mertsincan** [comment]
Hi @PranKe01,

Could you please try it with the latest version? We made some changes related to Table. I think this issue has been already fixed.

**Comment by PranKe01** [comment]
Yeah, looks good in v14.2.1. Will close the issue.
