### ISSUE TITLE
Slider | The range slider handlers jumps strangely in case the same value of the handlers occurs

### ISSUE THREAD

**Issue by Jombasa** [primefaces/primeng#12136]
### Describe the bug

If the default values ​​(0 - 100) are not used and the two handlers come into contact, they start jumping to different positions. 

When analysing with dev tools in the browser, I noticed that the handler's left (style) value changes by as much as the min or max value was specified, again depending on which handler was moving. 

### Environment

Default

### Reproducer

https://github-ha7qx8-5rcmdv.stackblitz.io

### Angular version

14.2.1

### PrimeNG version

14.1.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.15.1

### Browser(s)

Chrome

### Steps to reproduce the behavior

For example, if I have

rangeValues: number[] = [18, 366];
min: number = 18;
max: number = 366;

then for example if I move rangeValues[0] to rangeValues[1] handler (from min to max), it will change left of rangeValues[0] handler to 366% and vice versa to 18% if rangeValues[1] handler is moved to the position of rangeValues[0] handler. 
The same goes if the values ​​are in different positions and rangeValues[0] handler is changed, but in this case it does not change by max.

**Comment by gucal** [comment]
Hi, 
#12175. After the release of 14.2.2, you can use it without any problems.

**Comment by Jombasa** [comment]
> Hi, #12175. After the release of 14.2.2, you can use it without any problems.

There is still bug in your newest solution (I've tried out master/main branch). Try to set [min] to number that is not 0 (I had use 18) and move the most right handler to the min position. It will jump.
