### ISSUE TITLE
Table: Frozen column has no selection outline

### ISSUE THREAD

**Issue by dougmbarcellos** [primefaces/primeng#12132]
### Describe the bug

Clicking on a table row displays a selection outline across the row (on click and focus). However, frozen columns are missing this outline.

### Environment

Windows 10 64 Bit
Chrome 106.0.5249.119

### Reproducer

https://stackblitz.com/edit/table-frozen-column-has-no-selection-border

### Angular version

15.1.0

### PrimeNG version

15.0.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

---

### Browser(s)

Chrome 

### Steps to reproduce the behavior

- Open https://stackblitz.com/edit/table-frozen-column-has-no-selection-border
- Click on some line.
- First column is frozen, and has no outline applied after selection.

### Expected behavior

- Click on some line.
- All columns, including first column has outline applied after selection.

**Comment by dougmbarcellos** [comment]
Workaround:


Apply this css:

```css
tr:nth-child(odd) {
  background-color: #eee;
}
```

**Comment by adrian0015** [comment]
Is there temporary workaround? Tried few css hacks but to no avail :(

**Comment by dougmbarcellos** [comment]
> Is there temporary workaround? Tried few css hacks but to no avail :(

I had to force remove these styles.
