### ISSUE TITLE
14.2.0 TS2380 in overlay.d.ts

### ISSUE THREAD

**Issue by hkjeffchan** [primefaces/primeng#12159]
### Describe the bug

Error: node_modules/primeng/overlay/overlay.d.ts:17:9 - error TS2380: The return type of a 'get' accessor must be assignable to its 'set' accessor type
  Type 'undefined' is not assignable to type 'string'.

17     get mode(): OverlayModeType | string;
           ~~~~


Error: node_modules/primeng/overlay/overlay.d.ts:21:9 - error TS2380: The return type of a 'get' accessor must be assignable to its 'set' accessor type
  Type 'undefined' is not assignable to type 'string'.

21     get styleClass(): string | undefined;
           ~~~~~~~~~~

Error: node_modules/primeng/overlay/overlay.d.ts:25:9 - error TS2380: The return type of a 'get' accessor must be assignable to its 'set' accessor type
  Type 'undefined' is not assignable to type 'string'.

25     get contentStyleClass(): string | undefined;
           ~~~~~~~~~~~~~~~~~


Error: node_modules/primeng/overlay/overlay.d.ts:31:9 - error TS2380: The return type of a 'get' accessor must be assignable to its 'set' accessor type
  Type 'undefined' is not assignable to type 'boolean'.

31     get autoZIndex(): boolean | undefined;
           ~~~~~~~~~~


Error: node_modules/primeng/overlay/overlay.d.ts:33:9 - error TS2380: The return type of a 'get' accessor must be assignable to its 'set' accessor type
  Type 'undefined' is not assignable to type 'number'.

33     get baseZIndex(): number | undefined;
           ~~~~~~~~~~


Error: node_modules/primeng/overlay/overlay.d.ts:41:9 - error TS2380: The return type of a 'get' accessor must be assignable to its 'set' accessor type
  Type 'undefined' is not assignable to type 'ResponsiveOverlayOptions'.

41     get responsive(): ResponsiveOverlayOptions | undefined;
           ~~~~~~~~~~


Error: node_modules/primeng/overlay/overlay.d.ts:43:9 - error TS2380: The return type of a 'get' accessor must be assignable to its 'set' accessor type
  Type 'undefined' is not assignable to type 'OverlayOptions'.

43     get options(): OverlayOptions | undefined;
           ~~~~~~~

### Environment

Mac

### Reproducer

_No response_

### Angular version

14.2.9

### PrimeNG version

14.2.0

### Build / Runtime

TypeScript

### Language

ES6

### Node version (for AoT issues node --version)

v18.11.0

### Browser(s)

_No response_

### Steps to reproduce the behavior

Upgrade to 14.2.0 and build

14.1.2 is fine

### Expected behavior

no error

**Comment by hkjeffchan** [comment]
Angular CLI: 14.2.9
Node: 18.11.0 (Unsupported)
Package Manager: npm 8.19.2 
OS: darwin x64

Angular: 14.2.9
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.9
@angular-devkit/build-angular   14.2.9
@angular-devkit/core            14.2.9
@angular-devkit/schematics      14.2.9
@angular/cdk                    14.2.6
@schematics/angular             14.2.9
rxjs                            7.5.7
typescript                      4.8.4

**Comment by hkjeffchan** [comment]
tsconfig.json:

/* To learn more about this file see: https://angular.io/config/tsconfig. */
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitOverride": true,
    "noPropertyAccessFromIndexSignature": false,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2020",
    "module": "es2020",
    "lib": [
      "es2020",
      "dom"
    ],
    "typeRoots": [
      "node_modules/@types"
    ]
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true,
    "fullTemplateTypeCheck": true,
    "extendedDiagnostics": {
      "checks": {
        "invalidBananaInBox": "error",
        "nullishCoalescingNotNullable": "warning"
      },
      "defaultCategory": "suppress"
    },
    "strictPropertyInitialization": false
  },
  "exclude": [
    "node_modules"
  ]
}

**Comment by brunork26** [comment]
To fix this for the moment you can go into:
/primeng/overlay/overlay.d.ts
and "fix" the setters:
from: `set mode(value: string);`
to: `set mode(value: OverlayModeType | string);`

**Comment by mertsincan** [comment]
Hi @hkjeffchan and @brunork26,

Thanks a lot for your report! Could you please check and test my fix?

**Comment by nestor91sanchez** [comment]
Hi guys, I have the same error, @mertsincan Could you please confirm me the version to fix that?

**Comment by mertsincan** [comment]
@nestor91sanchez I'll release 14.2.1 version asap.

**Comment by mertsincan** [comment]
v14.2.1 Released ;)

**Comment by rashid-naico** [comment]
@mertsincan Thank you so much
