### ISSUE TITLE
p-organizationchart-line-left

### ISSUE THREAD

**Issue by o0hailang0o** [primefaces/primeng#12150]
### Describe the feature you would like to see added

How to use it

### Describe the solution you'd like

I need an example.

### Additional context

I need an example so that I can easily understand

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
