### ISSUE TITLE
p-scrollpanel: custom color settings not working according to documenttion

### ISSUE THREAD

**Issue by myonara** [primefaces/primeng#12153]
### Describe the bug

I'm using the example code from the [p-scrollpanel documentation](https://www.primefaces.org/primeng/scrollpanel). Even in stackblitz I don't get the color in the custombar1 showing up, see stackblitz example.
also the deault color it is hard to identify, that there is a scrollbar.

### Environment

Angular 14with primeng using scss to fulfill primeng documentation example.

### Reproducer

https://stackblitz.com/edit/github-n1z3ua

### Angular version

14.2.9

### PrimeNG version

14.1.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

-

### Steps to reproduce the behavior

Visit the [stackblitz example](https://stackblitz.com/edit/github-n1z3ua) and look the second scrollbar, almost not visibile.

### Expected behavior

Either the default color is set to primary color or the custombar1 example of the documentation is also working in the stackblitz example.

**Comment by myonara** [comment]
the stackblitz example is using an older version (angular 14.0.7 and primeng 14.0.2). after updating the dependencies there are some strange error messages due to the fullcalender.

**Comment by cetincakiroglu** [comment]
Hi,

Stackblitz demo is just updated you can get the same behavior as in https://www.primefaces.org/primeng/scrollpanel
Closing the issue.

Thanks for reporting!
