### ISSUE TITLE
Remove p-fullCalendar component

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primeng#12152]
As you know, this component was using [fullCalendar API](https://fullcalendar.io/). Many changes have been made to this API recently and it was sometimes not possible to adapt it due to technical limitations. That's why we decided to remove this component. However, we will continue to support [fullCalendar](https://fullcalendar.io/) as a style.

**Comment by mocolicious** [comment]
Hi, I'm using this for an important project I've been working very hard on.  would you perhaps reconsider discontinuing its support if I can fix the issue in a PR? @mertsincan

**Comment by Metalefs** [comment]
This was a horrible decision

**Comment by Programmercito** [comment]
fullcalendar.io doesn't have support for Angular 17 and it's not open source for things that this component had, terrible
