### ISSUE TITLE
Component: Table

### ISSUE THREAD

**Issue by ProfEibe** [primefaces/primeng#12166]
### Describe the feature you would like to see added

It would be great if there was an option to select a row in p-table not only with a left-mouse-click but also with a middle-click or right-click.

### Is your feature request related to a problem?

On middle-click nothing happens.

### Describe the solution you'd like

There should be an own event for middle-clicking on a row.

### Additional context

As usecase I think about opening a detail-page for one row in a new tab. When I'm left-clicking I get the onRowSelect Event and can route to the detail-page in the same tab. When I'm middle-clicking it would be great to have a similar Event, like onRowMiddleSelect for example, where I can open the Route in a new Window/Tab.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
