### ISSUE TITLE
Usage <p-panel> inside <p-panel> rendering error

### ISSUE THREAD

**Issue by DarienF** [primefaces/primeng#12164]
### Describe the bug

If you try to use `<p-panel>` component (child) inside another `<p-panel>` component (parent), you will get rendering error --> 
Collapse/expande won't work for inner (child) `<p-panel>` component. Basically panel should be collapsed/expanded on mouse trigger icon click....but it all the time in expanded mode. 
Reason is that some styling for parent expanded panel re-write styling for child collapsed panel.
Here is demo:
https://stackblitz.com/edit/github-navhz3?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

...and HTML for reproduce:
```
<p-panel header="Parent" [toggleable]="true" [collapsed]="collapsed1">
  <ng-template pTemplate="icons">
    <button
      pButton
      class="p-panel-header-icon p-link"
      icon="pi pi-cog"
    ></button>
  </ng-template>
  <div style="width:100%;">
    <!-- <p-panel> inside <p-panel> -->
    <p-panel header="Child" [toggleable]="true" [collapsed]="collapsed2">
      <ng-template pTemplate="icons">
        <button
          pButton
          class="p-panel-header-icon p-link"
          icon="pi pi-cog"
        ></button>
      </ng-template>
      <div style="width:100%;">
        TEST
        <br />
        TEST
        <br />
        TEST
        <br />
        TEST
        <br />
        TEST
        <br />
        TEST
        <br />
        TEST
        <br />
        TEST
        <br />
        TEST
        <br />
      </div>
    </p-panel>
  </div>
</p-panel>
```

### Environment

"primeflex": "^3.2.1",
"primeicons": "^5.0.0",
"primeng": "^14.0.1",

### Reproducer

https://stackblitz.com/edit/github-navhz3?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

### Angular version

14.0.0

### PrimeNG version

14.0.1

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

18.6.0

**Comment by mehmetcetin01140** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.
