### ISSUE TITLE
Galleria：Need support zoom in/out mode

### ISSUE THREAD

**Issue by RobersonLuo** [primefaces/primeng#12165]
### Describe the feature you would like to see added

My app has uploaded some images(png) for each bill, but it's shown unfriendly to the user for some images that are too big or too small.

**Comment by RobersonLuo** [comment]
It's the old issue below reopened:
https://github.com/primefaces/primeng/issues/9694

**Comment by bsogulcan** [comment]
Any news?

**Comment by AndriusdevLa** [comment]
Please just combine image and galleria, its so frustating, having only image preview with all zoom/rotate funcitons and gallery without any functions - should be same for both!!!

**Comment by RobersonLuo** [comment]
> Please just combine image and galleria, its so frustating, having only image preview with all zoom/rotate funcitons and gallery without any functions - should be same for both!!!

Hi Andriusdevla,
I think no need to combine, please see the demo of  the DevUI component "ImagePreview" :
https://devui.design/components/zh-cn/ImagePreview/demo#custom-usage

that's we want and wish help you.
