### ISSUE TITLE
p-tree: checkbox settings disappear while using the filter function

### ISSUE THREAD

**Issue by AlexStefka** [primefaces/primeng#12177]
### Describe the bug

Before filtering, if nodes are selected, that is shown correctly in p-tree:

![image](https://user-images.githubusercontent.com/117895940/201057163-202e0568-1448-45cf-9375-338387f3625e.png)

When filtering, p-tree loses the checkbox states (**_and you are not able to set / change the checkbox states by clicking on it_**)

![image](https://user-images.githubusercontent.com/117895940/201057294-d0794e85-0219-4e9a-87b6-4fa9ab0773e4.png)

When you are filtering and try to change a checkbox state, it throws errors:

![image](https://user-images.githubusercontent.com/117895940/201064141-8a90b6fa-c385-499c-9bf3-9ae21f13da3b.png)

### Environment

Angular frontend application using p-tree in HTML (we use prime-ng 14.0.1, issue also showing up in last version)

### Reproducer

https://stackblitz.com/edit/primeng-treeselection-demo-8ytoay?file=src%2Fapp%2Fapp.component.html

### Angular version

14.5.4

### PrimeNG version

14.0.1

### Build / Runtime

TypeScript

### Language

ALL

### Node version (for AoT issues node --version)

16.17.0

### Browser(s)

Chrome Version 107.0.5304.89 (Offizieller Build) (64-Bit)

### Steps to reproduce the behavior

enter filter term in the filter text field -> checkbox states are all set to not selected

### Expected behavior

checkbox settings should remain when filtering

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
