### ISSUE TITLE
Component: Table

### ISSUE THREAD

**Issue by ProfEibe** [primefaces/primeng#12171]
### Describe the bug

Toggled Columns are not saved by the state feature. So if you come back and a global-filter is set, which was used with the column, these rows are not found anymore.

### Environment

Angular 11 - 14

### Reproducer

https://stackblitz.com/edit/primeng-tablecoltoggle-demo-fhwqry?file=src/app/app.component.html

### Angular version

14

### PrimeNG version

14

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16

### Browser(s)

Chrome

### Expected behavior

Toggled columns should be also saved in tables state in local or session storage
#9705

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
