### ISSUE TITLE
p-slider: In Range mode, the slider gets stuck if the range min value is equal or superior to the range max value

### ISSUE THREAD

**Issue by btournai** [primefaces/primeng#12175]
### Describe the bug

In the slider in range mode, if you define a max value different of the default value, when you move the start range control of the slider after the end range control , the slider crashes and display its end range to the infinity.

1. 
![image](https://user-images.githubusercontent.com/108737437/177330320-8b286110-b953-4851-b920-05c492e401aa.png)
 
2.
![image](https://user-images.githubusercontent.com/108737437/177330588-53761d59-8f28-46a7-9894-75318edbb155.png)

### Environment

Everywhere

### Reproducer

https://stackblitz.com/edit/github-b4kumc-tcc3a9?file=package.json

### Angular version

13.3.8

### PrimeNG version

13.4.1, 14.2.1

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

14.18.0

### Browser(s)

Chrome 103

### Steps to reproduce the behavior

1. Create a slider in range mode with min = 0, max = 1000 and ngModel = [20, 500]
2. Move the start range control after the end range control

**Comment by Jombasa** [comment]
There is still bug in your newest solution (I've tried out master/main branch). Try to set [min] to number that is not 0 (I had use 18) and move the most right handler to the min position. It will jump.
