### ISSUE TITLE
Button: Label Element not found

### ISSUE THREAD

**Issue by denny99** [primefaces/primeng#12172]
### Describe the bug

AfterViewInit:
<img width="546" alt="image" src="https://user-images.githubusercontent.com/1826849/201033187-ad054e6b-595d-467a-9ad4-6997961ae483.png">

Set label:
<img width="694" alt="image" src="https://user-images.githubusercontent.com/1826849/201033233-212d87f1-d652-4109-bb14-307e45d19c25.png">

As you can see in the code snippets above. If you set the label after the component has been initialized, the label won't exists and therefore the setter crashes.

### Environment

Standard PrimeNG UI. See reproducer

### Reproducer

https://stackblitz.com/edit/github-tmcxm2

### Angular version

14.x.x

### PrimeNG version

14.2.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.1.0

### Browser(s)

Chrome 107

**Comment by mertsincan** [comment]
Good catch, @denny99 ;)
