### ISSUE TITLE
Focus going to background  while navigating using tab-key on IOS(Apple Devices) on any dialog

### ISSUE THREAD

**Issue by symmcy** [primefaces/primeng#12179]
### Describe the bug

When navigating using tab-key on any modal or dialog generated using p-dialog , the  focus goes to background when operating on IOS or any Apple Device , while it works fine for Windows OS

### Environment

IOS

### Reproducer

https://stackblitz.com/edit/primeng-dialog-demo-2f2p1i?file=README.md,src%2Fapp%2Fapp.component.html

### Angular version

13.3.9

### PrimeNG version

13.14.1

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

14.17.1

### Browser(s)

Safari , All browser on any Apple Device

### Steps to reproduce the behavior

In the Below example we have a simple p-dialog , when we open the dialog using show button and then press the tab key , the focus goes to the background on Apple devices . Works fine for Windows OS.

Stackblitz Plunker link - 
https://stackblitz.com/edit/primeng-dialog-demo-2f2p1i?file=README.md,src%2Fapp%2Fapp.component.html

### Expected behavior

The focus should remain on the dialog while pressing the tab key after opening the dialog.

**Comment by mehmetcetin01140** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.
