### ISSUE TITLE
P-Table - Column resize not working as expected

### ISSUE THREAD

**Issue by AvshT** [primefaces/primeng#12183]
### Describe the bug

Table is set with  **resizableColumns="true"** & **columnResizeMode="expand"**
When I resize the first column by let's say 50% the column is not fit into the destination place.

Please see the demo:
https://user-images.githubusercontent.com/29532821/201139298-6911a905-913d-4464-a2e5-a0044e72e312.mp4

(The bug is reproduced in all prime 14.x.x versions)

### Environment

Win 11

### Reproducer

https://stackblitz.com/edit/primeng-tablestate-demo-n6mg6r?file=src%2Fapp%2Fapp.component.html,package.json

### Angular version

14

### PrimeNG version

14.2.1

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

14

### Browser(s)

Chrome Latest

### Expected behavior

Column should resize properly.

**Comment by AvshT** [comment]
Any updates?

**Comment by PranKe01** [comment]
Even worse is that when you have set columnResizeMode to "fit", you can only resize "within the range of that column". So when you try to resize into the area of another column (like in your video) nothing happens Oo

**Comment by efibn** [comment]
@cetincakiroglu 
We are having the same bug/blocker, and it's useless to mentioned that: this is the **most important** component of PrimeNG, as I see it, most complicated and maintained.
So please, fix this **regression**! as this issue really block us all for moving on to the next version of Prime & Angular!

**Comment by mici37000** [comment]
I've also encountered this bug.
It's essental to solve it in order to be able to use table component properly.

**Comment by AvshT** [comment]
@cetincakiroglu prime-react release a Workaround here:
[https://github.com/primefaces/primereact/issues/3970]()

**Comment by PranKe01** [comment]
Hopefully it will also get fixed in primeng.

**Comment by Assassinationrogue** [comment]
@AvshT please check the PR and confirm if this is how it's supposed to work, a video is attached to the above PR.

**Comment by AvshT** [comment]
Hi,
There is any chance that you could enter this fix for V15?

Angular 16 requires Node 16, and unfortunately, our build machine is not compatible with it.

**Comment by biswasSaumyadip** [comment]
@AvshT you mean for angular v15?
