### ISSUE TITLE
[Feature Request] DataTable: Placeholder for column filter input

### ISSUE THREAD

**Issue by dzhavat** [primefaces/primeng#1218]
It would be useful to be able to set a placeholder for the filter input of a column.
Maybe something like this: 

`<p-column field="name" header="Name" [filter]="true" filterPlaceholder="John Doe"></p-column>`

**Comment by cagataycivici** [comment]
@Mrtcndkn, please take over, this is a nice addon.

**Comment by dzhavat** [comment]
You guys are amazing! Thanks a lot!
