### ISSUE TITLE
P-MultiSelect: Virtual scroll and select all with quantities > 2000 items causes window to freeze/hang while selecting rendering the browser unusable. 

### ISSUE THREAD

**Issue by cmccoy98** [primefaces/primeng#12182]
### Describe the bug

If a user does a select all when using virtual scroll in the P-MultiSelect component the browser freezes. This problem doesn't exist in the PrimeReact version of P-MultiSelect. This problem also extends to p-table when p-tableHeaderCheckbox/p-tableCheckbox is used. This issue is related #11775 which was closed because the issue could have been potentially fixed, however it appears to still persist.

PrimeReact example: https://codesandbox.io/s/c6b2f8

### Environment

Stackblitz

### Reproducer

https://stackblitz.com/edit/primeng-multiselect-demo-qidity?file=src%2Fapp%2Fapp.component.ts,package.json

### Angular version

14.2.x

### PrimeNG version

14.2.x

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

latest

### Steps to reproduce the behavior

1. Load a P-MultiSelect with virtualscrolling and 10000 elements.
2. Click selectall checkbox
3. Browser is kill

### Expected behavior

1. Load a P-MultiSelect with virtualscrolling and 10000 elements.
2. Click selectall checkbox
3. Browser is not kill

**Comment by yassine-fy94** [comment]
Hello, I'm facing the same issue with the p-dropdown component. When I try to search using the filter, the dropdown freezes and shows empty lines.

**Comment by cmccoy98** [comment]
Any update on this? I've had a handful of users in my application run into problems related to bulk selection via select-all

**Comment by masalinas** [comment]
I was checking this issue with the version 16.9.1 and the problem persist: multiselect about 8883 and waiting some seconds as you see in the captures

![Captura de pantalla de 2023-12-19 17-57-07](https://github.com/primefaces/primeng/assets/1216181/593981b8-9e56-4379-99a0-457d16aaab91)
![Captura de pantalla de 2023-12-19 17-56-52](https://github.com/primefaces/primeng/assets/1216181/da67631c-198e-4ff0-b44b-82661fff6aa6)

**Comment by mikewongblinx** [comment]
I dont think issue been resolved.

Just head to official demo link and click "select all". And the screen will freeze 
https://stackblitz.com/run?file=src%2FApp.jsx

**Comment by gtteamamxx** [comment]
I'm wondering why this issue has been closed since the problem still appears

**Comment by Zryru** [comment]
@gtteamamxx works if these inputs are used

       [showToggleAll]="true"
        [selectAll]="selectAllBookings()"
        (onSelectAllChange)="onSelectAllChange($event)"
