### ISSUE TITLE
Dropdown: Allow label to be selectable

### ISSUE THREAD

**Issue by davisb10** [primefaces/primeng#12188]
### Describe the feature you would like to see added

I would like to be able to click & drag inside the dropdown to be able to select the text label of the selected value.

### Is your feature request related to a problem?

A majority of our dropdowns contain contact names. Our users would like to be able to quickly select the label to be able to paste it into a different place.

**Comment by davisb10** [comment]
Another possible solution would be to add it as a double-click that shows an auto-hidden (after like 4 or 5 seconds) '&#x2611; Copied to Clipboard' tooltip that is common on different sites.

And then it could get added as a property for [doubleClickToCopyLabel]="true"

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
