### ISSUE TITLE
p-dialog: Dialog scrollbars appear for a moment and immediately disappear on closing child dropdown or multiselect overlay panel

### ISSUE THREAD

**Issue by apolishko** [primefaces/primeng#12199]
### Describe the bug

p-dialog scrollbars appear for a moment and immediately disappear on closing child dropdown or multiselect overlay panel

Steps to reproduce:
1. Create dialog 
<p-dialog [(visible)]="visible"
              [maximizable]="true"
              [closable]="true"
              [closeOnEscape]="false"
              [modal]="true" [style]="{width: '80vw', minWidth: '600px'}" appendTo="body">
2. Place a dropdown with property appendTo="body" in the content of the dialog
3. Open and close the dropdown popup. Dialog scrollbars flash.

### Environment

Windows 11
.NET Core 6.0

### Angular version

14.0.4

### PrimeNG version

14.2.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.4.0

### Browser(s)

Chrome 107.0.5304.107

### Steps to reproduce the behavior

1. Place a dropdown with property appendTo="body" in the content of the dialog
3. Open and close the dropdown popup. Dialog scrollbars flash.

### Expected behavior

p-dialog scrollbars should not appear when closing a child dropdown/multiselect popup

**Comment by mertsincan** [comment]
I think this issue has been already fixed in 14.2.2. https://github.com/primefaces/primeng/issues/12189

We'll release it asap. If the problem persists with it, please reopen this issue. Thanks a lot for your understanding!
Best Regards,
