### ISSUE TITLE
Component: Title

### ISSUE THREAD

**Issue by cloggy45** [primefaces/primeng#12194]
### Describe the bug

Picklist [keepSelection](https://www.primefaces.org/primeng/picklist) does not seem to work, or the documentation around this flag is confusing.

### Environment

Using Angular 14, PrimeNG 14.2.1

### Reproducer

primeng-picklist-demo-9lxr1c

### Angular version

14

### PrimeNG version

14.2.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14

### Browser(s)

Chrome, Microsoft Edge (Latest)

### Steps to reproduce the behavior

Drag one of the elements from the left side to the right. Notice that on the left hand side it is selection is removed and it only exists on the right. 

### Expected behavior

When we drag one of the elements from the source (left) side to the (target) right, the target should maintain the selection that was dragged over, rather than remove it.

**Comment by cloggy45** [comment]
There was some previous work done on this https://github.com/primefaces/primeng/issues/11283

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
