### ISSUE TITLE
P-Table: Edit-Row-Extra-Title : if responsive mode is true then edit row output will show extra headers

### ISSUE THREAD

**Issue by ensgenc** [primefaces/primeng#12192]
### Describe the bug

Hi, 

Headings at the bottom of the output started appearing on the desktop when the response true feature was enabled in the p-table edit row component. In this case, all 13 versions are available.

We are updating version 11.4.10 and we will forward similar errors to lts for a while.

Can you check

### Environment

"dependencies": {
    "@angular/animations": "^12.2.16",
    "@angular/cdk": "12.2.13",
    "@angular/common": "^12.2.16",
    "@angular/compiler": "^12.2.16",
    "@angular/core": "^12.2.16",
    "@angular/fire": "^6.1.4",
    "@angular/forms": "^12.2.16",
    "@angular/google-maps": "12.2.13",
    "@angular/localize": "^12.2.16",
    "@angular/material": "12.2.13",
    "@angular/platform-browser": "^12.2.16",
    "@angular/platform-browser-dynamic": "^12.2.16",
    "@angular/router": "^12.2.16",
    "@angular/service-worker": "^12.2.16",
    "@ngneat/until-destroy": "^8.0.3",
    "@ngx-translate/core": "^12.1.2",
    "axios": "^0.21.1",
    "core-js": "^2.5.4",
    "ngx-cookie-service": "^12.0.3",
    "ngx-countdown": "^12.0.1",
    "ngx-infinite-scroll": "^10.0.1",
    "primeflex": "^2.0.0",
    "primeicons": "^4.1.0",
    "primeng": "12.2.3",
    "prismjs": "^1.9.0"
  }

### Reproducer

https://stackblitz.com/edit/primeng-tableedit-demo-1cvaft?file=src/app/app.component.html

### Angular version

12.2.13

### PrimeNG version

12.2.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.17.1

### Browser(s)

Chrome Version 107.0.5304.87

**Comment by mehmetcetin01140** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.
