### ISSUE TITLE
Apolo Template, Dark or Dim Theme, rowHover = true doesnt not display correctly.

### ISSUE THREAD

**Issue by olegkap** [primefaces/primeng#12198]
### Describe the bug

I am using Apolo template 14.0.3 as it is downloaded from the website.

In Froze Columns example template I enable hover by setting [rowHover]="true".

When table scrolled to the left a little bit and mouse hovers over that row, cell that supposed to be hidden due to frozen column, is visible.

See image:
![image](https://user-images.githubusercontent.com/13485698/201399094-4b76f8fd-7728-4009-b078-3f7a25087edb.png)

Thanks,
Oleg

### Environment

Windows 11
.NET Core 6.0

### Angular version

14.2.10

### PrimeNG version

14.2.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v16.18.0

### Browser(s)

Chrome 107

### Steps to reproduce the behavior

1. Download Apolo template version 14.0.3
2. Add [rowHover]="true" to p-table component in Frozen Columns example
3. Run apolo application and go to table example (http://localhost:4200/#/uikit/table)
4. Scroll Frozen Columns example
5. 5.Scroll table left so column Id is hidden under Name column
6. Hover mouse over the table rows and notice Id is visible

### Expected behavior

When column is scrolled and hidden by frozen column, column should not be visible when mouse hovers over

**Comment by mertsincan** [comment]
Hi,

Does it work without Apollo? If yes, could you please create an issue at https://forum.primefaces.org/viewforum.php?f=81?
