### ISSUE TITLE
Prime LTS v12.2.3 Improve lazy loading and select all implementation on DataTable

### ISSUE THREAD

**Issue by ensgenc** [primefaces/primeng#12191]
### Describe the bug

Hi,

I am using 12.2.3 as primeng lts version and the table all Checkbox Selection error persists. Is there a solution for your LTS version?

The following solution is provided for version 13
#10951 

### Environment

"dependencies": {
    "@angular/animations": "^12.2.16",
    "@angular/cdk": "12.2.13",
    "@angular/common": "^12.2.16",
    "@angular/compiler": "^12.2.16",
    "@angular/core": "^12.2.16",
    "@angular/fire": "^6.1.4",
    "@angular/forms": "^12.2.16",
    "@angular/google-maps": "12.2.13",
    "@angular/localize": "^12.2.16",
    "@angular/material": "12.2.13",
    "@angular/platform-browser": "^12.2.16",
    "@angular/platform-browser-dynamic": "^12.2.16",
    "@angular/router": "^12.2.16",
    "@angular/service-worker": "^12.2.16",
    "@ngneat/until-destroy": "^8.0.3",
    "@ngx-translate/core": "^12.1.2",
    "@sendgrid/mail": "^7.4.5",
    "angular-oauth2-oidc": "^10.0.3",
    "axios": "^0.21.1",
    "core-js": "^2.5.4",
    "firefox": "0.0.1",
    "html2canvas": "^1.0.0-rc.7",
    "inputmask": "^5.0.7",
    "intl": "1.2.5",
    "jspdf": "^2.1.1",
    "ngx-cookie-service": "^12.0.3",
    "ngx-countdown": "^12.0.1",
    "ngx-infinite-scroll": "^10.0.1",
    "powerbi-client": "^2.17.2",
    "primeflex": "^2.0.0",
    "primeicons": "^4.1.0",
    "primeng": "12.2.3",
    "prismjs": "^1.9.0",
    "quill": "^1.3.7",
    "rxjs": "~6.6.3"
  }

### Reproducer

https://stackblitz.com/edit/primeng-tableselection-demo-oapuip?file=src/app/app.component.html

### Angular version

12.2.13

### PrimeNG version

12.2.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.17.1

### Browser(s)

Chrome Version 107.0.5304.87

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
