### ISSUE TITLE
Component: Table

### ISSUE THREAD

**Issue by lbroker** [primefaces/primeng#12201]
### Describe the feature you would like to see added

PrimeNG table component: https://primefaces.org/primeng/table/responsive
is missing functionality "Column Priority" like in Prime JSF components version

### Describe the solution you'd like

When making screen width smaller, some not very important columns should hide:
Examples:
https://www.primefaces.org/showcase/ui/data/datatable/responsive.xhtml?jfwid=fdb5a
https://datatables.net/extensions/responsive/examples/display-control/auto.html

### Additional context

I have reopened this request for feature from previous request:
https://github.com/primefaces/primeng/issues/10375

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
