### ISSUE TITLE
Chips: Content is not displaying using object as input and an item-template

### ISSUE THREAD

**Issue by user4me** [primefaces/primeng#12202]
### Describe the bug

Hello,

By using the p-chips component I've been experienced one issue while using a an array object as input value and an item template. When I write  a new text and press enter, the chip displays without its content. 

### Environment

```
    <p-chips [(ngModel)]="inputObject">
        <ng-template let-item pTemplate="item">
            <img class="p-chips-img" [src]="item.imgUrl">
            <span>{{item.name}}</span>
        </ng-template>
    </p-chips>
```

### Angular version

14.2.0

### PrimeNG version

14.2.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.2.1

### Browser(s)

Chromium 107.0.5304.91

### Expected behavior

The chip should be displayed with its content according to the template

**Comment by cetincakiroglu** [comment]
Hi @user4me,

Could you please share a Stackblitz exampleS by using https://stackblitz.com/github/primefaces/primeng-issue-template
