### ISSUE TITLE
Replace native JS with Renderer2

### ISSUE THREAD

**Issue by chaimite** [primefaces/primeng#12204]
### Describe the feature you would like to see added

Are there plans to replace native JS document object for Renderer2?

Renderer2 is the "angular" way of interacting with the DOM. While looking at the library I can see native JS being used.

### Describe the solution you'd like

Replace native JS document diwth renderer2

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
