### ISSUE TITLE
Toasts with different keys are not stacked

### ISSUE THREAD

**Issue by IliaIdakiev** [primefaces/primeng#12217]
### Describe the bug

In order to be reactive I want to use an array that represents my toasts. This means that whenever a toast gets removed from that array I would expect to be able to remove the toast from the message service. I saw that the only way for removing a toast is by providing an `key` to the `clear` method. All good until multiple toasts are shown, I would expect that those toasts since they are all for the same location on the screen are being stacked even though they are with different keys and they are not. 

[Here is a demo](https://stackblitz.com/edit/angular-ivy-dtrxte?file=src%2Fapp%2Fnotification%2Fnotification.component.html,src%2Fapp%2Fnotification%2Fnotification.component.ts,src%2Fapp%2Fnotification%2Fnotification.component.css)

### Environment

Angular 14

### Reproducer

https://stackblitz.com/edit/angular-ivy-dtrxte?file=src%2Fapp%2Fnotification%2Fnotification.component.html,src%2Fapp%2Fnotification%2Fnotification.component.ts,src%2Fapp%2Fnotification%2Fnotification.component.css

### Angular version

14

### PrimeNG version

13.0.4

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

x

### Steps to reproduce the behavior

1. Enter text inside input.
2. Click on the "Show notification" button to show notification.
3. Quickly enter another text inside the input.
4. Click on the "Show notification" button to show notification.

The two toasts appear over each other.

### Expected behavior

The two toasts should appear under each other since they are for the same location on the screen.

**Comment by mehmetcetin01140** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.
