### ISSUE TITLE
Table header and Columns values are overlapped when frozen columns are resized:

### ISSUE THREAD

**Issue by meghashivaswamy** [primefaces/primeng#12210]
### Describe the bug

Table header and Columns values are overlapped when frozen columns are resized: 

Issue:
https://stackblitz.com/edit/primeng-tablescroll-demo-qa7nvc?file=src%2Fapp%2Fapp.component.html

![Screenshot_Resize](https://user-images.githubusercontent.com/56187710/201638206-8b4d77dd-e5f2-43d4-80a1-ef7a42aae635.png)

### Environment

Angular CLI + PrimeNG

### Angular version

14.1.0

### PrimeNG version

14.0.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.16.0

### Browser(s)

Chrome, Webview2

### Steps to reproduce the behavior

Steps to Reproduce:
1.	Freeze first two columns Name, ID and make them as Resizable columns
2.	Resize(minimize the width) first frozen column and Scroll Horizontally
3.	Observe the Table header and Columns values are overlapped(Country can be seen back of Frozen columns)

**Comment by ThoSap** [comment]
Here you have a up-to-date StackBlitz example with Angular `17.2.2`, NodeJS `v18.18.0`, and PrimeNG `17.11.0`
https://stackblitz.com/edit/wgwshv?file=src%2Fapp%2Fdemo%2Ftable-frozen-columns-demo.html

**Comment by ThoSap** [comment]
See GitHub discussion https://github.com/orgs/primefaces/discussions/1477

**Comment by ThoSap** [comment]
@cetincakiroglu added the duplicated ticket #12411 to milestone **17.Future** 👍🏼

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
