### ISSUE TITLE
Table Sort & VirtualScroll don't work together

### ISSUE THREAD

**Issue by yukie1412** [primefaces/primeng#12215]
### Describe the bug

i forked the [sort demo](https://stackblitz.com/edit/primeng-tablesort-demo?file=README.md) from stablitz & added virtual scroll attributes to the table
then the columns are no longer sortable, **and** row columns are no longer aligned with table headers

![image](https://user-images.githubusercontent.com/2449212/201917575-ebf1eb08-8629-4c48-8464-6de19469de71.png)

### Environment

prod

### Reproducer

https://stackblitz.com/edit/primeng-tablesort-demo-zrctke?file=src%2Fapp%2Fapp.component.html

### Angular version

14.2.10

### PrimeNG version

14.2.1

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

14.17.3

### Browser(s)

edge 107.0, chrome 107.0

### Steps to reproduce the behavior

1. go to https://primeng-tablesort-demo-zrctke.stackblitz.io
2. click on table headers to sort columns

### Expected behavior

rows should reorder based on the sorted column

**Comment by mertsincan** [comment]
Hi @yukie1412,

Your stackblitz demo uses PrimeNg 14.0.2. Could you please try it with the latest PrimeNG version?

**Comment by yukie1412** [comment]
@mertsincan updated the link. the column alignment issue is fixed, though sorting still doesn't work on both edge & chrome

**Comment by stylepatrick** [comment]
Hey, have you already tried to use the datakey property in the <p-table>?

**Comment by mertsincan** [comment]
> .. updated the link. the column alignment issue is fixed, though sorting still doesn't work on both edge & chrome
This is not related to VirtualScroll. You have to make your sort structure with lazy method. Please see;
https://www.primefaces.org/primeng/table/lazy

Also, please see our code;
```
sortSingle() {
        ...

        if (field && order) {
            if (this.restoringSort) {
                this.restoringSort = false;
            }

            if (this.lazy) {
                this.onLazyLoad.emit(this.createLazyLoadMetadata()); // PLEASE SEE THIS LINE
            } else if (this.value) {
                if (this.customSort) {
                    this.sortFunction.emit({
                        data: this.value,
                        mode: this.sortMode,
                        field: field,
                        order: order
                    });
                } else {
                    this.value.sort((data1, data2) => {
                        let value1 = ObjectUtils.resolveFieldData(data1, field);
                        let value2 = ObjectUtils.resolveFieldData(data2, field);
                        let result = null;

                        if (value1 == null && value2 != null) result = -1;
                        else if (value1 != null && value2 == null) result = 1;
                        else if (value1 == null && value2 == null) result = 0;
                        else if (typeof value1 === 'string' && typeof value2 === 'string') result = value1.localeCompare(value2);
                        else result = value1 < value2 ? -1 : value1 > value2 ? 1 : 0;

                        return order * result;
                    });

                    this._value = [...this.value];
                }

                if (this.hasFilter()) {
                    this._filter();
                }
            }

            let sortMeta: SortMeta = {
                field: field,
                order: order
            };

            this.onSort.emit(sortMeta);
            this.tableService.onSort(sortMeta);
        }
    }
```
