### ISSUE TITLE
Component: Table; Store table state in the URL

### ISSUE THREAD

**Issue by Rhobal** [primefaces/primeng#12229]
### Describe the feature you would like to see added

Store table state in the URL

Please add "url" as an option to "stateStorage" on p-table, so state is stored as query parameter in the URL.

This way, links to data in a a filtered table can easily be bookmarked or mailed to other people

### Is your feature request related to a problem?

If I want to send a link to data displayed in a table, I have to send instructions for filtering along. If the table state was reflected in the URL, I could send a link to the filtered data to another person or I could bookmark the link to the data

### Describe the solution you'd like

- support `stateStorage="url"` in `p-table`
- As `stateKey`. name a query parameter to store the filter state in (could default to a standard value)
- On changes of the state, update the URL
- On updates of the state query parameter in the URL, change the table state
- replace the last URL in the history when updating state, do not add to the history

**Comment by juulian98** [comment]
Could be useful to combine storage and url

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
