### ISSUE TITLE
MultiSelect: placeholder renders many times

### ISSUE THREAD

**Issue by ghost** [primefaces/primeng#12220]
### Describe the bug

When translate page with google translate to Spanish, placeholder duplicates when I select the option in chip mode

![image](https://user-images.githubusercontent.com/95452787/201965766-b29d1222-e43f-4b92-9962-ceed50496716.png)

Chip mode:
![image](https://user-images.githubusercontent.com/95452787/201965945-a43209e0-32e6-4035-8a59-964d42071c12.png)

![image](https://user-images.githubusercontent.com/95452787/201965537-a5257083-a2d3-464b-93b1-3a94430bd80b.png)

### Environment

```
{
  "name": "test",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^11.2.14",
    "@angular/common": "~11.2.14",
    "@angular/compiler": "~11.2.14",
    "@angular/core": "~11.2.14",
    "@angular/forms": "~11.2.14",
    "@angular/localize": "~11.2.14",
    "@angular/platform-browser": "~11.2.14",
    "@angular/platform-browser-dynamic": "~11.2.14",
    "@angular/router": "~11.2.14",
    "@fortawesome/angular-fontawesome": "^0.8.2",
    "@fortawesome/fontawesome-svg-core": "^1.2.36",
    "@fortawesome/free-brands-svg-icons": "^5.15.4",
    "@fortawesome/free-solid-svg-icons": "^5.15.4",
    "@ng-bootstrap/ng-bootstrap": "^9.1.3",
    "@popperjs/core": "^2.10.1",
    "angular-file-saver": "^1.1.3",
    "aws-amplify": "^4.3.2",
    "bootstrap": "^5.1.1",
    "file-saver": "^2.0.5",
    "md5": "^2.3.0",
    "primeicons": "^4.1.0",
    "primeng": "^11.0.0",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1102.13",
    "@angular/cli": "~11.2.14",
    "@angular/compiler-cli": "~11.2.14",
    "@types/jasmine": "~3.6.0",
    "@types/md5": "^2.3.2",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "gulp": "^4.0.2",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.5.0",
    "ng-packagr": "^11.0.0",
    "protractor": "~7.0.0",
    "sonarqube-scanner": "^2.8.1",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.1.5"
  }
}
```

### Angular version

14.2.9

### PrimeNG version

11.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.10.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Go to https://www.primefaces.org/primeng-v11-lts/#/multiselect
2. Translate to spanish
3. Select and deselet the options in chip mode
4. Look the placeholder

### Expected behavior

Only one placeholder, that was set by [placeholder]="variable | pipe"

**Comment by cetincakiroglu** [comment]
Hi,

Could not replicate with the latest PrimeNG version (v14.2.1). The problem does not exist, closing the issue.

Thanks for your report!
