### ISSUE TITLE
Table: The column width of the reordered column is overridden by resized column width.

### ISSUE THREAD

**Issue by meghashivaswamy** [primefaces/primeng#12225]
### Describe the bug

The column width of the reordered column is overridden by resized column width.

![PrimeNG14](https://user-images.githubusercontent.com/56187710/202100241-71bff522-e053-4316-aa67-20856200d43d.png)
![PrimeNG13](https://user-images.githubusercontent.com/56187710/202100248-d9efdb8d-ad1e-4455-8f81-4ccadc97a394.png)

### Environment

"primeng": "14.0.2"
https://stackblitz.com/edit/primeng-tablesort-demo-uwph9t?file=src/app/app.component.html

"primeng": "13.0.4"
https://stackblitz.com/edit/primeng-tablereorder-demo-e2utgh?file=src/app/app.component.ts

### Angular version

14.1.0

### PrimeNG version

14.0.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.16.0

### Browser(s)

Chrome, WebView2

### Steps to reproduce the behavior

1. Resize (Minimize the width) the Column “Code” 
2. Drag and Drop the Column “Name” to the resized column 2nd position
3. observe the dropped position column width is still minimized or fixed.

### Expected behavior

The reordered column width should be retained even when it is dropped to a different position. (primeng 13 behavior)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
