### ISSUE TITLE
Multiselect vs Dropdown (Single select) filtering inconsistent please make both do a contains...

### ISSUE THREAD

**Issue by kmcnamee** [primefaces/primeng#1223]
In RC1 you changed the filtering of the prime dropdown to do a contains.   [Use contains for dropdown filter #1175](https://github.com/primefaces/primeng/pull/1175)

 However the multiselect dropdown is not behaving the same way and does a starts with.  Please make them consistent to both do a contains search.  The change on the multselect dropdown is a one line change here:

https://github.com/primefaces/primeng/blob/master/components/multiselect/multiselect.ts#L321

**Comment by cagataycivici** [comment]
Fixed via #1131
