### ISSUE TITLE
Tree Component: Not possible to drag to root

### ISSUE THREAD

**Issue by RolfVeinoeSorensen** [primefaces/primeng#12232]
### Describe the bug

When dragging a node to root of the tree, the droppednode is still the closest node and not like expected undefined or null.
See console output in attached stackblitz.

https://primeng-treedragdrop-demo-wrwvey.stackblitz.io

### Environment

Not env specific

### Reproducer

https://primeng-treedragdrop-demo-wrwvey.stackblitz.io

### Angular version

14.x.x

### PrimeNG version

14.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

x.x.x

### Steps to reproduce the behavior

run example
drag a node to root
read console output

### Expected behavior

droppednode should be undefined or null when dragging a node to root of the tree

**Comment by Caznik** [comment]
I'm having the same issue. There is no solution yet?
