### ISSUE TITLE
Component: dropdown virtual scroll

### ISSUE THREAD

**Issue by ManojKrishnasamy** [primefaces/primeng#12236]
### Describe the bug

In dropdown during scrolling it acts like this
![screenrecord virtualscroll](https://user-images.githubusercontent.com/107387275/202253283-376df098-61bf-44b5-8f1c-b05e9d608277.gif)

### Environment

Chrome

### Angular version

14.0.6

### PrimeNG version

14.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.0.0

**Comment by mertsincan** [comment]
Unfortunately, I couldn't replicate it. Could you please create a stackblitz link for us? Also, could you please try it with the latest PrimeNg version?

**Comment by dkhrunov** [comment]
Same issue

**Comment by dkhrunov** [comment]
Try to update to Angular v15 and Primeng v15.2.0, have same issue
