### ISSUE TITLE
Component: p-table The footer width affects the body

### ISSUE THREAD

**Issue by ensgenc** [primefaces/primeng#12248]
### Describe the bug

The element width in the footer affects the width of the first column in the body.

### Environment

Macos, Chrome

### Reproducer

https://stackblitz.com/edit/primeng-tablesections-demo-cjfxkt?file=src%2Fapp%2Fapp.component.html

### Angular version

12.2.13

### PrimeNG version

12.2.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.17.1

### Browser(s)

Chrome Version 107.0.5304.87

**Comment by mehmetcetin01140** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.
