### ISSUE TITLE
dataView: Create input filterMatchMode to set custom one

### ISSUE THREAD

**Issue by smootyDev** [primefaces/primeng#12245]
In dataView component, I can't set custom  input filterMatchMode as another component, for example, pickList. Always is 'contains'.

dataView.ts

line 386: `filter(filter: string, filterMatchMode: string = 'contains') {`

pickList.ts

line 272:  `@Input() filterMatchMode: string = 'contains';`
line 505 and below:  
filter(data: any[], listType: number) {
        let searchFields = this.filterBy.split(',');

        if (listType === this.SOURCE_LIST) {
            this.visibleOptionsSource = this.filterService.filter(data, searchFields, this.filterValueSource, this.filterMatchMode, this.filterLocale);
            this.onSourceFilter.emit({ query: this.filterValueSource, value: this.visibleOptionsSource });
        } else if (listType === this.TARGET_LIST) {
            this.visibleOptionsTarget = this.filterService.filter(data, searchFields, this.filterValueTarget, this.filterMatchMode, this.filterLocale);
            this.onTargetFilter.emit({ query: this.filterValueTarget, value: this.visibleOptionsTarget });
        }
    }

I would like to set a filterMatchMode input.

### Describe the solution you'd like

Remove filterMatchMode: string = 'contains'  and create   `@Input() filterMatchMode: string = 'contains';` 

dataView.ts

line 386: filter(filter: string, **filterMatchMode: string = 'contains'**) {
to 
line 386: filter(filter: string) {

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
