### ISSUE TITLE
Chart : Main Documentation Example Has Incorrect Options

### ISSUE THREAD

**Issue by jeff-a-andersen** [primefaces/primeng#12251]
### Describe the bug

On the chart main documentation page (https://www.primefaces.org/primeng/chart), the example has an options object that  contains the following:

```
        this.options = {
            title: {
                display: true,
                text: 'My Title',
                fontSize: 16
            },
            legend: {
                position: 'bottom'
            }
        };
```

But it should contain this (note that "title" and "legend" are wrapped in "plugins" in this):

```
    this.options = {
      plugins: {
        title: {
          display: true,
          text: 'My Title',
          fontSize: 16
        },
        legend: {
          position: 'bottom'
        }
      }
    };
```

### Environment

N/A - Any Web Browsers

### Angular version

14

### PrimeNG version

14

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

16.7.0

### Steps to reproduce the behavior

Go to https://www.primefaces.org/primeng/chart and see that the options are incorrect.

**Comment by gucal** [comment]
Hi,
Thanks for information. Showcase updated.
