### ISSUE TITLE
Component: Table (Documentation, PrimeNg v12)

### ISSUE THREAD

**Issue by Hardik-Vibe** [primefaces/primeng#12253]
### Describe the bug

The documentation of Table component (PrimeNg v12) is not up-to-date according to code base.

- In PrimeNg version 11.x.x, Table component was having div which had **p-datatable-scrollable-body** class.
- In primeNg version 12.x.x, Table component got rewritten and as part of that, They have replaced **p-datatable-scrollable-body** class with **p-datatable-wrapper**.

But the documentation is still showing **p-datatable-scrollable-body** class in styling section.

References:

PrimeNg v11

- Docs -> https://www.primefaces.org/primeng-v11-lts/#/table
- Code -> https://github.com/primefaces/primeng/blob/11.4.5/src/app/components/table/table.ts#L2320

PrimeNg v12

- Docs -> https://www.primefaces.org/primeng-v12-lts/#/table
- Code -> https://github.com/primefaces/primeng/blob/v12.2.3/src/app/components/table/table.ts#L103

### Environment

N/A

### Angular version

12.2.16

### PrimeNG version

12.2.3

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

v14.20.0

**Comment by mertsincan** [comment]
Thanks a lot for your report!
