### ISSUE TITLE
Component: Title

### ISSUE THREAD

**Issue by Asnyder0328** [primefaces/primeng#12258]
### Describe the feature you would like to see added

An official PrimeNG extension that is updated for VSCode.

### Is your feature request related to a problem?

I don't believe it is a problem but it would be nice to have.

### Describe the solution you'd like

An official PrimeNG extension, that has support for the latest version of PrimeNG, for VSCode.

### Describe alternatives you have considered

PrimeNG 7 Snippets

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
