### ISSUE TITLE
Component: p-fileUpload icon only problem 

### ISSUE THREAD

**Issue by pantalejmon** [primefaces/primeng#12265]
### Describe the bug

After updating to primeng 14.2.x, the plus icon inside the file upload button displays incorrectly. The icon is not centered and is shifted to the left border.

![obraz](https://user-images.githubusercontent.com/40317260/203095354-c8ab7b89-0d0a-4fc3-aed2-e1373e10ef64.png)
 

### Environment

Both firefox and chromium (tested on brave)

### Angular version

14.2.0

### PrimeNG version

14.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.17.0

### Browser(s)

chromium 107, Firefox 106

### Steps to reproduce the behavior

Problem exists in documentation with all themes 
[Link](https://www.primefaces.org/primeng/fileupload)

### Expected behavior

Icon should be centered inside the button, like in previous versions.

**Comment by cetincakiroglu** [comment]
Hi,

It's fixed with the PrimeNG v15.0.0-rc.1 

Regards
