### ISSUE TITLE
Build the Component documentation on storybook

### ISSUE THREAD

**Issue by juri-sinitson** [primefaces/primeng#12263]
### Describe the feature you would like to see added

I want to play around with inputs supported (e.g. on a Knob, Badge or Dynamic Dialog) and see the result instantly.
The original issue is #10700. I actually reopen that issue as the @yigitfindikli asked me. 

Because I still can't see the possibity to select the optimal combination of inputs on the documentation page in the way like e.g. here:
https://bbc.github.io/psammead/?path=/story/components-bulletin--tv-bulletin

Could you take this feature to the roadmap @yigitfindikli ?

**Comment by cetincakiroglu** [comment]
Hi,

Thanks for reporting and your support!

Documentation rework is in our roadmap and the status is in progress.

We're currently working on updating documentation across all Prime UI Libraries to make them more user-friendly and easy to use.

Regards
