### ISSUE TITLE
Add HTML anchors to the Documentation areas

### ISSUE THREAD

**Issue by juri-sinitson** [primefaces/primeng#12264]
### Describe the feature you would like to see added

I want to be able to give a link to a documentation area to jump in directly to that area without (long) scrolling. Let's just take https://www.primefaces.org/primeng/dynamicdialog as example. I want to jump to the possible properties directly instead of scrolling or Ctrl+F'ing. 

Original issue: #10546, so as @cetincakiroglu asked me, I reopen that issue here.

@cetincakiroglu could you add this feature to the roadmap?

**Comment by cetincakiroglu** [comment]
Hi,

Thanks for reporting and your support! 

Documentation rework is in our roadmap and the status is in progress.

We're currently working on updating documentation across all Prime UI Libraries to make them more user-friendly and easy to use.

Regards

**Comment by cetincakiroglu** [comment]
Hi @juri-sinitson 

We've solved this with the new documentation update, closing the issue
