### ISSUE TITLE
p-calendar initial value not visible with reactive forms

### ISSUE THREAD

**Issue by iguissouma** [primefaces/primeng#1226]
I having an issue displaying the initial value in a calendar.
My code is like below:

`<p-calendar id="startDate" [inline]="false" dateFormat="yy-mm-dd" formControlName="startDate" [(ngModel)]="program.startDate"></p-calendar>`

program.startDate is a date not null (startDate: Wed Nov 09 2016 01:00:00 GMT+0100 (Paris, Madrid))

I have blank value on the calendar like below:

![2016-11-07_19h05_52](https://cloud.githubusercontent.com/assets/9085108/20069552/5abb491e-a51d-11e6-884e-dd74de348d05.png)

When I select another date the date is shown:
![2016-11-07_19h09_38](https://cloud.githubusercontent.com/assets/9085108/20069666/c7eabe16-a51d-11e6-91f1-8d2be79f0aba.png)

I'm using the following version "primeng": "^1.0.0-rc.1" with ultima-ng theme.

Thanks.

**Comment by kcsahoo** [comment]
Please use rc.3 for correct operation

**Comment by tdi83** [comment]
I have the same issue with rc.3. 
 <p-calendar id="loanDate" formControlName="loanDate" dateFormat="dd.mm.yy" ></p-calendar>

loanDate is new Date('2013-06-30')
Value is displayed in DatePicker, but missing in the text field of calendar.

**Comment by iguissouma** [comment]
I updated to the rc3 today, I can confirm I have the same issue.
I deleted prime-ng from node_modules the run npm install
```
npm install
frontend@0.0.0 C:\dev\clients\cf\projects\op\frontend
└── primeng@1.0.0-rc.3
```
Run again my application.
The text field of calendar is still empty.

**Comment by iguissouma** [comment]
I have the following error too:
```
error_handler.js:54 TypeError: date.getFullYear is not a function
    at Calendar.formatDate (http://localhost:4200/main.bundle.js:73646:62)
    at Calendar.updateInputfield (http://localhost:4200/main.bundle.js:73323:43)
    at Calendar.writeValue (http://localhost:4200/main.bundle.js:73586:14)
    at http://localhost:4200/main.bundle.js:9094:27
    at http://localhost:4200/main.bundle.js:22201:65
    at Array.forEach (native)
    at FormControl.setValue (http://localhost:4200/main.bundle.js:22201:28)
    at FormGroupDirective.updateModel (http://localhost:4200/main.bundle.js:14476:14)
    at FormControlName.ngOnChanges (http://localhost:4200/main.bundle.js:31719:32)
    at Wrapper_FormControlName.detectChangesInternal (/ReactiveFormsModule/FormControlName/wrapper.ngfactory.js:44:18)
```


![2016-11-08_10h22_39](https://cloud.githubusercontent.com/assets/9085108/20093704/2213b354-a59e-11e6-9c7b-76da961d426f.png)

**Comment by dshupe** [comment]
We are also having issues with the initial date showing blank in the input field. In our case it happens when we have a form group that contains another form group of controls. We want to render the calendar control in a table like this:

```
<table class="table table-hover table-bordered table-responsive table-sm">
    <tr *ngFor="let subGroup of someForm.controls;">
        <td>
            <p-calendar [formControl]="subGroup.controls.DateExecuted"></p-calendar>
        </td>
    </tr>
</table>
```

The initial date value is not displaying. We cannot use formControlName in this case since we are inside an *ngFor of the subGroup of controls.

**Comment by iguissouma** [comment]
Same behaviour in rc4

**Comment by dshupe** [comment]
Verified that this is not fixed in rc4. Still cannot see initial value in the textbox of the p-calendar, but when the calendar drops down. the correct date is selected.

**Comment by ShankarSumanth** [comment]
Hi Guys,
 I have put together a working sample for this issue. I believe that the initial value is usually initialized in the constructor or the onInit method and my guess is that untill the UI is rendered these initial value is not picked up by angular. My idea was to insert this value in the ngAfterViewInit method so that once the view is initialized by angular and angular starts tracking these values it is easy to update the value. 
Strange but works.

html file
`<form [formGroup]="registerForm">

    <label>Start Date</label>

    <p-calendar [(ngModel)]="value" formControlName="calendar" ></p-calendar>

</form>`

ts file
`export class TestComponent implements AfterViewInit {

    value: Date;

    registerForm: FormGroup;

    constructor(private formBuilder: FormBuilder) {

        this.value = new Date();

        this.registerForm = this.formBuilder.group({
            calendar: ''
        });
        this.registerForm.get('calendar').valueChanges.subscribe(value =>
            console.log(value)
        );
    }

    ngAfterViewInit() {
        this.registerForm.get('calendar').setValue(this.value);
    }

}`

Hope this solution helps you all.

**Comment by iguissouma** [comment]
This issue is fixed in rc5.

**Comment by abdhafid** [comment]
I have the same problem with "primeng": "4.2.1" !

```
<form ....
<p-calendar [(ngModel)]="model.date" name="date"
                        [showIcon]="true" showTime="showTime" hourFormat="24" >
</p-calendar>
```
Thanks.

**Comment by markgoho-EDT** [comment]
Still seeing this in v5

**Comment by milindwmahajan** [comment]
Try converting date to ISO  before using it on the form

**Comment by AmirGilboa** [comment]
Yes! that that did the trick. 2 hours i'm on this. thanks @milindwmahajan . 
converting to ISO solved it.

**Comment by lucho120** [comment]
Tenía el mismo problema, solo tuve que hacer esto:
var dateValue='2023-02-11';
var dateFormat= new Date(dateValue)

con eso ya aparece la fecha en mi p-calendar
<p-calendar [showIcon]="true" formControlName="dateFormat"></p-calendar>

**Comment by enanglaw** [comment]
wrap the date format in a square bracket e.g. dateFormat="yy-mm-dd"  will be [dateFormat]="yy-mm-dd"

**Comment by khaldi-yass** [comment]
The problem lies in the type of selection mode you're using, the range mode only accepts an array of two dates, while the single mode accepts the single date object, setting your selectionMode="single" will fix the problem.
