### ISSUE TITLE
Component: InputNumber - InputNumber is not dirty when value changes - not  work with ReactiveForms

### ISSUE THREAD

**Issue by yhoangaleano** [primefaces/primeng#12268]
### Describe the bug

When working with the p-inputNumber and reactive forms, listening for field value changes does not work. It only executes the change when the field is exited and executes the blur event. I cite the issue that had already been opened and never was given solution, in fact this person left the solution in the following link https://github.com/primefaces/primeng/pull/11093/files in line 850.

#10902 

### Environment

Angular version: 15.0.0

PrimeNG version: 14.2.2

### Reproducer

https://stackblitz.com/edit/primeng-inputnumber-demo-hjxey9?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html

### Angular version

15.0.0

### PrimeNG version

14.2.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16

### Browser(s)

Chrome Version 107.0.5304.68 (Official Build) (64-bit)

### Steps to reproduce the behavior

Type a different value in the primeNg number input -> The form does not become dirty.
However, typing in the normal text input -> The form becomes dirty.

**Comment by yhoangaleano** [comment]
Thanks ♥

**Comment by cetincakiroglu** [comment]
Hi,

Continuation of the issue at https://github.com/primefaces/primeng/issues/12733 and it's fixed.
Closing the issue, thanks for reporting!
