### ISSUE TITLE
primeflex: please add [xs] breakpoint for small screen 

### ISSUE THREAD

**Issue by ahmedabdelhafez** [primefaces/primeng#12272]
### Describe the feature you would like to see added

Hello dears,

please add xs breakpoint for extra small screen.

thanks

**Comment by cetincakiroglu** [comment]
Hi,

The issue is irrelevant with PrimeNG, please open this issue on [PrimeFlex Repo](https://github.com/primefaces/primeflex/issues)
Closing the issue, thanks for reporting!

Regards
