### ISSUE TITLE
p-dropdown: data-automationId for dropdown items

### ISSUE THREAD

**Issue by gulyasfeccferenc** [primefaces/primeng#12279]
### Describe the feature you would like to see added

Add the possibility of an optional `data-automationId` attribute for the selectable children items of the `p-dropdown` component, similar currently `p-menuitem` has.

### Is your feature request related to a problem?

It would be a great help for our test automation team if we would have a built-in method to pass some unique automation id to  each children of a frequently changing `p-dropdown`.

### Describe the solution you'd like

I imagine the solution similar what you have at the `p-menuitem`. You can define a `data-automationId` on the parent (`p-dropdown`) which will add a generated `data-automationId` to the children as well, possibly taken the value of the array displayed in the dropdown into account.
e.g.:
```
<p-dropdown automationId="dyn-lang-selector"></p-dropdown>
```
would compiled in the HTML something similar:
```
<p-dropdown data-automationId="dyn-lang-selector">
  ...
     <p-dropdownitem data-automationId="dyn-lang-selector_EN">
       <li><span>English</span></li>
     </p-dropdownitem>
  ...
     <p-dropdownitem data-automationId="dyn-lang-selector_DE">
       <li><span>Germany</span></li>
     </p-dropdownitem>
  ...
</p-dropdown>
```

### Describe alternatives you have considered

I have a dirty solution basically adding a directive which then try to access the elements by different selectors and apply the `attr.data-automationId` on its own, but it is somewhat a dirty hack and could break if there is any change in the `p-dropdown` component

**Comment by probably-me** [comment]
The `data-automationid` attribute is also missing from `p-contextMenu` items, whereas it is present in `p-menu `items.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
