### ISSUE TITLE
Table: Sticky header not sticky in Chrome 90

### ISSUE THREAD

**Issue by PranKe01** [primefaces/primeng#12287]
### Describe the bug

The sticky header in scrollable tables is getting scrolled out of viewport, when scrolling the table in older Google Chrome versions. In latest Chrome version it works.

![image](https://user-images.githubusercontent.com/13560351/204225403-1a013fbd-ea14-4ecf-b134-75326ac983ce.png)

As a workaround I added "position: sticky; top: 0;" to the th additionally to the thead and then it worked for me - but not sure if it makes issues with resizable/frozen columns.

### Environment

Windows 10

### Reproducer

https://www.primefaces.org/primeng-v14/table/virtualscroll

### Angular version

14.0.4

### PrimeNG version

14.2.2 and 15.0.0

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

14

### Browser(s)

Chrome 90

### Steps to reproduce the behavior

1. Use Google Chome 90 (89 also not working)
2. Go to https://www.primefaces.org/primeng-v14/table/virtualscroll (or https://www.primefaces.org/primeng/table/scroll )
3. Scroll the table and see how sticky header is gone

### Expected behavior

The header should stick to the top in older browser versions, too.

**Comment by cetincakiroglu** [comment]
Hi,

It seems that it works with the latest PrimeNG, couldn't replicate and the related CSS rules are already exist in the demo. The live version and your example work as they should, closing the issue. (Tested with chrome v90.0.4430.93)
