### ISSUE TITLE
p-calendar in range mode does not allow manually typing in same start and end date

### ISSUE THREAD

**Issue by robuandrei** [primefaces/primeng#12286]
### Describe the bug

Using p-calendar in range mode. Need to be able to type in a date range with the same start and end date. This can be selected from the UI picker by clicking the same day twice. However, if a date range of the same day is typed in manually then the input is rejected and the calendar reverts to its previous selection.

### Environment

OS: Windows 11
Browser: Google Chrome
Can be reproduced in stackblitz in the library documentation example, so all other environment information should be accessible there.

### Reproducer

https://stackblitz.com/edit/primeng-calendar-demo-kj1zcc

### Angular version

14.2.8

### PrimeNG version

14.1.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.11.7

### Browser(s)

Chrome 121

### Steps to reproduce the behavior

When the user enters a date range with the same start and end date and after that clicks outside of the p-calendar input, the entered value is rejected.

### Expected behavior

Since a date range with the same start and end date is valid from the UI picker, it should also be valid when typed in manually not only when the range is selected from the picker.

**Comment by Yuliasik** [comment]
The same issue reproduced on ^12.0.1 version of PrimeNG

**Comment by sandrotonon** [comment]
Still not working with version 17.3.2

**Comment by PitamahBhishma-0** [comment]
hey is this solved ?
