### ISSUE TITLE
Input in Overlaypanel won't have focus

### ISSUE THREAD

**Issue by FrankEyk** [primefaces/primeng#12284]
### Describe the bug

When an overlaypanel is shown (via a button) the 'onShow' event should focus the input component in the overlaypanel.

The onShow event does trigger, but the focus call does nothing.

_Note_: There wasn't such unwanted behavior in version 11.0.0

_Alternate solution_: With the help of a delay, the input field will be focused.

### Environment

Windows 10
Angular 13.0.3

### Reproducer

https://stackblitz.com/edit/primeng-overlaypanel-demo-qzyygj?file=src/app/app.component.html

### Angular version

13

### PrimeNG version

13.0.4

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14.2

### Browser(s)

chrome

### Steps to reproduce the behavior

Click on the 'does not work' button, it opens an Overlaypanel with a input component in it, the input is not focused.

### Expected behavior

When the Overlaypanel is shown/toggled, the input component should be focused.

**Comment by scpoole709** [comment]
Add autofocus to the element you want focused. That worked for me.
