### ISSUE TITLE
Tree: Allow custom filter function

### ISSUE THREAD

**Issue by mihben** [primefaces/primeng#12285]
### Describe the feature you would like to see added

I would like to override the basic filter function in order to create custom method for filtering.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
