### ISSUE TITLE
Input mask component : optional character

### ISSUE THREAD

**Issue by realsaraf** [primefaces/primeng#1228]
How can i have characters to be options. 

for e.g i want to allow 0.1 or 1.1 or 11.11 or 11.111 etc

putting mask as 999.999 always wants my value to be in the form 111.111 instead of allowing me to use 11.111 etc

**Comment by cesarrew** [comment]
You can use this component:

https://www.npmjs.com/package/ng2-currency-mask

**Comment by cagataycivici** [comment]
You can use ? where whatever after ? would be optional.

**Comment by dtstsUI** [comment]
@cagataycivici is it possible to make a closed segment of optional characters?

e.g 9?*99*?.9?*99*?.9?*99*?

for a valid ip address (thats because the pattern option is not supported for numeric values.


thanks.

**Comment by flawesomesoft** [comment]
> @cagataycivici is it possible to make a closed segment of optional characters?
> 
> e.g 9?_99_?.9?_99_?.9?_99_?
> 
> in this case - for a valid ip address (that's because the pattern option is not supported for numeric values.)
> 
> thanks.

Unfortunately for IP address the only way seems to be using a regular input field in combination with RegEx as you can see in following example:
[](https://stackblitz.com/edit/github-a94aqp-xcqam8?file=src/app/app.module.ts)
