### ISSUE TITLE
TreeTable: resizing columns not working (properly) when a variable column width is set and [scrollable]="false"

### ISSUE THREAD

**Issue by Tortenschachtel** [primefaces/primeng#12290]
### Describe the bug

Assume there is a TreeTable that has columns with a variable width and the properties _[scrollable]="false"_ and  _[resizableColumns]="true"_
If _columnResizeMode="fit"_ (either by setting it explicitly or when using the default value for the parameter) it is not possible to change the width of the columns at all (even though the cursor indicates something to be happening).
If _columnResizeMode="expand"_ changing the size of one column will adjust the size of the whole TreeTable, seemingly by whatever delta the column was supposed to change, then adjust the size of _all_ columns (Potentially proportionally, but i am not certain about that. I believe i have seen other columns shrink when i increased the size of one.)

Note: This behaviour was first observed in PrimeNG 11.4.5, but i can reproduce it in 15.0.0 as well. The StackBlitz version is 14.0.2 because when attempting to use 15.0.0 i got an error that this version could not be found.

Also note: This problem only occurs if the columns have a preset width, either trough the column itself (`<col *ngFor="let col of columns" [ngStyle]="{'width': col.width}">`) or by setting the width on the th-elements (`<th *ngFor="let col of columns" ttResizableColumn [style.width]="col.width">`)

### Environment

Local environment:
node --version -> v14.20.1
npm --version -> 6.14.17
Browser: Vivaldi 5.5.2805.48 (Stable channel) (64-Bit)
Windows 10 Version 21H1 (Build 19043.2251)

PrimeNG and Angular version in application, where the error was first noticed:
PrimeNG: 11.4.5
Angular: 11.2.14

PrimeNG and Angular version in Showcase, where i could reproduce it (locally):
PrimeNG: 15.0.0-SNAPSHOT
Angular: 14.0.7

PrimeNG and Angular version in StackBlitz, according to Stack Blitz:
PrimeNG: 14.0.2
Angular: 14.0.7

### Reproducer

https://stackblitz.com/edit/github-unn4ct-2epfmr?file=src%2Fapp%2Fapp.component.html

### Angular version

14.0.7

### PrimeNG version

14.0.2

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

14.20.1

### Steps to reproduce the behavior

In the provided StackBlitz link try to resize the columns of either table. The first table will not actually resize the columns. The second will resize all columns instead of just the selected one.

### Expected behavior

A column should be resized exactly as input by the user. In "extend" mode other columns should not resize at all.

**Comment by cetincakiroglu** [comment]
Hi,

It's not a bug it's by design, treeTable has two column resize modes "fit" and "expand". Fit is the default one and the overall table width does not change when a column is resized. In "expand" mode, table width also changes along with the column width.

**Comment by Tortenschachtel** [comment]
> Hi,
> 
> It's not a bug it's by design, treeTable has two column resize modes "fit" and "expand". Fit is the default one and the overall table width does not change when a column is resized. In "expand" mode, table width also changes along with the column width. It's not related with [scrollable]="false"

I am aware of the two modes, however under the circumstances described above resizing columns either does not work at all (mode "fit") or it resizes all columns at once (mode "expand"). Please have a look at the stackblitz example provided in the original post.
