### ISSUE TITLE
Dropdown with no options cause exception on keydown

### ISSUE THREAD

**Issue by KonbOgonb** [primefaces/primeng#1229]
Steps to reproduce:
1) Add dropdown with no options. (Why not? This is possible when we dynamically receive drop down from db…)
2) Focus it.
3) "Tab" to next control
4) Get exception

Issue is in the first line of onKeydown(event), it tries to get value of selectedoption, which is null.

**Comment by cagataycivici** [comment]
What is your PrimeNG version?

**Comment by KonbOgonb** [comment]
I was able to reproduce it with "1.0.0-rc.3"

**Comment by cagataycivici** [comment]
Replicated
