### ISSUE TITLE
Component: Table , Rowgrouping with subheader does not work with paging

### ISSUE THREAD

**Issue by pakoc100** [primefaces/primeng#12309]
### Describe the bug

I took the basic example from https://www.primefaces.org/primeng/table/rowgroup , the section with rowGroupMode="subheader" . Then i enabled paging . The subheaders/contents are not correct, starting at page 2 and the following pages. (see stackblitz example)

### Environment

Stackblitz

### Reproducer

https://stackblitz.com/edit/primeng-tablerowgroup-demo-fu4x8q?file=README.md

### Angular version

15.0.1

### PrimeNG version

14.2.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.15.1

### Browser(s)

Chrome latest

### Steps to reproduce the behavior

1. Expand Group on Page 1 => fine
2. Go To Page 2 
3. Expand Group at page 2 => bug

### Expected behavior

The rowgrouping / expanding / collapsing works on all pages as it does on page 1.

**Comment by mpacon** [comment]
We also suffer from this problem. I can also reproduce it with 15 RC1.

**Comment by cetincakiroglu** [comment]
Hi,

Added it to the milestone. Thanks for your report!
