### ISSUE TITLE
Component: p-inputnumber with currency - double my number when we write inside (BUG IS ON YOUR WEBSITE TOO)

### ISSUE THREAD

**Issue by Loqualist** [primefaces/primeng#12308]
### Describe the bug

Hello, when I double click on the p-inputnumber (with currency), and after I write a number, it write it 2 times.

Example : 
1) I double click on the p-inputnumber 
2) I write a number
3) The number is doubling : I write 2 it writes 22. I write 33 it writes 3333. You have a video of your page http://primefaces.org/primeng/inputnumber with the bug on the p-inputnumber with  currency inside.

https://user-images.githubusercontent.com/90766823/204748217-cd0b4165-bbdb-44d6-9481-52f1d6efd543.mov

### Environment

Angular App that uses primeng p-inputnumber to write prices.

### Angular version

15.0.1

### PrimeNG version

14.2.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

<= 16.16.0

### Steps to reproduce the behavior

1) I double click on the p-inputnumber 
2) I write a number
3) The number is doubling : I write 2 it writes 22. I write 33 it writes 3333. You have a video of your page http://primefaces.org/primeng/inputnumber with the bug on the p-inputnumber with  currency inside.

https://user-images.githubusercontent.com/90766823/204748672-9a6ef5c0-c21e-4da3-9814-0222756113d1.mov

### Expected behavior

If I write 1 in the p-inputnumber with currency, I need that the result is 1, not 11. Every time I have to delete my number to rewrite it properly.

**Comment by KevinHetzelGFL** [comment]
It happens on all inputnumber elements with suffix.

**Comment by lala81996** [comment]
& I noticed it happening only on "live"-sites, meaning  on _localhost_ or similar like Stackblitz the bug doesn't occur.

**Comment by KevinHetzelGFL** [comment]
The occurs from version 14.2.0, it is working in previous versions. I think something in this changes is wrong:

- InputNumber | Support highlight on focus property https://github.com/primefaces/primeng/issues/12077
- inputNumber | minFractionDigits fails if set to "0" when using with a suffix https://github.com/primefaces/primeng/issues/11902
- InputNumber | Pass formattedValue to input event https://github.com/primefaces/primeng/issues/12070

Also the error occurs only if the suffix is longer than 1 character

@Loqualist downgrading to 14.1.2 will fix the issue.

**Comment by nicholasfoden** [comment]
Interestingly the issue also only occurs when typing between the number and the suffix.

This issue is caused by [line 976](https://github.com/primefaces/primeng/pull/11991/commits/f7fe54aaff903e817b4aae2112bdfd399dd90d3b#) Removing this code block stops the double typing of numbers issue.

It however introduces other problems. Perhaps this commit needs removing until a solution which solves both issues is found.

**Comment by Loqualist** [comment]
Indeed the bug is not present in version 14.1.2, but appears on 14.2.2 and 15.0.0

**Comment by ThoSap** [comment]
I experience the same issue with PrimeNG `v14.2.3`
```html
<p-inputNumber class="col" formControlName="qntyPlanned"
               [showButtons]="true" [min]="1" mode="decimal" [suffix]="'global.qntySuffix' | translate" [locale]="localeId">
</p-inputNumber>
```

**Comment by paulstelzer** [comment]
@cetincakiroglu You introduced this bug. Can you please fix this issue?

**Comment by cetincakiroglu** [comment]
> @cetincakiroglu You introduced this bug. Can you please fix this issue?

Added into milestone

**Comment by maganap** [comment]
I can confirm this seems to happen to any `p-inputNumber` using a `suffix` after the thousand separator is shown.
Angular 15, primeng@15.2.0

**Comment by cetincakiroglu** [comment]
Is this still exist on v15.4.1, couldn't replicate with the latest version?

**Comment by KevinHetzelGFL** [comment]
It is working in  v15.4.1

**Comment by cetincakiroglu** [comment]
> It is working in v15.4.1

So the issue does not exist anymore, right? I've tried so many things but couldn't replicate.

**Comment by KevinHetzelGFL** [comment]
> > It is working in v15.4.1
> 
> So the issue does not exist anymore, right? I've tried so many things but couldn't replicate.

right

**Comment by paulstelzer** [comment]
The bug mentioned here is fixed, but keyboard navigation is still not working because the cursor is behind the suffix. i opened another ticket, so this can closed here https://github.com/primefaces/primeng/issues/12969
