### ISSUE TITLE
p-scrollPanel - scrollToBottom()

### ISSUE THREAD

**Issue by psarno** [primefaces/primeng#12315]
### Describe the feature you would like to see added

We are using the `p-scrollPanel` as part of a chat interface.   The newest messages appear at the bottom.

When the component loads, we would like it to jump to the bottom of the scroll area, so that the last message is fully in view.

There is currently a `scrollTop` method that takes a number.  We have been working around this by giving it an arbitrarily high number to ensure that it scrolls to a position that is essentially the bottom, although this is not guaranteed to work due to the length of content in the scrollPanel.

### Is your feature request related to a problem?

Yes, there is no way for the `p-scrollPanel` to scroll itself to the bottom via a method call.

### Describe the solution you'd like

Expose a `scrollToBottom()` method, similar to `scrollTop` but that would scroll so that all content is in view, to the bottom of the panel.

### Describe alternatives you have considered

We are calling `scrollTop` with an arbitrarily high "magic number" (1000000) to force it to scroll to the bottom.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).

**Comment by AlbaSS18** [comment]
Hi,

My team is also interested in this improvement. 

Thanks
