### ISSUE TITLE
DynamicDialog need to steal focus

### ISSUE THREAD

**Issue by Foprta** [primefaces/primeng#12319]
### Describe the bug

When you open DynamicDialog with button, focus remains on the button, so you can keep presing "Enter" to spam new modals.

### Environment

MacOS 13.0.1, MacBook Pro 2021 Late
Brave Browser 1.45.131

### Reproducer

https://www.primefaces.org/primeng/dynamicdialog

### Angular version

15

### PrimeNG version

15

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16

### Browser(s)

Brave 1.45.131

### Steps to reproduce the behavior

1. Go to https://www.primefaces.org/primeng/dynamicdialog
2. Press "Show" button (it will open dialog)
3. Press "Enter" on keyboard (it will open dialog again)

### Expected behavior

No modals opened on "Enter" press.

**Comment by cetincakiroglu** [comment]
Hi,

Good catch, thanks for reporting the issue!

**Comment by mserege** [comment]
Hi,

This change breaks focus on first element with autofocus in dynamic dialog.

Would it be possible to get this fix without loosing autofocus ?

Thanks
