### ISSUE TITLE
Material Indigo Dark theme incontinent style

### ISSUE THREAD

**Issue by davidsarkany** [primefaces/primeng#12314]
### Describe the bug

Hello!

I use Material Indigo Dark theme and Tree and Listbox components with filter functions.

These use different bolder styles:
Tree: border: 1px solid rgba(255, 255, 255, 0.12);
Listbox: border: 1px solid rgba(255, 255, 255, 0.3);

Another thing is that the list box has a border under the search box, but the tree view doesn't.

### Environment

Theme: Material Indigo Dark
https://primefaces.org/primeng/tree/filter
https://primefaces.org/primeng/listbox

### Angular version

14.2.0

### PrimeNG version

14.2.2

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

16.14.2

### Steps to reproduce the behavior

Use Material Indigo Dark theme and try these components with filter.
https://primefaces.org/primeng/tree/filter
https://primefaces.org/primeng/listbox

**Comment by mehmetcetin01140** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.
