### ISSUE TITLE
The Modal stick with the mouse cursor on IE

### ISSUE THREAD

**Issue by CHOUAIAR** [primefaces/primeng#1232]
I'm using IE11 and when I move the modal, in some cases; I think when the cursor get out of the header of the modal it stick. Do you have any idea about this?

Thanks in advance.

**Comment by cagataycivici** [comment]
Please provide steps to replicate as we are unable to do so.

**Comment by CHOUAIAR** [comment]
Actually, you need just to move the modal in different direction especially when you move it vertically. the moment the cursor go out of the hearder it stick and follow the cursor everywhere.

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/VZbdZfQ7SuTV87tTkbYR
