### ISSUE TITLE
Button: Ripple directive not working in new Angular/PrimeNG version 14

### ISSUE THREAD

**Issue by mshnajar** [primefaces/primeng#12325]
### Describe the bug

The pRipple directive which worked in are latest version (11) on buttons now doesn't have any visual effect in the new version 14.
No changes in code: this.primengConfig.ripple = true; added in app.component & RippleModule added in app.module

### Environment

Angular 14, PrimeNG 14, Harmony Template Theme

### Angular version

14.2.6

### PrimeNG version

14.1.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.13.2

### Browser(s)

Chrome, Opera

**Comment by seymanurgullu** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
Also, if you have a question about the template, please post it in the forum.
