### ISSUE TITLE
Table | allow to drop colresizer on another column

### ISSUE THREAD

**Issue by cetincakiroglu** [primefaces/primeng#12320]
Continuation of: [Table: Resize column not working correct in fit mode](https://github.com/primefaces/primeng/issues/12289)

**Comment by PranKe01** [comment]
@cetincakiroglu Why is this closed? In PrimeNG v16 it is still not possible to resize the columns, by dragging the slider over another column.

**Comment by PranKe01** [comment]
@cetincakiroglu Dropping the resizer on another cloumn still does not work in v17.3! Why is this closed?
