### ISSUE TITLE
dropdown: ngModel cannot work if set editable to true (default item cannot be selected)

### ISSUE THREAD

**Issue by kingemma** [primefaces/primeng#12328]
### Describe the bug

Hello PrimeNg team,

I used PrimeNg  version is 13.4.1.

I found an issue that the default selected option cannot work when set editable=true in dropdown component. 

See below code demo, the selectedTicklerType ("Item 3") cannot be selected as default value after I set  **[editable]="true"** .

If I removed  [editable]="true" , then the "Item 3" can be selected as default item well.

`     <p-dropdown
            id="ticklertype"
            [filter]="true" filterBy="name"
            optionLabel="name" optionValue="id" 
            placeholder="Select covenant type"
            filterPlaceholder="Search"
            [editable]="true" 
            [showClear]="true"
            [options]="ticklerTypes" 
            [(ngModel)]="selectedTicklerType"
            
        >
        </p-dropdown>`

`    ngOnInit() {
        let newItem = { id: 0, name: 'Item 1' };
        let newItem2 = { id: 1, name: 'Item 2' };
        let newItem3 = { id: 2, name: 'Item 3' };
        let newItem4 = { id: 3, name: 'Item 4' };
        let tmpItems: any[] = [];
        tmpItems.push(newItem);
        tmpItems.push(newItem2);
        tmpItems.push(newItem3);
        tmpItems.push(newItem4);
        this.ticklerTypes = tmpItems;
        this.selectedTicklerType = Enumerable.from(this.ticklerTypes).firstOrDefault(x => x.id === 2);
    }`

### Environment

Windows 10 x64

### Angular version

13

### PrimeNG version

13.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.18.1

**Comment by mehmetcetin01140** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.
