### ISSUE TITLE
pDraggableDisabled is not enabling dragging on conditional cases

### ISSUE THREAD

**Issue by chandru-kumar** [primefaces/primeng#12326]
I have a table where I need to drag a row after selection of the row. I'm setting pDraggableDisabled upon selection or non-selection rows. Initially pDraggableDisabled is set to true and If I select the row, the ng-reflect-p-draggable-disabled="false" does get set to false. But the row is still not draggable.

Note: If pDraggableDisabled is not added, dragging is working for all the rows.

`<ng-template #body let-row let-rowIndex="rowIndex"><tr [selectableRowIndex]="rowIndex" [selectableRow]="row" pDraggableDisabled={{!isDraggableRow(row)}} pDraggable="changeActivities" (onDragStart)="dragStart()" (onDragEnd)="dragEnd()">`

Initially on table load:
`<tr _ngcontent-mkb-c263="" pdraggable="changeActivities" class="p-element p-selectable-row ng-star-inserted" ng-reflect-scope="changeActivities" ng-reflect-p-draggable-disabled="true" ng-reflect-selectable-row-index="1" ng-reflect-selectable-row="[object Object]" tabindex="0"></tr>`

After selection of row:
`<tr _ngcontent-mkb-c263="" pdraggable="changeActivities" class="p-element p-selectable-row ng-star-inserted p-highlight" ng-reflect-scope="changeActivities" ng-reflect-p-draggable-disabled="false" ng-reflect-selectable-row-index="1" ng-reflect-selectable-row="[object Object]" tabindex="0"></tr>`

Can anyone pls help on this? Am i doing it somewhere wrong or it's issue with primeng-drag-drop lib itself?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
