### ISSUE TITLE
Cannot read properties of undefined (reading 'toLocaleLowerCase')

### ISSUE THREAD

**Issue by mkumar92** [primefaces/primeng#12337]
### Describe the bug

showing this when trying to switch application thourgh keboard ( alt+tab ) and its occuring everytime when trying to switch. 

### Environment

dev/staging

### Angular version

14.0.7

### PrimeNG version

14.2.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.15.0

### Browser(s)

chorme ( 106.0.5249.119 )

### Steps to reproduce the behavior

switch application thourgh keboard ( alt+tab )

![error-screenshot](https://user-images.githubusercontent.com/50980506/205864459-bd234083-33df-4800-8ae3-7d9810c89849.png)

**Comment by bjansen** [comment]
I'm experiencing the same issue. It looks like a duplicate of https://github.com/primefaces/primeng/issues/9870, which has unfortunately been closed because there was no response from the maintainers of PrimeNG. I can confirm that the problem is still present.

**Comment by cetincakiroglu** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.
