### ISSUE TITLE
InputNumber: Paste behavior dependent on current input values

### ISSUE THREAD

**Issue by SMayer135** [primefaces/primeng#12334]
### Describe the bug

InputNumber Integer Only (default) behavior allows pasting of decimals when the input is empty

### Environment

Reproducible on demo

### Angular version

14.2.4

### PrimeNG version

14.2.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.17.3

### Steps to reproduce the behavior

1. Go to http://primefaces.org/primeng/inputnumber
2. Copy 123.123 to clipboard
3. Highlight "Integer Only" example
4. Paste
5. Notice paste does not occur
6. Clear out Integer Only example input field
7. Paste
8. Notice that 123.123 (including decimal) is now present in what is supposed to be an Integer Only input

### Expected behavior

Integer Only inputs (default behavior) should not accept decimals

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
