### ISSUE TITLE
p-table: Unable to make header sticky anymore

### ISSUE THREAD

**Issue by kishor-p** [primefaces/primeng#12333]
### Describe the bug

According the documentation: https://www.primefaces.org/primeng/table/sticky

Changing a simple CSS should make the header sticky.

Ever since update 14.2.2 version and above. This does not work any more.

### Environment

Using Primeng 14.2.2
also tried with: 15.0.0.rc.1

### Reproducer

https://stackblitz.com/edit/github-qdcank

### Angular version

14.0.0

### PrimeNG version

14.2.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.1

### Browser(s)

Chrome

### Expected behavior

Table Header should stick after scroll.

**Comment by kishor-p** [comment]
> Have you tried this answer?
> 
> [#12287 (comment)](https://github.com/primefaces/primeng/issues/12287#issuecomment-1328965165)

Yes i have and it works.

Either PrimeNG showcase should update this info or next version of PrieNG should have this fix. Hence i am raising this issue.

**Comment by cetincakiroglu** [comment]
Hi,

It seems that it works with the latest PrimeNG, couldn't replicate and the related CSS rules already exist in the demo. The live version and your example work as they should, closing the issue. (Tested with all browsers and chrome v90.0.4430.93)
