### ISSUE TITLE
P-TreeTable: Column width in percentage

### ISSUE THREAD

**Issue by PranKe01** [primefaces/primeng#12342]
### Describe the bug

When using colspan in the p-treetable, the width of each column is set in pixel isntead of percentage (for example when resizing a column). That way, whenever the width of the table changes, the layout breaks, because the sum of the width of the columns may be greater than the new table width.

### Environment

Windows.

### Reproducer

https://www.primefaces.org/primeng-v14/treetable/colresize

### Angular version

14.0.4

### PrimeNG version

14.2.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14

### Steps to reproduce the behavior

1. Go to https://www.primefaces.org/primeng-v14/treetable/colresize
2. Make the columns of the "fit mode table" wider (you will notice a scrollbar on the bottom, which is already a bad thing)
3. Make the browser window smaller (you will notice an even bigger scrollbar)

### Expected behavior

In fit mode, there should be no horizontal scrollbar, when changing column sizes.

**Comment by PranKe01** [comment]
@mertsincan Any update here? :)

**Comment by PranKe01** [comment]
@mertsincan In PrimeNG v16.0.0, the column resize does not seem to work (at least in the demo): https://primeng.org/treetable#columnresize

When you try to resize the column, nothing happens and the slider keeps active :|

**Comment by PranKe01** [comment]
@cetincakiroglu Column resizing does not work. As this is a quiet popular feature, I am wondering why nobody is fixing it?

**Comment by VolodymyrKornetskyi** [comment]
I also have issues with columns sizing.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
