### ISSUE TITLE
Component: p-columnFilter has effect on p-table 'first' property

### ISSUE THREAD

**Issue by doublemcz** [primefaces/primeng#12344]
### Describe the bug

I am implementing `p-table` with restoration of filters from url query. Filters and paging are bind directly from the wrapper component properties in template to the `p-table`. You can achieve the same error result when using state. When using component `p-columnFilter` in column headers it has effect on property `first` in the `p-table`. It literally clears any value from it and sets the property `first` to zero. In example, in documentation, it works because there is not `p-columnFilter` component and `first` is persitent. The issue is that the `first` property in the `p-table` must persist otherwise user is not taken to the correct spot.

```
<p-table
    [stateKey]="'state-key'"
    [stateStorage]="'local'"
    [rows]="10"
    [loading]="loading"
    [paginator]="true"
    [totalRecords]="records.length"
    [rowsPerPageOptions]="[10, 20, 50]"
    [showCurrentPageReport]="true"
    [value]="records">
    <ng-template pTemplate="header">
      <tr>
        <th translate pSortableColumn="id" [style.width.px]="120">
          ID
          <p-sortIcon field="id"></p-sortIcon>
        </th>
        <th translate pSortableColumn="name">
          Name
          <p-sortIcon field="name"></p-sortIcon>
        </th>
      </tr>
      <tr>
        <th>
          <p-columnFilter type="text" field="id" matchMode="equals" [showClearButton]="false"></p-columnFilter>
        </th>
        <th>
          <p-columnFilter type="text" field="name" matchMode="contains" [showClearButton]="false"></p-columnFilter>
        </th>
      </tr>
    </ng-template>
    <ng-template pTemplate="body" let-vendor>
      <tr>
        <td>{{ vendor.id }}</td>
        <td>{{ vendor.name }}</td>
      </tr>
    </ng-template>
  </p-table>
```

### Environment

Curentlly in development

### Angular version

14.1.1

### PrimeNG version

14.2.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.3.1

### Browser(s)

Chrome 106.0.5249.62

**Comment by doublemcz** [comment]
Any update on this?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
