### ISSUE TITLE
Component: RadioButton throw exception when not use formControlName and name not match

### ISSUE THREAD

**Issue by Soriya-Chhai** [primefaces/primeng#12340]
### Describe the bug

When we use RadioButton in reactive form, it require to put name and formControlName match. But in case, we want to use it in FormArray, it needs to difference name to make RadioButton Group difference.

### Environment

Development

### Angular version

14.2.2

### PrimeNG version

14.2.2

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

14.17.4

### Browser(s)

Chrome

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
