### ISSUE TITLE
Change the firstDay automatically

### ISSUE THREAD

**Issue by CHOUAIAR** [primefaces/primeng#1234]
I know that using jQuery we can do it but using Angular 2 is there a way to change the firstDay dynamically after the rendering of the schedule?

**Comment by cagataycivici** [comment]
Please use forum for questions;

http://forum.primefaces.org/viewforum.php?f=35&sid=276c5ae7570d9b3751325405c6fc5510

It can be done by editing the firstDay propert of the bound locale object.
