### ISSUE TITLE
Prime NG TabView Title Partial Display

### ISSUE THREAD

**Issue by mehemanthkumar** [primefaces/primeng#12343]
### Describe the bug

When using prime ng scrollable feature list items are shown in horizontal . items are get hidden I.e, half content only shown.
For Refrence pasting screen shot below.

![image](https://user-images.githubusercontent.com/33151425/205910448-1eada05b-3217-4a40-b647-c3c2d2a44c43.png)

![image](https://user-images.githubusercontent.com/33151425/205910571-ed977217-b5e1-447a-b0ab-e6c63a572d8e.png)
![image](https://user-images.githubusercontent.com/33151425/205910685-08468dbd-54e6-4a19-9bb3-aeb385dfcdf6.png)

In above screen shot tab no 22 was shown partially . 

### Environment

Both Local and in server

### Angular version

14

### PrimeNG version

14.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.6.4

### Browser(s)

Chrome , Firefox latest

### Steps to reproduce the behavior

https://primefaces.org/primeng/tabview -> Scrollable part

### Expected behavior

Full Tab title should be shown.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
