### ISSUE TITLE
PrimeNG Table : Paginator state is not refreshed on value input change

### ISSUE THREAD

**Issue by Simon-GHI** [primefaces/primeng#12350]
### Describe the bug

There is an issue with primeNG table with paginator. The paginator state does not get refresh when the value changes. 

I reproduce the bug on stackblitz: https://stackblitz.com/edit/primeng-tabledoc-demo-vdi4uw?file=src/app/app.component.ts

Regards,
Simon

### Environment

Fork of PrimeNG documentation table stackblitz.

Angular / PrimeNG : v13

### Reproducer

https://stackblitz.com/edit/primeng-tabledoc-demo-vdi4uw?file=src/app/app.component.ts

### Angular version

13.0.3

### PrimeNG version

13.0.4

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

0

### Steps to reproduce the behavior

- Go on last page
- Hit filter button
=> No data appears
=> The paginator state get desynchronized. It shows only one page, the buttons are not disabled, the current page is not set to page 1.

### Expected behavior

The paginator state refresh. 
- The current page is set to: 
          - Selected page if there is data available for that page.
          - Last page with data available if current selected page > remaining number of page
          - First page
- The "next" and "previous" button became disabled (based on number of pages/current page)

**Comment by mehmetcetin01140** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.
