### ISSUE TITLE
Autocomplete clears selected item on using tab

### ISSUE THREAD

**Issue by grmeier** [primefaces/primeng#12358]
### Describe the bug

After migrating to Angular 14 and PrimeNG 14 we saw a bug that mkes the selected item in an autocomplete disappear when using the tab- key to go to the next item. This only happens when you use the up and down arrow keys and enter to select the option. Before the update we were using PrimeNG 9 which didn't have this problem.

From what I found, this bug already existed in the past and was supposed to be solved with PrimeNG 11. Issues I found regarding this problem:
https://github.com/primefaces/primeng/issues/8740
https://github.com/primefaces/primeng/issues/9378

### Environment

Spring Boot microservice using Angular 14.2.10 with PrimeNG 14.2.2.

### Angular version

14.2.10

### PrimeNG version

14.2.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.13.2

### Browser(s)

Microsoft Edge version 108.0.1462.42, Google Chrome version 107.0.5304.107

### Steps to reproduce the behavior

1. Go to the input field using the autocomplete component
2. Start entering characters till you find a matching option
3. select the option using the arrow up and down keys and press enter to confirm your selection
4. press the tab- key to jump to the next field

### Expected behavior

The selected value in autocomplete should still be selected after using the tab- key and the field is not empty.

**Comment by mehmetcetin01140** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.
