### ISSUE TITLE
Primeng Dropdown value doesn't show when made editable dynamically

### ISSUE THREAD

**Issue by sudrack** [primefaces/primeng#12356]
### Describe the bug

Consider the following scenario:
There's a p-dropdown, which is not editable initially. You set some value by choosing one of the dropdown options.
Then you make the p-dropdown editable dynamically (in this case there's a radio button that toggles between Editable and Fixed).

Now although the selected value isn't changed, you no longer see the value that was set earlier. Rather you see the placeholder.
This misleads the user into believing that the dropdown value has been reset.

PS: Since this is a behavioral issue, I'm not sure how to write a unit test case to catch this bug. Since the selected value is not being reset, its just that the value is not seen in the dropdown when it is made editable dynamically.

### Environment

Angular 13 dev environment

### Reproducer

https://stackblitz.com/edit/primeng-dropdown-demo-9pswaa?file=src/app/app.component.html

### Angular version

13.0.3

### PrimeNG version

13.0.4

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.1

### Steps to reproduce the behavior

1. Initially the p-dropdown is not editable. Select an option. Observe that value being set on the dropdown, replacing the placeholder. You can see below the message "The dropdown value selected is: <Your-selection>"
2. Now switch the radio button above to Editable, and observe that the message below hasn't changed, but the value on the dropdown appears to have reset, and you can see the placeholder again.
3. On switching the radio button back to Fixed, you can now see the initially set value on the dropdown again.

### Expected behavior

Making the dropdown editable dynamically shouldn't affect the appearance of the dropdown. If the value is unchanged, then it should still be seen on the dropdown.

**Comment by ShubhamSudame** [comment]
Here's something that I've observed:

When p-dropdown is not editable (editable=false), then the HTML structure of p-dropdown is as:
p-dropdown
- div
  - div
  - span
  - div

But when p-dropdown is editable (editable=true), then the span inside the structure is replaced by input element:
p-dropdown
-div
  - div
  - input
  - div

And a possible fix would be to put value attribute to the input element, like [value]="this.optionLabel"

**Comment by ShubhamSudame** [comment]
![image](https://user-images.githubusercontent.com/24990178/206906696-66a192fb-0f9b-40e3-87b7-86b59c93f63c.png)
![image](https://user-images.githubusercontent.com/24990178/206906710-2ad0088a-81d9-4096-a3dc-25e38cc1cdb3.png)

**Comment by ShubhamSudame** [comment]
![image](https://user-images.githubusercontent.com/24990178/206906741-c42d39f9-a517-4d64-a0ec-09e376335a70.png)

**Comment by Triskae** [comment]
Same issue here !

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
