### ISSUE TITLE
Bootstrap compatibility

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#1236]
Check components when bootstrap css is present as bootstrap's default border box-sizing might break some of the components.

**Comment by inzerion** [comment]
p-dropdown and p-checkbox css issues with Bootstrap
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

![screen shot 2016-11-14 at 5 37 31 pm](https://cloud.githubusercontent.com/assets/4501271/20270792/2cf24090-aa91-11e6-9717-b5b6fb241caf.png)

**Comment by cagataycivici** [comment]
Thanks, that is what I guessed. Fix is simple hopefully.

**Comment by vrmerlin** [comment]
I'm having this problem as well. Is a solution coming?  Does seem like it should be simple fix for those who know the CSS behaviors.

**Comment by gilhanan** [comment]
p-multiSelect also have some css issue with bootstrap:
![image](https://cloud.githubusercontent.com/assets/5566282/20924499/5695a65a-bbba-11e6-92ab-233abb9135b0.png)
