### ISSUE TITLE
Password: Add autocomplete property for input

### ISSUE THREAD

**Issue by t4keo** [primefaces/primeng#12362]
### Describe the feature you would like to see added

I want to use the p-password component because it’s less buggy than the directive (I just opened 2 issues) but I can’t set the "autocomplete" value directly via the component meaning that my browser think that it’s the current-password that I’m trying to set while it's the new one.
This could be avoided by adding an "inputAutocomplete" attribute to the component. This would just translate the inputAutocomplete to [attr.autocomplete]="valueOfInputAutocompleteProperty" and allow us to set it’s type so the browser knows which input means what.

### Is your feature request related to a problem?

The pPassword directive is not working well and not like p-password component

### Describe the solution you'd like

adding inputAutocomplete property to p-password component.
<p-password inputAutocomplete="new-password"></p-password>

See : https://developer.mozilla.org/en/docs/Web/HTML/Attributes/autocomplete

**Comment by t4keo** [comment]
https://github.com/primefaces/primeng/pull/11020

**Comment by t4keo** [comment]
Linked to issues : https://github.com/primefaces/primeng/issues/12360 and https://github.com/primefaces/primeng/issues/12361

**Comment by t4keo** [comment]
As a dirty workaround, it’s still possible to do this :

```typescript
@Component({
  selector: 'app-my-component',
  templateUrl: '<p-password #newPwdInput
                [feedback]="true"
                [toggleMask]="true"
                [(ngModel)]="newPassword"
                id="new-password"></p-password>'
})
export class MyComponent implements AfterViewInit {
  @ViewChild('newPwdInput') newPwdInput: Password;
  newPassword: string;

  constructor() {}

  ngAfterViewInit() {
    this.newPwdInput.input.nativeElement.autocomplete = 'new-password';
  }
}
```

**Comment by oleg-varlamov** [comment]
The same. We also need the ability to pass attributes to input so that the browser reacts correctly. Waiting for decision...

**Comment by aplanos** [comment]
In case anyone has the view hidden, and the password input is lazy loaded, for example when the form is loaded on a hidden sidebar, you can use the same approach than @t4keo, but instead using ngAfterViewInit use:

`ngAfterViewChecked() {
      this.newPassword.input.nativeElement.autocomplete = 'new-password';
}`

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primeng/pull/11020
