### ISSUE TITLE
p-table: scrollToVirtualIndex not working

### ISSUE THREAD

**Issue by probably-me** [primefaces/primeng#12372]
### Describe the bug

The scrollToVirtualIndex function does not scroll the desired row into view

### Environment

Angular 15 and latest PrimeNG version.

### Reproducer

https://angular-ivy-d6de7q.stackblitz.io

### Angular version

15.0.3

### PrimeNG version

15.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.17.1

### Browser(s)

Chrome, Edge

### Steps to reproduce the behavior

1. Ensure the table is scrolled to the top.
2. Enter the index into the editor of a row that is just out of view.  For example, i could see the first 21 rows so i tried using row 23.
3. The specified row is not scrolled into view.  The scrollbar does not move at all.

### Expected behavior

The specified row is scrolled into view.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
