### ISSUE TITLE
Component: Tree - onNodeDrop(event) - add operation type ([drop in/change parent] vs. [drop above/rearrange])

### ISSUE THREAD

**Issue by Ernio3** [primefaces/primeng#12376]
### Describe the feature you would like to see added

Make onNodeDrop(event) allow us to differentiate between "drop into" and "drop above" target node when dropping dragged node.

### Is your feature request related to a problem?

Currently we have:
```
onNodeDrop(event: {
	originalEvent: Event;
	dragNode: TreeNode<any>;
	dropNode: TreeNode<any>;
	index: any;
	accept(): any;
}) {}
```
The problem is that `event.index` is always equal to that of `event.dropNode`, no matter the operation - so both when we drop dragged node above some other node, or if we drop it into it - we get the same results in onNodeDrop(event).
Because of this when we would like to validate with `[validateDrop]="true"` and allow dropping with `event.accept()` we can't know what operation actually happened, if it was:

- rearrangement in the same parent
- dropping into other parent (onto it, so new index=0)
- dropping into other parent, but next to it's existing child, so index might not be 0.

### Describe the solution you'd like

Additional parameter provided in onNodeDrop(event) or literally anything that would allow us to differentiate without tricks.

### Describe alternatives you have considered

1. Custom implementation (which is simply very dirty solution).
2. Workaround would be to get:
`(event.originalEvent.target as HTMLElement)`
and since solid primeng TreeNodes are `<div>` and droppoints between them are `<li>` we would do check to know when our node was dropped into (another node, or a droppoint above it).

**Comment by arianox** [comment]
same Problem!

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
