### ISSUE TITLE
pDraggable: please permit attaching data

### ISSUE THREAD

**Issue by vigouredelaruse** [primefaces/primeng#12373]
### Describe the feature you would like to see added

in a component library scenario, it's useful to drag http retrieved entities from one component to another

the issue is simple if the component is added to its container component by its component selector tag like so:
```
<EmittingComponent (onDragDTO)="currentDraggedDTO" ></EmittingComponent>
```

however if EmitttingComponent is added to its container with a ```<router-outlet/>``` the event emitter option is obviously unavailable

for instance
* component A displays users
* component B displays user permissions
* permit setting user permissions by dragging from component A to component B or vice versa

to support this scenario pDraggable and pDroppable should
* offer a mechanism for the drop target to receive arbitrary drag data regardless of whether the drag source and the drop target are elements within the same component or not

### Describe the solution you'd like

pDraggable and pDroppable should permit attaching arbitrary objects that are available to drop event handlers

### Describe alternatives you have considered

currently i'm faking this with a singleton 'message broker' service that the drag source uses to emit on Subject<DTO> when dragging starts

given that pDraggable and pDroppable are independent i don't see another 'easy' way to implement this functionality

i am willing to submit such a glue service in a pull request if necessary
please advise

**Comment by vigouredelaruse** [comment]
to continue on the solution's i've tried vein, behold this bare class that broadcasts on a minimal set of subscriptions

```
/**
 * this service is intended to nearly statelessly mimic a
 * - publish / subscribe message broker
 * - with hardcoded message channels
 * - tolerate 'late joining' subscribers for drag start events
 * must
 * - indicate to subscribers what the current entity being dragged is
 * - support specific types being dragged and associated with specific broadcast channels
 * - ignore any ominous implications of singleton pattern use herein
 */
export class HorselessEntityDragAndDropService {

  arbitraryDragged$ : ReplaySubject<any> = new ReplaySubject<any>(1);


constructor() { }

}
```

for extra points, some delegate (pattern) extension point mechanism could be provided, such that consumers of pDraggable/pDroppable could supply an IPDraggableMessageBus of their own design that mentions their own data types and specifies their own set of channels as per their own requirements

regards

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
