### ISSUE TITLE
MultiSelect Input design issue when all elements are selected

### ISSUE THREAD

**Issue by iguissouma** [primefaces/primeng#1237]
The selected lit is not shown in one line, see the image below:
![2016-11-08_14h05_03](https://cloud.githubusercontent.com/assets/9085108/20100554/519b22e0-a5be-11e6-8707-e045aea3c249.png)

**Comment by iguissouma** [comment]
I fixed the issue adding white-space: nowrap; like below:

```
.ui-multiselect .ui-multiselect-label {
  display: block;
  padding: 3px 26px 3px 5px;
  width: auto;
  border: 0;
  white-space: nowrap;
  text-overflow: ellipsis;
  overflow: hidden;
}
```

**Comment by cagataycivici** [comment]
Which theme are you using?

**Comment by iguissouma** [comment]
ultima-ng

**Comment by cagataycivici** [comment]
Please report the issue at;

https://github.com/primefaces/ultima-ng
