### ISSUE TITLE
Component: Breadcrumb link opens in new tab

### ISSUE THREAD

**Issue by dhanush-tydy** [primefaces/primeng#12384]
### Describe the bug

breadcrumb links are opening in new tab after updating primeng to 14.x. but in 13.x it's working fine

### Environment

Angular app with primeng

### Angular version

14.2.12

### PrimeNG version

14.1.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.1

**Comment by dhanush-tydy** [comment]
Any update on this issue?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
