### ISSUE TITLE
MultiSelect: onPanelHide triggers twice

### ISSUE THREAD

**Issue by ppaulis** [primefaces/primeng#12382]
### Describe the bug

We are using multiple multiSelects in our applications and after upgrading primeng from 13.1.1 to 14.2.2 (along with an upgrade to Angular v14), the (onPanelHide) event seems to trigger twice. On 13.1.1 everything worked fine.

After a few tests in the Stackblitz, it seems that the bug has been introducted with PrimeNG **v14.2.0**. On v14.1.x eveything works as expected.

```
<p-multiSelect
    [options]="inventoryLocations"
    [(ngModel)]="selectedInventoryLocations"
    optionLabel="name"
    (onPanelHide)="filterUpdated()"
    placeholder="Select Location(s)"
></p-multiSelect>
```

### Environment

Angular v14.2
Node 16.15.0

### Reproducer

https://github-97sg5b.stackblitz.io/

### Angular version

14.2.12

### PrimeNG version

14.2.2

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

16.15.0

### Browser(s)

Chrome, Firefox

### Steps to reproduce the behavior

In the Stackblitz:

1. Select/Deselect one or more elements in the multiSelect
2. Click outside the multiSelect to trigger the onPanelHide
3. The counter below the multiSelect increments twice

### Expected behavior

I expect the onPanelHide event to be triggered only once when closing the panel of the multiSelect.

**Comment by jayee** [comment]
Also, when the multiselect is destroyed/unloaded the onPanelClose is triggered, even when never opened in the first place.
Tested in 14.2.3
