### ISSUE TITLE
Table Row Expansion | Scroll jumps up in tables with nested tables

### ISSUE THREAD

**Issue by arozdobudko-incomm** [primefaces/primeng#12381]
### Describe the bug

Table implicitly scrolls up if you click a row to display additional content and scroll down. 
Note: There wasn't such unwanted behavior in version 12.0.1

### Environment

Window 10
Google Chrome108.0.5359.73

Angular 15.0.1
PrimeNG 15.0.0 

### Reproducer

https://stackblitz.com/edit/primeng-tablerowexpansion-demo-nyhay7?file=src%2Fapp%2Fapp.component.html

### Angular version

15.0.1

### PrimeNG version

15.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14.2

### Browser(s)

Google Chrome108.0.5359.73

### Steps to reproduce the behavior

Open stackblitz example
Click chevron icon to expand row
Try to scroll down

Page will jump up, there is no possibility to scroll to the bottom of the table

### Expected behavior

Scroll should work as usual

**Comment by arozdobudko-incomm** [comment]
any updates?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
