### ISSUE TITLE
TreeTable: virtual scroll does not render content inside mat-tab-group

### ISSUE THREAD

**Issue by LucaVazz** [primefaces/primeng#12387]
### Describe the bug

When setting virtualScroll to true on a p-treetable which is contained in a mat-tab-group, no content is rendered.

### Environment

see stackblitz

### Reproducer

https://stackblitz.com/edit/primeng-treetable-demo-pzthvv

### Angular version

14.2.12

### PrimeNG version

14.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

n/a

### Browser(s)

n/a

### Steps to reproduce the behavior

1. open the second tab, observe that no table content is rendered
2. reload the preview, toggle isVirtualScroll to false, open the second tab, observe that table content is rendered

### Expected behavior

Table content should also be rendered with virtualScroll = true

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
