### ISSUE TITLE
Component: DataView createLazyLoadMetadata missing filters

### ISSUE THREAD

**Issue by yelhouti** [primefaces/primeng#12383]
### Describe the bug

In opposite to dataTable, dataView seems to be missing the filters from the lazyLoad event

### Environment

primeng app

### Angular version

14.2.3

### PrimeNG version

14.1.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.13.0

### Expected behavior

Lazy load event should be consistent

**Comment by mehmetcetin01140** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.
