### ISSUE TITLE
Treetable: thead / tbody out of sync. on keyboard navigation

### ISSUE THREAD

**Issue by maertz** [primefaces/primeng#12388]
### Describe the bug

The horzontal table body position gets out of sync. with the horizontal position of the table header position when the user navigates through the columns with the tab key.

That happens on tables where the total width of all columns exceeds the table viewport and allows the user to scroll horizontally.

### Environment

see stackblitz

### Reproducer

https://stackblitz.com/edit/primeng-treetableresize-demo-yr6q32

### Angular version

14.1.3

### PrimeNG version

14.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

n/a

### Browser(s)

n/a

### Steps to reproduce the behavior

1. Click on the page title
2. Press multiple times tab to focus through the column header links
3. Table header moves horizontally independent from the table body

### Expected behavior

Table body position stays in sync with the table header position.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
