### ISSUE TITLE
Component: Button

### ISSUE THREAD

**Issue by cdskill** [primefaces/primeng#12386]
### Describe the feature you would like to see added

Button component should be able to handle input [form] to trigger (for example) submit' event of form even if the button is not inside the [formGroup] directive.

Example bellow: 

https://stackblitz.com/edit/primeng-dialog-demo-qowuyc?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts

https://user-images.githubusercontent.com/12627583/207857756-e25b5ea1-0a38-44d8-a0a7-0ec4fde4aad3.mp4

### Is your feature request related to a problem?

Yes because sometimes it's happend that the submit action is trigger somewhere else. And if we want to not break the layout of a dialog (like the video above) we cannot wrap all the content in a form tag element.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
