### ISSUE TITLE
indeterminate of checkbox

### ISSUE THREAD

**Issue by jisqaqov** [primefaces/primeng#1239]
Good evening. Could you please consider adding "indeterminate" state for checkbox. Thanks.

**Comment by cagataycivici** [comment]
Is it different than triStateCheckbox?

http://www.primefaces.org/showcase/ui/input/triStateCheckbox.xhtml

**Comment by jisqaqov** [comment]
A little bit, it displays dash instead of cross sign and mostly used in partial selection like in Tree.
https://css-tricks.com/indeterminate-checkboxes/

**Comment by Nishanthi** [comment]
Hi, I am in need of this 'indeterminate' state of primeng checkbox. I see this issue is in open state, so can anyone suggest me an alternate or any work around please ?
