### ISSUE TITLE
Component: p-menu in popup mode, add a property to chose if the menu closes on the click of an item.

### ISSUE THREAD

**Issue by LouLeGrain** [primefaces/primeng#12391]
### Describe the feature you would like to see added

I use a p-menu component on popup mode, and i toggle items in the menu. (They are dynamic columns in a table)
It would be a better UX to keep the menu opened, to toggle items, and close it using the toggle button.

![pb](https://user-images.githubusercontent.com/9808953/208084131-de64d494-3209-4f40-95d5-61fa9f1924f4.gif)

### Describe the solution you'd like
Be able to keep the popup menu opened, with a single boolean value

`<p-menu [popup]="true" [model]="items" [closeOnItemClick]="false"></p-menu>`

![pb2](https://user-images.githubusercontent.com/9808953/208109740-5463fd18-1fa2-4635-939c-6eafa62b615f.gif)

**Comment by LouLeGrain** [comment]
Here's what i came with, i'll make a PR out of this.
![pb2](https://user-images.githubusercontent.com/9808953/208109740-5463fd18-1fa2-4635-939c-6eafa62b615f.gif)

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
