### ISSUE TITLE
p-dropdown throws ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by mrvanti** [primefaces/primeng#12390]
### Describe the bug

Hi,

When expanding a p-dropdown with a medium to large dataset ( > 300, it takes a split second to load) and pressing the expandbutton very quickly, it throws the following error:

ERROR Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'. Find more at https://angular.io/errors/NG0100
    at throwErrorIfNoChangesMode (core.mjs:9231:11)
    at bindingUpdated (core.mjs:13744:17)
    at bindingUpdated2 (core.mjs:13758:23)
    at bindingUpdated4 (core.mjs:13768:23)
    at pureFunction4Internal (core.mjs:21879:12)
    at Module.ɵɵpureFunction4 (core.mjs:21666:12)
    at MultiSelect_Template (primeng-multiselect.mjs:43:101)
    at executeTemplate (core.mjs:11242:9)
    at refreshView (core.mjs:11127:13)
    at refreshComponent (core.mjs:12188:13)

### Environment

Angular 15, PrimeNG 15,
Its currently beeing built in dev-mode.

### Angular version

15.0.2

### PrimeNG version

15.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14.0

### Browser(s)

Edge 107.0.1418.62

**Comment by Max0nyshchenko** [comment]
Any update here? I can reproduce the bug locally by having the same configuration but on Chrome 109.0.5414.120 (64-bit).
Also the bug is reproducible with p-multiSelect

**Comment by memodo** [comment]
This error is also being experienced on our project, but with the difference that it happens even with just a couple of items in the data set. Quickly and repeatedly clicking on a p-dropdown element leads to an NG0100 error.

**Comment by dnordahl1** [comment]
I'm seeing this intermittently with a cypress test interacting with dropdown in 16.9.1  
Adding some waits between dropdown click and item click seems like it might have worked, but the issue still appears to be present in 16
