### ISSUE TITLE
npm `latest` tag stills points to 14.2.3

### ISSUE THREAD

**Issue by thetric** [primefaces/primeng#12392]
### Describe the bug

![image](https://user-images.githubusercontent.com/19861998/208101749-ac1148a3-a481-4962-81f9-a9be54458a6e.png)

* https://www.npmjs.com/package/primeng?activeTab=versions
* https://yarnpkg.com/package/primeng

### Environment

npm, yarn 3

### Angular version

15.0.0

### PrimeNG version

15.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.1

### Expected behavior

The `latest` tag points to the latest 15.x version

**Comment by thetric** [comment]
I expect it to point the latest 16.x version but it points to the latest published version. Not sure if this is intended (by npm)

**Comment by viceice** [comment]
they should use a different tag, eg `lts` for publishing lts releases, so the latest tag always points to latest version

**Comment by thetric** [comment]
Seems to be fixed
