### ISSUE TITLE
Sidebar does not render the custom template!

### ISSUE THREAD

**Issue by Ruslancic** [primefaces/primeng#12395]
### Describe the bug

I created the new app with Angular, importded all PrimeNG dependencies and try to add sidebar with custom header, content and footer! And the redndering not working properly!

I tried from your demo stackblitz page and same error! Adding 
`
  <ng-template pTemplate="header">Header Content</ng-template>
  <ng-template pTemplate="content">Body Content</ng-template>
  <ng-template pTemplate="footer">Footer Content</ng-template>
`
not working!

### Environment

Angular: 15.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.3
@angular-devkit/build-angular   15.0.3
@angular-devkit/core            15.0.3
@angular-devkit/schematics      15.0.3
@angular/fire                   7.5.0
@nguniversal/builders           15.0.0
@nguniversal/express-engine     15.0.0
@schematics/angular             15.0.3
rxjs                            7.5.7
typescript                      4.8.4

### Angular version

13+

### PrimeNG version

15.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

**Comment by volvachev** [comment]
Hi, you should to import `SharedModule` from primeng, this module stores directives `pTemplate`.

**Comment by cetincakiroglu** [comment]
Hi,

Here is the example to show you how to implement: https://stackblitz.com/edit/primeng-sidebar-demo-rytfco?file=src%2Fapp%2Fapp.component.html,package.json,angular.json,src%2Fapp%2Fapp.module.ts
