### ISSUE TITLE
Webpack quickstart guide

### ISSUE THREAD

**Issue by bPopovska** [primefaces/primeng#124]
Do you have an intention to develop a quckstart guide for primeng + webpack?

**Comment by cagataycivici** [comment]
In fact, we do very soon.

**Comment by cagataycivici** [comment]
Assigned to @Mrtcndkn

**Comment by cagataycivici** [comment]
Please review;

https://github.com/Mrtcndkn/primeng-quickstart

**Comment by Mrtcndkn** [comment]
https://github.com/Mrtcndkn/primeng-quickstart updated

**Comment by cagataycivici** [comment]
Better to ask the repo owners.

**Comment by davisb10** [comment]
@sushant-j - You should be able to install the primeng package and font-awesome package with 'npm install --save primeng font-awesome' and then add the primeng and font-awesome stylesheets as explained in their documentation below.

[External Stylesheets](https://github.com/AngularClass/angular2-webpack-starter/#external-stylesheets)
