### ISSUE TITLE
Table scrollToVirtualIndex method hangs when scrolling to top

### ISSUE THREAD

**Issue by JamesSCADA98765** [primefaces/primeng#12403]
### Describe the bug

I have a table with virtual scrolling enabled and a pre-loaded dataset. I can use the scrollToVirtualIndex method to scroll a row near the bottom of the dataset without issue. However, if I use scrollToVirtualIndex to scroll up the table, the browser hangs.

### Environment

OS: Windows 11
Browser: Edge version 108.0.1462.54

### Reproducer

https://angular-ivy-b1v27t.stackblitz.io

### Angular version

15.0.4

### PrimeNG version

15.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.3.1

### Browser(s)

Edge version 108.0.1462.54

### Steps to reproduce the behavior

1. Go to StackBlitz
2. Click on "Scroll To 40000"
3. Click on "Scroll to Top"

### Expected behavior

Table should scroll to row 40000 and then back to top.
What actually happens is it scrolls to 40000, then hangs after scrolling to top.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
