### ISSUE TITLE
Masked Input in Calendar

### ISSUE THREAD

**Issue by msg-tbrtz** [primefaces/primeng#12401]
### Describe the feature you would like to see added

The PrimeNG [Calendar](https://www.primefaces.org/primeng/calendar) can be used using the mouse by picking a calendar and by using the keyboard by just typing out the date. The developer can configure the expected date format.

Sadly, this has limited use as the user does not implicitly know the expected format and faulty input is just deleted.

It would be desired to have the option to show the mask of the expected input, just like in [p-inputMask](https://www.primefaces.org/primeng/inputmask).

### Is your feature request related to a problem?

I'm always frustrated when I type a date to a calendar field, but not knowing the expected format exactly, my input gets deleted without any error message.

### Describe the solution you'd like

Let the calendar field have an input mask.

### Describe alternatives you have considered

One could add a label or plain text stating the expected date format.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
