### ISSUE TITLE
<p-dropdown> tag placeholder not working properly 

### ISSUE THREAD

**Issue by MrAkashKum** [primefaces/primeng#12407]
### Describe the bug

<p-dropdown inputId="roleList" [style]="{'minWidth':'100%'}" [options]="roles" optionLabel="name" formControlName="roles" [showClear]="true" optionValue="name" placeholder="Select Role" >
                </p-dropdown>

when click on dropdown then showing placeholder 

and I have used also dropDown module in module.ts file

### Environment

Dev

### Angular version

14

### PrimeNG version

14.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16

### Browser(s)

Google Chromo, Edge ana

### Steps to reproduce the behavior

Already I have added code in description 
use it 

1. added above code in HTML page
2. create array in ts file
3. added dropDown module in app.module.ts file
4. then run the project 

Snapshot -

![image](https://user-images.githubusercontent.com/109546378/208690005-7b8080e6-41db-497a-ad68-aa5414b950f9.png)

**Comment by volvachev** [comment]
Hi, could you add a stackblitz example? (I'm trying your code, but can't reproduce error).

**Comment by krraghav** [comment]
First One dropdown
<p-dropdown [options]="locationDetails" [style]="{'minWidth':'100%'}" formControlName="company" optionLabel="locationName" [filter]="true"
                filterBy="locationName" [showClear]="true" placeholder="Select a Company">
                <ng-template let-locationDetail pTemplate="item">

                    <div>{{locationDetail.locationName}}</div>

                </ng-template>
            </p-dropdown>

second one drop down

<p-dropdown inputId="roleList" [style]="{'minWidth':'100%'}" [options]="roles" optionLabel="name" formControlName="roles" [showClear]="true" optionValue="name" placeholder="Select Role" >
                </p-dropdown>
            
![image](https://user-images.githubusercontent.com/109546378/210330365-cbe59225-bc2b-4e32-96fb-44f7346d5bb0.png)

![image](https://user-images.githubusercontent.com/109546378/210330574-d121c0fb-da41-41ac-87d2-fed5caa281ef.png)

here drop down feature placeholder not working 
like placeholder="Select a Role">

            @cetincakiroglu @vincent @DerekLiang @volvachev

**Comment by krraghav** [comment]
okay @volvachev 
we are in very intial phase project development 
that's why I can share with you module 

Attached zip file and please create one Angular project and setup accordingly

if anything please let me know

Thanks
 

[user-info.zip](https://github.com/primefaces/primeng/files/10335481/user-info.zip)
