### ISSUE TITLE
Table - Resizing column affects other column's width.

### ISSUE THREAD

**Issue by aleckulikouski** [primefaces/primeng#12400]
### Describe the bug

While using 'Expand Mode' for resizbleColumns resizing one column results in width change column to the left.

### Environment

Ubuntu 20.04.5

### Reproducer

https://www.primefaces.org/primeng/table/colresize

### Angular version

14.2.4

### PrimeNG version

14.1.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.21.1

### Steps to reproduce the behavior

1. Resize 2nd column.
2. 1st column width changed.

### Expected behavior

1st column width remained.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
