### ISSUE TITLE
Multi-select: Options are not being shown when used in reactive form module

### ISSUE THREAD

**Issue by rajvarshu** [primefaces/primeng#12404]
### Describe the bug

I have integrated p-multiselect in a reactive form(autocomplete). Below is the code snippet

**<form novalidate [formGroup]="searchGroupForm" class="p-multiselect" >
    <p-multiSelect filterPlaceHolder="{{'webox.weboxHtml.search' | translate}}"
        defaultLabel="{{'sDevices.sDevicesHtml.filter_by_group_names' | translate}}"
        [options]="grpNamesByPlatform" formControlName="grpNamesFC"
        (onChange)="grpNameSelChanged($event)" class="dev-selection"
        (keyup)="grpNameSelChanged($event)" filterBy="label,value" #mySelect>
    </p-multiSelect>
</form>**

After typing more than 2 chars, I am triggering an API call to get the options list which contains the following values
[
{value: 'mongodb-id-groupa', label: 'GroupA'},
{value: 'mongodb-id-group', label: 'GroupB'},
]
I tried to console log and I can see the values in grpNamesByPlatform but the options are not showing

### Environment

<img width="791" alt="image" src="https://user-images.githubusercontent.com/22830847/208602755-2b242ee6-16e4-4021-91e2-af479c942ece.png">
<img width="428" alt="image" src="https://user-images.githubusercontent.com/22830847/208602781-30abbbbd-a831-496c-884e-d2b38afc60c4.png">

### Reproducer

<form novalidate [formGroup]="searchGroupForm" class="p-multiselect" >
    <p-multiSelect filterPlaceHolder="{{'webox.weboxHtml.search' | translate}}"
        defaultLabel="{{'sDevices.sDevicesHtml.filter_by_group_names' | translate}}"
        [options]="grpNamesByPlatform" formControlName="grpNamesFC"
        (onChange)="grpNameSelChanged($event)" class="dev-selection"
        (keyup)="grpNameSelChanged($event)" filterBy="label,value" #mySelect>
    </p-multiSelect>
</form>
### Angular version

11.2.13

### PrimeNG version

11.4.8

### Build / Runtime

Angular CLI App

### Language

ES6

### Node version (for AoT issues node --version)

14.17.3

### Browser(s)

Chrome

### Steps to reproduce the behavior

I have integrated p-multiselect in a reactive form(autocomplete). Below is the sample code snippet.

<form novalidate [formGroup]="searchGroupForm" class="p-multiselect" >
    <p-multiSelect filterPlaceHolder="{{'webox.weboxHtml.search' | translate}}"
        defaultLabel="{{'sDevices.sDevicesHtml.filter_by_group_names' | translate}}"
        [options]="grpNamesByPlatform" formControlName="grpNamesFC"
        (onChange)="grpNameSelChanged($event)" class="dev-selection"
        (keyup)="grpNameSelChanged($event)" filterBy="label,value" #mySelect>
    </p-multiSelect>
</form>
After typing more than 2 chars, I am triggering an API call to get the options list which contains the following values
[
{value: 'mongodb-id-groupa', label: 'GroupA'},
{value: 'mongodb-id-group', label: 'GroupB'},
]
I tried to console log and I can see the values in grpNamesByPlatform but the options are not showing

### Expected behavior

Options should be shown in the dropdown

**Comment by mehmetcetin01140** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.
