### ISSUE TITLE
Search left icon for autocomplete

### ISSUE THREAD

**Issue by apalpant** [primefaces/primeng#12413]
### Describe the feature you would like to see added

I would like to have search left icon like https://www.primefaces.org/primeng/inputtext on autocomplete

### Describe the solution you'd like

i would like boolean or string for visibility or icon description

### Describe alternatives you have considered

I did that by directive 

```
TS :

@Directive({
    selector: '[p-searchIcon]'
})
export class PAutoCompleteSearchIconDirective implements AfterViewInit {

    constructor(private autoComplete: AutoComplete) {
    }

    ngAfterViewInit(): void {
        const span = this.autoComplete.el.nativeElement.firstChild;
        const searchIcon= document.createElement("i");
        searchIcon.classList.add('pi', 'pi-search');
        searchIcon.style.left=".75rem";
        span.appendChild(searchIcon);
        span.classList.add('p-input-icon-left');
    }
}

CSS :

.p-input-icon-left > i:first-of-type {
    left: unset;
    color: #6c757d;
  }
```

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
