### ISSUE TITLE
InputNumber: Negative amount fails if currency is placed before the amount (Euro by example)

### ISSUE THREAD

**Issue by jcourtoy** [primefaces/primeng#12410]
### Describe the bug

Hello,

The only way to way to write a negative amount in euro (type currency) is to type the whole amount BEFORE typing the negative sign.

### Environment

You can reproduce it easily in your showcase : https://www.primefaces.org/primeng/inputnumber (the currency for Germany or Japan)

### Angular version

15

### PrimeNG version

15.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

19.1.0

### Browser(s)

Edge

### Steps to reproduce the behavior

1. Focus on an InputNumber with mode="currency" and currency="EUR"
2. Type "-"
3. Type your amount

### Expected behavior

It must have the same behavior than the dollar currency

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
