### ISSUE TITLE
Nested p-dialog do not move correcly

### ISSUE THREAD

**Issue by maxime-gr** [primefaces/primeng#12414]
### Describe the bug

When nesting a p-dialog inside another p-dialog, the p-dialog cannot be dragged correctly.

### Environment

See stackblitz.

### Reproducer

https://stackblitz.com/edit/angular-ivy-aeokxn?file=src/app/app.component.html

### Angular version

15.0.4

### PrimeNG version

15.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

8.5.4

### Steps to reproduce the behavior

Move the p-dialog nested into the other p-dialog, the p-dialog move at the bottom left of the viewport.

### Expected behavior

It should have the same behavior as when the p-dialog is not nested.

**Comment by cetincakiroglu** [comment]
Hi @maxime-gr,

Could you please update the Stackblitz example, it seems broken.

**Comment by maxime-gr** [comment]
Hi @cetincakiroglu,

I probably forgot to save it at some point... I updated my original comment.

**Comment by deepakoraon19** [comment]
A workaround would be appending the dialogs into the body, try adding [ appendTo = "body" ] to the dialog, works for me.

**Comment by mylifeandcode** [comment]
Having this issue as well in v17.4.0, and appendTo="body" does not correct it.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
