### ISSUE TITLE
Table Filter date picker position off screen (PrimeNG v.15)

### ISSUE THREAD

**Issue by aparkertg** [primefaces/primeng#12418]
### Describe the bug

Basic setup - Display a PrimeNG table with multiple rows. Place a "date" column at the right/end of the table. The date column needs to be filterable by date type with the filter display set to menu (display="menu"). The table should primarily take up the width of the screen.

When attempting to filter by date with the setup above, the date picker calendar's overlay is often positioned with much of the display off the screen. The user cannot select dates off the screen unless they horizontally scroll to the right. For our primary users this can be tedious.

This can be seen on the PrimeNG demo table filtering site: https://www.primefaces.org/primeng/table

Position the date column so that it's near the end of the screen on the right, and open the filter date picker. The left side of the date picker is positioned at the start of the filter input box (left: 0), and as a result, much of the date picker is off-screen.

It seems that previous versions positioned the date picker more appropriately. 
Stackblitz of PrimeNG v.13 with the date picker displayed correctly: https://primeng-tablefilter-demo-mqfwtn.stackblitz.io/

### Environment

Observed on Chrome, Firefox, and Safaria

### Angular version

15.0.3

### PrimeNG version

15.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.1

### Browser(s)

Chrome, Firefox, and Safaria

### Steps to reproduce the behavior

See basic description

**Comment by vokic** [comment]
I would like to reopen this issue because it is still present. The setup is the same as original post, here is the preview on PrimeNG website:

![chrome_screenshot (6)](https://user-images.githubusercontent.com/30930109/223415701-09b77d9e-9a66-4f48-9163-e5a38d92b56b.png)

**Comment by fattytedcoder** [comment]
I encounter the same issue. If the table width wider enough, full calendar in the most right hand column cannot display properly.

![image](https://user-images.githubusercontent.com/100893113/228718226-e24cadc6-591a-43f7-bb54-80274b7f01de.png)

**Reproducer**
https://primeng-tablevirtualscroll-demo-gk5wkx.stackblitz.io/
