### ISSUE TITLE
Table | Column resize is incompatible with frozen columns 

### ISSUE THREAD

**Issue by spbtne** [primefaces/primeng#12411]
### Describe the bug

https://user-images.githubusercontent.com/69213046/208846213-e5ea8b54-5833-403d-baf2-61b77f30efa4.mp4

The issue appears then column is frozen and resizable 

### Environment

Frozen Columns & Resizable columns

### Angular version

14.2.0

### PrimeNG version

14.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.13.2

### Browser(s)

Chrome 108

### Steps to reproduce the behavior

1. Go to table, with several frozen and resizable columns(in the video example Name and Id columns are frozen and resizable)
2. Change size of frozen column

### Expected behavior

Column width recalculated properly after resizing

**Comment by ThoSap** [comment]
Here you have a StackBlitz example with Angular `17.2.2`, NodeJS `v18.18.0`, and PrimeNG `17.11.0`
https://stackblitz.com/edit/wgwshv?file=src%2Fapp%2Fdemo%2Ftable-frozen-columns-demo.html

**Comment by ThoSap** [comment]
See GitHub discussion https://github.com/orgs/primefaces/discussions/1477

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
