### ISSUE TITLE
Calendar - keyboard flicker

### ISSUE THREAD

**Issue by nev-21** [primefaces/primeng#12425]
# Description

When click on calendar button, and touchUI is true, the input is focused then the calendar-dialog appear.

This provoke a flicker with keyboard (OSK) in phones and tablets.

# Solution

https://github.com/primefaces/primeng/blob/e514cd6738e1f10a19fccad92e9c2e5fad8fb80c/src/app/components/calendar/calendar.ts#L1491

this method should consider only focus the input if touchUI is false.

**Comment by nev-21** [comment]
Solution code

```
if (!this.overlayVisible) {
        if (!this.touchUI) {
          inputfield.focus();
        }
        this.showOverlay();
      } else {
        this.hideOverlay();
      }
```

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
