### ISSUE TITLE
Tabs are breaking when you try them with [selected] attribute

### ISSUE THREAD

**Issue by jignesh-techvasu** [primefaces/primeng#1242]
When using TabView component with [selected] attribute. It stops working as expected. I am using syntax like this :

```
<p-tabPanel header="Header Text" [selected]="selectedTab=='tab1'">
    Content 1
</p-tabPanel>
```

I have actually created clone of prime repo and added the same demonstration on prime tab demo page. Please see the issue in action. Please follow the instruction in README.md of repo for steps to reproduce. It's very simple to reproduce and nothing my application specific there. Pure simple clone of prime demo.

https://github.com/jignesh-techvasu/prime_tab_issue

Thank you.

**Comment by Mrtcndkn** [comment]
Hi it works totally fine in local.I reviewed your sample code thanks for being so clear btw.I have some minor changes on yours and its working.

`selectedTab: string = 'tab1';`

I created the variable typesafe.

and here is my working html

`<p-tabView>
        <p-tabPanel header="Godfather I" leftIcon="fa-calendar" [selected]="selectedTab === 'tab1'">
            The story begins as Don Vito Corleone, the head of a New York Mafia family, overseeshis daughter's wedding. His beloved son ichael has just come home from the war, but does not intend to become part of his father's business. T hrough Michael's life the nature of the family business becomes clear. The business of the family is just like the head of the family, kind and benevolent to those who give respect, but given to ruthless violence whenever anything stands against the good of the family.
        </p-tabPanel>
        <p-tabPanel header="Godfather II" rightIcon="fa-print" [selected]="selectedTab === 'tab2'">
            Francis Ford Coppola's legendary continuation and sequel to his landmark 1972 film, The_Godfather parallels the young Vito Corleone's rise with his son Michael's spiritual fall, deepening The_Godfather's depiction of the dark side of the American dream. In the early 1900s, the child Vito flees his Sicilian village for America after the local Mafia kills his family. Vito struggles to make a living, legally or illegally, for his wife and growing brood in Little Italy, killing the local Black Hand Fanucci after he demands his customary cut of the tyro's business. With Fanucci gone, Vito's communal stature grows.
        </p-tabPanel>
        <p-tabPanel header="Godfather III" leftIcon="fa-bell-o" rightIcon="fa-bookmark-o" [selected]="selectedTab === 'tab3'">
            After a break of more than  15 years, director Francis Ford Coppola and writer Mario Puzo returned to the well for this third and final story of the fictional Corleone crime family. Two decades have passed, and crime kingpin Michael Corleone, now divorced from his wife Kay has nearly succeeded in keeping his promise that his family would one day be completely legitimate.
        </p-tabPanel>
    </p-tabView>

    {{selectedTab === 'tab1'}}

    <button (click)="activateTab('tab1')">Activate Tab 1</button>
    <button (click)="activateTab('tab2')">Activate Tab 2</button>
    <button (click)="activateTab('tab3')">Activate Tab 3</button>`

**Comment by Mrtcndkn** [comment]
Hi I reviewed your sample code. Thanks for being so clear btw. It's working fine locally right now i have some minor changes on your code.

My variable is typesafe

`selectedTab: string = 'tab1'`
`
<p-tabPanel header="Header Text" [selected]="selectedTab === 'tab1'">
    Content 1
</p-tabPanel>
`
And I used === rather than == try this one please.

**Comment by jignesh-techvasu** [comment]
Hi,

Thank your for your attention. I have done both changes as you suggested. I updated repo. However, issue is still persisting.  

One interesting fact is that issue comes on only when you use  onChange handler

` <p-tabView (onChange)="onTabChange($event)">`

This is strange! To reproduce, please follow exactly below steps :

- Open the page : http://localhost:8080/#/tabview
- Click on second tab: "Godfather II"
- Click on "Activate Tab 1" button (You see nothing happens!!)
- Click on "Activate Tab 3" button (You see now we have tab2 and tab3 active togather!)

If you follow exact above steps, you will surely get it reproduced. 

Thank you for your help and all great work.

**Comment by jignesh-techvasu** [comment]
@Mrtcndkn I am not able to re-open the issue. I  hope you get my above message notification.
