### ISSUE TITLE
Title Column Re-sizer blue line is appearing even after the mouse click is released in Table

### ISSUE THREAD

**Issue by Charmi-webosmotic** [primefaces/primeng#12439]
### Describe the bug

Title Column Re-sizer blue line is appearing even after the mouse click is released in Table

Click on the column expansion line by using both the mouse(right & left) clicks and drag the mouse. Then release the mouse clicks. The blue highlighter line is still present and not disappearing in prime ng p-table component.

https://www.loom.com/share/70303831c08d4068b36cfa6798d803d1

### Environment

PrimeNG version : ^13.1.0

### Angular version

~13.1.1

### PrimeNG version

^13.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Browser(s)

Chrome (mac, window)

Replicate on 
System: Mac
Browser: (Chrome)

**Comment by cetincakiroglu** [comment]
Hi,

Cannot replicate the issue with the latest PrimeNG version. Could you please provide a Stackblitz example or give instructions on how to reproduce it?

**Comment by Charmi-webosmotic** [comment]
@cetincakiroglu Any Update on this issue?

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
