### ISSUE TITLE
OverlayPanel target arrow points to the wrong position when target is on the right edge of the screen

### ISSUE THREAD

**Issue by rtsinc** [primefaces/primeng#12435]
### Describe the bug

When the content is large, and on the right side of the screen, the arrow is wonky. 

Chrome:
<img width="1918" alt="primengOverlayPanelBug_Chrome" src="https://user-images.githubusercontent.com/64662104/209948229-5b8e68bd-368f-4d66-80a5-3150b4461ed7.png">
Safari:
<img width="1913" alt="primengOverlayPanelBug_Safari" src="https://user-images.githubusercontent.com/64662104/209948264-f9556aae-d782-4aeb-a1b4-3b5ceceb4a6e.png">

### Environment

Chrome:  108.0.5359.124 
Safari:  Version 16.2 (17614.3.7.1.7, 17614)

### Reproducer

https://stackblitz.com/edit/primeng-overlaypanel-demo-gj6ssy?file=src/app/app.component.html

### Angular version

13.0.3

### PrimeNG version

13.0.4

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

"ts-node": "~8.3.0"

### Steps to reproduce the behavior

To duplicate:
1. Go to https://www.primefaces.org/primeng/overlaypanel
2. Click on StackBlitz tab
3. Once in StackBlitz, click on Projects icon
4. Go to src/app/app.component.html and 
**Replace**
`<p-button [label]="selectedProduct ? selectedProduct.name : 'Select a Product'" icon="pi pi-search" (click)="op.toggle($event)"></p-button>`
**With**
```
<div style="text-align: right; cursor: pointer;">
    <i class="pi pi-shopping-cart" (click)="op.toggle($event)" 
    [title]="selectedProduct ? selectedProduct.name : 'Select a Product'" 
    [attr.aria-label]="selectedProduct ? selectedProduct.name : 'Select a Product'"></i>
</div>
```
5. Click on the shopping cart icon

### Expected behavior

Regardless of the content, the panel should be positioned so that the arrow aligns with the icon.

**Comment by rtsinc** [comment]
### My colleague Kyle has a **workaround**:

Turns out that alignment issue is caused by a really small button. I just tricked the overlay into thinking the button was bigger by adding padding and used negative margins to compensate for the padding.

Basically, if the button is less than 2-3rem, it wasn't able to place the arrow correctly.

I also decided to **remove the close button** bc I think it doesn't look good and doesn't make it any easier to dismiss the popup.


So, using the example above, add the following style to the icon:
`<i style="padding: 0 0.8rem; margin-left: -0.8rem;" class="pi pi-shopping-cart" (click)="op.toggle($event)" 
[title]="selectedProduct ? selectedProduct.name : 'Select a Product'" 
[attr.aria-label]="selectedProduct ? selectedProduct.name : 'Select a Product'"></i>`

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
