### ISSUE TITLE
Documentation : Unable to bookmark specific component or version page

### ISSUE THREAD

**Issue by jeff-a-andersen** [primefaces/primeng#12434]
### Describe the bug

On the website, you can no longer bookmark a component for a single link to a specific versions components.

For instance, if I bookmark "https://www.primefaces.org/primeng-v14/table", I'm redirected to "https://www.primefaces.org/primeng/", which then requires several clicks in your website to get to where I want to be.

I can bookmark "https://www.primefaces.org/primeng-v14", but then I have to click the "Components" link, search (or scroll) for the component and click it.

Can this be fixed so the bookmark functionality is back?  It seems to happen since the version 15 documentation was released to the website.

Thx

### Environment

https://www.primefaces.org/primeng

### Angular version

14.1.0

### PrimeNG version

14.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.7.0

### Browser(s)

All

### Steps to reproduce the behavior

See bug description for steps to reproduce.

### Expected behavior

Bookmark takes you to the component page.

**Comment by mertsincan** [comment]
Fixed for new versions' site.
