### ISSUE TITLE
Save State for TreeTable

### ISSUE THREAD

**Issue by critchie** [primefaces/primeng#12444]
### Describe the feature you would like to see added

I would like to be able to save state like you can with the Table.

### Describe the solution you'd like

Save treetable state like you can with a Table.

### Describe alternatives you have considered

Do not use the TreeTable.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
