### ISSUE TITLE
Add ColumnFilter to TreeTable

### ISSUE THREAD

**Issue by critchie** [primefaces/primeng#12443]
### Describe the feature you would like to see added

Is it possible to add a columnFilter to a TreeTable?

### Describe the solution you'd like

I'd like to use a columnFilter on a TreeTable the way you can use a columnFilter on a Table.

### Describe alternatives you have considered

Not using a TreeTable.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
