### ISSUE TITLE
p-dropdown: option displays "empty" when value is 0 (zero) instead of the actual value 0

### ISSUE THREAD

**Issue by FabienDehopre** [primefaces/primeng#12455]
### Describe the bug

When using an array of numbers for the dropdown options and that one of the values is 0 then the corresponding option displays "empty" instead of the actual value 0. 

This is because the template at line [60](https://github.com/primefaces/primeng/blob/master/src/app/components/dropdown/dropdown.ts#L60) uses a `||` instead of `??`.

### Environment

N/A

### Reproducer

https://stackblitz.com/edit/github-fkqm3v?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

### Angular version

15.0.4

### PrimeNG version

15.0.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.1

### Steps to reproduce the behavior

1. Go to the stackblitz reproduction url provided
2. Open the dropdown on the preview pane.

### Expected behavior

The option shouldn't display "empty" when the value is neither `null` nor `undefined`.
Use the optional operator `??` instead of the boolean operator `||` in the template.

**Comment by FabienDehopre** [comment]
@cetincakiroglu there is the same issue at line [136](https://github.com/primefaces/primeng/blob/master/src/app/components/dropdown/dropdown.ts#L136) so the bug is not fully resolved...

**Comment by likwidgames** [comment]
@cetincakiroglu this is not fixed as of 16.5.0

**Comment by cetincakiroglu** [comment]
Hi,

We're currently implementing accessibility and as a part of it, we've just reworked and refactored the dropdown component, this bug is fixed currently and the fix will be available in near future. We'll release accessibility implementation for the input components in upcoming weeks.
