### ISSUE TITLE
Overlay API

### ISSUE THREAD

**Issue by jiangyh1024** [primefaces/primeng#12459]
### Describe the bug

I did what the doc says, but didn't get it worked.

<img width="651" alt="image" src="https://user-images.githubusercontent.com/34930870/210714087-cef7129b-1278-4c21-aedd-a53c50edb17a.png">

but the overlay components didn't reflect this change

<img width="776" alt="image" src="https://user-images.githubusercontent.com/34930870/210714195-c348e89a-86eb-47d7-96d4-5fa709805083.png">

### Environment

macos

angular15

### Angular version

15

### PrimeNG version

15

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Browser(s)

chrome

**Comment by cetincakiroglu** [comment]
Hi,

Could you please share a Stackblitz reproducer so we can identify what's wrong?

**Comment by jiangyh1024** [comment]
https://stackblitz.com/edit/primeng-dropdown-demo-apvevj?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

menu list isn't appended to body

**Comment by jiangyh1024** [comment]
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/34930870/211493068-63fd3fd6-7742-4df0-9875-71c2629ab7ff.png">

**Comment by jiangyh1024** [comment]
calendar component has the same problem

**Comment by jiangyh1024** [comment]
calendar component has the same problem 


https://stackblitz.com/edit/primeng-dropdown-demo-apvevj?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
