### ISSUE TITLE
pContextMenu: Does not showUp on triggerEvent click

### ISSUE THREAD

**Issue by falkzilm-nuclos** [primefaces/primeng#12458]
### Describe the bug

We implemented on our side contextMenu openings on left-click via triggerEvent => 'click'.
After updating to newest primeNG Version, we had v12.1 previously and updated to v15, this stopped working.

Debugging the part lead me to an commit for fixing #11048 with commit 18e16b5762494f84f8aca1942db9345b4b65bef1
Here you removed the `event.stopPropagation()` part, i do not know if this is needed or intended but this breaks the possibility to use the `click` triggerEvent.

I also created a stackblitz example illustration the issue, it seems nothing happens but internally the contextMenu opens and closes instant.

### Environment

Angular 15 / PrimeNG 15

### Reproducer

https://stackblitz.com/edit/github-7ctpfl?file=src/app/app.component.html

### Angular version

15.0.4

### PrimeNG version

15.0.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.1

### Browser(s)

Vivaldi, Chrome

### Steps to reproduce the behavior

In StackBlitz click on `Element for contextMenu` this should open a contextMenu.

### Expected behavior

contextMenu should work with triggerEvent `click`

**Comment by bhavesh2777** [comment]
Hello @falkzilm-nuclos,
I'm frontend developer & interested in contributing in this project, is it okay?

**Comment by cetincakiroglu** [comment]
Hi,

You should use "global" input prop. Here is the refactored and working version of your example https://stackblitz.com/edit/github-7ctpfl-oij5ax?file=src%2Fapp%2Fapp.component.html

**Comment by falkzilm-nuclos** [comment]
This is not entirely the same behavior, i do want the contextMenu to be bound to the target element click Event and open with click not somewhere on the document  which has nothing to do with the target element.

So the global option is not the right thing. I do have a workaround atm to open the contextMenu on click on the element via ViewReference, where i do cancel the mouse event manually, but it did work in the previous versions. The only thing you changed between the versions are the `stopPropagation` and the question was if this is intended and needed?

**Comment by falkzilm-nuclos** [comment]
I guess i wont get any updates after this was closed ?
