### ISSUE TITLE
Overlay glith for table component  with frozen cols and editable rows

### ISSUE THREAD

**Issue by guillaume-f** [primefaces/primeng#12464]
### Describe the bug

With the Table component, when I combine the frozen columns option and editable by rows, there is an overlay bug only if the line is in edit mode

### Environment

Primeng : 13.0.4
Angular : 13.0.3

### Reproducer

https://stackblitz.com/edit/primeng-tableedit-demo-hxtejy?file=src/app/app.component.html

### Angular version

13.0.3

### PrimeNG version

13.0.4

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.15.5

### Browser(s)

All

### Steps to reproduce the behavior

In the example provided,
1/ Select a rows and click on the "pencil" icon to activate the edit mode for the row
2/ Scroll horizontally and see the bug
  => Some fields (dopdown, inputswitch,...) overlay the frozen column instead of pass behind

### Expected behavior

The fields had to pass behind the frozen column(s)

**Comment by mehmetcetin01140** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.
