### ISSUE TITLE
Bug : Paginator should stick to scrollable table on row number update

### ISSUE THREAD

**Issue by Torquin** [primefaces/primeng#12463]
### Describe the bug

When using scrollHeight & paginator i'm getting some issues with paginator not sticking to bottom of table on paginator change / column filter

### Environment

N/A

### Reproducer

https://primeng-tablescroll-demo-yfqwkm.stackblitz.io

### Angular version

15.0.4

### PrimeNG version

15.0.0

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

18.10.2

### Steps to reproduce the behavior

In stackblitz just change paginator from 10 to 5

### Expected behavior

The paginator should stick to the bottom of the datatable and not have empty space between the two

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
