### ISSUE TITLE
pButton Directive: Button does not adapt to width the label requires on initial load

### ISSUE THREAD

**Issue by silenum** [primefaces/primeng#12462]
### Describe the bug

On the initial load of the application, the buttons do not adapt to the width required by the label.

![image](https://user-images.githubusercontent.com/43389781/210976771-c5b2c4e9-05a3-4f54-8b09-5b574765ab46.png)

When changing the view and switching back the buttons have the expected width.

![image](https://user-images.githubusercontent.com/43389781/210977219-f4554133-f033-41c0-a115-0b7a006bc147.png)

### Environment

I am using [ngx-translate](https://github.com/ngx-translate/core) within the label declaration.

See the following code snippet as a representative example:

```html
<button class="mt-3 mr-3 p-button-raised p-button-secondary"
        icon="fas fa-person-walking-arrow-right"
        label="{{'home.button.trail' | translate}}"
        pButton
        pRipple
        routerLink="/ctp/trail"
        type="button">
</button>
```

### Angular version

15.0.4

### PrimeNG version

15.0.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.1

### Expected behavior

I would the buttons expect to render with the width the labels require on the initial load,
so that they look as follows:

![image](https://user-images.githubusercontent.com/43389781/210977219-f4554133-f033-41c0-a115-0b7a006bc147.png)

**Comment by lkijak** [comment]
Same for me, after going to the page the buttons have the correct width but after refreshing the page their width decreases and a new style is added to them

.p-button.p-button-icon-only {
     width: 2.357rem;
     padding: 0.5 rem 0;
}

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
