### ISSUE TITLE
Component: We cannot Able To Add Custom Icons And Custom Img

### ISSUE THREAD

**Issue by RAJEEV2510** [primefaces/primeng#12467]
### Describe the feature you would like to see added

In Tree node There is no option for user can add change image-icon according to requirement .
I add a customImage property if user true that property user now can add custom Images too.

### Is your feature request related to a problem?

I have a probem ,we want use our own images to tree node

### Describe the solution you'd like

I added a customImage property in tree node , if user true that property user now can add custom Images too.
in node model just true this property and do node.icon=image-path

nodeModel={
....
,
customImage:true

}
and  and give node.icon =image-path;
![customImageProperty](https://user-images.githubusercontent.com/49456702/211133694-347192e4-7376-4ffa-8006-ce0daf7cceb3.png)

**Comment by rayen-mhamdi** [comment]
we want this feature, can any one reopen the PR and merge it  ?

**Comment by RAJEEV2510** [comment]
Hii primefaces team , 
i want this feature which was requested my pull request.
 please merge this feature and let others to add any icon or images

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
