### ISSUE TITLE
p-table with Virtual Scroll and Lazy Loading display error

### ISSUE THREAD

**Issue by dnetuschil** [primefaces/primeng#12465]
Hi,

### Describe the bug

In the version 11-LTS of PrimeNG, a `<p-table>` with lazyLoading + Scroller did not require an array length at the init.
When you arrived at the end of your loaded data, a new call was getting the next batch of data.

(I've not tryed this on version 12 and 13 of PrimeNg).

In my project, I use the p-table (version 14) with :
- [Virtual Scroll](https://www.primefaces.org/primeng-v14/table/virtualscroll)
- [Lazy Loading](https://www.primefaces.org/primeng-v14/table/lazy)
- [Filter](https://www.primefaces.org/primeng-v14/#/table/filter)

The problems are :
-  The data does not load because the onLazyLoad($event) returns `event.rows = 0` and my API returns an empty array.
-  When I use the reset method of the primeng table component, I have data returned by my API, but it does not display.

It does not work until I assign a length to my array. The issue here is that I don't know precisely the among of records in my array each time. For exemple, I could assign a length of 10k to my array but that would leave me with a huge blank at the bottom. 

If the array's length is reassigned after the component's init, the scrollbar does not resize to the table's size.

### Environment

Angular 14, Primeng 14.2.3, see the stackblitz

### Reproducer

https://stackblitz.com/edit/primeng-tablevirtualscroll-demo-fbg1xz?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html

### Angular version

14.2.12

### PrimeNG version

14.2.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.17.0 

### Browser(s)

Brave

### Steps to reproduce the behavior

1. Open my stackblitz example
2. Show the console (initialize with data : First : 0, Rows : 0, Table : 0)
3. Click on RESET button and show the console (First : 0, Rows : 100, Table : 100)
4. Take note that the data is not displayed in the `<p-table>` (it's not in the DOM neither).

### Expected behavior

I want to display my data without having to initialize the length of my array first.

**Comment by mertsincan** [comment]
Hi,

This is by design. Table needs the default array length to set the scrollbar and other calculations. So in such issues, a call should be made to the DB to get the size of the data. Then lazy loads can be performed.
```
ngOnInit() { // OR other lifecycle methods according to your needs.
    ...

    fetch(<END_POINT>).then(res => {
        this.virtualCars = Array.from({ length: res.size });
    });
  }
```

Best Regards,
