### ISSUE TITLE
this.value in calendar is sometimes a string make the code fails when calling date methods like getFullYear

### ISSUE THREAD

**Issue by iguissouma** [primefaces/primeng#1246]
this.value in calendar is sometimes a string make the code fails when calling date methods like getFullYear

![2016-11-08_10h22_39](https://cloud.githubusercontent.com/assets/9085108/20135669/36f7bd50-a671-11e6-922b-8cdf25249a97.png)

prime-ng rc3

**Comment by iguissouma** [comment]
Seems to be fixed in prime-ng rc4.

**Comment by Prontsevich** [comment]
Have this problem in 1.1.4.  Init Calendar with date in code, then open page and you get string instead of date. But if you select any day then there is a date in this.value.

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/VZbdZfQ7SuTV87tTkbYR
