### ISSUE TITLE
Component: Chip

### ISSUE THREAD

**Issue by sebastienchevriaupro** [primefaces/primeng#12479]
### Describe the feature you would like to see added

Prevent hiding the chip only when the called "onRemove" is a success
For example, if chips are entities in DB, hiding them should only occurs if the called API returns the success response.

### Describe the solution you'd like

either catching a returned boolean of the onRemove event
either a boolean to control the visibility

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
