### ISSUE TITLE
Title - Prime overlay close on escape key

### ISSUE THREAD

**Issue by AjeetUI** [primefaces/primeng#12473]
Is Possible to close prime overlay on escape key?

**Comment by AjeetUI** [comment]
Any update?

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
