### ISSUE TITLE
Incorrect Arrow Direction In Dialog Examples

### ISSUE THREAD

**Issue by batlasAEI** [primefaces/primeng#12482]
For each of the examples involving opening a p-dialog in a certain position, the arrows are facing the opposite direction than what the position is. This kind of makes sense for left/right/top/left as the dialogs animate in that direction, but for all of the diagonals they just appear in that area, making the arrows appear backwards.

https://github.com/primefaces/primeng/blob/5539bb252be5d7e5bbb09704d998c8158eca3d3b/src/app/showcase/components/dialog/dialogdemo.html#L83-L98

![image](https://user-images.githubusercontent.com/39916532/211901600-b70b4b0b-e3b2-4067-9f3a-ac5783d609f5.png)

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
