### ISSUE TITLE
Table: EmptyMessage

### ISSUE THREAD

**Issue by gaellegoff** [primefaces/primeng#12489]
### Describe the bug

It looks like the emptymessage pTemplate doesn't work anymore

### Environment

CRM application : Angular

### Angular version

15.0.3

### PrimeNG version

15.0.1

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

16.18.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

I've got a p-table in my template with a pTemplate="emptymessage"
But the message is never shown

**Comment by volvachev** [comment]
Hi, could you add example on stackblitz?

**Comment by gaellegoff** [comment]
I found the explanation, sorry
