### ISSUE TITLE
Table | Unable to reorder to the last element in the table after a scroll occurs

### ISSUE THREAD

**Issue by NinkevdVeen** [primefaces/primeng#12493]
### Describe the bug

We have encountered some behaviour which is a bit confusing/illogical and we think is incorrect, hence this bug report.

When ordering in the table with Reorder you can pick up the last item. When moving it slightly up the drop area is visible just above the picked up item. So the area between the last item and the item before last.
When I drop this last item there I expect it to be dropped where it used to be, but instead it is moved 1 row before.

I saw there were some issues with the last item and scrolling, so perhaps there is some relation? (https://github.com/primefaces/primeng/issues/10003)

### Environment

Can be found in the documentation: https://primefaces.org/primeng/table/reorder -> so this concerns latest versions, but I have added versions as described in provided stackblitz (https://stackblitz.com/edit/primeng-tablereorder-demo) as well as our tested versions

- Latest Firefox: currently 108.0.2
- Latest Chrome: currently 109.0.5414.87
- OS: MacOs, but also seen in Linux

### Reproducer

https://stackblitz.com/edit/primeng-tablereorder-demo

### Angular version

13.0.3 and 14.2.6

### PrimeNG version

13.0.4 and 14.1.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18 and 16

### Browser(s)

latest Firefox & Chrome, possibly others

### Steps to reproduce the behavior

1. go to either https://primefaces.org/primeng/table/reorder or https://primeng-tablereorder-demo.stackblitz.io
2. click and hold last item in list (gaming set, which is below game controller)
3. move it up a couple of pixels, you will see a drop area right below game controller, and above item you are holding(gaming set).
4. drop the game set in that drop area, so between current item and item above current.
5. Game set should not move, or just move to the same position, but instead has moved above game controller and has become item before last.

This happens when you drag Gaming set **above** game controller as well, but that is expected behaviour.

### Expected behavior

When dragging last item in list (Gaming set) between last item(gaming set) and item before last (Gaming controller) I expect the item to move there, which mean to actually not move at all.
I do not expect it to move before the item before last, above game controller.

**Comment by talitagoulart** [comment]
I recorded a video to demonstrate the issue on the official doc page:
https://user-images.githubusercontent.com/3587657/222754594-3cb1ab32-d653-4114-aec3-bf0f2e8966e0.mov

- Drag a row and drop it in the last position. Since the table is completely in the visible area, it works.
- Zoom in so the end of the table is outside the visible area.
- Scroll down to see the end of the table and try to move a row to the last position. The drop marker doesn't show so the row can't be dropped in the last position.
