### ISSUE TITLE
Accordion: Low type checking and outdated docs

### ISSUE THREAD

**Issue by IvanPenyaHuguet** [primefaces/primeng#12499]
### Describe the bug

Some of the inputs, otputs and implementation of the Accordion are not properly typed with typescript or described in the docs. 

Example:
- activeIndex is not any, it is a number or number[]
- style is not any (as implemented) or string (as docs), it is an object
- selectedChange output is not any, it is a boolean

The docs does not describe all the outputs available in the components, like activeIndexChange.

Additionally, the accordion is using "which" to check the key pressed for accesibility, it is recommended to avoid which.

### Environment

Angular 14.x.x
Primeng 14.x.x

### Angular version

14.x.x

### PrimeNG version

14.x.x

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.15.0

**Comment by cetincakiroglu** [comment]
Hi @IvanPenyaHuguet,

Thanks a lot for your contribution, I've explained why we cannot merge in your PR. Again, I'm labeling the issue as documentation and it'll be evaluated when the documentation update for the related component is in progress.
