### ISSUE TITLE
Button: p-button executing methods on click when disabled

### ISSUE THREAD

**Issue by cosmin19** [primefaces/primeng#12495]
### Describe the bug

__Code:__
``` html
<p-button label="Not OK" disabled="true" (click)="foo()"></p-button>
```
__Bug:__ foo method is executed on click even though the button is disabled. This happens only when using p-button. 

If I'm using
```html
<button pButton label="OK" disabled="true" (click)="foo()"></button>
```
the foo method is not executed.

### Environment

Angular 15.0.4
PrimeNG 15.0.1
Tested in Chrome Version 108.0.5359.124 (Official Build) (64-bit)

### Angular version

15.0.4

### PrimeNG version

15.0.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.1

### Steps to reproduce the behavior

1. Create a foo method in .ts file
``` typescript
foo() { console.log('Hello world') }
```
2. Add button in .html file
``` html
<p-button label="Not OK" disabled="true" (click)="foo()"></p-button>
```
3. Click on button
4. Observe how method **foo** is executed

### Expected behavior

Disabled buttons should not execute methods on click.

**Comment by critchie** [comment]
When using p-button you have to use (onClick)="foo()". When using onClick with p-button the click event will not fire when the button is disabled.

Events
Events are defined using standard notation in pButton and with on* prefix at p-button.

<button pButton type="button" label="Click" (click)="handleClick($event)"></button>
<p-button label="Click" (onClick)="handleClick($event)"></p-button>

**Comment by jucasoft** [comment]
@volvachev
I looked at your implementation but I believe it doesn't solve the problem. I suspect the problem is with how chromium catches the "click" event.

@cosmin19 explained the problem very well, it doesn't depend on the graphic style.

**Comment by volvachev** [comment]
> @volvachev I looked at your implementation but I believe it doesn't solve the problem. I suspect the problem is with how chromium catches the "click" event.
> 
> @cosmin19 explained the problem very well, it doesn't depend on the graphic style.

Hi, this class adds`pointer-events: none` that block an event such as `click`.

**Comment by jucasoft** [comment]
> > @volvachev I looked at your implementation but I believe it doesn't solve the problem. I suspect the problem is with how chromium catches the "click" event.
> > @cosmin19 explained the problem very well, it doesn't depend on the graphic style.
> 
> Hi, this class adds`pointer-events: none` that block an event such as `click`.

I have to pay you for a coffee. do cats like coffee?

thank you.

**Comment by volvachev** [comment]
> I have to pay you for a coffee. do cats like coffee?
> 
> thank you.

Cats like coffee only with milk 😉.  What about dogs?
You're welcome
