### ISSUE TITLE
Tree: It is impossible to select any chckbox(es) in Multiple Selection with Checkbox after any filtering

### ISSUE THREAD

**Issue by mkmeric** [primefaces/primeng#12496]
### Describe the bug

Resulting node(s) cannot be be clicked after filtering in Tree component with Multiple Selection with Checkbox. Also console errorr as "ERROR RangeError: Maximum call stack size exceeded"

### Environment

Windows 11.

### Angular version

15.0.5

### PrimeNG version

15.0.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.1

### Browser(s)

Chrome 109.0.5414.74

### Steps to reproduce the behavior

1. Create tree with Multiple Selection with Checkbox
2. Enable filtering
3. Filter any node in tree
4. Checkbox cannot clicked

### Expected behavior

Resulting node(s) should be clicked after filtering in Tree component with Multiple Selection with Checkbox

**Comment by yuweibor** [comment]
same error ! need to be fixed ....

**Comment by yuweibor** [comment]
in fact when rebuilding tree data,  they add the root node to parent of root node with error .
in correct way , root node`s parent should be null forever.

**Comment by davidediak** [comment]
Found the solution:
you need to specify the property "key" for all the nodes. 
It's not documented anywhere AFAIK.

**Comment by mkmeric** [comment]
> Found the solution: you need to specify the property "key" for all the nodes. It's not documented anywhere AFAIK.

Any example code?

Thanks...

**Comment by davidediak** [comment]
> Any example code?

p-tree needs an array of TreeNode as input right?
If you check the actual definition of TreeNode you see a `key` property, you just need to define it for all nodes.
That simple.

**Comment by mastersys-giovanni** [comment]
16.8 same error

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
