### ISSUE TITLE
calendar

### ISSUE THREAD

**Issue by nizalsha** [primefaces/primeng#12497]
### Describe the bug

I have added calendar to my component like following

`<p-calendar [(ngModel)]="date14" [inline]="true"></p-calendar>`

and get this error message
Type 'Event' is missing the following properties from type 'Date': toDateString, toTimeString, toLocaleDateString, toLocaleTimeString, and 37 more.

I have added calendar module to my app module, but got this

### Environment

Angular 14.x.x
primeng 14.x.x

### Angular version

14.0.0

### PrimeNG version

14.2.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.16.0

**Comment by pouyababaie** [comment]
@nizalsha what is date14 type?

**Comment by nizalsha** [comment]
date14 is type Date.

Actualy I solved this issue, this has due to some imports in my app module.  

I have imported reactiveformsmodule and the issue was solved.

Thanks for your quick response
