### ISSUE TITLE
TreeSelect filter not appearing properly

### ISSUE THREAD

**Issue by critchie** [primefaces/primeng#12491]
### Describe the bug

I can't seem to get the p-treeSelect filter to appear properly.

![image](https://user-images.githubusercontent.com/340046/212212215-4baec5e2-3752-40de-b69b-90f4e2d69cdf.png)

I have it wrapped in a span for floating labels and I'm using reactive forms.
```
  <span class="p-float-label">
    <p-treeSelect
      id="parentId"
      placeholder="Select a Parent Project"
      formControlName="parentId"
      [options]="projectOptions"
      [filter]="true"
    >
    </p-treeSelect>
    <label for="parentId">Parent</label>
  </span>
```

The demo on the primeng site shows a working treeselect with filter. I'm baffled on what is happening here.

### Environment

N/A

### Angular version

15.1.0

### PrimeNG version

15.0.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v18.12.1

### Browser(s)

Google

**Comment by felixoehler** [comment]
I had the same issue but I could fix it by updating my primeng-designer theme. The one I was using was generated with Angular 11 or something. Using one generated with the Angular 14 version fixed the issue for me.

**Comment by critchie** [comment]
My theme was generated with Theme Designer v14 but I saw that v15 was ready so I grabbed it and regenerated my theme. And now it works.

Thanks for help.
