### ISSUE TITLE
Dropdown gets disabled after element selected

### ISSUE THREAD

**Issue by derchirurg** [primefaces/primeng#1250]
The dropdown box gets disabled after an element was selected. If I want to select another value, the dropdown is disabled.

My HTML:
`<p-dropdown [options]="myoptions" [(ngModel)]="selected.Id"></p-dropdown>`

My TS code in Component:
```
[...]
export class MyComponent implements OnInit
{
    selected: any;
    myoptions: SelectItem[];

    constructor()
    {
        super();
        this.myoptions= [];
    }

    ngOnInit()
    {
        this.myservice.get()
            .subscribe((result) =>
            {
                result.forEach(element =>
                {
                    this.myoptions.push({label: element.Name, value: element.Id});
                });
            });
    }
[...]
}
```

What am I doing wrong?

**Comment by iguissouma** [comment]
Try with the following code:
HTML:
`<p-dropdown [options]="myoptions" [(ngModel)]="selected"></p-dropdown>`

**Comment by derchirurg** [comment]
Thanks for your feedback.
This can not work, becaus I need to bind to the ID.
But I tried it, it is still disabled (and the value is not bound correctly, as I wrote above).

**Comment by iguissouma** [comment]
Can you check the javascript console for errors?

**Comment by derchirurg** [comment]
There are no errors in the console.

**Comment by iguissouma** [comment]
I have the folowing working example:
```
<p-dropdown id="country" formControlName="country" [options]="listOfCountries" [(ngModel)]="establishment.countryId"
                      [autoWidth]="false"></p-dropdown>
```
Maybe there's problem when not using formControlName.

**Comment by derchirurg** [comment]
That is not working for me, because I'm not using model driven forms. I just bind to `ngModel`, then I am getting an error if I user `formControlName`.

**Comment by derchirurg** [comment]
Same behaviour in new released rc.4.

**Comment by cagataycivici** [comment]
Please provide a test case that we can replicate, we are unable to replicate right now.

**Comment by derchirurg** [comment]
I think it was an issue with ng-bootstrap. With the new update, there are no problems.
