### ISSUE TITLE
'primeng/api' or its corresponding type declarations. 

### ISSUE THREAD

**Issue by 3238011256** [primefaces/primeng#12505]

**Comment by 3238011256** [comment]
install primeNg another project in angular show the error.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
