### ISSUE TITLE
Add Dynamic Sidebar feature

### ISSUE THREAD

**Issue by JeffGreat** [primefaces/primeng#12507]
We should have a dynamic sidebar just like dynamic dialog. Actually, having all that tags declarations in html files is not convenient at all.

Thank you

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
