### ISSUE TITLE
onLazyLoad event not firing in p-multiSelect

### ISSUE THREAD

**Issue by vetrims11** [primefaces/primeng#12509]
### Describe the feature you would like to see added

<p-multiSelect
      [options]="ecuNumbers"
      [placeholder]="'LABEL.SNG.ECU_NUMBER' | translate"
      optionLabel="name"
      formControlName="ecuNumber"
      [lazy]="true"
      [filter]="true"
      [virtualScroll]="true"
      [virtualScrollItemSize]="34"
      [lazyLoadOnInit]="true"
      (onLazyLoad)="loadLazy($event)"
      [maxSelectedLabels]="2"
    >
      <ng-template #rbMultiselectItem let-ecu>
        {{ ecu.name }}
      </ng-template>
    </p-multiSelect>

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
