### ISSUE TITLE
FileUpload + Drag and Drop: Drag and drop triggers upload in Firefox Developer Edition

### ISSUE THREAD

**Issue by abinici** [primefaces/primeng#12518]
### Describe the bug

We have been using your file upload component for an internal application where we can upload images. Besides uploading, we have also implemented functionality for changing the order of the images. To accomplish this we have used your drag and drop component. You can drag an image and drop it above another image, and their positions will be swapped. This has worked perfectly until recently where we found an issue in Firefox Developer Edition. When using Firefox Developer Edition and trying to change image position, the file upload component acts like we dropped a new image for upload.

Here is a snippet from our code:

```html
<div [class.dragging]="draggedFile !== file && draggedFile !== null" class="image-container ui-fileupload-content" *ngFor="let file of files">
    <div [pDroppable]="isLoading ? '' : 'dd'" (onDrop)="drop($event,file)">
        <lc-image-container pDraggable="dd" (onDragStart)="dragStart($event,file)" (onDragEnd)="dragEnd($event)" [width]="150">
        </lc-image-container>
    </div>
</div>
```

I have a short screen recording that shows the issue:
https://drive.google.com/open?id=1xN_sSt6yJV2aZX2RGh3wAQDNSC0omQMF

### Environment

We experience the issue in Firefox Developer Edition and not in Firefox. But eventually this issue will also happen in Firefox.

### Angular version

12.2.16

### PrimeNG version

12.2.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.15.0

### Browser(s)

Firefox Developer Edition 110.0b2 (64-bit)

### Expected behavior

Normally, when we drag and drop an element, using the drag and drop component, to change element position, the file upload component does not treat this is as a new upload.

Here is a screen recording of the expected behavior in Chrome:
https://drive.google.com/open?id=1xNx1kT4Jf0yFFLxhhGQLg5JPChL2Xxzb

**Comment by mehmetcetin01140** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.
