### ISSUE TITLE
throws error Cannot find module 'primeNg/api' or  its corresponding type declarations.

### ISSUE THREAD

**Issue by 3238011256** [primefaces/primeng#12512]
### Describe the bug

in angular show following error: 
Cannot find module 'primeNg/api' or  its corresponding type declarations.

### Environment

windows 10

### Angular version

14.2.0

### PrimeNG version

13.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v14.15.4

### Browser(s)

chrome version 109.0.5414.74

### Steps to reproduce the behavior

git clone https://github.com/primefaces/primeng/releases/tag/13.4.1.
npm install .
import accordionModule in app.module.ts show the error terminal.

### Expected behavior

no error.
![Screenshot (2)](https://user-images.githubusercontent.com/111338608/213094242-edded707-0b0b-4f25-8fb0-d15f4652d3ee.png)

**Comment by mehmetcetin01140** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.
