### ISSUE TITLE
Dropdown: E2E testing ExpressionChangedAfterItHasBeenChecked (NG0100)

### ISSUE THREAD

**Issue by MatW3B** [primefaces/primeng#12519]
### Describe the bug

Trying to test dropdown component  in Cypress - expanding and immediately clicking an option - causes thrown expressionChangedAfterItHasBeenChecked error.
Seems like a similiar issue to https://github.com/primefaces/primeng/issues/12390, but here it's just a simple dropdown without multiselect and expansion button. I provide a minimalistic reproducible example as well. Please check the repo in Reproducer.

Caused by `p-inputwrapper` it seems.

**Has a workaround:** Use cy.wait(500) in the testing screnario, before clicking another option and after expanding the dropdown.

### Environment

Windows 10
Cypress 10.9.0

### Reproducer

https://github.com/MatW3B/pNG-15-dropdown-issue

### Angular version

15.1.1

### PrimeNG version

15.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.15.1

### Steps to reproduce the behavior

Steps based on provided repository:
1. Clone the repo provided in Reproducer;
2. `npm i` to install packages;
3. run `npm run start` to start the devserver;
4. In another terminal: run `npm run cy:open` to run cypress;
5. In cypress gui: ctrl + shift + I to toggle devtools, and move to console;
6. click on the only spec provided and let it run;
7. after it finishes note the error in the console.

Actual issue:
1. Have a dropdown anywhere with at least 2 selectable options provided;
2. Open the dropdown and quickly choose another option
3. Observe the error in the console.

### Expected behavior

No errors in the dev environment in the console.

**Comment by Max0nyshchenko** [comment]
Any update here? I can reproduce the bug manually (without cypress) on localhost by having the same configuration on Chrome 109.0.5414.120 (64-bit).
Also the bug is reproducible with p-multiSelect as well.

**Comment by roman-balzer** [comment]
We also just noticed the issue while E2E Testing with Cypress. After a little bit playing around with it, I noticed that I can reproduce it by clicking fast. (Double-Click on the dropdown box). I tried reduce potential factors, so I remove parameters to find whats causing the issue. For instance removing `filter` and `filterBy` helped a bit. I have to click faster to get the error message. But ultimately the minimal code to reproduce the error is:
`<p-dropdown></p-dropdown>`
Well, I have to click really fast (and have to be in a dev environment), but the it will throw an error. Currently we will use `cy.wait()` to get E2E-Tests working...

**Comment by miguelchico** [comment]
same thing happening for me

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
