### ISSUE TITLE
Docs: Search

### ISSUE THREAD

**Issue by EmirBoyaci** [primefaces/primeng#12515]
### Describe the bug

Hi,

I was checking PrimeNG docs and wanted to search a component. When I type something in the input area, it does not search and it acts like nothing happened 😄

### Environment

https://primefaces.org/primeng

### Angular version

-

### PrimeNG version

15.0.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

-

### Steps to reproduce the behavior

1. Go to https://primefaces.org/primeng
2. Type something to the search input

**Comment by ridy01-backup** [comment]
https://primefaces.org/primeng/setup do you mean the search field on this site? It works for me.

**Comment by EmirBoyaci** [comment]
> https://primefaces.org/primeng/setup do you mean the search field on this site? It works for me.

Okay I got it right now, I had some issues about the rendering i think. However, behavior of search input is differs if you compare with PrimeReact's search input. IMHO it shouldn't differ between Prime* libraries :) Nevermind, it works as expected.
