### ISSUE TITLE
Dropdown and MultiSelect panel overflow

### ISSUE THREAD

**Issue by Xriuk** [primefaces/primeng#12523]
### Describe the bug

When long labels are used the dropdown/multiselect panels overflow the body, this happens especially on mobile devices.
This happens both with attachTo="body" and default.

![immagine](https://user-images.githubusercontent.com/6189813/213476438-f47d76ed-1d8d-4ca6-ae62-dec1563db128.png)

### Environment

Irrelevant

### Reproducer

https://stackblitz.com/edit/github-m7dwmq?file=src/app/app.component.ts

### Angular version

14.0.6

### PrimeNG version

14.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

Not applicable

### Expected behavior

I guess adding a max width to both panels and allowing item labels to wrap on whitespaces could help, since the panel is already scrollable vertically.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
