### ISSUE TITLE
"RangeError: Maximum call stack size exceeded" in p-table with whole table editing mode with pInputText cells

### ISSUE THREAD

**Issue by pavlov-leonid** [primefaces/primeng#12522]
We would like to make table with inline editing of whole table. 
We use p-table compopent with **editMode="row"** and **editingRowKeys** and set "true" for all table rows.

here stackblitz example based on standard primeng-tableedit-demo
https://stackblitz.com/edit/primeng-tableedit-demo-s9bz8h?file=src/app/app.component.ts

When row count is more than 132 (with 3 **pInputText** in each row) we get a lot of errors in browser console:
- RangeError: Maximum call stack size exceeded (Chrome)
- InternalError: too much recursion (Firefox)

PrimeNG v13 and v14 are affected by this issue.

Acording to stack trace it is some kind of recurtion in **InputText.ngAfterViewInit**...

What we do wrong? Maybe exists any workaroud or editMode="table" ?

**Comment by vandamb** [comment]
I encountered in fact the same issue (primeng 14.2.2) with a regular table (no editmode) containing 3 pInputText per row, from the moment the number of rows > 111. I could work around it by setting the pagination of the table to 100 (was 150).

**Comment by Vinar223** [comment]
I have the same problem.
Are there any solutions that do not involve reducing the number of inputs on the page?

**Comment by NM5Reimu** [comment]
Same
Does anyone already have a solution?

**Comment by mylifeandcode** [comment]
Having this issue in v16.0.2 as well.

**Comment by rd-joni** [comment]
Having this issue in v16.5.1 as well, cant use more than 100 inputs in the table.

**Comment by fortunes-guardian** [comment]
I have the same issue, without table, just a lot of inputs on one page. Debugged it down to: 'InputText.ngAfterViewInit' also.
I had to stop using the directive.

**Comment by gwartnes** [comment]
Same issue here. Version 15.2.0. Error is triggered somewhere between 370 ~ 560 rows, where each row has one `input` with the `pInputText` directive.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by hunhejj** [comment]
@mertsincan Unfortunately this is still an issue with latest 18.0.0-rc.2. I created a StackBlitz example demonstrating the issue: https://stackblitz.com/edit/stackblitz-starters-fkuj9z

**Comment by hanneslim** [comment]
Can also confirm, that the issue still persists. Would be good if someone reopens the issue!

**Comment by arthursaude** [comment]
Any updates on this? Im still getting the error on 18.0.2
