### ISSUE TITLE
Table component does not work as expected with row edit mode

### ISSUE THREAD

**Issue by WillooWisp** [primefaces/primeng#12528]
### Describe the bug

Your row edit sample for table component does not work. It should only be editable when editing the complete row, but all cells are individually editable without entering row edit.

### Environment

Stackblitz sample

### Reproducer

https://stackblitz.com/edit/primeng-tableedit-demo

### Angular version

15.1.1

### PrimeNG version

15.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.1

### Browser(s)

Chrome

### Steps to reproduce the behavior

Run your own stackblitz sample, https://stackblitz.com/edit/primeng-tableedit-demo

### Expected behavior

Table cells should only be editable when row is selected for editing.

**Comment by WillooWisp** [comment]
Anyone?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
