### ISSUE TITLE
Dropdown Filter not working for simple arrays like string[]

### ISSUE THREAD

**Issue by otonielguajardo** [primefaces/primeng#12521]
### Describe the bug

Dropdown does not work for simple arrays like string[]

https://user-images.githubusercontent.com/23427095/213288544-6124b8bb-7cf3-48fa-95ee-e7bda526ba37.mov

### Environment

macOS Ventura 13.0.1
Apple M1

### Reproducer

https://stackblitz.com/edit/primeng-dropdown-demo-f3wctg

### Angular version

15.0.0

### PrimeNG version

15.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.11.0

### Steps to reproduce the behavior

1. Pass array of strings to component's `[options]` property
2. Set `[filter]` property to `true`
3. Serve app
4. Click on component
5. Type name of any option from the array previously passed to `[options]` property

### Expected behavior

Search box should filter options succesfully

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
