### ISSUE TITLE
Table: header columns are shifting if tbody cell has long text inside

### ISSUE THREAD

**Issue by arozdobudko-incomm** [primefaces/primeng#12539]
### Describe the bug

When some tbody cell in a table has long text inside and you scrolling it, header columns are shifting. 

### Environment

Used the provided stackblitz template to reproduce the problem

### Reproducer

https://stackblitz.com/edit/primeng-tablegridlines-demo-xkdgah

### Angular version

15

### PrimeNG version

15

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14.2

### Browser(s)

Chrome 109.0.5414.75 

### Steps to reproduce the behavior

Go to the provided example, scroll down data in the table

**Comment by arozdobudko-incomm** [comment]
any updates?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
