### ISSUE TITLE
stateKey with variable and use the same table with more different datacources

### ISSUE THREAD

**Issue by zornic84** [primefaces/primeng#12534]
### Describe the bug

Hello,

when I specify a table with different data sources and use stateKey with a variable, the stateKey from both tables is stored mixed together when I switch back and forth between the data sources.
If I now set a filter on one table, the filter is also applied to the second data source and no data is displayed.

app.component.html:
` 
     <p-button` label="Load User" (click)="loadUser()" ></p-button>
     <p-button label="Load Test" (click)="loadTest()" ></p-button>
     
     
        <p-table #dt2 [columns]="_cols" [value]="_items" selectionMode="single" dataKey="id" styleClass="p-datatable-customers"
        [rows]="10" [paginator]="true" stateStorage="local" [stateKey]="_stateKey" (onStateSave)="onStateSave($event)">        
          <ng-template pTemplate="header" let-columns>
        <tr>
            <th *ngFor="let col of columns" [pSortableColumn]="col.field">
                {{col.header}}
                <p-sortIcon [field]="col.field"></p-sortIcon>
                <p-columnFilter [type]="col.type" [field]="col.field" display="menu"></p-columnFilter>
            </th>
        </tr>
    </ng-template>
    <ng-template pTemplate="body" let-rowData let-columns="columns">
    <tr [pContextMenuRow]="rowData" [pSelectableRow]="rowData">
        <td *ngFor="let col of columns">
            <ng-template *ngIf="col.field === 'Active';then boolField;else defaultField"></ng-template>
            <ng-template #boolField>
                <div><i class="pi" [ngClass]="{'true-icon pi-check-circle': rowData[col.field], 'false-icon pi-times-circle': 
                           !rowData[col.field]}"></i></div>
            </ng-template>
            <ng-template #defaultField>
                <div>{{ col.data ? (rowData[col.field]| date : col.format) : rowData[col.field] }}</div>
            </ng-template>
        </td>
    </tr>
          </ng-template>      
           <ng-template pTemplate="emptymessage">
            <tr>
                <td colspan="4">No data found.</td>
            </tr>
        </ng-template>
    </p-table>`

app.component.ts:
` 
  
  import { Component, OnInit, Input } from '@angular/core';
   
 @Component({
      selector: 'app-root',
      templateUrl: './app.component.html'
    })
   export class AppComponent { 
    public _cols: any[] = [];
    public _items: any[] = [];
    public _stateKey: string = "";

    constructor() { }
    ngOnInit() {
      this.loadUser();
    }
    public onStateSave(event: any) {
        console.log(event);
    }
    public loadUser(){
      this._stateKey = "loadUser";
      this._cols = [
        { field: 'Firstname', header: 'Vorname', type: 'text' },
        { field: 'Lastname', header: 'Nachname', type: 'text' },
        { field: 'UserName', header: 'Benutzername', type: 'text' },
        { field: 'Email', header: 'E-Mail', type: 'text' },
      ];
      
      this._items =[
        {Firstname: 'Max', Lastname: 'Mustermann', UserName: 'MMustermann', EMail: 'MMUstermann@asd.de'},
        {Firstname: 'Hans', Lastname: 'Wurst', UserName: 'HWurst', EMail: 'HWurst@asd.de'}
      ]
    }
    public loadTest(){
      this._stateKey = "loadTest";
      this._cols = [
        { field: 'name', header: 'Name', type: 'text' },
      ];
      this._items =[
        {name: 'Test01'},
        {name: 'Test02'},
        {name: 'Test03'},
        {name: 'Test04'},
        {name: 'Test04'},
      ]
    }
}
`

### Environment

VisualStudio Code 1.74.3

"dependencies": {
    "@angular/animations": "~15.1.0",
    "@angular/cdk": "~15.1.0",
    "@angular/common": "~15.1.0",
    "@angular/compiler": "~15.1.0",
    "@angular/core": "~15.1.0",
    "@angular/forms": "~15.1.0",
    "@angular/platform-browser": "~15.1.0",
    "@angular/platform-browser-dynamic": "~15.1.0",
    "@angular/router": "~15.1.0",
    "@angular/service-worker": "~15.1.0",
    "@auth0/angular-jwt": "^5.1.2",
    "@fullcalendar/angular": "6.0.3",
    "@fullcalendar/core": "^6.0.3",
    "@fullcalendar/daygrid": "^6.0.3",
    "@fullcalendar/interaction": "^6.0.3",
    "@fullcalendar/timegrid": "^6.0.3",
    "@fullcalendar/web-component": "^6.0.3",
    "@ngx-translate/core": "^14.0.0",
    "@ngx-translate/http-loader": "^7.0.0",
    "@videogular/ngx-videogular": "^7.0.1",
    "chart.js": "^4.2.0",
    "crypto-js": "~4.1.1",
    "file-saver": "^2.0.5",
    "ngx-doc-viewer": "^15.0.1",
    "primeflex": "^3.3.0",
    "primeicons": "^6.0.1",
    "primeng": "15.1.0",
    "prismjs": "1.29.0",
    "quill": "^1.3.7",
    "rxjs": "~7.8.0",
    "tslib": "^2.4.1",
    "zone.js": "~0.12.0"
  },

### Reproducer

https://stackblitz.com/edit/primeng-tablestate-demo-mymbvb?file=src/app/app.component.ts

### Angular version

15.1.1

### PrimeNG version

15.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

19.4.0

### Browser(s)

Chrome109

### Steps to reproduce the behavior

Add my code into your example and click on buttons and se what happend...
https://stackblitz.com/edit/primeng-tablestate-demo-mymbvb?file=src/app/app.component.ts

In filter you can see all filters "Firstname", "Lastname", "UserName", "Email" AND unfortunately "name"

{
    "first": 0,
    "rows": 10,
    "filters": {
        "Firstname": [
            {
                "value": null,
                "matchMode": "startsWith",
                "operator": "and"
            }
        ],
        "Lastname": [
            {
                "value": null,
                "matchMode": "startsWith",
                "operator": "and"
            }
        ],
        "UserName": [
            {
                "value": null,
                "matchMode": "startsWith",
                "operator": "and"
            }
        ],
        "Email": [
            {
                "value": null,
                "matchMode": "startsWith",
                "operator": "and"
            }
        ],
        "name": [
            {
                "value": "04",
                "matchMode": "endsWith",
                "operator": "and"
            }
        ]
    }
}

### Expected behavior

I expect that the filters are applied cleanly to the columns that are also present or that the filters of both data sources are not connected when saving the filters.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
