### ISSUE TITLE
ContextMenu | triggerEvent="click" does not have any effect

### ISSUE THREAD

**Issue by cetincakiroglu** [primefaces/primeng#12532]
The trigger event is broken

**Comment by nathanvj** [comment]
I tried to reproduce in Stackblitz, and noticed it was working fine with PrimeNG v13.

However after upgrading to v14, it does not work anymore. You can find the Stackblitz [here](https://stackblitz.com/edit/primeng-contextmenu-demo-ppq72k?file=src/app/app.component.html).

In the Stackblitz I mention 3 issues:

- Issue 1: Click trigger event not working
- Issue 2: Manually open context menu through ViewChild not working
- Issue 3: Manually open TieredMenu through ViewChild not working
