### ISSUE TITLE
Password | Add maxlength

### ISSUE THREAD

**Issue by mkumar92** [primefaces/primeng#12531]
### Describe the bug

<p-password [maxlength]="20" (keydown.space)="$event.preventDefault();"
          [toggleMask]="true" [inputStyleClass]="'form-control'" [styleClass]="'w-100 verifyPassword__input'"></p-password>

### Environment

dev

### Angular version

14.0.7

### PrimeNG version

14.2.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v16.15.0

### Expected behavior

need to stop entering more than max limit.

**Comment by cetincakiroglu** [comment]
Hi,

**maxlength** is not an input property of **p-password**. This feature does not exist, so I've changed the topic and labelled as new feature.
