### ISSUE TITLE
TabView - <p-tabView>

### ISSUE THREAD

**Issue by vikore** [primefaces/primeng#12544]
### Describe the bug

Accessibility issue - 
Keyboard enter key event is not calling onTabChange event of p-tabView while it is working for tab switch event when it is used with ng-template <ng-template pTemplate="header">. On mouse click event onTabChange event is getting called. As like mouse click event similar behavior is expected with keyboard enter key event when focus is on tab. 

HTML-
<p-tabView>
    <p-tabPanel>
        <ng-template pTemplate="header">
            <a  (click)="onTabChange($event, 0)"></a>
        </ng-template>
    </p-tabPanel>
</p-tabView>

### Environment

Development

### Angular version

13.3.8

### PrimeNG version

13.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.1

### Steps to reproduce the behavior

1. Navigate to any tab in the tabPanelHeader of tabView using keyboard tab key navigation
2. Hit enter key on the keyboard when focus is on the tab
3. Observe the tabPanel details change but onTabChange  event is not called.

### Expected behavior

onTabChange event should be called on keyboard enter key event

**Comment by mehmetcetin01140** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.
