### ISSUE TITLE
More Dynamic Dialogue Features

### ISSUE THREAD

**Issue by Stankman** [primefaces/primeng#12548]
### Describe the feature you would like to see added

It'll be cool to customize Dynamic Dialogue Footer Template and add the option to block/unblock scroll just like the classic dialogue.

### Describe the solution you'd like

For the scroll block just add the same boolean just as the normal dialogue.

For custom footer template add more events to send info from Child to Parent whenever clicking into a button in case there's one.

**Comment by cetincakiroglu** [comment]
Hi @RodolfoXDR 

Good idea, thanks for suggestion

**Comment by Stankman** [comment]
Hopefully I get to see this in the next version:) I'm still waiting for this feature

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
