### ISSUE TITLE
pDraggable="one" fires events on pDroppable="two"

### ISSUE THREAD

**Issue by tmc101** [primefaces/primeng#12540]
### Describe the bug

Hi

When I drag ```<div pDraggable="one">``` over ```<div pDroppable="two">``` the onDragEnter and onDragLeave events fire.

Also, the ```p-draggable-enter``` class is added to ```<div pDroppable="two">```

Here's the result of dropping DRAG1 on to DROP2:
![image](https://user-images.githubusercontent.com/11647741/213702895-4e25dbf1-056a-4133-a9a6-b24eeafe92cd.png)

This issue was mentioned before - but the problem still persists in the PrimeNg 15.1.0:

https://github.com/primefaces/primeng/pull/11344#issuecomment-1082786999

### Environment

Windows 10.

### Reproducer

https://github-sclhxh.stackblitz.io

### Angular version

15.1.0

### PrimeNG version

15.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.15.1

### Steps to reproduce the behavior

Drag and drop the DRAG1 div on to the DROP2 div in the stackblitz example.

### Expected behavior

I would expect no interaction between pDraggable="one" and pDroppable="two" elements.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
