### ISSUE TITLE
Issue with table that has virtual scrolling and lazy loading

### ISSUE THREAD

**Issue by monkey-jhe** [primefaces/primeng#12547]
### Describe the bug

In the demo table for virtual scrolling with lazy loading the table doesn't always trigger the lazy load event properly.

### Environment

.

### Reproducer

https://stackblitz.com/edit/primeng-tablevirtualscroll-demo-ptfsgv?file=src/app/app.component.html

### Angular version

15.1.0

### PrimeNG version

15.1.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.13.2

### Steps to reproduce the behavior

1. Jump to a lower part of the table (quickly drag the scrollbar) so that many virtual pages are above and below the newly loaded data
2. Wait for the loading to finish 
3. Scroll up to trigger the lazy loading and wait for it to finish multiple times
4. After 2-5 times of triggering the lazy loading it gets stuck loading data and doesn't trigger the lazy loading event

### Expected behavior

When you jump to a lower part of the table the lazy loading event should be triggered properly every time you scroll past a certain amount of rows.

**Comment by JohannesBeiserSG** [comment]
I notices the same problem. 
It can easily be reproduced in the [official current Stackblitz example](https://stackblitz.com/run?file=package.json) by changing scrollHeight to something like 750px. 

Scrolling down fast using the scrollbar, you can see at the border of a lazy-load block of 100 that the skeleton is waiting to be filled with entries but the lazyLoadEvent only triggers for the skeleton-rows if you scroll further up (in the middle of the empty 100-element block). But thats too late.
