### ISSUE TITLE
Dropdown: overlay with appendTo="body" did not scroll to already selected item

### ISSUE THREAD

**Issue by grozdanova** [primefaces/primeng#12551]
### Describe the bug

When dropdown appendTo="body" is set, then did not scroll me to selected item and I should scroll again to find it.
I saw in code, that in onOverlayAnimationStart() --> this.itemsWrapper = null, because can`t find '.p-dropdown-items-wrapper'.
If I don`t specify appendTo, it works correctly.

### Environment

primeng v 15.0.1

### Reproducer

https://stackblitz.com/edit/github-yswjwo?file=src/app/app.component.ts

### Angular version

15

### PrimeNG version

15.0.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16

### Steps to reproduce the behavior

1. Select last option in dropdown 
2. Open again options overlay
3. Bug - didn`t scroll me automatically to selected option

### Expected behavior

To scroll me automatically to selected option

**Comment by cghislai** [comment]
this is fixed in v15.1.1
