### ISSUE TITLE
Component: p-calendar in p-inputgroup have border-radius, thus not following the p-inputgroup styling

### ISSUE THREAD

**Issue by LouLeGrain** [primefaces/primeng#12558]
### Describe the bug

When putting a `<p-calendar>` in a `.p-inputgroup`, the `<input>` element of the p-calendar have borders.

See my stackblitz screen capture

![p-calendar border bug](https://user-images.githubusercontent.com/9808953/214846541-20ab2ee8-eb5b-4609-b241-482e4e753d5f.png)

If somebody encounters this bug, i have included, as you can see, some workarounds [in the stackblitz](https://stackblitz.com/edit/primeng-inputgroup-demo-yn5wak?file=src/app/app.component.html)

### Environment

My package.json :
```json

"dependencies": {
    "@angular/animations": "^14.0.5",
    "@angular/cdk": "^13.3.3",
    "@angular/common": "^14.0.5",
    "@angular/compiler": "^14.0.5",
    "@angular/core": "^14.0.5",
    "@angular/forms": "^14.0.5",
    "@angular/google-maps": "^14.2.3",
    "@angular/platform-browser": "^14.0.5",
    "@angular/platform-browser-dynamic": "^14.0.5",
    "@angular/router": "^14.0.5",
    "@angular/service-worker": "^14.0.5",
    "@ngx-translate/core": "^14.0.0",
    "@types/w3c-web-usb": "^1.0.4",
    "angular-gridster2": "^14.0.0",
    "file-saver": "^2.0.5",
    "primeflex": "^3.0.0",
    "primeicons": "^6.0.0",
    "primeng": "^14.2.3",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "xlsx": "^0.18.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^14.0.5",
    "@angular-eslint/builder": "^14.0.0-alpha.4",
    "@angular-eslint/eslint-plugin": "^14.0.0-alpha.4",
    "@angular-eslint/eslint-plugin-template": "^14.0.0-alpha.4",
    "@angular-eslint/schematics": "^14.0.0-alpha.4",
    "@angular-eslint/template-parser": "^14.0.0-alpha.4",
    "@angular/cli": "^14.0.5",
    "@angular/compiler-cli": "^14.0.5",
    "@angular/language-service": "^14.0.5",
    "@angular/localize": "^14.0.5",
    "@types/file-saver": "^2.0.5",
    "@types/jasmine": "~3.10.0",
    "@types/node": "^12.20.55",
    "@typescript-eslint/eslint-plugin": "^5.29.0",
    "@typescript-eslint/parser": "^5.29.0",
    "eslint": "^8.18.0",
    "jasmine-core": "~4.0.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.1.0",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "typescript": "^4.7.4"
  }

```

### Reproducer

https://stackblitz.com/edit/primeng-inputgroup-demo-yn5wak?file=src/app/app.component.html

### Angular version

14.0.5

### PrimeNG version

14.2.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.9.0

### Browser(s)

Chrome Version 109.0.5414.119 (Official build) (arm64)

### Steps to reproduce the behavior

1. Create a div with the `.p-inputgroup` class
2. Put a first `.p-inputgroup-addon` in it
3. Then a `<p-calendar>`

### Expected behavior

The p-calendar `<input>` should have borders depending on the surrounding  `.p-inputgroup-addons`

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Comment by pynadium** [comment]
Hello, this is still an issue in v19

**Without workaround:**

```
        <p-input-group class="w-full ">
            <p-inputgroup-addon><i class="pi pi-calendar"></i></p-inputgroup-addon>
            <p-date-picker formControlName="dateFrom" class="w-full" [showIcon]="false"></p-date-picker>
        </p-input-group>
```

**With workaround:**

```
        <p-input-group class="w-full">
            <p-inputgroup-addon><i class="pi pi-calendar"></i></p-inputgroup-addon>
            <p-datePicker formControlName="dateTo" class="w-full flex-workaround"></p-datePicker>
        </p-input-group>
```


**Component css:**
```
.flex-workaround {
    display: flex !important;
    flex: 1 1 auto;
    width: 1% !important;
    align-items: center;

}
```
**Result:** 
![Image](https://github.com/user-attachments/assets/de0e075c-d555-4482-b941-ac90732ef7d3)



In global styles.css you can also fix the boarder integration between the `<p-input-group-addon>` and the `<p-datepicker>` 
(or use in the component css class with ::ng-deep

.p-inputgroup .p-inputtext {
    border-start-end-radius: 6px;
    border-end-end-radius: 6px;
    border-end-start-radius: 0;
    border-start-start-radius: 0;
}

**Workaround Result:**

![Image](https://github.com/user-attachments/assets/22320712-b6d1-4f2f-a5bb-5e6d36d51570)

The width problem arises when using both display: grid and display:flex styles.
The root cause is the (superflous?) `<span>  `child of the `<p-datepicker>` cannot apply flex: 1 1 auto because :

> The display: block property on the parent element prevents flex from having an effect.
Try setting the display: block property on the parent to display: flex.

From chrome developer tools:
.p-inputgroup .p-inputtext, .p-inputgroup .p-inputwrapper {
    flex: 1 1 auto;  <--- this is not applied
    width: 1%;
}
