### ISSUE TITLE
Calendar: The year options have blank labels when no date has been selected, yet

### ISSUE THREAD

**Issue by pgkavogiannis** [primefaces/primeng#12552]
### Describe the bug

While opening a `<p-calendar/>` date picker (selection mode = range), the year options seem to exist, but there are not labels for them

![image](https://user-images.githubusercontent.com/59098876/214609405-29eff0f3-3f17-45b8-8a79-531d70e42c2c.png)

### Environment

Operating system: Windows 10 Pro
IDE: Webstorm
Package manager: yarn, node

### Angular version

15.0.3

### PrimeNG version

15.0.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.19.0

### Browser(s)

Firefox v109.0

**Comment by pgkavogiannis** [comment]
There is not an error control handling for non-valid values in the `isYearSelected()` method in the following line: https://github.com/primefaces/primeng/blob/master/src/app/components/calendar/calendar.ts#L1364 where accessing `this.value[0]`

**Comment by sajimavelil** [comment]
Support expecting for this problem

**Comment by sebastianamaro** [comment]
Same issue here

![image](https://github.com/primefaces/primeng/assets/1429677/7242f8eb-1e22-4ce3-b05b-682f0a019d4f)

Chrome Version 114.0.5735.199

PrimeNG version:  "primeng": "^15.2.0",

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
