### ISSUE TITLE
DataTable not working in IE working fine in chrome and other browsers

### ISSUE THREAD

**Issue by deephakdd** [primefaces/primeng#1256]
Unable to get property 'add' of undefined or null reference
getting the above error

**Comment by kcsahoo** [comment]
I also found a problem in IE and Firefox.
The row select and unselect works fine in Chrome but not in IE or Firefox.
Can this resolution be included in next release as IE is mostly used in most organisations?

**Comment by kcsahoo** [comment]
The select and unselect in single selection mode has totally broken and is erratic across Chrome/IE/Firefox.
PrimeNG team has agreed to look in to it. Let us hope they fix all data table issues across all three browsers before they release RTM

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/VZbdZfQ7SuTV87tTkbYR

**Comment by mertsincan** [comment]
Hi @deephakdd and @kcsahoo,
I couldn't replicate this issue with 4.0.2. My test codes;
http://localhost:4200/#/datatable/selection
