### ISSUE TITLE
Component: Table, I wan't to discriminate which filters are really defined or not

### ISSUE THREAD

**Issue by EmilianoElMariachi** [primefaces/primeng#12569]
### Describe the feature you would like to see added

In the Table component, I wan't to be able to discriminate which filters are really set or not.
Actually, the "LazyLoadEvent.filters" object contains a FilterMetadata for each column whatever a filter is defined or not for the column.
Nevertheless when no filter is specified on a column, I noticed that the FilterMetadata.value is null, which is actually for me the only way to detect if a filter is specified or not. Unfortunately, in some use cases a null value can be an explicit filter value, so in the case we are not able to discriminate if the user wants to set an explicit filter with the null value or if the user didn't set any specific filter.

### Is your feature request related to a problem?

No

### Solution 1
Removed unfiltered columns from LazyLoadEvent.filters object.
This solution would be a breaking change (not the best option from my point of view).

### Solution 2
Add an extra boolean property on FilterMetadata to indicate is filter is active or not. Example: FilterMetadata.active

### Describe alternatives you have considered

I don't have any alternative to this problem.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
