### ISSUE TITLE
clear selected checkboxes using code

### ISSUE THREAD

**Issue by yxtao** [primefaces/primeng#12560]
### Describe the feature you would like to see added

Clear selected checkboxes to make all checkboxes to be unselected with code in Angular component.ts file when use primeng p-table.

**Comment by cghislai** [comment]
you can just instantiate a new selection array, which you bind to your table selection value.

See https://stackblitz.com/edit/primeng-tableselection-demo-2eyv15?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html (bottom of the page) for an example.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
