### ISSUE TITLE
Autocomplete: Issue with Virtual Scroll

### ISSUE THREAD

**Issue by Wykks** [primefaces/primeng#12568]
### Describe the bug

When using virtual scroll, the results show once, then after clear and any other query, it doesn't work anymore.

### Environment

primeNG v 15.1.1

### Angular version

15.1.2

### PrimeNG version

15.1.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

NA

### Steps to reproduce the behavior

In the autocomplete with Virtual Scroll here https://primeng.org/autocomplete#virtualscroll

Type : "i"
Then clear the input
Type : "m" (which show nothing as expected)
Then clear the input
Then type "i" ==> Bug

**Comment by denny99** [comment]
<img width="522" alt="image" src="https://user-images.githubusercontent.com/1826849/217786692-8f079fa1-6c06-4922-90f1-52c451e6a3e6.png">

I can confirm this. The first time it works. Then it stops working. After some more typing the results will appear again. Kind of random

**Comment by hamzajazyri** [comment]
Hello @cetincakiroglu !  Could  you please take a look at the [PR](https://github.com/primefaces/primeng/pull/12619). Thank you!
