### ISSUE TITLE
Sidebar: onHide ist emitted twice

### ISSUE THREAD

**Issue by m11t** [primefaces/primeng#12564]
### Describe the bug

When closing a sidebar the onHide EventEmitter is emitted twice:
1. Through the `close` function call
2. Through the `onAnimationEnd` function

### Environment

-

### Reproducer

https://github-2usv44.stackblitz.io

### Angular version

at least since 13

### PrimeNG version

at least since 13.0.4

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

11.0.4

### Steps to reproduce the behavior

1. Click on the button with the arrow
2. Close the sidebar by either clicking on on the background mask or the close button (x)

### Expected behavior

The onHide should only be emitted once.

**Comment by lf-novelt** [comment]
the "fix" seems to have broken the "onHide" output property.
it's not called anymore when not binding the visible property event listenir

```
<p-sidebar [visible]="displayApprovalDialog !== null" position="right" [style]="{width: '30em'}"
  (onHide)="onHideApprovalDialog($event)" [showCloseIcon]="true">
```

emit = false so it does not call it from the close event anymore. 
<img width="489" height="249" alt="Image" src="https://github.com/user-attachments/assets/46296545-d97b-4049-8881-47bbab07f6f9" />

The `onHide` action was the thing that was closing the sidebar for me
