### ISSUE TITLE
Autocomplete inputStyle/inputStyleClass doesn't work for multiple mode

### ISSUE THREAD

**Issue by stalky14** [primefaces/primeng#1257]
When passing in the class required for the 'inputStyleClass' attribute in autocomplete element, the class does not get applied. 
Inspector shows that the class is applied to the "class" of the input but the "ng-reflect-ng-class" returns [object Object].

I would have expected "ng-reflect-class-name" to then refer to the class.

**Comment by jock-dalby** [comment]
I found on version 2.0.5 using autocomplete, inputStyleClass works fine for non-multiple inputs but not for multiples. I upgraded and tried on version 4 but still not working. Instead it just attaches the given class name to 'inputstyleclas's and' ng-reflect-input-style-class' attributes on the p-autocomplete element. Is this the intended behaviour? Is there a different approach for targeting the input element while allowing multiple selections?
