### ISSUE TITLE
Dropdown: Add browser autofill support

### ISSUE THREAD

**Issue by mpschaeuble** [primefaces/primeng#12576]
### Describe the feature you would like to see added

Native HTML dropdowns support the "autocomplete" attribute. This is quite handy in some forms, e.g. to automatically select the country in a dropdown of countries by the browsers autofill feature. The primeng-dropdown component however does not seem to support this feature.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
