### ISSUE TITLE
autoComplete: (v15.1.1) ExpressionChangedAfterItHasBeenCheckedError errors are thrown when used in overlays

### ISSUE THREAD

**Issue by cghislai** [primefaces/primeng#12573]
### Describe the bug

When an autocomplete component is placed in an p-overlay panel, then selecting the value with the mouse triggers an `ExpressionChangedAfterItHasBeenCheckedError` error.

This issue only appears to occur when the autocomplete component is placed in an overlayPanel component, and when the value is selected using a mouse click.

This is a regression from version 15.0.1, which does not have this behaviour.

v15.1.1 (failing) reproducer: https://stackblitz.com/edit/github-7g4tg5?file=package.json,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fmodel.ts,src%2Fapp%2Fapp.component.html

v15.0.1 (working) reproducer: https://stackblitz.com/edit/github-7g4tg5-dvj7mj?file=package.json,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fmodel.ts,src%2Fapp%2Fapp.component.html

### Environment

angular 15
primeng 15
stackblitz

### Reproducer

https://stackblitz.com/edit/github-7g4tg5?file=package.json,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fmodel.ts,src%2Fapp%2Fapp.component.html

### Angular version

15.1.1

### PrimeNG version

15.1.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16

### Browser(s)

chromium

### Steps to reproduce the behavior

from the reproducer:
1. click on the bordered div to display the overlay
2. select a value using the mouse

actual behaviour: 
- the value is selected
- the overlay is hidden
- an error is thrown

### Expected behavior

- the value is selected
- the overlay is not hidden
- no error is thrown

**Comment by cetincakiroglu** [comment]
Hi,
We've introduced a new component called "overlay" to eliminate defects such as in this case.
Please use the new **p-overlay** component instead of overlayPanel, it's extended and more powerful component compared to overlayPanel. Here is the refactored version of your example with p-overlay. 

https://stackblitz.com/edit/github-7g4tg5-wmyaiy?file=src%2Fapp%2Fapp.component.html

**Comment by cghislai** [comment]
thanks, it seems to work fine indeed.

For reference, here is an example where the `p-overlay` component does not hide when clicking the nested `p-autocomplete` overlay: https://stackblitz.com/edit/github-7g4tg5-um1csv?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

Instead of attaching the autocomplete overlay to the body component, the autocomplete element is wrapped inside a named div preventing the click event to bubble, and the autocomplete overlay is appended to it to fix styling.
