### ISSUE TITLE
Tooltip arrow is broken

### ISSUE THREAD

**Issue by VictoriaKalakustava** [primefaces/primeng#12579]
The issue is actual for all tooltip positions except right. On the scale 110% and 125% the tooltip arrow separated from body by white line. Reproduced on primeng documentation examples, so looks like it is not depends on my code.
I am using Chrome Version 109.0.5414.120 (Official Build) (64-bit)

Try yourself
https://www.primefaces.org/primeng/tooltip
![image](https://user-images.githubusercontent.com/17678017/215513073-49da7ea0-94f4-4d4e-a2bf-5fa4787a75e2.png)

**Comment by martinszeltins** [comment]
Same issue on PrimeVue
