### ISSUE TITLE
primeng calendar year view not work with *maxDate* and *minDate* not working 

### ISSUE THREAD

**Issue by ashikjs** [primefaces/primeng#12583]
### Describe the bug

![image](https://user-images.githubusercontent.com/13074235/215689938-55cddd66-0192-4f2a-9397-ed616e3ad406.png)

It's my code  use 

`
 ```
 currentDate: Date = new Date()

 <p-calendar formControlName="date"
              appendTo="body" view="year" dateFormat="yy"
              [minDate]="currentDate"
  ></p-calendar>
And 
 <p-calendar formControlName="date"
              appendTo="body" view="year" dateFormat="yy"

              [maxDate]="currentDate"
  ></p-calendar>
```
`

Anyone of those date not disable those previous or future date but if user click future date then it automatic select current years.

### Environment

**Angular 15.0.4
primeng: ^15.0.1**

### Angular version

15.0.4

### PrimeNG version

15.0.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v18.13.0

### Browser(s)

Chorme, firfox

### Expected behavior

It should be disable future date if i set maxDate current date and it should be disable previous date if i set minDate current Date

**Comment by JohannesPertl** [comment]
Any updates with this issue? It's an annoying bug and should be an easy fix

**Comment by mertsincan** [comment]
Hi @JohannesPertl,

Could you please try the fix at https://github.com/primefaces/primeng/pull/12154? If ok for you, I'll merge it asap after it is updated.

Best Regards,
