### ISSUE TITLE
Component: Loading propertie does not works on <button> tag, only on <p-button>

### ISSUE THREAD

**Issue by RichardCar** [primefaces/primeng#12582]
### Describe the bug

when uses loading propertie on <button> tag, it's works but when loading has finished, button looks like disabled. 
However, on <p-button> component works fine.

### Environment

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 15.1.1
Node: 16.13.2
Package Manager: npm 8.1.2
OS: win32 x64

Angular: 15.1.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... google-maps, platform-browser, platform-browser-dynamic
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.1
@angular-devkit/build-angular   15.1.1
@angular-devkit/core            15.1.1 (cli-only)
@angular-devkit/schematics      15.1.1 (cli-only)
@angular/cli                    15.1.1
@angular/fire                   7.5.0
@schematics/angular             15.1.1 (cli-only)
rxjs                            7.8.0
typescript                      4.9.4
"primeng": "15.0.1",

### Angular version

15.1.1

### PrimeNG version

15.0.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.13.2

**Comment by ridy01-backup** [comment]
Did you try it on PrimeNG 15.1.1?

**Comment by BeGj** [comment]
I have the same problem. It works for p-button component but not for the pButton directive. It previously worked on primeng and angular 14.
Currrently tested on primeng 15.4.1 and angular 15.2.8.

The loading icon keeps spinning even if the property was initiated as false and never changed.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
