### ISSUE TITLE
p-chips component allows duplicate values if there are trailing spaces in the text even though 'allowDuplicate' is set to false. 

### ISSUE THREAD

**Issue by andy14312** [primefaces/primeng#12594]
![image](https://user-images.githubusercontent.com/13926547/216259981-904f91b2-72b5-4dfa-951e-42394a4bf02a.png)

**Comment by pritam-chowdhury** [comment]
@andy14312 does it even work without trailing spaces??? Below i have attached my stackblitz
https://stackblitz.com/edit/primeng-chips-demo-b7f3jr?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts
It has exact same values in array and allowDuplicate is also set to false...still it showing Both the values
