### ISSUE TITLE
TreeSelect: p-treeSelect panel is getting detached from input container 

### ISSUE THREAD

**Issue by miranda18** [primefaces/primeng#12592]
### Describe the bug

When using p-treeSelect I am getting an issue of the panel getting detached from the input container. This issue is persisting even in the newest version.

For reference, this is the issue I had opened previously: https://github.com/primefaces/primeng/issues/11825

I was able to reproduce again within the documentation, with the same steps mentioned in the previously opened issue.

![image](https://user-images.githubusercontent.com/17749621/216124715-42fc38c7-6bac-4878-87be-cc8fc6680381.png)

![image](https://user-images.githubusercontent.com/17749621/216124754-a7f9a1df-9acc-49fe-822f-896daee88d61.png)

<img width="350" alt="image" src="https://user-images.githubusercontent.com/17749621/216125556-2976af36-a244-43d9-805c-6fcc41b872b0.png">

### Environment

Angular 13, Primeng 13.4.1, Chrome (latest version)

### Reproducer

https://stackblitz.com/edit/primeng-treeselect-demo?file=src%2Fapp%2Fapp.component.html

### Angular version

13.3

### PrimeNG version

13.4.1, 15.2.0 

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.1

### Browser(s)

Only tested on Chrome and Edge

### Steps to reproduce the behavior

1. In the Multiple dropdown example, expand the different options (order I used: documents -> events -> movies):
2. Click out of the filter
3. Open filter again 
4. Collapse the options (order I used: movies -> events -> documents)

### Expected behavior

The expected behavior is that the panel stays attached to the filter container

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by autonomobil** [comment]
Still happening, please re-open

https://github.com/user-attachments/assets/d6ac123c-4f5c-4d64-b6ad-07a400130793

**Comment by Gauravs734** [comment]
![Image](https://github.com/user-attachments/assets/3abbcd1b-241f-4286-8b72-35e9dc28b3d6)
Still the issue persists in version 19 of the p-treeSelect. The dropdown window is getting from the component as shown in the image.
