### ISSUE TITLE
Chart is not defined error

### ISSUE THREAD

**Issue by murathazer** [primefaces/primeng#126]
when we try to use doughnutChart component following error occurs;

```
angular2.dev.js:23730 ReferenceError: Chart is not defined
    at DoughnutChart.initChart (http://localhost:8080/node_modules/primeng/components/chart/doughnutchart/doughnutchart.js:91:30)
    at DoughnutChart.ngAfterViewInit (http://localhost:8080/node_modules/primeng/components/chart/doughnutchart/doughnutchart.js:62:14)
    at AbstractChangeDetector.ChangeDetector_FrontPageComponent_0.afterViewLifecycleCallbacksInternal (viewFactory_FrontPageComponent:119:82)
    at AbstractChangeDetector.afterViewLifecycleCallbacks (http://localhost:8080/node_modules/angular2/bundles/angular2.dev.js:9924:12)
```
```
"angular2": "2.0.0-beta.11",
"primeng": "^0.8.1",
"primeui": "^4.1.5"
```

**Comment by cagataycivici** [comment]
Welcome to PrimeNG, you also need to add charts.js to your page.

**Comment by Faigjaz** [comment]
I've got the same Problem. chart.js implemented before angular-chartjs. 

Chart is not defined. Error occurs within my .html.

**Comment by abbas-innotical** [comment]
@cagataycivici 
Could you please give a working example of chart using primeng ? 
and from where we have to add chart.js ?

**Comment by Leezheng357** [comment]
@abbas-innotical 
Could you please give a working example of chart using primeng ? 
and from where we have to add chart.js ?

**Comment by mornir** [comment]
I would also like to see a working example of chart using primeng in order to see how to add it.

**Comment by bomberblue07** [comment]
Y'know, the fact you have to import Chart.js isn't really mentioned on the showcase...

**Comment by dyrleif** [comment]
wow thank you , I would never have found this out.

**Comment by merlosy** [comment]
Hi!
I am working with angular (v2+) in Typescript, I added:
````
npm install --save chart.js
npm install --save-dev @types/chart.js
```

**Comment by intergleam** [comment]
is there a way to load via `angular cli`? kinda sucks putting <script> tag in the index

**Comment by cagataycivici** [comment]
Yes;

 "scripts": [
          "../node_modules/chart.js/dist/Chart.js",
          //..others
      ],

**Comment by intergleam** [comment]
it doesn't work this way may be because the scripts are loaded at the bottom of the page

**Comment by cagataycivici** [comment]
It works for me;

https://www.primefaces.org/ultima-ng/#/charts

**Comment by intergleam** [comment]
hm yeah that works indeed https://github.com/intergleam/test-primeng

**Comment by eheb** [comment]
In .angular-cli.json  i add :+1: "scripts": [
          "../node_modules/chart.js/dist/Chart.js"
      ],
I get this issue : ERROR in multi script-loader!./~/chart.js/dist/Chart.js
Module not found: Error

**Comment by eheb** [comment]
@cagataycivici where can i find the to chart docs in your post on 11 march ?

**Comment by jwiesmann** [comment]
I had a similar issue <code>ReferenceError: Chart is not defined</code> funny thing was, that i had to change the order of how my javascript was loaded (same issue i had before with quill.js)

What i did: 
added `ChartModule` to my module.ts (plus imports)

installed chart.js
<code>
npm install --save chart.js
npm install --save-dev @types/chart.js
</code>
added script to `.angular-cli.json`

**NOT WORKING** (in `.angular-cli.json`)
<code>
        "../node_modules/quill/dist/quill.js",
        "../node_modules/angular2-indexeddb/angular2-indexeddb.js",
        "../node_modules/chart.js/dist/Chart.bundle.js"
</code>
**WORKING** (in `.angular-cli.json`)
<code>
        "../node_modules/quill/dist/quill.js",

        "../node_modules/chart.js/dist/Chart.bundle.js",
        "../node_modules/angular2-indexeddb/angular2-indexeddb.js"
</code>

I do not really have an idea why it is like that... but that worked for me..

**Comment by mahesh5b5** [comment]
@jwiesmann  thanks ! :)

**Comment by borriej** [comment]
Thanks! The docs should really be updated about installation. I only needed ng prime charts and ran into the same issue. @kosnet2  solution for the win
