### ISSUE TITLE
p-autocomplete: baseZIndex, autoZIndex, appendTo not respected

### ISSUE THREAD

**Issue by JanST123** [primefaces/primeng#12600]
### Describe the bug

p-autocomplete does not respect the properties `baseZIndex`, `autoZIndex`, `appendTo` nor is the new `overlayOptions` passed to `p-overlay`. It's just missing in the code.

### Environment

primeng@15, angular 15

### Angular version

15.1.3

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.21.2

### Steps to reproduce the behavior

```html
 <div style="height: 100px; overflow: hidden">
     <p-autoComplete
        [suggestions]="options"
        [baseZIndex]="1500"
        appendTo="body"
    ></p-autocomplete>
 </div>
```

### Expected behavior

The overlay should be appended to the body with a z-Index >= 1500 so it is visible even if the containing div is overflow:hidden

**Comment by silviu-ciobanu** [comment]
same issue

**Comment by webwerkerio** [comment]
same issue here

**Comment by oleg-varlamov** [comment]
We have the same problem - overlayOptions are not applied to the overlay. We have to change the styles directly to get around the problem.

**Comment by anurgaly** [comment]
I have same problem...

**Comment by JanST123** [comment]
The problem is still existing in primeNG 16.0.2 ... 

Please could someone merge the PR https://github.com/primefaces/primeng/pull/12601 ? So we don't have to build our own packages for this simple fix...
