### ISSUE TITLE
rc.4 has broken Datatable select/unselect functionality

### ISSUE THREAD

**Issue by kcsahoo** [primefaces/primeng#1260]
After I upgraded to rc.4, the select/unselect functionality does nopt work.
Please see your own showcase example.
It was working in rc.3

Pl check this functionality:
In single mode, a row is selected on click event of a row. If the row is already selected then the row gets unselected.

**Comment by kcsahoo** [comment]
Can this functionality be checked in your own showcase example with Chrome/Firefox and IE?
Thanks in advance for your help before RTM is released on 14 Nov 2016 as published.

**Comment by dzhavat** [comment]
Unfortunately it seems that multiple selection is broken as well.

**Comment by ctrl-brk** [comment]
And I personally would prefer 'unselect' only in multi select mode. In single mode the selection should only change when you click on the other row, not on the same one.

**Comment by kcsahoo** [comment]
If you see other users' concerns, the desired behaviour should be different for single and multiple selections.
Meta Key with click is only used in multiple select cases as a standard and single selection is by single click  toggle.

**Comment by kcsahoo** [comment]
If you have only one row in the table, how do you unselect?
rc.3 had the right functionality and should be restored.

**Comment by ctrl-brk** [comment]
Don't select it in the first place ;) Really, why do you need to unselect a single item?

**Comment by derchirurg** [comment]
I need unselect in my application, because then the view changes and hides information. The solution like in rc.3 was nice, it would be great if you can bring it back.

**Comment by ctrl-brk** [comment]
derchiurg, so you have a list with let's say one item. You click on this item and some details appear. You click one more time and details disappear. On and off on the same view, nothing else happens. I can't remember any grid acting this way.

**Comment by kcsahoo** [comment]
I use select and unselect events for enabling and disabling certain buttons on the page and clear/clone some objects. It all depends on your application requirements. It was a feature earlier which is not working after rc.4.

**Comment by derchirurg** [comment]
@ctrl-brk this is for editing rows. I can not explain it in total, it is a requirement. Nevertheless it depends on the usecase, if you don't need it, you don't have to use it. As @kcsahoo mentioned: it worked earlier and I need to use it.

**Comment by dzhavat** [comment]
I also work on an app that depends on selecting and unselecting rows, because I use it to show some buttons. After rc.4 this behavior is broken. I also noticed that it is not possible to select multiple rows just by clicking on them (as it was before).

**Comment by cagataycivici** [comment]
This has been discussed before, this is by design, on non-touch devices use metakey+ctrlkey and on touch devices use click/tap, for previous discussions;

https://github.com/primefaces/primeng/issues/794

The metakey/ctrlkey implementation is based on operating system such mac or windows which users are familiar with. On mobile devices, datatable switches to tap based selection without keys as they don't exist. We'll keep monitoring further feedback, we might introduce attributes to make this customizable in future right now we could not replicate a bug.

**Comment by ctrl-brk** [comment]
May be it can be configurable in some way? Select/unselect, keys/mouse etc.

**Comment by saridakis** [comment]
I have the some issue here. On a 'VERY slow' tablet and a table with about 100 rows, from within a browser, the datatable, most of the time it does not selects multiple rows but its working just like a 'single selection mode'. The last tap deselects all previous selected rows and selects just one. On a much more fast tablet and mobile device it seems to working as expected!!!
