### ISSUE TITLE
Tooltips: Option to close tooltips with escape

### ISSUE THREAD

**Issue by pfdutoit** [primefaces/primeng#12603]
### Describe the feature you would like to see added

Add the ability to close tooltips by pressing Escape.

### Is your feature request related to a problem?

For more information, see https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html

People navigating using without a mouse (i.e. keyboard-only or using assistive technologies) have no way to close tooltips at their own discretion. Tooltips only disappear when moving the mouse away, or with autohide. The former excludes non-mouse users. The latter would not comply with WCAG criteria either: https://www.w3.org/WAI/WCAG21/Techniques/failures/F95

### Describe the solution you'd like

Add an boolean flag to tooltip options called hideOnEscape that close them manually. It would be a boolean that would be set to false by default. 

### Describe alternatives you have considered

If it were only necessary in one location, one could implement the required feature on the relevant component easily. However, tooltips are ubiquitous to most websites, so implementing the closing-on-Escape mechanism on a component-by-component basis is unfeasible and bug-prone.

### Additional context

![closeTooltipOnescape](https://user-images.githubusercontent.com/10095939/216909917-266fc10c-5850-4451-844f-643b0c136459.gif)

**Comment by SoyDiego** [comment]
Yes, very necessary, as the property autoHide="false". For accesibility is required!

Thanks for do it and hope accept this PR.
