### ISSUE TITLE
p-tabMenu: visible property of  MenuModel API isn't recognized

### ISSUE THREAD

**Issue by Draftscode** [primefaces/primeng#12614]
### Describe the bug

Setting any MenuItem to visible false does not hide the related item in the dom.

### Environment

primeng@15.2.0
angular@15.1.4

### Reproducer

https://stackblitz.com/edit/angular-ivy-yixiyk?file=src/main.ts

### Angular version

15.1.4

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Browser(s)

Chrome

### Steps to reproduce the behavior

just set "visible" of any menuItem to false

### Expected behavior

MenuItem's with visible: false should be not rendered in DOM

**Comment by fsheiness** [comment]
p-hidden class is being added correctly, but the `display` property is getting overridden by the p-tabmenuitem class 
![primeng](https://user-images.githubusercontent.com/112975559/227632211-623a3874-8fc5-4223-8799-6c28d892c27a.png)
