### ISSUE TITLE
Table: Not all pages are loaded in flexscroll with lazyload

### ISSUE THREAD

**Issue by m11t** [primefaces/primeng#12615]
### Describe the bug

When using the Table component in a similar setup as done at https://primeng.org/table/flexscroll, not all pages are requested when scrolling.

In the attached Stackblitz it can be easilz seen, that the last page is not loaded.

### Environment

-

### Reproducer

https://github-1zbhrt.stackblitz.io

### Angular version

15.1.4

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

-

### Steps to reproduce the behavior

1. Scroll down manually

### Expected behavior

The second (or last) page should be requested and applied.
No more skeletons should be seen.

**Comment by ahp-painer** [comment]
:+1:

**Comment by derseeli** [comment]
Hi Melf,
could you please share the Reproducer/the example code again? It's not working anymore.

Thanks, Niels
