### ISSUE TITLE
DataTable onRowUnselect not fired

### ISSUE THREAD

**Issue by derchirurg** [primefaces/primeng#1261]
In the current release 1.0.0-rc.4 the event onRowUnselect is not fired in the datatable.
In the previous release everything worked fine.

**Comment by kcsahoo** [comment]
It fires but goes to RowSelect event.
This is causing a lot of problems in select/unselect.

**Comment by kcsahoo** [comment]
It fires correctly with Ctrl+Click.
This change was made in rc.4 for multiple select/unselect.
But it is affecting Single Selection.

**Comment by derchirurg** [comment]
I am handling this behaviour on my own. It would be nice, if it will work for single selection as in rc.3.

**Comment by cagataycivici** [comment]
Discussed at 1260.
