### ISSUE TITLE
Autocomplete: when you use the down key it does not scroll

### ISSUE THREAD

**Issue by renedominguez1** [primefaces/primeng#12610]
### Describe the bug

Autocomplete: when you use the down key it does not scroll

### Environment

Autocomplete: when you use the down key it does not scroll

### Angular version

15.1.3

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.10.0

### Browser(s)

Chrome

**Comment by Ivan-Grishkov** [comment]
This issue is really hurts. I have no idea how to overcame it
