### ISSUE TITLE
Component: Dropdown and Multiselect with VirtualScroll panel should ajust height when there are only a few elements

### ISSUE THREAD

**Issue by luismqoliveira** [primefaces/primeng#12612]
### Describe the bug

Hello, I'm trying to use dropdown with virtual scroll (v14 prime). Have an issue when my dropdown is just a few items, like less than 6. As each item has 30px and you guys are setting scrollHeight 200px as default the dropdown is just huge when i only have 1 item (see photo, this is the official example in stackblitz). The 200px should be replaced with the height of the component below which is dymanic, it's calculated based on the number of elements. I think 200px static doesn't fit when we have a few items. 
As you can see in both photos the height just increases as the number of elements increase too but the 200px always the same...
The height should be dynamically calculated as you are doing on the element below and we should be allowed to change the max-height, not the height.

![Screenshot from 2023-02-01 17-28-17](https://user-images.githubusercontent.com/26435234/217783269-2e8c8700-c8d3-4417-9380-b827f4b4d012.png)
![Screenshot from 2023-02-01 17-26-54](https://user-images.githubusercontent.com/26435234/217783277-da3dc5ac-92f4-4817-80fb-9a04592dc155.png)

### Environment

I'm using primeng 14 and angular 14 but I used your example from stackblitz from primeng official page (which is angular and primeng 13), the links are below:

Stackblitz: https://stackblitz.com/edit/primeng-dropdown-demo-g4la9c?file=src/app/app.component.html
Demo: https://primeng-dropdown-demo-g4la9c.stackblitz.io

### Angular version

13

### PrimeNG version

13

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

8.9.5

**Comment by mehmetcetin01140** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.

**Comment by maudvd** [comment]
This still happens in V17
