### ISSUE TITLE
InputNumber [maxlength] not working & it works weirdly on large input length

### ISSUE THREAD

**Issue by bkj281** [primefaces/primeng#12616]
### Describe the bug

```
<p-inputNumber
                class="w-full"
                styleClass="w-full"
                inputStyleClass="w-full floty-filter-controls"
                [(ngModel)]="currentValue"
                [maxlength]="selectedField?.Precision"
                (onInput)="onNumberInput($event)"
                [maxFractionDigits]="selectedField?.Scale"
                #numberField
 ></p-inputNumber>
```

here [maxlength] doesn't bind input fields length.
when we add large number it adds "0" even if we press any other digit.

### Environment

Angular v13

### Angular version

13.3.9

### PrimeNG version

13.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Browser(s)

ALL

**Comment by mehmetcetin01140** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.
