### ISSUE TITLE
API Documentation: All

### ISSUE THREAD

**Issue by mannyNRECA** [primefaces/primeng#12625]
### Describe the feature you would like to see added

Forgive me if this is already listed somewhere, but I cannot for the life find it.  

I would like to see API documentation, much like you see in [Material UI](https://mui.com/material-ui/api/button/).

### Is your feature request related to a problem?

I'm always frustrated when I try to use a PrimeNG component and the only documentation I have are examples which may or may not fit my scenario.

### Describe the solution you'd like

I'd like to see API Documentation where you can see: 

- A list of all components
- A list of properties and methods for each component
- Descriptions of each property/method

### Describe alternatives you have considered

I've used the examples and now I'm starting to look through the node_modules and try out properties/methods without knowing what they actually do.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
