### ISSUE TITLE
p-tabview using with confirmation dialog breaking sometimes

### ISSUE THREAD

**Issue by kalyanipullela** [primefaces/primeng#12629]
### Describe the bug

Hello,
I'm trying to change the tabview based on the confirmation message. If a user clicks on yes then only the tab needs to be changed. It works correctly for 4-5 iterations and then it does not give the popup, changes the tab and again after a delay of 5-10sec when clicked then shows the popup.

Here is the code snippet:
```
<p-confirmDialog header="Confirmation" key="unsaveChanges" icon="pi pi-exclamation-triangle"></p-confirmDialog>
<p-tabView [(activeIndex)]="index">      
    <p-tabPanel>
        <ng-template pTemplate = "header">
           <div (click)="handleChange($event,0)>
            <i class="pi pi-users"></i>&nbsp;
            <span>Assignments</span>
            </div
        </ng-template>
        <app-assignments></app-assignments>
    </p-tabPanel>
    <p-tabPanel>
          <div (click)="handleChange($event,1)>
        <ng-template pTemplate = "header">
            <i class="pi pi-envelope"></i>&nbsp;
            <span>Message Log</span>
             </div>
        </ng-template>
          <div (click)="handleChange($event,2)>
        <app-messagelog></app-messagelog>
        </div>
    </p-tabPanel>
</p-tabView>
```
component,ts
```
index=0;
handleChange(e:MouseEvent,tabIndex:any) {
    e.stopPropagation();
    console.log("TAB CHANGE CLICKED &",e)
    if (this.index == tabIndex){
      return;
    }
    console.log(tabIndex)
    this.confirmationService.confirm({
      message: "There are unsaved changes, do you want to proceed?",
      key:"unsaveChanges",
      accept: () => {
        this.index = tabIndex;
        
      },
      reject: () => {}
    });
  }
```

### Environment

Angular 12
PrimeNg 12

### Angular version

12

### PrimeNG version

12

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14

### Browser(s)

Chrome

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
