### ISSUE TITLE
Component: Table - Multiple Selection with MetaKey does not support CTRL + ENTER

### ISSUE THREAD

**Issue by konuch** [primefaces/primeng#12621]
### Describe the bug

In Table component set up as **"Multiple Selection with MetaKey"** use case, it's not possible to mimic CTRL + CLICK behavior using keyboard. If you click on a given row while CTRL is pressed, you add/remove row from selection. This is not possible using keyboard navigation, eg. CTRL+ENTER. SHIFT key functionality is supported using both mouse and keyboard. 
It can be verified on https://primeng.org/table/selection page.

### Environment

Windows 10

### Angular version

15.1.0

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.15.1

### Browser(s)

Chrome latest

### Steps to reproduce the behavior

1. Open https://primeng.org/table/selection
2. Go to part **"Multiple Selection with MetaKey"**
3. Navigate with arrow keys in the table.
4. Press CTRL and ENTER. 
5. Row is not selected.
6. Press SHIFT and ENTER. 
7. Row is selected

### Expected behavior

Expected behaviour is that CTRL key meta selection is supported via keyboard only. Eg. you select a row with arrow keys, hit CTRL+ENTER and row is selected, move with arrow keys to next row and select anothert one with CTRL+ENTER.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
