### ISSUE TITLE
Reopen issue #11442 p-inputNumber cannot use the decimal separator of the digital keyboard when the separator is a comma

### ISSUE THREAD

**Issue by Labaffe** [primefaces/primeng#12626]
### Describe the bug

I just reopen this issue that was closed. But new improvements dont fix this problem.

https://github.com/primefaces/primeng/issues/11442

In short : "The component p-inputNumber is expecting a comma as a decimal separator, and the digital keyboard only provides dots."

### Environment

Linux/Windows 10

### Reproducer

See https://stackblitz.com/edit/github-qhqhnr where the p-inputNumber is set with french locale.

### Angular version

15.0.4

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.20.0

### Browser(s)

Chrome

**Comment by theguiro** [comment]
+1, greatly diminishes the user experience since they cannot add decimal values.

**Comment by selfides** [comment]
Have anybody found a solution?

**Comment by rgarciaggr** [comment]
This would be a great improvement since there are other programs (like calc or excel) where you can type the numpad Decimal and it detects the decimal character based on your locale.
