### ISSUE TITLE
p-dropdown: ngModel is ignored (neither read nor updated)

### ISSUE THREAD

**Issue by tobiasmuecksch** [primefaces/primeng#12634]
### Describe the bug

I've created a dropdown as described in the documentation.
The dropdown ignores the ngModel value and does not update it correctly.

```html
<p-dropdown [styleClass]="'page-dropdown'" [options]="dropdownOptions" [(ngModel)]="entriesPerPage"
  optionLabel="label" optionValue="trefferAnzahl" (onChange)="onUpdateEntriesPerPage($event)"
  style="margin-left: auto;"></p-dropdown>
```

With PrimeNG 14.x it worked perfectly fine. But after upgrading to 15.x it's broken.

### Environment

macos 13.1
nodejs 18.14.0

### Reproducer

https://github.com/tobiasmuecksch/primeng-dropdown-issue

See section "reproduction" for stackblitz demos (14.x and 15.x)

### Angular version

15.1.0

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.14.0

### Angular 14 with PrimeNG 14.x
✅  Works as expected

https://github-tengjd.stackblitz.io

### Angular 15 with PrimeNG 15.2.0
❌ Same code, different versions, but ngModel is broken

https://github-tengjd-wgbjsz.stackblitz.io

## Git Repo
I've also prepared a git repo, in case you need it.

1. `git clone git@github.com:tobiasmuecksch/primeng-dropdown-issue.git`
2. `npm install`
3. `npm run start`
4. Change the selected entry in the dropdown
5. you will see, that the ngModel value is not updated

### Expected behavior

Well, I'd expect the ngModel value to change according to the user's selection.

**Comment by awat365c** [comment]
I had the same issue, or rather have the same issue. I found that if i put a placeholder in it, ngModel works as expected.

**Doesn't work**
<p-dropdown inputId="new" id="new" [options]="newFilters"
            [(ngModel)]="newFilter" optionLabel="value" dataKey="id"></p-dropdown>

**Works**
<p-dropdown placeholder="New" inputId="new" id="new" [options]="newFilters"
            [(ngModel)]="newFilter" optionLabel="value" dataKey="id"></p-dropdown>

**Comment by z857039580** [comment]
I find that，delayed assignment can solve this proble。Such as：
`setTimeout(() => this. newFilter = **)`

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
