### ISSUE TITLE
TabMenu - QueryParams ignored in isActive function

### ISSUE THREAD

**Issue by valentindruon** [primefaces/primeng#12631]
### Describe the bug

Currently, if a TabMenu's items all have the same routerLink value, and are only different based on queryParams, the isActive function returns true for every one of these items.

This leads to every items having the `p-highlight` class and being showed as active to the user

### Environment

Angular 13.3.1 
PrimeNG 13.4.1

### Angular version

13.3.11

### PrimeNG version

13.4.1

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

14.9.1

**Comment by semahawk** [comment]
Just ran into this issue on the latest version, 16.4.1. @valentindruon any chance on reopening #12630?

**Comment by valentindruon** [comment]
Idk, my pull request has been ignored

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
