### ISSUE TITLE
P-Table: Virtual Scroll not working with group header and footer

### ISSUE THREAD

**Issue by bubblegumsoldier** [primefaces/primeng#12633]
### Describe the bug

Once the virtual scroll is enabled the group headers and footers of the row grouping are hidden and not displayed at all. Is this a known issue, not yet supported, or a bug?

![image](https://user-images.githubusercontent.com/3788628/218753144-9ac52116-04d5-486a-99de-fcdbcbd734fa.png)

![image](https://user-images.githubusercontent.com/3788628/218753187-ee5cb8d0-f077-4127-8c3c-097aad28e613.png)

### Environment

I took some time to reproduce the issue in a minimal demo

https://stackblitz.com/edit/primeng-tablevirtualscroll-demo-szyuau?file=src%2Fapp%2Fapp.component.html

### Angular version

14.2.11

### PrimeNG version

14.2.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.1

**Comment by bubblegumsoldier** [comment]
https://github.com/primefaces/primeng/blob/085a4e6b09e54ef6f1c5ae6f770bdc7fe724414c/src/app/components/table/table.ts#L2485

In this line I see that this functionality is actively disabled when `dt.virtualScroll` is `true`... Why is that the case and why is it not communicated anywhere?

**Comment by michcothwork** [comment]
It's not just hidden headers either. Virtual scrolling breaks row grouping all together. If you have row grouping enabled, and are in subheader it will stop grouping properly. This is on all versions of PrimeNG that are v14 and above. 

Here is a stackblitz using v14. I took the row grouping demo and added virtual scrolling.
https://stackblitz.com/edit/primeng-tablerowgroup-demo-dhx2pl?file=src%2Fapp%2Fapp.component.html

**Comment by bubblegumsoldier** [comment]
For anyone that finds himself in the same trouble: I solved it using a workaround.

I anotated each row item object with whether it is in a group and specifically anotated the first and last item of the group with a boolean. Then I just added another row for the first Item in the row template and gave the "inside" rows a class. See example code below.

```html
<ng-template pTemplate="body" let-item>
  <tr *ngIf="item.firstInGroup" class="group-head-row">
    <td colspan="100%">{{item.group.name}}</td>
  </tr>
  <tr [class.is-in-group]="item.group">
    <!-- my item row itself -->
  </tr>
</ng-template>
```

This renders just fine even with virtual scrolling. But it is of course just a workaround as it doesnt allow for expansion on click etc.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
