### ISSUE TITLE
p-treeSelect: css size classes has no effect(such p-inputtext-lg)

### ISSUE THREAD

**Issue by itismohammadreza** [primefaces/primeng#12646]
### Describe the bug

According to the [documentation](https://primeng.org/inputtext) (sizes section), the following code is expected to make the `p-treeSelect` larger, but it has no effect (while it works fine on other components like `p-autoComplete` and `p-dropdown` etc.).
```
<div class="p-inputtext-lg">
    <p-treeSelect></p-treeSelect>
</div>
```

### Environment

windows

### Reproducer

https://stackblitz.com/edit/github-pfxuju?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.module.ts

### Angular version

15

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.16.0

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
