### ISSUE TITLE
Component: InputNumber - Additional digit is written once separation of thousands is reached

### ISSUE THREAD

**Issue by Kaiden42** [primefaces/primeng#12642]
### Describe the bug

When you type in the value of `1000` into the field of an InputNumber element, an additional digit is typed when you type the fourth digit.
You can reproduce this issue on your website at the Japan Currency input field.
![image](https://user-images.githubusercontent.com/26521388/219423374-b8ba0d58-ee7e-448e-9d3b-1def5afc0436.png)

It seems that this bug occurs when `maxFractionDigits` is set to `0`. This happens for the € currency as well, when there are no fraction digits. It does not happen when `maxFractionDigits` is set to a value greater than or equal to 1.

Maybe related to #12308

### Environment

It happens on your own website too.
You can see this bug on the versions v15.2.0 and v14.2.2 on your example page. Version v13.4.1 is not affected.

### Reproducer

https://primeng.org/inputnumber

### Angular version

15.1.4

### PrimeNG version

15.2.0

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

16.17.1

### Steps to reproduce the behavior

1. Visit https://primeng.org/inputnumber
2. Type four digits in the Japan Currencies field
3. There is a fifth digit appearing in the field

### Expected behavior

The field should only have the four digits I've typed.

**Comment by Goomba41** [comment]
Also met with this issue

**Comment by LouLeGrain** [comment]
Same problem here

My workaround for the moment is to use a `.p-inputgroup` with and addon for the currency
```html
<div class="p-inputgroup">
    <p-inputNumber id="budget" formControlName="budget"></p-inputNumber>
    <span class="p-inputgroup-addon">
        €
    </span>
</div>
```
![image](https://user-images.githubusercontent.com/9808953/226985542-bd56f262-a0e9-42de-af94-f61b6b2bd2c3.png)

**Comment by cetincakiroglu** [comment]
Hi,

Is this bug still happens with the latest version? I couldn't replicate by setting maxFractionDigits to 0. Could you please instruct me?

**Comment by Goomba41** [comment]
> Hi,
> 
> Is this bug still happens with the latest version? I couldn't replicate by setting maxFractionDigits to 0. Could you please instruct me how can I reproduce or could you please share a Stackblitz example?

When i updated to [15.2.1](https://github.com/primefaces/primeng/releases/tag/15.2.1) version, bug seems to be fixed

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
