### ISSUE TITLE
Component: Chart component does not have a styleClass. 

### ISSUE THREAD

**Issue by larteyjoshua** [primefaces/primeng#12649]
### Describe the feature you would like to see added

The Chart component does not have a style class.

### Is your feature request related to a problem?

I want to change the size of the chart on different screen sizes with a CSS media query but I was unable. 

### Describe the solution you'd like

I write to recommend that styleClass should be added to the Chart to make accessibility with CSS class for easy manipulating with CSS media query

### Describe alternatives you have considered

I try using the responsive property set to true but it seems not working as the size doesn't change on a mobile screen.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
