### ISSUE TITLE
data tables resizableColumns not working as expected in all browsers

### ISSUE THREAD

**Issue by deephakdd** [primefaces/primeng#1264]
<p-dataTable [value]="cars" resizableColumns="true">
            <p-column field="vin" header="Vin"></p-column>
            <p-column field="year" header="Year"></p-column>
            <p-column field="brand" header="Brand"></p-column>
            <p-column field="color" header="Color"></p-column>
 </p-dataTable>

when trying to resize column  (say 2nd or third) i end up having only the column which i resized and its adjacent column , other 2 are not visible

**Comment by kcsahoo** [comment]
Yes, there are several Datatable issues in IE and some issues in Firefox.

**Comment by khurambutt-REIsys** [comment]
This problem is also in Chrome as well, I was using Chrome and experienced this problem. I wanted to report this issue but already found this one here.

I was checking on the demos at http://www.primefaces.org/primeng/#/datatable/colresize, it seems to be actually working there, which Release version is in use there as seems like the working version to me.

Thanks very much for the great work done.

**Comment by cagataycivici** [comment]
Which browsers you are having issue with?

**Comment by khurambutt-REIsys** [comment]
I am using browsers: both having similar problems, I was using 3 columns.
Chrome - Version 54.0.2840.87 (64-bit) - One column totally gets hidden on resizing.
Firefox - 49.0 - One column gets toooo small in size, barely visible.

**Comment by cagataycivici** [comment]
Attach a video of your case as we can't replicate.

**Comment by cagataycivici** [comment]
Min-width is 15 by the way but you can customize it with cas on column.

**Comment by khurambutt-REIsys** [comment]
Attached is the video  -- [PrimeNG Issue Video.zip](https://github.com/primefaces/primeng/files/587921/PrimeNG.Issue.Video.zip)

FYI, tried both versions "1.0.0-rc.4" and "1.0.0-rc.3" and didn't work for me in both of them.

**Comment by deephakdd** [comment]
any updates on this issue ???

any help is highly appreciated

**Comment by khurambutt-REIsys** [comment]
I am stuck on this issue as well, will appreciate any help in this regard.

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/VZbdZfQ7SuTV87tTkbYR
