### ISSUE TITLE
FilterService: Add support for fuzzy filtering

### ISSUE THREAD

**Issue by martin31821** [primefaces/primeng#12656]
### Describe the feature you would like to see added

Currently, the FilterService can do several different filtering modes, e.g. 'contains' or 'startsWith'. While these are quite useful, there are a few use cases where a fuzzy filtering is desired, e.g. using fuse.js.

### Describe the solution you'd like

I see two options:
1. Implement a fuzzy search directly in primeng
2. Allow the filterService to be extended by custom filtering implementations, which might actually be the more flexible approach. That way a user like me can extend the filterService without bloating the bundle size for all users.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
