### ISSUE TITLE
When the Options are pre-Selected, the treeSelect always comes in Expanded mode. 

### ISSUE THREAD

**Issue by SalmanNizami** [primefaces/primeng#12658]
### Describe the bug

We are using Primeng 13.1.0 in which we are using TreeSelect component . 
Our scenario is that we pre-populate the selectedNodes and assign them when the page Initializes and once we open the treeSelect dropdown, the nodes are always in Expanded mode . We tried to Explicitly assign expanded value to false but still it doesn't work . it always comes in Expanded mode which is annoying . 

have attached a sample version from your own Primeng Tree Select Page. Here I have explicitly assigned the values initially and once the data is loaded, tree dropdown data is always expanded. 

Is there a way to collapse the data ?

### Environment

???

### Reproducer

https://stackblitz.com/edit/primeng-treeselect-demo-c4sq5b?file=src/app/app.component.ts

### Angular version

13.2.4

### PrimeNG version

13.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.13.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

Have Attached link of a Demo project .

### Expected behavior

The Tree data should collapse if we explicitly make it to collapse.

**Comment by SalmanVolvoGit** [comment]
Any update on this enhancement. It would be great value addition if this feature is looked upon.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
