### ISSUE TITLE
Table: page state not persisting when adding p-columnFilter to header template

### ISSUE THREAD

**Issue by Zagano-AOR** [primefaces/primeng#12655]
### Describe the bug

When trying to persist table state includeing filters, page sort order, everythig works fine except when you add the p-columnFilter, after adding it to the header page state is no longer respected but sort and filters still work correctly. So, somehow the first attribute is reset back to 0. 

### Environment

Windows dev machine but tested in all PC and mobile browsers

### Angular version

14.2.12

### PrimeNG version

14.2.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.18.0

### Steps to reproduce the behavior

1. add a new p-table to your template
2. load the required data and binder de value attribute
3. declare/enable paginator, rows, dataKey, stateKey and stateStorage
4. add the corresponding templates to the table, header, body, (caption, footer if needed)
5. navigate to any page of the table
6. refers the page and it will work...
7. then add the p-columnFilter and page is no longer persisting (go to session/local storage accordingly and notice that the **first** attribute is reset back to 0)  

### Expected behavior

State should persist page number even when using the p-columnFilter...

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
