### ISSUE TITLE
DataTable lazy loading filter issue with ngDoCheck

### ISSUE THREAD

**Issue by bogdanvaduva** [primefaces/primeng#1265]
I have a DataTable with filters. If I click inside a filter column and then hit the tab key, the lazyloading will do a refresh of data.

In ngDoCheck you have:

_let changes = this.differ.diff(this.value);_

If this.value is an Array of Objects the above statement will always return true because, within DefaultIterableDiffer, we have:
    function looseIdentical(a, b) {
        return a === b || typeof a === 'number' && typeof b === 'number' && isNaN(a) && isNaN(b);
    } which always return true.

Am I understanding it right? 

OR 

Should I change filterTimeout as follow:
        this.filterTimeout = setTimeout(function () {
            if (value!='') {
                if (!_this.filters.hasOwnProperty(field) || _this.filters[field].value!=value) {
                    _this.first = 0;
                    _this.filters[field] = { value: value, matchMode: matchMode };
                    _this.filter();
                    _this.filterTimeout = null;
                }
            } else {
                if (_this.filters.hasOwnProperty(field) && _this.filters[field].value!=value) {
                    _this.first = 0;
                    _this.filters[field] = { value: value, matchMode: matchMode };
                    _this.filter();
                    _this.filterTimeout = null;
                }
            }
        }, this.filterDelay);
and delete this.first=0 from filter ?

Regards

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/VZbdZfQ7SuTV87tTkbYR

**Comment by bogdanvaduva** [comment]
Thanks, I will let you know.
