### ISSUE TITLE
Calendar: Decade template implicit value is undefined

### ISSUE THREAD

**Issue by erqk** [primefaces/primeng#12661]
### Describe the bug

When using custom template for decade, the implicit value is undefined.

### Environment

Angular 15.1.0
NodeJs 18.13.0
Windows 11

### Angular version

15.1.0

### PrimeNG version

15.2.1-SNAPSHOT

### Build / Runtime

Angular CLI App

### Language

ES6

### Node version (for AoT issues node --version)

18.13.0

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
