### ISSUE TITLE
p-dropdown: validation not working

### ISSUE THREAD

**Issue by r0754497** [primefaces/primeng#12667]
### Describe the bug

ng-dirty class isn't being added to the dropdown component on validation. Not displaying red border or browser default validation.

### Environment

ts:
`@ViewChild("cameraForm") cameraForm: any;
... (method under button) {
this.cameraForm.nativeElement.reportValidity(); }`

html:
```
<form #cameraForm class="camera-details">
  <span class="p-float-label">
    <p-dropdown name="cameraForm" id="dropdown" [autoDisplayFirst]="false" [options]="cameras" [(ngModel)]="selectedCamera" optionLabel="name"
                [ngClass]="{'ng-dirty': selectedCamera}" [required]="true"></p-dropdown>
    <label for="dropdown">Camera</label>
  </span>
</form>
```

### Angular version

15.1.0

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

8.19.2

**Comment by volvachev** [comment]
Hello, could you explain why you are using `reportValidity` from Html and not using Angular validators functionality?

For example, [ReactiveForm](https://angular.io/api/forms/FormControl), or [ngForm](https://angular.io/api/forms/NgForm).

Angular adds `ng-dirty` by itself, no need to do it manually.

A red border on the drop-down list appears if two classes `ng-dirty.ng-invalid`

In my example, when you select something and it fails the test, a red box appears.
```html
<form #cameraForm class="camera-details">
  <span class="p-float-label">
    <p-dropdown name="cameraForm" id="dropdown" [autoDisplayFirst]="false" [options]="cities" [formControl]="control" optionLabel="label"
				[required]="true"></p-dropdown>
    <label for="dropdown">Camera</label>
  </span>
</form>
```

```ts
control = new FormControl('', [Validators.required, (currentControl) => {
        if (currentControl.value === 'test') {
            return null;
        }
        
        return {test: true};
    }])
```

**Comment by r0754497** [comment]
It's adding the ng-invalid class but not the ng-dirty class. Even when I changed it to FormGroup/FormControl instead of base HTML.
I used the HTML way because that gave me something that works. Have no clue why it isn't adding ng-dirty when invalid is added.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
