### ISSUE TITLE
Table with multiselect column filter, not applying default filter from ngModel

### ISSUE THREAD

**Issue by dennismagno** [primefaces/primeng#12660]
### Describe the bug

I tried the sample project in table https://primeng.org/table/filter.  I change the ngModel to show or select default filter for the multi select. The option is selected correctly in multiselect.  But unfortunately the filter is not applied in the table.  As you can see in the screenshot below. I choose **Amy Elsner** as default filter.  But the table is also showing agent with name **Ioni Bowcher**

![image](https://user-images.githubusercontent.com/5070675/220541383-6dace811-24bf-4a6e-8f38-d5dff928e47a.png)

### Environment

Angularjs

### Angular version

15.1.4

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.19.0

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
