### ISSUE TITLE
p-editor: completly broken styling

### ISSUE THREAD

**Issue by Draftscode** [primefaces/primeng#12668]
### Describe the bug

currently the p-editor component looks completly broken.

### Environment

angular 15.2.0
primeng 15.2.0
quill 1.3.7

### Angular version

15.2.0

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.2

### Browser(s)

Chrome

### Steps to reproduce the behavior

Just copy paste example from documentation into stackblitz with angular 15.x.x

[Stackblitz](https://stackblitz.com/edit/angular-ivy-csyzxp?file=src/main.ts)

### Expected behavior

Should show exactly the same editor like in documentation

**Comment by moritz-baumgart** [comment]
Hey I saw that you closed the issue yourself, did you manage to fix it? I just stumbled upon this, because I am currently facing the same problem.

**Comment by tsteuwer-accesso** [comment]
@Draftscode  did you resolve this? @moritz-baumgart  and I are having the same issue. I just installed Quill then tried to use the component and it's completely broken.

![image](https://github.com/primefaces/primeng/assets/32495798/6dfea063-c912-456c-b5fd-2408c98f5fe5)

**Comment by JohanHeyvaert** [comment]
I had the same problem. Importing quill's css fixed it.

Maybe this is obvious, but I think it **should be added to the documentation** (https://primeng.org/editor).
