### ISSUE TITLE
p-tag: style not change dynamically

### ISSUE THREAD

**Issue by stsness** [primefaces/primeng#12665]
### Describe the bug

Using p-tag style not change dynamically.

### Environment

Angular 14
Primeng 14

### Reproducer

https://stackblitz.com/edit/github-k27wqg?file=src/app/app.component.html

### Angular version

14

### PrimeNG version

14.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Steps to reproduce the behavior

1. Select an option
2. Show correct color p-tag
3. Change option
4. P-tag Not change to new color

### Expected behavior

Update new color after change.

**Comment by ericvaroto** [comment]
Hello everyone,
Any update about this issue?

I'm facing the same problem in version 16.0.1: the TAG component do not refresh the "style" attribute to get the new value "background-color" in property "roleColor"

Code:
`<p-tag
    [style]="{
      'background-color': '#' + member.roleColor
    }"
    >
      {{ member.roleName }}
</p-tag>`

**Comment by jvegaseg** [comment]
Same problem with PrimeNG 17.7.0.

¿Any workarround?
