### ISSUE TITLE
p-table: Bad performance of total selection

### ISSUE THREAD

**Issue by Kisters-BS** [primefaces/primeng#12671]
### Describe the bug

When selecting all lines at once, the selection takes unexpected long. For example selecting 2000 lines takes one second and 4000 already more than three seconds.  I have defined dataKey so deep checking when comparing objects is not needed.

### Environment

See stackblitz

### Reproducer

https://stackblitz.com/edit/primeng-table-selection-4ce3fa?file=src%2Fapp%2Fapp.component.ts

### Angular version

15.2.0

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.19.0

### Browser(s)

Firefox 110.0, Chrome 110.0

### Steps to reproduce the behavior

1. Click on the header checkbox which selects all lines

### Expected behavior

I have tested this feature with another table implementation library and there is no problem of selecting 8000+ lines at once. So I expect to be able to select 10000 lines with no effort.

**Comment by dalenguyen** [comment]
Did you try to add the virtualScroll to the table? I will improve the performance. For example:

```
<p-table
  [columns]="cols"
  [value]="cars"
  [scrollable]="true"
  scrollHeight="700px"
  [(selection)]="selectedCars"
  dataKey="vin"

  [virtualScroll]="true"
  [virtualScrollItemSize]="12"
>
```

**Comment by Kisters-BS** [comment]
Yes, I also tried it with virtualScroll and it does improve the performance to some extend but it still takes up to multiple seconds for the selection all data

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
