### ISSUE TITLE
p-table: table collapse on filter set

### ISSUE THREAD

**Issue by cgomm** [primefaces/primeng#12672]
### Describe the bug

When I set a filter for on column, the table will collapse totally.

![image](https://user-images.githubusercontent.com/18654854/220950333-c00bac6c-7289-437d-b6d9-3874539e80c4.png)
![image](https://user-images.githubusercontent.com/18654854/220950713-a9856b32-6c1c-4b7f-8cb6-8d37018b9448.png)

### Environment

<p-table
  [...]
  scrollHeight="{{ tableSize-minuetTableSize }}px"
  [...]
>

### Angular version

14.2.12

### PrimeNG version

14.2.2/14.2.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.15.1

### Browser(s)

Chrome 110

**Comment by mehmetcetin01140** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.
