### ISSUE TITLE
p-table: rowsPerPageOptions set to All doesn't update the paginator consistently when changing the table's [value]

### ISSUE THREAD

**Issue by activedecay** [primefaces/primeng#12674]
### Describe the bug

Changing the pagination dropdown to 'All' does not have the desired effect when the entries in the table are growing

### Environment

linux browser. reproduced in stackblitz though, so all environment information should be there as well

### Reproducer

https://stackblitz.com/edit/primeng-tablepage-demo-z2hxr4?file=src/app/app.component.ts

### Angular version

15.1.0

### PrimeNG version

15.0.1

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

v18.12.0

### Browser(s)

chromium

### Steps to reproduce the behavior

Steps:
1. create a table that is being updated with new rows
2. setup pagination with {'showAll': 'All'} and with the number of rows shown equal to the `rows` variable
3. render the table in the GUI, wait for an update, then change the `rows` to 'All' using the dropdown menu in the gui
4. ERROR: the behavior expected is that all the rows are shown and the numbers in the paginator make sense. the numbers don't make sense, and there are additional pages shown as an option to click on.
5. workaround: clicking the number 1 in the paginator will show all the rows as expected

### Expected behavior

updating the length of a table's value array should update the paginator as expected when the number of rows is set to 'all'

**Comment by ymg2006** [comment]
Hello, I faced same issue and traced it in paginator.ts 
```
    ngOnChanges(simpleChange: SimpleChanges) {
        if (simpleChange.totalRecords) {
            this.updatePageLinks();
            this.updatePaginatorState();
            this.updateFirst();
            this.updateRowsPerPageOptions();
        }

        if (simpleChange.first) {
            this._first = simpleChange.first.currentValue;
            this.updatePageLinks();
            this.updatePaginatorState();
        }

        if (simpleChange.rows) {
            this.updatePageLinks();
            this.updatePaginatorState();
        }

        if (simpleChange.rowsPerPageOptions) {
            this.updateRowsPerPageOptions();
        }
    }
```

methods should be re ordered like below to work properly
```
   ngOnChanges(simpleChange: SimpleChanges) {
        //first update updateRowsPerPageOptions to fix showAll problem
        if (simpleChange.rowsPerPageOptions) {
            this.updateRowsPerPageOptions();
        }

        if (simpleChange.totalRecords) {
            //first update updateRowsPerPageOptions to fix showAll problem
            this.updateRowsPerPageOptions();
            this.updatePageLinks();
            this.updatePaginatorState();
            this.updateFirst();
        }

        if (simpleChange.first) {
            this._first = simpleChange.first.currentValue;
            this.updatePageLinks();
            this.updatePaginatorState();
        }

        if (simpleChange.rows) {
            this.updatePageLinks();
            this.updatePaginatorState();
        }
    }
```
I will create a pull request after debugging and confirming the fix

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
