### ISSUE TITLE
p-table: filter or sort does not work with [lazy]="true", without it will print a error message

### ISSUE THREAD

**Issue by cgomm** [primefaces/primeng#12670]
### Describe the bug

Within out table we added the following attributes:
```
  <p-table
    [value]="content"
    [columns]="activeColumns"
    dataKey="id"
    [loading]="this.loadingContent"
    [scrollable]="true"
    [virtualScroll]="true"
    [virtualScrollItemSize]="46"
    rows="100"
    scrollHeight="{{ tableSize-minuetTableSize }}px"
    [reorderableColumns]="true"
    stateStorage="session"
    [stateKey]="stateKey"
    (onStateSave)="syncStorageState(stateKey, $event)"
    styleClass="p-datatable-sm"
    [customSort]="true"
    (sortFunction)="customSortFunction($event)"
    [expandedRowKeys]="expandedRows"
  >
```

I would like us of the virtual scroll feature, because we will render otherwise 2k+ elements within the table. 

Everything works fine and as intended, expect this error message.
![image](https://user-images.githubusercontent.com/18654854/220872013-bedaf55c-9d8e-4569-bfc8-93698aeb989c.png)

I am not able to remove it, expect I remove the state feature, which is not a option currently. 

### Environment

html:
```
<div>
  <p-table
    [value]="content"
    [columns]="activeColumns"
    dataKey="id"
    [loading]="this.contentLoading"
    [scrollable]="true"
    [virtualScroll]="true"
    [virtualScrollItemSize]="46"
    rows="100"
    scrollHeight="{{ tableSize-minuetTableSize }}px"
    [reorderableColumns]="true"
    stateStorage="session"
    [stateKey]="stateKey"
    (onStateSave)="syncStorageState(stateKey, $event)"
    styleClass="p-datatable-sm"
    [customSort]="true"
    (sortFunction)="customSortFunction($event)"
    [expandedRowKeys]="expandedRows"
  >
    <ng-template pTemplate="header">[...]</ng-template>
    <ng-template pTemplate="body" let-rowData let-expanded="expanded" let-columns="columns">[...]</ng-template>
    <ng-template pTemplate="rowexpansion" let-rowData>[...]</ng-template>
    <ng-template pTemplate="summary">[...]</ng-template>
    <ng-template pTemplate="emptymessage">[...]</ng-template>
  </p-table>
</div>
```

### Angular version

14.2.12

### PrimeNG version

14.2.2/14.2.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.15.1

### Browser(s)

Chrome 110

### Expected behavior

No error messages will be printed within the console

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
