### ISSUE TITLE
Dropdown: Setting required triggers formGroup validation 

### ISSUE THREAD

**Issue by Marlaqk** [primefaces/primeng#12677]
### Describe the bug

Having a p-dropdown and validator over a formGroup leads to ExpressionChangedAfterItHasBeenCheckedError. Each time the checkbox value changes the validator is called two times even though the dropdown value does not change.

### Environment

Angular CLI + PrimeNG

### Reproducer

https://stackblitz.com/edit/primeng-dropdown-demo-du5p35

### Angular version

13.3

### PrimeNG version

13.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.11.1

### Steps to reproduce the behavior

1. Check checkkox
2. Uncheck checkbox

### Expected behavior

Changing the checkbox should not trigger the validator again.

**Comment by mehmetcetin01140** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.
