### ISSUE TITLE
p-multiselect: Cannot read properties of undefined (reading 'nativeElement') at CdkVirtualScrollViewport._doChangeDetection (scrolling.js:1073:1)

### ISSUE THREAD

**Issue by MuditMT** [primefaces/primeng#12678]
### Describe the bug

I enable the virtual scrolling and set the itemSize="30" in the p-multiselect so after the click on multiselect I am getting the 
error in the console Cannot read properties of undefined (reading 'nativeElement') at CdkVirtualScrollViewport._doChangeDetection (scrolling.js:1073:1)

### Environment

Angular CLI + PrimeNG

### Angular version

13.3.11

### PrimeNG version

13.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.16.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

Enable the virtual scrolling ->set the itemSize="30" -> Click on p-multiselect

### Expected behavior

getting the error in console 
Cannot read properties of undefined (reading 'nativeElement')
    at CdkVirtualScrollViewport._doChangeDetection (scrolling.js:1073:1)
    at Object.next (scrolling.js:847:1)
    at ConsumerObserver.next (Subscriber.js:91:1)
    at SafeSubscriber._next (Subscriber.js:60:1)
    at SafeSubscriber.next (Subscriber.js:31:1)
    at Subject.js:34:1
    at errorContext (errorContext.js:19:1)
    at ReplaySubject.next (Subject.js:27:21)
    at ReplaySubject.next (ReplaySubject.js:22:1)
    at Object.next (share.js:44:1)

**Comment by volvachev** [comment]
Hi, could you please create stackblitz?

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
