### ISSUE TITLE
Component: Signature

### ISSUE THREAD

**Issue by mbonnevalle** [primefaces/primeng#12687]
### Describe the feature you would like to see added

I am developing an application and we would need the equivalent of [Signature ](https://www.primefaces.org/showcase/ui/input/signature.xhtml?jfwid=ab6a2)available on primefaces in primeng.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
