### ISSUE TITLE
Component: Chips - Component not marking form control as touched when a new item is added

### ISSUE THREAD

**Issue by timandella** [primefaces/primeng#12686]
### Describe the bug

When the Chips component is linked to a Reactive form, then when the user types in some text and presses Enter to add a new chip, even though the form control associated with the component is marked as dirty, it is not marked as touched.

I feel it should be marked as touched in this instance because the form is actually updated at this point, and any validation should be shown.

### Environment

Windows 10

### Reproducer

https://stackblitz.com/edit/github-udq5js?file=src/app/app.component.html

### Angular version

15.0.0

### PrimeNG version

15.0.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.15.1

### Steps to reproduce the behavior

1. Create a component in which the Chips component is linked to a reactive form
2. Enter some text in the Chips component and press Enter

### Expected behavior

Form control should be marked as touched

**Comment by volvachev** [comment]
Hi, i think you not right (check official [doc](https://angular.io/api/forms/AbstractControlDirective#touched)). Right now it works on the `blur` event.

**Comment by timandella** [comment]
Yes, it works on the blur event, but I am suggesting that for the Chips component, when the user enters some text and pressed Enter to add a new chip, the component should also be marked as touched then.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
