### ISSUE TITLE
p-Inputnumber: Reactive Form valueChange Event on Input

### ISSUE THREAD

**Issue by ProfEibe** [primefaces/primeng#12683]
### Describe the feature you would like to see added

Inputnumbers behavior should be like all the other form-components.

Reactive Forms valueChange Event should be called on each keystroke

### Is your feature request related to a problem?

The feature-request is been asked for for two years now!
#9132

**Comment by tmc101** [comment]
I agree.

The current behaviour is counter-intuitive for reactive forms.

Take the very simple case of a form containing a p-inputNumber and a button which is enabled when the form is valid. 

The user enters a valid value for the number, but then cannot click the submit button until they have clicked somewhere else to trigger the model update and allow the button to become enabled.

This makes for a pretty poor user experience.

Why is the current behaviour the desired behaviour?

**Comment by Jonesmann1337** [comment]
I agree, too!

Although this might be fixed within [#11093](https://github.com/primefaces/primeng/pull/11093). Unfortunately, I‘m not able to verify this right now, because I‘m on my phone :-)

**Comment by ActJV** [comment]
another dirty fix is to blur() and focus() it again:
`
protected onInput(i: InputNumber){
  // https://github.com/primefaces/primeng/issues/9132
  // https://github.com/primefaces/primeng/issues/10283
  // https://github.com/primefaces/primeng/issues/12683
  
  if (!i.disabled) {
    const input = i.input.nativeElement;
    input.blur();
    input.focus();
  }
}
`

**Comment by ActJV** [comment]
seems resolved https://github.com/primefaces/primeng/pull/12681
