### ISSUE TITLE
Dropdown: Last item gets hidden by the horizontal scrollbar

### ISSUE THREAD

**Issue by scurk1415** [primefaces/primeng#12695]
### Describe the bug

The last item in a dropdown gets hidden (half hidden) behind the horizontal scrollbar if the option label is longer than the **p-scroller** container (if it overflows)

### Environment

Can be reproduced even on stackblitz so the environment does not really matter

### Reproducer

https://stackblitz.com/edit/primeng-dropdown-demo-mwkpfl?file=src/app/app.component.html

### Angular version

15.2

### PrimeNG version

15.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

Stackblitz version

### Steps to reproduce the behavior

1. Open the stackblitz
2. Click on the dropdown
3. Scroll to the bottom
4. Check the last element (it is half hidden behind the scrollbar)

### Expected behavior

The scrollbar should be under the last item, to not hide it

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
