### ISSUE TITLE
DataTable doesn't update filtered results when source data changes

### ISSUE THREAD

**Issue by ats17** [primefaces/primeng#1269]
Normally, DataTable updates its view any time its value input changes; however, this doesn't happen when a filter is applied. 

To reproduce:
1. Create a DataTable with filtering enabled on at least one column and add sample data
2. Update the data in code and see that the DataTable view updates to match
3. Enter some filter text that passes at least one row
4. Update the data in code (for one of the displayed rows) and see that the DataTable view **does not update to match**

**Comment by ats17** [comment]
I've added pull request #1270 as one way to fix this.

**Comment by ats17** [comment]
Closed pull request #1270 because I buggered the repo. Replaced with PR #1279.

**Comment by cagataycivici** [comment]
Tracking at #1295
