### ISSUE TITLE
In Place: Prevent Click and Keydown functionality not compatible with each other

### ISSUE THREAD

**Issue by straiforos** [primefaces/primeng#12696]
### Describe the feature you would like to see added

The In Place component has a key-down method that is impossible to disable. It would be greatly appreciated if this could be disabled since I have used this for an inline edit in tables to ensure we have the close button, and I added logic to make it not enabled for many columns, if my user clicks the cell with editing disabled then hits return, the in-place is activated but can not be easily deactivated due to the separation of key down and the prevent click input.

### Is your feature request related to a problem?

Yes In Place KeyDown method is not toggle-able. Causing a small edge case for our use cases.

### Describe the solution you'd like

something like prevent click, to prevent key down.

### Describe alternatives you have considered

I tried enhancing my overriding logic for onActivate and onDeactivate. Yet, once active and prevent click is enabled the close button does not deactivate when the key down activates the in-place content. I have added read-only if the cell is not configured to be editable to prevent our users from having the expectation of overriding data.

### Additional context

When prevent click is true (when my cell is configured to not be editable) key down allows activation but not deactivation.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
