### ISSUE TITLE
Table Virtual scroll + Frozen columns is unstable

### ISSUE THREAD

**Issue by Kirik42** [primefaces/primeng#12694]
### Describe the bug

When Virtual scroll is used with more than one frozen column, vertical scroll is unstable, the scroll moves when you go down and when you have scrolled down the table, the scroll is stuck, you can't go back up

### Environment

Angular application

### Angular version

15.2.0

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12

### Browser(s)

Chrome and Firefox last version

**Comment by solanha1999** [comment]
To me is not working as well

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
