### ISSUE TITLE
TabView: Incorrect ink bar position in dialogs when using material design themes

### ISSUE THREAD

**Issue by ks0777** [primefaces/primeng#12698]
### Describe the bug

When using a TabView inside a dialog in combination with any of the material design themes the initial position of the ink bar will be  calculated incorrectly. If the activeIndex is set to anything execpt 0 the ink bar will have an incorrect position

### Environment

The incorrect behavior appears when the Tabview is inside of a dialog and if a material design theme is being used.

### Reproducer

https://github-qztknd.stackblitz.io

### Angular version

15.1.0

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.13.2

### Expected behavior

The ink bar is correctly positioned under the selected header as it is when manually switching between tabs.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
