### ISSUE TITLE
Tabmenu: set as scrollable show forward button when no needed on Mobile Chrome

### ISSUE THREAD

**Issue by paulstelzer** [primefaces/primeng#12702]
### Describe the bug

If you have a tabmenu component set as [scrollable]="true" and the menu items fit in the screen, forward button is shown and does nothing when click it.

This only happens on Android Chrome:

![Screenshot_20221004-100601_Chrome](https://user-images.githubusercontent.com/20501666/193768362-06ccc945-b601-4d9e-a92e-0ce8425b5ba6.jpg)

Copy of #12009 because it was closed although it is not fixed

### Environment

Only happens on Chrome Mobile (Android)

### Reproducer

https://primefaces.org/primeng/tabmenu

### Angular version

15.1

### PrimeNG version

14.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Browser(s)

Android Chrome

### Steps to reproduce the behavior

1. Go to https://primefaces.org/primeng/tabmenu
2. Scroll to the right
3. The forward button will not be removed and last tab is not visible

please keep in mind:  This issue not occurs on Desktop Browsers (this is fixed #11415). So this only occurs on mobile Chrome.

### Expected behavior

Forward and backward buttons should be only shown when necessary.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
