### ISSUE TITLE
TreeTable: coltoggle is not working properly in Edge browser

### ISSUE THREAD

**Issue by DhayaniMeshak** [primefaces/primeng#12701]
### Describe the bug

In edge browser, if i try to toggle any column in treetable component, my page is autoscrolling to top of the page. I'm not seeing this issue with chrome or Firefox browsers. i saw this issue even in primeNG official website. so, adding the site instead of reproducer.

### Environment

https://primeng.org/treetable/coltoggle - even here i can see this issue.

### Reproducer

https://primeng.org/treetable/coltoggle

### Angular version

11.1.0

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

12.16.06

### Browser(s)

Microsoft edge browser

### Steps to reproduce the behavior

1. open the link in microsoft edge browser.
2. scroll to videos column.
3. click to toggle videos column.

each time, page scrolls to table top.

### Expected behavior

Page should retain in videos column as in Google chrome and Firefox browsers.

**Comment by DhayaniMeshak** [comment]
[Screen recording.webm](https://user-images.githubusercontent.com/126853794/223018704-7477c9aa-d8e7-4a67-b5d4-0e0a5a18ae94.webm)
i've updated the screen recording of my issue here.

**Comment by gucal** [comment]
I couldn't replicate the same issue. Can you add your edge version? @DhayaniMeshak 

Updating the browser to the latest version maybe a solution.

**Comment by gucal** [comment]
I tested it in this version but I didn't encounter any problems.

Did you see this issue on another device?

**Comment by DhayaniMeshak** [comment]
Yes, my tester saw this bug in our project, treetable implementation. While I was trying to resolve it, I found this bug in prime ng documentation site itself.

**Comment by DhayaniMeshak** [comment]
These are my windows specifications:
Edition	Windows 10 Enterprise
Version	21H2
Installed on	‎11/‎17/‎2021
OS build	19044.2604
Experience	Windows Feature Experience Pack 120.2212.4190.0

Is it related to any specific machine or version?
@gucal

**Comment by gucal** [comment]
I tried it with Windows 11. I tried it on Mac devices, but it's okay. I can't help you because I can't repeat. I will continue to try to repeat. @DhayaniMeshak

**Comment by DhayaniMeshak** [comment]
As a temporary fix for my project, I'm scrolling the page again to the Node, which is clicked. Anybody facing this issue, can use this method to resolve it.

 ` @ViewChild(TreeTable ,{static: false}) treetable: TreeTable;

  // Method called on expansion of row
onNodeExpand(event) {
    this.checkBroswerToResetScroll(event);  
}

  // Method called on collapse of row
  onNodeCollapse(event) {
    this.checkBroswerToResetScroll(event); 
  }

  checkBroswerToResetScroll(event){
    const isIEOrEdge = /msie\s|trident\/|edg\//i.test(window.navigator.userAgent); // to check the browser
    const index = this.treetable.serializedValue.findIndex(element => element.node.data.Id === event.node.data.Id); // comparing the node ID with treetable nodes id
//apply code changes only to edge browser
    if(isIEOrEdge) { 
      setTimeout(() => {
        document.getElementById('main-content-root').scrollTo({
          top: ( 74 * index) + 102, // 74 - each node height, 102 - calculated fix height for our page
          behavior: 'smooth'
        });
      }, 160); // as tree table scroll delay time is 150, I've given 160
    }
  }`
  
  This will make your page scroll to the clicked node with a scroll effect. 
  @gucal This is temporary fix by me. Incase you guys able to replicate issue and found fix, please let me know.

**Comment by ebernste123** [comment]
@DhayaniMeshak Thank you for documenting this issue. I am also seeing the same thing in both our treeview/application and the primeng demo. 

It is not browser version specific as we have 3 people in the office that can reproduce the issue. We also have 3 other people that do not see the issue. Everyone is running the same (latest) version of Edge. Most are on MS Windows 10 Professional. 

It seems like it has something to do with the machine and software running on it, as I have two computers with identical MS Edge build and one shows the issue, the other one does not. 

@gucal and @cetincakiroglu I am more than happy to help debug this issue with you on one of our machines, just let me know the easiest way to do it.

I just checked the MS Edge version and updated it. Both versions have the issue. 
Version 112.0.1722.68 (Official build) (64-bit)
Version 113.0.1774.35 (Official build) (64-bit)

Thank you in advance,
Eran

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
