### ISSUE TITLE
OverlayPanel: strange position behavior when append to a fixed element

### ISSUE THREAD

**Issue by Adrii77** [primefaces/primeng#12709]
### Describe the bug

In my project, I have a `position: fixed ` topbar containing a bell icon. When clicking on the bell, an overlay panel appears and shows notifications (as Facebook). Then, 2 problems :

1) Without [appendTo] : the overlay panel is correctly positioned, but if we scroll in the document, the panel follows the scroll... 

2) With [appendTo] : the overlay panel stay attaches to the bell icon during scroll, great ! But, if we decide to open the overlay panel after scrolling : the overlay panel appears detached from the bell.  

I created a stackblitz on Prime 13, but the problem persists on version 15.

### Environment

Angular 15, Prime 15 app.

### Reproducer

https://stackblitz.com/edit/primeng-overlaypanel-demo-2jnkpi?file=src/app/app.component.html

### Angular version

15.2.1

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14.2

### Browser(s)

Chrome 108

### Steps to reproduce the behavior

1. Scroll down a bit
2. Click on the button
3. Close the panel
4. Reproduce from step 1

For the initial problem : 
1. Remove `[appendTo]="pouet"` 
2. click on the button
3. Scroll down

### Expected behavior

Overlay panel should always stay attaches to its element (which is located inside a `position: fixed ` container, such as topbar in my case), even if we scroll. If we scroll first (before showing the panel), it should appeared attaches to its element.

**Comment by dav021** [comment]
I have same issue

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
