### ISSUE TITLE
AutoComplete: Option autoHighlight should ignore group entries

### ISSUE THREAD

**Issue by MetroMarv** [primefaces/primeng#12717]
# Observed behavior

When enabling the `autoHighlight` option of an AutoComplete component, that is a grouped AutoComplete, the group header is autohighlighted.

See following [StackBlitz](https://stackblitz.com/edit/primeng-autocomplete-demo-zfzzy5). When typing "Ham" the option "Hamburg" is the first valid answer. But if I now press enter, the option "Germany" is selected.

![image](https://user-images.githubusercontent.com/9006725/223459426-e86cc151-d827-4819-9de7-4ead2ac6f781.png)

And after pressing enter

![image](https://user-images.githubusercontent.com/9006725/223459588-15dc2783-f2a0-4afb-b1d7-9e154a07cebf.png)

# Expected behavior

The first valid answer is highlighted (e.g. with some background) and when pressing enter that answer is selected.

**Comment by JudahKeelin** [comment]
Any updates or work arounds on this? Currently running into the same issue.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
