### ISSUE TITLE
p-tree: Parent node always undefined in node selection events when Virtual Scrolling is enabled

### ISSUE THREAD

**Issue by nitrousdigital** [primefaces/primeng#12718]
### Describe the bug

`event.node.parent` is always `undefined` in `onNodeSelect` of a PrimeNG tree **when virtual scrolling is enabled**

 

### Environment

Discovered in PrimeNG 11.4.10 and reproduced in 15.2.0 (see the attached stackblitz for a demo)

### Reproducer

https://stackblitz.com/edit/primeng-treeselection-demo-yvxqt7?file=src/app/app.component.html

### Angular version

14.1.3

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.13.2

### Steps to reproduce the behavior

1. Build a tree (without virtual scrolling enabled) and ensure all `parent` references are set in the `TreeNode` model instances. 
2. Select a node in the tree
3. Notice that the `event.node.parent` will be defined for non-root nodes.
4. Now change the display template for your tree, to enable virtual scrolling by adding the following to the `<p-tree>`
```
[virtualScroll]="true"
[virtualNodeHeight]="33"
scrollHeight="200px"
```
5. Select a node in the tree
6. Notice that now the `event.node.parent` will be `undefined` for all nodes.

### Expected behavior

`event.node.parent` should contain a valid reference to the parent node for all non-root nodes, even when virtual scrolling is enabled.

**Comment by ZawadaMatt** [comment]
Any news ?

**Comment by cetincakiroglu** [comment]
Fixed in https://github.com/primefaces/primeng/pull/15072
