### ISSUE TITLE
Calendar: Add customized input labels for today, tomorrow, and yesterday dates

### ISSUE THREAD

**Issue by benjaminbekes** [primefaces/primeng#12716]
### Describe the feature you would like to see added

Could be useful when the user has clicked on the 'today' date or 'tomorrow' date to see the label 'Tomorrow', 'Today', or any custom label for these dates. 
Could be fancier and quicker to understand that 7.3.2023 is today.
Just for the inspiration:
![image](https://user-images.githubusercontent.com/29887220/223457174-ad8d4bd7-281d-497a-993f-9c640a12e5c3.png)

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
