### ISSUE TITLE
p-editor: text is cleared when webpage is translated by google translate.

### ISSUE THREAD

**Issue by RichardCar** [primefaces/primeng#12719]
### Describe the bug

when webpage is using google translate like img:
![image](https://user-images.githubusercontent.com/25970055/223466499-88af7c14-d772-414c-a127-08e32de8b489.png)

p-editor component doesn't work. if you try type any text, then it is erased/cleared automatically. 

![ezgif-5-1530666998](https://user-images.githubusercontent.com/25970055/223476803-a1332f1a-e333-4b0c-99ef-5f25099ee7a8.gif)

### Environment

   _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 15.1.1
Node: 16.13.2
Package Manager: npm 8.1.2
OS: win32 x64

Angular: 15.1.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... google-maps, platform-browser, platform-browser-dynamic
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.1
@angular-devkit/build-angular   15.1.1
@angular-devkit/core            15.1.1 (cli-only)
@angular-devkit/schematics      15.1.1 (cli-only)
@angular/cli                    15.1.1
@angular/fire                   7.5.0
@schematics/angular             15.1.1 (cli-only)
rxjs                            7.8.0
typescript                      4.9.4

### Angular version

15.1.0

### PrimeNG version

15.0.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.13.2

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
