### ISSUE TITLE
Can't bind to 'value' since it isn't a known property of 'p-dataTable'.

### ISSUE THREAD

**Issue by hkashlan** [primefaces/primeng#1271]
Hi Yesterday I installed angular seed

and I followed https://github.com/mgechev/angular-seed/wiki/Add-PrimeNG

and http://www.primefaces.org/primeng/#/datatable

but I am getting 
Unhandled Promise rejection: Template parse errors:
Can't bind to 'value' since it isn't a known property of 'p-dataTable'.
1. If 'p-dataTable' is an Angular component and it has 'value' input, then verify that it is part of this module.
2. If 'p-dataTable' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.

**Could someone help me to integrate angular seed with primefaces for datatabe?**

**Comment by cagataycivici** [comment]
You haven't seem to imported DataTableModule.

**Comment by hkashlan** [comment]
you are right the solution was:

inside home.module.ts

import { DataTableModule } from 'primeng/primeng';

imports: [CommonModule, SharedModule, DataTableModule],

Thank you @cagataycivici

**Comment by sga-lalitesh** [comment]
I'm facing the same problem for OrderListModule.
`Can't bind to 'value' since it isn't a known property of 'p-orderList'.`
Imported
import {OrderListModule} from 'primeng/components/orderlist/orderlist';
in app.component.ts

**Comment by hkashlan** [comment]
@sga-lalitesh sorry for delay 

could you do a simple plnkr?
http://plnkr.co/edit/Qi2Nw2imLpDUF8NJinYw?p=preview

**Comment by kruthi12434354657687** [comment]
Can't bind to 'value' since it isn't a known property of 'p-growl' .... i have got this error while compiling could anyone clarify this please............
