### ISSUE TITLE
p-carousel: index for paging not working correctly when autoPlayInterval is set

### ISSUE THREAD

**Issue by DavideMin** [primefaces/primeng#12712]
### Describe the bug

Carousel component not working correctly when the property  `circular` is set to `true` and `autoPlayInterval` is used (tested with value 3000).
Index is not calculated correctly.

Potential cause of error (local variables are not updated in the correct way):

![6ac95f6f-37f9-4ace-8062-eb105035ac21](https://user-images.githubusercontent.com/126673828/223158957-bcbe2d80-883d-44be-bc5e-1dd8b843cb80.jpg)

Furthermore, the properties seem not to work if the tag<p-carousel> is inside a container with `*ngIf`  structural directive.

### Environment

**Angular** 15.1.5
**PrimeNG** 15.2.0

### Angular version

Latest

### PrimeNG version

Latest

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.10.0

**Comment by volvachev** [comment]
Hi, could you add an example on stackblitz?

**Comment by DavideMin** [comment]
An example for `*ngIf` structural directive not working:
[https://stackblitz.com/edit/primeng-carousel-demo-w3zygr?file=src/app/app.component.ts]()

As for the index problem, I will try to reproduce the bug on stackblitz when I find some time

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
