### ISSUE TITLE
Sidebar Custom Content rendering error

### ISSUE THREAD

**Issue by DarienF** [primefaces/primeng#12728]
### Describe the bug

Custom content (header, body, footer templates) not rendering correctly 

```
<p-sidebar
    [(visible)]="displaySidebar"
    position="right"
    [dismissible]="true"
  >
    <ng-template pTemplate="header">Header Content</ng-template>
    <ng-template pTemplate="content">Body Content</ng-template>
    <ng-template pTemplate="footer">Footer Content</ng-template>
  </p-sidebar>
```

Link to reproduce:
https://stackblitz.com/edit/github-ntfeae?file=package.json,src%2Fapp%2Fapp.component.html

### Environment

"primeflex": "^3.2.1",
"primeicons": "^6.0.1",
"primeng": "^15.0.0",

### Reproducer

https://stackblitz.com/edit/github-ntfeae?file=package.json,src%2Fapp%2Fapp.component.html

### Angular version

14.0.0

### PrimeNG version

15.0.0

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

v18.14.0

**Comment by arthurb4a** [comment]
I have the same issue!

primeng@15.2.0
angular@15.2

**Comment by KevinCarpNotrs** [comment]
Same deal as arthur, It only seems to render like so for me inside the content div (There's a header div with a close button and an empty footer space that seems to take up about a quarter of space)

```
<p-sidebar>
<!--content renders here-->
</p-sidebar>
```
The provided templates for Headers/Content/Footers will fail to render.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
