### ISSUE TITLE
p-autoComplete |  showClear property  not clear the ngModel value

### ISSUE THREAD

**Issue by pjhifo** [primefaces/primeng#12729]
### Describe the bug

I enabled the showClear property on my p-autoComplete component, but when I clicked the × button, the value on his control was cleared, but the ngModel's value remained.
I have tried to upgrade the version, but I have upgraded to the latest version and still have this problem.
I tried StackBlitz on the site and also had this problem.

### Environment

Angular version
15.2.2

PrimeNG version
15.2.0

### Angular version

15.2.2

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.13.2

**Comment by flortsch** [comment]
I think autocomplete should clear it's ngModel value as well. As a workaround, one can use the onClear hook to reset the ngModel.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
