### ISSUE TITLE
Tooltip support for `p-tree` expand/collapse icon

### ISSUE THREAD

**Issue by sh977218** [primefaces/primeng#12726]
### Describe the feature you would like to see added

It would be nice to have support tooltip for expand/collapse toggler in tree module.

### Is your feature request related to a problem?

I thought of having customize ngTemplate, but pTemplate is not able to customize the expand/collapse icon. Thus I cannot add my own tooltip directive on those icons.

### Describe the solution you'd like

Having p-tooltip attach to p-tree expand/collapse icon, with optional input string

### Describe alternatives you have considered

Currently there is no way to work around for this.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
