### ISSUE TITLE
InputNumber | does not update the input value onInput

### ISSUE THREAD

**Issue by cetincakiroglu** [primefaces/primeng#12733]
Problem: Value only updates on blur and on focus events, cannot subscribe to valueChanges on input with reactive forms. Can't detect input change.

Expected behavior: Value updates on user input.

**Comment by cetincakiroglu** [comment]
solved in https://github.com/primefaces/primeng/commit/558fed57c2dffb85ecc1704ab78d5e03738a6f1b

**Comment by nathanvj** [comment]
Is this the same issue as the one I mentioned in Discord?

I want to update the value of an input field when the form value changes (e.g. user inputs a number that doesn't match a specific requirement, I want to reset it).

See StackBlitz, you can see that the hello is printed to the console and the form.getRawValue is updated, but the second time you change the input field it does not reflect the actual value anymore. [StackBlitz here.](https://stackblitz.com/edit/primeng-inputnumber-demo-6rpqtl?file=src/app/app.component.ts)

So steps to reproduce:
- Input random number, e.g. 40
- See that the value gets updated to 100 immediately
- Do it again
- Notice that it doesn't get updated to 100 in the UI (but still gets updated in the actual form value)

**Comment by nathanvj** [comment]
Is this the same issue as the one I mentioned in Discord?

I want to update the value of an input field when the form value changes (e.g. user inputs a number that doesn't match a specific requirement, I want to reset it).

See StackBlitz, you can see that the hello is printed to the console and the form.getRawValue is updated, but the second time you change the input field it does not reflect the actual value anymore. [StackBlitz here.](https://stackblitz.com/edit/primeng-inputnumber-demo-6rpqtl?file=src/app/app.component.ts)

So steps to reproduce:
- Input random number, e.g. 40
- See that the value gets updated to 100 immediately
- Do it again
- Notice that it doesn't get updated to 100 in the UI (but still gets updated in the actual form value)

**Comment by cetincakiroglu** [comment]
> Is this the same issue as the one I mentioned in Discord?
> 
> I want to update the value of an input field when the form value changes (e.g. user inputs a number that doesn't match a specific requirement, I want to reset it).
> 
> See StackBlitz, you can see that the hello is printed to the console and the form.getRawValue is updated, but the second time you change the input field it does not reflect the actual value anymore. [StackBlitz here.](https://stackblitz.com/edit/primeng-inputnumber-demo-6rpqtl?file=src/app/app.component.ts)
> 
> So steps to reproduce:
> 
> * Input random number, e.g. 40
> * See that the value gets updated to 100 immediately
> * Do it again
> * Notice that it doesn't get updated to 100 in the UI (but still gets updated in the actual form value)

Thanks for steps, I'll create a case in this fix and test the situation.

**Comment by cetincakiroglu** [comment]
Hi @nathanvj 
I've tried the steps you've mentioned on this solution and the cases are different. I've opened an issue for yours. 
https://github.com/primefaces/primeng/issues/12765

**Comment by cetincakiroglu** [comment]
fixed in https://github.com/primefaces/primeng/commit/558fed57c2dffb85ecc1704ab78d5e03738a6f1b
