### ISSUE TITLE
TreeSelect: Filter functionality requires the "key" property but this is not in the sample data or the stackblitz

### ISSUE THREAD

**Issue by greg0rym** [primefaces/primeng#12731]
### Describe the bug

TreeSelect: Filter functionality requires the Key property but this is not in the sample data here https://primeng.org/treeselect or the stackblitz here https://stackblitz.com/edit/primeng-treeselect-demo?file=README.md. Without the key property, selected items do not show as selected when closing and reopening the treeselect.

Unfortunately the stackblitz on the documentation does not allow Filtering as it used an older version of primeng

### Environment

not environment specific

### Angular version

15.1.2

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Steps to reproduce the behavior

1. Create a treeselect using the data provided in the doucumentation https://primeng.org/treeselect
2. Add [filter]="true"
3. Select an item
4. Close the treeselect
5. Reopen
6. Selected item is not selected in treeselect

### Expected behavior

The documentation should specify the key property in the sample data and the stackblitz should be updated to demonstrate the filter functionality.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
