### ISSUE TITLE
PrimeNg Table (version 15) can crash in "updateStickyPosition" if the cell is destroyed

### ISSUE THREAD

**Issue by WesleySSmith** [primefaces/primeng#12737]
### Describe the bug

The PrimeNg table (version 15.2.0) can crash in `updateStickyPosition` if the cell is destroyed.

The problem is that in the `FrozenColumn` classes's  `ngAfterViewInit()` method, it sets a timer that runs after 1000ms and calls `updateStickyPosition`.

https://github.com/primefaces/primeng/blob/15.2.0/src/app/components/table/table.ts#L2738

But, the cell might be destroyed by the time 1 second has elapsed.  In that case, the code will crash when trying to access `this.el.nativeElement.parentElement.nextElementSibling` here: https://github.com/primefaces/primeng/blob/15.2.0/src/app/components/table/table.ts#L2762

Maybe it would be best to implement `ngOnDestroy` and stop the timer (if it exists).  Or add code to `updateStickyPosition` to return quickly if the component has been destroyed.

Also, the approach of creating a timer for each frozen cell can cause many timers to be created (potentially hundreds).  This can cause problems for Angular unit tests because you can easily end up with more than 20 pending timers, and that will make Angular's flush() function fail with an error:  `Error: flush failed after reaching the limit of 20 tasks. Does your code use a polling timeout?`  Ideally, you would find a way to replace the overall approach of setting a timer per cell with something that didn't use timers at all, or at least uses fewer of them.

### Environment

N/A

### Reproducer

https://stackblitz.com/edit/github-vwhhsn?file=src/app/app.component.html

### Angular version

15.2.1

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

N/A

### Steps to reproduce the behavior

Run the project on Stackblitz.
View the debug console:

```
ERROR TypeError: Cannot read properties of null (reading 'nextElementSibling')
    at FrozenColumn.updateStickyPosition (primeng-table.mjs:2685:65)
    at eval (primeng-table.mjs:2664:18)
    at timer (zone.js:3083:47)
    at ZoneDelegate.invokeTask (zone.js:434:35)
    at eval (core.mjs:24046:55)
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:24046:36)
    at ZoneDelegate.invokeTask (zone.js:433:64)
    at Object.onInvokeTask (core.mjs:24347:33)
    at ZoneDelegate.invokeTask (zone.js:433:64)
    at Zone.runTask (zone.js:205:51)
```

### Expected behavior

No javascript errors

**Comment by kondam** [comment]
Any update on this issue? we use 14.2.3 and seeing same issue.

**Comment by DailisLangovskis** [comment]
Hello, has there been some development done to resolve this issue?

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
