### ISSUE TITLE
Table: 'this.el.nativeElement.parentElement is null' for frozen columns which are dynamically generated

### ISSUE THREAD

**Issue by Kisters-BS** [primefaces/primeng#12748]
### Describe the bug

I generate my table columns with frozen columns dynamically and newly assign them on every update.
When I update the table columns I get the error:
![](https://user-images.githubusercontent.com/84901454/225013611-cce1812c-a5db-4c3d-b22c-57a5dd59c51e.png)
The error is from the **updateStickyPosition** function where the parentElement is undefined:
let filterRow = this.el.nativeElement.**parentElement**.nextElementSibling;

### Environment

See stackblitz

### Reproducer

https://stackblitz.com/edit/github-w2zrds

### Angular version

15.2.2

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.19.0

### Browser(s)

All

### Steps to reproduce the behavior

1. Click on the update button
2. See error message in the console

### Expected behavior

No error thrown

**Comment by digeomel** [comment]
I am sorry, this bug was identified on version 15 but the bugfix was merged only on version 16. Can we please have it merged on version 15, too? We cannot upgrade to 16 just yet.
