### ISSUE TITLE
p-accordion in p-panel

### ISSUE THREAD

**Issue by stutu-hun** [primefaces/primeng#12749]
p-accordion is unclosable when it is in a toggleable p-panel:

`<p-panel [toggleable]="true">
  <p-accordion>
    <p-accordionTab header="Header 1">
      Content 1
    </p-accordionTab>
    <p-accordionTab header="Header 2">
      Content 2
    </p-accordionTab>
    <p-accordionTab header="Header 3">
      <p-accordion>
        <p-accordionTab header="Header 1">
          Content 1
        </p-accordionTab>
        <p-accordionTab header="Header 2">
          Content 2
        </p-accordionTab>
        <p-accordionTab header="Header 3">
          Content 3
        </p-accordionTab>
      </p-accordion>
    </p-accordionTab>
  </p-accordion>
</p-panel>`

angular version: 15.2.0
primeng version: 15.2.0

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
