### ISSUE TITLE
Component: Inputtext with Floatlabel

### ISSUE THREAD

**Issue by Triskae** [primefaces/primeng#12742]
### Describe the bug

When using PinputText with a floatlabel and an error under the input, the float label is slightly offset.

### Environment

Production environment

### Reproducer

https://stackblitz.com/edit/primeng-floatlabel-demo-cfrgpw?file=src/app/app.component.html

### Angular version

14.2.2

### PrimeNG version

14.2.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

19.3.0

### Expected behavior

No offset when one or more <small> tags are present and have p-error tag.

**Comment by Triskae** [comment]
Hello, it's still the case with angular and primeng 16.

[Stackblitz](https://stackblitz.com/edit/qvcuas?file=src%2Fapp%2Fdemo%2Fmessages-inline-demo.html)

**Comment by maxcabourg** [comment]
Hello,

It's still the case with version 21. It's because the label is positioned  with absolute, relatively to the height of the p-floatLabel box which also contains the tag containing the error message. It should be positioned relatively to the input.
