### ISSUE TITLE
Primeng calendar timeOnly unconfigured

### ISSUE THREAD

**Issue by rafaelcb21** [primefaces/primeng#1275]
After primeng evolves to version "^1.0.0-rc.3", the following problem appears with the calendar:

`<p-calendar [(ngModel)]="date7" [timeOnly]="true"></p-calendar>`

![primeng-calendar](https://cloud.githubusercontent.com/assets/9912894/20211032/b072d1ec-a7e3-11e6-9e8d-4130b7de323c.png)

I've tried everything and I can not change.

Can you help me?

**Comment by Mrtcndkn** [comment]
It works fine locally.How can i replicate this?

**Comment by rafaelcb21** [comment]
I found the problem, I was referencing the `primeng.min.css` file of the last version. After I reference the file of the same version the problem did not appear any more
