### ISSUE TITLE
Floating label for dropdown control with placeholder

### ISSUE THREAD

**Issue by flawesomesoft** [primefaces/primeng#12750]
### Describe the bug

When using a floatlabel for a dropdown control there is a strange behaviour when adding a placeholder.

The opacity for .p-float-label .p-placeholder is set to 0.
When you click inside the dropdown control it is set to 1.

This could be connected to a prior bugfix for issue [#11508](https://github.com/primefaces/primeng/issues/11508)

Refer also the the linked stackblitz for a showcase of the issue.

### Environment

Using Angular 14 with PrimeNG components tested on Chrome and Firefox

### Reproducer

https://stackblitz.com/edit/github-wtcruv-w4ls4t?file=src/app/app.component.html

### Angular version

14.2.10

### PrimeNG version

14.2.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.19.0

### Browser(s)

Chrome, Firefox

### Steps to reproduce the behavior

Creating a float label for dropdown control and adding a placeholder.

By default the placeholder is hidden.
When you click inside the dropdown control the placeholder is visible.

Refer to linked stackblitz for a showcase of the issue.

### Expected behavior

Floating label for a dropdown control should behave like for a input control as long as no entry was selected in the dropdown.

**Comment by flawesomesoft** [comment]
My current workaround is setting the opacity to 1 via CSS styling.
```CSS
::ng-deep some-component-selector {
.p-float-label .p-placeholder {
  opacity: 1;
}
```

The input control

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
