### ISSUE TITLE
Tooltip: position bottom breaks on dropdown

### ISSUE THREAD

**Issue by smartm0use** [primefaces/primeng#12754]
### Describe the bug

Using Tooltip on Dropdown is not working as expected. In case of position "bottom" the tooltip appears too low.

![image](https://user-images.githubusercontent.com/5399265/225269798-f4ee2a66-433a-4b07-af4a-a6e6b9fd3790.png)

### Environment

I'm using Primeflex 3.3.0.

### Reproducer

https://stackblitz.com/edit/primeng-primeflex-formlayout-demo-mgdaxg

### Angular version

15.2.1

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.10.0

### Steps to reproduce the behavior

Add `pTooltip="Some text" tooltipPosition="bottom"` to a Dropdown component.

### Expected behavior

Show the tooltip in the right position, as happen with other form elements, such as this:

![image](https://user-images.githubusercontent.com/5399265/225270018-aedf03b1-4ca4-475c-9f28-d5960727c650.png)

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
