### ISSUE TITLE
Avatar: Add support for referrer policy on the underlying img

### ISSUE THREAD

**Issue by jeremylcarter** [primefaces/primeng#12751]
### Describe the feature you would like to see added

It would be great if the avatar and avatar group components supported `referrerpolicy` setting on the underlying img element.

### Is your feature request related to a problem?

The problem is that I occassionally get 403's on content from the `googleusercontent.com` domain which is where most of my avatars are referenced.

For more information see: https://stackoverflow.com/questions/56242788/http-403-on-images-loaded-from-googleusercontent-com

### Describe the solution you'd like

Potentially a `noReferrer` boolean or similar.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
