### ISSUE TITLE
Feature request or usage question

### ISSUE THREAD

**Issue by eqvis** [primefaces/primeng#12755]
Hi,

I'm using treetable and it looks good. Now I want to change the styling (css) depending on the level of the node.
Is this possible? It would be cool to have some custom attribute filled with this information instead of style-attributes generated by primeng (margin: 16*$level px)

Greetings,
Mayra

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
