### ISSUE TITLE
AutoComplete: Lazy not called

### ISSUE THREAD

**Issue by ProfEibe** [primefaces/primeng#12753]
### Describe the bug

When using Lazy, the onLazyLoad callback is never called

### Environment

Angular and PrimeNG 15

### Angular version

15.2

### PrimeNG version

15.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.17.0

### Browser(s)

latest Chrome

### Expected behavior

when typing letters in the input field, onLazyLoad should be called to load a subpart of the whole result.

**Comment by wildgarden** [comment]
I I can confirm this. When browsing the code https://github.com/primefaces/primeng/blob/master/src/app/components/autocomplete/autocomplete.ts the implementation seems incomplete.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
