### ISSUE TITLE
p-inputmask: when adding required property cursor doesn't go at the begining of mask

### ISSUE THREAD

**Issue by mgrzego3** [primefaces/primeng#12757]
### Describe the bug

If required property is added to p-inputmask behaviour of cursor changes. Instead of going at the beginning of the mask it goes closest to place where click occurs. 

Click in the middle of p-inputmask **with** required property:
![image](https://user-images.githubusercontent.com/60580202/225564006-6a999567-e798-4367-9202-ce67fe8fc6f0.png)
Click in the middle of p-inputmask **without** required property:
![image](https://user-images.githubusercontent.com/60580202/225564349-175e3811-1055-4904-9ac8-8bb80e240cc9.png)

### Environment

ng serve

### Reproducer

https://primeng-inputmask-demo-2qppbg.stackblitz.io

### Angular version

15.1.3

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14.0

### Browser(s)

firefox, chrome

### Steps to reproduce the behavior

1. Click in the middle or near to right side of p-inputmask with required property
2. Cursor is in the middle or at the end of mask

### Expected behavior

Cursor should be at the beginning of mask

**Comment by nicolasnevraumont** [comment]
I noticed a similar behaviour but linked to the autocomplete property.

Setting autocomplete="off" prevents from having the cursor moving into or at the end of the mask.

**Comment by markleppke** [comment]
It also prevents the user from inputing a value, which is a bit of an usability issues. A user enters the field with the cursor at the end and tries to input a value, expecting something to show up in the field, but there is no repsonse.

**Comment by TheYouIsHere** [comment]
Bug is still there. As @nicolasnevraumont said, I had to set autocomplete="off" as a workaround.

**Comment by AYGTX** [comment]
Bug is still there. especially when you slide your mouse while mousedown over the field.

**Comment by jmrobbins13** [comment]
If an autocomplete will appear for the masked field when clicked it does not start at the beginning, likewise, if I have an autocomplete visible on another field and then click into the masked field it also does not start at the beginning.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
