### ISSUE TITLE
InputNumber | cannot set value when using reactiveForms

### ISSUE THREAD

**Issue by cetincakiroglu** [primefaces/primeng#12765]
- bug: value can be set but the component keeps updating the value
- expected behavior: Value shouldn't be updated.

[Reproducer.](https://stackblitz.com/edit/primeng-inputnumber-demo-6rpqtl?file=src/app/app.component.ts)

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
