### ISSUE TITLE
Component: Title

### ISSUE THREAD

**Issue by Pierre-The-Rock-Bernier** [primefaces/primeng#12767]
### Describe the bug

for InputNumber, for tabindex:

PrimeNG documentation (available at https://primeng.org/inputnumber) writes that the tabindex is of type number

opening the source code of inputnumber.d.ts, I see that the type is string

when I use it, the compiler generates the error "Type 'number' is not assignable to type "string" ngtsc(2322)

my code:
              <p-inputNumber
                [tabindex]="2*i+1"
              ....
              />

note that the same [tabindex]="2*i+1" works great for other PrimeNG components

My resolution:
edit inputnumber.d.ts, and change the declaration (on line 20 in my version of it) to
      tabindex: number;

then my code compiles

### Environment

latest Angular version:15.2 
latest PrimeNG version: 15.2

### Angular version

15.2

### PrimeNG version

15.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

19.8.1

### Browser(s)

latest Chrome version

### Steps to reproduce the behavior

              <p-inputNumber
                [tabindex]="2*i+1"
               ...
              />

### Expected behavior

I would expect the code to compile. It does for the other components.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
