### ISSUE TITLE
[p-tree] should not select node on right click if contextMenu is set #9520

### ISSUE THREAD

**Issue by dmaf87** [primefaces/primeng#12763]
### Describe the bug

any update for the #9520 issue? 

### Environment

Chrome browser on Windows 11

### Angular version

13.3.9

### PrimeNG version

13.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v14.18.0

**Comment by helkatz** [comment]
Still not fiexed since 2020!!!

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
