### ISSUE TITLE
p-dropdown: ExpressionChangedAfterItHasBeenCheckedError for 'p-inputwrapper-focus'

### ISSUE THREAD

**Issue by ES-Six** [primefaces/primeng#12778]
Hello PrimeNG,

### Describe the bug

When I double click on a p-dropdown selector, the given error happened :
![image](https://user-images.githubusercontent.com/13310075/226692529-961a99c1-276a-4cf4-8bdd-477d99b9b5a3.png)

Screenshot on Stackblitz :
![image](https://user-images.githubusercontent.com/13310075/226704768-be37a95c-80dd-4726-8ed0-f8f5efbb4c6f.png)

Stackblitz hosted demo joined to this issue.

### Environment

Basic as possible, Angular + PrimeNG only

### Reproducer

https://stackblitz.com/edit/angular-dndqap?file=src/main.ts

### Angular version

15.2.0

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.15.1

### Browser(s)

ALL

### Steps to reproduce the behavior

1) Open the Stackblitz demo
2) Find the selector on the page and fast double click (faster as possible) multiple times on it (5 or more times)
3) Look at the console for the error

### Expected behavior

No error on the console

Thanks for reading.

**Comment by ES-Six** [comment]
I think it's related to this part of the p-dropdown code :


Inside PrimeNG `components/dropdown/dropdown.ts` at line 273 : https://github.com/primefaces/primeng/blob/15.2.0/src/app/components/dropdown/dropdown.ts#L273

Code extract for PrimeNG `components/dropdown/dropdown.ts` at line 273 :
```ts
    host: {
        class: 'p-element p-inputwrapper',
        '[class.p-inputwrapper-filled]': 'filled',
        '[class.p-inputwrapper-focus]': 'focused || overlayVisible' <-- here
    },
```

**Comment by ES-Six** [comment]
Need triage, I suggest to mark this issue as bug, anyone ?

**Comment by jacqueslareau** [comment]
Hello, just to mention I also experience this bug with the autocomplete component. Might be the same thing.

**Comment by ES-Six** [comment]
Is primeng open to PR ?

**Comment by ES-Six** [comment]
Here is an updated stackblitz as this bug remains with the latest version of primeng and Angular 16.

https://stackblitz.com/edit/angular-abpgi6

Simply fast double on a selector to trigger the error in the console...

**Comment by ddotsdot** [comment]
It appears that there is a similar issue related to `primeng/inputmask`. When `autofocus` property is set to `true`, an ExpressionChangedAfterItHasBeenCheckedError is triggered. 

I adapted @ES-Six's stackblitz example accordingly.

[https://stackblitz.com/edit/angular-xkcwnv](https://stackblitz.com/edit/angular-xkcwnv?devToolsHeight=33&file=src%2Fmain.ts)
(If you don't see the error log on first load, press reload button)

Does anyone have a quick fix to that?

If `[autoFocus]="false"`, there won't be any error. 

PS: Feel free to move this comment to another issue if desired...

**Comment by ashikjs** [comment]
@ES-Six  can you check it right now, I can not reproduce it .

**Comment by ES-Six** [comment]
> @ES-Six can you check it right now, I can not reproduce it .

Hello @ashikjs ,

Yes, the bug is still here.

Here is an updated sample with the latest version of primeng and Angular 16 :

[https://stackblitz.com/edit/angular-qqgbci](https://stackblitz.com/edit/angular-qqgbci)

Here is a demo video :

[Capture_video_du_2023-08-31_18-10-31.webm](https://github.com/primefaces/primeng/assets/13310075/7d745041-318e-4851-8656-c7f58119d661)


I edited the stackblitz to make the bug easier to reproduce as it seems the error is easier to trigger when the selector contains a lot of values (let's say 150 values). More the selector is slow, the easier it is to trigger the error.

Just click fast 4 or 5 times on the selector in the stackblitz and the error will trigger in the browser console :

![image](https://github.com/primefaces/primeng/assets/13310075/621df830-be56-4a23-b988-918d35eadd0c)

Additionally, you can trigger the bug by focusing the selector and keep pressing the space bar for about 3 seconds and the same error will spam the browser console :)

**Comment by sandeepagrawal-proto** [comment]
Hi Any updates on this bug please?

**Comment by RinoGaetano94** [comment]
+1

**Comment by pete4dev** [comment]
+1

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
