### ISSUE TITLE
Treetable: add frozenValue / frozen row for virtual scrolling

### ISSUE THREAD

**Issue by RIDY01** [primefaces/primeng#12773]
### Describe the feature you would like to see added

It would be nice to have an option to always freeze / fix a row using virtual scrolling. 
Currently, if you fix a row using CSS, it disappears after scrolling outside the viewport. 

### Describe the solution you'd like

To add a freeze row / frozen rows property in treetable using virtual scrolling. 

### Describe alternatives you have considered

It works using CSS: 

.sticky_row {
  position: sticky !important;
  top: 0;
  z-index: 99999;
}

But it disappears after the virtual scroller shows new rows.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
