### ISSUE TITLE
Component: Title

### ISSUE THREAD

**Issue by oixan** [primefaces/primeng#12772]
### Describe the bug

Current behavior
Event fired: onBlur

Expected behavior
Event fired: onSelect

### Environment

Windows 10

### Reproducer

https://stackblitz.com/edit/primeng-autocomplete-demo-49evvu?file=src%2Fapp%2Fapp.component.ts

### Angular version

15.1.4

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v16.13.2

### Steps to reproduce the behavior

Click the autocomplete
Digit: i
With mouse click 1 item you prefer

### Expected behavior

Event fired: onSelect

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
