### ISSUE TITLE
Resources package export uses deprecated folder mapping

### ISSUE THREAD

**Issue by bertrandE** [primefaces/primeng#12777]
### Describe the bug

Following the PR that added the `exports` in the library `package.json` (see https://github.com/primefaces/primeng/pull/11967), it seems that the way the `resources` folder is mapped is deprecated:

```
(node:26976) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./resources/" in the "exports" field module resolution of the package at C:\Development\my-project\node_modules\primeng\package.json.
Update this package.json to use a subpath pattern like "./resources/*".
(Use `node --trace-deprecation ...` to show where the warning was created)
```

As I understand, the `exports` property of `package.json` should use a subpath pattern instead:

```
"exports": {
  "./resources/*": "./resources/*"
},
```

More info: https://nodejs.org/api/deprecations.html#DEP0148

### Environment

This depreciation affects only users using Node 16+.

### Angular version

14.2.x

### PrimeNG version

14.2.x

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.x.x

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
