### ISSUE TITLE
P-Calendar Disabled not working

### ISSUE THREAD

**Issue by vikramt24** [primefaces/primeng#12776]
`    <p-calendar [selectOtherMonths]="selectOtherMonths" [(ngModel)]="dateValue" [disabled]="isDisabled" [formControl]="control" [showIcon]="true" [dateFormat]="dateFormat" [minDate]="minDate" appendTo="body"
        [dataType]="'string'" [maxDate]="maxDate" [showButtonBar]="showButtonBarValue" [showOtherMonths] = "false" [readonlyInput]="true"
        [class]="calendarClass" [ngClass]="calendarStyleClass" (onSelect)="onInput($event)"  (input)="onInput($event)" [attr.data-cy]="uniqueLocator" [required]="required" appendTo="body"></p-calendar>`

This is my Implementation

![image](https://user-images.githubusercontent.com/94819789/226558906-657a2b1d-aac6-448e-96e0-71ee9dc86b92.png)

This is what I am Getting in HTML. disabled property is not adding to button and also to the Input. 

Could you please let me know. What can be the issue?

**Comment by kyjus25** [comment]
Are you able to provide a reproduction of this more fully on something like StackBlitz or CodeSandbox? It seems to be working for me

https://stackblitz.com/edit/angular-ybsuww-licbvh?file=src/app/demo/calendar-icon-demo.html

**Comment by vikramt24** [comment]
I am using  version 15.2.1

**Comment by pafmaf** [comment]
> It seems to be working for me, could you share what version of PrimeNG you're using?
> https://stackblitz.com/edit/angular-ybsuww-tmqqjv?file=src/app/demo/calendar-icon-demo.ts

Try setting `isDisabled = true` at first, and it will start with `disabled = false`.

I'm using 16.0.2 .

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
