### ISSUE TITLE
TabView: ConfirmDialog breaks closable tab

### ISSUE THREAD

**Issue by smartm0use** [primefaces/primeng#12774]
### Describe the bug

If I add a ConfirmDialog to handle the close of a tab of TabView it breaks.

### Environment

Running Angular application with Primeng in Chromium.

### Reproducer

https://stackblitz.com/edit/primeng-tabview-demo-sdjd5f

### Angular version

15.2.1

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.10.0

### Steps to reproduce the behavior

Create the template for a TabView and set `[controlClose]` and `(onClose)` parameters on `p-tabView` element. Then set `[closable]` to any `p-tabPanel` element.

The function called by `(onClose)` will close the tab with `[closable]` attribute, throught `.close()` method on the triggered event.
But if you pass the event to a function, in this case the function of a ConfirmDialog, the close of the tab doesn't happen.
To trigger it and having the tab closed you have to click on any other tab first.

**Comment by smartm0use** [comment]
Adding `event.originalEvent.target.click();` after `event.close()` does the trick.
Anyway it is an issue and it should be fixed.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
