### ISSUE TITLE
MegaMenu: support tooltipOptions

### ISSUE THREAD

**Issue by eXpertise7** [primefaces/primeng#12770]
### Describe the feature you would like to see added

Ability for Developer to add a tooltip to main MegaMenuItem item in that list.

### Is your feature request related to a problem?

Fully at the bottom, comparasion is provided: at the right side in that image, we can see that tooltip is not supported in MegaMenuItem list. It's really important to provide tooltip in the p-megaMenu if we're using it for sidebar, and if a Developer wants to have sidebar items without label (so sidebar takes less screen width) provided, so tooltip would be helpful.

### Describe the solution you'd like

Add tooltipOptions Object at MegaMenuItem interface and support tooltip at p-megaMenu component.

### Additional context

![image](https://user-images.githubusercontent.com/17203747/226304778-261b7c48-f3ca-43bc-8147-da688ff867f0.png)

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
