### ISSUE TITLE
scroll to selection in DataTable, Tree and TreeTable

### ISSUE THREAD

**Issue by jisqaqov** [primefaces/primeng#1278]
Good day. New features to Tree, TreeTable and DataTable.
When selection changed i would like to suggest scroll to selection. It is crucial because records could be many. For example selection can occur at the beginning and at the end.

**Comment by jisqaqov** [comment]
I think this issue is crucial and still waiting for your response...

**Comment by mmlitvin** [comment]
Also really think this feature is a necessity.  Would love to see it being bumped up int he work queue. Thank you !

**Comment by mohan1304** [comment]
Me too looking for this functionality. As mentioned above it will be helpful if this can be prioritized.

Please suggest if there is an alternative way to achieve this funtionality

**Comment by blasetti** [comment]
Any suggestion? Is this crucial functionality planned or is there some workaround to have the autoscroll to an item programmatically selected?

**Comment by johnhamm** [comment]
Here is a way you can do it:

HTML:

`<p-tree #mytreeid id="mytree"></p-tree>`

Angular:

```
@ViewChild("mytree") mytree: Tree;

// selection is the TreeNode you want to scroll into view
scrollToSelectionPrimeNgDataTree(selection, tree, elementIdName) {
      if (tree.value !== null) {
          let index = tree.value.indexOf(selection);
          document.getElementById(elementIdName).querySelectorAll("p-treenode")[index].scrollIntoView();
      }
  }
```

**Comment by cagataycivici** [comment]
Do you need window scroll position to scroll to the selected item? Please provide more details.

**Comment by jisqaqov** [comment]
Nope, not window scroll. Well, Tree and TreeTable itself contains scroll. So this scroll should position on the selected node. It depends if selected node is in the middle of tree, scroll should move down or up to the position of node. So, wherever selected node, scroll should move to it's position.

**Comment by danny-swimmer** [comment]
@johnhamm - Could you please elaborate a bit on your comment from Mar 24? For example, it's not clear to me where the 2nd argument (tree) to scrollToSelectionPrimeNgDataTree() comes from. It would be helpful to provide an example of calling scrollToSelectionPrimeNgDataTree().

**Comment by kc13greiner** [comment]
@cagataycivici - Let me see if I can clarify (I would like this feature too):

When the [(selection)] attribute of a table changes, it would be desirable to have the option to make the table scroll to that selected row.

**Comment by johnhamm** [comment]
Here's how you would call scrollToSelectionPrimeNgDataTree:

HTML:

`<p-tree #mytree id="mytree"></p-tree>`

Angular:

```
@ViewChild("mytree") mytree: Tree;

// selection is the TreeNode you want to scroll into view
scrollToSelectionPrimeNgDataTree(selection, tree, elementIdName) {
      if (tree.value !== null) {
          let index = tree.value.indexOf(selection);
          document.getElementById(elementIdName).querySelectorAll("p-treenode")[index].scrollIntoView();
      }
  }
```

// selectedTreeNode is set to the TreeNode that you want to scroll to
// mytree is set to the mytree property of your component (declared above using ViewChild to select the tree based on the id of the HTML element specified by the hashtag and id attributes)
// "mytree" is the ID attribute of the HTML (tree) element

`scrollToSelectionPrimeNgDataTree(selectedTreeNode, mytree, "mytree")`

**Comment by daleclements** [comment]
This would also be beneficial in ListBox. When something in a list (like a row in a table) is selected programatically it is usually expected that the list will scroll in order to make the newly selected row visible, if it has to.

**Comment by juri33** [comment]
Nice feature to have

**Comment by geisslercom** [comment]
+1

**Comment by OppiXP** [comment]
+1

**Comment by AlfaCoder** [comment]
+1

**Comment by herubber** [comment]
+1

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.

**Comment by sridhark158** [comment]
+1
