### ISSUE TITLE
Deprecate Components

### ISSUE THREAD

**Issue by cetincakiroglu** [primefaces/primeng#12781]
Components below will be deprecated

- Gmap
- Recaptcha

**Comment by cetincakiroglu** [comment]
- https://github.com/primefaces/primeng/commit/b8f6364d5177b37dc0ca81003da7871156529628
- https://github.com/primefaces/primeng/commit/cc035e414efa3091914ffc0adf057ecca8afbfd0

**Comment by maurice85** [comment]
can i still install these as separate dependencies?
