### ISSUE TITLE
Component: Table - CSP violation error is triggered

### ISSUE THREAD

**Issue by lawcha** [primefaces/primeng#12787]
## What happens
I get an CSSP violation error in dev console coming from platform-browser (see below).
![image](https://user-images.githubusercontent.com/71696298/226979478-58f07e8b-f369-445a-8ac9-a4f8642879ea.png)
When looking to the sources tab, the following line makes that error (see below).
![image](https://user-images.githubusercontent.com/71696298/226979769-233857a0-2ef7-406e-956c-87170d358024.png)
## Question
Is there any plan for fixing that handling ?

### Environment

Running the app locally on a Macbook pro M1

### Angular version

13.3.11

### PrimeNG version

13.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.10.0

**Comment by kyjus25** [comment]
@lawcha ah, I see, thank you. I'll see if I can get a testing environment for this

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Comment by lawcha** [comment]
Hi,
Thanks for the update. Are you thinking about https://primeng.org/configuration#csp ? I might check this, if yes.

**Comment by mertsincan** [comment]
Hi @lawcha, Thanks a lot for your update! Yes, could you please check it with the latest PrimeNG 18 or 19.rc-1 version? If the problem persists, please create a new issue. Thanks again!
