### ISSUE TITLE
Component: Docs are not accessible 

### ISSUE THREAD

**Issue by pavankjadda** [primefaces/primeng#12782]
### Describe the bug

When I go to https://primeng.org/ I see HTTP 404 error

### Environment

NA

### Reproducer

https://primeng.org/

### Angular version

15.2.3

### PrimeNG version

15.2.1

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

18.x

### Expected behavior

Docs should load as expected

**Comment by LouLeGrain** [comment]
Found [a workaround](https://web.archive.org/web/20230315084343/https://primeng.org/setup), thanks to the wayback machine, until they fix this up.

**Comment by pavankjadda** [comment]
It seems the issue is resolved
