### ISSUE TITLE
Component: Messages/error - Tailwind theme wrong background color

### ISSUE THREAD

**Issue by JoolianGarcia** [primefaces/primeng#12788]
### Describe the bug

Background color for error message in tailwind theme is wrong, it is the same as "warning" message, this creates conflicting visual communication for users.

Background should be #fef2f2, as per tailwind standard 

Class where the wrong background color
```
.p-message.p-message-error {
    background: #FEF3C7;
    border: none;
    border-width: 0 0 0 6px;
    color: #DC2626;
}
```

### Environment

Angular / yarn

### Angular version

14.2.0

### PrimeNG version

15.0

### Build / Runtime

TypeScript

### Language

ALL

### Node version (for AoT issues node --version)

10.9.1

### Browser(s)

All

### Steps to reproduce the behavior

- Visit https://primeng.org/messages
- Apply Tailwind theme

### Expected behavior

Error message should have light red background in order to clearly communicate severity of issue.

**Comment by cetincakiroglu** [comment]
Hi, 

This issue is related to Theme Designer, so I'm moving it to designer repo https://github.com/primefaces/designer-ng/issues/45

Thanks for reporting!
