### ISSUE TITLE
Docs: File Upload missing HttpClientModule import documentation

### ISSUE THREAD

**Issue by WSevenster** [primefaces/primeng#12795]
### Describe the bug

FileUploadModule requires HttpClientModule to work - this has been left off the documentation. 
Without it you will get a few errors and the FileUploadModule won't load. 
![image](https://user-images.githubusercontent.com/98009867/227063974-42f80ae9-cf12-4cfc-b9c9-f8793dbb93ae.png)

### Environment

Official Site: https://primeng.org/fileupload

### Angular version

15.1.4

### PrimeNG version

15.2.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.16.0

**Comment by kyjus25** [comment]
If fileUpload requires HttpClientModule then it's the one that should be importing it, not the parent app. The docs are right but the ngModule is wrong. I'll check in to this tomorrow, thanks for the report!

**Comment by kyjus25** [comment]
@WSevenster You're right, fileUpload was missing the import!

**Comment by WSevenster** [comment]
Great. Previous documentation just included the import as shown below - took me a while to realise what was going on 😋 thanks!

![image](https://user-images.githubusercontent.com/98009867/227088370-1f2b89c5-f7bf-4dac-9cf9-c1242100024a.png)

**Comment by kyjus25** [comment]
@WSevenster interesting. I wonder if the removal from the docs was intentional or not. Guess we'll see if the PR goes through or not 🤷🏼‍♂️ either way we'll get this fixed 💪

**Comment by kyjus25** [comment]
@Urtgard Thank you for the elaboration, this was my bad for not knowing this, I was under the impression interceptors were persisted. Which version are you seeing this issue?

@cetincakiroglu This seems to already be removed from the codebase, but I'm having some issues tracking down exactly when it was removed; it must have gotten overwritten at some point (which is good, I guess!).

**Comment by cetincakiroglu** [comment]
@kyjus25 Yed it was overwritten. It's fixed now

**Comment by WSevenster** [comment]
Can we update the documentation to suggest importing HttpClientModule? 
Without it the file upload won't work. 

![image](https://user-images.githubusercontent.com/98009867/234402624-b83e9451-1f91-4ea8-bd6e-c0d85a2a22d1.png)
