### ISSUE TITLE
I need a way to overlap my refresh modal on the others modals

### ISSUE THREAD

**Issue by gabrielsolanha** [primefaces/primeng#12793]
I often run into problems with z-index in PrimeNg, where the confirm dialog is always hidden under the dialog in dialog(2 dialog). Manufacturers need to create custom z-index according to the user's preferences instead of automatic as it is now.
when i disable auto z-index the dialog doesn't follow [style] = "{"z-index":"99999"}". So sad

_Originally posted by @PhamVanthinh2801 in https://github.com/primefaces/primeng/issues/1907#issuecomment-1165162364_
            
I having the exact same problem i need to disable the auto z-index cause I have a refresh so I don´t know how do I put my refresh modal on z-index top, does do someone can please help me with this problem?

**Comment by kyjus25** [comment]
@gabrielsolanha What is the issue? It seems to be working for me

https://stackblitz.com/edit/primeng-dialog-demo-ce7afv?file=src/app/app.component.ts

Contrary to https://github.com/primefaces/primeng/issues/1907#issuecomment-1165162364 the confirm dialog is not behind the dialog

**Comment by gabrielsolanha** [comment]
@kyjus25 Sory about the late, I having this problem when I have this maximable button on the modal, in others cases works well. can u please help me with this problem? 
 
![image](https://user-images.githubusercontent.com/63301429/227262472-d9620e6b-49a9-4226-a9ad-0e345934cc0c.png)

when I have this type of modal the z-index options do not work well

**Comment by kyjus25** [comment]
@gabrielsolanha Still working for me, even when the dialog is maximized first
https://stackblitz.com/edit/primeng-dialog-demo-xlnwqx?file=src/app/app.component.ts

**Comment by gabrielsolanha** [comment]
@kyjus25 So I don't know what am I doing wrong 
that is my code of the maximizable modal:

```
<p-dialog
  [(visible)]="isVisible"
  [modal]="true"
  [style]="{width: '900px'}"
  [minY]="70"
  [maximizable]="true"
  [baseZIndex]="10000"
  [focusOnShow]="false"
  (onHide)="closeModal()"
>
```



that is my code of the refresh modal:


```
<p-dialog
  [visible]="display"
  [modal]="true"
  [transitionOptions]="'10ms'"
  class="auto-refresh"
  [closeOnEscape]="false"
  [closable]="false"
  [focusOnShow]="false"
  [autoZIndex]="false"
  [style]='{"z-index":"999999 !important"}'
>
```
