### ISSUE TITLE
<P-TIMELINE> Add tool tip timestamp to the circle icon.

### ISSUE THREAD

**Issue by mcwebdev** [primefaces/primeng#12798]
### Describe the feature you would like to see added

<P-TIMELINE> Add tool tip timestamp to the circle icon.
I would like the ability to hover the circle icon in the timeline component => reveal a tool tip.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
