### ISSUE TITLE
Primeng Docs: Missing searchbox field

### ISSUE THREAD

**Issue by mrfy** [primefaces/primeng#12809]
### Describe the bug

In new docs (v15.2.1) search box has been removed.
 
Below I'm attaching screenshot from prevoious version:
![image](https://user-images.githubusercontent.com/22953614/227463570-d5379e09-c74e-4d17-8b30-14a32cfc4715.png)

### Environment

Chrome v110

### Angular version

15

### PrimeNG version

15.2.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Browser(s)

Chrome 110

### Expected behavior

Please restore searchbox.

**Comment by kyjus25** [comment]
Duplicate of #12800
