### ISSUE TITLE
Component: AutoComplete dropdown is flashing after fast double click on dropdown button

### ISSUE THREAD

**Issue by yurchik-ogurchik** [primefaces/primeng#12806]
### Describe the bug

AutoComplete dropdown is flashing after double click on dropdown button. When we downgraded to 15.2.0 this bug is not reproduced so it was appeared only in 15.2.1 version.
The same behavior is reproduced for Dropdown component. This problem is also reproduced on  https://primeng.org/autocomplete and https://primeng.org/dropdown pages for example.

### Environment

It doesn't matter because it reproduced on your official site too

### Angular version

15.1.3

### PrimeNG version

15.2.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.0

### Browser(s)

Chrome 111

### Steps to reproduce the behavior

1. Open https://primeng.org/autocomplete
2. Go to Dropdown
3. Double-click on dropdown button with moving mouse

Actual behavior:
Component flashes quickly. It will flash until reload the page

### Expected behavior

I expected the dropdown list to open without flashing

**Comment by ashikjs** [comment]
@yurchik-ogurchik I Double-click dropdown icon or input then it close immediate after open and it expected behavior. can you tell me more details of  your issues.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
