### ISSUE TITLE
P-toast issue on mobile

### ISSUE THREAD

**Issue by nikchawla008** [primefaces/primeng#12807]
### Describe the bug

If I trigger toast using messageService.add, then click on the toast, the toast does not obey the life property anymore on mobile. The toast stays on the screen till I click somewhere outside the toast. Scrolling the page does not shift focus off the toast either.

### Environment

Angular 14.2.12
PrimeNG 14.1.1

Env does not matter as this bug is present on official site as well

### Angular version

14.2.12

### PrimeNG version

14.1.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14.2

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Use a mobile for this
2. Create a toast using message service, any severity with any life (say 5000).
3. Click on the toast message
4. The toast will not disappear after 5 seconds (life is 5000).
5. Scroll the page (still toast does not disappear)
6. Click anywhere out side the toast.
7. Toast disappears now

### Expected behavior

Toast should obey the life property and get removed after it. It should not matter if we click inside the toast.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
