### ISSUE TITLE
Please bring back the Search option on your site

### ISSUE THREAD

**Issue by AvshT** [primefaces/primeng#12800]
### Describe the bug

Please bring back the Search option on your site
![image](https://user-images.githubusercontent.com/29532821/227126683-7ad1c64d-c0e5-49e4-bbad-e6c7c84f79c9.png)
(The Vue site has some search)

Another thing:
Every component has some description about its features and properties - I didnt find it also, please check.
![image](https://user-images.githubusercontent.com/29532821/227129550-a5b46ba5-3589-460b-a263-36b1c9a2f10c.png)

### Environment

Win10

### Angular version

latest

### PrimeNG version

latest

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

latest

### Browser(s)

Chrome

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
