### ISSUE TITLE
Dialog closeOnEscape should ignore events that are already handled

### ISSUE THREAD

**Issue by teetotum** [primefaces/primeng#12804]
### Describe the bug

The dialog closes on Esc in situations when it should not: when the Esc key originated in any form control with an open poup, the Esc key event was intended to close said popup, and the event is handled by the form control.

I found one [related issue](https://github.com/primefaces/primeng/issues/11044).

### Environment

Windows 10, Chrome browser v. 111.0.5563.65 (Official Build) (64-Bit)

### Reproducer

https://github-sey9pb.stackblitz.io

### Angular version

15.1.0

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.0

### Steps to reproduce the behavior

  In the StackBlitz example:
  Open the dialog and open the dropdown or the multiSelect, hit Escape, the
  dropdown will handle the event and will close as expected. The dialog should
  stay open in this case, but will also close.

### Expected behavior

I expected the dialog to stay open.

Suggested solution: When an event handler (in this case the dropdown's Esc key handler) handles an event in such a way that it can be considere "dealt with", it should mark the event as "handled" by calling "event.preventDefault()".
Any DOM event handler that is intended to behave in such a way as to distinguish between "unhandled" and "handled" events (in this case the dialog's Esc key handler) should check "event.defaultPrevented" first, and act accordingly.

(I have found this a reasonable approach to handling bubbling DOM events in general, and not only for this specific issue at hand)

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
