### ISSUE TITLE
p-table (Event onEditComplete) does not returns index

### ISSUE THREAD

**Issue by costlydeveloper** [primefaces/primeng#12803]
### Describe the bug

on edit complete event there is no index returned:

<img width="376" alt="image" src="https://user-images.githubusercontent.com/55545296/227172453-2bc5f044-17af-44cb-b195-246c323be344.png">

### Environment

Mac

### Angular version

14.2.12

### PrimeNG version

14.1.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.10.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. edit cell
2. press enter
3. watch an event returned

### Expected behavior

to return the right index

**Comment by cetincakiroglu** [comment]
Hi,

As @volvachev mentioned above, you need to define a rowIndex and pass it through the input pEditableColumnRowIndex  property. Closing the issue since this is not a bug.

**Comment by akbarhafeezbutt** [comment]
Thank @volvachev , Its working.
