### ISSUE TITLE
Calendar: Predefined ranges

### ISSUE THREAD

**Issue by yelhouti** [primefaces/primeng#12815]
### Describe the feature you would like to see added

Have the ability to add predefined ranges

### Is your feature request related to a problem?

It is easier to use for reports (current month, last month, last year...)

### Describe the solution you'd like

http://www.daterangepicker.com/#options

### Describe alternatives you have considered

Using the template header and tweaking the css to show it at the left.

**Comment by slyk** [comment]
similar request https://github.com/primefaces/primeng/issues/13004

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
