### ISSUE TITLE
Update documentation about building from source

### ISSUE THREAD

**Issue by dzhavat** [primefaces/primeng#1281]
I made a fork last night in order to play a bit with the code (and hopefully contribute something :)). When I came to building the project, I faced a problem because I couldn't figure out how to do it correctly. Then I found [Building From Source](https://github.com/primefaces/primeng/wiki/Building-From-Source) page in the Wiki.

While it was very helpful, I think it was a bit confusing as well. It says that I should `remove the peerDependencies section` in `package.json` but that section is no longer there. At the end I figured it out. Just pasted the provided code without deleting anything.

I think it will be a good idea if you update that page so it better reflects the current state of the repository.

**Comment by cagataycivici** [comment]
Thank you, will update.
