### ISSUE TITLE
Weird textbox showing inside p-dropdown

### ISSUE THREAD

**Issue by abishai53** [primefaces/primeng#12818]
My dropdowns were looking weird and I resolved to use a ListBox to get away from the dropdowns. Unfortunately, I needed a table later and it seems to reuse dropdowns. Note that I am not the one implementing these dropdowns but they come with the table. Either way, they are all exhibiting the exact same issue that I had when I was using the dropdown component directly.

I have attached images showing the component. It basically inserts a huge textbox within the dropdown.

<img width="225" alt="image" src="https://user-images.githubusercontent.com/56086645/227749794-2133bf40-0ce5-4006-ac0e-ca75da1771fd.png">

<img width="246" alt="image" src="https://user-images.githubusercontent.com/56086645/227749824-83222fa7-9260-4a1e-9fc3-62ee0493038f.png">

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
