### ISSUE TITLE
Primeng Table re ordering not working in ipad ios devices.

### ISSUE THREAD

**Issue by mponnuchami** [primefaces/primeng#12812]
### Describe the bug

Integrated prime ng table reordering in desktop view. Its working as we expected. But in IOS/ android devices the table reordering not working. The drag and drop also not working. I place primeng direct URL in ipad, but unfortunately it's not working.

### Environment

development and as well in production.

### Angular version

15.2.1

### PrimeNG version

13.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.18.0

### Browser(s)

ipad air safari browsers , Android Tablet

### Steps to reproduce the behavior

1. Open the url in ipad safari browsers.
2. Verify the table reordering.

### Expected behavior

The table reordering should work on ipad and android devices.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Comment by uebelmar** [comment]
@mehmetcetin01140 still not working under v17 and v18. can you reopen the issue or should i create a new one?
