### ISSUE TITLE
p-frozen-column not have border

### ISSUE THREAD

**Issue by nguyenvu1702** [primefaces/primeng#12826]
### Describe the bug

![image](https://user-images.githubusercontent.com/79560062/228126069-59ad864e-85d6-4859-ace9-d6fc02b801a2.png)
I'm using frozenColumn , disable background table and see frozen header path does not have border. So when I scroll table  Borders moving.
![image](https://user-images.githubusercontent.com/79560062/228126529-83e4633c-ab31-4cca-a43c-4344bfb7d636.png)

### Environment

Angular: 12
Primeng: 12.2.3

### Angular version

12.0.5

### PrimeNG version

12.2.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.15.0

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
