### ISSUE TITLE
DyanmicDialog: Missing Link in documentation

### ISSUE THREAD

**Issue by Gurran** [primefaces/primeng#12821]
### Describe the bug

![Screenshot from 2023-03-27 12-38-19](https://user-images.githubusercontent.com/42462633/227930619-9000993a-9707-4e35-a0b4-b7334c172d29.png)
![Screenshot from 2023-03-27 12-39-11](https://user-images.githubusercontent.com/42462633/227930622-c7a5c7f0-0637-4db6-adb1-a982e1ac5409.png)

### Environment

Web

### Angular version

*

### PrimeNG version

*

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

*

**Comment by gucal** [comment]
Thanks for reporting.

**Comment by Gurran** [comment]
@gucal Failing Cypress? 
https://github.com/primefaces/primeng/actions/runs/4532308387/jobs/7983519465
