### ISSUE TITLE
Component: InputNumber overwrites fractional digit instead of adding the new digit and moving the other digits to the right

### ISSUE THREAD

**Issue by Th3D0ct0r** [primefaces/primeng#12829]
### Describe the feature you would like to see added

I have a p-inputnumber but the entry behavior does not serve my needs. Lets say I have "1.001". My cursor is set as follows: 1.|001. When I enter a number (i.e. 3) i expect this result: 1.3|001, instead I get this result: 1.3|01. 

### Is your feature request related to a problem?

The problem comes from the "insert" Method in primeng-inputnumber.mjs:

**Original Code which replaces current number:**

newValueStr = inputValue.slice(0, selectionStart) + text + inputValue.slice(selectionStart + text.length, charIndex) + inputValue.slice(charIndex);

**Needed Code which shifts numbers to right and adds new number:** 

newValueStr = inputValue.slice(0, selectionStart) + text + inputValue.slice(selectionStart, charIndex) + inputValue.slice(charIndex);

### Describe the solution you'd like

Add a property to choose if i want to shift fractional digits to the right instead of overwriting the current cursor digit.

### Additional context

Angular version
14.2.4

PrimeNG version
14.1.2

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
