### ISSUE TITLE
[table]: binding to scrollHeight causes issues with table virtualization

### ISSUE THREAD

**Issue by conner-fallone** [primefaces/primeng#12825]
### Describe the bug

When binding scrollHeight via async pipe, the grid virtualization seems to break after the value changes. When scrolling, you just see a bunch of white space, and then you eventually lose all rows.

https://user-images.githubusercontent.com/5201384/228053188-6ef80a7b-4adc-4f8f-8b90-4cc25355aeac.MP4

### Environment

See stackblitz

### Reproducer

https://stackblitz.com/edit/angular-14-demo-qh8mkn?file=src/app/home/home.component.ts

### Angular version

14

### PrimeNG version

14

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14.0

### Browser(s)

All

### Steps to reproduce the behavior

1. Create a virtualized table with scroll
2. Bind scrollheight to async pipe
3. Change scrollheight value
4. Notice that the virtualization stops behaving as expected

### Expected behavior

Virtualization should support changes to scrollHeight and be reactive to it.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
