### ISSUE TITLE
Component: InputNumber - Control update on blur even when value has not been changed

### ISSUE THREAD

**Issue by MarcinBorowski95** [primefaces/primeng#12832]
### Describe the bug

When using the InputNumber component it updates the control value and state on blur even when no change has been made to the value

### Environment

All environments from dev to prod

### Angular version

15.2.4

### PrimeNG version

15.2.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.1

### Browser(s)

Chrome, Egde

### Steps to reproduce the behavior

1. Create a control with updateOn strategy set to 'blur'
2. Use InputNumber component to show the control
3. Focus on the input
4. Focus out off the input
5. Control value is updated to the same one
6. Control is set to being dirty even when no change has been made to the value

### Expected behavior

On blur when no change is made to the input value the control should not be updated. Control should not be dirty.

**Comment by volvachev** [comment]
I think it's a duplicate [12673](https://github.com/primefaces/primeng/issues/12673)

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
