### ISSUE TITLE
Shift key support for DataTable row selection

### ISSUE THREAD

**Issue by ctrl-brk** [primefaces/primeng#1283]
To select multiple items at once shift-click would be very helpful.

**Comment by mmlitvin** [comment]
I agree.  In order to do any group actions on the large data sets shift support is a must. Thank you !

**Comment by santoshsas** [comment]
@cagataycivici i am using primeNg in our projects, and looking for shift to work on data table for sometime now. This is good to have from UX perspective, as user are use to shift to select multiple lines. It be will great if you can fix this soon, its not major change just need to add(shift key) this line in dataTable.ts

var metaKey = event.metaKey || event.ctrlKey || event.shiftKey;

Will appreciate ur quick action on this.

**Comment by ctrl-brk** [comment]
@santoshsas, shift should select everything from currently selected item to the shift-clicked item. Not just duplicate ctrl-click functionality.

**Comment by santoshsas** [comment]
@ctrl-brk I agree but this needs to be fixed don't see any update by @cagataycivici when since nov on when this will be address.

**Comment by cagataycivici** [comment]
This is on our todo list.

**Comment by Streammz** [comment]
I took a bit of my time to write a helper class that implements this behaviour on an existing datatable, for the people that need this functionality now.

It probably requires some changes to have it work on your project, but for my project it works.

https://pastebin.com/G1DLfrvS

An example to initialise it:

```
import { Component, AfterViewInit, ViewChild } from '@angular/core';
import { DataTable } from 'primeng/components/datatable/datatable';
import { DataTableSelectionHelper } from './datatable.selection-helper';

@Component({
    template: '<p-dataTable #myDataTable ...></p-dataTable>'
})
export class YourComponent implements AfterViewInit {

    @ViewChild('myDataTable') dataTable: DataTable;

    ngAfterViewInit() {
       new DataTableSelectionHelper(this.dataTable);
    }

}
```

**Comment by arjayleviackerman24** [comment]
@Streammz I'm planning to use this helper you've created but when I use it there is a code error. 

`this.table.dataKey`  - dataKey is does not exist on type Datatable.
`this.table._selection `  - _selection does not exist on type Datatable.
 `this.table.selectionKeys`  -selectionKeys does not exist on type Datatable.

I'm in angular 2.3 and using primeng 2.0.2
