### ISSUE TITLE
Component: Galleria scroll thumbnail

### ISSUE THREAD

**Issue by stsness** [primefaces/primeng#12835]
### Describe the feature you would like to see added

Add an horizontal scrollbar in thumbnail section.

### Is your feature request related to a problem?

No

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
