### ISSUE TITLE
Table: Lazy Loading with Virtual Scrolling jumps up and down, sometimes causing infinite loops

### ISSUE THREAD

**Issue by Laurent02** [primefaces/primeng#12830]
### Describe the bug

When having a large dataset and using the Table component with Virtual Scrolling and Lazy Loading combined, the table sometimes "jumps" a bit when a new section of the data is loaded. This behaviour seems to be worse when implemented in a larger application (such as ours) but is reproducable in a simple StackBlitz demo.
Sometimes, the jumping causes an infinite loop because the jump triggers a new lazy load event.

### Environment

We have this issue on PrimeNG 14.2.3 and Angular 14, but it can also be reproduced with PrimeNG 15.2.0 and Angular 15.

### Reproducer

https://stackblitz.com/edit/angular-qnszqr

### Angular version

15.2.1

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14.2

### Steps to reproduce the behavior

Start scrolling in the table.
Especially when scrolling to the end, the behaviour is more clear.

[PrimeNG-TableLazyLoadDemo---StackBlitz.webm](https://user-images.githubusercontent.com/17859632/228161836-0be00d82-3305-4a68-9ca5-5725e452f49f.webm)

### Expected behavior

The scrollbar is steady as a rock, and there is espacially no possibility for an infinite loop because of unneeded LazyLoadEvents.

**Comment by jeffreyansell** [comment]
I am seeing this as well.  It is also happening with dropdowns.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
