### ISSUE TITLE
Component: InputNumber - Control update on strategy is ignored

### ISSUE THREAD

**Issue by MarcinBorowski95** [primefaces/primeng#12831]
### Describe the bug

When using the InputNumber component with angular reactive forms it ignores the updateOn strategy of the form control. This means that the value of the input is always updated on every change event, regardless of whether the updateOn strategy is set to blur or submit. This can cause unwanted side effects, such as triggering validation errors or setting the control state to dirty when unwanted.

### Environment

All environments from dev to prod

### Angular version

15.2.4

### PrimeNG version

15.2.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.1

### Browser(s)

Chrome, Egde

### Steps to reproduce the behavior

1. Create a control with updateOn strategy set to 'blur'
2. Use InputNumber component to show the control 
3. Start inputing a number
4. Each key press causes the control to be updated 

### Expected behavior

Control is updated only on blur

**Comment by volvachev** [comment]
I think it's a duplicate [12673](https://github.com/primefaces/primeng/issues/12673)

**Comment by neergaard79** [comment]
Still an issue in 15.3.0

**Comment by cetincakiroglu** [comment]
Fixed in https://github.com/primefaces/primeng/pull/15948
