### ISSUE TITLE
Component: Tree table with virtual scroll issue

### ISSUE THREAD

**Issue by gcannone** [primefaces/primeng#12844]
### Describe the bug

We encountered a problem using the virtual scroll on treeTable with scrollHeight set in px. When the number of items does not fill the whole page, or there are collapsed nodes, instead of appearing the empty space under the tree-table rows, the tree-table rows increase their height. Is there a way to avoid this row height variability?

### Environment

<html>
<body>

scrollHeight => 400px
virtualScroll => true
virtualScrollItemSize => 40

In my scenario, the tree table has only two rows and the rowHeight is much greater than 40, creating a very unsightly situation graphically.

<br class="Apple-interchange-newline">
</body>
</html>

### Angular version

15.1.5

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.10.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

Create a tree table with the following parameters and only two rows as values:

scrollable => true
scrollHeight => 400px
virtualScroll => true
virtualScrollItemSize => 40

### Expected behavior

I expect that the single row height is always 40px and not variable based on how many rows the tree table has.

**Comment by gcannone** [comment]
Is it possible to get feedback on the problem described?

**Comment by flkeller** [comment]
Still no one at least having a look over it? Issue still persists. Virtual scroll not usable in TreeTable

**Comment by MBJ554** [comment]
No one has found a solution for this yet?

**Comment by MBJ554** [comment]
@gcannone @flkeller If you still need a work around, I have managed to fix it for my end atleast. 
adding a `display: flex;` to the `<tr>` seems to stop it from stretching.

**Comment by hoangphuc2k** [comment]
any update this issue?

**Comment by SultanGabriel** [comment]
any updates? I am having the same issue.

**Comment by hoanganhbong** [comment]
same issue, any solution yet ?

**Comment by Erledus** [comment]
beside maybe the Display Flex solution, for me it worked to set a min-height in tablestyle on the <p-treetable>
[tableStyle]="{ 'min-width': '40rem', 'min-height': '51px' }"

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
