### ISSUE TITLE
Messages not showing custom icon with severity set

### ISSUE THREAD

**Issue by Xriuk** [primefaces/primeng#12849]
### Describe the bug

When specifying both severity and icon the specified icon gets overridden by the default severity icon.
As you can see here they are both set:
https://github.com/primefaces/primeng/blob/e88ba436fb9ec4a5ccd51922f3a035a0217749f7/src/app/components/messages/messages.ts#L16-L19

### Environment

...

### Angular version

All

### PrimeNG version

All

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

...

### Expected behavior

If the icon is set it should override any default icon

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
