### ISSUE TITLE
DataTable - changing data source doesn't clear selected items

### ISSUE THREAD

**Issue by ctrl-brk** [primefaces/primeng#1284]
You have to manually reset [(selection)] when [value] changes.

**Comment by cagataycivici** [comment]
This is expected, one may prefer to keep selections if they exist in new data set as well. So it should better be handled at app side not by datatable. Also we can't really know how the data changes, maybe a certain record is removed or added, if we remove selections in that case that would cause bugs, as on app side you know the type of data change (e.g. new search results or change a record in existing dataset), better you decide how to handle selections.
