### ISSUE TITLE
Component: Selection of the only child row in a tree-table

### ISSUE THREAD

**Issue by gcannone** [primefaces/primeng#12845]
### Describe the bug

In my scenario, I have a tree-table with checkbox row selection. In case a parent row has only one child, I don't have the possibility to select only the child row, but it also automatically selects the parent.

### Environment

![image](https://user-images.githubusercontent.com/44498334/229139673-6dc48703-85c8-47df-88e2-3144b531f663.png)

### Reproducer

https://primeng.org/treetable#checkbox

### Angular version

15.1.5

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.10.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Create a tree-table with selection mode checkbox
2. Populate tree table with values
3. I want to select a certain row, which is the only child of a parent row.
4. The tree-table also automatically selects the parent row for me

### Expected behavior

I expect the tree-table not to automatically select the parent row as well, or at least give me the possibility to configure this behavior.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
