### ISSUE TITLE
Feature Request: are you providing Tooltip support in Primeng Editor toolbar. IF not then any other solution for that?

### ISSUE THREAD

**Issue by AjeetUI** [primefaces/primeng#12841]
### Describe the feature you would like to see added

Tooltip not appears in HTML editor toolbar.
![image](https://user-images.githubusercontent.com/87692474/229097719-d4a0de45-4692-429e-a957-2b55156b72ca.png)

### Is your feature request related to a problem?

Yes

### Describe the solution you'd like

Need tooltip for better User experience.

### Describe alternatives you have considered

Tooltip

### Additional context

N/A

**Comment by AjeetUI** [comment]
Hello, Any update ?

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
