### ISSUE TITLE
PrimeNG Website - Keyboard Copy Command Broken on MacOS

### ISSUE THREAD

**Issue by shawnweeks** [primefaces/primeng#12846]
### Describe the bug

I don't really know how else to describe this but on any of the code blocks on primeng.org like the one at https://primeng.org/installation under Download it is impossible to copy the text using a keyboard on MacOS. As soon as you hit the command key the text is unselected and it's impossible to hit command+c to copy the text. I've verified this on multiple macs. Copy from the code block sections on other prime sites like primevue.org work fine with the keyboard.

### Environment

macOS 13.2.1
Firefox 111.0.1
Chrome 111.0.5563.146
Safari 16.3

### Angular version

N/A

### PrimeNG version

N/A

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

N/A

### Browser(s)

Firefox 111.0.1 or Chrome 111.0.5563.146 or Safari 16.3

### Steps to reproduce the behavior

Goto the Download section of https://primeng.org/installation and try and copy the line `npm install primeng primeicons` using a keyboard on macOS

### Expected behavior

Pressing the command key as a part of the command+c combination should not unselect the text.

**Comment by cetincakiroglu** [comment]
Thanks for reporting

**Comment by kyjus25** [comment]
@gucal PR up. Changing prism to run only on view init instead of every check (like when CMD is pressed) fixed the issue.

**Comment by szymonhel** [comment]
I have the same issue on WIN 11.

**Comment by kyjus25** [comment]
@szymonhel Yes, to clarify, this issue occurs on any OS, not just macOS. 

MacOS just happens to use the Super key more for it's shortcuts.
