### ISSUE TITLE
Slider range handler stuck on maximum

### ISSUE THREAD

**Issue by rolandoldengarm** [primefaces/primeng#1285]
If you slide both sliders to the maximum values, you can't change the value anymore. I guess the right slider is on top in that case.
Can be replicated in the demo: http://www.primefaces.org/primeng/#/slider

Just slide them both to the right, and you're stuck.

I've fixed it for now with a z-index change:
````
.ui-slider span:nth-child(2) {
    z-index:1000 !important; // this is the most left slider
}
````

**Comment by rolandoldengarm** [comment]
Hmm, this is not a proper fix, because when you set both to minimum values, you are then blocked :)

**Comment by aseifert** [comment]
Why was this issue closed? As far as I can tell this bug is still occurring (see the [official showcase page](https://www.primefaces.org/primeng/showcase/#/slider)).
