### ISSUE TITLE
PrimeNG doesn't work with Content-security-Policies that enforce trusted-types

### ISSUE THREAD

**Issue by gerjon-eatch** [primefaces/primeng#12855]
### Describe the feature you would like to see added

PrimeNG has multiple issues that make it incompatible with Content-security-Policies that enforce trusted-types.
Most companies I work for have (for good reason) security policies in place that require a CSP that enforces trusted-types. That means, PrimeNG is not allowed to be used with such companies. 

This has been reported before, see e.g this closed issue: https://github.com/primefaces/primeng/issues/11050

Mostly this is because PrimeNG makes assignments to innerHTML all over the code base. In most cases this could be replaced relatively easily with textContent (if it is just textual content that is assigned, also possyble for style elements).

### Is your feature request related to a problem?

The problem is that PrimeNG is incompatible with a COntent-Security-Policy that enforces trusted-types.

### Describe the solution you'd like

Make PrimeNG compatible witrh stricter security policies

### Describe alternatives you have considered

No alternative

**Comment by rwilliamsBBM** [comment]
I'm using primeng version 14, and I get this issue in Chrome trying to use the pTooltip. Of course updating my current project to the latest version of primeng is part of the scope of my current project and my hope is that the issue will be fixed in the latest version. 
Quickly Perusing the latest source, it looks like it might still have the same 'TrustedHTML' issue if not using a template for the tooltip?
Here's what I found in version 14.
In the tooltip source file on or around line 220:
`updateText() {
        if (this.getOption('escape')) {

            this.tooltipText.innerHTML = '';
            this.tooltipText.appendChild(document.createTextNode(this.getOption('tooltipLabel')));
        }
        else {
            this.tooltipText.innerHTML = this.getOption('tooltipLabel');
        }` 

I updated this to:
`updateText() {
        if (this.getOption('escape')) {
            const escapeHTMLPolicy = trustedTypes.createPolicy("myEscapePolicy", {
                createHTML: (string) => string.replace(/>/g, "<"),
              });

            this.tooltipText.innerHTML = escapeHTMLPolicy.createHTML('');
            this.tooltipText.appendChild(document.createTextNode(escapeHTMLPolicy.createHTML(this.getOption('tooltipLabel'))));
        }
        else {
            this.tooltipText.innerHTML = this.getOption('tooltipLabel');
        }`
And it now works in Chrome. But in the latest source I see (starting around line 386 of primeng/fesm2022/prime-tooltip.msj):
`updateText() {
        const content = this.getOption('tooltipLabel');
        if (content instanceof TemplateRef) {
            const embeddedViewRef = this.viewContainer.createEmbeddedView(content);
            embeddedViewRef.detectChanges();
            embeddedViewRef.rootNodes.forEach((node) => this.tooltipText.appendChild(node));
        }
        else if (this.getOption('escape')) {
            this.tooltipText.innerHTML = '';
            this.tooltipText.appendChild(document.createTextNode(content));
        }
        else {
            this.tooltipText.innerHTML = content;
        }
    }`
** this.tooltipText.innerHTML = '';** is the problem in Version 14 and I appears to still currently be there in Beta?
Am I reading this all correct?

**Comment by rwilliamsBBM** [comment]
Update.
Project upgraded to latest versions of Angular 16.xx and Prime NG 16.xx .

Running in local, simple text tooltips still throw the TrustedHTML error.  Tooltips using templates work fine.

**Comment by jfbarahonag** [comment]
Hi everybody.

I'm working with Angular V16 and OWASP ZAP scanner is reporting  
![image](https://github.com/primefaces/primeng/assets/28329247/e7a7da3b-bb6a-4858-9dd2-04e61cf90fd6)

Is the usage of PrimeNG the root of this alert?

**Comment by d-eder** [comment]
It seems that this is still not fixed with the current latest prime ng release (19.0.10).

I'm getting this error:
```
polyfills-FFHMD2TL.js:1 
        
        Uncaught TypeError: Failed to set the 'innerHTML' property on 'Element': This document requires 'TrustedHTML' assignment.
    at e.updateText (chunk-3JXWUU6K.js:70:7255)
    at e.create (chunk-3JXWUU6K.js:70:5412)
    at e.show (chunk-3JXWUU6K.js:70:6456)
    at e.activate (chunk-3JXWUU6K.js:70:4342)
    at e.onMouseEnter (chunk-3JXWUU6K.js:70:3869)
    at f.invokeTask (polyfills-FFHMD2TL.js:1:7068)
    at t.runTask (polyfills-FFHMD2TL.js:1:2375)
    at E.invokeTask [as invoke] (polyfills-FFHMD2TL.js:1:8144)
    at I (polyfills-FFHMD2TL.js:1:15196)
    at H (polyfills-FFHMD2TL.js:1:15492)
```


```
        updateText() {
            let t = this.getOption("tooltipLabel");
            if (t instanceof E) {
                let i = this.viewContainer.createEmbeddedView(t);
                i.detectChanges(),
                i.rootNodes.forEach(o => this.tooltipText.appendChild(o))
            } else
                this.getOption("escape") ? (this.tooltipText.innerHTML = "", // <- ther error happens here
                this.tooltipText.appendChild(document.createTextNode(t))) : this.tooltipText.innerHTML = t
        }
```
