### ISSUE TITLE
Menu Item Readonly

### ISSUE THREAD

**Issue by Kunepro** [primefaces/primeng#12858]
### Describe the feature you would like to see added

I would like an option to make some rows of the menu readonly.

### Is your feature request related to a problem?

Using the menu, all the menu items are clickable.
I want to use the dropdown menu with some lines being readonly state for contextual information.
For example I have a menu that is clicked on the "user" icon, when opened one line is the user's username, the line below is the log out button.
Username shouldn't be clickable, just readable.

### Describe the solution you'd like

Add a flag "readonly" to the menu item APIs, if true the element is just a div and not an a or a button.
It is not clickable, but it is selectable as text.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
