### ISSUE TITLE
all: Add zone.js 0.13.0 support

### ISSUE THREAD

**Issue by jase88** [primefaces/primeng#12851]
### Describe the feature you would like to see added

Use primeng with newer Angular versions with zonejs 0.13.0

### Is your feature request related to a problem?

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: primeng@15.3.0
npm ERR! Found: zone.js@0.13.0
npm ERR! node_modules/zone.js
```

### Describe the solution you'd like

primeng should support the newest zonejs version

**Comment by tambor81** [comment]
any progress on this one?
