### ISSUE TITLE
MessageService

### ISSUE THREAD

**Issue by vitosalvia** [primefaces/primeng#12857]
### Describe the bug

If setting key for message interface, message service does not working.

this.messageService.add({
      key:${utenza.uUID}
      severity: 'success',
      summary: 'Service',
      detail: `UUID: ${utenza.uUID} - STATUS: ${utenza.status}`,
      sticky: true,
    });

### Environment

webstorm

### Angular version

15.2.2

### PrimeNG version

15.3.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.1

**Comment by gucal** [comment]
Hi,

If there is a key, the <p-messages</p-messages> component you put in the template must also contain the key.

`<p-messages key="example"></p-messages>`

`{ severity: 'success', summary: 'Service Message', detail: 'Via MessageService', key:'example' },`
