### ISSUE TITLE
p-accordion

### ISSUE THREAD

**Issue by Kudeshpande** [primefaces/primeng#12863]
### Describe the bug

Unable to select de-select checkbox with spacebar if it is inside an accordion. 

https://stackblitz.com/edit/github-ran6kl-8kj1fi?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.css

### Environment

Development

### Angular version

13.3.8

### PrimeNG version

13.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.1

### Steps to reproduce the behavior

- Create an accordion with a checkbox inside accordion header
- now navigate to the checkbox using keyboard 
- press spacebar

### Expected behavior

- Expected: Checkbox should be checked/unchecked 
- Actual: Accordion is expanded/collapsed

**Comment by mehmetcetin01140** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.
