### ISSUE TITLE
Ctrl + C copying code examples on primeng.org is broken

### ISSUE THREAD

**Issue by teetotum** [primefaces/primeng#12860]
### Describe the bug

I used to copy snippets from code examples on primeng.org with Crtl + C.

When I try this now the text selection in the code section is cleared as soon as my finger hits the Ctrl key.

### Environment

Chrome Browser, Windows 10

### Reproducer

https://primeng.org/installation#download

### Angular version

15

### PrimeNG version

15

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.0

### Steps to reproduce the behavior

1. go to https://primeng.org/installation#download
2. select `npm install primeng primeicons` in the code snippet box
3. hit Ctrl key
4. text selection is lost

### Expected behavior

I expect the text selection to not be cleared when hitting Ctrl key or any other modifier key

**Comment by vokic** [comment]
I just opened the same issue without realizing there is one. Please look into this 😺

**Comment by gucal** [comment]
Hi,

Duplicate issue #12846. 

Thanks for reporting.
