### ISSUE TITLE
Tree: Expand with virtualscroll results in expanded node outside the window

### ISSUE THREAD

**Issue by mconner** [primefaces/primeng#12869]
### Describe the bug

When you expand a node with virtual scrolling enabled, the window displays a seemingly random location in the tree, where the expanded node often isn't even visible. This is exceedingly inconvenient when you have large numbers of items (e.g. 1000s in the example) in the tree, and you keep losing your position every time you expand a node.  

I'm currently using primeng 13.3.2, but I see the exact same behavior in the 14.0.2 documentation example, which I've used as the Reproducer.  _(The 15.x documentation doesn't include a virtual scroll example, and I can't even start any of the 15.x examples in stackblitz, as I get errors starting, beginning with: ./src/app/app.module.ts:29:0-64 - Error: Module not found: Error: Package path ./codehighlighter is not exported from package )._

I was hoping to mitigate this by forcing the window to scroll to the node, but the expand event contains only the TreeNode and the originalEvent (a PointerEvent).  The targetElement on the PointerEvent presumably won't work, since the virtualscrolling is going to rewrite a bunch of stuff, and that element may be removed or represent a different TreeNode.  I was thinking of using the virtualScrollBody (for 13.3.2, I know it has changed for 14.x) on the Tree to scrollToIndex, but I don't see how to get the index from the TreeNode. (I'm not even sure what the index represents, as it isn't documented.)

### Environment

Windows 10

### Reproducer

https://stackblitz.com/edit/primeng-treescroll-demo?file=README.md

### Angular version

 13.2.5

### PrimeNG version

13.3.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v16.14.0

### Browser(s)

Edge 111.0.1661.62 , Chrome 111.0.5563.147

### Steps to reproduce the behavior

For a tree with virtualScroll enabled:

1. Click on the first node with lots of child nodes (Node 0 in example).
2. Scroll down to Node 1 (or any of the top-level nodes) and expand it.
3. The window jumps to a seemingly random place within the tree.  

### Expected behavior

I would expect Node 1 to remain visible at its current location, or at least in visible within the scroll window, and its child elements to appear below it, pushing down any sibling nodes out of view.

**Comment by mehmetcetin01140** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.

**Comment by sthompson-celerity** [comment]
anyone who gets here from google here is a workaround:
```
// Expand the node programmatically
node.expanded = true;
// Force a re-render by creating a new reference to the nodes array.
this.nodes = [...this.nodes];
```
