### ISSUE TITLE
p-password - add autocomplete directive / input 

### ISSUE THREAD

**Issue by patricoos** [primefaces/primeng#12867]
### Describe the feature you would like to see added

Chrome browser automatically completes the password in p-password, there is no parameter to disable it. I created my own directive for this, but I think it can be added to the component implementation

autocomplete
autocomplete="off"
autocomplete="new-password'"

### Describe the solution you'd like

```
import {  AfterViewInit, Directive, Input } from '@angular/core';
import { Password } from 'primeng/password';

@Directive({
    selector: 'p-password[autocomplete]'
})
export class PasswordAutocompleteDirective implements AfterViewInit {
    
    @Input() autocomplete: string = '';

    constructor(private _el: Password) { }

    ngAfterViewInit(): void {
        this._el.input.nativeElement.autocomplete = this.autocomplete&& this.autocomplete.length !== 0 ? this.autocomplete: 'new-password'; 
    }
}
```

**Comment by Stankman** [comment]
This would be actually cool, when I use p-password I always get the following warning:

![image](https://github.com/primefaces/primeng/assets/14809454/02deecda-b3b4-499c-89b8-359c09de8d6a)

Please add this option

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
