### ISSUE TITLE
p-multiSelect: The `maxSelectedLabels` is not working with chips

### ISSUE THREAD

**Issue by rrchai** [primefaces/primeng#12861]
### Describe the bug

When the `display="chip"` is used, the `maxSelectedLabels`/`selectedItemsLabel` seems not to be used anymore. 

```html
<p-multiSelect
  [options]="['option1', 'option2', 'option3']"
  [(ngModel)]="selected"
  [maxSelectedLabels]="2"
  selectedItemsLabel="{0} items selected"
  display="chip"
>
</p-multiSelect>
```

```ts
// ...
selected!: string;
// ...
```
### Environment

N/A

### Angular version

15.0.1

### PrimeNG version

15.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.14.0

### Browser(s)

Chrome

### Expected behavior

I expect it will show `selectedItemsLabel` when the `maxSelectedLabels` is reached (even if it's the chip-display)

**Comment by MarianneAK** [comment]
I also have this issue

**Comment by amrud** [comment]
having this issue with v16.2.0, even the showcased stackblitz not working

**Comment by Ampixel** [comment]
I also have this problem. The chips overflow and enlarge the field. But without chips it works.

![image](https://github.com/primefaces/primeng/assets/47177594/b6e25802-b104-4700-8c31-5f7a72816111)

without display="chip"

![image](https://github.com/primefaces/primeng/assets/47177594/ae8ad5bf-a332-437b-bc57-d88ddfd5a1bb)

My version 15.3.0

**Comment by tclark333** [comment]
I was able to find a workaround for this. Set the display type to change to 'comma' when the max label count is exceeded.

Add a property to define your max selected label count.
`maxSelectedLabels: number = 2;`

Create a function to return the display type.
```  
get multiSelectDisplay() {
    return this.selected?.length > this.maxSelectedLabels ? 'comma' : 'chip';
  }
  ```


Set the display type using the function so it will switch to 'comma' when needed, making the maxSelectedLabels property work.
```
<p-multiSelect 
  [options]="['option1', 'option2', 'option3']"
  [(ngModel)]="selected"
  [maxSelectedLabels]="maxSelectedLabels"
  selectedItemsLabel="{0} items selected"
  [display]="multiSelectDisplay">
</p-multiSelect>
  ```

**Comment by Ampixel** [comment]
THANKS @tclark333  ! it works thanks to your solution

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
