### ISSUE TITLE
p-slider: when [range]='true', slider does not update when model changes

### ISSUE THREAD

**Issue by koesper** [primefaces/primeng#12868]
### Describe the bug

I've got a slider in range mode, so that outputs two values (`slider=[0,150]`).
but if you update that model, the slider does not change.

See the stackblitz for a working example, where you can change the model with a simple textbox.

FYI, when in regular mode, it works, so it appears to be something specific for '[range]=true'

### Environment

stackblitz, tried on mac chrome 111 & 113, safari and firefox.

### Reproducer

https://stackblitz.com/edit/github-cnvmir?file=src/app/app.component.html

### Angular version

14.0.7

### PrimeNG version

14.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.15.0

**Comment by adri95cadiz** [comment]
Same happens for me and i'm updating the value just like you say @Phil-DS, i'm trying to find a workaround will update.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
