### ISSUE TITLE
Dialog  Component : maximize and restore not working properly with window resize

### ISSUE THREAD

**Issue by Abdulali97** [primefaces/primeng#12862]
I am using the PrimeNG Dialog component and I have got an issue when trying to automatically maximize and restore the dialog based on the window size. like  I want the dialog to maximize when the window width is less than or equal to 660px and restore to its original size when it is greater than 660px.

The issue I'm facing is that the dialog does not maximize/restore automatically when resizing the browser window. It only changes the size after clicking inside the dialog, which is not the desired behavior.

Here's the code snippet I have tried:

```typescript

 @ViewChild(Dialog) dialog!: Dialog;

  @HostListener('window:resize', ['$event'])
  onResize(event: any) {
    this.updateDialogSize();
  }

  ngOnInit() {}

  ngAfterViewInit() {
    this.updateDialogSize();
  }

  updateDialogSize() {
    if (window.innerWidth <= 660) {
      this.dialog.maximize();
    } else {
      this.dialog.maximize(); // This should restore the dialog, but it doesn't work as expected.
      this.changeDetectorRef.detectChanges();
    }
  }
```

I have tried several different approaches but none of them have resolved the issue. 

Any assistance would be greatly appreciated. 
Thank you!

**Comment by Abdulali97** [comment]
> This works. Some kind of magic happens with initDrag to resize the window, even when draggable is false. Very strange.
> 
> https://stackblitz.com/edit/angular-rcca6c-ejnggy?file=src/app/demo/dialog-maximizable-demo.htm

**Comment by Abdulali97** [comment]
@kyjus25  Thank you for the suggestion,   but after resizing the window size  the dialog will move when I move the mouse : )

**Comment by kyjus25** [comment]
@Abdulali97 Ah dang it, I thought I'd fixed that. If you set [draggable] to false the issue should go away, but that may be a deal breaker depending on your use case. It is probably a change detection problem like your original code snippet, this was just the only way I could get it to trigger

**Comment by Abdulali97** [comment]
@kyjus25  Thank you, that solves it :) 
I think the auto-maximize feat in the dialog will be a great option  It would enhance the user experience on smaller screens and make it easier for developers to create responsive applications for various devices.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
