### ISSUE TITLE
p-table - Keyboard accessibility, column resizing capability through keyboard

### ISSUE THREAD

**Issue by sandipchitale** [primefaces/primeng#12866]
### Describe the feature you would like to see added

For Keyboard accessibility accessibility implement column resizing capability through keyboard.

### Is your feature request related to a problem?

It is not possible to resize p-table columns using keyboard.

### Describe the solution you'd like

Implement column resizing capability through keyboard.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
