### ISSUE TITLE
Tooltip: Global configuration object

### ISSUE THREAD

**Issue by konuch** [primefaces/primeng#12875]
### Describe the feature you would like to see added

I think it would be useful to have global configuration object for `tooltip` directive similar to global config for `overlay`.

### Is your feature request related to a problem?
We are currently working hard to align our application with WCAG. We use primeng v15.3 and we would like to globally set tooltip behavior, eg. `autoHide: false`. This setting is necessary to comply with https://www.w3.org/TR/WCAG21/#content-on-hover-or-focus This is not possible at the moment and we need to edit a lot of code to align all tooltips through-out our application. Having a global configuration object would help out meeting this requirement. 

### Describe the solution you'd like

Add `tooltipOptions` property to `PrimeNgConfig` class which can be injected to root component and modify tooltip behavior globally.

**Comment by SoyDiego** [comment]
It's a nice idea.

**Comment by Adrii77** [comment]
Any news about this ? this would be so useful and remove many boilerplate code !

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
