### ISSUE TITLE
Dynamic Dialog, p-dropdown, p-overlayPanel: Dropdown content, overlay content is hidden when I scrolling page in Dynamic Dialog

### ISSUE THREAD

**Issue by Chienpv00** [primefaces/primeng#12874]
### Describe the bug

I use Dynamic Dialog and open myComponent, In my myComponent, i use some p-dropdown, p-overlayPanel. But when I open dropdown or overlay panel, it close when i scrolling in Dialog content. Can some one help me update it.

### Environment

Angular 15.1.0
primeng: 15.2.1
rxjs: 7.5.0
zone: 0.11.4

### Reproducer

https://stackblitz.com/edit/angular-7tjqb9?file=src/app/app.module.ts

### Angular version

15.1.0

### PrimeNG version

15.2.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v16.19.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. open dialog (use Dynamic dialog)
2. open dropdown
3. scroll content

### Expected behavior

Overlay panel or dropdown content don't hide when I scroll content in dialog

**Comment by syam38** [comment]
@Chienpv00  I am also looking for a solution, were you able to fix it?

**Comment by Chienpv00** [comment]
I still can't fix it, could you help me. thanks

**Comment by syam38** [comment]
@Chienpv00   This can be solved by passing [overlayOptions] input to the p-dropdown component of primeng 15.

We can send the below options to the component and it worked for me.
I found this by digging deeper into dropdown.ts and overlay.ts files of primg ng.

```
getOverlayOptions(): OverlayOptions {
    return {
      listener: (event: Event, options?: OverlayListenerOptions) => {
     if (options.type === 'scroll') {
        return false;
      }
      return options.valid;
      }
    };
}
```

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
