### ISSUE TITLE
p-timeline: broken styling when alignment is set to "alternate"

### ISSUE THREAD

**Issue by Yurcek** [primefaces/primeng#12873]
### Describe the bug

Events on timeline are not displayed correctly. 
![image](https://user-images.githubusercontent.com/39995663/231111660-c1dde920-aa13-4972-8f5f-3582e33b3f98.png)

Last item of the timeline is stretched because it has not space enough.

### Environment

Win11, WebStorm 2022.3.2

### Angular version

15.2.4

### PrimeNG version

15.2.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.19.1

### Browser(s)

Chrome 111.0.5563.147

### Steps to reproduce the behavior

add templated elements with at least 20 characters of text.
Sample of element:
```
 <ng-template pTemplate="content" let-event>
                <div class="flex flex-column gap-3">
                <span class="text-2xl font-semibold">
                  10 April 2023
                </span>
                  <span class="text-white">
                  Closing votes
                </span>
                </div>
              </ng-template>
```

### Expected behavior

Events on the timeline have to be on the same height and have equal width.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
