### ISSUE TITLE
p-table: onEditComplete emits wrong data

### ISSUE THREAD

**Issue by dserve** [primefaces/primeng#12871]
### Describe the bug

I've upgraded Angular and Primeng to version 15. Now, `onEditComplete` behaves differently: If I'm editing a cell within a `pEditableColumn` of a `p-table` and press 'Enter', the correct data is emitted by `onEditComplete`. But if I jump to another row, `onEditComplete` does not emit the data of the previously edited row but rather the data of the next row. So, in this case `onEditComplete` emits the same data as the following `onEditInit`.

### Environment

No specific requirements. See reproducer on stackblitz.

### Reproducer

https://stackblitz.com/edit/github-1gdamy?file=src/app/components/table/table.component.ts

### Angular version

15.2.5

### PrimeNG version

15.3.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14.2

### Browser(s)

Chrome, Firefox

### Steps to reproduce the behavior

1. Click on any cell in the first row of the table. Edit its value.
2. Click on any cell in another row to edit its value.
3. `onEditComplete` emits the data of the second row and not the first row.

### Expected behavior

`onEditComplete` should emit the data of the previously edited row.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
