### ISSUE TITLE
list box does not work with angular reactive forms

### ISSUE THREAD

**Issue by mveer-jaipur** [primefaces/primeng#12878]
### Describe the bug

I am trying to use listbox for angular forms and formControlName does not work inside it,

https://stackblitz.com/edit/primeng-listbox-demo-byc3p6

### Environment

https://stackblitz.com/edit/primeng-listbox-demo-byc3p6

### Angular version

13

### PrimeNG version

13

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

**Comment by mehmetcetin01140** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.
