### ISSUE TITLE
SlideMenu: Popup in toolbar scrolling issues (Angular 15, Stackblitz)

### ISSUE THREAD

**Issue by mcalihe** [primefaces/primeng#12879]
### SlideMenu: Popup in toolbar scrolling issues (Angular 15, Stackblitz) 

Dear PrimeNg Team,

i have the following issue with the SlideMenu inside a Toolbar:

The toolbar is fixed on top with "position: absolute;top:0;left:0;width:100%;". The slidemenu (popup: true) is located inside the p-toolbar.

If it is attached to body, it will move on scroll.
If it is not attached to the body (default), it will be placed wront if scrolled before opening the slidemenu.

So i would need a solution for this slidemenu popup to work inside a toolbar.

Here is a Stackblitz which showcases my issue:
[Stackblitz Env for repro](https://stackblitz.com/edit/primeng-slidemenu-demo-5hfpiy?file=src/app/app.component.ts)
https://stackblitz.com/edit/primeng-slidemenu-demo-5hfpiy?file=src/app/app.component.ts

### Environment

[Stackblitz Env for repro](https://stackblitz.com/edit/primeng-slidemenu-demo-5hfpiy?file=src/app/app.component.ts)

### Reproducer

https://stackblitz.com/edit/primeng-slidemenu-demo-5hfpiy?file=src/app/app.component.ts

### Angular version

15.2.4

### PrimeNG version

15.3.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.15.1

### Steps to reproduce the behavior

The toolbar is fixed on top with "position: absolute;top:0;left:0;width:100%;". The slidemenu (popup: true) is located inside the p-toolbar.

If it is attached to body, it will move on scroll.
If it is not attached to the body (default), it will be placed wront if scrolled before opening the slidemenu.

### Expected behavior

No matter if i scroll first or after opening the menu, i want the option to have a slidemenu that works coorectly (layout) inside a fixed toolbar. It should always be placed correctly at the target and not move on scroll

**Comment by puschie286** [comment]
Same for the OverlayPanel

**Comment by SeanHaleAtPI** [comment]
I am experiencing this issue as well

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
