### ISSUE TITLE
AutoComplete component is not scrolling on arrow down

### ISSUE THREAD

**Issue by Marcio-H** [primefaces/primeng#12883]
### Describe the bug

The items suggested in the overlay is not scrolling down when pressing arrow down

### Environment

Tested in the primeng website

### Angular version

15.2.4

### PrimeNG version

15.3.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.15.0

### Steps to reproduce the behavior

1. Go autoComplete input
2. Type something
3. Press arrow down until pass the last item

**Comment by cetincakiroglu** [comment]
Fixed in https://github.com/primefaces/primeng/pull/12885
