### ISSUE TITLE
Prime ng Table: Table footer not  stick at the end of the page, stick where the content end

### ISSUE THREAD

**Issue by aj-hops** [primefaces/primeng#12882]
### Describe the bug

In my prime-ng table, my <ng-template pTemplate="footer"> put some value inside the pfooter.
I want to show the total calculation column-wise at the end of the table, but the footer sticks to the content not stick at the end of the page.

To give more detail about the problem I attached the Stackblizz Demo here :
https://stackblitz.com/edit/primeng-tablefilter-demo-nqvsnr?file=src%2Fapp%2Fapp.component.html,src%2Fassets%2Fcustomers-large.json

please look at the demo there is a given table size but footer not work as expected

### Environment

Prime ng and Angular

### Angular version

15.0.3

### PrimeNG version

14.2.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.40.0

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
