### ISSUE TITLE
Component: Title

### ISSUE THREAD

**Issue by vitosalvia** [primefaces/primeng#12886]
### Describe the bug

I've noticed that in in p-table with lazy scroll, the method (onLazyLoad)="loadCarsLazy($event)" is called twice at the initialization of the component.

### Environment

Tested in the primeng website on stackblitz

### Angular version

15.2.2

### PrimeNG version

15.3.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.1

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
