### ISSUE TITLE
Table: Weird behavior when clear selection programmatic in multiple mode

### ISSUE THREAD

**Issue by thang1160** [primefaces/primeng#12881]
### Describe the bug

Whenever I clear `[(selection)]` in the multiple mode, it unchecks visually but not the data key of the `p-table`. This means checkboxes' states are still preserved, rechecking any row will make rows from the last `[(selection)]` automatically checked again.

### Environment

Stackblitz and Ubuntu 22.10

### Reproducer

https://stackblitz.com/edit/angular-zrrzlh

### Angular version

15.2.1

### PrimeNG version

15.3.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14.2

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Check more than 1 row
2. Set two-way binding `[(selection)]` variable to `undefined`
3. Recheck any row

### Expected behavior

The rechecked row must be checked and the remaining will be unchecked

**Comment by Kisters-BS** [comment]
Your selectedProducts is an array of Product, so change your declaration to:
selectedProducts: Product[];

In your clearSelectedProducts function you can clear the selection by assigning a new array:
this.selectedProducts = [];

My guess why undefined does not work is that in the onChanges function of the table it checks if selection is assigned which returns false for undefined:
if (simpleChange.selection) {
https://github.com/primefaces/primeng/blob/master/src/app/components/table/table.ts#L822
