### ISSUE TITLE
Component: Dialog

### ISSUE THREAD

**Issue by NrujalSharma** [primefaces/primeng#12892]
### Describe the feature you would like to see added

The maximizable dialog should be able to open in maximized manner by default

### Is your feature request related to a problem?

Right now there is no way to open a dialog in maximized view by default. It always opens in the default size.

### Describe the solution you'd like

The `maximized` variable should be an input so that we can have the dialog open in maximized mode by default

### Describe alternatives you have considered

I tried setting the width and height styles to 100% but to no avail

**Comment by Stankman** [comment]
Adding to this feature, a minimum screen size also would be cool to trigger this feature:

Let's say if Prime detects Screen to be 'sm', 'md', 'lg' maximize automatically.

**Comment by ZeroSkill830** [comment]
agree with the others. By default, maximizeable prop does not open the modal window in full-screen mode. I would add another prop that handles the default state.
