### ISSUE TITLE
Primeng dropdown/multiselect filter not working on Ionic modals when using appendTo="body"

### ISSUE THREAD

**Issue by mcrtricolor** [primefaces/primeng#12891]
### Describe the bug

When using a Primeng dropdown or multiselect on a ion-modal of Ionic and setting the appendTo property to 'body', the filter input appears to be on read-only mode. Cannot put focus on it, thus impossible to work with it. If I remove the appendTo property it works fine but it overflows my modal.

I tried it within a primeng dialog and there it works as expected.

For more information, i inject an ionic page (with ion-content) to the ion-modal.

### Environment

Angular: 15.2.6
Primeng: 15.3.0
Ionic: 7.0.2

Working on Windows 10 and Webstorm.

### Reproducer

[Example at Stackblitz](https://stackblitz.com/~/github.com/Montsemontero/bugCombos)

### Angular version

15.2.6

### PrimeNG version

15.3.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.15.11

### Browser(s)

Chrome 111

### Steps to reproduce the behavior

Just open the modal, open de dropdown or multiselect and try to set focus or write on the input, it doesn't do anything.
I tried to change css properties but with no success.

### Expected behavior

You should open the modal, then the dropdown or multiselect, set focus on filter input and write your filter.

**Comment by mcrtricolor** [comment]
Hi, I just added a reproduction of the error on stackblitsz. This is still an issue with angular 17 and primeng 16.

I need help with it, thanks.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Comment by mcrtricolor** [comment]
Hi, this is still an issue, and it's a big problema for us. We have a lot of functionalities in modals or popover, so not having a functional filter on dropdowns kills us.

Thanks in advance.

**Comment by mcrtricolor** [comment]
Hi, I'm still having this issue in angular 18, filter of dropdown/multiselect with appendTo=body isn't working on ionic modals.

Can someone help me? If not a fix maybe a workaround?

Thanks again!
