### ISSUE TITLE
Angular 11 LTS bug in AutoComplete in mobile phones

### ISSUE THREAD

**Issue by vadimt2** [primefaces/primeng#12902]
### Describe the bug

https://www.primefaces.org/primeng-v11-lts/#/autocomplete
Go here from mobile chrome app.
Click toggle open auto complete and you will see the bug.

It does working from the desktop, mobile development mode.

So please check it only from your phone.

### Environment

Any android phone.

### Angular version

11

### PrimeNG version

11

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

12

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Take your phone.
2. Open Chrome
3. Open this url https://www.primefaces.org/primeng-v11-lts/#/autocomplete
4. Click on toggle any auto complete

### Expected behavior

Will open the auto complete and you will see the list of items.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
