### ISSUE TITLE
 Ensures elements with an ARIA role that require parent roles are contained by them (.p-treenode-content[aria-posinset="1"][aria-label="Documents"]).

### ISSUE THREAD

**Issue by msftedad** [primefaces/primeng#12907]
### Describe the bug

Required ARIA parents role not present for “Documents” treeitem.

### Environment

Chrome: Version 112.0.5615.121 (Official Build) (64-bit)
PrimeNG: Version v15.0.0-rc.1

### Reproducer

http://primefaces.org/primeng/tree

### Angular version

13.3.1

### PrimeNG version

13.3.0

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

13.3.0

### Browser(s)

Chrome: Version 112.0.5615.121 (Official Build) (64-bit)

### Steps to reproduce the behavior

1.Launch the application using URL  http://primefaces.org/primeng/tree
2."Tree" screen should open.
3.TAB to "Documents" control.
4.Open Accessibility insights for web and run 'fast pass'.
5.Check the issue captured by AI4W for the "Documents" control(treeitem).

Snippet: <div role="treeitem" class="p-treenode-content" draggable="false" tabindex="0" aria-posinset="1"
aria-selected="false" aria-label="Documents">

How to fix:
Fix any of the following:
Required ARIA parents role not present: group, tree

### Expected behavior

Required ARIA parents role should be present for “Documents” treeitem.
![908193_Issue](https://user-images.githubusercontent.com/93735775/232985608-613e0b10-0368-4f2c-8c6a-b854cd2fad9d.png)

**Comment by msftedad** [comment]
Hi team, Any update on this issue?

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
