### ISSUE TITLE
p-autoComplete: Clear button appears on wrong side and is misaligned

### ISSUE THREAD

**Issue by psarno** [primefaces/primeng#12905]
### Describe the bug

We have a p-autoComplete component that is defined as:

```
<div class="p-field p-grid">
<div class="p-col">
<span class="p-float-label">
<p-autoComplete
  [(ngModel)]="newPointerTarget"
  [showEmptyMessage]="true"
  [suggestions]="suggestions"
  (completeMethod)="filterExtensions($event)"
  field="field"
  [minLength]="1"
  [showClear]="true"
  [multiple]="false"
  name="extensions"
  appendTo="body"
  placeholder="Select target extension"
>
</p-autoComplete>
<label>
  Pointer Target
</label>
</span>
</div>
</div>
```
When the user types anything in, the clear icon is shown on the left instead of the right, and does not animate:

![image](https://user-images.githubusercontent.com/18640860/232563375-66fb15ed-f29f-4573-83f4-0d4ac658b701.png)

I attempted an exact repro in StackBlitz and it is not showing this behavior.  I am not sure why.

### Environment

Angular 15.2.5.  PrimeNG 15.2.1.

package.json

    "@angular/animations": "^15.2.5",
    "@angular/cdk": "^15.2.5",
    "@angular/common": "^15.2.5",
    "@angular/compiler": "^15.2.5",
    "@angular/core": "^15.2.5",
    "@angular/forms": "^15.2.5",
    "@angular/platform-browser": "^15.2.5",
    "@angular/platform-browser-dynamic": "^15.2.5",
    "@angular/router": "^15.2.5",
    "primeicons": "^6.0.1",
    "primeng": "~15.2.1",

Angular.json:

            "styles": [
              "src/styles.css",
              "node_modules/primeng/resources/primeng.min.css",
              "node_modules/primeicons/primeicons.css",
              "node_modules/primeflex/primeflex.css",
              "src/assets/css/quill.snow.min.css"
            ],

### Reproducer

https://github-erovyt.stackblitz.io

### Angular version

15.2.5

### PrimeNG version

15.2.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.13.1

### Browser(s)

Chrome 111.0.5563.149 (Official Build) (64-bit)

### Steps to reproduce the behavior

1. Add a p-autoComplete component to a form as in the reproducer
2. Unfortunately, the reproducer doesn't exhibit this behavior

### Expected behavior

The clear icon should be on the right-hand side of the control, and should properly animate when looking for suggestions.

**Comment by psarno** [comment]
Note that we do not override any styles in CSS or anything else that could alter the base behavior of this component. 

It's simply the component nested in the DIVs as shown in the code above.

**Comment by psarno** [comment]
@cetincakiroglu 

I've created an updated repro scenario that fully models our behavior, including having the component in a modal dialog.  

I see why this is happening.   If you go into the inspector and remove the 'right' CSS property on `p-autocomplete.p-autocomplete-clearable .p-autocomplete-clear-icon`, you will see the same behavior we are seeing.

![image](https://user-images.githubusercontent.com/18640860/233424291-37266601-6a98-4845-b33b-3c7aecaabc4a.png)

Removing that CSS property ends up with what we're seeing:

![image](https://user-images.githubusercontent.com/18640860/233425259-473682b6-28cc-4eb2-9862-4216e378c817.png)

https://stackblitz.com/edit/github-uka4gw?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

Our component does not get this style applied to it at all.

Any ideas as to why ours is missing `p-autocomplete.p-autocomplete-clearable`?  If I manually add this `right` property, it fixes it.

So at least we have a workaround, but I'm not sure what exactly is happening.

![image](https://user-images.githubusercontent.com/18640860/233423572-d93e5bad-085e-47e9-9c5d-5e82792d28d3.png)

**Comment by psarno** [comment]
We have upgraded to Angular 16.0.4 and PrimeNG 16.0.0-rc.2 and continue to see this issue.

Not just with the clear icons, but also with the "eyeball" to show passwords.

I've double checked our CSS, we are not altering the way these components are rendered.

![image](https://github.com/primefaces/primeng/assets/18640860/1e6c9e74-596f-428f-b1e0-63adc66b77a1)

**Comment by pgerste** [comment]
> We have upgraded to Angular 16.0.4 and PrimeNG 16.0.0-rc.2 and continue to see this issue.
> 
> Not just with the clear icons, but also with the "eyeball" to show passwords.
> 
> I've double checked our CSS, we are not altering the way these components are rendered.
> 
> ![image](https://user-images.githubusercontent.com/18640860/244096053-1e6c9e74-596f-428f-b1e0-63adc66b77a1.png)

The same issue appears even in the official PrimeNG docs (v16.0.1):
https://primeng.org/password#togglemask
