### ISSUE TITLE
Paginator: previous and next button icons not visible

### ISSUE THREAD

**Issue by h3llrais3r** [primefaces/primeng#12916]
### Describe the bug

Using the paginator in combination with the table by setting [paginator]="true".
Running latest version 15.4.0 of primeng.
Navigation buttons are present, but icons are not visible.
The problem occurs since upgrade to version 15.
![image](https://user-images.githubusercontent.com/1945295/233365167-7b024624-233e-4217-a73b-400b3f534a86.png)

When overriding the templates within the p-table, it works as expected.
```html
<ng-template pTemplate="paginatorfirstpagelinkicon">
    <p-button type="button" icon="pi pi-angle-double-left" styleClass="p-button-text"></p-button>
  </ng-template>
  <ng-template pTemplate="paginatorpreviouspagelinkicon">
    <p-button type="button" icon="pi pi-angle-left" styleClass="p-button-text"></p-button>
  </ng-template>
  <ng-template pTemplate="paginatornextpagelinkicon">
    <p-button type="button" icon="pi pi-angle-right" styleClass="p-button-text"></p-button>
  </ng-template>
  <ng-template pTemplate="paginatorlastpagelinkicon">
    <p-button type="button" icon="pi pi-angle-double-right" styleClass="p-button-text"></p-button>
  </ng-template>
```

![image](https://user-images.githubusercontent.com/1945295/233366249-091d25f5-b157-4197-8dfd-7206a75c547f.png)

The problem seems to be coming from the custom icon components (f.e. AngleDoubleLeftIcon) below not being rendered:
![image](https://user-images.githubusercontent.com/1945295/233372119-cf246a83-774d-4004-8a81-7efb47a19a0c.png)

### Environment

Any

### Angular version

15.2.8

### PrimeNG version

15.4.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.20.0

### Expected behavior

Button icons to appear by default

**Comment by cetincakiroglu** [comment]
Hi,

Thanks for reporting the issue, it'll be fixed in the upcoming release next week!

**Comment by h3llrais3r** [comment]
Just tried the new release, and I can confirm it's fixed.
Thanks for the quick solution!
![image](https://user-images.githubusercontent.com/1945295/233711351-70b4de1e-fca1-4e88-a4a2-d66f570358cc.png)

**Comment by gauravpatni123** [comment]
when there are no records in the p-table then in the paginator, I am unable to select page size from the dropdown as the dropdown is disabled , can someone help me on that ?
