### ISSUE TITLE
Table: multi-column sorting is not working correctly for string data that contains some character combinations.

### ISSUE THREAD

**Issue by andreduejon** [primefaces/primeng#12910]
### Describe the bug

Hi guys!

I've been trying to figure out why my multi-column sort has been behaving strangely lately. Ever since I upgraded from an early version 14.x.x to the version 15.3.0. 

It seems that line 181 `value1.localeCompare(value2, locale, { numeric: true }` in `objectutils.ts` is no longer sorting our data properly. Setting the field `numeric` to `false` solved the issue for me, but I expect that this was implemented for a reason in #11918.

Example: When sorting in ascending order, the value _59A446_ (string) comes before _038898_ (string). The field contains unique IDs that can contain letters, but mostly consist of numbers. I provided a quick stackblitz project.

I guess I could use a custom sort function, however, I do not believe that this behaviour is correct.   

### Environment

Angular 15 application using PrimeNg 15.3.0.

### Reproducer

https://stackblitz.com/edit/angular-kgrjhr

### Angular version

15.2.3

### PrimeNG version

15.3.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.13.0

### Steps to reproduce the behavior

This issue has a stackblitz project linked.

1. Set `sortMode `of table to `multiple`.
2. Have in one columns data that consist of numbers, numbers and upper case letters.
3. Sort the column as the first column.

### Expected behavior

The expected behaviour is to have the sorting as it was before the change to the sorting function, or to have an option to use the old implementation.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
