### ISSUE TITLE
p-password toggleMask not styled

### ISSUE THREAD

**Issue by cholasimmons** [primefaces/primeng#12918]
### Describe the bug

The "eye" icon that reveals the password upon clicking, is now left aligned with no padding, it feels like a bug rather than a design choice. It was fine in version 15.3.0, right aligned with good padding

### Environment

Angular 15, PrimeNG 15.4, nothing extravagant running on a Windows 11 laptop.
I've been running my project for 2 months now, no issues

### Angular version

15.2.1

### PrimeNG version

15.4.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.15.0

### Browser(s)

Firefox 112.0.1

### Steps to reproduce the behavior

Simply `npm install primeng` and add a p-password to a form.

### Expected behavior

As in the previous minor version, the icon was well padded despite it being on the right hand side (which feels better)

**Comment by cetincakiroglu** [comment]
Hi,

Thanks for reporting the issue, it'll be fixed in the upcoming release next week!

**Comment by cholasimmons** [comment]
Thanks, will be waiting

**Comment by ebrfawzy** [comment]
Any updates for this fix?

I am using 
 "primeflex": "^3.3.1",
"primeicons": "^6.0.1",
"primeng": "^16.0.2",

the same bug with toggle password icon.

**Comment by aboteler** [comment]
I am having the same issue where the eye icon is right-aligned not left-aligned.

My package.json has

"primeflex": "^3.3.1",
"primeicons": "6.0.1",
"primeng": "^16.3.1",

I am using p-password this way
`
<div class="col-12">
          
          <p-password [(ngModel)]="userSignup.password"
                      appendTo="body"
          >
          </p-password>
</div>
`

**Comment by ebrfawzy** [comment]
@aboteler I got problem solved when replacing old theme.css files with the new ones here:

https://github.com/primefaces/primeng/tree/master/src/assets/components/themes

**Comment by aboteler** [comment]
Thanks for the info.  I can't use those theme files since I am using the freya template.
