### ISSUE TITLE
p-table: Not rendering itself in Virtual Scroll mode after a parent element becomes visible

### ISSUE THREAD

**Issue by AbakumovAlexandr** [primefaces/primeng#12912]
### Describe the bug

With the latest PrimeNG (15.3.0). `<p-table>` in Virtual Scroll mode doesn't render itself  If its `value` is updated and `<p-table>` is inside a `display: none;` parent element, `<p-table>` displays itself as a zero dimensional block when that parent element becomes visible.

It looks similar to a previosly fixed issue #7345.

Could you advice. please?

### Environment

Windows 10.

### Reproducer

https://stackblitz.com/edit/github-exso2o

### Angular version

15.2.7

### PrimeNG version

15.3.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.13.0

### Browser(s)

Chrome 112

### Steps to reproduce the behavior

1. Click on the TOGGLE VISIBILITY button to display an empty p-table (with a column header only) for the 1st time.
2. Click on the TOGGLE VISIBILITY button 2nd time to hide the empty p-table.
3. Click on the NEW DATA button to assign another data source to p-table whike it's invisible.
4. Click on the TOGGLE VISIBILITY button to display the p-table. Nothing gets visually changed, even the column header doesn't get displayed as on the step # 1.
If you inspect the p-table HTML element, you could make sure its dimensions are 0 x 0 for some reason.

### Expected behavior

After changing the visibility of any p-table's parent element from `display: none;` to `display: <any of not none>;`, p-table in Virtual Scroll mode must render itself properly.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
