### ISSUE TITLE
New trackBy prop in Carousel component

### ISSUE THREAD

**Issue by dkrzysztof** [primefaces/primeng#12923]
### Describe the feature you would like to see added

Hi, I see that in the carousel component is missing any `trackBy` declaration. Could it be added ? 

### Is your feature request related to a problem?

I tried implementing a carousel of images that displays images with different statuses ( status and image url is passed in the array via the `[value]` prop). Basically three statuses: `checked`, `loading`, and `ready`. Each status is updated in the array asynchronously, which happens quickly (each image change is around 1 sec). The update comes in the updated property of a single image that is passed with all images array to `[value]` - so the update happens by updating the `[value]` prop.

Without `trackBy` prop, Angular recreates all of the components, which makes the whole carousel flicker and load all images every time each second until the updates stop instead of updating single component of the carousel.

### Describe the solution you'd like

Add simple `trackBy` or `trackByFn` Input prop to the carousel component

### Describe alternatives you have considered

I thought of creating a wrapper component around carousel items and bypassing the initialization by creating some service, but this solution seems to be the Angular way and definitely less buggy.

**Comment by cetincakiroglu** [comment]
Hi,

Thanks for the suggestion, it's a good idea to improve performance we'll look into it

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
