### ISSUE TITLE
Missing media component in PrimeNG: Fan

### ISSUE THREAD

**Issue by morsagmon** [primefaces/primeng#12927]
### Describe the feature you would like to see added

In addition to the Carousel and Galleria, I am missing a component that mimics the cards selection that looks like a "fan":
![image](https://user-images.githubusercontent.com/22539785/233616508-c505d241-272f-40ec-988c-2b495c829dc3.png)

### Describe the solution you'd like

As swipeable element to pick up an image, as shown here:

![image](https://user-images.githubusercontent.com/22539785/233616225-af96395d-bbbf-4760-9d82-a21e3cc32b3c.png)

The images can be swiped left or right, with a single image currently on top, tappable (selectable).

Another approach can be seen here:
https://swiperjs.com/demos/255-effect-cards/core

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
