### ISSUE TITLE
Tree: Accumulating right and bottom paddings

### ISSUE THREAD

**Issue by burkaysucu** [primefaces/primeng#12921]
In theme.css, there is the following rule:

```
.p-tree .p-tree-container .p-treenode {
  padding: 0.143rem;
}
```

This means accumulating right and bottom paddings. As a result, the horizontal space decreases and the gap between successive items increases for deeper nodes. I guess it should not be by design because it does not look good and showing more space around an inner node than around an upper node does not sound desirable. Just changing the padding values for right and bottom to 0 in the same rule set is enough to solve this. Below are screenshots from the tree component's documentation page. Used "highlight all elements matching this selector" feature of the dev tools to get them. It gets worse for a tree with more depth.

![accumulating](https://user-images.githubusercontent.com/45235622/233392244-2601ed2b-1ef2-4d32-b622-923a5b8b3c89.jpg)

![not accumulating](https://user-images.githubusercontent.com/45235622/233392272-e1a32f48-c140-4522-8f71-0324a961e6b6.jpg)

### Environment

It is observable on PrimeNG documentation page as well.

### Angular version

15.2.0

### PrimeNG version

15.4.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.20.0

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
