### ISSUE TITLE
p-checkbox 

### ISSUE THREAD

**Issue by DanilVezmenov** [primefaces/primeng#12920]
### Describe the bug

after the minor update of priming, something changed in the structure of the p-checkbox because of this, I had problems with the work of the code.

### Environment

Common angular app

### Angular version

^15.2.0

### PrimeNG version

^15.2.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.15.0

### Browser(s)

Chrome last version

### Steps to reproduce the behavior

The difference between 15.2.1 and ^15.2.1
![image](https://user-images.githubusercontent.com/107387472/233390989-e334a146-3621-4725-b49d-8b3f9db8e0a1.png)
![image](https://user-images.githubusercontent.com/107387472/233391087-2320c172-9907-4e26-b325-1b31bad86916.png)

простите за плохое описание проблемы, но она пропала после того как я жестко зафиксировал версию библиотеки на   15.2.1

for style custom check i use 
```
.pi-check:before {
  content: url(./assets/check.svg) !important;
  width: 10px !important;
  height: 8px !important;
}
```

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
