### ISSUE TITLE
Component: TreeSelect & MultiSelect

### ISSUE THREAD

**Issue by andytanasa** [primefaces/primeng#12926]
### Describe the bug

If the overlay-panel is opening above the input and searching for options, the overlay-panel is remaining in the initial position. 
The same issue is with multiselect as well.

### Environment

Dev

### Angular version

15.2.7

### PrimeNG version

15.3.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.20.0

### Steps to reproduce the behavior

Go to PrimeNg website -> search for TreeSelect or MultiSelect -> scroll down to filter-> let the treeSelect under the filter chapter to be at the bottom of the screen -> in the open overlay search for an option -> the overlay is not moving down to be connected with the input.

### Expected behavior

After search, with the overlay-panel above the input, it should be connected to the input. Thank you.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
