### ISSUE TITLE
Component: P-Image Preview Image URL

### ISSUE THREAD

**Issue by webtimo-de** [primefaces/primeng#12928]
### Describe the feature you would like to see added

Hello, I would find it very good if a preview URL can also be given with the p-image for preview, so I don't always have to load the entire image, but a smaller version is loaded, and only when you look at the large one want to indicate that it will then load.

### Describe the solution you'd like

So I would give two parameters at this point, first src where you show the original image and for the preview parameter you can not only specify a boolean, but also a string, where the small image variant is then entered.

**Comment by Adishone** [comment]
The other way to get around this issue could be to add **srcset** and **sizes** attributes to img element:
```
<img
  srcset="elva-fairy-480w.jpg 480w, elva-fairy-800w.jpg 800w"
  sizes="(max-width: 600px) 480px,
         800px"
  src="elva-fairy-800w.jpg"
  alt="Elva dressed as a fairy" />
```
probably a bit more flexible in the future and easier to implement now. Article about responsive images:
https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

Anyway +1 for fixing that

**Comment by webtimo-de** [comment]
> 

I don't quite understand your comment, whether it should serve as a solution or as a supplement. In my case, I show pictures where I don't know what size they are. Neither height nor width. I have customized sizes for desktop environment. My application is not intended for mobile phones. I just want my server traffic and server performance to be burdened less, as I partly display several images, but which are usually not viewed, and thus the image would not have to be loaded in full size. And since I like to use the "preview=True" to avoid opening images in the new tab, I would prefer such a simple workflow. Because first building an img and then preview does not correspond to the philosophy of PrimeNG.

**Comment by Adishone** [comment]
> > 
> 
> I don't quite understand your comment, whether it should serve as a solution or as a supplement. In my case, I show pictures where I don't know what size they are. Neither height nor width. I have customized sizes for desktop environment. My application is not intended for mobile phones. I just want my server traffic and server performance to be burdened less, as I partly display several images, but which are usually not viewed, and thus the image would not have to be loaded in full size. And since I like to use the "preview=True" to avoid opening images in the new tab, I would prefer such a simple workflow. Because first building an img and then preview does not correspond to the philosophy of PrimeNG.

I'm saying that there are two ways of fixing this problem, the one that you mentioned by adding separate source attribute for preview image and second one by adding srcset and sizes attributes.

**Comment by webtimo-de** [comment]
> > I don't quite understand your comment, whether it should serve as a solution or as a supplement. In my case, I show pictures where I don't know what size they are. Neither height nor width. I have customized sizes for desktop environment. My application is not intended for mobile phones. I just want my server traffic and server performance to be burdened less, as I partly display several images, but which are usually not viewed, and thus the image would not have to be loaded in full size. And since I like to use the "preview=True" to avoid opening images in the new tab, I would prefer such a simple workflow. Because first building an img and then preview does not correspond to the philosophy of PrimeNG.
> 
> I'm saying that there are two ways of fixing this problem, the one that you mentioned by adding separate source attribute for preview image and second one by adding srcset and sizes attributes.

Thank you for your reply.

As far as I know, however, this does not work in the `p-image`, since I do not use `img` myself, unfortunately this does not help me ):

Https://primeng.org/image

Since "img" does not have a preview function.
