### ISSUE TITLE
Component: dynamic Tabview

### ISSUE THREAD

**Issue by catherinekennedy** [primefaces/primeng#12931]
### Describe the bug

hello all,If I pass the tab content dynamically. the content is only shown at the last tab and remaining tabs are empty

```
<p-tabView>
  <ng-container *ngFor="let item of tabviewData.data">
    <p-tabPanel [header]="item.title">
      <ng-content></ng-content>
    </p-tabPanel>
  </ng-container>
</p-tabView>
```

```
 <tabview [tabviewData]='tabviewData'>
  <div>
  <p>tab 1</p>
</div>
<div>
  <p>tab 2</p>
</div>
<div>
  <p>tab 3</p>
</div>
  </tabview>
```
![image](https://user-images.githubusercontent.com/67736813/233969240-e980293b-eaa5-4a0d-abfe-9bed83f40c5f.png)

![image](https://user-images.githubusercontent.com/67736813/233969319-6549e722-1422-4093-a184-6577ce7c0ac0.png)

### Environment

dev

### Angular version

14.2.12

### PrimeNG version

14.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.13.0

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
