### ISSUE TITLE
MultiSelect | Alignment is broken if showClear is enabled

### ISSUE THREAD

**Issue by cetincakiroglu** [primefaces/primeng#12932]
Steps to reproduce:

- Select value
- See the alignment fail

https://stackblitz.com/edit/angular-isdwdl?file=src%2Fapp%2Fdemo%2Fmulti-select-basic-demo.html

**Comment by MarvinSchoening** [comment]
The fix got reverted and it's broken again, see: https://github.com/primefaces/primeng/commit/5e0a3f3a4021df734d56c9ff6b9a70f1eaae0bed
