### ISSUE TITLE
Component: Carousel swipe not working properly on iOS devices

### ISSUE THREAD

**Issue by franpereadev** [primefaces/primeng#12942]
### Describe the bug

I'm submitting a

[X] bug report 

Current behavior
Open up https://primeng.org/carousel

If you open it up in responsive mode in chrome / use it on Android the swiping works fine. If you try to do the same in iOS it doesn't work.

Expected behavior
The gestures should work on both on iOS and Android

What is the motivation / use case for changing the behavior?
The user experience should be the same on both systems.

### Environment

Please tell us about your environment:

Angular version: 15

PrimeNG version: 15.2

Browser: [iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Language: [all]

### Angular version

15.2

### PrimeNG version

15.2

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

16

### Browser(s)

Safari and chorme in all iOS devices

### Steps to reproduce the behavior

Open up https://primeng.org/carousel

If you open it up in responsive mode in chrome / use it on Android the swiping works fine. If you try to do the same in iOS it doesn't work.

### Expected behavior

The gestures should work on both on iOS and Android

**Comment by strasvoul** [comment]
Same issue! just to mention that from chrome's emulators seems to work fine but in a real device it doesn't.

**Comment by vikramt24** [comment]
Same issue. Can we get in the Next Release

**Comment by northrain04** [comment]
Same issue too

**Comment by jcarpintero11** [comment]
Same issue.

**Comment by cetincakiroglu** [comment]
fixed in https://github.com/primefaces/primeng/pull/14575
