### ISSUE TITLE
Using SplitButton causes  ReferenceError: Cannot access 'TieredMenu' before initialization

### ISSUE THREAD

**Issue by bendehghan** [primefaces/primeng#12945]
### Describe the bug
Looks like a new bug in 15.4.0
While running tests into my application I got the following error:

```   
    ReferenceError: Cannot access 'TieredMenu' before initialization

      37 | import {RadioButtonModule} from 'primeng/radiobutton';
      38 | import {SpeedDialModule} from 'primeng/speeddial';
    > 39 | import {SplitButtonModule} from 'primeng/splitbutton';
         | ^
      40 | import {TabViewModule} from 'primeng/tabview';
      41 | import {TieredMenuModule} from 'primeng/tieredmenu';
      42 | import {ToggleButtonModule} from 'primeng/togglebutton';

      at Object.<anonymous> (node_modules/primeng/fesm2020/primeng-tieredmenu.mjs:195:243)
      at Object.<anonymous> (node_modules/primeng/fesm2020/primeng-splitbutton.mjs:8:21)
      at Object.<anonymous> (src/app/rc/dm-rc.module.ts:39:1)
      at Object.<anonymous> (src/app/rc/main-rc/main-rc.component.spec.ts:10:1)

```

### Environment
Mac Jest tests.

### Angular version
```
        "@angular/animations": "15.2.8",
        "@angular/cdk": "15.2.8",
        "@angular/common": "15.2.8",
        "@angular/compiler": "15.2.8",
        "@angular/core": "15.2.8",
        "@angular/forms": "15.2.8",
        "@angular/platform-browser": "15.2.8",
        "@angular/platform-browser-dynamic": "15.2.8",
        "@angular/router": "15.2.8",
        "@angular-builders/custom-webpack": "15.0.0",
        "@angular-builders/jest": "15.0.0",
        "@angular-devkit/architect": "0.1502.6",
        "@angular-devkit/build-angular": "15.2.6",
        "@angular-devkit/core": "15.2.6",
        "@angular-eslint/builder": "15.2.1",
        "@angular-eslint/eslint-plugin": "15.2.1",
        "@angular-eslint/eslint-plugin-template": "15.2.1",
        "@angular-eslint/schematics": "15.2.1",
        "@angular-eslint/template-parser": "15.2.1",
        "@angular/cli": "15.2.6",
        "@angular/compiler-cli": "15.2.8",
        "@angular/language-service": "15.2.8",

```

### PrimeNG version
14.1.0

### Build / Runtime
Angular CLI App

### Node version (for AoT issues node --version)
v19.6.1
 
### Browser(s)
CLI

### Steps to reproduce the behavior
import {SplitButtonModule} from 'primeng/splitbutton';
`npx jest --clearCache && npx jest --no-cache --updateSnapshot .`

### Things I've tried
Using primeng 15.3.0 and zone.js 12 works fine. With 15.4.0 and required zone.js 13 I get the new errors.

**Comment by bendehghan** [comment]
This is a similar bug: 
https://github.com/primefaces/primeng/issues/11931

**Comment by bendehghan** [comment]
Can somebody please triage this so we can at least get it on the radar? What is the triage process? Are we missing any info to get going?
Thank you :)

**Comment by blackholegalaxy** [comment]
ping @cagataycivici  @cetincakiroglu

**Comment by cetincakiroglu** [comment]
Thanks for reporting, we're investigating the issue.

**Comment by pudrik** [comment]
I got the same issue on 16.0.2, both Menubar and TiredMenu. From what i can tell the errors manifest themselfs different depending on the order of the import statement

**Comment by vespertilian** [comment]
As of 16.1.0 this is also an issue with the Mega Menu. 16.0.2 works.

**Comment by psbenz** [comment]
Possible workaround:

jest.mock('primeng/splitbutton', () => ({
  SplitButtonModule: jest.fn(),
}));
jest.mock('primeng/contextmenu', () => ({
  ContextMenuModule: jest.fn(),
}));

**Comment by osmolo** [comment]
> jest.mock('primeng/splitbutton', () => ({
> SplitButtonModule: jest.fn(),
> }));

Suggested workaround doesn't work for me.
_mockConstructor does not have a module def (ɵmod property)_
_Unexpected value 'mockConstructor' imported by the module 'SharedModule'. Please add an @NgModule annotation._ (SharedModule is my module that imports SplitButtonModule)

**Comment by psbenz** [comment]
I added the mocks in setup-jest.ts and it works for me

**Comment by osmolo** [comment]
I endend up mocking this way in setup-jest.ts:

```
@NgModule()
export class SplitButtonMockModule { }

jest.mock('primeng/splitbutton', () => ({
  SplitButtonModule: SplitButtonMockModule,
}));
```
