### ISSUE TITLE
Overlay: p-overlay div not removed from DOM on hiding panel

### ISSUE THREAD

**Issue by RinoGaetano94** [primefaces/primeng#12948]
### Describe the bug

When hiding the overlay content (clicking outside the panel or programmatically) the wrapper div with class 'p-overlay' will not be removed from the DOM. This will cause an invisible layer blocking interactions with the page. If you perform another click, the p-overlay div will be removed from DOM.

It seems to happen only if responsive params is passed.

It seems to work properly on 14.2.2 Official Documentation.

This is the div that should be removed from DOM (it will removed on second click)
![Schermata del 2023-04-26 10-43-23](https://user-images.githubusercontent.com/16806264/234521056-01b6f35b-fec6-413e-a211-4347e0c22f8a.png)

### Environment

PrimeNG Official Documentation

### Reproducer

https://primeng.org/overlay#basic

### Angular version

15.2.2

### PrimeNG version

15.1.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.13.0

### Steps to reproduce the behavior

0. Trigger the responsive breakpoint resizing the window.
1. Click the "Show Overlay" button in the basic example.
2. Click outside the overlay panel to make it disappear.

If you try to click the "Show Overlay" button again to reopen the overlay, it will fail. You will not see the cursor pointer too. 

Even if the click fails, the p-overlay wrapper will be correctly removed this time

### Expected behavior

When hiding overlay panel, the p-overlay wrapper should be removed from DOM to re-establish the page interaction

**Comment by faisal6699** [comment]
Need immediate solve :|
