### ISSUE TITLE
Component: Menu popup in dialog

### ISSUE THREAD

**Issue by Wykks** [primefaces/primeng#12952]
### Describe the bug

Menu in popup mode doesn't position correctly when used in a dialog

### Environment

Stackblitz

### Reproducer

https://stackblitz.com/edit/angular-kvd6ry?file=src/app/demo/dialog-basic-demo.ts

### Angular version

15.2.1

### PrimeNG version

15.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.4

### Steps to reproduce the behavior

Use a Menu without popup:true inside a Dialog

**Comment by cetincakiroglu** [comment]
There is `appendTo` property for this.

https://stackblitz.com/edit/angular-kvd6ry?file=src%2Fapp%2Fdemo%2Fdialog-basic-demo.html
