### ISSUE TITLE
p-inputmask: cannot use 'a' or '9' as fixed part of mask

### ISSUE THREAD

**Issue by mgrzego3** [primefaces/primeng#12955]
### Describe the bug

When trying to use fixed part in mask which includes 'a' or '9' it expects letter or digit.
For example mask="9 and 9" converts to "9 _nd 9"
 mask="(+490) 999-9999" converts to "(+4_0) ___-____"

### Environment

stackblitz

### Reproducer

https://primeng-inputmask-demo-anzbcc.stackblitz.io

### Angular version

15.1.3

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14.0

### Browser(s)

firefox, chrome

### Steps to reproduce the behavior

Use 'a' or '9' in inputmask

### Expected behavior

Make some way to escape character like "\9"
<p-inputMask mask="(+4\90) 999-9999" ....>
or add some property to define special character for digits and letters like
<p-inputMask digitMask="#" mask="(+490) ###-####" ....>

**Comment by jhcpeixoto** [comment]
#13413

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
