### ISSUE TITLE
Upgraded from 14.01 to 15.4, now Column widths change

### ISSUE THREAD

**Issue by danrald** [primefaces/primeng#12963]
### Describe the bug

Normally our columns fit in a specific area of the page. Since upgrading, some columns expand to fit all of the characters that are in the column. This expansion of the columns is putting a horizontal scrollbar, so the users cannot see all of the columns unless they use the scroll. What is causing this? We need to have the view. Any ideas?

Thanks

### Environment

Primeng 15.4.0
Angular 15.2.7
Typescript: 4.8.4

### Angular version

15.2.7

### PrimeNG version

15.4.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.13.0

### Browser(s)

Chrome

**Comment by vinnyab28** [comment]
Hi @danrald,
I've faced a similar issue once during migration of PrimeNG.
Here is the thing which I observed and made changes accordingly to fit my requirement:

- The classes in the table have been updated from the `v14.0.1` and `v15.4.1`

[v14.0.1](https://github.com/primefaces/primeng/blob/v14.0.1/src/app/components/table/table.ts)
`<table #table role="table" class="p-datatable-table" [ngClass]="tableStyleClass" [ngStyle]="tableStyle" [style]="scrollerOptions.spacerStyle" [attr.id]="id+'-table'">`

[v15.4.1](https://github.com/primefaces/primeng/blob/master/src/app/components/table/table.ts)
`<table
                        #table
                        role="table"
                        [ngClass]="{ 'p-datatable-table': true, 'p-datatable-scrollable-table': scrollable, 'p-datatable-resizable-table': resizableColumns, 'p-datatable-resizable-table-fit': resizableColumns && columnResizeMode === 'fit' }"
                        [class]="tableStyleClass"
                        [style]="tableStyle"
                        [attr.id]="id + '-table'"
                    >`

So if you observe, additional classes such as `p-datatable-scrollable-table` , `p-datatable-resizable-table` and with respect to that CSS have also been updated in the codebase of PrimeNG.

So I recommend you to check the classes in your project and updated them accordingly as well.

**Comment by danrald** [comment]
@vinnyab28 
Thanks Vineeth!

I'm still having trouble with the, but I have narrowed it down to some flex issues. Thanks for the replay.

**Comment by vinnyab28** [comment]
> @vinnyab28 Thanks Vineeth!
> 
> I'm still having trouble with the table, but I have narrowed it down to some flex issues. Thanks for the reply.

@danrald since this isn't an issue with the code, I guess you can close this issue now.

**Comment by danrald** [comment]
@vinnyab28,

My solution that I posted had issues. Im back to square one. For some reason the table.css is not being loaded at all. if I set table-layout to fixed, the columns do not flex. For some reason the styling is not being loaded at all. At least the what it look like the issue is now.

**Comment by joshuadesmith** [comment]
Has anyone gotten a working solution to preventing column autosizing? I'm trying to prevent columns from expanding on a scrollable table with a dynamic number of columns. Widths set with either `[style.width]` or cell class seem to be ignored entirely.

**Comment by joshuadesmith** [comment]
Was able to workaround the issue by setting `display: flex` on the `<tr>` elements for both the header and body templates and then setting the width of all `<th>` and `<td>` elements.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
