### ISSUE TITLE
Component: Table ColumnFilter

### ISSUE THREAD

**Issue by andrerauer** [primefaces/primeng#12961]
### Describe the bug

The Table does not filter data with the date filter as a row filter. After changing sort or something else, the filter is applied.

### Environment

Stackblitz, chrome Browser, OSX

### Reproducer

https://stackblitz.com/edit/github-auqy6v

### Angular version

14.x and above

### PrimeNG version

14.x and above

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.15.1

### Browser(s)

Chrome

### Steps to reproduce the behavior

Add Table, add date filter in "row mode". Click in Date-Filter, choose a date: nothing happend. Change Sort-Order for one column: Data is filtered.

### Expected behavior

Data is filtered.

**Comment by mehmetcetin01140** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.
