### ISSUE TITLE
Component: TreeTable

### ISSUE THREAD

**Issue by MaximeKoitsalu** [primefaces/primeng#12960]
### Describe the bug

Resize feature does not work anymore. When you try the resize line gets stuck and nothing happens. You need to refresh to get "unstuck".

### Environment

Your documentation

### Reproducer

https://stackblitz.com/edit/angular-tivs1m?file=package.json

### Angular version

15.2.1

### PrimeNG version

15.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14.2

### Browser(s)

Latest Chrome & Latest Firefox

### Steps to reproduce the behavior

Step 1: 
Navigate here: https://primeng.org/treetable#fitmode

Step 2:
Try and resize any of the columns.

Step 3:
Observe the broken feature.

### Expected behavior

The columns do resize. And not a stuck line and no resize.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
