### ISSUE TITLE
Inputnumber: Keyboard Navigation not working properly

### ISSUE THREAD

**Issue by paulstelzer** [primefaces/primeng#12969]
### Describe the bug

Keyboard Navigation not working properly in inputnumber with suffix

### Environment

Chrome / Firefox / Safari

### Reproducer

https://primeng.org/inputnumber

### Angular version

15.2.8

### PrimeNG version

15.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Browser(s)

Chrome / Firefox / Safari

### Steps to reproduce the behavior

1. Go to Prefix & Suffix (https://primeng.org/inputnumber)
2. Type in "8888" in Miles
3. Try to arrow left or delete on keyboard. it's not working

https://user-images.githubusercontent.com/20501666/235094223-f46093e7-8754-436d-b2b4-13cf4c2ea516.mov

### Expected behavior

Keyboard navigation should work

**Comment by zakharenkov** [comment]
reproduced in 16.2.0

**Comment by Agut14** [comment]
Is this fixed in some version?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
