### ISSUE TITLE
Primeng-Table Use Storage as Cookie instead of Session and Local Storage

### ISSUE THREAD

**Issue by krunal8123** [primefaces/primeng#12968]
I have checked the table.ts file and seen that only storage mechanisms used are "Session" and "Local" storage. Is it possible to use cookie as storage mechanism ??

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
