### ISSUE TITLE
Row based styling for DataTable

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#1296]

**Comment by cagataycivici** [comment]
Added rowStyleClass which is a function that gets the row data and returns the style class.

**Comment by pmeems** [comment]
I tried but can't get it to work.
I've update the primeNg components and I can see `<tr #rowElement [class]=\"getRowStyleClass(rowData,rowIndex)\"` in \node_modules\primeng\components\datatable\datatable.js
So I assume I have the correct version.
My table looks like this:
`<p-dataTable [hidden]="loading" [rowStyleClass]="customRowClass" [value]="timePeriods" scrollable="true" scrollHeight="400px">`
And my function:
`    public customRowClass(rowData, rowIndex): string {
        console.log("In customRowClass");
        console.log(rowData);
        console.log(rowIndex);
        return "";
    }`

rowData and rowIndex are undefined.
I want to use a class when a property of my rowData is false.
Please advice.

**Comment by onstottj** [comment]
Does `rowData` have the information you'd use to determine the CSS class for that row?  If so, how are you using that in customRowClass()?

This question is also posted here: http://stackoverflow.com/q/40528666/132374
