### ISSUE TITLE
Format file size of p-fileupload

### ISSUE THREAD

**Issue by pmeems** [primefaces/primeng#1297]
As I mention here: http://stackoverflow.com/questions/40514986/how-tp-customize-primeng-p-fileupload it is very hard to customize the formatting of the file size in p-fileupload.
It now shows 3 digits which is very confusing.

Perhaps implementing this one is enough: https://github.com/RenovoSolutions/TypeScript-Angular-Utilities/blob/master/source/services/fileSize/fileSize.md

Also adding some option for the developer to easily override the used formatting is very welcome.

Related issue #1247

**Comment by pmeems** [comment]
#1247

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/VZbdZfQ7SuTV87tTkbYR
