### ISSUE TITLE
Dropdown: rendering problem when used in a Dialog and dialog's parent is scrolled

### ISSUE THREAD

**Issue by adelesse** [primefaces/primeng#12970]
### Describe the bug

The dropped-down list becomes detached from the input when the dialog's parent is scrolled. Even using `appendTo="body"`

Similar to : https://github.com/primefaces/primereact/issues/2683

![image](https://user-images.githubusercontent.com/5594132/235174276-1f9d7d36-7d01-4c3f-b2e2-e4d3e6481dbd.png)

### Environment

Chrome

### Angular version

15.2.1

### PrimeNG version

15.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

Can be reproduce on official documentation :

- Go to : https://primeng.org/dialog#overlaysinside 
- On _Overlays Inside_ click "Show"
- Open dropdown 
- Scroll parent body

### Expected behavior

Dropdown should not be affected by scrolling the parent component.

**Comment by ashikjs** [comment]
@adelesse Can you check your dialog z-index value or any reproachable code or live link .

Most chance have your  dialog z-index is more then dropdown.

**Comment by adelesse** [comment]
Hi @ashikjs,

I am exactly in the same conditions of the official demo.
I made a fork here : https://stackblitz.com/edit/yhji8y-894kvf?file=src%2Fapp%2Fdemo%2Fdialog-overlays-inside-demo.html

![image](https://github.com/primefaces/primeng/assets/5594132/a1106742-5615-4447-b26d-092848ad1b1b)

**Comment by Phileicht** [comment]
Since there is a fix for the react part for over a year now, is there a way to speed up the fix of this bug a little?
Would be great if this could get fixed soon.
You could also just use the same behavior as you do in react and close the dropdown options if scrolled outside the options.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
