### ISSUE TITLE
Treetable: if virtualScroll is applied together with scrollHeight=flex, can not override max-height for the table row

### ISSUE THREAD

**Issue by MariyaR** [primefaces/primeng#12971]
### Describe the bug

Hello everyone, 
I have a treetable in my app with the following settings: 
             class="bom-grid"
             styleClass="p-treetable-sm p-treetable-gridlines"
             [value]="data"
             [columns]="columnsToDisplay" 
             [scrollable]="true"
             [scrollHeight]="'flex'"
             [virtualScroll]="true"
            
after updating Angular to version 13->14->15 and hence updating primeng to version 15.4.1, if I use virtualScroll together with scrollHeight=flex, the overriding of max-height of table rows does not work. Please see the attached example on stackblitz which reproduce this bug - if I remove either scrollHeight = flex or virtualScroll, the [ngStyle] on line 20 starts to work. Also, if there are more data in the table (remove filtering in the component) and scrollHeight, virtualScroll and ngStyle are applied, the table starts to buggin when scroll down to the end of the table. This can be seen in the example (but not seen in my application). 

### Environment

Stackblitz, chrome Browser

### Reproducer

https://stackblitz.com/edit/primeng-treetable-demo-xbpqlc?file=README.md,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html

### Angular version

15, 14

### PrimeNG version

15, 14

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.16.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

1) use component treetable with 2 top level nodes inside parent component
2) use settings [scrollable]="true"
             [scrollHeight]="'flex'"
             [virtualScroll]="true" for the treetable 
3) try to apply max-height style to table row whatever way in order to make them smaller than all the parrent div

### Expected behavior

to have a possibility to limit the max-height of the table row

**Comment by hoangphuc2k** [comment]
Is there any solution for this problem yet?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
