### ISSUE TITLE
SelectButton: Custom color for each button

### ISSUE THREAD

**Issue by ikiliki** [primefaces/primeng#12974]
### Describe the feature you would like to see added

I would like to configure background color and font color for each button.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
