### ISSUE TITLE
New Feature: Add OTP Input Component

### ISSUE THREAD

**Issue by yashHenceforth** [primefaces/primeng#12978]
### Describe the feature you would like to see added

![image](https://user-images.githubusercontent.com/109594325/235590541-c1e80769-0e93-4a00-bdca-f286738f8494.png)

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
