### ISSUE TITLE
Dropdown size when menu options text is too long for borders

### ISSUE THREAD

**Issue by deblab0** [primefaces/primeng#12981]
- Steps to reproduce:
     - Edit HTML Elements code of a <li> element, that belongs inside the menu options of a dropdown, so that the span text is too long for the dropdown borders size
- Expected results:
     - Entry shows an ellipsis at the end (...) instead of the full text when it's too long for the dropdown
- Actual results:
     -  Option text is shown in full, making the dropdown larger than it was meant to look
- Details:
     - 
![image](https://user-images.githubusercontent.com/35925024/235704790-9312ebd6-a09d-4fb8-87cf-aae5ee421741.png)
![image](https://user-images.githubusercontent.com/35925024/235704828-41874e25-ccda-4432-b67e-37747295b6f2.png)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
