### ISSUE TITLE
treeSelect programmatically partialSelect

### ISSUE THREAD

**Issue by j-barth** [primefaces/primeng#12989]
### Describe the bug

Hi,

I implement a treeSelect in a simple CRUD form.
I use a formControl.
When user select a child node, the parent node will be partialSelected. This work correctly.

When the user return to the form, I init it with values previously saved.
To init the form, I build the selected node list. I put in the list children selection and parents selection. For parents selection I put node.partialSelected = true when it's necessary. 
This last point doesn't work, my parents nodes are always checked.

### Environment

Angular CLI: 14.2.10
Node: 16.20.0
Package Manager: yarn 3.3.0 
OS: linux x64

Angular: 14.2.12

primeng: 14.2.3

### Angular version

14.2.0

### PrimeNG version

14.2.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v16.20.0

### Steps to reproduce the behavior

Implement treeSelect with formControl using selectionMode="checkbox"
Init selection with partialSelected=true on a parentNode.

The partialSelected is not considered.

### Expected behavior

The parent node checkbox is partialSelected

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
