### ISSUE TITLE
Component: Button, Loading Attribute - Loading icon gets stuck when used

### ISSUE THREAD

**Issue by tgfactor** [primefaces/primeng#12980]
### Describe the bug

The pButton directive does not remove the loading icon after the loading attribute is set to false after it was initially set to true.

### Environment

Using primeng@15.4.x.  (Issue does not exist in prior versions).

### Angular version

15.2.8

### PrimeNG version

15.4.x

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.14.0

### Steps to reproduce the behavior

1. Set up a html button and add the pButton directive to it.
2. In the loading attribute ([loading]), set it to a variable that is initially true.
3. In the code, change that variable to be false to turn off the loading.
4. You will notice that while the opacity correctly changes from below 1 (loading true) to 1 (loading false), the loading icon fails to disappear when loading is false.
**Important:** I can verify (and have done the testing to prove) that this bug was introduced in version 15.4.x; the loading actions are correctly executing in version 15.3.

**Comment by tgfactor** [comment]
I can confirm that as of today, using version 16.1 of primeng, this loading icon being stuck is still happening and it has not been dealt with.  Please advise, yet again!

**Comment by passion2** [comment]
This is still an issue, is there a workaround for this?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
