### ISSUE TITLE
Add support for Angular 16

### ISSUE THREAD

**Issue by NateRadebaugh** [primefaces/primeng#12993]
### Describe the feature you would like to see added

Add support for Angular 16

### Is your feature request related to a problem?

Angular 16 was released by primeng does not include it as an allowed version of angular

### Describe the solution you'd like

Update peer dependencies to allow angular 16:
```json
    "peerDependencies": {
        "@angular/core": "^16.0.0",
        "@angular/common": "^16.0.0",
        "@angular/forms": "^16.0.0",
        "rxjs": "^6.0.0 || ^7.5.0",
        "zone.js": "^0.10.2 || ^0.11.0 || ^0.12.0 || ^0.13.0"
    }
```

### Describe alternatives you have considered

1. Keep on old angular
2. Force update anyway and run "npm install --force" every time

**Comment by imaksp** [comment]
it seems initial version is already ready see following:
https://github.com/primefaces/primeng/milestone/227?closed=1

**Comment by NateRadebaugh** [comment]
Great thanks, looks like mine is a dup of #12990
