### ISSUE TITLE
ColorPicker: programmatically set its value without ngModel

### ISSUE THREAD

**Issue by BenRacicot** [primefaces/primeng#12997]
### Describe the feature you would like to see added

Hello! It appears that quite often developers are seeking answers for how to set the color picker's value.

The docs do not have an answer for this without `ngModel`. 

Perhaps even more often we're using reactive forms. In my case I'd like to use ColorPicker within a form but only to inform the user of the color choice and to give them UI to potentially pick a color to propagate the color field. It is not an input field in this case but should only inform the actual text field.

This is a compounded issue when used within a form array where `ngModel` cannot be used and ColorPicker is only being used to inform a `color` field. ColorPicker is unusable in this situation.

```
// template
<p-colorPicker #picker></p-colorPicker>

// controller
picker.value = '#ff0000' // does not work like it does for other inputs
```

How can we set the color value for ColorPicker?

### Is your feature request related to a problem?

Reusable components have one job. I'm always frustrated when they do not function in the most basic ways. 
The color picker should be usable as if it is any other input field. Read its value, change its value, that's it.

### Describe the solution you'd like

You can see in [this Stackblitz reproduction](https://stackblitz.com/edit/5wqgyr?file=src%2Fapp%2Fdemo%2Fcolor-picker-reactive-forms-demo.html) that the colorpicker can inform the text field but not the other way around. Is this possible?

**Comment by imaksp** [comment]
It supports both template based forms & reactive forms so you should be able to use it with form array, see the following doc:
https://primeng.org/colorpicker#reactive-forms

**Comment by BenRacicot** [comment]
Hi @imaksp thanks for replying. I think the main issue I see is that informing the component does not work in every expected Angular way. Please see the original issue description for the details.

>This is a compounded issue when used within a form array where ngModel cannot be used and ColorPicker is only being used to inform a color field. ColorPicker is unusable in this situation.

**Comment by imaksp** [comment]
Hi, I assume you are using reactive form with form array which has color picker so setValue,  patchValue & valueChanges should work as expected. 
if you can create reproduction it will be helpful in narrowing down the issue. 
Also I am not a team member but can debug the issue in free time using reproduction.

**Comment by imaksp** [comment]
Also one more thing if this code does not work for colorpicker then its not a very big issue (as it is custom component): 
```
picker.value = '#ff0000'
```
as this code interacts with native DOM element directly, you should use setValue on control if you want to set it in Angular way.
& if you are using code this this for modifying other inputs  (using `input.value`) then it not an angular way & you should use setValue func.

**Comment by BenRacicot** [comment]
Updated with repro

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
