### ISSUE TITLE
MultiSelect: Allow null as a value for options to allow compatibility with the async pipe

### ISSUE THREAD

**Issue by Michael-Ziluck** [primefaces/primeng#12995]
### Describe the feature you would like to see added

Right now, the `options` input for the `MultiSelectComponent` only allows `any[]` as the input. When running in strict mode, this prevents the use of the `AsyncPipe` from Angular as that returns `T | null` rather than just `T`.

It would be nice to be able to do something like the following:

```html
<p-multiSelect [options]="availableOptions$ | async" [(ngModel)]="myModel"></p-multiSelect>
```

### Is your feature request related to a problem?

It's frustrating to need to use the MultiSelectComponent with the following syntax as it conflicts with the built-in change detection from Angular:

```html
<p-multiSelect [options]="(availableOptions$ | async) ?? []" [(ngModel)]="myModel"></p-multiSelect>
```

### Describe the solution you'd like

Change the typing of the get/set functions for `options` to something like this:

```typescript
    @Input() get options(): any[] | null {
        return this._options;
    }

    set options(val: any[] | null) {
        this._options = val ?? [];
        this.updateLabel();
    }
```

### Describe alternatives you have considered

This is the only alternative available, as mentioned above.
```html
<p-multiSelect [options]="(availableOptions$ | async) ?? []" [(ngModel)]="myModel"></p-multiSelect>
```

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
