### ISSUE TITLE
ConfirmDialog: Use Service inside lazy loaded Module

### ISSUE THREAD

**Issue by KevinHetzelGFL** [primefaces/primeng#12998]
### Describe the bug

I try to use the ConfirmService inside a lazy loaded Module. The dialog is not opening. I have to add the <p-confirmDialog> tag to the component to get it work. Without lazy loading the service uses the tag inside app.component.html and the dialog is opening. I'm also using ToastModule exact same way, and it is working. 

I created a stackblitz, but it is working because lazy loading is not working in stackblitz. 

### Environment

see stackblitz

### Reproducer

https://stackblitz.com/edit/github-yotq7n?file=README.md

### Angular version

15.2.8

### PrimeNG version

15.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.13.0

**Comment by jeremylcarter** [comment]
I have seen this issue before too. I think it has something to do with the lazy module having its own scope.

**Comment by KevinHetzelGFL** [comment]
> static forRoot(): ModuleWithProviders<SharedModule> {
>     return {
>       ngModule: SharedModule,
>       providers: [ConfirmationService, MessageService, DialogService]
>     }
>   }

Did you get it work this way? I tryed it but i still have to add the confirmDialog tag to every Module.

**Comment by jeremylcarter** [comment]
Do you key your dialog tag? I have just 1 dialog tag in my layout component
and use this method to get lazy modules to use the same single keyed dialog
tag

**Comment by KevinHetzelGFL** [comment]
I checked again every module and every library. One shared library inside my project also provided the ConfirmationService. I removed it, now it is working. 
I don't need your foorRoot() method. It is working if you provide the service inside app.module.

**Comment by BenRacicot** [comment]
This may be related to shared services. I cannot get shared services working as expected when shared between standalone components from their router. The service instances are separated.

Would appreciate any confirmation of this problem or perhaps fixes.

**Comment by Tucaen** [comment]
Services provided by a component are also not shared and I couldn't find a way to force them to, yet

Example:
ComponentA  - provides Service
   ComponentB - opens Dialog
   
 Dialog 
   Component B - no provider for Service error
