### ISSUE TITLE
p-dropdown: undesired behavior when adding tabindex attribute

### ISSUE THREAD

**Issue by Picoquio** [primefaces/primeng#12992]
### Describe the bug

Hello there. I found this issue with the primeng's p-drodown.

Whenever I set the `tabindex` attribute in the `p-dropdown` tag, I need to press the tab key twice in order to navigate through such component. While inspecting the HTML, I think I found the cause of the problem: there are two tags with a `tabindex` attribute: 

1. The `p-dropdown` tag
2. The `input` tag nested below

![pdropdown](https://user-images.githubusercontent.com/84530694/236205914-a295e877-71b3-4f89-86fc-09cf867f908d.gif)

Testing in chrome developer tools, I tried deleting the upper `tabindex` attribute (the one present in the `p-dropdown` tag) and the issue seemed to get fixed.

***Note**: it's also happening with the `p-inputNumber` tag. Not sure how far this goes, how extense might be the list of components affected by this issue. 

### Environment

Not sure what I should put here. The error was detected in a development environment. It can be reproduced in the stackblitz link provided

### Reproducer

https://stackblitz.com/edit/github-katpta?file=src/app/app.component.html

### Angular version

14.1.3

### PrimeNG version

14.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.17.0

### Steps to reproduce the behavior

1. Open stackblitz link
2. Click on the first p-dropdown
3. Press tab key to navigate

### Expected behavior

One should only press the tab key once in order to navigate through p-dropdowns and similar affected components.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
