### ISSUE TITLE
Calendar: No longer aligns to fit viewport if it overflows

### ISSUE THREAD

**Issue by arthur-alvesaf** [primefaces/primeng#13008]
### Describe the bug

A bug was introduced in the commit: https://github.com/primefaces/primeng/commit/7633038b5c1ca76f91bf86ac2c5719b5b28c63d4

And since then (the last 6 months) every new version has carried this bug where the calendar is no longer able to align to fit within the viewport, but rather is allowed to overflow outside of the screen making interacting with it impossible.

### Environment

You don't even need to pull the project, just go to the documentation to view the bug. Follow the steps below to reproduce.

Ironically, since the update to the look of the documentation since version 15, this is only able to be seen in the documentation of version 14, but I assure you it's present in all versions >= 14.2.0.

### Angular version

14.3.0

### PrimeNG version

14.2.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.19.0

### Browser(s)

All of them

### Steps to reproduce the behavior

1. Go to the documentation of PrimeNG at: https://www.primefaces.org/primeng-v14-lts/calendar

2. Make the screen width 1000px

3. Click on the 'Icon' type calendar

4. Note parts of it are inaccessible and overflowing outside the viewport

### Expected behavior

Like in versions before PrimeNG 14.2.x, where the calendar would align to fit within the screen. You can follow the same steps as before but in the PrimeNG 13 documentation to see: https://www.primefaces.org/primeng-v13-lts/#/calendar

**Comment by arthur-alvesaf** [comment]
The above PR should fix the issue in just one line. I hope this can be resolved soon because it is affecting my project and my customers. 

Also, if I may request it, can this go in the next patch version for all major versions since v14? My project uses 14.2.3 and we are not quite ready to upgrade to a newer major version yet. Please and thank you :)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
