### ISSUE TITLE
Unit Test: Compilation Failed

### ISSUE THREAD

**Issue by vinnyab28** [primefaces/primeng#13006]
### Describe the bug

When trying to run `npm run test`, we have the following compilation errors:

`Error: src/app/showcase/layout/footer/app.footer.component.ts:16:42 - error TS2591: Cannot find name 'require'. Do you need to install type definitions for node? Try 'npm i --save-dev @types/node' and then add 'node' to the types field in your tsconfig.`

`16     version = require('package.json') && require('package.json').version;`

`Error: src/app/showcase/layout/topbar/app.topbar.component.ts:73:23 - error TS2591: Cannot find name 'process'. Do you need to install type definitions for node? Try 'npm i --save-dev @types/node' and then add 'node' to the types field in your tsconfig.`
`73         const valid = process.env.NODE_ENV !== 'production';`

### Environment

Angular CLI: 15.2.7
Node: 16.17.1
Package Manager: npm 9.1.1
OS: win32 x64

Angular: 15.2.8
... animations, cdk, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.7
@angular-devkit/build-angular   15.2.7
@angular-devkit/core            15.2.7
@angular-devkit/schematics      15.2.7
@angular/cli                    15.2.7
@nguniversal/builders           15.2.1
@nguniversal/common             15.2.1
@nguniversal/express-engine     15.2.1
@schematics/angular             15.2.7
ng-packagr                      15.2.2
rxjs                            7.8.1
typescript                      4.8.4

### Angular version

15.2.8

### PrimeNG version

15.4.2-SNAPSHOT

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.17.1

### Steps to reproduce the behavior

1. Run `npm run test`

### Expected behavior

Run the test cases.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
