### ISSUE TITLE
p-password: attribute 'className' instead of 'class' used in content template

### ISSUE THREAD

**Issue by Ursuss21** [primefaces/primeng#13003]
### Describe the bug

Hello. I've been working on customizing the p-password component in one of my projects. When I attempted to style out the p-password-info class, I haven't received any results. I thought that maybe there was a specificity issue, but nothing helped, even using !important temporarily. I've looked into the codebase, and found out the line I wanted to check:

`<div className="p-password-info">{{ infoText }}</div>`

As you can see, class name 'p-password-info' is applied to the attribute 'className', which, I believe, doesn't work and doesn't apply styles. I guess the solution would be to just replace it with:

`<div class="p-password-info">{{ infoText }}</div>`

Should I make a PR regarding this issue? I know it's small and it's not something super important, but it could be useful to have the ability to customize the text for someone.

### Environment

Ubuntu 20.04

### Angular version

15.2.6

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.20.0

**Comment by volvachev** [comment]
Hello, I opened pr.  at the moment you can style through the [attribute](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors)
