### ISSUE TITLE
AutoComplete control inappropriately fires onClear event when selecting an item with the mouse (correctly doesn't when using the keyboard)

### ISSUE THREAD

**Issue by AlejandroFlorin** [primefaces/primeng#13007]
### Describe the bug

In the autocomplete control, if you use the keyboard (down arrow and enter key) to select an item, the control triggers only the onSelect event as expected.

However, if you use the mouse to select an item, the control triggers the onClear event prior to triggering the onSelect event.

This is an issue because I have handlers for both the onClear and onSelect events which both make calls to a server api. It then becomes a race situation between the onClear event and the onSelect event when the user clicks on an option (as opposed to using the keyboard to select an option). There is also no way to know from the onClear event if it was triggered by the selection of an item (so I can not do the call) or by an actual clearing of the control, other than setting a state variable in the onSelect event and using a timeout on the onClear event to check the variable before making its call.

### Environment

Dev Machine:
  Windows 11
  Visual Studio 2019

### Angular version

15.2.8

### PrimeNG version

15.4.1

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Steps to reproduce the behavior

Add an Autocomplete control to a component. The properties I'm using are:
                  <p-autoComplete
                                    formControlName="recruiter"
                                    [suggestions]="availableRecruiters"
                                    field="fullName"
                                    dataKey="id"
                                    [forceSelection]="true"
                                    (onClear)="onRecruiterClear()"
                                    (onSelect)="onRecruiterChange()"
                                    (completeMethod)="onRecruiterSearch($event)">
                    </p-autoComplete>

Assign an array of values to the control's suggestions object
Search for an item
Use keyboard (down arrow and enter) to select an item (control triggers the onSelect event only: expected)
Search for the same item
With mouse, click on one of the displayed items (control triggers the onClear event as well as the onSelect event: not expected)

### Expected behavior

The onClear event should not be triggered when selecting an item, regardless of the method used to select the item.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
