### ISSUE TITLE
Calendar: working with ISO date strings (from DB) using [(ngModel)]

### ISSUE THREAD

**Issue by slyk** [primefaces/primeng#13018]
### Describe the feature you would like to see added

**Let p-calendar handle ISO date strings.**

Entity loaded from server, and need to simply get some updates from user (forms) and save this entity back. So the simplest and fast way is to get object by json and parse it (from DB we receive **dates as ISO date strings**). Then associate properties of that entity to input fields using `<p-calendar [(ngModel)]="entity.date"></p-calendar>`.

So expected behavior of calendar component  would be to get ISO string and display it. An onSelect output the value in same format, so we can simply send that entity to server.

### Is your feature request related to a problem?

Right now we have a problem:
- if component get ISO date string it just don't recognize it and display nothing;
- also after selecting date  the output format is a Date or string (but not in ISO format)
So we have to add additional code to pre-view and pre-save data.

This is common task because many DB have DATETIME format cells and for js/ts using json is common wayt so send data, where the types are lost. So to remove  boilerplate better to put ability to work with **ISO string dates** to component.

### Describe the solution you'd like

We already have dataType="string", but it is NOT capable to handle input in ISO string. So without any external changes I guess component itself can:

1.  check the input value and if its **ISO** string - parse it to date for internal use 
2.  return as **ISO** string _(if the input was in that format)_

**Comment by villegasrfael** [comment]
This is a bug that comes and goes between versions, 90% of the backends return dates as ISO Date String, it is ridiculous that dates have to be converted from ISO string to date before consuming PrimeNg components, and then back to ISO date string before sending to backend. This happens with almost all components that use dates.
Please make components able to consume Date() and/or ISO Date string indistinctly. 🙏

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
