### ISSUE TITLE
Table: dynamic pReorderableColumnDisabled

### ISSUE THREAD

**Issue by megafinz** [primefaces/primeng#13017]
### Describe the feature you would like to see added

I have a `p-table` with freezable and reorderable columns. I would like to implement a way to dynamically toggle freezable columns. Frozen columns should not be reorderable.

### Is your feature request related to a problem?

Using `[frozen]=isColumnFrozen(column)` attr on a column seems to work fine in the freezability department, I can change the frozen status dynamically. 

The problem I have is that it looks like I'm not able to change the reorderability of the column dynamically (by using `[pReorderableColumnDisabled]=isColumnFrozen(column)` attr). If column's reorderability is disabled when the table loads, I can't enable it later, and vice-versa.

### Describe the solution you'd like

Would be nice if I could change the value of `pReorderableColumnDisabled` attr at any point in time and that would enable/disable column reorderability respectively.

### Additional context

Looking at [the code](https://github.com/primefaces/primeng/blob/1d30a243e274d12ca28a51444e86e1a651f7c618/src/app/components/table/table.ts#LL3451C5-L3455C6) it seems that event handlers for the column are initialized once in `ngAfterViewInit`. Maybe event handlers should check the value of `pReorderableColumnDisabled`?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
