### ISSUE TITLE
Chips: After clicking the clear button does not allow to input values

### ISSUE THREAD

**Issue by avytak** [primefaces/primeng#13011]
### Describe the bug

When we set the max and showClear attributes for the p-chips:
`<p-chips [addOnBlur]="true" [showClear]="true" [max]="5"></p-chips>
`
After that type the max possible values (in that case 5) and press the clear button, the input is still disabled.

### Environment

Windows 10

### Reproducer

https://stackblitz.com/edit/primeng-chips-maxitems-bug?file=src%2Fapp%2Fapp.component.html

### Angular version

14.2.0

### PrimeNG version

14.2.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Browser(s)

Chrome 113.0.5672.92

### Steps to reproduce the behavior

1. Go to chips input.
2. Enter any 5 values.
3. Click the clear icon.
4. Try to enter any value after that.
5. Observe

### Expected behavior

After the clicking clear button I should be able to write the value again.
A possible reason could be that `clear` method does not have ` updateMaxedOut method`:

`    clear() {
        this.value = null;
        this.updateFilledState();
        this.onModelChange(this.value);
        this.onClear.emit();
    }`

**Comment by avytak** [comment]
One more thing that I found is that when we have `[addOnBlur]="true"` and typed the last allowed item and press the "Enter" - it duplicate it in the input field, so we have 6 items rather than 5. You can reproduce it in the same stackblitz code example. Is this the right behavior?

**Comment by irekBudzowski** [comment]
> One more thing that I found is that when we have `[addOnBlur]="true"` and typed the last allowed item and press the "Enter" - it duplicate it in the input field, so we have 6 items rather than 5. You can reproduce it in the same stackblitz code example. Is this the right behavior?

@avytak you are right. 
As a team workaround, if your business case accepts it, you might set `[allowDuplicate]=false` so focusOut won't duplicate the last element.
