### ISSUE TITLE
Menubar | ReferenceError: Cannot access 'Menubar' before initialization

### ISSUE THREAD

**Issue by VallarasuS** [primefaces/primeng#13024]
**Description**

Existing tests fail with the following error

ReferenceError: Cannot access 'Menubar' before initialization

```
import { MenubarModule } from 'primeng/menubar';

```

**Environment**
Windows Jest tests

**Angular Version**
15.2.3

**Primeng Version**
15.4.0

**Build / Runtime**
Angular CLI App

**Language**
TypeScript

**Steps to Reproduce**
1. import { MenubarModule } from 'primeng/menubar';
2. run npm test

**Expected behavior**
Exoect the tests to run without the error in subject.

**Comment by AndreasHae** [comment]
I have the same issue after upgrading to Primeng 15.4.1 and Angular 15.2.9. The application builds and runs fine, but when executing tests via Jest, I get hit with `ReferenceError: Cannot access 'Menubar' before initialization`.

**Comment by 213edu** [comment]
+1 on `15.4.1`

**Comment by bendehghan** [comment]
Another one for splitbutton https://github.com/primefaces/primeng/issues/12945

**Comment by bcandullo** [comment]
This is still an issue in `16.0.0-rc.1` and `16.0.0-rc.2`.

**Comment by cetincakiroglu** [comment]
Thanks for reporting, we're investigating the issue.

**Comment by Thomas-Schindler** [comment]
Hi,
we have the same problem here. We want to migrate from Angular 14 to Angular 15 using PrimeNG 15.4.0. When we try to run our unit tests with jest  (version ^28.0.0), whe get the error message on each test of an Angular component referencing a PrimeNG component. 

`Test suite failed to run

    ReferenceError: Cannot access 'PanelMenu' before initialization

      10 | import { SelectButtonModule } from 'primeng/selectbutton';
      11 | import { BreadcrumbModule } from 'primeng/breadcrumb';
      12 | import { PanelMenuModule } from 'primeng/panelmenu';
`
Downgrading to PrimeNG 15.3.0 fixed the problem. But of course would we like to use ^15.4.1 in the future. Is there any chance to get a fix in 15.4.x?

**Comment by Thomas-Schindler** [comment]
Hello,

we have experienced the same problem when migrating from Angular 14 and PrimeNG 14 to Angular 15.2.9 and PrimeNG 15.4.1. A workaround for us is to use PrimeNG 15.3.0. But of course we would like to get also the fixes and enhancements made ein 15.4.x. Is there a change that a fix is available also for 15.4.x?

**Comment by HMubaireek** [comment]
The issue still appears in 16.0.2

**Comment by psarno** [comment]
I am attempting to create a repro for another issue in StackBlitz but am getting the following:

> Error in /turbo_modules/primeng@16.1.0/fesm2022/primeng-contextmenu.mjs (144:254)
> Cannot access 'ContextMenu' before initialization

I am tryng to update the repro template to use the latest PrimeNG (16.1.0) but it won't render my `<p-menubar>` component after updating the template from 14 -> 16.1.

I'm not dealing with a context menu at all.

**Comment by umuero** [comment]
The issue spread to ContextMenuModule with commit #f4f3598

constructor(@Inject(forwardRef(() => ContextMenu)) contextMenu: ContextMenu)
was working 

constructor(...., public contextMenu: ContextMenu)
fails

**Comment by cetincakiroglu** [comment]
Hi,

We're currently working on accessibility and in this process, we are refactoring & reworking all of the components, because of that all tests need to be refactored afterwards. I'm moving this issue to 16.Future milestone and after we finalize accessibility implementation we'll take this issue into consideration while we fixing the tests.

**Comment by Torquin** [comment]
Hi @cetincakiroglu, 
Any ETA for these updates. Got it working by modifying frontend/node_modules/primeng/fesm2022/primeng-tieredmenu.mjs but this is obviously not the correct way to go.

Thanks

**Comment by psarno** [comment]
I still am having trouble trying to get a Stackblitz up and running for version 16.

All of the dependencies are where they should be, but the error I am seeing now is:

> Error in /turbo_modules/primeng@16.3.1/fesm2022/primeng-tieredmenu.mjs (137:252)

> Cannot access 'TieredMenu' before initialization

No menus are being used ... in fact the template is completely empty.

The call stack seems to originate in primeng-splitbutton.mjs before failing in tieredmenu.mjs?

> Unhandled Promise rejection:
> Cannot access 'TieredMenu' before initialization
> Error: Cannot access 'TieredMenu' before initialization
> ReferenceError: Cannot access 'TieredMenu' before initialization
> at Object.eval (primeng-tieredmenu.mjs:137:252)
> at eval (primeng-tieredmenu.mjs:1219:4)
> at eval (primeng-tieredmenu.mjs:1220:3)
> at Object.eval (primeng-splitbutton.mjs:35:25)
> at eval (primeng-splitbutton.mjs:251:4)

**Comment by livanov** [comment]
Still having issues with PanelMenu in Angular 16, primeng 16.9

**Comment by pdemro** [comment]
+1 for 15.4.0 :( .  Downgrading to 15.3.0 solves the issue

p.s. thanks for the great library ♥️
