### ISSUE TITLE
Component: Speed dial component

### ISSUE THREAD

**Issue by jacob-hougaard** [primefaces/primeng#13027]
### Describe the feature you would like to see added

I would be nice to be able to use other icons on the speed dial in primeng, for example through a template. 
An example could be: 

```html
<p-speedDial [model]="items" direction="up" [radius]="80" type="semi-circle">
      <ng-template pTemplate="icon">
          <svg src='path/to/icon.svg'/>
      <ng-template>
</p-speedDial>
```

### Is your feature request related to a problem?

Yes. The problem is that our application is not using primeng's icon pack, but is instead using static svg files for this use case.

### Describe the solution you'd like

Some way to either have a template to set the icon, or be able to add html directly into the icon attribute of the MenuModel.

### Describe alternatives you have considered

We have tried adding the images as background for the buttons in the speed dial after initialisation, using the button template on the speed dial.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
