### ISSUE TITLE
Component: OverlayComponent orientation relative to target

### ISSUE THREAD

**Issue by nicholasirsyad** [primefaces/primeng#13025]
### Describe the feature you would like to see added

I have a requirement from my client to display the overlay panel above the target element with the arrow pointing downwards. I have looked everywhere to see if there's an option from primeNG to do this, but there isn't. 

I've looked into customising the CSS myself, but found that the p-overlaypanel that's opened has an inline style with exact top and left values, which makes it hard to adjust. It seems that the component actually calculates the target's coordinates and place the overlay panel in an exact coordinate with an absolute positioning. 

This is with primeNG v16.0.0, as per latest docs on the website. 

### Describe the solution you'd like

As mentioned by many others, I wish that the OverlayComponent has an [orientation] attribute which accepts: "top" | "left" | "right" | "bottom" 

So when the user specifies "top" the resulting panel will appear on top of the target with the arrow pointing downwards, and if "left" is specified, the panel should appear on the left side of the target with the arrow pointing right towards the target element.

**Comment by Michael-Ziluck** [comment]
This is effectively a recreation of issue #2567 which was closed without being resolved. It had 45 likes and is a much needed and desired feature.

For convenience, I'm going to paste the body of that issue here:

> [x] feature request
> 
> Looking for a way to align the overlay panel, by default it aligns the top and left edge to its parent element, but it would be nice to have other ways to align it.
> 
> For example:
> 
> top-left
> top-center
> top-right
> bottom-left
> bottom-center
> bottom-right
> right-top
> right-center
> right-bottom
> left-top
> left-center
> left-bottom

**Comment by angeladeliz** [comment]
Any update on this implementation?

**Comment by Joebeurg** [comment]
Over 7 years...

**Comment by CronGM** [comment]
I remember back in 2019 a customer (and the agency I worked in) desired this feature. I wanted to contribute to the project but they didn't want to allocate time and budget to work on "an open source project not related to the client". I can't believe it's been five years since then and this feature hasn't been implemented. Even back then I saw a couple of PRs from people who wanted to contribute to PrimeNG.

I guess there must not be that much interest in the feature to be taken seriously. 🤷🏻‍♂️

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
