### ISSUE TITLE
ConfirmDialog: Accept Icon is duplicated

### ISSUE THREAD

**Issue by denny99** [primefaces/primeng#13022]
### Describe the bug

Well pretty simple: 

Heres the buggy code piece https://github.com/primefaces/primeng/blob/ac054f92f9c45be9709d2b0351e4ce0b5d1e430b/src/app/components/confirmdialog/confirmdialog.ts#L96:

```html
<button
                        type="button"
                        pRipple
                        pButton
                        [icon]="option('acceptIcon')"
                        [label]="acceptButtonLabel"
                        (click)="accept()"
                        [ngClass]="'p-confirm-dialog-accept'"
                        [class]="option('acceptButtonStyleClass')"
                        *ngIf="option('acceptVisible')"
                        [attr.aria-label]="acceptAriaLabel"
                    >
                        <ng-container *ngIf="!acceptIconTemplate">
                            <i *ngIf="option('acceptIcon')" [class]="option('acceptIcon')"></i>
                            <CheckIcon *ngIf="!option('acceptIcon')" [styleClass]="'p-button-icon-left'"/>
                        </ng-container>
                        <span *ngIf="acceptIconTemplate" class="p-button-icon-left">
                            <ng-template *ngTemplateOutlet="acceptIconTemplate"></ng-template>
                        </span>
                    </button>
```

As you can see with the addition of icon template, the icon is now duplicated. With the new i element and also with the icon attribute on the button itself. Thats not the case for the reject button.

### Environment

Angular with Nest Backend on MacOS

### Angular version

15.x

### PrimeNG version

15.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.x

### Expected behavior

Just remove the single line

**Comment by cetincakiroglu** [comment]
Hi @denny99 ,

Thanks for reporting the issue, it seems the issue has already been fixed between 15.4.2-16.0.0-rc.2.
Closing the issue.
