### ISSUE TITLE
PickList: Add support of range selection

### ISSUE THREAD

**Issue by afroz1989** [primefaces/primeng#13029]
### Describe the feature you would like to see added

Add support of range selection by holding the metakey. Example, select a range by clicking the first one holding Shift or Ctrl and clicking the last one

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
