### ISSUE TITLE
Component: Label of dropdown when filtering lazyload table

### ISSUE THREAD

**Issue by dbraun19** [primefaces/primeng#13021]
### Describe the bug

We are experincing issues when filtering our p-table with dropdowns. The table is displaying 50 entries at once. After scrolling through the first 50 entries the next 50 are loaded. 
When filtering with dropdowns, the filtering works correctly. However the optionLabel is not displayed but the placeholder.
The error only occurs when the table has more than 50 entries and less than 50 entries remain after filtering.

`<p-table
        #tabellePostkorbVorgaenge
        id="tabellePostkorbVorgaenge"
        [scrollable]="true" [rows]="50"
        [virtualScroll]="vorgaenge.length > 50" [virtualScrollItemSize]="51" scrollHeight="flex"
        [value]="vorgaenge" [columns]="sichtbareSpalten"
        [resizableColumns]="true" [reorderableColumns]="true" columnResizeMode="expand"
        [loading]="loading"
        [lazy]="true" (onLazyLoad)="ladeVorgaengeLazy($event)"
        (onColResize)="spaltenBreiteGeaendert($event)"
        (onColReorder)="spaltenReihenfolgeGeaendert($event)"
        sortMode="single" sortField="eingangsdatum" [sortOrder]="1"
        [rowHover]="true"
        styleClass="p-datatable-gridlines p-datatable-striped p-datatable-sm suche__ergebnistabelle"
    >`

` <ng-container *ngIf="col.field === 'prioritaet'">
              <p-columnFilter [field]="col.field" matchMode="equals" [showMenu]="false"
                              [showClearButton]="false"
                              id="vorgangsListeFilter_prioritaet">
                <ng-template pTemplate="filter" let-value let-filter="filterCallback">
                  <div id="vorgangsListeFilter_prioritaet_dropdown_container">
                    <p-dropdown id="vorgangsListeFilter_prioritaet_dropdown"
                                inputId="vorgangsListeFilter_prioritaet_dropdown_input"
                                #prioritaetDropdown styleClass="karma-form-control"
                                [options]="prioritaetSelectItems" [showClear]="true"
                                placeholder="Auswählen" [virtualScroll]="false"
                                (onChange)="filter($event.value)" appendTo="body"
                                [panelStyle]="{ 'maxHeight': '95px' }">
                      <ng-template let-option pTemplate="item">
                        <div id="vorgangsListeFilter_prioritaet_item_container">
                          <span
                              id="vorgangsListeFilter_prioritaet_dropDown_{{option.label}}">{{option.label}}</span>
                        </div>
                      </ng-template>
                    </p-dropdown>
                  </div>
                </ng-template>
              </p-columnFilter>
            </ng-container>`

### Environment

Before label of filter value is set:
![image](https://github.com/primefaces/primeng/assets/93702994/ab226b18-2946-4ff9-9b03-949fb28140e1)

After label of filter value is set:
![image](https://github.com/primefaces/primeng/assets/93702994/0d592e20-bf1f-454d-8f3b-93f552c6f964)

### Angular version

15.2.2

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.2.0

### Browser(s)

Chrome 112

**Comment by volvachev** [comment]
Hi, can you create example on stackblitz?

**Comment by dbraun19** [comment]
Hi, unfortunately I can't get the code to run on stackblitz. It throws the error: Type 'Event' has no properties in common with type 'LazyLoadEvent'.

**Comment by dbraun19** [comment]
I fixed with setting the virutalScroll property of the p-table to true, instead of  [virtualScroll]="vorgaenge.length > 50" [virtualScrollItemSize]="51"
