### ISSUE TITLE
Component controls trigger icon 'font-weight' and 'font-size' no longer can be changed

### ISSUE THREAD

**Issue by DarienF** [primefaces/primeng#13037]
### Describe the bug

I figured in 16.0.0-rc.1 some component controls has implemented 'chevrondownicon'/'calendaricon'/etc. components for rendering trigger icon with `<svg>` inside. I think usage `<svg>` is a bad idea because:
1. Not all component has `<svg>` for rendering icons inside (for example `<p-inputnumber>` with plus/minus icons on left/right  `buttonlayout="horizontal"` has buttons with `<span>` inside). How do you plan to maintain unification???
2.  I was able to change `font-weight` and `font-size` very simple when it was `<span>` or `<i>` with `pi` class (`class="pi pi-plus"`) by add simple styling for it. Now it become a problem.

### Environment

"primeflex": "^3.3.0",
"primeicons": "^6.0.1",
"primeng": "^16.0.0-rc.1",

"typescript": "~5.0.2"

### Angular version

16.0.1

### PrimeNG version

16.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v18.14.0

### Expected behavior

Might be worth leaving `<span>` or `<i>` with `pi` class?)

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
