### ISSUE TITLE
p-confirmPopup errors when setTimeout runs after onContainerDestroy

### ISSUE THREAD

**Issue by jacks-bush** [primefaces/primeng#13034]
### Describe the bug

In the p-confirmPopup, there are a few listeners that get set up in a setTimeout that gets called when the popup is first opened. If, for some reason, that setTimeout does not get called before the popup is closed, which sets `this.confirmation = null` on the component, the component throws a bunch of errors in places where it is expecting `this.confirmation` to be defined. 

The most common case we are seeing in our app is that `this.confirmation` is null when `bindScrollListener()` is called from the setTimeout.

### Environment

Versions below.

### Angular version

14.2.5

### PrimeNG version

14.1.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14.0

### Browser(s)

Chrome and Firefox, didn't test the others

### Steps to reproduce the behavior

I was unable to reproduce this in a stackblitz, but I can reproduce in our app consistently. What happens is as follows:

1. User resizes a chart which causes it to redraw. 
2. User clicks on another chart, hits delete and the confirm popup comes up.
3. User hits enter and the confirm popup disappears.
4. When the first chart finishes redrawing, an error is thrown in `bindScrollListener()` in the confirm popup component, because `this.confirmation` is null.

**Comment by jacks-bush** [comment]
@cetincakiroglu,

When I updated our application to use the 16.0.1 release that included the #13035 pull request, I found another issue that was not happening when I first tested my fixes locally. 
I made a new pull request #13756 to fix the new error. Since it's the same underlying issue I just kept this bug report. Let me know if I should make a new one instead!

**Comment by cetincakiroglu** [comment]
Hi @jacks-bush,

Could you please open an issue for that too so I can add it to the milestone

**Comment by jacks-bush** [comment]
@cetincakiroglu,
I made #13761 and linked it to the new pull request and this issue.
