### ISSUE TITLE
p-dropdown cannot be clickable in test cafe

### ISSUE THREAD

**Issue by valin1o** [primefaces/primeng#13033]
### Describe the bug

I'm running some test on my Angular application and for some reason, I'm using a p-dropdown with a template which has ids for the dropdown itself and the list items inside of it. Either way, when trying to select the dropdown and click it, it doesn't get clicked. The .hover(element-id) works but the .click(element-id) doesn't.

### Environment

Angular version and primeng stated below.
Running on windows 11, Chrome version stated below.

### Angular version

14.3.0

### PrimeNG version

14.2.11

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.15.0

### Browser(s)

Chrome 113.0.0.0

### Steps to reproduce the behavior

1. Create a selector of the component.
2. Use that selector and put it inside a .hover
3. .hover works, the next step is to .click the p-dropdown
4. .click doesn't work, test fails.

### Expected behavior

Expected to be clickable.

**Comment by biswasSaumyadip** [comment]
Could you provide a Stackblitz link?

**Comment by valin1o** [comment]
It's part of a larger code, I think I can give you a short example but that would be how an atomated test is configured in test cafe. But yeah, I will try to give you an example of a code.

**Comment by valin1o** [comment]
> Could you provide a Stackblitz link?

It's part of a larger code, I think I can give you a short example but that would be how an atomated test is configured in test cafe. But yeah, I will try to give you an example of a code.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
