### ISSUE TITLE
SelectButton: support deselect / unselect / clear of selected option in single select case

### ISSUE THREAD

**Issue by teetotum** [primefaces/primeng#13048]
### Describe the feature you would like to see added

A `p-selectButton` that is single-select can never be completely un-selected again, to bring it back to its initial state.
(The multi-select case does support this.)

### Is your feature request related to a problem?

We need this in our application and currently use a hacky workaround involving a callback for `onOptionClick`

```
<p-selectButton
      [formControlName]="id"
      [options]="options"
      [multiple]="false"
      (onOptionClick)="unselectIfSelected($event, id)"
><p-selectButton>
```

```
unselectIfSelected(event: any, id: string) {
    const target = event.originalEvent.target as HTMLElement;
    const isSelected = (elem: HTMLElement | null): boolean => elem?.classList.contains('p-highlight') || false;
    if (isSelected(target) || isSelected(target.parentElement)) {
      this.form.get(id)?.reset();
    }
}
```

**Comment by Adrii77** [comment]
This issue should be closed, as SplitButton now contains an inpunt "allowEmpty" which is handle this case.

"allowEmpty" seems to not appeared inside the primeng documentation, but the input exists and works.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
