### ISSUE TITLE
Building from source webpack -> Implement in local project?

### ISSUE THREAD

**Issue by TekSiDoT** [primefaces/primeng#1304]
Building from source using `npm run build-dev' results in 70 #.js chunk files plus the vendor/polyfill/application files.

I think the wiki should continue to explain how these files can be used in a local dev environment to verify the function of new additions / changes.

**Comment by qjlee** [comment]
check here https://github.com/primefaces/primeng/issues/2301

**Comment by TekSiDoT** [comment]
Great find, thanks! I'll leave the issue open as a reminder to update the developer docs for now.

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
