### ISSUE TITLE
Table: Virtual scroll Lazy loading don't load first elements when scrolled from bottom to top

### ISSUE THREAD

**Issue by ayazenok** [primefaces/primeng#13049]
### Describe the bug

We got this implementation(on 13.3.2 works good) There is no event fires when we scroll to top, (also got same behaviour like in https://github.com/primefaces/primeng/issues/12830), and we do not get first rows to display(like it was from start).

![Screenshot_2](https://github.com/primefaces/primeng/assets/73278147/3bea4f56-a2ef-4f3c-a153-da5bb395e070)
![Screenshot_3](https://github.com/primefaces/primeng/assets/73278147/fa273d0c-c968-4042-9b8b-c51e54d2646e)
![Screenshot_5](https://github.com/primefaces/primeng/assets/73278147/bfc815ac-db16-4ef8-b9f9-73527ce33c34)

### Environment

PrimeNG 15.2.0 and Angular 15.

### Angular version

15.2.2

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Steps to reproduce the behavior

https://github.com/primefaces/primeng/assets/73278147/cfa1c4e0-7461-43cd-b708-21ebc3868cc4

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
