### ISSUE TITLE
Component: RadioButton

### ISSUE THREAD

**Issue by martin-bernard00** [primefaces/primeng#13046]
When tabbing, it does not tab through each radio button. On the initial tab, it focuses on the first radio button, and on the next tab, it skips all other radio buttons and focuses on the next non-radio button item. And, when you shift-tab, it return focus to the last radio button in the group.

To recreate:
1. Go to https://primeng.org/radiobutton
2. Click the Group radio button example
3. Begin tabbing

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
