### ISSUE TITLE
OverlayPanel and ConfirmPopup: Styling occasionally broken

### ISSUE THREAD

**Issue by LexanRed** [primefaces/primeng#13045]
### Describe the bug

When using the OverlayPanel or the ConfirmPopup via the ConfirmationService the styling breaks from time to time.

It should look like this:
<img width="284" alt="Screenshot 2023-05-15 at 19 27 31" src="https://github.com/primefaces/primeng/assets/57357219/3b5634d3-60d7-454e-ab08-b13da602b7c4">
<img width="197" alt="Screenshot 2023-05-15 at 19 38 41" src="https://github.com/primefaces/primeng/assets/57357219/f6a540c5-4840-4b89-ab09-7da88e596ac7">

Sometimes it rather looks like this:
<img width="316" alt="Screenshot 2023-05-15 at 19 27 20" src="https://github.com/primefaces/primeng/assets/57357219/4838e741-d7a3-4d28-abfe-9b6dd058ca05">
<img width="225" alt="Screenshot 2023-05-15 at 19 38 34" src="https://github.com/primefaces/primeng/assets/57357219/86903713-f8ef-46c7-aa24-577c41539a06">

I can open the same popup or overlayPanel several times on the same page with different outcomes. 
Sometimes it works three times in a row, sometimes i only get the faulty outcome with the arrow moved outside of the box. 
I was unable to detect any pattern here. 

### Environment

PrimeNg with Apollo layout 

### Angular version

16.0.1

### PrimeNG version

16.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Browser(s)

Safari, Chrome, Firefox

**Comment by pourquoi** [comment]
same issue with primeng 16.0.0
