### ISSUE TITLE
Component: Table

### ISSUE THREAD

**Issue by GanjaGanja** [primefaces/primeng#13043]
### Describe the bug

**reorderableRows** property is missing in **Table** component. This property is mentioned in documentation for the component: https://primeng.org/table#reorder

### Environment

PrimeNG version 16.0.0-rc.1

### Angular version

15.2.5

### PrimeNG version

16.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.15.0

### Expected behavior

**reorderableRows** property for Table component shouldn't be mentioned in documentation https://primeng.org/table#reorder

**Comment by spulido-slingr** [comment]
Hi!, Any update on this? Need this feature to fully migrate to v16

**Comment by Nikos-Iosifidis** [comment]
Any plans to actually add this feature?
It would be useful to be able to enable/disable the reorder of rows.
