### ISSUE TITLE
Component: Title

### ISSUE THREAD

**Issue by vitosalvia** [primefaces/primeng#13051]
### Describe the bug

onRowSelect table not working if table is on modal

### Environment

PrimeNG v16.0.0

### Angular version

16.0.0

### PrimeNG version

16.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
