### ISSUE TITLE
Table: Global filtering on the table is not working as shown in the documentation.

### ISSUE THREAD

**Issue by Disura-Randunu** [primefaces/primeng#13052]
### Describe the bug

In the table component [docs](https://primeng.org/table#filter), it shows that global filtering on the table is possible as below.
`<input pInputText type="text"  (input)="dt.filterGlobal($event.target.value, 'contains')" placeholder="Search..." />`

However, it's not working and gives the following error:
`error TS2339: Property 'value' does not exist on type 'EventTarget'`

Is it a problem from my end or is it related to angular version or any other issue?

I also found the following workaround to make it work. But I'm not sure whether it's okay to use, even though it's working as expected.
`<input pInputText type="text"  (input)="dt.filterGlobal($any($event.target).value, 'contains')" placeholder="Search..." />`

### Environment

OS: Windows 10

Versions:
NPM: 9.5.0
NodeJS: 18.14.2
Angular: 15.2.8
PrimeNG: 15.4.1

### Angular version

15.2.8

### PrimeNG version

15.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.14.2

**Comment by sergiorodriguez82** [comment]
+1

**Comment by voronovmaksim** [comment]
+1

**Comment by pablosay** [comment]
> ### Describe the bug
> In the table component [docs](https://primeng.org/table#filter), it shows that global filtering on the table is possible as below. `<input pInputText type="text" (input)="dt.filterGlobal($event.target.value, 'contains')" placeholder="Search..." />`
> 
> However, it's not working and gives the following error: `error TS2339: Property 'value' does not exist on type 'EventTarget'`
> 
> Is it a problem from my end or is it related to angular version or any other issue?
> 
> I also found the following workaround to make it work. But I'm not sure whether it's okay to use, even though it's working as expected. `<input pInputText type="text" (input)="dt.filterGlobal($any($event.target).value, 'contains')" placeholder="Search..." />`
> 
> ### Environment
> OS: Windows 10
> 
> Versions: NPM: 9.5.0 NodeJS: 18.14.2 Angular: 15.2.8 PrimeNG: 15.4.1
> 
> ### Reproducer
> _No response_
> 
> ### Angular version
> 15.2.8
> 
> ### PrimeNG version
> 15.4.1
> 
> ### Build / Runtime
> Angular CLI App
> 
> ### Language
> TypeScript
> 
> ### Node version (for AoT issues node --version)
> 18.14.2
> 
> ### Browser(s)
> _No response_
> 
> ### Steps to reproduce the behavior
> _No response_
> 
> ### Expected behavior
> _No response_

It worked for me too!

**Comment by LuizTokuhara** [comment]
I am having the same issue.
Using Angular v16.1.0 and PrimeNG v16.6.0.

**Comment by dimd13** [comment]
+1
primeng v17.0.0
angular v17.0.0

**Comment by ECesco** [comment]
+1
primeng v17.0.0
angular v17.0.0

Seeing errors :

Object is possibly 'null'.ngtsc(2531)
Property 'value' does not exist on type 'EventTarget'.ngtsc(2339)

**Comment by zeydduran** [comment]
+1

**Comment by michsindlinger** [comment]
Use a function for filtering instead directly accessing the $event.target.value.
In the function you can cast the event target to an HTMLInputElement and access the value.

<input pInputText type="text" (input)="onGlobalFilter(dt1, $event)" placeholder="Search..." />

onGlobalFilter(table: Table, event: Event) {
    table.filterGlobal((event.target as HTMLInputElement).value, 'contains');
  }

**Comment by Hernan940504** [comment]
+1

**Comment by molinaangeldavid** [comment]
You saved my life man.
I was struggling this problem
+1

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
