### ISSUE TITLE
New feature: Table excel view request

### ISSUE THREAD

**Issue by yuvarajProl** [primefaces/primeng#13057]
Dear Team,

**Subject:** New feature request.

We require a data table display, just as Excel. Is it possible to change many cells with the same value at once using drag-and-drop operations in the table Excel view feature?
We are willing to purchase this feature or pay for support. Would you please give us the best solution to this?

Thanks & Regards,
Yuvaraj.K

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
