### ISSUE TITLE
DataTable Column Reorder Throws Error in IE and Edge

### ISSUE THREAD

**Issue by mariahlynne** [primefaces/primeng#1305]
When a datatable column is clicked and dragged (with `[reorderableColumns]="true"`), errors are thrown in both Internet Explorer 11 and Edge (but not in Chrome nor Firefox). The column can be successfully reordered, but other functionality becomes broken if this occurs. Specifically, once a column is reordered, its header does not update properly when sorting is toggled. Sorting still works, but the sort toggle icon and header styling does not change.

Here are the errors from IE:
~~~~
EXCEPTION: Error in ./DataTable class DataTable - inline template:16:65 caused by: Unexpected call to method or property access.
ORIGINAL EXCEPTION: Unexpected call to method or property access.
ORIGINAL STACKTRACE:
Error: Unexpected call to method or property access.
    at DataTable.prototype.onColumnDragStart (eval code:853:9)
    at _View_DataTable5.prototype._handle_dragstart_0_3 (Function code:801:3)
    at Anonymous function (eval code:9437:21)
    at Anonymous function (eval code:1525:13)
    at Anonymous function (eval code:1638:108)
    at ZoneDelegate.prototype.invoke (eval code:230:13)
    at onInvoke (eval code:6206:25)
    at ZoneDelegate.prototype.invoke (eval code:230:13)
    at Zone.prototype.runGuarded (eval code:128:21)
    at NgZone.prototype.runGuarded (eval code:6101:55)
    at outsideHandler (eval code:1638:71)
    at ZoneDelegate.prototype.invokeTask (eval code:263:17)
    at Zone.prototype.runTask (eval code:154:21)
    at invoke (eval code:335:21)
ERROR CONTEXT:
[object Object]
   {
     [functions]: ,
     __proto__: { },
     _nodeIndex: 0,
     _staticNodeInfo: { },
     _tplCol: 65,
     _tplRow: 16,
     _view: { },
     component: null,
     componentRenderElement: { },
     context: { },
     injector: { },
     providerTokens: [ ],
     references: { },
     renderNode: { },
     source: "./DataTable class DataTable - inline template:16:65",
     Symbol(__immutablehash__)_m.tfqt30oiq89: undefined,
     Symbol(observable)_l.tfqt30oiq89: undefined,
     Symbol(react.element)_n.tfqt30oiq89: undefined,
     Symbol(rxSubscriber)_k.tfqt30oiq89: undefined
   }
SCRIPT5022: Error: Error in ./DataTable class DataTable - inline template:16:65 caused by: Unexpected call to method or property access.
eval code (175) (158,25)
~~~~

**Comment by Mrtcndkn** [comment]
Can you confirm that its only happening when developer tools opened? Close developer tools when you first load the page try to reorder columns after reordering open your developer tools and please notify me about the behaviour so i try to find a workaround or fix for this behaviour.

**Comment by mariahlynne** [comment]
When I load the page with developer tools closed and then reorder columns, I still see the same issues with sorting after reordering columns. The column does get reordered correctly, but after a column is reordered, its header doesn't update visually when sorting is changed (sorting still works properly as well, just the header styling and sort icon don't change). So this is the same behavior as I'm seeing with developer tools open.

**Comment by cagataycivici** [comment]
Please try with RC5, 1294 should fix it as well.

**Comment by mariahlynne** [comment]
Thanks! Do you have an estimate as to when RC5 will be released?
