### ISSUE TITLE
carousel: prev-icon

### ISSUE THREAD

**Issue by mbausche** [primefaces/primeng#13050]
### Describe the bug

In the area of the "next-arrow" i can see that the prev-icon class is used. For me it looks like a copy&paste-error

master:

https://github.com/primefaces/primeng/blame/ee9f4805dddbeeb304a81af7693ab0ff1d1da66d/src/app/components/carousel/carousel.ts#L85

10.0.3:

https://github.com/primefaces/primeng/blob/281315b38d7dba5635fb7fd6cde20eaf4d63b7fa/src/app/components/carousel/carousel.ts#LL43C39-L43C48

### Environment

PrimeNg >= 10

### Angular version

10.2.5

### PrimeNG version

10.0.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.17.0

**Comment by shreyashrajiokalaskar** [comment]
Please add more description on this. If possible also add a screen-capture of the issue. Thanks !

**Comment by cetincakiroglu** [comment]
Hi,

It's actually same styles and same class for the both prev & next icons. It's not a copy paste error.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
