### ISSUE TITLE
selectButton: Conditional template rendering is not working

### ISSUE THREAD

**Issue by mohammadreza99** [primefaces/primeng#13053]
### Describe the bug

In some case I have a usage like this : 
```
    <p-selectButton [(ngModel)]="value" [options]="options">
      <ng-template let-item *ngIf="condition">
        // some stuff
      </ng-template>
    </p-selectButton>
```

and I want to show template if the `condition` is `true` and use the default template if it is `false`.
Its behavior is that if `condition = false` it still uses the template in the code above.
other components like dropdown etc. have this feature properly for using `TemplateDirective`, but `selectButton` don't use it and cause this issue.

### Reproducer

https://stackblitz.com/edit/github-wrgned?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

### Angular version

16.0.1

### PrimeNG version

16.0.0

**Comment by payisesp** [comment]
This issue is back in the prime ng version 16.0.2
