### ISSUE TITLE
Prime ng show table scroll over the header row

### ISSUE THREAD

**Issue by aj-hops** [primefaces/primeng#13056]
### I want show prime ng scroll bar only in p-table body part not in header part row 

![image](https://github.com/primefaces/primeng/assets/109080101/96e66a37-1f19-4464-a482-79fb3a526b1f)

In this prime-ng table. curranty showing the scroll to the table body and table header both part.
Is it possible to display the scroll only in the p-table body part not in p-header part?

May I use cdk-virtual-scroll-viewport in Prime-table, if yes then how can I use it?

### Environment

Angular with Primeng

### Angular version

15.2.2

### PrimeNG version

15.3.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.20.0

### Browser(s)

firefox, Chrome

### Expected behavior

Prime-table should be visible only in table body part not in header part

**Comment by qwertyuiop13579** [comment]
I have the same issue

**Comment by bountyface** [comment]
It seems that the header of the table has the attribute `position: sticky`
There is another problem

**Comment by elinagilevich** [comment]
Same here in the latest v.17. It seems to be pretty odd to have scrollbar in the header area.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
