### ISSUE TITLE
Component: TreeSelect, MultiSelect, Dropdown

### ISSUE THREAD

**Issue by andytanasa** [primefaces/primeng#13066]
### Describe the bug

For TreeSelect, MultiSelect and Dropdown components, on a single click the overlay panel is opening as intended, on a double click it attempts to open, but the panel doesn't stay on the screen and it gets positioned in the wrong place. 

### Environment

Dev

### Angular version

15.2.7

### PrimeNG version

15.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.20.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

Double click on input for any of the components TreeSelect, MultiSelect, Dropdown and the panel doesn't stay on the screen and also it gets positioned in the wrong place.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
