### ISSUE TITLE
Themes: Combine Light/Dark themes so they work well with prefers-color-scheme

### ISSUE THREAD

**Issue by cody-reibsome** [primefaces/primeng#13067]
### Describe the feature you would like to see added

Currently light/dark theme toggles are controlled via toggling injection of a separate css file - this does not mesh well with modern light/dark mode web standards.

The current implementation prevents efficient usage of `prefers-color-scheme` (ref: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) which would allow for adaptive swapping between light and dark modes based on a user's device settings.

### Describe the solution you'd like

It seems like this could be resolved by modifying https://github.com/primefaces/primeng-sass-theme/blob/main/theme-base/_colors.scss to have an additional ruleset on e.g. `html[data-theme=dark]` that applies the css variables for colors in a dark theme.

**Comment by cody-reibsome** [comment]
Related: https://github.com/primefaces/primeng/issues/10746

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
