### ISSUE TITLE
Quill dependency - Vulnerability

### ISSUE THREAD

**Issue by vvdevteam** [primefaces/primeng#13064]
### Describe the bug

PrimeNg uses Quill as dependency which has an open vulnerability since 2021: https://github.com/advisories/GHSA-4943-9vgg-gr5r

Any plans on resolving this? I don't think Quill team is addressing this vulnerability.

### Environment

It's a security vulnerability, not sure if this is needed.

### Angular version

15.0.1

### PrimeNG version

15.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.0.0

**Comment by ThoSap** [comment]
Can be closed if https://github.com/primefaces/primeng/issues/14721 is done.

**Comment by countfnx** [comment]
#14721 is closed
