### ISSUE TITLE
Wrong type definition of ToastCloseEvent

### ISSUE THREAD

**Issue by Menecats** [primefaces/primeng#13079]
### Describe the bug

The ToastCloseEvent interface is defined as follows:

```typescript
/**
 * Custom close event.
 * @see {@link Toast.onClose}
 */
export interface ToastCloseEvent {
    /**
     * Message of the closed element.
     */
    message?: string;
    /**
     * Index of the removed element.
     */
    index?: number;
}
```

but:
- the `message` field should be of type `Message` as it's the type currently returned by the inner `p-toastItem` component.
- the `index` field should be removed as it's never set in the `onMessageClose` event of the `p-toast` component.

### Environment

.

### Angular version

16.0.2

### PrimeNG version

16.0.0-rc.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.14.1

**Comment by gucal** [comment]
Thanks for your reporting and contribution.
