### ISSUE TITLE
Update Documentation: Don't import all modules in examples

### ISSUE THREAD

**Issue by mocolicious** [primefaces/primeng#13073]
### Describe the feature you would like to see added

I think the documentation would be a lot more useful if it 

1.  used standalone components
2. only imported the minimum of what was necessary to the example

### Is your feature request related to a problem?

I've ran into a lot of issues where things aren't working as they're meant to because i'm missing certain imports and I can't figure out what im missing any other way than adding every module from the example and remvoing them until I get to a working version.  This is so tedious.  The examples don't do anything for you when it comes to understanding imports and troubleshooting missing deps.

### Describe the solution you'd like

1.  used standalone components
2. only imported the minimum of what was necessary to the example

### Describe alternatives you have considered

I've tried reading documentation thoroughly to find things, sometimes its just not there and other times its really difficult to find.  I've also done like I said and add every single import and try removing ones I dont think I need.

### Additional context

Most recently I had this issue with Progressbar Module, which ultimately I found doesn't work as a standalone (I think?) but when it comes to troubleshooting, even if i'm just doing something dumb I think it would help if there was a way to say for certain that im not missing an import

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
