### ISSUE TITLE
Component: InputNumber

### ISSUE THREAD

**Issue by astropio3000** [primefaces/primeng#13077]
### Describe the bug

InputNumber dont handle onBlur changes. After changing ngModelOptions to updateOn: 'blur' it still behave as onInput. I check it out in repo and find it has implemented overriding logic for it which collides with angular forms. 

`    
updateModel(event, value) {
        const isBlurUpdateOnMode = this.ngControl?.control?.updateOn === 'blur';

        if (this.value !== value) {
            this.value = value;

            if (!(isBlurUpdateOnMode && this.focused)) {
                this.onModelChange(value);
            }
        } else if (isBlurUpdateOnMode) {
            this.onModelChange(value);
        }
        this.onModelTouched();
    }
`

onModelTouched() should be call only on blur event and onModelChange should be called every time value change and ngModel will handle it.

I think component should not depends on ngControl

### Environment

Normal angular 15 apllication project

### Angular version

15.2.9

### PrimeNG version

15.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Steps to reproduce the behavior

1. Create InputNumber with [(ngModel)]
2. add [ngModelOptions]='{updateOn: 'blur'}'

### Expected behavior

Value is changing onInput instead onBlur

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
