### ISSUE TITLE
Panel: Collapse icon of toggle button is not showing

### ISSUE THREAD

**Issue by miribo** [primefaces/primeng#13071]
### Describe the bug

In Panel component, collapse icon of toggle button is not showing when collapse icon property is defined in p-panel tag.
When panel is expanded, collapse icon of the toggle button is not shown.

### Environment

Bug can be reproduced in primeng-panel-toggleable-demo on StackBlitz.

### Reproducer

https://stackblitz.com/run?file=src%2Fapp%2Fdemo%2Fpanel-toggleable-demo.html

### Angular version

16.0.0

### PrimeNG version

16.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Browser(s)

Chrome 113

### Steps to reproduce the behavior

Open file panel-toggleable-demo.html located in src\app\demo directory.
Add properties expandIcon and collapseIcon to p-panel tag like:
<p-panel header="Header" [toggleable]="true" expandIcon="pi pi-chevron-up" collapseIcon="pi pi-chevron-down">
Note: Icons are in reverse order as stated in issue #12929.
After demo is compiled panel is showed expanded but toggle button is not showing chevron-down icon.
Span element inside of toggle button (labeled as collapse button) is missing.
Expand icon is showed properly in toggle button (labeled as expand button).

This is not case when collapseIcon property is not defined (minus icon is shown in collapse button).

### Expected behavior

When collapseIcon property of panel is defined, defined icon should be showed in togle button.

**Comment by cetincakiroglu** [comment]
Hi,

Thanks for reporting the issue.
Fixed in https://github.com/primefaces/primeng/issues/13074
