### ISSUE TITLE
Component: KeyFilter

### ISSUE THREAD

**Issue by PointSingularity** [primefaces/primeng#13076]
### Describe the bug

```pKeyFilter``` only accepts strings and no RegExp values.

In PrimeNG version 15 this worked:
 ```ipv4RegEx = /^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)(\.(?!$)|$)){4}$/```;
template:
```html
          <input
            class="w-44 text-center"
            id="extDevIp"
            [pKeyFilter]="ipv4RegEx"
            [pValidateOnly]="true"
            pInputText
            type="text"
            formControlName="ip"
            placeholder="0.0.0.0"
          />
```

If I try to do this in 16 or if I convert it to string, it doesn't work:
 ```ipv4RegEx = /^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)(\.(?!$)|$)){4}$/.toString()```;

But if I just cast the type, it works again, functionality wise too:
 ```ipv4RegEx = /^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)(\.(?!$)|$)){4}$/ as unknown as string;```

### Environment

Windows 10,
Node: 18.16.0,
npm: 9.6.6,
Using NX version 16.2.1

### Angular version

16.0.2

### PrimeNG version

 16.0.0-rc.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Browser(s)

Chrome  113.0.5672.127

### Expected behavior

```pKeyFilter``` to accept strings and RegExp values.

**Comment by chaeller** [comment]
I have the same problem. See https://angular-ppftj4.stackblitz.io

**Comment by PointSingularity** [comment]
This should be fixed by https://github.com/primefaces/primeng/pull/13087.

**Comment by SoyDiego** [comment]
Same problem here, see: https://stackblitz.com/edit/h5vb1g-ft2wtd?file=package.json,src%2Fapp%2Fdemo%2Fkey-filter-reg-exp-demo.html,src%2Fapp%2Fdemo%2Fkey-filter-reg-exp-demo.ts,src%2Fapp%2Fapp.module.ts,tsconfig.json
