### ISSUE TITLE
inputNumber breaks when prefix starts with a space

### ISSUE THREAD

**Issue by create-signal** [primefaces/primeng#13089]
### Describe the bug

If the prefix property on p-inputNumber starts with a space character, for example:

```
<p-inputNumber
    inputId="currency-us"
    prefix=" $"
    locale="en-US"
></p-inputNumber>
```

The input will accept the first number input and then reset to null on the second number input.

### Environment

Angular 15.2.4
PrimeNG 15.3

### Reproducer

https://stackblitz.com/edit/github-a4nnvk?file=src%2Fapp%2Fapp.component.html

### Angular version

15.2.4

### PrimeNG version

15.3

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

16.17.0

### Steps to reproduce the behavior

Create an inputNumber with a prefix property of " $"

Type in "20"

The key press sets the value to "$2"

The second key press sets the value to ""

### Expected behavior

The field should behave the same with a prefix of "$" or " $"

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
