### ISSUE TITLE
Outdated documentation about TreeModule on primefaces.org site

### ISSUE THREAD

**Issue by vadimzham** [primefaces/primeng#1308]
Not sure that should be posted on github issue tracker but [this page](http://www.primefaces.org/primeng/#/tree) about TreeModule looks like outdated - in documentstion i saw this import example:
```js
import {TreeModule,TreeNode} from 'primeng/primeng';
```
But looks like `TreeNode` no more presents.

**Comment by Mrtcndkn** [comment]
Actually you should have TreeNode for using the component.
