### ISSUE TITLE
A question related to Toast Component, the purpose of breakpoints?

### ISSUE THREAD

**Issue by RubenHaeck** [primefaces/primeng#13081]
What is the purpose of the property **breakpoints** of the component **Toast** ?

```typescript
export class Toast implements OnInit, AfterContentInit, OnDestroy {

@Input() breakpoints: any;

}
```

Could you possibly make an example?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
