### ISSUE TITLE
dropdown: setting style=width:100% breaks reactivity

### ISSUE THREAD

**Issue by muuvmuuv** [primefaces/primeng#13090]
### Describe the bug

This is weird, settings style directly on `p-dropdown` breaks reactivity.

### Environment

See repl

### Reproducer

https://stackblitz.com/edit/aa4y65?file=src%2Fapp%2Fdemo%2Fdropdown-reactive-forms-demo.ts,src%2Fapp%2Fdemo%2Fdropdown-reactive-forms-demo.html

### Angular version

15

### PrimeNG version

15

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
