### ISSUE TITLE
Dependencies: declare `@angular/...` packages as `peerDependencies`

### ISSUE THREAD

**Issue by marcelhohn** [primefaces/primeng#13099]
### Describe the bug

Currently, Angular packages, on which the functionality of your components relies on, are only declared as `devDependencies` in your `package.json`. However, some of the packages are not only required during the development process, but also in production.

For example, since PrimeNG v15, you use Self-Closing Tags for your Icons, which have been introduced in Angular 15.1. Therefore someone cannot use PrimeNG 15 with e.g. Angular 14 or even Angular 15.0.x. This fact should be reflected in the `peerDependencies`. This would ensure that users of your library have the required configuration to make PrimeNG work.

See also: https://angular.io/guide/creating-libraries#peer-dependencies

### Environment

npm Version 8.11.0

### Angular version

14

### PrimeNG version

15

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.15.1

### Expected behavior

When installing PrimeNG, I want to be sure that I don't need to care about the dependencies it requires. This should be covered by `dependencies` and `peerDependencies`.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
