### ISSUE TITLE
p-fileUpload: Icon properties don't work in Basic mode.

### ISSUE THREAD

**Issue by Rimann91** [primefaces/primeng#13091]
### Describe the bug

When using the File Upload component in basic mode, I have been unsuccessful in adding primeng icons to the button. Either there is a bug or the documentation is missing a discription of how to specifically do this. The compnent doc lists properties for 'chooseIcon', 'uploadIcon', etc... but when setting the property to an icon (eg. 'pi pi-upload') one of the 'span' elements inside of the component is set to 'none' so the icon is there but it does not display. 

I was able to set the span to 'display: inline' accessing the DOM with js and the icon appears, but then it is aligned left and the button is rectangular rather than a square. I had to set the width and height also by accessing the DOM object.  It seems to me that using a prebuilt component should not require js style manipulation through the DOM object to appear as expected. Either there is a way to do it correctly that is not documented or this is a bug that needs to be fixed.

### Environment

Developing on Windows 10 inside of WSL2 Ubuntu and testing in Chrome

NX workspace 15.7
Node  16.18
Primeng 14.2.3
PrimIcons 6.0.1

### Angular version

14.2

### PrimeNG version

14.2.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.18

### Expected behavior

Icons should appear in the center of the file-upload button when the chooseIcon or uploadIcon properties are set

**Comment by volvachev** [comment]
Hi, I checked that in the latest version this is fixed. (please check on 15.4.0+)

**Comment by mehmetcetin01140** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.
