### ISSUE TITLE
Component: Picklist ,Can we add sourcefoorterTemplate and targetFooterTemplate like sourceHeaderTemplate and targetHeaderTemplate.

### ISSUE THREAD

**Issue by abdullahqudeer** [primefaces/primeng#13097]
### Feature Description:

 I want to request  to add **sourceFooterTemplate** and **targetFooterTemplate** like **sourceHeaderTemplate** and **targetHeaderTemplate**.

### Problem Statement:

I want to add a table on both side of picklist, I have added table tag in header templates but now there is no option to close table tag.
.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
