### ISSUE TITLE
Component: Panel, custom expandIcon not showing!

### ISSUE THREAD

**Issue by Ruslancic** [primefaces/primeng#13092]
### Describe the bug

Adding `expandIcon` to the header of the Panel, does not show the icon! Working only with default icons!

### Environment

`Angular CLI: 16.0.1
Node: 16.18.0
Package Manager: npm 9.6.6
OS: win32 x64

Angular: 16.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.1
@angular-devkit/build-angular   16.0.1
@angular-devkit/core            16.0.1
@angular-devkit/schematics      16.0.1
@schematics/angular             16.0.1
rxjs                            7.8.1
typescript                      5.0.4
primeflex: 3.3.0
primeicons: 6.0.1
primeng: 16.0.0-rc.1`

### Reproducer

https://stackblitz.com/edit/ykjgg2?file=src%2Fapp%2Fdemo%2Fpanel-toggleable-demo.html

### Angular version

16.0.1

### PrimeNG version

16.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.18.0

### Steps to reproduce the behavior

Just test Panel Demo Template

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
