### ISSUE TITLE
Confirm Dialog message with multiple lines

### ISSUE THREAD

**Issue by bogacg** [primefaces/primeng#1310]
Apparently `\n` or `<br>` are not permitted with message area of confirm dialog.

I believe that would be a nice addition to be able to define line endings for `message` text.

**Comment by VictorRos** [comment]
I also encounter this problem.
I found a solution to take account `\n` for `message` text by overloading `.ui-confirmdialog-message` CSS class.

```css
.ui-confirmdialog-message {
    white-space: pre-line;
}
```

For example:
```TypeScript
this.confirmationService.confirm({
    header: "My header",
    message: "My line 1\nMy line 2\n\nMy last line",
});
```
will display the following body dialog
```
My header                                                 X
------------------------------------------------------------
My line 1
My line 2

My last line
```

Hope it can help.

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release with using <br> instead in message, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/VZbdZfQ7SuTV87tTkbYR

**Comment by hoangthuongboz** [comment]
> I also encounter this problem.
> I found a solution to take account `\n` for `message` text by overloading `.ui-confirmdialog-message` CSS class.
> 
> ```css
> .ui-confirmdialog-message {
>     white-space: pre-line;
> }
> ```
> 
> For example:
> 
> ```ts
> this.confirmationService.confirm({
>     header: "My header",
>     message: "My line 1\nMy line 2\n\nMy last line",
> });
> ```
> 
> will display the following body dialog
> 
> ```
> My header                                                 X
> ------------------------------------------------------------
> My line 1
> My line 2
> 
> My last line
> ```
> 
> Hope it can help.

Very good

**Comment by codearachnid** [comment]
The class has changed slightly - so you should use `.p-confirm-dialog-message` if you still want to use the styling to reference new line text:

```
.p-confirm-dialog-message {
white-space: pre-line;
}
```
