### ISSUE TITLE
Toggable Panel without toggler is not available anymore

### ISSUE THREAD

**Issue by chaeller** [primefaces/primeng#13101]
### Describe the bug

The toggable Panel works fine for me in PrimeNG 15.4.1.
With PrimeNG 16.0.0-rc.2 I have the following problem:

The panel has to be toggable and collapsed. The user should not be able to expand the panel. It should be expaned by code using the API.

PrimeNG 15.4.1 = OK :
https://stackblitz.com/edit/angular-ze1k1l?file=src%2Fmain.ts

PrimeNG 16.0.0-rc.2 = not OK : 
https://stackblitz.com/edit/angular-k5mrk2?file=src%2Fmain.ts

### Environment

Windows 10
Node: 18.16.0
npm: 9.6.6

### Reproducer

https://stackblitz.com/edit/angular-k5mrk2?file=src%2Fmain.ts

### Angular version

16.0.2

### PrimeNG version

16.0.0-rc.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Browser(s)

Chrome 113.0.5672.127

### Steps to reproduce the behavior

PrimeNG 15.4.1 = OK :
https://stackblitz.com/edit/angular-ze1k1l?file=src%2Fmain.ts

PrimeNG 16.0.0-rc.2 = not OK : 
https://stackblitz.com/edit/angular-k5mrk2?file=src%2Fmain.ts

### Expected behavior

The panel has to be toggable and collapsed. The user should not be able to expand the panel. It should be expaned by code using the API.

[toggler]="none" is not possible with the Panel in PrimeNG 16.0.0-rc.2

**Comment by chaeller** [comment]
The following workaround works for me:
```
  <p-panel
    [toggleable]="true"
    [collapsed]="collapsed"
    (onAfterToggle)="onAfterToggle()"
  >
    <ng-template pTemplate="headericons">
      <ng-container *ngIf="isCollapsed()">
        <i class="pi pi-fw pi-chevron-down" (click)="iconClick($event)"></i>
      </ng-container>
      <ng-container *ngIf="!isCollapsed()">
        <i class="pi pi-fw pi-chevron-right"></i>
      </ng-container>
    </ng-template>
     ...
  </p-panel>
```

The click handler:
```
  // prevent disabled and collapsed panel to expand when clicking on the icon
  iconClick(event: MouseEvent) {
    if (this.disabled) {
      event.stopPropagation();
    }
  }
```

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
