### ISSUE TITLE
Panel expandIcon is not displayed

### ISSUE THREAD

**Issue by chaeller** [primefaces/primeng#13100]
### Describe the bug

A toggable Panel with custom Icons works fine in PrimeNG 15.4.1.
With PrimeNG 16.0.0-rc.2 the expandIcon is not visible!

PrimeNG 15.4.1 = OK :
https://stackblitz.com/edit/angular-vgmkut?file=src%2Fmain.ts

PrimeNG 16.0.0-rc.2 = not OK : 
https://stackblitz.com/edit/angular-gaudtc?file=package.json

### Environment

Windows 10
Node: 18.16.0
npm: 9.6.6

### Reproducer

https://stackblitz.com/edit/angular-gaudtc?file=package.json

### Angular version

16.0.2

### PrimeNG version

16.0.0-rc.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Browser(s)

Chrome 113.0.5672.127

### Steps to reproduce the behavior

PrimeNG 15.4.1 = OK :
https://stackblitz.com/edit/angular-vgmkut?file=src%2Fmain.ts

PrimeNG 16.0.0-rc.2 = not OK : 
https://stackblitz.com/edit/angular-gaudtc?file=package.json

### Expected behavior

A toggable Panel with custom Icons works fine in PrimeNG 15.4.1.
With PrimeNG 16.0.0-rc.2 the expandIcon is not visible!

**Comment by chaeller** [comment]
The functionality is deprecated. Using the template headericons works for me:
  <p-panel
    [toggleable]="true"
    [collapsed]="collapsed"
  >
    <ng-template pTemplate="headericons">
      <ng-container *ngIf="isCollapsed()">
        <i class="pi pi-fw pi-chevron-down"></i>
      </ng-container>
      <ng-container *ngIf="!isCollapsed()">
        <i class="pi pi-fw pi-chevron-right"></i>
      </ng-container>
    </ng-template>
...

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
