### ISSUE TITLE
p-inputNumber do not show value 0

### ISSUE THREAD

**Issue by hschindler** [primefaces/primeng#13103]
### Describe the bug

I have an p-inputNumber control on my page an if my data have the int value 0. The input show nothing.

I tried it with ngModel and with form field.
Here my HTML-Code:
`<p-inputNumber
    [min]="0"
    [max]="99"
    mode="decimal"
    [(ngModel)]="this.myData">
</p-inputNumber>`

### Environment

Windows 11, Angular, Typescript

### Angular version

~15.2.0

### PrimeNG version

^15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v18.16.0

### Expected behavior

The input number should show the value 0 if the data is int 0.

**Comment by mikeandtherest** [comment]
I cannot reproduce your issue. Most likely there's something happening on with the value of myData or some other binding issue.

Here's a working Stackblitz example of your scenario: https://stackblitz.com/edit/stackblitz-starters-f4zas2?file=src%2Fmain.ts

Btw, you should not use the 'this' keyword inside the html template file. It's unneeded and bad practice.

**Comment by hschindler** [comment]
Hi thank you for you effort. Unfortunaltely it was my misstake. I had an if (myData) arround my code to set data.

And value 0 is not true with if.
