### ISSUE TITLE
 TreeTable: Can't write multi line in a textarea used to edit a cell

### ISSUE THREAD

**Issue by ThibSCH** [primefaces/primeng#13105]
### Describe the bug

Hello,

I ran into the same issue as described here : https://github.com/primefaces/primeng/issues/10458 which has been closed but not fixed.

> Textarea when used in Datatable Celleditor completes Edit Mode when Enter Or ALT+Enter Or Shift+Enter key is pressed.

The last comment said :
> "this improvement may have been developed in another issue ticket without realizing it"

which was unfortunately not true 😢 despite using the latest version (16.0 rc1) as can be seen here : https://codesandbox.io/s/primeng-tree-table-edit-demo-forked-3yro2k?file=/src/app/demo/tree-table-edit-demo.html

A pull request to not exit the editing mode on 'shift+enter' is already available for it and it looks good to me :  https://github.com/primefaces/primeng/pull/11476

Best Regards,

### Environment

Prime 16
Angular 16

also on 15

### Reproducer

https://codesandbox.io/s/primeng-tree-table-edit-demo-forked-3yro2k?file=/src/app/demo/tree-table-edit-demo.html

### Angular version

16.0.0

### PrimeNG version

16.0.0-rc1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.18.0

### Steps to reproduce the behavior

1. Create a treetable with cells editable with a textarea
2. Start editing a cell by clicking on it
3. Press enter (with or without any modifier key)
4. The editing stops and no new line is added to the textarea value

### Expected behavior

Possibility to add a new line inside a  textarea used to edit a cell in a TreeTable by either setting an option or using a modifier key along enter

**Comment by arianox** [comment]
@mertsincan You you provid the bugfix for latest 15. release?
