### ISSUE TITLE
Documentation - Update

### ISSUE THREAD

**Issue by psarno** [primefaces/primeng#13115]
### Describe the feature you would like to see added

The documentation as it relates to things such as event objects available and exposed by PrimeNG is terriby out of date.

Just as one example, for `p-dropdown` it says that `onChange` handles:

> event.originalEvent: Browser event
> event.value: Selected option value 

In reality, there is a `DropdownChangeEvent` defined in `primeng/dropdown`.

Another example would be `p-table` and `onFilter`.   The documentation states:

> event.filters: Filters object having a field as the property key and an object with value, matchMode as the property value.
> event.filteredValue: Filtered data after running the filtering. 

In reality, there is a `TableFilterEvent` defined in `primeng/table`.

It would be extremely helpful if the documentation (especially on the API tab) refelected these interfaces that exist for these purposes, instead of referring to random event properties.

### Is your feature request related to a problem?

Yes, it's a problem because we have to go looking around for events that may be suitable for the use cases when we can't refer to the official documentation.

### Describe the solution you'd like

Updated documentation as interfaces are created and exported from PrimeNG libraries for use in such cases.

**Comment by enzocassemiro** [comment]
I'm not sure if I should create a new issue for this, but I noticed that the documentation for the PrimeNG tables lacks information about lazy loading and server-side functionality. These features can be incredibly useful when dealing with large datasets and optimizing performance.

https://primeng.org/table#paginator-basic

It would be great if the documentation could cover these aspects in detail, providing examples and guidelines on how to implement lazy loading and server-side functionality with the PrimeNG tables. This would greatly benefit developers who are looking to optimize their table performance.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
