### ISSUE TITLE
Component: Tree

### ISSUE THREAD

**Issue by RS-Roshi** [primefaces/primeng#13118]
### Describe the bug

The `[(selection)]` is two way bonded but if I set something in .ts file it is not displayed as selected in Tree type checkbox, any suggestion?

### Environment

Angular v16 
PrimNG v16

### Angular version

16

### PrimeNG version

16

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Browser(s)

Chrome

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
