### ISSUE TITLE
Table - documentation of table paginator programatic inconsistent

### ISSUE THREAD

**Issue by koesper** [primefaces/primeng#13119]
### Describe the bug

Two minor issues with the documentation of the table paginator, in the examples of programmatic usage:

1. In the examples, a couple of buttons is added to the showcase, but they are not in the actual case. This makes it a bit confusing where the `next()` and `prev()` functions are coming from.  

2. in the template of `paginator-programmatic-doc` the `first` property is using two way databinding, which is not possible.  
`[(first)]="first"` -> `[first]="first"`

I'll open a PR for these minor changes

### Environment

-

### Angular version

16

### PrimeNG version

16.0.0-rc.2 (master branch)

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

-

**Comment by cetincakiroglu** [comment]
Fixed in https://github.com/primefaces/primeng/issues/13119
