### ISSUE TITLE
Primeng table does not respected [rows]='25' property when selected location are placed at top of the table

### ISSUE THREAD

**Issue by SwamiNachiket** [primefaces/primeng#13114]
I am using primeng p-table version 9.x , The table uses lazyloading feature along with pagination,
I am facing a strange issue , when selected rows from the second page are moved to the first page, the display number of rows on the page exceeds the [rows]='25',it ignores the 'rows' property value,

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
