### ISSUE TITLE
 Error: node_modules/primeng/api/shared.d.ts:19:81 - error TS2344: Type '{ type: { alias: "type"; required: false; }; name: { alias: "pTemplate"; required: false; }; }' does not satisfy the constraint '{ [key: string]: string; }'.   Property '"type"' is incompatible with index signature.     Type '{ alias: "type"; required: false; }' is not assignable to type 'string'.  19     static ɵdir: i0.ɵɵDirectiveDeclaration<PrimeTemplate, "[pTemplate]", never, { "type": { "alias": "type"; "required": false; }; "name": { "alias": "pTemplate"; "required": false; }; }, {}, never, never, false, never>; 

### ISSUE THREAD

**Issue by vivekaviva** [primefaces/primeng#13111]
Getting this issue  when i try to import 

import { CalendarModule } from 'primeng/calendar';

in my component

**Comment by SOLVOHA** [comment]
I have the same issue.

**Comment by Jiya-Ull-Haq** [comment]
same issue

**Comment by qiuyuhz** [comment]
same issue

**Comment by LordMario** [comment]
No hay solucion

**Comment by A330454** [comment]
Solution Found!!!!

Just update npm and update your angular/cli version, if the error persists on your current project, try creating a new angular project , broke my head trying to fix this, but because of the primeng updates, it has to be done with the lastest recommended npm and angular/cli versions. hope this is useful for you guys, good coding!

**Comment by pablosay** [comment]
Your solution worked for me!

> Solution Found!!!!
> 
> Just update npm and update your angular/cli version, if the error persists on your current project, try creating a new angular project , broke my head trying to fix this, but because of the primeng updates, it has to be done with the lastest recommended npm and angular/cli versions. hope this is useful for you guys, good coding!

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
