### ISSUE TITLE
Dialog: position relative when append to another element

### ISSUE THREAD

**Issue by Nevermre** [primefaces/primeng#13112]
### Describe the feature you would like to see added

I would like to prime ng set dialog(or p-dialog-mask) position to relative or let me choose what position I would like when append the dialog to another element, because the p-dialog-mask is set to fixed by default 

### Is your feature request related to a problem?

yeah I tried to position my dialog in some area, but isn't possible.

### Describe the solution you'd like

set the position to relative or a new parameter to choose position

### Describe alternatives you have considered

manually set the x,y position of the dialog

### Additional context

![image](https://github.com/primefaces/primeng/assets/37025821/d79ccf7b-8460-43c4-807a-c1ffe3e760cb)
Dialog after setting the position to relative and append to a invisible div in my code

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
