### ISSUE TITLE
FileUpload | File limit does not fire error

### ISSUE THREAD

**Issue by cetincakiroglu** [primefaces/primeng#13129]
https://stackblitz.com/edit/j3bzrg?file=package.json,src%2Fapp%2Fdemo%2Ffile-upload-basic-demo.html

**Comment by jlorellana684** [comment]
Hi, I would like to clarify, it's not the file limit itself. When fileLimit is set the error messages don't work.

**Comment by jlorellana684** [comment]
@gucal that doesn't solve the issue, try for example selecting an invalid file type and you won't get the error message.
