### ISSUE TITLE
How to build without Angular dependency?

### ISSUE THREAD

**Issue by httpdigest** [primefaces/primeng#1312]
I just cloned the project and found that the package.json does not declare any dependencies, including to Angular 2.
Consequently, a build with:
`npm install`
`npm run build-prod`
results in many errors for unresolved module imports of angular.

**Comment by httpdigest** [comment]
Adding the following to the package.json fixes all build issues:
```json
  "dependencies": {
    "@angular/core": "2.1.2",
    "@angular/common": "2.1.2",
    "@angular/compiler": "2.1.2",
    "@angular/core": "2.1.2",
    "@angular/forms": "2.1.2",
    "@angular/router": "3.1.2",
    "@angular/http": "2.1.2",
    "@angular/platform-browser": "2.1.2",
    "@angular/platform-browser-dynamic": "2.1.2",
    "rxjs": "5.0.0-rc.1",
    "core-js": "2.4.1",
    "zone.js": "0.6.26"
  },
```

**Comment by Mrtcndkn** [comment]
Yes we mention that in the wiki section thanks.
