### ISSUE TITLE
p-inputnumber: Icons

### ISSUE THREAD

**Issue by psarno** [primefaces/primeng#13126]
### Describe the feature you would like to see added

The `p-inputtext` controls supports icons:

![image](https://github.com/primefaces/primeng/assets/18640860/08d59f84-fc0c-424b-a839-34cefbf70d33)

The `p-inputnumber` does not.

The documentation onlly mentions as CSS class `p-input-number-button-icon` which is for the "icon" but there is no information on how this is supposed to be used.

When mixing and matching `p-inputtext` and `p-inputnumber` controls that need icons, this becomes difficult.

### Is your feature request related to a problem?

Yes, on forms we vertically mix these controls and the text ones look fine with the icons.  The numeric ones do not.
![image](https://github.com/primefaces/primeng/assets/18640860/6769d366-6745-47fa-90c9-b50056b0ad3b)

### Describe the solution you'd like

The ability for p-inputnumber to support icons.

**Comment by MAN-Sendance** [comment]
I am also interested in this. Why was it closed?
