### ISSUE TITLE
Component: Drag and drog

### ISSUE THREAD

**Issue by Clemzd** [primefaces/primeng#13121]
### Describe the feature you would like to see added

Complete the documentation to add the possibility to disable the directive

### Is your feature request related to a problem?

No

### Describe the solution you'd like

Explain that this code is possible
`<div pDraggable [pDraggableDisabled]="draggableDisable">`

I had to get into the source code to find it

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
