### ISSUE TITLE
Component: Tree - Library is missing import for plusicon

### ISSUE THREAD

**Issue by kkovac1** [primefaces/primeng#13122]
### Describe the bug

After setting tree layout to horizontal. There is no plus icon for child expand.

You can see in the html below from inspect, there is no svg for plus icon, like there is for minusicon.

Plus icon HTML:
![image](https://github.com/primefaces/primeng/assets/75999845/bb865c7e-42e6-4e7b-b959-89efce21f2d1)

Minusicon HTML: 
![image](https://github.com/primefaces/primeng/assets/75999845/6c83d54f-2106-4e55-885f-f2f3e3c78885)

Anyone already faced this? 

### Environment

.

### Angular version

16

### PrimeNG version

16

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Browser(s)

Chrome

**Comment by kkovac1** [comment]
Found problem. Tree module is missing import for Plusicon!
![image](https://github.com/primefaces/primeng/assets/75999845/73181c6c-4f07-436b-a954-d6b06dec39a3)

**Comment by kyjus25** [comment]
Broken on StackBlitz example as well. Only an issue in horizontal layout

![Screenshot from 2023-06-01 13-49-15](https://github.com/primefaces/primeng/assets/6710794/9ec62758-fa0f-48ae-9cb0-adb55276766a)

**Comment by kyjus25** [comment]
Also, I should note is broken on PrimeNG 15 as well
