### ISSUE TITLE
Provide ability for immutablejs data with custom classes instead of array

### ISSUE THREAD

**Issue by born2net** [primefaces/primeng#1313]
Provide ability for immutablejs data with custom classes instead of array

We wanted to begin using this lib, however in out projects we use Immutable.js with custom classes (so we can get typed data in Redux), to see the full story checkout: 
https://www.youtube.com/watch?v=bEkPEnudm7s&feature=youtu.be

This means we need to provide both the Immuatble data as well as a helper methods that will tell PrimeNg how to unwrap the class members ```getData=...``` as in

```

var myList = List<any>([myClassA,myClassB,myClassC]);

<p-dropdown [options]="myList" [getData]="myFunc" #dropDown (onChange)="onSelectedAdnetCustomer($event, dropDown.value)" [style]="{'width':'200px'}" [(ngModel)]="selectedBusinessId" filter="filter"></p-dropdown>

myFunc((i_myClass:MyClass)=>{
    return i_myClass.getmyData()
});

```
Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by NNemec** [comment]
This sounds related to my own issue, though I am not quite sure:

Does the getData input that you describe actually exist? Or is this the proposal that you make?

In any case: I also want to use PrimNG with immutable.js data structures (in my case with DataTable), but however I try this, I cannot get it to work. Anyhow, I am not quite sure yet, whether fully understand the situation at all.

**Comment by born2net** [comment]
ya I am in the same boat, waiting on this feature before we can start using this lib :(
it seems to only support basic data structures and we need support for our custom StoreModel which is based on Immutablejs

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
