### ISSUE TITLE
FileUpload: onSelect behaviour

### ISSUE THREAD

**Issue by jlorellana684** [primefaces/primeng#13130]
### Describe the bug

When using the choose button the onSelect event doesn't have the files in the "files" property, but when using drag and drop it does, it's suposed that when selecting the files they always should go into files property to do custom checks, before it goes to the currentFiles property. @cetincakiroglu 

### Environment

dev

### Reproducer

https://stackblitz.com/edit/bwlhgp?file=src%2Fapp%2Fdemo%2Ffile-upload-advanced-demo.html

### Angular version

16.0

### PrimeNG version

16

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
