### ISSUE TITLE
NodeJS CI failing

### ISSUE THREAD

**Issue by IvanFeric** [primefaces/primeng#13146]
### Describe the bug

NodeJS CI GitHub workflows (https://github.com/primefaces/primeng/actions/workflows/node.js.yml) have been failing for the last 2 weeks due to using the old `actions/checkout@v2` and `actions/setup-node@v2` specified in the workflow definition (https://github.com/primefaces/primeng/blob/master/.github/workflows/node.js.yml). The fail message is:

> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-node@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

For example, one such fail is this one - https://github.com/primefaces/primeng/actions/runs/5143729396

It should probably be fixed by updating the version of checkout action from `actions/checkout@v2` to `actions/checkout@v3` as well as updating the version of setup-node action from `actions/setup-node@v2` to `actions/setup-node@v3`. As per https://github.com/actions/setup-node/issues/617, there should be no breaking changes for upgrade and the major change was to use node 16 instead of node 12 which is no longer supported by GitHub.

### Environment

Not applicable - the problem is in the GitHub workflows

### Angular version

16

### PrimeNG version

16

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
