### ISSUE TITLE
Component: calendar true readonly feature

### ISSUE THREAD

**Issue by ysk3a** [primefaces/primeng#13145]
### Describe the feature you would like to see added

Any plans to add true readonly to calendar. (not readonlyinput) 
maybe until https://github.com/angular/angular/issues/11447 is resolved? 
setting to disable with reactive form does not include disable controls on submit (unless you do some kind of work around of using getRawValues or something)
but visually it is hard to read. 
and maybe for accessibility improvement based on https://github.com/angular/angular/issues/11447#issuecomment-889526801 .

it seems that there have been a couple issues added https://github.com/primefaces/primeng/issues?q=readonly+calendar but all have been closed.

### Is your feature request related to a problem?

There should be a readonly so that there user can still interact as much as a normal html readonly allows and not open a calendar when user focuses on the p-calendar input since it is readonly. this is separate from primeng's readonlyinput and disable state since disable state with reactive form is omitted on submit.

### Describe the solution you'd like

Add true readonly so that the user cannot click the input to open the calendar or make any changes. Different from disable.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
