### ISSUE TITLE
Karma test throws "documentResizeListener is not a function" message in dialog.js

### ISSUE THREAD

**Issue by nomis89** [primefaces/primeng#1314]
I think the ngOnDestroy method in dialog.js wants to unsubscribe listeners which doesn't exist.

Also mentioned in this forum entry:
http://forum.primefaces.org/viewtopic.php?f=35&t=47860
Thanks

**Comment by Mrtcndkn** [comment]
Thanks i think the issue is what you mentioned i will review that and get back to you from here.

**Comment by nomis89** [comment]
@Mrtcndkn nice, thanks for the fast reply :)

**Comment by albertosramires** [comment]
@Mrtcndkn Any updates on this?

**Comment by Yoranium238** [comment]
This same issue exists in confirmdialog.js.  Does this require a separate issue to be logged?
