### ISSUE TITLE
Paginator: Accessibility Issue on paginator button and drop down

### ISSUE THREAD

**Issue by KalyaniDas** [primefaces/primeng#13141]
### Describe the bug

I am using paginator component on p-table. it is working fine but getting some accessibility related critical issues below are the screenshots

![image](https://github.com/primefaces/primeng/assets/116780063/e5e7e65d-65b1-49a2-a53d-68dd9c1fdf52)
4 paginator buttons (next , previous)
1 dropdown lebel
![image](https://github.com/primefaces/primeng/assets/116780063/b4b47f62-ee27-4a5f-bbdc-3d78240c9038)
![image](https://github.com/primefaces/primeng/assets/116780063/3e494f55-4cb9-441c-a909-b2a9c5347e6d)

need help to fix those critical issues

### Environment

 **angular/cli: ^14.2.10,
 angular/compiler-cli":^14.2.12
 primeng : ^14.2.3
 primeicons: ^6.0
node": ^12.11.1**
  
axe DevTools : to scan the page for accessibility testing 

### Angular version

14.2.10

### PrimeNG version

14.2.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

^12

### Steps to reproduce the behavior

Go to primeNg table example https://www.primefaces.org/primeng-v14-lts/table
scan paginator component (scan part of the page) using axe dev Tools or any other accessibility tool see the result

![image](https://github.com/primefaces/primeng/assets/116780063/ebdcee36-1d87-4aeb-9398-1b0d3c76f399)

### Expected behavior

need to know the solution to fix  all critical and serious issues .

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
