### ISSUE TITLE
Toast messages disappear too fast when using a combination of clear followed by add when using the MessageService

### ISSUE THREAD

**Issue by zandhaai** [primefaces/primeng#13149]
### Describe the bug

I have created the following NgRx effect:

```
    toast$ = createEffect(() =>
        this.actions$.pipe(
            ofType(CoreActions.Toast),
            tap(message => {
                this.messageService.clear();
                this.messageService.add(message);
            })
        ),
        {dispatch: false} // Because only an action is done, we should not redispatch (that would cause an infinite dispatch loop of toasts)
    );
```

The reason is, I want to remove previous messages when showing a new one, consider the situation:

Toast 'Saving...' followed by 'Saved!'. 

Now I noticed the clear seems to mess up the lifetime of a message: the messages disappear very quickly. If I comment out the 'this.messageService.clear()' it works normally. Looking at your code this could be the cause:

```
export class MessageService {
    private messageSource = new Subject<Message | Message[]>();
    private clearSource = new Subject<string | null>();

``` 
So these could interact with each other.

### Environment

Development environment: Windows 11

### Angular version

13.3.3.1

### PrimeNG version

13.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.1.0

### Browser(s)

Chrome 114

### Steps to reproduce the behavior

n/a

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
