### ISSUE TITLE
Issue with positioning when using float label in the InputNumber Component with buttons!

### ISSUE THREAD

**Issue by ysk3a** [primefaces/primeng#13140]
### Describe the bug

When using the float label for InputNumbers with Buttons, the float label is on top of the button.
![image](https://github.com/primefaces/primeng/assets/53593899/274338e1-cf5e-4c06-a0ae-29acf5f3a551)
I am guessing that float should be floating above where the text cursor/caret is since that is how it moves when using normal primeng input text with float + icon.

### Environment

Stackblitz on Chrome 114
https://stackblitz.com/edit/d6ttwj?file=src%2Fapp%2Fdemo%2Finput-number-buttons-demo.html

### Reproducer

https://stackblitz.com/edit/d6ttwj?file=src%2Fapp%2Fdemo%2Finput-number-buttons-demo.html

### Angular version

16

### PrimeNG version

"primeng": "16.0.0-rc.1",

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

stackblitz node -v : 16.14.2

### Browser(s)

 Chrome 114

### Expected behavior

When using float label with inputnumber that has horizontal buttons, the label should not be on top of the buttons.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
