### ISSUE TITLE
Sidebar: p-sidebar accessibility issue 

### ISSUE THREAD

**Issue by KalyaniDas** [primefaces/primeng#13142]
### Describe the bug

I am using sidebar component. getting below critical accessibility issue on p-side bar component 

Tested in primeng site https://www.primefaces.org/primeng-v14-lts/sidebar
![image](https://github.com/primefaces/primeng/assets/116780063/2db3a77f-1c1d-4e6d-bde2-cd437ff4b823)

### Environment

angular/cli: ^14.2.10,
angular/compiler-cli":^14.2.12
primeng : ^14.2.3
primeicons: ^6.0
node": ^12.11.1

### Angular version

14.2.10

### PrimeNG version

14.2.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

^12

### Steps to reproduce the behavior

Go to sidebar component https://www.primefaces.org/primeng-v14-lts/sidebar
click on any button to see the side bar  once side bar is opened 
scan the component using axeDev tool for any other accessibility tool

### Expected behavior

Need help to fix above mentioned critical issue related to accessibility, 

Thanks
Kalyani Das

**Comment by cetincakiroglu** [comment]
Hi,

Accessibility implementation is available for versions 16.5x and 17. You are experiencing an error because there is no accessibility implementation for version 14. Please try using more recent versions.
