### ISSUE TITLE
Button: loading style issue when already has an icon

### ISSUE THREAD

**Issue by mohammadreza99** [primefaces/primeng#13148]
### Describe the bug

The loading icon has no margin from label, if already there is an icon.

### Environment

windows

### Reproducer

https://stackblitz.com/edit/r6awcv?file=package.json,src%2Fapp%2Fdemo%2Fbutton-loading-demo.html

### Angular version

16.0.1

### PrimeNG version

16.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

**Comment by Estrolldomezx** [comment]
try this
  
<button
    pButton
    pRipple
    class="ml-2"
    label="Submit"
    type="button"
    icon="pi pi-home"
    [loading]="loading"
    (click)="load()"
  ></button>

**Comment by mohammadreza99** [comment]
@Estrolldomezx  Thanks,
Suppose I'm not using the bootstrap. although you add margin to button own. but the loading icon needs margin.
