### ISSUE TITLE
Component: InputNumber

### ISSUE THREAD

**Issue by mgomesfiducial** [primefaces/primeng#13143]
### Describe the feature you would like to see added

As a currency InputNumber should be possible when the user use the dot(.) in the numberpad keyboard (the numbers in the keyboard at the right) the component change to comma depending of the component configuration. For example on windows calculator, when he use the dot(.) at the right of the keyboard they change to comma (,) depending of the locale. For questions of ux this will be a good thing for the users.

### Is your feature request related to a problem?

no

### Describe the solution you'd like

if i use the numberpad of the keyboard at the right, and i want to enter the value 1,99, when i press the dot(.) the component should change the dot(.) for comma (,). in that way i don't need to press the comma in the keyboard and i can use the dot(.) in the numeric keyboard.

![image](https://github.com/primefaces/primeng/assets/126164227/cb32fceb-b0aa-463e-beb6-835d6f9effcb)

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
