### ISSUE TITLE
Component: QR

### ISSUE THREAD

**Issue by yashHenceforth** [primefaces/primeng#13156]
### Describe the feature you would like to see added

Hello Prime Team, Here I am request you to add QR Component in your package.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
