### ISSUE TITLE
PrimeNG Website - Documentation for Toast missing position feature in demo

### ISSUE THREAD

**Issue by KraftyKaleb** [primefaces/primeng#13159]
### Describe the bug

https://primeng.org/toast#position
Demo code is missing the position HTML tag. It is possible to view the API tab and infer that the property should be in the HTML, but this may be confusing for new users.
![image](https://github.com/primefaces/primeng/assets/25018116/19f8b69b-be21-40f6-a3a5-61b03d512fe5)
Should be `<p-toast position="{{position}}">`

### Environment

Chrome 114.0.5735.110

### Angular version

16.0.1

### PrimeNG version

16.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Browser(s)

Chrome 114.0.5735.110

### Steps to reproduce the behavior

Go to https://primeng.org/toast#position and view the code in the demo. There is no "position" property used.

### Expected behavior

I expected the code demo to demonstrate how to use the documented feature.

**Comment by gucal** [comment]
Hi,

Thanks for reporting. Fixed https://github.com/primefaces/primeng/pull/13179
