### ISSUE TITLE
Table: Programmatic scroll to specified index does not work

### ISSUE THREAD

**Issue by ttd1shoonya** [primefaces/primeng#13154]
### Describe the bug

Programmatic scrolling the primeng table to an specified index does not work.
ex: this.dataTable.scrollToVirtualIndex(someRowIndex);

The scroll however works as expected if a timeout is introduced.

### Environment

The issue is not limited to a specific environment (reproducible with primeng table 15.3 onwards)

### Reproducer

https://stackblitz.com/edit/f5qvib-kgw93q

### Angular version

15.1.0^

### PrimeNG version

15.3.0^

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14.2

### Steps to reproduce the behavior

1. Click on withoutTimeout button, the table is populated with 4000 rows and scrollToVirtualIndex is set to index 3000
2. The programmatically selected index is not selected

### Expected behavior

1. Click on withoutTimeout button, the table is populated with 4000 rows and scrollToVirtualIndex is set to index 3000
2. The programmatically selected index is selected

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
