### ISSUE TITLE
Angular2-Meteor with PrimeNG

### ISSUE THREAD

**Issue by hakikihacioglu** [primefaces/primeng#1315]
Hi,

I am working on a project with Angular-Meteor and it is working great. As my starting point I made use of https://github.com/Urigo/angular2-meteor-base. Now I would like to install PrimeNG as my UI. The documentation on http://www.primefaces.org/primeng/#/setup says I need a module manager like webpack or system.js to bind the dependencies. None of them exists on the angular-meteor-base project. I don't even understand how that works, because even on the Angular2 page, the boilerplate example contains a module loader. How can I add PrimeNG into this.

Thank you

**Comment by garethlewis** [comment]
You really need to talk to the Meteor guys, this is a generic issue.
