### ISSUE TITLE
Component: Sidebar still does not hide the overlay when dismissing

### ISSUE THREAD

**Issue by Vernon-Accela** [primefaces/primeng#13150]
### Describe the bug

We saw this issue in v12, and I see reports of it in v14, but we now see it again in version 15. When the user dismisses the sidebar, the p-overlay-component sometimes stay behind. At this point, the user can't interact with the page at all. In order to work around this, I've had to create a ViewChild of the component and manually dismiss it, calling the hide code twice.

### Environment

Angular application:

Angular: 15.2.3
Primeng: 15.3.0
AOT enabled

### Angular version

15.2.3

### PrimeNG version

15.3.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.20.0

### Browser(s)

Chrome 113.0.5672.127, Edge 113.0.1774.50

### Steps to reproduce the behavior

1. Create a PrimeNg page with a Sidebar component. 
2. Once compiled, open and interact with the sidebar
3. Click outside the sidebar to dismiss it.
4. Try to interact with the page that was below the sidebar
Expected Results: I can click and interact with the page
Actual Results: I can't interact with the UI. A check of the HTML reveals the component overlay is still there blocking input.

### Expected behavior

Expected Results: I can click and interact with the page
Actual Results: I can't interact with the UI. A check of the HTML reveals the component overlay is still there blocking input.

**Comment by bharatbhaskar** [comment]
The workaround is to use CSS as - 

::ng-deep .p-sidebar-mask {
    z-index: 0 !important;
}

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
