### ISSUE TITLE
Toast documentation needs updated

### ISSUE THREAD

**Issue by logan-pipes** [primefaces/primeng#13151]
The html content of the [position](https://primeng.org/toast#position) section is incorrect, it actually corresponds to (and is a duplicate of) the section [above](https://primeng.org/toast#severity) it. The typescript content looks to be correct.

**Comment by kyjus25** [comment]
@mertsincan This was fixed in https://github.com/primefaces/primeng/commit/41cdc69a97e8bac6e2ea344b8db4ee11afb5b481
