### ISSUE TITLE
Focused Dropdown Disable Selection via Keyboard to enable navigating a form with WASD Keys

### ISSUE THREAD

**Issue by monsterrave** [primefaces/primeng#13166]
### Describe the feature you would like to see added

Is there a way to disable the keyboard support for printable characters, mainly letters?
I read that in the past, this feature was not available at first.

### Describe the solution you'd like

I want to suppress, that an option gets selected when typing any letter. The reason for this to me is, that i want to have a feature that a User can navigate a form with columns by using the keys WASD. 

In the past there has been a pull request for that, but sadly was denied back then. #4191

### Describe alternatives you have considered

I tried something like this, but the problem is, that i have a directive bound to a parent component, that listens for key strokes and does stuff then.

```
const el = this.dropdown.nativeElement.querySelector('.ui-helper-hidden-accessible');
    el.addEventListener(
      'keydown',
      (event: KeyboardEvent) => {
        event.stopPropagation();
      },
      { capture: true }
    );
```

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
