### ISSUE TITLE
Calculation of CSS top position for Autocomplete dropdown

### ISSUE THREAD

**Issue by httpdigest** [primefaces/primeng#1316]
Currently, the CSS `top` property of the dropdown in the _Multiselect_ component is correctly computed as a negative offset when it will not fit into the viewport below the text input field.
However, for the _Autocomplete_ component, this does not happen.
It would be nice, if for the Autocomplete component, this also worked.

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/VZbdZfQ7SuTV87tTkbYR
