### ISSUE TITLE
Calling Table.filter with matchmode = 'equals' doesn't work when value is empty string or null

### ISSUE THREAD

**Issue by AlejandroFlorin** [primefaces/primeng#13168]
### Describe the bug

When calling table.filter, if you pass an empty string or null for the value parameter with matchmode = 'equals', it doesn't filter the records to only those that have an empty string or null for the passed field. Instead, the table is not filtered at all.

### Environment

Dev Machine:
Windows 11
Visual Studio 2019

### Angular version

15.2.8

### PrimeNG version

15.4.1

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Steps to reproduce the behavior

- Add table TestTable to a component
- Bind records to the table with some records having non-empty strings, some having an empty string and some having a null for field TestField
- Call:
`this.TestTable.filter('', 'TestField', 'equals')`
`this.TestTable.filter(null, 'TestField', 'equals')`

### Expected behavior

The table should be filtered to only those records that have an empty string or null for the TestField when making the calls

Instead, the table is not filtered at all for either call.

**Comment by AlbaSS18** [comment]
Hello, do you resolve this problem? I need the same.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
