### ISSUE TITLE
As the scroll remains in the top, the last rows of data are not automatically scrolled on less data.(approx 20  rows)

### ISSUE THREAD

**Issue by SinhaSmita95** [primefaces/primeng#13164]
### Describe the bug

**Pre-req**
Contain less data (approx 20 data).
**case 1**
Step1: Change the index value this.sc.scrollToVirtualIndex(18) in reset1(); --> this.sc.scrollToVirtualIndex(19); 
step2: Click on "with Time out" button . 
Result: As the scroll remains in the top, the last rows of data are not automatically scrolled on less data.

**case 1**
Step1: Change the index value this.sc.scrollToVirtualIndex(18) in reset(); --> this.sc.scrollToVirtualIndex(19); 
step2: Click on "with out Time out" button . 
Result: As the scroll remains in the top, the last rows of data are not automatically scrolled on less data.

### Environment

"primeng": "16.0.0"
https://stackblitz.com/edit/f5qvib-46rgcy?file=src%2Fapp%2Fdemo%2Ftable-virtual-scroll-demo.html,src%2Fapp%2Fdemo%2Ftable-virtual-scroll-demo.ts,src%2Fstyles.scss,package.json
![VirtualScrollssue1](https://github.com/primefaces/primeng/assets/135976761/78cfafe3-09ab-4014-a99e-151c2ab7398a)

### Angular version

16.0.0

### PrimeNG version

16.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

12.1.1

### Browser(s)

Chrome

### Steps to reproduce the behavior

**Pre-req**
Contain less data (approx 20 data).
**case 1**
Step1: Change the index value this.sc.scrollToVirtualIndex(18) in reset1(); --> this.sc.scrollToVirtualIndex(19); 
step2: Click on "with Time out" button . 
Result: As the scroll remains in the top, the last rows of data are not automatically scrolled on less data.

**case 1**
Step1: Change the index value this.sc.scrollToVirtualIndex(18) in reset(); --> this.sc.scrollToVirtualIndex(19); 
step2: Click on "with out Time out" button . 
Result: As the scroll remains in the top, the last rows of data are not automatically scrolled on less data.

### Expected behavior

Scrolling should be automatic for the last rows. The row will appear in the viewport as a result.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
