### ISSUE TITLE
Component: Menubar - Add .p-menuitem-link-active to item which contain children with active routes

### ISSUE THREAD

**Issue by rousek** [primefaces/primeng#13163]
### Describe the feature you would like to see added

I would like to highlight menu items which contain children (or their children contain children, etc) that have active `routerLink`.

My goal is to be able to highlight menu item `Users` when route is `/user/1` or `/user/2`. This is not currently possible AFAIK.

```
menuItems: MenuItem[] = [
  {
    label: 'Users',
    items: [
      {
        label: 'John Doe',
        routerLink: ['/user/1'],
      },
      {
        label: 'Jane Smith',
        routerLink: ['/user/2'],
      }
    ]
  }
];
```

### Describe the solution you'd like

I'd like to add a property to `MenuItem` which would set `[routerLinkActive]="'p-menuitem-link-active'"` on it even if it does not have `routerLink` itself.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
