### ISSUE TITLE
Tooltip displays vertically instead of repositioning

### ISSUE THREAD

**Issue by erincarignan** [primefaces/primeng#13169]
### Describe the bug

When a tooltip is placed on an element located close to the right edge of the browser, the tooltip doesn't properly reposition itself in another direction.  Instead, it uses the vertical space.
![image](https://github.com/primefaces/primeng/assets/12430262/0d29b473-2c36-4be5-b04e-d7cda7cf3164)

### Environment

No specific environment.

### Reproducer

https://stackblitz.com/edit/tveeaz-jciyna?file=src%2Fapp%2Fdemo%2Ftooltip-demo.html

### Angular version

15.2

### PrimeNG version

15.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Steps to reproduce the behavior

1. In the stackblitz sample, hover over the button.

### Expected behavior

Expected the tooltip to reposition to the left to display the contents correctly.

**Comment by docentYT** [comment]
This problem occurs in chrominium-based browsers. In firefox the tooltip displays correctly.
Firefox:
![obraz](https://github.com/primefaces/primeng/assets/63965954/b9cfdbcc-6219-4eba-b9e9-b82f652cf7ff)

**Comment by docentYT** [comment]
I have found a workaround for this problem. You need to set `min-width` to some value. The higher the value, the better the chance that the tooltip will work correctly on different page sizes and zooms. For me, 100px is sufficient.
```scss
::ng-deep .p-tooltip {
    min-width: 100px;
}
```

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Comment by Guigeek973** [comment]
Same issue in 2025 on chromium on v18
this workaround is so bad in term of UI : 
::ng-deep .p-tooltip {
    min-width: 100px;
}
