### ISSUE TITLE
Module '"primeng/utils"' has no exported member 'FilterUtils'

### ISSUE THREAD

**Issue by JohnMikel1990** [primefaces/primeng#13176]
### Describe the bug

After angular version 15 upgrade i am getting the issue related to "FilterUtils". Saying Module '"primeng/utils"' has no exported member 'FilterUtils'.

import {FilterUtils} from 'primeng/utils';  ------Module '"primeng/utils"' has no exported member 'FilterUtils'.
**Code:**
filterStatus(event: Switch, dt: Table): void {
    this.showErrorOnly = event.checked;
    if (event.checked) {
      dt.value = **FilterUtils.filter**(this.data, ['validation.status'], 'INVALID', 'contains');
    } else {
      dt.value = this.data;
    }
    dt.reset()
  }

Is there any alternate for doing filter without code changes. 

### Environment

**Package.json file:**

"private": true,
  "dependencies": {
    "@angular/animations": "15.2.9",
    "@angular/cdk": "15.2.9",
    "@angular/common": "15.2.9",
    "@angular/compiler": "15.2.9",
    "@angular/compiler-cli": "15.2.9",
    "@angular/core": "15.2.9",
    "@angular/forms": "15.2.9",
    "@angular/localize": "15.2.9",
    "@angular/material": "15.2.9",
    "@angular/platform-browser": "15.2.9",
    "@angular/platform-browser-dynamic": "15.2.9",
    "@angular/platform-server": "15.2.9",
    "@angular/router": "15.2.9",
    "@fullcalendar/core": "6.1.8",
    "@ngneat/dialog": "4.0.0",
    "@ngneat/transloco": "4.2.7",
    "@ngrx/effects": "15.4.0",
    "@ngrx/store": "15.4.0",
    "@ngrx/store-devtools": "15.4.0",
    "@popperjs/core": "^2.11.8",
    "angular-archwizard": "7.0.0",
    "bootstrap": "5.3.0",
    "chart.js": "4.3.0",
    "copy-webpack-plugin": "11.0.0",
    "core-js": "3.30.2",
    "file-saver": "2.0.5",
    "font-awesome": "4.7.0",
    "guid-typescript": "1.0.9",
    "hammerjs": "2.0.8",
    "immutable": "4.3.0",
    "intl": "1.2.5",
    "jquery": "3.7.0",
    "jsog-typescript": "1.0.0-1",
    "lodash": "4.17.21",
    "ngx-joyride": "2.5.0",
    "normalize.css": "8.0.1",
    "primeflex": "3.3.1",
    "primeicons": "6.0.1",
    "primeng": "15.4.1",
    "quill": "1.3.7",
    "rxjs": "7.8.1",
    "typescript": "4.9.5",
    "util": "^0.12.5",
    "xlsx": "0.18.5",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "15.2.8",
    "@angular/cli": "15.2.8",
    "@angular/language-service": "15.2.9",
    "@ngrx/schematics": "15.4.0",
    "@rollup/plugin-commonjs": "25.0.0",
    "@rollup/plugin-node-resolve": "15.1.0",
    "@types/jasmine": "4.3.2",
    "@types/jasminewd2": "2.0.10",
    "@types/node": "20.2.5",
    "@typescript-eslint/eslint-plugin": "5.59.9",
    "@typescript-eslint/parser": "5.59.9",
    "codelyzer": "6.0.2",
    "eslint": "8.42.0",
    "jasmine-core": "5.0.0",
    "jasmine-spec-reporter": "7.0.0",
    "karma": "6.4.2",
    "karma-chrome-launcher": "3.2.0",
    "karma-cli": "2.0.0",
    "karma-coverage-istanbul-reporter": "3.0.3",
    "karma-jasmine": "5.1.0",
    "karma-jasmine-html-reporter": "2.1.0",
    "karma-junit-reporter": "2.0.1",
    "karma-scss-preprocessor": "4.0.0",
    "prettier": "2.8.8",
    "replace-in-file": "7.0.1",
    "rollup": "3.24.0",
    "source-map-explorer": "2.5.3",
    "ts-node": "10.9.1",
    "webpack": "5.82.0",
    "webpack-bundle-analyzer": "4.9.0"
  }
}

### Angular version

15

### PrimeNG version

15.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.18.1

**Comment by cetincakiroglu** [comment]
Filter utils have been removed since PrimeNG 11.0.0-rc.2 and it's not exported or documented anywhere in the PrimeNG. Closing the issue since it is not valid.
