### ISSUE TITLE
AutoComplete Advanced can not type Chinese, but Multiple can

### ISSUE THREAD

**Issue by zhangsanshi** [primefaces/primeng#1317]
The test page is
[http://www.primefaces.org/primeng/#/autocomplete](http://www.primefaces.org/primeng/#/autocomplete).
I also test copy word(like: 我是小明) and It's work.

describe:
When I type the word，the Input method will show and hide in a very short time, so I can't select any Chinese.

**Comment by cagataycivici** [comment]
Duplicate of #1318
