### ISSUE TITLE
Chinese support for AutoComplete

### ISSUE THREAD

**Issue by anchenlee** [primefaces/primeng#1318]
When I type "病理"  and it will show like " bbibinbingbing'lbing'li病理" in Basic and Advanced, but it's ok in Multiple, How to solve this problem?

**Comment by zxc19890923** [comment]
me to

**Comment by peterzhb** [comment]
Does it support Chinese now? I typed in both Single and Multiple and there is no reaction.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
