### ISSUE TITLE
Tooltip in PrimeNG 16 stopped working in Chrome

### ISSUE THREAD

**Issue by olegkap** [primefaces/primeng#13191]
### Describe the bug

Looks like this problem only occurs in Chrome browsers
If you go to documentation site:
https://primeng.org/tooltip

And try to see example of tooltip then tooltip will not show in any example and all you see now is this error in the console debug window:

"polyfills.592a92282d9cd7cd.js:1 Uncaught Cannot append null to [object HTMLDivElement]"

### Environment

Chrome: Version 114.0.5735.110 (Official Build) (64-bit)
Angular version 16
PrimeNG version 16

### Angular version

16.0.0

### PrimeNG version

16.0.0

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

v18.15.0

### Browser(s)

Chrome, Version 114.0.5735.110 (Official Build) (64-bit)

### Steps to reproduce the behavior

1. Open Chrome Browser
2. Go to https://primeng.org/tooltip
3. Try to hover or go into any examples that show tooltip

### Expected behavior

Tooltip should be shown as expected

**Comment by tonymporter** [comment]
Same error here, just upgraded.

**Comment by gucal** [comment]
Fix commit - https://github.com/primefaces/primeng/commit/039f3e215c810e2b9d8924b50c9942151b0ca183

You can use `appendTo="body"`
