### ISSUE TITLE
Table: Document possibility to pass function as dataKey

### ISSUE THREAD

**Issue by AndreasHae** [primefaces/primeng#13196]
### Describe the bug

I just spent an hour investigating our internal use of the p-table component because we are passing a function to its dataKey property, while both the documentation and the Typescript type indicate that only string values are allowed.

Both the type and the docs should indicate that it is possible to pass a function instead of the property path.

### Environment

?

### Angular version

15.2.9

### PrimeNG version

15.3.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.13.2

**Comment by perceptron8** [comment]
In our use case, we are iterating over `SomeEnum` and then do row expansion using `Map<SomeEnum, BoringDetails[]>`. Sadly, it's impossible to use `rowexpansion` without a `dataKey` (expansion leads to `Error: dataKey or groupRowsBy must be defined to use row expansion`), yet... enum doesn't have any `dataKey` that could be used (however it is itself perfectly valid dataKey!).

We would happily use `dataKey="identity"` (assuming `identity = v => v`) if that was possible - currently we are  forced to use `dataKey="$any(identity)"` and pray that the implementation doesn't change. It seems that this change would require only declared type change, as it `ObjectUtils.resolveFieldData` is being used under the hood.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Comment by perceptron8** [comment]
@mehmetcetin01140 It took me about 3 minutes to check if this was fixed. It was not which you can verify by looking at https://github.com/primefaces/primeng/blob/18.0.0/packages/primeng/src/table/table.ts#L498.

Please do reopen this issue instead of forcing us to create a new one. You had plenty of time to at least triage this...

Thanks!

**Comment by perceptron8** [comment]
I've started https://github.com/orgs/primefaces/discussions/3248.
