### ISSUE TITLE
Tabs are breaking when you try them with [selected] and (onChange) used togather

### ISSUE THREAD

**Issue by jignesh-techvasu** [primefaces/primeng#1319]
@Mrtcndkn  This is related to  #1242 .

Thank your for your attention. I have done both changes as you suggested on #1242. I updated repo. However, issue is still persisting. I am not able to open the issue there. Hence creating new issue.

One interesting fact is that issue comes on only when you use onChange handler

<p-tabView (onChange)="onTabChange($event)">

This is strange! To reproduce, please follow exactly below steps :

Open the page : http://localhost:8080/#/tabview
Click on second tab: "Godfather II"
Click on "Activate Tab 1" button (You see nothing happens!!)
Click on "Activate Tab 3" button (You see now we have tab2 and tab3 active togather!)

If you follow exact above steps, you will surely get it reproduced.

Thank you for your help and all great work.

**Comment by Mrtcndkn** [comment]
You can do it with local template variables or another solution is that using event.index.
The problem with this is you are changing value with buttons and tabs when you can anything without using tabs you should update your value here try this:

html
` <p-tabView (onChange)="onTabChange($event)">
        <p-tabPanel header="Godfather I" leftIcon="fa-calendar" [selected]="selectedTab==0">
            The story begins as Don Vito Corleone, the head of a New York Mafia family, overseeshis daughter's wedding. His beloved son ichael has just come home from the war, but does not intend to become part of his father's business. T hrough Michael's life the nature of the family business becomes clear. The business of the family is just like the head of the family, kind and benevolent to those who give respect, but given to ruthless violence whenever anything stands against the good of the family.
        </p-tabPanel>
        <p-tabPanel header="Godfather II" rightIcon="fa-print" [selected]="selectedTab==1">
            Francis Ford Coppola's legendary continuation and sequel to his landmark 1972 film, The_Godfather parallels the young Vito Corleone's rise with his son Michael's spiritual fall, deepening The_Godfather's depiction of the dark side of the American dream. In the early 1900s, the child Vito flees his Sicilian village for America after the local Mafia kills his family. Vito struggles to make a living, legally or illegally, for his wife and growing brood in Little Italy, killing the local Black Hand Fanucci after he demands his customary cut of the tyro's business. With Fanucci gone, Vito's communal stature grows.
        </p-tabPanel>
        <p-tabPanel header="Godfather III" leftIcon="fa-bell-o" rightIcon="fa-bookmark-o" [selected]="selectedTab==2">
            After a break of more than  15 years, director Francis Ford Coppola and writer Mario Puzo returned to the well for this third and final story of the fictional Corleone crime family. Two decades have passed, and crime kingpin Michael Corleone, now divorced from his wife Kay has nearly succeeded in keeping his promise that his family would one day be completely legitimate.
        </p-tabPanel>
    </p-tabView>

    <div>
        <button (click)="activateTab(0)">Activate Tab 0</button>
        <button (click)="activateTab(1)">Activate Tab 1</button>
        <button (click)="activateTab(2)">Activate Tab 2</button>
    </div>`

ts

`onTabChange(event) {
        this.msgs = [];
        this.msgs.push({severity:'info', summary:'Tab Expanded', detail: 'Index: ' + event.index});
        this.activateTab(event.index);
    }

    activateTab(tabNumber) {
        this.selectedTab = tabNumber;
    }`

**Comment by jignesh-techvasu** [comment]
@Mrtcndkn Thank you for the work around. It will keep me moving forward as of now.

However, just thinking about betterment of prime ui , don't you think there is something need to be enhanced in prime tab logic ? I understand when you mentioned that variable need to assigned in "onTabChange". However, please consider that if we don't provide (onChange) at all, the same scenario works just fine.
