### ISSUE TITLE
Component: InputMask

### ISSUE THREAD

**Issue by guillaume-f** [primefaces/primeng#13202]
### Describe the bug

When the InputMask component is used with a specific mask AND the property unmask is set to true
each time the field is focus/blur, an event is triggered and the valueChanges of Angular is fired even if the value is not modified

=> no event should be triggered if the value of the field has not been modified

### Environment

Angular : 14.2.12
Primeng : 14.2.3
Browser : ALL

### Reproducer

https://stackblitz.com/edit/github-ejhueh-qf6pvk?devToolsHeight=33&file=src%2Fapp%2Fapp.component.html

### Angular version

14.2.12

### PrimeNG version

14.2.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.21.3

### Browser(s)

ALL

### Steps to reproduce the behavior

Open the console and focus/blur input without make any change

### Expected behavior

No event should be triggered if the value of the field has not been modified

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
