### ISSUE TITLE
Component: Chips

### ISSUE THREAD

**Issue by ian-bolton** [primefaces/primeng#13208]
### Describe the bug

When using dictation and saying 'new line' or 'new paragraph' the tag isn't created as it would be if you hit return on the keyboard. It seems to create a second version of the text already entered on iOS

### Environment

iOS and Android. Works with Windows voice assistant. Tested on https://primeng.org/chips on these platforms as well and is an issue there as well as local environment

### Angular version

15.1.4

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.20.0

### Steps to reproduce the behavior

1. Go to https://primeng.org/chips
2. Click in to create first chip
3. Enable dictation
4. Speak
5. Say 'new line' or new 'paragraph'
6. Click away from input to see final text

### Expected behavior

No chip created and possibly duplicated text

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Comment by ian-bolton** [comment]
No problem, thanks for responding
