### ISSUE TITLE
Component: Tooltip does not appear

### ISSUE THREAD

**Issue by Valera1980** [primefaces/primeng#13217]
### Describe the bug

There is not any tooltip when the directive pTooltip is added to input. You can see the error in console - Uncaught Cannot append null to [object HTMLDivElement]

### Environment

Angular 16.1.0

### Reproducer

https://codesandbox.io/s/fphh65

### Angular version

16.1.1

### PrimeNG version

16.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Browser(s)

Version 114.0.5735.134 (Official Build) (64-bit)

### Steps to reproduce the behavior

1. import { TooltipModule } from 'primeng/tooltip' in the module
2. add "pTooltip" to any input
3. hover on input
4. the tooltip does not appear
5. open F12 - Uncaught Cannot append null to [object HTMLDivElement]

### Expected behavior

1. import { TooltipModule } from 'primeng/tooltip' in the module
2. add "pTooltip" to any input
3. hover on input
4. tooltip appears
5. open F12 - there is not error

**Comment by ynixt** [comment]
> In version 16.0.1 https://github.com/primefaces/primeng/releases/tag/16.0.1 is fixed

I'm on version 16.0.1 but the tooltip still not working when the tooltip is on a dialog.

**Comment by cetincakiroglu** [comment]
Both issues are fixed now, closing the issue and the fix will be available for the 16.0.2 this week
