### ISSUE TITLE
ToolTip doesn't show

### ISSUE THREAD

**Issue by jhcpeixoto** [primefaces/primeng#13212]
### Describe the bug

Get this error in console:

- **polyfills.js:9383 Uncaught Cannot append null to [object HTMLDivElement]**

### Environment

Local Setup, Mac OS
Angular CLI: 16

### Angular version

16.0.4

### PrimeNG version

16.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.1

### Browser(s)

Brave

**Comment by jhcpeixoto** [comment]
This issue only happend when updated to last version of primeng if i use [16.0.0-rc.2](https://github.com/primefaces/primeng/releases/tag/16.0.0-rc.2) it work perfect

**Comment by gucal** [comment]
Hi,

This issue is fixed in https://github.com/primefaces/primeng/commit/039f3e215c810e2b9d8924b50c9942151b0ca183
