### ISSUE TITLE
MenuModule import hard crash

### ISSUE THREAD

**Issue by Zukzuk** [primefaces/primeng#13226]
### Describe the bug

Importing the MenuModule into a module causes a hard crash with error:
Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Cannot resolve type entity SafeHtmlPipe to symbol

### Environment

Development environment in a default NX monorepo, in the host application.

### Reproducer

https://stackblitz.com/edit/ugkm3n?file=package.json

### Angular version

16.0.0

### PrimeNG version

16.0.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Steps to reproduce the behavior

1. Create an angular module
2. Import the MenuModule in your app module
3. Error will occur

See stackblitz error on startup

### Expected behavior

Should be able to import the MenuModule into my app module
<img width="2030" alt="Screenshot 2023-06-18 at 21 31 12" src="https://github.com/primefaces/primeng/assets/329382/6d2dd52a-7108-4511-a208-ec2ce378d07e">

**Comment by jhcpeixoto** [comment]
Already fixed on https://github.com/primefaces/primeng/issues/13218

**Comment by cetincakiroglu** [comment]
Closing the issue since it's fixed in https://github.com/primefaces/primeng/issues/13218
