### ISSUE TITLE
Compiler error: [p-autoComplete] Argument of type 'Event' is not assignable to parameter of type 'MouseEvent'

### ISSUE THREAD

**Issue by igordanilovski** [primefaces/primeng#13227]
### Describe the bug

In this specific case:
`<p-autoComplete
        #autoComplete
        styleClass="p-custom-autocomplete default-input-field"
        [(ngModel)]="selectedPlaceShownText"
        [suggestions]="placesPredictions!"
        (onSelect)="selectPlace($event)"
        (onClear)="closeDropdown()"
        (completeMethod)="searchPlaces($event)"
        (onFocus)="autoComplete.handleDropdownClick($event)"`
        
When compiling the app, the compiler gives me the following error:
![image](https://github.com/primefaces/primeng/assets/39922564/3185ad8f-b128-4f93-95b5-cd360891dfee)

There is definitely something wrong with the package because here the param is Event (autocomplete.d.ts)
![image](https://github.com/primefaces/primeng/assets/39922564/edf71f9b-d0d5-4bea-a20d-dab0d3bad614)

But the function requires MouseEvent as a param.
![image](https://github.com/primefaces/primeng/assets/39922564/8ee81273-3ca1-46ed-8fc5-16fa65e2c7d0)

I can't fix this issue and can't find any workaround so I think the team should look into this.

### Environment

Local.

### Angular version

16.1.0

### PrimeNG version

16.0.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Expected behavior

It should be changed to `Event`, probably... As I saw that was used in previous versions.

**Comment by volvachev** [comment]
Hi, I don't quite understand what the click method and the focus event have to do with it?
click !== focus - why you used click for that?

workaround for you case

```ts
(onFocus)="onFocus($event)"

public onFocus(event: Event) {
  this.autoCompleteRef.handleDropdownClick(event as MouseEvent);
}

```

**Comment by igordanilovski** [comment]
Thanks, I will try it, but I think that this is a bug on their side, I think. I have this code since Angular 15 and primeng 15 version, nothing is changed, but after installing primeng 16 I think this started as an issue. With initial release 16.0.0-rc1 there wasn't any issue, but after that this issue happened.

**Comment by alkthegit** [comment]
Hi,
maybe a little bit late, but for someone updating from 15 to 16 and higher.

This is relly not a bug of any kind in primeng@16.

This is just as simple as undocumented breaking change in `<p-autocomplete>` API, and it's relly annoying while updating to v16 not to be able to find it on changelog page.

```TypeScript
// in v15 just emitting selected option
this.onSelect.emit(option);
```

```TypeScript
// in v16 there is a dedicated interface for the event
export interface AutoCompleteOnSelectEvent {
    /**
     * Browser event.
     */
    originalEvent: Event;
    /**
     * Selected value.
     */
    value: any;
}
```

Even more strange that this issue marked as resolved bug in the changelog.

Primeng is a great library, but it definitely lacks some accuracy regarding migration details.
