### ISSUE TITLE
API: Difference between LazyLoadEvent and LazyLoadMeta

### ISSUE THREAD

**Issue by dscalzi** [primefaces/primeng#13228]
### Describe the bug

There are two interfaces, LazyLoadMeta and LazyLoadEvent. Meta seems to be more up to date and accurately represent the data that is emitted, especially in regard to the `filters` property.

What is the use of LazyLoadEvent? Perhaps it should be deprecated/removed?

### Environment

N/A

### Angular version

N/A

### PrimeNG version

master

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

N/A

### Steps to reproduce the behavior

Compare
src\app\components\api\lazyloadevent.ts
src\app\components\api\lazyloadmeta.ts

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
