### ISSUE TITLE
p-inputNumber: value is a string when entering "-"

### ISSUE THREAD

**Issue by ahelmel** [primefaces/primeng#13239]
### Describe the bug

When entering the "-" sign the value is a string and not null. When the component loses its focus the content is removed and the value is null. When entering a valid number the type of value is number. But as long as the user does not leave the p-inputNumber component the value is a string => "-".

Can be reproduced: https://stackblitz.com/edit/kem2hr
1. Enter "-" sign in the p-inputNumber
2. Do not leave the input => the value is "-", wrong
3. After entering a number like 5 => the value is -5, correct

In the case of an invalid value the input's value should be null. The value should never be a string.

### Environment

"primeng": "16.0.2",
"primeng": "15.3.0",
"@angular/*": "^16.0.0",

### Reproducer

https://stackblitz.com/edit/kem2hr

### Angular version

16

### PrimeNG version

15.3.0, 16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.0.0

### Browser(s)

Chrome

**Comment by lothern** [comment]
I've encountered this issue in my project as well.

**Comment by jbuesche** [comment]
We also have the problem in our project. Is there a workaround?

**Comment by schlagi123** [comment]
We also have the same problem in our project.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
