### ISSUE TITLE
OverlayPanel: Positioning with narrow target element

### ISSUE THREAD

**Issue by burkaysucu** [primefaces/primeng#13231]
### Describe the bug

When the target is narrow, OverlayPanel component is rendered to the right. Below screenshots are taken from https://primeng.org/overlaypanel after the target elements' texts are updated to be a single character via DevTools. Also, `px-0` class is added to the button and `w-10rem` class is removed from the span's parent.

These look good:

![image](https://github.com/primefaces/primeng/assets/45235622/9d8832f6-4e06-44f9-b9de-b299dd3a2411)
![image](https://github.com/primefaces/primeng/assets/45235622/c92e1f38-5303-4abe-a985-df0118bca3ef)

These need alignment:
![image](https://github.com/primefaces/primeng/assets/45235622/c6be3a68-1995-4805-bc0f-9b6c51e77d54)
![image](https://github.com/primefaces/primeng/assets/45235622/7eb659e3-2b83-4ba1-8ef0-3c499549be33)

### Environment

Latest PrimeNG. Observable on documentation page, too.

### Angular version

16.1.0

### PrimeNG version

16.0.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
