### ISSUE TITLE
Table: calling scrollToVirtualIndex in the bottom of the last page can cause rows to disapear.

### ISSUE THREAD

**Issue by shyallegro** [primefaces/primeng#13233]
### Describe the bug

I've implemented a search on a virtual table, it will scroll to the element the user is searching for.
when the line is at the bottom of the table, scrollToVirtualIndex won't be able to actually scroll to that line and will stop on the top of the last "page".
clicking on the table cause all the lines to disappear, I guess since virtual scroll to marks the wrong lines in view.

### Environment

development on windows/Linux reproduce on both production build and dev server

### Angular version

15.2.8

### PrimeNG version

15.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.14

### Browser(s)

chrome latest, firefox latest

**Comment by cetincakiroglu** [comment]
Hi, 
Could you please share a Stackblitz reproducer?

**Comment by omnight** [comment]
@cetincakiroglu 

I am not sure if my issue is the exact same one, but it sounds very similar. Calling ScrollToVirtualIndex when there is not enough items in the table to display the scrollbar produces unexpected behaviour where the rows above the scroll index are made invisible and unreachable. 

Adding more items to the list to make the scroll bar appear makes the problem go away.

Here is reproducable minimal example

https://stackblitz.com/edit/v31kqe?file=src%2Fapp%2Fdemo%2Ftable-virtual-scroll-demo.ts
