### ISSUE TITLE
Component: ToolTip

### ISSUE THREAD

**Issue by Dale-Western** [primefaces/primeng#13238]
### Describe the bug

ToolTip no longer supports string as an input for "tooltipPosition" this also breaks "tooltipOptions"

### Environment

windows

### Angular version

16.1.2

### PrimeNG version

16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.14.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

in TS file
tooltipDirection = 'left';

in HTML
<i class="pi pi-info-circle" tabindex="0" tooltipEvent="focus" pTooltip="blah blah" tooltipPosition="{{tooltipDirection}}"></i>

error message via VSCode
Type 'string' is not assignable to type '"left" | "right" | "top" | "bottom" | undefined'.ngtsc(2322)

this happens for other attributes 

### Expected behavior

type should be written like this
"left" | "right" | "top" | "bottom" | string | undefined

**Comment by Kisters-BS** [comment]
I think this is a good change. Allowing string would make the the string literal types needless. Why not add the type to your variable?
let tooltipDirection: "left" | "right" | "top" | "bottom" = 'left';

**Comment by Dale-Western** [comment]
This does not fix the problem, the angular compiler still throws the same error

error TS2322: Type 'string' is not assignable to type '"left" | "right" | "top" | "bottom" | undefined'.

**Comment by SoyDiego** [comment]
@Dale-Western I did a [PR](https://github.com/primefaces/primeng/pull/13285) solving the problem. Adding `"left" | "right" | "top" | "bottom" | string | undefined` was enough to fixed it (just like the other properties have it, for example `tooltipEvent`).
If you look the PR, you will see screenshots :)
Now we should wait if the solution is correct for the PrimeNG team and if they approve it.

**Comment by cetincakiroglu** [comment]
Fixed in https://github.com/primefaces/primeng/pull/13285
