### ISSUE TITLE
Dynamic Dialog: custom header template

### ISSUE THREAD

**Issue by dougmbarcellos** [primefaces/primeng#13236]
### Describe the feature you would like to see added

Please, reopen this pull request for improvements in the Dynamic Dialog component:

https://github.com/primefaces/primeng/pull/12068

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
