### ISSUE TITLE
Component: Title

### ISSUE THREAD

**Issue by RobertoVallado** [primefaces/primeng#13243]
### Describe the bug

Typo on the warnings as a result of using deprecated 'responsive' property

### Environment

Backend: C# (ASP.NET Core)
The backend of application is built using C# with the ASP.NET Core framework

Frontend: Angular
The frontend of application is developed using Angular

### Angular version

14.0.5

### PrimeNG version

14.2.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
