### ISSUE TITLE
Component: Title

### ISSUE THREAD

**Issue by mehmet-erkek** [primefaces/primeng#13240]
### Describe the bug

primeng componentlerin hepsinde bu ve buna benzer hataları alıyorum. olması gerektiği gibi kurulumu yaptım
![image](https://github.com/primefaces/primeng/assets/78926710/caf12f08-5886-43e4-8a84-43f5c989e102)

acaba panelde mi problem yaşıyorum dedim ve diğer componentlerde de böyle hata alıyorum 
![image](https://github.com/primefaces/primeng/assets/78926710/c9be8bf3-0f8e-4719-8b55-476841e04c73)

### Environment

Windows 11

### Angular version

15.0.0

### PrimeNG version

16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v18.13.0

### Browser(s)

Chrome 114.0.5735.134 (Resmi Derleme) (64 bit) Sürümü

### Steps to reproduce the behavior

yeni angular projesi oluştur
primeng yükle
primeflex yükle
style.css dosyasına importla
app.module.ts dosyasına  
import { CardModule } from 'primeng/card';
ekle 
html e card örneği yerleştir 
projeyi çalıştır

### Expected behavior

Önceki projemde sorunsuz çalışmıştı fakat şuan çalıştıramıyorum

**Comment by cetincakiroglu** [comment]
PrimeNG ve Angular versiyonlari senkronize sekilde gitmektedir. Angular 15 ile PrimeNG 16 kullanmaya calistiginiz icin bu hatayi aliyorsunuz. Angular 16 ile gelen guncellemeler, Angular 15 de kullanilan dependency versiyonlari kullanim disi birakmistir.

Cozum: Angular 15 + PrimeNG 15 kullanmak, veya Angular 16 + PrimeNG 16 kullanmaktir.
