### ISSUE TITLE
Component: MenuBar - should watch changes on MenuItems

### ISSUE THREAD

**Issue by javac9** [primefaces/primeng#13242]
### Describe the feature you would like to see added

Currently the MenuBar component provides a way for setting the `disabled` option on individual menu items. However, it's being considered only initially. If the property changes afterwards, the state of the MenuItem remains unchanged as the changes are not being watched.

### Is your feature request related to a problem?

It's related to a problem I'm currently having. I'm using the MenuBar to display some controls. One of them is to enable adding a new form group and when that happens, I want to disable this menu item until the form group completes its mission (fill in and save new value). Otherwise user can continue clicking "Add new" and add more empty form groups.

Here's a StackBlitz example: https://stackblitz.com/edit/wztuwg?file=src%2Fapp%2Fdemo%2Fmenubar-template-demo.ts

### Describe the solution you'd like

In the provided example, changes to the property `isActionPending` should be observed. In that case the menu item would get disabled as long as the property has `true` value and get re-enabled as soon as it changes to `false`

### Describe alternatives you have considered

none

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
