### ISSUE TITLE
Problem with p-table and onFilter event.

### ISSUE THREAD

**Issue by tkachenkoyevhen** [primefaces/primeng#13241]
### Describe the bug

Hi there.

I met problem with **p-table** component and **onFilter** event. My custom component **table** has variable **tableConfig$** as **Behavior subject**. This variable has items and some table configuration properties.
Each time the filter is updating when I make request to BE and in response self-updating tableConfig$ variable, items and pagination properties. Accordingly occur re-rendering of template.

At the end I got a problem that **onFilter** event falls in eternal loop.

### Environment

angular
nodejs
typescript
primeng

### Angular version

15.1.2

### PrimeNG version

11.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.20.0

### Browser(s)

Chrome 114.0.5735.133

### Steps to reproduce the behavior

1. Create Behavior Subject variable for exemple `settings$: BehaviorSubject<TableSettings> = new BehaviorSubject({items, pagination, ...etc})`
2. At change filters do some http request on onFilter handler.
3. At response do self-update settings$ variable this.settings$.next({...this.settings$, items, pagination, ...etc})
4. In result get eternal loop

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
