### ISSUE TITLE
Growl : TypeError when adding to message array before the component is initialised.

### ISSUE THREAD

**Issue by jdpearce** [primefaces/primeng#1324]
primeng@1.0.0-rc.4

Create a component and add one control -

    <p-growl [value]="msgs"></p-growl>

Implement `OnInit` in the component as follows - 

    ngOnInit() {
      this.msgs.push({ severity: 'error', summary: 'summary', detail: 'error' });
    }

On loading the component this results in an error - 

    TypeError: Cannot read property 'style' of undefined

I'll accept that it may be arguable as to whether this is a bug or misuse of the component, but the error thrown is extremely opaque and it took me a while to realise it was being thrown by the Growl component.

**Comment by cagataycivici** [comment]
Where have you initialized msgs?

**Comment by jdpearce** [comment]
I left that out because it seemed like boilerplate. Full MyComponent class just looks like this -

    export class MyComponent implements OnInit {
      msgs: Message[] = [];

      ngOnInit() {
        this.msgs.push({ severity: 'error', summary: 'Alerts', detail: 'error' });
      }
    }

**Comment by cagataycivici** [comment]
Assigned to my colleague, I also expect this to work.
