### ISSUE TITLE
pKeyFilter stops Enter key from submitting form in Firefox

### ISSUE THREAD

**Issue by driftfox** [primefaces/primeng#13246]
### Describe the bug

If an input in a form has pKeyFilter="pint" on it, you can't submit the form just by pressing the Enter key.

This issue is identical to https://github.com/primefaces/primeng/issues/5931 but applies specifically to Firefox. It is not an issue in in Chrome 114.0.5735.134.

### Environment

An Angular application with forms

### Reproducer

https://stackblitz.com/edit/js7ac5?file=src%2Fapp%2Fdemo%2Fkey-filter-presets-demo.ts

### Angular version

15.2.1, 16.0.0

### PrimeNG version

15.2.0, 16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.1

### Browser(s)

Firefox 114.0.1 (64-bit)

### Steps to reproduce the behavior

1. Add a `<form>` element with a method bound to `(ngSubmit)`.
2. Add an `<input>` element with `pKeyFilter="pint"` inside the `<form>`.
3. View this page in Firefox.
4. Enter a value in the <input> and press Enter on the keyboard.
5. Notice that the method bound to `(ngSubmit)` is not called.

### Expected behavior

Pressing Enter should call the method bound to `(ngSubmit)`.

**Comment by driftfox** [comment]
For reference, the fix I'm introducing in this PR was originally added with c488091 and then later removed in eb3f8a4.

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primeng/pull/13247
