### ISSUE TITLE
Component: p-calendar

### ISSUE THREAD

**Issue by idanzror100** [primefaces/primeng#13249]
### Describe the bug

p-calendar popup  is open when i use it in modal screen

### Environment

![p-calendar FocusBug](https://github.com/primefaces/primeng/assets/87425879/4397df44-8536-4fc3-9a39-22e640541c8a)

### Angular version

16.0.2

### PrimeNG version

16.0.2

### Build / Runtime

Angular CLI App

### Language

ES6

### Node version (for AoT issues node --version)

0.0.0

### Browser(s)

all chrome versions

### Steps to reproduce the behavior

open modal screen with calendrer

### Expected behavior

calendrer popup need to be close

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
