### ISSUE TITLE
Component: Title

### ISSUE THREAD

**Issue by ylahav** [primefaces/primeng#13248]
### Describe the feature you would like to see added

Supporting RTL

### Is your feature request related to a problem?

Example - Carousel

icons are displayed in the opossite direction...

### Describe the solution you'd like

2 levels:
1. global configuration for RTL
2. on a specific component

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
