### ISSUE TITLE
Button: custom loading icon is not displayed

### ISSUE THREAD

**Issue by mohammadreza99** [primefaces/primeng#13250]
### Describe the bug

Custom loading icon is not displayed. from doc sample:

![image](https://github.com/primefaces/primeng/assets/35723634/a58d42e0-6444-4d6e-8131-6a022dd8e2e4)

also, the loading icon space break when the `iconPos` set to right.

![image](https://github.com/primefaces/primeng/assets/35723634/bebfeadd-641c-42e7-9396-86deb5af5fe8)

### Environment

windows

### Angular version

16

### PrimeNG version

16

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

**Comment by GiacomoDM** [comment]
Relates to #13345 and #13195

**Comment by SoyDiego** [comment]
Hi @mohammadreza99 @GiacomoDM  I did a PR here: https://github.com/primefaces/primeng/pull/13363
I don't know if the best solution but solves the problem. Now we should wait if PrimeNG Team approves.
