### ISSUE TITLE
Table: 'Swedish' language table column filter not working properly

### ISSUE THREAD

**Issue by yuvarajProl** [primefaces/primeng#13256]
### Describe the bug

In the header portion of the data table, there is a "Name" column. In the column-row data, there are various values. 

Example: The words "Activation System" in the first row are written in the English language, and "ÅctivÅtion system" in the second row is written in the Swedish language.

When we attempt to filter the "Name" column using the key "act," both the "English" and the "Swedish" values are present in the filtered result.

I want the data table's specific key language filter result.

Please provide us with a solution as soon as possible.

Screen shots:

![test1](https://github.com/primefaces/primeng/assets/111727865/43d3042b-71ad-4306-b5eb-0e2dc2cfac04)

![test2](https://github.com/primefaces/primeng/assets/111727865/e92d0b80-588e-4066-a808-ed451ee5027a)

![test3](https://github.com/primefaces/primeng/assets/111727865/a212ee17-76e2-4c31-9a58-60339fc96de4)

Example workspace url:  https://stackblitz.com/edit/tccl1c

### Environment

Angular: 14.1.1,
Primeng: 14.1.2,
Node: 14.16.0

### Angular version

14.1.1

### PrimeNG version

14.1.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.16.0

### Expected behavior

I want the data table's specific key language filter result.

**Comment by yuvarajProl** [comment]
Dear Team,

Could you please assist me with this? I've been waiting for a while, but this problem still hasn't been fixed.

Thanks.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
