### ISSUE TITLE
Carousel: does not allow scrolling vertically on mobile

### ISSUE THREAD

**Issue by Xriuk** [primefaces/primeng#13266]
### Describe the bug

When scrolling the page on mobile, if the touch lands on the carousel it is not possible to scroll further down, even if the scroll is vertical.
This can be seen directly on the [components page of the site](https://primeng.org/carousel).

### Environment

...

### Reproducer

https://primeng.org/carousel

### Angular version

...

### PrimeNG version

...

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

...

### Steps to reproduce the behavior

- Go to: https://primeng.org/carousel
- Try scrolling vertially by pressing on the carousel and keeping the finger down

### Expected behavior

The carousel should allow scrolling vertically while "blocking" the user, only when it scrolls horizontally

**Comment by ChristoSmuts** [comment]
I am experiencing the same issue. 

In my testing it seems to not do this on the iPhone SE (2022) with Chrome browser. But with the Samsung S23 Ultra using Chrome the carousel stops the page from scrolling vertically when the touch is initiated on the carousel, but when the touch starts off the carousel the page scroll behaves as expected.

**Comment by Xriuk** [comment]
I tried on Android on Firefox and Chrome

**Comment by ChristoSmuts** [comment]
I found this: https://github.com/primefaces/primeng/issues/11607#issuecomment-1163017276 and it worked for me.

Added this to my TS file:

import { Carousel } from 'primeng/carousel';

constructor() {
    Carousel.prototype.onTouchMove = () => { };
}

I have not stress tested this yet, but so far it seems to do the trick.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Comment by MarcoOrts** [comment]
Hello everyone,
unfortunately this is still an active issue in 19.1.4

Is there any solution? The one above did not work for me.

**Comment by Michaelvsk** [comment]
Hi,
the problem still exists with PrimeNG v20 and v21. Please reopen.

@MarcoOrts 
We use this workaround https://github.com/primefaces/primeng/issues/11607#issuecomment-3144015825 and it works fine, because both, vertical page scrolling and horizontal scrolling through carousel elements are supported.
