### ISSUE TITLE
multiselect  dropdown is not auto postioning 

### ISSUE THREAD

**Issue by AravindThinkpalm** [primefaces/primeng#13267]
### Describe the bug

Dropdown is not aligned to top when it is opened at bottom of a div ,the dropdwon apperars at below 

### Environment

angular local environment

### Angular version

^15.0.3

### PrimeNG version

^15.1.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

12.22

### Browser(s)

chrome

### Steps to reproduce the behavior

when dropdown is placed at bottom, the drodpwn popup is not autopostioned

### Expected behavior

if no space at bottom then popup should  be positioned at top

**Comment by AntonKorn** [comment]
This also happens when the dropdown is at the very right of the page. Looks like it happens because target and relative elements are the same one

https://github.com/primefaces/primeng/blob/f8c7f537543cfde8b35bbeea355a5dc7645c3d3b/src/app/components/dom/domhandler.ts#L148

**Comment by cetincakiroglu** [comment]
Hi,

Could you please share a Stackblitz example?
