### ISSUE TITLE
Lower RxJS peer dep version

### ISSUE THREAD

**Issue by jameyg42** [primefaces/primeng#13262]
### Describe the feature you would like to see added

PR#13069 upped the peer dep version of RxJS (components/package.json) to ^7.8.1.  Does it actually need to be that high (wouldn't it be better to be aligned with Angular@16's own ^7.4.0 range?)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
