### ISSUE TITLE
when multiple p-dialog are open, key 'Escape' closes only the last p-dialog opened

### ISSUE THREAD

**Issue by flaviosantos3** [primefaces/primeng#13275]
### Describe the feature you would like to see added

    bindDocumentEscapeListener() {
        const documentTarget: any = this.el ? this.el.nativeElement.ownerDocument : 'document';

        this.documentEscapeListener = this.renderer.listen(documentTarget, 'keydown', (event) => {
            if (event.which == 27) {
                if (ZIndexUtils.getCurrent() == this.container.style.zIndex) {
                    this.close(event);
                }
                
            }
        });
    }

### Is your feature request related to a problem?

When i open multiple p-dialog, and press key Esc, all the p-dialog are closed

**Comment by LoaderB0T** [comment]
I can confirm we are having the same issue with primeng version 17.3.3

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
