### ISSUE TITLE
TabView: Button in TabPanel-header cannot select different tab

### ISSUE THREAD

**Issue by mbausche** [primefaces/primeng#13276]
### Describe the bug

We have a tabPanel with a Button on tab2. If the user clicks this button we don't want to switch to tab2 but switch to tab 1. 
This is done by setting the activeIndex = 0. But the TabView is still switching to panel at index 1

(This is a simplified use case)

### Environment

Windows 11/64 Bit

### Reproducer

https://stackblitz.com/edit/usaagv

### Angular version

15.2.9

### PrimeNG version

15.4.1

### Build / Runtime

TypeScript

### Language

ALL

### Node version (for AoT issues node --version)

16.20.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

Click on "Tab 1 (Working)" Application is switching to tab 1.
Click on "Tab 1 (Not Working)" Application is switching to tab 2.

### Expected behavior

Click on "Tab 1 (Not Working)" should switch to "Tab 1"

**Comment by tknkrtl** [comment]
`<p-tabView id="board-tab" [(activeIndex)]="activeIndex"> ....`

` this.activeIndex = this.tabs.length - 1 - 1 < 0 ? 0 : this.tabs.length - 1 - 1;`

setting activeIndex doesn't switch the active tab also it looks like component activates multiple tabs as selected tab and gives weird css border under their headers

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
