### ISSUE TITLE
Component: Autocomplete component

### ISSUE THREAD

**Issue by harishmp** [primefaces/primeng#13271]
### Describe the bug

Autocomplete component not handling long values(long chip values getting cut off) when multiple mode is used

### Environment

Angular local environment

### Angular version

14.2.12

### PrimeNG version

14.0.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.19.3

### Steps to reproduce the behavior

Use the autocomplete component and then set the [multiple]="true".

![image](https://github.com/primefaces/primeng/assets/32120845/8b31d0b1-24d4-41e0-9ba7-69f180bbb848)

### Expected behavior

Long chip value should be visible

**Comment by SoyDiego** [comment]
Hi @harishmp, you can solve the problem adding `fit-content` to the class `p-autocomplete-token`

![imagen](https://github.com/primefaces/primeng/assets/19764334/799a375f-2d40-49e5-b0cf-aab128b7a934)

I have created a PR with the solution to fix the problem. We will see If PrimeNG Team accept the solution, if not you can solve by yourself adding the class in your CSS :)

**Comment by cetincakiroglu** [comment]
Fixed in #13271
