### ISSUE TITLE
Inplace: Close icon customization variabe + input mismatch

### ISSUE THREAD

**Issue by BrettSmithNZ** [primefaces/primeng#13277]
### Describe the bug

setting closeIcon on inplace component has no effect.

Looking at https://github.com/primefaces/primeng/blob/master/src/app/components/inplace/inplace.ts

it seems that the template references ngIf="icon":
`      <ng-container *ngIf="closable">
                    <button *ngIf="icon" type="button" [icon]="icon" pButton (click)="onDeactivateClick($event)"></button>
                    <button *ngIf="!icon" type="button" pButton [ngClass]="'p-button-icon-only'" (click)="onDeactivateClick($event)">
                        <TimesIcon *ngIf="!closeIconTemplate" />
                        <ng-template *ngTemplateOutlet="closeIconTemplate"></ng-template>
                    </button>
                </ng-container>`

while the component has:

`  /**
     * Icon to display in the close button.
     * @group Props
     */
    @Input() closeIcon: string | undefined;`

### Environment

Good sized office, lighting could be better. mid level dell laptop, multiple 4k monitors.

### Angular version

15.1.0

### PrimeNG version

15.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14.2

### Browser(s)

Microsoft Edge

**Comment by SoyDiego** [comment]
Hi @BrettSmithNZ I have checked the problem and you are right.
I did a PR here: https://github.com/primefaces/primeng/pull/13291 that solve the problem.
Now we should wait if the PrimeNG Team approve it :)

**Comment by cetincakiroglu** [comment]
Fixed in #13291
