### ISSUE TITLE
Calendar: DisabledDays also disables months starting with disabled days

### ISSUE THREAD

**Issue by paniclabde** [primefaces/primeng#13278]
### Describe the bug

When I disable days for the calendar input it effects the month selection as well what is probably not intended behaviour.

### Environment

Windows 10 22H2
node 18.12.1
npm 9.2.0
vscode 1.79.2

### Reproducer

https://stackblitz.com/edit/primeng-calendar-demo-ehjwyn?file=src%2Fapp%2Fapp.component.html

### Angular version

14.2.12

### PrimeNG version

14.2.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.1

### Browser(s)

Firefox 114.0.2

### Steps to reproduce the behavior

1. Disable all days except monday via disabledDays property on calendar control
2. Click in input field to open calendar control
3. Switch to month selection
4. Only months starting with a monday are selectable

### Expected behavior

All months should be selectable, as disabledDays should not affect the month selection.

**Comment by Adhocfan** [comment]
The same is happening with Years that start with the same disabledDays.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
