### ISSUE TITLE
ContextMenu: onHide in ContextMenu doesn't work as expected

### ISSUE THREAD

**Issue by ova2** [primefaces/primeng#13289]
### Describe the bug

The **p-contextMenu** has an "onHide" close callback. Unfortunately, it does not really work as expected with PrimeNG 15.x, at least not for one specific case. The "onHide" callback is only called in cases if we left-click outside of the context menu or pick something with left-click from the context menu. In case when we have a context menu already opened and we try to open a context menu for another element (just using right-click anywhere else) the "onHide" callback is not invoked, so the context menu won't be cleared for that case (not ok). The context menu itself gets closed visually (ok).

### Environment

PrimeNG 15 LTS

### Angular version

15.x

### PrimeNG version

15 LTS

But seems to works with 16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.19.0

### Expected behavior

"onHide" on the first opened context menu is called when the user opens another context menu.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
