### ISSUE TITLE
PrimeOne compatibility with new Figma Dev Mode

### ISSUE THREAD

**Issue by cmcconomyfwig** [primefaces/primeng#13282]
### Describe the feature you would like to see added

Figma very recently announced a new 'dev mode' whose capabilities appear to overlap significantly with PrimeOne:
https://www.figma.com/dev-mode/

Are there any plans to create a version of PrimeOne which is integrated with the variables etc provided in the new Dev Mode?

### Describe the solution you'd like

I would like for a designer to be able to drop in native primeng components and output whatever files can be directly consumed by primeng developers

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
