### ISSUE TITLE
onColResize does not trigger change detection

### ISSUE THREAD

**Issue by ghazi-git** [primefaces/primeng#13283]
### Describe the bug

When the `onColResize` event fires, it does not trigger change detection to update the signal value that is displayed in the template.
This issue seems to be linked to a [previously closed issue](https://github.com/primefaces/primeng/issues/9996)

### Environment

Error reproduced in Stackblitz, here are the steps to recreate the same stackblitz:
- fork the stackblitz for "[Column Resize > Expand Mode](https://primeng.org/table#expand-mode)"
- add a signal to track the delta for resizing a column `delta = signal(0);`
- add an event handler for updating the signal
```javascript
onResize($event: any) {
    const d = $event.delta;
    console.log("delta", d);
    this.delta.set(d);
}
```
- attach the column resize event handler to the primeng table `(onColResize)="onResize($event)"`
- display the signal value in the template `Delta: {{delta()}}`

### Reproducer

https://stackblitz.com/edit/5mwpan?file=src%2Fapp%2Fdemo%2Ftable-column-resize-expand-mode-demo.ts

### Angular version

16

### PrimeNG version

16

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.20.0

### Steps to reproduce the behavior

- resize any column
- after that, you'll see that the updated signal value is **not** displayed in the template

### Expected behavior

After resizing any column, any template binding should be updated automatically. Currently, they are only updated if change detection is triggered manually via sth like `this.changeDetectorRef.detectChanges()`

**Comment by cetincakiroglu** [comment]
Hi,

Thanks for reporting the issue, might be solved with Angular Signals instead of dirty checking.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
