### ISSUE TITLE
Component: Table with dropdown in filter row

### ISSUE THREAD

**Issue by ElMohMoh** [primefaces/primeng#13281]
### Describe the bug

Since the version `15.3.0`, I have an issue with the component the dropdown filter in table component when I have only one row in the table.

To show you my issue, I use a forked project codesandbox from the url https://codesandbox.io/s/crqz0z (from exemple: https://www.primefaces.org/primeng-v15-lts/table#filter-row).

My forked project url is https://codesandbox.io/s/primeng-table-filter-row-demo-forked-3tdvw7 (in fullscrean mode https://4ggwht.sse.codesandbox.io/). In my exemple, we have only one row and in fullscrean mode we can't select the filter "agent". I think is due to the css rule: `overflow: auto;` on the selector `.p-datatable>.p-datatable-wrapper`.

![image](https://github.com/primefaces/primeng/assets/7288045/8c59455d-97c8-419c-b39a-8c962ee3080d)

### Environment

PrimNG `15.3.0` table with dropdown filter and only one row.

### Reproducer

https://codesandbox.io/s/primeng-table-filter-row-demo-forked-3tdvw7

### Angular version

15.2.5

### PrimeNG version

15.3.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.19.1

### Browser(s)

Version 114.0.5735.199 (Build officiel) (64 bits)

### Steps to reproduce the behavior

Go to 'https://4ggwht.sse.codesandbox.io/' on a desktop.
Click on filter "Agent"

### Expected behavior

The dropdown for the filter "agent" show all options

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
