### ISSUE TITLE
p-menu: Links are turned into groups

### ISSUE THREAD

**Issue by virtualmarc** [primefaces/primeng#13297]
### Describe the bug

Top Level menu items from the model are turned from links to groups as soon as a group is added to the model.

If the model only contains url, routerLink or command Entries everything works fine, but as soon as a group entry with sub items is added, everything on the top level is turned to groups.

### Environment

macOS 13.4
IntelliJ IDEA 20023.1.3

### Reproducer

https://stackblitz.com/edit/8uujks?file=src%2Fapp%2Fdemo%2Fmenu-group-demo.ts

### Angular version

16.0.0

### PrimeNG version

16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.1

### Browser(s)

Chrome 114

### Steps to reproduce the behavior

1. Create a Menu Model
2. Add the model to a p-menu
3. Fill the Model with routerLink Entries
4. Add an Entry with Child Entries

### Expected behavior

Links should stay links and should not convert to groups.
This works fine with the Panel Menu but not with the Menu.

**Comment by cetincakiroglu** [comment]
Hi,

The issue is not clear and the reproducer you've shared is the actual example in the live demo which does not replicate the issue. Could you please share a valid Stackblitz reproducer?

**Comment by virtualmarc** [comment]
Sorry, StackBlitz did not save my changes I made to the example.

I updated the example again.

**Comment by cetincakiroglu** [comment]
Hi,

Thanks for updating the example, now I can see the bug.

**Comment by SoyDiego** [comment]
Hi @cetincakiroglu and @virtualmarc. 
I did a PR https://github.com/primefaces/primeng/pull/13313 solving the problem.
Let me know If I should modify something :)
