### ISSUE TITLE
Carousel: Examples Bugged

### ISSUE THREAD

**Issue by Raasec** [primefaces/primeng#13293]
### Describe the bug

All examples are bugged.

![image](https://github.com/primefaces/primeng/assets/94648093/5048dc5f-78a4-4cb6-ae53-b945a15b9e58)

### Environment

ng 16

### Angular version

16.0.1

### PrimeNG version

16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v18.16.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

https://primeng.org/carousel

**Comment by SoyDiego** [comment]
Will be fixed in the next release 16.0.3. I did a PR a few days ago and was approved here: https://github.com/primefaces/primeng/pull/13287

**Comment by cetincakiroglu** [comment]
Hi,

This issue will be fixed in the upcoming release (16.0.3). Closing the issue since the related pr is merged it's already fixed. Thanks for reporting!
