### ISSUE TITLE
Column Filter overlay is not hiding when using clear() from Table class or when click another column filter, after being touched.

### ISSUE THREAD

**Issue by abhidynmc** [primefaces/primeng#13298]
### Describe the bug

In table filters, we observed below two issues:

- When we click a column filter and touch any component inside filter overlay and then we click on another column filter, previous filter overlay wont hide.
![image](https://github.com/primefaces/primeng/assets/34659228/967a9b98-5e5e-4327-8674-585d20b28bd3)
- When we click a column filter and touch any component inside filter overlay and then click **Clear** (It calls tableRef.clear() function internally), filter overlay wont hide. 
![image](https://github.com/primefaces/primeng/assets/34659228/f6dbf3ca-7c85-478e-9f39-69402d478ba1)

Please take a look and let me know if there is any fix or workaround for this.

### Environment

Angular version 13.3.12,
PrimeNg version 13.4.0 

### Reproducer

https://stackblitz.com/edit/primeng-tablefilter-demo-2z53i9?file=src%2Fapp%2Fapp.component.ts

### Angular version

13.3.12

### PrimeNG version

13.4.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.20.1

### Browser(s)

Chrome, Edge

### Steps to reproduce the behavior

1. Go to : https://stackblitz.com/edit/primeng-tablefilter-demo-2z53i9?file=src%2Fapp%2Fapp.component.ts
2. Click any one column filter.
3. Click first dropdown "Match All".
4. Click any other column filter.
5. Previous filter wont hide.
-------------------------

1. Go to : https://stackblitz.com/edit/primeng-tablefilter-demo-2z53i9?file=src%2Fapp%2Fapp.component.ts
2. Click any one column filter.
3. Click first dropdown "Match All".
4. Click "Clear".
5. Filter overlay wont hide.

### Expected behavior

Filter overlay should hide on both cases.

**Comment by cetincakiroglu** [comment]
Hi,

This issue does not exist in the latest version of the PrimeNG and it's probably fixed between v14-v16. Fix for v13 is not possible right now. I suggest you update the version. Closing the issue because it's not valid.
