### ISSUE TITLE
p-contextMenu left click not working for rows in a p-table

### ISSUE THREAD

**Issue by dgashby** [primefaces/primeng#13294]
### Describe the bug

Triggering a context menu using a left-click doesn't work for rows in a p-table.

The reason for needing this is for use on iOS devices (and possibly Android) where a long press brings up the built-in context menu rather than my custom menu.

### Environment

Angular 14, 15
Prime 14, 15

### Reproducer

https://stackblitz.com/edit/primeng-table-context-menu?file=src%2Fapp%2Fapp.component.html

### Angular version

14.1.3

### PrimeNG version

14.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Steps to reproduce the behavior

1. Left click on a row
2. No context menu appears.
3. Right click on a row
4. The context menu does appear.

### Expected behavior

A context menu should appear when left clicking on a table row, not on a right click.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
