### ISSUE TITLE
 Component: Avatar

### ISSUE THREAD

**Issue by tomavic** [primefaces/primeng#13292]
### Describe the bug

There is no actual component with the name `p-avatarGroup`

Your example is actually not working :)

https://codesandbox.io/s/ceg08p

### Environment

ng 15

### Reproducer

https://codesandbox.io/s/ceg08p

### Angular version

15

### PrimeNG version

15

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

**Comment by TolgaYigit** [comment]
The imports array is lacking the import of the AvatarGroupModule. Simply adding it to the array should resolve the issue and allow it to function properly.

**Comment by SoyDiego** [comment]
> It seems that the AvatarGroupModule import is missing from the imports array in the app.module.ts file. Simply adding this import should resolve the issue and make it work as intended.

Hi @tomavic, as @TolgaYigit said you should add `import { AvatarGroupModule } from "primeng/avatargroup";`and then add `AvatarGroupModule` in the imports array in the app.module.ts file. 
By the way I created a CodeSandbox here: https://codesandbox.io/s/primeng-avatar-group-demo-2xcgyt.

**Comment by tomavic** [comment]
Thanks @TolgaYigit & @SoyDiego for reply. However this module is not mentioned in the documentation.

Also please confirm that this module `AvatarGroupModule` is supported by `prime@15`

Finally, I would have applied the desired style without importing the module and applied this simple style to my example

```scss
.avatar-group p-avatar + p-avatar {
  margin-left: -1rem;
}

```

and in html

```html
      <div class="flex justify-content-center avatar-group">
        <p-avatar
          *ngFor="let item of items"
          [label]="item.name"
          styleClass="border-1"
          size="large"
          shape="circle"></p-avatar>
      </div>
```

**Comment by SoyDiego** [comment]
> Thanks @TolgaYigit & @SoyDiego for reply. However this module is not mentioned in the documentation.
> 
> Also please confirm that this module `AvatarGroupModule` is supported by `prime@15`
>

I don't know what version you PrimeNG are you using exactly but I downloaded PrimeNG 15.4.1 and have the `AvatarGroupModule`.

![image](https://github.com/primefaces/primeng/assets/19764334/720aac6f-e97c-4680-a4be-ec73d73fd249)

**Comment by tomavic** [comment]
@SoyDiego  
I believe then it should be add this missing part in the documentation.

**Comment by SoyDiego** [comment]
> @SoyDiego Cool. I believe that this missing part should be add in the documentation.

I created a PR adding that part: https://github.com/primefaces/primeng/pull/13296
