### ISSUE TITLE
Component: SelectButton with TEMPLATE don't show correctly

### ISSUE THREAD

**Issue by payisesp** [primefaces/primeng#13302]
### Describe the bug

Anything you add to the template is not showing, it seems like the template functionality was completely removed completely on version 16.0.2

### Environment

I'm trying to implement something similar to the example that PrimeNG shows on his website [PrimeNG - SelectButton](https://www.primefaces.org/primeng/#/selectbutton) in the section Custom Template. I'm trying to replicate the same. This is my code:

component.ts

metodos: any[];
selectedMetodo;

constructor() {
    this.metodos = [
      { 'name': 'Tarjeta de crédito','flag': 'pse.png' },
      { 'name': 'PSE', 'flag': 'pse.png' },
      { 'name': 'Efectivo', 'flag': 'pse.png'}
    ];
  }
component.html
`<p-selectButton [options]="metodos" [(ngModel)]="selectedMetodo">
    <ng-template let-item>
        <h1>Any Text</h1>
        <span>{{item.name}}</span>
    </ng-template>
</p-selectButton> `

### Angular version

16.1.1

### PrimeNG version

16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

Adding     <ng-template let-item> </ng-template let-item> should allow you to customize each button, but is not working, the template item doesn't display any extra element, just the label of the button, this stopped working on version 16.0.2

### Expected behavior

I was expecting to see the H1 element inside the buttons

**Comment by cetincakiroglu** [comment]
Could you please share a Stackblitz reproducer?

**Comment by payisesp** [comment]
The Prime NG Issue Template just allows to install the primeng version 14.1.1 and the issue is on the version 16.0.2
![image](https://github.com/primefaces/primeng/assets/138920687/3bc0c18a-34b0-4357-af63-b7f818b6cca5)

**Comment by scurk1415** [comment]
You have to add **pTemplate** attribute to ng-template

**Comment by mpkeusch** [comment]
We had the same issue.

With v16.0.1 (see this commit: https://github.com/primefaces/primeng/pull/13174/commits/bed52dc465a369edbf1f6c0da313398fd288e5ac) the ngTemplate inside the selectbutton stopped working as before.

We didn't have the pTemplate attribute in ng-template. And adding **pTemplate** fixed our problems. Thanks for pointing this out @scurk1415
