### ISSUE TITLE
Check for prefers-reduced-motion

### ISSUE THREAD

**Issue by luukbrauckmann** [primefaces/primeng#13301]
### Describe the feature you would like to see added

I would like that the Primeng components would respect the users settings for reduced motion so that the components would minimize the use of non-essential motion.

### Is your feature request related to a problem?

This will improve accessibility & user experience.

### Describe the solution you'd like

Media queries which will disable the transitions & animations.

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
