### ISSUE TITLE
Dropdown: Lazy doesn't work as expected with filter (also for MultiSelect)

### ISSUE THREAD

**Issue by yelhouti** [primefaces/primeng#13307]
### Describe the bug

The virtual scroller inside the dropdown relies on the number of items, however this value depends on the selected filter.

For this to work well, the DropdownLazyLoadEvent should have a filter value and should also be triggered on filter.

### Environment

chrome

### Angular version

16.1.3

### PrimeNG version

16.0.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.1

### Browser(s)

Chrome

### Steps to reproduce the behavior

Use a lazy dropdown with filter

### Expected behavior

have the filter value in the event

**Comment by yelhouti** [comment]
Edit:
Workaround for dropdown:
```typescript
import { Directive } from '@angular/core';
import { Dropdown, DropdownLazyLoadEvent } from 'primeng/dropdown';

/**
 * The role of this directive is to fix this: https://github.com/primefaces/primeng/issues/13307
 */
@Directive({
  // eslint-disable-next-line @angular-eslint/directive-selector
  selector: 'p-dropdown [lazy]'
})
export class LazyDropdownDirective {
  constructor(private dropdown: Dropdown) {
    // we have to override emit since it is directly called in the template
    // emit by default, just calls super.next() with super=Subject
    dropdown.onLazyLoad.emit = (event: DropdownLazyLoadEvent) => dropdown.onLazyLoad.next({ ...event, filter: dropdown.filterValue } as DropdownLazyLoadEvent);
    const oldActivateFilter = dropdown.activateFilter;
    dropdown.activateFilter = () => {
      if (dropdown.lazy) {
        dropdown.onLazyLoad.next({ first: 0, last: dropdown.scroller?.step ?? 20, filter: dropdown.filterValue } as DropdownLazyLoadEvent);
      } else {
        oldActivateFilter();
      }
    }
  }
}

```

**Comment by yelhouti** [comment]
this branch has a fix: https://github.com/yelhouti/primeng/blob/selectLazy/src/app/components/dropdown/dropdown.ts#L1158

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
