### ISSUE TITLE
Image Component: adding ng-template to p-image-preview-indicator to be able to customize

### ISSUE THREAD

**Issue by GeorgeHulpoi** [primefaces/primeng#13304]
### Describe the feature you would like to see added

Right now you can't customize the Image preview and it's very useful when you're dealing with actions like Edit or Remove or even having a checkbox for bulk actions. Adding ng-template in the preview section would help us to achieve this goal.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
