### ISSUE TITLE
Image Component: additional source for Mask Overlay

### ISSUE THREAD

**Issue by GeorgeHulpoi** [primefaces/primeng#13303]
### Describe the feature you would like to see added

Image Component currently uses the same source for the thumbnail image and the mask overlay. It would be great to can be used two sources, one for the thumbnail which should be a smaller size and one for the mask overlay at full size.

### Is your feature request related to a problem?

Using a big image can cause slow loading.

### Describe the solution you'd like

Two sources, one for thumbnail and another for full size.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
