### ISSUE TITLE
Component: FileUpload p-fileupload-highlight css class not defined in _fileupload.scss

### ISSUE THREAD

**Issue by ajjp** [primefaces/primeng#13306]
### Describe the bug

p-fileupload-highlight css class not defined in _fileupload.scss

### Environment

Windows

### Angular version

16.1.3

### PrimeNG version

16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.1

**Comment by SoyDiego** [comment]
I don't understand your issue.
Can be more specific or write more information, screenshots, etc...?

Thanks

**Comment by SoyDiego** [comment]
> I've checked it and it works like a charm. Thank you!

Happy to help! 🚀
