### ISSUE TITLE
TreeSelect (Filter): Resizing does not behave as expected after performing a filter

### ISSUE THREAD

**Issue by jhonatan-vsd** [primefaces/primeng#13314]
### Describe the bug

When my select component is positioned on the right of the screen, when filtering the items, the panel ends up being out of position, as you can see in the video below, the same does not happen when the component is positioned on the left (in this case the its position after filtering is positioned according to the select).

the demonstration of what is happening can be seen in the video below, see the expansion after filtering when the component is on the right of the screen:
https://github.com/primefaces/primeng/assets/81754888/561b5859-9590-4087-8535-4d64fbef841c

Obs: I already validated using the latest versions of Angular and PRIMENG, the problem persists.

### Environment

Local Setup, Mac OS
Angular CLI: 13.3.11

### Angular version

13.3.11

### PrimeNG version

13.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.20.1

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
