### ISSUE TITLE
Expose "trackBy" function for component using NgFor directive like Carousel, accordion, ....

### ISSUE THREAD

**Issue by Apokalypt** [primefaces/primeng#13315]
### Describe the feature you would like to see added

In complex applications, it's not uncommon to run into a number of performance problems. One possible solution and improvement is the use of a custom "[trackBy](https://angular.io/api/core/TrackByFunction)" function for ngFor directives to better manage the updating of DOM elements.

I would like that a similar function is exposed on some components like Carousel and Accordion to improve performance

### Is your feature request related to a problem?

The source of this request comes from the fact that in the case of a current development, where I need to combine different Carousels and Accordions, I'm encountering a problem with the DOM rendering, which is performed each time I interact with an input leading to bugs (user can't enter text, click button, ...)

### Describe the solution you'd like

Expose the ability to provide a custom [TrackByFunction](https://angular.io/api/core/TrackByFunction) like Angular Material does it with [MatTable](https://angular.io/api/core/TrackByFunction)

### Describe alternatives you have considered

There's no effective alternative, since this is how Angular recommends building complex applications in order to improve performance (using the TrackBy function).
To get around the problem we've encountered, we've changed the design and the way we display the forms, but it's not clean and shouldn't be done that way!

### Additional context

For those who don't know the use case of this function here is some resources for you :
- https://angular.io/api/core/TrackByFunction
- https://stackoverflow.com/questions/42108217/how-to-use-trackby-with-ngfor
- https://netbasal.com/angular-2-improve-performance-with-trackby-cc147b5104e5

**Comment by Apokalypt** [comment]
I just have found some other tickets that talk about that "TrackByFunction". I think that's a really wanted feature for performance and to avoid some bugs :
- #12923 
- #8231

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
