### ISSUE TITLE
p-multiselect disable option is not working

### ISSUE THREAD

**Issue by ekuicsdoodles** [primefaces/primeng#13311]
### Describe the bug

The **disabled** option in p-multiselect options is not working even after the **optionDisabled** has been provided. Please look into this.

### Environment

Normal 

### Angular version

10.0.8

### PrimeNG version

9.1.3

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

14.20.0

### Browser(s)

All

### Expected behavior

The option should be disabled in every case if it is marked as disabled.

**Comment by cetincakiroglu** [comment]
Hi,

The version you are using is very outdated and not up-to-date. It is not possible for us to fix this error in that version. This issue is not present in the newer versions, and we recommend using the latest versions of PrimeNG. Labeling as invalid and closing the issue.
