### ISSUE TITLE
p-table: Frozen columns see-through on hover in material theme

### ISSUE THREAD

**Issue by Elias-Graf** [primefaces/primeng#13312]
### Describe the bug

Since the background color of the row is set to a color using alpha `rgba(0, 0, 0, 0.04)`, and the background color of frozen columns is set to `inherit`, the frozen column will become see through and show the content of the row behind. This is not very pretty at best, and at worst, makes the text ineligible.

 **This is not happening the in the default theme. The issue is (at least) occurring in the material light theme.**

See this picture:

![image](https://github.com/primefaces/primeng/assets/46671625/8e57c3b6-ebab-48ff-8276-d7560e6d0dcc)

### Environment

See the reproducer below

### Reproducer

https://codesandbox.io/s/primeng-table-frozen-columns-demo-forked-mf6k86?file=/src/app/demo/table-frozen-columns-demo.html

### Angular version

our version is 15.\*.\*, but as you can see, it's also reproducable in 16.\*.\*

### PrimeNG version

our version is 15.\*.\*, but as you can see, it's also reproducable in 16.\*.\*

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v18.16.1

### Steps to reproduce the behavior

1. Open the reproducer
2. Decrease the viewport so the frozen column is over the content of a normal column
3. Hover a row

### Expected behavior

That darkening of the hover should not be done using alpha values, thus not showing what's behind frozen columns.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
