### ISSUE TITLE
When we use filter without result

### ISSUE THREAD

**Issue by arabakevin** [primefaces/primeng#13318]
### Describe the bug

When we try to use the filter when we don't have row or result this one is unusable.
![image](https://github.com/primefaces/primeng/assets/16837548/05d37937-fadb-43ea-a1c4-62f1f54147c4)
This example is on your documentation in 'filter row' section with the filter 'agent'
[primefaces.org/primeng-v13-lts/#/table/filter](https://www.primefaces.org/primeng-v13-lts/#/table/filter

### Environment

documentation on your website

### Reproducer

https://www.primefaces.org/primeng-v13-lts/#/table/filter

### Angular version

15

### PrimeNG version

13

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Steps to reproduce the behavior

1 go to https://www.primefaces.org/primeng-v13-lts/#/table/filter
2 go to the section 'Filter Row'
3 filter with 'Xuxue Feng' agent and use 'Ukraine' in country.
4 Try to change filter agent --> It's impossible to see and use the filter

**Comment by mehmetcetin01140** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.
