### ISSUE TITLE
Table: Column width resize does not fall at the indicator while resizing.

### ISSUE THREAD

**Issue by megharajak-05** [primefaces/primeng#13328]
### Describe the bug

Table: Column width resize does not fall at the indicator while resizing. The column width should be at the intended position where the column-resizer/indicator was dragged.
![image](https://github.com/primefaces/primeng/assets/139353448/f0431342-9c10-4058-9ee7-e4e430695f93)

### Environment

"primeng": "16.0.2"
https://stackblitz.com/edit/1ea4k4-s64bwu?file=src%2Fapp%2Fdemo%2Ftable-column-resize-fit-mode-demo.html,src%2Fapp%2Fdemo%2Ftable-column-resize-fit-mode-demo.html

### Angular version

16.0.0

### PrimeNG version

16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.16.0

### Browser(s)

Chrome, WebView2

### Steps to reproduce the behavior

1. Resize the column width by keeping dragging the column-resizer at the intended width.
2. Observe the column width in the Table.

### Expected behavior

The column width should be at the intended position where the column-resizer/indicator was dragged.

**Comment by ErzaScarlett6797** [comment]
Issue is fixed with the latest PrimeNg version (16.1.0).

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
