### ISSUE TITLE
Table:- On Column resize of multiple columns , the column width of previously resized column is getting changed.

### ISSUE THREAD

**Issue by megharajak-05** [primefaces/primeng#13329]
### Describe the bug

On Column resize of multiple columns , the column width of previously resized column is getting changed.

Resize the width of Column 'Code'. (Please refer the yellow highlights for the position in indication.)
![image](https://github.com/primefaces/primeng/assets/139353448/304cf0fe-551a-412a-b257-f31b50fd55c0)

Now Resize the width of Column 'Name'. It also changed the column width of Column 'Code'. Here, the previously resized width of Column 'Code' is overridden. (Please refer the yellow highlights for the position in indication. )
![image](https://github.com/primefaces/primeng/assets/139353448/dc6a7c29-ba02-4cf3-ab99-77a280836fa4)

### Environment

"primeng": "16.0.2"
https://stackblitz.com/edit/1ea4k4-s64bwu?file=src%2Fapp%2Fdemo%2Ftable-column-resize-fit-mode-demo.html,src%2Fapp%2Fdemo%2Ftable-column-resize-fit-mode-demo.html

### Angular version

16.0.0

### PrimeNG version

16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.0.0

### Browser(s)

Chrome, WebView2

### Steps to reproduce the behavior

1. Resize the width of Column 'Code'. (Please refer the yellow highlights for the position in indication.)
![image](https://github.com/primefaces/primeng/assets/139353448/304cf0fe-551a-412a-b257-f31b50fd55c0)

2. Now Resize the width of Column 'Name'. It also changed the column width of Column 'Code'. Here, the previously resized width of Column 'Code' is overridden. (Please refer the yellow highlights for the position in indication. )
![image](https://github.com/primefaces/primeng/assets/139353448/dc6a7c29-ba02-4cf3-ab99-77a280836fa4)

### Expected behavior

On resizing any table column, the previously resized columns or other columns width should not get changed.

**Comment by ErzaScarlett6797** [comment]
Issue is fixed with the latest PrimeNg version (16.1.0).

**Comment by ErzaScarlett6797** [comment]
The issue regarding column resizing affecting other columns has been resolved in the latest version. However, there remains a concern when it's used in combination with row span.
Basic configuration with below values are working as expected:

[resizableColumns]="true"
columnResizeMode="expand"
[scrollable]="true"

However, upon examining the additional configurations below, we observed that the scenario is not functioning as anticipated.

rowGroupMode="rowspan"
groupRowsBy="collectionCasePk"
[metaKeySelection]="true"
selectionMode="multiple"
dataKey="collectionCaseItemPk"
scrollHeight="flex"

Sample: https://stackblitz.com/edit/getneq-ewv7fa

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
