### ISSUE TITLE
Component: p-organizationChart

### ISSUE THREAD

**Issue by lohithatn** [primefaces/primeng#13321]
### Describe the feature you would like to see added

Currently, the organization chart only has a vertical tree kind of structure.

Requested feature to have organization chart to have horizontal flow as well

![Organizational Charts for PowerPoint - Showeet](https://github.com/primefaces/primeng/assets/5121031/97aebe6b-ea51-4add-9122-2c810ae6d5e2)

### Is your feature request related to a problem?

We are trying to implement this feature using a p-organization chart, but since horizontal orientation we couldn't use priming organization chart,

### Describe the solution you'd like

If p-organizationchart had layout attributes where we can say horizontal orientation or vertical orientation. it would be helpful. Then this component will become more useful

### Describe alternatives you have considered

I have used d3-org-chart, which is more complex then priming organization chart, but it has all the orientation required

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
