### ISSUE TITLE
DataGrid: Stacked Headers

### ISSUE THREAD

**Issue by Logic-Bits** [primefaces/primeng#13330]
### Describe the feature you would like to see added

Hello!

As far as I can see, there is no stacked Header possible.
Would this maybe become a option at some point?

https://help.syncfusion.com/angular/grid/stackedheader

Thanks!

### Describe the solution you'd like

https://help.syncfusion.com/angular/grid/stackedheader

### Describe alternatives you have considered

https://help.syncfusion.com/angular/grid/stackedheader

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
