### ISSUE TITLE
Component: Input Number

### ISSUE THREAD

**Issue by ajjp** [primefaces/primeng#13339]
### Describe the feature you would like to see added

Be able to define or automatically determine the behavior of the NumpadDecimal key to emit a period or a comma depending on the value of the locale.
i.e. if the locale uses a comma as a decimal point then the emitted NumpadDecimal value should be a comma, otherwise a period.

![image](https://github.com/primefaces/primeng/assets/106910824/b436f0a6-d825-4747-9633-64d07a3e3937)

![image](https://github.com/primefaces/primeng/assets/106910824/ea56054b-caa1-4708-8394-da48c7023499)

### Is your feature request related to a problem?

This has been requested by the users because it's very useful when they are using the numeric keypad to enter many decimal values in a row as it would make possible to use just that part of the keyboard.

### Describe the solution you'd like

The component determine the behavior it should have depending on the provided locale value.

**Comment by SoyDiego** [comment]
Hi @ajjp, is not this property that you are requesting?

![image](https://github.com/primefaces/primeng/assets/19764334/efcabe4b-1db3-477e-a8fb-0c8d6057ceb4)

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
