### ISSUE TITLE
Table with flex scroll enabled wrongly shows scrollbar if header heights change

### ISSUE THREAD

**Issue by Menecats** [primefaces/primeng#13333]
### Describe the bug

If the header of a table configured flex scrolling changes height after the component has been initialized the scrollbar appears even if the table has more space to grow.

This can happen for example if the user changes a different language and the new label doesn't fit on a single line.

**Note:** The table `p-scroller` element is taking all the available space but it's scrollable content has instead the initial fixed height in pixels even if the `scrollHeight` property is set by the `p-table` component to `100%`

### Environment

Angular 16.1.5
PrimeNG 16.0.2
Chrome 114 and Edge 114

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-ibdwfh?file=src%2Fapp%2Fapp.component.ts

### Angular version

16.1.5

### PrimeNG version

16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.14.1

### Browser(s)

Chrome 114, Edge 114

### Steps to reproduce the behavior

Open the stackblitz project 'https://stackblitz.com/edit/stackblitz-starters-ibdwfh?file=src%2Fapp%2Fapp.component.ts'

wait 1 second and see that the header label changes, than the scrollbar appears even if we only have 3 elements on screen and there is more space for the table to grow.

### Expected behavior

The table should grow to all available space before showing the scrollbar

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
