### ISSUE TITLE
primeng:table using virtualScroll squishes the table width and all width style is ignored

### ISSUE THREAD

**Issue by ibroudno** [primefaces/primeng#13331]
### Describe the bug

the table works as expected but when I add [virtualScroll] it's width becomes very narrow and adding with= or style={min-width is ignored.

### Environment

Windows 10

### Angular version

15.2.6

### PrimeNG version

15.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.13

### Browser(s)

chrome 114.0.5735.199

### Steps to reproduce the behavior

use this table      
<p-table [value]="filteredData" scrollHeight="41rem" 
      selectionMode="single" [(selection)]="selectedRow"
      dataKey="modelId"
      sortMode="multiple"
      styleClass="p-datatable-striped" [tableStyle]="{'min-width': '50rem','heigh':'41rem'}" 
      class="model-table"
      >

see it work , add  [virtualScroll]="true" into tha tag see it squished

### Expected behavior

It keeps the appearance as before  [virtualScroll]="true" was added.

**Comment by dmshapoval** [comment]
As a hack for those who interested: use css variable
In my case it was a table with virtual scroll in the overlay panel. So to be able set virtual scroller width as it ignores config and causes squeeze

`
::ng-deep {
  .suggestions { 
    .p-datatable {
      .p-scroller {
        width: var(--suggestions-table-width);
      }

      .p-datatable-table {
        width: min-content;
      }
    }
  }
}

// on the table use binding or fixed width depending on the case
[style.--suggestions-table-width]="suggestionsTableWidth"
`

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
