### ISSUE TITLE
p-calendar: When pressing the Down key, the focus is lost from the input

### ISSUE THREAD

**Issue by angularinterviews** [primefaces/primeng#13334]
### Describe the bug

When you press the Down key on the input area of the date, the focus is lost and it moves to the arrow selection of the popup.

### Environment

Angular Web App

### Angular version

16.1.4

### PrimeNG version

16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.1

### Browser(s)

Chrome 114

### Steps to reproduce the behavior

1. Open the calendar
2. Select a date
3. If you press the Up key, the caret goes to the beginning of the text date
4. But when you press Down the focus is lost from the input and goes to the popup.

### Expected behavior

When you press Down, the caret should go at then end of the input and not lose the focus.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
