### ISSUE TITLE
Please add document that how to run show case.

### ISSUE THREAD

**Issue by hryktrd** [primefaces/primeng#1333]
I would like PrimeNG demo site (like http://www.primefaces.org/primeng/#/autocomplete) at local, but I can't run that because anuglar2 packages are not included in package.json.

So I added packages like followings.

```javascript
"dependencies": {
    "@angular/common": "~2.1.1",
    "@angular/compiler": "~2.1.1",
    "@angular/core": "~2.1.1",
    "@angular/forms": "~2.1.1",
    "@angular/http": "~2.1.1",
    "@angular/platform-browser": "~2.1.1",
    "@angular/platform-browser-dynamic": "~2.1.1",
    "@angular/router": "~3.1.1",
    "@angular/upgrade": "~2.1.1",
    "angular-in-memory-web-api": "~0.1.13",
    "core-js": "^2.4.1",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.0.0-beta.12",
    "systemjs": "0.19.39",
    "zone.js": "^0.6.25"
  }
```

Would you like to add that dependencies at package.json?

Best regards.

**Comment by dzhavat** [comment]
I don't know if you've seen it but there's [Building From Source](https://github.com/primefaces/primeng/wiki/Building-From-Source) page in the Wiki. 

In there you can read more about running PrimeNG locally (but it's pretty much what you suggest) :)

**Comment by hryktrd** [comment]
Thank you!
I copied this dependencies from other project.
but document in [Building From Source](https://github.com/primefaces/primeng/wiki/Building-From-Source) page include same dependencies.
Why package.json of primeNG doesn't include that ?

**Comment by dzhavat** [comment]
Well, it's mentioned in that page...

> PrimeNG package.json configuration is in distribution mode by default, meaning there are no dependencies defined to run the samples.

I think the reason is because you usually include PrimeNG as a dependency in your App's main `package.json` file. Therefore there's no need for having those dependencies in this package as well.

**Comment by hryktrd** [comment]
Oh, I had overlooked this explanation.
I understood. I'll add this dependencies myself.

Thank you.
