### ISSUE TITLE
P-Button is firing (click) event when it is disabled

### ISSUE THREAD

**Issue by thremendus** [primefaces/primeng#13342]
### Describe the bug

Describe the bug
<p-button (click)="iShouldNotFire()" label="Submit" [disabled]="true"></p-button>

The button is firing the click event even when it is disabled.

Notes: Apparently this was "fixed" recently according to <https://github.com/primefaces/primeng/issues/13042> but even after updating PrimeNG and Angular to latest GA I can still see the issue happening.

### Environment

PrimeNG v16.0.2

### Reproducer

https://stackblitz.com/edit/48dz3o?file=src%2Fapp%2Fdemo%2Fbutton-disabled-demo.ts

### Angular version

16.1.4

### PrimeNG version

16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.1

### Browser(s)

Chrome 114, Edge 114

### Steps to reproduce the behavior

Add a button to your html:
<p-button (click)="iShouldNotFire()" label="Submit" [disabled]="true"></p-button>

Click on the bottom half of the disabled button to see the click event firing.

### Expected behavior

I believe that button should not fire the event. Disabling is apparently just visual.

**Comment by thremendus** [comment]
@GiacomoDM I don't think that's correct. The official  documentation for p-button uses (click) instead of (onClick) when attaching an event handler to the click event.

**Comment by SoyDiego** [comment]
As @GiacomoDM  said, for `button` you should use `(click) `and for `p-button` the` (onClick)`.

![image](https://github.com/primefaces/primeng/assets/19764334/1b3c7b05-2875-4d1f-8602-05ae7f062720)

> @GiacomoDM I don't think that's correct. The official documentation for p-button uses (click) instead of (onClick) when attaching an event handler to the click event.

In my opinion, the docs it's wrong. I will do a PR fixing that part to be clear.

**Comment by thremendus** [comment]
Gotcha. I just realized that the API documentation does in fact states the use of onClick() but the examples do not.

Thank you @SoyDiego and @GiacomoDM for clarifying this. I will mark this ticket as resolve then.
