### ISSUE TITLE
Dialog: Drag not working as expected in nested dialogs

### ISSUE THREAD

**Issue by ks0777** [primefaces/primeng#13347]
### Describe the bug

When nesting two dialog components inside of each other, dragging the inner one will result the dialog being dragged anywhere but where the cursor actually is.

### Environment

Nothing to note here, see stackblitz example that demonstrates it directly on issue template. I discovered the bug in my project running on primeng 15.3.0 where this bug also still exists, as well as in the latest primeng version 16.0.2

### Reproducer

https://stackblitz.com/edit/github-zjgvux?file=src%2Fapp%2Fapp.component.html

### Angular version

14.0.7

### PrimeNG version

14.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.1

### Steps to reproduce the behavior

Open stackblitz example
Drag the inner dialog somewhere

### Expected behavior

The dialog gets dragged wherever the cursor is dragged.

**Comment by SoyDiego** [comment]
Hi @ks0777, I have checked your problem and in my personal opinion dialog modal are not created to be nested. 
Why do you want to do that? And PrimeNG doesn't show examples about that in any places. Maybe I'm wrong but doesn't have sense, nesting dialogs.

**Comment by ks0777** [comment]
Hi @SoyDiego, I totally agree that nesting dialogs is bad style. I am however working on a frontend that can be dynamically configured by the user, which can result in nested dialogs in some cases. For modal dialogs nesting makes even less sense but as can be seen in the example, the bug also exists on non-modal dialogs. It may not be a common scenario, but it can definitely occur and should thus not cause any weird behavior.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
