### ISSUE TITLE
UITreeNode: Inconsistent Rendering Logic (missing `isLeaf()`-check for Toggle Buttons)

### ISSUE THREAD

**Issue by Gykonik** [primefaces/primeng#13340]
### Describe the bug

In the `UITreeNode` component, there is a difference in the rendering logic between the `horizontal` and `vertical` layouts. When using `horizontal` layout, there is a conditional check to determine if the current node is a leaf or not:

```html
<span *ngIf="!isLeaf()" [ngClass]="'p-tree-toggler'" (click)="toggle($event)">
```

However, this check is missing when using the `vertical` layout:

```html
<button type="button" [attr.aria-label]="tree.togglerAriaLabel" class="p-tree-toggler p-link" (click)="toggle($event)" pRipple tabindex="-1">
```

I think it should be considered a bug because it creates unnecessary space for leaf nodes. If someone wants to include that space for leaf nodes, they could add it manually using CSS.

Here is the corresponding image illustrating the issue:

![image](https://github.com/primefaces/primeng/assets/17333876/0a85fdf3-f644-4ff8-b731-ed2ec3b3cb65)

### Environment

Browser and platform independent

### Reproducer

https://stackblitz.com/edit/l1p4wo-ulbm6m

### Angular version

^16.0.0

### PrimeNG version

16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.20.0

### Steps to reproduce the behavior

Just look at the resulting tree and expand `Documents`, then you see the blank space before `Work` and `Home` that should serve as placeholders for the `toggle`-button but shouldn't be visible on leaf nodes in my opinion.

### Expected behavior

The `toggle`-buttons should be hidden completely on leaf nodes.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
