### ISSUE TITLE
Button: Loading icon not showing when used by pButton directive

### ISSUE THREAD

**Issue by akostmOR** [primefaces/primeng#13345]
### Describe the bug

The [loading] input doesn't show the indicator when the pButton directive is used. It's working with <p-button> component.
Attached a stackblitz link, the right button is working, the left doesn't.

### Environment

macos, chrome

### Reproducer

https://stackblitz.com/edit/gyambj?file=src%2Fapp%2Fdemo%2Fbutton-loading-demo.ts

### Angular version

^16.0.0

### PrimeNG version

16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.20.0

**Comment by GiacomoDM** [comment]
Relates to #13250 and #13195

**Comment by SoyDiego** [comment]
Hi @akostmOR  I did a PR here: https://github.com/primefaces/primeng/pull/13363
I don't know if the best solution but solves the problem. Now we should wait if PrimeNG Team approves.
