### ISSUE TITLE
Table + Calendar: Row editing is closed when date is selected from calendar 

### ISSUE THREAD

**Issue by dgashby** [primefaces/primeng#13343]
### Describe the bug

If a p-table editable row has a cell containing a p-calendar component, selecting a date on the calendar component closes the calendar but also exits edit mode for the whole row.  To edit other cells you need click on the edit button to re-enable edit mode for the row. 

### Environment

Angular + PrimeNG

### Reproducer

https://stackblitz.com/edit/github-ysrsjw

### Angular version

14.0.7

### PrimeNG version

14.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Browser(s)

Chrome  114.0.5735.198 

### Steps to reproduce the behavior

1. Click on the row edit button to enable editing mode.
2. Click on the first cell to open the calendar
3. Select a date from the calendar.
4. The calendar disappears
5. The row is no longer in edit mode.

### Expected behavior

After selecting a date at step three, I would expect the row to remain in edit mode so other cells can be edited.

**Comment by mehmetcetin01140** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.
