### ISSUE TITLE
p-calendar: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by psarno** [primefaces/primeng#13348]
### Describe the bug

I've reduced this down to its core repro:

```
<p-calendar
view="month"
dateFormat="mm/yy"
[yearNavigator]="true"
></p-calendar>
```

Try changing the month using the upper left/right arrows.

### Environment

Angular / PrimeNG 16

### Reproducer

https://stackblitz.com/edit/github-wh3ibs

### Angular version

16.0.0

### PrimeNG version

16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Steps to reproduce the behavior

1. https://stackblitz.com/edit/github-wh3ibs
2. Change the month using either arrow at the top

### Expected behavior

The month should change without throwing a JavaScript error.

**Comment by SoyDiego** [comment]
Hi @psarno I have checked the problem and you are right.
I did a PR solving the problem. You can check here #13349.
Now we should wait if PrimeNG Team approve it.

Thanks! :)

**Comment by psarno** [comment]
@cetincakiroglu Is there any chance this PR can be reviewed?  

This has a very basic repro and is throwing an exception when trying to simply change the year via arrows.

**Comment by psarno** [comment]
@cetincakiroglu 

@SoyDiego has put in effort to resolve some of these very basic oustanding issues.  Do we know when we can get a PR review?

I'm not asking PrimeNG to fix something for me outside of support, I'm only asking that they review a fix for something that is simply broken.  Helps everyone!

Thanks! 👍

**Comment by gucal** [comment]
Hi,

We are now fully focused on accessibility improvements. That's why there was a bit of a hitch. I will inform you after reviewing the PR.

Thank you

**Comment by psarno** [comment]
@gucal I have multiple easy repro items open with PRs that need a fix to help everyone.

I totally get that you're working components for accessability .... do you have a timeframe?

Not only this PR, but others:

https://github.com/primefaces/primeng/issues/13348
