### ISSUE TITLE
AutoComplete:  completeOnFocus

### ISSUE THREAD

**Issue by arunvc** [primefaces/primeng#13344]
### Describe the bug

when a selection is made then multiple api calls are made when we click on the autocomplete dropdown button with completeOnFocus=true, 

[sample.webm](https://github.com/primefaces/primeng/assets/9069988/bcfce4ec-40a3-454a-ab62-fb62176f7ff0)

```
    <p-autoComplete [(ngModel)]="selectedCountry" [dropdown]="true" [suggestions]="filteredCountries" (completeMethod)="filterCountry($event)" field="name"
    [completeOnFocus]="true"
    ></p-autoComplete>
```

### Environment

Ubuntu 22.04

### Reproducer

https://stackblitz.com/edit/pyscce?file=src%2Fapp%2Fdemo%2Fautocomplete-dropdown-demo.html

### Angular version

16

### PrimeNG version

16

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16

### Browser(s)

Firefox

### Steps to reproduce the behavior

check the attached  video

**Comment by SoyDiego** [comment]
Hi @arunvc I have checked the problem and I did PR. You can check here #13350 
Now we should wait if PrimeNG Team approve it.
