### ISSUE TITLE
Add money/currency mask

### ISSUE THREAD

**Issue by apiweb** [primefaces/primeng#1334]
In the [InputMask ](http://www.primefaces.org/primeng/#/inputmask)component documentation, you receive the following message:

> InputMask component is used to enter input in a certain format such as numeric, date, currency

However I never got to make the mask run for currency / money.

I think it would be interesting to add a currency / money mask to the component, similar to this one:
http://assisrafael.github.io/angular-input-masks/ (ui-money-mask)

It is a very good mask, but it only works with Angular1.

**Comment by cesarrew** [comment]
You can use this one:
https://www.npmjs.com/package/ng2-currency-mask

"A very simple currency mask directive for Angular 2 that allows using a number attribute with the ngModel. In other words, the model is a number, and not a string with a mask."

**Comment by marcoskichel** [comment]
up

**Comment by stevenvanryckeghem** [comment]
+1

**Comment by sudheerj** [comment]
You can add currency symbols in the format but not thousand,decimal separators dynamically etc.

**Comment by cagataycivici** [comment]
We'll do this via upcoming inputnumber for this instead.

**Comment by Lipe16** [comment]
IInputNumber?
