### ISSUE TITLE
Sortable PickList

### ISSUE THREAD

**Issue by ZeroZeroOne-dev** [primefaces/primeng#13354]
### Describe the feature you would like to see added

Currently the picklist is not sortable

This feature request existed before but was closed without solution: #8074

### Describe the solution you'd like

Allow for both user-defined sorting and sorting through code (same way as the table does)

### Describe alternatives you have considered

Currently I'm sorting the list in code every time the source of target list changes.

This does not allow for user based sorting.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
