### ISSUE TITLE
p-InputNumber: scientific annotation (large numbers) bug

### ISSUE THREAD

**Issue by jserra91** [primefaces/primeng#13353]
### Describe the bug

When you type a lot of numbers in the p-inputnumber, there is a moment when it converts to exponential. All numbers after that number are replaced by 0.

This happens at the component level because of the conversion.

https://primeng.org/inputnumber#numeral

If you type in the field Without Grouping the number 6566546546546216846351346513246641 (random numbers) you will see that there is a moment when the numbers are replaced by 0.

### Environment

N/A. Try it in the showcase of primeng

### Reproducer

https://primeng.org/inputnumber#numeral

### Angular version

15.2.x

### PrimeNG version

15.4.5-lts

### Build / Runtime

TypeScript

### Language

ALL

### Node version (for AoT issues node --version)

18.14.2

### Browser(s)

Chrome last version

### Steps to reproduce the behavior

1. Go to https://primeng.org/inputnumber#numeral
2. Write a large number in the Without Grouping
3. Check the number

### Expected behavior

Correct display of the number

**Comment by hcornelisonJHA** [comment]
Also experiencing this issue, has any one found a work around for this?

**Comment by fbergmann** [comment]
This would be resolved by exposing the `notation` field on InputNumber, like suggested in: <https://github.com/primefaces/primeng/issues/11830>

**Comment by szeiser** [comment]
This solution won't work for us - we need to display up to 19 digits without scientific notation.

**Comment by saver711** [comment]
@szeiser SAME -_-

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
