### ISSUE TITLE
Accessibility W3C bug in the tables and some more components

### ISSUE THREAD

**Issue by vadimt2** [primefaces/primeng#13352]
### Describe the bug

Hi.
Your tables are not W3C friendly.
Please go to this url:
https://primeng.org/table
Filter and Filter Row.
When you are navigating with the keyboards everything is working like it should be.
*** But when you are using a software's like JAWS or NVDA
1. It should say the category name separated from sorting and there is no tabindex on the sorting icon.
2. When you click on the Filter and you are using Jaws or NVDA and you click on the arrows or shift
it doesn't go to the "p-column-filter-overlay-menu" it's going to the next filter instead.
3. When you clicking on the expand button it doesn't say that this is an expand button
4. when you are clicking "Showing 1 to 10 of 200 entries" the next, prev buttons it doesn't say that this is buttons with prev and next.

* Using just a keyboard to navigate through all the component is not enough.
  You should test it with JAWS or NVDA
  Your table is not really supports W3C.

It was fully tested with our W3C developers and QA.

### Environment

DEV,QA

### Reproducer

https://primeng.org/table

### Angular version

15.0.0

### PrimeNG version

15.4.5

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Download Jaws or (NVDA) - Better to test in both of them
2. Install them, and make sure that they are working
3. Make sure that your speakers volume is loud enough to be heard
4. Navigate with tabs and keyboards
2. Navigate to this url:
[https://primeng.org/table](https://primeng.org/table)
5. Go to Filter and Lazy Load (Sections/Tags)
6. Open them in stackblitz Filter and Lazy
7. Try to open the filter and filter items
8. Try to hear the sorting, and the paginations buttons
9. Test all your table

### Expected behavior

It should be W3C friendly

**Comment by SoyDiego** [comment]
Hi @vadimt2, PrimeNG Team are working in accessibility right now. All the components at the bottom of the page has this message:

![image](https://github.com/primefaces/primeng/assets/19764334/5b02de49-f4f7-4434-98db-7600323951f8)

You can check the roadmap here: https://primeng.org/roadmap

Maybe this week they will release 16.0.3 with panel, misc, and menu section.

![image](https://github.com/primefaces/primeng/assets/19764334/a07b5803-e9f2-45c4-ab85-689dc8c33b0e)

So, they are working in this moment in all the components.

**Comment by cetincakiroglu** [comment]
Hi,

Yes, our tables are not W3C-friendly because at the bottom of the page, it indicates that "Accessibility implementation is in progress." Any contributions regarding accessibility are welcome. Please don't hesitate to open a PR.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
