### ISSUE TITLE
p-table: pTemplateBody doesn't display row when value is falsy (0 or null)

### ISSUE THREAD

**Issue by Tomorovik** [primefaces/primeng#13351]
### Describe the bug

After upgrading from PrimeNg 13 to 16 in our team, I've come across to weird bug. 

Specifically when given values to table are simple array of numbers, when providing template for body, row with value that is falsy (0 or null) is not shown at all. 

### Environment

Angular / PrimeNG 16

### Reproducer

https://stackblitz.com/edit/5mwpan-c5n39x?file=src%2Fapp%2Fdemo%2Ftable-column-resize-expand-mode-demo.html

### Angular version

16.0.1

### PrimeNG version

16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.1

### Steps to reproduce the behavior

For version 16
1. Go to  https://stackblitz.com/edit/5mwpan-c5n39x?file=src%2Fapp%2Fdemo%2Ftable-column-resize-expand-mode-demo.html
2. See displayed values

For version 13
1. Go to https://stackblitz.com/edit/primeng-tableedit-demo-yfjazm?file=src%2Fapp%2Fapp.component.html
2. See displayed values

### Expected behavior

In PrimeNg 16, it should still display correctly even when value is falsy

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
