### ISSUE TITLE
InputNumber: Does not check validation initially with ngClass

### ISSUE THREAD

**Issue by Kisters-BS** [primefaces/primeng#13367]
### Describe the bug

InputNumber does not check validation initially with ngClass. If the value is changed after loading it behaves correctly.
For validation I have to use ngClass to conditionally set the validation state.

### Environment

See stackblitz

### Reproducer

https://stackblitz.com/edit/cyubyy?file=src%2Fapp%2Fdemo%2Finput-number-invalid-demo.html

### Angular version

16.0.0

### PrimeNG version

16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.19.0

### Browser(s)

All

### Steps to reproduce the behavior

1. Add the following to an inputNumber:
    [ngClass]="{ 'ng-invalid ng-dirty': true }"

### Expected behavior

InputNumber should also show invalid state initially

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
