### ISSUE TITLE
Dropdown: Empty template doesn't work

### ISSUE THREAD

**Issue by vmlobo** [primefaces/primeng#13360]
### Describe the bug

When using the 'empty' template listed in the Dropdown component's docs, it doesn't seem to work or do anything.

### Environment

Angular application using Primeng

### Reproducer

https://stackblitz.com/edit/github-d1p6s3?file=src%2Fapp%2Fapp.component.html

### Angular version

15.2.0

### PrimeNG version

15.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.19.0

### Steps to reproduce the behavior

Create a dropdown component, and set the autoDisplayFirst option to false, and create define an ng-template with pTemplate='empty'

### Expected behavior

The content of the mentioned ng-template should be displayed while no item is selected. This template should also be boud to the emptyTemplate field of the Dropdown object, which isn't the case.

**Comment by ashikjs** [comment]
@vmlobo  it will only show when your drop-down don't have any options . 

BTW: maybe your looking placeholder

**Comment by ashikjs** [comment]
This issue should be close @cetincakiroglu and @SoyDiego

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
