### ISSUE TITLE
KeyFilter ，Unable to recognize Chinese input

### ISSUE THREAD

**Issue by fabian4** [primefaces/primeng#13369]
### Describe the bug

Unable to recognize Chinese input 
you can input chinese with Pinyin
![image](https://github.com/primefaces/primeng/assets/60428924/1c2fd81a-5ef4-4f5b-8bf4-4343f61d0349)

### Environment

https://primeng.org/keyfilter

### Angular version

15

### PrimeNG version

15

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

12

### Steps to reproduce the behavior

![image](https://github.com/primefaces/primeng/assets/60428924/72bcd0b9-0c22-47b0-8faa-b419c058e737)

**Comment by fabian4** [comment]
![image](https://github.com/primefaces/primeng/assets/60428924/14102ab0-ca60-4780-812a-5e4a3e3b69ff)


Also `_` is unable to recognize.

**Comment by fabian4** [comment]
I think we should make it more clear in doc since it allows `_`
https://github.com/primefaces/primeng/blob/291456e83534bcaf15ead1fdbfea6d81d2b48d16/src/app/components/keyfilter/keyfilter.ts#L52-L53

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
