### ISSUE TITLE
How to use LabelFor? Because input components don't have id attribute

### ISSUE THREAD

**Issue by apiweb** [primefaces/primeng#1336]
Is there any way for me to add a label to a component input, such as: p-inputMask, p-spinner, p-autoComplete, etc ...
I would very much like to use 
`<label for = "idComponent"> Test label </ label>`
But since these components do not have the ID attribute, I can not bind them to the label using LabelFor.
Is there any way to make this work?

**Comment by kartheininger** [comment]
I do not know if i don't get the problem right, but is there anything to be changed in primeng to get this working, because its a default html feature: http://www.w3schools.com/tags/att_label_for.asp

**Comment by apiweb** [comment]
It does not work because the primeng components do not have ID tag support. So I can not relate a label using "label for =[id]" because the component has no id...

**Comment by cagataycivici** [comment]
There is inputId for all inputs in recently PrimeNG releases that you can use to match with label.
