### ISSUE TITLE
Calendar support hijri data 

### ISSUE THREAD

**Issue by ahmedabdelhafez** [primefaces/primeng#13362]
### Describe the feature you would like to see added

Hello dears, 
I faced an issue that I want to switch between hijri data and miladi date and I cannot found this feature in prime calendar،cab the prime Ng team add it to calendar in the next release

### Describe the solution you'd like

Create a new extension or package 
Add this as a new feature

**Comment by kunalahuja06** [comment]
@ahmedabdelhafez 
You can configure LocaleSettings  in primeng Configuration.

Refer to this stackblitz: [Calendar Demo](https://primeng-calendar-demo-n3hq6y.stackblitz.io)
Refer for Locale Configuration: [Primeng Config](https://primeng.org/configuration)
Refer for Primeng LocaleSettings Interface: [Primeng Locale Interface](https://primeng.org/calendar#api.calendar.interfaces)

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
