### ISSUE TITLE
OrganizationChart not refreshing view after new TreeNode is added

### ISSUE THREAD

**Issue by troncomputers** [primefaces/primeng#13368]
### Describe the bug

New tree item is shown only after collapse/expand or reselect a node

### Environment

stackblitz

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-ifznba?file=src%2Fmain.ts

### Angular version

16

### PrimeNG version

16

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Steps to reproduce the behavior

https://youtu.be/Rx36onV8e3o

### Expected behavior

New item should be visible immediately

BTW.
It is acting very wird on stackblitz. That is not happening localy. The tree should be updated when new node is added, that is the main issue

**Comment by SoyDiego** [comment]
Hi @troncomputers I have checked the problem and you are right. 
I did a PR and now we should wait to PrimeNG Team approve it if it's ok for them.
You can check here the solution and your example solved: https://github.com/primefaces/primeng/pull/13396
