### ISSUE TITLE
Question - PrimeNG 6

### ISSUE THREAD

**Issue by mauroalexandre** [primefaces/primeng#13379]
Years ago, I needed to create a fork of prime in order not to break my application due to the creation of turbotable and removal of fontawesome.

Today I need to change some things, but I forgot how to generate the .JS of the components to publish. The build does not generate.

Can anybody help me?

**Comment by cetincakiroglu** [comment]
Hi,

You can find v6 from releases and download by zip: https://github.com/primefaces/primeng/releases
Please use the PrimeLand Discord channel for questions like that you can receive faster answers: https://discord.gg/gzKFYnpmCY

Download, make the changes, run the build command, and publish.
