### ISSUE TITLE
Lazy loading with virtual scroll on p-table

### ISSUE THREAD

**Issue by boiche** [primefaces/primeng#13370]
### Describe the bug

**Prerequisites:**
- data source of 1000 records
- p-table with 
1. scroll height: 761px
2. rows: 30
3. virtualScrollItemSize: 40
4. virtualScroll: true
5. virtualScrollDelay: 0
- child component that is reachable through a button. The child component must be able to navigate back to the grid.

Lazy loading is triggered only when reaching the beginnig of next chunk of data.
When scrolled via primeng/table/Table's method 'scrollToVirtualIndex(index: number): void' upwards data is not loaded when scrolling through previous chunk of data. Loads it when reaching the beginning of current chunk.

### Environment

Windows 11, Visual Studio Community 2022, Angular template project,

### Reproducer

https://stackblitz.com/edit/ntutb5?file=src%2Fapp%2Fdemo%2Ftable-virtual-scroll-lazy-demo.html

### Angular version

15.2.0

### PrimeNG version

15.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.17.1

### Browser(s)

Chrome

### Steps to reproduce the behavior

Steps to reproduce: 
Scroll to random record index (e.g. 250).
Navigate to child component.
Navigate back to the grid (**not by popstate**).
Via primeng/table/Table's method 'scrollToVirtualIndex(index: number): void' try to scroll to the recent reached index (e.g. 250)
Try to scroll upwards.

### Expected behavior

Expected result:  data is loaded normally

Comment: lazy loading should be able to trigger onLazyLoad event when reaching new chunk either from top or bottom.
No data is loaded above the yellow chunk. What is expected is onLazyLoad to be triggered right before reaching the bottom of the chunk above (as it works for bottom chunks).
![virtual_scroll_with_lazy_load](https://github.com/primefaces/primeng/assets/31018722/d1dd56bd-fe8f-4c24-961c-9a587d1b16c6)

**Comment by SaajRP** [comment]
This is still an issue on PrimeNg 16.2.0

- Virtual Scroll, Lazy Load, rows has been set to a given number
- Scroll from the top of the table to the bottom, then scroll to the middle
- The middle of the table will be stuck in a loading state indefinitely 

A work around I’ve found it not setting the rows, however, this will cause another set of issues, such as 
- https://github.com/primefaces/primeng/issues/13517

**Comment by SaajRP** [comment]
This remains a problem as of PrimeNg 16.9.0

**Comment by SaajRP** [comment]
Remains problems as of PrimeNg 17.0.0

**Comment by SaajRP** [comment]
Remains a problem as of PrimeNg 17.2.0

**Comment by SaajRP** [comment]
Remains a problem at of PrimeNg 17.10.0

**Comment by SaajRP** [comment]
Remains a problem as of PrimeNg 17.12.0

**Comment by SaajRP** [comment]
@cetincakiroglu would it be possible from someone from the PrimeNg team to have a look at, as this has remained an issue for almost a year

**Comment by SaajRP** [comment]
Remains a problem as of PrimeNg 17.8.7

@cetincakiroglu @mehmetcetin01140, would someone please have a look at this has been an issue for over a year, and makes virtual scrolling, lazy load tables with a row attribute defined, unusable in practice

**Comment by SaajRP** [comment]
Stackblitz instance for testing: https://stackblitz.com/edit/oetsny-rdsoxe

**Comment by SaajRP** [comment]
Remains an issue as of PrimeNg 18.0.0 

@mertsincan would you mind having a look?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
