### ISSUE TITLE
Multiselect: Overlay should not be closed when toggle on unSelectAll icon.

### ISSUE THREAD

**Issue by mohanreddyarolla** [primefaces/primeng#13384]
### Describe the feature you would like to see added

@cetincakiroglu 
Currently when we click on unSelectAll icon, it closes the overlay. But what if the users intended to unSelect all so that they can select some other options. They again need to open the overlay and select the options. 

So, I suggest to make the overlay visible on clicking unSelectAll.

### Describe the solution you'd like

I suggest to make the overlay visible on clicking unSelectAll so that the users may get the chance to select some other options.

**Comment by cetincakiroglu** [comment]
Hi,

Thanks for pointing out the issue, we're implementing accessibility right now and all components and functionalities responsible to open, close, toggle etc. will be reworked.

**Comment by cetincakiroglu** [comment]
You can create a pr 🙂

**Comment by mohanreddyarolla** [comment]
@cetincakiroglu 
Here is the PR for it #13385
