### ISSUE TITLE
SplitButton menu options not working correctly in v16.1.0

### ISSUE THREAD

**Issue by rosenthalj** [primefaces/primeng#13389]
### Describe the bug

When clicking on the SplitButton's  "Items  option" button,  the popup menu doesn't display near the button. 

The movie below is of the [PrimeNG 16.1.0 SplitButton demo](https://primeng.org/splitbutton)   

https://github.com/primefaces/primeng/assets/45439491/35f6506a-cf72-4c82-95ea-dc9e357a7fa2

### Environment

PrimeNG 16.1.0

### Angular version

16.x

### PrimeNG version

16.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.4.0

### Browser(s)

chrome, safari, firefox

### Steps to reproduce the behavior

1) Click on any of the SplitButton "Items  option" buttons on the  [PrimeNG 16.1.0 SplitButton demo](https://primeng.org/splitbutton)  
2) See that the popup menu is not be displayed near the SplitButton

### Expected behavior

Clicking the SplitButton "Items  option" button should display a popup menu  near the SplitButton

**Comment by biswasSaumyadip** [comment]
Hi,
I have made the fix, raised the PR, and for proof a video is attached.
@cetincakiroglu could you please check the PR seems recent PRs are failing?
