### ISSUE TITLE
Tree: Drag and Drop not working in Windows WebView2

### ISSUE THREAD

**Issue by 00jeser** [primefaces/primeng#13387]
### Describe the bug

I have an app on Tauri+Angular and p-tree can start dragging items, but it can't drop it
If I run same code in chromium-based browser it all works 

### Environment

Tauri+Angular

### Angular version

16.0.2

### PrimeNG version

16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.4.0

### Browser(s)

Tauri(WebView2)

**Comment by nuheci** [comment]
I encountered this issue when using Tauri v2 as well. I resolved it by configuring the `tauri.conf.json` file.
```
"app": {
    "windows": [
      {
        ...
        "dragDropEnabled": false
      }
    ]
}
```
