### ISSUE TITLE
PrimeNG 16.1.0 selecting a menu option causes panel to scroll

### ISSUE THREAD

**Issue by rosenthalj** [primefaces/primeng#13390]
### Describe the bug

A problem with Menubar and other PrimeNG "menu" components was introduced in PrimeNG 16.1.0.

When  a Menubar option is selected and a horizontal scroll bar is present, the menubar will scroll so that the corresponding option or parent option is at the beginning of the visible region.  This same problem occurs in other PrimeNG  "menu" components like MegaMenu

The first movie demonstrates when a Menubar's root menu option is selected:

https://github.com/primefaces/primeng/assets/45439491/65350e02-c770-4a44-9e21-97ccd9fa9fe3

The second movie demonstrates when a MenuBar's child menu option is selected:

https://github.com/primefaces/primeng/assets/45439491/dc01b4b0-9533-44e6-9053-62b098972f7d

The third movie demonstrates when a MegaMenu's child menu option is selected:

https://github.com/primefaces/primeng/assets/45439491/9f7e9d2a-ee64-47b7-8071-113a31a09c81

The forth movie demonstrates when a TieredMenu's root and child menu options iare selected:

https://github.com/primefaces/primeng/assets/45439491/6c38a4ca-48a8-4ee7-be89-d35cba249b8a

### Environment

Mac OS and Windows

### Reproducers

Menubar:  https://stackblitz.com/edit/vyzu1j?file=package.json
MegaMenu:  https://stackblitz.com/edit/3hyz2s?file=package.json
TieredMenu:  https://stackblitz.com/edit/buqxye?file=package.json

### Angular version

16.x

### PrimeNG version

16.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Browser(s)

chrome, safari, firefox

### Steps to reproduce the behavior

MenuBar 
1) Run the [stackblitz Menubar reproducer](https://stackblitz.com/edit/vyzu1j?file=package.json)
2) Expand the stackblitz window so that all 5 menubar options are visible
3) Make sure the horizontal scroll bar is scrolled completely to the left
4) Click on a menu option (like "Quit" or "Users > New")
5) See that the panel automatically scrolls and the selected option (or its parent option) is at the start of the scroll region

MegaMenu
Follow similar steps as above with the [stackblitz MegaMenu reproducer](https://stackblitz.com/edit/3hyz2s?file=package.json)

TieredMenu
Follow similar steps as above with the [stackblitz TieredMenu reproducer](https://stackblitz.com/edit/buqxye?file=package.json)

### Expected behavior

After executing step 4, the panel should not scroll.

**Comment by biswasSaumyadip** [comment]
Can anybody explain why 
    scrollInView(index: number = -1) {
        const id = index !== -1 ? `${this.id}_${index}` : this.focusedItemId;
        const element = DomHandler.findSingle(this.rootmenu.el.nativeElement, `li[id="${id}"]`);

        if (element) {
            element.scrollIntoView && element.scrollIntoView({ block: 'nearest', inline: 'begin' });
        }
    }
    introduced in the codebase?
