### ISSUE TITLE
FileUpload: when multiple files are selected and more than one has errors only only one message is shown

### ISSUE THREAD

**Issue by ajjp** [primefaces/primeng#13397]
### Describe the bug

When I select more than one file either by opening the file chooser or drag to the drag and drop and if more than one is invalid - wrong type, file size limit exceeded , only one message is shown.

I believe the problem is in the "validate" method that is cleaning the "msgs" array in every file validation:

The code is:
this.msgs = []

And should be:
this.msgs ??= []

![image](https://github.com/primefaces/primeng/assets/106910824/d8d0d598-7c3e-4121-b6d5-e8bd6e6555f4)

### Environment

Windows

### Angular version

16.1.3

### PrimeNG version

16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.17.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Select more than one file either by clicking the file choose button or by dragging them to the drop area
2. Only one error message is shown

### Expected behavior

Display all files with errors and not only the last one validated

**Comment by SoyDiego** [comment]
I have checked the problem and I did a PR with the solution here: https://github.com/primefaces/primeng/pull/13399
Now we should wait if PrimeNG Team approve it.
Thanks!
