### ISSUE TITLE
FileUpload: allow file size units internationalization

### ISSUE THREAD

**Issue by ajjp** [primefaces/primeng#13398]
### Describe the feature you would like to see added

Define the formatSize units in the language I want.

### Is your feature request related to a problem?

I need to display file size units in French language:

['o', 'ko', 'Mo', 'Go', 'To', 'Po', 'Eo', 'Zo', 'Yo']

### Describe the solution you'd like

Have an Input parameter to define formatSize

![image](https://github.com/primefaces/primeng/assets/106910824/39693aa4-c463-4b2a-bf90-4ca910efedd2)

**Comment by SoyDiego** [comment]
Hi @ajjp. I have created a PR here https://github.com/primefaces/primeng/pull/13400 to add this new feature. Now we should wait for PrimeNG to review and approve it.

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primeng/pull/13603
