### ISSUE TITLE
Component selector naming convention

### ISSUE THREAD

**Issue by ziuniecki** [primefaces/primeng#13393]
Hi, chevron left component has invalid selector.

https://github.com/primefaces/primeng/blob/ebe3f946250ebf801a4787b25b006315ab553063/src/app/components/icons/chevronleft/chevronleft.ts#L5C16-L5C31

You should follow standards for custom elements to avoid web accessibility problems:

https://angular.io/guide/styleguide#component-selectors

https://html.spec.whatwg.org/multipage/custom-elements.html#valid-custom-element-name

**Comment by SoyDiego** [comment]
You are right, @ziuniecki but I don't know if PrimeNG Team will do this because If they do, will generate breaking changes for all the users and is not the idea.

**Comment by ziuniecki** [comment]
yeah it will be breaking change but its just selector name change... Or just make it deprecated and remove those components in other versions, when teams will have time to migrate. PrimeNG made more complecated breaking changes in the past.

**Comment by SoyDiego** [comment]
> yeah it will be breaking change but its just selector name change... Or just make it deprecated and remove those components in other versions, when teams will have time to migrate. PrimeNG made more complicated breaking changes in the past.

I agree with your issue but I'm not part of PrimeNG Team or the person who take decision, only a contributor and I don't know if they will do. But I agree because is important follow the standards

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
