### ISSUE TITLE
NG0912: Component ID generation collision detected

### ISSUE THREAD

**Issue by slaven3kopic** [primefaces/primeng#13403]
### Describe the bug

After migrating to PrimeNG 16 (v16.1.0) and Angular 16 (v16.1.6) we are getting the following warnings related to PrimeNG:

![Screenshot 2023-07-31 at 14 03 05](https://github.com/primefaces/primeng/assets/16098085/8b1ede49-3907-4a8a-ba42-797420ccc111)

### Environment

Node 18.11.0
PrimeNG 16.1.0
Angular 16.1.6

### Angular version

16.1.6

### PrimeNG version

16.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.11.0

### Expected behavior

Warnings should not be in the console

**Comment by SoyDiego** [comment]
> ### Describe the bug
> 
> After migrating to PrimeNG 16 (v16.1.0) and Angular 16 (v16.1.6) we are getting the following warnings related to PrimeNG:
> 
> ![Screenshot 2023-07-31 at 14 03 05](https://user-images.githubusercontent.com/16098085/257212584-8b1ede49-3907-4a8a-ba42-797420ccc111.png)
> ### Environment
> 
> Node 18.11.0 PrimeNG 16.1.0 Angular 16.1.6
> ### Reproducer
> 
> _No response_
> ### Angular version
> 
> 16.1.6
> ### PrimeNG version
> 
> 16.1.0
> ### Build / Runtime
> 
> Angular CLI App
> ### Language
> 
> TypeScript
> ### Node version (for AoT issues node --version)
> 
> 18.11.0
> ### Browser(s)
> 
> _No response_
> ### Steps to reproduce the behavior
> 
> _No response_
> ### Expected behavior
> 
> Warnings should not be in the console 

Hi @slaven3kopic. I have checked all the project and I don't find anything repetitive about selector `p-header` or `p-footer`.
Also I have 2 projects with PrimeNG and I cannot see that warning.
Can you show the problem creating an stackblitz, please?

**Comment by slaven3kopic** [comment]
The issue for use is solved by adding 

```javascript
  new webpack.DefinePlugin({
    ngDevMode: config.mode === 'development',
  }),
```

in our `webpack.config.js`. It is not related to PrimeNG
