### ISSUE TITLE
Component: Mentions

### ISSUE THREAD

**Issue by ajitzero** [primefaces/primeng#13406]
### Describe the feature you would like to see added

Mentions would be a directive used on input/textarea elements where we can configure triggers like `@`, `#` or `/` for mentioning people, linking tags or triggering custom slash commands.

Prime React has this already: https://primereact.org/mention/

### Is your feature request related to a problem?

No.

### Describe the solution you'd like

Prime React has this already: https://primereact.org/mention/

A popular Angular variant is https://github.com/dmacfarlane/angular-mentions, but we should implement our version, which aligns itself with the React component's API as much as possible.

Unlike React, where this is a component, we should make a directive here. Then we wouldn't need to reimplement/expose native features like the hidden property, etc.

### Describe alternatives you have considered

https://github.com/dmacfarlane/angular-mentions

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).

**Comment by ajitzero** [comment]
Moved to Discussons: https://github.com/orgs/primefaces/discussions/788
