### ISSUE TITLE
p-table and p-menubar together:  Regression 16.0.2 -> 16.1.0

### ISSUE THREAD

**Issue by psarno** [primefaces/primeng#13405]
### Describe the bug

We have a `p-menubar` component, inside of a `<ng-template pTemplate="caption">`, in a `p-table`.

The p-table has `selectionMode="multiple"` and allows the user to check off individual rows:

`[(selection)]="selectedExtensions"`

We hook the `onRowSelect()` and `onRowUnselect()` methods and create the menubar items, where some of their disabled properties is set by the number of selected rows:

```
this.toolbarMenuItems = [
        {
          label: r.DELETE_SELECTED,
          disabled: this.selectedExtensions.length === 0
        },
        ... etc
}
```

I can verify that in version 16.0.2 of PrimeNG, the menubar items properly enable/disable when checking off rows in the table.

In version 16.1.0 they do not.

I can not create a repro at this time as the PrimeNG template is out of date on StackBlitz and trying to bring it up to 16.1.0 [results in a separate issue](https://github.com/primefaces/primeng/issues/13024).

### Environment

PrimeNG 16.1.0
Angular ~16.0.0

### Angular version

16.1.6

### PrimeNG version

16.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Steps to reproduce the behavior

1. Using PrimeNG 16.1.0, place a p-menubar in the header template of a p-table
2. In OnRowSelect() and OnRowUnselect(), re-create the menubar items, setting disabled equal to selectedItems.Count > 0

### Expected behavior

Items properly enable/disable based on selection count.

Actual behavior:  Items remain disabled (initial state).

**Comment by cetincakiroglu** [comment]
Hi,

Could you please share a Stackblitz reproducer?

**Comment by psarno** [comment]
> Could you please share a Stackblitz reproducer?

@cetincakiroglu As mentioned in the submission I can not get 16.1.0 working on StackBlitz (I linked to the issue I'm having there).  

The PrimeNG suggested template is still using version 14 and this does not reproduce the issue.
