### ISSUE TITLE
Component: PanelMenu - styleClass and tooltip not applied

### ISSUE THREAD

**Issue by GiacomoDM** [primefaces/primeng#13401]
### Describe the bug

The updated PanelMenu with accessibility features breaks styleClass and both tooltip proerties of MenuItem. 

The `styleClass` is only passed to a root node, the children and the nested ones don't receive it. 
The `tooltip`, both as simple property and with `toolipOptions` is never showed. 

Working in version 16.0.2: https://stackblitz.com/edit/knzccw-zc4qm7?file=src%2Fapp%2Fdemo%2Fpanel-menu-basic-demo.ts

### Environment

Windows 11

### Reproducer

https://stackblitz.com/edit/knzccw-k2kels?file=src%2Fapp%2Fdemo%2Fpanel-menu-basic-demo.ts

### Angular version

16.X

### PrimeNG version

16.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.20

### Steps to reproduce the behavior

1. Open the provided stackblitz
2. Observe the `styleClass` applied to the first root `MenuItem`
3. Expand the first item, the `styleClass` is not applied to the children
4. No node has the tooltip provided in the MenuItem definition in the component class

### Expected behavior

Every node with a `styleClass` provided should have it.
Every node with either `tootlip` or `tooltipOptions` provided should display it.

**Comment by cetincakiroglu** [comment]
Thanks for reporting the issue!
