### ISSUE TITLE
Component: Title

### ISSUE THREAD

**Issue by kinjal-thakkar-granicus** [primefaces/primeng#13419]
### Describe the bug

Hi,
While trying to create a component dynamically using createComponent API from @angular/core, the suggestions and loading symbol arent loading.

**AddresslookupComponent - HTML**
<p-autoComplete [style]="{'width':'100%'}" [inputStyle]="{'width':'100%'}" [(ngModel)]="selectedAddress" [suggestions]="cSVSuggestionModelOutput.Attributes" (completeMethod)="csvSuggestionHandler($event)" field="{{infos.searchFieldName}}" [minLength]="3" placeholder="{{infos.placeholder}}" (onSelect)="findAddress()" (onKeyUp)="keyPress($event)">
<ng-template let-address pTemplate="item" #itemRender>
<div [innerHTML]="address[infos.searchFieldName] | highlight: selectedAddress"></div>
</ng-template>
</p-autoComplete>

**TS in AppComponent **
reloadComponent(defaultValue:any){
const someDOMElement = document.querySelector('.host app-address-lookup') as HTMLElement;
this.componentRef = createComponent(AddresslookupComponent,{environmentInjector:this.appRef.injector,hostElement:someDOMElement});
this.appRef.attachView(this.componentRef.hostView);
this.componentRef.changeDetectorRef.detectChanges();
}

### Environment

Windows 10
VSCode

### Angular version

14.2.6

### PrimeNG version

14.2.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

--

### Browser(s)

Chrome

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
