### ISSUE TITLE
MultiSelect accesskey

### ISSUE THREAD

**Issue by TejAllam** [primefaces/primeng#13417]
### Describe the feature you would like to see added

Access the multi select component using an accesskey

### Describe the solution you'd like

Add an attribute to multiselect so that it can be selected using keyboard shortcuts 

### Additional context

If I have multi select implementation on a page, to access that element using accesskey ; it's not readily available currently.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
