### ISSUE TITLE
Component: Picklist

### ISSUE THREAD

**Issue by w1andresv** [primefaces/primeng#13424]
### Describe the bug

When the picklist has a preloaded  target list  and I try to move one item to target to source it's no posible

https://github.com/primefaces/primeng/assets/11529941/2d9561ec-7ad8-4d63-ae0e-881de5e2c7c4

### Environment

Prod

### Angular version

16.1.0

### PrimeNG version

16.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Browser(s)

Chrome

**Comment by SoyDiego** [comment]
Can you share a stackblitz please?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
