### ISSUE TITLE
TieredMenu: On mobile tieredmenu requires double tap to open submenu

### ISSUE THREAD

**Issue by r0754497** [primefaces/primeng#13433]
### Describe the bug

TieredMenu requires 2 touches to open a submenu. One focusses, next one opens. Required fix: touch to have the same behaviour as hover on menu items with submenu.
@cetincakiroglu 

### Environment

Occurred on multiple phones (Android and iOS), also the case when using Chrome dev tools.

### Reproducer

https://primeng.org/tieredmenu

### Angular version

15.2.8

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

8.19.2

### Steps to reproduce the behavior

Go to https://primeng.org/tieredmenu, open Chrome dev tools (F12), press CTRL+SHIFT+M to switch to mobile view and press the example menu.

### Expected behavior

Open submenu on the first tap.

**Comment by SoyDiego** [comment]
Hi @r0754497 I have checked the issue and you are right.
I have created a PR fixing the problem. You can check the PR here: https://github.com/primefaces/primeng/pull/13443.
Now we should wait PrimeNG Team approve it if it's ok for them this solution.

Thanks

**Comment by rosenthalj** [comment]
After quickly searching all PrimeNG menu components,  it appears that at a minimum MenuBar and MegaMenu have similar code to TieredMenu.  The TieredMenu is the only component that has ben fixed "fixed" 

MenuBar has the same problem

https://github.com/primefaces/primeng/assets/45439491/31c00ed6-109f-4a58-9e63-25717840b3fc

MegaMenu has the same problem

https://github.com/primefaces/primeng/assets/45439491/3cb6cdcc-6c6e-416b-83a6-4a8fa115a412

Note:  I quickly tested PanelMenu and SlidMenu and they appear to work correctly.

**Comment by SoyDiego** [comment]
> After quickly searching all PrimeNG menu components, it appears that at a minimum MenuBar and MegaMenu have similar code to TieredMenu. The TieredMenu is the only component that has ben fixed "fixed"
> 
> MenuBar has the same problem
> MenuBarTouchBug.mov
> 
> MegaMenu has the same problem
> MegaMenuTouchBug.mov
> 
> Note: I quickly tested PanelMenu and SlidMenu and they appear to work correctly.

Thanks @rosenthalj If you can create different issues will be great and we will try to fix it too.

**Comment by rosenthalj** [comment]
@SoyDiego 

I reviewed your PR changes a second time.  I don't fully understand the changes (my lack of knowledge).  Have you confirmed that your changes don't break the TieredMenu functionality for a desktop browser?

In the movie listed below,  I mouse click on the "File" menu option and then mouse hover over other menu options and finally I click outside the TieredMenu. This is expected desktop behavior (working properly in PrimneNG v16.1.0)

https://github.com/primefaces/primeng/assets/45439491/5bfbf905-e165-4f85-a9db-ab6b131e45ac

**Comment by SoyDiego** [comment]
> @SoyDiego
> 
> I reviewed your PR changes a second time. I don't fully understand the changes (my lack of knowledge). Have you confirmed that your changes don't break the TieredMenu functionality for a desktop browser?
> 
> In the movie listed below, I mouse click on the "File" menu option and then mouse hover over other menu options and finally I click outside the TieredMenu. This is expected desktop behavior (working properly in PrimeNG v16.1.0)
> TiredMenuWorkingProperlyWithDesktopBrowser.mov

When I did all was working perfectly but you can check by yourself using my branch with the changes.

**Comment by rosenthalj** [comment]
@SoyDiego 

I didn't mean to  "go-down-the-rabbit-hole", but ...

I downloaded your [branch](https://github.com/SoyDiego/primeng/tree/13433-fix-doubletap-tieredmenu)

The good news was that when I ran the steps in my previous comment using your branch,  the TieredMenu on a desktop browser worked as expected.  

The bad news is that I performed additional "touch" testing in your TieredMenu  branch and found that contents of submenus of submenus can not be displayed using "touch".

The first movie is using your branch.   It shows that the contents of the file->edit submenu can not be displayed using "touch"

https://github.com/primefaces/primeng/assets/45439491/dd2446f9-856f-4502-a05e-8cc6d7c5bf51

The second movie is from the PrimeNg v16.1.0 demo.   It shows that the contents of the file->edit submenu can be displayed using "touch",  but it takes "two" touches which is equivalent to the original bug.

https://github.com/primefaces/primeng/assets/45439491/62e1c61a-4cf3-4628-9295-7c22f7666001

**Comment by SoyDiego** [comment]
Hi @rosenthalj I have checked and yes, was my error.
I did a new PR because @cetincakiroglu revert the changes when you wrote your comment.
The new PR with the solution is here: https://github.com/primefaces/primeng/pull/13458. 
I tested in mobile, desktop, opening the submenues, and all. Hope now is ok.

If you can check and confirm too will be great and If you have another problem let me know and I will try to fix it!
