### ISSUE TITLE
p-inputNumber -- deprecated keyCode and which used when checking for keypress and keydown

### ISSUE THREAD

**Issue by jiyeol-lee** [primefaces/primeng#13439]
### Describe the bug

for the keyboardEvent, which and keyCode is deprecated and it's recommended to use `key`.

For example
```typescript
onInputKeyDown(event) {
  if (this.readonly) {
    return;
  }
  this.lastValue = event.target.value;
  if (event.shiftKey || event.altKey) {
    this.isSpecialChar = true;
    return;
  }
  let selectionStart = event.target.selectionStart;
  let selectionEnd = event.target.selectionEnd;
  let inputValue = event.target.value;
  let newValueStr = null;
  if (event.altKey) {
    event.preventDefault();
  }

  // we should use "event.key" in here
  // original code uses "event.which"
  switch (event.key) {
    //up
    case 'ArrowUp':
      // ...
      break;
    //down
    case 'ArrowDown':
      // ...
      break;
    //left
    case 'ArrowLeft':
      // ...
      break;
    //right
    case 'ArrowRight':
      // ...
      break;
    //enter
    case 'Enter':
      // ...
      break;
    //backspace
    case 'Backspace': {
      // ...
      break;
    }
    // del
    case 'Delete':
      // ...
      break;
    default:
      break;
  }
  this.onKeyDown.emit(event);
}

onInputKeyPress(event) {
  if (this.readonly) {
    return;
  }
  event.preventDefault();
  // so we can just use "event.key"
  // and change "48 <= code && code <= 57" to "/^\d$/.test(char)"
  let code = event.which || event.keyCode;
  let char = String.fromCharCode(code);
  const isDecimalSign = this.isDecimalSign(char);
  const isMinusSign = this.isMinusSign(char);
  if ((48 <= code && code <= 57) || isMinusSign || isDecimalSign) {
    this.insert(event, char, { isDecimalSign, isMinusSign });
  }
}
```

### Environment

I was testing using @testing-library/dom and  @testing-library/user-event and tried to type on inputNumber tag but nothing works because @testing-library did not implement keyboard event for `which` and `keyCode`. Once I change them to `key`, my test cases pass like magic.

### Angular version

14.2.3

### PrimeNG version

14.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Browser(s)

ALL

**Comment by NateRadebaugh** [comment]
@cagataycivici  are you open to a PR to fix this? Is this in scope for the v18 release?

I understand accessibility is documented as being supported, but it seems to mostly be related to contrast and does not clarify details of keyboard support
> https://primeng.org/guides/accessibility

**Comment by NateRadebaugh** [comment]
Looks like that PR that was closed without merging is still the right fix and was not applied to the latest codebase.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
