### ISSUE TITLE
pDialog: [breakpoints] renders inline styling without nonce attribute

### ISSUE THREAD

**Issue by kp-xcess** [primefaces/primeng#13438]
### Describe the bug

As of v16, Angular supports defining and rendering nonce attributes for its inline style and script elements. This seems to work well with the PrimeNG components for the biggest part.

There is however an exception that I discovered today: when using a p-dialog element and specifying [breakpoints](https://primeng.org/dialog#api.dialog.props.breakpoints), it generates an inline style element containing a `@media` style. This element does not have a nonce attribute set. When using CSP, this causes an error in the browser console, for example:
> Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'nonce-Oq6WB1UgsEIzd+dweOxV0dN0mUuXxxAstBU6ehnD9H0='". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution.

And this is an example of the inline style element that is generated (in my case, content may of course vary depending on your breakpoints value):
![image](https://github.com/primefaces/primeng/assets/7505668/8d9d0497-dbfb-4926-9b4a-723828dbe092)

The workaround is to not use the breakpoints property and instead include the CSS generated by PrimeNG directly into my own components CSS.

### Environment

OS: **Windows 11**
Browser: **Brave v1.56.14** (basically Chrome). But happens with all browsers that enforce CSPs.

### Output of _ng version_:
Angular CLI: 16.1.5
Node: 16.19.1
Package Manager: npm 9.3.0
OS: win32 x64

Angular: 16.1.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.5
@angular-devkit/build-angular   16.1.5
@angular-devkit/core            16.1.5
@angular-devkit/schematics      16.1.5
@angular/cdk                    16.1.5
@angular/cli                    16.1.5
@schematics/angular             16.1.5
ng-packagr                      16.1.0
rxjs                            6.6.7
typescript                      5.1.6
zone.js                         0.13.1

### Angular version

16.1.5

### PrimeNG version

16.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.19.1

### Steps to reproduce the behavior

1. Make sure to add CSP (my suggestion is to use the Report-Only variant), either as a response header from your backend, or as a meta tag in your index.html. Use this value:
> connect-src http: https: ws: wss: localhost:*;block-all-mixed-content ;child-src 'self';default-src 'self' data:;frame-ancestors 'none';object-src 'none';upgrade-insecure-requests ;script-src 'self' 'nonce-SomeNoncense';style-src 'self' 'nonce-SomeNoncense'
2. Add **ngCspNonce="SomeNoncense"** to your _app_ element in Angular's index.html.
3. Add a working **p-dialog** to your component.
4. Define and set the breakpoints attribute with some values.
5. Open up your browser console (F12).
6. Watch and behold...

### Expected behavior

It is okay to render inline style elements, but it should look like this instead (based on my example):
```html
<style type="text/css" class="ng-tns-c4292766971-2" nonce="SomeNoncense">
    @media screen and (max-width: 960px) {
            .p-dialog[pn_id_5] {
                width: 600px !important;
        }
    }
</style>
```

Use Angulars [CSP_NONCE](https://angular.io/api/core/CSP_NONCE) injection token to retrieve the nonce to use.

**Comment by koesper** [comment]
@kp-xcess Have you ever found a solution? I believe i'm running into the same issue

**Comment by kp-xcess** [comment]
> @kp-xcess Have you ever found a solution? I believe i'm running into the same issue

I have so far stuck with my own workaround (ie. the one I described within this issue).

Since the folks from PrimeTek have not responded to this issue at all (...) and you are still running into it, presumably using the current latest stable version(?), I'm guessing that it has not been solved yet.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
