### ISSUE TITLE
Accessibility | Breadcrumb - separetors aren't hidden and the list is not wrapped in a `nav` element

### ISSUE THREAD

**Issue by GiacomoDM** [primefaces/primeng#13437]
### Describe the bug

The Breadcrumb component doesn't follow the [Accessibility section](https://primeng.org/breadcrumb#accessibility) description.
The `li`s used as separators don't have `aria-hidden="true"` and the `ul` tag is inside a `div` instead of a `nav`. 

### Environment

Windows

### Reproducer

https://primeng.org/breadcrumb

### Angular version

16.X

### PrimeNG version

16.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.20

### Steps to reproduce the behavior

1. Open the https://primeng.org/breadcrumb page
2. Inspect the first example for the Breadcrumb component
3. The `li`s used as separators don't have `aria-hidden="true"` and the `ul` tag is inside a `div` instead of a `nav`. 

### Expected behavior

As described in the Accessibility section of the component's documentation.

**Comment by StefaniOSApps** [comment]
same

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
