### ISSUE TITLE
router for menus?

### ISSUE THREAD

**Issue by vrmerlin** [primefaces/primeng#1344]
I'm new to primeNG, and am finding the menus challenging. I would like to use the menubar, but want to use the commands, not a router. Unfortunately, as has been discussed in other issues, the menubar throws the "No provider for Router!" error if you don't provide a router.

So, is there an example that specifies how to provide a minimum router, when you are actually using commands? I poked around on the internet, and found some examples (for this specific problem), but the solutions don't work, I think because they were targeted at old, obsolete Angular 2 versions. 

I followed these directions here, which look fairly new:
https://www.reddit.com/r/Angular2/comments/54p0mm/primeng_tab_router_question/

Now, the menus do indeed come up, but in the console, I'm getting "Cannot find primary outlet to load 'DockingMainComponent'". How do I make that go away? Can you add an example to the menu documentation to explain how set this up for just menu commands, not routes?

Thanks,
John

**Comment by cagataycivici** [comment]
Doesn't your app have a router?

**Comment by vrmerlin** [comment]
No,  I don't think I need one.  I'm using NW.js to make a desktop app, and Phosphorus.js as a docking framework.  So I want the menus to just trigger javascript code that kicks off docking panels as needed by the user.

**Comment by vrmerlin** [comment]
Hopefully I can get a response to my question above? I've been pouring over the internet trying to get a basic routing going in order to make these menus work (when no routing is actually needed), and can't figure it out. Is it possible to have a menu of just commands, not routes?

**Comment by cagataycivici** [comment]
Currently router is required by the menu components I'm afraid, we couldn't find an easier way not depend on it. Feedback is welcome.
