### ISSUE TITLE
p-radioButton: Cannot initialize form group with inital value

### ISSUE THREAD

**Issue by Triskae** [primefaces/primeng#13446]
### Describe the bug

When I create a p-radio group with a reactive form I cannot initialize de component with an initial value.
Here is an example [Stackblitz](https://stackblitz.com/edit/wnctrn?file=src%2Fapp%2Fdemo%2Fradio-button-reactive-forms-demo.html)

### Environment

"@angular/core": "^16.1.7",
"primeng": "^16.1.0"

### Reproducer

https://stackblitz.com/edit/wnctrn?file=src%2Fapp%2Fdemo%2Fradio-button-reactive-forms-demo.html

### Angular version

16.1.7

### PrimeNG version

16.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.2.0

### Browser(s)

Brave: 1.56.14 Chromium: 115.0.5790.114

### Steps to reproduce the behavior

Go to stackblitz, or create a group of radio button. Add a reactive form to it, try to initiate the form with a value.

### Expected behavior

The expected result is the corresponding radio button selected with the value specified in the initialization of the reactive form.

**Comment by Cr3aHal0** [comment]
This problem is still present in the latest release. In the current state, the value you're initializing the form with must be the same reference as one of the options provided, given you want the value to be an object and not a primitive value.

In your case, if you want to make it work awaiting for a "fix", you can replace the current setValue/patchValue with : 
`this.formGroup = new FormGroup({
      selectedCategory: new FormControl(this.categories[0]),
});`

**Comment by Triskae** [comment]
Hello, Thanks for the fix !! Indeed, it seems to work, until it's fixed is the way to go, but imo, the good to to do, is to check if the initial 'key' value exist in the possible input values, and if it's the case, auto select the right radio ...

**Comment by Cr3aHal0** [comment]
Hi,
You 're welcome. There is a fresh discussion about providing the same kind of mecanism other components such as Dropdown already got to handle such type of value. Combobox & Radio are a bit different as they're handled one by one on the component level while Dropdown (i.e.) is all about handling a set of options but we'll see where this will land :)

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
