### ISSUE TITLE
MenuBar and MegaMenu: On mobile menubar and megamenu both requires double tap to open submenu

### ISSUE THREAD

**Issue by rosenthalj** [primefaces/primeng#13447]
### Describe the bug

MenuBar  and MegaMenu both requires 2 touches to open a submenu. One focusses, next one opens. Required fix: touch to have the same behaviour as hover on menu items with submenu.

Same exact issue as Issue #13433 but for MenuBar and MegaMenu.  This problem has been just been fixed and closed for TieredMenu.  The pull request file [tieredmenu.ts](https://github.com/primefaces/primeng/pull/13443/files#diff-0f78da967be578fe31289e62b917434f52f9902618913c827f6388d7de7fc3c0)  has been updated,  but similar changes have not been made to menubar.ts and megamenu.ts.

https://github.com/primefaces/primeng/assets/45439491/b57abfc3-4347-4d3a-b76b-0994c8bea8bb

https://github.com/primefaces/primeng/assets/45439491/98c53460-625c-4944-a0fb-de5e1c3d74c9

### Environment

Same exact environment  as Issue #13433

### Reproducer

https://primeng.org/menubar and https://primeng.org/megamenu

### Angular version

16.x

### PrimeNG version

16.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

same node version as issue #13433

### Browser(s)

same browsers as issue #13433

### Steps to reproduce the behavior

same steps to reproduce as issue #13433 but with MegaMenu and MenuBar

Go to https://primeng.org/menubar or https://primeng.org/mega menu, open Chrome dev tools (F12), press CTRL+SHIFT+M to switch to mobile view and press the example menu.

### Expected behavior

Open submenu on the first tap.

**Comment by cetincakiroglu** [comment]
Fixed in https://github.com/primefaces/primeng/commit/05b9bcf62bc6054f986c90c8f46e4dc7f53d8f20
