### ISSUE TITLE
Table:- In the Table row grouping(rowGroupMode="rowspan") with selectionMode="multiple" , On the hover over the second row of any group, the Representative column is not highlighting.

### ISSUE THREAD

**Issue by megharajak-05** [primefaces/primeng#13448]
### Describe the bug

Table:- In the Table row grouping(rowGroupMode="rowspan") with selectionMode="multiple" and [metaKeySelection]="true" , On hover over the second row of any group, the Representative column is not highlighting.

![image](https://github.com/primefaces/primeng/assets/139353448/fcca9e3a-1364-41a4-ba69-75ac8d1d791e)
.
![image](https://github.com/primefaces/primeng/assets/139353448/c91b0ccb-a28d-44d3-a56c-e34e2e8eb689)

### Environment

"primeng": "16.1.0",

https://stackblitz.com/edit/getneq?file=src%2Fapp%2Fdemo%2Ftable-rowspan-grouping-demo.html,src%2Fapp%2Fdemo%2Ftable-rowspan-grouping-demo.ts,package.json

### Angular version

16.0.0

### PrimeNG version

16.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.16.0

### Browser(s)

Chrome, WebView2

### Steps to reproduce the behavior

1. Hover over first row on any group, the Representative column is highlighting.
2. Hover over second row/any other row (except the first row) of that group, the Representative column is not highlighting.

### Expected behavior

Hover over second row/any other row of that group, the Representative column should be highlighted.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
