### ISSUE TITLE
Component: p-menu - the first menu item preselected by default

### ISSUE THREAD

**Issue by lexzhukov** [primefaces/primeng#13441]
### Describe the bug

The p-menu component in the popup mode highlights the first item as focused by default when it's opened. 
This issue is reproducible on the official documentation page, https://primeng.org/menu#popup.
![image](https://github.com/primefaces/primeng/assets/12192373/f745ee60-67de-44dc-a956-74c089ddbd2d)

### Environment

The PrimeNG documentation.

### Angular version

16.1.8

### PrimeNG version

16.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.5.0

**Comment by SoyDiego** [comment]
For accessibility that is the correct functionality.

**Comment by cetincakiroglu** [comment]
Please read the accessibility section of the related component. Closing the issue since it's invalid.
