### ISSUE TITLE
Component: InputNumber - possible to add unlimited number of dots and fraction numbers on Android phone

### ISSUE THREAD

**Issue by AndrewAKovalenko** [primefaces/primeng#13451]
### Describe the bug

It's possible to add multiple dots on android, and maxFractionDigits is ignored (on screenshot `[maxFractionDigits]="2"` )

Also sometimes there is problems with deletion of fraction digits

https://primeng.org/inputnumber#numeral

![image](https://github.com/primefaces/primeng/assets/34687666/7b04eae1-c522-4032-82f2-183585536033)

### Environment

Samsung Galaxy S10

### Angular version

16.1.7

### PrimeNG version

16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.16.0

### Browser(s)

Latest Chrome

### Steps to reproduce the behavior

1. Create input number component with `maxFractionDigits`
2. Try to add multiple dots
3. Observe result
4. Try to add more fraction digits, than allowed and observe result
5. Try to add and delete dots and fraction digits multiple times, observe wrong behavior

### Expected behavior

User should be able to add only one dot, that splits fraction digits from integer part of number on Android
User should be able to add only defined amount of fraction digits  on Android
User should be able to delete fraction digits and dot on Android

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
