### ISSUE TITLE
Button: loading style issue when already has an icon

### ISSUE THREAD

**Issue by gerjon-eatch** [primefaces/primeng#13459]
### Describe the bug

Looks like this bug's fix: #13148 was undone on master, and therefore never made it into e.g. the 16.1.0 release.

### Environment

See #13148

### Reproducer

https://stackblitz.com/edit/r6awcv?file=package.json,src%2Fapp%2Fdemo%2Fbutton-loading-demo.html

### Angular version

16

### PrimeNG version

16.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.15.0

### Browser(s)

all

### Steps to reproduce the behavior

See #13148

### Expected behavior

See #13148

**Comment by cetincakiroglu** [comment]
Hi,

Related PR is merged and this bug is fixed right now and it's included in the current milestone. Closing the issue since it's duplicate. 

Thanks for the reporting!
