### ISSUE TITLE
TabMenu: Disabled items are no longer rendered

### ISSUE THREAD

**Issue by ChristiaanNel** [primefaces/primeng#13454]
### Describe the bug

The TabMenu component does not render disabled menu items anymore since version 16.1.0.

I suspect that the following line changed this behaviour while implementing some accessibility features, which changed the component to only render focusable items:
https://github.com/primefaces/primeng/pull/13372/files#diff-17544e54cbbf575382fec88dd6fcaec56549fe759ec76917cc650aac12b2bb60R217

### Environment

Windows

### Reproducer

https://stackblitz.com/edit/github-93mbu7-xddcmq?file=src%2Fapp%2Fapp.component.ts

### Angular version

16

### PrimeNG version

16.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

19.4.0

### Steps to reproduce the behavior

1. Create a TabMenu component
2. Bind the component to a list of MenuItem
3. Set one of the items to disabled, by setting its `disabled` property to `true`

### Expected behavior

I would expect the menu item to still be rendered, but styled in a way to indicate that it is disabled, as it was rendered before version 16.1.0.

**Comment by cetincakiroglu** [comment]
Thanks for reporting the issue, since the accessibility implementation is a giant update, some functionalities may be broken unintentionally. We're looking forward to fix this issue.
