### ISSUE TITLE
fileUpload: conversion uses 1000 instead of 1024 for file size formatting

### ISSUE THREAD

**Issue by ajjp** [primefaces/primeng#13467]
### Describe the bug

formatSize function uses a base of 1000 instead of 1024 which causes inaccurate units conversion

### Environment

![image](https://github.com/primefaces/primeng/assets/106910824/c239d916-6560-42f9-9440-f061d8ec5d85)

### Angular version

16.1.3

### PrimeNG version

16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.17.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. input maxFileSize = 10485760 (10 MB)
2. conversion returns 10.5 MB instead of 10 MB

### Expected behavior

Accurate size conversion

**Comment by SoyDiego** [comment]
Hi @ajjp, I have created a PR changing that
You can check here: https://github.com/primefaces/primeng/pull/13473/files
Now we should wait PrimeNG Team approve it soon.

Thanks

**Comment by ldesgrange** [comment]
The original code seemed (almost) fine to me:
- either use a 1000 factor and SI decimal prefixes (**k** (lowercase), M, G, T, P, E, Z, Y),
- or use a 1024 factor and IEC binary prefixes (Ki, Mi, Gi, Ti, Pi, Ei, Zi, Yi),
but don't mix one with the other, see https://en.wikipedia.org/wiki/Binary_prefix
