### ISSUE TITLE
Dropdown: onModelChange in "set options" causing ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by israelrios** [primefaces/primeng#13465]
### Describe the bug

The introduction of a onModelChange call in the "set options" method causes ExpressionChangedAfterItHasBeenCheckedError because de view was already checked most of time at this point. I recently upgraded from primeng 12 to 15 and that change broke almost all the views that use a dropdown. I'd like to suggest removing it and leaving the model with the value it already has even when not in the options.

### Environment

Medium complexity app with large views.

### Reproducer

https://stackblitz.com/edit/github-t9imek-vaf8tt?file=src%2Fapp%2Fapp.component.html&file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

### Angular version

15.2.9

### PrimeNG version

15.2.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.20.1

### Steps to reproduce the behavior

Go to https://stackblitz.com/edit/github-t9imek-vaf8tt?file=src%2Fapp%2Fapp.component.html&file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

Click in the button. Look at the console.

### Expected behavior

No exception is throw.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
