### ISSUE TITLE
Dropdown: Escape Key event not default prevented

### ISSUE THREAD

**Issue by JanST123** [primefaces/primeng#13463]
### Describe the bug

When closing a dropdown overlay via 'Escape' Key on keyboard, the event is not default prevented. Therefore other components cannot detect that this keyboard event was already processed.

### Environment

Angular 16 with primeNG 16

### Angular version

16.0.5

### PrimeNG version

16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Steps to reproduce the behavior

1. Use a dropdown in a dialog that closed on 'Escape' key event
2. Open dropdown
3. Press 'Escape' key
4. Dropdown overlay AND the dialog closes

### Expected behavior

The dropdown should close but the dialog should recognize that `event.defaultPrevented` is `true` and should not close

**Comment by gucal** [comment]
Hi, 
Good catch, thank you!
