### ISSUE TITLE
Input components should support left icon

### ISSUE THREAD

**Issue by MAN-Sendance** [primefaces/primeng#13460]
### Describe the feature you would like to see added

At the moment only InputText component in combination with pInputText directive supports left icon.

However, it would be great if also other input components would support left icon e.g. Password, InputNumber. 

At the moment this is not possible since e.g. InputNumber does not have a directive and the tag version p-inputNumber does not support child nodes.

### Describe the solution you'd like

Input Components should support left icons (by either supporting directives or by taken child elements).

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
