### ISSUE TITLE
Component: ContextMenu

### ISSUE THREAD

**Issue by oriebalzyuot96** [primefaces/primeng#13468]
### Describe the bug

 once I click Right I need to override model Property(items array that show on context menue  ) with new data 

this issue in new version . in last version I over ride propty model like (this.context menu.model )and data in array is changed in last version I cannot did the same approach I notice in code property called ('processedItems')

but I cannot over ride ,, any help ?? for now I used this.contextMenu["_processedItems"] =  new data  
but in this way in my code I create new array with same interface of _processedItems .interface had index parenet .... etc 

so can please reply with the best solution

the code I used 
```

in ts   @ViewChild('contextMenu') contextMenu: ContextMenu;
showContextMenu (){
     this.contextMenu1.model   =  ( newArray ) //in last version 

   this.contextMenu1["_processedItems"] = ( newArray ) //in last version  but I need to create new aarray of my item with same interface of _processedItems 

}


for now I use 

    this.contextMenu["_processedItems"] = this.createProcessedItems(this.contextMenuItems|| [])
i used same function in documentation 
 createProcessedItems(items: any, level: number = 0, parent: any = {}, parentKey: any = '') {
        const processedItems = [];

        items &&
            items.forEach((item, index) => {
                const key = (parentKey !== '' ? parentKey + '_' : '') + index;
                const newItem = {
                    item,
                    index,
                    level,
                    key,
                    parent,
                    parentKey
                };

                newItem['items'] = this.createProcessedItems(item.items, level + 1, newItem, key);
                processedItems.push(newItem);
            });

        return processedItems;
    }

```

in html 
```
  <p-contextMenu[model]="contextMenuItems" [appendTo]="'body'" #contextMenu></p-contextMenu>
   <div (contextmenu)="$event?.preventDefault();showContextMenu($event,node)"></div>
```

### Environment

windows

### Angular version

16

### PrimeNG version

16

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.13.0

### Expected behavior

when    this.contextMenu.model = new data .. it should work

**Comment by nemo-js** [comment]
I face the same issue. 

_processedItems_ getter sets the _processedItems private field only the first time, so when _items_ reference changes, the _processedItems field is not updated anymore.

**Comment by cetincakiroglu** [comment]
Could you please create a stackblitz example by forking this https://stackblitz.com/edit/x5xydd?file=package.json

**Comment by cetincakiroglu** [comment]
Thanks for reporting the issue, this issue can be seen across all of the menu components after the accessibility update, I've just opened a more generic issue that covers all the menu components in here https://github.com/primefaces/primeng/issues/13471

You can track the issue on the link above, closing this issue since it's only related to contextmenu.

Thank you for your effort and support!
