### ISSUE TITLE
Datatable Row Expansion not work if columns added by *ngFor

### ISSUE THREAD

**Issue by ihabZhaika** [primefaces/primeng#1346]
Hi,
i added Row Expansion to my table , but when i click the arrow t o show it ,in case if table columns added by *ngFor it displays little box with no content , in case i added the columns manually it shows the content

Working code
```
<p-dataTable [value]="commodities"  selectionMode="single" [globalFilter]="globalFilter" [rows]="15"
             scrollable="true" [paginator]="true"     [(selection)]="selectedRow" 
             [globalFilter]="globalFilter" sortMode="multiple" expandableRows="true">
  <p-column expander="true" styleClass="col-icon"></p-column>

  <p-column field="no"    [filter]="true" [sortable]="true" [header]="TYPE_NUMBER"></p-column>
  <p-column field="name"  [filter]="true" [sortable]="true" [header]="NAME"></p-column>
  <p-column field="price" [filter]="true" [sortable]="true" [header]="PRICE"></p-column>


  <template >
    <h1>Testing Row Expansion</h1>
  </template>
</p-dataTable>

```

not working code

``` 
<p-dataTable [value]="commodities"  selectionMode="single" [globalFilter]="globalFilter" [rows]="15"
             scrollable="true" [paginator]="true"     [(selection)]="selectedRow"
             [globalFilter]="globalFilter" sortMode="multiple" expandableRows="true">
  <p-column expander="true" styleClass="col-icon"></p-column>

  <p-column *ngFor="let col of columns"  [field]="col.field" [header]="col.header" [filter]="col.filter" [sortable]="col.sortable" > </p-column>

  <template >
    <!--{{customer.commodities |json}}-->
    <h1>Testing Row Expansion</h1>
  </template>
</p-dataTable>
```

So what to do in this case ?

**Comment by sgomanf** [comment]
I have the same problem, it was working until angular version 2.1.x

**Comment by bogacg** [comment]
I had similar problem when I've upgraded Angular to v.2.2.1, reverting back to v2.1.2 fixed it

**Comment by sgomanf** [comment]
Continue the problem even in version 1.0.0.RC6

**Comment by sgomanf** [comment]
I installed the latest version of PrimeNG (1.0.0) and it still does not work. The first click expands normally, the successive displays the table empty. What am I doing wrong?

`<div class="ui-grid-row" *ngIf="detliquidac">
	<p-panel header="CONCEPTOS" class="ui-grid-col-12">

		<p-dataTable [value]="detliquidac" expandableRows="true" resizableColumns="true">

			<p-column [expander]="true" styleClass="col-icon" [style]="{'width':'5%'}"></p-column>

			<p-column header="PERIODO" [style]="{'width':'12%'}">
				<template let-col let-row="rowData" pTemplate type="body">
					<span style="float:center">{{ getPeriodo(row)}}</span>
				</template>
			</p-column>
			<p-column field="dencos" header="O.SOCIAL" [style]="{'width':'30%'}"></p-column>
			<p-column header="CONCEPTO">
				<template let-col let-row="rowData" pTemplate type="body">
					<span>{{ row["cptoden"] + (row["cptodesc"] ? ' - ' + row["cptodesc"] : '') }}</span>
				</template>
			</p-column>
			<p-column header="IMPORTE" [style]="{'width':'13%'}">
				<template let-col let-row="rowData" pTemplate type="body">
					<span style="float:right">{{getImporte(row) | number:'1.2-2'}}</span>
				</template>
			</p-column>

			<template let-row pTemplate type="body">
				<div class="ui-grid ui-grid-responsive ui-fluid" style="font-size:16px;padding:1px">
					<div class="ui-grid-row">
						<div class="ui-grid-col-12" style="text-align:left">
							<table style="width:100%">
								<thead style="background-color:honeydew;">
									<td style="width:25%">Nombre</td>
									<td style="width:25%">Efector</td>
									<td style="width:4.4%; text-align: center; padding-left:1px; padding-right:1px;">Ca</td>
									<td>Prestacion</td>
									<td style="width:10%; text-align: center">Importe</td>
								</thead>
								<tr *ngFor="let it of row.liquidDetList">
									<td>{{it.apyn}}</td>
									<td>{{it.efector}}</td>
									<td>{{it.cant}}</td>
									<td>{{it.prestac}}</td>
									<td style="text-align: right; padding-left:1px; padding-right:2px;">{{it.importe | number:'1.2-2'}}</td>
								</tr>
							</table>
						</div>
					</div>
				</div>
			</template>

		</p-dataTable>

	</p-panel>
</div>`

**Comment by sgomanf** [comment]
Related: angular/angular#13080

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/MxSw4qOuwDfq7rLO7jrR?p=preview
