### ISSUE TITLE
p-overlayPanel does not hide automatically after scrolling

### ISSUE THREAD

**Issue by idzeravianka** [primefaces/primeng#13462]
### Describe the bug

The overlay panel does not automatically hide when it uses scrolling, when the content does not fit in the container specified by the height, and the user scrolls the scrollbar with a mouse click instead of a wheel.

### Environment

Windows/MacOS

### Reproducer

https://stackblitz.com/edit/ppug2d?file=src%2Fapp%2Fdemo%2Foverlay-panel-template-demo.html

### Angular version

16.0.0

### PrimeNG version

16.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

any

### Browser(s)

Chrome v114.0.5735.198

### Steps to reproduce the behavior

1. Open the provided StackBlitz.
2. Click 'Show' button to open overlay panel.
3. Using the left mouse button (do not use the mouse wheel) scroll the content to the middle.
4. Сlick the left mouse button anywhere in the document outside the overlay panel container (you will see that the panel is not closed).
5. Click again outside the overlay panel and the panel will close.

### Expected behavior

Panel closes after first click outside the panel

**Comment by SoyDiego** [comment]
Hi @idzeravianka, I have checked the problem and you are right.
I did a PR with a possible solution, you can check here: https://github.com/primefaces/primeng/pull/13480
If you can check or If you find something, let me know.
Now we should wait the PrimeNG Team approve it if it's ok for them.
