### ISSUE TITLE
InputText | Add ariaLabel and ariaLabelledBy inputs (accessibility) 

### ISSUE THREAD

**Issue by Gykonik** [primefaces/primeng#13472]
### Describe the feature you would like to see added

In the documentation the usage of `aria-label` is defined - however the `pInputText` directive doesn't provide `ariaLabel` property.

**Comment by mehmetcetin01140** [comment]
Hi, 

We apologize for the delayed response. Our team began implementation for accessibility with version 16.5x and successfully completed the accessibility implementation with version 16.9.1 after intensive work and meticulous study. The mentioned issue might have been resolved between these versions. If the problem persists in PrimeNG v17, please feel free to open a new issue without hesitation. Thanks for reporting the issue!
