### ISSUE TITLE
Tree Mapper

### ISSUE THREAD

**Issue by cagriman** [primefaces/primeng#13470]
### Describe the feature you would like to see added

Hi everyone,

Is it possible to draw new links by dragging between two tree.

I saw sample in gojs. see; https://gojs.net/latest/samples/treeMapper.html

![image](https://github.com/primefaces/primeng/assets/40563072/fcf2a217-c64e-485c-8588-8db2a306c033)

How can i do similar to this design in PrimeNG

Thanks

Cheers

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
