### ISSUE TITLE
Dialog Draggable

### ISSUE THREAD

**Issue by oriebalzyuot96** [primefaces/primeng#13479]
### Describe the bug

we can draggable dynamic dialog  and dialog using header. if move the mouse to body content then draggable icon disappeared. we Cannot Drag

### Environment

Windows

### Reproducer

https://primeng.org/dynamicdialog

### Angular version

16

### PrimeNG version

16

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.13.0

### Expected behavior

draggable allow in any place in component in footer and body not just header this isssue for dialog , daynamic dialog 

and cab added this feature for confirm dialog .

**Comment by SoyDiego** [comment]
Hi @oriebalzyuot96, in my opinion it's ok can be draggable when you are only in the header of the dialog.
Imagine you have a button in the body,  and when the user press "click", maybe can move the window doing that by accident. That behaviour is not good for UX/UI.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
