### ISSUE TITLE
[PrimeNg]Table:- The drag and drop feature is not working when we select multiple rows within the PrimeNG table's row grouping (configured with rowGroupMode="rowspan" and selectionMode="multiple").

### ISSUE THREAD

**Issue by rajatchouksey07** [primefaces/primeng#13487]
### Describe the bug
The functionality of selecting multiple rows within the PrimeNG table's row grouping (using rowGroupMode="rowspan") and selectionMode="multiple" with drag and drop feature is not working as expected.

It work only if single row with in that row group is selected.

### Environment

"primeng": "16.0.2"

https://stackblitz.com/edit/getneq-cgsmaj?file=src%2Fapp%2Fdemo%2Ftable-rowspan-grouping-demo.html,src%2Fapp%2Fdemo%2Ftable-rowspan-grouping-demo.ts,package.json

### Angular version

16.0.0

### PrimeNG version

16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.0.0

### Browser(s)

Chrome, WebView2

### Steps to reproduce the behavior

In prime-ng table,
1. Select multiple rows with in the row group "
![image](https://github.com/primefaces/primeng/assets/32260131/11c63170-9b4c-4125-954c-1774f7789923)

2. Drag and Drop selected row group to differrent index/position in the PrimeNG table
![image](https://github.com/primefaces/primeng/assets/32260131/21fc9436-939d-42d6-9233-1d0454dc162c)

Actual:- Drag and Drop happens only for the last selected row of that group.

### Expected behavior

All the rows of that group must be dragged and dropped to respective position/index in the table.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
