### ISSUE TITLE
pButton | Loading icon not removing

### ISSUE THREAD

**Issue by GiacomoDM** [primefaces/primeng#13489]
### Describe the bug

Only with the directive `pButton`, when the loading status of a button with a an icon changes, the loading indicator is not removed: 
![image](https://github.com/primefaces/primeng/assets/25552695/3263689e-d29c-4210-898f-8ca119967cab)

Using the component `p-button` instead of the directive works. 

### Environment

Windows

### Reproducer

https://stackblitz.com/edit/gmhqyu?file=src%2Fapp%2Fdemo%2Fbutton-loading-demo.html

### Angular version

16.X

### PrimeNG version

16.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.20

### Steps to reproduce the behavior

1. Open the provided stackblitz
2. Click on any button to start the loaders
3. After 2 seconds the loaders stops, but the loading icon is not removed for the buttons with the directive `pButton`

### Expected behavior

At step 3, `pButton` should behave the same a `p-button`.

**Comment by knightSarai** [comment]
Using `p-button` might break some styles, a work around this is to supply loadingIcon, something like this:
`
<button
          pButton
          type="button"
          icon="pi pi-search"
          loadingIcon="pi pi-spin pi-spinner"
          [loading]="loading"
>
</button>
`

**Comment by LexanRed** [comment]
I can confirm this issue. In my case it was the other way round, the spinner did not show up despite the loading property changing from false to true. 

When supplying the loadingIcon as @knightSarai mentioned, it works.
