### ISSUE TITLE
Component: InputTextarea

### ISSUE THREAD

**Issue by marioosh-net** [primefaces/primeng#13484]
### Describe the bug

InputTextarea with autoResize=true have issues like below:
- Click on not focused textarea makes scroll up;
- Click outside on focused textarea makes scroll up;

### Environment

Chrome browser on Windows 10

### Reproducer

https://stackblitz.com/edit/ib29s9

### Angular version

16.0.0

### PrimeNG version

16.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.20.0

**Comment by SoyDiego** [comment]
Hi @marioosh-net, I have checked the problem and you are right.
I did a PR solving the problem. You can check it here: https://github.com/primefaces/primeng/pull/13495
Now we should wait PrimeNG Team approve it if they think the solution is OK for them.
