### ISSUE TITLE
feat: Calendar: expose input date parsing error messages

### ISSUE THREAD

**Issue by ribizli** [primefaces/primeng#1349]
I need to show to the user an error message if an invalid date format is entered in the input filed (I'll do this with a custom validator in a wrapper component).

Can you please add a filed `parseError` and set to `null/undefined` or to the caught thrown error from `parseValueFromString()`?

I can also create a PR if you like, please let me know.

**Comment by ribizli** [comment]
My current solution is, that I patch Calendar's `onInput` method:

```
  @ViewChild(Calendar) private _calendar: Calendar;
  ngOnInit() {
    if (this._calendar) {
      let origOnInput = this._calendar.onInput;
      this._calendar.onInput = (event) => {
        this._inputFieldValue = event.target.value;
        origOnInput.call(this._calendar, event);
      };
    }
  }
```
Next I do validation based on the fact that the model value is `null` but there is something entered in the input.

**Comment by cagataycivici** [comment]
Please create a PR and we'll discuss there, it is not super clear to me.
