### ISSUE TITLE
Menu & TrieredMenu - add option to inject custom icons by template or model

### ISSUE THREAD

**Issue by zygarios** [primefaces/primeng#13496]
### Describe the feature you would like to see added

I would kindly ask for the addition of a feature allowing the injection of custom icons using the appropriate ng-template within the Menu and TieredMenu components.

Currently, it's only possible to load icons from the PrimeIcons library. 

### Is your feature request related to a problem?

Currently, we are in the process of migrating our project from Angular Material to PrimeNG. However, the lack of templates for custom fragment definition is significantly impeding our progress. One of such components is the Menu and TieredMenu mentioned above. We extensively use our own icons in the project and would like to have independence in this aspect.

### Describe the solution you'd like
It would be highly beneficial to have the option of defining custom icons, preferably along with the entire content for each individual row:
```
<p-menu [model]="items">
   <ng-template pTemplate="rowItem" let-item="item">
      <img src="src/assets/custom-icon.svg"><span>{{item.content}}</span>
   </ng-template>
</p-menu>
```

### Describe alternatives you have considered
Alternatively, an option could be added to the model for passing icons in a format other than "pi pi-fw", for example:

```
items = [
    {
        label: 'New',
        icon: 'pi pi-fw pi-plus',
    },
    {
        label: 'Delete',
        iconSrc: 'src/assets/custom-icon.svg'
    }
];
```

### Additional context
![image](https://github.com/primefaces/primeng/assets/40625750/6bfd9f24-de70-494e-8f69-691dba0606a4)

_No response_

**Comment by saver711** [comment]
any progress on that ?

**Comment by kewo22** [comment]
any fixes for this ?

**Comment by kewo22** [comment]
This worked for me 

`
    this.items = [
      {
        label: 'Lbl 1',
        icon: 'custom-icon-1',
      },
      {
        label: 'Lbl 2',
        icon: 'pi pi-star-fill',
      },
      {
        label: ':bl 3',
        icon: 'custom-icon-2',
      },
    ];
`

`:host ::ng-deep {
  .custom-icon-unread-1{
    width: 1rem;
    height: 1rem;
    background-image: url("/assets/.../icon.svg");
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
  }
  .custom-icon-2 {
    width: 1rem;
    height: 1rem;
    background-image: url("/assets/.../icon.svg");
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
  }
}
`

**Comment by kewo22** [comment]
this.items = [ { label: 'Lbl 1', icon: 'custom-icon-1', }, { label: 'Lbl 2', icon: 'pi pi-star-fill', }, { label: ':bl 3', icon: 'custom-icon-2', }, ];`
`

**Comment by EXayer** [comment]
Or you can use custom template as documentation suggests

https://primeng.org/customicons

```
    <p-menu #menu [model]="items" [popup]="true">
      <ng-template pTemplate="item" let-item>
        <a *ngIf="!item?.url" [attr.tabindex]="-1" class="p-menuitem-link" [routerLink]="item.routerLink">
          <div>
            <lucide-icon [size]="18" [name]="item.icon"></lucide-icon>
            <span>{{ item.label }}</span>
          </div>
        </a>
        <a *ngIf="item?.url" [attr.tabindex]="-1" class="p-menuitem-link" [attr.href]="item.url">
          <div>
            <lucide-icon [size]="18" [name]="item.icon"></lucide-icon>
            <span>{{ item.label }}</span>
          </div>
        </a>
      </ng-template>
    </p-menu>
```

**Comment by mjlux** [comment]
> This worked for me
> 
> ```
>     this.items = [
>       {
>         label: 'Lbl 1',
>         icon: 'custom-icon-1',
>       },
>       {
>         label: 'Lbl 2',
>         icon: 'pi pi-star-fill',
>       },
>       {
>         label: 'lbl 3',
>         icon: 'custom-icon-2',
>       },
>     ];
> ```
> 
> ```
> :host ::ng-deep {
>   .custom-icon-1{
>     width: 1rem;
>     height: 1rem;
>     background-image: url("/assets/.../icon.svg");
>     background-position: center;
>     background-repeat: no-repeat;
>     background-size: cover;
>   }
>   .custom-icon-2 {
>     width: 1rem;
>     height: 1rem;
>     background-image: url("/assets/.../icon.svg");
>     background-position: center;
>     background-repeat: no-repeat;
>     background-size: cover;
>   }
> }
> ```

You can even use a whole different icon library this way. i.e. **bootstrap icons** also adds utilty classes to reference its icons by a similiar class name structure as primeNG does. If you've added the bootstrap icons css to your project, you can substitute `pi pi-edit` with` bi bi-pencil` and it just works. This would be a more realistic approach to custom icons than having a icon file loaded every time a menu is created.
