### ISSUE TITLE
TreeTable: Updating [rows] does not update the number of rows shown

### ISSUE THREAD

**Issue by tsteuwer-accesso** [primefaces/primeng#13491]
### Describe the bug

The TreeTable component has an input called `rows` which you can use with `paginator=true` to paginate the results. When updating the `rows` input, the pagination section at the bottom of the component updates (once), but the rows do not update. Changing the `rows` input again does not update the rows or the pagination.

[Primefaces - Primeng Issue Template - StackBlitz.webm](https://github.com/primefaces/primeng/assets/32495798/c2904ef8-2020-4229-a5d9-61c31e37ea62)

Reproduction steps below

Editor URL - https://stackblitz.com/edit/github-cmgwug?file=src%2Fapp%2Fapp.component.html
Application URL - https://github-cmgwug.stackblitz.io

### Environment

Ubuntu 20.04
Chrome 115.0.5790.110 (Official Build) (64-bit)

### Reproducer

https://github-cmgwug.stackblitz.io

### Angular version

16.1

### PrimeNG version

16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Browser(s)

Chrome 115

### Steps to reproduce the behavior

1. Go to https://github-cmgwug.stackblitz.io
2. The current `rows` input on initialization is set to 5.
3. Click the "Change to 10 rows"
4. Notice the pagination at the bottom changes to reflect that there is only 1 page (since there are a total of 10 rows) but the rows themselves don't show up.

### Expected behavior

Whenever the `rows` input changes, the number of rows should be reflected in the UI.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
