### ISSUE TITLE
Templating support for accordion tab

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#135]
Add support to place custom content at header

**Comment by cagataycivici** [comment]
This is available now for 0.9.

```xml
<p-accordionTab>
    <header>
        Header Content
    </header>
    Body Content
</p-accordionTab>
```

**Comment by neonnn** [comment]
On http://www.primefaces.org/primeng/#/accordion there is a code sample showing that <p-header> should be used to create custom header. Can you please fix this.

**Comment by Programm3r** [comment]
Hi,

Not sure what the resolution was here, but the following code with regards to the header, simple does not work:

```html
<p-accordionTab>
    <ng-template pTemplate="header">Header Content</ng-template>
    <ng-template pTemplate="content">Body Content</ng-template>
</p-accordionTab>
```

**Comment by higortavares** [comment]
> Hi,
> 
> Not sure what the resolution was here, but the following code with regards to the header, simple does not work:
> 
> ```
> <p-accordionTab>
>     <ng-template pTemplate="header">Header Content</ng-template>
>     <ng-template pTemplate="content">Body Content</ng-template>
> </p-accordionTab>
> ```
> 
> This on the other hand, does the job:
> 
> ```
> <p-accordionTab>
>   <p-header>
>   </p-header>
> </p-accordionTab>
> ```

Thank you, I spend some hours searching how to solve this, but it works :)
