### ISSUE TITLE
Table:- Automatic Leftward Scrolling of Table upon Column Sorting ([customSort]="true" and [virtualScroll]="true")

### ISSUE THREAD

**Issue by megharajak-05** [primefaces/primeng#13507]
### Describe the bug

Scroll all the way to the right and sort the last column of the table. The data is getting sorted, but the table still scrolls automatically to the left (beginning) of the table. This happens when we have [customSort]="true" and [virtualScroll]="true"). As per requirement, we need virtualScroll with customSort.

![image](https://github.com/primefaces/primeng/assets/139353448/fe79b365-92d0-4e2c-9344-15d0c402c815)

### Environment

"primeng": "16.1.0"

https://stackblitz.com/edit/getneq-pmboqa?file=src%2Fapp%2Fdemo%2Ftable-rowspan-grouping-demo.html,src%2Fapp%2Fdemo%2Ftable-rowspan-grouping-demo.ts,package.json

### Angular version

16.0.0

### PrimeNG version

16.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.16.0

### Browser(s)

Chrome, WebView2

### Steps to reproduce the behavior

1. Scroll all the way to the right and sort the last column of the table. 
2. The data is getting sorted, but the table still scrolls automatically to the left (beginning) of the table. This happens when we have [customSort]="true" and [virtualScroll]="true"). As per requirement, we need virtualScroll with customSort.

### Expected behavior

The data should be sorted, and the table should remain in its current position without automatically scrolling to the left (beginning) of the table.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
