### ISSUE TITLE
Datatable row unselect broken

### ISSUE THREAD

**Issue by RomeoMikeFox** [primefaces/primeng#1350]
In latest RCs, the Datatable unselection of selected row is not working as expected, nor the ```onRowUnselect``` trigger.

Being ```selectionMode="single"```, the only way to properly unselect the row and to trigger the ```onRowUnselect``` is to press a metaKey while clicking on the selected row.

Otherwise, the only event triggered is the ```onRowSelect```.

Issue is from **line 832 of the datatable.ts** file. 
```
if(selected && metaKey) {
        if(this.isSingleSelectionMode()) {
                this.selection = null;
                this.selectionChange.emit(null);
        }
        else {
                this.selection.splice(this.findIndexInSelection(rowData), 1);
                this.selectionChange.emit(this.selection);
        }
                
        this.onRowUnselect.emit({originalEvent: event, data: rowData, type: 'row'});
}
```
The condition to enter in the unselect case should probably be more complex and should take into account the ```selectionMode``` before testing the metaKey.

**Comment by dzhavat** [comment]
This is not a bug. It is intended to be that way. It's discussed in [this thread](http://forum.primefaces.org/viewtopic.php?f=35&t=48091&p=148813#p148813).
