### ISSUE TITLE
Google sign in white background in dark theme

### ISSUE THREAD

**Issue by Hider-alt** [primefaces/primeng#13503]
### Describe the bug

When I render the google sign in button (either via Typescript or by pasting the HTML code generated from [here](https://developers.google.com/identity/gsi/web/tools/configurator)), a white background-color is set, but only if I am using a dark theme from PrimeNG.
I tried setting the background-color myself, but since the google button generates an iframe, I can't change the css.
![e055b0aa-1aea-428f-95c2-134eb3af2190](https://github.com/primefaces/primeng/assets/74743628/2a3b135c-dfc1-4824-90ef-3b4f28c15e75)
![dc7be461-c3df-4151-9c8f-6b6f48038f04](https://github.com/primefaces/primeng/assets/74743628/0965d8d3-df72-498a-a394-bef3ad7caab0)

### Environment

OS: Windows 11
Browser: Chrome (I noticed that this problem doesnt’t occur in Safari)

### Angular version

16.2.0

### PrimeNG version

16.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.17.1

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Generate code to render Google sign in button [here](https://developers.google.com/identity/gsi/web/tools/configurator) and paste it in your HTML
2. Set any dark theme of PrimeNG

### Expected behavior

![IMG_7369](https://github.com/primefaces/primeng/assets/74743628/f330e165-f442-452b-92ad-17b0e6d9a73d)

**Comment by SoyDiego** [comment]
Share a stackblitz with your problem and maybe someone can help you

**Comment by Hider-alt** [comment]
Thank you very much!
Finally after weeks I solved it by setting in the css `color-scheme: light;`

However this problem only occurred when I installed both PrimeNG and Tailwind. If I used the two libraries individually, there was no problem
