### ISSUE TITLE
Sidebar related bug

### ISSUE THREAD

**Issue by prnkrawat** [primefaces/primeng#13509]
### Describe the bug

Not able to write into text field. I have
<img width="960" alt="prime_ng_sidebar_bug" src="https://github.com/primefaces/primeng/assets/103996562/cb9d01d3-9f11-45c0-852c-5140cf84c0c1">
 created text field inside sidebar panel.

### Environment

Dev environment

### Angular version

16

### PrimeNG version

^16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.1

### Expected behavior

We should be able to type inside text field.

**Comment by SoyDiego** [comment]
Hi @prnkrawat, I have checked the problem and you are right.
I did a PR solving the problem. You can check it here: https://github.com/primefaces/primeng/pull/13510
Now we should wait PrimeNG Team approve it if they think the solution is OK for them.

Thanks!

**Comment by gucal** [comment]
Fixed https://github.com/primefaces/primeng/pull/13490. Thanks for the report.

**Comment by prnkrawat** [comment]
Thanks. I will verify it.
