### ISSUE TITLE
dropDown 

### ISSUE THREAD

**Issue by oriebalzyuot96** [primefaces/primeng#13506]
@cetincakiroglu ### Describe the feature you would like to see added

feature related to virtual scroll 

when I had drop down in my component and I send page index like 1and page size 10 then I need apply virtual scroll if user scroll to end call api again by send page index ++ 

but after I read documentation multiple time (virtual scroll just front)... get all data and cashed in front then its scroll  the proprty I used from documentation 

 [virtualScrollOptions]="ScrollerOptions"
                 [lazy]="true"
                 [virtualScroll]="true"
                 [virtualScrollItemSize]="10"

I readed cearfuly ScrollerOptions ### https://github.com/primefaces/primeng/blob/master/src/app/components/api/scrolleroptions.ts

thers method call on scroll but its work when user scroll 

I need new method called **### onScrollToEnd**

example:
 ScrollerOptions: any = {
  numToleratedItems: 10, // Adjust this based on your requirements
  onScrollToEnd: () => {
    if (!this.isFetching) {
      this.isFetching = true;
      this.pageIndex++;
      this.loadMoreData();
    }
  }
};

so plese help developer (because virtual scroll its so important to allow user to determine call api with scroll and I think its added big value to component )

when added this property I try alot in scroll function to find way to know if scroll in end or no but I cannot find way >> at the end appreceated your team effore and you for reading >> 

feel free to reply me if Had any question >>

**Comment by lixaotec** [comment]
+1
dear @oriebalzyuot96 , any workaround?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
