### ISSUE TITLE
Component: Hyperlink for A11y

### ISSUE THREAD

**Issue by megaroeny** [primefaces/primeng#13505]
### Describe the feature you would like to see added

The framework needs a dedicated Link component. Currently, I see there's a Button variant, `p-button-link` but the issue is for A11y (accessibility), there needs to be a distinction between a button and a hyperlink.

### Is your feature request related to a problem?

It is somewhat related to a problem to meet Accessibility criteria

### Describe the solution you'd like

Have a dedicated Link component versus a prop for the Button component.

### Describe alternatives you have considered

If you keep it a prop, there needs to be some attributes applied to meet the criteria for links. (See article linked below)

> To be a valid link it must have:
> 
> A href attribute: The location of the anchor, page or resource.
> Link content Text describing where the link is going, this could be plain text or the [alt attribute](https://www.a11yproject.com/posts/alt-text/) of an image.
> Opening and closing tags.

### Additional context

**Some good resources to reference:**
- [Khan Academy's Link component](https://khan.github.io/wonder-blocks/?path=/docs/link--docs) — I designed these with the design system team there. 
- [Creating valid and accessible links](https://www.a11yproject.com/posts/creating-valid-and-accessible-links/) — Talks about some of the differences between buttons and links and when to use them. In general: Links should be used for navigating, and Buttons should be used for actions.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
