### ISSUE TITLE
Component: Pick List

### ISSUE THREAD

**Issue by leoncydsilva** [primefaces/primeng#13513]
### Describe the bug

If PickList component is used in Dynamic Dialog, when dragging the items from source or target the items goes behind the dialog

https://github.com/primefaces/primeng/assets/45206626/99d2a6c2-9484-42cb-8e3b-a694469bb17c

### Environment

Happens on all env

### Reproducer

https://stackblitz.com/edit/github-n1wv7s?file=src%2Fapp%2Fapp.component.ts

### Angular version

16.2.1

### PrimeNG version

16.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.20.1

### Browser(s)

Chrome 115.0.5790.170

### Steps to reproduce the behavior

1. Insert Pick List Component in Dynamic Dialog
2. If we try to drag items from source or target, the item goes behind dialog

**Comment by leoncydsilva** [comment]
PS: I tried setting public autoZIndex: false and  baseZIndex: 100000 but now table column header is on top of dialog

static openDialog(dialogService: DialogService) {
        return dialogService.open(TableViewComponent, {
            header: 'Table View',
            width: '60%',
            closeOnEscape: true,
            maximizable: true,
            autoZIndex: false,
            baseZIndex: 100000
        });
    }

![Screenshot 2023-08-18 at 10 07 39 PM](https://github.com/primefaces/primeng/assets/45206626/52b33f35-e24f-4d65-a73a-729666713d05)

**Comment by SoyDiego** [comment]
Hi @leoncydsilva , I have checked the problem and you are right.
I did a PR solving the problem. You can check it here: https://github.com/primefaces/primeng/pull/13515
Now we should wait PrimeNG Team approve it if they think the solution is OK for them.

If you want a temporal solution until PrimeNG Team approve it,  in your `.css` you can use:

```
.cdk-drag-preview {
    z-index: 2000 !important;
}
```

Thanks

**Comment by leoncydsilva** [comment]
Hey @SoyDiego thanks a ton, will be using your workaround until the PR gets merged

**Comment by SoyDiego** [comment]
> Hey @SoyDiego thanks a ton, will be using your workaround until the PR gets merged

Happy to help, bro 🚀
