### ISSUE TITLE
TreeSelect: Option to only make leaf nodes selectable

### ISSUE THREAD

**Issue by Gykonik** [primefaces/primeng#13514]
### Describe the feature you would like to see added

I would love to see an option within `TreeSelect` that only makes the leaf nodes selectable, and expands/collapses the children when the user clicks on a non-leaf node. At least for my use cases, I don't want the non-leaf nodes to be selectable at all - they should represent the hierarchy.

### Is your feature request related to a problem?

Sort of - I would like to express file hierarchy without the directories being selectable (because I want to select files and not directories). I've faced similar issues with `Tree`, but could figure out a hacky workaround by myself.

### Describe the solution you'd like

I guess a boolean for `onlyLeafSelectable` or something similar would be sufficient. If you want to give developers more fine-grained options one could add an option similar to "disabled"  just for `selectable` or something.

### Describe alternatives you have considered

1. Manipulating the ngModel & `preventDefault` of events => did work for `Tree` but not for `TreeSelect` 
2. Using the `disabled` option - that sort of works, however, I think it would be more suitable to click on a non-leaf item that should expand/collapse the children instead of doing nothing (as would be the case for `disabled`). Doing it like this would still give me part of the expected behavior, as I can still expand it using the arrow-icon, but that's not great UX.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).

**Comment by ahbarrozo** [comment]
In case anyone is still looking for an answer, you could implement a function to filter TreeNodes that contain no children upon a node selection. For instance : 

<p-treeSelect [(ngModel)]="selectedNodes" (onNodeSelect)="selectLeavesOnly()" ... />

selectLeavesOnly() {
  this.selectedNodes = this.selectedNodes.filter((node: TreeNode) => !node.children)
}
