### ISSUE TITLE
p-steps: Vertical Display

### ISSUE THREAD

**Issue by kyjus25** [primefaces/primeng#13518]
### Describe the feature you would like to see added

Currently p-steps only supports a horizontal display of steps. My feature request is to implement a vertical option that mimics the behavior of [Angular Material](https://material.angular.io/components/stepper/overview#stepper-vertical). This would include the templating ability to have the drawn step line wrap past the active form as this is difficult to reproduce currently.

### Is your feature request related to a problem?

Given that there is no templating ability to assign content to the step item, it is difficult to reproduce the effect of the form sitting between 2 step items without some JS/CSS height trickery to fudge the effect, especially if you want it to slide open and closed like Angular Material.

### Describe the solution you'd like

A boolean to toggle between horizontal and vertical, and an `<ng-content />` area on each step to display a form inside. Again, a reproduction of [Angular Material](https://material.angular.io/components/stepper/overview#stepper-vertical)'s vertical stepper.

### Describe alternatives you have considered

Setting `.p-steps ul` to `display: block` gets you 99% of the way there, but without a template container you'd have to set the line between steps to an arbitrary height based off of the size of the form content, it's just a lot of fudging and overriding that could otherwise be handled easily with a toggle and template.

### Additional context

I understand this template area doesn't really do much in horizontal mode, but maybe it could perform a fade or slide animation between step templates as you navigate the steps instead?

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
