### ISSUE TITLE
Menubar: autoDisplay and autoHide broken

### ISSUE THREAD

**Issue by g1thuser** [primefaces/primeng#13512]
### Describe the bug

The autoDisplay and autoHide properties don't work anymore. autoHide doesn't work at all, autoDisplay works only once after clicking on any root menu item. Clicking on a menu item leaves the last clicked root menu item in the selected status.

The error is already present in primeng 16.1.0, but didn't exist in primeng 16.0.2

### Environment

Ubuntu 22.04
Firefox 116.03

### Angular version

16.2.0

### PrimeNG version

16.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.5.1

### Steps to reproduce the behavior

see [here](https://stackblitz.com/edit/hemvbj-ldr7mf?file=src%2Fapp%2Fdemo%2Fmenubar-basic-demo.html,package.json) for primeng 16.1.0

see [here](https://stackblitz.com/edit/hemvbj-ldbfpp?file=src%2Fapp%2Fdemo%2Fmenubar-basic-demo.html,package.json) for primeng 16.2.0

### Expected behavior

see [here](https://stackblitz.com/edit/hemvbj?file=src%2Fapp%2Fdemo%2Fmenubar-basic-demo.html,package.json) for primeng 16.0.2

**Comment by SoyDiego** [comment]
Hi @g1thuser, they know about the problem and will fix it.
Here you have  a reply of one of the members of PrimeNG Team:

![image](https://github.com/primefaces/primeng/assets/19764334/d800847d-6116-4cdb-8314-81b8b99b2a41)

The link is this: https://github.com/primefaces/primeng/issues/13455#issuecomment-1671416418

**Comment by AndreasHae** [comment]
Still causing issues on primeng 17.2.0.

**Steps to reproduce:**
1. Add a `p-menubar` with `[autoHide]="true" [autoHideDelay]="0"` and submenus
2. Hover over a root menu item -> submenu opens
3. Hover away from menubar -> submenu should close immediately, but stays open

**Comment by chimayko** [comment]
Still happening on 17.5

> Still causing issues on primeng 17.2.0.
> 
> **Steps to reproduce:**
> 
> 1. Add a `p-menubar` with `[autoHide]="true" [autoHideDelay]="0"` and submenus
> 2. Hover over a root menu item -> submenu opens (works as intended because `autoDisplay` default is true)
> 3. Hover away from menubar -> submenu should close immediately, but stays open

Still happening on 17.5, following the same steps described above.

Workaround:

Define a viewChild for the menu bar and add a mouseleave callback to it and force close, using renderer2:

```
this.renderer.listen(
     this.menubar.el.nativeElement,
     'mouseleave',
     (event) => {
       this.menubar.hide();
     },
   );
```

**Comment by kubedan** [comment]
Autodisplay works if change source code.
```diff --git a/src/app/components/tieredmenu/tieredmenu.ts
--- a/src/app/components/tieredmenu/tieredmenu.ts
+++ b/src/app/components/tieredmenu/tieredmenu.ts
@@ -695,6 +695,9 @@
 
  onItemMouseEnter(event: any) {
     if (!DomHandler.isTouchDevice()) {
+      if (this.autoDisplay) {
+        this.dirty = true; 
+        }
       if (this.dirty) {
         this.onItemChange(event);
       }

```

**Comment by JeffersonFarFan** [comment]
Are there any updates or workarounds ? 

Still happening on 17.14.1

**Comment by kubedan** [comment]
> Are there any updates or workarounds for autoDisplay? Neither default = true nor setting it to true works for me.
> 
> Still happening on 17.14.1
> 
> Found out that its not working only for chrome

You can do with the tieredmenu component what I did with the fileupload component (https://github.com/primefaces/primeng/issues/15212#issuecomment-2071719150) and fix it as I mentioned here: https://github.com/primefaces/primeng/issues/13512#issuecomment-2044409597.

**Comment by JeffersonFarFan** [comment]
@kubedan Thanks for answer. So theres no solution without updating the primeng code ?

**Comment by bjsawyer** [comment]
I've opened a PR based on @kubedan 's suggestion here https://github.com/primefaces/primeng/pull/16077

**Comment by mgafsia** [comment]
Unfortunately, I still have the same issue for autoDisplay and autohide still not work with v17.18.9. I'm using Chrome.
