### ISSUE TITLE
p-steps Docs: Routing Example Broken

### ISSUE THREAD

**Issue by kyjus25** [primefaces/primeng#13519]
### Describe the bug

https://primeng.org/steps/seat#routing is missing the Next / Back buttons and should either be removed or fixed. Manually clicking the "Seats" step takes you to `/seats`, but going back to `/personal` either by clicking the step or by navigating in the URL does not work and returns a site-wide 404, which may be why the buttons were removed.

UPDATE: I also noted that the Algolia search defaults directly to `https://primeng.org/steps/seat`, this should be https://primeng.org/steps/personal

<img width="783" alt="Screenshot 2023-08-20 at 2 12 17 PM" src="https://github.com/primefaces/primeng/assets/6710794/31745ce3-40c3-467a-828f-bbf6a6a32372">

### Environment

Chrome

### Reproducer

https://primeng.org/steps/seat#routing

### Angular version

16.0.0

### PrimeNG version

16.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Steps to reproduce the behavior

- Visit https://primeng.org/steps#routing
  - No buttons to navigate "Next"
- Manually click "Seat" step
  -  Route changes correctly but places you back at the top of the page
- Manually click "Personal" step
  -  Nothing happens
- Manually navigate from https://primeng.org/steps/seat to https://primeng.org/steps/personal
  -  Receive a 404

### Expected behavior

Demo works as on https://www.primefaces.org/primeng-v14-lts/steps/personal

**Comment by SoyDiego** [comment]
I'm on it. 
This afternoon I will do the PR :)

**Comment by SoyDiego** [comment]
The PR is here #13527.

Thanks for you help @kyjus25
