### ISSUE TITLE
p-table: Virtual Scroll, Lazy Load table with value from Observable W Async Pipe/toSignal stuck in loading state when sorting

### ISSUE THREAD

**Issue by SaajRP** [primefaces/primeng#13517]
### Describe the bug

Virtual scroll, lazy load table that has its value set from either an Observable with an Async pipe or a Signal created using the toSignal function on an observable gets stuck in a loading state after sorting when scrolled to the top of table. The user has to scroll down for the table to be no longer stuck in a loading state

This issue does not happen for the same table after sorting when not scrolled at the top of the table.

- Calling the LazyLoadEvent.forceUpdate() function does not make a difference
- Using either the Default or OnPush ChangeDetectionStrategy, does not make a difference
- Settings the rows input appears to fix the issue, but causes another bug, where if the user scrolls from the top of the table, to the bottom, then scrolls to the middle of the table, the data in the middle will remain stuck in a loading state indefinitely  (https://github.com/primefaces/primeng/issues/13370)

### Environment

macOS Ventura 13.5
- latest version of Safari
- latest version of Chrome
- latest version of Firefox

Windows 10 Version 22H2
- latest version of Edge (Chromium)
- latest version of Chrome
- latest version of Firefox

### Reproducer

https://stackblitz.com/edit/oetsny-rdsoxe?file=src%2Fapp%2Fdemo%2Ftable-virtual-scroll-lazy-demo.ts

### Angular version

16.2.0

### PrimeNG version

16.9.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.0

### Steps to reproduce the behavior

- Go to virtual scroll, lazy load table which has its value set from either an observable with async pipe or a signal created using the toSignal function on an observable 
- Remain scrolled at the top of table
- Click on sort button
- Table will remain in a loading state, until the user scrolls down

### Expected behavior

- Go to virtual scroll, lazy load table which has its value set from either an Observable with Async pipe or a Signal created using the toSignal function on an observable 
- Remain scrolled at the top of table
- Click on sort button
- Data not be stuck in a loading state, and newly sorted data should be visible on the table

**Comment by SaajRP** [comment]
This remains a problems as of PrimeNg 16.9.0

**Comment by SaajRP** [comment]
Remains a problem as of PrimeNg 17.0.0

**Comment by SaajRP** [comment]
Table sorting when scrolled at the top of a table appears to be functioning correctly as of PrimeNg 17.2.0

**Comment by esaAtbeconfig** [comment]
In version 17.2 with a virtual scroller and 6k lines data, if you scroll to the bottom of the list than sort, the UI get stucks for a while than is available. The sort method doesn't seem to be involved in this. The problem seems to be related to the scrolling position, at 0%, no slowdown, at 10% a little, at 100% it hangs. I did not find any looping code for the moment but there must be somewhere and the source being not observable or signal seems to do the same thing.

**Comment by SaajRP** [comment]
@esaAtbeconfig, the issue you’ve described has been raised on

https://github.com/primefaces/primeng/issues/13494

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
