### ISSUE TITLE
Component: Sidebar component along with inputs not working properly

### ISSUE THREAD

**Issue by ghost** [primefaces/primeng#13526]
### Describe the bug

When opening the sidebar I have entered data in any data entry, the following error appears: 
![error](https://github.com/primefaces/primeng/assets/68087817/88249df2-508b-454f-88dd-5b1bbc4171a2)

Simple code, following the documentation.
<p-button type="button" class="mr-2" (click)="sidebarVisible2 = true" icon="pi pi-arrow-left"></p-button>
<p-sidebar [visible]="sidebarVisible2" position="right" [modal]="false" [dismissible]="false" [closeOnEscape]="true">
    <div class="grid formgrid p-fluid">
        <div class="field col-12">
            <input type="text" pInputText />
        </div>
        <div class="field col-12">
            <input type="text" pInputText />
        </div>
    </div>
</p-sidebar> 

### Environment

Local Development Environment

### Angular version

16.2.0

### PrimeNG version

16.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Click the button with the left arrow icon (pi pi-arrow-left) to open the p-sidebar.
2. Enter data in the input fields
3. Observe the error in the browser console.

### Expected behavior

Allow the use of forms in a sidebar

**Comment by SoyDiego** [comment]
This problem was fixed and will be solved in next release.
You can check here: https://github.com/primefaces/primeng/pull/13490

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
