### ISSUE TITLE
SplitButton [NG]: Menu is not closing when click on outside

### ISSUE THREAD

**Issue by siva7170** [primefaces/primeng#13522]
### Describe the bug

Hi Team, 

I m facing the issue with SplitButton. The SplitButton's menu is not closed when click on outside.

This issue is also available in SplitButton documentation

### Environment

OS: Windows 11
Browser: Firefox 116.0.2

### Angular version

16.2.0

### PrimeNG version

16.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.15.0

### Steps to reproduce the behavior

1. Click on dropdown button
2. Hover on other menu item in opened menu
3. Click on outside.

### Expected behavior

When we click on outside, the opened menu should close.

**Comment by SoyDiego** [comment]
Hi @siva7170, I did a PR solving the problem.
You can check here: https://github.com/primefaces/primeng/pull/13539.
Now we should wait if PrimeNG Team approve it.

Thanks!

**Comment by siva7170** [comment]
@SoyDiego  Thank you for your effort. SplitButton is now fine. I will expect this next release.

**Comment by SoyDiego** [comment]
It's not necessary closed the issue. Will be closed when my PR it's approved (If they approve it).
I linked your issue to the PR. If is continue open, maybe someone can see another solution better.
But it's the same, you decide. Thanks again :)

**Comment by gucal** [comment]
Issue reopened for review.
