### ISSUE TITLE
PrimeNG 15.4.7-lts licence 

### ISSUE THREAD

**Issue by sagarbichewar** [primefaces/primeng#13528]
### Describe the bug

I integrate lts license code as per documentation and working fine in development mode but on production it showing warning msg on top "You are using lts version of primeng with invalid license, you may either switch back to a non LTS-version or purchase a license at PrimeStore "

Angular version : 15.2.0
PrimeNG version : 15.4.7-lts
![localhost](https://github.com/primefaces/primeng/assets/119410276/b76afb8a-b641-4ecf-add8-92a5c7ef21d2)
![main](https://github.com/primefaces/primeng/assets/119410276/375e4ecb-5f62-4820-8dbb-5c1d9e6e3ac7)
![production](https://github.com/primefaces/primeng/assets/119410276/ba251ea3-a9d6-4a33-a29d-a79f95969f08)

### Environment

Angular version : 15.2.0
PrimeNG version : 15.4.7-lts

### Angular version

15.2.0

### PrimeNG version

15.4.7-lts

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.17.0

### Browser(s)

chrome,firefox,edge

### Steps to reproduce the behavior

add licence key in main.ts or app.component.ts constructor as per documentation after that on development mode it working fine(not showing warning message) ,after that make build using ng build command and run it on server it start showing license warning message.
![localhost](https://github.com/primefaces/primeng/assets/119410276/46d82d8b-8cf1-45bf-b380-611090b7de6b)
![main](https://github.com/primefaces/primeng/assets/119410276/2f1307a1-7bc9-4893-aeca-62fc3059a5ce)
![production](https://github.com/primefaces/primeng/assets/119410276/5a1d88da-87af-4065-b0bd-5a118a8b1594)

### Expected behavior

remove warning message on production

**Comment by gucal** [comment]
Hi,

 You can contact us e-mail at contact@primetek.com.tr for LTS

**Comment by sagarbichewar** [comment]
I mail on above mail id but nobody is responding from last 4 days. My mail id is ssagarb@logicmo.com. Can you please check it from your end ?
