### ISSUE TITLE
Sidebar: Badge property not working

### ISSUE THREAD

**Issue by gabboman** [primefaces/primeng#13523]
### Describe the bug

The badge property on the sidebar menu gets rendered as regular text without anything else
<img width="274" alt="imagen" src="https://github.com/primefaces/primeng/assets/3456181/fc57b44f-bae0-4995-9732-3ef5da6e5f49">
<img width="554" alt="imagen" src="https://github.com/primefaces/primeng/assets/3456181/8c6a4334-3ce8-46cb-b136-8d867089afc5">
This bug did not happend before the update to 16.2.0. it was ok in 16.0.0

### Environment

primeng with primeflex. This bug started happening after the update to 16.2.0

### Angular version

16.2.0

### PrimeNG version

16.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.0

### Steps to reproduce the behavior

the badge should be displayed as a small number in a colorful circle

**Comment by SoyDiego** [comment]
> @SoyDiego I am afraid that the stackblitz fails when using this. https://stackblitz.com/edit/github-yrp44t?file=src%2Fapp%2Fcomponents%2Fnavigation-menu%2Fnavigation-menu.module.ts,src%2Fapp%2Fcomponents%2Fnavigation-menu%2Fnavigation-menu.component.html,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fcomponents%2Fnavigation-menu%2Fnavigation-menu.component.scss
> 
> Here is my update: Its not the sidebar component, is the panelMenu component. I also can confirm that the issue happens in 16.1.0 but not in 16.0.2

Yes, it's failing :(
![image](https://github.com/primefaces/primeng/assets/19764334/93a872a6-1fd3-4e72-8ab8-b0cfe257cc21)

**Comment by gabboman** [comment]
> > @SoyDiego I am afraid that the stackblitz fails when using this. https://stackblitz.com/edit/github-yrp44t?file=src%2Fapp%2Fcomponents%2Fnavigation-menu%2Fnavigation-menu.module.ts,src%2Fapp%2Fcomponents%2Fnavigation-menu%2Fnavigation-menu.component.html,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fcomponents%2Fnavigation-menu%2Fnavigation-menu.component.scss
> > Here is my update: Its not the sidebar component, is the panelMenu component. I also can confirm that the issue happens in 16.1.0 but not in 16.0.2
> 
> Yes, it's failing :( ![image](https://user-images.githubusercontent.com/19764334/262361890-93a872a6-1fd3-4e72-8ab8-b0cfe257cc21.png)

yep, well seems like next release will fix it. Will stay tuned for the 16.2.1 or whatever is the next one  :D

**Comment by SoyDiego** [comment]
> yep, well seems like next release will fix it. Will stay tuned for the 16.2.1 or whatever is the next one :D

If no one see your problem or be clear here, will not be in the next release :/

**Comment by mehrabisajad** [comment]
> @SoyDiego I am afraid that the stackblitz fails when using this. https://stackblitz.com/edit/github-yrp44t?file=src%2Fapp%2Fcomponents%2Fnavigation-menu%2Fnavigation-menu.module.ts,src%2Fapp%2Fcomponents%2Fnavigation-menu%2Fnavigation-menu.component.html,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fcomponents%2Fnavigation-menu%2Fnavigation-menu.component.scss
> 
> Here is my update: Its not the sidebar component, is the panelMenu component. I also can confirm that the issue happens in 16.1.0 but not in 16.0.2

Update the dependencies to fix the panelMenu component error.
"@angular-devkit/build-angular": "16.2.0",
"@angular/cli": "16.2.0",
"@angular/compiler-cli": "16.2.1",
"@types/node": "20.5.2",
"typescript": "5.1.6"
