### ISSUE TITLE
Remove problematic change detection for charts

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#1352]
Charts having multiple datasets break change detection and we could not find a decent way to do change detection for charts right now. Instead add reload() method to let the user do it manually.

**Comment by chpasha** [comment]
I'm sorry, I must be missing something. The chart where working just fine, at least I could change the data reference and the chart was updating. It didn't work for multiple datasets? Ok, maybe, but it did for more common scenarios and with complex ones we could still call some update/refresh whatever. Now if you update the data in runtime (and it must be 99% of all cases, who shows static data anyway?) the charts show literally nothing so I have to inject chart component in every page and call this refresh stuff every time the data changes. I think it is a huge step backward in usability
