### ISSUE TITLE
Table resize with direction rtl

### ISSUE THREAD

**Issue by vadimt2** [primefaces/primeng#13537]
### Describe the bug

Go here
https://www.primefaces.org/primeng-v14-lts/table/colresize
make the html direction rtl
try to resize the column
The resize is not working properly and you can't resize the last column

### Environment

all the environments

### Angular version

14.2.11

### PrimeNG version

14.2.11

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.10.x

### Browser(s)

chrome

### Steps to reproduce the behavior

1. Go to https://www.primefaces.org/primeng-v14-lts/table/colresize
2. Change the html direction to rtl
3. Try to resize the table

### Expected behavior

The resize will work properly and the last column resize will work

**Comment by zahraNoormohammadi** [comment]
hi
I solved this problem
Please replace these pieces of code with the source code

Angular version: 18.0.X+

PrimeNG version: 17.18.5

`onColumnResize(event: any) {
    let containerLeft = DomHandler.getOffset(this.containerViewChild?.nativeElement).left;
    DomHandler.addClass(this.containerViewChild?.nativeElement, 'p-unselectable-text');
    (<ElementRef>this.resizeHelperViewChild).nativeElement.style.height = this.containerViewChild?.nativeElement.offsetHeight + 'px';
    (<ElementRef>this.resizeHelperViewChild).nativeElement.style.top = 0 + 'px';
    if (event.type == 'touchmove') {
        (<ElementRef>this.resizeHelperViewChild).nativeElement.style.left = event.changedTouches[0].clientX + containerLeft + this.containerViewChild?.nativeElement.scrollLeft + 'px';
    } else {
        (<ElementRef>this.resizeHelperViewChild).nativeElement.style.left = event.pageX + containerLeft + this.containerViewChild?.nativeElement.scrollLeft + 'px';
    }
    (<ElementRef>this.resizeHelperViewChild).nativeElement.style.display = 'block';
}

onColumnResizeEnd() {
    let delta = this.resizeHelperViewChild?.nativeElement.offsetLeft - <number>this.lastResizerHelperX;
    let columnWidth = this.resizeColumnElement.offsetWidth;
    let newColumnWidth = columnWidth - delta;
    let minWidth = this.resizeColumnElement.style.minWidth.replace(/[^\d.]/g, '') || 15;

    if (newColumnWidth >= minWidth) {
        if (this.columnResizeMode === 'fit') {
            let nextColumn = this.resizeColumnElement.nextElementSibling;
            let nextColumnWidth = nextColumn.offsetWidth + delta;

            if (newColumnWidth > 15 && nextColumnWidth > 15) {
                this.resizeTableCells(newColumnWidth, nextColumnWidth);
            }
        } else if (this.columnResizeMode === 'expand') {
            this._initialColWidths = this._totalTableWidth();
            let tableWidth = this.tableViewChild?.nativeElement.offsetWidth - delta;

            this.setResizeTableWidth(tableWidth + 'px');
            this.resizeTableCells(newColumnWidth, null);
        }

        this.onColResize.emit({
            element: this.resizeColumnElement,
            delta: delta
        });

        if (this.isStateful()) {
            this.saveState();
        }
    }

    (<ElementRef>this.resizeHelperViewChild).nativeElement.style.display = 'none';
    DomHandler.removeClass(this.containerViewChild?.nativeElement, 'p-unselectable-text');
}`

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
