### ISSUE TITLE
[AutoComplete] p-autocomplete-token-icon alignment issue

### ISSUE THREAD

**Issue by atakantepe** [primefaces/primeng#13532]
![image](https://github.com/primefaces/primeng/assets/28745098/3707548d-8530-4acd-b871-209a8e99752e)

**Comment by SoyDiego** [comment]
Hi @atakantepe, I have created a PR in `primeng-sass-theme` project to solve this problem.

You can check here: https://github.com/primefaces/primeng-sass-theme/pull/39

![autocomplete fixed](https://github.com/primefaces/primeng/assets/19764334/befa527a-4699-42d2-91bf-0da0640cd26c)

**Comment by SoyDiego** [comment]
Now this is the correct PR, @mertsincan explained me about the projects and I did it again here in Core:
https://github.com/primefaces/primeng/pull/13634

If something is wrong, let me know and thanks again :)
