### ISSUE TITLE
PrimeNg Sidebar: Error with Input Field in PrimeNG Sidebar

### ISSUE THREAD

**Issue by srik790** [primefaces/primeng#13534]
### Describe the bug

When attempting to use an input field within the PrimeNG sidebar component, I encountered an error that manifests on typing or pressing keys within the input field.

### Environment

PrimeNG Version: ^16.2.0

### Reproducer

https://stackblitz.com/edit/a9owcl?file=package.json

### Angular version

16.1.0

### PrimeNG version

^16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.10.0

### Steps to reproduce the behavior

Create a PrimeNG sidebar.
Add an input field within the sidebar.
Start typing or perform key presses in the input field.

### Expected behavior

The input field should function smoothly without any errors, and the typed characters should appear as expected.

Actual Behavior:
An error is triggered while typing, causing unexpected behavior within the input field.

Additional Information:

PrimeNG Package Version (Before Issue Resolved): ^16.2.0
Solution: The issue was resolved by changing the PrimeNG package version to 16.2.0 (exact version).

**Comment by SoyDiego** [comment]
Hi, thanks for your report.
This bug will be fix in the next release. 
Was solved here: https://github.com/primefaces/primeng/pull/13490.
