### ISSUE TITLE
TabView: Scroll buttons are not displayed when adding tabPanel dynamically

### ISSUE THREAD

**Issue by RomDuvi** [primefaces/primeng#13530]
### Describe the bug

When adding tabPanels to a tabView, the scroll button is not displayed in the nav container of the tabView in case of overflow.
This behavior worked in PrimeNg 16.0.0.

If the tabView is instantiated with a number of tabPanels exceeding the tabView's nav container width, scroll buttons are correctly displayed.

### Environment

**Primeng** 16.2.0
**Angular** 16.2.1
**Node** 18.12.1
**Chrome** 116

### Reproducer

https://stackblitz.com/edit/github-fdxap3?file=src%2Fapp%2Fapp.component.ts

### Angular version

16.2.1

### PrimeNG version

16.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.1

### Browser(s)

Chrome 116

### Steps to reproduce the behavior

Create a tabView and add tabPanels until the width of the tabPanel list exceeds the tabView container.
The scroll buttons are not displayed.

### Expected behavior

Scroll buttons are displayed as soon as a new tabPanel is added to the tabView and the tabPanels exceed the width of the tabView container.

**Comment by SoyDiego** [comment]
Hi, @RomDuvi. please edit the title of your issue for example: `TabView: Scroll buttons are not displayed`.

I have checked the stackblitz and I can see displayed the scroll buttons (arrows).
And the buttons disappear when you are at the beginning or end of the TabView.

Maybe  I don't understood something. If you can give more info or record a gif or something will be better.

Thanks

**Comment by RomDuvi** [comment]
@SoyDiego , thanks for your answer :)
Sorry for the title, it has been updated.

In the stackblitz example, when I click the "Add button" multiple times it pushes new tabPanel to the tabView but the scroll button is never displayed.
![image](https://github.com/primefaces/primeng/assets/22677511/b8292ad7-debc-4d84-b470-a22eb4b94e7b)


Thanks for your help,

**Comment by lukasloetkolben** [comment]
![tabs](https://github.com/primefaces/primeng/assets/61192133/eec864a8-3438-4bb1-b7e7-e911e5ce888f)

I've encountered the same issue.
The scroll arrow isn't displaying when adding a new tab.

**Comment by miki995** [comment]
@mehmetcetin01140 Hi, can you have a look at this issue? Thanks
