### ISSUE TITLE
Component: Input inside a Sidebar

### ISSUE THREAD

**Issue by IamKayrox** [primefaces/primeng#13536]
### Describe the bug

Whenever you use an input element inside a sidebar and you try to input anything, it gives the following error:
`ERROR TypeError: ctx_r16.onKeyDown is not a function`

### Environment

A clean Angular 16.2.1 environment

### Reproducer

https://stackblitz.com/edit/github-ykrpuq

### Angular version

16.2.1

### PrimeNG version

16.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.17.1

### Steps to reproduce the behavior

1. Click the "Open Sidebar" button
2. Attempt to input anything in the input inside the sidebar
3. See error on console, also, nothing gets written inside the input

### Expected behavior

The input element is expected to work normally

**Comment by SoyDiego** [comment]
Hi, thanks for your report.
This bug will be fix in the next release. Was solved here: https://github.com/primefaces/primeng/pull/13490.

**Comment by webmatth** [comment]
Quick fix while we wait 😅

```
Object.assign(Sidebar.prototype, {
      onKeyDown(event: KeyboardEvent) {
        if (event.code === 'Escape') {
          this.hide();
        }
      }
    });
```

**Comment by SoyDiego** [comment]
> Quick fix while we wait 😅
> 
> ```
> Object.assign(Sidebar.prototype, {
>       onKeyDown(event: KeyboardEvent) {
>         if (event.code === 'Escape') {
>           this.hide();
>         }
>       }
>     });
> ```

Thanks for this tip @webmatth

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
