### ISSUE TITLE
Component: For table if select filter from Balance column filter and without Applying from column level its automatically showing applied and highlighted that particular filter icons

### ISSUE THREAD

**Issue by Jeevandhobale** [primefaces/primeng#13531]
### Describe the bug

https://www.primefaces.org/primeng-v14-lts/table
1.  in this link I click on Balance column filter and select dropdown but not click on apply button, click outside to the popup so this filter icon is  highlighted to blue. if we not click on apply button then do not want to highlight.
2.  also if we not click on apply button filter icon color change to blue but if we click on status column filter icon and select one of the value and click on apply button so both the filters are applied, we don't want this.  If balance column filter we not applied then only status column filter is applied. 

### Environment

we use this table in our project that uses frontend as a angular.

### Angular version

14.3.0

### PrimeNG version

14.2.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.18.1

### Browser(s)

Chrome, Firefox, iOS

### Steps to reproduce the behavior

1. go to link https://www.primefaces.org/primeng-v14-lts/table.
2. table> balance column >status column.

### Expected behavior

1. Without Applying any filter from column level, it should not be automatically showing applied and should not highlight that particular filter icons.
2. If 1st column filter is not applied and click outside to the popup and  select second column filter and then apply , so don't want to apply that both filter,  we want to apply only applied filter.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
