### ISSUE TITLE
Autocomplete Virtual Scroll issue

### ISSUE THREAD

**Issue by elaiyaraja-marimuthu** [primefaces/primeng#13541]
### Describe the bug

![image](https://github.com/primefaces/primeng/assets/81211142/15df08d6-9647-4dfc-a71d-e0559175895d)

While using auto complete with virtual scroll its coming blank while selecting items from bottom and also search incorrect fields after than lot of items are missing in dropdown

### Environment

prod

### Angular version

16

### PrimeNG version

16

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Browser(s)

all

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
