### ISSUE TITLE
Autocomplete: not working if nested in a sidebar : concole error: onKeyDown is not a function

### ISSUE THREAD

**Issue by kaising** [primefaces/primeng#13545]
### Describe the bug

Just copied the code from your documentation (first example). the autocomplete component is working fine. But NOT inside a sidebar.
I attach the code and it contains 2 copy of the autocomplete component.
one inside a sidebar, a second outside. the instance inside the sidebar is not working. 

### Environment

i attach the code

[umb-ui.zip](https://github.com/primefaces/primeng/files/12436917/umb-ui.zip)
![2023-08-25_09-45-21](https://github.com/primefaces/primeng/assets/2168009/39b8b276-fc8f-4aff-9e66-eb7a3987a3ad)

### Angular version

16.2.0

### PrimeNG version

16.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Browser(s)

chrome , firfox, edge,...

**Comment by SoyDiego** [comment]
Hi, thanks for your report.
This bug will be fix in the next release. Was solved here: https://github.com/primefaces/primeng/pull/13490.

**Comment by kaising** [comment]
Hi Diego,
And do you know when the next release will be deployed/available?
regards,
g


Le ven. 25 août 2023 à 13:58, Diego Franchina ***@***.***> a
écrit :

**Comment by SoyDiego** [comment]
> 

Sorry I don't know but I hope soon. 
I'm only a contributor, I'm not part of PrimeNG Team.

Thanks!

**Comment by szawadski** [comment]
Thanks @SoyDiego !

**Comment by ashikjs** [comment]
@cetincakiroglu  can you close this Issue ticket, it's already fixed by #13490

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
