### ISSUE TITLE
Component: Overlay

### ISSUE THREAD

**Issue by abdullah2993** [primefaces/primeng#13542]
### Describe the feature you would like to see added

in modal mode the overlay is not aligned to the target element, it would be nice to see the ability for modal overlay to be aligned to the target element just like it does in overlay mode.

### Is your feature request related to a problem?

No

### Describe the solution you'd like

it would be nice to see the ability for modal overlay to be aligned to the target element just like it does in overlay mode.

### Describe alternatives you have considered

manually implement the logic

**Comment by dylansyoung** [comment]
Does the appendTo property not accomplish what you're trying to do?

**Comment by abdullah2993** [comment]
> Does the "appendTo" property not accomplish what you're trying to do?

modal mode is different from overlay mode

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
