### ISSUE TITLE
Clicking on p-tableHeaderCheckbox on any page other than 1 is moving the pagination to page 1

### ISSUE THREAD

**Issue by sahil1989** [primefaces/primeng#13540]
### Describe the bug

Clicking on p-tableHeaderCheckbox on any page other than 1 is moving the pagination to page 1, this is happening for both lazily loaded or non lazily loaded table

### Environment

Production

### Angular version

14.2

### PrimeNG version

14.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14

### Browser(s)

chrome

[screen-capture (2).webm](https://github.com/primefaces/primeng/assets/2972955/fb1584bb-4fc2-408f-a593-8456c48735b3)

**Comment by dylansyoung** [comment]
@sahil1989 have you tried setting "resetPageOnSort" property on table to false?

**Comment by sahil1989** [comment]
@dylansyoung thanks it's working as expected now, not sure why this flag would work for header selection.

**Comment by sahil1989** [comment]
Closing the ticket

**Comment by dylansyoung** [comment]
@sahil1989 maybe possible that you have this templates as a sortable column? That could be one reason why that I can think of. Anyways, glad this solution worked for you.
