### ISSUE TITLE
Dynamic Dialog: Supports slide animation from right to left or in the opposite direction.

### ISSUE THREAD

**Issue by Chienpv00** [primefaces/primeng#13554]
### Describe the feature you would like to see added

I would like to propose a new feature for our application that involves enhancing the visual dynamics of our user interface. Currently, I have configured an element with a specific "position" attribute set to 'right'. However, to create a more engaging and fluid user experience, I envision an animation where this element smoothly transitions from the right side of the screen to the left

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
