### ISSUE TITLE
File uploader: error in the documentation for maxFileSize="1000000"

### ISSUE THREAD

**Issue by nordon2022** [primefaces/primeng#13557]
### Describe the bug

The maxsize attribute accepts a digit or undefined, but specified as a string

### Environment

Nx, Angular, primeng

### Angular version

16.1.0

### PrimeNG version

16.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.18.0

**Comment by dylansyoung** [comment]
![image](https://github.com/primefaces/primeng/assets/104391407/e8034300-b27b-4485-9b3d-87d21a34317d)
The documentation specifies as a nullable number. If you're talking about the examples...the string to number conversion happens as part of javascript conversion so there is no need for [maxFileSize]="1000000". Am I understanding your issue correctly?

**Comment by nordon2022** [comment]
close
