### ISSUE TITLE
ProgressSpinner - Documentation and Template Class Discrepancy

### ISSUE THREAD

**Issue by Aniruddha-Shriwant** [primefaces/primeng#13552]
### Describe the bug

The classes mentioned in the documentation for the ProgressSpinner component are not aligned with the classes used in the actual Angular component's template. This inconsistency can lead to confusion and potential issues for developers who rely on the documentation for theming or other customizations.

### Environment

I encountered this issue while working in a development environment using Angular, specifically with PrimeNG's ProgressSpinner component.

### Angular version

16.1.4

### PrimeNG version

16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Steps to reproduce the behavior

1. Navigate to the documentation for the ProgressSpinner component.
2. Observe the classes mentioned for various elements:
   - Expected for SVG element: `p-progress-circle`
   - Expected for Circle element: `p-progress-path`
3. Now, inspect the actual Angular component's template.
4. Observe the classes used in the template:
   - Actual for SVG element: `p-progress-spinner-svg`
   - Actual for Circle element: `p-progress-spinner-circle`
5. Notice the discrepancy between the expected classes from the documentation and the actual classes in the component template.

Template:
https://github.com/primefaces/primeng/blob/24993b4e321f2180f89cb3eea3c4910fc0bf018d/src/app/components/progressspinner/progressspinner.ts#L9-L15

Documentation:
https://github.com/primefaces/primeng/blob/24993b4e321f2180f89cb3eea3c4910fc0bf018d/src/app/showcase/doc/progressspinner/styledoc.ts#L22-L29

### Expected behavior

The classes mentioned in the documentation should align with the classes used in the Angular component's template to avoid any confusion or potential issues.

**Comment by SoyDiego** [comment]
Hi @Aniruddha-Shriwant, thanks for report the issue.
Pull requests are welcome :)

**Comment by Aniruddha-Shriwant** [comment]
Thanks @SoyDiego will raise it 😛
