### ISSUE TITLE
Component: Menu component throws a JS exception

### ISSUE THREAD

**Issue by jacobvernau-soda** [primefaces/primeng#13568]
### Describe the bug

When all menu items in a `p-menu` are disabled, the following TypeError appears when any part of the document is clicked. 
```
error_handler.ts:45 ERROR TypeError: Cannot read properties of undefined (reading 'getAttribute')
    at Menu.changeFocusedOptionIndex (menu.ts:611:64)
    at Menu.onListBlur (menu.ts:503:14)
    at menu.ts:661:26
    at HTMLDocument.<anonymous> (dom_renderer.ts:317:11)
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at async-stack-tagging.ts:44:49
    at AsyncStackTaggingZoneSpec.onInvokeTask (async-stack-tagging.ts:44:30)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Object.onInvokeTask (ng_zone.ts:424:29)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
```

### Environment

Mac

### Reproducer

https://stackblitz.com/edit/b8r8nz?file=src%2Fapp%2Fdemo%2Fmenu-basic-demo.ts

### Angular version

16.2.1

### PrimeNG version

16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.1.3

### Steps to reproduce the behavior

1. Disable all menu items in a p-menu element
2. Open dev console
3. Click anywhere on document
4. See TypeError

### Expected behavior

All menu items should be able to be disabled without issue

**Comment by dalenguyen** [comment]
I think it happens when this function is triggered `changeFocusedOptionIndex`.

```
const links = DomHandler.find(this.containerViewChild.nativeElement, 'li[data-pc-section="menuitem"][data-p-disabled="false"]');

// when all menu is disabled. The list is an empty array, and the order has the value of 0.

order > -1 && this.focusedOptionIndex.set(links[order].getAttribute('id'));
```

It finds the list of menu items and changes the focus. However, the menu list is 0 since all of them are disabled. 

I can help to create a PR for this.

**Comment by jacver** [comment]
Yeah, it looks to be a simple enough fix.
