### ISSUE TITLE
Sidenav: Input Key Down triggers "TypeError: ctx_r16.onKeyDown is not a function"

### ISSUE THREAD

**Issue by luis-incomm** [primefaces/primeng#13569]
### Describe the bug

Any input element inside a p-sidenav component is triggering "TypeError: ctx_r16.onKeyDown is not a function"  when a key is pressed. This is happening on any 16 version.  

### Environment

@angular-devkit/architect       0.1602.0
@angular-devkit/build-angular   16.2.0
@angular-devkit/core            16.2.0
@angular-devkit/schematics      16.2.0
@angular/cli                    16.2.0
@schematics/angular             16.2.0
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.1
npm                            8.3.1
node                         v16.14.0

### Reproducer

https://stackblitz.com/edit/j5tjkf?file=src%2Fapp%2Fdemo%2Fsidebar-size-demo.html

### Angular version

16.2.0

### PrimeNG version

16.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

 16.14.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Add any input element inside a p-sidebar component 
2. Try to type focusing on the element 
3. Open the console
4. "TypeError: ctx_r16.onKeyDown is not a function" error is trigger

**Comment by gucal** [comment]
Hi,

The related issue has been corrected with this pr [https://github.com/primefaces/primeng/pull/13490/files]. With version 16.2.1 the bug will be fixed.

Thank you for your report.

**Comment by luis-incomm** [comment]
Thanks a lot, @gucal much appreciated it.

**Comment by uaiangemar** [comment]
Buen día con todos, consulta, tengo el mismo error, pero no se como aplicar la solución mencionada, agradeceré si me pudieran orientar como solucionar.

Gracias.
