### ISSUE TITLE
Add innerHtml to growl detail

### ISSUE THREAD

**Issue by Skuriles** [primefaces/primeng#1356]
Just as a proposal:

Would it be possible to change the growl template from

`<p>{{msg.detail}}</p>`
to

`<p [innerHtml]=\"msg.detail\"></p>`

This would allow to format growls (in my case to show a short list of changes).
For all other users it wouldn't change anything..

**Comment by cagataycivici** [comment]
Isn't it a bit dangerous?

**Comment by Skuriles** [comment]
As far as I understand:
https://angular.io/docs/ts/latest/guide/security.html

> For the HTML to be interpreted, you must bind it to an HTML property such as innerHTML. But binding a value that an attacker might control into innerHTML normally causes an XSS vulnerability. For example, code contained in a <script> tag is executed:

->so innerHtml is sanitized automatically- But I'm no expert in security issues. If there are any concerns about it, leave it as it is

**Comment by upmauro** [comment]
Maybe it's a good idea create a pipe to use in project.

```
import { Pipe, PipeTransform } from '@angular/core';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';

@Pipe({
  name: 'safeHtml',
  pure: true
})
export class SafeHtmlPipe implements PipeTransform {

  constructor(private _sanitizer: DomSanitizer) { }

  transform(html: String): SafeHtml {
    if (state) {
      return this._sanitizer.bypassSecurityTrustHtml(html);
    }
  }
}

```

Then, you can use innerHtml like this:

`<p [innerHtml]="msg.detail | safeHtml"></p>`

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/MxSw4qOuwDfq7rLO7jrR?p=preview
