### ISSUE TITLE
Component: Buttons and table frozen column

### ISSUE THREAD

**Issue by benoitjry** [primefaces/primeng#13562]
### Describe the bug

https://github.com/primefaces/primeng/assets/140921945/978723e7-f688-4135-9b2f-0090f4e07049

When I put a button in table, the button overflow the frozen column. It's same with inputSwitch and checkbox component.

### Environment

I found this by working for my company but i reproduce it in the PrimeNG demo environement 

### Reproducer

https://stackblitz.com/edit/yf9ft6?file=src%2Fapp%2Fdemo%2Ftable-frozen-columns-demo.html

### Angular version

16.2.0

### PrimeNG version

16.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.20.0

### Expected behavior

the button should be "behind" the frozen column

**Comment by quentin-ineat-ca** [comment]
I think this fix breaks the header for frozen column.
Header goes behind the content when you scroll as the same z-index is shared.
Maybe also introduced with the new "@ layer" from 16.4.0 (introducing many breaking changes for a minor version in my opinion).

Working again if you remove the z-index introduced in PR #13590.

Inside inspect :
![Screenshot 2023-09-28 at 2 45 35 PM](https://github.com/primefaces/primeng/assets/110048454/265f0fdb-1acb-4692-812b-61e139aff24e)

Exemple :
![Screenshot 2023-09-28 at 2 54 47 PM](https://github.com/primefaces/primeng/assets/110048454/ee62e3d5-4cea-4f59-826f-605bdd648ced)
