### ISSUE TITLE
ComponePrimeNG 15.4.7-lts licence

### ISSUE THREAD

**Issue by nikhil-logicmo** [primefaces/primeng#13561]
### Describe the bug

I integrate lts license code as per documentation and working fine in development mode but on production it showing warning msg on top "You are using lts version of primeng with invalid license, you may either switch back to a non LTS-version or purchase a license at PrimeStore "

Angular version : 15.2.0
PrimeNG version : 15.4.7-lts
![262249559-ba251ea3-a9d6-4a33-a29d-a79f95969f08](https://github.com/primefaces/primeng/assets/140494260/333303f9-06cf-40c1-a1d6-882405c5f692)
![262249555-375e4ecb-5f62-4820-8dbb-5c1d9e6e3ac7](https://github.com/primefaces/primeng/assets/140494260/8c7b2246-ae46-4ebb-978b-e366ded68d0b)
![262249549-b76afb8a-b641-4ecf-add8-92a5c7ef21d2](https://github.com/primefaces/primeng/assets/140494260/5fc5ab57-503b-4330-a13c-d2644dedadd2)

### Environment

Angular version : 15.2.0
PrimeNG version : 15.4.7-lts

### Angular version

15.2.0

### PrimeNG version

15.4.7-lts

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.17.0

### Browser(s)

chrome,firefox,edge

### Steps to reproduce the behavior

add licence key in main.ts or app.component.ts constructor as per documentation after that on development mode it working fine(not showing warning message) ,after that make build using ng build command and run it on server it start showing license warning message.

### Expected behavior

remove warning message on production

**Comment by mertsincan** [comment]
Hi @nikhil-logicmo,

Could you please contact us at contact_at_primetek.com.tr ?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
