### ISSUE TITLE
onHide

### ISSUE THREAD

**Issue by cooligus** [primefaces/primeng#13565]
### Describe the bug

```html
<p-dialog
  [visible]="visible()"
  [modal]="true"
  [style]="{ width: '50vw' }"
  [draggable]="false"
  [resizable]="false"
  [dismissableMask]="true"
  (onHide)="hide()"
>
</p-dialog>
```

This is my dialog config. According to my tests, function passed to `onHide` executes only when `visible` is changed to `false`. I'm using signal here to control my dialog's visibility and I cannot give it directly to `p-dialog`.

### Environment

Angular 16 with signals

### Angular version

16.1.0

### PrimeNG version

16.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.17.0

### Expected behavior

When you click the background or 'X' button, the `onHide` executes whether `visible` is mutable or not.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
