### ISSUE TITLE
Toast: Expose default Toast Item life prop for overriding

### ISSUE THREAD

**Issue by sjwall** [primefaces/primeng#13577]
### Describe the feature you would like to see added

Add a property to Toast to allow for the default life for Toasts to be changed

### Is your feature request related to a problem?

The 3000ms default is not always suitable to client requirements when the toast messages may consistently be longer. In a larger code base this can be more difficult to manage a default life that is longer when it needs to be set on every message added to the message service

### Describe the solution you'd like

Add a property life to Toast like so:
```
<p-toast [life]="10000"></p-toast>
```
This will then override the 3000 default with 10000

### Describe alternatives you have considered

Wrapping the message service with a custom message service that adds a default life to all messages that don't have one specified

### Additional context

I have raised PR #13570 which covers implementing this prop

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primeng/pull/13570
