### ISSUE TITLE
[Menu] Menu has weak z-index 

### ISSUE THREAD

**Issue by dalenguyen** [primefaces/primeng#13576]
### Describe the bug

When opening menu item, the menu has an overlay issue due to the other element has a bigger z-index.

<img width="741" alt="image" src="https://github.com/primefaces/primeng/assets/14116156/3b28def7-4878-4399-ad46-5553b907935c">

Link: https://primeng.org/megamenua 

### Environment

Production

### Angular version

16.0.0

### PrimeNG version

16.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Steps to reproduce the behavior

Go to https://primeng.org/megamenu

Click on the menu to show the menu item
The demo links (stackblitz...) interfere with the menu item

### Expected behavior

The menu should have a bigger z-index than the other items. The current value is 1.

**Comment by ashikjs** [comment]
This issue also existed in MenuBar

![image](https://github.com/primefaces/primeng/assets/13074235/08738e12-4626-48b8-ba64-b583446af1f4)
