### ISSUE TITLE
Carousel lazy loading

### ISSUE THREAD

**Issue by hamz4arif** [primefaces/primeng#13575]
### Describe the feature you would like to see added

Subject: Feature Request: Lazy Loading Support for Carousel Component

Dear PrimeNG Team,

I hope this message finds you well. First, I want to express my appreciation for the incredible work your team has done in developing the PrimeNG library. It has significantly simplified the development of Angular applications.

I'm writing to propose a feature enhancement for the Carousel component. As web performance continues to be a critical aspect of modern applications, I believe that the addition of lazy loading support to the Carousel component could provide substantial benefits to both developers and end-users.

Lazy loading, as you may know, is an optimization technique that loads content, such as images, only when they are about to be displayed. This can lead to significant improvements in initial page load times and overall user experience. While the current Carousel component is powerful, incorporating lazy loading functionality would be a tremendous step forward in terms of performance.

Here are a few reasons why I believe adding lazy loading to the Carousel component would be highly beneficial:

1. Improved Initial Load Performance: Lazy loading would prevent unnecessary loading of images or content that the user might not immediately see, resulting in faster initial page load times.

2. Bandwidth Efficiency: By loading images only when they are needed, users on slower connections or limited data plans can have a smoother experience.

3. Enhanced User Experience: The Carousel component would provide a more seamless and fluid interaction, as users won't have to wait for all images to load before seeing the content.

4. Competitive Edge: Incorporating modern performance features like lazy loading can set PrimeNG apart and attract more developers looking for highly performant UI components.

I understand that implementing this feature may involve technical challenges, but I believe that the positive impact it could have on user experience would make it well worth the effort. I'm sure many in the developer community would greatly appreciate and benefit from this enhancement.

Thank you for considering my suggestion. Your commitment to continuously improving PrimeNG is truly commendable. I look forward to hearing your thoughts on the possibility of adding lazy loading support to the Carousel component.

### Is your feature request related to a problem?

its not related to a problem i just need to add lazy loading in the carousel

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
