### ISSUE TITLE
https://www.primefaces.org/primeng/showcase/#/multiselect

### ISSUE THREAD

**Issue by lakshmi2716** [primefaces/primeng#13573]
https://www.primefaces.org/primeng/showcase/#/multiselect
The latest version still has this breaking behavior.

Please let us know in which version will the fix be included?

_Originally posted by @KunalD2 in https://github.com/primefaces/primeng/issues/7047#issuecomment-1018239644_

**Comment by kroger-renu** [comment]
I have been currently using Primeng 17.11.0 version and this issue still hasn't been fixed. Is there any update on in which release will it be fixed or is it in progress? As @yigitfindikli once mentioned in 2018 that it is has been fixed, I can see it still failing, even in the primeng website demo examples.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
