### ISSUE TITLE
Charts cause page render on mouse move in RC5

### ISSUE THREAD

**Issue by chpasha** [primefaces/primeng#1357]
I'm afraid something is broken in RC5 in Chart component, after updating to this version my pages keeps rerendering itself every time I move a mouse anywhere or make a click even outside the chart. Maybe it is somehow related to this change https://github.com/primefaces/primeng/commit/5fb44ff176eb77ce43eb35c944c88e28b3a0619f#diff-8dd8b96d4cf84e05e482544ad0fcb481
~~The strange thing is that uninstalling RC5 and bringing back RC4 doesn't help~~ Sorry, it does help if cleaning npm cache, the stupid thing has installed rc5 inspite of rc4 in package.json

**Comment by mertsincan** [comment]
I think this issue is fixed for next release; https://github.com/primefaces/primeng/issues/1352
