### ISSUE TITLE
Calendar enhancement

### ISSUE THREAD

**Issue by rmarchiori** [primefaces/primeng#1358]
Hello guys, 

Here are a my original post with my suggestions: 

[http://forum.primefaces.org/viewtopic.php?f=35&t=48164&sid=2c04ad6dc249ef3d7cc161350d2ef9ff](url)

1. Add an input mask and key validation according to date format. Ex: (Accept only number ans special keys for dates)

2. Add support to keys up and down to add and subtract according to the section where the caret is located. Ex: Caret is located over the month, when you type up it'll add 1 to month and so on.  

3. Add support to show a custom mask once the field is null (kinda like you guys already do in input mask component. Ex: support custom masks in this case like aaaa-mm-jj (french)

Thanks,

**Comment by listerp** [comment]
I would also like to see this feature added, it is a must have.

**Comment by vorenus181** [comment]
I look forward for this feature too!

**Comment by igogu** [comment]
I am so interested too.

**Comment by br87m** [comment]
Please, add these features to calendar component!

**Comment by cagataycivici** [comment]
Please create separate feature request tickets so we can track them one by one, thank you for the feedback.

**Comment by mlakhara** [comment]
I have created the issue for data masking #3133
