### ISSUE TITLE
columnFilter: Add option template for columnFilter menu button

### ISSUE THREAD

**Issue by MatheusWebDev** [primefaces/primeng#13584]
### Describe the feature you would like to see added

I would like the possibility of define a template for the button in columnFilter when is in type 'menu'.

### Is your feature request related to a problem?

No.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
