### ISSUE TITLE
Modal Buttons not Allowing Custom Classes

### ISSUE THREAD

**Issue by wyattpuckett** [primefaces/primeng#13583]
### Describe the bug

We've noticed that confirm/cancel buttons in primeNG modals cannot have their classes customized. We work with another third-party company to track clicks across our platform. To do this, we insert properties on class attributes for buttons. We've realized that we cannot customize the classes for the dialog-accept and dialog-reject buttons within modals.

### Environment

In our environment, the user can create/delete objects. When deleting the object, we use a primeng dialog to allow the user to confirm/reject the deletion. We would like to track which button the user presses by inserting custom properties on the button classes.

### Angular version

15.2.1

### PrimeNG version

15.3.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.18.14

### Steps to reproduce the behavior

1. Add a dialog component to your code
2. Attempt to customize the class attributes for the confirm/reject buttons

### Expected behavior

Class attributes should allow addition of properties

**Comment by dylansyoung** [comment]
If you use the pTemplate="footer" inside of the dialogs, you can add your own buttons and as then add your own custom classes to the buttons. Example: 

<p-confirmDialog #cd [style]="{width: '50vw'}">
    <ng-template pTemplate="header">
        <h3>Header Content</h3>
    </ng-template>
    <ng-template pTemplate="footer">
        <button type="button" class="my-custom-class" pButton icon="pi pi-times" label="No" (click)="cd.reject()"></button>
        <button type="button" class="my-custom-class" pButton icon="pi pi-check" label="Yes" (click)="cd.accept()"></button>
    </ng-template>
</p-confirmDialog>

Does that solve your problem?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
