### ISSUE TITLE
Dropdown's panel does not open when it is created on higher z-index

### ISSUE THREAD

**Issue by Bhaveshshah777** [primefaces/primeng#13595]
### Describe the bug

I have created a dropdown on a overlay panel. This issue happens only in Mozilla firefox (I have tried Chrome and it is working fine)

As far a DOM, I noticed that both browser treats this event differently. Firefox creates a ::before pseudo class whereas chrome creates whole dropdown-panel component.

### Environment

This is Mozilla Firefox. I am using intel I7 processor. OS: Windows 11

### Angular version

12.1.2

### PrimeNG version

13.3.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.21.3

### Browser(s)

Mozilla Firefox Developer Edition

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
