### ISSUE TITLE
TabView: Lower border disappears on lower zoom

### ISSUE THREAD

**Issue by Khousheish** [primefaces/primeng#13598]
### Describe the bug

if you zoom out on a page that contains tabs, the lower border and active indicator disappear.

### Environment

Nothing special, Angular.

### Reproducer

https://stackblitz.com/edit/github-ubg2ne

### Angular version

16.0.4

### PrimeNG version

16.0.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.16.0

### Browser(s)

Chrome 115 specifically but what I can see all browsers

### Steps to reproduce the behavior

1. go to the attached stackblitz application [URL](https://github-ubg2ne.stackblitz.io) or the primeng tabview page [URL](https://primeng.org/tabview).
2. Zoom out (80 or 90%).
3. Observe as the bottom border disappears.

### Expected behavior

The bottom border is visable as well as the highlight.

**Comment by Khousheish** [comment]
Any update on this? We need to know how to move forward.

**Comment by ashsk46** [comment]
Facing the exact same issue and we would love to know when we can expect a fix.

**Comment by nicolasnevraumont** [comment]
Might be related: the lower border of the items gets thiner with windows recommanded screen scaling (125%).

Visible in the demo at https://primeng.org/tabview#template

**Comment by chsh3280** [comment]
No one answered this answer? Was it not taken care of?

**Comment by Khousheish** [comment]
Hi @chsh3280 we just recently upgraded to v17 and it seems that it got fixed. it is notreproducable anymore from our side or from the official PrimeNG website.
https://primeng.org/tabview

**Comment by Khousheish** [comment]
Closing as it got fixed in v17.

**Comment by chsh3280** [comment]
I look at the tabs on the site, reduce the resolution to 90% and I don't see the border on the tabs. I have attached a photo
![pic](https://github.com/primefaces/primeng/assets/59176231/cdd6dc3b-2221-4de2-a06e-e35703c19ac8)

**Comment by Khousheish** [comment]
<img width="2056" alt="Screenshot 2024-01-21 at 15 24 59" src="https://github.com/primefaces/primeng/assets/37106704/3536d30a-f887-4c67-878d-26589166a771">
That is weird 😅  as you can see from my side it seems fine. Maybe its based on the laptop, chrome version, aspect ration or resolution. No idea where to even start investigating this...

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
