### ISSUE TITLE
Drag and Drop event returns wrong data on P-Tree component

### ISSUE THREAD

**Issue by oasmat83** [primefaces/primeng#13592]
### Describe the bug

I'm calling the onNodeDrop emitter, but the event is returning the same dropNode and index for items that are re-ordered either to the second to last or last iteration.

Here is a screenshot of the console output when re-ordering an item to second to last or last in the list.

![image](https://github.com/primefaces/primeng/assets/8332561/231aa127-4ceb-4c03-922f-3b357a8a0784)

### Environment

OS: Windows 11 Pro

### Reproducer

https://stackblitz.com/edit/q2saaz?file=src%2Fservice%2Fnodeservice.ts

### Angular version

13.3.11

### PrimeNG version

13.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.15.0

### Browser(s)

Chrome Version 116.0.5845.111

### Steps to reproduce the behavior

Go to <p-tree> component that has onNodeDrop set. Drag and drop an item to the second to last or last item. The index and dropNode logged on the console are the same for both. 

### Expected behavior

I would expect the index and dropNode to be different.

I believe if I'm re-ordering an item to the end of the list the dropNode should probably return null

**Comment by jonnomk** [comment]
I second this.  We've had to disable drag and drop in all parts of our app that use the Tree component because it just doesn't work.  The data that gets returned from the onNodeDrop event makes no sense and you're not able to reliably determine where the item should be located.  A dropNode is returned when dropping between nodes, even when dropping at root level.  I would think a dropnode should only be returned if you're dropping into a node or at some index within a node, not root?  I really hope this is sorted in a future release.  I'm using version 15.2.

**Comment by jonnomk** [comment]
Just further from my last comment, the below is a screenshot from two different nodeDrop events:

![image](https://github.com/primefaces/primeng/assets/56191325/ffd62447-3639-49e5-81bc-33e96744151b)

The first one is dropping on a droppoint between two items, as shown below.

![image](https://github.com/primefaces/primeng/assets/56191325/ee405d83-73db-44e0-9274-281a700e5cf5)

The second is dropping into the team, as shown below.

![image](https://github.com/primefaces/primeng/assets/56191325/729f948d-92c6-4f8b-bedb-08c6c7a1fb93)

Both scenarios create the same data in the nodeDrop event, so we're unable to determine whether to accept the drop (we're using validateDrop).

**Comment by mehmetcetin01140** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.

**Comment by ilonachan** [comment]
The issue was not addressed, at all.
