### ISSUE TITLE
Column Filter: Auto close on Click Outside does not work

### ISSUE THREAD

**Issue by denny99** [primefaces/primeng#13596]
### Describe the bug

```javascript
    bindDocumentClickListener() {
        if (!this.documentClickListener) {
            const documentTarget: any = this.el ? this.el.nativeElement.ownerDocument : 'document';

            this.documentClickListener = this.renderer.listen(documentTarget, 'click', (event) => {
                if (this.overlayVisible && !this.selfClick && this.isOutsideClicked(event)) {
                    this.hide();
                }

                this.selfClick = false;
            });
        }
    }
```

According to the code of the Column Filter, the filter should automatically hide when clicking outside.
It does not right now.

Side Note:
When you use a datepicker or autocomplete as filter input (with appendTo=body) the filter will close when fixing this bug.

### Environment

PrimeNG Playground https://primeng.org/table#filter

### Reproducer

https://primeng.org/table#filter

### Angular version

16.x

### PrimeNG version

16.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

x

### Browser(s)

All

### Steps to reproduce the behavior

1. Goto the Menu Filter Demo
2. Open a Filter Menu
3. Click somewhere else or open other menus
4. Won't close as coded

### Expected behavior

Should close when clicking outside.

A solution for appendTo body inputs would be appreciated.

**Comment by cetincakiroglu** [comment]
Fixed in here https://github.com/primefaces/primeng/pull/13619
