### ISSUE TITLE
TabMenu: It does not update the items dynamically

### ISSUE THREAD

**Issue by aolle99** [primefaces/primeng#13609]
### Describe the bug

When you try to add a new item to the array of items after it has been rendered, it is not displayed, even if it is in the array of items.

### Environment

Angular v16.2.0
PrimeNG v16.3.1

### Reproducer

https://stackblitz.com/edit/5cvzhk?file=src%2Fapp%2Fdemo%2Ftab-menu-basic-demo.html

### Angular version

16.2.0

### PrimeNG version

16.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.0

### Steps to reproduce the behavior

In Reproducer (I used an example from your website because it didn't work for me in the template):

1. Press Add new Tab
2. Check how a new item does not appear, but if you look at the browser console, you will see that it has been added to the array

### Expected behavior

A new item has been added to the menu

**Comment by OfficerHalf** [comment]
I had this issue as well when attempting to bind `[model]` to a signal. The component just doesn't update.

**Comment by aolle99** [comment]
Any Solution?

**Comment by dalenguyen** [comment]
This is the nature of the change detection. You can utilize an immutable approach for it to work. For example:

```
this.items = [...this.items, { label: 'New tab', icon: 'pi pi-fw pi-pencil' }]
```

**Comment by tizon15** [comment]
the solution of @dalenguyen works for me, the only difference is that I'm using a ViewChild of the tabMenu, and instead of in the Html bidding the item, I'm using the tabMenu.model

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
