### ISSUE TITLE
Possibility to remove Message or Toast

### ISSUE THREAD

**Issue by sandrotonon** [primefaces/primeng#13600]
### Describe the feature you would like to see added

Method to remove Toast/Message programattically by ID

### Is your feature request related to a problem?

It's currently not possible to remove a specific Toast or Message. We got some longliving Toasts wich must be specifically deleted when an event occurs.

### Describe the solution you'd like

There should be a method to remove a specific Toast/Message by its ID

### Describe alternatives you have considered

Refactor the `clear(key?: string)` Method to take a key **or** id. But "clearing" seems to be more like "removeAll", at least for me.

### Additional context

See #8647 and #5663

I have raised PR https://github.com/primefaces/primeng/pull/13599 which covers implementing this method

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
