### ISSUE TITLE
FileUpload: Error Handling with `p-messages` rather than `p-toast`

### ISSUE THREAD

**Issue by Gykonik** [primefaces/primeng#13606]
### Describe the bug

The FileUpload component uses `<p-messages>` for displaying errors during file uploads. This leads to layout shifts and strange formatting. I think the proper way would be to use `<p-toast>`, or at least give the developer an option to switch between both.

Before:
![image](https://github.com/primefaces/primeng/assets/17333876/34b69dac-e5fc-43c2-b8ed-276bcf8f5f12)

After:
![image](https://github.com/primefaces/primeng/assets/17333876/78115a47-4b97-4672-b12e-c5837ef85617)

### Environment

Angular 16.2.3
PrimeNG 16.3.1

### Reproducer

https://stackblitz.com/edit/szdd2o?file=src%2Fapp%2Fdemo%2Ffile-upload-basic-demo.html

### Angular version

16.2.3

### PrimeNG version

16.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.10.0

### Steps to reproduce the behavior

1. Upload a file that will trigger an error (basically any file for this demo, because file size is set to 1 Byte).
2. Observe that the error is displayed using <p-messages> causing layout shifts.

### Expected behavior

It would be more user-friendly if the component supported using `<p-toast>` for error messages to prevent layout shifts. An optional flag to switch between `<p-messages>` and `<p-toast>` would be ideal.

**Comment by dalenguyen** [comment]
I think it will look better if we remove the styling for the card.

```
<div class="card flex justify-content-center" style="width: 150px">

TO 

<div class="card flex justify-content-center">
```

<img width="393" alt="image" src="https://github.com/primefaces/primeng/assets/14116156/cbee286e-d58e-4717-a1e4-c2eb81156d66">


Or do you have many cards that have the upload button?

**Comment by Gykonik** [comment]
I don't have many cards, but I have an upload button in my page header, so there is zero space to show such an inline `p-message`. That's why I would prefer at least an option or even `p-toast` by default, as it makes more sense in my opinion.

**Comment by mihapek** [comment]
p-toast for the messages would be great

**Comment by UltimatumGamer** [comment]
+1

**Comment by barthuygen** [comment]
+1

**Comment by inesDomi** [comment]
+1

**Comment by kheos31** [comment]
+1

**Comment by avolianiuk7** [comment]
+1

**Comment by Satbir-B** [comment]
+1

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Comment by Satbir-B** [comment]
Apologies I cant see any instruction on the new V19 File upload that would allow errors to appear in a P-Toast as opposed to a P-Message.

**Comment by AndrewNovik** [comment]
Same problem
