### ISSUE TITLE
OverlayPanel: Calendar and table inside OverlayPanel, click inside dissmiss the overlaypanel

### ISSUE THREAD

**Issue by penihel** [primefaces/primeng#13605]
### Describe the bug

Look this sample

https://primeng.org/overlaypanel#datatable

Try click to order the column, sometimes at 1st, sometimes at 2nd or 3rd click, the painel closes unexpectedly.

I'm also trying to place an inline "Calendar" inside an OverlayPanel, but when I click to browse previous months the panel unexpectedly closes as well.

### Environment

Angular 16.2
primeng 16.2

### Reproducer

https://primeng.org/overlaypanel#datatable

### Angular version

16.2.0

### PrimeNG version

16.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Browser(s)

Chrome

### Steps to reproduce the behavior

https://primeng.org/overlaypanel#datatable

### Expected behavior

the panel should stay open, only close when selecting the programmed action, or clicking outside the panel

**Comment by penihel** [comment]
nothing about this?

**Comment by penihel** [comment]
nothing about this?

**Comment by pete-mcwilliams** [comment]
Here's a simple repro for the calendar was about to raise this issue also... click on buttons in header left, right, month and year dismisses the overlay
https://stackblitz.com/edit/xzstuc?file=src%2Fapp%2Fdemo%2Foverlay-panel-basic-demo.html

**Comment by penihel** [comment]
@cagataycivici can you help here?

**Comment by cetincakiroglu** [comment]
Fixed in https://github.com/primefaces/primeng/pull/13809
