### ISSUE TITLE
Taking a screenshot of a PDropdown does not work as expected

### ISSUE THREAD

**Issue by The-Real-1** [primefaces/primeng#13602]
### Describe the bug

When trying to genrate a screenshot of a node , the generated screenshot representation of the node is cropped.

![result-screenshot-node](https://github.com/primefaces/primeng/assets/143707078/4118207c-cc8e-46e4-9fff-25cdea652846)

### Environment

Web browser on official PrimeNg site.

### Angular version

^16.0.0

### PrimeNG version

^16.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v18.16.1

### Browser(s)

Chrome Version 116.0.5845.141 

### Steps to reproduce the behavior

1. Visit https://primeng.org/dropdown

1. Open the Chrome dev tools , inspect the page and select the dropdown component like in this image :
![dropdown-inspection](https://github.com/primefaces/primeng/assets/143707078/a6825179-94a6-4506-884d-ad945dbe3f7e)

1. Then right-click in the inspector section targeting the dropdown component and select `Capture node screenshot` like in this image : 

![dropdown-screenshot-node](https://github.com/primefaces/primeng/assets/143707078/721e82db-cdf6-412a-a257-adbd20e0203a)

1. Go to your Download folder and check the generated image : 

![result-screenshot-node](https://github.com/primefaces/primeng/assets/143707078/fe95786d-bf72-40a3-b5a6-84fc7b54f491)

### Expected behavior

The generated image should not be croped.

**Comment by The-Real-1** [comment]
Any ideas/returns about this behaviour ?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
