### ISSUE TITLE
Every component don't work

### ISSUE THREAD

**Issue by pigisfre** [primefaces/primeng#13614]
### Describe the bug

For every component of prime ng I get this error.
`Error: src/app/dashboard/vehicle/vehicle/vehicle.component.html:4:5 - error NG8001: 'p-button' is not a known element:
1. If 'p-button' is an Angular component, then verify that it is part of this module.
2. If 'p-button' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

4     <p-button label="Check"></p-button>
      ~~~~~~~~~~~~~~~~~~~~~~~~

  src/app/dashboard/vehicle/vehicle/vehicle.component.ts:9:16
    9   templateUrl: './vehicle.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component VehicleComponent.

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ 
**

× Failed to compile.`

I am using the latest version of angular and prime ng.

### Environment

Windows 10, Visual studio.

### Angular version

16.1.7

### PrimeNG version

16.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

9.6.7

**Comment by SoyDiego** [comment]
You need to add the Module that integrate the component that you want to use.
In your error message you need to add `ButtonModule`

**Comment by pigisfre** [comment]
@SoyDiego I inserted the ButtonModule but it still doesn't work

**Comment by SoyDiego** [comment]
> @SoyDiego I inserted the ButtonModule but it still doesn't work

Share a stackblitz, like this is impossible help you. 
And it's not problem of PrimeNG, PrimeNG works ok, you are not importing the modules in the correct way

**Comment by pigisfre** [comment]
`import { Component, OnInit } from '@angular/core';
import { PrimeNGConfig } from 'primeng/api';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {
  title = 'bosch-vehicle-certificate';

  constructor(private primengConfig: PrimeNGConfig) {} 
  ngOnInit() { this.primengConfig.ripple = true;}
}
` This is my app component

**Comment by pigisfre** [comment]
`import { CUSTOM_ELEMENTS_SCHEMA, NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { AuthenticationModule } from './authentication/authentication.module';
import { DashboardModule } from './dashboard/dashboard.module';
import { StoreModule } from '@ngrx/store';
import { fakeBackendProvider } from './_fakeBackend/fakeBackendInterceptor';
import { HttpClientModule } from '@angular/common/http';



@NgModule({
  declarations: [
    AppComponent,   
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    AuthenticationModule,
    DashboardModule,
    HttpClientModule,
    StoreModule.forRoot({}, {}),  
  ],
  providers: [ fakeBackendProvider,],
  bootstrap: [AppComponent],
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class AppModule { }
`
app.module

**Comment by pigisfre** [comment]
`import { CUSTOM_ELEMENTS_SCHEMA, NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { DashboardRoutingModule } from './dashboard-routing.module';
import { DashboardComponent } from './dashboard/dashboard.component';
import { RbUiComponentsModule } from '@inst-iot/bosch-angular-ui-components';

@NgModule({
  declarations: [
    DashboardComponent,
  ],
  imports: [
    CommonModule,
    DashboardRoutingModule,
    RbUiComponentsModule, 
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class DashboardModule { }
`
The dashboard module

**Comment by pigisfre** [comment]
`import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { DashboardComponent } from './dashboard/dashboard.component';

const routes: Routes = [
  {
    path: '', component: DashboardComponent,
    children: [
      { path: '', redirectTo: '/dashboard/vehicle', pathMatch: 'full' },
      { path: 'dashboard/vehicle', loadChildren: () => import('./vehicle/vehicle-routing.module').then(m => m.VehicleRoutingModule) },
    ],
  },
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule]
})
export class DashboardRoutingModule { }
`

**Comment by pigisfre** [comment]
`import { CUSTOM_ELEMENTS_SCHEMA, NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { VehicleComponent } from './vehicle/vehicle.component';
import { VehicleRoutingModule } from './vehicle-routing.module';
import { TableModule } from 'primeng/table';
import { ButtonModule } from 'primeng/button';




@NgModule({
  declarations: [
    VehicleComponent
  ],
  imports: [
    CommonModule,
    VehicleRoutingModule,
    TableModule,
    ButtonModule
    
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class VehicleModule { }
`

**Comment by pigisfre** [comment]
`import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { VehicleComponent } from './vehicle/vehicle.component';

const routes: Routes = [
  {path : '', redirectTo: 'dashboard/vehicle/', pathMatch: 'full'},
  {path : '', component: VehicleComponent}
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule]
})
export class VehicleRoutingModule { }
`

**Comment by pigisfre** [comment]
<p>vehicle works!</p>


    <p-button label="Check"></p-button>

**Comment by mayCh12** [comment]
did you have a response for this problem plz ?
