### ISSUE TITLE
p-image: preview image execute ngSubmit

### ISSUE THREAD

**Issue by smootyDev** [primefaces/primeng#13611]
### Describe the bug

I have a form 

```
<form (ngSubmit)="onFormSubmit()">
<p-image [src]="imageURL" width="90" height="90" alt="image" [preview]="true"></p-image>
</form>
```
When I click to preview image, onFormSubmit method is executed it and It's wrong. 

### Environment

Anyone

### Angular version

16.2.2

### PrimeNG version

16.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.15.1

### Expected behavior

ngSubmit form must not be executed when I click on preview image.

`<div class="p-image-preview-indicator"...`
 was changed  
`<button class="p-image-preview-indicator" ...`  a month ago.

type="button" must be present

**Comment by gucal** [comment]
Fixed https://github.com/primefaces/primeng/pull/13648. 

Thanks for report.
