### ISSUE TITLE
MenuModule items don't get active styling

### ISSUE THREAD

**Issue by MAN-Sendance** [primefaces/primeng#13615]
### Describe the bug

I am using PrimeNg with [theme-base](https://github.com/primefaces/primeng-sass-theme/tree/main/theme-base) and [my-theme](https://github.com/primefaces/primeng-sass-theme/tree/main/themes/mytheme).

routerLinkActive is not working since `p-menuitem-link-active` does not exist in `_mixins.scss`

It would require something like this:

```
@mixin menuitem {
  > .p-menuitem-content {
     ...

    .p-menuitem-link-active {
      color: $menuitemTextActiveColor;
      background-color: $menuitemActiveBg;

      .p-menuitem-text {
        color: $menuitemTextActiveColor;
      }

      .p-menuitem-icon {
        color: $menuitemIconActiveColor;
      }

      .p-submenu-icon {
        color: $menuitemIconActiveColor;
      }
    }

    ...
  }
}
```

### Environment

Ubuntu / Angular / PrimeNg / Prime Sass Themes

### Angular version

16.2.3

### PrimeNG version

16.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.17.1

### Expected behavior

Menu items which use routerLink should get correct styling (color, background-color, etc) when the route matches the current route and due to that `.p-menuitem-link-active` is applied

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
