### ISSUE TITLE
[DataTable] Row selection focus styling issue

### ISSUE THREAD

**Issue by atakantepe** [primefaces/primeng#13617]
Offset should be `outline-offset: -0.15rem;` like in the PrimeVue

![image](https://github.com/primefaces/primeng/assets/28745098/3223e800-1821-476e-afef-11424f64d698)
![image](https://github.com/primefaces/primeng/assets/28745098/daf7ae3f-16a7-4596-87ef-53ddce577211)

**Comment by SoyDiego** [comment]
Hi @atakantepe @gucal, sorry for delay. I was in holidays ^^
I fixed the value in `primeng-sass-theme`. You can check here: https://github.com/primefaces/primeng-sass-theme/pull/44

Thanks!
