### ISSUE TITLE
p-sidebar: suggestion panel of autocomplete is closed when scrolling inside p-sidebar component

### ISSUE THREAD

**Issue by Ixiondbz** [primefaces/primeng#13613]
### Describe the bug

This bug occurs when you place the autocomplete component(p-autoComplete) inside a sidebar component(p-sidebar). Whenever the suggestion panel of autcomplete is opened, it is hidden automatically whenever the user tries to scroll(vertically) in the sidebar. This phenomena doesn't occur if p-autoComplete is placed outside of p-sidebar. This behavior causes an unpleasant user experience in mobile devices. 

**Edit**: This same behavior also happens to **p-dropdowns**, **p-multiselect** and even **p-dialog** component. 

### Environment

Angular: 16.2.0
Primeng: 16.3.1

### Reproducer

https://stackblitz.com/edit/8usf2g?file=package-lock.json

### Angular version

16.2.0

### PrimeNG version

16.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.20.0

### Steps to reproduce the behavior

1. Create a primeng page with a p-sidebar component that possibly uses a button to open the sidebar.
2. Place one p-autoComplete component inside the p-sidebar and a second p-autoComplete outside p-sidebar.
3. Run the angular app.
4. Click OR type some characters in p-autoComplete component that is placed OUTSIDE of p-sidebar to trigger open the suggestion panel. Try to scroll up and down outside of the suggestion panel using mouse(for laptops/PCs) or finger touch(mobile screens/tablets).
5. Click OR type some characters in p-autoComplete component that is placed INSIDE of p-sidebar to trigger open the suggestion panel. Try to scroll up and down outside of the suggestion panel using mouse(for laptops/PCs) or finger touch(mobile screens/tablets).

### Expected behavior

Scrolling both inside and outside of p-sidebar shouldn't affect the visibility of p-autoComplete's suggestion panel. 

The panel should remain open if the user scrolls inside the sidebar just as it remains open if they scroll outside of p-sidebar.

**Comment by Ixiondbz** [comment]
> I agree. However, this doesn't cause the issue.

**Comment by Ixiondbz** [comment]
> There should not be style="height: 1200px" in p-sidebar. Its a component not a element tag.

I agree. However, this doesn't cause the issue.

**Comment by pragyaInexture08** [comment]
Also when I have autocomplete inside sidebar, and sidebar when opened from right, then everythings is fine it takes left: -35px auto-adjusts. But when sidebar is opened form left, autocomplete doesn't auto adjusts and scroll start coming, and above issue comes.

**Comment by naisharshah31** [comment]
This is still reproduceable with latest Prime NG version (v19), on scroll suggestion panel is closed and even through autocomplete options are available it doesn't reopen on autocomplete focus
