### ISSUE TITLE
Datatabe: header filtering with a p-calendar or p-select gets cropped and cannot be scrolled

### ISSUE THREAD

**Issue by TheFabio** [primefaces/primeng#13625]
### Describe the bug

This issue can be observed [on the filter row example page](https://primeng.org/table#filter-row), as below, the p-select filter gets cropped: 
![image](https://github.com/primefaces/primeng/assets/13587934/b8a9264a-cb20-4342-9a3b-cc0ea9066b61)

A calendar becomes useless, because on top of the cropping, when you scroll it closes:
![image](https://github.com/primefaces/primeng/assets/13587934/55b8babc-ba5a-4541-bcb5-709326977ceb)

### Environment

simple angular app with primeng 16.2.0

### Angular version

16.2.0

### PrimeNG version

16.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.5.1

### Browser(s)

Any

### Steps to reproduce the behavior

Go to https://primeng.org/table#filter-row

filer country by "al" startswith
click on status filter:
![image](https://github.com/primefaces/primeng/assets/13587934/b8a9264a-cb20-4342-9a3b-cc0ea9066b61)

### Expected behavior

The selection control not to be cropped
A date pick control not to be cropped

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
