### ISSUE TITLE
Table

### ISSUE THREAD

**Issue by GusBeare** [primefaces/primeng#13628]
### Describe the bug

Date filtering breaks when the date has a timestamp.

My data set has dates that look like this.

    "endTime": "2019-10-21 08:34:29"

My table filtre code is like this:

      <ng-container *ngIf="col.filterType === 'date'">
            <p-columnFilter
              [type]="col.filterType"
              [field]="col.field"
              display="menu"></p-columnFilter>
          </ng-container>

Data display:  I need to show the time in the grid.

    {{ rowData[col.field] | date: 'dd-MM-YYYY hh:mm'}}

When I try to filter on these dates using the filter menu I get this error.

ERROR TypeError: value.getTime is not a function
    at dateAfter (primeng-api.mjs:306:26)
   
Am I doing something wrong? Do I need to format the data before passing to the component?

### Environment

Latest Angular with latest PrimEng as of today 7/9/23.

### Angular version

16.2.0

### PrimeNG version

16.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

9.5.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

Create a data set with dates like  "2019-10-21 08:34:29".

Set up a table with date filtering using display="menu".

Try any filter.

### Expected behavior

Filtering should ignore the timestamp and filter the grid based on the date.

**Comment by dalenguyen** [comment]
I think you need to convert the time to the Date object. E.g. `new Date(date)`

**Comment by GusBeare** [comment]
thanks 
where would I do this?  The examples show dates as strings in json. Surely the prime code reads the date strings into a date object when it loads the data?

    var dt= "2019-10-21 08:34:29";
    dto = new Date(dt);
    console.log(dto);
    var j = JSON.stringify(dto);
    console.log(j);

I can read my date strings just fine and then when I convert them back to json I get the same data I passed in.

Confused I am.

**Comment by dalenguyen** [comment]
Can you create a sample Stackblitz for this?

**Comment by GusBeare** [comment]
Sure.

https://primeng-tablefilter-demo-5frmpu.stackblitz.io

If you look at the company json you can see I changed the first row to:

 "company": "Benton, John B Jr",
      "date": "2019-10-21 08:34:29",

The date filtering does not work for that date. But it does work for others. I can't replicate the error but it may be because all my dates have times.

**Comment by GusBeare** [comment]
hmm.. date after works. 

I will have to check my code since date after doesn't work on my dev code and I can't see anything different.

**Comment by dalenguyen** [comment]
Probably, the version of Angular & PrimeNg is different in Stackblitz?

**Comment by GusBeare** [comment]
I can't work this out at all. I created a stack b with latest Angular and PrimeNg and it works fine:

https://stackblitz.com/edit/primeng-tablefilter-demo-5frmpu?file=src%2Fapp%2Fapp.component.html

Then I thought it might be because I need to show/hide cols based on data and there might be a mistake where the filter is working on the wrong col. Show I showed all cols and same issue.

The only other thing I can think of that's different is the data being an observable.

    ngOnInit(): void {
    this.receipts$ = this.store.select(fromReceipts.selectReceipts);
    
And in the template:

    <p-table
    [columns]="cols"
    [value]="(receipts$ | async)!"

Any ideas?

**Comment by GusBeare** [comment]
It works fine like this:
   <p-columnFilter
        type="date"
         [field]="col.field"></p-columnFilter>

But it breaks with display="menu".

**Comment by GusBeare** [comment]
Could it just be because some of the dates are null?

 "endTime": null,

**Comment by GusBeare** [comment]
No, that's not it. Works fine in the stackblitz.

**Comment by dalenguyen** [comment]
> I can't work this out at all. I created a stack b with latest Angular and PrimeNg and it works fine:
> 
> https://stackblitz.com/edit/primeng-tablefilter-demo-5frmpu?file=src%2Fapp%2Fapp.component.html
> 
> Then I thought it might be because I need to show/hide cols based on data and there might be a mistake where the filter is working on the wrong col. Show I showed all cols and same issue.
> 
> The only other thing I can think of that's different is the data being an observable.
> 
> ```
> ngOnInit(): void {
> this.receipts$ = this.store.select(fromReceipts.selectReceipts);
> ```
> 
> And in the template:
> 
> ```
> <p-table
> [columns]="cols"
> [value]="(receipts$ | async)!"
> ```
> 
> Any ideas?

I tried to turn your property into an observable. It sill works in Stackblitz.

**Comment by GusBeare** [comment]
Thanks for trying. I give up for now. Have to move onto other stuff.

**Comment by dalenguyen** [comment]
I guess it was fixed in the latest version. You may want to upgrade your application.

**Comment by GusBeare** [comment]
I just upgraded to latest and I get the same issue. I thought that it might be because I am dynamically showing/hiding cols, headers and filters using hidden.

  <th *ngFor="let col of columns" [hidden]="!col.visible">

But I went through the template and made them all static and got the same issue. It doesn't seem to matter how I format the date.

    ERROR TypeError: value.getTime is not a function
    at dateAfter (primeng-api.mjs:306:26)
    at Table.executeLocalFilter (primeng-table.mjs:1718:16)
    at Table._filter (primeng-table.mjs:1662:51)
    at ColumnFilter.onRowMatchModeChange (primeng-table.mjs:5220:17)
    at _class25_div_4_ul_2_li_1_Template_li_click_0_listener (primeng-table.mjs:5557:34)
    at executeListenerWithErrorHandling (core.mjs:16195:16)
    at wrapListenerIn_markDirtyAndPreventDefault (core.mjs:16228:22)
    at HTMLLIElement.<anonymous> (platform-browser.mjs:665:17)
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at core.mjs:27127:55

![prime_issue](https://github.com/primefaces/primeng/assets/5166509/f0afc90a-4c33-40ad-b9c2-a4a0cdba86cd)

**Comment by GusBeare** [comment]
I noticed the Stackb has this:

 "primeng": "^13.4.1",

but the latest release if 13.3.1

**Comment by GusBeare** [comment]
I've seen this in the filter examples:

this.customers.forEach((customer) => (customer.date = new Date(<Date>customer.date)));

dates are converted to date objects. However, this is not the same in all the examples. BUT, when I stopped using the observable and manually created the data object like this:

     const row: Receipt = {
         startTime: new Date(),
         endTime: new Date(),

    this.someData = [];
    this.someData.push(row);

Then it fixed the issue.  It would really help if there was clarity in the documentation.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
