### ISSUE TITLE
Drop-down: Navigation using Tab press and shift tab is not working

### ISSUE THREAD

**Issue by Mdimraan23** [primefaces/primeng#13623]
### Describe the bug

Navigation using keyboard with tab and shift tab is not working when drop-down control is present

### Environment

Primeng version 16.3.1, 16.2.0 works fine in 16.1.0

### Angular version

16

### PrimeNG version

16.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.2.0

**Comment by AEonWho** [comment]
Ran into the same Problem, works on 16.2.0 but not on 16.3.1
I think this commit introduced this issue: https://github.com/primefaces/primeng/commit/b1efe18a85b7e0bb86ecbf93fe830ad2b67f86ff
