### ISSUE TITLE
Dropdown: The option changes when navigating between dropdowns in p-table using arrow keys

### ISSUE THREAD

**Issue by StefanEJonsson** [primefaces/primeng#13620]
### Describe the bug

I have a p-table where some of the cells contain dropdowns. When a cell is selected I can change the selection using the arrow keys to navigate between cells in the table. But when I have a dropdown cell selected and press down or up both the table and the dropdown react to the key event, resulting in the dropdown-alternative being changed when I navigate down or up in the table.

I tried to solve this by making the dropdown readonly except when shift is down. Then I could use up/down to navigate between cells and shift+up/shift+down to change alternative. The problem is that then the dropdown is only clickable when shift is down, which I suspect most users will not find very intuitive.

### Environment

Probably the same issue independent of environment. The stackblitz example I linked to is not mine but it demonstrates the problem pretty well.

### Reproducer

https://stackblitz.com/edit/primeng-dropdown-demo-smm-001?file=src%2Fapp%2Fapp.component.html

### Angular version

16.2.2

### PrimeNG version

16.2.0

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

v16.14.2

### Browser(s)

chrome

### Steps to reproduce the behavior

In the stack-blitz example, select a cell in the table and navigate between cells using the arrow keys. When a cell with a dropdown is selected, press down. The focus moves to the cell below, which is correct but the dropdown also changes its selected item. If you press shift+down, the dropdown changes its selection and the focus is not moved. So there is a way of changing the dropdown without changing the focus, but there is no way of changing the focus without changing option.

### Expected behavior

There needs to be some way to tell the dropdown to only react to arrow-keys if shift is down.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
