### ISSUE TITLE
Datatable: Virtual Scroll Lazy

### ISSUE THREAD

**Issue by georg-adler** [primefaces/primeng#13621]
### Describe the bug

When using the primeng table with virtual scrolling and lazy loading enabled, the following error is thrown when the first new data was loaded:
<details><summary>Error message</summary>
<p>

core.mjs:10920 ERROR TypeError: Cannot read properties of null (reading 'scrollTop')
    at Scroller.onScrollPositionChange (primeng-scroller.mjs:723:53)
    at Scroller.onScrollChange (primeng-scroller.mjs:770:65)
    at primeng-scroller.mjs:804:22
    at timer (zone.js:3084:47)
    at _ZoneDelegate.invokeTask (zone.js:450:35)
    at core.mjs:27127:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:27127:36)
    at _ZoneDelegate.invokeTask (zone.js:449:64)
    at Object.onInvokeTask (core.mjs:27437:33)
    at _ZoneDelegate.invokeTask (zone.js:449:64)

</p>
</details> 

The error seems to happen because of the timeout in "onContainerScroll":
![onContainerScroll](https://github.com/primefaces/primeng/assets/127318497/8dfe99ed-13d6-49a7-8820-a2ab521cc7a2)

event.target is null there, leading to an error down the line:

![onScrollPositionChange](https://github.com/primefaces/primeng/assets/127318497/28826833-30c6-4130-aee8-51084508dc95)

### Environment

Running in angular 16 with node 18.15.0
ShadowDom is enabled on the Component using the table

### Reproducer

https://stackblitz.com/edit/epnkmf?file=src%2Fapp%2Fdemo%2Ftable-virtual-scroll-lazy-demo.ts

### Angular version

16.2.2

### PrimeNG version

16.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.15.0

### Browser(s)

Chrome 116

EDIT: add reproducer based on the example in the documentation

**Comment by tobikugel** [comment]
Is there any update on this issue? I face the same problem.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
