### ISSUE TITLE
Component: Panelmenu SubMenus not supported HTML content

### ISSUE THREAD

**Issue by roman-bychkov** [primefaces/primeng#13637]
### Describe the bug

Nested MenuItems no longer support HTML content.
`escape: false` doesn't change anything

![image](https://github.com/primefaces/primeng/assets/32703652/04cd7b48-8e1f-42fc-8cd3-0e1671fc5f9d)

### Environment

x

### Reproducer

https://stackblitz.com/edit/iezdha?file=package.json

### Angular version

16.2.0

### PrimeNG version

16.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v18.12.1

### Expected behavior

Nested menuItems should support HTML content

**Comment by roman-bychkov** [comment]
any updates?

**Comment by ashikjs** [comment]
@roman-bychkov  Thanks for your issue report, I solved and make a Pull request for this issue. Hope fully primng team will approved it in next release .
