### ISSUE TITLE
Panel: using Collapse function does nothing

### ISSUE THREAD

**Issue by dolphinsd** [primefaces/primeng#13631]
### Describe the bug

Here is a sample
https://stackblitz.com/edit/expbcb?file=src%2Fapp%2Fdemo%2Fpanel-toggleable-demo.ts

Calling collapse on open panel should collapse it.

### Environment

Chrom

### Reproducer

https://stackblitz.com/edit/expbcb?file=src%2Fapp%2Fdemo%2Fpanel-toggleable-demo.ts

### Angular version

16.2.0

### PrimeNG version

16.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

latest

### Browser(s)

Chrome

### Steps to reproduce the behavior

Run example

### Expected behavior

should collapse panel

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
