### ISSUE TITLE
p-dialog: ExpressionChangedAfterItHasBeenCheckedError with attr.aria-labelledby

### ISSUE THREAD

**Issue by psarno** [primefaces/primeng#13636]
### Describe the bug

I know some work is being done here on accessability, and I saw a [related issue](https://github.com/primefaces/primeng/issues/13497) but not with the `p-dialog` component.

We are on the latest PrimeNG version (16.3.1).

The exception is:

> ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value for 'attr.aria-labelledby': 'pn_id_70_header'. Current value: 'pn_id_73_header'. Expression location: _Dialog component

Call Stack:

    at throwErrorIfNoChangesMode (core.mjs:11010:11)
    at bindingUpdated (core.mjs:14251:17)
    at ɵɵattribute (core.mjs:14295:9)
    at Dialog_div_0_div_1_Template (primeng-dialog.mjs:357:8)
    at ReactiveLViewConsumer.runInContext (core.mjs:11103:13)

Line in primeng-dialog.mjs triggering this:

![image](https://github.com/primefaces/primeng/assets/18640860/f2cb938e-7a57-448e-aa3d-4f4adaa81f4a)

Dialog defined as:

```
<p-dialog
  [(visible)]="showUpdateMultiPointerDialog"
  [modal]="true"
>

```
**Also** - Can we get an updated reproducer template that isn't on Angular 14 and PrimeNG 14?

I am unable to update the template in stackblitz to Angular 16/PrimeNG 16, no matter what I try [I end up with](https://stackblitz.com/edit/github-qfq83u?file=package.json,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts):

> Error in /turbo_modules/primeng@16.3.1/fesm2022/primeng-tieredmenu.mjs (137:252)
> Cannot access 'TieredMenu' before initialization

### Environment

Angular 16.2.2
PrimeNG 16.3.1

### Angular version

16.2.2

### PrimeNG version

16.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Steps to reproduce the behavior

1. Create a p-dialog component
2. Set it's [(visible)] property to a boolean flag
3. Set the boolean to true to show the dialog

### Expected behavior

There is no ExpressionChangedAfterItHasBeenCheckedError

**Comment by SoyDiego** [comment]
I think I did a PR about that.
I will check again

**Comment by psarno** [comment]
@SoyDiego I appreciate the assistance, I have edited the title, it was wrong.  This is clearly occuring in the "_Dialog component" as per the stack trace.

Will that PR resolve this issue?   It was merged but did it get into 16.3.1?

If so, then the problem persists.

**Comment by psarno** [comment]
@SoyDiego I appreciate the help.

It's in the dialog component, as per the stack trace:

> at Dialog_div_0_div_1_Template (primeng-dialog.mjs:357:8)

And error:

> Expression` location: _Dialog component

I see the PR was merged.   Did that go out with 16.3.1?

If so then an issue persists here.

**Comment by SoyDiego** [comment]
> 

Yes, was merged. It's very weird.
Tomorrow I will check again and I will update here.

**Comment by SoyDiego** [comment]
Now I saw the problem.
My issue was fixed in `dynamic dialog` and this is `dialog`. They are different. I will try to solve again tomorrow.

Thanks for report the issue

**Comment by SoyDiego** [comment]
Hi @psarno I tried to replicate your problem but I cannot see errors and anything.

##  My code

![image](https://github.com/primefaces/primeng/assets/19764334/fe590a82-19ee-4895-be90-278eef51f585)

![image](https://github.com/primefaces/primeng/assets/19764334/c0fe3f41-3944-4120-b301-3ad79073d812)

## Testing

![testing dialog](https://github.com/primefaces/primeng/assets/19764334/90abc301-76d2-4d43-a6e6-e26a25bad91e).

For that maybe is good idea if you can replicate with Stackblitz.

Thanks again

**Comment by psarno** [comment]
It seems to be the exact same issue as was occuring in #13497 just in a different component.

It may be difficult to reproduce, I am not sure what the underlying cause is but it's probably no coincidence that we have the same error in two similar components on the same exact statement (with the `attr.aria-labelledby`).  I am aware work is being done on accessibility in PrimeNG, and this happens to be happening on an accessibility 

Sometimes these things are not always immediately reproducible and we have to go off crash reports and put in defensive coding or fixes simply based off reports that include the call stack, such as this one does.

Since this looks to be literally the same problem, with the same code, just in a different component, why not apply the same fix here to be safe?

![image](https://github.com/primefaces/primeng/assets/18640860/71964cb4-9d21-471f-9a2c-7cac366cb8fb)

**Comment by SoyDiego** [comment]
> @SoyDiego It seems to be the exact same issue as was occuring in #13497 just in a different component.
> 
> It may be difficult to reproduce, I am not sure what the underlying cause is but it's probably no coincidence that we have the same error in two similar components on the same exact statement (with the `attr.aria-labelledby`).
> 
> Sometimes these things are not always immediately reproducible and we have to go off crash reports and put in defensive coding or fixes simply based off reports that include the call stack, such as this one does.
> 
> Since this looks to be _literally the same problem_, with the same code, just in a different component, why not apply the same fix here to be safe? It was needed in one, why would it not be needed in both?
> 
> ![image](https://user-images.githubusercontent.com/18640860/266783595-71964cb4-9d21-471f-9a2c-7cac366cb8fb.png)
> 
> And as I asked in the original post, is there any reason we don't have an updated Stackblitz repro template that uses the latest PrimeNG 16? I can not get 16 to work on StackBlitz, [I am unsure why it throws this error](https://stackblitz.com/edit/github-qfq83u?file=package.json,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts).

@psarno I will create a new PR adding the same implementations because you are right, It's the same problem but I don't know why can't replicated. And I'm not decide this things and I don't know why Stackblitz is not working.
I'm not part of PrimeNG Team, only a contributor here trying to help, ok?
Also I don't know If PrimeNG Team will approve it, because again, I tested and I cannot replicated the problem, and you are the only user with that problem. In that issue (#13497), a lot of problem were reporting.

**Comment by psarno** [comment]
The error is occuring in the `<p-dialog>` component as shown by the call stack, but our actual repro scenario is a component setup such as the following:

```
<p-dialog>
   <ng-template pTemplate="body">
      <p-autoComplete></p-autoComplete>
    </ng-template>
</p-dialog>
```

That is overly simplified but it shows the control that causes this error to occur.

When we type a character into the `<p-autoComplete>`, it immediatly throws the 
`ExpressionChangedAfterItHasBeenCheckedError`.   Note however, that this is **not** occuring in the `<p-autoComplete>`, even though that triggers it to occur ... it is occuring in the `<p-dialog>` as per the call stack.

**Comment by psarno** [comment]
@SoyDiego Understood that you're just a contributor, you are doing a great work with the PRs.

I am also just leaving these notes here so the PrimeNG team can see the logic behind what is going on, if this is ever merged.

@cagataycivici Is there any chance we can get an officially updated Stackblitz template for PrimeNG from your team to version 16?   The current one is on 14.  I have [tried to get it working](https://stackblitz.com/edit/github-qfq83u?file=package.json,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts) with 16 but run into one particular error I haven't figured out.

**Comment by SoyDiego** [comment]
> The error is occuring in the `<p-dialog>` component as shown by the call stack, but our actual repro scenario is a component setup such as the following:
> 
> ```
> <p-dialog>
>    <ng-template pTemplate="body">
>       <p-autoComplete></p-autoComplete>
>     </ng-template>
> </p-dialog>
> ```
> 
> That is overly simplified but it shows the control that causes this error to occur.
> 
> When we type a character into the `<p-autoComplete>`, it immediatly throws the `ExpressionChangedAfterItHasBeenCheckedError`. Note however, that this is **not** occuring in the `<p-autoComplete>`, even though that triggers it to occur ... it is occuring in the `<p-dialog>` as per the call stack.

I tried with this example too and I couldn't see the problem.
Anyway, I have created a PR here: https://github.com/primefaces/primeng/pull/13644 applying the same solution as `dynamycdialog` component.
Will see If PrimeNG Team approve it or not.

**Comment by jncalderon** [comment]
@psarno @cetincakiroglu  hi guys, I see that this fix become on 16.4.2 release, how I can get before?

**Comment by cetincakiroglu** [comment]
Hi @psarno,

You can't get before, we'll release it today!

**Comment by psarno** [comment]
I am still seeing this today on 16.4.1.  The odd thing is this occurs as soon as I click on a plain `<p-button>` component inside of a `<p-dialog>`:

> Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value for 'attr.aria-labelledby': 'pn_id_60_header'. Current value: 'pn_id_63_header'. Expression location: _Dialog component.
