### ISSUE TITLE
Wrong documentation about table body

### ISSUE THREAD

**Issue by Dzerominik** [primefaces/primeng#13635]
https://github.com/primefaces/primeng/blob/d7177ab835dc8bb61df7771deb26756742e7a439/src/app/showcase/doc/apidoc/index.json#L21169C61-L21169C64

Should it be " $implicit: any, // Row data." and not " $implicit: any, // Columns."))

**Comment by SoyDiego** [comment]
Hi @Dzerominik, I was checking the issue in docs and I think is OK `Columns`, look the code of the component:

![image](https://github.com/primefaces/primeng/assets/19764334/ace42f1a-5cdc-42f9-9234-64427ecd1f85)

Could you confirm this for me @mertsincan @gucal, please?

If I'm wrong, I can change it. 

Thanks

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
