### ISSUE TITLE
Listbox: pTemplate="filter" not displayed when showToggleAll is false

### ISSUE THREAD

**Issue by RepentAndBelieveTheGospel** [primefaces/primeng#13643]
### Describe the bug

When setting showToggleAll to false, the filter template is not displayed anymore.

Attributes used:

- [(ngModel)]
- options
- [checkbox]="true"
- [multiple]="true"
- optionLabel
- filterBy
- [showToggleAll]="false"

Templates used:

- pTemplate="header"
- pTemplate="filter"

If filter is set to true, then you can set showToggleAll to false and the filter template is displayed. The filter attribute is missing from the documentation when using the filter template (see here: https://www.primefaces.org/primeng-v14-lts/listbox), so this is either a documentation issue or a bug, if the filter attribute is not meant to be used when dealing with custom content.

Note that if showToggleAll is true (default), then the custom filter template is displayed without the need to set the filter attribute to true.

### Environment

-

### Angular version

14.0.7

### PrimeNG version

14.2.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.6.0

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
