### ISSUE TITLE
dynamic dialog module (same instances on top of each other)

### ISSUE THREAD

**Issue by shayan-ghzl** [primefaces/primeng#13646]
### Describe the bug

you can open a specific type of dynamic dialog many times on top of each other

example:
https://github.com/shayan-ghzl/angular-primeng-dynamic-dialog-test

stackblitz:
https://stackblitz.com/edit/angular-nw6ebt

### Environment

angular verison 16

### Reproducer

https://stackblitz.com/edit/angular-nw6ebt

### Angular version

16.2.4

### PrimeNG version

16.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Browser(s)

chrome

**Comment by thedavidhoffman** [comment]
This bit us in the behind. We have a scenario where we intentionally have instances on top of each other and this changed the default behavior. Thankfully I found the flag you added for "duplicate" in the DynamicDialogConfig, but I think by default the behavior should have been left alone and a flag added to disallow duplicates.

**Comment by shayan-ghzl** [comment]
@SoyDiego @thedavidhoffman do you want me to make a second PR?
i do not know if you are from primeng team or not but if you want i can create a new PR
