### ISSUE TITLE
Menu: Keyboard navigation broken in PrimeNg Diamond

### ISSUE THREAD

**Issue by steveschmitt** [primefaces/primeng#13653]
### Describe the bug

Popup menu keyboard navigation works properly in the [PrimeNg Menu documentation page](https://primeng.org/menu#popup)

However, in the [PrimeNg Diamond template](https://www.primefaces.org/diamond-ng/#/uikit/menu/personal), it does not work.  Something is interfering with the keyboard events.  We noticed this in our own Diamond-based app, but it is also apparent in the on the [Diamond samples page](https://www.primefaces.org/diamond-ng/#/uikit/menu/personal).  Click on Overlay Menu **Options** button and attempt to choose a menu item with the keyboard.

### Environment

PrimeNG Diamond template
PrimeNG 15.3.0

### Angular version

15.2.6

### PrimeNG version

15.3.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.1

### Steps to reproduce the behavior

1. Go to the [Diamond samples page](https://www.primefaces.org/diamond-ng/#/uikit/menu/personal).  
2. Scroll down to Overlay Menu sample.
3. Click on Overlay Menu **Options** button and attempt to choose a menu item with the keyboard.

### Expected behavior

Menu should be keyboard-navigable as described in [the Menu documentation](https://primeng.org/menu#accessibility)

But the keys do nothing.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
