### ISSUE TITLE
AutoComplete: Suggestions list display is broken after scroll when virtual scroll enabled

### ISSUE THREAD

**Issue by Ioana-Drimbarean** [primefaces/primeng#13655]
### Describe the bug

Dear team,

I have encountered an issue while testing the autocomplete component with virtual scroll enabled.
I think there is something wrong with the scrolling reset and the scroll container calculation. I suggest you use a more complex list of items while fixing the bug and not just a list of prefixed  "item <number>".
Please check the steps to reproduce section for more details.

### Environment

Prime NG demo component: https://primeng.org/autocomplete#virtualscroll
PrimeNG version: v16.3.1 (from your own demo page) or 16.0.2 (my locale environment version)
Angular version: 16

### Angular version

16.1.0

### PrimeNG version

16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v19.7.0

### Browser(s)

Chrome, FF

### Steps to reproduce the behavior

CASE 1: broken display of suggestion list
1) Use Prime NG demo component: https://primeng.org/autocomplete#virtualscroll
2) Search after **Item** and then scroll down through the list of suggestions
3) Add 0 at the end after scrolling => the display is broken(you barely see the suggestion within the scrolling container)
4) Add 9 instead of 9, delete input and check different combinations
=> The display is broken sometimes. It helps scrolling through the list, in order to get back to the right behaviour.
![after_scroll_6](https://github.com/primefaces/primeng/assets/109617190/caa43c96-ce89-4b29-a119-d9fcfc0a81b2)
![after_scroll_5](https://github.com/primefaces/primeng/assets/109617190/ce1eb3e6-ee30-40fb-bfd7-cb5d0611aab1)
![after_scroll_4](https://github.com/primefaces/primeng/assets/109617190/b77c7d75-f171-46cc-81b5-5dcf1e5170e0)
![after_scroll_3](https://github.com/primefaces/primeng/assets/109617190/04d22e5f-00e8-42ec-8ecd-1dcf6d237cdd)
![after_scroll_2](https://github.com/primefaces/primeng/assets/109617190/c236358b-6a57-4dcd-b8f0-3634121cd556)

CASE 2: inconsistent scroll area size.
1) Use Prime NG demo component: https://primeng.org/autocomplete#virtualscroll (Please refresh the page, or open it in a new tab)
2) Search after **Item 0** => The list of suggestions shows one item and empty space.
3) Delete 0 and then add it again => The list of suggestions shows one item and no empty space.
![item_0_first](https://github.com/primefaces/primeng/assets/109617190/65506733-d5bc-4dcd-89de-5a51425b809e)
![item_0_second_time](https://github.com/primefaces/primeng/assets/109617190/6bc9c018-089b-44b1-a37a-73c1d6654fec)

### Expected behavior

The list of suggestions should be visible to the user and the scrolling area size for the suggestion list should be consistent.(recalculated after the number of results).
Also, this workflow also should work when the showEmptyMessage option is enabled.
Please contact me if you need more input.

**Comment by andyg3** [comment]
I am facing the same issue, and the demo page is still broken.

**Comment by imohammadali** [comment]
I have the same issue, in the https://primeng.org/autocomplete we can see it's not working properly:
![image](https://github.com/primefaces/primeng/assets/107179088/3a09051d-fdda-408c-98c4-2129e974dbf7)

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
