### ISSUE TITLE
ConfirmPopup: CloseOnEscape is not working

### ISSUE THREAD

**Issue by Gykonik** [primefaces/primeng#13652]
### Describe the bug

When pressing escape on an open confirmation dialog with `closeOnEscape: true`, nothing happens.

### Environment

-

### Reproducer

https://stackblitz.com/edit/ztmvzt?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fdemo%2Fconfirm-popup-basic-demo.ts

### Angular version

16.1.0

### PrimeNG version

16.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.20.0

### Steps to reproduce the behavior

Open the confirmation dialog and try to close it using escape.

### Expected behavior

The dialog should close immediately after pressing escape.

**Comment by SoyDiego** [comment]
Hi @Gykonik, thanks for report the issue.
Tomorrow I will do the pull request solving the issue.

Regards

**Comment by SoyDiego** [comment]
Hi @Gykonik, I did a PR here solving the problem: https://github.com/primefaces/primeng/pull/13675.

Could you edit the title of your post and write `ConfirmPopup` instead of `ConfirmDialog`, please?. The correct component was `ConfirmPopup`

Now we should wait if PrimeNG Team approve it.

Thanks

**Comment by Gykonik** [comment]
Sure, thanks for your effort! :)
