### ISSUE TITLE
calendar: (inline) make keyboard focus available for dates

### ISSUE THREAD

**Issue by gvlekke** [primefaces/primeng#13656]
### Describe the feature you would like to see added

**Feature request / make it concistent**
The calendar now can have focus on dates when they are in a overlay, with the tab you can navigate to the month year and after that the date is selected. Like this example:
![non-inline-calendar](https://github.com/primefaces/primeng/assets/1651949/5420701e-641b-4d2b-b85a-97ca7ac506ec)

For the inline calendar this is not the case and its only possible to select the month and the year.
![inline-wrong](https://github.com/primefaces/primeng/assets/1651949/6fb6ded9-0502-4a29-872e-8a09c9b1c250)

It would be nice if both on the non-inline calendar and the inline calendar we can select the dates with the keyboard.

### Is your feature request related to a problem?

inconsistent of keyboard selection in calendar inline vs non-inline

### Describe the solution you'd like

We can think about making something that when the month or year is selected that we can push the arrow down key to go down from the year or the month to the dates.

I think it would be something like this: ![inline-calendar](https://github.com/primefaces/primeng/assets/1651949/8af5b831-b6cc-4a65-a43c-258b28b5a573)

### Describe alternatives you have considered

temporary focus trap could also be possible and then remove the focustrap when we push esc button, but I think that is harder for the user to understand. So I don't think this is a good alternative.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
