### ISSUE TITLE
showClear on calendar doesn't appear if showIcon is set to true

### ISSUE THREAD

**Issue by cdskill** [primefaces/primeng#13650]
### Describe the bug

The @Input() showClear input does'nt display the cross button icon if @Input()showIcon is set to true.

https://stackblitz.com/edit/bbgayt?file=src%2Fapp%2Fdemo%2Fcalendar-basic-demo.html

### Environment

Work.

### Angular version

16.2.3

### PrimeNG version

16.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.17.1

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. use p-calendar
2. set showClear and showIcon to true
3. the icon of showIcon is displayed but not the showClear button if we set a date.

### Expected behavior

The clear button should be displayed.

**Comment by ashikjs** [comment]
@cdskill I solved it Primng Theme hopefully they will merge it .

**Comment by ashikjs** [comment]
Here is PR: https://github.com/primefaces/primeng-sass-theme/pull/45

**Comment by cetincakiroglu** [comment]
Hi,

Thanks a lot for reporting the issue!
