### ISSUE TITLE
p-virtualScroller: Container now tabbable

### ISSUE THREAD

**Issue by johanneszelger** [primefaces/primeng#13668]
### Describe the bug

I have a form with a virtualscroller inside. Since updating from 16.x to 16.3.1 I noticed that the virtualscroller has now a div element (right inside the p-scroller element div) which has tabindex 0

### Environment

-

### Angular version

16.2.1

### PrimeNG version

16.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

-

### Steps to reproduce the behavior

- Have a form where the p-virtualscroller element is inside after another input. 
- Focus the input first
- now tab
- the virtualscroller now has the focus

### Expected behavior

container element should not be focusable

**Comment by ashikjs** [comment]
@johanneszelger  can you add some example to understand.

**Comment by johanneszelger** [comment]
Hi, sure.

So here in the first Screenshot you see the focus in the last element of the top row. the top row is outside of the virtual-scroller.
![bug1](https://github.com/primefaces/primeng/assets/67544309/bbbc0ee5-b80b-4ecc-b1bb-3d8eeb4f3221)

Then i press Tab, and no element seems to be focused (visually). The dropdown in the second row should be focused, but isn't.

![bug2](https://github.com/primefaces/primeng/assets/67544309/fd543ff7-b502-4d10-91b0-77ddff53a80a)

The reason is that the a container element of p-scroller. Note that the tabindex is explicitly set to "0", which seems to be new, since this was not an issue in earlier versions (16.0).

![bug3](https://github.com/primefaces/primeng/assets/67544309/bf90100d-5863-42bc-a213-fb34e3de5a69)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
