### ISSUE TITLE
Component: Table Pagination State

### ISSUE THREAD

**Issue by CarlsVier** [primefaces/primeng#13660]
### Describe the bug

When using the pagination from p-table, the pagination state after using global filter is the page is coming at NaN.
<img width="229" alt="image" src="https://github.com/primefaces/primeng/assets/144782215/24afe516-3348-45fb-9fe0-022812e45c88">

### Environment

Localhost runner

### Angular version

Angular 15.1.3

### PrimeNG version

14.2.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.19.0

### Steps to reproduce the behavior

1. On a p-table with global search enable. Do a search on global filter.
2. See on the console log the state of the pagination.

### Expected behavior

<img width="167" alt="image" src="https://github.com/primefaces/primeng/assets/144782215/76bdeaac-f533-4b7a-87c8-b6517396e448">

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
