### ISSUE TITLE
Flickering issue in Dropdown

### ISSUE THREAD

**Issue by jishnuP7** [primefaces/primeng#13667]
### Describe the bug

Primeng dropdown keep flickering on multiple click on the p-dropdown.

### Environment

Windows

https://github.com/primefaces/primeng/assets/73280575/1f364fb2-e9b4-4293-b73a-bb8af93b30ab

### Angular version

15.2.3

### PrimeNG version

15.2.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.21.3

### Browser(s)

Chrome

### Steps to reproduce the behavior

Click multiple times on the dropdown.

**Comment by ashikjs** [comment]
Can you share with any code base or reproducible path or code in  stackblitz . @jishnuP7

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
