### ISSUE TITLE
Dropdown: Add new event emitter 'onOptionClick'

### ISSUE THREAD

**Issue by Kisters-BS** [primefaces/primeng#13663]
### Describe the feature you would like to see added

I would like to have the same event emitter as for example SelectButton has:
https://primeng.org/selectbutton#api.selectbutton.emitters.onOptionClick

### Describe the solution you'd like

I would like to receive an event from onOptionClick when a option is selected. It can get triggered again from the active / already selected option. The Event cannot be sent by a disabled option.

### Describe alternatives you have considered

I have considered onChange but it only emits when the active option has been changed. The onClick event does emit when the dropdown itself or an option has been clicked and does not have information about the active option therefore also not suited for my use case.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
