### ISSUE TITLE
Calendar: Not possible to select date with keyboard because it skips over a disabled date to the next month.

### ISSUE THREAD

**Issue by tom-vism** [primefaces/primeng#13661]
### Describe the bug

In calendar popup, when navigating using arrow keys it jumps over the disabled date to the next month. It should be possible to select any date available on the current month using only keyboard. Issue happens also on older versions of primeng. Currently, we use version 13.

### Environment

Any environment

### Reproducer

https://stackblitz.com/edit/hjneq9?file=package.json

### Angular version

16.2.4

### PrimeNG version

16.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.20.0

### Steps to reproduce the behavior

1. Open calendar
2. Open September in 2023 calendar view and make sure date is focused
3. Try to select September 6, 2023 using only keyboard arrow keys

### Expected behavior

It should be possible to select any date available on the current month using only keyboard.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
