### ISSUE TITLE
ColumnFilter in row mode and type date not trigger change when value change

### ISSUE THREAD

**Issue by PierreB40** [primefaces/primeng#13672]
### Describe the bug

Using p-columnFilter in row mode and date type
Select a value in the calendar

### Environment

x

### Reproducer

https://codesandbox.io/s/primeng-table-filter-row-date-59jwcy

### Angular version

16.2.1

### PrimeNG version

16.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.17.1

### Steps to reproduce the behavior

In the reproduction link, the filter in the first column (date) is a date filter.
Selecting a new filter value does not trigger a change, nor does pressing enter. A matchMode must be chosen to trigger a change. 

### Expected behavior

A change when the value is modified or when enter is pressed, as with other filters in row mode.

**Comment by ashikjs** [comment]
@PierreB40  , but i can not see any date property in this object and you did not define any date property in globalfilter value.

**Comment by PierreB40** [comment]
This is not related to the data, but to the behavior of the filter.
I've changed the data to avoid confusion

**Comment by ashikjs** [comment]
Thanks @PierreB40 , now i got it.

**Comment by ashikjs** [comment]
@PierreB40  can you check my PR, this issue solved on this PR

**Comment by PierreB40** [comment]
Your solution corrects the action of selecting a date in the calendar
But when the date is entered using the keyboard, the event is triggered each time the keyboard is entered 😕

**Comment by ashikjs** [comment]
@PierreB40 I understand your point but it's not free text box it's a calendar, when you type any date in input box if it match with colander format then automatically it filter, event you don't need to press enter. 

you can check video to understand the behavior more details.


https://www.awesomescreenshot.com/video/20777390?key=48435726b29035f62f5d75e729b81c38

**Comment by PierreB40** [comment]
@ashikjs I know what you mean, the problem is that the calendar doesn't wait for a good format to trigger ngModelChange, so in lazy loading every keyboard entry triggers onLazyLoad

**Comment by ashikjs** [comment]
@PierreB40 here ngModelChange only tiger when calendar value change not user on type. If it was firing event on every key press then I will not provided this solution.

**Comment by jdavid82** [comment]
Hi, I looked through the release logs for releases since November 23, 2023 and I couldn't find this particular bug fix in the. Has this fix been released? And if so, in which release did it come out? Thank you.
