### ISSUE TITLE
Component: Primeng Documentation

### ISSUE THREAD

**Issue by pudrik** [primefaces/primeng#13671]
### Describe the feature you would like to see added

I think i speak for many people when i say it would be nice if you spend some time fixing your documentation of v16 as it neither complete in many places causing people to switch versions and having to navigate to the same place again instead of just going to the same page but a different version.

One example of missing data are models they arent defined in v16

**Comment by SoyDiego** [comment]
Thanks. I agree the docs should be improve it.
Maybe you can write here too https://github.com/orgs/primefaces/discussions to discuss about that with Primetek Team

**Comment by pudrik** [comment]
> Thanks. I agree the docs should be improve it. Maybe you can write here too https://github.com/orgs/primefaces/discussions to discuss about that with Primetek Team

@SoyDiego feel free to add things that are missing. https://github.com/orgs/primefaces/discussions/59

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
