### ISSUE TITLE
DynamicDialog - remove entryComponents from docs

### ISSUE THREAD

**Issue by tomer953** [primefaces/primeng#13679]
### Describe the bug

According to the current documentation for [Dynamic Dialogs](https://primeng.org/dynamicdialog), it is stated that entryComponents are required for dynamic dialogs.

`Since the dynamically loaded content is not defined at build time, a configuration is necessary using the entryComponents of your parent module`

 However, with Angular 9 and above, using the Ivy rendering engine, entryComponents are generally no longer necessary. This could lead to confusion for developers using newer versions of Angular

### Environment

.

### Angular version

16.2.0

### PrimeNG version

16.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Expected behavior

it should mention that entryComponents are generally not required when using Angular 9 and above with the Ivy rendering engine. This would help developers avoid unnecessary configuration and reduce confusion.

**Comment by SoyDiego** [comment]
Thanks for report.
PRs are welcome! :)

**Comment by tomer953** [comment]
NP. 
https://github.com/primefaces/primeng/pull/13682

**Comment by SoyDiego** [comment]
> NP. #13682

Thanks
