### ISSUE TITLE
Datatable single selection inconsistency

### ISSUE THREAD

**Issue by kcsahoo** [primefaces/primeng#1367]
In touch devices, this works fine. First touch selects the row, the next touch deselects it. Effectively toggle.
This is the right functionality.
In desktop or laptop devices, single click is equivalent to touch on touch devices.
But first click selects the row, next click does not deselect.
This is not the right behaviour and is also contrary to documentation.
Documentation is correct but implementation does not match it.
This is a bug and please resolve it in RTM.

**Comment by ctrl-brk** [comment]
There's no row deselect in single selection mode on desktop devices. In multiselect you can use ctrl-click. That's the default system behavior.  Works exactly as it should.

**Comment by cagataycivici** [comment]
Works as intended, design based upon filesystems.
