### ISSUE TITLE
Image: Add srcset attribute

### ISSUE THREAD

**Issue by drilko** [primefaces/primeng#13683]
### Describe the feature you would like to see added

On the documentation site it says:" Image is used as the native img element and supports all properties that the native element has.", but it is missing **srcset** attribute.
It would be beneficial to support it as well.

### Is your feature request related to a problem?
Nope

### Describe the solution you'd like

Add srcset and perhaps previewImageSrcset inputs to the component.

### Describe alternatives you have considered

I could probably "hack it" in some way by using *ngIf or media queries but it would be better to support srcset attribute as you already use native img element.

**Comment by tomer953** [comment]
Just a quick note, if we support `srcset` attribute we should also support `sizes`

> Note: If the [srcset](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#srcset) attribute uses width descriptors, the sizes attribute must also be present, or the srcset itself will be ignored.

**Comment by tomer953** [comment]
The implementation however should not be too complex:
```

@Input() srcset: string | undefined;
@Input() sizes: string | undefined;
```

`<img [attr.src]="src" [attr.srcset]="srcset" [attr.sizes]="sizes" … />`

**Comment by SoyDiego** [comment]
I have a PR.
I will send it tomorrow :)

**Comment by SoyDiego** [comment]
PR submitted here https://github.com/primefaces/primeng/pull/13691.

Thanks!
