### ISSUE TITLE
SlideMenu - Cannot Toggle Popup When Hovered MenuItem Without Childs 

### ISSUE THREAD

**Issue by kkamay** [primefaces/primeng#13694]
### Describe the bug

Hello All,

As the title indicates, toggling functionality gets disrupted when a MenuItem without child items is hovered on a SlideMenu popup. This functionality works fine when the popup items are not hovered or the last item hovered is a MenuItem with child items. I have tried it by altering the StackBlitz that you have provided in [PrimeNG website for SlideMenu popup](https://primeng.org/slidemenu#popup).

Here is a video to show it to you better:
https://streamable.com/y4cbjw

Thank you.

### Environment

PrimeNG Version: 16.3.1

### Reproducer

https://streamable.com/y4cbjw

### Angular version

16.2.0

### PrimeNG version

16.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.20.0

### Steps to reproduce the behavior

1. Open SlideMenu popup.
2. Hover on a MenuItem without child items.
3. Click elsewhere and see that the menu is not closed.

### Expected behavior

Toggling functionality should stay the same for all elements (MenuItems with or without childs).

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
