### ISSUE TITLE
Component: dialog

### ISSUE THREAD

**Issue by amirheydari9** [primefaces/primeng#13693]
### Describe the feature you would like to see added

Add a feature that can be used to set default settings for the config dialog, similar to what Angular Material does for its dialog

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
