### ISSUE TITLE
Themes: bootstrap4-dark-blue - Different CSS values

### ISSUE THREAD

**Issue by psarno** [primefaces/primeng#13696]
### Describe the bug

In 16.3.1, I noticed that the layout in a `p-dialog` component's content area was not correct, but this was only occuring when using the `bootstrap4-dark-blue` theme.

In this theme, the content padding is defined as:

```
.p-dialog .p-dialog-content {
   padding: 0 1.5rem 2rem 1.5rem;
}
```

Other themes, such as saga-blue, have this padding defined as:

```
.p-dialog .p-dialog-content {
   padding:1rem;
}
```

The 1 rem padding looks correct, in `bootstrap4-dark-blue` it is setting a 0 top padding, forcing the text of the content area up against the header.

It seems like this should match.

### Environment

PrimeNG 16.3.1

### Angular version

16.2.2

### PrimeNG version

16.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Expected behavior

The padding should match across themes.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
