### ISSUE TITLE
TreeSelect popup closes when unchecking nodes

### ISSUE THREAD

**Issue by joel-matthias** [primefaces/primeng#13698]
### Describe the bug

When selectionMode is set to 'checkbox', unchecking a checked tree node causes the popup to close prematurely

### Environment

Issue can be reproduced in PrimeNG demo app https://primeng.org/treeselect#checkbox

### Angular version

16

### PrimeNG version

16.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.20.1

### Browser(s)

Chrome, Firefox

### Steps to reproduce the behavior

Open PrimeNG demo page at https://primeng.org/treeselect#checkbox
Open select
Check an item
Uncheck that item
Result: Popup tree closes
Expected: Popup tree should stay open

### Expected behavior

Popup tree should stay open

**Comment by Romain-Luengo** [comment]
Same behavior here

**Comment by fkrajcar-cirtuo** [comment]
+1

**Comment by fkrajcar-cirtuo** [comment]
There is a workaround for this bug:
```
<p-treeSelect #treeselect class="w-full md:w-20rem" containerStyleClass="w-full" [(ngModel)]="selectedNodes" [options]="nodes" display="chip" [metaKeySelection]="false" selectionMode="checkbox" placeholder="Select Item" (onHide)="onHide($event)"></p-treeSelect>
```

Add `[metaKeySelection]="false"` and `(onHide)="onHide($event)"` on `<p-treeSelect>`

In your .ts:
```
  onHide(event) {
    if (event === undefined) {
      this.treeselect.overlayVisible = true;
    }
  }
  ```
  
Credit goes to [Berkin Sansal](https://stackoverflow.com/users/2549567/berkin-sansal) - SO thread - https://stackoverflow.com/questions/76976298/how-to-prevent-overlay-of-treeselect-checkbox-auto-collapse-when-click-child-nod

**Comment by GitHubStan** [comment]
> onHide(event) {
>     if (event === undefined) {
>       this.treeselect.overlayVisible = true;
>     }
>   }

Thanks for the fix, @fkrajcar-cirtuo. However, it's a partial fix. With this fix, they can't close the treeselect by clicking on the select box. Since event is undefined, we can't tell what they clicked on to conditionally hide the overlay.

**Comment by GitHubStan** [comment]
Note that this only happens when you click on the checkbox. If you click on the label for the checkbox, things work as expected.

**Comment by fkrajcar-cirtuo** [comment]
> > onHide(event) {
> > if (event === undefined) {
> > this.treeselect.overlayVisible = true;
> > }
> > }
> 
> Thanks for the fix, @fkrajcar-cirtuo. However, it's a partial fix. With this fix, they can't close the treeselect by clicking on the select box. Since event is undefined, we can't tell what they clicked on to conditionally hide the overlay.

Yes, that is correct, but that was not a problem in our case since clicking outside the panel (and label itself) and ESC closes it as expected.

**Comment by GitHubStan** [comment]
Here's my monkey patch of onClick() that allows med to close the overlay by clicking on the dropdown box.

```
  @ViewChild(TreeSelect)
  treeselect: TreeSelect;

  ngAfterViewInit(): void {
    this.treeselect.onClick = this.monkeyPatchTreeSelectOnClick.bind(this);
  }

private monkeyPatchTreeSelectOnClick(event: any) {
  if (this.treeselect.disabled) {
    return;
  }

  if (
    !this.treeselect.overlayViewChild?.el?.nativeElement?.contains(event.target) &&
    !DomHandler.hasClass(event.target, 'p-treeselect-close') &&
    this.indicatesDropDownBox(event) // This is the line added for the fix
  ) {
    if (this.treeselect.overlayVisible) {
      this.treeselect.hide();
    } else {
      this.treeselect.show();
    }

    this.treeselect.focusInput?.nativeElement.focus();
  }
}

private indicatesDropDownBox(event: any) {
  const classesIndicatingDropdownWasClicked = [
    'p-treeselect-label',
    'p-treeselect-label-container',
    'p-treeselect-trigger',
    'p-treeselect-trigger-icon',
  ];
  const indicatesDropDownBox = classesIndicatingDropdownWasClicked.some((c) => DomHandler.hasClass(event.target, c));
  return indicatesDropDownBox;
}
```

**Comment by zfloyd** [comment]
This update has caused the TreeSelect to not close when in "single" mode after making a selection.  I'm not sure why this change was made, but its almost assuredly the reason for the break.

```
if (this.selectionMode === 'single') {
            **// this.hide();**
            this.focusInput?.nativeElement.focus();
        }
```

**Comment by cetincakiroglu** [comment]
> @cetincakiroglu , this update has caused the TreeSelect to not close when in "single" mode after making a selection. I'm not sure why this change was made, but its almost assuredly the reason for the break.
> 
> ```
> if (this.selectionMode === 'single') {
>             // this.hide();
>             this.focusInput?.nativeElement.focus();
>         }
> ```


Hi,

Thanks for letting us know, we'll check it.

**Comment by zfloyd** [comment]
@cetincakiroglu just compare the "Basic" example of Tree Select in PrimeNG 16 with the latest one in the demo site:
https://www.primefaces.org/primeng-v16-lts/treeselect#basic
https://primeng.org/treeselect#basic

Selecting an item is supposed to close the control.

**Comment by mrkubad** [comment]
Hi,

As @zfloyd said this fix has broken behavior that caused to close overlay in a `single` selection mode.

#### control behavior before fix
![before fix](https://github.com/primefaces/primeng/assets/48626025/01ec8c24-6fef-4e6d-afa3-ac70d81a3be3)

#### control behavior after fix
![after fix](https://github.com/primefaces/primeng/assets/48626025/960818b2-e50f-4dc0-ad52-d77b1a8625a5)

Is someone working on fixing this issue?
