### ISSUE TITLE
Calendar: Disabled Dates Not Actually Disabled in Range Selection

### ISSUE THREAD

**Issue by Ryan-h1** [primefaces/primeng#13697]
### Describe the bug

Disabled dates are not fully disabled in range mode. When dates are disabled and the selectionMode is 'single', then disabled dates can not be selected, but when it's set to range, disabled dates can be selected so long as the start and end date are enabled.

### Environment

Compiled and served on Mac OS, StackBlitz, Windows. Tested on all modern browsers.

### Angular version

16.2.5

### PrimeNG version

16.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.10.0

### Steps to reproduce the behavior

1. Go to [https://stackblitz.com/github/Ryan-h1/primeng-calendar-issue-demo?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/github/Ryan-h1/primeng-calendar-issue-demo?file=src%2Fapp%2Fapp.component.ts)
2. Open the calendar
3. Find a date that is disabled
4. Select the day before and the day after as the range
5. Observe that you have selected the disabled date, despite it being disabled

### Expected behavior

Disabled dates should be prevented from being selected regardless of whether they're selected within a range or as singular dates.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
