### ISSUE TITLE
Multiselect: VirtualScroll viewport doesn't resize correctly when searching

### ISSUE THREAD

**Issue by LinusSee** [primefaces/primeng#13692]
### Describe the bug

When scrolling in a multiselect with virtual scrolling and then searching for an item, the viewport size becomes too small to display any items.

### Environment

Reproducable using PrimeNg Docs https://primeng.org/multiselect#virtualscroll.
I checked the docs for v15 and v16 and was able to reproduce the bug in both.

### Angular version

16

### PrimeNG version

16.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16

### Browser(s)

Firefox 117, Chrome 116, Edge 117

### Steps to reproduce the behavior

To recreate you can use the virtual scroll example from the docs https://primeng.org/multiselect#virtualscroll.

1. Scroll down a few items e.g. "Item 50"
![1_MultiselectVirtualScrollBug](https://github.com/primefaces/primeng/assets/23562543/8a4330eb-4a88-4694-a656-0ee71b44788b)

2. Search for a specific item (to reduce the number of items displayed to 1)
![2_MultiselectVirtualScrollBug](https://github.com/primefaces/primeng/assets/23562543/8a624106-e94f-4f6a-8e2c-1b8a2c108f27)

3. Viewport size is too small to display any items
![3_MultiselectVirtualScrollBug](https://github.com/primefaces/primeng/assets/23562543/0784085a-9220-409e-ba66-1fc1db8931ae)

### Expected behavior

The viewport should have a size necessary to display found items.

**Comment by admt1** [comment]
Same issue here, i need to use virtualScroll, but it's not resizing

**Comment by Romain-Luengo** [comment]
Same here

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
