### ISSUE TITLE
api/treenode.ts Fails Evaluating

### ISSUE THREAD

**Issue by pratikthecook** [primefaces/primeng#137]
```
interface TreeNode {
    label?: string;
    data?: any;
    icon?: any;
    expandedIcon?: any;
    collapsedIcon?: any;
    children?: TreeNode[];
    leaf?: boolean;
}
```
While trying to load a tree of the basic item `<p-tree [value]="files"></p-tree>`
 
following is the console output

**Uncaught SyntaxError: Unexpected identifier
	Evaluating http://localhost:63342/sourcePrimeNg/components/api/treenode.ts**

I fixed this by simply replacing all references of the interface TreeNode with any;

**Comment by cagataycivici** [comment]
What is your version?

**Comment by cagataycivici** [comment]
Please try with 0.8.2 as this looks same as

https://github.com/primefaces/primeng/issues/127

**Comment by pratikthecook** [comment]
Yes ive checked now the issue is resolved, work fine :+1:  thanks..
