### ISSUE TITLE
pButton: Cannot set property className of [object SVGElement] which has only a getter

### ISSUE THREAD

**Issue by silviagreen** [primefaces/primeng#13706]
### Describe the bug

When changing the value of [icon] attribute of p-button like this:
* old value: class name of a custom icon of font-awesome
* new value: name of a standard icon

In browser console appears the following error:

ERROR TypeError: Cannot set property className of [object SVGElement] which has only a getter
    at ButtonDirective.updateIcon (primeng-button.mjs:129:38)
    at set icon [as icon] (primeng-button.mjs:45:18)

### Environment

Angular web application, using font-awesome icons. Some icons are custom.

### Angular version

15.2.1

### PrimeNG version

15.3.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.14.2

### Browser(s)

Chrome 116.0.5845.188, Firefox 116.0.1

### Steps to reproduce the behavior

1) create a custom icon
![image](https://github.com/primefaces/primeng/assets/2613299/bbdbf9ae-3175-4d70-b577-6cfcfa00620d)

2) use this icon in a p-button

3) update the icon attribute with another value.

Here is the problem in the button.ts file:

![image](https://github.com/primefaces/primeng/assets/2613299/dc47d1ac-53ea-45e6-80e1-ac60d09cd06b)

You are expecting the iconElement to have the class attribute, but in case of custom element, the iconElement is an <svg>

To reproduce issue: [Stackblitz](https://stackblitz.com/edit/angular-ivy-v3rgzz?file=src%2Fapp%2Fapp.component.html)

**Comment by volvachev** [comment]
Hi, can you add stackblitz for reproduce

**Comment by silviagreen** [comment]
@volvachev I have added the stackblitz

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
