### ISSUE TITLE
AngularJS modules can't be resolved

### ISSUE THREAD

**Issue by sudheerj** [primefaces/primeng#1371]
When I try to build and run(npm install,npm start) the PrimeNG project typescript files are not able to resolve angular,rxjs,core-js modules.But If I try to add all these modules locally inside node_modules the webpage is opened without finding primeng.min.css file.I didn't find this kind of issues with any other AngularJS projects.

![image](https://cloud.githubusercontent.com/assets/3127317/20459788/8595f468-af09-11e6-8e03-fcb6fb3f6add.png)

Environment
OS:Windows
nodejs:6.9.1
npm:3.10.8

**Comment by cagataycivici** [comment]
Please see;

https://github.com/primefaces/primeng/wiki/Building-From-Source

**Comment by sudheerj** [comment]
Thanks Cagatay. Got the point.It is working fine now.
