### ISSUE TITLE
dismissableMask is not working on ConfirmationPopup

### ISSUE THREAD

**Issue by MussaratAziz** [primefaces/primeng#13714]
### Describe the bug

dismissableMask is not working on ConfirmationPopup i want to set to false.

### Environment

.

### Angular version

16

### PrimeNG version

16.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.1

### Steps to reproduce the behavior

.

### Expected behavior

dismissableMask  should work by setting it to true or false

**Comment by SoyDiego** [comment]
Hi @MussaratAziz , I have checked the problem and you are right.
I did a PR solving the problem. You can check it here: https://github.com/primefaces/primeng/pull/13721
Now we should wait PrimeNG Team approve it if they think the solution is OK for them.

Regards

**Comment by MussaratAziz** [comment]
@SoyDiego cheers
