### ISSUE TITLE
New @layer implementation 

### ISSUE THREAD

**Issue by tugcekucukoglu** [primefaces/primeng#13737]

**Comment by andyg3** [comment]
This change has broken my jest tests. Do I need a new shim or something?
I see:
```
    Error: Could not parse CSS stylesheet
        at exports.createStylesheet 
```

and later...
`detail: '@layer primeng{.p-dialog-mask{position:fixed;top:0;left:0;width:100%;height:100%;display:flex;justify-content:center;align-items:center;pointer-events:... etc.`

**Comment by Adrii77** [comment]
Same issue here

**Comment by JLa2r** [comment]
Also having the same issue with unit tests

**Comment by danymarques** [comment]
Same here.. Any idea to workaround this?

**Comment by Adrii77** [comment]
Didn't find... I'm stuck on PrimeNG 16.3 because of that. All of my snapshots tests are broken witl 16.4.

**Comment by Adrii77** [comment]
I resolve the issue : I found [this issue from primevue](https://github.com/primefaces/primevue/issues/4512). It's an issue from jsdom and [this workaround resolve it](https://github.com/jsdom/jsdom/issues/2177#issuecomment-1724971596)

**Comment by Phil-DS** [comment]
This has been breaking my tests, and messing up the testing process. Until its properly fixed, I might have to revert to a primeng version prior to this.

The stubbing/mocking of the console.error function is still breaking the test workflow, as it's not properly going through the tests themselves.

**Comment by bendehghan** [comment]
is this being tracked with another bug? I'm also seeing this error and I'm confused why the bug is closed.

**Comment by angelo-v** [comment]
https://github.com/primefaces/primeng/issues/14085
