### ISSUE TITLE
LazyLoad Support for p-dropdown with filter

### ISSUE THREAD

**Issue by giovannistiwes** [primefaces/primeng#13738]
### Describe the feature you would like to see added

Support lazy filtering, because when the amount of data is large, searching for everything once is complicated.

### Describe the solution you'd like

You already have ports on the internet with this solution: 

https://github.com/yelhouti/primeng/blob/all-fixes/src/app/components/dropdown/dropdown.ts

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
