### ISSUE TITLE
p-galleria: Should have `appendTo` when `fullScreen` is true

### ISSUE THREAD

**Issue by ruskovweb** [primefaces/primeng#13739]
### Describe the feature you would like to see added

I want to be able to append the gallery to the body element, or some other outer element. Currently I have an issue with the stacking context.

### Is your feature request related to a problem?

When we define the gallery as an inner component it can't be visualized on full screen on top of all other components.

### Describe the solution you'd like

`appendTo` field would solve the issue

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).

**Comment by mcrtricolor** [comment]
I'm having the same issue.
