### ISSUE TITLE
Sidebar: custom or predefined close button position

### ISSUE THREAD

**Issue by akhalaiav** [primefaces/primeng#13741]
### Describe the feature you would like to see added

In existing functionality, we can only show or hide the close button.

Documentation https://primeng.org/sidebar#api.sidebar .

show: 
<img width="1342" alt="Снимок экрана 2023-09-25 в 17 33 37" src="https://github.com/primefaces/primeng/assets/38914142/6d099c6c-0a55-4668-a512-8a6d589fb86b">

hide:
<img width="1342" alt="Снимок экрана 2023-09-25 в 17 33 22" src="https://github.com/primefaces/primeng/assets/38914142/e0812109-ad39-486f-a726-fda7af25ba0d">

but in my case, I would like to have the custom close button outside of the sidebar.

like :
<img width="1342" alt="Снимок экрана 2023-09-25 в 17 33 22 — копия" src="https://github.com/primefaces/primeng/assets/38914142/bfdb43e9-9a4d-43cb-88f2-f81bba7a4738">

or 
<img width="1342" alt="Снимок экрана 2023-09-26 в 09 44 13" src="https://github.com/primefaces/primeng/assets/38914142/e151bb57-f39c-41ed-8d4a-bb8b3fc2bc25">

Is it possible to implement this functionality?

### Describe the solution you'd like

Will be better when we have something like that:

```
<p-sidebar closeButtonPosition="outside">
    ...
</p-sidebar>
```

### Describe alternatives you have considered

We can hide the close button and create some manual close button with styles, but I think it is not a good idea.

### Additional context

Current:
PrimeNg Version - 16.3.1
Node 18

Environment
Latest Angular and Primeng version

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
