### ISSUE TITLE
After updating from v16.3.1 to v16.4.0 every thing broke

### ISSUE THREAD

**Issue by MussaratAziz** [primefaces/primeng#13755]
### Describe the bug

After updating from 16.3.1 to 16.4.0 every component coming up error like this 
  The module 'primeng/toast' could not be found.

152         ToastModule,
            ~~~~~~~~~~~

  node_modules/primeng/toast/toast.d.ts:154:1
    154 export declare class ToastModule {
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    155     static ɵfac: i0.ɵɵFactoryDeclaration<ToastModule, never>;
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ...
    157     static ɵinj: i0.ɵɵInjectorDeclaration<ToastModule>;
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    158 }
        ~
    The class is declared here.

or many more i cant paste eveything here   some of the error saying cant find modules such as pickList etc.

### Environment

Angular 16

### Reproducer

_No response_

### Angular version

16

### PrimeNG version

16.4.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.1

### Browser(s)

chrome

### Steps to reproduce the behavior

_No response_

### Expected behavior

_No response_

**Comment by cetincakiroglu** [comment]
If everything is broken, how come the Stackblitz demos still work? Could you please share a stackblitz example ademonstrating the issue?

**Comment by MussaratAziz** [comment]
> If everything is broken, how come the Stackblitz demos still work? Could you please share a stackblitz example demonstrating the issue?

@cetincakiroglu my responsibility was letting you guys know rest is up to you. Stackblitz examples mostly isnt complex and not used in conjunction with other controls etc.

**Comment by cetincakiroglu** [comment]
Please create a reproducer on Stackblitz so we can investigate the issue

**Comment by MussaratAziz** [comment]
> Please create a reproducer on Stackblitz so we can investigate the issue

will try to. Thanks

**Comment by SoyDiego** [comment]
I don't know if is good idea but someone has created a new post in Discussions about some issues or bugs.
Maybe we can replicate all in one place or is better in different posts?
This is the post: https://github.com/orgs/primefaces/discussions/130

Thanks

**Comment by MussaratAziz** [comment]
tried again to update angular project from 16.3.1 to 16.5.0  and i am using bootstrap4-dark-blue/theme.css all the styles and button colors were working in 16.3.1 after update to 16.5.0 now all styling disappear. Any idea why its happening? thanks @SoyDiego
