### ISSUE TITLE
I have a Parent Tree and a Children Tree and As I Can set headers for Parent Tree I need to set headers for children tree is there a possible way to do so? A sample of what i want is show as below using TreeTable

### ISSUE THREAD

**Issue by palaksethi24** [primefaces/primeng#13762]
### Describe the feature you would like to see added
**P-tree table**
I have a Parent Tree and a Children Tree and As I Can set headers for Parent Tree I need to set headers for children tree is there a possible way to do so? A sample of what i want is show as below using TreeTable
![desk](https://github.com/primefaces/primeng/assets/130535064/06adca2f-e6db-4099-a69f-22c08f7e6ff7)

Typescript Code :- 
this.reportService.getOverheadAuditReport(this.selectedScenario || "").subscribe(data => {
            this.reportData = data.map((row: IOverheadAudit) => mapFlatDataForTreeTable(row))
			});
			
			mapTreeDataForTreeTable(row: any, isLeaf: boolean): TreeNode {
        return {
            data: row,
            leaf: isLeaf
        }
    }
	
	HTML CODE :- 
	 <p-treeTable [value]="reportData" [paginator]="true" [paginatorPosition]="'both'" 
                             [rows]="50" [rowsPerPageOptions]="rowOptions" **[columns]="selectedReportCols"**
                             [scrollable]="true" scrollHeight="400px" [resizableColumns]="true" [loading]="loading"
                             (onNodeExpand)="onNodeExpand($event)" 
                             columnResizeMode="expand" [reorderableColumns]="true" styleClass="table-bordered" #treeTable>
							 
							 
							    <ng-template pTemplate="header" let-columns>
                        <tr style="height: 55px;">
                            <th *ngFor="let col of columns" [ttSortableColumn]="col.field" ttResizableColumn ttReorderableColumn>
                                {{col.header}}
                                <p-treeTableSortIcon [field]="col.field"></p-treeTableSortIcon>
                            </th>
                        </tr>
						
						<ng-template pTemplate="body" let-rowNode let-rowData="rowData" let-columns="columns">
                        <tr style="height: 30px;">
                            <td *ngFor="let col of columns; let i = index" class="ca-overFlowHidden" title="{{rowData[col.field]}}">

                                <div *ngIf="!col.pipeCurrency && !col.pipeNumber && !col.pipeDollarOnly && !col.pipePercent && !col.pipeNumberOnly" [ngClass]="{'text-right':col.total,
                                                                        'text-left':!col.total}">
                                    <p-treeTableToggler [rowNode]="rowNode"  *ngIf="i == 0" ></p-treeTableToggler>
                                    {{rowData[col.field]}}
                                </div>
								</td>
								</tr>
								</ng-template>
                    </ng-template>
							 
							 </p-treeTable>

**Comment by adri95cadiz** [comment]
I think you can use rowExpand feature of standard table component to achieve this. 
https://primeng.org/table#row-expand

**Comment by SoyDiego** [comment]
> ### Describe the feature you would like to see added
> 
> **P-tree table** I have a Parent Tree and a Children Tree and As I Can set headers for Parent Tree I need to set headers for children tree is there a possible way to do so? A sample of what i want is show as below using TreeTable ![desk](https://user-images.githubusercontent.com/130535064/271005413-06adca2f-e6db-4099-a69f-22c08f7e6ff7.png)
> 
> Typescript Code :- this.reportService.getOverheadAuditReport(this.selectedScenario || "").subscribe(data => { this.reportData = data.map((row: IOverheadAudit) => mapFlatDataForTreeTable(row)) });
> 
> ```
> 		mapTreeDataForTreeTable(row: any, isLeaf: boolean): TreeNode {
>     return {
>         data: row,
>         leaf: isLeaf
>     }
> }
> 
> HTML CODE :- 
>  <p-treeTable [value]="reportData" [paginator]="true" [paginatorPosition]="'both'" 
>                          [rows]="50" [rowsPerPageOptions]="rowOptions" **[columns]="selectedReportCols"**
>                          [scrollable]="true" scrollHeight="400px" [resizableColumns]="true" [loading]="loading"
>                          (onNodeExpand)="onNodeExpand($event)" 
>                          columnResizeMode="expand" [reorderableColumns]="true" styleClass="table-bordered" #treeTable>
> 						 
> 						 
> 						    <ng-template pTemplate="header" let-columns>
>                     <tr style="height: 55px;">
>                         <th *ngFor="let col of columns" [ttSortableColumn]="col.field" ttResizableColumn ttReorderableColumn>
>                             {{col.header}}
>                             <p-treeTableSortIcon [field]="col.field"></p-treeTableSortIcon>
>                         </th>
>                     </tr>
> 					
> 					<ng-template pTemplate="body" let-rowNode let-rowData="rowData" let-columns="columns">
>                     <tr style="height: 30px;">
>                         <td *ngFor="let col of columns; let i = index" class="ca-overFlowHidden" title="{{rowData[col.field]}}">
> 
>                             <div *ngIf="!col.pipeCurrency && !col.pipeNumber && !col.pipeDollarOnly && !col.pipePercent && !col.pipeNumberOnly" [ngClass]="{'text-right':col.total,
>                                                                     'text-left':!col.total}">
>                                 <p-treeTableToggler [rowNode]="rowNode"  *ngIf="i == 0" ></p-treeTableToggler>
>                                 {{rowData[col.field]}}
>                             </div>
> 							</td>
> 							</tr>
> 							</ng-template>
>                 </ng-template>
> 						 
> 						 </p-treeTable>
> ```
> 
> ### Is your feature request related to a problem?
> 
> _No response_
> ### Describe the solution you'd like
> 
> _No response_
> ### Describe alternatives you have considered
> 
> _No response_
> ### Additional context
> 
> _No response_

Maybe this type of questions you can do it in the Discussions Forums: 
https://github.com/orgs/primefaces/discussions/categories/primeng

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
