### ISSUE TITLE
p-chips: premature blur when removing chips

### ISSUE THREAD

**Issue by aerollen** [primefaces/primeng#13777]
### Describe the bug

The blur event seems to be fired prematurely when removing. Instead of a single blur event firing for removing multiple chips it fires multiple times.  This behavior is unexpected as the `p-chip` is apart of the `p-chips` component, compare this with a multiselect dropdown which only fires blur once the user has clicked away from the component.   

It looks like maybe focus is being lost on the `p-chips` item when clicking on the actual chip itself?  The component has a [addOnBlur](https://primeng.org/chips#api.chips.props.addOnBlur) property, maybe a similar property is needed for deleting?

### Environment

Windows 10 Enterprise version 10.0.19045 Build 19045

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-cxbsip?embed=1&file=src%2Fmain.ts

### Angular version

15.1.6

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Browser(s)

Chrome 114.0.5735.110

### Steps to reproduce the behavior

In the stackblitz it displays a `p-chips` as well as the values bound to the property `values1`.

1. Click the close _x_ on one of the chips, doesn't matter which one.
2. Observe that the chip has been removed but the values of `values1` has not been updated as no `blur` has fired.
3. Click the close _x_ on one of the chips, doesn't matter which one.
4. Observe that `values1` has changed, this is unexpected behavior.
5. Click the close _x_ on the final chip
6. Observe that `values1` has changed again, this is unexpected behavior.
7. Click anywhere else on the page to force a `blur`
8. Observe that `values1` has changed again and is finally empty

### Expected behavior

In the stackblitz it displays a `p-chips` as well as the values bound to the property `values1`.

1. Click the close _x_ on one of the chips, doesn't matter which one.
2. Observe that the chip has been removed but the values of `values1` has not been updated as no `blur` has fired.
3. Click the close _x_ on one of the chips, doesn't matter which one.
2. Observe that the chip has been removed but the values of `values1` has not been updated as no `blur` has fired.
5. Click the close _x_ on the final chip
2. Observe that the chip has been removed but the values of `values1` has not been updated as no `blur` has fired.
7. Click anywhere else on the page to force a `blur`
8. Observe that `values1` has changed again and is finally empty, this is the expected behavior.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
