### ISSUE TITLE
ContextMenu: escape: false with SVG is not working

### ISSUE THREAD

**Issue by benjamindobravec** [primefaces/primeng#13770]
### Describe the bug

I'm trying to add SVG icon to ContextMenu and icon is not showing.

MenuItem with SVG icon:
`{  label: '<span class="icon p-menuitem-icon"><svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 -960 960 960" width="24"><path d="M480.091-336.924q67.985 0 115.485-47.59 47.5-47.591 47.5-115.577 0-67.985-47.59-115.485-47.591-47.5-115.577-47.5-67.985 0-115.485 47.59-47.5 47.591-47.5 115.577 0 67.985 47.59 115.485 47.591 47.5 115.577 47.5ZM480-392q-45 0-76.5-31.5T372-500q0-45 31.5-76.5T480-608q45 0 76.5 31.5T588-500q0 45-31.5 76.5T480-392Zm.055 171.999q-137.977 0-251.439-76.115Q115.155-372.231 61.54-500q53.615-127.769 167.022-203.884 113.406-76.115 251.383-76.115t251.439 76.115Q844.845-627.769 898.46-500q-53.615 127.769-167.022 203.884-113.406 76.115-251.383 76.115Z"></path></svg></span><h1>File</h1>', escape: false, ... } `

This MenuItem is working only on Menu component and not on ContextMenu component.

### Environment

Angular: 16.2.7
PrimeNg: 16.4.1

### Angular version

16.2.7

### PrimeNG version

16.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.17.1

### Browser(s)

Chrome 117

**Comment by eXpertise7** [comment]
@benjamindobravec not related to this issue, but just a question, on PrimeNG 16.4.1 does p-contextMenu component gets destroyed (when opened) when you route to other page (component)?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
