### ISSUE TITLE
Need an update of the samples of the Tree component

### ISSUE THREAD

**Issue by sebastienchevriaupro** [primefaces/primeng#13775]
### Describe the bug

As it is written in the API doc the type of the selection input should be any
The code samples linked to the Selection, Mulitple and Checkbox sections do not mention an any type parameter but TreeNode and TreeNode[]
In my project (angular 16.2.6 + primeng 16.4.0) it doesn't compile with a Type mismatch error

### Environment

angular 16.2.6 + primeng 16.4.0

### Angular version

16.2.6

### PrimeNG version

16.4.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

?

**Comment by ashikjs** [comment]
@sebastienchevriaupro can you give us any screenshot or code base for reproduce this case.

**Comment by sebastienchevriaupro** [comment]
![image](https://github.com/primefaces/primeng/assets/94359688/fea4a6b9-7417-4e1d-b3a6-396d34922921)

**Comment by sebastienchevriaupro** [comment]
The difference with your samples seems to the be in tsconfig.json :
https://stackblitz.com/edit/t6vruk?file=tsconfig.json

**Comment by sebastienchevriaupro** [comment]
Perhaps something with the "strict" options

**Comment by mklinke** [comment]
We still have the same issue with 17.4.0. We found that this setting in tsconfig.json shows the issue when enabled:
```json
{
  "angularCompilerOptions": {
    "strictTemplates": true
  },
  ...
}
```

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
