### ISSUE TITLE
Editor: Dark themes are broken

### ISSUE THREAD

**Issue by SoyDiego** [primefaces/primeng#13786]
### Describe the bug

![image](https://github.com/primefaces/primeng/assets/19764334/29705201-7178-4138-a8f8-ed5e655fdfae)

### Environment

-

### Angular version

Last version

### PrimeNG version

Last version

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.5.1

### Steps to reproduce the behavior

1. Go to https://primeng.org/editor
2. Change to a theme dark mode
3. Try to open options in editor

### Expected behavior

Show the correct color.

**Comment by eXpertise7** [comment]
I wonder did someone even test these changes on Angular 16 in the PrimeNG team. I love PrimeNG, it's by far best angular UI library, but work done in last months with accessibility is unacceptable.

@SoyDiego you're a PrimeNG freak, could you help me with one thing please? Can you try testing ContextMenu p-contextMenu component on PrimeNG 16.3.1 or PrimeNG 16.4.0: **try routing to another page on clicking on one ContextMenu item** - it does NOT work properly to me. ContextMenu is not removed from the DOM after we route to another page in the Angular app.

**Comment by SoyDiego** [comment]
> I wonder did someone even test these changes on Angular 16 in the PrimeNG team. I love PrimeNG, it's by far best angular UI library, but work done in last months with accessibility is unacceptable.
> 
> @SoyDiego you're a PrimeNG freak, could you help me with one thing please? Can you try testing ContextMenu p-contextMenu component on PrimeNG 16.3.1 or PrimeNG 16.4.0: **try routing to another page on clicking on one ContextMenu item** - it does NOT work properly to me. ContextMenu is not removed from the DOM after we route to another page in the Angular app.

Please create a issue or write your problem here https://github.com/orgs/primefaces/discussions/categories/primeng adding stackblitz example.

**Comment by eXpertise7** [comment]
@SoyDiego could you please tell me what's difference between opening an issue here in the Issue tracker and opening a Discussion in the link you've sent? Discussion item's purpose to open is when we're not 100% sure that some issue is persistent?

**Comment by SoyDiego** [comment]
> @SoyDiego could you please tell me what's difference between opening an issue here in the Issue tracker and opening a Discussion in the link you've sent? Discussion item's purpose to open is when we're not 100% sure that some issue is persistent?

The difference is that you are writing in the wrong place. On an issue that has nothing to do with your problem and you are mixing things up. The issue that I generated has to do with EDITOR Component and you are talking about ContextMenu and Menu.
If you have any questions about how something works, it is better to write in the place indicated, but do what you want, it will be more difficult to find the answer you want here.

**Comment by cetincakiroglu** [comment]
Fixed in here https://github.com/primefaces/primeng/commit/64dc78685cf3cad034ca8fe7d058b57acccb891b

Related to https://github.com/primefaces/primeng/issues/13831
