### ISSUE TITLE
Bug in Tooltip inside a dialog box

### ISSUE THREAD

**Issue by kcsahoo** [primefaces/primeng#1378]
Inside dialogbox, the input with tooltip has problem.
The tooltip postion is not working anymore in rc.5
It was working in rc.4
Request resolve in RTM.

**Comment by kcsahoo** [comment]
A part of code to illustrate:

<p-dialog header="View/Add/Edit/Delete Model" [(visible)]="displayAddDialog" modal="modal" showEffect="fade" width=850>
        <form [formGroup]="modelForm">
            <div class="ui-grid ui-grid-responsive ui-grid-pad">
                <div class="ui-grid-row" style="margin-left:40px;">
                    <div class="ui-grid-col-12">
                        <fieldset style="border-width:0">
                            <h4 class="first">Project Code *</h4>
                            <input pInputText type="text" id="projectCode" name="projectCode" placeholder="Project Code" [(ngModel)]="modelAdded.projectCode"
                                   formControlName="projectCode"
                                   pTooltip="Project Code is required field" tooltipPosition="bottom" tooltipEvent="hover">
                            <div *ngIf="!projectCode.valid && !projectCode.pristine" class="ui-message ui-messages-error ui-corner-all">
                                Project Code is required field
                            </div>
                        </fieldset>
                    </div>
                </div>

**Comment by eelayoubi** [comment]
i'm actually having a problem with the tooltip position, i have my tooltip inside a dataTable, i was using an old version of primeng (v.1.0.0-beta.20 ), i have my tooltip with position set to Bottom, it was working great, i just updated to 1.0.0-rc.6, and now the position of the tooltip is really bizarre !

**Comment by cagataycivici** [comment]
@eelayoubi Your isssue is fixed at #1383

**Comment by cagataycivici** [comment]
Just checked this issue inside dialog and 1383 fix also handles this.
