### ISSUE TITLE
Table | Expandable rows broken with paginator

### ISSUE THREAD

**Issue by cetincakiroglu** [primefaces/primeng#13783]
Expandable row grouping is broken when used with paginator

https://github.com/orgs/primefaces/discussions/135

**Comment by shanmuga-act** [comment]
Any ETA on this?

**Comment by cetincakiroglu** [comment]
This issue is a duplicate of https://github.com/primefaces/primeng/issues/14081.

Closing the issue.

**Comment by shanmuga-act** [comment]
@cetincakiroglu - It looks like the expandable row grouping looks fine in all the pages. But it looks like the expandable row group footer template getting attached with all the rows on second page onwards. But it looks fine in the first page. Pasted the 'stackblitz' link with this issue for your reference. Let me know if you need any more info.

https://stackblitz.com/edit/pjmitklr?file=src%2Fapp%2Ftable-expandable-row-group-demo.html

![Image](https://github.com/user-attachments/assets/ab0bf903-e628-4b05-9ec0-15dac1d2fe2c)
