### ISSUE TITLE
Add a section about layers in the doc

### ISSUE THREAD

**Issue by sebastienchevriaupro** [primefaces/primeng#13780]
### Describe the feature you would like to see added

https://www.youtube.com/watch?v=EPRUy0lvgBA

**Comment by SoyDiego** [comment]
PRs are welcome @sebastienchevriaupro :)

**Comment by sebastienchevriaupro** [comment]
What is the meaning of PR @SoyDiego  ?

**Comment by SoyDiego** [comment]
> What is the meaning of PR @SoyDiego ?

Pull requests :)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
