### ISSUE TITLE
DataView component NOT updating after its data source (array) changed

### ISSUE THREAD

**Issue by LightBulbIdea** [primefaces/primeng#13792]
### Describe the bug

When updating the data source of the DataView via TS the component doesn't reflect the changes in HTML. In order to reflect any changes that were made to the data source in HTML I need to interact with either sorting, filtering, changeLayout, pagination, etc.

Not entirely sure why updating the Array attached as data source to the DataView doesn't trigger a change detection so it can redraw the items.

### Environment

Windows 11

### Reproducer

https://stackblitz.com/edit/lvyxjh?file=src%2Fapp%2Fdemo%2Fdata-view-pagination-demo.html,src%2Fapp%2Fdemo%2Fdata-view-pagination-demo.ts,src%2Fapp%2Fapp.module.ts

### Angular version

16.1.4

### PrimeNG version

16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.1

### Browser(s)

Chrome 117

### Steps to reproduce the behavior

https://stackblitz.com/edit/lvyxjh?file=src%2Fapp%2Fdemo%2Fdata-view-pagination-demo.html,src%2Fapp%2Fdemo%2Fdata-view-pagination-demo.ts,src%2Fapp%2Fapp.module.ts

Go to the reproducer link >> Click the Add button (it will add the first item of the data source array over and over) >> The DataView component won't refresh and will display old values >> Click any of the pagination buttons at the bottom OR change the layout via code >> You will now see that the data being displayed gets updated with all the new items that were added to the data source via the Add button.

### Expected behavior

When modifying the data source array of the DataView component via TypeScript it should automatically reflect the changes made to it. I shouldn't have to trigger another TS function or interact with the component via the browser to see the changes.

**Comment by ashikjs** [comment]
@LightBulbIdea  it's Pass by reference issue. You need to remove/change your object reference,

 here one workable example:
https://stackblitz.com/edit/lvyxjh-ajz3uy?file=src%2Findex.html

**Comment by LightBulbIdea** [comment]
Oh I see. This solution will work. Thanks @ashikjs!

I will close the ticket.
