### ISSUE TITLE
Component: InputMask

### ISSUE THREAD

**Issue by pastpap** [primefaces/primeng#13798]
### Describe the feature you would like to see added

Two new attributes for the component to transmit down to the <input> child element.

Attribute list:

1.  **aria-autocomplete** - string | none, inline, list, both
2. **spellcheck** - boolean | true, false

We realize that these are not part of the <input> tag specification. Nevertheless they seem to do the trick when it comes to Edge. 

### Is your feature request related to a problem?

When opening a page that contains InputMasks with the Microsoft Edge browser the **private info** of the user is suggested for autocompleting the input.
This happens even with the autocomplete attribute already set to "off".
What was observed is that using aria-autocomplete eliminates this bug from edge.

Sometimes the Edge browser will also trigger a pop-up with suggested values if the spellcheck is not set to false.

### Describe the solution you'd like

Having the two extra attributes being passed down to the <input> child element of this component would fix the problem.

### Describe alternatives you have considered

What we used as an alternative was to create a directive with access to the InputMask component and querying the DOM for the child <input> element to set the attribute after the view init event when the input is actually generated.

`
     constructor(private mask: InputMask) {
     }

    public ngAfterViewInit(): void {
        ((this.mask.el.nativeElement as HTMLElement).firstChild as HTMLElement).setAttribute('aria-autocomplete', 'none');
    }
`

But this is an ugly workaround in our opinion. :)

### Additional context

![image](https://github.com/primefaces/primeng/assets/13162396/b9ad748c-b184-46f3-8608-b4f092aa7650)

**Comment by rehdie** [comment]
Another attribute, which would be useful for mobile devices: inputmode

**Comment by mertsincan** [comment]
Please use PrimeNG discussion channel for the new features. Thanks you!
