### ISSUE TITLE
p-calendar: I18N API doesn't change translations of dayNamesMin when p-calendar is inline

### ISSUE THREAD

**Issue by nidhal-belhadj** [primefaces/primeng#13793]
### Describe the bug

[X] bug report
[ ] feature request
[ ] support request

**Stackblitz Case (Bug Reports)**
https://stackblitz.com/edit/primeng11-localization-bug-8x9w6u

**Current behavior**
When calendar is inline, the i18N API doesn't change translations of dayNamesMin. (the view is not updated)

**Expected behavior**
days ans month names should be updated.

### Environment

dev env

### Angular version

12.0.0

### PrimeNG version

12.2.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.21.1

### Browser(s)

Chrome

### Steps to reproduce the behavior

1- create an app that contains the p-calendar component as inline (very important)
2- add a btn that change the language  (as described by the primeng doc https://www.primefaces.org/primeng-v12-lts/#/i18n)
3- in your env, try to change the language 

### Expected behavior

days ans month names should be updated.

**Comment by ashikjs** [comment]
@nidhal-belhadj but it's working on updated version did you try to upgrade it to new version and your stackblize primng & Angular version is 11.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
