### ISSUE TITLE
MuliSelect | throws error when double clicking on trigger icon

### ISSUE THREAD

**Issue by cetincakiroglu** [primefaces/primeng#13808]
**Reproduction: ** double click on trigger icon 

https://stackblitz.com/edit/dtvhna-mlyhdq?file=src%2Fapp%2Fdemo%2Fmulti-select-virtual-scroll-demo.htmlthrows error when double clicking on selection container

**Comment by turp** [comment]
This bug looks like it's related: https://github.com/primefaces/primeng/issues/12778

**Comment by turp** [comment]
@cetincakiroglu - any luck resolving this issue? I see it was removed from 16.6.0 milestone. Thanks!

**Comment by turp** [comment]
This is still an issue for us. We're currently using 16.02 - I haven't tried 17 yet, but I assume it's still an issue in the latest version.

**Comment by turp** [comment]
This is still an issue. Do not close

**Comment by edipof** [comment]
This is still an issue.
