### ISSUE TITLE
Component: TreeSelect with [showClear]="true" changing height after select item

### ISSUE THREAD

**Issue by AnViSe** [primefaces/primeng#13801]
### Describe the bug

Component: TreeSelect with [showClear]="true" changing height after select item

### Environment

angular version 16.2.0
primeng version 16.4.1

### Angular version

16.2.0

### PrimeNG version

16.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.6.0

**Comment by anlampe** [comment]
Looks like it's a similar issue like #13654, means it should maybe also be raised [here](https://github.com/primefaces/primeng-sass-theme/issues).

**Comment by SoyDiego** [comment]
Hi @AnViSe and @anlampe. 
I have created a PR solving the issue in `primeng-sass-theme` project.
You can check here: https://github.com/primefaces/primeng-sass-theme/pull/58

Thanks for report the problem
