### ISSUE TITLE
TieredMenu: rootmenu coming as undefined for 'onOverlayAnimationStart' 

### ISSUE THREAD

**Issue by ShrutiBaghel** [primefaces/primeng#13812]
### Describe the bug

While running all the specs in jasmine-karma framework I get an error, 
ERROR: 'ERROR', TypeError: Cannot read properties of undefined (reading 'sublistViewChild')
TypeError: Cannot read properties of undefined (reading 'sublistViewChild')
    at TieredMenu.onOverlayAnimationStart

This has been started from primeng version 16.1.0 and not before that. 
As it doesn't talk about any particular spec file in my application instead navigates to zone.testing I am not sure how to go ahead with it.

### Environment

angular version 16.2.6
primeng version 16.4.1

### Angular version

16.2.6

### PrimeNG version

16.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.19.0

**Comment by Kateriine** [comment]
+1

**Comment by ShrutiBaghel** [comment]
The problem was with my specs, found the issue hence closing. Thanks
