### ISSUE TITLE
Password | Incorrect placement of close icon when [toggleMask]="true"

### ISSUE THREAD

**Issue by leykee** [primefaces/primeng#13817]
### Describe the bug

When enabling both the showClear and toggleMask flags at the same time, then the clear icon is not position well

<img width="710" alt="Screenshot 2023-10-06 at 11 32 41" src="https://github.com/primefaces/primeng/assets/94969394/b52200cd-ea2e-4e40-bd9a-a3810a9701eb">

### Environment

macOS

### Angular version

16.2.4

### PrimeNG version

16.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.20

### Browser(s)

Chrome

### Expected behavior

The icon should be vertically centred.

**Comment by SoyDiego** [comment]
> ### Describe the bug
> 
> When enabling both the showClear and toggleMask flags at the same time, then the clear icon is not position well
> <img alt="Screenshot 2023-10-06 at 11 32 41" width="710" src="https://user-images.githubusercontent.com/94969394/273166955-b52200cd-ea2e-4e40-bd9a-a3810a9701eb.png">
> ### Environment
> 
> macOS
> ### Reproducer
> 
> _No response_
> ### Angular version
> 
> 16.2.4
> ### PrimeNG version
> 
> 16.1.0
> ### Build / Runtime
> 
> Angular CLI App
> ### Language
> 
> TypeScript
> ### Node version (for AoT issues node --version)
> 
> 16.20
> ### Browser(s)
> 
> Chrome
> ### Steps to reproduce the behavior
> 
> _No response_
> ### Expected behavior
> 
> The icon should be vertically centred.

Thanks for reported.
Tomorrow I will fix it! :)

**Comment by SoyDiego** [comment]
Hi @leykee,
I did a PR solving the problem. You can check it here: https://github.com/primefaces/primeng/pull/13823
Now we should wait PrimeNG Team approve it if they think the solution is OK for them.
