### ISSUE TITLE
Component: Carousel | Circular Option is broken when first iteration is done

### ISSUE THREAD

**Issue by EnricoMessall** [primefaces/primeng#13821]
### Describe the bug

When first circular iteration is done, the component moves back all the way to the second element see:
https://www.youtube.com/watch?v=9YeLum9tyn0

Looking into some console loggings, it is looking for me that the value at position 7 to -3 (totalShiftedItems) is being wrongly overwritten by the second logging at position 4 to -1 (totalShiftedItems).

The second logging in this case is the ngAfterContentChecked function.

<img width="340" alt="Screenshot 2023-10-07 at 08 26 05" src="https://github.com/primefaces/primeng/assets/62150527/6f3a6e64-125f-4f12-bad9-cf171c75f01f">

### Environment

-

### Reproducer

https://primeng.org/carousel

### Angular version

16.2.3

### PrimeNG version

16.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.5.1

### Browser(s)

Chrome, Safari

**Comment by EnricoMessall** [comment]
Problem is not part of the totalShiftedItems.

It lays in onTransitionEnd where the first element is getting a translate3d of 100 after first of all having one of 1100 after some milliseconds. If the carousel isn't waiting for that, this effect happens.

**Comment by EnricoMessall** [comment]
Results from [ngAfterContentChecked](https://github.com/primefaces/primeng/blob/master/src/app/components/carousel/carousel.ts#L492) this line. When using normal stepping by hand this line resets totalShiftedItems to its correct value before calling onTransitionEnd. With autoplayInterval or too fast clicking ngAfterContentChecked happens after onTransitionEnd and results in having the wrong translate3d value

**Comment by notetosiraj** [comment]
modified totalShiftedItems condition  seems issue may fixed .

`
//carousel.ts

step(dir: number, page?: number) {

// code removed here due to brevity

if (isCircular && this.page === this.totalDots() - 1 && dir === -1)
 {       
            totalShiftedItems = -1 * this._numVisible;               // modified line
            page = 0;            
  } 
        
  }
`
![gitissue](https://github.com/primefaces/primeng/assets/51027104/832faa61-f9ce-4a65-8c9c-8cd859825e07)
