### ISSUE TITLE
Tooltip: disable autoHide doesn't work

### ISSUE THREAD

**Issue by Adrii77** [primefaces/primeng#13828]
### Describe the bug

The option "autoHide" doesn't work properly. If autoHide is set to false, the tooltip disapear.

### Environment

NG 16, PrimeNG 16

### Angular version

16.2.7

### PrimeNG version

16.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.20.0

### Browser(s)

Chrome 117

### Steps to reproduce the behavior

1. Go here : https://primeng.org/tooltip#autohide
2. hover the input with autoHide false, then, hover the tooltip content.

### Expected behavior

Tooltip should not disapear if autoHide is set to false when toopltip's content is hovered.

**Comment by konuch** [comment]
Caused by this commit: https://github.com/primefaces/primeng/commit/bc98f435587562e234b36d035e0a544884232813

**Comment by SoyDiego** [comment]
Hi @Adrii77 and @konuch, you are right about the problem
I have created a PR solving the problem removing the `pointer-events`.
You can check here https://github.com/primefaces/primeng/pull/13847

Thanks!

**Comment by AliKholmatov** [comment]
Hi. It doesn't work with positionLeft property
