### ISSUE TITLE
SlideMenu: Deprecate from PrimeNG 

### ISSUE THREAD

**Issue by gucal** [primefaces/primeng#13830]
Deprecate SlideMenu

**Comment by nathanvj** [comment]
May I ask why this component was deprecated?

**Comment by james-cavanagh** [comment]
Can I also ask why?

**Comment by quartelh** [comment]
Where can we find information about what will replace the SlideMenu? 
By deprecating this component our solution is now functionally broken.

**Comment by PR4SAN** [comment]
why this component got deprecated? can anyone update the motive here? this breaks application

**Comment by aydinjons** [comment]
Why?  we are using this component in lots of projects.
