### ISSUE TITLE
Component: Calendar

### ISSUE THREAD

**Issue by Lucas-Feichtinger** [primefaces/primeng#13832]
### Describe the feature you would like to see added

A option to create custom columns inside the calendar table, that provides a way to display additional information.  

### Describe the solution you'd like

in Usage it could look something like this:
![image](https://github.com/primefaces/primeng/assets/17267378/7580a492-ecf3-45bd-b4c6-64a6e1f0b4e1)

### Describe alternatives you have considered

Another option could be adding additional pTemplate="left" and pTemplate="right" the the Calendar. This way you do not have to build a workaround with pTemplate="header" to move the content to the side of the Calendar.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
