### ISSUE TITLE
Calendar fills string var with date instead time

### ISSUE THREAD

**Issue by Gwulior** [primefaces/primeng#1384]
Hello, i have a field like below
```
<p-calendar [(ngModel)]="endTime" dataType="string" timeOnly="true" hourFormat="24"
[showIcon]="true"></p-calendar>
```
I choose a time, and when i grab my model var, i see it is filled with "11/21/2016" instead "20:46" i can see in the field.

**Comment by gekallergis** [comment]
I also have a similar problem! Setting the control as

`<p-calendar ... dataType="string" dateFormat="M dd, yy" [showTime]="true" [hourFormat]="24" ...`

results in my model having just the date instead of both date and time! :disappointed:

**Comment by gavrilas** [comment]
I also have a similar problem! 

There is no time information in string dataType.

**Comment by victorcg88** [comment]
Same problems. The simplest example:

`<p-calendar [(ngModel)]="mySelection" dataType="string" [showTime]="true"></p-calendar>
 <span>Display the date an tyme:{{mySelection}}</span>`

It shows on calendar input box correct selection ('01/18/2017 12:13') but fails showing on span 01/10/2017.

Kind of a bug? Any workaround?

**Comment by ben2323** [comment]
Same issue over here. Any news ?

**Comment by niravpatel9898** [comment]
`<p-calendar [(ngModel)]="time_24h" [timeOnly]="true" [showTime]="true" [hourFormat]="24" (onSelect)="onChangeTime($event)"></p-calendar>
`
```
onChangeAgendaTime($event:any){
    console.log("hahaha: "+this.convertTime($event));
}
```

```
convertTime(str:string) {
      var date = new Date(str),
      mnth = ("0" + (date.getMonth()+1)).slice(-2),
      day  = ("0" + date.getDate()).slice(-2),
      hours  = ("0" + date.getHours()).slice(-2),
      minutes = ("0" + date.getMinutes()).slice(-2);
      return [hours, minutes].join(":");
}

```
The console.log above is giving me the correct 24hr formatted time :)

**Comment by victorcg88** [comment]
Yes, but that is not a example with `dataType="string"` and `[timeOnly]="false"`

**Comment by gourab-dilu** [comment]
<p-calendar class="s-caldr" [(ngModel)]="statFromDt"
						showTime="true" hourFormat="24" showIcon="true"
						[minDate]="minDate" [maxDate]="maxDate" [readonlyInput]="true"
						(ngModelChange)="fromToDateChange()"></p-calendar>
Try this it will work

**Comment by Bengejd** [comment]
Everyone is throwing out different functions that accomplish the issue at hand, but why over complicate things, when Javascript does this naturally for us?

Just use ` modelVar.toLocaleTimeString('en-GB');`

While @niravpatel9898 's solution does technically work (Though it will trigger every time you change the time, like trying to set the minutes for example), it's reinventing the wheel, and unnecessary.

**Comment by cagataycivici** [comment]
Please provide a plunkr that replicates this and we'll reopen.

http://plnkr.co/edit/VZbdZfQ7SuTV87tTkbYR?p=preview

I can't seem to replicate with 4.0.2
