### ISSUE TITLE
Component: Title

### ISSUE THREAD

**Issue by kazakevich-alexei** [primefaces/primeng#13842]
### Describe the feature you would like to see added

Functionality is needed to transmit values for @Input and @Output parameters.
Make a normal component, not a lousy wrapper.

### Is your feature request related to a problem?

[_No response_](https://github.com/primefaces/primeng/issues/8383)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
