### ISSUE TITLE
menu component item for ng-template

### ISSUE THREAD

**Issue by coskunyaman** [primefaces/primeng#13848]
### Describe the feature you would like to see added

Hello, it will be great to be able to define ng-template for items of menu objects.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
