### ISSUE TITLE
p-multiselect: Unable to tab to the footer template within a MultiSelect

### ISSUE THREAD

**Issue by adyeardley** [primefaces/primeng#13857]
### Describe the bug

I'm submitting a ... (check one with "x")

```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
The multiselect closes if you use tab to move to the footer template.

**Expected behavior**
By using tab. I want to be able to navigate to the footer.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/primeng-multiselect-demo-shsaac?file=src%2Fapp%2Fapp.component.html

**What is the motivation / use case for changing the behavior?**
For accessibilty, we need to be able to use the multiselect using only keyboard inputs.

### Environment

Angular version: 16.2.0

PrimeNG version: 16.0.2

Browser:
Edge 117.0.2045.60
Chrome 118.0.5993.71

### Reproducer

https://stackblitz.com/edit/primeng-multiselect-demo-shsaac?file=src%2Fapp%2Fapp.component.html

### Angular version

16.2.0

### PrimeNG version

16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14.2

### Browser(s)

Edge, Chrome, Firefox

### Steps to reproduce the behavior

- open the multiselect
- use TAB to try and navigate to the footer content
- the multiselect closes.

### Expected behavior

By using tab. I want to be able to navigate to the footer.

**Comment by capc0** [comment]
Additionally, if the current focus is within the footer and the user presses `tab` again, the focus goes to the next DOM element outside of the overlay panel, breaking the "focus-trap-logic".

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
