### ISSUE TITLE
p-messages: static content not being displayed

### ISSUE THREAD

**Issue by mikehutter** [primefaces/primeng#13858]
### Describe the bug

The static content of the p-messages component is not displayed. The MessagesModule does not re-export SharedModule which declares the pTemplate directive and so the template is not found by the MessagesComponent and thus not displayed.

https://github.com/primefaces/primeng/blob/97045e75d4758b4af480e30e59206bef73d64916/src/app/components/messages/messages.ts#L262

https://github.com/primefaces/primeng/blob/97045e75d4758b4af480e30e59206bef73d64916/src/app/components/messages/messages.ts#L134

The current workaround would be to also import SharedModule from primeng/api when no other imported module uses/exports SharedModule. (ex: ToastModule)

### Environment

Angular: 16.2.x
PrimeNG: 16.5.x
Node: 18.17.x

### Reproducer

https://stackblitz.com/edit/c9xj4a

### Angular version

16.2.x

### PrimeNG version

16.5.x

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.17.1

### Steps to reproduce the behavior

Open the provided [stackblitz](https://stackblitz.com/edit/c9xj4a) and confirm that the static content is not displayed. Also, confirm that SharedModule is not re-exported in source.

https://github.com/primefaces/primeng/blob/97045e75d4758b4af480e30e59206bef73d64916/src/app/components/messages/messages.ts#L262

### Expected behavior

The p-messages component should discover the pTemplate and display its content statically.

**Comment by IceBreakerG** [comment]
I was also having this issue. Importing the `SharedModule` from `primeng/api` fixed the issue.

**Comment by Et3rnal** [comment]
Looks like the issue is due to missing icon-related import, so if you import any other module that has icons (and doesn't have the same issue) the messages will appear

for example `ChipsModule`

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
