### ISSUE TITLE
primeng.css: Disabled items have 'default' cursor rather than 'not-allowed' cursor

### ISSUE THREAD

**Issue by derekatkinson** [primefaces/primeng#1385]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Disabled items, such as disabled tabs, show the `default` cursor when mouse hovers over them.

**Expected behavior**
Disabled items, such as disabled tabs, should show the `not-allowed` cursor when mouse hovers over them.

**Minimal reproduction of the problem with instructions**

View the _tabview_ page in PrimeNG documentation: http://www.primefaces.org/primeng/#/tabview
and hover over the disabled button. Cursor is `default` rather than `not-allowed`, and if you try to override `.ui-state-disabled`'s cursor with a `not-allowed` cursor using your browser's developer tools you won't be able to.

**What is the motivation / use case for changing the behavior?**

The `not-allowed` cursor is more informative than the `default` cursor, indicating that there might be an action available for a part of the UI but that it is currently not allowed or disabled.

I'm making theme modifications so that PrimeNG components will fit into our existing UI seamlessly. Currently, we use the `not-allowed` cursor on all disabled items. The following rules in primeng.css prevent me from changing the cursor to `not-allowed` for disabled items:
```
/* Interaction Cues
----------------------------------*/
.ui-state-disabled { cursor: default !important; }
.ui-state-disabled a { cursor: default !important; }
```

I don't want to edit this in primeng.css, since we're likely to adopt updates to that file in the future and would have to repeat this change each time. If the `not-allowed` cursor were used instead, or even if `!important` were removed, our problem would be solved.

**Please tell us about your environment:** 

* **Development environment:** macOS Sierra 10.12, installed PrimeNG via npm (and IDE should have no impact)

* **Angular version:** N/A

* **PrimeNG version:** 1.0.0-rc.5

* **Browser:** Chrome 54.0.2840.71

 
* **Language:** CSS

* **Node (for AoT issues):** `node --version` =   v.4.5.0

**Comment by cagataycivici** [comment]
What is the cursor on a disabled native html element?

```
<input type="text" disabled>
```

**Comment by derekatkinson** [comment]
Looks like it's the `default` cursor, which is surprising. I guess it makes sense from PrimeNG to follow that standard, but I wonder if it's necessary to define this cursor rule as `!important` in primeng.css.

**Comment by cagataycivici** [comment]
!important is there to make sure no other custom css overrides it, we had some issues in the past with PrimeFaces so included !important as it is not likely for users to customize disabled cursor.
