### ISSUE TITLE
TieredMenu: Submenus in popup do not appear on hover.

### ISSUE THREAD

**Issue by ryankugel** [primefaces/primeng#13861]
### Describe the bug

In past version of PrimeNG, submenus in popups were shown immediately when hovering over an item when using `autoDisplay`. This bug was introduced in PrimeNG 16.1.0. #13582 reported this bug, and a fix was made in #13593, but it does not appear to have fixed the problem.

This is due to to checking `this.dirty` in `onItemMouseEnter()`. When the popup is initially shown, `this.dirty` is `false`, so `onItemChange(event)` is not called until an item is clicked.

A potential solution for this bug is to update the `show()` function to set `this.dirty` to `true` if `popup` & `autoDisplay` are both `true`.

### Environment

N/A

### Reproducer

See below

### Angular version

16.2.0

### PrimeNG version

16.5.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.16.0

### Browser(s)

All

### Steps to reproduce the behavior

Use PrimeNG's showcase for the TieredMenu: https://primeng.org/tieredmenu

1. In the **Popup** section, click the **Show** button.
2. Hover over the items in the root menu, like "File" & "Edit" and note that their submenus do not show.

### Expected behavior

Submenus should immediately appear when hovering over an item when `popup` and `autoDisplay` are set to `true`.

**Comment by ginger7890** [comment]
Hello,

We are having the same problem.

It seems this behavior depends on Window's "touch screen" feature.

Submenu pops up on mouse over when "touch screen" feature is enabled.
![20231211_093010](https://github.com/primefaces/primeng/assets/136214476/5147a1a3-8422-4485-8874-2daa407adb9f)

Submenu does not pop up on mouse over when "touch screen" feature is disabled.
![20231211_093129](https://github.com/primefaces/primeng/assets/136214476/bb99b868-f2eb-4211-8961-3ad5eeaf38a7)

For PCs without touch screens, the sub menu does not pop up on mouse over.

I have checked with five colleagues and this seems to be affecting the behavior.

We would like for the sub menu to pop up on mouse over as well even when "touch screen" feature is not available.

**Comment by WienemannCC** [comment]
We are experiencing the same Issue.

**Comment by DerekBolger** [comment]
Hi guys just to let you know, this issue also exists for the Menubar Component on your latest stable release. Tested by multiple people in the office using different variants of Microsoft Surface Books and Surface Book laptops (when touchscreen is enabled).

When hovering on a menu item with dropdown sub menu's it wont appear.
