### ISSUE TITLE
Primeng Steps: ng Template

### ISSUE THREAD

**Issue by saikrishnasangapu** [primefaces/primeng#13865]
### Describe the feature you would like to see added

Please open the ng template for primeng steps 
currently in the pstep component the steps are in numbers only. but if ng template is added we can use a json to define all the custom properties using ngtemplate body or for step

**Comment by Aniruddha-Shriwant** [comment]
+1

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
