### ISSUE TITLE
Tooltip doesn't accept TemplateRef<HTMLElement> anymore

### ISSUE THREAD

**Issue by Marc-AntoineGL** [primefaces/primeng#13866]
### Describe the bug

Hello, sorry in advance if my issue is not clear enough, that's my first one.

I am using tooltip and displaying a template inside it with a TemplateRef<HTMLElement>.

But a recent [commit](https://github.com/primefaces/primeng/commit/6c53f9d12bcfc3acab7a09417d39705a446c4043) has removed that possibility, this following code has been changed:
```ts
@Input('pTooltip') content: string | TemplateRef<HTMLElement> | undefined;
```
I don't know if it was on purpose or not, but according to this, your [documentation](https://primeng.org/tooltip) about tooltip is now outdated mentionning "Tooltip can use either a string or a TemplateRef." 

On top of that I have been impacted by a change in the constructor taking as argument a ChangeDetectorRef instead of a ViewContainerRef previously. 

```ts
constructor(@Inject(PLATFORM_ID) private platformId: any, public el: ElementRef, public zone: NgZone, public config: PrimeNGConfig, private renderer: Renderer2, private viewContainer: ViewContainerRef) {}
```

Since these two changes are not really linked with the commit message "Add id and role attributes to tooltip for accessibility" I would like to know if they are going to be kept or not so I can update my code accordingly if yes.

For the moment I'm keeping my 16.4.1, so let me know.

Regards.

### Environment

Angular app

### Angular version

^16.2.2

### PrimeNG version

16.5.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.10.0

**Comment by lwestfall** [comment]
Wow, this is serendipitous. I just ran into this and was going to submit an issue myself.

**Comment by jncalderon** [comment]
I have this issue as well :(

**Comment by bemes9226** [comment]
so we need to add this code in my ts file, need some assist here in satckblitz
