### ISSUE TITLE
Show active state on tabMenu items that use routerLink

### ISSUE THREAD

**Issue by digitalcraftco** [primefaces/primeng#1386]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

Doesn't respect routerLinkActive if tabMenu is used for navigating to unique views. On refresh .ui-state-active gets reset to [0].

**Expected behavior**

Detect if routerLink is being used and keep track of active state.

Similar to #1382 for menuBar component. Add RouterModule and below to tabMenu.ts

```[routerLink]="item.routerLink" routerLinkActive="ui-state-active"```

**Comment by cagataycivici** [comment]
Fixed via;

https://github.com/primefaces/primeng/issues/2393
