### ISSUE TITLE
Component: Messages are not shown and closed properly

### ISSUE THREAD

**Issue by keatis** [primefaces/primeng#13879]
### Describe the bug

Hi. I tried and example of multiple closable messages from [documentation page](https://primeng.org/messages), but got a bit different result.

Instead of three messages at a time I've got first rendered ok, only colored container with no text and icons instead of the second message, and no third message at all.

When I click a close button of 1st msg, the second message becomes ok. Then, if I click any close button again, third message shows up.

There's a bit more odd behavior: when a complete set of messages shown, clicking Close button will close corresponding message **and** the messages below. Thus, closing first message will eliminate all three _(I expect only first msg is closed)_.

### Environment

Here is a minimal stackblitz to highlight a problem: https://stackblitz-starters-d51k3w.stackblitz.io
I made it from fresh start, since Issue Template is kinda not usable. 

### Reproducer

https://stackblitz-starters-d51k3w.stackblitz.io

### Angular version

16.2.9

### PrimeNG version

16.5.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.8.0

### Expected behavior

I expect three messages at a time to completely render.
Clicking Close button only closes corresponding message.

**Comment by cetincakiroglu** [comment]
Hi,

Your Stackblitz example is broken, please update the link

**Comment by keatis** [comment]
Hmm, weird. I just copied and URL via Share function.
Ok, here's an editor link: https://stackblitz.com/edit/stackblitz-starters-d51k3w?file=src%2Fmain.ts

**Comment by lwestfall** [comment]
@keatis your standalone component doesn't bootstrap the animations module. See: https://stackoverflow.com/a/72504735/6621862

Forked your stackblitz with fix implemented: https://stackblitz.com/edit/stackblitz-starters-gwrukw?file=src%2Fmain.ts

**Comment by keatis** [comment]
Oh, I completely missed BrowserAnimationsModule from documentation. Thanks for pointing this out.
Everything works fine and smoothly now. Thanx twice for help!
