### ISSUE TITLE
Component: Documentation (Step)

### ISSUE THREAD

**Issue by ibrahimkelly** [primefaces/primeng#13885]
### Describe the bug

On step menu click, the parent container (Components) section close.

<img width="683" alt="Screenshot 2023-10-15 at 12 28 15" src="https://github.com/primefaces/primeng/assets/94073143/0b018798-6b4c-495c-aa70-dd0565c46c1c">

After click
<img width="792" alt="Screenshot 2023-10-15 at 12 29 03" src="https://github.com/primefaces/primeng/assets/94073143/f944a24e-edb4-4317-90a6-6907da17fb87">

### Environment

Mac os

### Angular version

16.2.9

### PrimeNG version

16.5.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

In the documentation

On Menu section
1. Click on step
2. The global section (Components) will be closed.

**Comment by SoyDiego** [comment]
Hi @ibrahimkelly, thanks for report it.
I have created a PR here #13887 solving the problem.
Now we should wait PrimeNG team check it and approve it if it's ok for them.

Thanks
