### ISSUE TITLE
Documentation website: style issue when switching themes

### ISSUE THREAD

**Issue by Ensar025** [primefaces/primeng#13880]
### Describe the bug

When viewing the API section of the documentation, if I switch from light mode to dark, or dark to light mode, the default column of the API section stays like the previous theme, making it unreadable. 

This happens with every documented component. The class "doc-option-light" does not change to "doc-option-dark" when the theme is switched.

Example switching from dark to light: 
![image](https://github.com/primefaces/primeng/assets/99197230/a8ef2f67-c4a5-4cb7-b3ce-a5d89a7a5f5e)

Example switching from light to dark:
![image](https://github.com/primefaces/primeng/assets/99197230/b36baee3-8c5e-40eb-b912-bf380b0445ef)

### Environment

Microsoft Edge Version 117.0.2045.60 (Official build) (64-bit), haven't tested with other browsers

### Angular version

not applicable

### PrimeNG version

v 16.5.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

not applicable

**Comment by cetincakiroglu** [comment]
Hi,

Thanks a lot for reporting the issue, it's fixed now.
