### ISSUE TITLE
Accordion: Add Search Functionality

### ISSUE THREAD

**Issue by Gykonik** [primefaces/primeng#13888]
### Describe the feature you would like to see added

I propose the introduction of a search functionality to the accordion component, enhancing both its accessibility and usability. This feature would include a search bar within or atop the accordion, enabling users to effortlessly locate and access the content they need.

Upon entering a search query, the accordion tabs containing matching text would automatically expand to reveal the relevant content. There could be options to either expand all matching tabs or only the first matching tab, providing a flexible user experience. This feature would be particularly beneficial in instances where the accordion hosts a substantial amount of content, making manual navigation time-consuming or cumbersome.

**Benefits**
- Improved Accessibility: Users with disabilities may find it easier to access the content they need without having to navigate through each accordion tab.
- Enhanced Usability: A search functionality would streamline the process of locating specific content within the accordion, saving time and improving the overall user experience.
- Flexible Navigation: By providing the option to expand either all matching tabs or only the first, users can choose the navigation mode that suits them best.

If you guys think that this is not a feature that would be used frequently, I would still love to hear about hints how to implement it on my own! :)

### Is your feature request related to a problem?

No

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
