### ISSUE TITLE
Component:  Calendar timeOnly selectionMode="range"

### ISSUE THREAD

**Issue by pclancysc** [primefaces/primeng#13884]
### Describe the feature you would like to see added

The Calendar component has an existing selectionMode property.  When [timeOnly]=true the selectionMode property is ignored. 

Ideally allow a range of times to be selected in this mode.

e.g. 
09:00 to 17:00

### Is your feature request related to a problem?

I'ts not documented that the selectionRange property only applies to dates

### Describe the solution you'd like

Extend current function to show two time pickers side by side.  Validate end time > start time.

**Comment by El-Tommy** [comment]
@pclancysc Were you able to extend the current component to have this support or did you migrate to another one?

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
