### ISSUE TITLE
Tooltip: Output 'e' on console

### ISSUE THREAD

**Issue by Snoppi-Wizard** [primefaces/primeng#13894]
When opening the menu in a split-button, 'e' is written to the console.

**Comment by rosenthalj** [comment]
For completeness, the latest version of toopltip.ts (October 17, 2023) now properly handles simpleChange.id

![Blaming_primeng_src_app_components_tooltip_tooltip_ts_at_master_·_primefaces_primeng](https://github.com/primefaces/primeng/assets/45439491/12207f53-1a63-48b3-ad5b-82690fa95095)

**Comment by cetincakiroglu** [comment]
Hi,

This issue is fixed and it's not available in releases after 16.5.0. Closing the issue.
