### ISSUE TITLE
Add multi-column feature to AutoComplete 

### ISSUE THREAD

**Issue by mendozagit** [primefaces/primeng#13893]
### Add MultiColumn feature to AutoComplete componet. 

This feature was requested a long time ago in #4269 , but was never developed. 
The community really feels that this feature adds a lot to the component.
The idea is: instead of showing a list of selectable single items, show a table with selectable rows.

Something like ... 
![Screenshot_2](https://github.com/primefaces/primeng/assets/28969854/b2b001f4-a390-49bf-afd1-bd1c62acfe6e)

### Is your feature request related to a problem?

No

### A) Table Headers
   - Table headers should be inferred by suggestions object array.
   
     ``` js
     suggestions= [
       {employeeId : "0001", "firstname": "Jesus", "city": "Dallas" },
       {employeeId : "0002", "firstname": "Raul", "city": "Vancouver" },
       {employeeId : "0003", "firstname": "Jose", "city": "New York" }
     ]
     ```
   
     **Table headers and rows should look like:**
     ```markdown
     | EmployeeId | Firstname | City       |
     |------------|-----------|------------|
     | 0001       | Jesus     | Dallas     |
     | 0002       | Raul      | Vancouver  |
     | 0003       | Jose      | New York   |
     ```
   
### B) Table Cells Selectable
   - When the table has many columns enable horizontal scroll.
   - Table cells should be selectable with the left and right arrows on the keyboard only to move the horizontal scroll and see the rest of the not visible columns.
   
### C) Configuration
   - By default, the table must have the same width as the AutoComplete box.
   - The width and height of the table should be configurable by properties.
   
### D) Keyboard Support  Inherited from AutoComplete (Only lastone is new)
   ```markdown
   | Key       | Function                                                                                      |
   |-----------|-----------------------------------------------------------------------------------------------|
   | tab       | Moves focus to the input element when popup is not visible. If the popup is open and an item  |
   |           | is highlighted then popup gets closed, item gets selected and focus moves to the next        |
   |           | focusable element.                                                                            |
   | up arrow  | Highlights the previous item if popup is visible.                                             |
   | down arrow| Highlights the next item if popup is visible.                                                |
   | enter     | Selects the highlighted item and closes the popup if popup is visible.                        |
   | home      | Highlights the first item if popup is visible.                                               |
   | end       | Highlights the last item if popup is visible.                                                |
   | escape    | Hides the popup.                                                                              |
  | down arrow | If the popup is hidden, pressing this key will open the popup and move the focus to  the first row. |
 ```

 
 
 
### E) Dummy Sample 
![Screenshot_2](https://github.com/primefaces/primeng/assets/28969854/b2b001f4-a390-49bf-afd1-bd1c62acfe6e)

### Describe alternatives you have considered

https://help.syncfusion.com/js/autocomplete/multicolumn

### Additional context

https://demos.telerik.com/kendo-ui/multicolumncombobox/index

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
