### ISSUE TITLE
Component: Tooltip needs always visible option

### ISSUE THREAD

**Issue by pclancy** [primefaces/primeng#13896]
### Describe the feature you would like to see added

We need to be able to show tooltips on mobile devices, e.g. using the speed dial control there is no way for the user to know what each icon means without some textual context. 

### Is your feature request related to a problem?

Users cannot tell what the option in a speed dial does without any textual context.   The speed dial would otherwise be a great component for mobile users.

### Describe the solution you'd like

 Ideally extend the current tooltipEvent prop to have an "Always" or "None" event type that means the tooltip is always shown.

### Describe alternatives you have considered

CSS overrides won't work since the tooltip element isn't rendered until the tooltipEvent occurs.

**Comment by dmcclure-qcells** [comment]
Ran into the same issue with tooltips, and to solve this by extending the directive is IMO a little messy. Particularly in my use case of attaching a tooltip to an element with dynamic position. You need to override all of the default behavior to hide the tooltip, while preserving desired behavior.

If I remember correctly, a workaround could be to use the functions from the Tooltip to unbind all of the event listeners, and then use the `show()` method to activate it.
I believe

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
