### ISSUE TITLE
Component: Button cannot be associated with form

### ISSUE THREAD

**Issue by pclancy** [primefaces/primeng#13897]
### Describe the feature you would like to see added

The p-button control should expose a Form property.

### Is your feature request related to a problem?

The p-button control does not expose a Form property.  It won't be possible to associate a Form with a submit button which is useful when adding Submit buttons into separate templates (e.g. footer in dialog or side panel)

e.g. Dialog content

`<form id="myform"></form>`

e.g. Dialog footer

` <ng-template pTemplate="footer">
<p-button type="submit" form="myform" label="submit"></p-button>
</ng-template>`

### Describe the solution you'd like

p-button needs to expose a Form prop as per https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#form

> The element to associate the button with (its form owner). The value of this attribute must be the id of a `<form>` in the same document. (If this attribute is not set, the `<button>` is associated with its ancestor `<form>` element, if any.)
> 
> This attribute lets you associate `<button>` elements to `<form>`s anywhere in the document, not just inside a `<form>`. It can also override an ancestor `<form>` element.
> 

### Describe alternatives you have considered

Falling back to a standard button with the `pButton` directive.

**Comment by RFretwell** [comment]
Nothing major to add to the discussion other than I've also just run into this as a problem.

**Comment by fhcj2** [comment]
Me too

**Comment by matteocusinato** [comment]
Me too 👍

**Comment by JamesTheTerry** [comment]
Same issue here :/

**Comment by luber** [comment]
+1

**Comment by mertsincan** [comment]
Please use PrimeNG discussion channel for the new feature. Thanks a lot!

**Comment by Ivanho92** [comment]
I transfered the issue to a [discussion](https://github.com/orgs/primefaces/discussions/3346) as recommended.
