### ISSUE TITLE
pTooltip: New id property not forwarded to HTML id property

### ISSUE THREAD

**Issue by jpgoelz** [primefaces/primeng#13891]
### Describe the bug

When using property binding or a calculated value (using `{{}}`) on the `id` property of an element and `[pTooltip]` is used, The `id` is no longer set and only `ng-reflect-id` exists on the element. This breaks CSS that is based on ID selectors.

The bug was most probably introduced in https://github.com/primefaces/primeng/pull/13849.

### Environment

Not much to tell. I could recreate this behavior on multiple different environments.

### Reproducer

https://angular-ckdurs.stackblitz.io

### Angular version

16.2.9

### PrimeNG version

16.5.0

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Steps to reproduce the behavior

There are two ways which are both not working:

```html
<!-- property binding -->
<span [id]="'element-42'" [pTooltip]="'tooltip 42'"></span>
<!-- no property binding, but calculated id -->
<span id="element-{{ 43 }}" [pTooltip]="'tooltip 43'"></span>
```
The resulting HTML is missing the id property:
```html
<span _ngcontent-ng-c1260524478='' class='p-element' ng-reflect-id='element-42' ng-reflect-text='tooltip 42'></span>
<span _ngcontent-ng-c1260524478='' class='p-element' ng-reflect-id='element-43' ng-reflect-text='tooltip 43'></span>
```

Not using the property binding or calculated id works:
```html
<!-- direct use of id: works -->
<span id="element-44" [pTooltip]="'tooltip 44'"></span>
```
Resulting HTML has `id` property:
```html
<span _ngcontent-ng-c1260524478='' id='element-44' class='p-element' ng-reflect-id='element-44' ng-reflect-text='tooltip 44'></span>
```

### Expected behavior

The ID property is properly set in all three cases.

**Comment by jpgoelz** [comment]
FYI (offtopic) - The PrimeNG template provided in the bug report template seems to be broken. Without changing anything, it does create a valid angular application. I tried everything and in the end it said `Error: NG0908: In this configuration Angular requires Zone.js`. That's when I gave up on the template.

**Comment by jpgoelz** [comment]
Possibly already fixed by PR https://github.com/primefaces/primeng/pull/13881.

**Comment by cetincakiroglu** [comment]
Thanks for reporting, closing the issue since it's already fixed.
