### ISSUE TITLE
Dropdown: add class customization to input class

### ISSUE THREAD

**Issue by cfasol** [primefaces/primeng#13898]
### Describe the feature you would like to see added

in my project use primeng input component with size sm.
when I use dropdown the apparence, especially the high  is different. 
I can solve with CSS but in my point of view is a work around of problem
I d like have a property to specify my custom css class to input inside a DropDown.

### Describe the solution you'd like

To solve this behaviour I propose to add a new property "inputStyleClass" this value will be added to current class to input css class.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
