### ISSUE TITLE
SelectButton: Default behavior is broken (and the PrimeNG SelectButton demo is also broke)

### ISSUE THREAD

**Issue by rosenthalj** [primefaces/primeng#13907]
### Describe the bug

The default behavior of the SelectButton was broken when new feature (SelectButton: Add allowEmpty property #13853) was implemented.

Also, the SelectButton PrimeNG demo is now broke. 

The first video is showing the PrimeNG v15.4.9-lts PrimeNG SelectButton demo working properly

https://github.com/primefaces/primeng/assets/45439491/55594b6d-c293-4cfd-8b41-9949878956e2

The second video is showing the current PrimeNG SelectButton demo broken.

https://github.com/primefaces/primeng/assets/45439491/cedec6ef-863e-4ec9-adea-c5daa0389825

**Workaround:  For all legacy code  (including the PrimeNG SelectButton demo) set allowEmpty property to false**

### Environment

mac os and windows

### Reproducer

https://primeng.org/selectbutton

### Angular version

16.x

### PrimeNG version

16.5.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.1

### Browser(s)

safari, chrome, firefox

### Steps to reproduce the behavior

1.  Go to the current PrimeNG SelectButton Demo:  https://primeng.org/selectbutton
2. Go to the "Basic" SelectButton Example
3. The "Off" button will be blue, which indicates it is in a "selected" state
4. Click the "Off" button
5. The "Off" button will turn white and the "On" button will remain white.  Note:  both buttons will be be in an "unselected" state 

### Expected behavior

After step 4,  the "Off" button should have remained blue (and in a "selected" state)

**Comment by martin-kasa-swissre** [comment]
Thanks, for the reply. I am not saying it is a bug, I am just saying it would just be better to have default value for allowEmpty set to false, so it would not be breaking change. But I understand it is too late for that.
