### ISSUE TITLE
[DataTable] export to csv still not handling commas - csv should be quoted

### ISSUE THREAD

**Issue by gatapia** [primefaces/primeng#1391]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

Export to csv a table with commas in the fields

**Expected behavior**

CSV should be quoted

**Please tell us about your environment:**

* **Angular version:** 2.2.1

* **PrimeNG version:** RC6
Browser: ALL

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/VZbdZfQ7SuTV87tTkbYR
