### ISSUE TITLE
Component: Panel 

### ISSUE THREAD

**Issue by ulgyd0gg** [primefaces/primeng#13914]
### Describe the feature you would like to see added

Panel will look strange when you used the footer template. because the `border-bottom-left-radius: 3px` and `border-bottom-right-radius: 3px` is used in `p-panel-content`, but not footer.

### Describe the solution you'd like

I think maybe we can isolate the `border-bottom-left-radius-radius: 3px` and `border-bottom-right-radius: 3px` in a new CSS class selector. Add to content when footer does not exist, and add to footer's container if it exists.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
