### ISSUE TITLE
PickList Reordering of multiple entries to the top or bottom

### ISSUE THREAD

**Issue by rastarubio** [primefaces/primeng#13912]
### Describe the bug

The feature "send to top" or "send to bottom" in p-pickList does not work correctly when multiple entries are selected.

### Environment

Windows

### Reproducer
Here is a simple stackblitz example:
https://stackblitz.com/edit/8ojywy?file=src%2Fapp%2Fdemo%2Fpicklist-basic-demo.html

_No response_

### Angular version

15.2.5

### PrimeNG version

15.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.1.0

### Steps to reproduce the behavior

**Precondition:**

- We have a PrimeNG Picklist with 4 entries in the order 
entry_1 
entry_2 
entry_3 
entry_4

**Steps to reproduce:**
1. Multiselect entry_3 and entry_4.
2. Move the selected entries to the very top. Use the "button move to top".
3. Check Order

**Actual Result:** 
entry_4
entry_3
entry_1
entry_2 

### Expected behavior

**Expected Result:**
entry_3
entry_4
entry_1
entry_2

**Comment by ashikjs** [comment]
Can you create a example

**Comment by rastarubio** [comment]
Done. Description updated with stackblitz link.
