### ISSUE TITLE
Toast: Toast only takes pi icons

### ISSUE THREAD

**Issue by SimonJ-DR** [primefaces/primeng#13915]
### Describe the bug

https://github.com/primefaces/primeng/blob/master/src/app/components/toast/toast.ts#L55

This line prevents font awesome icons from working. (The 'pi' class)

### Environment

Unrelated

### Angular version

16.2.9

### PrimeNG version

16.5.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.5.1

### Steps to reproduce the behavior

1. add toast
2. enter fa icon
3. look

### Expected behavior

Custom icons to be allowed

**Comment by cetincakiroglu** [comment]
Hi,

You can use headless template option and customize the everything in the toast as you wish.
