### ISSUE TITLE
Calendar: the calendar disables the year if minDate is set to the current month

### ISSUE THREAD

**Issue by alexandergu** [primefaces/primeng#13919]
### Describe the bug

If **minDate** is set to a date later than the current one, the Calendar disables the entire year for selection.

### Environment

Local Setup, Mac OS
Angular CLI: 16.2.0

### Angular version

16.2.0

### PrimeNG version

16.5.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.20.0

### Browser(s)

All

### Steps to reproduce the behavior

1. Set minDate to a date greater than the current one.
2. Select the calendar
3. Switch to year
4. Try to select the year that is set in minDate

### Expected behavior

The year is available for selection even if minDate is far in the future compared to the current date

**Comment by cnaess-te** [comment]
See https://github.com/primefaces/primeng/issues/13826 for reproducer
(https://stackblitz.com/edit/dlwhy3?file=src%2Fapp%2Fdemo%2Fcalendar-minmax-demo.ts)

**Comment by tomascap-fly** [comment]
Hi,

can I kindly ask whether there's any estimate for when the above PR could be merged? We need this fix rather urgently.


Thanks!

Tomas
