### ISSUE TITLE
PrimeNG : SideBar onHide Not trigger

### ISSUE THREAD

**Issue by RajdeepsinhBhatti** [primefaces/primeng#13933]
### Describe the bug

After upgrading prime ng 14 to 16 version sidebar not working properly

when sidebar visible variable value change to false at that time onHide not trigger  

### Environment

Production

### Reproducer

https://stackblitz.com/edit/mkdqss

### Angular version

16.2.0

### PrimeNG version

16.5.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.0

### Steps to reproduce the behavior

when sidebar visible variable value change to false at that time onHide not trigger  

### Expected behavior

it should be trigger when variable value change to false from true

**Comment by maruthumj** [comment]
@RajdeepsinhBhatti I will take this one.

**Comment by mehmetcetin01140** [comment]
Hi,

The solution in this pr ( #13959 ) leads to multiple triggers of the hide function and causes other bugs.

**Comment by clopez1winsupply** [comment]
Was this fix ever tested? I took primeng 16.9.1 and it is still broken, even when I use primeng 17 it is broken too.
