### ISSUE TITLE
TriStateCheckboxComponent: inputId not working

### ISSUE THREAD

**Issue by amgalitzky** [primefaces/primeng#13946]
### Describe the bug

on the TriStateCheckbox when you have a label with a  `for` & a TriStateCheckbox with an `inputId` when clicking on the label it won't toggle the checkbox state it only shows the focus of the checkbox. 

### Environment

I use "primeng": "^16.2.0",
You can see the bug on your documentation preview:
https://primeng.org/tristatecheckbox#reactive-forms

### Angular version

16.2.0

### PrimeNG version

16.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

19

**Comment by SoyDiego** [comment]
HI @amgalitzky.
I did a PR solving the problem and updating the docs.
You can check here: https://github.com/primefaces/primeng/pull/13977

Thanks!
