### ISSUE TITLE
Panelmenu: Blinking "focus" on first menu item

### ISSUE THREAD

**Issue by lmormol** [primefaces/primeng#13940]
### Describe the bug

There is an issue with blinking focus after clicking in any menu item. For a moment .p-focus is set on first menu item.

Here you can see incorrect behaviour:

https://drive.google.com/file/d/1TLmJ_U1S4va7NYzEbAJRiklLwNHmO3ah/view?usp=sharing

### Environment

Mac os Apple M2
Sonoma 14

### Angular version

16.2.3

### PrimeNG version

16.5.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.17.1

### Browser(s)

Latests: Chrome, Opera, Safari

### Steps to reproduce the behavior

1. Go to Basic panel menu.
2. Expand "Edit" group menu item.
3. Start clicking on Left / Center / Right or Justify sub-items.
4. Observe that for a moment focus is incorrectly set on a first menu item in this case "Left". 

### Expected behavior

"Focus" should be set on menu item which was clicked.

**Comment by jermylucas** [comment]
Thanks for pointing this out. It's not a great visual behavior...

**Comment by lmormol** [comment]
No big deal, thanks for fixing the issues! 

Please have a look also at [this one](https://github.com/primefaces/primeng/issues/13630) in a spare moment.

Have a nice day!

**Comment by jermylucas** [comment]
@cetincakiroglu  This is fixed with issue #14236

**Comment by cetincakiroglu** [comment]
Closing the issue since it's already fixed.

**Comment by alejandrobiker** [comment]
The error continued, was it resolved?
