### ISSUE TITLE
Component: MultiSelect ExpressionChangedAfterItHasBeenCheckedError when spam clicking

### ISSUE THREAD

**Issue by nathanvj** [primefaces/primeng#13942]
### Describe the bug

When you spam click on the MultiSelect input to open the options, you get the following error in console. 

_ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'. Expression location: MultiSelect component._

See here:
<img width="859" alt="Screenshot 2023-10-23 at 12 28 43" src="https://github.com/primefaces/primeng/assets/26263426/01ccb188-5948-46ed-806e-707f28c0e391">

### Environment

N/A

### Reproducer

https://stackblitz.com/edit/c75mkf?file=package.json

### Angular version

16.2.0

### PrimeNG version

16.5.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

n/a

### Steps to reproduce the behavior

1. Open the StackBlitz
2. Spam click on the MultiSelect a couple times
3. Check console (only visible in a dev environment)

### Expected behavior

To not have the errors in console

**Comment by maruthumj** [comment]
I'm taking this  one and also this will be my first contribution to the open source world!

**Comment by turp** [comment]
Unfortunately, this doesn't fix the issue. Please see https://stackblitz.com/edit/dtvhna?file=src%2Fapp%2Fdemo%2Fmulti-select-virtual-scroll-demo.html,package.json and quickly click multiple times on the multiselect dropdown.

I thought that by adding [virtualScroll]="true" might do the trick, but it doesn't seem to affect the behavior
