### ISSUE TITLE
Component: ContextMenu with appendTo="body" doesn't close when destroyed

### ISSUE THREAD

**Issue by brio1009** [primefaces/primeng#13948]
### Describe the bug

When using a context menu with appendTo="body", the opened context menu stays open even if the context menu component is destroyed/removed.

### Environment

Windows + Chrome

### Reproducer

https://stackblitz.com/edit/yfrjgh?file=src%2Fapp%2Fdemo%2Fcontext-menu-document-demo.html

### Angular version

16.2.0

### PrimeNG version

16.5.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.0

### Steps to reproduce the behavior

1. Go to the Stackblitz example
2. Click `Show menu appended to body` and `Show menu not appended to body`. Now, two context menus should be open.
3. Click `Destroy context menu component`
4. Notice that the `Appended to body` context menu stays open

### Expected behavior

The context menu with appendTo="body" should also be removed.

**Comment by eXpertise7** [comment]
@brio1009 This might be related: https://github.com/orgs/primefaces/discussions/161

I'm opening issue for ContextMenu issue now also.

**Comment by brio1009** [comment]
Similar to #13949, this issue is probably related to #13936

**Comment by maruthumj** [comment]
Hi @brio1009 I will work on this.

**Comment by maruthumj** [comment]
In the below video you can see that this issue got resolved by the changes that I have pushed into the linked Pullrequest.
https://github.com/primefaces/primeng/assets/32091483/9789a4af-6373-47fc-a152-5bf070dd628f

**Comment by brio1009** [comment]
Thanks for the fast response + fix release :)
