### ISSUE TITLE
Dropdown: keyboard trap

### ISSUE THREAD

**Issue by bmayen** [primefaces/primeng#13944]
### Describe the bug

When users navigate to a Dropdown with the keyboard, it traps keyboard focus. https://primeng.org/dropdown

This critically breaks accessibility as there is no way to navigate further after accessing a Dropdown.

### Environment

v16

### Reproducer

https://primeng.org/dropdown

### Angular version

^16

### PrimeNG version

^16

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Steps to reproduce the behavior

Use keyboard to navigate to a Dropdown. Cannot navigate forward or back after Dropdown is focused. Keyboard is trapped.

### Expected behavior

Dropdown releases focus and allows users to navigate forward or back after being focused.

**Comment by cetincakiroglu** [comment]
Hi,

Dropdown received a massive refactor & rework during the accessibility implementation in v16.7, keyboard support is updated also. Mentioned issue probably fixed and doesn't exist in v17. If the issue persists, please create a new issue for it. 

Thanks for the report!

Closing the issue.
