### ISSUE TITLE
Component: panelMenu bugs dropdown in sidepanel after reopening

### ISSUE THREAD

**Issue by HackingLutz** [primefaces/primeng#13951]
### Describe the bug

In out application we use the PanelMenu inside a SidePanel Component as our Usermenu. If you open the SidePanel right after initial loading of the page you are on and choose to open a Menuitem inside a dropdown of the PanelMenu it loads just fine, but after closing the sidepanel and open the dropdown item again there is a visual bug.

![image](https://github.com/primefaces/primeng/assets/5261735/a78daa44-82e1-4872-8fd5-02fa664fdada)

### Environment

Running node locally on my computer and use Angular / Primeng. The identified problem is only within PrimeNg/Angular.

### Angular version

16.2.7

### PrimeNG version

16.5.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v18.3.0

### Browser(s)

Chrome, Firefox, Safari, Edge

### Steps to reproduce the behavior

1. Refresh site (CTRL+F5)
2. Open sidebar
3. Expand "Clean up"
4. Collapse "Clean up"
5. Close sidebar
6. Open sidebar
7. Expand "Clean up"

**Comment by jermylucas** [comment]
I had a similar issue once but it's extremely difficult to diagnose without a reproducible product. Can you provide it? 
Does your p-panelMenu have the [multiple]="true" set?
