### ISSUE TITLE
Minimize Dialog

### ISSUE THREAD

**Issue by carlo1010** [primefaces/primeng#13958]
### Describe the feature you would like to see added

The function I'm requesting is the minimization of dialogs as happens on primeface jsf

https://www.primefaces.org/showcase/ui/overlay/dialog.xhtml?jfwid=85e3b

### Is your feature request related to a problem?

when creating entrerprice applications I often need to display more panels,

with this function I can have multiple panels at hand without having to search for all the sections I need every time

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
