### ISSUE TITLE
Component: Dialog - Custom Positioning Support

### ISSUE THREAD

**Issue by AldoAbdiel** [primefaces/primeng#13966]
### Describe the feature you would like to see added

I propose enhancing the Dialog component by adding a new property or expanding the existing one to handle more complex positioning based on coordinates "X" and "Y". Currently, the Dialog component offers fixed position options like "center," "left," "top," "bottom," "right," "topleft," "topright," "bottomleft," and "bottomright."

### Is your feature request related to a problem?

The current fixed position options limit the flexibility of instantiating the dialog precisely based on specific coordinates, hindering the ability to position the dialog dynamically.

### Describe the solution you'd like

I suggest introducing a new property to the openDialog function. This property would accept an object with "x" and "y" coordinates. The dialog position would then be dynamically centered on the screen based on these provided coordinates, offering more precise control over its placement.

### Describe alternatives you have considered

I have considered using the component OverlayPanel, but this one also doesn't fit the need described.

### Additional context

No response

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
