### ISSUE TITLE
Datatable column template and expandable rows

### ISSUE THREAD

**Issue by tigrenok00** [primefaces/primeng#1396]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

Hi

I have a table with expandable rows, the expansion template displays an inner table. 
Everything works perfectly, including the expansion, **until** I add a column **template** to the outer table - see column "custPrice". 
It the custPrice row is displayed correctly, incuding the value, but when I click to expand the row - I get the following error:

> EXCEPTION: Error in ./PlanDataComponent class PlanDataComponent - inline template:169:61 caused by: Cannot read property 'custPrice' of undefined

```
<p-dataTable [value]="planData.custLvl" class="small" expandableRows="true" tableStyleClass="my-table" [editable]="true">
          <p-column expander="true" styleClass="col-icon"></p-column>
          <p-column field="element.text" header=" " styleClass="col-item"></p-column>
          <p-column field="netPrice" header="xxx" styleClass="row-regular"></p-column>
          <p-column field="discountPct" header="xxx" styleClass="row-regular-editable">
          </p-column>
          <p-column field="custPrice" header="xxx" styleClass="row-regular-editable">
           <template let-el1="rowData" pTemplate type="body">
                 {{el1.custPrice}}
            </template>
          </p-column>
          <p-column field="posPrice" header="xxx" styleClass="row-regular-editable" [editable]="true"></p-column>
          <p-column field="baseFcst" header="xxx" styleClass="row-regular"></p-column>
          <p-column field="upliftPct" header="xxx" styleClass="row-regular-editable" [editable]="true"></p-column>
          <p-column field="upliftUnit" header="xxx" styleClass="row-regular"></p-column>
          <p-column field="totalFcst" header="xxx" styleClass="row-regular"></p-column>
          <p-column field="plnCost" header="xxx" styleClass="row-regular"></p-column>
          <p-column field="startDate" header="xxx" styleClass="row-regular"></p-column>
          <p-column field="endDate" header="xxx" styleClass="row-regular"></p-column>

         <template let-cust>
            <p-dataTable [value]="cust.items" tableStyleClass="inner-table" [editable]="true">
              <p-column field="element.text" header=" " styleClass="col-item-inner"></p-column>
              <p-column field="netPrice" header="xxx" styleClass="row-inner"></p-column>
              <p-column field="discountPct" header="xxx" styleClass="row-inner-editable"></p-column>
              <p-column field="custPrice" header="xxx" styleClass="row-inner-editable" [editable]="true"></p-column>
              <p-column field="posPrice" header="xxx" styleClass="row-inner-editable" [editable]="true"></p-column>
              <p-column field="baseFcst" header="xxx" styleClass="row-inner"></p-column>
              <p-column field="upliftPct" header="xxx" styleClass="row-inner-editable" [editable]="true"></p-column>
              <p-column field="upliftUnit" header="xxx'" styleClass="row-inner"></p-column>
              <p-column field="totalFcst" header="xxx" styleClass="row-inner"></p-column>
              <p-column field="plnCost" header="xxx" styleClass="row-inner"></p-column>
              <p-column field="startDate" header="xxx" styleClass="row-inner-editable" [editable]="true"></p-column>
              <p-column field="endDate" header="xxx" styleClass="row-inner-editable" [editable]="true"></p-column>
            </p-dataTable>
          </template>

        </p-dataTable>
```

* **Angular version:** 2.0.X
~2.1.0

* **PrimeNG version:** 2.0.X
1.0.0-rc.4

* **Browser:** [all]

**Comment by ribizli** [comment]
This is still the same issue from #966. 
See also #1366 for an other strange problem.

**Comment by cagataycivici** [comment]
You need to use;

{code}
<p-dataTable [value]="planData.custLvl" class="small" expandableRows="true" tableStyleClass="my-table" [editable]="true">
<template let-cust>
            <p-dataTable [value]="cust.items" tableStyleClass="inner-table" [editable]="true">
              <p-column field="element.text" header=" " styleClass="col-item-inner"></p-column>
              <p-column field="netPrice" header="xxx" styleClass="row-inner"></p-column>
              <p-column field="discountPct" header="xxx" styleClass="row-inner-editable"></p-column>
              <p-column field="custPrice" header="xxx" styleClass="row-inner-editable" [editable]="true"></p-column>
              <p-column field="posPrice" header="xxx" styleClass="row-inner-editable" [editable]="true"></p-column>
              <p-column field="baseFcst" header="xxx" styleClass="row-inner"></p-column>
              <p-column field="upliftPct" header="xxx" styleClass="row-inner-editable" [editable]="true"></p-column>
              <p-column field="upliftUnit" header="xxx'" styleClass="row-inner"></p-column>
              <p-column field="totalFcst" header="xxx" styleClass="row-inner"></p-column>
              <p-column field="plnCost" header="xxx" styleClass="row-inner"></p-column>
              <p-column field="startDate" header="xxx" styleClass="row-inner-editable" [editable]="true"></p-column>
              <p-column field="endDate" header="xxx" styleClass="row-inner-editable" [editable]="true"></p-column>
            </p-dataTable>
          </template>

          <p-column expander="true" styleClass="col-icon"></p-column>
          <p-column field="element.text" header=" " styleClass="col-item"></p-column>
          <p-column field="netPrice" header="xxx" styleClass="row-regular"></p-column>
          <p-column field="discountPct" header="xxx" styleClass="row-regular-editable">
          </p-column>
          <p-column field="custPrice" header="xxx" styleClass="row-regular-editable">
           <template let-el1="rowData" pTemplate type="body">
                 {{el1.custPrice}}
            </template>
          </p-column>
          <p-column field="posPrice" header="xxx" styleClass="row-regular-editable" [editable]="true"></p-column>
          <p-column field="baseFcst" header="xxx" styleClass="row-regular"></p-column>
          <p-column field="upliftPct" header="xxx" styleClass="row-regular-editable" [editable]="true"></p-column>
          <p-column field="upliftUnit" header="xxx" styleClass="row-regular"></p-column>
          <p-column field="totalFcst" header="xxx" styleClass="row-regular"></p-column>
          <p-column field="plnCost" header="xxx" styleClass="row-regular"></p-column>
          <p-column field="startDate" header="xxx" styleClass="row-regular"></p-column>
          <p-column field="endDate" header="xxx" styleClass="row-regular"></p-column>

        </p-dataTable>
{code}

**Comment by cagataycivici** [comment]
Location does not matter in 1.0 final though.

**Comment by tigrenok00** [comment]
Awesome, thanks a lot

**Comment by ribizli** [comment]
With your current solution (which I haven't tested btw) you take the first child, so location indeed matters.

**Comment by ilianiv** [comment]
I am afraid of this, too https://github.com/primefaces/primeng/commit/7b20941cb71196047f5919bd66b66cfeb5f3ba5d#commitcomment-19920597
