### ISSUE TITLE
Component: Carousel

### ISSUE THREAD

**Issue by ibrahimkelly** [primefaces/primeng#13978]
### Describe the feature you would like to see added

I'd like to make a custom list [1,2,3] for custom content, but not worked

`<p-carousel [value]="[1, 2, 3]" [numVisible]="3" [numScroll]="3" [circular]="true">
  <ng-template pTemplate="item">
    <div class="carousel-item">
      <img src="https://example.com/images/1.png" alt="Image 1">
      <h3>Image 1</h3>
      <p>This is the first image in the carousel.</p>
    </div>
  </ng-template>
  <ng-template pTemplate="item">
    <div class="carousel-item">
      <img src="https://example.com/images/2.png" alt="Image 2">
      <h3>Image 2</h3>
      <p>This is the second image in the carousel.</p>
    </div>
  </ng-template>
  <ng-template pTemplate="item">
    <div class="carousel-item">
      <img src="https://example.com/images/3.png" alt="Image 3">
      <h3>Image 3</h3>
      <p>This is the third image in the carousel.</p>
    </div>
  </ng-template>
</p-carousel>`

### Is your feature request related to a problem?

With the Carousel custom list

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
