### ISSUE TITLE
Component: Tree - ERROR RangeError: Maximum call stack size exceeded at Tree.propagateUp

### ISSUE THREAD

**Issue by kazakevich-alexei** [primefaces/primeng#13976]
### Describe the bug

component Tree - ERROR RangeError: Maximum call stack size exceeded    at Tree.propagateUp

For the p-tree component, [filter]="true" , SelectionMode="checkbox" are set.
There are approximately 1000 elements in the [value] data source, with a maximum nesting of 3 levels

A value is entered in the filter field and the result is received.
When clicking on any node, an error occurs as a result

![image](https://github.com/primefaces/primeng/assets/60583226/9aceb364-e03f-47cb-82e6-0f3556ca4e18)

### Environment

windows 11, Webstorm

### Angular version

16.2.6

### PrimeNG version

16.5.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.1

### Steps to reproduce the behavior

For the p-tree component, [filter]="true" , SelectionMode="checkbox" are set.
A value is entered in the filter field and the result is received.
When clicking on any node, an error occurs as a result

**Comment by rolandtoth** [comment]
Experiencing this with PrimeNG v17.9.0 too, with only 6 items. This issue makes the search function entirely unusable.

Also when searching, selected checkboxes became unselected, but that's probably another issue.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
