### ISSUE TITLE
refresh does not work

### ISSUE THREAD

**Issue by Danieleeee** [primefaces/primeng#1397]
**I'm submitting a ...**
bug report

**Current behavior**
reloading data, from http, of charts and tables (with expandableRows) don't work.
chart animation (reloading) don't work.

**Expected behavior**
reloading data you can see the updates, animation.

* **Angular version:** 2.2.1

* **PrimeNG version:** RC6

* **Browser:** Chrome (latest), IE 11
 
* **Language:** [ TypeScript 2.0.10 | ES5]

**Comment by cagataycivici** [comment]
Change detection is not supported by charts, you need to call refresh() method in 1.0 final manually on chart component.

**Comment by Danieleeee** [comment]
I'm not talking about change detection.
I load the chart data from a function, like loadData(). If I recall this function to update the data, nothing happens. the same behavior in expandableRows. It works only the first time.
In RC4 it worked correctly.

**Comment by albertosramires** [comment]
@cagataycivici I'm on the same boat as @Danieleeee, I want to load data dynamically from an API and I can't make the user update the data manually. In your latest [showcase](https://raw.githubusercontent.com/primefaces/primeng/master/showcase/demo/chart/chartdemo.html) you call the refresh method by referencing a view reference, that's fine if you're calling it manually through a button like the example (even though it doesn't seem to work anyway) but how do you suggest we do this dynamically?
