### ISSUE TITLE
Multiselect set value error v16.7.0

### ISSUE THREAD

**Issue by macallejah** [primefaces/primeng#13999]
### Describe the bug

I set a value of a multiselect through a form (patchValue), and the value is not set. In version 16.6.0 it works perfectly

### Environment

multiselect

### Angular version

16.2.9

### PrimeNG version

16.7.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.1

### Expected behavior

When you set the value to be displayed in the component

Note:
This function (multiselect.ts: 1775) does not take the value of the input. It may be one of the problems

     writeValue(value: any): void {
        this.value = this.modelValue(); 
        this.updateModel(this.value);
        this.checkSelectionLimit();

        this.cd.markForCheck();
    }

**Comment by ZephyrZiggurat** [comment]
Our multiselects are not respecting a default list of items that should be pre-selected. They worked perfect in 16.6.0 but not in 16.7.0.

The code looks similar to this old example (that I no longer see in the docs):

```
<p-multiSelect [options]="cars" [(ngModel)]="selectedCars">
</p-multiSelect>

cars = [
    {label: 'Audi', value: 'Audi'},
    {label: 'BMW', value: 'BMW'},
    {label: 'Fiat', value: 'Fiat'}
]
selectedCars=[cars[0].value]
```

**Comment by mperezd** [comment]
Stackblitz example showing patchValue is not working:

[https://stackblitz.com/edit/srtdud?file=src%2Fapp%2Fdemo%2Fmulti-select-reactive-forms-demo.ts](url)

**Comment by cetincakiroglu** [comment]
Hi,

Thanks for reporting the issue, we've reworked the input components during the accessibility implementation and this issue is probably related to this process.
