### ISSUE TITLE
onClick event listbox error v16.7.0

### ISSUE THREAD

**Issue by macallejah** [primefaces/primeng#13998]
### Describe the bug

Event is not emitted when you select an element from list.

### Environment

listbox 

### Angular version

16.2.9

### PrimeNG version

16.7.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.1

### Expected behavior

In version 16.6.0 the event was emitted correctly

**Comment by cetincakiroglu** [comment]
Hi,

With version 16.7.0, we have released the first part of the accessibility implementation for inputs that we have been working on for a long time. Based on the research we conducted during the implementation, we decided that many components needed changes in their structure and simplification, and these components were rewritten. Unfortunately, after extensive testing, there may be unexpected and unforeseen bugs that have emerged. We are grateful for your reports, and we are working to address them in the upcoming release!
