### ISSUE TITLE
p-image-preview-indicator rendered when preview is false

### ISSUE THREAD

**Issue by leykee** [primefaces/primeng#14002]
### Describe the bug

Image with `preview: false` show the p-image-preview-indicator, but should not.
When inspecting our page, that image indicator mask is covering the whole page, making it impossible to inspect any elements without deleting the dom node everytime.
I checked the code and this commit seems to have introduced the regression: https://github.com/primefaces/primeng/commit/162d1997280c609806921df1197cc6bb9ac7eff6

### Environment

PrimeNG 16.6

### Angular version

16.2.0

### PrimeNG version

16.6.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.17

**Comment by francopan** [comment]
I would also add that when the user clicks on the image when [preview]="true", it is adding "p-overflow-hidden" to body in order to show the preview. However, if you have a click event to redirect, when the user clicks the image, it will get redirected and the preview is not shown, which is correct, but the class is still applied.

Example below.

```html
<div (click)="onClick()">
    <p-image [src]="src" [height]="height + 'px'" [width]="width + 'px'" [preview]="preview">
    </p-image>
    <span>{{person.name}}</span>
</div>
```

```typescript
@Component({
  selector: 'app-person-photo',
  templateUrl: './person-photo.component.html',
  styleUrls: ['./person-photo.component.scss'],
})
export class PersonPhotoComponent {
  @Input() includeName = true;
  ...
  @Input() public preview = true
  public src: string | undefined;
  private _person: PersonCredit | Person | undefined;

  @Input() set person(person: PersonCredit | Person | undefined) {
    this._person = person;
    if (this._person?.profile_path) {
      this.src = `${api_url.image}/w${this.width}_and_h${this.height}_face/${this._person?.profile_path}`;
    }
  }

  public get person(): PersonCredit | Person | undefined {
    return this._person;
  }

  public onClick() {
    if (this._person) {
      this.clicked.next(this._person);
    }
  }
}
```
