### ISSUE TITLE
Component: textArea with pInputTextArea and AutoResize=true scroll issue

### ISSUE THREAD

**Issue by erber014** [primefaces/primeng#14003]
### Describe the bug

When using <textarea> with pInputTextArea and [autoResize]=true in a sidebar with a scrollbar there is an issue where the sidebar will get scrolled when the textarea is interacted with and a user tries to interact with other elements in the sidebar. See reproducer below.

### Environment

Using windows 10 and latest version of Firefox.

### Reproducer

https://stackblitz.com/edit/mffv5p?file=src%2Fapp%2Fdemo%2Finput-textarea-auto-resize-demo.html

### Angular version

16.2.0

### PrimeNG version

16.5.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.0

### Steps to reproduce the behavior

Go to reproducer stackblitz.
1. Open sidebar.
2. Put focus on the textarea or button in sidebar.
3. Scroll down and try clicking on the button at the bottom.
The button will not be clicked and we will instead scroll up in the sidebar. User will need to scroll down manually and then click the button one more time which is annoying

### Expected behavior

I expect to be able to interact with page elements in sidebar with a textarea even when textarea is focused.

**Comment by sandrotonon** [comment]
Also reproducable with Version 16.6.0.

**Comment by stephanebouget** [comment]
waiting for a fix, this lib do the job : https://www.npmjs.com/package/ngx-autosize

**Comment by Metal079** [comment]
This issue seems fixed with the latest version

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
