### ISSUE TITLE
Bug datatable expander template RC7

### ISSUE THREAD

**Issue by MarcGK** [primefaces/primeng#1400]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**

Since the upgrade to RC7 the expander template in the datatable component doesn't work anymore. Only the first time I open an expander, it shows the data. The next expander is empty and all template vars I want to lookup are undefined. 
I traced it down to the use of *ngFor in the expander template. It could be that the last commit to datatable.ts, https://github.com/primefaces/primeng/commit/7b20941cb71196047f5919bd66b66cfeb5f3ba5d#diff-693f413104a81c421843ae657f5a6d09
where template.first is introduced, conflicts with the "first" var that *ngFor sets.
(What I should do is download the primeng git  source and test it (in the npm install I cannot find datatable.ts) but after many hours tracing this bug down I leave it to you !
Maybe you could point me to instructions how to use the primeng git repository and directly edit the ts files in my local node_packages directory, ot how to roll back to previous releases.)

**Minimal reproduction of the problem with instructions**
Use *ngFor in an expander template of a datatable

* **Angular version:** 2.1.2

* **PrimeNG version:** 1.0.0-RC7

* **Browser:** [all ]

**Comment by srllemo** [comment]
We have same problem with same issue using ngFor in template works only when first time expanded, every next expand shows only empty space.  
Angular 2.2.1
PrimeNG 1.0.0-RC5

 same problem with PrimeNG 1.0.0-RC6 too.

**Comment by MarcGK** [comment]
Extra info, I stripped down my template and reduced it to the following test data:

Inside my component:
```
        this.dummycols = [{ "fieldname": "id" }, { "fieldname": "name" }];
        this.dummydata = [{ "id": "1", "name": "Name 1" }, { "id": "2", "name": "Name 2" }];
```
template:
  Data Table bug with ngFor. Rowdata empty after second expand.
```
  <p-dataTable [value]="dummydata" expandableRows="true">
                  <template let-mydata > 
                    <div> 
                      RowData: {{mydata | json }}
                    </div>
                    <div class="ui-grid-col-9">
                            <div class="ui-grid ui-grid-responsive ui-grid-pad">
                               <div *ngFor="let mycol of dummycols" class="ui-grid-row"> 
                                 Data: {{mydata[mycol.fieldname]}}
                               </div>
                            </div>
                    </div>
                  </template>
                  <p-column expander="true" styleClass="col-icon" [style]="{'width':'30px'}"></p-column>
                  <p-column field="_id" [header]="ID"></p-column>
                  <p-column field="name" [header]="NAME"></p-column>
  </p-dataTable>
  <div>
    <span>dymmydata {{dummydata | json }} </span>
    <span>dymmydata {{dummycols | json }} </span>
  </div>
  Data Table bug withhout ngFor
  <p-dataTable [value]="dummydata" expandableRows="true">
                  <template let-mydata > 
                    <div> 
                      RowData: {{mydata | json }}
                    </div>
                  </template>
                  <p-column expander="true" styleClass="col-icon" [style]="{'width':'30px'}"></p-column>
                  <p-column field="_id" [header]="ID"></p-column>
                  <p-column field="name" [header]="NAME"></p-column>
  </p-dataTable>
```

Rowdata is vanished after the second expand.

**Comment by MarcGK** [comment]
Ahhhh, according my packages.json I have angular 2.1.2. I checked the logs again and it looks like that a npm upgrade gone wrong and installed angular 2.2.1. I will install angular 2.1.2. again and will report if it starts working again.

**Comment by MarcGK** [comment]
With a downgrade to Angular 2.1.2, everythings works again, sorry for the confusion.
