### ISSUE TITLE
Global filter to search tree-table is not returning all the relevant results

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primeng#14016]
Reported By PRO User;
> Global filter to search tree-table is not returning all the relevant results.
It searches only one column at a time.
We ran the demo for prime-ng v16 filter(https://primeng.org/treetable#filter) with a small subset of data and tried the search there to confirm that other component logics are not interfering with the search results.
Here is a demo page: PrimeNG TreeTableFilterDemo - StackBlitz
In the demo page, if we search with last name Weasley it only returns 4 results instead of 6.

**Comment by zakharenkov** [comment]
I [described](https://github.com/primefaces/primeng/issues/12155) a similar problem, but at that time no one heard me.
But better late than never :)
