### ISSUE TITLE
p-tooltip : autohide="false" does not work every times

### ISSUE THREAD

**Issue by stephanebouget** [primefaces/primeng#14014]
### Describe the bug

**add [autohide]="false" to the p-tooltip component and hover it from the arrow carret element**

### It doen't works when mouse hover the tooltip by the carret arrow : 
![ko](https://github.com/primefaces/primeng/assets/13203455/24e4f91e-3478-4f03-bf75-0cc72f77a43d)

### It works when mouse hover the tooltip directly (by the bottom or top of the tooltip) : 
![ok](https://github.com/primefaces/primeng/assets/13203455/b75b5952-ad4a-4579-bbcb-a8ab77ea4c13)

### Environment

primeng 16.7.0

### Angular version

16

### PrimeNG version

16.7.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

**Comment by maruthumj** [comment]
Hi @stephanebouget can you please provide the reproducible stackblitz sample app?

**Comment by Bra7wurs7** [comment]
I have this same problem. Maybe I'll have time to setup a Stackblitz example the next month or so. Can't earlier, sorry.

**Comment by stephanebouget** [comment]
> Hi @stephanebouget can you please provide the reproducible stackblitz sample app?

No need a stackblitz. You Can reproduce it directly here: https://primeng.org/tooltip

**Comment by maruthumj** [comment]
@stephanebouget I have fixed the issue in the linked PR

**Comment by stephanebouget** [comment]
tested OK in 18.0.0. TY!
