### ISSUE TITLE
Downgrade PrimeNG not help 

### ISSUE THREAD

**Issue by ja74687** [primefaces/primeng#14017]
### Describe the bug

@cetincakiroglu 
Hey when I downgrade PrimeNG to 16.5 I have similar problem like in version 16.7, but when i downgrade to 16.0.2 problem was resolved :) That weird.

### Environment

Angular 16

### Angular version

16

### PrimeNG version

16*

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.14.2

**Comment by cetincakiroglu** [comment]
This issue is invalid, please open a new issue by actually describing the issue. It's not clear what's going on from this.
