### ISSUE TITLE
p-tag: styleClass input not working

### ISSUE THREAD

**Issue by lixaotec** [primefaces/primeng#14020]
### Describe the bug

I´m trying to add custom color to tag just by adding new classes, and it seems the Input styleClass is not working, because i does not pass the classes i´ve entered

### Environment

v16.6.0

### Angular version

16

### PrimeNG version

16.6

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

latest

### Expected behavior

<span class that receives [class]="styleClass" should work.
Maybe its conclifting with the [ngClass]="computeClass()" that decides the severity

**Comment by lixaotec** [comment]
Also, it does not supports custom Severity... i think that would be great to accepts a custom severity

lets say: p-tag-{severity}
p-tag-plain
p-tag-ok

The whole concept of severity for all components could be more flexible

**Comment by mehmetcetin01140** [comment]
Could you please share a stackblitz reproducer?
