### ISSUE TITLE
The ngModel directive can't set an item of dropdown in version 16.7.0

### ISSUE THREAD

**Issue by ailtonbsj** [primefaces/primeng#14023]
### Describe the bug

If the p-dropdown component was set with ngModel when value will be changed, it don't affect state of this component. If you downgrade to 16.6.0 start to work well.

![issue](https://github.com/primefaces/primeng/assets/5393895/b029007e-95fd-43a5-80c5-ef0c240d104f)
[Tested here](https://github-3qqjb4.stackblitz.io)

### Environment

Using Xubuntu 22.04 LTS with Visual Code.
Using node, npm and angular-cli.

### Reproducer

https://stackblitz.com/edit/github-3qqjb4?file=src%2Fapp%2Fapp.component.ts

### Angular version

16.2.12

### PrimeNG version

16.7.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.8.1

### Browser(s)

All

### Steps to reproduce the behavior

Just click the buttons on example.

### Expected behavior

It expected change the dropdown automatically when clicked on buttons.
It expected the have the same behavior of 16.6.0.

**Comment by cetincakiroglu** [comment]
Hi,

With version 16.7.0, we have released the first part of the accessibility implementation for inputs that we have been working on for a long time. Based on the research we conducted during the implementation, we decided that many components needed changes in their structure and simplification, and these components were rewritten. Unfortunately, after extensive testing, there may be unexpected and unforeseen bugs that have emerged. We are grateful for your reports, and we are working to address them in the upcoming release!
