### ISSUE TITLE
p-toast issue with Angular 16 standalone app

### ISSUE THREAD

**Issue by Goteii** [primefaces/primeng#14028]
### Describe the bug

I wanted to implement a notification component in my Angular 16 standalone app with a p-toast just in my app.component.html to keep it DRY. As long as I directly call this.messageService.add({}) from my components its fine, even if I invoke the messageService in my service. The problem starts when I call a service from a service so a flow is: 
component -> service -> service.
In this situation I keep getting error: 
ERROR
Error: Uncaught (in promise): NullInjectorError: R3InjectorError(Standalone[RegisterComponent])[UserAuthService -> UserAuthService -> UserAuthService -> UserAuthService -> AppMessageService -> MessageService -> MessageService]:
NullInjectorError: No provider for MessageService!
NullInjectorError: R3InjectorError(Standalone[RegisterComponent])[UserAuthService -> UserAuthService -> UserAuthService -> UserAuthService -> AppMessageService -> MessageService -> MessageService]:
NullInjectorError: No provider for MessageService!

After hours of trying to work things out I managed to make a workaround based on setting a flag and toastMessageContent with signals in my last service(the most nested one) and then listen to that in effect() from my app.component.ts and display toast from there but this solution is nasty.

### Environment

Local dev env, Angular 16, standalone, signals, vscode, win10, lazy-loaded components, nx

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-pncz7d?file=src%2Fapp%2Fuser-auth%2Fregister%2Fregister.component.ts

### Angular version

16.2.0

### PrimeNG version

16.5.0

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.0

### Steps to reproduce the behavior

1. Create a standalone app
2. Install primeng
3. Import ToastModule in your app.component.ts and define p-toast in your app.component.html
4. Import "MessageService" in @Component({providers: []}) in your app.component.ts
5. Create dummy.component.ts
6. Create dummy.service.ts
7. Create dummy2.service.ts
8. dummy.component.ts should call a method from dummy.service.ts which calls method from dummy2.service.ts
9. dummy2.service.ts method should include this.messageService.add() and private messageService: MessageService in its constructor.

### Expected behavior

No console error and toast being displayed properly

**Comment by Urtgard** [comment]
I don't think this is an issue with PrimeNg.

1. Remove `providers: [AppMessageService]` from `RegisterComponent`
2. Remove `providers: [MessageService]` from `AppComponent`
3. Add `MessageService` to your prodivers array in `appConfig`

**Comment by Goteii** [comment]
Damn, it indeed works now. Thank you @Urtgard

**Comment by Ikeoh** [comment]
Guys, is the way I implemented the MessageService correct?

It didn't work for me...

![image](https://github.com/primefaces/primeng/assets/34623527/e87e1ce5-0d28-4608-98ca-2c26acb7e153)
![image](https://github.com/primefaces/primeng/assets/34623527/76f15f16-e03a-4ebe-8376-dc91f8fc79bc)

**Comment by Goteii** [comment]
Hey @Ikeoh, did you try to pass "MessageService" in appConfig without wrapping it in importProvidersFrom() method? It should work that way if you import messageService and call this.messageService.add({}) from your components. In my forked link there is already implemented solution proposed by @Urtgard which works so I can you can look up there

**Comment by caboodal** [comment]
I can confirm that adding the MessageService directly into the app.config.ts file does prevent the null injector error.

However, the messages don't seem to be appear in the p-message component, very poor documentation on this to demonstrate how it all hangs together!

**Comment by naris** [comment]
@caboodal The messages are not supposed to appear in a p-message component -- you need a p-toast component for the messages to show up, this indeed documented here --> [https://www.primefaces.org/primeng-v14-lts/toast](https://www.primefaces.org/primeng-v14-lts/toast)

**Comment by caboodal** [comment]
@naris yeah I know I got it all working in the end both messages and toasts. The documentation falls a little short in providing the complete picture. I'm finding this with all of the components.

**Comment by FlorisRHeijmans** [comment]
I have the same issue of the Toast not showing using a <p-toast/> in my component. I have stripped all code down to match the example. @caboodal Can you share the details on your fix?

**Comment by caboodal** [comment]
@FlorisRHeijmans are you sorted now?

**Comment by FlorisRHeijmans** [comment]
Yes!

**Comment by abdrhxyii** [comment]
If you are using angular version 17+
then add the MessageService and BrowserAnimationsModule in app.config.ts file in provider array.

```
export const appConfig: ApplicationConfig = {
  providers: [
    provideRouter(routes), 
    provideHttpClient(), 
    MessageService, 
    importProvidersFrom([BrowserAnimationsModule]) ], 
};
```

**Comment by andimclean** [comment]
Well I feel dumb, I got caught out by this. Thanks for the save.

**Comment by gs-kug** [comment]
You can create a new service and inject it in both interceptor and the page layout. Then you use a observable to emit a event from interceptor to layout, in the layout you add the message. This will work, in other words you are not directly calling messageservice in the interceptor, but using a service as intermediate communication and calling in a component.

Parts of code:

    import { Injectable } from '@angular/core';
    import { Subject } from 'rxjs';
    
    @Injectable({
      providedIn: 'root'
    })
    export class ChangeDetectionService {
      private $detect: Subject<ToastMessageOptions> = new Subject<ToastMessageOptions>()
    
      get detect() {
        return this.$detect.asObservable()
      }
    
      trigger(options: ToastMessageOptions) {
        this.$detect.next(options)
      }
    }
    
    export interface ToastMessageOptions {
      text?: any;
      severity?: string;
      summary?: string;
      detail?: string;
      id?: any;
      key?: string;
      life?: number;
      sticky?: boolean;
      closable?: boolean;
      data?: any;
      icon?: string;
      contentStyleClass?: string;
      styleClass?: string;
      closeIcon?: string;
    }

LayoutComponent:

    ngOnInit() {
        const sub = this.changeDetectionService.detect.subscribe((message) => {
          this.messageService.add(message)
          // this.cdr.detectChanges()
        })
        this.subscriptions.add(sub)
      }

Interceptor:

    @Injectable()
    export class UserFeedbackErrorInterceptor implements HttpInterceptor {
    
      private cds: ChangeDetectionService = inject(ChangeDetectionService)
      //skipcq: JS-0057
      constructor(private readonly messageService: MessageService,
                  private readonly dialogService: DialogService) {
      }
    
      // skipcq: JS-0323
      intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
        return next.handle(req)
          .pipe(
            catchError(err => {
              if (err instanceof HttpErrorResponse) {
                if (err.status === 0 && !err.url?.includes('/info')) {
                  this.messageService.add({
                    severity: 'error', detail:
                      'Ocorreu um erro ao tentar contactar o servidor', sticky: true
                  });
                  //skipcq: JS-0339
                } else if (err.status === 400 && this.isApiUrl(err.url!)) {
                  this.cds.trigger({
                    severity: 'warn', summary: $localize`:@@msg-error-validation:Data validation error`,
                    detail: this.getValidations(err.error),
                    sticky: true
                  })
                  //skipcq: JS-0339
                } else if (err.status === 422 && this.isApiUrl(err.url!)) {
                  this.cds.trigger({
                    severity: 'warn',
                    summary: $localize`:@@msg-error-business:There is an error processing the request`,
                    detail: this.getMessages(err.error),
                    sticky: true
                  })
                  //skipcq: JS-0339
                } else if (err.status >= 500 && err.status < 600 && this.isApiUrl(err.url!)) {
                  this.cds.trigger({
                    severity: 'error', summary: $localize`:@@msg-error-unknown:There is an error processing the request`,
                    detail: this.getMessages(err.error),
                    sticky: true
                  })
                } else if (err.status === 403) {
                  this.dialogService.open(FeedbackMsgComponent, {
                    resizable: false,
                    maximizable: false,
                    contentStyle: {
                      overflow: 'auto'
                    },
                    breakpoints: {
                      '960px': '75vw',
                      '640px': '90vw'
                    },
                    modal: true,
                    data: {
                      msg: $localize`:@@msg-error-forbidden:Access denied`,
                      detail: $localize`:@@access-denied-text:You don't have the permissions`
                    }
                  })
                }
              }
              throw err;
            })
          );
      }
    }

**Comment by Bagestan** [comment]
@gs-kug thank you, works on v20
