### ISSUE TITLE
pPassword's strength indicator is behind a dialog

### ISSUE THREAD

**Issue by yerzhant** [primefaces/primeng#1402]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When pPassword input element is place into p-dialog the strength indicator appears behind the model dialog.

**Expected behavior**
The strength indication should be placed before (in z-order) a modal dialog.

**Minimal reproduction of the problem with instructions**
```
<p-dialog visible="true" modal="true" header="Set password">
  <input type="password" pPassword>
</p-dialog>
```

**What is the motivation / use case for changing the behavior?**
This is inconvenient.

**Please tell us about your environment:**
Ubuntu 16.04, VSC, ng-cli

* **Angular version:** 2.0.0.

* **PrimeNG version:** 1.0.0-rc.7

* **Browser:** [Chrome 52.0.2743.116 (64-bit)]
 
* **Language:** [TypeScript 2.0.2]

* **Node (for AoT issues):** `node --version` =  NA

**Comment by sudheerj** [comment]
The z-index should be dynamic for all overlay elements. I will raise a PR for this.

**Comment by sudheerj** [comment]
https://github.com/primefaces/primeng/pull/2898
