### ISSUE TITLE
ListBox | OnChange doesn't emit

### ISSUE THREAD

**Issue by HomelessCoder** [primefaces/primeng#14033]
### Describe the bug

The `onChange` event is not emitted.

### Environment

Angular 16 with Prime 16.7.0

### Reproducer

https://github-95kjvf.stackblitz.io

### Angular version

16.2.12

### PrimeNG version

16.7.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.9.0

### Steps to reproduce the behavior

Define and set the `onChange` handler. Click on the ListBox option. The handler was not called.

### Expected behavior

The handler was called. (Works fine with the same code in primeng v16.6)

**Comment by cetincakiroglu** [comment]
Hi,

With version 16.7.0, we have released the first part of the accessibility implementation for inputs that we have been working on for a long time. Based on the research we conducted during the implementation, we decided that many components needed changes in their structure and simplification, and these components were rewritten. Unfortunately, after extensive testing, there may be unexpected and unforeseen bugs that have emerged. We are grateful for your reports, and we are working to address them in the upcoming release!
