### ISSUE TITLE
TabMenu: Breaking change added while fixing #13910

### ISSUE THREAD

**Issue by Michael-Ziluck** [primefaces/primeng#14044]
### Describe the bug

Before #13910 and #13911, the following was an acceptable usage of the template for tab menus:

```html
<p-tabMenu [(activeItem)]="currentTab" [model]="tabItems">
  <ng-template pTemplate="item" let-item>
    {{ item.label | translate: I18N_PRODUCT }}
  </ng-template>
</p-tabMenu>
```

Which would result in this display:
![image](https://github.com/primefaces/primeng/assets/10745543/c4446f1e-e8c3-442c-a99d-b306d61249f3)

Now with the same markup, it results in this:
![image](https://github.com/primefaces/primeng/assets/10745543/b22bc53a-1ba3-41b7-92fb-678b3ac01315)

The change is because previously, the <ng-container> was within the <a> tag. I know you updated the docs to reflect this, but shouldn't breaking changes be constrained to major version changes? Seems wildly arbitrary and inconvenient for users to have to make the change. I'll be opening a bug issue as well.

### Environment

Angular: 16.2.12
PrimeNG: 16.7.1
Browser: latest Chrome

### Angular version

16.2.12

### PrimeNG version

16.7.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

N/A

### Browser(s)

Chrome

**Comment by jsdevtom** [comment]
I can reproduce

**Comment by philkrpp** [comment]
Also same for me.

**Comment by NexGenUA** [comment]
I have the same problem.
Also, when you click on a tab, routing does not work (routerLink).
What ideas? Manually process a click on a tab, taking into account all routing options?
Angular: 17.0.7
PrimeNG: 17.2.0

**Comment by DarkLeopard** [comment]
Quick edit: Add a wrapper to your template following the example.
`<a role="menuitem" pripple [routerLink]="item.routerLink" class="p-ripple p-element p-menuitem-link ng-star-inserted">`

**Comment by Michael-Ziluck** [comment]
@DarkLeopard Appreciate sharing the fix for those who are searching for a solution to this problem. For the original issue though, this should have only been introduced on a major version change as the update breaks existing usages of the component.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
