### ISSUE TITLE
Component: Dropdown | If optionValue is given label is not shown in input field

### ISSUE THREAD

**Issue by EnricoMessall** [primefaces/primeng#14042]
### Describe the bug

See bug video: https://discord.com/channels/787967399105134612/787967806367989790/1171196298867777636

### Environment

- 

### Angular version

16.2.3

### PrimeNG version

16.7.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.5.1

### Browser(s)

Chrome, Safari

### Steps to reproduce the behavior

Add optionValue to dropdown

### Expected behavior

optionValue shouldn't hide shown label on input.

**Comment by ericvaroto** [comment]
+1

**Comment by lukasloetkolben** [comment]
+1

**Comment by jerkovicl** [comment]
you can clearly see issue [here](https://stackblitz.com/edit/us998q?file=src%2Fapp%2Fdemo%2Fdropdown-reactive-forms-demo.html)

**Comment by Nexus6ITA** [comment]
+1

**Comment by jerkovicl** [comment]
Reproduction [here](https://stackblitz.com/edit/us998q?file=src%2Fapp%2Fdemo%2Fdropdown-reactive-forms-demo.html%2Csrc%2Fapp%2Fdemo%2Fdropdown-reactive-forms-demo.ts%2Cpackage.json)

**Comment by anof1r** [comment]
Got the same issue, problem caught on the latest version

**Comment by Jmurga16** [comment]
I've Node 18.8.2 and Angular 16.2.10 LTS versions, and with this prime ng (16.7.2) got the same issue.

**Comment by nicolasfaure988** [comment]
+1

**Comment by ashikjs** [comment]
Yp, this issue will solved next release you guess cam check it here. #14094

**Comment by EnricoMessall** [comment]
As @ashikjs mentioned will be fixed with #14000 see commit https://github.com/primefaces/primeng/commit/a0512439dd9d4d7d7cc41d031461e569c0f6e01c

Closing this one
