### ISSUE TITLE
PrimeNG showcase doesn't work for every component.

### ISSUE THREAD

**Issue by celtu** [primefaces/primeng#1404]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

I cannot explore primeng showcase (http://www.primefaces.org/primeng/).
**Expected behavior**

I see description of desired primeng component after I clicked it in left menu.
**Minimal reproduction of the problem with instructions**
Please click Menu/Menubar - it doesn't take effect.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by celtu** [comment]
2 hours ago it was working.

**Comment by dzhavat** [comment]
It is working fine now. They updated the page around an hour or so ago so you must've encountered a minor "hiccup" :)

**Comment by cagataycivici** [comment]
Can't replicate.
