### ISSUE TITLE
Fileupload component disables upload button

### ISSUE THREAD

**Issue by capkaempfer** [primefaces/primeng#14046]
### Describe the bug

If the fileupload is configured with the following properties, it will disable the upload button when files are uploaded one after the other.
```
[multiple]="true"
[maxFileSize]="maxSize"
[fileLimit]="4"
[customUpload]="true"
[showCancelButton]="false"
[showUploadButton]="false"
[auto]="true"
(uploadHandler)="emitFiles($event.files)"
```

### Environment

Angular: 16.2.7
PrimeNG: 16.7.0
Browser: latest Chrome

### Reproducer

https://stackblitz.com/edit/djzi3p?file=src%2Fapp%2Fdemo%2Ffile-upload-basic-demo.ts

### Angular version

16.2.7

### PrimeNG version

16.7.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.20.2

### Steps to reproduce the behavior

1. configure fileupload as seen above
2. click the choose button
3. select a single file and open
2. click the choose button again
4. select a second single file and open
5. the select button will now be disabled

### Expected behavior

After investigating in the code, the isChooseDisabled somehow adds files.length and the uploadedFileCount variable to compare to the maximum number of files.
I do not understand why it even adds it like that or why uploadedFileCount is counted in the first place.

**Comment by ashikjs** [comment]
Actually this case for `multiple` select feature not working properly.

**Comment by capkaempfer** [comment]
Definitely, but why is files.length and uploadedFileCount added to eachother to determine wether the file limit is exceeded?

**Comment by ashikjs** [comment]
@capkaempfer ya, Here have some miss calculation so we need to fixed it. soon.
