### ISSUE TITLE
applyFocus() method is working only when dropdown is editable.

### ISSUE THREAD

**Issue by ravikumar1243** [primefaces/primeng#14051]
### Describe the bug

I have a dropdown in dialog. As autoFocus directive will not work for dropdown which is inside dialog.
I am trying to set the focus using applyFocus() method in ngAfterViewInit() method. 

My dropdown has options and it is not editable. I observed the code in primeng-dropdown.mjs (applyFocus()) is setting the focus to input[readonly] when dropdown is not editable .

![image](https://github.com/primefaces/primeng/assets/95016007/d00a9dd1-c5bb-4198-82df-80e43f4cfeba)

### Environment

All Envrionments.

### Angular version

16.2.11

### PrimeNG version

16.7.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.9.3

### Browser(s)

Chrome 90

### Steps to reproduce the behavior

Call autoFocus() method for the dropdown which is not editable and have options.

Focus is not getting set to the dropdown.

### Expected behavior

Focus should set to the Dropdown as we are calling autoFocus() method.

**Comment by ashikjs** [comment]
@ravikumar1243 do you have any example ?

**Comment by LarsHabier** [comment]
I also can reproduce the bug of OP via this stackblitz:
https://stackblitz.com/edit/ma1fnw?file=src%2Fapp%2Fdemo%2Fdropdown-basic-demo.ts
