### ISSUE TITLE
p-dropdown doesn't setValue manually with Reactive Form

### ISSUE THREAD

**Issue by Argyos** [primefaces/primeng#14053]
### Describe the bug

I'm trying to set manually the form after some services retrieve some information, and I need to set back again to the dropdown the values (using setTimeout for practicity).

Along side are a normal selector which work accordingly to what I expected. I did the same with the p-dropdown i doesn't work at all.

It detected the change by the method onChange but again nothing happen.

https://stackblitz.com/edit/ge9bjb?file=src%2Fapp%2Fdemo%2Fdropdown-reactive-forms-demo.ts

Maybe it need some reference on the `<p-dropdown>` in order to work?

### Environment

primeng: 16.7.0
node: v18.18.0

### Reproducer

https://stackblitz.com/edit/ge9bjb?file=src%2Fapp%2Fdemo%2Fdropdown-reactive-forms-demo.ts

### Angular version

16.2.0

### PrimeNG version

16.7.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.8.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Enter stackblitz.com
2. Wait 2 seconds
3. Dont change dropdown

### Expected behavior

Must Change the dropdown current value to the [1]

**Comment by Argyos** [comment]
> Update your version to 16.7.1. I had tested here and worked well.

Thanks work perfectly with `"primeng": "16.7.1"`

**Comment by Kris-Pelteshki** [comment]
I'm not sure this works. We're using `^17.5.0`. 

We are calling `form.reset()` and all other fields work, but not `p-dropdown`
