### ISSUE TITLE
Component: p-chips | does not work with Reactive Forms

### ISSUE THREAD

**Issue by batudmr** [primefaces/primeng#14062]
### Describe the bug

p-chips does not allow typing and updating in Reactive Forms

### Environment

MacOS

### Reproducer

https://primeng.org/chips#reactive-forms

### Angular version

16.2.0

### PrimeNG version

16.7.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.9.0

### Browser(s)

Chrome 118

### Steps to reproduce the behavior

1. Go to reproducer link 
2. Type something to the component

### Expected behavior

Reactive forms approach should work while typing just like other template driven approaches.

**Comment by eggShells** [comment]
Shouldn't you be releasing bug fixes in a minor version update?  This bug has broken the functionality that previously worked, and we cannot move to prior version because there are breaking changes in the versions.
