### ISSUE TITLE
Upgrade to Angular 17?

### ISSUE THREAD

**Issue by Sebastian-G** [primefaces/primeng#14063]
Is there any release plan for Angular 17? 
And the introduction of DesignTokens matching the Firma Files?

**Comment by b1rigu** [comment]
Yes please add angular 17 support

**Comment by mircowidmer** [comment]
I'm getting the following error after upgrading to Angular 17:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: out-of-office@0.0.0
npm ERR! Found: @angular/common@17.0.1
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^16.2.0" from primeng@16.7.2
npm ERR! node_modules/primeng
npm ERR!   primeng@"^16.7.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

I assume the reason is, PrimeNG 16.7.2 is not ready for Angular 17.

**Comment by Rotzbua** [comment]
> I assume the reason is, PrimeNG 16.7.2 is not ready for Angular 17.

PrimeNG version supports only the according Angular version.
In the past it took about a month until a PrimeNG release was available.

**Comment by ces6jedi** [comment]
Too many crashes and bugs for me to continue with this framework, so slow to move to Angualr 17 as well ☹️

**Comment by gjlmotea** [comment]
I can't wait to get started with v17 too.

**Comment by DominikPieper** [comment]
I’m waiting too. But let’s keep realistic, Angular 17 is just a few days out. Anyone know if the work already begun?

**Comment by alexnoise79** [comment]
v17 is full of new syntax especially from point of view of templates, i think will take some time to refactor the codebase of primeng... 

so seat back, relax and enjoy your flight!

**Comment by alydemah** [comment]
> v17 is full of new syntax especially from point of view of templates, i think will take some time to refactor the codebase of primeng...
> 
> so seat back, relax and enjoy your flight!

Is a refactor necessary, the old control flow is still supported and should work with no issues with v17.
Or it's planned to move to new control flow in the new release of primeng?

**Comment by leogouveia** [comment]
> > v17 is full of new syntax especially from point of view of templates, i think will take some time to refactor the codebase of primeng...
> > so seat back, relax and enjoy your flight!
> 
> Is a refactor necessary, the old control flow is still supported and should work with no issues with v17. Or it's planned to move to new control flow in the new release of primeng?

In addition, many of the new features are in developer preview. I think it's best to release them from the preview in order to refactor the code.

**Comment by MAN-Sendance** [comment]
This issue should be prioritized. I also think that it is not necessary to do a whole refactoring immediately since the old syntax is still supported by Angular 17.

**Comment by morsagmon** [comment]
What I wish is to get a clear statement from PrimeFaces rep on their plan, so that we can plan accordingly.

**Comment by puschie286** [comment]
note: https://github.com/orgs/primefaces/discussions/424

**Comment by alexnoise79** [comment]
> > v17 is full of new syntax especially from point of view of templates, i think will take some time to refactor the codebase of primeng...
> > so seat back, relax and enjoy your flight!
> 
> Is a refactor necessary, the old control flow is still supported and should work with no issues with v17. Or it's planned to move to new control flow in the new release of primeng?

well of course the old control flow is still supported, but without a refactor we will not be able to enjoy the real power of v17, honestly i don't know what is the current plan, probably refactor will be done step by step.

i hope there will be a migration tool to help developers in this high risk task

**Comment by DominikPieper** [comment]
@alexnoise79  there’s a schematic for the migration.

ng generate @angular/core:control-flow

**Comment by SERGE3-g** [comment]
Salve a tutti mi potreste aiutare a risolvere questo problem perchè ho installato angular v17 e mi da questo problema per favore aiutatemi. 
https://github.com/orgs/primefaces/discussions/424#discussioncomment-7581849

<img width="871" alt="Screenshot 2023-11-15 alle 23 00 10" src="https://github.com/primefaces/primeng/assets/113424842/906f4fb2-f418-4d08-807e-7427567d0532">

**Comment by cetincakiroglu** [comment]
Hi everyone!

As the Core team, following the recent accessibility update we released, we are currently working on fixing the reported issues and focusing on implementing the data section accessibility. After rolling out the accessibility implementation with one last release in v16, we will release PrimeNG 17. If everything goes smoothly, we plan to release the PrimeNG 17.0.0-rc.1 version with Angular 17 support next week.

**Comment by jhcpeixoto** [comment]
@cetincakiroglu When will all the components be refactored to adapt to version v17 with (Conditional statements)?

**Comment by slyk** [comment]
@cetincakiroglu thank you!! for your service and being contributor of such great lib.

Don't sure that "data section accessibility" is more important now than giving incomers to use PrimeNG. Now in renaissance of Angular we have a lot of them wanted to try new features. And now they decide what to use. The decisions that they will do right now will lead to community size around that PrimeNG and its value/place in other libs.

Maybe working with angular pre-preleases to have some beta at the Angular release date will be the best idea to not lose newcomers. They have simple projects and ready to start working with a beta. But they mostly don't ready to start with older Angular lib when the new version is released. (don't know if angular have some pre-release / RC open to public, hope so).

I guess me and other people who into it more that couple of years can wait (and should wait) some time for all migration schematics and bugs to be fixed before moving their bigger projects to new versions. So its ok. That is why above I've talked about newcomers mostly. But the community needs them :)

P.S. don't really know the details behind the "data section accessibility", sorry.

**Comment by cetincakiroglu** [comment]
Hi folks,

We are currently testing PrimeNG 17 to determine if there are any breaking changes. Our plan is to present 17.0.0-rc.1 to you tomorrow. We apologize for the delay, but we couldn't carry over all the reported bugs from version 16 related to accessibility updates. We are working to provide you with a stable experience. Thank you for your patience and understanding. As a team, we are eagerly looking forward to delivering PrimeNG 17 to you!

**Comment by cetincakiroglu** [comment]
Fixed in https://github.com/primefaces/primeng/commit/465482e08e98f01811c8062831ee14ddc85323b2

**Comment by MAN-Sendance** [comment]
Thanks a million! @cetincakiroglu
