### ISSUE TITLE
Component: p-multiSelect does not render grouped items that have a property named group

### ISSUE THREAD

**Issue by jpgoelz** [primefaces/primeng#14061]
### Describe the bug

We are using a p-multiSelect in our application with grouped items.

The values are dynamically grouped by a `group` property in our own SelectItem-Inerface:

```typescript
export interface GroupableSelectItem<T> extends SelectItem<T> {
  group: string;
}
````

Since PrimeNG 16.7.x items in groups are no longer rendered/selectable if the items have a `group` property. If any other property name is used, there is no problem (see StackBlitz).

![image](https://github.com/primefaces/primeng/assets/32487587/b26bc956-b924-4c78-aa07-db35b9c3598c)

### Environment

Any environment has this problem.

### Reproducer

https://stackblitz.com/edit/1j5ikb?file=src%2Fapp%2Fdemo%2Fmulti-select-group-demo.html

### Angular version

16.2.x

### PrimeNG version

16.7.x

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Steps to reproduce the behavior

Add a `group` property to any of the grouped items in a p-multiSelect with `[group]="true"`.

I forked this StackBlitz from the MultiSelect component demo for groups:

https://stackblitz.com/edit/1j5ikb?file=src%2Fapp%2Fdemo%2Fmulti-select-group-demo.ts

### Expected behavior

The items are rendered OR the docs warn that `group` cannot be used as a property.

**Comment by ashikjs** [comment]
@jpgoelz  primeNG options have costume property name ``option`` so  if you add same property then it make conflict.

**Comment by jpgoelz** [comment]
> @jpgoelz primeNG options have costume property name `option` so if you add same property then it make conflict.

Not sure if I can follow. Which options and where? We are not using an "option" property.

**Comment by cetincakiroglu** [comment]
Hi,

Thanks a lot for reporting the issue!
