### ISSUE TITLE
Frozen Columns in dataTables.

### ISSUE THREAD

**Issue by albertosramires** [primefaces/primeng#1406]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
No frozen columns implemented.

**Expected behavior**
Frozen columns implemented.

**What is the motivation / use case for changing the behavior?**
With large data tables it's important to have information that you always want the user to view (usually the first couple of columns) so he can have a reference to where he is on the table without having to keep scrolling left and right and frozen columns provide this. I don't see this feature on your roadmap so I figured I should point it out since a lot of people might benefit from having this.
Here's an example of this: http://demos.telerik.com/kendo-ui/grid/frozen-columns

**Comment by cagataycivici** [comment]
This is on roadmap;

https://github.com/primefaces/primeng/wiki/Roadmap

Closing for now and will create a new ticket with details when we pick it up from roadmap after 1.0. 

At the moment, we're closing tickets that duplicate the upcoming features in roadmap as a part of issue tracker maintenance.

**Comment by cagataycivici** [comment]
#1742
