### ISSUE TITLE
PrimeNg did not support Angular 17 

### ISSUE THREAD

**Issue by pctimhk** [primefaces/primeng#14076]
### Describe the bug

I try to install primeng in angular app created in angular cli 17.0. However, the following error displayed.

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: bct@0.0.0
npm ERR! Found: @angular/common@17.0.1
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^17.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^16.2.0" from primeng@16.7.2
npm ERR! node_modules/primeng
npm ERR!   primeng@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

### Environment

Angular CLI: 17.0.0
Node: 18.17.1
Package Manager: npm 9.6.2
OS: win32 x64

Angular: 17.0.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0
@angular-devkit/build-angular   17.0.0
@angular-devkit/core            17.0.0
@angular-devkit/schematics      17.0.0
@angular/cli                    17.0.0
@schematics/angular             17.0.0
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2

### Angular version

17.0.0

### PrimeNG version

16.7.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.17.1

### Browser(s)

Chrome 90

### Steps to reproduce the behavior

Execute the follow command
npm install -g @angular/cli
npm update -g @angular/cli
ng new AngularWebApp --style scss --standalone false --ssr false --routing true"
npm install PrimeNg

### Expected behavior

Install success

**Comment by cetincakiroglu** [comment]
Hi,

This issue is fixed and Angular17 support provided with PrimeNG v17
