### ISSUE TITLE
Documentation: AnimationEvent_2 typo?

### ISSUE THREAD

**Issue by kvchrissh** [primefaces/primeng#14071]
### Describe the bug

Not a bug, but potential error in the documentation?
For example in the Calendar component, the `onClose` event type is `AnimationEvent_2`. In the Angular library project I'm working on with VS Code, I get no suggestion for this, instead a suggestion for `AnimationEvent` from Angular. But then the HTML file of the component that uses the Calendar complains about the type. `AnimationEvent_2` also doesn't link to any type reference, when I click on it on the PrimeNG Calendar docs page. Is `AnimationEvent_2` a typo or is it an error on my side? A quick google search didn't provide an answer.

### Environment

VS Code 1.81.1

### Angular version

16.2.12

### PrimeNG version

16.7.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.0

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
