### ISSUE TITLE
 broken styles after updating from version 16.3.1 to 16.7.2 in angular

### ISSUE THREAD

**Issue by beyaban** [primefaces/primeng#14072]
### Describe the bug

The update from version 16.3.1 to 16.7.2 has completely messed up all the styles in my angular app. It doesn't make sense to fix all the styles manually. What has changed? Any ideas?

### Environment

Angular 16.2.6, sass

### Angular version

16.2.6

### PrimeNG version

16.7.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v18.16.0

**Comment by imaksp** [comment]
styles for any specific component or all ? are you using custom theme?

**Comment by pete-mcwilliams** [comment]
duplicate issue, it's to do with layers

**Comment by beyaban** [comment]
> styles for any specific component or all ? are you using custom theme?

styles for table, dropdown, input field, no custom theme defined

**Comment by beyaban** [comment]
> duplicate issue, it's to do with layers

what do you mean with layers?

**Comment by pete-mcwilliams** [comment]
I mean search for the duplicate bug using the keyword layers https://github.com/primefaces/primeng/issues/13757
