### ISSUE TITLE
Horizontal menu covering web page content

### ISSUE THREAD

**Issue by JxEngel** [primefaces/primeng#14077]
### Describe the bug

When the 'Menu Type' is set to horizontal it _pushes down_ the content of our webpage appropriately. However, if the menu items wrap to a 2nd row the menu overlaps content. Is there a way to handle this so the menu always pushes the rest of the body down according to its size? 

### Environment

Angular 13, primeng 13 web app

### Angular version

13.3.4

### PrimeNG version

13.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14.2

**Comment by cetincakiroglu** [comment]
Hi,

Could you please share a stackblitz reproducer?
