### ISSUE TITLE
Table | Row Expansion and Selection not Working Together

### ISSUE THREAD

**Issue by Fraser12345** [primefaces/primeng#14081]
### Describe the bug

Issue https://github.com/primefaces/primeng/issues/11129 still not working so I reopen it. 

 For selecting is necessary to have dataKey as item id. But in that case grouping is not working.

### Environment

Angular project using primeNg components.

### Angular version

15.2.8

### PrimeNG version

15.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.17.0

**Comment by cetincakiroglu** [comment]
Fixed in https://github.com/primefaces/primeng/pull/14672
