### ISSUE TITLE
MegaMenu & MenuBar | Activate root item on hover.

### ISSUE THREAD

**Issue by cetincakiroglu** [primefaces/primeng#14086]
Accessibility improvement:

- `MegaMenu` hover behavior will change. The root element will activate without a click needed if there isn't an active root element.
- `MenuBar` hover behavior will change. The root element will activate if `autoDisplay` set to true without a click needed if there isn't an active root element.

**Comment by drakgoku** [comment]
<img width="1547" height="500" alt="Image" src="https://github.com/user-attachments/assets/c4d8bc78-8570-4e2f-9b97-208659e83414" />

<img width="198" height="24" alt="Image" src="https://github.com/user-attachments/assets/5c3a87bc-2759-4b4e-a81b-11e23865986b" />
