### ISSUE TITLE
Calendar current day

### ISSUE THREAD

**Issue by ibrahimkelly** [primefaces/primeng#14091]
### Describe the bug

The text color of the current day of calendar not fully visible on hover.

![image](https://github.com/primefaces/primeng/assets/94073143/54e5700c-48fb-4e00-a590-09ec530b8ade)

### Environment

Windows

### Angular version

16

### PrimeNG version

16.5.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

21

### Browser(s)

Chrome

### Steps to reproduce the behavior

When hovering the calendar current day.

### Expected behavior

Different color like balck.

**Comment by ibrahimkelly** [comment]
If confirmed as bug, assign me on it.

Thanks !

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
