### ISSUE TITLE
Toggleable DataTable Reflow Mode

### ISSUE THREAD

**Issue by mcwebdev** [primefaces/primeng#141]
Ability to toggle `<tr>` into PseudoEl "Card" 

In linked example it is the the third button in the group of controllers.

http://issues.wenzhixin.net.cn/bootstrap-table/

**Comment by cagataycivici** [comment]
The link seems broken?

**Comment by mcwebdev** [comment]
seems to have been an issue with the URL injection into the webform. Updated the link. Many Thanks!

**Comment by cagataycivici** [comment]
By toggle tr do you mean row expansion?

**Comment by mcwebdev** [comment]
Yes it is much like that behavior with added elements. "Cards" are a new psuedoElement being adopted by many frameworks which will make them easier for syndication. They follow this semantic.

<div class="card-view">
    <span class="title" style="text-align: center; vertical-align: middle; ">Item ID</span>
    <span class="value">0</span>
</div>

**Comment by cagataycivici** [comment]
Oh I see, we already have something similar, check out the reflow please;

http://www.primefaces.org/primeng/#/datatableresponsive

If you reduce the width of the window, datatable goes in card mode. I guess we can add a class to make this mode toggleable for large screens as well, what do you think?

**Comment by cagataycivici** [comment]
I've added stacked property and added a demo for it using a button where clicking the button toggles the stacked value so the datatable switches between tabular and card layout.

**Comment by mcwebdev** [comment]
I tested it out, but was unable to get it working. I think the css for it wasn't pushed to the repo. When I did git pull I didn't see any css files come down. I am seeing .ui-datatable-stacked added to DOM.

**Comment by cagataycivici** [comment]
Yes, the css is in PrimeUI so will be available with upcoming PrimeUI 4.2 that PrimeNG 1.0.0-beta.1 uses. CSS is shared between these two and it is distributed in PrimeUI.
