### ISSUE TITLE
frozen headers and columns with virtual scroll

### ISSUE THREAD

**Issue by stacisoutherland24** [primefaces/primeng#14104]
### Describe the bug

In our application we are having issue with tables that have virtual scroll enabled and have frozen columns. The headers do not move with the table cells as you would expect them to. They headers will come offline too and will shake back and forth

### Environment

Angular ERP system

### Reproducer

https://stackblitz.com/edit/g985zm?file=src%2Fapp%2Fdemo%2Ftable-basic-demo.html

### Angular version

16.2.0

### PrimeNG version

16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.4.2

### Steps to reproduce the behavior

1.Go to stackblitz table and scroll up and down and side to side 

### Expected behavior

I expect the headers to scroll with the correct data in the column

**Comment by harryKont** [comment]
We are also facing the same issue, is there a plan to fix this?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
