### ISSUE TITLE
Multiselect: Missing itemValue in onChange event

### ISSUE THREAD

**Issue by Kisters-BS** [primefaces/primeng#14100]
### Describe the bug

Since version 16.7.0 the onChange event does not emit itemValue.

See the regression by comparing the versions:
https://github.com/primefaces/primeng/compare/16.6.0...16.7.0

Working example with version 16.6.0: https://stackblitz.com/edit/4a9zpc-afbx9w

### Environment

See stackblitz

### Reproducer

https://stackblitz.com/edit/4a9zpc

### Angular version

16.2.0

### PrimeNG version

16.7.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.0

### Expected behavior

itemValue is emitted by the onChange event

**Comment by ashikjs** [comment]
@Kisters-BS  I can see itemvalue with onChange event.

![Screenshot from 2023-11-14 10-56-35](https://github.com/primefaces/primeng/assets/13074235/d79fc322-9e39-40d6-8a23-9859f5e30d33)

**Comment by Kisters-BS** [comment]
@ashikjs In your console log I can also only see **originalEvent** and **value**. There should also be **itemValue**, see: https://primeng.org/multiselect#api.multiselect.events.MultiSelectChangeEvent

**Comment by ashikjs** [comment]
@Kisters-BS  Thanks now, understand.

**Comment by Kisters-BS** [comment]
I have tested the fix, it works! Thank you 😊
