### ISSUE TITLE
MultiSelect component triggers two empty change events when rendered

### ISSUE THREAD

**Issue by mher-at-qbeyond** [primefaces/primeng#14103]
### Describe the bug

If the multiselect is configured with the following properties, it will launch two `onChange` events with `value: null` and without `originalEvent`
```

    [options]="cities"
    [(ngModel)]="selectedCity"
    [filter]="false"
    optionLabel="name"
    optionValue="code"
    [maxSelectedLabels]="2"
    (onChange)="dropdownChanged($event);"
```

### Environment

Angular: 16.2.7
PrimeNG: 16.7.0
Browser: latest Chrome

### Reproducer

https://stackblitz.com/edit/djzi3p-5kiysu?file=src%2Fapp%2Fdemo%2Fmulti-select-basic-demo.ts

### Angular version

16.2.7

### PrimeNG version

16.7.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.20.2

### Steps to reproduce the behavior

1.	configure multiselect as seen above
2.     after the page is rendered two empty events will be launched on onChange trigger

### Expected behavior

Should not launch two empty `onChange` events when rendered.

**Comment by cetincakiroglu** [comment]
Hi,

This issue is fixed in https://github.com/primefaces/primeng/commit/2008537aa3e9df3f3757ffcdaecba65acccb751c

Thanks a lot for reporting the issue!
