### ISSUE TITLE
DataView component CANNOT find any results from @Input data passed from parent component

### ISSUE THREAD

**Issue by anof1r** [primefaces/primeng#14106]
### Describe the bug

I'm trying to pass data from the parent component to a child that contains a DataView. Unfortunately, the DataView showing the "No results found" message and cannot render passed data under no circumstances.

### Environment

Windows 10

### Reproducer

https://stackblitz.com/edit/angular-pa3wff?file=demo%2Fsecond%2Fsecond.component.html

### Angular version

16.2.0

### PrimeNG version

16.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

17.4.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Pass any data to the child component that contains DataView
2. Bind it  `<p-dataView [value]="your array of object">`
3. See the result

https://stackblitz.com/edit/angular-pa3wff?file=demo%2Fsecond%2Fsecond.component.html
Here you can see that the first component passes the data Array to its child, but DataView doesn't render it 

### Expected behavior

`<p-dataView>` component renders all the necessary data from `@Input()` decorator, like `<p-table>` does

**Comment by ashikjs** [comment]
@anof1r  here is workable solution, 
https://stackblitz.com/edit/angular-tnean4?file=src%2Fapp%2Fdemo%2Fsecond%2Fsecond.component.html 

btw: you did mistake two one you call Grid layout but used itemlist template and you did not call rows.

**Comment by anof1r** [comment]
Hi @ashikjs, thanks for your response. 
Your solution works as expected, but I really need to pass data through `@Input()`
I've changed layout and pTemplate properties locally and in Reproducer. Nothing changed, still no data in DataView. 
If it can help, checkout my local approach here - https://github.com/anof1r/language-quizz/blob/dev/anof1r/src/app/words-list/words-list.component.html

**Comment by ashikjs** [comment]
@anof1r can you check it? I can see here everything expected.

https://stackblitz.com/edit/angular-usbl6e?file=src%2Fapp%2Fdemo%2Fsecond%2Fsecond.component.ts

**Comment by anof1r** [comment]
Gosh :( my bad. Just found the logic error. Everything works fine now. Thanks for help @ashikjs !
