### ISSUE TITLE
Accordion: nested inputs loose focus when pressing arrow keys

### ISSUE THREAD

**Issue by vinlos** [primefaces/primeng#14105]
### Describe the bug

When we nest any kind of input (multiselect, select, autocomplete...) inside an **accordion** and we use arrow keys to select any entry, the input looses the focus in favour of accordion tab header.

### Environment

Ubuntu linux
VsCode

### Reproducer

https://stackblitz.com/edit/github-ykowfu?file=src%2Fapp%2Fapp.component.html

### Angular version

16.2.12

### PrimeNG version

16.6.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.1

### Steps to reproduce the behavior

1. Open [stackblitz live snippet](https://stackblitz.com/edit/github-ykowfu)
2. Type something in autocomplete input
3. Press "arrow-down" to select an entry

it's impossible to select an entry because the input looses the focus

### Expected behavior

input should keep the focus and allows to select an entry using arrow keys

**Comment by Gykonik** [comment]
The following issue might also be related https://github.com/primefaces/primeng/issues/13488
