### ISSUE TITLE
Primeng css

### ISSUE THREAD

**Issue by a-zana** [primefaces/primeng#14116]
### Describe the bug

in the 'primeng/resources/primeng' there is:

      input[type='button'],
      input[type='submit'],
      input[type='reset'],
      input[type='file']::-webkit-file-upload-button,
      button {
          border-radius: 0;
      }

this css is too generic and have a deep impact with for example bootstrap (importing bootstrap with a layer and set the boostrap layer before primeng as have to be).

### Environment

use bootstrap with primeng and try to use for exmple the bootstrap button-group

### Angular version

16.2.19

### PrimeNG version

16.6.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.10.0

### Browser(s)

Chrome 119

### Expected behavior

It is better to do somenthing like:

    [class^='p-'] {
        input[type='button'],
        input[type='submit'],
        input[type='reset'],
        input[type='file']::-webkit-file-upload-button,
        button {
            border-radius: 0;
        }
    }

so to apply this rule only to the primeng components

**Comment by egorbwork** [comment]
I agree, I encountered a similar problem with the buttons.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
