### ISSUE TITLE
Broken style of prime-ng paginator dropdown that is inside dialog when paginatorDropdownAppendTo="body"

### ISSUE THREAD

**Issue by vokic** [primefaces/primeng#14112]
### Describe the bug

When appending a paginator of a p-table that is inside a dialog, using **paginatorDropdownAppendTo="body"**, the dropdown of the  paginator is not the same style as before

Before appending it to body:

![Before](https://i.imgur.com/UiLHQLU.png)

After adding paginatorDropdownAppendTo="body":

![After](https://i.imgur.com/FLYfQvU.png)

### Environment

Windows 10,
Node: 18.16.1
Primeng: 16.7.1,
Angular: 16.2.0,
npm 9.8.0,
VS Code 1.84.2

### Angular version

16.2.0

### PrimeNG version

16.7.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.1

### Steps to reproduce the behavior

1. Create a table with paginator inside a dialog pop up
2. Select paginator dropdown → the menu is "under" the border
3. add paginatorDropdownAppendTo="body" to the table
4. Select paginator dropdown → the menu is "over" the border but it is narrow

Also when I try to manually edit padding or margin, using css, I cannot do it when it is appended to body. When I remove it, the styles apply:

```
 :host ::ng-deep .p-dropdown-panel .p-dropdown-items .p-dropdown-item {
  margin: 0.75rem !important;
  padding: 0.75rem !important;
} 
```

### Expected behavior

The dropdown menu is expected to be the same width as when it is not appended to body.

**Comment by digeomel** [comment]
Having the same issue here with 16.8.0 as well.

**Comment by digeomel** [comment]
It looks like in v16.x you renamed the `p-paginator` input from `dropdownAppendTo` to just `appendTo`:

https://github.com/primefaces/primeng/blob/master/src/app/components/paginator/paginator.ts#L164

But in the `p-table` component template you're still passing the old `dropdownAppendTo` input:

https://github.com/primefaces/primeng/blob/master/src/app/components/table/table.ts#L158

**Comment by digeomel** [comment]
The problem seems to be caused by this class:

https://github.com/primefaces/primeng/blob/16.8.0/src/app/components/dropdown/dropdown.css#L45

But I see that on master it is already removed.

As a temporary workaround, I've set this class globally to override the one coming from PrimeNg:

```css
.p-dropdown-panel {
    position: unset;
    top: unset;
    left: unset;
}
```

**Comment by puranjayjain** [comment]
the problem still persists

**Comment by himinat** [comment]
just updated from v16 to v17, the problem still persists...

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by iznogood112** [comment]
i had the same issue and "paginatorDropdownAppendTo body" solved it for me
