### ISSUE TITLE
inputSwitch dynamic disabled cause ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by lufo88ita** [primefaces/primeng#14126]
### Describe the bug

If I use a variable to set disabled in InputSwitch
https://primeng.org/inputswitch

and change the value from false to true in console it show
ExpressionChangedAfterItHasBeenCheckedError

### Environment

OS: Windows 10
Angular 16.2
Primeng: 16.7.2
But it happens also in
primeng 14.2.3
angular 14.2
And I suppose in primeng 15 also.

### Reproducer

https://stackblitz.com/edit/ich5kf-cksjho?file=src%2Fapp%2Fdemo%2Finput-switch-disabled-demo.html

### Angular version

16.2

### PrimeNG version

16.7.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.20.2

### Browser(s)

Chrome 119.0.6045.159

### Steps to reproduce the behavior

1) Open the stackblitz example
2) Click on the inputswitch (the example disabled the input switch for 2 seconds)
3) Watch in the console the error

### Expected behavior

No error print in the console

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
