### ISSUE TITLE
p-multiSelect: Error with [resetFilterOnHide]=true and reopening of the dropdown

### ISSUE THREAD

**Issue by SchleichAlex** [primefaces/primeng#14122]
### Describe the bug

1. Set the "resetFilterOnHide" flag to true on the Multiselect Component
`                <p-multiSelect [resetFilterOnHide]="true"></p-multiSelect>
`
3. Open the Dropdown via click
4. Close the Dropdown 
5. Open the Dropdown again and there will be an exception in the Console 
`ERROR TypeError: ctx_r52._filterValue is not a function
    at MultiSelect_ng_template_15_div_3_ng_template_4_div_1_Template`

### Environment

Im using the official PrimeNG showcase app "basicdoc.ts" for my test

### Reproducer

https://stackblitz.com/edit/github-myoirr?file=README.md

### Angular version

16.2.0

### PrimeNG version

16.7.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.20.2

### Browser(s)

Chrome 118.0.5993.89

### Expected behavior

The filter should be resetted after closing the dropdown and no error should be on the console after reopening

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
