### ISSUE TITLE
p-virtualScroller  autosize issue

### ISSUE THREAD

**Issue by khushbupatel2** [primefaces/primeng#14129]
<p-virtualScroller #virtualScroller [value]="conversations" scrollHeight="500px" autosize
		[rows]="conversations.length" [cache]="false" [lazy]="false">
			<ng-template let-row pTemplate="item" let-i="index">
			<div class="ui-g car-item">
	<p [innerHTML]="row?.message "></p>
		</div>
		</ng-template>
	</p-virtualScroller>
	
	@ViewChild('virtualScroller', { static: false }) public virtualScroller!: VirtualScroller;
	 public scrollTo(i:any): void {
     
      try {
        this.virtualScroller.scrollTo(i);
      } catch (error) {}
    }
   when I use autosize that time scrollTo not work please help me

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
