### ISSUE TITLE
Accessibility | Data Section

### ISSUE THREAD

**Issue by yigitfindikli** [primefaces/primeng#14123]
### Describe the bug

- [x] Table
- [x] DataView
- [x] OrderList
- [x] Paginator
- [x] Tree
- [x] TreeSelect
- [x] TreeTable
- [x] Timeline
- [x] VirtualScroller

**Comment by cetincakiroglu** [comment]
Fixed in https://github.com/primefaces/primeng/commit/4cc722d7fd88066a0687f7a328f8d48a7228ecde
