### ISSUE TITLE
p-dropdown: onBlur is been called on selection, without lost focus, and before onChange

### ISSUE THREAD

**Issue by lixaotec** [primefaces/primeng#14128]
### Describe the bug

Dear Fellows,

It seems to me that onBlur shoud not be called on option selection in pDropDown, and when an options is chosen, the control has not lost focus yet, and p-dropdown is calling onBlur at that time..
And in my case it seems to be called moments before the data (option) actually has been changed (what fires onChange), and I have a validation which occurs on onBlur.

The wordaround (very ugly in fact) i found is to have a timer to wait 100-200ms in onBlur step to wait for the option be filled so I can dispatch a validation.

What do you think? 
Should p-Dropdown deal with it, or simply dont dispatch onBlur if it has not lost focus?

Thanks in advance.

### Environment

angular v16

### Angular version

v16.2

### PrimeNG version

v16.6.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

lastest

**Comment by cetincakiroglu** [comment]
Hi,

Component fires onBlur event after the input loses focus. Check the example https://stackblitz.com/edit/piyadq?file=src%2Fapp%2Fdemo%2Fdropdown-basic-demo.html,src%2Fapp%2Fdemo%2Fdropdown-basic-demo.ts

**Comment by lixaotec** [comment]
Dear @cetincakiroglu ,

Thanks for promptly replaying.

Sure it does fires after the input loses focus.

The question it is also firing before losing focus too.. and if you subscribe to onChange, you´ll notice that onChange is fired *before* onBlur, which leads to confusion. That´s because when an item is selected , there´s no focus losing yet.

So its firing onBlur when it wasnt supposed to, and by that, onChange ends calling after it. 

Blur is a widely event trigger to dispatch validation. If i trigger it before selected item is ready, will end up on false positive error message.

https://stackblitz.com/edit/piyadq-iicqbz?file=src%2Fapp%2Fdemo%2Fdropdown-basic-demo.ts

Agreed?

**Comment by cetincakiroglu** [comment]
Thanks for explanation and the example, I'll check it 👍🏻
