### ISSUE TITLE
Component: p-multiSelect resetFilterOnHide issue

### ISSUE THREAD

**Issue by Anesta94** [primefaces/primeng#14134]
### Describe the bug

When resetFilterOnHide is enabled, the second opening of the overlay panel generates an exception. I believe the issue lies in the resetFilter method; the _filterValue property is set to null. In my opinion, it should be done like this: this._filterValue.set(null), since it is a Signal or by using the setter filterValue.

![p-multiSelect-1](https://github.com/primefaces/primeng/assets/41288508/973d6c4b-866a-4b1c-a8e5-080d1751781e)
![p-multiSelect-2](https://github.com/primefaces/primeng/assets/41288508/d992337a-dcfe-4053-8f5d-53e140b4e1b0)

### Environment

All

### Reproducer

https://stackblitz.com/edit/pjvadj?file=src%2Fapp%2Fdemo%2Fmulti-select-basic-demo.html

### Angular version

16.2.0

### PrimeNG version

16.7.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.0

### Steps to reproduce the behavior

1. Click on p-multiSelect to open overlay panel
2. Click outside to close overlay panel
3. Click on p-multiSelect to open overlay panel

At this point the exception should be thrown in console.

**Comment by Wozhizxy** [comment]
I have also encountered this issue, and I feel that it is a bug

**Comment by cetincakiroglu** [comment]
Hi,

Thanks a lot for reporting the issue!
