### ISSUE TITLE
AutoComplete | Items are not visible after overlay is opened second time

### ISSUE THREAD

**Issue by lemonCMS** [primefaces/primeng#14137]
### Describe the bug

When using the autocomplete with dropdown and virtualscroll, after selecting one item that is outside the scroll view and then open the dropdown. The dropdown is "empty". You need to scroll to see the items in the list.

See the default example in de components.

### Environment

The example environment

### Reproducer

https://primeng.org/autocomplete#virtualscroll

### Angular version

16

### PrimeNG version

16.7.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

the example env

**Comment by cetincakiroglu** [comment]
Hi,

Thanks a lot for reporting the issue!

**Comment by julian-baumann** [comment]
This still seems to be an issue in the latest version. You can even see that the demo (https://primeng.org/autocomplete#virtualscroll) has the same issue.
