### ISSUE TITLE
DataTable rowExpansion bug with Angular 2.2.x

### ISSUE THREAD

**Issue by ribizli** [primefaces/primeng#1413]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
http://embed.plnkr.co/bJ0ln941VPbUX7KP3Mtk/
From the second opening on the template variables are messed up inside the rowexpansion template if it contains any structural directive (ngIf, ngFor).

**Expected behavior**
Fix the above. The issue can be angular related, but it can be avoided by not querying by TemplateRef. Use template naming or custom directive (`pTemplate`) for the rowexpansion template.

**Minimal reproduction of the problem with instructions**
See above. Open row expansion at lease two times (same or different row), the content will not reflect the rowexpansion template.

**What is the motivation / use case for changing the behavior?**
Otherwise app stops working with angular 2.2x

**Please tell us about your environment:**

* **Angular version:** 2.2.X

* **PrimeNG version:** 1.0.0

* **Browser:** all
 
* **Language:** TypeScript 2.0

**Comment by ribizli** [comment]
Related: https://github.com/angular/angular/issues/13080

**Comment by bogacg** [comment]
Instead of using ngFor and styling directly, I've tried to use p-dataList, same erronous behaviour happens.

**Comment by ribizli** [comment]
We are still sitting on the 2.1 version of angular, and cannot get rid of some already fixed router bugs because this is a blocking issue. I see that you are waiting for the fix from angular team (https://github.com/angular/angular/issues/13118, https://github.com/angular/angular/pull/13167), but the workaround would be so desired.

**Comment by bogacg** [comment]
Meantime I've changed my app's UX in order to keep development. Instead of expanding table rows, I open an overlay panel containing related info of that row upon row selection.

**Comment by ribizli** [comment]
I went currently an other direction: since angular 2.3 supports annotation inheritance, I crated a subclass of `DataTable` which uses template alias to query the expansion template:
```
export class MyDataTable extends DataTable {
  @ContentChildren('expansion') rowExpansionTemplate: QueryList<TemplateRef<any>>;
}
```
And instead of using the primeNG's `DataTableModule` I declare my implementation in my module.

**Comment by bogacg** [comment]
@ribizli Did you see this ? [PrimeNG 1.1 Release Info](http://blog.primefaces.org/?p=4240)
## Breaking Changes

> Row expansion template requires a pTemplate whose value is rowexpansion to correctly identify it.

**Comment by ribizli** [comment]
This issue can be closed, I guess. Thanks.

**Comment by ribizli** [comment]
This issue is solved, can be closed.
But let me point out an other blocking issue for us: #1600

**Comment by danicomas** [comment]
@ribizli do you have an example (pnlkr) as you did it? Regards

**Comment by ribizli** [comment]
@danicomas what? primeng devs have fixed the issue using `pTemplate` directive.

**Comment by danicomas** [comment]
Sorry @ribizli I have opened a related issue about @ViewChild in https://github.com/primefaces/primeng/issues/1775

In first instance I thought that was the same problem I had.
