### ISSUE TITLE
PrimeNG Calendar does not allow to select max year

### ISSUE THREAD

**Issue by mittal-shah** [primefaces/primeng#14132]
### Discussed in https://github.com/orgs/primefaces/discussions/322

<div type='discussions-op-text'>

<sup>Originally posted by **mittal-shah** October 26, 2023</sup>
PrimeNG Calendar does not allow to select max year. To reproduce set max-date to "2005-05-01", Open date picker, select current year link 2023, click previous button until you see 2005. Notice, that 2004 is available to pick but not 2005. Any solutions or workaround? Should this be turned to an issue?

![image](https://github.com/primefaces/community/assets/27385176/0a1b84ee-c663-45f6-ba1e-bc2f0fce2a8f)

See this demo to verify https://stackblitz.com/edit/xku2nb?file=src%2Fapp%2Fdemo%2Fcalendar-minmax-demo.ts

**Comment by cushychandru** [comment]
Issue still replicable ,
`this.date = new Date('2022-06-01');
 this.minDate = new Date('2000-01-01');
 this.maxDate = new Date();`
