### ISSUE TITLE
Table: Multiple selection with SHIFT/click does not work together with paginator and lazy loading

### ISSUE THREAD

**Issue by aabruc** [primefaces/primeng#14140]
### Describe the bug

We have problems with the multi select via SHIFT/click in tables. 
The problem occurs when you have set a paginator and then try a multi select on the second page (it works perfectly on the first). 
All rows up to the end, starting with the anchor row, are selected.
The demo table on PrimeNg works, but ours does not. 
The difference is the lazy load, which is not combined in the demo table. 
I added this to Stackblick and indeed the multi select no longer works properly.

### Environment

The example environment

### Reproducer

https://stackblitz.com/edit/mkvney-7dpojm?file=src%2Fapp%2Fdemo%2Ftable-multiple-selection-demo.ts

### Angular version

16

### PrimeNG version

16.3.1 and higher / The example environment

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

The example environment

### Steps to reproduce the behavior

1. Switch button 'MetaKey' should be on
2. Goto table page two
3. Select one row 
4. Try to select a block of rows (maybe three rows) via SHIFT/click
5. All rows up to the end, starting with the anchor row, are selected incorrectly

### Expected behavior

Should be clear ;)

**Comment by mnhock** [comment]
Can confirm the bug.

**Comment by vinnyab28** [comment]
Please find the PR for the fix here: https://github.com/primefaces/primeng/pull/14209

**Comment by quentin-ineat-ca** [comment]
Works fine for the bug.

Doing "shift + click" on the 2nd page after doing a previous selection on another page acts as a new selection.
Is this the expected behaviour ?
