### ISSUE TITLE
Dropdown: Crashes with console error if both filter and virtualScroll are enabled

### ISSUE THREAD

**Issue by thesam** [primefaces/primeng#14146]
### Describe the bug

1. Enable both "filter" and "virtualScroll".
2. Type anything in the filter input field.
3. The component crashes. The items are not filtered and there is an error in the console.
![image](https://github.com/primefaces/primeng/assets/667010/19e58edb-e832-4ff2-86a8-73ed6f45109b)
![image](https://github.com/primefaces/primeng/assets/667010/43020a9c-049f-43b6-8dcf-b3da2536f056)

### Environment

Stackblitz
Firefox/Chrome
Ubuntu Linux

### Reproducer

https://stackblitz.com/edit/w2hg1n?file=src%2Fapp%2Fdemo%2Fdropdown-virtualscroll-demo.html

### Angular version

16.2.0

### PrimeNG version

16.7.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

N/A

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
