### ISSUE TITLE
Table ColumnFilter menu buttons not displaying the Plus or Trash Icon

### ISSUE THREAD

**Issue by barbGit2** [primefaces/primeng#14157]
### Describe the bug

(U) The table does not include an @NgModule import for the TrashIcon or the PlusIcon used by the #menu.  I believe this is why those icons are no longer displayed in the Filter menu buttons "Add Rule" or "Remove Rule"

### Environment

Currently using PrimeNG 16, but I do not see an import for PlusIcon or TrashIcon in master as well.

### Reproducer

https://primeng.org/table#filter

### Angular version

16.2.9

### PrimeNG version

16.5.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.20.2

### Browser(s)

Chrome

### Steps to reproduce the behavior

You can see this issue in the PrimeNG documentation page at https://primeng.org/table#filter :

1. Click the filter button in any column header 
2.  Look at the "Add Rule" button, the "+" icon is missing (it used to be "+ Add Rule").  
3.  Add any value to filter the table and click 'Add Rule'
4.  Add a rule > A "Remove Rule" button is added; however, it no longer displays the 'trash' icon.  It used to be '"trash icon" Remove Rule'

### Expected behavior

- In the table column filter menu, the "Add Rule" button should be "+ Add Rule"
- In the table column filter menu, the "Remove Rule button should be "'trash icon' Remove Rule"

**Comment by cervenf** [comment]
Hi,
it seems like button text is now missing completely
![image](https://github.com/primefaces/primeng/assets/1408155/204fa295-a491-4edb-87f0-4c34177bd382)
It is on https://primeng.org/table#filter version 17.1.0
Thank you.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
