### ISSUE TITLE
Dropdown does not have the same width of the input when appendTo="body"

### ISSUE THREAD

**Issue by urielzen** [primefaces/primeng#14159]
### Describe the bug

This issue was not present in primeng v.16.6.X, but after upgrading to 16.7.x and now 16.8.0 the issue has started appearing.

v16.6.x
![image](https://github.com/primefaces/primeng/assets/7947179/5334a972-8553-4773-8fe6-9c4d03e9ad13)

v.16.8.0
![image](https://github.com/primefaces/primeng/assets/7947179/0fe0bcf2-b2b6-4ac9-b6e6-884e3de7488c)

this happens when appendTo="body" attribute is present.

Thanks!

### Environment

VSCode + Windows

### Angular version

16

### PrimeNG version

16.8.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.17.1

### Browser(s)

Chrome

**Comment by cetincakiroglu** [comment]
Thanks for reporting the issue
