### ISSUE TITLE
Component: ConfirmDialog

### ISSUE THREAD

**Issue by reramjiawan** [primefaces/primeng#14160]
### Describe the bug

The ConfirmDialog supports customization through ng-templates. However when looking at the source code I noticed that not the correct element, ng-container, is used as the templateOutlet for several templates. I have created a PR that resolves this.

### PR

[PR](https://github.com/primefaces/primeng/pull/14154)

### Angular version

16.2.12

### PrimeNG version

16.8.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.x.x

### Steps to reproduce the behavior

1.) use ngTemplate for ConfirmDialog message and you will notice it will not be rendered correctly once openend.

### Expected behavior

Correct support for ngTemplate for all required elements inside ConfirmDialog

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
