### ISSUE TITLE
DataTable : rowStyleClass doesn't play well with Angular architecture.

### ISSUE THREAD

**Issue by jdpearce** [primefaces/primeng#1416]
I'm submitting a ...
```
[ x] bug report ?
```
This is an implementation issue, really.

**Current behavior**
The DataTable inlines the function that you use for determining the rowStyleClass. Considering this will almost certainly be coming from the component presenter class, it should at the very least bind that function to the class instance somehow.

It also doesn't play well with the style scoping. If I put my row styles in the component.scss file, Angular will scope them to be say, "oddRow[_ngcontent-smo-15]" and "evenRow[_ngcontent-smo-15]", which is determined at runtime (afaik) - the DataTable needs to modify the classes returned with this attribute selector. The issue above makes solving this second part challenging, to say the least - I haven't yet figured out a way to inject ElementRef into an inlined function.

Lastly, it seems to call the rowStyleClass function *a lot*. I was clicking a button elsewhere on a page containing a DataTable and the whole table was being rechecked on each click. I don't know if this is down to the way Angular 2 notifies regarding drawing the screen, but it seems excessive.

(Apologies for creating what might be 3 issues in one - I think the architecture of this feature needs to be revisited, so solving any one issue might well invalidate the other two)

**Please tell us about your environment:**
Windows 7, Visual Studio Code, npm, angular-cli

* **Angular version:** 2.2.1

* **PrimeNG version:** 1.0.0

* **Browser:** Chrome 54
 
* **Language:** TypeScript 2.0.3

* **Node (for AoT issues):** `node --version` = v6.9.1

**Comment by jdpearce** [comment]
Just a thought, but would it be possible to invert the behaviour? i.e. make the row styling event based and we have a row style handler? You could then pass in the row data, a handle to the row element itself, perhaps with a setStyle method the handler can use which already knows what the element reference is?

**Comment by Thavarajan** [comment]
actually you can use the '/deep/ '
that will almost eliminate the attribute in angular2

**Comment by jdpearce** [comment]
@Thavarajan You might need to explain that one. I have absolutely no idea how your comment relates to this issue 😣

**Comment by cagataycivici** [comment]
@jdpearce, I'd be glad to use ngClass in this case but rowData is not available to the page author as it is created when we loop the data to create TRs with ngFor. The scope of rowData variable is not exposed to your outer component that uses p-dataTable. So although I'm not 100% happy with current impl, it is the only working solution we've found. We're open to other suggestions though, not sure how can do it event based, Angular does not provide an event that we can expose when TR elements are created.

**Comment by jdpearce** [comment]
Ok, so it sounds a lot more tricky than I imagined, thanks for reviewing this. I might take a look myself and if I get anywhere I'll let you know.

**Comment by Thavarajan** [comment]
hi @jdpearce 
 sorry for the delayed reply

> It also doesn't play well with the style scoping. If I put my row styles in the component.scss file, Angular will scope them to be say, "oddRow[_ngcontent-smo-15]" and "evenRow[_ngcontent-smo-15]", which is determined at runtime (afaik) - the DataTable needs to modify the classes returned with this attribute selector. The issue above makes solving this second part challenging, to say the least - I haven't yet figured out a way to inject ElementRef into an inlined function.

For this scenario i suggessted the solution /deep/
please see [this link ](https://angular.io/docs/ts/latest/guide/component-styles.html) 

hope it helps you

**Comment by jdpearce** [comment]
@cagataycivici I've had a think about this. I will admit my knowledge of A2 is not very deep as yet, so I may be off track, but would it be possible to encapsulate all the row behaviour in a separate component (DataTableRow?) and then leverage the lifecycle hooks to provide events? (You could do a lot more than simple styling with this kind of approach, I think)

I appreciate this would be a really big change though...

**Comment by laserus** [comment]
@cagataycivici I suggested a PR for better addressing of this. https://github.com/primefaces/primeng/pull/2583

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
