### ISSUE TITLE
Docs/Demo: Programatic Paginator is missing key line in HTML

### ISSUE THREAD

**Issue by Phil-DS** [primefaces/primeng#14168]
### Describe the bug

https://primeng.org/table#paginator-programmatic claims that you can bind the 'first' value to allow programatic pagination. However, the example code is lacking the key line. Compare it to the working code in the docs, and the equivalent in the examples, you see the line is available in the live one and not the example code blocks.

Working Current Code
https://github.com/primefaces/primeng/blob/f7f13481d6485deea6b13539edc09e5b54697601/src/app/showcase/doc/table/paginatorprogrammaticdoc.ts#L19-L29
Basic code example
https://github.com/primefaces/primeng/blob/f7f13481d6485deea6b13539edc09e5b54697601/src/app/showcase/doc/table/paginatorprogrammaticdoc.ts#L106-L115
HTML code example
https://github.com/primefaces/primeng/blob/f7f13481d6485deea6b13539edc09e5b54697601/src/app/showcase/doc/table/paginatorprogrammaticdoc.ts#L146-L155

### Environment

https://primeng.org/table#paginator-programmatic

### Angular version

16.x.x

### PrimeNG version

16.8.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

Current

**Comment by GeorgFritze** [comment]
still in 17.0.0

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
