### ISSUE TITLE
Table: 'Not equals' filter not working correctly

### ISSUE THREAD

**Issue by bibinf** [primefaces/primeng#14179]
### Describe the bug

Hi,

I've noticed that the 'Not equals' filter is somehow not working correctly. If one types in some characters and deletes them afterwards, the table shows an empty result. Even without clicking the "Apply" button.

Besides that I think it should not filter without "Apply", the result is also not correct because != '' should show all non-empty records instead of an empty table.

Best regards and thanks for your effort,
Sebastian

### Environment

Windows 10

### Angular version

16.X.X

### PrimeNG version

16.8.0 but older versions as well

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.1

### Steps to reproduce the behavior

1. Go to https://primeng.org/table#filter
2. Select 'Not equals' filter of first column
3. Enter 'test'
4. Delete 'test'
5. Table gets filtered without 'Apply' and returns an empty table instead of complete example data

### Expected behavior

The filter should not fire automatically without apply.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by bibinf** [comment]
I've retried the steps. It's still not working.

**Comment by markusramsak** [comment]
This issue still exists
