### ISSUE TITLE
Calendar issues with time

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#1417]
Reported by a PRO user;

* Displays wrong numbers when set to hourFormat="12". Should only be 1 to 12. 
* Displays wrong numbers higher than 24, which should never happen at all.

```
<p-calendar [formControlName]="model.id" 
hourFormat="12"
[showTime]="true"
[timeOnly]="true" 
[readonlyInput]="true" ></p-calendar>
```

**Comment by bomberblue07** [comment]
Can you please work on #1150 while you're at it, too?
