### ISSUE TITLE
InputSwitch does not have transitionOptions as property

### ISSUE THREAD

**Issue by lufo88ita** [primefaces/primeng#14181]
### Describe the bug

In this old issue
https://github.com/primefaces/primeng/issues/6652
he said 
"Introduce new transitionOptions property to components with animations to make it customizable"
But InputSwitch does not have this property, so it is not possible to customize the animation from checked to unchecked and viceversa.

### Environment

Windows 10

### Angular version

16,2

### PrimeNG version

16.8.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.20.2

### Browser(s)

Chrome

### Steps to reproduce the behavior

Just check the documentation

### Expected behavior

transitionOptions must be available

**Comment by cetincakiroglu** [comment]
Hi,

We've future plans to update animations in PrimeNG, it's in our backlog for v17.

**Comment by mehmetcetin01140** [comment]
Hi, 

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
