### ISSUE TITLE
TabView Navbar hides last item / Wheelscroll not working anymore

### ISSUE THREAD

**Issue by helkatz** [primefaces/primeng#14182]
### Describe the bug

- on p-tabView when i use scrollable feature the right nav-button will not be hided when the last item is reached
- also navbutton is not hided when navitems do not exceed space!
- i think scrolling with mouse wheel worked already but here not

follow this stackblitz link to see
https://stackblitz.com/edit/rh87uy

### Environment

follow this stackblitz link to see
[(https://stackblitz.com/edit/rh87uy)]

### Angular version

16

### PrimeNG version

16

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

follow this stackblitz link to see
https://stackblitz.com/edit/rh87uy

**Comment by cetincakiroglu** [comment]
Hi,

Thanks for reporting the issue!

**Comment by helkatz** [comment]
@cetincakiroglu should this now work in 16.9.0?
because i tries and there is no change!

cheers

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
