### ISSUE TITLE
Component: TreeSelect

### ISSUE THREAD

**Issue by adcore-dev** [primefaces/primeng#14193]
### Describe the bug

All nodes in TreeSelect show amount of kids in it.
In prev. version it doesn't happen.
Can be reproduced directly in demo https://primeng.org/treeselect
![image](https://github.com/primefaces/primeng/assets/71829010/02fe0bd1-a7f2-463a-aef4-84eaee25e689)

### Environment

Angular version 16, 16.9.0

### Reproducer

https://codesandbox.io/s/g8jgr6

### Angular version

16.2.12

### PrimeNG version

16.9.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v16.16.0

### Browser(s)

Chrome 119.0.6045.159 (Official Build) (64-bit)

### Expected behavior

No children length in label or option not to show it
![image](https://github.com/primefaces/primeng/assets/71829010/f4a842a3-f777-4aa6-b98a-94b1bbf52f0e)
as workaround for now I used:
```
<ng-template pTemplate="default" let-node>
    {{node.label}}
  </ng-template>
```

**Comment by adcore-dev** [comment]
Just checking in - when might someone be able to take a look at the issue? Any updates would be greatly appreciated.

**Comment by jschu** [comment]
Fix available in mentioned issue [#14193](https://github.com/primefaces/primeng/issues/14193)

**Comment by adcore-dev** [comment]
@jschu 
Hey, but this workaround stop working when you add other template to component:
![image](https://github.com/primefaces/primeng/assets/71829010/223a3298-9309-4568-ae91-5ec646bb6f06)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
