### ISSUE TITLE
Dropdown Component

### ISSUE THREAD

**Issue by marinija** [primefaces/primeng#14190]
### Describe the bug

property [autoDisplayFirst]="true" not working anymore, it's not auto selecting the first dropdown option

### Environment

Angular version 16, 16.9.0

### Angular version

16.0.0

### PrimeNG version

16.9.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14.0

**Comment by alexnoise79** [comment]
2 Major releases and still this is not fixed? how possible?

**Comment by alexnoise79** [comment]
https://github.com/primefaces/primeng/blob/master/src/app/components/dropdown/dropdown.ts#L1082

value is null

**Comment by yarikwest** [comment]
See https://github.com/primefaces/primeng/issues/14426

**Comment by yarikwest** [comment]
> 1 Major and 3 minor releases and still this is not fixed? how possible?

https://github.com/primefaces/primeng/issues/14426

**Comment by PeterHewat** [comment]
> > 1 Major and 3 minor releases and still this is not fixed? how possible?
> 
> See #14426

It's a pity the documentation hasn't been updated: https://primeng.org/dropdown#api.dropdown.props.autoDisplayFirst

**Comment by digitalcraftco** [comment]
How do we handle async  as use cases now?
```
<div *ngIf="sendToChoices$ | async as options; else showLogin">
 <p-dropdown [(ngModel)]="comMethod" [options]="options" placeholder="Select"></p-dropdown>
</div>
  ```

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
