### ISSUE TITLE
pMultiSelect: The filter isn't working as it did before, specifically in terms of filtering by label

### ISSUE THREAD

**Issue by GeroSchaarmann** [primefaces/primeng#14194]
### Describe the bug

Previously, the filter defaulted to being filtered by "label" (observed in primeng version 16.6.0). However, this is no longer the case. To restore the desired previous behavior, you now need to incorporate the "filter field" for the filter to function.

### Environment

follow this stackblitz link to see

### Reproducer

https://stackblitz.com/edit/github-eleua3-w79tvq

### Angular version

16.2.12

### PrimeNG version

16.9.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14.0

### Steps to reproduce the behavior

Attempt to filter the users in the StackBlitz link; it is currently not functioning. Add the "label" to the filterField param now—it should resolve the issue. Alternatively, lower the version to observe the previous behavior.

**Comment by cetincakiroglu** [comment]
Fixed in https://github.com/primefaces/primeng/pull/14220
