### ISSUE TITLE
[Feature Request] DataTable: row-wise editability

### ISSUE THREAD

**Issue by TekSiDoT** [primefaces/primeng#142]
Sometimes it can be desirable to lock or enable editing not on the complete column of a table but on individual cells.

**Comment by cagataycivici** [comment]
Do you mean like the first datatable at;

http://www.primefaces.org/showcase/ui/data/datatable/edit.xhtml

**Comment by TekSiDoT** [comment]
No, not quite. Using the first table you're refering to there would be a mechanism to switch editing for individual cells. This could be based on either cell content itself or on some auxiliary data structure. Each data row would have to supply the information whether a specific value inside that row should be editable or not.

I realize this sounds complicated, but in the end it's an extension to the current format where table and column need the editable flag. The same would go for rows in *ngFor structures, possibly like this:

```
<p-dataTable [(value)]="limitsData" [editable]="true" (onRowSelect)="handleRowSelect($event)">
<p-column *ngFor="#col of limitsCols" [field]="col.field" [header]="col.header"  [editable]="col.editable">
        <template #col #car="rowData">
            <span [style.color]="car[col.field]" [editable]="car[col.editable]">{{car[col.field]}}</span>
        </template></p-column>
</p-dataTable>   
```

**Comment by rktawni** [comment]
I am looking feature like: 
http://www.primefaces.org/showcase/ui/data/datatable/edit.xhtml

in datagrid with angular2. 

I'll appreciate any help

**Comment by sanketsw** [comment]
I need the same. I want to have a date picker in the Date column of my editable data table

**Comment by dmitrynovik** [comment]
This is a very much needed feature indeed. As I understand, there is no way to have cell-level editability at the moment, it's either whole column editable or not.

**Comment by sanketsw** [comment]
This issue should be labeled as enhancement.

**Comment by nkagarw** [comment]
Row-wise editing like we have in primefaces is desirable. Can we put this enhancement in the next beta milestone maybe for beta 19 ?

**Comment by cagataycivici** [comment]
Comments have different requirements and request is not clear. Moved the request to roadmap called row based editing, will pick it up and create a new ticket later after 1.0.

https://github.com/primefaces/primeng/wiki/Roadmap

**Comment by katrina-engelbrecht** [comment]
Hi, 
I need this row based editing function for p-datatable urgently. When this new feature will be added into primeNG datatable?

**Comment by vinodkumar526** [comment]
When this row editable feature in ang4 will come on the road?
referance:http: //www.primefaces.org/showcase/ui/data/datatable/edit.xhtml

**Comment by cagataycivici** [comment]
Our estimate is within 2 months.

**Comment by venkatsub24** [comment]
Hi, 
Has cell level editing has been incorporated in primeng? I have searched a lot for this, but have ended up here. If yes, can anyone pls explain how to use?

Thanks.

**Comment by Chi1985** [comment]
Hi,

Has the cell level editing been implemented in PrimeNg datatable?

**Comment by gabrielalack** [comment]
Bump!
