### ISSUE TITLE
Component: Table & Scroller

### ISSUE THREAD

**Issue by wS2Zth** [primefaces/primeng#14205]
### Describe the bug

EN:
When using Lazy Load with Virtual Scroll in the table component, the onLazyLoad function always works twice (the lazyLoadOnInit flag has no effect).

(If I remember correctly, this problem has been going on since the Virtual Scroll implementation was changed, not specifically related to the PrimeNG 17 release.)

---

TR:
Table component'inde Virtual Scroll ile Lazy Load kullanıldığında, onLazyLoad fonksiyonu iki kez çalışıyor (lazyLoadOnInit'in bu duruma bir etkisi yok). 

(Yanlış hatırlamıyorsam, bu sorun Virtual Scroll implementasyonu değiştirildiğinden beri devam ediyor, özellikle PrimeNG 17 versiyonu ilgili değil.)

### Environment

Angular : 17
PrimeNG : 17
Arc Browser
macOS Sonomo 14.1.1 

### Reproducer

https://stackblitz.com/edit/github-a4wbfw

### Angular version

17.0.3

### PrimeNG version

17.0.0-beta.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v18.18.2

**Comment by cetincakiroglu** [comment]
Fixed in https://github.com/primefaces/primeng/pull/14206
