### ISSUE TITLE
Picklist source and target items are not rendered as disabled when the picklist is disabled since the v16.9.0 release.

### ISSUE THREAD

**Issue by Antelope-IT** [primefaces/primeng#14200]
Prior to v16.9.0, when the picklist is disabled the p-disabled class is added to the class list of each of the list items in the source and target lists. 

As a result of the duplication of the ngClass directive [here](https://github.com/primefaces/primeng/blame/c83a830d72d60344c79b5708f6770926af0e9760/src/app/components/picklist/picklist.ts#L168) and [here](https://github.com/primefaces/primeng/blame/c83a830d72d60344c79b5708f6770926af0e9760/src/app/components/picklist/picklist.ts#L276) this is no longer the case.

The values returned from the ngClass directive [here](https://github.com/primefaces/primeng/blame/c83a830d72d60344c79b5708f6770926af0e9760/src/app/components/picklist/picklist.ts#L272) and [here](https://github.com/primefaces/primeng/blame/c83a830d72d60344c79b5708f6770926af0e9760/src/app/components/picklist/picklist.ts#L272)

 `[ngClass]="{ 'p-picklist-item': true, 'p-highlight': isSelected(item, selectedItemsTarget), 'p-disabled': disabled }"` 
 
  that provided the class list prior to v16.9.0, with the p-disabled functionality, is overwritten by the value returned from the function itemClass [here](https://github.com/primefaces/primeng/blame/c83a830d72d60344c79b5708f6770926af0e9760/src/app/components/picklist/picklist.ts#L1246) (shown below)
 ```
 itemClass(item, id, selectedItems) {
    return {
        'p-picklist-item': true,
        'p-highlight': this.isSelected(item, selectedItems),
        'p-focus': id === this.focusedOptionId
    };
}
```
It appears that the issue can most easily be fixed by removing the duplication and merging the return values of the itemClass function so that it returns

 ```
itemClass(item, id, selectedItems) {
   return {
      'p-picklist-item': true,
      'p-highlight': this.isSelected(item, selectedItems),
      'p-focus': id === this.focusedOptionId,
      'p-disabled': disabled
   };
}

```

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
