### ISSUE TITLE
Module: BrowserAnimationsModule compatibility

### ISSUE THREAD

**Issue by Khumain** [primefaces/primeng#14207]
### Describe the bug

Hello wonderful Team,

I noticed that with the new Angular 17 update and a full standalone app (no modules), I am unable to make animations work correctly. I tried the [following configuration](https://angular.dev/guide/animations#enabling-the-animations-module):
```js
import { ApplicationConfig } from '@angular/core';
import { provideRouter } from '@angular/router';

import { routes } from './app.routes';
import {provideAnimationsAsync} from "@angular/platform-browser/animations/async";

export const appConfig: ApplicationConfig = {
  providers: [
    provideRouter(routes),
    provideAnimationsAsync()
  ]
};
```
but it does not seem to animate buttons (hover functionalities for example).

### Environment

Windows 11
Node v18.17.1
Npm v8.16.0

### Angular version

17.0.3

### PrimeNG version

17.0.0-beta.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.17.1

### Browser(s)

Firefox 120.0

### Steps to reproduce the behavior

Simply with `<p-button label="Submit"></p-button>`

### Expected behavior

The button should show a pointer cursor and change its color on hover or click

**Comment by cetincakiroglu** [comment]
Hi,

We're using the same thing in our app.config.ts for PrimeNG Showcase. It works in our demos, maybe you're missing something, could you please check available guides of v17 in angular.dev

**Comment by Khumain** [comment]
Hello @cetincakiroglu you were right, I forgot `@import "primeng/resources/primeng.min.css"` in my styles.css file. You guys are amazing, thank you for keeping such a great library up to date!
