### ISSUE TITLE
Component: Table paginator error  - 16.8.0 <-> 16.9.1

### ISSUE THREAD

**Issue by jaman7** [primefaces/primeng#14204]
### Describe the bug

Describe the bug
on paginator when chagne table page
ERROR TypeError: Cannot read properties of undefined (reading 'firstChange')

v16.6.0  its ok

### Environment

No response

### Angular version

16.2.12

### PrimeNG version

16.8.0 and 16.9.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.0

**Comment by cetincakiroglu** [comment]
Could you please share a stackblitz reproducer so we can identify the issue clearly?

**Comment by akbarhafeezbutt** [comment]
Thanks @jaman7 due to your comment, I've used the v16.6.0 now my error has been solved. 
ERROR TypeError: Cannot read properties of undefined (reading 'firstChange')

Thank alot.
