### ISSUE TITLE
Table: FilterMatchMode for boolean is CONTAINS, but should be EQUALS

### ISSUE THREAD

**Issue by wertzui** [primefaces/primeng#14210]
In this line, `FilterMatchMode.EQUALS` is only returned for `"number"`, but not for `"boolean"`.
https://github.com/primefaces/primeng/blob/34757378b2c6e43b422fbd0ac3648116cedbfe40/src/app/components/table/table.ts#L5375

For `"boolean"` it falls back to the default case of `FilterMatchMode.CONTAINS` which does not make sence for boolean types.

For `"boolean"` the `FilterMatchMode` should be `FilterMatchMode.EQUALS`.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
