### ISSUE TITLE
Placeholder text shows with the initial value of the dropdown

### ISSUE THREAD

**Issue by twmobius** [primefaces/primeng#14219]
### Describe the bug

I think this is related to #14094. I am getting at a state where both the p-dropdown placeholder and the initial value in a reactive form component are both shown at the same time. 

As seen in the screenshot here:

![CleanShot 2023-11-28 at 00 11 59](https://github.com/primefaces/primeng/assets/854155/ef9c57f0-8a3a-4a09-b676-6fe65c7ffe39)

 I think it happens because the options are being lazy loaded and the form is `patchValue()`d before the options are being populated. Something related to the `label()` method perhaps (https://github.com/primefaces/primeng/blob/master/src/app/components/dropdown/dropdown.ts#L918C1-L922C8)

### Environment

I've tried it with primeng 16.6.0 and 16.7.2, and it doesn't happen

### Reproducer

https://stackblitz.com/edit/qxhoel-3xpawg

### Angular version

16.2.12

### PrimeNG version

16.8.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.1

**Comment by cetincakiroglu** [comment]
Hi,

Couldn't replicate the behavior in the latest PrimeNG, it may have fixed within 16.9 and 17.0.0-beta.1. Please see the working example: https://stackblitz.com/edit/u9wypz?file=src%2Fapp%2Fdemo%2Fdropdown-reactive-forms-demo.ts,src%2Fapp%2Fdemo%2Fdropdown-reactive-forms-demo.html

**Comment by twmobius** [comment]
I can verify that it works as expected on 16.9.0, I've updated by stackblitz to 16.9.0 and it works.
