### ISSUE TITLE
Component: p-inputNumber big issues with mode=currency and currency property

### ISSUE THREAD

**Issue by erber014** [primefaces/primeng#14227]
### Describe the bug

Currency mode with certain currencies seems to be messy. Test for example typing in a negative amount in the euro field in
[https://primeng.org/inputnumber#currency](https://primeng.org/inputnumber#currency). When you do the cursor jumps to the end of the input field and you cannot enter anything without placing the cursor somewhere in the number manually using your mouse. The euro currency is not the only one with issues, just check the official inputNumber page...

### Environment

[https://primeng.org/inputnumber#currency](https://primeng.org/inputnumber#currency)

### Angular version

Whatever the official site uses

### PrimeNG version

v17.0.0-beta.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

Whatever the official site uses

### Steps to reproduce the behavior

[https://primeng.org/inputnumber#currency](https://primeng.org/inputnumber#currency)

### Expected behavior

Currency mode should work properly for all supported currencies..

**Comment by NadyKazi** [comment]
[https://stackoverflow.com/questions/65895980/primeng-p-inputnumber-unable-to-enter-negative-fractional-numbers/78701723#78701723](url)
refer this link

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by mertsincan** [comment]
@uebelmar, details; https://github.com/primefaces/primeng/issues/17069
