### ISSUE TITLE
Component: Multi-select does not work correctly in custom filter

### ISSUE THREAD

**Issue by MatheusGomes01** [primefaces/primeng#14226]
### Describe the bug

![image](https://github.com/primefaces/primeng/assets/35032498/0bb39f85-2de9-4444-b27e-50cfd507566a)

In the image above, you can see that the item is being printed on the left side, but the item does not appear when I copy and paste it into the filter, but if I type character by character, there will be times when it will appear and there will be times that won't

### Environment

This test is being in a development environment

### Angular version

14

### PrimeNG version

14

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14.2

### Browser(s)

Chrome

### Steps to reproduce the behavior

Create a custom filter, which calls a response from an API, copy something that is not in the initial load, but that exists in the API and then it will not find the item.
The API must search for the requested name if it is not in the initial load

### Expected behavior

When you put something that exists in the return, it prints

**Comment by ashikjs** [comment]
can you share any code with us?

**Comment by MatheusGomes01** [comment]
The code is confidential, i cannot share it due to company policies.

But here is an example that is semi-identical to the one constructed, where
the difference is just the name of the variables.

html:

<p-multiSelect [options]="accounts" [(ngModel)]="selectedAccounts"
defaultLabel="Select a Country" optionLabel="name" optionValue="id"
class="multiselect-custom" selectdItemsLabel="{0} iteem selected"
[filter]=true (onFilter)="accountFilter($event)">
</p-multiSelect>

ts:

accountFilter(event){
    this.store.dispatch(AccountsRequest({params: {account: event.filter}}));

    // The following methods are for dealing with success and failure, on
success it displays a success message, subscribes to the accounts action to
get the returned accounts and gives a false when loading the table, the
error only gives a false on the loading and displays an error message
    this.accountFilterSuccess()
    this.accountFilterFailure()
}

Remembering that the methods above work and I can print the result on the
screen, the method contains pagination in the back-end, so when I search
for something that is on one of the following pages, it does not print in
the multi-select component, but prints in the screen if I leave the print,
but if I open the multi-select with the value initially loaded, it prints
in the multi-select too, but the searches do not occur as expected


Em qua., 29 de nov. de 2023 às 12:02, MD Ashik ***@***.***>
escreveu:

**Comment by MatheusGomes01** [comment]
The code is confidential, i cannot share it due to company policies.

But here is an example that is semi-identical to the one constructed, where the difference is just the name of the variables.

html:

<p-multiSelect [options]="accounts" [(ngModel)]="selectedAccounts" defaultLabel="Select a Country" optionLabel="name" optionValue="id" class="multiselect-custom" selectdItemsLabel="{0} iteem selected" [filter]=true (onFilter)="accountFilter($event)">
</p-multiSelect>

ts:

accountFilter(event){
    this.store.dispatch(AccountsRequest({params: {account: event.filter}}));

    // The following methods are for dealing with success and failure, on success it displays a success message, subscribes to the accounts action to get the returned accounts and gives a false when loading the table, the error only gives a false on the loading and displays an error message
    this.accountFilterSuccess()
    this.accountFilterFailure()
}

Remembering that the methods above work and I can print the result on the screen, the method contains pagination in the back-end, so when I search for something that is on one of the following pages, it does not print in the multi-select component, but prints in the screen if I leave the print, but if I open the multi-select with the value initially loaded, it prints in the multi-select too, but the searches do not occur as expected

**Comment by MatheusGomes01** [comment]
@ashikjs Could you give me some feedback?

**Comment by MatheusGomes01** [comment]
@ashikjs Could you clarify better? I don't understand it correctly, it seems like the error won't be dealt with
