### ISSUE TITLE
Component: Calendar Year picker

### ISSUE THREAD

**Issue by bkindzierski** [primefaces/primeng#14233]
### Describe the bug

When adding  a p-calendar using a formControlName  and using the "year" view, the component does not display the years. and receives the following error:

> ERROR TypeError: Y.getFullYear is not a function 
>     at an.isYearSelected (calendar.ts:1680:56)
my example: 
<p-calendar formControlName="myid" view="year" dateFormat="yy"></p-calendar>

### Environment

I am seeing this when running ng serve on localhost

### Angular version

17

### PrimeNG version

16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.9.0

### Browser(s)

chrome

### Steps to reproduce the behavior

Add the example code from primeng website version 17 beta to form using a formControlName  instead of [(ngModel])

**Comment by mgecmez** [comment]
I have a similar problem. Because, for example, I tried to set the year 2024 to the calendar and it gave this error.

**Comment by tindezeeuw** [comment]
We have the same problem with a calendar in the range selection mode. 
The problem is in the isYearSelected(year: number) function of the calendar.ts. I will open a PR for this

**Comment by picagianluca** [comment]
Hi, this issue was fixed for calendar component (now deprecated and removed) but the same problem still on datepicker. Could you please fix also the datepicker component?
