### ISSUE TITLE
Carousel: Different output of carousel compared to localhost and deployment

### ISSUE THREAD

**Issue by Tickets14** [primefaces/primeng#14237]
### Describe the bug

Im currently using Carousel to display a list of product. In localhost everything is perfect but when I deploy my project the layout of carousel changes. How do i fix this?
here is the output from my localhost:
![localhost](https://github.com/primefaces/primeng/assets/53848311/a91a235f-e924-40c7-aaa6-502012e99f19)

here is the output when i deploy it:
![deployment](https://github.com/primefaces/primeng/assets/53848311/30d7b4ca-dcd1-43ed-ac38-a7286a776f4c)

### Environment

in S3 

### Angular version

16.2.11

### PrimeNG version

16.9.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.0

### Expected behavior

Here is my expected output:
![localhost](https://github.com/primefaces/primeng/assets/53848311/45d86c2c-36ee-418f-a9ef-13db730050b1)

**Comment by ashikjs** [comment]
@Tickets14 understand your issue, We need a reproduceable path or code. Can you try to generate it in stackblitz.com

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
