### ISSUE TITLE
Vertical tree structure with same layout as horizontal

### ISSUE THREAD

**Issue by zeljkohuber** [primefaces/primeng#1423]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Tree structure has 2 default layouts: horizontal and vertical. Vertical is presented more like "folder structure" while horizontal is presented as binary tree.

**Expected behavior**
Is it possible somehow to implement vertical layout but with same look as the one in horizontal? I'm not sure if I can somehow override tree-node component to create my own template, since current template that can be set within p-tree doesn't actually affect the main layout of the tree but only minor inner part which is nested within the base layout.

**Minimal reproduction of the problem with instructions**

* **Angular version:** 2.1.1

* **PrimeNG version:** 1.0.0-beta.20

* **Browser:** [all]

 
* **Language:** [TypeScript 2.0.6 | ES2015]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Fixed via #2992
