### ISSUE TITLE
Dropdown: filterBy not working. 

### ISSUE THREAD

**Issue by castrovini85** [primefaces/primeng#14235]
### Describe the bug

After setting which property I want to filter from, the component still uses the label.

### Environment

I saw it on my localhost and was able to reproduce it on stackblitz.

### Reproducer

https://stackblitz.com/edit/nqejfj-qma9qg?file=src%2Fapp%2Fdemo%2Fdropdown-filter-demo.ts

### Angular version

17.0.0

### PrimeNG version

17.0.0-beta.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20

### Steps to reproduce the behavior

Here I add the `filterText` property to the countries example from the website.
![image](https://github.com/primefaces/primeng/assets/4996281/43868557-83ad-499a-b364-11ee3c80e9c8)

I also changed the `filterBy` option on the HTML
![image](https://github.com/primefaces/primeng/assets/4996281/b041a90e-b9ac-4cd1-b5d9-ef1cba830b51)

When I search for '1' or '2', nothing shows up
![image](https://github.com/primefaces/primeng/assets/4996281/95c5c4e0-231b-40b3-8096-827736763f5a)
![image](https://github.com/primefaces/primeng/assets/4996281/cb91868d-cd15-4e1a-85a0-c38f278b6cfe)

If I search by anything that matches the labels, it is filtering
![image](https://github.com/primefaces/primeng/assets/4996281/9cd3b65c-4e72-4219-805d-1b0171221c06)

### Expected behavior

After setting the `filterBy` to a property of the object, it should be filtering by it, not the label.

**Comment by ashikjs** [comment]
@castrovini85 you missed the documentation checked here https://primeng.org/dropdown#api.dropdown.props.filterFields 

you have to mention `filterFields` with array like this. `[filterFields]="['filterText']"`

you can check  it here, https://stackblitz.com/edit/nqejfj-jpabs9?file=src%2Fapp%2Fdemo%2Fdropdown-filter-demo.ts
