### ISSUE TITLE
pSortableColumn in ngContainer not triggering sorting

### ISSUE THREAD

**Issue by flkeller** [primefaces/primeng#14231]
### Describe the bug

Hi,

i am trying to create a custom table component which wraps p-table.

but i want to use the integrated sorting of pSortableColumn.

With that aproach i am getting a console error

ERROR NullInjectorError: R3InjectorError(AppModule)[Table -> Table]: 
  NullInjectorError: No provider for Table!
    at NullInjector.get (provider_collection.ts:49:1)
    at R3Injector.get (r3_injector.ts:322:4)
    at R3Injector.get (r3_injector.ts:322:4)
    at ChainedInjector.get (component_ref.ts:158:22)
    at lookupTokenUsingModuleInjector (di.ts:379:34)
    at getOrCreateInjectable (di.ts:426:1)
    at ɵɵdirectiveInject (shared.ts:69:7)
    at NodeInjectorFactory.SortableColumn_Factory [as factory] (ɵfac.js:1:1)
    at getNodeInjectable (di.ts:671:36)
    at instantiateAllDirectives (shared.ts:1053:1)

i could add Table and TableService to providers in app module, but that does not solve the problem. 
The sorting is rendered correctly, but the sorting functionality in the background is not triggered.

I assume that when i provide just Table and TableService on my own in app module, they do not have the correct p-table in the background.

Is there any way to do that?

Thanks and best regards.

### Environment

windows 10
chrome
ide:  rider

### Reproducer

https://stackblitz.com/edit/github-5emdsv

### Angular version

16.2.12

### PrimeNG version

16.6.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

17.0.0

### Browser(s)

Chrome

### Expected behavior

sorting should work with ng-container in template

**Comment by Urtgard** [comment]
In my wrapper component for p-table I use the following approach:

Use `@ViewChild` to save a reference of your table in your wrapper component.
```js
@ViewChild(Table, { static: true }) table: Table;
```

Use a factory to provide not any table but the table used in your component.
```js
providers: [
    {
      provide: Table,
      useFactory: (component: AppComponent): Table => component.table,
      deps: [AppComponent],
    },
  ],
```
---
From my own experience: Think about whether you really need a wrapper component or a directive could do the job as well

**Comment by flkeller** [comment]
Thanks very much, works perfect.

Did not know that this is possible.
