### ISSUE TITLE
CSP TrustedType does not work with Carousel component

### ISSUE THREAD

**Issue by benjaminknauer** [primefaces/primeng#14257]
### Describe the bug

The Carousel component does not work with Content-Security-Policy that enforces trusted-types.

See also: #12855 and #11050

```
 ERROR TypeError: Failed to set the 'innerHTML' property on 'Element': This document requires 'TrustedHTML' assignment.
    at Carousel.createStyle (primeng-carousel.mjs:376:37)
    at Carousel.ngAfterContentInit (primeng-carousel.mjs:248:18)
    at callHookInternal (core.mjs:3940:14)
    at callHook (core.mjs:3967:13)
    at callHooks (core.mjs:3922:17)
    at executeInitAndCheckHooks (core.mjs:3872:9)
    at refreshView (core.mjs:12939:21)
    at detectChangesInView (core.mjs:13062:9)
    at detectChangesInEmbeddedViews (core.mjs:13006:13)
    at refreshView (core.mjs:12922:9)
```

![image](https://github.com/primefaces/primeng/assets/4982360/50445d0d-0a19-4f0a-bd1d-618d3c7a56c9)

### Environment

Normal Angular CLI Project

### Angular version

16.1.8

### PrimeNG version

16.9.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.2

### Browser(s)

Chrome

### Steps to reproduce the behavior

Add to angular.json

```
"serve": {
    "options": {
        "headers": {
            "Content-Security-Policy": "trusted-types angular; require-trusted-types-for 'script';"
        }
    }
}
```

Use a CarouselComponent.

### Expected behavior

Should work with CSP headers.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
