### ISSUE TITLE
Component: Sidebar

### ISSUE THREAD

**Issue by Sp94dev** [primefaces/primeng#14254]
### Describe the bug

When trying to close the sidebar, the sidebar-mask disappears but the component stays open.
(onHide) is not triggered.

### Environment

Standard angular application

### Reproducer

https://stackblitz.com/edit/774ddz?file=src%2Fapp%2Fdemo%2Fsidebar-basic-demo.html

### Angular version

17.1.0

### PrimeNG version

17.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v18.17.0.

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Open sidebar
2. Close sidebar

### Expected behavior

(onHide) should call closeSidebar method

**Comment by eXpertise7** [comment]
My experience is that I can tell that if `[(visible)]` `ngModel` variable if `p-sidebar` has two race conditions (two booleans), and if we manipulate these booleans one `p-sidebar` will set `(onHide)` `EventEmitter `correctly, but it will not set second `p-sidebar `(destroy a component there) in the same view.

**Splitting these two race conditions from one `p-sidebar`, into two  separate `p-sidebar`'s at my hide did the trick (no issues anymore), but issue is persistent still with p-sidebar in mentioned case.**

I hope that'll help some of users to temporarily fix that at your codebase, and that PrimeNG team will find what's the issue quicker.

**Comment by eXpertise7** [comment]
> @eXpertise7 could You show an example?

I've different case, I'm using normal public boolean variables, not Signal's.

Before it was this, it has worked in the primeng@15.2.0 (my version):
```
<!-- <p-sidebar
  position="right"
  [(visible)]="showFirstSidebarContent || showSecondSidebarContent"
  (onHide)="closeSidebar()">
    <app-first-component *ngIf="showFirstSidebarContent "></app-first-component>
    <app-second-component *ngIf="showSecondSidebarContent "></app-second-component>
</p-sidebar>

```
  closeSidebar(): void {
    // apply sidebar flags because we have 2 conditions in 2 way databinding visible prop
    // usually we don't need this approach
    this.showFirstSidebarContent = false;
    this.showSecondSidebarContent = false;
  }
```

On primeng@16.9.0 it does not work.

So I needed to split (without using (onHide) event method):


```
<p-sidebar
  position="right"
  [(visible)]="showFirstSidebarContent "
>
  <app-first-component *ngIf="showFirstSidebarContent "></<app-first-component>
</p-sidebar>
```

```
<p-sidebar
  position="right"
  [(visible)]="showSecondSidebarContent"
>
  <app-second-component *ngIf="showSecondSidebarContent "></app-admin-group-guide>
</p-sidebar>
```

This is not issue solve of `p-sidebar`, this could be just for some people temporarily workaround.

**Comment by Sp94dev** [comment]
Ahh yes, In my case setting [modal]=false helps a little but it is not a solution because I lost overlay and a click outside of sidebar behaviours.

**Comment by gabboman** [comment]
In my case it worked fine with primeng16 in general, but when updated to angular 17 started getting this issue too. Temporaly I will set modal to false

**Comment by gabboman** [comment]
Issue still happens at 17.1.0

**Comment by mountpoint** [comment]
in version 17.3.0 when you try to close **programatically** by setting [(visible)]="isVisible" sidebar disappears but the mask stays visible
![Screenshot 2023-12-28 181058](https://github.com/primefaces/primeng/assets/2649412/bdb313f2-bc7d-4c11-818a-ac913dafdfff)

**Comment by cetincakiroglu** [comment]
> @cetincakiroglu
> 
> in version 17.3.0 when you try to close **programatically** by setting [(visible)]="isVisible" sidebar disappears but the mask stays visible. So I downgraded back to 17.2.0 ![Screenshot 2023-12-28 181058](https://private-user-images.githubusercontent.com/2649412/293238974-bdb313f2-bc7d-4c11-818a-ac913dafdfff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4MzAyNjIsIm5iZiI6MTcwMzgyOTk2MiwicGF0aCI6Ii8yNjQ5NDEyLzI5MzIzODk3NC1iZGIzMTNmMi1iYzdkLTRjMTEtODE4YS1hYzkxM2RhZmRmZmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDIzMTIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjlUMDYwNjAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGQxZGRhNmExYjhmNTk3NzExMTgyZjNlNjMxNTE1YTQxM2UxZmZhMDAzNDk5Nzk2ZjJkYjg0OWQ4ZWMzOWY0NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uO0-nlotxGbAiaRIbA97OXYZEumQjDPlpRdvIn_lklk)

could you please create a separate issue with a stackblitz reproducer for this?

**Comment by riker09** [comment]
Maybe this is helpful. I have a p-menu component inside the p-sidebar and when I click on one of the menu items the p-sidebar is closed and if I _immediately_ spam-click on the p-overlay it gets closed sometimes? It reliably works with one specific link in my menu while others don't.

**Comment by Melliche** [comment]
Hello, the problem is still present with the latest versions of Angular 17, if I modify the value of visible, the onHide event is not triggered, I use these dependencies:

` "dependencies": {
    "@angular/animations": "^17.3.11",
    "@angular/cdk": "^17.3.10",
    "@angular/common": "^17.3.11",
    "@angular/compiler": "^17.3.11",
    "@angular/core": "^17.3.11",
    "@angular/forms": "^17.3.11",
    "@angular/platform-browser": "^17.3.11",
    "@angular/platform-browser-dynamic": "^17.3.11",
    "@angular/router": "^17.3.11",
    "@jsverse/transloco": "^7.4.2",
    "angular-oauth2-oidc": "13.0.1",
    "dayjs": "^1.11.11",
    "lodash": "^4.17.21",
    "ngx-highlightjs": "^7.0.1",
    "primeflex": "^3.3.1",
    "primeicons": "^6.0.1",
    "primeng": "^17.18.1",
    "rxjs": "~7.8.1",
    "tslib": "^2.6.2",
    "uuid": "^9.0.0",
    "zone.js": "~0.14.7"
  },`
