### ISSUE TITLE
Problem using PrimeNG with TailwindCSS

### ISSUE THREAD

**Issue by MoInMaRvZ** [primefaces/primeng#14255]
### Describe the bug

When using primeng and tailwindcss together the preflight styles from tailwind overwrite the some styles from primeng. 

Buttons and borders are primarily affected by this. All borders are missing. The Table is not striped with p-datatable-striped set in styleClass

### Environment

I am using node 20 with angulat 17. The problem also occurs with version 16

### Angular version

17

### PrimeNG version

17

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20

### Browser(s)

Every Browser

### Steps to reproduce the behavior

1. Create angular Project
2. Install primeng as described in primeng docs
3. Install tailwindcss as described in tailwind docs
4. Add button and inputs 

### Expected behavior

The PrimeNG Styles should be more important than the tailwind preflight styles.
The Button should render its background colors and all borders should be displayed correct.

**Comment by dalenguyen** [comment]
Looks like it's the same as https://github.com/primefaces/primeng/issues/13757

**Comment by moohkooh** [comment]
Same issue also from my side. I create a fresh new project Angular 17, tailwind 3.4.0 and primeNG 17.1.0 e.g. Button are broken

<img width="97" alt="image" src="https://github.com/primefaces/primeng/assets/3660216/5c3ce342-6123-4e0f-a34f-d6c13b955c94">

**Comment by i-am-milap** [comment]
Try this

@import "tailwindcss/base" layer(tailwindcss);
@import "tailwindcss/components" layer(tailwindcss);
@import "tailwindcss/utilities" layer(tailwindcss);

**Comment by i-am-milap** [comment]
Try this

```
@import 'tailwindcss/base' layer(tailwindcss);
@import 'tailwindcss/components' layer(tailwindcss);
@import 'tailwindcss/utilities' layer(tailwindcss);

@import 'primeng/resources/themes/lara-light-blue/theme.css';
@import 'primeng/resources/primeng.css';
```
[Refrance](https://www.reddit.com/r/Angular2/comments/179c2j9/has_anyone_got_tailwind_and_primeng_to_work/)

**Comment by BeGj** [comment]
In angular 17 when using the new builder `@angular-devkit/build-angular:application` and putting tailwindcss styles in a layer like:
```css

@layer tailwind-base, primeng, tailwind-utilities;

@import "tailwindcss/base" layer(tailwind-base);
@import "tailwindcss/components" layer(tailwind-utilities);
@import "tailwindcss/utilities" layer(tailwind-utilities);

@import "primeng/resources/themes/lara-light-blue/theme.css";
@import "primeng/resources/primeng.css";
```

It does not automatically add new tailwindcss classes to your build when using ng serve. Instead, if you ONLY put the preflight/reset in the layer then tailwindcss will add the classes. The following fix makes it so that you dont have to restart ng serve for every tailwindcss class change

```css
@layer tailwind-base, primeng;

@import "tailwindcss/base" layer(tailwind-base);
@tailwind components;
@tailwind utilities;

@import "primeng/resources/themes/lara-light-blue/theme.css";
@import "primeng/resources/primeng.css";
```

**Comment by saiful-70** [comment]
How I solved the problem for me.

1. putting exactly this order in angular.json
```json
// angular.json
 "styles": [
        "src/styles.scss",
        "node_modules/primeng/resources/themes/lara-light-blue/theme.css",
        "node_modules/primeng/resources/primeng.min.css"
 ],
```


2. Finally in your global CSS file([official documentation](https://primeng.org/guides/csslayer#tailwind))
```scss
// styles.scss
@layer tailwind-base, primeng, tailwind-utilities;

@layer tailwind-base {
  @tailwind base;
}

@layer primeng; //not necessary I think

@layer tailwind-utilities {
  @tailwind components;
  @tailwind utilities;
}```

**Comment by Triskae** [comment]
Same issue here 
When using the solution above, it works partially, everything seems to work fine except for responsive classes in tailwind.... When I use xl:flex for example, the style appears in the browser code inspector, but the UI does not update accordingly, can you confirm that you have also this problem ?  

> How I solved the problem for me.
> 
> 1. putting exactly this order in angular.json
> 
> ```json
> // angular.json
>  "styles": [
>         "src/styles.scss",
>         "node_modules/primeng/resources/themes/lara-light-blue/theme.css",
>         "node_modules/primeng/resources/primeng.min.css"
>  ],
> ```
> 
> 2. Finally in your global CSS file([official documentation](https://primeng.org/guides/csslayer#tailwind))
> 
> ```css-scss
> // styles.scss
> @layer tailwind-base, primeng, tailwind-utilities;
> 
> @layer tailwind-base {
>   @tailwind base;
> }
> 
> @layer primeng; //not necessary I think
> 
> @layer tailwind-utilities {
>   @tailwind components;
>   @tailwind utilities;
> }```
> ```

**Comment by luismejia1** [comment]
> Same issue here When using the solution above, it works partially, everything seems to work fine except for responsive classes in tailwind.... When I use xl:flex for example, the style appears in the browser code inspector, but the UI does not update accordingly, can you confirm that you have also this problem ?
> 
> > How I solved the problem for me.
> > 
> > 1. putting exactly this order in angular.json
> > 
> > ```json
> > // angular.json
> >  "styles": [
> >         "src/styles.scss",
> >         "node_modules/primeng/resources/themes/lara-light-blue/theme.css",
> >         "node_modules/primeng/resources/primeng.min.css"
> >  ],
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. Finally in your global CSS file([official documentation](https://primeng.org/guides/csslayer#tailwind))
> > 
> > ```
> > // styles.scss
> > @layer tailwind-base, primeng, tailwind-utilities;
> > 
> > @layer tailwind-base {
> >   @tailwind base;
> > }
> > 
> > @layer primeng; //not necessary I think
> > 
> > @layer tailwind-utilities {
> >   @tailwind components;
> >   @tailwind utilities;
> > }```
> > ```



Responsive styles work for me after implement this solution, the only difference is that apart from all that, I added a prefix in tailwind.config.js file:

![image](https://github.com/primefaces/primeng/assets/84051009/94a021e4-9f8d-455f-a343-f5a60bed1bef)

**Comment by paelsam** [comment]
I solved the problem by changing the order of the primeng imports

```css
/* Tailwind CSS */

@layer tailwind-base, primeng, tailwind-utilities;

/* Primeng Settings */
@import "primeng/resources/primeng.css";
@import "primeng/resources/themes/mira/theme.css";
@import "primeicons/primeicons.css";

@layer tailwind-base {
    @tailwind base;
}

@layer tailwind-utilities {
    @tailwind components;
    @tailwind utilities;
}

```

**Comment by Stephan-MC** [comment]
i found a solution which works for me on angular 17.3


```scss
// src/styles.scss

/* You can add global styles to this file, and also import other style files */
@layer base, primeng, components, utilities, variants;

// Please take note of the order in which these are imported
@import "tailwindcss/base.css" layer(base);
@import "primeng/resources/primeng.min.css";
@import "primeng/resources/themes/tailwind-light/theme.css";
@import "primeicons/primeicons";
@import "tailwindcss/components.css" layer(components);
@import "tailwindcss/utilities.css" layer(utilities);
@import "tailwindcss/variants.css" layer(variants);

@layer base {
  @tailwind base;
  * {
    @apply transition-all duration-300 ease-in-out;
  }
}

@layer components {
  @tailwind components;
}

@layer utilities {
  @tailwind utilities;
}

@layer variants {
  @tailwind variants;
}

```

the image below shows the order of each layer in the browser

![image](https://github.com/primefaces/primeng/assets/77833621/0337610b-b3cf-46d0-ab16-07f5f7f56e6c)

**Comment by puschie286** [comment]
provided solutions in this thread create nested layers for tailwing, which cause problems with pseudo selectors for custom classes (:hover, :focus and so on). to fix this, you need to keep the original layers - simplest way i found is to create a file with the layer structure
```
// src/layer.css
@layer base, primeng, components, utilities;
```
and than import all layers in your main css
```
// src/styles.css
@import 'primeng/resources/primeng.min.css';
/** IMPORT STYLE HERE **/

@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {}
@layer components {}
@layer utilities {}
```
you can also import custom themes after your main css in angular.json

**Comment by flier268** [comment]
It is easy to use:
https://primeng.org/guides/csslayer#tailwind
```scss
@layer tailwind-base, primeng, tailwind-utilities;
        
@layer tailwind-base {
    @tailwind base;
}

@layer tailwind-utilities {
    @tailwind components;
    @tailwind utilities;
}
```
And, **Add `preflight: false` to corePlugins**
```json

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  theme: {
    extend: {},
  },
  plugins: [],
  corePlugins: { preflight: false }
}
```

**Comment by dilincoln** [comment]
This one seems to fit the best solution because in the case that we set preflight to false, we lost some CSS Reset Utilities from Tailwind.

> i found a solution which works for me on angular 17.3
> 
> ```css-scss
> // src/styles.scss
> 
> /* You can add global styles to this file, and also import other style files */
> @layer tw-base, primeng, tw-components, tw-utilities, tw-variants;
> 
> // Please take note of the order in which these are imported
> @import "tailwindcss/base.css" layer(tw-base);
> @import "primeng/resources/primeng.min.css";
> @import "primeng/resources/themes/tailwind-light/theme.css";
> @import "primeicons/primeicons";
> @import "tailwindcss/components.css" layer(tw-components);
> @import "tailwindcss/utilities.css" layer(tw-utilities);
> @import "tailwindcss/variants.css" layer(tw-variants);
> 
> @layer tw-base {
>   * {
>     @apply transition-all duration-300 ease-in-out;
>   }
> }
> 
> @layer tw-components {
>     // tailwind component classes here
> }
> 
> @layer tw-utilities {
>     // tailwind utitlity classes here
> }
> ```
> 
> the image below shows the order of each layer in the browser ![image](https://private-user-images.githubusercontent.com/77833621/320054450-bb23b327-d6ee-484a-a7af-aff68d4c8412.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NjM1NDAsIm5iZiI6MTcxNTk2MzI0MCwicGF0aCI6Ii83NzgzMzYyMS8zMjAwNTQ0NTAtYmIyM2IzMjctZDZlZS00ODRhLWE3YWYtYWZmNjhkNGM4NDEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDE2MjcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3OWM3MmE0OThiZGNiMDYzN2Y1ZmRjNzVjODdkNWEyZmExYmM0OWZmNWJmNzZiOWY3ODlhNDVjYzQ0ZDdlODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lRKHQHNcTvcWmTa8p13SL1I96F0VMawFXAbUi3oVzrY)

**Comment by 11Firefox11** [comment]
@Stephan-MC 's [solution](https://github.com/primefaces/primeng/issues/14255#issuecomment-2039838008) worked for me too. Only thing I had to change was to put the `.css` file extension at the end of the line containing primeicons.

**Comment by gitadam0** [comment]
> ```json
> corePlugins: { preflight: false }
> ```

why add the `preflight`

because just adding this to my css file is enough 
@layer tailwind-base, primeng, tailwind-utilities;

```
@layer tailwind-base {
  @tailwind base;
}

@layer tailwind-utilities {
  @tailwind components;
  @tailwind utilities;
}
```

**Comment by BeGj** [comment]
> i found a solution which works for me on angular 17.3
> 
> ```css-scss
> // src/styles.scss
> 
> /* You can add global styles to this file, and also import other style files */
> @layer tw-base, primeng, tw-components, tw-utilities, tw-variants;
> 
> // Please take note of the order in which these are imported
> @import "tailwindcss/base.css" layer(tw-base);
> @import "primeng/resources/primeng.min.css";
> @import "primeng/resources/themes/tailwind-light/theme.css";
> @import "primeicons/primeicons";
> @import "tailwindcss/components.css" layer(tw-components);
> @import "tailwindcss/utilities.css" layer(tw-utilities);
> @import "tailwindcss/variants.css" layer(tw-variants);
> 
> @layer tw-base {
>   * {
>     @apply transition-all duration-300 ease-in-out;
>   }
> }
> 
> @layer tw-components {
>     // tailwind component classes here
> }
> 
> @layer tw-utilities {
>     // tailwind utitlity classes here
> }
> ```
> 
> the image below shows the order of each layer in the browser ![image](https://private-user-images.githubusercontent.com/77833621/320054450-bb23b327-d6ee-484a-a7af-aff68d4c8412.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5OTIxMjEsIm5iZiI6MTcyMDk5MTgyMSwicGF0aCI6Ii83NzgzMzYyMS8zMjAwNTQ0NTAtYmIyM2IzMjctZDZlZS00ODRhLWE3YWYtYWZmNjhkNGM4NDEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDIxMTcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NWUxODhhODg3N2FlMWEzMzk0MTgwNjRjY2UyMTIwMTgzODMzOTQ3ZTMwYTI2OTM5MmZkYjVjN2E3ZDg2NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.In7KdPdpvlaGR120-Fjg7mAvaiFB_6vrwFzQmbmCEOM)

I just started a new angular 18.1 project today and incredibly enough I ran into problems with tailwindcss and primeng layers once again. The tailwindcss preflight removed all button characteristics. This quoted response was the ONLY solution among all the various threads on the topic that solved it. Not sure why tho..

**Comment by thatoneprogrammer111** [comment]
I am on Angular 18.0.3 and I've tried everything I could find, yet nothing worked. The only thing that worked for me (after A LOT of trial and error) is this:
```css
@import 'tailwindcss/base.css' layer(tailwind);
@import 'tailwindcss/components.css' layer(tailwind);
@import 'tailwindcss/utilities.css' layer(tailwind);
@import 'primeflex/primeflex.css' layer(prime);
@import 'primeng/resources/themes/lara-light-blue/theme.css' layer(prime);
@import 'primeng/resources/primeng.css' layer(prime);
```You can put anything in `layer(prime)`, so `layer(abc)` also works.
I cannot tell you why this works, but it does (at least for me).

**Comment by gitadam0** [comment]
> I am on Angular 18.0.3 and I've tried everything I could find, yet nothing worked. The only thing that worked for me (after A LOT of trial and error) is this:
> 
> ```css
> @import 'tailwindcss/base.css' layer(tailwind);
> @import 'tailwindcss/components.css' layer(tailwind);
> @import 'tailwindcss/utilities.css' layer(tailwind);
> @import 'primeflex/primeflex.css' layer(prime);
> @import 'primeng/resources/themes/lara-light-blue/theme.css' layer(prime);
> @import 'primeng/resources/primeng.css' layer(prime);
> ```
> 
> You can put anything in `layer(prime)`, so `layer(abc)` also works. I cannot tell you why this works, but it does (at least for me).
> 
> EDIT: After some more testing, you can name the `tailwind` layer anything you want as well.

good luck
did you try my solution right above:

https://github.com/primefaces/primeng/issues/14255#issuecomment-2166916267

**Comment by rui-branco** [comment]
For me this order of things worked. 

Angular 18.1.0
PrimeNG 17.18.8

```
@layer tailwind-base, primeng, tailwind-utilities;

@layer tailwind-base {
    @tailwind base;
}

@layer primeng {
    @import 'primeng/resources/primeng.css';
    @import 'primeicons/primeicons.css';
}
@layer tailwind-utilities {
    @tailwind components;
    @tailwind utilities;
}

```

**Comment by phalla-doll** [comment]
Any update on this? The official solution provided by PrimeNG seemed to NOT working.

    @layer tailwind-base, primeng, tailwind-utilities;

    @layer tailwind-base {
         @tailwind base;
     }

    @layer tailwind-utilities {
         @tailwind components;
         @tailwind utilities;
    }

**Comment by phalla-doll** [comment]
> > I am on Angular 18.0.3 and I've tried everything I could find, yet nothing worked. The only thing that worked for me (after A LOT of trial and error) is this:
> > ```css
> > @import 'tailwindcss/base.css' layer(tailwind);
> > @import 'tailwindcss/components.css' layer(tailwind);
> > @import 'tailwindcss/utilities.css' layer(tailwind);
> > @import 'primeflex/primeflex.css' layer(prime);
> > @import 'primeng/resources/themes/lara-light-blue/theme.css' layer(prime);
> > @import 'primeng/resources/primeng.css' layer(prime);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You can put anything in `layer(prime)`, so `layer(abc)` also works. I cannot tell you why this works, but it does (at least for me).
> > EDIT: After some more testing, you can name the `tailwind` layer anything you want as well.
> 
> good luck did you try my solution right above:
> 
> [#14255 (comment)](https://github.com/primefaces/primeng/issues/14255#issuecomment-2166916267)

Thanks @gitadam0 , your solution worked on my project as well (v17) but dynamic theming will be a pain in the butt.

**Comment by thatoneprogrammer111** [comment]
Hey again, so I solved most of my issues with 1 thing:
I accidentally loaded it twice, once in the `styles.css`, and directly through the `angular.json`.
If anyone encounters this in the future: Try to only load the `styles.css` in your `angular.json`

**Comment by somq** [comment]
Found another workaround since _tailwind base_ was also clashing with _primeng_ for us; ugly but does the job.

I simply reverted the tailwind base layer that was overwriting primeng classes with `all: revert-layer !important;`.

```scss
@layer tailwind, prime;

@import 'tailwindcss/base.css' layer(tw-base);

@import 'assets/layout/styles/layout/layout.scss' layer(prime);
@import 'primeicons/primeicons.css' layer(prime);

@import 'assets/layout/styles/theme/tailwind/tailwind-light/theme.scss' layer(prime);
@import 'primeng/resources/primeng.css';

@import 'tailwindcss/components.css' layer(tw-components);
@import 'tailwindcss/utilities.css' layer(tw-utilities);
@import 'tailwindcss/variants.css' layer(tw-variants);

@layer tw-base {
  [type='text'],
  [type='email'],
  [type='url'],
  [type='password'],
  [type='number'],
  [type='date'],
  [type='datetime-local'],
  [type='month'],
  [type='search'],
  [type='tel'],
  [type='time'],
  [type='week'],
  [multiple],
  textarea,
  select {
    all: revert-layer !important;
  }
}
```

**Comment by gitadam0** [comment]
> Found another workaround since _tailwind base_ was also clashing with _primeng_ for us; ugly but does the job.
> 
> I simply reverted the tailwind base layer that was overwriting primeng classes with `all: revert-layer !important;`.
> 
> ```css-scss
> @layer tailwind, prime;
> 
> @import 'tailwindcss/base.css' layer(tw-base);
> 
> @import 'assets/layout/styles/layout/layout.scss' layer(prime);
> @import 'primeicons/primeicons.css' layer(prime);
> 
> @import 'assets/layout/styles/theme/tailwind/tailwind-light/theme.scss' layer(prime);
> @import 'primeng/resources/primeng.css';
> 
> @import 'tailwindcss/components.css' layer(tw-components);
> @import 'tailwindcss/utilities.css' layer(tw-utilities);
> @import 'tailwindcss/variants.css' layer(tw-variants);
> 
> @layer tw-base {
>   [type='text'],
>   [type='email'],
>   [type='url'],
>   [type='password'],
>   [type='number'],
>   [type='date'],
>   [type='datetime-local'],
>   [type='month'],
>   [type='search'],
>   [type='tel'],
>   [type='time'],
>   [type='week'],
>   [multiple],
>   textarea,
>   select {
>     all: revert-layer !important;
>   }
> }
> ```
> 
> Works for the datatable for now, will probably run into more surprises when we get into the implementation of other primeng components...

nice workaround
this was my solution
https://github.com/primefaces/primeng/issues/14255#issuecomment-2166916267

**Comment by gitadam0** [comment]
> > > I am on Angular 18.0.3 and I've tried everything I could find, yet nothing worked. The only thing that worked for me (after A LOT of trial and error) is this:
> > > ```css
> > > @import 'tailwindcss/base.css' layer(tailwind);
> > > @import 'tailwindcss/components.css' layer(tailwind);
> > > @import 'tailwindcss/utilities.css' layer(tailwind);
> > > @import 'primeflex/primeflex.css' layer(prime);
> > > @import 'primeng/resources/themes/lara-light-blue/theme.css' layer(prime);
> > > @import 'primeng/resources/primeng.css' layer(prime);
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > You can put anything in `layer(prime)`, so `layer(abc)` also works. I cannot tell you why this works, but it does (at least for me).
> > > EDIT: After some more testing, you can name the `tailwind` layer anything you want as well.
> > 
> > 
> > good luck did you try my solution right above:
> > [#14255 (comment)](https://github.com/primefaces/primeng/issues/14255#issuecomment-2166916267)
> 
> Thanks @gitadam0 , your solution worked on my project as well (v17) but dynamic theming will be a pain in the butt.

no problem brother, what do you mean by dynamic theming

**Comment by jmpussacq** [comment]
Hello,

If you've encountered issues with the order of CSS layers when using PrimeNG, avoid using both `.scss` and `.css` files simultaneously.

Make sure not to import files with the `.css` extension for PrimeNG (or for other libraries, if applicable). This is because SASS will import `.css` files before `.scss` files

For example in your `styles.scss` file :

```
@layer tailwind-base, primeng, tailwind-utilities, my-app;

@layer tailwind-base {
  @tailwind base;
}

@import "primeng/resources/themes/bootstrap4-light-blue/theme";
@import "primeng/resources/primeng";

@layer tailwind-utilities {
  @tailwind components;
  @tailwind utilities;
}

@layer my-app {
  @import 'styles/custom';
}
```

I hope this helps ! :)

**Comment by phalla-doll** [comment]
How do you switch between themes (light/dark)? Because using "@import" is not dynamic.

**Comment by docentYT** [comment]
Tailwind preflight still overrides primeng classes in 19.0.2.

My `app.config.ts`:
```ts
import { ApplicationConfig, provideZoneChangeDetection } from '@angular/core';
import { provideRouter } from '@angular/router';
import { appRoutes } from './app.routes';
import { provideClientHydration } from '@angular/platform-browser';
import { provideAnimations } from '@angular/platform-browser/animations';
import { provideHttpClient, withFetch } from '@angular/common/http';
import { providePrimeNG } from 'primeng/config';
import { LocalePl } from './primeng.pl.locale';
import Aura from '@primeng/themes/aura';

export const appConfig: ApplicationConfig = {
  providers: [
    provideClientHydration(),
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(appRoutes),
    provideAnimations(),
    provideHttpClient(withFetch()),
    providePrimeNG({
      ripple: true,
      translation: LocalePl,
      theme: {
        preset: Aura,
        options: {
          cssLayer: {
              name: 'primeng',
              order: 'tailwind-base, primeng, tailwind-utilities'
          },
      }

      }
    })
  ],
};
```

`styles.scss`:
```scss
@import 'primeicons/primeicons.css';
@layer tailwind-base, primeng, tailwind-utilities;

@layer tailwind-base {
@tailwind base;
}

@layer tailwind-utilities {
@tailwind components;
@tailwind utilities;
}

// import Quill styles in styles.scss
@import 'quill/dist/quill.core.css';
@import 'quill/dist/quill.snow.css';
```
