### ISSUE TITLE
Dart support

### ISSUE THREAD

**Issue by theiceguy** [primefaces/primeng#1425]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
Run the .d.ts files thru this tool to provide dart support on pub.dartlang.org
https://github.com/dart-lang/sdk/issues/24874

**Current behavior**

No dart support

**Expected behavior**

We need a dart package

**Minimal reproduction of the problem with instructions**

no dart support

**What is the motivation / use case for changing the behavior?**

broader developer audience

**Please tell us about your environment:**

dart on linux

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [all]

 chrome, ff, ie

* **Language:** [TypeScript X.X]
dart

* **Node (for AoT issues):** `node --version` =

**Comment by tabinnorway** [comment]
This would be awesome

**Comment by yigitfindikli** [comment]
We'll reconsider if there is more community feedback on this. Thank you for your report.
