### ISSUE TITLE
Doc: Steps close menu

### ISSUE THREAD

**Issue by puschie286** [primefaces/primeng#14259]
### Describe the bug

when you click on [steps](https://primeng.org/steps/), the menu closes and the entry is not marked as active

### Environment

browser

### Angular version

Not relevant

### PrimeNG version

17.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

not relevant

### Browser(s)

Current chrome / firefox

### Steps to reproduce the behavior

1. open https://primeng.org/steps/
2. see closed menu -> open menu
3. see missing 'router-link-active' on steps menu entry

**Comment by mehmetcetin01140** [comment]
Fixed in #15850
