### ISSUE TITLE
Component : Paginator is disabled by default when there are no records in the table , prime ng version 15.0.0

### ISSUE THREAD

**Issue by gauravpatni123** [primefaces/primeng#14261]
### Describe the bug

I am using paginator and when there are no records in the table the paginator is disabled by default , I want to make it enabled irrespective whether there are records in the table or not , please suggest how this can be done or let me know if there is any specific property for that .

### Environment

it is in the Development environment or local environment

### Angular version

15

### PrimeNG version

15.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.21.2

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
