### ISSUE TITLE
Component: Paginator Dropdown Accessibility in 16.9.1

### ISSUE THREAD

**Issue by GMacAussie** [primefaces/primeng#14260]
### Describe the bug

Running Accessibility Insights for Web (Microsoft) plugin on Basic Paginator Demo shows accessibility issues with the dropdown. See attached dropdown open/closed reports.
[PrimeNG-16.9.1-PaginatorBasic-open.pdf](https://github.com/primefaces/primeng/files/13517177/PrimeNG-16.9.1-PaginatorBasic-open.pdf)
[PrimeNG-16.9.1-PaginatorBasic-closed.pdf](https://github.com/primefaces/primeng/files/13517178/PrimeNG-16.9.1-PaginatorBasic-closed.pdf)

### Environment

Microsoft Edge Version 119.0.2151.72 (Official build) (64-bit)
Windows 10 Pro Version	10.0.19045 Build 19045

### Reproducer

https://stackblitz.com/edit/k8ueix?file=package.json

### Angular version

16.2.0

### PrimeNG version

16.9.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

x.x.x

### Steps to reproduce the behavior

1. Run the Accessibility Insights for Web extension (Chrome or Edge) in the Basic Paginator page. It will report errors with the dropdown while closed
2. Open the Paginator dropdown and restart Accessibility Insights for Web. It will report errors with the dropdown while open

### Expected behavior

No accessibility issues are reported.

**Comment by cetincakiroglu** [comment]
Hi,

Thanks for reporting the issue, this issue is covered in #14358 and it's fixed. I've tested with the extension you've mentioned and the issue does not exist anymore with https://github.com/primefaces/primeng/commit/c77dbbb4219eca029d29ab96bd7772ecfaa5baa4

Closing the issue and removing from the milestone.
