### ISSUE TITLE
Component: SelectButton Accessibility in 16.9.1

### ISSUE THREAD

**Issue by GMacAussie** [primefaces/primeng#14266]
### Describe the bug

Running Accessibility Insights for Web (Microsoft) plugin on Basic SelectButton shows accessibility issues with the 'buttons' having an invalid aria-pressed="true" attribute, raising an aria-allowed-attr error. See attached document.

NOTE: There is a contrast error but that is easily addressed via CSS.
[PrimeNG-16.9.1-SelectButtonBasic.pdf](https://github.com/primefaces/primeng/files/13531686/PrimeNG-16.9.1-SelectButtonBasic.pdf)

### Environment

Microsoft Edge Version 119.0.2151.72 (Official build) (64-bit)
Windows 10 Pro Version 10.0.19045 Build 19045

### Reproducer

https://stackblitz.com/edit/tdv4xo?file=package.json

### Angular version

16.2.0

### PrimeNG version

16.9.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

x.x.x

### Steps to reproduce the behavior

1. Run the Accessibility Insights for Web extension (Chrome or Edge) in the Basic SelectButton page. It will report the ARIA attribute errors

### Expected behavior

No accessibility issues are reported.

**Comment by WTW-Jacob-Evans** [comment]
hey, we are also encountering this issue. We are using Primeng version 17.11
![image](https://github.com/primefaces/primeng/assets/163871134/fe0ead8e-a370-4cba-9079-9b41244a305b)

Highlighted by Axe DevTools
