### ISSUE TITLE
Component: Table

### ISSUE THREAD

**Issue by abhishekk-raj** [primefaces/primeng#14263]
### Describe the bug

Table's row selection length calculation is incorrect if I select some rows and delete it. 

### Environment

Standard angular application

### Reproducer

https://stackblitz.com/edit/github-wsf8m1?file=src%2Fapp%2Fapp.component.html

### Angular version

16.2.11

### PrimeNG version

16.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.1

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Enter First name, Last name, Email and select role
2. It should add a new blank row
3. Select the row which has data filled, now you can notice Delete Member button should be enabled and selected row count should be 1
4. Press the Delete Member button to delete the row
5. Now no row is selected but still you can see selected row count is 1 that is incorrect 

### Expected behavior

After deleting row since no row is selected so selected row count should be 0.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
