### ISSUE TITLE
Component: MultiSelect - Filter not working for grouped items

### ISSUE THREAD

**Issue by jpgoelz** [primefaces/primeng#14278]
### Describe the bug

When using grouped select items for the MultiSelect component, filtering no longer works, even for SelectItems that have a label property. It is now necessary to explicitly specify `optionLabel="label"`, which is a regression.
The same is true for `optionValue="value"`. The whole select item is being emitted, if this is not provided.

The problem can be seen in the demo for grouped items on the PrimeNG website: https://www.primefaces.org/primeng-v16/multiselect#group.

![image](https://github.com/primefaces/primeng/assets/32487587/26090d14-c8c9-45cf-94ca-9fca0f1636d7)

![image](https://github.com/primefaces/primeng/assets/32487587/71773ada-4e34-4bc0-928a-1574e981d666)

### PrimeNG versions

16.9.1, 17.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Steps to reproduce the behavior

1. Add a MultiSelect component with `SelectItemGroup` that use `SelectItem[]`.
2. Use the filter to filter for items. Nothing will be found.
3. Add `optionLabel="label"` and `optionValue="value"` and try again. Elements will be found.

### Expected behavior

When using default SelectItems, `label` and `value` should not need to be specified as an `optionLabel` resp. an `optionValue`.

**Comment by RinoGaetano94** [comment]
Same problem with Dropdown component: filter doesn't work without explicit set  `optionLabel="label"`

**Comment by hemal-panchasara** [comment]
with optionLabel="label" it will filter but group name is not coming along with the label. primeng 17. angular 17

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
