### ISSUE TITLE
Component: Dropdown does not render the options that have a group property

### ISSUE THREAD

**Issue by tsinevik** [primefaces/primeng#14276]
### Describe the bug

Similar to this issue #14061 Dropdown component won't render an option when it has `group` property. I believe the same solution to mentioned issue should be applied to Dropdown component when it's deciding which template to use.

<img width="872" alt="image" src="https://github.com/primefaces/primeng/assets/43264254/b7334671-e30f-48b1-9cc9-9d68aa834864">

### Environment

Any environment

### Reproducer

(https://stackblitz.com/edit/ee5k5j?file=src%2Fapp%2Fdemo%2Fdropdown-basic-demo.ts)

### Angular version

17.0.0

### PrimeNG version

17.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Steps to reproduce the behavior

Add a `group` property to any option.

https://stackblitz.com/edit/ee5k5j?file=src%2Fapp%2Fdemo%2Fdropdown-basic-demo.ts

### Expected behavior

The items should be rendered OR the docs should warn that `group` cannot be used as a property.

**Comment by cetincakiroglu** [comment]
Hi,

It's not a bug, you're using component wrong and sending not supported options format for grouping. Please see the example: https://stackblitz.com/edit/ph9ucn?file=src%2Fapp%2Fdemo%2Fdropdown-group-demo.ts,src%2Fapp%2Fdemo%2Fdropdown-group-demo.html
