### ISSUE TITLE
tag as pill not working

### ISSUE THREAD

**Issue by pjlasl** [primefaces/primeng#14275]
### Describe the bug

I upgraded PrimeNG from v15 to v16.9 and noticed that all of my tags with attribute [rounded]=true do not show rounded edges.

### Environment

I am running angular 16.2.12 and primeng 16.9.1. 

If I revert back to v15 of PrimeNG everything works as expected.

### Angular version

16.2.12

### PrimeNG version

16.9.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.5.0

### Browser(s)

Google Chrome

### Steps to reproduce the behavior

Add tag element and use the [rounded]=true attribute

### Expected behavior

The tag is expected to have rounded corners (pills).

**Comment by cetincakiroglu** [comment]
Please see the examples 
v16.9.1: https://www.primefaces.org/primeng-v16/tag#pill
v17: https://primeng.org/tag#pill

**Comment by pjlasl** [comment]
I'm not convinced this is completed...I looked at the examples
As I noted in my example I am using [rounded]=true and v16.9.1 is not honoring that.

Something is kosher moving from 15 to 16...
