### ISSUE TITLE
p-tableCheckbox not getting checked

### ISSUE THREAD

**Issue by prnkrawat** [primefaces/primeng#14274]
### Describe the bug

p-tableCheckbox is not getting checked from outside based on some condition.
I have to mark checkbox true based on some condition, how can we do that?

### Environment

Local

### Angular version

16

### PrimeNG version

16

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.1

### Browser(s)

chrome

### Expected behavior

Checked property should work

**Comment by cetincakiroglu** [comment]
Hi,

Could you please ask how-to questions in discord channel to get support fast from the community. PrimeLand Discord: https://discord.gg/gzKFYnpmCY
