### ISSUE TITLE
Version 16 autoComplete (onFocus) does not really support with handleDropdownClick, 

### ISSUE THREAD

**Issue by piyalcodes** [primefaces/primeng#14279]
https://github.com/primefaces/primeng/blob/e8620e4c88795a30fc6bc730d7be4f4b446db75d/src/app/components/autocomplete/autocomplete.ts#L1030

It seems the Version 16 does not really work the way it should work for handleDropdownClick with (onFocus),

this is what we are using for the method of (onFocus): 
`this.autoComplete.handleDropdownClick(new Event('void'));`
(the idea here is when click on input field, we need to open the dropdown. and when select an option, it needs to close)

What happened now: 
After option selected from the dropdown, it keep showing. and it does not hide the dropdown.

Guide us with example for the fix or let us know if it can be fixed from the library level?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
