### ISSUE TITLE
p-dropdown: when filtering, placeholder is displayed even if there is a selected option

### ISSUE THREAD

**Issue by estellepicq** [primefaces/primeng#14282]
### Describe the bug

- p-dropdown uses [filter]="true" feature
- An option is already selected in the dropdown ✅
- The dropdown displays the selected option label ✅
- Open the overlay again to search for another option ✅
- Type in the filter input ✅
- The dropdown displays the placeholder above the selected option label ❌

![image](https://github.com/primefaces/primeng/assets/33844394/b62abaef-40f7-496e-b211-609692d33dd4)

It should keep displaying the selected option label.

### Environment

PrimeNG official documentation: https://primeng.org/dropdown#filter

### Reproducer

https://primeng.org/dropdown#filter

### Angular version

17.0.0

### PrimeNG version

17.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Steps to reproduce the behavior

- Select an option in the dropdown
- Open the overlay again to search for another option
- Type in the filter input

### Expected behavior

Only the selected option label should be displayed.

I've forked and fixed it, let me know if you'd like a PR:

![image](https://github.com/primefaces/primeng/assets/33844394/dd611a5d-28ad-407d-8955-1717a36e4761)

![image](https://github.com/primefaces/primeng/assets/33844394/cba9160c-0cf8-41b1-bf3b-e8680d50e99c)

**Comment by abroekhuis** [comment]
I know this one is closed, but am wondering if this will be backported to a fix for version 16 as well.  As can be seen on the version examples, the same problem occurs there.
