### ISSUE TITLE
Dropdown: selectedItem template not displayed on the first change of form control

### ISSUE THREAD

**Issue by tsinevik** [primefaces/primeng#14283]
### Describe the bug

If Dropdown has `selectedItem` template that uses the context variable and this dropdown is connected to reactive form there might be an issue when dynamically setting the value for the first time (for example in `ngOnInit` or in `Input` setter calling `control.setValue`). Dropdown displayed shrunk and there's no value, but on click it returns to normal display. Seems like some rerender issue during change detection.

<img width="125" alt="image" src="https://github.com/primefaces/primeng/assets/43264254/f05df07a-9203-49af-8c2c-b6107e811339">

### Environment

Any environment

### Reproducer

https://stackblitz.com/edit/qgxlcn?file=src%2Fapp%2Fdemo%2Fdropdown-template-demo.ts,src%2Fapp%2Fdemo%2Fdropdown-template-demo.html

### Angular version

17.0.0

### PrimeNG version

17.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.0

### Steps to reproduce the behavior

https://stackblitz.com/edit/qgxlcn?file=src%2Fapp%2Fdemo%2Fdropdown-template-demo.ts,src%2Fapp%2Fdemo%2Fdropdown-template-demo.html

1. Provide `selectedItem` template to Dropdown and use context variable to display the value
2. Create form control with empty value, connect it to dropdown component
3. At `ngOnInit` set some value to the control
4. Dropdown displayed incorrectly with strange height and without value

### Expected behavior

Dropdown should display value correctly

**Comment by jacqueslareau** [comment]
Still present in 17.0.0

**Comment by jakob-bebop** [comment]
Still present in 17.0.0 and Angular 17.0.6

**Comment by jakob-bebop** [comment]
I guess this is a duplicate https://github.com/primefaces/primeng/issues/14241, which appears to be fixed in the upcoming version...

Is there an eta for 17.1.0?
