### ISSUE TITLE
Table: Apply and Clear text buttons for filter menu are missing

### ISSUE THREAD

**Issue by ioantoader** [primefaces/primeng#14289]
### Describe the bug

Table: Apply and Clear text buttons for filter menu are missing. See the image
![image](https://github.com/primefaces/primeng/assets/39898241/17bb94e1-2ad9-48c1-8a36-1657fcb65a36)

### Environment

Windows

### Angular version

17.0.6

### PrimeNG version

17.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.10.0

**Comment by mnhock** [comment]
Can confirm the bug, the buttons within the column filter are not visible, the text is missing.

**Comment by rosenthalj** [comment]
This bug should not be closed

"Remove Rule" and "Add Rule" filter button labels are still missing after fix https://github.com/primefaces/primeng/commit/fd09195b51d9db03e9bced6d69fd3add3a1a8450

**Comment by MauricioGarnica** [comment]
I can confirm rosenthalj's comment, the buttons he mentioned are still missing.

**Comment by cetincakiroglu** [comment]
> This bug should not be closed
> 
> "Remove Rule" and "Add Rule" filter button labels are still missing after fix [fd09195](https://github.com/primefaces/primeng/commit/fd09195b51d9db03e9bced6d69fd3add3a1a8450)

thanks a lot for the quick feedback, I'll open a new issue for them in 17.1.1 milestone
