### ISSUE TITLE
PrimeNG does not work with AOT in RTM

### ISSUE THREAD

**Issue by kcsahoo** [primefaces/primeng#1428]
The quick start example successfully compiles with ngc with small type changes
But Rollup throws a number of errors.
Can PrimeNG be made to work with AOT?
Please make it work with an example.

**Comment by cagataycivici** [comment]
What are the errors?

**Comment by skendrot** [comment]
error:
> Error: 'CalendarModule' is not exported by node_modules\primeng\components\calendar\calendar.js (imported by app\app.module.js). For help fixing this error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module

**Comment by CelsoSantos** [comment]
I'm facing the same issue with Rollup, in my case with the FileUploadModule.

Rollup v0.41.4
Node v6.7.0
Angular v2.4.4
PrimeNG v2.0.0-rc1.

PrimeNG v1.1.4 also presented the exact same error.

**Comment by cagataycivici** [comment]
This should be fixed long time ago, all online demos of PrimeNG run on AOT like Ultima, Poseidon ...
