### ISSUE TITLE
TreeSelect: Issue with TreeSelect in PrimeNG 16 - Unwanted '0' Prefix in Labels

### ISSUE THREAD

**Issue by BouazzaSeif** [primefaces/primeng#14285]
### Describe the bug

Hello,

I've encountered an issue with TreeSelect in PrimeNG 16 where the labels display an undesired '0' in front of each one. This problem is illustrated in the attached screenshot.

![image](https://github.com/primefaces/primeng/assets/38986451/3135473e-f794-4e9d-8da3-00d9a4d9fc47)

Additionally, the same bug can be observed on the official PrimeNG documentation site:

![image](https://github.com/primefaces/primeng/assets/38986451/f26c9223-2819-4ac5-9b69-157ceaac68f4)

Could you please look into this matter and provide a fix for the unwanted '0' prefix in the TreeSelect labels? It impacts the user experience, and your prompt attention to this issue would be highly appreciated.

Thank you.

### Environment

"primeng": "16.9.1" 
"angular": "16"

### Reproducer

https://stackblitz.com/edit/skfymg?file=src%2Fservice%2Fnodeservice.ts

### Angular version

16

### PrimeNG version

16.9.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.17.0

**Comment by adcore-dev** [comment]
I opened same issue few weeks ago, no feedback till now
[https://github.com/primefaces/primeng/issues/14193](url)

**Comment by jschu** [comment]
A workaround for this issue is to create a template to override the label. Unfortunatelly there is no predefined template to do this. So you have to set the property `type` for all your TreeNodes and define a template with the exact same name.

https://stackblitz.com/edit/skfymg-giimzn

**Comment by adcore-dev** [comment]
@jschu 
Hey, but this workaround stop working when you add other template to component:
![image](https://github.com/primefaces/primeng/assets/71829010/223a3298-9309-4568-ae91-5ec646bb6f06)

PrimeNG 17, not an option for now, it require Angular 17, which require Node 18.

**Comment by jschu** [comment]
this seems like a specific problem with the template `itemtogglericon`
I could not find a solution for this specific case
with other templates, the workaround works

**Comment by cetincakiroglu** [comment]
Hi,

This issue is already fixed and cannot be replicated with the latest version. Could you please share a stackblitz example if it still exists?

**Comment by adcore-dev** [comment]
Hi,
In 17.x.x problem resolved
In 16.x.x problem exist

**Comment by Gabrielfch** [comment]
Hola la forma de resolverlo en la version 16.9.1
`
              <p-treeSelect 
                formControlName="selectedNodes"
                [options]="treeNodes" 
                display="chip" 
                [showClear]="true"
                [filter]="true"
                <ng-template let-node pTemplate="default">
                  <span>{{node.label}}</span>
                </ng-template>
              </p-treeSelect>`

**Comment by ldv-orbyta** [comment]
> Hola la forma de resolverlo en la version 16.9.1 `<ng-template let-node pTemplate="default"> <span>{{node.label}}</span> </ng-template>`

Not working in my case with the same primeNG version. The templating doesn't work at all

**Comment by ldv-orbyta** [comment]
`<div class="flex flex-column gap-2">
  <label>{{ label }}</label>
  <p-treeSelect
    class="w-full"
    containerStyleClass="w-full"
    [filter]="true"
    [(ngModel)]="selectedNodes"
    [options]="options"
    selectionMode="single"
    [showClear]="true"
    [emptyMessage]="'EMPTY_MESSAGE' | translate"
    [placeholder]="'SELECT_ITEM' | translate"
  >
    <ng-template let-node pTemplate="node">
      NOT WORKING
    </ng-template>
  </p-treeSelect>
</div>
`
![{ABED5286-6D8B-421F-BB2C-0650BE671035}](https://github.com/user-attachments/assets/7d8e79e3-889f-4728-832d-f080e05c7bd1)
Still see these counter at the end!

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
