### ISSUE TITLE
p-dropdown and p-multiselect: generated HTML has duplicate id

### ISSUE THREAD

**Issue by hstiekema** [primefaces/primeng#14284]
### Describe the bug

A p-dropdown or p-multiselect component with an id (`<p-dropdown id="some-id">`) results in duplicate ids. The p-dropdown element will get a div inside it with the same id as the p-dropdown element.
The same effect occurs on p-multiselect

### Environment

Any

### Reproducer

https://stackblitz.com/edit/github-q5rtf2?file=src%2Fapp%2Fapp.component.html

### Angular version

16.2.12

### PrimeNG version

16.9.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.2

### Steps to reproduce the behavior

Create any p-dropdown or p-multiselect and assign it an id 

### Expected behavior

There are no duplicate IDs

**Comment by AdamOakman** [comment]
I can only confirm this issue affects ui test automation based on assumption that id attributes are unique in the DOM. Would be nice if we had it fixed

**Comment by balkarov** [comment]
+1

**Comment by egonokhov** [comment]
I found a workaround, I use property binding for id and it generates only one element with such id.
`<p-dropdown [id]="some-id" [options]="options"></p-dropdown>`

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
