### ISSUE TITLE
Component: Dropdown - display bug when using virtualScroll and filter together

### ISSUE THREAD

**Issue by lak357** [primefaces/primeng#14280]
### Describe the bug

I defined a p-dropdown that uses the virtualScroll and the filter at the same time.

When you search for an element, the list is updated with the elements that are related to the search.

However, when the list of elements corresponding to the search contains few elements (not enough for the scroll bar to be displayed) and we click outside the list and then reopen it, then the height of the list is much too large compared to the size needed.

### Environment

Angular 16.2.0
Primeng 16.9.1

### Reproducer

https://stackblitz.com/edit/ca7vez?file=src%2Fapp%2Fdemo%2Fdropdown-reactive-forms-demo.html

### Angular version

16.2.0

### PrimeNG version

16.9.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.20.2

### Browser(s)

Different versions of chrome and firefox (tried with: Chrome 119.0.6045.200, Firefox 120.0 and  91.0.1esr)

### Steps to reproduce the behavior

1. Click on the dropdown field;
2. Search : _try 1240_ (at this stage the height of the list is good);
3. Click outside the dropdown;
4. Click on the dropdown field;

Result : You have a list with one item (Country 1240) but the height of the list is too big.

![image](https://github.com/primefaces/primeng/assets/69200180/ecf1b78d-0373-492c-86b9-137e38eec1b0)

### Expected behavior

1. Click on the dropdown field;
2. Search : _try 1240_ (at this stage the height of the list is good);
3. Click outside the dropdown;
4. Click on the dropdown field;

Result : You have a list with one item (Country 1240) and the height of the list is adjusted well.

**Comment by lak357** [comment]
The problem is still present with version 17.5.0.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
