### ISSUE TITLE
Dropdown: The dropdown does not appear when clicking on a label associated with an inputId.

### ISSUE THREAD

**Issue by zakharenkov** [primefaces/primeng#14287]
### Describe the bug

There was already a similar error message, but that was a long time ago.
https://github.com/primefaces/primeng/issues/346

### Environment

Angular app

### Reproducer

https://stackblitz.com/edit/dpzq7a?file=src%2Fapp%2Fdemo%2Fdropdown-floatlabel-demo.html

### Angular version

17.0.6

### PrimeNG version

17.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.0

### Steps to reproduce the behavior

Click on the label associated with the input field - focus will go to the input field itself.
Click on the label associated with the dropdown - nothing will happen.
Expected behavior - the dropdown will open.

**Comment by mickey-connectit** [comment]
I am using Angular 17.0.5 and PrimeNG 17.3.3 and experiencing the same issue

**Comment by JamalGuyo** [comment]
This issue is still there in primeng v17.3.
<label for="user">User</label> <p-dropdown [options]="users" [(ngModel)]="model.user" id="user"></p-dropdown> 
The label is not focusing on the p-dropdown. same issue with multiselect.

**Comment by fsievers** [comment]
primeng v17.18.11 and issue still exists for p-dropdown and p-multiSelect

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
