### ISSUE TITLE
ListBox: emptyMessage not working

### ISSUE THREAD

**Issue by tlinford** [primefaces/primeng#14294]
### Describe the bug

On `ListBox` the `emptyMessage` property stopped working in versions >= 16.7.0

### Environment

stackblitz

### Reproducer

https://stackblitz.com/edit/2debcw?file=src%2Fapp%2Fdemo%2Flistbox-basic-demo.html

### Angular version

17.0.5

### PrimeNG version

16.7.0 - 17.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v18.18.0

**Comment by gpobr** [comment]
Not working in v17.11 https://stackblitz.com/edit/6uh9ca?file=src%2Fapp%2Fdemo%2Flistbox-filter-demo.html
