### ISSUE TITLE
toggleButton : StyleClass is not passed to child div

### ISSUE THREAD

**Issue by Triskae** [primefaces/primeng#14292]
### Describe the bug

In the documentation it says that we can use the styleClass option to provide a class to parent. In PrimeNG V17, it's not working properly, since the class put in styleClass is not copied to parent div.

The IDE is also reporting the attribute style class is not allowed.

![image](https://github.com/primefaces/primeng/assets/28785555/9d515181-11e1-4b3a-9651-8662e337f10e)

The Stackblitz for this example is also broken.

### Environment

"@angular/animations": "^17.0.3",
    "@angular/cdk": "^17.0.1",
    "@angular/common": "^17.0.3",
    "@angular/compiler": "^17.0.3",
    "@angular/core": "^17.0.3",
    "@angular/fire": "^16.0.0",
    "@angular/forms": "^17.0.3"
 "primeng": "^17.0.0",

### Angular version

17

### PrimeNG version

17

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

21.2.0

**Comment by SoyDiego** [comment]
> ### Describe the bug
> 
> In the documentation it says that we can use the styleClass option to provide a class to parent. In PrimeNG V17, it's not working properly, since the class put in styleClass is not copied to parent div.
> 
> The IDE is also reporting the attribute style class is not allowed.
> 
> ![image](https://private-user-images.githubusercontent.com/28785555/288776764-9d515181-11e1-4b3a-9651-8662e337f10e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5NjAwOTEsIm5iZiI6MTcwMTk1OTc5MSwicGF0aCI6Ii8yODc4NTU1NS8yODg3NzY3NjQtOWQ1MTUxODEtMTFlMS00YjNhLTk2NTEtODY2MmUzMzdmMTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDE0MzYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzOGEyOGE5YWJjOGVmNjQzNDFkN2YxNTdkMzdmMzYyZGQ5MzRjYTg2MGU3NzczN2Q4Yzk5MGJjODlhNGNlZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zcVYTNR8wgNc19J5aaXRpGK_6NlPA3sfYLTEDGQjVho)
> 
> The Stackblitz for this example is also broken.
> ### Environment
> 
> "@angular/animations": "^17.0.3", "@angular/cdk": "^17.0.1", "@angular/common": "^17.0.3", "@angular/compiler": "^17.0.3", "@angular/core": "^17.0.3", "@angular/fire": "^16.0.0", "@angular/forms": "^17.0.3" "primeng": "^17.0.0",
> ### Reproducer
> 
> _No response_
> ### Angular version
> 
> 17
> ### PrimeNG version
> 
> 17
> ### Build / Runtime
> 
> Angular CLI App
> ### Language
> 
> TypeScript
> ### Node version (for AoT issues node --version)
> 
> 21.2.0
> ### Browser(s)
> 
> _No response_
> ### Steps to reproduce the behavior
> 
> _No response_
> ### Expected behavior
> 
> _No response_

I don't understand your problem. In the title you wrote toggleButton, but in your example the problem is in InputGroup.
Could you be more clear and add a Stackblitz to see the problem?

Thanks

**Comment by Triskae** [comment]
Your right ! My bad, thanks @SoyDiego

**Comment by SoyDiego** [comment]
> Your right ! My bad, thanks @SoyDiego

no problem, happy to help! 🚀
