### ISSUE TITLE
Data table: metadata field "first" is incorrect when filtering with lazy load.

### ISSUE THREAD

**Issue by Bozjator** [primefaces/primeng#143]
When positioned on non-first page in data table and changing one of the filters, a lazy load method metadata first field is set to e.g. 3. I think it should be set to 0, since it will return entirely new set of data from server (e.g. after filtering I had results for less then one page but they weren't shown since first page was skipped).
In case when lazy load method is called due to filter change, first field should be set to zero.

BR, Blaž

**Comment by cagataycivici** [comment]
Could you please clarify what do you mean by skip metadata field?

**Comment by Bozjator** [comment]
I'm sorry, i meant metadata field event.first.
