### ISSUE TITLE
Unable to select seconds in the Calendar component

### ISSUE THREAD

**Issue by jpheintz** [primefaces/primeng#1430]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Currently the Calendar component does not include the capability of selecting seconds.

**Expected behavior**
Unable to set seconds for the time.

**Minimal reproduction of the problem with instructions**
Use calendar component and notice there is no option to select seconds.

**What is the motivation / use case for changing the behavior?**
Certain use cases require users to enter a specific time down to the seconds.

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/MxSw4qOuwDfq7rLO7jrR?p=preview
