### ISSUE TITLE
Removing an item from autocomplete closes p-OverlayPanel

### ISSUE THREAD

**Issue by patjag91** [primefaces/primeng#14300]
### Describe the bug

P-autocomplete is added into p-OverlayPanel. After selecting an item from autocomplete and trying to remove it the whole overlay is closed

### Environment

PrimeNG 17.0, Angular 17

### Reproducer

https://stackblitz.com/edit/rcbspb-6wowop

### Angular version

17

### PrimeNG version

17

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v18.18.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Create a  p-autocomplete component inside p-OverlayPanel
2. add an autocomplete item
3. remove an item

### Expected behavior

Item is removes, overlay stays opened

**Comment by SoyDiego** [comment]
A simple workaround you can use  is adding:  `dismissable` and `showCloseIcon`

```js
<p-overlayPanel #move [dismissable]="false" [showCloseIcon]="true">
```

I tried in your example and works but yes, should not be closed.

Thanks for report it!
