### ISSUE TITLE
Dropdown: Tabbing away from dropdown sets selected item to first option

### ISSUE THREAD

**Issue by erber014** [primefaces/primeng#14307]
### Describe the bug

When tabbing to/from a dropdown in https://primeng.org/dropdown the first option is selected. This is surely not how its meant to work? Navigating through a page using tab should not set values in inputs in my opinion

### Environment

https://primeng.org/dropdown latest version 17.0.0

### Angular version

Whatever the official site uses

### PrimeNG version

latest version 17.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

Whatever the official site uses

### Browser(s)

Firefox

### Steps to reproduce the behavior

Go to https://primeng.org/dropdown, tab through page from dropdown to dropdown. Watch as all dropdowns have the first option set as selected item.

### Expected behavior

Tabbing through dropdown component should not set selected item.

**Comment by Wykks** [comment]
Normal behavior indeed : https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/#kbd_label

**Comment by erber014** [comment]
No, I was talking about behavior when dropdown is never open and you are only tabbing through the form. Was starting to think either I was crazy or the world is crazy, thanks. :)

**Comment by Da13Harris** [comment]
They've been doing lots of work on fixing dropdown issues lately, and I think this one may have been fixed already. They've got quite the backlog of issues, so if this one is fixed I recommend closing it.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
