### ISSUE TITLE
Highlighted background and text colors of lara-light-teal are identical

### ISSUE THREAD

**Issue by Kaemmelot** [primefaces/primeng#14315]
### Describe the bug

When using lara-light-teal as theme many highlighted background and foreground colors seem to be identical, causing text to be unreadable. For example: the selection, the pagination and sorted headers in tables:
![image](https://github.com/primefaces/primeng/assets/5353825/1cea4dcc-6720-4176-8278-8aa99365a634)

The selection in the organization chart is another example and based on the CSS there seem to be more.

Also some lara colors are missing in the [built-in themes list](https://primeng.org/theming#builtinthemes).

### Environment

This can be reproduced on the website, for example for the table component.

### Angular version

17.0.6

### PrimeNG version

17.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.10.0

### Browser(s)

Chrome

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by Kaemmelot** [comment]
Just checked and the issue seems to be fixed in the latest version. Thanks!
