### ISSUE TITLE
p-columnFilter: Not diplaying OK on PrimeNG17

### ISSUE THREAD

**Issue by AIO1** [primefaces/primeng#14314]
### Describe the bug

Go to the documentation and try to use the filter, you will see the following:
![image](https://github.com/primefaces/primeng/assets/17305493/033c0bf2-ce72-4efa-865d-52ad498b67a5)

### Environment

https://primeng.org/table#filter-menu

### Reproducer

https://primeng.org/table#filter-menu

### Angular version

17

### PrimeNG version

17

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.10.0

**Comment by Wykks** [comment]
Duplicate of https://github.com/primefaces/primeng/issues/14289

**Comment by AIO1** [comment]
Fixed in #14289 and #14365
