### ISSUE TITLE
MultiSelect: onChange not working as intended with checkboxes and empty searchs

### ISSUE THREAD

**Issue by AIO1** [primefaces/primeng#14313]
### Describe the bug

Clicking on the checkbox marked in the image, won't trigger an onChange event.
![image](https://github.com/primefaces/primeng/assets/17305493/ce4ee3c5-1c1b-48bd-a024-df736e839ec1)

Also, if you search something that doesn't exist and then click the checkbox, it will be left as no columns select, and also, onChange event won't be triggered:
![image](https://github.com/primefaces/primeng/assets/17305493/ab29534c-7160-460b-86af-5484821cbb20)

### Environment

N/A

### Angular version

17

### PrimeNG version

17

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.10.0

### Steps to reproduce the behavior

Refer to Describe the bug

### Expected behavior

onChange should be triggered in the situations described, since, as the documentation says related to onChange for p-multiSelect:
Callback to invoke when value changes.

**Comment by cetincakiroglu** [comment]
Hi,

We've updated the toggleAll logic, added `onSelectAllChange` emitter and `selectAll` boolean, and now the user needs to configure it to prevent performance issues. You can see the example https://stackblitz.com/edit/2cvetx?file=src%2Fapp%2Fdemo%2Fmulti-select-basic-demo.html,src%2Fapp%2Fdemo%2Fmulti-select-basic-demo.ts

However, I realized that there is a misused condition in the multiselect.ts which caused the malfunction of the emitter. I've fixed it now, and you can utilize onSelectAllChange and onChange emitters as shown in the example above. 

Thanks for reporting the issue!
