### ISSUE TITLE
p-treenode-dragover is not always removed when you are no longer hovering over treeitem

### ISSUE THREAD

**Issue by pete-mcwilliams** [primefaces/primeng#14310]
### Describe the bug

p-treednode-dragover class applied to multiple listitems divs.  It is not possible to indicate to the user where they are dropping accurately.  The p-treenode-dragover class is still displayed after dragging has stopped.

Possibly an issue with the children of a list item keeping the parent mouseover?

![Screenshot 2023-12-09 at 07 10 57](https://github.com/primefaces/primeng/assets/73467841/4ac50478-315f-46de-aa64-e7801fc48b03)

### Environment

It's affecting the latest demo with primeng 17.0.0, also 16.9.1 the version we are using.

### Reproducer

https://stackblitz.com/edit/jmnkp9?file=package.json

### Angular version

16.2.7

### PrimeNG version

16.9.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v18.17.0

### Steps to reproduce the behavior

In the tree draggable demo expand all parents, drag a child e.g. goodfellas to the top of the list, then back down over parent listitems see many divs below li retain the class p-treenode-dragover. 

### Expected behavior

If the p-treenode-dragover is supposed to indicate the drop on list item the class should be removed when no longer hovering over the listitem.

**Comment by sarka-kolarova-engel** [comment]
Hello, can be expected this issue will be resolved in close feature? Currently we are using this feature in our company and decided to hide part of our implementation until bug is fixed. Thank you for response in advance.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
