### ISSUE TITLE
Dropdown: dynamic text in placeholder is not displayed

### ISSUE THREAD

**Issue by dbelob** [primefaces/primeng#14320]
### Describe the bug

The text in the placeholder is not displayed if it is generated dynamically using pipe.
![primeng-dropdown-placeholder-error-invalid1](https://github.com/primefaces/primeng/assets/22131253/d41c3e43-de43-42f1-ba65-ab5ef15f5192)

### Environment

OS: Windows 8.1, Windows 10

### Reproducer

https://stackblitz.com/github/dbelob/primeng-dropdown-placeholder-error

### Angular version

17.1.2

### PrimeNG version

17.5.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.11.0

### Browser(s)

Chrome 120.0.6099.71, Firefox 120.0.1, Edge 120.0.2210.61

### Steps to reproduce the behavior

1. Add `p-dropdown` with or without `ng-template`
2. Use dynamic text in `placeholder` attribute (for example `{{'selectCountry' | translate}}`)
3. Open application in any browser: text will not appear
4. Select other language (see example): text will not appear

### Expected behavior

The text is successfully displayed in _PrimeNG 16.6.0_
https://stackblitz.com/github/dbelob/primeng-dropdown-placeholder-error/tree/primeng16.6.0

Text should be displayed after opening the application:
![primeng-dropdown-placeholder-error-valid1](https://github.com/primefaces/primeng/assets/22131253/a2923f72-c53e-4dff-9e72-a09196f47466)

Text should change after changing the language:
![primeng-dropdown-placeholder-error-valid2](https://github.com/primefaces/primeng/assets/22131253/69bffc0a-21b4-44ef-bebe-6b37992c02c6)

**Comment by dbelob** [comment]
See same issue #14321

**Comment by matusko89** [comment]
same issue here, aparently [placeholder]="value" is set only the first time and then is not detecting the change of the value

**Comment by matusko89** [comment]
So I found a workaround, if you use string interpolation then it works `placeholder="{{ value }}`

**Comment by danieljedrzejczyk** [comment]
@cetincakiroglu pls add multiselect bug to 17.6.0 
https://github.com/primefaces/primeng/issues/14321

**Comment by cetincakiroglu** [comment]
@danieljedrzejczyk 

Thanks a lot for letting me know!

**Comment by McFck** [comment]
@cetincakiroglu Greetings, can this PR be forwarded to primeng v16 ?

**Comment by aman-dedalus** [comment]
Is this fixed in v16?
