### ISSUE TITLE
Inputnumber: Inputnumber#currency mode not allowing to remove minus sign for Dollar and INR fields.

### ISSUE THREAD

**Issue by akshayantony55** [primefaces/primeng#14327]
### Describe the bug

Inputnumber: Inputnumber#currency mode not allowing to remove minus sign for Dollar and INR fields.

### Environment

https://primeng.org/inputnumber#currency

Using windows environment.

### Angular version

17.0

### PrimeNG version

17.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.10

### Steps to reproduce the behavior

1. Go to https://primeng.org/inputnumber#currency.
2. Remove existing currencies, and add minus sign to all the currencies with some currency values.
3. Try to remove the minus sign by putting the cursor at the beginning position.
4. Minus sign is successfully removed for Germany and Japan, but not removed for US and India.

### Expected behavior

Minus sign should get removed for US and India currencies.

**Comment by NadyKazi** [comment]
[https://stackoverflow.com/questions/65895980/primeng-p-inputnumber-unable-to-enter-negative-fractional-numbers/78701723#78701723](url)

refer this link

**Comment by NadyKazi** [comment]
[https://stackoverflow.com/a/78701723/20703604](url)

refer this
