### ISSUE TITLE
Bug when entering text in the column filters

### ISSUE THREAD

**Issue by Danieleeee** [primefaces/primeng#1432]
[X] bug report 

**Current behavior**
If you enter several times the data in the column filters and then delete them, some characters are not inserted or some not deleted.
I have sortable columns.

**Minimal reproduction of the problem with instructions**
enter "tttttttttt" in the filters, then delete them, then repeat the process several times.

* **Angular version:** 2.1.X

* **PrimeNG version:** 1.0.0 final

* **Browser:** [Chrome latest | IE 11 | Safari ]

**Comment by Thavarajan** [comment]
dii you try with the filterDelay to increase the filter time

**Comment by Danieleeee** [comment]
I'll try....but the same error occurs in official page of prime NG: 
http://www.primefaces.org/primeng/#/datatable/filter

**Comment by Danieleeee** [comment]
> dii you try with the filterDelay to increase the filter time
With filterDelay it works!
Thanks!

**Comment by cagataycivici** [comment]
Glad to hear!
