### ISSUE TITLE
Speed Dial: Invisible overlay hangs below element

### ISSUE THREAD

**Issue by horizoncarlo** [primefaces/primeng#14330]
### Describe the bug

I have a 64px Speed Dial, but there is an extra 36px of invisible overlay below the Speed Dial, which blocks mouse events from being passed through to elements underneath. The overlay seems to be part of the flex layout, and appears in whatever direction your Speed Dial is set to (in my case `direction="down"`, with `type="linear"`).

![primeng-speed-dial-overhang](https://github.com/primefaces/primeng/assets/65215473/6069b0a3-6204-400a-8e1d-f8491e1fbd45)

The same behaviour is evident when inspecting the PrimeNG component suite itself.

### Environment

Seen in PrimeNG 16 and 17 (with Angular versions to match) on Chrome v120 on desktop Linux.

### Angular version

16, 17

### PrimeNG version

16, 17

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Expected behavior

I would expect Speed Dial to maintain it's specified height (in this case 64px) without any overhang/overlay that blocks clicks.

**Comment by cetincakiroglu** [comment]
Hi,

It's not the overlay, it's the menu items list of the component. It happens because the angular animations don't work with `display: none`, it breaks the animation. Due to the technical limitations, we're not able to modify the animation in this way. We're planning to replace angular animations with our custom CSS animations in the future.

**Comment by horizoncarlo** [comment]
Unfortunate limitation. Any timeline on a projected fix?

**Comment by redakker** [comment]
I found a workaround.
If you are using template, then you can hide the menu items if the menu is closed:
`<p-speeddial
    [model]="menuItems$ | async"
    direction="up"
    mask
    [style]="{ position: 'absolute', right: '1rem', bottom: '1rem' }"
    (onShow)="mobileMenuHidden = false"
    (onHide)="mobileMenuHidden = true"
  >
    >
    <ng-template #item let-item let-toggleCallback="toggleCallback">
      <div
        class="border-1 -ml-2 flex w-20 cursor-pointer flex-col items-center justify-between gap-1 rounded bg-white p-1"
        [ngClass]="{ hidden: mobileMenuHidden }"
        (click)="toggleCallback($event, item)"
      >
        <span [class]="item.icon"></span>
        <span class="p-1 text-xs">
          {{ item.label | translate }}
        </span>
      </div>
    </ng-template>
  </p-speeddial>`
