### ISSUE TITLE
Multiselect dropdown should not show  "empty" option

### ISSUE THREAD

**Issue by yunusyerli1** [primefaces/primeng#14337]
### Describe the bug

![Screenshot from 2023-12-12 17-04-26](https://github.com/primefaces/primeng/assets/37618039/4c611094-10f3-490c-a740-b5f1a4a0838d)
ı am getting the array like in the image. The first  object in the array which  label and value are empty. So, ı expect multiselect dropdown should not show empty option . See below image:
![Screenshot from 2023-12-12 17-07-54](https://github.com/primefaces/primeng/assets/37618039/1b913283-056a-4df1-b90a-bd50be68dadb)

### Environment

Ubuntu and docker

### Angular version

16

### PrimeNG version

16.9.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.17.1

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Create a list with one empty label and empty value
2. Check multiselect
3. Empty option will be seen

### Expected behavior

if array member has empty label, the dropdown should not show it

**Comment by cetincakiroglu** [comment]
Hi,

It's made by design, not a bug. Users use the component with values, not empty objects. Instead of updating the component, you can simply remove the empty object and use the component.

**Comment by yunusyerli1** [comment]
I cant change empty object array since the array is dynamic and being used in many places. I just thought logically if label comes with no value, dropdown shouldnt show it or at least there should be an built-in option to choose such a thing. Anyway, ı got your response. Thank you Mr Çetin Bey
