### ISSUE TITLE
multiselect: clicking directly on the svg icon closes the overlay

### ISSUE THREAD

**Issue by angelo-v** [primefaces/primeng#14335]
### Describe the bug

When clicking directly on the checkmark svg icon of a selected element, the overlay closes, but it should stay open.

The svg is hard to hit manually in with the default theme, but in our theme it is very likely to click and anyoing that the overlay then closes.

### Environment

Angular web application

### Angular version

16

### PrimeNG version

\>14

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Browser(s)

Chrome

### Steps to reproduce the behavior

To reproduce visit https://primeng.org/multiselect open one of the examples selects and check an element, then execute in the dev console:

```javascript
document.querySelectorAll('.p-checkbox-icon')[0].dispatchEvent(new Event('click', {bubbles: true}))
```

### Expected behavior

The overlay stays open

**Comment by thecooper** [comment]
Is there any way I could get this added to version 16?
