### ISSUE TITLE
Component: PickList

### ISSUE THREAD

**Issue by bzhao16834** [primefaces/primeng#14339]
### Describe the bug

When either availalbe or selected list is empty, clicking on p-picklist would cause TypeError: Cannot read properties of undefined (reading 'getAttribute') at PickList.changeFocusedOptionIndex (primeng-picklist.mjs:937:48)

### Environment

Microsoft Edge for Business version 10.0.2210.61

### Reproducer

https://www.primefaces.org/primeng-v16/picklist

### Angular version

16.2.12

### PrimeNG version

16.9.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.0 and 16.9.1

### Steps to reproduce the behavior

1. Open PrimeNG Picklist page in a browser, https://www.primefaces.org/primeng-v16/picklist 
2. Hit F12 to open browser's developer console
3. On PrimeNG Picklist page, FEATURES tab, Basic section, make sure the Selected list of demo picklist is empty.
4. Click anywhere in Selected area, and inspect developer console. You should be able to observe ERROR TypeError: Cannot read properties of undefined (reading 'getAttribute') in console output
5. Same error would occur if empty picklist receives focus

### Expected behavior

No error in console output when empty picklist is clicked or receives focus

**Comment by cetincakiroglu** [comment]
Fixed in https://github.com/primefaces/primeng/pull/14342
