### ISSUE TITLE
PickList: Filtering bug, when moving item to target list

### ISSUE THREAD

**Issue by PranKe01** [primefaces/primeng#14334]
### Describe the bug

When the filter in source list is active and we move an selected item, which is filtered out, to the target list, the filtered source list will be wrong.

### Environment

Environment independent.

### Reproducer

https://primeng.org/picklist

### Angular version

16.0.0

### PrimeNG version

17.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.0.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

1) Go to https://primeng.org/picklist
2) Go to the second pick list, with the filters
3) Select "Blue Band" item
4) While "Blue Band" is selected, type into the filter "Bracelet" -> The selected "Blue Band" will disappear, but the move buttons are still enabled.
5) Click on the "right-arrow" button in the middle of the lists, to move the selected item to the right list.
6) The "Blue Band" item will be moved to the right list (even though it was not visible) AND on the left list, one element dissapears, which should stay in the filtered list!

### Expected behavior

When a selected item is filtered out, the move right button should be disabled
OR
When a filtered out item is moved to the right, the filtered items should not change

**Comment by cetincakiroglu** [comment]
Fixed in https://github.com/primefaces/primeng/pull/14340
