### ISSUE TITLE
MultiSelect: UpdateLabel() method missing

### ISSUE THREAD

**Issue by mshnajar** [primefaces/primeng#14343]
### Describe the bug

I have updated my Angular to 16 & PrimeNG to 16.9.1
After the update I get this compile-time error:
Property 'updateLabel' does not exist on type 'MultiSelect'.
I traced the PrimeNG MultiSelect codes & realized that in the migration from 16.6.0 to 16.7.0 @cetincakiroglu had a big commit "MultiSelect | Accessibility Enhancements" (0cdb8bd) & the   updateLabel() method was removed.
Could you please tell me what was the reason & also I don't remember what this method actually did (Legacy code)?
And what could be the alternative method instead of updateLabel()

### Environment

Angular to 16
PrimeNG 16.9.1

### Angular version

16.2..12

### PrimeNG version

16.9.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.10.0

**Comment by cetincakiroglu** [comment]
Hi,

With version 16.7.0, we have released the first part of the accessibility implementation for inputs that we have been working on for a long time. Based on the research we conducted during the implementation, we decided that many components needed changes in their structure and simplification, and these components were rewritten. UpdateLabel is one of the rewritten methods. You can download and check the code of previous releases as a zip file from the releases tab on the repo.

**Comment by mshnajar** [comment]
As I mentioned above, I am using PrimeNG 16.9.1 & in this version we get compile error, telling that there is no method named UpdateLabel to call  ( Error: Property 'updateLabel' does not exist on type 'MultiSelect' )
So what has happed to UpdateLabel method? Is it renamed or removed?
We used this method to clear the MultiSelect, selected items label & now we have commented this part of code!
Please guide us & give a possible solution for this problem

**Comment by shamimBJIT** [comment]
> As I mentioned above, I am using PrimeNG 16.9.1 & in this version we get compile error, telling that there is no method named UpdateLabel to call ( Error: Property 'updateLabel' does not exist on type 'MultiSelect' ) So what has happed to UpdateLabel method? Is it renamed or removed? We used this method to clear the MultiSelect, selected items label & now we have commented this part of code! Please guide us & give a possible solution for this problem @cetincakiroglu

I'm also facing similar issues!

**Comment by mshnajar** [comment]
Based on my problem & others experience , I don't think immediate act on closing a really open issue is what is accepted.
@cetincakiroglu 
@cagataycivici

**Comment by cetincakiroglu** [comment]
Hi,

The ﻿`updateLabel` method was an undocumented method that was used within the component without any encouragement for users to use it. It is the user's responsibility to use an undocumented method and bear the consequences that may arise from it. Instead of this method, we are now using `angular signals`. Since it wasn't publicly mentioned or documented, removing was not a breaking change.
