### ISSUE TITLE
MenuItem in panelmenu , the navigate param

### ISSUE THREAD

**Issue by CK110** [primefaces/primeng#1435]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
when i use the MenuItem
this is my code: 
```
{
        label: 'personal',
        items: [
          {label: 'contract',routerLink: ['contract']},
          {label: 'depart',routerLink: ['depart']}
        ]
}
```
In angular2 ,  navigate(commands: any[], extras?: NavigationExtras): Promise<boolean>;
there is a extras Enables relative navigation from the current ActivatedRoute. 
but in [BasePanelMenuItem](https://github.com/primefaces/primeng/blob/master/components/panelmenu/panelmenu.ts)
```
        if(item.routerLink) {
            this.router.navigate(item.routerLink);
        }
```
there is no NavigationExtras. 

but i can use the command to implement 
```
   {label: 'contract',command:(event)=> this.nagivate(event,['contract'])},
 
 nagivate(event,path){
    this.router.navigate(path, { relativeTo: this.route });
  }
```
**Expected behavior**
if there is a  NavigationExtras , i just only need use the routerLink 

* **Angular version:** 2.0.0

* **PrimeNG version:** 1.0.0-rc.2
 this is still an issue in the most recent Angular version

**Comment by ar53n** [comment]
Its true. I suggest all menu navigation make relative because

First item should work relative. Second item will work absolutly.
What do you think? @cagataycivici 
`{
        label: 'personal',
        items: [
          {label: 'contract',routerLink: ['contract']},
          {label: 'depart',routerLink: ['/depart']}
        ]
}`

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/VZbdZfQ7SuTV87tTkbYR
