### ISSUE TITLE
Component: TriStateCheckbox lost margin between label and checkbox

### ISSUE THREAD

**Issue by jpgoelz** [primefaces/primeng#14369]
### Describe the bug

There is a design bug which was introduced by first replacing `p-checkbox-label` with `p-tristatecheckbox-label` in 
https://github.com/primefaces/primeng/pull/13977, then just removing the class altogether in https://github.com/primefaces/primeng/pull/14312 and readding it in https://github.com/primefaces/primeng/pull/14360.

When checking the changes between 16.6.0 (the version I know where both clicking the label and the style were working correctly) and 17.1.0 ([link](https://github.com/primefaces/primeng/compare/16.6.0...17.1.0)), I notice that the `p-tristatecheckbox-label` CSS class does no longer exist and should be replaced again with `p-checkbox-label` to fix this.

Additionally, the on-click event should be re-added to allow clicking on the label.

![image](https://github.com/primefaces/primeng/assets/32487587/2e2303f4-e75d-4aee-a438-f714c44fb9f0)

### Environment

n/a

### Reproducer

https://stackblitz.com/edit/77z5q5?file=src%2Fapp%2Fdemo%2Ftri-state-checkbox-basic-demo.html

### Angular version

16, 17

### PrimeNG version

16.9.1, 17.0.0, 17.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.x

**Comment by SoyDiego** [comment]
Hi @jpgoelz I did a PR solving the problem.
You can check here: https://github.com/primefaces/primeng/pull/14371
But the **click** in the **checkbox** it is working ok, you should add a `value`. Here you have a example:

![solved](https://github.com/primefaces/primeng/assets/19764334/dfa2cb59-4182-4512-a8bf-c10004b055d0)

But I fixed also the examples in the website because were failing. If you use the attribute  `label` you don't need to use `inputId` like the examples in the website. You can see more examples in my PR.

Thanks for report it!

**Comment by jpgoelz** [comment]
Hey, thank you for the fast response!

The issue with clicking was regarding clicking the label: of the tri-state-checkbox:

![tri-state-checkbox-label-click](https://github.com/primefaces/primeng/assets/32487587/369ca971-9168-453a-9f51-e69ad3065d2e)
([StackBlitz](https://stackblitz.com/edit/77z5q5-dglwgv?file=src%2Fapp%2Fdemo%2Ftri-state-checkbox-basic-demo.html))

I guess my "minimal working example" was too minimal. 😅

**Comment by SoyDiego** [comment]
> Hey, thank you for the fast response!
> 
> The issue with clicking was regarding clicking the label: of the tri-state-checkbox:
> 
> ![tri-state-checkbox-label-click](https://private-user-images.githubusercontent.com/32487587/290988677-369ca971-9168-453a-9f51-e69ad3065d2e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MjYzNTMsIm5iZiI6MTcwMjcyNjA1MywicGF0aCI6Ii8zMjQ4NzU4Ny8yOTA5ODg2NzctMzY5Y2E5NzEtOTE2OC00NTNhLTlmNTEtZTY5YWQzMDY1ZDJlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDExMjczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxNmJmZjBmMWI5N2RiYzMzZjA3M2MxZDczOGIzMjc5ZmE2NzA0MGVlYmU3MTU3ZDVmMGNiYmY3YTBjZDhkZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.co_ytlWN3Xyxlb_gcrFs4HK6xXO5SQBmrMZIZCpvQIQ) [ ![tri-state-checkbox-label-click](https://private-user-images.githubusercontent.com/32487587/290988677-369ca971-9168-453a-9f51-e69ad3065d2e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MjYzNTMsIm5iZiI6MTcwMjcyNjA1MywicGF0aCI6Ii8zMjQ4NzU4Ny8yOTA5ODg2NzctMzY5Y2E5NzEtOTE2OC00NTNhLTlmNTEtZTY5YWQzMDY1ZDJlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDExMjczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxNmJmZjBmMWI5N2RiYzMzZjA3M2MxZDczOGIzMjc5ZmE2NzA0MGVlYmU3MTU3ZDVmMGNiYmY3YTBjZDhkZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.co_ytlWN3Xyxlb_gcrFs4HK6xXO5SQBmrMZIZCpvQIQ) ](https://private-user-images.githubusercontent.com/32487587/290988677-369ca971-9168-453a-9f51-e69ad3065d2e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MjYzNTMsIm5iZiI6MTcwMjcyNjA1MywicGF0aCI6Ii8zMjQ4NzU4Ny8yOTA5ODg2NzctMzY5Y2E5NzEtOTE2OC00NTNhLTlmNTEtZTY5YWQzMDY1ZDJlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDExMjczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxNmJmZjBmMWI5N2RiYzMzZjA3M2MxZDczOGIzMjc5ZmE2NzA0MGVlYmU3MTU3ZDVmMGNiYmY3YTBjZDhkZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.co_ytlWN3Xyxlb_gcrFs4HK6xXO5SQBmrMZIZCpvQIQ) [ ](https://private-user-images.githubusercontent.com/32487587/290988677-369ca971-9168-453a-9f51-e69ad3065d2e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MjYzNTMsIm5iZiI6MTcwMjcyNjA1MywicGF0aCI6Ii8zMjQ4NzU4Ny8yOTA5ODg2NzctMzY5Y2E5NzEtOTE2OC00NTNhLTlmNTEtZTY5YWQzMDY1ZDJlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDExMjczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxNmJmZjBmMWI5N2RiYzMzZjA3M2MxZDczOGIzMjc5ZmE2NzA0MGVlYmU3MTU3ZDVmMGNiYmY3YTBjZDhkZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.co_ytlWN3Xyxlb_gcrFs4HK6xXO5SQBmrMZIZCpvQIQ) ([StackBlitz](https://stackblitz.com/edit/77z5q5-dglwgv?file=src%2Fapp%2Fdemo%2Ftri-state-checkbox-basic-demo.html))
> 
> I guess my "minimal working example" was too minimal. 😅

Yeah, don't worry with my PR will fixed the problem, If PrimeNG Team approve it and it's a good solution for them, will be released.
Here you have a example working with your code:

![fixed](https://github.com/primefaces/primeng/assets/19764334/ab1cf923-543f-436a-8062-b2c9f54588a7)

**Comment by jpgoelz** [comment]
Perfect, thanks!

**Comment by jpgoelz** [comment]
@cetincakiroglu, this was released in 17.2.0 but does not appear in the Changelog.

**Comment by SoyDiego** [comment]
> @cetincakiroglu, this was released in 17.2.0 but does not appear in the Changelog.

Yes, it does @jpgoelz.

![image](https://github.com/primefaces/primeng/assets/19764334/fb76df41-2fbe-4dbe-a991-97d5e8b677e4)

**Comment by jpgoelz** [comment]
I obviously need glasses. Sorry for wasting your time! 🤦 

I only looked at the changelog provided by Renovate, which apparently parses the milestones and not the changelog provided by you guys. My bad!

![image](https://github.com/primefaces/primeng/assets/32487587/ed4585f6-550a-4ffb-a3c4-8a957ff5709a)

**Comment by SoyDiego** [comment]
no problem, happy to help!
