### ISSUE TITLE
AutoComplete: (Multiple) Placeholder does not disappear after selecting item

### ISSUE THREAD

**Issue by c-o-l-i-n** [primefaces/primeng#14376]
### Describe the bug

In PrimeNG 16.6.0 and earlier, selecting an item in a multi-select AutoComplete removes the placeholder.

In PrimeNG v16.7.0 and later, selecting an item in a multi-select AutoComplete does NOT remove the placeholder.

**PrimeNG 16.6.0 ([Stackblitz](https://stackblitz.com/edit/stackblitz-starters-hqfgdx?file=src%2Fmain.ts))**
![16.6.0 before](https://github.com/primefaces/primeng/assets/40863449/23e41134-31f6-4ff3-961c-cd38dbf7b8a7)
![16.6.0 after](https://github.com/primefaces/primeng/assets/40863449/486d8c7e-ffd8-4798-9f44-52d904285354)

**PrimeNG 16.7.0 ([Stackblitz](https://stackblitz.com/edit/stackblitz-starters-srrovt?file=package.json,src%2Fmain.ts)) and PrimeNG 17.1.0 ([Stackblitz](https://stackblitz.com/edit/stackblitz-starters-q2esz6?file=src%2Fmain.ts))**
![16.7.0 before](https://github.com/primefaces/primeng/assets/40863449/89bf874a-8215-45b9-9a40-fe9b6b88a11f)
![16.7.0 after](https://github.com/primefaces/primeng/assets/40863449/658e2048-ebd7-4393-b0ae-89018b0bba89)

I believe this regression is caused by the removal of [this line](https://github.com/primefaces/primeng/compare/16.6.0...16.7.0#diff-9d50135e4516e9d05443fe244f93500de64822fab036452e838f67fc36c5e821L117) in v16.7.0:
`[attr.placeholder]="value && value.length ? null : placeholder"`

### Environment

Stackblitz

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-srrovt?file=package.json,src%2Fmain.ts

### Angular version

16.2.12

### PrimeNG version

16.7.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

Whichever version Stackblitz uses

### Steps to reproduce the behavior

1. Create an AutoComplete with `[multiple]="true"`
2. Select an item

### Expected behavior

The placeholder should disappear after selecting an item. Behavior should remain consistent with previous versions.

**Comment by mehmetcetin01140** [comment]
Hi,

Thanks for reporting the issue!
