### ISSUE TITLE
treetable improvements

### ISSUE THREAD

**Issue by djay1977** [primefaces/primeng#1437]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
Would it be possible to add the following features to the treetable component:
- double-click event
- change expandedIcon/collapsedIcon
- Icon of the node to display next to content
- context menu

Thanks

**Comment by mmlitvin** [comment]
I am also looking for all these features. Just adding my vote here.
Thanks

**Comment by cagataycivici** [comment]
Issue is too broad, please create separate tickets.
