### ISSUE TITLE
Component: Table changing value broken for multiSort

### ISSUE THREAD

**Issue by yelhouti** [primefaces/primeng#14372]
### Describe the bug

When I use multiSort, and the value (not the reference, ex: add an element to the array) of the table changes, the view is not updated
This seems to be caused by:
https://github.com/primefaces/primeng/blob/b5d5c276e7bd4f39f6f8cd4ef7a9ef94212e5703/src/app/components/table/table.ts#L1607

### Environment

simple angular project

### Angular version

17.0.0

### PrimeNG version

17.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.1

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
