### ISSUE TITLE
ng-dirty ng-invalid class doesnot work on dropdown component

### ISSUE THREAD

**Issue by amirheydari9** [primefaces/primeng#14379]
### Describe the bug

ng-dirty ng-invalid class doesnot work on dropdown component

### Environment

nothing

### Angular version

17

### PrimeNG version

17

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.8.1

**Comment by freddyfly86** [comment]
Upgrade to 17.1.0 version solved issue for me

**Comment by cetincakiroglu** [comment]
https://primeng.org/dropdown#invalid
