### ISSUE TITLE
Multiple calendar in one page makes page not responsive when opening and closing the widget.

### ISSUE THREAD

**Issue by mobilestar2015** [primefaces/primeng#1438]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Now I have several calendar components(about 10) in one page.
And when I open the calendar widget(overlay) and click the outside of the widget to close the widget.
It makes the page not responsive. (Takes about 5~10s for Angular change detection)
I investigated the calendar.js code and can see there are following code in ngOnInit.

```
this.documentClickListener = this.renderer.listenGlobal('body', 'click', () => {
            if(this.closeOverlay) {
                this.overlayVisible = false;
            }
            
            this.closeOverlay = true;
            this.dateClick = false;
        });
```

at line 274~281
This was the reason of the bug.
It's called x times for every calendar components when clicking the page.
Angular change detection function takes much time to change the zone changes.

**Expected behavior**
Expected behavior is that make it responsive.

**What is the motivation / use case for changing the behavior?**
The above codes need to be moved to onInputFocus function or somewhere else which are called once.

**Please tell us about your environment:**
Windows 10, Visual Studio Code, npm, firebase

* **Angular version:** 2.2.1

* **PrimeNG version:** 1.0.0

* **Browser:** 
 all
* **Language:** TypeScript 2.0.10 | ES6 | ES5

* **Node (for AoT issues):** `node --version` =   6.7.0

**Comment by rfboykin** [comment]
I also experienced this issue when showing more than 5 calendars on a page (which I need as I had a datepicker in a datatable template). 

As a workaround I created a wrapper component that lazily loads p-calendar when clicked or focused into. Updating the calendar component would be very helpful.

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/MxSw4qOuwDfq7rLO7jrR?p=preview

**Comment by chanakyanet** [comment]
![image](https://user-images.githubusercontent.com/18224197/33080466-2c960610-cea6-11e7-8426-edeebc1e18a3.png)

Experiencing calendar issue on click and close and re-click again. does not stop increasing
