### ISSUE TITLE
AutoComplete: Virtual Scroll not working in primng demo site

### ISSUE THREAD

**Issue by ashikjs** [primefaces/primeng#14385]
### Describe the bug

It's not working on PrimeNg live demo site. You check it live site here [Autocomplete#virtualscroll](https://primeng.org/autocomplete#virtualscroll)

Here bug details video 

https://github.com/primefaces/primeng/assets/13074235/684c9b15-45d5-4323-bbd3-ca1f2d0eaee4

### Environment

17

### Angular version

17

### PrimeNG version

17

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

**Comment by cetincakiroglu** [comment]
Hi,

It's actually working, there is nothing displayed because you're searching something that doesn't exist in the data. Data is  item + index
