### ISSUE TITLE
Component: all

### ISSUE THREAD

**Issue by klimchak** [primefaces/primeng#14381]
### Describe the bug

Components are not displayed correctly. There are no styles on the components. 
Dropdown, Buttons, Dialog, Sidebar and etc.

![image](https://github.com/primefaces/primeng/assets/59660054/96e4ca1c-d261-4ddb-94c3-e6157e212abd)
![image](https://github.com/primefaces/primeng/assets/59660054/b387d0bd-df08-4e6a-96de-2f0cfc8ba09f)
![image](https://github.com/primefaces/primeng/assets/59660054/ea29948b-4895-4f29-be0c-ad39149712ce)
![image](https://github.com/primefaces/primeng/assets/59660054/3599c1d6-ab0f-4b7a-a658-93bed3cb785a)
![image](https://github.com/primefaces/primeng/assets/59660054/48cb363a-4c84-48eb-9d26-c9ecf5bbe2a4)
![image](https://github.com/primefaces/primeng/assets/59660054/bdea872f-9525-482a-ac19-adff69064fd8)

### Environment

macOS Big Sur
Safari 14.1

### Angular version

16-17

### PrimeNG version

16-17

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

latest

### Browser(s)

Safari 14.1

### Steps to reproduce the behavior

1. go to PrimeNG docs using apple device with macOS Big Sur and latest Safari browser;
2. try to open sidebar or dialog or display buttons section

**Comment by SoyDiego** [comment]
Hi, I tried with a macOS device and Safari on last version and works correctly.
@klimchak Could you try a hard-refresh, please?

**Comment by klimchak** [comment]
> Hi, I tried with a macOS device and Safari on last version and works correctly.
> @klimchak Could you try a hard-refresh, please?

Try to use macOS Big Sur or less, because in the latest 3 versions (Monterey, Ventura and Sonoma) are working fine.

**Comment by SoyDiego** [comment]
> > Hi, I tried with a macOS device and Safari on last version and works correctly.
> > @klimchak Could you try a hard-refresh, please?
> 
> Try to use macOS Big Sur or less, because in the latest 3 versions (Monterey, Ventura and Sonoma) are working fine.

If i'm not wrong, the Browser Support is 2/3 last versions. They had this in the old website:

![image](https://github.com/primefaces/primeng/assets/19764334/a9929a55-9943-48c6-a29a-74274e7b6845)

But i'm not 100% sure.

**Comment by klimchak** [comment]
> > > Hi, I tried with a macOS device and Safari on last version and works correctly.
> > > @klimchak Could you try a hard-refresh, please?
> > 
> > 
> > Try to use macOS Big Sur or less, because in the latest 3 versions (Monterey, Ventura and Sonoma) are working fine.
> 
> If i'm not wrong, the Browser Support is 2/3 last versions. They had this in the old website:
> 
> ![image](https://private-user-images.githubusercontent.com/19764334/291204601-a9929a55-9943-48c6-a29a-74274e7b6845.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4ODk5ODAsIm5iZiI6MTcwMjg4OTY4MCwicGF0aCI6Ii8xOTc2NDMzNC8yOTEyMDQ2MDEtYTk5MjlhNTUtOTk0My00OGM2LWEyOWEtNzQyNzRlN2I2ODQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDA4NTQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1ZWU2Y2ZkNmQ1YzAxNzcxNDBmMjdjMjg0YWRkMTE4ZGJkNTViMzI3YTU0NTM0ZDNjMzI0MTQyYjFmODZhNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aOTHFwE-biPK6EgwwMyocYjKLgfsz5UtFpNpfnr3qvQ)
> 
> But i'm not 100% sure.

yes, but it's strange. because 15 and less version fine working on all macOS versions, but 16 and 17 do not.

**Comment by klimchak** [comment]
this problem can be replicated if use Safari v.14.1 (as i know it's latest version for macOS Big Sur). 
Safari v.14.1 not supported @layer (it's using in node_modules/primeng/resources/primeng.min.css).

**Comment by atamansv** [comment]
The `@layer` CSS [at-rule](https://developer.mozilla.org/en-US/docs/Web/CSS/At-rule) is relatively new and only supported by 93.55% of users https://caniuse.com/mdn-css_at-rules_layer
So excluding IE, that's ~6% of users, and that's pretty significant!
