### ISSUE TITLE
Multiselect does not focus filter input

### ISSUE THREAD

**Issue by umuero** [primefaces/primeng#14387]
### Describe the bug

multiselect @Input autofocusFilter should focus the filterInput 
it's not working

### Environment

Mac OSX, Chrome

### Angular version

v17

### PrimeNG version

v17.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v18.16.0

### Steps to reproduce the behavior

https://primeng.org/multiselect
click multiselect box @basic

**Comment by mehmetcetin01140** [comment]
Hi,

Thanks for reporting the issue!
