### ISSUE TITLE
Autoresize of TextArea  does not resize correctly if relative width is defined

### ISSUE THREAD

**Issue by pvlptr** [primefaces/primeng#1439]
Autoresize of TextArea (directive pInputTextarea)  does not resize correctly if relative width (for example width: 100%) is defined.

Example from Ultima theme life preview (Only 5 rows entered, but TextArea was resized to 20 rows):
![textarearesize](https://cloud.githubusercontent.com/assets/6097612/20671722/31e382a2-b587-11e6-96d6-aec325a7c1a5.png)

**Comment by Hesesses** [comment]
Any updates with this?

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/MxSw4qOuwDfq7rLO7jrR?p=preview

**Comment by richteri** [comment]
Unfortunately this issue is still seem to be present when you set any width other than the native [cols] width for the input textarea:

https://plnkr.co/edit/FMiGoSmiBGPIIe4QDjpo?p=preview

**Comment by hughanderson4** [comment]
@cagataycivici please re-open it.  i have this issue with current primeng, same as @richteri - see his plnkr, the textarea always 2x taller

**Comment by mdelorimier** [comment]
Hello, this issue still semms to persist in 8.1.1. Any plans to fix?
