### ISSUE TITLE
DataView: Fix typo in docs

### ISSUE THREAD

**Issue by SimonJ-DR** [primefaces/primeng#14391]
### Describe the bug

Small mistake in docs

### Environment

Exists in v17 docs

### Angular version

17.1.0

### PrimeNG version

17.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.5.1

**Comment by cetincakiroglu** [comment]
fixed in https://github.com/primefaces/primeng/pull/14390
