### ISSUE TITLE
Toast: UI is different from the one on the website

### ISSUE THREAD

**Issue by codrut1** [primefaces/primeng#14394]
### Describe the bug

When opening a toast, it can be noticed that it doesn't look right

### Environment

Windows 11, VSCode

### Reproducer

https://codesandbox.io/p/devbox/fervent-fast-jfsp85?file=%2Fbutton-demo%2Fsrc%2Fapp%2Fapp.component.html%3A5%2C20&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clq3qme7v0006356jepq0p49z%2522%252C%2522sizes%2522%253A%255B70.8965929304472%252C29.1034070695528%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clq3qme7v0002356jn8vu3813%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clq3qme7v0004356jnu4vk5vv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clq3qme7v0005356j5it9y2qz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B53.48534201954397%252C46.51465798045603%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clq3qme7v0002356jn8vu3813%2522%253A%257B%2522id%2522%253A%2522clq3qme7v0002356jn8vu3813%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqc53o8i0002356kd88fm0so%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A5%252C%2522startColumn%2522%253A20%252C%2522endLineNumber%2522%253A5%252C%2522endColumn%2522%253A20%257D%255D%252C%2522filepath%2522%253A%2522%252Fbutton-demo%252Fsrc%252Fapp%252Fapp.component.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqc53o8i0002356kd88fm0so%2522%257D%252C%2522clq3qme7v0005356j5it9y2qz%2522%253A%257B%2522id%2522%253A%2522clq3qme7v0005356j5it9y2qz%2522%252C%2522activeTabId%2522%253A%2522clqc53s97002a356kg2ui7z2c%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A34027%252C%2522id%2522%253A%2522clqc53s97002a356kg2ui7z2c%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clq3qme7v0004356jnu4vk5vv%2522%253A%257B%2522id%2522%253A%2522clq3qme7v0004356jnu4vk5vv%2522%252C%2522activeTabId%2522%253A%2522clqc52gfj00hf356jv22d43db%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq3qme7v0003356jz1quwq8a%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%252C%257B%2522id%2522%253A%2522clqc52gfj00hf356jv22d43db%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clqc52ggf025oefg61texdd6a%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Angular version

17.0.0

### PrimeNG version

17.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Steps to reproduce the behavior

1. Open any toast
2. Observe how it looks
![image](https://github.com/primefaces/primeng/assets/75161694/1379b222-f4d6-47d4-a105-a2973f2e1a1a)

To reproduce on Stackblitz, click the button to open the toast

### Expected behavior

![image](https://github.com/primefaces/primeng/assets/75161694/4a15f889-fc38-417d-8a99-067bfd31e4b2)

**Comment by codrut1** [comment]
Did you check the reproducer?

**Comment by siddhareddy** [comment]
Hey @codrut1 
You are using a different theme i.e `saga-blue` in your **angular.json** . Try changing the theme to `lara-light-blue` to get the desired theme

![image](https://github.com/primefaces/primeng/assets/9216710/f41a20df-0ed7-445c-aa10-e8b0e3ecdd3a)

Ref : [primeng-theming](https://primeng.org/theming)

**Comment by cetincakiroglu** [comment]
Your example doesn't even start and the we cannot reproduce mentioned issue with the latest primeng.

**Comment by codrut1** [comment]
Hi, I updated it to 17.3.0 and it still doesn't work, also try running the example now (on port 43541)

**Comment by siddhareddy** [comment]
You are missing one other thing in your **angular.json** styles   i.e "node_modules/primeng/resources/primeng.min.css" https://primeng.org/installation#styles
Once you have done that, try to rebuild your angular project with `ng serve --watch` or `ng build --watch` which is needed to refresh the dist files.
I downloaded it locally, its working as you expected
![image](https://github.com/primefaces/primeng/assets/9216710/f9964de4-3def-4d30-83e7-6608cc23f1ef)

Good luck!

**Comment by codrut1** [comment]
@siddhareddy you are right, a lot of the issues I had with the UI came from forgetting to include this dependency. Thanks for the help, I am still new to primeng and angular
