### ISSUE TITLE
p-multiSelect: Component not showing more than 3 values on input text field

### ISSUE THREAD

**Issue by taranipawan** [primefaces/primeng#14396]
### Describe the bug

If we are selecting more than 3 values in p-multiSelect component than it is not showing in input field.

![image](https://github.com/primefaces/primeng/assets/53966417/b83506e3-5dc2-4aa1-b6bf-053e9aeacd38)

### Environment

I am using PrimeNg version 16.9.1 and Angular 16.0.2

### Angular version

16.0.2

### PrimeNG version

16.9.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14.0

**Comment by kkoripl** [comment]
Looked through the code of v16.7.0 and just discovered that setting on component [maxSelectedLabels]="undefined" make it show everything you select.

**Comment by cetincakiroglu** [comment]
use maxSelectedLabels

https://stackblitz.com/edit/q47yiv?file=src%2Fapp%2Fdemo%2Fmulti-select-basic-demo.html,src%2Fapp%2Fdemo%2Fmulti-select-basic-demo.ts

**Comment by YerlinMatu** [comment]
[maxSelectedLabels]="items.length"
