### ISSUE TITLE
Component: Dropdown > Last Child of DropdownList remains selected

### ISSUE THREAD

**Issue by domsprung** [primefaces/primeng#14399]
### Describe the bug

When using the Dropdown component, the last item of the dropdown selection list is permanently displayed when selected. This means there is no longer any option to select other options.
![Animation](https://github.com/primefaces/primeng/assets/154335581/7bbbd0e2-1f0a-4fa3-8118-546c6fe71cc9)

### Environment

"dependencies": {
    "@angular/animations": "^16.2.12",
    "@angular/common": "^16.2.12",
    "@angular/compiler": "^16.2.12",
    "@angular/core": "^16.2.12",
    "@angular/forms": "^16.2.12",
    "@angular/platform-browser": "^16.2.12",
    "@angular/platform-browser-dynamic": "^16.2.12",
    "@angular/router": "^16.2.12",
    "@angular/service-worker": "^16.2.12",
    "@microsoft/signalr": "^8.0.0",
    "@ngrx/component-store": "^16.3.0",
    "primeflex": "^3.3.1",
    "primeicons": "^6.0.1",
    "primeng": "^16.9.1",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "workbox-sw": "^7.0.0",
    "workbox-window": "^7.0.0",
    "zone.js": "~0.13.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^16.2.2",
    "@angular-eslint/builder": "16.2.0",
    "@angular-eslint/eslint-plugin": "16.2.0",
    "@angular-eslint/eslint-plugin-template": "16.2.0",
    "@angular-eslint/schematics": "16.2.0",
    "@angular-eslint/template-parser": "16.2.0",
    "@angular/cli": "~16.2.2",
    "@angular/compiler-cli": "^16.2.12",
    "@types/jasmine": "~4.3.0",
    "@typescript-eslint/eslint-plugin": "5.62.0",
    "@typescript-eslint/parser": "5.62.0",
    "eslint": "^8.49.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.0",
    "husky": "^8.0.0",
    "jasmine-core": "~4.6.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "karma-junit-reporter": "^2.0.1",
    "lint-staged": "^14.0.1",
    "prettier": "^3.0.3",
    "prettier-eslint": "^15.0.1",
    "ts-loader": "^9.5.1",
    "typescript": "~5.1.3",
    "webpack-cli": "^5.1.4",
    "workbox-cli": "^7.0.0"
  }
  }

### Angular version

16.2.12

### PrimeNG version

16.9.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.10.0

### Browser(s)

Chrome

### Expected behavior

The selection should continue to work no matter which dropdown item is selected.

**Comment by cetincakiroglu** [comment]
Hi,

Could you please share a stackblitz reproducer so we can identify the issue?

**Comment by domsprung** [comment]
Here is the required Stackblitz: https://stackblitz.com/edit/github-2dcgac?file=src%2Fapp%2Fapp.component.ts

**Comment by cetincakiroglu** [comment]
Hi,

Component works as expected see the updated stackblitz https://stackblitz.com/edit/github-2dcgac?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts
