### ISSUE TITLE
InputGroup | Add styleClass and style input properties

### ISSUE THREAD

**Issue by msg-ptavoul** [primefaces/primeng#14404]
### Describe the bug

If we put an InputMask inside an InputGroup the InputMask width is very small.
So the InputMask is not filling up to 100% (it's more like 1%).

We tried to use the PrimeFlex class "w-full" to set the width up to 100%.
But that is not working...

### Environment

Windows 11

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-1l7ghs

### Angular version

17.0.0

### PrimeNG version

17.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.9.0

### Browser(s)

119.0.6045.200

### Steps to reproduce the behavior

1. Write an InputGroup Wrapper
2. Put an InputMask inside the wrapper
3. Run the Project and check the view
4. Put the PrimeFlex class "w-full" into the InputMask and check again the view - nothing happened

**Comment by cetincakiroglu** [comment]
Hi,

pInputGroup needs styleClass and style input properties to fix it. Updating the issue title.

**Comment by msg-ptavoul** [comment]
Thank you very much for the quick answer @cetincakiroglu , but the problem was not fixed...
I updated the stackblitz code with actual and expected examples.

Please reopen the bug.
*I added an old issue to the code.
