### ISSUE TITLE
Datatable top and bottom number of links out of sync

### ISSUE THREAD

**Issue by rklempert** [primefaces/primeng#1441]
Posted this under issue #671. Since it is marked closed, maybe you are not looking at comments for closed issues.

I am using [lazy]="true" and "both." Showing 10 links and on the first page of results and increasing rows from 10 to 100, changes to fewer number of links only in the paginator in which the dropdown was changed. If selecting rows from 10 to 100 on a page other than first, like 2nd or 3rd page of results, everything works. The reset of links doesn't happen for first page.

**Comment by cagataycivici** [comment]
Create a plunkr please;

http://plnkr.co/edit/NtWWnN

**Comment by rklempert** [comment]
I’m not sure I can do that, too much code to move over into Plunkr. Can I do a screen recording or Skype share or any other way?

Thanks,
Robert Klempert | bswift
10 S. Riverside Plaza, Suite 1100
Chicago, IL 60606
312.373.3483 (direct)
877.9.BSWIFT (toll free)
rklempert@bswift.com<mailto:rklempert@bswift.com>
www.bswift.com<http://www.bswift.com/>

**Comment by padryn** [comment]
I've observed the same behavior.  I've created a simple project using angular-cli that illustrates this issue.  I'll see if I can move it over to plunker.

**Comment by padryn** [comment]
Okay, I've forked and updated the plunker.

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/MxSw4qOuwDfq7rLO7jrR?p=preview
