### ISSUE TITLE
Component: TreeTable - 

### ISSUE THREAD

**Issue by mb-19** [primefaces/primeng#14412]
### Describe the bug

When adding a StyleClass to a TreeNode in TreeTable it wont apply. For Example adding styleclass opacity-30 to a TreeNode wont change the Opacitity.
It works fine in other components like Tree. 

### Environment

Node20 
Primeng 17+
Angular 17

### Angular version

17

### PrimeNG version

17

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20

### Steps to reproduce the behavior

(https://stackblitz.com/edit/4kpoo7-yrnqvw?file=src%2Fapp%2Fdemo%2Ftree-table-basic-demo.ts)

**Comment by cetincakiroglu** [comment]
Hi,

Could you please share a stackblitz reproducer so we can identify the issue clearly?

**Comment by mb-19** [comment]
hello, 

thank you, here is a stackblitz reproducer: https://stackblitz.com/edit/4kpoo7-yrnqvw?file=src%2Fapp%2Fdemo%2Ftree-table-basic-demo.ts
