### ISSUE TITLE
Component: Dropdown - If editable is true and optionValue is present, the selected option will not be shown

### ISSUE THREAD

**Issue by dumitru-tabara-dev** [primefaces/primeng#14427]
### Describe the bug

If the "enabled" flag is se to true and the optionValue is different than the default value('value') then after selecting an option in the dropdown, the selected option will not be visible in the UI.

![dropdown](https://github.com/primefaces/primeng/assets/108414209/6db518f3-e174-4b30-bca0-9fa2c6cd5d7d)

The stackblitz file contains two cases: the first one is working and the second one is not working because of the optionValue.

### Environment

Angular 17.0.8 + PrimeNG 17.2.0

### Reproducer

https://stackblitz.com/edit/unjmt9-fsxjbz?file=src%2Fapp%2Fdemo%2Fdropdown-editable-component.html

### Angular version

17.0.8

### PrimeNG version

17.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.0

### Browser(s)

Chrome 120.0

**Comment by cetincakiroglu** [comment]
Hi,

Thanks for reporting, we've fixed the issue. `optionValue` property should be ignored when `editable` is set to true.  You don't need to provide optionValue if the dropdown is editable. only `optionLabel` is required if the options are not in string format.

**Comment by dumitru-tabara-dev** [comment]
Hi @cetincakiroglu ,
What if I want to set the value of the selected input but not the label in my reactive form field?
An example:
I have an object like this in my array: { fieldName: "SomethingName", fieldValue: "SomethingValue" }.
And i have the following attributes set in my dropdown: 
**"formControlName"="myFormProp"
"editable"=true
"optionLabel"="fieldName"
"optionValue"="fieldValue"**
When I select an option from the dropdown I'm expecting myFormProp from the formGroup to contain "SomethingValue", not "SomethingName".
But if I type something in the dropdown, for example: "Some typing", I'm expecting myFormProp = "Some typing".

I hope it makes sense, this is why I specify the optionValue, and it used to work as expected before.

**Comment by cetincakiroglu** [comment]
Checked the previous versions, optionValue omitted there if the input is editable, even if it provided, component was using optionLabel in editable.
