### ISSUE TITLE
<p-tabView orientation="bottom"> doesn't work correctly

### ISSUE THREAD

**Issue by llnagy** [primefaces/primeng#1442]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
when I set the tabview orienation to "bottom" the tabs are at the top, but have the look of bottom tabs, meaning top of rectangle is open at the top.

**Expected behavior**
The tabs should be below the tabPanels

**Minimal reproduction of the problem with instructions**
Create an app with the a tabview in a panel and the orientation="bottom".  Note: all other orientations work, "top", "left", "right". Only "bottom" doesn't work correctly.

<div class="panel panel-default">
    <div class="panel-body">
        <p-tabView orientation="bottom">
            <p-tabPanel header="Definitions">
                Content 0
            </p-tabPanel>
            <p-tabPanel header="Equipment">
                Content 1
            </p-tabPanel>
            <p-tabPanel header="Procedures">
                Content 2
            </p-tabPanel>
        </p-tabView>
    </div>
</div>

**What is the motivation / use case for changing the behavior?**
We want the tabs to be at the bottom.

**Please tell us about your environment:**
Windows 7, webpack

* **Angular version:** 2.0.X
angular 2.2.0

* **PrimeNG version:** 2.0.X
"primeng": "^1.0.0",

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

CHROME Version 54.0.2840.99 m
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
"typescript": "2.0.9", ES5.1 or ES6

* **Node (for AoT issues):** `node --version` =

**Comment by William-2020-03-03** [comment]
how can I solve this issue? I also met thie issue.
