### ISSUE TITLE
Dropdown | Deprecate autoDisplayFirst property

### ISSUE THREAD

**Issue by cetincakiroglu** [primefaces/primeng#14426]
- `autoDisplayFirst` property will be removed in the future because of the maintenance time cost and model value collisions.

- Instead of the autoDisplayFirst, users can set the value by the model value as shown below.

```

// component.html
<p-dropdown [options]="cities" [(ngModel)]="selectedCity" optionLabel="name" placeholder="Select a City"></p-dropdown>


// component.ts
    cities: City[];

    selectedCity: City | undefined;

    ngOnInit() {
        this.cities = [
            { name: 'New York', code: 'NY' },
            { name: 'Rome', code: 'RM' },
            { name: 'London', code: 'LDN' },
            { name: 'Istanbul', code: 'IST' },
            { name: 'Paris', code: 'PRS' }
        ];
        this.selectedCity = this.cities[0] // same output with the autoDisplayFirst property, therefore it's not needed.
    }

```

**Comment by alexnoise79** [comment]
it's a pity cause scenario like this cannot be used anymore, and they were very useful

`<p-dropdown [options]="cities" ngModel optionLabel="name" (ngModelChange)="doThis($event)></p-dropdown>`

**Comment by PeterHewat** [comment]
Documentation needs updating: https://primeng.org/dropdown#api.dropdown.props.autoDisplayFirst

**Comment by ArturJarosz** [comment]
Isn't ngModel deprecated as well?

**Comment by AlbaSS18** [comment]
And if I don't want to select any value, what value should I set? Null or undefined?

**Comment by majkers** [comment]
It's a really bad change. What if we to force user to select an item (so we don't want to select firs item) and option list is taken from service? We have either spread it (option list) with empty|null value and label or use empty placeholder now...

**Comment by digitalcraftco** [comment]
What about async as options now? https://github.com/primefaces/primeng/issues/14190#issuecomment-2221402942

**Comment by samwightt** [comment]
Unfortunately this broke our app on our Angular 17 upgrade and was quite annoying to hunt down :( Wish this hadn't been deprecated.

**Comment by Kolic822** [comment]
You can create a custom directive for p-dropdown that will auto display first

`import { AfterContentInit, Directive } from '@angular/core';
import { NgControl } from '@angular/forms';
import { Dropdown } from 'primeng/dropdown';

@Directive({
  selector: '[autoSelectFirst]',
  standalone: true,
})
export class AutoSelectFirstDirective implements AfterContentInit {
  constructor(
    private control: NgControl,
    private dropdown: Dropdown,
  ) {}

  ngAfterContentInit(): void {
    // Ensure the form control exists
    const formControl = this.control.control;
    if (!formControl) return;

    // Auto-select the first option when options are available
    const setFirstOption = () => {
      if (this.dropdown.options && this.dropdown.options.length > 0) {
        const firstValue = this.dropdown.options[0].value;
        formControl.patchValue(firstValue.toUpperCase());
      }
    };

    // PrimeNG `p-dropdown` may load options asynchronously, so use `ngAfterViewInit` to wait for them
    setFirstOption();

    // Listen for option changes on the dropdown (using PrimeNG's update event)
    this.dropdown.onShow.subscribe(setFirstOption);
  }
}
`
