### ISSUE TITLE
Mask Placeholder text color is wrong color in IE

### ISSUE THREAD

**Issue by daddyschmack** [primefaces/primeng#1443]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

The mask placeholder is dark color in IE 11, while it's light gray in chrome
**Expected behavior**

The mask placeholder would the same color across all browsers
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

The color should be consistent across all browsers
**Please tell us about your environment:**

Windows 7 IE 11
* **Angular version:** 2.0.X

2.02
* **PrimeNG version:** 2.0.X

1.0
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript 2.0
* **Node (for AoT issues):** `node --version` =   
6.3.0

**Comment by daddyschmack** [comment]
I addressed this in my project with the following scss entry:
p-inputMask {
  :-ms-input-placeholder {
    color: darkgray;
  }
}

**Comment by sudheerj** [comment]
Yes,it is replicated for placeholder text-color.MS specific style class required to make it consistent with other browsers.

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
