### ISSUE TITLE
Tooltip: disable autoHide doesn't with positionLeft property

### ISSUE THREAD

**Issue by AliKholmatov** [primefaces/primeng#14431]
### Describe the bug

Hi! Tooltip: disable autoHide doesn't work with positionLeft property.

### Environment

Angular 16.2.7

### Angular version

16.2.7

### PrimeNG version

16.9.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v18.18.0

**Comment by maruthumj** [comment]
Hi @AliKholmatov . It will be helpful for me to debug the issue if you provide any stackblitz reproducer

**Comment by AliKholmatov** [comment]
@maruthumj Hi. https://stackblitz.com/edit/wszuks?file=src%2Fapp%2Fdemo%2Ftooltip-auto-hide-demo.html

**Comment by AliKholmatov** [comment]
Hi. Any updates?)
