### ISSUE TITLE
p-menubar: `ERROR TypeError: Cannot read properties of undefined (reading 'item')` when clicking on disabled menu item

### ISSUE THREAD

**Issue by apolishko** [primefaces/primeng#14434]
### Describe the bug

Create p-menubar  where [model] is an array of MenuItems with all items disabled. Click on any disabled item. The following exception is thrown: 

> core.mjs:11760 ERROR TypeError: Cannot read properties of undefined (reading 'item')
>     at Menubar.onMenuFocus (primeng-menubar.mjs:777:184)
>     at Menubar_Template_p_menubarSub_menuFocus_3_listener (primeng-menubar.mjs:1114:30)
>     at executeListenerWithErrorHandling (core.mjs:24632:16)
>     at Object.wrapListenerIn_markDirtyAndPreventDefault [as next] (core.mjs:24665:22)
>     at ConsumerObserver.next (Subscriber.js:91:33)
>     at SafeSubscriber._next (Subscriber.js:60:26)
>     at SafeSubscriber.next (Subscriber.js:31:18)
>     at Subject.js:34:30
>     at errorContext (errorContext.js:19:9)
>     at EventEmitter_.next (Subject.js:27:21)
> 

```
class Menubar {
    onMenuFocus(event: any) {
        this.focused = true;
        const processedItem = this.findVisibleItem(this.findFirstFocusedItemIndex());
        const focusedItemInfo = this.focusedItemInfo().index !== -1 ? this.focusedItemInfo() : { index: this.findFirstFocusedItemIndex(), level: 0, parentKey: '', item: processedItem.item };

        this.focusedItemInfo.set(focusedItemInfo);
        this.onFocus.emit(event);
    }
}
```

**The processedItem is udefined.**

### Environment

Window 11

### Angular version

17.0.8

### PrimeNG version

17.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.9.0

### Browser(s)

Chrome 120.0.6099.129

### Steps to reproduce the behavior

![image](https://github.com/primefaces/primeng/assets/40760636/c3c690c3-4eaa-47ce-abc7-463bd4874900)

### Expected behavior

There should be no exception

**Comment by abdallahifox** [comment]
it will be helpful if you provide any stackblitz  example to debug your problem

**Comment by apolishko** [comment]
https://stackblitz.com/edit/stackblitz-starters-swwf8t?file=src%2Fmain.ts

Please click on any menu bar item

**Comment by cetincakiroglu** [comment]
Thanks a lot for reporting the issue!
