### ISSUE TITLE
Tree removed css classes

### ISSUE THREAD

**Issue by HeavyRainLQ** [primefaces/primeng#14445]
### Describe the bug

removed css class on [3f8dcc3](https://github.com/primefaces/primeng/commit/3f8dcc36b8aae81f39607c8c66bfd7234b4edf3e)
now we dont have any connector ui like this 

![no-connector](https://github.com/primefaces/primeng/assets/18249297/fbc9937f-300d-4c8d-9cd4-908ce13af1f6)

### Environment

NA

### Reproducer

https://stackblitz.com/edit/jqtsyy-iu3jee?file=src%2Fapp%2Fdemo%2Ftree-basic-demo.html

### Angular version

17.0.8

### PrimeNG version

17.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Steps to reproduce the behavior

using p-tree in horizontal layout

### Expected behavior

![image](https://github.com/primefaces/primeng/assets/18249297/cc0b2874-c79d-4a0a-8289-e4368625043c)

**Comment by JuliaHorokhovatska** [comment]
I have same problem https://github.com/primefaces/primeng/issues/14656
