### ISSUE TITLE
Component: ToggleButton

### ISSUE THREAD

**Issue by lm-niranjan** [primefaces/primeng#14443]
### Describe the bug

`tabindex` attribute  on `ToggleButton` is not set as expected.

### Environment

NA

### Reproducer

https://stackblitz.com/edit/rqvhch-jhgnnm?file=src%2Fapp%2Fdemo%2Ftoggle-button-reactive-forms-demo.html

### Angular version

17.0.2

### PrimeNG version

17.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.17.1

### Steps to reproduce the behavior

1. Goto - https://stackblitz.com/edit/rqvhch-jhgnnm?file=src%2Fapp%2Fdemo%2Ftoggle-button-reactive-forms-demo.html
2. Click on button number 1
3. Press Tab key

### Expected behavior

Expected that the focus follows the button order as per number.

**Comment by cetincakiroglu** [comment]
Fixed in https://github.com/primefaces/primeng/pull/14444
