### ISSUE TITLE
Ultima label transition with primeng p-inputMask

### ISSUE THREAD

**Issue by djay1977** [primefaces/primeng#1444]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

With Ultima template, there is a transition css to put the label in the inputfield like placeholder.
When there is focus on inputfield, the css transition put the label above the field. The same behavior when the field is initialized with ngModel.

With the p-inputMask, the css transition doesn't work when the field is initialized with ngModel and the label stay in field with value.

Code :
`<span class="md-inputfield">
<p-inputMask [(ngModel)]="val" mask="99-9999"></p-inputMask>
<label>Test Mask</label>
</span>
<span class="md-inputfield">
<input [(ngModel)]="val2" type="text" pInputText>
<label>Name</label>
</span>`

Result with value :
[See printscreen](http://img4.hostingpics.net/pics/33054420161127113202PrimeNGULTIMA.png)

**Expected behavior**

I should have the same behavior as for pInputText. See the second example on the following link:
[See printscreen](http://img4.hostingpics.net/pics/33054420161127113202PrimeNGULTIMA.png)

**Minimal reproduction of the problem with instructions**

See the code below based on the sources code ultima theme with primeng.

**What is the motivation / use case for changing the behavior?**

I think this is a bug in the css transition of the ultima theme for the p-inputMask.
It works well with other types of fields.

**Please tell us about your environment:**

Windows 8
IntelliJ Idea 2016.3
npm
lite server
lastest version of Google Chrome

* **Angular version:** 2.2.3

* **PrimeNG version:** 1.0.0

* **Browser:** Chrome 54.0.2840.99

 
* **Language:** TypeScript 2.0.10

* **Node (for AoT issues):** `node --version` =  6.9.1

**Comment by gilsondev** [comment]
I'm using PrimeNG 1.1.4 and this problem happen again

**Comment by mertsincan** [comment]
Please try this issue with PrimeNG 2.0.RC1 version.

**Comment by gilsondev** [comment]
The problem is still occurring

**Comment by intergleam** [comment]
any update? Any warranty on my Barcelona? this is a stopper for us
