### ISSUE TITLE
Accordion

### ISSUE THREAD

**Issue by HAOCHUMG** [primefaces/primeng#14440]
When I click accordion,Can cancel turn on or turn off accordiontab?I want to use p-inputswich control this component and,my p-inputswich is on the p-accordion and trigger bubble event. How can I do?

**Comment by cetincakiroglu** [comment]
Hi,

You can use icon templating option of the accordion https://primeng.org/accordion#api.accordion.templates.icon

**Comment by HAOCHUMG** [comment]
https://github.com/primefaces/primeng/assets/107093038/37540406-7e97-4051-ba16-b12636624c32

**Comment by HAOCHUMG** [comment]
How can I solved this problem 😭😭

**Comment by HAOCHUMG** [comment]
@cetincakiroglu  How can I use icon templating ， I dont want when I click accrodion it trigger open or close ,I want to controll open and close by button How can I use icon templating to complete this problem

**Comment by HAOCHUMG** [comment]
@cetincakiroglu if I use template icon is destory ,because my p-inputSwitch also on this accordion ，also disable too ，How can I fix this problem
