### ISSUE TITLE
listbox filter is not working if options is bind to a string array

### ISSUE THREAD

**Issue by ioantoader** [primefaces/primeng#14454]
### Describe the bug

I have a listbox like
```
 <p-listbox [filter]="true" [multiple]="true" [checkbox]="true"
                    [metaKeySelection]="false" [(ngModel)]="filterConstraint.value" [options]="c?.filterOptions??[]"
                    class="time-series-filter-listbox"></p-listbox>
```

where     public filterOptions: string[] | undefined; not an array of objects label, value, In this case when I enter a value in the filter always the list is empty

### Environment

windows

### Angular version

17.0.8

### PrimeNG version

17.03

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.10

**Comment by julesyan** [comment]
I am encountering the same problem. I have made a stackblitz for it here: https://stackblitz.com/edit/gjuaa6?file=src%2Fapp%2Fdemo%2Flistbox-filter-demo.html

Have yet to figure out a workaround...

**Comment by DanielWojciechowskiLingaro** [comment]
+1, Any updates on this issue?

**Comment by DanielWojciechowski** [comment]
+1, any updates on this issue?

**Comment by hemal-panchasara** [comment]
I am facing the same issue with p-listbox. primeng version 16 and angular version 17
