### ISSUE TITLE
p-listbox empty filter message is not being shown

### ISSUE THREAD

**Issue by nikhilwadibhasme** [primefaces/primeng#14459]
### Describe the bug

p-listbox empty filter message is not working as expected.

Expected - 
After filtering, if no data is found, It should show set emptyFilterMessage.

Demo - 
https://stackblitz.com/edit/mxdtg7?file=src%2Fapp%2Fdemo%2Flistbox-virtual-scroll-demo.ts,src%2Fapp%2Fdemo%2Flistbox-virtual-scroll-demo.html

### Environment

https://stackblitz.com/edit/mxdtg7?file=src%2Fapp%2Fdemo%2Flistbox-virtual-scroll-demo.ts,src%2Fapp%2Fdemo%2Flistbox-virtual-scroll-demo.html

### Reproducer

https://stackblitz.com/edit/mxdtg7?file=src%2Fapp%2Fdemo%2Flistbox-virtual-scroll-demo.ts,src%2Fapp%2Fdemo%2Flistbox-virtual-scroll-demo.html

### Angular version

17.0.7

### PrimeNG version

17.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.10.0

### Browser(s)

Chrome

**Comment by Basketblo** [comment]
@mehmetcetin01140 Could you take a look, when you will have a possibility?
