### ISSUE TITLE
p-accordion: Accordion inside a p-tabView which is inside a p-dialog will appear all expanded the second time the dialog is opened.

### ISSUE THREAD

**Issue by AIO1** [primefaces/primeng#14458]
### Describe the bug

Here is part of the code of the dialog:
```
p-dialog [(visible)]="houseModalShow" [modal]="true" [style]="{ width: '95vw', height: '95vw'}" [draggable]="false" [resizable]="false" [closeOnEscape]="false" [closable]="false" [maximizable]="true">
```

The code of the tabView:
```
    <p-tabView [scrollable]="true">
        <p-tabPanel> <!--DATOS GENERALES-->
            <ng-template pTemplate="header"> 
                <i class="pi pi-info-circle" [ngStyle]="{'margin-right.px': 8}"></i>
                <span>General data</span>
            </ng-template>
            <p-accordion class="w-full">
                <p-accordionTab>
```

First time the dialog window is opened they will appear like so:
![image](https://github.com/primefaces/primeng/assets/17305493/0590cbce-75af-4dc8-acf6-a5849dab56ec)

The second time they will appear expanded like this (and multiple has not been enabled):
![image](https://github.com/primefaces/primeng/assets/17305493/1add6be0-a57e-438d-9f40-34099cc6346b)

This is not the expected behaviour, they should be all collapsed when opening subsequent times the dialog.

### Environment

Development

### Angular version

17

### PrimeNG version

17.3.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.10.0

**Comment by ashikjs** [comment]
@AIO1  can you add some stackblitz re-generatable code for this .

**Comment by AIO1** [comment]
> @AIO1 can you add some stackblitz re-generatable code for this .

Here you go:
https://stackblitz.com/edit/primeng-tablevirtualscroll-demo-rhjlhx?file=src%2Fapp%2Fapp.component.html

Click the "Open window" and you will see all accordions collapsed. Close the modal window with any of the 2 buttons of the right bottom.
Open again the modal window with "Open window" and you will see both accordions expanded.

If you need anything else, just let me know.

Thanks in advance! :)

**Comment by ashikjs** [comment]
@AIO1 Ya, your right here have a issue when  you use accordion in dialog it's behave worried when dialog closed and re-open.
PrimeNg team maybe will solve it soon. 

but if you want, you can do a temporary solution like this.

```
 <p-tabView [scrollable]="false" *ngIf="aModalShow">
    <p-tabPanel>
                ******
  </p-tabPanel>
  </p-tabView>

```

NB: it will generate UI flicker or blink  issue .

**Comment by puschie286** [comment]
solution from https://github.com/primefaces/primeng/issues/9453#issuecomment-718573057 works great
