### ISSUE TITLE
Component: Sidebar. Cannot close sidebar programmatically

### ISSUE THREAD

**Issue by mountpoint** [primefaces/primeng#14450]
### Describe the bug

In version 17.3.0 when you try to close programmatically by setting **[(visible)] --> false** sidebar disappears but the mask stays visible. So I downgraded back to 17.2.0

https://stackblitz.com/edit/774ddz-9b8nth

### Environment

any

### Reproducer

https://stackblitz.com/edit/774ddz-9b8nth

### Angular version

17

### PrimeNG version

17.3.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

-

### Steps to reproduce the behavior

1. Go to https://stackblitz.com/edit/774ddz-9b8nth
2. Open sidebar by pressing Show button
3. Close sidebar by pressing Hide button

Current behavior: the mask stays visible

### Expected behavior

the mask become invisible

**Comment by critchie** [comment]
I'm having the exact same issue. This is indeed a new issue with 17.3.0.

**Comment by riker09** [comment]
Is this related or even the same as https://github.com/primefaces/primeng/issues/14254 ?

**Comment by critchie** [comment]
This is definitely a different issue. #14254 fixed that issue but appears to have caused this issue.

With this issue when you close the sidebar programmatically the sidebar closes but the <div> element that blocks the UI remains in the DOM. The user can’t interact with the application because it is blocked.

**Comment by dumitru-tabara-dev** [comment]
I'm having this issue as well.

**Comment by LightBulbIdea** [comment]
Can confirm, after upgrading from 17.2 to 17.3 I am seeing this issue with the sidebar component. Will need to downgrade to 17.2 until this gets fixed.

**Comment by dumitru-tabara-dev** [comment]
@cetincakiroglu , can you take a look at this and let us know when you will be able to fix it? It is a pretty big issue that affects the sidebar usage.
Thank you a lot.

**Comment by cetincakiroglu** [comment]
Hi,

Thanks a lot for reporting the issue, we're working on it.

**Comment by mountpoint** [comment]
> Hi,
> 
> I've fixed it right now, but the problem is you cannot use signal with two way binding yet. Your example will work after the fix but, you shouldn't use `[visible]="sidebarVisible()"` because visible property is designed with two way binding and you cannot set sidebarVisible after visible changes to false. Best approach would be using a variable instead of signal. `[(visible)]="sidebarVisible"` will work.

It doesn't work even without signals, with normal approach

**Comment by Adrii77** [comment]
I think cetin means it won't work with signals **after** his fix ?

**Comment by mountpoint** [comment]
> > > Hi,
> > > I've fixed it right now, but the problem is you cannot use signal with two way binding yet. Your example will work after the fix but, you shouldn't use `[visible]="sidebarVisible()"` because visible property is designed with two way binding and you cannot set sidebarVisible after visible changes to false. Best approach would be using a variable instead of signal. `[(visible)]="sidebarVisible"` will work.
> > 
> > 
> > It doesn't work even without signals, with normal approach
> 
> I think cetin means it won't work with signals **after** his fix ?

I don't know... in my project I use usual approach without signals and in version 17.3.0 it doesn't work

**Comment by critchie** [comment]
> Hi,
> 
> I've fixed it right now, but the problem is you cannot use signal with two way binding yet. Your example will work after the fix but, you shouldn't use `[visible]="sidebarVisible()"` because visible property is designed with two way binding and you cannot set sidebarVisible after visible changes to false. Best approach would be using a variable instead of signal. `[(visible)]="sidebarVisible"` will work.

This suggestion along with 17.3.1 fixes the issue for me. The sidebar is functioning as expected.

**Comment by riker09** [comment]
After carefully reviewing all comments here I believe I had a different issue. The modal-backdrop was not closed when clicking a link within the sidebar (and thus navigating to a different page). The links were inside a p-tree component (default Angular routing links).

However, upgrading to v17.3.1 has resolved this and now I can use the default `[modal]="true"` again.

**Comment by mogmura3** [comment]
In my case, I was able to close the sidebar by calling detectChanges in the closeCallback method.
Here is the relevant part of my code:

```typescript
export class SideBarComponent {
	@ViewChild("sidebarRef") sidebarRef!: Sidebar;

	constructor(private readonly cd: ChangeDetectorRef) {}

	closeCallback(e: any): void {
		this.sidebarRef.close(e);
		this.sidebarVisible = false;

		this.cd.detectChanges();
		console.log("this.sidebarVisible", this.sidebarVisible);
	}

	sidebarVisible = true;
}
```
By calling this.cd.detectChanges() after setting this.sidebarVisible = false, I was able to successfully close the sidebar. However, I would like to mention that I am not very familiar with Angular and PrimeNG, so there might be a better solution that I am unaware of.

**Comment by MacMeissner** [comment]
I created a new Angular18 project. 
After installation of PrimeNg, PrimeFlex and PrimeIcons i tried to run this.

```html
<p-sidebar [visible]="true" [dismissible]="false" [modal]="true" > 
   Bla
</p-sidebar>
```

Same Problem. Can not close the Sidebar.

Following these steps: 

1. Create a sidebarvisible member in Component-Class.
```typescript
sidebarVisible = true;
```

2. Change Binding to Two-Way-Binding

```html
<p-sidebar [(visible)]=sidebarVisible [dismissible]="false" [modal]="true" > 
   Bla
</p-sidebar>
```

3. Add provideNoopAnimations to app.config.ts 
```typescript
export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes), 
    provideClientHydration(),

    // important
    provideNoopAnimations(),
  ]
};
```

Now it's running.

**Comment by carcigenicate** [comment]
This is still broken in V21's `p-drawer`s. Setting `[visible]` to `false` doesn't cause the mask to disappear. 

Looking through the source, I'm not even sure how this is meant to work. The only place I can see setting `[visible]` having any effect is in the [`visible` setter](https://github.com/primefaces/primeng/blob/5d830b126c4b1bd879843b1b4340281fbd0ff192/packages/primeng/src/drawer/drawer.ts#L207). That enables the modal if `visible` was set to true, but doesn't do anything if it was set to false.

And, on top of the mask not being removed, `(onHide)` also doesn't fire if the drawer was closed by setting `[visible]`.

**Comment by domhirs** [comment]
Facing the same issue as @carcigenicate with PNG21 in an Angular21 Application. 

After "closing" the p-drawer via setting `visible = false`, the mask remains in the DOM. As if i am performing a logout, the mask stays in the dom placed in the highest layer, preventing the user from any action on the page.

It looks like a race condition, as its working as intended when I set a timeout before trying to route.

**Comment by carcigenicate** [comment]
@domhirs 

I should have posted it here, but see my temporary fix that I posted in another similar issue thread: https://github.com/primefaces/primeng/issues/19214#issuecomment-3791411546

It's meant to be a simple patch that requires minimal changes and is easy to remove if they fix this.

**Comment by domhirs** [comment]
@carcigenicate ah great, thank you for the response.
