### ISSUE TITLE
p-autocomplete: optionLabel input has wrong type

### ISSUE THREAD

**Issue by AndreasHae** [primefaces/primeng#14468]
### Describe the bug

The documentation for `optionLabel` in `p-autocomplete` says:
> Property name or getter function to use as the label of an option

But this is not apparent in the type, which is only `string`. If I want to pass a getter function, I have to use `$any` otherwise I get a compile error in the template.

Hence the type should be changed to `string | (item: any) => string`.

### Environment

See versions below

### Angular version

17.0.6

### PrimeNG version

17.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.0

**Comment by SoyDiego** [comment]
Hi @AndreasHae, I did a PR solving the problem. You can check it here: #14486.
Now we should wait PrimeNG Team approve it if they think the solution is OK for them.
