### ISSUE TITLE
PrimeNG website: Navigating by URL not possible (404 error)

### ISSUE THREAD

**Issue by PranKe01** [primefaces/primeng#14460]
### Describe the bug

When you try to access for example https://www.primefaces.org/primeng-v16-lts/installation you will get a 404 error message.

### Environment

All

### Reproducer

https://www.primefaces.org/primeng-v16-lts/installation

### Angular version

all

### PrimeNG version

all

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

all

### Steps to reproduce the behavior

1) Go to https://www.primefaces.org/primeng-v16-lts/installation

### Expected behavior

When you visit https://www.primefaces.org/primeng-v16-lts/installation the page should show up, like when you navigate to it via the primeng start page (which is possible).

**Comment by SoyDiego** [comment]
Yes, it's not working.
Right now is working (like you said) if you access vía: 

![image](https://github.com/primefaces/primeng/assets/19764334/a6903875-149e-4eff-acc5-decedb52b610)

**Comment by PranKe01** [comment]
Yes, but in respect of bookmarks and SEO, it should also work by accessing by URL. :)

**Comment by PranKe01** [comment]
Looks like it is working now.
