### ISSUE TITLE
Table | custom state save/restore [new feature]

### ISSUE THREAD

**Issue by cervenf** [primefaces/primeng#14461]
### Describe the bug

At the moment table support only to store state (pagination, sorting, filtering options) to session or local storage.
Would be nice to have possibility to implement custom state save and restore.

### Environment

not important

### Angular version

17

### PrimeNG version

17

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20

**Comment by critchie** [comment]
@cervenf  I needed something like you're asking for so I came up with this table-manager service. Take a look at this StackBlitz and see if it will help you.

[Table Manager](https://stackblitz.com/edit/vxtyck?file=src%2Fapp%2Fdemo%2Ftable-manager-demo.ts)

**Comment by cervenf** [comment]
@critchie Sorry for late replay. Thank you very much for the answer and also code sharing.

If I understand Table manager correctly it helps mainly in these 2 things:
[columns]="tableManager.selectedColumns"
[globalFilterFields]="tableManager.filterFields"
And rest is stored to local storage via: stateStorage="local"

Is there some way to store/restore sorting and filtering, please?

In my case, I have tree as navigation and I'm displaying data in table based on which node is selected.
Grid is reused and in some cases I would like to keep filters and sort. But not pageNumber and page size because data are different.
Thank you.

**Comment by critchie** [comment]
@cervenf When you create a new instance of TableManager the constructor will read in the data from local storage. Line 45 in the ngOnInit() is where new TableManager is called. If you take a look at the TableManager constructor you will see where it does the read from local storage. All the rest is standard Angular binding. The ngAfterViewInit() is needed to assign the actual table to the TableManager. I had to do it this way because the table isn’t fully built and available until AfterViewInit.

**Comment by cervenf** [comment]
I mean, I would like to store only sorting (column names, order etc.) and filtering (column names, operator..) and not current page.
I would like to not use default:
  <p-table
    **stateStorage="local"**    
  >

But then I don't know how to restore (initialise table) with stored values.

**Comment by cervenf** [comment]
Thank you.

I didn't know that p-table has these properties which I can set manually:
<p-table
[filters]=...
[multiSortMeta]=...
[rows]=

I'm using lazyload tables and I can store those values during (onLazyLoad) and restore them in the constructor.
