### ISSUE TITLE
Dropdown | Component selects first option on tab press

### ISSUE THREAD

**Issue by cetincakiroglu** [primefaces/primeng#14473]
steps to reproduce:

1-) Without any interaction, focus on the dropdown by pressing tab.
2-) Press tab again, it should move the focus to the next focusable element but it selects the first value instead.

Reported on discord: https://discord.com/channels/787967399105134612/787967806367989790/1192056571904135289

**Comment by eironman** [comment]
Hello, Did you get any answer on this? The Discord link does not work.
