### ISSUE TITLE
@Anuj170122  how did you work on this particular issue ?

### ISSUE THREAD

**Issue by AVSOLVE** [primefaces/primeng#14470]
@Anuj170122  how did you work on this particular issue ?

_Originally posted by @EddyMurphy95 in https://github.com/primefaces/primeng/issues/1342#issuecomment-1821249344_
            
HTML

<div class="m-4">
  <button
    pButton
    label="Limpar"
    class="p-button-outlined"
    icon="pi pi-filter-slash"
    (click)="clear(dt1)"
  ></button>
  <span class="p-input-icon-left ml-auto">
    <i class="pi pi-search"></i>
    <input
    pInputText
    type="text"
    (input)="filterGlobal($event)"
    placeholder="Global Search"
  />
  </span>
</div>

TYPESCRIPT

 filterGlobal(event: Event) {
    const filter: any = (event.target as HTMLInputElement).value;
    const filterFields = [
      'example',
    ];

    if (this.dt1) {
      this.dt1.value = this.filterService.filter(this.data, filterFields, filter, 'contains');
    }
  }

  clear(table: Table) {
    table.clear();
  }

**Comment by cetincakiroglu** [comment]
Hi,

Issue is not clear and due to invalid format.
