### ISSUE TITLE
Component: Dropdown/Calendar

### ISSUE THREAD

**Issue by aleximunichre** [primefaces/primeng#14479]
### Describe the bug

A dropdown (and calendar) component get their views hidden behind other html elements when positioned within container with CSS overflow-y: auto

Here's when dropdown opens-up and goes behind absolutely positioned header (blue)
![image](https://github.com/primefaces/primeng/assets/155632596/d9ff90be-5680-4d0a-b2ae-e405daf26fe5)

Here's when dropdown opens downwards
![image](https://github.com/primefaces/primeng/assets/155632596/8f0ac464-8089-49b2-96c4-4c5ceea74283)

### Environment

Linux

### Reproducer

https://stackblitz-starters-kgvrsb.stackblitz.io

### Angular version

17.0.8

### PrimeNG version

17.0.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.13.0

### Steps to reproduce the behavior

1. Create a container div with CSS:
.container {
  margin: 64px 0;
  height: 100px;
  overflow-y: auto;
}
2. Place dropdown/calendar within the container
3. Should be able to see that both elements render only partially

### Expected behavior

Should the calendar/dropdowns be visible at max screen view ?

**Comment by cetincakiroglu** [comment]
Stackblitz link is broken, could you please try it with appendTo="body" ?

**Comment by aleximunichre** [comment]
> Stackblitz link is broken, could you please try it with appendTo="body" ?

Thanks, that solved the issue
