### ISSUE TITLE
Calendar: component emit different format on load then after change

### ISSUE THREAD

**Issue by Sp94dev** [primefaces/primeng#14484]
### Describe the bug

When we change dataType and dateFormat on the p-calendar element it does not reflect this value on the initial load.

### Environment

    "primeng": "17.3.1",
    "@angular-devkit/build-angular": "^17.0.5",
    "@angular/animations": "^17.0.5",
    "@angular/cdk": "^17.0.2",
    "@angular/cli": "^17.0.5",
    "@angular/common": "^17.0.5",
    "@angular/compiler": "^17.0.5",
    "@angular/compiler-cli": "^17.0.5",
    "@angular/core": "^17.0.5",
    "@angular/forms": "^17.0.5",
    "@angular/platform-browser": "^17.0.5",
    "@angular/platform-browser-dynamic": "^17.0.5",
    "@angular/platform-server": "^17.0.5",
    "@angular/router": "^17.0.5",
    "chart.js": "3.3.2",
    "primeflex": "^3.3.1",
    "primeicons": "^6.0.1",
    "quill": "1.3.7",
    "rxjs": "~7.8.1",
    "tslib": "^2.5.0",
    "zone.js": "~0.14.0"
 

### Reproducer

https://stackblitz.com/edit/gucrzb?file=src%2Fapp%2Fdemo%2Fcalendar-basic-demo.html,src%2Fapp%2Fdemo%2Fcalendar-basic-demo.ts

### Angular version

17.0.5

### PrimeNG version

17.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.10.0

### Browser(s)

All

### Steps to reproduce the behavior

1. Initialize the calendar with any date
2. add dateFormat="dd/mm/yy" and  dataType="string" in template
3. display the value of the control
4. The initial load value is in DateTime format
5. after the date format is changed to desired 

### Expected behavior

Apply format and type on initial load

**Comment by jayee** [comment]
This change emits model change initially, when nothing is changed in the model. The form is also set to dirty.

The code in my case
`<p-calendar [inputId]="name"
			[name]="name"
			[keepInvalid]="true"
			[dataType]="'string'"
			[disabled]="disabled"
			[maxDate]="maxDate"
			[(ngModel)]="datum"
			(ngModelChange)="changed()">
</p-calendar>
`
