### ISSUE TITLE
p-dropdown: FilterBy multiple values is not working

### ISSUE THREAD

**Issue by jalley3** [primefaces/primeng#14492]
### Describe the bug

This was previously working. However since upgrading to 17.2.0 the filterBy property seems to be ignored and the optionLabel field is the only one that gets searched.

Here is an image of the stackblitz that demonstrates the issue:
![image](https://github.com/primefaces/primeng/assets/17911817/2c052806-083b-47ea-8925-886f8d2e17e0)
![image](https://github.com/primefaces/primeng/assets/17911817/6b055943-22e7-42c2-8391-2ab93b1cbc56)

Note filterBy is set to filter by code and name but only name gets searched (and name is the value that is in the OptionLabel attribute).

Here is the dropdown code: 

```
<p-dropdown
    [options]="countries"
    [(ngModel)]="selectedCountry"
    optionLabel="name"
    [filter]="true"
    filterBy="name,code"
    [showClear]="true"
    placeholder="Select a Country"
  >
    <ng-template pTemplate="selectedItem">
      <div class="flex align-items-center gap-2" *ngIf="selectedCountry">
        <img
          src="https://primefaces.org/cdn/primeng/images/demo/flag/flag_placeholder.png"
          [class]="'flag flag-' + selectedCountry.code.toLowerCase()"
          style="width: 18px"
        />
        <div>{{ selectedCountry.name }}</div>
      </div>
    </ng-template>
    <ng-template let-country pTemplate="item">
      <div class="flex align-items-center gap-2">
        <div> {{country.code}} </div>
        <div>{{ country.name }}</div>
      </div>
    </ng-template>
  </p-dropdown>
```

Here is the link to the stackblitz: https://stackblitz.com/edit/1n452r?file=src%2Fapp%2Fdemo%2Fdropdown-filter-demo.html 

### Environment

Im using 17.2.0 but in the stackblitz above it is 17.3.1 and still the same issue.

### Reproducer

https://stackblitz.com/edit/1n452r?file=src%2Fapp%2Fdemo%2Fdropdown-filter-demo.html,package.json

### Angular version

17.0.7

### PrimeNG version

17.2.0

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

20.10

### Expected behavior

As per the API, and the way that the component previously functioned, the filterBy attribute should allow you to specify multiple values to filter the dropdown by

**Comment by jalley3** [comment]
Also just to provide a little more information, the order i put them in does not play a factor in the filtering, i think the property is being ignored all together because it is only ever the value that is the option label that gets searched.

**Comment by yassine-fy94** [comment]
add the filterFields on your html p-dropdown :
[filterFields] ="['name','code']"
