### ISSUE TITLE
Component: p-table - Cell edit capable table throws error when sorting

### ISSUE THREAD

**Issue by critchie** [primefaces/primeng#14494]
### Describe the bug

A table setup for cell editing throws "TypeError: Cannot read properties of undefined (reading 'firstChange')" when sorting. 

### Environment

StackBlitz

### Reproducer

https://stackblitz.com/edit/kzzhg6?file=src%2Fapp%2Fdemo%2Ftable-cell-edit-demo.html

### Angular version

17.0.5

### PrimeNG version

17.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

0.0.0

### Steps to reproduce the behavior

1. Visit StackBlitz link above
2. Open the Dev Tools of the browser
3. Sort a column on the grid.
Result: error is thrown

### Expected behavior

No errors should be thrown.

**Comment by JIBIN-P** [comment]
Thank you @critchie because of your example, I was able to find the pEditableColumnRowIndex property which was missing in the official documentation for the cell edit functionality otherwise index was showing up as undefined.
