### ISSUE TITLE
Cannot find name 'MenuItem' in primeng while using like private items: MenuItem[];

### ISSUE THREAD

**Issue by partha006** [primefaces/primeng#1449]
I was trying to implement the sample in the below url 

[http://www.primefaces.org/primeng/#/menubar](url)

but getting the error on the line  private items: MenuItem[]; as cannot find name 'MenuItem' even though i used import {MenuModule,MenuItem} from 'primeng/primeng'; in app.module.ts

**Comment by Mrtcndkn** [comment]
I checked it locally but it seems to be working fine.

**Comment by GZTiempo** [comment]
Hi, i have installed the primeng but i have the same issue shall i install it from another source?

**Comment by igogu** [comment]
You have to import MenuItem in the component where you are going to use it, you can't import it in app.module.ts because you can't include it in ngmodule imports

**Comment by ninebling** [comment]
Thx for @igogu . It works. I tried like this:

1. in 'app.module.ts' import MenuModule
2. and in 'app.component.ts' import MenuItem 

I think that the tutorial [http://www.primefaces.org/primeng/#/menubar](url) should be fix.

**Comment by sudheerj** [comment]
The showcase documentation import doesn't mean only for app module .It mentioned as what specific modules and classes need to be imported(for both component.ts,module.ts) to work with the component.
