### ISSUE TITLE
OverlayPanel: Accessibility documentation

### ISSUE THREAD

**Issue by puschie286** [primefaces/primeng#14493]
### Describe the bug

the [documentation](https://primeng.org/overlaypanel#accessibility) still says that the component add the aria attributes. as @cetincakiroglu [mentioned](https://github.com/primefaces/primeng/issues/14290#issuecomment-1854003450), its the developer reponsibility to add these attributes

### Environment

documentation

### Angular version

17

### PrimeNG version

17.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

0

**Comment by cetincakiroglu** [comment]
You can use ariaLabel and ariaLabelledBy input properties.
```
    /**
     * Defines a string that labels the input for accessibility.
     * @group Props
     */
    @Input() ariaLabel: string | undefined;
    /**
     * Establishes relationships between the component and label(s) where its value should be one or more element IDs.
     * @group Props
     */
    @Input() ariaLabelledBy: string | undefined;
```

**Comment by puschie286** [comment]
@cetincakiroglu can you please stop closing issues that are not complete...
the documentation still says : "OverlayPanel adds aria-expanded state attribute and aria-controls to the trigger so that the relation between the trigger and the popup is defined."
