### ISSUE TITLE
p-multiselect is not resetting when using with reactive form

### ISSUE THREAD

**Issue by Cretesh-Anuj** [primefaces/primeng#14490]
### Describe the bug

P-multiselect is not going back to its default label even after resetting it when using reactive form

### Environment

Latest Angular + PrimeNg, easily reproducible (see the StackBlitz link below)

Step 1 : 
![MicrosoftTeams-image](https://github.com/primefaces/primeng/assets/96906749/5c36ab42-988e-4a02-ac8c-9b241366789e)

Step 2: 

![23e4af63-b033-446c-bde5-37d63573016a](https://github.com/primefaces/primeng/assets/96906749/eabfbaa9-4c6c-4f5f-801e-b1527812a94b)

Step 3: 
The checkboxes are unchecked but label is still present with those values.

![7084ce1c-784a-46dc-9eff-d17de8b5f2c0](https://github.com/primefaces/primeng/assets/96906749/bae8758f-b509-4d89-a12d-f5c05f01f326)

### Reproducer

https://stackblitz.com/edit/swzu6g?file=src%2Fapp%2Fdemo%2Fmulti-select-template-demo.ts

### Angular version

17.0.8

### PrimeNG version

17.3.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.9.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Select values from multiselect dropdown
2. Click on reset button
3.  Checkbox is getting unchecked but it is not reflecting multiselect label (i.e. it is not going back to its default label or placeholder)

### Expected behavior

1. Select values from multiselect dropdown
2. Click on reset button
3. Checkbox should be unchecked and it should be back to default label or placeholder

**Comment by chetanbavare** [comment]
this.trcPatientEngagementForm.get('selectedCountries').setValue([]);
add this line inside ResetForm() function to set the selected countries array to null after clicking reset button

**Comment by Gnaneshwar9059** [comment]
Thanks for the suggestion, we do aware of this approach but the above issue is still concern right? And there are lot of places where we are using that and we can't set them manually everywhere.

**Comment by yassine-fy94** [comment]
add [showClear]="true" on your html p-multiSelect
