### ISSUE TITLE
p-listbox: max-height forced

### ISSUE THREAD

**Issue by mshnajar** [primefaces/primeng#14496]
### Describe the bug

In Listbox component, on class: .p-listbox-list-wrapper,  max-height: 200px; is applied
This forced the body of Listbox do have maximum height of 200px.
I had to use ::ng-deep & !important to override this problem

### Environment

Angular 16, PrimeNG 16

### Angular version

16.2..12

### PrimeNG version

16.9.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.10.0

### Browser(s)

Chrome, Opera

**Comment by cetincakiroglu** [comment]
Hi,

In listbox, scrollHeight input is set to 200px by default, you can use it by `<p-listbox scrollHeight="auto"/>`. You don't need to use `ng-deep` or CSS to override it.

**Comment by john8329** [comment]
What's the rationale behind this default?
Other components don't behave like this (e.g. tables)
