### ISSUE TITLE
Component: p-dataView v17.3

### ISSUE THREAD

**Issue by mcrightworks** [primefaces/primeng#14495]
### Describe the bug

After upgrading to v17. DataView no longer shows results.

### Environment

`"dependencies": {
    "@angular/animations": "^17.0.8",
    "@angular/common": "^17.0.8",
    "@angular/compiler": "^17.0.8",
    "@angular/core": "^17.0.8",
    "@angular/forms": "^17.0.8",
    "@angular/platform-browser": "^17.0.8",
    "@angular/platform-browser-dynamic": "^17.0.8",
    "@angular/router": "^17.0.8",
    "chart.js": "^4.4.1",
    "primeflex": "^3.3.1",
    "primeicons": "^6.0.1",
    "primeng": "^17.3.0",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.2"
  },`

### Angular version

17.0.8

### PrimeNG version

17.3.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20

### Steps to reproduce the behavior

Implement a Dataview with latest primeng and angular. No code changes.
Also the DOCS are not reflecting a stackblitz with the latest v17. They are all still v16.

**Comment by siddhareddy** [comment]
If you have upgraded from PrimeNG 16 to 17. 
There were breaking changes to **p-dataView** [17.0-rc1-breaking-changes](https://github.com/primefaces/primeng/blob/master/CHANGELOG.md#1700-rc1-2023-11-29) . 
You may need to change the **templates names and data params** as per the new docs
What's changed : [14214 - DataView | Remove primeflex dependency](https://github.com/primefaces/primeng/issues/14214)
I think the demo are working as expected stackblitz - [dataview-demo-primeng-17.3.1](https://stackblitz.com/edit/u9x5ek?file=package.json)
