### ISSUE TITLE
Calendar: Calendar Icon has a default cursor on hover

### ISSUE THREAD

**Issue by navedqb** [primefaces/primeng#14501]
### Describe the bug

Calendar Icon has a default cursor on hover

https://primeng.org/calendar#icon

### Environment

.

### Reproducer

https://primeng.org/calendar#icon

### Angular version

17

### PrimeNG version

17.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

.

### Steps to reproduce the behavior

1. Go to https://primeng.org/calendar#icon
2. Hover over the calendar icon 
3. Icon has a default cursor

**Comment by mertsincan** [comment]
Thanks a lot for your report and PR! We'll discuss it with our design team.

**Comment by navedqb** [comment]
Sure, thanks!

**Comment by onursenture** [comment]
Having only the cursor: pointer is not sufficient. The input should also remain in the hover state. Looking at it from a behavior standpoint, because the date picker opens when we click on the icon, it should both have the cursor:pointer and remain in the input hover state.

**Comment by onursenture** [comment]
We discussed with the team again; another solution is to give icon pointer-events: none, which will prevent confusion.
