### ISSUE TITLE
Table: Using source as signal/observable that comes from NgRx selector throws error when trying to sort column

### ISSUE THREAD

**Issue by codrut1** [primefaces/primeng#14514]
### Describe the bug

When using NgRx and selecting with either `this.store.select(selector)` or `this.store.selectSignal(selector)`, the sorting feature will not work and throw the following error in the console:
![image](https://github.com/primefaces/primeng/assets/75161694/919aafaa-f48b-4a8a-9f7a-9c31dcd3b538)
This error also occurs when using an Observable and adding the data source with the async pipe: `<p-table [value]="(items | async)!">`

Note that this issue does not happen if the signal is defined directly in `app.component.ts`.
Also noticed that when hovering the type of the data in `<p-table [value]="items()">`, it is `() => dataType[]` instead of `dataType[]`

### Environment

{
    "@angular/animations": "^17.0.0",
    "@angular/common": "^17.0.0",
    "@angular/compiler": "^17.0.0",
    "@angular/core": "^17.0.0",
    "@angular/forms": "^17.0.0",
    "@angular/platform-browser": "^17.0.0",
    "@angular/platform-browser-dynamic": "^17.0.0",
    "@angular/router": "^17.0.0",
    "@ngrx/store": "^17.0.1",
    "primeng": "^17.3.1",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.2"
  }

### Reproducer

https://codesandbox.io/p/devbox/frosty-smoke-fttpws?file=%2Fdemo%2Fsrc%2Fapp%2Fapp.config.ts%3A16%2C3&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr61dt4n0006356kounoavuo%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr61dt4n0002356kqv6vhlez%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr61dt4n0004356k9ptfq5xt%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr61dt4n0005356kzzz62mg1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B55.90151369994251%252C44.09848630005749%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr61dt4n0002356kqv6vhlez%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr61dt4n0001356kqljap94i%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clr635wx00002356jhjj2eog5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A16%252C%2522startColumn%2522%253A3%252C%2522endLineNumber%2522%253A16%252C%2522endColumn%2522%253A3%257D%255D%252C%2522filepath%2522%253A%2522%252Fdemo%252Fsrc%252Fapp%252Fapp.config.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clr61dt4n0002356kqv6vhlez%2522%252C%2522activeTabId%2522%253A%2522clr635wx00002356jhjj2eog5%2522%257D%252C%2522clr61dt4n0005356kzzz62mg1%2522%253A%257B%2522id%2522%253A%2522clr61dt4n0005356kzzz62mg1%2522%252C%2522activeTabId%2522%253A%2522clr635y2g002b356jtxwge4lg%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A4200%252C%2522id%2522%253A%2522clr635y2g002b356jtxwge4lg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clr61dt4n0004356k9ptfq5xt%2522%253A%257B%2522id%2522%253A%2522clr61dt4n0004356k9ptfq5xt%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr61ehx4002n356k1byp207q%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clr61ehy402f0eeg6bqivexl6%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clr61ehx4002n356k1byp207q%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Angular version

17.0.0

### PrimeNG version

17.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Browser(s)

-

### Steps to reproduce the behavior

1. Use NgRx in the app and have a simple reducer or selector.
2. Inject the store and call the selector `items = this.store.selectSignal(selectItems);`
3. Add the data source in the template: `<p-table [value]="items()">`
4. Enable sorting and try to sort

### Expected behavior

Sorting should work and no error should occur

**Comment by Cr3aHal0** [comment]
This is not an issue about PrimeNG but rather your Typescript environment. Since `Array.sort` directly alter the given array rather than producing a new one (depends on the output version of Javascript IIRC) and since the store data is immutable outside of reducers & pipelines provided by NGRX itself, you have to explicitly provide a copy of the array stored in your store before performing such operation, e.g. introducing a selector with perform a spread of current array content.

**Comment by codrut1** [comment]
@Cr3aHal0 you are right, that is the issue! Thanks very much
