### ISSUE TITLE
p-dropdown: optionValue is not working when object has property 'group'

### ISSUE THREAD

**Issue by kiknadze** [primefaces/primeng#14516]
### Describe the bug

I performed a version migration from PrimeNG 14 to 16.9.1, and immediately the dropdowns that receive an object but have their value and label specified stopped working. The options are not displayed in the HTML. 

As I investigated problem is 'group' property of object. If group is undefined it works properly, but if group has any value then it shows empty list.

```
<p-dropdown
      [options]="templates"
      inputId="templateId"
      placeholder="Select Template"
      optionLabel="name"
      optionValue="id"
      formControlName="templateId">
</p-dropdown>
```
![12](https://github.com/primefaces/primeng/assets/9992978/1f83d75c-3305-4c39-ab02-13a5d88b1bab)

![295270663-2769ac3b-df07-4e52-b57b-a424c3be778b](https://github.com/primefaces/primeng/assets/9992978/d713d962-9c7c-4507-bbe6-b15af794c072)

![image](https://github.com/primefaces/primeng/assets/9992978/62645734-ce9b-4e7b-ad9f-3a01b5551df6)

### Environment

"@angular/animations": "^16.2.12",
"@angular/cdk": "^16.2.12",
"@angular/common": "^16.2.12",
"@angular/compiler": "^16.2.12",
"@angular/core": "^16.2.12",
"@angular/forms": "^16.2.12",
"@angular/platform-browser": "^16.2.12",
"@angular/platform-browser-dynamic": "^16.2.12",
"@angular/router": "^16.2.12",
"@angular/service-worker": "^16.2.12",
"ngx-bootstrap": "^11.0.2",
"bootstrap": "^5.2.0",
"font-awesome": "^4.7.0",
"@fortawesome/angular-fontawesome": "^0.13.0",
"@fortawesome/fontawesome-svg-core": "^1.2.36",
"@fortawesome/free-regular-svg-icons": "^5.15.1",
"@fortawesome/free-solid-svg-icons": "^5.15.4",
"primeicons": "^5.0.0",
"primeng": "^16.9.1",
"rxjs": "~6.6.3",
"zone.js": "^0.13.3"

### Angular version

16.2

### PrimeNG version

16.9.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.1

### Browser(s)

Chrome

**Comment by mertsincan** [comment]
Thanks a lot for your report! Could you please attach a stackblitz link for us to replicate? I added a milestone. If you attach a link, we'll fix it before the milestone is released.

**Comment by kiknadze** [comment]
> stackblitz

https://stackblitz.com/edit/lfryhg?file=src%2Fapp%2Fdemo%2Fdropdown-basic-demo.ts

**Comment by tsinevik** [comment]
Hi, this is because dropdown has incorrect logic for choosing a template for option. It renders group template if option object has group property.
I have a PR opened (#14382) with fix for this issue for quite some time already. Would really appreciate if you push a fix for it as quick as possible.
