### ISSUE TITLE
Mouse icon: No change possible on disabled state

### ISSUE THREAD

**Issue by msg-ptavoul** [primefaces/primeng#14522]
### Describe the bug

**Old Bug:**
https://github.com/primefaces/primeng/issues/1385

The need to use a different mouseicon for the "disabled" state in german and also in european-government applications is mandatory. Via EU Laws the different States are forced to implement the rules of accessibility. For this example the Rules "1.4.1 Use of Color" and "1.4.11 Non-text contrast" of the WCAG 2.1 come to frution. The Rules are also implemented in the DIN EN 301549 v3.1.1.

This means the colorchange as primary and only option to differ is not sufficient. A button needs the option with other characteristics (like the mousicon) to show a different state (in this case: disabled).

The Change would further enable PrimeNGs as a suitable framework for the public sector.

### Environment

Windows 11

### Angular version

17.0.8

### PrimeNG version

17.3.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.9.0

### Browser(s)

Chrome 119.0.6045.200

**Comment by mertsincan** [comment]
Hi,

We wrap .p-disabled class with @layer primeng to customize easily. Please try the following css;
```
.p-disabled, .p-disabled * {
    cursor: ...
    pointer-events: auto;
}
```
Best Regards,

**Comment by mervetagci** [comment]
Merhabalar.
Verdiğiniz kodu kullanmak istediğim componentimin css dosyasında deniyorum ama cursor stilinde herhangi bir değişiklik olmadı. Bu normal mi?
kullandığım .css dosyası:
![image](https://github.com/primefaces/primeng/assets/66209345/bb999f4c-3b7f-4b34-87c6-0902d381f1d2)
meta.dropdown içeriği:
![image](https://github.com/primefaces/primeng/assets/66209345/93f63e59-b47f-4028-9b8f-7805790e6b46)

**Comment by mervetagci** [comment]
Buradaki sorunumu (encapsulation: ViewEncapsulation.None,) ve class ekleyerek ile çözdüm. Class ve id lere bakarak css dosyasında kullanmak istediğim stilleri kullanabildim.
![image](https://github.com/primefaces/primeng/assets/66209345/c8bb7016-da5e-4b2f-8ead-1c0258d1184f)
