### ISSUE TITLE
Google Gboard and inputmask control

### ISSUE THREAD

**Issue by cfs-spivey** [primefaces/primeng#14529]
### Describe the bug

On a pixel device; the device uses GBoard and issue occurs if you type like 01/01/1980 and then delete 01/01/yyyy, the cursor moves before the forward slash and when you types it messes up the year typed 01/01/9801. This happens with any mask that has seperators in it.

### Environment

Any mobile device with Gboard keyboard.

### Angular version

15.2.4

### PrimeNG version

17.3.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.13.1

### Steps to reproduce the behavior

1. Use a Pixel phone or install Gboard on Samsung phone.
2. Go to a site like https://primeng.org/inputmask.
3. Type into one of the masked fields.
4. Delete characters to the masked separator.
5. The cursor will move in front of the separator.
6. Type and now the characters will be out of position.

### Expected behavior

Cursor should move after the masked separator, this will allow the correct characters to be typed.

**Comment by mertsincan** [comment]
Thanks a lot for your report! We'll check it but, I appreciate it if you support us with a PR.
