### ISSUE TITLE
TreeTable: Selection of a node results in the selection of another node under a different parent if data is the same

### ISSUE THREAD

**Issue by mconner** [primefaces/primeng#14536]
### Describe the bug

When if two nodes have the same data values (but are not the same instance), and one of them is selected, then the the other node will also be selected.

### Environment

Windows 10, but duplicated in stackblitz

### Reproducer

https://stackblitz.com/edit/f13fae?file=src%2Fapp%2Fdemo%2Ftree-table-selection-checkbox-demo.html

### Angular version

17.0.8

### PrimeNG version

17.3.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.10.0

### Browser(s)

  Microsoft Edge for Business Version 120.0.2210.121 (Official build) (64-bit)

### Steps to reproduce the behavior

The reproducer is a clone of the Checkbox Selection example: https://primeng.org/treetable#checkbox, however, I got similar results with the multiselect example.  I duplicated the Angular data as Angular2 in NodeService.getFileSystemNodesData(), and changed the size of the cli.app child node.

1. Start the reproducer.  Note the instructions at the top that essentially will be duplicated here.  
2. Expand the "Applications" Node, and then both the "Angular" and "Angular2" child nodes.
3. Select the "Angular" node (click the checkbox).  You should see something like the following: 
![image](https://github.com/primefaces/primeng/assets/540402/60b820b9-bbbb-453a-ad3b-ef7b2db7267a)

Note that while node "Angular2" was never selected, some of its children were, in addition to those of "Angular".  It appears that this is because the children's data are equivalent.  The "cli.app" in "Angular2" was _not_ selected because I modified its attributes to not match those of "cli.app" under "Angular".

I thought that including rowTrackBy might fix the problem.  The documentation for rowTrackBy states:  
> Function to optimize the dom operations by delegating to ngForTrackBy, default algorithm checks for object identity.  

However, while the rowTrackBy function is getting called, it had no effect on the outcome of the select.

I also tried adding an explicit key attribute to the node.  It made no difference.

Possible Workaround: Adding a unique key to the data.  This is ugly,but should work.

This may be related to https://github.com/primefaces/primeng/issues/10228, which was closed in spite of the fact that the op indicated that the described solution had nothing to do with editing. But I couldn't run that reproducer to confirm.

### Expected behavior

When you select a node in the treetable, other nodes that are not children of that node should not be selected.

**Comment by mertsincan** [comment]
Hi @mconner,

I think you can use `dataKey` prop for it and set a unique key of nodes.

```
<TreeTable dataKey="id" ..../>

// each node need to contain unique `id` key. 
```

For now, closed. If the problem persists, please reopen this ticket.
Best Regards,

**Comment by mconner** [comment]
@mertsincan, 
While adding dataKey="id" and then adding unique keys works (and is presumably more performant than just adding the key, as I had suggested in the workaround), it is kludgy, as the data now requires the key, and the API uses TreeNode, which already _has_ a key attribute:  
    /**
     * Mandatory unique key of the node.
     */
    key?: string;

Why is that not used instead?

In any case, this should be better documented. The example in the doc only works because it didn't happen to have two nodes with the same data.
