### ISSUE TITLE
Dropdown: can't select input with Shift + Home / Shift + End

### ISSUE THREAD

**Issue by perceptron8** [primefaces/primeng#14540]
### Describe the bug

Shift + Home / Shift + End doesn't select text.

### Environment

https://stackblitz.com/

### Reproducer

https://github-qox9rx.stackblitz.io

### Angular version

17.0.9

### PrimeNG version

17.3.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

21.5.0

### Browser(s)

Google Chrome: 120.0.6099.199, Firefox: 121.0

### Steps to reproduce the behavior

1. Type anything
2. Press Shift + Home
3. Press Home
4. Press Shift + End
5. Press End

### Expected behavior

Text should become selected in steps 2 and 4.

**Comment by perceptron8** [comment]
Stackblitz url doesn't seem to work, so here's MCVE:

```html
<p-dropdown [filter]="true" [options]="['Australia', 'Brazil', 'China']">
  ```

**Comment by cetincakiroglu** [comment]
Hi,

Selection by specifically `shift + end` and `shift + home` keys are not supported.  `shift + end` and `shift + home` are navigate to either first or last element in the dropdown. Set `selectOnFocus` to `true` to enable selection by focusing on an option.

Here is a stackblitz example: https://stackblitz.com/edit/dbpmhs?file=src%2Fapp%2Fdemo%2Fdropdown-basic-demo.html

**Comment by perceptron8** [comment]
@cetincakiroglu In stackblitz example you gave:
1. there is no [filter]="true", thus no text input
2. shift is unnecessary to navigate, first/last item is can be selected with home/end only (is this another bug?)

> Selection by specifically shift + end and shift + home keys are not supported.

What kind of selection did you have in mind?

**Comment by cetincakiroglu** [comment]
My bad, I missed the explanation, I got you know, I'll check it again. Thanks for letting me know 👍🏻

**Comment by perceptron8** [comment]
Please also note, that this is a regression. Text selection (and I mean text input which is used for filtering) was working properly on [v15](https://www.primefaces.org/primeng-v15-lts/dropdown#filter), but stopped working on [v16](https://www.primefaces.org/primeng-v16-lts/dropdown#filter).

**Comment by perceptron8** [comment]
Thanks!
