### ISSUE TITLE
Component: Dropdown - value that is not in the options is not displayed in the edit box after restart

### ISSUE THREAD

**Issue by ppieczul** [primefaces/primeng#14549]
### Describe the bug

The value entered in the editable field, if it is not among the selectable options, it is not displayed in the edit box when component is reinitialised. Also, if the dropdown is not editable, and the value is not among the options, it is not displayed. I am not sure if it should display that value, I think it should at least in case of editable dropdown. It may be a matter of initialising the editable box value to the current value.

### Environment

Electron app

### Angular version

17.0.8

### PrimeNG version

17.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

21.5.0

### Browser(s)

Chrone

### Steps to reproduce the behavior

Create a dialog with a dropdown with some options A, B, C and make it editable
Enter something D that is not A, B, C in the dropdown edit box, store the value and close dialog
Open the dialog - the D is displayed in the edit box
Reload the application and open the dialog - the edit box is empty, but value D is set in the runtime properly

### Expected behavior

Value not in the options list should be displayed in the edit box and allow to be edited

**Comment by mertsincan** [comment]
Hi,

Unfortunately, I couldn't replicate it. Could you please attach a stackblitz link for us to replicate? Thanks a lot!

**Comment by cetincakiroglu** [comment]
Hi,

Your example does not start you can fork this example to create a new one https://stackblitz.com/edit/hqi4ek?file=package.json

**Comment by ppieczul** [comment]
Here it is: https://stackblitz.com/edit/hqi4ek-aqswqg

**Comment by cetincakiroglu** [comment]
Hi,

Thanks for the example, it seems that the issue has been fixed in v17.4.0 https://stackblitz.com/edit/hqi4ek-yzaslk?file=src%2Fapp%2Fdemo%2Fdropdown-basic-demo.ts,src%2Fapp%2Fdemo%2Fdropdown-basic-demo.html,package.json

Closing the issue since it doesn't exist in v17.4.0, thanks a lot for reporting the issue!
