### ISSUE TITLE
p-calendar: validation is triggered before calendar is even touched

### ISSUE THREAD

**Issue by martinkasa** [primefaces/primeng#14542]
### Describe the bug

When required="true" and dataType="string", calendar component changes property bound by ngModel and incorrectly set it to null probably. Consequence is also that control is marked as dirty and therefore if it is required, it is immediately highlighted with red as invalid.

Check stackblitz example: https://stackblitz.com/edit/tkapjd?file=src%2Fapp%2Fdemo%2Fcalendar-reactive-forms-demo.ts

![image](https://github.com/primefaces/primeng/assets/32707615/b685c667-d0a5-4ba5-b848-b1a38791fb6c)

### Environment

angular 17 app on Windows

### Reproducer

https://stackblitz.com/edit/tkapjd?file=src%2Fapp%2Fdemo%2Fcalendar-reactive-forms-demo.ts

### Angular version

17

### PrimeNG version

17.3.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Browser(s)

all

**Comment by mertsincan** [comment]
Thanks a lot for your report! I added a milestone for it. We'll check it before the milestone is released. Thanks a lot for your understanding!
