### ISSUE TITLE
Make the calendar Saturday and Sunday different colors

### ISSUE THREAD

**Issue by mikosu3** [primefaces/primeng#1455]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

I want the option to change the color on Saturday and Sunday in the calendar.
Pull request #1392 

![calendar](https://cloud.githubusercontent.com/assets/11406992/20740711/b230d040-b708-11e6-98d0-cdffb6ce76fa.jpg)

**Comment by upmauro** [comment]
Nice feature! 
+1

**Comment by mikosu3** [comment]
Yes. I want this feature in my project.
it marge to master when i happy
