### ISSUE TITLE
TreeTable: StyleClass wont apply

### ISSUE THREAD

**Issue by mb-19** [primefaces/primeng#14559]
### Describe the bug

When adding a StyleClass to a TreeNode in TreeTable it wont apply. For Example adding styleclass opacity-30 to a TreeNode wont change the Opacitity. It works fine in other components like Tree.

### Environment

Node20  Primeng 17+ Angular 17

### Reproducer

https://stackblitz.com/edit/4kpoo7-yrnqvw?file=src%2Fapp%2Fdemo%2Ftree-table-basic-demo.ts

### Angular version

17

### PrimeNG version

17

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20

### Browser(s)

chrome

**Comment by mertsincan** [comment]
Thanks a lot for your report! I set a milestone and we'll check it before the milestone is released. Also, could you please update title of this ticket? Thanks!
