### ISSUE TITLE
Component: Chips. Duplicate validation is case sensitive 

### ISSUE THREAD

**Issue by AndrewAKovalenko** [primefaces/primeng#14550]
### Describe the bug

Currently, chip validation in `p-chips` component is case sensitive, it means that `test@test.com` and `Test@test.com` (or `test` and `Test`) are considered different values and don't treated as duplication. 

### Environment

Chrome

### Angular version

17.0.2

### PrimeNG version

17.3.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.10.0

### Steps to reproduce the behavior

1. Go to `Chips`
2. Set `[allowDuplicate]=false`
3. Type `test` and hit `Enter`
4. Type `Test` and hit `Enter`
5. Observe result

### Expected behavior

Component should only have `test` value. 
`Test` should be filtered out

**Comment by AndrewAKovalenko** [comment]
Created pull requets to fix this issue https://github.com/primefaces/primeng/pull/14551

**Comment by mertsincan** [comment]
Thanks a lot for the PR! Please see my comment.
