### ISSUE TITLE
MultiSelect: selectedItemsLabel is not localized

### ISSUE THREAD

**Issue by puschie286** [primefaces/primeng#14554]
### Describe the bug

selectedItemsLabel is not localized, but there is a translation entry for that: "selectionMessage"

Workaround: set selectedItemsLabel  to  inject( PrimeNGConfig ).getTranslation( 'selectionMessage' )

### Environment

documentation

### Angular version

17

### PrimeNG version

17.3.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

-

### Steps to reproduce the behavior

1. Use different translation
2. Use MultiSelect with multiple items selected so that selectedItemsLabel is shown
3. See selectedItemsLabel has not the selectionMessage translation value

### Expected behavior

selectedItemsLabel should be default to "selectionMessage" translation

**Comment by mertsincan** [comment]
Thanks a lot for your report! I set a milestone and we'll check this issue before the milestone is released. Also, I really appreciate it if you support us with a PR.

Best Regards,

**Comment by cetincakiroglu** [comment]
Hi @puschie286 ,

Thanks a lot for the report, we've just updated the selectedItemsLabel, could you please check it after the release and let us know if the issue persists?

**Comment by antoinesully** [comment]
Hi @cetincakiroglu ! 

I have the same issue.
I updated to **primeng 17.4.0**.

I put this in the translation config (_config.setTranslation({_) : 
![image](https://github.com/primefaces/primeng/assets/157026186/003f3610-287a-4633-ae52-02132c4a9fc3)

Empty message is working as espected:  
![image](https://github.com/primefaces/primeng/assets/157026186/2eed5cd2-bd78-4124-ab76-531d9d3238ff)

But the "selectionMessage" isn't working ... 
![image](https://github.com/primefaces/primeng/assets/157026186/030d1605-6a1c-406f-b3a4-0337dc428694)

Best regards,

**Comment by matusko89** [comment]
still persist, the fix #14712 would work, it needs to be released though :)

**Comment by antoinesully** [comment]
Hi ! 
It works perfectly ! 
Thank you :)
