### ISSUE TITLE
Component: p-dropdown autoDisplayFirst not marked as deprecated in the web-documentation  

### ISSUE THREAD

**Issue by PauloKoglin** [primefaces/primeng#14553]
### Describe the bug

It isn't really a bug, I just noticed that the property [autoDisplayFirst](https://primeng.org/dropdown#api.dropdown.props.autoDisplayFirst) from `p-dropdown` is now deprecated, but the documentation hasn't been updated in the PrimeNG website.

### Environment

Current PrimeNG web-documentation -> https://primeng.org/dropdown

### Angular version

17.3.1

### PrimeNG version

17.3.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.10.0

### Steps to reproduce the behavior

Just take a look at the https://primeng.org/dropdown#api.dropdown.props.autoDisplayFirst

### Expected behavior

Be marked as deprecated.

**Comment by mertsincan** [comment]
Thanks a lot for your report! We'll update doc.
