### ISSUE TITLE
ConfirmPopup arror right side rendering defect

### ISSUE THREAD

**Issue by DarienF** [primefaces/primeng#14557]
### Describe the bug

Try to render ConfirmPopup on something located on right side of the panel or screen. Arror should be set on right side of the popup.
...and here what does it look like on my project:
![1](https://github.com/primefaces/primeng/assets/8654375/09893870-397f-4962-b220-8ed268eecf99)
...and here on reproducer:
![2](https://github.com/primefaces/primeng/assets/8654375/5d3df3ba-60a3-4265-97ab-9910a0ce1755)

### Environment

"primeflex": "^3.3.1",
"primeicons": "^6.0.1",
"primeng": "^17.0.0-rc.1",

### Reproducer

https://stackblitz.com/edit/github-ntfeae?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.module.ts

### Angular version

17.0.0

### PrimeNG version

17.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.10.0

**Comment by mertsincan** [comment]
Thanks a lot for your report! I set a milestone. We'll fix it before the milestone is released.

**Comment by DarienF** [comment]
I figure that out already. In some cases usage of 'event.currentTarget' solve the problem. Any way, get valid target HTML DOM element from 'event' is solution. 
I thought about the future upgrade...nice to set popup position left/right from target HTML DOM element.

**Comment by DarienF** [comment]
Solution with usage ViewChild interesting. Allow to trigger popup from button but set popup on another target HTML DOM element. Thanks)
