### ISSUE TITLE
p-calendar: Doesn't close on date selection in range mode

### ISSUE THREAD

**Issue by lm-swaroop** [primefaces/primeng#14558]
### Describe the bug

```hideOnDateTimeSelect``` doesn't work when ```selectionMode="range"```

### Environment

Chrome Version 120.0.6099.109
Ubuntu 22.04

### Reproducer

https://stackblitz.com/edit/cte5uw?file=src%2Fapp%2Fdemo%2Fcalendar-range-demo.html

### Angular version

17.0.0

### PrimeNG version

17.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.10.0

### Browser(s)

Chrome 120

### Steps to reproduce the behavior

1. Select start date 
2. Select end date

### Expected behavior

Datepicker overlay should close

**Comment by mertsincan** [comment]
Thanks a lot for your report! We'll check and get back to you.

**Comment by amonsour** [comment]
Sorry to open this back up, but now the `hideOnDateTimeSelect` does not do anything if range is selected.
Should have `&& this.hideOnDateTimeSelect` at the end for those who want the Calendar to stay open:

[https://github.com/primefaces/primeng/blob/27065cf3ae41af49874b205be096edaa489d9522/src/app/components/calendar/calendar.ts#L1495](https://github.com/primefaces/primeng/blob/27065cf3ae41af49874b205be096edaa489d9522/src/app/components/calendar/calendar.ts#L1495
)

**Comment by Xylios13** [comment]
Due to this change, as @amonsour mentioned, the property `hideOnDateTimeSelect` is no longer respected when in `range` selection mode.

Please take a look at this :)

**Comment by cetincakiroglu** [comment]
This issue is closed by a typo of another PR comment. Re-opening the issue
