### ISSUE TITLE
Component: pCalendar: Date becomes empty string if dataType="string is specified

### ISSUE THREAD

**Issue by fraras** [primefaces/primeng#14574]
### Describe the bug

When changing a date inside a table with the `p-calendar` component, if the `dataType="string"` is specified the `[(ngModel)]` of the component returns an empty string instead of the date.

### Environment

Angular

### Reproducer

https://stackblitz.com/edit/github-y9uamu-cbuqcz?file=src%2Fapp%2Fapp.component.html

### Angular version

17.0.7

### PrimeNG version

17.3.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.17.0

### Browser(s)

Chrome 120.0.6099.217

### Steps to reproduce the behavior

1. Build a `p-table`
2. Add a `p-calendar` component into an editable field of the table
3. Add the property `dataType="string"`
4. Define the dates in the model as string
5. Click on the date to open the Calendar

### Expected behavior

The dates in the Date (Data Type String) column should be maintained in the calendar input box when clicked.

**Comment by bhardwajsuresh** [comment]
Same issue with everyone with v17.4.0 as well. This should be fixed asap

**Comment by fbobbio** [comment]
Any news here?

**Comment by fbobbio** [comment]
> Any news here?

Apparently solved.
Upgraded `primeng` to `17.17.0` and `"@ngx-formly/primeng": "^6.2.2"`

My angular version `17.0.6`

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
