### ISSUE TITLE
Table, pFrozenColumn: Frozen columns are extremely slow and kick off many change detection cycles

### ISSUE THREAD

**Issue by natebundy** [primefaces/primeng#14579]
### Describe the bug

The pFrozenColumn directive is kicking off an extra change detection cycle for every table cell that contains the directive. For example, with a table with 90 rows that each have a td as part of a frozen column, 90 extra change detection cycles happen. For a table with 2 frozen columns with 90 rows, 180 extra change detection cycles happen.

(The directive also kicks off unnecessary cycles when using pFrozenColumn with a false frozen input for dynamic frozen columns since [setTimeout is being called either way](https://github.com/primefaces/primeng/blob/99b6e8fe53344d0fd5aa582a5fc16d05061609cf/src/app/components/table/table.ts#L3287))

In addition to the high number of change detection cycles, the frozen column code in [updateStickyPosition](https://github.com/primefaces/primeng/blob/99b6e8fe53344d0fd5aa582a5fc16d05061609cf/src/app/components/table/table.ts#L3295) is blocking the main thread and causing layout thrashing, which is freezing the UI for several seconds (and for one of our power users with a huge amount of data, over a minute!) with decently sized tables. This happens when we initially draw the table, when clearing a search, or doing any operation that causes frozen columns to be redrawn. For virtual scrolling up in large tables with a frozen column with all of the data loaded (especially when showing an additional frozen column, such as checkboxes for multiple selection), this causes several seconds of the browser thrashing with a blank table before finally being able to draw the table again. Setting the styles this way is potentially causing the browser to reperform layout for every single cell in a frozen column every time that table cell is initialized.

### Environment

Slowness with table began when upgrading PrimeNG from 14 to 16. Nothing special about our environment.

### Reproducer

https://stackblitz.com/edit/github-ddsd3p

### Angular version

17.0.8

### PrimeNG version

17.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.2

### Steps to reproduce the behavior
Using the provided StackBlitz:

1. Notice change detection cycles caused by loading a table with frozen columns
2. Clicking "redraw table" will start change detection count at 0 and reload the table data. Notice how many cycles it takes to reload the table
3. Search for something (e.g. "James") then notice how many change detection cycles happen when clearing out the search

4. Click toggle table type and switch to the table without frozen columns, then repeat steps 1-3 and notice how many fewer change detection cycles happen

5. Try searching while the change detection cycles are counting up on the table with frozen columns and notice that the search cannot respond until the change detection cycles are finished
6. Notice how choppy scrolling is while the change detection cycles are firing

### Expected behavior

Ideally, frozen columns should be implemented in a way that kicks off no more than 1 extra change detection cycle per column (or even 0 or 1 **total** extra cycles), no extra cycles for dynamically frozen columns with a false input, and should only set styles once per column instead of once per cell. (Frozen columns will still have to be recalculated where column sizes may change - e.g. when virtual scroll brings in new items or when filtering table data - since automatic table sizing may change column sizes in such cases, but those should follow the same rules. Perhaps a ResizeObserver could handle such cases?) After upgrading from PrimeNG 14 to 16 and then 17, we've had to implement our own frozen columns in the meantime because the table performance with frozen columns has gotten so much worse.

**Comment by cetincakiroglu** [comment]
Hi,

Thanks for reporting the issue, could you please try and give us feedback with the v17.10.0 after this week's release?

**Comment by cetincakiroglu** [comment]
@natebundy 

Thanks for the feedback, I've tested with your example in my local. Running outside of the zone removed unnecessary change detection calls. Could you please test it after the release and tag me if anything is wrong?

**Comment by intracloud** [comment]
me too.
i have p-table with 7 frozen columns and 400 rows.
It's extremely slow, even Chrome shows message to close the window
Thanks.

**Comment by AgusEDSA** [comment]
We have the same issue, a table with 12 columns, 2 frozen, on 500+ rows it starts freezing the browser.

**Comment by natebundy** [comment]
@intracloud @AgusEDSA when you both get a chance, try 17.10. It does seem like a marked improvement for frozen column performance for my app. Initially rendering large tables with frozen columns can still take a second or two, but once they're rendered they're much more responsive. However, we're usually maxing out at 2-3 frozen columns, so it'll be interesting to hear if this is still the case with 7.

If you immediately click and hold the down arrow on the vertical scrollbar after the table with frozen columns loads (or after pressing "Redraw table"), you can see a huge difference between these two:
[17.3.2](https://stackblitz.com/edit/github-ddsd3p)
[17.10.0](https://stackblitz.com/edit/github-xjhahs)

17.3.2 will literally freeze to a halt on my machine while 17.10.0 keeps scrolling along.

**Comment by intracloud** [comment]
hi @natebundy 

The performance problem isn't when scrolling up to the bottom or right left.
The problem is that when the p-table loads the data, without pFrozenColumn it takes a few seconds, with pFrozenColumn 10 or 20 times longer.

This problem is the same when I have 3 or 4 pFrozenColumn columns, I have so many because there are columns that have p-buttons to execute actions on the record.

This performance problem does not exist in version 14.1.2, the data loading is fast, but the problem is that the pFrozenColumn columns do not work correctly with p-buttons or icons

Thanks.

**Comment by Xapuu** [comment]
After fighting the same issue with versions 16+ and  17.13, ended up with writing my own CSS instead of using the frozen mechanism.
[StackBlitz](https://stackblitz.com/edit/n4decm?file=src%2Fapp%2Fdemo%2Ftable-paginator-basic-demo.html&file=src%2Fapp%2Fdemo%2Ftable-paginator-basic-demo.html,src%2Fstyles.scss,package.json)

It works for me, hopefully it will help someone else that ends up in this thread.

**Comment by cuongbrilliantSE** [comment]
@Xapuu It works when there's only one frozen column."

**Comment by andromida** [comment]
Are you able to have more than 2 frozen columns working?
After 3 frozen columns, the table is messed up: check this [Stackblitz](https://stackblitz.com/edit/e9xfw5-1wx36w)

**Comment by philip-42** [comment]
Is it possible that this issue was fixed in version 17.10 and re-introduced in 17.15?

**Comment by shyallegro** [comment]
Hi @cetincakiroglu seems this issue is back, I'm on 17.18.9

**Comment by loicgasser** [comment]
so 17.14 is fine and 17.14.1 is broken

**Comment by loicgasser** [comment]
This could be the issue:
https://github.com/primefaces/primeng/pull/15302/files

**Comment by AbdulKShahid** [comment]
When setting [frozen] = true, the table slows down, with performance worsening as the number of rows increases. Please let know if there is an update on this issue. Thanks.

**Comment by phalla-doll** [comment]
Performance degrades with pFrozenColumn on version 17.18.9. It crashes browser tab if having many rows, columns in the table.

**Comment by lucabarletta** [comment]
Can we reopen this issue since it is pending again?

**Comment by anant0103** [comment]
It also occurred in v17.18.12. The browser crashes when handling 100 rows and more than 15 columns.

**Comment by ckantzer** [comment]
I'm seeing slowness with frozen columns with version v19.0.10.  Is this still an issue?

**Comment by ckantzer** [comment]
@natebundy I know this is an old post, but would you be able to share the custom frozen column code you added instead of using the PrimeNg directive?

**Comment by natebundy** [comment]
@ckantzer Hi. I can't give you the exact code, but I should at least be able to help point you in the right direction. There are several caveats. The project I did this on is still on 17.18.11 for primeng, so it may need adjustments to work on the latest. We re-used the p-frozen-column class because we had other styles targeting frozen columns that I didn't want to have to change if we were able to go back to using the built-in frozen columns. (Unstyled mode is really ideal for our use case, but it's not out yet, unfortunately.) 

Also, the way we did this only supports one frozen left and one frozen right column in addition to the frozen checkbox column for multiple selection. Supporting multiple frozen columns per side would need to be attached to resize observers in order to remain performant (ideally a _single_ observer per additional column and set the style on the entire column at once - the way PrimeNG was (is?) doing this by setting left or right on literally every cell in a frozen column one at a time is a non-starter) and would have to update the "left" or "right" positions dynamically for each column past the first one on each side. 

It's more brittle than I like, but the frozen column performance problem was wrecking us, so we needed a quick workaround.

```html
<!-- table templates -->
<ng-template pTemplate="header" let-columns>
            <tr #headerRow>
                <!-- Keeping the following for when PrimeNG fixes frozen column performance -->
                <!-- <th *ngIf="selectionMode === 'multiple'" pFrozenColumn [frozen]="true"> -->
                <th *ngIf="selectionMode === 'multiple'" class="radio-button-column p-frozen-column">
                    <p-tableHeaderCheckbox [hidden]="hideHeaderCheckbox"></p-tableHeaderCheckbox>
                </th>
                <!-- Keeping the following for when PrimeNG fixes frozen column performance -->
                <!-- <th #headerColumns *ngFor="let col of columns; let i = index; trackBy: byField" -->
                <!-- [pSortableColumn]="col.field" [alignFrozen]="col.alignFrozen" pFrozenColumn [frozen]="col.frozen" -->
                <th #headerColumns *ngFor="let col of columns; let i = index; trackBy: byField" 
                    [pSortableColumnDisabled]="col.disableSort"
                    [ngClass]="{'in-multi-select': selectionMode === 'multiple', 'p-frozen-column': col.frozen, 'frozen-left': col.frozen && col.alignFrozen !== 'right', 'frozen-right': col.frozen && col.alignFrozen === 'right'}">
                    <span>
                        <ng-container *ngTemplateOutlet="col.headerTemplate"></ng-container>
                        <ng-container *ngIf="!col.headerTemplate">{{ col.header }}</ng-container>&nbsp;<p-sortIcon *ngIf="!col.disableSort" [field]="col.field"></p-sortIcon>
                    </span>
                </th>
            </tr>
</ng-template>

<ng-template pTemplate="body" let-dataItem let-columns="columns" let-rowIndex="rowIndex"
            let-expanded="expanded">
                <tr [ngClass]="{'in-multi-select': selectionMode === 'multiple'}" class="app-table-row" [ngStyle]="{ 'height':rowHeight}"
                    [pSelectableRow]="dataItem">
                    <!-- Keeping the following for when PrimeNG fixes frozen column performance -->
                    <!-- <td *ngIf="selectionMode === 'multiple'" class="radio-button-column in-multi-select" pFrozenColumn [frozen]="true"> -->
                    <td *ngIf="selectionMode === 'multiple'" class="radio-button-column in-multi-select p-frozen-column">
                        <p-tableCheckbox *ngIf="!isRowDisabled" [value]="dataItem" (click)="$event.stopPropagation()" [disabled]="isRowDisabled"></p-tableCheckbox>
                    </td>
                    <ng-container *ngFor="let col of columns; let i = index; trackBy: byField">
                        <!-- Keeping the following for when PrimeNG fixes frozen column performance -->
                        <!-- [alignFrozen]="col.alignFrozen" pFrozenColumn [frozen]="col.frozen" -->
                        <td [ngClass]="{ 'in-multi-select': selectionMode === 'multiple', 'p-frozen-column': col.frozen, 'frozen-left': col.frozen && col.alignFrozen !== 'right', 'frozen-right': col.frozen && col.alignFrozen === 'right' }">
                            <div>
                                <ng-container  [ngTemplateOutlet]="col.template" [ngTemplateOutletContext]="dataItem | templateContext"></ng-container>
                                @if (!col.template) {
                                  {{ dataItem[col.field] }}
                                }
                            </div>
                        </td>
                    </ng-container>
                </tr>
</ng-template>
```

```scss
<!-- styles -->
<!-- if you aren't using the p-frozen-column class, you'll need to add position: sticky yourself -->
    // primeng frozen column slowness workaround. we can remove these styles if we get to switch back to using their built-in frozen columns
    ::ng-deep {
        td:not(.radio-button-column).p-frozen-column.frozen-left, th:not(.radio-button-column).p-frozen-column.frozen-left, td.radio-button-column, th.radio-button-column {
            left: 0;
        }
 
        td:not(.radio-button-column).p-frozen-column.frozen-right, th:not(.radio-button-column).p-frozen-column.frozen-right {
            right: 0;
        }
    }

    ::ng-deep td:not(.radio-button-column).in-multi-select.p-frozen-column.frozen-left, th:not(.radio-button-column).in-multi-select.p-frozen-column.frozen-left {
        left: 2.5rem !important;
    }
```

**Comment by Frekvens1** [comment]
@natebundy Thank you for sharing your code!

In my case, the issue was that `<th alignFrozen="right" pFrozenColumn></th>` wasn’t positioned as the final column, which caused it to misalign and leave part of the table visible to the right. Applying your fix corrected that.

`"primeng": "^19.1.3"`

```html
<th class="p-frozen-column frozen-right"></th>
````

````scss
:host {
  .p-frozen-column, .p-frozen-row {
    background: var(--p-datatable-row-background);
    position: sticky;
    z-index: 1;
  }

  .p-frozen-row {
    top: 49px; /* Your table header height */
  }

  .p-frozen-column.frozen-left {
    left: 0;
  }

  .p-frozen-column.frozen-right {
    right: -1%; /* Fixes iPhone glitch */
  }
}
````
