### ISSUE TITLE
MultiSelect : Display Limit issue after upgrade

### ISSUE THREAD

**Issue by pjlasl** [primefaces/primeng#14577]
### Describe the bug

We recently upgraded from v15 to v16 and noticed that the multiselect is now capping items to 3 even though you select more.
We have not upgraded our PROD environment to v16 and the multiselect component is working as expected.

We are not using the "selectionLimit" property so it shouldn't limit the display.

The dropdown shows all of the selected options, but the chips cap at 3.

### Environment

This is what our multiselect code looks like...we made not changes moving from v15 to v16
<p-multiSelect
          *ngSwitchDefault
          [ngStyle]="{flex:1}"
          [options]="(branches | async)?? []"
          [(ngModel)]="criteria.branchList"
          defaultLabel="Select Branches..."
          display="chip"
          appendTo="body"
          filterMatchMode="startsWith"
          optionLabel="branch"
          [disabled]="(branches | async)?.length === 1"
        ></p-multiSelect>

### Angular version

16

### PrimeNG version

16

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.5.0

### Browser(s)

Google Chrome

**Comment by HeavyRainLQ** [comment]
Input property "maxSelectedLabels" is setted by default to 3. Try to set it to undefined or null if you don't want limit.
However this default value is missing in the doc and should be added. Now the doc is saying is set to null.
Hope it can help!

**Comment by pjlasl** [comment]
Perfect! I'll try it out.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
