### ISSUE TITLE
Component: Dropdown having disabled=false before group=true attribute breaks the behaviour

### ISSUE THREAD

**Issue by idealser** [primefaces/primeng#14587]
### Describe the bug

For some reason component is sensitive to attribute order and if you place [disabled] before [group] attribute the group functionality will become broken. I took base dropdown group sample and added disabled property before the group

Working:
```html
  <p-dropdown [options]="groupedCities" [(ngModel)]="selectedCity" placeholder="Select a City" 
 [group]="true" [disabled]="false">
```
Not working:
```html
  <p-dropdown [options]="groupedCities" [(ngModel)]="selectedCity" placeholder="Select a City" 
[disabled]="false" [group]="true">
```

### Environment

n/a

### Reproducer

https://stackblitz.com/edit/kdezbb?file=src%2Fapp%2Fdemo%2Fdropdown-group-demo.html

### Angular version

17.0.5

### PrimeNG version

17.3.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
