### ISSUE TITLE
If 'rows' input parameter is changed by the host, the list of page links in the paginator is not updated

### ISSUE THREAD

**Issue by zy-serguei** [primefaces/primeng#1458]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

http://plnkr.co/edit/U77F9RGsnKqD5cMzAgre

**Current behavior**

1. Initial state: 'rows' is 1, totalRecords is 10.
Observe the number of page links is 5, you can click a page, navigate to the next page or to the last page.
2. Change the value in the 'Rows' dropdown to 10.
Result: The list of page links is still 5, but can't navigate to any page.

**Expected behavior**

The list of page links must change to a single page

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.2.3

* **PrimeNG version:** 1.0.0

* **Browser:** all

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by yigitfindikli** [comment]
Unable to replicate with latest PrimeNG, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
