### ISSUE TITLE
Table filter set undefined

### ISSUE THREAD

**Issue by certifirm** [primefaces/primeng#14588]
### Describe the bug

I am using table component with this filter box:

```
 <th>
          <input pInputText style="width: 100%;"
            (input)="employeesList.filter($event.target['value'], column.field, 'contains')"
            [value]="employeesList.filters[column.field]?.['value']">
 </th>
```

Using PrimeNG 17.3.0 all works well.  With 17.3.1 and up, sets undefined in the inputbox when you write a character in it.

### Environment

Angular 17
Prime 17.3.3

### Angular version

17

### PrimeNG version

17.3.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v18.18.2

### Expected behavior

Work like in 17.3.0

**Comment by Da13Harris** [comment]
We are also encountering this bug in the latest release (17.4.0).

When typing anything into the <input> filter, the word "undefined" appears in the text box. This issue appears to have been introduced by #14433, which fixed #14432. Unfortunately, this is a breaking change in a minor release.

Here's an example snippet of our code that has this issue:

```html
<input
  id="network-name-filter"
  type="text"
  (input)="utilitiesService.tableFilter(tableRef, 'networkName', $event)"
  [value]="utilitiesService.castFilterAsMetadata(tableRef.filters['networkName'])?.value"
  placeholder="Filter Network Name"
/>
```

**Comment by mylifeandcode** [comment]
Having this issue as well.

**Comment by cetincakiroglu** [comment]
Hi @certifirm @Da13Harris,

Could you please provide a stackblitz example so we can identify and address the issue? I'm moving this to the next week's milestone until the reproducer arrives.

**Comment by cetincakiroglu** [comment]
Fixed in https://github.com/primefaces/primeng/pull/15053
