### ISSUE TITLE
p-table: "Date is after" filter does not exclude selected date

### ISSUE THREAD

**Issue by psarno** [primefaces/primeng#14589]
### Describe the bug

When using a <p-table> component with filtering, when selecting "Date After" and choosing a date, that date remains in the table, despite the fact it should only show dates _after_ that date.

This can be seen even in the PrimeNG documentation example.  In this case, "Date Is After" "09/12/2015" should not include that date in the result list, but it remains.

You have to select "Date is After" "09/13/2015" (the day after) if you actually want to exclude "09/12/2015".

![image](https://github.com/primefaces/primeng/assets/18640860/fc73b8b0-0a3f-432d-9aa2-918676e403ab)

![image](https://github.com/primefaces/primeng/assets/18640860/5e61842c-12e1-43d6-9feb-e81cf3cf2b28)

### Environment

PrimeNG 17.3.3
Angular 17.0.9

### Reproducer

Can be reproduced on PrimeNG's documentation page for Table

### Angular version

17.0.9

### PrimeNG version

17.3.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.0

### Steps to reproduce the behavior

1. Open the filter on any date column
2. Select "Date is After" as the filter type
3. Enter a date that is displayed in the grid
4. Click "Apply"

### Expected behavior

The date selected in the date field should **not be included** in the result set, as it is not "after" itself.

**Comment by nbrown-ScottLogic** [comment]
I think I have covered this bug in this PR: https://github.com/primefaces/primeng/pull/15343
