### ISSUE TITLE
Component: Chips. No ability to limit max length of chip

### ISSUE THREAD

**Issue by AndrewAKovalenko** [primefaces/primeng#14592]
### Describe the bug

As for now, there is no ability to limit max length of value, that will be inserted into chip.
Proposal is to add `maxLength` property, that will limit number of characters that can be typed.

It will use `input`'s native `maxlength` property
Benefit is improved UX and usage of standard HTML attributes

New `@Input` will be introduced, so no breaking changes

### Environment

Chrome

### Angular version

17.0.4

### PrimeNG version

17.3.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.10.0

### Browser(s)

Chrome 120

**Comment by AndrewAKovalenko** [comment]
implemented in https://github.com/primefaces/primeng/pull/14593

**Comment by christenbc** [comment]
The parameter maxLength has no effect whatsoever even though setting it. This does not work yet
