### ISSUE TITLE
p-autocomplete: maxlength doesn't work anymore

### ISSUE THREAD

**Issue by PauloKoglin** [primefaces/primeng#14595]
### Describe the bug

Our Team is still migrating the PrimeNG-Version in our project from 15 to 17.

This time I found a problem with the `p-autocomplete`. The property `maxlength` doesn't work anymore, even setting the property it does allow to type more characters than defined.

Not working (17.3.3) [Stackblitz](https://stackblitz.com/edit/7uuytc?file=src%2Fapp%2Fdemo%2Fautocomplete-basic-demo.html)

https://github.com/primefaces/primeng/assets/19362886/9f9b16ea-c04e-46ea-9428-2f81cdb48e44

Working fine (15.3.1) [Stackblitz](https://stackblitz.com/edit/hxp7md?file=src%2Fapp%2Fdemo%2Fautocomplete-basic-demo.html)

https://github.com/primefaces/primeng/assets/19362886/d5b033ec-c761-452d-9544-c7660512ae5e

### Environment

"@angular/animations": "17.0.8",
"@angular/common": "17.0.8",
"@angular/compiler": "17.0.8",
"@angular/core": "17.0.8",
"@angular/forms": "17.0.8",
"@angular/platform-browser": "17.0.8",
"@angular/platform-browser-dynamic": "17.0.8",
"@angular/router": "17.0.8",
"@swc/helpers": "~0.5.2",
"primeflex": "^3.3.1",
"primeicons": "^6.0.1",
"primeng": "17.3.1",
"rxjs": "7.8.1",
"tslib": "^2.3.0",
"zone.js": "0.14.2"

### Reproducer

https://stackblitz.com/edit/7uuytc?file=src%2Fapp%2Fdemo%2Fautocomplete-basic-demo.html

### Angular version

17.0.8

### PrimeNG version

17.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.10.0

### Steps to reproduce the behavior

See the video in the description.

### Expected behavior

The input doesn't allow to type more characters than defined.

**Comment by cetincakiroglu** [comment]
Hi,

Thanks a lot for reporting the issue!
