### ISSUE TITLE
p-calendar in range mode does not allow manually typing single date

### ISSUE THREAD

**Issue by sandrotonon** [primefaces/primeng#14590]
### Describe the bug

Using p-calendar in range mode. Need to be able to type in a single date. This can be selected from the UI picker by clicking a date and outside the calendar. However, if a single date is typed in manually then the input is rejected and the calendar reverts to an empty value.
The input is only accepted if a full range is manually typed in.

Also see issue #12286

### Environment

OS: macOS Sonoma 14.2.1
Browser: Firefox 121.0.1

### Reproducer

https://stackblitz.com/edit/ngnlme

### Angular version

17.1.0

### PrimeNG version

17.3.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.10.0

### Steps to reproduce the behavior

1. Open demo
2. Klick Input field
3. Type one single Date (e.g. 01/01/2022)
4. Tab outside the field

### Expected behavior

When typing in a single Date into a calendar in range-mode, the Datepicker should switch to the typed date (according to the configured locale).

**Comment by eduardheller89** [comment]
Any updates to this? I see also another problem in single dates: If date is higher than "maxDate" it stays in the input field. This is not the behaviour I see when I put in both range dates, where its gets deleted automatically.
