### ISSUE TITLE
SplitButton : No disbaled state for menubutton

### ISSUE THREAD

**Issue by pouyababaie** [primefaces/primeng#14600]
### Describe the bug

there were no component inputs to set the menubutton disabled state so i added it.

### Environment

default Primeng development environment 

### Angular version

16.0.2

### PrimeNG version

16.5.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.9.0

### Browser(s)

Chrome 20.0.6099.225 (Official Build) (64-bit)

**Comment by cetincakiroglu** [comment]
Fixed in https://github.com/primefaces/primeng/pull/14602
