### ISSUE TITLE
Calendar Returns Wrong Date 

### ISSUE THREAD

**Issue by PardeepJain** [primefaces/primeng#1461]
I am using calendar of primeng and as expected the date on select should be like this

2017-01-03

but i am getting in return like this: 

Wed Mar 01 2017 00:00:00 GMT+0530 (IST)

How to achieve this without using any external method of javascript ?

**Comment by upmauro** [comment]
In my opinion primeng is right. Calendar needs work with Date objects.

What you think about create a setter/getter function for your target and call .toISOString() ?

**Comment by PardeepJain** [comment]
amm may be they were right @upmauro , 
but whats your suggestion, may i get bit more explanation about this here ( if possible with code) ? 
how to use `.toISOString()` ?

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/MxSw4qOuwDfq7rLO7jrR?p=preview
