### ISSUE TITLE
Component: Calendar isn't show initial value from FormControl/ngModel

### ISSUE THREAD

**Issue by dreyliky** [primefaces/primeng#14616]
### Describe the bug

The calendar that binded to FormControl isn't shown the initial value from FormControl - check screen.

dateFormat - `yy-mm-dd`
dataType - `string`

But then, if I change the date in the overlay by picking the date manually - it updates the value in the "input" element.

![image](https://github.com/primefaces/primeng/assets/28815991/2b43583f-25da-4d51-a24e-ffc903d4feab)

### Environment

Angular 17, PrimeNG 17.3.3

https://stackblitz.com/edit/4gkycx?file=src%2Fapp%2Fdemo%2Fcalendar-reactive-forms-demo.html

### Reproducer

https://stackblitz.com/edit/4gkycx?file=src%2Fapp%2Fdemo%2Fcalendar-reactive-forms-demo.html

### Angular version

17.0.5

### PrimeNG version

17.3.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.0

**Comment by davisb10** [comment]
I think I found the issue. It was introduced in https://github.com/primefaces/primeng/pull/14497

That addition now runs the updateModel method, which calls formatDateTime, which then checks if the 'value' is a valid Date object. However, when the value is a string it will return false and then update the value of the form to be null.

This area of the calendar code will need reworked to handle this change.

**Comment by PraveenReddy-4e1** [comment]
Still it is not working.

**Comment by Tsai-Ching** [comment]
It is unstable. I am having the date while the ngModel  is not showing in the calender from time to time.

**Comment by Berejnec** [comment]
Still not working. Date is not showing from time to time.

**Comment by sdmakwana** [comment]
still the same issue occurs

**Comment by heynmi** [comment]
At a large cap organization, we are upgrading from Angular 16 -> 18 for our internally facing UI that's critical to company operations.

This issue also is also occurring for us after the upgrade. Deployed environments show the date, upgraded code shows an empty box. We've been testing a lot of different approaches but ultimately are getting an unpopulated calendar.

If the box is clicked on, and a date selected, then it does populate, but not on initialization.

Does anyone have a fix for this?

**Comment by ManjeeLama** [comment]
Is there any workaround for this?

**Comment by khaldi-yass** [comment]
The problem lies in the type of selection mode you're using, the range mode only accepts an array of two dates, while the single mode accepts the single date object, setting your selectionMode="single" will fix the problem.
