### ISSUE TITLE
Component: Autocomplete

### ISSUE THREAD

**Issue by rekna1** [primefaces/primeng#14615]
### Describe the bug

Autocomplete bound to property that has value null displays [Object object]

### Environment

 "@angular/core": "^17.0.7",
 "primeng": "^17.3.3",

### Angular version

17.0.7

### PrimeNG version

17.3.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.10.0

### Steps to reproduce the behavior

`
vm.viewData.besluitType=  {
  PrefLabel:null
 }

 <p-autoComplete appendTo="body" [ngModel]="vm.viewData.besluitType" class="flexauto" 
            [suggestions]="vm.besluitTypes" (completeMethod)="this.searchBesluitTypeSubj.next($event.query)"
            (ngModelChange)="setBesluitTypeId($event)" field='PrefLabel' name="besluittype">
            <ng-template let-besluittype pTemplate="item">
              <div class="besluittype level-{{besluittype.Level}} enabled-{{!besluittype.HasChildren}}">
                {{besluittype.PrefLabel}}
              </div>
            </ng-template>
          </p-autoComplete>`

### Expected behavior

I expect it to display an empty string as was the case in version 16

**Comment by rekna1** [comment]
still having this issue with version 17.6

**Comment by rekna1** [comment]
I investigated the issue further, the autocomplete binds to { Id:null, Description:null }.
see comments in the code
```
 inputValue = computed(() => {
        const modelValue = this.modelValue();
        if (modelValue) {
            if (typeof modelValue === 'object') {
                const label = this.getOptionLabel(modelValue);
                // so label will be null and in this case it returns modelValue which is an object
                // the condition might be wrong, property Description exists on the model, it only contains null
                // so it should return null (or empty string)
                return label != null ? label : modelValue;
            }
            else {
                return modelValue;
            }
        }
        else {
            return '';
        }
    });

```

**Comment by shammill** [comment]
Also having this issue. Having a null label will display as [Object object].
Introduced in v16. There is nothing in the change logs regarding this change in behaviour.

Related to 
https://github.com/primefaces/primeng/issues/14341

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
