### ISSUE TITLE
Component: MultiSelect

### ISSUE THREAD

**Issue by jimguistwite** [primefaces/primeng#14617]
### Describe the bug

When MultiSelect toggleAll is invoked, disabled items become de-selected.  Prior versions of the library did not de-select disabled items.   As a result, after toggle all is again clicked, the disabled items are now unselected.

<img width="479" alt="image" src="https://github.com/primefaces/primeng/assets/746213/a50a821b-191e-4850-8a6d-af61a421ec50">

<img width="493" alt="image" src="https://github.com/primefaces/primeng/assets/746213/865813d5-dfd1-4c87-9f54-19b7ca9f339d">

<img width="486" alt="image" src="https://github.com/primefaces/primeng/assets/746213/58c0d40d-f498-468e-a229-24d6f99719f0">

### Environment

https://stackblitz.com/edit/github-ry5j6r?file=src%2Fapp%2Fapp.component.ts

### Reproducer

https://stackblitz.com/edit/github-ry5j6r?file=src%2Fapp%2Fapp.component.html

### Angular version

17.0.9

### PrimeNG version

17.3.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.10.0

**Comment by VolodymyrKornetskyi** [comment]
I double checked source code and figure out that property toggleAllDisabled is removed from component but still using in html. Guys please double check multiselect component for issues

**Comment by thaihacong** [comment]
The logic is broken here https://github.com/primefaces/primeng/blob/fd18d9678a7a2733610981b3e7620c62566e26f9/src/app/components/multiselect/multiselect.ts#L1834.
<img width="590" alt="image" src="https://github.com/primefaces/primeng/assets/8019304/5247d1ca-f407-4caf-87df-7c51ff882f16">

In old working versions, it was done like in https://github.com/primefaces/primeng/blob/ac054f92f9c45be9709d2b0351e4ce0b5d1e430b/src/app/components/multiselect/multiselect.ts#L870.
<img width="406" alt="image" src="https://github.com/primefaces/primeng/assets/8019304/d3aadff0-5a6f-4520-a9b1-ecbd46a72ba7">

**Comment by cetincakiroglu** [comment]
Fixed in https://github.com/primefaces/primeng/pull/14997
