### ISSUE TITLE
Component: Calendar sets seconds to current seconds even if showSeconds=false

### ISSUE THREAD

**Issue by SkoZombie** [primefaces/primeng#14626]
### Describe the bug

When using a time but not seconds, the seconds are still set as part of `selectDate()`. This will mean if an end user selects the same date twice the dates may not be equal to each other due to the seconds component of the time. This may lead to confusing behaviour such as the period between two times being a fractional number of minutes.

Without testing locally, my guess is the line:

`date.setSeconds(<number>this.currentSecond);`

Should be updated to:

`date.setSeconds(this.showSeconds ? <number>this.currentSecond : 0);`

So that seconds are not set to anything other than zero if they are not being displayed to the user.

### Environment

NodeJS 18.17.1
Angular 17.1.1
PrimeNG 17.4.0

### Angular version

17.1.1

### PrimeNG version

17.4.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.17

### Steps to reproduce the behavior

1. Create a calendar [showTime]="true" [showSeconds]="false"
2. Select a date and time
3. Inspect the bound object, seconds will be set to whatever the current seconds rather than zero

### Expected behavior

The seconds component of the Date should always be zero if showSeconds=false to avoid confusion

**Comment by uebelmar** [comment]
documentation says "Whether to show the seconds in time picker"

so this option toggles only the display of the seconds in the picker. it does not manipulate the date object behind.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Comment by filiptrivan** [comment]
I have the same problem in the latest version, any updates?

**Comment by SkoZombie** [comment]
> I have the same problem in the latest version, any updates?

Given they closed this issue, I think you'll need to raise a new ticket
