### ISSUE TITLE
Not able to import OrderListModule or PickListModule i Angular 17.1 standalone components

### ISSUE THREAD

**Issue by BaardOvrebo** [primefaces/primeng#14624]
### Describe the bug

When trying to import OrderListModule or PickListModule the application will not compile and returns an error from common.js complaining about a value reading ‘None’

I am using Angular 17.1 and the latest PrimeNG.

All of the other components from PrimeNG seems to be working without issues.

### Environment

NodeJS 20^
Angular 17.1
PrimeNG latest

### Angular version

17.1

### PrimeNG version

17.4.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.0

### Steps to reproduce the behavior

Create Angular project with standalone components.
Try adding Picklist to a component’s import.

### Expected behavior

After adding the PickListModule to the components import array you will not be able to load the application. It returns an error in the console.

**Comment by PaulBerthelot21** [comment]
Hello @BaardOvrebo, have you found a solution ? Thanks.

**Comment by baard-ovrebo** [comment]
> Hello @BaardOvrebo, have you found a solution ? Thanks.

Sorry. I have still not been able to have this work

**Comment by PaulBerthelot21** [comment]
@BaardOvrebo, I managed to get the modules working, for my part I had not installed the Angular CDK. 

`npm install @angular/cdk --save`
