### ISSUE TITLE
Table: built-in Ctrl+A errors when "rows" parameter is defined

### ISSUE THREAD

**Issue by horizoncarlo** [primefaces/primeng#14634]
### Describe the bug

Create a p-table with `selectionMode="multiple"` and `[rows]="5"` (or whatever number).

Select a row, then press Ctrl+A in an attempt to select the rest. Nothing happens and in the web console there is an error:
![image](https://github.com/primefaces/primeng/assets/65215473/3009098e-7db3-4e03-8dd5-82a20a62d12b)

I've also seen "data is not iterable" from onKeyDown.

### Environment

Basic app, running in Linux on Chrome or Firefox, with Ang/PrimeNG versions below.

### Reproducer

https://stackblitz.com/edit/github-u7kinp?file=src%2Fapp%2Fapp.component.html

### Angular version

17.0.7

### PrimeNG version

17.3.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

Node 20.9.0

### Browser(s)

Chrome and Firefox

### Steps to reproduce the behavior

From the StackBlitz example:

1. Select a row
2. Press Ctrl+A
3. Nothing happens and there is an error in the console

If you remove [rows] from the p-table and try again it works as expected.

### Expected behavior

Ctrl+A selects all the rows properly

**Comment by quentin-ineat-ca** [comment]
@cetincakiroglu Error fixed in console but the selected lines are inexact, wrong fix.
Related to : https://github.com/primefaces/primeng/issues/14463

**Comment by cetincakiroglu** [comment]
> @cetincakiroglu Error fixed in console but the selected lines are inexact, wrong fix.
> 
> Related to : https://github.com/primefaces/primeng/issues/14463

Thanks for the feedback we'll check again.

**Comment by cetincakiroglu** [comment]
Hi @quentin-ineat-ca ,

Ctrl + A selects all options in the current page and there isn't a console error. Could you please guide me to catch what's wrong with it?

**Comment by quentin-ineat-ca** [comment]
Hello @cetincakiroglu 
With this exemple: https://stackblitz.com/edit/ty2zuu-6efrnz?file=package.json
I'm on mac and use cmd + a.

On apparence the selection is good but the actual selected rows are not good and they are duplicated.

If you click on first row (for exemple), cmd+a, you get 15 selected while only 10 on the page. 
You click on another row, cmd+a, and the amount is again different.

**Comment by cetincakiroglu** [comment]
Hi,

Thank you for helping me understand the problem and providing a new example. When the paginator is used, the selectAll function does not work properly. I have created a new issue and added it to the milestone. We will try to resolve this issue in version 17.6.0 https://github.com/primefaces/primeng/issues/14700

**Comment by cetincakiroglu** [comment]
We've investigated the issue and found that `selectRange` method needs a refactor. The behavior should be same as checkbox selection. We'll rewrite the select all logic for pSelectableRow. I'm moving this issue #14700  to the 17.Future milestone since the issue needs a meticulous study to be handled carefully. We'll take a look at it within the v17.

**Comment by quentin-ineat-ca** [comment]
Thank you for the follow up :)
