### ISSUE TITLE
Cannot tab into tieredmenu where an id and label exist

### ISSUE THREAD

**Issue by Cue-Ai-NGinEar** [primefaces/primeng#14638]
### Describe the bug

Unable to tab into an element within the p-splitbutton component. This only happens when you have a value set for optional parameters "label" and "id" - if you remove the id parameter then you can tab into the tieredmenu element. 

### Environment

Angular app running in Chrome.

### Angular version

16.2.9

### PrimeNG version

16.9.1

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

18.19.3

### Steps to reproduce the behavior

Within the p-splitbutton component, if you tab to the defaultbutton, then menubutton and active this, you cannot tab into the tieredmenu - it is impossible to get the keyboard to focus into the menu.

### Expected behavior

You should be able to have an "id" value set on the tieredmenu element with the p-splitbutton component and still tab into it.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
