### ISSUE TITLE
Calendar defaultDate is not highlighted

### ISSUE THREAD

**Issue by clementdessoude** [primefaces/primeng#14633]
### Describe the bug

I'm not sure if it is a bug or if I don't understand the documentation properly. I tried to use the defaultDate property on the calendar component. The calendar open on the month and year of the defaultDate, as expected, but I expected to see also the defaultDate option highlighted (as the today's date is highlighted by default).

My understanding of the documentation is the same: 
> Set the date to highlight on first opening if the field is blank. 

<img width="906" alt="Screenshot 2024-01-25 at 16 46 27" src="https://github.com/primefaces/primeng/assets/25530077/f3c7339b-db1e-405f-a75f-a228d3e648e5">

### Environment

My application is running on Angular 17 with latest version of PrimeNg (17.4.0)

### Angular version

17.0.9

### PrimeNG version

17.4.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.11.0

### Steps to reproduce the behavior

1. Add a calendar input in your Angular project with a default date (e.g. new Date('1995-12-17T03:24:00');)
2. Open the calendar input. You should see the month of December, 1995.
3. The 17th of December however is not highlighted

### Expected behavior

I would expect to see the default date highlighted, as the today's date is. Or to have a clearer documentation on this property

Please let me know if I can help in any way on this topic !

**Comment by arnoudb** [comment]
We are experience the same issue (angular 17.0.9, primeNG: 17.3.2)

**Comment by nbrown-ScottLogic** [comment]
I believe this is covered in the bug issue : https://github.com/primefaces/primeng/issues/2799
