### ISSUE TITLE
p-selectButton: Can not add a overwritten class

### ISSUE THREAD

**Issue by ClaraKrchr** [primefaces/primeng#14647]
### Describe the bug

I'm working on prime ng in v16, before the version update of angular (I'm now in v16) I was working on a p-selectButton which had a different background color depending on the id of the displayed object. Since the migration, my buttons no longer change color, I no longer even see my class in the DOM.
I contacted the prime ng discord, they told me it was a regression and to create an issue ticket here

### Environment

I work on visual studio code and with edge.

### Reproducer

https://stackblitz.com/edit/github-kvdet4?file=src%2Fapp%2Fapp.component.html

### Angular version

16.2.10

### PrimeNG version

16.5.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.16.0

### Browser(s)

edge

### Steps to reproduce the behavior

just open the DOM and you will not see my class

**Comment by zzzaaa** [comment]
Your example dosent work (compile error) You forgot to attach a models array. :)
