### ISSUE TITLE
Component: Dropdown

### ISSUE THREAD

**Issue by Moh1982KH** [primefaces/primeng#14648]
### Describe the bug

1. https://primeng.org/dropdown
2. go to chapter Filter
3. select an Item
4. click on clear button
5. input field is empty. 

**Expectation**: Show placeholder 

### Environment

Angular 17
PrimeNG: 17.0.4
Node: 20 

### Angular version

17

### PrimeNG version

17

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. https://primeng.org/dropdown
2. go to chapter Filter
3. select an Item
4. click on clear button
5. input field is empty. 

### Expected behavior

**Expectation**: Show placeholder

**Comment by mountpoint** [comment]
same issue

**Comment by cetincakiroglu** [comment]
Hi,

This issue is fixed with v17.6.0. You can check here http://primeng.org/dropdown#filter

Thanks for reporting, I'm closing the issue.
