### ISSUE TITLE
Calendar: disabledDays invoking the year navigator to be displayed disabled

### ISSUE THREAD

**Issue by amonsour** [primefaces/primeng#14640]
### Describe the bug

Using the disabledDays, the year navigator is taking the first date in January, and seeing if that date alone is disabled, instead of the whole month.

`    isYearDisabled(year) {
        return !this.isSelectable(1, this.currentMonth, year, false);
    }`

### Environment

Angular 17
PrimeNG 17.4.0

### Reproducer

https://stackblitz.com/edit/stmnpi?file=src%2Fapp%2Fdemo%2Fcalendar-float-label-demo.ts

### Angular version

17.0.5

### PrimeNG version

17.4.0

### Build / Runtime

Angular

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.1

### Steps to reproduce the behavior

1. Open the stackblitz link
2. Click the calendar component in the preview
3. Click 2024
4. 
![image](https://github.com/primefaces/primeng/assets/9057540/04fefa27-2062-4469-ae6b-031ba7e4f9a8)

### Expected behavior

The years should be clickable if any date in January is enabled, when using disabledDays

**Comment by robGardiner01** [comment]
I've tried reproducing this on mine and it seems to work properly
