### ISSUE TITLE
p-table: p-paginator only let me change number of rows displayed once

### ISSUE THREAD

**Issue by jogp10** [primefaces/primeng#14650]
### Describe the bug

I open a table, I change the number of rows displayed on the table. When trying to change once more the number of rows displayed on the table, the pop-up with the possible choices does not appear visible.

I have other tables on my project where everything works fines. It is a problem of this specific table.

### Environment

Html component:
<p-table class="main-content" #sos_test_detail_table [id]="tableId" [columns]='cols' [value]='data' sortMode='multiple'
             selectionMode='single'
             [lazy]='true'
             (onLazyLoad)='loadDataLazy(tableRef)'
             [scrollable]='false'
             [rowsPerPageOptions]='rowsPerPageOptions'
             [totalRecords]='totalRecords' [loading]='loading'
             [showCurrentPageReport]='true' [paginator]="true" [rows]='rowsByDefault'
             [currentPageReportTemplate]='infoReportDisplay'>
             
   SCSS rules specific to table component (p-table):
   .main-content {
  max-height: 55vh;
  overflow-y: scroll;
}

Other SCSS rules:
:host {
  position: absolute;
  z-index: 100;
}

.popup_bg {
  display: flex;
  justify-content: center;
  align-items: center;
}

.outter-wrapper {
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  background: transparent;
  display: flex;
  justify-content: center;
  align-items: center;
}

.content-wrapper {
  color: white;
  background: var(--popup-color);
  border-radius: 15px;
  max-width: 80vw;
}

.header {
  height: 57px;
  background: rgba(0, 0, 0, 0.13);
  border-radius: 15px 15px 0px 0px;
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0 18px;

  &__title {
    font-size: 13px;
    font-weight: bold;
  }

  &__icon {
    cursor: pointer;
  }
}

   
  Html component of a working table:
  <p-table #vms_history_table id="vms_history_table" [columns]='cols' [value]='data' sortMode='multiple'
        selectionMode='single' [lazy]='true'
        (onLazyLoad)='loadDataLazy(tableRef)' [scrollable]='true' [scrollHeight]='scrollHeight'
        [rowsPerPageOptions]='rowsPerPageOptions' [totalRecords]='totalRecords' [loading]='loading'
        [showCurrentPageReport]='true' [paginator]="true" [rows]='rowsByDefault'
        [currentPageReportTemplate]='infoReportDisplay' [pageLinks]="'5'">
        
        Paginator is equal in both tables

### Angular version

10.2.0

### PrimeNG version

9.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.15.1

### Browser(s)

Microsoft Edge

### Steps to reproduce the behavior

1. Click to appear popup table
2. Change number of rows displayed
3. Try to change number of rows displayed again

### Expected behavior

I should be able to change the number of rows displayed more than once.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
