### ISSUE TITLE
CalendarModule: problem to order more than 12 months

### ISSUE THREAD

**Issue by FerViaEmi** [primefaces/primeng#14654]
### Describe the bug

Dear team,

I am using CalendarModule component "primeng":"^15.3.0", in "@angular/common":"^15.0.0", "@angular/core":"^15.0.0".

I need to load the next 13 months from now but the month load fails when the current month is November or December. For the rest of the months, the process works.

Do you have this scenario identified, do you have a proposed solution?

Example of failed configuration:

<div class="p-fluid p-grid p-formgrid">
  <div class="p-field p-col-12 p-md-4">
    <label for="monthpicker">Month Picker</label>
    <p-calendar
      [(ngModel)]="date12"
      view="date"
      [inline]="true"
      dateFormat="dd/mm/yy"
      [yearNavigator]="true"
      yearRange="2000:2030"
      [readonlyInput]="true"
      inputId="monthpicker"
      [numberOfMonths]="13"
    ></p-calendar>
  </div>
</div>

<img width="310" alt="november_calendar" src="https://github.com/primefaces/primeng/assets/158077217/d554f6fa-72d8-4151-803a-34a1ea04cfcb">

### Environment

development environment

### Reproducer

https://stackblitz.com/edit/primeng-calendar-demo-k8gckd?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html

### Angular version

15.0.0

### PrimeNG version

15.3.0

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

8.3.0

### Browser(s)

all

### Expected behavior

the expected behaviour is to be able to recover the next 13 months without error for the months of November and December. The error is only reproducible for these two months.

**Comment by FerViaEmi** [comment]
Hello,

any news about this issue?

thank you.

**Comment by egarciade** [comment]
Hi. 
Have you been able to check the issue?
Please is very important for us
Thanks

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Comment by DrochCH** [comment]
Are you aware that this error persists 3 years later?
