### ISSUE TITLE
No line for p-tree horizontal 

### ISSUE THREAD

**Issue by JuliaHorokhovatska** [primefaces/primeng#14656]
### Describe the bug

![Screenshot from 2024-01-29 19-23-12](https://github.com/primefaces/primeng/assets/111287515/6240c605-194f-44af-b585-95c3e22a5d4d)
there must be:
![Screenshot from 2024-01-29 19-24-21](https://github.com/primefaces/primeng/assets/111287515/901cba7a-71e1-4d65-91f7-b1e205da4262)

### Environment

Angular 17, primeng 17.4.0

### Angular version

17.0.8

### PrimeNG version

17.4.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v18.18.0

### Steps to reproduce the behavior

using p-tree in horizontal layout

### Expected behavior

![Screenshot from 2024-01-29 19-24-21](https://github.com/primefaces/primeng/assets/111287515/7f712cb1-a21a-4450-836a-35ad38a13b4f)

**Comment by cetincakiroglu** [comment]
Hi,

I couldn't replicate the issue https://stackblitz.com/edit/u2tnbu?file=src%2Fapp%2Fdemo%2Ftree-basic-demo.html
Could you please provide an example so we can investigate the problem?

**Comment by cetincakiroglu** [comment]
I am moving to the next milestone while waiting for the response.
