### ISSUE TITLE
p-columnFilter: On selection of options in the filter dropdown, the filter menu is inconsistently closing

### ISSUE THREAD

**Issue by aditi1425** [primefaces/primeng#14651]
### Describe the bug

The p-columnFilter module in PrimeNG exhibits an inconsistent issue where the filter dropdown randomly closes upon the selection of options. This behavior occurs sporadically, making it challenging to reproduce consistently. The problem seems to be related to the selection of options within the filter dropdown making the user unable select multiple filter option in a single instance. 

### Environment

occurring on all environments

### Angular version

13.2.6

### PrimeNG version

13.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

-

### Steps to reproduce the behavior

- Apply a filter to a column that triggers the filter dropdown to appear.
- Attempt to select an option from the dropdown.
- Observe that, at times, the dropdown closes unexpectedly after selecting an option(generally on second selection)

### Expected behavior

The filter dropdown should remain open after selecting an option until the user explicitly closes it or clicks outside the dropdown area.

**Comment by BecomingGG** [comment]
On v17.1.0  on dropdown select it closes column filter instantly is there possibility to change this behaviour.

**Comment by aditi1425** [comment]
We can use the **overlayVisible** property of column filter in order to handle the visibility.
