### ISSUE TITLE
Dropdown: autoOptionFocus property not working

### ISSUE THREAD

**Issue by miki995** [primefaces/primeng#14655]
### Describe the bug

Using the most simple example of dropdown, the _autoOptionFocus_ property is not doing it's job.

The problem is present only on first dropdown open, after first open, the focus is gone as it should be.

### Environment

Angular 17, Primeng 17

<img width="1003" alt="image" src="https://github.com/primefaces/primeng/assets/22272040/937f9e71-07a1-40dd-9b1a-08ba79e2379f">

<img width="1040" alt="image" src="https://github.com/primefaces/primeng/assets/22272040/5d76b117-c43f-4440-83c5-f1132ee31126">

### Angular version

17.1.1

### PrimeNG version

17.4.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.13

### Steps to reproduce the behavior

1. Open primeng repo master branch
2. Go to src/app/showcase/doc/dropdown/basicdoc.ts
3. Add [autoOptionFocus]="false" to the <p-dropdown component
4. Compile and check

### Expected behavior

The dropdown should not show the focus on first item on first load.

**Comment by c-o-l-i-n** [comment]
@cetincakiroglu @mehmetcetin01140 This is still broken in PrimeNG 17.18.0:

https://stackblitz.com/edit/stackblitz-starters-rytw83?file=src%2Fmain.ts

![image](https://github.com/primefaces/primeng/assets/40863449/fb66d405-7c62-44b6-870e-c9940a5ebdf9)

**Comment by Ar-Kareem** [comment]
This was supposedly fixed in version (`17.5.0`  2024-02-01) but I'm still experiencing it in `17.18.11`.

It only happens the first time I open the dropdown when loading the page
![image](https://github.com/user-attachments/assets/904e4db3-0bfc-4fc9-a9ad-9011c713f864)

Closing the re-opening the dropdown corrects the behavior (by having no option selected)
![image](https://github.com/user-attachments/assets/2222ec2a-005a-42f9-8197-3e6c2c6a625f)

**Comment by mountpoint** [comment]
@cetincakiroglu this issue still exists in version 17.18.11

**Comment by himanshujain1985** [comment]
I am also facing this issue while using the PrimeNg 17.18.10 version. Is there a workaround for this issue?

**Comment by TigranWA** [comment]
Also broken for "primereact": "^10.9.5", not only ng
