### ISSUE TITLE
PrimeNg p-columnFilter does not close on outside element click or scroll or search submit

### ISSUE THREAD

**Issue by Joroooo** [primefaces/primeng#14658]
### Describe the bug

primeng p-columnFilter element filter does not work properly. 
Filters not close on click outside of the element 

working in primeng 13
https://stackblitz.com/edit/primeng-tablefilter-demo?file=package.json

not working on future versions
https://stackblitz.com/edit/primeng-tablefilter-demo-cgdpzk?file=package.json

Provided solutions in https://github.com/primefaces/primeng/issues/10692

do not help

### Environment

"primeng": "~16.5.1",
"@angular/core": "^16.2.0",

### Angular version

16.2

### PrimeNG version

16.5

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.10

### Browser(s)

Chrome

### Steps to reproduce the behavior

Create primeng Table, add standart fllters. Filter cannot be closed on external click. 
See both links for working properly in v13 and not working in v16

working in primeng 13
https://stackblitz.com/edit/primeng-tablefilter-demo?file=package.json

not working on future versions
https://stackblitz.com/edit/primeng-tablefilter-demo-cgdpzk?file=package.json

### Expected behavior

Filters should open without extra directives and works arrounds and should close on outside element click or scrolls

**Comment by mehmetcetin01140** [comment]
Hi,

In primeng version 17.5.0, it works as expected : https://stackblitz.com/edit/primeng-tablefilter-demo-eiz7bq?file=package.json
