### ISSUE TITLE
p-dropdown: when virtualscroll is enabled search is not working

### ISSUE THREAD

**Issue by Anesta94** [primefaces/primeng#14663]
### Describe the bug

Setting virtualScroll and filter properties to true, search is not working.
In console i see this error.
![image](https://github.com/primefaces/primeng/assets/41288508/c9b7a600-aeca-400c-8290-bebcba25bbed)

### Environment

Stackblitz

### Reproducer

https://stackblitz.com/edit/rrbtms?file=src%2Fapp%2Fdemo%2Fdropdown-virtualscroll-demo.html

### Angular version

17.0.5

### PrimeNG version

17.4.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.0

### Expected behavior

By entering characters in the search field, the results should be filtered correctly.

**Comment by cetincakiroglu** [comment]
Hi,

Could you please try with the latest version (17.6.0)

**Comment by cetincakiroglu** [comment]
Hi, 

I couldn't catch the error in v17.6.0, could you confirm this behavior?

![Screenshot 2024-02-13 at 10 46 53](https://github.com/primefaces/primeng/assets/69278826/f13986dc-f2d5-45aa-b1aa-2610a161d158)

**Comment by cetincakiroglu** [comment]
Hi @Anesta94,

Thanks a lot for confirming the fix. I'm closing the issue since it's invalid in the latest version.
