### ISSUE TITLE
TreeTable: Previous, First Page, Last Page and Next button icons not visible when using paginator component

### ISSUE THREAD

**Issue by VaishV25** [primefaces/primeng#14674]
### Describe the bug

Navigation buttons are present, but icons are not visible. 

It may be the same problem that was fixed on regular table-component:
 https://github.com/primefaces/primeng/issues/12916

The fix awas also provided for TreeTable version 16
https://github.com/primefaces/primeng/issues/13258

Our application has other dependencies which work on version 15, could you please provide a solution for version 15.

### Environment

Bug can be seen in primeNg demo page.

https://www.primefaces.org/primeng-v15-lts/treetable

### Reproducer

https://www.primefaces.org/primeng-v15-lts/treetable

### Angular version

15.2.10

### PrimeNG version

15.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.0

### Expected behavior

The icons for pagination previous, first page, next and last page must be visible.

**Comment by mehmetcetin01140** [comment]
Hi,

It will be included in the LTS release next Wednesday (Feb. 21). Thank you for reporting the issue.
