### ISSUE TITLE
PanelMenu Component: Add header/icon template 

### ISSUE THREAD

**Issue by CountFib** [primefaces/primeng#14676]
As far as I know, and after looking for a solution, it seems there's no template available for the header of the PanelMenu.

My goal is to use a custom icon, as describe here https://primeng.org/customicons#svg
But this doesn't seem possible with the PanelMenu component.

The only template available is submenuicon, but it affects the arrow, not the icon.

The issue #13789 pointed out that there's an item template available for all menu item and has been closed, but for PanelMenu it affects only the submenu, not the first level menu.

Is there something I missed? If I didn't, would it be possible to add this feature? Thanks.

**Comment by edora-clausjessing** [comment]
+1

Only submenuitems are rendered according to the template. There should be a template like in p-menu.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
