### ISSUE TITLE
ActiveIndex on p-tabmenu

### ISSUE THREAD

**Issue by tigrenok00** [primefaces/primeng#1468]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Is there an option to set **activeIndex** programmatically on p-tabmenu? I saw it exists in js version but not on ng. 
Is there a workaround to do this? ActiveItem only works for initial selection and not programatically...

* **Angular version:** 2.0.1

* **PrimeNG version:** 1.0.0.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
There is no activeIndex in tabview, you can use selected property binding though if you need indexes or similar;

```
<button type="button" (click)="index = 2" label="Change to 2"></button>
    <p-tabView>
        <p-tabPanel header="Godfather I" leftIcon="fa-calendar" [selected]="index == 0">
            aaa
        </p-tabPanel>
        <p-tabPanel header="Godfather II" rightIcon="fa-print" [selected]="index == 1">
            bbb
        </p-tabPanel>
        <p-tabPanel header="Godfather III" leftIcon="fa-bell-o" rightIcon="fa-bookmark-o" [selected]="index == 2">
            ccc
        </p-tabPanel>
    </p-tabView>
```

**Comment by cagataycivici** [comment]
You can do a binding to [activeItem] to programmatically control the active element. For example;

```
<p-tabMenu [model]="items" [activeItem]="items[1]"></p-tabMenu>
```
This will open the index 1 by default, if you bind a variable instead then you can change it programmatically like;

```
<p-tabMenu [model]="items" [activeItem]="currentItem"></p-tabMenu>
```

```
change() {
    currentItem = this.items[1];
}
```
