### ISSUE TITLE
Listbox: Unexpected behaviour of Page Up/Down + infinite loop 

### ISSUE THREAD

**Issue by ramires83** [primefaces/primeng#14686]
### Describe the bug

Page Up behaves as Page Down
Page Down key press causes infinite loop  

### Environment

SPA Angular web app
Windows environment

### Angular version

16.2.9

### PrimeNG version

16.9.4-lts

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.17.0

### Browser(s)

Chrome 121.0.6167.85 (Official Build) (64-bit)

### Steps to reproduce the behavior

1. Enable checkboxes (using checkbox=true), the filter input (filter=true) and the "Show all" option (showToggleAll=true). 
2. Click one of the items in the list to bring keyboard focus to the UL element (.p-listbox-list).
3. Press the Page Down key.
   Expected behaviour: List scrolls down
   Actual behaviour: nothing happens
5. Press the Page Up key.
   Expected behaviour: No action as the list is already scrolled up
   Actual behaviour: List scrolls down
6. Press the Page Up key again.
   Expected behaviour: List scrolls up
   Actual behaviour: nothing happens
8. Press the Page Down key again 
   Expected behaviour: nothing happens  as the list is already scrolled down
   Actual behaviour: Control enters an infinite loop and becomes unresponsive

### Expected behavior

Page Down scrolls the list down
Page Up scrolls the list up
Control remains responsive

**Comment by cetincakiroglu** [comment]
Closing the issue due to inactivity. Feel free to open a new issue with the reproducer.
