### ISSUE TITLE
Component: Dropdown TypeError: option.toLowerCase is not a function

### ISSUE THREAD

**Issue by CyleClone** [primefaces/primeng#14682]
### Describe the bug

Same problem as in issue #14370:
Declaring a dropdown with a filter, but not specifying `optionlabel="label"` or `filterBy="label"` breaks the dropdown on filter.

### Environment

Chrome, Mozilla

### Reproducer

https://stackblitz.com/edit/github-3wjoqr?file=src%2Fapp%2Fapp.component.html

### Angular version

17.x.x

### PrimeNG version

17.x.x

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.x.x

### Expected behavior

Default filter should reference to label as before, not undefined

**Comment by bartan34** [comment]
I have the same problem. Event with 17.4.0.

**Comment by asithade** [comment]
For me, when I have to add both `optionLabel="label"` and ` filterBy="label"`. Then because of that, I also have to add `optionValue="value"`, if not it pastes the object instead of the value.
