### ISSUE TITLE
Dialog: visibleChange does not emit when dialog opens

### ISSUE THREAD

**Issue by LoaderB0T** [primefaces/primeng#14688]
### Describe the bug

When using a dialog element, the `visibleChange` output only emits `false` when the dialog is hidden (visible set to `false`).

It would be great to also emit `true` when the dialog is opened (`visible` set to `true`).

This would be great for directives that build upon opening/closing dialogs as the input value of `visible` is not easily usable from there.

Exemplary Code:

```html
<p-dialog [visible]="someValue$ | async" (visibleChange)="someMethod($event)>
//...
</p-dialog>
```

```typescript
protected someMethod(event: boolean) {
  console.log(event);
}
```

Expected Behavior:
Console logs show "true" when opening and "false" when closing the dialog

Actual behavior:
Console logs only show false when closing, and nothing when opening the dialog

We will gladly try to contribute a PR for a solution if you agree that this should be the behavior.

### Angular version

17.0.X

### PrimeNG version

17.3.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.9

### Browser(s)

Chrome 120

**Comment by LoaderB0T** [comment]
Just had an afterthought. If this is not preferred because of two way databinding, I would like to add another EventEmitter like "visibilityChanged" or something to not introduce problems for two way databinding.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
