### ISSUE TITLE
Checkbox: Disabled property does not work when it's used with formControlName

### ISSUE THREAD

**Issue by mehmetcetin01140** [primefaces/primeng#14693]
### Describe the bug

Disabled property does not work when it's used with formControlName.

### Environment

Angular 17
PrimeNG: 17.3.3

### Angular version

17

### PrimeNG version

17.3.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20

### Steps to reproduce the behavior

<form class="flex align-items-center gap-1" [formGroup]="formGroup">
<p-checkbox formControlName="city" value="New York" inputId="ny" [disabled]="true"></p-checkbox>
<label for="ny">New York</label>
</form>

**Comment by mirinio** [comment]
this is still not working for me

**Comment by mirinio** [comment]
this is still not working properly. if I disable the checkbox it only gets disabled within the next detection. So when I click on the checkbox it disables after the click. but it should disable before that.

[example](https://stackblitz.com/edit/j5hhcz?file=src%2Fapp%2Fdemo%2Fcheckbox-reactive-forms-demo.html,src%2Fapp%2Fdemo%2Fcheckbox-reactive-forms-demo.ts,package.json)
