### ISSUE TITLE
Checkbox support for Listbox

### ISSUE THREAD

**Issue by ntkolev** [primefaces/primeng#1469]
**I'm submitting a ...**
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**What is the motivation / use case for changing the behavior?**
I would like to use the MultiSelect as a Listbox with checkboxes. The master checkbox/search capabilities make this component perfect for our needs.

The closest thing I could try is to hide the combo with `display:none`, and set the `overlayVisible` to true. The problem is that the overlay is hidden when the user clicks outside of it. It would be great if there was a way to fix it on the screen.

**Comment by Mrtcndkn** [comment]
Hi,

Like in primefaces http://www.primefaces.org/showcase/ui/input/manyMenu.xhtml  ?

**Comment by ntkolev** [comment]
Yes, exactly like this one, but for Angular2

**Comment by roni-frantchi** [comment]
Thanks for the prompt response @Mrtcndkn .

> Like in primefaces http://www.primefaces.org/showcase/ui/input/manyMenu.xhtml ?

I'd say, yes. Although there a couple of notable differences:
1. On PrimeFaces `SelectManyMenu` clicking an item (not the checkbox of the item), unselects all other items. In PrimeNg's `MultiSelect`, clicking on an item is similar to clicking an item's checkbox.
2. PrimeFaces `SelectManyMenu` doesn't have a built in Select All checkbox like PrimeNg's `MultiSelect`.

On both items, I'd the PrimeNg's `MultiSelect` approach is the one we're looking for.

**Comment by Mrtcndkn** [comment]
Okey we will do it in 1.0.2 @roni-frantchi

**Comment by roni-frantchi** [comment]
Awesome. Thanks so much @Mrtcndkn !

**Comment by cagataycivici** [comment]
Reopening for code review.
