### ISSUE TITLE
Component: Calendar incorrect process initial value from FormControl/ngModel

### ISSUE THREAD

**Issue by dreyliky** [primefaces/primeng#14699]
### Describe the bug

The calendar shows the date in the input element but doesn't select the initial date inside the overlay until I select it by clicking on a specific day inside the overlay.

dateFormat - `yy-mm-dd`
dataType - `string`

In PrimeNg >=17.3.3 <17.5.0 calendar behavior described here:
https://github.com/primefaces/primeng/issues/14616

![image](https://github.com/primefaces/primeng/assets/28815991/ce22747e-c318-4ce8-b323-17f05982a7e7)

### Environment

https://stackblitz.com/edit/4gkycx-okhm5i?file=src%2Fapp%2Fdemo%2Fcalendar-reactive-forms-demo.html

### Reproducer

https://stackblitz.com/edit/4gkycx-okhm5i?file=src%2Fapp%2Fdemo%2Fcalendar-reactive-forms-demo.html

### Angular version

17

### PrimeNG version

17.5.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.0

**Comment by cetincakiroglu** [comment]
Reverted the PR that breaks the functionality and causes this issue. Related PR is reverted in here https://github.com/primefaces/primeng/pull/14750

Thanks for reporting the issue
