### ISSUE TITLE
Codesandbox examples not working due to node and incompatibility

### ISSUE THREAD

**Issue by blackat** [primefaces/primeng#14707]
### Describe the bug

Hello,
in all the Codesandbox example there is an incompatibility between the Angular version and the node.js version, none of the examples can be run;

```bash
info No lockfile found.
[1/4] Resolving packages...
warning @angular-devkit/build-angular > webpack-dev-middleware > memfs@3.6.0: this will be v4
warning @angular-devkit/build-angular > webpack-dev-server > webpack-dev-middleware > memfs@3.6.0: this will be v4
[2/4] Fetching packages...
error @angular-devkit/build-angular@17.1.2: The engine "node" is incompatible with this module. Expected version "^18.13.0 || >=20.9.0". Got "16.15.1"
error Found incompatible module.
```

### Environment

Condesandbox examples.

### Angular version

17.1.1

### PrimeNG version

17.5.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.15.1

**Comment by cetincakiroglu** [comment]
Hi,

Thanks for reporting the issue, we've removed the codesandbox from the documentation. Closing the issue since it's referenced in here https://github.com/primefaces/primeng/issues/14792
