### ISSUE TITLE
p-listbox: style="max-height: 200px" being set automatically

### ISSUE THREAD

**Issue by psarno** [primefaces/primeng#14704]
### Describe the bug

In a standard `<p-listbox>`, the height is limited to 200px due to a `style="max-height: 200px"` being placed on the `<div>` with the `p-listbox-list-wrapper` class:

```
<p-listbox
name="notificationTypes"
[options]="notificationTypes"
[(ngModel)]="selectedTypes"
[multiple]="true"
optionLabel="description"
[checkbox]="true"
[showToggleAll]="false"
/>
```

![image](https://github.com/primefaces/primeng/assets/18640860/937210e5-ce76-409e-b3bd-038ec4935398)

The relevant area in the source is:

![image](https://github.com/primefaces/primeng/assets/18640860/86ec5367-400c-475f-88c3-1300a9d611bb)

A workaround is to set `[scrollHeight]="'auto'"` on the `<p-listbox>`.

Note in Stackblitz, when rendered, height is capped and you get a scrollbar:

![image](https://github.com/primefaces/primeng/assets/18640860/91458f52-6883-42e4-9efc-1cbebcb6e7c2)

### Environment

PrimeNG 17.5 (also occurs with 17.4)
Angular 17.1.0

### Reproducer

https://stackblitz.com/edit/github-zmo9ym?file=src%2Fapp%2Fapp.component.ts

### Angular version

17.1.0

### PrimeNG version

17.5

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.0

### Steps to reproduce the behavior

Example and StackBlitz repro provided

### Expected behavior

No `max-width` style placed by default.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
