### ISSUE TITLE
Component: Primeng table with expanded rows and frozen columns (which are represented as table)

### ISSUE THREAD

**Issue by imotality** [primefaces/primeng#14711]
### Describe the bug

While describing primeng table and using expandable table with frozen column, I represented the expanded rows as another p-table. I have added for both of them frozen columns, but when I want to scroll, positioning are wrong, and it only scrolls parent table.  I want to connect 2 tables as one to have the same scroll. How can i do that?

### Environment

using primeng v.15

### Angular version

15

### PrimeNG version

15

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Steps to reproduce the behavior

create p-table with frozen columns, and after create expanded rows as representing of another p-table with frozen column and try to scroll it vertically. 

### Expected behavior

both tables with frozen columns are syncronized

**Comment by imotality** [comment]
<img width="460" alt="image" src="https://github.com/primefaces/primeng/assets/27500883/3ce73e35-deb4-4887-a13e-74f8f0220ea0">
 the example

**Comment by imotality** [comment]
https://stackblitz.com/edit/io4hpq?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fdemo%2Ftable-row-expand-demo.html

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
