### ISSUE TITLE
p-dropdown: with reactive form, preselected value break UI

### ISSUE THREAD

**Issue by cervenf** [primefaces/primeng#14722]
### Describe the bug

When I modify demo from documentation : https://primeng.org/dropdown#reactive-forms
That I preselect value from cities (this.cities[0]), then dropdown looks broken.
When I use p-dropdown outside form (via ngmodel) and it works correctly.

export class DropdownReactiveFormsDemo implements OnInit {
    cities: City[] | undefined;
    
    formGroup: FormGroup | undefined;

    ngOnInit() {
        this.cities = [
            { name: 'New York', code: 'NY' },
            { name: 'Rome', code: 'RM' },
            { name: 'London', code: 'LDN' },
            { name: 'Istanbul', code: 'IST' },
            { name: 'Paris', code: 'PRS' }
        ];

        this.formGroup = new FormGroup({
            selectedCity: new FormControl<City | null>(this.cities[0])
        });
    }
}

dropdown looks like this:

![image](https://github.com/primefaces/primeng/assets/1408155/c292293b-2967-436c-ba42-5a62854480c6)

### Environment

windows 11

### Angular version

17.1.2

### PrimeNG version

17.5.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.10.0

**Comment by Kombuchelada** [comment]
I'm experiencing this issue as well. It's preventing me from upgrading my applications to v17.

**Comment by cervenf** [comment]
@Kombuchelada is version 16 working correctly? (I'm new to primeng). Thank you.

**Comment by stevenpotts** [comment]
@cervenf if you are getting the same thing as me, then no, it doesn't work in 16 or 17, this has held me back to Angular 15 for so long now :( it gets harder and more problematic to upgrade the more versions of angular there are, and yet using Prime NG is really making things awkward now, its a lot of work to move away from it in my application, but waited months and we have not heard anything.
I don't think I am doing anything wrong? it works fine in v15.
The value gets stored in the form value fine, but the dropdown loses the selected value label.

My only option is waiting, or maybe finding a third party dropdown component.
here you can see the broken one when selected, and the one with its placeholder before selection.

![image](https://github.com/primefaces/primeng/assets/133002195/e0dc5ec3-ca21-4b15-996e-3a9653a079a5)


`
<p-dropdown 
                        styleClass="w-100"
                        formControlName="producerOption"
                        [options]="ddlProducerOptions" 
                        optionValue="_id" 
                        optionLabel="contactKnownas" 
                        placeholder="Producer:" 
                        (onChange)="onProducerSelected($event)"
                        [filter]="true"
                        filterBy="contactKnownas"
                        [showClear]="true"
                        >
</p-dropdown>
`

**Comment by MaciejSzczurek** [comment]
This error occurs for many developers, myself included. It is related to the programmatic setting of the form value, which destroys the user interface. A simple example edit shows what this error looks like. A quick workaround for this problem is to reset this value u set it again with some delay, but this is a very ugly solution.

https://stackblitz.com/edit/xbdmk9?file=src%2Fapp%2Fdemo%2Fdropdown-reactive-forms-demo.ts

**Comment by stevenpotts** [comment]
yes i see your right about the reset value thing, the first one i select is broken, if i change it again it works.

**Comment by stevenpotts** [comment]
Maybe some good news for you guys. 
17.3.1 works for me -- when the latest 17.5.0 does not!

so if you want to try this if you need angular 17 like me, then 
uninstall with npm uninstall primeng
then install with npm i primeng@17.3.1

**Comment by stevenpotts** [comment]
agree, it has to be some issues with versioning and how different members of team are working off it i presume.
v16 was always broken for me, i could never get it to work, then it appears they fixed it for early versions of 17 then its broke again in 17.5, in what looks like to be exactly the same problem.

**Comment by rbbp23** [comment]
Yep, broken here as well.
It seems the dropdown and autocomplete components get more and more side effects with each release :(

**Comment by biswasSaumyadip** [comment]
In version 17.6 dropdown is working fine seems.

**Comment by biswasSaumyadip** [comment]
In version 17.6 the dropdown is working fine.

**Comment by cetincakiroglu** [comment]
Hi,

This issue is fixed and doesn't exist in v17.6.0, you can see here https://stackblitz.com/edit/oewvp1?file=src%2Fapp%2Fdemo%2Fdropdown-reactive-forms-demo.ts

Closing the issue since it's invalid with the latest version. Thanks for reporting the issue.
