### ISSUE TITLE
Component: Chips | A chip generated on pressing enter key to confirm input

### ISSUE THREAD

**Issue by zeatan** [primefaces/primeng#14720]
### Describe the bug

As per the video below, when pressing the enter key to confirm input, a new chip is created.
Before version 16.7.0, this behavior did not occur.

https://github.com/primefaces/primeng/assets/6779963/2f7d029b-8862-4ee3-9542-59ea84ee5ca8

### Environment

win11/chrome latest, macOS12/chrome latest

### Angular version

17.1

### PrimeNG version

17.5.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.19.0

### Browser(s)

Chrome 121

### Expected behavior

Not generate chip on pressing enter key to confirm input.

For example, use `event.keyCode === 13` intead of `event.code === 'Enter'`

**Comment by cetincakiroglu** [comment]
Pressing enter adds new chip. It was working in the same way before https://www.primefaces.org/primeng-v15-lts/chips#basic

Could you please provide stackblitz example so we can identify the issue clearly?

**Comment by zeatan** [comment]
@cetincakiroglu 

I tried making it.
it cannot be reproduced without input conversion (such as JP/CN/KR languages using IME).

Ver 17.6.0 below, has this problem
https://stackblitz.com/edit/github-4qo4pk

Ver 16.6.0 below, is correct behavior.
https://stackblitz.com/edit/bq8963

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
