### ISSUE TITLE
Input Components: Input hover not displaying blocked cursor when input is disabled.

### ISSUE THREAD

**Issue by VA-Ansari** [primefaces/primeng#14735]
### Describe the bug

When Password input is disabled it is not showing the "not-allowed" type cursor when hovering, instead it shows only the default cursor.

### Environment

Angular

### Angular version

18

### PrimeNG version

17.5.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

Latest

### Steps to reproduce the behavior

1. Go to Disabled Password
2. Hover on the Disabled Password
3. It shows the default cursor.

### Expected behavior

1. Go to Disabled Password
2. Hover on the Disabled Password
3. It should be showing the block cursor.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
