### ISSUE TITLE
Multiselect: headerCheckboxViewChild not found

### ISSUE THREAD

**Issue by MaksymPlotnikov** [primefaces/primeng#14737]
### Describe the bug
![image](https://github.com/primefaces/primeng/assets/125256442/ba30d5d9-a090-4359-aae5-d53513f610cc)

ViewChild input `headerCheckboxViewChild` with  `appendTo="body"` and custom `filterTemplate` cannot be found since overlay is not a view child.
Possible solution:
Please add optional chaining inside `onToggleAll` method since `nativeElement` of undefined.
 ```
 DomHandler.focus(this.headerCheckboxViewChild?.nativeElement);
 ```
 
 And provide a possibility to pass this custom template checkbox as a `headerCheckboxViewChild` to component

### Environment

PrimeNG 17.5.0

### Angular version

17.1.1

### PrimeNG version

17.5.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.0

### Steps to reproduce the behavior

1. Add appendTo="body" attribute for multi-select and add  with custom `filterTemplate`
2. Click on 'Select all'  checkbox in the panel header.

Demo:
https://stackblitz.com/edit/8cwxx3

### Expected behavior

No errors in console

**Comment by VolodymyrKornetskyi** [comment]
The same issue...
