### ISSUE TITLE
Code example does not run in Codesandbox and Stackbliz

### ISSUE THREAD

**Issue by blackat** [primefaces/primeng#14740]
### Describe the bug

Hello,
I would like to play around with some example but they don't work anymore neither in Codesandbox nor in stackblitz probaby due to the same root cause.

In code Sandbox the error is:
```bash
$ ng serve
/bin/sh: 1: ng: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
```

Angular CLI is not found, after a while you get 502 Bad Gateway.

### Environment

CodeSandbox and Stackblitz

### Angular version

17.1.1

### PrimeNG version

17.5.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

Not found

### Steps to reproduce the behavior

Just take one of the example like https://codesandbox.io/s/vs6577

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
