### ISSUE TITLE
Component: Dropdown Typing in filter input displays placeholder instead of selected option

### ISSUE THREAD

**Issue by Draganlazarev90** [primefaces/primeng#14757]
### Describe the bug

When you have dropdown with filter, choose an option from the dropdown, then start typing in the filter results in showing the placeholder instead of the selected option.
[bug.webm](https://github.com/primefaces/primeng/assets/23295567/c35b9090-71cb-42e1-b69f-e9120d2a48dd)

### Environment

Primeng 17.6.0

### Reproducer

https://stackblitz.com/edit/h1xfk1?file=src%2Fapp%2Fdemo%2Fdropdown-reactive-forms-demo.html

### Angular version

17.0.6

### PrimeNG version

17.6.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.0

### Steps to reproduce the behavior

1. Create a dropdown with filter  and placeholder
2. Select option from dropdown
3. Start typing in the filter something different than the selected option
4. Placeholder is shown instead of the selected option

### Expected behavior

Show selected option instead of placeholder

**Comment by rosenthalj** [comment]
This bug is basically the same bug as #14596 which was closed in v17.5.0 and is now a bug in v17.6.0
