### ISSUE TITLE
Calendar Select Other Month issue

### ISSUE THREAD

**Issue by IvanPrytsko** [primefaces/primeng#1475]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/rAJ7bjA2tHkRoHiLYV5p?p=preview

**Current behavior**
1) If we select date from previous month - everything fine
2) If we select date from next month - actually selects date from previous.

**Expected behavior**
 If we select date from next month - date from next month should be selected.

**Minimal reproduction of the problem with instructions**
![calendar issue](https://cloud.githubusercontent.com/assets/4824000/20805976/0d7b3574-b80a-11e6-8bdd-313ad2989e95.PNG)
Click on (1) date - will be selected 30 JAN 2017 - OK
Click on (2) date - will select 03 JAN 2017 - Expected 03 MAR 2017

**What is the motivation / use case for changing the behavior?**
Wrong behavior

**Please tell us about your environment:**
Win10

* **Angular version:** 
2.2.1

* **PrimeNG version:**
1.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 54
Firefox 47
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.0.10

**Comment by upmauro** [comment]
#1450
