### ISSUE TITLE
Component: Dropdown: selected option is not displaying correctly.

### ISSUE THREAD

**Issue by D-Studio-21th** [primefaces/primeng#14753]
### Describe the bug

On selecting a value for the first time, the selected value is not displayed on UI. In subsequent selections, the previously selected value is being displayed.

![293031469-8e57de98-0907-4cc5-9864-3a83aee96ed0](https://github.com/primefaces/primeng/assets/37596709/0d804c95-cfcf-476a-a7a9-bd5c0cd6676a)

![293031470-6f7576ba-6726-466e-a74f-dfb17340f8b6](https://github.com/primefaces/primeng/assets/37596709/025e3b09-bc4a-48b6-9c32-ea8cf04b4127)

### Environment

Any

### Angular version

any

### PrimeNG version

older 16.4.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

any

### Browser(s)

any

### Steps to reproduce the behavior

1. Open https://stackblitz.com/edit/adtdqm?file=src%2Fapp%2Fdemo%2Fdropdown-basic-demo.html
2. Open console log 
3. Select any option in drop-down
4.

**Comment by cetincakiroglu** [comment]
Hi,

Try to receive updated value from the event itself, onChange event emits the updated value. Component updates selectedOption afterward. selectedOption is a variable that we use within the component.

**Comment by D-Studio-21th** [comment]
Hello, I need selectedOption because of value don`t show all data. How can I get data from [{label: 'test', value: "test", data: ["some data"]}] e.g. It`s working in primeng <= 16.4.2
