### ISSUE TITLE
Component: Dropdown

### ISSUE THREAD

**Issue by NrujalSharma** [primefaces/primeng#14751]
### Describe the bug

Selected values in dropdowns are not rendering within the input box of a dropdown but on expanding options the option shows selected.

Dropdown options come from a signal and dropdown value comes from a separate API call
The behaviour is unpredictable as the value renders sometimes and sometimes it doesn't. Looks like some race condition issue.

PFA

![image](https://github.com/primefaces/primeng/assets/48145591/14ded4bf-db8b-4327-a191-36ae1add1b3b)
![image](https://github.com/primefaces/primeng/assets/48145591/330e7126-59cd-4aff-8930-32b757625d50)

### Environment

Windows 11

### Angular version

~17.0.10

### PrimeNG version

^17.3.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.0

### Browser(s)

Chrome, Edge

### Expected behavior

If a dropdown field has a value assciated with it, the selected value should be rendered within the input box

**Comment by laurz94** [comment]
I am having a similar problem. The dropdown knows which option is selected, but the value is not displayed when selected.

"@angular/core": "^16.2.10",
"primeng": "^16.9.1",
"typescript": "~4.9.5"

**Comment by laurz94** [comment]
Works in 16.6. Breaks in 16.7

**Comment by cetincakiroglu** [comment]
Hi,
Could you please share a stackblitz example so we can identify the issue?

**Comment by NrujalSharma** [comment]
@cetincakiroglu 
Upgrading to 17.6.0 fixed the issue for us

**Comment by cetincakiroglu** [comment]
Hi @NrujalSharma,

Thanks a lot for the feedback, I'm closing the issue since it doesn't exist anymore.
