### ISSUE TITLE
Component: Attribute pReorderableRowHandle not working in span and i

### ISSUE THREAD

**Issue by amrud** [primefaces/primeng#14761]
### Describe the bug

Getting error when run unit test with the attribute pReorderableRowHandle
 
Error: NG0303: Can't bind to 'pReorderableRowHandle' since it isn't a known property of 'i' (used in the 'CustomComponent' component template).
        1. If 'i' is an Angular component and it has the 'pReorderableRowHandle' input, then verify that it is a part of an @NgModule where this component is declared.
        2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.
        error properties: Object({ code: 303 })
        Error: NG0303: Can't bind to 'pReorderableRowHandle' since it isn't a known property of 'i' (used in the 'GridCellFormattingComponent' component template).
        1. If 'i' is an Angular component and it has the 'pReorderableRowHandle' input, then verify that it is a part of an @NgModule where this component is declared.
        2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

### Environment

Windows

### Angular version

17.1.2

### PrimeNG version

17.5.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.0

### Steps to reproduce the behavior

Run unit test, it will throw this error Can't bind to 'pReorderableRowHandle' since it isn't a known property of 'i'

### Expected behavior

Should not throw error, and can be use within span and i

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
