### ISSUE TITLE
How to set global configuration in Chart.js

### ISSUE THREAD

**Issue by blackat** [primefaces/primeng#14760]
### Describe the bug

Hello,
I am looking for a way to globally set the Chart.js configuration.
According to the [doc](https://www.chartjs.org/docs/latest/configuration) I should use `Chart.defaults` but I don't have a way to get a reference to the object Chart using `p-chart`.

- Is it something not documented?
- Any idea or workaround?

Thanks :-)

### Environment

MacOsx

### Angular version

17.1.1

### PrimeNG version

17.5.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.3.0

### Browser(s)

Chrome

**Comment by lukasmatta** [comment]
Hey @blackat,

I think you can access the `Chart` object by importing it, just use `import { Chart } from 'chart.js';`
