### ISSUE TITLE
Component: Table cell-edit with p-calendar

### ISSUE THREAD

**Issue by erber014** [primefaces/primeng#14774]
### Describe the bug

When using p-calendar in a p-table with cell-edit the calendar pop-up does not open up correctly.
![image](https://github.com/primefaces/primeng/assets/43607100/609ea319-e51e-4d05-b9b8-222648a620b8)
As can be seen in the above screenshot, the pop-up opens "inside" the table with scrollbars horizontally and vertically which partially obscures/hides the pop-up depending on how much initial space the table is taking up.

### Environment

PrimeNG 17.6.0, modified stackblitz of Table-components cell-edit demo.

### Reproducer

(https://stackblitz.com/edit/r8c8lb?file=package.json)

### Angular version

17.05

### PrimeNG version

17.6.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.0

### Steps to reproduce the behavior

Click on a cell in the column farthest to the right (calendar). The pop-up where you can select a date opens "inside" the table, causing scrollbars to appear and hiding part of the pop-up.

### Expected behavior

When clicking on a p-calendar inside a cell-editable p-table the pop-up should open "over" the table so it is fully visible/usable.

**Comment by erber014** [comment]
Can just mention that I have the same problem with dropdowns (haven't tried multiselects but this might not work well either).

**Comment by ordorub** [comment]
You should add appendTo="body" to your calendar
![1](https://github.com/primefaces/primeng/assets/2127693/16b2f90e-f322-4c95-9928-b00fb1701dca)
