### ISSUE TITLE
p-inputNumber: value does not update when typing with @testing-library/user-event

### ISSUE THREAD

**Issue by angelo-v** [primefaces/primeng#14776]
### Describe the bug

When typing into a p-inputnumber field using @testing-library/user-event (`userEvent.type(input, '42');`) the value does not update

### Environment

jest, testing-library, angular, primeng

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-xzt6ad?file=src%2Fprimeng-form.component.spec.ts

### Angular version

17.1.2

### PrimeNG version

17.5.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.10.0

### Steps to reproduce the behavior

Run the tests in the stackblitz reproducer

### Expected behavior

This should work:

```
  it('userEvent should change p-inputnumber value', async () => {
    const renderResult = await render(PrimeNgFormComponent, {});
    const input = screen.getByLabelText('Age');
    await userEvent.type(input, '42');
    expect(input).toHaveValue('42');
    expect(renderResult.fixture.componentInstance.form.value.age).toEqual(42);
  });
```

**Comment by jadir-junior** [comment]
I create a little helper with the jonaths code


```
import { fireEvent } from '@testing-library/angular';

export class UserEvent {
  static typeNumber(
    element: Element | Node | Document | Window,
    number: number
  ) {
    if (number.toString().length > 1) {
      const numbers = number.toString().split('');
      numbers.forEach((number) => this.keyPress(element, number));
      return;
    }

    this.keyPress(element, number.toString());
  }

  private static keyPress(
    element: Element | Node | Document | Window,
    number: string
  ) {
    fireEvent.keyPress(element, {
      code: `Digit${number}`,
      key: number,
      keyCode: number.codePointAt(0),
    });
  }
}

```
in tests

```

 UserEvent.typeNumber(prepTimeHoursInput, 1);
 UserEvent.typeNumber(prepTimeMinutesInput, 30);

```

**Comment by guilhermetod** [comment]
Same here, but I only caught this when migrating from Jasmine to Jest. Everything was working fine with jasmine, but it showed up only on jest

**Comment by askberentsen** [comment]
It is because testing-library do not support UIEvent.which and KeyboardEvent.keycode, as both are deprecated (https://github.com/testing-library/user-event/releases/tag/v14.0.0), while in `onInputKeyPress` it checks for those, rather than checking KeyboardEvent.key.
I've opened a PR that i hope will resolve the issue: https://github.com/primefaces/primeng/pull/16863

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
