### ISSUE TITLE
Table: ColumnFilters are applied even before Apply button was clicked.

### ISSUE THREAD

**Issue by BergkampHUN** [primefaces/primeng#14777]
### Describe the bug

There is an inconsistency between the different type of inputs in the column filter menu.
The free text input are not applied until the user doesn't hit enter or the Apply button was clicked.
The checkbox and date selectors are immediately applied when the item selected.

The biggest problem with this is, if you type something into the free text input field, the you didn't apply but when you apply any other filter later, the text input remains there and will be applied with the new filter.

It would be great to have an option to disable the filtering before the Apply button was hit, and the inputs should be cleared when the apply button was not clicked.

### Environment

angular 17.0.5
primeng 17.6.0
node 20.9.0

### Reproducer

https://stackblitz.com/edit/i8xazh?file=package.json

### Angular version

^17.0.5

### PrimeNG version

17.6.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.9.0

### Steps to reproduce the behavior

1. Open the column filter menu for the "Name" column
2. Type "James" into the input field
3. Don't hit enter or click on Apply
4. Click to the second column filter button
5. Type "Egypt"
3. Don't hit enter or click on Apply
4. Click outside of the menu then it's gonna be closed.
5. The filter buttons for the first two columns are giving back false state, because they are active like there is an active filtering, but in reality nothing was filtered yet.
6. Click the filter button for the "Date" column.
7. Select any date
8. After the date selection the filters are applied automatically here.
9. You can see the filters for the first two columns are also applied when you selected a date (Basically when you apply any other filter)

### Expected behavior

When the filter input is filled but not applied would be great to clear the input field so when other fields are filtered this filter will not be applied silently.
Would be also great to be able to remove the "Apply" button, because it make no sense for example for Dates or MultiSelect types, when the selection applies everything automatically.

**Comment by ShpetimLatifi** [comment]
I'm having the same issue

**Comment by leidenzer** [comment]
I'm having the same issue. There should be a consistency accross all the filter types. I think that filter should be applied when the button apply is clicked or enter key is hitted. Also, the focus of filter button gets actived once text or bumber are entered in the input filed even if the data is not filtered. I beleive that the focus should be actived only if data is filtered.

**Comment by mahesh-mathew** [comment]
I am also having the same issue. Clearing date filter is also not clean.

**Comment by runerand** [comment]
Same/similar issue: for text filter, enter key (with focus in filter value) performs the filtering, but if user then clicks outside the filter dialog, the filter is removed.

**Comment by ray-kay** [comment]
Bug still present in latest version 18.0.0 stable
