### ISSUE TITLE
Getting a handle of the filtered data from p-datatable

### ISSUE THREAD

**Issue by ASK83** [primefaces/primeng#1478]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
The filtered data is not being sent back from the onFilter() of p-datatable. This is formal request of my former post on the forum. 
http://forum.primefaces.org/viewtopic.php?f=35&t=47092&p=147460&hilit=filtered+data#p147460

**Expected behavior**
Filtered data comes back with onFilter() of the p-datatable.

**What is the motivation / use case for changing the behavior?**
Having the filtered data back from the component would be better because the data has been already been filtered once and I can make a summary of the filtered that in my app without filtering the data again for better performance.

**Please tell us about your environment:**
Not relevent

Thanks for consideration!

**Comment by elpendor** [comment]
Another vote for this.

**Comment by cagataycivici** [comment]
onFilter event gives it as event.filteredValue.
