### ISSUE TITLE
Chart is not drawing when the data attribute is dynamic

### ISSUE THREAD

**Issue by unaor** [primefaces/primeng#1479]
I'm implementing a chart component that is drawing fine when i define the data attribute as a normal array of numbers
However my data for that component comes from a service (observer) so when is the chart is first drawn, no data is available and it draws blank.
I've read in the documentation the following "Due to complexity of charts.js, change detection is not available and when the data changes, you need to call refresh() method manually."

However i don't know how to get a reference of the chart object from within my controller
I've tried the following but i get undefined for chart
`  ngAfterViewInit(chart: UIChart) {
    this.drawGraph(this.graphData);
  }`

**Comment by garethlewis** [comment]
You're probably going to need a viewchild reference.

**Comment by unaor** [comment]
Yes i actually reference the chart with viewchild, figured it out this night, yet when i call its refresh method nothing happens. Even weirder once view is rendered,if i invoke the update method from the ui, it works
Update() { this.myChart.refresh()}

**Comment by cesarrew** [comment]
#1422

**Comment by unaor** [comment]
@cesarrew thanks i did that and it worked, seems kinda hack but works

**Comment by Mrtcndkn** [comment]
It is now fixed with https://github.com/primefaces/primeng/issues/2235
