### ISSUE TITLE
Component: Multiselect onChange not called

### ISSUE THREAD

**Issue by tsepton** [primefaces/primeng#14807]
### Describe the bug

Using a the [MultiSelect](https://primeng.org/multiselect) component, the `onChange` callback does not emit when selecting all values through the upper checkbox that serves as a shortcut to select/unselect all values.

### Environment

Ubuntu 23.10
Angular v17
Primeng 17.3.2

### Angular version

17.0.7

### PrimeNG version

17.3.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v18.16.1

### Steps to reproduce the behavior

template: 
```html
<p-multiSelect
    [options]="mockupData"
    (onChange)="onChangeCallback($event)"
    (onSelectAllChange)="onSelectAllChangeCallback($event)"
></p-multiSelect>
```

typescript:
```
protected onChangeCallback(event: any): void {
      console.log(event) // called only when a particular value is checked or unchecked
      // selecting or deselecting all values through the shortcut checkbox does not call the line above
}

protected onSelectAllChangeCallback(event: any): void {
      console.log(event) // not called neither when selecting or deselecting all values through shortcut checkbox
}
```

### Expected behavior

`onChange` (i.e. "[_Callback to invoke when value changes_](https://primeng.org/multiselect#api.multiselect.emitters.onChange)") and `onSelectAllChange` (i.e "[_Callback to invoke when all data is selected_](https://primeng.org/multiselect#api.multiselect.emitters.onSelectAllChange)") events should emit as the upper checkbox is clicked or unclicked.

**Comment by jandersen-yahoo** [comment]
We are also experiencing this with any version higher than 16.6.0.  Looking at the change log between 16.6.0 and 16.7.0, there were three commits with MultiSelect.  One [commit ](https://github.com/primefaces/primeng/commit/c842b8d343e79847853c9c33135a0ad8bdf2f573) has to do with the checkbox in the header, which I assume is the select all functionality.  Perhaps this is where the problem was introduced?

**Comment by rosenthalj** [comment]
I created pull request #14826 which fixes this issue.  PR #14826 supersedes PR #14604
