### ISSUE TITLE
Step Component doesn't fire activeIndexChange event when works with routing

### ISSUE THREAD

**Issue by matte0080** [primefaces/primeng#14816]
### Describe the bug

Step Component doesn't fire activeIndexChange event when works with routing.

### Environment

VsCode
MacOS

### Angular version

17.0.8

### PrimeNG version

17.4.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.10.0

### Browser(s)

Chrome 121

### Steps to reproduce the behavior

1. Go to [PrimeNg Steps](https://primeng.org/steps/seat#routing)
2. Edit the routing example and add (activeIndexChange)="onActiveIndexChange($event)" 
3. In component add onActiveIndexChange methdo to print out $event value.

### Expected behavior

onActiveIndexChange fired when change step with routing

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
