### ISSUE TITLE
Checkbox: Disabled checkboxes appear writable until they receive focus

### ISSUE THREAD

**Issue by LoaderB0T** [primefaces/primeng#14819]
### Describe the bug

When using a p-checkbox with reactive forms, the disabled state of the formControl is not represented by the ui (hover effects, pointer cursor, etc) until the checkbox is clicked or you switch the focus to it by pressing the tab key. Only then the checkbox gets the correct css classes to show the disabled state.

Example gif of this behavior:
<img src="https://i.imgur.com/Z7bROso.gif">

My template code for the checkbox:

```html
    <p-checkbox
      [tabindex]="0"
      [formControl]="formControl"
      [binary]="true"
      inputId="my-id"
    ></p-checkbox>
```

Can be reproduced easily in the stackblitz I sent. Was working in 17.3.3

### Environment

-

### Reproducer

https://stackblitz.com/edit/github-p6bxec

### Angular version

17.1.2

### PrimeNG version

17.7.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.9.0

### Browser(s)

Chrome 121

**Comment by vaibhav65577** [comment]
Hello @LoaderB0T  @mehmetcetin01140 @vincent 
Is this issue fixed?
I install latest version 17.13.0 and still face same issue.
```
<p-checkbox
    *ngIf="menu.allowAdd"
    [ngClass]="menu.isAddDisabled ? 'disabled' : ''"
    [disabled]="menu.isAddDisabled"
    [binary]="true"
    formControlName="add"
    [attr.disabled]="menu.isAddDisabled"
  ></p-checkbox>
```

with this same code, I was able to disable this checkbox in version 17.7.0 but not able to disable the same checkbox in 17.13.0 or in any version after 17.7

**Comment by LoaderB0T** [comment]
@vaibhav65577 What you describe seems to be a different issue. My issue was that the disabled state from the formControl was not correctly detected by the control, your issue sounds like the "disables" input binding of the checkbox does not get detected when using form Controls. AFAIK using [disabled] together with a formControl is deprecated by angular.

My issue has indeed been fixed by the referenced PR.

You could try to handle the disabled state in the formControl itself instead of the binding in the template.
