### ISSUE TITLE
Chips improvements

### ISSUE THREAD

**Issue by FallenRiteMonk** [primefaces/primeng#1482]
Would it be possible to extend the chips module by following functionality:
 - custom seperator keys (ex.: use space to enter a chip)
 - custom validators (ex.: a chip may not contain sybols like !"§$%&...)
 - transformations on input (ex.: make string lowercase on input)
 - prevent duplicates (same inputs are ignored)
and change/fix the following:
 - entering a blank chip results in chip height not being same as the rest of chips
 - remove the x to delete a chip if disabled is activated

**Comment by wujitouch** [comment]
For the blank chips issue override the .ui-chips-token-label display value, like so:

.ui-chips-token .ui-chips-token-label {
    display: inline-block;
}

**Comment by wujitouch** [comment]
https://github.com/primefaces/primeng/pull/1588

**Comment by cagataycivici** [comment]
Please create a separate ticket for each one as the current ticket is too broad, better to divide into smaller pieces to manage easier.
