### ISSUE TITLE
Dropdown: Options with long text overflow browser window

### ISSUE THREAD

**Issue by sandrotonon** [primefaces/primeng#14834]
### Describe the bug

If a dropdown option is to long to be displayed entirely, it overflows the browser-window and doesn't break line

Screenshot:
<img width="697" alt="Bildschirmfoto 2024-02-19 um 08 55 44" src="https://github.com/primefaces/primeng/assets/3889326/96ec62d5-7862-4b18-838d-79c28574d97f">

### Environment

Tested on MacOS Sonoma 14.3

### Reproducer

https://stackblitz.com/edit/sdgdep?file=package.json

### Angular version

17.0.5

### PrimeNG version

17.7.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

unknown

### Browser(s)

Firefox 122.0

### Expected behavior

The dropdown options should wrap and be displayed entirely

**Comment by mehmetcetin01140** [comment]
Hi,

You can use itemTemplate to customize as you wish, here is a basic example: https://stackblitz.com/edit/bmatbx-pykeza?file=src%2Fapp%2Fdemo%2Fdropdown-template-demo.html 

Closing the issue since there isn't a bug or defect.

**Comment by FatimaMedusa** [comment]
I still have this issue

**Comment by 3vinicius** [comment]
@mehmetcetin01140 Thank you, it completely solved my problem.

**Comment by GiaBaorr** [comment]
Thank you it solved my problem:
```
<p-select
        [options]="emissionFactors"
        optionLabel="nameEN"
        optionValue="id"
        formControlName="emissionFactorID"
        class="w-full"
      >
        <ng-template let-factor pTemplate="item">
          <div class="flex align-items-center gap-2">
            <div style="white-space: normal;">{{ factor.nameEN }}</div>
          </div>
        </ng-template>
</p-select>
```
