### ISSUE TITLE
[TreeTable] Documentation

### ISSUE THREAD

**Issue by jdpearce** [primefaces/primeng#1484]
There's a problem with the docs in `showcase/demo/treetable/treetabledemo.html`

On lines 477 and 480, where it says `let-col #node="rowData"` it should instead read `let-node="rowData"`.

If you do actually use the form currently shown, you get an error - `There is no directive with "exportAs" set to "rowData"`

**Comment by dzhavat** [comment]
Have you considered making a PR? It's a perfect case for contributing something :)
Anyway I fixed that in #1488 ;)

**Comment by jdpearce** [comment]
Thanks, I did consider it but didn't have time yesterday :(  I also wasn't entirely sure which way the docs were going. i.e. whether the docs were wrong for the current version or right for the next version but the code hadn't caught up!

I was so rushed I even managed to mess up posting this issue! 😣 (Must have accidentally hit return or clicked somehow and it submitted before I was done - hence the errant "[" in the title)
