### ISSUE TITLE
Component: TitleHide p-fileUpload choose button

### ISSUE THREAD

**Issue by Hassanabdelqader** [primefaces/primeng#14840]
### Describe the bug

I want to Hide p-fileUpload choose button but us keep displayed even with ! important in css 
Any help with this

### Environment

Angular 

### Angular version

14.2.5

### PrimeNG version

9.1.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16

### Browser(s)

Chrome

**Comment by SoyDiego** [comment]
> ###
> 
> I want to Hide p-fileUpload choose button but us keep displayed even with ! important in css Any help with this

Try using `::ng-deep`

```css
::ng-deep .your-button{
   display none;
}
```

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
