### ISSUE TITLE
InputNumber: When used with Reactive Forms and an empty value, it does not have an empty value

### ISSUE THREAD

**Issue by codrut1** [primefaces/primeng#14845]
### Describe the bug

I want to use p-inputNumber and have the initial value empty, I use it in a react form and the initial control value is ''. I expected the initial value to be empty, not 0

### Environment

VS Code, Windows 10

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-5qaygy?file=src%2Fapp%2Fapp.component.html

### Angular version

17.0.0

### PrimeNG version

17.6.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Add reactive forms and p-inputNumber, with the control value set as ''
2. Make sure that [allowEmpty] is true on the input

### Expected behavior

I expect that the input will initially be empty, not display 0

**Comment by cetincakiroglu** [comment]
You're not even using reactive form in the example. There isn't a bug, please see the example: https://stackblitz.com/edit/fmccwf?file=src%2Fapp%2Fdemo%2Finput-number-reactive-forms-demo.ts,src%2Fapp%2Fdemo%2Finput-number-reactive-forms-demo.html

**Comment by MisooB** [comment]
It doesn't matter whether you use reactive form or not.

`<p-inputNumber [(ngModel)]="number"></p-inputNumber>`

will always show 0 instead of empty field, when the number is set to empty string. (`number = '' `)

Is this not a bug?
