### ISSUE TITLE
p-pickList: Content-Security-Policy throws a inline-style error when [responsive]="true"

### ISSUE THREAD

**Issue by victorgawk** [primefaces/primeng#14847]
### Describe the bug

If Content-Security-Policy header is enabled and the user tries to render a p-pickList with `[responsive]="true"`, the browser throws a  inline-style error.
Related:
#14584
#14846
#13438
#12787

### Environment

Add a CSP header enforcing style-src: 'self' in order to reproduce the error:
```html
<head>
<meta http-equiv="Content-Security-Policy" content="
    default-src 'self'; 
    script-src 'self' 'nonce-randomNonceString';
    style-src 'self' 'nonce-randomNonceString';">
</head>
<body>
<app-root ngCspNonce="randomNonceString">
   ...
</app-root>
</body>
```

### Angular version

17.2.1

### PrimeNG version

17.7.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.0

### Browser(s)

Chrome 121.0.6167.185

### Steps to reproduce the behavior

1. The error happens when the `<p-pickList>` is loaded / initialized.

### Expected behavior

Should have an option to add a nonce attribute to the component that is receiving the style, or not adding style at all.

**Comment by jlfrances** [comment]
Indeed, I have the same error. 

It's happening when setting styles to make the data table responsive.
It happens when it appends this InnerHTML, exactly here:

<img src="https://github.com/primefaces/primeng/assets/36110804/e3e09cb6-67d6-4950-8574-d7c5b5b8661f" width="450">

**Comment by SoyDiego** [comment]
Any idea @cetincakiroglu @mehmetcetin01140.
Maybe you can give us an idea with this problem.

Thanks!! :)

**Comment by SoyDiego** [comment]
Hi @victorgawk did you have any solution?
Thanks!

**Comment by victorgawk** [comment]
unfortunately no 😢

**Comment by SoyDiego** [comment]
> unfortunately no 😢

Thanks for your reply. We have created a new issue giving more information and a reproducer here:
https://github.com/primefaces/primeng/issues/15911

Thanks!

**Comment by victorgawk** [comment]
I also had this problem with two other NPM components, each used a different solution to solve:

- ng-icons: added a `withContentSecurityPolicy()` config [issue](https://github.com/ng-icons/ng-icons/issues/92) [solution](https://github.com/ng-icons/ng-icons?tab=readme-ov-file#content-security-policy)
- codemirror: added a `EditorView.cspNonce.of("rAnd0mNonceVaue")` option to inform the nonce string [issue](https://codemirror.net/docs/ref/#view.EditorView^cspNonce) [issue](https://github.com/codemirror/dev/issues/395) [solution](https://codemirror.net/docs/ref/#view.EditorView^cspNonce)
