### ISSUE TITLE
Component: Autocomplete

### ISSUE THREAD

**Issue by rekna1** [primefaces/primeng#14848]
### Describe the bug

In previous version, when a space was entered, it would trigger a search. In current version it seems primeng does not search  (I can see in the code of primeng this has been added ). 
This is a breaking change, as we were relying in one particular case that space would trigger search. It would be better if primeng didn't change behaviour causing breaking changes. Instead provide a configuration option to specify whether or not to search on space, defaulting to the behaviour of the previous version (search on space)

### Environment

- windows 
- angular / primeng

### Angular version

17.0.7

### PrimeNG version

17.6

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.10.0

### Steps to reproduce the behavior

1. type space in autocomplete
2. no search is happing (was the case previous version)

### Expected behavior

When space is pressed , default behaviour should be search.
Provide configuration option to opt in for not searching on space, so default behaviour does not break.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
