### ISSUE TITLE
DropDown Accessibility Issue: Scrollable region must have keyboard access

### ISSUE THREAD

**Issue by HellinSunWTW** [primefaces/primeng#14852]
### Describe the bug

Click the dropdown to open the list -> Scan the page using Axe Dev Tools with dropdown menu open

The Axe Dev Tools for Accessibility is reporting the following issue: Scrollable region must have keyboard access

![image](https://github.com/primefaces/primeng/assets/152492138/4325da7c-7fcb-4d2a-b324-63e93bd5fe14)

Potential solution: Adding a tabindex="0" might fix this issue

### Environment

Windows 10

### Angular version

17.2.1

### PrimeNG version

17.7.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.0

### Browser(s)

Edge

### Steps to reproduce the behavior

1. Install the Axe Dev Tools for Accessibility plug-in.

2. Visit the PrimeNG dropdown page (https://primeng.org/dropdown) on Chrome/Edge browser.

3. Click to open any dropdown menu

4. Scan the page with Axe

**Comment by cetincakiroglu** [comment]
Hi,

Thanks for raising the issue.

Unfortunately, adding tabindex to the element with the .p-dropdown-items-wrapper class does not solve the problem and disrupts the component's current accessibility behavior, leading to a breaking change. We also use the same accessibility features in PrimeVue and PrimeReact. To avoid affecting our other Prime UI Libraries (PrimeVue & PrimeReact) and UIKit, the team will discuss this issue and make improvements accordingly. I am moving this issue to the next milestone until a decision is made.
