### ISSUE TITLE
Dropdown: TypeError: this.getOptionLabel(...).toLocaleLowerCase is not a function

### ISSUE THREAD

**Issue by shdb2** [primefaces/primeng#14865]
### Describe the bug

Declaring a dropdown with a filter or as editable with e.g. primitive number values (which are allowed according to the documentation), breaks the dropdown filter/edit option with the following error:

> ERROR TypeError: this.getOptionLabel(...).toLocaleLowerCase is not a function
    at _Dropdown.isOptionMatched (primeng-dropdown.mjs:2057:70)
    at primeng-dropdown.mjs:2033:101
    at Array.findIndex (<anonymous>)
    at _Dropdown.searchOptions (primeng-dropdown.mjs:2033:76)
    at _Dropdown.onEditableInput (primeng-dropdown.mjs:1632:26)
    at Dropdown_input_3_Template_input_input_0_listener (primeng-dropdown.mjs:142:37)

Same problem as in issue https://github.com/primefaces/primeng/issues/14370 and https://github.com/primefaces/primeng/issues/14682: Has not been fixed yet despite the other issues being closed.

### Environment

Chrome

### Angular version

17.2.x

### PrimeNG version

17.7.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.0

### Steps to reproduce the behavior

Stackblitz: https://stackblitz.com/~/github.com/shdb2/primeng-dropdown-test-v17

### Expected behavior

Filtering and editing should be possible.

**Comment by AndY322** [comment]
I have the same problem with p-multiSelect after updating on 17.7.0.

**Comment by kongshu612** [comment]
this should be a bug from primeng side. or it is a break change. you can bypass it by provide the **optionLabel**, **optionValue**. or if your options are string[], it works as expected
