### ISSUE TITLE
Better support of Angular animation system

### ISSUE THREAD

**Issue by Tuizi** [primefaces/primeng#1486]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Let's take the DataTable as an example, if I want to animate the row insertion I cannot.

**Expected behavior**
PrimeNG should be flexible enough to let us animate everything in the component

**What is the motivation / use case for changing the behavior?**
Angular 2 has a great Animation system that we cannot use with PrimeNG

**Comment by cagataycivici** [comment]
This is a general suggestion that does not specify a case so closing, we use animations internally such as dialog and will consider your feedback on how to expose parts that can be animated. Thank you.
