### ISSUE TITLE
ProgressBar: Material Theme not fully supported

### ISSUE THREAD

**Issue by mirinio** [primefaces/primeng#14868]
### Describe the bug

The value inside the progress-bar isn't shown.

### Environment

your website

### Angular version

17.2.1

### PrimeNG version

17.7.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. https://primeng.org/progressbar#basic
2. choose Theme => Material Design
3. Basic progress-bar value 50% isn't shown anymore

### Expected behavior

1. https://primeng.org/progressbar#basic
2. choose Theme => Material Design
3. Basic progress-bar value 50% shows in the center

**Comment by SoyDiego** [comment]
I don't know if this is a bug @mirinio 
Maybe PrimeNG team have created it like this because is like Material Design style.
If you [visit the documentation of Material Design](https://m3.material.io/components/progress-indicators/overview),  nowhere part has text in the progress bar.
