### ISSUE TITLE
Editor: Value is not set to `null` if quill content is e.g. `<h2><br></h2>` instead of `<p><br></p>`

### ISSUE THREAD

**Issue by dorthrithil** [primefaces/primeng#14864]
### Describe the bug

The primeng quill wrapper can correctly set the ng controls value to `null` in case the html content of quill is `<p><br></p>`.  However when pasting smth like `<h2>Title</h2>` and deleting it again, quills internal "empty" placeholder is not `<p><br></p>` but `<h2><br></h2>`. primeng[ only checks for the paragraph case](https://github.com/primefaces/primeng/blob/master/src/app/components/editor/editor.ts#L302), so this case is not recognized as empty and required validators that check for `''` or `null` don't work as expected.

I added a reproducer where I initialized the form with `<h2><br></h2>`. Pasting the content results in the same issue. Type something, delete it again: the `h2` stays and quill doesn't recognize the editor as empty.

### Environment

Quill 1.3.7

### Reproducer

https://stackblitz.com/edit/github-isihci-fen4k8?file=src%2Fapp%2Fapp.component.html

### Angular version

17.2.2

### PrimeNG version

17.7.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

Not applied

### Steps to reproduce the behavior

See reproducer

### Expected behavior

The wrapper recognizes actually empty content as empty and writes `null` to the controls value.

**Comment by ThoSap** [comment]
@dorthrithil can you try https://github.com/primefaces/primeng/releases/tag/17.18.3, now Quill 2.X.X (currently 2.0.2) is supported.
It could be that this fixes your issue, but I did not verify.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
