### ISSUE TITLE
Scrollbar Extending Beyond Table Body in PrimeNG p-table Component

### ISSUE THREAD

**Issue by vbnr** [primefaces/primeng#14862]
### Describe the bug

In the provided example from the PrimeNG p-table documentation, the scrollbar extends beyond the table body, appearing in area such as the table heading.

### Environment

- Angular version: 16.0.3
- PrimeNG version: 16.0.2
- Node version: 18.13.0
- Browser: Chrome 121.0.6167.185
- Windows 11

### Angular version

16.0.3

### PrimeNG version

16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.13.0

### Browser(s)

Chrome 121.0.6167.185

### Steps to reproduce the behavior

1. Visit the [PrimeNG p-table documentation](https://www.primefaces.org/primeng-v16-lts/table#vertical-scroll), Section **Scroll/Vertical Scroll**
3. Review the example demonstrating a table with a predefined scrollHeight making the header section sticky.

Snippet of the example:
`<p-table [value]="customers" [scrollable]="true" scrollHeight="400px" [tableStyle]="{'min-width': '50rem'}">
`

Screenshot:
![image](https://github.com/primefaces/primeng/assets/33627564/88258487-d423-442c-822a-9b2ff1456ead)

### Expected behavior

The scrollbar should be within the body of the table and should not extend beyond it. The header section should remain sticky as the user scrolls through the table content.

**Comment by vsawant18** [comment]
I am also facing the same issue. Suddenly from the last 3 days, table column has not obeyed its width and taken size as the max length of text in that column and showing a horizontal scrollbar at the bottom. Please find the below screenshot.

![image](https://github.com/primefaces/primeng/assets/42796715/9248aedb-a475-42cb-ab2a-df711d11e8f7)

Angular: 14.1.0
primeng: 14.2.3
https://registry.npmjs.org/primeng/-/primeng-14.2.3.tgz

**Comment by robGardiner01** [comment]
I made a start on this and found that it can be fixed by altering the CSS of the table's head and body to "display: block" and setting a specific height for the body. However, this means the head and body columns do not line up unless their widths are explicitly set.
