### ISSUE TITLE
Button: styleClass

### ISSUE THREAD

**Issue by LucasAlumni** [primefaces/primeng#14870]
### Describe the bug

StyleClass does not work in PrimeNG 15 LTS

### Environment

https://www.primefaces.org/primeng-v15-lts/button#severity

### Angular version

15.2.9

### PrimeNG version

15.4.16-lts

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.0

**Comment by Vulps22** [comment]
I am seeing this as well

```html
<p-button styleClass="p-button-primary" label="Learn More" [raised]="true"></p-button>

<button pButton pRipple label="Join Now" icon="pi pi-discord" class="font-bold px-5 py-3 p-button-primary p-button-raised p-button-rounded white-space-nowrap"></button>
```

`StyleClassModule` and `ButtonModule` are both imported into the component

both of these elements have no color to them, they appear to be transparent, but all the other styling works fine

Angular: 17.1
PrimeNG: 17.8
Primeflex: 3.3.1

styles.css:

```css
@import "primeng/resources/themes/soho-dark/theme.css";
@import "primeng/resources/primeng.css";
@import "primeflex/primeflex.css";

```

**Comment by dobanisola-scottlogic** [comment]
@Vulps22 
I tried to reproduce the bug but could not. I used Stackblitz to attempt to reproduce the bug, see link below  
https://stackblitz.com/edit/angular-tjtjdp?file=src%2Fmain.ts

Could you check the link to see if I missed something? I'll like to fix this issue.

Thanks.
