### ISSUE TITLE
Emitters onBlur and onFocus in TriStateCheckbox

### ISSUE THREAD

**Issue by SzymonBol** [primefaces/primeng#14882]
### Describe the bug

hello, i noticed that there is no emitters in TriStateCheckbox for blur and focus event. There is only one emitter that emitts a value on change.
![image](https://github.com/primefaces/primeng/assets/66698077/1cb39fab-ee9a-4bf4-b177-85d6f68bea96)

### Environment

InteliJ EAP 2024

### Angular version

17.2.0

### PrimeNG version

17.7.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.0

### Browser(s)

Firefox

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
