### ISSUE TITLE
Calendar error on click of the years menu for selectionMode="range"-> cannot read properties of undefined (reading 'getFullYear' )

### ISSUE THREAD

**Issue by AntoninaY01** [primefaces/primeng#14881]
### Describe the bug

I have the following code in my html file:

<p-calendar dateFormat="dd.mm.yy"
                        #calendar
                        formControlName="dateRange"
                        selectionMode="range"
                        [readonlyInput]="true"
                        [minDate]="minStartDate"
                        [maxDate]="maxDate">
            </p-calendar>
            
When I haven't selected any dates from the calendar and I click on the years menu I get the following error in the console:
<img width="487" alt="Screenshot 2024-02-26 at 18 00 39" src="https://github.com/primefaces/primeng/assets/72103370/987c822a-12ff-40d6-917e-2634727beceb">

and the calendar looks like this:
<img width="613" alt="Screenshot 2024-02-26 at 17 50 25" src="https://github.com/primefaces/primeng/assets/72103370/fe7db84f-5544-418e-b1da-1aea9326f8bf">

If I have selected one date and then I click on the years menu it works just fine.

However this issue is only for the calendar in the 'range' selection mode.

Thanks in regards!

### Environment

web env

### Angular version

16.2.12

### PrimeNG version

16.9.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v18.17.0

### Browser(s)

Chrome

**Comment by demogorgon2222** [comment]
It happens if you initialize the control with empty array. It works fine if you initialize it with a null:
https://stackblitz.com/edit/github-xrcxa9
