### ISSUE TITLE
showing deprecated DOMNodeInserted on p-editor

### ISSUE THREAD

**Issue by the-dev-adonis** [primefaces/primeng#14885]
### Describe the bug

![Screenshot from 2024-02-26 18-24-11](https://github.com/primefaces/primeng/assets/153516858/f82978d7-8325-4cd5-83af-08c9e1df7f4d)

### Environment

prod and dev both

### Angular version

15.2.0

### PrimeNG version

15.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.1

**Comment by ThoSap** [comment]
@cetincakiroglu can be closed if https://github.com/primefaces/primeng/issues/14721 is done.

**Comment by ThoSap** [comment]
@cetincakiroglu you can close this issue, it was fixed in #14721
