### ISSUE TITLE
Button: Ripple animation not appear

### ISSUE THREAD

**Issue by ahmet-cetinkaya** [primefaces/primeng#14907]
### Describe the bug

I checked this button component in the [PrimeNG documentation](https://primeng.org/button#basic). The ripple animation appears in the document, but it doesn't appear in the [StackBlitz demo](https://stackblitz.com/edit/72rvez?file=src%2Fapp%2Fdemo%2Fbutton-basic-demo.html) or in my project either.

### Environment

I used StackBlitz demo in [PrimeNG documentation](https://primeng.org/button#basic).

### Reproducer

https://stackblitz.com/edit/72rvez?file=src%2Fapp%2Fdemo%2Fbutton-basic-demo.html

### Angular version

17.2.2

### PrimeNG version

17.8.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.0

### Browser(s)

Librewolf v120.0.1-1, Brave v1.63.165 Chromium: v122.0.6261.94, Chrome v122.0.6261.95

**Comment by psarno** [comment]
You have to inject an instance of `PrimeNGConfig `and set `ripple = true`.

This [fixes the demo example](https://stackblitz.com/edit/72rvez-mlqxfx?file=src%2Fapp%2Fdemo%2Fbutton-basic-demo.ts).

```
export class ButtonBasicDemo {
  constructor(private primengConfig: PrimeNGConfig) {
    this.primengConfig.ripple = true;
  }
}
```

**Comment by ahmet-cetinkaya** [comment]
> You have to inject an instance of `PrimeNGConfig `and set `ripple = true`.
> 
> This [fixes the demo example](https://stackblitz.com/edit/72rvez-mlqxfx?file=src%2Fapp%2Fdemo%2Fbutton-basic-demo.ts).
> 
> ```
> export class ButtonBasicDemo {
>   constructor(private primengConfig: PrimeNGConfig) {
>     this.primengConfig.ripple = true;
>   }
> }
> ```

Yes, this configuration is required. I knew the default value was true. Thanks.
