### ISSUE TITLE
Column Filter: Column Filter not hiding when filter is applied using "Enter" key and form field is focused

### ISSUE THREAD

**Issue by sulo1337** [primefaces/primeng#14910]
### Describe the bug

Column filter model is not hiding itself when a filter is applied using keyboard by hitting "Enter" key. 

Example:

```html
<p-columnFilter display="menu" [showOperator]=false [operator]="'and'" [maxConstraints]=1 [hideOnClear]=true [matchMode]="'contains'"></p-columnFilter>
```
When I keep pressing "Tab" to focus the "Apply" button then press enter, the filter modal hides itself. But it won't hide when "Enter" is pressed and focus is on the form element.

### Environment

PrimeNG Version: 16.4.1
Angular Version: 16.2.7
Node Version: 18

### Angular version

16.2.7

### PrimeNG version

16.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.19.0

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
