### ISSUE TITLE
Datatable Paginator custom css class

### ISSUE THREAD

**Issue by ebosantos** [primefaces/primeng#1492]
**I'm submitting a feature request**
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
By using datatable component and it's paginator, it isn't possible to set paginator css class, unless you custom theme css file.

**Expected behavior**
It would be easier if a property could be exposed so a css class could be set, as it's possible when you use paginator without using datatable (I mean styleClass property).

**What is the motivation / use case for changing the behavior?**
Custom styling.

**Please tell us about your environment:**
MAC OS, WebStorm

* **Angular version:** 2.1.0

* **PrimeNG version:** 1.0.1

* **Browser:** Chrome Version 54.0.2840.98 (64-bit)

**Comment by cagataycivici** [comment]
```
<p-dataTable styleClass="my"
```

```
.my .ui-paginator {
   ....
}
```
