### ISSUE TITLE
Component: p-tree - spacebar key is hijacked by component and can't be used in custom node template

### ISSUE THREAD

**Issue by nvgame00** [primefaces/primeng#14927]
### Describe the bug

I use custom tree-item template for renaming tree nodes inline. The template renders <input> which will accept all the keyboard keys but not the spacebar because component uses it to de/select active node. I tried different things with stopPropagation without success, seems that component is listening for events at capture phase

### Environment

/

### Angular version

16.2.2

### PrimeNG version

17.8.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.9.0

**Comment by zachsteffens** [comment]
@nvgame00 I was able to get this to work with a keydown handler on the textbox in my template 

`handleKeyDown(event: Event): void {
    event.stopImmediatePropagation();
}`

I also tried `event.stopPropagation()`  which did not work.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
