### ISSUE TITLE
p-inputNumber: onInputBlur NPE

### ISSUE THREAD

**Issue by DbkMG** [primefaces/primeng#14928]
### Describe the bug

p-inputNumber onInputBlur-Method throws NPE if value==null

### Environment

chrome browser

### Angular version

17.2.3

### PrimeNG version

17.9.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.13.0

### Steps to reproduce the behavior

Reproducable in primeng showcase
1. go to https://primeng.org/inputnumber
2. scroll down to Float Label Example
3. focus inputfield
4. blur
5. check webdev-console

### Expected behavior

No NPE

**Comment by adcore-dev** [comment]
The problem here that model after blur become string. It wasn't happen before

**Comment by vigalo** [comment]
As @adcore-dev  said, the model becomes string. This problem broken my app and made me downgrade to 17.8.0 until fixed

**Comment by psarno** [comment]
I just came here to report this same thing, I couldn't find a suitable workaround.

I'm going to have to downgrade also.   It seems there is a brand new PR for it though.
