### ISSUE TITLE
Checkmark is visible when InputSwitch is set to checked in md-dark-theme

### ISSUE THREAD

**Issue by monacodelisa** [primefaces/primeng#14921]
### Describe the bug

The checkmark is visible when the input switch has a state of `checked` - md-dark theme

![image](https://github.com/primefaces/primeng/assets/64324417/5bd1110f-30a8-4e40-8784-9419e1ee61bf)

### Environment

localhost
chrome browser

### Angular version

17

### PrimeNG version

17

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

**Comment by cetincakiroglu** [comment]
Hi,

I've reverted your fix because we couldn't replicate the behavior. Could you please create a stackblitz example or a screen recording so we can identify the issue?

**Comment by cetincakiroglu** [comment]
I'm moving the issue to the next milestone until receiving a reproducer.

**Comment by monacodelisa** [comment]
@cetincakiroglu hi sorry I though I saw it as merged, I will try to stackblitz it, 
in the meantime I can show you the - [deployed app](https://angular-net-dashboards.netlify.app/sales)
and the relevant code in my [public repo for that app](https://github.com/monacodelisa/Angular-ASP.NET-Dashboard/blob/main/angular-dashboard/src/styles.scss)

**Comment by cetincakiroglu** [comment]
I don't see any issue in your app. Please let me know when the stackblitz is ready.

![Screenshot 2024-03-19 at 09 37 13](https://github.com/primefaces/primeng/assets/69278826/e376c702-893f-4d61-b731-db348c5c4b56)

**Comment by monacodelisa** [comment]
@cetincakiroglu I spotted the issue on my app, fixed it and then I decided to share the same fix over here. 

But between me documenting the issue, my initial PR getting merged with the styles I added, the issue marked as completed and now - relevant styles have been applied which were not present when I created the issue

![image](https://github.com/primefaces/primeng/assets/64324417/900c51f7-a4fe-44ed-9216-14cddf4a904f)

slightly different placement than what I submitted initially but same element, same issue and it's all fine now 👍

**Comment by cetincakiroglu** [comment]
Hi,

Is this issue really exist or still ongoing, or are you experiencing this problem due to a change in your code? The issue is not clear, and we cannot replicate it with the latest version (v17.11.0). Could you please share a StackBlitz example demonstrating the issue?

**Comment by monacodelisa** [comment]
@monacodelisa close it
