### ISSUE TITLE
p-editor: Does not work with SSR

### ISSUE THREAD

**Issue by armingdev** [primefaces/primeng#14931]
### Describe the bug

The application can't be built when I add p-editor component to the app. This started happening when I upgraded Angular & PrimeNG to the latest versions (from version 17 of angular and primeng).

```ts
ng build
An unhandled exception occurred: document is not defined
See "/private/var/folders/zz/6s9z09bj4wj_8zvyv132whv00000gn/T/ng-90AZGj/angular-errors.log" for further details.
```

This error is gone when I comment import of the p-editor component and HTML usage of it.

### Environment

MacOS Sonoma 14.3.1

### Angular version

17.2.3

### PrimeNG version

17.9.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.1

### Browser(s)

Latest FireFox

### Steps to reproduce the behavior

In the component:

```ts

import {EditorModule} from "primeng/editor";

  imports: [
    ReactiveFormsModule,
    InputTextModule,
    EditorModule,
    ToastModule,
  ],

```

in html:

```html

 <p-editor formControlName="topicContent" [style]="{ height: '320px' }" [styleClass]="'forum-post'"></p-editor>
 
 ```

### Expected behavior

Editor was working fine in Angular v16 with latest version of PrimeNG at that time.

**Comment by nejat-njonjo** [comment]
Wrap it inside `@if` block, I use it like that and it is working, [check the example here](https://github.com/primefaces/primeng/issues/15324#issuecomment-2120789413)
