### ISSUE TITLE
Multiselect: reset form doesn't clear the field

### ISSUE THREAD

**Issue by aboudard** [primefaces/primeng#14937]
### Describe the bug

When using the Multiselect PrimeNg component, with a custom `pTemplate="selectedItems"` if you want to reset the form, the value of the field is cleared, but the options remain even if they don't appear, they still are present in the component as `selectedOptions`. When using Array of string instead of Array of objects as the data of the Multiselect, the field doesn't get cleared, and values still show up.
The form is a Reactive Form.
When you get the Multiselect elements and clear the selectedOptions programatically, the fields get cleared as expected.
Selecting values :
![image](https://github.com/primefaces/primeng/assets/767767/3fe58a95-713b-4a15-9a15-46cfbed39951)
Reset ko :
![image](https://github.com/primefaces/primeng/assets/767767/41c9d8f0-49c3-4eb7-8f96-b9704b4b745f)
Reset ok :
![image](https://github.com/primefaces/primeng/assets/767767/2325637b-c2f9-4260-8f94-d3b4fa7880ee)

### Environment

Regular Angular CLI project with Angular 16 and PrimeNg 16, primeflex.

### Reproducer

https://stackblitz.com/edit/primeng-dropdown-demo-gjw8xm

### Angular version

16.2.12

### PrimeNG version

16.9.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16+

### Browser(s)

Chrome 122

### Steps to reproduce the behavior

In the Stackblitz : 
- Select values for the 3 multiselect.
- Click on the button `reset ko`
- The first field had the length of his previous selection, the second field still shows values, the third field is ok
- Select values for the 3 multiselect
- Click on the button `reset ok`
- All fields are cleared

DOM inspection on the first field :
![image](https://github.com/primefaces/primeng/assets/767767/46e57646-98e0-44ff-b292-3f7e5464e172)

### Expected behavior

On FormGroup reset, the fields should both be cleared of value, but also of display.

**Comment by mehmetcetin01140** [comment]
Hi,

Thanks for reporting the issue.
This issue has been fixed between your version and v17.16.1, please use the latest version to get the updates. 

Example with 17.16.1: https://stackblitz.com/edit/ayjjym?file=src%2Fapp%2Fmulti-select-basic-demo.ts

Closing the issue.
