### ISSUE TITLE
p-autocomplete completeMethod ignores minLength

### ISSUE THREAD

**Issue by rennechSICKAG** [primefaces/primeng#14938]
### Describe the bug

The primeng p-autocomplete component ignores the minLength when clicking the dropdown icon. The completeMethod event is fired anyway. 
In the documentation is written for the MinLength: Minimum number of characters to initiate a search. 
On clicking the Dropdown-Icon when the min length is not reached the completeMethod event is fired and the search will run anyway.

### Environment

Angular

### Angular version

17.1.1

### PrimeNG version

17.5.0

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Browser(s)

Firefox & Chrome

### Steps to reproduce the behavior

1. Go to the Documentation: https://primeng.org/autocomplete#dropdown
2. Click Edit With StackBlitz
3. Add a [minLength]="x" to the component
4. Click the search icon

### Expected behavior

The search-event is not fired, because the min Length is not reached

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Comment by mbortoli** [comment]
Still present as of version 17.18.15, but not sure it’s a bug, though. 

I believe it breaks when “completeOnFocus” is set to true, since the “search” function only checks the query length if the event source is an “input”.

Is this the expected behavior?
