### ISSUE TITLE
Table: Filter option operator is missing

### ISSUE THREAD

**Issue by mirinio** [primefaces/primeng#14932]
### Describe the bug

I set two filter menus using columFilters inside the p-table.
Using the menu I can select operator, value and mode.
When using table.filter(...) I can't select the operator which results in a wrong behavior if you want to preselect with OR instead of AND.
Stackblitz example: https://stackblitz.com/edit/99pbba?file=src%2Fapp%2Fdemo%2Ftable-basic-demo.ts

### Environment

{
  "name": "primeng-table-basic-demo",
  "description": "PrimeNG TableBasicDemo",
  "license": "MIT",
  "keywords": [],
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test"
  },
  "dependencies": {
    "primeng": "17.9.0",
    "@angular-devkit/build-angular": "^17.0.5",
    "@angular/animations": "^17.2.2",
    "@angular/cdk": "^17.2.1",
    "@angular/cli": "^17.2.1",
    "@angular/common": "^17.2.2",
    "@angular/compiler": "^17.2.2",
    "@angular/compiler-cli": "^17.2.2",
    "@angular/core": "^17.2.2",
    "@angular/forms": "^17.2.2",
    "@angular/platform-browser": "^17.2.2",
    "@angular/platform-browser-dynamic": "^17.2.2",
    "@angular/platform-server": "^17.2.2",
    "@angular/router": "^17.2.2",
    "chart.js": "3.3.2",
    "primeflex": "^3.3.1",
    "primeicons": "^6.0.1",
    "quill": "1.3.7",
    "rxjs": "~7.8.1",
    "tslib": "^2.5.0",
    "zone.js": "~0.14.0"
  }
}

### Angular version

17.2.1

### PrimeNG version

17.9.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

https://stackblitz.com/edit/99pbba?file=src%2Fapp%2Fdemo%2Ftable-basic-demo.ts

using Table => filter(value: any, field: string, matchMode: string): void; to set filters always adds AND operator.

### Expected behavior

using Table => filter(value: any, field: string, matchMode: string): void;  should have operator to set like in the filter Menu.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
