### ISSUE TITLE
Dropdown issue !! do not choose a default value from options.

### ISSUE THREAD

**Issue by liorZucker11** [primefaces/primeng#14948]
### Describe the bug

I have a dynamic dropdown that only appears if I select it, when it appears it appears without a default value and no value in the placeholder.

### Environment

vs code + angular 17.1.2 +nodejs 18.18 + typescript

### Angular version

17.1.2

### PrimeNG version

17.6

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18

**Comment by mehmetcetin01140** [comment]
Hi,

Could you please share a stackblitz example?

**Comment by liorZucker11** [comment]
I understood that a bug was opened for you about choosing the first option
as a default value, and then you fixed it so that it would no longer be
selected
 With us it was exactly the opposite
Anyway we got it sorted so no need
Thank you

‫בתאריך יום ב׳, 18 במרץ 2024 ב-15:52 מאת ‪Mehmet Çetin‬‏ <‪
***@***.***‬‏>:‬

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
