### ISSUE TITLE
PanelMenuSub: badge property not accessed properly in template

### ISSUE THREAD

**Issue by onetwotreefourfivesix** [primefaces/primeng#14956]
### Describe the bug

When using the PanelMenu with multiple levels, the badge is only shown on the header level.

In the template for PanelMenuSub the property 'badge' is directly accessed on the processedItem object.
```
<span class="p-menuitem-badge" *ngIf="processedItem.badge" [ngClass]="getItemProp(processedItem, 'badgeStyleClass')">{{ getItemProp(processedItem, 'badge') }}</span>
```
But the processedItem has no explicit property badge. The property badge should be accessed like in PanelMenu:
```
<span class="p-menuitem-badge" *ngIf="getItemProp(item, 'badge')" [ngClass]="getItemProp(item, 'badgeStyleClass')">{{ getItemProp(item, 'badge') }}</span>
```

### Environment

Windows

### Reproducer

https://stackblitz.com/edit/github-pf4huw

### Angular version

17.2.3

### PrimeNG version

17.8.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.11.1

### Steps to reproduce the behavior

Create PanelMenu with one PanelMenuSub.
Expand PanelMenu to show PanelMenuSub.
No badge is shown in PanelMenuSub.

### Expected behavior

The badge is shown for every level of child items.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
