### ISSUE TITLE
Dropdown loses focus in accordion when using arrow keys

### ISSUE THREAD

**Issue by spahno** [primefaces/primeng#14953]
### Describe the bug

After the update to PrimeNG 17.x.x the dropdowns, that are placed in an accordion, are losing focus when using the arrow keys to navigate through the dropdown options. 

It works for selecting the first option, but after that, the dropdown loses focus and the accordion tabs are focused instead.
I created a blank sample app with the most recent Angular & PrimeNG versions and could verify this behavour.

```
<p-accordion [activeIndex]="0">

    <p-accordionTab header="Header I">

        <p-dropdown [options]="cities" [(ngModel)]="selectedCity" optionLabel="name" [showClear]="true" placeholder="Select a City"></p-dropdown>

    </p-accordionTab>

</p-accordion>
```

### Environment

```
"dependencies": {
    "@angular/animations": "^17.0.7",
    "@angular/common": "^17.0.7",
    "@angular/compiler": "^17.0.7",
    "@angular/core": "^17.0.7",
    "@angular/forms": "^17.0.7",
    "@angular/platform-browser": "^17.0.7",
    "@angular/platform-browser-dynamic": "^17.0.7",
    "@angular/router": "^17.0.7",
    "@ngrx/effects": "^17.0.1",
    "@ngrx/store": "^17.0.1",
    "@ngrx/store-devtools": "^17.0.1",
    "@ngx-translate/core": "^15.0.0",
    "@types/node": "^20.1.4",
    "lodash-es": "^4.17.21",
    "primeflex": "^3.3.0",
    "primeicons": "^6.0.1",
    "primeng": "^17.9.0",
    "rxjs": "^7.8.1",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.2"
  }
```

### Angular version

17.0.7

### PrimeNG version

17.9.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.19.0

### Browser(s)

Chrome 122

### Steps to reproduce the behavior

1. Click the p-dropdown
2. Press an arrow key until the dropdown loses focus
3. accordion tabs will be focused

### Expected behavior

The focus should stay within the dropdown option list.

**Comment by Alhajras** [comment]
I just filed this issue and I guess they are related!

https://github.com/primefaces/primeng/issues/15406
