### ISSUE TITLE
Table: pFrozenColumn freeze on right breaks with many cols

### ISSUE THREAD

**Issue by stefan-floeren** [primefaces/primeng#14955]
### Describe the bug

When freezing columns to the right, 1 or 2 columns work fine.

With more than 2 columns, things break in interesting ways:

- The header and first row have 2 frozen columns
- The second row has 3 frozen columns
- And so on until the maximum is hit:

![image](https://github.com/primefaces/primeng/assets/42731906/58e9056e-9e1d-4851-ac44-91ad60ef046d)

### Environment

Angular with primeng

### Reproducer

https://stackblitz.com/edit/v2qrkb?file=src%2Fapp%2Fdemo%2Ftable-frozen-columns-demo.html

### Angular version

17.2.2

### PrimeNG version

17.9.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

n/a

### Expected behavior

Frozen columns are consistent across all rows

**Comment by cetincakiroglu** [comment]
Hi,

This issue is fixed with the 17.15.0 release previous week. Here is the stackblitz example with 17.15.0 https://stackblitz.com/edit/v2qrkb-eg71l9?file=src%2Fapp%2Fdemo%2Ftable-frozen-columns-demo.ts

Closing the issue, thanks a lot for reporting!
