### ISSUE TITLE
{first} in currentPageReportTemplate of Paginator  doest not reset after new filter activated

### ISSUE THREAD

**Issue by Kexi2071** [primefaces/primeng#14952]
### Describe the bug

I use the following statement to show data
 <p-table #dt1 [value]="serverList"  [lazy]="true" (onLazyLoad)="loadServers($event)" 
        [rows]="10" [totalRecords]="totalRecords" [paginator]="true" responsiveLayout="scroll"
        [showCurrentPageReport]="true" currentPageReportTemplate=" {first}-{last}  on  {totalRecords}"
  >
When I go to next page, the {first} is changed successfully.When I reload loadServers() using new filter, the data what are displayed are changed successfully, as same as {last} and {totalRecords}. However, {first} does not not changed to 1, it is stuck on last value.

### Environment

Ubuntu 22.04.3 LTS
node v20.11.0
Angular CLI: 17.0.10
npm 10.2.4

### Angular version

17.0.10

### PrimeNG version

17.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.0

### Browser(s)

chrome 122.0.6261.94

### Steps to reproduce the behavior

1.  insert the following statement into template html
 <p-table #dt1 [value]="serverList"  [lazy]="true" (onLazyLoad)="loadServers($event)" 
        [rows]="10" [totalRecords]="totalRecords" [paginator]="true" responsiveLayout="scroll"
        [showCurrentPageReport]="true" currentPageReportTemplate=" {first}-{last}  on  {totalRecords}"
  >
2. press next several times to get a   {first} value different with 1
3. reload data using different filter to get different dataset
4. you will see {totalRecords} 、{last} changed, however, {first} remain the old value.
 

### Expected behavior

when dataset changed,  {first} should be modified to 1

**Comment by sgomanf** [comment]
same issue

**Comment by mehmetcetin01140** [comment]
Hi,

Could you please share a stackblitz example?

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
