### ISSUE TITLE
TypeError: Click listener in primeng StyleClass throws a null object error

### ISSUE THREAD

**Issue by adri95cadiz** [primefaces/primeng#14963]
### Describe the bug

This happens sometimes when the click listener is triggered and the target is not in the dom anymore, I'm unable to reproduce this issue in a controlled environment as it only happens on complex interfaces with many mutations.

Nevertheless the error seems easy to fix as it is checking `if (this.target.offsetParent === null)` and it could be controlled if the target is not existant anymore to avoid triggering these kinds of issues.

### Environment

This is an angular application on PrimeNG version 17.8.0 but it has been happening since PrimeNG 16.

### Angular version

17.2.*

### PrimeNG version

17.*.*

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.8.1

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
