### ISSUE TITLE
DataGrid memory leak

### ISSUE THREAD

**Issue by bencameron00** [primefaces/primeng#1496]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

I am seeing this exact same issue when when using the DataGrid (https://github.com/primefaces/primeng/issues/488).

This is being hooked up to an RX Observable.
Is it possible that the DataGrid needs the same fix as you did to the DataTable?

When the browser is run for a long period of time it will eventually crash due to an out of memory error.
When the prime datagrid is not used there is no error in the browser and it runs happily.

**Expected behavior**
Long running browser to continue to update the DataGrid successfully.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows 10, node 7.0.0, webpack

* **Angular version:** 2.0.X
2.3.0 rc0

* **PrimeNG version:** 2.0.X
    "primeng": "1.0.1",
    "primeui": "4.1.15",

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome Version 55.0.2883.75 m
IE11
 
* **Language:** 
TypeScript 2.0.2
ES5

* **Node (for AoT issues):** `node --version` =   
Node 7.0.0

**Comment by cagataycivici** [comment]
I've reviewed the datagrid code and could not find a part that may cause a leak, do you know which data fills the memory causing the problem? That may give an idea.

**Comment by bencameron00** [comment]
Hi
We had a long running we app that updates the DataGrid every 10 seconds. We noticed that if we ran the application over night each morning the browser would have crashed due to an out of memory issue.
We spent a long time looking at our code but found that if we took out the DataGrid the problem went away.
We watched the memory usage in the Chrome dev tools and found that each time the garbage collector ran it left a bit of memory being used each time, this slowly increased until the browser broke.
It looks like a very similar issue to the link that I have posted above.
https://github.com/primefaces/primeng/issues/488

**Comment by bencameron00** [comment]
Hi @cagataycivici
Are you still considering this issue?

**Comment by dereklin** [comment]
@bencameron00 Maybe it's related to https://github.com/angular/angular/issues/13725
Have you tried a different grid for the auto refresh?  How is performance?

**Comment by cagataycivici** [comment]
Does it still happen with 2.0.1?

**Comment by dereklin** [comment]
Take a look at this: https://tranquil-harbor-5498.herokuapp.com/#/pd  chrome will crash saying it has run out of memory

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/MxSw4qOuwDfq7rLO7jrR?p=preview
