### ISSUE TITLE
PrimeNg: Upgraded to 16.9.1 showing node count along with label

### ISSUE THREAD

**Issue by Rishikap123** [primefaces/primeng#14971]
### Describe the bug

Upgraded primeng from 15.x to 16.9.1 where we can see node count is getting displayed along with label name.

### Environment

N/A

### Reproducer

https://www.primefaces.org/primeng-v16-lts/tree

### Angular version

16.2.12

### PrimeNG version

16.9.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14.2

### Browser(s)

All

### Steps to reproduce the behavior

1.Open https://www.primefaces.org/primeng-v16-lts/tree
2.Child node counts are in the labels . 

### Expected behavior

Child node count should not be visible along with labels.

**Comment by amonsour** [comment]
It was fixed in v17.2 I think.
