### ISSUE TITLE
p-table: Date filter not working

### ISSUE THREAD

**Issue by mkoestner** [primefaces/primeng#14987]
### Describe the bug

The date picker in a date filter in p-table is no longer working. I cannot switch to other months and the selection is not used as filter.

### Environment

you can see in the documentation:
https://primeng.org/table#filter

### Angular version

17.2.3

### PrimeNG version

17.10.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.17.1

### Steps to reproduce the behavior

https://primeng.org/table#filter

### Expected behavior

The date picker in a filter column should be usable and the selected date should be used as filter value.

**Comment by psarno** [comment]
I am experiencing this issue also.

When clicking on the month arrows, the calendar closes.  When clicking on the date, the calendar closes and the date is not set on the filter.

You can reproduce this on the PrimeNG documentatio page for table filter.  Try changing the month or picking a day.

https://primeng.org/table#filter

![image](https://github.com/primefaces/primeng/assets/18640860/bcfeb670-94e7-4348-aba8-ab5d56474a04)

**Comment by mkoestner** [comment]
I reverted now to 17.7.0.
In this release the calendar works. I think the bug was introduced in 17.8.0, perhaps with #14825

**Comment by sam-epner** [comment]
I am also experiencing this issue. 


https://github.com/primefaces/primeng/assets/107948225/78a5f195-4576-4c57-bc33-c759f13cbce2
