### ISSUE TITLE
Dropdown: dropdown would close overlay when selecting text on filter

### ISSUE THREAD

**Issue by Foxandxss** [primefaces/primeng#14990]
### Describe the bug

Using a dropdown (and the multiselect) with a filter. 

Say you want to hightlight the text of the filter to copy it and you do it with the mouse. You click in the filter input and you drag your mouse until you reach the end of the input and instead of stopping the dragging in the input itself, you unpress the button outside of it. If you do that the overlay will close and you will lose the highlight.

Related to #7515

### Environment

Happens on the docs itself.

### Reproducer

https://primeng.org/dropdown#filterbasic

### Angular version

17.0.0

### PrimeNG version

17.10.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.0.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

Open the demo page. Dropdown -> filter. Type something, click with the mouse at the end of the string, hold to select and unpress the button outside the overlay. It will close

### Expected behavior

Dropdown should remain open after clicking outside if there is selected text

**Comment by iMarti** [comment]
The AutoComplete component suffers from the same issue.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
