### ISSUE TITLE
Changelog: is broken due html tags in issue title

### ISSUE THREAD

**Issue by Kisters-BS** [primefaces/primeng#14992]
### Describe the bug

The html tags in the changelog issue title gets interpreted as real html tags: 
![image](https://github.com/primefaces/primeng/assets/84901454/4f366ad0-e630-4386-9d53-517b53387aca)

### Environment

primeNG project

### Angular version

17.2.0

### PrimeNG version

17.10.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.0

**Comment by cetincakiroglu** [comment]
Hi,

It's already fixed. Closing the issue.
