### ISSUE TITLE
Component: MultiSelect use listitem semantically 

### ISSUE THREAD

**Issue by mristov** [primefaces/primeng#15002]
### Describe the bug

![image](https://github.com/primefaces/primeng/assets/150306240/58b50584-8a8f-4d17-9aa4-3b9415582ddc)

### Environment

PrimeNG 17.10

### Angular version

17.0.5

### PrimeNG version

17.10

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.1

**Comment by TaneliTuomola** [comment]
I'm facing same issue and i think your previous issue report is related to this:

https://github.com/primefaces/primeng/issues/15001

All these problems are due to invalid html structure of the multiselect list:
`<ul>
	<p-multiselectitem>
		<li>`

**Comment by cetincakiroglu** [comment]
Fixed in https://github.com/primefaces/primeng/pull/15153
