### ISSUE TITLE
p-inputNumber: output type changed to string from number

### ISSUE THREAD

**Issue by imaksp** [primefaces/primeng#15017]
### Describe the bug

In version 17.8.0 p-inputNumber was outputting number type when used with ngModel, but now in latest version 17.10.0 it gives output value as string.

### Environment

NA

### Angular version

17.2.x

### PrimeNG version

17.10.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.x

### Steps to reproduce the behavior

1. just log typeof output value (field binded using ngModel) of p-inputNumber on blur event.

### Expected behavior

It should output value as **number** type like in previous versions.

**Comment by imaksp** [comment]
https://github.com/primefaces/primeng/pull/15015 might be related.

**Comment by aknuth** [comment]
It's due to the following change in V 17.9.0:

![image](https://github.com/primefaces/primeng/assets/1428662/e95545ba-ea82-48cb-a6a5-5b7717288af7)
commit was 82a4050b6cc5a5891e6ba177a0f0d9143c8bb635

I recently changed the code of the onInputBlur method in my workspace:

```
onInputBlur(event: Event) {
        this.focused = false;

        let newValue = this.validateValue(this.parseValue(this.input.nativeElement.value));//?.toString();
        this.input.nativeElement.value = this.formatValue(newValue);
        this.input.nativeElement.setAttribute('aria-valuenow', newValue?.toString());
        this.updateModel(event, newValue);
        this.onBlur.emit(event);
    }
```
that also solves #14928: p-inputNumber: onInputBlur NPE 

hope that helps ...

**Comment by cetincakiroglu** [comment]
Hi,

Thanks for reporting the issue, this issue has been fixed by @rosenthalj in https://github.com/primefaces/primeng/commit/9b0518ed535b63fbeb18640b968e4c99fcf228d6

This issue is superseded by https://github.com/primefaces/primeng/issues/15014

Closing the issue.
