### ISSUE TITLE
Component: InputText

### ISSUE THREAD

**Issue by anikalthh** [primefaces/primeng#15010]
### Describe the bug

Two features from the InputTextModule aren't working:

1. 
<img width="260" alt="Screenshot 2024-03-11 at 9 43 40 PM" src="https://github.com/primefaces/primeng/assets/95908881/d3b8f7fe-300d-4e7d-814f-066f27eb4a14">
`    <div class="p-toolbar-group-center">
        <span class="p-input-icon-left">
            <i class="pi pi-search"></i>
            <input pInputText placeholder="Search forum"/>
        </span>
    </div>` 

The icon is supposed to be inside the input text box but it is currently outside of the textbox.

2. There is a similar issue with Floating Label of the InputTextModule. The floating label is outside of the textbox before it is even clicked on/ focused.
    

### Environment

PrimeNG project

### Angular version

17

### PrimeNG version

17.10.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.0

### Browser(s)

Chrome

**Comment by mithun522** [comment]
Hey @anikalthh i was going through the issues and i found that the floating label of the inputTextModule is working fine. Can you please give a stackblitz repo of the issue reproduced or a screen record.

**Comment by mithun522** [comment]
Hey @cetincakiroglu In the documentation of inputTextIcon the code with search icon is getting overlapped when we try to use the exact same code in our project. Below video is the example of how it works 

[Screencast from 03-22-2024 05:31:12 PM.webm](https://github.com/primefaces/primeng/assets/76867392/53124783-81b4-480d-a1ab-9db4c537d599)

and so I have added a padding to the input box after which the code works like the below video.

[Screencast from 03-22-2024 05:25:59 PM.webm](https://github.com/primefaces/primeng/assets/76867392/72591aa3-f69a-48bd-b24b-640747f654cc)
