### ISSUE TITLE
Table column - Selecting all Checkbox having issue

### ISSUE THREAD

**Issue by Rishikap123** [primefaces/primeng#15023]
### Describe the bug

Table column When selecting all checkboxes the default checkboxes are getting disabled.

### Environment

N/A

### Angular version

16.2.12

### PrimeNG version

16.9.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14.2

### Browser(s)

All

### Steps to reproduce the behavior

1. Open https://www.primefaces.org/primeng-v16-lts/table#column-toggle
2. In html file made 2 columns as "required: true".
3. If i am selecting all columns then the default column which should be enabled is getting disabled.
![image](https://github.com/primefaces/primeng/assets/100288743/11f9ae5c-aa69-4917-99ab-f6e464e0992a)

### Expected behavior

Default column with required as true should always be enabled.

**Comment by cetincakiroglu** [comment]
Hi,

Column interface doesn't have `required` property. Even though I've added it in the example, it doesn't effect the column toggle behavior. Please see the example: https://stackblitz.com/edit/89f7g5?file=src%2Fapp%2Fdemo%2Ftable-column-toggle-demo.ts

**Comment by cetincakiroglu** [comment]
Closing the issue due to inactivity.
