### ISSUE TITLE
p-inputNumber: Emits number while changing but string when losing focus

### ISSUE THREAD

**Issue by jpgoelz** [primefaces/primeng#15039]
### Describe the bug

When changing the content of a p-inputNumber, the emitted value correctly is of type `number`. But as soon as the input loses focus the type changes to `string`, which may lead too hard to find typing problems.

### Environment

Any environment should have this problem. I tested this with the documentation demo StackBlitz (see below).

### Reproducer

https://stackblitz.com/edit/m96pfg?file=src%2Fapp%2Fdemo%2Finput-number-numerals-demo.html

### Angular version

17.2.2

### PrimeNG version

17.10.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

n/a

### Browser(s)

Chrome

### Steps to reproduce the behavior

In my StackBlitz, change the values of the input fields and see the output below:

![numberInput-produces-string](https://github.com/primefaces/primeng/assets/32487587/aa194bc1-7b1f-481a-9dc0-8cef1c422b81)

### Expected behavior

The emitted type is always number (and maybe undefined/null, if input is empty).

**Comment by dl3g0** [comment]
Hello, I have the same problem, let's hope they fix it in version 17.11.0

**Comment by gerardva** [comment]
I'm also experiencing this issue. This seems to be introduced in 17.9.0, as far as I can tell by this change: https://github.com/primefaces/primeng/commit/82a4050b6cc5a5891e6ba177a0f0d9143c8bb635#diff-d15eb5f971fcc845ef140641bb6498419d87b06832dd22180381101c84f55a70R1369

**Comment by jpgoelz** [comment]
> I'm also experiencing this issue. This seems to be introduced in 17.9.0, as far as I can tell by this change: [82a4050#diff-d15eb5f971fcc845ef140641bb6498419d87b06832dd22180381101c84f55a70R1369](https://github.com/primefaces/primeng/commit/82a4050b6cc5a5891e6ba177a0f0d9143c8bb635#diff-d15eb5f971fcc845ef140641bb6498419d87b06832dd22180381101c84f55a70R1369)

That could also explain, why I keep seeing this Error in my console when emptying the input field:<br />
![image](https://github.com/primefaces/primeng/assets/32487587/4f940c76-c4e1-47f7-8917-233356c324ec)

**Comment by jpgoelz** [comment]
The issue seems to be resolved in PrimeNG 17.11.0:

https://stackblitz.com/edit/m96pfg-zf4xhr?file=src%2Fapp%2Fdemo%2Finput-number-numerals-demo.ts
