### ISSUE TITLE
Component: Calendar - Update type for minDate and maxDate

### ISSUE THREAD

**Issue by avytak** [primefaces/primeng#15038]
### Describe the bug

![image](https://github.com/primefaces/primeng/assets/108807758/7513f846-d5ab-4610-b580-0fbb04452ba6)
According to the documentation, the default value for the minDate and maxDate is **Null**
However, the setters for them accept only the **Date** format.
Is it possible to update the setters to accept Nullable<Date>?
I have a situation when in some cases I don't need to have the minDate in my calendar.
A possible workaround is to use **unknown** 

```
<p-calendar						
dataType="string"
[minDate]="minDate"
[showIcon]="true"></p-calendar>

this.minDate= null as unknown as Date
```
,

### Environment

Windows 10

### Angular version

16.2.8

### PrimeNG version

16.5.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.19.1

### Browser(s)

Chrome

### Expected behavior

I will be able just to assign null to the variable, without using unknown.

**Comment by dobanisola-scottlogic** [comment]
This issue can be closed as it has been fixed in this [here](https://github.com/primefaces/primeng/pull/14646).

**Comment by ThoSap** [comment]
No @dobanisola-scottlogic it was fixed here: https://github.com/primefaces/primeng/pull/14754
See discussion https://github.com/orgs/primefaces/discussions/1136

@cetincakiroglu this issue can be closed.
