### ISSUE TITLE
When using stateStorage for the p-table I always get the following error in the console when the component first loads:

### ISSUE THREAD

**Issue by slagbat** [primefaces/primeng#15043]
### Describe the bug

When using stateStorage for the p-table I always get the following error in the console when the component first loads:

> has-permission.guard.ts:54 ERROR TypeError: Cannot read properties of undefined (reading 'querySelectorAll')
    at DomHandler.find (primeng-dom.mjs:70:35)
    at Table.saveColumnWidths (primeng-table.mjs:2321:34)
    at Table.saveState (primeng-table.mjs:2250:18)
    at Table.ngOnChanges (primeng-table.mjs:1028:26)
    at Table.rememberChangeHistoryAndInvokeOnChangesHook (core.mjs:3032:14)
    at callHookInternal (core.mjs:4024:14)
    at callHook (core.mjs:4055:9)
    at callHooks (core.mjs:4006:17)
    at executeInitAndCheckHooks (core.mjs:3956:9)
    at selectIndexInternal (core.mjs:11780:17)

It doesn't seem to cause any real issues with my code as it is only to do wit saving the column widths.

My table is implemented as a custom component as below. The error is shown even when using my table directly in Storybook (as a story) as well as when the component is implemented in our applications:

```html
<p-table #dataTable [dataKey]="'id'" [value]="rows" [columns]="selectedColumns" [styleClass]="styleClass"
  [tableStyle]="tableStyle" [(selection)]="selectedRows" [paginator]="true" [rows]="pageSize"
  [totalRecords]="totalRecords" [resizableColumns]="true" [reorderableColumns]="true"
  [paginatorPosition]="paginatorPosition" [showJumpToPageDropdown]="showJumpToPageDropdown"
  [showCurrentPageReport]="true" [currentPageReportTemplate]="currentPageReportTemplate"
  [loading]="loading" [rowHover]="true" [selectAll]="selectAll" columnResizeMode="fit" [lazy]="true"
  (onLazyLoad)="loadData($event)" (selectAllChange)="toggleAllSelect($event)" (onRowSelect)="selectRow($event)"
  (onRowUnselect)="unselectRow($event)" [lazyLoadOnInit]="false" [scrollable]="scrollable"
  [scrollHeight]="scrollHeight" [showLoader]="true" [stateStorage]="local" stateKey="users-table"
 >
```

### Environment

Linux docker containers

### Angular version

16.2.12

### PrimeNG version

16.9.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

21.2.0

### Expected behavior

No errors are shown in the console.

**Comment by hcornelisonJHA** [comment]
We are experiencing the same issue with a table that has the row expanders enabled. Bouncing back and forth to the grid causes this error to be thrown, same version as the original bug report.
