### ISSUE TITLE
Checkbox: Disabled property does not work when it's used with formControlName

### ISSUE THREAD

**Issue by maxkonoplin** [primefaces/primeng#15047]
### Describe the bug

Disabled property does not work when it's used with formControlName and didn't use binary property. 

### Environment

Angular 17
PrimeNG: 17.10.0

### Angular version

17.2.0

### PrimeNG version

17.10.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.0

**Comment by CaringDev** [comment]
Also [with formControl](https://github.com/bbvch/CheckboxError/blob/main/src/app/app.component.spec.ts#L25), I think this might be related to other "Checkbox XYZ does not work with reactive forms" issues, e.g. #14880 and #15033

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
