### ISSUE TITLE
Component: p-dropdown    (onBlur)  is not fired when a value is not selected

### ISSUE THREAD

**Issue by isuruRSSL** [primefaces/primeng#15049]
### Describe the bug

Previously p-dropdown fired (onBlur)  when we select the dropdown and click elsewhere without selecting a dropdown value.
But a after upgrading to primeng version 17.9.0  ,  (onBlur) is no longer fired for above scenario.
It now only fires when we select a dropdown value.

### Environment

Primeng version - 17.9.0
Angular version - 17.2.3

### Angular version

17.2.3

### PrimeNG version

17.9.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v18.15.0

### Browser(s)

Chrome Version 122.0.6261.112

### Steps to reproduce the behavior

1. Add (onBlur)="onBlur($event)" in the p-dropdown component
2. log the event to console to check if it's fired.
3.  Select  dropdown field , but don't select any value . Just click elsewhere on the screen.
4. Observe if onBlur fires any event

### Expected behavior

(onBlur)  must fire an event for the above scenario even when we doesn't select a value.
That's how it happened in the previous primeng version we used ( version -15.2.0)

**Comment by imaksp** [comment]
Hi, this bug/change might have been introduced with this in v16:
https://github.com/primefaces/primeng/issues/14128

it seems this change was done to fix other bug.

**Comment by mehmetcetin01140** [comment]
Hi, could you please share a stackblitz example?
