### ISSUE TITLE
[*]: whole page & browser tab is hanging after 17.11 update

### ISSUE THREAD

**Issue by imaksp** [primefaces/primeng#15057]
### Describe the bug

whole page & browser tab is hanging after 17.11 update, currently don't have regeneration as could not debug due to some infinite loop introduced by 17.11 version

### Environment

NA

### Angular version

17.3.0

### PrimeNG version

17.11

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.x

### Steps to reproduce the behavior

will add if I find something.

### Expected behavior

there should not be any infinite loop & browser tab should not hang, there should be some tests to catch this issues with every new minor version update, I think team should stop accepting PR(s) without test case.

**Comment by imaksp** [comment]
Hi, I have found possible issue for this , in version 17.11 following panelMenu related PR was merged:
https://github.com/primefaces/primeng/pull/15042
it has created infinite loop issue on one of our page, if I remove use of panelMenu component our app works with 17.11 version.

**Comment by cetincakiroglu** [comment]
Hi,

The issue is related with https://github.com/primefaces/primeng/issues/15057

**Comment by cetincakiroglu** [comment]
Hi,

I've updated the relevant lines, could you please check it after the v17.12.0 release

**Comment by imaksp** [comment]
Hi @cetincakiroglu **17.12** release has fixed this issue, thanks.
