### ISSUE TITLE
Meter group set values under 1 as zero

### ISSUE THREAD

**Issue by blackat** [primefaces/primeng#15055]
### Describe the bug

Hello,
if the list contains some values under 1 like 0.5% etc. it is rounded to 0, [here the code](https://discord.com/channels/787967399105134612/787967806367989790/1217426620055425075).

It would be great to have the possibility to not be limited to values >= 1.

### Environment

I am using PrimeNG 17.10.0 under OSX and Google Chrome.

### Angular version

17.2.4

### PrimeNG version

17.10.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.3.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

Just set a value less than 1.

### Expected behavior

Values less than 1 are correctly rendered.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
