### ISSUE TITLE
p-panel: No top border when [showHeader]="false"

### ISSUE THREAD

**Issue by psarno** [primefaces/primeng#15056]
### Describe the bug

When the <p-panel> component has [showHeader]="false", the upper border is not properly displayed.

This impacts every free theme I tested it with.

In order to fix it and have it work across themes, I had to apply the following CSS rule to a `<p-panel>` that had `styleClass="fix-panel-header"`.

```
:host ::ng-deep .fix-panel-header .p-panel-content {
  border: 1px solid var(--surface-border);
  background: var(--surface-card);
  color: var(--highlight-text-color);
  padding: 1rem;
  border-radius: 3px;
}
```

**Incorrect**

![image](https://github.com/primefaces/primeng/assets/18640860/55f2f4d0-a51e-4d4d-b8cb-11d3c57c1766)

**Fixed:**

![image](https://github.com/primefaces/primeng/assets/18640860/1ca2f882-ac16-4ef6-8726-fa667683d9a9)

### Environment

Angular 17.2.4
PrimeNG 17.8.0

### Reproducer

See above

### Angular version

17.2.4

### PrimeNG version

17.8.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.0

### Steps to reproduce the behavior

1. Put a `<p-panel>` component on the page
2. Set `showHeader="false"` on the `<p-panel>`

### Expected behavior

Top border should render.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
