### ISSUE TITLE
The width of the columns shows unexpected results and expanded automatically on load 

### ISSUE THREAD

**Issue by chinthu** [primefaces/primeng#15054]
### Describe the bug

THe table with resize enabled and resize mode expand and on load the column width is showing too large size and each column is taking 100% of available width.

### Environment

"primeng": "^13.4.1",
"@angular/common": "~13.1.0",

### Angular version

13.1.0

### PrimeNG version

13.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.13.2

### Browser(s)

Chrome 122

### Steps to reproduce the behavior

1. Load the grid and initial size of columns become too large
2. or click on sort of column , the size of all columns becomes 100% of available width 
![sample grid](https://github.com/primefaces/primeng/assets/3716082/1ef7f7d9-f605-4528-ba51-22f056fa958a)

### Expected behavior

on initial load columns will autofit in available area

**Comment by mehmetcetin01140** [comment]
Hi, could you please share a stackblitz example?
