### ISSUE TITLE
P-password have a bug on smaller device

### ISSUE THREAD

**Issue by neergaby95** [primefaces/primeng#15062]
### Describe the bug

P-password have a bug on smaller width devices like phone under 767px width

### Environment

When open page like login from sakai for exemple, the input p-password is making smaller then normal on resolution under 767 width

### Angular version

17.0.2

### PrimeNG version

17.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

1

### Browser(s)

chrome

### Steps to reproduce the behavior

![Capture](https://github.com/primefaces/primeng/assets/21299917/db4b1347-0c60-410b-9761-540f145f57c9)

**Comment by AbdulKhader4123** [comment]
A pr has been raised for this.
https://github.com/primefaces/sakai-ng/pull/23

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
