### ISSUE TITLE
Component: Terminal

### ISSUE THREAD

**Issue by anthonyPierronAT** [primefaces/primeng#15061]
### Describe the bug

When using the terminal component, I get an injection error because of the TerminalService. This service is not singleton and it is never provided and only used in the constructor of the component.
The below screenshot is from your Stackblitz example of Terminal from your site which is in version 17.10.0.
<img width="836" alt="image" src="https://github.com/primefaces/primeng/assets/149659719/c8a2afc0-f84c-4707-b716-da3b8b50f66b">

### Environment

MacOS

### Angular version

17.2.4

### PrimeNG version

17.9.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.1

### Browser(s)

Chrome 122.0.6261.129

### Steps to reproduce the behavior

Open the demo of your Terminal component

### Expected behavior

The terminal component not causing an injection error with the TerminalService.

**Comment by mehmetcetin01140** [comment]
Hi, this issue has been fixed in the latest version of PrimeNg (17.17.0).

Terminal demo (v17.17.0) = https://stackblitz.com/edit/prdev8?file=package.json
