### ISSUE TITLE
 ERESOLVE unable to resolve dependency tree

### ISSUE THREAD

**Issue by LeoAguanta** [primefaces/primeng#15069]
### Describe the bug

unable to install primeng

code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: atlas.clinicmanagement.web@0.0.0
npm ERR! Found: rxjs@7.5.7
npm ERR! node_modules/rxjs
npm ERR!   rxjs@"~7.5.5" from the root project
npm ERR!   peer rxjs@"^6.5.3 || ^7.4.0" from @angular/common@17.3.0
npm ERR!   node_modules/@angular/common
npm ERR!     @angular/common@"^17.2.2" from the root project
npm ERR!     peer @angular/common@"^17.0.0" from primeng@17.11.0
npm ERR!     node_modules/primeng
npm ERR!       primeng@"17.11.0" from the root project
npm ERR!     2 more (@angular/forms, @angular/platform-browser)
npm ERR!   2 more (@angular/core, @angular/forms)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer rxjs@"^6.0.0 || ^7.8.1" from primeng@17.11.0
npm ERR! node_modules/primeng
npm ERR!   primeng@"17.11.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

### Environment

Currently in local invironment

I am using latest version of Angular - v17.2.1
and RxJS v7.5.5

### Angular version

v17.2.1

### PrimeNG version

17.11.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.11.1

**Comment by dalenguyen** [comment]
Try with `npm install primeng --legacy-peer-deps` or `npm install primeng --force`.

**Comment by docentYT** [comment]
Angular v18 similar problem

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @ng-bootstrap/ng-bootstrap@16.0.0
npm ERR! Found: @angular/common@18.0.0
npm ERR! node_modules/@angular/common
npm ERR!   peer @angular/common@"18.0.0" from @angular/forms@18.0.0
npm ERR!   node_modules/@angular/forms
npm ERR!     @angular/forms@"^18.0.0" from the root project
npm ERR!     peer @angular/forms@"^17.0.0 || ^18.0.0" from primeng@17.18.0
npm ERR!     node_modules/primeng
npm ERR!       primeng@"17.18.0" from the root project
npm ERR!   peer @angular/common@"18.0.0" from @angular/platform-browser@18.0.0
npm ERR!   node_modules/@angular/platform-browser
npm ERR!     peer @angular/platform-browser@"18.0.0" from @angular/forms@18.0.0
npm ERR!     node_modules/@angular/forms
npm ERR!       @angular/forms@"^18.0.0" from the root project
npm ERR!       1 more (primeng)
npm ERR!     peer @angular/platform-browser@"18.0.0" from @angular/platform-browser-dynamic@18.0.0
npm ERR!     node_modules/@angular/platform-browser-dynamic
npm ERR!       @angular/platform-browser-dynamic@"^18.0.0" from the root project
npm ERR!     2 more (@angular/router, the root project)
npm ERR!   5 more (@angular/platform-browser-dynamic, @angular/router, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^17.0.0" from @ng-bootstrap/ng-bootstrap@16.0.0
npm ERR! node_modules/@ng-bootstrap/ng-bootstrap
npm ERR!   @ng-bootstrap/ng-bootstrap@"^16.0.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/common@17.3.10
npm ERR! node_modules/@angular/common
npm ERR!   peer @angular/common@"^17.0.0" from @ng-bootstrap/ng-bootstrap@16.0.0
npm ERR!   node_modules/@ng-bootstrap/ng-bootstrap
npm ERR!     @ng-bootstrap/ng-bootstrap@"^16.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```
