### ISSUE TITLE
p-tree: Incorrect node passed in onNodeSelect when [filter]="true"

### ISSUE THREAD

**Issue by psarno** [primefaces/primeng#15063]
### Describe the bug

If you have a `<p-tree>` component and set `[filter]="true"` on it, when you filter the tree the wrong node is passed into the onNodeSelect() function.

**Repro:**

https://stackblitz.com/edit/github-tayhsx

Type "123" into the filter, and click "123".  Note that the displayed node is the parent, not the one that was clicked.

![primeng](https://github.com/primefaces/primeng/assets/18640860/509c6c60-f0bb-447c-87d7-78d59379c249)

### Environment

Angular 17.2.4
PrimeNG 17.8.0

### Reproducer

https://stackblitz.com/edit/github-tayhsx

### Angular version

17.2.4

### PrimeNG version

17.8.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.0

### Steps to reproduce the behavior

1. https://stackblitz.com/edit/github-tayhsx
2. Filter for "123"
3. Click "123"

### Expected behavior

Expect:  Shows "123"
Result: Shows "Parent Node"

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
