### ISSUE TITLE
The calendar inside a table in row editing mode behaves incorrectly when the key is time

### ISSUE THREAD

**Issue by ordorub** [primefaces/primeng#15079]
### Describe the bug

When I put a line into edit mode and try to change the date or time, the calendar behaves strangely.

When you select a date or change the time using the arrows, after 1-2 clicks the calendar closes and the line exits the editing mode.

If you try to edit numbers using the keyboard, then after 2 keystrokes the calendar closes and the line exits the editing mode.

This happens if **dataKey="time"** is specified in the table. If you remove this property, the calendar works well.

### Environment

```JSON
"dependencies": {
    "rxjs": "7.8.1",
    "quill": "1.3.7",
    "tslib": "2.6.2",
    "primeng": "17.11.0",
    "zone.js": "0.14.4",
    "chart.js": "3.9.1",
    "primeflex": "3.3.1",
    "primeicons": "6.0.1",
    "@types/node": "12.20.55",
    "@angular/cdk": "16.2.14",
    "@angular/core": "17.3.0",
    "@angular/forms": "17.3.0",
    "@types/jasmine": "4.3.1",
    "@angular/common": "17.3.0",
    "@angular/router": "17.3.0",
    "@angular/compiler": "17.3.0",
    "@angular/animations": "17.3.0",
    "@angular/platform-browser": "17.3.0",
    "@angular/platform-browser-dynamic": "17.3.0"
  }
```

### Reproducer

https://stackblitz.com/edit/github-zckp3f?file=src%2Fapp%2Fapp.component.html

### Angular version

17.3.0

### PrimeNG version

17.11.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.0

### Browser(s)

Chrome 122.0.6261.129

### Steps to reproduce the behavior

1. Click the edit button in the line.
2. Click on the time field.
3. Press the up arrow next to the second twice.

### Expected behavior

The time should increase by two seconds. The calendar must remain open.

**Comment by cetincakiroglu** [comment]
The key should be a value that will not change. When you change the key, component cannot find the related data and overlay closes. Try to assign something else that you will not edit. It'll work. Closing the issue.
