### ISSUE TITLE
Dropdown: Improper event handling

### ISSUE THREAD

**Issue by maxkonoplin** [primefaces/primeng#15070]
### Describe the bug

In previous versions of PrimeNG, this behavior worked correctly, but starting from version 17, it behaves differently. If we create multiple inputs (checkbox and multiselect), open the multiselect dropdown, and in its open state, click on the checkbox, the onChange event of the checkbox will trigger before the onPanelHide event of the multiselect.

### Environment

Angular 17
PrimeNG: 17.11.0

### Angular version

17.2.0

### PrimeNG version

17.11.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.0

**Comment by isuruRSSL** [comment]
Yep, I've already added an issue for onBlur event
https://github.com/primefaces/primeng/issues/15049
But  seems event handling is messed up, even in multiselect input component.

**Comment by cetincakiroglu** [comment]
Hi @maxkonoplin,

Could you please share a stackblitz example?

onChange should be fired before the panel closes. Overlay Panel closes after the selection not before the selection.

**Comment by cetincakiroglu** [comment]
Closing the issue due to inactivity.
