### ISSUE TITLE
PrimeNG 16.9.x TabView Scroll arrow not showing up.

### ISSUE THREAD

**Issue by nesanmano** [primefaces/primeng#15073]
### Describe the bug

I have updated my angular app from 12 to 16 . This implied that I upgraded my primeng to 16 as well. The problem is the p-tabview  is not showing the scroll arrow even thought we set the scrollable property to true. I tried to resize the window but it does not seem to work.  I know that this issue was reported multiple times. 

### Environment

Windows 10, Visual Code Node JS 20, Angular 16.2.3, PRimeNg 16.9.3

### Angular version

16.2.3

### PrimeNG version

16.9.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20

### Browser(s)

Edge

**Comment by cetincakiroglu** [comment]
Hi,

Could you please see the example, scrollbars are visible https://stackblitz.com/edit/lkdzmc?file=package.json

If the issue persists, please provide a stackblitz example so we can identify the issue.

**Comment by nesanmano** [comment]
Hi, I have not solved the problem. I can get to see the button to navigate toward the left when I scroll it using the web kit scroll bar (This is a test that I have performed using the dev tool from Chrome.) When adding items to the tab View dynamically, the arrow to navigate toward the right does not show up. My doubt, is that the resize event is not being triggered properly so that the buttons show up. I really need help on this. How is the event triggered.?

**Comment by nesanmano** [comment]
I have found the issue. The issue is regarding the condition in the tab view.ts file. More precisely, the bindResizeObserver method. WidthOffsetWidth greater than containerOffsetWidth. This is always false since it the container and the ul list are always same.

**Comment by cetincakiroglu** [comment]
@nesanmano,

Resize event listens to the window resize. Currently, it works in the latest version. It shows the arrow when the tab count is more than to fit the container. Could you please test it with the latest LTS version (16.9.7) or the latest PrimeNG version (17.12.0)?

**Comment by cetincakiroglu** [comment]
Closing the issue due to inactivity.
