### ISSUE TITLE
Component: Autocomplete has focusable descendants

### ISSUE THREAD

**Issue by mristov** [primefaces/primeng#15097]
### Describe the bug

<img width="393" alt="image" src="https://github.com/primefaces/primeng/assets/150306240/82687605-7d38-4207-bc9a-0ccc92c5f9ca">

### Environment

Windows 11

### Angular version

17.0.5

### PrimeNG version

17.11

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.1

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
