### ISSUE TITLE
TreeSelect Component: Enabled filters and checbox selection mode

### ISSUE THREAD

**Issue by samirosmanoviccirtuo** [primefaces/primeng#15092]
### Describe the bug

We are using the TreeSelect component with enabled filters and selectionMode set to "checkbox". 

`
  <p-treeSelect
    selectionMode="checkbox"
    [options]="options"
    [filter]="true"
    [propagateSelectionDown]="true"
    [propagateSelectionUp]="true"
    >
    </p-treeSelect>
`

When filtering nodes, we encounter a situation where, during filtering, a node that initially has 10 child nodes is selected as 'full' due to the fact that only 1 filtered item remains at the end of filtering. After that, when we close and reopen this component, none of the checkboxes are marked. In this case, we also receive incorrect selected values from the component.

https://github.com/primefaces/primeng/assets/132335157/91504ec4-c7c7-4d30-acd0-94dddf260bf9

As you can see in the attached video, in both cases, "Chile" should be selected as the value.

### Environment

Chrome,
Windows 10

### Angular version

17.1.2

### PrimeNG version

17.7.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
