### ISSUE TITLE
OverlayPanel: Close overlay when clicked again

### ISSUE THREAD

**Issue by anikets43** [primefaces/primeng#151]
Hi, 
Is there any configuration to close the overlay panel when clicked second time. 

Thanks,
Aniket

**Comment by cagataycivici** [comment]
Hi,

Clicked where? Its target?

**Comment by anikets43** [comment]
Hi @cagataycivici 

Let's say in the below demo link(Basic), when user clicks on the basic button it will open the overlay panel. Again when click on the same, it should close the panel. In the demo, when we click outside the overlay, it closes.
[http://www.primefaces.org/primeng/#/overlaypanel](url)

Regards,
Aniket

**Comment by cagataycivici** [comment]
I've added toggle() method for this, so that if panel is visible, toggle hides it. Signature is same as show so you just need to replace show with toggle. show still remains for cases where you always want to show it.
