### ISSUE TITLE
Listbox: Empty message is not displayed

### ISSUE THREAD

**Issue by gpobr** [primefaces/primeng#15105]
### Describe the bug

The empty message is not displayed when the filter is applied.

### Environment

Windows

### Reproducer

https://stackblitz.com/edit/6uh9ca?file=src%2Fapp%2Fdemo%2Flistbox-filter-demo.html

### Angular version

17.2

### PrimeNG version

17.9, 17.11

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.9

### Steps to reproduce the behavior

1. Set a ListBox with filter and empty message (see reproducer)

### Expected behavior

The empty message should be displayed when the applied filter returns no results.

**Comment by mehmetcetin01140** [comment]
Hi, this issue is not present in the latest version of PrimeNG (17.17.0). Please try it with the latest version. I'm closing the issue.
