### ISSUE TITLE
Component: p-dropdown

### ISSUE THREAD

**Issue by WTW-Jacob-Evans** [primefaces/primeng#15112]
### Describe the bug

When the dropdown is expanded but there are no values, and the "no results found" message is shown, Axe DevTools is showing an accessibility issue. This is related to the list not being contained within the ul or ol tags that have the role "list" or no role (the current role is "listbox").
![image](https://github.com/primefaces/primeng/assets/163871134/af956c17-9518-4e70-80a7-c36fbd91a32a)
![image](https://github.com/primefaces/primeng/assets/163871134/1611c0c6-c018-415e-a967-fb49f201ffb3)

### Environment

windows 10

### Reproducer

https://stackblitz.com/github/primefaces/primeng-issue-template?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts

### Angular version

17.2.3

### PrimeNG version

17.11.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.0

**Comment by mlz11** [comment]
Hey @cetincakiroglu @mehmetcetin01140 👋🏻 

I have opened the following PR https://github.com/primefaces/primeng/pull/15157 attempting to fix the issue. Don't hesitate to tell me what you think of it !
