### ISSUE TITLE
p-multiSelect: onRemove event not getting emitted

### ISSUE THREAD

**Issue by NrujalSharma** [primefaces/primeng#15118]
### Describe the bug

The onRemove event is not getting emitted when a selection is removed

### Environment

Angular application on Chrome

### Angular version

~17.0.10

### PrimeNG version

^17.6.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.11.0

### Browser(s)

Chrome 122.0.6261.129

### Expected behavior

onRemove event should get emitted when an item is removed from selection

**Comment by zemalay** [comment]
> ### Describe the bug
> The onRemove event is not getting emitted when a selection is removed
> 
> ### Environment
> Angular application on Chrome
> 
> ### Reproducer
> _No response_
> 
> ### Angular version
> ~17.0.10
> 
> ### PrimeNG version
> ^17.6.0
> 
> ### Build / Runtime
> Angular CLI App
> 
> ### Language
> TypeScript
> 
> ### Node version (for AoT issues node --version)
> v20.11.0
> 
> ### Browser(s)
> Chrome 122.0.6261.129
> 
> ### Steps to reproduce the behavior
> _No response_
> 
> ### Expected behavior
> onRemove event should get emitted when an item is removed from selection

Me too

**Comment by ermaneng** [comment]
when using chips onRemove event is emmitted however not working with the selection checkboxes
