### ISSUE TITLE
p-multiSelect: onSelectAllChange event not getting emitted

### ISSUE THREAD

**Issue by NrujalSharma** [primefaces/primeng#15119]
### Describe the bug

`onSelectAllChange` should be triggered when checkbox selected, but the event does not get emitted

### Environment

Anglar app on chrome browser running on Windows 11

### Angular version

~17.0.10

### PrimeNG version

^17.6.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.11.0

### Browser(s)

Chrome 122.0.6261.129

### Steps to reproduce the behavior

```html
<p-multiSelect
  [options]="caseTypeOptions()"
  optionLabel="name"
  optionValue="name"
  selectedItemsLabel="{0} columns selected"
  defaultLabel="Choose Case Types"
  display="comma"
  [filter]="true"
  [showClear]="true"
  formControlName="caseType"
  [maxSelectedLabels]="7"
  (onClear)="caseTypeCleared($event)"
  (onSelectAllChange)="caseTypeSelectAllChanged($event)"
  (onChange)="caseTypeSelectionUpdated($event)">
</p-multiSelect>
```

```ts
caseTypeSelectAllChanged(data: any) {
  console.log('caseTypeSelectAllChanged', data);
}
```

### Expected behavior

The event should get triggered

**Comment by Dharmang92** [comment]
Facing the same issue. Any update?

**Comment by pabloaguiars** [comment]
Same issue here. Using Primeng 16.9.1.

**Comment by mehmetcetin01140** [comment]
Hi, this issue is not present in the latest version of PrimeNG (17.17.0). Please try it with the latest version.
