### ISSUE TITLE
Styles are broken in Microsoft Edge

### ISSUE THREAD

**Issue by vdiaz1130** [primefaces/primeng#15120]
### Describe the bug

Styles do not render properly in the Edge browser. They look correct in Chrome (Canary as well), Safari, and Firefox.

<img width="2363" alt="image" src="https://github.com/primefaces/primeng/assets/24530571/942923c4-4aa2-4e59-8ed5-918be7f7d4b7">

### Environment

package.json
```
    "@angular/animations": "^17.0.0",
    "@angular/common": "^17.0.0",
    "@angular/compiler": "^17.0.0",
    "@angular/core": "^17.0.0",
    "@angular/forms": "^17.0.0",
    "@angular/platform-browser": "^17.0.0",
    "@angular/platform-browser-dynamic": "^17.0.0",
    "@angular/router": "^17.0.0",
    "primeicons": "^6.0.1",
    "primeng": "^17.2.0",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.2"
```
node -v 20.7.0
npm -v 10.1.0
OsX 14.2

### Angular version

17.0.0

### PrimeNG version

17.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.7.0

### Steps to reproduce the behavior

git clone [git@github.com](mailto:git@github.com):thecodedeck/angular-cc-1-client.git
git clone [git@github.com](mailto:git@github.com):thecodedeck/angular-cc-1-server.git

cd into each and run npm i
Start terminal in each
On client run ng serve
On server run npm start

Check it in chrome.
Check it in MS Edge

### Expected behavior

Should render correctly in MS Edge

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
