### ISSUE TITLE
PanelMenu: Submenu's not using animations

### ISSUE THREAD

**Issue by SimonJ-DR** [primefaces/primeng#15124]
### Describe the bug

Opening one of the top level items displays submenu's for a brief moment then collapses them. After that they cannot be opened again.
EDIT:
This issue seems to be fixed. Although there is still some funky behavior going on. When multiple layers are expanded, opening a new submenu it'll close on layer without animations.

### Environment

In the official docs

### Angular version

17

### PrimeNG version

17.11.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.5.1

### Browser(s)

Chrome

### Steps to reproduce the behavior

https://primeng.org/panelmenu
Fully expand 2 layers, then open a different menu item.

**Comment by Ruslancic** [comment]
I confirm, that navigation in submenu is not working also!
