### ISSUE TITLE
Table: Multiple selection with CTRL and mouse click in a table with with Editable cells lagging if a large number of rows and column are present

### ISSUE THREAD

**Issue by fraras** [primefaces/primeng#15142]
### Describe the bug

When the user tries to select multiple columns with the CTRL Key and the mouse click the application starts to lag and freezes for several seconds (with more columns the freeze time is longer) This doesn't happen in those cases:

- If the user selects rows using only the keyboard (both shift key or CTRL)
- if the metaKeySelection is set to false (selecting multiple rows with the simple click of the mouse)

### Environment

localhost Angular app

### Reproducer

https://stackblitz.com/edit/github-fsqmbr-j5e2z6?file=src%2Fapp%2Fapp.component.ts

### Angular version

17.3.1

### PrimeNG version

17.11.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.19.0

### Browser(s)

Microsoft Edge Version 122.0.2365.92 (Official Build) (64 bit)

### Steps to reproduce the behavior

1. Select multiple Rows with CTRL key and left click of the mouse

### Expected behavior

The user should be able to select the rows without lag or freeze of the application.

**Comment by fraras** [comment]
I noticed that if I select only using the keyboard with ctrl and enter and then I continue usining ctrl + left mouse click the table is behaving normally without any lags until I release and press again the ctrl key

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
