### ISSUE TITLE
Calendar: Not working when minDate is set

### ISSUE THREAD

**Issue by sebastiangorski** [primefaces/primeng#15140]
### Describe the bug

I'm using Calendar component on my page. When I don't provide either `mindate` or `maxDate`, everything works fine. However, when I bind the date to `minDate` attribute, the Calendar component opens, but is not reacting to clicks. I can't select a day, I can't change month nor year. Please see attached video.

There is a hover effect on day cells, but once I click, it's not reacting to anything.

Here is how I set the date:

HTML Template:
```html
<p-calendar
    [formControlName]="stepInput.label"
    [minDate]="getTodayDate()"
    dateFormat="dd.mm.yy"
></p-calendar>
```

Component TS file:
```ts
protected getTodayDate(): Date {
    return new Date();
}
```

https://github.com/primefaces/primeng/assets/44788859/50b7dfd7-1ff2-48b2-9e61-8255558688a0

### Environment

localhost Angular app

### Angular version

17.3.1

### PrimeNG version

12.12.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.17.1

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Set `minDate` attribute on Calendar component
2. Open component to select date
3. Observe it's not clickable

### Expected behavior

Calendar component opens and I am able to select dates excluding the ones matching `minDate` or `maxDate`.

**Comment by maruthumj** [comment]
@sebastiangorski you cannot not pass a function directly to the minDate property since minDate's  data type is "Date" only. you should create a date variable and have to pass it to the minDate. hope this is helpful!

**Comment by MRashad26** [comment]
@maruthumj , @ThoSap 

I have a similar issue here with the reactive form, i'm using `minDate` and `maxDate` as a date variables, however, when i dynamically change the two date variables based on some criteria the `p-calendar` input field shows up as empty or shows up the placeholder value, unless i focus into the input and then focus out, the date then is displayed correctly, this happens when using `minDate` and `maxDate` as a date variables, so if i remove them, everything works fine.

Kindly appreciate your support please, Thanks

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Comment by allenaxie** [comment]
I'm encountering the same bug. Can anyone confirm if this is fixed or what the proper implementation is? I tested by passing a simple getter that returns `new Date()` but the date picker is still broken for me if `minDate` or `maxDate` attribute is used.

**Comment by akabuli** [comment]
> I'm encountering the same bug. Can anyone confirm if this is fixed or what the proper implementation is? I tested by passing a simple getter that returns `new Date()` but the date picker is still broken for me if `minDate` or `maxDate` attribute is used.

you do not need pass getter. directly instantiate new Date
