### ISSUE TITLE
p-fileUpload auto file upload not working in advanced mode

### ISSUE THREAD

**Issue by wessisaac** [primefaces/primeng#15150]
### Describe the bug

In PrimeNg's p-fileUpload, auto file-upload (auto="true") not working in advanced mode (mode="advanced") in basic mode it is working properly.

### Environment

Primeng Version 17.11.0 ("primeng": "17.11.0") angular version 17.3.0 ("@angular/core": "17.3.0")

### Angular version

17.3.0

### PrimeNG version

17.11.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.1

### Browser(s)

Chrome 122.0.6261.131, Firefox 124.0.1 (64-bit)

### Expected behavior

Auto file upload should be supported in p-fileupload's advanced mode

**Comment by cetincakiroglu** [comment]
Related to https://github.com/primefaces/primeng/issues/15117
