### ISSUE TITLE
uploadHandler of p-fileUpload is not called anymore

### ISSUE THREAD

**Issue by sbaeumlisberger** [primefaces/primeng#15154]
### Describe the bug

After update from primeng 17.6.0 to 17.11.0 the `uploadHandler` of  a `p-fileUpload` with `[customUpload]="true"` is not called anymore. An update to 17.12.0 also did not solve the problem.

### Environment

internal testing environments and local testing

### Angular version

17.3.0

### PrimeNG version

17.11.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.11.1

**Comment by RankXen** [comment]
Duplicate of #15117

**Comment by sbaeumlisberger** [comment]
Fixed in version 17.13.0. Thank you!
