### ISSUE TITLE
All Components: Styles broken

### ISSUE THREAD

**Issue by notzairdev** [primefaces/primeng#15151]
### Describe the bug

I have updated my PrimeNG components to the latest version but my styles are broken, both for the ContextMenu, MultiSelect, etc. I am using Angular 17.2.1 with the latest version of PrimeNG

![image](https://github.com/primefaces/primeng/assets/73313698/958f083c-116d-415a-9e7b-0cae5fc42e01)

### Environment

localhost and my web deployments

### Angular version

17.2.1

### PrimeNG version

17.12.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

21.2.0

### Browser(s)

Google Chrome 123.0.6312.58

**Comment by jacqueslareau** [comment]
Cannot upgrade primeng anymore, critical bugs on each version update

**Comment by ZairDeLuque** [comment]
And downgrading the version to version 15, which is the one that works best, gives me problems with NPM and I have to force everything.
