### ISSUE TITLE
Support for uploading folders

### ISSUE THREAD

**Issue by dzhavat** [primefaces/primeng#1517]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
**FileUpload** component supports only files.

**Expected behavior**
To be able to upload folders as well.

**What is the motivation / use case for changing the behavior?**
Chrome, Firefox and Edge support folder upload. PrimeNG can take advantage of those capabilities and add support folders to their FileUpload component as well.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Latest of Chrome, Firefox, Edge

**Comment by dzhavat** [comment]
Any plans on this?

**Comment by cagataycivici** [comment]
Interesting, will be checked.

**Comment by dzhavat** [comment]
Since I open the issue I managed to implement my own folder upload and am therefore not interested in this feature anymore. You can close the issue if you want.

However I still think it will be a good addition to PrimeNG and am encouraging you to consider it.

The way I implemented is by checking for `webkitGetAsEntry` function on the `event.dataTransfer` object. Something like this:

```
let dataTransfer = event.dataTransfer;

if (dataTransfer.items && dataTransfer.items[0] && dataTransfer.items[0].webkitGetAsEntry) {
    // Supports folder upload
  } else {
    // Supports only file upload
}
```

Hope you find it helpful.

**Comment by QiZZ121** [comment]
event.dataTransfer in IE9  undefined,can you tell me why, Thanks @dzhavat

**Comment by dzhavat** [comment]
It is probably because [dataTransfer](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer) is not supported on IE9.

**Comment by QiZZ121** [comment]
event.dataTransfer || event.target  do not supported on IE9.Do you know how to solve?

**Comment by dzhavat** [comment]
I'm sorry but I haven't used IE9 for years and don't even have it. So I can't really help with this one.

**Comment by Dav-Git** [comment]
Has there been any progress here?

**Comment by yigitfindikli** [comment]
We'll reconsider if there is more community feedback on this. Thank you for your report.

**Comment by dkarnati** [comment]
Team, 
Please consider re-visiting this feature. You have an edge over angular material with this control. If it can let couple more things, it would be great:
1) Folder Upload
2) Zip a folder when a folder is selected (optional), will be helpful for large uploads
3) If either of them seems not needed, please provide an option to add additional button(s) along with 3 existing buttons (in the same row as 3 buttons) so that we can add our own functionality on click of those.

**Comment by mattveraldi** [comment]
Please, reconsider to implement this feature. It is crucial for our client use case.
