### ISSUE TITLE
Flags icons for US is wrong

### ISSUE THREAD

**Issue by cetincakiroglu** [primefaces/primeng#15184]
See: https://github.com/orgs/primefaces/discussions/1534

**Comment by melloware** [comment]
I will update PrimeReact and PrimeFaces CSS and PNG @cetincakiroglu when you update this one

**Comment by cetincakiroglu** [comment]
@melloware I've updated the `flags_responsive.png` from primereact cdn also, you can make the related changes.

**Comment by melloware** [comment]
Thank you I will check today.

**Comment by melloware** [comment]
@cetincakiroglu i am confused the image looks the same with an incorrect USA flag?

I did this yesterday in PrimeReact which has correct American flag and MIT license
