### ISSUE TITLE
Component: Dropdown. After closing the overlay, the p-overflow-hidden class is not deleted if overlay mode is modal

### ISSUE THREAD

**Issue by asauvez** [primefaces/primeng#15186]
### Describe the bug

The bug looks like https://github.com/primefaces/primeng/issues/14012 but for DropDown.
I have a <p-dropdown [overlayOptions]="{mode: 'modal'}">.
When closing the overlay, I can no longer scroll the screen because <body> has still the class "p-overflow-hidden".

### Environment

16.9.1

### Angular version

16

### PrimeNG version

16.9.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v18.19.0

### Steps to reproduce the behavior

1. Create a dropdown <p-dropdown [overlayOptions]="{mode: 'modal'}">
2. Open and close the overlay.
3.Try to scroll the screen.

### Expected behavior

Class "p-overflow-hidden" should be removed from <body> when the overlay is hide.

**Comment by maruthumj** [comment]
@asauvez I'm not able to reproduce this issue. can you please create a sample app on stackblitz and share it?
