### ISSUE TITLE
Tree: Tree search stop on the first occurence on lenient mode

### ISSUE THREAD

**Issue by LinkTheFirstFlame** [primefaces/primeng#15190]
### Describe the bug

In lenient mode, the tree search result will not expand a folder that matches the search if it's child also matches the search too, whereas in strict mode it will show it.
This problem could come from this line : https://github.com/primefaces/primeng/blob/eed5029014fc329901892a5014d66e8792d28d35/src/app/components/tree/tree.ts#L1625

### Environment

Angular 17 application

### Angular version

17.2.2

### PrimeNG version

17.12.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

10.1.0

### Browser(s)

Chrome 123

### Steps to reproduce the behavior

1. Go on https://primeng.org/tree#filter
2. In the example trees, search for "doc" in the leniant tree.
3. In the strict tree search for "doc".
The lenient tree will not display every matching node.
![tree-filter-bug](https://github.com/primefaces/primeng/assets/97889988/4ee5a15f-bbd8-48bc-b04f-90c5810509f4)

### Expected behavior

In lenient mode, all result matching the search have to be visible.

**Comment by kheos31** [comment]
Same problem for us, strict mode is too strict and cannot be used because it does not show nodes inside the folder which match the search, which is a classical request for users.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
