### ISSUE TITLE
Tree: Search results are not updated when new data is added

### ISSUE THREAD

**Issue by LinkTheFirstFlame** [primefaces/primeng#15193]
### Describe the bug

If the tree is filtered by a search and it's data is updated, the search result won't display the new matching data unless the search term is updated.

### Environment

Angular 17 application

### Reproducer

https://stackblitz.com/edit/ynxmdk?file=src%2Fapp%2Fdemo%2Ftree-filter-demo.html,src%2Fapp%2Fdemo%2Ftree-filter-demo.ts

### Angular version

17

### PrimeNG version

17.12.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

10.2.3

### Browser(s)

Chrome 123

### Steps to reproduce the behavior

1. Go on https://stackblitz.com/edit/ynxmdk?file=package.json
2. Search for "file" in the tree
3. Click on "Append data" button 
4. Change the search term
![tree-search-fitler](https://github.com/primefaces/primeng/assets/97889988/fbb44007-4f11-42fb-a31d-1eeefa23c319)

### Expected behavior

The tree should call the _filter function whenever the given data is updated without updating the search term.

**Comment by kheos31** [comment]
Same behaviour on our product, tree should refresh filter if new nodes are received from input
