### ISSUE TITLE
Api: Filter Service 'İ' character problem

### ISSUE THREAD

**Issue by selcukkutuk** [primefaces/primeng#15204]
### Describe the bug

When searching in the filter service, first the removeAccents method and then the toLocaleLowerCase method are applied to the searched expression. The letter 'İ' is subjected to an incorrect transformation here.

let searchPhrase = 'İSTANBUL'; -> 'ıstanbul'
let searchedPhrase= 'istanbul'; -> 'istanbul'

[            let filterValue = ObjectUtils.removeAccents(filter.toString()).toLocaleLowerCase(filterLocale);](https://github.com/primefaces/primeng/blob/2186e27f451575ac0b0570c18aa79989970bea2c/src/app/components/api/filterservice.ts#L35)

### Environment

"primeng": "17.3.2",
"@angular/core": "~17.0.9",

### Angular version

17.0.9

### PrimeNG version

17.3.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.9.0

### Browser(s)

Google Chrome 123.0.6312.59

### Steps to reproduce the behavior

filterService.filter()

### Expected behavior

When searching for the expression İSTANBUL with the entry istanbul, the result must be found successfully.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
