### ISSUE TITLE
Multiselect: When use display chip it html elements for chips are missing

### ISSUE THREAD

**Issue by askurdjel** [primefaces/primeng#15202]
### Describe the bug

![image](https://github.com/primefaces/primeng/assets/20112496/b74bdd49-bf6f-4cdb-a658-7c3c27b6aa82)

I would like to have number of selected hidden chips, and for previous version I have directive which actually count number of hidden chip html elements, but in this version (17) when I select more than 3 elements html tags for chip are rendered only for first 3 and for others are missing

### Environment

not relevant

### Angular version

17.2.3

### PrimeNG version

17.8.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.11.0

**Comment by robGardiner01** [comment]
There's already an attribute you can add called maxSelectedLabels which sets the max number of chips to display. If you want it to render all of them just add maxSelectedLabels="this.cities.length"

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
