### ISSUE TITLE
Table: No events emitted from dynamic <ng-content *ngTemplateOutlet> templates 

### ISSUE THREAD

**Issue by ilkomiliev** [primefaces/primeng#15219]
### Describe the bug

I am trying to implement reusable table component, where I can pass the corresponding pTemplates as @Input() and utilize default templates where customization is not necessary, i.e.:

`
...
<ng-template pTemplate="body" let-product>
    <ng-container *ngTemplateOutlet="bodyTmpl || defaultBodyTmpl; context: { $implicit: product }"></ng-container>
</ng-template>
...
`

and respectively:

`@Input() bodyTmpl!: TemplateRef<any>;`

Everything works fine, but the events are not anymore emitted. If I replace the dynamic template with the templates' code then the events are available.

### Environment

see stackblitz

### Reproducer

https://stackblitz.com/edit/github-c6s33v?file=src%2Fmain.ts,src%2Fapp%2Fapp.component.html

### Angular version

17.3.3

### PrimeNG version

17.12.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

see stackblitz

### Browser(s)

all

### Steps to reproduce the behavior

1. Goto https://stackblitz.com/edit/github-c6s33v
2. Open the Console
3. After the table is loaded select some row

### Expected behavior

1. The row is marked as selected
2. onRowSelected with the event details is printed in the console

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
