### ISSUE TITLE
inputOtp: Does not work as expected with reactive forms

### ISSUE THREAD

**Issue by yossef7525** [primefaces/primeng#15225]
### inputOtp: Does not work as expected with reactive forms

The reaction I expect after filling the first character, that the input will automatically move in focus mode to the second position, unfortunately when I wrap the input with formControl this does not happen, the focus remains in the first position.

### Environment

- win 11
- chrome 123.0
- angular 17

### Reproducer

[stackblitz](https://stackblitz.com/edit/github-jmkjzu?file=src%2Fapp%2Fapp.component.html)

### Angular version

17

### PrimeNG version

17

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20

### Browser(s)

chrome 123

**Comment by yarikwest** [comment]
while using binding, you should do it in brackets: [formControl]="otp"
