### ISSUE TITLE
Calendar popover closing issue

### ISSUE THREAD

**Issue by ardeshirj** [primefaces/primeng#1522]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

**Current behavior**
Calendar popup stay open when you click outside of the calendar until you hover back over it.

**Expected behavior**

Calendar popup should close out once the user click outside of the calendar popup area.

**Minimal reproduction of the problem with instructions**
Checkout the `gif` below:

![primeng-datepicker](https://cloud.githubusercontent.com/assets/6003742/20981708/97597094-bc6a-11e6-918a-53f5240731e0.gif)

**What is the motivation / use case for changing the behavior?**
User no longer wants to see the popup calendar once they click away from the calendar.

**Please tell us about your environment:**
MacOSX El Capitan (10.11.6), npm 3.10.8, webpack-dev-server

* **Angular version:** 2.0.X
Angular 2.1.1

* **PrimeNG version:** 2.0.X
Primeng 1.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 54
Firefox 49
Safari 10
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.0.0

* **Node (for AoT issues):** `node --version` =   6.9.1

**Comment by nguni52** [comment]
I'm having the same issue. Any suggestions on how to solve this?

**Comment by sudheerj** [comment]
I'am not able to replicate this issue.Which version you tried.Are you able to replicate the issue in showcase.

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/MxSw4qOuwDfq7rLO7jrR?p=preview
