### ISSUE TITLE
Keyboard shortcuts support to primeng

### ISSUE THREAD

**Issue by anikets43** [primefaces/primeng#1523]
Hi @cagataycivici 

Is there keyboard shortcuts features available to primeng like Kendo UI? If it doesn't have, is it possible to wrap up primeng and create custom a component to include keyboard shortcuts features?

Please suggest.

Thanks,
Aniket

**Comment by cagataycivici** [comment]
The issue is too broad, many components have support for it. If not please create separate tickets like keyboard support for component xxx. Thank you.
