### ISSUE TITLE
p-dataTable need improove performance with "*ngIf" expression

### ISSUE THREAD

**Issue by nexxoft** [primefaces/primeng#1525]
I found that when the mouse movement on ANY component (not exactly p-dataTable) every time called the function inside *ngIf expression in p-dataTable and all functions inside "template" of every column.
It would be more better performance if have a setting to *ngIf works only at the first drawing or may be on something else condition.
In our project p-dataTable may show 1000 rows and more. At that count of rows performance is very poor (on row hilights and click events)

primeng 1.0.1
angular 2.1.1
typescript 2.0.2
browser chrome (may be on other)

**Comment by izll** [comment]
Hi, It's same: https://github.com/primefaces/primeng/issues/706

**Comment by SteveDowsett** [comment]
Is there going to be a fix for this? The performance needs addressing or another choice of datagrid for me

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
