### ISSUE TITLE
Table: expandedRowKeys property broken in primeng 17.13.0

### ISSUE THREAD

**Issue by N0153** [primefaces/primeng#15257]
### Describe the bug

It is not possible to use the _expandedRowKeys_ to programmatically control the expanded status of each row in a **Table** when using **primeng** _17.13.0_. When attempting to manually expand a row the following message is returned
```
ERROR TypeError: Cannot create property 'key' on boolean 'true'
    at Table.toggleRow (vendor.js:200476:42)
    at RowToggler.onClick (vendor.js:203006:15)
    at RowToggler_click_HostBindingHandler (vendor.js:203023:22)
    at executeListenerWithErrorHandling (vendor.js:78612:12)
    at wrapListenerIn_markDirtyAndPreventDefault (vendor.js:78644:18)
    at HTMLButtonElement.<anonymous> (vendor.js:99169:112)
    at _ZoneDelegate.invokeTask (polyfills.js:8235:171)
    at vendor.js:67846:49
    at AsyncStackTaggingZoneSpec.onInvokeTask (vendor.js:67846:30)
    at _ZoneDelegate.invokeTask (polyfills.js:8235:54)
```

The only solution for now is to rollback to **primeng** _17.12.0_ or lower.

### Environment

**angular** _17.3.3_
**primeng** _17.13.0_

### Reproducer

https://stackblitz.com/edit/3uwgk4

### Angular version

17.3.3

### PrimeNG version

17.13.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.0

### Steps to reproduce the behavior

1. Open the StackBlitz reproducer
2. Notice that the rows are not expanded by default, although they should be
3. Try expanding a row
4. Check the console for the error

### Expected behavior

It should be possible to control the **expanded** state of a **Table** rows using the _expandedRowKeys_  property.

**Comment by Clemzd** [comment]
It works with version 17.12.0

**Comment by BGBRWR** [comment]
https://github.com/primefaces/primeng/pull/15243 fixes this.

**Comment by mehmetcetin01140** [comment]
Hi, this issue is not present in the latest version of PrimeNG (17.17.0). Please try it with the latest version. I'm closing the issue.
