### ISSUE TITLE
splitbutton

### ISSUE THREAD

**Issue by AMZALE** [primefaces/primeng#15251]
### Describe the bug

splitbutton - there is arrow icon, but after clicking, it doesn't rotate, and there is no any css classes, properties which says that menu is showed 

### Environment

Angular 16

### Angular version

16

### PrimeNG version

16.9.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18

### Browser(s)

Chrome

### Steps to reproduce the behavior

splitbutton - there is arrow icon, but after clicking, it doesn't rotate, and there is no any css classes, properties which says that menu is showed 

### Expected behavior

rotate icon or need css properties which says that menu is showed

**Comment by volvachev** [comment]
Hi, has this worked before? (rotated icon)

At the moment I see that there is an `aria-expanded` attribute, perhaps this is enough for your needs?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
