### ISSUE TITLE
p-table: columnFilter of type numeric are no longer working

### ISSUE THREAD

**Issue by PaulSchult** [primefaces/primeng#15264]
### Describe the bug

If you have a simple p-table with a p-colum-filter that is of type numeric, you are not able to use the filter feature of the given columFilter.

If you try to open the columnFilter and try to type some numbers nothing will happen. The following error will be displayed inside of the console.

![image](https://github.com/primefaces/primeng/assets/40341262/84e1edc0-046e-422a-a025-26f9beed44ef)

This seems to be the result of the added input transforms. These will return "NaN" if the value is undefined, which in return breaks the following formatting logic of the input. 
![image](https://github.com/primefaces/primeng/assets/40341262/671c4d3f-cafa-4c09-b155-24b4dedbd292)

### Environment

It's a simple p-table with some columns, forked from the offical primeNg table example.

### Reproducer

https://stackblitz.com/edit/xaehyx?file=src%2Fapp%2Fdemo%2Ftable-filter-menu-demo.html

### Angular version

17.3.1

### PrimeNG version

17.13.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20

### Steps to reproduce the behavior

1. Create a p-table with at least one p-columnFilter of the numeric type
2. Open the columnFilter of the numeric column
3. Try to add a number the input for filtering
4. Notice that it doesn't work

**Comment by PaulSchult** [comment]
Are you sure? The PR doesn't change any transform that correlates with the max/minFractionDigits input.

**Comment by PaulSchult** [comment]
I would probably suggest to add `transform: (value: unknown) => numberAttribute(value, null)` to the @Input() element for these two. This doesn't break the `Intl.NumberFormat` number formatting. If you like I could open a separate PR for this issue.

**Comment by BGBRWR** [comment]
I ended up removing the transform for `minFractionDigits` and `maxFractionDigits` on the Table and InputNumber components. `minFractionDigits` will default to zero if it is undefined. `maxFractionDigits` will get set dynamically to the ISO 4217 currency code if it is undefined.

**Comment by PaulSchult** [comment]
Thanks

**Comment by johanneszelger** [comment]
I can confirm it does no longer work. A temp workaround is to set [minFractionDigits]="x" [maxFractionDigits]="x" to a value that works for you.
