### ISSUE TITLE
CurrentPageReport for Paginator

### ISSUE THREAD

**Issue by lonyel** [primefaces/primeng#1526]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/NtWWnN

**Current behavior**
Currently, the p-datatable 's pagination only show pageno and page navigation button,can't add total page,total data-size ctc.

**Expected behavior**
We need customize the content at pagination bar. Ex rec-count,page-count,etc.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
In real business system,the user need known how mach record info then to do next step.

**Please tell us about your environment:**
Windows 10

* **Angular version:** 2.2.0

* **PrimeNG version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** TypeScript 2.0.10

* **Node (for AoT issues):** `6.9.1` =

**Comment by guntram** [comment]
This can be easily achieved by adding extra info manually below the dataTable, see
http://stackoverflow.com/questions/41287776/how-to-add-custom-text-to-primeng-paginator/43780642#43780642

**Comment by bossqone** [comment]
any updates on this?

**Comment by smitpsanghavi** [comment]
Waiting for this feature. Is it scheduled for release any time soon?

**Comment by dario-frongillo** [comment]
waiting this feature

**Comment by smitpsanghavi** [comment]
@lonyel This can be closed since it is available since v7

**Comment by yigitfindikli** [comment]
Available since v7.
