### ISSUE TITLE
Component: Multiselect and dropdown

### ISSUE THREAD

**Issue by FelixTwoli** [primefaces/primeng#15267]
### Describe the bug
Missing `id` or `name` attribute
Despite specifying a `<label for=FORM_ELEMENT>` and an `id` with the same `name`, the browser console throws an error stating that a form field should have an id or name attribute. This could potentially affect form submission and autofill functionality.

### Environment

Development, staging, and production environments

### Angular version

17.3.1

### PrimeNG version

17.10.0

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

20.11.0

### Steps to reproduce the behavior

1. Use the dropdown or multi-select component in the PrimeNG UI library.
2. Specify a `<label>` with a for attribute matching the id of the form field.
3. Ensure that the id attribute is present in the form field.
3. Observe the browser console for the error message mentioned.

### Expected behavior

The components should have both `id` and `name` attributes to ensure proper form functionality and accessibility.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
