### ISSUE TITLE
p-table passing any expandedRowKeys will cause table to not expand anymore

### ISSUE THREAD

**Issue by ymg2006** [primefaces/primeng#15270]
### Describe the bug

p-table binding any [expandedRowKeys] will cause table to not expand anymore.

### Environment

Angular CLI: 17.3.3
Node: 20.12.1
Package Manager: npm 10.5.0
OS: win32 x64

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1703.3 (cli-only)
@angular-devkit/core         17.3.3 (cli-only)
@angular-devkit/schematics   17.3.3 (cli-only)
@schematics/angular          17.3.3 (cli-only)

### Angular version

17.3.3

### PrimeNG version

17.13.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.12.1

### Steps to reproduce the behavior

just bind any object to expandedRowKeys it will break expanding of table

### Expected behavior

Work like 17.12.0, I will create a pull request to fix.

**Comment by ymg2006** [comment]
#15271 solves this issue
#15271

**Comment by cetincakiroglu** [comment]
Fixed in https://github.com/primefaces/primeng/pull/15243
