### ISSUE TITLE
Calendar: Date Grid Keyboard Support is not working

### ISSUE THREAD

**Issue by ramyanuthal** [primefaces/primeng#15276]
### Describe the bug

When setting 'Time' for input field, holding down the up/down arrows should continue to scroll the numbers. Currently, this feature is not working. The arrows must be clicked each time the user wants the number to change.

### Environment

My Environment details:
Angular: 16.2.9
node: 16.14.0
Primeng: 16.9.1
@ngrx/store": "^16.3.0"

### Angular version

16.2.9

### PrimeNG version

 16.9.1

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14.0

### Browser(s)

Microsoft Edge

### Steps to reproduce the behavior

When setting 'Time' for input field, the up/down/side arrows should continue to scroll the numbers. 

### Expected behavior

Grid Keyboard Support should work with up/down/side arrows should continue to scroll the numbers.

**Comment by cetincakiroglu** [comment]
Hi,

Could you please create a stackblitz example so we can identify the issue?
