### ISSUE TITLE
MultiSelect Component: onSelectAllChange() logic in VirtualScroll is incorrect.

### ISSUE THREAD

**Issue by kroger-renu** [primefaces/primeng#15273]
### Describe the bug

If we do not add VirtualScroll in the multiselect, onSelectAllChange logic works fine, clicking on Header Checkbox selects only the valid options even after filtering. But to improve the performance of the multiselect, if we add VirtualScroll the onSelectAllChange() logic marks all the items present in the list as checked. 
Expected behaviour- it should check if filtering is applied or not, if filters are there then only visible valid options should be selected/deselected (as in the actual behavior of Multiselect without VirtualScroll in v17.11.0). Handle select and deselect both the scenarios.
Actual:
![Screenshot (1)](https://github.com/primefaces/primeng/assets/151019703/12146e46-deae-4b4a-8c41-2b2b59b0dadc)
![Screenshot (3)](https://github.com/primefaces/primeng/assets/151019703/6b0e7d3a-59f6-4ca1-8527-ca628e8ca7f8)

Expected: 
![Screenshot (4)](https://github.com/primefaces/primeng/assets/151019703/48dccd41-6f9c-4efb-b319-6a7776ed5f47)

Another bug, if we have previously selected any item from the multiselect and search any keyword using filter. Clicking on SelectAll checkbox will reset previously selected items and select only the visible ones.
Actual:
![Screenshot (8)](https://github.com/primefaces/primeng/assets/151019703/dd0ccd70-0991-4ef5-9751-dc7fd99eb0f4)
![Screenshot (7)](https://github.com/primefaces/primeng/assets/151019703/4cdf92b9-51c9-4397-bbcf-2eda4dd85f5c)

Expected: Selected Rome initially, then searched "n", on clicking selectAll now 4 items should be there (Rome, New York, London, Istanbul) instead of new 3 (New York, London, Istanbul).
![Screenshot (6)](https://github.com/primefaces/primeng/assets/151019703/806e94e3-8b47-4acf-98f1-bf1a74fc4cec)
![Screenshot (5)](https://github.com/primefaces/primeng/assets/151019703/cc62d2f0-2254-4f88-bb60-6ba7d5aa3e7d)

### Environment

Angular CLI: 17.3.3
Angular: 17.3.2
Node: 20.9.0
zone.js: 0.14.4
Typescript: 5.2.2
Package Manager: npm 10.1.0
OS: win32 x64

### Angular version

17.3.2

### PrimeNG version

17.11.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.9.0

### Steps to reproduce the behavior

Add VirtualScroll in your multiselect component, add the given onSelectAllChange() logic in the primeng demo example or you can directly reproduce this in the example demo given on the primeng website.
1. Go to the multiselect dropdown, 
2. Click on the search filter, search for some keyword,
3. Click on Select All header checkbox
4. You will see all the items present in the dropdown will be marked "checked", instead of **only** visible optionsList after filtering based on the search input.

### Expected behavior

SelectAll should only select/deselect the visible option list if filtering is applied.

**Comment by joshi-renu** [comment]
A new and enhanced issue has been created, this issue can be deleted now.

**Comment by kroger-renu** [comment]
A new and enhanced issue has been created, this issue can be deleted now.
