### ISSUE TITLE
pDroppable: pDroppableDisabled is only evaluated after view init

### ISSUE THREAD

**Issue by playtinum** [primefaces/primeng#15282]
### Describe the bug

The evaluation on if the something can be dropped is only evaluated after view init. This makes it impossible to block dropping for distinct elements and enable it for others to "drag time". 

See: 
https://github.com/primefaces/primeng/blob/4f8844429cea3696d345ed6c912d337c2e9e6707/src/app/components/dragdrop/dragdrop.ts#L203

### Environment

primeng version 17.12

### Angular version

17.3.0

### PrimeNG version

17.12

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.13.0

**Comment by playtinum** [comment]
Would a PR that targets this issue be accepted or are the efforts be generally wasted?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
