### ISSUE TITLE
Split Button: Nested is not working correctly on mobile

### ISSUE THREAD

**Issue by tomhuber96** [primefaces/primeng#15288]
### Describe the bug

The nested Split button does not work correctly on mobile. Deeper levels are not visible. 
![image](https://github.com/primefaces/primeng/assets/52798757/19837597-379d-4820-9313-013db906f671)

On iOS Chrome the CSS breaks and is horizontal scrollable. 

I guess this issue would also occur too, if the button is positioned on the right side. 

### Environment

Tested on v17.13. and v17.9. on Chrome. 

Can be tested in the demo https://primeng.org/splitbutton

### Angular version

17

### PrimeNG version

17.13

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11

### Browser(s)

Chrome

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
