### ISSUE TITLE
TriStateCheckbox edit inside p-column

### ISSUE THREAD

**Issue by tigrenok00** [primefaces/primeng#1528]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

I have a TriStateCheckbox inside a p-colun template in a p-datatable. I want it to be editable via TriStateCheckbox GUI. 
However, when the row is set to editable, when I click the checkbox, instead of checkbox changing state, the cell displays the TRUE or FALSE text value, like when editing a regular text or number cell.
If the row is not set to editable, then the checkbox is disabled.
Please help.

* **Angular version:** 2.1.0

* **PrimeNG version:** 1.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
