### ISSUE TITLE
Calendar: minDate bug when using 12 hourFormat

### ISSUE THREAD

**Issue by synes85** [primefaces/primeng#15286]
### Describe the bug

When I used the calendar component with [showTime]="true" [hourFormat]="12" properties and set a minDate to PM, after the time reached minDate, decrementing the hour resulted a strange behavior. Pressing the button decreased the hour and also changed the date.

https://github.com/primefaces/primeng/assets/18285471/ed97da04-3ac0-4558-8176-0c5ded451507

### Environment

Stackblitz

### Reproducer

https://stackblitz.com/edit/1k7gzq

### Angular version

17.3.1

### PrimeNG version

17.13.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.0

### Browser(s)

Chrome 123

### Steps to reproduce the behavior

1. Click on calendar input
2. Select first possible day and time on calendar popup (which is the minDate)
3. Click on hour decrementation button

**Comment by RogueTea** [comment]
Hello, I am currently looking into this. I've drafted out a solution could you please tell me if this is the correct behaviour you're looking for. I've attached a video below 
[29_04_2024, 17_06_15 - Screen - Untitled video.webm](https://github.com/primefaces/primeng/assets/59694437/5d02a071-ab9a-4b9a-b45a-8af2547384c5)

**Comment by synes85** [comment]
It looks good. Thank you!
