### ISSUE TITLE
[IE 11; p-dropdown] Unexpected change of .ui-dropdown-panel width

### ISSUE THREAD

**Issue by stawr93** [primefaces/primeng#1529]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

http://plnkr.co/edit/ef6ywd

**Current behavior**

If list of dropdown options contains some very long value (which exceeds .ui-dropdown width), in IE11 when user opening options list its width changes unexpectedly.

**Expected behavior**

No unexpected width changing.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 8.1, VS Code

* **Angular version:** 2.1.1

* **PrimeNG version:** 1.0.0

* **Browser:** [IE 11]

 
* **Language:** [TypeScript 2.0.3]

* **Node (for AoT issues):** `node --version` =   v6.6.0

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
