### ISSUE TITLE
MultiSelect Component: onSelectAllChange() logic in VirtualScroll is incorrect (filter perspective is missing).

### ISSUE THREAD

**Issue by joshi-renu** [primefaces/primeng#15294]
### Describe the bug

When VirtualScroll is not incorporated in the Multiselect, the onSelectAllChange logic functions as expected. Specifically, clicking on the header checkbox results in the selection of only the valid options, even after applying filters.

However, when VirtualScroll is implemented to enhance the Multiselect's performance, a discrepancy arises. The onSelectAllChange() logic seems to mark all items present in the list as selected, regardless of the applied filters.

**Expected Behavior**
The anticipated behavior is for the logic to determine whether filtering has been applied or not. If filters are present, then only the visible and valid options should be selected or deselected. This functionality aligns with the actual behavior of Multiselect without VirtualScroll in version 17.11.0. The expectation is for this to handle both selection and deselection scenarios appropriately.
![Screenshot (159)](https://github.com/primefaces/primeng/assets/92154838/818a5692-706b-4c15-bf09-8c921713cb9f)

**Actual Behavior**
The implemented logic selects/deselects all the items in the options list, even with filters.
![Screenshot (160)](https://github.com/primefaces/primeng/assets/92154838/569fb792-ea58-4a66-8cc8-0761ed8c78df)
![Screenshot (161)](https://github.com/primefaces/primeng/assets/92154838/0646146b-f723-4d9b-b049-7735e16e258d)

### Environment

Angular CLI: 17.3.3
Angular: 17.3.2
Node: 20.9.0
zone.js: 0.14.4
Typescript: 5.2.2
Package Manager: npm 10.1.0
OS: win32 x64

### Angular version

17.3.2

### PrimeNG version

17.11.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.9.0

### Steps to reproduce the behavior

1. Implement VirtualScroll in the Multiselect component and add the onSelectAllChange() logic as provided in the PrimeNG demo example. This can also be reproduced directly on the demo example given on the PrimeNG website.
2. Navigate to the Multiselect dropdown.
3. Click on the search filter and enter a keyword.
4. Click on the Select All header checkbox.
5. You will observe that all items present in the dropdown, not just those matching the filter criteria, are marked as "checked".

### Expected behavior

The anticipated behavior is for the SelectAll checkbox to only select/deselect the visible options in the dropdown list, provided a filter is applied. The SelectAll checkbox should not affect items that do not match the applied filter criteria.
![Screenshot (159)](https://github.com/primefaces/primeng/assets/92154838/20b2433f-cd35-447f-8661-18575bf34a6c)

**Comment by cetincakiroglu** [comment]
Hi,

This issue is superseeded by https://github.com/primefaces/primeng/issues/15373

Thanks a lot for reporting the issue, we'll add new template options and update the demo to make this possible.

Closing the issue.

**Comment by joshi-renu** [comment]
I see the changes to headercheckbox template- selectAll logic has been incorporated but on deselecting an item, selectAll should also deselect, which is still a bug.
