### ISSUE TITLE
p-inputNumber: Disabled is not working correcly when using ReactiveForms

### ISSUE THREAD

**Issue by GabrielAPineiro** [primefaces/primeng#15299]
### Describe the bug

I have a wrapper component which is implementing ControlValueAcessor, and I'm using the setDisabledState from the primeng input. It's not working correctly when I start the form control as disabled. The input appears to be disabled, but once I click on it I'm able to edit the value, and then the field gets disabled for good.
![inpuNumber-bug](https://github.com/primefaces/primeng/assets/104081429/1b9407da-3074-43d2-adbc-e4b6297de73d)

### Environment

I use a windows 11 laptop. Angular 17.3.5, PrimeNG 17.12.0 and node v20.10.0

### Reproducer

https://stackblitz.com/edit/github-daas27-pb8btj?file=src%2Fapp%2Fapp.component.ts

### Angular version

17.3.5

### PrimeNG version

17.12.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.10.0

### Steps to reproduce the behavior

1. Load component with form initial state disabled
2. See component looks disabled (inputDisabled is returning true, which shows the red border)
3. Click inside the component, red border disappears and its possible to edit the value

### Expected behavior

Component is disabled from the beginning and stays disabled until we enable it in the ReactiveForm

**Comment by cetincakiroglu** [comment]
> Hi, in your example you can remove the `[disabled]="disabled ?? false"` and control disabled state via `formControl`. Everything will work as expected.

@GabrielAPineiro Please try this, closing the issue.
