### ISSUE TITLE
DataScroller: Lazy loading event 'first' property 

### ISSUE THREAD

**Issue by mattem** [primefaces/primeng#153]
Maybe I'm using this incorrectly, but when using the DataScroller with lazy loading, the `first` property of the event does not match that of the index of top visible row in the list when scrolling up (returning from the bottom of the list), the number just increases by `rows` each time. 

For example, markup is 

``` xml
<p-dataScroller [value]="rows" [inline]="true" [rows]="20" scrollHeight="500px" [lazy]="true" (onLazyLoad)="onLazyLoad($event)">
    <template #row>
        <p>{{row.SeqId}} {{row.MainTitle}}</p>
    </template>
</p-dataScroller>
```

The `onLazyLoad` event handler just logs out the event. 
Is this the expected behavior? The demo does not seem to do this? Using version 0.9.1

**Comment by cagataycivici** [comment]
Looks like a bug, being worked on.

**Comment by cagataycivici** [comment]
Oh, you mean going up, but the load is only called when going down with scroller. It should not be called when scrolling up to view already loaded elements.

**Comment by mattem** [comment]
Here is a plunker that shows this behaviour. 
http://plnkr.co/edit/PHuVeQB5cLxMYSORepUf?p=preview

I guess my use case here is not actually infinite scrolling, but more just using it for the lazy loading of items in to the list. When the bottom of the list is reached, and no more items are available to be loaded in, then the scrolling exhibits this behaviour. It can also be reproduced by not adding any items to the list within the `onLazyLoad` callback. 
I appreciate that this may not be supported, as the use case is slightly different.

**Comment by cagataycivici** [comment]
This seems like the expected behavior for me.
