### ISSUE TITLE
<p-columnFilter> not working with <p-treeTable>

### ISSUE THREAD

**Issue by imoitra007** [primefaces/primeng#15316]
### Describe the bug

I am trying to use **p-columnFilter** inside  **p-treeTable**, it is giving Null Injector issue in browser console.

![image](https://github.com/primefaces/primeng/assets/42399766/09888786-9b44-42f0-9f6b-f137a947da43)

### Environment

 "primeng": "16.0.2",

Angular CLI: 16.2.10
Node: 16.20.2
Package Manager: npm 8.19.4
OS: win32 x64

Angular: 16.2.12
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.10
@angular-devkit/build-angular   16.2.10
@angular-devkit/core            16.2.10
@angular-devkit/schematics      16.2.10
@angular/cli                    16.2.10
@schematics/angular             16.2.10
rxjs                            7.8.1
typescript                      4.9.5
webpack                         5.89.0
zone.js                         0.13.3

### Angular version

16.2.10

### PrimeNG version

16.0.2

### Build / Runtime

Angular CLI App

### Language

ES6

### Node version (for AoT issues node --version)

v16.20.2

**Comment by horenko** [comment]
Same problem. Any update pelase?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
