### ISSUE TITLE
OrderList: Unable to insert space into input component

### ISSUE THREAD

**Issue by spahicharis** [primefaces/primeng#15326]
### Describe the bug

While using input element inside p-orderList component one is not able to insert space into it. Here is the screenshot example:

![image](https://github.com/primefaces/primeng/assets/11409141/8de4107a-1836-43f7-b3b6-17263efd433e)

![image](https://github.com/primefaces/primeng/assets/11409141/26a837eb-21f9-4d92-b425-f6cc6198b8c2)

### Environment

Issue is easily reproducible on latest primeng version 17.14.1.

### Angular version

17.0.8

### PrimeNG version

17.14.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.1

### Steps to reproduce the behavior

Prerequisites
Have installed Angular app and setup primeng components
Import p-orderList component

Steps to reproduce
1. Edit p-orderList template (pTemplate="item")
2. Put basic input field in pTemplate
3. Run app using command ng serve
4. Try to put space into input field

### Expected behavior

I should be able to insert space into input.

**Comment by mjlux** [comment]
The default behaviour of a OrderListItem on space is to select/unselect the item.
We faced the same issue and resolved it by adding an `(keydown.space)="$event.stopPropagation()"` EventListener to the input.
Hope this helps.
