### ISSUE TITLE
Question: Is it possible to define a separate Paginator for a Table

### ISSUE THREAD

**Issue by mconner** [primefaces/primeng#15321]
I'm trying to mimic the styling/layout of an existing application (JSF).  pagination is looks roughly like:

< 1 2 3 >

Caption and some other things

Table goes here

< 1 2 3 >

I'd like to define a paginator (or paginators) and then attach it to the table.

Is this possible? I tried setting paginator to false, but then it doesn't paginate at all, even though I've got rows set.  I could presumably enable the paginator, and then set display: none on the element, but that seems somewhat kludgey.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
