### ISSUE TITLE
Component: AutoComplete Suggestions Async Pipe PROBLEM

### ISSUE THREAD

**Issue by 1c3f0x84** [primefaces/primeng#15327]
### Describe the bug

Autocomplete control doesn't work with the Async Pipe + a pipe delay.

It only works the first time! The second time there are no suggestions.

See [stackblitz](https://stackblitz.com/edit/kxgavc?file=src%2Fapp%2Fdemo%2Fautocomplete-reactive-forms-demo.ts,package.json)

### Environment

Angular

### Reproducer

https://stackblitz.com/edit/kxgavc?file=src%2Fapp%2Fdemo%2Fautocomplete-reactive-forms-demo.ts,package.json

### Angular version

17.3.1

### PrimeNG version

17.14.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.0

**Comment by 1c3f0x84** [comment]
Can someone help me with this?

**Comment by 1c3f0x84** [comment]
@TaherShbnnzhd @DerekLiang @csokun @Skyr @cetincakiroglu ?!?

**Comment by 1c3f0x84** [comment]
It's the same as #5030 !

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Comment by davidguedes** [comment]
Alguma solução? Sigo com o mesmo problema. Angular na versão **12.1.2** e PrimeNG na versão **12.2.3**.
