### ISSUE TITLE
TabMenu: activeItemChange duplicate invocation

### ISSUE THREAD

**Issue by parked-toes** [primefaces/primeng#15329]
### Describe the bug

Use stackblitz example from documentation and add logging of executions:

```
onActiveItemChange(event: MenuItem) {
    this.activeItem = event;
    console.log(`Executed ${this.i++} times` );
}
```

Log:
When application inits:
Executed 1 times

1 time click on a tab:
Executed 2 times
Executed 3 times
Executed 4 times

Src:
https://stackblitz.com/edit/air4fc?file=src%2Fapp%2Fdemo%2Ftab-menu-controlled-demo.ts,package.json

### Environment

primeng-tab-menu-controlled-demo

### Angular version

17.3.1

### PrimeNG version

17.14.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Browser(s)

chrome

### Expected behavior

No initial and duplicate firing

**Comment by IceBreakerG** [comment]
Just chiming in, I'm seeing the same issue with the TabMenu component. My version is:

- Angular 17.2.0
- primeng 17.15.0

**Comment by stevenrlp** [comment]
Same issue still present.

- Angular 18.1.0
- primeng 17.18.6

**Comment by OmkarJ13** [comment]
I am also facing this issue

**Comment by alimdi** [comment]
Same Issue here

**Comment by alimdi** [comment]
looks like fixed on 17.18.9

**Comment by preetamjakhmola** [comment]
> looks like fixed on 17.18.9

No, I am using 17.18.9 but it persists.

**Comment by alimdi** [comment]
True, it stopped and now happening again on 17.18.9. There somehow a reason that I can't figure out.

**Comment by preetamjakhmola** [comment]
due to that i used different way to solve it. i tried Click event.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
