### ISSUE TITLE
Tree: Expanding a node scrolls to incorrect position when using Virtual Scroll

### ISSUE THREAD

**Issue by LennartMart** [primefaces/primeng#15336]
### Describe the bug

When using VirtualScroller, expanding a node scrolls to the wrong position in the tree. It's also broken on the documentation page: https://primeng.org/tree#preload . 

### Environment

17.14.1

### Reproducer

https://stackblitz.com/edit/2uz5xq?file=package.json

### Angular version

17.3.1

### PrimeNG version

17.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.0

### Steps to reproduce the behavior

1. Scroll down in the tree
2. Choose a node that wasn't initially visible
3. Expand the node
4. The tree will scroll upwards, the expanded node is out of sight.

### Expected behavior

The expanded node should stay visible.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
