### ISSUE TITLE
Component: Dropdown panel stay opened

### ISSUE THREAD

**Issue by mristov** [primefaces/primeng#15331]
### Describe the bug

Dropdown panel stay opened after we try to press arrow-down on keyboard on last option on showed panel.
It will be good when we test this to turn on Narrator from Windows

### Environment

PrimeNG 17.12
Windows 11

### Reproducer

https://primeng.org/dropdown

### Angular version

17.0.5

### PrimeNG version

17.12

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.1

### Browser(s)

Chrome

### Steps to reproduce the behavior

Test scenario is when we try to open **Basic** example and navigate through

<img width="796" alt="image" src="https://github.com/primefaces/primeng/assets/150306240/1cc4d837-116f-4f6f-a683-710db1b67da3">

**Comment by Sinan997** [comment]
Hi @mristov, I didn't understand. Could you give more detail?

Does problem continues in version `17.17.0`?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
