### ISSUE TITLE
SelectButton: Two attributes for the same behaviour

### ISSUE THREAD

**Issue by Thomas-Schindler** [primefaces/primeng#15334]
### Describe the bug

The <p-selectbutton> component has two attributes which are both switching the behaviour of the component regarding the clearing of the selection:

"unselectable", description: "Whether the selection can be cleared."
"allowEmpty", description: "Whether selection can not be cleared."

This is quite confusing, as it is not clear which one to use and more importantly, which one is winning in case of contradictionary values.
What happens if I set "unselectable" to "true" and "allowEmpty" to "false". Is it possible to clear the selected value or not?

![image](https://github.com/primefaces/primeng/assets/7558409/57d92628-8587-41de-bbe3-ee49a89d78a4)

### Environment

We are currently using PrimeNG 16.9.1.

### Angular version

16.2.12

### PrimeNG version

16.9.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.1

### Expected behavior

I think it would be easier to have only on attribute, either "unselectable" or "allowEmpty".  I would prefer "allowEmpty"

**Comment by maruthumj** [comment]
@Thomas-Schindler I will start work on this one

**Comment by maruthumj** [comment]
@Thomas-Schindler I afraid that removing any one of the properties might cause issues for the people who are already using it.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
