### ISSUE TITLE
inputOtp: Replace character does not work when all inputs are filled in

### ISSUE THREAD

**Issue by wolfvandenbussche** [primefaces/primeng#15330]
### Describe the bug

The replacing of a character stops working when all the inputs are filled in.

### Environment

I used https://primeng.org/inputotp

### Angular version

17

### PrimeNG version

17.14.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20

### Steps to reproduce the behavior

Add inputOtp with length 4
type 2 numbers
![image](https://github.com/primefaces/primeng/assets/43757937/9b0cb354-2876-4643-b297-59582cf5ad00)
select the first input
type a number => the initial number is replaced
![image](https://github.com/primefaces/primeng/assets/43757937/4e53eef4-68da-47d2-9437-57da9afd4af7)
This works properly

Now type 4 numbers
select the first input
type a number => nothing happens, then number does not get replaced.
Tab keyboard function also stops working here

### Expected behavior

I expect the behavior to stay the same when it's fully filled in

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
