### ISSUE TITLE
Table's select all checkbox shouldn't select the checkbox which are disabled

### ISSUE THREAD

**Issue by Bhaveshshah777** [primefaces/primeng#15338]
### Describe the bug

When user clicks on p-tableHeaderCheckbox all p-tableCheckbox in that table are selected. Even those which are disabled. 

Expectation: It should not select those record whose p-tableCheckbox is disabled.

### Environment

Windows 11, Angular 12, Node 14.21.3, PrimeNg 16

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-hjrvss?file=src%2Fmain.ts

### Angular version

17.2.0

### PrimeNG version

17.14.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.0

### Browser(s)

Mozilla Firefox

### Steps to reproduce the behavior

1. Wait for data to load in the p-table
2. Click on p-tableHeaderCheckbox (select all) checkbox
3. Observe the selection

Actual result: Even the disabled checkboxes are selected.

### Expected behavior

When select all checkbox is selected, all disabled row should not be selected

**Comment by Bhaveshshah777** [comment]
@cetincakiroglu

**Comment by cetincakiroglu** [comment]
@Bhaveshshah777 could you please update the stackblitz link, it's broken.

**Comment by Bhaveshshah777** [comment]
@cetincakiroglu I have updated the stackblitz link, could you try again?

**Comment by cetincakiroglu** [comment]
Please update the example, it's not clear.
![Screenshot 2024-05-03 at 16 01 07](https://github.com/primefaces/primeng/assets/69278826/806dbca7-4971-43d4-9d4c-c5915f294bda)

**Comment by Bhaveshshah777** [comment]
When clicked on select all checkbox even disabled checkboxes are being selected, which I think should not. As once disabled, you cannot click on it and mark it as checked. The only way to mark a disabled checkbox check is via select all checkbox, which I feel is not as intended. Please verify.

![327761278-806dbca7-4971-43d4-9d4c-c5915f294bda](https://github.com/primefaces/primeng/assets/96644510/4a97940f-5080-4307-8372-a11d75c331fd)

**Comment by cetincakiroglu** [comment]
Hi,

Thanks for reporting the issue. 

Disabled options will not checked anymore.

To customize selection logic and omit the disabled rows you can use `rowSelectable` input as the example below.
**Template**
```
        <p-table [value]="products" [rowSelectable]="rowSelectable">
            <ng-template pTemplate="header">
                <tr>
                    <th><p-tableHeaderCheckbox></p-tableHeaderCheckbox></th>
                    <th>Name</th>
                </tr>
            </ng-template>
            <ng-template pTemplate="body" let-product>
                <tr>
                    <td><p-tableCheckbox [value]="product" [disabled]="product.isDeleted"></p-tableCheckbox></td>
                    <td>{{ product.name }}</td>
                </tr>
            </ng-template>
        </p-table>

```

**.ts**

```


    constructor(private productService: ProductService, private cd: ChangeDetectorRef) {
        this.rowSelectable = this.rowSelectable.bind(this);
    }


    rowSelectable(event) {
        return !event.data.isDeleted;
    }
```

**Comment by VolodymyrKornetskyi** [comment]
I faced the issue when checkbox is disabled and selected. In this case if user click selectAll checkbox disabled and selected checkboxes become to be unselected. Is there any possibility to avoid changing status of disabled checkboxes?
