### ISSUE TITLE
Component: Calendar

### ISSUE THREAD

**Issue by lerich** [primefaces/primeng#15347]
### Describe the bug

      I updated primeng for last version and found that  hideOnDateTimeSelect does not work for RangeSelection.
      In your code if range selected, the datePicker is hiding at once.
Your code:
```
       if ((this.isSingleSelection() && this.hideOnDateTimeSelect) || (this.isRangeSelection() && this.value[1])) {
            setTimeout(() => {
                event.preventDefault();
                this.hideOverlay();

                if (this.mask) {
                    this.disableModality();
                }

                this.cd.markForCheck();
            }, 150);
        }
```
        Please fix the bug. 
        Valeriy

### Environment

   "primeng": "17.12.0",

### Angular version

17.3.1

### PrimeNG version

17.12.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.11.0

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
