### ISSUE TITLE
Spinner maxlength and thousandSeparator

### ISSUE THREAD

**Issue by Helayxa** [primefaces/primeng#1534]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

Plunkr is not up-to-date with primeNG 1.0.1

**Current behavior**

I have maxlength attribute sets to 5. So, I want to input 5 numbers maximum.

The problem is with the thousandSeparator. If I input 10000, it's changed to 10,000, so there's one more character.

With my maxlength to 5, I can only input 4 numbers, because it's counting the comma. 

**Expected behavior**

If I have maxlength to 5, I want to input 5 numbers and having the thousandSeparator.

* **PrimeNG version:** 1.0.1

**Comment by cagataycivici** [comment]
maxlength is implemented by browser so in your case, maxlength should be 6, no?
