### ISSUE TITLE
Spinner with decimal numbers

### ISSUE THREAD

**Issue by Helayxa** [primefaces/primeng#1535]
I'm submitting a ... (check one with "x")

[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
Plunkr Case (Bug Reports)

Plunkr is not up-to-date with primeNG 1.0.1

Current behavior

I have a step of 1, my decimalSeparator by default ("."), and if I input 1.5, the spinner returns 1.
If I want to input decimal numbers, I have to set a decimal step.

Moreover, if I have a step of 1.25, and a value of 1, if I try to increment the value with arrow up key, it returns 2 instead of 2.25

Expected behavior

If I input decimal number in the Spinner with a step of 1, it should return decimal and increment the decimal value. If I input 1.5 and click on the up arrow or press the arrow up key, I should have 2.5.

PrimeNG version: 1.0.1

**Comment by asteria277** [comment]
I'm having the same problem here.

In fact, the solution would be to allow changing the property "precision" of spinner component. 
For the moment, the precision is calculated on the step. 
If step is "1" then precision will be 0 and decimal part will always be removed.
Allowing having a step of "1" and a precision of "2" will increase "1.55" to "2.55"...

For now I'm extending the spinner component in order to override the precision property in ngOnInit and it works.

**Comment by cagataycivici** [comment]
Unable to replicate, maybe I don't understand it, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview

**Comment by madnaelo** [comment]
Hi Dear @cagataycivici, 

PFB the plunkr test case for the issue:
http://plnkr.co/u9Ue9crSWLcvmjUiQsmB

To summarize the problem again: The precision is being calculated from step value, whereas there are scenarios when we want a whole number step value, but if user wants to enter decimal value manually, it should be allowed. But in the plunkr example, you can see, the spinner whose step is whole number, does not submit decimal values even if manually entered.

Thanking you in anticipation.
