### ISSUE TITLE
DomHandler no support with Angular SSR

### ISSUE THREAD

**Issue by kusmierczykw** [primefaces/primeng#15354]
### Describe the bug

There is a problem with support SSR by the DomHandler.
I try to open dialog on enter to concrete page in the app but the app crashes. The same problem is with Sidebar component.

<img width="1152" alt="image" src="https://github.com/primefaces/primeng/assets/18058760/f6cc0ba0-4e48-487b-9db0-b312557fc74d">

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-cjg9pe?file=src%2Fapp%2Fapp.component.html

### Angular version

SSR

### PrimeNG version

17.14.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Steps to reproduce the behavior

Add simple fragment of code to the app.component.html file:

```
<p-dialog [visible]="true" [modal]="true">
    This is a asimple test.
</p-dialog>
```

and run app with SSR mode.

The app carshes with the following error:
```
ERROR ReferenceError: document is not defined
    at _DomHandler.blockBodyScroll (/home/projects/stackblitz-starters-cjg9pe/.angular/vite-root/demo/main.server.mjs:1661:5)
    at _Dialog.enableModality (/home/projects/stackblitz-starters-cjg9pe/.angular/vite-root/demo/main.server.mjs:4139:18)
```

### Expected behavior

Support SSR by the DomHandler.

**Comment by kusmierczykw** [comment]
The workaround for this example is use:

```
  public readonly isBrowser = isPlatformBrowser(this.platformId);

  public constructor(
    private readonly navigator: NavigatorService,
    @Inject(PLATFORM_ID) private readonly platformId: object,
  ) {}
```

and 

```
@if (isBrowser) {
  <p-dialog
    [visible]="true">
    This is example content.
  </p-dialog>
}
```

But this does not change the fact that DomHandler does not support SSR.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
