### ISSUE TITLE
P-listbox onFocus() Event is not working in Angular 17

### ISSUE THREAD

**Issue by sarangrajan948** [primefaces/primeng#15356]
### Describe the bug

OnFocus() event is not working on Primeng 

### Environment

`OnFocus()` event is not working on Primeng Listbox.

```html
<p-listbox [options]="rentalLocationsName" [(ngModel)]="selectedLocation" (onFocus)="onListFocus()" (onBlur)="onBlurMouse()" [filter]="true" [style]="{ width: '15rem' }" [listStyle]="{'max-height': '220px'}">

```

```ts
onListFocus() {
console.log('list focused!');
}

```

### Angular version

17.3

### PrimeNG version

17.12

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18

**Comment by asphub** [comment]
I am also facing the same issue. Is there any alternative ways to fix this.

**Comment by vinydanylo** [comment]
@sarangrajan948 have you been able to fix this?
