### ISSUE TITLE
Table: rowspan issue when the table is frozen and scrollable

### ISSUE THREAD

**Issue by alisesan** [primefaces/primeng#15362]
### Describe the bug

Describe the bug
There is an issue with the rowspan attribute when the table is scrollable and frozen. The horizontal scroll breaks the layout for the forzen columns.

After debug it seems that the rowspan is ignored and the calculation of the left property is wrong for the second line

### Environment

![image](https://github.com/primefaces/primeng/assets/31968685/115bb2b3-d4e2-445d-8f8c-504624370fc2)

### Reproducer

https://stackblitz.com/edit/primeng-tableselection-demo-712q71?file=src%2Fapp%2Fapp.component.html

### Angular version

13.0.3

### PrimeNG version

13

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.10.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

Use the horizontal scroll. The second line of the header will ignore the rowspan and overflow the cell

### Expected behavior

The second line of the header should take the rowpan in consideration

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
