### ISSUE TITLE
Global variant set to `filled` doesn't work

### ISSUE THREAD

**Issue by Shusty-6th** [primefaces/primeng#15365]
### Describe the bug

Setting the global variant to `filled` does not change the appearance of the displayed controls in the material design theme. Global ripple setting works fine.

``` js
  constructor(private primengConfig: PrimeNGConfig) {
    this.primengConfig.ripple = true;
    this.primengConfig.inputStyle = 'filled';
  }
```

### Environment

Just see check stablitz demo. Notice it's md-light-indigo theme.

.

### Reproducer

https://stackblitz.com/edit/github-aeyd2t-olhu1d?file=src%2Fapp%2Fapp.component.ts

### Angular version

17.3.5

### PrimeNG version

17.14.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.0.9

### Expected behavior

I just want to see the filled controls as they appear on the primeNg documentation page when set to filled:
![image](https://github.com/primefaces/primeng/assets/7383088/3aa8a84e-76b8-446f-b1d6-868c6700f8e2)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
