### ISSUE TITLE
Dropdown: when using `selectedItem` template if the selected option is `0` then no template is rendered

### ISSUE THREAD

**Issue by frabonomi** [primefaces/primeng#15366]
### Describe the bug

When using the `p-dropdown` component with a custom `selectedItem` template to customize the selected label display as per documentation, the template isn't rendered if the selected option equals to `0`. 

<img src="https://github.com/primefaces/primeng/assets/677873/27bca019-3c66-46b8-819d-d43f147fee58" width="400" alt="PrimeNG Dropdown issue when the selected option is 0"/>

From a quick look at [the code](https://github.com/primefaces/primeng/blob/7815968d779b5b28446ae5e9a2dfd4d3143fe58f/src/app/components/dropdown/dropdown.ts#L155) it seems that this is happening because of the condition `selectedItemTemplate && selectedOption`. In my case the `selectedOption` is `0` and is therefore considered falsy, but it should be a treated as a possible valid value.

In a way it seems to be related to issue https://github.com/primefaces/primeng/issues/14954

### Environment

MacOS 14.2.1

### Reproducer

https://stackblitz.com/edit/github-41pgth?file=src%2Fapp%2Fapp.component.html

### Angular version

17.3.5

### PrimeNG version

17.14.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

LTS

### Steps to reproduce the behavior

1. Add a `p-dropdown` component
2. Set its options to an array containing a value that is `0`
3. Define a custom `selectedItem` template
4. Select the option with the value `0`

### Expected behavior

The custom template should be rendered even if the selected option is `0`.

**Comment by frabonomi** [comment]
Happy to open a PR for this, if needed ☝️

**Comment by frabonomi** [comment]
I think the main use case for this is when the options values are coming from an enum ([without an initializer](https://www.typescriptlang.org/docs/handbook/enums.html#numeric-enums)):

```typescript
enum Direction {
  Up, // === 0
  Down,
  Left,
  Right,
}
```

**Comment by Degcube** [comment]
Hi, this is broken again in version v19.0.9
