### ISSUE TITLE
Calendar: Property `[defaultDate]` makes the calendar unresponsive in reactive forms

### ISSUE THREAD

**Issue by ThoSap** [primefaces/primeng#15388]
### Describe the bug

When the PrimeNG Calendar is used with Angular reactive forms, setting the input binding `[defaultDate]` makes the Calendar unresponsive and the user can no longer select a date, month, or year.

### Environment

[StackBlitz - PrimeNG CalendarReactiveFormsDemo [defaultDate] broken](https://stackblitz.com/edit/ukbf3f?file=src%2Fapp%2Fdemo%2Fcalendar-reactive-forms-demo.html,src%2Fapp%2Fdemo%2Fcalendar-reactive-forms-demo.ts)

### Reproducer

https://stackblitz.com/edit/ukbf3f?file=src%2Fapp%2Fdemo%2Fcalendar-reactive-forms-demo.html,src%2Fapp%2Fdemo%2Fcalendar-reactive-forms-demo.ts

### Angular version

17.3.6 and 17.3.1 (from StackBlitz)

### PrimeNG version

17.15.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.11.1

### Browser(s)

Chrome 123.0.6312.124

### Steps to reproduce the behavior

[StackBlitz - PrimeNG CalendarReactiveFormsDemo [defaultDate] broken](https://stackblitz.com/edit/ukbf3f?file=src%2Fapp%2Fdemo%2Fcalendar-reactive-forms-demo.html,src%2Fapp%2Fdemo%2Fcalendar-reactive-forms-demo.ts)

### Expected behavior

The PrimeNG Calendar should work with Angular reactive forms when the input binding `[defaultDate]` is set.

**Comment by ThoSap** [comment]
My current workaround is the following:
```ts
  @ViewChild('myCalendar')
  private myCalendar!: Calendar;

  ngAfterViewInit(): void {
    // Workaround for the buggy <p-calendar [defaultDate]="getMaxDate()"> property binding in reactive forms
    this.myCalendar._defaultDate = this.getMaxDate();
  }
```

```html
<form [formGroup]="formGroup">
  <p-calendar #myCalendar
    [defaultDate]="getMaxDate()"
    formControlName="date"
  />
</form>
```

**Comment by ThoSap** [comment]
This is still an issue with PrimeNG v17.18.9

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
