### ISSUE TITLE
[Enhancement] Calendar - bind to a UTC date but display a local date

### ISSUE THREAD

**Issue by gatapia** [primefaces/primeng#1538]
Working with servers and users in different time zones really sucks.  What would make it easier is if the Calendar component supported UTC dates as its underlying model.  It would be the calendar's responsibility to render a nice local date/time to the user but binding that to a UTC date.

Currently I have to do that in hacky intercepting code.

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
