### ISSUE TITLE
Component: confirmdialog doesn't allow custom key

### ISSUE THREAD

**Issue by windwakerclem** [primefaces/primeng#15392]
### Describe the bug

Hello, i would like to report a bug i'm getting with confirmdialog.

I use multiple confirm dialog boxes and for that i must use the "key" value 

First box
`this.confirmationService.confirm({
        header: 'Ask for confirmation',
        message: 'Do you agree with these informations ?  :<br/>' + confirmations,
        icon: 'pi pi-exclamation-triangle',
        key: 'first',
        accept: () => {
          this.checkIfOtherError();
        },
        reject: () => {
          this.validationRequest = false;
        },
      });`

Second box :
`this.confirmationService.confirm({
      header: 'Confirmation after errors',
      message:
        'Do you still want to validate as there are errors in the form ?',
      icon: 'pi pi-exclamation-triangle',
      key: 'second',
      accept: () => {
        this.save();
      },
      reject: () => {
        this.validationRequest = false;
      },
    });`

I wanted to change both keys "first" and "second" to something like "confirmDialog" and "confirmAfterErrorDialog" but when i do that nothing works.
I even tried "confirmation1" and "confirmation2" and it doesn't work eather.

It is not possible to use a "business" key ? It works  only with "first","second","third"in my case.

### Environment

Single  angular 10 web-app with primeNG 11 

### Angular version

10.0.0

### PrimeNG version

11.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.21.3

### Browser(s)

Edge

### Expected behavior

PrimeNG confirmdialog should work with every string key.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
