### ISSUE TITLE
EXCEPTION: TypeError: jQuery(...).puidialog is not a function

### ISSUE THREAD

**Issue by shalaby** [primefaces/primeng#154]
Hi,
Thanks for your effort to bring us this very good ui lib.
I am having a problem with dialog
`EXCEPTION: TypeError: jQuery(...).puidialog is not a function`
I used the tab component without any problem.
I am using meteor.js which ships with query 1.11.2 and depends on it.
of course I am using angular2. 
can you guys help me out please.

**Comment by Mrtcndkn** [comment]
Our current version of jquery is  v2.2.1 if it is not going to be a problem for your project remove jquery 1.11.2 from your sources and just try with primeui-ng-all.js

**Comment by shalaby** [comment]
Thank you for your immediate reply, I solved it just like you said.
