### ISSUE TITLE
DynamicDialog: `closeOnEscape` and `dismissableMask` not working in combination with `closable=false`

### ISSUE THREAD

**Issue by dorthrithil** [primefaces/primeng#15401]
### Describe the bug

The `closeOnEscape` and `dismissableMask` have no effect when used in combination with `closable=false`. This kind of makes sense. However the `closable` description reads "Adds a close icon to the header to hide the dialog." So it's only about the icon. 

In my case I didn't want to have the icon but still wanted the dialog to be closable.

### Environment

Angular app.

### Reproducer

https://stackblitz.com/edit/github-nus4rk-h6lv8i?file=src%2Fapp%2Fapp.component.ts

### Angular version

17.1.3

### PrimeNG version

17.15.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

21.7.1

### Steps to reproduce the behavior

See reproducer

### Expected behavior

The icon can be hidden and the dialog can still be closed.

**Comment by cetincakiroglu** [comment]
Good catch, thanks for reporting the issue!

**Comment by ranma42** [comment]
The very same issue affects non-dynamic dialogs:

https://github.com/primefaces/primeng/blob/cb32f8d6017be584927ee6d94432b58608ba211b/packages/primeng/src/dialog/dialog.ts#L670

https://github.com/primefaces/primeng/blob/cb32f8d6017be584927ee6d94432b58608ba211b/packages/primeng/src/dialog/dialog.ts#L899

Should I open a new issue?
