### ISSUE TITLE
Component: SelectButton currently selected option isnt visible with aura theme

### ISSUE THREAD

**Issue by razaqq** [primefaces/primeng#15408]
### Describe the bug

The currently selected option is invisible when using the aura theme on a SelectButton

### Environment

windows x64

### Angular version

17.3.6

### PrimeNG version

17.15

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.1

**Comment by razaqq** [comment]
sorry was a bug on my end

**Comment by jbcbezerra** [comment]
Did you fix this @razaqq ? cause i have the same problem when using the item template.
