### ISSUE TITLE
Editor: p-Editor's value inside p-Sidebar cannot be updated at the same time as opening the sidebar

### ISSUE THREAD

**Issue by rubenteck** [primefaces/primeng#15410]
### Describe the bug

When updating the formcontrol value of a p-editor inside a p-sidebar in the same function that opens said sidebar, the value displayed by the editor doesn't change.

### Environment

I use a windows 11 laptop with IntelliJ. Angular 17.3.4, PrimeNG 17.15.0 and node v18.20.1.

### Reproducer

https://stackblitz.com/edit/github-evzyaq?file=src%2Fapp%2Fapp.component.html

### Angular version

17.3.4

### PrimeNG version

17.15.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.20.1

### Browser(s)

edge

### Steps to reproduce the behavior

in the stackblitz example:
1. click the 'open sidebar' button (this opens the sidebar and updates the formcontrol value
2. the editor still displays the original value
3. (optional) click the 'update' button in the sidebar
4. (optional) the editor now does display the updated value

### Expected behavior

the editor should show the updated value in step 2.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
