### ISSUE TITLE
ui-datatable-header not applied to DataTable

### ISSUE THREAD

**Issue by deviant32** [primefaces/primeng#1541]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Datatable header does not have ui-datatable-header class applied to it

**Expected behavior**
Table header should have ui-datatable-header

**Minimal reproduction of the problem with instructions**
Use Datatable component and inspect the thead

**What is the motivation / use case for changing the behavior?**
Should be a simple fix that will allow easier styling of the header

**Please tell us about your environment:**
Mac OSX

* **Angular version:** 2.0.X
Angular 2.2.3

* **PrimeNG version:** 2.0.X
1.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All browsers
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2

* **Node (for AoT issues):** `node --version` =   
Node 5.10.1

**Comment by dzhavat** [comment]
It is actually applied but maybe not in the way you think it should be. If you take a look at [Facets](http://www.primefaces.org/primeng/#/datatable/facets) you can see that `ui-datatable-header` is applied to the row that contains **List of Cars**

**Comment by Mrtcndkn** [comment]
As @dzhavat told there ui-datatable-header class for facets in basic datatable there is no header so there is no ui-datatable-header class.
