### ISSUE TITLE
Dropdown: selectedItem Template dropdown with no placeholder size is off

### ISSUE THREAD

**Issue by ethanolree** [primefaces/primeng#15422]
### Describe the bug

When using a Dropdown component in combination with a selectedItem template, if there is no placeholder, the height of the dropdown is off.

Here is a screenshot example. Both dropdowns have a selectedItem template, however, only the first has a placeholder
![image](https://github.com/primefaces/primeng/assets/112996028/4586b0f1-eaa3-417c-aaf9-d3e09bf4cedf)

### Environment

N/A

### Angular version

17.3.1

### PrimeNG version

17.15.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20

### Expected behavior

Dropdown height should be the same regardless of having a placeholder or not

**Comment by adri95cadiz** [comment]
I use these two rules to workaround this, in case this solves the problem for you. Anyways it would be good if it could be fixed.

`
  p-dropdown > .p-dropdown .p-dropdown-label:empty::before {
    content: '\0000a0';
  }

  p-dropdown
    > .p-dropdown
    .p-dropdown-label:has({identifier for the item in your dropdown selectedItem template})
    span[class='ng-star-inserted'] {
    display: none;
  }
  `

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
