### ISSUE TITLE
button doesn't work repple does't work 

### ISSUE THREAD

**Issue by cadentic** [primefaces/primeng#15421]
### Describe the bug

  <button pButton pRipple label="Learn More" type="button" class="mr-3 p-button-raised p-button-rounded white-space-nowrap"></button>
            <button pButton pRipple label="Live Demo" type="button" class="p-button-raised p-button-rounded white-space-nowrap p-button-outlined" icon="pi pi-upload"></button>
          
this simple button and ripple effects don't work while it was working yesterday itself 
### Environment

{
  "name": "CADENTIC®",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test",
    "serve:ssr:cadentic_dot_net_in": "node dist/cadentic_dot_net_in/server/server.mjs"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^17.3.6",
    "@angular/cdk": "^17.3.6",
    "@angular/common": "^17.3.6",
    "@angular/compiler": "^17.3.6",
    "@angular/core": "^17.3.6",
    "@angular/forms": "^17.3.6",
    "@angular/platform-browser": "^17.3.6",
    "@angular/platform-browser-dynamic": "^17.3.6",
    "@angular/platform-server": "^17.3.6",
    "@angular/router": "^17.3.6",
    "@angular/ssr": "^17.3.6",
    "@ibm/plex": "^6.4.0",
    "express": "^4.18.2",
    "primeflex": "^3.3.1",
    "primeicons": "^7.0.0",
    "primeng": "^17.13.0",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^17.3.3",
    "@angular/cli": "^17.3.3",
    "@angular/compiler-cli": "^17.3.0",
    "@types/express": "^4.17.17",
    "@types/jasmine": "~5.1.0",
    "@types/node": "^18.18.0",
    "jasmine-core": "~5.1.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "typescript": "~5.4.2",
    "@cloudflare/workers-types": "^4.20240423.0",
    "wrangler": "^3.50.2"
  }
}

### Angular version

17.3.0

### PrimeNG version

17.13

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.12.1

### Browser(s)

chrome , duckduck go 

### Steps to reproduce the behavior
using angular with scss 
_No response_

**Comment by RogueTea** [comment]
Would you happen have a stackblitz or code to recreate the environment?

**Comment by cadentic** [comment]
https://github.com/cadentic/cadentic_dot_net_in/blob/main/src/app/herosections/herosections.component.html 
here is this code

**Comment by hendyghsta** [comment]
same issue, i am click button with pRipple in Dialog no_response, and i try spam fast click to work.., but slow click no response..., and and remove pRipple normal click button event

**Comment by hashproton** [comment]
I have the same error.
Tried the stackblitz documentation examples.

[basic](https://stackblitz.com/run?file=src%2Fapp%2Fimports.ts)
[directive](https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.html)

https://primeng.org/button#basic
https://primeng.org/button#directive

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
