### ISSUE TITLE
Menubar no long supports MenuItem title. Component: MenuBar

### ISSUE THREAD

**Issue by aladdinhussein** [primefaces/primeng#15449]
### Describe the bug

In an older versions of Menubar, the menu item title will get displayed as a tooltip, but currently the menu item title is completely ignored and I don't see any other ways to display tooltips. 

### Environment

Angular App

### Angular version

17.0.8

### PrimeNG version

17.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20

### Browser(s)

Chrome

### Steps to reproduce the behavior

Assign the MenuItem title a value and then add that menuitem to a menubar. 
When you hover over the menuitem, a tooltip should be displayed.

### Expected behavior

 tooltip should be displayed

**Comment by mkoestner** [comment]
As far as I can see this in the source, title is no longer respected. You have to use tooltipOptions for displaying a tooltip.

**Comment by aladdinhussein** [comment]
> As far as I can see this in the source, title is no longer respected. You have to use tooltipOptions for displaying a tooltip.

Correct, the source code references the TooltipOptions only, but I couldn't get that to work either.

**Comment by mkoestner** [comment]
Worked for me with 17.15.0 and the following:
tooltipOptions: { tooltipLabel: 'this is my tooltip' }

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
