### ISSUE TITLE
keyboard event code is coming as empty for backspace

### ISSUE THREAD

**Issue by Subhasreerajavel** [primefaces/primeng#15442]
### Describe the bug

In Input number component, key board event code is coming as empty for backspace in android.

### Environment

Android

### Angular version

17.0.6

### PrimeNG version

17.12.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.10.0

### Browser(s)

chrome

**Comment by cetincakiroglu** [comment]
Fixed in https://github.com/primefaces/primeng/pull/15443
