### ISSUE TITLE
Docs: Stackblitz missing

### ISSUE THREAD

**Issue by r3ps4J** [primefaces/primeng#15456]
### Describe the bug

There used to be a stackblitz button available when hover a code block on the docs. This was a very helpful feature because the full code doesn't show the actual full code, services and stuff are not shown. Now this is gone, see the screenshot below.

![image](https://github.com/primefaces/primeng/assets/40723838/1da12070-ebe8-4216-aae1-4d675c010109)

There used to be a a lightning bolt icon which would open the stackblitz, similar to this (taken from the primevue docs):

![image](https://github.com/primefaces/primeng/assets/40723838/a21cec38-1592-4bff-b483-a4dd323b3903)

### Environment

I used https://primeng.org/table when I discovered that it's missing.

### Reproducer

N/A

### Angular version

N/A

### PrimeNG version

N/A

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

N/A

### Browser(s)

Firefox

### Steps to reproduce the behavior

1. Open https://primeng.org/
2. Click "Get Started"
3. Choose a random component from the sidebar under "Components"
4. Hover your mouse over a code block
5. See that the stackblitz icon is not there anymore

### Expected behavior

The stackblitz icon should be there

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Comment by r3ps4J** [comment]
Why do you guys always copy paste this response instead of looking into the issue to confirm it's still a problem?
