### ISSUE TITLE
DataView [rowsPerPageOption] not working

### ISSUE THREAD

**Issue by PolyakDonat** [primefaces/primeng#15455]
### Describe the bug

When I add the [rowsPerPageOption] to the p-dataview attribute list it is not loading the dropwdown.

### Environment

My environment is a simple local applicationthat is using the p-dataview componenet as the listing mechanism

### Reproducer

https://stackblitz.com/edit/github-lnvphz?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html

### Angular version

17.3.7

### PrimeNG version

17.16.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.15.0

### Steps to reproduce the behavior

1. Change the rowsPerPageOptions to be equal: [5]
2. A small empty dropdown will appear
3. Change it to be e.g.: [5, 15, 30]
4. There will be no rendered dropdown

### Expected behavior

A full list of the options should be rendered in a dropdown.

**Comment by PolyakDonat** [comment]
Hey there! Can you give me a rough estimate when this will be merged?

**Comment by axitpoojara** [comment]
is this working with angular 18 ?
