### ISSUE TITLE
Component: Dynamic Dialog, there is no option to pass data back on custom event like output emitter

### ISSUE THREAD

**Issue by jstechaut** [primefaces/primeng#15458]
### Describe the bug

In the context of PrimeNG's Dynamic Dialog component, there's currently no built-in functionality to pass data back to the parent component via a custom event emitter, such as an Output. This limitation inhibits seamless communication between the dynamically created dialog and its parent component. It would be beneficial to raise this issue with the PrimeNG development team to address the absence of this feature. Implementing such functionality would enhance the flexibility and usability of the Dynamic Dialog component, allowing for more efficient data exchange and interaction between components within Angular applications.

### Environment

vscode

### Angular version

17.0.0

### PrimeNG version

17.3.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.12.0

### Expected behavior

need support for the above

**Comment by jstechaut** [comment]
I want the data to be passed without close the modal as close event will only work on close the modal , I want to send data to parent component without closing the modal

**Comment by NateRadebaugh** [comment]
Interesting. Try passing the callback as part of the `data` object then, and you can call it from your modal directly.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
