### ISSUE TITLE
Table Checkbox: Not centered vertically

### ISSUE THREAD

**Issue by r3ps4J** [primefaces/primeng#15457]
### Describe the bug

When you have a checkbox in a table, it's not centered vertically. This wasn't obvious to me before either, but with the introduction of the Aura theme which features smaller checkboxes, it can now be clearly seen. The screenshot below shows a hover of the <td> element with a checkbox inside it, as you can see there is a much bigger space above the checkbox than below.

![image](https://github.com/primefaces/primeng/assets/40723838/03b6bde3-4e7a-4371-8fee-8b875c78c499)

### Environment

Angular 17 & PrimeNG 17, used with the Aura theme. Check the stackblitz below.

### Reproducer

https://stackblitz.com/edit/github-xur7cs

### Angular version

^17.3.0

### PrimeNG version

^17.15.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.12.2

### Steps to reproduce the behavior

1. Create a table with checkboxes
2. Enable the Aura theme (although it also happens on other themes, just less obvious as the checkboxes usually are the biggest element there and thus the row is the same height)
3. Use the inspector to show the spacing around the checkboxes

### Expected behavior

It should be centered, right now it's aligned towards the bottom of the row and looks kinda weird.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Comment by r3ps4J** [comment]
Why do you guys always copy paste this response instead of looking into the issue to confirm it's still a problem?
