### ISSUE TITLE
primeng 16 forces a default height of 200px on the listbox

### ISSUE THREAD

**Issue by nesanmano** [primefaces/primeng#15450]
I have an serious problem. My app has a sidebar (div)with overflow enabled. We construct a menu using the listbox component. The problem is the when we expand a listbox it has a scroll bar because the number of items are greater than the visible area. If I we remove the 200px height, all the items(listboxes) can be fully expanded. The problem is the div containing the listboxes is scrollable beyond the maximum number of listboxes that it contains. In other words, we have a huge white spaces after the last listbox component We did not have this problem in the previous versions of primeng.  I went to check the code on the repo and they are not the same. As of version 16.9 we have the scrollHeight.?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
