### ISSUE TITLE
Angular standalone components

### ISSUE THREAD

**Issue by alexciesielski** [primefaces/primeng#15465]
### Describe the bug

As discussed [here](https://github.com/orgs/primefaces/discussions/923#discussioncomment-9312910) I volunteer to start the migraton of primeng components and directives to the new standalone API.

This issue is not a bug ticket, but simply an issue for the PR to reference.

### Angular version

17.x

### PrimeNG version

17.6.0

### Expected behavior

Components and directives are standalone

**Comment by alexciesielski** [comment]
Tagging @cetincakiroglu as requested in the discussion mentioned above

**Comment by kyjus25** [comment]
@alexciesielski I would be interested to help with this effort.

Are you planning to work from top of docs to bottom, or alphabetically? Perhaps we can coordinate if you you're willing for an assist 🙏 if you'd rather solo that's cool too

**Comment by alexciesielski** [comment]
Lets wait for @cetincakiroglu first to give his initial review on the PR I opened and then we can coordinate afterwards

**Comment by cetincakiroglu** [comment]
@alexciesielski Could you please create a checklist in this issue so it would be easier to track which components are done. I suggest you send PR's after we release v18, because we're doing some internal component changes and I don't want to break your valuable contribution.

**Comment by kyjus25** [comment]
Reopen - will be resumed at the completion of new theming API in v18
