### ISSUE TITLE
Progressbar lags behind

### ISSUE THREAD

**Issue by razaqq** [primefaces/primeng#15475]
### Describe the bug

![24-05-07_11-39-20_uW84S4xi](https://github.com/primefaces/primeng/assets/5948878/1e768752-886b-42cb-8764-e56b53605f4b)

p-progressbar lags behind and then jumps all at once at the end
`<p-progressBar [value]="progress" [showValue]="true" unit="%"></p-progressBar>`

replacing it with `mat-progress-bar` without any code changes fixes it
comparison:

![24-05-07_11-54-17_Hpt0rApA](https://github.com/primefaces/primeng/assets/5948878/fe4ad010-6841-47d5-a34a-956ae93ddb77)

### Environment

windows

### Angular version

17.3.7

### PrimeNG version

17.16.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.11.1

**Comment by pkdigital** [comment]
Try adding..

` .p-progressbar-value-animate {
    transition: width 250ms 0ms cubic-bezier(0.4, 0, 0.6, 1);
  }`

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
