### ISSUE TITLE
MultiSelect: Invisible chips have enabled clear buttons

### ISSUE THREAD

**Issue by szlezakbartosz** [primefaces/primeng#15479]
### Describe the bug

When adding chips to multiselect component, the chips that do not fit the input are still generated (at least some of them). Even though they are invisible, they still have active clear buttons. Because of that it's possible to remove the chip eg. when trying to open the dropdown. It is reproducable in the docs:

https://github.com/primefaces/primeng/assets/97099991/40fb130a-4b4b-4a4e-980e-dc7eab6013ad

### Environment

-

### Angular version

17.3.1

### PrimeNG version

17.16.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.19.0

### Steps to reproduce the behavior

1. Open multiselect dropdown
2. Select multiple items
3. Inspect the input and look for invisible chip's remove button
4. Click the invisible button
5. Chip is removed and item is deselected

### Expected behavior

Invisible items should not allow interactions. If the chips need to be generated even though they are not visible, the remove buttons should be disabled.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
