### ISSUE TITLE
Calendar component: date input value is removed when a date before mindDate is entered

### ISSUE THREAD

**Issue by rolsmam** [primefaces/primeng#15487]
### Describe the bug

When I type a date in the inputfield before the minDate, the complete input is erased. Before PrimeNG 17.16.0, the input remained in the inputfield and was shown as invalid (red border). It happens here: https://github.com/primefaces/primeng/blob/15945168fad4ffbbe1dda55904ba6162a79fe0dd/src/app/components/calendar/calendar.ts#L1605

### Environment

<p-calendar
  #calendar
  dateMask
  (inputMaskValid)="handleInput($event)"
  (onSelect)="handleCalendarSelect($event)"
  [(ngModel)]="date"
  (ngModelChange)="onChange($event)"
  [keepInvalid]="true"
  [showOnFocus]="false"
  [showWeek]="true"
  [showIcon]="true"
  [dateFormat]="primeNGCalendarFormat"
  placeholder="dd-mm-jj"
  [minDate]="minDate ?? defaultMinDate"
></p-calendar>

### Angular version

17.3.6

### PrimeNG version

17.16.0

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.0

### Steps to reproduce the behavior

1. Set minDate
2. Set keepinvalid true
3. Input date before mindate
4. Actual result: date is removed, field not invalid

### Expected behavior

Expected: as before, date remains in field and field is invalid (red border)

**Comment by RogueTea** [comment]
Ah, I believe I actually introduced this bug. Working on it now.

**Comment by gvlekke** [comment]
Thanks for your quick response and if you need any help @RogueTea don't hesitate to ask :)
