### ISSUE TITLE
TreeTable: Selection and editable cells do not allow spaces within the input fields

### ISSUE THREAD

**Issue by kartheininger** [primefaces/primeng#15497]
### Describe the bug

Using a TreeTable with selection in combination with editable cells does not allow "spaces" within the inputs.

High likely because the selection is somehow done via space.

### Environment

Stackblitz, primeng issue template
https://github-xofatw.stackblitz.io
or editable:
https://stackblitz.com/edit/github-xofatw

### Reproducer

https://stackblitz.com/edit/github-xofatw?file=src%2Fapp%2Fapp.component.html

### Angular version

17.3.7

### PrimeNG version

17.16.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Steps to reproduce the behavior

https://github-xofatw.stackblitz.io

Try to edit the file size and try to enter a space

### Expected behavior

Spaces should be possible ;)

**Comment by kartheininger** [comment]
> Removing `ttSelectableRow` will solve your problem.

But then I cannot select the rows anymore by clicking on them? The problem is the combination of selection and inline-editing.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
