### ISSUE TITLE
Component: Editor Mismatched Format for reactive forms two way binding

### ISSUE THREAD

**Issue by sh-ct** [primefaces/primeng#15494]
### Describe the bug

When using reactive forms with the editor component, manually entering text into the editor in the browser sets the form control's value to a string of HTML, i.e `'<p>Some text content</p>'`. However if this same value was set on the form control directly the editor will have all content cleared causing a mismatch between the visible text content and the form control value.

To programmatically set the value it needs to be set as an object with an html key i.e. `{ html: '<p>Some text content</p>' }`.

I believe this is because the value is directly passed to `this.quill.clipboard.convert(this.value)` which requires the object format, so either this should be updated to handle setting the form control to strings or the value output should be in the correct format.

### Environment

Windows 10

### Reproducer

https://stackblitz.com/edit/github-xr1xck?file=src%2Fapp%2Fapp.component.ts

### Angular version

17.3.7

### PrimeNG version

17.16.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.9.0

### Steps to reproduce the behavior

1. Setup a component using the Editor Component and link it with a form control
2. Enter text into the editor using mouse and keyboard, the form control value will be set to a string i.e.  `'<p>String</p>'`
3. Programmatically Set the value of the form control to a string of HTML, i.e `'<p>String of HTML</p>'`, this will not work
4. Programmatically set the value to an object with a html key i.e. `{ html: '<p>String of HTML</p> }`, this will work

### Expected behavior

Setting the form control using a string of HTML should set this as the editor text content, or the component should output the entered HTML in the correct format (`{ html: 'html' }`)

**Comment by robm-sentinelda** [comment]
This seems to be an issue when using Quill 2.0+ (which I think changed the clipboard behavior that @sh-ct mentioned). 
Note: This is also an issue for Template-Driven forms using [(ngModel)] binding, where initial bound value doesn't appear.

**_POTENTIAL WORKAROUND:  Downgrade to Quill v1.3.7._**, which is what we did and documented behavior is restored.

(@sh-ct thanks for the good write-up and StackBlitz example, which really helped me!)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
