### ISSUE TITLE
TabMenu: Tooltip does not work through title

### ISSUE THREAD

**Issue by mhazak** [primefaces/primeng#15500]
### Describe the bug

The tabmenu items don't show the tooltip received from the `title` attribute.

### Environment

"@angular/common": "^16.2.8"
"primeng": "^16.9.1",

### Reproducer

https://stackblitz.com/edit/epjkez?file=src%2Fapp%2Fdemo%2Ftab-menu-active-demo.ts

### Angular version

16.2.8

### PrimeNG version

16.9.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.17.1

### Expected behavior

If some of the MenuItem contains a `title` attribute, it should automatically render the tooltip.

**Comment by Sinan997** [comment]
update your items array like this

```ts
this.items = [
  { label: 'Homee', icon: 'pi pi-fw pi-home', tooltipOptions: { tooltipLabel:'Test123' }},
  { label: 'Calendar', icon: 'pi pi-fw pi-calendar', tooltipOptions: { tooltipLabel:'Calendar' }},
  { label: 'Edit', icon: 'pi pi-fw pi-pencil', tooltipOptions: { tooltipLabel: 'Edit' }},
  {
    label: 'Documentation',
    icon: 'pi pi-fw pi-file',
    tooltipOptions: { tooltipLabel: 'Documentation' }
  },
  { label: 'Settings', icon: 'pi pi-fw pi-cog', tooltipOptions: { tooltipLabel: 'Settingsl' }},
];
```

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
