### ISSUE TITLE
TabMenu: Tooltip does not work using tooltip field

### ISSUE THREAD

**Issue by godfryd** [primefaces/primeng#15517]
### Describe the bug

Setting tooltip field is not working, no tooltip is displayed.
The same applies to title field but there is a bug for that: https://github.com/primefaces/primeng/issues/15500

### Environment

```
    "@angular/animations": "17.0.8",
    "@angular/cdk": "17.0.4",
    "@angular/common": "17.0.8",
    "@angular/compiler": "17.0.8",
    "@angular/core": "17.0.8",
    "@angular/fire": "17.0.0",
    "@angular/forms": "17.0.8",
    "@angular/language-service": "17.0.8",
    "@angular/localize": "17.0.8",
    "@angular/platform-browser": "17.0.8",
    "@angular/platform-browser-dynamic": "17.0.8",
    "@angular/router": "17.0.8",
    "@angular/service-worker": "17.0.8",
    "primeflex": "3.3.1",
    "primeicons": "7.0.0",
    "primeng": "17.15.0",
```

### Angular version

17.0.8

### PrimeNG version

17.15.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.10.0

### Steps to reproduce the behavior

Pick any example of tabmenu from the docs and add tooltip field to tab items list.

### Expected behavior

Tooltip is displayed.

**Comment by Sinan997** [comment]
Hi, could you use `tooltipOptions` object and set `tooltipOptionLabel`?

example usage:
update your items array like this

```ts
this.items = [
  { label: 'Homee', icon: 'pi pi-fw pi-home', tooltipOptions: { tooltipLabel:'Test123' }},
  { label: 'Calendar', icon: 'pi pi-fw pi-calendar', tooltipOptions: { tooltipLabel:'Calendar' }},
  { label: 'Edit', icon: 'pi pi-fw pi-pencil', tooltipOptions: { tooltipLabel: 'Edit' }},
  {
    label: 'Documentation',
    icon: 'pi pi-fw pi-file',
    tooltipOptions: { tooltipLabel: 'Documentation' }
  },
  { label: 'Settings', icon: 'pi pi-fw pi-cog', tooltipOptions: { tooltipLabel: 'Settingsl' }},
];
```

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
