### ISSUE TITLE
MultiSelect Component: deselecting a checkbox item after selectall is not properly binded and previous selected items get reset on using filters.

### ISSUE THREAD

**Issue by joshi-renu** [primefaces/primeng#15516]
### Describe the bug

This is in reference to the issue [https://github.com/primefaces/primeng/issues/15294](url).
The selectAll functionality in Virtual Scroll with filter is working fine but deselection has not taken into account while resolving that issue. After filtering, selecting selectAll and then deselecting any item doesn't deselect the selectAll checkbox.
There is a concept of header checkbox template introduced for partial and all selections, but there is no proper information provided in the documentation, even both of their functions look the same. Please resolve this bug and update the documentation with proper examples.

Another bug, if we previously select any item and then search with some keywordand then selectAll, previously selected item gets removed from the selected list.

### Environment

Angular CLI: 17.3.3
Angular: 17.3.2
Node: 20.9.0
zone.js: 0.14.4
Typescript: 5.2.2
Package Manager: npm 10.1.0
OS: win32 x64

### Angular version

17.3.2

### PrimeNG version

17.11.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.9.0

### Steps to reproduce the behavior

Bug1 :
1. Implement VirtualScroll in the Multiselect component and add the onSelectAllChange() logic as provided in the PrimeNG demo example. This can also be reproduced directly on the demo example given on the PrimeNG website.
2. Navigate to the Multiselect dropdown.
3. Click on the search filter and enter a keyword.
4. Click on the Select All header checkbox.
5. Now, deselect any of the selected item, selectAll should also be deselcted but it doesn't happen so.

Bug2:
1. Implement VirtualScroll in the Multiselect component and add the onSelectAllChange() logic as provided in the PrimeNG demo example. This can also be reproduced directly on the demo example given on the PrimeNG website.
2. Navigate to the Multiselect dropdown.
3. Select any item from the dropdown.
4. Now go to search filter and search for any item other than the previous selected item.
5. Now click on Select All, you will see the previously selected doesn't appear in the selected list.

### Expected behavior

Bug 1: 
Expected behavior is to select and deselect, both of which should be properly bound with the selectAll checkbox
Bug 2:
Expected behavior is that previously selected items without any filters should not get reset/removed, if we search for some items with filters and click on selectAll.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
