### ISSUE TITLE
2 Function Glitches Found - Step By Step Guide To Replicate

### ISSUE THREAD

**Issue by listeasy** [primefaces/primeng#1551]
Glitch Found,

1.) Header Column and Grid Column are not aligned
2.) Column Resize and Column Reorder Do not function

How to duplicate:

**Add 10 Header Columns Values**
First Name, Last Name, Address 1, Address 2, City , State, Postal Code, Country , Phone 1, Phone 2

**Add 10 Body Column Field Values**
Prime, Faces, 123 somewhere st, suite 100, Los Angles , California, 90120, United States, 3101112222, 3101113333

**Enable checkbox variable** " Multiple selection can also be handled using check boxes by enabling the selectionMode property of column as "multiple".

**Enable Vertical scroll bar variable Only** "Data scrolling with fixed header is available horizontally, vertically or both. ScrollHeight and ScrollWidth values can either be fixed pixels or percentages."

**Enable Column Resize** "Columns can be resized using drag drop by setting the resizableColumns to true. There are two resize modes; "fit" and "expand". Fit is the default one and the overall table width does not change when a column is resized. In "expand" mode, table width also changes along with the column width. onColumnResize is a callback that passes the resized column header as a parameter."

**Enable Column Reorder**  "Columns can be reordered using drag drop by setting the reorderableColumns to true. onColReorder is a callback that is invoked when a column is reordered."

**Load the project,**  

**Issue 1.)** Grid header and grid body column values are not align.
**Issue 2.)** Column Resize and Column Reorder do not function.

Conclusion:
1.) If we Remove the vertical scroll bar variable.
Grid Header Values and Grid Body Column values are align and Column Resize and Column Reorder now work

**Comment by huineng** [comment]
I have exactly the same issue , reorder doesn't work in combination with scrollable.

Now also when using scrollable true and scrollWidth (either 100% of a fixed px), then when using resize  "expand" and you resize, then the horizontal scrolling gets lost. 

so the resize event is recalculating the total width of the table but overwriting the width set by the scrollWidth

thanks

**Comment by bmstambaugh** [comment]
I am having the same issues as well in Angular 4x and PrimNG 4.0.0-rc.3. This was going to be my next submitted issue until I found this.

**Comment by cagataycivici** [comment]
Tracked at;

#2890
