### ISSUE TITLE
PrimeNg Table Cannot assign to read only property '0' of object '[object Array] 

### ISSUE THREAD

**Issue by ekrem-kocak** [primefaces/primeng#15521]
### Describe the bug

In Angular 17.3 version, I'm using PrimeNG 17.15 version table. I'm constantly encountering the same error during sorting. To check if I'm making a mistake, I tried to implement it exactly as described in the [documentation](https://primeng.org/table#single-column-sort), but I still get the same error.

> 
> ERROR TypeError: Cannot assign to read only property '0' of object '[object Array]'
>     at Array.sort (<anonymous>)
>     at Table.sortSingle (primeng-table.mjs:1163:32)
>     at Table.sort (primeng-table.mjs:1101:18)
>     at SortableColumn.onClick (primeng-table.mjs:3601:21)
>     at SortableColumn_click_HostBindingHandler (primeng-table.mjs:3627:92)
>     at executeListenerWithErrorHandling (core.mjs:25630:16)
>     at wrapListenerIn_markDirtyAndPreventDefault (core.mjs:25664:22)
>     at HTMLTableCellElement.<anonymous> (platform-browser.mjs:679:17)
>     at _ZoneDelegate.invokeTask (zone.js:403:31)
>     at core.mjs:14556:55

### Environment

-

### Angular version

17.3.0

### PrimeNG version

17.15.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.12.2

### Browser(s)

Chrome

**Comment by imaksp** [comment]
Hi, you can check this live demo code from doc, it is working here:
https://stackblitz.com/run?file=src%2Fapp%2Ftable-single-column-sort-demo.html

**Comment by ekrem-kocak** [comment]
```

<p-table [value]="basvurular" [columns]="cols" [tableStyle]="{ 'min-width': '60rem' }">
      <ng-template pTemplate="header" let-columns>
        <tr>
          <th *ngFor="let col of columns" [pSortableColumn]="col.field">
            {{ col.header }} <p-sortIcon [field]="col.field" />
          </th>
        </tr>
      </ng-template>
      <ng-template pTemplate="body" let-rowData let-columns="columns">
        <tr>
          <td *ngFor="let col of columns">{{ rowData[col.field] }}</td>
        </tr>
      </ng-template>
</p-table>
```

**Comment by ekrem-kocak** [comment]
I realized that the issue stemmed from the state management library (I'm using NGXS). As a solution, I utilized the @Input value transform introduced with Angular 16.
![image](https://github.com/primefaces/primeng/assets/64695572/18884b3b-bdc0-40ee-abbe-22d88c408b2f)
![image](https://github.com/primefaces/primeng/assets/64695572/eb3509d6-64c8-47dd-9677-234068764239)
![image](https://github.com/primefaces/primeng/assets/64695572/36a900d6-e382-41b1-83c5-8cdaee3fc502)

 
 
 

You can opt for such a solution, or you can use the cloneDeep function from the lodash library. For versions of Angular prior to 16, my suggestion would be to use the following approach instead of @Select.
 
![image](https://github.com/primefaces/primeng/assets/64695572/34eb29fc-4dde-4480-89fc-20d70fcc9cfc)

**Comment by ekrem-kocak** [comment]
I realized that the issue stemmed from the state management library (I'm using NGXS). As a solution, I utilized the @Input value transform introduced with Angular 16.
![image](https://github.com/primefaces/primeng/assets/64695572/18884b3b-bdc0-40ee-abbe-22d88c408b2f)
![image](https://github.com/primefaces/primeng/assets/64695572/eb3509d6-64c8-47dd-9677-234068764239)
![image](https://github.com/primefaces/primeng/assets/64695572/36a900d6-e382-41b1-83c5-8cdaee3fc502)

 
 
 

You can opt for such a solution, or you can use the cloneDeep function from the lodash library. For versions of Angular prior to 16, my suggestion would be to use the following approach instead of @Select.
 
![image](https://github.com/primefaces/primeng/assets/64695572/34eb29fc-4dde-4480-89fc-20d70fcc9cfc)

**Comment by ekrem-kocak** [comment]
I realized that the issue stemmed from the state management library (I'm using NGXS). As a solution, I utilized the `@Input()` value transform introduced with Angular 16.

![image](https://github.com/primefaces/primeng/assets/64695572/18884b3b-bdc0-40ee-abbe-22d88c408b2f)
![image](https://github.com/primefaces/primeng/assets/64695572/eb3509d6-64c8-47dd-9677-234068764239)
![image](https://github.com/primefaces/primeng/assets/64695572/36a900d6-e382-41b1-83c5-8cdaee3fc502)

 
 
 

You can opt for such a solution, or you can use the cloneDeep function from the lodash library. For versions of Angular prior to 16, my suggestion would be to use the following approach instead of `@Select`
 
![image](https://github.com/primefaces/primeng/assets/64695572/34eb29fc-4dde-4480-89fc-20d70fcc9cfc)
