### ISSUE TITLE
TieredMenu:Tooltip property does not work on MenuItem

### ISSUE THREAD

**Issue by SaulFein** [primefaces/primeng#15536]
### Describe the bug

When using a the TieredMenu and adding a tooltip to the menu items the tooltip does not show. If you use the tooltipOptions.tooltipLabel it works. 

### Environment

Production. Reproducable in stack blitz from the doc examples on PrimeNg documentation.

### Reproducer

https://stackblitz.com/edit/gy48zd?file=src%2Fapp%2Ftiered-menu-basic-demo.ts

### Angular version

17.3.7

### PrimeNG version

17.6.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.13.1

### Steps to reproduce the behavior

1. Add a tooltip property to a menu item.
2. Hover over menu item

### Expected behavior

I would expect to see the tool tip on hover.

I believe this should be an input in the code:
<img width="869" alt="Screenshot 2024-05-10 at 3 22 34 PM" src="https://github.com/primefaces/primeng/assets/12875543/4085ddfc-fffb-4506-83a1-525e2aa5d33d">

**Comment by Sinan997** [comment]
You can also provide like this:

```ts
tooltipOptions: { tooltipLabel: 'SaulFein' }
```
