### ISSUE TITLE
Skeleton [size] property is no longer a string accepting rem values but instead expects shapes

### ISSUE THREAD

**Issue by LightBulbIdea** [primefaces/primeng#15535]
### Describe the bug

Skeleton [size] property is no longer a string accepting REM values. It now requires the developer to pass either 'circle', 'square' or undefined. This change appears to be a mistake since there's already a shape property in said component. Because of this new change we can no longer specify the size of the skeleton.

This changed was introduced on v17.16.1

v17.16.0 file: 
https://github.com/primefaces/primeng/blob/9df3367a51ee2a1e01c17c1c29b4e069b0594dd2/src/app/components/skeleton/skeleton.ts#L47

v.17.16.1 file: **(This looks wrong)**
https://github.com/primefaces/primeng/blob/7fdceab2dbb7831484f1567d47214a54d1c49de1/src/app/components/skeleton/skeleton.ts#L47

### Environment

Angular 17.3.4

PrimeNG 17.16.1

### Angular version

17.3.4

### PrimeNG version

17.16.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20

### Steps to reproduce the behavior

Code change to the skeleton's size property that seems unintentional.

### Expected behavior

To be able to pass a size value rather than to be forced to pass in a shape since we already have a dedicated shape property.

**Comment by imaksp** [comment]
Hi, yes it looks like a mistake, introduced with this recent commit by @cetincakiroglu :
https://github.com/primefaces/primeng/commit/a521b102f980a1f57d329b293079e6f53ebc5337

**Comment by cetincakiroglu** [comment]
Hi,

Thanks for letting us know, we'll address it with the upcoming release.

**Comment by cetincakiroglu** [comment]
Fixed in https://github.com/primefaces/primeng/pull/15540
