### ISSUE TITLE
TreeSelect: ng-touched not working & add onFocus, onBlur events

### ISSUE THREAD

**Issue by Pablo200206** [primefaces/primeng#15537]
### Describe the bug

When doing focus out on tree select, ng-untouched never updates to ng-touched

### Environment

Angular 16, the bug replicates with primeng 16 and 17, the same thing happens on the treeselect documentation https://primeng.org/treeselect

### Angular version

16

### PrimeNG version

17.16.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20

### Browser(s)

Edge

### Steps to reproduce the behavior

1. Focus and focus out on tree select
2. It stills with the ng-untouched class

### Expected behavior

On focus out tree select should be touched

**Comment by cetincakiroglu** [comment]
fixed in https://github.com/primefaces/primeng/pull/15538
