### ISSUE TITLE
Message: New severity not reflected in styles

### ISSUE THREAD

**Issue by EinfachHans** [primefaces/primeng#15534]
### Describe the bug

In https://github.com/primefaces/primeng/pull/15471 new `severity` options were added. For the message component they were named differently before and the changes were not applied to the styles. The `error` and `warn` options are removed, but still used for styles [in all the theme files](https://github.com/primefaces/primeng/blob/9d82a055f1a9708a5b0dc98f635b65259fcc4ac5/src/assets/components/themes/lara-dark-purple/theme.css#L5760-L5774). So the new `danger` and `warning` have no styling.

### Environment

// 

### Angular version

17.3.8

### PrimeNG version

17.16.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.12.2

**Comment by Shusty-6th** [comment]
After updating primeNg to the new version, we have the same problem. I can see that for message severity `error` is no longer supported and instead takes `danger`, however the component displays badly because the theme css message still uses `error` and not `danger`.

**Comment by vinishiru** [comment]
Temporary solution for typescript that corrects the style, but displays an exclamation icon instead of times icon.
```javascript
[severity]="$any('error')"
```

**Comment by thetric** [comment]
This is really annoying and concerns every component with a `severity` input. This is a really annoying breaking change in a minor release :(

**Comment by meriturva** [comment]
Related to https://github.com/primefaces/primeng-sass-theme/issues/134

**Comment by cetincakiroglu** [comment]
Hi all,

Severity options for the message should be as follows:

`severity: 'success' | 'info' | 'warn' | 'error' | 'secondary' | 'contrast' | undefined;`

Possibly, this issue stems from a problem occurring when merging branches. We'll address the issue in 17.18.3 this week.
