### ISSUE TITLE
TreeSelect: Panel does not hide on selected item

### ISSUE THREAD

**Issue by Pablo200206** [primefaces/primeng#15539]
### Describe the bug

TreeSelect panel does not hide when item is selected

### Environment

Angular 17

### Angular version

17

### PrimeNG version

17.16.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.0.0

### Browser(s)

Edge

### Steps to reproduce the behavior

https://primeng.org/treeselect

Deploy tree select items.
Select one

### Expected behavior

Panel hides when option is selected

**Comment by cetincakiroglu** [comment]
Fixed in https://github.com/primefaces/primeng/commit/8351c3ff431f6e4e8f803057dff5fc56e2bfa2f4
