### ISSUE TITLE
Autofill is breaking floating-label positioningComponent: Title

### ISSUE THREAD

**Issue by BlackstarSoon** [primefaces/primeng#15544]
### Describe the bug

When (chrome) autofill happens, the label is not floating above the input field, unless any interaction on the page has taken place.
![image](https://github.com/primefaces/primeng/assets/20101800/76925d5f-fbc1-459e-abb6-5a80d34dada8)

### Environment

Windows 11, Chrome and Edge browser

### Angular version

16.2.1

### PrimeNG version

16.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.0

### Steps to reproduce the behavior

1. Take any form input field with a floating label styles as proposed in https://www.primefaces.org/primeng-v16-lts/inputtext
2. Have autofill data in your browser
3. Load the page

### Expected behavior

Label should be immediately above the input field after page load.

As issue happened in previous version, this currently can be fixed when added the below selector to the label styling
`.p-float-label textarea:-webkit-autofill ~ label,
.p-float-label input:-webkit-autofill ~ label`

**Comment by BlackstarSoon** [comment]
The fixes that I used is based on this reported ticket
https://github.com/primefaces/primeng/issues/5472

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
