### ISSUE TITLE
Elements inside the template of p-tree can't be clicked

### ISSUE THREAD

**Issue by Cedware** [primefaces/primeng#1554]
Elements inside the template of a p-tree can't be clicked so buttons click action aren't executed and the cursor can't be moved into input boxes:
```
  <p-tree [value]="categories">
    <template let-node pTemplate type="category">
      <input type="text"><!--can't edit-->
      <button pButton label="ok" click="add()"></button><!-- can't click' -->
    </template>
  </p-tree>
```

**Comment by Cedware** [comment]
Alright, it figured out, that it not a problem with the template it self.
When the value property is bind to a get property, the tree view does completely ignores click events

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
