### ISSUE TITLE
tabMenu breaks table virtual scroll calculations

### ISSUE THREAD

**Issue by puschie286** [primefaces/primeng#15556]
### Describe the bug

When using tabMenu and a table with virtual scrolling, the scroll height (transform: translate3d(0px, 0px, 0px) on p-datatable-tbody p-scroller-content) is calculated wrong after update - causing the scrollbar to jump back up and make it impossible to scroll down.

tried to create an example in stackblitz but its far less problematic there then in our environment - so its might be related to some css constelation. 
here gif with menu:
![ScrollWithMenu](https://github.com/primefaces/primeng/assets/2429036/a14f41f6-a285-42f8-a097-0678faece83a)
without menu: 
![ScrollWithoutMenu](https://github.com/primefaces/primeng/assets/2429036/5da51827-709e-443f-beb7-8c7da4e30ab3)

our current workaround is to delay the tabMenu draw by @if statement and setTimeout( ..., 1 ) but we coud not figure out what tabMenu does to interfer the scroll calculation. 

When looking at the html you see that the tbody (p-datatable-tbody p-scroller-content) get updated with the correct transform style first right before its reset to 0, 0, 0. (gif of triggering scroll update 2 times)
![ScrollHtmlReset](https://github.com/primefaces/primeng/assets/2429036/1d9eb401-16f5-4bc5-b3ac-5986202f01d7)

### Environment

<div class="h-full flex flex-col">
<div class="flex-initial">
<p-tabMenu [model]="navigations" [scrollable]="true" styleClass="my-5"/>
</div>
<div class="flex-auto overflow-auto">
<leaderboard></leaderboard> (insert by router-outlet)
</div>
</div>

### Reproducer

https://stackblitz.com/edit/wgws6t-8kyucc

### Angular version

17.3.7

### PrimeNG version

17.16.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.12.2

### Browser(s)

Chrome

**Comment by adrian-czarnomski-engel** [comment]
We have pretty much the same issue, we have p-tabMenu and p-listbox with virtual scroll inside router-outlet. It doesn't work for any component with virtual scroll. All chromium based browsers and also firefox doesn't work, but we noticed that Safari has no problem with it.

![Záznam obrazovky 2024-05-24 v 9 08 12](https://github.com/primefaces/primeng/assets/151854094/768c5bc2-a0db-48b8-a487-f063b80aaada)

Our configuration is:
Angular 17.3.0
PrimeNG: 17.16 (tested also 17.17)
Node 22.2.0
Browsers Chrome/Edge and Firefox (chromium based)

**Comment by adrian-czarnomski-engel** [comment]
@puschie286 Since the PrimeNG team haven't answered yet, I noticed, that if the wrap component of p-tabMenu has OnPush Strategy, it works as expected. Scrolling in virtual scroll causes refreshing p-tabMenu multiple times which leads to calling **updateInkBar()** method inside of p-tabMenu, which spams DomHandler. You can override the updateInkBar method to do nothing, or activate OnPush strategy. It helped us.

**Comment by puschie286** [comment]
@adrian-czarnomski-engel thanks for the tip but it doesnt seems to work for us - the tabMenu and the virtual scrolling component are in completely different angular components, both are OnPush so there seems to be some conflict in the intern calculations

**Comment by NynaPykulska** [comment]
I had this issue with virtual scroll in a table, until I found this thread [4029](https://github.com/primefaces/primeng/issues/4029).
The class that they applied the style to is not in the table anymore, so instead I added it like this 
`.p-datatable {
    .p-datatable-tbody, .p-datatable-scroller-spacer {
        overflow-anchor: none;
    }
}`
I don't know what does the structure of the tab menu look like, so don't know if this will help, but maybe it can be a clue for you too.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
