### ISSUE TITLE
Custom sort in table not working.

### ISSUE THREAD

**Issue by mahesh-mathew** [primefaces/primeng#15550]
### Describe the bug

Custom sort is not working expected. (sortFunction)="customSort($event)" is not getting triggered.Using the vesrion "primeng": "^17.16.0".

<p-table
#dt
[columns]="cols"
[value]="values"
(sortFunction)="customSort($event)" [customSort]="true"
[tableStyle]="{ 'min-width': '50rem' }"
[paginator]="true"
[rows]="10"
[scrollable]="true"
currentPageReportTemplate="Showing {first} to {last} of {totalRecords} entries"
(onPage)="onPaginate($event)"
[showCurrentPageReport]="true"
[totalRecords]="totalRecords"
[lazy]="true"
[rowsPerPageOptions]="[5, 10, 20]"
[selectionMode]="'multiple'"
[(selection)]="selectedRows"
>

In ts
import { ConfirmationService, SortEvent } from 'primeng/api';

customSort(event : SortEvent){
    console.log(event);
    
  }
  
  tried as per the latest documentation.But customSort Method is not triggered while applying the sort.

### Environment

local environment

### Angular version

17.00

### PrimeNG version

17.16.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.0

**Comment by Sinan997** [comment]
Hi, https://primeng.org/table#removable-sort it works.

could you share stackblitz

**Comment by FedericoStroppiana** [comment]
sortFunction is not triggered when lazy is true

**Comment by AIO1** [comment]
> sortFunction is not triggered when lazy is true

@Sinan997 I can confirm this is happening. Custom sort is not triggered if lazy load is being used.

**Comment by MikeMatusz** [comment]
Why the sudden reversal on this? There have been numerous issues and discussions in the past, and if you have `[lazy]="true"`, then sorting and filtering should be done on the server or in the `onLazyLoad` function.  This makes sense, as the client doesn't have all the data. If the sort changes, you need to consider records not loaded into `data` yet.

This was a breaking change, and doesn't make sense to me.  As we have a shared wrapper where `lazy` is conditional, this caused issues our code and we have to short-circuit out of our sort function now, when previously it was never called.  Why would we want to sort client-side if we don't have all the records that need to be sorted?
