### ISSUE TITLE
Table filter:  templating filter as Calendar with selectionMode range throws error

### ISSUE THREAD

**Issue by dterol** [primefaces/primeng#15576]
### Describe the bug

 Templating filter as Calendar with selectionMode range throws error when **increment/decrement** time.

**Here an example:**

<p-columnFilter
                        field="timestamp"
                        type="date"
                        display="menu"
                        [showMatchModes]="false"
                        [showOperator]="false"
                        [showAddButton]="false"
                        [showClearButton]="false"
                    >
                        <ng-template pTemplate="filter" let-value>
                            <p-calendar
                                inputId="timestampRange"
                                [ngModel]="value"
                                [readonlyInput]="true"
                                [showTime]="true"
                                [showIcon]="true"
                                hourFormat="24"
                                selectionMode="range"
                                [showSeconds]="true"
                                dateFormat="yy-mm-dd"
                                [required]="true"
                             ></p-calendar>
                        </ng-template>
 </p-columnFilter>

**Here the error from console:**

main.44d5f1af5cc45044.js:1 TypeError: n.toDateString is not a function
    at t.toggleAMPMIfNotMinDate (main.44d5f1af5cc45044.js:1:647613)
    at t.incrementHour (main.44d5f1af5cc45044.js:1:647394)
    at t.repeat (main.44d5f1af5cc45044.js:1:648205)
    at t.onTimePickerElementMouseDown (main.44d5f1af5cc45044.js:1:647783)
    at main.44d5f1af5cc45044.js:1:614252
    at yT (main.44d5f1af5cc45044.js:1:105707)
    at r (main.44d5f1af5cc45044.js:1:105880)
    at HTMLButtonElement.<anonymous> (main.44d5f1af5cc45044.js:1:177001)
    at l.invokeTask (polyfills.a85ee331dfc35634.js:1:19273)
    at Object.onInvokeTask (main.44d5f1af5cc45044.js:1:92137)

### Environment

N/A

### Angular version

17.3.7

### PrimeNG version

17.16.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.10.0

### Browser(s)

All

### Steps to reproduce the behavior

1. Template filter as calendar with selection mode range and show time.
2. Increment or decrement time.

### Expected behavior

No error expected.

**Comment by mahmoudmohsendev** [comment]
Please any updates on this issue ??
