### ISSUE TITLE
Multiple root nodes in tree

### ISSUE THREAD

**Issue by Lucasvo1** [primefaces/primeng#1557]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[* ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
Would it be possible to have multiple root nodes inside a horizontal tree?

**Comment by cagataycivici** [comment]
At this point no but if there is more demand, we'll reopen to see if we can implement it.

**Comment by robichaud** [comment]
This would be a great feature to have.

**Comment by ps91** [comment]
This could be a nice feature. Please reopen this issue.

**Comment by Ernio3** [comment]
Sign me up! Please reopen.
