### ISSUE TITLE
Button | Remove wrapper span elements from icon templates

### ISSUE THREAD

**Issue by cetincakiroglu** [primefaces/primeng#15582]
Span elements wrapping around the icon templates may cause styling issues in other icon libraries. To prevent any additional styles coming from the PrimeNG, we'll remove wrapper span elements to allow users to customize their choice of icon. Additionally, a new `class` template parameter will be provided.
 
Example:
```
            <p-button label="Test Material Symbol icon">
                <ng-template pTemplate="icon" let-class="class">
                    <span class="material-symbols-outlined" [ngClass]="class">info</span>
                </ng-template>
            </p-button>
```

**Comment by rokamon1997** [comment]
Is it possible this broke the "pi-spin" icon functionality? With version 17.17.0 simple button with pi-spin class doesn't seem to work anymore.

This does not work.
`<p-button icon="pi pi-spinner pi-spin"></p-button>`

Temporary fix for me is to use classic button with pButton directive instead.

**Comment by OmkarJ13** [comment]
This should've been marked as a breaking change in the changelogs. 
The users of the library will not know that you have to use a new template parameter to make icon classes work
