### ISSUE TITLE
Split button: tooltip for the items

### ISSUE THREAD

**Issue by koesper** [primefaces/primeng#15581]
### Describe the bug

There is no tooltip option for the items within the dropdown.
If you set a tooltip like this:
`<p-splitButton title="tooltip">`
It is visible whenever you hover over the button, the dropdown arrow or the dropdown menu.

setting it in the model doesnt work:
`<p-splitButton [model]="items">
 this.items = [{
        label: "Item in the dropdown",
        title: "does not work",
        tooltip: "also does not work",
}]`

There also is no template for the items in the dropdown

### Environment

stackblitz, forked from the Splitbutton Basic example, tested on chrome dev 126.0.6468.2

### Reproducer

https://stackblitz.com/edit/wcyfxh

### Angular version

17.3.7

### PrimeNG version

17.16.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

n/a

**Comment by Sinan997** [comment]
#15598 will fix the tooltip problem on dropdown buttons.

For main button #15601

**Comment by cetincakiroglu** [comment]
Fixed in https://github.com/primefaces/primeng/pull/15598
