### ISSUE TITLE
@bon-vivant

### ISSUE THREAD

**Issue by fra-venti** [primefaces/primeng#15584]
@bon-vivant 
Can you reopen this issue? This is still an issue in 17.6

[stackblitz](https://stackblitz.com/edit/4rtnwa?file=src%2Fapp%2Fdemo%2Ftree-select-basic-demo.html)

_Originally posted by @nur-kjaeger in https://github.com/primefaces/primeng/issues/11815#issuecomment-1940774909_

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
