### ISSUE TITLE
pTooltip: tooltip creates overflow of body

### ISSUE THREAD

**Issue by Emiliorth** [primefaces/primeng#15599]
### Describe the bug

In PrimeNG 17.16.1 when tooltip code is added at the end of , for a less than second it's code takes some height, making body have overflow if your site is set to have height of 100vh
In previous versions of PrimeNG, like 15xx there was no such a problem

### Environment

Angular 17
PrimeNG 17.16.1
![20240516_123415_chrome](https://github.com/primefaces/primeng/assets/46076240/aa1fe976-0a63-4506-b91a-e11b3c9ea3f5)

### Angular version

17.3.0

### PrimeNG version

17.16.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

21.6.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Add pTooltip to anything
2. Make div inside body to have height: 100vh
3. After hovering on pTooltip element, p-tooltip will append to body, consuming height, so it will appear below our 100vh wrapper, giving body overflow

### Expected behavior

Like in PrimeNG 15.x.x, appended p-tooltip to the body should not consume any height not for even 1ms so the overflow will not appear

**Comment by mehmetcetin01140** [comment]
Hi, in the latest PrimeNG version (17.17.0), this issue has been fixed. Could you please try again with the updated version?

Example (v17.17.0) = https://stackblitz.com/edit/yqjz5u-c2d5dk?file=src%2Fapp%2Ftooltip-position-demo.html

I'm closing the issue.

**Comment by Emiliorth** [comment]
Works flawlessly! Thank you for the information :)
