### ISSUE TITLE
pTemplate not working for p-toolbar alone

### ISSUE THREAD

**Issue by krabouilleur** [primefaces/primeng#15608]
### Describe the bug

on a standalone component:

the ts
```
@Component({
  selector: 'app-menu',
  standalone: true,
  imports: [ToolbarModule, AsyncPipe],
```
....
```
<p-toolbar >
        <ng-template pTemplate="end">
            ------> !!!!!!!!!!!!!!! IS NOT SHOWING
        </ng-template>
    </p-toolbar>
```

but the content of ng-template is showing if I add a cardModule
the ts
```
@Component({
  selector: 'app-menu',
  standalone: true,
  imports: [ToolbarModule, AsyncPipe, CardModule],
```
....
```
<p-toolbar >
        <ng-template pTemplate="end">
            ------> !!!!!!!!!!!!!!! IS WORKING
        </ng-template>
    </p-toolbar>
```

### Environment

"primeng": "^17.16.1",
"@angular/core": "^17.3.0",

### Angular version

17.3

### PrimeNG version

17.16.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.9.0

### Browser(s)

chrome

**Comment by maruthumj** [comment]
@krabouilleur please create a sample app in stackblits to investigate this issue further.

**Comment by Sinan997** [comment]
Hi @krabouilleur, please import `SharedModule` to use `PrimeTemplate` Directive.

```ts
import { ToolbarModule } from 'primeng/toolbar';
import { SharedModule } from 'primeng/api';

@Component({
  selector: 'app-menu',
  standalone: true,
  imports: [ToolbarModule, SharedModule],
```

**Comment by SoyDiego** [comment]
> Hi @krabouilleur, please import `SharedModule` to be able to use `PrimeTemplate` Directive.
> 
> ```ts
> import { ToolbarModule } from 'primeng/toolbar';
> import { SharedModule } from 'primeng/api';
> 
> @Component({
>   selector: 'app-menu',
>   standalone: true,
>   imports: [ToolbarModule, SharedModule],
> ```

@Sinan997 you are right here.   @krabouilleur you should import the `SharedModule`.
I have created a **[PR](https://github.com/primefaces/primeng/pull/15619)** and added a line in Imports to be clear.

![image](https://github.com/primefaces/primeng/assets/19764334/f82a09fd-6d91-4f0f-92d0-8814901978f9)

**Comment by alaindeurveilher** [comment]
There is the same issue for the p-menu component. Should a new issue be created?
