### ISSUE TITLE
Slider not working with max value more than 100.

### ISSUE THREAD

**Issue by PardeepJain** [primefaces/primeng#1560]
While Adding  Max value more than 100 it will not working as expected. i used this

    <p-slider [(ngModel)]="rangeValues" [range]="true"></p-slider>

where as 

rangeValues = [10, 2000]

Not wroking, why ? any working example would be highly appreciated.

**Comment by Mrtcndkn** [comment]
I think the problem is that with your maximum value you should add 
    `<p-slider [(ngModel)]="rangeValues" [range]="true" [max]="3000"></p-slider>`

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
