### ISSUE TITLE
TreeTable: Header/Footer columns are misaligned

### ISSUE THREAD

**Issue by can-oezkan** [primefaces/primeng#15610]
### Describe the bug

Header/Footer columns are misaligned

https://primeng.org/treetable#gridlines

https://v18.primeng.org/treetable#gridlines

![image](https://github.com/primefaces/primeng/assets/161650114/b07371dc-a782-4595-8831-1ff11e959a63)

There is a padding of 17px applied to the right of header/footer:
![image](https://github.com/primefaces/primeng/assets/161650114/d983565e-ade2-45ba-b740-e49c031743bf)

### Environment

unrelated

### Reproducer

https://primeng.org/treetable#gridlines

https://v18.primeng.org/treetable#gridlines

### Angular version

unrelated

### PrimeNG version

17.18.12

v18

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

unrelated

### Steps to reproduce the behavior

1. Visit https://primeng.org/treetable
2. View all treetables that have the scroller attribute set to true.

### Expected behavior

Header/Footer columns should align with body columns.

Example ([Table Component](https://primeng.org/table#gridlines)):
![image](https://github.com/primefaces/primeng/assets/161650114/6d49ab88-e9bb-43d2-8b8e-8bad19c70f42)

**Comment by Sinan997** [comment]
This line is responsible for this bug. It adding a padding no matter scroll bar exist or not. 

I have test it in my local, i delete this line and nothing break up. 
But i am not sure, it might broke something. Maybe @cetincakiroglu can help.

https://github.com/primefaces/primeng/blob/b55baa83ea597d9fd5ab0e7198ce6f98810116ec/src/app/components/treetable/treetable.ts#L2423

**Comment by buecherlstefan** [comment]
My Table looks like this :/
Can someone help?

![image](https://github.com/user-attachments/assets/401eef09-5430-4d5d-95af-3fcf510ccf2f)

**Comment by can-oezkan** [comment]
This seems to be fixed now in v18 https://v18.primeng.org/treetable#gridlines

**Comment by can-oezkan** [comment]
Bug is there again: https://v18.primeng.org/treetable#gridlines
![image](https://github.com/user-attachments/assets/c73a9742-57f7-4e0f-b7dd-66d068cc5028)
