### ISSUE TITLE
PrimeNG website out of sync

### ISSUE THREAD

**Issue by rosenthalj** [primefaces/primeng#15616]
### Describe the bug

The current version of PrimeNG is 17.17.0.  PrimeNG's website version is 17.16.1. 
Also, when launching stackblitz from any PrimeNG example,  package.json uses PrimeNG 17.16.1

The following video demonstrates the issue.   Look at the  PrimeNG version number on each of the pages.

https://github.com/primefaces/primeng/assets/45439491/7f946fbd-7397-4e98-bfc3-f9c6aaf68a2f

### Environment

N/A

### Reproducer

https://primeng.org/

### Angular version

17

### PrimeNG version

17.17.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

n/a

### Browser(s)

all browsers

### Steps to reproduce the behavior

1) go to PrimNG website: https://primeng.org/ and check version number
2) launch any stackblitz example and check package.json fo the primeng version number 

### Expected behavior

See the current primeNG version number:  17.17.0

**Comment by mehmetcetin01140** [comment]
Hi, thanks for reporting the issue. The issue has been resolved, so I am closing it.
