### ISSUE TITLE
Component: Input OTP backspace not working in Android Mobile

### ISSUE THREAD

**Issue by vikramthangaraj** [primefaces/primeng#15615]
### Describe the bug

Input OTP backspace not working in Android Mobile

### Environment

Android Backspace

### Angular version

17

### PrimeNG version

17

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20

### Browser(s)

Android Browsers

**Comment by cetincakiroglu** [comment]
Duplicate of https://github.com/primefaces/primeng/issues/15613

Closing the issue
