### ISSUE TITLE
Badge: Badge and BadgeDirective - property badgeSize different

### ISSUE THREAD

**Issue by fabioplateroti** [primefaces/primeng#15622]
### Describe the bug

Into component "**Badge**" and into directive "**BadgeDirective**", the property **badgeSize** are different-

### Environment

no info

### Angular version

17.2.0

### PrimeNG version

17.17.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.9.0

**Comment by SoyDiego** [comment]
Could you edit the title of the issue, please?

thanks!

**Comment by fabioplateroti** [comment]
#15790
