### ISSUE TITLE
Stepper: separator should not be inside the toggleable content on vertical stepper?

### ISSUE THREAD

**Issue by devr52** [primefaces/primeng#15632]
### Describe the bug

Why put the stepper separator inside the toggleable content on vertical stepper? it seems weird to have it this way? what's the use of it, if it is only visible when a step is active?

https://github.com/primefaces/primeng/blob/master/src/app/components/stepper/stepper.ts#L278

This is somewhat contradicting on how the horizontal separator works wherein it's [not together with the content](https://github.com/primefaces/primeng/blob/master/src/app/components/stepper/stepper.ts#L214C2-L216C44)? I am trying to get the same line like in the horizontal, but this is impossible to do in the vertical view because the separator can only be seen when the step is active??

### Environment

N/A

### Angular version

17.3.9

### PrimeNG version

17.16.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.20.2

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
