### ISSUE TITLE
TieredMenu: Submenus is not opening on hover in chrome browser

### ISSUE THREAD

**Issue by rajeshranjan1** [primefaces/primeng#15635]
### Describe the bug

TieredMenu: Submenus is not opening on hover in chrome browser, 

p-menuitem-active class is not adding while hover on the submenu,

### Environment

<p-tieredMenu *ngIf= "isTieredMenu" #menu [model]="options" [popup]="true" appendTo="body" [styleClass]="className"></p-tieredMenu>

### Angular version

17.2.1

### PrimeNG version

17.8.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.9.0

### Browser(s)

Chrome 125.0.6422.61

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
