### ISSUE TITLE
CheckBox: make it a standalone component

### ISSUE THREAD

**Issue by RogueTea** [primefaces/primeng#15638]
### Describe the bug

Based on [Discussion](https://github.com/orgs/primefaces/discussions/923#discussioncomment-9312910). This is a ticket to track the checkbox component
This is not a bug ticket.

### Environment

Windows

### Angular version

17.3.6

### PrimeNG version

17.16.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v21.7.3

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
