### ISSUE TITLE
ContextMenu support for iOS

### ISSUE THREAD

**Issue by kt215** [primefaces/primeng#1563]
ContextMenu is not working on iOS Safari using touch and hold.

How to reproduce: [http://www.primefaces.org/primeng/#/contextmenu](http://www.primefaces.org/primeng/#/contextmenu)

Browser: Mobile Safari 10
iOS 10.1.1 (iPad)

It works fine on Chrome (Desktop and Android) using touch and hold.

**Comment by kt215** [comment]
Issue is also reproducible on iOS 10.2

**Comment by kt215** [comment]
It's been over a year and this is still a problem. @cagataycivici can this be added to an upcoming milestone?

In the mean time, I found a work-around by handling the `touchend` event for Safari. However, even with this work-around, dismissing an open context menu is not easy.

It also looks like a similar issue affect the tooltips, because they don't get easily dismissed either.

**Comment by benignoms** [comment]
It would be a major breakthrough for anyone who works with responsive applications. Today it is unfeasible to use.

**Comment by cagataycivici** [comment]
Please see https://github.com/primefaces/primeng/pull/6459
