### ISSUE TITLE
Table Component: onRowSelect and onRowUnselect events have undefined index

### ISSUE THREAD

**Issue by vindow** [primefaces/primeng#15649]
### Describe the bug

The TableRowSelectEvent and TableRowUnSelectEvent objects coming from onRowSelect and onRowUnselect events have index properties of value undefined.

### Environment

Stackblitz

### Reproducer

https://stackblitz.com/edit/github-nnjcdw?file=src%2Fapp%2Fapp.component.html

### Angular version

17.3.9

### PrimeNG version

17.17.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.1

### Steps to reproduce the behavior

1. Open console
2. Click a table row in the app
3. See that the logged event has undefined index

### Expected behavior

Index should be the actual index of the item in the table data

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Comment by alaindeurveilher** [comment]
Has someone verified if this was fixed? I am on v17.18.12 and have the bug. Is it fixed in earlier versions of PrimeNg?

Edited: Bug is present in v18.0.2.
Edited: Bug is still present in v19.1.3.

**Comment by dsilva01** [comment]
The solution for this problem 
https://github.com/primefaces/primeng/issues/18446#issuecomment-2962338546
