### ISSUE TITLE
p-slider: Vertical slider doesn't work anymore in the related showcase on 17.17.0

### ISSUE THREAD

**Issue by coder80s** [primefaces/primeng#15640]
### Describe the bug

When you go to slider vertical example on https://primeng.org/slider#vertical vertical slider can't be changed, this was working properly in PrimeNG 17.16.1

### Environment

Your production showcase environment.

### Reproducer

This happens when opening related showcase demo stackblitz

### Angular version

17.3.6

### PrimeNG version

17.17.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.18.67

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Go to https://primeng.org/slider#vertical
2. Try to drag down or up the slider

### Expected behavior

Should appear the vertical bar and should  be able to change its value while dragging around.
![image](https://github.com/primefaces/primeng/assets/6144556/e64721b5-75a8-4e29-b223-034dc4c43595)

**Comment by Sinan997** [comment]
It works fine, are you sure there is a bug?

**Comment by coder80s** [comment]
Ok it looks like that now looks fine, weird though. Maybe I had something cached on my browser.
