### ISSUE TITLE
Menubar autoDisplay not working with Chrome Version 125.0.6422.61 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by JeffersonFarFan** [primefaces/primeng#15641]
### Describe the bug

Menubar autoDisplay not working with Chrome Version 125.0.6422.61 (Official Build) (64-bit)
Also not on Primeng website 

### Environment

Chrome Version 125.0.6422.61 (Official Build) (64-bit)
Primeng 17.17

### Angular version

17

### PrimeNG version

17.17.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.10.0

### Browser(s)

Chrome Version 125.0.6422.61 (Official Build) (64-bit)

### Steps to reproduce the behavior

1. Open Chrome Version 125.0.6422.61 (Official Build) (64-bit)
2. Open https://primeng.org/menubar
3. See examples autoDisplay does not have any effect

### Expected behavior

Should work like https://primeng.org/tieredmenu

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
