### ISSUE TITLE
Component: Autocomplete with virtualScroll does not resize options container

### ISSUE THREAD

**Issue by hernanartesi-willdom** [primefaces/primeng#15643]
### Describe the bug

I am upgrading from primeng 14 to 17 and I have a few p-autoComplete with virtualScroll. In the previous version, if the options were wider than the input, it would resize the container accordingly. Removing virtualScroll would work correctly but we have thousands of options so it is not possible for us.

Version 14

![image](https://github.com/primefaces/primeng/assets/153227836/fb11f350-0439-471f-8c11-e06e01ba0dcd)

While after the upgrade it just adds a vertical scrollbar

Version 17

![image](https://github.com/primefaces/primeng/assets/153227836/2b5336e0-c377-46bd-bb38-e64f9dfd999b)

Steps to replicate: it can be replicated with the demo version, just reduce the size of the screen enough

### Environment

Angular app using primeng

### Angular version

17.3.7

### PrimeNG version

17.17.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.3.0

### Browser(s)

Chrome

### Expected behavior

VirtualScroller is resized correctly to the width of the wider element

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
