### ISSUE TITLE
p-autocomplete panel is not closing on clicking outside

### ISSUE THREAD

**Issue by Manoj-077** [primefaces/primeng#15650]
### Describe the bug

I'm unable to close an autocomplete suggestions panel on clicking anywhere outside. Tried adding appendTo="body" too.

https://github.com/primefaces/primeng/assets/116277499/2494d258-cb0c-40b4-8bac-3001b31a2cf6

### Environment

We run primeNg in the angular environment. Our version of angular is 15.2.9.

### Angular version

15.2.9

### PrimeNG version

15.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.0

### Browser(s)

Any browser (preferably chrome)

### Steps to reproduce the behavior

1. Just open the primeNg autocomplete
2. Once the autocomplete panel opens, click outside. The panel doesn't close

### Expected behavior

The autocomplete panel must close on closing outside.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
