### ISSUE TITLE
Table: Reorderable column false still gives cursor move

### ISSUE THREAD

**Issue by Emiliorth** [primefaces/primeng#15656]
### Describe the bug

Table: Reorderable column false and pReorderableColumnDisabled true still gives cursor move

### Environment

Windows 10 PrimeNG 17.17.0 Angular 17

### Angular version

17.3.0

### PrimeNG version

17.17.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

21.6.0

### Browser(s)

Chrome

**Comment by RogueTea** [comment]
Hello, I'm wondering if you're still using pReorderableColumn in your code like: 
```
  <p-table [value]="products" [columns]="cols" [reorderableColumns]="false" [tableStyle]="{ 'min-width': '50rem' }">
                    <ng-template pTemplate="header" let-columns>
                        <tr>
                            <th style="width:3rem"></th>
                            <th *ngFor="let col of columns" pReorderableColumn>
                                {{ col.header }}
                            </th>
                        </tr>
                    </ng-template>
                    <ng-template pTemplate="body" let-rowData let-columns="columns" let-index="rowIndex">
                        <tr [pReorderableRow]="index" [pReorderableRowDisabled]="true">
                            <td>
                                <span class="pi pi-bars" pReorderableRowHandle></span>
                            </td>
                            <td *ngFor="let col of columns">
                                {{ rowData[col.field] }}
                            </td>
                        </tr>
                    </ng-template>
                </p-table>
```

**Comment by Emiliorth** [comment]
Yes, I do use [reorderableColumns] binding on p-table and this is my th:
`
 <th [pReorderableColumnDisabled]="someReordCondition"
        [pSortableColumn]="sortField"
        [pSortableColumnDisabled]="someSortCondition"
        pReorderableColumn
        [id]="id">
...
    </th>
`
I am looping over my @Input() columns instead of using let-columns
I do not use row reordering
