### ISSUE TITLE
peditor: online demo and the code behind does not match

### ISSUE THREAD

**Issue by mustafaekim** [primefaces/primeng#1565]
PrimeNG online p-editor demo has 2 p-editor examples. Second one is said to have a "Custom Toolbar" however it actually does not have a custom toolbar but a standart one.

Secondly, this project does not reflect the code behind the live demos. According to this project, second example would really have a custom toolbar.

**Comment by bro87m** [comment]
Today custom toolbar does not work with **primeng-4.0.0.rc2** and **quill 1.2.4**.

**Comment by cagataycivici** [comment]
I've double checked with a minor improvements, seems good to me;

https://github.com/primefaces/primeng/commit/3c8b62b418ec403e8a84f54160fdae8e8b3a5cde
