### ISSUE TITLE
PrimeNG Radio button not working inside reactive form

### ISSUE THREAD

**Issue by MoInMaRvZ** [primefaces/primeng#15666]
### Describe the bug

The p-radioButton component is not working properly when used inside a reacive form.
Everytime when I use the radio button component inside reactive form i can select every radiobutton like seen in this screenshot
![image](https://github.com/primefaces/primeng/assets/12547883/a355abcb-2f5e-410d-b0e0-990718e50d93)

### Environment

```
<form [formGroup]="hereFormGroup">
<div class="flex flex-col">
      <p-radioButton name="myradiobtn" label="btn1"></p-radioButton>
      <p-radioButton name="myradiobtn" label="btn2"></p-radioButton>
      <p-radioButton name="myradiobtn" label="btn3"></p-radioButton>
      <p-radioButton name="myradiobtn" label="btn4"></p-radioButton>
 </div>
</form>
```

### Angular version

16.2.0

### PrimeNG version

16.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20

### Steps to reproduce the behavior

1. Create a reactive form in typescript
2. Implement form in html template
3. Use radiobuttons as described in environment above

### Expected behavior

You should be able to select only one radio button at a time

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
