### ISSUE TITLE
Table: After reordering columns p-draggable-enter class stays

### ISSUE THREAD

**Issue by Emiliorth** [primefaces/primeng#15662]
### Describe the bug

After reordering columns (dropping column at desired position), p-draggable-enter class stays on <th> element

### Environment

Windows 10 PrimeNG 17.17.0 Angular 17.3

### Angular version

17.3.0

### PrimeNG version

17.17.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

21.6.0

### Browser(s)

Chrome

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
