### ISSUE TITLE
Unexpedted behaviours in the editor

### ISSUE THREAD

**Issue by mustafaekim** [primefaces/primeng#1566]
Even the p-editors on the live demo page is not working correctly. (first one)

When you start writing within the first editor,

- the cursor expectedly goes to the beginning.
- some spaces are removed
- there happen a huge number of **selectionaction** behind. (sometimes indefinilety)

The second demo may work fine, even though I am not quite sure. What is the difference between two?

**Comment by mustafaekim** [comment]
+ this only happens in Chrome

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview

**Comment by Elanor-L** [comment]
We got this problem today and found a solution. In our component, there were 2 editors at the same time in two different p-dialogs. Putting an *ngIf on both editors, so only one exists at the time, prevents this weird behaviour. (Only the editor with data in it had this strange behaviour, this other was fine).
