### ISSUE TITLE
Automplete: autoHighlight=true option no longer works in latest primeng version

### ISSUE THREAD

**Issue by nevius** [primefaces/primeng#15663]
### Describe the bug

I recently upgraded from primeng 16.1.0 to 17.17.0
Now, in the autocomplete component, autoHighlight=true no longer automatically selects the first element in the list of suggestions.

### Environment

Angular app using primeng.

### Reproducer

https://stackblitz.com/edit/4shexj?file=src%2Fapp%2Fautocomplete-objects-demo.html

### Angular version

17.3.9

### PrimeNG version

17.17.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.10.0

### Steps to reproduce the behavior

1. Open StackBlitz example
2. Type "United" into the text input

### Expected behavior

Expected: "United Arab Emirates" suggestion is highlighted and can be selected by hitting Enter key.
Actual: No suggestion is highlighted.

**Comment by nevius** [comment]
I just checked the code and it seems that this behavior is now controlled by the autoOptionFocus option. Maybe the documentation should be updated.

**Comment by Petar-CV** [comment]
Hm, we're having the same issue in one of our projects running PrimeNG 17.18.2
Did you manage to bypass it using autoOptionFocus? @nevius

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Comment by reisi007** [comment]
https://primeng.org/autocomplete --> STill there in V20 documentation

**Comment by Epskampie** [comment]
Still there in v21 documentation.........
