### ISSUE TITLE
Apollo Template is missing p-stepper css styles from css themes

### ISSUE THREAD

**Issue by cosmin19** [primefaces/primeng#15679]
### Describe the bug

StepperModule can not be used properly in Apollo Template due to the fact that all .p-stepper styles are missing from available css themes created in Apollo Template: "assets/layout/styles/theme/theme-\*/\*/theme.css"

### Environment

Windows 10
Angular 17.3.1

### Angular version

17.3.1

### PrimeNG version

17.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.0

### Steps to reproduce the behavior

1. Download Apollo Template
2. Add StepperModule and create a new Stepper in a component. See: https://primeng.org/stepper
3. Observe how the stepper is displayed in browser
![image](https://github.com/primefaces/primeng/assets/10066755/928a1841-0329-4dfa-a863-72ac1a880637)

### Expected behavior

The component should be displayed as in the documentation page: 
![image](https://github.com/primefaces/primeng/assets/10066755/c15d5d07-0f16-4b87-aec2-fa4e60c9a481)

**Comment by KeemOnGithub** [comment]
Same issue for Sakai.

**Comment by KeemOnGithub** [comment]
Similar issue with Sakai.

**Comment by moti-malka** [comment]
Any update about this issue? 
I have same problem with Sakai Template. 
There is workaround to solve this?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
