### ISSUE TITLE
Dialog close

### ISSUE THREAD

**Issue by FallenRiteMonk** [primefaces/primeng#1568]
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
If I have a Dialog open (modal value doesn't matter) and click outside of it, it stays open.

**Expected behavior**
I think it would be a nice to have feature if one could specify the Dialog to close if a user clicks out side of it (it looses focus).

**What is the motivation / use case for changing the behavior?**
Using it as some kind of optional dialog it would be nice if a user could close it with as little effort as possible.

**Comment by cagataycivici** [comment]
Not sure about this but if more users demand it, we'll reopen an option in future.

**Comment by davidalee** [comment]
This is a pretty common feature for modals and should be included IMO. Look at Bootstrap for one example.

**Comment by bevrard** [comment]
+1

**Comment by kboyd31** [comment]
+1

**Comment by muslim-niche** [comment]
+1
