### ISSUE TITLE
[DataTable] Column footer templates don't display.

### ISSUE THREAD

**Issue by jdpearce** [primefaces/primeng#1569]
**I'm submitting a ...** 
```
[x] bug report
```

The documentation indicates the following : 

> A template inside a column must be decorated with pTemplate directive along with the type property to indicate where the template belongs to. Possible values are "header", "body" and "footer".

Yet templates with type "footer" seem to be completely ignored.

**Plunkr Case (Bug Reports)**
A note on this - Plunkr is *blocked* where I work.

**Minimal reproduction of the problem with instructions**

* Component html

````
<p-dataTable [value]="values">
  <p-column>
    <template pTemplate type="header">
        Name
    </template>
    <template let-row="rowData" pTemplate type="body">
        {{row.name}}
    </template>    
    <template pTemplate type="footer">
        Footer
    </template>
  </p-column>
</p-dataTable>
````

* Component ts
````
export class MyComponent  {
  private values: any = [{id: 0, name: "one"}, {id: 1, name: "two"}];
}
````

**Please tell us about your environment:**
Windows, VSCode, NPM, Angular-CLI

* **Angular version:** 2.2.3

* **PrimeNG version:** 1.0.1

* **Browser:** Chrome

**Comment by ilianiv** [comment]
Is it fixed now?

**Comment by moxival** [comment]
@cagataycivici is this fixed? I have exactly the same weird behaviour, it is like i don't even pass footer template:

Is the below correct? Should it work?
```typescript
<p-column field="amount_due" header="Due" sortable="true" filter="true" [style]="{width: '100px'}">
    <template pTemplate="footer">
      <div class="tex-al-right">Sum: {{sumAmountDue}}</div>
    </template>
    <template let-data="rowData" pTemplate="body">
      <div class="tex-al-right">{{data.amount_due | currency:'EUR':true}}</div>
    </template>
  </p-column>
```

PLease note we are on PrimeNG 2.0.3

**Comment by cagataycivici** [comment]
Should be fixed for 4.RC1

**Comment by moxival** [comment]
But is 4.RC1 compatible with Angular 2?

**Comment by cagataycivici** [comment]
No it is not.

**Comment by moxival** [comment]
Will it be ever backported to the current stable version of PrimeNG?

**Comment by cagataycivici** [comment]
2.0.4 has just been released but this couldn't go in. But does it still happen with 4.0.RC1? I can't replicate.

**Comment by moxival** [comment]
Well I don't know about RC1, we are using Angular 2.4.9, cannot use NG 4 because the other libs are not NG4 ready! 

Anyway it will be nice if you can backport it in the stable branch 'cos it is broken ATM

**Comment by cagataycivici** [comment]
Currently no plans, correct me if I'm wrong but Angular 2.x does not get updates from Google as well right? We follow the same level of support.

**Comment by billfranklin** [comment]
Actually, I am experiencing the same problem with v4.1.0-RC.2

**Comment by pantonis** [comment]
Same problem here with Primeng 4.1.2 stable

**Comment by pantonis** [comment]
@cagataycivici is this still a bug?
