### ISSUE TITLE
Accordion -> Throws error when [multiple]="true" and [activeIndex] is set to a value

### ISSUE THREAD

**Issue by LightBulbIdea** [primefaces/primeng#15699]
### Describe the bug

When using an accordion with the multiple property set to true and an activeIndex it throws an error during initialization that only fixes itself when Angular does another change detection cycle. This can cause the whole accordion to not render properly (in certain occasions).

I was able to reproduce this error by using PrimeNG's official example in stackblitz. <https://stackblitz.com/edit/qydhj5?file=src%2Fapp%2Faccordion-dynamic-demo.html>

Here is what I am getting in my Angular App. It seems that this_activeIndex is 0 instead of an array so it blows up in the .includes(). 

![image](https://github.com/primefaces/primeng/assets/134245016/23612a26-5a80-47d2-bf83-e7872fa07592)

  ERROR: TypeError: this._activeIndex.includes is not a function
    at Accordion.updateSelectionState (vendor.js:106674:58)
    at Accordion.initTabs (vendor.js:106665:10)
    at Accordion.ngAfterContentInit (vendor.js:106655:10)
    at callHookInternal (vendor.js:40433:10)
    at callHook (vendor.js:40457:7)
    at callHooks (vendor.js:40417:9)
    at executeInitAndCheckHooks (vendor.js:40372:5)
    at refreshView (vendor.js:47900:11)
    at detectChangesInView$1 (vendor.js:48079:5)
    at detectChangesInViewIfAttached (vendor.js:48042:3)

### Environment

Windows 11, Chrome 125.0.6422.77, Angular 17.3, PrimeNG 17.17.0

### Reproducer

https://stackblitz.com/edit/qydhj5?file=src%2Fapp%2Faccordion-dynamic-demo.html

### Angular version

17.3

### PrimeNG version

17.17.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20

### Browser(s)

Crhome

### Steps to reproduce the behavior

Create an accordion and set both, multiple and activeIndex properties

### Expected behavior

To not error out and render properly.

**Comment by c-o-l-i-n** [comment]
You said it yourself! 🙂 Try setting `activeIndex` to an array:

```html
<p-accordion
  [multiple]="true"
  [activeIndex]="[0]"
>
  <!-- ... -->
</p-accordion>
```

According to the [docs](https://primeng.org/accordion), the `activeIndex` needs to be an array in multiple mode:

> Index of the active tab or an array of indexes in multiple mode.

**Comment by LightBulbIdea** [comment]
Well, I completely missed that. Thank you @c-o-l-i-n
