### ISSUE TITLE
Toast: Misaligned message when detail is missing

### ISSUE THREAD

**Issue by dalenguyen** [primefaces/primeng#15701]
### Describe the bug

When the detail is missing in the MessageService, the alignment looks weird. 

<img width="371" alt="image" src="https://github.com/primefaces/primeng/assets/14116156/af542d0a-5cdb-460a-959f-db10c8a98fb6">

### Environment

Production

### Angular version

17.3.7

### PrimeNG version

17.17.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20

### Steps to reproduce the behavior

1. Go the Stackblitz example from PrimeNG docs
2. Delete the detail option

```
this.messageService.add({ severity: 'success', summary: 'Success' });
```

### Expected behavior

It's should be aligned in the middle

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
