### ISSUE TITLE
Dropdown option does show properly in Dialog

### ISSUE THREAD

**Issue by ABU-BAKKAR-SIDDIK-DEV** [primefaces/primeng#15700]
### Describe the bug

![image](https://github.com/primefaces/primeng/assets/170724429/3d70412d-15a5-4168-904f-f59e7535c26e)

Even trying to scroll down the options tray goes away.

### Environment

local

### Angular version

17

### PrimeNG version

17

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20

**Comment by c-o-l-i-n** [comment]
Try adding `appendTo="body"` to the dropdown:

```html
<p-dropdown
  appendTo="body"
/>
```

This takes the dropdown overlay out of the dialog and puts it straight into the HTML body.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
