### ISSUE TITLE
Column Grouping Support for Scrollable DataTable

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#1570]
Add support for column grouping in a scrollable datatable.

**Comment by haimmag** [comment]
add 
<template [ngIf]="headerColumnGroup">
                          **<colgroup>
                            <col *ngFor="let col of columns" [ngStyle]="col.style" />                            
                          </colgroup>**  
                        </template>                         
                        <thead>                        
                            <template [ngIf]="headerColumnGroup">
                                <tr *ngFor="let headerRow of headerColumnGroup.rows" class="ui-state-default">
                                    <th #headerCell *ngFor="let col of headerRow.columns" [ngStyle]="col.style" [class]="col.styleClass" [attr.colspan]="col.colspan" [attr.rowspan]="col.rowspan"
                                        (click)="sort($event,col)" (mouseenter)="hoveredHeader = $event.target" (mouseleave)="hoveredHeader = null" [style.display]="col.hidden ? 'none' : 'table-cell'"
                                        [ngClass]="{'ui-state-default ui-unselectable-text':true, 'ui-state-hover': headerCell === hoveredHeader && col.sortable,
                                        'ui-sortable-column': col.sortable,'ui-state-active': isSorted(col), 'ui-resizable-column': resizableColumns}"
                                        [tabindex]="col.sortable ? tabindex : -1" (focus)="focusedHeader=$event.target" (blur)="focusedHeader=null" (keydown)="onHeaderKeydown($event,col)">
                                        <span class="ui-column-resizer" *ngIf="resizableColumns && ((columnResizeMode == 'fit' && !lastCol) || columnResizeMode == 'expand')" (mousedown)="initColumnResize($event)"></span>
                                        <span class="ui-column-title" *ngIf="!col.selectionMode&&!col.headerTemplate">{{col.header}}</span>
                                        <span class="ui-column-title" *ngIf="col.headerTemplate">
                                            <p-columnHeaderTemplateLoader [column]="col"></p-columnHeaderTemplateLoader>
                                        </span>
                                        <span class="ui-sortable-column-icon fa fa-fw fa-sort" *ngIf="col.sortable"
                                             [ngClass]="{'fa-sort-desc': (getSortOrder(col) == -1),'fa-sort-asc': (getSortOrder(col) == 1)}"></span>
                                        <input type="text" pInputText class="ui-column-filter" [attr.placeholder]="col.filterPlaceholder" *ngIf="col.filter" [value]="filters[col.field] ? filters[col.field].value : ''" (click)="onFilterInputClick($event)" (keyup)="onFilterKeyup($event.target.value, col.field, col.filterMatchMode)"/>
                                    </th>
                                </tr>
                            </template>

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
