### ISSUE TITLE
AutoComplete: with multiple = true no emitter gets triggered when query input gets emptied

### ISSUE THREAD

**Issue by yorickp** [primefaces/primeng#15705]
#### Use case

Displaying a contextually filtered suggestions list (based on the actual query input value) on each interaction with the query input of a multi-select auto-complete.

#### Context

The following works fine to achieve this in most interaction scenarios:

- Setting `completeOnFocus` to _true_ enables filtering and showing a suggestions list on initial focus through the `completeMethod`.
- (Almost) all _changes to the query input_ also trigger the `completeMethod`, making it once again possible to filter and show a contextually filtered suggestions list.

#### Issue / Gap

Only when the **query input changes from having a value to becoming empty**, there is no proper way to process that into a contextually filtered suggestions list, as nor the `completeMethod` nor the `onClear` gets triggered (even when `minLength` is set to _0_). While with `multiple` set to _false_, `onClear` is triggered in this case.

### Environment

Mac OS 14.5

### Reproducer

https://stackblitz.com/edit/github-skd1tz?file=src%2Fapp%2Fapp.component.html

### Angular version

17.1.3

### PrimeNG version

17.17.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.1

### Steps to reproduce the behavior

In the linked StackBlitz:

1. In the auto-complete query input for `multiple = false`:
  1. type 1 character
  2. erase that character (backspace)
2. In the auto-complete query input for `multiple = true`:
  1. type 1 character
  2. erase that character (backspace)

<img width="247" alt="image" src="https://github.com/primefaces/primeng/assets/17572730/da323dd1-0262-42d0-b58d-64c8394903b6">

With multiple=false `completeMethod` is triggered on having typed a character, and `onClear` is triggered on having erased the character.
With multiple=true `completeMethod` is triggered on having typed a character, and nor `onClear` nor `completeMethod` are triggered on having erased the character.

### Expected behavior

`onClear` to get triggered on erasing the last character in the query input in context of multiple=true, similar to what happens when multiple=false, or (in case there would be a good reason for this behavioural deviation between multiple being true or false) to let `completeMethod` get triggered in this scenario when minLength=0 (as that would also make sense).

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
