### ISSUE TITLE
Tree Component: scrollHeight 'flex' breaks functionality

### ISSUE THREAD

**Issue by novarider** [primefaces/primeng#15719]
### Describe the bug

Reopening #9545 because it's still reproducable. If a tree component with scrollHeight set to 'flex', has an initial empty value and gets a non empty value assigned, tree data is not shown nor the empty placeholder is shown.

### Environment

In our app the tree is empty on pageload and then gets data assigned to it, sadly data are not shown if scrollHeight is set to flex.

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-zwuvcl

### Angular version

17.2.0

### PrimeNG version

17.16.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.2.3

### Steps to reproduce the behavior

- Open stackblitz
- Click 'Fill tree' button to see the tree breaking.

If scrollHeight is changed to e.g. '200px' component is working fine again.

### Expected behavior

scrollHeight should only change height of the tree not key functionality.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Comment by novarider** [comment]
Hi, no problem at least an answer at all :)

We stand right before an angular update, I will check if this bug exists with the new version as well and create a new ticket if needed 👍

**Comment by mertsincan** [comment]
Thanks a lot for your update! We are in a new process regarding issues. https://github.com/primefaces/primeng/issues/17069

Best Regards,
