### ISSUE TITLE
Component: Tree default template not used when unknown type specified

### ISSUE THREAD

**Issue by cluxig** [primefaces/primeng#15711]
### Describe the bug

If a `TreeNode` defines a `type`, it is used as mapping for the rendering `ng-template pTemplate=[type]`. If the tree node has a type, where no `pTemplate` is defined for, the `default` template should be used instead. It makes sense, since `default` should mean `default` and not "type-not-specified".

The issue can be find easily in the code:
```ts
getTemplateForNode(node: TreeNode): TemplateRef<any> | null {
    if (this._templateMap) return node.type ? this._templateMap[node.type] : this._templateMap['default'];
    else return null;
}
```

but it should be:
```ts
getTemplateForNode(node: TreeNode): TemplateRef<any> | null {
    return this._templateMap?.[node.type] ?? this._templateMap?.['default'] ?? null;
}
```

### Environment

nothing to tell

### Angular version

16+

### PrimeNG version

16+

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Expected behavior

the default template shall be used if either no type or non-mapped type is specified

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
