### ISSUE TITLE
p-editor: A jest worker process was terminated by another process

### ISSUE THREAD

**Issue by szymonworld** [primefaces/primeng#15715]
### Describe the bug

I had updated PrimeNG from 17.12.0 to 17.13.0 where introduce fix:
"FIX: Editor Module. ReferenceError: document is not defined. https://github.com/primefaces/primeng/issues/8817 by @nejat-njonjo in https://github.com/primefaces/primeng/pull/14325"
After that I'm getting:
Test suite failed to run

    A jest worker process (pid=x) was terminated by another process: signal=SIGSEGV, exitCode=null. Operating system logs may contain more information on why this occurred.

      at ChildProcessWorker._onExit (../../node_modules/.pnpm/jest-worker@29.7.0/node_modules/jest-worker/build/workers/ChildProcessWorker.js:370:23)

It is from unit test of component which is using p-editor.
All tests pass when I adding flag: --runInBand.
I was using quill 1.3.7 but even with 2.0.2 there is the same error.

### Environment

Pnpm: 8.15.5
NX: 18.1.2

        "jest": "29.7.0",
        "jest-environment-jsdom": "29.7.0",
        "jest-junit": "16.0.0",
        "jest-preset-angular": "14.0.3",
        "quill": "1.3.7",

### Angular version

17.3.1

### PrimeNG version

17.13.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.19.1

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
