### ISSUE TITLE
On delete key press, the characters get shifted by removal

### ISSUE THREAD

**Issue by tanishkasaxenna** [primefaces/primeng#15716]
### Describe the bug

Using datetime mask in input mask when kept cursor on the start of the date and pressing delete, the date does not get deleted section-wise. The characters get shifted to the left.

### Environment

Node version: 20.10.0

### Angular version

17.0.7

### PrimeNG version

17.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.10.0

### Steps to reproduce the behavior

1. Use date mask property for Input mask.
2. The date format is separating the date, month and year by the use of special characters (e.g: /, .).
3.  Place the cursor at the start of the field.
4. Press the delete key.
5. The character at the beginning of the field gets removed but the other characters from the right get shifted irrespective of different section.

### Expected behavior

1. On pressing the delete key, the fields should get removed section-wise.
2. Fields from the next section should not get shifted.
3. To delete particular characters, cursor should be placed in that particular section.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
