### ISSUE TITLE
Button: Using Icon + LoadingIcon removes common class

### ISSUE THREAD

**Issue by luprobert** [primefaces/primeng#15736]
### Describe the bug

When using both [icon] + [loadingIcon] somehow the common class name from icon <span> is removed.

### Environment

Firefox, Chrome, StackBlitz

### Reproducer

https://stackblitz.com/edit/bh1tmu?file=src%2Fapp%2Fbutton-loading-demo.html

### Angular version

17.3.7

### PrimeNG version

17.17.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

21.7.1

### Browser(s)

Firefox, Chrome

### Steps to reproduce the behavior

1. Open StackBlitz
2. Check the component app/button-loading-demo.html and see (icon="pi pi-check"
    loadingIcon="pi pi-home")
3. Check the icon <span> classes on the rendered button

### Expected behavior

Both icons should be rendered.

**Comment by SoyDiego** [comment]
Hi @luprobert.
I fixed the problem in #15733.
Now we should wait until PrimeNG Team approve it!.

Thanks for report it!

**Comment by daniel1919-00** [comment]
Hi @SoyDiego.

The same thing happens regardless of the webfont used, for example with fontawesome: [check stackblitz](https://stackblitz.com/edit/bh1tmu-5627cr?file=src%2Fapp%2Fbutton-loading-demo.html) . 

Does your fix only apply to the primeng pi icons?

**Comment by SoyDiego** [comment]
> Hi @SoyDiego.
> 
> The same thing happens regardless of the webfont used, for example with fontawesome: [check stackblitz](https://stackblitz.com/edit/bh1tmu-5627cr?file=src%2Fapp%2Fbutton-loading-demo.html) .
> 
> Does your fix only apply to the primeng pi icons?

Yes my solution is only applying for `pi` icons. I'm checking if I can fix it for FontAwesome too

**Comment by daniel1919-00** [comment]
We should look for a more generic solution, the issue seems to be that common classes between [icon] and [loadingIcon] are removed from the first input.

**Comment by SoyDiego** [comment]
> We should look for a more generic solution, the issue seems to be that common classes between [icon] and [loadingIcon] are removed from the first input.

I tried a lot of things and I cannot yet. Maybe I will cancel my PR, maybe someone has a better solution

**Comment by SoyDiego** [comment]
@daniel1919-00 I think now I fixed. Now is adding the text that you write perfectly in your `icon` and `loadingIcon` attribute. If you can check will be nice.

**Comment by daniel1919-00** [comment]
@SoyDiego Just tested it now using your PR with pictogrammers material design webfonts and it seems to be fixed 😄. Great work!

**Comment by SoyDiego** [comment]
> @SoyDiego Just tested it now using your PR with pictogrammers material design webfonts and it seems to be fixed 😄. Great work!

great! thanks for testing it!
Now we should wait to PrimeNG Team approve it and consider my solution good too!

Thanks again =)
