### ISSUE TITLE
Table (+ Calendar): p-table requires p-calendar module even if it isn't used

### ISSUE THREAD

**Issue by chasepo** [primefaces/primeng#15737]
### Describe the bug

Building a prod distribution of an angular app that includes a `p-table` with a `p-columnFilterFormElement` results in a build where `primeng-calendar.mjs` is included in the final output. It looks like this might be that p-columnFilterFormElement includes p-calendar regardless of whether it is being used or not.

### Environment

macOS

### Reproducer

https://stackblitz.com/edit/github-1rw5mk

### Angular version

17.3.7

### PrimeNG version

17.16.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.1

### Browser(s)

Chrome 125

### Steps to reproduce the behavior

1. npm install -g source-map-explorer
2. ng build --configuration production
3. source-map-explorer dist/main.js
4. review output
5. verify that `primeng-calendar.mjs` is listed (in my case 75kb/8%)

### Expected behavior

As `p-calendar` is neither used nor explicitly imported, i did not expect it to be included in my final dist output.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
