### ISSUE TITLE
Tree expandToNode does not work

### ISSUE THREAD

**Issue by jisqaqov** [primefaces/primeng#1573]
Good day. expandToNode in Tree does not work in demo page in http://www.primefaces.org/primeng/#/tree example. Generally it  does not work, but it is used to work before. Could you please fix the bug.

**Comment by cagataycivici** [comment]
It is obselete as it is removed in 1.1.

**Comment by vega3000** [comment]
You said expandToNode it's obselete (samething for findPathToNode). 
But what is the new methods to use ? Do you have an alternative ?

**Comment by mmlitvin** [comment]
I would like to know that also
