### ISSUE TITLE
Table: Not responsive within Sidebar Layout from PrimeBlocks

### ISSUE THREAD

**Issue by kaposoniro** [primefaces/primeng#15735]
### Describe the bug

The responsive feature of tables seems to be broken when they are located within the main content of the Sidebar Layout taken from PrimeBlocks. It only seems to be the case when placed within a `flex` container.

### Environment

Chrome, StackBlitz

### Reproducer

https://stackblitz.com/edit/yub5cx-uqtdin

### Angular version

17.3.7

### PrimeNG version

17.17.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.12.2

### Steps to reproduce the behavior

1. Open StackBlitz
2. Open Preview in new tab
3. Shrink the browser until the table extends beyond the page size

![brave_aWq0BHdvOd](https://github.com/primefaces/primeng/assets/149376384/a18edba6-8170-49b8-8e28-e30e6690e353)

### Expected behavior

The table should not extend beyond the page size and display the horizontal scroll bar instead.

**Comment by kaposoniro** [comment]
Expected behavior should be like this:

![brave_t548kmay8M](https://github.com/primefaces/primeng/assets/149376384/27adea2f-df61-476f-b86a-5727291e66b0)

**Comment by Joebeurg** [comment]
Having the same issue, even after updating to 17.18 version which supports Angular V18 peer dependencies.
The other option to avoid having a scrollbar on the BODY element, is using `responsiveLayout="stack"` which changes the table layout on smaller screens.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
