### ISSUE TITLE
View object is not working in PRIMENG schedule with angular 2

### ISSUE THREAD

**Issue by saurabh-NTT** [primefaces/primeng#1576]
I am not able to set custom view in schedule and not able to set view object.

views: {
        agendaFourDay: {
            type: 'agenda',
            duration: { days: 4 },
            buttonText: '4 day'
        }
    }

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
