### ISSUE TITLE
<p-sidebar> closeOnEscape closes on escape in HostListener after it is dynamically set to false

### ISSUE THREAD

**Issue by TriangularPrismSquared** [primefaces/primeng#15760]
### Describe the bug

First, closeOnEscape is set to true in the <p-sidebar [closeOnEscape]="closeOnEscape"> attribute.

A form on this page becomes dirty, and a call is made to change the value to false.

The following code is used on the HostListener to display a modal pop up asking if the user wants to close the box if the escape key is pressed, and the local public variable is false that's being passed into p-sidebar.  ChangeRefreshDetection.detectChanges has also been manually pushed.

@HostListener('document:keydown', ['$event'])
  handleKeyboardEvent(event: KeyboardEvent) {
    // Check if the Escape key was pressed
    if (event.key === 'Escape' && !this.closeOnEscape) {
      console.log(this.sidebar);
      this.displayCloseModal();
    }
  }

In the console.log, I pass the ViewChild of the sidebar, this is the display:

![image](https://github.com/primefaces/primeng/assets/171197950/2bfd23e7-2d43-417b-9360-f5bf552cb536)

As you can see, the 'closeOnEscape" in the snip is false.

Result:  The sidebar closes, and the modal will appear.

Tested:  This does not happen if I set the closeOnEscape directly to false in the p-sidebar.  This seems to only happen with dynamic changes.

### Environment

Angular 16.0.0

### Angular version

16.0.0

### PrimeNG version

16.9.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

21.7.3

### Steps to reproduce the behavior

Have a <p-sidebar> open with a form.  Have <p-sidebar #sidebar [closeOnEscape]="closeOnEscape">  On load, have it sent to true.

Dirty the form.  On dirty, change the closeOnEscape variable that you're passing in to false.

Use similar code below to evaluate when the key is pressed. 

 @ViewChild('sidebar') sidebar: ElementRef;

@HostListener('document:keydown', ['$event'])
  handleKeyboardEvent(event: KeyboardEvent) {
    // Check if the Escape key was pressed
       console.log(this.sidebar);
    if (event.key === 'Escape' && !this.closeOnEscape) {
      console.log(this.sidebar);
      this.displayCloseModal();
    }
  }

Despite closeOnEscape being false, the drawer will close on escape, but the modal will open.  You will note in the console.logs that closeOnEscape in the p-sidebar ViewChild will be set to false. 

### Expected behavior

Once the closeOnEscape tag is set to false dynamically, the escape key should not close the p-sidebar and should function the same way as it currently does statically.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
