### ISSUE TITLE
Menu: Using templates requires importing SharedModule (or other component module)

### ISSUE THREAD

**Issue by yorickp** [primefaces/primeng#15767]
### Describe the bug

While other components inherently come with the potential of using templates as described in their API, the Menu component does not. E.g. using templates of the Menu component (cf. start, end, item and/or submenuheader) in scope of a standalone component does not work without also importing another PrimeNG component (e.g. ButtonModule, ...) or the SharedModule directly (which exposes `PrimeTemplate`).

### Environment

macOS 14.5

### Reproducer

https://stackblitz.com/edit/github-g5f1tz?file=src%2Fapp%2Fapp.module.ts

### Angular version

17.3.10

### PrimeNG version

17.17.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.1

### Steps to reproduce the behavior

Isolate a Menu component implementation with a custom template applied for any of the available templates (`start`, `end`, `item` and/or `submenuheader`) in a context with `MenuModule` as its sole PrimeNG import.

Actual behaviour:
The template customisations are not applied.

### Expected behavior

The custom menu template(s) to be applied.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
