### ISSUE TITLE
p-dropdown: p-dropdown-open style is missing from dropdown

### ISSUE THREAD

**Issue by jaspertolsma** [primefaces/primeng#15762]
### Describe the bug

We have a chevron icon that rotates when our p-dropdowns are opened. To detect whether a dropdown is opened we use the p-dropdown-open class. We were on PrimeNG 15.4.1 and updated recently to PrimeNG 17.7.0. In this version of PrimeNG the p-dropdown is missing the p-dropdown-open class. It is still mentioned in the [docs](https://primeng.org/dropdown#style), however in [this](https://github.com/primefaces/primeng/commit/99a83d0832aafa4d3d88eff54cf747742f00056c) commit you can see it is removed. Without this class we cannot detect whether the dropdown is opened. 

The p-inputwrapper-focus class has partial overlap with the p-dropdown-open class, but is also set when the dropdown is focused, but not opened, so doesn't fit our use case.

### Environment

Chrome

### Angular version

17.3.10

### PrimeNG version

17.17.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Steps to reproduce the behavior

1. Open a primeng dropdown
2. See in the html that the class p-dropdown-open is not set.

### Expected behavior

1. Open a primeng dropdown
2. The class p-dropdown-open is set on the dropdown.

**Comment by B34v0n** [comment]
Hi, I just had the same issue, but I was able to find a workaround.
You can use the `aria-expanded`-tag to see if it is opened:
```css
p-dropdown div.p-dropdown div.p-dropdown-trigger[aria-expanded='true'] {
    rotate: 180deg;
}
```

**Comment by willmca** [comment]
@jaspertolsma @B34v0n I have raised a PR that will address this issue
