### ISSUE TITLE
Header of scrollable Table covers the dialog when [maximizable]="true"

### ISSUE THREAD

**Issue by angelasrc93** [primefaces/primeng#15769]
### Describe the bug

We have a table and on the last column a button which opens a dialog. When the table is [scrollable]=true and the dialog is [maximizable]="true" the table header row is above the opened dialog. With [scrollable]=false the popup behaves as expected. See the attached screenshot.

### Environment

Angular and Primeng 17
![table dialog issue](https://github.com/primefaces/primeng/assets/71488702/dc0df14c-e0e0-4d43-9680-93e59520eb83)

### Angular version

17.3.4

### PrimeNG version

17.15.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.12.1

### Browser(s)

Chrome Version 123.0.6312.122 (Official Build) (64-bit)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
