### ISSUE TITLE
[Table] pTemplate="body" : variable let-x is "any" type

### ISSUE THREAD

**Issue by krabouilleur** [primefaces/primeng#15777]
### Describe the bug

In my ts component:
`foos$!: Observable<Foo[]>;`

in my html template: 
```
@if (foos$ | async; as foos) {
    <p-table [value]="foos">
        <ng-template pTemplate="body" let-foo> // foo is any instead of Foo
            <tr>
                <td>{{ foo.code }}</td> // foo is any instead of Foo
```

The variable (here let-foo) is any type instead of Foo, (not inferred)

is there a way to have a strongly typed variable ?

### Environment

Angular 17 (standalone), Windows 11, 

### Angular version

^17.3.0

### PrimeNG version

17.16.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.9.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

```
@Component({
  selector: 'app-foo',
  standalone: true,
  imports: [TableModule, SharedModule, AsyncPipe],
  templateUrl: './api-foo.component.html',
  styleUrl: './api-foo.component.scss'
})
export class FooComponent implements OnInit {

  fooService = inject(FooService);

  foo$!: Observable<Foo[]>;

  ngOnInit(): void {
    this.foos$ = this.fooService.getFoos();
  }
}
```

```
@if (foos$ | async; as foos) {
    <p-table [value]="foos">
        <ng-template pTemplate="body" let-foo> // foo is any instead of Foo
            <tr>
                <td>{{ foo.code }}</td> // foo is any instead of Foo
            </tr>
        </ng-template>
    </p-table>
}

```

### Expected behavior

let-foo typed Foo

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
