### ISSUE TITLE
Component: p-treeselect. Selecting filtered checkbox incorrectly selecting higher nodes

### ISSUE THREAD

**Issue by AndY322** [primefaces/primeng#15776]
### Describe the bug

when using p-treeselect component in checkbox selection mode with filter and filtering child nodes, selecting all filtered nodes - as a result higher nodes selecting as fully selected, but actually they have to be partial selected
![image](https://github.com/primefaces/primeng/assets/34483813/2d779dc5-bbac-4be3-b13f-752431f3f2db)
![image](https://github.com/primefaces/primeng/assets/34483813/45b5beb1-4cbe-4968-99da-3b739bf449a5)

### Environment

N/A

### Angular version

17.0.7

### PrimeNG version

17.12.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.1

### Steps to reproduce the behavior

1. Set up p-treeselect with filter and checkbox mode
2. filter some node with several items to have only one item 
3. select this item
Result - parent node checked as 'fully' selected

### Expected behavior

parent nodes should be marked as 'partial' selected

**Comment by AndY322** [comment]
found one more issue, I guess it is connected with original one, if filtering, and there is a node in another group, after selecting parent nodes is not selected at all after clearing filter, but should be 'partial' selected
![image](https://github.com/primefaces/primeng/assets/34483813/75c98dcf-3d86-4e90-af69-d83fd14ffd8d)
![image](https://github.com/primefaces/primeng/assets/34483813/50bd2e38-f928-4604-9d68-06723d873841)
please let me know if require separate issue for that

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
