### ISSUE TITLE
Component: Table (Advanced Filter)

### ISSUE THREAD

**Issue by mastersys-giovanni** [primefaces/primeng#15778]
### Describe the bug

In the advanced filter popup, when you press enter, the filter is applied, but does not save, that is, when you click outside to hide the popup, you lose the filter.

### Environment

Windows 12

### Angular version

18.0.1

### PrimeNG version

17.8.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.14

### Browser(s)

Chrome

### Steps to reproduce the behavior

in the advanced filter example itself

### Expected behavior

When you press enter, it should have the same behavior as clicking apply

**Comment by rosenthalj** [comment]
The video listed below recreates the bug described in the issue.  I followed the steps provided in the description:  "when you press enter, the filter is applied, but does not save, that is, when you click outside to hide the popup, you lose the filter."


https://github.com/primefaces/primeng/assets/45439491/e32da37f-627f-42dd-8eb2-38216e680ea3

**Comment by cetincakiroglu** [comment]
Fixed in https://github.com/primefaces/primeng/pull/15808
