### ISSUE TITLE
Use Checkbox component: MultiSelect

### ISSUE THREAD

**Issue by mehmetcetin01140** [primefaces/primeng#15770]

**Comment by mehmetcetin01140** [comment]
Fixed in [18.0.0-beta.1](https://github.com/primefaces/primeng/releases/tag/18.0.0-beta.1)

**Comment by Heydydon** [comment]
Hi, it seems this caused a regression in the component's accessibility, no aria-label is put on the select all checkbox, and the attribute toggleAllAriaLabel and the config translation.aria.selectAll / translation.aria.unselectAll don't work anymore
