### ISSUE TITLE
Component: AutoComplete

### ISSUE THREAD

**Issue by LMS5413** [primefaces/primeng#15774]
### Describe the bug

When use onShow or onHide event, this property "event" returns undefined.

### Environment

Linux Mint
Bun.sh (In reproducer its using Node JS)
Angular.JS v18

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-eqfehj

### Angular version

18.0.2

### PrimeNG version

17.18.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

Bun.SH 1.1.8+89d25807f (In reproduce, Node 20 LTS)

### Browser(s)

Tested With: Brave, Mozila Firefox

### Steps to reproduce the behavior

1) Create AutoComplete component
2) Include onShow or onHide event
3) Log event property

### Expected behavior

Returns event property value.

**Comment by LMS5413** [comment]
Observation: I tried using Angular.JS v17 but same problem.


```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.3.8
Node: 21.7.1 (Unsupported)
Package Manager: bun 1.1.8
OS: linux x64

Angular: 17.3.10
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.8
@angular-devkit/build-angular   17.3.8
@angular-devkit/core            17.3.8
@angular-devkit/schematics      17.3.8
@angular/cli                    17.3.8
@angular/ssr                    17.3.8
@schematics/angular             17.3.8
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.6
```

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
