### ISSUE TITLE
Avatar: badge does not work with circle shape

### ISSUE THREAD

**Issue by AnTiiK** [primefaces/primeng#15783]
### Describe the bug

The badge is not visible with circle shape

### Environment

{
  "name": "primeng-avatar-label-demo",
  "description": "PrimeNG AvatarLabelDemo",
  "license": "MIT",
  "keywords": [],
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test"
  },
  "dependencies": {
    "primeng": "17.18.0",
    "@angular-devkit/build-angular": "^18.0.2",
    "@angular/animations": "^18.0.1",
    "@angular/cdk": "^18.0.1",
    "@angular/cli": "^18.0.2",
    "@angular/common": "^18.0.1",
    "@angular/compiler": "^18.0.1",
    "@angular/compiler-cli": "^18.0.1",
    "@angular/core": "^18.0.1",
    "@angular/forms": "^18.0.1",
    "@angular/platform-browser": "^18.0.1",
    "@angular/platform-browser-dynamic": "^18.0.1",
    "@angular/platform-server": "^18.0.1",
    "@angular/router": "^18.0.1",
    "chart.js": "4.4.2",
    "primeflex": "^3.3.1",
    "primeicons": "^7.0.0",
    "quill": "2.0.2",
    "rxjs": "~7.8.1",
    "tslib": "^2.5.0",
    "zone.js": "~0.14.0"
  }
}

### Reproducer

https://stackblitz.com/edit/ywg1qx?file=src%2Fapp%2Favatar-label-demo.html

### Angular version

18.0.0

### PrimeNG version

17.18.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Steps to reproduce the behavior

1. Open the repro
2. See the difference between circle and square shapes 

### Expected behavior

The badge must be display same as square shape

**Comment by stevenrlp** [comment]
Issue seems to still be there is version 18, I was able to solve it by adding the following css: (not sure if it is correct but it works)

`.p-avatar {
    overflow: visible;
}`

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
