### ISSUE TITLE
TreeTable: misalignment of rows with frozen column if browser's zoom less than 100%

### ISSUE THREAD

**Issue by grek-andrian** [primefaces/primeng#15789]
### Describe the bug

Misalignment of rows between frozen and unfrozen parts when the vertical scroll moved into the down position in case the browser's zoom is less than 100% (e.g. 80%)
![primeng-treetable](https://github.com/primefaces/primeng/assets/13050475/a9ac67d4-d4b2-4510-a989-681e61d7faa9)

### Environment

Chrome

### Angular version

17

### PrimeNG version

17.18.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Browser(s)

Chrome 125

### Steps to reproduce the behavior

1. Open treetable with frozen column and vertical scroll. 2. Change the browser's zoom to 80% 3, Move the vertical scroll into the down position 4. Check the alignment of the rows

### Expected behavior

Rows of frozen and unfrozen parts are aligned

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
