### ISSUE TITLE
IconField: Does not work correctly if InputTextModule is not imported too

### ISSUE THREAD

**Issue by aberonni** [primefaces/primeng#15798]
### Describe the bug

The `IconField` component does not render correctly if `InputTextModule` is not explicitly imported (although not explicitly used). I don't know if this is a documentation error, or a bug.

When following [IconField documentation](https://primeng.org/iconfield):

```ts
import { IconFieldModule } from 'primeng/iconfield';
import { InputIconModule } from 'primeng/inputicon';

@Component({
  ...
  imports: [
    IconFieldModule,
    InputIconModule,
  ],
```

I see this:

![image](https://github.com/primefaces/primeng/assets/1260402/305c973c-2ea2-4d1a-81da-64ac5d604aa6)

If I add the `InputTextModule` import, it works fine:

```diff,ts
import { IconFieldModule } from 'primeng/iconfield';
import { InputIconModule } from 'primeng/inputicon';
+import { InputTextModule } from 'primeng/inputtext';

@Component({
  ...
  imports: [
    IconFieldModule,
    InputIconModule,
+   InputTextModule
  ],
```
![image](https://github.com/primefaces/primeng/assets/1260402/4ad0eb34-d36a-4fde-8dca-24666f8fb30d)

### Environment

N/A

### Angular version

17.3.0

### PrimeNG version

17.18.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.20.0

**Comment by SoyDiego** [comment]
> ### Describe the bug
> 
> The `IconField` component does not render correctly if `InputTextModule` is not explicitly imported (although not explicitly used). I don't know if this is a documentation error, or a bug.
> 
> When following [IconField documentation](https://primeng.org/iconfield):
> 
> ```ts
> import { IconFieldModule } from 'primeng/iconfield';
> import { InputIconModule } from 'primeng/inputicon';
> 
> @Component({
>   ...
>   imports: [
>     IconFieldModule,
>     InputIconModule,
>   ],
> ```
> 
> I see this:
> 
> ![image](https://private-user-images.githubusercontent.com/1260402/337152160-305c973c-2ea2-4d1a-81da-64ac5d604aa6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5Mzg1MTcsIm5iZiI6MTcxNzkzODIxNywicGF0aCI6Ii8xMjYwNDAyLzMzNzE1MjE2MC0zMDVjOTczYy0yZWEyLTRkMWEtODFkYS02NGFjNWQ2MDRhYTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDlUMTMwMzM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2JhNzUxNGJjNmVhZjI0NThhY2IzZDhhYjQzZDVjOWE3Mzg3NDY0ZTE2NjRiZWQ2NjRiZmM2MDU2YWI2MzBlNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uegbPXsF3zF0RTHEvAxdT76PV8nNPxH0fdvDhOHVFjw)
> 
> If I add the `InputTextModule` import, it works fine:
> 
> ```diff
> import { IconFieldModule } from 'primeng/iconfield';
> import { InputIconModule } from 'primeng/inputicon';
> +import { InputTextModule } from 'primeng/inputtext';
> 
> @Component({
>   ...
>   imports: [
>     IconFieldModule,
>     InputIconModule,
> +   InputTextModule
>   ],
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/1260402/337152952-4ad0eb34-d36a-4fde-8dca-24666f8fb30d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5Mzg1MTcsIm5iZiI6MTcxNzkzODIxNywicGF0aCI6Ii8xMjYwNDAyLzMzNzE1Mjk1Mi00YWQwZWIzNC1kMzZhLTRmZGUtOGRjYS0yNDY2NmY4ZmIzMGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDlUMTMwMzM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTc5MTQ0N2JhYzQ0OTlkY2YyNThhNzZkZDg2M2FkODE5ZTI3Mzc5MTg3YTQ5NDQyNmEzZjk2OGM5NzZlODFlYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mtp82Gt1lRlJrstLnr4gucjhuSzX_j2_Aax7xh2nIyM)
> ### Environment
> 
> N/A
> ### Reproducer
> 
> _No response_
> ### Angular version
> 
> 17.3.0
> ### PrimeNG version
> 
> 17.18.0
> ### Build / Runtime
> 
> Angular CLI App
> ### Language
> 
> TypeScript
> ### Node version (for AoT issues node --version)
> 
> 18.20.0
> ### Browser(s)
> 
> _No response_
> ### Steps to reproduce the behavior
> 
> _No response_
> ### Expected behavior
> 
> _No response_

Thanks for report it!
I have created a PR #15814 adding the import to documentation
