### ISSUE TITLE
Component: InputNumber unneeded update model on blur 

### ISSUE THREAD

**Issue by Zodiark1020** [primefaces/primeng#15799]
### Describe the bug

When using p-inputNumber component with updateOn 'blur' strategy, the model is updated on blur even when no changes were made.
This causes many unwanted notifications to the form and potentially to other controls.

My use case is in a reactive form, though this behaviour also happens with ngModel due to the _**else if**_ in this method:
![img](https://github.com/primefaces/primeng/assets/42294130/d3cd1087-26ae-4c8a-9aa3-1f00ff45f15e)

### Environment

Angular 17
PrimeNG 17.17.0

### Angular version

17.3.x

### PrimeNG version

17.17.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.x

### Expected behavior

I expect what already happens on updateOn 'change', i.e., when the value hasn't changed there is no need to call onModelChange

**Comment by mehmetcetin01140** [comment]
Hi,

Could you please share a stackblitz example so we can identify the issue clearly?

**Comment by Zodiark1020** [comment]
Any news about this issue?
