### ISSUE TITLE
Component: Paginator. "Show All" option in dropdown always displayed first

### ISSUE THREAD

**Issue by markuczy** [primefaces/primeng#15793]
### Describe the bug

When you use paginator with `rowsPerPageOptions` property you can display "All" option. However, it will always be displayed first event if you define it as last in `rowsPerPageOptions`.

```html
<p-paginator 
    ...
    [rowsPerPageOptions]="[10, 20, 30, { showAll: 'All'}]" />
```

I would expect that the following snippet would result in 'All' option displayed last in dropdown.
You could probably simply not do unshift but just push 'All' option whenever someone puts it in `rowsPerPageOptions` - https://github.com/primefaces/primeng/blob/master/src/app/components/paginator/paginator.ts#L409

### Environment

N/A

### Angular version

17

### PrimeNG version

17.18.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.1

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
