### ISSUE TITLE
I can't show tooltip for disabled steps

### ISSUE THREAD

**Issue by NikolasTrapp** [primefaces/primeng#15801]
### Describe the bug

It would be great to have a way to show tooltips in the `<p-steps>` component items even if the step is disabled.

### Environment

Angular

### Angular version

17.2.3

### PrimeNG version

17.10.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.1

### Browser(s)

any

**Comment by Sinan997** [comment]
`p-disabled` class is prevents the pointer events. 
https://github.com/primefaces/primeng/blob/e5f593ea1f856a398414830b5cb613a5705fae4e/src/app/components/common/common.css#L49

You can manually change this behaviour by setting `pointer-events: all;`

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
