### ISSUE TITLE
Dropdown: onBlur event is emitted when the user clicks the dropdown arrow

### ISSUE THREAD

**Issue by gpobr** [primefaces/primeng#15800]
### Describe the bug

When the user clicks the expand arrow in a focused dropdown, the blur event is emitted.

### Environment

Windows 11

### Reproducer

https://stackblitz.com/edit/hhqsns?file=src%2Fapp%2Fdropdown-basic-demo.html

### Angular version

17.1.2

### PrimeNG version

17.18

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.9.0

### Steps to reproduce the behavior

1. Set a dropdown to autofocus
2. Add an onBlur event emitter
3. While the dropdown is focused, click on the dropdown arrow

### Expected behavior

The blur event should be emitted only when the user clicks outside the dropdown element. The dropdown arrow is part of the dropdown.

**Comment by puschie286** [comment]
still happens when filter is enabled
https://stackblitz.com/edit/hhqsns-mce5qf?file=src%2Fapp%2Fdropdown-basic-demo.html
