### ISSUE TITLE
RadioButton: On low-pixel-density displays, Aura radio buttons are misshapen and unaligned when `rem` units not a multiple of 4

### ISSUE THREAD

**Issue by c-o-l-i-n** [primefaces/primeng#15803]
### Describe the bug

On displays with a 1:1 pixel ratio, radio buttons in the Aura theme are misshapen and unaligned when `rem` units are not a multiple of 4.

The default `font-size` for the PrimeNG documentation site (and my company's app) is `14px`, which causes the radio buttons not to render properly.

Browsers do not render half-pixels well on low-pixel-density displays. When the `rem` unit is a multiple of 4, all radio button height & width values are integers. However, for example, when `rem` is set to `14px`, the height & width of the radio button is `17.5px`, and the height & width of the inner icon is `10.5px`.

Screenshots direct from primeng.org:

### Good :)

|12px|16px|20px|
|---|---|---|
|![image](https://github.com/primefaces/primeng/assets/40863449/c8985541-ebf1-4a05-9b11-74a55ac02e6c)|![image](https://github.com/primefaces/primeng/assets/40863449/2f7710cf-3b0c-466f-9464-c9e5da414274)|![image](https://github.com/primefaces/primeng/assets/40863449/ddce1029-96ab-4008-a966-81774fd2b767)|

### Not so good :(

|10px|14px (default size on primeng.org)|18px|
|---|---|---|
|![image](https://github.com/primefaces/primeng/assets/40863449/938fc15a-24c4-4674-a784-c544f010021e)|![image](https://github.com/primefaces/primeng/assets/40863449/c087d8ab-e377-4cf3-a834-06ead79c9fac)|![image](https://github.com/primefaces/primeng/assets/40863449/4170243a-efa7-4540-88e3-d289286cf7fa)|

I can't find pixel density usage statistics, but I imagine this issue affects many PrimeNG users. Angular and PrimeNG thrive in complex enterprise dashboards. Most corporations are probably not giving their employees high-pixel-density displays.

**Edit:** This issue also affects [PrimeVue](https://primevue.org/radiobutton/):

|14px|
|---|
|![image](https://github.com/primefaces/primeng/assets/40863449/5aca7274-1e88-49c1-97d6-91e014e986e4)|

### Environment

Chrome with a 1920 x 1200 monitor.

### Reproducer

https://primeng.org/radiobutton

### Angular version

18.0.0

### PrimeNG version

17.18.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

-

### Steps to reproduce the behavior

View a radio button on a low-pixel-density display.

### Expected behavior

Radio buttons should be concentric circles in all font sizes and display types.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Comment by drakenfly** [comment]
I can confirm that this is still a problem in PrimeNG@v19.0.6.

I didn't see a reopen that is linked to this issue.
