### ISSUE TITLE
Improve AutoComplete Object support

### ISSUE THREAD

**Issue by remmeier** [primefaces/primeng#1580]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Object support for the auto-complete component is currently rather limited. A "field" attribute can be set to choose one of the fields. A varierty of things can this way not be supported (like internationalization, combinding multiple fields, etc.).

Two options would be:

- allow to specify a template (like for the suggestions)
- allow to specify a pipe

At some point both should potentially be supported. A template is more flexible but also more work. While a pipe is simple and could be used for both the items and the suggestions.

**Comment by cghislai** [comment]
There is an existing workaround that should probably be documented.
Bind the ngModel attribute to a string (using `[ngModel]`, not `[(ngModel)]`.
Use an object array for suggestions.
In the onComplete event handler, take your object instance and set the ngModel-bound  string to the value of your choice.

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview

There is selectedItemTemplate now.
