### ISSUE TITLE
Page freezes on resize when using many pFrozenColumn

### ISSUE THREAD

**Issue by PronDmytro** [primefaces/primeng#15816]
### Describe the bug

The page is freezing on resize when using many pFrozenColumns.
In my work project, the page never unfreezes. I [reproduced](https://stackblitz.com/edit/vxva11?file=src%2Fapp%2Ftable-frozen-columns-demo.html) a similar table, and here the page freezes for 1-2 seconds.

Upd: When there are more rows, the freeze lasts longer.

It looks like the main problem is in this listener, because a listener is created for each instance of pFrozenColumn.
https://github.com/primefaces/primeng/blob/e5f593ea1f856a398414830b5cb613a5705fae4e/src/app/components/table/table.ts#L3329-L3338

### Environment

Windows 11

### Angular version

17.3.0

### PrimeNG version

17.18.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.12.1

**Comment by nikolaSim** [comment]
This is critical, it freezes the whole application.

**Comment by lautarogfernandez** [comment]
Is there any news from this fix? it is also freezing the whole application when it tries to run this method updateStickyPosition.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Comment by MrRebchik** [comment]
I tried it on version 19. the problem of freezing when resizing remains
