### ISSUE TITLE
p-calendar

### ISSUE THREAD

**Issue by jm-csi** [primefaces/primeng#15813]
### Describe the bug

when using p-calendar with these properties
        <p-calendar 
        appendTo="body" 
        formControlName="" 
        [showIcon]="true" 
        [minDate]="" 
        (onSelect)=""
        (onInput)=""
        [touchUI]="" 
        [showOnFocus]="false"
        [selectOtherMonths]="true">
        
  on an android device if you click on the input so its focused and select the icon to open the calendar the calendar will sometimes close immediately without allowing you to make any calendar selection.

### Environment

our environment uses angular and primeng. 

### Reproducer

https://stackblitz.com/edit/github-y7ydws?file=src%2Fapp%2Fapp.component.html

### Angular version

17.1.0

### PrimeNG version

17.4.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.13.0

### Browser(s)

android 13

### Steps to reproduce the behavior

on an android device have the input filled out for the p-calendar leave it focused and select the p-calendar icon

### Expected behavior

the calendar should open and not close right away

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
