### ISSUE TITLE
Dialog is not draggable via touch

### ISSUE THREAD

**Issue by sthabring** [primefaces/primeng#15827]
### Describe the bug

The dialog is not draggable on touch devices 

### Environment

No special Environment. This even happens in the documentation: https://primeng.org/dialog

### Reproducer

https://stackblitz.com/edit/github-pjuqh4?file=src%2Fapp%2Fapp.component.html

### Angular version

17.3.11

### PrimeNG version

17.18.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.14.0

### Steps to reproduce the behavior

1. Go to https://stackblitz.com/edit/github-pjuqh4?file=src%2Fapp%2Fapp.component.html
or https://primeng.org/dialog on a device that **support touch interactions**
2. Open a dialog a dialog
3. Try to drag the dialog via touch 

### Expected behavior

The dialog is draggable via touch

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
