### ISSUE TITLE
Password: Wrong icon for show/hide password toggle

### ISSUE THREAD

**Issue by SoyDiego** [primefaces/primeng#15826]
If you have the `******` should be the eye icon with slash.
If you have `your text` should be the eye icon.

## Problem

![image](https://github.com/primefaces/primeng/assets/19764334/a6eb0d77-8db2-4069-b710-5e4e5ea8e09c)

### Environment

-

### Reproducer

https://primeng.org/password#togglemask

### Angular version

Last version

### PrimeNG version

Last version

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20

### Steps to reproduce the behavior

https://primeng.org/password#togglemask

### Expected behavior

Invert the icons

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
