### ISSUE TITLE
SplitButton: Broken in RTL mode

### ISSUE THREAD

**Issue by aberonni** [primefaces/primeng#15824]
### Describe the bug

RTL:

![image](https://github.com/primefaces/primeng/assets/1260402/07f7d840-5599-478d-960c-b8b6d00ea398)

I'm well aware that RTL mode is not officially supported. I am opening this issue because I would like to submit a PR addressing it.

### Environment

I am testing this on the PrimeNG website

### Angular version

N/A

### PrimeNG version

17.18.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

N/A

### Steps to reproduce the behavior

1. Go to the [SplitButton documentation page](https://primeng.org/splitbutton)
2. Open the devtools
3. Paste `document.documentElement.dir = 'rtl'` in the console

**Comment by aberonni** [comment]
For additional context, this was supposedly fixed in the past: https://github.com/primefaces/primeng/commit/af86bcb62f825d3c2605f7b20e9467ab19d79e43

But since then, the `dir` option has become obsolete and unused.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Comment by aberonni** [comment]
It's indeed fixed, thanks!
