### ISSUE TITLE
markAllAsTouched not firing

### ISSUE THREAD

**Issue by krabouilleur** [primefaces/primeng#15823]
### Describe the bug

I've an input text, with a validator required.
If I write then I make the field empty, the field is red (cause ng-dirty + ng-invalid)

If I click on my submit button which test the form with "markAllAsTouched() the field is not red (ng-invalid but not ng-dirty)

### Environment

angular 17 standalone

### Angular version

17.3.0

### PrimeNG version

17.16.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.9.0

### Browser(s)

chrome

### Steps to reproduce the behavior

html:

```
<form [formGroup]="form" class="flex">
            <div class="flex flex-column gap-2">
                <label for="name">xxxx</label>
                <input pInputText id="name" [formControl]="f_name" />
                <small id="key-alias-help">xxx</small>
            </div>
        </form>
 <p-button [label]="xxx" (onClick)="test()"/>
```

component:

```
Component({
  standalone: true,
  imports: [ReactiveFormsModule...],
```

```
get f_name() {
    return this.form.get('name') as FormControl;
  }
  form = this.fb.group({
    name: [null, [Validators.required]]
  });
```

```
test() {
    this.form.markAllAsTouched();
```

### Expected behavior

inputtext become red with the ng-dirty css class

**Comment by B34v0n** [comment]
Hi there, I got the same Issue and created a stackblitz for it. https://github.com/primefaces/primeng/issues/16118
I just saw, that you tried to do it with `markAsTouched()`, which only sets the fields to touched, not to dirty.
I need the error to be seen as soon as the field is `touched`, not only on `dirty`.

For your use-case, you could iterate over the fields and use the `markAsDirty`-Method, which sets them to dirty, so the error is shown

**Comment by MarkusY123** [comment]
Hi, it is still an issue in the version 18.

And because this is not working as expected, the examples given in the official documentation about form validation are not working with PrimeNG.

https://angular.dev/guide/forms/form-validation

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
