### ISSUE TITLE
Dropdown: options in cleared if initialized during component constructor

### ISSUE THREAD

**Issue by axos88** [primefaces/primeng#15839]
### Describe the bug

if `[options]` is initialized from a field initializer, it's value is reset to undefined, but if it's initialized within ngOnInit(), it works.

### Environment

n/a

### Angular version

17

### PrimeNG version

master

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

n/a

### Browser(s)

chrome latest

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
