### ISSUE TITLE
InputOtp: Android Phones - MoveToNext is not called after input

### ISSUE THREAD

**Issue by televicDev** [primefaces/primeng#15846]
### Describe the bug

If you use an Android Phone to input characters in the InputOtp component, multiple characters are inserted in the same input element.

### Environment

Android Phone - Samsung A54 & A55
Reproduceable on [the PrimeNG demo](https://primeng.org/inputotp#basic)

### Angular version

17.3.5

### PrimeNG version

17.18.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.20.2

### Browser(s)

Chrome on Samsung phone

### Steps to reproduce the behavior

Type into the input field on a real device.
All of the characters are added to the first input.

The behavior is OK on emulators and can only (for us atleast) be reproduced on real devices

### Expected behavior

I expect that after inputting a character the focus is moved to the next input but instead all of the characters I am inputting are added to the same input.

https://github.com/primefaces/primeng/assets/91054218/b8365c1d-25db-44da-8ede-9ab8cfdece1e

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
