### ISSUE TITLE
Multiselect: selectionLimit not working

### ISSUE THREAD

**Issue by ZeroSkill830** [primefaces/primeng#15842]
### Describe the bug

Setting the selectionLimit property does nothing.

Ex: i set [selectionLimit]="3" but i can choose more than 3 options

### Environment

Issue is reproducible with all Angular v > 16.0

### Reproducer

https://stackblitz.com/edit/github-bozwmz?file=src%2Fapp%2Fapp.component.html

### Angular version

16.2.0

### PrimeNG version

16.9.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

17.1.0

### Steps to reproduce the behavior

1 Go to the slackblitz url provided
2 Select more than 3 options
3 Unchecked options are still enabled if selectionLimit is reached

### Expected behavior

I'm expecting to see all the unchecked options disabled if the selectionLimit is reached.

**Comment by trigiacbmt** [comment]
I checked this issue in version 17.18.0. It is working well. Please retest with the latest version @ZeroSkill830

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
