### ISSUE TITLE
Calendar: Popup appears partly offscreen even when there's enough vertical space

### ISSUE THREAD

**Issue by adama357** [primefaces/primeng#15841]
### Describe the bug

Under certain conditions, the calendar popup appears too high on the screen and gets cut off. This seems to happen within a certain range if (1) the calendar input has `[appendTo]="'body'"` set, (2) the browser is zoomed in to at least 120%, and (3) you have to scroll down to get to the calendar input. 

(Setting `[appendTo]="'body'"` is necessary if the calendar input is inside of a dialog popup.)

![CalendarShouldFit](https://github.com/primefaces/primeng/assets/20462430/46bad44b-025c-4db2-b229-675fc7b0a754)

### Environment

Windows 10

### Reproducer

https://stackblitz.com/edit/github-gccr6n?file=src%2Fapp%2Fapp.component.html

### Angular version

17.3.11

### PrimeNG version

17.18.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.12.1

### Browser(s)

Chrome 125, Firefox 116

### Steps to reproduce the behavior

1. Set your browser zoom to >= 120%.
2. Scroll down so that the calendar input is approximately in the middle of the screen (or a little higher).
3. Click on the calendar input.

### Expected behavior

If there isn't enough vertical space to show the calendar popup attached to the input, the popup should appear right below the top of the screen. (This is how it works normally.)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
