### ISSUE TITLE
Component: calendar component doesn't display the clear icon properly in certain conditions

### ISSUE THREAD

**Issue by abhijit-chikane** [primefaces/primeng#15843]
### Describe the bug

![image](https://github.com/primefaces/primeng/assets/50770619/5948fdcc-f009-4023-866d-cf691d588f0c)
with IconDisplay 'input' shows incorrectly
Calendar having both input icon and clear icon does not show properly

with
IconDisplay 'button' it works properly
![image](https://github.com/primefaces/primeng/assets/50770619/320c2dd4-45b4-42bf-bec9-6c1927f9f380)

### Environment

Angular 17 project

### Reproducer

[Stackblitz](https://stackblitz.com/edit/github-gccr6n-buqo2f?file=src%2Fapp%2Fapp.component.html)

### Angular version

17.2.0

### PrimeNG version

17.18.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.9.0

### Browser(s)

Edge 126

### Steps to reproduce the behavior

set both 
                <p-calendar [showIcon]="true"
                            [iconDisplay]="'input'"
                            [timeOnly]="true"
                            hourFormat="12"
                            [showClear]="true" />

### Expected behavior

it should show the icon's properly

**Comment by SoyDiego** [comment]
The same issue was reported here: https://github.com/primefaces/primeng/issues/15834

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
