### ISSUE TITLE
Component: Table. Resizable columns with column grouping

### ISSUE THREAD

**Issue by dperezfadonminsait** [primefaces/primeng#15844]
### Describe the bug

When using grouped Columns with resizableColumns the resize functionality fails.

example: https://stackblitz.com/edit/6cvsqv?file=src%2Fapp%2Ftable-column-group-demo.html

### Environment

Primeng 17, Angular 18

### Reproducer

https://stackblitz.com/edit/6cvsqv?file=src%2Fapp%2Ftable-column-group-demo.html

### Angular version

18.0.1

### PrimeNG version

17.18.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

17.18.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

Resize in table headers, first works, with the others weird things happens.
Without colspan > 1 in tds of the header everything goes ok.

### Expected behavior

Everything resizes with  no problems.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
