### ISSUE TITLE
Table: Frozen columns are displaced

### ISSUE THREAD

**Issue by ranthonissen** [primefaces/primeng#15852]
### Describe the bug

In a table with many columns, of which also a large number are frozen, the placement of the fixed columns is totally messed up.
Headers are placed out of order, and row cells are not frozen at all

### Environment

Chrome
Edge
Firefox

### Reproducer

https://github-8nkwy5.stackblitz.io

### Angular version

17.3.9

### PrimeNG version

17.18.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22.2.0

### Steps to reproduce the behavior

1. Open the app
2. Scroll the table horizontally
3. Frozen columns scroll with the table

### Expected behavior

Frozen columns should remain fixed at their position, no matter how many columns are frozen, and no matter how large or small the screen is.

**Comment by ThoSap** [comment]
Could be fixed together with #12210

**Comment by ranthonissen** [comment]
@cetincakiroglu 
Any status update on this issue and PR #15854?
The frozen column issues are a showstopper for our team, and we need to decide if we can move along or need to revert to a version prior to this and related issues.

**Comment by Kirik42** [comment]
> @cetincakiroglu Any status update on this issue and PR #15854? The frozen column issues are a showstopper for our team, and we need to decide if we can move along or need to revert to a version prior to this and related issues.

Up ! Need it too, thanks
