### ISSUE TITLE
Dropdown isOptionDisabled wrong comparisons

### ISSUE THREAD

**Issue by Xriuk** [primefaces/primeng#15855]
### Describe the bug

https://github.com/primefaces/primeng/blob/1a7c2cf489e3d34e99661c3e04cf79685803d519/src/app/components/dropdown/dropdown.ts#L1269-L1275
I'm using the component with optionValue, so values returned are properties of passed options.
There are some wrong comparisons on line 1270:

- `this.getOptionValue(this.modelValue()) === this.getOptionValue(option)` should be `this.modelValue() === this.getOptionValue(option)` since `this.modelValue()` is not an object/option but the actual value, so it is wrong to retrieve a value from a value.
- `this.getOptionLabel(this.modelValue() === this.getOptionLabel(option))` this looks just wrong, not sure what is was supposed to be, it seems to want to compare the value with the label of the given option, so maybe it should be `this.modelValue() === this.getOptionLabel(option)` as you cannot get a label from a value as it is not an object/option.

### Environment

Not applicable

### Angular version

17.3.5

### PrimeNG version

17.13.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.13.0

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
