### ISSUE TITLE
Calendar: Visual heading text is not marked as heading [Accessibility]

### ISSUE THREAD

**Issue by Jogonarr-3Pillar** [primefaces/primeng#15856]
### Describe the bug

Text appears and functions like a section heading but is not marked up as such.

![image](https://github.com/primefaces/primeng/assets/39072072/c7d72099-5cba-46ea-8fa7-571a9599fc16)

The element where the heading markup should go is probably the one with class `p-datepicker-title` since it holds both buttons:

![image](https://github.com/primefaces/primeng/assets/39072072/beec2f69-aa9e-42c6-b2f7-5dc5fd3e2c55)

**RULE :** 
Text that acts as a heading visually or structurally MUST be designated as a true heading in the markup.

**HOW TO FIX:** 
Fix this issue by using ONE of the following techniques:
1. Use \<h1> to \<h6> elements to mark text as a heading. Note: Using real HTML headings (\<h1>, \<h2>, etc.) is preferable when creating new markup.

```html
<h1>Types of Web Accessibility Laws</h1>
<h2>Civil Rights Laws</h2>
<h2>Procurement Laws</h2>
<h2>Industry-Specific Laws</h2>
```

2. When retrofitting legacy markup, using the `role="heading"` attribute, combined with the `aria-level` attribute, can be a useful way to add heading semantics to markup without the risk of breaking any styles that might be attached to the legacy markup. The `aria-level` attribute value is heading level desired.

```html
<div class="heading1" role="heading" aria-level="1">Types of Web Accessibility Laws</div>
```

**REFERENCE:** 
- Deque University: [https://dequeuniversity.com/class/semantic-structure2/headings/real-headings](https://dequeuniversity.com/class/semantic-structure2/headings/real-headings)
- W3C-WAI tutorial: [https://www.w3.org/WAI/tutorials/page-structure/headings/](https://www.w3.org/WAI/tutorials/page-structure/headings/)

**BACKGROUND:** 
People who can see are able to quickly scan a page for headings and subheadings to understand the content and structure of a page. People who are blind do not have this ability if heading text is not marked in a way that screen readers can understand. Heading text and hierarchy must be identified semantically with heading markup. When heading markup is correctly applied, screen readers are able to: communicate that text is a heading and its level, provide a heading outline to users, and allow users to navigate directly from heading to heading.

### Environment

Requires a screen-reader tool installed (tested witn NVDA v2024.1.0.31547) to be able to test how it is being narrated.

![image](https://github.com/primefaces/primeng/assets/39072072/51ef0404-48ed-49fc-9aab-842f8ab34829)

### Reproducer

https://stackblitz.com/edit/github-gw86kd-bcpu5k?file=src%2Fapp%2Fapp.component.html

### Angular version

17.3.11

### PrimeNG version

17.18.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.1

### Browser(s)

Chrome 125.0.6422.142

### Steps to reproduce the behavior

1. Open a screen-reader (tested wth NVDA v2024.1.0.31547)
2. Tab into the calendar
3. Press down arrow on the keyboard
4. Press tab to go to the Previous Month button
5. Press down arrow on the keyboard
6. Notice that it narrates "Button Choose Month Button Choose Year"

### Expected behavior

When navigating with the screen-reader and stepping on the header of the calendar it should read something like:
`heading    level 2  June 2024`

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
