### ISSUE TITLE
Dropdown displays first option when none of the options match the model

### ISSUE THREAD

**Issue by spike83** [primefaces/primeng#1585]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

http://plnkr.co/edit/v90204ZGRGdvgrpZmW7j?p=preview

**Current behavior**
When reactive forms or ngModel provides a value which is not matching one of the options the value remains and the first option of dropdown is shown.

**Expected behavior**
The dropdown component should make sure only a value from options will be returned. When a value is provided that does not match the options a default value should be set.
When a form is submitted the values showing up to the user must be sent.

**Minimal reproduction of the problem with instructions**
Open up the plunker, you can see the drop down is showing up 'New York' but the value is null.

**What is the motivation / use case for changing the behavior?**
- Avoid null values when a choice is required.
- Avoid clash between what the user can see and what's in model.

* **Angular version:** 2.2.3

* **PrimeNG version:** 1.0.0

* **Browser:** all 
 
I made a pull request to fix that #1537

**Comment by aaraggornn** [comment]
+1 I have run into this issue using ngModel. When the model is null the first option is shown unnecessarily.

**Comment by Klinton90** [comment]
I wouldn't agree that null values should be avoided as it might be expected behavior. To fix that you should assign default value in Controller to what ever is provided to `ngModel`:
```
constructor(){
    ...
    this.selectedCity = this.cities[0];
}
``` 

Moreover formInput itself properly validate that case. Add to template to see what I mean:
```
<p-dropdown required #city2="ngModel" [options]="cities" [(ngModel)]="selectedCity"></p-dropdown>
<p>isFormInputValid: {{city2.valid}}</p>
```

**Comment by spike83** [comment]
I agree for simple cases this is a workaround. But IMHO the dropdown control is made to restrict the value to a specific set of values defined by options. If one would like to allow null, it's ok and done by a specific option with value null. 
I think the dropdown should make sure the value coming out is always one of the options list. And what you see is what you get in the model. Always and handled by the dropdown.

**Comment by Klinton90** [comment]
Ok, I see your point. I just tested original Select implementation with Angular2: when model is null or undefined  dropdown shows nothing (white field) as selected value.

**Comment by spike83** [comment]
This is correct for some browsers like chrome. In IE it's diffrent. There the first Option is showing up but model is null.
The dropdown component is absolute necessary to make the behavior consistent over all browsers.

**Comment by LHIOUI** [comment]
I am running into this issue, i think the dropdown should show a placeholder when the model is null like the 'empty' string when no options provided.

**Comment by daleclements** [comment]
This is an issue for me too. It's most problematic because the list item is displayed but the model remains null. Showing nothing would probably be preferable, but modifying the model to match the displayed option would be better than what we have now. Right now the model and view are out of sync initially.

**Comment by cagataycivici** [comment]
What does regular select element do, isn't it the same? For consistency we show the first one. Should we display blank value?

**Comment by yuyingliu331** [comment]
I am writing to express my issue with required field in dropdown select for primeng in angular 2. If I want to show a popup window where user has not selected and I used placeholder in my dropdown. Also, I think there should be a default null value in dropdown instead of placeholder field.

**Comment by shah-bee** [comment]
Is the issue https://github.com/yuyingliu331 solved

**Comment by shah-bee** [comment]
Is the issue required and placeholder solved?

**Comment by Klapsa2503** [comment]
Not working on IE / Edge

**Comment by RomanSyed** [comment]
I also have an issue with the dropdown ,my requirement is that i want to set a default value in dropdown its showing the value in the dropdown but internally its not taking that value its taking null instead

**Comment by RomanSyed** [comment]
> I am writing to express my issue with required field in dropdown select for primeng in angular 2. If I want to show a popup window where user has not selected a value in dropdown and I used placeholder in my dropdown. It doesn't show the popup window. I also used required="required" in my dropdown. I think as soon as I launch the dropdown selection gets the values, the required field is fulfilled. The required is not working properly.

Exactly placeholder works for this, but what if we want some default value instead of placeholder

**Comment by RomanSyed** [comment]
> This is an issue for me too. It's most problematic because the list item is displayed but the model remains null. Showing nothing would probably be preferable, but modifying the model to match the displayed option would be better than what we have now. Right now the model and view are out of sync initially.
> 
> EDIT: As a workaround, you can define a placeholder attribute to display something else, but unfortunately if you just try to put `placeholder=""` you get the first option and if you put `placeholder=" "` with a space then the input ends up having no height. Something like `placeholder="..."` can work though.

Exactly placeholder works but what if we want to set some default value instead of placeholder

**Comment by shreyas9545** [comment]
Hi if there is no searched item exists in dropdown  can we add searched item to dropdown list

**Comment by bjansen** [comment]
> EDIT: As a workaround, you can define a placeholder attribute to display something else, but unfortunately if you just try to put placeholder="" you get the first option and if you put placeholder=" " with a space then the input ends up having no height. Something like placeholder="..." can work though.

It looks like using `placeholder="&nbsp;"` instead of `placeholder=" "` fixes the height issue (at least on Firefox + macOS):

<img width="463" alt="image" src="https://user-images.githubusercontent.com/281528/131477509-a27e5ecf-3812-4019-bd5f-1172f51a5f98.png">

**Comment by xszbencex** [comment]
Try using [autoDisplayFirst]="false" attribute, as the [docs](https://www.primefaces.org/primeng/dropdown) says:

`<html>
<body>

autoDisplayFirst | boolean | true | Whether to display the first item as the label if no placeholder is defined and value is null.
-- | -- | -- | --

</body>
</html>`
