### ISSUE TITLE
Dropdown: property autoDisplayFirst not working with async options (16 lts)

### ISSUE THREAD

**Issue by itx-niklas-baugatz** [primefaces/primeng#15868]
### Describe the bug

If the options property is loaded async (with a BehaviorSubject), the [autoDisplayFirst]="true" property is not working.

The first value, is not selected. It only works, if the data is present on load.

### Environment

Stackblitz, Angular 16 & Primeng 16 lts

### Reproducer

https://stackblitz.com/~/github.com/itx-niklas-baugatz/primengdropdown

### Angular version

16.2.12

### PrimeNG version

16.9.11-lts

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.20.3

### Expected behavior

In earlier versions (i updated from 11) the first value got selected on load

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
