### ISSUE TITLE
Component: picklist scrolls to top

### ISSUE THREAD

**Issue by jayee** [primefaces/primeng#15861]
### Describe the bug

When picklist gets focus, it scrolls to top.

### Environment

Example on https://primeng.org/picklist

### Angular version

18.0.1

### PrimeNG version

17.18.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

-

### Browser(s)

FF, Chrome

### Steps to reproduce the behavior

1. Go to https://primeng.org/picklist
2. Scroll down first example with mouse wheel
3. Click on item

### Expected behavior

It should not scroll to top.
See version 16
https://www.primefaces.org/primeng-v16-lts/picklist

**Comment by jorgebenaventee** [comment]
This also happens on [demo](https://primeng.org/picklist#filter). If you scroll down in source elements and click last one, you'll get scrolled back to the top.

**Comment by rg1220** [comment]
Bump. Seeing this bug as well. Like @jorgebenaventee mentioned, it's happening on the documentation page.

![jump](https://github.com/primefaces/primeng/assets/6728645/53c52371-0644-4de1-8f25-4e944129c2ea)
