### ISSUE TITLE
Dropdown: empty string not a valid option value (16 lts)

### ISSUE THREAD

**Issue by itx-niklas-baugatz** [primefaces/primeng#15875]
### Describe the bug

I updated from primeng 11 to 16 lts and the option value "" or empty string is no longer working. The item is selected, but the label does not show a selection. This was possible in v11.

The selection is even selected in the dropdown.

### Environment

stackblitz, angular 16, primeng 16 lts

### Reproducer

https://stackblitz.com/~/github.com/itx-niklas-baugatz/primengdropdownemptystring?file=src/app/app.component.ts

### Angular version

16.2.12

### PrimeNG version

16.9.11-lts

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.20.3

### Expected behavior

The dropdown should show the selected label. It is marked in the dropdown box as selected

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
