### ISSUE TITLE
unable to copy Accordion header content 

### ISSUE THREAD

**Issue by SanjeevKumarSB** [primefaces/primeng#15870]
I am unable to copy the header of the accordian element.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
