### ISSUE TITLE
Autocomplete: ngModel value changes to null before selecting when forceSelection is true

### ISSUE THREAD

**Issue by OmkarJ13** [primefaces/primeng#15880]
### Describe the bug

When [forceSelection] is enabled on the autocomplete component, when selecting a value the model changes to null for a split second before changing to the selected value. This leads to some weird bugs if the DOM is updated depending upon the autocomplete value.

### Environment

Stackblitz

### Reproducer

https://stackblitz.com/edit/xckznk?file=src%2Fapp%2Fautocomplete-force-selection-demo.html,src%2Fapp%2Fautocomplete-force-selection-demo.ts,src%2Findex.html

### Angular version

18.0.1

### PrimeNG version

17.18.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v18.20.3

### Steps to reproduce the behavior

1. Go to the stack blitz
2. Click on the autocomplete and select "Country 1"
3. You should see a paragraph come up above the autocomplete.
4. Now edit the autocomplete value to remove the "1" and try to click on "Country 2". It will not work because the value got changed to null on blur and DOM updated accordingly, but the actual click did not happen on the dropdown due to a change in its position.

### Expected behavior

The component should not set the model value to `null` before selecting a value when forceSelection is true.

If I use OnSelect event, I don't get the null which is expected. when using ngModel or reactive forms the similar behaviour should be there.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
