### ISSUE TITLE
Dropdown: Inconsistancy between clear function and floatLabel

### ISSUE THREAD

**Issue by Rlamotte** [primefaces/primeng#15888]
### Describe the bug

As a user of primeNg, I encounter a bug using p-floatlabel with p-dropdown when clicking on "clear" button activated when "showClear" is set to true.

When the clear button is clicked, the focus is not going out of the dropdown, causing the floatLabel to be maintain to the top of the input : 
![image](https://github.com/primefaces/primeng/assets/25707233/c46aaaa8-0a5e-4f94-9b88-977f118b7824)

### Environment

Tested on my custom application, and verified using primeNg stackblitz example of dropdown used with p-floatLabel.

### Reproducer

https://stackblitz.com/edit/hyorxr?file=src%2Fapp%2Fdropdown-floatlabel-demo.html

### Angular version

18.0.1

### PrimeNG version

17.18.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.20.3

### Browser(s)

Chrome 126.0.6478.114

### Steps to reproduce the behavior

1. Go to the stackblitz example
2. Start the app, and choose any city
3. Click outside the dropdown to close it
4. Click on the "X" button to clear the dropdown

### Expected behavior

Expected : 
- The dropdown should be maintain closed
- The focus should not be anymore on the dropdown input
- The floatLabel should be in the dropdown input

Current behavior : 
- Focus is maintained on the dropdown, causing the floatLabel to be in top of the input until the user click anywhere else

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
