### ISSUE TITLE
p-tree: disable arrow key navigation 

### ISSUE THREAD

**Issue by gauravp-dev** [primefaces/primeng#15892]
### Describe the bug

I have an input as a tree node and I am not able to use left arrow key or space key as on left arrow key event is registered for expanding tree and space is assigned to for selection. So i am not able to add space inside the input neither I am able to scroll through text inside input box

### Environment

"@angular/animations": "^17.3.6",
"@angular/common": "^17.3.6",
"@angular/compiler": "^17.3.6",
"@angular/core": "^17.3.6",
"@angular/forms": "^17.3.6",
"@angular/platform-browser": "^17.3.6",
"@angular/platform-browser-dynamic": "^17.3.6",
"@angular/router": "^17.3.6",
"pretty-bytes": "^6.1.1",
"primeflex": "^3.3.1",
"primeicons": "^7.0.0",
"primeng": "^17.15.0",
"rxjs": "~7.8.0",
"screenfull": "^6.0.2",
"to-json-schema": "^0.2.5",
"tslib": "^2.3.0",
"uuid": "^9.0.1",
"zone.js": "~0.14.3"

### Angular version

17.3.6

### PrimeNG version

17.15.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
