### ISSUE TITLE
Dynamic Dialog Errors If No Focusable Element (Maximum call stack size exceeded)

### ISSUE THREAD

**Issue by johnhwright** [primefaces/primeng#15894]
### Describe the bug

We use dynamic dialogs fairly aggressively in our applications and after the most recent update and now we get `Maximum call stack size exceeded` errors when opening certain ones:

![image](https://github.com/primefaces/primeng/assets/11820009/1bafcd00-f171-4a03-a18f-c5189ce05a0b)

I've traced this back to dialogs that don't have any focusable element on them at load (see the attached stackblitz). This can be worked around by setting `config.focusOnShow = false;` But we have hundreds of dialogs and having a focusable element isn't always even known until runtime. Would be great if this could be fixed so it doesn't explode if no element is found.

Seems related to https://github.com/primefaces/primeng/pull/15263 

### Environment

n/a

### Reproducer

https://stackblitz.com/edit/github-a35oyt?file=src%2Fapp%2Fapp.component.html

### Angular version

17.3.11

### PrimeNG version

17.18.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

n/a

**Comment by shekhaua** [comment]
The same issue happens in a normal dialog (primeng 17.18.2) component (p-dialog), if focusOnShow parameter is not set to false. 
RangeError: Maximum call stack size exceeded
    at Module.DomHandler (primeng-dialog.mjs:1152:1)
    at Dialog.focus (primeng-dialog.mjs:423:25)
    at Dialog.focus (primeng-dialog.mjs:438:18)
    at Dialog.focus (primeng-dialog.mjs:438:18)
    at Dialog.focus (primeng-dialog.mjs:438:18)
    at Dialog.focus (primeng-dialog.mjs:438:18)
    at Dialog.focus (primeng-dialog.mjs:438:18)
    at Dialog.focus (primeng-dialog.mjs:438:18)
    at Dialog.focus (primeng-dialog.mjs:438:18)
    at Dialog.focus (primeng-dialog.mjs:438:18)

**Comment by radek-furmanski** [comment]
still occurs on version: "primeng": "^19.1.3",

**Comment by johnhwright** [comment]
Still an issue on version: "primeng": "^20.0.1",

**Comment by javierjsp** [comment]
+1, "primeng": "^20.0.1",
