### ISSUE TITLE
p-autocomplete: maxlength attribute type is defined as number | undefined but not able to set value as undefined.

### ISSUE THREAD

**Issue by gauravp-dev** [primefaces/primeng#15891]
### Describe the bug

 maxlength attribute type is defined as number | undefined but behind its using input maxlength attribute i.e 'string | number | null' So if I set maxlength variable type as   `number | undefined` then I get error as 
 - _Type 'number | undefined' is not assignable to type 'string | number | null'.
  Type 'undefined' is not assignable to type 'string | number | null'_

  And if I set as `number | null` then I get error as 
  - _Type 'number | null' is not assignable to type 'number | undefined'.
  Type 'null' is not assignable to type 'number | undefined'_

### Environment

"@angular/animations": "^17.3.6",
    "@angular/common": "^17.3.6",
    "@angular/compiler": "^17.3.6",
    "@angular/core": "^17.3.6",
    "@angular/forms": "^17.3.6",
    "@angular/platform-browser": "^17.3.6",
    "@angular/platform-browser-dynamic": "^17.3.6",
    "@angular/router": "^17.3.6",
"pretty-bytes": "^6.1.1",
    "primeflex": "^3.3.1",
    "primeicons": "^7.0.0",
    "primeng": "^17.15.0",
    "rxjs": "~7.8.0",
    "screenfull": "^6.0.2",
    "to-json-schema": "^0.2.5",
    "tslib": "^2.3.0",
    "uuid": "^9.0.1",
    "zone.js": "~0.14.3"

### Angular version

17.3.6

### PrimeNG version

17.15.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
