### ISSUE TITLE
AutoComplete: Fails to display options on space.

### ISSUE THREAD

**Issue by kubrauzunn** [primefaces/primeng#15901]
### Describe the bug

In PrimeNG version 15.x, it was possible to trigger the dropdown options in the AutoComplete component by pressing the space bar, as demonstrated in the [v15 documentation](https://www.primefaces.org/primeng-v15-lts/autocomplete).

<img width="853" alt="image" src="https://github.com/primefaces/primeng/assets/57157434/a23e11bb-4a11-4c12-9245-185f6af10386">

However, after upgrading to version 17.x, this functionality appears to be missing. Users are no longer able to display the dropdown options by using the space bar. Based on the documentation it seems like it has been like this since version 16. Please refer to the [v17 documentation](https://primeng.org/autocomplete) for the current implementation example.

<img width="796" alt="image" src="https://github.com/primefaces/primeng/assets/57157434/1aeca513-7536-4f09-b261-cd5c64bdb0e6">

### Environment

Angular v17+ with PrimeNG v17+. 

### Angular version

17.12.0

### PrimeNG version

17.12.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.12.0

### Steps to reproduce the behavior

1) Implement the basic AutoComplete component as shown in the [v17 documentation](https://primeng.org/autocomplete).
2) Attempt to trigger the dropdown options by pressing the space bar.

### Expected behavior

The dropdown options should display when the space bar is pressed, similar to the behavior in version 15.x.

**Comment by cetincakiroglu** [comment]
Hi,

We've made accessibility enhancements between v16.7x and v17. Mentioned behavior is not longer exists with autoComplete. However, you can still open autocomplete options by space if you focus on dropdown button, space registers as a button click in this case.

This behavior will not be re-implemented. I am closing the issue.
