### ISSUE TITLE
Password: When disabled allows to edit on focus tab

### ISSUE THREAD

**Issue by Pablo200206** [primefaces/primeng#15905]
### Describe the bug

When using keyboard navigation with a disabled p-password, the component gets focused and allows to edit the content of the input

### Environment

PrimeNG 17, can be tried in the documentation page https://primeng.org/password

### Reproducer

https://primeng.org/password

### Angular version

17

### PrimeNG version

17.18.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Browser(s)

Edge

**Comment by Pablo200206** [comment]
I just created a PR, it looks that disabled wasn´t binded to the inner input, also, there weren´t disabled styles for it

**Comment by mehmetcetin01140** [comment]
Fixed id #15906
