### ISSUE TITLE
Frozen row not working properly when frozen column is present

### ISSUE THREAD

**Issue by MatejJanotka** [primefaces/primeng#15912]
### Describe the bug

If I have cell which belongs to frozen column and also to frozen row the cell is not sticky if scrolling table vertically.

### Environment

I reproduced it on stackblitz link below
![frozen-buggy](https://github.com/primefaces/primeng/assets/72610532/3f9b71b0-2672-4cf7-800a-3217f7e5c150)

[link to stackblitz](https://stackblitz.com/edit/ncaeuw)

### Angular version

17.2.3

### PrimeNG version

17.18.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.12.2

### Browser(s)

all

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
