### ISSUE TITLE
Calendar: Range selection mode with numberOfMonths > 1 should show end date in the last showed month

### ISSUE THREAD

**Issue by szymonworld** [primefaces/primeng#15918]
### Describe the bug

The PR https://github.com/primefaces/primeng/issues/15818 introduced a bug to the calendar in range selection mode.

### Environment

macOS Sonoma 14.5

### Reproducer

https://stackblitz.com/edit/github-naqavf-tdvop1?file=src%2Fapp%2Fapp.component.html

### Angular version

17.3.1

### PrimeNG version

17.17.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.19.1

### Browser(s)

Arc 1.48

### Steps to reproduce the behavior

1. Open calendar
2. Select some date range with at least 2 months
![Screenshot 2024-06-28 at 14 25 20](https://github.com/primefaces/primeng/assets/9286136/14eee84b-e3ce-46b7-bf02-b8fe8eb45f87)
3. Close calendar
4. Open calendar
5. First calendar shows end date and the second one is empty
![Screenshot 2024-06-28 at 14 25 29](https://github.com/primefaces/primeng/assets/9286136/932c31de-5bdd-4e48-b28c-daa191481f2a)

### Expected behavior

All showed months should be used to show selected date range, without context switching on reopen of calendar.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
