### ISSUE TITLE
Component: p-dropdown

### ISSUE THREAD

**Issue by ug-amaurya** [primefaces/primeng#15919]
### Describe the bug

Used [editable]="true" in a dropdown and used that in p-tabView when tabs changed dropdown control is patched with optionValue instead of optionLabel.

### Environment

local

### Angular version

16.2

### PrimeNG version

16.6

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Browser(s)

Chrome

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
