### ISSUE TITLE
Add .warn severity class

### ISSUE THREAD

**Issue by jorgebenaventee** [primefaces/primeng#15913]
### Describe the bug

In version 17.15.0, buttons and messages severity options included "warn" to display them with a yellow background. As of 17.18.1 it is replaced by "warning" breaking compatibility with themes like [Freya](https://freya.primeng.org/#/) as it only supports "warn" as a class. As a workaround, you can use `[severity]="$any('warn')"` to render them correctly.

### Environment

I am using Angular 17.3.8 with Node version v20.5.1 and PrimeNG version 17.18.1

### Angular version

17.3.8

### PrimeNG version

17.18.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.5.1

**Comment by davidda** [comment]
This should be fixed asap. It is even wrong in PrimeNGs demo pages. The type requires "warning" but to make it work you must set "warn".

https://stackblitz.com/edit/yckkaz?file=src%2Fapp%2Fmessages-severity-demo.ts

**Comment by cetincakiroglu** [comment]
Hi @davidda @jorgebenaventee ,

Thanks for reporting the issue, probably it happens due to a typo. It should be warn not warning. We'll address this issue in 17.18.3 this week.
