### ISSUE TITLE
Icon: pi-list-check missing

### ISSUE THREAD

**Issue by eluchsinger** [primefaces/primeng#15929]
### Describe the bug

When using  `pi pi-list-check`, it seems to be missing or not showing up.

If I change it to for example `pi pi-bars`, it seems to work.

```tyescript
protected tabs: MenuItem[] = [
    {
      label: "Doesnt work",
      icon: "pi pi-list-check",
      routerLink: ["route-1"],
    },{
      label: "Works!",
      icon: "pi pi-bars",
      routerLink: ["route-2"],
    },
  ];
```

### Environment

MacOS, probably not relevant.

### Angular version

18.0.5

### PrimeNG version

17.18.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.12.0

### Browser(s)

Edge

**Comment by anaisberg** [comment]
I have the same issue (MacOs, Chrome,   primeng: 17.12.0,  @angular/core: 17.3.0)

**Comment by eluchsinger** [comment]
Same thing for `pi-bell-slash` by the way.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
