### ISSUE TITLE
Dropdown: The return type of a 'get' accessor must be assignable to its 'set' accessor type

### ISSUE THREAD

**Issue by manikandan2k29** [primefaces/primeng#15935]
### Describe the bug

Getting "The return type of a 'get' accessor must be assignable to its 'set' accessor type" error once I've added the package to my application and compiled the code.

### Environment

Im using Angular 16 for my project

### Angular version

16

### PrimeNG version

17.18.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Browser(s)

chrome

### Steps to reproduce the behavior

Install the ngprime.
Add DropdownModule
Compile the code 
Getting error message in terminal

### Expected behavior

Should not get error message
When I change the type of getPlaceholder manually its working fine

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
