### ISSUE TITLE
Menubar: the display is not correct if the menu is on the right

### ISSUE THREAD

**Issue by Garfield-fr** [primefaces/primeng#15932]
### Describe the bug

If you align a menu to the right when you open it, the menu will stick out of the window. It should be right-aligned and not left-aligned.

### Environment

Angular 18 on Linux

### Reproducer

https://stackblitz.com/edit/mn18wx?file=src%2Fapp%2Fmenubar-template-demo.ts,src%2Fapp%2Fmenubar-template-demo.html

### Angular version

18.0

### PrimeNG version

17.18.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.0

### Browser(s)

Chrome

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Comment by Garfield-fr** [comment]
I've tested the menu with version 19, and there's no change. The bug is still there. If the main menu is on the right, the sub-menu should open on the left. It opens on the right and is outside the window.
