### ISSUE TITLE
Component: Slider

### ISSUE THREAD

**Issue by ShreenidhiBodas** [primefaces/primeng#15947]
### Describe the bug

Cannot select values by clicking on the slider.
min and max for the slider are set (0 and 10 respectively).
Following things work:
* Dragging the slider
* focusing and using keyboard

This does not:
* clicking on the slider to select. If the slider is clicked till value 9, then just by clicking on the slider, 10 cannot be selected

### Environment

Angular 18
PrimeNG 17

### Reproducer

https://stackblitz.com/edit/rjnawj?file=src%2Fapp%2Fslider-basic-demo.html

### Angular version

18.0.2

### PrimeNG version

17.18.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.20.3

### Steps to reproduce the behavior

1. Click on the slider bar to select a value
2. go on clicking ahead to select the next value
3. when the value reaches 9, try clicking on the very end of the slider bar 
Behaviour: 10 cannot be selected

### Expected behavior

Default step for the slider is 1. with this, clicking on the slider bar should update the slider value

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
