### ISSUE TITLE
P-Splitter: Can't change template visibility at runtime

### ISSUE THREAD

**Issue by R0binSmit** [primefaces/primeng#15940]
### Describe the bug

I have probably found a bug in the P-Splitter. The misbehaviour relates to the restriction of the visibility of individual areas within the P-Splitter. If I define a P-Splitter with two defined areas, I can restrict the visibility of the areas using the "ng-templates" & "ngIf" (see test case 1 from my example). However, it is not possible to change the visibility at runtime (see test case 2 from my example). There I used "setTimeOut" to change the visibility of an area to "hidden" after 5 seconds. However, this has no influence on the DOM. 

### Environment
* Microsoft Windows 11 Pro
* IDE: Visual Studio 2022

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-onvsgv

### Angular version

18.0.0

### PrimeNG version

17.18.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

17.18.2

### Steps to reproduce the behavior

1. Implement a P-Splitter with two templates
2. Restrict the visibility of one template by "*ngIf" and a boolean
3. Change the visibility restriction at runtim (by setTimeOut for example)

### Expected behavior

After changing the Boolean value in *ngIf, the change is taken into account and the DOM is adjusted accordingly (set template visibility).

**Comment by mehmetcetin01140** [comment]
Hi, as a workaround until the issue is fixed, you can use this: https://stackblitz.com/edit/stackblitz-starters-ptlv7q?file=src%2Fmain.ts.

**Comment by R0binSmit** [comment]
Thanks for your quick response. The workaround works fine 👍.

**Comment by R0binSmit** [comment]
Please open the bug ticket again. The bug has not been fixed.

**Comment by R0binSmit** [comment]
Why is this issue closed? Is there any solution?

**Comment by mohammed-b** [comment]
I have the same issue. Not possible to hide ng-templates on runtime using the @if

**Comment by Marlaqk** [comment]
Same issue on my project. Native solution would be preferred over ViewChild manipulation.
