### ISSUE TITLE
p-dialog: Close icon elipsis shape instead of circle

### ISSUE THREAD

**Issue by Emiliorth** [primefaces/primeng#15941]
### Describe the bug

Using github saas theme lara light blue, not precompilled but using 
@import './primeng-sass-theme/themes/lara/lara-light/blue/theme'; (17.18.1)
"close" icon has elipsis shape (20px left and right)
![image](https://github.com/primefaces/primeng/assets/46076240/9b6fe1e3-ec6b-47c4-a647-98ad347325f4)
![image](https://github.com/primefaces/primeng/assets/46076240/ce666208-2daf-48d3-8f93-9a69917a6c98)
it gets pading from .p-button from _calendar.scss:114

### Environment

Angular 18,
PrimeNG 17.18.2

### Angular version

18.0.3

### PrimeNG version

17.18.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22.2.0

### Browser(s)

Chrome

**Comment by duarch** [comment]
My workaround is this:

name.component.scss

```scss

:host ::ng-deep .p-dialog .p-dialog-header .p-button {
  padding: 0;
}
```

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
