### ISSUE TITLE
change date outside of calendar

### ISSUE THREAD

**Issue by lilling** [primefaces/primeng#1595]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
when changing the date value that linked to the calendar it does not change.

**Expected behavior**
the calendar will show the correct date

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/MnZnGs8jORjpCodTV5JA?p=preview

**What is the motivation / use case for changing the behavior?**
isnt that obvious?

**Please tell us about your environment:**

windows vscode 

* **Angular version:** 
2.1.0

* **PrimeNG version:** 
1.0.0

**Comment by luigidallavalle** [comment]
Still here in 1.1.3, any update?

@lilling did you managed to write a workaraound?

**Comment by lilling** [comment]
@luigidallavalle in the plunker it was fixed.

**Comment by luigidallavalle** [comment]
I think the plunker is not working as expected: pressing he date is changed but the calendar doesn't reflect those changes.
I forked a new plunker that uses version 1.1.4 and the issue seems to be there.
here it is http://plnkr.co/edit/LntAFNmsR5h5iNikZ7bs?p=preview

**Comment by lilling** [comment]
you mean it should move to the current date? you right. reopening.

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
