### ISSUE TITLE
pInputText: maximum call size exceeded on table

### ISSUE THREAD

**Issue by Danny220** [primefaces/primeng#15952]
### Describe the bug

I have a table with pInputText inputs. If I set the size of the table to 50, it gives me "maximum call size exceeded" error. 

`<input
  *ngIf="col.type === fieldTypes.TEXT"
  type="text"
  pInputText
  class="p-inputtext-sm"
  [ngModel]="item[col.id]"
  [disabled]="col.id == 'Code' && item.LongPK > 0"
  (ngModelChange)="onEdit(item, col.id, $event)"
/>
`

if I remove the pInputText directive the error doesn't occur.

### Environment

Angular 15 & PrimeNG 15.0.1, it's a ERP (factory manager) application that we are developing.

### Angular version

15.0.0

### PrimeNG version

15.0.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.10.0

### Steps to reproduce the behavior

1. create an editable table with a lot of records and a lot of columns with a textbox
2. set the table dimension to 50

### Expected behavior

"maximum call size exceeded" should not occur

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Comment by alpacamannn** [comment]
Still doesnt work.
