### ISSUE TITLE
progress-bar value not visible when using material theme

### ISSUE THREAD

**Issue by majkers** [primefaces/primeng#15957]
### Describe the bug

When I set material as my theme progress bar stops displaying value. You can check it on demo page here:

https://primeng.org/progressbar

### Environment

Demo page https://primeng.org/progressbar

### Angular version

17

### PrimeNG version

17.8.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

N/A

### Browser(s)

All

### Steps to reproduce the behavior

1. Go to https://primeng.org/progressbar
2. Switch theme to material
3. Check results

### Expected behavior

I think value should be seen regardless theme selected

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
