### ISSUE TITLE
p-badge: p-badge-no-gutter missing

### ISSUE THREAD

**Issue by Emiliorth** [primefaces/primeng#15950]
### Describe the bug

![image](https://github.com/primefaces/primeng/assets/46076240/dae9eb38-01b8-4b81-a259-7b2ae183116e)
p-badge-no-gutter is missing when adding warning severity
Also, when adding pBadge to the custom div and even without severity, this class isn't added.

### Environment

PrimeNG, Angular, Lara Light Blue sass theme from github, no precompilation

### Angular version

18.0.3

### PrimeNG version

17.18.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22.2.0

**Comment by volvachev** [comment]
Hi, this class `p-badge-no-gutter` is added if the property(`value`) is set.

**Comment by volvachev** [comment]
For a value whose `length` === `1`.

**Comment by Emiliorth** [comment]
I see, thank you :)
