### ISSUE TITLE
p-multiselect: chips and selectedItems bug

### ISSUE THREAD

**Issue by Emiliorth** [primefaces/primeng#15953]
### Describe the bug

When you use display="chips", after selecting some items and then changing array of options to different in comparision to selected items, labels inside chips disappear.
When you use pTemplate and let-selectedItems, those becomes empty array.
It should carry some values copy, instead of some options based ones (I'm guessing) 

### Environment

Angular, PrimeNG

### Angular version

18.0.3

### PrimeNG version

17.18.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22.2.0

### Browser(s)

Chrome

**Comment by mehmetcetin01140** [comment]
Hi,

Could you please share a stackblitz example so we can identify the issue clearly?

**Comment by Emiliorth** [comment]
Hello,

I am little unable to do that. I can post code here.
This is an example for selectedItems to be different than form control value, when you have some options, select few of them and then change options array value to different array (like when you get paged data from BE when you type something in filter)
`<p-multiSelect [formControlName]="controlName"
                               [inputId]="inputId"
                               appendTo="body"
                               optionLabel="label"
                               optionValue="value"
                               [options]="options"
                               [filter]="filterable"
                               (onFilter)="setGetMultiselectOptionsTrigger($event)">

                         <ng-template pTemplate="selectedItems" let-selectedItems>
                                   <p-tag styleClass="rad-text-body-support"
                                   [value]="entry.label"
                                   *ngFor="let entry of selectedItems"></p-tag>
                        </ng-template>
                       
                </p-multiSelect>`

When it comes to chips, you just remove custom template and use PrimeNG chips display

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
