### ISSUE TITLE
Contextmenu submenu appears out of view area

### ISSUE THREAD

**Issue by krojew** [primefaces/primeng#1596]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When a context menu has a submenu and it's invoked near the border of the page, the submenu is extended past the browser window causing scroll bars to appear.

**Expected behavior**
Submenu should be positioned on the opposite side, like with desktop menus.

**Minimal reproduction of the problem with instructions**

1. Create a simple context menu wit ha submenu.
1. Clik near the edge of the browser window and observe results.

**What is the motivation / use case for changing the behavior?**
The menu should behave like desktop menus, and not extend the document past the view area size.

**Please tell us about your environment:**
Firefox, TS 2.1.4

* **Angular version:** 2.0.X
2.1.1

* **PrimeNG version:** 2.0.X
1.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Firefox, most likely other too.
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS 2.1.4

**Comment by Mrtcndkn** [comment]
Hi,
Actually thats implemented and i couldn't replicate it can you create a plunker for this.

**Comment by krojew** [comment]
The same issue appears on the demo page: http://www.primefaces.org/primeng/#/contextmenu

**Comment by alexavator** [comment]
Hello, I came across with the same problem. The problem only with SUBMENU. A context menu itself opens normally always, but a submenu always opens to the right side.

**Comment by krojew** [comment]
To illustrate the issue (taken from the demo page): 
![contextmenu](https://cloud.githubusercontent.com/assets/1268573/21304366/048b8b4e-c5c5-11e6-8b30-d8224376c415.png)

**Comment by Mrtcndkn** [comment]
All right i replicated it too i will work on this and get back to you from here.

**Comment by alexavator** [comment]
at whitch version I can get this fix?

**Comment by miresk** [comment]
Could you please also fix the position of the submenu when it is open at the bottom of the page? It overflows the bottom of the viewport.
![contextmenu-issue](https://user-images.githubusercontent.com/2345749/27577067-9eb94004-5b1f-11e7-9157-380ecad583f1.jpg)
