### ISSUE TITLE
p-fileUpload: chooseStyleClass

### ISSUE THREAD

**Issue by kashcode** [primefaces/primeng#15961]
### Describe the bug

style applied on the file-upload component, but it never gets to the button itself.
![image](https://github.com/primefaces/primeng/assets/7689209/70f35a69-8db6-4470-97c9-aad329158d40)
and button:
![image](https://github.com/primefaces/primeng/assets/7689209/5d0324fc-8026-48b3-a534-39f6dd2c7876)

### Environment

Win 10

### Angular version

17.3.5

### PrimeNG version

17.14.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.13.0

### Expected behavior

Upload component choose button should be outlined:
![image](https://github.com/primefaces/primeng/assets/7689209/cfe988fa-cd94-4d22-a3fb-7346000176ae)

**Comment by kheruvimovv** [comment]
In basic mode add your styles to styleClass. There is no chooseButton in basic mode, it's only for advanced mode.
`<p-fileUpload ...
                        mode="basic"
                        styleClass="p-button-outlined">`

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
