### ISSUE TITLE
OverlayPanel, Popover: Changing the dismissable property after the overlayPanel has already been opened has no effect.

### ISSUE THREAD

**Issue by can-oezkan** [primefaces/primeng#15964]
### Describe the bug

Changing the `dismissable` property after the overlayPanel has already been opened has no effect.

### Environment

unrelated

### Reproducer

https://stackblitz.com/edit/github-rhrnsr?file=src%2Fapp%2Fapp.component.html

### Angular version

18.2.12

### PrimeNG version

18.0.0-rc1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

unrelated

### Expected behavior

The current value of the property `dismissable` should be respected.

**Comment by leozulfiu** [comment]
Hi @can-oezkan 

I just ran into the same problem where I have a button on my overlay and clicking it (which fires a request + polling), I want to make the overlay **not** dismissable until I get a certain response. Binding a variable to `[dismissable]="isDialogDismissable"` didn't work either as you tested it. Looking in the code of the overlay I saw that the dismissable Input doesn't get re-evaluated when it changes: https://github.com/primefaces/primeng/blob/master/src/app/components/overlaypanel/overlaypanel.ts#L242

What I did was simply calling the methods `unbindDocumentClickListener` when I press the button (to make it not dismissable) and `unbindDocumentClickListener` when I want to make my overlay dismissable again.

This is what I have in my parent component:
```
  @ViewChild('op') overlayPanel: OverlayPanel;

...
  handle(isGenerating: boolean) {
    if (isGenerating) {
      this.overlayPanel.unbindDocumentClickListener();
    } else {
      this.overlayPanel.bindDocumentClickListener();
    }
  }
```

And handle gets called via an Output from the child itself. The dismissable input is not even needed in that case:

```diff
<p-overlayPanel
- [dismissable]="isDialogDismissable" >
   ...
</p-overlayPanel>
```

Hope this helps you too!
