### ISSUE TITLE
p-dropdown: Unify dropdown behaviour on clear

### ISSUE THREAD

**Issue by Pablo200206** [primefaces/primeng#15972]
### Describe the bug

After applying onclear to the p-dropdown, it becomes focused and the ng-touched class is added, preventing the float label from returning to its original position. This issue does not occur with multiselect and treeselect. Consistent behavior across all inputs with onclear would be a good addition.

### Environment

Angular 18 with last primeng version

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-lbdxsb?file=src%2Fmain.ts

### Angular version

18

### PrimeNG version

17

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20

### Browser(s)

Edge, Chrome...

### Steps to reproduce the behavior

1. Go to https://stackblitz.com/edit/stackblitz-starters-lbdxsb?file=src%2Fmain.ts
2. Clear all the inputs
3. Dropdown has a different behaviour

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
