### ISSUE TITLE
Panel overlay position on a div with css transformations

### ISSUE THREAD

**Issue by T005206** [primefaces/primeng#15975]
### Describe the bug

Hello, I am developing a map using the ReactFlow library. This library uses a div where it renders the map. It is possible to pan and zoom on the map, but it does so with CSS transformations. I am using PrimeReact's OverlayPanel, but I have encountered a problem. If the appendTo of the overlay is set to "self", it moves correctly with the map and applies the same zoom as the map since it is contained within a div to which the CSS transformation is applied. The problem is that it does not position correctly on the element that opens it. Is there any way to override the method PrimeReact uses to position the overlay and take into account the transformation of the parent container? Or, on the other hand, how could I position the element correctly if the container has a transformation? If the appendTo is set to the default, it positions correctly but becomes disconnected when panning or zooming the map.

### Environment

Windows 10
Chrome Versión 126.0.6478.127

### Angular version

13

### PrimeNG version

17

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
