### ISSUE TITLE
Component: Table multiSort event not equal to SortEvent signature

### ISSUE THREAD

**Issue by ToraTengu** [primefaces/primeng#15987]
### Describe the bug

Table component when emiting a multiple sort event does not match the SortEvent interface.

The Output is declared on line **853** and  is triggered, when sortMode is multiple,  on line **1630** of the _table.ts_ file.

> **Obs**: No two-way binding is used because the use case where the issue was detected needs to sync the event with other components...

From the code of the component is seems to indicate that the SortEvent should used on those lines...

### Environment

OS: Window 11

### Reproducer

https://stackblitz.com/edit/github-qsrynb

### Angular version

17.3.11

### PrimeNG version

17.18.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.14.0

### Steps to reproduce the behavior

1. Inthe template, add a p-table with sortMode set to multiple and a onSort callback:
```
<p-table
  . . .
  sortMode="multiple"
  [value]="rows"
  (onSort)="updateSort($event)"
> . . . </p-table>
```
2. in the code wire up the component to handle the event
```
. . . 
public updateSort(event): void {
  this.sortMeta = event.multisortmeta;
} 
. . . 
```
3. Inspect the event object sent to the handler

### Expected behavior

It should return a object that matchjes the SortEvent interface.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
