### ISSUE TITLE
change max date doesn't changing on the calendar

### ISSUE THREAD

**Issue by lilling** [primefaces/primeng#1599]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/EmreiCb5y6VAKScrthRN?p=preview

**What is the motivation / use case for changing the behavior?**
its obvious

**Please tell us about your environment:**

* **Angular version:** 2.0.X
2.1.0

* **PrimeNG version:** 2.0.X
1.1.0

**Comment by subarroca** [comment]
+1

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
