### ISSUE TITLE
Table: Lazy load virtual scroll: View cannot expand past initial placeholder array length.

### ISSUE THREAD

**Issue by ratchet5980** [primefaces/primeng#15997]
### Describe the bug

Following the demo for virtual scroll, my use case involves loading data of an unknown length into a scrollable table. The amount returned is also unknown due to records being removed for business purposes. When the array splice functions exceed the length of the initial Array.from function, the data past the max limit cannot be reached as it fires a scroll event and resets the position to before the end of the initial length. Ex. I set the array as 200 length, I load in 210 items programatically, I scroll to view item 210 and get reset viewing items 190-200, any attempts viewing 201+ reset the scroll back to 190-200.

### Environment

Stackblitz environment uses the default from the PrimeNg Table Virtual Scroll Lazy Load example. 

Business environment uses angular 17.3.6, PrimeNg 17.16.0.

### Reproducer

https://stackblitz.com/edit/fhhqtq?file=src%2Fapp%2Ftable-virtual-scroll-lazy-demo.ts

### Angular version

17.3.6

### PrimeNG version

17.16.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.9.0

### Browser(s)

Edge, Chrome

### Steps to reproduce the behavior

1. Scroll to bottom of table.
2. Wait for data to load and scroll position to be set
3. Note how many items are next via debug or console log
4. Scroll down to view remaining items
5. Notice where scroll position is set to at the position before scroll attempt was made.

### Expected behavior

Excess data can be viewed without forcing scroll position reset.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
