### ISSUE TITLE
p-inputotp: Autocomplete on Safari browser on Mac osx does not fill in all input fields

### ISSUE THREAD

**Issue by timothyBrake** [primefaces/primeng#16006]
### Describe the bug

When using Safari and having added a otp code to an existing username and password in Safari password manager. When autocompleting the username and password, next autocompleting the OTP only fills in the first input field rather than filling in all digits in all input fields.

### Environment

MacOSX using Safari browser.

### Angular version

17.2.1

### PrimeNG version

17.18.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.11.1

### Browser(s)

Safari

### Steps to reproduce the behavior

1. Add username and password to Safari password manager
2. Add OTP to Safari password manager using the setup key
3. Try autocompleting the OTP
4. Only the first input field is filled in with the entire OTP (6 digits) rather than having the 6digits split and filled in the input fields

To be clear, the value is in first field so when using it, it does have the complete 6 digit number in the [(ngModel)]="exampleValue", it's just not visible in the UI.

### Expected behavior

I expect the entire 6 digits to be filled across the 6 input fields, each containing 1 digit.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
