### ISSUE TITLE
TreeTable: Sorting by multiple columns should show badge value like `Table`

### ISSUE THREAD

**Issue by lzm0** [primefaces/primeng#16008]
### Describe the bug

The `Table` components shows a number representing the sort order in the column header:
https://primeng.org/table#multiple-columns-sort
<img width="1095" alt="image" src="https://github.com/user-attachments/assets/155be88f-601b-4545-beb7-3059455067fd">

However, this is not the behaviour in the `TreeTable` component.
https://primeng.org/treetable#sortmultiplecolumns
<img width="1090" alt="image" src="https://github.com/user-attachments/assets/cd1fdc9d-2f54-4f16-af35-804db15901b1">

It would be nice if the behaviour were consistent.

### Environment

The official documentation example

### Angular version

17.18.4

### PrimeNG version

17.18.4

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

18.20.3

### Steps to reproduce the behavior

1. Go to the documentation section linked above.
2. Sort the tables by multiple columns by holding `Meta`.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
