### ISSUE TITLE
Component: P-input number problem with currency PYG and locale es-PY

### ISSUE THREAD

**Issue by diegomartinez9** [primefaces/primeng#16002]
### Describe the bug

I can't type any amount. It only works with arrows. i tried with anothers currencies and locales and it works. 

### Environment

Angular 17 with primeng version 17.14.1

### Angular version

17.0.0

### PrimeNG version

17.14.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.14.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

Just type

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
