### ISSUE TITLE
p-table: reorder indicator not accurate

### ISSUE THREAD

**Issue by ardakod** [primefaces/primeng#16007]
### Describe the bug

Angular p-table needs way too much dragging to have the right indicator appearing.

[angular.webm](https://github.com/user-attachments/assets/638ea6d3-30fb-48e9-8913-7f63d80bceba)

A good example is primereact where the indicators are guess earlier and requires less dragging.

[react.webm](https://github.com/user-attachments/assets/07eb2c69-789b-42aa-a0ca-b69f296d5337)

### Environment

your main website launched on Chrome 

### Angular version

18.0.0

### PrimeNG version

17.18.4

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.14

### Browser(s)

Chrome

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
