### ISSUE TITLE
p-accordion: svg icon doesn't register click to open or close panels

### ISSUE THREAD

**Issue by ryann3588** [primefaces/primeng#16001]
### Describe the bug

The `<chevrondownicon>` element blocks the click event from being registered against the accordion tabs. This seems to be easily fixed by adding "pointer-events: none" to the .p-accordion-toggle-icon class. This is reproduceable in the prime demo of v16 also https://www.primefaces.org/primeng-v16-lts/accordion. 

### Environment

prime v16

### Angular version

16.2.12

### PrimeNG version

16.9.11-LTS

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.20.2

### Browser(s)

Chrome 126.0.6478.127

### Expected behavior

The svg toggle icon shouldn't block the click event on the accordion tab.

**Comment by charlesfouquet** [comment]
I also confirm this happens with the `<chevronrighticon>` and custom template headers with PrimeNG v17.18.1, only when clicking outside of this icon or the custom headers does it open the accordion

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
