### ISSUE TITLE
Component: p-table: NullInjectorError when passing an ng-template in to a component which wraps a p-table

### ISSUE THREAD

**Issue by sachith94-lion** [primefaces/primeng#16009]
### Describe the bug

I want to create a **standalone** wrapper component using p-table. so this is how my wrapper component implemented which wraps a <p-table> and I use <ng-template> to pass in a header and body template to this wrapper component. This all works fine unless I use 
`pSortableColumn, pSelectableRow , pSortableColumnDisabled`

 , ect.. directives and 

`<p-sortIcon></p-sortIcon> `

. At this point I get a NullInjectorError.

`NullInjectorError: NullInjectorError: No provider for Table!`

```
 <p-table
      #primengTable
      [value]="tableValue()"
      [columns]="colsCalendars"
    >
      <ng-template pTemplate="header" let-columns>
        <ng-container *ngIf="tableHeaderTemplate" [ngTemplateOutlet]="tableHeaderTemplate" [ngTemplateOutletContext]="{ $implicit: columns }"> </ng-container>
      </ng-template>
      <ng-template pTemplate="body" let-rowData let-columns="columns" let-rowIndex="rowIndex">
        <ng-container *ngIf="tableBodyTemplate" [ngTemplateOutlet]="tableBodyTemplate" [ngTemplateOutletContext]="{ $implicit: columns }"> </ng-container>
      </ng-template>
      <ng-template pTemplate="emptymessage">
        <ng-container *ngIf="tableEmptyMessageTemplate" [ngTemplateOutlet]="tableEmptyMessageTemplate"> </ng-container>
      </ng-template>
    </p-table>
```

```
<app-table [tabItems]="tabItems" [colsCalendars]="colsCalendars" [getTableDataCallback]="getCalendar">
    <ng-template appTableHeaderTemplate let-columns>
      <tr>
        <th *ngFor="let col of columns" class="font-medium text-color" [pSortableColumn]="col.field" [style.width]="'30rem'">
          <div class="w-full h-full flex align-items-center justify-content-start">
            <span>{{ col.header }} </span><p-sortIcon class="pl-2" field="{{ col.field }}"></p-sortIcon>
          </div>
        </th>
        <th style="width: 20%"></th>
      </tr>
    </ng-template>
     </app-table>
```

https://github.com/primefaces/primeng/issues/7985
https://github.com/primefaces/primeng/issues/7985#issuecomment-515537861
i saw you guys provided a solution here but seem like this is also not working.  I get 
`Cannot read property 'tableService' of undefined issue.`

Angular version: 17.2.2
PrimeNG version: 17.18.0
Browser: all

Can you please provide me a solution for this?

### Environment

All env

### Angular version

17.2.2

### PrimeNG version

17.18.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v18.20.1

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Comment by playanth95978** [comment]
still not working today, i tried to do the samething and got the same error..
