### ISSUE TITLE
Different behaviour filtering on SelectItems in ListBox and Dropdown

### ISSUE THREAD

**Issue by quartelh** [primefaces/primeng#16003]
I am confused.
The behaviour for Dropdown is different than for ListBox. According to https://github.com/primefaces/primeng/issues/15864 it has nothing to do with the ListBox logic, and one should provide a `filterFields` or `optionLabel` property.

But that is not needed for Dropdown.

See https://stackblitz.com/edit/j5s22b-iaamnd.

For Dropdown it just works and there is no need for `filterFields` or `optionLabel` property for the filter to just work with SelectItem.

_Originally posted by @quartelh in https://github.com/primefaces/primeng/issues/15864#issuecomment-2222488467_

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
