### ISSUE TITLE
overlay: there is no size restrictions for overlays

### ISSUE THREAD

**Issue by LoaderB0T** [primefaces/primeng#16011]
### Describe the bug

Hi there!

Currently when you have a component that utilizes the overlay (eg dropdown or multiselect) the overlay width can grow indefinitely. So far it even overflows the viewport.

Example with dropdown:
![Y0XAXxA - Imgur](https://github.com/user-attachments/assets/99acd15c-7405-4c06-93b7-5908d7ebd277)

I thought about multiple ways of how to fix this behavior in a simple and unified way for all overlays, but feared that all approaches that don't require user configuration, are too opinionated and will not work universally. I will create a PR with a proposed solution soon.

In my proposed solution, the overlay options are extended with `calculateMaxWidth`. A type that accepts a variety of value formats:

      - `true` will set the maximum width to the control's width.
      - `false` will not set a maximum width.
      - A number will set the maximum width to a multiple of the control's width.
      - A number followed by 'px' will set the maximum width to a fixed size in pixels.
      - A number followed by 'vw' will set the maximum width to a percentage of the viewport width.
      Also accepts an array of values. The smallest value will be used.

An example of how it looks with the value 2:
![kUIR627 - Imgur](https://github.com/user-attachments/assets/c5143310-3847-4f3c-952e-a092320a26b4)

As you can see the dropdown is now a bit more manageable. :)

I hope you agree with my solution and I will await PR feedback eagerly.

### Environment

Tested in the latest master version of primeNG in the PrimeNG Playground

### Angular version

18.0.2

### PrimeNG version

master

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.1

**Comment by LoaderB0T** [comment]
@cetincakiroglu 
I understand and respect the decision however I would kindly ask for reconsideration (I will gladly rework the whole thing differently) that allows us to set the max width relative to the control. (Eg max 2x the size of the control). As far as I can tell, this is not possible with the existing solution.

Thanks!

**Comment by cetincakiroglu** [comment]
Hi,

It's possible to make it 2x the size of the control, please check the example :)

https://stackblitz.com/edit/8vedws?file=src%2Fapp%2Fdropdown-basic-demo.html,src%2Fapp%2Fdropdown-basic-demo.ts

**Comment by LoaderB0T** [comment]
@cetincakiroglu  Fair enough although I would still prefer a built-in way. I guess we will create a directive that adds a parameter that somehow attaches to the onOpen and sets the max width then. This way I don't have to do it for all occurrences.

If you ever change your mind, let me know :D
