### ISSUE TITLE
Dynamic Dialog: Prevent scroll to top when child dialog closes in parent dialog

### ISSUE THREAD

**Issue by singhpawank** [primefaces/primeng#16024]
### Describe the bug

I have nested dialogs using primeng dialog service, I set focusOnShow false. When I closes dialog B inside dialog A, dialog A's component scrolled to top and first focusable element receives focus. How to prevent it.

```
private defaultOverlayConfig:DynamicDialogConfig = {
    data:{},
    showHeader:false,
    closable:false,
    height:'100%',
    width:'100%',
    focusOnShow:false,
    focusTrap:false,
    style: { height:'100%', 'max-height':'100%', 'border-radius':'0', 'box-shadow':'none'},
    contentStyle:{height:'100%', padding:'0px', margin:'0px', 'border-radius':'0'},
    maskStyleClass:'overlay-mask-style',
    appendTo:document.getElementById('overlay'),
    transitionOptions: '0ms linear'
   }
```

### Environment

```
"dependencies": {
    "@angular/animations": "^17.3.0",
    "@angular/common": "^17.3.0",
    "@angular/compiler": "^17.3.7",
    "@angular/core": "^17.3.0",
    "@angular/platform-browser": "^17.3.0",
    "@angular/platform-browser-dynamic": "^17.3.0",
    "@ngx-translate/core": "^15.0.0",
    "primeng": "^17.15.0",
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^17.3.6",
    "@angular/cli": "^17.3.6",
    "@angular/compiler-cli": "^17.3.0",
    "typescript": "~5.4.2"
  }
  ```

### Angular version

17.3.0

### PrimeNG version

17.15.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.13.0

### Browser(s)

Version 126.0.6478.127

### Expected behavior

When dialog B closes I want parent  dialog A's scroll position as it was before opening dialog B.

**Comment by singhpawank** [comment]
I added pButton to first button in the component inside dialog A(parent dialog) and this behavior stopped.
```
<p-button pButton class="back-button" icon="pi pi-arrow-left" (onClick)="goBack()"/>
```

**Comment by jonnomk** [comment]
This isn't a fix though.  I don't think the dialog should be trying to automatically give focus to anything on close.  I upgraded to PrimeNG version 17.18.6 from version 15.  It didn't do this previously.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Comment by mathisvester** [comment]
This issue is not solved in current PrimeNG version.

Reproduction URL: https://zzexher7.stackblitz.io

@mertsincan and @singhpawank can you please reopen the issue or should I create a new one?

**Comment by kekude** [comment]
this is issue is still present in current version of primeng 20.2.0
