### ISSUE TITLE
preventDefault is not working in p-tabView

### ISSUE THREAD

**Issue by jaydeepkasture** [primefaces/primeng#16022]
### Describe the bug

Hi guys I want to prevent the tab which I have created using p-tabView from changing I tried to use preventDefault method and stopPropogation method still no result I want to prevent the tab from changing without reloading the component

### Environment

I am using 
 "primeng": "^14.2.3",
 "typescript": "~4.7.2"
 "@angular/cli": "~14.2.7",
    "@angular/compiler-cli": "^14.2.0",

### Angular version

 14.2.12

### PrimeNG version

14.2.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.19.0

### Expected behavior

p-tabView should able to prevent the changing tab process

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
