### ISSUE TITLE
Treetable :Incorrect Column Resizing Behavior in RTL Environment

### ISSUE THREAD

**Issue by murshidAktharV** [primefaces/primeng#16027]
### Describe the bug

When resizing the tree table column in a Right-to-Left (RTL) environment (such as Arabic or Hebrew), the resizing behavior is opposite to the intended direction. Please address this issue to ensure correct column resizing in RTL layouts.
this issue happening in both fit mode and expand mode.

### Environment

Windows

### Reproducer

https://primeng-treetableresize-demo.stackblitz.io/

### Angular version

16.0.3

### PrimeNG version

16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18

### Browser(s)

Chrome

### Steps to reproduce the behavior

1.Change the direction property of table to rtl in slack Bitz example
2.expand first column , then you can see second column is shrinking

### Expected behavior

when expand first column , first column need to expand

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
