### ISSUE TITLE
Table: column-filter outside click does not close when it is inside a dialog component

### ISSUE THREAD

**Issue by ymg2006** [primefaces/primeng#16020]
### Describe the bug

put a table and a column filter inside dialog
click to open filter menu
it will not hide event if you close the modal

### Environment

Windows

### Reproducer

https://stackblitz.com/edit/github-978vwo

### Angular version

17.3.8

### PrimeNG version

17.8.4

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.12.1

### Browser(s)

All

### Steps to reproduce the behavior

put a table and a column filter inside dialog
click to open filter menu
it will not hide event if you close the modal

### Expected behavior

close the modal on outside click

**Comment by mohammed-ezzedine** [comment]
It seems that the issue is back in v18

**Comment by ymg2006** [comment]
> It seems that the issue is back in v18

Many issues that previously were fixed are back in version 18 and 19.
I think it's appropriate to make new issues for them and reference corresponding issue that they realize what's the root of the issue.

**Comment by AsadiAli02** [comment]
have the same problem in version 19

**Comment by JBedworth-cpi** [comment]
And still in v20
