### ISSUE TITLE
CSS media queries for ui-grid fails

### ISSUE THREAD

**Issue by kt215** [primefaces/primeng#1602]
Problem file: primeng.css (grid.css)

Some @media entries do not have units, and when I add units, it works again.

For example:

```
@media (min-width: 480) {
    .ui-grid-fixed {
        width: 480;
    }
}
```
works when changed to
```
@media (min-width: 480px) {
    .ui-grid-fixed {
        width: 480px;
    }
}
```

PrimeNG: 1.1.0
Chrome 54.0.2840.99

**Comment by Mrtcndkn** [comment]
https://github.com/primefaces/primeng/pull/1603 its merged thanks.
