### ISSUE TITLE
p-tieredMenu responsive: We've to tap twice to open the submenu

### ISSUE THREAD

**Issue by UlricW** [primefaces/primeng#16035]
### Describe the bug

In responsive mode (like ipad pro for example), when clicking on a menu that contains submenu, we've to tap 2 times to open the submenu overlay, the first tap focus the menu, and the second one open the overlay

we can reproduce it easily by opening the p-tieredmenu stackblitz (my example is the routing one), we activate the responsive mode from chrome, and select ipad pro as device

### Environment

Windows 11, PrimeNG 17.8.1, angular 17.1.0

### Angular version

17.1.0

### PrimeNG version

17.8.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.2

### Browser(s)

Chrome

### Steps to reproduce the behavior

we can reproduce it easily by opening the p-tieredmenu stackblitz (my example is the routing one), we activate the responsive mode from chrome, and select ipad pro as device

### Expected behavior

The submenu overlay shoud be opened on the first tap

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
