### ISSUE TITLE
p-dropdown Select and Scroll Issues

### ISSUE THREAD

**Issue by emorin** [primefaces/primeng#16037]
We are having 2 big issues with the dropdown component that started with version 16.x.  

In version 15.x, you could expand a dropdown and type a single character and the dropdown would cycle through the options that begin with that letter.

For example,
Rome
Rodeo

If you type r, it should select Rome. Then if you type r again it should jump to the next element which would be Rodeo.

It stopped working like that in version 16.x and now in 17.x. This is common for dropdowns to work like this. You should be able to keep typing the letter and the dropdown will cycle through the options that start with that letter.

The second issue is as follows.
Dropdown has a list of values that has a scroll bar. If you tab into the select and type a letter for a value that is past the view, the option overlay does not scroll down to see the selected value.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
