### ISSUE TITLE
Missing severity type support for 'primary' on tag component on version 17.18.4

### ISSUE THREAD

**Issue by shadowtje1990** [primefaces/primeng#16033]
### Describe the bug

According to the documentation there should be a severity 'primary'. (And if I recall correctly this was something that was supported in previous versions)

<img width="787" alt="Screenshot 2024-07-16 at 01 09 03" src="https://github.com/user-attachments/assets/833eccae-f374-4451-9fa9-19279ebfc3ff">
https://primeng.org/tag#severity

However since the introduction of strict typing on severity, I noticed that the type 'primary' is no longer supported or is missing for the tags. 

<img width="806" alt="Screenshot 2024-07-16 at 01 12 14" src="https://github.com/user-attachments/assets/a9df7317-52f3-425e-9084-e433210ad31f">
https://primeng.org/tag#api.tag.props

Seems to be missing from |https://github.com/primefaces/primeng/blob/e142de683b9cbcf2342774e9390ee09b0934580f/src/app/components/tag/tag.ts#L50

### Environment

Primeng version: 17.18.4
Reference links tags: https://primeng.org/tag#severity
Reference links API tags: https://primeng.org/tag#api.tag.props
Link to tag severity component: |https://github.com/primefaces/primeng/blob/e142de683b9cbcf2342774e9390ee09b0934580f/src/app/components/tag/tag.ts#L50

### Angular version

17.1.3

### PrimeNG version

17.18.4

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.15.0

### Expected behavior

Expected that 'primary' would be 1 of the supporting severities for tags.

**Comment by LightBulbIdea** [comment]
@shadowtje1990 By not passing a value for the "severity" property the button will default to Primary, I don't think a "primary" value is needed. Otherwise, what would be the different between Primary and Undefined?

**Comment by shadowtje1990** [comment]
I could agree with that statement. However, this suggests there is a misalignment between the use of the severity property in the tags component and how it is utilized in other components ( messages, badges, and buttons ) There you can explicit say you want to use 'primary' as severity.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
