### ISSUE TITLE
p-calendar p-multiselect: Click opens wrong menu

### ISSUE THREAD

**Issue by Emiliorth** [primefaces/primeng#16038]
### Describe the bug

Having such form:
```
<row>
<col-12>p-multiselect</col-12>
<col-sm-6 col-12>p-calendar with time</col-sm-6 col-12><col-sm-6 col-12>p-calendar with time</col-sm-6 col-12>
</row>
```
(above is a shorthand)
then enabling mobile view in DevTools, shrinking view to below sm (causing form to have 3 rows), selecting value in first p-calendar, then disabling mobile view (causing form to have 2 rows with 1 and 2 column) and finally clicking on multiselect, causes first p-calendar to open

### Environment

Angular + PrimeNG

### Angular version

18.0.3

### PrimeNG version

17.18.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22.2.0

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
