### ISSUE TITLE
PrimeNG Not Building with latest Master - missing search-insights

### ISSUE THREAD

**Issue by awdorrin** [primefaces/primeng#16031]
### Describe the bug

ng build of current pull from git results in:

```
Application bundle generation failed. [33.787 seconds]

✘ [ERROR] TS2307: Cannot find module 'search-insights' or its corresponding type declarations. [plugin angular-compiler]

    node_modules/@algolia/autocomplete-plugin-algolia-insights/dist/esm/types/InsightsClient.d.ts:1:74:
      1 │ ...hodMap, InsightsClient as _InsightsClient } from 'search-insights';
        ╵                                                     ~~~~~~~~~~~~~~~~~


✘ [ERROR] TS2307: Cannot find module 'search-insights' or its corresponding type declarations. [plugin angular-compiler]

    node_modules/@algolia/autocomplete-plugin-algolia-insights/dist/esm/types/InsightsClient.d.ts:2:211:
      2 │ ...TokenChange as InsightsOnUserTokenChange, } from 'search-insights';
```

### Environment

Windows 11 build environment

### Angular version

18.0.2

### PrimeNG version

17.18.4

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.20.3

### Steps to reproduce the behavior

git clone of master
npm install
ng serve

**Comment by awdorrin** [comment]
I found you have to install search-insights manually:
`npm install search-insights`

**Comment by JimmyBarrientos** [comment]
Can confirm that @awdorrin 's solution works. Not sure why it isnt included in the latest.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
