### ISSUE TITLE
P-Chart: Chart Width & Height not working with 17.18.4

### ISSUE THREAD

**Issue by gopikrishna-manifest** [primefaces/primeng#16048]
### Describe the bug

When we set Width and Height parameters, the chart is not scaling based on the height. It works good in 17.18.3 version.
![Screenshot_4](https://github.com/user-attachments/assets/bd1965ad-9496-4124-8fc2-6c31f8dc8975)

### Environment

not relevant

### Angular version

17.3.1

### PrimeNG version

17.18.4

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.6.0

### Browser(s)

Chrome 126.0.6478.127

### Expected behavior

It should scaled with the given height

**Comment by lothern** [comment]
Why was this issue closed?

I'm seeing the same behavior in 17.8.7.

**Comment by gopikrishna-manifest** [comment]
@lothern I closed this as it works after I given the unit for width and height like below

` <p-chart type="line" [data]="data" [options]="options" [width]="'200px'" [height]="'200px'"></p-chart>`
