### ISSUE TITLE
p-dropdown with editable=true and floating labels doesn't work with manually entered values

### ISSUE THREAD

**Issue by HeikeDuennebacke** [primefaces/primeng#16049]
### Describe the bug

When adding the [editable]="true" property to the component **and** using float labels, it is not possible to type a value manually.

Reproduction on stackblitz: [https://stackblitz.com/edit/ybzyi4?file=src%2Fapp%2Fdropdown-editable-demo.ts](stackblitz)

### Environment

@angular-devkit/architect       0.1800.5
@angular-devkit/build-angular   18.0.5
@angular-devkit/core            18.0.5
@angular-devkit/schematics      18.0.5
@angular/cli                    18.0.5
@schematics/angular             18.0.5
rxjs                            7.8.1
typescript                      5.4.5
primeng                         17.18.4
zone.js                         0.14.7

### Angular version

18.0.5

### PrimeNG version

17.18.4

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.0

### Browser(s)

Firefox, Chrome (current versions)

### Steps to reproduce the behavior

Clicking into the dropdown field -> typing manually is impossible.

### Expected behavior

<p-dropdown> with [editable]="true"  in combination with <p-float-label> should behave the same when manually typing a value as when selecting a value from the drop down list.

**Comment by v-jovan** [comment]
I have the same problem.
I saw that it was fixed here #10170 but somehow it's still present.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
