### ISSUE TITLE
Menubar: Positioning of sub-menus goes off screen

### ISSUE THREAD

**Issue by jparrish-lumatrak** [primefaces/primeng#16046]
### Describe the bug

When a menu has subitems on a node to the far-right of the page, the subitems do not slide out to the left. Instead, they continue to slide out to the right and get cutoff.

### Environment

Chromium

### Reproducer

https://stackblitz.com/edit/y7hoqx?file=src%2Findex.html

### Angular version

18.0.1

### PrimeNG version

17.18.4

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

0

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
