### ISSUE TITLE
MultiSelect and Listbox filterby is not working

### ISSUE THREAD

**Issue by ymg2006** [primefaces/primeng#16052]
### Describe the bug

MultiSelect and Listbox filterby is not working

### Environment

17.18.4

### Angular version

17.3.11

### PrimeNG version

17.18.4

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.12.1

### Browser(s)

All

**Comment by mertsincan** [comment]
This issue does not fit our format. Without any test cases, it is very difficult to see in which cases it does not work. Please provide more details.
