### ISSUE TITLE
Component: Table, when I try add a custom icon doesn't work

### ISSUE THREAD

**Issue by jadir-junior** [primefaces/primeng#16068]
### Describe the bug

This is my html and I have notice, when I put one ng-template within another, doesn't works 

```
<ng-template pTemplate="header">
    <tr>
      <th style="width: 4rem">
        <p-tableHeaderCheckbox></p-tableHeaderCheckbox>
      </th>
      <th pSortableColumn="name" style="width: 20%">
        <div class="flex items-center">
          <span>Nome</span>
          <!-- <i class="material-icons-outlined p-sortable-column-icon">sort</i> -->
          <ng-template
            pTemplate="sorticon"
            field="name"
            let-sortOrder="sortOrder"
          >
            <div *ngIf="sortOrder === 0">
              <!-- Nenhuma ordenação -->
              <i class="material-icons-outlined p-sortable-column-icon">sort</i>
            </div>
            <div *ngIf="sortOrder === 1">
              <!-- Ordenação ascendente -->
              <i class="material-icons-outlined p-sortable-column-icon"
                >arrow_upward</i
              >
            </div>
            <div *ngIf="sortOrder === -1">
              <!-- Ordenação descendente -->
              <i class="material-icons-outlined p-sortable-column-icon"
                >arrow_downward</i
              >
            </div>
          </ng-template>
        </div>
      </th>
      <th>Status</th>
      <th>Perfil</th>
      <th>E-mail</th>
      <th>Alterado em</th>
      <th>Ações</th>
    </tr>
  </ng-template>
```

I notice within ngAfterContentInit, it aren't in that.

![error-2](https://github.com/user-attachments/assets/4a7edb8b-7d8c-448f-a518-789370e2825c)
![errro-1](https://github.com/user-attachments/assets/7b6b8d0e-5249-4870-97c3-eff2fea0e1b0)

if I move it to the top of the pTemplete header it appears

### Environment

Windows 11

### Angular version

18.0.0

### PrimeNG version

17.18.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.14.0

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
