### ISSUE TITLE
tabmenu: automationId not working

### ISSUE THREAD

**Issue by parked-toes** [primefaces/primeng#16075]
### Describe the bug

menuItem.automationId does not work for p-tabMenu. No data-* attribute is rendered.

### Environment

OS: Ubuntu

### Angular version

17

### PrimeNG version

17.18.14

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
