### ISSUE TITLE
Schedule css working

### ISSUE THREAD

**Issue by mbeckenbach** [primefaces/primeng#1607]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
```

**Current behavior**
Full calendar component does not apply theme styles. Im using an angular cli project. 

This is in my styles.css:
```
/* You can add global styles to this file, and also import other style files */
@import url('../node_modules/primeng/resources/themes/omega/theme.css');
@import url('../node_modules/primeng/resources/primeng.min.css');
@import url('../node_modules/font-awesome/css/font-awesome.min.css');
@import url("../node_modules/fullcalendar/dist/fullcalendar.css");
@import url("../node_modules/fullcalendar/dist/fullcalendar.print.css");
```

I have added the same configuration as in the docs example, so there should be bottons at the top.(http://www.primefaces.org/primeng/#/schedule)

As you can see in my screenshot there are no buttons. But the chrome dev tools show that there are some buttons in the rendered html.

![image](https://cloud.githubusercontent.com/assets/6654388/21275235/0da98ff0-c3cc-11e6-9822-742cbee44202.png)

**Please tell us about your environment:**
Win10, Angular CLI 1.0.0-beta.22-1

* **Angular version:** 2.0.X
2.2.3

* **PrimeNG version:** 2.0.X
"fullcalendar": "^2.7.2", (As on the docs page)
"jquery": "^3.1.1",
"primeng": "^1.1.0",

* **Browser:** All
 
* **Language:** Typescript

**Comment by Mrtcndkn** [comment]
Could you please provide a plunkr?

http://plnkr.co/edit/NtWWnN

**Comment by ramonsan** [comment]
Seems fullcalendar.print.css overwrite styles to b/n suitable for printer mode. Delete that line and you will have correct styles.
