### ISSUE TITLE
ButtonDirective changing severity does not update styles

### ISSUE THREAD

**Issue by danemesis** [primefaces/primeng#16074]
### Describe the bug
Changing severity input for Directive does not change button styles.

https://github.com/primefaces/primeng/blob/98f96823b0e82dd60a432e11090cb9b611b01ecc/src/app/components/button/button.ts#L112

### Environment
126.0.6478.183 (Official Build) (arm64), macos

### Angular version
18

### PrimeNG version
17.18.1

### Build / Runtime
Angular CLI App

### Language
TypeScript

### Node version (for AoT issues node --version)
v20.15.1

### Browser(s)
Chrome

###  Steps to reproduce the behavior
change directive's severity and see that styles are not changing.

### Expected behavior
Styles change once button's severity is updated

## Reproduced
https://stackblitz.com/edit/stackblitz-starters-8skcaw?file=src%2Fmain.ts

**Comment by danemesis** [comment]
I imagine if to update as `label` or other settable Input's it should work

https://github.com/primefaces/primeng/blob/98f96823b0e82dd60a432e11090cb9b611b01ecc/src/app/components/button/button.ts#L72

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
