### ISSUE TITLE
.p-organizationchartL 3 rules skipped due to selector errors

### ISSUE THREAD

**Issue by docentYT** [primefaces/primeng#16073]
### Describe the bug

I do not use organization chart in my website. Error displayed by angular during and after build:
```
3 rules skipped due to selector errors:
  .p-organizationchart .p-organizationchart-lines :nth-child(1 of.p-organizationchart-line-left) -> n-th rule couldn't be parsed ('1 of.p-organizationchart-line-left')
  .p-organizationchart .p-organizationchart-lines :nth-last-child(1 of.p-organizationchart-line-left) -> n-th rule couldn't be parsed ('1 of.p-organizationchart-line-left')
  .p-organizationchart .p-organizationchart-lines :nth-child(1 of.p-organizationchart-line-right) -> n-th rule couldn't be parsed ('1 of.p-organizationchart-line-right')
```

### Environment

Angular: 18.1.1
PrimeNG: 17.8.5

### Angular version

18.1.1

### PrimeNG version

17.8.5

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.12.1

**Comment by Hassan-Gaad** [comment]
I encounter the same issue once enable bundle optimization ! any update here?

**Comment by sugihartolim** [comment]
Confirmed still happening with primeng 17.8.6 and angular 18.

**Comment by devwagner** [comment]
The issue is still happening. 
PrimeNG 17.18.9 
Angular 18.2.2

**Comment by nagringapp** [comment]
same here 
"primeng": "^17.18.10",
"@angular/cdk": "^18.2.3",
"@angular/common": "^18.0.0",

**Comment by erickfigueiredo** [comment]
Same here

"primeng": "^17.18.11",
"@angular/core": "^18.2.0",

**Comment by instantgis** [comment]
Same here too

    "@angular/core": "^18.0.0",
    "primeng": "^17.18.10",

Tried downgrading to primeng 17.18.10 as mentioned above, still no go.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
