### ISSUE TITLE
Table> double call to (onLazyLoad) event after #15996

### ISSUE THREAD

**Issue by ymg2006** [primefaces/primeng#16070]
### Describe the bug

When lazy is true on the table sorting causes double call to (onLazyLoad) event after commit: Fixed #15550 - Table | Custom sort in table not working #15996.
<img width="1270" alt="Screenshot 2024-07-21 093654" src="https://github.com/user-attachments/assets/3ff15b96-90d8-49da-8728-85df9e14f414">

### Environment

Windows 11

### Angular version

17.3.6

### PrimeNG version

17.18.5

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.12.1

### Browser(s)

All

### Steps to reproduce the behavior

<p-table #dataTable
                         (onLazyLoad)="getUsers($event)"
                         [value]="users"
                         [rows]="100"
                         [lazy]="true"

### Expected behavior

one call to onLazyLoad.

**Comment by sparmar-agilic** [comment]
Is this issue fixed?
