### ISSUE TITLE
Showcase: does not persist theme config on reload or navigation

### ISSUE THREAD

**Issue by jjs98** [primefaces/primeng#16071]
### Describe the bug

When I configure darkmode or a special theme on primeng.org and then
- reload the page
- search for a component
- click on a reference link to another component
the theme is resetted.

### Environment

-

### Angular version

-

### PrimeNG version

17.18.5

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

-

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
