### ISSUE TITLE
RTL support for datatable component

### ISSUE THREAD

**Issue by MehdiSaeedifar** [primefaces/primeng#1608]
Please support right-to-left languages such as Arabic or Farsi for datatable component.

**Comment by nimanzd** [comment]
Is there any plan for supporting right to left languages?

**Comment by yuvalbl** [comment]
Hey guys, 
Any news regarding table RTL support?
It would be wonderful indeed  if you'll add it :)

**Comment by cagataycivici** [comment]
Will do for 4.1.1, we've just started RTL enhancements;

https://www.primefaces.org/primeng/#/rtl

**Comment by ismcagdas** [comment]
Hi @cagataycivici , is this in your short term plan ?

We are using PrimeNg and it is great. The only problem we had with datatable and rtl is, when datatable is scrollable, scrollbar does not scroll table's header. If you are not going to work on this in a short time, can you offer a workaround for this problem ?

Thanks for your great effort.

**Comment by Rchoudhary-tcs** [comment]
same issue as with @ismcagdas ,please give your feedback on this post @cagataycivici

**Comment by tigrenok00** [comment]
Same issue with the scroll in RTL, please help @cagataycivici

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.

**Comment by ismcagdas** [comment]
@cagataycivici p-table has the same issue.

**Comment by anuradhamudalige** [comment]
Fixed this using ngAfterViewInit,
const elements = this.elem.nativeElement.querySelectorAll('.ui-datatable-scrollable-body');
    let initValue = 0;
    const headerBox = this.elem.nativeElement.querySelectorAll('.ui-datatable-scrollable-header-box');
    const table = headerBox[0].children[0] as any;
    elements[0].addEventListener('scroll', () => {
      if (headerBox && headerBox[0].style && this.isLanguageChanged) {
          const marginLeft = parseInt(headerBox[0].style.marginLeft, 10);
          headerBox[0].style.marginRight = '0px';
          if (!this.scrolled) {
            this.scrolled = true;
            initValue = marginLeft;
          }
          table.style.marginRight = (initValue - marginLeft) + 'px';
      }
    });

**Comment by patolam** [comment]
for those who struggle with the same problem using p-table:
`
    const body: HTMLElement = table.el.nativeElement.querySelector('.ui-table-scrollable-body');
    const header: HTMLElement = table.el.nativeElement.querySelector('.ui-table-scrollable-header');
    body.addEventListener('scroll', () => {
      header.scrollLeft = body.scrollLeft;
    });
`
