### ISSUE TITLE
p-megaMenu: Menu opens automatically on mouse hover

### ISSUE THREAD

**Issue by VF9999** [primefaces/primeng#16081]
### Describe the bug

When hovering the mouse over a p-megaMenu component, the menu opens automatically. All mouse hover settings in Windows have been turned off and all menus and links open when clicked except p-megaMenu, which opens on mouse hover.

### Environment

Windows. Angular development.

### Angular version

17.2.3

### PrimeNG version

17.10.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.20.4

### Browser(s)

Chrome 126.0.6478.183, FireFox 128.0

### Steps to reproduce the behavior

1. Hover mouse over p-megaMenu component and the menu opens without clicking it.

### Expected behavior

When clicking the p-megaMenu, it should then open.

**Comment by rosenthalj** [comment]
See the following closed Issue #14086:  MegaMenu & MenuBar | Activate root item on hover

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
