### ISSUE TITLE
Accordion: Case-sensitive tag name causes CSS issues

### ISSUE THREAD

**Issue by gregorwinkler** [primefaces/primeng#16090]
### Describe the bug

To use the accordion and its tabs, we have to use `p-accordionTab` in our code.
When the app is then built, the tag name changes to `p-accordiontab`.

This is generally not a problem, as element tags are case-insensitive in CSS.

However, we have the problem that we purge our CSS to reduce the file size. As the base-theme refers to `p-accordiontab` and thus our overwrites as well, while in the template files there is only `p-accordionTab`, all styles are purged, as PurgeCSS is case-sensitive.

If there is no problem about it, I think it makes most sense to just have the same spelling for the accordion tab element tag and not to have a different one in the build version.

### Environment

All

### Angular version

17.1.3

### PrimeNG version

17.17.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v21.7.1

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
