### ISSUE TITLE
this.multiSortMeta undefined in if branch

### ISSUE THREAD

**Issue by jtragg** [primefaces/primeng#1609]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
this.multiSortMeta has the potential to be undefined when reaching if branch on line 641
https://github.com/primefaces/primeng/blob/master/components/datatable/datatable.ts#L638-L643
```
if(this.stopSortPropagation) {
    this.stopSortPropagation = false;
}
else if(!this.lazy && (this.sortField||this.multiSortMeta)) {
    if(this.sortMode == 'single')
        this.sortSingle();
    else if(this.sortMode == 'multiple')
        this.sortMultiple();
}
```

**Expected behavior**
Should probably look more like this:

```
if (this.stopSortPropagation) {
  this.stopSortPropagation = false;
} else if (!this.lazy && (this.sortField||this.multiSortMeta)) {
    if (this.sortMode == 'single' && this.sortField) {
      this.sortSingle();
    } else if (this.sortMode == 'multiple' && this.multiSortMeta) {
      this.sortMultiple();
    }
}
```
This is not an actual fix, just a way to explain the issue. Because the first else if is checking for `this.sortField||this.multiSortMeta`, there is a possibility that `this.multiSortMeta` is undefined when it reaches the call to that function.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

It's unclear that you're supposed to set one property with the other, when you don't the error message isn't helpful. 
**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [**all** | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [**all** | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
