### ISSUE TITLE
Remove Chips Component

### ISSUE THREAD

**Issue by cetincakiroglu** [primefaces/primeng#16091]
Chips component will be removed in v18. 

Use autocomplete with `typeahead` feature instead.

**Comment by cetincakiroglu** [comment]
Fixed in v18.0.0-beta.1

**Comment by PierreB40** [comment]
I don't understand how autocomplete with typeahead can replace p-chips, it lacks many parameters.
For example, : `allowDuplicate`, `separator`, `max`, `addOnTab`, `addOnBlur`, ...

And in my opinion, naming is misleading: p-autocomplete without typeahead is no longer an autocomplete.

I use p-chips to copy comma-separated e-mail addresses `john.doe@gmail.com,jane.doe@gmail.com` with a limit of 10 addresses and prohibit duplicate values.
With v18 autocomplete multiple without typeahead doesn't allow me to have the same behavior. 

Autocomplete without typeahead is much less flexible.

**Comment by vetemi** [comment]
@cetincakiroglu Can you elaborate on what you mean with typeahead feature? I don't exactly understand how to use it

**Comment by mcrtricolor** [comment]
We need Chips back, this autocomplete is nowhere near enough.

Please let us have it back.
