### ISSUE TITLE
Password: Tooltip with `tooltipEvent='focus'` is never displayed

### ISSUE THREAD

**Issue by igor-leshkevych** [primefaces/primeng#16106]
### Describe the bug

When adding a tooltip to a `Password` component and setting `tooltipEvent` to `focus`, the tooltip never shows. 
I also tested the following combinations:
1. Normal `<input>` and `tooltipEvent=focus`: works fine
2. `Password` and `tooltipEvent=hover`: works fine

So the issue seems to be specific to the combination of `Password` and `tooltipEvent=focus`.

### Environment

The original environment I used:
- Node v22.3.0
- Angular 18.1.1
- PrimeNG 17.18.6

But I also reproduced the issue on a StackBlitz from your website (in [this](https://primeng.org/tooltip#event) section). There, the environment is:
- Angular 18.0.1
- PrimeNG 17.18.6

### Reproducer

https://stackblitz.com/edit/github-jj5ibr?file=src%2Fapp%2Fapp.component.html

### Angular version

18.0.1

### PrimeNG version

17.18.6

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22.3.0

### Steps to reproduce the behavior

1. Open the page with a password element, configured with a tooltip.
2. Focus on the password element.

### Expected behavior

Expected result: The tooltip is displayed.

Actual result: no tooltip is displayed.

**Comment by filiptrivan** [comment]
Any update? In v19 still not working?

Reproducer:
https://stackblitz.com/edit/angular-primeng-18-sandbox-8ebsm2eg?file=src%2Fapp%2Fapp.component.ts

**Comment by OmkarJ13** [comment]
this is still not working in v20
