### ISSUE TITLE
Input: Error State on ng-touched

### ISSUE THREAD

**Issue by B34v0n** [primefaces/primeng#16118]
### Describe the bug

The error state for Input-Fields is only added, if the field is marked as `ng-dirty` and `ng-invalid`. 

If I want to validate an input-field on being empty, it is not shown as invalid.

The invalid state should be set, if the field has the classes `ng-invalid` and `ng-touched`.
With that change, the field can be validated even if I only tab through the form.

### Environment

All Environments, like Chrome, Firefox etc.

### Reproducer

https://stackblitz.com/edit/github-4p7qmt?file=src%2Fapp%2Fapp.component.html

### Angular version

17.3.12

### PrimeNG version

17.18.6

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.16.0

### Steps to reproduce the behavior

1. Open the stackblitz: https://stackblitz.com/edit/github-4p7qmt?file=src%2Fapp%2Fapp.component.html
2. Tab through the two inputs - no red error-border
3. Insert a character and delete it again - red error-border visible

### Expected behavior

The red error-border should be visible, even if I don't insert something and delete it again afterwards.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
