### ISSUE TITLE
Editor: the style of the toolbar is missing up when custom modules used

### ISSUE THREAD

**Issue by its-dibo** [primefaces/primeng#16114]
### Describe the bug

when adding custom modules using `[modules] = "modules"` the editor's style is damged

[see this demo](https://primeng-editor-demo-z8agrd.stackblitz.io)

[code](https://stackblitz.com/edit/primeng-editor-demo-z8agrd?file=src%2Fapp%2Fapp.component.html)

### Reproducer

https://stackblitz.com/edit/primeng-editor-demo-z8agrd?file=src%2Fapp%2Fapp.component.html

### Angular version

18

### PrimeNG version

17.18.6

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20

### Browser(s)

chrome

**Comment by renanvieiraa** [comment]
You can hide this by inserting an empty pTemplate header into the p-editor tag to trigger the ‘template element’ and hide the PrimeNG toolbar.

I've fixed this in https://github.com/primefaces/primeng/pull/16357

```
<p-editor
  [style]="{ height: '320px' }"
  [modules]="modulesInEditor"
>
  <ng-template pTemplate="header"> </ng-template>
</p-editor>
```
