### ISSUE TITLE
Dropdown: onBlur event is emitted when the user clicks the dropdown arrow

### ISSUE THREAD

**Issue by puschie286** [primefaces/primeng#16115]
### Describe the bug

follow up: https://github.com/primefaces/primeng/issues/15800

still happens when filter is enabled

### Environment

....

### Reproducer

https://stackblitz.com/edit/hhqsns-mce5qf?file=src%2Fapp%2Fdropdown-basic-demo.html

### Angular version

...

### PrimeNG version

17.18.6

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

...

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
