### ISSUE TITLE
Component: SplitButton

### ISSUE THREAD

**Issue by Hvdvyve** [primefaces/primeng#16111]
### Describe the bug

When the 'OnClick' part of the SplitBotton has the the 'onDropdownButtonClick' functionality put in it. That part does nothing. I do not know if this is a bug or intended functionality? It used to work in older versions.

### Environment

I used the PrimeNG Issue Template that was provided on stackblitz.com.

### Reproducer

https://stackblitz.com/edit/github-wc9bvd?file=src%2Fapp%2Fapp.component.html

### Angular version

17.0.0

### PrimeNG version

17.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.9.0

### Steps to reproduce the behavior

1. Go to the stackblitz environment provided.
2. Click on the 'list' button.
3. Nothing happens, that's the bug.

### Expected behavior

A drop-down should be shown, just like when you click on the arrow button.

**Comment by kyjus25** [comment]
https://github.com/primefaces/primeng/pull/14395 proposed a fix which was closed.
