### ISSUE TITLE
p-autoComplete: Unable to type spaces in editable dropdowns

### ISSUE THREAD

**Issue by kanixxx833** [primefaces/primeng#16113]
unable to key in space on autocomplete also unable to key in numbers

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
