### ISSUE TITLE
<p-multiselect>: Dropdown scroll jumping backwards

### ISSUE THREAD

**Issue by Ritik2411** [primefaces/primeng#16128]
### Describe the bug

Dropdown scroll is jumping backwards when i add [virtualScroll]="true". When I remove this property i works fine but after adding it scroll is not working properly.

### Environment

Currently working in testing enviroment.

### Angular version

17.3.5

### PrimeNG version

17.14.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.15.0

### Browser(s)

Chrome

### Expected behavior

Scroll should work properly.

**Comment by MatthewBrenner1** [comment]
I am having the same issue.

It's also broken on the primeng website.
[multiselect](https://primeng.org/multiselect)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
