### ISSUE TITLE
tabmenu: emits change event twice when an item is clicked

### ISSUE THREAD

**Issue by noureddine-taleb** [primefaces/primeng#16123]
### Describe the bug

in tabmenu when you click item it emits change event twice

### Environment

prod

### Angular version

17.2.0

### PrimeNG version

17.3.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v18.19.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

click on tabmenu item and in the parent listen for tabChanged event.

### Expected behavior

the tabChanged event should emit once

**Comment by cetincakiroglu** [comment]
fixed in https://github.com/primefaces/primeng/pull/16122
