### ISSUE TITLE
Tree: textArea in Template mode does not respond to a space key

### ISSUE THREAD

**Issue by zbychpo** [primefaces/primeng#16121]
### Describe the bug

Tree: textArea in Template mode does not respond to a space key

### Environment

Reproduced in all browsers.

### Reproducer

https://stackblitz.com/edit/github-nqgnwm-uj3o1a

### Angular version

17.3.11

### PrimeNG version

17.18.6

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.x.

### Browser(s)

Firefox

### Steps to reproduce the behavior

1.     Go to Tree -> Template OR go to the attached stackblitz environment.
2.     Click on the toggle button, and input box(textArea) appears.
3.     Try inputting a space to the input field.
4.     Space is not getting inserted into the input field.

### Expected behavior

I should be able to insert a space to the textarea field.

**Comment by zbychpo** [comment]
Probably the same error occurs if I use the Editor(quill) component

**Comment by zbychpo** [comment]
Ok, it works, thank you

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
