### ISSUE TITLE
pDropdown: not working properly inside pOverlayPanel

### ISSUE THREAD

**Issue by ahaller-billtrust** [primefaces/primeng#16124]
### Describe the bug

When opening a dropdown inside an overlay panel and selecting a value from the dropdown, the overlay panel unexpectedly closes.

**Note:** This only happens when setting the `appendTo="body"` property for the dropdown.

**Steps to Reproduce**
1. Open the demo: https://stackblitz.com/edit/k9fw6g?file=src%2Fapp%2Fdropdown-basic-demo.html
2. Open the overlay panel.
3. Inside the overlay panel, locate and open the dropdown menu.
4. Select any value from the dropdown menu.

**Expected Behavior**
The overlay panel should remain open after selecting a value from the dropdown.

**Actual Behavior**
The overlay panel closes immediately after selecting a value from the dropdown.

### Environment

Browser: Chrome
OS: Windows 10

### Reproducer

https://stackblitz.com/edit/k9fw6g?file=src%2Fapp%2Fdropdown-basic-demo.html

### Angular version

18.0.1

### PrimeNG version

17.18.6

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.20.4

### Browser(s)

Chrome 127

### Steps to reproduce the behavior

1. Open the demo: https://stackblitz.com/edit/k9fw6g?file=src%2Fapp%2Fdropdown-basic-demo.html
2. Open the overlay panel.
3. Inside the overlay panel, locate and open the dropdown menu.
4. Select any value from the dropdown menu.

### Expected behavior

The overlay panel should remain open after selecting a value from the dropdown.

**Comment by mehmetcetin01140** [comment]
Hi, 

I’ve provided a StackBlitz example for you. You can achieve the expected behavior using the method shown in the example.

Example: https://stackblitz.com/edit/k9fw6g-wuune9?file=src%2Fapp%2Fdropdown-basic-demo.html

**Comment by ahaller-billtrust** [comment]
thank you for the workaround @mehmetcetin01140 !

**Comment by ahaller-billtrust** [comment]
the issue still happens (even with @mehmetcetin01140 workaround).

https://github.com/user-attachments/assets/2d5a4780-5533-4409-ab9c-6670d9187727

**Comment by ahaller-billtrust** [comment]
any updates?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
