### ISSUE TITLE
Table: Broken link in documentation

### ISSUE THREAD

**Issue by naris** [primefaces/primeng#16135]
### Describe the bug

The table pagination documentation here: https://primeng.org/table#paginator instructions has a broken link for server side pagination that returns a 404 error:
"Pagination is enabled by setting paginator property to true and defining a rows property to specify the number of rows per page. For server side pagination, see the [lazy loading](https://primeng.org/table%23lazy) example."

### Environment

windows edge browser

### Angular version

n/a

### PrimeNG version

17.18.6

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

n/a

### Browser(s)

Edge, Chrome, any other browser

### Steps to reproduce the behavior

1. go to https://primeng.org/table#paginator
2. click the broken link https://primeng.org/table%23lazy

### Expected behavior

The broken link should go to an existing page showing how to perform server-side pagination

**Comment by SoyDiego** [comment]
Please, edit the title of your issue in this way: `Name Of Component: Your problem`

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
