### ISSUE TITLE
Dropdown: Search is not working in dropdown with group option as true (dropdown with group option)

### ISSUE THREAD

**Issue by gsr414** [primefaces/primeng#16131]
### Describe the bug

I am using primeng 11.4.10, I am using dropdown with group option as true, whenever If I enter first character of first option in first group in keyboard (Ex: B in Berlin is first option in first group) , option is not getting selected, but it is working for second option. after selecting second option If I search again with first character of first option then it is working.

### Environment

Development

### Angular version

12

### PrimeNG version

11.4

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14

### Browser(s)

chrome

### Steps to reproduce the behavior

1. Go to Dropdown with Group option
2. open the dropdown
3. Enter first character of first group options in keyboard (ex: B in Berlin)

![image](https://github.com/user-attachments/assets/418d20de-3b93-4489-9acb-33d0c9e43750)

### Expected behavior

The expected Behavior is, it should select first group first option in dropdown

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
