### ISSUE TITLE
AutoComplete | [object Object] displayed when 'field' value is null

### ISSUE THREAD

**Issue by apraul** [primefaces/primeng#16141]
### Describe the bug

When the value of the property `field="nom"` is null - the autocomplete displays [object Object] in the input field.

The object passed on ngModel is:
 `personnePhysique.paysDeces = { 
    id: null; 
    nom: null; 
}`

This issue is not singular on our app, so we have other autocompletes with the same issue. 
I've seen that if the object is null (ex:  `personnePhysique.paysDeces = null`) and not the property, it works alright.

### Environment

Recently we've upgraded our frontend app from angular 14 to angular 18 and this is one of issues that we've encountered.

I provide some screenshots with the in-app display, usage of autoComplete component in template & the value provided from http request that fills the autocomplete.

![image](https://github.com/user-attachments/assets/4c251b18-016a-4cfc-82ad-b91b913ac6e7)
![image](https://github.com/user-attachments/assets/610c921f-514e-44a7-a370-a2d41e9973e0)
![image](https://github.com/user-attachments/assets/f804857d-226c-4515-984d-f4aed2be3f06)

### Angular version

18.1.0

### PrimeNG version

17.18.6

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22.4.0

### Expected behavior

The input should be empty if the value is null.

**Comment by apraul** [comment]
I think this PR will solve the issue: https://github.com/primefaces/primeng/pull/16231

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
