### ISSUE TITLE
Panel: Aria-IDs are duplicated

### ISSUE THREAD

**Issue by msg-jstren** [primefaces/primeng#16143]
### Describe the bug

Lighthouse detects the following accessability issue:
![image](https://github.com/user-attachments/assets/1b389d21-1253-48a9-a849-4e4103fb5892)

The toggle icon and the panel title have the same ID, thats why the accessability issue is detected.

### Environment

This Lighthouse report is from the PrimeNG page itself: https://primeng.org/panel

It was first detected from us in our own implementation:
Browser: Chrome (Update 127)
Angular version: 17.2.3
PrimeNG version: 17.18.1

### Reproducer

https://primeng.org/panel

### Angular version

17.2.3

### PrimeNG version

17.18.6

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.9.0

### Browser(s)

Chrome

### Expected behavior

There should be no accessability issues.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
