### ISSUE TITLE
Table: Elements under frozen columns visible on hover or select on Aura Dark theme.

### ISSUE THREAD

**Issue by adri95cadiz** [primefaces/primeng#16149]
### Describe the bug

The elements under frozen columns become visible on Aura Dark Theme, this is apparently because the theme is using backgrounds with low opacity on hovered and highlighted rows.

![image](https://github.com/user-attachments/assets/444ad3a6-802f-461f-942e-4bfee1d6ec3b)

### Environment

This an Angular enterprise application with the latest Angular and PrimeNG versions.

### Reproducer

https://stackblitz.com/edit/ggqmvq?file=src%2Fapp%2Ftable-frozen-columns-demo.html

### Angular version

18.1.2

### PrimeNG version

17.18.6

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.14.1

### Steps to reproduce the behavior

1. Create an Angular application with PrimeNG using theme aura dark.
2. Create a table component with frozen columns and selection mode multiple or single.
3. Scroll the table so the other columns are under the frozen columns.
4. Hover or select any row or rows.
5. Observe how the columns under the frozen column become visible when the row becomes hovered or selected.

### Expected behavior

The items under the frozen column shouldn't be visible under any circunstance.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
