### ISSUE TITLE
Table Pagination Bug With Signals

### ISSUE THREAD

**Issue by tolgatopkara** [primefaces/primeng#16146]
### Describe the bug

page count not updating when adding signal data into table

### Environment

Angular 17,prima 17, 

### Angular version

17.3.10 

### PrimeNG version

17.7.0 

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.9.0

### Steps to reproduce the behavior

When i use default row=5, and add new values with signals= pagination not updating the how many page is there.
For example it stucs in 1 page when i add 10 signal data to the table.
Its updating when it comes to delete.

**Comment by EnricoMessall** [comment]
Hey @tolgatopkara. Can you create a small example with stackblitz by using the original https://primeng.org/table#basic stackblitz doc? That would help to understand the issue a little bit better

**Comment by tolgatopkara** [comment]
after updating v18 and all other dependencies there is no bug left for now. 
if i find some time i will create a stackblitz example

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
