### ISSUE TITLE
MegaMenu: Aria-attributes doesn't match their roles

### ISSUE THREAD

**Issue by msg-jstren** [primefaces/primeng#16144]
### Describe the bug

Lighthouse detects the following accessability issue:
![image](https://github.com/user-attachments/assets/eb03e0f1-de25-4a65-84a3-4df11c1d27f3)

### Environment

This Lighthouse report is from the PrimeNG page itself: https://primeng.org/megamenu

It was first detected from us in our own implementation:
Browser: Chrome (Update 127)
Angular version: 17.2.3
PrimeNG version: 17.18.1

### Reproducer

https://primeng.org/megamenu

### Angular version

17.2.3

### PrimeNG version

17.18.6

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.9.0

### Browser(s)

Chrome

### Expected behavior

There should be no accessability issues.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
