### ISSUE TITLE
Import helpers from tslib (less bundle sizes)

### ISSUE THREAD

**Issue by ova2** [primefaces/primeng#1615]
In TypeScript 2.1, we can import TypeScript's helpers from **tslib**. This helps to reduce the size of  generated bundles. You can read about this e.g. here: https://blog.mariusschulz.com/2016/12/16/typescript-2-1-external-helpers-library

Currently, if you go e.g. to http://www.primefaces.org/primeng/#/blockui and inspect the response (Webpack generated JS file), you will see **this.__decorate** 9 times! The same function implementation is emitted 9 times. As solution you can install tslib

```
npm install tslib --save
```

and add this settings to tsconfig.js

```
{
  "compilerOptions": {
    ...
    "noEmitHelpers": true,
    "importHelpers": true,
    ...
  }
}
```

Many thanks.

**Comment by cagataycivici** [comment]
Thanks, we'll review.

**Comment by cagataycivici** [comment]
PrimeNG is now a CLI project so this is obselete now.
