### ISSUE TITLE
Calendar: showTime with dateMin creates inconsistencies

### ISSUE THREAD

**Issue by VMM-FE** [primefaces/primeng#16151]
### Describe the bug

When using the component of the calendar with the `[showTime]="true" [dateMin]="dateMin"` creates some inconsistencies with the workflow. Sometimes it works fine:

![working fine](https://github.com/user-attachments/assets/75337fd7-122c-4b24-8210-79c829193283)

First case:
Sometimes it just unable to select the min date (in the gif example min time was 15):

![min time not accessible](https://github.com/user-attachments/assets/a1bd0a0f-607e-4af2-a8c8-7cc0700cfbfc)

Second case:
Other times it's an infinite flow of decreasing the time (in the gif example min time was 10):

![decreasing time forever](https://github.com/user-attachments/assets/f4bbf35a-2563-4350-b677-d6c40a90b7ae)

I don't know why this is happening but it should always work as the first gif no matter the time or what the user clicks before accessing the time (I don't even know how to really reproduce it because sometimes works fine, sometimes is the first case and others is the second).

Thanks in advance!

### Environment

-

### Angular version

Last version

### PrimeNG version

Last version

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20

### Steps to reproduce the behavior

https://stackblitz.com/edit/c7hasn?file=src%2Fapp%2Fcalendar-time-demo.ts,src%2Fapp%2Fcalendar-time-demo.html,package.json

### Expected behavior

If the dateMin says that the min time it's 15:00 that should be the min time to select. And shouldn't be an inconsistence of going from 15 to 16 when clicking the down arrow.

**Comment by VMM-FE** [comment]
Maybe it's related with this other issue https://github.com/primefaces/primeng/issues/15609

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
