### ISSUE TITLE
Component: TreeSelect filter input box closes when the keyboard is called out when it is focused on an Android mobile

### ISSUE THREAD

**Issue by yuxixi0613** [primefaces/primeng#16168]
### Describe the bug

I found a bug in android mobile, when i click the TreeSelect-Filter (https://www.primefaces.org/primeng-v13-lts/#/treeselect),
the android mobile device will open the mobile's keyboard by default, then the TreeSelect and keyboard will close.
The entire process, from popping up to automatically closing, took less than a second.
In addition, I tested that Apple devices do not have this problem.

### Environment

angular version: 13.3.4
primeng version: 13.4.1

### Angular version

13.3.4

### PrimeNG version

13.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.16.0

### Steps to reproduce the behavior

1.Access(https://www.primefaces.org/primeng-v13-lts/#/treeselect) with android mobile.
2.click the filter TreeSelect component
3.Click on the search input box to focus it

https://github.com/user-attachments/assets/dcb89dd4-e6ed-40cb-a749-840fdca91a66

### Expected behavior

when the Android phone focuses on the input box, the entire TreeSelect component will not be closed due to the pop-up keyboard

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
