### ISSUE TITLE
Component: MultiSelect

### ISSUE THREAD

**Issue by MatviiKharlamenko** [primefaces/primeng#16162]
### Describe the bug

When using global clear button (i mean [showClear]="true") multiSelect does not trigger onChange

Similar problem but for chips which was fixed in 12.2.2.2 primeng version:
https://stackoverflow.com/questions/65475851/primeng-multiselect-on-change-not-triggered-on-chips-removal

### Environment

Primeng master version

### Reproducer

https://stackblitz.com/edit/yhk7ow-kk9ebt?file=src%2Fapp%2Fmulti-select-chips-demo.ts,src%2Fapp%2Fmulti-select-chips-demo.html

### Angular version

18.0.2

### PrimeNG version

master

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22.4.1

### Steps to reproduce the behavior

Try using showClear and onChange together

### Expected behavior

When using global clear button ([showClear]="true") multiSelect should trigger onChange

**Comment by EnricoMessall** [comment]
@MatviiKharlamenko I think it might be better to use [ngModel] with (ngModelChange). See this example:

https://stackblitz.com/edit/yhk7ow-zf6ww8?file=src%2Fapp%2Fmulti-select-chips-demo.html

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
