### ISSUE TITLE
Component: Dropdown touched event is triggered before value change

### ISSUE THREAD

**Issue by yelhouti** [primefaces/primeng#16163]
### Describe the bug

It is common practice to have code that shows validation error (ex: field required) when a field is touched.
ex:
```html
<p-dropdown
        [options]="choiceOptions!"
        name="choice"
        formControlName="choice"
        id="field_choice"
        [placeholder]="Choose"
>
</p-dropdown>
<div class="validation-messages">
  <ng-container
          *ngIf="
                editForm.controls.choice.errors && (editForm.controls.choice.dirty || editForm.controls.choice.touched)
              "
  >
    <p-message
            severity="error"
            *ngIf="editForm.controls.choice.errors.required"
            [text]="'entity.validation.required' | translate"
    >
    </p-message>
  </ng-container>
</div>
```

This issue with this code is that when you click on a dropdown value, an error is shown then disappears once the value is set. (Also if there is a layout shift on error show, the value is not set/clicked)

Touched IMO should not bet set when an option is clicked until a value is set or the dropdown is closed for any reason. (no hidden input blur nonsense needed)

### Environment

Angular Prime App

### Reproducer

https://stackblitz.com/edit/github-q5iejb?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

### Angular version

17.3.12

### PrimeNG version

17.18.7

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

stakcblitz

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. have a dropdown with a validation message when touched and error
2. open the dropdown
3. choose valid option
4. watch error blink

### Expected behavior

Error should not blink when touched

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
