### ISSUE TITLE
Component: IconField and InputIcon

### ISSUE THREAD

**Issue by MosheSchnitzler** [primefaces/primeng#16172]
### Describe the bug

When resizing the icon size, the icon will dock at the center instead of staying vertically centered. However, it does work when I explicitly specify the CSS `transform: translate(-50%);` and remove the `margin-top` on the `p-iconField` component

### Environment

Angular, PrimeNg, and TailwindCSS.

### Reproducer

https://stackblitz.com/edit/a8v14g?file=src%2Fapp%2Ficonfield-basic-demo.html

### Angular version

17.3

### PrimeNG version

17.18.7

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.15.0

### Steps to reproduce the behavior

Navigate to the stack blitz, and see it. Try to add the following styles to the p-inputIcon styleClass, and see how the icon element gets centered.
transform: translate(-50%);
margin-top: 0;

### Expected behavior

The icon should stay centered even when resizing it.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
