### ISSUE TITLE
p-table triggers lazy loading event twice 

### ISSUE THREAD

**Issue by aabruc** [primefaces/primeng#16182]
### Describe the bug

My table definition looks like this:
```
<p-table dataKey="id" [value]="items" 
    [paginator]="true" [rowsPerPageOptions]="[10,20,30,100,1000,10000]"
    [rows]="20" [alwaysShowPaginator]="false" paginatorDropdownAppendTo="body"
    [(selection)]="selectedItems" selectionMode="multiple" [metaKeySelection]="true"
    (onRowSelect)="rowSelect()" (onRowUnselect)="rowUnselect()"
    [lazy]="true" [showLoader]="true" [filters]="filters" (onFilter)="selectedItems = []"
    [rowHover]="true" responsiveLayout="scroll">
```    
We're faced with the issue that the combination of column filter and sorting triggers the lazy loading twice. 
Sorting and then column filter works fine, sorting without column filter also. 
As soon as there is a column filter in the LazyLoadingEvent, **a sorting  triggers twice,** and therefore we have two backend calls immediately after each other.
```
{first: 0, rows: 20, sortField: "changeDate", sortOrder: 1,…}
	filters: {name: {value: ["abc"], matchMode: "in"}}
	first: 0
	globalFilter: null
	rows: 20
	sortField: "changeDate"
	sortOrder: 1
```
I found a similar ticket that contains almost the same issue with PrimeNg version 14 from February 23, still open:
https://github.com/primefaces/primeng/issues/12595 

### Environment

Windows 11 Enterprise

### Angular version

17.3.12

### PrimeNG version

17.18.6

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.11.1

### Browser(s)

Chrome

**Comment by mnhock** [comment]
Are there any news on this ticket?

**Comment by mehmetcetin01140** [comment]
Hi, if you are still experiencing the issue with version 17.18.7, could you create a StackBlitz example?

**Comment by SaajRP** [comment]
@mehmetcetin01140 

I have been able to replicate this on PrimeNg 17.18.7. Look at the console log whenever you sort or filter a table column, it logs 2 lazy load events, when it should only log 1

https://stackblitz.com/edit/oetsny-rdsoxe?file=src%2Fapp%2Fdemo%2Ftable-virtual-scroll-lazy-demo.ts

**Comment by aabruc** [comment]
@SaajRP,
Hi and thank you! Unfortunately, in your demo even the first load runs twice. This is not the case in any of my programs.

In the meantime, I have also created a demo. Here you can see that only one lazy load event is called - in any case, even if filtering and then sorting are performed first. It's very simple, but I cannot see what difference to my (admittedly more complex program with the call to the backend) causes this double lazy loading.

I use PrimeNg 18 and Angular 18 and dynamic columns.
https://stackblitz.com/edit/mkvney-yv1qdi

Could you please check, if my demo is meaningful enough for this test and what the difference is to your program, @mehmetcetin01140, @SaajRP? When you have the same issue it must be a combination of p-table settings that leads to the double lazy loading. In the meantime, I will carry out this comparison with my program and let you know if I have any results.

Thank you and kind regards
Andrea.

**Comment by SaajRP** [comment]
@aabruc 

On your StackBlitz instance, I set the customSort property to true on p-table (as I assume sorting will be handled by your API instead of the client), now whenever I sort, it logs the lazy load event twice

**Comment by ahaller-billtrust** [comment]
I'm experiencing the same issue. Setting `customSort` property to **true** on `p-table` triggers `(onLazyLoad)` twice.
I also notice that the second call to `onLazyLoad` has incorrect pagination params if we are in a different page than the first one (`first` property of the lazy load event).

**Comment by aabruc** [comment]
Hi @ahaller-billtrust, 
You are right, this setting triggers lazy loading twice. Unfortunately, my table does not have this setting and if I explicitly set `[customSort]="false"`, it still does not help. But I guess you're on the right way, It could be a second call in the `sortSingle()` method by mistake.

**Comment by aabruc** [comment]
Tested in my program with PrimeNg 17.18.8 and now it works well.
Thank you all for the cooperation!

**Comment by SaajRP** [comment]
@mehmetcetin01140 , I've updated my Stackblitz instance to PrimeNg 17.18.9 (https://stackblitz.com/edit/oetsny-rdsoxe?file=src%2Fapp%2Fdemo%2Ftable-virtual-scroll-lazy-demo.ts,package.json), this is still an issue. In the console, it continues to log 2 events whenever the user  has entered a new value into a given filter
