### ISSUE TITLE
Virtual Scroll Jumping Backwards For P-Table

### ISSUE THREAD

**Issue by skmonirul248** [primefaces/primeng#16185]
### Describe the bug

Table definition looks like this:
```
<p-table #table 
         [columns]="visibleColumns" [value]="orderGridRows"
         dataKey="VPN"
         [sortField]="sortField" [sortOrder]="sortOrder"
         [reorderableColumns]="true" [resizableColumns]="true"
         [globalFilterFields]="['this.readData(data)']"
         columnResizeMode="expand" (onColReorder)="baseOnColReorder($event)"
         (onColResize)="baseOnColResize($event)"
         (onSort)="baseOnSort($event)"
         (onFilter)="onFilter($event)"
         [scrollHeight]="scrollHeight"
         [scrollable]="true"
         [virtualScroll]="true" [virtualScrollItemSize]="39"
         selectionMode="single"
         (onRowSelect)="onProductSelected($event)"
         rowHover="true">
```

### Environment

When virtualScroll = true, the scroll bar moves backwards while scrolling, causing the table to frick. Without virtualScroll the scroll capability functions as intended.

### Angular version

18.0.5

### PrimeNG version

17.18.7

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.16.0

### Browser(s)

Chrome 127.0.6533.90, Firefox - 128.0.3

### Steps to reproduce the behavior

The table is fricking and moving backward while you are scrolling.

**Comment by mehmetcetin01140** [comment]
Hi,

Could you please share a stackblitz example so we can identify the issue clearly?

**Comment by SaajRP** [comment]
Seems to linked to the virtualScrollItemSize.

In my Stackblitz, if I set the virtualScrollItemSize to 39, I can't scroll to the very bottom of the table, it goes back up. However if  I set it to 50 I have no issue

https://stackblitz.com/edit/oetsny-rdsoxe?file=src%2Fapp%2Fdemo%2Ftable-virtual-scroll-lazy-demo.ts

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try **PrimeNG v19**. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
