### ISSUE TITLE
Adds new feature - Avatar support image and label together

### ISSUE THREAD

**Issue by EnricoMessall** [primefaces/primeng#16199]
### Describe the bug

Feature ticket - requested by cetin

### Environment

-

### Angular version

-

### PrimeNG version

-

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

-

**Comment by EnricoMessall** [comment]
Hey @cetincakiroglu, here the issue ticket. Haven't opened issue tickets for both feature requests because the template is only for bugs :)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
