### ISSUE TITLE
RatingModule is not an ngModule

### ISSUE THREAD

**Issue by rolandoldengarm** [primefaces/primeng#1619]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
After upgrading to latest version of angular-cli, and Angular (2.3.1), I cannot import any module from primeNg:

````
$ ng build
Hash: 188beb6aad17abd0b4af
Time: 21282ms
chunk    {0} main.bundle.js, main.bundle.map (main) 380 kB {1} [initial] [rendered]
chunk    {1} vendor.bundle.js, vendor.bundle.map (vendor) 4.59 MB [initial] [rendered]
chunk    {2} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]

ERROR in RatingModule is not an NgModule
````
Tested with SliderModule and RatingModule.
All other modules and 3rd party  modules are working fine.

**Expected behavior**
I should be able to import a module.

**Please tell us about your environment:**
Windows 10, Angular-CLI @ latest master branch

* **Angular version:** 2.0.X
2.3.1

* **PrimeNG version:** 2.0.X
1.1.0

* **Node (for AoT issues):** 

`node --version` =   
6.9.3

**Comment by rolandoldengarm** [comment]
I've found a workaround, by importing the modules directly:

````
import { SliderModule } from 'primeng/components/slider/slider';
import { RatingModule } from 'primeng/components/rating/rating';
````

**Comment by cagataycivici** [comment]
I can't figure out why this happens, they are exported from primeng.ts

**Comment by rolandoldengarm** [comment]
Yeah I know, I've checked, but maybe this is because of a change in Angular 2.3.1? Or an issue with AOT? Just guessing.
Can't test without AOT as since .beta-22 in Angular CLI, AOT is always enabled.

**Comment by nieldw** [comment]
This is similar to this, more general, angular-cli issue: [#3157](https://github.com/angular/angular-cli/issues/3157) and [#3426](https://github.com/angular/angular-cli/issues/3426).

Downgrading typescript to 2.0.10 solved the problem for my own app.module, but I'm also getting this issue.

**Comment by markheron91** [comment]
From the angular issue https://github.com/angular/angular-cli/issues/3426 it seems as if this error occurs when the code is not statically analyzable. All of the internal folders within primeng have a <module>.metadata.json file - does the main folder need to have a primeng.metadata,json file?

**Comment by the-destro** [comment]
have you tried beta24 yet? It seems to have resolved this for me

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
