### ISSUE TITLE
Compatibility with row expansion and selection

### ISSUE THREAD

**Issue by akreidercap** [primefaces/primeng#1620]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/e4NHCBHLYzrx45965etD?p=preview

**Current behavior**
If I expand a row the row gets the ui-state-expanded and ui-state-highlight class. If I collapse a row ui-state-expanded class is removed, but ui-state-highlight class is still there.

**Expected behavior**
If I collapse a row ui-state-expanded and ui-state-highlight classes should be removed

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.2.4

* **PrimeNG version:** 1.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Can't replicate with latest version, please provide a new plunkr with 4.1.RC2.
