### ISSUE TITLE
Menubar: Clicking menuitems outputs error in console

### ISSUE THREAD

**Issue by quranc** [primefaces/primeng#16201]
### Describe the bug

**Component generates console errors**
When clicking on a menuitem in the menubar component, you can see console error output.

**Error message**
Blocked aria-hidden on a <a> element because the element that just received focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus.

<img width="376" alt="menubar" src="https://github.com/user-attachments/assets/fe0c3143-b0d5-4a5e-96a6-d4acf72dc580">

### Environment

Can be reproduced in the website showcases

### Reproducer

https://primeng.org/menubar

### Angular version

18

### PrimeNG version

17.18.7

### Build / Runtime

Angular CLI App

### Language

ALL

### Node version (for AoT issues node --version)

20.16.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Open inspect mode
2. Make sure you have the console open
3. Click on any of the menuitems in the Menubar (https://primeng.org/menubar)
3. You should now see the console error

### Expected behavior

No error output

**Comment by pjlasl** [comment]
@cetincakiroglu will this be corrected for v16 LTS?

**Comment by JohannesBeiserSG** [comment]
I keep having the described problem on 17.18.9.

**Comment by fabian4** [comment]
The problem also happened when using TreeModule
