### ISSUE TITLE
Adds new feature - Picklist selectable

### ISSUE THREAD

**Issue by EnricoMessall** [primefaces/primeng#16200]
### Describe the bug

Feature ticket

### Environment

-

### Angular version

-

### PrimeNG version

-

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

-

**Comment by EnricoMessall** [comment]
Hey @cetincakiroglu. Also for that [pull request](https://github.com/primefaces/primeng/pull/16045) a ticket to add it to the milestone

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
