### ISSUE TITLE
Range selection in Calendar

### ISSUE THREAD

**Issue by xg-wang** [primefaces/primeng#1621]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Expected behavior**
Add support for Elapse selection in a single calendar.

**What is the motivation / use case for changing the behavior?**
Now we have to create two calendars to input a start/end time, this could make calendar more flexible.

**Comment by cagataycivici** [comment]
Good idea!

**Comment by PavelBogatyrev** [comment]
Has it been intergrated into 4.1.1 if not what is next target milestone?

**Comment by cooljith91112** [comment]
Just found a bug in calendar range mode. If dates belongs to two months we can select two dates of the months but the selection is not visible.

![2017-09-11_13-49-27](https://user-images.githubusercontent.com/2651484/30264928-2b7428a6-96f8-11e7-84f8-2b7d06ca3238.gif)

**Comment by arulnithi** [comment]
This is because the range in-between calculation only considers dates (and not the months) for highlighting. When the date range is across multiple months, the in-between range tries to highlight the range between the start date and end date without considering that they are in different months. This is a bug

**Comment by FergusZhou** [comment]
@arulnithi May I know is there any way to fix this now?

**Comment by cagataycivici** [comment]
The bug is reported elsewhere.
