### ISSUE TITLE
I want to use PrimeNG's ConfirmationService in a service to display a confirmation dialog. However,...

### ISSUE THREAD

**Issue by LetAmericaGreatAgain** [primefaces/primeng#16218]
"I want to use PrimeNG's ConfirmationService in a service to display a confirmation dialog. However, the examples provided on the official website show how to use it in a component, requiring the <p-toast /> and <p-confirmDialog /> tags to be included in the HTML file. Since a service does not have a corresponding HTML file, how should I proceed?"

**Comment by shaman-apprentice** [comment]
It is enough to have one `<p-confirmDialog></p-confirmDialog>` somewhere in your app. I have put it in my root *app.component.html* at the bottom. The `ConfirmationService` will utilize this global instance. I hope this information helps you.
