### ISSUE TITLE
Enable edit based on row data

### ISSUE THREAD

**Issue by gregkopp** [primefaces/primeng#1622]
Is there a method/technique that can be implemented to make a specific row's elements editable?

I have a DataTable that is a mixture of "stock" and "user" data. I only want the user to be able to edit the "user" data.

**Comment by cagataycivici** [comment]
Like this?

https://www.primefaces.org/showcase/ui/data/datatable/edit.xhtml

**Comment by UrzaUrza** [comment]
I would like this feature too.
Any data or milestone ?

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
