### ISSUE TITLE
[p-inputNumber]How to get the original value before maxFractionDigits

### ISSUE THREAD

**Issue by ttnnphuoc** [primefaces/primeng#16237]
I want to get the original value for we do the action maxFractionDigits in [p-inputNumber]
Example:
original value: 89.931334923;
maxFractionDigits=2 => new value is 89.93.
So I want to get the original value (89.931334923) to calculation some thing.
Can you fix this or add a new property to get original value before splice with maxFractionDigits to control this?

**Comment by ibrahimkelly** [comment]
> I want to get the original value for we do the action maxFractionDigits in [p-inputNumber]
> Example:
> original value: 89.931334923;
> maxFractionDigits=2 => new value is 89.93.
> So I want to get the original value (89.931334923) to calculation some thing.
> Can you fix this or add a new property to get original value before splice with maxFractionDigits to control this?
> It's also possible to handle it in typescript side, for example if it's resulted by a division you have to set `originalValue = x/y`.

**Comment by mertsincan** [comment]
Thanks @ibrahimkelly ;)
