### ISSUE TITLE
PickList: onSourceFilter call api

### ISSUE THREAD

**Issue by huangyedie** [primefaces/primeng#16230]
### Describe the bug

The data returned by the call is not displayed .
As shown in the picture.
![lQLPJxD_x8NcYhfNAdnNBAmwGBuwyaLbCxEGpfiYv1hLAg_1033_473](https://github.com/user-attachments/assets/b8ffb043-9413-41b1-9da5-1587fbca4478)
![lQLPJxJrlAVFYhfNAQjNA3yw_n8GRIdoGhoGpfiYv1hLAQ_892_264](https://github.com/user-attachments/assets/c948ff8a-beb0-4e92-9426-1d31f12e3160)
![lQLPKHZvIgOHUxfNA-HNCA6weOjtkClzVZYGpfiYv1hLAA_2062_993](https://github.com/user-attachments/assets/f2bf595b-bd9a-4f10-825b-89bd54fcbe2f)

### Environment

I want to use lazy loading, so I have no choice but to use onSourceFilter。
See https://github.com/primefaces/primeng/issues/16201  

### Angular version

12.2.0

### PrimeNG version

12

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20

**Comment by huangyedie** [comment]
Can anyone help solve this？

**Comment by huangyedie** [comment]
@cetincakiroglu

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
