### ISSUE TITLE
Bootstrap Theme - Overwrites Application Style

### ISSUE THREAD

**Issue by thaoula** [primefaces/primeng#1624]
Hi Guys,

The new Bootstrap theme stylesheet introduced in 1.1 seems to break the styling of my application. 

This is caused by the addition of the Body selector in the stylesheet. Why is required, the components seem to work just find when you remove this selector.

**body {
    font-size: 1em;
    color: #373a3c;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
}**

Also, why are you setting the font and why is everything have to prefixed with body?

body .ui-widget,
body .ui-widget .ui-widget {
    **font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;**
    text-decoration: none;
    font-size: 1em;
}

Regards,
Tarek

**Comment by wujitouch** [comment]
I had the same issue. I just moved primeng's css files before mine.

**Comment by cagataycivici** [comment]
Removed the body {} style to fix this, still rest is untouched, we use the body prefix trick to override the structural css defined in primeng.css which should be placed after the theme.

**Comment by wujitouch** [comment]
I feel like this is the wrong way to theme it. Typically it's base styles, then theme styles. This allows you to easily override styles as intended in CSS.
