### ISSUE TITLE
Messages: Messages template does not work if messagemodule is imported alone

### ISSUE THREAD

**Issue by Pablo200206** [primefaces/primeng#16253]
### Describe the bug

When using a static message with a template, the template won't function if only the Message module is imported. However, if an additional module, such as the Dropdown module, is imported, the template will work.

https://stackblitz.com/edit/stackblitz-starters-245gze?file=src%2Fmain.ts

### Environment

{
  "name": "angular-starter",
  "private": true,
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build"
  },
  "dependencies": {
    "@angular/animations": "^18.1.0",
    "@angular/common": "^18.1.0",
    "@angular/compiler": "^18.1.0",
    "@angular/core": "^18.1.0",
    "@angular/forms": "^18.1.0",
    "@angular/platform-browser": "^18.1.0",
    "@angular/router": "^18.1.0",
    "primeng": "^17.18.9",
    "rxjs": "^7.8.1",
    "tslib": "^2.5.0",
    "zone.js": "~0.14.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^18.1.0",
    "@angular/cli": "^18.1.0",
    "@angular/compiler-cli": "^18.1.0",
    "typescript": "~5.5.0"
  }
}

### Angular version

18.1

### PrimeNG version

17.18

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20

### Browser(s)

Safari, Chrome, Edge

### Steps to reproduce the behavior

1. Go to https://stackblitz.com/edit/stackblitz-starters-245gze?file=src%2Fmain.ts
2. Template will not work
3. If you import DropDownModule it will work

**Comment by asithade** [comment]
Potentially similar if not the same issue. 

If you try to call a component that uses the messages module with a static message value within a parent component that uses ng-template, it doesn't load. 

https://stackblitz.com/edit/e4lkbj?file=src%2Fapp%2Fmessages-static-demo.html
