### ISSUE TITLE
Browser URL Not Updating Correctly After Navigation on PrimeNG Documentation Site

### ISSUE THREAD

**Issue by erfanfarhadi75** [primefaces/primeng#16257]
### Describe the bug

The browser's URL should update to `https://primeng.org/menubar` when navigating to the Menubar component and revert to `https://primeng.org/tabmenu` when going back

### Environment

- Browser: Chrome 127
- OS: Windows 11 Enterprise

### Angular version

None

### PrimeNG version

None

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

None

### Steps to reproduce the behavior

1. Navigate to [TabMenu](https://primeng.org/tabmenu).
2. Click on any of the items to navigate to [Menubar](https://primeng.org/menubar).
3. Use the browser's back button to go back to the previous page.

### Expected behavior

- The browser's URL should update to `https://primeng.org/menubar` when navigating to the Menubar component and revert to `https://primeng.org/tabmenu` when going back.

**Comment by can-oezkan** [comment]
I could not reproduce this bug on the current primeng v17 site.

**Comment by can-oezkan** [comment]
I can reproduce this bug now on v17 and v18.

Reproduce:
1. Click on any component on the sidebar (https://primeng.org/autocomplete)
2. Click on any other component on the sidebar (https://primeng.org/cascadeselect)
3. The browser back button does not navigate back. Only after clicking it multiple times.

**Before navigating to next component**
![image](https://github.com/user-attachments/assets/93a8bbdf-0eb7-4679-ada3-29fc75cf179f)

**After navigating to next component**
![image](https://github.com/user-attachments/assets/879ebff4-b51a-464d-b740-8c84c9a00b99)

**Comment by erfanfarhadi75** [comment]
Thank you, @can-oezkan , for taking the time to recheck and confirm the issue. I appreciate your efforts and attention to detail. If there's anything further I can do to help troubleshoot or provide additional information, please let me know. Thanks again! 🙏
