### ISSUE TITLE
Table: Responsive "stack" mode not behaving as advertised

### ISSUE THREAD

**Issue by Venom1991** [primefaces/primeng#16272]
### Describe the bug

When reaching the desired width breakpoint the table does not collapse rows, i.e. it does not stack the data as it's supposed to.

### Environment

Angular 17.3.12
PrimeNG 17.18.9
Node 22.6.0
Typescript 5.4.5
Windows 10
VS Code 1.92.2

### Angular version

17.3.12

### PrimeNG version

17.18.9

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22.6.0

### Browser(s)

Firefox 129, Chrome 127

### Steps to reproduce the behavior

Simply visit the [official example](https://primeng.org/table#responsive-stack) and try decreasing the window's horizontal dimension. A scrollbar is shown instead of the rows collapsing. Same thing happens locally within my Angular/PrimeNG app, of course.

### Expected behavior

The table should collapse its rows when the defined breakpoint is reached, as shown [here](https://www.primefaces.org/primeng-v14-lts/table/responsive) (PrimeNG v14 LTS)

**Comment by abinici** [comment]
I can confirm that this regression appears from version 17.18.9. And right now in one of my projects I have installed version 17.18.8 to avoid this issue.

**Comment by Venom1991** [comment]
@abinici 
Thank you, I'll downgrade to 17.8.8.

**Comment by nick-allen** [comment]
#16291

**Comment by Venom1991** [comment]
Hi, what is happening with this issue? As far as I can tell, PrimeNG v18 dropped support for this feature entirely (no "Responsive" section in the [docs](https://v18.primeng.org/table)). Does this mean that this issue probably wont be fixed, ever?
