### ISSUE TITLE
Chips seperator

### ISSUE THREAD

**Issue by FallenRiteMonk** [primefaces/primeng#1628]
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Adding chip is only possible using enter key

**Expected behavior**
Have the possibility to define one or more custom keys for inserting a chip (ex.: like space)

**What is the motivation / use case for changing the behavior?**
Gives developers the possibility to decide what is best for there use case

**Comment by cagataycivici** [comment]
We'll consider this when more users require it. Thank you.

**Comment by danteCarvalho** [comment]
i want exactly this behavior ( Have the possibility to define one or more custom keys for inserting a chip (ex.: like space)), so i am requesting it.

**Comment by jackstuard** [comment]
same here, I would like to use space to add a chips...

**Comment by abhisheksharma85** [comment]
Any plan to add these custom chips feature?

**Comment by edboyledev** [comment]
I have to bump this. I find the most common use of chips in my development is something along the lines of hashtags and single keywords.
