### ISSUE TITLE
Chip duplicate handling

### ISSUE THREAD

**Issue by FallenRiteMonk** [primefaces/primeng#1630]
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
A user can enter the same chip over and over again

**Expected behavior**
Prevent the input of multiple same/duplicate chips

**What is the motivation / use case for changing the behavior?**
To have the possibility to prevent users from spaming with same chips

**Comment by lebnic** [comment]
Moreover, this setting should be configurable, eg: allowDuplicates="false"
