### ISSUE TITLE
Component: Using P-table with pagination in dialog

### ISSUE THREAD

**Issue by Balakoteswararo** [primefaces/primeng#16312]
### Describe the bug

I am using a table with pagination inside a p-dialog. When I click on the p-paginator-rpp-options, it is displayed inside the popup, but I need it to display above the popup. Is there any code to fix this issue?. i am using the same component in so many paces.

![popup-issue](https://github.com/user-attachments/assets/369e0d82-d170-447a-b01d-cecc967eb9a0)

this image was with more data.
![popup with more data](https://github.com/user-attachments/assets/b52112ed-b8f4-44c8-8223-1508fe38c04d)

**Below is the code in my application**:
<p-dialog [(visible)]="showPopup" *ngIf="showPopup" [style]="{width: '70%'}" header=" Data" [modal]="true">
    <ng-template pTemplate="content">
        <app-vectorgrid appendTo="body" *ngIf="PopupColumns" [gridConfig]="gridConfig" [dataSource]="PopupData"
            [defaultColumns]="PopupdefaultColumns" [cols]="PopupColumns" [EnableSearch]="true"
            [globalFilterFields]="popupglobalFilterFields" (OnRowSelect)="OnRowSelect($event)">
        </app-vectorgrid>
    </ng-template>
</p-dialog>

### Environment

production

### Angular version

14

### PrimeNG version

11

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20

### Browser(s)

All Browsers

**Comment by Balakoteswararo** [comment]
**any one can explain the issue & what was the solution for this issue?**

**Comment by Balakoteswararo** [comment]
Issue was fixed.

**Comment by zaeemhuzaifa** [comment]
what was the solution to this.??i am having the same problem

**Comment by zaeemhuzaifa** [comment]
> Issue was fixed.

how..?

**Comment by Balakoteswararo** [comment]
Its Fixed

**Comment by Balakoteswararo** [comment]
Add the **paginatorDropdownAppendTo="body"** property to your <p-table> to ensure the paginator dropdown renders properly, especially inside modals or scrollable containers.

<p-table [value]="data" [paginator]="true" paginatorDropdownAppendTo="body">
</p-table>
