### ISSUE TITLE
Multiple column support for Listbox

### ISSUE THREAD

**Issue by ekuusi** [primefaces/primeng#1631]
**I'm submitting a ...** 
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**What is the motivation / use case for changing the behavior?**
I would like to have the Listbox to allow for listing the items in multiple columns. The current features of Listbox is perfect for us especially with the new checkbox / filter support, but in a situation with a lot of entries (in our case selecting multiple names from a large list), it would be very useful to show results in two or three columns to make better use of screen real estate.

**Comment by cagataycivici** [comment]
You can just use templating and use grid css inside.
