### ISSUE TITLE
Page hangs when scroll to bottom of p-table and filter any data.

### ISSUE THREAD

**Issue by RinkuKushwaha** [primefaces/primeng#16323]
### Describe the bug

In primeng table, when we have data around 50K - 60K rows, then on scrolling to the bottom of the table and then apply any filtering, then the whole page is getting hanged. 
The case is added in this project:
[PrimeNgDemo.zip](https://github.com/user-attachments/files/16833357/PrimeNgDemo.zip)

### Environment

Windows 10
Angular CLI - 16

### Angular version

16.1.0

### PrimeNG version

16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.1

### Browser(s)

All browsers

### Steps to reproduce the behavior

1. Scroll to then end of the table
2. Filter any record from any column
3. Try to do anyother operation

### Expected behavior

Filtering should work and page should not go unresponsive

**Comment by SaajRP** [comment]
Seems to be a delicate of https://github.com/primefaces/primeng/issues/13494
