### ISSUE TITLE
Listbox select all with filter only selects those starting with filter string

### ISSUE THREAD

**Issue by ekuusi** [primefaces/primeng#1632]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Can be reproduced in the sample at PrimeNg:
http://www.primefaces.org/primeng/#/listbox

**Current behavior**
Select all button only selects entries that start with the search string instead of all entries that are shown with the current filter.

**Expected behavior**
Should select all entries shown with the filter.

**Minimal reproduction of the problem with instructions**
In the sample, filter with 'r', then click the select all checkbox. It only selects Rome out of the three entries shown. 

Filter with 'n', click select all and it only selects New York.

**What is the motivation / use case for changing the behavior?**
The current behavior is not expected and very unintuitive.

**Comment by cagataycivici** [comment]
Not sure, I think it makes sense to select all that are visible, if there is more feedback, we'll reconsider. Thank you.

**Comment by ekuusi** [comment]
@cagataycivici there was a bug before, but it has been fixed in some recent release after I made this post. It now works as it should, so closing is fine.
