### ISSUE TITLE
Rename InputTextarea as TextArea

### ISSUE THREAD

**Issue by cetincakiroglu** [primefaces/primeng#16332]
InputTextarea directive will be deprecated in v18. Use `textarea` directive instead which is renamed version of InputTextarea.

**Comment by cetincakiroglu** [comment]
Fixed in v18.0.0-beta.1

**Comment by THL-giacomo-mariani** [comment]
I have not found any documentation of this change in the migration guide to version 18 (https://v18.primeng.org/guides/migration) or to version 19 (https://primeng.org/migration/v19)
