### ISSUE TITLE
DynamicDialog | Closing nested dialog makes the underlying dialog scroll back to the top

### ISSUE THREAD

**Issue by mehmetcetin01140** [primefaces/primeng#16335]
https://stackblitz.com/edit/yhhhok?file=src%2Fapp%2Fdemo%2Fproductlistdemo.ts

**Comment by kekude** [comment]
hello, upgraded to latest version 20.1.2 the issue is still present

**Comment by cs-AmadeoTerriere** [comment]
> hello, upgraded to latest version 20.1.2 the issue is still present

We also have the problem reintroduced since the upgrade to version 19. It seems to be on version 21.X though.. https://github.com/primefaces/primeng/commit/5f215ec2c705287ac3b8cf0a8ec4f5de48f6efa0
