### ISSUE TITLE
ContextMenu: disabled label

### ISSUE THREAD

**Issue by Danieleeee** [primefaces/primeng#1634]
feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
```

**Current behavior**
All items and labels are always activated in ContextMenu.

**Expected behavior**
Have the possibility to set disabled some label of the ContextMenu


* **Angular version:** 2.3.X

* **PrimeNG version:** 1.1.X

* **Browser:** [ Chrome Latest| IE XX  ]

**Comment by kt215** [comment]
This feature already exists in PrimeNG 1.1.0. Use `MenuItem`'s `disabled` field.

See documentation here: http://www.primefaces.org/primeng/#/menumodel

**Comment by Danieleeee** [comment]
You are right.
Thanks!

​A​
nother question
​:
​
Is there a function that
​is called ​
when I click
​ the right button of the mouse, before the contextual menu?​

​Thanks.​



2016-12-20 14:43 GMT+01:00 Ken <notifications@github.com>:

**Comment by kt215** [comment]
On a `div` you can do this:

```
(contextmenu)="onContextMenu($event)"
```

But, try using stackoverflow for questions instead:
http://stackoverflow.com/search?tab=newest&q=primeng
