### ISSUE TITLE
Component: Select [primeng v18]

### ISSUE THREAD

**Issue by luca-peruzzo** [primefaces/primeng#16351]
### Describe the bug

In the new primeng v18 beta the select overlay-panel does not change style when the user goes mouse-over on an option.
In the previous version (dropdown) and other v18 components, such as the popup menu or context menu, this style change is available.

### Environment

[primeng v18 showcase](https://v18.primeng.org/select)

### Reproducer

https://v18.primeng.org/select

### Angular version

18.2.2

### PrimeNG version

18.0.0-beta.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.17.0

### Expected behavior

Select option background have to change when a user goes mouse-over on it

**Comment by cagataycivici** [comment]
Thanks for trying out the beta, we'll get this in beta.2.

**Comment by cetincakiroglu** [comment]
Fixed in 18.0.0-beta.2
