### ISSUE TITLE
p-inputOtp does not paste code sent by SMS, only sets the first digit

### ISSUE THREAD

**Issue by jvegaseg** [primefaces/primeng#16373]
### Describe the bug

Using a mobile and when an OTP is sent by SMS, the keyboard suggest the code, if your select the suggestion, only the first char is copied in the fields (6-digits).

I do not know it it related to **autocomplete="one-time-code"** attribute but p-inputOtp  is not using it.

### Environment

A web page using Chrome navigator on an iphone mobile.

### Angular version

18.2.4

### PrimeNG version

17.18.10

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.14.0

### Browser(s)

Chrome 128.0.6613.120

### Expected behavior

6-digits code filled in the p-inputOtp field

**Comment by gitadam0** [comment]
@jvegaseg any updates?

**Comment by gquittet** [comment]
Hello @gitadam0 @jvegaseg 👋 

I ended up with this solution and it works well on my side:

```html
<p-inputOtp [formControl]="otpInput" [integerOnly]="true" [length]="6">
  <ng-template pTemplate="input" let-token let-events="events">
    <input
      pInputText
      type="text"
      [maxLength]="1"
      (input)="events.input($event)"
      (paste)="events.paste($event)"
      [attr.value]="token"
      autocomplete="one-time-code"
    />
  </ng-template>
</p-inputOtp>
```

**Comment by luca-peruzzo** [comment]
this bug is also present in primeng 18.0.0-beta.3
[inputotp](https://v18.primeng.org/inputotp#integeronly)

**Comment by medbenmakhlouf** [comment]
I handled this use case in my last PR and I wrote a test fo it , you can check it in this commit : https://github.com/primefaces/primeng/pull/16650/commits/1bde5dd2c50b8888eaa6802c0f1b5a741ec44663

**Comment by luca-peruzzo** [comment]
created #16824 to fix the problem in v18

**Comment by JuenTingShie** [comment]
Is this fix release in v18? May I ask when will this been release?
