### ISSUE TITLE
p-table: custom sort should not be invoked if `lazy` is true

### ISSUE THREAD

**Issue by MikeMatusz** [primefaces/primeng#16370]
### Describe the bug

If I configuring the p-table for lazy-loading, the sort should be handled on the server or in the `onLazyLoad` function, otherwise the sort has only a portion of the total data source available.  And if we are already sorting on the server, it tries to run additional client-side logic to sort, which may conflict.

Numerous issues have come up in the past about using them together, and the response has always been the same as above.  That changed suddenly with #15550 and caused issues we had to work around in our code.  This was a breaking change, not a fix, and I'm not sure the utility of it.

If new records are returned when you load the next page, the client-side sort might interleave them with the first set of results, which would be a very confusing user experience.  I can't think of a good use case for supporting this, as it seems like it could only cause undesirable behavior.

### Environment

N/A

### Angular version

17

### PrimeNG version

17

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20

**Comment by mertsincan** [comment]
Could you please try the latest version?
