### ISSUE TITLE
Multi-select : Chip remove event not exposed 

### ISSUE THREAD

**Issue by lm-shashank** [primefaces/primeng#16379]
### Describe the bug

Chip remove event not exposed 

### Environment

Dev

### Angular version

18.0.0

### PrimeNG version

17.18.10

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

-

**Comment by LucasLopesr** [comment]
Please, if possible, deliver this in the 16.9.15-LTS version as well, I just encountered this issue and am looking for a way around it
