### ISSUE TITLE
Can not get updatePrimaryPalette to work in 18.0.0-beta.1

### ISSUE THREAD

**Issue by Puresoft** [primefaces/primeng#16387]
### Describe the bug

By calling updatePrimaryPalette my primary colors do not change. Also a custom preset seem not work.

I've provided a stackblitz.

Thank you very much.

### Environment

I'm on Windows 

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-x2oc1x?file=src%2Fmain.ts

### Angular version

18.2.2

### PrimeNG version

18.0.0-beta.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22.7

### Browser(s)

Chrome

**Comment by matejschwartz** [comment]
I have the same issue, trying to replace primary color of Lara or Aura theme, everything mentioned in documentation doesn't work: definePreset, updatePreset, updatePrimaryPalette...

**Comment by svenhabex** [comment]
I have the same issue. Still present in 18.0.0-beta.2

**Comment by COLTstreet** [comment]
I am also having this same issue with 18.0.0-beta.2

**Comment by Haze272** [comment]
Same problem 18.0.0-beta.2. Neither definePreset() method nor the overriding variables doesnt work to change theme. Seems that we have to wait for stable version

**Comment by cetincakiroglu** [comment]
Hi all, 

We've fixed the issue with v18.0.0-beta.2. 
For the example above, there was an error while defining and setting the preset. Could you please check the example below?

Here is the refactored version of your example: https://stackblitz.com/edit/stackblitz-starters-nmlpfw?file=src%2Fmain.ts,package.json

**Comment by cetincakiroglu** [comment]
Closing the issue then, thanks for testing and reporting the beta!
