### ISSUE TITLE
Datatable col header alignment lost while sorting

### ISSUE THREAD

**Issue by srinigowda** [primefaces/primeng#1638]
![colheaderalignmentlost](https://cloud.githubusercontent.com/assets/44777/21349591/b8b2db86-c6d8-11e6-89ea-94bb202b4d44.png)

The column header alignment is lost while sorting.

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
