### ISSUE TITLE
Inquiry About Future Licensing Plans for PrimeNG

### ISSUE THREAD

**Issue by rahul-scriptus** [primefaces/primeng#16389]
Dear PrimeNG Support Team,
 
I am writing to inquire about PrimeNG’s future licensing plans. Specifically, **I would like to know if there are any plans to transition entirely to a premium-only model for future releases of PrimeNG.**

Understanding your future direction on this matter will greatly assist in our planning and decision-making process. Any information you could provide would be greatly appreciated.

Thank you for your time and assistance.

Best regards,
Rahul-scriptus

**Comment by mertsincan** [comment]
PrimeNg is an open-source project. You can use all currently existing components for free. Only addons such as primeng-blocks and templates will be paid.

Exp;
https://primeblocks.org/
