### ISSUE TITLE
 Issue with Flexbox Layout (and others) with some components

### ISSUE THREAD

**Issue by azuziii** [primefaces/primeng#16388]
### Describe the bug

I'm tired of having to manually keep writing stupid things like 
```
p-button button {
  width: 100%;
}

p-password,
p-password > div,
p-password > div > input {
  width: 100% !important;
}

a {
  display: flex;
  justify-content: center;
}
```

The above "fix" causes other issues with icon buttons, and some other components.

A button, input or any other component should stretch to take the full width of it parent if you use something like flex, the only thing that is stretching is p-password and the button isn't (nor is the div inside the p-password). Same thing happens with inputs, it just starts to get annoying because that is not quite the default behavior, and doing [style]={width...} is not a fix.

### Environment
```
{
  "name": "app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^18.2.0",
    "@angular/common": "^18.2.0",
    "@angular/compiler": "^18.2.0",
    "@angular/core": "^18.2.0",
    "@angular/forms": "^18.2.0",
    "@angular/platform-browser": "^18.2.0",
    "@angular/platform-browser-dynamic": "^18.2.0",
    "@angular/router": "^18.2.0",
    "@types/socket.io": "^3.0.1",
    "ngx-socket-io": "^4.7.0",
    "primeflex": "^3.3.1",
    "primeicons": "^7.0.0",
    "primeng": "^17.18.10",
    "rxjs": "~7.8.0",
    "socket.io": "^4.7.5",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.10"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^18.2.2",
    "@angular/cli": "^18.2.2",
    "@angular/compiler-cli": "^18.2.0",
    "@types/jasmine": "~5.1.0",
    "jasmine-core": "~5.2.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "tailwindcss": "^3.4.11",
    "typescript": "~5.5.2"
  }
}
```

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-cd191d?description=An%20angular-cli%20project%20based%20on%20@angular/animations,%20@angular/common,%20@angular/compiler,%20@angular/core,%20@angular/forms,%20@angular/platform-browser,%20@angular/platform-browser-dynamic,%20@angular/router,%20core-js,%20rxjs,%20tslib%20and%20zone.js&file=src%2Fmain.ts,src%2Fglobal_styles.css&template=node&title=Angular%20Starter

### Angular version

18.2.0

### PrimeNG version

17.18.10

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.17.0

### Steps to reproduce the behavior

Just make a parent component with display flex and flex-direction column, put p-password, p-input or p-button and a normal button or input and see the difference for your self.

**Comment by mertsincan** [comment]
This is not related to PrimeNg core. Please use PrimeNG discord channel/discussion.

Best Regards,
