### ISSUE TITLE
Multiselect-Chip Close Event not exposed

### ISSUE THREAD

**Issue by lm-shashank** [primefaces/primeng#16381]
### Describe the bug

In the Multiselect when we select element as chip and  from top bar input box if we want to close the chip the close event is not exposed

### Environment

Development

### Angular version

18.0.0

### PrimeNG version

17.18.10

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.1

### Browser(s)

Chrome

### Expected behavior

It Should fire a close event

**Comment by LucasLopesr** [comment]
Please, if possible, deliver this in the 16.9.15-LTS version as well, I just encountered this issue and am looking for a way around it
