### ISSUE TITLE
PasswordModule UI is different from InputTextModule UI when fields are disabled

### ISSUE THREAD

**Issue by manukudur** [primefaces/primeng#16393]
### Describe the bug

i want to disable the input fields while interacting with api. but i feel UI is not similar when input fields are disabled.

input fields without disabled
![Screenshot 2024-09-16 154533](https://github.com/user-attachments/assets/de4fff64-c207-4dc7-a29b-dea5fa2e85c5)

input fields with disabled
![Screenshot 2024-09-16 154445](https://github.com/user-attachments/assets/25f3a510-ada5-455c-9b22-6bba453dba14)

my suggestion is both fields should look similar and also 'toggleMask' should not work when disabled.

code link -->  [stackblitz](https://stackblitz.com/edit/stackblitz-starters-rfxdhs?file=src%2Fmain.ts)

### Environment

dev

### Angular version

18.1.0

### PrimeNG version

18.0.0-beta.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.15.1

### Steps to reproduce the behavior

added stackblitz link

### Expected behavior

my suggestion is both fields should look similar and also 'toggleMask' should not work when disabled.

**Comment by cetincakiroglu** [comment]
Hi,

Thanks a lot for testing the beta and reporting the issue!

**Comment by cetincakiroglu** [comment]
Fixed in https://github.com/primefaces/primeng/commit/c66a1457f631eebc8ea58c6b8542d506f870b75c
