### ISSUE TITLE
DynamicDialog: Mask not working (v18)

### ISSUE THREAD

**Issue by jicedtea** [primefaces/primeng#16396]
### Describe the bug

Mask not working with dyanamic dialog

### Environment

All environments

### Reproducer

https://v18.primeng.org/dynamicdialog#example

### Angular version

18.2.0

### PrimeNG version

18.0.0.beta-1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22

### Browser(s)

All

### Steps to reproduce the behavior

![image](https://github.com/user-attachments/assets/bd6664f2-93a3-4f83-a1dc-05ac591525f9)

### Expected behavior

![image](https://github.com/user-attachments/assets/8fe16b54-c59d-47d4-aff8-6ea6a4791256)

**Comment by cetincakiroglu** [comment]
Fixed in ab3a9693236966a53bc4b8e3abcc7635f18b2753
