### ISSUE TITLE
p-password template

### ISSUE THREAD

**Issue by vikore** [primefaces/primeng#16400]
### Describe the bug

When we open p-password input template in %zoom, the template is overlapping on the input field and user can't see the input value. Please find the attached screen shot and video -

![Screenshot 2024-09-18 165938](https://github.com/user-attachments/assets/8f0e137d-c598-4398-b7ff-7ef6af64b456)

https://github.com/user-attachments/assets/d8a4011e-dd30-461c-89ea-02da399a3659

### Environment

Development

### Angular version

17.3.6

### PrimeNG version

17.16.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.1

### Browser(s)

Chrome, Firfox, safari, IE-Edge

### Steps to reproduce the behavior

1.  Increase percent zoom of the page to 175% - 200%
1.  Navigate to p-password template input
2.  click on the input
3.  Observe the template overlaps on the input making input hidden behind the template

### Expected behavior

password template should be opened at the top or bottom of the input depending on the position of the input on the page

**Comment by mertsincan** [comment]
Hi,

The components don't support changes related to zoom in/out.
