### ISSUE TITLE
MultiSelect: onSelectAllChange event is not working

### ISSUE THREAD

**Issue by yashvendar** [primefaces/primeng#16414]
### Describe the bug

`onSelectAllChange` event is not working for `multiselect`

### Environment

All environments

### Angular version

16.2.0

### PrimeNG version

16.9.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.10.0

### Browser(s)

All browser

### Steps to reproduce the behavior

1. Create a function that displays input events on console
2. call this function on `onSelectAllChange` event of `multiselect` component
3. check or un-check select all checkbox on the overlay
4. you will see that we are not getting any events.

### Expected behavior

After all item selection or un-selection, `multiselect` component should emit `onSelectAllChange` event

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
