### ISSUE TITLE
Datepicker's showIcon property is missing in the interface in prime v18

### ISSUE THREAD

**Issue by rogeru** [primefaces/primeng#16412]
### Describe the bug

In prime v18 beta 1, the showIcon property of the datepicker component seems to be still used but missing in the interface 
https://github.com/primefaces/primeng/blob/18.0.0-beta.1/src/app/components/datepicker/datepicker.interface.ts

v18 docs also still list the property.

### Environment

prime v18 beta 1

### Angular version

18.2.5

### PrimeNG version

18.0.0-beta.1

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

20.16.0

### Browser(s)

Chrome latest

**Comment by cetincakiroglu** [comment]
Hi,

Thanks a lot for reporting the issue, it seems that the issue has been fixed in v18.0.0-beta.2

Please see: https://v18.primeng.org/datepicker#api.datepicker.props.showIcon

Closing the issue.
