### ISSUE TITLE
Component: Slider

### ISSUE THREAD

**Issue by bable3** [primefaces/primeng#16429]
### Describe the bug

Dinamicly change min and max values doesn't recalculate handlevalue

### Environment

angular 18.2.0
primeng : 17.18.9

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-ju5w7w?description=An%20angular-cli%20project%20based%20on%20@angular/animations,%20@angular/common,%20@angular/compiler,%20@angular/core,%20@angular/forms,%20@angular/platform-browser,%20@angular/platform-browser-dynamic,%20@angular/router,%20core-js,%20rxjs,%20tslib%20and%20zone.js&file=package.json,src%2Fmain.ts,angular.json,src%2Findex.html&template=node&title=Angular%20Starter

### Angular version

18.2.0

### PrimeNG version

17.18.9

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.17.0

### Browser(s)

chrome 

### Steps to reproduce the behavior

set the value of the slider at 40
set the min value to 30

### Expected behavior

the slider should update it's dom to be from 30 to 100 and not just when i change the value.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by mwilman** [comment]
It seems that the problem is still occuring. The handle position does not change when you change the min or max value of the slider. It should rerender, but it does not.
