### ISSUE TITLE
Frozen columns not working in RTL table

### ISSUE THREAD

**Issue by tigrenok00** [primefaces/primeng#16427]
### Describe the bug

Reopening a bug from January which is still not fixed in the latest version, making RTL frozen columns unusable!!

Using frozen columns (one or more) in RTL direction has incorrect results:

With alignFrozen="right":

Inspecting the css (example with one frozen column, the first one):
both th and td - has incorrect position of right: 69px (instead of 0)

Adding another frozen column is all wrong making the two of them overlap.

Without alignFrozen="right":
(one col example)
both td and th have left: 0px instead right: 0

I'm very much in need of frozen columns support in RTL, is there a quick workaround to make this work (with multiple frozen columns)?

### Environment

Angular

### Angular version

18.2.0

### PrimeNG version

17.18.10

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.20.4

**Comment by tigrenok00** [comment]
https://github.com/primefaces/primeng/issues/14480

**Comment by mertsincan** [comment]
Thanks a lot for this issue! We're working on RTL support in v18. We'll check and get back to you before 18.Final

**Comment by mertsincan** [comment]
Could you please try the latest 18 version? 

For now, closed. If the problem persists, please reopen this issue.
