### ISSUE TITLE
DomHandler:  calculateScrollbarHeight() setting this.calculatedScrollbarWidth, should be this.calculatedScrollbarHeight.

### ISSUE THREAD

**Issue by greg9504** [primefaces/primeng#16433]
### Describe the bug

While profiling an application with many dom items, I noticed that context menus were slow to display.  Profiling revealed that a render style calculation was caused by the context menu 
![image](https://github.com/user-attachments/assets/390d2823-c687-423c-ac1c-0cd8604bc003)
```javascript
positionSubmenu(sublist) {
        let parentMenuItem = sublist.parentElement.parentElement;
        let viewport = DomHandler.getViewport();
        let sublistWidth = sublist.offsetParent ? sublist.offsetWidth : DomHandler.getHiddenElementOuterWidth(sublist);
        let sublistHeight = sublist.offsetHeight ? sublist.offsetHeight : DomHandler.getHiddenElementOuterHeight(sublist);
        let itemOuterWidth = DomHandler.getOuterWidth(parentMenuItem.children[0]);
        let itemOuterHeight = DomHandler.getOuterHeight(parentMenuItem.children[0]);
        let containerOffset = DomHandler.getOffset(parentMenuItem.parentElement);
        sublist.style.zIndex = ++DomHandler.zindex;
        if (parseInt(containerOffset.top) + itemOuterHeight + sublistHeight > viewport.height - DomHandler.calculateScrollbarHeight()) { //<-- call to calculateScrollBarHeight causes style every time
            sublist.style.removeProperty('top');
            sublist.style.bottom = '0px';
        }
        else {
            sublist.style.removeProperty('bottom');
            sublist.style.top = '0px';
        }
        if (parseInt(containerOffset.left) + itemOuterWidth + sublistWidth > viewport.width - DomHandler.calculateScrollbarWidth()) {
            sublist.style.left = -sublistWidth + 'px';
        }
        else {
            sublist.style.left = itemOuterWidth + 'px';
        }
    }

```
Looking at the code in calculateScrollbarHeight:
```javascript
public static calculateScrollbarHeight(): number {
        if (this.calculatedScrollbarHeight !== null) return this.calculatedScrollbarHeight;

        let scrollDiv = document.createElement('div');
        scrollDiv.className = 'p-scrollbar-measure';
        document.body.appendChild(scrollDiv);

        let scrollbarHeight = scrollDiv.offsetHeight - scrollDiv.clientHeight;
        document.body.removeChild(scrollDiv);

        this.calculatedScrollbarWidth = scrollbarHeight; //<--- this should be this.calculatedScrollbarHeight

        return scrollbarHeight;
    }
```
The line:
 this.calculatedScrollbarWidth = scrollbarHeight;
should be:
this.calculatedScrollbarHeight = scrollbarHeight;

While this will not improve the context menu performance the first time the context menu is displayed, subsequent instances of context menus will display much faster as a Recalculate style will not need to be done.

Guessing this is a cut and paste error when the method was first written.

Also wondering if there is a better way to do this without requiring style recalculation.  

### Environment

Found in 15.4.1 but looking at the latest code, bug is still there.

### Angular version

15.2.5

### PrimeNG version

15.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.15.0

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
