### ISSUE TITLE
New Component | Tabs

### ISSUE THREAD

**Issue by cetincakiroglu** [primefaces/primeng#16437]
New component Tabs will be added as a replacement for deprecated TabView component.

**Comment by cetincakiroglu** [comment]
Fixed in https://github.com/primefaces/primeng/commit/acd95adcd25495ad706b3cc81932fc147dde683a

**Comment by akigroupemanagement** [comment]
Hi,

How can we get active index ? In TabView we have [(activeTabIndex)], what is the equivalent in <p-tabs ? 

Thanks in advance
Regards
