### ISSUE TITLE
Component: Metergroup

### ISSUE THREAD

**Issue by AleTornesello** [primefaces/primeng#16439]
### Describe the bug

When the first or last meter item is not visible because his value is 0, the **visible** first or last items, instead of rounded start/end, they have a flat start/end.

For example:
![image](https://github.com/user-attachments/assets/6feddf0f-82b4-4a66-bd49-978fe500f64b)

I suggest to ignore the items with a value equal to zero to prevent this. The correct way to view the meter should be:
![image](https://github.com/user-attachments/assets/011227bc-4cee-4b26-8943-0e1f3f0575f9)

### Environment

I have forked this repository and run it with `npm run start`. I did't have done any changes.

### Angular version

18.0.2

### PrimeNG version

17.18.10

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.17.0

### Steps to reproduce the behavior

Set the first and/or last meter group items' value of the meter group exaple to zero.

**Comment by cetincakiroglu** [comment]
Fixed in https://github.com/primefaces/primeng/pull/16440
