### ISSUE TITLE
DataTable - incorrect index on dynamic objects

### ISSUE THREAD

**Issue by wujitouch** [primefaces/primeng#1645]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/HN5PvhvbyPij65jHzH35

**Current behavior**
DataTable row index is not correct when dynamically adding objects in the middle of the values array. It works correctly if adding them to the end of the array.

**Expected behavior**
Index should be correct, as in the ngFor directive (see plunk)

**Comment by wujitouch** [comment]
I think this might be a problem with change detection in Angular 2. If I change the array reference for values to a new array instance it works.

For example, this works:

this.cars = JSON.parse(JSON.stringify(this.cars));

<p-dataTable [value]="cars">
        <p-column header="Index">
            <template pTemplate="body" let-index="rowIndex">
                {{index}}
            </template>
        </p-column>
    </p-dataTable>

**Comment by wujitouch** [comment]
So I figured out why it's doing this and how to solve it (at least my way). The reason (I think) it does this is because the ColumnBodyTemplateLoader directive is recycled by the ngFor parent directive. So, the child directive needs to watch for changes and updated the view's context accordingly. This is the working code:

`@Component({
    selector: 'p-columnBodyTemplateLoader',
    template: ``
})
export class ColumnBodyTemplateLoader {
        
    @Input() column: any;
        
    @Input() rowData: any;
    
    @Input() rowIndex: number;

    context: any;
    
    constructor(public viewContainer: ViewContainerRef) {}
    
    ngOnChanges() {
        if (this.context) {
            this.context.rowData = this.rowData;
            this.context.rowIndex = this.rowIndex;
        }
    }

    ngOnInit() {
        this.context = {
            '\$implicit': this.column,
            'rowData': this.rowData,
            'rowIndex': this.rowIndex
        };
        let view = this.viewContainer.createEmbeddedView(this.column.bodyTemplate, this.context);
    };
}`

**Comment by adrienverge** [comment]
I have a very similar problem after updating to 1.1.2.

When changing the data array, changes are not reflected except for new rows added at the end. The bug occurs when inserting rows (with `this.cars.splice()`) but also when completely replacing the data array (with `this.cars = [ ... ]`).

Here is a demonstration of the bug: http://plnkr.co/edit/6BvfsmCkIvXfvKYBc0hT?p=preview

(By the way @wujitouch, I tried your plunker and it seems to work without bugs for me: rows added in the middle are correctly inserted and displayed.)

**Comment by ragafus** [comment]
I also have this problem with dynamic objects. It's still happening in version 1.1.3

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
