### ISSUE TITLE
p-table & p-columnfilter - Error on console and matchmode not show correctly when using [filters]

### ISSUE THREAD

**Issue by igore13** [primefaces/primeng#16452]
### Describe the bug

Hello,

I get this error on the console : ERROR TypeError: ctx_r0.filterConstraint is undefined

you can reproduce that with exemple table (filter basic) in documentation PrimeNG V17.

If you remove a code with p-column-filter template, no error show.

### Environment

Windows 10 Pro

### Reproducer

https://stackblitz.com/edit/cpsrep-nmczjk?file=src%2Fapp%2Fdemo%2Ftable-filter-row-demo.html,src%2Fapp%2Fdemo%2Ftable-filter-row-demo.ts

### Angular version

18.1.4

### PrimeNG version

17.18.11

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.1

### Browser(s)

Firefox

### Steps to reproduce the behavior

1 => Code
Add in HTML p-table :

[filters]="filters"

And in TS :

public filters: {[key: string]: FilterMetaData} = {}
constructor() {
    setTimeout(() => {
        this.filters = {
            name: { value: 'Test', matchMode: 'Equals' }
        }
    }, 5000)
}
2 => Wait 5 seconds and look other filters matchmode

**Comment by igore13** [comment]
I have send a PR : https://github.com/primefaces/primeng/pull/16453

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primeng/pull/16453
