### ISSUE TITLE
Component: MenuBar

### ISSUE THREAD

**Issue by Avantifer** [primefaces/primeng#16450]
### Describe the bug

There is no breakpoint or responsive
![image](https://github.com/user-attachments/assets/ff934c19-4760-4ad0-add9-91f59fbc1431)

### Environment

Local

### Angular version

18.2.5

### PrimeNG version

18.0.0-beta.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.17.0

**Comment by cetincakiroglu** [comment]
Fixed in https://v18.primeng.org/menubar
