### ISSUE TITLE
Improve Growl long message handling

### ISSUE THREAD

**Issue by FallenRiteMonk** [primefaces/primeng#1646]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
With a longer detail text in a growl, the ```ui-growl-message``` div gets pushed under the ```ui-growl-image fa fa-2x fa-close``` span:
![false](https://cloud.githubusercontent.com/assets/8779846/21369478/6b9e1b74-c707-11e6-82e7-c829454f0691.png)

**Expected behavior**
The div should stay in the same position it is with a short detail, just with two lines
Example short detail:
![right](https://cloud.githubusercontent.com/assets/8779846/21369508/96c90728-c707-11e6-9711-a4f5a7f5855b.png)
As it used to be before 1.1 (Using 1.0.1 it works fine)

**Minimal reproduction of the problem with instructions**
To reproduce just show a growl with a bit longer text (the exact character count is not known)
ex.: ```messageList.push({ severity: 'warn', summary: 'Error Message', detail: 'Validation failed Validation failed Validation failed' });```

* **Angular version:** 2.0.X
2.2.3

* **PrimeNG version:** 2.0.X
1.1.0

**Comment by Skuriles** [comment]
Same problem here with Angular 2.4.2 and primeng 1.1.4!
Think the title and the message should be splitted and not packed in "ui-growl-message"

**Comment by cagataycivici** [comment]
Growl is removed in favor of Toast.
