### ISSUE TITLE
Wrong hover color in outline button (New theming)

### ISSUE THREAD

**Issue by d-eder** [primefaces/primeng#16463]
### Describe the bug

We are setting the `hoverColor` property in the button component style:
```
    button: {
      colorScheme: {
        light: {
          outlined: {
            primary: {
              ...
              hoverColor: '{content.white}'
            }
          } ...
```

In the screenshot you can see, that the variable `--p-button-outlined-primary-color` is used for the color. 
Since the element is hovered, the variable `--p-button-outlined-primary-hover-color`  should be used instead.

![image](https://github.com/user-attachments/assets/13681c52-7783-49dc-93ef-d70d191f0b1e)

### Environment

* Local environment using ng serve
* Customized theming (with Lara Theme as default preset) 

### Angular version

18.2.5

### PrimeNG version

18.0.0-beta.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.17.0

### Steps to reproduce the behavior

1. Override the button styles for the inline button
2. Set the property hoverColor to a different color
3. Hover the button in the browser -> the wrong text color is used

### Expected behavior

The correct hover color should be used (as mentioned above, the css variable `--p-button-outlined-primary-hover-color`  should be used with the css hover selector

**Comment by cagataycivici** [comment]
I don't see a **hoverColor** in the outlined button tokens, outlined buttons and regular buttons are different, outlined button removes background so should not use text colors from the regular colors. I don't understand the issue. So this token does not exist;

```
button.outlined.primary.hover.color

button: {
      colorScheme: {
        light: {
          outlined: {
            primary: {
              ...
              hoverColor: '{content.white}'
            }
          } ...
```
