### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by raboud** [primefaces/primeng#16475]
### Describe the bug

PrimeNG V18.0.0-Beta.2 Documentation Error. On the intstallation page. 

provideAnimationAsync should be provideAnimationsAsync (3 instances)

### Environment

Documentation

### Angular version

18.2.4

### PrimeNG version

v18.0.0-Beta.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.16.0

**Comment by sake12** [comment]
Correct:
![image](https://github.com/user-attachments/assets/3ad41afa-770f-4f32-a4b1-12f8e6a091de)

**Comment by AStoker** [comment]
Also confirming the typo. Check out the Angular documentation for the method: https://angular.dev/guide/animations#enabling-the-animations-module

**Comment by mertsincan** [comment]
Fixed for next version.
