### ISSUE TITLE
Breadcrumb v18: Nested links when using template

### ISSUE THREAD

**Issue by TaneliTuomola** [primefaces/primeng#16478]
### Describe the bug

There will be a link inside another link when using template structure with the breadcrumb component. 
<img width="345" alt="image" src="https://github.com/user-attachments/assets/7a66308e-1215-4bbb-8153-999aac4d595f">

### Environment

https://v18.primeng.org/breadcrumb#template

### Angular version

18.0.5

### PrimeNG version

18.0.0-beta.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22.6.0

### Steps to reproduce the behavior

https://v18.primeng.org/breadcrumb#template

### Expected behavior

https://primevue.org/breadcrumb/#template

**Comment by cetincakiroglu** [comment]
Hi,

Thanks a lot for reporting this issue!

**Comment by cetincakiroglu** [comment]
Fixed in https://github.com/primefaces/primeng/commit/c9d9cb029c8d7096008b426419f50731620e6daf
