### ISSUE TITLE
Primeng v18.beta-2 | Firefox - Switching to dark theme doesn't work

### ISSUE THREAD

**Issue by GitStorageOne** [primefaces/primeng#16471]
### Describe the bug

[https://primeng.org](https://primeng.org) (17.18.11) - Switching to dark theme works.
[https://v18.primeng.org](https://v18.primeng.org) (beta.2) - Switching to dark theme doesn't work (even after cleaning browser cache).
(no issues with beta.1)

### Environment

No environment - issue reproduced with v18.primeng.org.

### Angular version

18.0.1

### PrimeNG version

18.0.0-beta-2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Browser(s)

Firefox 130.0.1; 131

### Steps to reproduce the behavior

1. Use Firefox 131.
2. Go to [https://v18.primeng.org](https://v18.primeng.org) (beta.2)
3. Try to enable dark theme.
4. Nothing happens.

### Expected behavior

Dark theme should work.

**Comment by cetincakiroglu** [comment]
Hi,

Thanks a lot for testing the beta and reporting the issue!

**Comment by cetincakiroglu** [comment]
Fixed in https://github.com/primefaces/primeng/commit/e86e14878fb926e864313e51153c3f14e3686a2b
