### ISSUE TITLE
'p-buttonGroup' is not a known element in 18.0.0-beta.2

### ISSUE THREAD

**Issue by OleksiiPrykhodko** [primefaces/primeng#16488]
### Describe the bug

The button group can't be used in 18.0.0-beta.2

'p-buttonGroup' is not a known element:
1. If 'p-buttonGroup' is an Angular component, then verify that it is included in the '@Component.imports' of this component.
2. If 'p-buttonGroup' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@Component.schemas' of this component to suppress this message.ngtsc(-998001)

### Environment

Windows

### Reproducer

https://primeng.org/button#buttongroup

### Angular version

18.0.0

### PrimeNG version

18.0.0-beta.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.13.1

### Browser(s)

Any

### Steps to reproduce the behavior

1) Go to https://primeng.org/button#buttongroup and cope the HTML
2) And it to the component and import ButtonModule. 
3) See the error.

### Expected behavior

The ButtonGroup module can be imported and the p-ButtonGroup be used.

**Comment by Gangz1o** [comment]
yes, got the same issue as below:
<img width="1291" alt="image" src="https://github.com/user-attachments/assets/9b46bba6-e85f-4f99-aa77-5d7d73cdfe77">

**Comment by cetincakiroglu** [comment]
Fixed in https://github.com/primefaces/primeng/commit/a40bb5d49d048daffd74d9059d6c3527a9aad494

**Comment by zakharenkov** [comment]
Reproduced in 18.0.0-beta.3

**Comment by 3San360** [comment]
facing the same issue in 18 beta 2 version

**Comment by IvanBanifatsyeu** [comment]
add import { ButtonGroupModule } from 'primeng/buttongroup';

**Comment by beklife** [comment]
still same issue

**Comment by rubenheymans** [comment]
for me I also had my buttons wrapped in another div so I have this css in my button-group component:
```
:host ::ng-deep {
  .p-buttongroup .p-button,
  .p-buttongroup portal-button .p-button {
    margin: 0;
  }

  .p-buttongroup .p-button:not(:last-child),
  .p-buttongroup .p-button:not(:last-child):hover,
  .p-buttongroup portal-button:not(:last-child) .p-button,
  .p-buttongroup portal-button:not(:last-child) .p-button:hover {
    border-right: 0 none;
  }

  .p-buttongroup .p-button:not(:first-of-type):not(:last-of-type),
  .p-buttongroup portal-button:not(:first-of-type):not(:last-of-type) .p-button {
    border-radius: 0;
  }

  .p-buttongroup .p-button:first-of-type:not(:only-of-type),
  .p-buttongroup portal-button:first-of-type:not(:only-of-type) .p-button {
    border-start-end-radius: 0;
    border-end-end-radius: 0;
  }

  .p-buttongroup .p-button:last-of-type:not(:only-of-type),
  .p-buttongroup portal-button:last-of-type:not(:only-of-type) .p-button {
    border-start-start-radius: 0;
    border-end-start-radius: 0;
  }

  .p-buttongroup .p-button:focus,
  .p-buttongroup portal-button .p-button:focus {
    position: relative;
    z-index: 1;
  }

  .p-buttongroup {
    display: flex;
  }

  .p-buttongroup > .p-button,
  .p-buttongroup > portal-button .p-button {
    flex: 1;
  }
}
```
