### ISSUE TITLE
 PickList v18: The direction of the controls remains upright on narrow screens

### ISSUE THREAD

**Issue by TaneliTuomola** [primefaces/primeng#16481]
### Describe the bug

<img width="340" alt="image" src="https://github.com/user-attachments/assets/11794127-dadf-4393-b157-5416d5b905c0">
Flex direction of the controls is always "column".

### Environment

https://v18.primeng.org/picklist

### Reproducer

https://v18.primeng.org/picklist

### Angular version

18.0.5

### PrimeNG version

18.0.0-beta.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22.6.0

### Steps to reproduce the behavior

https://v18.primeng.org/picklist

### Expected behavior

https://primevue.org/picklist

**Comment by cetincakiroglu** [comment]
Fixed in https://github.com/primefaces/primeng/commit/75348a61a6ab2703abc5029fa118921c67eab929

**Comment by TaneliTuomola** [comment]
Now its not responsive at all and does not get stacked on narrow screens like on PrimeVue: https://primevue.org/picklist/ @cetincakiroglu
