### ISSUE TITLE
Dropdown default value

### ISSUE THREAD

**Issue by Serginio1** [primefaces/primeng#1649]
```
updateSelectedOption(val: any): void {
        this.selectedOption = this.findOption(val, this.optionsToDisplay);
        if(!this.selectedOption && this.optionsToDisplay && this.optionsToDisplay.length && !this.editable) {
            this.selectedOption = this.optionsToDisplay[0];
            this.value = this.selectedOption.value; // set default value
        }
        this.selectedOptionUpdated = true;
    }
```

When add dynamic data changes label

**Comment by kt215** [comment]
What's your question/issue exactly?

**Comment by Serginio1** [comment]
When creating a component in the existing list when an item is selected, the value is not set, and when a new value in the top of the list is added to the list, the component changes the selected value to the new. Here's a link to my changehttps://github.com/Serginio1/Angular2SignalrCore/blob/master/Angular2SignalrCore/ClientApp/app/components/dropdown/dropdown.тсngDoCheck () {         let changes = this.differ.diff (this.options);                 if (changes && this.initialized) {             this.optionsToDisplay = this.options;             this.updateSelectedOption (this.value); // Value === unassigned             this.optionsChanged = true;         }     }selectItem (event, option) {         this.selectedOption = option;         this.value = option.value;!!!                         this.onModelChange (this.value);         this.onChange.emit ({             originalEvent: event,             value: this.value         });     }  updateSelectedOption(val: any): void {        this.selectedOption = this.findOption(val, this.optionsToDisplay);        if(!this.selectedOption && this.optionsToDisplay && this.optionsToDisplay.length && !this.editable) {            this.selectedOption = this.optionsToDisplay[0];            this.value = this.selectedOption.value; // And the need to set the value of the selected item is similar selectItem                        }        this.selectedOptionUpdated = true;    }I apologize. I use Google translator29.12.2016, 02:05, "Ken" <notifications@github.com>:What's your question/issue exactly?

**Comment by Serginio1** [comment]
When creating a component in the existing list when an item is selected, the value is not set, and when a new value in the top of the list is added to the list, the component changes the selected value to the new. Here's a link to my  change  https://github.com/Serginio1/Angular2SignalrCore/blob/master/Angular2SignalrCore/ClientApp/app/components/dropdown/dropdown.ts

```
ngDoCheck () {         let changes = this.differ.diff (this.options);                
   if (changes && this.initialized) { 
            this.optionsToDisplay = this.options;  
           this.updateSelectedOption (this.value); // Value === unassigned            
           this.optionsChanged = true;         }     }


```
```
selectItem (event, option) { 
        this.selectedOption = option;        
       this.value = option.value; !!! set value
       this.onModelChange (this.value);
        this.onChange.emit ({   
          originalEvent: event,
             value: this.value         });     }  

updateSelectedOption(val: any): void { 
       this.selectedOption = this.findOption(val, this.optionsToDisplay);
        if(!this.selectedOption && this.optionsToDisplay && this.optionsToDisplay.length && !this.editable) {           
 this.selectedOption = this.optionsToDisplay[0];
  this.value = this.selectedOption.value; // And the need to set the value of the selected item is similar selectItem                        }     
   this.selectedOptionUpdated = true;    }

```
I apologize. I use Google

**Comment by jolee11** [comment]
When I programmatically change the value of dropdown, 
I need to change the code of components/dropdown/dropdown.js as follows:

Dropdown.prototype.updateSelectedOption = function (val) {
    this.selectedOption = this.findOption(val, this.options);
    this.selectedOptionUpdated = true;
};

Otherwise, primeng keep displaying previous selected option!
By the way, is there any way to clear the filter string programmatically?

Thank you very much!

**Comment by cagataycivici** [comment]
Please use forum for questions. There is resetFilter() method that you can use.

**Comment by marekdano** [comment]
How can I use resetFilter() method in my component? Do you have a sample implementation how I can call resetFilter() method in my component?

**Comment by aguher** [comment]
If you put a placeholder for the p-dropdown, you can reset  putting a null value inside the model. Example:
<p-dropdown placeholder="Selecciona un valor" [(ngModel)]="filter"></p-dropdown>

Then create a method to clean the 'filter' value, and the dropdown will show the placeholder value again.
