### ISSUE TITLE
Picklist: Movebottom Button has wrong aria label

### ISSUE THREAD

**Issue by e-matthaey** [primefaces/primeng#16498]
The Movebottom Button in the picklist component references the wrong aria label. 
Instead of 'Move Down' it should be 'Move Bottom'.

![picklist](https://github.com/user-attachments/assets/d0b3abee-0625-4d7b-8cc6-d37b3b594d12)

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primeng/pull/16497
