### ISSUE TITLE
Issue with Dropdown component doesn't keep the height of option overlay

### ISSUE THREAD

**Issue by cdskill** [primefaces/primeng#16492]
### Describe the bug

When using a dropdown component with thousand of items, then activate the virtual scroll options AND filtering feature, once u type the search term it correctly filters options but if u pressing backspace to remove search term, the overlay remains little.

See the video attached.

https://github.com/user-attachments/assets/414305c2-2609-46e2-8f2b-1c4bbfa22003

### Environment

stackblitz

### Angular version

18.0.1

### PrimeNG version

17.18.11

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.20.3

### Steps to reproduce the behavior

1. use the stackblitz from primeng doc about virtual scroll
2. add filter=true

### Expected behavior

keep the original size of the options

**Comment by Mallette** [comment]
Related to https://github.com/primefaces/primeng/issues/16457
