### ISSUE TITLE
TimePicker Component

### ISSUE THREAD

**Issue by CoveTechnologyAus** [primefaces/primeng#165]
Hi Guys
Is there any plan for a TimePicker component? This would be a handy component for quick time entry on forms that utilize PrimeNG and is probably my only stumbling block for using PrimeNG in our upcoming TimeTracker application.

Thanks in advance.

**Comment by anikets43** [comment]
@CoveTechnologyAus You can have look on [http://valor-software.com/ng2-bootstrap/#timepicker](url) if your development is blocked due to timepicker component.

**Comment by cagataycivici** [comment]
Yes, we'll have it for 1.0.0-beta.1 in a couple of days. It will be like the ones with time;

http://www.primefaces.org/showcase/ui/input/calendar.xhtml

**Comment by cagataycivici** [comment]
Almost done
<img width="320" alt="screen shot 2016-04-07 at 13 34 25" src="https://cloud.githubusercontent.com/assets/686247/14348492/824550fc-fcc5-11e5-8ab2-6fbd9ced5738.png">

**Comment by cagataycivici** [comment]
Available now for 1.0.0-beta.1
