### ISSUE TITLE
Dropdown opens using ctrl + alt + any key

### ISSUE THREAD

**Issue by gaurav-shinde-ptc** [primefaces/primeng#16504]
### Describe the bug

When we fucus on an P dropdown using tab, it should open dropdown when we click enter after focusing the element. But when we click ctrl + alt + any key it expands the dropdown. Some keys are reserved for other operations in our application and this behavior is blocking those operations. Is there any way to suppress this?

### Environment

Development 

### Angular version

17.3.6

### PrimeNG version

17.18.5

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.12.10

### Steps to reproduce the behavior

1. Go to https://primeng.org/dropdown
2. Focus on dropdown using tab key
3. Press ctrl + alt + any key
4. This will open the dropdown

### Expected behavior

Dropdown should expand only by pressing enter key

**Comment by mertsincan** [comment]
This issue is not related to PrimeNG core. please use PrimeNG discord channel/discussion for such questions.

Best Regards,
