### ISSUE TITLE
Scrollpanel: Scrollbar in wrong position on initial load

### ISSUE THREAD

**Issue by felixoehler** [primefaces/primeng#16508]
### Describe the bug

On initial load the scrollbar isn't located correctly and is usually offset by quite a margin. If there shouldn't be a scrollbar at all it still displays. 
The issue goes away as soon as you hover over the Scrollpanel component.

### Environment

@angular/core 17.3.12
primeng 17.18.11

Chrome or Edge

I did observe the issue in various different applications as well es your own documentation

### Angular version

17.3.12

### PrimeNG version

17.18.11

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.12.2

### Browser(s)

Chrome 129.0.6668.90, Edge 129.0.2792.79

### Steps to reproduce the behavior

Load the Scrollpanel documentation: https://primeng.org/scrollpanel
Scroll down to the Custom section where you can actually see the scrollbar
Observer the scrollbar being way to the right of where they should be.

Screenshot for reference of what I'm seeing:
![image](https://github.com/user-attachments/assets/04192c98-730f-452b-b8bc-6799eb14e33f)

### Expected behavior

Scrollbar should display in the correct position on initial load already.
Scrollbar should display at all if it is not needed also on initial load already.

**Comment by felixoehler** [comment]
I managed to workaround the issue by calling `ScrollPanelComponent.moveBar()` in my component within `ngAfterViewChecked` lifecycle hook.

**Comment by mertsincan** [comment]
I think this issue has already been fixed for the next version. For now, closed. If the problem persists, please reopen it.
