### ISSUE TITLE
18.0.0-beta2 - ComponentStyles are not exported -> extended Components fail

### ISSUE THREAD

**Issue by DbkMG** [primefaces/primeng#16509]
### Describe the bug

We extend some PrimeNG-Components and while testing the 18.0.0-beta.2 release we get RuntimeErrors because the component-styles are not provided.

We can't provide them ourself because they are not exported via public_api.

### Environment

ng 18
primeng 18.0.0-beta.2

### Angular version

18.2.6

### PrimeNG version

18.0.0-beta.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.1

**Comment by cetincakiroglu** [comment]
Fixed in https://github.com/primefaces/primeng/commit/16c99c8ca63c9abd54594e50c1897daf57dcc6dd
