### ISSUE TITLE
All the rows appear after clicking on row edit

### ISSUE THREAD

**Issue by nouaim** [primefaces/primeng#16516]
### Describe the bug

All the rows appear when i click on the edit button however only one row should be appeared

 https://primeng.org/table#row-edit
 
 I am using Bootstrap instead of primeflex
 
 
![Screenshot from 2024-10-11 10-08-35](https://github.com/user-attachments/assets/4eef4fb8-69d3-4bf5-944a-9228221e40f1)

### Environment

Nx app

### Angular version

18.0.0

### PrimeNG version

17.18.4

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.15.1

### Browser(s)

firefox

**Comment by wS2Zth** [comment]
I think it is not about bootstrap, can you share your implementation?

**Comment by nouaim** [comment]
@wS2Zth thanks a lot for your answer, you are correct. It appeared I didn't update the dataKey in the html (in my Api it is recordId instead of id)

![image](https://github.com/user-attachments/assets/882446fc-987d-4e92-8886-39bd027899cb)
