### ISSUE TITLE
PrimeNG v18 Bug - PanelMenu not working

### ISSUE THREAD

**Issue by EnricoMessall** [primefaces/primeng#16511]
### Describe the bug

Using the panelmenu in the current v18 is not working. Its not expanding its fields. 

When its is fixed there is still an issue that the item toggle is behaving wrongly and just closes some items again even if they should stay open

See: 

https://github.com/user-attachments/assets/049d538b-8fda-4328-9c80-57d7c083ff0f

### Environment

PrimeNG v18

### Angular version

18.0.1

### PrimeNG version

18.0.0-beta.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v22.7.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Go to https://v18.primeng.org/panelmenu
2. Try to expand a menu point
3. Menu point does nothing

### Expected behavior

Menu point expands and shows childs

**Comment by EnricoMessall** [comment]
Hey @cetincakiroglu maybe you can pick that up into the next v18 beta 💯

**Comment by wS2Zth** [comment]
Did not realize, you have already solved it. :3 Thanks @EnricoMessall !

**Comment by cetincakiroglu** [comment]
Fixed in https://github.com/primefaces/primeng/pull/16512
