### ISSUE TITLE
Data Table 'trackBy must be a function, but received undefined'

### ISSUE THREAD

**Issue by agusdutra** [primefaces/primeng#1652]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
I was using primeng 1.0.0 and angular 2.2.1. I've updated primeng to 1.1.1 and angular to 2.4.1

On the last version Datatable worked fine, without the rowTrackBy (I don't need it)
After I updated, the same datatable, without any changes, throws me this error and doesn't render any rows.

**Expected behavior**
Show rows of the data table .

**Minimal reproduction of the problem with instructions**
Use simple datatable primeng on angular 2.4.1 and primeng 1.1.1

Environment: 
WebStorm 2016.3
Angular version: 2.4.1
PrimeNG version:1.1.1
Browser:all

Stack trace: 

<img width="1232" alt="captura de pantalla 2016-12-21 a las 22 55 34" src="https://cloud.githubusercontent.com/assets/12460226/21412659/a179640a-c7d0-11e6-8525-12fdefcabab9.png">

[files.zip](https://github.com/primefaces/primeng/files/667818/files.zip)

**Comment by agusdutra** [comment]
I've reverted my dependencies back to angular 2.2.1 just like it was before, and the table renders with no problem, without any further changes.

**Comment by zhangwei8387** [comment]
I have the same problem. I created a very simple Datatable .
my angular  is 2.4
primeng 1.1.1

error like this.

![primengerror](https://cloud.githubusercontent.com/assets/9648537/21418202/73e3bcc2-c85a-11e6-84c1-0e4fb4b79fd9.png)

**Comment by WispZhan** [comment]
It works in Angular 2.2.1 and Primeng 1.1.1. But Angular 2.4.X does not work.

**Comment by AndreiShostik** [comment]
for me it doesn't work only for UI tests, but app still working

**Comment by bogacg** [comment]
Same here, upgraded to PrimeNg 1.1.1 and Angular 2.4.1, get same error for dataTables

**Comment by Emdee89** [comment]
I can also confirm that it works with PrimeNG 1.1.1 and Angular 2.4.0, however it does break with Angular 2.4.1 then...

**Comment by cagataycivici** [comment]
Created an issue at;

https://github.com/angular/angular/issues/13641

On our side, we can create a dummy function as default value, @Mrtcndkn please do so and release 1.1.2 as DataTable is unusable now with 2.4.1.

**Comment by Mrtcndkn** [comment]
1.1.2 is released it's solving this problem for now

**Comment by ribizli** [comment]
I'm not sure that the default implementation makes it:
```
rowTrackBy: Function = () => {};
```
Because now everything is tracked by `undefined`, which is returned from the function above. Angular uses the identity function as default.
```
trackByIdentity = (index: number, item: any) => item;
```

A haven't had time to test this, but I'm pretty sure this can make some performance problems, since `DefaultIterableDiffer` cannot really track for changes.
