### ISSUE TITLE
table inappropriately displays p-column-title of span

### ISSUE THREAD

**Issue by mohamedsch** [primefaces/primeng#16549]
### Describe the bug

The hidden p-column-title span data is being displayed

### Environment

Windows 10 Pro, VS Code

### Angular version

18.2.2

### PrimeNG version

18.0.0-beta.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.18.0

**Comment by cetincakiroglu** [comment]
Hi,

The issue is unclear. Could you please explain `p-column-title` element? There isn't such an element rendered on screen.
