### ISSUE TITLE
PrimeNG v18 - Extend Card Theming Support

### ISSUE THREAD

**Issue by EnricoMessall** [primefaces/primeng#16557]
Currently without custom templates its hard to create custom paddings and gaps between titles, content and footer. Also its hard to adjust titles. 

These adjustments introduce more token variables to customize paddings and gaps to have a more complete version of cards that can have different paddings between titles, content and footer.

**Comment by cagataycivici** [comment]
I'm afraid we can't add new tokens right now, the tokens are shared between all Prime UI libraries and the Figma UI Kit needs to be updated when a new token is added so it has its own process and timeline. We're currently focused on stability of the theming system not adding new tokens until v18 final. New tokens cannot be added v18.1.0.

For now you can extend it yourself with custom tokens, here is an example from Vue version, same applies to NG;

https://www.youtube.com/watch?v=galIbID_Ywo

However eventually, I think we should add the tokens you mentioned.
