### ISSUE TITLE
Select (v18): overlap between outline and border with invalid state

### ISSUE THREAD

**Issue by jicedtea** [primefaces/primeng#16577]
### Describe the bug

Related: 
https://github.com/primefaces/primeng/pull/16407
https://github.com/primefaces/primeng/commit/bf8423bbc53a02f050846e79bae1dc02cd1ad5a8

Select
![image](https://github.com/user-attachments/assets/58bb50ac-87f8-4148-af42-57970e340f6e)
InputText
![image](https://github.com/user-attachments/assets/e68ea597-d533-4f6d-a401-523402041682)

### Environment

All

### Reproducer

https://v18.primeng.org/select#invalid

### Angular version

Lastest

### PrimeNG version

18

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

Lastest

**Comment by cagataycivici** [comment]
It works as intended in PrimeVue version, we should check other form components for this as well. Thank you for the heads up.
