### ISSUE TITLE
[Enhancement/Feature] Calendar should hide values out of range when dates are restricted

### ISSUE THREAD

**Issue by arossi90** [primefaces/primeng#1660]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
As title says, it would be great if calendar could hide the values when using restricted dates, and also navigators with unselectable values. Pretty much as it worked before when calendar component was based on jquery datepicker.
From the example page, http://www.primefaces.org/primeng/#/calendar , you can see (and navigate through) all the months and years current available in the calendar component, even though they're not selectable.

**Comment by cagataycivici** [comment]
Will check with the jquery version, thank you.

**Comment by yigitfindikli** [comment]
We'll reconsider if there is more community feedback on this. Thank you for your report.
