### ISSUE TITLE
PrimeNG Filter: No way to localise prime-ng filter content

### ISSUE THREAD

**Issue by MahimaFullStack** [primefaces/primeng#16608]
### Describe the bug

PrimeNG Filter: No way to localise prime-ng filter content

![Filters_Reporting_Export_page](https://github.com/user-attachments/assets/f3fb574c-dd18-4042-9642-8e6258adf470)

### Environment

Angular application using filters in Grid controls

### Angular version

"@angular/cdk": "^15.2.9",     "@angular/common": "^15.2.9",     "@angular/compiler": "^15.2.9",     "@angular/core": "^15.2.10",

### PrimeNG version

"primeng": "^15.4.1",

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22.7.0

### Browser(s)

Chrome

### Expected behavior

PrimeNG Filter: No way to localise prime-ng filter content

Content for Filter not getting localised

**Comment by mertsincan** [comment]
Also, please check https://primeng.org/configuration#locale
