### ISSUE TITLE
Table | Bug on table checkboxes

### ISSUE THREAD

**Issue by mehmetcetin01140** [primefaces/primeng#16618]
https://stackblitz.com/edit/bfqnfa?file=src%2Fapp%2Ftable-checkbox-selection-demo.html%3AL22

**Comment by MaurizioCasciano** [comment]
Hi @mehmetcetin01140, does this fix also https://github.com/primefaces/primeng/issues/15780 ?

**Comment by AvshT** [comment]
Hi, solving this bug causes a significant performance issue here:
![image](https://github.com/user-attachments/assets/3d0e8514-d37d-4af0-a6d9-11238baf72a4)
The subscription is triggered multiple times with each checkbox click.
To reproduce the issue, click the "Check All" checkbox and then uncheck it again.

**Comment by LoaderB0T** [comment]
@AvshT do I have smth to do with that? :)
