### ISSUE TITLE
Can Paginator do that?

### ISSUE THREAD

**Issue by shi1hh** [primefaces/primeng#1661]
like this
![20161222214458](https://cloud.githubusercontent.com/assets/15082157/21427663/d569d25c-c890-11e6-8633-d413f1b0dddb.png)
![20161222214502](https://cloud.githubusercontent.com/assets/15082157/21427666/d653729a-c890-11e6-97f0-631b1d26dc9d.png)

**Comment by Mrtcndkn** [comment]
Please use forum for questions and support requests instead of issue tracker.

**Comment by pantonis** [comment]
@shi1hh Did you find a way of doing this?
