### ISSUE TITLE
Component: Table — misaligned table-like footer

### ISSUE THREAD

**Issue by mateuszchmielewski** [primefaces/primeng#16614]
### Describe the bug

When using footer template on table component as a last row, the columns are misaligned. It looks like the footer is not part of the main table. Possibly because it's wrapped with the following div element:
```
<div class="p-datatable-footer">
     <tr>...</tr>
</div>
```

It's observable in the official example:
![obraz](https://github.com/user-attachments/assets/6f74563d-35d9-4741-87cf-cde66bcf42a3)
Source: https://v18.primeng.org/table#horizontal-scroll

### Environment

**OS**
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19045 N/A Build 19045

### Angular version

18.2.8

### PrimeNG version

18.0.0-beta.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22.9.0

### Browser(s)

Chrome, Firefox

### Expected behavior

Footer columns should be aligned with the main table columns.

**Comment by cetincakiroglu** [comment]
fixed in https://github.com/primefaces/primeng/commit/26d492bbdb009f94b916e2a3d5678a170a0c78fd
