### ISSUE TITLE
DOCS treeTable: Typo in the selector of p-treeTableToggler

### ISSUE THREAD

**Issue by qwadrox** [primefaces/primeng#16628]
### Describe the bug

```diff
- <p-treetableToggler [rowNode]
+ <p-treeTableToggler [rowNode]
```
The name should be camelCase at the referenced places. 

### Environment

-

### Angular version

18

### PrimeNG version

18.0.0-beta.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

-

**Comment by cetincakiroglu** [comment]
fixed in https://github.com/primefaces/primeng/pull/16629
