### ISSUE TITLE
Tabs v18: Missing p-tab-active class

### ISSUE THREAD

**Issue by TaneliTuomola** [primefaces/primeng#16627]
### Describe the bug

The active tab does not get the right design when it lacks a style class: "p-tab-active".
<img width="405" alt="image" src="https://github.com/user-attachments/assets/391c2a0c-c5d2-496b-ad7b-59082b67a353">
Here is the style class set via developer tools:
<img width="403" alt="image" src="https://github.com/user-attachments/assets/f83bf934-5fa9-42f9-8ff6-f1633d2f2e72">

### Environment

https://v18.primeng.org/tabs

### Reproducer

https://v18.primeng.org/tabs

### Angular version

18.0.5

### PrimeNG version

18.0.0-beta.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22.8.0.

### Steps to reproduce the behavior

https://v18.primeng.org/tabs

### Expected behavior

https://primevue.org/tabs/

**Comment by cetincakiroglu** [comment]
Hi,

Thanks a lot for testing the beta and reporting the issue! Fixed in https://github.com/primefaces/primeng/commit/2924ff540df4cdbf5412e5449115edaf93a02fec
