### ISSUE TITLE
Component: Auto Complete - with Force Selection, selected option is overriding with the matched value 

### ISSUE THREAD

**Issue by dpeese** [primefaces/primeng#16625]
### Describe the bug

When Force Selection is enabled, if we have options like below, on entering "Afghanistan" and selecting option "Afghanistanb" is still emitting "Afghanistan" instead of "Afghanistanb". It is only happening for the first time
Ex:
Afghanistan
Afghanistana
Afghanistanb

### Environment

primeng
nodejs
angular

### Reproducer

https://stackblitz.com/edit/632ydq?file=src%2Fapp%2Fautocomplete-reactive-forms-demo.ts,src%2Fservice%2Fcountryservice.ts,src%2Fapp%2Fautocomplete-reactive-forms-demo.html

### Angular version

18

### PrimeNG version

17.18.11

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Browser(s)

chrome

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primeng/pull/16649
