### ISSUE TITLE
PickList v18: PickList layout remains horizontal with narrow screens

### ISSUE THREAD

**Issue by TaneliTuomola** [primefaces/primeng#16626]
### Describe the bug

After fix #16482, the whole layout of the pickList component does not change when the screen size changes. The direction of the buttons icons does change.
https://v18.primeng.org/picklist
vs.
https://primevue.org/picklist/

### Environment

https://v18.primeng.org/picklist

### Angular version

18.0.5

### PrimeNG version

18.0.0-beta.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22.6.0

### Steps to reproduce the behavior

Change window size of the browser: https://v18.primeng.org/picklist

### Expected behavior

https://primevue.org/picklist/

**Comment by cetincakiroglu** [comment]
Hi,

Thanks a lot for testing the beta and giving us feedback. We've fixed it in https://github.com/primefaces/primeng/commit/c77ea0202fd052386336273549e1fe155b734898
