### ISSUE TITLE
p-picklist Filter stop working in v18 beta-3

### ISSUE THREAD

**Issue by joangilabert94** [primefaces/primeng#16622]
### Describe the bug

After update to v18 beta 3 the filter in p-picklist stop working

### Environment

Angular 18.2.8
PrimeNG: 18.0.0-beta.3

### Angular version

18.2.8

### PrimeNG version

18.0.0-beta.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.15.0

### Browser(s)

All

### Steps to reproduce the behavior

Create simple p-picklist:

`
<p-picklist [source]="sourcePicklist" [target]="targetPicklist" sourceHeader="Available" targetHeader="Selected"
    [dragdrop]="true" [sourceStyle]="{ height: '30rem' }" [targetStyle]="{ height: '30rem' }" filterBy="label">
      <ng-template pTemplate="item" let-item>
      <div>
        {{item.value}} - {{item.label}}
      </div>
    </ng-template>
  </p-picklist>
`

![image](https://github.com/user-attachments/assets/0dd45857-b6a4-4cc7-b4fb-963e5e0e5d87)
![image](https://github.com/user-attachments/assets/b9f74f13-646e-486d-8375-09fc7ec3baf5)

### Expected behavior

Filter works

**Comment by Amalkrish09** [comment]
sourcePick=signal<any[]>([]);
 <input
        type="text"
        (keyup)="filter($event)"
        role="textbox"
        class="p-picklist-filter-input p-inputtext p-component"
      />
      
       filter(event: any) {
    this.sourcePick.set(this.sourcePicklist.filter(x => x.label.toLowerCase().includes(event.target.value.toLowerCase())));
   }
I resolved this issue by implementing a custom method.

**Comment by sharonmoriel** [comment]
I'm also using version 18 and I've just run into the same issue and found a temporary solution. It appears that when using the filterBy parameter, the only working string is "name", so renaming my filter property from what I had (and used to work, i.e. `label`) to `name`, made the filtering work just fine. Perhaps the `name` value is accidentally hardcoded.
