### ISSUE TITLE
Component: Password input pPassword meter does not update in v18 beta 2 version

### ISSUE THREAD

**Issue by 3San360** [primefaces/primeng#16632]
### Describe the bug

Component: Password input pPassword meter does not update in v18 beta 2 version

### Environment

v18 beta 2

### Angular version

18

### PrimeNG version

18 beta 2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20

**Comment by cetincakiroglu** [comment]
fixed in https://github.com/primefaces/primeng/commit/ec4914f6a978c19b6951c1291c39304a0577a5bb
