### ISSUE TITLE
Contributing to primeng

### ISSUE THREAD

**Issue by harilal** [primefaces/primeng#1664]
**I'm submitting a ...**  (check one with "x")
I Would like to contribute to the primeng.
Couldn't find any thing usefull.
except https://github.com/primefaces/primeng/wiki/Building-From-Source

As a beginner no idea where to start working on? 
Do i need to work on the master branch?
Do i need to commit package.json?
Since it's been said to add the dependencies in the above link?

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by wujitouch** [comment]
This is what you do:

1. Fork the repo.
2. Check out a copy of your fork.
3. Create a very specific issue (very small change).
4. Fix it and update the showcase with the fix or create a plunkr if it doesn't belong in the showcase showing that it works.
5. Create a pull request referencing that issue.

Just so you know, you can't make real (big) changes. It's against their company policy to allow outside significant changes. Trust me, I tried...

**Comment by Mrtcndkn** [comment]
Thanks for explanation.
