### ISSUE TITLE
Component: Drawer does not render footer template

### ISSUE THREAD

**Issue by adamlwomble** [primefaces/primeng#16641]
### Describe the bug

The Drawer component does not display the footer template; looking at its source, the template appears to be the problem because it references `_footerTemplate` (lines 90 and 92) where the component class declares the property as `footerTemplate` (line 293).

### Environment

macOS Sequoia 15.0.1
Unix shell (Zsh)

### Angular version

~18.2.0

### PrimeNG version

18.0.0-beta.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.18.0

### Steps to reproduce the behavior

1. Implement an instance of the Drawer component
2. Within the `<p-drawer>` opening and closing tags, include `<ng-template pTemplate="footer">Footer</ng-template>`
3. Verify the text “Footer” is neither displayed in the view nor rendered in the DOM.

### Expected behavior

1. Implement an instance of the Drawer component
2. Within the `<p-drawer>` opening and closing tags, include `<ng-template pTemplate="footer">Footer</ng-template>`
3. Verify the text “Footer” is both displayed in the view and rendered in the DOM.

**Comment by cetincakiroglu** [comment]
Hi,

Thanks a lot for testing the beta and giving us feedback. This issue is fixed in https://github.com/primefaces/primeng/commit/57adb2b8d58127721602b79d226f77b526025c80
