### ISSUE TITLE
Row selection should be on a tap event instead of a touchstart.

### ISSUE THREAD

**Issue by samuellaplante** [primefaces/primeng#1666]
**I'm submitting a **
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
When we scroll a datatable on a mobile device, it triggers selection handler, because of the (touchstart) event on the <tr> element. 

**Expected behavior**
It should be a (tap) event to be sure the user really intended to select the row

**Minimal reproduction of the problem with instructions**
I did a pull request that correct the behaviour.

**Please tell us about your environment:**
Android or IOS

* **Angular version:** 2.0.1

* **PrimeNG version:** 1.0.1

* **Browser:** [all]

 
* **Language:** [all]

**Comment by kt215** [comment]
I've tried reproducing this on both the latest Chrome browser on Android, and latest Safari on iOS, and I'm not seeing a problem with the current implementation. Can you please create a plunkr for this?

**Comment by cagataycivici** [comment]
We need more feedback on this, if there is more demand we'll consider the change, until now we haven't received many. Some seem to prefer touchstart which is like mousedown.
