### ISSUE TITLE
Dynamic dialog: header text is bugged

### ISSUE THREAD

**Issue by MykolaSirko1** [primefaces/primeng#16666]
### Describe the bug

I am using DialogService to open my component:

```typescript
onModal() {
    this.dialogService.open(ModalComponent, {
      header: 'Modal header',
      width: '500px',
      style: { background: 'transparent' },
      modal: true,
      closable: true,
    });
  }
``` 

the problem is when option `closable: true` is added, then when the modal window is opened for the first time, the following text is displayed in the header instead of what is specified in the options:
<img width="501" alt="image" src="https://github.com/user-attachments/assets/3a18c412-f285-4365-990e-f3bd29cf8530">

On subsequent openings, the text becomes correct:

<img width="473" alt="image" src="https://github.com/user-attachments/assets/2d824dee-56a2-4585-ba0f-21b388421fb3">

### Environment

Development

### Angular version

18.2.3

### PrimeNG version

18.0.0-beta.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Expected behavior

Header text is correct

**Comment by Zeck-Koay** [comment]
Hi, I created example based on the Issue Template. 
[https://stackblitz.com/edit/github-sqieue](https://stackblitz.com/edit/github-sqieue)
