### ISSUE TITLE
Theming v18: when a primitive is declared with a value of number, it always adds 'px' when used as scope token

### ISSUE THREAD

**Issue by jogerj** [primefaces/primeng#16668]
### Describe the bug

Given a theme declares a primitive value
```ts
const myTheme = definePreset(Aura, {
  primitive: {
    font: {
      bold: 700, // or '700', doesn't matter
    },
  },
  components: {
    button: {
      label: {
        fontWeight: '{font.bold}',
      },
    },
  },
});
```

the css variable always adds 'px' so that the value of `--p-font-bold` is `700px`. This is unusable for case of font weight.

### Environment

any

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-3h9lr2?file=src%2Fmain.ts

### Angular version

^18.1.0

### PrimeNG version

18.0.0-beta.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.20.3

### Steps to reproduce the behavior

use the variable as a scope token

### Expected behavior

does not add 'px' unless value specified 

should behave like in [tailwindcss](https://tailwindcss.com/docs/font-weight) applying class `font-bold`

**Comment by mertsincan** [comment]
Thanks a lot for your report! Fixed in `@primeuix/styled` package.
