### ISSUE TITLE
Component: Textarea, style is not being applied. 

### ISSUE THREAD

**Issue by saloiofun** [primefaces/primeng#16678]
### Describe the bug

The textarea component is not working with `pTextarea` directive. 

### Environment

Local and on stackblitz 

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-bxbgpx?file=src%2Fmain.ts

### Angular version

18.1.0

### PrimeNG version

18.0.0-beta.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.0.0

**Comment by LMatass** [comment]
+1

Any news here?

**Comment by saloiofun** [comment]
Importing `TextareaModule` worked. 
`import { TextareaModule } from 'primeng/textarea;` 

Created a PR to update the docs.
PR: https://github.com/primefaces/primeng/pull/16730
