### ISSUE TITLE
Component: Calendar

### ISSUE THREAD

**Issue by paweell5808** [primefaces/primeng#16686]
### Describe the bug

The date attribute ‘data-date’ contains an incorrect value for the month; it should be 11 instead of 10. The error is due to the month values being counted from 0 instead of 1.

### Environment

Angular 17, Google Chrome v130.0.6723.92

### Angular version

17.3.11

### PrimeNG version

17.17.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.15.0

### Browser(s)

Google Chrome v130.0.6723.92

### Steps to reproduce the behavior

![Zrzut ekranu 2024-11-04 104646](https://github.com/user-attachments/assets/77719f91-06a4-487a-a4ed-676f84d7f304)

**Comment by mertsincan** [comment]
Is this issue fixed?

**Comment by paweell5808** [comment]
I checked on StackBlitz with latest version 17.18.12 and it still doesn't work.

![image](https://github.com/user-attachments/assets/83556095-aa20-45e8-a22e-8aa78679274e)

**Comment by pointers-enjoyer** [comment]
After I searched source code for 17.18.12, it seems a commit has passed that reverted my solution.
Commit: 59b0d276025a81b8fd4b2c7c92211f7f25178e9f

This commit was created after I pushed solution for this issue, on another issue branch (https://github.com/primefaces/primeng/pull/16690/commits)

Should I push this again?

**Comment by paweell5808** [comment]
Please keep in mind to also implement this fix in higher versions, e.g. 18
