### ISSUE TITLE
Angular 2.4.1 breaks DataTable

### ISSUE THREAD

**Issue by ribizli** [primefaces/primeng#1668]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
If no rowTrackBy function given, ngFor throws an exception. See https://github.com/angular/angular/commit/fcd116fdc05c4ed1e03d2f934e3a3718a757f159

**Expected behavior**
Handle missing (undefined) rowTrackBy input.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.4.1 (check was introduced in this version)

* **PrimeNG version:** 1.0.1 (I'm behind due to other bug, please fix that too: e.g.: #1600) (bug also in version 1.1.1)

**Comment by cagataycivici** [comment]
Duplicate 1652
