### ISSUE TITLE
Calendar Unable to Select a Date after setting minDate

### ISSUE THREAD

**Issue by darius-iko** [primefaces/primeng#1669]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/LCTezM?p=preview

**Current behavior**
After setting minDate, the Calendar is unable to select any date.

**Expected behavior**
It should be able to select a date.

**Minimal reproduction of the problem with instructions**
Set minDate of a calendar to any date and check the result.

**Please tell us about your environment:**
OS: Windows, IDE: VS Code and Browser (Google Chrome)

* **Angular version:** 2.3.1

* **PrimeNG version:** 1.1.1

* **Browser:** all
 
* **Language:** TypeScript 2.0.3

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
