### ISSUE TITLE
iOS Safari Keyboard Not Triggering on <p-password> Component Input Field

### ISSUE THREAD

**Issue by nirangaL** [primefaces/primeng#16693]
### Describe the bug

I'm experiencing an issue with the PrimeNG <p-password> component where the iOS keyboard does not trigger when the user interacts with the input field inside the component on iOS Safari. This issue also occurs on the official PrimeNG documentation examples of the <p-password> component.
![image](https://github.com/user-attachments/assets/a8142243-e24b-4624-9d43-44610af17d33)

### Environment

The issue was tested on an iPad 9 running iOS 16.x, using Safari as the browser. The problem also occurs in Chrome on iOS. The application is built with Angular 14.x and PrimeNG 13.x, and the development environment uses Node.js v14.x and npm 6.x. The issue was reproduced on a real device and also in a simulator.

### Angular version

13.2.7

### PrimeNG version

13.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.18.3

### Browser(s)

 iOS, v16.0 , Browsers Safari and Chrome

### Steps to reproduce the behavior

1. Create a simple Angular application that uses the <p-password> component from PrimeNG 13.4.1.
2. Test the application on an iOS device (e.g., iPad 9) using Safari or Chrome.
3. When you tap on the input field (password field) inside the <p-password> component, the keyboard does not appear as expected
4. This issue happens both in a simple use case and in examples provided on the official PrimeNG documentation site for the <p-password> component.

### Expected behavior

When the user taps on the <p-password> component's input field, the iOS keyboard should appear.

**Comment by mertsincan** [comment]
Could you please try the latest PrimeNG version?
