### ISSUE TITLE
DynamicDialog v18.0.0-beta.2

### ISSUE THREAD

**Issue by foum-traore** [primefaces/primeng#16692]
### Describe the bug

Hello,
I'm experiencing an issue with the DynamicDialog: even with modal=true, it's possible to click outside the dialog. In previous versions, the dialog opened with an overlay by default, preventing interactions outside the modal.
Here are the links for comparison: [v18 DynamicDialog Example](https://v18.primeng.org/dynamicdialog#example)
[Previous PrimeNG DynamicDialog Example](https://primeng.org/dynamicdialog#example)

### Environment

Angular primeng.

### Angular version

^18.0.4

### PrimeNG version

18.0.0-beta.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v22.3.0

### Browser(s)

Google chrome

**Comment by gbarrionuevo** [comment]
this seems to be working in [18.0.0-rc.2]
