### ISSUE TITLE
CurrentPageReport for Paginator

### ISSUE THREAD

**Issue by anikets43** [primefaces/primeng#167]
![paging](https://cloud.githubusercontent.com/assets/7136799/14307429/8b2c0e24-fbec-11e5-8c6d-e7b9258ff952.png)

Hi, I am trying to add paging details in the grid footer to record the page items and total count. I don't see any event exposed on Page change. Can anyone provide some input.

Thanks,
Aniket

**Comment by anikets43** [comment]
Hi @cagataycivici I encountered below property in dataTable.ts which is being used  paginator.ts for adding select options.
**datatable.ts**
`@Input() rowsPerPageOptions: number[];

<p-paginator [rows]="rows" [first]="first" [totalRecords]="totalRecords" [pageLinkSize]="pageLinks" styleClass="ui-paginator-bottom"
                (onPageChange)="paginate($event)" [rowsPerPageOptions]="rowsPerPageOptions" *ngIf="paginator"></p-paginator>`

**paginator.ts**
` <select class="ui-paginator-rpp-options ui-widget ui-state-default" *ngIf="rowsPerPageOptions" (change)="onRppChange($event)">
                <option *ngFor="#opt of rowsPerPageOptions" [value]="opt" [selected]="rows == opt">{{opt}}</option>
            </select>`

But when I try to pass [rowsPerPageOptions] in the dataTable, I don't see any difference.
`<p-dataTable [value]="value" [rows]="rows"  [paginator]="true" [pageLinks]="5" [responsive]="true" [rowsPerPageOptions]="rowsPerPage">`
 this.rowsPerPage = [5,10,15];

Kindly let me know whether this functionality has been implemented or in the pipeline.

Much Regards,
Aniket

**Comment by cagataycivici** [comment]
rowsPerPage has been added a couple of days ago so not released yet, it will be available in 1.0.0-beta.1 due april 11 so you can use this feature.

About displaying current page, we should do it as a built-in feature because we have it in PrimeFaces, called CurrentPageReportTemplate="{0} of {1}" where 0 is current page and 1 is total number of pages.

**Comment by anikets43** [comment]
@cagataycivici 
Will it be possible to bind the dynamic data on page index change?

**Comment by cagataycivici** [comment]
Not sure what you mean by dynamic data?

**Comment by bella92** [comment]
@cagataycivici , what is the status of this feature, is it expected soon?

**Comment by anikets43** [comment]
Hi @bella92 : Primeng datatable supports lazy loading features. Kindly refer the documentation.

Cheers,
Aniket

**Comment by adarshakr** [comment]
How to get current page number in data grid?

**Comment by h-arora** [comment]
was this incorporated?
