### ISSUE TITLE
Component: MultiSelect with virtual scroll

### ISSUE THREAD

**Issue by mojesto** [primefaces/primeng#16708]
### Describe the bug

The bug occurs when a user searches in the multiselect component with virtual scroll and reaches a "No results found" state. Upon partially clearing the search term to bring back multiple results, the dropdown panel height does not automatically expand to display all results, remaining limited to a single row height.

### Environment

MacOS, Chrome

### Angular version

18.2.11

### PrimeNG version

17.18.11

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.1

### Browser(s)

Chrome 130

### Steps to reproduce the behavior

Open the multiselect virtual scroll demo at https://primeng.org/multiselect#virtualscroll.

1. In the search input, type "emf" so that "No results found" appears.
2. Then, delete the "f" from the search field.
3. Despite many results now appearing, the dropdown panel height remains short, showing only one row.

### Expected behavior

Dropdown panel automatically expands it's height to display multiple results

**Comment by rgolonko** [comment]
In my case working solutions is:

Add @ViewChild('autoComplete') autoComplete: AutoComplete;
In callback method onShow i added a line: this.autoComplete.scroller.unbindResizeListener();
Function onResize in scroller component imo is the source of the problem and it is not needed in case of AutoComplete/MultiSelect components. Invoked function calculateAutoSize() is enough and call onResize just break the height of panel.

I have the same problem as reported in: https://github.com/primefaces/primeng/issues/16727
