### ISSUE TITLE
Component: p-checkbox no longer has the attribute label in version 18.

### ISSUE THREAD

**Issue by raboud** [primefaces/primeng#16707]
### Describe the bug

version 18 has somehow dropped the attribute label

### Environment

Angular 18 and primeNg 18 beta 2

### Angular version

18.2.4

### PrimeNG version

v18.0.0-Beta.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.16.0

### Expected behavior

should have a label when label attribute is set like previous versions

**Comment by mehmetcetin01140** [comment]
The label property has been deprecated. #15688

**Comment by kshetline** [comment]
It's annoying that this was deprecated, then removed. It's way, way easier to use a label attribute.
