### ISSUE TITLE
Button component doesn't allow custom icon and label (18 beta.3)

### ISSUE THREAD

**Issue by AStoker** [primefaces/primeng#16701]
### Describe the bug

While attempting to use Font Awesome icons with a button, I found that it is not currently possible unless you're specifically using class based icons (which does not support tree shaking and increases overall size of the application).
The code that determines whether a label is used or not looks to see if there's a content template added (https://github.com/primefaces/primeng/blob/c89e42c654253022d3c21b6e0c8580cec676ea63/src/app/components/button/button.ts#L417), this means you are unable to use an icon component with the `label` binding.

``` html
   <p-button 
      label="Test"
    >
      <ng-template pTemplate="contentTemplate">
        <fa-icon [icon]="['fas', 'sun']"></fa-icon>
      </ng-template>
    </p-button>
  ```

In this example, the label `Test` is not rendered.
Ideally, we should be able to have a custom icon template option, so that we can allow more options for rendering icons.

### Environment

Windows 11, Edge browser

### Angular version

18

### PrimeNG version

18.0.0-beta.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.16.0

### Browser(s)

Edge

### Steps to reproduce the behavior

1. Add a `<p-button>` with a label.
2. Add a ng-template to add an icon
3. Note the icon appears but the label is not rendered.

### Expected behavior

We should be able to have a custom icon component with a label.

**Comment by jogerj** [comment]
have you tried using 
```
<ng-template #contentTemplate>
```

**Comment by cetincakiroglu** [comment]
Hi,

`contentTemplate` is not a templating option of button component. Component work as expected with the correct use below:

Correct usage: 

```
            <p-button>
                <ng-template pTemplate="content">
                    <i class="pi pi-plus"></i>
                    <span>Test</span>
                </ng-template>
            </p-button>

            <p-button label="test">
                <i class="pi pi-plus"></i>
            </p-button>

            <p-button>
                <i class="pi pi-plus"></i>
                <span>Test</span>
            </p-button>
            
            // compatible +v18
            <p-button>
                <ng-template #content>
                    <i class="pi pi-plus"></i>
                    <span>Test</span>
                </ng-template>
            </p-button>
```
