### ISSUE TITLE
dynamic dialog dismissible mask false not shown v18 beta 3

### ISSUE THREAD

**Issue by urielzen** [primefaces/primeng#16723]
### Describe the bug

The dynamic dialog background is not shown (`p-overlay-mask` not applied) when `dismissableMask` property is set to `false`. It only shows when it is `true`.

### Environment

Windows/Chrome

### Angular version

18

### PrimeNG version

18 beta 3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.20.3

### Browser(s)

Chrome

### Expected behavior

I believe the modal background should be shown even if it is not dismissible, as that was the behavior in v17

**Comment by cetincakiroglu** [comment]
Hi,

You need to set `modal` property to `true` to display mask.

Here is a dialog configuration to make it work:

```
    show() {
        this.ref = this.dialogService.open(ProductListDemo, {
            header: 'Product List',
            modal: true, // this should be true
            width: '50vw',
            closable: true,
            contentStyle: { overflow: 'auto' },
            dismissableMask: false,
            breakpoints: {
                '960px': '75vw',
                '640px': '90vw'
            }
        });
    }
```
