### ISSUE TITLE
Ensure that document functions exist before calling in ngOnDestroy()

### ISSUE THREAD

**Issue by brian428** [primefaces/primeng#1672]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Creating a test plunk here would be difficult because the issue manifests during unit test teardown.

**Current behavior**
If you unit test a component that uses something like ConfirmDialog, the test **must** be `async()` and/or must wait for component to be stable, or errors will be thrown. This is due to the onNgDestroy() calls:

```
if(this.responsive) {
    this.documentResponsiveListener();
}

if(this.closeOnEscape && this.closable) {
    this.documentEscapeListener();
}
```

The problem is that if the Dialog is destroyed before the listeners are set, these calls will throw `xxx is not a function` errors. (In a totally separate issue, and even more annoying, these failures will cause **all subsequent tests** to fail, which is suspect is a Karma or Jasmine issue related to how the tests are executed.)

I know this affects ConfirmDialog, but I imagine that any component that uses document listeners like this would have the same problem.

**Expected behavior**
Destroying components that use document listeners should not error if the listeners have not been set. Before the functions are called during destroy, they should be checked for existence. Something like:
```
if(this.responsive && this.documentResponsiveListener) {
    this.documentResponsiveListener();
}

if(this.closeOnEscape && this.closable && this.documentEscapeListener) {
    this.documentEscapeListener();
}
```

**Comment by Chintanvpatel** [comment]
@brian428 Same issue here with contextmenu component. I'm getting

> undefined is not a constructor (evaluating 'this.documentClickListener()') in karma-shim.js

https://github.com/primefaces/primeng/blob/master/components/contextmenu/contextmenu.ts#L241

**Comment by brian428** [comment]
Is there a reason this hasn't been included in the final 2.0 release?

**Comment by brian428** [comment]
@cagataycivici Just trying to get some sort of answer about getting these fixes merged into master, because they never made it into the final 2.0. Could someone actually merge these fixes in please?

**Comment by brian428** [comment]
@cagataycivici Just trying to bump this since these fixes _still_ haven't actually been merged into the master branch. https://github.com/primefaces/primeng/blob/master/components/confirmdialog/confirmdialog.ts#L223

Can someone please get these merged in? Thanks.

**Comment by andrii-oleksyshyn** [comment]
Hi Brian,

Could you please share an example of async test that resolves this issue?
Thanks.

**Comment by cagataycivici** [comment]
@brian428 #2149 fixes all, no?

**Comment by andrii-oleksyshyn** [comment]
As I understand these fixes are included only in 4.0 build but not in the latest 2.x?

**Comment by cagataycivici** [comment]
No plans for a new 2.x as upgrading to 4 is quite easy. If there is more demand from community, we can do it though.

**Comment by andrii-oleksyshyn** [comment]
Angular 4 is still in RC, so migration to it is not the best solution.

**Comment by andrii-oleksyshyn** [comment]
@cagataycivici it's really awesome that you released new build for Angular 2, but it doesn't include ngOnDestroy fix for the context menu component 😞
