### ISSUE TITLE
New Package: `@primeng/themes`

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primeng#16738]
A package with pre-built themes for PrimeNG, designed to work with new theming API.

**Comment by urielzen** [comment]
I am unable to import the themes from this package. 
this won't work `import Lara from '@primeng/themes/lara';`

**Comment by mertsincan** [comment]
Please try; 
https://stackblitz.com/edit/umweie?file=package.json,src%2Fapp%2Fpanel-basic-demo.html,src%2Fapp%2Fpanel-basic-demo.ts

**Comment by urielzen** [comment]
Thanks,
The issue turned out to be typescript complaining about missing declaration file for the module
`Could not find a declaration file for module`, so I just added `// @ts-expect-error` above the import
