### ISSUE TITLE
DatePIcker:  12 hourformat validation error

### ISSUE THREAD

**Issue by harilal** [primefaces/primeng#1673]
When hourformat set to "12" and selected date is in "PM" , change the hour to 12 in  inputfield and the date changes to AM and the date in the input filed show PM,

When the time is in "AM" and edit hour to 12 it sets as a 12"00 AM and the value is 00:00.

When the date is set to 12:00PM, change the am/pm to "AM" and date set to 12:00 am

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Fixed via #1648
