### ISSUE TITLE
Customers table demo filter problem

### ISSUE THREAD

**Issue by karthikMNK** [primefaces/primeng#16746]
### Describe the bug

Go to Table component - samples - customers - filter by agent - enter text 9 in the custom input filter

![image](https://github.com/user-attachments/assets/0a1e3148-e1b0-4664-a9a7-a7e853066f89)

we get no results found message but the text field has lost its value and there is no reset button like in PrimeNG 17

### Environment

Showcase->
https://v18.primeng.org/table#customers
Latest Version V18

### Angular version

18

### PrimeNG version

18

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

11

### Browser(s)

chrome

### Steps to reproduce the behavior

Go to Table component - samples - customers - filter by agent - enter text 9 in the custom input filter

![image](https://github.com/user-attachments/assets/0a1e3148-e1b0-4664-a9a7-a7e853066f89)

we get no results found message but the text field has lost its value and there is no reset button like in PrimeNG 17

### Expected behavior

same as PrimeNG 17

**Comment by cagataycivici** [comment]
It should work as in;

https://primevue.org/datatable/#customers

Should be fixed in v18.

**Comment by karthikMNK** [comment]
The issue is in V18 only may be i did not mention it correctly. 
https://v18.primeng.org/table#customers

**Comment by shaman-apprentice** [comment]
As an addition: The basic demo currently only shows the paginator and no table data at all - https://v18.primeng.org/table#filter
