### ISSUE TITLE
Table documentation missing lazy load example

### ISSUE THREAD

**Issue by JuncalLP** [primefaces/primeng#16745]
### Describe the bug

On the docs page for table component, under the pagination section, there's a link for a lazy loading example, but it's broken. Thought this might be an issue with the beta docs but happens on v17 and v15 docs too.

![imagen](https://github.com/user-attachments/assets/d3a2ffb4-d0a4-4a70-9b24-ec391675d0e7)
![imagen](https://github.com/user-attachments/assets/9e04d8b7-1b1e-4370-b14b-92c3b2090b3e)

### Environment

Windows 10

### Angular version

18.2.8

### PrimeNG version

18.0.0-beta.4

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22.9

### Browser(s)

Mozilla Firefox

### Steps to reproduce the behavior

Navigate to https://v18.primeng.org/table#paginator and click on 'lazy loading' 

### Expected behavior

The lazy loading example should exist

**Comment by joviga-dev** [comment]
up

**Comment by aboudard** [comment]
Yeah, the lazy section is here now, but it's place in the links on the right is off, and the text to descibe it is the same as the virtualscroll : 
![image](https://github.com/user-attachments/assets/011c6570-3ebd-47c7-b24e-7ea48a5c6125)

https://v18.primeng.org/table#virtual-scroll-lazy
should be
https://v18.primeng.org/table#lazy
Problem with menu indentation obviously

**Comment by JuncalLP** [comment]
> Yeah, the lazy section is here now, but it's place in the links on the right is off, and the text to describe it is the same as the virtualscroll : ![image](https://private-user-images.githubusercontent.com/767767/387403328-011c6570-3ebd-47c7-b24e-7ea48a5c6125.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5OTg0OTAsIm5iZiI6MTczMTk5ODE5MCwicGF0aCI6Ii83Njc3NjcvMzg3NDAzMzI4LTAxMWM2NTcwLTNlYmQtNDdjNy1iMjRlLTdlYTQ4YTVjNjEyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQwNjM2MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wY2FkNDY2YzUzZWFiNGY2NTI5ODEyMGYwMGYzMjNmYzhjNTNiOGM3NWM4NmI3MWMyYWZkNzk2ZDY5ZGEwNTZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0k6hf7782mM8DUsLPxmddGrwGF_Eumfi7Am45_ZVOeY)
> 
> https://v18.primeng.org/table#virtual-scroll-lazy should be https://v18.primeng.org/table#lazy Problem with menu indentation obviously

Are you sure about that? I think that the identation is right there, they're both examples of Virtual scroll, but on the first one the displayed elements array are eagerly loaded while on the second one are they're lazy loaded, however I'm interested in a lazy load example by itself, without Virtual scroll (handling paging, sorting, global search...).

**Comment by aboudard** [comment]
> Are you sure about that? I think that the identation is right there, they're both examples of Virtual scroll, but on the first one the displayed elements array are eagerly loaded while on the second one are they're lazy loaded, however I'm interested in a lazy load example by itself, without Virtual scroll (handling paging, sorting, global search...).

After checking, you are right, the v17 docs is organized the same way. I think that `lazy` should have its own section though, as you say. And for me, both are unrelated, the scroll event is simply going through the lazy mechanism.
That being said, even in v17 docs, the texts are already duplicated.

**Comment by aboudard** [comment]
Here is the page I was mentioning in v16:
https://www.primefaces.org/primeng-v16-lts/table#lazy-load
This page should be here. If I have time I might take a look at this for a PR.

**Comment by joviga-dev** [comment]
@mehmetcetin01140  Does removing the hyperlink to the broken url really fixes the problem of the lazy loading example not existing?

**Comment by aboudard** [comment]
Yeah, I really doubt this commit would fix the problem.
