### ISSUE TITLE
Improve theme definitions in `@primeng/themes`

### ISSUE THREAD

**Issue by romagnoli8** [primefaces/primeng#16749]
### Describe the bug

Hi, I updated to 18.0.0.beta.4 my PrimeNG version but I lost my theme Aura. I have this problem now.

<img width="911" alt="image" src="https://github.com/user-attachments/assets/0993286e-ae92-4d13-8b8f-fbe62504679e">

### Environment

Staging.

### Angular version

18.2.0

### PrimeNG version

18.0.0-beta.4

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22.4.1

**Comment by caboodal** [comment]
Same problem here after upgrading from beta.3 with the following output: -

X [ERROR] TS2307: Cannot find module 'primeng/themes/aura' or its corresponding type declarations. [plugin angular-compiler]

    projects/shared/src/bootstrap/themes/blink-preset.ts:1:21:
      1 │ import { Aura } from 'primeng/themes/aura';
        ╵                      ~~~~~~~~~~~~~~~~~~~~~


X [ERROR] TS2307: Cannot find module 'primeng/themes' or its corresponding type declarations. [plugin angular-compiler]

    projects/shared/src/bootstrap/themes/blink-preset.ts:2:29:
      2 │ import { definePreset } from 'primeng/themes';

**Comment by urielzen** [comment]
Sample here
https://stackblitz.com/edit/umweie?file=package.json,src%2Fapp%2Fpanel-basic-demo.html,src%2Fapp%2Fpanel-basic-demo.ts

**Comment by mertsincan** [comment]
> I had to import it with ts error disabled
// @ts-expect-error expected
import Material from '@primeng/themes/material';

Fixed for the next version.

**Comment by JamesTheTerry** [comment]
@mertsincan Are you sure this has been fixed? I'm still seeing this when running primeng 18.0.0-rc.1 and @primeng/themes 18.0.0-beta.4 (the current latest releases).

**Comment by mertsincan** [comment]
Yes, please use primeng v18.0.0-rc.1 and @primeng/themes v18.0.0-rc.1

**Comment by JamesTheTerry** [comment]
> Yes, please use primeng v18.0.0-rc.1 and @primeng/themes v18.0.0-rc.1

🤦‍♀️ I didn't see the newer releases on npm, it totally works. My bad.

Thanks @mertsincan!

**Comment by AnaisR7** [comment]
Same issue here with primeng and @primeng/themes 18.0.2.
`import { definePreset } from '@primeng/themes';` in my custom preset file leads to the error : TS2307 (TS) Cannot find module 'primeng/themes' or its corresponding type declarations.

But `import Nora from '@primeng/themes/nora';` works good
