### ISSUE TITLE
Create CHANGELOG.md

### ISSUE THREAD

**Issue by ctrl-brk** [primefaces/primeng#1675]
Would be very beneficial. The current process for me is go to primefaces web site, click on forum, click on topic, go to blog to read what changed in a new version. That's a long way.

**Comment by cagataycivici** [comment]
Thanks, we will consider it after 4.1.

**Comment by Klinton90** [comment]
4.2 in RC state. Please add Changelog. 🥇

**Comment by maxkorz** [comment]
@cagataycivici version 4.3.0 has been released, still no change log in [releases](https://github.com/primefaces/primeng/releases)....

**Comment by Klinton90** [comment]
https://github.com/primefaces/primeng/milestone/75?closed=1

**Comment by maxkorz** [comment]
@Klinton90 [Blog entry](https://www.primefaces.org/primeng-4-3-0-released-verona/) describes 8 important changes, while [full changelog](https://github.com/primefaces/primeng/milestone/75) has 85 closed issues. I don't want to waste my time going through 85 issues. And I don't want to waste my time going to github -> web site -> forum -> topic -> blog

**Comment by brian428** [comment]
@cagataycivici Any progress on this? You've got a great library here, but understanding what has been changed/fixed/added between versions is _way_ more difficult than it should be. Can't whoever is writing the various blog posts and forum posts just update a CHANGELOG.md file as well? Or use a package like [conventional-changelog](https://www.npmjs.com/package/conventional-changelog) to generate a CHANGELOG? Please consider addressing this. Thanks.

**Comment by rafa-as** [comment]
Totally agree, must be present

**Comment by MattiJarvinen-BA** [comment]
Currently looking at primeeng 4.2.2 upgrade to 5.2.4 no clue what has changed & where to look for that backwards incompatible change.

**Comment by szechyjs** [comment]
The lack of a CHANGELOG in this project is very frustrating! The only way I can figure out what changed is to go through the commit history, and even that is a pain as the commit messages only list Issue numbers.

![screen shot 2018-04-25 at 11 42 16 am](https://user-images.githubusercontent.com/847739/39256810-dc1c81d0-487d-11e8-9421-29718ed75af4.png)

**Comment by brian428** [comment]
The bizarre thing is that they post occasional version updates on their blog, which means **someone** is doing **some** level of tracking on what has changed. Why they've decided to post these to their blog (where few will see it) instead of updating a README is truly baffling.

**Comment by ctrl-brk** [comment]
With 5.2.7 release there's not even a blog post. Go figure...

**Comment by brian428** [comment]
Just updating today and once again realizing how absurd it is that there's no CHANGELOG, so once again I get to do manual version comparisons to try and determine what actually changed.

Could the PrimeNG folks **please** add a CHANGELOG? It'd be two years late, but better late than never.

**Comment by ViceIce** [comment]
Additionally they even add new features or breaking changes in bugfix releases. :disappointed:

**Comment by cagataycivici** [comment]
Here is the initial version, we'll add more info about breaking changes as well so it will be maintained/updated from now on.

https://github.com/primefaces/primeng/blob/master/CHANGELOG.md
