### ISSUE TITLE
Docs: Theming is outdated (PrimeNg 18.0.0-rc.1)

### ISSUE THREAD

**Issue by hunhejj** [primefaces/primeng#16759]
### Describe the bug

The docs were not completely updated after the package `@primeng/themes` has been extracted. For example in the docs `definePreset` is still imported from `primeng/themes` although it is supposed to be imported from `@primeng/themes` now.

![image](https://github.com/user-attachments/assets/980699c7-06a4-4eb1-8d39-767c91973383)

### Environment

Lorem ipsum.

### Angular version

18

### PrimeNG version

18.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

10

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primeng/pull/16760
