### ISSUE TITLE
Theme presets are not publicly exposed (@primeng/themes v18.0.0-rc.1)

### ISSUE THREAD

**Issue by hunhejj** [primefaces/primeng#16758]
### Describe the bug

The presets are not publicly exposed anymore from `@primeng/themes`. Eslint is not happy about using "internal modules".

![image](https://github.com/user-attachments/assets/021af094-b129-4583-93cc-c8dee69c5392)

### Environment

Just a regular Angular application.

### Angular version

18

### PrimeNG version

18.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

10

**Comment by mertsincan** [comment]
This package exports multiple objects so that users can create their own presets. For this reason, you can ignore it from eslint rules.

Exp;
```
import base from '@primeng/themes/aura/base'
import accordion from '@primeng/themes/aura/accordion'
import button from '@primeng/themes/aura/button'
...

const customAura = {
      ...base,
     components: {
          accordion,
          button,
          ...
     }
}

export default customAura;
```
Or 
```
import Aura from '@primeng/themes/aura'
```

**Comment by hunhejj** [comment]
I get that @mertsincan but I don't see how that's answers my original issue. Can't you just expose those objects publicly the same way like you expose any component in the main primeng package?
