### ISSUE TITLE
Component: pInputText size attribute (18.0.0-rc.1)

### ISSUE THREAD

**Issue by mazerdeci** [primefaces/primeng#16761]
### Describe the bug

The pInputText directive now has a size attribute. This attribute conflicts with the size attribute of the input element.

<input type="text" pInputText size="10">
Angular compiler says
Type '"10"' is not assignable to type '"small" | "large"'.

Note: You can replace size with Size to make the application compile. But this is not the right approach. 

### Environment

Windows 11

### Angular version

18.2.12

### PrimeNG version

18.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22.11.0

**Comment by cetincakiroglu** [comment]
fixed in https://github.com/primefaces/primeng/commit/8f8b5f8e6a56ab4880e4ed58f83eb4fdb6661040
