### ISSUE TITLE
Component: Table. Using @if or *ngIf within a column template produces "expression has changed after it was checked"

### ISSUE THREAD

**Issue by ctrl-brk** [primefaces/primeng#16766]
### Describe the bug

```
<ng-template pTemplate="body" let-items>
  <tr>
    <td>
      @if (true) {
        example
      }
    </td>
  </tr>
</ng-template>
```  
 Using conditional output anywhere in the template will result in the error below.
 This was introduced in the rc1 version. Beta didn't have this issue.

RuntimeError: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: '[object Object]'. Current value: 'undefined'. Expression location: _Table component. Find more at https://angular.dev/errors/NG0100
    at throwErrorIfNoChangesMode (core.mjs:10484:9)
    at bindingUpdated (core.mjs:18610:9)
    at ɵɵproperty (core.mjs:21743:7)
    at Table_Template (primeng-table.mjs:9520:12)
    at executeTemplate (core.mjs:11782:5)
    at refreshView (core.mjs:13335:7)
    at detectChangesInView (core.mjs:13543:5)
    at detectChangesInViewIfAttached (core.mjs:13505:3)
    at detectChangesInComponent (core.mjs:13494:3)
    at detectChangesInChildComponents (core.mjs:13555:5)

### Environment

angular 18.2.12
primeng 18.0.0-rc.1

### Angular version

18.2.12

### PrimeNG version

18.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22.9.0

**Comment by alljinx** [comment]
Hi, same issue for me with 18.0.0-rc.1 too except that I don't have any error output in the console.
If I remove the `@if (true) {` the header is correctly displayed. If I don't, the header is not displayed at all.

My test code is similary, using Panel :
```
<p-panel>
  <ng-template pTemplate="header">
    @if (true) {
        Amy Elsner
    }
  </ng-template>
</p-panel>
```

**Comment by shaman-apprentice** [comment]
I had the same issue. The template selectors were changed and the new ones are also used in the new documentation. So for me it worked to change `<ng-template pTemplate="body" let-items>` to `<ng-template #body let-items>`.

Out of curiosity: After a very short look in the source code, it was not clear to me, why the old ones are still picked up? However, this detail is not important for the bug issue, I guess.

**Comment by shaman-apprentice** [comment]
As a quick follow up / guess: [@ContentChild('body')](https://github.com/primefaces/primeng/blob/v18/packages/primeng/src/table/table.ts#L4207) was introduced with v18. And within `ngAfterContentInit` the templates get set by [(this.templates as QueryList<PrimeTemplate>).forEach((item) => { ...](https://github.com/primefaces/primeng/blob/v18/packages/primeng/src/table/table.ts#L4485). With the move to `@ContentChild('body')` and co the `ngAfterContentInit` callback can and should be removed?

**Comment by cetincakiroglu** [comment]
Hi,

Cannot replicate with the 18.0.0-rc.2
