### ISSUE TITLE
Menu component templates not rendered v18.0.0-beta.4

### ISSUE THREAD

**Issue by teflonmuflon2** [primefaces/primeng#16765]
### Describe the bug

the start and end tempaltes are not rendered

### Environment

chrome on windows 11

### Angular version

18.2.1

### PrimeNG version

18.0.0-beta.4

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v22.11.0

### Steps to reproduce the behavior

<p-menu [model]="items" class="flex justify-center" styleClass="w-full md:w-60">
    <ng-template pTemplate="start">
        <span class="inline-flex items-center gap-1 px-2 py-2">
            <svg width="33" height="35" viewBox="0 0 33 35" fill="none" xmlns="http://www.w3.org/2000/svg" class="block mx-auto">
                <path d="..." fill="var(--primary-color)" />
            </svg>
            <span class="text-xl font-semibold">
                PRIME<span class="text-primary">APP</span>
            </span>
        </span>
    </ng-template>
    <ng-template pTemplate="submenuheader" let-item>
        <span class="text-primary font-bold">{{ item.label }}</span>
    </ng-template>
    <ng-template pTemplate="item" let-item>
        <a pRipple class="flex items-center p-menu-item-link">
            <span [class]="item.icon"></span>
            <span class="ml-2">{{ item.label }}</span>
            <p-badge *ngIf="item.badge" class="ml-auto" [value]="item.badge" />
            <span *ngIf="item.shortcut" class="ml-auto border border-surface rounded bg-emphasis text-muted-color text-xs p-1">
                {{ item.shortcut }}
            </span>
        </a>
    </ng-template>
    <ng-template pTemplate="end">
        <button pRipple class="relative overflow-hidden w-full border-0 bg-transparent flex items-start p-2 pl-4 hover:bg-surface-100 dark:hover:bg-surface-800 rounded-none cursor-pointer transition-colors duration-200">
            <p-avatar image="https://primefaces.org/cdn/primeng/images/demo/avatar/amyelsner.png" class="mr-2" shape="circle" />
            <span class="inline-flex flex-col">
                <span class="font-bold">Amy Elsner</span>
                <span class="text-sm">Admin</span>
            </span>
        </button>
    </ng-template>
</p-menu>

### Expected behavior

should display the templates

**Comment by mertsincan** [comment]
Could you please attach a stackblitz link for us to replicate? Thank you!

**Comment by teflonmuflon2** [comment]
> Could you please attach a stackblitz link for us to replicate? Thank you!

i copied the demo from:
https://v18.primeng.org/menu

![image](https://github.com/user-attachments/assets/cb93a883-9c14-4165-99ff-058c39278669)


it doesn't works on the demo page either

**Comment by teflonmuflon2** [comment]
very strange. if i use @if in any of template the templates not displayed.
not working:
  <ng-template let-item pTemplate="item">
    @if (item?.visible !== false) {
      <a class="flex items-center p-menuitem-link ml-3">
        <mat-icon
          class="{{ item?.text_color ? item?.text_color : 'text-primary' }}"
          fontIcon="{{ item.icon ? item.icon : 'add_circle' }}" />
        <span class="ml-2 {{ item?.text_color ? item?.text_color : '' }} ">{{ item.label }}</span>
        @if (item?.selector) {
          <span class="ml-auto border surface-border bg-blue-500 text-white text-xs p-1">
            {{ item?.selector }}
          </span>
        }
      </a>
    }
  </ng-template>
  
  working:
    <ng-template let-item pTemplate="item">
    <a class="flex items-center p-menuitem-link ml-3">
      <mat-icon
        class="{{ item?.text_color ? item?.text_color : 'text-primary' }}"
        fontIcon="{{ item.icon ? item.icon : 'add_circle' }}" />
      <span class="ml-2 {{ item?.text_color ? item?.text_color : '' }} ">{{ item.label }}</span>

      <span
        [ngClass]="
          item?.selector ? 'bg-blue-500 ml-auto border surface-border text-white text-xs p-1' : ''
        ">
        {{ item?.selector }}
      </span>
    </a>
  </ng-template>

**Comment by teflonmuflon2** [comment]
needed to use the new syntax
