### ISSUE TITLE
Component: Jest cannot find module '@primeng/themes'

### ISSUE THREAD

**Issue by jogerj** [primefaces/primeng#16767]
### Describe the bug

Test suite failed to run

    Cannot find module '@primeng/themes' from 'src/app/core/theme.config.ts'  

    Require stack:
      src/app/core/theme.config.ts
      src/app/core/app.config.ts
   

### Environment

any

### Angular version

18.2.6

### PrimeNG version

18.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v22.8.0

### Steps to reproduce the behavior

jest runs on appcomponent cannot find the module

### Expected behavior

finds the module without explicit mapping

**Comment by mertsincan** [comment]
Hi,

`@primeng/themes` is a different package. You can check whether it is loaded or exclude/add it to jest.

**Comment by jogerj** [comment]
For other `@primeng` imports this is already supported oob without explicitly setting moduleNameMapper. Only the themes package doesn't

**Comment by Gillesf31** [comment]
Same question here, since v18 I can't use Jest and Primeng together, I tried a lot of configuration in my jest config file without any success

**Comment by Micuba** [comment]
This configuration works for me:

`
moduleNameMapper: {'@primeng/themes': '<rootDir>/node_modules/@primeng/themes/index.mjs'},
`

**Comment by Nickolaus** [comment]
In addtion to @Micuba:
```
  moduleNameMapper: {
    ...pathsToModuleNameMapper(compilerOptions.paths, {
      prefix: '<rootDir>/',
    }),
    '@primeng/themes': '<rootDir>/node_modules/@primeng/themes/index.mjs'
  },
```
