### ISSUE TITLE
Component: PickList (18.0.0-rc.1)

### ISSUE THREAD

**Issue by mazerdeci** [primefaces/primeng#16762]
### Describe the bug

sourceHeader and targetHeader properties of Picklist are not working anymore.

Documentation of picklist at https://v18.primeng.org/picklist API page mentions both sourceHeader and targetHeader properties. But i can not see this properties in source code of picklist. There are just declarations. Will these properties deprecate? 
I also checked sourceHeader and targetHeader templates. No luck.

Note: I tried to reproduce this bug with issue template. But template is  old and i'm not able to upgrade to v18.

### Environment

Windows 11

### Angular version

18.2.12

### PrimeNG version

18.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22.11.0

**Comment by cetincakiroglu** [comment]
closed in https://github.com/primefaces/primeng/commit/55c1f7c9936437cbb4b6bb7a8d794ebbfcd3eac5

**Comment by mazerdeci** [comment]
<div class="p-picklist-title" *ngIf="!targetHeaderTemplate">{{ sourceHeader }}</div>
should be
<div class="p-picklist-title" *ngIf="!targetHeaderTemplate">{{ targetHeader }}</div>
