### ISSUE TITLE
Component: Template for Tree not working (18.0.0-rc.1)

### ISSUE THREAD

**Issue by jonath92** [primefaces/primeng#16764]
### Describe the bug

With the 18.0.0-rc.1 version, templates within the tree component are ignored. This can also be seen in the [documentation](https://v18.primeng.org/tree#template): 
![image](https://github.com/user-attachments/assets/768cd938-8adf-4361-a3c0-6d6ff36ec40b)

### Environment

Reproducable in every browser

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-lwljgf?file=src%2Fapp%2Ftree.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

### Angular version

18.2.0

### PrimeNG version

18.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.9.0

**Comment by cetincakiroglu** [comment]
Hi,

`urlTemplate` is not a property of tree. It was a documentation mistake. https://v18.primeng.org/tree#api.tree.templates
