### ISSUE TITLE
v18 themes : 'themes' folder went missing between release beta3 and beta4

### ISSUE THREAD

**Issue by Laryan1** [primefaces/primeng#16771]
### Describe the bug

The "themes" folder supposed to host the logic for themes manipulation went missing between beta3 and beta4

### Environment

[18.0.0-rc.1](https://www.npmjs.com/package/primeng/v/18.0.0-rc.1)

### Angular version

18.x.x

### PrimeNG version

18.0.0-rc.1

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

22.x.x

### Expected behavior

The "themes" folder should be present.

**Comment by mertsincan** [comment]
Yes, please use @primeng/themes

**Comment by Arun6381** [comment]
But @primeng/themes also not found in node module?

**Comment by itanitcom** [comment]
Hello 
.css/.scss not exist in my "node_modules/primeng/resources/themes/" .
same for  primeng.min.css
after npm install @primeng/themes

Angular: 19.0.5
Angular CLI: 19.0.6
Node: 20.18.0
`-- primeng@19.0.2
`-- @primeng/themes@19.0.2
