### ISSUE TITLE
v18 RC1 and Beta 5 Don't Have resources Folder

### ISSUE THREAD

**Issue by mylifeandcode** [primefaces/primeng#16782]
### Describe the bug

Installing the packages for v18 RC1 or v18 Beta 5 don't include the resources folder. Can't access themes or CSS which are no longer present.

### Environment

Angular CLI: 19.0.0
Node: 20.18.0
Package Manager: npm 10.2.4
OS: win32 x64

### Angular version

19.0.0

### PrimeNG version

18.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.18.0

### Steps to reproduce the behavior

npm i primeng@18.0.0-rc.1
Look in node_modules/primeng folder
No resources subfolder is present

### Expected behavior

resources subfolder should be present. Or another folder containing the CSS.

**Comment by Momme97** [comment]
Hi for themes you need to install these package: 
# Using npm
npm install primeng@18.0.0-rc.1 @primeng/themes@18.0.0-rc.1

![image](https://github.com/user-attachments/assets/da933f6e-3d13-415b-bac0-1c6ea0c52496)

**Comment by mylifeandcode** [comment]
Thank you @Momme97 and @HaodongMo !
