### ISSUE TITLE
v18.RC1 Theme Sample not working

### ISSUE THREAD

**Issue by Puresoft** [primefaces/primeng#16785]
### Describe the bug

If I create a new project and follow the config docs (just activate aura and place a button), no theme is applied

[Created a sample here](https://stackblitz.com/edit/stackblitz-starters-wihkg7?file=src%2Fmain.ts)

### Environment

Windows 11
Chrome
Angular 18.1
primeng 18rc1

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-wihkg7?file=src%2Fmain.ts

### Angular version

18.1

### PrimeNG version

18.0.rc1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22.7

### Browser(s)

Chrome current version

**Comment by kuhnlud** [comment]
Hi, 
To apply a theme, you should do it like this:
```
export const appConfig: ApplicationConfig = {
  providers: [
    provideAnimationsAsync(),
    providePrimeNG({
      theme: {
        preset: Aura
      },
    }),
  ],
};
```
I tried it in your StackBlitz, and it works. However, it’s certain that the documentation and code are still a bit rough around the edges.

**Comment by mertsincan** [comment]
Thanks a lot for the update! We're working on the demos.

**Comment by jagAlskarFisk** [comment]
@kuhnlud Sorry if I am missing something, but I see that your code is exactly like the one in the stackblitz, but no styling is applied

![image](https://github.com/user-attachments/assets/0b861731-867c-4d23-8419-1c7a7cb7c833)

**Comment by Puresoft** [comment]
The problem is solved, but you should update the documentation soon. New users will look for other libraries if the simplest setup doesn't work.

![image](https://github.com/user-attachments/assets/b3315dd5-b3c7-4312-bea9-6a4a63551fc8)

**Comment by mertsincan** [comment]
Thanks a lot for your update!

**Comment by sandipchitale** [comment]
For me the following worked...

```
import {providePrimeNG} from 'primeng/config';
import Aura from '@primeng/themes/aura';
:
:
:
export const appConfig: ApplicationConfig = {
  providers: [
    : 
    providePrimeNG({
     //  theme: Aura <----------------- does not work
      theme: { // <--------------------- this works!
        preset: Aura,
        options: {
          prefix: 'p',
          darkModeSelector: '.dark-theme'
        }
      },
      ripple: true
    })]
};
```

**Comment by djad442** [comment]
how to apply this ApplicationConfig if using modules instead of standalone app, since module bootstraps like:

```
platformBrowserDynamic().bootstrapModule(AppModule, {
  ngZoneEventCoalescing: true
})
  .catch(err => console.error(err));
```
