### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by tugcekucukoglu** [primefaces/primeng#16793]

**Comment by mertsincan** [comment]
Port: https://github.com/primefaces/primevue/issues/6826

**Comment by Zukqurnain** [comment]
@mertsincan @tugcekucukoglu Is there a way we can get RTL support early, perhaps through a beta version? Alternatively, do we have any estimates on which version it will be released?

**Comment by mertsincan** [comment]
@Zukqurnain We've already ported it, but I need to make a few changes today. We plan to release it this week.

**Comment by Zukqurnain** [comment]
> @Zukqurnain We've already ported it, but I need to make a few changes today. We plan to release it this week. https://github.com/orgs/primefaces/projects/4/views/15

Thanks, @mertsincan , for your quick response and for creating such an excellent Frontend Angular library &#10084;

**Comment by pdaneshmand** [comment]
You can check this issue

https://github.com/primefaces/sakai-ng/issues/85
