### ISSUE TITLE
menu: appendTo values other than body not working correctly in v18

### ISSUE THREAD

**Issue by jasonverber** [primefaces/primeng#16795]
### Describe the bug

When `Menu.appendTo` is set to a value other than `"body"` the menu items are not appended to the element passed via template ref, but rather the element is appended to the menu items.

```
appendOverlay() {
        if (this.appendTo) {
            if (this.appendTo === 'body') this.renderer.appendChild(this.document.body, this.container);
            else appendChild(this.container, this.appendTo);
        }
    }
```

Changing the order of the parameters fixes this:

```
appendOverlay() {
        if (this.appendTo) {
            if (this.appendTo === 'body') this.renderer.appendChild(this.document.body, this.container);
            else appendChild(this.appendTo, this.container);
        }
    }
```

This actually appears to be backwards everywhere that the @primeuix/utils version of `appendChild` is called.

### Environment

Fresh download of the `v18` branch running the showcase app with a menu added to a button will reproduce this. Personally running on an Apple silicon Mac with node 18.19.1.

### Reproducer

https://stackblitz.com/edit/github-l2mr75?file=src%2Fapp%2Fapp.component.html

### Angular version

18

### PrimeNG version

18.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.19.1

### Steps to reproduce the behavior

1. Install PrimeNG 18
2. Use the `Menu` component with `[appendTo]="someTemplateRef"`
3. Observe the menu does not appear where it should.
4. Update `menu.ts` to reverse the order of the parameters for `appendChild`
5. Observe the menu does appear where it should.

### Expected behavior

Menu items should appear appended to the element passed in via `appendTo`

**Comment by epitzalis** [comment]
In Angular 18.1.1 and primeng 17.18.5 the same problem occurs

**Comment by VicTMPDeV** [comment]
same environment than @epitzalis commented, same problem

**Comment by VicTMPDeV** [comment]
Using primeng v.19.0.5, with angular version 19.0.5. Using p-menu component with an [appendTo] value different from 'body' makes p-menu never closing (i guess it's something about bubbling event behavior).
I need to use another value different from body because p-menu scrolls along with all scrollable content. There I have to snapshots, initial and final positioning:

INITIAL:

![Image](https://github.com/user-attachments/assets/71370d9b-69e4-4222-86aa-b709b8957fba)

SCROLLING:

![Image](https://github.com/user-attachments/assets/febbdb3c-78b5-4189-a19f-5879cac542a8)

**Comment by pippaz** [comment]
This is still an issue for me, is there a workaround that you know of?

**Comment by VicTMPDeV** [comment]
I have fix it using a CSS class like this

<p-menu class="foo__sort-menu" [model]="sortOptions" [popup]="true" #sortMenu>
        <ng-template #item let-item>
            <li class="p-menu-item-link"
                [class.p-menu-item-link--selected]="selectedSortOption === item.label"
                (click)="item.command()">
                <span class="p-menu-item-label">{{ item.label }}</span>
            </li>
        </ng-template>
    </p-menu>

   &__sort-menu {
        position: absolute;
        top: v.$sz-none;
        left: v.$sz-none;
        z-index: v.$z-sticky-fixed;
        position: fixed;
    }

now it works the way I want

**Comment by pippaz** [comment]
Thank you so much! For the table I ended up making the 'td' relative

`<ng-template pTemplate="body" let-item>
    <tr>
          <td class="nmb-action relative">
            <p-splitbutton
              label="Edit"
              [raised]="true"
              icon="fa fa-pen"
              [model]="menuItems"
              (onClick)="edit(item)"
              (onDropdownClick)="menuItems = getMenuIems(item)"
              outlined="true"
            ></p-splitbutton>
          </td>
          <td>{{ item.name }}</td>
          <td>{{ item.description }}</td>
          <td>{{ item.isCirculate ? 'Yes' : 'No' }}</td>
    </tr>
</ng-template>`

And added this global style.

`.p-splitbutton {
  p-tieredmenu {
    position: fixed !important;
    z-index: 1050 !important;
  }
}`

As the [appendTo]="body" was behaving strangely.
