### ISSUE TITLE
Add support for the Scheduler add-on to the Schedule component based on FullCalendar

### ISSUE THREAD

**Issue by magwalls** [primefaces/primeng#168]
The Schedule component seem to be a very nice component. As you know it is based on the jQuery plugin FullCalendar. There is an add-on to FullCalendar called Scheduler. 

Would it be possible to add support for the Scheduler as well?

**Comment by cagataycivici** [comment]
It is a commercial product, our license will not allow to use the Scheduler module I'm afraid.
