### ISSUE TITLE
Unselect without ctrl + when click in a selected row with a single mode

### ISSUE THREAD

**Issue by danicomas** [primefaces/primeng#1680]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

**Current behavior**
You need to press ctrl +. It makes not sense if you are in a single mode.

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by ctrl-brk** [comment]
Why would you need to unselect in single mode? Anyway, such functionality should be optional, not the only way.

**Comment by danicomas** [comment]
With a single mode only the mouse click to select and unselect. @ctrl-brk

**Comment by danicomas** [comment]
I have realized something like that: 
http://plnkr.co/edit/A6QLS1?p=preview

@ctrl-brk you can verify it to detect if something we can do it better.

**Comment by cagataycivici** [comment]
Turning of metaKeySelection will give you the desired behavior.
