### ISSUE TITLE
Two-way binding doesn't work with manually entered date in calendar input

### ISSUE THREAD

**Issue by vadjs** [primefaces/primeng#1682]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/nOFb3Dp0GYl1jMbUZFCX
But i don't know why real code examples with PrmeNG doesn't work on plunkr.

**Current behavior**

Calendar input module has next bug: if date in calendar input was entered manually from keyboard and it loses focus without any click, [(ngModel)] value has correct moment value but two-way binding doesn't work in this case - you can't reset input value by external event(reset button in plunkr example).

**Expected behavior**

Here are 3 ways of correct behavior:
1. To count manually entered correct data value and be possile to affect on it by two-way binding.
2. To not count manually entered correct data value and not convert value in input to [(ngModel)] value.
3. Affect input value every time(doesn't matters correct or not) when something affects on [(ngModel)] value.

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/nOFb3Dp0GYl1jMbUZFCX (needs to make it working)
Input correct data value manually from keyboard.
Lose focus of input without any clicking on calendar.
Click "Reset value" button.
You will see that [(ngModel)] value was reset but input value not.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Everywhere.

* **Angular version:** 2.0.X

2.4.1

* **PrimeNG version:** 2.0.X

1.1.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Everywhere.
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript 2.1.1

* **Node (for AoT issues):** `node --version` =   
6.9.1

**Comment by luigidallavalle** [comment]
did you find any workaround to make it work?

**Comment by hungerregnuh** [comment]
here's a workaround, just add the relevant code to the writeValue and onChange methods...

```
@ViewChild('p-calendar') calendar: Calendar;
this.calendar.value = null;
this.calendar.updateInputField();
```

**Comment by cagataycivici** [comment]
Seems to be working with 4.2.2, if not provide a plunkr please;


http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=info

**Comment by pauloegk** [comment]
Hello, I had the same problem, I managed to solve it this way.

import { Calendar } from 'primeng/primeng';
@ViewChild(Calendar) calendar: Calendar;

this.calendar.updateInputfield();
