### ISSUE TITLE
`Angular 19` Support

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primeng#16827]
Details; https://github.com/primefaces/primeng/pull/16783

**Comment by AStoker** [comment]
If it helps, here's a list of files that needed to be updated in my testing. The Docs still have a lot of work though. https://github.com/AStoker/primeng/commit/a1bad87497c480a7b62abd392a5a9540d52c9a05

**Comment by NateRadebaugh** [comment]
Can this be back-ported to a 17.x release once this is ready?

**Comment by mertsincan** [comment]
Today, we had a detailed meeting about Angular 19 and decided to support it with PrimeNG 19. We are very close to the PrimeNG 18.Final. After releasing it, we plan to release PrimeNG 19.rc.1 within 1 to 2 weeks. Thanks a lot for your understanding!

**Comment by mertsincan** [comment]
> Can this be back-ported to a 17.x release once this is ready?

Unfortunately, we do not plan to port it to version 17. Primeng versions will be released following the Angular versions. Otherwise, there will be many breakages in frameworks and libraries that are under such active development. I think this is the most logical thing.

**Comment by igordanilovski** [comment]
So as I understand v17 & v18 (which still is in beta) will not have support for Angular 19? First release to support Angular 19 will be 19.x?

**Comment by David-Ben-Mesecke** [comment]
@mertsincan I agree with all of what @aberonni said, however, as opposed to him, if I do not at least see a drastic attitude change from your team, I am switching back to free and well supported angular material, this is completely unacceptable for my workflow. When angular updates, I update, I can wait a maximum of a week to update to a new major version upgrade but not even an day longer. I am pretty sure many of your paying customers feel the same. That said, this gives me a much needed kick in the butt to finally abstract my use of frontend UI components using facades. Yet @mertsincan please, pretty please, with sugar on top, please don't make me go back to angular material, right now, I have better things to do. Also, from what I can tell, the fix does not demand much work from you, so please do it, and do it right now.

**Comment by David-Ben-Mesecke** [comment]
> Today, we had a detailed meeting about Angular 19 and decided to support it with PrimeNG 19. We are very close to the PrimeNG 18.Final. After releasing it, we plan to release PrimeNG 19.rc.1 within 1 to 2 weeks. Thanks a lot for your understanding!

Are you a team of dev without a formal administration? If so that approach works great for dev to dev businesses like this one, for a while. Yet then as you grow bigger and bigger, administrative task grow disproportionally so you may hire some secretaries doing your bidding there and for a time, that may work too. Yet as you grow even bigger you need a non dev marketing manager , a technical manager who is a non participating software architect and a dedicated professional CEO.

Because if your meeting had included management, including marketing, I am sure they would have told you your approach will cost you a lot of customers and it certainly won't boost customer satisfaction. Now I don't know the percentage of your customers who like I am are using continuous integration in their software development process. my guess is very high. Anyway, we who do, my guess is, most of us, can't work with 3rd party code that doesn't understand or for some other reason is unable to meet that requirement. For one, because many of us then won't be able to meet our customers requirements. Not be able to update causes a lot of problems, security related for instance. The latest security fixes can't be implemented, to mention a highly important one.

**Comment by yarikwest** [comment]
Come on, guys! Don't be too harsh on the maintainers. Please remember that this is a free, open-source project. If you're eager to see updates, you can fork the repo or submit a PR to help speed up the work for the maintainers. Alternatively, you can use Angular Material, which is updated alongside Angular. Oh, wait, I almost forgot—it lacks many of the cool components that are available in PrimeNG.

I don't believe PrimeNG is the only library in your projects that doesn't update immediately after each new Angular version. I, too, am waiting for the possibility to upgrade to Angular 19. I have at least 10 large enterprise projects that need upgrading, but I prefer to wait a month for a well-tested library rather than rushing into an update with potential bugs.

**Comment by zygarios** [comment]
I use Material in projects, and sometimes PrimeNG. I definitely wouldn’t be so harsh on the creators when it comes to a free tool—I’d just express my disappointment and wait. However, if I were indeed a paying customer (@David-Ben-Mesecke claims he uses the paid version), I’d probably be upset about such an approach to updates as well... But it’s not my place, so I politely wait and hope the creators will improve the process.

**Comment by NateRadebaugh** [comment]
From my understanding, there's 2 things at play:
* Support Angular 19
* Support new prime theming 

The main desire from the prime team is that new prime theming is a breaking change and will only be supported starting in primeng 18+

The main desire from the community in this thread is to upgrade their current projects to angular 19 in-place without breaking changes.

Based on the conversation in #16783 it seems the only breaking change in angular 19 blocking primeng 17 from supporting angular 19 is the switching of default standalone from false to true.  If the prime components that are not currently standalone were updated to explicitly mark as `standalone: false`, would that be enough to satisfy the angular 19 runtime issues in a primeng v17 release?

**Comment by David-Ben-Mesecke** [comment]
> I use Material in projects, and sometimes PrimeNG. I definitely wouldn’t be so harsh on the creators when it comes to a free tool—I’d just express my disappointment and wait. However, if I were indeed a paying customer (@David-Ben-Mesecke claims he uses the paid version), I’d probably be upset about such an approach to updates as well... But it’s not my place, so I politely wait and hope the creators will improve the process.

I totally agree, if I hadn't paid for it, I would have formulated my critique differently. On the other hand, they are a business, thriving from what I can tell, and my critique while maybe a bit  on the harsher side, is well meant and constructive. I have a lifetime of experience in the business and I wrote it because I believe the critique, and suggestions for change may be valuable to them. 

Like most businesses, I paid for it because I wanted to support what was a great product that seemed to have the ambition to become even greater. But for me, and I am sure that goes for most of their customers, its not about the money, it's about the time invested in implementing the product into ours, which now may turn out to have been a complete waste of a significant amount of time and effort, depending on how this goes. Now in my case, its not even as bad as it may be for many others, I have planned to add a facade to abstract the ui component library, in about 12 month or so. It's a lot of work to go ahead and replace it. That is why businesses pay for their components, to ensure they are being well maintained and to be able to get support if or when needed. That is also why I bother writing this, hoping my, I believe good advice to their company, will motivate them to get this done before I am forced to switch libraries.

**Comment by mertsincan** [comment]
I truly value and respect all your feedback. First and foremost, PrimeNG is a 100% free and open-source project featuring over 80 components.

PrimeNG versions align with Angular’s versioning. For example, PrimeNG 19 will support Angular 19. If you’re using an older Angular version, you can select a compatible PrimeNG release. Why do we take this approach? While we deeply appreciate Angular’s rapid evolution and many improvements, it can be challenging for library developers like us. Supporting multiple Angular versions simultaneously often leads to compatibility headaches—such as making a feature work in Angular 18 but not 17 or 19. We've faced this many times. To simplify things for both our team and our users, we tie PrimeNG versions to Angular versions.

Why don’t we release new versions immediately after Angular updates? Because we have a packed roadmap! One major focus is the new theming engine, designed to make theme creation easier and integrate seamlessly with Figma. We're nearly finished with that. Next, we'll introduce the new pt structure from PrimeVue into PrimeNG, giving users enhanced control over DOM elements—for tasks like event binding or adding attributes. Additionally, RTL (right-to-left) support is now fully implemented with version 18.

Remember, PrimeNG includes over 80 components, each with its own complexities. Ensuring they work together seamlessly, while testing and optimizing performance, takes time. If we only had 10 components, we could move much faster! So while we aim to support new Angular versions as quickly as possible, it’s not an instant process. That said, we’re closely following Angular’s developments—this recent improvement, for instance, is one we’re really excited about.

Regarding paid products like PrimeBlocks, Templates, and UI kits, we’re always transparent about what’s supported. We never have a misleading statement in these such as the next version will be released immediately or that it is currently supported. When we release updates, it’s not just about changing the version number—we also refresh the designs, test usability, and add new features and improvements.

Finally, here’s the exciting news: we’re planning to release 18-rc.1 this week, and 19-rc.1 a week after that. Thank you for your understanding! Always bet on Prime!

**Comment by zygarios** [comment]
Thank you for your point of view :) it's honest

**Comment by dhuome** [comment]
Hi PrimeNG Team,

I’m starting a new major project with Angular 19 and wanted to check if there’s any update or ETA for resolving [Issue #16827]. Your work is greatly appreciated, and knowing the status would help me plan accordingly.

Thanks in advance!

**Comment by eluchsinger** [comment]
I'm a bit concerned, because we updated a major platform to Angular 19 and PrimeNg 17.18.12 seems to be working flawlessly in production with many many users. What exactly should be broken?

**Comment by imaksp** [comment]
> I'm a bit concerned, because we updated a major platform to Angular 19 and PrimeNg 17.18.12 seems to be working flawlessly in production with many many users. What exactly should be broken?

you can check this: https://github.com/primefaces/primeng/pull/16783#issuecomment-2491842355
its related to default standalone with Angular 19, not all components uses standalone true in primeng, with v19 standalone false needs to be added, angular 19 also has some breaking change related to `effect` timing.

**Comment by seancampbell3161** [comment]
> Hi PrimeNG Team,
> 
> I’m starting a new major project with Angular 19 and wanted to check if there’s any update or ETA for resolving [Issue #16827]. Your work is greatly appreciated, and knowing the status would help me plan accordingly.
> 
> Thanks in advance!

As mertsincan just said above, v19-rc.1 is expected next week sometime.

**Comment by dhuome** [comment]
> > Hi PrimeNG Team,
> > I’m starting a new major project with Angular 19 and wanted to check if there’s any update or ETA for resolving [Issue #16827]. Your work is greatly appreciated, and knowing the status would help me plan accordingly.
> > Thanks in advance!
> 
> As mertsincan just said above, v19-rc.1 is expected next week sometime.

No, I meant the v19 Final release.

**Comment by radarsu** [comment]
For people interested with a dirty, temporary workaround, Angular 19 works with Primeng 18, if after installing dependencies you do:
1. Kill angular app.
2. Delete angular cache.
3. Run `find ./node_modules/primeng/fesm2022 -type f -name "*.mjs" -exec sed -i 's/, i0\.ɵɵStandaloneFeature],/],/g' {} +`.
4. Enjoy.

**Comment by robmanganelly** [comment]
MAC folks using @radarsu 's script 👀 
```json    
"postinstall": "find ./node_modules/primeng/fesm2022 -type f -name \"*.mjs\" -exec sed -i '' 's/, i0\\.ɵɵStandaloneFeature],/],/g' {} +"
```

**Comment by JakeAi** [comment]
> For people interested with a dirty, temporary workaround, Angular 19 works with Primeng 18, if after installing dependencies you do:
> 
> 1. Kill angular app.
> 2. Delete angular cache.
> 3. Run `find ./node_modules/primeng/fesm2022 -type f -name "*.mjs" -exec sed -i 's/, i0\.ɵɵStandaloneFeature],/],/g' {} +`
> 4. Enjoy.
> 
> Above could as well be added in `package.json` postinstall script for convenience:
> 
> ```json
> "scripts": {
>     "postinstall": "find ./node_modules/primeng/fesm2022 -type f -name \"*.mjs\" -exec sed -i 's/, i0\\.ɵɵStandaloneFeature],/],/g' {} +"
> },
> ```

Thanks for this. Have you noticed any side effects?

**Comment by radarsu** [comment]
@JakeAi 
Haven't, so far it works like a charm for me.

**Comment by JakeAi** [comment]
> @JakeAi Haven't, so far it works like a charm for me.

I'm working on a new project using angular 18, but the new signal functionality is a must have. I feel by the time I'm "done," I'd have to refactor to v19. I haven't noticed anything yet either.

**Comment by radarsu** [comment]
@JakeAi yeah, the signals make whole codebase so much more managable. I'd recommend mastering them quickly.

I do a project with Angular 19 fully based on signals, primeng 18 and tailwind v4 beta. Figuring out perfect setup was tough, but those new releases solve so many problems I was struggling with in the past it's worth it (state management with signals feels so much better, management of primitive and semantic CSS values and components, theming and light/dark modes).

I even ditched zone.js, everything is working great and I no longer have obscured stack traces.

Feel free to contact me privately if you'd like to copy my setup.

**Comment by imaksp** [comment]
Hi @radarsu zoneless is working with primeng v18?, AFAIK zoneless is not supported by this lib yet.

**Comment by radarsu** [comment]
@imaksp 
Haven't yet encountered any problems without it, I use OnPush changeDetection strategy and signals everywhere. But so far I use just few simple components from PrimeNG in that setup, maybe some advanced ones will have problems.

**Comment by Odex64** [comment]
@radarsu Hey, how did you manage to install Tailwind v4? I get a bunch of errors while attempting to install that in a clean Angular v19 project.

**Comment by radarsu** [comment]
@Odex64 
I started with:
1. `pnpm i -D tailwindcss@next @tailwindcss/postcss@next`
2. I created `postcss.config.json` in root of project:
```json
{
    "plugins": {
        "@tailwindcss/postcss": {}
    }
}
```
3. I added `theme.css` file in `src/styles`:
```css
@import 'tailwindcss';

@theme {
    --color-*: initial;
    --font-*: initial;
   /* ... */
    --color-primary-500: var(--p-primary-500);
    --color-error-500: var(--p-error-500);
}
```
4. I imported theme.css file in my `index.scss` that's loaded by `angular.json`.
```scss
@use './primeng.scss' as *;
@use './components.scss' as *;
@use './utilities.scss' as *;
@import './theme.css';
```

Major nuances I experienced were:
1. It didn't work when I tried using another format than postcss.config.json.
2. It didn't work when I used tailwind @theme in `.scss` file, so I had to keep tailwind configuration in `.css`.
3. It didn't work when I used `@use './theme.css' as *;` instead of `@import './theme.css';`.

**Comment by slawanextlevels** [comment]
Im still getting also with the postinstall

```

Uncaught TypeError: fn is not a function
    at core.mjs:19413:38
    at Array.forEach (<anonymous>)
    at initFeatures (core.mjs:19413:24)
    at Object.toString (core.mjs:19275:5)
    at noSideEffects (core.mjs:122:5)
    at ɵɵdefineComponent (core.mjs:19240:10)
    at <static_initializer> (primeng-menu.mjs:720:33)
    at primeng-menu.mjs:703:1
```

**Comment by radarsu** [comment]
@slawanextlevels make sure you have killed an angular app then cleaned angular cache directory, then run script and error should be gone.

**Comment by mertsincan** [comment]
Hi everyone,

Thank you so much for the PRs and feedback! PrimeNG 19 now works with Angular 19. Today, we plan to release PrimeNG 19-rc.1 so you can test it and share your thoughts.
https://github.com/primefaces/primeng/compare/master...v19

I’d also like to talk about what’s next for PrimeNG 20. In v18 and v19, our main focus was building the [new theming engine](https://primeng.org/theming), and now it’s complete. For PrimeNG 20, we want to improve the codebase completely. This includes using strict types, adding more tests, moving to a signal-based and zoneless structure, and updating all components with the latest best Angular practices. We have a lot of internal improvements planned and will share more details with you soon.

**Comment by yarikwest** [comment]
> Hi everyone,
> 
> Thank you so much for the PRs and feedback! PrimeNG 19 now works with Angular 19. Today, we plan to release PrimeNG 19-rc.1 so you can test it and share your thoughts. [master...v19](https://github.com/primefaces/primeng/compare/master...v19)
> 
> I’d also like to talk about what’s next for PrimeNG 20. In v18 and v19, our main focus was building the [new theming engine](https://primeng.org/theming), and now it’s complete. For PrimeNG 20, we want to improve the codebase completely. This includes using strict types, adding more tests, moving to a signal-based and zoneless structure, and updating all components with the latest best Angular practices. We have a lot of internal improvements planned and will share more details with you soon.

When is the planned final release of v19?

**Comment by mertsincan** [comment]
> When is the planned final release of v19?
Unless there are any major issues, we plan to release PrimeNG v19.Final the next week.

**Comment by slawanextlevels** [comment]
I got [master...v19](https://github.com/primefaces/primeng/compare/master...v19) running. Thank you

**Comment by mertsincan** [comment]
PrimeNG 19.0.0-rc.1 Released; https://www.npmjs.com/package/primeng/v/19.0.0-rc.1

**Comment by dalenguyen** [comment]
Confirmed that 19.0.0-rc.1 fixed the `Uncaught TypeError: fn is not a function` issue on my end :)

**Comment by gbarrionuevo** [comment]
https://github.com/primefaces/primeng/issues/17005

**Comment by dragsense** [comment]
PrimeNG 19.0.0-rc.1 working fine with angular 19

**Comment by alvaroaxo** [comment]
Confirmed, PrimeNG 19rc works with Angular 19

**Comment by lalo-mx** [comment]
I have an issue with 19rc, how are the styles configured now?

```
@import "primeng/resources/themes/fluent-light/theme.css";
```

```
X [ERROR] Could not resolve "primeng/resources/themes/fluent-light/theme.css"

    src/primeng.scss:1:8:
      1 │ @import "primeng/resources/themes/fluent-light/theme.css";
        ╵         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The path "./resources/themes/fluent-light/theme.css" is not exported by package "primeng":

    node_modules/primeng/package.json:46:13:
      46 │   "exports": {
         ╵              ^

```

**Comment by Delagen** [comment]
@lalo-mx RTFM, migration guide is published https://primeng.org/guides/migration

**Comment by dragsense** [comment]
> I have an issue with 19rc, how are the styles configured now?
> 
> ```
> @import "primeng/resources/themes/fluent-light/theme.css";
> ```
> 
> ```
> X [ERROR] Could not resolve "primeng/resources/themes/fluent-light/theme.css"
> 
>     src/primeng.scss:1:8:
>       1 │ @import "primeng/resources/themes/fluent-light/theme.css";
>         ╵         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
>   The path "./resources/themes/fluent-light/theme.css" is not exported by package "primeng":
> 
>     node_modules/primeng/package.json:46:13:
>       46 │   "exports": {
>          ╵              ^
> ```

no need to import the css files.

https://primeng.org/theming

Configuration API
Theme
The theme property is used to customize the initial theme.

import { ApplicationConfig } from '@angular/core';
import { provideAnimationsAsync } from '@angular/platform-browser/animations/async';
import { providePrimeNG } from 'primeng/config';
import Aura from '@primeng/themes/aura';

export const appConfig: ApplicationConfig = {
    providers: [
        provideAnimationsAsync(),
        providePrimeNG({ 
            theme: {
                preset: Aura
            }
        })
    ]
};

**Comment by ThoSap** [comment]
@radarsu I do the same, I have a PrimeNG 17.18.15 application with Angular 19.0.5 and it is completely zoneless with `ChangeDetectionStrategy.OnPush` and signals.

Zoneless with signals everywhere already worked before I upgraded to Angular 19 with Angular 18.2.0 and PrimeNG 17.18.9, no issues have been reported by any user so far and Zoneless with this setup has been in production since May 2024.

> @JakeAi yeah, the signals make whole codebase so much more managable. I'd recommend mastering them quickly and Angular 19 release is crazy good, so on new project you might want to consider upgrading quickly.
> 
> I do a project with Angular 19 fully based on signals, primeng 18 and tailwind v4 beta. Figuring out perfect setup was tough, but those new releases solve so many problems I was struggling with in the past it's worth it (state management with signals feels so much better, management of primitive and semantic CSS values and components, theming and light/dark modes).
> 
> I even uninstalled zone.js and did zoneless angular and everything is working great, I no longer have obscured stack traces.
> 
> Feel free to contact me privately if you'd like to copy my setup.

> @imaksp Haven't yet encountered any problems without it. I use OnPush changeDetection strategy and manage data via signals everywhere. But so far I use just few simple components from PrimeNG in that setup, maybe some advanced ones will have problems.

**Comment by sergey-morenets** [comment]
> @lalo-mx RTFM, migration guide is published https://primeng.org/guides/migration

Hi @Delagen 

It's not clear whether Primeng 19+ supports non-standalone configuration. In the "Getting started" guide(https://primeng.org/installation) there's a following configuration which can be applied for standalone components only:

```
export const appConfig: ApplicationConfig = {
    providers: [
        provideAnimationsAsync(),
        providePrimeNG({
            theme: {
                preset: Aura
            }
        })
    ]
};
```

**Comment by Delagen** [comment]
@sergey-morenets It's common configuration whenever use standalone or not. It's just new syntax and provider functions. Just read docs.

**Comment by ibandim123** [comment]
> Confirmed, PrimeNG 19rc works with Angular 19

This confirmed?

**Comment by jex-novatec** [comment]
For me it's not working with the following versions:
`"dependencies": {
    "@angular/common": "~19.1.0",
    "@angular/compiler": "~19.1.0",
    "@angular/core": "~19.1.0",
    "@primeng/themes": "^19.0.6",
    "primeng": "^19.0.5"
  },`

**Comment by gatzsche** [comment]
> For me it's not working with the following versions: `"dependencies": { "@angular/common": "~19.1.0", "@angular/compiler": "~19.1.0", "@angular/core": "~19.1.0", "@primeng/themes": "^19.0.6", "primeng": "^19.0.5" },`

Are there versions that are working?

**Comment by samjs89** [comment]
@jex-novatec Same for me. not working. below are my dependencies.


`{
    "@angular/animations": "^19.1.0",
    "@angular/common": "^19.1.0",
    "@angular/compiler": "^19.1.0",
    "@angular/core": "^19.1.0",
    "@angular/forms": "^19.1.0",
    "@angular/platform-browser": "^19.1.0",
    "@angular/platform-browser-dynamic": "^19.1.0",
    "@angular/router": "^19.1.0",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.15.0"
  }`

**Comment by gatzsche** [comment]
The error results from primeng-icons-baseicon.mjs, 105:
```
features: [i0.ɵɵProvidersFeature([BaseIconStyle]), i0.ɵɵInputTransformsFeature, i0.ɵɵInheritDefinitionFeature],
```

The value `i0.ɵɵInputTransformsFeature` is undefined.

`i0` again is imported via `import * as i0 from '@angular/core';`

Why is `i0.eeInputTransformFeature` undefined?

Was it removed from the latest angular version?

**Comment by gatzsche** [comment]
I found it: `ɵɵInputTransformsFeature` has been removed in Angular 19.1.7. It is available in Angular 19.1.6.

Restricting Angular to 19.1.6 should remove the issue temporarily.

**Comment by gatzsche** [comment]
You need to remove the ^ from the version numbers, which means that in the background minor patches like 19.1.7 are installed. But then you need to increase the versions manually.

**Comment by danielschmitz** [comment]
> You need to remove the ^ from the version numbers, which means that in the background minor patches like 19.1.7 are installed. But then you need to increase the versions manually.

```
"dependencies": {
    "@angular/animations": "19.1.7",
    "@angular/common": "19.1.7",
    "@angular/compiler": "19.1.7",
    "@angular/core": "19.1.7",
    "@angular/forms": "19.1.7",
    "@angular/platform-browser": "19.1.7",
    "@angular/platform-browser-dynamic": "19.1.7",
    "@angular/router": "19.1.7",
    "@primeng/themes": "^19.0.6",
    "primeng": "^19.0.6",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.15.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^19.1.5",
    "@angular/cli": "^19.1.5",
    "@angular/compiler-cli": "19.1.7",
    "@types/jasmine": "~5.1.0",
    "jasmine-core": "~5.5.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "typescript": "~5.7.2"
  }
```

still not working... any tip?

**Comment by gatzsche** [comment]
This should do it:

```json
"dependencies": {
    "@angular/animations": "<=19.1.6",
    "@angular/common": "<=19.1.6",
    "@angular/compiler": "<=19.1.6",
    "@angular/core": "<=19.1.6",
    "@angular/forms": "<=19.1.6",
    "@angular/platform-browser": "<=19.1.6",
    "@angular/platform-browser-dynamic": "<=19.1.6",
    "@angular/router": "<=19.1.6",
    "@primeng/themes": "^19.0.6",
    "primeng": "^19.0.6",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.15.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "<=19.1.5",
    "@angular/cli": "<=19.1.6",
    "@angular/compiler-cli": "<=19.1.6",
    "@types/jasmine": "~5.1.0",
    "jasmine-core": "~5.5.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "typescript": "~5.7.2"
  }
```

**Comment by gatzsche** [comment]
> 
> still not working... any tip?

See my comment before. Version 19.1.7 is broken. Replace it by <= 19.1.6.

**Comment by danielschmitz** [comment]
It didn't work either. Can you publish a newly created project on GitHub with only the button from the tutorial working?

In theory, PrimeNG should work just by doing the standard installation, without this postinstall or version adjustment. I hope they fix this ASAP.

**Comment by gatzsche** [comment]
There is already an issue for that:

https://github.com/primefaces/primeng/issues/17730

**Comment by pastagaz69** [comment]
> > still not working... any tip?
> 
> See my comment before. Version 19.1.7 is broken. Replace it by <= 19.1.6.

Thanks a lot ! workaround works like a charm
