### ISSUE TITLE
Filtering for Tree

### ISSUE THREAD

**Issue by agusdutra** [primefaces/primeng#1683]
It would be really nice to have a filtering box that can be added to Trees and filters the TreeNode[] on the component without losing the selection and the original TreeNode[].

The filter could work with the label of the Tree Nodes.
 
In a project I'm using checkable tree nodes and sometimes it gets a bit hard to find some nodes.

I'm talking about some filter like this: 
http://ee.github.io/angular-ui-tree-filter/

Thanks.

**Comment by ajmair01** [comment]
Agreed :point_up:. We are using the tree component for selecting across a large hierarchy. Would be very nice to have filtering support without having to write custom code to support it.

**Comment by cagataycivici** [comment]
@mertsincan did it for PrimeFaces, we can do similar I believe.

**Comment by olegkon** [comment]
This Search/Filter is very important for us.
Can we vote on that issue?  +1

When can we expect it done?

TIA,
Oleg.

**Comment by PrajwalGonsalves07** [comment]
+1

**Comment by beaugogh** [comment]
+1

**Comment by pepe-escrich** [comment]
+1

**Comment by mkseng** [comment]
+1

**Comment by saikiranmandhala** [comment]
+1

**Comment by seeshadows** [comment]
+1

**Comment by banejo** [comment]
+1

**Comment by kkcode24** [comment]
+1

**Comment by mchauhan** [comment]
+1

**Comment by claudiuconstantin** [comment]
Any milestone for this?

**Comment by ethnoplex** [comment]
+1

**Comment by skormel** [comment]
+1

**Comment by CarlinhosSousaJunior** [comment]
+1

**Comment by j1j** [comment]
+1

**Comment by mediaaminian** [comment]
+1

**Comment by cal2sms** [comment]
+1

**Comment by alaa9jo** [comment]
+1

**Comment by akashdeepg12** [comment]
It would be very good to  have global functionality in PrimeNg tree.Atleast user can search any file/folder globally by using global filter box..

**Comment by Fiszi** [comment]
+1

**Comment by claudiuconstantin** [comment]
Any updates on this one?

**Comment by cagataycivici** [comment]
Not in the scope of new TreeTable of 6.0.

**Comment by chennoam7** [comment]
Hi,
We need it too, it will be a great feature.
Thanks, 
Chen

**Comment by lucky1ravi** [comment]
Any update on this feature.

**Comment by i23591326** [comment]
I have implemented TreeTable filtering on my own by hiding rows in "body" template, since it's fully available for rewriting. However, in the case of Tree component, I cannot hide node using the same trick, since only a small part of tree node is customizable by templating. 
Could anyone advise a workaround here?

**Comment by kariponkko** [comment]
Any updates for this feature?

**Comment by RingoKam** [comment]
Not sure if this would help, following function would find the node you are searching for and expand it and its parent. 

```javascript
         /**
	 * @param {TreeNode} node primeng tree node data
	 * @param {string} propField name of the property you are searching for ex: label
	 * @param {any} searchValue value you are searching for
	 */
	filterExpandRecursive(
		node: TreeNode,
		propField: string,
		searchValue: any
	): boolean {
		const isMatchSearchField = node[propField] === searchValue;
		node.expanded =
			node.children &&
			node.children.length > 0 &&
			node.children.some(childNode =>
				this.filterExpandRecursive(childNode, propField, searchValue)
			);
		return isMatchSearchField || node.expanded;
	}
`

**Comment by umangsavaliya** [comment]
Implemented Tree filter below solution:
https://codereview.stackexchange.com/questions/148273/filtering-a-deep-array

**Comment by raycola** [comment]
Hi,
 will TreeTable's Filtering be released with 7.0.0?
please It's very important

good job

**Comment by claudiuconstantin** [comment]
It seems that this will be included in 7.0.0-beta.2 (7.0.0-beta.1 was released today)

**Comment by cagataycivici** [comment]
We got something working but kinda ran out of time for 7.0.0-final so will be in 7.0.1.

**Comment by mertsincan** [comment]
Added 3 attributes to tree;

Name | Type | Default | Description
-- | -- | -- | --
filter | boolean | false | When specified, displays an input field to filter the items.
filterBy | string | label | When filtering is enabled, filterBy decides which field or fields (comma separated) to search against.
filterMode | string | lenient | Mode for filtering valid values are lenient and strict. Default is lenient.

**Comment by eltigree** [comment]
In wich Release this filter for TreeTable will come? In actual Release 7.0.5 is this not included, thnx

**Comment by mertsincan** [comment]
Yes, I'm working on it.

**Comment by mertsincan** [comment]
Please see this issue; https://github.com/primefaces/primeng/issues/7230

**Comment by eltigree** [comment]
Thnx a lot @mertsincan! Great work!

**Comment by mertsincan** [comment]
You're welcome! Also, please see #7237 for Tree with filter and checkbox selection.

**Comment by akinihsan** [comment]
Teşekkürler elinize sağlık.

**Comment by ludakhris** [comment]
This is AWESOME! I was using an older version and was literally just looking for this feature!

**Comment by jigneshkhatri** [comment]
Facing serious issue when selecting any node, after applying filter:

![image](https://user-images.githubusercontent.com/8259729/65271710-55c46b00-db3b-11e9-80d4-d12e197fb018.png)

Any workaround?

Angular: **8.0.2**
primeng: **8.0.1**

**Comment by szh** [comment]
@jigneshkhatri Are you doing something in the event handler that's causing it to change the selection, thereby calling the event handler again? It looks like something's causing an infinite loop

**Comment by jigneshkhatri** [comment]
@szh : Nope. Just have plain `<p-tree>` like this:

`          <p-tree [filter]="true" filterMode="strict" [value]="features" selectionMode="checkbox"
            [propagateSelectionUp]="true" [propagateSelectionDown]="true"></p-tree>`

Without filter, it is working fine.

**Comment by jigneshkhatri** [comment]
Have anyone found any solution for this issue?

**Comment by AJBauwens** [comment]
Problem for me when using filter is that NodeSelect always selects top item in the tree irrespective of clicked node or whether or not the top node complies with the filter.

The filter is thus unusable

**Comment by mGershtein** [comment]
Check this out: https://github.com/primefaces/primeng/issues/7397

The selection after filtering will work if the nodes are provided with a unique key

**Comment by AJBauwens** [comment]
Thanks for this. Adding the key does enable me to identify the selected
node through the event but sadly seems to force the filter into strict mode
so that I am unable to see any child nodes.

**Comment by ezespman** [comment]
Is there a way, the filter would only run when user press enter instead of pressing keys? that will be game change. otherwise, is there a way to run the filter from code?

**Comment by cyberrranger** [comment]
i m use a filter without click enter

```
<input (input)="filter($event)" pInputText placeholder="{{'Suche' | translate}}">

<p-treeTable ..... #tt> .......

filter(event: any) {
		let query = event.target.value;
		if (query.length >= 3) {
			this.hasFilter = false;
			this.query = query;
			this.tt.filter(query, "global", "contains");
		} else {
			this.tt.filter(null, "global", "contains");
			if (!query) {
				this.query = null;
			}
		}
	}
```

**Comment by ezespman** [comment]
Thanks Cyber Ranger, But p-tree is another story. It could be an option to let user press enter to traverse through the tree especially for large data. Or click the search button after they type.

Cheers,
Ezechias Dominique

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ezespman** [comment]
Greetings cyberranger,

            As you know, we are in a situation that is dire because we have to make sure we stay healthy and also to take care our love ones. It is a challenge for us now, since we are not used to stay in a confined place for amount of time and if we have to take care our loved ones, such as our family members, and other people.

            But there is a light in this darkness, the light is found in the bible that helps a lot of people to cope with situations that they are currently dealing. It will be great help to you, as it can provide some practical wisdom that you can use to apply. One verse, I would like to share with you is ISAIAH 33:24:
And no resident*<https://www.jw.org/en/library/bible/nwt/books/isaiah/33/#fn114213414> will say: “I am sick.”+<https://www.jw.org/en/library/bible/nwt/books/isaiah/33/#v23033001-v23033024>The people dwelling in the land will be pardoned for their error.+<https://www.jw.org/en/library/bible/nwt/books/isaiah/33/#v23033001-v23033024>

    Yes one day, we won't have to deal with this type of situation but as of now, we have to endure this for a short while. The day of hpe will happen under Jehovah's Kingdom with Jesus Christ as King. In the meantime, do not be stressful because that will cause unnecessary risks to you health and loved ones(Proverbs 14:30).

    In the meantime, the video link below will give more info about why the bible is a book to study.

    Online Video Library | JW.ORG Videos English<https://www.jw.org/en/library/videos/#en/mediaitems/VODMinistryTools/pub-wsb_1_VIDEO>

Online Video Library | JW.ORG Videos English

Bible-based movies and videos for families, teenagers, and children. Documentaries about Jehovah’s Witnesses. Wa...




Thanks,
Ezechias Dominique

**Comment by ghassenrachid** [comment]
You have to add a key for every item in your tree check this solution with primeng 11.3.0 
[stackblitz](https://stackblitz.com/edit/primeng-treeselection-demo-2pnk19?file=src%2Fapp%2Fapp.component.html)
