### ISSUE TITLE
Datatable stop ordering the columns

### ISSUE THREAD

**Issue by sgomanf** [primefaces/primeng#1684]
When updating to the version 1.1.2, datatable stopped working the ordering of the columns. When I click on the column I want to sort, it orders a different column. If back to version 1.1.1 works correctly

Angular version 2.3.1

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
