### ISSUE TITLE
Drawer: deprecated showCloseIcon needed

### ISSUE THREAD

**Issue by JuncalLP** [primefaces/primeng#16848]
### Describe the bug

For the Drawer component, [showCloseIcon] is deprecated and we're instructed to use [closable] instead. However, as the component uses ORs checking both and they both default to true, to get a non closable Drawer we need to set both to false. 

### Environment

Windows 10, Mozilla Firefox

### Angular version

18.2.0

### PrimeNG version

18.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22.9

### Steps to reproduce the behavior

Create a template with a Drawer and set [closable]=false, you'll still see the close icon until you set [showCloseIcon]=false too.

### Expected behavior

The use of the non deprecated input should suffice

**Comment by cetincakiroglu** [comment]
fixed in https://github.com/primefaces/primeng/commit/d4080704306aa8902459a5b35635edd1b92bb620

**Comment by JuncalLP** [comment]
> fixed in [d408070](https://github.com/primefaces/primeng/commit/d4080704306aa8902459a5b35635edd1b92bb620)

I don't think this solves the issue fully, now if you set non deprecated input to true and deprecated one to false you get a non closable drawer. If both inputs are set I think the standard would be the component should honor the non deprecated one and issue some kind of warning.
