### ISSUE TITLE
PTooltip: Setting border-radius in a new style does not change the container class .p-tooltip border radius

### ISSUE THREAD

**Issue by albertB4work** [primefaces/primeng#16854]
### Describe the bug

This is my style 

.candidateCardDetailsTooltip:extend(jobInscriptionsTooltip) {
  &.p-tooltip {
    max-width: 191px;
    border-radius: 12px;
  }
  .p-tooltip-arrow {
      //... styles
    }
  .p-tooltip-text {
    // styles
  }
}

When I put 20px or 200px the border radius is always the same

![Captura de pantalla 2024-11-26 a las 16 37 19](https://github.com/user-attachments/assets/4a14d693-c8f5-46d1-8572-0f2e74ab09c5)

### Environment

Angular project with Angular 18

### Angular version

18.2.12

### PrimeNG version

17.18.12

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

10.9.1

### Expected behavior

Change the border-radius to style the tooltip

**Comment by mertsincan** [comment]
Which PrimeNG version are you using? 17.18.12?
