### ISSUE TITLE
Dynamic Dialog: log ERROR when closable is false or not set

### ISSUE THREAD

**Issue by aboudard** [primefaces/primeng#16852]
### Describe the bug

When running an `open` method on `DialogService`, is you set [closable] to false, or omit the input, the console is logging an ERROR like this:
`ERROR RangeError: Maximum call stack size exceeded`
![image](https://github.com/user-attachments/assets/df13c0d2-f783-4284-95fd-ff045e7f2625)

### Environment

Local environnement Windows 11, reproduced on StackBlitz, see below

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-3g88jq?file=src%2Fmain.ts

### Angular version

18.1.0

### PrimeNG version

18.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.20.3

### Browser(s)

Chrome 131

### Steps to reproduce the behavior

Run the project, click on the button, check the console in devtools.

### Expected behavior

Should not log an ERROR in any case.

**Comment by aboudard** [comment]
I just edited the issue with another Stackblitz, based on the PrimeNg template.
The ERROR is there. I also reproduced the bug in the showcase application with a newly created component.

**Comment by JakeAi** [comment]
I also have this issue @mehmetcetin01140

**Comment by john8329** [comment]
Same here, this is definitely happening with 18.0.6-lts, I'll update if I have a reproducibility.

**Comment by john8329** [comment]
Two components with the exact same configuration but in different places have different behaviors, one works the other doesn't. Tracing it shows that `(@animation.start)="onAnimationStart($event)"` in p-dynamicdialog triggers `focus()` which then repeats itself over and over on line 476 because `DomHandler.getFocusableElement(focusParentElement);` fails. Inspecting it reveals that `DomHandler` is a module and not a class..? There's some webpack trickery happening here maybe. For now I'll patch this and disable the call since it breaks prod.

```patch
diff --git a/esm2022/dynamicdialog/dynamicdialog.mjs b/esm2022/dynamicdialog/dynamicdialog.mjs
index 7a032010e528d8cc8b3ed3f2bf1a8ecdbed034b4..084d0b02e1d4aec1cb46d39157aa33ea06e83751 100644
--- a/esm2022/dynamicdialog/dynamicdialog.mjs
+++ b/esm2022/dynamicdialog/dynamicdialog.mjs
@@ -513,7 +513,7 @@ export class DynamicDialogComponent extends BaseComponent {
             this.focus(this.footerViewChild.nativeElement);
         }
         else if (!focusableElement && this.headerViewChild) {
-            this.focus(this.headerViewChild.nativeElement);
+            //this.focus(this.headerViewChild.nativeElement);
         }
     }
     maximize() {
diff --git a/fesm2022/primeng-dynamicdialog.mjs b/fesm2022/primeng-dynamicdialog.mjs
index 777b576444f69c454e6214d94ec36b97b40c3017..1c7d6f75e71b39872ce759d01cb991cabf97e5f8 100644
--- a/fesm2022/primeng-dynamicdialog.mjs
+++ b/fesm2022/primeng-dynamicdialog.mjs
@@ -885,7 +885,7 @@ class DynamicDialogComponent extends BaseComponent {
             this.focus(this.footerViewChild.nativeElement);
         }
         else if (!focusableElement && this.headerViewChild) {
-            this.focus(this.headerViewChild.nativeElement);
+            //this.focus(this.headerViewChild.nativeElement);
         }
     }
     maximize() {
```
