### ISSUE TITLE
Table ColumnFilter: Filter method not setable

### ISSUE THREAD

**Issue by shaman-apprentice** [primefaces/primeng#16867]
### Describe the bug

Filter method of column filter is not set correctly.

### Steps to reproduce the behavior

1. Go to https://v18.primeng.org/table#filter-advanced
2. Click on filter of name header
3. Chose "Contains" as filter method
4. Enter "Butt"

### Observed behavior

- No entries are shown
- When re-opening the filter, the filter method is set to "Starts with"

### Expected behavior

- First row with name "James Butt" is shown
- When re-opening the filter, the filter method is set to "Contains"

### Reproducer

https://v18.primeng.org/table#filter-advanced

### Angular version

18.x.x

### PrimeNG version

18.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22.10.0

### Browser(s)

Chrome

**Comment by rosenthalj** [comment]
Almost all of the column filters in the 18rc2 table advance filter demo are broken.  When fixing this issue,  all table column filters need to be verified/fixed.

**Comment by cetincakiroglu** [comment]
Hi,

This issue is fixed in https://github.com/primefaces/primeng/commit/61dca6acdf798637fb325b14f101e1f5b99ef808 and the fix will be available by upcoming release.
