### ISSUE TITLE
DatePicker: Icons are wrong in RTL mode

### ISSUE THREAD

**Issue by khobabc** [primefaces/primeng#16873]
### Describe the bug

In RTL mode, date picker forward or reverse icons, as well as input icons show on the wrong side.

![image](https://github.com/user-attachments/assets/aa22d35c-efd9-4581-ae8a-df27c1be5ba2)

This screenshot is from official PrimeNG 18 docs.

### Environment

Chrome on MacOS

### Reproducer

https://v18.primeng.org/datepicker

### Angular version

18.2.12

### PrimeNG version

18.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.20.2

**Comment by mertsincan** [comment]
Fixed for the next version. Thank you!
