### ISSUE TITLE
Uncaught TypeError: fn is not a function - PrimeNG 18-RC.2

### ISSUE THREAD

**Issue by dalenguyen** [primefaces/primeng#16895]
### Describe the bug

The issue appears when using Angular v19 & PrimeNG v18 RC

<img width="449" alt="image" src="https://github.com/user-attachments/assets/e84b9360-7dca-49f9-bacf-7484439a2ecb">

```
// node_modules/@angular/core/fesm2022/core.mjs
function initFeatures(definition) {
  definition.features?.forEach(fn => fn(definition));
}

// primeng/fesm2022/primeng-icons-baseicon.mjs

  static ɵcmp = /*@__PURE__*/i0.ɵɵdefineComponent({
    type: BaseIcon,
    selectors: [["ng-component"]],
    hostAttrs: [1, "p-component", "p-iconwrapper"],
    inputs: {
      label: "label",
      spin: [2, "spin", "spin", booleanAttribute],
      styleClass: "styleClass"
    },

```

### Environment

Production

### Angular version

19.0.1

### PrimeNG version

18.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20

### Browser(s)

Chrome

**Comment by slawanextlevels** [comment]
Interesting Fact: 18.0.0-beta.3 with Angular v19 works

**Comment by mertsincan** [comment]
https://github.com/primefaces/primeng/issues/16827

**Comment by dalenguyen** [comment]
@slawanextlevels I tried that beta version. It has the same error.

**Comment by DanielGabbay** [comment]
It still doesn't work for me - I've tried all the beta versions of Primeng, including rc and including the official version 18.0.0 (the latest one released), and it doesn't work with Angular 19 (which is also up to date).

**Comment by dorji-dev** [comment]
Similar issue here but from divider component it seems: 
<img width="419" alt="Screenshot 2024-12-12 at 00 26 26" src="https://github.com/user-attachments/assets/233a7547-b2ab-4427-a9df-ffc28b8f5393" />

`"primeng": "^18.0.0"`
`"@primeng/themes": "^18.0.0"`
`"@angular/core": "^19.0.0"`

**Comment by Delsus78** [comment]
Similar here too with 
angular/core ^19.0.4 
primeng ^18.0.0
primeicons 7.0.0 (but dont work without too)

```
ERROR TypeError: fn is not a function
    at core.mjs:19413:38
    at Array.forEach (<anonymous>)
    at initFeatures (core.mjs:19413:24)
    at Object.toString (core.mjs:19275:5)
    at noSideEffects (core.mjs:122:5)
    at ɵɵdefineComponent (core.mjs:19240:10)
    at <static_initializer> (primeng-icons-baseicon.mjs:96:33)
    at primeng-icons-baseicon.mjs:70:24
    ```

**Comment by SteveRuben** [comment]
Similar here too with
angular/core ^19.0.4
primeng ^18.0.0
primeicons 7.0.0 (but dont work without too)

core.mjs:19413 Uncaught TypeError: fn is not a function
    at core.mjs:19413:38
    at Array.forEach (<anonymous>)
    at initFeatures (core.mjs:19413:24)
    at Object.toString (core.mjs:19275:5)
    at noSideEffects (core.mjs:122:5)
    at ɵɵdefineComponent (core.mjs:19240:10)
    at <static_initializer> (primeng-badge.mjs:489:33)
    at primeng-badge.mjs:429:21

**Comment by mertsincan** [comment]
PrimeNG **18** for Angular **18**

PrimeNG **19** for Angular **19**

https://github.com/primefaces/primeng/issues/16827

**Comment by igorosabel** [comment]
I just got the same error with Angular 19.1.7 and PrimeNG 19.0.6

Uncaught TypeError: fn is not a function
    at core.mjs:19348:38
    at Array.forEach (<anonymous>)
    at initFeatures (core.mjs:19348:24)
    at Object.toString (core.mjs:19291:5)
    at noSideEffects (core.mjs:122:5)
    at ɵɵdefineDirective (core.mjs:19289:10)
    at <static_initializer> (primeng-tooltip.mjs:746:33)
    at primeng-tooltip.mjs:135:23

I have this:

Angular CLI: 19.1.8
Node: 22.0.0
Package Manager: npm 10.5.1
OS: win32 x64

Angular: 19.1.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1901.8
@angular-devkit/build-angular   19.1.8
@angular-devkit/core            19.1.5
@angular-devkit/schematics      19.1.5
@angular/cdk                    19.1.5
@angular/cli                    19.1.8
@angular/pwa                    19.1.5
@schematics/angular             19.1.5
rxjs                            7.8.1
typescript                      5.7.3
zone.js                         0.15.0

And also

"primeflex": "3.3.1",
"primeicons": "^7.0.0",
"primeng": "^19.0.6",

I have deleted node_modules, .angular, reverted changes on package.json and package-lock.json and I can't make it work either.

Thanks

**Comment by SolaireFR** [comment]
## Error :
Some primeng import dont work in angular standalone project :
imports: [PopoverModule], 
or
imports: [StyleClassModule],

![Image](https://github.com/user-attachments/assets/59bb6ad8-42a5-4a45-ac41-3cef401a1792)

## Package version :
```json
"dependencies": {
    "@angular/animations": "^19.0.0",
    "@angular/common": "^19.0.0",
    "@angular/compiler": "^19.0.0",
    "@angular/core": "^19.0.0",
    "@angular/forms": "^19.0.0",
    "@angular/platform-browser": "^19.0.0",
    "@angular/platform-browser-dynamic": "^19.0.0",
    "@angular/router": "^19.0.0",
    "@capacitor/android": "7.0.1",
    "@capacitor/app": "7.0.0",
    "@capacitor/barcode-scanner": "^2.0.0",
    "@capacitor/core": "7.0.1",
    "@capacitor/haptics": "7.0.0",
    "@capacitor/keyboard": "7.0.0",
    "@capacitor/status-bar": "7.0.0",
    "@ionic/angular": "^8.0.0",
    "@primeng/themes": "^19.0.5",
    "class-transformer": "^0.5.1",
    "cordova-plugin-inappbrowser": "^6.0.0",
    "ionicons": "^7.0.0",
    "keycloak-angular": "^19.0.2",
    "keycloak-js": "^26.2.0",
    "primeclt": "^0.1.5",
    "primeicons": "^7.0.0",
    "primeng": "^19.0.5",
    "rxjs": "~7.8.0",
    "tailwindcss-primeui": "^0.3.2",
    "tslib": "^2.3.0",
    "zone.js": "~0.15.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^19.0.0",
    "@angular-eslint/builder": "^19.0.0",
    "@angular-eslint/eslint-plugin": "^19.0.0",
    "@angular-eslint/eslint-plugin-template": "^19.0.0",
    "@angular-eslint/schematics": "^19.0.0",
    "@angular-eslint/template-parser": "^19.0.0",
    "@angular/cli": "^19.0.0",
    "@angular/compiler-cli": "^19.0.0",
    "@angular/language-service": "^19.0.0",
    "@capacitor/cli": "7.0.1",
    "@ionic/angular-toolkit": "^12.0.0",
    "@types/jasmine": "~5.1.0",
    "@typescript-eslint/eslint-plugin": "^8.18.0",
    "@typescript-eslint/parser": "^8.18.0",
    "eslint": "^9.16.0",
    "eslint-plugin-import": "^2.29.1",
    "eslint-plugin-jsdoc": "^48.2.1",
    "eslint-plugin-prefer-arrow": "1.2.2",
    "jasmine-core": "~5.1.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "tailwindcss": "^3.4.17",
    "typescript": "~5.6.3"
  }
```

**Comment by bal-dan** [comment]
I found a workaround for this issue by pinning all Angular deps to "19.1.6" and PrimeNG to "19.0.5"

**Comment by mertsincan** [comment]
Please see; https://github.com/primefaces/primeng/issues/17730

**Comment by AdityaPawar2** [comment]
TypeError: fn is not a function
    at node_modules_angular_core_fesm2022_core_mjs-_10e20.js:21013:38
    at Array.forEach (<anonymous>)
    at initFeatures (node_modules_angular_core_fesm2022_core_mjs-_10e20.js:21013:24)
    at Object.toString (node_modules_angular_core_fesm2022_core_mjs-_10e20.js:20801:5)
    at noSideEffects (node_modules_angular_core_fesm2022_core_mjs-_10e20.js:1705:5)
    at Module.ɵɵdefineComponent (node_modules_angular_core_fesm2022_core_mjs-_10e20.js:20766:10)
    at scrolling.mjs:193:96
    at <static_initializer> (scrolling.mjs:1051:712)
    at 79975 (scrolling.mjs:666:40)
    at __webpack_require__ (remoteEntry.js:3416:41) 
Is this same or a different issue ?
