### ISSUE TITLE
Dropdown/Select/MultiSelect: Option overlay doesn't open in the available area 

### ISSUE THREAD

**Issue by cdskill** [primefaces/primeng#16908]
### Describe the bug

When opening a dropdown positioned near the bottom of the page (e.g., a "Rows per page" option in a table), the dropdown content opens below the trigger element, even when there's no space available. This causes the options overlay to be hidden and inaccessible instead of adjusting to display above where there's sufficient room.

### Environment

Angular

### Angular version

18.2.0

### PrimeNG version

18.0.0-rc.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.17.0

### Browser(s)

chrome

### Steps to reproduce the behavior

https://github.com/user-attachments/assets/19a56c9a-8d99-4102-8cef-aa2bf1a2e15c

1. create a dropdown or table positioned in the bottom the page
2. click 

In video u can see struggling with multiselect and dropdown in table but splitbutton is working.

### Expected behavior

should calculated the available place and open accordingly.
It seems to work with the split button.

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primeng/issues/16658

**Comment by OmkarJ13** [comment]
This is happening again in 19.0.10 😕
