### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by Alfonso2k** [primefaces/primeng#16907]
### Autocomplete wont compile.

Hello, I have been trying to implement the autocomplete component with the source code provided but it wont compile because next line :
`  <ng-container *ngIf="!emptyTemplate; else empty">
                                    {{ searchResultMessageText }}
                                </ng-container>
                                <ng-container #empty *ngTemplateOutlet="emptyTemplate"></ng-container>`
 Here, empty is undefined. What I am doing wrong? Thanks.                    

### Environment

Development.

### Angular version

18.2.3

### PrimeNG version

18.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.18.0

**Comment by cetincakiroglu** [comment]
Hi,

Thanks a lot for testing the beta and reporting the issue. Issue is fixed in https://github.com/primefaces/primeng/commit/1cff1d8a7e3a760cc7e8238931dc2d35ebd21d20
