### ISSUE TITLE
[Bug] ngFor and ngIf not working in PrimeNG Table 

### ISSUE THREAD

**Issue by MUHAMMADYASIR92** [primefaces/primeng#16903]
### Describe the bug

Following error starts displaying when I try to add ngIf in the table <td> tag.

list.component.ts:141 ERROR RuntimeError: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: '[object Object]'. Current value: 'undefined'. Expression location: _Table component. Find more at https://angular.dev/errors/NG0100
    at throwErrorIfNoChangesMode (core.mjs:10493:9)
    at bindingUpdated (core.mjs:18604:9)
    at ɵɵproperty (core.mjs:21737:7)
    at Table_ng_template_9_Template (primeng-table.mjs:2363:8)
    at executeTemplate (core.mjs:11791:5)
    at refreshView (core.mjs:13344:7)
    at detectChangesInView (core.mjs:13552:5)
    at detectChangesInViewIfAttached (core.mjs:13514:3)
    at detectChangesInEmbeddedViews (core.mjs:13474:7)
    at refreshView (core.mjs:13371:5)

### Environment

 Following is my environment.
 
 "dependencies": {
    "@angular/animations": "^18.2.0",
    "@angular/common": "^18.2.0",
    "@angular/compiler": "^18.2.0",
    "@angular/core": "^18.2.0",
    "@angular/forms": "^18.2.0",
    "@angular/platform-browser": "^18.2.0",
    "@angular/platform-browser-dynamic": "^18.2.0",
    "@angular/router": "^18.2.0",
    "@primeng/themes": "^18.0.0-rc.1",
    "angular-highcharts": "^17.0.1",
    "file-saver": "^2.0.5",
    "highcharts": "^11.4.8",
    "js-cookie": "^3.0.5",
    "moment": "^2.30.1",
    "primeflex": "^3.3.1",
    "primeicons": "^7.0.0",
    "primeng": "^18.0.0-rc.1",
    "quill": "^2.0.2",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.10"
  },

### Angular version

18.2.0

### PrimeNG version

18.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.1

### Steps to reproduce the behavior

Add a simple table and try to add ngIf directive to the td. It will start giving the error and table won't populate. 

### Expected behavior

It should work according to the given conditions

**Comment by cetincakiroglu** [comment]
Could not replicate with the 18.0.0-rc.2
