### ISSUE TITLE
Component: [Bug] Sorting function working but Icons are not changing their beh

### ISSUE THREAD

**Issue by MUHAMMADYASIR92** [primefaces/primeng#16914]
### Describe the bug

When I sort a table it usually show ascending and descending icons. But currently icon remains the same.

### Environment

 "dependencies": {
    "@angular/animations": "^18.2.0",
    "@angular/common": "^18.2.0",
    "@angular/compiler": "^18.2.0",
    "@angular/core": "^18.2.0",
    "@angular/forms": "^18.2.0",
    "@angular/platform-browser": "^18.2.0",
    "@angular/platform-browser-dynamic": "^18.2.0",
    "@angular/router": "^18.2.0",
    "@primeng/themes": "^18.0.0-rc.2",
    "angular-highcharts": "^17.0.1",
    "file-saver": "^2.0.5",
    "highcharts": "^11.4.8",
    "js-cookie": "^3.0.5",
    "moment": "^2.30.1",
    "primeflex": "^3.3.1",
    "primeicons": "^7.0.0",
    "primeng": "^18.0.0-rc.2",
    "quill": "^2.0.2",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.10"
  }

### Angular version

18.2.0

### PrimeNG version

18.0.0-rc.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.1

### Browser(s)

Chrome 131.0.6778.86 

### Steps to reproduce the behavior

Add a simple table and turn on sorting by putting p-sorticon selector.

### Expected behavior

If we apply a ascending order to a column it should show icon accordingly. Same for descending order.

**Comment by rosenthalj** [comment]
In the v18 PrimeNG Basic Sort Demo the sort icons are not displayed.

The following screenshot is a side-by-side comparison of the v17 and v18 PrimeNG Basic Sort Demo

![Angular_Table_Component_and_Angular_Table_Component_and_pvt_-_Schedules_Compare_and_pvt_-_Home](https://github.com/user-attachments/assets/62ec0829-1e75-403f-aa28-04c068af9049)
