### ISSUE TITLE
Component: [Bug] Row selection not working in PrimeNG Table

### ISSUE THREAD

**Issue by MUHAMMADYASIR92** [primefaces/primeng#16913]
### Describe the bug

PrimeNG table row selection not working

### Environment

 "dependencies": {
    "@angular/animations": "^18.2.0",
    "@angular/common": "^18.2.0",
    "@angular/compiler": "^18.2.0",
    "@angular/core": "^18.2.0",
    "@angular/forms": "^18.2.0",
    "@angular/platform-browser": "^18.2.0",
    "@angular/platform-browser-dynamic": "^18.2.0",
    "@angular/router": "^18.2.0",
    "@primeng/themes": "^18.0.0-rc.2",
    "angular-highcharts": "^17.0.1",
    "file-saver": "^2.0.5",
    "highcharts": "^11.4.8",
    "js-cookie": "^3.0.5",
    "moment": "^2.30.1",
    "primeflex": "^3.3.1",
    "primeicons": "^7.0.0",
    "primeng": "^18.0.0-rc.2",
    "quill": "^2.0.2",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.10"
  }

### Angular version

18.2.0

### PrimeNG version

18.0.0-rc.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.1

### Browser(s)

Chrome 131.0.6778.86 

### Steps to reproduce the behavior

Add a simple table and turn on selection. It won't work,

### Expected behavior

When we select a row it should be selected.

**Comment by rosenthalj** [comment]
The current v18 demo selection demo appear to work?

![Angular_Table_Component](https://github.com/user-attachments/assets/902097e1-1243-43d2-840a-8c082b60c54a)

**Comment by MUHAMMADYASIR92** [comment]
> The current v18 demo selection demo appear to work?
> 
> ![Angular_Table_Component](https://private-user-images.githubusercontent.com/45439491/392104063-902097e1-1243-43d2-840a-8c082b60c54a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMjI3NzYsIm5iZiI6MTczMzMyMjQ3NiwicGF0aCI6Ii80NTQzOTQ5MS8zOTIxMDQwNjMtOTAyMDk3ZTEtMTI0My00M2QyLTg0MGEtOGMwODJiNjBjNTRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDE0Mjc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwY2ZmOGRlNzQxM2RmYjY4MjdmNTUzOWM5MmYxNmZiYjJiYTUwNTNjMTU3ZmI5MjU0MTgwNWQ1MzhhMjk5YmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.r4tEi6A3fA9PP6OAmGg2o0liDA2kOwUrcQkFfxvkcSU)

It's working on the webpage of primeng but won't work when you try to do it by installing 18.0.0-rc.2 in your project.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Comment by MUHAMMADYASIR92** [comment]
Thanks @mertsincan for you response. I have upgraded to v19 its fine now.
