### ISSUE TITLE
DataTable global filtering not working as expected when using columns templates

### ISSUE THREAD

**Issue by gilhanan** [primefaces/primeng#1692]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/DW7Tun?p=preview

**Current behavior**

Global filtering not working as expected when using templates within columns

**Expected behavior**

Filtering same behave when not using templates

* **Angular version:** 2.0.X

* **PrimeNG version:** 1.1.2

**Comment by raviganesh12** [comment]
I have the same issue with sorting. If i use a template & use [sortable]=true sorting fails.

This has to be addressed quickly.

**Comment by raviganesh12** [comment]
The sorting issue when using template was fixed with 1.1.4 release. Thanks a lot. You guys are awesome!!

**Comment by adelprado** [comment]
I also have the same problem and tried installing v1.1.4 but still does not work. Any suggestions?

**Comment by kaushalshah45** [comment]
I have the same problem, global filter not working with template. Any update on this issue?

**Comment by Sumei1009** [comment]
Same problem here

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
