### ISSUE TITLE
Table: DOM element id="undefined" breaks table rendering

### ISSUE THREAD

**Issue by nilzen** [primefaces/primeng#16922]
### Describe the bug

Create a div element with `id="undefined"` then PrimeNG injects css in to the div element and the table breaks completely

### Environment

Using PrimeNG RC 2

### Angular version

18.3

### PrimeNG version

18.rc2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.17

### Expected behavior

The page should render the PrimeNG table but it renders css inside the DOM element with id="undefined"

**Comment by mertsincan** [comment]
I think this issue was already fixed in 18.Final. For now, closed. If the problem persists, please reopen this issue.

**Comment by nilzen** [comment]
Tried with 18.0.0 and it's still an issue, I just added an empty `<div id="undefined"></div>` and the css gets injected there and breaks the table rendering

![image](https://github.com/user-attachments/assets/4bb0e762-8ab3-4453-af4c-b1d29b105ac2)
