### ISSUE TITLE
Component: Table SortIcon V18 RC2

### ISSUE THREAD

**Issue by mastersys-giovanni** [primefaces/primeng#16938]
### Describe the bug

SortIcon error in build

https://stackblitz.com/edit/stackblitz-starters-pzx3kx?file=src%2Fapp%2Fapp.component.html

### Environment

https://stackblitz.com/edit/stackblitz-starters-pzx3kx?file=src%2Fapp%2Fapp.component.html

### Angular version

18

### PrimeNG version

18

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

x

### Browser(s)

chrome

### Steps to reproduce the behavior

https://stackblitz.com/edit/stackblitz-starters-pzx3kx?file=src%2Fapp%2Fapp.component.html

build sample

**Comment by cetincakiroglu** [comment]
Hi,

Thanks a lot for reporting the issue, this issue is fixed in https://github.com/primefaces/primeng/commit/61dca6acdf798637fb325b14f101e1f5b99ef808 and the fix will be available by upcoming release.
