### ISSUE TITLE
18.0.0-rc.2: Stepper content duplicated when stepper is in Dialog

### ISSUE THREAD

**Issue by mplgn** [primefaces/primeng#16936]
### Describe the bug

When a Stepper is inside of a Dialog, the content of each step panel is duplicated.   This does not occur when the Stepper in on a "base" page.     In the screenshot below, there is a Stepper on the base page and a Stepper in a Dialog.  You can see that the Stepper in the Dialog has duplicated content.    The Stepper code I'm using is from the PrimeNG 18 rc.2 demo.

Stackblitz link is provided below to demonstrate and reproduce this.

NOTE: this issue surfaced after upgrading from 18.0.0-beta.3 to 18.0.0-rc.2 (it was working correctly in beta.3).

<img width="850" alt="image" src="https://github.com/user-attachments/assets/e314f8ab-8f42-40d6-a2ef-f2a4da84136d">

### Environment

Angular v18 + PrimeNG 18 rc.2
macOS Sequoia
Webstorm 2024.3

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-soyalt?file=src%2Fapp%2Fapp.component.html

### Angular version

18.2.0

### PrimeNG version

18.0.0-rc.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.17.0

### Steps to reproduce the behavior

1. Go to the Stackblitz demo

2. View the "correct" Stepper when the app loads
<img width="863" alt="image" src="https://github.com/user-attachments/assets/c2620e9c-ea34-4926-9fd8-416394f7dae2">

3. Click the "Open Dialog" button

4. View the broken Stepper when the dialog opens
<img width="738" alt="image" src="https://github.com/user-attachments/assets/8855b9f3-7911-4f7c-8098-bbe3351d6e90">

### Expected behavior

Stepper content should not be duplicated when embedded in a Dialog.

**Comment by cetincakiroglu** [comment]
fixed in https://github.com/primefaces/primeng/commit/7757565de65e3fb1ca8d9565db0ca27b457e3e03
