### ISSUE TITLE
Component: Tree Template Not Working (V18 RC2)

### ISSUE THREAD

**Issue by mastersys-giovanni** [primefaces/primeng#16934]
### Describe the bug

https://v18.primeng.org/tree#template links not working

### Environment

Showcase

### Angular version

Showcase

### PrimeNG version

18 RC2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

Showcase

### Browser(s)

Chrome

**Comment by cetincakiroglu** [comment]
fixed in https://github.com/primefaces/primeng/commit/030695cb5f5be4fab8777650821cb1630484dd7e
