### ISSUE TITLE
[Bug]AutoComplete can't type in japanese on using Chrome?

### ISSUE THREAD

**Issue by saienkin** [primefaces/primeng#1693]
AutoComplete can't type in japanese on using Chrome

[Basic] ・[Advanced] 　→　NG
type Japanese  [ ka（か） ] with japanese ime 
か（IE）　－＞　ｋあ（chrome）

[Multiple] 　→　OK
type Japanese  [ ka（か） ] with japanese ime 
か（IE）　－＞　か（chrome）

test on offical site
http://www.primefaces.org/primeng/#/autocomplete

can you tell me a way out of the problem?

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
