### ISSUE TITLE
p-table/Aura: Dark Mode header for Frozen + Sorted Column is transparent

### ISSUE THREAD

**Issue by allout58** [primefaces/primeng#16940]
### Describe the bug

When using the Aura theme in Dark Mode (not Light Mode), a frozen column, when sorted, has a translucent background for it's header and as such allows the column headers to the right to completely clobber the text of the header.

Bad (some clipping):
![image](https://github.com/user-attachments/assets/80a1b58a-fe1e-4b83-ba61-304bb509838d)
Worst case (completely unreadable):
![image](https://github.com/user-attachments/assets/e7b16d3b-5141-4cfd-ab2a-992f48588727)

### Environment

N/A

### Reproducer

https://stackblitz.com/edit/github-gnsykl (reused from #16939)

### Angular version

18.2.12

### PrimeNG version

18.0.0-rc2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.17.0

### Steps to reproduce the behavior

1) Build out a table with a sortable and frozen column
2) Sort the frozen column
3) Scroll to the right to see the non-frozen column header visible behind the frozen+sorted column header

### Expected behavior

Frozen columns should still be completely usable even when sorted in Dark Mode

**Comment by cetincakiroglu** [comment]
fixed in https://github.com/primefaces/primeng/commit/516e7e9c5e8133cb1bd9dd3e0f76b097999a2a5b
