### ISSUE TITLE
Component: FloatLabel V18 rc2

### ISSUE THREAD

**Issue by mastersys-giovanni** [primefaces/primeng#16948]
### Describe the bug

1 - Incorrect input width (does not occupy the space)
2 - Not working with pre value

### Environment

https://stackblitz.com/edit/stackblitz-starters-7fccjf?file=src%2Fapp%2Fapp.component.html

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-7fccjf?file=src%2Fapp%2Fapp.component.html

### Angular version

18

### PrimeNG version

18 rc2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

stackblitz

### Browser(s)

Chrome

### Steps to reproduce the behavior

Run
https://stackblitz.com/edit/stackblitz-starters-7fccjf?file=src%2Fapp%2Fapp.component.html

**Comment by mplgn** [comment]
@mastersys-giovanni - for the width, you need to style the input so it occupies 100% of it's parent container

`<input id="username" pInputText text="Value" style="width: 100%" />`

<img width="1108" alt="image" src="https://github.com/user-attachments/assets/ce9f6e45-a475-428a-91ef-a6354af30439">

**Comment by mastersys-giovanni** [comment]
1 Its ok.
So only 2 is a mistake.

**Comment by mastersys-giovanni** [comment]
2 - its ok in v18 final
