### ISSUE TITLE
v18.0.0-beta.3: Buttons Press Border

### ISSUE THREAD

**Issue by webtimo-de** [primefaces/primeng#16953]
### Describe the bug

Hello everyone,
I'm currently using PrimeNG v17 and wanted to test PrimeNG v18. I noticed that the buttons in the "Lara" preset are missing a border. This was present in v17 and is also present in v18 in the inputs/text area.

v18 Button:
![grafik](https://github.com/user-attachments/assets/6bcd738d-8cf7-4f10-8458-bcd1422c9d51)

v17 Button:
![grafik](https://github.com/user-attachments/assets/48aae407-c3eb-4b8a-9553-6b8cf47358ce)

v18 Input:
![grafik](https://github.com/user-attachments/assets/f497f099-8d44-4c14-be9a-ef50d1363bcd)

v17 Input:
![grafik](https://github.com/user-attachments/assets/9e1b0efa-c590-4d9f-9059-56645e94d49d)

If this is not a bug, I would personally like to see this brought back because it will clearly show the user/client that they have pressed the button.

### Environment

PrimeNG Doc

### Angular version

18.2.13

### PrimeNG version

18.0.0-beta3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.17.0

### Browser(s)

Firefox, Edge, Chrome, Safari

### Steps to reproduce the behavior

v17: https://primeng.org/button
v18: https://v18.primeng.org/button

### Expected behavior

![grafik](https://github.com/user-attachments/assets/3fc85819-8462-4016-afee-2d25be2192a8)
I want the frame back when the user/client presses the button.

**Comment by mertsincan** [comment]
This is by design. Please try this behaviour with HTML button element;
<!DOCTYPE html>
<html>
<body>

<h1>The button Element</h1>

<button type="button">Click Me!</button>
 
</body>
</html>

**Comment by webtimo-de** [comment]
> This is by design. Please try this behaviour with HTML button element;
> 
> ```
> <!DOCTYPE html>
> <html>
> <body>
> 
> <h1>The button Element</h1>
> 
> <button type="button">Click Me!</button>
>  
> </body>
> </html>
> ```

So do I understand that correctly? That this was taken out on purpose?

Or is there a way to get the border back?

**Comment by webtimo-de** [comment]
@mertsincan
