### ISSUE TITLE
Component: Accordion import documentation out of date

### ISSUE THREAD

**Issue by JamesTheTerry** [primefaces/primeng#16961]
### Describe the bug

The docs need to be updated to have the import specified as

```typescript
import { AccordionModule } from 'primeng/accordion';
```

Instead of:

<img width="816" alt="Screenshot 2024-12-06 at 15 10 29" src="https://github.com/user-attachments/assets/0a479da0-42f8-4810-a6b4-ac0d4123de18">

### Environment

N/A

### Angular version

18

### PrimeNG version

18.0.0-rc2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22.11

**Comment by JamesTheTerry** [comment]
PR opened: https://github.com/primefaces/primeng/pull/16960

**Comment by cetincakiroglu** [comment]
fixed in https://github.com/primefaces/primeng/commit/d2692ce99ca7d170d1e9cf39dc2f04e9de3be1ef
