### ISSUE TITLE
primeng@Latest: Inconsistency in document

### ISSUE THREAD

**Issue by ShahrozS** [primefaces/primeng#16981]
### Describe the bug

According to the official website, after installing the latest version of primeng ``npm install primeng`` do the following for prime ng styles: 
![image](https://github.com/user-attachments/assets/a2a41667-4ad9-4c6c-b4cc-0ca3970d2551)

But the latest primeng version i.e. 18.0.0 does not contain any resource folder. 

### Environment

Win10 64

### Angular version

18.2.0

### PrimeNG version

18.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.15.1

### Browser(s)

Edge

### Steps to reproduce the behavior

1. Install `npm i primeng`
2. paste `@import "primeng/resources/themes/lara-light-blue/theme.css";
@import "primeng/resources/primeng.css";
` in style.scss/css.

### Expected behavior

Resource folder unrecognized by the IDE or the compiler.

**Comment by Mickael-Martinez** [comment]
The theming system has changed in PrimeNG v18.

To configure it, you need to follow the steps described here:

https://v18.primeng.org/configuration

Be careful, the documentation on the website still defaults to the V17.

**Comment by c-o-l-i-n** [comment]
The documentation site has been updated to v18, so this should be resolved now.

https://primeng.org/installation

**Comment by cathy1129** [comment]
v18 page reports 404
![image](https://github.com/user-attachments/assets/26323c8b-a3d6-43be-8bc9-e61ed1728e6d)
![image](https://github.com/user-attachments/assets/4b8b02f8-32ca-4651-b72e-f30958566f75)

**Comment by cathy1129** [comment]
Where is the style file for version v18?
