### ISSUE TITLE
Component: Dropdown -virtualScroll UI issue

### ISSUE THREAD

**Issue by vishalsoni007** [primefaces/primeng#16991]
### Describe the bug

In version17(^17.18.12), Basic dropdown work properly but if add [virtualScroll]="true" [virtualScrollItemSize]="38" then options not showing in expand panel. this issue is on primeNg offical website too.

### Environment

     "@angular/common": "^18.0.0",
    "primeng": "^17.18.12",

### Angular version

18.0.0

### PrimeNG version

17.18.12

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

22

### Browser(s)

Chrome 110

### Steps to reproduce the behavior

1. Add p-dropdown with virtualScroll
2. On click of that expand panel is not visible properly. 

### Expected behavior

After click on dropdown with virtualScroll it should get expand properly for select options

**Comment by meursj** [comment]
The bug was introduced in version 17.18.13, in 17.18.12 it worked ok

See also [https://github.com/primefaces/primeng/issues/17039](https://github.com/primefaces/primeng/issues/17039)

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primeng/issues/17039
