### ISSUE TITLE
v18 Component: Select

### ISSUE THREAD

**Issue by lengauermario** [primefaces/primeng#16998]
### Describe the bug

Template of selectedItem is not working. It should be displaying "This is a customvalue" in the input field.

```
<p-select [options]="types" appendTo="body" [style]="{ width: '100%' }">
  <ng-template pTemplate="selectedItem" let-item>
    This is a customvalue
  </ng-template>
  <ng-template pTemplate="item" let-item> {{ item }} - test </ng-template>
</p-select>
```

![image](https://github.com/user-attachments/assets/8fb65ea6-9634-43a5-a20c-b75fe69dfd8f)

### Environment

upgrading from 18.0.0-rc.1 to 18.0.0

### Reproducer

https://stackblitz.com/edit/github-wcuxbgyk?file=package.json

### Angular version

18.0.1

### PrimeNG version

18.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v22.5.1

### Browser(s)

Chrome v. 131.0.6778.86

### Steps to reproduce the behavior

1. view the select box see that the custom value is not shown.

### Expected behavior

selectedItem should display custom value.

**Comment by mehmetcetin01140** [comment]
Fixed in 8513e956bb7584f74be17e9629aa52d177ec14e5
