### ISSUE TITLE
Component: Dynamic dialog rendering styles instead of title (19.0.0-rc.1)

### ISSUE THREAD

**Issue by gbarrionuevo** [primefaces/primeng#17005]
### Describe the bug

![image](https://github.com/user-attachments/assets/712a9d4d-5c8c-40b4-84a4-27e4a1bd8905)

its rendering this instead of the title

`@layer primeng{.p-image-mask{display:flex;align-items:center;justify-content:center;}.p-image-preview{position:relative;display:inline-flex;line-height:0;}.p-image-preview-mask{position:absolute;inset-inline-start:0;inset-block-start:0;width:100%;height:100%;display:flex;align-items:center;justify-content:center;opacity:0;transition:opacity 0.3s;border:0 none;padding:0;cursor:pointer;background:transparent;color:var(--p-image-preview-mask-color);transition:background var(--p-image-transition-duration);}.p-image-preview:hover &gt; .p-image-preview-mask{opacity:1;cursor:pointer;background:var(--p-image-preview-mask-background);}.p-image-preview-icon{font-size:var(--p-image-preview-icon-size);width:var(--p-image-preview-icon-size);height:var(--p-image-preview-icon-size);}.p-image-toolbar{position:absolute;inset-block-start:var(--p-image-toolbar-position-top);inset-inline-end:var(--p-image-toolbar-position-right);inset-inline-start:var(--p-image-toolbar-position-left);inset-block-end:var(--p-image-toolbar-position-bottom);display:flex;z-index:1;padding:var(--p-image-toolbar-padding);background:var(--p-image-toolbar-background);backdrop-filter:blur(var(--p-image-toolbar-blur));border-color:var(--p-image-toolbar-border-color);border-style:solid;border-width:var(--p-image-toolbar-border-width);border-radius:var(--p-image-toolbar-border-radius);gap:var(--p-image-toolbar-gap);}.p-image-action{display:inline-flex;justify-content:center;align-items:center;color:var(--p-image-action-color);background:transparent;width:var(--p-image-action-size);height:var(--p-image-action-size);margin:0;padding:0;border:0 none;cursor:pointer;user-select:none;border-radius:var(--p-image-action-border-radius);outline-color:transparent;transition:background var(--p-image-transition-duration),color var(--p-image-transition-duration),outline-color var(--p-image-transition-duration),box-shadow var(--p-image-transition-duration);}.p-image-action:hover{color:var(--p-image-action-hover-color);background:var(--p-image-action-hover-background);}.p-image-action:focus-visible{box-shadow:var(--p-toolbar-action-focus-ring-shadow);outline:var(--p-toolbar-action-focus-ring-width) var(--p-toolbar-action-focus-ring-style) var(--p-toolbar-action-focus-ring-color);outline-offset:var(--p-toolbar-action-focus-ring-offset);}.p-image-action .p-icon{font-size:var(--p-image-action-icon-size);width:var(--p-image-action-icon-size);height:var(--p-image-action-icon-size);}.p-image-action.p-disabled{pointer-events:auto;}.p-image-original{transition:transform 0.15s;max-width:100vw;max-height:100vh;}.p-image-original-enter-active{transition:all 150ms cubic-bezier(0,0,0.2,1);}.p-image-original-leave-active{transition:all 150ms cubic-bezier(0.4,0,0.2,1);}.p-image-original-enter-from,.p-image-original-leave-to{opacity:0;transform:scale(0.7);}}`

### Environment

.

### Angular version

19x

### PrimeNG version

19.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22

**Comment by Halynsky** [comment]
Similar issue in the version `18.0.0`
![image](https://github.com/user-attachments/assets/5d760fd0-4e7f-4660-a259-a90fce8fc4a8)

**Comment by luchian94** [comment]
One thing I noticed is that after closing and reopening the dialog styles are correct

**Comment by cetincakiroglu** [comment]
Hi,

Thanks for reporting the issue.

Fixed for 19.0.0.Final. Could you please test the issue again after v19.0.0 is out?

**Comment by gbarrionuevo** [comment]
> Hi,
> 
> Thanks for reporting the issue.
> 
> Fixed for 19.0.0.Final. Could you please test the issue again after v19.0.0 is out?

ty, when is gonna be released ?
