### ISSUE TITLE
Component: Dynamic dialog can't be closed (19.0.0-rc.1)

### ISSUE THREAD

**Issue by gbarrionuevo** [primefaces/primeng#17009]
### Describe the bug

![image](https://github.com/user-attachments/assets/58d3efd9-7b70-4315-9ffa-577fb8b83927)

When trying to close, it errors out as shown in the image

### Environment

/

### Angular version

19.x.x

### PrimeNG version

19.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22x

**Comment by cetincakiroglu** [comment]
Fixed in https://github.com/primefaces/primeng/commit/5bc3a96cf047c8cb60dace22c26e6c5c28d19cc6

**Comment by gbarrionuevo** [comment]
this is still happening in 19.0.0 final, please consider hotfixing it or suggesting a workaround, this has been a thing since primeng 18 @cetincakiroglu
