### ISSUE TITLE
Components: Dropdown, AutoComplete, Listbox -virtualScroll UI issue

### ISSUE THREAD

**Issue by petrov-ana** [primefaces/primeng#17007]
### Describe the bug

In version 17.18.13, Basic dropdown, autocomplete, listbox work properly but if add [virtualScroll]="true" [virtualScrollItemSize]="38" then options not showing in expand panel. This issue is on primeNg offical website too. In version 17.18.12 there is no such problem
![image](https://github.com/user-attachments/assets/73cf1d57-2e40-40e4-b21a-def9275d4d0e)
![image](https://github.com/user-attachments/assets/dbd43bfe-ab9a-49e0-949e-2ae1a1c8a91c)
![image](https://github.com/user-attachments/assets/867fd96c-90fe-489d-ae7e-bbe8332af05a)

### Environment

"@angular/common": "^17.3.0",
"primeng": "^17.18.13",

### Angular version

17.3.7

### PrimeNG version

17.18.13

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.2

### Browser(s)

Chrome 129.0.6668.71, Firefox 133.0.3 

### Steps to reproduce the behavior

1. Add p-dropdown or p-autocomplte or p-listbox with virtualScroll
2. On click of that expand panel is not visible properly.

### Expected behavior

After click on dropdown or p-autocomplte with virtualScroll it should get expand properly for select options

**Comment by LoaderB0T** [comment]
Not sure if really related, but we also have an issue with virtual scrolling in the table control since v 17.18.13.
The "contentEl" in the scroller gets set initially to a `div.p-scroller-content`, which gets removed from the DOM afterwarts...
Results in a calculation of 0 visible items. So it might be related to this bug here.

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primeng/issues/17039
