### ISSUE TITLE
Component: ConfirmDialog p-footer does not replace default buttons (v18.0.0)

### ISSUE THREAD

**Issue by honboubao** [primefaces/primeng#17000]
### Describe the bug

Defining a `<p-footer>` element for the ConfirmDialog places the custom footer next to the default one, instead of replacing it.
Defining a custom footer with `<ng-template #footer>` instead, does replace the default footer as expected.

![grafik](https://github.com/user-attachments/assets/98ce79d7-2f8c-4d93-a6ad-125cd590e91f)

Also referring back to my previously reported issue #16780 and the comment added after it has been closed.

> I don't think commit https://github.com/primefaces/primeng/commit/089a01d96a832a8ad5456402850e0835b0db1936 really addresses the issue. With that change, it will basically always render the default buttons, even if a custom footer is provided, in the latter case it would render both.
>
> I think the issue arises with <ng-template #footer> defining footer as a reference which clashes with @ContentChild(Footer) footer: Nullable<TemplateRef<any>> so I would suggest renaming the variable name of the latter.
>
> The @else if that's been modified in the commit can then be reverted or replaced with a simple @else.

### Environment

Windows 10
Firefox 128.3.1esr

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-jtdunfpw?file=src%2Fapp%2Fapp.component.html

### Angular version

18.2.7

### PrimeNG version

18.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.20.3

**Comment by mehmetcetin01140** [comment]
Fixed in 6d5613b13c64e8d7a190487c536861091e06e249
