### ISSUE TITLE
Datatable Context menu right click array empty

### ISSUE THREAD

**Issue by listeasy** [primefaces/primeng#1700]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Empty Context Menu Array Empty

**Expected behavior**
The context menu should display for the row item in focus on right click even if the checkbox is not clicked. 
If a checkbox / more then one checkbox is checked it will give you the context menu as well.
Technically we should have 2 option, Single Item in focus context menu  or multiple item checkbox bulk context menu options . 2 separate context menu

**Minimal reproduction of the problem with instructions**

Add a grid with Selection varible the ability to have check boxes
Add the grid  Context Menu variable
Right click any row item on grid with no check boxes checked.  The context menu will not display and return an empty array

**What is the motivation / use case for changing the behavior?**
To be used as an action menu or bulk action menu depending on row selected via context menu 

**Please tell us about your environment:**

* **Angular version:** 2.4.1

* **PrimeNG version:** 1.1.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   

Attach files by dragging & dropping,  Choose Files selecting them, or pasting from the clipboard.
 Styling with Markdown is supported
Submit new issue
Contact GitHub API Training Shop Blog About
© 2016 GitHub, Inc. Terms Privacy Security Status Help

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
