### ISSUE TITLE
ThemeProvider loadCommonTheme always injects undefined nonce

### ISSUE THREAD

**Issue by Quimey-CityGIS** [primefaces/primeng#17012]
### Describe the bug

Loading a theme is blocked by CSP headers because the provided nonce value is hardcoded as undefined when the ThemeProvider loads the commonTheme values:

Link to primeng source code:
https://github.com/primefaces/primeng/blob/cb7c271bed2f507e30e89af3d35c8b2836acd6dc/packages/primeng/src/config/themeprovider.ts#L65

### Environment

Angaulr application served with strict CSP headers

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-jwbthjxa?file=src%2Fapp.component.html

### Angular version

18.2.9

### PrimeNG version

18

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.18.0

### Expected behavior

The ThemeProvider should use the actual CSP_NONCE provided by Angular when executing loadCommonTheme.

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primeng/commit/cb8449b236f8065ce84c81c0a5fc80836efe83bb

**Comment by ivan-price-acted** [comment]
@mertsincan  would it be possible to have this commit applied to the 18.x branch / release as well ?
