### ISSUE TITLE
Improve Badge, Chip and Tag structure

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primeng#17011]
Use `host` option.

**Comment by mehmetcetin01140** [comment]
Badge: https://github.com/primefaces/primeng/commit/25dfa030a7c2bb42aab4d6f853afff11a2af00bf
Chip: https://github.com/primefaces/primeng/commit/6cbedf999ca3f5b791fd7024b20ce5f605dd97c4
Tag: https://github.com/primefaces/primeng/commit/dbfbfa9aaf55af72574f88a762bb07a88b34e451
