### ISSUE TITLE
Component: Panel Header Template not working

### ISSUE THREAD

**Issue by mastersys-giovanni** [primefaces/primeng#17020]
### Describe the bug

Header template with ngif not show

See https://stackblitz.com/edit/github-wmmskvr1?file=src%2Fapp%2Fapp.component.html

### Environment

https://stackblitz.com/edit/github-wmmskvr1?file=src%2Fapp%2Fapp.component.html

### Reproducer

https://stackblitz.com/edit/github-wmmskvr1?file=src%2Fapp%2Fapp.component.html

### Angular version

18

### PrimeNG version

18

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

https://stackblitz.com/edit/github-wmmskvr1?file=src%2Fapp%2Fapp.component.html

### Browser(s)

Chrome

### Steps to reproduce the behavior

https://stackblitz.com/edit/github-wmmskvr1?file=src%2Fapp%2Fapp.component.html

On click panel not show header

### Expected behavior

See card

**Comment by cetincakiroglu** [comment]
fixed in v19 https://stackblitz.com/edit/yoaurhyo-lfqfibvu?file=src%2Fapp%2Fpanel-basic-demo.html,src%2Fapp%2Fpanel-basic-demo.ts
