### ISSUE TITLE
Component: ListBox with checkbox = true and showToggleAll = true random behavior

### ISSUE THREAD

**Issue by mtrefzer** [primefaces/primeng#17032]
### Describe the bug

The `ListBox` with `checkbox` set to `true` and `showToggleAll` also set to `true` behaves randomly.

### Environment

Ubuntu 24.04

### Reproducer

https://stackblitz.com/edit/github-mdreytim

### Angular version

18.2.12

### PrimeNG version

18.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22.11.0

### Steps to reproduce the behavior

1. Go to [https://stackblitz.com/edit/github-mdreytim](https://stackblitz.com/edit/github-mdreytim)
2. Click SelectAll
3. Unselect first item (New York)

### Expected behavior

I would expect that "SelectAll" and the item "New York" gets unchecked.

If you click on some other items and select or unselect "All" the behavior seams to be quite random to me.

**Comment by dubey-suraj** [comment]
@mtrefzer  I'm working on this.
