### ISSUE TITLE
Component: Dropdown Virtual Scroll - UI bug error

### ISSUE THREAD

**Issue by ibandim123** [primefaces/primeng#17031]
### Describe the bug

Hi, Everything alright!

I see that Dropdown virtual scroll in PrimeNG v17 is not align with User Interface, the scroll limit height in "17px" in that element child.
![{48ED02E4-2C99-4B11-8636-C9D943376F14}](https://github.com/user-attachments/assets/ce247ac2-90fe-4936-ae78-021c5dc77b9b)

### Environment

PrimeNG v17.18.9

### Angular version

18.2.7

### PrimeNG version

17.18.9

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.9.0

### Expected behavior

Expected:
![{02E0481F-8C6E-403E-BBFE-61AE04FDBBD5}](https://github.com/user-attachments/assets/b4b963f0-a244-4068-b39d-2252a6ae84eb)

**Comment by meursj** [comment]
Maybe update to 17.18.12 but not 17.18.13 since 17.18.13 has a newly introduced bug with virtual scrolling.

See [https://github.com/primefaces/primeng/issues/17039](https://github.com/primefaces/primeng/issues/17039)

**Comment by meursj** [comment]
Probably even better to mark this as duplicate for [https://github.com/primefaces/primeng/issues/16991](https://github.com/primefaces/primeng/issues/16991)

**Comment by ibandim123** [comment]
> Maybe update to 17.18.12 but not 17.18.13 since 17.18.13 has a newly introduced bug with virtual scrolling.
> 
> See #17039

I using CDN version 17.18.0 and still broken.

**Comment by ibandim123** [comment]
@mertsincan Please, Do you can add this fix in CDN library in Lara-Light-Indigo and Lara-Dark-Indigo? Thank you for all.

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primeng/issues/17039
