### ISSUE TITLE
[CSP] providePrimeNG csp nonce does not solve all csp issues when "theme" property is defined

### ISSUE THREAD

**Issue by tom-vism** [primefaces/primeng#17048]
### Describe the bug

Not all CSP issues are fixed when providing the CSP nonce into the PrimeNG config when the "theme" property is an empty object or "preset" is null.
While debugging, the first nonce value is passed undefined.

### Environment

strict csp policy, no unsafe-inline, we are using nonces.

### Reproducer

https://stackblitz.com/edit/azxstcmm?file=src%2Fmain.ts

### Angular version

^18.2.11

### PrimeNG version

^18.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.18.1

### Browser(s)

Chrome 131.0.6778.140

### Steps to reproduce the behavior

![image](https://github.com/user-attachments/assets/71eee800-49c8-491f-be75-185d2823dacb)

![image](https://github.com/user-attachments/assets/e1405e95-cefa-4a52-99af-74d5d2557313)

![image](https://github.com/user-attachments/assets/14935376-39a4-4d5a-af83-ae1d18da4123)|

![image](https://github.com/user-attachments/assets/92c13c13-2c00-4728-9b4b-283ebef24ded)

### Expected behavior

Nonce attribute is set correctly and no csp issues are thrown in the console when "theme" is defined in the primeng config

**Comment by SavGRY** [comment]
Yep, this is also happening to me with the rc `19.0.0-rc.1` with Angular 19.

Although it's not a stable release, it's the same problem.

**Comment by Jonathazn** [comment]
Wondering if I have the same issue, but in my case, the nonces are empty strings like so:
`<style type="text/css" nonce="" data-primeng-style-id="global-style">...</style>`

Nonce gets set in providePrimeNG like this:
`csp: {nonce: 'angularNonce'}`

Nonce is correctly set in the ngcspnonce attribute of app-root (server is nginx), but all other nonce values are empty strings.
Locally the nonces are set to the same default value the ngcspnonce has, but in production they are empty.

Angular version
`19.0.1`

PrimeNG version
`19.0.0-rc.1`

**Comment by tom-vism** [comment]
> Wondering if I have the same issue, but in my case, the nonces are empty strings like so: `<style type="text/css" nonce="" data-primeng-style-id="global-style">...</style>`
> 
> Nonce gets set in providePrimeNG like this: `csp: {nonce: 'angularNonce'}`
> 
> Nonce is correctly set in the ngcspnonce attribute of app-root (server is nginx), but all other nonce values are empty strings. Locally the nonces are set to the same default value the ngcspnonce has, but in production they are empty.
> 
> Angular version `19.0.1`
> 
> PrimeNG version `19.0.0-rc.1`

For security reasons, nonce attribute is hidden. In devtools you can try to access it with `document.querySelector('style[nonce]')?.nonce`.
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/nonce#accessing_nonces_and_nonce_hiding

**Comment by Jonathazn** [comment]
> > Wondering if I have the same issue, but in my case, the nonces are empty strings like so: `<style type="text/css" nonce="" data-primeng-style-id="global-style">...</style>`
> > Nonce gets set in providePrimeNG like this: `csp: {nonce: 'angularNonce'}`
> > Nonce is correctly set in the ngcspnonce attribute of app-root (server is nginx), but all other nonce values are empty strings. Locally the nonces are set to the same default value the ngcspnonce has, but in production they are empty.
> > Angular version `19.0.1`
> > PrimeNG version `19.0.0-rc.1`
> 
> For security reasons, nonce attribute is hidden. In devtools you can try to access it with `document.querySelector('style[nonce]')?.nonce`. https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/nonce#accessing_nonces_and_nonce_hiding

The console is full of errors saying the csp header is violated... unless the issue is that nonce is different on every request, but I don't see why you wouldn't want that...

**Comment by Jonathazn** [comment]
The same happens in 19.0.0, does anything configuration wise need to change? @mertsincan

**Comment by stephanie-dm** [comment]
For me it works with 19.0, but there are some remaining CSP errors, see this issue: https://github.com/primefaces/primeng/issues/17019
