### ISSUE TITLE
Component: p-panel

### ISSUE THREAD

**Issue by khvedela** [primefaces/primeng#17041]
### Describe the bug

when using pTemplate="icons" in ng-template inside p-panel component it does not show it in header.

### Environment

angular 18 with primeng 18.0.0-rc2, same behaviour with primeng 18.0.0.

### Angular version

18.0.0

### PrimeNG version

18.0.0-rc2

### Build / Runtime

Angular CLI App

### Language

ES5

### Node version (for AoT issues node --version)

21.7.3

### Browser(s)

chrome

### Steps to reproduce the behavior

use p-panel component

insert ng-template section inside

```
<ng-template pTemplate="icons">
...
</ng-template>
```

### Expected behavior

it should show small cog icon in header

**Comment by khvedela** [comment]
turnes out you need to use #icon instead of pTemplate="icons", documentation needs to be updated.

**Comment by cetincakiroglu** [comment]
Hi,

This issue has been fixed for the latest versions of (v18 and v19). Here is the working version with v19
