### ISSUE TITLE
p-calendar  time not set programatically

### ISSUE THREAD

**Issue by mitosandov** [primefaces/primeng#1704]
I am submitting a bug

[img]http://i.imgur.com/lZSmgdY.png[/img]

I am having structure like the one on the picture. I want when i select 2 valid times for monday (start- end) to auto fill all the start and end dates of all the other days.
For the purpose i use:
`(onSelect)="firstRowHourSelected($event, i)" (onBlur)="firstRowHourSelected($event, i)"`

and then 

`
               firstRowHourSelected(argument, index) {
                if(!index && this.hoursOfOperation[0].s1 && this.hoursOfOperation[0].e1) {            
               for(let i = 1; i < this.hoursOfOperation.length; i++) {
                   this.hoursOfOperation[i].s1 = undefined;
                    this.hoursOfOperation[i].s1 = this.hoursOfOperation[0].s1;
                    this.hoursOfOperation[i].e1 = undefined;
                    this.hoursOfOperation[i].e1 = this.hoursOfOperation[0].e1;
                  }
                }
                }`

buut this code is only working when i initially set the values from undefined to some hour. When i try to set programmatically  already set values they are not displayed correctly on the screen. 
Despite my `this.hoursOfOperation[5].e1 `is properly set via code to a new one.

Is there some way to achieve this? Some "refresh/update" method?

**Comment by subarroca** [comment]
+1

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
