### ISSUE TITLE
ProvidePrimeng(v19): deprecated APP_INITIALIZER

### ISSUE THREAD

**Issue by luca-peruzzo** [primefaces/primeng#17042]
### Describe the bug

APP_INITIALIZER is deprecated and no longer works

### Environment

angular 19 app

### Angular version

19.0.4

### PrimeNG version

19.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22.11.0

### Browser(s)

all

**Comment by 0x426** [comment]
When using it with Angular SSR, my complete App gets stuck due to `providePrimeNG()` with the use of `APP_INITIALIZER`.
