### ISSUE TITLE
p-password: disabled prop doesn't work with Reactive forms

### ISSUE THREAD

**Issue by imaksp** [primefaces/primeng#17054]
### Describe the bug

p-password's `disabled` prop doesn't work with Reactive form.

### Environment

NA

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-wbls24dq?file=src%2Fapp%2Fapp.component.ts

### Angular version

19.x

### PrimeNG version

19.0.0-rc1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.x

### Steps to reproduce the behavior

check stackblitz, disabled is true but input is not disabled.

### Expected behavior

it should disable the password input.

**Comment by qwadrox** [comment]
@imaksp 

This is not bug @mertsincan 
----
@imaksp In a reactive form, the [disabled] attribute doesn't work the same way because the form control is managed by the FormControl instance. You can disable the control as so: 
```ts
export class AppComponent {
  private formBuilder = inject(NonNullableFormBuilder);
  registerForm = this.formBuilder.group({
    password: ['', [Validators.required, Validators.minLength(8)]],
  });

  constructor() {
    this.registerForm.controls.password.disable();
  }
}
```

Also if you observe the console logs you will see this message from Angular: 
```console
It looks like you're using the disabled attribute with a reactive form directive. If you set disabled to true
when you set up this control in your component class, the disabled attribute will actually be set in the DOM for
you. We recommend using this approach to avoid 'changed after checked' errors.

Example:
// Specify the `disabled` property at control creation time:
form = new FormGroup({
  first: new FormControl({value: 'Nancy', disabled: true}, Validators.required),
  last: new FormControl('Drew', Validators.required)
});

// Controls can also be enabled/disabled after creation:
form.get('first')?.enable();
form.get('last')?.disable();
```
An article might be useful: 
https://medium.com/netanelbasal/disabling-form-controls-when-working-with-reactive-forms-in-angular-549dd7b42110

**Comment by imaksp** [comment]
Hi @qwadrox thanks for the info, it works if I use `{value: '', disabled: true}`.  it is still missing readonly prop support, but new issue can be created for it, so closing.
