### ISSUE TITLE
Error on unit test angular 19

### ISSUE THREAD

**Issue by apis3445** [primefaces/primeng#17057]
### Describe the bug

Hi! When I set up the unit test I got a lot of errors similar to this: 

/node_modules/primeng/fesm2022/primeng-toolbar.mjs:210:85-107 - Error: export 'ɵɵStandaloneFeature' (imported as 'i0') was not found in '@angular/core' (possible exports: ANIMATION_MODULE_TYPE, APP_BOOTSTRAP_LISTENER, APP_ID, APP_INITIALIZER, AfterRenderPhase, ApplicationInitStatus, ApplicationModule, ApplicationRef, Attribute, COMPIL

How I can get unit test working correctly? 

### Environment

Mac OS m1

### Angular version

19.0.5

### PrimeNG version

18.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

23.1.0

### Expected behavior

can execute unit test

**Comment by KeithGillette** [comment]
Per #16827, Angular 19 is supported starting with PrimeNG 19.0.0-rc.1, though that closed issue contains a work-around that may allow PrimeNG 18.0.0 to be used with Angular 19.

**Comment by mertsincan** [comment]
Details; https://github.com/primefaces/primeng/issues/16827#issuecomment-2511150789
