### ISSUE TITLE
Calendar enter key should select time on timeonly

### ISSUE THREAD

**Issue by mitosandov** [primefaces/primeng#1705]
Please add the possibility when the type of a calendar is set to be only time  on Enter key to auto select the time. At the moment when user opens a time he needs to click on arrows and select other time in order to start populating. I tried handling (keyup)="onKeyTime($event, i)"  buuut fortunately it does not handle enter key when the focus is on the dropped content and inside it has only "timestamp" which is the offset since the dropdown was opened. At the moment (at least i could not find way) we cant select time on key press like enter or tab.

**Comment by yigitfindikli** [comment]
We'll reconsider if there is more community feedback on this. Thank you for your report.
