### ISSUE TITLE
p-password: @for doesn't work in footer template

### ISSUE THREAD

**Issue by imaksp** [primefaces/primeng#17055]
### Describe the bug

Angular's `@for` loop doesn't work in footerTemplate. (but it works in headerTemplate).

### Environment

NA

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-scfase3f?file=src%2Fapp%2Fapp.component.html

### Angular version

19.x

### PrimeNG version

19.0.0-rc1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.x

### Steps to reproduce the behavior

Check stackblitz for current behaviour.

### Expected behavior

it should render footerTemplate even if it has `@for` inside, just like headerTemplate.

**Comment by qwadrox** [comment]
I tried your example. [in 19.0.0-rc1 there was a typo](https://github.com/qwadrox/primeng/blob/d4ef3dc6b4f4ac26c120263edab918c567e2e1e3/packages/primeng/src/password/password.ts#L646)

<img width="1476" alt="image" src="https://github.com/user-attachments/assets/056da8ac-fcaa-46b4-bfd7-a0818445af83" />

You have to write like #footerT the name and it will work. On the master branch this error wouldn't occur.

**Comment by imaksp** [comment]
Hi, this is fixed in v19 final release due to merge of code from master. Thanks.
