### ISSUE TITLE
p-InputNumber: scientific annotation (large numbers) bug

### ISSUE THREAD

**Issue by jserra91** [primefaces/primeng#17066]
### Describe the bug

When you type a lot of numbers in the p-inputnumber, there is a moment when it converts to exponential. All numbers after that number are replaced by 0.

This happens at the component level because of the conversion.

https://primeng.org/inputnumber#numeral

If you type in the field Integer Only the number 6566546546546216846351346513246641 (random numbers) you will see that there is a moment when the numbers are replaced by 0.

Is the same issue reported in 20 Jul of 2023 that @mehmetcetin01140 closed the ticket but is not solved (and not tested).
https://github.com/primefaces/primeng/issues/13353

### Environment

In all environments (and all versions)

### Reproducer

https://primeng.org/inputnumber#numeral

### Angular version

latest

### PrimeNG version

latest

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.14.2

### Browser(s)

Chrome last version

### Steps to reproduce the behavior

1. Go to https://primeng.org/inputnumber#numeral
2. Write a large number in the Integer Only
3. Check the number

### Expected behavior

Correct display of the number

**Comment by mertsincan** [comment]
Thanks a lot for your update!

**Comment by cetincakiroglu** [comment]
Hi,

JavaScript number input doesn't support large numbers. Please see: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

At this point we cannot handle the native dynamics, there are libraries out there take the input as string and display the large numbers. But it's unfortunately not possible do the same with number input.
