### ISSUE TITLE
p-confirmDialog: style & styleClass are not being passed to confirm dialog [v19-rc1]

### ISSUE THREAD

**Issue by imaksp** [primefaces/primeng#17072]
### Describe the bug

confirm dialog is not passing `style` or custom class from `styleClass` (like max-w-xl) as shown in stackblitz.
see below image for example:

<img width="843" alt="p-confirm-issue" src="https://github.com/user-attachments/assets/187730a2-5527-4684-8307-4996ba953919" />

### Environment

NA

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-qstm28mv?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

### Angular version

19.x

### PrimeNG version

19.0.0-rc1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.x

### Browser(s)

ALL

### Steps to reproduce the behavior

Check reproduction link , dialog uses full screen width if message has more characters.

### Expected behavior

it should pass given `style` & `styleClass` to p-dialog.

**Comment by imaksp** [comment]
Hi, I have checked code for this, it seems passed styleClass value is not being used in component, instead it uses  `cx('root')`:
https://github.com/primefaces/primeng/blob/cb8449b236f8065ce84c81c0a5fc80836efe83bb/packages/primeng/src/confirmdialog/confirmdialog.ts#L30

& it seems style prop is not even present on p-dialog used inside `p-confirmDialog`:

https://github.com/primefaces/primeng/blob/cb8449b236f8065ce84c81c0a5fc80836efe83bb/packages/primeng/src/confirmdialog/confirmdialog.ts#L25-L38

**Comment by cetincakiroglu** [comment]
fixed in https://github.com/primefaces/primeng/commit/5a4219a06327a3b8c26f43914c1034db6020e95b
