### ISSUE TITLE
AutoComplete documentation example uses wrong type

### ISSUE THREAD

**Issue by Wendelstein7** [primefaces/primeng#17096]
### Describe the bug

The documentation of [AutoComplete](https://primeng.org/autocomplete) contains this code in the example:
```ts
items: any[] | undefined;
```

However the [signature](https://primeng.org/autocomplete#api.autocomplete.props.suggestions) of the `suggestions`-property is `any[]`. This causes the following error in a TypeScript IDE:

```
Type 'any[] | undefined' is not assignable to type 'any[]'.
  Type 'undefined' is not assignable to type 'any[]'.ngtsc(2322)
```

Therefore, the example code should be corrected to:
```ts
items: any[] = [];
```

I have a PR fixing this issue: #17097 

### Environment

Angular 19 with PrimeNG 19

### Angular version

19.0.0

### PrimeNG version

19.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22.6.0

**Comment by mertsincan** [comment]
Sorry for the confusion. Can you resend the PR of the Master branch? Thank you!

**Comment by Wendelstein7** [comment]
Will do, thanks!
