### ISSUE TITLE
Unnecessary binding

### ISSUE THREAD

**Issue by baloodevil** [primefaces/primeng#171]
Some examples in primeng have unnecessary binding.  For example, in the accordion example, showing how to set the multiple property flag...
```
<p-accordion [multiple]="true">
    <p-accordionTab header="Header 1">
        Content 1
    </p-accordionTab>
</p-accordion>

```

The square brackets are only needed if the 'multiple' property is going to be bound to a property in the model.  In the example, it is just set to 'true', rather than bound to something like 'myMultipleSetting'.  So because it is set to a static primitive, square brackets and binding are not needed, and only add binding code to the executed source.

This is sufficient...
```
<p-accordion multiple="true">
    <p-accordionTab header="Header 1">
        Content 1
    </p-accordionTab>
</p-accordion>

```

**Comment by cagataycivici** [comment]
I know but I see this as a matter of preference, multiple="false" also enables multiple mode which might be confusing to users we decided on [multiple]="true".
