### ISSUE TITLE
Replace Header and Footer with p-header and p-footer

### ISSUE THREAD

**Issue by EddyP23** [primefaces/primeng#1710]
# Problem
In `components/common/shared.ts` selectors of Header and Footer components don't have prefix `p-` and even worse shadow real HTML elements `<header>` and `<footer>`. It makes detecting import problems miserable, as there is no error, if it can't recognise `Header` or `Footer` components.

# Proposed Solution
Change selectors to `p-header` and `p-footer` to make it consistent to the whole prime-ng package.

**Comment by Darktaelb** [comment]
Help me. Trying to add p-footer with calendar for saving changes and have this error:
"p-footer is not a known element", i can't find a solution for this, "SharedModule" included in NgModule doesn't help

Text of module:
"@NgModule({
    imports:[
        ScheduleModule,
        DialogModule,
        InputMaskModule,
        CheckboxModule,
        BrowserModule,
        FormsModule,
        SharedModule

    ],
    declarations:[
        EventCalendarComponent, JqueryForEventCalendarComponent
    ],
    exports:[
        EventCalendarComponent
    ],
    providers:[
        ConfirmationService

    ],
    bootstrap:[]
})"

**Comment by nicovanbelle** [comment]
I have the same issue.. The docs stating **"Note that Header and Footer components should be imported and defined at directives section of your component for this to work."** was not much of a help.

**Comment by Darktaelb** [comment]
I solved this problem, my colleagues being loaded old lib (1.*.*) which
doesn't support p-footer
And until I removed in package.json this lib, old lib moved on
If it doesn't help you, try to add SharedModule from primeng/primeng to
NgModule in "Imports"
чт, 2 февр. 2017 г. в 12:32, Nico Van Belle <notifications@github.com>:
