### ISSUE TITLE
[v19]: TreeSelect missing Styles for IconField and InputIcon

### ISSUE THREAD

**Issue by 0x426** [primefaces/primeng#17105]
### Describe the bug

Styles are missing for the TreeSelect component if applied with the filtering option.

For whatever reason, the inner components of the TreeSelect (InputText and SearchIcon) seem to have been removed if I compare the v18.0.0 and v19.0.0-rc.1 (search in the changed files for "treeselect"):
* https://github.com/primefaces/primeng/compare/18.0.0...19.0.0-rc.1

<img width="1169" alt="TreeSelectBug" src="https://github.com/user-attachments/assets/5b08ae6e-51e7-4c5b-8994-a2e50340d789" />

<img width="408" alt="TreeSelectBug02" src="https://github.com/user-attachments/assets/85ac7560-14e0-46d1-adbf-347e27551e16" />

### Environment

Stackblitz

### Reproducer

https://stackblitz.com/edit/github-sa75g5ld?file=src%2Fapp%2Fapp.component.html

### Angular version

19.0.4

### PrimeNG version

19.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v22.9.0

### Steps to reproduce the behavior

1. Open the TreeSelect
2. Styles are broken (Icon not in input, etc.)

### Expected behavior

Elements are properly styled.

**Comment by rd-david-steglich** [comment]
The bug is also in the final release v19 and on the demo page.

**Comment by mertsincan** [comment]
Fixed for 18.0.2 and 19.0.1
