### ISSUE TITLE
Component: TieredMenu - CSS problem

### ISSUE THREAD

**Issue by SLI-DR** [primefaces/primeng#17104]
### Describe the bug

When the horizontal screen size is less than 960px, the tiered menu with popup has issues. The button is repositioned, and the popup opens in an incorrect position.

The bug is currently present and reproducible on the PrimeNG website in the TieredMenu section under Popup: [link here](https://primeng.org/tieredmenu#popup).

To reproduce the issue, resize the window below 960px and click the button.

### Environment

Windows, Visual Studio Code.

### Angular version

18.2.0

### PrimeNG version

18.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22.12.0

### Browser(s)

Firefox, Chrome

### Steps to reproduce the behavior

1.Go to PrimeNG website in the TieredMenu section under Popup: [link here](https://primeng.org/tieredmenu#popup).

2. Resize the window below 960px.

3. Click Toggle button in the Popup section.

### Expected behavior

Same behavior as if window is above 960px.

**Comment by cetincakiroglu** [comment]
Hi,

This issue has been fixed with the latest release. https://primeng.org/tieredmenu#popup
