### ISSUE TITLE
Component: Dropdown

### ISSUE THREAD

**Issue by keajod01** [primefaces/primeng#17112]
### Describe the bug

When tabbing to a dropdown that has enough records for the dropdown to have a scroll bar and then pressing a letter on the keyboard of an item lower on the list in the dropdown, it opens the dropdown however it does not auto scroll to where the record is in the dropdown.

Below is a gif of the bug:

![PrimeNGDropdown](https://github.com/user-attachments/assets/05239e5d-d16f-40b1-add4-5d9ebdbb331d)

### Environment

I have tried it on the PrimeNG website and the bug exists there too.

### Angular version

18.2.13

### PrimeNG version

17.18.12

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.17.8

### Browser(s)

Chrome, FireFox

### Steps to reproduce the behavior

1. Tab to a dropdown that has enough records so that it has a scroll bar.
2. Press the letter on the keyboard for a record that is lower on the list of items in the dropdown.
3. It will open the dropdown however, visually it will not scroll to the record.
4. Visually it will remain on the top of the dropdown.

### Expected behavior

When you tab to a dropdown and press a letter of a record in the dropdown, it should both visually scroll to the dropdown and highlight the record.

**Comment by EtienneBoshoff** [comment]
Found the same problem was about to open a bug

**Comment by keajod01** [comment]
Hi, could we perhaps have the fix applied to version 17? As 17 is the version that we are making use of.

PrimeNG version: 17.18.12
