### ISSUE TITLE
primeng 17.18.14 dependency for tslib moved from dependency to devDependency

### ISSUE THREAD

**Issue by Tasteful** [primefaces/primeng#17117]
### Describe the bug

Today just after the release of 17.18.14 my build was stop working. After investigation I can see that the 17.18.13 have the tslib as dependency but the new 17.18.14 have it as devDependency. Is this by purpose?

### Environment

Local dev environment Windows 11

### Angular version

-

### PrimeNG version

17.18.14

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

-

**Comment by mertsincan** [comment]
Thanks a lot! Please try https://www.npmjs.com/package/primeng/v/17.18.15

**Comment by Tasteful** [comment]
Thanks, now our builds are working as before again without any change in our code.
