### ISSUE TITLE
Table: size not working

### ISSUE THREAD

**Issue by Timmeeeey** [primefaces/primeng#17113]
### Describe the bug

I can't get the table size to work.
In the doc it works (https://primeng.org/table#size) but when i try to use it it doesn't work (see reproducer)

### Environment

NA

### Reproducer

https://stackblitz.com/edit/github-mmqvn7jg

### Angular version

18.2.x

### PrimeNG version

18.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.14.0

**Comment by mark7p** [comment]
hi @Timmeeeey , there's new API for V18. I will create a PR to update the docs. Please use the` size` property as seen below.

**TS:**
```
sizes = [
    { name: 'Small', value: 'small' },
    { name: 'Normal', value: undefined },
    { name: 'Large', value: 'large' }
];
```

**HTML:**
```
<p-selectbutton
  [options]="sizes"
  [(ngModel)]="selectedSize"
  [multiple]="false"
  optionLabel="name"
  optionValue="value"
  
/>

<p-table [value]="products" [size]="selectedSize">
  <ng-template #header>
    <tr>
      <th>Name</th>
    </tr>
  </ng-template>
  <ng-template #body let-product>
    <tr>
      <td>{{ product.name }}</td>
    </tr> 
  </ng-template>
</p-table>
```

**Comment by JoanaJaneFdez** [comment]
Hello! just wanted to let you know that in your documentation on v18 https://v18.primeng.org/table#size its not corrected, also in the demo on blitz its not working. it still says [styleClass]="selectedSize.class"
