### ISSUE TITLE
Component: DatePicker is not working

### ISSUE THREAD

**Issue by egorbwork** [primefaces/primeng#17124]
### Describe the bug

On click following error appears in console and popover is not opened.
![Screenshot-3](https://github.com/user-attachments/assets/a2a45d26-6fbb-45dd-9094-ab630ad66577)

### Environment

ubuntu 22.

### Reproducer

https://primeng.org/datepicker

### Angular version

18

### PrimeNG version

18.0.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Browser(s)

Firefox

### Steps to reproduce the behavior

1.  Add component to the page
2.  Click on it

### Expected behavior

An overlay to set date will appear.

**Comment by Delagen** [comment]
The same  #17125

**Comment by mertsincan** [comment]
Fixed for next version.
