### ISSUE TITLE
Error when [showButtonBar]="true" is applied to the datepicker component

### ISSUE THREAD

**Issue by lucas-mota-gomes** [primefaces/primeng#17125]
### Describe the bug

When enabling the [showButtonBar]="true" property on the datepicker component, the following error occurs:

`ERROR Error: NgClass can only toggle CSS classes expressed as strings, got undefined
    at _NgClass._toggleClass (common.mjs:3012:15)
    at _NgClass._applyStateDiff (common.mjs:2996:14)
    at _NgClass.ngDoCheck (common.mjs:2973:10)
    at callHookInternal (core.mjs:4166:10)
    at callHook (core.mjs:4193:5)
    at callHooks (core.mjs:4150:9)
    at executeInitAndCheckHooks (core.mjs:4105:5)
    at selectIndexInternal (core.mjs:12624:9)
    at ɵɵadvance (core.mjs:12608:3)
    at DatePicker_div_3_div_6_Template (primeng-datepicker.mjs:1985:8)
`

### Environment

Library Version: [v19.0.0]
Angular Version: [v19.0.3]

Additional Context:
If the [showButtonBar] property is set to false, the error does not occur.

### Angular version

19.0.3

### PrimeNG version

19.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.0

### Browser(s)

Edge

### Steps to reproduce the behavior

1. Use the datepicker component with [showButtonBar]="true".
2. Open the datepicke

### Expected behavior

The datepicker should display the button bar without error

**Actual Behavior:**
An error is thrown in the console and the button bar does not render properly.

**Comment by Delagen** [comment]
Seems this is issue: https://github.com/primefaces/primeng/commit/61a7891db8fced1899c662a8666d97e81163cbcf#diff-40c9e8900181657297f7c0b31d5fee5a96cd1c1704f1d9f406b3bfcd8b1022a9R493

ngClass values wraper in square brackets, that by default result in `[undefined]` and `undefined` is invalid value for class

**Comment by Delagen** [comment]
Workaround, set any classes for this buttons
```
    [todayButtonStyleClass]="'btn-bar-today'"
    [clearButtonStyleClass]="'btn-bar-clear'"
```
