### ISSUE TITLE
DatePicker: Styles not working

### ISSUE THREAD

**Issue by aaron-za-dev** [primefaces/primeng#17129]
Component is displayed incorrectly after upgrading to version 19

Primeng v19

![image](https://github.com/user-attachments/assets/b4a1ad12-8be4-4243-8fea-b5d51c6ce759)

After update to Primeng v18.0.1

![image](https://github.com/user-attachments/assets/cb7259f7-e800-448a-9ab2-c040d4ffae56)

Primeng v18.0.0

![image](https://github.com/user-attachments/assets/d945bffc-f6bf-4a1f-900f-b4e0ba8c7314)

### Environment

Using:

 - @primeng/themes: 19.0.0 - 18.0.1
 - primeng: 19.0.0 - 18.0.1
 - tailwindcss": "^3.4.17

### Reproducer

https://primeng.org/datepicker

### Angular version

19.0.5, 18.0.1

### PrimeNG version

19.0.0, 18.2.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22.11.0

### Browser(s)

Any

### Steps to reproduce the behavior

1. Go to https://primeng.org/datepicker
2. Click on any datepicker

### Expected behavior

The component should be displayed correctly

**Comment by imaksp** [comment]
This is looking bad, did you find any workaround for this?

**Comment by mligtenberg** [comment]
Adding the following CSS to your main styles.css (or scss, or sass) seems to fix it for me:
```css
.p-datepicker .p-datepicker-panel:not(.p-datepicker-panel-inline) {
    position: absolute;
}
```
