### ISSUE TITLE
Component: DatePicker

### ISSUE THREAD

**Issue by ja74687** [primefaces/primeng#17136]
### Describe the bug

Hello

I have question I use new prime 19 and this is new theme or bug ? 
![image](https://github.com/user-attachments/assets/5b4d3da9-c468-4d51-9564-b782b2ecddb7)

How i Can fix it ? :) 

### Environment

Angular 19
PrimeNg19

### Angular version

19

### PrimeNG version

19

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

latest

**Comment by imaksp** [comment]
duplicate of #17129, check comments for temp. workaround.
