### ISSUE TITLE
Component: P-dropdown has issue while removing items.Scroll is not happening Properly

### ISSUE THREAD

**Issue by acharugulla** [primefaces/primeng#17130]
### Describe the bug

Primeng dropdown scroll is buggy, when user removes value in editable dropdown. It doesn't scroll to correct value

### Environment

Angular 

### Angular version

17

### PrimeNG version

17

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20

### Browser(s)

Chrome,Safari , Edge

### Steps to reproduce the behavior

Assume you have editable prime ng drop down which has values from 1 to 500. User enters a value in editable dropdown as 300. The dropdown opens and scrolls to 300. But when user erases value (assume 0), then value will be 30, dropdown should scroll to 30 
and its not happening

I tried implementing logic like this  which is working
https://stackblitz.com/edit/ejxbx3fy?file=src%2Fapp%2Fdropdown-editable-demo.ts,src%2Fapp%2Fdropdown-editable-demo.html
but when i have appendTo Body. it doesn't work

This needs to be fixed

### Expected behavior

It should scroll to 30 when user removes 0 in that

**Comment by acharugulla** [comment]
I tried implementing logic like this  which is working
https://stackblitz.com/edit/ejxbx3fy?file=src%2Fapp%2Fdropdown-editable-demo.ts,src%2Fapp%2Fdropdown-editable-demo.html


but when i have appendTo Body. it doesn't work 

This needs to be fixed

**Comment by qwadrox** [comment]
@acharugulla 
Hi. I tried your example. I type 40000 and then delete a 0 so it becomes 4000 it scrolls there then I remove another 0, and it goes to 400. 

https://github.com/user-attachments/assets/2315548e-20a3-48d8-beb9-67b0b3a45c6c

**Comment by acharugulla** [comment]
Hi @qwadrox 
It is working because i have written the code for scroll

I am calling scroll function each time , based on some conditions. It should work automatically. My org uses 1000 of p-dropdown
I cant call scroll methods in each p dropdown 

You this issue needs to be fixed

**Comment by acharugulla** [comment]
I have provided you a solution 
You can try with basic example without my code

**Comment by acharugulla** [comment]
@qwadrox can you please make this feature available in primeng 17 version
^17.18.8 or below 

So, that this feature gets added to our code  without bumping any versions of primeng

**Comment by qwadrox** [comment]
> So, that this feature gets added to our code without bumping any versions of primeng 

I don't know if they're allowing PRs for older Primeng versions, and I'm not sure they will also allow this one and when. If you need this fix a lot you might be better creating your own build for whatever version you support and publish it to GitHub for example: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry

**Comment by mertsincan** [comment]
Thanks @qwadrox! Fixed in 19.0.2.
