### ISSUE TITLE
Component: Menu. Popup menu containing items and items with children does not work.

### ISSUE THREAD

**Issue by ctrl-brk** [primefaces/primeng#17131]
### Describe the bug

This works:
```
this.items = [
  {
    label: 'Item 1'
  },
  {
    label: 'Item 2'
  },
];
```
![image](https://github.com/user-attachments/assets/558d667d-79e2-4881-bfd2-9933077dc47f)

But as soon as I add another item with subitems ("Item 3"), the items "Item 1" and "Item 2" stop working. They will be treated like they have child items even if they don't. Displayed in bold and not allowing clicks.
```
this.items = [
  {
    label: 'Item 1'
  },
  {
    label: 'Item 2'
  },
  {
    label: 'Item 3',
    items: [
        {
            label: 'Item 4',
        }
    ]
  }
];
```
![image](https://github.com/user-attachments/assets/3947e6d7-a2af-4a0f-9da2-53026c7032ee)

### Environment

PrimeNg versions 17 - 19

### Angular version

18.2.12

### PrimeNG version

18

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22.9.0

### Browser(s)

any

### Expected behavior

Menubar works with mixed child/no child configuration. Popup should too.

**Comment by ctrl-brk** [comment]
> hi @ctrl-brk , according to the docs, **Menu** supports only one level.
> 
> > Menu supports **one level** of nesting by defining children with items property
> 
> You should consider using [**TieredMenu**](https://primeng.org/tieredmenu#popup), it also supports `popup`.

But all your demos have at least one children for each root level item.
What I'm saying is that it doesn't work when you have items with children and without. If you only have items with children or only root items, then it works.

But this is only in popup mode. If you use the same menuitems array but the menu is in "bar" mode - everything works fine.

Does it make sense? Just try the menuitems I posted in the issue.

**Comment by aberonni** [comment]
@mertsincan this is still an issue - I am encountering the same. "Menu" nesting only works if all items are nested.
