### ISSUE TITLE
RadioButton: No difference between radio filled and outlined

### ISSUE THREAD

**Issue by GreyM22** [primefaces/primeng#17135]
### Describe the bug

There is no visual difference between the radio with variant outlined and the radio with variant filled.

Bellow is the radio with variant filled that looks the same as the radio with variant outlined. 
![image](https://github.com/user-attachments/assets/24f5fd1b-2319-4312-a74b-da58a3f10d40)

### Environment

PrimeNG version19, website version https://primeng.org/

### Angular version

same as website

### PrimeNG version

v19

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

same as website

### Browser(s)

Chrome

### Steps to reproduce the behavior

Go to website https://primeng.org/

### Expected behavior

To be a visual difference between the variant filled and outlined. 

In the documentation the disabled radio is displayed like below:
![image](https://github.com/user-attachments/assets/88b6d956-450b-489d-aa1e-90efd3b5c739)
Maybe the filled variant is the same but without the color grey ?

**Comment by imaksp** [comment]
Hi, its same for checkbox difference will be visible only when its not checked/selected.

**Comment by mertsincan** [comment]
> Hi, its same for checkbox difference will be visible only when its not checked/selected.

Yes, this is by design.

**Comment by hanockjoseph** [comment]
**Solution for this Problem** ❤️

CSS -

```
:host ::ng-deep .filled-radio.p-radiobutton.p-radiobutton-checked .p-radiobutton-box .p-radiobutton-icon {
    background: var(--p-primary-color);
}

:host ::ng-deep .filled-radio.p-radiobutton:not(.p-disabled):has(.p-radiobutton-input:hover).p-radiobutton-checked 
.p-radiobutton-box .p-radiobutton-icon {
    background: var(--p-primary-color);
}
```


HTML -
`<p-radiobutton class="filled-radio" name="party" value="S" variant="filled"  inputId="Self" />`


this is working. (for those who are trying to make the radiobutton looks filled)
