### ISSUE TITLE
Extra apostrophe in breadcrumb component

### ISSUE THREAD

**Issue by KraftyKaleb** [primefaces/primeng#17148]
### Describe the bug

Extra single quote/apostrophe character in breadcrumb (.p-breadcrumb-item-label) css class string. Viewable on line 104.

https://github.com/primefaces/primeng/blob/acf55315de87803de28e7860b45f0f54607e9ffb/packages/primeng/src/breadcrumb/breadcrumb.ts#L104

### Environment

All environments. The code is viewable in git.

### Angular version

19.0.5

### PrimeNG version

19.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22.8.0

### Steps to reproduce the behavior

View breadcrumb in chrome inspect element

### Expected behavior

Css class to not have a random apostrophe

**Comment by martinkasa** [comment]
Hi @KraftyKaleb, I noticed that the apostrophe is on four places, maybe you can update your PR to fix them all.

**Comment by KraftyKaleb** [comment]
> Hi @KraftyKaleb, I noticed that the apostrophe is on four places, maybe you can update your PR to fix them all. Just search for string p-breadcrumb-item-label' to find them.

Thank you, I have updated the PR accordingly.
