### ISSUE TITLE
Limit the width of multiselect dropdown

### ISSUE THREAD

**Issue by mohan1304** [primefaces/primeng#1714]
Hi,

Want to know if there is a way to control the width of the multiselect dropdown? Currently it is expanding as long as the list of the selected items from the multiselect dropdown. I don't want the dropdown to be expanded when I select the items

**Comment by Mrtcndkn** [comment]
There is nothing special for this but you can give it a fixed with.

**Comment by zealitude** [comment]
@Mrtcndkn hey, it violate user experience. I even hard to find any other multiselect library will allow this happen

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
