### ISSUE TITLE
Component: DatePicker

### ISSUE THREAD

**Issue by PaulBerthelot21** [primefaces/primeng#17144]
### Describe the bug

Hello, I migrate PrimeNG 17 to 18 and i switch calendar to date-picker but the overlay date picker glitch in my screen and when i come to the documentation i see this display when i click on the date-picker : 
![image](https://github.com/user-attachments/assets/384f9e0b-d59a-4fb6-99ac-360ac8ada7d4)

### Environment

[Primeng](https://primeng.org/datepicker)

### Angular version

18

### PrimeNG version

18

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

xxxxx

### Browser(s)

Edge

**Comment by mertsincan** [comment]
Please try the latest version.https://www.npmjs.com/package/primeng?activeTab=versions
