### ISSUE TITLE
DataTable: column resizing with bootstrap not working

### ISSUE THREAD

**Issue by derchirurg** [primefaces/primeng#1715]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/YwrwEh3E1BPPBdbOy350

**Current behavior**

Including bootstrap and primeng has some issues in the DataTable component. The resizing of the columns does not work as expected. In the Plunker sample, the vertical resizer does not show on the correct position. In my app I do also have the issue, that the calc of the columns does not work as expected in Chrome (please see the attached image). In IE and FF it seems to work. I think it has something to do with the col-md-3 class of bootstrap. I removed bootstrap from my app and tried the primeng grid-system: same as with bootstrap as you can see on the images.

First:
![chrome-bug 1](https://cloud.githubusercontent.com/assets/22213966/21586982/2df35a3a-d0d7-11e6-92d9-8522032c588d.PNG)

Second:
![chrome-bug 2](https://cloud.githubusercontent.com/assets/22213966/21586981/2df346d0-d0d7-11e6-9dca-ef9edce59822.PNG)

**Expected behavior**

Resizing should work together with bootstrap.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Operating System: Windows 7
IDE: Visual Studio Code

* **Angular version:** 2.2.3

* **PrimeNG version:** 1.1.2

* **Browser:** [all | Chrome 55.0.2883.87 m| Firefox XX | IE 11 | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [TypeScript 2.0.6]

* **Node (for AoT issues):** `node --version` =   6.7.0

**Comment by Mrtcndkn** [comment]
Hi this issue is about container div's position.When position is relative and there is an datatable inside of that container this happening we are investigating.

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
