### ISSUE TITLE
PrimeNG/Themes is missing variables required for PrimeFlex 

### ISSUE THREAD

**Issue by chris-stillwell** [primefaces/primeng#17163]
### Describe the bug

Multiple variables are missing from PrimeNG that PrimeFlex depends on. These include: 

- `--surface-ground`
- `--surface-section`
- `--surface-card`
- `--surface-overlay`
- `--surface-border`
- `--surface-hover`

### Environment

Not relevant. 

### Reproducer

https://stackblitz.com/edit/github-svrzkh3h?file=src%2Fapp%2Fapp.component.html

### Angular version

18

### PrimeNG version

18

### Steps to reproduce the behavior

Add the following to any PrimeNG project. The `surface-* ` classes are unresolved.

`<div class=border-2 my-2 p-2 shadow-2 surface-border surface-card'>Lorem ipsum....</div>`

![image](https://github.com/user-attachments/assets/5cd6fdad-a587-4fac-8a6c-139d5f956d6a)
![image](https://github.com/user-attachments/assets/b43a3525-b973-4372-8f24-1dd4dae4eec4)

### Expected behavior

In version 17 of PrimeNG
![image](https://github.com/user-attachments/assets/74359a33-004a-4490-805b-9b9782dc8237)
![image](https://github.com/user-attachments/assets/0920e5c9-ee81-4fea-a20d-f9294f320345)

**Comment by cagataycivici** [comment]
PrimeFlex has been deprecated for a long time, please review;

https://primeng.org/guides/primeflex

**Comment by chris-stillwell** [comment]
Thanks for the prompt reply. Is it possible to get a deprecation notice on the PrimeFlex website? And are Blocks deprecated then as well?

**Comment by ddurham2** [comment]
They're still [mentioned in the docs](https://primeng.org/colors).  Very misleading.  Shouldn't they be removed?  Or at least, should the docs mention that they are provided by primeflex?  I couldn't even find them when I was using primeflex before converting to tailwind.
