### ISSUE TITLE
Could not resolve "primeng/resources/primeng.css"

### ISSUE THREAD

**Issue by jbarber2016** [primefaces/primeng#17170]
### Describe the bug

After upgrading to Primeng 19, my styles.scss can no longer resolve the primeng css resources.  When I run npm start on my angular 19.0.6 application it shows an error "Could not resolve "primeng/resources/primeng.css""

`@import "primeng/resources/themes/lara-light-blue/theme.css";
@import "primeng/resources/primeng.css";
@import "primeicons/primeicons.css";
@import 'primeflex/primeflex.scss';`

### Reason for not contributing a PR

- [ ] Lack of time
- [x] Unsure how to implement the fix/feature
- [ ] Difficulty understanding the codebase
- [ ] Other

### Reproducer

https://stackblitz.com/edit/github-jrrmkeze

### Environment

I am running this from visual studio code.

### Angular version

19.0.5

### PrimeNG version

v19

### Node version

20.12.2

### Steps to reproduce the behavior

1. create a new angular 19.0.6 application using scss
2. add primeng 19
3. add primeng to the styles.scss
4. npm start

### Expected behavior

What is the proper way to resolve the css in styles.scss?

**Comment by MichiBaum** [comment]
Hi @jbarber2016

As of PrimeNG 18 forward, `primeng/resources` and `theme.css` are removed and replaced with a new architecture.
I suggest you looking into [Guides -> Migration to V18 -> SASS Themes](https://primeng.org/guides/migration), [Theming](https://primeng.org/theming) and [Tailwindcss](https://primeng.org/tailwind).
I hope I could help you.

**Comment by jbarber2016** [comment]
@MichiBaum Thank you very much.  That's very helpful.
