### ISSUE TITLE
p-popover: Show close icon

### ISSUE THREAD

**Issue by framework-res** [primefaces/primeng#17176]
### Describe the bug

p-popover #op [showCloseIcon]="true"
showCloseIcon seem isn't working

### Reason for not contributing a PR

- [X] Lack of time
- [ ] Unsure how to implement the fix/feature
- [ ] Difficulty understanding the codebase
- [ ] Other

### Reproducer

https://stackblitz.com/edit/mvjlrclu?file=package.json,src%2Fapp%2Fimports.ts,src%2Fapp%2Fpopover-basic-demo.html

### Environment

----

### Angular version

18.2.12

### PrimeNG version

v18 (LTS Only)

### Steps to reproduce the behavior

Click button toggle

### Expected behavior

Pop over will be open but without old prime ng close icon

**Comment by el7lme** [comment]
I have the same issue in ver 19.0.1

**Comment by cetincakiroglu** [comment]
Hi,

Thanks for reporting the issue, it seems that there is a typo leftover from component rework, `showCloseIcon` is not used anywhere in the component, and the component doesn't have a button with close functionality at all. The proper solution to pass close function by closeCallback context variable with `content` template.

Correct use:

```
<p-popover ....>
    <ng-template #content let-closeCallback="closeCallback">
      <button (click)="closeCallback($event)">Close</button>
    </ng-template>
</p-popover>

```

**Comment by nchaigne** [comment]
> Hi,
> 
> Thanks for reporting the issue, it seems that there is a typo leftover from component rework, `showCloseIcon` is not used anywhere in the component, and the component doesn't have a button with close functionality at all. The proper solution to pass close function by closeCallback context variable with `content` template.
> 
> Correct use:
> 
> ```
> <p-popover ....>
>     <ng-template #content let-closeCallback="closeCallback">
>       <button (click)="closeCallback($event)">Close</button>
>     </ng-template>
> </p-popover>
> ```

I tried your suggestion for adding back a close button, but it does not seem to work.
I get this error:

`NG5: Argument of type 'TemplateRef<any>' is not assignable to parameter of type 'string'.`

**Comment by Shusty-6th** [comment]
Just add x button

<p-popover #po >
  <ng-template pTemplate="content">
    <p-button (onClick)="po.hide()" icon="fa-solid fa-xmark" />
  </ng-template>
</p-popover>

**Comment by nchaigne** [comment]
Actually, it also works with the solution proposed by [cetincakiroglu], with a fix:
`#content` must be replaced by: `pTemplate="content"`

As follows:
```
    <ng-template pTemplate="content" let-closeCallback="closeCallback">
      <button (click)="closeCallback($event)">Close</button>
    </ng-template>
```

I don't know if it is supposed to work with `#content` ?

**Comment by johanneszelger** [comment]
The documentation still shows showCloseIcon, very confusing

https://primeng.org/popover
