### ISSUE TITLE
DataTable: Body-Template let-row="rowData" not working

### ISSUE THREAD

**Issue by derchirurg** [primefaces/primeng#1717]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/LFFEj0eZuUVR70whn7YY

**Current behavior**

I am using a body template in DataTable and iterate throug the rows with `let-row="rowData"`.
This does not work anymore with lazy loading (see the plunk) since version 1.1.2 of primeng.
Workaround: using the rowindex with `let-index="rowIndex"` and access the data of my backing component with `rows[index]`.

**Expected behavior**

Paging should work.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.2.3

* **PrimeNG version:** 1.1.2

* **Browser:** [all]

 
* **Language:** [TypeScript 2.0.10]

* **Node (for AoT issues):** `node --version` =   6.7.0

**Comment by Lynx12** [comment]
This problem is present even with Lazy load disabled. Row selection is working, but it has problems with body template... Pagination should be fixed too...

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
