### ISSUE TITLE
Rating: Missing cancel input in component

### ISSUE THREAD

**Issue by itismohammadreza** [primefaces/primeng#17197]
The Rating component documentation mentions the cancelIcon and onCancel inputs/outputs. However, it seems that the following inputs have been removed:

- cancel
- iconCancelStyle
- iconCancelClass

### Angular version

19

### PrimeNG version

19

**Comment by mertsincan** [comment]
https://github.com/primefaces/primeng/issues/17203#issuecomment-2561287123
