### ISSUE TITLE
Button with Icon: the label is not updated when used with a pipe

### ISSUE THREAD

**Issue by iguissouma** [primefaces/primeng#1719]
When used with a pipe such as translate (ng2-translate) the label is not correctly updated.
First display - OK
![2017-01-03_10h57_00](https://cloud.githubusercontent.com/assets/9085108/21604645/9fa4b160-d1a4-11e6-8dbb-1fb083831770.png)
After language switch - KO
![2017-01-03_11h00_18](https://cloud.githubusercontent.com/assets/9085108/21604657/b4e161c2-d1a4-11e6-8ebc-4c3522c5d982.png)

DOM

![2017-01-03_11h07_14](https://cloud.githubusercontent.com/assets/9085108/21604674/d3021bf6-d1a4-11e6-9276-efeec1dfc625.png)

"primeng": "^1.1.1",
"@angular/core": "2.2.1",
"ng2-translate": "^4.0.0",

I'm using the ultima-ng theme but I don't thik the problem is related to the theme.

**Comment by donriver** [comment]
I have the similar issue, and it seems that it's related to https://github.com/primefaces/primeng/issues/1685
