### ISSUE TITLE
Datepicker: size Input Has No Effect 

### ISSUE THREAD

**Issue by itismohammadreza** [primefaces/primeng#17200]
The Datepicker component includes a size input, which is expected to adjust the size of the component. However, this input appears to have no effect, as all Datepicker instances render with the same size regardless of the value provided.

### Angular version

19

### PrimeNG version

v19

![image](https://github.com/user-attachments/assets/d909633a-8c52-4b3b-91e1-228d19a4e3dc)

**Comment by mertsincan** [comment]
https://github.com/primefaces/primeng/issues/17203#issuecomment-2561287123
