### ISSUE TITLE
Inconsistency in Config Property Support for filterMatchModeOptions and zIndex

### ISSUE THREAD

**Issue by itismohammadreza** [primefaces/primeng#17203]
According to the documentation, all config properties for PrimeNG can be provided either via the providePrimeNG provider or the PrimeNG service. However, filterMatchModeOptions and zIndex can currently only be configured through the PrimeNG service.

This inconsistency limits the flexibility of the providePrimeNG approach for managing global configurations. It would be beneficial to allow filterMatchModeOptions and zIndex to be set through providePrimeNG as well, ensuring uniformity in how config properties are handled.

Could this enhancement be considered for a future release?

### PrimeNG version
19

**Comment by mertsincan** [comment]
This issue does not match the [templating](https://github.com/primefaces/primeng/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml), please open a new issue using "Bug Report"

<img width="1196" alt="Screenshot 2024-12-24 at 16 49 52" src="https://github.com/user-attachments/assets/c2d19632-dedc-4a34-b802-18979adf3267" />
