### ISSUE TITLE
CascadeSelect: Incorrect type for optionGroupChildren in documentation

### ISSUE THREAD

**Issue by itismohammadreza** [primefaces/primeng#17201]
In the documentation of CascadeSelect, the type of the optionGroupChildren input is listed as string. However, the provided examples pass an array to this input, which appears to work without issues.

### Angular version

19

### PrimeNG version

v19

**Comment by mertsincan** [comment]
https://github.com/primefaces/primeng/issues/17203#issuecomment-2561287123
