### ISSUE TITLE
Datatable scroll and sort do not work together

### ISSUE THREAD

**Issue by kcsahoo** [primefaces/primeng#1720]
Scroll and sort work independently.
But if you use both, scroll works but sort functionality breaks .

**Comment by SerkanDayicik** [comment]
sort and custom template dont work to with Scrollable Data Table

**Comment by kcsahoo** [comment]
Do you have any plans to implement this functionality of sort and scroll working together?

**Comment by raviganesh12** [comment]
I am facing same issue.. Sorting breaks with scroll.

**Comment by Mrtcndkn** [comment]
Hi,

1.1.4 released today for scroll and sorting is problem consisting or is it fixed?

**Comment by kcsahoo** [comment]
It works
Many thanks
You guys are doing a great job

**Comment by Mrtcndkn** [comment]
Glad to hear that.

**Comment by abhijithpn** [comment]
What is the fix for this issue ? I am also facing the same issue.
