### ISSUE TITLE
Auto Expand Row Groups - Data Table

### ISSUE THREAD

**Issue by LifeguardConcepts** [primefaces/primeng#1721]
The docs mention that you can auto expand rows using the expandedRowGroups property of the DataTable.  Does this work when using RowGroup and is there an example of what data needs to be added to the property?

**Comment by listerp** [comment]
Did anyone ever respond to you, or did you figure it out?

**Comment by LifeguardConcepts** [comment]
No, I haven't had a response yet on this.  I poked around for a bit but didn't find a solution.  It looks like you can specify it for Expandable Rows, "By default all rows are collapsed and expandadRows property needs to be populated with the row data instances to show particular rows as expanded by default." but I didn't see this property added for row grouping.

**Comment by ajshapiro** [comment]
The property is expandedRowsGroups not expandedRowGroups as stated in the documentation (note the "s" in "Rows"). You can bind this to an array in your component class.

For example:

`<p-datatable ... [expandedRowsGroups]="groupHeaders">`

In component class:
`groupHeaders = ['group1','group2','group3']`;

**Comment by kcsahoo** [comment]
I could not make it work.
I presume the groupHeaders  array holds the field names used for grouping.

**Comment by kcsahoo** [comment]
I made it work.
the groupHeaders array should hold group field values, not names.

**Comment by enshuti** [comment]
@kcsahoo I know this is closed, but can you tell how you made it work - what are the group field values? Can you you perhaps show example?

**Comment by enshuti** [comment]
Never mind. I wanted to expand all row groups by default. I managed to this a property on the datable. For anybody who might be struggling with something similar, here's an example:

**In the template:**
`<p-dataTable #table.... [expandedRows]="table.value"`

**Comment by siddeshcs** [comment]
@enshuti Thanks for that code......by default all row groups are expanding but when u click on collapse icon the row is getting removed ...can u please help me in that....???
Thanks in advance
