### ISSUE TITLE
TreeSelect Bug !!!!

### ISSUE THREAD

**Issue by oxxzz** [primefaces/primeng#17223]
### Describe the bug

![截屏2024-12-26 17 54 04](https://github.com/user-attachments/assets/7f0d79fd-c058-410e-89be-85655743110f)

In my project, I found that TreeSelect cannot be used. When using the official document sample code, the error is as shown in the figure. Also, can't TreeSelect select a certain field value? Currently, when selected, tree nodes are obtained, which is the case in ReactiveForms., In my project, I found that TreeSelect cannot be used. When using the official document sample code, the same error occurs as shown in the figure. Also, can't TreeSelect select a certain field value? Currently, when selected, tree nodes are obtained, which is the case in ReactiveForms.

### Reason for not contributing a PR

- [ ] Lack of time
- [ ] Unsure how to implement the fix/feature
- [ ] Difficulty understanding the codebase
- [ ] Other

### Reproducer

-

### Environment

-

### Angular version

19.0.6

### PrimeNG version

v19

### Node version

v22.12.0

### Steps to reproduce the behavior

-

### Expected behavior

-

**Comment by cetincakiroglu** [comment]
Closing the issue since the issue templating is invalid. Please open a new issue.
