### ISSUE TITLE
Unhandled tooltip exception after #705

### ISSUE THREAD

**Issue by johnhwright** [primefaces/primeng#1722]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/ppyWXAczsL46nDKaZQbo

**Current behavior**
**See Plunkr.** - When no text is provided, tooltip's create() is not called due to https://github.com/primefaces/primeng/issues/705 so the container is never created, but when the mouse leaves the input the hide() method is called which accesses the container.

**Expected behavior**
Tooltip with empty text will not be shown and hide method will check if (container) so it won't throw an exception. 
```
hide() {
    if(this.container) {
        this.container.style.display = 'none';
    }
    this.ngOnDestroy();
}
```
**What is the motivation / use case for changing the behavior?**
Need the ability to enable/disable tooltips, https://github.com/primefaces/primeng/issues/460 hasn't been looked at in half a year, figured this would be easier for you to get in a release.

* **Angular version:** 2.4.0

* **PrimeNG version:** 1.1.3

**Comment by cagataycivici** [comment]
ngOnDestroy already checks for this.container
