### ISSUE TITLE
Primeng style classes not reflecting in print

### ISSUE THREAD

**Issue by smtgpt62** [primefaces/primeng#1725]
I am making angular 2 app using primeng. I am trying to print a page which is using primeng datatable. I have made some changes  for datatable style classes in styles.css . But when i am printing that datatable, the styles are not reflecting i.e background color of data table header is not showing. I have done something like this in styles.css :

@media all{  
.ui-datatable th.ui-state-default{
   background-color: #bfcad5;
    color: #444d58;
   -webkit-print-color-adjust: exact !important; 
}
}

Please help me out with this issue.

**Comment by kichano** [comment]
I have the same problem.


Did you find a solution ?

**Comment by DarioN1** [comment]
I'm facing the same problem...

**Comment by smtgpt62** [comment]
Add your style classes inside "@media print" attribute in style.css
