### ISSUE TITLE
Customizable checkbox icons

### ISSUE THREAD

**Issue by Etchelon** [primefaces/primeng#1726]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
A checked p-checkbox displays a fa-check by default

**Expected behavior**
To be able to specify the icon for the p-checkbox:
<p-checkbox icon="fa-trophy"></p-checkbox>

**What is the motivation / use case for changing the behavior?**
Example: I want to mark a user as a winner of a competition: the checkbox could display a fa-trophy instead of a fa-check. It is more suitable for the context.

* **Angular version:** any

* **PrimeNG version:** any

* **Browser:** all
 
* **Language:** all

Thanks in advance.

**Comment by jacobodeharo** [comment]
According to documentation https://www.primefaces.org/primeng/showcase/#/checkbox the icon is already customisable. I think this issue can be closed @cagataycivici .

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
