### ISSUE TITLE
Tabview with buttons on one line

### ISSUE THREAD

**Issue by Lucasvo1** [primefaces/primeng#1729]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report 
[x ] feature request 
[ ] support request 
```
Is it possible to have a Tabview and a button on the same line? 

Left might have the Tabview and on the far right there might be some buttons.

**Comment by cagataycivici** [comment]
display: inline-block and vertical-align can help. Please use forum for cases like these.
