### ISSUE TITLE
Accordion add expand(accordionTabIndex) method

### ISSUE THREAD

**Issue by ilianiv** [primefaces/primeng#1730]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**What is the motivation / use case for changing the behavior?**
I need to expand an accordion tab programmatically by tab index.   
I can do this by AccordionTab.toggle() but it forces me to pass a DOM event as first argument so I should hack it with dummy event.

**Current workaround**
```
this.accordion.tabs[ index ].toggle(new Event('noop'));
```

**Expected behaviour**
```
this.accordion.expand(index);
```

* **PrimeNG version:** 1.1.3

**Comment by cagataycivici** [comment]
4.1. final brings activeIndex property that you can use to expand programmatically, better to use binding instead of method.
