### ISSUE TITLE
TreeTable - child nodes may not be accessible

### ISSUE THREAD

**Issue by matthiasscudlik** [primefaces/primeng#1731]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
* the TreeTable can possibly have infinite levels with children (thanks to lazy loading, which is very good!)
* expanding the TreeTable, at some point  (depending on screen size) the child nodes cannot be accessed anymore

**Expected behavior**
* at least the hierarchy node should be resizable

**Minimal reproduction of the problem with instructions**
* go to http://www.primefaces.org/primeng/#/treetable 
* at the demo/example for lazy loading expand a lot of levels, at some point  (depending on screen size) the child nodes cannot be accessed anymore

**What is the motivation / use case for changing the behavior?**
* on the demo page you only have 3 columns, so you can expand a lot of nodes before the issues occurs
* if you have around 10 columns, child nodes cannot be accessed after expanding only a few nodes
* in my case i have up to ~20 hierarchy levels in reality

**Please tell us about your environment:**
demo page: http://www.primefaces.org/primeng/#/treetable

Thanks a lot for providing this great library!

**Comment by cagataycivici** [comment]
TreeTable will be reimplemented, please monitor;

#4813
