### ISSUE TITLE
TreeTable - expand state is not preserved using lazy loading

### ISSUE THREAD

**Issue by mscu** [primefaces/primeng#1732]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
* expand multiple levels
* collapse the root node
* expand the root node again
* the child nodes are all collaplsed
** only occurs using lazy loading **

**Expected behavior**
* expanding the root node again should lead to the same state as is has been before
* if you are not using the lazy loading it works (!)

**Minimal reproduction of the problem with instructions**
* go to http://www.primefaces.org/primeng/#/treetable 
* at the demo/example for lazy loading expand some nodes (multiple levels)
* collapse the root node
* expand the root node again
* -> all child nodes are collapsed

**What is the motivation / use case for changing the behavior?**
* Usability
* I have to use lazy loading

**Please tell us about your environment:**
demo page: http://www.primefaces.org/primeng/#/treetable

Thanks a lot for providing this great library!

**Comment by cagataycivici** [comment]
It is a downside of lazy, I think at onExpand event, you need to keep the state on your side manually since you load the nodes.

**Comment by undertherainITA** [comment]
Sorry but... treetable lazy loading it is not also in Primefaces for JSF?
I use Primefaces JSF with dataTable and lazy loading for large database data with dynamic query with pageinfo, pagehelper, etc..
Treetable lazy loading it is not also in Primefaces for JSF?
Please help me... ;)
