### ISSUE TITLE
Custom Filter Support for DataTable 

### ISSUE THREAD

**Issue by gatapia** [primefaces/primeng#174]
I would like to add custom filter to a table.  I thought I could just add an entry to DataTable.filterConstraints but this is not exposed.

**Comment by cagataycivici** [comment]
We'll discuss this and get back to you.

**Comment by cagataycivici** [comment]
We'll try to do it after 1.0.0-beta.1. PrimeFaces has it so PrimeNG should as well.

**Comment by cagataycivici** [comment]
Let's track at #196
