### ISSUE TITLE
Have a Vertical Layout for DataTable rather than default horizontal layout

### ISSUE THREAD

**Issue by sbm977** [primefaces/primeng#1740]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[x ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/NtWWnN

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

To have a Vertical Layout of DataTable rather than using Default Horizontal Layout
**Please tell us about your environment:**

Windows 7, Webstorm, NodeJS,webpack-dev-server
* **Angular version:** 2.1.0

* **PrimeNG version:** 1.0.0-rc.5

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   6.9.1

**## I have come by a situation where I want to change the Horizontal Layout of DataTable to Vertical layout as illustrated below:**

By Default:
![image](https://cloud.githubusercontent.com/assets/23419320/21685324/2b29b6c8-d32f-11e6-878c-69cf2b2d11df.png)

My requirement
![image](https://cloud.githubusercontent.com/assets/23419320/21685289/08d58fb6-d32f-11e6-8861-1cc740aabc8a.png)

So, can anybody hint me a way to do that.

-Thanks

**Comment by cagataycivici** [comment]
Support requests should be posted to forum;

http://forum.primefaces.org/viewforum.php?f=35

Thank you.
