### ISSUE TITLE
p-dataTable does not support scrollHeight to be dynamically changed

### ISSUE THREAD

**Issue by mmlitvin** [primefaces/primeng#1744]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Unable to adjust scrollheight of the table dynamically

**Expected behavior**
scrollheight of the table is adjusted 

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/deVjwOV34xE9fygsm3r2?p=preview

**Please tell us about your environment:**
Windows

* **Angular version:** 2.4

* **PrimeNG version:** 1.1.2

* **Browser:** [Chrome Version 55.0.2883.87 m ]
 
* **Language:**  TypeScript

**Comment by cagataycivici** [comment]
Issue is not clear, provide more details please.
