### ISSUE TITLE
Fixing mistakes in datatable documentation

### ISSUE THREAD

**Issue by henriquecustodia** [primefaces/primeng#1746]
Hello, I've done a PR to fix some mistakes in datatable documentation. 
This mistakes made me lose a lot time today, so I think that is better to contribute to help the community doesn't lose time as well  :smile:.

Thank you for that amazing components!

[#1745](https://github.com/primefaces/primeng/pull/1745)

**Comment by Mrtcndkn** [comment]
Thanks
