### ISSUE TITLE
Setting current page with a query parameter

### ISSUE THREAD

**Issue by ht89** [primefaces/primeng#1747]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**

After setting the current page with a query parameter, the current page is not highlighted. For example, if the current page is set to 2, the highlighted page number is still 1.
**Expected behavior**

The page number should be highlighted based on the page number set when loading the application with a query parameter.
* **Angular version:** 2.3

* **PrimeNG version:** 1.1.4

**Comment by cagataycivici** [comment]
Use first property to change the page programmatically by binding. You can also bind it to a query param.
