### ISSUE TITLE
More tooltip positions

### ISSUE THREAD

**Issue by danielsogl** [primefaces/primeng#1753]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

I want to place the tooltips not just top, left or right.
It would be nice if it can be placed like top left or bottom right.

**Comment by agusdutra** [comment]
+1

**Comment by cagataycivici** [comment]
Sounds good, added to our roadmap.

**Comment by Pikadili83** [comment]
Is it possible to tell tooltip to follow cursor position?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
