### ISSUE TITLE
Reorder support for Grouped DataTable Headers

### ISSUE THREAD

**Issue by snowdave86** [primefaces/primeng#176]
Requesting new feature to be added to DataTable (Grouping available through dragging and dropping the column header).

**Comment by cagataycivici** [comment]
Thanks for the idea, we first need to #103 though.

**Comment by bentherunner** [comment]
Hello,

This is really a good idea and something that we need on our datatables.
Is there any progress on this?

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
