### ISSUE TITLE
Calender should handle UNIX timestamps

### ISSUE THREAD

**Issue by danielsogl** [primefaces/primeng#1760]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
Today I noticed, that the calendar module cant handle UNIX timestamps. This is important for many APIs.
This would be easy to implement with just a new Date(timeStamp);

**Comment by VeryBueno** [comment]
Any plans to implement this? We use JSON APIs and dates get serialized as unix timestamps. Thanks.

**Comment by acadario-tessi** [comment]
I would be interrested as well, I have many REST services that return timestamp in json and I must convert them to Date manually when using calendar in update forms...

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
