### ISSUE TITLE
AutoComplete should show suggestions on down arrow key

### ISSUE THREAD

**Issue by gilhanan** [primefaces/primeng#1761]
AutoComplete not showing suggestions while input value empty and pressing Arrow Down key.

(i'm not sure if it's issue or not)

http://www.primefaces.org/primeng/#/autocomplete

**Comment by GFoley83** [comment]
It would be good to get this merged.

**Comment by cagataycivici** [comment]
So should we send an empty query in this case down is clicked?

**Comment by gilhanan** [comment]
@cagataycivici Yes, i think we should so, because we have to give the opportunity for programmer to update the data.
btw, i think that some day we should refactor the component to use observable.

**Comment by mconner** [comment]
It seems that this is working, sort of, at least in primeng-4.2.2.  with multiple enabled. If I down arrow on clean autocomplete, it shows me the list.  If I type in a value, the backspace to clear the query. then down arrow, it does NOT show the list.  If then start typing, and select a option from the list, then down arrow, it works, again.

**Comment by Yoranium238** [comment]
Is there any traction on this?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
