### ISSUE TITLE
onFocus for Calendar

### ISSUE THREAD

**Issue by variable-content** [primefaces/primeng#1766]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Unable to elegantly react to focus event on the calendar input field. I have a wrapping component that needs to change its display when the calendar's input field gains focus. Currently need to use something like renderer.listen(hostEl.nativeElement.querySelector('p-calendar input'), 'focus'... to achieve this.
This component already as an onBlur event, would be nice to include onFocus for parity.

**Expected behavior**
<p-calendar
    [(ngModel)]="value" 
    (onBlur)="onBlur($event)"
    (onFocus)="onFocus($event)">
</p-calendar>

**What is the motivation / use case for changing the behavior?**
See above.

* **PrimeNG version:** 1.1.4

**Comment by Mrtcndkn** [comment]
It already has you can just use it like that

**Comment by variable-content** [comment]
Sorry, logged a few issues yesterday, this was supposed to about the Calendar, not the Dropdown, will update the issue to reflect this.

**Comment by variable-content** [comment]
Thanks @cagataycivici for getting this merged!
