### ISSUE TITLE
P-Multiselect multiple times on same component

### ISSUE THREAD

**Issue by RavGup** [primefaces/primeng#1768]
Hi,

Trying to put p-multiselect control multiple time on same component. and it's giving an error "Error trying to diff ''

Its perfectly working fine with 1 control. I tried to create a Plunket but, I didn't know how to make ref to PrimeNG control into it.

Thanks
Ravi

**Comment by dellax** [comment]
try this:
`this.formBuilder.group({
      yourModel: [[]]
 });`

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
