### ISSUE TITLE
Angular2.dev.js errors - Prevents Navigation in Showcase

### ISSUE THREAD

**Issue by snowdave86** [primefaces/primeng#177]
When navigating showcase:
this.calendarElement.datetimepicker is not a function on Calendar page (breaks navigation)
this.options.target.hasClass is not a function on ContextMenu page (breaks navigation)

**Comment by cagataycivici** [comment]
You also need to update the primeui to current dev version. I do it manually by copying files to node_modules of primeng now, I'd suggest waiting for beta1 though as we'll release primeng 1.0 beta 1 along with compatible primeui 4.2.
