### ISSUE TITLE
ControlValueAccessor interface support for DataTable

### ISSUE THREAD

**Issue by windwolfreal** [primefaces/primeng#1771]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

In many case, I want to use data-table with Reactive Form style, so that i can maintain a complex entity-have some simple type fields and some collection fields--in one formGroup, and a form control need to implement ControlValueAccessor interface.
So it would be nice if data-table support reactive form style, and I can maintain the table data by a FormArray

**Comment by usmanniqbal** [comment]
Any update on this ticket I am required same functionality?

**Comment by cagataycivici** [comment]
Keeping it here to see how many more users need it.

**Comment by jrodATX** [comment]
Would like to be able to use a Reactive form in a data table as well. thanks!

**Comment by vatsalpande** [comment]
I am trying to do the same. Any plan to include this? It will be really a great addition.

**Comment by cagataycivici** [comment]
Yes, we'll try do to it for 4.1.1.

**Comment by mlakhara** [comment]
Really happy to see the last update. I myself am working on creating a wrapper on top of PrimeNg Datatable. This would be a big boost for the library as well.

**Comment by skormel** [comment]
Any plan to include this feature? We're working with reactive forms  that include datatable so this feature will be great addition.

**Comment by michaeljohnbennett** [comment]
yes I'm having the same issue. when I bind to a form control with a selection as the values it won't work right now.

Also the pristine/isDirty checks don't get triggered on the form even if I'm bound to the formControl.

I have to write some custom logic into the form save method before emitting this back to my data store (I'm currently using ngrx redux like store for entities) so thats another issue entirely.

The datatable is amazing, having these features would be Awesome to the power infinity! 😃

**Comment by Coffee-Tea** [comment]
Is it already available in PrimeNg?
I have 4.1.3 version and can't type anything within formControls in datatable :(

**Comment by stephanie-dm** [comment]
This was already asked in this issue as well: https://github.com/primefaces/primeng/issues/1142

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.

**Comment by jaredmartinez** [comment]
whats the eta on 5.1 @cagataycivici ? Thanks for all the hard work!

**Comment by sbkpilot1** [comment]
can anyone confirm if CVA support is present in the new TurboTable?  I checked the docs and there isn't any reference to Reactive Forms so I am guess no?  Confirmation would be appreciated :)

**Comment by skormel** [comment]
Is there any update on this issue/feature?

**Comment by aleq** [comment]
Any update? Can you share example of using editable p-table (TurboTable) with reactive form (FormArray), I couldn't find any working solution so far.
