### ISSUE TITLE
[Bug] Aot compile fails with 1.1.3 and 1.1.4

### ISSUE THREAD

**Issue by EricSch** [primefaces/primeng#1772]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Compilation with ngc fails with `Error: Metadata version mismatch for module .../node_modules/primeng/components/common/api.d.ts, found version 3, expected 2
    at StaticReflector.getModuleMetadata (..\node_modules\@angular\compiler\bundles\compiler.umd.js:25219:36)`

**Expected behavior**
Compiles without error, works until PrimeNG 1.1.2

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**
Windows, Gulp with Rollup

* **Angular version:** 
2.3.0 with ngc

* **PrimeNG version:** 
1.1.3 and 1.1.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Not browser depended

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS 2.0.9, ES5
* **Node (for AoT issues):** `node --version` =   
7.2.0

**Comment by AleksandarAleksandrov** [comment]
I'm facing the same issue :(

**Comment by cagataycivici** [comment]
Should be all good now, even PrimeNG showcase runs on AOT.
