### ISSUE TITLE
scss compile task is missing from gulpfile.js 

### ISSUE THREAD

**Issue by mikosu3** [primefaces/primeng#1773]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Minimal reproduction of the problem with instructions**
I built it according to the following procedure according to [wiki](https://github.com/primefaces/primeng/wiki/Building-From-Source)

----
git clone https://github.com/primefaces/primeng.git

add dependencies to package.json

npm install
gulp build
npm start 

http://localhost:8080/resources/themes/omega/theme.css 404 not found
![schdule](https://cloud.githubusercontent.com/assets/11406992/21798827/d2fcceac-d759-11e6-90ef-03f5c44adfce.jpg)

----
As git is only committed with scss, it seems that gulp task to compile is missing

* **PrimeNG version:** 2.0.0-SNAPSHOT

**Comment by Mrtcndkn** [comment]
`sass  --watch resources/ --sourcemap=none`

You should use sass watcher for css files.

Take a look at this:
http://sass-lang.com/documentation/file.SASS_REFERENCE.html
