### ISSUE TITLE
[Feature request] - Label animation with other components

### ISSUE THREAD

**Issue by djay1977** [primefaces/primeng#1774]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

With this code, label of an input can be animated on focus by wrapping both the input and label in an element with md-inputfield style class

`<span class="md-inputfield">
    <input type="text" pInputText>
    <label>Name</label>
</span>`

Would it be possible to have the same behavior for the following components :

- AutoComplete
- Dropdown
- InputTextarea
- Calendar

**What is the motivation / use case for changing the behavior?**

To standardize the layout of my forms with the label animation

**Please tell us about your environment:**

* **Angular version:** 2.4.2

* **PrimeNG version:** 1.1.4

* **Browser:** Chrome 55 | Firefox 50.1.0 | IE 11

 
* **Language:** TypeScript 2.1

* **Node (for AoT issues):** 6.9.2

**Comment by sudheerj** [comment]
Is it specific to PrimeNG? The animations can be customized through Angular's animation package.Can you please explain what kind of animations you are doing.
