### ISSUE TITLE
[Bug] Datatable header sort indicator on columns with custom sort, where body is populated via template

### ISSUE THREAD

**Issue by lcirvin** [primefaces/primeng#1778]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://plnkr.co/edit/wu94Qh

**Current behavior**
For datatable columns with a custom sorting function, where the body is populated with a template (rather than via the "field=" attribute on p-column), a user clicks on the column header to perform a sort, and though the table contents are sorted, the header shows no indication that it is being sorted upon.

**Expected behavior**
The header is expected to behave the same as headers of sortable columns populated with the "field=" attribute, i.e. The header would be highlighted to indicate that it is being sorted upon, and an up or down arrow would be present to indicate ascending or descending order.

**Minimal reproduction of the problem with instructions**

A live example is available at:
https://plnkr.co/edit/wu94Qh
Given data defined in my component as follows:
`private data = [{id:1,name:"Jack"}, {id:2,name:"Jon"}, {id:3,name:"Janet"}, {id:4,name:"Jerry"}];`

 you can check the issue using a dataTable structured as followed:
`<p-dataTable [value]="data">
    <p-column field="id" header="ID" [sortable]="true"></p-column>
    <p-column header="Customer Name" sortable="custom" (sortFunction)="onNameSort($event)">
        <template pTemplate="body" let-nameText="rowData.name">
            {{nameText}}
        </template>
    </p-column>
</p-dataTable>`

**What is the motivation / use case for changing the behavior?** Consistency with other sortable columns

**Please tell us about your environment:** Win 10, VS2015, npm, Asp.net core rtm

* **Angular version:** 2.0.0

* **PrimeNG version:** 1.0.0-beta20

* **Browser:**  at least: Edge, Chrome, Firefox

 
* **Language:** TypeScript 2.0.3

* **Node (for AoT issues):** `node --version` =   v4.2.5

**Comment by Klinton90** [comment]
I think it works. You just need to assign `field` property to 2nd column. Probably that should be mentioned in docs or add guard/throw exception in case if `sortable` and no `field` provided.

**Comment by lcirvin** [comment]
Thanks Klinton90!  Setting a value there does cause the desired functionality to occur.  I don't think I would have guessed that there was a dependency on setting the `field` property to get the sorting graphics to show.
