### ISSUE TITLE
Calendar performance issues

### ISSUE THREAD

**Issue by variable-content** [primefaces/primeng#1781]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Render speed is very slow when there are a large number (100+) of Calendar components on the page.

**Expected behavior**
Should be little to no lag to render.
Suggested fix is to only render of the calendar overlay when necessary (currently its rendered, but hidden with display: none;). I found that this dramatically sped up render times.

**Minimal reproduction of the problem with instructions**
Add this to the calendardemo.html template:
        <button (click)="perfTest()">Perf Test</button>
        <div *ngIf="isPerfTest">
            <p-calendar *ngFor="let i of arr" [(ngModel)]="date1"></p-calendar>
        </div>
And in the CaledarDemo component class:
export class CalendarDemo {
    isPerfTest: boolean;
    arr = Array(100).fill(1);
    ...
    perfTest() {
        this.isPerfTest = !this.isPerfTest;
    }

**Please tell us about your environment:**
Windows 10

* **Angular version:** 2.X.X

* **PrimeNG version:** 1.1.4

* **Browser:** all

**Comment by ilianiv** [comment]
Accordion component has the same issue https://github.com/primefaces/primeng/issues/1808

**Comment by variable-content** [comment]
PR to fix this issue is ready to be reviewed: https://github.com/primefaces/primeng/pull/1817

**Comment by cagataycivici** [comment]
Merged 1817.

**Comment by cagataycivici** [comment]
Also removed creation of a new date for checking if day is today to reduce memory usage. Calendar performance has been improved significantly. Thank you.

**Comment by variable-content** [comment]
Awesome, thanks for taking a look!
