### ISSUE TITLE
Mouse click row item will cancel all other checkbox in Listbox with Multiple, Checkbox

### ISSUE THREAD

**Issue by zealitude** [primefaces/primeng#1782]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

Mouse click row item will cancel all other checked checkbox in Listbox with Multiple, Checkbox Mode.
Ref:
http://www.primefaces.org/primeng/#/listbox

**Expected behavior**

checked checkbox should not unchecked everytime when item 
Ref:
http://www.primefaces.org/primeng/#/multiselect

**What is the motivation / use case for changing the behavior?**

As a user, a list of checkbox is expected to behavior like multiselect.

**Comment by cagataycivici** [comment]
That is by design, a checkbox is there to add without clearing others. Still you can change this behavior with [metaKeySelection]="false"
