### ISSUE TITLE
Missing tabindex for most of components

### ISSUE THREAD

**Issue by ilianiv** [primefaces/primeng#1787]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Autocomplete, Chips, etc.. components' tabindex is not passed to the real control (input, textarea, select...).

**Expected behavior**
Tabindex for "wrapper" components like autocomplete to be passed to the real control (input).

**Minimal reproduction of the problem with instructions**
Create a simple form with autocomplete component an set it a tab index. Going through component with Tab key will focus <p-autoComplete> but not the <input> in it so you can't type text.

**Please tell us about your environment:**

* **Angular version:** 2.4.1

* **PrimeNG version:** 1.1.3

* **Browser:** [all]

 
* **Language:** [all]

**Comment by ilianiv** [comment]
This already has been done for calendar https://github.com/primefaces/primeng/issues/1549. Please do it for all other components.

**Comment by Msukumar** [comment]
how to add tabindex for p-picklist

**Comment by nkch8054** [comment]
Any update on this.
