### ISSUE TITLE
Primeng schedule component with angular cli

### ISSUE THREAD

**Issue by arat3091** [primefaces/primeng#1788]
**i am submitting a bug report[]**

i am getting TypeError: this.schedule.fullCalendar is not a function

i have included ../node_modules/primeui/primeui-ng-all.min.js in angular-cli.json

**Current behavior**

gives an error

**Expected behavior**
IT should not give an error

**Comment by Mrtcndkn** [comment]
You should add full calendar js and css to your cli.json

` "styles": [
        "../node_modules/primeng/resources/primeng.min.css",
        "../node_modules/fullcalendar/dist/fullcalendar.min.css",
        "../node_modules/quill/dist/quill.snow.css",
        "styles.scss"
      ]`

`"scripts": [
          "../node_modules/jquery/dist/jquery.js",
          "assets/layout/js/layout.js",
          "assets/layout/js/ripple.js",
          "assets/layout/js/nanoscroller.js",
          "assets/layout/js/swipe.js",
          "../node_modules/moment/moment.js",
          "../node_modules/chart.js/dist/Chart.js",
          "../node_modules/fullcalendar/dist/fullcalendar.js",
          "../node_modules/quill/dist/quill.js"
      ]`

like this.
