### ISSUE TITLE
DataTable sortField attribute cause Exception on 1.1.1+

### ISSUE THREAD

**Issue by ymuller** [primefaces/primeng#1789]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
``

**Current behavior**
DataTable do not work with primeng 1.1.1+ but is fine with 1.1.0.

Below is the exception
TypeError: Cannot read property 'find' of undefined at DataTable.ngDoCheck (datatable.js:285) 

* **Angular version:** 2.0.X
I'm running Angular 2.4.2 (the issue is there also with 2.4.0 and 2.4.1)

* **PrimeNG version:** 2.0.X
1.1.1, 1.1.2, 1.1.3, 1.1.4

**Comment by cagataycivici** [comment]
Is it possible to provide a plunkr?

**Comment by cyberrranger** [comment]
i have the same bug.

if i use sortfield => "Cannot read property 'find' of undefined at DataTable.ngDoCheck"
if i use NO sortfield => "Cannot read property 'find' of undefined at DataTable.ngDoCheck"

**Comment by ymuller** [comment]
Sorry, I am not use to plunkr by now, so below is a code snippet 
`      <p-dataTable [value]="model.list" selectionMode="multiple" [(selection)]="selectedContactPersons" sortField="firstNameAndLastName" [sortOrder]="1">
            <p-column field="firstNameAndLastName" header="{{'request.wizard.contactPerson.firstNameAndLastName.label' | translate }}" [sortable]="true"></p-column>
            <p-column field="division" header="{{'request.wizard.contactPerson.division.label' | translate }}" [sortable]="true"></p-column>
            <p-column field="department" header="{{'request.wizard.contactPerson.department.label' | translate }}" [sortable]="true"></p-column>
            <p-column field="unit" header="{{'request.wizard.contactPerson.unit.label' | translate }}" [sortable]="true"></p-column>
            <p-column field="phoneNumber" header="{{'request.wizard.contactPerson.phoneNumber.label' | translate }}" [sortable]="true"></p-column>
        </p-dataTable>`

**Comment by ASK83** [comment]
Similar issue with multisort  has been reported with a plunker, but it hasn't beenreviewed by any primeng team member. 

[https://github.com/primefaces/primeng/issues/1663](url)

 thx
