### ISSUE TITLE
MenuBar main items broken in IE11

### ISSUE THREAD

**Issue by sedma** [primefaces/primeng#1793]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://www.primefaces.org/primeng/#/menubar

**Current behavior**

Every main menubar item is broken in two lines - icon and text in IE 11. Chrome display OK.
Issue is visible in primeng showcase with IE 11
**Expected behavior**

Display of menubar should be consistent between browsers and not broken in two lines.

**Minimal reproduction of the problem with instructions**

Open IE 11 and navigate http://www.primefaces.org/primeng/#/menubar

**What is the motivation / use case for changing the behavior?**

I use your great library and would like to move to current version where other bugs are fixed. Users have IE11

**Please tell us about your environment:**

Win 7
* **Angular version:** 2.0.X

N/A
* **PrimeNG version:** 2.0.X

I have tested current version (used in showcase)

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

I use currently IE 11.0.9600.18537
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
N/A
* **Node (for AoT issues):** `node --version` =   
N/A

**Comment by sedma** [comment]
![menubar_ie11](https://cloud.githubusercontent.com/assets/22873763/21863854/609a1a54-d83f-11e6-9434-15c67f0a9d46.jpg)

**Comment by sedma** [comment]
No one experience this in IE11 ? 
It doesn't work in PrimeNG 2.0.0-RC2.. Can you please fix it. Thanks

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.

**Comment by Mrtcndkn** [comment]
Glad to hear that.
