### ISSUE TITLE
Allow static HTML in the messages component

### ISSUE THREAD

**Issue by corydorning** [primefaces/primeng#1795]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Using `p-messages` requires setting the severity and actual message in the controller unless i do this:
```
<p-messages [value]='[{"severity":"info", "detail":"your message"}]'></p-messages>
```
**Expected behavior**
Would be nice to be able to use `p-messages` and just including the message between the directive tags like this:

```
<p-messages [severity]="info">my html/content here</p-messages>
```

**What is the motivation / use case for changing the behavior?**
The use case is that simple static messages could be used where applicable instead of setting it in the controller. Also, i'm not able to insert any links in my message even if doing it via the controller

* **PrimeNG version: 1.1.4

**Comment by koesper** [comment]
The growl component already does this (PR #1414), although this might not be safe (As discussed in #1356)
But it would be a very nice idea to have this functionality in both!

**Comment by cagataycivici** [comment]
We can just allow html in message component.

```
<p-messages [value]='[{"severity":"info", "detail":"<br>your message</br>"}]'></p-messages>
```

**Comment by EltonWhybrow** [comment]
It there any ETA on this added feature

**Comment by nate-knight** [comment]
@cagataycivici I tried the above code on 4.1.1, but the html is still not rendering in the message.

**Comment by Tempus35** [comment]
I also tried static html in the detail part of the object with 4.1.1 and it is not parsing the html.

**Comment by leye0** [comment]
It looks like it works now.

**Comment by guntram** [comment]
> `<p-messages [value]='[{"severity":"info", "detail": detail}]'></p-messages>`
and in TS: `detail = \`<a href="www.google.de" target="_blank">here is a link</a>\``
works for me with primeng 6.0.0, note that it is "P-MESSAGES" and not "P-MESSAGE"...

**Comment by dcanning** [comment]
this is not working in 10 lts branch, I get this rendered:
![image](https://user-images.githubusercontent.com/1880970/111515779-93528600-8729-11eb-9cae-484375f3c67d.png)

**Comment by mmraja83** [comment]
Ref: https://github.com/primefaces/primeng/issues/8836

<p-message ... [escape]="false">
