### ISSUE TITLE
DataTableModule is not an NgModule when building from source

### ISSUE THREAD

**Issue by paddybc** [primefaces/primeng#1800]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
N/A

**Current behavior**
When I build the project from source and include it in my own angular-cli project when I build that project with ng build I get the error "Error in DataTableModule is not an NgModule".

**Expected behavior**
Using a local built copy of PrimeNG should be the same as using the version downloaded from NPM and cause any errors.

**Minimal reproduction of the problem with instructions**
- Clone the PrimeNG repo
- Branch at 1.1.4 (newest release at time of writing) and change package.json as instructed at https://github.com/primefaces/primeng/wiki/Building-From-Source
- Run:
  - npm install
  - gulp build
  - tsc
- Use the result in an angular-cli project instead of retrieving from NPM (in dependencies set version to "file:\<location\>"
- Clear node_modules of other project
- Run on other project:
  - npm install
  - ng build
- Error is shown when build is complete

This didn't happen before but it is unclear when it changed, we were on v1.0.0 before and this seems to have happened when upgrading.

**What is the motivation / use case for changing the behavior?**
N/A

**Please tell us about your environment:**
Windows 7

* **Angular version:** 2.4.3

* **PrimeNG version:** 1.14

* **Browser:** N/A
 
* **Language:** TypeScript 2

**Comment by paddybc** [comment]
After some investigation comparing what is put in node_modules when taken from a local copy and from NPM it appears this is happening because the metadata files are not being generated when I build locally. These seem to be a new addition since upgrading. Am I building the project incorrectly? How can I build and get these files?

**Comment by cagataycivici** [comment]
Please use forum for cases like these.
