### ISSUE TITLE
Defect : Menubar problem in IE11

### ISSUE THREAD

**Issue by kcsahoo** [primefaces/primeng#1801]
Menubar width issue in IE 11.
works fine in Chrome and Firefox and Microsoft Edge.
This issue is from PrimeNg v 1.1.3 onwards.
worked in previous versions.
This issue has been reported by some more users in the forum.

**Comment by sedma** [comment]
I have same issue, it's still broken in PrimeNG 2.0.0-RC2

**Comment by cagataycivici** [comment]
@mertsincan Can you please check on IE11?

**Comment by sedma** [comment]
This has already been solved several weeks ago, it is duplicated issue I think ... 
It works in IE11 now.
