### ISSUE TITLE
Listbox allow to disable items on the list box

### ISSUE THREAD

**Issue by Dekel-Cohen** [primefaces/primeng#1802]
**I'm submitting a ...**  (check one with "x")
```

[X ] feature request => Allow to disable items on the list box.
A user might not have permission to select/unselect items on the listbox, 
but we still want to make it visible.
We want an option to pass items to the list box but to specify which items are enabled and which are not, only the enabled items should be clickable.
```

**Current behavior**
All the items we pass are clickable. The user can select/unselect each item in the list 

**Expected behavior**
To be able to mark specific items as not editable.
If already selected, the user should not be able to unselect,
if not select the user should not be able to select.

**What is the motivation / use case for changing the behavior?**
We have enterprise product and often the user doesn't have permission to edit every item 
in the list, but we still want to show the data to the user.

* **PrimeNG version:** 2.0.X
As far as i can see, the feature is missing from 2.0.X and from the roadmap.

**Comment by cagataycivici** [comment]
Makes sense, we're thinking how to expose it, I mean how can you tell the component if the item is disabled or not. Maybe with a separate disabledItems property?

**Comment by Dekel-Cohen** [comment]
Sounds good to me

**Comment by brachi-wernick** [comment]
@cagataycivici  maybe if I have templates give me the ability to put the check box as a part of my template. Then I will be able to disable it myself.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by szymonmindfuel** [comment]
> If already selected, the user should not be able to unselect

This one is still needed, or couldn't find it in the documentation how to do it.
