### ISSUE TITLE
DataTable filtering keyboard entry being cleared 

### ISSUE THREAD

**Issue by HarshaAnirudhan** [primefaces/primeng#1803]
Following two observations are found while using the PrimeNG Plug In:
1.) Not able to set the Max Length for character limit <p-column>
2.) While searching in the search box, the last character is getting deleted automatically. 
    For eg: while searching a word 'ABC' the last character'C' is not getting considered in the search box.

Could you please analyze on the above issues and kindly let us know your comments on the same.

**Comment by cagataycivici** [comment]
1) You can use a custom filter template.
2) Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
