### ISSUE TITLE
Be able to define custom labels in picklist buttons. 

### ISSUE THREAD

**Issue by wesleydean** [primefaces/primeng#1804]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
No ability to customize labels of buttons in picklist. (not referrring to the target/ source controls.

**Expected behavior**
Option to customize labels with a [addLabel] and [removeLabel] directive

**Comment by cagataycivici** [comment]
But they are icons, you mean title attribute?

**Comment by wesleydean** [comment]
Yes I meant the title attribute here (guess I wasn't specific enough) but that would be a great feature :)

**Comment by sudheerj** [comment]
Do you mean that we need to add titles for each button and that too can be customized with different properties

**Comment by cagataycivici** [comment]
Yes like addTitle="Add"

**Comment by deveshsinghal22** [comment]
Hi @cagataycivici / @sudheerj , are we planning to add these changes in primng future releases?

**Comment by yigitfindikli** [comment]
We'll reconsider if there is more community feedback on this. Thank you for your report.
