### ISSUE TITLE
p-gmap in p-tabView doesn't work

### ISSUE THREAD

**Issue by saienkin** [primefaces/primeng#1806]
In one of my tabs I have to show a gmap component. 
but whatever I have tried hasn't worked. Here is my snippet:

```
<p-tabView>
        <p-tabPanel header="div1"  [selected]="true">
            <div></div>
        </p-tabPanel>
        <p-tabPanel header="gmap">
            <p-gmap.....
        </p-tabPanel>
        <p-tabPanel header="div3">
            <div></div>
        </p-tabPanel>
    </p-tabView>
```

How to overcome the problem? Thanks in advance.

**Comment by garethlewis** [comment]
What messages, if any do you get in the console?

**Comment by saienkin** [comment]
to mr garethlewis
there is no message in the console.

**Comment by sudheerj** [comment]
This issue might be because of hidden container issue.I can see this issue with customized steps wizard as well.

![image](https://cloud.githubusercontent.com/assets/3127317/25781976/d9b61f20-3373-11e7-9227-925117be6073.png)

**Comment by cagataycivici** [comment]
@Mrtcndkn take over please.

**Comment by sudheerj** [comment]
@Mrtcndkn Is it planned for 4.1 release or is it may get delayed

**Comment by Mrtcndkn** [comment]
@sudheerj It is planned for 4.1 release.

**Comment by smitpsanghavi** [comment]
I also have a similar problem where the map remains blank when I open the tab. It is not the 1st tabViw tab. The solution I found is as follows:
```javascript
private onTabChange(event: any): void {
    if ((event.index as number) === 1) {
        setTimeout(() => { window.dispatchEvent(new Event("resize")); }, 1);
    }
}
```
This was referred from this SO question: [https://stackoverflow.com/a/6879644](https://stackoverflow.com/a/6879644)

Any way this fix can be incorporate in p-gmap?

**Comment by Mrtcndkn** [comment]
Thanks for the information we fixed it with an inside method.

**Comment by smitpsanghavi** [comment]
I saw in the commit details that the map has been initialized again.
The answer I linked to has a comment where the map centre has been extracted, map "resized" and centre set once again. I hope this is not needed after @Mrtcndkn fix.

**Comment by cagataycivici** [comment]
In this method, map is initialized only when it gets visible so fixing the problem.
