### ISSUE TITLE
InputSwitch dynamic label support

### ISSUE THREAD

**Issue by apokhilenko** [primefaces/primeng#1807]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
InputSwitch width computes based on onLabel and offLabel values, and if these values was changed by some event - there are no width changes for InputSwitch component. Here are two examples:
1) If label value comes with some delay(for example, from 'translate' pipe of ng2-translate, after first load files with translations) http://plnkr.co/edit/XWs83e?p=preview
2) If label value changed by user(ToggleButton component works fine in this case) http://plnkr.co/edit/9IZ5FN?p=preview

**Expected behavior**
InputSwitch width is changed in accordance with labels

**Environment:**

* **Angular version:** 2.3.1

* **PrimeNG version:** 1.1.4

* **Browser:** [all]

 
* **Language:** [all]

**Comment by gasparbarancelli** [comment]
@cagataycivici 
the onLabel and offLabel properties of the inputswitch component have been removed, I believe you can close this issue.
