### ISSUE TITLE
Dynamic pTooltip?

### ISSUE THREAD

**Issue by pchristou** [primefaces/primeng#1809]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
Using the tooltip module, the pTooltip="value" does not get updated if fed a variable. Instead, it prints out the literal variable name.

**Expected behavior**
It should be possible to set the pTooltip to be a variable and upon the variables value changing, update the tooltip shown.

**What is the motivation / use case for changing the behavior?**
Allow for dynamic tooltips!

**Please tell us about your environment:**
Windows 7, Angular 2, ngrx

* **Angular version:** 
2.4.1

* **PrimeNG version:** 
1.1.4

**Comment by m-tomczyk** [comment]
Try:
[pTooltip]="variableName"

Your syntax works for this case only:
pTooltip="const inline string value"

**Comment by plfgavilan** [comment]
It's not working for me [pTooltip] solution

**Comment by IRCraziestTaxi** [comment]
@m-tomczyk Yeah, that does not work. `[pTooltip] is not a known input of *`.
