### ISSUE TITLE
Improve Calendar input/display formatting support

### ISSUE THREAD

**Issue by remmeier** [primefaces/primeng#1810]
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

* What is the motivation / use case for changing the behavior?

calendar has currently limited support for dateFormat="string". It should be possible to declare dateFormat and hourFormat separately for the input string and the display value. Usually backends return some standard format and it needs to be properly formatter for display to the user. As such the display and input format can differ. Potentially two new attributes inputDateFormat and inputHourFormat can be introduced.

**Comment by remmeier** [comment]
or ideally it should be able to format the output with moment.js and the appropriate locales

**Comment by cagataycivici** [comment]
Thank you, if more users demand it, we'll reconsider.

**Comment by randdusing** [comment]
Please reconsider. Having a separate display and model format would make things much easier.
