### ISSUE TITLE
primeng.css overrides  component's css

### ISSUE THREAD

**Issue by efstathiosntonas** [primefaces/primeng#1812]
I tried putting some css to override primeng.css dropdown style inside the styles:[] but the primeng.css takes over.

I tried ViewEncapsulation.None but this applies the style to the whole app's dropdowns.

Is there any other way to force the component's css to load?

**Comment by huyiwei93** [comment]
try to use !important

**Comment by cagataycivici** [comment]
This is a question, please use forum for questions.
