### ISSUE TITLE
DataTable filter input deletes characters during typing

### ISSUE THREAD

**Issue by remmeier** [primefaces/primeng#1813]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

The official examples are broken as well:

http://www.primefaces.org/primeng/#/datatable/filter

start typing "aaaaaaaaaa" into the filter input of the first column ("vin"). You will notice that some of the "a"s quickly appear and then  disappear again. 

**Current behavior**

it makes filtering very annoying.

**Expected behavior**

don't swallow any characters

**Minimal reproduction of the problem with instructions**

see above with the official example (http://www.primefaces.org/primeng/#/datatable/filter)

**What is the motivation / use case for changing the behavior?**

unusable this way

**Please tell us about your environment:**

Windows 10

* **Angular version:** 2.0.X

2.2.1

* **PrimeNG version:** 

1.1.4

* **Browser:** 

all it seems (at least Chrome, Firefox, Edge)

 
* **Language:** 

Typescript 2.0.10

**Comment by FreshG** [comment]
I also stumbled across this issue while filtering a list with about 100 entries. It makes filtering really annoying and even unusable.

**Comment by anirudh-jagithyala** [comment]
Hi,
This issue still occurs for IE, {I am using IE 11}, However chrome works fine.
Is it something to do with change() event handled by IE versus chrome? 

Any fix/workaround for IE?
