### ISSUE TITLE
Prime ng datepicker inside prime ng datatable creates css issue (it hides inside the datatable)

### ISSUE THREAD

**Issue by Shifs** [primefaces/primeng#1818]
I'm submitting a bug report:

Prime ng date picker does not work properly inside the row of the prime-ng data table. I have a scenario where on click of edit inside row, a date picker opens. In certain scenarios, the date picker gets cut basically it get hides inside the datatable. I tried overriding CSS properties but all in vain. 

Here is the screenshot for the same.
![date](https://cloud.githubusercontent.com/assets/25151484/21983943/a1797aaa-dc19-11e6-8389-096e0f012667.png)

Please tell us about your environment:
Ubuntu, Angular 2.3, PrimeNG 1.1.4

Angular version: 2.0.X
Angular 2.4.1

PrimeNG version: 2.0.X
PrimeNG 1.1.14

Browser:
All

Language:
ES6

**Comment by kanakisn** [comment]
Hi,

you can try the appendTo attribute of the p-calendar. Try to set it to an element using a  local template variable. This worked for us.

**Comment by Shifs** [comment]
@kanakisn : Thanks a lot . It worked !

**Comment by rut-t** [comment]
@Shifs can you give please a referance to documetation for prime-ng calendar? I cannot find this at their component list and I don;t know how to use it.

**Comment by Shifs** [comment]
Here is the link for prime ng calendar
http://www.primefaces.org/primeng/#/calendar




*Regards,*

Shifa Salheen
Lead Programmer Analyst
Argusoft India Limited.
www.argusoft.com

**Comment by bishu40010961** [comment]
can you provide a example. I mean how to use local template variable. I am using primeng 5.x its not working for me. same problem. 
`<ng-template let-col let-car="rowData" pTemplate="editor" #ref>
                    <p-calendar [(ngModel)]="car[col.field]" [appendTo]="ref" name="test" dateFormat="dd/mm/yy" placeholder="DD/MM/YYYY">
                    </p-calendar>
</ng-template>`

**Comment by bishu40010961** [comment]
same problem, can i get a code snippet. i tried using template ref variable, its positioning calendar overlay to bottom right corner of data-grid.

**Comment by ruipimentel** [comment]
Code snippet:

```html
<!-- Add a div outside the p-table: -->
<div #calendarWrapper></div>

<p-table
  [value]="cars"
  editMode="row"
  dataKey="identifier"
>
  <!-- ... -->
  <ng-template pTemplate="body" let-car let-editing="editing">
    <!-- ... -->
      <td pEditableColumn>
        <p-cellEditor>
          <ng-template pTemplate="input">
            <!-- Add [appendTo] to solve the CSS conflict with p-table: -->
            <p-calendar
              [(ngModel)]="car.manufacturingDate"
              [appendTo]="calendarWrapper"
            >
            </p-calendar>
          </ng-template>
          <ng-template pTemplate="output">
            {{car.manufacturingDate}}
          </ng-template>
        </p-cellEditor>
      </td>
    <!-- ... -->
  </ng-template>
</p-table>
```
