### ISSUE TITLE
Spinner with min value can be cleared with backspace

### ISSUE THREAD

**Issue by michaelilyin** [primefaces/primeng#1819]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/4p9aHzjRnI3XBw9RlBO1

**Current behavior**

1. Focus to displayed spinner
2. Type 2
3. Press 'backspace'
4. '1' will be displayed
5. Press 'packspace' again
6. Spinner is empty now

**Expected behavior**
On step 6 '1' still displayed

**Minimal reproduction of the problem with instructions**

See *Current behaviour* section

**What is the motivation / use case for changing the behavior?**

When user clearing spinner with backspace, in model variable still presented minimal spinner value. As user I expect validation error, but model is valid.

**Comment by Sergeon** [comment]
On top of that, the value of the spinner will still be the `[min]` instead of  `''`: http://plnkr.co/edit/FcAqZOvzIhpuEoyd7Fsn?p=preview

**Comment by michaelilyin** [comment]
Hm, unfortunaetrly the value sets to `[min]` in your example but in editor still sets to `''` when backspace pressed.

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview

**Comment by michaelilyin** [comment]
Ok. plunkr here. http://plnkr.co/edit/UFqc2VcHL2FVbwVrhaz9?p=preview
1. When page loaded in spinner and currenv value *(must be <min value> or null (or undefined))*
2. Set current spinner value to 2
3. Type backspace in spinner, spinner and current value will be 1 (*ok*)
4. Type backspace again. Current value is 1 but *spinner value is empty*. *(must be <min value> or null (or undefined))*

Replicating in Chrome 59.0.3071.115 (Official Build) (64-bit)
And Yandex browser 17.6.1.749

**Comment by sabithpocker** [comment]
I can replicate the same in Chrome/Windows in the above plunker.
