### ISSUE TITLE
add ngClass to growl module (Enhancement)

### ISSUE THREAD

**Issue by huineng** [primefaces/primeng#1822]
**I'm submitting a ...**  (check one with "x")
```

[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap

```

Is it possible to add an ngClass on the grown module

 <div #container class="ui-growl ui-widget" [style.zIndex]="zIndex" [ngClass]="growlClass">

The reason is that i would like to position the message bottom left or top left and by having a class i can easily do that

**Comment by kryzys69** [comment]
I haven't noticed your issue, but few hours ago I've made a PR #1828 that adds ngStyle to p-growl.

**Comment by huineng** [comment]
Perfect thank you , i have seen it in the code.. great stuff !
