### ISSUE TITLE
dataTable#rowStyleClass mess up with row styles

### ISSUE THREAD

**Issue by borovsky** [primefaces/primeng#1827]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://embed.plnkr.co/9eOs9R5GrAApHR0q3m8i/

**Current behavior**
rowStyleClass mess up with styles, e.g. it possible to have inconsistent styles: ui-datatable-even ui-datatable-odd in the same time, ui-state-highlight if no selectable rows

**Expected behavior**
rowStyleClass correctly generate class attribute

**Minimal reproduction of the problem with instructions**
In plunk, change one of the columns to match other column in the same row (triggers row class change). 
When row class changes, class list for row became inconsistent (even and odd class, highlight, etc)

* **Angular version:** 2.4.3

* **PrimeNG version:** 1.1.4

* **Browser:** all
 
* **Language:** all

* **Node (for AoT issues):** `node --version` =

**Comment by laserus** [comment]
I have faced the same and thought that it could be due to usage of [class] and [ngClass] in the same element. Fixed this with moving rule for [class] to ngClass, and unfortunately [ngClass] cannot work as this: 
```
[ngClass]="{'my-class': condition, [dt.getRowStyle(rowData, index)]:true}"
```
Thus change the ngClass to array of classnames.

**Comment by cagataycivici** [comment]
Fixed via PR
