### ISSUE TITLE
Calendar in dialog cannot be fitted

### ISSUE THREAD

**Issue by norbert-tasi** [primefaces/primeng#1829]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/oTFPKdbgNt97vgPIUjBO?p=preview

**Current behavior**

In Dialog the calendar component is only visible if the dialog is big enough to display.

**Expected behavior**

Should be visible if the dialog is small.
solution can be: In dialog should be fixed positioned

**Comment by cagataycivici** [comment]
appendTo="body" can help.
