### ISSUE TITLE
Two components require global var PUI to be defined.

### ISSUE THREAD

**Issue by dustins** [primefaces/primeng#183]
I'm not sure where this is expected to be defined, but without it being defined autocomplete and overlay error. I don't know where it is supposed to be defined, but it is probably best not to have global dependencies like this.

Edit: I see it is supposed to be defined in PrimeUI, although since this is such a small dependency, the ability to PrimeNG one without the other would be lovely, and potentially minimum effort.

**Comment by cagataycivici** [comment]
We'll see what we can do and give an update.
