### ISSUE TITLE
Unable to assign default selected value for each drop down of datatable column

### ISSUE THREAD

**Issue by srivatsavap** [primefaces/primeng#1831]
Hi, 

I am new to primeng I have rendered datatable successfully and I have rendered a column of drop downs in the datatable, so my requirement is I need to assign default selected value for each of the drop down.
for example , for drop down in the column 5 of row 1 I need a option to be selected by default while rendering or loading datatable first time itself and for column 5 of row 2  I need another option to be selected while rendering or loading of datatable.

I am attaching my code in a docx file. Please help. Thanks.
[primengdoc.docx](https://github.com/primefaces/primeng/files/713257/primengdoc.docx)
![primeng](https://cloud.githubusercontent.com/assets/12388920/22055243/376205fc-dd80-11e6-9b8d-1f9f12274ed7.png)

**Comment by cagataycivici** [comment]
Please use forum for cases like these, a plunkr can help as well.
