### ISSUE TITLE
PrimeNg datable sorting is not working properly

### ISSUE THREAD

**Issue by EkamKamboj** [primefaces/primeng#1838]
Primeng datatable sorting is not properly working in case of numeric value. Can some one debug and fix this issue on urgent basis.

Thanks in advance.

**Comment by arielpires** [comment]
I'm having this problem too!

**Comment by babajon** [comment]
Downgrading to primeNg 4.0.0-rc.1 solved this issue when sorting on dates for me. Might help you:  @arielpires  @EkamKamboj

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.

**Comment by EkamKamboj** [comment]
Thanks @Mrtcndkn Issue is not coming in latest version

**Comment by Mrtcndkn** [comment]
Glad to hear that.

**Comment by msonnad** [comment]
I am using primeng 4.3.0 , but sorting of numeric values is not proper.
