### ISSUE TITLE
Locale configuration for Schedule

### ISSUE THREAD

**Issue by lpenet** [primefaces/primeng#184]
Would it be possible to add some other attributes of fullCalendar to p-schedule ?

Having :
- minDate
- maxDate
- buttonText
- columnFormat
- dayNames
- monthNames

would be great.

dayNames and monthNames are mandatory to use the schedule in languages other than English.

**Comment by cagataycivici** [comment]
I've grouped all localized keys under locale object;

```xml
<p-schedule [events]="events" [locale]="es"></p-schedule>
```

```ts
export class MyModel {

    es: any;

    ngOnInit() {
        this.es = {
            monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio',
                'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre']
        };
    }
}
```
