### ISSUE TITLE
DataTable - Single selection selects multiple with same row entries

### ISSUE THREAD

**Issue by derchirurg** [primefaces/primeng#1856]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/OFOk18xhLMcPZ6elnuvO

**Current behavior**

I am using single selection in DataTable. If I have two rows with equal column values, the selection selects both rows instead of one. Please see the provided Plunk.

**Expected behavior**

It should select only the clicked row.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.2.3

* **PrimeNG version:** 1.1.4

* **Browser:** [all ]

 
* **Language:** [TypeScript 2.0.6]

* **Node (for AoT issues):** `node --version` =   6.7.0

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview

**Comment by adama357** [comment]
I was able to replicate this issue with this plunkr: 

http://plnkr.co/edit/AqmxZwIK0LMOMfvirRO8

**Comment by GuzzoLM** [comment]
Found the same issue here. I might be mistaken, but I think the selection in datatable is based in row data, not in row index. So, if you have two rows with equal data, both will be highlighted, even though only one was actually selected.

However, it doesn't explain why tables with similar rows, where the only difference is the date in one or more columns, show the same behaviour.

Is there any workaround for this?

**Comment by GuzzoLM** [comment]
Ok, found the workaround. You can use the **dataKey** property in order to define a field to be compared in order to find out if the rows are equal or not.

**Comment by Puneetraj02** [comment]
You can use the property of p-table ( compareSelectionBy="equals")

- "equals" compares by reference 
- "deepEquals"  compares all fields

Bydefault it set as "deepEquals"

Thanks

**Comment by PuneetRaj54** [comment]
You can use the property of p-table ( compareSelectionBy="equals")

"equals" compares by reference
"deepEquals" compares all fields
Bydefault it set as "deepEquals"

Thanks
