### ISSUE TITLE
Missing to pass the parameter 'legendTemplate' into Chart js

### ISSUE THREAD

**Issue by Vincent-Pang** [primefaces/primeng#186]
in LineChart, there is @Input() 'legendTemplate', but it is forgotten to pass into Chart.js

i.e.
this.chart = new Chart(... {
   ....
   legendTemplate: this.legendTemplate   <----- missing this parameter
})

This problem is exist in linechart, barchart, polarareachart and radarchart.
But not in piechart and doughnutchart

**Comment by cagataycivici** [comment]
Thank you.
