### ISSUE TITLE
Listbox: clicking on an item will unselect all other items

### ISSUE THREAD

**Issue by Dekel-Cohen** [primefaces/primeng#1860]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
I tried to build a Plunkr Case for it but i encountered importing the Listbox module.
Any help with it will be much appreciated. 

**Minimal reproduction of the problem with instructions**
1. Go to the documentation of Listbox: 
    http://www.primefaces.org/primeng/#/listbox 
2. Select New York, Rome (click on the checkbox)
3. Click on London (on the title, not on the checkbox) =>New York, Rome will be unselected. 

**What is the motivation / use case for changing the behavior?**
We want to use this component in our project but this bug makes this component almost unusable.

**Comment by Mrtcndkn** [comment]
Actually it's not a bug that's the way it works by design.

**Comment by Dekel-Cohen** [comment]
@Mrtcndkn The user can very easily unselect all its items,
The only way he can revet the change is by closing the modal and open it again.
I don't think that the common use case is that the user wants all it's items to be unselected 
once he clicks on an item.

Will consider to change it to be less error prone?
like clear all selected items if the user *double* click on an item..

**Comment by roni-frantchi** [comment]
@Mrtcndkn also note that the Multiselect dropdown component doesn't behave this way: http://www.primefaces.org/primeng/#/multiselect .
I find the behavior @Dekel-Cohen had mentioned to make more sense.
That said, maybe an `@Input()` could be added to make the Listbox multiselect behave more like the Multiselect component

**Comment by Mrtcndkn** [comment]
Okey we will review this behavior i will inform you guys from here. @Dekel-Cohen @roni-frantchi

**Comment by brachi-wernick** [comment]
@Mrtcndkn any progress for this?
