### ISSUE TITLE
Listbox: select all option does not work well when using the filter

### ISSUE THREAD

**Issue by Dekel-Cohen** [primefaces/primeng#1862]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
I tried to build a Plunkr Case for it but i encountered importing the Listbox module.
Any help with it will be much appreciated.

**Current behavior**
Filter the multi-select, you will see that the list box shows all items that *contains* the entered filter
but clicking will only select items that *begins* with the entered filter.

**Expected behavior**
Select-all should select all options you currently see on the listbox.

**Minimal reproduction of the problem with instructions**
1. Go to the documentation of Listbox:
     http://www.primefaces.org/primeng/#/listbox
     use the Advanced (Multiple, Checkbox and Filter) demo.
2. In the filter enter the letter 'r' => (you will see only options that contains the letter 'r', which is good)
3. Click on select-all => only Rome will be selected.

**What is the motivation / use case for changing the behavior?**
We think that selecting all items once you use the filter if a very common 
and important case in this component.
It definitely the case for us...

**Comment by cagataycivici** [comment]
@Mrtcndkn This does not fix that, it just changes the way filtering is done. Issue is still there.

**Comment by cagataycivici** [comment]
My bad, it fixes it, sorry.

**Comment by kaushikmeduri** [comment]
Can any one advise which version has this fix in https://www.primefaces.org/downloads/

**Comment by kaushikmeduri** [comment]
Can any one advise which version has this fix in https://www.primefaces.org/downloads/

I opened new ticket https://github.com/primefaces/primefaces/issues/4337
