### ISSUE TITLE
Dialog component p-dialog not respecting the resizable attribute

### ISSUE THREAD

**Issue by unaor** [primefaces/primeng#1864]
Im creating a new p-dialog in the following way
`
<p-dialog resizable="false" [(visible)]="display" modal="modal" width="300" responsive="false">`

yet its creating a modal with the resize handle and the css class .ui-dialog .ui-resizable-se

**Comment by Mrtcndkn** [comment]
Hi,

`<p-dialog [resizable]="false" [(visible)]="display" modal="modal" width="300" responsive="false">`

You should bind it.

**Comment by unaor** [comment]
Thanks, just one question, why some are binded and others no? was i suppose to know it or are the docs missing something,

**Comment by Mrtcndkn** [comment]
Actually it's angular related but when a property set true by default you should bind it to false for becoming false.
