### ISSUE TITLE
Give calendar a date list with valid dates that should be clickable in the datepicker

### ISSUE THREAD

**Issue by Mandersen21** [primefaces/primeng#1865]
I'm submitting a ... (check one with "x")

[] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

Current behavior
It's not possible to give the datePicker a list with dates that should be valid (clickable)

Expected behavior
You should be given the datepicker a list of dates, where the dates in the list should be clickable, and the dates that are not in the list, should not be selected.

PrimeNG version
1.1.4

Angular2 version
2.3.1

**Comment by Mandersen21** [comment]
Maybe it is easier to give a invalid list of dates, where these dates should be disabled :)

**Comment by cagataycivici** [comment]
There is disabledDates in newer versions.
