### ISSUE TITLE
datatable emptyMessage not working 2.0.0-rc.1 

### ISSUE THREAD

**Issue by Samisama** [primefaces/primeng#1866]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/tehXSsrFFMBCG9tdlAcJ?p=preview

**Current behavior**
empty message is not displayed when no data

**Expected behavior**
empty message should be displayed when no data

**Minimal reproduction of the problem with instructions**
add an emptyMessage attribute to your datatable, the message will not display.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows, Atom, angular-cli, tomcat backend server

* **Angular version:** 2.0.1

* **PrimeNG version:** 2.0.0-rc.1
Was working on previous version

* **Browser:** [all]
 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =   
v6.9.2

**Comment by Mrtcndkn** [comment]
It's about our datatable enhancements and new features.It's now fixed for RC2

**Comment by Samisama** [comment]
empty message not showing when you filter the datatable with a value not present in the column.
