### ISSUE TITLE
[BUG] Cant resolve components/lightbox/lightbox after updating to 2.0.0

### ISSUE THREAD

**Issue by MTechDE** [primefaces/primeng#1867]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

I updated PrimeNG 1.4.x to 2.0.0-RC1

**Expected behavior**

After updating to PrimeNG 2.0.0-RC1 i recieved this error:

```
ERROR in ./~/primeng/primeng.js
Module not found: Error: Can't resolve './components/lightbox/lightbox' in 'C:\Users\SOGL_D\workspace\gizs-frontend-angular2\node_modules\primeng'
 @ ./~/primeng/primeng.js 38:9-50
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts
```

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.4.4

* **PrimeNG version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   6.9.1

**Comment by Mrtcndkn** [comment]
Hi,

How can i replicate this problem locally it seems fine @MTechDE .

**Comment by MTechDE** [comment]
I think this is jsut a problem when you try to update the package by 'npm install --save primeng@latest"

**Comment by Mrtcndkn** [comment]
Still no lucks i updated my primeng version the latest and still locally no error about lightbox
