### ISSUE TITLE
p-inputMask not updating

### ISSUE THREAD

**Issue by todres** [primefaces/primeng#1868]
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Plunkr Case demonstrating buggy behavior:**
http://plnkr.co/edit/RtXeArlvLaLE3GCr3r6y?p=preview

**Current behavior**
When I exchange the two-way bound model variable of a p-inputmask's value from a defined value to undefined the component's value is not updated. Possilby related, the initial value isn't shown either.

**Expected behavior**
When the value of a p-inputmask becomes undefined the component should update and show the mask for an empty field.
This bug is a regression from primeng version 1.1.0->1.1.4
Use the provided plunkr to verify correct behavior in primeng 1.1.0

**Minimal reproduction of the problem with instructions**
See plunkr above, or:
Create a p-inputmask with a two-way bound value. Set the value to something matching the mask, and then programmatically change it to undefined.

**Possible fix:**
this commit [f992187a5ee2f45d8dab44816634dbba5a150a50](https://github.com/primefaces/primeng/commit/f992187a5ee2f45d8dab44816634dbba5a150a50?diff=split) moved "this.checkVal()" into the else block. Moving it behind should fix this issue, although i can't tell if that breaks the animation the commit fixed.

**Please tell us about your environment:**

* **Angular version:** 2.4.3
* **PrimeNG version:** 1.1.4
* **Browser:** Chrome 55.0.2883.87 m (64-bit) | Firefox 45.6.0
* **Language:**  TypeScript 2.0.8

**Comment by rafaelodon** [comment]
The problem is still occuring in 2.0.2. I believe the "this.checkVal();" line was mistakenly moved to inside an "else" block.
