### ISSUE TITLE
DataTable TAB in the next row

### ISSUE THREAD

**Issue by Danieleeee** [primefaces/primeng#1871]
[ ] feature request

**Current behavior**
In DataTable, with editable cels, if I press TAB button I go in the next column, but at the end of the row it don't go in the next rows.

**Expected behavior**
When I press TAB in the last colum of a record, the focus go in the first column of the next row.

* **Angular version:** 2.3.X

* **PrimeNG version:** 2.0.X

**Comment by Nattujessy** [comment]
In Addition to the @Danieleeee points,
Tab key is not working on datatable editable cell which has pTemplate="editor".
if i have dropdown in pTemplate="editor" as follows,
`<p-column [style]="{'overflow': 'visible'}" [editable]="true" field="disposition" header="Disposition">
                <template let-lineItem="rowData" pTemplate="editor">
                    <p-dropdown [options]="dispositionsOptions" [style]="{'width': '100%'}" [(ngModel)]="lineItem.disposition"></p-dropdown>
                </template>
            </p-column>`
Pressing tab key from this is not focusing on next column.

**Comment by GopiAnnan** [comment]
In addition to the above issues, Datatable with editable, Tab is not moving to the next editable columns. It moves only to adjacent Editable columns. Not to the next available editable columns.

**Comment by jtraband** [comment]
Same issue as above

**Comment by jtraband** [comment]
Also cannot tab out of an editable column that has a p-dropdown editor.

**Comment by cagataycivici** [comment]
Tracked at;

2124
