### ISSUE TITLE
Calendar needs "onClose" event

### ISSUE THREAD

**Issue by bomberblue07** [primefaces/primeng#1874]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

It would be nice if the Calendar emitted an "onClose" event that fires when the user has potentially selected a date and is done interacting with the Calendar. That way, any code I need to fire when a date/time is selected, doesn't fire every time the user increments the minute.

**Comment by Mrtcndkn** [comment]
There is an onBlur event on calendar which is exactly what you want i guess. @bomberblue07

**Comment by tanat** [comment]
@Mrtcndkn onBlur fires always, when input text blurred (when you click on calendar window)

**Comment by cagataycivici** [comment]
@Mrtcndkn, add onClose please.

**Comment by nagpvn2** [comment]
How to allow p-calendar to display only years. I didn't found any property for this. could you please help me in this.
