### ISSUE TITLE
Empty message not showing up on datatable

### ISSUE THREAD

**Issue by tallkid24** [primefaces/primeng#1875]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/B0sWBIRGXsgJInrEGOAk

**Current behavior**
When a datatable loads with no entries, the empty message doesn't display.

**Expected behavior**
Expect the empty message, whether passed as an input or the default to show up once the table loads with no entries.

**Minimal reproduction of the problem with instructions**
See plunkr above or:
Create a datatable and pass in an empty array to the values.

**Please tell us about your environment:**

* **Angular version:** 2.0.X
2.4.1

* **PrimeNG version:** 2.0.X
2.0.0-rc.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 55.0.2883.87 m
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.0.1

**Comment by Mrtcndkn** [comment]
Hi,

It's fixed for RC2.

https://github.com/primefaces/primeng/issues/1866

**Comment by viktoriya-bordyug** [comment]
Currenly only 
npm ERR! notarget 0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.9.1, 1.0.0-beta.1, 1.0.0-beta.2, 1.0.0-beta.3, 1.0.0-beta.4, 1.0.0-beta.5, 1.0.0-beta.6, 1.0.0-beta.7, 1.0.0-beta.8, 1.0.0-beta.9, 1.0.0-beta.10, 1.0.0-beta.11, 1.0.0-beta.12, 1.0.0-beta.13, 1.0.0-beta.14, 1.0.0-beta.15, 1.0.0-beta.16, 1.0.0-beta.17, 1.0.0-beta.19, 1.0.0-beta.20, 1.0.0-rc.1, 1.0.0-rc.2, 1.0.0-rc.3, 1.0.0-rc.4, 1.0.0-rc.5, 1.0.0-rc.6, 1.0.0-rc.7, 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 2.0.0-rc.1
are available.
When do you suppose to release RC2? I desperately need it with last fixes.

**Comment by Mrtcndkn** [comment]
In datatable.ts line 195 replace with this line

`<td [attr.colspan]="dt.visibleColumns().length" class="ui-datatable-emptymessage">{{dt.emptyMessage}}</td>`

It will work for you till RC2.It will be ready in 1 week.

**Comment by tallkid24** [comment]
@viktoriya-bordyug RC2 is released.

**Comment by t0ry** [comment]
Yeeeaah!
Giant thank you!!!
