### ISSUE TITLE
Dropdown and Autocomplete component inside Datatable(Primeng: 2.0.0-rc.1).

### ISSUE THREAD

**Issue by Nattujessy** [primefaces/primeng#1877]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

 

**Current behavior**

I updated primeng: 2.0.0-rc.1 and found followings,
1. Scrollable DataTable headers are not fit with datatable rows until get scrollbar.
3. scrollHeight in percentage is not working. where as it worked in pervious versions.
4. RowIndex number is showing as 'NaN'
5. Dropdown in last line of scrollable datatable is not visible.
	- Will be better if the suggestion list gets populated in upwards when its dont have space to show at bottom.
6. Performance of autocomplete is low.
	- If i have 2 autocomplete component in 30+ rows of datatable then the click event of an component became slow.
	- The click event focusing the cursor in autocomplete component after 1 or 2 seconds.
Please see images for your reference https://www.screencast.com/t/1I5XJkjUSQQ
**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Browser: Chrome 55
os: win32 x64 4gb RAM

* **Angular version:** 2.4.4

angular-cli: 1.0.0-beta.19-3

* **PrimeNG version:** 2.0.0-rc.1

* **Browser:** [all | Chrome 55 | Firefox 50 | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by Emdee89** [comment]
Can also confirm that "rowIndex" in datatable column template appears as NaN. Here is my code:
_<p-column *ngFor="xyz" header="someHeader">
            <template let-col let-rowData="rowData" let-rowIndex="rowIndex" pTemplate="body">
                      <span>{{this.getDmuPropertyValue(rowIndex, dmuProperty.name)}}</span>
             </template>
 </p-column>

First parameter rowIndex passed to that function has value NaN always.

This breaks the entire data table.

**Comment by Nattujessy** [comment]
Here is my code:
`	<p-column>
        <template pTemplate="header">
            <span class="fa fa-plus-circle" (click)="addNewLineItem()"></span>
        </template>
        <template let-rowIndexValue="rowIndex" pTemplate="body">
            <p >{{rowIndexValue}}</p>
        </template>
    </p-column>`
It showing "rowIndex" as NaN.

**Comment by Nattujessy** [comment]
A lot more releases are came..
and Point number **3, 4 & 5** are fixed in latest versions.
hence closing this issue.
