### ISSUE TITLE
[feat] Datatable: allow to specify how column is sorted

### ISSUE THREAD

**Issue by cghislai** [primefaces/primeng#1879]
When you use `sortable="custom"` on a `p-column` element with a custom sortFunction, there is no way to get the visual feedback on the column header.
It would be nice to be able to bind a `sortOrder` attribute on the column, something like
```
<p-column sortable="custom" sortOrder="-1">
<p-column sortable="custom" sortOrder="1">
<p-column sortable="custom" [sortOrder]="null">
```
that would display the colored header with the correct arrow icon.

EDIT: this problem only occurs when using custom column templating, not bound to a single 'field' on the rowData.

**Comment by lcirvin** [comment]
Is this the same as #1778  ?  If so, a user @Klinton90 kindly offered a workaround there.

**Comment by cagataycivici** [comment]
Weird, unable to replicate with PrimeNG 4.1.RC2, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
