### ISSUE TITLE
p-datatable export to CSV

### ISSUE THREAD

**Issue by tigrenok00** [primefaces/primeng#1880]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Hi,
I'm trying to use the export datatable to CSV functionality, like shown on the demo page.
1. The column header names in the excel file are the same as the field names, not the p-column headers, can it be changed? It makes more sense for the user to see the display headers.
2. How can I fix the encoding in export? I have texts in Hebrew which are fine in browser, but get messed up in excel after export.

thanks!!

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.0-rc1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by tigrenok00** [comment]
As for UTF-8 support, I discovered that if you append '\ufeff' in the beginning of the csv string, it works fine. Can you consider adding a parameter for this, please?

**Comment by tigrenok00** [comment]
There is also a dates format issue, the dates are getting exported in a very long format, which is then impossible to change to another in excel (if it could be changed, it would be less of an issue).
The exported format is as follows:
Wed Apr 26 2017 00:00:00 GMT+0300 (Jerusalem Daylight Time)
Can you please add a date format parameter or preset it to anything shorter? I would like dd/mm/yy.
Thanks!

**Comment by cagataycivici** [comment]
Moved to 2473

**Comment by HChampaneri** [comment]
Export to CSV .. date format issue, is there any alternative to it?

**Comment by agarciagan** [comment]
Regarding date format issue, I have updated the resolveFieldData function of datatable to format a date as a Excel ffriendly string when a value is an ISO date. Could it be possible to have something similar integrated on the DataTable component?

`  DataTable.prototype.resolveFieldData = function(data, field) {
    if (data && field) {
      if (field.indexOf('.') == -1) {
        //Added by me to export dates in excel compatible format
        if (moment(data[field], moment.ISO_8601, true)
          .isValid())
          return (moment(data[field])
            .format("YYYY-MM-DD HH:mm:ss"));
        //End of changes
        return data[field];
      } else {
        var fields = field.split('.');
        var value = data;
        for (var i = 0, len = fields.length; i < len; ++i) {
          if (value == null) {
            return null;
          }
          value = value[fields[i]];
          console.log(value)
        }
        return value;
      }
    } else {
      return null;
    }
  };`
