### ISSUE TITLE
Accordion tab headers underlined as of PrimeNG 2.0.0 RC1

### ISSUE THREAD

**Issue by Emdee89** [primefaces/primeng#1881]
[X ] bug report 

In my web app I updated to the latest PrimeNG 2.0.0 RC 1 and found that all of the accordian tab header bars are now underlined. I did not apply any custom style to make it underlined. Using PrimeNG 1.1.4 they were not underlined. 

Any idea why this happened?

**Comment by Mrtcndkn** [comment]
Can you upload a screenshot or sample code please.

**Comment by Emdee89** [comment]
Accordion Tabs using PrimeNG 2.0.0 RC 1
![accordion tabs primeng 200rc1](https://cloud.githubusercontent.com/assets/20860575/22248558/688cddf0-e23f-11e6-813b-c48f05c42e8f.PNG)

Accordion Tabs using PrimeNG 1.1.4
![accordion tabs primeng 114](https://cloud.githubusercontent.com/assets/20860575/22248567/6fad7e0a-e23f-11e6-89f4-70e5e2c2c6f4.PNG)

Sample code:
 <p-accordion [multiple]="false">
            <p-accordionTab [selected]="isCreationModeActivated()">
                <p-header>
                    <img *ngIf="isCreationModeActivated()" src="xyz" height="85%" />
                    <span>Basic Data</span>
                </p-header>

**Comment by sudheerj** [comment]
I'am not able to replicate on latest showcase version. So please try with latest PrimeNG version. Please comment out for any concerns.

**Comment by kerrmedia** [comment]
Happening every time for me, using CLI. Accordion header text is underlined.

**Comment by L3opard** [comment]
If you're using CLI, put this in styles.css:

```
a:-webkit-any-link {
    text-decoration : none;
}
```

**Comment by L3opard** [comment]
If you're using CLI, put this in styles.css: 

```
a:-webkit-any-link {
    text-decoration : none;
}
```

**Comment by NiarK** [comment]
I had the same issue...
For me, adding:
`.ui-accordion .ui-accordion-header a { text-decoration : none !important; }
`
to the styles.css file solve this.

**Comment by kerrmedia** [comment]
Thanks!
