### ISSUE TITLE
"Input fields" for Calender time

### ISSUE THREAD

**Issue by danielsogl** [primefaces/primeng#1883]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

Actually, the time just can be set by steppers. But it would be better, if we can type the time manually with a "input field".
it should look like this: http://valor-software.com/ng2-bootstrap/#/timepicker

**Expected behavior**

It would be much easier then just pressing the steppers.

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   2.9.1

**Comment by Ketec** [comment]
Been up for a while, any plans? The current time picker works - but if you need to enter specific minutes, you have to click  the arrows a lot until you hit the right one eventually.

**Comment by Tomdrouv1** [comment]
Hi ! Any updates for this must have feature ? Thanks

**Comment by visyan** [comment]
bump

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by Alan4DS** [comment]
This has not been solved up to now. Can someone reopen this?

**Comment by ljuborados** [comment]
@mertsincan this should really be reopened.
