### ISSUE TITLE
Schedular Issue

### ISSUE THREAD

**Issue by alikharrat** [primefaces/primeng#1884]
**Current behavior**
In the Schedular when we click on the day or on the event the start date doesn't appear but we got placerholder=99/99/9999 (even in the example on your tuto the webSite)

**Expected behavior**
We expect to get the date shown something (i guess some updates have been made on fullCalender)

I have made my own investigation, the issue is caused by the mask "attribue" the solution i found it's temporary in the function "handleDayClick" and "handleEventClick" in the affectation of this.eventstart we should have  `this.event.start=event.date.format.replace('-','');`  instead of  `this.event.start = event.date.format();`

why this is a temporary solution because when we Click on Save (to add an event for example)
when we try to console.log(this.event.start) inside "SaveEvent()" we will have for example "201701-01" instead of "2017-01-01" 

PS: when you click in the Input start date then Save() we will not have the issue "201701-01"

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
