### ISSUE TITLE
is there any posible to provide the sass for each theme?

### ISSUE THREAD

**Issue by steve3d** [primefaces/primeng#1885]
**I'm submitting a feature request  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
no sass for any theme

**Expected behavior**
provide the sass for each theme

**What is the motivation / use case for changing the behavior?**
first of all, thank you for this great ui library, but in my own project, I need to modify the css of themes to meet my requirements, but currently there is no sass for themes, so I have to modify the css my hand, this is a very boring work, and each version update require the same work to do.

So I'm wondering is there any possible to provide a sass for each theme so users can customize something based on a existing theme?

**Comment by Mrtcndkn** [comment]
With 2.0-RC.1 all themes have scss folder except bootstrap.

**Comment by steve3d** [comment]
ah..... this is my bad, I just checked the bootstrap theme folder, 

When could we have the sass for bootstrap theme?

**Comment by sudheerj** [comment]
Yes,SASS is available for all themes except bootstrap.But I'am not sure when it is going to be planned for bootstrap.

**Comment by mpierce5** [comment]
Is there any update as to when SASS for bootstrap might be available?

**Comment by cagataycivici** [comment]
Bootstrap theme will be redone as a premium theme based on sass in a month.

**Comment by fakepk** [comment]
All right, then I will migrate to another framework, sorry guys.
