### ISSUE TITLE
Editable Datatable Fields always required

### ISSUE THREAD

**Issue by TriplicateGirl** [primefaces/primeng#1889]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When using a p-datatable with the editable attribute, the fields in the p-column are now always required (introduced in 2.0.0-rc.1).

**Expected behavior**
The fields in the editable p-datatable shouldn't be always required - I would expect to see making them required as an option - not the default/only option.

**Minimal reproduction of the problem with instructions**
Using a datatable with the editable attribute, delete the information in the cell and leave the cell. You will see the field turn red for HTML 5 validation (the input will have the required attribute).

http://primefaces.org/primeng/#/datatable/editable

**What is the motivation / use case for changing the behavior?**
Using an editable datatable in my current app, the cells in the table are not always applicable for each row and are therefore often times empty. The users will no longer be able to save the form without filling in every cell in those datatables (which is not a valid business case) as the HTML 5 validation will prevent the action. Will need to continue to use 1.1.4 release, where this was not an issue.

* **Angular version:** 2.4.4

* **PrimeNG version:** 2.0.0-rc.1

* **Browser:** [all | Chrome 55

**Comment by siddharthaReddy** [comment]
@TriplicateGirl not sure if you already resolved this one. But you can checkout this [underlying angular issue](https://github.com/angular/angular/issues/10094).

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
