### ISSUE TITLE
PrimeNG 2.0-RC1 upgrade issue

### ISSUE THREAD

**Issue by mohan1304** [primefaces/primeng#1890]
Hi,

I am not sure if this is the right place to ask this question here. I posted the same in primeng forum no response so checking if someone can help me

I am trying to upgrade to PrimeNG 2.0-RC1 using "npm install primeng --save". But nothing happening and still old version is showing. 

my current primeng version : 1.1.4

I finally used "npm install primeng@2.0.0-rc.1 --save " with this command my package.json got updated as shown below

"dependencies": {
    "@angular/common": "~2.4.3",
    "@angular/compiler": "~2.4.3",
    "@angular/core": "~2.4.3",
    "@angular/forms": "~2.4.3",
    "@angular/http": "~2.4.3",
    "@angular/platform-browser": "~2.4.3",
    "@angular/platform-browser-dynamic": "~2.4.3",
    "@angular/router": "~3.4.3",
    "@types/jasmine": "^2.5.41",
    "@types/node": "^6.0.60",
    "@types/selenium-webdriver": "^2.53.39",
    "angular-in-memory-web-api": "~0.2.4",
    "core-js": "^2.4.1",
    "karma": "^1.4.0",
    "lodash": "^4.17.4",
    **"primeng": "^2.0.0-rc.1",**
    "reflect-metadata": "^0.1.9",
    "rxjs": "5.0.3",
    "systemjs": "0.19.43",
    "typescript": "^2.1.5",
    "zone.js": "^0.7.6"
  },

I am not sure if I screwed up my environment with above steps because I still see the issue https://github.com/primefaces/primeng/issues/1696

Could someone assist me on how to properly upgrade to latest primeng version.

**Comment by MTechDE** [comment]
I had also problems by updating to 2.0.0.
Uninstall it first and then reinstall PrimeNG.

**Comment by mohan1304** [comment]
Hi MTechDE

Thank you for your response.

I am new to angular2 and primeng technologies. Could you please let me know how to uninstall only primeng from my angular project.

It will be helpful if you can provide the steps

**Comment by mohan1304** [comment]
Thank you.

I uninstalled and reinstalled PrimeNG
