### ISSUE TITLE
Error with ConfirmDialog component: undefined is not a constructor (evaluating 'this.documentResponsiveListener()')

### ISSUE THREAD

**Issue by wheelerlaw** [primefaces/primeng#1891]
I'm using a `ConfirmDialog` component from the PrimeNG library in my angular 2 app. The component works fine when testing it out in a browser, but for some reason, using the component makes Karma/Jasmine explode. 

     Error: Error in ./ReturnFileParameterComponent class ReturnFileParameterComponent - inline template:2:4 caused by: undefined is not a constructor (evaluating 'this.documentResponsiveListener()') in C:/Users/wlaw/Desktop/ens_fits_ui/karma-shim.js (line 41475)
            ngOnDestroy@C:/Users/wlaw/Desktop/ens_fits_ui/karma-shim.js:71991:45 <- webpack:///~/primeng/components/confirmdialog/confirmdialog.js:140:0
            ngOnDestroy
            destroyInternal
            destroy@C:/Users/wlaw/Desktop/ens_fits_ui/karma-shim.js:41076:34 <- webpack:///~/@angular/core/bundles/core.umd.js:12361:0
            ...

In the `component.spec.ts` file, I imported both the dialog service and module needed for the dialog component to work:

    import {
        ...
        ConfirmDialogModule,
        ConfirmationService
    } from 'primeng/primeng';

    describe('Return File Parameter Component Test', () => {
    
        beforeEach(() => {
            TestBed.configureTestingModule({
                declarations: [ReturnFileParameterComponent, HtmlUserFriendlyTimePipe, Html24HourDatePipe, DayOfWeekPipe],
                providers: [
                    ...
                    ConfirmationService,
                    ...
                ],
                imports: [
                    ...
                    ConfirmDialogModule
                ]
            });
            TestBed.compileComponents();
        });

    // All my tests are here

    });

But almost every test fails. 

Here is the beginning portion of the template file:

    <div class="ui-grid-row" id="return-parameter-table">
        <h5>Return File Parameters</h5>
        <p-growl [value]="msgs" life="3000"></p-growl>
        <p-confirmDialog header="Confirmation" icon="fa fa-question-circle" width="425"></p-confirmDialog>
    ...

I'm using `jasmine-core` 2.2.5 with `karma` 1.4.0 and `karma-jasmine` 1.1.0. 

I'm running the tests with PhantomJS, but I've also tried Firefox and Chrome to see if it was a browser issue, but the error persists. 

As a workaround, I created a fake component to replace the troublesome `ConfirmDialog` component that is being declared by the `ConfirmDialogModule` module: 

```
// Fake component class because the ConfirmDialog has issues with Karma/Jasmine
@Component({
    selector: 'p-confirmDialog',
    template: ''
})
class FakeConfirmDialogComponent {
}
```

I then modified the metadata for the `ConfirmDialogModule` to look for my fake component instead of the real one:

```
TestBed.overrideModule(ConfirmDialogModule, {
    set: {
        declarations: [FakeConfirmDialogComponent],
        exports: [FakeConfirmDialogComponent]
    }
});
```

I have an idea as to why this is happening: 

When running in Karma, the `this.documentResponsiveListener` is not getting set properly in `ngAfterViewInit`:

```
if(this.responsive) {
    this.documentResponsiveListener = this.renderer.listenGlobal('window', 'resize', (event) => {
        this.center();
    });
}
```

And so when `ngOnDestroy` is called, it fails here:
```
if(this.responsive) {
    this.documentResponsiveListener();
}
```

But I don't know enough about Karma or PrimeNG (or the Angular renderer for that matter) to know exactly why that would be happening or if this is expected behavior.

**Comment by willydee** [comment]
Had the same problem today. Got it solved by using the fixture:
```
    beforeEach(() => {
        fixture = TestBed.createComponent(<componentToTest>);
	fixture.detectChanges();
    });
```

**Comment by brian428** [comment]
The frustrating thing is that this was supposedly fixed (https://github.com/primefaces/primeng/issues/1672), but the fixes were never actually merged into the master branch. I think someone forgot, but I'm hoping it'll actually get done ASAP.

**Comment by cagataycivici** [comment]
Can't replicate with 4.0.x, please drop a comment if issue persists.
