### ISSUE TITLE
dropdown with appendTo = "body" and filter="true", list moves when filter entered

### ISSUE THREAD

**Issue by SirDieter** [primefaces/primeng#1893]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/QgrjWC8Jlk3KCvaWcfh3?p=preview

**Current behavior**

when I have [appendTo]="'body'" on a dropdown and it also has filter set to true, when I enter something in the filter input field, the list moves close to the left upper corner of the screen

**Expected behavior**

The list shouldn't move after entering input in the filter.
**Minimal reproduction of the problem with instructions**
Open dialog, open dropdown, type in filter.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 7, Webstorm 2016.2.3, npm
* **Angular version:** 2.4.3

* **PrimeNG version:** 1.1.4

* **Browser:** [all]

 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =   v5.6.0

**Comment by SirDieter** [comment]
already fixed with pull request #1896

**Comment by SirDieter** [comment]
apparently the options also move when it is not in a dialog.

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
