### ISSUE TITLE
Add feature to PickList

### ISSUE THREAD

**Issue by pieterlouw1974** [primefaces/primeng#1894]
**I'm submitting a ...**  (check one with "x")
```

[x ] feature request 

add showButtons to Picklist like showSourceControls and showTargetControls

To disable a person from changing data if not allowed to , but will still be able to see what has been selected and available

**Comment by sudheerj** [comment]
The description is not clear. Not sure what do you mean by show buttons similar to showSourceControls and showTargetControls. Do you want to control buttons which exists between source and target

**Comment by pieterlouw1974** [comment]
Disable buttons if user not allowed to pick items. Cannot move items between source and target

**Comment by cagataycivici** [comment]
Why not use disabled then?

**Comment by cagataycivici** [comment]
Or do you mean readonly?
