### ISSUE TITLE
DataTable Column Hidden Property Missing(p-column)

### ISSUE THREAD

**Issue by pratikthecook** [primefaces/primeng#190]
I am using your datatable and want a hidden column, so i added the below,

`p-column field="key" header="key" hidden="true" #keycol></p-column>`
But this doesnt seem to work as the 'column.ts' in 'primeNgV1/components/column/column.ts' is missing the hidden attribute.

 Can you please add this enhancement.

**Comment by cagataycivici** [comment]
Added for 1.0.0.beta.2

**Comment by pratikthecook** [comment]
Using it..Thanks!

**Comment by cagataycivici** [comment]
Glad to hear!

**Comment by MTechDE** [comment]
You need to add this to the documentation. I found this function by google linking to this issue.

**Comment by nishapd1990** [comment]
Hi,
I am using 8.1.1 version of  primeNG datagrid and I want to hide column. But hidden="true"  is not working for me. Please help. I did't get above solutions to fix.
Please help!!
