### ISSUE TITLE
p-selectbutton focus  problem

### ISSUE THREAD

**Issue by Thavarajan** [primefaces/primeng#1902]
Not able to focus the single p-selectbutton by using tab key or any keyboard combination
TabIndex property only assign the focus to the base not for the button

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
