### ISSUE TITLE
p-overlayPanel position problem

### ISSUE THREAD

**Issue by alarive** [primefaces/primeng#1904]
When a big p-overlayPanel is attached to an element at the top of the page, the overlayPanel is not visible. Its style.top property gets set to a large negative number.

**Comment by emilianbold** [comment]
Let me know if my pull request fixes your problem.

You could also manually tweak in node_modules/primeng/components/dom/domhandler.js the absolutePosition function and make sure you have something like

```
        if ((targetOffset.top + targetOuterHeight + elementOuterHeight > viewport.height) &&
          (targetOffset.top + windowScrollTop > elementOuterHeight))
            top = targetOffset.top + windowScrollTop - elementOuterHeight;
        else
            top = targetOuterHeight + targetOffset.top + windowScrollTop;
```

**Comment by alarive** [comment]
I ended up using your PR, that fixes my issue. Thanks !

**Comment by alarive** [comment]
I'm leaving the issue until your PR get accepted.

**Comment by cyberrranger** [comment]
@emilianbold thx for your patch, is working
@cagataycivici can you please accept the pull request?

**Comment by cagataycivici** [comment]
We first flip now and if top is less than 0, then try to fit it, this is called flipfit :)

**Comment by cyberrranger** [comment]
sry is not fixed complete :/ (on split button)

![screenshot 2017-03-31 17 08 47](https://cloud.githubusercontent.com/assets/21671762/24556469/c2088568-1634-11e7-9cf4-4197b52d79ce.png)

i have on the top from the page a splitbutton with 12 entrys Jan. - Dec. is now the hight from the window > hight from all month Buttons, the overlay with the buttons open on the top

**Comment by cagataycivici** [comment]
Split button doesn't seem to use this new algorithm, please create a new ticket and we'll review.

**Comment by cyberrranger** [comment]
@cagataycivici please show #2439

**Comment by cagataycivici** [comment]
Sure, added to 4.1.RC1.
