### ISSUE TITLE
Allow codehighlighter to display unescaped code

### ISSUE THREAD

**Issue by corydorning** [primefaces/primeng#1906]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/KF9yfck7w1MS3BsGASNi?p=preview

**Current behavior**
I get an error due to the CSS curly braces { ... }

```
Error: Uncaught (in promise): Error: Template parse errors:
Unexpected character "EOF" (Do you have an unescaped "{" in your template? Use "{{ '{' }}") to escape it.) ("
}
</code>
</pre>[ERROR ->]"): AppComponent@11:6
Invalid ICU message. Missing '}'. ("
}
</code>
</pre>[ERROR ->]"): AppComponent@11:6
    at resolvePromise (VM309 zone.js@0.6.25?main=browser:429)
    at resolvePromise (VM309 zone.js@0.6.25?main=browser:414)
    at VM309 zone.js@0.6.25?main=browser:462
    at ZoneDelegate.invokeTask (VM309 zone.js@0.6.25?main=browser:236)
    at Zone.runTask (VM309 zone.js@0.6.25?main=browser:136)
    at drainMicroTaskQueue (VM309 zone.js@0.6.25?main=browser:368)
    at XMLHttpRequest.ZoneTask.invoke (VM309 zone.js@0.6.25?main=browser:308)
```

**Expected behavior**
Output highlighted CSS

**Minimal reproduction of the problem with instructions**
The following test case works if I remove the CSS curly braces from `app/app-template.html`, compared to the plunkr above:
http://plnkr.co/edit/Ly3g78mXcAqBI34MsBcx?p=preview

**What is the motivation / use case for changing the behavior?**
Being able to highlight code properly

* **Angular version:** 2.2.1

* **PrimeNG version:** 1.1.0

* **Browser:** all

**Comment by cagataycivici** [comment]
Not sure of a way to do it, we escape manually. e.g. { => &#123;
