### ISSUE TITLE
z-index always increase for background mask

### ISSUE THREAD

**Issue by IvanPrytsko** [primefaces/primeng#1907]
Hi, after some strange behavior on my project, I found that background mask `z-index` always increase, and override my components. 
I take a look to sources, and find that `DomHandler.zIndex` is a `static` property which increases in this way ```++DomHandler.zIndex```. 

Can you please comment on it, is it bug, or such behavior needed. 
Thanks!

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
it can be reproduced on
- http://www.primefaces.org/primeng/#/dialog
- http://www.primefaces.org/primeng/#/confirmdialog

**Current behavior**
on every opening `dialog`, `z-index` on `mask` always increase.

**Expected behavior**
As I expect, `z-index` shouldn't increase 

**Minimal reproduction of the problem with instructions**
Please look through `devTools` to attached background `mask` 
```<div class="ui-widget-overlay ui-dialog-mask" style="z-index: 1001;"></div>```

**What is the motivation / use case for changing the behavior?**
It can override custom component's `z-index`

**Please tell us about your environment:**
Reproduced on a DEMO page

**Comment by StevenLiekens** [comment]
I suspect that this is by design to support opening multiple dialogs at once, so that dialogs are stacked in the order that they were opened (oldest on the background, newest on the foreground).

**Comment by cagataycivici** [comment]
By design, it should be dynamic, newest at the top.

**Comment by pankajbhasker** [comment]
Facing the the same issue. How to customize this behavior?

**Comment by IvanPrytsko** [comment]
@pankajbhasker I just increase my local zindez depends on DomHandler.zIndex

**Comment by pankajbhasker** [comment]
@ivanPrytsko I resolve this problem by using the property appendTo like below

  <p-confirmDialog header="Confirmation" icon="fa fa-question-circle" width="425" appendTo="body"></p-confirmDialog>

**Comment by pankajbhasker** [comment]
`  <p-confirmDialog header="Confirmation" icon="fa fa-question-circle" width="425" appendTo="body"></p-confirmDialog>`

**Comment by omanu01** [comment]
- I am facing the same issue. I am using multiple dialog chain (It's not nested one, but calling one dialog within another one). But If I am clicking the previous dialog, the z-index of it gets increased(the one which I clicked, Not the topmost one). And The topmost dialog goes behind as it's z-index gets decreased dynamically. 

- One more point here should be noted that "modal" is not working for multiple dialog chain neither "appendTo".

- I tried specifying z-index inside my topmost dialog, but still it takes the value dynamically, not the one which I specified. I used zindex. z-index, style="z-index:9999", baseZindex and almost all the available suggestions web but not worked.

**Comment by pankajbhasker** [comment]
Try using important keyword with style like. style="z-index: 10001 !important;

**Comment by laclac777** [comment]
Try this:
[autoZIndex]="false" [style]="{'z-index': 10001}"

**Comment by PhamVanthinh2801** [comment]
I often run into problems with z-index in PrimeNg, where the confirm dialog is always hidden under the dialog. Manufacturers create custom z-index according to the user's preferences instead of automatic as it is now.
