### ISSUE TITLE
Add options to Paginator to show the total number of pages and/or items

### ISSUE THREAD

**Issue by JavierMF** [primefaces/primeng#1908]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Expected behavior**
It would be very nice if the Paginator component supports showing the total number of pages or the total number of items that it is paginating. A similar functionality is already available in the PrimeFaces library.
![captura de pantalla 2017-01-24 a las 22 52 41](https://cloud.githubusercontent.com/assets/3293795/22268545/37aaa660-e288-11e6-95dc-64e916f7f1ff.png)

**What is the motivation / use case for changing the behavior?**
Applications users need to know the total size of the collection they are navigating using a paginator and the most natural way to show that info is inside the paginator panel itself.

Would you accept a PR implementing this functionality following your guidelines?

**Comment by JavierMF** [comment]
I think issue #1661 requires a similar functionality (but the title is not very descriptive).

**Comment by keyvhinng** [comment]
+1

**Comment by pantonis** [comment]
+1 

This is basic functionality.  Didn't see any table that doesn't have this behavior.

**Comment by cagataycivici** [comment]
Tracked at #1526
