### ISSUE TITLE
DataTable header checkbox should not be checked when filter is applied

### ISSUE THREAD

**Issue by tlofgren** [primefaces/primeng#1909]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/NtWWnN
_My fork_: [http://plnkr.co/edit/imms7t?p=info](http://plnkr.co/edit/imms7t?p=info)

**Current behavior**
When the datatable has both multiple selection and global filter enabled, you can check multiple items. Then if you filter out items so that all visible items are checked, the header checkbox is also checked. This allows you to deselect all (toggle header checkbox), which removes all from selection instead of only the visible items.

**Expected behavior**

To behave like primeng <=1.1.0, the header checkbox should be clear when a filter is applied so that one cannot deselect all the items in the table.

**Minimal reproduction of the problem with instructions**

To see the issue, load [my fork](http://plnkr.co/edit/imms7t?p=preview) of the plunkr and do the following:
1. In the Filter box, type 'audi'
2. Note the header checkbox is checked
3. Uncheck the header checkbox
4. The whole selection is cleared, including the Honda item

Only the Audi items should be removed from the selection list. Or the header checkbox should not be checked. **This problem appears in the patch from PrimeNG 1.1.0 to 1.1.1.**

**What is the motivation / use case for changing the behavior?**

This bug did not exist before primeng 1.1.1, so the datatable should be modified to behave like it did before that patch.

**Please tell us about your environment:**

Windows 7 Pro

* **Angular version:** 2.4.4

* **PrimeNG version:** 1.1.1

* **Browser:** all

 
* **Language:** all

**Comment by tlofgren** [comment]
Any word on this issue? @Mrtcndkn? This defect still exists in PrimeNG 2.0.

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
