### ISSUE TITLE
p-autoComplete: Input field remains disabled if using the disabled attribute

### ISSUE THREAD

**Issue by cghislai** [primefaces/primeng#191]
When using the autoComplete component with `[disabled]="myControllerBooleanValue"`, the input remains disabled event when `myControllerBooleanValue` evaluates to `false`.

The `disabled="false"` attribute is set on the input element, but it seems that browsers only check the presence of this attribute rather than its value.  The `ui-state-disabled` class is present as well.

**Comment by cghislai** [comment]
If the dropdown button is present, it remains active

**Comment by irapopova** [comment]
Is this fixed ?
I'm using primeng": "~2.0.1" and it still has this issue

**Comment by Neonell** [comment]
As workaround I'm setting a boolean attribute in the ngOnInit method based on the input parameter value. This is working and if the boolean attribute is set to false then the element is enabled. (so false if undefined or false and true if set to true). I cannot explain why it is working only with normal attribute and not with @Input attributes... I also was surprised by this behavior as Typescript is type-safe.
