### ISSUE TITLE
Pass rowIndex to column template (pTemplate="rowexpansion")

### ISSUE THREAD

**Issue by undefinederror** [primefaces/primeng#1910]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

```
<template let-rowIndex="rowIndex" pTemplate="rowexpansion">
    {{rowIndex}}
</template>
```

**rowIndex** is currently undefined in _rowexpansion_ template, as opposed to _body_ template.

Same motivations as for https://github.com/primefaces/primeng/issues/268. **rowIndex** should be passed to whichever template gets repeated row by row.

**Comment by bakasmarius** [comment]
What is current state of this issue? Can we expect any changes anytime soon?

**Comment by cagataycivici** [comment]
@Mrtcndkn Add it please for 4.1

**Comment by atiq-ur-rehman** [comment]
<p-dataTable  (onRowDblclick)="getRowIndex($event)"></p-datatable>
in compnent.ts
getRowindex(event){
let rowIndex=this.arrayName.indexOf(event.data);
console.log(rowIndex);
}
