### ISSUE TITLE
Option to expand dropdown with arrows

### ISSUE THREAD

**Issue by Alberthaff** [primefaces/primeng#1912]
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

It would be great with an option to expand the dropdown when the up/down arrows are clicked while the dropdown is focused. It currently just changes the value instead of showing the dropdown.

A normal HTML dropdown usually expands when the up/down arrows are clicked.

**Comment by cagataycivici** [comment]
Alt+down does this same as native select.
