### ISSUE TITLE
Positioning dialog on open

### ISSUE THREAD

**Issue by laserus** [primefaces/primeng#1913]
**I'm submitting a ...
```
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
```

**Current behavior**
Any new p-dialog **always** opens in the center of viewport. This behavior is defined at:
```
ngAfterViewChecked()  ->  show() -> center()
```

**Expected behavior**
If position is set in the styles (or some inputs) do not center the dialog. This behavior could be strange for large screens. Also it could be beneficial to inherit the position of dialog from it's parent position. E.g. if button clicked and the dialog is opened, it will be opened where the <p-dialog> elements are placed. 

**What is the motivation / use case for changing the behavior?**
Usability. Flexibility.

**Comment by laserus** [comment]
There was a little bit different, but resembling issue: https://github.com/primefaces/primeng/issues/607
Although the issue in stale state.

**Comment by GabKas** [comment]
Hi,

the following fix: https://github.com/primefaces/primeng/commit/ec06e44f3ac271485f56b0191726fc129042d91c 
was removed the ngAfterViewChecked lifecycle hook in 4.0.0-rc.2.

Unfortunately the dialog does not open in the center of viewport anymore.
Because the center() function can not calculate the elementHeight properly.

**Comment by shalaby** [comment]
@GabKas same issue here, any workaround?

**Comment by GabKas** [comment]
@shalaby 
There is a solution, need to call the center() method of the dialog on the 'onShow' event:
<p-dialog #dialog ...
(onShow)="windowWrap.setTimeout(dialog.center.bind(dialog), 0)">

'windowWrap' is a wrapper service for the global Window object (for mocking, testing).
Angular: How do I get a reference to the window object? https://juristr.com/blog/2016/09/ng2-get-window-ref/
