### ISSUE TITLE
DataTable Bugs when scrollable=true

### ISSUE THREAD

**Issue by trgllc** [primefaces/primeng#1914]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/ht0MCydBQiLl7kYRQxJA?p=preview

**Current behavior**

There are several issues demonstrated when setting the scrollable attribute on the datatable module. They are listed and shown in the above plnkr. Here is a summary of them:

- Scrolling does not work unless you override the float:left to be float:none in the stylesheet - **This was fixed in RC2**
- You cannot reorder the column headers
- You cannot resize the column headers if columnResizeMode=expand. If set to fit then it works however you can't resize the last column
- Using RowGrouping the headers do not line up
- There is an underscore character showing up at the beginning of the rowgroupheader
- Using the pTemplate=editor and a dropdown. The dropdown popup does not show over the table.

**Expected behavior**

- Scrolling works without stylesheet "fix"
- Able to reorder column headers
- Able to resize column headers
- Headers line up when using rowgrouping
- Dropdown lists are shown outside of the table, not needing to scroll the table down to see its items

**Minimal reproduction of the problem with instructions**
It is in the above plnkr

**What is the motivation / use case for changing the behavior?**
Scrolling functionality is desired for best user experience, however, with the current bugs it cannot be provided.

**Please tell us about your environment:**

Windows 7, Visual Studio 2015, NPM, IIS

* **Angular version:** 2.4.2

* **PrimeNG version:** 2.0.0

* **Browser:** Chrome 55

 
* **Language:** TypeScript 2.0 | ES5

* **Node (for AoT issues):** `node --version` =

**Comment by mohan1304** [comment]
Can this issue be fixed ASAP?

**Comment by robachma** [comment]
same issue.

**Comment by akj123** [comment]
any timeline when this issue will be fixed?. I was finalizing data table component between ngxdatatable and this, but hold back as reorder and resize column features don't work with scrollable true.

**Comment by cagataycivici** [comment]
Issue is too broad, please create specific issues for each case instead of one general issue so that each of them can be treated differently.

**Comment by trgllc** [comment]
Due to lack of response we cancelled our requisition for PrimeNg support and went with another vendor for our Grid needs. We're not going to make separate bugs as we no longer are using the grid.

**Comment by ctrl-brk** [comment]
@trgllc I'm curious which one you've chosen?

**Comment by trgllc** [comment]
Wijmo

**Comment by cagataycivici** [comment]
Almost all the issues above solutions. Please note that companies usually subscribe to PrimeNG Pro support to secure our response within 4 hours. I wish good luck with your project whatever 3rd party lib you have settled on. Cheers.

**Comment by ctrl-brk** [comment]
No offense here )) We appreciate all your hard work.
But those issues are known for over a year now.
The simplest test is to enable scrolling, column resize and reorder and fill the grid with just a few records, so the scrolling is not happening. You will see header misalignment and just try to resize/reorder columns multiple times - it will have issues.

**Comment by trgllc** [comment]
Right, we had Pro Support quoted and were about to purchase, however, we stopped it to look at alternatives due to lack of response or posted roadmap in regards to these issues. 

We are pleased with all of the other controls in the toolkit and appreciate the response given to any issues that arise other than the grid. We can also appreciate how big of an undertaking the grid component is, and do not envy you having to support so many features within it.

**Comment by cagataycivici** [comment]
Resize+Scroll is tracked seperately at, if you think issues persist, please create a new ticket with a plunkr.

https://github.com/primefaces/primeng/issues/1005
