### ISSUE TITLE
Scheduler do not load initial events

### ISSUE THREAD

**Issue by JacobSiegle** [primefaces/primeng#1915]
Previously using primeNG 1.1.4, FullCalendar 3.1.0, JQuery 3.1.1.
Upgraded using primeNG 2.0.0-rc.1, FullCalendar 3.1.0, JQuery 3.1.1.

I see in parent 7ae654b commit 4bed5403025827c8017b2f04b85fe80faa105b3f that this snippet of code is removed in the options.

```
events: (start, end, timezone, callback) => {
         callback(this.events);
},
```

Adding this back in causes events to show again on the schedule.

**Comment by wonbyte** [comment]
+1

**Comment by wonbyte** [comment]
@JacobSiegle Can you make a PR to fix?
