### ISSUE TITLE
Dropdown with Angular2Forms

### ISSUE THREAD

**Issue by Klinton90** [primefaces/primeng#1917]
Could you please provide example for using `p-dropdown` with Angular2Forms. I searched SO and Github. There is ticket that says that new Angular2 Forms are supported, but I still cannot make it work. Answer on SO is related to old FormAPI. Here is Plunkr, thanks: 
[plunkr](http://plnkr.co/edit/2gn8F1JcC3pYAOZ2dhzZ)

**Comment by ebosantos** [comment]
`<p-dropdown [options]="cities" formControlName="cityId"></p-dropdown>`

`FormGroup form;`

```
this.form = this.fb.group({
    cityId:                ['', [Validators.required]]
});
```

**Comment by Klinton90** [comment]
Thank you for your answer. I meant use example with template-driven forms, not model-driven (my bad, I have to be more precise). Anyway, thank you. As I'm going to switch to Model-driven forms...

**Comment by cagataycivici** [comment]
Please use forum for cases like these.
