### ISSUE TITLE
Dropdown inside of a <label> doesn't close on item select

### ISSUE THREAD

**Issue by AUsernameForGitHub** [primefaces/primeng#1918]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/SUGlWpR767ZaLsFftJKI?p=preview

**Current behavior**
Dropdown does not support label-for due to ID not propagating onto the correct element, as such, the only way to get label-click events to expand the dropdown are to put the dropdown inside the label (an alternative label-for approach). However, doing this causes the label's click events to also fire on dropdown-related click events (et al.) both doubling up the label events and also causing the dropdown to re-open when an item is selected.

**Expected behavior**
Single label click events expand dropdown and selecting an item closes the dropdown.

**Minimal reproduction of the problem with instructions**
See plnkr: http://plnkr.co/edit/SUGlWpR767ZaLsFftJKI?p=preview

**Comment by cagataycivici** [comment]
Dropdown should not be placed inside label.

**Comment by AUsernameForGitHub** [comment]
Agreed. But label-for doesn't work with Dropdown because the ID doesn't
propagate down to the appropriate element.

**Comment by cagataycivici** [comment]
There is inputId property for that.

**Comment by Giwayume** [comment]
Dropdowns inside of labels are valid HTML5. You should reconsider.
