### ISSUE TITLE
p-tooltip inside a scrollable table is mispositioned 

### ISSUE THREAD

**Issue by ASK83** [primefaces/primeng#1922]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
This punker showcase the behavior and the magnitude of mispositioning will be worse with a bigger table.  
http://plnkr.co/edit/43HqrN?p=preview

**Current behavior**
When we have a scrollable table and we want to show a tooltip on the columns the tool tip will be wrongly positioned after scrolling down. I tried both positionStyle of fixed and '' and none was working.

**Expected behavior**
The tool tip needs to be appearing close to the hovered element in a table not down the page. 

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
It will be great if one could put a tooltip for extra details of a given row in a table. 

**Please tell us about your environment:**

Windows, VSCode, npm
* **Angular version:** 2.0.X
>2.0.

* **PrimeNG version:** 2.0.X
2.0.0-rc.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
probably all browsers but was tested on opera, and chrome.
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by Mrtcndkn** [comment]
Hi,

Could you please try to add positionStyle="fixed" to tooltip applied element.

**Comment by ASK83** [comment]
Thanks for the response. 
I updated my plunker link, I don't know why it wasn't working before but now works. 
I do have the positionStyle="fixed" in my span element. Here is the code snippet. 

`<p-column field="brand" >
      <template pTemplate="body" let-col let-row="rowData">
                <span [pTooltip]="row[col.field]" positionStyle="fixed">
                  {{row[col.field]}}
                </span>
            </template>
    </p-column>`

Is there anything wrong that I am doing here?

**Comment by Mrtcndkn** [comment]
It seems normal is it working now?

**Comment by ASK83** [comment]
no, when you scroll down the tip will appear down in the page instead of besides the item in the table. The mispositioning gets worse when you scroll down.

**Comment by Mrtcndkn** [comment]
Okey i will review that and get back to you.

**Comment by cagataycivici** [comment]
#1968 should fix this, I've added documentation as well.

Scrolling Containers
When placed inside a scrolling container like an overflown div such as scrollable datatable cells, tooltip must be appended to another element that has relative positioning instead of document body which is the default.

```
<div pTooltip="Enter your username" appendTo="target" style="position:relative">
```

**Comment by ASK83** [comment]
Thanks for this. I tried it but wasn't able to make it work. Not sure what i am doing wrong that still the tip appears at the column. Here is my code using PG2-rc3.

` <div #out style="position:relative">
<p-dataTable [value]="sales" [multiSortMeta]="multiSortMeta" scrollable="true" scrollHeight="200px">
    <p-headerColumnGroup>
        <p-row>
            <p-column header="Brand" rowspan="3"></p-column>
            <p-column header="Sale Rate" colspan="4"></p-column>
        </p-row>
        <p-row>
            <p-column header="Sales" colspan="2"></p-column>
            <p-column header="Profits" colspan="2"></p-column>
        </p-row>
        <p-row>
            <p-column header="Last Year" ></p-column>
            <p-column header="This Year"></p-column>
            <p-column header="Last Year"></p-column>
            <p-column header="This Year"></p-column>
        </p-row>
    </p-headerColumnGroup>
    
    <p-column field="brand" >
      <template pTemplate="body" let-col let-row="rowData">
                <span [pTooltip]="row[col.field]" [appendTo]="out" >
                  {{row[col.field]}}
                </span>
            </template>
    </p-column>
    
    <p-column field="lastYearSale"></p-column> 
    <p-column field="thisYearSale" ></p-column>
    <p-column field="lastYearProfit" ></p-column>
    <p-column field="thisYearProfit" ></p-column>
</p-dataTable>
</div> `

and here is the link to my original plunker
http://plnkr.co/edit/43HqrN?p=preview

Thanks for your help!

**Comment by johnhwright** [comment]
@ASK83 
There's no need for 
`<div #out style="position:relative">`

Update your column to:
```
    <p-column field="brand" [style]="{'overflow':'visible'}" >
      <template pTemplate="body" let-col let-row="rowData">
          <span [pTooltip]="row[col.field]" appendTo="target" style="position: relative;">
            {{row[col.field]}}
          </span>	
      </template>
    </p-column>
```

**Comment by ASK83** [comment]
Thanks @johnhwright it worked!

**Comment by unaor** [comment]
@johnhwright i have long text on my column so i don't want to use the [style]="{'overflow':'visible'}" on the column, but this way te tooltip only shows the point, and no room for the rest
`<p-column field="message" header="Message">
      <ng-template let-col let-compliance="rowData" let-ri="rowIndex" pTemplate="body">
        <span pTooltip="{{compliance.message}}" tooltipPosition="left" class="no-wrap" appendTo="target" style="position:relative;">{{compliance.message}}</span>
      </ng-template>
    </p-column>`

the no-wrap class does : white-space: nowrap

**Comment by harveenchadha** [comment]
I have the same issue as that of unaor. Has anyone find the workaround for this?

**Comment by harveenchadha** [comment]
For all those who are in this scenario, where they cannot let the column to overflow.
1.  Make sure you use appendTo="body"
```
<p-column header="Online Name"  [sortable]="true" >
              <template pTemplate="body" let-col>
                <span pTooltip="Blue for Business" appendTo="body"  style="position:relative;"  tooltipPosition="top">Blue for Business</span>
               
               
              </template>
              
            </p-column>

```

this is a change you have to do it in your ts file.

2. Also there will be a change in tooltip.js

```
case 'top':
                left = targetLeft + (this.domHandler.getOuterWidth(this.el.nativeElement) - this.domHandler.getOuterWidth(this.container)) / 2;
                top = targetTop -  this.domHandler.getHeight(this.container);
		top=this.el.nativeElement.getBoundingClientRect().top-31; // just override the top to the top of the bounding rectangle and you will get the tooltip at right position
				
                break;
```
