### ISSUE TITLE
Spinner onChange doesn't fire with buttons

### ISSUE THREAD

**Issue by kuba-010** [primefaces/primeng#1927]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Here's an example plunk
http://plnkr.co/kOfz0R

**Current behavior**
Open the plunk and click the check box, you'll see a value in the last event value. Use the spinner to change the number value, and nothing happens. Update the input manually (just type a value) it'll set the last event value to object event.

**Expected behavior**
Using the spinner should output an event

**Minimal reproduction of the problem with instructions**
as above

**Comment by patriknil90** [comment]
I've also noticed this bug. Can't see where in the source code it may fail though.

**Comment by buchatsky** [comment]
spinner.js
