### ISSUE TITLE
DataTable rowGroupMode="rowspan" doesn't work without sortField

### ISSUE THREAD

**Issue by ilianiv** [primefaces/primeng#1928]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/p7yLad?p=preview

**Current behavior**
If you remove `sortField` from p-dataTable with rowGroupMode="rowspan" it doesn't group anything.

**Expected behavior**
You should be able to group in rowspan mode without sortField. Maybe groupField should work with rowspan mode as it works with subheader mode.

**Minimal reproduction of the problem with instructions**

Remove `sortField` from p-dataTable with rowGroupMode="rowspan".

**What is the motivation / use case for changing the behavior?**

Don't want to sort rows.

**Please tell us about your environment:** all 

* **Angular version:** 2.4.x

* **PrimeNG version:** primeng@2.0.0-rc.1

* **Browser:** all

* **Language:** all

**Comment by cagataycivici** [comment]
Grouping requires sorted data at the moment so required for now.
