### ISSUE TITLE
Dropdown rendering below table

### ISSUE THREAD

**Issue by TekSiDoT** [primefaces/primeng#193]
The new implementation seems to render below the following table row when created inside a row template:

![dropdown_overlay](https://cloud.githubusercontent.com/assets/10874046/14459162/aa8967b6-00b6-11e6-8392-5ea237fe2867.PNG)

**Comment by cagataycivici** [comment]
DataTable cells have overflow: hidden, you can make this work by;

```xml
<p:column style="overflow:visible"
   <template
       <p-dropdown
```

So that dropdown overlay can be displayed fully.

**Comment by TekSiDoT** [comment]
Thanks, however, the error persists. I've switched off all custom CSS to make sure there's no interference.

**Comment by cagataycivici** [comment]
I'm unable to replicate;

```xml
       <p-column field="color" header="Color" style="overflow:visible">
            <template #col #car="rowData">
                <p-dropdown [options]="cities"></p-dropdown>
            </template>
        </p-column>
```

<img width="343" alt="screen shot 2016-04-13 at 19 18 09" src="https://cloud.githubusercontent.com/assets/686247/14500893/898a2acc-01ac-11e6-8ec8-9938358b8a3d.png">

**Comment by TekSiDoT** [comment]
I've traced the error to a dynamic setting that overwrote the static style=' ', my bad. Thanks for your help!

**Comment by TekSiDoT** [comment]
It does, however, still render below the bottom of the table, creating a vertical scroll bar instead:

![renderbelow](https://cloud.githubusercontent.com/assets/10874046/14520719/4a66260a-0226-11e6-81fd-2edd2f979eaf.PNG)

**Comment by cagataycivici** [comment]
This is a regular table right? Not scrollable.

**Comment by TekSiDoT** [comment]
It's non-scrollable, correct.

**Comment by cagataycivici** [comment]
Ok, we'll check. Reopening.

**Comment by TekSiDoT** [comment]
excellent, let me know if you need help reproducing

**Comment by cagataycivici** [comment]
Fixed on PrimeUI side by removing overflow auto from ui-datatable-wrapper.

**Comment by TekSiDoT** [comment]
excellent, I manually excluded the respective css lines, this resolved the issue.

**Comment by alex4033** [comment]
Hi, I 'm trying to do the following:

`	<p-dataTable  [value]="detailList">
	    <p-column header="idDetail">
			<template let-col let-detail="rowData" let-rowIndex="rowIndex">
				<input type="text" placeholder="Required" [(ng-model)]="detail.idDetail"/>
			</template>
		</p-column>
	</p-dataTable>`

My question is what is the correct way to use the ngModel within the <p - dataTable >

**Comment by GopiAnnan** [comment]
@cagataycivici 
about this issue. 
Fixed on PrimeUI side as css of datatable is there by removing overflow auto from ui-datatable-wrapper.

Still I have that issue.. Last row dropdown overflow is hiding. 

Could you please confirm this fix is still available ? I dont see any css class name(ui-datatable-wrapper) as part of datatable.css
