### ISSUE TITLE
Select a range of consecutives dates using a single Calendar

### ISSUE THREAD

**Issue by LHIOUI** [primefaces/primeng#1931]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
It will be nice if the Calendar component could manage to select a range of dates instead of one date value. 
**example** : showing in the input 01/27/2017-01/31/2017 as start and end dates and styling the date between theses dates. I'm planning the add the feature my self by adding a boolean input indicating if i am selecting a single date or a range of dates also i will change the model to be an array in case the calendar mode is set to selecting range of dates, then styling all dates in the range

**Comment by cagataycivici** [comment]
Tracked at;

https://github.com/primefaces/primeng/issues/1621
