### ISSUE TITLE
Default value is ignored by InputMask

### ISSUE THREAD

**Issue by crimpphantom** [primefaces/primeng#1933]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
See plunker http://plnkr.co/edit/2nmx8Wtqxfhn93aWPHi3

**Current behavior**
Default value will be ignored in inputMask. 

**Expected behavior**
Default value will be display in the inputMask.

**Minimal reproduction of the problem with instructions**
See plunker http://plnkr.co/edit/2nmx8Wtqxfhn93aWPHi3

**What is the motivation / use case for changing the behavior?**
Bugfix

**Please tell us about your environment:**
Windows 8, Linux Mint

* **Angular version:** 2.0.X
2.2.0

* **PrimeNG version:** 2.0.X
2.0.0-rc.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Test with Firefox 50.1.0

**Comment by digitalcraftco** [comment]
This looks like the issue where it strips the last character off. I added another letter to the variable and it shows up but removes the last character on the input field.

See Plunk: http://plnkr.co/edit/C6M7SlFQnldM9YvGeklK

**Comment by howlettt** [comment]
This has been fixed in version 2.0.0

**Comment by crimpphantom** [comment]
The problem was not fixed in version 2.0.0. -> see Plunk and change the primeng version in the systemjs.config.js.

**Comment by howlettt** [comment]
See my fork of the Plunk using 2.0.0 http://plnkr.co/edit/Lt0zP8Lt9USwSELH2CEZ?p=preview
The input has the value "Test" in it on load, thought the issue was that the input was empty before, am I misunderstanding something?

**Comment by crimpphantom** [comment]
You are right! Thank you for the hint! My retest was wrong! With 2.0.0 the error was fixed! :-)
