### ISSUE TITLE
Filtering on formatted date

### ISSUE THREAD

**Issue by h3llrais3r** [primefaces/primeng#1938]
This is more a question if this is foreseen or not.
I'm using a template for the column to format my date in DD/MM/YYYY format.
I now also want to filter on this column, so I've enabled the filter on this column.
Is it possible to filter on the formatted value instead of the Date value?

I already tried to use the template also for filtering, but I don't see how I could filter on the formatted value instead of the real value.

```
<p-dataTable #dt [value]="listAccounts" [paginator]="true" [rows]="10"  [pageLinks]="3" [rowsPerPageOptions]="[5,10,20]">
            <p-column field="createdOn"  header="{{'accounts.list.label.createdOn' | translate}}" [sortable]="true" [filter]="true" filterMatchMode="contains">
                <template pTemplate="body" let-col let-account="rowData">{{ account.createdOn | date: dateFormat }}</template>
                <template pTemplate="filter" let-col>
                    <input type="text" pInputText class="ui-column-filter" [value]="dt.filters[col.field] ? dt.filters[col.field].value : ''" (click)="dt.onFilterInputClick($event)" (keyup)="dt.onFilterKeyup($event.target.value, col.field, col.filterMatchMode)"/>
                </template>
            </p-column>
 </p-dataTable>
```

**Comment by ctrl-brk** [comment]
Try to use pipe for date formatting instead of template. I think it works for me.

**Comment by h3llrais3r** [comment]
Where will you use it? Because using it inside the 'field' does not work...

**Comment by ctrl-brk** [comment]
I'm sorry. Never mind. You are right, still need a template. Sorting seems to work though.

**Comment by h3llrais3r** [comment]
Sorting yes, because it sorts on the date object, which works.
Filtering not... because I want to filter on the formatted date string.

**Comment by pete-wright** [comment]
We are hitting this issue also, any fix/workaround?

**Comment by babajon** [comment]
@pete-wright  Downgrading to primeNg 4.0.0-rc.1 solved this issue when sorting on dates (which are numerical values) for me. Might help you: @arielpires @EkamKamboj

**Comment by cagataycivici** [comment]
Dup of #815
