### ISSUE TITLE
Dropdown size not set when inside dynamic TabView

### ISSUE THREAD

**Issue by TekSiDoT** [primefaces/primeng#194]
The size of dropdowns inside table rows of tables within dynamic TabViews is only correctly rendered on the first active tab:

![dropdown_size](https://cloud.githubusercontent.com/assets/10874046/14459236/013dd678-00b7-11e6-9c71-c8a778c93bfa.PNG)

**Comment by cagataycivici** [comment]
This is expected, for example please see;

http://forum.primefaces.org/viewtopic.php?f=35&t=45113

I'd suggest;

{code}
<p-dropdown [autoWidth]="false" style="width:100%">
{code}

or

{code}
<p-dropdown style="width:100%">
{code}

**Comment by TekSiDoT** [comment]
perfect, thank you!
