### ISSUE TITLE
P-Calendar Restrict Example - Bug?

### ISSUE THREAD

**Issue by ahmni01** [primefaces/primeng#1941]
Hello,

The Restrict example for Calendar (in the primeng examples) shows that the Calendar is all disabled, not able to select any date within the restricted date as well. I tried to run the example code and I see the same behaviour:
[http://www.primefaces.org/primeng/#/calendar](url)

Few members from forum have confirmed the bug as well:
[http://forum.primefaces.org/viewtopic.php?f=35&t=48830](url)

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**
Just look at the Restrict Example to confirm the bug:
[http://www.primefaces.org/primeng/#/calendar](url)

**Current behavior**
Not able to select a date within or outside the restriction date. Basically the entire calendar is disabled and disallows date selection.

**Expected behavior**
Allow the selection of date within the restricted range.

**Minimal reproduction of the problem with instructions**
Just look at the Restrict Example to confirm the bug:
[http://www.primefaces.org/primeng/#/calendar](url)

**Please tell us about your environment:**
MacOS Sierra

* **Angular version:** 2.0.X
"@angular/core": "~2.4.0",

* **PrimeNG version:** 2.0.X
"primeng": "^2.0.0-rc.2",

* **Browser:** 
Tested on Browser - Chrome 55.0.2883.95 (64-bit) and Safari
 
* **Language:**  ES5]

* **Node (for AoT issues):** `node --version` =   v6.9.2

**Comment by sudheerj** [comment]
I can't replicate the issue with latest local build.May be showcase build not having this fix.

![image](https://cloud.githubusercontent.com/assets/3127317/22404360/604d36c4-e66a-11e6-87fc-22c86221aa51.png)

**Comment by mertsincan** [comment]
Please see; https://github.com/primefaces/primeng/commit/ba4c3f7269dcdb7cc4f93894181975c5ede8aee7

**Comment by sudheerj** [comment]
Is it an issue with demo example or source code?

**Comment by mertsincan** [comment]
Hi  @sudheerj,
There was a problem with the demo page. I changed calendardemo.ts to fix this problem.
