### ISSUE TITLE
Shouldn't p-calendar getUTCHours() instead of getHours()

### ISSUE THREAD

**Issue by marcinkaszuba** [primefaces/primeng#1942]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
Today I have noticed that when p-calendar gets the value of for example `Thu Jan 26 2017 08:15:00 GMT+0100 (CET)` it displays 08:15 while it should display 07:15 according to the shown and passed timezone. 

**Expected behavior**
In my opinion p-calendar should take into consideration passed timezone so in the presented case it should display 7:15 instead of 8:15.

**What is the motivation / use case for changing the behavior?**
I think that in the most of the applications that use such fields as p-calendar timezones are everywhere and it may be a little bit annoying to programatically change it everytime so it displays the correct value. It may be clearly visible, when used with schedule, where for example when user clicks cell presenting 7:00 AM, it passes the date in the following format: `Thu Jan 26 2017 08:15:00 GMT+0100 (CET)` (of course after changing from momentjs to JavaScript object), then we would like to show the hour in the p-calendar field, but it gets only 08:15 and completely ignores the timezone, while it should display 07:15.

I think that the possible reason is in the `formatTime()` function of CalendarComponent, which uses 
`getHours()`, `getMinutes()` and `getSeconds()` functions. I think that it should use `getUTCHours()`, `getUTCMinutes()` and `getUTCSeconds()`, so it looks like:

```
let hours = date.getUTCHours();
let minutes = date.getUTCMinutes();
let seconds = date.getUTCSeconds();
```

If you don't agree with above, and it is solved like that on purpose, I would really appreciate the explanation.

* **Angular version:** 2.4.3

* **PrimeNG version:** 2.0.0-rc.1

**Comment by nahkh** [comment]
I'm also facing this issue. I currently don't see a way to pass a timezone attribute through p-calendar to fullcalendar. This is blocking our use case and if it's not resolved we'll have to fall back to using fullcalendar directly.
