### ISSUE TITLE
pButton disabled doesn't work with pTooltip

### ISSUE THREAD

**Issue by djay1977** [primefaces/primeng#1945]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

When i declare a pButton with pTooltip, disabled behavior doesn't work

**Expected behavior**

The pButton must be disabled if true

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.4.5

* **PrimeNG version:** 2.0.0-rc.2

* **PrimeNG utima version:** 2.0.0

* **Browser:** Chrome 55 | Firefox 50.1.0 | IE 11

 
* **Language:** [all | TypeScript 2.1.4 | ES6/7 | ES5]

**Comment by cagataycivici** [comment]
This is expected as browser does not fire the events that triggers the tooltip if the target is disabled.
