### ISSUE TITLE
[FEATURE] Autocomplete pass index of option to itemTemplate

### ISSUE THREAD

**Issue by Petr0vi4** [primefaces/primeng#1946]
**I'm submitting a ...** (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
You can't access the index of autocomplete's option in itemTemplate.

**Expected behavior**
You can access the index of autocomplete's option in the same way you access it in ngFor:
```
<p-autoComplete>
    <template let-item let-idx="index">
        {{idx}} - {{item.name}}
    </template>
</p-autoComplete>
```

* **Angular version:** 2.4.0

* **PrimeNG version:** 1.1.4

* **Browser:** all
 
* **Language:** all

* **Node (for AoT issues):** `node --version` =  6.7.0

**Comment by Petr0vi4** [comment]
PR #1944

**Comment by cagataycivici** [comment]
Merged.
