### ISSUE TITLE
[iOS only] Dropdown Autocmoplete doesn't show suggestions by clicking on dropdown button 

### ISSUE THREAD

**Issue by silver-486** [primefaces/primeng#1948]
[X ] bug report

**Plunkr Case (Bug Reports)**
Issue is reproduces even on the page with examples from documentation
http://www.primefaces.org/primeng/#/autocomplete

**Current behavior**
1.Try to tap on autocomplete dropdown button
2. Nothing happens

**Expected behavior**
1.Try to tap on autocomplete dropdown button
2.Panel with options is opened

**Minimal reproduction of the problem with instructions**
There is nothing special actions to reproduce, it just doesn't work
1. Open page
2. Tap on autocomplete dropdown button
3. Nothing happens

**What is the motivation / use case for changing the behavior?**
It would be very useful if it will work on iOS properly.

**Please tell us about your environment:**
iOS 10.2.1
reproduces in Safari and Chrome

* **Angular version:** 
2.4.1

* **PrimeNG version:**
2.0.0-rc.1

* **Browser:** 
Chrome 55.0.2883.79 
iOS 10.2.1 Safari
 
* **Language:** 
TypeScript 2.0.10 

* **Node (for AoT issues):** 
node --version = v6.9.1

**Comment by ar53n** [comment]
+1

**Comment by herrstrom** [comment]
I have the same problem. Do you have any idea when this bug can be solved?

**Comment by ar53n** [comment]
@herrstrom in a few days I'll look at the cause of the problem

**Comment by ar53n** [comment]
https://github.com/primefaces/primeng/blob/master/components/autocomplete/autocomplete.ts

When we click on button not invoke show() function and no changes any classes and styles, but when we typing in input this function invoke and we see suggestions. 

Need more time for debugging and fixing problem

**Comment by Mrtcndkn** [comment]
What is your current PrimeNG version? @silver-486 @ar53n @herrstrom  I tried it with the latest versions of PrimeNG (4.1.0 RC2) and angular (4.2.3) and it's working is this issue still persists?

**Comment by herrstrom** [comment]
Version 2.0.X

**Comment by Mrtcndkn** [comment]
Could you please try it with latest versions?

**Comment by Mrtcndkn** [comment]
If issue persists on the latest version of primeng 4.1.0-RC2 feel free to open the ticket again.
