### ISSUE TITLE
DataTable reset() method doesn't clear all filter input fields

### ISSUE THREAD

**Issue by Svrkota-S** [primefaces/primeng#1949]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
DataTable's `reset()` method doesn't clear all filter input fields after it's called. If there's only one filter filled, it will clear it normally, but if there's more than one, data will still be displayed without any filters, but input fields will still have previously inputed values.

**Expected behavior**
`reset()` method should clear all filter input fields.

* **Angular version:** 2.4.5

* **PrimeNG version:** 2.0.0-rc.2

* **Browser:** All
 
* **Language:** All

* **Node (for AoT issues):** `node --version` =  v6.3.0

**Comment by sudheerj** [comment]
This can be replicated with custom filters only.If you use built-in filters then it won't cause this issue.The local component control values also need to be reset.

**Comment by Svrkota-S** [comment]
That is not true, I'm simply using `[filter]="true" filterMatchMode="contains"` on all of my filters, there's no trace of anything custom.

**Comment by sudheerj** [comment]
This is how I tried.

1.Filter on 3 columns without using custom filter feature

![image](https://cloud.githubusercontent.com/assets/3127317/22465082/f86f96be-e7f4-11e6-8fd0-0da53ccbd35e.png)

2. After clicking on reset button all filter inputs got cleared and the table displayed with initial records

![image](https://cloud.githubusercontent.com/assets/3127317/22465140/2b62e0b2-e7f5-11e6-95da-062d15cad6fb.png)

**Comment by bimalpaul** [comment]
+1. Can only be replicated with custom filters. 

1. Apply filters (normal and custom). Works as expected
![image](https://cloud.githubusercontent.com/assets/19557345/25900896/9e7de116-355a-11e7-84e9-2205e0f5b7ad.png)

2. Reset. Table reset with no filters. But the header in the custom filter stays. 
![image](https://cloud.githubusercontent.com/assets/19557345/25900908/a7f6aae8-355a-11e7-867a-8f98b90d4ad2.png)
In this example, I would have expected the Offset filter of 3 to be cleared too. It doesn't make sense for the filter text to not change when the filter was reset. Like it did for Well Name

**Comment by cagataycivici** [comment]
We can't know what are inside custom filters, so you need to clear them manually. Online example has a slider with manual clear.

**Comment by DraghiciR** [comment]
Could you please provide a link to said slider?

**Comment by Mrtcndkn** [comment]
@DraghiciR You can check it from over here:
http://primefaces.org/primeng/#/datatable/filter

**Comment by viniciusalvess** [comment]
I had similar issue with a custom filter with a primeng calendar, where it was only clearing it's filter after I forced called reset on the component using: @ViewChild(DataTable) dataTableComponent: DataTable; to access the datatable component methods, but the problem with this approach was that it resets all the filters. So I solved it by deleting the filter property manually on the onClearClick event of the calendar as follows:
```
onMyCalClearClick(){
    delete this.dataTableComponent.filters.myFilterProp; // work around to clear custom filter
    this.dataTableComponent.onLazyLoad.emit(); // here I force the datatable to refresh, bu maintaining the other filters if it has.
} 
```
