### ISSUE TITLE
SelectButton auto width adjustment

### ISSUE THREAD

**Issue by ekuusi** [primefaces/primeng#1950]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
p-selectButton button widths are dynamic based on the button label length

**Expected behavior**
Be able to manually set p-selectButton width. If done have buttons be of uniform relative width and buttons would not go to multiple rows.

For example if p-selectButton width is set to 400px and has 4 buttons, each button would be 100px (25%) wide.

**What is the motivation / use case for changing the behavior?**
p-selectButton would be much more usable as an UI element if the user had at least this amount of control on the size.

* **PrimeNG version:** 2.0.0-rc2

**Comment by gasparbarancelli** [comment]
@ekuusi 
You can set a styleClass in the options, so each button can have its class, I believe the current form is the most correct to solve your problem.

**Comment by yigitfindikli** [comment]
We'll reconsider if there is more community feedback on this. Thank you for your report.
