### ISSUE TITLE
DataTable doesn't scroll with ScrollHeight=100% or to large fixed values

### ISSUE THREAD

**Issue by csharpparadise** [primefaces/primeng#1952]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/mpWYMp [code in index.html]

**Current behavior**
The scroll bar in the pDataTable Component doesn't work with scrollHeight=100% or fixed values, that are so large, that the content can fit in it. 

**Minimal reproduction of the problem with instructions**
See Plunkr.

**What is the motivation / use case for changing the behavior?**
This is probalbly a simple bug in the data table component and should be fixed.

**Please tell us about your environment:**
Chrome, Angular 2, Windows 10

* **Angular version:** 2.0.2

* **PrimeNG version:** 2.0.0 RC2
In version 1.0.0, the scrolling works as expected.

* **Browser:** 
Tested in Chrome 55, MS Edge, IE11
 
* **Language:** 
ES5

**Comment by cagataycivici** [comment]
Dup of https://github.com/primefaces/primeng/issues/1905
