### ISSUE TITLE
dataTable: Horizontal scroll bar is not shown, and text is truncated.

### ISSUE THREAD

**Issue by danny-swimmer** [primefaces/primeng#1953]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/sKIbw9hfpkYhy9U9lhfN

**Current behavior**
I've configured my p-dataTable for Vertical and Horizontal scrolling. However when one of the columns in the p-dataTable has a long text string, the horizontal scroll bar is not shown, and text is truncated.

**Expected behavior**
Horizontal scroll bar should be shown and be usable.

**Minimal reproduction of the problem with instructions**
Please see http://plnkr.co/edit/sKIbw9hfpkYhy9U9lhfN

**What is the motivation / use case for changing the behavior?**
To be able to read all of the text.

**Please tell us about your environment:**
Server OS: Ubuntu linux 14.04
Package Mgr: webpack
Browser OS: Windows 7
Browser: Chrome

* **Angular version:** 2.0.X
2.4.4

* **PrimeNG version:** 2.0.X
2.0.0-rc.1

Browser: Chrome

**Comment by ctrl-brk** [comment]
Try to give [style]="{'overflow': 'inherit'}" to this column

**Comment by danny-swimmer** [comment]
Thanks @ctrl-brk. Adding either [style]="{'overflow': 'visible'} or [style]="{'overflow': 'inherit'}" to this column turns on the horizontal scrolling.

I now see that this topic is covered in the documentation at http://www.primefaces.org/primeng/#/datatable, however it's hidden very well at the bottom of a long page, under "Overlays in Cells". It probably should be given its own link at the top of the page, like all of the other topics.

I'm closing this ticket.

**Comment by pantonis** [comment]
@danny-swimmer  Did you manage to make it work?

**Comment by danny-swimmer** [comment]
Hi @pantonis,
Yes. As I noted in my comment from Jan 30, I added [style]="{'overflow': 'visible'}" to the p-column. This fixed the problem.

**Comment by pantonis** [comment]
@danny-swimmer I have ```[scrollable]="true" scrollWidth="90%"```` but I dont see horizontal scrollbar..

**Comment by pantonis** [comment]
@danny-swimmer Can you poat some code please?

**Comment by danny-swimmer** [comment]
@pantonis - Please refer to the plunk at [](https://plnkr.co/edit/jBMtwmBfZSvXYOZV5XSb)
The crucial change is the addition of [style]="{'overflow': 'visible'}" at line 14 of app.template.html. Without this addition, the horizontal scroll bar is not displayed.

**Comment by pantonis** [comment]
@danny-swimmer That code does not work.

**Comment by danny-swimmer** [comment]
@pantonis - Please be more specific. The plunk at https://plnkr.co/edit/jBMtwmBfZSvXYOZV5XSb works for me.

**Comment by pantonis** [comment]
```
![image](https://user-images.githubusercontent.com/3295086/34112528-811095b4-e415-11e7-92b4-dec0f83c1529.png)

```

**Comment by pantonis** [comment]
![image](https://user-images.githubusercontent.com/3295086/34112559-9a4219ae-e415-11e7-986d-ac58654ec7bd.png)

**Comment by ugald80** [comment]
Hey friends, i found the origin of this problem
the header-box of the component has the sum of widths of all th headers cells. then the table width always get the sum of all columns widths and never will show the scroll.
**I override the 'ui-table-scrollable-body' class css, setting a 100px width**. with percentage widths this does not work, this only works with fixed values (px, em, pc, etc).
