### ISSUE TITLE
[feature request] configurable id for input inside primeng components

### ISSUE THREAD

**Issue by tykayn** [primefaces/primeng#1957]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```
**Minimal reproduction of the problem with instructions**
acessibility is lacking for the autocomplete component, we cannot define an id corresponding to a label.

**What is the motivation / use case for changing the behavior?**
for basic acessibility.

**Please tell us about your environment:**
webstorm, ubuntu 16.04

* **Angular version:** 2.1.0
* **PrimeNG version:** 1.1.4

* **Browser:**all
* **Language:** all

**Comment by jacalgit** [comment]
+1

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
