### ISSUE TITLE
The arrow from the AutoComplete component does not work in Safari

### ISSUE THREAD

**Issue by alarive** [primefaces/primeng#1960]
For example, in the showcase ( http://www.primefaces.org/primeng/#/autocomplete ) , clicking on the arrow of the "Advanced" AutoComplete example does not display the suggestion panel in Safari.

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
