### ISSUE TITLE
2 rows header - Text aligned to top even if it is not broken into 2 lines

### ISSUE THREAD

**Issue by yuvalbl** [primefaces/primeng#1961]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/NtWWnN

**Current behavior**

When header text is very close to header boundries (e.g. space inside the the minus padding) 
It aligned to top instead of being splint into 2 rows

**Expected behavior**

Text should be aligned to top only if it breaks into 2 line

**Minimal reproduction of the problem with instructions**
Steps to reconstruct (see attachment):
1. Create a table with headers which some of them are of 2 rows
2. Put some text in the header
3. minimize the screen width to the text breaking point (when it should break into 2 lines)
Just before the breaking point text is aligned to top 
NOTE: the screen resize is just for this reproduction demo - 
It first occur to me when I happens to have a column it this state (e.g. text was close to the boundaries)

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Linux(Ubuntu) ,webstorm, angular-cli (uses webpack + npm)

* **Angular version:** 2.0.X

2

* **PrimeNG version:** 2.0.X

2.0.0-rc2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

chrome 56 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript

* **Node (for AoT issues):** `node --version` =   6.9.4
![primeng_2rows_headers](https://cloud.githubusercontent.com/assets/11487010/22474013/5ce28e60-e7e3-11e6-8420-c9b632fd4002.jpg)

**Comment by yuvalbl** [comment]
Hey guys, 
did you manage to reconstruct it, or do you need more info for this issue?

**Comment by cagataycivici** [comment]
You can just remove white-space:nowrap from the column via style or styleClass property.
