### ISSUE TITLE
MultiSelect value support objects

### ISSUE THREAD

**Issue by EgyTechnology** [primefaces/primeng#1962]
Hello everyone,
I was thinking to share the idea of feature, in case if it's not in the plan.
So I'd like to suggest that MultiSelect support for dealing with objects, I noticed that it is not have support for dealing with objects unlike Dropdown.

I was using version 2.0.0-rc.2 of PrimeNg.

**Comment by stephanecot** [comment]
In the source code of multiselect component, there is the method:
` 
findLabelByValue(val: any): string {
let label = null;
        for(let i = 0; i < this.options.length; i++) {
            let option = this.options[i];
            if(option.value == val) {
                label = option.label;
                break; 
            }
        }
        return label;
    }
`

I think there is a problem with the line **option.value == val**
How can it work with object? We need to compare with a property of the object (there is no equals mehtod in javascript like in java.. :( )

**Comment by TakanashiOuken** [comment]
Having the same issue here
If the value is a object it will simple return null

**Comment by gsbybb** [comment]
I have the same issue...
