### ISSUE TITLE
Grid offset classes

### ISSUE THREAD

**Issue by corydorning** [primefaces/primeng#1973]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
The grid system allows you to position elements on a page but only directly next to each other. Would be nice if you could offset elements so they don't sit right next to each other. the only way this can be done now is to create an empty element with a grid class.

Something like this:
```
<div class="ui-g">
  <div class="ui-g-6">...content...</div>
  <div class="ui-g-3 ui-g-offset-3">content w/ 3 grid columns of space to the left</div>
</div>
```

Instead of having to do this:
```
<div class="ui-g">
  <div class="ui-g-6">...content...</div>
  <div class="ui-g-3"></div>
  <div class="ui-g-3">content w/ 3 grid columns of space to the left</div>
</div>
```

**What is the motivation / use case for changing the behavior?**
fewer unneeded dom elements

**Comment by waldo2188** [comment]
Hi, I was facing the same issue.
I've submit a PR, so if you have time, you can check if this resolve your problem ?

**Comment by cagataycivici** [comment]
Will be ready in 4.1.1

**Comment by smitpsanghavi** [comment]
Is this still going to be done?
We want to use the all of Grid CSS but we have to mix it with bootstrap Grid CSS because of missing offset classes. It's a mess.

**Comment by smitpsanghavi** [comment]
@corydorning This can be closed since it is available since v7

**Comment by yigitfindikli** [comment]
You can check it out PrimeFlex.
