### ISSUE TITLE
Add options property to Schedule

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#1976]
To support fullcalendar features that do not have a corresponding property in Schedule.

**Comment by ElMohMoh** [comment]
Hi thank you for this.

I need to use the feature Get / Set Options Dynamically (https://fullcalendar.io/docs/utilities/dynamic_options/)

How can I the options property to call this feature?

Thank you for your help.

**Comment by victorcg88** [comment]
Hey @ElMohMoh did you find any example of how to use it? I will apreciate a code example, thanks.

**Comment by cagataycivici** [comment]
@Mrtcndkn Please provide an example here.

**Comment by Mrtcndkn** [comment]
Let's assume we are working inside of calendardemo.ts in PrimeNG showcase.

We have a testDate variable for binding.

    testDate: Date;

    let newTestDate = new Date();

    this.testDate = newTestDate;

    this.testDate.setDate(22);

    console.log(this.testDate.getDate());

For the HTML part

     <p-calendar [(ngModel)]="testDate" tabindex="0"></p-calendar>

We have a two-way binding for our testDate variable.

@ElMohMoh @victorcg88

**Comment by cagataycivici** [comment]
I guess they need an example of using options property with p-schedule which allows access to fullcalendar.

**Comment by Mrtcndkn** [comment]
First you need to bind [options]="optionConfig" configuration to your schedule like this
`
<p-schedule [events]="events" [header]="header" [options]="optionConfig" defaultDate="2017-02-01" [eventLimit]="4" [editable]="true"
                (onDayClick)="handleDayClick($event)" (onEventClick)="handleEventClick($event)"></p-schedule>
`

optionConfig is a variable for the necessary configurations.
`optionConfig: any;`

Inside ngOnInit function:
`ngOnInit() {
        this.optionConfig = {
            isRTL: true
        };
    }`

You can use options property like this.
