### ISSUE TITLE
 can't to add filter for columns in p-headerColumnGroup tag

### ISSUE THREAD

**Issue by yuvalbl** [primefaces/primeng#1979]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/NtWWnN
Would if I could, seems like systemJS can't import your pkg from unpkg.com

**Current behavior**

I've ask a [question on stackoverflow](http://stackoverflow.com/questions/42001031/primeng-with-angular2-how-to-add-filter-for-columns-in-p-headercolumngroup-tag) in regards to this matter

Filter is not working in this simple template:
```
 <p-dataTable [value]="characters">
    <p-headerColumnGroup>
      <p-row>
        <p-column header="Id" [filter]="true">ID</p-column>
      </p-row>
    </p-headerColumnGroup>
    <p-column field="id" header="Id" ></p-column>
  </p-dataTable>

```
**Expected behavior**

Filter should work as without using p-headerColumnGroup

**Minimal reproduction of the problem with instructions**

Simply copy the template and add some data to it

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.3.1

* **PrimeNG version:** 2.0.0-rc3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 chrome 56

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

* **Node (for AoT issues):** `node --version` =

**Comment by yuvalbl** [comment]
Hey guys, 
did you manage to reconstruct it, or do you need more info for this issue?

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
