### ISSUE TITLE
icon only toggle button

### ISSUE THREAD

**Issue by ferdibejtullahu** [primefaces/primeng#1980]
when i try to add toggleButton with icon without text, template render normal button not circle wothout text, is it possible to add this functionality in the togglebutton.ts in the row 14.
instead of  'ui-button-text-icon-left': (onIcon&&offIcon), to be 'ui-button-text-icon-left': (onIcon&&offIcon&&onLabel&&offLbel),'ui-button-icon-only':(onIcon&&offIcon&&!onLabel&&!offLbel)

**Comment by sudheerj** [comment]
You are right. It will center align the button when there is no text.
