### ISSUE TITLE
[Question] How to locally deploy changes to repo using npm?

### ISSUE THREAD

**Issue by kambojankit** [primefaces/primeng#1981]
I have forked the repo, added some features to the autocomplete module, and now want to include them into my other project. 

I tried to do prod build build not able to use it as a dependency in my project. 

Can someone please suggest the correct way. (already tried to reach through forum, in vain.)

**Comment by gmarziou** [comment]
Have you run `npm link` in your cloned primeng?

**Comment by kambojankit** [comment]
@gmarziou thanks for the prompt response, but linking doesn't seem to solve the issue. 
Here is what i did:
- Forked repo
- did required changes
- npm install
- gulp build
- npm start

Tested things work as expected in showcase, then used your suggestion and did as below:
- npm link
- npm link primeng (in application)

This doesn't seem to solve it. here is snapshot of the error
[error-message](https://drive.google.com/drive/folders/0B_SX_7LNuPu7cDk4WXRvMGZIWEk?usp=sharing)

**Comment by kambojankit** [comment]
@Mrtcndkn @cagataycivici hey guys can you please help, i need inputs to build the project in a way similar to the one i get with npm install.

**Comment by kambojankit** [comment]
Hey, it was my mistake, have been able to get it working now. 

It was to do with, the packaging of CSS in application.

**Comment by olingerc** [comment]
@kambojankit could you please post the exact steps you followed to build and install your fork?

**Comment by yelhouti** [comment]
@kambojankit could you do that please?
