### ISSUE TITLE
Quick growl stays (sticky)

### ISSUE THREAD

**Issue by FallenRiteMonk** [primefaces/primeng#1983]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

**Current behavior**
If a growl message is shown right after app initialization the message stays as if Growl sticky was set to true even if it is not.

**Expected behavior**
The Growl message should vanish after its ```[life]``` time (default 3000) has run by.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/X85etYKNqdVIqXabjeuA

Running this plunker immediately shows a growl messages which stays.
Clicking the button ```Show second``` shows a second message, upon which then the first also vanishes once 3sec have passed

* **Angular version:** 2.0.X
2.4.5

* **PrimeNG version:** 2.0.X
1.1.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Reproducible on latest of using the above plunkr: chrome, firefox, opera, edge, internet explorer
 
* **Language:** 
TypeScript 2.0.10

* **Node (for AoT issues):** `node --version` =
v6.9.3

**Additional info**
wrapping the messageList.push into a timeout, solves the problem:
```
setTimeout(() => {
  this.messageList.push({ severity: 'info', summary: 'first', detail: 'stays' });
}, 0);
```

**Comment by RushPVA** [comment]
same here (for both versions - PrimeNG version: 2.X, 4.X, angular version 2.X, 4.X)

**Comment by RushPVA** [comment]
timeout works without animation

**Comment by bsh314** [comment]
Yes, "sticky" disables "life" timeout & keeps growl displayed.
Versions:
 "@angular-mdl/core": "^4.0.1",
 "primeng": "^4.0.0-rc.2",

**Comment by Franky238** [comment]
Same here.

**Comment by sudheerj** [comment]
Please look at this thread for necessary changes(The way messages updated and two-way binding) https://github.com/primefaces/primeng/issues/2634
