### ISSUE TITLE
Chips: onRemove: event.value is not string

### ISSUE THREAD

**Issue by lebnic** [primefaces/primeng#1984]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/NtWWnN
Plunkr not possible since missing chips module

**Current behavior**
Output "onRemove" emits event, where "$event.value" is an array. I was expecting a string... Indeed, Output "onAdd" emits event, where "$event.value" is a string, which does make sense. Hence, this seems like a lack of consistency. Furthermore, in code:
       `this.onRemove.emit({
            originalEvent: event,
            value: removedItem
        });`
which seems to imply value: removed item is a single item, not an array...

**Expected behavior**

event.value should be a string for onRemove (like it is for "onAdd")

**Minimal reproduction of the problem with instructions**

    `<p-chips (onAdd)="myFctn($event.value)" (onRemove)="myFctn($event.value)"></p-chips>`
`
  myFctn(e) {
    console.log(e);
  }
`
Inspect console output, add an element to chips: you'll see event.value is a string.
Then, remove an element from chips: you'll see event.value.value is an array of strings (with a single string, of course, the only chip that was removed...)

**What is the motivation / use case for changing the behavior?**

Chips needs to be consistent for onAdd and onRemove.

**Please tell us about your environment:**

* **Angular version:** 2.0.X

$ npm angular -v
3.10.10

* **PrimeNG version:** 2.0.X

    "primeng": "1.1.3"

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chromium: Version 55.0.2883.87 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Please provide a plunkr, can't replicateThis should be fixed in recent PrimeNG release, please try with them and if issue persists drop a comment and we'll reopen.
