### ISSUE TITLE
Chips: can't highlight label with mouse

### ISSUE THREAD

**Issue by lebnic** [primefaces/primeng#1985]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/NtWWnN
Chips not available...

**Current behavior**

After highlighting with mouse, releasing left-click button will remove label highlight...

I've found a workaround: click and hold mouse's left button; drag over chip label (dont release!); hit "ctrl + c". This work, over, average user don't want to do that...

**Expected behavior**

As Button is highlightable, thus after highlighting with mouse and release left-click button, chip label should remain highlighted...

**Minimal reproduction of the problem with instructions**

Make sure chips is already containing a few chips.
Drag cursor over chip label's first char, press and hold left-click button.
Drag cursor till chip'l label last char (don't let go of left-click button). Chip label should be highlighted, this is good.
Let go of left-click button. Observe chip label is no longer highlighted. This is a bug. Chip label should remain highlighted after releasing left-click...

**What is the motivation / use case for changing the behavior?**

User experience is bad because it is not easy to "copy-past" chip labels.

**Please tell us about your environment:**

* **Angular version:** 2.0.X

3.10.10

* **PrimeNG version:** 2.0.X

1.1.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chromium
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
