### ISSUE TITLE
Pass the column information to onRowClick

### ISSUE THREAD

**Issue by pranz123** [primefaces/primeng#1986]
Is it possible to identify column on click event over the particular column in datatables?

**Comment by cagataycivici** [comment]
There is onRowClick, you can get the event.target, find the td element and get the index which is way too hard, I think we should pass the column to the onRowClick, much easier.

**Comment by cagataycivici** [comment]
This requires core changes on our side and a bit of performance hit so we've postponed it until more users demand it.
