### ISSUE TITLE
Bug with Editable on P-datatable

### ISSUE THREAD

**Issue by lsoaresesilva** [primefaces/primeng#1988]
**I'm submitting a ...**  (check one with "x")
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Current behavior**
Using a p-datatable with editable true. If I double click in cell, the input edit appears and I can edit the value and after pressing enter the value is edited, as expected. However if I try to edit it again (doubling clicking) the input edit does not show. To get this work, I have to click in another cell, within editable property, and after double click again in the cell I wanted to edit. 

**Expected behavior**
Click in the cell, edit should appear. 

**Minimal reproduction of the problem with instructions**
Edit a cell with editable true, finish edition and try to edit it again. Input will not shown again. This problem also appears on editable examples from PrimeNG site.

**What is the motivation / use case for changing the behavior?**
It is a bug.

**Please tell us about your environment:**
MACOSX, tried with Chrome v55 and Safari.

* **Angular version:** 2.0.X
Angular 2.4.5

* **PrimeNG version:** 2.0.X
2.0.0rc2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome v55 and Safari.
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript
* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
