### ISSUE TITLE
Unitless Dialog Width-Height

### ISSUE THREAD

**Issue by geogauci** [primefaces/primeng#1990]
**I'm submitting a ...**
```
[x ] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case**
http://plnkr.co/edit/JVIeFK

**Current behavior**
The dialog width is set to 300px, even if the width is set to auto. Also, not responsive.

**Expected behavior**
The dialog should by default take the width of the window, as per [issue 1262](https://github.com/primefaces/primeng/issues/1262). However, an auto width does not work at all. 
**My aim is to set the dialog width to 90% of the screen.**

* **Angular version:** 2.4.6
* **PrimeNG version:** 2.0.0-rc3
* **Browser:** [all]

**Comment by gregorfelkar** [comment]
+1

I have similar issue, aiming to 80% window width. It would be very nice to have percent option on width attribute.

**Comment by bakasmarius** [comment]
This would really help to fight the bug when the Dialog does not centralize after dynamic content is added.

**Comment by stannynuytkens** [comment]
Must have!

**Comment by blhussey** [comment]
Much needed feature.

**Comment by mlakhara** [comment]
@blhussey @bakasmarius This was taken in v 4.1.1. Can you please update and verify ?

**Comment by blhussey** [comment]
Angular: 4.3.4
PrimeNG: 4.1.3
Dynamic content is causing the issue. I forced the width on the content and the centering worked fine.

**Comment by bakasmarius** [comment]
Angular: 4.4.0-RC.0
PrimeNG: 4.2.0-rc.1
I just tested it and setting width in html does nothing at all, no matter if it is in pixels or percents.
However, adding CSS to .ui-dialog { } and using width in it works for pixels and percents.

**Comment by ericsvendsen** [comment]
For now I used the `::ng-deep` combinator to set a width on the dialog:
```
::ng-deep .ui-dialog {
    width: 90% !important;
}
```
Seems fine for now, but just remember that [ng-deep will change eventually](https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep). Therefore it would be nice to have a built-in solution for this.

**Comment by dhniels** [comment]
percentage support would be nice since the responsive property added at https://github.com/primefaces/primeng/issues/2795 doesnt work properly with dynamic content.

**Comment by lasimone** [comment]
+1

**Comment by ARandomDude** [comment]
Please add this much-needed functionality. The workaround by @ericsvendsen does not seem to work for "dialogues in dialogues", meaning it does not work when a dialog has "appendTo='body'", and is probably not a lasting solution.

**Comment by sourabh8003** [comment]
@ARandomDude: It'll work just keep that piece of css code at you top level component's scss/css file.

**Comment by nanoTitan** [comment]
+1 on this. A percentage width is a must. The ng-deep solution could stop working in the future due to new version updates.

**Comment by mahald** [comment]
also would need this, would be pretty nice

**Comment by mahald** [comment]
+1

**Comment by alesbrelih** [comment]
+1

**Comment by cagataycivici** [comment]
We also need to support vw vh and any other units so it should be unitless.

**Comment by cagataycivici** [comment]
width, height, minWidth and minHeight are deprecated, suggested way is using the style prop with the unit you prefer;

```
<p-dialog [style]="{width: '50vw'}"
```
