### ISSUE TITLE
[FEATURE] Set p-tooltip per p-dataTable row

### ISSUE THREAD

**Issue by bojanidis10** [primefaces/primeng#1991]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Impossible to set a p-tooltip per p-dataTable row

**Expected behavior**
p-dataTable will have an ability to display p-tooltip on per row basis.

**What is the motivation / use case for changing the behavior?**
Provide additional information to end user ("invalid data", ...)

**Please tell us about your environment:**

* **Angular version:** 2.4.4

* **PrimeNG version:** 2.0.0-rc2

**Comment by Mrtcndkn** [comment]
Actually it's not impossible you can create your rows with templates and later you can set tooltips for that templates.

**Comment by bojanidis10** [comment]
Template can be put only inside a column. I need to put a tooltip on a row. That would work only if I create a single column with a template. Inside this column I would then create my cells. 
```
<p-column>
    <template pTemplate="header">
         <div class="row">
              <div>Col 1</div>
              <div>Col 2</div>
          </div>
    </template>
    <template let-car="rowData" pTemplate="body">
        <div class="row" pTooltip="Some text">
              <div>{{row.vin}}</div>
              <div>{{row.year}}</div>
         </div>
    </template>
</p-column>
```
If I go this way I lose the ability to many other features that grid has to offer - editing, sorting, column resizing, column filtering,...
I think this would be a hack, not a solution. And I would not want to lose all of these mentioned possibilities over a tooltip feature. 

If I am missing something please explain it to me, as I would like to learn how this can be done without such hack.

**Comment by unaor** [comment]
no news on this?

**Comment by cagataycivici** [comment]
Tooltip requires a host, tr is not a host, you need a custom impl for this on your side. The request is too custom for us to implement.
