### ISSUE TITLE
[feature request] DataTable custom style for TR

### ISSUE THREAD

**Issue by gatapia** [primefaces/primeng#1996]
Similar to existing [rowStyleClass] please add [rowStyle] to support custom styles for TRs.  Setting say the background colour for a row based on database data is very hard without support for custom styles.

**Comment by cagataycivici** [comment]
More bindings cause performance issues, since rowStyleClass do the job, we don't need rowStyle for this reason.

**Comment by rbj325** [comment]
rowStyleClass does not do the job.

If we allow our user to select a custom color, do you suggest we have a CSS class for every HEX/RGB color?
