### ISSUE TITLE
Custom content for menubar

### ISSUE THREAD

**Issue by sudheerj** [primefaces/primeng#1997]
The custom options for menubar or megamenu is quite useful to place additional information.The general use case is having some form components and login details as extra information to optimally use the view.It is provided in PrimeFaces as options facet too.

**Comment by cagataycivici** [comment]
@Mrtcdkn Use ng-content to place whatever inside menubar and megamenu as options.

**Comment by Mrtcndkn** [comment]
https://github.com/primefaces/primeng/issues/3153
