### ISSUE TITLE
Primeng installed in CLI stopped working

### ISSUE THREAD

**Issue by ceejay15** [primefaces/primeng#1998]
Hi, I am recently using angular2 with primeng and it is working fine then. When we move to angular-cli primeng stopped working fine. It displays data and renders table. But I am not able to sort, paginate, filter, do a global search, exporting to csv and everything that is working before.  

I noticed that it only happens whenever I route from one component to another that uses it. Is there any way on how do we make it work like before?  

Any help, insight greatly appreciated. 

Thanks

**Comment by cagataycivici** [comment]
Please use forum for cases like these.
