### ISSUE TITLE
Some attributes for Dialog component do not work.

### ISSUE THREAD

**Issue by omerfarukyilmaz** [primefaces/primeng#200]
While I can use `(maximizable)="false"`
other attributes such as:
`(draggable)="false"` or `(resizable)="false"`
take no effect whatsoever.

`(width)="auto"` does not work as well but writing
`width="auto"` works. Am I doing something wrong?

**Comment by cagataycivici** [comment]
You need to use the [] syntax not ()

**Comment by omerfarukyilmaz** [comment]
Well, my apologies about the other ones but I still could not get 
`[location]="left top"`
`[location]="50,150"`
`[location]="bottom"`
or any other variants working.
