### ISSUE TITLE
Visible property to calendar

### ISSUE THREAD

**Issue by chrillewoodz** [primefaces/primeng#2001]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Expected behavior**
Provide an input/method for closing the calendar upon selecting a date.

**What is the motivation / use case for changing the behavior?**
Especially on mobile devices it's horrible UX since the datepicker takes up so much space on the screen. It's hard to close it manually.

**Comment by upmauro** [comment]
Now the calendar close after the date is selected. I tried and worked here.

Look https://github.com/primefaces/primeng/blob/master/components/calendar/calendar.ts#L463
and https://github.com/primefaces/primeng/blob/master/components/calendar/calendar.ts#L816 and https://github.com/primefaces/primeng/blob/master/components/calendar/calendar.ts#L1163

**Comment by VictorDeBlas** [comment]
And if I want to close the calendar manually? For example, when a resize event succeed.

Thanks.

**Comment by alejandrohn** [comment]
How close the calendar manually? When calendar is inside a pop up not close when a date is selected?

**Comment by cagataycivici** [comment]
We can expose overlayVisible

**Comment by timvl** [comment]
You can create a viewchild and set the 'overlayVisible' property manually: 

In your template add a template reference variable:
```
<p-calendar #myCalendar ... 
```
In your controller access the overlayVisible property:
```
@ViewChild('myCalendar') datePicker;

hideDatePicker(){
    this.datePicker.overlayVisible = false;
}
```

**Comment by zbabos** [comment]
You can close the popup datepicker by simulation of Escape keypress.
Example if user press the Enter key, the popup will close (and dateSelect ajax event will fire):

<p:calendar ... onkeyup="if(event.keyCode==13){keydownevent(this,'Escape',27);}else{return false;}">
  <p:ajax event="dateSelect" listener="#{mybean.onDateSelect}" update="@(.myclass)" />
  <p:ajax event="keyup" listener="#{mybean.onDateSelect}" update="@(.myclass)" />
  <p:ajax event="blur"  listener="#{mybean.onDateSelect}" update="@(.myclass)" />
</p:calendar>

(...but also ajax event will fire if popup is already closed and user press the Enter key or user leaves the p:calendar)

function keydownevent(d,k,c) {
              var e;
              if(typeof(Event) === 'function') {
                // Mozilla, Chrome  
                e = new Event('keydown');
              }else{
                // IE  (IE11)
                e = document.createEvent('Event');
                e.initEvent('keydown', true, true);
              }
              e.key=k;    
              e.keyCode=c;
              e.which=e.keyCode;
              e.altKey=false;
              e.ctrlKey=false;
              e.shiftKey=false;
              e.metaKey=false;
              e.bubbles=true;
              d.dispatchEvent(e);
}

**Comment by SSTPIERRE2** [comment]
Did this used to work or was it just not tested with `selectionMode="range"`? There is a bug where if you use this property to "programmatically hide" the calendar, the overlay stays open and you can't click anything on the page (due to its z-index). See my stackblitz demo: https://vbwilqlo.github.stackblitz.io I will open an issue...

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
