### ISSUE TITLE
p-menubar is not responsive

### ISSUE THREAD

**Issue by abishek** [primefaces/primeng#2005]
p-menubar component is not responsive in that it doesn't collapse when the screen size is minimized. Is it possible to do this with styleClasses? Can someone provide an example? 

PS: I tried posting the same in the forum but got no response. So I am posting as an issue to see if someone will respond here.

Thank You!

**Comment by abishek** [comment]
can I get any help on this? I am unable to proceed with the framework for this one reason! I need the menu to be responsive. 

at least let me know if it won't be fixed. i'll at least spend the effort writing my own menubar variant!

**Comment by sudheerj** [comment]
I can't replicate the issue.Can you please replicate the issue in showcase.

**Comment by sudheerj** [comment]
The menubar is responsive as attached in snapshot
![image](https://cloud.githubusercontent.com/assets/3127317/26035066/0858d31a-38f9-11e7-8dd5-35c690053403.png)

**Comment by DmitryEfimenko** [comment]
This is pretty bad responsive behavior. I would not even consider this responsive. The expected behavior should be a standard hamburger menu.

This issue should be reopened.

**Comment by atheodosiou** [comment]
I have the same issue! There is no responsiveness at all! Reopen the issue please!
