### ISSUE TITLE
BUG- "Can't bind to 'model' since it isn't a known property of 'p-contextMenu'."

### ISSUE THREAD

**Issue by eliavmaman** [primefaces/primeng#2006]
Hey , i'm new to angular2, and i'm trying to use Primeng ContextMenu.
i did the follow Based on the docs :
1.```import {ContextMenuModule,MenuItem} from 'primeng/primeng';```
2.```<p-contextMenu #cm [model]="items"></p-contextMenu>```
3.I added in the component.ts
```
private items: MenuItem[];

    ngOnInit() {
        this.items = [
            {
                label: 'File',
                items: [{
                        label: 'New', 
                        icon: 'fa-plus',
                        items: [
                            {label: 'Project'},
                            {label: 'Other'},
                        ]
                    },
                    {label: 'Open'},
                    {label: 'Quit'}
                ]
            },
            {
                label: 'Edit',
                icon: 'fa-edit',
                items: [
                    {label: 'Undo', icon: 'fa-mail-forward'},
                    {label: 'Redo', icon: 'fa-mail-reply'}
                ]
            }
        ];
    }
```

I've also saw that the source has no binding to "[model]" property.

```
 template: "\n <div #container **[ngClass]**=\"'ui-contextmenu ui-menu ui-widget ui-widget-content ui-corner-all ui-helper-clearfix ui-menu-dynamic ui-shadow'\" \n **[class]**=\"styleClass\" **[ngStyle]**=\"style\" **[style.display]**=\"visible ? 'block' : 'none'\">\n<p-contextMenuSub [item]=\"model\" root=\"root\"></p-contextMenuSub>\n        </div>\n    ",
```

**Comment by eliavmaman** [comment]
any idea?

**Comment by Mrtcndkn** [comment]
Where did you import the component? @eliavmaman

**Comment by eliavmaman** [comment]
hey @Mrtcndkn ,
I've imported the component in both ```app.module.ts``` and in my ```xxx.component.ts```
did i do something wrong?

**Comment by eliavmaman** [comment]
?

**Comment by stevegraygh** [comment]
@eliavmaman I got this message when I added an import but forgot to add the module to the imports array

**Comment by stevegraygh** [comment]
to illustrate with a simple eg

bad:

import { ContextMenuModule, ContextMenu, MenuItem } from 'primeng/primeng';

@NgModule({
    imports: [
        MenuModule

good:

import { ContextMenuModule, ContextMenu, MenuItem } from 'primeng/primeng';

@NgModule({
    imports: [
        ContextMenuModule, MenuModule

**Comment by Mrtcndkn** [comment]
Hi,
You need to import these modules from app.modules.ts

**Comment by stevegraygh** [comment]
yeah I had a similar problem today but I worked it out so I was just letting eliavmaman know how to fix it if he made the same mistake

I have the imports in app.module.ts and mymodule.module.ts

**Comment by sudheerj** [comment]
This is not a bug. Please use forum for any questions.
