### ISSUE TITLE
Calendar week days are never updated so no localization possible

### ISSUE THREAD

**Issue by chpasha** [primefaces/primeng#2008]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

the weekdays array is populated in ngOnInit and never updated again, so trying to change values bound to locale will do nothing. 
**Expected behavior**

weekdays should be updated as soon as an object bound to locale property changes

**Minimal reproduction of the problem with instructions**

just update locale.dayNamesMin after the widget was already initialized. the calendar will show the old values. 

**What is the motivation / use case for changing the behavior?**

i18n for calendar is not complete

**Please tell us about your environment:**

ubuntu, jetbrains idea, npm

* **Angular version:** 2.0.X

2.2.4

* **PrimeNG version:** 2.0.X

1.1.4

**Comment by kryzys69** [comment]
I've made PR long time ago (#1196), but it was not merged. Don't know why. It allows "dynamic" localization.

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview

Issue was: https://github.com/primefaces/primeng/issues/2361

**Comment by gepird** [comment]
Hello.
I got the same problem as described here. Plunkr: https://plnkr.co/edit/APNi47nuDMHYN3zmTxWD?p=preview

**Comment by Ankitacse** [comment]
how can we use multiple values in locale of prime ng calendar ,if we try to do so can we able to make week day also change/
