### ISSUE TITLE
Move templates into dedicated file to ease component inheritance and customization

### ISSUE THREAD

**Issue by remmeier** [primefaces/primeng#2009]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Components define the entire HTML code inline with @Component({template: ... }). This makes it harder to extend an customize a component. HTML code should be put into a separate file. For information about component inheritance is available in https://scotch.io/tutorials/component-inheritance-in-angular-2.

**Comment by cagataycivici** [comment]
It is a huge task and if there is more demand, we can do it. Due to personal preferences they are inline.
