### ISSUE TITLE
a lot of warnings with webpack

### ISSUE THREAD

**Issue by MurhafSousli** [primefaces/primeng#201]
Hi, I'm using this PrimeNG with angular2-webpack-starter, it's working just fine, but I'm wondering why am I getting **75** warnings? and how can fix them.

Exceptions:
```
./~/primeng/primeng.js
Cannot find source file 'primeng.ts': Error: Cannot resolve 'file' or 'directory' ./primeng.ts in C:\Users\Murhaf\Documents\GitHub\angula2-drupal\node_modules\primeng
./~/primeng/components/api/lazyload.js
Cannot find source file 'lazyload.ts': Error: Cannot resolve 'file' or 'directory' ./lazyload.ts in C:\Users\Murhaf\Documents\GitHub\angula2-drupal\node_modules\primeng\components\api
./~/primeng/components/api/message.js
Cannot find source file 'message.ts': Error: Cannot resolve 'file' or 'directory' ./message.ts in C:\Users\Murhaf\Documents\GitHub\angula2-drupal\node_modules\primeng\components\api
.
.
.
```

Thank you.

**Comment by cagataycivici** [comment]
It would be better to ask this as angular2-webpack-starter project tracker. We don't ship ts files by the way.

**Comment by gdi2290** [comment]
the problem is due to the source maps. I created a branch for primeng
https://github.com/AngularClass/angular2-webpack-starter/tree/primeng

**Comment by akozhemiakin** [comment]
This answer on Stackoverflow helps me to fix it: http://stackoverflow.com/a/36727305/1563543

**Comment by truongnmt** [comment]
how to fix in webpack.dev.js file? Mine run in webpack dev enviroment and I dont know where to fix, here is my webpack.dev.js file:  http://pastie.org/10875854

**Comment by gdi2290** [comment]
can you exclude it `helpers.root('node_modules/primeng'),` from sourcemaps

https://github.com/AngularClass/angular2-webpack-starter/blob/4a07eef656df71c8fc48d125f7b6a670a1e96046/config/webpack.common.js#L120...L124

**Comment by DmitryEfimenko** [comment]
this is not really a solution. I'm using `angular-cli` and getting these warnings. `angular-cli` does not have a way to manipulate with webpack config directly (or I don't know of a way) so that's not an option for me.
Even if it was, it's still a hacky solution. There needs to be a proper fix for it.

**Comment by marcusreese** [comment]
I'm having the same problem as @DmitryEfimenko. Similar thread: https://github.com/primefaces/primeng/issues/732

**Comment by DmitryEfimenko** [comment]
as a matter of fact, our build server treats these warnings as failures and fails the build. So I had to disable running tests during the build meanwhile. Not cool at all!

@cagataycivici any word on this?
