### ISSUE TITLE
Datatable not firing edit events correctly

### ISSUE THREAD

**Issue by cbterceiro** [primefaces/primeng#2013]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/D1AK7i

**Current behavior**
Datatable edit events are not firing correctly. onEditInit is fine, but onEditComplete and onEditCancel only fire when Enter and Esc keys are pressed, respectively.

**Expected behavior**
onEditComplete should fire whenever the input loses focus.

**Minimal reproduction of the problem with instructions**
Setup a datatable with editable fields and listen to the events mentioned before.

**What is the motivation / use case for changing the behavior?**
When a user edits anything on the table and leaves the input, I want to apply my custom logic.

**Please tell us about your environment:**
OS: Windows 10 x64
IDE: Visual Studio Code

* **Angular version:** 2.0.X
2.4.6

* **PrimeNG version:** 2.0.X
2.0.0 final

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Tested on Chrome and Firefox
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.0.10

* **Node (for AoT issues):** `node --version` =  6.9.4

**Comment by cbterceiro** [comment]
May be related with #1988

**Comment by cbterceiro** [comment]
Sorry, did not see #1923 and #1924.

**Comment by mattqs** [comment]
Was this issue resolved? It seems that all mentioned issues are closed, but I still don't get any events whenever input loses focus by clicking outside of the cell in version 4.1.0-rc.3
