### ISSUE TITLE
Schedule does not display end date when creating an event with same Start/End date

### ISSUE THREAD

**Issue by wonbyte** [primefaces/primeng#2015]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
If you create a new calendar event with the Start/End date for the same day, when you select the event the pop up dialogue does not display the end date. Events created over multiple days have the End Date properly display

**Expected behavior**
The End Date should populate in the pop up box for an event that starts and ends the same day.

**Minimal reproduction of the problem with instructions**
go to http://www.primefaces.org/primeng/#/schedule  and create a day with the same Start/End date. i.e. 
Start : 2017-02-10
End: 2017-02-10

Save the event and then click on it to open up the dialogue. The end date will not populate.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows 7, Mac

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome(latest), Safari (latest)
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
This is handled by fullcalendar, it always ignores provided end date and sets it as null internally. I think if times are included then it will display fine.
