### ISSUE TITLE
Schedule does not show date over the full Start/End range

### ISSUE THREAD

**Issue by wonbyte** [primefaces/primeng#2016]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
After creating a new event, the event always displays one less than the end date.

**Expected behavior**
The event should display across the Start/End date.

**Minimal reproduction of the problem with instructions**
go to http://www.primefaces.org/primeng/#/schedule and create an event Start: 2017-02-14 End: 2017-02-17

The event will only cover 2017-02-14 to 2017-02-16. 

It should cover up to 2017-02-17

**Please tell us about your environment:**
Windows 7, Mac

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Safari (latest), Chrome(latest)
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
As far as I know this is by design of fullcalendar;

https://github.com/fullcalendar/fullcalendar/issues/2653

**Comment by cagataycivici** [comment]
More information at endDate section;

https://fullcalendar.io/docs1/event_data/Event_Object/

**Comment by doncatnip** [comment]
These docs say: "For example, if the last full day of an event is Thursday, the exclusive end of the event will be 00:00:00 on Friday! "
Which is not what happens for fullDay background events. The 'exclusive' end of that event displayed is *Thursday*, one day early.
