### ISSUE TITLE
Dragging schedule events moves all events

### ISSUE THREAD

**Issue by wonbyte** [primefaces/primeng#2017]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
Create two events on two different days. Drag one of the newly created events and the other will move too.

**Expected behavior**
when dragging an event only that event should move.

**Minimal reproduction of the problem with instructions**
go to http://www.primefaces.org/primeng/#/schedule and create two events on two different dates. Drag either and both will move
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 7, Mac

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome(latest), Safari (latest)
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by wonbyte** [comment]
@cagataycivici Any updated on this and #2016 #2015 ?

**Comment by wonbyte** [comment]
The issue seems to be here with this id not being updated:  https://github.com/primefaces/primeng/blob/master/showcase/demo/schedule/scheduledemo.ts#L77

removing it seems to resolve this issue.

**Comment by cagataycivici** [comment]
This is a bug of showcase demo not the schedule itself, each newly created event must have a unique id.

**Comment by wonbyte** [comment]
@cagataycivici Do I need to manually manage theses ID's or just make sure that each new Event I create in a component has a unique id?

**Comment by cagataycivici** [comment]
Yes, you need to make sure every event has unique id. This is required by fullcalendar.

**Comment by armdev** [comment]
i have the same problem with 11.0.0 version of primefaces, my id was really unique, but bug disappear then I set unique id as event group id , before that I set group id the same string ("payment" for event group id).
