### ISSUE TITLE
PrimeNG component refactor - remove wrapper div (perfomance)

### ISSUE THREAD

**Issue by eggp** [primefaces/primeng#2021]
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap

Dear All, 

I would like to kindly ask you why don’t you use the DOM element created by component element for wrapper. 
Problems: 
- The component element has no style (for example: display)
- Unnecessary waste of resources (unnecessary DOM element about: 100 panel, 100 unnecessary DOM element)
- the wrapper in components become unnecessary (expect:  fieldset (for example))
- unnecessary style and class binds, because in the Angular the ngStyle and ngClass directives are available. And it is works because there is no unnecessary wrapper. 
- Unfortunately the Angular does not yet support the directive assigned to host element.

As an example I rewrote the Panel component, result: 
- minus 1 div
- minus 2 bind, watcher...
- from outside work:
	- ngStyle
	- ngClass

my modified PrimeNG2 panel code:
https://gist.github.com/eggp3pixel/690eb29ac1671627fa2aac8a398eaef5

Thanks, eggp

**Comment by cagataycivici** [comment]
Although I like the points, we cannot do the change due to backward compatibility.

**Comment by eggp** [comment]
Hello @cagataycivici 

Because you did not deal with this issue, this is the reason why i did not answer.
I would like to ask you which compatibility problems do you have ? 
In my opinion it can cause problem only on theme and css level but i think simplier components can not cause problems (in the worst case css selectors change in scss files)

I use the PrimeNG in the bigger projects where there are lot of component on the browser and I think with the solution we can decrease the DOM dramatically.

If you think so I refactor to simple components code.
