### ISSUE TITLE
p-multiselect don't work properly as filter in dataTable

### ISSUE THREAD

**Issue by Danieleeee** [primefaces/primeng#2022]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
[https://drive.google.com/file/d/0B9FXvLPoVlfeY0lTMkg5Q3pTeDQ/view?usp=sharing](url)

**Minimal reproduction of the problem with instructions**
Hi,
I have added p-multiselt in the filter of my p-dataTable:

`<template pTemplate="filter" let-col>
					<p-multiSelect [options]="Remi" defaultLabel="Tutti" (onChange)="dt.filter($event.value,col.field,col.filterMatchMode)" styleClass="ui-column-filter" appendTo="body"></p-multiSelect>
				</template>`
The problem is that when I click for selecting on one item of the list, the list disappear and I have to re-click on the filter (multiSelect).

I think that the problem is with "appendTo" but if I remove it the list is under the dataTabel.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.4.6

* **PrimeNG version:** 2.0.0

* **Browser:** [Chrome Last ]

 
* **Language:** [ES5]

**Comment by nag0538** [comment]
.ui-datatable-scrollable-header {
overflow: visible;
}

this thing worked for me
note:remove appendTo="body"
