### ISSUE TITLE
Selected option does not appear highlighted while opening list again

### ISSUE THREAD

**Issue by skgyan** [primefaces/primeng#2024]
I am using autocomplete single select and my options are coming from an endpoint. When I select an option and opens the list again I don't see the selected option highlighted, however if I use up/down arrow keys then selection moves from the previously selected option.

**Comment by Mrtcndkn** [comment]
Autocomplete dropdown displays suggestions when you select a suggestion it's your value but when you reopen suggestion that item is only a suggestion so it's expected behaviour.

**Comment by skgyan** [comment]
But shouldn't it move from the first option on wards on using down arrow key rather than from the last selected value.
