### ISSUE TITLE
scrollable table  breaks with few items

### ISSUE THREAD

**Issue by yuvalbl** [primefaces/primeng#2028]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/Mol9nO9jls4RXvMCKom7?p=preview

**Current behavior**

scrollable table  breaks with few items (not enough items for scroll)

**Expected behavior**

It should look like a table without scrolling

**Minimal reproduction of the problem with instructions**
*STEPS TO REPRODUCE (see plunker)*
1. create scrollable table with  scrollHeight="200px" and 3 items
2. look at the tables headers and table columns borders (see image attached and plunker
![image](https://cloud.githubusercontent.com/assets/11487010/22782049/03774716-eece-11e6-9b96-ca2f887e60dc.png)
)

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Linux ubuntu, webstorm

* **Angular version:** 2.0.X

2.4

* **PrimeNG version:** 2.0.X

2.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

chrome 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

* **Node (for AoT issues):** `node --version` =

**Comment by Mrtcndkn** [comment]
Hi,

I couldn't replicate this issue and your plunkr isn't working.

http://pasteboard.co/whJ5d99Is.png

**Comment by yuvalbl** [comment]
This is the template I've used, with the data array as "characters"

`  <p-dataTable [value]="characters" scrollable="true" scrollHeight="200px">
    <p-column field="id" header="Id" [sortable]="true"></p-column>
    <p-column field="name" header="Name" [sortable]="true"></p-column>
    <p-column field="weapon" header="Weapon" [sortable]="true"></p-column>
  </p-dataTable>`

**Comment by Mrtcndkn** [comment]
I did it exactly like you with your datatable still no lucks.

http://pasteboard.co/wB8DZBkxH.png

**Comment by yuvalbl** [comment]
I've manage to reconstruct it easily with the following steps:
1. Download plunk code  [plunk_scrollable_table_breaks.zip](https://github.com/primefaces/primeng/files/769202/plunk_scrollable_table_breaks.zip)
2. Run it with python server as offered [here](http://stackoverflow.com/questions/19328170/why-doesnt-this-plnkr-work-when-i-download-it)
3. Go to localhost:8000 (or whatever port you define if you override the default) and there it is.

I'm uploading my downloaded plunk as  attachment.

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
