### ISSUE TITLE
DataTable Mutltiselect filter is not completely visible

### ISSUE THREAD

**Issue by mohan1304** [primefaces/primeng#2030]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

DataTable multiselect filter is not completely visible when table size is smaller than multiselect filter. Please refer below link for more details

http://stackoverflow.com/questions/42139842/primeng-datatable-multiselect-filter-is-fully-visible-when-table-size-is-smaller

**Expected behavior**

Multiselect filter when we click on table column header should always show on top irrespective of table size

**Please tell us about your environment:**

Operating System: Windows 7

* **Angular version:** 2.0.X

Angular 2.4.6

* **PrimeNG version:** 2.0.X

PrimeNG 2.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome 56

**Comment by Mrtcndkn** [comment]
Hi,

Add appendTo="body" to your multi select.

**Comment by mohan1304** [comment]
Thanks for your reply. Its displaying as expected by adding appendTo="body" to multiselect. But the problem is multiselect popup disappears after selecting the value. 

My code is 
<template pTemplate="filter" let-col>
            				<p-multiSelect [options]="propName" defaultLabel="All" (onChange)="propsDt.filter($event.value,col.field,col.filterMatchMode)" styleClass="ui-column-filter" appendTo="body" ></p-multiSelect>
        				</template>

**Comment by mohan1304** [comment]
Please reopen the issue.

**Comment by mohan1304** [comment]
Can we reopen the issue please?
