### ISSUE TITLE
DatatTable MultiSelect Filter does not work on multiple selections with numeric Label value pairs

### ISSUE THREAD

**Issue by anirudh-jagithyala** [primefaces/primeng#2032]
**I'm submitting a ...**  (check one with "x")
```
[* ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/sIvf1L5C9YOxzLvcFopu?p=preview 

**Current behavior**

Multiselect Filter, filters datatable if only on item selected. Filter does not happen with multiple selection.

http://plnkr.co/edit/sIvf1L5C9YOxzLvcFopu?p=preview 

**Expected behavior**
Multiple Items in the multiselect Filter to be allowed for datatable filter selection

**Minimal reproduction of the problem with instructions**

Sample code: 
http://plnkr.co/edit/sIvf1L5C9YOxzLvcFopu?p=preview 

**What is the motivation / use case for changing the behavior?**

**_It is more to essentially handle SelectItem label Value as Key,Value pairs with keys being numbers rather than string , in such cases the filtering of multiselect does not behave as expected._** 

I assume, To fix this, the filter should be a collections of values in the FilterMetaData
https://github.com/primefaces/primeng/blob/master/components/common/api.ts#L22

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by anirudh-jagithyala** [comment]
It is more to essentially handle SelectItem label Value as Key,Value pairs with keys being numbers rather than string , in such cases the filtering of multiselect does not behave as expected.

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview

**Comment by AlexTo** [comment]
I am using the latest 4.2.2 and still encountering the same problem. Whatever I type in global filter results in "No records found"
If I remove the column that has selectionMode="multiple" then global filter works as per normal.
