### ISSUE TITLE
Autocomplete with dropdown button usability issues

### ISSUE THREAD

**Issue by davladus** [primefaces/primeng#2033]
**I'm submitting a usability bugs

**Plunkr Case (Bug Reports)**
http://www.primefaces.org/primeng/#/autocomplete 

**Current/Expected behavior**
**Minimal reproduction of the problem with instructions**

	**Issue 1**
	When I click on dropdown button (Advanced sample)
	And type letters to filter data
	Then
		Observed: nothing happens
		Expected: filterring happens

	 **Issue 2**
	When I click on text area (Advanced sample)
	Then
		Observed: nothing happens
		Expected: selection dropdown is expanded

	**Issue 3**
	When I start typing letters (Advanced sample)
	And selection dropdown is expanded
	Then
		Observed: nothing selected
		Expected: first filtered item is selected

	**Issue 4**
	When I have some value selected (Volvo) (Advanced sample)
	And I click on dropdown button 
	Then
		Observed: nothing selected
		Expected: initially selected item is selected (Volvo)

**What is the motivation / use case for changing the behavior?**
make you product better

**Please tell us about your environment:**
 Window 7, Chrome

**Comment by Mrtcndkn** [comment]
Hi,

Your post should involve 1 issue only you should open your issues separately.
