### ISSUE TITLE
Chart function generateLegend needs to be exposed

### ISSUE THREAD

**Issue by ivanhosgood** [primefaces/primeng#2035]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
N/A

**Current behavior**
generateLegend() isn't exposed within chart.ts. This function is used to invoke the callback legendCallback, used to customise the styling of the legend. 
http://www.chartjs.org/docs/#chart-configuration-legend-configuration

**Expected behavior**

generateLegend is exposed 

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Chart legend customization

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

2.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by seanareed** [comment]
@sikolio :  Thanks for the fix! I was breaking my head over that!

Will sikolio's fix make it into the next release?

(I don't see the change in the 4.1.0-rc.3 source.)
