### ISSUE TITLE
AutoComplete filtering doesn't work after dropdown button is clicked

### ISSUE THREAD

**Issue by davladus** [primefaces/primeng#2038]
**I'm submitting a usability bug

Plunkr Case (Bug Reports)
http://www.primefaces.org/primeng/#/autocomplete

Current/Expected behavior

When I click on dropdown button (Advanced sample)
And type letters to filter data
Then
	Observed: nothing happens
	Expected: filtering happens

Please tell us about your environment:
Window 7, Chrome

**Comment by Mrtcndkn** [comment]
This one is fixing this issue

https://github.com/primefaces/primeng/issues/2037
