### ISSUE TITLE
Autocomplete with dropdown button is not expanded on click

### ISSUE THREAD

**Issue by davladus** [primefaces/primeng#2039]
**I'm submitting a usability bug

Plunkr Case (Bug Reports)
http://www.primefaces.org/primeng/#/autocomplete

Current/Expected behavior
Minimal reproduction of the problem with instructions

When I click on text area (Advanced sample)
Then
	Observed: nothing happens
	Expected: selection dropdown is expanded

What is the motivation / use case for changing the behavior?
make you product better

Please tell us about your environment:
Window 7, Chrome

**Comment by Mrtcndkn** [comment]
We reviewed this and this is expected behaviour.
