### ISSUE TITLE
Autocomplete: previously selected value is not selected in 

### ISSUE THREAD

**Issue by davladus** [primefaces/primeng#2042]
**I'm submitting a usability bug

Plunkr Case (Bug Reports)
http://www.primefaces.org/primeng/#/autocomplete

Current/Expected behavior
Minimal reproduction of the problem with instructions

When I have some value selected (Volvo) (Advanced sample)
And I click on dropdown button 
Then
	Observed: nothing selected
	Expected: initially selected item is selected (Volvo)

What is the motivation / use case for changing the behavior?
make you product better

Please tell us about your environment:
Window 7, Chrome

**Comment by Mrtcndkn** [comment]
We reviewed this and this is expected behaviour.
