### ISSUE TITLE
Dropdown component update using model binding

### ISSUE THREAD

**Issue by ribizli** [primefaces/primeng#2043]
**I'm submitting a ...
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

http://plnkr.co/edit/lRYOd41KNG2oMVEY6JyA?p=preview

**Current behavior**
When updating the model value that was selected by selecting **from a filtered list** of the dropdown, the dropdown is not getting updated to the correct value. If the filter option is not used or is emptied before, everything is working fine.

**Expected behavior**
The dropdown's textbox should be updated to the correct value.

**Minimal reproduction of the problem with instructions**
Instuctions in the plunkr.

**Please tell us about your environment:**

* **Angular version:** latest (2.4.7)

* **PrimeNG version:** 2.0.0

* **Browser:** [Chrome 56 ]
 
* **Language:** [TypeScript 2.X]

**Comment by ribizli** [comment]
I think here the issue is, that the list of options is filtered, and the by model set value is not inside. One should clear the filtering when `writeValue` is called by `ngModel`

**Comment by GabKas** [comment]
Hi,

are you planning to merge the proposed fix?

**Comment by siddharthaReddy** [comment]
It would be great if this fix can be added in upcoming 2.x release too. We can't update to 4.x yet, as the app still uses angular@2.x
