### ISSUE TITLE
How to building the npm package?

### ISSUE THREAD

**Issue by SangKa** [primefaces/primeng#2047]
Each component folder of the npm package has files as blow:
.js
.js.map
.d.ts
.metedata.json

Could you please publish a guide for how to building the npm package just like [Building From Source](https://github.com/primefaces/primeng/wiki/Building-From-Source) in the Wiki. 
Thank you~

**Comment by rikup88** [comment]
Here are some instructions: http://forum.primefaces.org/viewtopic.php?f=35&t=48895&p=151257&hilit=build#p151257

**Comment by SangKa** [comment]
Thanks a lot ~ so helpful
