### ISSUE TITLE
Datatable row editing

### ISSUE THREAD

**Issue by katrina-engelbrecht** [primefaces/primeng#2048]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/D1AK7i

**Current behavior**

The datatable can be editalbe for the whole table or for columns.
**Expected behavior**

I want to edit table cell based on row. A good example pls. refer to 

- [ ] http://www.primefaces.org/showcase/ui/data/datatable/edit.xhtml 
the first example.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

At the end of each row there is a "edit" icon, when user clicks on it, the whole row will be editable, and the icons will be changed to "save" and "cancel". User can save the change or cancel the editing action back to the initial "edit" icon. Just like the PrimeFaces datatable editable showcase.
**Please tell us about your environment:**

Windows 10, WebStorm, npm, NodeJS
* **Angular version:** 2.0.X
Angular 2.0.X

* **PrimeNG version:** 2.0.X
PrimeNG Version 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =  6.9.5

**Comment by sharok** [comment]
@cagataycivici Could you add this feature to roadmap? I think it's very important feature for datatable.

**Comment by lx1036** [comment]
@cagataycivici @sharok Yes, It is a very import feature for datatable. We need it, haha.

**Comment by katrina-engelbrecht** [comment]
so how about this issue? Have you make some progress?

**Comment by sharok** [comment]
I saw inline row editing in the roadmap, but now it doesn't have it. @cagataycivici Do you have plans for inline row editing/adding? If no, could you provide some workaround if it's possible?

**Comment by cagataycivici** [comment]
Yes, we'll do it after 4.0.

**Comment by meanle11** [comment]
I see this problem becomes necessary for developer, I hope team primeng will update it soon

**Comment by jevgenimarenkov** [comment]
Do you have any plans to implement that? Actually, it is critical feature for DataTable.

**Comment by NordRagnarok** [comment]
There are any updates regarding this issue? I'm looking forward to use this data table but cannot without this feature - if there's anything I can help, please notify me. Thanks.

**Comment by alannsiqueira** [comment]
Há alguma atualização sobre este problema? Estou ansioso para usar esta tabela de dados, mas não posso sem esse recurso - se houver qualquer coisa que eu possa ajudar, notifique-me. Obrigado.[2]

**Comment by alannsiqueira** [comment]
There are any updates regarding this issue? I'm looking forward to use this data table but cannot without this feature - if there's anything I can help, please notify me. Thanks.

**Comment by scurk1415** [comment]
I also want to know if there are any changes about this.

**Comment by alannsiqueira** [comment]
waiting for this feature

**Comment by sviswanathjcet** [comment]
waiting for this feature

**Comment by sviswanathjcet** [comment]
@cagataycivici Can i get any update on this feature?

**Comment by pierfreeman** [comment]
+1 on the queue, I really needed it

**Comment by karakule006** [comment]
waiting too

**Comment by alannsiqueira** [comment]
is there a preview for this feature?

**Comment by Chi1985** [comment]
Any update on this feature?

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.

**Comment by pierfreeman** [comment]
@cagataycivici I'm looking the documentation of the new p-table but I don't see any "edit by row". Do you confirm this feature will be present in the next release?

**Comment by evilsephiroth** [comment]
any news on this?

**Comment by selem1** [comment]
Need it please on the old DataTable, I cannot use the Turbo Table since it works only for angular-5 projects !

**Comment by NordRagnarok** [comment]
The version on the site is the most updated one? It does support this feature yet - only cell edit
Thanks

**Comment by pierfreeman** [comment]
@cagataycivici an answer on this? Any news would be appreciated.

**Comment by ctrl-brk** [comment]
I would suggest you to create a new issue. Seems like they've closed all Datatable issues without even looking at them (that's sad because lots of them apply to the new version too) when released the new TurboTable.
It also doesn't look like there will be any future updates for Datatable. And I'm afraid that Datatable will be completely removed soon so you're going to stick to some older version of primeng without ability to update it.

**Comment by pierfreeman** [comment]
@ctrl-brk Yeah I don't mind to work with TurboTable instead of DataTable, I already migrated to this component, but as you said, several issues still apply to it. 
So yes, I will create another issue, hoping it won't be shut down as well.

**Comment by pierfreeman** [comment]
I created a new related issue specifically for the new table: https://github.com/primefaces/primeng/issues/5284

It seems that it has already been put in the milestones for release 6.
