### ISSUE TITLE
Peer dependencies with A2-beta.15 incompatible?

### ISSUE THREAD

**Issue by Luchillo** [primefaces/primeng#205]
Just installed PrimeNg and npm complains about peer deps, A2-beta.15 requires zone.js@^0.6.10 while PrimeNg requires exactly 0.6.6 so if i fulfil A2 deps i fail to fulfil Zone.js version for PrimeNg peer dependency, can this be updated or fixed to '@^0.6.6'.

Also PrimeNg complains for a peer dep on System.js but i'm using webpack, shouldn't be a choice of the user which bundler to use?

**Comment by cesarrew** [comment]
#204

**Comment by cagataycivici** [comment]
See #206 please.

**Comment by Luchillo** [comment]
Cool, when will beta.3 arrive?

**Comment by cagataycivici** [comment]
Should be mid next week.

**Comment by Luchillo** [comment]
@cagataycivici I notice that most lib makers use hard peer dependencies on certain versions of other libs, in `primeng@1.0.0-beta.4` case is `angular2@2.0.0-beta.17`, is it really a hard dependency? do primeng `beta.0` break if used with `angular2@2.0.0-beta.16` or `15`or `14`?

As far as i know peer dependencies are meant to tell the user what's the minimum version of the other libs that this one needs to work properly, if it's indeed `angular2@2.0.0-beta.17` the minimum, at least put it as `angular2@^2.0.0-beta.17` in order to allow for future Angular 2 versions.

**Comment by cagataycivici** [comment]
Yes it will break due to some breaking changes in beta 17 so at least beta 17 is required.

**Comment by cagataycivici** [comment]
Sure we will add at least symbol for next primeng beta releas3. Thanks for your feedback.
