### ISSUE TITLE
Allow for inserted pictures in the editor to be resized

### ISSUE THREAD

**Issue by vbudilov** [primefaces/primeng#2050]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Minimal reproduction of the problem with instructions**
Use the editor primeng component. Insert an image into an editor. it can't be resized within the editor.

**What is the motivation / use case for changing the behavior?**

In any 'editor-type' of an environment, the ability to format the picture inserted into the editor is vital. Maybe an inserted picture should go into a div which dimenstions can be manipulated either by typing or directly with the mouse. 

**Please tell us about your environment:**

Linux, Chrome

* **Angular version:** 2.0.X

2.4.7
* **PrimeNG version:** 2.0.X

2.0.0-rc.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript
* **Node (for AoT issues):** `node --version` =

**Comment by upmauro** [comment]
PrimeNG uses QuillJS and the library does not support resize yet.

https://github.com/quilljs/quill/issues/905

**Comment by cagataycivici** [comment]
This is related to quill.
