### ISSUE TITLE
ContextMenu support for Schedule

### ISSUE THREAD

**Issue by lamhidra** [primefaces/primeng#2051]
I want to attach a contextmenu to schedule when i click on a specific day
I have tried this:
handleDayClick(event, contextMenu) {
     contextMenu.show(event.jsEvent);
  }
But it didn't work.

**Comment by billfranklin** [comment]
Yes, please add contextmenu support for Schedule for both days and events.  Day use case is right click on day to Add an event (or, for instance, show rejected requests, et.al.), whereas left click would be used to switch to basicDay view.  Event use case is right click on event to View/Add/Edit/Delete/Approve/Reject/etc. event

This particular need has been driving me crazy

**Comment by yigitfindikli** [comment]
We'll reconsider if there is more community feedback on this. Thank you for your report.
