### ISSUE TITLE
RadioButton selecting multiple options

### ISSUE THREAD

**Issue by onesick** [primefaces/primeng#2052]
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When I select a radio button, and select another button, the previous button stays visually chosen. However, the value gets updated.

**Expected behavior**
I expect the radio button to show the value selected, instead of saving the history of radio buttons clicked.

The html view are the following:
```
```
<div formArrayName="sms">
<span><p-radioButton formControlName="time" value="9AM ~ 12PM" label="9AM to 12PM"  ></p-radioButton></span>
<span><p-radioButton formControlName="time" value="10AM ~ 2PM" label="10AM to 2PM" ></p-radioButton></span>
 <span><p-radioButton formControlName="time" value="1PM ~ 5PM" label="1PM to 5PM" ></p-radioButton></span>
</div>
```

Thank you.

**Comment by Mrtcndkn** [comment]
Hi,

Locally it looks fine. 
Please try this;
   
     <p-radioButton formControlName="time" name="radio" value="9AM ~ 12PM" label="9AM to 12PM"  ></p-radioButton>
     <p-radioButton formControlName="time" name="radio" value="10AM ~ 2PM" label="10AM to 2PM" ></p-radioButton>
     <p-radioButton formControlName="time" name="radio" value="1PM ~ 5PM" label="1PM to 5PM" ></p-radioButton>

Add name="radio" to all buttons.

If bug consists please reopen the issue.

**Comment by onesick** [comment]
Hi,

I use FormArray, and when more than 1 forms are added within the array, the radio button gets messed up. Which ever the last form's radio I click stays marked as clicked. The values are all correctly selected. However, in UI perspective, it is really confusing cause I do not know what value I selected for other forms in the FormArray. I think this is another bug.
