### ISSUE TITLE
File Upload 'disabled' attribute disabling whole functionality even if set to false

### ISSUE THREAD

**Issue by bhamde** [primefaces/primeng#2054]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

http://plnkr.co/edit/61VzrVztgGSkdgUcFKXO

**Current behavior**
Currently as you can see in plunker, even tho disabled attribute is set to false, the choose button is disabled which is unexpected.

**Expected behavior**
http://www.primefaces.org/primeng/#/fileupload describes that there is an attribute called 'disabled' that disables/enabled the upload button. Therefore I expect the choose button to always be enabled even if disabled is set, also if we set disabled="false", the upload button should be still enabled. We should be able to bind this attribute to a local variable to enable/disable the button

**What is the motivation / use case for changing the behavior?**
Main motive is to be able to disable the upload button if the files chosen are not as required

Issue found on primeNG Version 2.0.0

**Comment by Mrtcndkn** [comment]
Hi,

You should bind disabled attribute

    [disabled]="false"

**Comment by DropkickSteve** [comment]
This issue has not been addressed, the [disabled] property disables all 3 buttons, there is no way to disable a click on the Upload button according to some condition. Version 4.2.2
