### ISSUE TITLE
Issue with p-calendar stepMinute and dataType="string"

### ISSUE THREAD

**Issue by Jobberd** [primefaces/primeng#2058]
**I'm submitting a ...**
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

http://plnkr.co/edit/QUWB5e76HwapxWbxpWpa

**Current behavior**

If you use the stepMinute directive in combination with dataType="string", the minutes will not be added correctly. 

**Expected behavior**

When you use stepminutes with dataType="string", the minutes should be added as if p-calendar internally parses the time as integers 

**Minimal reproduction of the problem with instructions**

See behaviour in plunkr added above

**Comment by upmauro** [comment]
This is not a bug.

Look, https://github.com/primefaces/primeng/blob/master/components/calendar/calendar.ts#L206

The stepMinute is a number, but for angular respect the type you need use brackets []

Use **[stepMinute]="15"** instead of stepMinute="15"
