### ISSUE TITLE
create a custom DropDownComponent from DropDown

### ISSUE THREAD

**Issue by yalaa90** [primefaces/primeng#2059]
hi i'm trying to create a custom DropDownComponent from DropDown so i my code is 
export class DropDownComponent extends Dropdown  {

but i got exception that inline template:0:0 caused by: No provider for DomHandler!

so when i put it in the providers array it throw another exception 
Invalid providers for "DropDownComponent" - only instances of Provider and Type are allowed, got: [DropDownService, ?undefined?]

so it's ?undefined?

please tell me if there any another way to create custom dropdown component that implements controlValueAccessor to use it with ngModel or FormControlName

```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

 
* **Angular version:** 2.3.1

* **PrimeNG version:** 1.1.4

**Comment by cagataycivici** [comment]
Please use forum for support requests and questions, thank you.
