### ISSUE TITLE
Sorting stops working after custom global filter is applied (DataTable & AutoComplete)

### ISSUE THREAD

**Issue by LDV2k3** [primefaces/primeng#2064]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

I was able to reproduce the issue on plunker (link below) using the same structure as in my local project
- app.ts
-- contains the <p-dataTable>, the data, the pipe in the [value] and the filter's component
- filter.ts
-- contains the <p-autoComplete>, pre-filtered names, EventEmitter, etc.
- pipe.ts
-- contains the logic to return the data according the names chosen

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/FIHY8sY8wCA0Ms6lrQ3f?p=preview

**Current behavior**
On filtering two or more names the sorting stops working unless I clear the filter

**Expected behavior**
Sorting should work also with the filter applied

**Minimal reproduction of the problem with instructions**
1. Try sorting the table as is (it works, with both columns)
2. Filter two (or more) different names, ie. John B & Charlie B
3. Try sorting the table by any of its columns (it doesn't work)
4. Clear both (or all) the names of the filter
5. Try sorting the table (it works again)

**Please tell us about your environment:**
Windows 10, NPM, Angular CLI beta 21, Visual Studio Code

* **Angular version:** 2.4.4

* **PrimeNG version:** 2.0.0 final

* **Browser:** [Chrome 56 | Firefox 51 | IE 11]
 
* **Language:** [TypeScript ~2.1.5 | ES6/7]

* **Node (for AoT issues):** `node --version` =   4.4.7

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
