### ISSUE TITLE
Frozen columns in datable - styling is broken when row has empty values in all unfrozen columns

### ISSUE THREAD

**Issue by mmlitvin** [primefaces/primeng#2066]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/oyT5op2cnkR5cerVNZzJ?p=preview

**Current behavior**
If row has empty values in all unfrozen columns rows styling is messed up

**Expected behavior**
Empty values in the table should have no impact on styling

**Minimal reproduction of the problem with instructions**

See plunker above

**What is the motivation / use case for changing the behavior?**

It is a defect

**Please tell us about your environment:**

* **Angular version:** 2.4.1

* **PrimeNG version:** 2.0.0

* **Browser:** [Chrome 56 | Firefox 45.0.1 ]

 
* **Language:** [all | TypeScript 2.0 | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
This has been discussed a couple of times, you need to set min-height of datatable rows;

```
.ui-datatable tbody > tr {
   min-height:30px;
}
```

We don't to do to avoid performance as we need to calculate things, so leave to the user.
