### ISSUE TITLE
Frozen columns in datable - styling is broken on Word Wrap

### ISSUE THREAD

**Issue by mmlitvin** [primefaces/primeng#2067]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/HP5Sp0nocEd4WRW7ROVP?p=preview

**Current behavior**
When frozen columns in datable new feature is enabled - styling is broken on Word Wrap in cells

**Expected behavior**
Rows height should stay the same across the table

**Minimal reproduction of the problem with instructions**

Please see plunker above

**What is the motivation / use case for changing the behavior?**

A defect

Angular version: 2.4.1
PrimeNG version: 2.0.0
Browser: [Chrome 56 | Firefox 45.0.1 ]
Language: [all | TypeScript 2.0 | ES6/7 | ES5]

Node (for AoT issues): node --version =

**Comment by arjun7692** [comment]
+1 facing same problem. Due to two tables being created, word wrap creates a row height mismatch.

**Comment by nobiinu-and** [comment]
+1

**Comment by cagataycivici** [comment]
This has been discussed a couple of times, you need to set min-height of datatable rows;

```
.ui-datatable tbody > tr {
   min-height:30px;
}
```

We don't to do to avoid performance as we need to calculate things, so leave to the user.
