### ISSUE TITLE
Routes from links or buttons do not update static menu

### ISSUE THREAD

**Issue by blinkxzero** [primefaces/primeng#2069]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When changing routes using a link or button (not the menu), the menu does not update to the new page, nor does it open the submenu if the route is a child.  

**Expected behavior**
The menu should always reflect the current route if possible. Submenus should open if the route is a child inside a submenu. 

**Minimal reproduction of the problem with instructions**
- Go directly to: http://www.primefaces.org/ultima-ng/#/forms
- Notice all menus are closed and none are styled with the active route. 

**What is the motivation / use case for changing the behavior?**
Hyperlinks, buttons with hyperlinks, or pages that users "bookmark" all create this behavior. It causes confusion for the users since the menu doesn't reflect the current state of the application.

**Please tell us about your environment:**

* **Angular version:** 2.4.7

* **PrimeNG version:** 2.0.0

* **Browser:** all
 
* **Language:** all

**Comment by cagataycivici** [comment]
Demo router is one level, to implement something like this you need to configure router to do something like components/forms. Current behavior is expected.
