### ISSUE TITLE
DataTable filtering and sorting not working well together

### ISSUE THREAD

**Issue by gatapia** [primefaces/primeng#207]
Updated to beta1 and the problem still exists, i.e.  
- Set up a table with columns with sortable=true filter=true 
- Filter by some value (using default filter type)
- Sort by any column and the full list is displayed again

**Comment by cagataycivici** [comment]
Can you try with beta2?

**Comment by gatapia** [comment]
Yes this was with beta2, here is the relevant section of my packages.json.

```
    "primeng": "^1.0.0-beta.2",
    "primeui": "^4.1.8",
```

**Comment by cagataycivici** [comment]
Replicated, it happens after sorting again though for me like filter+sort is ok but sorting again displays full list.

**Comment by prabugithub** [comment]
this is still replicating in custom sort option, is there any workaround? it return whole data instead of custom data
