### ISSUE TITLE
Accordion: use animation callback to control the animating flag

### ISSUE THREAD

**Issue by ribizli** [primefaces/primeng#2072]
**I'm submitting a ...** 
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Currently if the `AccordionTab`'s selected state is changed through `@Input`, the `animating` flag is not set, so the class `ui-accordion-content-wrapper-overflown` is removed during animation, so the content is immediately visible, ruining the animation.

**Expected behavior**
Use `(@tabContent.start)` and `(@tabContent.done)` to set the `animating` flag. (There is already a `TODO` for this in the code)

* **PrimeNG version:** 2.0.0

**Comment by sudheerj** [comment]
Can you provide an example to replicate the issue.

**Comment by ribizli** [comment]
http://plnkr.co/edit/jSU9gNtfq6UUMRLh0SIy?p=preview

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
