### ISSUE TITLE
Remove fade in/fade out on p-dialog

### ISSUE THREAD

**Issue by fplini** [primefaces/primeng#2073]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Hi all, I simply want to know how remove the fade in/fade out effect to a p-dialog. It seems to be impossible? I posted on forum many days ago but nobody replied.

**Please tell us about your environment:**

Windws 7, IntelliJ IDEA, Jboss

* **Angular version:** 2.0.X
2.x

* **PrimeNG version:** 2.0.X
^1.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by sudheerj** [comment]
You can use NoopAnimationModule to disable the animations.
