### ISSUE TITLE
Scheduler add-on support for FullCalendar

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#2074]
Add support for Scheduler module, note that users many need to buy a license to use it as its license is not fully open;

https://fullcalendar.io/scheduler/license/

**Comment by ajay12thwonder** [comment]
@cagataycivici ,
      Any idea as to when this will be included in PrimeNg?
Thanks
Ajay

**Comment by cagataycivici** [comment]
By the end of this month.

**Comment by m1rc0** [comment]
@cagataycivici do you have any news about this?

Thanks

**Comment by sudheerj** [comment]
As a question from my personal point of view, is GPL license won't be fullfilled for PrimeNG as open source project?

**Comment by cagataycivici** [comment]
Due to license issues, we've decided not to proceed for now, need to consult fullcalendar guys to see if we can do it.

**Comment by ohtwadi** [comment]
@cagataycivici As noted by @sudheerj, wouldn't GPL license be sufficient for use with PrimeNG?  I'm sure it would be appreciated by many if FullCalendar Schedular can be added to PrimeNG Schedule.

Thank you for providing this awesome UI library.  I used PrimeFaces in the past and PrimeNG is just as awesome!

**Comment by dnyg** [comment]
Any news about this?
