### ISSUE TITLE
SplitButton does not return Menu metadata in command callback

### ISSUE THREAD

**Issue by iammostwnted** [primefaces/primeng#2075]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
SplitButton does not return Menu metadata in command callback , instead it returns MouseEvent.

**Expected behavior**
SplitButton should return original event (browser event) and menuitem metadata as stated in documentation at http://www.primefaces.org/primeng/#/menumodel

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by loic49** [comment]
+1

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/VZbdZfQ7SuTV87tTkbYR

The code we have is;

```
item.eventEmitter.emit({
                originalEvent: event,
                item: item
            });
```
