### ISSUE TITLE
TabView Not Scrolling after adding more tabs

### ISSUE THREAD

**Issue by serak** [primefaces/primeng#2076]
HI All Dojo , Angular material 1.x and most of full featured Tabview(tabcontainers) scroll horizontally which i think is more needed function when it comes to multitasking webapp 

![image](https://cloud.githubusercontent.com/assets/3592372/22962298/1b76b8ae-f35d-11e6-843e-abd769839103.png)

**Comment by morganRotaStabelli** [comment]
I needed too, this! Optimus, calls all Autobots!!

**Comment by imranshafqat** [comment]
I need it too
+1

**Comment by cagataycivici** [comment]
Duplicate of https://github.com/primefaces/primeng/issues/1701;

We'll do it as we've done it before at PrimeFaces.
