### ISSUE TITLE
primeng.DataTable, how to set a row as selected (highlighted) with button in-grid? 

### ISSUE THREAD

**Issue by milla** [primefaces/primeng#2078]
As p-dataTable 1 is master table, and p-dataTable 2 is its detail table, so when a button of 'Show Detail' got clicked, the row containing the button shall be shown as selected or highlighted.  How I can make this? is there any existing function I can call to set a row as selected or some what?

Thanks, Elaine

**Comment by cagataycivici** [comment]
Please use forum for support requests.
