### ISSUE TITLE
Primeng Beta 2 missing zonejs 0.6.10 fails npm install.

### ISSUE THREAD

**Issue by dlabaj** [primefaces/primeng#208]
Installing Primeng beta 2 from npm causes failure due to miss configuration of zonejs.  It's currently set to 0.6.6 in beta 2, however Angular 2.0.0-beta15 want zonejs 0.6.10.  Angular also updated systemjs to 0.19.26

 "dependencies": {
    "angular2": "2.0.0-beta.15",
    "systemjs": "0.19.26",
    "es6-shim": "^0.35.0",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.2",
    "zone.js": "0.6.10"
  },

**Comment by cagataycivici** [comment]
Please see;

https://github.com/primefaces/primeng/issues/206
