### ISSUE TITLE
Dropdown not usable when used inside dialog with scheduler

### ISSUE THREAD

**Issue by gabriel-munteanu** [primefaces/primeng#2080]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

I created my plunker from scrath before I saw this template
https://plnkr.co/edit/lVl35Gg6m05RC9pMMxbp

**Current behavior**
When opening the dialog(on day click) I cannot use the mouse to select an option from the dropdown. Only arrow keys and Enter key works.

**Expected behavior**
I should be able to select an option without problem.

**Minimal reproduction of the problem with instructions**
-

**What is the motivation / use case for changing the behavior?**
I need a dropdown in that dialog :)

**Please tell us about your environment:**
- not relevant

* **Angular version:** 2.4.4 in plnkr is 2.4.7

* **PrimeNG version:** 2.0.0

* **Browser:** [all ]

 
* **Language:** [TypeScript ]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
