### ISSUE TITLE
Displayed value in the input does not always get updated correctly

### ISSUE THREAD

**Issue by alarive** [primefaces/primeng#2081]
**I'm submitting a ...** 
```
[x ] bug report => Search github for a similar issue or PR before submitting
```

This can be reproduced in the showcase by doing the following steps:
1. go to http://www.primefaces.org/primeng/#/calendar
2. click in the "basic" calendar and select the date Feb 15, 2017
3. delete the content of the text input
4. type "2017" in the text input
5. select again  Feb 15, 2017 (**it has to be the same date than in step 2**)
The date text input does not get updated and still displays "2017", while the value of the calendar component is Feb 15, 2017

**Comment by gforceg** [comment]
I can confirm this issue happens to me too.
I've had similar problems w/ using the calendar component as a time picker.

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
