### ISSUE TITLE
Values for Slider StepFactor

### ISSUE THREAD

**Issue by bevrard** [primefaces/primeng#2087]
Is there a way to pass a list of values to the slider? (in place of steps)

Thanks

**Comment by sudheerj** [comment]
That is not the functionality of Slider component. i.e, It won't take random array values for sliding.

**Comment by cagataycivici** [comment]
There is range slider.

**Comment by bevrard** [comment]
Yes but I would like to get only one value, with a "step animation".  The step only allows to get a fixed increase.
In our case, we want to use step with these values:
1, 100, 2000, 5000, 50000.

Would it be possible?

**Comment by cagataycivici** [comment]
So that is for stepFactor right? Right now it is not possible. Reopening.

**Comment by bevrard** [comment]
Yes. Thanks!

**Comment by nithindan** [comment]
Is it possible to pass set of values for Steps ?

**Comment by Spawnrad** [comment]
How can we handle that please ?
I have a big slider range values between 0 to 10Million and i need to change the step value too.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
