### ISSUE TITLE
Incorrect order of working of "Cross" button on fileUpload component

### ISSUE THREAD

**Issue by ptsydzik** [primefaces/primeng#2088]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

you du not need Plunker issue reproduce on demo page http://primefaces.org/primeng/#/fileupload

**Current behavior**
1. Upload picture 1 than upload picture 2.
2. press "cross" button near picture 2
Actual: picture 1 is removed

**Expected behavior**
Expected: picture 2 is removed

**how to fix**
https://github.com/primefaces/primeng/blob/master/components/fileupload/fileupload.ts#L32
*ngFor="let file of files" should become *ngFor="let file of files; let i = index;"

this will solve issue

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
