### ISSUE TITLE
Generic SelectItem

### ISSUE THREAD

**Issue by m-tomczyk** [primefaces/primeng#2089]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
SelectItem interface has 'value' field of type _any_. Assigning values does not force any type check in this case.
In most cases values are either string or some form of enum (enum type or string literal type acting as enum) for every value of SelectItem's 'value' field in array. Having _any_ there makes keeping type safety in dropdowns difficult.

**Expected behavior**
SelectItem is generic interface. Example:

```
interface SelectItem<T> {
    label: string;
    value: T;
}

let dropdownItems: SelectItem<ExampleEnum>[] = [
    {
        label: 'example', 
        value: ExamleEnum.EXAMPLE_VALUE //<-- This is now ensured by typescript
    }
] 
```
Still if somebody requires to mix values in 'value' field you can use _any_ as type

**What is the motivation / use case for changing the behavior?**
More robust applications. 

**Please tell us about your environment:**

* **Angular version:** 2.X.X

* **PrimeNG version:** 2.X.X

* **Browser:** All browsers
 
* **Language:** Typescript

**Comment by steigerm** [comment]
+1 for this request

**Comment by m-tomczyk** [comment]
Little update on this.
In upcoming typescript v2.3 there will be new language feature that can make including this change as non-breaking - Default genertics ( https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#generic-parameter-defaults ).
`
interface SelectItem<T = any> {
    label: string;
    value: T;
}
`

**Comment by cagataycivici** [comment]
value can be anything, I see people using objects. Once typescript 2.3 is adopted, we can use the generic approach above, that's great!

**Comment by cagataycivici** [comment]
So we'll wait once typescript 2.3 has wider adoption.

**Comment by gatimus** [comment]
Angular CLI uses [2.3](https://github.com/angular/angular-cli/commit/69d3d2b05b5010187d918a2eb84df1feb7033d12) and supports [2.4](https://github.com/angular/angular-cli/commit/7b9fc285e3a9f6d06aa4a42c4b5e550c929888d7). If you `ng new` with `@angular/cli@1.4.5` you currently get `typescript@~2.3.3`.

**Comment by Anandhsa09** [comment]
In ng-dropdown, I am using selectedItem/API, the assigned value as the object from TS  are not displayed in the dropdown.
example:
TS
state = { id: 1, name: Chigaco } 
HTML
In the drop-down only shows placeholder not this assigned values

**Comment by william-lohan** [comment]
@Anandhsa09 what library is `ng-dropdown`? That doesn't sound related, there must be a way to specify which property to display in the `ng-dropdown` API ie like `optionLabel` in [`p-dropdown`](https://www.primefaces.org/primeng/#/dropdown) and template interpolation (see `viewValue`) in [`mat-select`](https://material.angular.io/components/select/examples) .

**Comment by Anandhsa09** [comment]
I put optionLabel in p-dropdown, but it's not working. It shows the only placeholder. Actually, I want to set the value programmatically. value is the object. facing problem to append the value in the dropdown.

**Comment by william-lohan** [comment]
@Anandhsa09 I suggest making an example of what you are talking about on https://stackblitz.com/fork/angular and posting a question on https://stackoverflow.com/

This issue is only about type intellisense so not sure its related.
