### ISSUE TITLE
Overlay: Dialog - location/position

### ISSUE THREAD

**Issue by the-r3dshirt** [primefaces/primeng#209]
The "location" attribute does not appear to do anything, and I could not find any reference to it within dialog.js

Default positioning seems to be positioning to the center based on total page height, not the height of the viewport? Although the example appears to works correctly: http://www.primefaces.org/primeng/#/dialog

**Comment by cagataycivici** [comment]
It should be based on viewport height, where do you want it to be located instead of center of page?

**Comment by the-r3dshirt** [comment]
Center would be ideal but it is positioning much further down the page and in same cases its not visible at all due to the offset position. I suspect one of the container elements/[bootstrap](http://getbootstrap.com/css/) style sheet is causing it some problems.

**Comment by cagataycivici** [comment]
Do you have an image in a dialog? Or something that is displayed after dialog is displayed?

**Comment by the-r3dshirt** [comment]
The content within the dialog was a form. I tried a simple text string as well, both had the positioning problem. On pages shorter than the viewport height the dialog box would position in the center as expected, on a long/tall pages it seems to be trying position in the center based on the height of page content.

**Comment by cagataycivici** [comment]
We'll check, thank you.

**Comment by the-r3dshirt** [comment]
"primeng": "1.0.0-beta.2",
"primeui": "4.1.8"

Seem to have solved the problem, if no height is specified for the body then it will produce a non centered dialog if your page is taller than the viewport. Setting body style="height: 100%" resolves the problem. :)

**Comment by cagataycivici** [comment]
Strange, in my tests that style wasn't required. I'll reopen if more users have this. One last thing, do you have doctype on your page?

**Comment by the-r3dshirt** [comment]
Ha, indeed I was missing <!DOCTYPE html> at the top of my index.html and that seems to have corrected it :+1:

**Comment by cagataycivici** [comment]
Great!
