### ISSUE TITLE
e2e tests

### ISSUE THREAD

**Issue by miherlosev** [primefaces/primeng#2093]
Components are too complex. And as time goes, their complexity grows.
To reduce the number of defects, I propose to add e2e tests.
I can write them using [TestCafe](http://github.com/devexpress/testcafe).
What do you think about it?

**Comment by waldo2188** [comment]
I think that's will be a great idea.
The tests you gonna write can also help people to write their own test.
So yes, it's a great idea !

**Comment by sudheerj** [comment]
There are some plans or discussions on unit tests and e2e tests from PrimeNG Team as well. But there is no final conclusion or dates on this.

**Comment by jdiapps** [comment]
I am trying to write my own unit test for the DataTable PrimeNG component.  I am populating the data correctly in the unit test, but when I call fixture.detectChanges() the DataTable doesn't populate the data. Only the p-dataTable and p-column is showing.

Are there examples of unit tests for DataTables?  Thanks

**Comment by cagataycivici** [comment]
New test suite is on the way. We'll create separate tickets for each components so closing this one.
