### ISSUE TITLE
contextmenu doesn't handle visibility

### ISSUE THREAD

**Issue by dankil** [primefaces/primeng#2095]
In the `p-contextMenuSub` template is the visible property not handled. Man can only use disabled: `[ngClass]="{'ui-state-disabled':child.disabled}"`

Please add a `*ngIf="child.visible"` to the `li` element

```
<template ngFor let-child [ngForOf]="(root ? item : item.items)">
    <li *ngIf="child.visible" #item [ngClass]="{'ui-menuitem ui-widget ui-corner-all':true,'ui-menu-parent':child.items,'ui-menuitem-active':item==activeItem}"
```

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
