### ISSUE TITLE
DataTable Column custom sorter support

### ISSUE THREAD

**Issue by gatapia** [primefaces/primeng#210]
It would be good if columns supported functions in the sortable argument.  I.e.

`<p-column field="x" [sortable]="customsorter">...`

Where custom sorter is a standard sorting function , i.e:

```
customsorter(column: string, row_a: any, row_b: any): number
// i.e. return -1, 0, 1 defending on comparison
```

Or perhaps as a temporary hack `[sortable]` could take a string pointing to another column.

This feature ofcourse would allow smart sorting on ordinal fields, such as "Severity" where alphabetical order makes no sense.

**Comment by cagataycivici** [comment]
Sounds good.
