### ISSUE TITLE
row unselect not work in datatable

### ISSUE THREAD

**Issue by papiroca-tm** [primefaces/primeng#2101]
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

* **Angular version:** 2.2.0
* **PrimeNG version:** 2.0.0
* **Language:** [TypeScript 2.0.10 ]
* **Node (for AoT issues):** `node --version` =   7

its not work in my project and its not work on http://www.primefaces.org/primeng/#/datatable/selection
onRowUnselect never fire, and not unselected after click on it.
i try to set selectedrow to null but it not work.

what i must do if i need this functionality?

**Comment by ctrl-brk** [comment]
Ctrl-click will deselect.
Would be nice to have this behavior configurable, so you can use either Ctrl-click for multiselect grids or just simple click for single.

**Comment by papiroca-tm** [comment]
tnx

**Comment by cagataycivici** [comment]
@ctrl-brk It is configurable in 2.0.1 via [metaKeySelection]="false";

https://github.com/primefaces/primeng/issues/2098
