### ISSUE TITLE
Allow editor template access rowIndex in datatable

### ISSUE THREAD

**Issue by windwolfreal** [primefaces/primeng#2104]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Comment by kuba-010** [comment]
I think this is a bug, no? If I use the pTemplate="body" it works fine, but when set to "editor" it seems to have no value

**Comment by upstreamosGH** [comment]
I've added the input property rowIndex to ColumnEditorTemplateLoader.
I've tested in my project and now the rowIndex is available also in column editor's template.
I'll make a pull-request. I Hope this could help.

**Comment by VincenzoMi** [comment]
It would be nice expose row index  in editor template. ;)
