### ISSUE TITLE
p-header not same length as p-body in scrollable datatable

### ISSUE THREAD

**Issue by KyubiBoy** [primefaces/primeng#2106]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://embed.plnkr.co/L3c7rU/

**Current behavior**
The header is not the same length as the body

**Expected behavior**
The header should be the same length as body

**Minimal reproduction of the problem with instructions**
**Full screen** monitor or **zoom out** and then **refresh** page(exceeds width of 1457px). It works just fine for "Laptop" and "Laptop L" screen widths

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** All
 
* **Language:** TypeScript X.X

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
