### ISSUE TITLE
TreeTable - group nodes with types different from leaves type

### ISSUE THREAD

**Issue by buchatsky** [primefaces/primeng#2109]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**

Now TreeTable accepts only regular objects (with the same structure) for both "leaf" nodes and "node" nodes which are stored in the "TreeNode.data" field, and it's impossible to display grouping nodes with different fields, even with plain text label: field "TreeNode.label" is not used anywhere in treetable.js

**Expected behavior**
If TreeNode.data == null - display TreeNode.label over all row width instead of column-structured row.
This is enough for simple tasks (but group templating could be better for more complex cases)
I temporary fixed the issue with the following template:

<div class="ui-treetable-row" [ngClass]="{'ui-state-highlight':isSelected(),'ui-treetable-row-selectable':treeTable.selectionMode}">
	<ng-container *ngIf="node.data">
		<td *ngFor="let col of treeTable.columns; let i=index" ...>
			
		</td>
	</ng-container>
	<td *ngIf="!node.data" [attr.colspan]="treeTable.columns.length" (click)="onRowClick($event)">
		<a href="#" class="ui-treetable-toggler fa fa-fw ui-c" [ngClass]="{'fa-caret-down':node.expanded,'fa-caret-right':!node.expanded}"
			[ngStyle]="{'margin-left':level*16 + 'px','visibility': isLeaf() ? 'hidden' : 'visible'}" (click)="toggle($event)" 
			[title]="node.expanded ? labelCollapse : labelExpand"></a>
		<span>{{ node.label }}</span>
	</td>
</div>

and I also utilized properties "level" (tree level) and "value" (grouping ID) on the TreeNode.
PS. Fixed html template is not shown here so I added it as FixedTemplate.html to Plunker

**Minimal reproduction of the problem with instructions**

Plunker sample code for testing: [http://plnkr.co/edit/L7jjUg](http://plnkr.co/edit/L7jjUg)
(leaves are displayed but group node labels are not) 

**What is the motivation / use case for changing the behavior?**

Suppose Suppliers table from the Microsoft SQL Northwind demo DB. It has basic structure like:
`class Supplier {
	Id: number;
	CompanyName?: string;
	City?: string;
	Region?: string;
	Country?: string;
}`
and I want to group them with 2 levels: with Country and then with Region. And similar situation when Supplier has RegionID and CountryID which reference another table (let's say DictItems).

**Please tell us about your environment:**
* **Angular version:** 2.4.6
* **PrimeNG version:** 2.0.0-rc.3
* **Browser:** [all] 
* **Language:** [all]

**Comment by cagataycivici** [comment]
Can't you use templating to customize the content of node?

**Comment by cagataycivici** [comment]
TreeTable will be reimplemented, please monitor;

#4813
