### ISSUE TITLE
Page rerenders when moving mouse if p-dialog is used in according component

### ISSUE THREAD

**Issue by divid3byzero** [primefaces/primeng#2110]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/dK9SQGhe3RwtJpcZVU7g?p=preview

**Current behavior**

- Add p-dialog to any component
- Add logging via console.log() to any function that is called in the component template
- Move mouse across page in browser window

**Expected behavior**

- Page is not rendered every time the mouse is moved across the page

**Minimal reproduction of the problem with instructions**
- Bug is reproducible with the above Plunker. Start Plunker, move mouse over app and check log.

**What is the motivation / use case for changing the behavior?**

- Performance

**Please tell us about your environment:**

Operating system: macOS, Windows
IDE: IntelliJ, Visual Studio Code
Package manager: npm
HTTP server: App started via Angular CLI

* **Angular version:** 2.4.0 and 2.4.7

* **PrimeNG version:** 2.0.0 and 1.1.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 - Chrome

* **Language:** TypeScript 2.0.2

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
