### ISSUE TITLE
Parallel file uploads

### ISSUE THREAD

**Issue by pmeems** [primefaces/primeng#2112]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

I select multiple files and when I hit the upload button all files are send at once.

**Expected behavior**

Like Dropzone.js don't send all files at once but one by one or any other setting.
This will increase stability, less problems when the network has a glitch and in our case when a job is waiting for the files to arrive the job can start processing the first files while the rest of the files are still uploading.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Our users are allowed to upload lots of files up to 3 GB in total.
Sending all files in one request is unreliable and time consuming.

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

We're still using PrimeNG v1. But if needed we can upgrade to v2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All browsers
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All

* **Node (for AoT issues):** `node --version` =

**Comment by ewinchen** [comment]
any update about this issue? I think this feature is useful because nowadays servers could have a size limitation per request, if upload files at once, it would exceed the limitation, however, parallel upload would not.

**Comment by yigitfindikli** [comment]
We'll reconsider if there is more community feedback on this. Thank you for your report.
