### ISSUE TITLE
Allow HTML in p-confirmdialog component message

### ISSUE THREAD

**Issue by PCASME** [primefaces/primeng#2116]
**I'm submitting a ...**
```
[   ] bug report
[ X ] feature request
[   ] support request
```

PR: [#2115]

**Current behavior**

Use of the _interpolation binding syntax_ with the `message` property in the `p-confirmdialog` component.

`<span class="ui-confirmdialog-message">{{message}}</span>`

**Expected behavior**

Use _property binding syntax_ with the **innerHTML** property instead.

`<span class="ui-confirmdialog-message" [innerHTML]="message"></span>`

**What is the motivation / use case for changing the behavior?**

More flexibility and styling for confirmation messages.

**Please tell us about your environment:**

* macOS Sierra (version 10.12.3)
* Visual Studio Code
* Node v7.5.0
* npm 4.1.2

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [all]

 
* **Language:** [TypeScript 2.1.6]

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
