### ISSUE TITLE
Host on cdnjs?

### ISSUE THREAD

**Issue by hare1039** [primefaces/primeng#2118]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
Hi,
I'm a member of cdnjs, and we receive a request to add primeng into our service.
https://github.com/cdnjs/cdnjs/issues/10134 

Can primeng host in a cdn environment?
If it can, please tell us what files should we host (including information about previous versions will speed up the process) !

Thank you for any help you provide!

**Comment by cagataycivici** [comment]
Thank you, github repo does not contain any file as at build time to npm, binaries are generated. Is it possible to get them from unpkg? If so I think they are;

https://unpkg.com/primeng@2.0.0/resources/themes/bootstrap/theme.css
https://unpkg.com/primeng@2.0.0/resources/themes/omega/theme.css
https://unpkg.com/primeng@2.0.0/resources/primeng.min.css
https://unpkg.com/primeng@2.0.0/primeng.js

**Comment by hare1039** [comment]
Thank you for the reply!

**Comment by hare1039** [comment]
About the theme files, should we add all the themes or only the two themes you mention?

**Comment by hare1039** [comment]
@cagataycivici Sorry to bother you again.
Can I make sure what file should we put on cdnjs?
Do you think the following list is enough using in browser?
https://unpkg.com/primeng@4.0.1/
```
primeng.js
primeng.js.map
components/
resources/
```
Thanks!
