### ISSUE TITLE
Having build issues due to primeng not updating zone.js version number.

### ISSUE THREAD

**Issue by ascalonwa** [primefaces/primeng#212]
npm ERR! peerinvalid The package zone.js does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angular2@2.0.0-beta.15 wants zone.js@^0.6.10
npm ERR! peerinvalid Peer primeng@1.0.0-beta.2 wants zone.js@0.6.6

**Comment by cagataycivici** [comment]
Please see;

https://github.com/primefaces/primeng/issues/206
