### ISSUE TITLE
Tooltip usability problem with appendTo set to "target"

### ISSUE THREAD

**Issue by saulimus** [primefaces/primeng#2125]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

http://plnkr.co/edit/D1AK7i

**Current behavior**

1. Use pTooltip with an element, with appendTo set to "target".
1. Hover over the **center** of the element, showing a tooltip on the right.
2. Move mouse cursor to the right, over the tooltip.
3. The tooltip doesn't hide.

**Expected behavior**

The tooltip should always disappear when the mouse hovers over it. The behavior is correct when appendTo is set to "body".

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/CGvuta7tLkmROsdFvME2

**What is the motivation / use case for changing the behavior?**

The option appendTo="target" needs to be used in my case as the elements the tooltips are used for are in a scrollable container. (see documentation for p-tooltip)
The user needs to be able to select an adjacent button as easily as with appendTo="body".

**Please tell us about your environment:**

* **Angular version:** 2.2.4

* **PrimeNG version:** 2.0.0 Final

* **Browser:** [ all ]

**Comment by saulimus** [comment]
I was able to work around the problem by making my own fork of the tooltip directive and adding this line after tooltipText element creation:
`tooltipText.addEventListener('mouseenter', (event) => {
    this.hide();
});`

**Comment by cagataycivici** [comment]
Discussed but we need more feedback on this, so closing until then. Some seem to prefer tooltip staying on hover itself.
