### ISSUE TITLE
Bug(Calendar): input not cleared when clearing the model after entering date via keyboard

### ISSUE THREAD

**Issue by cacogr** [primefaces/primeng#2127]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Entering a date in Calendar input via keyboard and then clearing the corresponding model programatically does not clear the input.

**Expected behavior**
To clear the input the same way it does as if the date was entered using the calendar popup.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/mgUHzIdm87H4JJRQsQon?p=preview

Enter a date in format dd/mm/yyyy with your keyboard and click 'Clear' -> input not cleared.
Do the same entering the date from the calendar popup -> input cleared.

* **Angular version:** 2.4.X

* **PrimeNG version:** 2.0.1

* **Browser:** Chrome 56 (other browsers not tested)
 
* **Language:** TypeScript 2.0

**Comment by external-olgierd** [comment]
A fix for #2081 should also resolve this issue. Pull request added.

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview

**Comment by cagataycivici** [comment]
@Mrtcndkn Confirm please.

**Comment by Mrtcndkn** [comment]
I tried it locally with the latest version of PrimeNG (4.1.0-RC2) and Angular (4.2.3) and it's working. @cagataycivici
