### ISSUE TITLE
DataTable Memory problem after update to 2.0.1

### ISSUE THREAD

**Issue by michal-kindl** [primefaces/primeng#2133]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

**Current behavior**

After upgrade to PrimeNG 2.0.1 (from 2.0.0) I encounter following error:
EXCEPTION: Error in ./TableBody class TableBody - inline template:14:20 caused by: Maximum call stack size exceeded

The problem seems to be in DataTable component when I use templates.
After rollback to version 2.0.0 it works. There has been no code changes, just the upgrade.

**Expected behavior**

Just work as before update.

**Minimal reproduction of the problem with instructions**

I am using p-dataTable with column templating, it is actually a small table with aprox. 20 rows.
There is a custom component inside a column template.
On the left is a result in 2.0.0, on the right in 2.0.1. 
![primeng_datatable](https://cloud.githubusercontent.com/assets/20546439/23212404/e0a601d0-f906-11e6-978e-1277f5456dd9.png)

[Model.zip](https://github.com/primefaces/primeng/files/793419/Model.zip)

**Please tell us about your environment:**

Windows 8 Enterprise, Visual Studio Code, Node - Express

* **Angular version:** 2.4.1

* **PrimeNG version:** 2.0.1

* **Browser:** 

Chrome v. 56.0.2924.87 
* **Language:** TypeScript 2.1.6,  ES6

* **Node (for AoT issues):** `node --version` =  v6.9.5

Thank you in advance for your support.

**Comment by buchatsky** [comment]
I confirm this. The problem is related to row selection:
`<p-dataTable #dt [value]="items" selectionMode="single" [(selection)]="selectedItem">
	<p-column field="CompanyName" header="Company Name"></p-column>
</p-dataTable>`
But (for me) the problem arises only when I use Breeze entity objects returned from its EntityManager. When I switch code to constant local array - selection works correctly.
And it worked perfectly with PrimeNg 2.0.0

**Comment by michal-kindl** [comment]
Yes, I forgot to mention, that I am using Breeze...I go to check it.

**Comment by michal-kindl** [comment]
Yes!!! 
Thank you for fast fix of the problem, I confirm it works now with 2.0.2.
