### ISSUE TITLE
How to show autocomplete suggestions panel after onSelect

### ISSUE THREAD

**Issue by ydubey** [primefaces/primeng#2135]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[x] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/D1AK7i

**Current behavior**
When calling `this.autoCompleteComponent.show()` in `onSelect` method, the panel is not shown.

**Expected behavior**
`this.autoCompleteComponent.show()` should re-evaluate `completeMethod` and show suggestions panel.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
I want to conditionally present next suggestions once a suggestion is accepted. When calling `show` in `onSelect` method, the panel does not stay open. I would like to trigger re-evaluation of `completeMethod` and show suggestions panel programatically.

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Please use forum for support requests.
