### ISSUE TITLE
Datatable Scrollable set to true column header misaligned with dynamic width and height

### ISSUE THREAD

**Issue by anirudh-jagithyala** [primefaces/primeng#2137]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.
![image](https://cloud.githubusercontent.com/assets/9027951/23239962/a4c425ae-f927-11e6-9e38-93f75f27f9ff.png)

http://plnkr.co/rvY2SLmQG0wdrkRFeiYb
http://plnkr.co/edit/rvY2SLmQG0wdrkRFeiYb?p=info

**Current behavior**

A Scrollable Table which changes the height and width based on page size mis align on the headers to datatable.
**Expected behavior**

irrespective of dynamic heigh and width of the Scroll region Headers should be align to body.

**Minimal reproduction of the problem with instructions**
Sample code available here

http://plnkr.co/rvY2SLmQG0wdrkRFeiYb
http://plnkr.co/edit/rvY2SLmQG0wdrkRFeiYb?p=info

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by anirudh-jagithyala** [comment]
similar to  #487 , but problem persists for dynamic columns with dynamic height/width based on page size .

**Comment by Ketec** [comment]
Can confirm - bootstrap theme (perhaps others too).
I have 100% width set and the header leaves 17px margin when there is not enough data in the table below to show the scrollbar. This causes header to get misaligned.

I do not have resizeable columns enabled (but for some reason they still ignore  given widths and resize themselves regardless).

**Comment by BartoszBaczek** [comment]
This is happening to me as well. I have set width of each column with 
`<p-column [style]="{'width':'300px'}">` .  

Also, my `<p-datatable>` is scrollable is  set to true.

**Comment by jibin-tj** [comment]
same problem here. Any updates on this?

**Comment by Ketec** [comment]
The 4.0.1 updated the code for scrollbar detection it seems. i do not get that issue anymore.

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview

**Comment by Rchoudhary-tcs** [comment]
@cagataycivici What about the misalignment in the "RTL" direction.Is that will be taken care in the next release.Or is there any workaround for the same.In "LTR" direction,i am not having any misalignment issues.

**Comment by randomgithubdev** [comment]
Was the problem solved? Is there any workaround/ fix? 
I cannot get it to work properly

**Comment by anuradhamudalige** [comment]
For RTL direction misalignment, I could fix this inside ngAfterViewInit

`const elements = this.elem.nativeElement.querySelectorAll('.ui-datatable-scrollable-body');
    let initValue = 0;
    const headerBox = this.elem.nativeElement.querySelectorAll('.ui-datatable-scrollable-header-box');
    const table = headerBox[0].children[0] as any;
    elements[0].addEventListener('scroll', () => {
      if (headerBox && headerBox[0].style && this.isLanguageChanged) {
          const marginLeft = parseInt(headerBox[0].style.marginLeft, 10);
          headerBox[0].style.marginRight = '0px';
          if (!this.scrolled) {
            this.scrolled = true;
            initValue = marginLeft;
          }
          table.style.marginRight = (initValue - marginLeft) + 'px';
      }
    });`
