### ISSUE TITLE
Rows disappear when virtual scrolling datatable

### ISSUE THREAD

**Issue by dereklin** [primefaces/primeng#2138]
Go to http://www.primefaces.org/primeng/#/datatable/scroll, scroll on the virtual scrolling table, the rows will disappear during scrolling.

**Comment by upmauro** [comment]
It's not a bug. The example show a virtual scroll with "lazy" option enabled. To show values when lazy is enabled it's necessary user finish scroll.

**Comment by DanGraZisson** [comment]
I'm experiencing the same in my own template, without enabling the lazy option.

**Comment by Mrtcndkn** [comment]
It is for demo purposes if you are using the same code snippet from the live showcase and it's expected behavior.
