### ISSUE TITLE
Slider handle: slider handle still follows mouse even after mouse button is released

### ISSUE THREAD

**Issue by lebnic** [primefaces/primeng#2144]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/A1A9nO

**Current behavior**

When clicking multiple time on slider-handle, handle will keep following cursor, even after click is released...

**Expected behavior**

handle should stop following cursor after click is released.

**Minimal reproduction of the problem with instructions**

Using this demo, http://plnkr.co/edit/A1A9nO follow these steps:
- Position your cursor over slider-handle
- Quickly, click mouse left button 4 times and hold after the 4th click
- Mouse the cursor around to change the slider position
- Release mouse button
- Move mouse cursor away. Observe slider value keeps following the cursor: This is a bug.

**What is the motivation / use case for changing the behavior?**

Most user are using slider via the slider handle; However, the slider-handle can be "hard" to grab with the mouse (for some reason) and user might click "all over the place" until they grab it. Bottom line is; I've experienced this bug many time while I was developing, and even another user at my job have reported this bug to me, so, it happens and it is annoying...

**Please tell us about your environment:**

Linux

* **Angular version:** 2.0.X

3.10

* **PrimeNG version:** 2.0.X

2.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview

**Comment by lebnic** [comment]
@cagataycivici wrong plunker link
