### ISSUE TITLE
Calendar doesnt play well with OnPush change detection strategy

### ISSUE THREAD

**Issue by external-olgierd** [primefaces/primeng#2148]
I'm submitting a ...

[x ] bug report => Search github for a similar issue or PR before submitting

http://plnkr.co/edit/i58dTl1dQgrNmKQedcT5?p=preview

Current behavior
When <p-calendar> is used within the component with OnPush change detection strategy, the closing of the datepicker popup is not working as expected:
- datepicker is not closing when date is selected (need to click twice)
- datepicker is not closing when focus is lost from the input field/when user clicks anywhere else on the screen

Expected behavior
Datepicker is closed when date is selected or when user clicks anywhere else on the screen.

Minimal reproduction of the problem with instructions
It affects any <p-calendar> component that is added to the component with OnPush change detection strategy. See the above plunker.

What is the motivation / use case for changing the behavior?
OnPush change detection strategy is widely used in Angular2 apps for performance reasons so Calendar component should behave correctly in these cases.

Angular version: 2.0.0 and above (incl. most recent one)

PrimeNG version: 2.0.1

Browser: all

**Comment by alialtun14** [comment]
Autocomplete component behaves in a similar way too.

**Comment by external-olgierd** [comment]
@alialtun14 I suggest you log a new issue with relevant plunkr for autocomplete component. Probably the best way to get it fixed quickly.

**Comment by variable-content** [comment]
@alialtun14 I'm running into the same issue, have created this issue for it: https://github.com/primefaces/primeng/issues/2226

**Comment by alialtun14** [comment]
Thank you.

**Comment by CelsoSantos** [comment]
Hi everyone,
Hi @cagataycivici 

I'm still having this issue on 2.0.6...

I have a calendar that I don't have any issue firing the focus event, however, the calendar consistently requires two clicks to select a date.

I did notice that the calendar css classes goes from having `ui-inputwrapper-focus` class to not having it **on the first click**, but only the **second does actually change something and makes the onSelect event fire.**

Wasn't this issue supposed to fix that?
