### ISSUE TITLE
dropdown filter in scrollable table is not showing

### ISSUE THREAD

**Issue by ASK83** [primefaces/primeng#2152]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting

```

**Plunkr Case (Bug Reports)**
Following plunker shows the problem.

http://plnkr.co/edit/YFRONc?p=preview

**Current behavior**
When adding a drop down filter to a scrollable table the drop down filter will be hidden behinde the table even if the overflow is set to visible for the column.

**Expected behavior**
To show the drop down list in a scrollable table.

**What is the motivation / use case for changing the behavior?**
When we have a scrollable table means it has a large data so filtering the values that have categories would be beneficial. 

**Please tell us about your environment:**
vscode

* **Angular version:** 2.0.X
2.4.8

* **PrimeNG version:** 2.0.X
2.0.1

* **Browser:** [all 
 
* **Language:** [all 

* **Node (for AoT issues):** `node --version` =   NA

**Comment by anirudh-jagithyala** [comment]
You need to be using 'appendTo' attribute on your drop down. 

appendTo="body"

![image](https://cloud.githubusercontent.com/assets/9027951/23374772/f3c9de96-fce2-11e6-8bc2-9f5dac2bfaa1.png)

**Comment by ASK83** [comment]
Thanks a lot for your comment @anirudh-jagithyala. That was my problem.

**Comment by ravikzm** [comment]
I have followed all suggestions like using overflow : visible or appendTo="body" but nothing working for me.
`  <p-column [style]="{'width':'5%','overflow':'visible'}" [sortable]="false" field="Status" header="Status" [filter]="true" filterMatchMode="equals" >
                            <ng-template pTemplate="filter" let-itemcol>
                                <p-dropdown [options]="statusList"  [style]="{'width':'100%','overflow':'visible'}" appendTo="body" (onChange)="dtaction.filter($event.value,itemcol.field,itemcol.filterMatchMode)" styleClass="ui-column-filter"></p-dropdown>
                            </ng-template>
                        </p-column>`
![image](https://user-images.githubusercontent.com/29487440/32146779-254c8f1e-bc9a-11e7-8de1-63377f76610a.png)

Please help to resolve it
