### ISSUE TITLE
[SimpleFeatureRequest]Add a Cell style function like row style function "rowStyleClass" in DataTable component.

### ISSUE THREAD

**Issue by Lyoko-Jeremie** [primefaces/primeng#2157]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

Current have a row style function "rowStyleClass", but not have a cell style function maybe like "cellStyleClass" and so on.

**Expected behavior**

add a cellStyleClass that : 
"gets the row data and row index as parameters and returns a style class for the <b>cell</b>".
that function can return a style class to change cell background-color and so on.

**Minimal reproduction of the problem with instructions**

only add a cellStyleClass like rowStyleClass at the &lt;td&gt; element in datatable.ts 's line 162: TableBody compoment's template html. and add support function in the DataTable compoment like getRowStyleClass function.

**What is the motivation / use case for changing the behavior?**

example, change cell background-color to make a color-full timetable.
use <code>div</code> in template cannot fill the full cell.

**Please tell us about your environment:**

latest WebStorm

**Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by Lyoko-Jeremie** [comment]
i use follow hack directive to solution it, so, i think i dont need it now !!

```ts
import {Directive, ElementRef, OnInit, Renderer, Input, OnDestroy, Output, EventEmitter} from '@angular/core';
import * as _ from 'lodash';
import {ReplaySubject} from "rxjs";

@Directive({
    selector: '[ccParentsSetter]'
})
export class ParentsSetterDirective implements OnInit,OnDestroy {

    @Input('classObject') set classObject(value: any) {
        this.classObjectSubject.next(value);
    }

    @Input('styleObject') set styleObject(value: any) {
        this.styleObjectSubject.next(value);
    }

    @Input('attributeObject') set attributeObject(value: any) {
        this.attributeObjectSubject.next(value);
    }

    // (click) function
    @Input() onClickParam: any;
    @Output('ccParentsSetterOnClick') onClick: EventEmitter<any> = new EventEmitter();
    private onClickListenUnhookFunc: Function|undefined;

    // cold Subject
    // use to dynamic flush all the thing
    classObjectSubject: ReplaySubject<any> = new ReplaySubject();
    styleObjectSubject: ReplaySubject<any> = new ReplaySubject();
    attributeObjectSubject: ReplaySubject<any> = new ReplaySubject();

    constructor(private elementRef: ElementRef,
                private renderer: Renderer) {
    }

    ngOnInit() {
        // find td
        let parentFinder = (node: Node, level: number = 0): Node|null => {
            return (node && level < 10) ? (
                    node.nodeName == "TD" ? node : parentFinder(node.parentNode, level + 1)
                ) : null;
        };
        let node = parentFinder(this.elementRef.nativeElement);
        // inject all the thing
        if (node) {
            this.onClickListenUnhookFunc = this.renderer.listen(node, "click", () => {
                this.onClick.emit(this.onClickParam);
            });
            this.classObjectSubject.subscribe(
                next => {
                    _.forIn(next, (v, k) => {
                        this.renderer.setElementClass(node, k, v);
                    });
                }
            );
            this.styleObjectSubject.subscribe(
                next => {
                    _.forIn(next, (v, k) => {
                        this.renderer.setElementStyle(node, k, v);
                    });
                }
            );
            this.attributeObjectSubject.subscribe(
                next => {
                    _.forIn(next, (v, k) => {
                        this.renderer.setElementAttribute(node, k, v);
                    });
                }
            );
        }
    }

    ngOnDestroy() {
        // must release click functuin
        if (this.onClickListenUnhookFunc) {
            this.onClickListenUnhookFunc();
        }
    }

}

```

**Comment by Lyoko-Jeremie** [comment]
close it, please :(

**Comment by supriya2992** [comment]
I have found a way to change background the color of the column.
Please let me know if I have done it the correct way or need some improvement.
Below is my code :

**HTML Code:**
```
<p-column  header="ID" >
	<template let-data="rowData" pTemplate="body">
        	<span #x> {{ getColor(x,data) }} {{ data.id }}</span>
	</template>
</p-column>
```


**TS Code:**
```
// just a sample code, to assign background color depending on our required criteria
getColor(x, data) {
    var color: string;
    if (data.status === 1) {
      color = 'lightgreen';
    } else if (data.status === 2) {
      color = 'lightblue';
    } 
    x.parentNode.parentNode.style.background = color; // x.parentNode.parentNode accesses the <td> element of table :)
  }
```

**Here is the output:**
![bg_color_td](https://cloud.githubusercontent.com/assets/22049173/26388344/5e5e4d74-4071-11e7-95c5-9ba3bae6577c.PNG)


Hope this helps!!
Thanks

**Comment by Lyoko-Jeremie** [comment]
@supriya2992 it's work well but i dont like it as ParentsSetterDirective way.
because this is a hack way and cannot work well dom struct change.

**Comment by cagataycivici** [comment]
Better to use column style and styleClass.

**Comment by gjenner** [comment]
can you post an example using column style and styleClass that accomplishes the same results please

**Comment by Lyoko-Jeremie** [comment]
@gjenner But if you need control every cell's color, the column style will not enough. Example to write a simple colorfull task table.

**Comment by gjenner** [comment]
you stated "Better to use column style and styleClass, just looking for an example of @supriya2992 's solution in your suggested method

**Comment by Lyoko-Jeremie** [comment]
yea, I use the ParentsSetterDirective as long as 4 mouth. ㄟ( ▔, ▔ )ㄏ

**Comment by pantonis** [comment]
@cagataycivici  I use styleClass 

```
[styleClass]="checkStyleClass"
 
and in ts.

public checkStyleClass(item: Client){
...
}
```

but the function is not fired

**Comment by bhaidar** [comment]
@pantonis  try to use 
    
    [styleClass]="checkStyleClass()"

**Comment by denniseffing** [comment]
I think this should be reopened, since the solution mentioned here is still just a hacky workaround and nobody could post a working solution with styleClass.

**Comment by bgsavage** [comment]
+1

**Comment by denniseffing** [comment]
I guess the issue isn't a "simple feature request" after all since the latest pull request got denied because of performance impacts when calling a function for every table cell.

See #4463.

@cagataycivici Would you please reopen this issue. I need more attention for this feature. As of now, I am still using the hacky workaround described above but I can't add a new feature request for my application (dynamically configurable columns) without losing colored cells (which are mandatory) because the workaround is based on angular template reference variables which are static only and can't be dynamic.

**Comment by Lyoko-Jeremie** [comment]
@denniseffing I think your question need a way to control any special table cell by the table compoment ref on parents compoment's TS code.
