### ISSUE TITLE
p-tree children icons shows when there are no children in 2.0.1

### ISSUE THREAD

**Issue by ASK83** [primefaces/primeng#2164]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**
Here is the pluncker showing the bug!
http://plnkr.co/edit/Cibh1l?p=preview

**Current behavior**
This is a small bug, that was working in previous versions but with 2.0.1 it is showing icons besides the nodes that have no children.

**Expected behavior**
Not to show the icons for terminal nodes. 

**Minimal reproduction of the problem with instructions**
![image](https://cloud.githubusercontent.com/assets/17345249/23364043/1e34b7c0-fcc3-11e6-9726-8b047691df90.png)

**What is the motivation / use case for changing the behavior?**
More consistent UI at the terminal nodes. 

* **Angular version:** 2.0.X
2.4.8

* **PrimeNG version:** 2.0.1

* **Browser:** [all ]
 
* **Language:** [all]

**Comment by upmauro** [comment]
Have an error in your code. You are using CSS from version 2.0.0, but using npm package 2.0.1, please change your CSS imports to 2.0.1 to see the problem solved.

**Comment by ASK83** [comment]
Oh, Thanks a lot @upmauro for catching that!
