### ISSUE TITLE
Templating support for Multiselect component

### ISSUE THREAD

**Issue by waldo2188** [primefaces/primeng#2165]
**I'm submitting a** : feature request.
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
The multiselect show a list of simple string value with a checkbox associated.

**Expected behavior**
It would be great if we can templating the manner where the value is shown. Like it is the case in the
Dropdown component.

**What is the motivation / use case for changing the behavior?**
We have to show a list of address at our users, and this address need to be presented on multiple lines and we have somes condition for presenting or not somes value. That's why a templating for the Multiselect Component would be a great feature.

* **Angular version:** 2.4.8

* **PrimeNG version:** 2.0.1

**Comment by cagataycivici** [comment]
<img width="489" alt="screen shot 2017-08-22 at 15 03 37" src="https://user-images.githubusercontent.com/686247/29564829-1487eff8-874c-11e7-8928-fd7c6830d746.png">

**Comment by theNotoriousHxc** [comment]
Is there any way to add a button right beside the input text? or something like a sticky footer with a button?
