### ISSUE TITLE
p-autoComplete component performance is low

### ISSUE THREAD

**Issue by Nattujessy** [primefaces/primeng#2166]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

 
**Current behavior**

When i have 20+ rows with autocomplete component, the click event is  take more than 4 seconds to get focused.
when i comment autocomplete component in data table it was working fine.
Earlier i had a same kind of problem with dropdown but primeng2.0 was improved the performance with dropdown. Similer kind of stuff are needed for autocomplete component as well.

**Expected behavior**

No performance issue with autocomplete component inside datatable rows.

**Minimal reproduction of the problem with instructions**
 
**Steps to reproduce**

1. Create the datatable with 13 columns (2 of them are autocomplete, 5 of them are dropdown, remains are input filed.
2. Add 20+ rows to it.
3. Click any drodown or text box component. You will see the delay time to get focused.
4. If u remove the autocomplete components you will see the fastness.
**Please tell us about your environment:**

* **Angular version:** 2.4.8

* **PrimeNG version:** 2.0.1

* **Browser:** [all]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =  6.9.5

**Comment by Miosss** [comment]
+1, performance with a few (20+) rows and autocomplete is worse that using paper and pen
