### ISSUE TITLE
Event is not defined

### ISSUE THREAD

**Issue by kamalkech** [primefaces/primeng#2167]
**Please tell us about your environment:**
Windows 10

* **Angular version:** 2.0.X
universal-cli: 1.0.0-alpha.universal.3
angular-cli: 1.0.0-beta.23
node: 6.10.0
os: win32 x64

* **PrimeNG version:** 2.0.X
"primeng": "^2.0.0-rc.2",

I get this error : 

`C:\Projets\Angular\ung-universal\node_modules\primeng\components\tooltip\tooltip.js:145      
        __metadata('design:paramtypes', [Event]),                                            
                                         ^                                                   
                                                                                             
ReferenceError: Event is not defined                                                         
    at C:\Projets\Angular\ung-universal\node_modules\primeng\components\tooltip\tooltip.js:14
5:42                                                                                         
    at Object.<anonymous> (C:\Projets\Angular\ung-universal\node_modules\primeng\components\t
ooltip\tooltip.js:175:2)                                                                     
    at Module._compile (module.js:570:32)                                                    
    at Object.Module._extensions..js (module.js:579:10)                                      
    at Module.load (module.js:487:32)                                                        
    at tryModuleLoad (module.js:446:12)                                                      
    at Function.Module._load (module.js:438:3)                                               
    at Module.require (module.js:497:17)                                                     
    at require (internal/module.js:20:19)                                                    
    at Object.<anonymous> (C:\Projets\Angular\ung-universal\node_modules\primeng\primeng.js:6
9:10)                                                                                        `

Any idea ?

**Comment by cagataycivici** [comment]
Can you try with 2.0.2?

**Comment by kamalkech** [comment]
@cagataycivici :  No compatible version found: primeng@2.0.2

**Comment by StefH** [comment]
I've same issue when trying to include primeng in my example project : https://github.com/StefH/AngularTestPrimeNG

**Comment by akashs25** [comment]
hey did you get solution for the same?

**Comment by cagataycivici** [comment]
You probably need to add following to your tsconfig.json;

```
"lib": ["dom","es6"],
```

**Comment by StefH** [comment]
I was able to get all working. See my project.

**Comment by EAbychkov** [comment]
@StefH How did you solve this?

**Comment by StefH** [comment]
Did you check my project? https://github.com/StefH/AngularTestPrimeNG

**Comment by EAbychkov** [comment]
@StefH Yes, but I can't figure out **what exactly** can help me to solve this problem.

**Comment by StefH** [comment]
Maybe in:

`AngularCliApp/src/tsconfig.app.json`
and
`AngularCliApp/tsconfig.json`

See commit:
https://github.com/StefH/AngularTestPrimeNG/commit/a848f3d384a7a4af6f268c3414267de6326c9e48

**Comment by imichelakos** [comment]
primeng/components/tooltip/tooltip.ts:34
    onMouseEnter(e: Event) {
                    ^
ReferenceError: Event is not defined

Angular: 4.3.0
PrimeNG: 4.0.0-rc.2

Any thoughts? 
"lib": ["dom","es6"] doesn't solve the issue

**Comment by san4ezz87** [comment]
@imichelakos I have same issue

**Comment by san4ezz87** [comment]
@imichelakos did you solve it?

**Comment by mistrynilesh** [comment]
I am also facing same issue. any update ?

**Comment by secondcircle** [comment]
I am getting the same Issue.
