### ISSUE TITLE
Add disabled input for Fieldset

### ISSUE THREAD

**Issue by ilianiv** [primefaces/primeng#2168]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Fieldset has no disabled property.

**Expected behavior**
Fieldset has disabled property.

**What is the motivation / use case for changing the behavior?**
I need it to disable a block of form controls at once.

* **PrimeNG version:** 2.0.1

* **Browser:** [all]

 
* **Language:** [all]

**Comment by cagataycivici** [comment]
It is not common to disable panel components, ui-state-disabled just adds visuals with opacity, components inside will still be enabled. I'd suggest disabling the children of fieldset manually and use styleClass of fieldset to add ui-state-disabled instead.
