### ISSUE TITLE
onShow and onHide events for Dropdown

### ISSUE THREAD

**Issue by mani0608** [primefaces/primeng#2172]
I'm submitting a ...

```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When using `<p-dropdown>` inside editor template of `<p-datatable>` there is no option to load content into the dropdown based on current rowdata.

**Expected behavior**
It would be really useful if `<p-dropdown>` support _onShow/OnOpen_ events

**Usecase**
I need to add new options when the dropdown component is loaded/opened based on current rowData inside template.

**Comment by mani0608** [comment]
Is there any chance that this feature could be included ??

**Comment by TomDn** [comment]
+1

**Comment by DesertFoxNV** [comment]
Very interested in this feature (onShow/OnOpen/OnClose events for p-dropdown). Looks like it was scheduled for 4.1.1. Did it not make the cut?
