### ISSUE TITLE
DropDown breaks

### ISSUE THREAD

**Issue by shubhijain106** [primefaces/primeng#2173]
I'm having an issue getting a dropdown to work as a filter. The drop down is there as long as I do not use template tags.Also clicking on dropdown  does nothing. Am I missing something here or is this a bug? I've included some of the code from my component, some of the other classes (data provider, reducer, etc.) that are not relevant are not shown.

**_basic-grid.component.html_**

<p-dataTable [value]="cars" [rows]="20" [paginator]="true">
    <p-column field="vin" header="Rule Name"></p-column>
    <p-column field="year" header="Order" sortable="true"></p-column>
    <p-column field="brand" header="Description" [filter]="true" [style]="{'overflow':'visible'}"  filterMatchMode="equals">
  <template pTemplate="filter" let-col>
			<p-dropdown [options]="brands" [style]="{'width':'100%'}" (onChange)="dt.filter($event.value,col.field,col.filterMatchMode)" styleClass="ui-column-filter"></p-dropdown>
		</template>
    </p-column>
    <p-column field="color" header="Rule Type"></p-column>
</p-dataTable>

**_basic-grid-component.ts_**

import { Component, OnInit, ViewEncapsulation, ChangeDetectionStrategy } from '@angular/core';
import {MyCustomType} from '../shared/service/mycustom.type';
import {CarService} from '../shared/service/car-service';
import { Dropdown, SelectItem} from 'primeng/primeng';

@Component({
  selector: 'app-basic-grid',
  templateUrl: './basic-grid.component.html',
  styleUrls: ['./basic-grid.component.css'],
  encapsulation: ViewEncapsulation.None,
 
})
export class BasicGridComponent implements OnInit {
cars: MyCustomType[];
 brands: SelectItem[];

  constructor(private carService:CarService) { }

  ngOnInit() {
    this.carService.getCarsMedium().then(cars => this.cars = cars);
     this.brands = [];
        this.brands.push({label: 'AutoMatch', value: 'AutoMatch'});
        this.brands.push({label: 'AutoPost', value: 'AutoPost'});
        this.brands.push({label: 'AutoAssign', value: 'AutoAssign'});
   

}

  }

**Comment by ASK83** [comment]
check out my posted issue with a plucker attached that shows a fixed version of showing drop down filter in a table. Maybe that can help you figure out the problem. 
https://github.com/primefaces/primeng/issues/2152

**Comment by shubhijain106** [comment]
Nope, it didn't work

**Comment by anirudh-jagithyala** [comment]
@shubhijain106 
You nee to embed the drop down in template with <template pTemplate="filter">
Check the already working example @ http://www.primefaces.org/primeng/#/datatable/filter

**Comment by sudheerj** [comment]
I can't replicate the issue. Please try with latest versions and comment here for any issue.
