### ISSUE TITLE
Display dropdown on select key

### ISSUE THREAD

**Issue by Nattujessy** [primefaces/primeng#2174]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Have a look at following plunker.

http://plnkr.co/edit/D5MkPwvRlXiGF2yQhZbk?p=preview

**Current behavior**

Viewing dropdown list by pressing space key is not working inside datatable.

**Expected behavior**

To show options while pressing space key.

**Minimal reproduction of the problem with instructions**
 - In the plunker just click the input fild for Name and then move to dropdown component by pressing tab key.
- Now press space key to show the list.
Note: mouse click is working fine.. Only the problem is when navigating through keyboard.

 
 
* **Angular version:** 2.4.8

* **PrimeNG version:** 2.0.1

* **Browser:** [all ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =    6.9.5

**Comment by zubycodes** [comment]
I came across same issue ..
please someone fix or reply !!

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
