### ISSUE TITLE
DataTable filter is not cleared when ::-ms-clear is clicked

### ISSUE THREAD

**Issue by StevenLiekens** [primefaces/primeng#2179]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
No Plunkr but the issue exists even in the API sample
http://www.primefaces.org/primeng/#/datatable/filter

**Current behavior**
Internet Explorer 11 (and possibly IE10 and Edge) add a clear button to input fields. When that button is clicked, the global filter is cleared but the DataTable does not handle that event.

![ms-clear](https://cloud.githubusercontent.com/assets/1583241/23413312/90586818-fdd8-11e6-91bb-073790578d70.gif)

**Expected behavior**

When the ms-clear button is clicked, the DataTable filter should be reset.

The current workaround is to press the Return key after clicking ms-clear.

**Minimal reproduction of the problem with instructions**

Open the DataTable filter sample in IE10 or IE11
http://www.primefaces.org/primeng/#/datatable/filter

**What is the motivation / use case for changing the behavior?**

Users are confused

**Please tell us about your environment:**

Tested in IE11 on Windows 7

* **Angular version:** 2.4.8

* **PrimeNG version:** 2.0.1

* **Browser:** Internet Explorer 11

 
* **Language:** all

* **Node (for AoT issues):** `node --version` = not applicable

**Comment by StevenLiekens** [comment]
Bump

**Comment by StevenLiekens** [comment]
The fundamental problem here is that filtering is applied on `keydown` instead of on `input` or on `change`. Any way to change the filter without pressing a key breaks change detection.

cc @cagataycivici @Mrtcndkn

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/commit/c4b5549962757fbea6a6ccfe05813018f7edd183

Fixes this as well.

**Comment by StevenLiekens** [comment]
@cagataycivici I just updated to 4.1.0 and the issue still exists when using `[globalFilter]="inputRef"`
