### ISSUE TITLE
Add onSelectionChange to OrderList

### ISSUE THREAD

**Issue by simdevmon** [primefaces/primeng#2180]
**I'm submitting a ...**
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When the selection of the order list changes, there is no way to get informed about that.

**Expected behavior**
OrderList should support an onChange event similar to Dropdown, Spinner, ... which gets fired, when the current selection has changed.

**What is the motivation / use case for changing the behavior?**
I want to implement a master-detail view of items, which can be sorted. When the selection of the order list changes, I want to display details of the selected item in a separate area.

**Comment by Mrtcndkn** [comment]
There is onReorder method for orderlist when the order changed it will be invoked it can solve your problem.

**Comment by simdevmon** [comment]
onReorder does not help me, because I have an additional button outside of the component to delete the current selection for example. So I need to be informed when the selection changes (no reorder).
