### ISSUE TITLE
p-dataTable problem with responsive view in Safari

### ISSUE THREAD

**Issue by pserafin** [primefaces/primeng#2184]
using:
"primeng": "1.1.0",
"primeui": "4.1.15",
"@angular": "2.0.1",

Hi,
The DataTable in responsive mode in Safari doesn’t behave as it should. Everything is fine in Chrome, Firefox and Microsoft Edge, but when you try responsive table on Safari, the records doesn’t stack after each other as the supposed to, but the table cells are in the same line. It looks like the float:left doesn’t work properly. However, on the prime faces site ,the tables act responsively, but when you turn your application on iPhone or in Safari, is doesn’t look like it supposed to. I attach the screen from application to show what I mean.
[https://goo.gl/photos/nGfGEwq7RmRe7fzo8](url)

Regards

**Comment by pserafin** [comment]
Ok, we were able to solve that problem by adding  <!DOCTYPE html> at main page.
But still responsive view is bugged - switching between responsive/normal views
* adds empty columns
* removes actions binded to toggle button (expandableRows="true")
* totally messing view in nested datatable
* additionally column headers with template (<template pTemplate type="header">) are not shown in responsive view

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview

**Comment by szilardd** [comment]
thanks @pserafin . missing DOCTYPE was causing the same issue when using the data table component in PrimeVue
