### ISSUE TITLE
[Feature Request]: pPassword needs attribute to switch on/off metering panel

### ISSUE THREAD

**Issue by nerk** [primefaces/primeng#2187]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**What is the motivation / use case for changing the behavior?**

pPassword component always shows the password strength metering panel. This is only useful when defining new passwords. Furthermore, it is not documented how to suppress this panel in CSS. Here is what I am currently doing:

```
/deep/ .ui-password-panel-overlay { 
    display: none;
}
```

I suggest to not show the metering panel by default and add an attribute to pPassword to enable the panel explicitly for specifying new passwords.

**Please tell us about your environment:**

* **PrimeNG version:** 2.0.X

* **Browser:** [all]

 
* **Language:** [all]

**Comment by external-olgierd** [comment]
This should be a simple change, just wondering though whats the purpose of using this component over normal <input> with password type if you dont want the strength meter to be displayed?

**Comment by nerk** [comment]
@external-olgierd Ahh, I think you meant to use the PrimeNG InputText with `type="password"`? This could work.

**Comment by nerk** [comment]
Well, I still think that this might still be a bit misleading. 

If there is  pPassword, developers not familiar with PrimeNG are inclined to use it in all places where password entry is required - not only when creating new passwords. 

It really didn't occur to me (and my coworkers) that we'd have to use InputText with type "password" instead. We are all very new to PrimeNG, though.

Maybe this could at least be mentioned in the documentation of pPassword. Or we are all somewhat braindead already and did not see the obvious.

**Comment by Mrtcndkn** [comment]
Hi,

We reconsidered this and you are right about it.

With 4.0.RC1 you can easily close the feedback panel like this =>

     <input pPassword type="password" [feedback]="false"/>

feedback property is true by default for closing it you need to bind it like in the example.

**Comment by cagataycivici** [comment]
Better name would be passwordFeedback as pPassword is a directive.
