### ISSUE TITLE
Change locale of Schedule string

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#2188]
To be compatible with fullcalendar api, set locale as a string rather than an object.

**Comment by rawit** [comment]
I have added PrimeNg Schedule to my Angular 4 app and it works fine.
I would now like to change the locale from default english to "nb".

I see the doc (https://www.primefaces.org/primeng/#/schedule) says

"Localization for different languages and formats is defined by binding the settings object to the locale property. Following is a schedule with Spanish month names."

... 

"<p-schedule [events]="events" locale="es"></p-schedule>"

but using this exact code does not work.

And looking at the changed code here it seems to have included an object with Spanish month names which explains the doc, but this is no longer so.

And the change in schedule.ts simply assigns the submittet locale to config.locale? Is that it? I would be suprised of you don't need a bit more code for this to work unless there has been changes in other commits.

I see in my "node_modules/fullcalendar/dist/locale" folder that a lot of locales are included there. 
Why are they not uses by Schedule?

Regards
/Ragnar Westad
