### ISSUE TITLE
No value accessor for '' using quickstart and prime-slider

### ISSUE THREAD

**Issue by goleary** [primefaces/primeng#219]
I started with this quickstart and added a slider to the app.component

    import {Component} from 'angular2/core';
    import {InputText, Slider} from 'primeng/primeng';

    @Component({
	selector: 'my-app',
	template: `
        <h1>My First 2 App</h1>
        <input type="text" pInputText [(ngModel)]="text" />
        {{text}}
        <p-slider [(ngModel)]="val"></p-slider>
        {{val}}
      `,
      directives: [InputText]
    })
    export class AppComponent {
    val: number;
    text: string;
    }

but I get the error mentioned in the title

**Comment by cagataycivici** [comment]
I guess you also need to add Slider to directives;

```typescript
directives: [InputText,Slider]`
``
