### ISSUE TITLE
Grouping inputs into single control with .ui-input-group

### ISSUE THREAD

**Issue by buchatsky** [primefaces/primeng#2191]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

I have not found a convenient way to group several input controls (e.g. InputText with 1 or more Buttons) into one solid pack. Bootstrap 3.3.7 "input-group" looks inconsistent with PrimeNg controls and styles, Bootstrap 4.0.0-alpha - a bit better, but also not perfect (with gaps between buttons)

**Plunkr Case**
http://plnkr.co/edit/kuwqRJ
I managed to stick them together, but there are still problems with height of different controls, and also slightly different heights under different browsers

**Expected behavior**
'ui-input-group' style to group inputs. Several inputs look like a solid input control, with the same height and with different (specified or default) widths

**What is the motivation / use case for changing the behavior?**

Use case examples: 
1) search control on the toolbar (InputText with search Button)
2) custom ButtonEdit control on the form (InputText with one or more Buttons)

**Please tell us about your environment:**

* **Angular version:** 2.4.8

* **PrimeNG version:** 2.0.0

* **Browser:** [all]

 
* **Language:** [all]

**Comment by cagataycivici** [comment]
We'll introduce these after 4.1, more are on the way as well.
