### ISSUE TITLE
Allow disabled items in Dropdown

### ISSUE THREAD

**Issue by hhubik** [primefaces/primeng#2192]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Expected behavior**
Need to be able to show items in the dropdown that would not be selectable by the user. See [this example](https://select2.github.io/examples.html#disabled-results).

**Comment by cagataycivici** [comment]
This is available since 6.0.2;

https://www.primefaces.org/primeng-6-0-2-released/
