### ISSUE TITLE
DataTable rowGroupMode="rowspan" doesn't work with sortField 

### ISSUE THREAD

**Issue by mmlitvin** [primefaces/primeng#2193]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://plnkr.co/edit/CHjgioK0lHp1x56XpD9F?p=preview

**Current behavior**
If you try sorting up and down on the same column and THEN try to sort other columns widget breaks and becomes unresponsive. Error is thrown in the console

**Expected behavior**
Sorting should work consistently

**Minimal reproduction of the problem with instructions**
Steps on reproducing the problem are listed in plunker

**What is the motivation / use case for changing the behavior?**
User wants to sort rows

**Please tell us about your environment:**
Angular version: 2.4.x
PrimeNG version: primeng@2.0.1
Browser: all
Language: all

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
