### ISSUE TITLE
Tooltip remains visible after closing calendar

### ISSUE THREAD

**Issue by EnsiRu** [primefaces/primeng#2196]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/RByDip

**Current behavior**

Tooltip on calendar button is shown and always visible after picking date from previous month.

**Expected behavior**

Tooltip should disappear when calendar is closed and mouse left it's area.

**Minimal reproduction of the problem with instructions**

0. Add primeng tooltip to primeng calendar button
1. Open calendar
2. Click on previous month button
3. Select any day
4. Move mouse out of calendar button

**What is the motivation / use case for changing the behavior?**

Current behaviour prevents from using tooltips on calendar buttons.

**Please tell us about your environment:**

* **OS:** Linux

* **Angular version:** 2.4.8

* **PrimeNG version:** 2.0.1

* **Browser:** [Chrome 56 | Firefox 51]

 
* **Language:** [TypeScript 2.0.x]

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview

**Comment by leo420994717** [comment]
same problem

http://plnkr.co/edit/zpIEGWkl5QNHbtkO3IFS?p=preview

**Comment by leo420994717** [comment]
@cagataycivici @EnsiRu 
same problem

http://plnkr.co/edit/zpIEGWkl5QNHbtkO3IFS?p=preview

**Comment by thewelder76** [comment]
This is also happening on dropdown. It only happens when a different value is selected.
I added an example to the previous plunkr
http://plnkr.co/edit/Bg8sXcJxneQ94EB2OD4j?p=preview

Chrome 58 and Firefox 54 on Mac
Angular 4.2.2 and PrimeNG 4.1.0-rc.2

**Comment by fxmfr** [comment]
This problem also occurs when adding pTooltip to a button which gets disabled on click.
I'm sorry, cannot provide a plunkr atm because of restrictions... But this is the code to reproduce the isse:

`<button pButton type="button" [disabled]="isDisabled" (click)="isDisabled = !isDisabled" label="disable" pTooltip="some tooltip text"></button>`

Chrome 59 & IE11 on Windows, Angular 4.2.4 and PrimeNG 4.1.0-rc.2.
Firefox 54 is not affected.

Thanks for attention and your great work!

**Comment by DavyDeDurpel** [comment]
I'm also seeing the same behaviour on AutoComplete field.  So basically it seems to happen on every widget that looses the focus without user interaction.

**Comment by DavyDeDurpel** [comment]
I'm able to workaround the issue by adding `appendTo="body"` to the Autocomplete field.  But it's not a solution as it causes the auto complete dialog to render in the wrong place.

**Comment by darek8686** [comment]
I can confirm bug on primeNg 4.1.3

**Comment by Paddelu** [comment]
still happening with at least calendar component 4.2.0-rc.1

**Comment by ekoch** [comment]
I have the same problem with a route change. 
Set a delay big enough on the link that trigger the route change, the tooltip appear in the next page (in the top left of the screen) and never disappear

**Comment by mlaffargue** [comment]
Same here with dynamic tabs, opening a tab from a button with a tooltip will leave the tooltip forever on the screen. Using "life" attribute at the moment to ensure the tooltip disappears.
