### ISSUE TITLE
Remove placehoder in non-empty multiple autocomplete

### ISSUE THREAD

**Issue by sharok** [primefaces/primeng#2197]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Bug exists on the [demo](http://www.primefaces.org/primeng/#/autocompletehttp://www.primefaces.org/primeng/#/autocomplete) page. 

**Current behavior**
 `p-autocomplete` control with `multiple` flag.
Placeholder (countries) is not hidden when value is selected.

**Expected behavior**
Placeholder must be hidden when at least one value is selected

* **Angular version:** 2.4.X

* **PrimeNG version:** 2.0.1

* **Browser:** all 

 
* **Language:**  TypeScript 2.0 

* **Node (for AoT issues):** `node --version` =   7.2.1

**Comment by cagataycivici** [comment]
It is by design, need to discuss this with my colleagues.

**Comment by KeithGillette** [comment]
Any update on the internal discussion on this issue, @cagataycivici? With @sharok, I thought that not hiding the placeholder in the `p-autocomplete multiple="true"` was a bug, not a feature, since the behavior is inconsistent with the other inputs that support placeholder text. Thanks!

**Comment by cagataycivici** [comment]
Ok, let's remove it then.

**Comment by sharok** [comment]
What do you think about create some input parameter and users can set true/false if they want hide placeholder when there are values or not.

**Comment by cagataycivici** [comment]
Sure, makes sense.
