### ISSUE TITLE
Dropdown comoponent throwing error on empty selectitem array

### ISSUE THREAD

**Issue by ljubomir** [primefaces/primeng#220]
After the latest update, all of my Dropdown components are throwing the following error:

> EXCEPTION: TypeError: Cannot read property 'label' of undefined in ...

I assume is because of the **updateLabel()** invoked on **ngOnInit()**. 
IMHO additional check for empty array might help resolve this issue..

I'm using primeng 1.0.0-beta.2 with Angular 2.0.0-beta.15

**Comment by cagataycivici** [comment]
Will review and give an update.
