### ISSUE TITLE
DataTable pagination using custom code not working

### ISSUE THREAD

**Issue by mohan1304** [primefaces/primeng#2200]
**Current behavior**

I have a requirement to retain DataTable state. I tried to cache the DataTable and Table pagination event and then when I call table.paginate(paginationEvent) the table is not going to the page as per pagination.

I also tried table.onPage.emit({first:20,rows:10}) and still its not working

I remember it was working sometime back (I believe PrimeNG 1.1.4 not sure) and now I observed it is not working

**Expected behavior**

Table pagination should happen

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Operating system : Windows7
Server: Tomcat

* **Angular version:** 2.0.X

Angular 2.4.6
"webpack": "2.2.1"

* **PrimeNG version:** 2.0.X

PrimeNG 2.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

  
Chrome:56

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
"typescript": "~2.1.6",
* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
