### ISSUE TITLE
expose the carousel event 

### ISSUE THREAD

**Issue by byunru** [primefaces/primeng#2201]
suggest expose the carousel event for carousel when been navigated to a new image
the scenario is when I click left/right arrow button, the content outside of the carousel need to updated accordingly based on which image currently show.

**Comment by cagataycivici** [comment]
Added onPage event.

**Comment by adjiandov** [comment]
When will this be released/when can I as a developer use the event?

**Comment by cagataycivici** [comment]
We're planning by mid next week, there will be documentation.

**Comment by pynadium** [comment]
Would be nice to also have the direction of movement in this event. 
That is, based on the orientation, expose also the direction of swipe or the button clicked actual value (up - down, left - right). 
Would this be possible?
