### ISSUE TITLE
Changing rows should trigger pagination in Data components

### ISSUE THREAD

**Issue by wbrannoc** [primefaces/primeng#2202]
I'm submitting a bug report

**Current behavior**
When dynamically changing the number of rows to display in the p-dataTable, the number of pages displayed by the paginator does not automatically update until a page change is initiated.

http://plnkr.co/edit/L4rZYnJ9AWVhGHuarM9d?p=preview

**Expected behavior**
The number of pages in the paginator should match the number of pages of data in the table after changing the row attribute on the table.

**Steps to reproduce**
http://plnkr.co/edit/L4rZYnJ9AWVhGHuarM9d?p=preview
Enable pagination on the p-dataTable
Start with 30 rows of data with the table rows property set to 5.  The number of pages is calculated as 6.
Dynamically change the rows property on the table to 10 and reset the table.  The number of pages does not update but the table display does.
Change the selected page from the first page to another page and the number of pages is recalculated.
If you are on a different page than the first page the number of pages are recalculated immediately when rows is changes and the table is reset.

**What is the motivation / use case for changing the behavior?**
Correct display logic for generating the number of pages for pagination

**Please tell us about your environment:**
Angular CLI hosted in IIS

* **Angular version:** 2.4.6

* **PrimeNG version:** 2.0.1

* **Browser:** Chrome 56
 
* **Language:** TypeScript 2.1.6

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.

**Comment by abhikhan25** [comment]
@wbrannoc 

`@ViewChild(DataTable) datatable: DataTable;`

When you change the rows, just reset the table immediately after that
`this.datatable.reset();`

this updates the paginator and displayed rows in table.

**Comment by izy2nv** [comment]
@wbrannoc Plz what's the quivalence to 'dataToRender' (present in dataTable) in 'p-table' ? 
I'm trying to get the number of VISIBLE rows in p-table after pagination has occured.

**Comment by dangrima90** [comment]
@cagataycivici I have replicated a similar issue and cannot seem to solve it. Both on Client side Data Tables and Lazy loaded Data Tables, changing the page size does not seem to trigger the necessary events.

https://stackblitz.com/edit/primeng-turbo-table-test

In the Client side table if you are on the first page and you change the page size it works fine. However if you go to the second page and change the page size this doesn't work.

In the Lazy loaded table it seems that the lazy load event is not triggered when changing the page size.

I don't know if I'm doing something wrong. What I have is a drop down from which I am setting the page size (i.e. the rows input property). I have tried slicing the array with the data and also setting the first input property to zero, but nothing seems to work. Is there any way to make this work please?

This was tested using Angular version 6.0.0 and PrimeNG version 6.1.4.
