### ISSUE TITLE
Tooltip - Multiline support missing when updating from 1.x to 2.0.1

### ISSUE THREAD

**Issue by luigidallavalle** [primefaces/primeng#2205]
**I'm submitting a ...**  
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/VChLUx?p=preview

**Current behavior**
If I put a `<BR>` in the tooltip body the `<BR>` is rendered as if it's normal text, the version 1, let me write a multi line tooltip simply using `<BR>`

**Expected behavior**
I would like the tooltip text to go on a new line at every `<BR>`

**Minimal reproduction of the problem with instructions**
Run the plunker attached 

**Please tell us about your environment:**
Win10, webpack

* **Angular version:** 2.4.1

* **PrimeNG version:** 2.0.1

* **Browser:** tested only on chrome
 
* **Language:** TypeScript 2.0.10

**Comment by szurilo** [comment]
Same issue here.
Any solution?

**Comment by luigidallavalle** [comment]
@szurilo were you able to make up a workaround?
any chance to get some feedback?

**Comment by szurilo** [comment]
No, I am still waiting for a solution.

**Comment by sunkike** [comment]
workaround ... 

Source in: http://pastebin.com/Q4PHB5br

I have added a function addText(node,text) and replaced de line:
//tooltipText.appendChild(document.createTextNode(this.text)); 
addText(tooltipText,this.text);

I hope this it would be usefull  until the guys find a solution for this problem in this component.

**Comment by agusdutra** [comment]
I was with the same problem and I found a workaround. 

1- set style white-space to pre-line: 
```css
/deep/
.ui-tooltip .ui-tooltip-text {
  white-space: pre-line;
}
```
2- Load the tooltip value from the template component using '\n' to break line

HTML: 
```HTML
            <a role="button" pTooltip="{{getToolTipValue()}}"
               tooltipPosition="top" class="btn-users" >
              <span>Tooltip</span></a>
```

component.ts: 
```javascript 
public getToolTipValue(): string {
    return "Line1 \n Line2 \n Line3";
  } 
```
Result: 

![tooltip](https://cloud.githubusercontent.com/assets/12460226/24262875/3ba4f5a2-0fda-11e7-9b81-cffdad163518.png)

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview

**Comment by citizentim** [comment]
I'm afraid this still isn't working for me.  Please see this plunkr: 

http://plnkr.co/edit/shirXecmSnDzX6qZtW11

**Comment by citizentim** [comment]
I see that this issue is still closed.  I'm wondering, has anyone seen this, or should I open a new issue?

**Comment by ijaouani** [comment]
Same problem here : I try \n and br solutions.
But none works.

**Comment by xadhoom** [comment]
you may want to check the "escape" tooltip property. set it to false and use <br /> for line breaks,
