### ISSUE TITLE
p-autocomplete doesn't cancel old request (replaces existing result).

### ISSUE THREAD

**Issue by johnhwright** [primefaces/primeng#2207]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Tricky, needs http requests to demonstrate.

**Current behavior**
When using **p-autocomplete** If a long request is made followed by a short request, the long request isn't cancelled and will replace the results of the latter.

**Expected behavior**
Expect the component to use something like an observable with a switchMap so it won't wait for existing requests once a new one is made.

**Minimal reproduction of the problem with instructions**
Have the complete method make a request that takes > 1 second, then have the complete method make a request that takes > 1 second.

**What is the motivation / use case for changing the behavior?**
Not very user friendly.

* **Angular version:** 2.0.X
4.0.0-beta.7

* **PrimeNG version:** 2.0.X
2.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All

**Comment by VenkateshKadiri66** [comment]
I'm also looking for a solution for this. Is it something that I need to code in the completeMethod to use switchMap or p-autocomplete has this and I'm missing some configuration?
