### ISSUE TITLE
[Feature Request] Provide access to tr tag inside of template for p-datatable.

### ISSUE THREAD

**Issue by sharok** [primefaces/primeng#2209]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**What is the motivation / use case for changing the behavior?**
It's hard to describe, so ask if you don't understand.
I need some way to apply directives to generated `tr` tags for datatable. I will show on example.
I want to implement row reorder. This is [demo](https://datatables.net/extensions/rowreorder/examples/initialisation/simple.html)

For now, I finished this task in the following way:
```
 <p-dataTable [value]="cars">
    <p-column>
      <template let-car="rowData" pTemplate="body">
        <button pDraggable="cars" pDroppable="cars"
                (onDragStart)="dragStart($event,car)"
                (onDragEnd)="dragEnd($event)"
                (onDrop)="drop($event, car)"            
                type="button" pButton
                icon="fa-bars"></button>
      </template>
    </p-column>
    <p-column field="year" header="Year"></p-column>
    <p-column field="brand" header="Brand"></p-column>
  </p-dataTable>
```

But, I want to apply `pDraggable` and `pDroppable` directives to `tr` tag itself. I need something that datatable will provide me.
I don't know if it's possible or not, so just let me know and feel free to close the issue if it's impossible.

* **PrimeNG version:** 2.0.1

**Comment by AleksandarAleksandrov** [comment]
+1

**Comment by cagataycivici** [comment]
We would like to but not sure how, nevertheless we'll create reorder via drag drop to DataTable.
