### ISSUE TITLE
Custom row style in odd rows is not working.

### ISSUE THREAD

**Issue by sanjarbek** [primefaces/primeng#2212]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/EJJbc7?p=preview

**Current behavior**

In odd rows .ui-datatable tbody > tr.ui-widget-content.ui-datatable-odd styles disable custom row style (in my case background color).

**Expected behavior**

it must apply custom row style whenever default style.

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

Ubuntu, Chrome

* **Angular version:** 2.4.0

* **PrimeNG version:** 2.0.1

**Comment by cagataycivici** [comment]
It could be that your css is overriden.
