### ISSUE TITLE
Calendar clicking on button icon not opening calendar IE9/IE10

### ISSUE THREAD

**Issue by henritoivar** [primefaces/primeng#2213]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

When using calendar with showIcon and clicking on the icon, then the calendar does not open. Clicking on the input still works. Works on Chrome, but not on IE9/IE10.

* **Angular version:** 2.0.X
2.4.9

* **PrimeNG version:** 2.0.X
2.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
IE9 IE10
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

**Comment by fr4nk** [comment]
The problem occurs here also: primeng V. 2.0.5, angular 2.4.10

I did a little debugging and found in calendar.js 'this.overlay.offsetParent' links to the overlay itself wich is the datepicker. (i think it should be a boolean, not an HTMLBodyElement like the other offsetXXX fields)

_(see offsetXXX fields of overlay here)_
![image](https://cloud.githubusercontent.com/assets/432089/24541388/7b306422-15f7-11e7-9d2e-07838aba748d.png)


![image](https://cloud.githubusercontent.com/assets/432089/24541324/40456772-15f7-11e7-9780-63678cc666a8.png)

![image](https://cloud.githubusercontent.com/assets/432089/24541345/5bcd697c-15f7-11e7-8423-f4fdff9da181.png)

**Comment by ankati** [comment]
I need this fix in PrimeNG 2.X as well @Mrtcndkn
