### ISSUE TITLE
Datatable Filter with multiselect and custom cells' contains such as html-list doesn't work

### ISSUE THREAD

**Issue by tamatcho** [primefaces/primeng#2215]
First I appreciate the Datatable-multiselect-filtering feature. However I am facing a case where I have a primNG Datatable whose cells' contains of one specific column are lists(<li>foo</li>) of strings. Which means I have in one cell a list of items and all items are SelectItem of the multiselect component in the column header. So filtering doesn't work anymore. Is there any way to achieve that or it is not possible yet?

**Comment by cagataycivici** [comment]
Issue is not clear, please use forum for support requests, we also appreciate a plunkr that is similar to your setup.
