### ISSUE TITLE
Chips drag n drop

### ISSUE THREAD

**Issue by lebnic** [primefaces/primeng#2216]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**What is the motivation / use case for changing the behavior?**

Would be nice to "transfert element between chips by simply doing a drag n drop"

**Comment by sudheerj** [comment]
This is bit special case because chips will come under input component.The drag & drop support on input component is very rare.I think picklist is the better option but you can't provide input.

**Comment by cagataycivici** [comment]
If more users demand it, we'll do it however I don't think it is too common. Still let's monitor feedback. Thank you.
