### ISSUE TITLE
Datatable: selectionMode enabled: cursor "jitters" when moving mouse around

### ISSUE THREAD

**Issue by lebnic** [primefaces/primeng#2217]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

http://plnkr.co/edit/2Q8Bdz

**Current behavior**

Nothing too problematic, but mouse cursor can seem a bit "jittery / eratic" when mouse cursor changes row...

**Expected behavior**

More fluid UX would be if mouse cursor remains constant when mousing-over different datatable rows...

**Minimal reproduction of the problem with instructions**

Using plunker: http://plnkr.co/edit/2Q8Bdz

Simply move your mouse over the datatable and observe cursor is not "constant" (Cursor changes (momentarily) when changing focus over 2 different rows: pointer... -> something else -> pointer)

**What is the motivation / use case for changing the behavior?**

Smooter UX

**Please tell us about your environment:**

Linux

* **Angular version:** 2.0.X

3.10

* **PrimeNG version:** 2.0.X

2.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

chrome

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
