### ISSUE TITLE
onFocus event not working in Primng Autocomplete

### ISSUE THREAD

**Issue by smtgpt62** [primefaces/primeng#2221]
Hi , I am trying to use onFocus() event of Autocomplete , but the event is not getting fired even if the aucomplete box gets focus.

Also I am trying to make the make the input box look red when the list is empty according to the typed characters, it is working fine , but when i am clearing the box with backspace then the color of the box is red even if the input box is empty.

**Comment by external-olgierd** [comment]
I think the best way to get it looked at/resolved is to follow the issue logging guidelines and include plunkr showing your problem.

**Comment by Mrtcndkn** [comment]
I tried it locally and everything seems working fine try it like this.

    <p-autoComplete [(ngModel)]="country" [suggestions]="filteredCountriesSingle" (completeMethod)="filterCountrySingle($event)" field="name" [size]="30"
        placeholder="Countries" [minLength]="1" (onFocus)="test()"></p-autoComplete>

**Comment by kuldarim** [comment]
For me it does not work either. I'm using it with reactive form.

```
<p-autoComplete
  [formControl]="searchControl"
  [suggestions]="searchResults"
  (completeMethod)="search($event)"
  (onFocus)="focus()"
></p-autoComplete>
```

**Comment by Mrtcndkn** [comment]
Glad to hear that.

**Comment by Taitalus** [comment]
working perfectly on version ```ˆ2.0.4```.

**Comment by padmarao123** [comment]
I have same problem
version 4.X   but also  not working

<div class="col-md-6 form-group">
              <label class="control-label">* Business type</label>
              <p-autoComplete #orgtype="ngModel" name="orgtype" [suggestions]="organization_type_list" [(ngModel)]="selected_organization_type"
              (completeMethod)="searchOrganizationType($event)" (focus)="totla()" field="name" placeholder="Organization type" [size]="50" [minLength]="1" required>
              </p-autoComplete>
              <div *ngIf="orgtype.invalid && (orgtype.dirty || orgtype.touched)" class="text-danger">
                <div *ngIf="orgtype.errors.required"> Business type is required.</div>
              </div>
            </div>

**Comment by sarangrajan948** [comment]
OnFocus() event is not working on Primeng Listbox.

   <p-listbox [options]="rentalLocationsName" [(ngModel)]="selectedLocation"  (onFocus)="onDropdownFocus()" (onBlur)="onBlurMouse()" [filter]="true" [style]="{ width: '15rem' }" [listStyle]="{'max-height': '220px'}"></p-listbox>
   
   onDropdownFocus() {
  console.log('Dropdown focused!');
}
