### ISSUE TITLE
selectOtherMonths not selecting greyed future dates of next month 

### ISSUE THREAD

**Issue by arunsaibk** [primefaces/primeng#2222]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
selectOtherMonths not selecting greyed future dates of next month , We are using priming calendar, In that we found one bug that if we add this property selectOtherMonths as true ,it should select greyed  past and future dates of previous and next month  but for the past month dates which are greyed, they are working fine ,  When I select the future dates which are greyed, I am getting NAN,

**Expected behavior**
it should select greyed  past and future dates of previous and next month  

**Minimal reproduction of the problem with instructions**
We are using priming calendar, In that we found one bug that if we add this property selectOtherMonths as true , it should select greyed  past and future dates of previous and next month  but for the past month dates which are greyed, they are working fine , When I select the future dates which are greyed, I am getting NAN,

**What is the motivation / use case for changing the behavior?**
client requirement

**Please tell us about your environment:**
Win 10

* **Angular version:** 2.0.X
2.4.3

* **PrimeNG version:** 2.0.X
1.1.4

**Comment by external-olgierd** [comment]
This should be resolved with the fix for #1689 and #1935 as essentially its the same problem.

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview

**Comment by Gnanarajk** [comment]
Any update on this item, the issue still persists.
