### ISSUE TITLE
DataTable Frozen Column Long Text Misaligned Rows

### ISSUE THREAD

**Issue by mdg357** [primefaces/primeng#2224]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/bDoEqReSx4L1x0NkdBak

**Current behavior**

Issue occurs when using frozen and unfrozen columns of a fixed pixel width. Rows in frozen columns with text that extends past the width limit of the column wrap to the next line. This then causes the subsequent rows to be misaligned.

**Expected behavior**
Columns with long text values should do one of the following (possibly decided by a configuration flag):
1. Allow the frozen to scroll horizontally 
2. Increase the height of the corresponding unfrozen row

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/bDoEqReSx4L1x0NkdBak

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **OS:** Windows 7
* **IDE:** Visual Studio Code
* **Package manager:** JSPM

* **Angular version:** ~2.2.0

* **PrimeNG version:** ^2.0.1

* **Browser:** Chrome
 
* **Language:** TypeScript

* **Node (for AoT issues):** 6.9.1

**Comment by cagataycivici** [comment]
This has been discussed a couple of times, you need to set min-height of datatable rows;

```
.ui-datatable tbody > tr {
   min-height:30px;
}
```

We don't to do to avoid performance as we need to calculate things, so leave to the user.
