### ISSUE TITLE
TreeNode expand performance issue

### ISSUE THREAD

**Issue by mohan1304** [primefaces/primeng#2225]
**Current behavior**

Tree expand is taking sometime when I try to expand TreeNode by clicking on it. Want to know if there is a way to show progress bar or loading spinner so that user is aware that something is going on

Chrome is taking little less time compared to IE. 

**Please tell us about your environment:**

Operating System : Windows7

* **Angular version:** 2.0.X

Angular 2.4.3
* **PrimeNG version:** 2.0.X

PrimeNG 2.0.0
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

IE11 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

TypeScript 2.1.6

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
