### ISSUE TITLE
Autocomplete does not work well within an OnPush Component

### ISSUE THREAD

**Issue by variable-content** [primefaces/primeng#2226]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/7yCXOOEIqrhpqTIFDXyR?p=preview

**Current behavior**
Create a component that uses OnPush change detection that uses the autocomplete component. Type a letter into the autocomplete field, click on an item in the list. List does not close.

**Expected behavior**
List should close.

**Minimal reproduction of the problem with instructions**
See this plunkr: http://plnkr.co/edit/7yCXOOEIqrhpqTIFDXyR?p=preview

**What is the motivation / use case for changing the behavior?**
OnPush is important to reduce which components need to be checked during change detection and is important for performance when the page contains a lot of nested components.

* **Angular version:** 2.0.X
2.4.9

* **PrimeNG version:** 2.0.X
2.0.2

* **Browser:** all 

* **Language:** all

**Comment by vlodko** [comment]
@variable-content same issue in SplitButton :(

**Comment by ilya-on-github** [comment]
It also blinks when OnPush strategy in combination with Observable.
When the detection strategy is set to OnPush and results are loaded in an async way, the dropdown part blinks and then disappears. See the plunker: http://plnkr.co/edit/pKHoxm14z2F9ut6U4CmW?p=preview
Try type 'vo' symbol by symbol.

**Comment by cagataycivici** [comment]
Please try with latest PrimeNG release, should be working with it.
