### ISSUE TITLE
p-calendar timeonly is not showing the correct time in input box

### ISSUE THREAD

**Issue by mitalikhundiwala** [primefaces/primeng#2229]
For timepicker,

If we provide datetime in ngModel, then **this.pm** boolean value is not being calculated with provided date. It's calculated based on current time.

**Comment by aclarktcc** [comment]
in formatTime this.pm needs swapped for hours > 11 

 if(this.hourFormat == '12' && hours > 11 && hours != 12) {
```

formatTime(date) {
        if(!date) {
            return '';
        }
        
        let output = '';
        let hours = date.getHours();
        let minutes = date.getMinutes();
        let seconds = date.getSeconds();
        
        if(this.hourFormat == '12' && hours > 11 && hours != 12) {
            hours-=12;
        }
        
        output += (hours < 10) ? '0' + hours : hours;
        output += ':';
        output += (minutes < 10) ? '0' + minutes : minutes;
        
        if(this.showSeconds) {
            output += ':';
            output += (seconds < 10) ? '0' + seconds : seconds;
        }
        
        if(this.hourFormat == '12') {
            output += this.pm ? ' PM' : ' AM';
        }
        
        return output;
    }
```

**Comment by mitosandov** [comment]
i have exactly the same issue - i provide 23:00 and on the UI i see 23:00 AM - please release a fix for this!

**Comment by mitalikhundiwala** [comment]
@aclarktcc It seems to be working fine with your provided solution. Any idea by when this fix will be available and have you submitted any pull request?

**Comment by aclarktcc** [comment]
sorry been busy on a handful of projects.  I have not had a chance to build the project and do a pull request.  I was just eyeing the code and saw it while looking into the issue.  If someone has some time to contribute that would be great

**Comment by SIlver--** [comment]
Has anyone been able to make a pull request yet?

**Comment by LeonardoBluesMan** [comment]
Please apply this fix asap!

**Comment by milosh012** [comment]
this is very ugly bug... can you @mitalikhundiwala submit a PR, and hopefully someone will merge it soon

**Comment by mitalikhundiwala** [comment]
I have submitted a PR, requested to merge it soon.

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
