### ISSUE TITLE
Tabbing support for editable cells in DataTable

### ISSUE THREAD

**Issue by kennetv** [primefaces/primeng#223]
Pressing tab when editing a cell in a datatable you should go to the next cell, now editing stops.

**Comment by sylvainpey** [comment]
This enhancement would be really great. Will it be added in a future beta ?

**Comment by philwith** [comment]
Really enjoying trialing this datatable component so far but this enhancement would be essential I think for me to use it in a project.

**Comment by cagataycivici** [comment]
Let's do it for RC4.

**Comment by jtraband** [comment]
Still running into this. Tabbing stops as soon as I hit a noneditable field or one with a ng-template editor

**Comment by xtoff** [comment]
Same problem. I still have this issue. I'm using Angular 4.1.1 and Primeng 4.0.0.
