### ISSUE TITLE
p-multiSelect in dataTable no overflow visible

### ISSUE THREAD

**Issue by Danieleeee** [primefaces/primeng#2231]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

I have a p-multiSelect in dataTable filter:
`<template pTemplate="filter" let-col>
							<p-multiSelect [options]="Remi" defaultLabel="tutti" (onChange)="dt.filter($event.value,col.field,col.filterMatchMode)" styleClass="ui-column-filter"></p-multiSelect>
						</template>`

[Image](http://i.imgur.com/tpZQZCM.jpg)

When I select only one element of the multiselect, decreases the number of records of the table and this is the result:

[Img](http://i.imgur.com/DTYaI5h.jpg)

As you can see the multiselect is hidden.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.4.X

* **PrimeNG version:** 2.0.X

**Comment by cagataycivici** [comment]
appendTo="body" usually solves cases like these.

**Comment by Danieleeee** [comment]
If I use appendTo="body" the multiselect don't work properly.
Whenever you select a record with the check box, the multiselect closes.

**Comment by nick1247** [comment]
> If I use appendTo="body" the multiselect don't work properly.
Whenever you select a record with the check box, the multiselect closes.

same for me

**Comment by Naveen07** [comment]
I had the same issue of the multiselect getting closed  when used appendTo="body" for a multiselect present inside a p-dialog .
