### ISSUE TITLE
Migrate to ng-template

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#2233]
From the deprecated template tag.

**Comment by attina-claudia** [comment]
Hi. 
If I use the ng-template in my columns I get: Unhandled Promise rejection: Template parse errors:
"let-" is only supported on template elements. ("" [style]="{'position':'relative','width' : '10%'}" required="true">
                 <ng-template [ERROR ->]let-col let-tr="rowData" pTemplate="body">
                  <span [ngClass]="{'column-error':tr['pa"): TransactionListComponent@46:30
"let-" is only supported on template elements. ("]="{'position':'relative','width' : '10%'}" required="true">

My code bellow:
<p-dataTable #dt id="transactionTableId" [value]="transactions" [rows]="10" [paginator]="true" [responsive]="true" [(selection)]="selectedTransaction"
              class="table table-hover table-mc-light-blue" [editable]="!isManager" (onEditComplete)="validateRow($event)">
<p-column field="pan" header="PAN" [editable]="!isManager" [style]="{'position':'relative','width' : '10%'}" required="true">
                 <ng-template let-col let-tr="rowData" pTemplate="body">
                  <span [ngClass]="{'column-error':tr['panError']}">{{tr[col.field]}}</span>
                </ng-template>
              </p-column>
 <p-column field="transactionType" header="Transaction Type" [style]="{'position':'relative','width' : '12%', 'overflow':'visible'}">
                <ng-template let-col let-tr="rowData" pTemplate="editor">
                  <p-dropdown  [ngClass]="{'column-error':tr['trasactionTypeError']}" [(ngModel)]="tr[col.field]" [options]="trTypes"
                                (onChange)="changeTransactionTypeListener(tr)" [autoWidth]="false" [style]="{'width':'100%'}">
                  </p-dropdown>
                </ng-template>
              </p-column>
 <p-column field="transactionDate" header="Transaction Date" [style]=" {'position':'relative','width' : '10%','overflow':'visible' }">
                <ng-template let-col let-tr="rowData" pTemplate="body">
                  {{tr[col.field]|date }}
                </ng-template>
                <ng-template let-col let-tr="rowData" pTemplate="editor">
                  <p-calendar [ngClass]="{'column-error':tr['transactionDateError']}" [(ngModel)]="tr[col.field]" [maxDate]="maxDate" (onSelect)="pickDate(tr)" [readonlyInput]="true"></p-calendar>
                </ng-template>
              </p-column>
......

Any suggestion?

**Comment by cagataycivici** [comment]
You need PrimeNG 4.0 to use ng-template within a PrimeNG component.

**Comment by attina-claudia** [comment]
Thank you for your response. The package.json : 
  "dependencies": {
    "@angular/common": "^2.4.0",
    "@angular/compiler": "^2.4.0",
    "@angular/core": "^2.4.0",
    "@angular/forms": "^2.4.0",
    "@angular/http": "^2.4.0",
    "@angular/platform-browser": "^2.4.0",
    "@angular/platform-browser-dynamic": "^2.4.0",
    "@angular/router": "^3.4.0",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "rxjs": "^5.1.0",
    "zone.js": "^0.7.6"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0-rc.1",
    "@angular/compiler-cli": "^2.4.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.4.2",
    "typescript": "~2.0.0"
  }

I don't install all the primeNG.  I took from the git only the components that I need. The datatable.ts, and domHandler and all that other stuff that I need (sharedModule, api) are the latest.

**Comment by mani0608** [comment]
Today i  ran npm update and primeng got updated to 4.0.0-rc.1. Suddenly i started getting the error 

> Error: Template parse errors: 'ng-template' is not a known element: 1. If 'ng-template' is an Angular component, then verify that it is part of this module. 2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("lick($event,item,selectedItemsSource)" (touchend)="onItemTouchEnd($event)"> [ERROR ->]<ng-template [pTemplateWrapper]="itemTemplate" [item]="item"></ng-template> </li>"): PickList@15:24 'ng-template' is not a known element: 1. If 'ng-template' is an Angular component, then verify that it is part of this module. 2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.

I have already added CUSTOM_ELEMENTS_SCHEMA in my module, but still i receive this error.

**Comment by cagataycivici** [comment]
PrimeNG 4 requires Angular 4, if you are on Angular 2 use PrimeNG 2.0.x instead.

**Comment by ragavanrajan** [comment]
I have migrated my application from angular 4 to angular 5 and getting this error. Can you please help how to fix this
