### ISSUE TITLE
IE: SCRIPT5022: Error: eventTask 'undefined.addEventListener:click'

### ISSUE THREAD

**Issue by Danieleeee** [primefaces/primeng#2236]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

Hi, I have p-tabMenu like this:
`<div class="x_content">
					<p-tabMenu [model]="items" [activeItem] ="itemAttivo"></p-tabMenu>
					<router-outlet></router-outlet>
				</div>`

when I'm in the first component loaded in router-outlet, i make the (event) call:
`this.router.navigate(['/ICRM2/']);`
that is the second tab of my p-tabMenu.

This is the error in IE11:
**_SCRIPT5022: Error: eventTask 'undefined.addEventListener:click': can not transition to 'running', expecting state 'scheduled', was 'notScheduled'._**

* **Angular version:** 2.4.9

* **PrimeNG version:** 2.0.2

* **Browser:** [ IE 11 ]

**Comment by cagataycivici** [comment]
Why not use routerLink property of menu model?

**Comment by Danieleeee** [comment]
I use it, 
but there are situation when I need change Tab through "button click" of other components.
Probably I did not understand that there's another way to call Tab2 through click event or routerLink.

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
