### ISSUE TITLE
Frozen columns in datable - data binding does not take place

### ISSUE THREAD

**Issue by mmlitvin** [primefaces/primeng#2237]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/lT0TVwxkiVRY1CIXQ48N?p=preview

**Current behavior**
When column's attribute 'frozen' is changed AFTER the table init it does not get reflected int he datatable

**Expected behavior**
Ability to dynamically change which columns should be frozen or not is needed

**Minimal reproduction of the problem with instructions**
Please see plunker above

**What is the motivation / use case for changing the behavior?**
Defect

Angular version: 2.4.1
PrimeNG version: 2.0.0
Browser: [Chrome 56 | Firefox 45.0.1 ]
Language: [all | TypeScript 2.0 | ES6/7 | ES5]

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview

**Comment by HoganHu0520** [comment]
@cagataycivici  This issue still exist. In bug report, [http://plnkr.co/edit/lT0TVwxkiVRY1CIXQ48N?p=preview](http://plnkr.co/edit/lT0TVwxkiVRY1CIXQ48N?p=preview).

In this case, click button to change a column's `frozen` status. 
We expect add or remove a frozen column.
But nothing happend.

**Comment by felipebri23** [comment]
I have the same issue
Angular version: 5.0.0
PrimeNG version: 5.0.0
Browser: [Chrome 56 | Firefox 45.0.1 ]
Language: [all | TypeScript 2.0 | ES6/7 | ES5]
