### ISSUE TITLE
Charts Refresh not working on primeng 2.0.2

### ISSUE THREAD

**Issue by agusdutra** [primefaces/primeng#2239]
I'm submitting a ...
[ X] bug report

Current behavior
I have some p-charts on a template and I'm updating it's data from the component on the OnInit inside a subscribe function.
I managed it to update the data following the steps explained on this bug report: https://github.com/primefaces/primeng/issues/568

I was using primeng 2.0.0 and it was working OK as expected. I've updated it to the latest version 2.0.2 and it stoped working. 

I downgraded back to 2.0.0 and worked again. The only change that I've made was the version change of primeng.

The code that I'm using to load and update the chart: 

```javascript
  @ViewChild("findings") chart: UIChart;
  ngOnInit() {

this.service.getDashboard().subscribe((dataSub) => {
        this.data = {
          labels: dataSub.keys,
          datasets: [{
            label: ' ',
            backgroundColor: this.colors,
            borderColor: this.colors,
            data: dataSub.values
          }]
        };
        this.chart.data = this.data;
        this.chart.refresh();

      }
    );
}
```
On the html template: 
```javascript
 <p-chart #chart type="bar" [height]="200" [width]="340" [data]="data"
                     [options]="options"></p-chart>
```

Minimal reproduction of the problem with instructions
-Use a p-chart that needs to be refreshed to show the data with primeng 2.0.0
-Update primeng to 2.0.2.

Please tell us about your environment
-WebStorm
-agular-cli 1.0.0-beta.26

Angular version: 2.4.4
PrimeNG version: 2.0.2
Language: Typescipt
Node: 6.10

**Comment by Mrtcndkn** [comment]
Hi,

If you are changing your data not your array just data inside of it then you should use refresh manually. But if you are changing your array then after 4.0.RC1 changeDetection will work automatically without any function call.
