### ISSUE TITLE
Calendar validator.registerOnValidatorChange is not a function Error

### ISSUE THREAD

**Issue by kuba-010** [primefaces/primeng#2240]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
```

**Current behavior**
The calendar validator is missing the "registerOnValidatorChange" method - see https://angular.io/docs/ts/latest/api/forms/index/Validator-interface.html#!#registerOnValidatorChange-anchor

It's a bit hard to reproduce in a simple plunker but when updating the control Angular can throw an "validator.registerOnValidatorChange is not a function" error

**Expected behavior**
It shouldn't throw the error

* **PrimeNG version:** 2.0.2

**Comment by kuba-010** [comment]
P.s. If I add the code below underneath the compiled Calendar.prototype.validate= etc. the error goes away

Obviously I can't do this in my actual solution

Calendar.prototype.registerOnValidatorChange=function(){
		console.log("OK");
	}

**Comment by sergw** [comment]
This is probably Angular bug. See here: https://github.com/angular/angular/pull/12593

**Comment by cagataycivici** [comment]
Seems like an angular issue.
