### ISSUE TITLE
[BUG] AutoComplete not showing previously selected element

### ISSUE THREAD

**Issue by eXXeption** [primefaces/primeng#2241]
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/5dV13TPkCxopMQSQKlxK?p=preview

**Current behavior**
Conditions: Only have one result on autocomplete.
Type for example 'aa' into the plunker, you get 'aaaaa' as a result.
Select the result via click or enter.
Remove some 'a' that the search string is 'aaa'.
Result 'aaaaa' is not shown.

**Expected behavior**
Result 'aaaaa' should still be shown if i selected it once and removed characters again.

**Minimal reproduction of the problem with instructions**
See plunker/expected behavior.

**What is the motivation / use case for changing the behavior?**
The user should have the possibility to reselect an entry if he removed some characters.

**Please tell us about your environment:**

* **Angular version:** 4.rc3
But doesn't work with angular 2, too.

* **PrimeNG version:** 2.0.0 / 2.0.2
Tried with both.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Reproduced it in Chrome, but its not a browser bug, its a logic bug.
 
* **Language:** 
Typescript

* **Node (for AoT issues):** `node --version` =   
v6.9.1

It can be changed by adding something like this to the Autocomplete ngDoCheck to force the opening of the panel:
```
   if (this.suggestions && this.value && this.value != '' && this.suggestions.length == 1 && this.value !== this.suggestions[0]) {
            changes = true;
        }
```
This is not a valid fix, but a workaround.

**Comment by upmauro** [comment]
Wooow, nice! I burning my mind to think how solve it.

Let's me try explain whats happening.

Inside doCheck() of AutoComplete component PrimeNG using IterableDiffers to check if have changes in array of sugestions, by the way, when you erase one character of filter for example, in many times the results is the same then  IterableDiffers.diff return false and we not call this.show()

https://github.com/primefaces/primeng/blob/master/components/autocomplete/autocomplete.ts#L146

**Comment by eXXeption** [comment]
Yes, I know what is happening, but I think it has a bad usability. Even if the suggestions don't change, I want to show the suggestion again, if I'm not matching a suggestion.

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
