### ISSUE TITLE
MultiSelect option navigation/selection using the keyboard

### ISSUE THREAD

**Issue by asheba** [primefaces/primeng#2243]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**What is the motivation / use case for changing the behavior?**
The user should be able to navigate through the options using the down/up arrows.
The user should be able to select/deselect an option using the spacebar key.
The user should be able to close the MultiSelect using tab/escape/enter keys.

This new behavior should conform to the keyboard navigation currently implemented in the dropdown component.

* **PrimeNG version:** 2.0.2

**Comment by xtoff** [comment]
Apparently, this is on the [roadmap](https://github.com/primefaces/primeng/issues/2243)!
Great news, because it is really annoying you have to mouse click an item to select it :)

@cagataycivici can you give us an estimate when this feature is released?

**Comment by cagataycivici** [comment]
We will create an accessibility matrix wiki with estimates this week to document/ track the accessibility state of each component, then will pick things up from there to improve. As multiselect is a popular component, my rough guess is end of april latest.

**Comment by cdibbs** [comment]
@cagataycivici - Did you guys end up making this wiki? I am having trouble finding it. Thanks!

**Comment by cagataycivici** [comment]
Not yet, we're doing an issue tracker review this week and will do the matrix later.

**Comment by cagataycivici** [comment]
Planned for 4.1.1

**Comment by dojchek** [comment]
@cagataycivici - Any updates on this one? Seems like it's still not in.

**Comment by Harlantr** [comment]
I'm using 4.1.3, and it doesn't seem like this feature has been introduced yet.  Any news?

**Comment by lothern** [comment]
I'm also curious about the status of this enhancement.

**Comment by dockleryxk** [comment]
Please?

**Comment by skotrik** [comment]
Any update on this?

**Comment by souravsaraf** [comment]
Any update on this? I am on v8 , still tabs not working on multiselect. :(

**Comment by yigitfindikli** [comment]
Fixed in v9+.
