### ISSUE TITLE
Key navigation doesn't work in Multiselect

### ISSUE THREAD

**Issue by ova2** [primefaces/primeng#2248]
Multiselect www.primefaces.org/primeng/#/multiselect

Key navigation doesn't work in the popup. You can navigate and select checkboxes by arrow keys and space / enter key.

**Comment by ova2** [comment]
Oh, just found this duplicate issue https://github.com/primefaces/primeng/issues/2243

**Comment by cagataycivici** [comment]
Duplicado! :)
