### ISSUE TITLE
Input field in MultiSelect grows and getting very long

### ISSUE THREAD

**Issue by ova2** [primefaces/primeng#2249]
Multiselect: http://www.primefaces.org/primeng/#/multiselect

The more items selected, the more grows the input field. It can be very long and looks ugly. I suggest to set the fixed length (layout is not broken then). If some items not fit the available length (visible space), they should be displayed as ... (ellipses).

**Comment by keyvhinng** [comment]
I agree, there should be a fixed width message so the layout is more persistent. The label should be something like 'Selected (x)' where x is the number of selected items.

**Comment by loftyduck** [comment]
@ova2 You should be able to accomplish this with a simple CSS rule
`p-multiSelect label {
    max-width: 150px;
}`

@keyvhinng your suggestion can be accomplished with: maxSelectedLabels and selectedItemsLabel

**Comment by cagataycivici** [comment]
There is maxSelectedLabels property for this.
