### ISSUE TITLE
zone.js dependency

### ISSUE THREAD

**Issue by dowoncha** [primefaces/primeng#225]
I'm using primeng v1.0.0-beta.2 which requires a peer dependency of zone.js 0.6.6. I am also using angular2 v2.0.0-beta.15 which requires zone.js ^0.6.10. I am trying to upload my application to openshift but am getting blocked by peerinvalid calls due to being unable to have both version of zone.js. Does anybody have a solution to this, maybe a way to keep both versions of zone.js or upgrade package.json in primeng to take higher versions?

remote: npm ERR! Linux 2.6.32-573.22.1.el6.x86_64
remote: npm ERR! argv "node" "/opt/rh/nodejs010/root/usr/bin/npm" "install" "-d"
remote: npm ERR! node v0.10.40
remote: npm ERR! npm  v2.14.13
remote: npm ERR! code EPEERINVALID
remote: 
remote: npm ERR! peerinvalid The package zone.js@0.6.11 does not satisfy its siblings' peerDependencies requirements!
remote: npm ERR! peerinvalid Peer angular2@2.0.0-beta.15 wants zone.js@^0.6.10
remote: npm ERR! peerinvalid Peer primeng@1.0.0-beta.2 wants zone.js@0.6.6

**Comment by cagataycivici** [comment]
This is fixed in;

#206 

Please try with 1.0.0-beta.3
