### ISSUE TITLE
Add activeIndex to TabView to change tab by code

### ISSUE THREAD

**Issue by stevenvanryckeghem** [primefaces/primeng#2253]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
There is no possibility to set an active tab by code. A specific use case: the user opens a dialog with tabs, switches tabs and closes the dialog. When he reopens the dialog, the tabview is in the last state from when the user closed the dialog.

**Expected behavior**

A possibility to control the opened tabs by code.

There is already a forum post by someone else about this matter. See https://forum.primefaces.org/viewtopic.php?f=35&t=48324

**Comment by external-olgierd** [comment]
Can you not use [selected] input on the relevant p-tabPanel to achieve this?

**Comment by stevenvanryckeghem** [comment]
@external-olgierd this only works the first time when showing the tabview. The second time when the tabview is already initialized, it doesn't look at the [selected] attribute anymore.

**Comment by external-olgierd** [comment]
See below plunker, if you bind it properly this should work as expected.
Unless change detection is not triggered for some reason - are you using OnPush in your parent component or something?

http://plnkr.co/edit/W2unKTLPDa8Yg5aoxgKH?p=preview

**Comment by stevenvanryckeghem** [comment]
@external-olgierd in the use case you're providing that works indeed. But my use case is a bit different. The _selectedTab_ always stays at the 0 value. Hence why probably the change detection is not triggered.

It's not that I want to change the selected tab with a specific action, but I always want to show the first tab when opening a dialog.

I can work around this by using the _onChange_ method and changing the selectedTab accordingly. But it feels like this should be included in the PrimeNG framework itself so you can call for example: this.tabView.selectedTab = 0; or something like that.

Here's the plunker with the workaround, but it feels like it can be done easier if the framework can provide some way to do this with less code: http://plnkr.co/edit/BU3axI?p=preview

Or is this just the way to go?

**Comment by external-olgierd** [comment]
Honestly I dont think there is anything wrong with that plunker. I would consider that cleaner solution than trying to call child component method from the parent programmatically, which is what you seem to want. I'd rather manipulate the input variable but thats just me.

**Comment by cagataycivici** [comment]
Should we introduce activeIndex property? We have it in PrimeFaces, I think with a setter we can hook-in to changes to activeIndex and manage the selected property of the selected tab.

**Comment by stevenvanryckeghem** [comment]
@cagataycivici yes, this would definitely help me out! :)

**Comment by cagataycivici** [comment]
Thanks, can be used by binding a number to the activeIndex property. In example below, buttons can be used to change the active tab.

```xml
<button (click)="change(0)">First</button>
<button (click)="change(1)">Second</button>
<button (click)="change(2)">Third</button>

<p:tabView [activeIndex]="index" ...
```

```typescript
   public index: number;

   change(index: number): void {
          this.index = index;
   }
```

**Comment by stevenvanryckeghem** [comment]
Awesome! Thank you for the quick solution!

**Comment by chriskyndrid** [comment]
I realize this issue is closed, but it doesn't appear that activeIndex is relevant to tabMenu and there doesn't seem to be a method by which you can adjust the current tab via code.
