### ISSUE TITLE
If it's possible to add an index into pTemplate.

### ISSUE THREAD

**Issue by marekdano** [primefaces/primeng#2254]
**Current behavior**

Currently looping through items in dropdown menu can be done through pTemplate like:
    `<template let-car pTemplate="item">`
    `    <div class="ui-helper-clearfix" style="position: relative;height: 25px;">`
     `       <div style="font-size:14px;float:right;margin-top:4px">{{car.label}}</div>`
     `   </div>`
   ` </template>`

**What is the motivation / use case for changing the behavior?**

I'll be really nice for my purpose to add an Index into the template while looping through items. Then I can know which item can be styled. Something like:
   `<template let-car let-index pTemplate="item">`
`    <div class="ui-helper-clearfix" style="position: relative;height: 25px;">`
     `       <div style="font-size:14px;float:right;margin-top:4px">`
     `          {{car.label}}`
      `         No. {{index}}`
       `     </div>`
      `  </div>`
   ` </template>`

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
It depends on the location, we usually pass the index. Please create a new ticket with more details, passing the index is not a problem.

**Comment by paulweimer** [comment]
For me this worked: let-index="rowIndex"
