### ISSUE TITLE
Zoom and Pan chart

### ISSUE THREAD

**Issue by Contu** [primefaces/primeng#2266]
Hi all,

I'm trying to use chartjs-plugin-zoom but it's not working. I'm not getting any kind of error, just nothing happens.
I'm using the following versions:
- angular:    2.4.5
- primeNG:  1.1
- chartJS:     2.3.0
- hammer:   2.0.8
- chartjs-plugin-zoom: 0.4.5

I highligth I can see the bar chart properly but the zoom and pan events don't work.

every answser/tip will be very welcome,
thanks in advance.

**Comment by Contu** [comment]
It works (a little bit slowly to be honest)

**Comment by Contu** [comment]
it works

**Comment by rich4756** [comment]
I have a reference to the p-chart object using `@ViewChild('chart'): UIChart` in my typescript file. How do I get a reference to the Chart.js chart object, instead of just the PrimeNG UIChart object?

**Comment by Danieleeee** [comment]
I have the same problem.
How to use this plugin in the option property of UIChart?
`<p-chart type="bar" height="70%" #chart [data]="data" [options]="options"  (onDataSelect)="selectData($event)"></p-chart>`

**Comment by MikeDabrowski** [comment]
@Contu  if it worked you could've shared how to setup it.
I installed and added script and added zoom to options but nothing works.

**Comment by AlexandrDobrovolskiy** [comment]
Same issue, can't find any examples how to use this plugin
