### ISSUE TITLE
Calendar error at click in date

### ISSUE THREAD

**Issue by Programmercito** [primefaces/primeng#2267]
i got error in master and 2.0.3 version:

EXCEPTION: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: ''. Current value: '10'.
EXCEPTION: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: ''. Current value: '10'.
handleError @ vendor.js:1294
next @ vendor.js:4175
schedulerFn @ vendor.js:3430
SafeSubscriber.__tryOrUnsub @ vendor.js:12543
SafeSubscriber.next @ vendor.js:12492
Subscriber._next @ vendor.js:12434
Subscriber.next @ vendor.js:12398
Subject.next @ vendor.js:14008
emit @ vendor.js:3412
triggerError @ vendor.js:3630
onHandleError @ vendor.js:3596
ZoneDelegate.handleError @ polyfills.js:14690
Zone.runTask @ polyfills.js:14521
ZoneTask.invoke @ polyfills.js:14772
vendor.js:1303 ORIGINAL STACKTRACE:
handleError @ vendor.js:1303
next @ vendor.js:4175
schedulerFn @ vendor.js:3430
SafeSubscriber.__tryOrUnsub @ vendor.js:12543
SafeSubscriber.next @ vendor.js:12492
Subscriber._next @ vendor.js:12434
Subscriber.next @ vendor.js:12398
Subject.next @ vendor.js:14008
emit @ vendor.js:3412
triggerError @ vendor.js:3630
onHandleError @ vendor.js:3596
ZoneDelegate.handleError @ polyfills.js:14690
Zone.runTask @ polyfills.js:14521
ZoneTask.invoke @ polyfills.js:14772
vendor.js:1304     at View_Calendar_1 (/CalendarModule/Calendar/component.ngfactory.js:132:7) [angular]
handleError @ vendor.js:1304
next @ vendor.js:4175
schedulerFn @ vendor.js:3430
SafeSubscriber.__tryOrUnsub @ vendor.js:12543
SafeSubscriber.next @ vendor.js:12492
Subscriber._next @ vendor.js:12434
Subscriber.next @ vendor.js:12398
Subject.next @ vendor.js:14008
emit @ vendor.js:3412
triggerError @ vendor.js:3630
onHandleError @ vendor.js:3596
ZoneDelegate.handleError @ polyfills.js:14690
Zone.runTask @ polyfills.js:14521
ZoneTask.invoke @ polyfills.js:14772
vendor.js:1307 ERROR CONTEXT:
handleError @ vendor.js:1307
next @ vendor.js:4175
schedulerFn @ vendor.js:3430
SafeSubscriber.__tryOrUnsub @ vendor.js:12543
SafeSubscriber.next @ vendor.js:12492
Subscriber._next @ vendor.js:12434
Subscriber.next @ vendor.js:12398
Subject.next @ vendor.js:14008
emit @ vendor.js:3412
triggerError @ vendor.js:3630
onHandleError @ vendor.js:3596
ZoneDelegate.handleError @ polyfills.js:14690
Zone.runTask @ polyfills.js:14521
ZoneTask.invoke @ polyfills.js:14772
vendor.js:1308 DebugContext_ {view: Object, nodeIndex: 1, nodeDef: Object, elDef: Object, elView: Object}
handleError @ vendor.js:1308
next @ vendor.js:4175
schedulerFn @ vendor.js:3430
SafeSubscriber.__tryOrUnsub @ vendor.js:12543
SafeSubscriber.next @ vendor.js:12492
Subscriber._next @ vendor.js:12434
Subscriber.next @ vendor.js:12398
Subject.next @ vendor.js:14008
emit @ vendor.js:3412
triggerError @ vendor.js:3630
onHandleError @ vendor.js:3596
ZoneDelegate.handleError @ polyfills.js:14690
Zone.runTask @ polyfills.js:14521
ZoneTask.invoke @ polyfills.js:14772
vendor.js:12547 Uncaught ZoneAwareError {__zone_symbol__error: Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Pre…, ngDebugContext: DebugContext_, __zone_symbol__stack: "    at View_Calendar_1 (/CalendarModule/Calendar/component.ngfactory.js:132:7) [angular]", __zone_symbol__message: "ExpressionChangedAfterItHasBeenCheckedError: Expre…checked. Previous value: ''. Current value: '10'."}

**Comment by external-olgierd** [comment]
That is not necessarily a calendar issue. Do you mind creating a plunker reproducing an issue?

**Comment by Programmercito** [comment]
yes in this repository 
https://github.com/Programmercito/primeng/tree/225cdd52aa7635b700a1611b28398f75a0f40898
in this tree in showcase calendar i get the error

**Comment by cagataycivici** [comment]
What is your Angular version? I get this with Angular 4.

**Comment by cagataycivici** [comment]
Fixed via https://github.com/primefaces/primeng/commit/f01ab6b4765d06eab00c35d3ab71f543dc62db8a

**Comment by Programmercito** [comment]
ohhh thanks i proved , yes  i have angular 4.0.rc1
