### ISSUE TITLE
create proper bootstrap-based theme

### ISSUE THREAD

**Issue by remmeier** [primefaces/primeng#2271]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

The current bootstrap theme neither provides a saas file nor depends/extends the official bootstrap saas file. 

**Expected behavior**

A primeng bootstrap theme extending the bootstrap 4 saas and making use of all the bootstrap styling (by using or extending them where possible). Many application do have a styling of bootstrap, this would allow there reuse in primeng.

**Comment by cagataycivici** [comment]
We're considering offering one as a premium theme based on sass, current one will stay as it is so it will be bootstrap pro version.

**Comment by remmeier** [comment]
A commercial one would be perfectly fine. We see lots of companies having bootstrap theming. So if primeng could built a theme on top of those saas files, that would be great. Currently it rather means that new applications get built with valor/ng2 bootstrap, even tough primeng provides a superior widget set.

The current bootstrap css theme imitating the not so pretty default bootstrap theming is probably not of that much help to most people.

**Comment by cagataycivici** [comment]
I see, but it wont use bootstrap classes as we have our own theme api. Wdyt? Thanks for the feedback.

**Comment by remmeier** [comment]
yes, I'm aware that primeng has its own set of classes. And that is a good thing to the most part. But from a  expectation point of view it would be great to see:

- an existing application using bootstrap
- having invested a lot of time in styling it (with saas)
- integrate the primeng bootstap theme 
- primeng components takeover that styling from bootstrap (maybe to 80%, as primeng has various more advanced things)

maybe that is achievable by setting up sass inclusions in an application like:

bootstrap sass -> custom bootstrap styling sass -> primeng bootstrap sass -> some more custom primeng styling

where the primeng bootstrap saas would extend the classes from bootstrap as far as possible with the sass @extend mechanism. How well/far that mapping would work, not sure. But it may be able to cover all the basics, because the barrier of using primeng in a project can otherwise be quite high due to the investments in bootstrap that is already in place.
