### ISSUE TITLE
Allow more specific imports

### ISSUE THREAD

**Issue by nikolasleblanc** [primefaces/primeng#2274]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Not a bug, but currently imports are all of the style:

`import { something } from 'primeng/primeng';`

And as a result webpack is bringing in the entire primeng bundle.

Similar to rxjs and how you can import only what you need from its rather large library by using imports like:

`import { Observable } from 'rxjs/Observable';`

Would it be possible to restructure the build so that we could instead import modules more specifically?

`import { something } from 'primeng/something';`

**What is the motivation / use case for changing the behavior?**

Smaller bundle sizes, less tree shaking required.

**Comment by cagataycivici** [comment]
It is already possible;

https://www.primefaces.org/primeng/#/setup

**Comment by nikolasleblanc** [comment]
Ah, excellent, thanks!
