### ISSUE TITLE
Numeric filter modes for DataTable

### ISSUE THREAD

**Issue by akj123** [primefaces/primeng#2276]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
Currently DataTable filterConstraints do support only fixed filter constraints like starts, ends, contains, equal, in which are unsuitable for numeric fields.

**Expected behavior**
I would like to attach a custom filter function to text field to filter data with provision to use >,<,>=,<= expressions to filter numeric data.
Add support to attach a custom filter function to text field to filter data as per our needs.

**What is the motivation / use case for changing the behavior?**
It will be very useful in financial websites where numeric data can be filtered using >,<,>=,<= expressions.

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
