### ISSUE TITLE
pass null value for validation on p-calendar time only

### ISSUE THREAD

**Issue by worldcreate** [primefaces/primeng#2277]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

Cant't pass null value when not required on p-calendar time only.

**Expected behavior**

pass null value when not required on p-calendar time only.

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
