### ISSUE TITLE
[BUG] Autocomplete - unable focus other control by tabulation key in advanced mode 

### ISSUE THREAD

**Issue by tom3kb** [primefaces/primeng#2281]
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**

Autocomplete in advanced mode doesn't allow to select next control on form after using tabulation key.

**Expected behavior**
Let tabulation change focus to a next control.

**Minimal reproduction of the problem with instructions**
Check autocomplete advanced example on https://www.primefaces.org/primeng/#/autocomplete

* **PrimeNG version:** 2.0.1

* **Browser:** [Chrome 56.0.2924.87 | Firefox 51.0.0 ]

The problem is changing focus back to an input control after handling dropdown button focus:
```javascript
onDropdownFocus() {
        this.dropdownFocus = true;
        this.inputEL.nativeElement.focus(); //<- problem in this line
    }
```

**Comment by xtoff** [comment]
Yeah, I find this really annoying.. You have to mouse click an item to select one..

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
