### ISSUE TITLE
Breadcrumb home mouseover displays default cursor

### ISSUE THREAD

**Issue by MrBreZe** [primefaces/primeng#2283]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
the home icon is displaying the cursor as default mouse cursor but on all other breadcrumbs the cursor is displayed as hand(cursor:pointer) so it looks like you can't click the homebreadcrumb.

**Expected behavior**
the home breadcrumb should behave like other breadcrumb elements. atleast a hand/pointer cursor is displayed while mouseover for the home breadcrumb

**Minimal reproduction of the problem with instructions**
mouseover the first breadcrumb (with home icon). https://www.primefaces.org/primeng/#/breadcrumb

**What is the motivation / use case for changing the behavior?**
users don't understand that they can navigate to home with this button

* **PrimeNG version:** 2.0.X
2.0.0

**Comment by sudheerj** [comment]
It makes sense to have cursor as pointer for home button.Even home button can be customized just like other menu items.

**Comment by cagataycivici** [comment]
Done but you need to use the home property to configure it like giving a router, otherwise it will be a readonly icon.
