### ISSUE TITLE
Lazy loading in datatable throws Expression has changed after it was checked error

### ISSUE THREAD

**Issue by BartoszBaczek** [primefaces/primeng#2285]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/ppY9dc3ugSqRxEcJiEsv?p=preview

**Current behavior**
Using lazy loading on data table component throws _Expression has changed after it was checked_ error.

**Expected behavior**
Using lazy loading should not throw errors

**Minimal reproduction of the problem with instructions**
Run plunker example and check log

**What is the motivation / use case for changing the behavior?**
No to throw a bug

**Please tell us about your environment:**
Operating system: Windows 10 64bit, 
IDE: VSCode, 
packagemanager: npm, 
httpserver: express

* **Angular version:** 2.0.X
2.2.1

* **PrimeNG version:** 2.0.X
2.0.3 (latest)

* **Browser:** [all]
 
* **Language:** [TypeScript 2.1.4.]

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
