### ISSUE TITLE
Lazy loading in data table with scrollable="true" makes content empty

### ISSUE THREAD

**Issue by BartoszBaczek** [primefaces/primeng#2286]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/eQPSdbAglMQK5AxSicce?p=preview

**Current behavior**
Using lazy loading on data table with scrollable="true" makes datatable content invisible

**Expected behavior**
Using lazy loading should not make datatable content invisible

**Minimal reproduction of the problem with instructions**
Run plunker example and see datatable content being empty. Also #2285.

**What is the motivation / use case for changing the behavior?**
Being able to use lazyloading with scrollable="true"

**Please tell us about your environment:**
Operating system: Windows 10 64bit, 
IDE: VSCode, 
packagemanager: npm, 
httpserver: express

* **Angular version:** 2.0.X
2.2.1

* **PrimeNG version:** 2.0.X
2.0.3 (latest)

* **Browser:** [all]
 
* **Language:** [TypeScript 2.1.4.]

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
