### ISSUE TITLE
PrimeNG DataTable Frozen Column Misaligned Rows Issue

### ISSUE THREAD

**Issue by mdg357** [primefaces/primeng#2287]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/D1AK7i

**Current behavior**
In IE10/IE11/Edge, the last row of a scrollable DataTable with at least one frozen column is misaligned when scrolled all the way to the bottom. It appears that IE10/IE11/Edge is not properly rending the padding that is supposed to be present to compensate the for the lack of the horizontal scroll bar on the frozen column(s).

**Expected behavior**
The last row of the frozen column should be vertically aligned with the last row of the unfrozen columns in the DataTable.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/DojpxL5czcNTW9pyN5CK

Open the Plunker in IE10/IE11/Edge and scroll all the way to the bottom of the datatable.

**What is the motivation / use case for changing the behavior?**
Broken functionality

**Please tell us about your environment:**

* **OS:** Windows 7
* **IDE:** Visual Studio Code
* **Package manager:** JSPM

* **Angular version:** ~2.2.0

* **PrimeNG version:** ^2.0.1

* **Browser:** IE10, IE11, Edge
 
* **Language:** TypeScript

* **Node (for AoT issues):** 6.9.1

**Comment by cagataycivici** [comment]
This has been discussed a couple of times, you need to set min-height of datatable rows;

```
.ui-datatable tbody > tr {
   min-height:30px;
}
```

We don't to do to avoid performance as we need to calculate things, so leave to the user.
