### ISSUE TITLE
DataTable Dynamic Columns with Frozen Columns

### ISSUE THREAD

**Issue by mdg357** [primefaces/primeng#2288]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/D1AK7i

**Current behavior**
This issue is related to Issue #2287 

To fix the row misalignment that occurs in IE10/IE11/Edge when scrolling to the bottom of the table, we have made the horizontal scrollbar visible for the frozen column(s). While this solves the alignment, it causes another issue when manipulating the array used for the dynamic columns. 

I suspect, but cannot conclusively confirm that this is due to how the array of frozen columns is built in the `initColumns()` function of the `DataTable` class. Specifically, this section:

```
if(col.frozen) {
    this.frozenColumns = this.frozenColumns||[];
    this.frozenColumns.push(col);
} 
```

**Expected behavior**

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/g3WbR9

1. Click either the "Add Column" or the "Reset" button. Notice that the frozen column is now duplicated. 

**What is the motivation / use case for changing the behavior?**
Eliminate the need for a workaround caused by another issue.

**Please tell us about your environment:**

* **OS:** Windows 7
* **IDE:** Visual Studio Code
* **Package manager:** JSPM

* **Angular version:** ~2.2.0

* **PrimeNG version:** ^2.0.1

* **Browser:** IE10, IE11, Edge, Chrome
 
* **Language:** TypeScript

* **Node (for AoT issues):** 6.9.1

**Comment by taozhiw** [comment]
```javascript 
initColumns(): void {
        this.columns = this.cols.toArray();
        // reset frozenColumns  and scrollableColumns 
        this.frozenColumns = [];
        this.scrollableColumns = [];
        if(this.scrollable) {
            this.scrollableColumns = [];
            this.cols.forEach((col) => {
                if(col.frozen) {
                    this.frozenColumns = this.frozenColumns||[];
                    this.frozenColumns.push(col);
                }
                else {
                    this.scrollableColumns.push(col);
                }
            });
        }

        this.columnsChanged = true;
    }
```

**Comment by taozhiw** [comment]
```javascript
initColumns(): void {
        this.columns = this.cols.toArray();
        if(this.scrollable) {
            this.scrollableColumns = [];
            // reset frozenColumns
            this.frozenColumns = null;
            this.cols.forEach((col) => {
                if(col.frozen) {
                    this.frozenColumns = this.frozenColumns||[];
                    this.frozenColumns.push(col);
                }
                else {
                    this.scrollableColumns.push(col);
                }
            });
        }

        this.columnsChanged = true;
    }
```

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
