### ISSUE TITLE
Exception TypeError using Dialog 

### ISSUE THREAD

**Issue by final87** [primefaces/primeng#229]
Hello everyone, I'm using primeNG in a project and I'm very thankful for your great work.

Now I'm trying to add a yes/no dialog but using `<p-dialog/>` I got this exception:
_node_modules/angular2/src/platform/browser/browser_adapter.js:85 
**EXCEPTION: TypeError: jQuery(...).puidialog is not a function**_

my _page.html_ is like this:
```
<div>
  <p-dialog header="Title" [(visible)]="display">
    Content
</p-dialog>
...
     <p>
      <button (click)="displayDialog()" type="button" class="btn btn-danger" >Open Dialog</button>
    </p>
</di>
```

while the extract from  _page.ts_ is:
```
import {Component, OnInit} from 'angular2/core';
import {Router, RouteParams} from 'angular2/router';
import {HTTP_PROVIDERS} from 'angular2/http';
import {BUTTON_DIRECTIVES} from 'ng2-bootstrap/ng2-bootstrap';
import {Dialog} from 'primeng/primeng';
...

@Component({
	selector: 'sm-newPersPage',
	templateUrl: 'page.html',
    directives: [BUTTON_DIRECTIVES, Dialog],
    providers: [HTTP_PROVIDERS]
})
export class NewPersCmp implements OnInit {
  display: boolean = false;

   constructor(
      private _router: Router,
      private _routeParams:RouteParams
      ) {}

  displayDialog() {
     this.display = true;
  }
...
}
```

Probably I'm not using this library in a good way, any idea for that kind of error?

my dependencies are:
"angular2": "2.0.0-beta.9",
    "primeng": "^0.9.1",
    "primeui": "^4.1.8",
    "es6-shim": "^0.33.3",
    "systemjs": "0.19.24",
    "zone.js": "0.5.15"

thanks

**Comment by cagataycivici** [comment]
Welcome, I think you miss,

<script src="node_modules/primeui/primeui-ng-all.min.js"></script>

Please see setup section at;

http://www.primefaces.org/primeng/#/setup

**Comment by final87** [comment]
Yes, I put it in a wrong place.
thank you

**Comment by cagataycivici** [comment]
Good to hear, thank you.
