### ISSUE TITLE
Lightbox positioning issue

### ISSUE THREAD

**Issue by godzillar** [primefaces/primeng#2292]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When lightbox opens an image and clicking previous or next button the image is pushed down a bit. This can be reproduced in the showcase page.

**Expected behavior**
The lightbox should center itself correctly.

**Minimal reproduction of the problem with instructions**
- Open the showcase page and select the lightbox menu item.
- Open the lightbox component by clicking a thumbnail image
- Click the next/prev button.
- Watch the lightbox being pushed down.

* **PrimeNG version:** 2.0.3

* **Browser:** [all]
 
* **Language:** [TypeScript 2.0.3]

* **Node (for AoT issues):** `node --version` =   6.9.2

**Comment by godzillar** [comment]
Btw: The behaviour as described only occurs when a title is used for the images

**Comment by SIlver--** [comment]
You can replicate the issue with the lightbox demo https://www.primefaces.org/primeng/#/lightbox

Going back and forth between images has it slowly go down the page.

**Comment by cagataycivici** [comment]
Yes, it seems to go down. @Mrtcndkn Take over please.
