### ISSUE TITLE
ContextMenu support for Listbox

### ISSUE THREAD

**Issue by skormel** [primefaces/primeng#2293]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

Listbox it's a great component but it has not support for context menu.

**Expected behavior**

Add context menu to listbox.

**What is the motivation / use case for changing the behavior?**

It'll be very interesting the posibility to add a context menu to show action related to selected element in the listbox.

**Comment by deniskrafczyk** [comment]
Are there any updated to this feature yet? 
I need this feature for a Datatable Column toggler inside contextmenu.

**Comment by skormel** [comment]
Is there any update on this new feature??

**Comment by ErikPhilips** [comment]
I didn't really have any trouble adding a context menu.

[Stackblitz Example](https://stackblitz.com/edit/primeng-template-project-angular-11-trn3zr)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
