### ISSUE TITLE
Option to disable animations in some components

### ISSUE THREAD

**Issue by danielordonez** [primefaces/primeng#2297]
We're currently using the p-calendar component in our project and it would be nice to let us decide which animations  should be used for the component rather than defaulting on an ease-in, ease-out of 400ms (maybe even be able to disable them or change it's duration), they are not bad looking, they just don't fit our design and we're forced to keep them that way if we don't want to modify the package.

**Comment by cagataycivici** [comment]
I see, please create specific issues for each one and we'll review.

**Comment by qetr1ck-op** [comment]
@cagataycivici @cagataycivici any progress here?
