### ISSUE TITLE
DropDown 

### ISSUE THREAD

**Issue by brachi-wernick** [primefaces/primeng#2302]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
if I have  this drop down (from here https://www.primefaces.org/primeng/#/dropdown)
```<p-dropdown [options]="cars" [(ngModel)]="selectedCar" [style]="{'width':'150px'}" editable="editable" placeholder="Select a Brand"></p-dropdown>```
and I want to type in and to search for the matching item.
currently all what I can do is to use `filter="filter"` and then if I will click the drop down icon I will see different search box in the drop down,
but still there I need to type and then *select* the suggestion.

**Expected behavior**
I want to type in the drop down input and to be completed if match was found.
for example if type `B` or `b` to get `BMW`. 
![dropdown suggest](https://cloud.githubusercontent.com/assets/3658085/23947080/cda88050-0985-11e7-9f6a-ffc4024442df.gif)
attached a gif demonstrates this:
I type `f` and I got `Fiat` I type `b` and got `BMW` I type `a` and got `Audi` no click.

**What is the motivation / use case for changing the behavior?**
I want to be able to fill in the form with keyboard only, without click, now I in the current implementation it requires click to search and another click to select.

**Comment by Nareshtekula** [comment]
This link  [https://www.primefaces.org/primeng/#/dropdown](url) has following error in console:
Uncaught TypeError: Cannot read property 'call' of undefined.

**Comment by brachi-wernick** [comment]
@Nareshtekula for me no, any way open your demos on input/drop down

**Comment by cagataycivici** [comment]
I think your use case is more or less similar to autocomplete component with dropdown mode.

**Comment by brachi-wernick** [comment]
@cagataycivici  seems like I must to do `setTimeout` this in order to see the drop down when clicking.
as your example code:
`handleDropdownClick() {
        this.filteredBrands = [];
        
        //mimic remote call
        setTimeout(() => {
            this.filteredBrands = this.brands;
        }, 100)
    }`
