### ISSUE TITLE
Incorrect semantic use of HTML label element in multiselect

### ISSUE THREAD

**Issue by phil-hutchinson** [primefaces/primeng#2306]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
N/A - issue affects all multiselect elements

**Current behavior**
The multiselect element displays its contents inside a `<label>` element, but the purpose of a label is to associate text that describes a control to the control itself (usually via the `for` attribute, or alternatively by placing the control between the start and end tags of the label.) This can be seen inside the template of the control in file components/multiselect/multiselect.ts, in the content

    <label>{{option.label}}</label>

**Expected behavior**
This content should be displayed within an alternate HTML tag (probably a `<span>`) instead of a `<label>`, e.g.:

    <span>{{option.label}}</span>

**Minimal reproduction of the problem with instructions**
Add a multiselect control to a page, and add some values.
Run the page, select some values, and then use browser developer tools to see what HTML element is being used to hold the list of selected items.

**What is the motivation / use case for changing the behavior?**
When `<label>` tags are used incorrectly, this can cause accessibility issues for people with disabilities who require a screen reader to use the web, as the screen reader will expect this label to provide descriptive text for a control.

**Please tell us about your environment:**
Windows 7, VS2015, npm, IIS (but not really applicable)

* **Angular version:** 2.4.3

* **PrimeNG version:** 2.0.0-rc.3 (however, I have verified this is still the same in the current source code.)

* **Browser:** all 
 
* **Language:** all

* **Node (for AoT issues):** `node --version` =   
N/A

**Comment by cagataycivici** [comment]
Agreed, we need to change it for 4.1.1.
