### ISSUE TITLE
Templates not working after upgrade

### ISSUE THREAD

**Issue by karthiks3000** [primefaces/primeng#2309]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

I just upgraded to Angular 4 RC 3 & upgraded to PrimeNG 4, but now the templates used in the data tables no longer work. I have buttons defined in the header of columns which don't appear anymore and row expansion throws the following error-

Cannot read property 'createEmbeddedView' of undefined

These were all working in the previous versions of PrimeNG.

**Comment by digitalcraftco** [comment]
<template> syntax has been depreciated in Angular 4. Try using <ng-template>. https://github.com/angular/angular/blob/master/CHANGELOG.md

**Comment by karthiks3000** [comment]
actually angular 4 still supports <template> but will be depreciated soon. For now they are only displaying a warning. The error turned out to be because of an incorrect case (ptemplate instead of pTemplate).

I still had to rollback the update to the previous versions of angular & PrimeNG because of some other issues that cropped up. 

Thanks!
