### ISSUE TITLE
orderlist styling with Modena theme a bit broken

### ISSUE THREAD

**Issue by gatapia** [primefaces/primeng#231]
Styling of order list is a little broken in the Modena theme:

![image](https://cloud.githubusercontent.com/assets/135965/14697926/2fafdfe4-07cc-11e6-8f5a-8854061b71ea.png)

My markup:
```
<p-orderList *ngIf="entities" [value]="entities">
  <template #entity>
    <li class="ui-orderlist-item ui-helper-clearfix">      
      <div>{{entity.Name}}</div>
    </li>
  </template>
</p-orderList>
```
I'm pretty sure (95%) that I dont have random CSS interacting with this page also.

**Comment by cagataycivici** [comment]
We'll checkor the upcoming modena, thank you.

cc @mertsincan @Mrtcndkn

**Comment by cagataycivici** [comment]
We're unable to replicate I'm afraid.
