### ISSUE TITLE
PropagateExpand for TreeNode

### ISSUE THREAD

**Issue by jisqaqov** [primefaces/primeng#2313]
Good day. There are cases when tree is big enough it is better to expand nodes which are partiallySelected or just selected. So, we need some kind of **propagateExpandUp** and **down**. In addition, users now can not see that nodes are selected because root node is not expanded.

**Comment by cagataycivici** [comment]
As it is a bit custom requirement, I'd suggest handling this on your side using onExpand event where you can get the expanded node and expand all descendants as well.
