### ISSUE TITLE
Calendar doesn't work with angular 2 forms

### ISSUE THREAD

**Issue by binjiezhao** [primefaces/primeng#2319]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

https://plnkr.co/edit/TQeXga

**Current behavior**

Throws error: Template parse errors:
Can't bind to 'formGroup' since it isn't a known property of 'form'.

**Expected behavior**

Render calendar in the angular 2 model driven form.

**Minimal reproduction of the problem with instructions**

Please see the plukr example: https://plnkr.co/edit/TQeXga

**What is the motivation / use case for changing the behavior?** 

According to the primeNG demo link https://www.primefaces.org/primeng/#/calendar , this should work:
Model Driven Forms
Calendar can be used in a model driven form as well.
<p-calendar formControlName="date"></p-calendar>

But it doesn't work under standard angular 2 model driven form setup.

**Please tell us about your environment:**

Windows 7, vs2015, npm, 
* **Angular version:** 2.0.X

Angular v2.4.5
* **PrimeNG version:** 2.0.X

primeNG v2.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by luchillo17** [comment]
Hi, it works all right for me when using the `[formGroup]='formFieldInClass'`, maybe is the angular version? i'm using angular 4 (though i shouldn't because primeng asks for angular 2 😝 ).

**Comment by codechamploo** [comment]
Throws error: Template parse errors:
Can't bind to 'formGroup' since it isn't a known property of 'form'.

The error stated maybe a result of not including the ReactiveFormsModule in the app.module.ts.  I tried it on the plunkr and the stated error goes away.

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
