### ISSUE TITLE
Filter Issues on DataTable

### ISSUE THREAD

**Issue by karthiks3000** [primefaces/primeng#2320]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

I am using PrimeNG 2.0.3 and am facing 2 issues with the filter functionality on the DataTable
**Issue 1:**
The global filter does not seem to work if the textbox is placed outside the div tag mentioned in the sample on the PrimeNG page. I have the following textbox code -
`<input #gb type="text" pInputText  placeholder="Global Filter">`

 and the following datatable definition

` <p-dataTable #dtPrograms [value]="contentRecords" expandableRows="true" 
                resizableColumns="true" columnResizeMode="expand"
                [paginator]="true" [pageLinks]="3" [rows]="10" [rowsPerPageOptions]="[5,10,20]"
                [globalFilter]="gb"  reorderableColumns="true" exportFilename="ContentProtectionDashboard"
                >`

But this does not work. However, the following lines of code work - 
`<div class="ui-widget-header" style="padding:4px 10px;border-bottom: 0 none">`
    `<i class="fa fa-search" style="margin:4px 4px 0 0"></i>`
    `<input #gb type="text" pInputText size="50" placeholder="Global Filter">`
`</div>`

**Issue 2:**
I get an error when I try to apply filter on the child band 
Here is my filter code - 
`<p-accordionTab header="Episode #">
                    <p-listbox  [style]="{'width':'180px'}" [options]="filterEpsNums" [(ngModel)]="selectedEpsNums" multiple="multiple" checkbox="checkbox" filter="filter" (onChange) = "dtEpisodes.filter(selectedEpsNums,'short_name','in')"></p-listbox>
                </p-accordionTab>`

dtEpisodes is a child band of dtPrograms -

` <p-dataTable #dtEpisodes [value]="cp.submissions" expandableRows="true"   reorderableColumns="true">  `

Filters on the main table work, but the filter on the child table throws the following exception
                  
Error in ./DashboardComponent class DashboardComponent - inline template:24:20 caused by: Cannot read property 'filter' of undefined

Here is a snapshot of how my UI looks-
![image](https://cloud.githubusercontent.com/assets/13357707/24008554/52ef014a-0a48-11e7-9880-42773aa1232c.png)

**Comment by karthiks3000** [comment]
After some more digging I found out that '#dtEpisodes' is not able to find the data table within the template. While '#dtPrograms' works, using '#dtEpisodes' doesn't work. I even tried to access the element using view child but no luck. 

Any suggestions??

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
