### ISSUE TITLE
p-calender width not supporting

### ISSUE THREAD

**Issue by shashi97** [primefaces/primeng#2321]
```
<div class="form-group">
          <label for="name" class="lbl-text">Scan Date</label>
          <p-calendar [style]="{'width':'100%'}" [(ngModel)]="workOrder.scanDate" [showIcon]="true"></p-calendar>
        </div>
```

**Comment by cagataycivici** [comment]
Use inputStyle instead.

**Comment by unaor** [comment]
doesnt work with % only with px tested with 5.2.0
            <p-calendar [(ngModel)]="endBy" name="endBy" (click)="checkAddDeviceConditions()" [showTime]="true" [showIcon]="true" [minDate]="startBy || now" dateFormat="dd.mm.yy" styleClass="swat-calendar-device" [inputStyle]="{'width':'213.2**px**'}"></p-calendar>

**Comment by villanuevacarlos14** [comment]
if you want to use width,

<p-calendar [style]="{'width':'95%'}" [inputStyle]="{'width':'95%'}"

**Comment by nathapob** [comment]
Thank Sir It's work

**Comment by ngoc31031997** [comment]
i try                                
 <p-calendar 
[style]="{'width': '100%'}" 
[inputStyle]="{'width':'100%'}">
 </p-calendar>
but it dont working
