### ISSUE TITLE
Update 'Building From Source' on wiki

### ISSUE THREAD

**Issue by keyvhinng** [primefaces/primeng#2322]
```
[X] bug report
[ ] feature request 
[ ] support request 
```
**Current behavior**
Steps on [Building From Source](https://github.com/primefaces/primeng/wiki/Building-From-Source) do not produce a working application. It lacks of a task to build the theme. On #2301 @qjlee shows a working gulp file to build the project successfully.

**Expected behavior**
Gulp file should include a task to build the theme.

**Comment by cagataycivici** [comment]
A bit obselete after we've migrated to CLI.
