### ISSUE TITLE
Add onRowClick to DataTable

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#233]
Pass the current rowData as the parameter along with actual click event.

**Comment by smallfresher** [comment]
I have the same trouble ! I want to how to save the problem .
I need to click row of the datatable and acquire the document content.
Please tell me,if you have . Thank you !

**Comment by cagataycivici** [comment]
We'll do it for beta4 in a couple of days. Please monitor this ticket. Right now workaround is defining a selectionMode and use onRowSelect event.
