### ISSUE TITLE
'ng-template' is not a known element:

### ISSUE THREAD

**Issue by skorunka** [primefaces/primeng#2333]
After adding FileUpload I got this runtime error:
![image](https://cloud.githubusercontent.com/assets/218913/24040486/5764bd6e-0b01-11e7-9712-bc1d52fb3294.png)

Other components(radio, checkbox) work fine.

My project is based on https://github.com/aspnet/JavaScriptServices/tree/dev/templates/Angular2Spa

In webpack(webpack.config.vendor.js) I'm referencing these dependencies:
				'primeng/components/fileupload/fileupload',
				'primeng/components/fileupload/fileupload.css',

And FileUploadModuleis registered in app.module.ts.

Any ideas?

**Comment by skorunka** [comment]
"PrimeNG 4 requires Angular 4, if you are on Angular 2 use PrimeNG 2.0.x instead."

After downgrading to 2.0.x, problem sorted.

**Comment by balajiswaroop** [comment]
I am getting the below error.

**'ng-template' is not a known element:**

package.json 
---------------
"primeng": "^2.0.4",
"@angular/core": "^2.4.0",

app.module.ts
----------------
Imported the below modules 
DataTableModule,
SharedModule

Looks like its unable to find the module in which the "ng-template" directive is present.
Please help.

**Comment by anubhavNPA** [comment]
got the same error - 
my html is -- 
<p-pickList [source]="sourceCars" [target]="targetCars" sourceHeader="Available" targetHeader="Selected" [responsive]="true" [sourceStyle]="{'height':'300px'}" [targetStyle]="{'height':'300px'}">
    <ng-template let-car pTemplate="item">
        <div class="ui-helper-clearfix">
            <img src="showcase/resources/demo/images/car/{{car.brand}}.gif" style="display:inline-block;margin:2px 0 2px 2px"/>
            <div style="font-size:14px;float:right;margin:15px 5px 0 0">{{car.brand}} - {{car.year}} - {{car.color}}</div>
        </div>
    </ng-template>
</p-pickList>
**************
component-ts -just the 2 lists initialised with data
*****************
App.Module
import {PickListModule, ConfirmDialogModule, SharedModule} from from 'primeng/primeng';
@NgModule({
  imports: [PickListModule, ConfirmDialogModule, SharedModule]

But for me my other code with DataTableModule works fine

**Comment by AKorshunov87** [comment]
@balajiswaroop 
> I am getting the below error.
> 'ng-template' is not a known element:

I had exactly the same problem today on
"primeng": "^2.0.4",
"@angular/core": "2.4.9",

found a solution:
**use 'template' instead of 'ng-template' in your html template.**

I think that errors appears because of version, that is ng-template added only in Angular 4 core.

**Comment by mkwsra** [comment]
using `template` tag works just fine, thanks a lot @AKorshunov87

**Comment by skorunka** [comment]
`ng-template` is Angular4 only, you need to target primeng version which is build for Angular2

**Comment by MakhouT** [comment]
`template` worked for me too. Thanks!

**Comment by GIOkafor** [comment]
`template` worked for me too. Thank you!!

**Comment by TarsemKashyap** [comment]
template work for me too !! just find mutliselect-dropdown.ts replace ng-template with template

**Comment by lucky9abhi** [comment]
I'm getting the same error..but I couldn't find where to replace the ng-template to just template. Help plz...

**Comment by TarsemKashyap** [comment]
@lucky9abhi you can find this file "mutliselect-dropdown.ts" inside node_modules folder with package name you installed.

**Comment by usshweoo** [comment]
<template> is work fine . thank you

**Comment by Mohanr1122** [comment]
i'm getting same error, when using p-picklist in ngprime, can you please tell me how to use "template" insted of "ng-template"?
