### ISSUE TITLE
Provide 'Show All' option in datatable's rows per page list

### ISSUE THREAD

**Issue by padryn** [primefaces/primeng#2334]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**What is the motivation / use case for changing the behavior?**

Provide a 'Show All' type option in the datatable paginator.

Justification.  While this behavior can be achieved be calculating the size of the dataset shown in the table and adding that to the rowsPerPageOptions list, that isn't as visually attractive as a text option for 'show all' would be.

**Comment by cagataycivici** [comment]
We plan to add custom content support to paginator where you can add functionality like this instead of adding it to rowsPerPage. We've noted this down, thank you.

**Comment by BeelineDevelopers** [comment]
Can someone please explain to me how to achieve this?  I've put in a custom solution that doesn't work very well, just wondering why it isn't as simple as adding 'All' and having custom handling for it?  

I tried implementing the "onPage()" function, and it only seems to be called for integers (i.e. added 'All' to the rowsPerPageOptions and it didn't call the function).

**Comment by mahipalsa** [comment]
Any Update on this one?
