### ISSUE TITLE
PrimeNG / UltimaNG : floating label not refreshed when no more selected data in autocomplete

### ISSUE THREAD

**Issue by minato-namikaze** [primefaces/primeng#2335]
**I'm submitting a bug **

**Current behavior**
In an autocomplete component, pick up a data
Click on the cross
If no more data in the input then the floating label of the component is not refreshed (displayed in the input like a placeholder)

**Expected behavior**
The floating label must be reset and fell like a placeholder

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Reproductible on Chrome

* **Angular version:** 2.0.1

* **PrimeNG version:** 2.0.0

* **Browser:** [ Chrome 56 ]

* **Node (for AoT issues):** `node --version` =   7.5.0

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
