### ISSUE TITLE
AutoScroll for drag drop components

### ISSUE THREAD

**Issue by brettkc** [primefaces/primeng#2338]
**I'm submitting a ...**  
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Drag & Drop module when you begin dragging an element but have a drop target not currently in the active viewport you are unable to scroll to the drop target.

**Expected behavior**
Would be nice to have some sort of auto scroll when you've got a draggable being dragged to the bottom and top of the screen.

**What is the motivation / use case for changing the behavior?**
Better drag and drop module behavior..

* **Angular version:** 4.0.0-rc.1

* **PrimeNG version:** 4.0.0-rc.1

**Comment by cagataycivici** [comment]
Agreed, I've done it in Picklist and Orderlist. Same solution can be applied to viewport as well.

**Comment by VladimirRadeski** [comment]
@cagataycivici  Any update for this enhancement?

**Comment by nvonbenken** [comment]
@cagataycivici any update on this?

**Comment by AyyappanBoston** [comment]
@cagataycivici is there any update for this?

**Comment by MeMeMax** [comment]
@cagataycivici I don´t want to bother but... any update on this?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
