### ISSUE TITLE
setTimeout call in Ultima

### ISSUE THREAD

**Issue by rkrisztian** [primefaces/primeng#2340]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
This is not really about a bug report, but about a possible design smell.

Ultima 2.01 has the following code in `app.component.ts`:

```
    ngAfterViewInit() {
(...)        
        setTimeout(() => {
            jQuery(this.layoutMenuScroller).nanoScroller({flash:true});
        }, 10);
    }
```

**Expected behavior**
I don't think it is a clean design to use `setTimeout` in a web application, and it should be use are rarely as possible. Moreover, using jQuery in an Angular application looks odd to me already. There may be valid exceptions, I am wondering however if we can avoid the use of `setTimeout` above. If there is a pure Angular way to implement the scoller, I would drop jQuery completely, but that would rather be a feature request. We could consider alternatives like `ng2-slimscroll`, although it isn't transparent when not hovered.

**Minimal reproduction of the problem with instructions**
N/A

**What is the motivation / use case for changing the behavior?**
Cleaner design.

**Please tell us about your environment:**
Does not matter.

* **Angular version:** 2.0.X
2.4.0

* **PrimeNG version:** 2.0.X
2.0.0-rc3, Ultima: 2.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Does not matter.
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.0.3

**Comment by cagataycivici** [comment]
This is not the correct issue tracker, please use the Ultima issue tracker instead.

https://github.com/primefaces/ultima-ng/issues

**Comment by rkrisztian** [comment]
=> https://github.com/primefaces/ultima-ng/issues/56
