### ISSUE TITLE
onFocus not working in Autocomplete

### ISSUE THREAD

**Issue by Yura13** [primefaces/primeng#2342]
I'm submitting a bug - onFocus not working in Autocomplete component.

**Plunkr Case (Bug Reports)**
https://plnkr.co/edit/bMYjxu7O3scmqiNSYhd7?p=preview

**Current behavior**
When input has focus(don't typing any character inside input field), list of items don't show

**Expected behavior**
List should show.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/bMYjxu7O3scmqiNSYhd7?p=preview

* **Angular version:** 2.0.X
2.4.9

* **PrimeNG version:** 2.0.X
2.0.4

* **Browser:** all 

* **Node (for AoT issues):** `node --version` =   6.10.0

**Comment by cagataycivici** [comment]
Can you replicate at liveshowcase? The plunkr works for me (chrome).

**Comment by cagataycivici** [comment]
It works for me, if I correct the timeout;

```
    setTimeout(() => {
      this.filteredItems = this.items;
    }, 100);
```

**Comment by Yura13** [comment]
It works only first time focus and if you press key "down".

**Comment by Yura13** [comment]
List of items don't show when input has focus
