### ISSUE TITLE
Datatable multisort does not work when one column contains date type

### ISSUE THREAD

**Issue by ryanwawr** [primefaces/primeng#2343]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When a datatable's sort mode is set to 'multiple', sorting on multiple columns breaks if one of the columns contains date types. This is because the multisortField function in datatable.ts, specifically the segment copied below, does not correctly account for the way date comparisons work in JavaScript.

```
else {
    result = (value1 < value2) ? -1 : 1;
}

if(value1 == value2)  {
    return (multiSortMeta.length - 1) > (index) ? (this.multisortField(data1, data2, multiSortMeta, index + 1)) : 0;
}
```

A detailed explanation of date comparison in JavaScript can be found [here](http://stackoverflow.com/questions/7244513/javascript-date-comparisons-dont-equal).

In short, the '==' comparison will fail for two identical dates in JavaScript because the operator is comparing the objects, not their values. Therefore, if two dates are equal, the ```else``` block in the code above will set result to 1, then the ```if``` block will be skipped, even though the values of the dates are equal. This causes sorting on any subsequent fields in the multisort meta array to be skipped.

**Expected behavior**
The mutlisortField function should contain separate logic for handling Date types that compares the results of the valueOf or getTime functions defined on the Date type rather than using the '==' operator to compare the objects. Something like the modification below should work.

```
let equalDates: boolean = value1 instanceof Date && value2 instanceof Date && value1.valueOf() === value2.valueOf();

if(value1 == value2 || equalDates)  {
    return (multiSortMeta.length - 1) > (index) ? (this.multisortField(data1, data2, multiSortMeta, index + 1)) : 0;
```

**Minimal reproduction of the problem with instructions**

1. Create a datatable that has sortMode set to multiple and has at least one column that contains Date types
2. Sort the table by multiple columns, one of which must be the date column. The bug will only manifest if the date column is not last in the sort order.
3. Sorting should fail on any column that follows the date column in the sort order.

**What is the motivation / use case for changing the behavior?**
the current behavior is incorrect and should be considered a fairly serious bug

**Please tell us about your environment:**
Windows 10, using Visual Studio 2015, running through webpack 

* **Angular version:** 2.0.X
2.0.0

* **PrimeNG version:** 2.0.X
1.1.4 (but the code in question is the same in the most recent version, so the behavior should not have changed)

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 56
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.1.0

* **Node (for AoT issues):** `node --version` =   
6.9.4

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
