### ISSUE TITLE
AppendTo body closes MultiSelect

### ISSUE THREAD

**Issue by Danieleeee** [primefaces/primeng#2345]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

See issue: p-multiSelect in dataTable no overflow visible #2231

* **Angular version:** 2.4.X

* **PrimeNG version:** 2.0.4

* **Browser:** [Chrome XX | IE XX ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by Saaether** [comment]
Getting this as well, when appendTo is set to body then any clicks on the drop down causes it to close which makes it so you cant use the filter by text at all

**Comment by nag0538** [comment]
.ui-datatable-scrollable-header {
    overflow: visible;
} 

this thing worked for me 
note:remove appendTo="body"

**Comment by Saaether** [comment]
Awesome! thanks nag0538

**Comment by cagataycivici** [comment]
PR checked in.
