### ISSUE TITLE
p-panel border issue

### ISSUE THREAD

**Issue by deveshsinghal22** [primefaces/primeng#2348]
When I use the div inside panel. It closes the border before the content.

I am attaching an screenshot. It works fine if we use other tag directly. but not with div
![panel-issue](https://cloud.githubusercontent.com/assets/2578290/24144618/f14f1960-0e53-11e7-98cf-dc2fea53afcc.png)

**Comment by sudheerj** [comment]
I can't replicate the issue with latest PrimeNG 4RC release.You should provide some code snippets or try it out on showcase.

**Comment by deveshsinghal22** [comment]
I think, I was facing this due to some misplaced div. 
Thanks for the quick response . 
closing this
