### ISSUE TITLE
[Bug] Dropdown doesn't close when another is open

### ISSUE THREAD

**Issue by snowdave86** [primefaces/primeng#235]
When a user selects another dropdown to open while one is currently open, it doesn't close the other dropdown as expected.

**Comment by cagataycivici** [comment]
What is your PrimeNG version?

**Comment by snowdave86** [comment]
I apologize - I was using 1.0.0-beta.2 and see that is no longer a problem.

**Comment by cagataycivici** [comment]
Yes, we've fixed that in beta.3. Thank you for the update.
