### ISSUE TITLE
[Bug] SlideMenu submenu always display: none

### ISSUE THREAD

**Issue by luchillo17** [primefaces/primeng#2352]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**
Checkout this repo with develop branch, run `npm start` and check the left menu when clicking the 'Graphics' menu item:
https://github.com/Luchillo/Luchillo-tech-showcase/tree/develop

**Current behavior**
The class `.ui-menu .ui-menu-parent .ui-menu-child` forces always `display: none` on the subMenu `ul` element. (Check first 2 images attached).

**Expected behavior**
Well, expected the subMenu to just show. (check last image attached after removing the `display: none` property from the subMenu's `ul` element).

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**
OS: Mac OS

Npm: 4.4.1

* **Angular version:** 2.4.6

* **PrimeNG version:** 2.0.5

* **Browser:** [all | Chrome 56 ]
 
* **Language:** [TypeScript 2.2.1]

* **Node (for AoT issues):** `node --version` =   6.9.4

**Aditional info**
First 2 images when transitionig from main menu to `Graphics` submenu, third one showing the expected result after finding the `ul` element and deactivating the `display: none` style.
![image](https://cloud.githubusercontent.com/assets/9698639/24165518/972dc4e6-0e3e-11e7-8de9-6c4e08753660.png)

![image](https://cloud.githubusercontent.com/assets/9698639/24165552/abb5d94e-0e3e-11e7-8da1-411463f83254.png)

![image](https://cloud.githubusercontent.com/assets/9698639/24165667/ffec464c-0e3e-11e7-8902-aca49b9bdbbe.png)

**Comment by sudheerj** [comment]
Can you please create simple plunker example instead of your github project(which has many other dependencies). Also can you please add step by step instructions to replicate.The above description is not bit clear.

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
