### ISSUE TITLE
Drop down list onChange not working

### ISSUE THREAD

**Issue by bluethefish** [primefaces/primeng#2353]
**Current behavior**
<p-dropdown [options]="mappingOptions" placeholder="Select Field" (onChange)="onFieldChange=($event)"></p-dropdown>

The onChange event is not been called.

**Expected behavior**
onChange callback should be called.

* **Angular version:** 2.0.X
2.4.10

* **PrimeNG version:** 2.0.X
2.0.5

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by Alex19ey** [comment]
Have the same issue:
Angular 2.4.6
PrimeNG 2.0.4

**Comment by Alex19ey** [comment]
I found the problem, instead of `(onChange)="onAccountSelect"` should be `(onChange)="onAccountSelect($event.value)"`

**Comment by cyberrranger** [comment]
works without $event

`<p-dropdown [options]="languages" [(ngModel)]="value" (onChange)="onChange()" [autoWidth]="false">
        </p-dropdown>`

**Comment by smitpsanghavi** [comment]
My `(onChange)` event gets fired even if I select the same item once again. Technically, it is not a change from the previous selection so this shouldn't happen.

Can somebody verify this?

**Comment by cyberrranger** [comment]
> Can somebody verify this?

yes, (onChange) is fired if I select the same item once again

**Comment by smitpsanghavi** [comment]
Thanks @cyberrranger 
In this case an issue needs to be raised for this. This behavior is actually not correct and needs to be corrected.

**Comment by cagataycivici** [comment]
Tracked at #2760

**Comment by clokworker** [comment]
Hello i was wondering if i wanted to fire the onChange event whiel selecting same item how could i do it?

**Comment by satyanarayanaAmzur** [comment]
please add a condition and use the findIndex  array method based on the index implement the conditional flow of selection code execution

**Comment by Alicia-Peraza** [comment]
s
