### ISSUE TITLE
p-dropdown ultima needs double click to select

### ISSUE THREAD

**Issue by vorenus181** [primefaces/primeng#2358]
**Current behavior**
While using Ultima theme primeng dropdown needs double click to select the value. Pushing Enter key works fine.

* **Angular version:** 2.4.9

* **PrimeNG version:** 2.0.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by ernestomar** [comment]
I'm using Ultima and p-dropdown without problem. Can you send code for reproduce the error?

**Comment by vorenus181** [comment]
I've already got solution. I was using getter function as items source of p-dropdown. With simple array property everything works fine. Thanks for your attention.

**Comment by abannsunny** [comment]
Hi,

This is still an issue.

https://stackblitz.com/edit/test-p-table-msxkby?file=package.json

I just updated the stackblitz to primeng 6. 
https://stackoverflow.com/questions/51720979/primeng-dropdown-needs-doubleclick-when-using-a-function-for-options

Is there a reason why getter shouldn't be used?

Thank you,
Abann

**Comment by i-amn** [comment]
This needs to be resolved, what if we want to show options in for loop and according to the key?

**Comment by MHacker9404** [comment]
I just ran into this issue with version 6.1.4

**Comment by leniel** [comment]
For anyone facing the same problem, here's the solution: https://stackoverflow.com/a/72148712/114029
