### ISSUE TITLE
tree : fa-caret-right showing up for leaf node

### ISSUE THREAD

**Issue by kevi793** [primefaces/primeng#2363]
I have followed your tree demo. But for the leaf nodes also there is fa-caret-right. I tried setting leaf:true, children:[], but was not able to remove the right-caret. Can anybody help?

**Comment by EdSteenhoek** [comment]
same here...

**Comment by cagataycivici** [comment]
I don't understand, do you have a screenshot?

**Comment by EdSteenhoek** [comment]
Need to do so further testing. It appears as if I face the same issue, yet it might be a data issue where the rest call returns false in stead of the expected true... Will update a.s.a.p. with test findings.

**Comment by EdSteenhoek** [comment]
Appologies... data issue :-(

**Comment by cagataycivici** [comment]
Thanks for confirming.
