### ISSUE TITLE
p-dropdown doesn't work in header of datatable when table is scrollable

### ISSUE THREAD

**Issue by cqzheng** [primefaces/primeng#2368]
Make the column [filter]="true", add template with p-dropdown for filter and add style style="overflow:visible". It works correctly. But if add scrollable="true" to the datatable, the list of p-dropdown doesn't show correclty. The overflow part is hidden. 
Did some debugging and found that a div with class ui-datatable-scrollable-header to wrapper table header is added when specify scrollable="true". Class ui-datatable-scrollable-header just set style "overflow:hidden". Thus p-dropdown doesn't work. The style="overflow:visible" can not passed to the div. There must be conflict of scrollable and custom filter.

**Comment by StevenLiekens** [comment]
Same problem with p-calendar.

**Comment by rohitsindhu90** [comment]
hi ,


Same problem i was facing in past. appendTo='bpdy' worked for me.
example:
 <p-column [style]="{'width':'150px','overflow':'visible'}"
field="CTNStatus" header="Status" [filter]="true" filterMatchMode="equals">
            <template pTemplate="filter" let-col>
                <p-dropdown [options]="ctnStatus"
[style]="{'width':'100%'}" appendTo="body"
(onChange)="dt.filter($event.value,col.field,col.filterMatchMode)"
styleClass="ui-column-filter"></p-dropdown>
            </template>

            
        </p-column>

**Comment by mukeshkamboj** [comment]
@rohitsindhu90 thanks for the solution. This saved my time 👍

**Comment by bimalpaul** [comment]
@rohitsindhu90 Thanks for that quick solution. 👍 🥇

**Comment by unaor** [comment]
Thanks saved the day

**Comment by rebelsyn** [comment]
appendTo="body"

@rohitsindhu90 nailed it

**Comment by cagataycivici** [comment]
Use appendTo body please.

**Comment by MayerMar** [comment]
Sorry for posting to a closed issue, but it would be great if infos like these would be linked on your showcase/example page. 

Would have saved me much time tinkering around aswell as it will for future visitors.

**Comment by ravikzm** [comment]
I have followed all suggestions like using overflow : visible or appendTo="body" but nothing working for me.
`  <p-column [style]="{'width':'5%','overflow':'visible'}" [sortable]="false" field="Status" header="Status" [filter]="true" filterMatchMode="equals" >
                            <ng-template pTemplate="filter" let-itemcol>
                                <p-dropdown [options]="statusList"  [style]="{'width':'100%','overflow':'visible'}" appendTo="body" (onChange)="dtaction.filter($event.value,itemcol.field,itemcol.filterMatchMode)" styleClass="ui-column-filter"></p-dropdown>
                            </ng-template>
                        </p-column>`
![image](https://user-images.githubusercontent.com/29487440/32146779-254c8f1e-bc9a-11e7-8de1-63377f76610a.png)

Please help to resolve it

**Comment by lalitmee** [comment]
Hello Guys, I solved the dropdown not showing bug by using the ` appendTo="body"`. But now what's happening is kind of ridiculous. As I am clicking on some dropdown to open and then scrolling the data of the table the drop-down is going with the table data. :thinking: :worried: 
I am attaching the screenshot of that. Please have a look and someone please tell me the reason why its happening. Thank you so much, guys. :innocent: 

![peek 2018-08-28 00-30](https://user-images.githubusercontent.com/10762218/44679892-cd6bb780-aa59-11e8-9bfa-9320ddc64a72.gif)

**Comment by UttamGiri** [comment]
lalitmee  did you find solution

**Comment by emrebaris9** [comment]
@lalitmee did you find the solution?

**Comment by lingardo** [comment]
@emrebaris9 did you find the solution?

**Comment by lalitmee** [comment]
@emrebaris9, it was a long time ago. I don't remember. But as I can see the screenshot I have attached, I don't think I found the solution.

**Comment by lingardo** [comment]
Guys, i found the solution, just need to delete propperty `overflow: hidden` in `ui-table-wrapper`

**Comment by mbsanchez** [comment]
In my case this issue was due that i forget to import the BrowserAnimationsModule in app.module.ts

import {BrowserAnimationsModule} from '@angular/platform-browser/animations';

**Comment by hulchenko** [comment]
> 

magic! Thank you very much
