### ISSUE TITLE
Performance Problem

### ISSUE THREAD

**Issue by DanielHabenicht** [primefaces/primeng#2369]
I'm submitting a ...  
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
When Loading any PrimeNG Site the "appendChild()" Function gets called inceredibly often from Zone.gs.

**Expected behavior**
Loading the page fast. 
Reasonable amount of "appendChild()" calls. 

**Minimal reproduction of the problem with instructions**
1. Open the PrimeNG website in any Browser you wish.
2. Open the Development Console and watch the Performance Tab (see Picture).

![capture](https://cloud.githubusercontent.com/assets/13590797/24256190/c248cd74-0fe7-11e7-957d-3f2c56adc96d.PNG)

**What is the motivation / use case for changing the behavior?**
PrimeNG Page loads far to long in Edge (more than 2s), IE11 (more than 10s) and Chrome (more than 3s) 

**Please tell us about your environment:**
I am running a Windows 10 machine with a sustainable amount of RAM and Computing-Power. 
This Bug is independet from the IDE.

* **Angular version:** 2.3.1 / 2.4.10
I don't know which version you guys are using but in our environment we are running v2.4.10. We've tested on v2.3.1 aswell.

* **PrimeNG version:** 2.0.5 / 2.0.0-rc-1
I don't know which version you guys are using but in our environment we are running v2.0.0-rc.1. We've tested on v2.0.5 aswell. 

* **Browser:** [ Chrome 57.0.2987.110  | IE 11 | Vivaldi 1.7.735.46  | Edge 38.14393.0.0 ]

**Comment by paule96** [comment]
Same here with our table.

**Comment by cagataycivici** [comment]
Try the new website please, it runs much faster.
