### ISSUE TITLE
Unable to select multiple values at a time from the multiselect dropdown inside p-dailog

### ISSUE THREAD

**Issue by Naveen07** [primefaces/primeng#2370]
I have a issue with multi select drop down inside a p-dialog box.
I was unable to select multiple values at a time from the multiselect dropdown, it gets closed after every single selection.
Currently using : Primeng V 2.0.1
this is my code
`<p-dialog> <p-multiSelect appendTo = "body" [options]="Data" class="ui-grid-col-4" [style]="{width :'100%'}" > </p-multiSelect> </p-dialog>`

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview

**Comment by ross-oreto** [comment]
I also experienced this issue and the cause is nesting the multi-select in a label tag:
```
<label>Cities broken :( 
<p-multiSelect [options]="cities"></p-multiSelect>
</label>
<br><br><br>
<label>Cities fine :)</label>
<p-multiSelect [options]="cities"></p-multiSelect>
```
