### ISSUE TITLE
Chart showcase documentation has minor error

### ISSUE THREAD

**Issue by colinfergusIR** [primefaces/primeng#2371]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

N/A

**Current behavior**
event.element_index, used in documentation, is not correct, yields null. 

**Expected behavior**
event.element_index would produce an integer value.

**Minimal reproduction of the problem with instructions**
For a chart, use the provided code, and uncomment the "event.element_index" code.

**What is the motivation / use case for changing the behavior?**
Better documentation.

**Please tell us about your environment:**
N/A

* **Angular version:** 2.0.X
N/A

* **PrimeNG version:** 2.0.X
master branch

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

* **Node (for AoT issues):** `node --version` =   
N/A

**Comment by sudheerj** [comment]
PR is already merged.Closing the issue now.
