### ISSUE TITLE
Error during AOT rollup process

### ISSUE THREAD

**Issue by pranz123** [primefaces/primeng#2373]
I am trying to run AOT rollup process but getting 'DataTableModule' is not exported by node_modules\primeng\primeng.js

**Please tell us about your environment:**
WIN 10

* **Angular version:** 
angular-cli: 1.0.0-beta.21
node: 6.9.1

* **PrimeNG version:** 2.0.5

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   6.9.1

**Comment by mustafaekim** [comment]
Try the on rollup.config.json

`    plugins: [
        nodeResolve({ jsnext: true, module: true }),
        commonjs({
            include: [
                'node_modules/rxjs/**', 'node_modules/primeng/**', 'node_modules/typedjson-npm/**'
            ],
            namedExports: {
                'node_modules/primeng/primeng.js': ['Editor', 'TabViewModule', 'DialogModule', 'EditorModule', 'SharedModule', 'AutoCompleteModule', 'InplaceModule', 'SpinnerModule', 'InputMaskModule', 'CalendarModule', 'ConfirmDialogModule', 'ConfirmationService', 'GrowlModule', 'ProgressBarModule'],
                'node_modules/typedjson-npm/js/typed-json.js': ['TypedJSON', 'JsonMember', 'JsonObject']
            }
        }),
        uglify()
    ]`

**Comment by cagataycivici** [comment]
Please use forum for cases like these, issue seems to be a config issue on your side.
