### ISSUE TITLE
Bug in Datatable scrolling

### ISSUE THREAD

**Issue by kcsahoo** [primefaces/primeng#2374]
When you enable vertical scrolling by having
scrollable="true" scrollHeight="800px"

the header row always takes space for scroll bar even if data rows occupy less height than scrollHeight setting.
But the data rows do not take space for scroll bar in this case which is right.
As a result, the alignment of header columns and datarow columns are offset.

**Comment by kcsahoo** [comment]
[scrollable]="true" scrollHeight="800px"

also did not solve the problem

**Comment by ctrl-brk** [comment]
It's an old bug. Multiple issues submitted already, but...

**Comment by StevenLiekens** [comment]
This can be easily fixed by setting overflow-y: scroll on the scrollable table. This ensures that the scrollbar area is always shown, even if there are not enough rows to cause overflow.

**Comment by kcsahoo** [comment]
Thanks.
This is not the right behaviour but will align the columns by forcing vertical scroll bar.

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
