### ISSUE TITLE
Autocomplete, choosing item from dropdown doesn't update ng-model

### ISSUE THREAD

**Issue by henritoivar** [primefaces/primeng#2375]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**
https://www.primefaces.org/primeng/#/autocomplete

**Current behavior**
The item doesn't get selected and ng-model is not set.

**Expected behavior**
Item should get selected and ng-model updated with the selection.

**Minimal reproduction of the problem with instructions**

1. Make sure nothing has been selected before
2. Under Advanced click on dropdown 
3. Click on an option
4. Bug occurs and item is not selected and ng-model is not updated.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10

* **Angular version:** 2.0.X

The one used on the website

* **PrimeNG version:** 2.0.X

The one used on the website

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Happens in IE11, IE10. Doesn't happen in IE9
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

* **Node (for AoT issues):** `node --version` =

**Comment by elvinmeza** [comment]
Additionally, if you click in the input box and enter a single blank space and then click/select an option from the list, it works. We detected this in IE11 as well.

**Comment by elvinmeza** [comment]
Besides the fact you need to add the necessary polyfills for IE, turns out that's not enough to make it work as expected. The issue occurs by the way IE handles the blur event on this, so when you click the scrollbar or anything in the panel loses the focus. I needed to solve this to move on what i'm doing currently, so did a PR with the fix that worked for me, but lets see what says the PrimeNG team since this is an IE specific issue.

**Comment by cagataycivici** [comment]
Tracked at 2788

**Comment by donvadicastro** [comment]
This was fixed on my side by adding empty single space to input control when first dropdown expanding occurs
```
onDropdownClick($event) {
    $event.originalEvent.preventDefault();
    $event.originalEvent.stopPropagation();

    if (this.autoCompleteComponent.panelVisible) {
      this.autoCompleteComponent.hide();
    } else {
      // fix bug with selecting initial value in IE https://github.com/primefaces/primeng/issues/745
      this.autoCompleteComponent.value || (this.autoCompleteComponent.value = ' ');
      this.autoCompleteComponent.show();
    }
  }
```

Declaration
```
<p-autoComplete  ...  (onDropdownClick)="onDropdownClick($event)"></p-autoComplete>
```

Where `autoCompleteComponent` is:
```
  @ViewChild(AutoComplete)
  autoCompleteComponent: AutoComplete;
```
