### ISSUE TITLE
PrimeNG 4.0.0-rc.1 error: Found the synthetic property @dialogState. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application

### ISSUE THREAD

**Issue by mustafaekim** [primefaces/primeng#2376]
Just upgraded to Angular 4.0.0 and primeng 4.0.0-rc.1.

I am getting the error below:

`ERROR Error: Found the synthetic property @dialogState. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.
    at checkNoSyntheticProp (dom_renderer.ts:368) [angular]
    at DefaultDomRenderer2.setProperty (dom_renderer.ts:311) [angular]
    at DebugRenderer2.setProperty (services.ts:883) [angular]
    at setElementProperty (ng_content.ts:1) [angular]
    at checkAndUpdateElementValue (element.ts:310) [angular]
    at checkAndUpdateElementInline (element.ts:208) [angular]
    at checkAndUpdateNodeInline (view.ts:448) [angular]
    at checkAndUpdateNode (view.ts:416) [angular]
    at debugCheckAndUpdateNode (services.ts:235) [angular]
    at debugCheckRenderNodeFn (services.ts:328) [angular]
    at Object.eval [as updateRenderer] (ConfirmDialog.html:2) [angular]
    at Object.debugUpdateRenderer [as updateRenderer] (services.ts:307) [angular]
    at checkAndUpdateView (view.ts:391) [angular]
    at callViewAction (view.ts:699) [angular]`

**Comment by mustafaekim** [comment]
fixed by:

`If you rely on Animations you’ll also need to install the animations package @angular/animations and import the new BrowserAnimationsModule from @angular/platform-browser/animations in your root NgModule. `

**Comment by pavel-sindelka** [comment]
I have the same problem! :(

**Comment by cmargulhano** [comment]
I'm too ...

**Comment by pavel-sindelka** [comment]
@mustafaekim Where to import BrowserAnimationsModule in this project please?
https://github.com/pavel-sindelka/astronauts

**Comment by ctrl-brk** [comment]
@pavel-sindelka works for me

**Comment by pavel-sindelka** [comment]
@ctrl-brk Works in my project or in yours?

**Comment by cagataycivici** [comment]
You need to import animations module, please review changelog of Angular, animations have their own module now.

**Comment by stirumala76** [comment]
In order to support Angular v4 animations you should:
Install animations npm install @angular/animations --save
Add import { BrowserAnimationsModule } from '@angular/platform-browser/animations'; and import in root NgModule

**Comment by elmoyeldo** [comment]
Had same issue.. got resolved with import of import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

**Comment by petersgiles** [comment]
I use angular-cli here's how I fixed it

console window
```bash
npm install --save @angular/animations@latest
```

and at the top of app.module.ts

```Typescript
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
```

and then in the @NgModule part of app.module.ts

```Typescript
@NgModule({
  declarations: [ ... ],
  imports: [
    ...
    BrowserAnimationsModule, \\ <-include this
  ],
  providers: [... ],
  bootstrap: [...]
})
```

**Comment by guntram** [comment]
But it is possible to put it into a different module than app.module right?!

I put it into a module keeping ui stuff together so we do not need to import everything.

`import {NgModule} from "@angular/core";
import {CommonModule} from "@angular/common";
import {BrowserAnimationsModule} from "@angular/platform-browser/animations";

import {DataTableModule} from "primeng/primeng";
import {CheckboxModule} from "primeng/primeng";
import {ButtonModule} from "primeng/primeng";
import {CalendarModule} from "primeng/primeng";

@NgModule({
    imports: [
        CommonModule,
        BrowserAnimationsModule,

        DataTableModule,
        CheckboxModule,
        ButtonModule,
        CalendarModule
    ],
    declarations: [],
    exports: [
        DataTableModule,
        CheckboxModule,
        ButtonModule,
        CalendarModule
    ]
})
export class AppPrimeNGModule { }`

and then import this module into app.module...

**Comment by tranbenoit** [comment]
Do not forget to add those lines in systemjs.config.js :
'@angular/animations': 'npm:@angular/animations/bundles/animations.umd.js',
      '@angular/animations/browser': 'npm:@angular/animations/bundles/animations-browser.umd.js',
      '@angular/platform-browser/animations': 'npm:@angular/platform-browser/bundles/platform-browser-animations.umd.js',

Found here : https://github.com/mgechev/angular-seed/issues/1880

**Comment by ahelord** [comment]
@mustafaekim  work for me thanks .

**Comment by rjsteinert** [comment]
My issue was that this was causing tests to fail. It should be noted that if you are going to use the BrowserAnimationsModule in a component that you have to also have to NgModule import that in your component's spec file.

In my case...
```
import { TangerineFormCardComponent } from './tangerine-form-card.component';
import { TangerineFormsModule } from '../../tangerine-forms.module';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

describe('TangerineFormCardComponent', () => {
  let component: TangerineFormCardComponent;
  let fixture: ComponentFixture<TangerineFormCardComponent>;

  beforeEach(async(() => {
    TestBed.configureTestingModule({
      imports: [
        TangerineFormsModule,
        BrowserAnimationsModule
        ]
    })
    .compileComponents();
  }))
```

**Comment by bobKasbi** [comment]
@rjsteinert: true. This did solve the issue from my side. Thanks!

**Comment by nop1984** [comment]
sadsa

**Comment by ShaileshBhatNP** [comment]
Here also same issue. But If I run in VS Code, there is no error. I'm getting the error if I run in Visual Studio IDE. Tried to solve all above solutions. But didn't work..
![errorinconsole](https://user-images.githubusercontent.com/29448807/35848272-85ea136c-0b43-11e8-8a6f-ec2955348963.png)


Project link In [VS Code](https://drive.google.com/open?id=1ny_KGOAG4z-OzqL_vFQK2S6htOxR5myl)

Project link in [Visual Studio IDE](https://drive.google.com/open?id=1upclsDsNrXI-GKVLqkKJw_IPmyrYuxW_)
