### ISSUE TITLE
Column Reorder and Resize support for Scrollable DataTable

### ISSUE THREAD

**Issue by snowdave86** [primefaces/primeng#238]
When a datatable has scrollable="true" as an option set, reorderableColumns="true" and resizableColumns="true" doesn't function.

**Comment by cagataycivici** [comment]
Yes, these are not supported yet for scrollable tables but they will be.

**Comment by jtesser** [comment]
I need the resize columns on the treeTable.  Is there a release fro primeNG that has this?

**Comment by cagataycivici** [comment]
Tracking at 1005.

**Comment by dpac4u** [comment]
isthis fix still works in latest? I don't see it is working yet ?

**Comment by rokkuci** [comment]
This is still a bug!

**Comment by raviganesh12** [comment]
This is still an issue for me. Any Work around would help.

**Comment by jayordway** [comment]
This is still not working. You cannot have both scrollable=true with column reorder. Can this issue be reopened please?

**Comment by ctrl-brk** [comment]
Here: https://github.com/primefaces/primeng/issues/1005

**Comment by Somnath-Ramraj** [comment]
The issue is still not resolved. @ctrl-brk - Could you please tell me if this has been added to Primefaces. I am using the latest version. But I am still getting this issue

**Comment by Somnath-Ramraj** [comment]
The issue is closed. Is there a way to make this work?

**Comment by ctrl-brk** [comment]
I have no idea what's going on with this. I'm waiting myself for almost a year now.

**Comment by cagataycivici** [comment]
Create a new ticket please with a sample, I just did for example;

https://github.com/primefaces/primeng/issues/2890
