### ISSUE TITLE
Overlaypanel need a double click on the body to close it, if the event that call show() is not a click event

### ISSUE THREAD

**Issue by Tuizi** [primefaces/primeng#2380]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/rFg3asM7Cqx1s1UaXeBt

**Current behavior**

You need to double click on the body if you want to close an overlay opened after a even other than a click

**Expected behavior**

We should be able to hide the Overlay independently of the event that opened it

**Minimal reproduction of the problem with instructions**

See the plunkr few lines of code are enough to reproduce it. 

**What is the motivation / use case for changing the behavior?**

I want to display the overlay panel when an user type something in a `<input>` for example

**Please tell us about your environment:**

MacOSX, Webstorm, yarn, nodejs

* **Angular version:** 2.0.X

2.4.10

* **PrimeNG version:** 2.0.X

2.0.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

* **Node (for AoT issues):** `node --version` =

**Comment by meiriko** [comment]
+1

The reason is that the onInit "eats" the first document click (assuming it is the triggering event). Didn't have time to further investigate or create a PR

**Comment by anafreitas** [comment]
any updates on this?

**Comment by edgar131** [comment]
+1 Very annoying.  I'm trying to show the panel on hover, but because of that it requires a double click to get it to close.  There also doesn't seem to be a easy way to handle closing it on mouseout of the panel.

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/commit/5c866710a803022c798245a93e0ed76a72dfb51c

**Comment by andreyshedko** [comment]
The problem still exists in **9.1.0**
