### ISSUE TITLE
File Upload component clean the selected file when user click on "Choose" button and then click on "Cancel" on the file choose window in IE11

### ISSUE THREAD

**Issue by davidkirolos** [primefaces/primeng#2381]
**I'm submitting a ...**  
```
[x] bug report => File upload issue on cancel file choose when single file upload.
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/ujLS9oZAvh0tItnN7Noi?p=preview

**Current behaviour**
The File Upload component clean the selected file when user click on "Choose" button and then click on "Cancel" on the file choose window in IE11.
Only if the component is set for **single** file upload (**no Multiple attribute**)

**Expected behaviour**
When the user click on "**Cancel**" button **in IE file choose window** the window should close and the earlier selected file should remain.

**Minimal reproduction of the problem with instructions**
In IE11 with single file configuration
1- Select one file.
2- Click on "Choose" button again.
3- **Don't** select any files and click on "Cancel" button the IE file chooser window.

**What is the motivation / use case for changing the behaviour?**
If the user decided to not select another file, he should be able to close the file chooser window without cleaning the earlier selected file.

**Please tell us about your environment:**
Windows 7 pro
IDE: VSC
Package manager: NPM 6.x
Server: Apache

* **Angular version:** 
2.4.X

* **PrimeNG version:** 
2.X

* **Browser:** 
[ IE 11]
 
* **Language:** 
[TypeScript 2.0.9]

**Comment by cagataycivici** [comment]
Does it still happen with 4.2.1? We've done fixes related to it.

**Comment by davidkirolos** [comment]
I was fixed,
thanks
