### ISSUE TITLE
DataScroller Exception 

### ISSUE THREAD

**Issue by muanaser** [primefaces/primeng#2388]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
DataScroller throws exception during on page load after upgrade from {Angular2, PrimeNG 1.01} to {Angular4, PrimeNG 2.0.5}

**Expected behavior**
Page loads without DataScroller exception.

**Minimal reproduction of the problem with instructions**
> ERROR TypeError: Cannot read property 'createEmbeddedView' of undefined
>     at ViewContainerRef_.createEmbeddedView (refs.ts:274)
>     at TemplateWrapper.ngOnInit (shared.ts:57)
>     at checkAndUpdateDirectiveInline (provider.ts:275)
>     at checkAndUpdateNodeInline (view.ts:455)
>     at checkAndUpdateNode (view.ts:416)
>     at debugCheckAndUpdateNode (services.ts:235)
>     at debugCheckDirectivesFn (services.ts:294)
>     at Object.eval [as updateDirectives] (DataScroller.html:9)
>     at Object.debugUpdateDirectives [as updateDirectives] (services.ts:273)
>     at checkAndUpdateView (view.ts:344)
>     at callViewAction (view.ts:699)
>     at execEmbeddedViewsAction (view.ts:669)
>     at checkAndUpdateView (view.ts:388)
>     at callViewAction (view.ts:699)
>     at execComponentViewsAction (view.ts:643)

**Please tell us about your environment:**

* **Angular version:** 4.0.0

* **PrimeNG version:** 2.0.5

* **Browser:** all

 
* **Language:** [TypeScript 2.2.1]

* **Node (for AoT issues):** `node --version` =   6.3.0

**Comment by muanaser** [comment]
Issue resolved. Changed template mark up,

> <ng-template let-dest pTemplate="item"> 
> ...
> </ng-template>

In version 1.0.1 code it was,

>  <template let-dest>
> ...
> <template>

**Comment by VarshilDoshi** [comment]
I get this type of error 
CustomComponent.html:6 ERROR TypeError: Cannot read property 'createEmbeddedView' of undefined
    at DropZone.ngAfterContentInit (DropZoneComponent.ts:40)
    at callProviderLifecycles (core.js:12699)
    at callElementProvidersLifecycles (core.js:12673)
    at callLifecycleHooksChildrenFirst (core.js:12656)
    at checkAndUpdateView (core.js:13806)
    at callViewAction (core.js:14153)
    at execComponentViewsAction (core.js:14085)
    at checkAndUpdateView (core.js:13808)
    at callViewAction (core.js:14153)
    at execComponentViewsAction (core.js:14085)
