### ISSUE TITLE
InputMask does not display initial value with Reactive Forms

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#2394]
If initial value is provided via reactive form, it is not displayed.

**Comment by cagataycivici** [comment]
My bad, it works.

**Comment by rweisse** [comment]
For me it doesn't seem to work. Initials values only work for normal `<input>`-Elements and not for `<p-inputMask>-Elements`:

component.html
```
<input pInputText [formControl]="myForm.controls['title']" type="text"/> <!-- foo -->
<p-inputMask [formControl]="myForm.controls['title']" mask="***"></p-inputMask> <!-- is empty -->
```

component.ts
```
myForm: FormGroup;

initForm() {
    this.myForm = this.fb.group({
        title: ['foo']
    });
}
```

**Comment by wiesnery** [comment]
Same here. As soon as I remove the mask, it works. Any updates on this?

**Comment by john182** [comment]
Same here. As soon as I remove the mask, it works. Any updates on this?

**Comment by SiebeDom** [comment]
Same here:
`                <p-inputMask mask="9999.999.999" id="belgianTaxNumber" formControlName="taxNumber" placeholder="9999.999.999"></p-inputMask>
                <input id="taxNumberInput" type="text" pInputText formControlName="taxNumber">`

`    this.customerForm = this.fb.group({
      taxNumber: [this.customer.taxNumber],`
