### ISSUE TITLE
Add loading property to DataTable

### ISSUE THREAD

**Issue by ctrl-brk** [primefaces/primeng#2395]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

DataTable emptyMessage property only accepts plain strings.

**Expected behavior**

Would be nice to accept html so you can show a "loading" spinner or something.

**Comment by cagataycivici** [comment]
When true, displays a loader icon.

**Comment by ycabrerago** [comment]
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'.

**Comment by Sergeon** [comment]
I can't get this to work, I got the same error @ycabrerago reported 7 days ago. 

In my component, I have this function to load data asynchronously:

```javascript
  
loadDataLazy(event: LazyLoadEvent) {
  
  this.loading = true;
  this.service.getFilteredData(event).subscribe( res => {
      this.data = res.data;
      this.total = res.total;
      this.loading = false;
   } );

}

```

While in the component html I define the datatable like:  

```html
  <p-dataTable [value]="data" [lazy]="true" (onLazyLoad)="loadDataLazy($event)" [loading]="loading"></p-dataTable>
```

I notice that, in the showcase, the example code doesn't set `loading` to false on request success, but just after the request line, which would cause the `loading` property to be set to false before the request was completed: (the next is code I paste from the primeNG showcase data table example)

```javascript
ngOnInit() {
        this.loading = true;
        setTimeout(() => {
            this.carService.getCarsSmall().then(cars => this.cars = cars);
            this.loading = false;
        }, 1000);
    }
```

Should the `getCarsSmall` request be a real http request over the wire, that code wouldn't work well. Also, I guess that a code like: 

```javascript
ngOnInit() {
        this.loading = true;
        setTimeout(() => {
            this.carService.getCarsSmall().then(cars => {
               this.cars = cars;
               this.loading = false;
             });

        }, 1000);
    }
```
(which would maintain the loading status until the request was successful) would trigger that error, as is happening to me when I try to change the `loading` property in the request success. It fails even if, in the `subscribe` callback, I defer the `loading` change with a long `setTimeout` call:

```javascript
  
loadDataLazy(event: LazyLoadEvent) {
  
  this.loading = true;
  this.service.getFilteredData(event).subscribe( res => {
      this.data = res.data;
      this.total = res.total;
      setTimeout( () => {
          this.loading = false; // This will fire the exception when reached

      } , 4000 );
      
   } );

}

```

I didn't know wether to comment here or open a new issue, sorry if that would be more proper. I'll open a new issue on request.
