### ISSUE TITLE
[Severe] Controls and media elements should have labels

### ISSUE THREAD

**Issue by huineng** [primefaces/primeng#2397]
**I'm submitting a ...**  (check one with "x")
```
[ x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
```
**What is the motivation / use case for changing the behavior?**
Accessibility check  failures

* **Angular version:** 4

* **PrimeNG version:** 4

* **Browser:** [Chrome]

running your prime website (and of course my own applications through the chrome accessibility checker , i get a lot of warnings

[Severe] Controls and media elements should have labels

below is your own autocomplete component gone through the checker

Any plans to have this compliant ? Should not be complicated, just add a label, 
Without this Prime cannot be used in production sites requiring accessibility compliance
thanks

![image](https://cloud.githubusercontent.com/assets/3482445/24395197/1de553d6-139f-11e7-882a-1ddfb62dfde3.png)

**Comment by cagataycivici** [comment]
Components have inputId to match with the label, not all demos use it though.
