### ISSUE TITLE
Accordion not working - PrimeNG 4

### ISSUE THREAD

**Issue by mani0608** [primefaces/primeng#2398]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
Accordion component not working properly with the primeng 4.0.0 rc1 and Angular 4

**Expected behavior**
Accordion component was working fine until Angular 2 and Primeng 2.0.4. But after upgrading to angular 4 and primeng 4.0.0 rc1 it stopped working. So, accordion expected to work with angular 4

**Minimal reproduction of the problem with instructions**
**_STEPS TO REPRODUCE_**:

1. Import Accordion module into the AppModule and add the AccordionModule to imports
2. Add sample accordion (GOD FATHER example) content into html file
3. Run the application

**What is the motivation / use case for changing the behavior?**
Upgrade to Angular 4 & PrimeNG 4.0.0 RC1

**Please tell us about your environment:**
**Operating System**: Windows
**Compiler**: TSC (with Lite-Server)
**Module**: CommonJS

**Angular Version:** 4.0.0
**PrimeNG Version:** 4.0.0 RC1

* **Browser:** [Chrome ]

* **Language:** [ TypeScript 2.2.X ]

**Attached Screenshot of the issue**
![image](https://cloud.githubusercontent.com/assets/20502054/24440300/0a893f1e-1471-11e7-8985-acbb9c0ad1d6.png)

**Comment by mani0608** [comment]
Sadly I have to move out of PrimeNG in case Im not getting a response on this. Yes it's going to be a couple of sleepless nights for me removing your components from my application. But still I have to do it. 
I ready struggled to overcome an issue with drop-down component without any support. 
But I very much love these components and I really wanted to use these. But at the sametime Im working 
for my client and he doesn't provide me much time. 
But I respect all the effort that this team has put on in building these components.

**Comment by mani0608** [comment]
With God's grace, i was able to fix this issue myself.

**Comment by SIlver--** [comment]
Thanks for not telling anyone else how you did it...

**Comment by mahesh5b5** [comment]
Please tell us how you fixed the issue man!
