### ISSUE TITLE
[BUG] onClick on <p-radioButton> don't fire a event

### ISSUE THREAD

**Issue by cyberrranger** [primefaces/primeng#2401]
[X] bug report => Search github for a similar issue or PR before submitting

sry my Plunkr demo don't run
`Can't bind to 'ngModel' since it isn't a known property of 'p-radioButton'.`
http://plnkr.co/edit/lJ1tyrnBNYaZgrlBwmzW?p=preview

* **Angular version:** 4.0.X
* **PrimeNG version:** 4.0.X

onClick on <p-radioButton> don't fire a event

`<p-radioButton name="group1" value="Option 1" label="Option 1" (onClick)="onClick()">`

**Comment by cyberrranger** [comment]
the same after update    "primeng": "^4.0.0-rc.2",

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview

**Comment by kito99** [comment]
@cyberrranger you need to add FormsModule to your module imports.

**Comment by cyberrranger** [comment]
@kito99 is already done

**Comment by mahesh5b5** [comment]
Clicking on radio circle its triggerring **onClick** event but not on label of the **p-radiobutton**

**Comment by tgupta694** [comment]
Hi Folks, I am still getting Can't bind to 'ngModel' since it isn't a known property of 'p-radioButton'.

on this 
http://plnkr.co/edit/lJ1tyrnBNYaZgrlBwmzW?p=preview


how do i fix it?

**Comment by cyberrranger** [comment]
@tgupta694 you missed
imports:      [ BrowserModule, **FormsModule**, ButtonModule, RadioButtonModule ],

**Comment by tgupta694** [comment]
Thanks - that solved the issue.
