### ISSUE TITLE
Custom filter function method to DataTable

### ISSUE THREAD

**Issue by tamatcho** [primefaces/primeng#2403]
I have a PrimeNg DataTable whose one column has as cell entry per cell a table of string(presented as html list using Templating and ngFor directive ). Then when filtering using filterMatchMode:'in' it doesn't work at all and when using the other filterMatchModes such contains, I get the following error: e.toLowerCase is not a function. (In 'e.toLowerCase()', 'e.toLowerCase' is undefined).
It would be nice to review your implementation of the 'filter'-methode to support such a use case or at least to give to possibility to implement our own filter methode on a PrimeNG DataTable.

**Comment by mscu** [comment]
i also need a custom filter method

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
