### ISSUE TITLE
Datatable lazy loading filter loop

### ISSUE THREAD

**Issue by kockicica** [primefaces/primeng#2405]
**I'm submitting a ...**  
```
[ x] bug report
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/RvsJ33Uy0qax0PEy9RKO?p=preview

**Current behavior**
Activating column filter (typing anything) creates infinte loop (setting value of the datatable triggers lazy loading event, then again)

**Expected behavior**

**Please tell us about your environment:**

* **Angular version:** 4.0.0

* **PrimeNG version:** 4.0.0-rc.1

**Comment by Danieleeee** [comment]
Still in Prime 4.0.0-rc2

**Comment by mika-el** [comment]
No more infinite loop with [immutable]="true"

**Comment by Danieleeee** [comment]
Yes, it's true, Thanks.
But it looks like a workaround.

**Comment by moxival** [comment]
Having the same problem. Any chance someone from primeng to acknowledge this as bug?

**Comment by moxival** [comment]
@cagataycivici sorry to ping you like this but this is still happening in RC3 - i will not go 'round make all the grids immutable as this is a workaround and not a real solution. Can you please comment on this issue?

**Comment by cagataycivici** [comment]
I'll check before 4.0-Final.

**Comment by cagataycivici** [comment]
How to replicate? Is there a plunkr?

**Comment by kockicica** [comment]
updated to  rc.3 http://plnkr.co/edit/RvsJ33Uy0qax0PEy9RKO?p=preview

**Comment by cagataycivici** [comment]
Fixed via 2606
