### ISSUE TITLE
Variable for font path for themes that uses font

### ISSUE THREAD

**Issue by lekhnath** [primefaces/primeng#2406]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When using omega theme getting the following error message:
```
Module not found: Error: Can't resolve './fonts/roboto-v15-latin-regular.woff2'
```

**Expected behavior**
Provide some $variable so that we could override that. Like `$fa-font-path` provided by font-awesome scss.

**Minimal reproduction of the problem with instructions**
```
@import '~primeng/resources/primeng.css';
@import '~primeng/resources/themes/omega/theme';
```

**What is the motivation / use case for changing the behavior?**
Without this not able to use with webpack.

* **Angular version:** 4.0

* **PrimeNG version:** 4.0.0-rc.1

**Comment by lekhnath** [comment]
Solved this problem by using `resolve-url-loader` webpack loader.

**Comment by actra-gschuster** [comment]
@lekhnath How did you exactly solve the problem?
I'm facing a similar issue, generation works as expected but the css refers the wrong path.
CSS is generated in /assets/css, fonts etc. are extracted to /assets/[fonts,images,...] but in the CSS it says e.g. url(assets/fonts/...ttf) which results in a request to /assets/css/assets/fonts/...ttf
