### ISSUE TITLE
Autocomplete - support for home, end, page up, page down keys

### ISSUE THREAD

**Issue by tom3kb** [primefaces/primeng#2407]
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**What is the motivation / use case for changing the behavior?**
It would be nice to get support for home, end, page up/down button in autocomplete. Up/down arrow is not enough if list contains tens/hundreds elements,

* **Angular version:** 4.0.0

* **PrimeNG version:** 4.0.0-rc.1

**Comment by dharapvj** [comment]
Along with those keys... can we also look at adding left, right arrow key based navigation within multiple selected items..

I am looking towards this to navigate between selected group via keyboard and use delete / backspace to remove some items which were selected by mistake.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
