### ISSUE TITLE
Datatable default sorting fails on changing data input list

### ISSUE THREAD

**Issue by dimitrijuchtmans** [primefaces/primeng#2408]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/3wBcgvttMhNutzWo2zln?p=preview

**Current behavior**
If I change the input list, the list is getting sorted only half of the time. I checked the sourcecode, and i think it is something with the 'stopSortingPropagation' attribute.

**Expected behavior**
Have the selected sorting be applied whenever we change the input list

**Minimal reproduction of the problem with instructions**
Click the button 'Get new letters'

**What is the motivation / use case for changing the behavior?**
Motivation: It's a plain bug. 
Use-case: I have to update the list frequently in my app

**Please tell us about your environment:**
Windows 10, IntelliJ, npm, Jboss

* **Angular version:** 2.4.8

* **PrimeNG version:** 2.0.5

* **Browser:** All
 
* **Language:** Typescript

**Comment by Strike117** [comment]
Same error here

**Comment by oshingc** [comment]
Please some help, I still have this error.

**Comment by blinkxzero** [comment]
+1 Would like some help with this as well. 

This makes editing data inside the data table frustrating for our clients, since once they update the data, I sync it to the database and then the datatable fails to sort. 

Exposing a function to sort programmatically could be a temporary solution, as it could be called after the data changes.

**Comment by m0rg** [comment]
+1

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
