### ISSUE TITLE
Calendar : ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: ''. Current value: '10'.

### ISSUE THREAD

**Issue by limjoonae** [primefaces/primeng#2410]
I have imported the BrowserAnimationsModule and can complie+run pass with Angular 4 but
When I click on calendar I found error 

![image](https://cloud.githubusercontent.com/assets/3191903/24448323/032edecc-149e-11e7-8467-2431fea7b20f.png)

app.component.ts
```
import { Component } from '@angular/core';

@Component({
  selector: 'my-app',
  template: `
  <p-calendar [(ngModel)]="value"></p-calendar>
  `,
})
export class AppComponent  { 
  value: Date;
}
```
app.module.ts
```
import { NgModule }      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { RouterModule, Routes } from '@angular/router';
import { CalendarModule } from 'primeng/primeng';
import { FormsModule } from '@angular/forms';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

import { AppComponent }  from './app.component';

@NgModule({
  imports:      [ 
    BrowserModule,
    CalendarModule,
    FormsModule,
    BrowserAnimationsModule
  ],
  declarations: [ 
    AppComponent,
  ],
  bootstrap:    [ AppComponent ]
})
export class AppModule { }
```

**Angular version:** 4.0.0
**PrimeNG version:** 2.0.5
**font-awesome:** 4.7.0

Please notify me for solution
Thankyou.

**Comment by Pythorogus** [comment]
There's a patch in the Primeng 4.0 RC1 release

**Comment by xorLogan** [comment]
I am using latest version of Primeng but still facing same issue.Please help
<img width="1312" alt="screen shot 2017-05-02 at 5 37 27 pm" src="https://cloud.githubusercontent.com/assets/26898766/25617099/36594ba4-2f5e-11e7-8e3c-e4967a3b0927.png">

**Comment by Arsenal83** [comment]
Angular version: 4.1.0
PrimeNG version: 4.0.0
working

thank you!

**Comment by cagataycivici** [comment]
Glad to hear!
