### ISSUE TITLE
Spinner allow , not only .

### ISSUE THREAD

**Issue by cyberrranger** [primefaces/primeng#2411]
[ x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap

show 
https://www.primefaces.org/primeng/#/spinner

I can enter 5.55 (5 point 55)
but not 5,55 (5 comma 55)

Regards
Patrick

**Comment by mikosu3** [comment]
did you try use decimalSeparator or thousandSeparator attributes?

**Comment by cyberrranger** [comment]
thx for note

if i use 
<p-spinner size="30" decimalSeparator=","></p-spinner>

and enter "0.5" is convert to 0,5 (ok)
but i enter "0,5" is convert to 5 ???

**Comment by mikosu3** [comment]
What kind of numbers would you like to expect "0, 5"?
"0 and 5"?
In the case of "0 and 5", I think that it is better to consider using Inputtext or Mask
