### ISSUE TITLE
Datatable filter causes ExpressionChangedAfterItHasBeenCheckedError 

### ISSUE THREAD

**Issue by Ketec** [primefaces/primeng#2412]
When typing/deleting too fast, this error is thrown.
Quick debug showed that it comes from here, specifically where it adds a new value to filters:
    
```
filter(value, field, matchMode) {
        if(!this.isFilterBlank(value))
            this.filters[field] = {value: value, matchMode: matchMode};
        else if(this.filters[field])
            delete this.filters[field];

        this._filter();
    }
```

Adding this.changeDetector.detectChanges(); after assignment fixed the problem.

**Comment by cagataycivici** [comment]
I'm unable to replicate, can it be done at live showcase?
