### ISSUE TITLE
Rename Dialog events

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#2413]
Remove onAfterHide and onAfterShow, rename onBeforeHide and onBeforeShow to onHide and onShow to align with other components.

**Comment by GabKas** [comment]
Hi,

the following fix: ec06e44
was removed the ngAfterViewChecked lifecycle hook in 4.0.0-rc.2.

Unfortunately the dialog does not open in the center of viewport anymore.
Because the center() function can not calculate the elementHeight properly.
