### ISSUE TITLE
No autocomplete after blur

### ISSUE THREAD

**Issue by needforjamaica** [primefaces/primeng#2415]
**I'm submitting a ...**  (check one with "x")
[x] bug report => Search github for a similar issue or PR before submitting

* **Angular version:** 2.0.X
* **PrimeNG version:** 2.0.5

I was testing first autocomplete example (basic) with static values 
countries: any[] = [
        {name: 'aaa'},
        {name: 'aaaakk'},
        {name: 'aaaaaajjj'},
        {name: 'aaaaaaaaah'},
        {name: 'aaaaaaaaaaf'},
        {name: 'aaaddddddddddddd'},
    ];

step 1) type "a", getting autocomplete
step 2) blur autocomplete field, autocomplete gone
step 3) continue typing, second "a". Nothing happen.

I think problem is "not changed suggestions array". My hotfix: this.filteredCountriesSingle = []; on blur. suggestions change every time ( !=[] ), so autocomplete shows every time

**Comment by evgd** [comment]
@needforjamaica hi, I thought I have the same problem, but my issue was to get "suggestions panel" visible after click on input after blur.
In your case, can you please explain what actions you perform between step 2 and 3. To start typing second "a" you had to click on autocomplete input?
https://www.primefaces.org/primeng/#/autocomplete
step 1 type "D" => results
step 2 blur => suggestions panel hide
step 3 click back to input
step 4 add "e" => Denmark in suggestions

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview

**Comment by evgd** [comment]
issue mentioned in my comment http://plnkr.co/edit/0rLrPMUcAuq9ZnkecHxJ?p=preview

**Comment by cagataycivici** [comment]
What are the test steps for the plunkr above?

**Comment by evgd** [comment]
step 1 type "D" on auto complete => see Denmark in results
step 2 blur by clicking outside of input or Tab => suggestions panel hides (expected) 
step 3 click on input => no results appear. To get results you'll have to delete character or enter one more
