### ISSUE TITLE
Dialog failure when including Animations Module

### ISSUE THREAD

**Issue by wesray** [primefaces/primeng#2416]
```
[ x] bug report => Search github for a similar issue or PR before submitting
 
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/Y7Uop18NiL9LwjIb3K1G?p=preview

**Current behavior**
When adding NoopAnimationsModule or BrowserAnimationsModule in root module, dialog throws error.  If using two way binding, setting visible during lifecycle of AfterViewInit, issue is alleviated. 

**Expected behavior**
Modal would show on load.
 
**What is the motivation / use case for changing the behavior?**
Auxiliary routes, default is to show dialog.

**Please tell us about your environment:**
Chrome/Angular CLI (ng serve)

* **Angular version:** 4.0.0 

* **PrimeNG version:** 4.0.0-rc.2 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript 2.2.1 | ES6/7 | ES5]

**Comment by cagataycivici** [comment]
Dup of 2428
