### ISSUE TITLE
Bug : primeng documentation links do not work after V4 rc.2

### ISSUE THREAD

**Issue by kcsahoo** [primefaces/primeng#2421]
Linked to #2420 
If you click on any menu item, nothing works.

**Comment by kcsahoo** [comment]
does not work in Chrome, works in Firefox and IE.

**Comment by kcsahoo** [comment]
#2420 does not work in any of the browsers

**Comment by kcsahoo** [comment]
It works now for Chrome also.
However #2420 is still issue and not resolved.

**Comment by sudheerj** [comment]
The issue exists for TieredMenu only and it works good in panelMenu 
[https://github.com/primefaces/primeng/issues/2763](url)
