### ISSUE TITLE
Adding new row inside datatable , replaces old row

### ISSUE THREAD

**Issue by deveshsinghal22** [primefaces/primeng#2423]
Hello,
I have a datatable, its has some columns with p-dropdown and some having textbox.
In the footer I have a button, onClick on this button pushes a new json in the exisiting array, like below

`
let tempJson : any = {
     'key' : null,
     'key2' :null
    };

    this.myjsonarray.push(tempJson);`

As soon as I click the add button, all the textboxes and dropdown reset value to null.

**Comment by deveshsinghal22** [comment]
@cagataycivici  I added this issue here.

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
