### ISSUE TITLE
onSlideEnd event is not getting values on range mode

### ISSUE THREAD

**Issue by danger1** [primefaces/primeng#2429]
When I use `p-slider`  element with `[range]`  attribute, I can not get the values via `(onSlideEnd)`
event.But if I use `(onChange)` instead, I can get the values or once I use p-slider without `[range]`  I can get the values with this attribute `(onSlideEnd)` as well.
The bug I want to explain is available on the link below.
[http://plnkr.co/edit/JacrFoQ79yjuRAjSfU4w?p=preview](http://plnkr.co/edit/JacrFoQ79yjuRAjSfU4w?p=preview)

`  <p-slider (onSlideEnd)="changeFilterRange($event)" [(ngModel)]="filterRangeValues" [style]="{'width':'100%'}" [range]="true"></p-slider>`

* **Angular version:** 2.3.1
* **PrimeNG version:** 2.0.1

regards..

**Comment by mnjongerius** [comment]
I fixed this in e0613d8b40bcb5f969de8cf48e7e98ce2598b827 (https://github.com/primefaces/primeng/pull/2829)

**Comment by cagataycivici** [comment]
Fixed via the PR, thanks.
