### ISSUE TITLE
[Calendar] Possibility to pick data in UTC timezone

### ISSUE THREAD

**Issue by vazham** [primefaces/primeng#2430]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
```

**Current behavior**

Current caleandar module doesn't have feature to pck UTC/local time.

**Expected behavior**

Would be vey useful to pick date in UTC timezone.

**What is the motivation / use case for changing the behavior?**

Sometimes it's needed to pick the date in UTC timezone, not in local. 

* **PrimeNG version:** 2.0.X
2.0.3

**Comment by britvik** [comment]
I was looking at the source code and there actually is UTC date when you pick a date from calendar. But there is local date when you update it manually via input. This should be fixed to be consistent...

**Comment by dags** [comment]
There should be a way to better handle timezone in Calendar. Currently, if you select a date from popup, input field is populated with a date that is one day earlier if local timezone is west of UTC. For instance, Argentina is -3 GMT and selecting 03/05/2017 will be shown as 03/04/2017 in field and value.

**Comment by vadimzham** [comment]
@dags Here are no problem with any timezone when date will be picked in UTC timezone because it always will be 00:00Z.

**Comment by cagataycivici** [comment]
There is utc property for this.

**Comment by alexschilpp** [comment]
I'm using the calendar module of primeng@4.1.1 in my Angular2 App template like this

`<p-calendar [(ngModel)]="requestFrom" (onSelect)="onRequestDateTimeRangeChange()" [inputId]="requestFrom" [showTime]="true" [utc]="true"></p-calendar>`

While having the utc property set to true I'd expect both the time in the input field and the ngModel value in my Angular component displayed and returned in UTC. Unfortunately it seems like that property is not working at all as the input field displays my local time and when I return the value in my component I get

`console.log(this.requestFrom);
-> Wed Jul 19 2017 11:36:36 GMT+0200 (CEST)`

**Comment by alexschilpp** [comment]
@cagataycivici any idea how to solve that?

**Comment by ericsvendsen** [comment]
@alexschilpp this is my expectation exactly. I just commented on #3611 since that issue is still open and might hopefully be resolved.

**Comment by sergey-morenets** [comment]
It seems that utc property still exists but it's not used any more in Calendar. If i set it I see this message in the console:
Setting utc has no effect as built-in UTC support is dropped.
