### ISSUE TITLE
dataTable template：error 'ng-template' is not a known element

### ISSUE THREAD

**Issue by Ningningz** [primefaces/primeng#2433]
DataTableModule,SharedModule  was imported，so why this error?

` <p-dataTable [value]="cars">
    <p-column field="vin" header="Vin"></p-column>
    <p-column field="year" header="Year"></p-column>
    <p-column field="brand" header="Brand"></p-column>
    <p-column styleClass="col-button">
        <ng-template pTemplate="header">
            <button type="button" pButton icon="fa-refresh"></button>
        </ng-template>
    </p-column>
</p-dataTable>`

error:  EXCEPTION: Uncaught (in promise): Error: Template parse errors:
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("  <p-column field="brand" header="Brand"></p-column>
    <p-column styleClass="col-button">
        [ERROR ->]<ng-template pTemplate="header">
            <button type="button" pButton icon="fa-refresh"></button"): BarrelComponent@12:8

**Comment by Ningningz** [comment]
Code written in official document

**Comment by Nattujessy** [comment]
What is your Angular and Primeng version?
'ng-template' is part of Angular4.0.0 and use primeng version 4.0.0.rc.1

**Comment by Ningningz** [comment]
Thank you！！！ the reason is my angular version is 2.0
