### ISSUE TITLE
Can't bind to 'target' since it isn't a known property of 'p-contextMenu'

### ISSUE THREAD

**Issue by TarasKovalenko** [primefaces/primeng#2434]
I try to use code from off-site about [contextmenu](https://www.primefaces.org/primeng/#/contextmenu)
And when I try to load my page with this component I catch next exception.

> Can't bind to 'target' since it isn't a known property of 'p-contextMenu'.
> 1. If 'p-contextMenu' is an Angular component and it has 'target' input, then verify that it is part of this module.
> 2. If 'p-contextMenu' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
>  ("<p-contextMenu [ERROR ->][target]="img" [model]="items2"></p-contextMenu>

1. firstPage.component .html code
```
<p-contextMenu [target]="img" [model]="items2 "></p-contextMenu>
<img #img src="/showcase/resources/images/primeng.svg" alt="Logo">
```

2. firstPage.component .ts
```
import { Component, OnInit } from "@angular/core";

import { ContextMenu, MenuItem } from 'primeng/primeng';

@Component({
    selector: "my-first-component",
    templateUrl: "firstPage.component .html",
})

export class firstPage implements OnInit {
    
    private items2: MenuItem[];

    ngOnInit() {
        
        this.items2 = [
            {
                label: 'Next',
                icon: 'fa-chevron-right'
            },
            {
                label: 'Prev',
                icon: 'fa-chevron-left'
            }
        ];
    }
}
```

3. module.ts
```
import { NgModule, ModuleWithProviders } from '@angular/core';
import { CommonModule} from "@angular/common";
import { FormsModule } from '@angular/forms';
import { firstPage } from "firstPage.component";

import { ContextMenu, MenuItem } from 'primeng/primeng';

@NgModule( {
    imports: [ContextMenuModule, MenuModule],
    declarations: [firstPage],
    exports: [firstPage ]
})

export class firstPagemodel
{
    
}
```

I don't know why this happens.
When I try to use **[global]="true"** it's work fine for me. But with **[target]="img"** don't work!

Any ideas how to fix this problem?

**Comment by himanshujain1985** [comment]
The [target] property is added in PrimeNg 4.x release. Please check which version of the library you are using.

**Comment by sudheerj** [comment]
Not able to replicate the issue.Please try with latest 4.x versions.
