### ISSUE TITLE
Collision detection for SplitButton

### ISSUE THREAD

**Issue by cyberrranger** [primefaces/primeng#2439]
see more info
https://github.com/primefaces/primeng/issues/1904#issuecomment-290742874

![screenshot 2017-03-31 17 08 47]
(https://cloud.githubusercontent.com/assets/21671762/24557174/05954440-1637-11e7-8421-3568f3757434.png)

i have on the top from the page a splitbutton with 12 entrys Jan. - Dec. is now the hight from the window > hight from all month Buttons, the overlay with the buttons open on the top

**Comment by cyberrranger** [comment]
#1904

**Comment by cagataycivici** [comment]
Fixed via 3063
