### ISSUE TITLE
Improve support for DatePipe/Moment.js

### ISSUE THREAD

**Issue by sliekens** [primefaces/primeng#2440]
**I'm submitting a ...** 
feature request

I use the Calendar component in my app and found that it is *really* hard to localize its date format using Angular's DatePipe or Moment.js with localizations.

**Please make it easier to format the displayed date in the Calendar component.** 

The Calendar only provides the following tokens for formatting dates:

> d - day of month (no leading zero)
> dd - day of month (two digit)
> o - day of the year (no leading zeros)
> oo - day of the year (three digit)
> D - day name short
> DD - day name long
> m - month of year (no leading zero)
> mm - month of year (two digit)
> M - month name short
> MM - month name long
> y - year (two digit)
> yy - year (four digit)
> @ - Unix timestamp (ms since 01/01/1970)
> ! - Windows ticks (100ns since 01/01/0001)
> '...' - literal text
> '' - single quote
> anything else - literal text

Moment.js provides a completely different set of tokens. Please add support for Moment.js tokens:
https://momentjs.com/docs/#/displaying/format/

 If you cannot support the tokens that Moment.js uses, please just provide an `@Input` option for the display value.

```js
// in Calendar component
@Input() displayValue: string;
```

Example API using ad-hoc Moment.js:
```html
<p-calendar [(ngModel)]="value" [displayValue]="moment.format(value)" />
```

Example API using DatePipe:

```html
<p-calendar [(ngModel)]="value" [displayValue]="value | date:'shortDate'" />
```

**Comment by StevenLiekens** [comment]
Another option that would work for me is if you implement templating for the display value. 

Example API:
```html
<p-calendar [(ngModel)]="value">
  <ng-template pTemplate="displayValue">
      <span>{{value | date:'shortDate}}<span>
  <ng-template>
</p-calendar>
```

**Comment by cagataycivici** [comment]
How about we provide a callback like timeFormatter where calendar calls your function to receive the formatted text.

**Comment by StevenLiekens** [comment]
Ehh it depends. How would the timeFormatter be configured?

As an input binding:
```
<p-calendar [(ngModel)]="value" [timeFormatter]="localize">
```

As an event binding:
```
<p-calendar [(ngModel)]="value" (timeFormatter)="localize(value)">
```

Maybe something else?

**Comment by cagataycivici** [comment]
Could be an input binding, not sure if it is possible to return a value from an EventEmitter if it is an @output.

**Comment by StevenLiekens** [comment]
Not directly possible, but if you emit an object then an event handler can mutate its properties. 

Anyway why can't the formatted date be a string binding?

**Comment by cagataycivici** [comment]
I don't think we can access the content of the template to get its output.

**Comment by StevenLiekens** [comment]
Okay forget about using binding syntax for this. How about you create a TimeFormatter service that is injected into CalendarComponent? Then I can create my own MyTimeFormatter service that implements TimeFormatter and add it to the providers array of my app module.

**Comment by zverbeta** [comment]
Hey, i found fast fix this issue, if you would like change model value, you should write:

Possible template syntax
`<p-calendar #calendar (onSelect)="select(calendar, event)"></p-calendar>`

Event listener output data
```
select(calendar) {
calendar.onModelChange(calendar.formatDate(calendar.value, '@'))
}
```

**Comment by huineng** [comment]
Can we possible align the primeng formatting with the angular datepipe conventions (or should this be a separate request ?) https://angular.io/api/common/DatePipe

example for year
prime y => 15 / yy => 2015
angular yy => 15   / y  => 2015 

example for month
prime MM  => September / m => 9
angular MMMM September / M => 9 
 
very confusing

**Comment by maiksch** [comment]
Anything new regarding this? I also would like to be able to use moment.js or DatePipe formatting for my PrimeNG calendar component

**Comment by digaus** [comment]
Imo the calendar should use angular datepipe for displaying the format aswell as the other metadata (can get day and month names throught the pipe).

**Comment by denes16** [comment]
Any news?, this will a very useful feature

**Comment by shahrishabhptechnical** [comment]
Any update on this?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by Et3rnal** [comment]
I don't see any solution for this, I would like a way to control what visible vs what on the model as well

- Pipe
- Template
- Or a new propriety like [displayType] which can take a method or format `dd/mm/yy`... without effecting the actual value

This should be reopened
