### ISSUE TITLE
Apply TreeNode styleClass on TreeTable row.

### ISSUE THREAD

**Issue by steveschmitt** [primefaces/primeng#2441]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Please add a `rowStyleClass` to the TreeNode that will be applied to the `div` row containing the node.  Currently one can use `styleClass` to affect individual columns, but not the containing row. 

**What is the motivation / use case for changing the behavior?**
This would allow individual rows to be styled, e.g. striping the table or highlighting rows based on content.

**Please tell us about your environment:** Windows, VSCode, Node

* **Angular version:** 2.4.10

* **PrimeNG version:** 2.0.5

* **Browser:** All
 
* **Language:** All

**Comment by ryancui-** [comment]
We need this feature too

I notice in the documentation, the definition of `TreeNode` contains `style` and `styleClass` but I found no implementation in source code. Hope be soon

**Comment by adityaprasoon** [comment]
+1

**Comment by UlricW** [comment]
Hi,
what's new about this feature ? is it a chance to be implemented ?
We need this kind of feature for our application

thanks

**Comment by adityaprasoon** [comment]
added pull request  #4015
