### ISSUE TITLE
DataTable event "onRowDblclick" should be renamed to "onRowDblClick"

### ISSUE THREAD

**Issue by dneelyep** [primefaces/primeng#2442]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

**Current behavior**

The event is named "onRowDblclick" (without a capital "c").

**Expected behavior**

The event is named "onRowDblClick" (with a capital "c").

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

The current wording is not consistent with the rest of the API, and causes typos when the event is typed into a text editor.

**Please tell us about your environment:**

Windows 7, Visual Studio Enterprise 2017

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [all]

 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
We have to keep it as it is due to backward compatibility. If more users demand it, we'll deprecate it and introduce the new one.
