### ISSUE TITLE
Support sort for dropdown in a table

### ISSUE THREAD

**Issue by panakour** [primefaces/primeng#2444]
Sort does not work properly if enable sortable on a table column and the content has dropdown

My code example:
```
    <p-column field="active" header="Active" [sortable]="true" [style]="{'overflow':'visible'}">
        <ng-template let-col let-data="rowData" pTemplate="body" >
            <p-dropdown [options]="userState" ></p-dropdown>
        </ng-template>
    </p-column>


```

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
