### ISSUE TITLE
primeNg dropdown placeholder doesn't work

### ISSUE THREAD

**Issue by wl1leo** [primefaces/primeng#2445]
Hi
**I am try to define placeholder using primeNg, but it doesn't work on some devices while it's working on another devices, please help me to define the problem,, regards  ...**

**Comment by luchillo17** [comment]
Too little description, try adding which devices and some screenshots of the errors.

**Comment by sudheerj** [comment]
I can't replicate the issue on desktop and mobile devices.It works fine on windows,macOS and iphone devices.Please provide more information.

**Comment by luchillo17** [comment]
@sudheerj First of all the description is too small and ambiguous, @wl1leo should put at least which devices is he talking to, PC? Mobile? if so which versions? Win 8? 10? Ubuntu 17.04? Mac OSX Sierra?

There's no point in testing anything if he doesn't specify better in which devices it fails.

**Comment by sudheerj** [comment]
@wl1leo If you are still able to find the issue then create a new issue with all the required details.This issue can be closed.
