### ISSUE TITLE
Setting background color to splitbutton

### ISSUE THREAD

**Issue by mohan1304** [primefaces/primeng#2450]
**Current behavior**

I followed below steps to set the background color of splitbutton but its not updating the background color

**Method 1 :** 

.html code
<p-splitButton icon="fa-level-up" iconPos="left"  [model]="rollupItems" label="Rollups" pTooltip="Rollups" tooltipPosition="bottom" styleClass="custom-background-style"></p-splitButton>

 .css code
.custom-background-style{
	background-color:yellow;
}

**Method2:**
<p-splitButton icon="fa-level-up" iconPos="left"  [model]="rollupItems" label="Rollups" pTooltip="Rollups" tooltipPosition="bottom"  [style]="{'background-color':'yellow'}"></p-splitButton>

**Expected behavior**

Setting background-color should update the background color of button. 
Please let me know if I have missed anything

**What is the motivation / use case for changing the behavior?**

I have a toolbar having multiple buttons placed horizintally. Clicking on the button should change the background-color of the button. Background color of prviously clicked button should be reset by clicking on other button.

**Please tell us about your environment:**

Windows7
* **Angular version:** 2.0.X

Angular 2.4.6
* **PrimeNG version:** 2.0.X

PrimeNG 2.0.0
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 IE11, Chrome 56
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript: 2.1.6
* **Node (for AoT issues):** `node --version` =

**Comment by Mrtcndkn** [comment]
We will add color option classes to splitbutton like in the regular buttons.After that you can change that class to give your own color.

**Comment by cagataycivici** [comment]
Please use forum for cases like these, as for the example;

```
.ui-splitbutton.custom-background-style .ui-button {
     background: yellow;
}
```
