### ISSUE TITLE
[Bug] Weird style errors with Ng4

### ISSUE THREAD

**Issue by luchillo17** [primefaces/primeng#2453]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Plunkr Case (Bug Reports) WIP**
Trying to create plunkr, WIP, use repo below meanwhile.

http://plnkr.co/edit/77OG7zX3LToGoidKaKOS

**Current behavior**
![image](https://cloud.githubusercontent.com/assets/9698639/24664108/5fefe400-191f-11e7-87d1-1e27eebc926b.png)

**Expected behavior**
Those white boxes under the app itself are weird, they should fill nice the area with Cruze theme.

**Minimal reproduction of the problem with instructions**
Have a repo with [Electron-Webpack](https://github.com/luchillo17/Electron-Webpack/tree/develop).

Run `npm i && npm run server:browser` in branch develop to start webpack-dev-server on port 8080, then press the "Add item" button at the bottom of the page.

If you want to test with the Electron way just `npm i && npm start:hmr`, then pressing the lowest button should suffice.

**What is the motivation / use case for changing the behavior?**
Broken styles.

**Please tell us about your environment:**

OS: Mac Sierra
IDE: Webpack 2 and VSCode.
Package Manager: npm.
Http: webpack-dev-server.

* **Angular version:** 4.0.1

* **PrimeNG version:** 4.0.0-rc.2
* **PrimeUI version:** 4.1.15

* **Browser:** [all | Chrome 57 | Electron-Renderer]
 
* **Language:** [all | TypeScript 2.2.2]

**Comment by sudheerj** [comment]
Is it the same issue with other themes as well or specific to Cruze theme

**Comment by luchillo17** [comment]
I've been updating many deps, and i cannot replicate right now, i'll post again if it ever happens again.

**Comment by sudheerj** [comment]
Okay.Thats great
