### ISSUE TITLE
Bug: Dialog box does not work in V4 rc.1 or rc.2

### ISSUE THREAD

**Issue by kcsahoo** [primefaces/primeng#2455]
Now that Angular V4 RTM is out, I hope PrimeNG team will soon release a bug free V4 of PrimeNG

There are a number of issues with V4 rc.1 and rc.2

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
