### ISSUE TITLE
Filtering for DataGrid

### ISSUE THREAD

**Issue by spyderz42** [primefaces/primeng#2457]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[* ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

I looked through the roadmap and issues and don't see this feature request. It would be nice if we could set up filtering and sorting on a datagrid just like you can on a datatable. (programatic sorting, not necessarily ui sorting)

**Comment by cagataycivici** [comment]
WE can add a global filter that filters on new filterField property that takes one or more props.

**Comment by sudheerj** [comment]
DataGrid is deprecated recently infavor of DataView component https://github.com/primefaces/primeng/issues/5255
