### ISSUE TITLE
DataTable sorting fails when replacing input data with copy of same list, and only once every four times.

### ISSUE THREAD

**Issue by dimitrijuchtmans** [primefaces/primeng#2464]
[X ] bug report

http://plnkr.co/edit/EN63WpZoojScOaqkF3yV?p=preview

The only thing I am doing is replacing the datatable input with the exact same list of elements, by clicking on the button. Every 4th time, the list is not ordered.

**Comment by cagataycivici** [comment]
Plunkr failed for me,  please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview

**Comment by dimitrijuchtmans** [comment]
Just click the button 4 times please. the plunker works perfectly here.
