### ISSUE TITLE
Pagination causes window location to be set to # and browser to direct away from datatable page

### ISSUE THREAD

**Issue by chrisexv6** [primefaces/primeng#2465]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

Please check reproduction instructions for live example (PrimeNG demo site)

**Current behavior**

Pagination control causes default event (href="#") to occur in Chrome.  If DataTable is open in a modal, the parent window location gets set to # and the modal automatically closes

**Expected behavior**
DataTable page data would change and nothing else would happen

**Minimal reproduction of the problem with instructions**
The bug can be seen directly on the PrimeNG website demo of a paginated DataTable.  

Access this URL using Chrome: https://www.primefaces.org/primeng/#/datatable/paginator

Click any of the paginator buttons and the Chrome window will be directed to: https://www.primefaces.org/primeng/#/

**What is the motivation / use case for changing the behavior?**

We have a form where the user can adds 1 or more items and they are stored in a DataTable.  Once the item count gets above a configurable amount, they need to page through them.  Once any pagination button is clicked (first, rewind, any page number, fast forward, last) the browser window is immediately directed to <webroot>/#

**Please tell us about your environment:**

Win10, VSCode, NPM, WEBrick/1.3.1 

* **Angular version:** 2.0.X
2.4.1

* **PrimeNG version:** 2.0.X
2.0.4
Also occurs on the PrimeNG website, Im not sure what version is running there

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome 57.0.2987.133
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

* **Node (for AoT issues):** `node --version` =

**Comment by encima** [comment]
I have just experienced this issue with a datatable component I am reusing in 2 different routes. Changing the page redirects the user to the home page. Is there any update on this?

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview

@Mrtcndkn Can you also test this.
