### ISSUE TITLE
Double Click event for TreeTable

### ISSUE THREAD

**Issue by djay1977** [primefaces/primeng#2468]
**I'm submitting a ...**  (check one with "x")
```
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
```

**What is the motivation / use case for changing the behavior?**

Would it be possible to add double-click event on node.
Currently, I have to go through a button to perform an action on the selected node.
Thanks

Solution :
On TreeTable component, add new EventEmitter : 
```
@Output() onRowDblclick: EventEmitter<any> = new EventEmitter();
```

On UITreeRow template, add (dblclick)="onRowDblclick($event)" : 
```
<td *ngFor="let col of treeTable.columns; let i=index" [ngStyle]="col.style" [class]="col.styleClass"  
(click)="onRowClick($event)" (touchend)="onRowTouchEnd()" (contextmenu)="onRowRightClick($event)" 
(dblclick)="onRowDblclick($event)">
```

onRowDblclick => call new TreeTable EventEmitter : 
```
    onRowDblclick(event: MouseEvent) {
      this.treeTable.onRowDblclick.emit({originalEvent: event, node: this.node});
    }
```

**Please tell us about your environment:**

Windows 10, IntelliJ IDEA 2017.1.1, yarn

* **Angular version:** 4.0.2

* **PrimeNG version:** 4.0.0-rc.3

**Comment by sudheerj** [comment]
The feature is already available.
