### ISSUE TITLE
UTF support for CSV export

### ISSUE THREAD

**Issue by ijaouani** [primefaces/primeng#2473]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/NoGsNQsDQRnIOgBNSInj?p=preview

**Current behavior**
When opening the csv file generated by the export function on datatable, the content is not properly encoded :

![image](https://cloud.githubusercontent.com/assets/27200712/24856238/45518fd0-1de4-11e7-9434-87a0156d11e6.png)

This may have been partially describe in issue #1880.

**Expected behavior**
The content should match the data seen on the datatable :
![image](https://cloud.githubusercontent.com/assets/27200712/24856701/f1da3c56-1de5-11e7-9a87-72d8000b948d.png)

**Minimal reproduction of the problem with instructions**
See plunkr above. Steps:
1. Click on CSV button
2. Open file in Excel
3. The content is not properly encoded.

**What is the motivation / use case for changing the behavior?**
The CSV file is often used in Excel.

**Please tell us about your environment:**
Windows 7 Pro x64

* **Angular version:** 2.4.5

* **PrimeNG version:** 2.0.5

* **Browser:**  Chrome Version 57.0.2987.133 (64-bit)
 
* **Language:**  TypeScript 2.1.5.0

* **Node (for AoT issues):** `node --version` =   6.10.0

**Comment by baigail93** [comment]
This doesn't seems to work in latest builds although the flag is set as described in the commit (closed on 12th April). Issue: https://stackoverflow.com/questions/45565126/primeng-localization-issue-with-export-datatable-csv

**Comment by AnaisR7** [comment]
Style having this issue. Can you reopen it please ?

![exportCSV_bug](https://user-images.githubusercontent.com/32449018/166649693-1a660c78-6e19-49a9-8d50-4a987ad9e521.PNG)
