### ISSUE TITLE
AutoComplete bound "disabled" property updated within event : ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by An0d** [primefaces/primeng#2474]
**I'm submitting a ...**
```
[x] bug report 
[ ] feature request 
[ ] support request
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/iOk6jUd4ubcP6OWCUgz0?p=preview

**Current behavior**
Since I updated Chrome to the latest version (57.0.2987.133) I'm facing an issue with the AutoComplete component
I'm still on Angular2 with PrimeNG 2.0.5 (reproduced with Plunkr on Angular 4.0.0 & PrimeNG 4.0.0-rc.1)

I've bound the "disabled" property of the AutoComplete component to a local variable (isDisabled)
When I try to update "isDisabled" to true within an event (click, onSelect and even ngModelChange) I got the following error :

`ORIGINAL EXCEPTION: Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'.`

I've tried everything I found... nothing works, I always got this error when updating the bound value ...
It worked perfectly before the Chrome update ... if I use enableProdMode() it works but it seems like a poor solution ...
When I run "ng serve" I'm not in "production mode" and then facing the issue.

The problem only occurs on the latest version of Chrome 57.0.2987.133
No problem (no error in console) in IE, Opera nor Firefox

**Expected behavior**
AutoComplete field should be disabled without any error

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/iOk6jUd4ubcP6OWCUgz0?p=preview

Just type "disable" in the AutoComplete field
ngModelChange event will fire and then error occur in Chrome console

**Please tell us about your environment:** Windows 8.1 & MacOS

* **Angular version:** 2.4.0 & 4.0.0 (Plunkr sample)

* **PrimeNG version:** 2.0.5 & 4.0.0-rc.1 (Plunkr sample)

* **Browser:** Chrome 57.0.2987.133
 
* **Language:** TypeScript

**Comment by Pythorogus** [comment]
Currently having the same problem. Did you find a solution ?

**Comment by cagataycivici** [comment]
There is utc property for this.

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
