### ISSUE TITLE
pass chip index to p-chip template

### ISSUE THREAD

**Issue by elega9t** [primefaces/primeng#2477]
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Expected behavior**
p-chip template should be able to access the chip index. This would help the custom template to be able to support the removeItem($event, index) feature.

**What is the motivation / use case for changing the behavior?**
I have a p-chip component which is has a custom template. In the custom template, I still want to have a remove(x) icon for user to be able to remove the chip.

* **Angular version:** 2.0.X
4.0.0

* **PrimeNG version:** 2.0.X
4.0.0-rc.2

**Comment by ivijan** [comment]
Hello @cagataycivici,
what would be the current status of this issue?
Will adding index be planned for the chip component?

I am looking a way how to validate each chip item via Angular form model, and the index could solve the problem.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
