### ISSUE TITLE
vertical alignment of p-steps component

### ISSUE THREAD

**Issue by alialtun14** [primefaces/primeng#2478]
[x] feature request

[In the present case] (https://www.primefaces.org/primeng/#/steps) there is no class to use p-steps in vertical alignment mode.  
I think it will make the component more useful if there is such an option.

![Sample of vertical steps component](https://cloud.githubusercontent.com/assets/782196/24887043/67c0e780-1e59-11e7-9544-e50de8a8de30.png)

**Comment by sudheerj** [comment]
+1 from my side. Also If we have more steps then it is good to have vertical alignment than horizontal.

**Comment by Ketec** [comment]
i happened to look at it (going to need soon), did a search and end up here. It is rather simple tho:
override` .ui-steps-item` `float:left` to `float:none ` and you get vertical steps.

**Comment by cagataycivici** [comment]
Sounds good.

**Comment by Pranavism** [comment]
with  .ui-steps-item {
  float:none !important;
}
how to get the horizontal line across steps to align vertically?
it remains horizontal in middle of vertical div

**Comment by sotoh** [comment]
It seems interesting but now we have Timeline Component.

**Comment by stephanie-dm** [comment]
With PrimeNG 11, the previous "float: none" workaround doesn't seem to work anymore.
I managed to accomplish a vertical layout with the following CSS (inside a component):

```
:host ::ng-deep .p-steps-item {
  padding-bottom: 15px;
}

:host ::ng-deep .p-steps ul {
  display: block;
  list-style-type: none;
  margin: 0;
  padding: 0;
}

:host ::ng-deep .p-steps .p-steps-item:before {
  content: none;
}
```

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by prnkrawat** [comment]
I want to know whether we can use vertical steps or not. Is it possible with primeNG?

**Comment by vtsimbos** [comment]
For vertical alignment create a css class with name 'stepsVertical'

`<p:steps class="stepsVertical">
<p:menuitem value=""/>
</p:steps>
`

body .ui-steps.stepsVertical:before{
    border-top: none;
    border-left: 1px solid var(--surface-border);
    height: 100%;
    left: 50%;
    top: 0;
}

body .ui-steps.stepsVertical ul{
    width: max-content;
    display: flex;
    flex-direction: column;
    margin: auto;
    height: 100%;
}
