### ISSUE TITLE
Severity support for SplitButton

### ISSUE THREAD

**Issue by Olmer1st** [primefaces/primeng#2482]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Hi,

Can you implement same Severity theming for splitbutton like for regular button. 
.ui-button-secondary
.ui-button-success
.ui-button-info
.ui-button-warning
.ui-button-danger

Thanks

**Comment by sudheerj** [comment]
This is not going to be complex thing.Normally only plain buttons will be used with severity.But this can be considered based on demand from user point of view :)

**Comment by Olmer1st** [comment]
Great! I thought it already work and was disappointed when checked.
