### ISSUE TITLE
Ability to cancel/revert value in editable datatable cells

### ISSUE THREAD

**Issue by borisremus** [primefaces/primeng#2485]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/8nAO6Bqox5n0Hba7q1yL

**Current behavior**
Pressing ESC when editing a cell in the datatable does not revert it's value

**Expected behavior**
When pressing ESC while editing a cell in a datatable the original value should be restored

**Minimal reproduction of the problem with instructions**
Click on a cell to start editing the value, modify the value, hit ESC

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Win10, IntelliJ

* **Angular version:** 4.0.X

* **PrimeNG version:** 4.0.X

* **Browser:** Chrome XX | Firefox XX | IE XX 
 
* **Language:** TypeScript 2.2

* **Node (for AoT issues):** `node --version` =

**Comment by mattqs** [comment]
You can store the original value within the onEditInit event and restore the original value in the onEditCancel event. That means pressing ESC is not an issue for me.

But, clicking outside of the edit textbox (onblur?) does not trigger any event and nothing can be done to fix this.

**Comment by DavidTheProgrammer** [comment]
@mattqs I am storing the original value `onEditInit` but I can't figure out how to restore the value after cancelling the editing with the `esc` key

**Comment by mattqs** [comment]
@DavidTheProgrammer 

```
@Component({
...
})
export class MyComponent {

  nameBeforeEdit = '';

  onEditInit(event) {
    this.nameBeforeEdit = event.data.name;
  }

  onEditCancel(event) {
    event.data.name = this.nameBeforeEdit;
    this.nameBeforeEdit = '';
  }

}
```

**Comment by DavidTheProgrammer** [comment]
I figured it put after trial and error. Thank you for this. I wish I saw it sooner... :-)

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
