### ISSUE TITLE
DataTable editable rows with templates don't have focus events

### ISSUE THREAD

**Issue by agusdutra** [primefaces/primeng#2486]
**I'm submitting a ...**  (check one with "x")
[X ] bug report => Search github for a similar issue or PR before submitting

**Current behavior**
When you use editable datatable with templates for editor and body, you lose the abilty to unfocus the row and navigate with TAB button and ENTER.

**Expected behavior**
When navigating the datatable on editable mode, you should be able to navigate to the next column with TAB and loose focus with ENTER when the row has editable templates.

**Minimal reproduction of the problem with instructions**

**Problem with Dropdown:**
On the showcase :  https://www.primefaces.org/primeng/#/datatable/editable

1. Case 1
1.1 Navigate with TAB from the first column until the dropdown (brand column) . 
1.2 Click TAB to navigate to the color column.
**Result:** You won't be able to navigate to the next column (color column).
2. Case 2
2.1 Navigate with TAB until the dropdown column.
2.2 Navigate with the arrow keys to select one item of the dropdown.
2.3 Click enter to confirm selection and lose focus. 
 **Result:** The dropdown is still active.

**Problem with input :** 
I'm also facing this issue in a project where I have to use conditional editing of an input text, depending on the value of another column. So I made the row editable with templates: 

```javascript
   <p-column field="totalPedido" header="Total Pedido" [sortable]="true"  [editable]="true">
        <ng-template let-col let-linea="rowData" pTemplate="editor">
                <input #input pInputText type="text" type="number"  *ngIf="canEdit(linea) ; else label"
                              [ngModel]="linea.totalPedido" 
                 <ng-template #label>
                         <span style="padding-right: 5px;">{{linea.totalPedido}}</span>
                </ng-template>
        </ng-template>
   </p-column>
```

**Please tell us about your environment:** WebStorm 2016.3, angular/cli 1.0.0

**PrimeNG version:**  "^4.0.0-rc.1"
**Angular version:**  "^4.0.0"
**Browser:** Chrome
**Language:** TypeScript 2.1.5

**Comment by siddharthaReddy** [comment]
Similar issue with 2.0.4

**Comment by desertdev** [comment]
I have almost the exact same problems, and running same versions as @agusdutra.

I needed to apply data binding to the dynamic input elements, so I also used templating to achieve this. It appears that any form controls inside <ng-template> tags lose the ability to handle the same keyboard events for ENTER and TAB that the normal input elements not inside template tags currently enjoy.

**Comment by cagataycivici** [comment]
Tab navigation is tracked at 2124

For enter and escape, since we don't know what kind of editor is inside, it is up to you to manage it, to close a cell, in 4.0-RC3 there is closeCell(event) method that you can call for example. Again for custom editors, we rather not intervene with escape and enter since these keys can have meanings for the editor eg dropdown.

**Comment by desertdev** [comment]
@cagataycivici: could you please provide a code snippet example on how to call closeCell()? 

I'm attempting to call it on blur but getting "ERROR TypeError: co.closeCell is not a function"

Example template code:
```
<ng-template *ngIf="col.editable" let-valcode="rowData" pTemplate="editor">
    <input type="text" pInputText [(ngModel)]="valcode[col.field]" (blur)="closeCell();" />
</ng-template>
```

**Comment by agusdutra** [comment]
I'm using it and it works.
You should have a dataTable reference and call it.
```javascript
<dataTable #dataTable> 
<p-column>
<ng-template *ngIf="col.editable" let-valcode="rowData" pTemplate="editor">
    <input type="text" pInputText [(ngModel)]="valcode[col.field]" (blur)="closeCell();" />
</ng-template>
</p-column>
</dataTable>

**Comment by desertdev** [comment]
Thank you @agusdutra, that was the piece I was missing! I just had to add the "p-" prefix to the dataTable tag name in your example.

**Comment by agusdutra** [comment]
yes, my bad. just corrected it.

**Comment by desertdev** [comment]
By the way, the new primeng 4.0-RC3 greatly improves the tabbing behavior when inside editable datatable cells. My simple example above actually gets in the way of the latest UI improvements, so instead I'm calling a separate method to decide if calling dataTable.closeCell() is even appropriate. (Still helpful for handling some custom functionality and a couple edge cases.)

@cagataycivici thanks for the great work and fast updates!

**Comment by sebastiansinsin** [comment]
@agusdutra have you solved the problem with input in editable datatable?
I have a same problem like you which I need to edit some column value and effect other column value.
could you help me to solve this?? thanks
