### ISSUE TITLE
Feature Request: Debounce on Datatable filter

### ISSUE THREAD

**Issue by kyle-burke** [primefaces/primeng#2489]
**I'm submitting a ...**
```
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
```

We use `[globalFilter]` as an entry point for server side filtering, and a debounce option in p-dataTable would save us from having to implement our own debounce wrapper around the lazyLoad function. If repo members/contributors think this would be useful, I'd be interested in providing a PR for it.

**Comment by tlcoder** [comment]
I agree a debounce option would be helpful as currently each keystroke hits our server.

**Comment by SchneMa** [comment]
exactly what I need! 
If possible you could also apply that option to Columns.
Slow typing on Column filter sometimes reset the textbox value...

**Comment by dzhavat** [comment]
Currently pressing almost any button (e.g. Esc ) will trigger an event. It will be useful to discard some of them.

**Comment by sakibulhasan** [comment]
4.1.1 released 2 days ago. Is this feature available? How can we use it for a textbox? any doc?

**Comment by pantonis** [comment]
How can we use debouncing for the OnFilter event?

**Comment by pantonis** [comment]
Tried to create a custom directive but unfortunately is not possible because cannot stop event propagation.

**Comment by pantonis** [comment]
Tried to create a custom directive but cannot be done as there is no actual event asssociated with onFilter

**Comment by pantonis** [comment]
How can you claim that you increased datatable perf if you missed such a feature which is easy to implement and is actually a perf bottelneck 👎

**Comment by mevalide** [comment]
Any update when this feature will be implemented? Any workaround available?

**Comment by pantonis** [comment]
@tigermev check this property ```filterDelay``` on https://www.primefaces.org/primeng/#/datatable. 
Filtering is implemented using timer which is very very wrong as it does not utilize the power of observables. I hope implementation changes

**Comment by tigermev** [comment]
@pantonis, yes, filterDelay should do the trick for me, thx also for your fix/contributions related to filterTimeout [https://github.com/primefaces/primeng/pull/3815](url)

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
