### ISSUE TITLE
Carousel : add rowsPerPageOptions feature

### ISSUE THREAD

**Issue by tranbenoit** [primefaces/primeng#2490]
Hello,

I would like to put many rows to the p-carousel component. However it seems there are no feature to do that. There's still the DataGrid component to solve that problem however I search to keep the ui-carousel-page-link design.
Is there any way to have a grid with ui-carousel-page-link's buttons ?

**Comment by cagataycivici** [comment]
Could you please provide more details? Do you want more multiline rows?

**Comment by tranbenoit** [comment]
At the beginning, I wanted to use p-carousel and add multiline rows. For example, I wanted the component to show 3x3 contents, like in DataGrid component

**Comment by mertsincan** [comment]
I think you can do it with new carousel component using template. Please try it. PrimeNg v8.1.0+

Best Regards,
