### ISSUE TITLE
[BUG] overlayVisible = true not working on p-multiSelect

### ISSUE THREAD

**Issue by mcwebdev** [primefaces/primeng#250]
overlayVisible = true not working on p-multiSelect.

**Comment by Mrtcndkn** [comment]
Locally it is working fine can you share your code please.

**Comment by cagataycivici** [comment]
I'm unable to replicate.

**Comment by vimalvaira** [comment]
<p-multiSelect  [options]="cities" 
                                        overlayVisible="isoverlayVisible"
                                        maxSelectedLabels="isDisplaySelectedLabel"
                                        [(ngModel)]="selectedCities"
                                         >
                        </p-multiSelect>

overkatVisible is supposed to open the drop down options right?

**Comment by mcwebdev** [comment]
It is supposed to render the multiselect with item container open.

**Comment by Mrtcndkn** [comment]
Just to be clear are you trying to open multiselect panel programatically for example with a button? @vimalvaira

**Comment by mcwebdev** [comment]
overlayVisible	boolean	TRUE	- > Specifies the visibility of the options panel OPEN

I currently achieve this using.
`.ui-multiselect .ui-multiselect-panel {
    display: block !important;
    visibility: visible;
}`

Acceptance.
Component loads on page already opened up.
![untitled](https://cloud.githubusercontent.com/assets/14930146/26180559/0e9032be-3b1f-11e7-9d9f-5836f1adb660.png)

**Comment by mcwebdev** [comment]
This may not be an issue anymore. we are using a custom multiselect based off an earlier iteration of primeng-multiselect.

**Comment by vimalvaira** [comment]
@Mrtcndkn yes that is exactly what I was trying to achive. 
In my case it would simply started to remaind open when it renders and button had no effect on its state.
@mcwebdev Ok thanks for update.
Thank you again for the quick reply.

**Comment by cagataycivici** [comment]
Will check again, last time it worked for me.

**Comment by cagataycivici** [comment]
I couldn't replicate again.
