### ISSUE TITLE
Please add a @Pipe/@Directive/@Component annotation in Angular 4

### ISSUE THREAD

**Issue by sagares421** [primefaces/primeng#2501]
Hi Team,
Can anyone provide the solution for the above error. We are facing this issue from last week but still upto now we didn't find any solution for this.
Kindly Help asap to the error resolved.

![image](https://cloud.githubusercontent.com/assets/19843046/24963486/578426ca-1fbc-11e7-8709-c821b2a2324f.png)

Regards,
SAPAriba Team

**Comment by cagataycivici** [comment]
Please use forum for support requests like these. Seems like a configuration issue on your side.

**Comment by Inlesco** [comment]
I encountered this issue before and solved it. Please read ---> https://github.com/primefaces/primeng/issues/3144
