### ISSUE TITLE
Template parse errors: "let-" is only supported on template elements.

### ISSUE THREAD

**Issue by sagares421** [primefaces/primeng#2502]
Hi Team,
Can anyone provide the solution for the above error. We are facing this issue from last week but still upto now we didn't find any solution for this.
Kindly Help asap to the error resolved.

vendor.bundle.js:51217 EXCEPTION: Uncaught (in promise): Error: Template parse errors:
"let-" is only supported on template elements. ("

    <p-dataTable [value]="cars" expandableRows="true">
        <ng-template [ERROR ->]let-car pTemplate="rowexpansion">
            <div class="ui-grid ui-grid-responsive ui-fluid" style="): DashboardComponent@3:21
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("

    <p-dataTable [value]="cars" expandableRows="true">
        [ERROR ->]<ng-template let-car pTemplate="rowexpansion">
            <div class="ui-grid ui-grid-responsive ui-"): DashboardComponent@3:8
Error: Template parse errors:
"let-" is only supported on template elements. ("

    <p-dataTable [value]="cars" expandableRows="true">
        <ng-template [ERROR ->]let-car pTemplate="rowexpansion">
            <div class="ui-grid ui-grid-responsive ui-fluid" style="): DashboardComponent@3:21
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("

    <p-dataTable [value]="cars" expandableRows="true">
        [ERROR ->]<ng-template let-car pTemplate="rowexpansion">
            <div class="ui-grid ui-grid-responsive ui-"): 

![image](https://cloud.githubusercontent.com/assets/19843046/24963756/21d74862-1fbd-11e7-9712-ae6173bfdbef.png)

Regards,
SAPAriba Team

**Comment by ctrl-brk** [comment]
Which Angular version do you use? ng-template is Angular4

**Comment by sagares421** [comment]
We are using Angular 4.0.0

**Comment by cagataycivici** [comment]
Please use forum for support requests, seems to be related to your Angular version.

**Comment by binary2quantum** [comment]
faced the same issue... but now fixed it

Try template instead of ng-template...it's working fine for me

**Comment by jibin-tj** [comment]
Works for me too. I use angular 2

**Comment by himajaM** [comment]
![image](https://user-images.githubusercontent.com/26132177/33057873-e37d494a-ceb2-11e7-8373-0f4fbe323976.png)


Error: Template parse errors:↵"let-" is only supported on ng-template elements. ("eadOnly]="true">
↵ <template wjFlexGridCellTemplate [cellType]="'Cell'" [ERROR ->]let-item="item">

Above is my error facing with wijmo after upgrading to angular 5 version

**Comment by vladimirmelekh** [comment]
+1, same error after update to angular 5 from angular 2. Any ideas how to fix?

**Comment by vladimirmelekh** [comment]
Hey @himajaM, just replace <template> with <ng-template> everywhere.

**Comment by nagchanda** [comment]
Was anyone able to resolve this issue ?

**Comment by elialber** [comment]
Import "TableModule" on NGModule.

**Comment by SmithaShankar** [comment]
Even i'm facing this issue on ng build --prod. But i do not have any <template> tags it is all replaced with <ng-template> and ngx-bootstrap is also not used in project. Please help on this.
ERROR in : "let-" is only supported on ng-template elements. ("
          </td>
        </tr>
          <template ngFor [ERROR ->]let-row [ngForOf]="rows" let-i= "index" >
          <tr [ngClass]="{'table-info': showExpandedRow && ")
: "let-" is only supported on ng-template elements. ("
          </td>
        </tr>
          <template ngFor let-row [ngForOf]="rows" [ERROR ->]let-i= "index" >
          <tr [ngClass]="{'table-info': showExpandedRow && (i == expandedRowIndex) &")
: "let-" is only supported on ng-template elements. ("}" style="font-size:1.5em; cursor:pointer"></i></a>
            </td>
              <template ngFor [ERROR ->]let-column [ngForOf]="columns" let-j= "index" >

                <td (click)="cellClick(row, column.n")
: "let-" is only supported on ng-template elements. ("or:pointer"></i></a>
            </td>
              <template ngFor let-column [ngForOf]="columns" [ERROR ->]let-j= "index" >

                <td (click)="cellClick(row, column.name, i)" *ngIf="!column.isEditi")

**Comment by mgleria** [comment]
I face the same problem and replacing <template> tag by <ng-template> I solved the issue.
