### ISSUE TITLE
NPM TreeDragDropService Missing!

### ISSUE THREAD

**Issue by KiransHub** [primefaces/primeng#2504]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

NPM appears to be missing TreeDragDropService. I have tried various versions and none of them appear to include the file. I ended up having to download the source from github.

**Comment by cyberrranger** [comment]
show #683

**Comment by cagataycivici** [comment]
You need to use PrimeNG 4.

**Comment by KiransHub** [comment]
right you are.. I started using NG4 and it's all working. Thank you.
