### ISSUE TITLE
Router Link for each tab of the TabView

### ISSUE THREAD

**Issue by uroti** [primefaces/primeng#2505]
Hi to all,
I have a Tabview Panel in which each Panel contains a component. I would like to have a different "link" for each panel so I using the router link. Actually this is my situation

[template](http://textuploader.com/dr69o)
[function](http://txt.do/dr69j)

This work well but it is only a simulation of what I want. In fact, in this way, I have the components outside the panels. I tried this solution but it didn't work :

[Not working Template](http://txt.do/dr694)

Do you have a solution?

Thank you

**Comment by cagataycivici** [comment]
Please use forum for cases like these, I'd suggest tabMenu component by the way.
