### ISSUE TITLE
Rename SharedModule

### ISSUE THREAD

**Issue by markgoho** [primefaces/primeng#2508]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
SharedModule imports conflict with existing SharedModule imports (i.e. namespace conflict)

**Expected behavior**
Primeng SharedModule should be uniquely namspaced to not conflict with generic "SharedModule" in existing projects.

**Minimal reproduction of the problem with instructions**
Use any module that requires importing the SharedModule from primeng. If there is an existing SharedModule being used in the current project, Angular gives an error with conflicting module names.

**What is the motivation / use case for changing the behavior?**
Using such a generic name "SharedModule" is bound to conflict with other things down the road.

**Please tell us about your environment:**
Win10, VS Code, Yarn

* **Angular version:** 4.0.2

* **PrimeNG version:** 2.0.6

* **Browser:** [all]

 
* **Language:** [TypeScript 2.2]

* **Node (for AoT issues):** `node --version` = 7.7.4

**Comment by cagataycivici** [comment]
Why not;

```
import SharedModule as PrimeSharedModule from "primeng/common/shared";
``

Also why do you need to import SharedModule in the first place?

**Comment by markgoho** [comment]
@cagataycivici great suggestion! That didn't even occur to me as an option, so thank you.

As per your docs:
![image](https://user-images.githubusercontent.com/9759954/27755847-75506ce4-5dc0-11e7-97ac-9ee920985832.png)

**Comment by cagataycivici** [comment]
Oh yes, we should remove it.
