### ISSUE TITLE
DataTable filter cannot filter out "active" ones between "active" and "inactive"

### ISSUE THREAD

**Issue by westlake91361** [primefaces/primeng#2509]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/PyI9u8cDvV3Vx0VSjhFM

**Current behavior**
Tried to filter by "Active". Changed filterMatchMode to use "equals", "startsWith" and "endsWith" but the results are the same -- can only filter by "inactive". If use "active" will return the whole list with both "active" and "inactive". It seems no matter which filterMatchMode I use, the filter results are the same. No exact match being returned.

**Expected behavior**
FilterMatchMode "equals"should return the word that contains the exact same words in the filter search.  For this case, filter by "active" with filterMatchMode = equals should only return the "active" items.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
Filter results should be based on the filterMatchMode. For "equals", unless it's an identical match no results should be returned; for "startsWith", should only return the words exactly start with the filter term, etc.

**Please tell us about your environment:**
Window 10, IntelliJ Ultima, npm

* **Angular version:** 4.0.0-rc.3

* **PrimeNG version:** 4.0.0-rc.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
