### ISSUE TITLE
[Bug] Full Calendar

### ISSUE THREAD

**Issue by mcwebdev** [primefaces/primeng#251]
open dialog on full calendar -> minimize dialog -> close dialog -> click on calendar again to instantiate calendar -> dialog does not display.

**Comment by cagataycivici** [comment]
Dialog is reimplemented as a native widget and minimize maximizable are left out initially so this doesn't apply anymore. When we re-add them, we'll consider this case as well.

**Comment by amitinnotical** [comment]
I am using primeng schedule its working but when i click on day slots of week and day view. it not working on some last hours. i dont know why. i bind minTime with a varible which come form api and its work as i want. but onDayClick method is not working on last slots Please help ASAP
<p-schedule #ref id="calendar" [events]="events" (onViewRender)="ViewChanged($event,ref)"   [header]="header" [slotDuration]="timeSlot"
                [minTime]="startTime" locale="en" [defaultView]='defaultView' [defaultDate]='today' [eventLimit]="4" (onDayClick)="handleDayClick($event)"
                (onEventClick)="handleEventClick($event)" (onEventMouseover)="showEeventDeatils($event)" (onEventMouseout)="hideEeventDeatils($event)"></p-schedule>
