### ISSUE TITLE
Add closeCell method to DataTable

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#2511]
Useful when there are custom cell editors so users can call it within their custom editors to close it.

**Comment by raviganesh12** [comment]
How to use this method? Any documentation will be helpful.

**Comment by cagataycivici** [comment]
```
<p-dataTable #dt
```

Whenever you need;

```
dt.closeCell()
```

**Comment by raviganesh12** [comment]
@cagataycivici  Thanks!
