### ISSUE TITLE
MenuBar router links do not work

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#2512]
RouterLink definition is ignored.

**Comment by Danieleeee** [comment]
Hi,
the problem is Still in RC3

**Comment by cagataycivici** [comment]
I can't replicate, sorry.

**Comment by hschindler** [comment]
Hi,
my links still doesn't work to with rc3 in panelMenu.

**Comment by cagataycivici** [comment]
PanelMenu is a different component, please create a new ticket then.

**Comment by Danieleeee** [comment]
Open here: #2522
