### ISSUE TITLE
filter in datatable crash

### ISSUE THREAD

**Issue by gustavobrian** [primefaces/primeng#2516]
Hello, and Thanks....
![img_20170413_125842](https://cloud.githubusercontent.com/assets/7863258/25013406/cf80f0ee-2049-11e7-93ca-4b994713a869.jpg)
![img_20170413_125534](https://cloud.githubusercontent.com/assets/7863258/25013416/d71aa160-2049-11e7-8946-8cd6bc14be35.jpg)

Version:
angular 4.0.2
primeng 2.0.6

On change 'Codigo' filter:
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: '3'. Current value: '2'.

**Comment by cagataycivici** [comment]
Please use PrimeNG 4.x.

**Comment by gustavobrian** [comment]
npm unistall primeng
and
npm install primeng@4.0.0-rc.2
 
the problem solved... thank for all... i love primeng....
