### ISSUE TITLE
Pass index of the row to onRowDblclick event

### ISSUE THREAD

**Issue by ndmello** [primefaces/primeng#2518]
I'm submitting a ...  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
Plunkr Case (Bug Reports)
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

Current behavior
OnRowDblclick event  provides event.originalEvent and event.data parameters only

Expected behavior
OnRowDblclick event should provide index of the row double clicked through event.index parameter 

What is the motivation / use case for changing the behavior?
I want to select multiple rows of datatable using checkbox for delete all etc and onRowDblclick event should show a modal to edit that row's values.

Angular version: 4.0.0

PrimeNG version:   4.0.0-rc.2

Browser: all 
 
Language: TypeScript 2.1 

Node (for AoT issues): `node --version` =   3.10.10

**Comment by mlakhara** [comment]
This should also be done for onRowClick event as well. @cagataycivici

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
