### ISSUE TITLE
PanelMenu router links do not work

### ISSUE THREAD

**Issue by Danieleeee** [primefaces/primeng#2522]
Hi, the problem is still in RC3 p-panelMenu.

**Comment by kcsahoo** [comment]
Works for me

**Comment by Danieleeee** [comment]
You load the menu in static way? Or dinamically from a service?

**Comment by sudheerj** [comment]
Is it related to menubar or panelmenu? Please provide an example to replicate.

**Comment by Danieleeee** [comment]
It is panelmenu:
`<p-panelMenu  [model]="items"></p-panelMenu>`
