### ISSUE TITLE
DataTable unable to edit data in an object

### ISSUE THREAD

**Issue by jefftham** [primefaces/primeng#2526]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

http://plnkr.co/edit/ar720AXLtznRvmCdFxf4?p=preview

**Current behavior**
DataTable is able to display the value in inner object. However, it is not saving correctly.
eg. 
Value of stockList[0].data.avg should be changed.
However, it created another field of stockList[0]["data.avg"].

**Expected behavior**
the new data should be binding to the same field,

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

DataTable should be working not only for a "flat" array of objects, but it should be also working for an array of complex objects.

**Please tell us about your environment:**

Windows 10, vscode, npm, angular 2, angular/cli, google firebase

* **Angular version:** 4.0.0

* **PrimeNG version:** 2.0.6

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] all browsers

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5] TypeScript 2.2.2

* **Node (for AoT issues):** `node --version` =   7.8.0

**Comment by nekkon** [comment]
+1 had the same problem

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
