### ISSUE TITLE
rowHeight calculation is not correct with cell body template

### ISSUE THREAD

**Issue by kmcs** [primefaces/primeng#2528]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/qPDOgRHGA5GkRhwArWfq?p=preview

**Current behavior**
The calculation of rowHeight in ScrollableView is done once:
https://github.com/primefaces/primeng/blob/8dac138a21215152289110c3ad26821d00b2608f/components/datatable/datatable.ts#L314

If you use a cell template you do not get the right cell height on the first ngAfterViewChecked() call.

**Expected behavior**
Remove caching of rowHeight calculation?

**What is the motivation / use case for changing the behavior?**
See the punkler below, you always have a vertical scrollbar.

**Please tell us about your environment:**

* **PrimeNG version:** 2.0.4 ->

* **Browser:** [Chrome 56 | Firefox 52]

* **Language:** all

* **Node (for AoT issues):** `node --version` =   5.12

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
