### ISSUE TITLE
Breadcrumb home icon customization fails

### ISSUE THREAD

**Issue by sudheerj** [primefaces/primeng#2531]
We can use home property of Breadcrumb component to customize it as menu item.But as of now the icon is not overriden from menuitem.

```
this.home = {
            label: 'Home',icon: 'fa-globe', command: (event) => {
                this.msgs.length = 0;
                this.msgs.push({severity: 'info', summary: "Home"});
            }
        };
```

**Comment by wlanni** [comment]
I don't understand why this was closed. The documentation [here](https://www.primefaces.org/primeng/#/breadcrumb) still displays the home property as configurable as a MenuItem. Is this going to be added into another milestone?

**Comment by rich4756** [comment]
It seems the only MenuItem field that has an affect is command. I am specifically looking to change the icon and add text.
