### ISSUE TITLE
Filters & Editable issue

### ISSUE THREAD

**Issue by Pinank** [primefaces/primeng#2537]
Hi Guys,

I'm using Editable & Filters list in Grid. Here is the code.

```
<p-dataTable [value]="dataList" [editable]="true" [rows]="8" [paginator]="true" [globalFilter]="gb">
    <p-column *ngFor="let col of cols" [field]="col.field" [header]="col.header" [filter]="col.filter"
              [filterPlaceholder]="col.placeholder" [editable]="col.editable"></p-column>
  </p-dataTable>
```

Its working fine for the local column wise filter and editing. I'm requiring the data to filter from API so for that i have to stop the local filter that PrimeNG is providing and hit the api on each character search. So is their any event which can return the search value to the TypeScript class?

Also with Editable, i'm not getting the edited value in TypeScript class. So is their any event which can return the edited cell value?

Thanks in Advance.

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
