### ISSUE TITLE
PUI is not defined on Dropdown

### ISSUE THREAD

**Issue by MurhafSousli** [primefaces/primeng#254]
I'm getting this error when I click on dropdown

`EXCEPTION: Error during evaluation of "click"
EXCEPTION: ReferenceError: PUI is not defined`

_template_
```
<div class="ui-grid-row">
    <div class="ui-grid-col-2"><label class="ui-outputlabel" for="role">Role</label></div>
    <div class="ui-grid-col-4">
      <p-dropdown [options]="roles" [(ngModel)]="selectedRole" id="role" class="ng-untouched ng-pristine ng-valid"></p-dropdown>
    </div>
</div>
```
_component_
```
import {Dropdown, SelectItem} from 'primeng/primeng';

export class AddUserCmp {

  roles: SelectItem[];
  selectedRole: string;

  constructor(){
    this.roles = [];
    this.roles.push({label: 'Employee', value: 'employee'});
    this.roles.push({label: 'Admin', value: 'administrator'});
  }
}
```
How can I fix PUI?

**Comment by cagataycivici** [comment]
Please include;

<script src="node_modules/primeui/primeui-ng-all.min.js"></script>

From PrimeUI

Hopefully in beta4, we'll break this dependency.

**Comment by manpreetAjimal** [comment]
I am also facing the same issue nad using angular beta15 version  and primeng@1.0.0-beta.2

**Comment by cagataycivici** [comment]
Upgrade to a newer primeng version please.
