### ISSUE TITLE
InputTextArea with AutoResize mode within a p-datatable

### ISSUE THREAD

**Issue by tigrenok00** [primefaces/primeng#2542]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Hi!
I want to use InputTextArea with AutoResize mode within a p-datatable. I've put it inside a p-column template, however, the text area does not resize automatically. Is there any additional configuration/styling should I apply to the table/column to make it work?
Thanks!

* **PrimeNG version:** 2.0.0-rc1

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
