### ISSUE TITLE
Error on Date object during Primeng DataTable Cell editing 

### ISSUE THREAD

**Issue by a4amitava** [primefaces/primeng#2545]
Please help . Getting the below error while prime data table cell editing for date object .
Although , the date is getting displayed but unable to edit and select calendar . Getting the below error-

_Error: Uncaught (in promise): Unexpected literal at position 2
    at resolvePromise (zone.js:712) [angular]
    at polyfills.bundle.js:3084:17 [angular]
    at Object.onInvokeTask (core.es5.js:4116) [angular]
    at ZoneDelegate.webpackJsonp.718.ZoneDelegate.invokeTask (zone.js:397) [angular]
    at_ 

The date in back end Data base is in this format 	**2016-03-10T00:00:00.000-07:00** .

The code i am referring from https://www.primefaces.org/primeng/#/datatable/editable
Below the code spinet 
```
<p-column field="toDate" header="Revision Date" [editable]="true" [style]=" {'overflow':'visible' }">
        <ng-template let-col let-row="rowData" pTemplate="body">
             {{row[col.field] | date}}
        </ng-template>
        <ng-template let-col let-row="rowData" pTemplate="editor">
            <p-calendar [(ngModel)]="row[col.field]"></p-calendar>
        </ng-template>
    </p-column>
```

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/77OG7zX3LToGoidKaKOS

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.0.X

* **PrimeNG version:** 4.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   6.10.0

**Comment by meanle11** [comment]
it's me the same. i hope will to ask why, maybe can fix it ?

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
