### ISSUE TITLE
CodeHighlighter example

### ISSUE THREAD

**Issue by mohan1304** [primefaces/primeng#2547]
I think I didn't completely understood the CodeHighlighter functionality. Need help with my below requirement

I have buttons placed horizontally and when I click on the button, view corresponding to that button functionality should be activated and the button should be highlighted. When I click on a different button the clicked button should be highlighted and previously highlighted button should be un highlighted.

It will be helpful if you can provide a sample code or detailed steps to achieve this

**Please tell us about your environment:**

Windows 7
* **Angular version:** 2.0.X

Angular 2.4.3
* **PrimeNG version:** 2.0.X

"primeng": "^2.0.0"
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome, IE11
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
"typescript": "^2.1.5",
* **Node (for AoT issues):** `node --version` =

**Comment by Mrtcndkn** [comment]
CodeHiglighter is for highlighting the code snippets. In our showcase we use codehighlighter for every documentation. You can't highlight a component with it.
