### ISSUE TITLE
Dropdown panel is not as wide as supposed to when appendTo is set to body.

### ISSUE THREAD

**Issue by akorchev** [primefaces/primeng#2551]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

http://plnkr.co/edit/ErA2nmOQglE6aRSWAsZl?p=preview

**Current behavior**

Dropdown panel isn't as wide as supposed to when appendTo is set to "body". 
**Expected behavior**

Dropdown panel should be as wide as the dropdown always.
**Minimal reproduction of the problem with instructions**

Open the plunker and open both dropdowns. The only difference is `appendTo="body"`.
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.0.X

* **PrimeNG version:** 4.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 all
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Reopen to use min-width.
