### ISSUE TITLE
No column titles in Datatable stacked mode without responsive attr

### ISSUE THREAD

**Issue by L-VE** [primefaces/primeng#2554]
**I'm submitting a ...** 
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
[http://plnkr.co/edit/iBQCJnEYa5UbtxC3bOQv](http://plnkr.co/edit/iBQCJnEYa5UbtxC3bOQv?p=preview)

**Current behavior**

Only when the responsive attribute is set to true, the td elements in the tbody contain a 
`<span class="ui-column-title">....</span>` which is visible when the table goes into stacked mode.

This is because the following line of code is defined in the TableBody template: 
`<span class=\"ui-column-title\" *ngIf=\"dt.responsive\">{{col.header}}</span>`

**Expected behavior**

Shouldn't this also happen when only the stacked attribute is used without the responsive attribute?
When you yourself determine the breakpoint where the datatable must go into stacked mode.
Or do these attributes have to be used together? Like setting the responsive value to match the stacked value?

**Please tell us about your environment:**

* **Angular version:** 4.0.2

* **PrimeNG version:** 4.0.0-rc.3

* **Browser:** all

 
* **Language:** TypeScript

**Comment by cagataycivici** [comment]
responsive property is required for this to work.
