### ISSUE TITLE
[BUG] Checkbox disable parameter not working

### ISSUE THREAD

**Issue by igogu** [primefaces/primeng#2555]
[ X] bug report => Search github for a similar issue or PR before submitting

https://plnkr.co/edit/MUCmGIK3FufosNFqQO1g?p=preview

**Current behavior**
Disable attribute of checkbox component is a boolean attribute, but it is not getting the value of the input, when you write the disable property the checkbox is automatically disabled. For example with:
`
<p-checkbox  binary="true" disabled="false"></p-checkbox>`

**Expected behavior**
The checkbox should change to enable if you write the input value as false, and only disabled if its true.

**Minimal reproduction of the problem with instructions**
it has the same behaviour:
```

<p-checkbox  binary="true" disabled="false"></p-checkbox>
<p-checkbox  binary="true" disabled="true"></p-checkbox>
```

**What is the motivation / use case for changing the behavior?**
It is just how it was working after primeng 4.x.x I think, I am not sure about what version was working well

**Please tell us about your environment:**

SO: Ubunut 16.04
IDE: eclipse neon
package manager: npm 

* **Angular version:** 4.0.2

* **PrimeNG version:** 4.0.0-rc.3

* **Node (for AoT issues):** `node --version` =   7.2.0

**Comment by Mrtcndkn** [comment]
Hi,

You should bind that attribute to the component like this

     <p-checkbox  binary="true" [disabled]="true"></p-checkbox>
     <p-checkbox  binary="true" [disabled]="false"></p-checkbox>
