### ISSUE TITLE
id property to menuitem api

### ISSUE THREAD

**Issue by CSHaze** [primefaces/primeng#2559]
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Current behavior**
There is no way to set an id attribute (that will appear in html) of items that are set in the component ts.

**Expected behavior**
Be able to set an id in component ts that will be displayed as an id attribute in the html.

**Minimal reproduction of the problem with instructions**
Create a menu item array in the component ts file.
Bind this to a menu bar. 
Notice there is no option to set an id in the menu item.
Examine html, notice there is no id attribute on any of the menu items.

**What is the motivation / use case for changing the behavior?**
I would like ids so I can find elements easier when running automated testing using Protractor.

**Please tell us about your environment:**
Windows 7, WebStorm, NPM

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by ZackAfro** [comment]
Was this ever added? I can add id to my menuItem model but it is not showing up in the DOM.
