### ISSUE TITLE
p-dropdown's placeholder attribute not working

### ISSUE THREAD

**Issue by saurav12** [primefaces/primeng#2562]
I'm submitting a bug report on [PrimeNG Dropdown](https://www.primefaces.org/primeng/#/dropdown).

    <p-dropdown [options]="cities" [(ngModel)]="selectedCity" placeholder="Select a City"></p-dropdown>

**Issue Explanation:**
I am unable to use the placeholder feature of `p-dropdown` template. Whenever I use placeholder attribute nothing happens & the default value is shown as the first select option value of the dropdown select item.

**Plunkr Case (Bug Reports)**
I've created a demonstration of the issue on [**Plunkr**](http://plnkr.co/edit/W631pfzRPoS4sgWh251N?p=preview).

**Environment Details:**
Below are my environment details in which I'm facing the issue:

    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/router": "3.0.0",
    "bootstrap": "^4.0.0-alpha.5",
    "core-js": "^2.4.1",
    "primeng": "1.1.4",
    "rxjs": "5.0.0-beta.12",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.6.23"

 - Angular version: 2.0.0
 - PrimeNG version: 1.1.4
 - Browser: All

**Comment by Mrtcndkn** [comment]
It is fixed after 2.0.3 you need to upgrade your PrimeNG version.

**Comment by jack-liyou** [comment]
"Primeng": "^4.2.2""
The same problem

**Comment by sangwingawande-sdn** [comment]
+1

**Comment by Trolejbus** [comment]
In my case (primeng version 9.1.3) setting optionLabel fixed this issue.

**Comment by AlexDEVpro** [comment]
> In my case (primeng version 9.1.3) setting optionLabel fixed this issue.

But then another problem arises: dropdown element starts to set as value entire SelectItem instead of value from it.
