### ISSUE TITLE
Problems writing words with tilde in "single" p-autocomplete field

### ISSUE THREAD

**Issue by alfupe** [primefaces/primeng#2563]
**I'm submitting a ...** 
```
[x] bug report => Search github for a similar issue or PR before submitting
```
**Current behavior**
Writing words with tildes in a SINGLE p-autocomplete input produce bad outputs: Writing "sesión" will produce "sesi´on". **Changing absolutely nothing but [multiple]="true" produce good output**: for instance "sesión" will print OK.

**Expected behavior**
Excepted good output when writing words with tildes.

**Minimal reproduction of the problem with instructions**
I've been unable to create a plunker.
I have tested the Basic example in https://www.primefaces.org/primeng/#/autocomplete and is working for me. Could it be caused by the "primeng": "^4.0.0-rc.2" version?

**Please tell us about your environment:**
* **Operating system:** Mac OS X 10.11.6 El Capitan
* **IDE:** PHPStorm 2017.1.2

* **Angular CLI version:** 1.0.0
* **Angular version:** 4.0.1
* **PrimeNG version:** 4.0.0-rc.2

* **Browser:** Chrome 57
* **Language:** [TypeScript 2.2.2]

* **Node (for AoT issues):** `node --version` =  v6.9.1

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview

**Comment by alfupe** [comment]
4.0.3 seems that have resolve the issue. Thanks.

**Comment by cagataycivici** [comment]
Nice!
