### ISSUE TITLE
[Bug] in FileUpload Component

### ISSUE THREAD

**Issue by EddyP23** [primefaces/primeng#2564]
The problem is that the method `isFileTypeValid` is implemented in a very weird way on the component.

For the details, please see my comment on this issue:
https://github.com/primefaces/primeng/issues/1694#issuecomment-294793171

**Comment by XiaoSeb** [comment]
Hi,
I think it should be something like that:
`var acceptable = this.isWildcard(type) ? this.getTypeClass(file.type) === this.getTypeClass(type)
                : file.type === type;`

**Comment by mnn** [comment]
It's definitely broken. When I use `application/pdf` it marks every file as invalid (even pdf files).

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview

**Comment by saiidabs** [comment]
anyone find a fix?
