### ISSUE TITLE
SplitButton does not work as expected within an CD.OnPush Component

### ISSUE THREAD

**Issue by vlodko** [primefaces/primeng#2566]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**Current behavior**
Now when parent component has CD.onPush, dropdown menu in split button doesn't work as expected - menu stays open when you click outside of split button.

**Expected behavior**
Dropdown should menu be closed when you click outside of split button.

**What is the motivation / use case for changing the behavior?**
Every PrimeNG component should work correctly with CD.onPush. 
It applies for 2.x and 4.x versions.

* **Angular version:** 2.4.9

* **PrimeNG version:** 2.0.6

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/VZbdZfQ7SuTV87tTkbYR
