### ISSUE TITLE
More alignment options to OverlayPanel

### ISSUE THREAD

**Issue by dhniels** [primefaces/primeng#2567]
[x] feature request 

Looking for a way to align the overlay panel, by default it aligns the top and left edge to its parent element, but it would be nice to have other ways to align it. 

For example:  
- top-left
- top-center
- top-right
- bottom-left
- bottom-center
- bottom-right
- right-top
- right-center
- right-bottom
- left-top
- left-center
- left-bottom

**Comment by BustyLoli-Chan** [comment]
This would be an extremely helpful feature to have as the current positioning of the overlay panel in conjunction with my current pages layout leads to the overlay getting cut off at certain browser resolutions. 
This essentially makes the panel in it's current state useless.

**Comment by dhniels** [comment]
Any updates on this feature?

**Comment by mkp05** [comment]
Any news about this feature? For a start is range similar to "tooltipPosition" from tooltip component would be enough (especially as tooltip does not accept a HTML for a text, so it's impossible to put for example an image in the tooltip - need to use OverlayPanel).

**Comment by dhniels** [comment]
[I found this example of a popover](https://github.com/ncstate-sat/popover) (built on Angular CDK) but they provide a horizontalAlign and verticalAlign option set that is exactly what I'm looking for. 

Check it out! There are some additional neat options provided. I think PrimeNG should glean some of the functionality ideas theyve employed here. Adding an arrow on top of that would make OverlayPanel a killer component :)

**Comment by JacobSiegle** [comment]
Seems like if this was implemented it would be useful in implementing #5213.

**Comment by televic-education** [comment]
Is this feature on the roadmap for the near future? If you want, I can implement this and create a pull request for it...

**Comment by cagataycivici** [comment]
Planned for 6.1.2.

**Comment by SwintDC** [comment]
Is the development for this already started? And is it planned for the 6.1.3 or 6.1.4 release? This is a feature we really need urgently. If the development is not started yet by the primeng team, would you consider merging a pull request created by us?

**Comment by thomassanders** [comment]
Any news on this feature? I suppose this is not part of 7.1.0 yet?
Thanks for the update!

**Comment by moshmage** [comment]
version 8.x is out and 9.x snapshot exists, but this feat has been pushed into limbo? not even a knee-jerk acceptance of @SwintDC ? maaaan..

**Comment by c123dl** [comment]
no support yet? i hate to say if there is no support i will have to use something else,
but is seems like no proggress for overlay panel issues at all.

**Comment by CronGM** [comment]
This is a feature that paid clients are requesting and it's sadly being ignored. If it's not being developed internally at least they should accept open PRs from the community.

**Comment by JacobSiegle** [comment]
The project is open source so you can build it yourself for your own personal use. After drop in a PR and hope for the best. If they decline it you can always still share your fork with others here.

**Comment by basseur** [comment]
Still nothing?

**Comment by augustobreno** [comment]
Also waiting for this fix.... after more then 3 years.

**Comment by komaira** [comment]
Any update on this request?

**Comment by daniatic** [comment]
Any updates on this?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by Michael-Ziluck** [comment]
This was not completed and needs to be reopened @mertsincan

**Comment by Michael-Ziluck** [comment]
This issue was recreated as https://github.com/primefaces/primeng/issues/13025 for anyone looking for an open ticket. Anyone who reacted to this issue should re-react over there.

**Comment by StephenSPaul** [comment]
For anyone interested, I ended up using the angular-cdk library which has a highly extensible API for overlays. It is de-coupled from the material library.

`npm i @angular/cdk`

ts```
import { OverlayModule } from '@angular/cdk/overlay';

@NgModule({
  imports: [
    OverlayModule,
  ],
})
export class MyModule {}
```

```html
<p-button
  icon="pi pi-ellipsis-v"
  [outlined]="true"
  #trigger
  (click)="this.$show.set(true)"
></p-button>
<ng-template
    cdkConnectedOverlay
    [cdkConnectedOverlayOrigin]="trigger.el"
    [cdkConnectedOverlayOpen]="$show()"
    [cdkConnectedOverlayPositions]="[{ originX: 'start', originY: 'center', overlayX: 'end', overlayY: 'center', offsetX: -15 }]"
    [cdkConnectedOverlayHasBackdrop]="true"
    (backdropClick)="this.$showSubOverheadIndex.set(null)"
  >
  <div class="popup">
        ...
  </div>
</ng-template>
```

**Comment by bbt-dikshit** [comment]
Any updates on this?
