### ISSUE TITLE
Tree - DragDrop makes mistakes when dragging downwards in between other nodes

### ISSUE THREAD

**Issue by filipvh** [primefaces/primeng#2569]
[X] bug report => Search github for a similar issue or PR before submitting

**Current behavior**
During DropDrag, drop the 1st element between the 2nd en 3rd, and the element takes 3rd position.

**Expected behavior**
Should take 2nd place.
**Minimal reproduction of the problem with instructions**

1. Go to Tree on the PrimeNG demo page: https://www.primefaces.org/primeng/#/tree
2. Scroll down to DragDrop demo
3. Drag 'Documents' in between Pictures and Movies
4. See Documents get placed wrong...

**Comment by cagataycivici** [comment]
@Mrtcndkn Take over please, seems like the issue we had when doing dragdrop for orderlist.
