### ISSUE TITLE
p-dropdown doesn't work inside modal

### ISSUE THREAD

**Issue by Sky4CE** [primefaces/primeng#2575]
**I'm submitting a bug*  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
Inside a modal window (ng2-bootstrap-modal) p-dropdown(and some other components) has very strange behavior, if I choose value from the list it never opens second time, I have to close modal and open again to choose new value.

**Expected behavior**
It should just work.

**Minimal reproduction of the problem with instructions**
Create modal using ng2-bootstrap-modal lib, put p-dropdown into modal markup.

**What is the motivation / use case for changing the behavior?**
Need this to work.

**Please tell us about your environment:**

* **Angular version:** 4.03

* **PrimeNG version:** 4.0.0-rc.3

* **Browser:** all
 
* **Language:**  TypeScript 2.3

* **Node (for AoT issues):** `node --version` =  v7.8.0

**Comment by Sky4CE** [comment]
I found out that problem occurs only for mouse event, if I use keyboard to open dropdown and choose value it works fine any number of times, but as I explained above when I choose value with mouse click then I'm not able to open dropdown again using mouse click (but it still works with keyboard).
Any help ?

**Comment by Sky4CE** [comment]
That's a bug of ng2-bootstrap-modal  closeByClickingOutside = true setting.

**Comment by nasr18** [comment]
for me p-dropdown not opening in ng2-bootstrap-modal.
