### ISSUE TITLE
how to set my value as object in p-dropdown in primeng

### ISSUE THREAD

**Issue by binary2quantum** [primefaces/primeng#2577]
` <div class="form-group row" [ngClass]="{ 'has-error': templateForm.submitted && !OSinfo.valid }">
           
                <label class="col-md-offset-1 col-md-2 textLabelColor" for="OS">OS</label>
                <div class="col-md-7">
                    <select class="form-control textAreaColor" [(ngModel)]="template.operatingSystem" #OSinfo="ngModel" name="OS_name" required>
					<option *ngFor="let system of OPERATING_SYSTEMS" [ngValue]="system.id">
					     {{system.name}}-{{system.type}}-{{system.osVersion}}</option>
				</select>
               
                    <div *ngIf="templateForm.submitted && !OSinfo.valid" class="help-block">OS Requirement must be specified.</div>
                </div>
            </div>`

This is my dropdown in angular2 model-driven form. i wish to replace this with the p-dropdown. hereby i have changed the code and it works fine.

` <p-dropdown [options]="OPERATING_SYSTEMS" [(ngModel)]="template.operatingSystem" [style]="{'width':'250px','overflow':'visible'}" appendTo="body" filter="filter">
    <template let-car pTemplate="item">
        <div class="ui-helper-clearfix" >
            <div style="font-size:14px;float:left;margin-top:4px">{{car.label}}</div>
        </div>
    </template>
</p-dropdown>`

Now my problem is i wish to set an object instead of value. So don't know how to achieve it perfectly.
I need some help to fix it. Thanks in Advance!

**Comment by luchillo17** [comment]
First format your code, is painful to read.

Second, your selected item variable is named template?

**Comment by binary2quantum** [comment]
I have fixed it from my backend... thanks @luchillo17

**Comment by cagataycivici** [comment]
Please use forum for how-to like questions and support requests.

**Comment by subbiahkk** [comment]
@binary2quantum how did you fixed that, i am trying to set value in my TS, but its not working.

**Comment by ADefWebserver** [comment]
This works for me.

My markup:

<p-dropdown id="assignedRole"
                                [options]="rolesDropdown"
                                [(ngModel)]="paramAssignedRole"
                                [style]="{'text-align':'center','width':'100px'}"
                                styleClass="ui-column-filter"
                                appendTo="body"></p-dropdown>

My Code:

                    // Set AssignedRole
                    if (SearchTaskParameters.assignedRoleId !== undefined && SearchTaskParameters.assignedRoleId !== "") {
                        let intSelectedRoleId: number = Number(SearchTaskParameters.assignedRoleId);
                        // try to find it in the dropdown
                        let selectedRole = this.rolesDropdown.find(x => x.value.iD == intSelectedRoleId);
  
                        if (selectedRole !== undefined) {
                            this.paramAssignedRole = selectedRole.value;
                        }
                    }
