### ISSUE TITLE
[BUG] Can not find name treeNode

### ISSUE THREAD

**Issue by mcwebdev** [primefaces/primeng#258]
Error: "Can not find name treeNode"

This doesn't seem to be an exported class in the library.

Steps:
import {TreeTable} from 'primeng/primeng';
import {TreeNode} from 'primeng/primeng';

directives: [TreeTable, TreeNode]

**Comment by cagataycivici** [comment]
TreeNode is not a directive, it is an interface so you need to remove it from directives.
