### ISSUE TITLE
Drag items outside a tree into a tree

### ISSUE THREAD

**Issue by lehran87** [primefaces/primeng#2582]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Only items from other trees can be dragged into a tree.

**Expected behavior**
Items from DataTables or other sources can be dragged into the tree.

**What is the motivation / use case for changing the behavior?**
It's a comfortable method to manipulate/extend a tree with new items.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
