### ISSUE TITLE
Multiselect maxItems attribute

### ISSUE THREAD

**Issue by Mrtcndkn** [primefaces/primeng#2586]
maxItems attribute decides how many items to show in container.

**Comment by Mrtcndkn** [comment]
https://github.com/primefaces/primeng/commit/36f406d571d8f59771f14b59044115ae3d01c14c

**Comment by kgkern01** [comment]
Was this attribute added to the Angular 2 version as well, or just the Angular 4 version?

**Comment by GayathriMohan** [comment]
How to customize the maxSelectedLabels? @Mrtcndkn

**Comment by Mrtcndkn** [comment]
<p-multiSelect [options]="cars" [(ngModel)]="selectedCars" maxSelectedLabels="5"></p-multiSelect>

@GayathriMohan

**Comment by GayathriMohan** [comment]
Works fine, thankyou @Mrtcndkn

**Comment by Mrtcndkn** [comment]
Glad to hear that.

**Comment by TakanashiOuken** [comment]
Not working in Angular 2

**Comment by aelsrana** [comment]
I use this code Angular 2 not working
<p-multiSelect [options]="products" [(ngModel)]="selectedProduct" maxSelectedLabels="1"></p-multiSelect>

**Comment by Mrtcndkn** [comment]
What is your primeng version? @aelsrana

**Comment by aelsrana** [comment]
"primeng":4.0.0-rc.3

**Comment by rfmatos** [comment]
Same here, doesn't work for me.  I can keep selecting items and the label container keeps growing past three items.

Using Angular 4.0.2 and Primeng 4.1.2.

<p-multiSelect name="courses" [options]="courses" [(ngModel)]="selectedCourses" maxSelectedLabels="3"></p-multiSelect>

**Comment by Mrtcndkn** [comment]
Could you please create a plunkr about it because i can't replicate it with the latest version

Regards

**Comment by rfmatos** [comment]
I just a little while ago realized I was on the 4.0.0-rc.3 not the latest.  I just upgraded to 4.1.0 and it works fine for me now.

**Comment by aelsrana** [comment]
Its works fine after version update

**Comment by senthil9090** [comment]
<p-multiSelect [options]="cities" appendTo="body" [(ngModel)]="selectedCities"></p-multiSelect>
append to body has some design issues 
any body have the solution for this??

**Comment by Shivamsharma625** [comment]
maxSelectedLabels Not work in primeng: 2.0.5.what I do without update primeng. 
Give me Suggestion. Thank you...

**Comment by dontboyle** [comment]
Broken again in primeng 8.0.4 and angualr ^8.0.0

                                                          `<p-multiSelect [style]="{'width':'150px'}"
                                                            styleClass="form-control"                                                            
                                                            name="selectClassMultiselect"
                                                            [options]="contestantClassList"
                                                            [defaultLabel]="l('SelectClass')"
                                                            [(ngModel)]="selectedClassList" optionLabel="nickName"
                                                            [panelStyle]="{minWidth:'8em'}" [maxSelectedLabels]="3">
                                                            <ng-template let-selectedClasses pTemplate="selectedItems">
                                                                <span *ngFor="let selectedClass of selectedClasses">
                                                                    <i [class]="'fa fa-' + selectedClass.icon"
                                                                        [title]="selectedClass.nickName"></i>
                                                                    ,&nbsp;
                                                                </span>
                                                            </ng-template>
                                                            <ng-template let-class let-i="index" pTemplate="item">
                                                                <span>
                                                                    <i [class]="'fa fa-' + class.value.icon"> </i>
                                                                    {{class.value.nickName}}
                                                                    ({{class.value.name}})
                                                                </span>
                                                            </ng-template>
                                                        </p-multiSelect>`
