### ISSUE TITLE
Datatable column sorting fails when all values are identical

### ISSUE THREAD

**Issue by lebnic** [primefaces/primeng#2588]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://embed.plnkr.co/98X5UtL36FcJ9WyuNqcl/

**Current behavior**

When there are more than 10 entries in a datatable, and all values under a column are of the same value, sorting this columns exhibits some weird behavior. See plunker above for quick demonstration of this bug.

**Expected behavior**

Datatable sorting seems to be working fine when 10 or less rows in datatable. This is expected behaviour.

**Minimal reproduction of the problem with instructions**

See plunker, description are included there...

**What is the motivation / use case for changing the behavior?**

I am using Datatable to display data returned by an API and sometime, all values are identical. However, sorting is broken, as mentionned above...

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
This is due to browser differences as PrimeNG uses native sort.

https://stackoverflow.com/questions/3026281/array-sort-sorting-stability-in-different-browsers
