### ISSUE TITLE
Growl should support Message's with arbitrary timeouts

### ISSUE THREAD

**Issue by spyderz42** [primefaces/primeng#2590]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**What is the motivation / use case for changing the behavior?**
It would be nice if the growl component would support arbitrary message timeouts. Instead of setting the growl to sticky or setting a timeout on it. You could specify this message should be sticky (error, user needs to see it), but this next message should have a 3second timeout (your save was successful), and this other one needs to hang around longer and should be here for 10 seconds.

**Please tell us about your environment:**

* **Angular version:** 4.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** all

 
* **Language:** [TypeScript 2.1]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Growl is deprecated, please use Toast instead which supports this.
