### ISSUE TITLE
How To Make My Custom Changes in Our Own PrimeNg Component

### ISSUE THREAD

**Issue by sagares421** [primefaces/primeng#2593]
Hi PrimeNG,

How To Make My Custom Changes in Our Own PrimeNg Component. Lets say changing Pagination as per our requirement by adding our own arrows and text Or changing accordion icon to our icon.

Can you please come up with any best way.

Regards,
SAP Ariba Team.

**Comment by cagataycivici** [comment]
Please use your PRO support for question.
