### ISSUE TITLE
Use Https service for FileUpload

### ISSUE THREAD

**Issue by ova2** [primefaces/primeng#2594]
Angular provides mock API for HTTP backend. There are nice approaches how to use mocks for backendless development, e.g. http://jasonwatmore.com/post/2016/11/24/angular-2-mockbackend-example-for-backendless-development Saidly, but this doesn't work with FileUpload because FileUpload doesn't use Angular HTTP service. It doesn't delegate the upload functionality to a service too - the component communicates directly with XMLHttpRequest (separation of concens is broken). Therefore, we can not mock the backend for testing, demos, etc.

**Comment by ova2** [comment]
Just FYI. Http service supports `FormData`. Here is a gist: https://gist.github.com/Toxicable/1c736ed16c95bcdc7612e2c406b5ce0f I suggest to use the service, even your own one, so that we can always overwrite it with `providers`. This is useful for extensions, mocking, demos, etc.

**Comment by gasparbarancelli** [comment]
@cagataycivici has already been answered in issue #4945

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
