### ISSUE TITLE
p-column and template doesn't work

### ISSUE THREAD

**Issue by bababudha** [primefaces/primeng#2597]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[x ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/77OG7zX3LToGoidKaKOS

**Current behavior**

I am new to Angular and primeNG and  trying to present some items using p-dataTable. The items will be presented if I use ordinary <table> tags and *ngFor for parsing and presentation of objects. However when I move to <p-dataTable> and using binding value to these items and try to present them the template for the object which is a list of objects doesn't work. 
Anybody sees obvious miss/problem with the following? 
This is the part of .html code which shows the two different approaches with and without p-dataTable:
<div *ngIf="selectedChallenge">
        <div *ngIf="items">
          <table>
            <tr>
              <th>Deltagande lag</th>
              <th>LagMedlemmar</th>
            </tr>
              <tr *ngFor="let item of items">
                <td>{{item.team.name}}</td>
                <td>
                <span *ngFor="let user of item.users">
                    {{user.firstname}} {{user.lastname}};
                </span>
                </td>
              </tr>
          </table>
        </div>

        <p-dataTable #dt [value]="items" selectionMode="single" [(selection)]= "team"
                     [editable]="true" [contextMenu] = "cm" scrollable="true">
            <p-header>
              <div class="ui-helper-clearfix">
                Utmaning
                <button  type="button" pButton (click)="editChallenge()" label="Edit" ></button>
                <button  type="button" pButton (click)="deleteChallenge()" label="Radera" ></button>
                <button  type="button" pButton (click)="showDetails()" label="Visa pass" ></button>
              </div>
            </p-header>
            <p-column field="team.name" header="Deltagande Lag"></p-column>
          <p-column header="Lagmedlemmar">
            <template *ngFor="let user of users"  let-col let-data="rowData" pTemplate type="body">
              <span {{user.firstname}} {{user.lastname}}></span>
            </template>
          </p-column>
        </p-dataTable>

        <p-contextMenu #cm [model]="items"></p-contextMenu>

          

        </div>

**Expected behavior**

The first part of presentation with <table>, for test, shows the following:
Deltagande lag	LagMedlemmar
1. Ettan	Bosse xxx; Johan xxx; Daniel xxx; Staffan xxx
2. Tvåan	Micael xxx; Anna xxx; Staffan xxx; Stefan xxx; Lars xxx
3. Trean	Test Companyuser; Micael xxx
4. Fyran	Johan xxx; Christian xxx; Arvid xxx;
5 Feman	Stefan xxx; Lars xxx; Johan xxx;

When the second part shows only the first objects: (well formated with primeNG stuff in reality)
Deltagande Lag	Lagmedlemmar
1.Ettan	
2. Tvåan	
3. Trean	
4. Fyran	
5 Feman	

The items are build in TypeScript and definition of every item is accordingly:
export class TeamUsers {
  users: User[];
  team: Team;
}
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

macOS (Sierra), IntelliJIDEA, Nodejs, Angular2, and backend Java application running on Wildfly.

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Tested on Chrome and Safari 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

* **Node (for AoT issues):** `node --version` =

**Comment by Mrtcndkn** [comment]
Try with <ng-template> instead of <template>.

**Comment by bababudha** [comment]
Sorry but I don't get it Mrtcndkn. Would you be a little more specific please?

**Comment by Mrtcndkn** [comment]
Recently tempalte syntax changed the first thing i saw before doing anything is that you are using the old one.

This one is old one

    <template>

This one is new one

    <ng-template>

**Comment by bababudha** [comment]
Thanks, but as far as I know you can not use "let" with ng-template, that was the reason that I used template. I have similar template code in other places in application and only this one doesn't work. I  'll try to change the implementation and use ng-template instead even if I think I have other issues in this case which doesn't work.

**Comment by cagataycivici** [comment]
Please use forum for cases like these, you need to use ng-template with Angular 4 and PrimeNG 4.
