### ISSUE TITLE
how to display the nested object in datatable

### ISSUE THREAD

**Issue by binary2quantum** [primefaces/primeng#2598]
"content": [
    {
      "model": {
        "modelId": 36,
        "modelName": "simple",
        "creationDate": 1490621902000
      },
      "clDetails": [
        {
          "clModel": {
            "clId": 60,
            "clTemplateName": "simple"
          },
          "scModel": {
            "scId": "AZ5Wu-c9Ix7",
            "scName": "man"
          }
        }
      ],
      "slaModel": {
        "slaTypeId": 1,
        "slaTypeName": "SLA_TYPE"
      },
      "notifyModel": {
        "notifyId": 27,
        "notifyName": "0"
      }
    }]
This is my json data...  and i wish to display it in primeng datatable... i tried and i can display all except the clDetails. i have googled it but still didn't found the exact solution. so please give me some solutions to fixt it

Thanks in advance!

**Comment by cagataycivici** [comment]
Please use forum for questions.
