### ISSUE TITLE
TreeNode.selectable feature from RC merged to 2.0.6

### ISSUE THREAD

**Issue by meesstees** [primefaces/primeng#2599]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Is it possible to merge commit https://github.com/primefaces/primeng/commit/bb1792eac98c7beb9d18ff68bed99408ad650108 into 2.0.6 branch?

**Current behavior**
TreeNode.selectable is not handled by TreeNode in 2.0.6 as per current documentation

**Expected behavior**
TreeNode.selectable to be handled by TreeNode in 2.0.6 as 4.0.0-RC3 currently does

**What is the motivation / use case for changing the behavior?**
To have version 4.0.0 behaviour in 2.0.6 regarding TreeNode.selectable state

* **Angular version:** 2.4.10

* **PrimeNG version:** 2.0.6

* **Language:** [TypeScript]

* **Node (for AoT issues):** `node --version` =  6.9.4

**Comment by cagataycivici** [comment]
We don't support 2.0.x at the moment, please upgrade to 4.x.
