### ISSUE TITLE
update to beta.17

### ISSUE THREAD

**Issue by gdi2290** [primefaces/primeng#260]
splitbutton depends on router but the Location etc moved to angular2/platform/common
related https://github.com/AngularClass/angular2-webpack-starter/issues/541

**Comment by cagataycivici** [comment]
There is a big problem though;

https://github.com/angular/angular/issues/8275

**Comment by cagataycivici** [comment]
Ok, fixed the problem by the suggested workaround so we fully support beta16 now with PrimeNG beta4.
