### ISSUE TITLE
Feature Request: Datatable custom column filter match mode

### ISSUE THREAD

**Issue by giovstef75** [primefaces/primeng#2602]
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Datatable column filtering: give the possibility to implement a custom filter match mode (i.e. using wildcard characters). I'm not talking about a regex based filter (too difficult for the end user), but a way to let the developer choose is own filter rule (replacing the standard filter method?).

**Comment by cagataycivici** [comment]
Tracked at #2403
