### ISSUE TITLE
Dropdown autocomplete does not work on FF and Safari

### ISSUE THREAD

**Issue by cqzheng** [primefaces/primeng#2604]
Trying p-autocomplete and visit on mac. On mac, chrome works well but firefox and safari doesn't work. The list doesn't pop up.
Did some debug and found that this.focus is false on fire and safari but true for chrome. This causes that the show function isn't called correct.
AutoComplete.prototype.show = function () {
        if (!this.panelVisible && (**this.focus** || this.dropdownFocus)) {
            this.panelVisible = true;
            this.panel.style.zIndex = ++domhandler_1.DomHandler.zindex;
            this.domHandler.fadeIn(this.panel, 200);
        }
    };

[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Comment by cagataycivici** [comment]
Do you mean dropdown functionality right? When you type list shows up but not on dropdown.
