### ISSUE TITLE
Datatable + Selection, delete row on select?

### ISSUE THREAD

**Issue by fplini** [primefaces/primeng#2609]
[X ] bug report => Search github for a similar issue or PR before submitting

Hi all, I'm using datatable with selection mode "single" that shows records from list X. 
I also have an input text that on key up enter it adds a record to the list X.
When I select a row in the table and without do anything I add a new record, primeng deletes the selected row from the list before add the new record.

Someone knows if is this a bug?
* **Angular version:** ^4.0.1

* **PrimeNG version:** 4.0.0-rc.3

**Comment by sudheerj** [comment]
The issue is not very much clear.Do you mean the selected row is unselected after adding the new record.Can you please make step by step approach with simple example.

**Comment by fplini** [comment]
I verified just now, I'll close the issue. The problem was a function binded to a button in the form that was called on keyup enter.
