### ISSUE TITLE
[Bug] DataTable: With frozen and editable columns row do not align

### ISSUE THREAD

**Issue by bmstambaugh** [primefaces/primeng#2613]
****I'm submitting a ...**  (check one with "x")**
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already 
[ ] support request => Please do not submit support request here, instead see 

**Plunkr Case (Bug Reports)**
[http://plnkr.co/edit/gZGid81oodPX8RwRC4bm ](http://plnkr.co/edit/gZGid81oodPX8RwRC4bm)

**Current behavior**
When enabling both editable columns and frozen columns the rows do not align. The editable rows are larger than the non-editable frozen rows.

**Expected behavior**
Rows should be the same height and align

**Minimal reproduction of the problem with instructions**
Simply load this plnkr and you will see 
[http://plnkr.co/edit/gZGid81oodPX8RwRC4bm ](http://plnkr.co/edit/gZGid81oodPX8RwRC4bm )

**Please tell us about your environment:**
OS: Windows
IDE: MS Code

* **Angular version:** 4.0.X
* **PrimeNG version:** 4.0.X
* **Browser:** [all] 
* **Language:** [all]

**Comment by bmstambaugh** [comment]
It would appear all editable cells get a height set to 36px and the frozen non editable cells have a height of 28px by default.  By adding `td { height: 36px; }` to my css file I can fix the issue quite easily, but the desired effect should be that both frozen and unfrozen rows should all have the same height applied.

**Comment by cagataycivici** [comment]
This is expected, known workaround is adding a similar element that causes height increase on the other side and use visibility:hidden or manually add it. We rather not deal with row calculation, you have the content so better you manage it with two solutions above. It will slow things us to find the row with max-height and apply it to all, imagine a table with many rows, faster is if you handle it in your app.
