### ISSUE TITLE
touched class not set when touching p-editor

### ISSUE THREAD

**Issue by psaussure** [primefaces/primeng#2614]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Plunkr Case (Bug Reports)**
No need for PlunkR Case: just go on PrimeNG Demo page about editor (toolbar Editor):

https://www.primefaces.org/primeng/#/editor

**Current behavior**
Using the editor, you can see `dirty/pristine` state changes on `p-editor` element when you type something inside.

BUT `touhed/untouched` state doesn't change and remain untouched.

**Expected behavior**
We expect that going, and typing in the `p-editor` trigger a `touched/untouched` state change

**Minimal reproduction of the problem with instructions**
Just load the `<p-editor>` module. Go in the editor and type something: you will see `ng-untouched` class and state remains here and `ng-touched` is never triggered.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.0.2 (also tested on 4.0.1)

* **PrimeNG version:** 4.0.0-rc.3

* **Browser:** All I was able to test on (IE, Edge, Firefox last version, Chrome last version)
 
* **Language:** TS

**Comment by blackholegalaxy** [comment]
Confirmed. Same problem here

**Comment by sanjaykumarkatta** [comment]
I'm still facing the same issue. Can you help me out in resolving it

**Comment by gmaggio-ca** [comment]
This issue is still occuring. Any plan to fix it? @cagataycivici
