### ISSUE TITLE
p-dropdown crashes when placed on a div with ngIf (RC.4)

### ISSUE THREAD

**Issue by SchneMa** [primefaces/primeng#2619]
[ X] bug report => Search github for a similar issue or PR before submitting

**Plunkr Case (Bug Reports)**
_Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed._

http://plnkr.co/edit/xxneXT8LNq3AepsAHVjf?p=preview

**Current behavior**
_If a p-dropdown element is placed inside a div with ngIf on it and you show that div the dropdown crashes._ 

**Expected behavior**
dropdown should not crash when showing it in the div or in an other element

**Minimal reproduction of the problem with instructions**
_To reproduce it just go to the plunker and click the button. Look in the console and you will see that the error message._ 
"Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: '103'. Current value: '132'." 

* **PrimeNG version:** 2.0.X
_Primeng 4.0.0-rc.4_

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
_Tested in FF and Chrome_

After updating my Primeng version to the new rc4 my application crashes after showing a div with an ngIf selector. The div contains a p-dropdown element and you can see how it looks like or rather how it behave when the div is shown.

This is my first report so please tell me if anything is missing or if you need any further informations.

**Comment by upstreamosGH** [comment]
Same issue!...It breaks my application. I currently rollback to 4.0.0-rc.3.

**Comment by dags** [comment]
Same issue here too, going to rc.3 meanwhile ...

**Comment by SpiderPork** [comment]
Same issue with rc.4, reverting to rc.3 works.

**Comment by cagataycivici** [comment]
Try RC5 please.

**Comment by SpiderPork** [comment]
Now it works.
Thanks.

**Comment by SchneMa** [comment]
@cagataycivici thx for that fast fix!
works like out of the box 🎉
