### ISSUE TITLE
Add spinner / loading image into autocomplete component

### ISSUE THREAD

**Issue by ghost** [primefaces/primeng#2621]
Do you take in consideration the opportunity to add a spinner when user typing / searching something into auto complete component by asynchronous  request?

**Comment by cagataycivici** [comment]
Will do for 4.1.1.

**Comment by orsolli** [comment]
What happened?

**Comment by miked1090** [comment]
@cagataycivici Any update on this? The Autocomplete component can really use some love.

**Comment by Ketec** [comment]
Looking for an update as well. It is currently a bit confusing.
The user may type something,  but nothing shows up - and no indicator if it is doing something or not.
Something that would  show the spinner when the search is called after typing and hide it after completeMethod (or even better when list is ready to show - longer list may take a few seconds).

**Comment by mtuzinskiy** [comment]
@cagataycivici Any updates? That feels like a crucial feature for an autocomplete component

**Comment by khichar-anil** [comment]
@cagataycivici 
It's not there in [4.2.0](https://github.com/primefaces/primeng/releases/tag/4.2.0) release as well. When we can expect this. In our use case we have massive data that we load on demand, sometime on typing and we also put infinite scroll inside the dropdown and we need this feature desperately.

**Comment by Ketec** [comment]
@khichar-anil but it is, i'm using it. It was added in 4.2.0 RC1.

**Comment by smurugavel** [comment]
right now, we have a home grown Angular component that can use icons for loading or "record not found". After upgrading to primeng 4.3 from 4.1.1, I see a spinner which is a good option, but it doesn't work for us. Is there a way to disable primeng loading spinner from autocomplete?
or atleast allow to display a different icon for "record not found" status.

**Comment by Ketec** [comment]
Why not override the icon in css? The class is provided (my previous comment).
like` /deep/ .ui-autocomplete-loader::before {content: "\\f110" !important;}'`

**Comment by Darnoj** [comment]
Well, in version 4.3.0 I do not see the ui-autocomplete-loader in any file, how can this be possible ?

**Comment by Ketec** [comment]
https://github.com/primefaces/primeng/blob/4.3.0/src/app/components/autocomplete/autocomplete.css

**Comment by Darnoj** [comment]
@Ketec I have seen that it's present also on https://github.com/primefaces/primeng/blob/4.3.0/src/app/components/autocomplete/autocomplete.ts
I'am just wondering why when I do npm install prime@4.3.0 I can't find any ui-autocomplete-loader in any file :)

**Comment by Ketec** [comment]
I have 4.3.0 installed from npm and i can see it in primeng.css and autocomplete.js

**Comment by Darnoj** [comment]
@Ketec the fact is that the loader isn't displayed, may it be linked with ultima theme we are using ?

**Comment by Ketec** [comment]
@Darnoj  Theme should not affect the npm core. Isn't the ultima theme as a separate resource?

**Comment by Darnoj** [comment]
@Ketec I tried to upgrade ultima theme to 4.3.0 but the spinner is still missing.
I have the following when loading : <i class="ui-autocomplete-loader fa fa-circle-o-notch fa-spin fa-fw"></i>
In chrome debug tool I can see that the css class applied are .material-icons and .fa but it seems that the fa-spin and fa-circle-o-notch are unresolved.

**Comment by Ketec** [comment]
You likely don't have font awesome included in the project.

**Comment by Darnoj** [comment]
@Ketec But Ultima overrides fa to material, see : https://forum.primefaces.org/viewtopic.php?f=45&t=47794
Maybe it is a bug of ultima ?

**Comment by Ketec** [comment]
Don't have ultima so cant  say much about it - but if it's overriden, are all the specific classes for each element there too?
Perhaps it doesn't have fa-circle-o-notch in material and no custom class added for material override.

**Comment by Darnoj** [comment]
@Ketec exactly, the spinner should be also displayed on datatable
I searched in the Ultima support forum and found this :
https://forum.primefaces.org/viewtopic.php?f=45&t=50855

Thank you for your help !

**Comment by cagataycivici** [comment]
AutoComplete has a spinner since a couple of releases back.
