### ISSUE TITLE
OptionGroup support to MultiSelect

### ISSUE THREAD

**Issue by actra-gschuster** [primefaces/primeng#2622]
**I'm submitting a ...**  (check one with "x")
```
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
```

**Expected behavior**
It'd be great if the MultiSelect component had something similar to "optgroup", so one may select all "option" entries inside an "optgroup" by checking the "optgroup"s checkbox.
Use case may ba a business with several subsidiaries, each one with multiple offices where you want to select all offices of a subsidiary but only a few of another one.

**Please tell us about your environment:**
* **Angular version:** 4.0.3
* **PrimeNG version:** 4.0.0-rc.3

**Comment by cagataycivici** [comment]
Added to roadmap.

**Comment by shraddha13** [comment]
When do you expect you can support this functionality? Any release date as I have urgent requirement to implement right away.

**Comment by pierfreeman** [comment]
Yes, I'd like to know too if this feature has been added to any milestones

**Comment by sweetyv** [comment]
Hi, any update on this feature? I really need support for this in my project. Please help.

**Comment by pabitra1989** [comment]
Any update on this feature?

**Comment by uodriozola** [comment]
Any update on this feature? I need to create groups of elements like in the following example:
![example](https://user-images.githubusercontent.com/34504311/70921395-7b6eec80-2024-11ea-9fc6-678e40662ebd.png)

**Comment by nancycg** [comment]
Is there any solution provided for this functionality? Kindly reply if it exists now!

**Comment by andyblem** [comment]
> Any update on this feature? I need to create groups of elements like in the following example:
> ![example](https://user-images.githubusercontent.com/34504311/70921395-7b6eec80-2024-11ea-9fc6-678e40662ebd.png)

this feature will be very much useful, can you please add it.

**Comment by EmanuelleViana** [comment]
Any prevision?

**Comment by pedrobacchini** [comment]
Intermediate solution:

https://medium.com/@saurabhatgate/grouped-multi-select-with-primeng-113616df9981

Don't work reactive form and validation style

**Comment by RobertRajcool** [comment]
Any update on this feature?

**Comment by YanerTavuz** [comment]
Any update on this yet? 
Grouping works but I would really like to be able to select/deselect the group so that its children is selected/deselected.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
