### ISSUE TITLE
Clear selections if options are updated in multiselect

### ISSUE THREAD

**Issue by rigoparedes** [primefaces/primeng#2623]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

1.  Select some items (original options collection)
2. Update the options collection
3. Select other items (new options collection)

- I  It shows "null,null,MI_NEW_OPTION" for selected items

**Expected behavior**
The original selections should be removed after update the options collection

**Please tell us about your environment:**
Mac OSX, code

* **Angular version:**
4.0.2

* **PrimeNG version:**
^4.0.0-rc.1

* **Browser:** 
 Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by masoudline** [comment]
this problem exists still on version 4.2.1!
I used version 4.2.1

**Comment by roventur** [comment]
Ciao all, same issue with version 4.3.0

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
