### ISSUE TITLE
z-index of growl should be higher

### ISSUE THREAD

**Issue by huineng** [primefaces/primeng#2626]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
```
**Current behavior**
z-index of dialog is higher then z-index of growl messages

**Expected behavior**
growl is expected to provide warning messages to users, by such it should always have a higher index then a modal window (dialog) as otherwise the growl message will be displayed behind the dialg

latest 4 x of angular and prime

solution just add 100 in growl
https://github.com/primefaces/primeng/blob/master/components/dialog/dialog.ts#L144

```
// adding 100 makes growl higher then other dialogs and modals
this.container.style.zIndex = String(++DomHandler.zindex + 100);
```

**Comment by cagataycivici** [comment]
But z-index is always dynamic, an overlay of any type dropdown, dialog, growl always get the highest z-index. Solution could be;

```
.ui-growl {
   z-index:99999999999 !important;
}
```

**Comment by huineng** [comment]
ok got that, but that might be true if you have only one module, in my app modules communicate with each other via eg .. ngrx store for message exchange.
in that case the dialog get's 1000 and yes design elements ++ when i open it.

but if i then display the message, it's in fact another module that opens and that get's then the default of 1000 so lower

so it works in single modules, not in multiple 

the thinking was that if you add another 1000 or so on top of the default for growl , you don't have that chance 

of course ! important solves it, but what's then the point of using dom zindex for growl
maybe a default @input for z ?

**Comment by KeithGillette** [comment]
We're experiencing the behavior described by @huineng of growl notifications appearing behind modal dialogs in a project using multiple Angular modules and pub/sub, even in releases after the 4.1.1 milestone tagged by  @cagataycivici . Is changing this behavior this still a planned enhancement? Thanks!

**Comment by bkyuchuk** [comment]
\sdg

**Comment by cagataycivici** [comment]
There is baseZIndex property in recent releases.
