### ISSUE TITLE
Select filter input attributes in data table

### ISSUE THREAD

**Issue by Sergeon** [primefaces/primeng#2629]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

When creating a filter in a datatable, would be handy to have a `[filterType]` property or something that drives the type of the input generated, so we can set the filter as `number`, `date` or other types.

Would be cool also to have a set of proxy properties to add restrictions to the inputs, like `maxlength` etc, like `[filterConstraintMaxlength]` or any similar syntax.

**Comment by cagataycivici** [comment]
Better would be using a custom filter with your own input, you'll have more flexibility in this case. If we'll receive more requests for this, we'll reopen.

**Comment by cagataycivici** [comment]
But we'll add filterType to begin with.
