### ISSUE TITLE
Add scrollbar on scrollable datatable with no records  ----PrimeNG version 4.0

### ISSUE THREAD

**Issue by high-speed** [primefaces/primeng#2631]
Add scrollbar on scrollable datatable with no records 
 same 
PrimeNG version:4.0;
Angular :4.0
![Uploading `QQ图片20170502093826.jpg…]()`

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
