### ISSUE TITLE
[Data-Table] Unselect action does not work in single selection mode

### ISSUE THREAD

**Issue by lechu1985** [primefaces/primeng#2636]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When grid is in single slection upon clicking for the second time, row is not unselected. 

**Expected behavior**
According to the docs rows should be selected/unselected upon clicks

**Minimal reproduction of the problem with instructions**

See plnkr:
http://plnkr.co/edit/4KX3QMz59ygNsfffKkzi

Second click on the same row should trigger an alert.

**What is the motivation / use case for changing the behavior?**
Unselecting works only when 'special' key is held -> like ctrl. 
But this is highly unintuitive if I am expected to have single selection.

**Please tell us about your environment:**
Windows, Chrome

* **Angular version:** 4.0.1

* **PrimeNG version:** 4.0.0-rc.5

**Comment by sudheerj** [comment]
By default the unselection works by pressing metaKey.This can be changed by setting metaKeySelection="false".So either you should use metaKey or set metaKeySelection="false" in your case.

Please reopen if the issue is still need to be fixed.I will open another issue to update the docs as needed.

**Comment by lechu1985** [comment]
Ufortunatly setting `metaKeySelection="false"` did not solve the problem. This property does not seem to have any impact on the behaviour of the table. 

See updated plnkr:
http://plnkr.co/edit/4KX3QMz59ygNsfffKkzi

**Comment by lechu1985** [comment]
It works fine now, thanks.
Updated the plnkr with your response.

**Comment by DmitryEfimenko** [comment]
The information about `[metaKeySelection]="false"` should be in the documentation

**Comment by sudheerj** [comment]
The attribute is mentioned in the attributes documentation section.

**Comment by DmitryEfimenko** [comment]
right, except when one works on a selection feature he goes to the appropriate [docs page](https://www.primefaces.org/primeng/#/datatable/selection), where there is no mention of it. Not trying to give a hard time. Just explaining why I didn't find it the first time. Other developers might have a similar issue.
