### ISSUE TITLE
p-autoComplete: drop down button padding still present if button not displayed

### ISSUE THREAD

**Issue by cghislai** [primefaces/primeng#264]
Using p-autoComplete without the dropdown button, padding is still present to make room for it. The cursor is also set to pointer over it.

**Comment by cagataycivici** [comment]
Can you please clarify, I don't see it;

<img width="502" alt="screen shot 2016-04-27 at 09 57 28" src="https://cloud.githubusercontent.com/assets/686247/14844226/861522ea-0c5e-11e6-9cf7-f1822abe46b8.png">

The one with dropdown has ui-autocomplete-dd at container span that adds padding for room for button. Autocomplete without dropdown, doesn't have this in my tests.

**Comment by cghislai** [comment]
Sorry, this was a workaround for a previous version issue in my own css :/
