### ISSUE TITLE
Tree Propagation cannot be turned off

### ISSUE THREAD

**Issue by yogesh2singh** [primefaces/primeng#2640]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/dWh4IJoFdiNDdQVMJwSE

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   

Angular Version - 2.4.7
PrimeNG version - 2.0.5

<p-tree [value]="data" selectionMode="checkbox" [(selection)]="selectedItem"
        [propagateSelectionUp]="false" [propagateSelectionDown]="false"(onNodeSelect)="nodeSelect($event)"></p-tree>

I want to stop propagation but it's not working.

**Comment by mlaffargue** [comment]
Anything new on this ? 

I would like to have checkboxes in the tree, each level has the same object type and row selection shouldn't be propagated.

Similar to #7387

**Comment by jone30rw** [comment]
I came up with this solution for this problem:
https://github.com/primefaces/primeng/issues/7387#issuecomment-517847810

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
