### ISSUE TITLE
Custom Paginator

### ISSUE THREAD

**Issue by lonyel** [primefaces/primeng#2645]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/dWh4IJoFdiNDdQVMJwSE

**Current behavior**
Now,the datatable's paginator can't customize. And we need  cusomize it.

**Expected behavior**
At datatable.ts line 418:
`
<p-paginator [rows]="rows" [first]="first" [totalRecords]="totalRecords" [pageLinkSize]="pageLinks" styleClass="ui-paginator-bottom"
                (onPageChange)="paginate($event)" [rowsPerPageOptions]="rowsPerPageOptions" *ngIf="paginator && paginatorPosition!='bottom' || paginatorPosition =='both'"></p-paginator>
 `
  and line 448:
`
 <p-paginator [rows]="rows" [first]="first" [totalRecords]="totalRecords" [pageLinkSize]="pageLinks" styleClass="ui-paginator-bottom"
                (onPageChange)="paginate($event)" [rowsPerPageOptions]="rowsPerPageOptions" *ngIf="paginator && paginatorPosition!='top' || paginatorPosition =='both'"></p-paginator>
 `

If change "paginatorPosition!='bottom'" to paginatorPosition=='top'  and paginatorPosition!='top' to
paginatorPosition=='bottom',now we can set paginatorPosition to 'none' to hide paginator and add ourself's 'paginator'.

Please?

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by sudheerj** [comment]
The paginatorPosition should respect only three values "top","bottom" and "both"

https://github.com/primefaces/primeng/pull/2957

**Comment by sudheerj** [comment]
The new PR  is available here https://github.com/primefaces/primeng/pull/3087

**Comment by rogueRabbit** [comment]
hi ,do you know How about default setting to last page?

**Comment by sudheerj** [comment]
There is first property to control the pagination.

**Comment by cagataycivici** [comment]
Yes, paginatorPosition can be used.

**Comment by Klinton90** [comment]
I would like to reopen that ticket.

First of all, current code is ambiguous:
`paginatorPosition!='bottom' || paginatorPosition =='both'"`
If value is `bottom` - top paginator is hidden, if anything else (`none`, `Bottom`, `tOp`) - it is shown. I just want to say that second condition can be removed and logic stays same.

I still need to enable pagination, but having custom paginator without turning table to `lazy` mode. Currently that is NOT possible. All pagination parameters set to dataTable are ignored, until `[paginator]=true` is set. But now there is NO way to hide built-in paginators.

One more request: it would be nice to have same parameter names for `paginator` (`pageLinkSize`) and `dataTable` (`pageLinks`).

**Comment by sabithpocker** [comment]
I have another scenario where I need two tables to be controlled by single paginator. I tried using a custom paginator for each table, but it dissent work without `paginator=true`. setting `paginator=true` brings in three paginators!

Currently is there any other way to connect a paginator to multiple datatables that are lazy loaded?

**Comment by jotapsl** [comment]
@sabithpocker Maybe use the standalone paginator component and hide the datatable's paginators. Then you could handle it manually.

**Comment by Klinton90** [comment]
I think initial problem (feature to hide paginator) is fixed. Thanks to primeNg team.  **PLEASE CLOSE THIS TICKET**

@sabithpocker if your tables are lazyloaded, then you have to handle pagination event manually. I.e. set `paginator="false`, add custom paginator to page:

```
            <p-paginator
                    styleClass="at-paginator-sm"
                    [totalRecords]="dataTable.totalRecords"
                    [first]="dataTable.first"
                    [rows]="dataTable.rows"
                    [pageLinkSize]="dataTable.pageLinks"
                    [rowsPerPageOptions]="dataTable.rowsPerPageOptions"
                    (onPageChange)="paginateAction($event)"
            ></p-paginator>
```

and refresh both tables such as:
```
    onPageChange($event: PaginationEventModel){
        this.table1Api.get($event).subscribe((result) => {
            this.table1Data = result;
        });
    this.table2Api.get($event).subscribe((result) => {
            this.table2Data = result;
        });
    }
```

**Comment by gmengi** [comment]
Hello  @Klinton90 i have 3 tables controlled by single paginator. Facing difficulties to integrate it. Its impacting to 1st table only.

Can you please help me out on this. Advance Thanks.
