### ISSUE TITLE
Autocomplete gives error if suggestions are initialized on load 

### ISSUE THREAD

**Issue by huineng** [primefaces/primeng#2647]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
```

**Current behavior**
When suggestions are **pre filled** then an error is thrown 
$exception (handle error) => TypeError: Cannot read property 'nativeElement' of undefined

prime 4 RC 05 

the error happened with your commit for getters and setters
https://github.com/primefaces/primeng/commit/8d122cbcaa8745e9870e06c1e6d46030c52b3fd6#diff-c142e5a063843c13d7063bd3e5f62620

the error happens on this line 
https://github.com/primefaces/primeng/blob/8d122cbcaa8745e9870e06c1e6d46030c52b3fd6/components/autocomplete/autocomplete.ts#L305

the reason is a timing issue

<input *ngIf="!multiple" #in type="text"
relates to 
@ViewChild('in') inputEL: ElementRef;

but because of the ngIf ,this "inputEL"  is only available AFTER the setting of the suggestions 
inputEl is not defined and error is thrown

You will not see this in your examples and demo pages as their the suggestions are only loaded via the function and you kick off with empty array

**Comment by khichar-anil** [comment]
Thank you @huineng. You saved my day. I managed to get rid of this error by leaving suggestions undefined on init and get them on demand.

**Error Code:**
`questions: Question[] = [new Question()]; // this is my suggestions object`

**Working Code:**
`questions: Question[] = [new Question()]; // this is my suggestions object`
 
I am getting this error even in `prime 4 RC 03`.
