### ISSUE TITLE
Growl doesn't remove messages automatically

### ISSUE THREAD

**Issue by rikup88** [primefaces/primeng#265]
Forum thread with code samples and details: [http://forum.primefaces.org/viewtopic.php?f=35&t=45141&sid=0ec697f6a7491c66b1d26ef75abd11e6](url)
Library versions:
PrimeNG 1.0.0-beta3
Angular2 beta15
Firefox 45
PrimeUI ^4.1.7
SystemJS 0.19.25

**Comment by cagataycivici** [comment]
Fixed via;

https://github.com/primefaces/primeng/issues/275

**Comment by brian428** [comment]
Is this actually fixed? The demo page (http://www.primefaces.org/primeng/#/growl) doesn't appear to set sticky=true, but the growls are still not automatically removed.

**Comment by cagataycivici** [comment]
Our bad, the demo source and the actual code doesn't match, actual code has sticky enabled. Fixed in code now and will be live soon in redeploy. Thank you.

**Comment by masagatech** [comment]
[immutable]= "false"

**Comment by vivekreddy** [comment]
[immutable]= "false"
<p-growl [immutable]= "false" life="3000" [(value)]="messagestack">

This worked for me too. Thanks @masagatech
