### ISSUE TITLE
In datatable-Scrollable mode,exists TWO hori-scrollbar AND footer panel is crash

### ISSUE THREAD

**Issue by lonyel** [primefaces/primeng#2650]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
![npz_ ffwo6 n 3uny1xgow](https://cloud.githubusercontent.com/assets/5528229/25562869/2eab79f0-2dc3-11e7-843e-d8812eacceb7.png)
![gp sq71z 74z vy_dfd6fa3](https://cloud.githubusercontent.com/assets/5528229/25562883/5d205300-2dc3-11e7-81a4-3d917d80be58.png)

**Plunkr Case (Bug Reports)**

**Current behavior**
In datatable-Scrollable mode,exists TWO hori-scrollbar AND footer panel is crash

**Expected behavior**

**Minimal reproduction of the problem with instructions**
In datatable, set scrollable=true, columns width greate container'width,then TWO hori-scrollbar displayed! and sum-footer is crashed.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.0.X

* **PrimeNG version:** 4.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   [7]

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
