### ISSUE TITLE
Dropdown selected value not working properly if Editable is set

### ISSUE THREAD

**Issue by DarioN1** [primefaces/primeng#2652]
I have an Angular2 application with PrimeNG suite installed.

I'm trying to implement a form with a primeNG dropdown component.

The problem happens when I run the application and I select an element from the listbox.

Instead of shows the value, it shows **[object Object]**.

This happens only if I se **editable="editable"** attribute, without it it works...

This is the code:

`<p-dropdown [options]="listCustomers_itm" placeholder="Selezionare" formControlName="Customer_itm" [(ngModel)]="Customer_itm" filter="filter" editable="editable"> </p-dropdown>`

ts file:

```
this.mdService.Get_Customer(false).subscribe(
      data => {
        this.listCustomers = data;

        this.listCustomers_itm = [];
        for (let c of this.listCustomers) {
          this.listCustomers_itm.push({ label: (c.code + ' - ' + c.businessName), value: { id: c.idCustomer, name: c.businessName, code: c.code } });
        }
      }
    );
```

If I use flat value like this, it works:

`this.listCustomers_itm.push({ label: c.code, value:c.businessName });`

Thanks to support

I have also a stackoverflow question open for this:

http://stackoverflow.com/questions/43694692/angular2-primeng-dropdown-selected-value-not-working-properly-if-editable-is

**Comment by mickeyjohn** [comment]
Hi,
I have the same problem with p-dropdown when using editable with either value "true" or "false". It only works if editable attribute is not present. Please any one know how to properly use the dropdown properly with or it might need a fix? 

Thanks a lot in advance.

**Comment by alexandremoore** [comment]
@mickeyjohn try to bind the "editable" attribute to an actual boolean property of your ts class.

**Comment by mickeyjohn** [comment]
Thanks @alexandremoore. The problem will happen either with a boolean variable or boolean values. You can try with custom value objects like:
```
export class MyModel {
    cities: SelectItem[];
    selectedCity: string;
    constructor() {
        this.cities = [];
        this.cities.push({label:'Select City', value:null});
        this.cities.push({label:'New York', value:{id:1, name: 'New York', code: 'NY'}});
        this.cities.push({label:'Rome', value:{id:2, name: 'Rome', code: 'RM'}});
        this.cities.push({label:'London', value:{id:3, name: 'London', code: 'LDN'}});
        this.cities.push({label:'Istanbul', value:{id:4, name: 'Istanbul', code: 'IST'}});
        this.cities.push({label:'Paris', value:{id:5, name: 'Paris', code: 'PRS'}});
    }
}
```
described in PrimeNG documentation: https://www.primefaces.org/primeng/#/dropdown

**Comment by DarioN1** [comment]
That is what I have implemented... It solved my problem!

**Comment by mickeyjohn** [comment]
@DarioN1. Glad to here that but what problem does it solve?

**Comment by DarioN1** [comment]
The problem that the user can't clear the selection...
Actually is a workaround...

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview

**Comment by Jesu26** [comment]
@DarioN1 - Please can you explain how you did you solve the problem or any samples for this.

i am facing the exactly mentioned one

HTML:
<p-dropdown [options]="cities" [(ngModel)]="selectedCar" [editable]="editable" placeholder="Select a Brand"></p-dropdown>

TS:
 editable: boolean;
this.editable = true;

Result:
Binded value in dropdown - [object Object].

**Comment by skormel** [comment]
I am having the same  issue,

here is a plunkr, with the issue replicated

http://plnkr.co/edit/Cs35FB?p=preview

Best Regards
Antonio

**Comment by wurst44** [comment]
Version 5.0.2: 

- When the "editable" attribute is NOT set on **p-dropdown** then DD is not editable. (default = false = good)
But now my NgModel values to preset the DD are beeing ignored. 
**[(ngModel)]="test" // test: string = 'Bogen';**
- When I do set the "editable" attribute it ignores its true/false values and sets it always to editable.
But now my NgModel values are set correctly in DD.  :(

Is that wired?

**Comment by wurst44** [comment]
For anybody that has the same issue, I tried to fix it and it worked for me.
It does not fix the "editable" issue, I do set the "editable" attribute to false, but it is still editable.
(I dont care at this moment)
This very untested, without warranty of any kind!
It now uses a value/lable pair as source for DD: 
```
p-dropdown [(ngModel)]="selectedTreeTableItems.formteil"
formteile: object[] = [
    { value: '0', label: 'Fish' },
    { value: '1', label: 'Salat' }
}
```
Changes in **primeng\components\dropdown\dropdown.js**

```
Dropdown.prototype.selectItem = function (event, option) {
        if (this.selectedOption != option) {
            this.selectedOption = option;
            -- this.value = option.value;
            -- this.onModelChange(this.value);
            ++ this.onModelChange(option);
            this.updateEditableLabel();
            this.onChange.emit({
                originalEvent: event,
                -- value: this.value
                ++ value: option.value
            });
        }
    };

...

Dropdown.prototype.writeValue = function (value) {
      ++ if(value){
        if (this.filter) {
            this.resetFilter();
        }
        -- this.value = value;
        -- this.updateSelectedOption(value);
        ++ this.value = value.value;
        ++ this.updateSelectedOption(this.value);
        this.updateEditableLabel();
        this.updateFilledState();
        this.cd.markForCheck();
      ++ }
    };

...

-- if (this.autoDisplayFirst && !this.placeholder && !this.selectedOption && this.optionsToDisplay && this.optionsToDisplay.length && !this.editable) {

++ if (this.autoDisplayFirst && !this.placeholder && !this.selectedOption && this.optionsToDisplay && this.optionsToDisplay.length) {
```
