### ISSUE TITLE
DataTable radioButton unselection

### ISSUE THREAD

**Issue by sudheerj** [primefaces/primeng#2653]
It is good to have unselection behaviour for radio button selection mode.This is available for single and multiple selections using meta Key and metaKeySelection properties.

**Comment by cagataycivici** [comment]
Not sure Sudheer, if more users demand it, will reconsider. Thank you.

**Comment by f-teixeira** [comment]
+1

**Comment by rrrbsd** [comment]
when selection is an object reference the condition: if (this.selection != rowData) is always true,  and the else clause doesn't fire also when clicking to unselect a row
