### ISSUE TITLE
Selection propagation for TreeTable

### ISSUE THREAD

**Issue by sudheerj** [primefaces/primeng#2654]
As of now there is no control on propagateSelection in either up or down side.It is good to have propagateSelectionUp and propagateSelectionDown controls similar to tree component.

**Comment by cagataycivici** [comment]
TreeTable will be reimplemented, please monitor;

#4813

**Comment by MdShahrukh** [comment]
How can I set a node from the component file(programmatically) as it was working in primeng 4.0 and also how can I delete an itme from table
Please provide support here.
