### ISSUE TITLE
Error in creating events in Week or Day view in ScheduleModule

### ISSUE THREAD

**Issue by harishmagnate** [primefaces/primeng#2656]
While trying to create events in Day or Week view using primeng scheduler 

ERROR Error: Uncaught (in promise): Extra/unparsed characters found in date: T05:30:00
    at resolvePromise (zone.js:712) [angular]
    at :4200/vendor.bundle.js:145978:17 [angular]

Able to re-produce this even in the demo app located at https://www.primefaces.org/primeng/#/schedule 

Has anyone solved this issue? Tried setting time format also on <p-calendar> no luck.

**Comment by sudheerj** [comment]
I can able to replicate the issue.The same issue occurs on PrimeFaces calendar example too.This might issue with external dependencies too.

https://github.com/primefaces/primefaces/issues/1610

**Comment by antoinel12** [comment]
Use
```
this.event.start = event.date.toDate();
```
instead of
```
this.event.start = event.start.format();
```
p-calendar is expecting a Date, not a String.

There is a mistake in the example or there have been a breaking change since the example has been written...

**Comment by sudheerj** [comment]
Okay. Let me check with the example of both calendar and schedule.

**Comment by cagataycivici** [comment]
Glad to hear! @Mrtcndkn Please check the Schedule examples to see if there is any mismatch between actual code and source display.

**Comment by bhaidar** [comment]
@cagataycivici 
I am facing the same issue even with the examples on the Primeng schedule page.

https://www.primefaces.org/primeng/#/schedule

Open Week view, click anywhere to create a new event, make sure developer tools is open and notice the exception:

````
ERROR Error: Uncaught (in promise): Extra/unparsed characters found in date: T07:30:00
````

Thanks

**Comment by bhaidar** [comment]
@cagataycivici I've noticed this exception thrown when clicking any Event that is non-all Day event.
