### ISSUE TITLE
PrimeNG 4.0.0 DataTable filter() don't work properly

### ISSUE THREAD

**Issue by Danieleeee** [primefaces/primeng#2657]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Minimal reproduction of the problem with instructions**

Hi,
I have a DataTable with LazyMode active:
`[lazy]="true" (onLazyLoad)="loadLazy($event)"`

if I set two filters:
`this.dt.filter(fiels1, column1, mode);`
`this.dt.filter(fiels2, column2, mode);`

it sets only the first filter.
If there are filters already in the table, they are ignored.

* **Angular version:** 4.1.0

* **PrimeNG version:** 4.0.0-RC5

**Comment by Danieleeee** [comment]
still in PrimeNG-4.0.0

**Comment by Danieleeee** [comment]
![filtri](https://cloud.githubusercontent.com/assets/22749175/25670917/8a1e8a30-302e-11e7-9b57-965c7b78cf98.gif)

**Comment by Danieleeee** [comment]
@cagataycivici 
News?

**Comment by cagataycivici** [comment]
Review for 4.0.1

**Comment by Danieleeee** [comment]
Thanks

**Comment by cagataycivici** [comment]
I'm unable to replicate, please provide a plunkr that replicates the issue and we'll reopen.
