### ISSUE TITLE
Datatables UI messed up after updating to beta 3

### ISSUE THREAD

**Issue by rizwanhussain-vteams** [primefaces/primeng#266]
I recently updated to beta 3 and found my datatables theme messed up. It has some classes missing in the generated markup. I made sure the markup matches that of demo site. Here are the specifics.

Angular 2 : beta.16
Primeng : beta.3   
Primeui : 4.1.8

I have included following files in the index file:

`<link rel="stylesheet" href="node_modules/primeui/themes/south-street/theme.css">`
`<link rel="stylesheet" href="node_modules/primeui/primeui-ng-all.min.css">`
`<script src="node_modules/primeui/primeui-ng-all.min.js"></script>`

I wanted to paste in the markup as well but the editor was causing issues. I think i am missing something in the includes or maybe the docs are not updated to reflect the latest changes in markup?

Also, with beta 16 of Angular, we also need a minor reference change as indicated in this error:

`node_modules/primeng/components/splitbutton/splitbutton.d.ts(4,18): error TS2305: Module '"node_modules/angular2/router"' has no exported member 'Location'`    

The `Location` module now resides in `angular2/platform/common`. 

**Update**

I have also noticed that the generated datatable does not have any `ui-widget` and `ui-datatable` classes. If i add those it seems to get better but the `paginator` is also missing some classes.

**Comment by cagataycivici** [comment]
This is due to a breaking change in beta 16;

https://github.com/angular/angular/issues/8275

So you need to use angular 2 beta 15 with primeng 1.0 beta3.

primeng 1.0 beta4. will support beta 16;

https://github.com/primefaces/primeng/issues/260
