### ISSUE TITLE
data-table rows are not correctly updated due to value changes

### ISSUE THREAD

**Issue by bmazaheri** [primefaces/primeng#2660]
**I'm submitting a ...** 
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case**
http://plnkr.co/edit/DWGysweBALCFp7QNyvx3

**Current behavior**
data table will not be updated when rows are changed during component life cycle.
An example is in the plunkr, but I could not realize the exact situation.

**Expected behavior**
data should be updated whenever value is changed

* **Angular version:** 4.0.0

* **PrimeNG version:** 4.0.0

* **Browser:** [all ]

 
* **Language:** [TypeScript 2.3.2]

**Comment by damonwildercarr** [comment]
You need to reset the companies2 variable whenever the data changes. Change detection no longer happens when an array is modified so push on an array will do nothing. This was done for performance reason and is by design as far as I know.

**Comment by bmazaheri** [comment]
Thank you @damonwildercarr , I found description in the [release notes](https://www.primefaces.org/primeng-4-0-0-rc4-released/).
It is definitely better performance wise, although it makes developer to write more code and have more considerations.

**Comment by sudheerj** [comment]
As mentioned before, this is as per design to improve the performance.
