### ISSUE TITLE
Datatable filter not working correctly

### ISSUE THREAD

**Issue by unaor** [primefaces/primeng#2662]
I have a strange behaviour, im trying to implement filtering that is triggered by an outside event (a graph click that triggers an event)

graph is in one component and its emmiting an event that is captured in the table component

```
this.stationService.upDownGraphEvent.subscribe(upDownEvent => {
        this.dt.filter('192.168.99', 'stationIp', 'startsWith');
 });
```
this view is not updated even though im seeing that the datatable object as a new filtered array of the data

for testing purposes i placed a button on the component that upon clicks triggers the same filter

```
test(){
      this.dt.filter('192.168.99', 'stationIp', 'startsWith');
 }
```

this is working, why is first code is not working?

**Comment by unaor** [comment]
i want to add additional info, this is happening when my service navigates to the table url, let me clarify
on one url, i have some graphs when i click on one of the graphs, the shared service first navigates to another url, where the table is rendered and then i apply the code mentioned above, and this is not working.....

**Comment by cagataycivici** [comment]
Unable to replicate with latest PrimeNG, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
