### ISSUE TITLE
Issue with scrolling page with p-gmap on touch screen

### ISSUE THREAD

**Issue by okachynskyy** [primefaces/primeng#2664]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
You can simply open a p-gmap example from documentations
https://www.primefaces.org/primeng/#/gmap

**Current behavior**
p-gmap fires 'onMapClick' event during page scrolling from map area on mobile phone with touch screen.

**Expected behavior**
p-gmap should not fire event during scrolling

**Minimal reproduction of the problem with instructions**
1) Navigate to https://www.primefaces.org/primeng/#/gmap on mobile device with touch screen
2) Touch a screen on map area and swipe down
3) You must see a dialog for adding a new point. But I think you should not see this dialog because you has simply scrolled the page down.

**What is the motivation / use case for changing the behavior?**
Changing this behavior will be useful for mobile users.

**Please tell us about your environment:**
Safari on Iphone 5s, iOs 10.3.1

* **Angular version:** 4.0.2

* **PrimeNG version:** 4.0.0

* **Browser:** [ iOS 10.3.1 Safari  ]

 
* **Language:** [TypeScript 2.2.2]

* **Node (for AoT issues):** `node --version` =   v6.10.2

**Comment by cagataycivici** [comment]
I think this is related to gmap api, we just bind the click event of gmap;

```
this.map.addListener('click', (event) => {
            this.zone.run(() => {
                this.onMapClick.emit(event);
            });
        });
```

So not sure what we can do.
