### ISSUE TITLE
New resetOnSort method to DataTable

### ISSUE THREAD

**Issue by tamasfoldi** [primefaces/primeng#2667]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/Q4AFbxbjfhvmdmKwvP5T

**Current behavior**
Datatable sets paginator to 0 when value changes in singleSort mode. It is because it calls the singleSort method which sets the `first` property to 0 https://github.com/primefaces/primeng/blob/master/components/datatable/datatable.ts#L1009 . 

**Expected behavior**
It should not resets the paginator on value change

**Minimal reproduction of the problem with instructions**
Change the value of a datatable on the 2nd page. 
See: http://plnkr.co/edit/Q4AFbxbjfhvmdmKwvP5T

**What is the motivation / use case for changing the behavior?**
I'm using redux, so I changing the datatable value when I'm deleting a row, and it resets the paginator and I dont want to be on the first page when deleting a single row.

* **Angular version:** 4.1.0

* **PrimeNG version:** 4.0.0

* **Browser:** all
 
* **Language:** all

**Comment by tallkid24** [comment]
I'm having the same issue as well. We may get minor updates on the objects that are being displayed and want to update the array, but the paginator resets. I thought the rowTrackBy would fix it in 4.0.1 but that doesn't seem to have any affect.

**Comment by cagataycivici** [comment]
Let's introduce a property like resetOnSort="true|false" for this.

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
