### ISSUE TITLE
primeNg shorthand

### ISSUE THREAD

**Issue by fiorenzino** [primefaces/primeng#267]
Should be really usefull a primeNg shorthand like FORM_DIRECTIVES, CORE_DIRECTIVES? 
@Component({
selector: 'my-app',
directives: [PRIMENG_DIRECTIVES]
 * })

Something like:

import {Type} from 'angular2/src/facade/lang';
export {
    AutoComplete,
    Button,
    Calendar,
    Checkbox,
    Column,
    Footer,
    DataTable,
    Dropdown,
    Header,
    InputSwitch,
    InputText,
    PickList
.....

} from "primeng/primeng";

export declare const PRIMENG_DIRECTIVES:Type[];
}

**Comment by cagataycivici** [comment]
Great idea, could you please provide a pull request as an example for us? Should we add this to primeng.ts at root folder?

**Comment by fiorenzino** [comment]
In my code, this is a simple class (named: primeng-directives.ts) like below.
But in the angular 2 source code, they use a different code: 
eg FORM_DIRECTIVES in directives.d.ts, the array of directives is dynamically filled with class names
using something like "export declare const FORM_DIRECTIVES: Type[];"

####### - primeng-directives.ts - ##
import {
    Accordion,
    AccordionTab,
    AutoComplete,
    BarChart,
    Breadcrumb,
    Button,
    Calendar,
    Carousel,
    Checkbox,
    CodeHighlighter,
    Column,
    ContextMenu,
    DataGrid,
    DataList,
    DataScroller,
    DataTable,
    Dialog,
    DoughnutChart,
    Draggable,
    Dropdown,
    Droppable,
    Editor,
    Fieldset,
    Footer,
    Galleria,
    GMap,
    Growl,
    Header,
    InputSwitch,
    InputText,
    InputTextarea,
    Lightbox,
    LineChart,
    Listbox,
    MegaMenu,
    Menu,
    Menubar,
    Messages,
    MultiSelect,
    OrderList,
    OverlayPanel,
    Paginator,
    Panel,
    PanelMenu,
    Password,
    PickList,
    PieChart,
    PolarAreaChart,
    ProgressBar,
    RadarChart,
    RadioButton,
    Rating,
    Schedule,
    SelectButton,
    SlideMenu,
    Slider,
    Spinner,
    SplitButton,
    SplitButtonItem,
    TabPanel,
    TabView,
    Terminal,
    TieredMenu,
    ToggleButton,
    Tree,
    TreeTable
}
    from
        "primeng/primeng";
import Type = ts.Type;


/**
 *
 * A list of all the primeng directives used as part of a `@Component` annotation.
 *
 *  This is a shorthand for importing them each individually.
 *
 * ### Example
 *
 * ```typescript
 * @Component({
 *   selector: 'my-app',
 *   directives: [PRIMENG_DIRECTIVES]
 * })
 * class MyApp {}
 * ```
 */
export const PRIMENG_DIRECTIVES:Type[] = [
    Accordion,
    AccordionTab,
    AutoComplete,
    BarChart,
    Breadcrumb,
    Button,
    Calendar,
    Carousel,
    Checkbox,
    CodeHighlighter,
    Column,
    ContextMenu,
    DataGrid,
    DataList,
    DataScroller,
    DataTable,
    Dialog,
    DoughnutChart,
    Draggable,
    Dropdown,
    Droppable,
    Editor,
    Fieldset,
    Footer,
    Galleria,
    GMap,
    Growl,
    Header,
    InputSwitch,
    InputText,
    InputTextarea,
    Lightbox,
    LineChart,
    Listbox,
    MegaMenu,
    Menu,
    Menubar,
    Messages,
    MultiSelect,
    OrderList,
    OverlayPanel,
    Paginator,
    Panel,
    PanelMenu,
    Password,
    PickList,
    PieChart,
    PolarAreaChart,
    ProgressBar,
    RadarChart,
    RadioButton,
    Rating,
    Schedule,
    SelectButton,
    SlideMenu,
    Slider,
    Spinner,
    SplitButton,
    SplitButtonItem,
    TabPanel,
    TabView,
    Terminal,
    TieredMenu,
    ToggleButton,
    Tree,
    TreeTable
];
############

**Comment by cagataycivici** [comment]
Kinda invalid now as RC5 introduced modules.
