### ISSUE TITLE
Add a new datatable filter mode : in range

### ISSUE THREAD

**Issue by unaor** [primefaces/primeng#2671]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
In my datable i would like to filter by the date field, all rows that are in the last 24 hours, so i need a filter mode that returns all values in range

**Comment by Ketec** [comment]
This would be extra useful now. Especially since you implemented date range picker.

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
