### ISSUE TITLE
Issues with combining multiple functionality of Datatable

### ISSUE THREAD

**Issue by BartokW** [primefaces/primeng#2676]
**I'm submitting a ...**  (check one with "x")
```
[*] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/dWh4IJoFdiNDdQVMJwSE

**Current behavior**

When combining multiple functions of the datatable, the table starts to fail to render correctly.  Combining column grouping, frozen columns, and resizable columns.  
**Expected behavior**

Have the table not duplicate headers, and allow proper resizing of columns.

**Minimal reproduction of the problem with instructions**

https://embed.plnkr.co/WHNy59dEdKqDBP6rUQ7F/

**What is the motivation / use case for changing the behavior?**

It appears to be a bug when combining the functions, thus rendering in an un-usable manner.
**Please tell us about your environment:**

Win 10, VS 2017, npm, IIS
* **Angular version:** 4.1

* **PrimeNG version:** 4.0

* **Browser:** all

* **Language:** all

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Please create a separate issue with a specific case like "Column Grouping support for Frozen Columns" because as components is huge some features may not work well each other so we need take each case separately.

**Comment by BartokW** [comment]
The specific features are the ones I'm trying to use together, with an example in the plunker.  Maybe the issue name should be adjusted to something else?
