### ISSUE TITLE
emptyMessage template for DataTable

### ISSUE THREAD

**Issue by jhenriquez** [primefaces/primeng#2677]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**

Current functionality allows for a text to be set through the [emptyMessage] input property and this message is rendered when the provided dataset is empty.

**Expected behavior**

Allow for a custom template to be specified in a manner similar to how is done with columns.

```
<p-empty-message>
  <ng-template>
         <span> Now I can have stuff in here.</span>
         <button>Even a button</button>
  </ng-template>
</p-empty-message>
```

**What is the motivation / use case for changing the behavior?**

UX could improve greatly in scenarios where some action is expected from the user
in order for data to be rendered. Or when information more complex than a simple
message is required.

* **Angular version:** 2.4.5

* **PrimeNG version:** 1.1.4

**Comment by jhenriquez** [comment]
Just wanted to add that I could put in a PR for this functionality. Since I don't think the `emtpyMessage` needs to be removed, some ground rules could be set for this, like which would take priority.

Also, the way I was thinking to go about it, was by allowing another `pTemplate` type, something like `empty`. That way the behavior will be familiar enough:

```
<p-datatable>
  ...
  <ng-template pTemplate="emtpy">
      <span>This is an empty message from a template</span>
  </ng-template>
  ...
</p-datatable>
```

**Comment by smitpsanghavi** [comment]
I like the 2nd idea. Can make way for nice-looking empty table messages.

**Comment by cagataycivici** [comment]
Sounds good for 4.1.1

**Comment by jhenriquez** [comment]
Awesome, I'll make some time to put together a PR.

**Comment by Rchoudhary-tcs** [comment]
Even i faced a lot of issues in order to place another message instead of primeng default message for empty datatable.Finally i removed that with the help of css class  
           .ui-datatable-emptymessage{
                  display:none
            }
Definitely adding a support for  a template instead of a string as emptyMessage for DataTable is a good idea

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
