### ISSUE TITLE
Display loader while virtual scroller is fetching data

### ISSUE THREAD

**Issue by mcherb** [primefaces/primeng#2678]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

**VirtualScroll**
In the exemple https://www.primefaces.org/primeng/#/datatable/scroll of the virtualscroll, the table is freezing when we try to load a new set of data. (I see white box instead of rows)

**Expected behavior**
No freezing while loading

**Please tell us about your environment:**
Ubuntu, Intellij 17, npm

* **Angular version:** 4.0.0

* **PrimeNG version:** 4.0.0

* **Browser:** all
 
* **Language:** TypeScript 2.1.6

* **Node (for AoT issues):** `node --version` =   v6.2.2

**Comment by cagataycivici** [comment]
I guess we can apply loading status while data is loaded.

**Comment by kenisteward** [comment]
in html
``
<p-dataTable [value]="cars" [scrollable]="true" [loading]="loading" [lazy]="true" (onLazyLoad)="loadData($event)" [totalRecords]="totalRecords">
    <p-column field="vin" header="Vin"></p-column>
    <p-column field="year" header="Year"></p-column>
    <p-column field="brand" header="Brand"></p-column>
    <p-column field="color" header="Color"></p-column>
</p-dataTable>
``



in component
``
loadData(event: LazyLoadEvent) {
    this.loading = true;
    this.cars = cars.load().finally(() => { this.loading = false});
}
``

with this example why can't the developer just set their own loading status?  That's what I would do in this case

**Comment by kenisteward** [comment]
It would be nice to have an onVirtualScroll EventEmitter

**Comment by kenisteward** [comment]
@cagataycivici when have onVirtualScroll as of at least 4.1.0.rc2  we should split it into onvirtualscorllstart/end or just internally set it like you said

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
