### ISSUE TITLE
FileUpload with empty URL 

### ISSUE THREAD

**Issue by a4amitava** [primefaces/primeng#2679]
I just need to read the file on clicking upload button . but , it seems the URL property is mandatory . 
Is it possible to read the files contents ?

**Comment by cagataycivici** [comment]
PrimeNG 4.1 supports client side only uploads, use customUpload property for this, documentation has more details.

**Comment by yonsterTheMonster** [comment]
@cagataycivici  Custom upload not working for me. PrimeNG 4.1.0-rc.2

**Comment by sujoydc** [comment]
Custom upload doesn't work for me too. Why don't they have proper examples in the documentation. It's so confusing. I have moved to vaadin. Much better.
