### ISSUE TITLE
Performance issue with checkbox in DataTable

### ISSUE THREAD

**Issue by dzhavat** [primefaces/primeng#2684]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

http://plnkr.co/edit/NKedrmMxqEC7vREbS9Hg?p=preview

**Current behavior**
When I hover one of the checkboxes in the first column (see plnkr example), ```ui-state-hover``` class is being added to the element. This causes a performance issue since it relies on JavaScript to add/remove the class.

![capture](https://cloud.githubusercontent.com/assets/1096332/25662358/8914a22e-3014-11e7-990b-c0ed2242d576.PNG)

**Expected behavior**

Not cause a performance problem. Maybe take advantage of CSS and use ```:hover``` to change the element's styling instead of adding/removing a class.

**Minimal reproduction of the problem with instructions**
1. Open the plnkr example
2. Open DevTools in Chrome and go to the Performance tab
3. Start a new recording
4. Hover one/some of the checkboxes
5. Stop the recording and examine the results

**What is the motivation / use case for changing the behavior?**

It will improve the performance of the DataTable when using together with a selection mode.

**Please tell us about your environment:**

Windows 10

* **Angular version:** 4.0.3

* **PrimeNG version:** 4.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, we've switched to css psuedo in general, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview

**Comment by marcodafonseca** [comment]
I'm using Ng2, so I don't think I can use a PrimeNg version newer than 2.0.6... Is there a fix for angular 2 compatible primeng?
