### ISSUE TITLE
p-contextMenu doesn't work with *ngIf

### ISSUE THREAD

**Issue by ctrl-brk** [primefaces/primeng#2688]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
<p-contextMenu *ngIf='true' #cm [model]="menuItems"></p-contextMenu>
Will render the component's html but will not work. Right-click hook is lost and menu will not open.

**Expected behavior**

Should work the same as without *ngIf

* **Angular version:** 4.1.0

* **PrimeNG version:** 4.0.0-rc.3

* **Browser:** [ Chrome XX | Firefox XX]

**Comment by sudheerj** [comment]
I can't replicate the issue.It works fine for me.You can try to replicate on showcase example.
