### ISSUE TITLE
DropDown auto width issue

### ISSUE THREAD

**Issue by sudheerj** [primefaces/primeng#2690]
By default autowidth property of DropDown component is true.But the input width is not calculated based on panel width.If we disable the autoWidth behaviour then it works properly.

![image](https://cloud.githubusercontent.com/assets/3127317/25688893/69806c08-30b5-11e7-9214-d4323954fd30.png)

**Comment by Abbraxar** [comment]
I have this problem on autoWidth enabled and disabled, it doesn't change anything for me.
Actually, I can't have a p-drodown with a width matching the elements when the options are dynamics.

**Comment by muhammad-saleh** [comment]
Could you try to add this to your style ?
```
.ui-dropdown-panel {
    max-width: 0;
}
```

**Comment by Abbraxar** [comment]
Hi, @muhammad-saleh , thank you for your concern !

My problem is solved, it was a silly mistake from me :
  ```
<p-dropdown
    [options]="workspaceOptions"
    [ngModel]="workspaceInit"
    (onChange)="changeWorkspace($event)"
    [filter]="workspaceOptions.length > 5">
    [autoWidth]="true"
    [style]="{'width': '100%'}">
  </p-dropdown>
```
You see the early closing tag ? So autoWidth and style weren't send to the p-dropdown.

But the original issue is still happening !

**Comment by muhammad-saleh** [comment]
@sudheerj @Abbraxar 
Sorry for not having time to reply properly
But anyway I created a plunker showing the your problem and the fix that I proposed earlier:
http://plnkr.co/edit/BsQoUOiyD1P20VILb3GI?p=preview

Hope that this works for you

Also please pardon me for using `!important` in CSS

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview

**Comment by MarcGarland** [comment]
This is old but if anyone runs into this issue again, I had to initialize my SelectItem array to an empty array as I pull the items in from a service.
