### ISSUE TITLE
Calendar TimeOnly incorrect hourformat

### ISSUE THREAD

**Issue by sudheerj** [primefaces/primeng#2693]
When we use calendar time picker with time only option and hourformat="12"  then it displays popup with incorrect AM/PM display.It always display AM in time picker popup as below.

<`p-calendar [(ngModel)]="date8" [timeOnly]="true" [hourFormat]="12"></p-calendar>`

![image](https://cloud.githubusercontent.com/assets/3127317/25690962/122c2abe-30c9-11e7-8a10-8a967dfe65a1.png)

**Comment by ohsomofo** [comment]
I'm seeing the same behavior in 4.0.1. Did this fix not make it into the release?

**Comment by sudheerj** [comment]
Are you able to replicate the issue on showcase? It worked for me. Please provide plunker example.

**Comment by adibbleWLT** [comment]
Same here, issue still present. I just updated and it is still not displaying PM.

**Comment by adibbleWLT** [comment]
I just threw this into a basic plunker. Same issue appears there:
http://plnkr.co/edit/omUctyZwccEM8mGnKaXM?p=preview

**Comment by EugeneBugor** [comment]
Same behavior for me. AM/PM switch invokes only on hours step from 12 to 01. The rest steps **display** only AM. But the **value** of calendar is correct.

**Comment by IbrahimElkhatib** [comment]
Same behavior as @EugeneBugor described

**Comment by sudheerj** [comment]
The above issue is related to AM/PM format for time picker popup. This issue is not related to AM/PM display in input field(DatePicker and TimePicker)

**Comment by EugeneBugor** [comment]
@sudheerj added a new issue related to my problem [https://github.com/primefaces/primeng/issues/2867](here)

**Comment by adibbleWLT** [comment]
Just wondering, as this issue still says closed, but has never been fixed. Is someone looking into this?

**Comment by rich4756** [comment]
@Mrtcndkn Tested on 4.2.1, same issue is present.

```
<p-calendar [showTime]="true" [hourFormat]="12" [(ngModel)]="startDate" placeholder="Start Date" [minDate]="oneYearAgo" [maxDate]="today" [showIcon]="true" [readonlyInput]="true"></p-calendar>
```

Can we reopen?

**Comment by nitishGE** [comment]
I am facing the same issue. At output += date.getHours() > 11 ? ' PM' : ' AM'; why are we not considering the user selected AM/PM value. Rather we are taking it from system time. This is where the issue comes.
