### ISSUE TITLE
Memory leak in accordion

### ISSUE THREAD

**Issue by Skyr** [primefaces/primeng#2696]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When creating AccordionTabs, they are added to the `tab` array of the parent Accordion: https://github.com/primefaces/primeng/blob/master/components/accordion/accordion.ts#L87
When tabs are removed (e.g. due to property changes), they still remain in the `tab` array. This results in two effects:
* Because the index is determined as "position in `tab` array" (https://github.com/primefaces/primeng/blob/master/components/accordion/accordion.ts#L123), the index constantly increases, thus the index number in the onOpen/onClose events do not refer to the "n-th tab"
* The array builds up, causing increasing memory usage

**Expected behavior**
Index number and "n-th tab" should be identical.

When removing a tab from the Accordion, it should be removed from the `tab` array.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.3.1 (should not matter)

* **PrimeNG version:** Tested with 2.0.3 and 2.0.6. Problem present in trunk code.

**Workaround**
Get a reference on the Accordion component and clear the `tab` array manually before refilling (not very nice, but worked in my case).

This is possibly the same problem as reported in #386 (which was closed as "unable to reproduce").

**Comment by sudheerj** [comment]
Actually We don't have any method such as removeTab so that the array can be refreshed or refilled. Can you create a simple example to replicate the issue.

**Comment by Skyr** [comment]
The tabs are dynamically created (and removed!) via a binding:
```
<p-accordion (onOpen)="onOpen($event)">
  <p-accordionTab *ngFor="let issue of issues">
    <sk-cube-grid [isRunning]='!detailsLoaded(issue.id)'></sk-cube-grid>
    <div *ngIf='detailsLoaded(issue.id)'>
      {{details[issue.id].description}}
    </div>
  </p-accordionTab>
</p-accordion>
```
I'm displaying some issues depending on search parameters entered via the GUI. When clicking search, the `issues` array of my model is updated.

Details are lazy-loaded in the onOpen event. Here I experience the increase of the index number - after the first search, index starts with 0, after the second search, the index starts with the count of tabs of the previous search. There might be a more elegant way to do that (I'm new to Angular), but this would still leave the issue of the memory leak.

**Comment by ofekdeitch** [comment]
If you know when the number of issues\accordion change, you can reinsert the `p-accordion` into the DOM via `*ngIf` as follows:

app.component.html:
```
<p-accordion (onOpen)="onOpen($event)" *ngIf="showAccordion">
  <p-accordionTab *ngFor="let issue of issues">
    <sk-cube-grid [isRunning]='!detailsLoaded(issue.id)'></sk-cube-grid>
    <div *ngIf='detailsLoaded(issue.id)'>
      {{details[issue.id].description}}
    </div>
  </p-accordionTab>
</p-accordion>
```

app.component.ts:
```
showAccordion = true;
issues: Issue[];

onIssusesChanged (newIssues: Issue[])
{
	this.showAccordion = false;
	this.issues = newIssues;
	this.reconstructAccordion();
}

reconstructAccordion(){
	setTimeOut(() => {
		this.showAccordion = true;
	},0);
}
```

**Comment by cagataycivici** [comment]
I've replicated these problems and working on them.
