### ISSUE TITLE
[question] how to disable mouse over labels in charts?

### ISSUE THREAD

**Issue by sebelga** [primefaces/primeng#2697]
**I'm submitting a ...**  (check one with "x")
```
[x] question
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Is there a way to disable the mouse over "labels" on the chart Components ?

thanks!

**Comment by sudheerj** [comment]
Please check Chartjs [](http://www.chartjs.org/docs/) options on disabling tooltip flag.ChartModel provides options attribute to add all these configuration.
