### ISSUE TITLE
Autocomplete shows [object Object] for objects field if it contains empty string

### ISSUE THREAD

**Issue by alezhu** [primefaces/primeng#2698]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://embed.plnkr.co/c0B8wHSeOMT3ySGKAXk8/

**Current behavior**
Autocomplete shows [object Object] for objects field if it contains empty string.

This is because autocompletes template uses such logic:

`[value]="value ? (field ? objectUtils.resolveFieldData(value,field)||value : value) : null"`

**objectUtils.resolveFieldData** return empty string, but empty string is FALSE and logic set value as [value] for input.

**Expected behavior**
Autocomplete shows empty string for objects field if it contains empty string

**Minimal reproduction of the problem with instructions**
See [plnkr link ](https://embed.plnkr.co/c0B8wHSeOMT3ySGKAXk8/)

**What is the motivation / use case for changing the behavior?**
Empty string is normal 

**Please tell us about your environment:**

Wndows,PhpStorm,npm,Apache

* **Angular version:** 2.0.X
4.1.0

* **PrimeNG version:** 2.0.X
4.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

* **Node (for AoT issues):** `node --version` =

**Comment by jaime-marcondes** [comment]
We have to initialize with " "  to shows correct behaviour too

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
