### ISSUE TITLE
Using file upload with a non-wildcard MIME type results in validation errors

### ISSUE THREAD

**Issue by jessepinho** [primefaces/primeng#2699]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

See here (note the `[accept]="'application/pdf'"`):
http://plnkr.co/edit/laAPazhuKxaQbPwu3y2N?p=preview

**Current behavior**

Selecting a PDF file for upload displays the error `Invalid file type, allowed file types: application/pdf.`.

**Expected behavior**

Selecting a PDF file for upload would result in no errors.

**Minimal reproduction of the problem with instructions**

See the Plunkr linked above. To test it, select a PDF file for upload, and you'll see the validation errors.

**What is the motivation / use case for changing the behavior?**

The [documentation](https://www.primefaces.org/primeng/#/fileupload) indicates that anything you could pass as a value to `accept` in an `<input type="file">` element is also acceptable here. However, PrimeNg's behavior is to effectively disallow MIME types in the `accept` property.

NOTE: this seems to be due to [this logic](https://github.com/primefaces/primeng/blob/master/components/fileupload/fileupload.ts#L196-L197), which only checks the MIME type if `FileUpload.accept` has a wildcard (e.g., an asterisk) in it. Otherwise, it just checks the extension.

**Please tell us about your environment:**

Mac, VSCode, NPM, Express server

* **Angular version:** 4.0.X

* **PrimeNG version:** 4.0.X

* **Browser:** Chrome

 
* **Language:** TypeScript

* **Node (for AoT issues):** `node --version` =

**Comment by JohannesBusch** [comment]
I tried all known types for csv and excel, but i always get the same result. even `application/*` does not work.

**Comment by aradosz79** [comment]
I can confirm that I have this component working with PDF files and it is ok.
Try maybe update your primeng version: 'npm update primeng' 

My is latest 4.1.3 running on angular v. 4.1.0

**Comment by JohannesBusch** [comment]
I just upgraded to verson 4.2 and checked again. it does not work for excel/csc files

**Comment by saiidabs** [comment]
@JohannesBusch  for me uploading files i had it like 
[accept]= "'.pdf,.doc,.docx,.text,.txt'"
having any spaces in that string caused it shit out invalid, so try it without spaces
