### ISSUE TITLE
Failure on Angular 2 beta.16

### ISSUE THREAD

**Issue by brian428** [primefaces/primeng#270]
Compile error in primeng when using Angular 2 beta.16:

`...ui/node_modules/primeng/components/splitbutton/splitbutton.d.ts(4,18): error TS2305: Module '"ui/node_modules/angular2/router"' has no exported member 'Location'.`

`Location` class has been moved, so the import probably just needs to be updated to:
`import {Location} from "angular2/platform/common";`

As an aside, beta.16 has a number of breaking changes so it's probably worth double-checking the other things mentioned here: https://github.com/angular/angular/blob/master/CHANGELOG.md

**Comment by cagataycivici** [comment]
Please see;

http://forum.primefaces.org/viewtopic.php?f=35&t=45287

and

https://github.com/primefaces/primeng/issues/260

In summary, upcoming beta4 adds support for angular2 beta16.
