### ISSUE TITLE
Row grouping with multiple fields

### ISSUE THREAD

**Issue by uroti** [primefaces/primeng#2709]
It is possible a multi row grouping with different fields?
I saw that now it is possible only with one field.

Thank you

**Comment by Inaamhusain** [comment]
Is there any example where we can see row grouping for multiple fields?

**Comment by Inaamhusain** [comment]
Is anyone active?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
