### ISSUE TITLE
npm start not working.

### ISSUE THREAD

**Issue by ishara** [primefaces/primeng#271]
npm start not working , I can see some dependence not install with current package.json.

How can I getting start ?

Any plan to add test cases to testing component ?

**Comment by cagataycivici** [comment]
Which project are you building? Your own? or PrimeNG itself?

**Comment by ishara** [comment]
PrimeNg itself

**Comment by cagataycivici** [comment]
Replace peerDependencies with;

```json
  "dependencies": {
 	"angular2": "2.0.0-beta.16",
    "systemjs": "0.19.26",
    "es6-shim": "^0.35.0",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.2",
    "zone.js": "0.6.12"
    "primeui": "4.1.8"
  },
```
Then do;

npm install
typings install
tsc
npm start

**Comment by ishara** [comment]
ok , thx for reply , any reason to remove this or mistakenly removed ?   

Do you have component test suite ?

**Comment by cagataycivici** [comment]
This is on purpose, as we publish to npm from this project, don't need to publish dependencies as it is suggested to use peerDependencies when publishing a module.

**Comment by JakeSummers** [comment]
> This is on purpose, as we publish to npm from this project

Hi @cagataycivici, any tips on how to publish from this project?  Posted a full question here: 

https://github.com/primefaces/primeng/issues/818
