### ISSUE TITLE
Allow header column group on tree table

### ISSUE THREAD

**Issue by ccasallas** [primefaces/primeng#2715]
Hi,

I'm submitting a

[ ] bug report
[ x ] feature request
[ ] support request 

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

I tried using header column group but it is unavailable for tree table:

```
<p-treeTable [value]="activities">
    <p-header>PLAN</p-header>

<p-headerColumnGroup>
		<p-row>
			<p-column header="Activity" rowspan="2"></p-column>
			<p-column header="Progress"  rowspan="2"></p-column>
			<p-column header="Responsible"  rowspan="2"></p-column>
			<p-column header="Resources" colspan="3"></p-column>
			<p-column header="Date" rowspan="2"></p-column>
		</p-row>
		<p-row>
			<p-column header="Financial" ></p-column>
			<p-column header="Technical"></p-column>
			<p-column header="Human"></p-column>
		</p-row>
	</p-headerColumnGroup>
	...........

```
This feature is available in common data table, Is it possible to enable it for tree table?

Prime forum discussion: https://forum.primefaces.org/posting.php?mode=reply&f=35&t=50655

thanks,

Carlos

**Comment by cagataycivici** [comment]
TreeTable will be reimplemented, please monitor;

#4813
