### ISSUE TITLE
[Showcase]Step Component activeIndexChange callback missing

### ISSUE THREAD

**Issue by sudheerj** [primefaces/primeng#2717]
The steps component supports one event callback named "activeIndexChange".But it is not documented in showcae. So it should be added events section.

**Comment by cagataycivici** [comment]
We don't document two-way binding helpers as it is not a callback, just there to write it back to model.

**Comment by seyyah** [comment]
@cagataycivici how to use `activeIndexChange` event? `p-steps` works but `activeIndex` doesn't. Give us a simple example?

```html
<p-steps
  [model]="items"
  [(activeIndex)]="activeIndex"
  styleClass="steps-custom"
  (activeIndexChange)="foobar($event)">
</p-steps>
```

```typescript
  foobar(event) {
    console.log("XXX: ", event);
  }
```

**Comment by aliasbody** [comment]
For everyone interested, this is how I managed to make it working (but indeed a good documentation is required here):

```html
<p-steps 
  #stepper 
  [model]="items" 
  [(activeIndex)]="activeIndex" 
  [readonly]="false" 
  (activeIndexChange)="stepperChanged($event)">
</p-steps>

<button 
  pButton 
  type="button" 
  label="Next Step"
  (click)="goToStep(1)"
```

And then on the .ts component:

```typescript
import {Steps} from 'primeng';
import {Component, OnInit, ViewChild} from '@angular/core';

(...)

@ViewChild('stepper', {static: true}) stepper: Steps;
public activeIndex = 0;

public stepperChanged(step) {
    console.log(1);
}

public goToStep(step: number) {
  this.stepper.activeIndexChange.emit(step);
}
```

This way the step is moved and the index is also updated.
