### ISSUE TITLE
p-dialog does not show

### ISSUE THREAD

**Issue by Mithi83** [primefaces/primeng#2720]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/di7mgd5fAEsw3l9Y5DHr

**Current behavior**
When I click on the button, the greyed-out background is shown, but the dialog is not shown. Inspecting the DOM, I found that the problem was style="display: none". Manually editing this to style="display: block" fixes the visibility issue.

```
<p-dialog header="Godfather I" modal="modal" responsive="true" width="300" ng-reflect-header="Godfather I" ng-reflect-width="300" ng-reflect-modal="modal" ng-reflect-responsive="true" ng-reflect-visible="true">
        <div class="ui-dialog ui-widget ui-widget-content ui-corner-all ui-shadow ui-dialog-draggable" ng-reflect-ng-class="[object Object]" style="display: none; width: 300px; visibility: visible; left: 266px; top: 757.5px; z-index: 1004;">
```

**Expected behavior**
Upon clicking the button, the style="display: block" should be automatically set.

**Minimal reproduction of the problem with instructions**
Take the example plunker, add the code from the example https://www.primefaces.org/primeng/#/dialog and hook it up to a button.

**What is the motivation / use case for changing the behavior?**
Working dialogs.

**Please tell us about your environment:**
Fedora 25

* **Angular version:** 4.0.3

* **PrimeNG version:** 4.0.0

* **Browser:** Chrome 52.0.2743.49 beta, Firefox 53.0

I found no way to re-open #2641 which sounds like a similar problem.

**Comment by sudheerj** [comment]
You need to import modules such BrowserAnimations, footer etc. There are many errors in your app.You can find them using Developer tools.
