### ISSUE TITLE
[Dropdown] [appendTo body] Calculated width doesn't take border and padding into consideration

### ISSUE THREAD

**Issue by muhammad-saleh** [primefaces/primeng#2723]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/dWh4IJoFdiNDdQVMJwSE

**Current behavior**
I was trying to use appendTo feature in the dropdown component and I noticed that there was 2px off in the calculated width
So I checked and found that this function in `dropdown.ts` return the width of the element without the border
```
public getWidth(el): number {
        let width = el.offsetWidth;
        let style = getComputedStyle(el);

        width -= parseFloat(style.paddingLeft) + parseFloat(style.paddingRight) + parseFloat(style.borderLeftWidth) + parseFloat(style.borderRightWidth);

        return width;
    }
```
*You could try it directly in the browser to check the result*

**Expected behavior**
It should return the width of the element including the border

### Question:
I see that you subtracted the padding and border width intentionally but may I know the reason why ?

* **Angular version:** 2.0.X
4

* **PrimeNG version:** 2.0.X
4

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
