### ISSUE TITLE
Tooltip content does not refresh until tooltip is reopened

### ISSUE THREAD

**Issue by aszechlicki** [primefaces/primeng#2727]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

http://plnkr.co/edit/19XYGXLVSfgV0z9wagwJ?p=preview

**Current behavior**
Tooltip content does not refresh when tooltip is open

**Expected behavior**
Tooltip content is refreshed even if tooltip is open

**Minimal reproduction of the problem with instructions**
See attached plunkr - value in tooltip is not refreshed until tooltip is reopened

**What is the motivation / use case for changing the behavior?**
I have a set of indicators displaying various parameters that change in real-time, and use tooltips to preview their current value.
One way of doing it would be adding support for ng-template as a tooltip content, it would have additional benefit of greatly improving flexibility of tooltip

**Please tell us about your environment:**
Windows, Angular-CLI

* **Angular version:** 4.1.0

* **PrimeNG version:** 4.0.0-rc.4

* **Browser:** 
all
 
* **Language:** TypeScript

* **Node (for AoT issues):** `node --version` =   v6.9.5

**Comment by cagataycivici** [comment]
Fixed in 4.1.RC1
