### ISSUE TITLE
Schedule RerenderEvents for supporting event filtering

### ISSUE THREAD

**Issue by pierfreeman** [primefaces/primeng#2729]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

Currently, also looking at the source code, the Schedule component does not implement the ReRenderEvent function. I have events with color properties, and I want to filter in and out the rendered events based on their colors.

**Expected behavior**

For my project I need to implement an event filtering based on event attributes through options selectors (like this -> http://stackoverflow.com/questions/6641355/jquery-fullcalendar-event-filtering/29993265#29993265).
Apart for the future plans to implement this feature, is there any workaround for get it working?

* **Angular version:** 4.1

* **PrimeNG version:** 4.0

**Comment by cagataycivici** [comment]
Maybe you can use the options property that is used to pass any fullcalendar option to p-schedule including config options, callbacks.

**Comment by yigitfindikli** [comment]
Schedule component is deprecated, you can use FullCalendar instead of schedule.
