### ISSUE TITLE
Dropdown in rowexpansion rendering below table

### ISSUE THREAD

**Issue by C00per** [primefaces/primeng#2730]
There is no overflow on the 'td' tag of the expandable row, so the dropdown list is partially behind the table row.
![image](https://cloud.githubusercontent.com/assets/1847391/25817566/706a3908-3430-11e7-9ed7-e04d84390148.png)

**Comment by C00per** [comment]
I've added to my CSS file to fix the issue

```
tbody.ui-datatable-data.ui-widget-content  > tr > td {
    overflow: visible;
}
```

**Comment by cagataycivici** [comment]
You can also try appendTo="body"
