### ISSUE TITLE
Add centerOnShow property to Dialog

### ISSUE THREAD

**Issue by Sergeon** [primefaces/primeng#2735]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request 
```

When the DialogComponent raises, a call to `center()` is made to center it within its container. There is no way for the client to prevent or customize this behavior right now.

Would be nice to be able to override this function, or at least to prevent it to be called. A prop like:

```html
<p-dialog [center]="false" ...> ... </p-dialog>
```

to prevent the function to be called would be useful, so the client can place the Dialog where she wants instead where `center()` places it. Exposing it as a hook is more complicated I guess, since client would have to mess with `domHandler` or `component` properties, I'm really not sure if it's worth the effort.

**Comment by SchneMa** [comment]
you can access the positioning with css deep accessor like this:

```
:host>>>.ui-dialog {
  top: 50% !important;
  left: 50% !important;
  transform: translate(-50%, -50%);
}
```

because the positioning is injected to the style attribute of the element you need the `!important` flag...
just a little workaround ;)

**Comment by SIlver--** [comment]
@SchneMa Thank you! this fixes my issue for #2795 for now

**Comment by SchneMa** [comment]
@SIlver-- glad to help 😄

**Comment by cagataycivici** [comment]
Tracked at https://github.com/primefaces/primeng/issues/2795
