### ISSUE TITLE
MultiSelect Optional Filter

### ISSUE THREAD

**Issue by adama357** [primefaces/primeng#2736]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```

The Dropdown input field allows you to specify whether or not you want a filter.  Would it be feasible to also make this optional for MultiSelect?  

E.g., you could set [filter]="false" if you didn't want it. 

Thanks!

**Comment by smitpsanghavi** [comment]
I came to create an issue for this change. Searched and found this. Guess I don't need to now.
