### ISSUE TITLE
p-dataTable no longer works with async pipe (4.0.0 regression)?

### ISSUE THREAD

**Issue by johnhwright** [primefaces/primeng#2737]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://embed.plnkr.co/7UPRshevNS75ZPgfqaPw/

**Current behavior**
As of the official 4.0.0 release, when using `| async` the table doesn't update beyond the first event. Note that in previous versions (<= 4.0.0-rc.3) this worked fine.

**Expected behavior**
The table would continue to update throughout the life of the observable.

**Minimal reproduction of the problem with instructions**
See plunk. 

**Please tell us about your environment:**

* **Angular version:**
4.0.0

* **PrimeNG version:**
4.0.0

* **Browser:** all
 
* **Language:** all

* **Node (for AoT issues):** `node --version` =  v7.3.0

**Comment by bomberblue07** [comment]
Hi @johnhwright it sounds like you have a similar issue to me, #2689 The issue is due to PrimeNG changing their change detection for datatables in RC.4 onward. Hope that helps!

**Comment by cagataycivici** [comment]
Please try solution at 2689.
