### ISSUE TITLE
4.0.0 Using [style] on p-column triggers error: Failed: Attempted to assign to readonly property.

### ISSUE THREAD

**Issue by blackholegalaxy** [primefaces/primeng#2738]
### I'm submitting a ...
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

### To reproduce
To reproduce, use html template containing a `p-column` with `[style]` and run under PhantomJS (using Karma to test such a component for example) (please note: if testing, run detectChanges, otherwise the error won't trigger as Phantom won't try to parse HTML template)

Use the [primeNG's example of Editable Datatable](https://www.primefaces.org/primeng/#/datatable/editable), especially the HTML part where we set:

```html
<p-column field="brand" header="Brand" [editable]="true" [style]="{'overflow':'visible'}">
   <ng-template let-col let-car="rowData" pTemplate="editor">
      <p-dropdown [(ngModel)]="car[col.field]" [options]="brands" [autoWidth]="false" [style]="{'width':'100%'}" required="true"></p-dropdown>
  </ng-template>
</p-column>
```

The important part, causing the issue is: `[style]="{'overflow':'visible'}"`.

Please note I tried with another style, with the same error occuring. **As soon as there is a `[style]` attribute, the error triggers.**

### Please note

**Using style on any other attribute than `p-column`, for example `p-dropdown`, works like a charm.**

### Current behavior

> Failed: Attempted to assign to readonly property.
> 
> 
>     setProperty@webpack:///~/@angular/platform-browser/@angular/platform-browser.es5.js:2923:0 <- NgAppSrc/test.ts:36994:11
>     setProperty@webpack:///~/@angular/core/@angular/core.es5.js:13256:0 <- NgAppSrc/test.ts:13637:34
>     setElementProperty@webpack:///~/@angular/core/@angular/core.es5.js:9530:0 <- NgAppSrc/test.ts:9911:30
>     checkAndUpdateElementValue@webpack:///~/@angular/core/@angular/core.es5.js:9449:0 <- NgAppSrc/test.ts:9830:31
>     checkAndUpdateElementInline@webpack:///~/@angular/core/@angular/core.es5.js:9383:0 <- NgAppSrc/test.ts:9764:50
>     checkAndUpdateNodeInline@webpack:///~/@angular/core/@angular/core.es5.js:12077:0 <- NgAppSrc/test.ts:12458:50
>     checkAndUpdateNode@webpack:///~/@angular/core/@angular/core.es5.js:12052:0 <- NgAppSrc/test.ts:12433:40
>     debugCheckAndUpdateNode@webpack:///~/@angular/core/@angular/core.es5.js:12681:21 <- NgAppSrc/test.ts:13062:64
>     debugCheckRenderNodeFn@webpack:///~/@angular/core/@angular/core.es5.js:12660:0 <- NgAppSrc/test.ts:13041:36
>     debugUpdateRenderer@webpack:///~/@angular/core/@angular/core.es5.js:12645:0 <- NgAppSrc/test.ts:13026:35
>     checkAndUpdateView@webpack:///~/@angular/core/@angular/core.es5.js:12024:0 <- NgAppSrc/test.ts:12405:28
>     callViewAction@webpack:///~/@angular/core/@angular/core.es5.js:12334:0 <- NgAppSrc/test.ts:12715:35
>     execComponentViewsAction@webpack:///~/@angular/core/@angular/core.es5.js:12280:0 <- NgAppSrc/test.ts:12661:27
>     checkAndUpdateView@webpack:///~/@angular/core/@angular/core.es5.js:12025:0 <- NgAppSrc/test.ts:12406:29
>     callWithDebugContext@webpack:///~/@angular/core/@angular/core.es5.js:13007:25 <- NgAppSrc/test.ts:13388:47
>     debugCheckAndUpdateView@webpack:///~/@angular/core/@angular/core.es5.js:12547:0 <- NgAppSrc/test.ts:12928:32
>     detectChanges@webpack:///~/@angular/core/@angular/core.es5.js:10116:52 <- NgAppSrc/test.ts:10497:81
>     _tick@webpack:///~/@angular/core/@angular/core/testing.es5.js:182:0 <- NgAppSrc/test.ts:31782:45
>     webpack:///~/@angular/core/@angular/core/testing.es5.js:196:41 <- NgAppSrc/test.ts:31796:54
>     invoke@webpack:///~/zone.js/dist/zone.js:365:0 <- NgAppSrc/polyfills.ts:3013:31
>     onInvoke@webpack:///~/zone.js/dist/async-test.js:49:0 <- NgAppSrc/test.ts:91740:45
>     onInvoke@webpack:///~/zone.js/dist/proxy.js:76:0 <- NgAppSrc/test.ts:92428:47
>     invoke@webpack:///~/zone.js/dist/zone.js:364:0 <- NgAppSrc/polyfills.ts:3012:40
>     onInvoke@webpack:///~/@angular/core/@angular/core.es5.js:4125:0 <- NgAppSrc/test.ts:4506:43
>     invoke@webpack:///~/zone.js/dist/zone.js:364:0 <- NgAppSrc/polyfills.ts:3012:40
>     run@webpack:///~/zone.js/dist/zone.js:125:0 <- NgAppSrc/polyfills.ts:2773:49
>     run@webpack:///~/@angular/core/@angular/core.es5.js:3994:42 <- NgAppSrc/test.ts:4375:65
>     detectChanges@webpack:///~/@angular/core/@angular/core/testing.es5.js:196:0 <- NgAppSrc/test.ts:31796:28
>     webpack:///NgAppSrc/app/task/expression/expression-list/expression-list.component.spec.ts:172:25 <- NgAppSrc/test.ts:32690:30
>     invoke@webpack:///~/zone.js/dist/zone.js:365:0 <- NgAppSrc/polyfills.ts:3013:31
>     onInvoke@webpack:///~/zone.js/dist/async-test.js:49:0 <- NgAppSrc/test.ts:91740:45
>     onInvoke@webpack:///~/zone.js/dist/proxy.js:76:0 <- NgAppSrc/test.ts:92428:47
>     invoke@webpack:///~/zone.js/dist/zone.js:364:0 <- NgAppSrc/polyfills.ts:3012:40
>     runGuarded@webpack:///~/zone.js/dist/zone.js:138:0 <- NgAppSrc/polyfills.ts:2786:53
>     runInTestZone@webpack:///~/@angular/core/@angular/core/testing.es5.js:110:0 <- NgAppSrc/test.ts:31710:35
>     webpack:///~/@angular/core/@angular/core/testing.es5.js:49:0 <- NgAppSrc/test.ts:31649:26
>     invoke@webpack:///~/zone.js/dist/zone.js:365:0 <- NgAppSrc/polyfills.ts:3013:31
>     onInvoke@webpack:///~/zone.js/dist/proxy.js:79:0 <- NgAppSrc/test.ts:92431:45
>     invoke@webpack:///~/zone.js/dist/zone.js:364:0 <- NgAppSrc/polyfills.ts:3012:40
>     run@webpack:///~/zone.js/dist/zone.js:125:0 <- NgAppSrc/polyfills.ts:2773:49
>     webpack:///~/zone.js/dist/jasmine-patch.js:102:0 <- NgAppSrc/test.ts:92143:37
>     webpack:///~/@angular/core/@angular/core/testing.es5.js:96:0 <- NgAppSrc/test.ts:31696:31
>     invoke@webpack:///~/zone.js/dist/zone.js:365:0 <- NgAppSrc/polyfills.ts:3013:31
>     onInvoke@webpack:///~/zone.js/dist/async-test.js:49:0 <- NgAppSrc/test.ts:91740:45
>     onInvoke@webpack:///~/zone.js/dist/proxy.js:76:0 <- NgAppSrc/test.ts:92428:47
>     invoke@webpack:///~/zone.js/dist/zone.js:364:0 <- NgAppSrc/polyfills.ts:3012:40
>     run@webpack:///~/zone.js/dist/zone.js:125:0 <- NgAppSrc/polyfills.ts:2773:49
>     webpack:///~/@angular/core/@angular/core/testing.es5.js:91:0 <- NgAppSrc/test.ts:31691:28
>     webpack:///~/zone.js/dist/async-test.js:38:0 <- NgAppSrc/test.ts:91729:46
>     invokeTask@webpack:///~/zone.js/dist/zone.js:398:0 <- NgAppSrc/polyfills.ts:3046:36
>     runTask@webpack:///~/zone.js/dist/zone.js:165:0 <- NgAppSrc/polyfills.ts:2813:57
>     invoke@webpack:///~/zone.js/dist/zone.js:460:0 <- NgAppSrc/polyfills.ts:3108:45
>     timer@webpack:///~/zone.js/dist/zone.js:1540:0 <- NgAppSrc/polyfills.ts:4188:34

### Expected behavior
We must be able to use [style] under PhantomJS on p-column. 

**Please note: using style on any other attribute, for example p-dropdown, works like a charm.**

### Please tell us about your environment:*

* **Angular version:** 4.1.0

* **PrimeNG version:** 4.0.0

* **Browser:** [ PhantomJS 2.1.1 ] - It may occur on other browsers
 
* **Language:** [TypeScript]

**Comment by psaussure** [comment]
Any news on that?

**Comment by cagataycivici** [comment]
My colleague will review for 4.1.

**Comment by cagataycivici** [comment]
Seems like an Angular issue, we just bind to ngStyle, I can't think of something that we can change.

**Comment by blackholegalaxy** [comment]
The fact is applying ngStyle or [style] equivalent on other modules than primeng p-column works like a charm...

**Comment by a-kolybelnikov** [comment]
Same issue with the [scrollHeight] and [scrollWidth] properties on p-dataTable component:
`TypeError: Cannot assign to read only property 'scrollHeight' of object '[object HTMLElement]'`
