### ISSUE TITLE
Dropdown not closing when body is clicked 

### ISSUE THREAD

**Issue by upmauro** [primefaces/primeng#2739]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/nxfNbrz8megTYL5yaN8Z?p=preview

**Current behavior**
The dropdown close just if another element is clicked, body is ignored.

**Expected behavior**
Close dropdown when body is clicked too;

**Minimal reproduction of the problem with instructions**
Steps described in plunkr

* **PrimeNG version:** 4.0.0

**Comment by ademilsonfp** [comment]
+1

**Comment by victorguimaraessilva** [comment]
👍🏻

**Comment by cagataycivici** [comment]
We listen to document click, can you replicate at;

https://www.primefaces.org/primeng/#dropdown

**Comment by SIlver--** [comment]
This occurs in plunker because you're clicking *outside* the `body` tag onto the iframe. 

![image](https://cloud.githubusercontent.com/assets/6362347/26128181/84f5505e-3a59-11e7-89eb-ce797436a8c4.png)

The yellow is out of context.

**Comment by ademilsonfp** [comment]
So you should use window event instead of document... no?!

**Comment by cagataycivici** [comment]
Should be fixed with recent releases, we were listening body not the document. Please try on a real page not a plunkr with iframes.
