### ISSUE TITLE
DataList with Loading Status like DataTable

### ISSUE THREAD

**Issue by SchneMa** [primefaces/primeng#2742]
[ x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap

Is it planned or is it possible to extend the DataList with a LoadingStatus like its implemented for DataTable?
At the moment only DataTable got this LoadingStatus like shown here:

`<p-dataTable [value]="cars" [loading]="loading">`

If usefull and possible you could add this option to DataList too.
Potentially also add it to DataGrid and other DataComponents if needed.

**Comment by ketsching** [comment]
Is there a plan to add this feature to the roadmap?

**Comment by cagataycivici** [comment]
Sounds good to me for 4.1.1.

**Comment by pkerblaze** [comment]
Any new planification for this feature ? Also for dataGrid / DataView since they work the same way

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
