### ISSUE TITLE
Swipe support for Carousel

### ISSUE THREAD

**Issue by QuentinLeGoff** [primefaces/primeng#2743]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Swipe support for touch enabled seems to not work on desktops or touch devices

**Minimal reproduction of the problem with instructions**
On your website ([https://www.primefaces.org/primeng/#/carousel](https://www.primefaces.org/primeng/#/carousel)), swipe navigation doesn't work even with touch mode enabled.

**Please tell us about your environment:**
Windows 10

* **Angular version:** 4.1.1

* **PrimeNG version:** 4.0.0

* **Browser:** [all]
 
* **Language:** [all | TypeScript 2.3]

**Comment by sinsunsan** [comment]
I am also waiting for that feature which is important for  a responsive site. 
Meanwhile I will use a jquery slick http://kenwheeler.github.io/slick/
wrapped in angular 2 https://github.com/stevermeister/ng2-slick

**Comment by Lolash** [comment]
Let me quote documentation:

> Carousel displays content using a slide effect featuring responsive mode, **swipe support for touch enabled devices** and various customization options.

Any update on the issue, because it's still not working?

**Comment by rafa-as** [comment]
Some news @cagataycivici ?

**Comment by cagataycivici** [comment]
Part of #3896
