### ISSUE TITLE
Allow editor template access rowIndex in datatable

### ISSUE THREAD

**Issue by JulienBroi** [primefaces/primeng#2744]
**I'm submitting a ...**
```
[x] bug report 
[ ] feature request 
[ ] support request
```

**What is the motivation / use case for changing the behavior?**
This issue was fixed in primeng 4 but was not in version 2 (see: https://github.com/primefaces/primeng/issues/2104)
I would like it to be fixed in primeng 2 since I need it.

* **Angular version:**
2.4

* **PrimeNG version:**
2.0.5

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
