### ISSUE TITLE
Support sortFunction for custom sort in case of lazy loading in DataTable.

### ISSUE THREAD

**Issue by sabithpocker** [primefaces/primeng#2748]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/dWh4IJoFdiNDdQVMJwSE

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**
```
<p-dataTable [value]="cars" [lazy]="true" [rows]="10" [paginator]="true" 
            [totalRecords]="totalRecords" (onLazyLoad)="loadCarsLazy($event)">
    <p-column field="year" header="Year" sortable="custom" (sortFunction)="sortDates($event)"></p-column>
</p-dataTable>
```
```
loadCarsLazy(event: LazyLoadEvent) {
    event.sortOrder;//yes
    event.sortField;//yes
    event.sortFunction;//undefined
}
```
**What is the motivation / use case for changing the behavior?**

The motivation is a bit abnormal, we have chosen to sort only the items available in client side and not fetch sorted list from server. We can opt to do this incase of default search(alphabetic) but for other custom searches there is no way to find the custom sortFunction defined in `p-data-table`.

**Please tell us about your environment:**

Mac OS Sierra, Sunlime, npm, webpack server.
* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

4.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 all
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by cagataycivici** [comment]
Sounds good.
