### ISSUE TITLE
p-dialog with closable false still displays close icon in header

### ISSUE THREAD

**Issue by desertdev** [primefaces/primeng#2750]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
```
http://plnkr.co/edit/PMczHH9jLneYXfUtvotZ?p=preview

**Current behavior**
p-dialog with attribute closable="false" still displays the 'x' close icon in the header.

**Expected behavior**
The 'x' icon should not be displayed when closable is false.

**Angular version:** 4.0.2
**PrimeNG version:** 4.0.0

**Comment by sudheerj** [comment]
You should mention property binding with square brackets in order to treat them as boolean values instead string values.

So it should be [closable]="true"
