### ISSUE TITLE
Template Plunkr with BrowserAnimationsModule fails to load due to missing libraries

### ISSUE THREAD

**Issue by stephanie-dm** [primefaces/primeng#2754]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/ZtIHlvbeDiM4uvivhNDc

**Current behavior**
When I create a new Plunkr based on the PrimeNG template Plunkr, it fails to load when I use the DialogModule in combination with the BrowserAnimationsModule.

After hours of searching, I discovered there was a network error on fetching the animations-script. Apparently the systemjs.config.js needs the following extra lines:

    '@angular/animations/browser': 'npm:@angular/animations/bundles/animations-browser.umd.js',
    '@angular/platform-browser/animations': 'npm:@angular/platform-browser/bundles/platform-browser-animations.umd.js',   

If you edit my Plunkr with these 2 extra lines, it does work. Please update the PrimeNG template Plunkr accordingly to save everyone else a lot of trouble!

* **Angular version:** 4.0.0

* **PrimeNG version:** 4.0.0.rc1

**Comment by sudheerj** [comment]
Cagatay only can update the PrimeNG issue template with the above mentioned animation package. I don't have access :)

**Comment by cagataycivici** [comment]
New plunkr should fix it.
