### ISSUE TITLE
Dialog: onAfterHide is not called when closing the dialog with "X"

### ISSUE THREAD

**Issue by stephanie-dm** [primefaces/primeng#2755]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/ppEZJKS5IcjwhR6OJ10l

**Current behavior**
The onAfterHide-callback is not called when closing the dialog with the default "X".

When you change the PrimeNG-version from 4.0.0 to 4.0.0-rc.1 (in systemjs.config.js), it works again, and it also used to work in PrimeNG 2.X.

The custom "Close" button in the dialog also doesn't trigger the onAfterHide-event, and this was previously mentioned in issue https://github.com/primefaces/primeng/issues/956 , but it still doesn't seem to be solved. Changing the PrimeNG-version from 4.0.0 to 4.0.0-rc.1 doesn't have any effect in this case, it doesn't work in both versions.

**Expected behavior**
I expect the onAfterHide-callback to be called when the dialog is closed with "X" and when changing the value for the "visible" attribute to false.

* **Angular version:** 4.0.0

* **PrimeNG version:** 4.0.0

* **Browser:** Chrome and Firefox (I haven't tested other ones)

**Comment by cagataycivici** [comment]
Callback name is "onHide"
