### ISSUE TITLE
Scrollable <p-dataTable> header does not get displayed within a <p-dialog>

### ISSUE THREAD

**Issue by ymuller** [primefaces/primeng#2758]
Bug report

**Current behavior**
When trying to add a Scrollable dataTable (scrollable=true; scrollHeight=100px) within a Dialog, the header of the DataTable does not get displayed correctly.
It works fine with a non-Scrollable dataTable. 

**Expected behavior**
The table should be displayed correctly

* **PrimeNG version:** 4.0.0 (Angular 4.1.2)

* **Browser:** all
 
* **Language:** TypeScript 2.3.2

**Comment by kumotaicho** [comment]
I have the exact same issue, the header of the table specifically gets messed up as soon as I specify the scrollable attribute.

**Comment by melocotton** [comment]
I'm also facing this problem. I had to disable scrollable attribute for now but we need it so a fix is really welcome.

**Comment by cagataycivici** [comment]
Looks good to me;

<img width="449" alt="screen shot 2017-06-29 at 12 07 48" src="https://user-images.githubusercontent.com/686247/27680181-97b55144-5cc3-11e7-9732-1f4a036e396f.png">

```xml
<p-dialog header="Godfather I" [(visible)]="display" modal="modal" [responsive]="true" [width]="400" [minWidth]="200">
        <p-dataTable [value]="cars" scrollable="true" scrollHeight="200px">
            <p-header>Vertical</p-header>
            <p-column field="vin" header="Vin"></p-column>
            <p-column field="year" header="Year"></p-column>
            <p-column field="brand" header="Brand"></p-column>
            <p-column field="color" header="Color"></p-column>
        </p-dataTable>
    </p-dialog>
```

**Comment by albus-sonitus** [comment]
Your headers may be off if you apply a table-layout style of 'auto' to the table.
