### ISSUE TITLE
Dropdown onChange fires on re-selection of same item

### ISSUE THREAD

**Issue by smitpsanghavi** [primefaces/primeng#2760]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
On re-selection of the same dropdown item, `onChange` event is fired

**Expected behavior**
`onChange` should be fired only when the selection changes. Re-selection of the same item is technically not a change.

**Minimal reproduction of the problem with instructions**
This is not needed I guess as the implementation is fairly straightforward.

**Please tell us about your environment:**
Windows 10, VS 2017, NPM v3.10.9

* **Angular version:** 4.1.1

* **PrimeNG version:** 4.0.0

* **Browser:** [all]
 
* **Language:** [TypeScript 2.3.2]

* **Node (for AoT issues):** `node --version` =   7.2.0

**Comment by sudheerj** [comment]
I can replicate the issue.The onchange event is emitted on click event of list, thats why the same item selection also causes change event fired.

**Comment by smitpsanghavi** [comment]
So is this accepted as a bug?

**Comment by smitpsanghavi** [comment]
@sudheerj Is this going to be fixed in the next release?

**Comment by cyberrranger** [comment]
#2353 (the same Problem)

**Comment by smitpsanghavi** [comment]
Bump!

**Comment by cagataycivici** [comment]
Set to 4.1.0.

**Comment by diegohoyos** [comment]
https://github.com/primefaces/primeng/issues/3392

**Comment by cagriman** [comment]
Hi,

I have still this problem while selecting same item.

Is this issue fixed, or not?

How  could i realize selecting same item?

Thanks
