### ISSUE TITLE
DataTable does not update view when source variable is modified. 

### ISSUE THREAD

**Issue by leetharris** [primefaces/primeng#2762]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
```

I can't use your Plunkr link. It's broken and doesn't properly load PrimeNG. 

**Current behavior**
In all previous versions of PrimeNG (before our Angular 4 / PrimeNG 4 upgrade), when we manipulated data in an object being used by DataTable it would immediately update. For example, I can .shift() and remove the first element of an array being used by a DataTable. 

If I inspect the object directly the row is clearly gone, but the DataTable still clearly shows the data as if nothing has changed. 

**Expected behavior**
When I manipulate a data object in the component the changes need to be displayed to the datatable. 

**Minimal reproduction of the problem with instructions**
1. Create a basic datatable that uses an array of 2 items. 
2. Use .shift() on the array to delete the first value.
3. Notice that the datatable does NOT update. 

**Please tell us about your environment:** MacOS Sierra, Chrome latest, Angular CLI 1.01

* **Angular version:** 4.1.0

* **PrimeNG version:** 4.0.0

* **Browser:** Chrome
 
* **Language:** TS

**Comment by smitpsanghavi** [comment]
Similar issues:
#2651
#2689
Cause: https://www.primefaces.org/primeng-4-0-0-rc4-released/

Basically, you need to create an entirely new array instead of making changes the original array.

**Comment by sudheerj** [comment]
As mentioned in the last thread it is due to removal of DoCheck interface.Please do the changes as mentioned.
