### ISSUE TITLE
Uncaught TypeError: Cannot read property 'draw' of null

### ISSUE THREAD

**Issue by macdojoh** [primefaces/primeng#2765]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/SoFI5YSDNTBrAmtOwVOd

**Current behavior**

Uncaught TypeError: Cannot read property 'draw' of null
    at Chart.Controller.<anonymous> (Chart.bundle.js:8605)
When setting the dataset property for a bar chart, when the UI attempts to update the view and is getting a null for the controller in chartjs.

**Expected behavior**

The UI updates with the new data in the dataset that was creating in OnInit.

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/SoFI5YSDNTBrAmtOwVOd

One thing to note, is this seems to be working in plunker but that looks to be backed by newer code for angular and primeng

**What is the motivation / use case for changing the behavior?**

Creating a chart from data from the RestFul WebService.

**Please tell us about your environment:**

Windows 10, Angular IDE, npm, included in Angular IDE

* **Angular version:** 2.0.X

2.4.0

* **PrimeNG version:** 2.0.X

2.0.6

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 

* **Node (for AoT issues):** `node --version` =

**Comment by macdojoh** [comment]
Asking the question led me to the answer finally. I was running the dataset value change in a .then call from an observable. I needed to happen in the setTimeout call for the .refresh call on the UIChart object.

**Comment by amirmohammadshokri** [comment]
retgrreg

**Comment by amirmohammadshokri** [comment]
egergerg
