### ISSUE TITLE
Dropdown - Control animation speed and easing

### ISSUE THREAD

**Issue by muhammad-saleh** [primefaces/primeng#2768]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**Current behavior**
Currently I have no control on the dropdown animation speed or easing cause it happens from code

**Expected behavior**
I expect that the animation should be done by CSS classes so I could override it and apply my own animation

**Comment by sudheerj** [comment]
The classes exists for outer container only. Are you expecting effect, effectDuration, easing and so on attributes

**Comment by msaleh-incorta** [comment]
@sudheerj Thanks for your reply, I'm talking about classes and not attributes
What I see now is these classes when animating:
`ui-dropdown-panel ui-widget-content ui-corner-all ui-helper-hidden ui-shadow ng-animating`
And what I saw was the values changing inline
Also all of these classes doesn't hold animation and easing values or am I getting something wrong ?

**Comment by cagataycivici** [comment]
Unfortunately as far as I know, Angular does not support variables in their animation api yet, correct me if I'm wrong, so we can't do the following;

```
,
    animations: [
        trigger('panelState', [
            state('hidden', style({
                opacity: 0
            })),
            state('visible', style({
                opacity: 1
            })),
            transition('visible => hidden', animate(animation)),
            transition('hidden => visible', animate('400ms ease-out'))
        ])
    ],
```

```
export class Dropdown {

       @Input() animation: string = '400ms ease-in';
```

Where animation is an attribute that can be customized but an error is given "error TS2304: Cannot find name 'animation'." So there is a technical limitation here.
