### ISSUE TITLE
AutoComplete input value not cleared on model change

### ISSUE THREAD

**Issue by Ketec** [primefaces/primeng#2778]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
If you type anything into the autocomplete input field and wont select anything or edit existing selection - you cannot clear the value by changing ngModel.
**Expected behavior**
Value updates or is cleared without selecting anything from the list.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X
4.1.2

* **PrimeNG version:** 2.0.X
4.0.0

Input should update fine if ngModel is used instead of value bind.

**Comment by ohadinho** [comment]
Same here. Changed variable that is bind to ngModel but input value doesn't change.
Can you provide a workaround ?

**Comment by sudheerj** [comment]
The issue is replicated. Please follow this issue status from this issue number https://github.com/primefaces/primeng/issues/2778

**Comment by ohadinho** [comment]
Can you write the Correct issue number??

**Comment by sudheerj** [comment]
Sorry.I updated the issue number.Thanks.

**Comment by yeahrow** [comment]
I am getting the same issue

**Comment by vangnd** [comment]
Same issue ... waiting for solution

**Comment by marcinkrajewski** [comment]
this is my workaround
http://plnkr.co/edit/lDttb5VIq8257pNIExTr?p=preview

**Comment by Ninja-Coding-Git** [comment]
nice workaround @marcinkrajewski

**Comment by photostu** [comment]
@marcinkrajewski Where does that AutoComplete type come from on L14? I tried this solution but that type was not recognized.

**Comment by marcinkrajewski** [comment]
@photostu 
localy i've added
`import {AutoComplete} from 'primeng/components/autocomplete/autocomplete';`
