### ISSUE TITLE
DataTable, if I setted headerColumnGroup, I want set body column colspan or rowspan,but attributes colspan is not working  

### ISSUE THREAD

**Issue by pumpkinp** [primefaces/primeng#2786]
# DataTable, if I setted headerColumnGroup, I want set body column colspan or rowspan,but attributes colspan is not working  

* **Angular version:** 4.0.1

* **PrimeNG version:** 4.0.0-rc2

* **Browser:** Chrome 57.0
 
* **Language:** TypeScript 2.0.0

* **Node (for AoT issues):** `node --version` =   6.10.2

**Comment by cagataycivici** [comment]
Unable to replicate probably because I don't understand your case enough, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
