### ISSUE TITLE
DeferModule is not exported

### ISSUE THREAD

**Issue by Shinzah** [primefaces/primeng#2792]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
DeferModule is not exported in main primeng exports definition

**Please tell us about your environment:**
Linux Ubuntu

* **Angular version:** 4.0.0

* **PrimeNG version:** 4.0.1

* **Browser:** [all]

 
* **Language:** [TypeScript 2.1]

**Comment by adnanel** [comment]
Will this be fixed in a 2.x.y version? The same bug applies.
