### ISSUE TITLE
Chips component clear all button

### ISSUE THREAD

**Issue by pantonis** [primefaces/primeng#2798]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/dWh4IJoFdiNDdQVMJwSE

**Current behavior**
When want to clear all chips now I have to go and delete each one 

**Expected behavior**
There should be a clear all button

**Comment by cagataycivici** [comment]
Not sure, if more users demand it we'll reconsider. Right now, it is easy though, you can clean them from your model by clearing the model array where you can bind this to a UI of your preference, like a button placed next to chips.
