### ISSUE TITLE
p-calendar ignoring defaultDate (PrimeNG 4.0.1)

### ISSUE THREAD

**Issue by SchneMa** [primefaces/primeng#2799]
[ x] bug report => Search github for a similar issue or PR before submitting

**Plunkr Case (Bug Reports)**
_http://plnkr.co/edit/xxneXT8LNq3AepsAHVjf?p=preview_

**Current behavior**
_The Calender Component just ignores the defaultDate input.
If you set the defaultDate it just stays at the actual date._

**Expected behavior**
_When I set the defaultDate it should apply the value to the Calendar._

_I wish that you can even dynamically change the defaultDate.
Lets say i got 2 Calendars to define a period and I set the start date with the first Calendar the second Calendar should have the value of the first as default in order that the user doesen't need to switch to that date manually._

_This works fine to set the minDate of the second Calendar but when I tryed to set the defaultDate nothing happend_

**Minimal reproduction of the problem with instructions**
just look at the Plunker and compare the Date under the Calendar and the date which is shown as default in the Calendar

* **PrimeNG version:** 4.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
tested the Plunker in FF and Chrome

**Comment by cagataycivici** [comment]
defaultDate is to display the month-year, to apply value use value property instead. Use case is where you have a default value but want to open calendar on another date different then value. In your case, please use ngModel instead of defaultDate.

**Comment by SchneMa** [comment]
Yeah your right in my case I can do this by setting the ngModel value.

But I rather thought of setting the displayed date when i open the Calendar than setting its value. 
I would rather prefer it when I could leave the Calendar-TextBox empty (undefined) and just setting the Date on which the calendar should open when the user clicks the box or icon.

So the User chose his startDate on the first Calendar and the second Calendar (EndDate) stays empty but when he opens the second one the Month and year from the StartDate is open.
Lets say StartDate is 04 June 2017 than the second Calendar should stay empty and on opening he should display June 2017.

Hope you can get what I'm talking off had no coffe till now... ☕️

**Comment by Ajax-ua** [comment]
You can use updateUI() method to implement default date changes
