### ISSUE TITLE
DataTable Edit on Row

### ISSUE THREAD

**Issue by meanle11** [primefaces/primeng#2800]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/dWh4IJoFdiNDdQVMJwSE

**Current behavior**

The datatable can be editable incell

**Expected behavior**

 I want to edit table on row. A good example pls. refer to
   http://www.primefaces.org/showcase/ui/data/datatable/edit.xhtml
  the first example.

because i think primefaces can edit on row with Ajax in example, it's User friendly. i hope PRIMENG Team can be integration for primeng soon. Thanks
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by sudheerj** [comment]
Please don't create duplicate threads(2 times created). The issue is already available.

https://github.com/primefaces/primeng/issues/2208
