### ISSUE TITLE
p-selectButton onFocus "ReferenceError" in Firefox

### ISSUE THREAD

**Issue by SchneMa** [primefaces/primeng#2801]
[x ] bug report => Search github for a similar issue or PR before submitting

**Plunkr Case (Bug Reports)**
instead of a Plunker:
https://www.primefaces.org/primeng/#/selectbutton

**Current behavior**
_If you click the selectButton an Error occures as you can see in the console.
It seems like the button is still working after that. (I found now advice that something is not working like it should after the Error was thrown/logged)._

**ReferenceError: event is not defined**
It seems like the Error occures in the onFocus event.
Error is shown even when that event is not used.

Tested in Firefox and Chrome
The Error occures in Firefox but not in Chrome.

**Minimal reproduction of the problem with instructions**
Go to the showcase Page (link above) and click on a selectButton while whatching to the console.

* **PrimeNG version:** Tested on  4.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
FF

**Comment by andrush001** [comment]
In selectbutton.ts there is a missing parameter:

![primngbug](https://cloud.githubusercontent.com/assets/14335021/26403286/0093993e-408e-11e7-8f1c-62fc30c06224.PNG)

**Comment by andrush001** [comment]
It looks like there is a typo in your fix @cagataycivici

**Comment by sudheerj** [comment]
It was fixed in a new commit.
