### ISSUE TITLE
Growl has a flicker effect on remove of a message from multiple messages

### ISSUE THREAD

**Issue by lekhnath** [primefaces/primeng#2805]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://www.primefaces.org/primeng/#/growl

**Current behavior**
When closing one of multiple growl messages, first all of the growl messages are removed and after that all messages are displayed excluding the closed one, which causes small but disturbing flicker effect.

**Expected behavior**

It should close/remove only the closed message and pop out that particular growl message without interfering with other innocent :)  growl messages.

**Minimal reproduction of the problem with instructions**

To reproduce just go to the [**growl**](https://www.primefaces.org/primeng/#/growl) section of primeng documentation site.  Click on the `multiple` button. Close any of the growl message manually.

**What is the motivation / use case for changing the behavior?**

Motivation is to eliminate a flicker after removing one of growl messages

**Please tell us about your environment:**

Well, it may not be important for this issue. Any.

* **Angular version:** 2.0.X

V4

* **PrimeNG version:** 2.0.X

V4.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Google Chrome and may be all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All
* **Node (for AoT issues):** `node --version` =

**Comment by SIlver--** [comment]
Here's a gif of the issue.

![animation](https://cloud.githubusercontent.com/assets/6362347/26157396/15fde1aa-3ae7-11e7-84ef-df26001f155c.gif)

**Comment by hbb520** [comment]
What time to repair life is growl ??????

**Comment by hbb520** [comment]
What time to repair life of  growl  ????
