### ISSUE TITLE
Using a <p-inputSwitch> inside a <p-dialog> throws an error in the console

### ISSUE THREAD

**Issue by kumotaicho** [primefaces/primeng#2806]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Using a **p-inputSwitch** inside a **p-dialog** prevents the dialog to be displayed and makes the following error message visible in the console:

> ERROR TypeError: Cannot read property 'offsetParent' of undefined
>     at InputSwitch.ngAfterViewChecked (inputswitch.js:43)
>     at callProviderLifecycles (core.es5.js:11142)
>     at callElementProvidersLifecycles (core.es5.js:11114)
>     at callLifecycleHooksChildrenFirst (core.es5.js:11098)
>     at checkAndUpdateView (core.es5.js:12130)
>     at callViewAction (core.es5.js:12485)
>     at execComponentViewsAction (core.es5.js:12417)
>     at checkAndUpdateView (core.es5.js:12128)
>     at callViewAction (core.es5.js:12485)
>     at execEmbeddedViewsAction (core.es5.js:12443)

The line **43** of _inputswitch.js_ being _if (this.container.offsetParent && !this.initialized) {_ which would mean that _this.container_ is undefined in that case.

It seems that this line was added to fix issue #972 which is very much alike to what I'm experiencing now (could it be some kind of regression?).

**Expected behavior**
The dialog is displayed along with its input switch.

* **Angular version:** 4.1.2

* **PrimeNG version:** 4.0.1

* **Browser:** Chrome 58.0.3029.110 (64-bit)
 
* **Language:** TypeScript 2.3.2

* **Node (for AoT issues):** `node --version` = v6.9.1

**Comment by hoisel** [comment]
Try add
` import { BrowserAnimationsModule } from '@angular/platform-browser/animations';` to your app root module.

**Comment by kumotaicho** [comment]
Thanks but I already have this line.

**Comment by cagataycivici** [comment]
Can't replicate, please provide a plunkr and we'll reopen.

**Comment by vjoshi139** [comment]
Hi every on please update primeng 4.0.2 the issue will fixed on it
