### ISSUE TITLE
Can't upload file using PUT request

### ISSUE THREAD

**Issue by jiarongxu** [primefaces/primeng#2808]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

fileUpload component always sends POST request to server.

**Expected behavior**

Add method attribute to let user uses POST or PUT

**Comment by igor-pavlichenko** [comment]
Although I'm setting method to be put
`<p-fileUpload
  ...
  [method]="'PUT'">
</p-fileUpload>`
it is still trying to send a POST request :\

**Comment by aminTiz** [comment]
Same is still happening to me. I checked the source code and figured out that calling POST method is hard coded and it doesn't use method

**Comment by olavoalvesneto** [comment]
> 
> 
> Same is still happening to me. I checked the source code and figured out that calling POST method is hard coded and it doesn't use method

how did you solve it?

**Comment by aminTiz** [comment]
I set the params like below
customUpload="true" and (uploadHandler)="myUploader($event)"

Then in myUploader method I called the put method in API request and it worked.

**Comment by aminTiz** [comment]
> > Same is still happening to me. I checked the source code and figured out that calling POST method is hard coded and it doesn't use method
> 
> how did you solve it?

I set the params like below
customUpload="true" and (uploadHandler)="myUploader($event)"

Then in myUploader method I called the put method in API request and it worked.

**Comment by olavoalvesneto** [comment]
> 
> 
> > > Same is still happening to me. I checked the source code and figured out that calling POST method is hard coded and it doesn't use method
> > 
> > 
> > how did you solve it?
> 
> I set the params like below
> customUpload="true" and (uploadHandler)="myUploader($event)"
> 
> Then in myUploader method I called the put method in API request and it worked.

please, could you send me the code for the "myUploader" method, olavoalvesneto@hotmail.com

**Comment by aminTiz** [comment]
> > > > Same is still happening to me. I checked the source code and figured out that calling POST method is hard coded and it doesn't use method
> > > 
> > > 
> > > how did you solve it?
> > 
> > 
> > I set the params like below
> > customUpload="true" and (uploadHandler)="myUploader($event)"
> > Then in myUploader method I called the put method in API request and it worked.
> 
> please, could you send me the code for the "myUploader" method, [olavoalvesneto@hotmail.com](mailto:olavoalvesneto@hotmail.com)

myUploader(event) {
event.files.map((_file) => {
this.httpClient.put(response.url, _file);
});
}
