### ISSUE TITLE
Is There Some Way To Allow The Menubar's menuitem Aligned Right With it's Parent ?

### ISSUE THREAD

**Issue by loohopen** [primefaces/primeng#2812]
![12](https://cloud.githubusercontent.com/assets/23475245/26185166/d6f5f31e-3bbb-11e7-96bb-4227e656cb04.png)
![22](https://cloud.githubusercontent.com/assets/23475245/26185175/e67fb52c-3bbb-11e7-9657-6fd52fa9baae.png)

i wanna this menuitem's panel aligned right with its parent, however , I find there's only defined  it's left in the MenubarModule, how should i do, help!

**Comment by cagataycivici** [comment]
Please use forum for questions.

**Comment by ascoril** [comment]
I am seeing the same issue, my menuitems are not aligned, nobody replies in forum, and the issues are closed here.

**Comment by MatteoMeil** [comment]
I agree with @ascoril
Find a way to do this using a bit of CSS. 
**I'm using PrimeNG v7.**

### Base workaround
To push buttons on right side maintaing order just set `text-align: right` to `p-menubar` in this way:
```html
<p-menubar [model]="menuItems" [style.textAlign]="'right'"></p-menubar>
```
then make submenu aligned to right side of root menu:
```css
p-menubarSub .ui-submenu-list {
  right: 0;
  left: initial !important;
}
```

### Extra workaround
Assuming you have a situation in which you want to push buttons on right and have some extra buttons defined this way:
```html
<p-menubar [model]="menuItems" [style.textAlign]="'right'">
  <button pButton label="My Button" icon="pi pi-check" (click)="doSomething()">
</p-menubar>
```
I suggest you to add this to your CSS:
```css
.ui-menubar-custom {
  float: left !important;
}
```
This will push extra buttons on the left side of Menubar

**Comment by TashaStenner** [comment]
Feature Request! Would love as a alignment option
