### ISSUE TITLE
dataTable add row on the fly

### ISSUE THREAD

**Issue by cyberrranger** [primefaces/primeng#2815]
[X] bug report => Search github for a similar issue or PR before submitting

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/MQ5FEOcKTMeRYf8MtBfs?p=preview

* **Angular version:** 4.0.0
* **PrimeNG version:** 4.0.1 (with 4.0.0-rc.1 my demo run)

* **Browser:** [all]
 
* **Language:** [TypeScript]

you can add a row with the blue button to the list, but in DataTable the new entry is not show

Regards

**Comment by f-teixeira** [comment]
you need to create a new list for the datatable to update

check this: http://plnkr.co/edit/YNKt89pVMsZAN4zRAnsk?p=preview

It was changed in 4.0.0-RC4: https://www.primefaces.org/primeng-4-0-0-rc4-released/

**Comment by cyberrranger** [comment]
thx is works

**Comment by smitpsanghavi** [comment]
You can close it yourself without waiting for the intervention of the devs. :)
