### ISSUE TITLE
Add positionRight and positionBottom to Dialog

### ISSUE THREAD

**Issue by mkennedy3000** [primefaces/primeng#2816]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**What is the motivation / use case for changing the behavior?**
To allow complete control over Dialog absolute positioning. (e.g. pin the dialog to the bottom or right of the screen)

**Comment by mkennedy3000** [comment]
@cagataycivici , the hope is to add even more flexibility from what #2781 provides

**Comment by cagataycivici** [comment]
It is a bit uncommon as positioning is usually top, left in box model. If more users demand it, we'll reconsider. Thank you.

**Comment by chyzhvasyl** [comment]
Yes, cause i want for example to positione

> It is a bit uncommon as positioning is usually top, left in box model. If more users demand it, we'll reconsider. Thank you.

It would be great, because for example i want to position modal box from the right side and the solution to put over [positionLeft]="9999999" is not rationally.
Thanks
