### ISSUE TITLE
Datatable width becomes not responsive if use resizable columns

### ISSUE THREAD

**Issue by annaAnt** [primefaces/primeng#2817]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Here is plnkr
http://plnkr.co/edit/kmMRdEs9VqsRrVlWuQ3z?p=preview

**Current behavior**
When I'm makin window smaller I get horizontal scrollBar

**Expected behavior**
When I'm makin window smaller I expext that table will resize too

**Minimal reproduction of the problem with instructions**
Here is example code:
<p-dataTable [value]="cars" [resizableColumns]="true">
    <p-column header="vin" field="vin"></p-column>
    <p-column header="year" field="year"></p-column>
    <p-column header="brand" field="brand"></p-column>
    <p-column header="color" field="color"></p-column>
</p-dataTable>
and screenshot
![image](https://cloud.githubusercontent.com/assets/28785773/26209989/fd04c4aa-3bf6-11e7-8329-331a90617bb1.png)

* **Angular version:** 4.0.1

* **PrimeNG version:** 4.0.1

* **Browser:** Chrome 58.0.3029.110 (64-bit)
 
* **Language:** TypeScript 2.3.2

* **Node (for AoT issues):** `node --version` =

**Comment by cyberrranger** [comment]
use responsive="true"

http://plnkr.co/edit/mq82ivvSnRqNu4B1DCGp?p=preview

**Comment by annaAnt** [comment]
unfortunately, this doesn't help
![image](https://cloud.githubusercontent.com/assets/28785773/26219126/474fda9e-3c16-11e7-88fe-2530d00d7ba3.png)

**Comment by cyberrranger** [comment]
strage...

<img width="1042" alt="screenshot 2017-05-18 21 08 29" src="https://cloud.githubusercontent.com/assets/21671762/26219196/33974972-3c0e-11e7-85cc-61ca3cb51bca.png">

**Comment by annaAnt** [comment]
you should preview window big then refresh page and after then make it smaller. Also you can see this problem on official site:
![image](https://cloud.githubusercontent.com/assets/28785773/26219324/3219affa-3c17-11e7-926e-d70a5bfff49c.png)

**Comment by cagataycivici** [comment]
I think this is expected, resizable columns get "fixed width", they will display a scrollbar to avoid overflow to support window width changes.

**Comment by brenoprata10** [comment]
This workd for me, on the styles.scss: 
#id_datatable{

  .ui-datatable {

    margin-right: -40rem !important;

  }

}

**Comment by eyeq** [comment]
resizableColumns="true"と同様にscrollable="true"でもこの問題が発生した。

td・thのwidthは、min-widthのように働くため、私は以下の方法で解決した。
`<style>
    th.responsive {
        width: 1% !important;
    }
</style>`

`<p:column styleClass="responsive"></p:column>`

IEでは、min-widthとして働かないため、ピクセル指定では上手くいかない。
Firefoxでは、0%を指定すると余白が生じた。
