### ISSUE TITLE
DataGrid does't re-render after removing an element from value array

### ISSUE THREAD

**Issue by Bangood** [primefaces/primeng#2820]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

I use PrimeNG 4.0.0, DataGrid does't re-render after removing an element from value array(the attributes 'value'). eg: valueArr.splice(index,1). But it re-render correctly if I set a new Array to it.
Additionally,  in PrimeNG 4.0.0 RC1, it does well.

* **Angular version:** 4.0.0

* **PrimeNG version:** 4.0.0

* **Browser:** [Chrome  60.0.3080.5 ]

 
* **Language:** [ TypeScrip2.2.1]

* **Node (for AoT issues):** `node --version` =   7.10

**Comment by damonwildercarr** [comment]
This is by design - please see: https://www.primefaces.org/primeng-4-0-0-rc4-released/

**Comment by Bangood** [comment]
Thanks for your help @damonwildercarr
