### ISSUE TITLE
I want to select by keyboard on radiobutton

### ISSUE THREAD

**Issue by hryktrd** [primefaces/primeng#2821]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
In normal radio button like that "<input type="radio">" can select by  left and right key on keyboard
but I can't it by p-radioButton.

Can you add this key operation ?

**Comment by upmauro** [comment]
For solve this issue we need big changes https://www.w3.org/TR/2016/WD-wai-aria-practices-1.1-20160317/examples/radio/radio.html

I need learn more about ARIA to contribute with this issue.

**Comment by hryktrd** [comment]
Thank you for your reply.

Oh, this is big problem...

Could you make this function ?

**Comment by cagataycivici** [comment]
I can't replicate it at showcase, using left right keys, I can navigate other radios as we use a hidden native radio inside to do it. Please provide a plunkr to helps us replicate.

**Comment by hryktrd** [comment]
Thank you.
sorry... I mis understand this problem.
I can select by left and right key, but it need push Shift+Tab key once.

Can you fix this to be able to select by  arrow key without Shift+Tab key ?
