### ISSUE TITLE
Add onRemove callback to FileUpload

### ISSUE THREAD

**Issue by white-cap** [primefaces/primeng#2822]
The onClear() callback at fileUpload  doesn't work for 
`div><button type="button" icon="fa-close" pButton (click)="remove(i)"></button></div>`
```
<p-fileUpload  chooseLabel="Choose a logo"  (onSelect)="onSelectLogo($event)" (onClear)="onClear()" >
</p-fileUpload>

@component....
....
public onClear() {
        console.log('trigger')
}
```
[X] feature request

**Current behavior**

it works only for cancel button 
**Expected behavior**

create a callback for this 

* **Angular version:** 4

* **PrimeNG version:** 4.0.0

**Comment by upmauro** [comment]
I can't reproduce, can you create a plunkr to help us?

**Comment by cagataycivici** [comment]
Changed PR to onRemove callback.
