### ISSUE TITLE
Treetable with Row Expansion like DataTable Row Expansion

### ISSUE THREAD

**Issue by icemanpac** [primefaces/primeng#2825]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**What is the motivation / use case for changing the behavior?**

To display extra content from a row.

* **Angular version:** 2.0.0-beta.21 

* **PrimeNG version:** 4.0.1

* **Browser:** all

**Comment by cagataycivici** [comment]
Not sure how it fits in TreeTable as it will be a confusing UI since treenode also expand children, if more users demand it, we'll reconsider.

**Comment by begogna** [comment]
Hello,
did someone find a way to have this feature ? or a workaround ?
I have a TreeTable with several columns but in expansion I want to see the description in just one column.
If rowexpansion will not be available in TreeTable I was thinking of using a child node with column grouping, but maybe there is a better solution.

Thanks in advance for your ideas,
Begoña
