### ISSUE TITLE
Calendar displayed value not updated on blur

### ISSUE THREAD

**Issue by saithis** [primefaces/primeng#2826]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Counldn't get the p-calendar to work in plunkr at all, but the bug is also in your demo page:
https://www.primefaces.org/primeng/#/calendar

**Current behavior**
When you type something that isnt a date like 'asdf' into an empty p-calendar and press tab (or click somewhere else, so the p-calendar input looses focus), then the input isn't cleared.

**Expected behavior**
The clearing of the input should work. 

**Minimal reproduction of the problem with instructions**
1. open https://www.primefaces.org/primeng/#/calendar
2. type 'asdf' into the Basic p-calendar (the p-calendar mustn't have a value selected before doing this)
3. hit tab
4. 'asdf' doesn't get cleared, as inputFieldValue didn't change

**What is the motivation / use case for changing the behavior?**
Because it is a bug. Also with the ultima layout the label will then be over the typed in text.

* **Angular version:** 2.4.X and 4.0.X

* **PrimeNG version:** 2.0.5 and the one on your demo page

**Comment by cagataycivici** [comment]
Review for 4.1.0.
