### ISSUE TITLE
Update valid state of calendar on input and blur

### ISSUE THREAD

**Issue by saithis** [primefaces/primeng#2828]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Counldn't get the p-calendar to work in plunkr at all, but the bug is also in your demo page:
https://www.primefaces.org/primeng/#/calendar

**Current behavior**
When you type something that isnt a date like 'asdf' into a p-calendar that has a date set and press tab (or click somewhere else, so the p-calendar input looses focus), then the input is cleared, but it is still invalid (_isValid = false).

**Expected behavior**
The control should be valid when it is cleared on blur. 

**Minimal reproduction of the problem with instructions**
1. open https://www.primefaces.org/primeng/#/calendar
2. select a date in the Basic p-calendar 
3. type 'asdf' into it
3. hit tab
4. if you inspect the p-calendar in the dev tools, then your see that it has the ng-invalid class

**What is the motivation / use case for changing the behavior?**
Because it is a bug.

* **Angular version:** 2.4.X and 4.0.X

* **PrimeNG version:** 2.0.5 and the one on your demo page

**Comment by Justabug** [comment]
Moreover, _isValid should be updated on any value change (for example, in the writeValue method)

**Comment by kairauer** [comment]
Is there a workaround for this? We need to be able to send "null" value for the date. This works if the calendar field is untouched. If you select a date and remove the date (clear input) afterwards, the field is marked as invalid.

**Comment by yigitfindikli** [comment]
Unable to replicate with latest PrimeNG, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
