### ISSUE TITLE
Font for label and items in multiselect seems to be little blur & bold

### ISSUE THREAD

**Issue by ankitgada** [primefaces/primeng#2831]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

Check out the plunkr here :
http://plnkr.co/edit/fi8JrQtjZrUUsLDy1j6J?p=preview

**Current behavior**
The font seems bolder than usual and looks blurry. I tried updating the font using CSS but nothing changes the font. I compared it to the regular dropdown from primeng and the font there is normal.

**Expected behavior**
The font styling should be consistent across all the controls and should be sharp

**Minimal reproduction of the problem with instructions**
Plunkr is attached

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
VS code . 

* **Angular version:** 2.0.X
4.0.3

* **PrimeNG version:** 2.0.X
4.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by sudheerj** [comment]
I can't see font issue with showcase example of multiselect. Can you check there. The default label will be sharp after active state.

**Comment by ankitgada** [comment]
I checked on the primeNG example page but that styling and the one on my plunkr is totally different. check it out : 
PrimeNG : https://www.primefaces.org/primeng/#/multiselect
My Plunkr : http://plnkr.co/edit/fi8JrQtjZrUUsLDy1j6J?p=preview

**Comment by cagataycivici** [comment]
Try;

```
    -webkit-font-smoothing: antialiased;
```

**Comment by MattLangleyUK** [comment]
Just had this myself. Basically it's an interaction with Bootstrap. I think a quick bit of styling or more consistent HTML across components should be considered to help this, as Bootstrap is so common.

Bootstrap applies bold to the Label element, and MultiSelect doesn't override this in it's own CSS classes. Other controls (well, DropDown, atleast) do specify the font weight in the .ui-dropdown .ui-dropdown-label and .normal.ui-inputtext classes. Also, DropDown doesn't use the Label element in it's list items, so there is an inconsistency between the two which could probably be resolved for more consistent styling.

(BTW, 'font-weight' in the Style property doesn't seem to work for MultiSelect, although other style options do. )

The following CSS counters the Bootstrap label styling which causes the inconsistency, specifically for the multiselect component:

label.ui-multiselect-label.ui-corner-all {
    font-weight: normal;
    margin-bottom: auto;
  }

li.ui-multiselect-item.ui-corner-all label {
  font-weight: normal;
  margin-bottom: auto;
}

This might be worth adding to the project?

**Comment by AnthonyLzq** [comment]
> Just had this myself. Basically it's an interaction with Bootstrap. I think a quick bit of styling or more consistent HTML across components should be considered to help this, as Bootstrap is so common.
> 
> Bootstrap applies bold to the Label element, and MultiSelect doesn't override this in it's own CSS classes. Other controls (well, DropDown, atleast) do specify the font weight in the .ui-dropdown .ui-dropdown-label and .normal.ui-inputtext classes. Also, DropDown doesn't use the Label element in it's list items, so there is an inconsistency between the two which could probably be resolved for more consistent styling.
> 
> (BTW, 'font-weight' in the Style property doesn't seem to work for MultiSelect, although other style options do. )
> 
> The following CSS counters the Bootstrap label styling which causes the inconsistency, specifically for the multiselect component:
> 
> label.ui-multiselect-label.ui-corner-all {
> font-weight: normal;
> margin-bottom: auto;
> }
> 
> li.ui-multiselect-item.ui-corner-all label {
> font-weight: normal;
> margin-bottom: auto;
> }
> 
> This might be worth adding to the project?

For those who may have the same problem, this may fix it. At least in my case it worked.
