### ISSUE TITLE
Submiting editing in DataTable cell after hittting Enter

### ISSUE THREAD

**Issue by javagose** [primefaces/primeng#2832]
Hello, 

I'm trying to rise an event after editing a DataTable cell on an input. 

I look around in documentation, i didn't find any usefull trick.

Example could be found [here ](http://www.primefaces.org/showcase/ui/data/datatable/edit.xhtml).

**Angular version**: 4.0.0
**PrimeNG version**: 4.0.0-rc.2

**Comment by sudheerj** [comment]
There is onEditComplete callback which will be triggered through Enter key once the edit is completed

Please check events section https://www.primefaces.org/primeng/#/datatable
