### ISSUE TITLE
Add style and styleClass to TriStateCheckbox

### ISSUE THREAD

**Issue by sudheerj** [primefaces/primeng#2836]
Both style and styleClass attributes will be helpful for customizing the checkbox display

https://github.com/primefaces/primeng/pull/2835

**Comment by cagataycivici** [comment]
Will apply them to outmost element.

**Comment by sudheerj** [comment]
I applied to inner DIV considering one user request on customizing background-color property. The background color won't be inherited to nested DIVs. Anyway it should be applied for outmost element only.The background-color customized  through additional properties.Thanks.
