### ISSUE TITLE
routerLinkActiveOptions property for MenuItem api

### ISSUE THREAD

**Issue by ph55** [primefaces/primeng#2838]
**I'm submitting a ...**  (check one with "x")
```
[X ] feature request
```

**Current behavior**

The RouterLinkActive directive toggles css classes for active RouterLinks based on the current RouterState. This cascades down through each level of the route tree, so parent and child router links can be active at the same time.

**Expected behavior**

To override this behavior, you can bind to the [routerLinkActiveOptions] input binding with the { exact: true } expression. By using { exact: true }, a given RouterLink will only be active if its URL is an exact match to the current URL:

```
[routerLinkActiveOptions]="{exact:true}"
```

[anglar docs](https://angular.io/docs/ts/latest/guide/router.html#!#router-link-active)

**Comment by elega9t** [comment]
Please, angular issue https://github.com/angular/angular/issues/8397 requires this feature for correctly activating menu items.
