### ISSUE TITLE
DataTables multiple selection without CTRL key

### ISSUE THREAD

**Issue by RicardoVaranda** [primefaces/primeng#284]
Is there currently a way to enable multiple selection on a data table without the use of a meta key or ctrl key?

If not can someone please point out where the prototype for the row selection is?

**Comment by cagataycivici** [comment]
No, as it is based on file system behavior where you need a key to multi select.

**Comment by RicardoVaranda** [comment]
I got that part but where would I have to go to change  this behavior? I've been looking at the node_modules files for primeng and can't seem to find anything related to selections.

**Comment by RicardoVaranda** [comment]
I've created a new pull request to address this issue, please take a look at it here:

[https://github.com/primefaces/primeng/pull/287/commits](url)

**Comment by cagataycivici** [comment]
Thank you for the pr after discussion, we've decided to wait for more user requests of this same requirement to proceed.

**Comment by rahuja910** [comment]
Will this feature be out with Beta-9?
