### ISSUE TITLE
ngAfterContentChecked trigger so much times in datatable component

### ISSUE THREAD

**Issue by giscafer** [primefaces/primeng#2842]
see the screenshot

![grid](https://cloud.githubusercontent.com/assets/8676711/26297178/58e3d5c6-3f04-11e7-9d33-3e6d8fa3aa90.gif)

in my component ,ngAfterContentChecked() is below：
```js


   ngAfterContentChecked(): void {
       console.log('11111ngAfterContentChecked11111111')
    }
```

when the mouseenter the table or select the row， it trigger many times the `AfterContentChecked` lifecircle

**Comment by cagataycivici** [comment]
What is your version?

**Comment by giscafer** [comment]
@cagataycivici the latest version PrimeNG 4.0.1

**Comment by cagataycivici** [comment]
Weird, I can't replicate it, please provide a plunkr and we'll review again. Closing for now.
