### ISSUE TITLE
PrimEng datatable is not being updated when model is changed.

### ISSUE THREAD

**Issue by mateuszs** [primefaces/primeng#2843]
**I'm submitting a **bug report**
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

http://plnkr.co/edit/OB5pG6O6nsjwgqCXA4tv?p=preview

**Current behavior**
When I update model,  p-datatable view is not updated how it was in Angular 2 and PrimEng 2. But as you can see in plunkr, ul list with *ngFor is updated properly so it may be a bug in primeng library. This is new issue which was not present on older primeng and angular.

**Expected behavior**
In plunkr, when button is clicked, row should be added to table

**Minimal reproduction of the problem with instructions**
Just click on button "Add"

**What is the motivation / use case for changing the behavior?**
?

**Please tell us about your environment:**
Windows 7

* **Angular version:**
Angular 4.0.0

* **PrimeNG version:** 
PrimEng 4.0.0

* **Browser:** 
Google Chrome, Firefox
 
Package.json

```
{
  "name": "scpet",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.1.3",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.26",
    "core-js": "^2.4.1",
    "primeng": "^4.0.1",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.0.4",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
  }
}
```

**Comment by f-teixeira** [comment]
you need to create a new array for the datatable to be updated, check this plunkr:
http://plnkr.co/edit/gdNZDHDEUuRLmIKUWmfx?p=preview

**Comment by sudheerj** [comment]
Please read this blog on changes required https://www.primefaces.org/primeng-4-0-0-rc4-released/

**Comment by mateuszs** [comment]
@f-teixeira @sudheerj  ehh, I do not understand why ngDoCheck was removed. It is a step back. So what is the most elegant method to add and remove element from array (equivalent of push/slice)?

**Comment by f-teixeira** [comment]
it was removed for performance reasons.

for push you can use list = [ ...list, newElement ]

slice already returns a new array so you can use it
