### ISSUE TITLE
No change detection (if Dropdown value is changed with keyboard down arrow key)

### ISSUE THREAD

**Issue by burhanyldz** [primefaces/primeng#2845]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
```
**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/m1H88j8un6R6HgFiAXgX?p=preview

**Current behavior**
If navigate and focus the dropdown using the keyboard TAB key (while it is untouched and displaying the placeholder), if down arrow key is used to change the dropdown value, the first change is not detected. It works if dropdown is changed with mouse click.

**Expected behavior**
It should detect the first change from the default value (null) while using keyboard to navigate through the form as with mouse.

**Minimal reproduction of the problem with instructions**
Focus the dummy input, press TAB button and change dropdown option with down arrow key.

**Please tell us about your environment:**
plunkr

* **Angular version:** 2.0.X
4.0.0

* **PrimeNG version:** 2.0.X
4.0.1

**Comment by Christhecoleman** [comment]
I also have encountered this issue

**Comment by bnazare** [comment]
I'm encountering this issue too. Also, I would like to add that it affects validation.
Say you have a dropdown marked as required, the first selection with keyboard will keep the field (and hence the form) as invalid.

**Comment by Christhecoleman** [comment]
Upgraded to primeng: 4.1.0-rc3 to see if the issue had been resolved, it's now worse as no value is selected if you tab into the dropdown list now reverted back to 4.0.0 where it works, also tooltip text is no longer displaying either

**Comment by cagataycivici** [comment]
Fixed via 3481
