### ISSUE TITLE
ng-autocomplete (select) event not triggered correctly in safari

### ISSUE THREAD

**Issue by Nielsb85** [primefaces/primeng#2847]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/GI2z9NBEAqUor1eT9dWH?p=preview

**Current behavior**
In safari when you search an item and click on the item, it wont trigger the (select) event. it will display the selected item in the input field. when you right click on it, it will trigger the (select)

**Expected behavior**
When you search for an item, and click it, it should trigger the (select) event with the left mouse button just as in CHROME. 

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
I want to add selected items to a different list when clicking on it and triggering the (select) event.

**Please tell us about your environment:**
macSierra

* **Angular version:** 2.0.X
2.0.4

* **PrimeNG version:** 2.0.X
4.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Safari

 Typescript
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by davisb10** [comment]
@Nielsb85 In the Plunkr you have the following code:
```html
   <p-autoComplete    (select)="add($event)"
                    [(ngModel)]="selected" field="value" [suggestions]="searchResults"
                    (completeMethod)="searchItems($event)">
    </p-autoComplete>
```
However the binding to the event is (onSelect)="..." not (select)="...". 
The use of (select)="..." in Chrome works but Safari might be more selective.

**Comment by Nielsb85** [comment]
@davisb10 that fixed it indeed.
