### ISSUE TITLE
behavior of p-listbox in multiple mode 

### ISSUE THREAD

**Issue by ASK83** [primefaces/primeng#2848]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
The problem can be viewed at [https://www.primefaces.org/primeng/#/listbox](url) 
under Advanced (Multiple, Checkbox and Filter).

**Current behavior**
In the multiple mode (multiple="true") in ListboxModule the user has to click on the checkbox to add values to the list, and clicking on the item itself clears up the list and selects just the clicked on. 

**Expected behavior**
Clicking on the item as well as clicking the checkboxes should select the item and add them to the list like the way the p-multiselect works.

**What is the motivation / use case for changing the behavior?**
Better user experience, the user expects that clicking on the row should add the item to its selection not just the checkbox. Because the styling shows and confirms such behavior. 

* **Angular version:** 4.1.2

* **PrimeNG version:** 4.0.1

* **Browser:** [all ]
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
You may change this behavior with [metaKeySelection]="false"

**Comment by ASK83** [comment]
Thanks a lot I missed that flag.
