### ISSUE TITLE
Datatable Export csv - field.indexOf is not a function

### ISSUE THREAD

**Issue by Benny739** [primefaces/primeng#2851]
Hi,

in primeng 4.0.1 I get the following error, when I try to export a csv from the datatables component:
TypeError: field.indexOf is not a function
    at DataTable.resolveFieldData (datatable.js:536)
    at datatable.js:1507
    at Array.forEach (<anonymous>)
    at DataTable.exportCSV (datatable.js:1503)

Reagrds
Benny

**Comment by upmauro** [comment]
can you create plunkr to reproduce this error?

**Comment by sudheerj** [comment]
I can't replicate the issue with showcase example. You might have defined dataTable in a different way. So please provide plunker example to replicate the issue.

**Comment by cagataycivici** [comment]
Can't replicate, please drop a comment when you have the plunkr.
