### ISSUE TITLE
Multiselect defaultValueLabel doesn't charge after translate

### ISSUE THREAD

**Issue by jalorente** [primefaces/primeng#2857]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report 
[x ] feature request 
[ ] support request
```

**Code**
HTML
```
<p-multiSelect [options]="languageDropdownModel"	[defaultLabel]="languageText"
[(ngModel)]="selectedLanguage" name="selectedLanguage">	</p-multiSelect>
```
TS
```
import { MultiSelectModule } from 'primeng/primeng';
.
.//class declarations and var assignment
.
public languageText: string;
ngOnInit() {
        this.translate.get(['CHOOSE_LANGUAGE']).toPromise().then((translation) =>{
				this.languageText = translation['CHOOSE_LANGUAGE'];
		});
	}
this.Service.getProfile().subscribe((user) => {
	this.userProfile=user;
        this.apiService.getLanguages(this.userProfile.language)
		.then((arrayLanguages: Array<Language>)=>{
		 this.languageDropdownModel =this.createDropDownListModel(arrayLanguages, "descripcion","codigo");                                       
		}).catch((error )=>{
			this.showError.message(error);
		});
});
```
**Current behavior**
The var languageText fills with a translated value depending of the user language. When i try to change the defaultLabel value with the translated value, the default value doesn't change. If i select a value and then deselect it, the default value magically appears but on init not.(¿?) 

**Expected behavior**
I try to change the defaultValueString  with a translated string (I use TranslateService  from ngx-translate/core)

**Minimal reproduction of the problem with instructions**
The var languageText fills with a translated value depending of the user language. When i try to change the defaultLabel value with the translated value, the default value doesn't charge (it appears empty and the ng-reflect-default-label have the correct value). If i fill the language text value with my own string (like "Choose one") it charges without problem. It happens when the app inits only, not when the component update

**What is the motivation / use case for changing the behavior?**
I need to do a multilanguage app with this kind of component

**Please tell us about your environment:**

* **Angular version:** 4.0.1

* **PrimeNG version:** 4.0.1

* **Browser:** all
 
* **Language:**  TypeScript 2.2.2 

* **Node (for AoT issues):** `node --version` = 6.9.5

**Comment by cagataycivici** [comment]
Should be fixed via #725
