### ISSUE TITLE
alwaysShowPaginator property for Paginator

### ISSUE THREAD

**Issue by Jonatino** [primefaces/primeng#2858]
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap

**Current behavior**
Currently pagination will always show no matter how many pages you actually have.

**Expected behavior**
It would be nice to hide the pagination buttons if there is only 1 page.

**Please tell us about your environment:**
Windows 10, Chrome

* **Angular version:** 2.0.X
2.4.0

* **PrimeNG version:** 2.0.X
2.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All

**Comment by sudheerj** [comment]
You are right. It should display only when there are more than one page. This is how it works in PrimeFaces

**Comment by cagataycivici** [comment]
Added alwaysShowPaginator to DataTable, DataGrid and DataList, same as in PrimeFaces.
