### ISSUE TITLE
Header template for Listbox

### ISSUE THREAD

**Issue by daleclements** [primefaces/primeng#2861]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Right now, if you have a Listbox with checkable options but no need for filtering, you still get a header with a "select all" checkbox and a blank area where the filter control would be.
![image](https://cloud.githubusercontent.com/assets/3041062/26376849/0312363c-3fdc-11e7-914e-9fd4de280a9d.png)

**Expected behavior**
It would be great if we could use attributes to specify whether to show the header and all-checkbox  and to be able to specify a value like title or button to put inside that space instead of the filter.

**What is the motivation / use case for changing the behavior?**

I can hide the header with some css in my component.css
`>>> .ui-listbox-header {
    display: none;
}`
but the other point is harder to accomplish. I'd have to break separation of concerns between component/view by programatically modifying the HTML and/or DOM in my component.ts if I wanted to accomplish something like this:
![image](https://cloud.githubusercontent.com/assets/3041062/26377401/15bc4438-3fde-11e7-9fda-bb4ab2170621.png)

**Comment by dhniels** [comment]
one thing i would add to this feature request - it would be nice to have the search box at the top (when you set filter to true) be fixed position so that it doesnt disappear when scrolling through a set height list box. does that make sense? should i create a separate issue/feature request?

**Comment by leopardy** [comment]
Posting this for anyone who might land here looking for a solution.
I don't know if this has been fixed in later versions but I'm in primeng 4.0.3 and the only way I got rid of it was to hide the header area
:host /deep/ .ui-listbox .ui-listbox-header {
    border-top: 0 none;
    border-right: 0 none;
    border-left: 0 none;
    border-radius: 0;
    margin-bottom: 0;
    padding: 0;
    visibility: hidden;
    height: 0;
}

**Comment by OskarsPakers** [comment]
For those who want to use multiple selections with checkbox, but don't want to have a header, can use `[showToggleAll]="false"`.
Header template is already supported and documented in https://primefaces.org/primeng/showcase/#/listbox section "Custom Content"

**Comment by yigitfindikli** [comment]
Unable to replicate with latest PrimeNG, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
