### ISSUE TITLE
last of selected day is not coloured at Schedule

### ISSUE THREAD

**Issue by hryktrd** [primefaces/primeng#2863]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/VZbdZfQ7SuTV87tTkbYR?p=preview

**Current behavior**

I use p-schedule, input start and end date.
For example, when I input 2017-05-20(start) and 2017-05-24(end), calendar's cells are colored from  2017-05-20 to 2017-05-23.
I want to be colored to 2017-05-24.

Can you fix it ?

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

2.4.0

* **PrimeNG version:** 2.0.X

4.0.1
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
This is the expected behavior of fullcalendar;

https://stackoverflow.com/questions/27407052/fullcalendar-end-date-wrong-by-one-day
