### ISSUE TITLE
Checkbox should support null/undefined model

### ISSUE THREAD

**Issue by mateuszs** [primefaces/primeng#2864]
**I'm submitting a ...** 
```
[ x  ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/PPIk2sjGNI9EyGhdkA9e?p=preview

**Current behavior**
I want to create a simple checkbox with my own event handler - just run method when checkbox is clicked but it generates error:

> Checkbox.html:7 ERROR TypeError: Cannot read property 'concat' of undefined
>     at Checkbox.addValue (checkbox.ts:106)
>     at Checkbox.updateModel (checkbox.ts:76)
>     at Checkbox.onClick (checkbox.ts:66)
>     at Object.eval [as handleEvent] (Checkbox.html:7)
>     at handleEvent (view.ts:140)
>     at callWithDebugContext (services.ts:645)
>     at Object.debugHandleEvent [as handleEvent] (services.ts:241)
>     at dispatchEvent (util.ts:173)
>     at eval (element.ts:221)
>     at HTMLDivElement.eval (dom_renderer.ts:75)
>     at ZoneDelegate.invokeTask (zone.js@0.8.4?main=browser:398)
>     at Object.onInvokeTask (ng_zone.ts:253)
>     at ZoneDelegate.invokeTask (zone.js@0.8.4?main=browser:397)
>     at Zone.runTask (zone.js@0.8.4?main=browser:165)
>     at HTMLDivElement.ZoneTask.invoke (zone.js@0.8.4?main=browser:460)

**Expected behavior**
It should not fail.

**Minimal reproduction of the problem with instructions**
Click on checkbox and watch console log

**Please tell us about your environment:**
Windows 7

* **Angular version:** 2.0.X
4.0.0

* **PrimeNG version:** 2.0.X
4.0.1

* **Browser:**
Chrome

**Comment by sudheerj** [comment]
This is because you didn't define model or value for default multi checkbox behavior
https://github.com/primefaces/primeng/pull/2870

**Comment by mateuszs** [comment]
@sudheerj  with attribute "value" the issue persists. I do not need ngModel for this because I am going to use onChange(). ngModel should be optional in this case.

**Comment by sudheerj** [comment]
Yeah, it won't depend on value setting. The PR will give clear distinction between single and multi checkbox

**Comment by codedumper** [comment]
Will it solve the same issue in ReactiveForm ? 
              <p-checkbox formControlName="is_911_passthrough"></p-checkbox>
generate the same error (formControl is existing).

**Comment by cagataycivici** [comment]
I believe so.
