### ISSUE TITLE
Customizable panel toggle icon

### ISSUE THREAD

**Issue by Korozu** [primefaces/primeng#2865]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Toggle Icon in a panel is not customizable.

**Expected behavior**
Customize toggle icon.

**What is the motivation / use case for changing the behavior?**
I would like to be able to customize the toggle icon on a panel.
I added a "+" button in the panel's header I use and it can be ambiguous.

**Comment by sudheerj** [comment]
But any other font-awesome icons won't suite for panel expansion and collapsed behavior. Anyway we can have icon(or toggleIcon) property similar to other components

**Comment by Korozu** [comment]
I think the chevron-up/chevron-down icons would be better in the project i'm working on, that's why i'm asking for this customizable feature.
