### ISSUE TITLE
Calendar TimeOnly doesn't display PM

### ISSUE THREAD

**Issue by EugeneBugor** [primefaces/primeng#2867]
AM/PM switch invokes only on hours step from 12 to 01. The rest steps **display** only AM.
My version of primeNG is 4.0.1.

Test it out here:
http://plnkr.co/edit/3YB877?p=preview

**Comment by sudheerj** [comment]
#2869

**Comment by cagataycivici** [comment]
Fixed via PR above.

**Comment by rich4756** [comment]
@sudheerj Tested on 4.2.1, same issue is present.

```
            <p-calendar [showTime]="true" [hourFormat]="12" [(ngModel)]="startDate" placeholder="Start Date" [minDate]="oneYearAgo" [maxDate]="today"
                [showIcon]="true" [readonlyInput]="true"></p-calendar>
```

Can we reopen?
