### ISSUE TITLE
P-dialog positionTop and positionLeft not working without each other

### ISSUE THREAD

**Issue by VagrantAI-c** [primefaces/primeng#2871]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

https://github.com/primefaces/primeng/blob/master/components/dialog/dialog.ts#L156
Dialog changes its position only if both positionTop and positionLeft are present

**Expected behavior**
I want only to bind positionTop or positionLeft for dialog position to take effect, not both

* **PrimeNG version:**
4.0.1

**Comment by sudheerj** [comment]
Yes, both properties must exist to customize a dialog position. AFAIK, this constraint is added because each element is posited based on Top,Left properties in the viewport.

**Comment by VagrantAI-c** [comment]
But aren't there some default values? What if I only want to change top value, and left is going to be default?

**Comment by cagataycivici** [comment]
Default is center which is calculated.
