### ISSUE TITLE
Calendar error with "getDate" function

### ISSUE THREAD

**Issue by pbonadero** [primefaces/primeng#2873]
primeng: 1.1.2
app: Angular4, webpack

If I change the version for the primeng 4.0.1, I getting the issue #2872 

Thanks,
Regards.

**Comment by sudheerj** [comment]
Please provide all details including plunker example as mentioned in github issue template.Otherwise the issue is treated as invalid.

**Comment by cagataycivici** [comment]
Please create a plunkr and we'll review again.
