### ISSUE TITLE
datatable colspan 

### ISSUE THREAD

**Issue by jiangyaqi2** [primefaces/primeng#2877]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

_
![qq20170525-0](https://cloud.githubusercontent.com/assets/21173134/26433212/cc5d9fec-4133-11e7-82d3-7de2c10346b7.jpg)
http://plnkr.co/edit/VZbdZfQ7SuTV87tTkbYR?p=preview_

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.0.1

* **PrimeNG version:** 4.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by sudheerj** [comment]
Please edit your issue with all required fields such as description, expected behavior,current behavior and so on. Otherwise there is no clue to find what you are expecting.

**Comment by cagataycivici** [comment]
This is not a valid issue report, please follow guidelines.
