### ISSUE TITLE
Cannot install latest git version.

### ISSUE THREAD

**Issue by DDevine** [primefaces/primeng#288]
I need compatibility with Angular 2.0.0-beta.17 so I am trying to install the latest version (primeng@1.0.0-beta.4-SNAPSHOT at git commit 9292017) of primeng which is apparently compatible.

However when I try to install with:
```
npm install @primefaces/primeng
or 
npm install git+https://github.com/primefaces/primeng.git
```
I end up with a node_modules/primefaces directory that only has:
```
LICENSE.md  package.json  README.md
```

And when I install with:
```
git clone https://github.com/primefaces/primeng.git
npm install primeng/
npm install # this runs typings in my project
```
I end up with:
```
components  LICENSE.md  package.json  primeng.js  primeng.js.map  README.md
```
However this is lacking typescript files and typings so I can't use it in my project.

I am not sure if this is a bug or my incompetence. Help would be greatly appreciated.

**Comment by cagataycivici** [comment]
Try replacing peerDependencies at package.json with;

`
  "dependencies": {
    "angular2": "2.0.0-beta.17",
    "systemjs": "0.19.26",
    "es6-shim": "^0.35.0",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "0.6.12"
    "primeui": "4.1.8"
  },
`

We'll release beta on monday by the way.

**Comment by DDevine** [comment]
Thanks.
