### ISSUE TITLE
AutoComplete input does not reflect model changes

### ISSUE THREAD

**Issue by ChrisA9** [primefaces/primeng#2882]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/r7DnQw?p=info

**Current behavior**
Text does not clear from autocomplete box

**Expected behavior**
Text should clear from autocomplete box

**Please tell us about your environment:**
OS : WIndows 7

* **Angular version:** 4.0.3
* **PrimeNG version:** 4.0.1

* **Browser:** Chrome 58.0.3029.110 (64-bit),

**Comment by sudheerj** [comment]
https://github.com/primefaces/primeng/issues/2778

**Comment by ohadinho** [comment]
I've installed 4.0.2 but this bug is still there. I'm changing a variable that has a two way binding to a model but the change doesn't reflect the text box value.

**Comment by ohadinho** [comment]
The issue occurs after selecting a value from the dropdown and trying to change it on OnSelect event handler

**Comment by sudheerj** [comment]
@ohadinho I can't replicate the issue. The value is reflected after button clear using both single and multiple features.

**Comment by ohadinho** [comment]
Steps to replicate:
1. Press the arrow to open the dropdown
2. Choose a value
3. Debug "OnSelect" method and change the ngModel variable value.

Expected Result: Value is the same as you defined after the change on
OnSelect method.

Actual Result:
The change in variable binded to ngModel didn't affect the input text.

**Comment by thirumalai-kc** [comment]
<p-autoComplete placeholder="Start typing name to see suggestions" formControlName="customerRequest" [suggestions]="customerResults" (completeMethod)="searchCustomer('customer_name', $event.query)" minLength="3" field="accountName" (onSelect)="setCustomerRequest($event)">

Start type 'abc'
Do not choose a value from the option
Perform clear (Here setting customerRequest to null)

Result: customerRequest (model) set to null but the field is not cleared/reset.

Expected: Field should be reset to null.

If I select some value from the option and clear, field is reset to null. Please address this issue.

**Comment by macleanpinto** [comment]
Issue exists in 4.1.2 as well

**Comment by iblank** [comment]
I noticed that p-autoComplete expects the model to be type object in the template. If the value is a string, the resolveFieldData method returns undefined, which sets the input value to an empty string.

Changing this fixes it for me:
```
[value]=\"value ? (field ? objectUtils.resolveFieldData(value,field)||'': value) : null\"
```
To:
```
[value]=\"value ? objectUtils.resolveFieldData(value,field)||value : null\"
```
Alternatively adding this at the top of the resolveFieldData method works as well (and is probably the safer way to handle it):
```
if (typeof data === 'string') {
    return data;
}
```

**Comment by metacoding** [comment]
The problem still exists, why did you close the issue?

**Comment by billfranklin** [comment]
@iblank works for me....please make this change

**Comment by photostu** [comment]
Still broken, wanting to clear the control when a selection is made... I null out the bound model and the suggestions list onSelect within a setTimeout even... when you click elsewhere on the screen, it does clear out

**Comment by billfranklin** [comment]
Status of this fix?

**Comment by MatteoMeil** [comment]
Found a possiblle workaround.
Check out [this comment](https://github.com/primefaces/primeng/issues/3641#issuecomment-518023181)

**Comment by DipankarDDUT** [comment]
Another approach :

Create a template variable suppose 
  @ViewChild('station', { static: true }) stationDrpdown: ElementRef;

in autoComplete tag  #station
 (onSelect)="onStationSelection($event)"


onStationSelection(station){
....

  this.stationDrpdown['inputFieldValue']=station.name;
...
}
