### ISSUE TITLE
Change acceptLabel dynamically for ConfirmDialog.

### ISSUE THREAD

**Issue by katsuragi545** [primefaces/primeng#2885]
I'm submitting a bug report that occurs when changing the acceptLabel of a ConfirmDialog. 

I'm trying to dynamically change the acceptLabel of a ConfirmDialog. The 'acceptLabel' is "Yes" by default and I would like to change it to "OK". This works fine when binding the 'acceptLabel' value in html to a value in TypeScript, but the "OK" button text appears behind "Yes". In other words, "Yes" stays on the button no matter what. 

Here is the html code:

`<p-confirmDialog width="425" [closable]="false" acceptLabel={{acceptLabel}}></p-confirmDialog>`

Here is a screenshot of the [issue:](http://imgur.com/a/0Bvgt)

**Comment by katsuragi545** [comment]
Figured it out. I was using a real old version of PrimeNG. Update it and it should work.

**Comment by MiRush94** [comment]
Which version fixed it for you? I can't get it to work unfortunately
