### ISSUE TITLE
Datatable Templating not working

### ISSUE THREAD

**Issue by RicardoVaranda** [primefaces/primeng#289]
Applying a template to a certain row does not seem to be functioning as stated.

```
<p-dataTable [value]="users" selectionMode="multipleNoMeta" [(selection)]="selectedUsers">
    <header>Multiple Selection</header>
    <p-column field="name" header="Name"></p-column>
    <p-column field="accountExpiry" header="Account Expiry">
        <template #col #user="rowData">
            <span [style.color]="blue">{{user[col.field]}}</span>
        </template>
    </p-column>
    <p-column field="passwordExpiry" header="Password Expiry"></p-column>
    <p-column field="accountLocked" header="Locked"></p-column>
    <p-column field="status" header="Status"></p-column>
</p-dataTable>
```

I have also tried with the multiple and single selection mode with no luck in both cases.

I have inspected the source code and see the following for that particular row:

```
<span class="ui-cell-data">
            <p-columntemplateloader></p-columntemplateloader>
            <span>10/10/2010</span>
</span>
```

It seems to create a columtemplateloader but loads nothing into it.

**Comment by cagataycivici** [comment]
What are your Angular2, PrimeNG versions?

**Comment by RicardoVaranda** [comment]
@cagataycivici I'm using:

"angular2": "2.0.0-beta.15",
"primeng": "^1.0.0-beta.3",
"primeui": "4.1.8",

**Comment by RicardoVaranda** [comment]
Updating to latest 

"angular2": "2.0.0-beta.17",
"primeng": "^1.0.0-beta.4",

Seems to have fixed it but its weird how it didnt on previous versions did you change templating recently?

**Comment by cagataycivici** [comment]
I'm not sure really, for the past few weeks there had been many changes to Angular2.
