### ISSUE TITLE
Resizable Columns issue with fixed width columns

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#2891]
When the column widths are defined in pixels, resizing does not work correctly like;

```
    <p-dataTable [value]="cars" resizableColumns="true">
        <p-column field="vin" header="Vin" [style]="{'width':'200px'}"></p-column>
        <p-column field="year" header="Year" [style]="{'width':'250px'}"></p-column>
        <p-column field="brand" header="Brand"  [style]="{'width':'150px'}"></p-column>
        <p-column field="color" header="Color"  [style]="{'width':'100px'}"></p-column>
    </p-dataTable>
```

Somehow percentage values or when no explicit width is defined, it all works fine.

**Comment by cagataycivici** [comment]
Marking as won't fix as browser autoscales widths since table is 100%, works great with percentage values so we should document this to users to give percentage values instead.

**Comment by SashankRamaraju** [comment]
Is there any documentation on this ?? please share the link
