### ISSUE TITLE
 How to import Chart.js in angular2-webpack-starter?

### ISSUE THREAD

**Issue by Ningningz** [primefaces/primeng#2892]
PrimeNG charts depend  file charts.js, how to import into the angular2-webpack-starter.
```
#  https://www.primefaces.org/primeng/#/chart
"scripts": [
  "../node_modules/chart.js/dist/Chart.js",
  //..others
],

```

**Comment by VagrantAI-c** [comment]
try adding it to your main app.module.ts:
`import 'chart.js/dist/Chart.min.js';`

**Comment by yulilong** [comment]
@VagrantAI-c 
I add `import 'chart.js/dist/Chart.min.js';` in the  src/app/app.module.ts,
After running the following error：    
```
ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve 'chart.js/dist/Chart.min.js' in '/Users/yu/work/cloudlink-front-framework/src/app'
 @ ./src/app/app.module.ts 8:0-37
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi (webpack)-dev-server/client?http://localhost:3000 ./src/main.browser.ts
Child html-webpack-plugin for "index.html":
```      
Is there any other way to load this file?

**Comment by VagrantAI-c** [comment]
You first need to install it via `npm i chart.js --save`

**Comment by cagataycivici** [comment]
Use forum for questions please.
