### ISSUE TITLE
Row expansion support for Responsive DataTable

### ISSUE THREAD

**Issue by andrei-ivanov** [primefaces/primeng#2893]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

I've tried to create a demo, but I can't make it work :-(
http://plnkr.co/edit/3pkKcMNk0JLi1Xkx6j9E?p=preview

**Current behavior**
When stacking a Responsive DataTable with Row Expansion, the cell with the expander gets a padding that takes half the screen.

**Expected behavior**
No extra space should be added in the expander cell.

<span class="ui-column-title"></span>

**Minimal reproduction of the problem with instructions**
Take a Responsive DataTable, make it responsive then put it in stack mode.

Using the inspector in Chrome, I think I found the cause:
@media (max-width: 35em)
.ui-datatable-reflow .ui-datatable-data td .ui-column-title {
    /* padding: .4em; */
    /* min-width: 30%; */
    display: inline-block;
    /* margin: -.4em 1em -.4em -.4em; */
}
Disabling those rules make it display fine, without the extra space.

**What is the motivation / use case for changing the behavior?**
I don't think the extra space is on purpose and it should be removed.

**Please tell us about your environment:**
angular 4.1.3, angular-cli, primeng-4.0.1, ng-serve

* **Browser:** 
Chrome 58 on MacOs, Chrome on Android 7, Firefox on MacOs
 
* **Language:** ES5

* **Node (for AoT issues):** `node --version` =   v7.10.0

**Comment by smitpsanghavi** [comment]
For the Ultima theme, this is what I get after applying expander.
![ultima-datatable-expander](https://user-images.githubusercontent.com/10339097/27474101-e4a75910-581e-11e7-88dd-25762f94021a.JPG)

Look at the humongous amount of wasted space in the expander column. Is this related to what you are facing?
My datatable code is
```html
<p-dataTable [value]="cars1" selectionMode="single" [(selection)]="selectedCar" [paginator]="true" [rows]="10" [responsive]="true"></p-dataTable>
```

**Comment by andrei-ivanov** [comment]
Hmm, my expander column is restricted:
`<p-column rowspan="2" [style]="{'width': '35px'}"></p-column>`

In normal view, it uses minimum space.
The problem is in stacked mode.

**Comment by Vrachno** [comment]
I'm not sure if it's the same problem, but I'm also getting irregular behavior when using rowExpansion with reflow.

This is the expanded row in full view:
![pf2](https://user-images.githubusercontent.com/6034580/27747619-993fadc2-5dd4-11e7-9891-4be15e9e9e54.png)

And it becomes like this in stacked mode:
![pf3](https://user-images.githubusercontent.com/6034580/27747698-ed8523c6-5dd4-11e7-8cdc-2d27d369106f.png)

If I hide the expansion from the console with a "hidden" class, the expandable row is shown correctly.

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
