### ISSUE TITLE
Footer Group not displayed on scrollable datatable

### ISSUE THREAD

**Issue by chinna-magapu** [primefaces/primeng#2894]
prime ng data table not showing the footer columns if i added scrollable="true"

My code looks like : 
<p-dataTable [value]="orderSummary.rows" scrollable="true" scrollHeight="200px" >

and footer group like : 
<p-footerColumnGroup>
				<p-row>
					<p-column *ngFor="let total of grandTotal" [footer]="total"></p-column>
				</p-row>
</p-footerColumnGroup>
i have checked the same issue in  #2350 but i didn't get the solution for this.

Angular version: 4.1.2
PrimeNG version: 4.0.1
Prime UI Version: 4.1.8

**Comment by nagpvn2** [comment]
Not all fields are displaying when scrollable is applied for p-headerColumnGroup.
