### ISSUE TITLE
Chart Components

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#29]
Create chart components based on charts.js, charts should be updated whenever their data changes via one-way binding and also should support events like click.

- Pie
- Bar
- Line
- Doughnut
- Radar
- PolarArea

**Comment by zamrokk** [comment]
When I try to use LineChart I got this error :  

```
ReferenceError: Chart is not defined
    at LineChart.initChart (http://localhost:1880/node_modules/primeng/components/chart/linechart/linechart.js:107:30)
    at LineChart.ngAfterViewInit (http://localhost:1880/node_modules/primeng/components/chart/linechart/linechart.js:70:14)
    a
```

coming from 

`            this.chart = new Chart(this.el.nativeElement.children[0].getContext("2d")).Line(this.value, {
`

**Comment by zamrokk** [comment]
I added this , and it works : 

    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js"></script>

**Comment by zamrokk** [comment]
if I try to display it inside a div hidden (accordion or bootstrap collapse), then on div content visible the chart is not displayed. Is it something to do with Angular 2 ?

![image](https://cloud.githubusercontent.com/assets/2536368/13847970/0fd6d5a2-ec50-11e5-8b7d-6515298a9f07.png)

**Comment by cagataycivici** [comment]
Please use PrimeNG forum for questions;

http://forum.primefaces.org/viewforum.php?f=35

**Comment by zamrokk** [comment]
ok, thanks
