### ISSUE TITLE
modal p-dialog is not scrollable

### ISSUE THREAD

**Issue by philly-vanilly** [primefaces/primeng#2902]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/6H0Q2Cm0184pLw3bto1h?p=preview

**Current behavior**
modal p-dialog is not scrollable, but the overflowing elements in the background are (SEE PLUNKR PLEASE)

**Expected behavior**
when a modal element is popped up, I expect it to be potentially bigger than screen size (e.g. overflowing) and thus able to have a scroll-bar. I also expect it to have all the focus so using arrow-keys or two-finger-gesture on a touchpad does not scroll the background, but the modal

**What is the motivation / use case for changing the behavior?**
in my specific case I am implementing a detail view of an element in a data-table as a modal dialog. this dialog is thus bigger than the usual "login-password" that you usually use modals for, and needs to overflow with scroll-bars

* **Angular version:** 4.0.3

* **PrimeNG version:** 4.0.1

* **Browser:** all

**Comment by cagataycivici** [comment]
Try;

```
 [contentStyle]="{'overflow':'auto','max-height':'200px'}"
```

**Comment by norvegec** [comment]
But if I need a full-height (responsive) dialog, what are my options here?

**Comment by guntram** [comment]
You should also set a min-height...
