### ISSUE TITLE
Advanced AutoComplete component does not store a typed-in value.

### ISSUE THREAD

**Issue by AthenaMarine** [primefaces/primeng#2908]
**I'm submitting a ...**  (check one with "x")
```
**[x] bug report => Search github for a similar issue or PR before submitting**
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

You can reproduce the error here in "Advanced" example: https://www.primefaces.org/primeng/#/autocomplete

**Current behavior**
When you type in a value into the "Advanced" AutoComplete component, the value is not displayed/saved when you tab out of the component.

**Expected behavior**
The "Advanced" component should behave the same way as the regular AutoComplete component.  If you type a value into the component and tab to exit, the typed in value should be what is displayed.

**Minimal reproduction of the problem with instructions**
Type "Ford" into the "Advanced" component and press tab to exit the component.  The value that is displayed is "Fiat".

Type "BMW" into the "Advanced" component and press tab to exit the component.  The value that is displayed is "Fiat".

**What is the motivation / use case for changing the behavior?**
Usability, adherence to the Law of Least Astonishment... The "Advanced" AutoComplete component should contain the value the user typed in, the same as the "Regular" AutoComplete component.

**Please tell us about your environment:**
MacOS Sierra 10.12.4

* **Angular version:** 2.0.X
Angular 4.0.2 Latest

* **PrimeNG version:** 2.0.X
Latest

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome 58.0.3029.110
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

TypeScript 2.1.5

* **Node (for AoT issues):** `node --version` =   

Node 6.10.1

**Comment by AthenaMarine** [comment]
Thank you for helping us with this issue :^)

**Comment by yigitfindikli** [comment]
Unable to replicate with latest PrimeNG, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
