### ISSUE TITLE
Bootstrap - Dropdown inside Accordion raises scrollbar

### ISSUE THREAD

**Issue by PhilippRoessner** [primefaces/primeng#291]
I have a Twitter-Bootstrap - Dropdown at the Bottom of a "accordionTab". When I open the Dropdown, the AccordionTab gets a scrollbar, the dropdown-Content is "inside" the accordion, instead of "overlay-style".

![accordion](https://cloud.githubusercontent.com/assets/6959716/14944380/86994200-0ff1-11e6-9076-10fd9fe54b3d.JPG)

**Comment by mdonato7** [comment]
This also applies to primeng's own dropdown control and menu control. I'm having this issue in beta 11 still.

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/issues/1869 fixes this.
