### ISSUE TITLE
Prime-ng datatable - Column reordering breaks if scrollable="true"

### ISSUE THREAD

**Issue by Somnath-Ramraj** [primefaces/primeng#2910]
<p-dataTable [value]="cars" scrollable="true" scrollHeight="200px" scrollWidth="100%" reorderableColumns="true" resizableColumns="true">
        <p-header>Vertical</p-header>
        <p-column field="vin" header="Vin" [style]="{width: '25%'}"></p-column>
        <p-column field="year" header="Year" [style]="{width: '25%'}"></p-column>
        <p-column field="brand" header="Brand" [style]="{width: '50%'}"></p-column>
    </p-dataTable>

**Comment by cagataycivici** [comment]
Please review existing issues first;

#2399
