### ISSUE TITLE
Programatically Tree-Selection

### ISSUE THREAD

**Issue by MrToasty97** [primefaces/primeng#2911]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[X] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

I can't provide a Plunkr Case, since this is from my work.

**Current behavior**
When I'm trying to click the Tree from my Typescript it is working everywhere except in IE11. I am creating a MouseEvent and assigning 'ui-chkbox-box ui-widget ui-corner-all ui-state-default' to the target of the Event.

**What is the motivation / use case for changing the behavior?**
I think there's just a simple thing to do for polyfilling the IE.

* **Angular version:** 2.0.X
Angular 4.0.0

* **PrimeNG version:** 2.0.X
4.0.0

**Comment by MrToasty97** [comment]
I got it working now, as someone has the same Issue sometimes, here's the Code:

    let me: MouseEvent = new MouseEvent('click');
    let elem = document.createElement('div');
    elem.className = 'ui-chkbox-box ui-widget ui-corner-all ui-state-default';
    elem.classList.add('ui-chkbox-box');
    elem.classList.add('ui-widget');
    elem.classList.add('ui-corner-all');
    elem.classList.add('ui-state-default');`

    `Object.defineProperty(me, 'target', {
      get: function () { return elem; },
      set: function (newValue) { elem = newValue; },
      enumerable: true,
      configurable: true
    });`

**Comment by cagataycivici** [comment]
We can't replicate, please create a plunkr, at least a dummy one with dummy data.
