### ISSUE TITLE
Modena readonly dropdown/Input fields do not look readonly

### ISSUE THREAD

**Issue by gatapia** [primefaces/primeng#292]
It would be nice if pInputText, pPassword, DropDown fields marked as readonly were styled differently to editable fields.  Currently you cannot tell if it is readonly or not (other than trying to change them).

Note: This is purely styling issue, the functionality works.

**Comment by gatapia** [comment]
Workaround is to use disabled="true" instead of readonly.  This has different styling.

**Comment by cagataycivici** [comment]
We'll consider this in upcoming Ultima, Rio-Modena-Adamantium are in maintenance mode so new features won't implemented. You'll get access to Ultima once it is released in 2 weeks.
