### ISSUE TITLE
p-dialog -  extra 1px frame in the footer section.

### ISSUE THREAD

**Issue by alialtun14** [primefaces/primeng#2928]
Current behavior
There is a extra frame in the p-footer section of  p-dialog component. This occurs after upgrade to PrimeNG version: 4.0.2  

When I create a case demonstrating with plunkr  related this bug,  This issue did not occur. But in my project the problem continues.

Expected behavior
The is no need extra 1px frame in the footer section.

Demo Case (without issue)
http://plnkr.co/edit/JZPPGyax4yTTFVuPLrM6?p=preview

Local Project Preview (with error)
![unwanted frame](https://cloud.githubusercontent.com/assets/782196/26584020/a0dde030-4547-11e7-8632-f5bc67fe82d7.png)

Angular version: 4.0.2
PrimeNG version: 4.0.2 with  ultima-ng 4.0

**Comment by cagataycivici** [comment]
Please remove ui-widget-content from your footer.
