### ISSUE TITLE
AutoComplete panel width improvements with appendto

### ISSUE THREAD

**Issue by alialtun14** [primefaces/primeng#2929]
[x ] bug report 

http://plnkr.co/edit/q6oLbp46vr3GD4ee6u33?p=preview

Current behavior
AutoComplete panel isn't as wide as supposed to when appendTo is set to "body".

Expected behavior
AutoComplete panel should be as wide as the dropdown always.

Angular version: 4.0.2
PrimeNG version: 4.0.2

**Comment by alialtun14** [comment]
Similar issue related to Dropdown panel

https://github.com/primefaces/primeng/issues/2551

**Comment by andrea-spotsoftware** [comment]
Any update or workaround to avoid this problem?

**Comment by andrea-spotsoftware** [comment]
@cagataycivici almost fixed but the width is miscalculated when the autocomplete has the dropdown button on the right.
