### ISSUE TITLE
DataTable - expandableRows with some hidden columns

### ISSUE THREAD

**Issue by gatapia** [primefaces/primeng#293]
A data table with some hidden columns does not correctly show expanded content. i.e. expanded content sits in a cell with colspan ignoring hidden columns.

Example:
```
<p-datatable [value]="list" expandableRows="true">
  <p-column expander="true"></p-column>
  <p-column header="shown col"></p-column>
  <p-column [hidden]="true" header="hidden col"></p-column>
</p-datatable>
```
Expanding rows in this table will look strange, this is because the expaned row content has wrong colspan (3 instead of 2).

**Comment by cagataycivici** [comment]
Will check for beta.6.

**Comment by gatapia** [comment]
Still happening for scrollable tables, fix here:
https://github.com/primefaces/primeng/pull/383
