### ISSUE TITLE
Chips field bug

### ISSUE THREAD

**Issue by pantonis** [primefaces/primeng#2930]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
I have a multiselect control with a chips control. Whatever I select in the multiselect it is added in chips control. By default the value item of the multiselect item is shown in the chips control. Lets say I have a collection of cities (label: "New York", value:1, label: "London", value:2). When I select New York in the Multiselect chips shows 1. If I set the field property of the chips control to "<p-chips field='label'></p-chips>" it shows an empty chip.

**Expected behavior**
Should show the label property

* **Angular version:** 
4.0.3

* **PrimeNG version:** 2.0.X
4.0.1

**Comment by cagataycivici** [comment]
Please provide a plunkr that replicates the issue.

**Comment by cagataycivici** [comment]
http://plnkr.co/edit/Wj39h1?p=preview
