### ISSUE TITLE
[Bug] in editable DataTable with nested object as data source (w added plnkr)

### ISSUE THREAD

**Issue by brud** [primefaces/primeng#2932]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/N0rNjg?p=preview

**Current behavior**
when for editable DT we have nested row object like this:
```
{
      vin: {
          vin: 'test'
      },
      year: 'test',
      brand: 'test',
      color: 'test',
}
```
and template lke this:
```
<p-dataTable [value]="cars" [editable]="true">
    <p-column field="vin.vin" header="Vin" [editable]="true"></p-column>
    <p-column field="year" header="Year"></p-column>
    <p-column field="brand" header="Brand"></p-column>
    <p-column field="color" header="Color"></p-column>
  </p-dataTable>
```
when we edit `vin.vin` editable row became a:
```
{

      vin.vin: 'new value', // <==== it's amazing

      vin: {
          vin: 'test'
      },

      year: 'test',
      brand: 'test',
      color: 'test',
}
```

**Expected behavior**
after editing object should be a:
```
{
      vin: {
          vin: 'new value'
      },
      year: 'test',
      brand: 'test',
      color: 'test',
}
```
**Please tell us about your environment:**
Ubuntu 16.04, PhpStorm, WebPack, nginx

* **Angular version:** 4.1.3

* **PrimeNG version:** 4.0.1

* **Browser:** Chromium 58
 
* **Language:** TypeScript 2.1.6

**Comment by DrummerKH** [comment]
+1

**Comment by maracinebogdan88** [comment]
Same here

**Comment by mniederkofler** [comment]
Same here.

Are there generally restrictions in the data table with nested objects? Or are nested object values fully supported.

**Comment by trueVitality** [comment]
+1

**Comment by jefftham** [comment]
@cagataycivici  , you can link this ticket to https://github.com/primefaces/primeng/issues/2526

**Comment by togbyte** [comment]
+1

**Comment by atanu21000** [comment]
+1

**Comment by digaus** [comment]
Any news on this? Ran into this issue cause I created a workaround for filterung and sorting piped data...

**Comment by maracinebogdan88** [comment]
If you still haven't found a solution, this should do it: 

<p-column field="vin" header="Vin" [editable]="true">
    <ng-template let-col let-car="rowData" pTemplate="body">
        {{car.vin.vin }}
    </ng-template>
    <ng-template let-col let-car="rowData" pTemplate="editor">
        <input type="text" pInputText [(ngModel)]="car.vin.vin">
    </ng-template>
</p-column>

**Comment by dmsaravanan1983** [comment]
This is not working, Dot notation is showing [object object] only

**Comment by maracinebogdan88** [comment]
I've actually tried it, it should work.
Please check this out [http://plnkr.co/edit/mqI5GK?p=preview]
By the way, the correct way to accessing object keys is one of these:

- cars[0].vin.vin

- cars[0]['vin']['vin']

and not like this: cars[0]["vin.vin"]

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
