### ISSUE TITLE
is there any solution for custom filters in primeNg table ? any update ?

### ISSUE THREAD

**Issue by akashdeepg12** [primefaces/primeng#2938]
is there any solution for custom filters in primeNg table ?
any update ? @jfarcand

**Comment by cagataycivici** [comment]
Please use forum for questions, also I don't think @jfarcand is interested in this issue :)

**Comment by akashdeepg12** [comment]
@cagataycivici  Actually I have tried to signup on  forum ,but error was coming during signup.

Can you please confirm me link of forum .
