### ISSUE TITLE
How to disable default filtering in PrimeNg DataTable ? 

### ISSUE THREAD

**Issue by akashdeepg12** [primefaces/primeng#2939]
PrimeNG DataTable has an option [filter]="true" which enables an input on column header used to filter data.
But we need globally flag to enable/disable filter of PrimeNg DataTable .
any update ? @cagataycivici

**Comment by cagataycivici** [comment]
Please use forum for questions and support requests.

**Comment by akashdeepg12** [comment]
@cagataycivici Actually I have tried to signup on forum ,but error was coming during signup.

Can you please confirm me link of forum .
