### ISSUE TITLE
[Enhancement] DataTable.expandableRows enhancements

### ISSUE THREAD

**Issue by gatapia** [primefaces/primeng#294]
Would be great if you could do the following:
- Set a tooltip on the expander column without using template column hacks.  I.e. I would like to set `title="View {{children.length}} children"` or something like that.  
- Have a boolean to enable / disable expansion on a per row basis.  I.e. show the expander arrow as "disabled" when no details for that row

**Comment by cagataycivici** [comment]
1296 will enable the second part where you can hide the expander icon, not sure about first request, will reconsider if more users demand it.
