### ISSUE TITLE
PrimeNg DropDown - User can't clear the value

### ISSUE THREAD

**Issue by DarioN1** [primefaces/primeng#2942]
Hi,
I'm implementing primeNg dropdown component in my Angular2 application.

This is the code:
`<p-dropdown [options]="listCustomers_itm" placeholder="Selezionare" [(ngModel)]="Customer_itm" [ngModelOptions]="{standalone: true}" [style]="{'width':'225px'}" filter="filter"  (onChange)="onCustomerSelect($event.value)">
</p-dropdown>`

All works fine except one annoing thing:

Once time the user has selected an option, he can't clear the selected value...

Can you help me?

**Comment by cagataycivici** [comment]
Please use forum for cases like these, discussions, help requests and questions.
