### ISSUE TITLE
Add eventAfterAllRender for Primeng Schedule

### ISSUE THREAD

**Issue by ahelord** [primefaces/primeng#2946]
I am trying to enable and disable filters for the calendar when all calendar events are rendered, but the eventAfterAllRender event (doc https://fullcalendar.io/docs/event_rendering/eventAfterAllRender/) is not available, you could add this original method Of fullcalendar.

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

* **Angular version:** 4.1.3

* **PrimeNG version:** 4.0.1

* **Browser:** [all ]

 
* **Language:** [typescript 2.2.2]

**Comment by ahelord** [comment]
@cagataycivici hi friend how is the progress of this?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
