### ISSUE TITLE
Use zxcvbn as Password Strength Estimation

### ISSUE THREAD

**Issue by apiweb** [primefaces/primeng#2949]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When using the PrimeNG Input Password, typing a 1234567 password is marked as a medium password, and when you type 123456789123456789, this password is marked as a strong password.
But clearly it is a weak password.

**Expected behavior**
Mark passwords that are repeats, sequences or keyboard patterns such as weak passwords.

**Minimal reproduction of the problem with instructions**
Using [Password Input
](https://www.primefaces.org/primeng/#/password)

**What is the motivation / use case for changing the behavior?**
When using [zxcvbn ](https://github.com/dropbox/zxcvbn/)(from the Dropbox development team). Most of these problems would be solved.
The lib can recognize patterns, common passwords, names and surnames. WordPress and some other CMS's already use zxcvbn.
And this could bring more security to the user, because instead of having 3 levels (weak, medium and strong), we would have 5 levels:

- 0 # too guessable: risky password. (guesses < 10^3)
- 1 # very guessable: protection from throttled online attacks. (guesses < 10^6)
- 2 # somewhat guessable: protection from unthrottled online attacks. (guesses < 10^8)
- 3 # safely unguessable: moderate protection from offline slow-hash scenario. (guesses < 10^10)
- 4 # very unguessable: strong protection from offline slow-hash scenario. (guesses >= 10^10)

**Angular version:** 2.0.X
4.1.X

**PrimeNG version:** 2.0.X
4.0.3

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
