### ISSUE TITLE
Dialog - onBeforeHide and onAfterHide events not fire

### ISSUE THREAD

**Issue by ammar91** [primefaces/primeng#295]
After upgrading to angular beta 17 and primeng beta 4, dialog events `onBeforeHide  `and `onAfterHide `not seems to be working. Hope to have this fix soon.

**Comment by Chadley08** [comment]
These events appear to still not be firing.

**Comment by bakasmarius** [comment]
Any update on this? For me onBeforeHide also does not work,
PrimeNG version: 4.0.3
Angular version: 4.1.3

**Comment by sudheerj** [comment]
There are no events like onBeforeHide or onAfterHide for dialog components
