### ISSUE TITLE
Datatable bugs

### ISSUE THREAD

**Issue by Ketec** [primefaces/primeng#2954]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
Latest 4.0.3
When looking through the source i saw two minor bugs:
in toggleRowGroup:
`
            this.expandedRowsGroups = this.expandedRowsGroups || [],
                this.expandedRowsGroups.push(rowGroupField);
`
comma used instead of semicolon.

findExpandedRowIndex:
`
        let index = -1
`
missing semicolon.

**Comment by cagataycivici** [comment]
Fixed by @upmauro
