### ISSUE TITLE
Dialog - Scrolling break

### ISSUE THREAD

**Issue by ammar91** [primefaces/primeng#296]
After upgrading to angular beta 17 and primeng beta 4, scrolling break inside a dialog.

![screen](https://cloud.githubusercontent.com/assets/7683970/14960395/e51ff55a-10ad-11e6-80d1-681161dfce69.png)

**Comment by cagataycivici** [comment]
Can you post your dialog code please?

**Comment by ghcsantos1978** [comment]
Every body knows how can i put scroll in dialog primeng?
