### ISSUE TITLE
DataTable OnEditComplete Event Not Executing When Editing Completed By Clicking Outside of Field Being Edited

### ISSUE THREAD

**Issue by jamesdking** [primefaces/primeng#2960]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/MynV9eXlmojgrCzHKHTT?p=preview

**Current behavior**
The OnEditComplete event does not execute when the edit is completed by clicking outside of the field being edited

**Expected behavior**
The OnEditComplete event should when editing is completed by clicking outside of the field being edited.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/MynV9eXlmojgrCzHKHTT?p=preview

* **Angular version:** 4.0.X
* **PrimeNG version:** 4.0.3
* **Browser:** [Chrome] 
* **Language:** [TypeScript 2.2.2]

**Comment by codertim** [comment]
Are we sure this code in the examples is correct: (onEditInit)="onEditComplete($event)" ?

**Comment by wujitouch** [comment]
I'm also experiencing this issue. Looking at the code, it's clear why it's happening. The event is only called in onCellEditorKeydown.

**Comment by jamesdking** [comment]
Apologies, the code in the Plunk was indeed incorrect.

**Comment by codertim** [comment]
No problem, I make mistakes like that every other day!

**Comment by wujitouch** [comment]
For me it doesn't work because I'm using an edit template. But I don't need this functionality right now so I won't open a ticket yet.
