### ISSUE TITLE
DataTable rowStyleClass causes webpage to become unresponsive if mouse over DataTable

### ISSUE THREAD

**Issue by kamran-pervaiz** [primefaces/primeng#2962]
hi guys,

I have used DataTable and it seems to call the rowStyleClass on mouse hover which makes the chrome page unresponsive if mouse moves on the page it calls rowStyleClass method which we can see in the Gif i have attached. If mouse is still then its fine which is not the ideal case.
`<p-dataTable [rows]="20" [paginator]="true" [pageLinks]="3" [rowsPerPageOptions]="[5,10,20]" [value]="searchresults" [globalFilter]="gb"
                            [resizableColumns]="true" [reorderableColumns]="true" [scrollable]="false" [rowStyleClass]="getRowStyleClass">
                            <p-column field="businessAreaName" header="Business Area" sortable="true">
                                <ng-template let-col let-searchresult="rowData" pTemplate="body">
                                    <a (click)="GoToBusinessAreaPage(searchresult.businessAreaId)">{{searchresult.businessAreaName}}</a>
                                </ng-template>
                            </p-column>
                            <p-column field="supplierName" header="Supplier" sortable="true">
                                <ng-template let-col let-searchresult="rowData" pTemplate="body">
                                    <a (click)="GoToSupplierPage(searchresult.supplierId)">{{searchresult.supplierName}}</a>
                                </ng-template>
                            </p-column>
                            <p-column field="factoryName" header="Factory" sortable="true">
                                <ng-template let-col let-searchresult="rowData" pTemplate="body">
                                    <a (click)="GoToFactoryPage(searchresult.factoryId)">{{searchresult.factoryName}}</a>
                                </ng-template>
                            </p-column>
                            <p-column field="countryName" header="Country" sortable="true">
                                <ng-template let-col let-searchresult="rowData" pTemplate="body">
                                    {{searchresult.countryName}}
                                </ng-template>
                            </p-column>
                            <p-column field="factoryStatus" header="Factory Status" sortable="true">
                                <ng-template let-col let-searchresult="rowData" pTemplate="body">
                                    {{searchresult.factoryStatus}}
                                </ng-template>
                            </p-column>
                            <p-column field="eventDate" header="Last Audit Date" sortable="true">
                                <ng-template let-col let-searchresult="rowData" pTemplate="body">
                                    <a href="/#/factory/{{searchresult.factoryId}}/event/{{searchresult.eventId}}">{{searchresult.eventDate | date:'y-MM-dd'}}</a>
                                </ng-template>
                            </p-column>
                        </p-dataTable>`

I will update primeng version soon as i have done a fix on other branch, which i need but do you think this issue will be resolved in latest primeng? I am assuming some mouseMove event is being called which triggers DataTable to call the method.

**Angular:** 4.0.0
**primeng:** 1.0.0

![2017-06-01_18-20-48](https://cloud.githubusercontent.com/assets/2331946/26692195/b30e6fb6-46f7-11e7-8969-003aa8d24862.gif)

**Comment by kamran-pervaiz** [comment]
someone created a plunker as well, you can have a look by opening Web Dev tools for chrome and in console.

http://plnkr.co/edit/25NZ7M?p=preview

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/VZbdZfQ7SuTV87tTkbYR
