### ISSUE TITLE
Not supported enableGridMenu And gridMenuCustomItems feature (as implemented in UI-Grid)in PrimeNg table 

### ISSUE THREAD

**Issue by akashdeepg12** [primefaces/primeng#2963]
enableGridMenu And gridMenuCustomItems feature as implemented in UI-Grid is not available in PrimeNg table .
Please support this feature as soon as possible.

**Comment by cagataycivici** [comment]
Do you have links so we can check them out?

**Comment by akashdeepg12** [comment]
you can checkout here :  
http://ui-grid.info/docs/#/tutorial/121_grid_menu

**Comment by cagataycivici** [comment]
You can easily implement this using p-menu and p-table.
