### ISSUE TITLE
Dropdown accessiblity

### ISSUE THREAD

**Issue by Mrtcndkn** [primefaces/primeng#2966]
Dropdown needs aria-label attribute for accessibility

**Comment by rudxde** [comment]
the arialabel Attribute ist not responsible for the selected item, it just describes the element. For the selected item, is the 'aria-activedescendant' attribute responsible. Also an role Attribute is necessary.

**Comment by ganlhi** [comment]
I agree with rudxde : currently the aria-label is set to the currently selected option which is incorrect because the aria-label is not the value of the field, but what the field is about. This must be changed, otherwise it is impossible to pass the accessibility criterias using this component.

**Comment by flashape** [comment]
Is the aria-activedescendant attribute supposed to get added to the text input?  I need to get this done.

**Comment by flashape** [comment]
I noticed that the hidden select input has the attribute aria-hidden="true", which I believe means it won't announce the value of aria-activedscendant anyway?  I've been trying to read up on how this pattern is supposed to work, but I still can't get it to work...if anyone knows how to fix this please let me know.
