### ISSUE TITLE
Dialog : Emit visibleChange when the dialog is shown

### ISSUE THREAD

**Issue by aesersnake** [primefaces/primeng#2969]
I'm submitting a ...

[] bug report
[X] feature request
[ ] support request

Current behavior
The visibleChange event is emited only when you close the dialog

Expected behavior
Emit visibleChange when the dialog is shown

Angular version: 4.0.X
PrimeNG version: 4.0.3
Browser: all
Language: [TypeScript 2.3.3]

**Comment by sudheerj** [comment]
Correct. But If the dialog is visible by default then it shouldn't emit visible change event. So I feel it shouldn't emit blindly based on show/hide

**Comment by cagataycivici** [comment]
But dialog itself never shows the dialog, it is shown by the model.

**Comment by Lucascoorek** [comment]
From what I see there is no information in the online doc's about `visibleChange` in the dialog section. It would be very helpfull to add it there, as the two-way binding to `visible` property is not always the best solution. 
For example I want to use some async pipe connected to some service to show/hide the dialog. This is not possible with two-way binding.
