### ISSUE TITLE
Multiple Date selection in calendar

### ISSUE THREAD

**Issue by smitpsanghavi** [primefaces/primeng#2970]
**I'm submitting a ...**
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
Need ability to select multiple dates from p-Calendar. 

**Current behavior**
A single date can be selected using the calendar component.

**Expected behavior**
Multiple non-consecutive dates can be selected.

**What is the motivation / use case for changing the behavior?**
We have a case where the user wants to select the dates on which holidays are required to be given. This needs a behaviour where multiple dates need to be taken as input from the calendar.

**Please tell us about your environment:**
Windows 10, VS 2017, NPM v3.10.9

* **Angular version:** 4.1.3

* **PrimeNG version:** 4.0.3

* **Browser:** all
 
* **Language:** TypeScript 2.3.4

**Comment by Nodios** [comment]
+1
