### ISSUE TITLE
Dynamic Sorting on data update? 

### ISSUE THREAD

**Issue by RicardoVaranda** [primefaces/primeng#298]
Not sure if this feature is already available but I was not able to find it, it would be cool if the table would update the sorting if a value is changed on the column which are being sorted.

Edit:
I see this is sort of implemented here:
https://github.com/primefaces/primeng/issues/298

But for some reason it does not update the sorting, currently I am changing a value of an object inside of the value array and the changes do display properly but it does not update the sorting, would you be able to shine some light on how this can be achieved?

**Comment by GraemeSMiller** [comment]
Yup - we need some way to force the table to resort if we change contents. Doesn't seem to maintain sort correctly if we change the contents of the table content outwith the table.

**Comment by cagataycivici** [comment]
So to clarify, if the table is sorted already and the data is changed by you, you want the table to sort the new data? I believe we can do it.

**Comment by GraemeSMiller** [comment]
Yes. Exactly that. Alternative is a way to just apply sort again. I am changing data so can just reapply. However being lazy it would be nice if table just resorted on data change.

**Comment by cagataycivici** [comment]
Ok, we'll do it then.

**Comment by RicardoVaranda** [comment]
Thanks for the fix.

**Comment by arjayleviackerman24** [comment]
Is this already implemented in primeng ? How can I resort the datatable if the data has changed?

**Comment by marslan2037** [comment]
@arjayleviackerman24 i don't think, i am also looking for this fix.

**Comment by JimmyTheNerd** [comment]
@arjayleviackerman24 & @marslan2037 I faced the same issue and solved it like this:

```
updateMyTableData() {
    var tmp = this.myTableData;
    for (var i = 0, c = tmp.length; i < c; i++) {
        tmp[i].whatever = 'new data';
    }
    this.myTableData = [...tmp];
}
```
**Sources**:

> Table may need to be aware of changes in its value in some cases such as reapplying sort. For the sake of performance, this is only done when the reference of the value changes meaning a setter is used instead of ngDoCheck/IterableDiffers which can reduce performance. So when you manipulate the value such as removing or adding an item, instead of using array methods such as push, splice create a new array reference using a spread operator or similar. (PrimeNG docs)

> https://github.com/primefaces/primeng/issues/2689#issuecomment-299407901

Hope it helps!
