### ISSUE TITLE
multiSelect doesn't close with change detection onPush

### ISSUE THREAD

**Issue by jbarbede** [primefaces/primeng#2981]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/9o3Lg9Twtz7OBTLsluds?p=preview

**Current behavior**

The multiselect doesn't close when using change detection strategy onPush on document click.

**Expected behavior**

The multiselect should simply close like autocomplete/dropdown components.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

4.1.2
* **PrimeNG version:** 2.0.X
4.0.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview

**Comment by jbarbede** [comment]
This is not working on release 4.0.3 (I fixed my first comment because I saw it was saying 2.x.x and 4.0.3). By recent release, you mean the new one coming (4.1.x)?

Anyway I updated the plunkr to 4.1.0-rc.2 and the problem still exists:
http://plnkr.co/edit/LTFxrLSjypLwnrmveEfq?p=preview
