### ISSUE TITLE
datatable with custom sort function on the default softField isn't working properly

### ISSUE THREAD

**Issue by sambrow** [primefaces/primeng#2985]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

This Plunkr (currently) exhibits the issue:
https://plnkr.co/edit/OPAiDJwtByZZ1DSP385r

Note: This is similar in spirit to this reported issue (which has a comment saying it is fixed):
https://github.com/primefaces/primeng/issues/553

**Current behavior**
A datatable with a default sortField set where that particular column happens to have a custom sort function.  The data for the table is set asynchronously (using setTimeOut() to simulate the delay that an AJAX call would have).

When the simulated AJAX call fires (after one second) and sets the backing store array, the custom sort function IS called (turn on the console to see some output it logs) BUT the user is left seeing the rows in the order dictated by the default sorting (alphabetical) rather than showing the results of the custom sort function.

That is, the user mistakenly sees this:

Apple
Samsung
Microsoft
Philips
Song
LG
Sharp
Panasonic
HTC
Toshiba

**Expected behavior**
After the simulated AJAX call fires and sets the backing store array, the custom sort function should be called AND the user should see the correct order of rows in the browser as determined by the custom sort function.

That is, the user should see this because the custom sort function sorts the words as if their first letter were removed and the remaining string was uppercased:

Samsung
Panasonic
LG
Sharp
Philips
Microsoft
Song
Toshiba
Apple
HTC

**Minimal reproduction of the problem with instructions**
Run this Plunkr
https://plnkr.co/edit/OPAiDJwtByZZ1DSP385r

wait one second for the data to load and then notice that the data is sorted alphabetically RATHER THAN how it should appear given the custom sort function.

**What is the motivation / use case for changing the behavior?**
I think any user of the datatable who gets their data via an ajax call and goes through the trouble of defining a custom sort function for the default sort column would expect that function to determine the actual display order.

**Please tell us about your environment:**
OSX 10.11.6

* **Angular version:** 4.1.3

* **PrimeNG version:** 4.0.0, 4.0.1, 4.0.2, 4.0.3
NOTE: This worked correctly in 4.0.0-rc.4

* **Browser:** Latest versions of Chrome, Firefox, and Safari on my Mac laptop 
* **Language:** TypeScript 2.2.1

**Comment by sivanandhu** [comment]
https://plnkr.co/edit/QCbFfkzNLBjh4cCi4MHO?p=preview

**Comment by sambrow** [comment]
@sivanandhu , please help me understand why you say the problem is solved.  I looked at your plunkr link and you have edited the custom sort function to use a lodash sort method which seems to just do a simple sort.   Thus, you are not using the special custom sort logic.

If you take out your custom sort call and comment in the original sort code, you will see that the original problem described in this issue is still present.

Thanks

-Sam

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
