### ISSUE TITLE
DataTable incorrectly highlights selected row when rows differ only in Date field

### ISSUE THREAD

**Issue by marcin-wroblewski** [primefaces/primeng#2989]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

http://plnkr.co/edit/Xo82XYdNtDI5bzheCvTl?p=preview

**Current behavior**
I'm displaying few rows which are unique, but differ only by Date field, e.g.
```
   myRows = [
     { d: new Date(2015,1,1), t: "x" },
     { d: new Date(2015,1,2), t: "x" },
     { d: new Date(2015,1,3), t: "x" }
   ];
```
When I click on any row, all of them are highlighted as selected.

**Expected behavior**
Only one row should be highlighted as selected.

**Minimal reproduction of the problem with instructions**

Prepare some rows which differ only in Date field:
```
   myRows = [
     { d: new Date(2015,1,1), t: "x" },
     { d: new Date(2015,1,2), t: "x" },
     { d: new Date(2015,1,3), t: "x" }
   ];
```
Build a DataTable on the rows
```
<p-dataTable selectionMode="single" [value]="myRows" >
    <p-column field="d" header="Date"></p-column>
    <p-column field="t" header="Text" ></p-column>
</p-dataTable>
```

Try to click on any row

**What is the motivation / use case for changing the behavior?**
I want to show some time series, and there is a possibility that some rows differ only in the Date field

**Please tell us about your environment:**

* **Angular version:** 4.0.0

* **PrimeNG version:** 4.0.1

* **Browser:** all
 
* **Language:** TypeScript 2.2

**Comment by daleclements** [comment]
Hi,

For what it's worth, I believe you can use the dataKey table attribute to solve your issue. dataKey specifies which field in your row objects is expected to be the unique identifier. In your plunkr, if I change to:

```
<p-dataTable selectionMode="single" [value]="myRows" [(selection)]="selectedRow" dataKey="d">
    <p-column field="d" header="Date"></p-column>
    <p-column field="t" header="Text" ></p-column>
</p-dataTable>
```
then I can select individual rows. Unfortunately I'm sure that if you have two rows with the same date, it will select them both when you select one, so you would want something like an id field even if you don't display it.

**Comment by dannymurphygfk** [comment]
Hi,
Using Angular 4 and primeng 4.1.0 
Though specifying the datakey does help in the example above I have an example using the cars models from the primeng website.

I am using the [(selection)] attribute to bind to a component property. [(selection)]="selectedRow". clicking the rows correctly sets this property.
If I programatically set the selectedRow it should highlight the row on the DataTable.
This works until I specify the dataKey attribute.

**Comment by jizza** [comment]
I have the same issue as @dannymurphygfk. I too programmatically set the selectedRow, which works until I make use of dataKey as a fix for the problem @marcin-wroblewski described.

I'm using primeng 4.2.2

Please fix the date issue!

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
