### ISSUE TITLE
Data load on the row expan click (trigger a service to load data )

### ISSUE THREAD

**Issue by nitin27may** [primefaces/primeng#2991]
I have loaded a set 700 rows in grid, now we have to load the another grid for respective row on the row expand click,

Now we want call the service to get that data for nested grid (on road Expand only)
How I can achieve that.

Also Is there any method which i can use on a custom click for row expand.

I have seen below way

```
<p-dataTable [value]="list" 
            #myTable
            expandableRows="true"
            selectionMode="none" 
            (onRowClick)="myTable.toggleRow($event.data)">
```
but this enable for the entire row, i have to expand it on click of a cell (custom click)

So here I have 2 questions 

- How we can load nested grid on the demand (on Row expansion click) ?

- How I can expand a row on the click of a cell (custom click on a button)?

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
```

* **Angular version:** 4.0.0

* **PrimeNG version:**4.0.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript 2.0.3 | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   7.7.4

**Comment by cagataycivici** [comment]
Please use forum for support requests, you may check out onRowExpand event.

**Comment by maksof-kashif** [comment]
onRowExpand is not working ???

**Comment by viveksyadav** [comment]
> onRowExpand is not working ???

No it isn't for me
