### ISSUE TITLE
DataTable onEdit(Complete) access to previous cell value

### ISSUE THREAD

**Issue by daleclements** [primefaces/primeng#2997]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
In a DataTable, when onEditComplete triggers ([and it doesn't always trigger at the right time](https://github.com/primefaces/primeng/issues/2967)), it passes an event that holds the new value of the cell, and the object bound to the [value] property of the table already contains that new cell value. This means that the previous value of the cell is completely lost.

**Expected behavior**
I would expect that either the event is fired before change is reflected in the backing object (so that you can compare the new value to the old value) or that the event contains the old value (so that you can compare the new value to the old value)

**What is the motivation / use case for changing the behavior?**
Checking for dirty values, for example. Let's say that I want to notify the user if the contents of the table have been changed, so that they can choose to save it back to the server. Every time they click on an editable cell and then click away, the onEditComplete event is fired, so I wouldn't be able to tell if they simply clicked it and clicked away without making changes, or even if they made changes but changed it back before leaving the cell (Like editing the value from 11 to 11). In those cases, I wouldn't want to mark the row/table as dirty.

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
