### ISSUE TITLE
Make dialog accept any CSS units

### ISSUE THREAD

**Issue by SIlver--** [primefaces/primeng#2998]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Right now, height/width is decided by accepting an `integer` and then converting it to a string with `px` at the end. The only time an `integer` seems to be required is for around [line 280](https://github.com/primefaces/primeng/blob/master/src/app/components/dialog/dialog.ts#L280) and [line 319](https://github.com/primefaces/primeng/blob/master/src/app/components/dialog/dialog.ts#L319) for calculating the position. But surely this can be done in another way if this feature was implemented? 

**Expected behavior**
I'm hoping I can use CSS units like % or any other value in the future to fit my uses cases. For %, it would allow the dialog to become responsive with the window.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.X.X

* **PrimeNG version:** 4.0.X

* **Browser:** [all]
 
* **Language:** [all]

**Comment by dhniels** [comment]
this would be nice as the new responsive="true" doesnt seem to quite work

**Comment by cagataycivici** [comment]
This is done in 7.0.2, also see;

https://github.com/primefaces/primeng/issues/6992

**Comment by ViceIce** [comment]
@cagataycivici You should add the milestone. :wink:
