### ISSUE TITLE
Can't resolve all parameters for Slider

### ISSUE THREAD

**Issue by susheelbanyal** [primefaces/primeng#3002]
I want to use primeng slider module in my angular project.
`"@angular/common": "4.0.0",
    "@angular/compiler": "4.0.0",
    "@angular/core": "4.0.0",
    "@angular/forms": "4.0.0",
    "@angular/http": "4.0.0",
    "@angular/platform-browser": "4.0.0",
    "@angular/platform-browser-dynamic": "4.0.0",`

`  "devDependencies": {
    "@angular/cli": "1.0.4",
    "@angular/compiler-cli": "4.0.0",`

app.module.ts
`import { SliderModule } from 'primeng/primeng';`
`
@NgModule({
  imports: [
    SliderModule,
]})
`
After following your documentation, I am getting the `Can't resolve all parameters for Slider`. Please let me know If I am doing wrong anything.

**Comment by cagataycivici** [comment]
Please use forum for support requests with full code of your app module.

**Comment by san4ezz87** [comment]
susheelbanyal Hey could you found out this problem's solution?
