### ISSUE TITLE
Reorder support for Scrollable Table

### ISSUE THREAD

**Issue by mithus7** [primefaces/primeng#3012]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

https://embed.plnkr.co/d9hQLeW3r95SMtCioTqt/

**Current behavior**
If the datatable is scrollable and has reorderableColumns, when we try to reorder the columns, they stay in the same place

**Expected behavior**
Should reorder the columns

**Minimal reproduction of the problem with instructions**
https://embed.plnkr.co/d9hQLeW3r95SMtCioTqt/

* **Angular version:** 4.1.0

* **PrimeNG version:** 4.0.3

* **Browser:** [all ]

Thank you

**Comment by mithus7** [comment]
I think this is related to #2399. I didn't find it at first because I was unaware that this is an enhancement.

Any ideas when this will be available?

**Comment by sudheerj** [comment]
Closing this issue as duplicate.
