### ISSUE TITLE
onBeforeHide event for Dialog

### ISSUE THREAD

**Issue by bakasmarius** [primefaces/primeng#3013]
We use a form inside p-dialog and if user changes the data inside the form and does not save it, we want to show a confirmDialog before the dialog hides.
onBeforeHide event would be very useful for this.
I think it was already implemented before? #295

**Comment by dcs3spp** [comment]
Any reason why onBeforeHide event no longer exists? Would be useful for displaying notification messages when the dialog state has been modified without saving....

**Comment by bakasmarius** [comment]
@cagataycivici are there any plans to bring this functionality back?

**Comment by yigitfindikli** [comment]
onHide event is now being called when the animation end. You can try with the latest PrimeNG.
