### ISSUE TITLE
angular cli ng build error by splitt button and spinner

### ISSUE THREAD

**Issue by sen3l3ss** [primefaces/primeng#3020]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
Error Messages:
```
ERROR in ng:///... /node_modules/primeng/components/splitbutton/splitbutton.d.ts.SplitButton.html (5,142): Cannot invoke an expression whose type lacks a call signature. Type 'EventEmitte
r<any>' has no compatible call signatures.
ERROR in ng:///... /node_modules/primeng/components/spinner/spinner.d.ts.Spinner.html (6,120): Cannot invoke an expression whose type lacks a call signature. Type 'EventEmitter<any>' has
no compatible call signatures.
```
**Environment:**
angular/cli: 1.1.0
node: 7.10.0
os: win32 x64
angular/animations: 4.1.3
angular/common: 4.1.3
angular/compiler: 4.1.3
angular/core: 4.1.3
angular/forms: 4.1.3
angular/http: 4.1.3
angular/platform-browser: 4.1.3
angular/platform-browser-dynamic: 4.1.3
angular/router: 4.1.3
angular/compiler-cli: 4.1.3
tslint: 5.1.0 or 5.4.3
typescript: 2.3.2 or 2.3.3

PrimeNG 4.0.3 => Error
PrimeNG 4.0.2 => Error
PrimeNG 4.0.1 => Error
PrimeNG 4.0.0 => No Error

**Comment by sudheerj** [comment]
PrimeNG showcase is based on angular CLI.I can't replicate the issue with PrimeNG showcase.

**Comment by cagataycivici** [comment]
Cant replicate as well.
