### ISSUE TITLE
Tree: When dragging an item hovering over another item should expand it

### ISSUE THREAD

**Issue by JakeSummers** [primefaces/primeng#3021]
**I'm submitting a ...**

```
[ ] bug report => Search github for a similar issue or PR before submitting
[X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

I am using the PrimeNg tree with Drag and Drop.  Currently I have a tree like this: 

```
 Food
     + Soda
     + Chips
     + Popcorn
     + Candies
```

If I start dragging Popcorn and hover over Chips I would expect chips to expand, like this: 

```
 Food
     + Soda
     + Chips
            + Lays
            + Pringles
     + Popcorm (currently being dragged)
     + Candies
```

_Current workaround:_ This_ is behavior is possible to piece together right now using templates in the tree with dragenter and debounce times but this seems like behavior that is naturally suited to the widget/component.

**Comment by janhurst** [comment]
The expand behaviour described by @JakeSummers is what I was expecting out of the box

**Comment by EzePerucca** [comment]
Any news on this? Or an alternate way to achieve it?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
