### ISSUE TITLE
Very strange behavior on two calendar component

### ISSUE THREAD

**Issue by aebmknrl** [primefaces/primeng#3023]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

Please review this plunkr:
** EDITED ** This is the correct plunkr:
http://plnkr.co/edit/kZLZPP7ro6jAo8HZZhoN?p=preview

**Current behavior**

I have two calendar components on my project. When user sets the first one, then this date is the min date for the second one. If i set the date on the second calendar, then the date OVERRIDES the date set on the first calendar component! But this is the strange part: If the difference dates setted on the components are > 1 day, then the problem is gone.

Please review the plunkr, and open the console to see the result. The dates set on the calendar view don't change, but on the backside of the app does.

**Expected behavior**

A normally behavior of the two calendar components
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

I'm on Windows 2010, node 6
* **Angular version:** 2.0.X

Angular 4.0.1
* **PrimeNG version:** 2.0.X

PrimeNG version 4.0.2
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 All Browsers
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by mlakhara** [comment]
I do not see any issue in the plunkr here. Can you please elaborate the issue with an example in the comment. This will clarify it a bit.

**Comment by aebmknrl** [comment]
Do you open the console and see the result? If you set a start date and later set a end date you will see that the start date was override with the end date. Please check out.

**Comment by aebmknrl** [comment]
Please note: the behavior is ONLY when you set the end date on the SAME day.

**Comment by aebmknrl** [comment]
@mlakhara i already update the plunkr with a few instructions. Thanks.

**Comment by mlakhara** [comment]
@aebmknrl This is because you are setting the newTask.end = newTask.start. Hence the model is bound to the date object which is also associated with the start date. You can do this `newTask.end = new Date(newTask.start)`.

**Comment by aebmknrl** [comment]
@mlakhara WTF? Sorry my friend but... i can't explain me why this works? Let me think... The problem was not the control... even the model is not the problem... the problem was that i not make an instance of the Date object? Is this correct?

**Comment by mlakhara** [comment]
Yes because the date object is set as  a reference and ngModel is bound to the same reference. You can close this issue now as this is not an issue with the control.

**Comment by aebmknrl** [comment]
Yes of course. I want to thank you @mlakhara for your help. I was not even close to solving this by myself. This was made me crazy.
