### ISSUE TITLE
DropDown Problem in DataTable Row 

### ISSUE THREAD

**Issue by kcsahoo** [primefaces/primeng#3026]
I have a DataTable which is scrollable.
If You have a dropdown list in a column in DataTable row and the DataTable height is less than the height of the DropDownList when clicked, the overflow does not show even if style is set to overflow:visible.
Instead, the scroll bar shows in DataTable and you have to scroll down to see the Dropdown list which is not intuitive at all. The user also does not think that the dropdown list is expanded.
It used to work before.
After PrimeNG V4.02, it does not work.
A number of changes in DropDown list has affected this.

**Comment by cagataycivici** [comment]
Provide a plunkr please so that we can review/reopen if necessary.

http://plnkr.co/edit/VZbdZfQ7SuTV87tTkbYR?p=preview

**Comment by rachelbr** [comment]
I'm also have this problem
For exp the calendar is opened behind the scrolled table
also the vertical lines moved...
![image](https://user-images.githubusercontent.com/16877732/29169609-7fe14628-7ddd-11e7-8771-a29675a8d5af.png)

**Comment by rachelbr** [comment]
I'm also have this problem
For exp the calendar is opened behind the scrolled table
also the vertical lines moved..
![image](https://user-images.githubusercontent.com/16877732/29170440-4c96fd4a-7de1-11e7-892f-6936b19a09d5.png)
