### ISSUE TITLE
Bug when resize columns in datatable inside an expanded row

### ISSUE THREAD

**Issue by gillesfabre34** [primefaces/primeng#3031]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => Search github for a similar issue or PR before submitting
```

**Current behavior**
When I try to resize columns in a p-datatable inside another p-datatable (i.e. inside an expanded row), all columns are resized with very strange lengths.

**Expected behavior**
I can resize correctly datatable columns when my datatable is inside an expanded row 

**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/cNDzVixgh566qVL7pgxq?p=preview
 
* **Angular version:** 4.0.1

* **PrimeNG version:** 4.0.0

* **Browser:** [ Chrome 58 ]

 
* **Language:** [TypeScript 2.3.2 | ES6 ]

* **Node (for AoT issues):** `node --version` = 6.10.3

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
