### ISSUE TITLE
datatable filtering/pagination does not clear selection

### ISSUE THREAD

**Issue by Ketec** [primefaces/primeng#3032]
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
Selectign a row and then filtering does not trigger row unselect event and  the row remains selected - even if it's not in the filtered results.

**Expected behavior**
The selection is cleared, allowing any data/modals etc loaded  to be reset when the selected row vanishes and is no longer in view. Configurale option if some prefer it this way.
But it causes confusion when modal has data for one row yet none are visibly selected.

**Comment by cagataycivici** [comment]
Common is what datatable does so if you want to change it at onFilter and onPage events, you can hook-in and clear the selection.

**Comment by rwngallego** [comment]
How do you clear the selection?
