### ISSUE TITLE
Modify Paginator style within DataTable Footer

### ISSUE THREAD

**Issue by karthiks3000** [primefaces/primeng#3033]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

I have implemented server side pagination and am using the paginator control within the footer of my datatable. However, i want to remove the border of the paginator that appears. It looks like this right now - 
![image](https://user-images.githubusercontent.com/13357707/26932354-40984d00-4c31-11e7-9988-1b49a8782086.png)

Here is my code
```
 <p-footer>   
                        <p-paginator rows="{{pageSize}}" totalRecords="{{totalRecordCount}}" [rowsPerPageOptions]="[10,20,30]" (onPageChange)="paginate($event)" [style]="{'border': none}"></p-paginator>
                                              
                        <div class="ui-helper-clearfix">
                            <div *ngIf="programRecords">Displaying {{dtPrograms.dataToRender?.length}} of {{totalRecordCount}} Record(s)
                                <button type="button" [disabled] = "selectedProgramRecords.length == 0 && selectedEpisodeRecords.length == 0 && selectedSeasonRecords.length == 0" pButton icon="fa-hand-spock-o" iconPos="left" label="Claim" (click)="claimRecords()" style="float:left" pTooltip="Claim Selected Tasks" tooltipPosition="top" tooltipEvent="hover"></button>                               
                                <button type="button" pButton icon="fa-file-excel-o" iconPos="left" label="CSV" (click)="dt.exportCSV()" style="float:right"></button>       
                            </div>                        
                        </div>                                                  
                    </p-footer>  
```

**Expected behavior**

setting the border property to none should ideally remove the border line, but it doesn't seem to make a difference.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.4.9

* **PrimeNG version:** 2.0.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by sudheerj** [comment]
Please use forum for questions like this. You can use below snippets.It works well.
`[style]="{'border':'none'}"`
