### ISSUE TITLE
Filter for Picklist

### ISSUE THREAD

**Issue by Mrtcndkn** [primefaces/primeng#3036]
Filter property for picklist.

**Comment by LordRudra** [comment]
Hi, I am using picklist component in my project, but seems callback event onSourceFilter is not working.
I expected this call when user enters filter criteria.
my code

<p-pickList #bapl [source]="availableBusinessAreaList" [target]="agentBankAccountDetailsForm.businessAreas" sourceHeader="Available Business Area"
							 targetHeader="Selected Business Area" [responsive]="true" filterBy="code" dragdrop="true" dragdropScope="businessAreas"
							 sourceFilterPlaceholder="Search" targetFilterPlaceholder="Search" [showSourceControls]="false" [showTargetControls]="false"
							 (onSourceFilter)="onSourceFilter()">
