### ISSUE TITLE
Services for PrimeNG

### ISSUE THREAD

**Issue by thormentor** [primefaces/primeng#3047]
I wonder if there are services for NGPrime similar to the ones that exist for ng-bootstrap?

**Comment by cagataycivici** [comment]
Please use forum cases like these.

**Comment by thormentor** [comment]
@cagataycivici ok, can you point me to a NGPrime forum or in the right direction for my question? Thank you.

**Comment by sudheerj** [comment]
Please do some search
  forum.primefaces.org

**Comment by onursenture** [comment]
The exact location of PrimeNG forum is https://forum.primefaces.org/viewforum.php?f=35
