### ISSUE TITLE
Upgrade to Chart.js 2.x

### ISSUE THREAD

**Issue by matmunk** [primefaces/primeng#305]
Upgrade to Chart.js 2.x (currently 2.0.2) from Chart.js 1.0.2.

**Comment by cagataycivici** [comment]
We'll do it for beta.6.

**Comment by timomayer** [comment]
cool thanks :) will you update to latest 2.1 version instead of 2.0.x?

**Comment by cagataycivici** [comment]
It seems 2.1 is latest so we'll do 2.1.

**Comment by cagataycivici** [comment]
Postpone to beta7.

**Comment by syriuszp** [comment]
Well Chart.js from version 2 have a different way of making instance of the chart, different bunch of options and many others new things I am not aware. What the pity to postpone to beta7. I have to look perhaps I can some how contribute to rewrite charts portion.

**Comment by cagataycivici** [comment]
Beta7 will be released on friday.
