### ISSUE TITLE
panel menu / menu item

### ISSUE THREAD

**Issue by marius-oprea** [primefaces/primeng#3053]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

I want to be able to customize more the panel menu / menu items and their behavior:
- add multiple[array] texts with different css styles on the same item menu
- add multiple[array] icons with different css styles on the same item menu
- choose the positions/location of icons and texts in the same menu item
- add clickable/button functionality for each of the texts and icons in the menu item

While the current aspect/behavior of the panel menu and menu items in general is just fine for most web applications, there are some situations when you want to add extra texts and icons on a menu item and also to add click/hover(others) functionality to some texts or icons

**Comment by cagataycivici** [comment]
If more users demand it, we'll reconsider, thank you.

**Comment by samIntegrateur** [comment]
I would like custom HTML for menu item, I guess it would respond to marius-oprea requests too. I have a use case : I need to add checkbox in front of item menu, is there a way to do that for now?
