### ISSUE TITLE
New Directive: Scrollbar

### ISSUE THREAD

**Issue by marius-oprea** [primefaces/primeng#3054]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
`

Create an Angular4 scrollbar component similar to ng2-slimscroll for examle ( https://github.com/jkuri/ng2-slimscroll ) that can be fully customizable and works the same on all major browsers (Chrome, Firefox, IE11, Edge, Opera), having the same functionality as a native browser scrollbar. Only the graphical styles should be changed.

I saw that nanoscroller is used in primeng projects, but is jQuery with js ES5 and this is not appropriate for Angular 4 projects. 

Something with pure Typescript respecting the Angular4 style guide(https://angular.io/docs/ts/latest/guide/style-guide.html)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
