### ISSUE TITLE
Native support for Grid CSS

### ISSUE THREAD

**Issue by marius-oprea** [primefaces/primeng#3055]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
Create additional layouting system using the latest CSS grid functionality with display: grid (https://www.w3.org/TR/css-grid-1/)
For the older browsers, a fallback to flexbox layout should be provided.

**Comment by kolkov** [comment]
Greetings! I apologize, but what about this issue?

**Comment by yigitfindikli** [comment]
You can check out [PrimeFlex](https://primefaces.org/primeng/showcase/#/primeflex).
