### ISSUE TITLE
input is repeated on Spinner

### ISSUE THREAD

**Issue by hryktrd** [primefaces/primeng#3058]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/VZbdZfQ7SuTV87tTkbYR?p=preview

**Current behavior**

On spinner, When I input 123 with iphone, 123123 is inputted.  And I test on chrome with IME-ON,
same probrem  occurs. (I input 123 with IME-ON, And Press F10 to change single-byte character.)

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.0.0

* **PrimeNG version:** 4.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   6.0.0

**Comment by ryanstroh** [comment]
Having this issue on Samsung s8 and samsung s5 chrome browser

**Comment by arjunshankar** [comment]
This issue has been in review for sometime. Is the PR a viable fix ... ?

**Comment by arjunshankar** [comment]
@hryktrd were you able to find any workarounds for this ??

**Comment by hryktrd** [comment]
@arjunshankar 
Yes, I sent pull request https://github.com/primefaces/primeng/pull/3113 but that hasn't merged.

**Comment by arjunshankar** [comment]
@hryktrd 
I tried using your code by extending the component. I can still reproduce the bug on Galaxy S8/S7/S6/S5 on the chrome browser while using the samsung keyboard.

The default Samsung browser seems to work fine. Also if you use any other keyboard.. like swype. that works fine as well.

What is the root cause of this issue ??
Thanks in advance.

**Comment by hryktrd** [comment]
Current code is written like [value]="valueAsString" to refrect formatted value to <input> element, but  valueAsString is not changed after keyup event and new value by IME is written after keyup event.
That is cause what I can understand of this issue.
I can't find out cause of your sumsung keyboard issue, sorry...

**Comment by cagataycivici** [comment]
Does it still happen with 4.2.1? I can't replicate on iPhone.

**Comment by hryktrd** [comment]
If you use 4.2.1 in Demo( https://www.primefaces.org/primeng/#/spinner ), It still happen in iphone(Japanese mode).

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
