### ISSUE TITLE
Responsive Datatable seems to be broken

### ISSUE THREAD

**Issue by darkwarriorn4p** [primefaces/primeng#306]
It seems that the responsive Datatable don't work correct.

--> See attached screenshot
![2016-05-04 11_36_37-clipboard](https://cloud.githubusercontent.com/assets/1255481/15010505/9d31bc70-11ec-11e6-9bbc-50d6d055f948.png)

Tested on Chrome & Firefox.

Using primeng1.0.0-beta.4 and angular2.0.0-beta.17

**Comment by Mrtcndkn** [comment]
It's now fixed for 1.0.0-beta.5
