### ISSUE TITLE
Alpha support for ColorPicker

### ISSUE THREAD

**Issue by simonwidjaja** [primefaces/primeng#3065]
I'm submitting a
```
[X] feature request
```
I would like to see alpha/transparency/rgba support for the new upcoming colorpicker.
Here is a sample of another ng2 color picker. Lacking alpha support is a showstopper for us, but I would love to switch over to PrimeNG's colorpicker soon ;) BTW: Keep up the amazing work!!!!

**Comment by epaitz** [comment]
Yes please add support for alpha (rgba).

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by orestisioakeimidis** [comment]
Hello @mertsincan! Support for alpha channel has not been added yet to the color picker component. Can we re-open this issue and add support for it?

**Comment by m3hari** [comment]
@mertsincan 
Yes +1 please. Here is a related issue https://github.com/primefaces/primevue/issues/2523

The color picker now is so basic. Transparency adjustment and eye-dropper are essential parts of color picker component. Here is Vuetify for reference 
![Screenshot 2024-10-10 at 16 13 43](https://github.com/user-attachments/assets/3d31f745-1e9c-43ad-b7b6-5942b360f610)

**Comment by Ronkiro** [comment]
https://github.com/orgs/primefaces/discussions/3131
