### ISSUE TITLE
Datatable filter filters and triggers event every time column is sorted

### ISSUE THREAD

**Issue by Ketec** [primefaces/primeng#3066]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
If you use column filter and then use sort, onFilter fires every time you sort the column. 

**Expected behavior**
It should sort filtered results and not sort the whole dataset and then filter it again - and trigger the filter event only on user input or when data changes.

**Comment by cagataycivici** [comment]
Unable to replicate, maybe I got the case wrong, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
