### ISSUE TITLE
<p-dataTable > multiple selection doesn't fill the model

### ISSUE THREAD

**Issue by UlricW** [primefaces/primeng#3068]
[x] bug report 
[ ] feature request
[ ] support request 

**Current behavior**
When we use the p-dataTable with selection mode input to multiple, the selection of a row doesn't fill the selection array. 

**Expected behavior**
When we use the p-dataTable with selection mode input to multiple, the selection of a row fill the selection array. 

**What is the motivation / use case for changing the behavior?**
Update the version of PrimeNG to 4.x.x

* **Angular version:** 4.0.2

* **PrimeNG version:** 4.0.2

* **Browser:** [all ]
 
* **Language:** [TypeScript 2.1.5 ES5]

```
<p-dataTable [value]="resultList" [paginator]="false" [rows]="10" [responsive]="true [rowHover]="isHover" (onRowClick)="consultLine($event)"  [(selection)]="selectedObjects" [rowStyleClass]="rowClassFunction">

        <p-column  selectionMode="multiple"></p-column>

        <p-column *ngFor="let column of columns; let index = index"
                  [field]="column?.field"
                  [header]="column?.header"
                  [sortable]="column?.sortable"
                  [filter]="column?.filter"
                  [filterMatchMode]="'contains'"
                  (sortFunction)="sortFunction($event)">
        </p-column>

</p-dataTable>
```

**Comment by cagataycivici** [comment]
https://www.primefaces.org/primeng/#/datatable/selection

Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
