### ISSUE TITLE
Visible flag support for Menu

### ISSUE THREAD

**Issue by marcuzy** [primefaces/primeng#3072]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/I43mWXXoYwblaCrcAu7A?p=preview

**Current behavior**
`visible` flag is not supported by Menu component, meanwhile MenuItem interface contains such property. 

**Expected behavior**
If `visible` property is set to false, menu item must be hidden.

**What is the motivation / use case for changing the behavior?**
Without `visible` support I should remake array with menu items and that's is uncomfortable. In addition, MenuItem contains `visible` property.

* **PrimeNG version:** 4.0.3

**Comment by johnhwright** [comment]
At the very least they should all behave the same.
https://embed.plnkr.co/nq2UzeKqYnqCDGXmNcTx/

For example, the p-contextMenu does actually hide the menu items when the visible property is false. But both the p-menu and p-menubar do not. Though they all seem to respect the disabled property.

**Comment by New-Key** [comment]
This issue was added to he milestone 4.1.1 I've been waiting the fix a while, tracking the milestone, what are the reason to reconsidered this issue not yet solved?

**Comment by k20human** [comment]
The bug still exists in 4.1.1

I don't see any trace of visible in [menu.ts](https://github.com/primefaces/primeng/blob/56d1be286368817309698cf03a95d1e950e7c785/src/app/components/menu/menu.ts) or [tabmenu.ts](https://github.com/primefaces/primeng/blob/56d1be286368817309698cf03a95d1e950e7c785/src/app/components/tabmenu/tabmenu.ts)

Seems that PR #3073 was rollback?

**Comment by cagataycivici** [comment]
Set to 4.1.4.

**Comment by jonnomk** [comment]
This is still an issue for the Steps component in PrimeNG v.11.4.0. If I set visible to false, the item still renders.

**Comment by JerinJ** [comment]
The visible flag is not taking runtime updates, that is if the user changes the role some menu options need to be hidden.

**Comment by masalinas** [comment]
This is still an issue for the Steps component in PrimeNG v.14.2.3. If I set visible to false, the item still renders.
