### ISSUE TITLE
Listbox custom style

### ISSUE THREAD

**Issue by Mrtcndkn** [primefaces/primeng#3077]
When custom width added to the list filter does not fit to the custom size.

**Comment by M0nter0** [comment]
Is this back in 8.0.2? I've ask it in [the forum](https://forum.primefaces.org/viewtopic.php?t=51300) without success. I've created a [stackblitz example](https://stackblitz.com/edit/listboxexample) so you can test it.

```
<p-listbox [options]="cities" [(ngModel)]="selectedCities" multiple="multiple" checkbox="checkbox" filter="filter" optionLabel="name"
[listStyle]="{'max-height':'150px', 'width':'300px'}">
  <p-header>
    Cities
  </p-header>
</p-listbox>
```

**Comment by kanikagarg7** [comment]
Hi,
Is there any way we can change filter from p-listbox to text.
I need to show text as"Select all" instead of filter in listbox
