### ISSUE TITLE
Primeng Error on Samsung Tab A

### ISSUE THREAD

**Issue by limjoonae** [primefaces/primeng#3078]
Hello. when i open my web i found error

![image](https://user-images.githubusercontent.com/3191903/27079593-6756ed40-5062-11e7-8042-09e04cba05ca.png)

and all component of primeng is not responding.
but  other device is normally responding.

Please help me to resolve. thank you.

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
