### ISSUE TITLE
Nested Data Source Updates Not Reflected In Displayed Table

### ISSUE THREAD

**Issue by jamesdking** [primefaces/primeng#3091]
[X] bug report
[ ] feature request
[ ] support request

http://plnkr.co/edit/RbRVczksRejBo0kd0Y4E?p=preview

**Current behavior**
Adding items to a nested collection that is the data source of the table does not update the display of the table.

**Expected behavior**
Modification of a nested data source should function exactly like a non-nested data source.

* **Angular version:** 4.0.X
* **PrimeNG version:** 4.0.3
* **Browser:** [Chrome 52] 
* **Language:** [TypeScript 2.2.2]

**Comment by jefftham** [comment]
http://plnkr.co/edit/jQS8ecVKdGySamg8kIZm?p=preview

it is partially working on version 2.0.6

**Comment by cagataycivici** [comment]
DataTable is deprecated in favor new p-table and not maintained anymore.
