### ISSUE TITLE
Accordion on Chrome is auto opening with multiple true

### ISSUE THREAD

**Issue by sgentile** [primefaces/primeng#3097]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
```
<p-accordion [multiple]="true">
            <p-accordionTab header="Add XYZ">
                <content>...</content>
            </p-accordionTab>
            <p-accordionTab header="Add ABC">
                 <content>...</content>
            </p-accordionTab>            
        </p-accordion>
```

**Expected behavior**
If should not have either tab expanded -but it's showing both, and when you click to 'close' it's thinking it's already closed - so you have to click twice.   But it should be closed by default

**Minimal reproduction of the problem with instructions**

* **Angular version:** 2.0.X
4

* **PrimeNG version:** 2.0.X
4.0.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome - but not Firefox
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

* **Node (for AoT issues):** `node --version` =   
Both AOT and not AOT

**Comment by Mrtcndkn** [comment]
Could you please create a plunkr about it because i can't replicate it.

http://plnkr.co/edit/Wj39h1?p=preview

When I try it looks like this
https://pasteboard.co/1lathoMs3.png

@sgentile
