### ISSUE TITLE
Focus and Blur events for Editor

### ISSUE THREAD

**Issue by immayank26** [primefaces/primeng#3114]
**I'm submitting a feature request for onFocus and onBlur events for primeng editor**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/VZbdZfQ7SuTV87tTkbYR?p=preview

This issue has not been reported yet.

**Current behavior**
The current primeng editor does not support focus and blur events.
Reference: https://forum.primefaces.org/viewtopic.php?f=35&t=51304&sid=b3e4042540bcfb40f90a36d7d0038a7f

**Expected behavior**
like (click) event, if we can support the (focus) and (blur events)

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
javascript supports blur and focus events and many other rich text editors support all the event listeners like click, focus, blur etc. These events can help in creating a much more responsive angular application with the use of primeng editor.

**Please tell us about your environment:**

* **Angular version:** 2.0.X
4.1.3

* **PrimeNG version:** 2.0.X
4.0.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   6.10.3

**Comment by supriyaraj03** [comment]
I would also like to have this feature inplace and I see that its not something very difficult if it is already implemented in onTextChange.

**Comment by sgentile** [comment]
Any updates on when this is planned ?

**Comment by leonetosoft** [comment]
This is very necessary!

Users are accustomed to Excell behavior.
That way it's very strange, you click edit the field, click on another field, the old one continues with the value you entered, but the editComplete was not fired ...

**Comment by bweitjensES** [comment]
This workaround didn't work for my, but I found a workaround mentioned in the quill editor (https://github.com/quilljs/quill/issues/2186#issuecomment-533401328) that I got to work:
```
export class MyComponent extends implements AfterViewInit{
  @ViewChild('pEditor')
  public editor: Editor;

  ngAfterViewInit() {
    this.editor.getQuill().editor.scroll.domNode.addEventListener('focus', this.onFocus.bind(this));
    this.editor.getQuill().editor.scroll.domNode.addEventListener('blur', this.onBlur.bind(this));
  }
  
  onFocus(): void {
  }

  onBlur(): void {
  }
} 
```

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by FloreaAndrei22** [comment]
This issue still happens (or happens again) in version 15.4.1.

The editor's (blur) event is emitted only if another field in the form group is selected.
