### ISSUE TITLE
DataTable - table.reset() clears visible sorted column but sort is not cleared

### ISSUE THREAD

**Issue by gatapia** [primefaces/primeng#312]
I think reset should either:
- Clear the sort column styling and also the sorted contents (back to original content)
or
- Not clear the sort column styling and leave sorting in place

Currently its a bit confusing (from a usability perspective).

**Comment by cagataycivici** [comment]
I see but how can we unsort it ? :)

**Comment by gatapia** [comment]
I currently have a hack where I do the following:
```
# template
<button (click)="reset(table)">Reset Table</button>
<p-datatable #table [value]="data" ...
# component
init() {
  $http.get(..., (data) => { 
    this.data = data;
    this.cloned = data.slice(0);
  });
}

reset(table) {
  table.reset();
  this.data = this.cloned.slice(0);
}
```


This unsorts the data.  However, this is not ideal as it will not work with the default sort of the table.  

I'm not familiar with DataTable's internals, does sorting actually change the bound array? I.e. Is my component's data array actually changed? If not just use that again.  If it is then perhaps; maybe add a data attribute to the TR dom node with its initial order and use this to sort?  Or perhaps have a map of some sort where a reference to each row's data is used to lookup its original index?  Something like.

```
# in datatable.ts
... after initial default sort
this.initialState = this.value.map((row, idx) => [row, idx]);

... after table reset
// use initialState to sort the this.value
```

To be honest I'm not familiar enough with DataTable's internal to give good suggestions.  This is also a very minor issue so it would be a shame to sacrifice memory or performance for this but perhaps there is something efficient that can be done.

**Comment by cagataycivici** [comment]
Yes, the actual data is changed, we don't keep a copy and would rather not. I think this make a complex component much more complex and I cannot think of a good way to do it so leave it to user to provide new unsorted data as reset just cleans up the visuals like page-sort-filter.

**Comment by NagarajNayakG** [comment]
use 
reset(table) {
  table.reset();
  table.updateDataToRender(data);
  this.data = this.cloned.slice(0);
}

**Comment by MedinaGitHub** [comment]
not work for my
