### ISSUE TITLE
Autocomplete dropdown and multiple features issue

### ISSUE THREAD

**Issue by sudheerj** [primefaces/primeng#3124]
When we use autocomplete with both dropdown and multiple features then you can observe autocomplete component alignment issue as below
`<p-autoComplete [(ngModel)]="topcountry" name="eventsMultiple" [suggestions]="filteredTopAsiaCountries"
                            (completeMethod)="filterTopAsiaCountries($event)"
                            [minLength]="1" placeholder="Type top asia country name" [dropdown]="true" [multiple]="true"
                            (onFocus)="onFocus()" (onBlur)="onBlur()" (onSelect)="onSelect()"
                            (onUnselect)="onUnselect()" (onClear)="onClearInput($event)"
                            (onDropdownClick)="handleDropdownClick($event)">
            </p-autoComplete>`

![image](https://user-images.githubusercontent.com/3127317/27250446-82e6094e-5362-11e7-96f4-5d470080d8cf.png)

**Comment by cagataycivici** [comment]
Can't replicate with master;

<img width="443" alt="screen shot 2017-06-28 at 12 03 15" src="https://user-images.githubusercontent.com/686247/27629093-d4785a24-5bf9-11e7-9f17-f4fab7cbe53e.png">

Please provide a plunkr if issue persists.
