### ISSUE TITLE
Remove item with backspace in autocomplete multiple mode

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#313]
When there is no value in text field and backspace is hit, remove the previously selected item in autocomplete multiple mode.

**Comment by well-made** [comment]
Would be nice if this is an option.
If this option is false, only way to delete a previous selected item would be using the "x".
Is that possible to implement?

**Comment by vinay277** [comment]
can we disable backspace deleting when there is no text in the input field. Do we have any property to handle this functionality
