### ISSUE TITLE
Organization Chart - no lines, empty leafs, etc. for Bootstrap theme

### ISSUE THREAD

**Issue by ova2** [primefaces/primeng#3130]
PrimeNG 4.1.0-rc.2

The organization chart has no lines, leafs are empty, etc. when using Bootstrap theme. Please fix asap because we use this theme in the Angular & PrimeNG book. Thanks!

![image](https://user-images.githubusercontent.com/767334/27260313-2cf748f0-5429-11e7-8cff-1776fb6a8338.png)

**Comment by ova2** [comment]
@Mrtcndkn Many thanks for your quick fix! The book is safe :-)

**Comment by ova2** [comment]
@Mrtcndkn @cagataycivici Do you know the approx. release date of PrimeNG 4.1?

**Comment by Mrtcndkn** [comment]
@ova2 Great glad to hear that :) Release will be in next week.
