### ISSUE TITLE
Datatable error

### ISSUE THREAD

**Issue by tejadong** [primefaces/primeng#3131]
Someone tells me, why does this happen?

<a href="http://es.tinypic.com?ref=2uyg7lu" target="_blank"><img src="http://i67.tinypic.com/2uyg7lu.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
