### ISSUE TITLE
Focus on filter when dropdown is opened with key

### ISSUE THREAD

**Issue by hzahed** [primefaces/primeng#3135]
When the DropDown (Content with Filter) is opened by keyboard shortcuts (Space or Alt+ Down), filter input is not focused and can not be reached even with tab key.

**Comment by yigitfindikli** [comment]
Unable to replicate with latest PrimeNG, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
