### ISSUE TITLE
AutoComplete 'filled' property should reflect dropdown selection too. 

### ISSUE THREAD

**Issue by dags** [primefaces/primeng#3143]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/upId5H?p=preview

**Current behavior**
Currently, AutoComplete 'filled' property doesn't reflect any change input coming from dropdown selection. Because of this, md-inputfield label animation doesn't work as expected making the label to overlap selected value when leaving the component. Class md-inputfield is present on some templates, like Ultima. 

**Expected behavior**
AutoComplete 'filled' property should reflect any dropdown selection changing to 'true' when a value has been selected and to 'false' if null value has been selected. This should make md-inputfield label animation to work as expected. Class md-inputfield is present on some templates, like Ultima. 

**Minimal reproduction of the problem with instructions**
Please use this plunker http://plnkr.co/edit/upId5H?p=preview and verify 'Filled' output : 
1) enter a v and will see Filled as true
2) remove any value and see Filled as false
3) with an empty autocomplete, select a value from dropdown and will se Filled don't change.

**What is the motivation / use case for changing the behavior?**
To get md-inputfield label animation working in all cases as expected.

**Please tell us about your environment:**
Linux BB-8 4.4.0-79-generic #100-Ubuntu SMP Wed May 17 19:58:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

* **Angular version:** 2.0.X
@angular/cli: 1.0.0
node: 6.11.0
os: linux x64
@angular/common: 4.1.0
@angular/compiler: 4.1.0
@angular/core: 4.1.0
@angular/forms: 4.1.0
@angular/http: 4.1.0
@angular/platform-browser: 4.1.0
@angular/platform-browser-dynamic: 4.1.0
@angular/router: 4.1.0
@angular/animations: 4.1.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.1.0

* **PrimeNG version:** 2.0.X
4.0.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
any

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 

* **Node (for AoT issues):** `node --version` =

**Comment by dags** [comment]
what milestone is this assigned to ?

**Comment by dags** [comment]
Any news about this issue ?

**Comment by yigitfindikli** [comment]
Unable to replicate with latest PrimeNG, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
