### ISSUE TITLE
Autocomplete empty text when lost focus

### ISSUE THREAD

**Issue by lukgit17** [primefaces/primeng#3147]
After replace following code 
`[value]=\"value ? (field ? resolveFieldData(value) || value : value) : null\"` 
with 
`[value]=\"value ? (field ? resolveFieldData(value) || '' : value) : null\"` 
result in this issue :
- If i have an object in ngModel with properties, where one property is declarated in field, if search and select with enter value from items list then when lost focus text in autocomplete will become empty. But if i select from items list with mouse click text will remain after lost focus. this issue not appear with old code.

PrimeNg version : 4.1.0-rc.2
Angular version : 4.2.3

**Comment by failpunk** [comment]
Yeah, this showed up for me when I upgraded to 4.1.  I have to revert.

**Comment by cagataycivici** [comment]
Replicated.
