### ISSUE TITLE
dropdown: custom object comparison function

### ISSUE THREAD

**Issue by just-jeb** [primefaces/primeng#3149]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**

Objects are always compared with `objectUtils.equals`

**Expected behavior**

Sometimes there is a need to compare objects (for selection) with a custom comparison function.
It would be nice to have it as optional property of the component.

* **Angular version:** 4.1.3

* **PrimeNG version:** 4.0.1

* **Browser:** all

 
* **Language:** all

I can create a PR for this if needed.

**Comment by cagataycivici** [comment]
We have dataKey for many data components, we can do the same here, thoughts? When it is present, ObjectUtils uses that.

**Comment by meltedspark** [comment]
Specifically for my case `dataKey` is not robust enough. And I don't think I'm alone in this.
`dataKey` allows just comparison by nested field. If I want to compare by two fields, it's impossible.
What I currently do to bypass this issue (and not only in dropdown) is overriding `Dropdown.prototype.findOptionIndex` method. But frankly I would expect it to be supported on the framework level.
What do you think? I can provide an implementation.

**Comment by cagataycivici** [comment]
Maybe we should just ask for equals() function in the objects? If there is equals function in the object, we can just call it.

**Comment by meltedspark** [comment]
This might work. But it also has downsides.
What if the object does have `equals` function but I still want to compare it (specifically for the dropdown selection) differently?
Also, what gets the higher priority, `dataKey` or `equals`? You wouldn't know, it depends on what the user wants.
In addition, the objects being compared are mostly pure data objects, in many cases received from the server. I wouldn't want to put on each such an object equality function just to make it selectable properly in dropdown.
Anyway, even allowing object comparison by equality function will be much better than now. I just don't think it's robust enough.
Thoughts?

**Comment by cagataycivici** [comment]
A custom function sounds good.

**Comment by meltedspark** [comment]
Shall I create a PR?

**Comment by twmobius** [comment]
I think `p-dropdown` should follow the way `SelectControlValueAccessor` is using `[compareFn]` to change the comparison algorithm

**Comment by PaddingtonTheBear** [comment]
This is definitely a needed functionality on dropdowns, multiselect, listboxes, etc. Other libraries and even Angular support this, I don't see the harm of including additional functionality for this.

**Comment by shdk** [comment]
Any news on this?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
