### ISSUE TITLE
radioButton: custom object comparison function for checked/unchecked state

### ISSUE THREAD

**Issue by just-jeb** [primefaces/primeng#3151]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**

Objects are always compared with `==` operator (`this.checked = (value == this.value)`)

**Expected behavior**

Sometimes there is a need to compare objects (for `checked` state) with a custom comparison function.
It would be nice to have it as optional property of the component.

* **Angular version:** 4.1.3

* **PrimeNG version:** 4.0.1

* **Browser:** all

 
* **Language:** all

I can create a PR for this if needed.

**Comment by cagataycivici** [comment]
A custom function sounds good.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
