### ISSUE TITLE
Going backwards/forward in time should switch AM/PM toggle

### ISSUE THREAD

**Issue by SIlver--** [primefaces/primeng#3156]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Right now, when you go from 12pm and click backwards, the time goes to 11PM instead of 11AM.

**Expected behavior**
The time should be 11AM. The issue doesn't occur for the 24 hour clock for obvious reasons.

**Minimal reproduction of the problem with instructions**
![animation](https://user-images.githubusercontent.com/6362347/27350411-49d2a9a6-55c8-11e7-9244-b9cdc5c3a9e8.gif)

**What is the motivation / use case for changing the behavior?**
The time changing switching logic should be done in the component itself.

* **Angular version:** 4.2

* **PrimeNG version:** 4.1.0

* **Browser:** [all ]

 
* **Language:** [all ]

**Comment by cagataycivici** [comment]
Let's wait for more feedback.

**Comment by yigitfindikli** [comment]
Unable to replicate with latest PrimeNG, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
