### ISSUE TITLE
ULTIMA's dropdown panel scrolling behavior differ to Standard theme.

### ISSUE THREAD

**Issue by kojisaiki** [primefaces/primeng#3157]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/Wj39h1?p=preview

**Current behavior**
In standard theme (one applied to PrimeNG page https://www.primefaces.org/primeng/#/dropdown ), dropdown panel has next behavior.

step1. select the lowest item, panel is closed automatically.
![image](https://user-images.githubusercontent.com/10954150/27372045-241adf22-569e-11e7-877a-32c755690993.png)

step2. panel reopen, and scroll to top manually. And close with outside click(do not select item).
![image](https://user-images.githubusercontent.com/10954150/27372095-5a4bac66-569e-11e7-848b-cf59d55bdd10.png)

step3. panel reopen, panel is scrolled to selected item position, automatically.
![image](https://user-images.githubusercontent.com/10954150/27372045-241adf22-569e-11e7-877a-32c755690993.png)

But, in ULTIMA theme is worked like following behavior.

step1. select the lowest item, panel is closed automatically.
![image](https://user-images.githubusercontent.com/10954150/27372336-3dedf38e-569f-11e7-85df-d7cd16b220ec.png)

step2. panel reopen, and scroll to top manually. And close with outside click(do not select item).
![image](https://user-images.githubusercontent.com/10954150/27372358-5127e248-569f-11e7-83b8-d3000cfafb50.png)

step3(trouble behavior). panel reopen, but panel is not scrolled to selected item position.
![image](https://user-images.githubusercontent.com/10954150/27372406-848cd454-569f-11e7-88c7-1806f38dc190.png)

**Expected behavior**
Scrolling to selected item position automatically, like standard theme.
![image](https://user-images.githubusercontent.com/10954150/27372336-3dedf38e-569f-11e7-85df-d7cd16b220ec.png)

**Please tell us about your environment:**

* **Angular version:** 2.0.X
Latest primeng's web page.

* **PrimeNG version:** 2.0.X
Latest primeng's web page.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Google Chrome 58.0.3029.110
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Please use Ultima forum to report issues instead of PrimeNG tracker as our support team monitors it for Ultima related cases.
