### ISSUE TITLE
Style 05-16 Don't prefix output properties

### ISSUE THREAD

**Issue by wndproc1** [primefaces/primeng#3158]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
N/A

**Current behavior**
Many events are named with the prefix 'on' (runs counter to the Angular Style Guide). 
    <p-chips
        (**onAdd**)="onAdd($event.value)"
        (**onRemove**)="onRemove($event.value)">
    </p-chips>

**Expected behavior**
Remove the prefix 'on' from the event name or provide both 'add' and 'onAdd' events
    <p-chips
        (**add**)="onAdd($event.value)"
        (**remove**)="onRemove($event.value)">
    </p-chips>

**Minimal reproduction of the problem with instructions**
N/A

**What is the motivation / use case for changing the behavior?**
In [Angular Style Guide 05-16](https://angular.io/guide/styleguide#dont-prefix-output-properties), 
it is defined as
- Do name events without the prefix on.
- Do name event handler methods with the prefix on followed by the event name.
Based on those style guide, we've implemented code validation rules but many PrimeNG modules does not follow the guideline so we had to disable the validation for 05-16.

**Please tell us about your environment:**
Windows, VSCode

* **Angular version:** 2.0.X
4.2.3

* **PrimeNG version:** 2.0.X
4.0.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

* **Node (for AoT issues):** `node --version` =   
all

**Comment by sudheerj** [comment]
+1 from my side. It has to be refactored across components. Good to work on these kind of breaking changes in major releases.

**Comment by cagataycivici** [comment]
Angular Style guide is opinionated advisory document, we'll stick to on, I frankly really like on instead of (add)=? which is confusing. Add what?
