### ISSUE TITLE
Project does not compile with implicit/strict compiler checks

### ISSUE THREAD

**Issue by zkonstas** [primefaces/primeng#3159]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
The codebase does not follow the strict Typescript styleguide. Specifically:
- There are variables with no type annotations. Therefore they have implicitly "any" type.
- There are implicit returns in some functions
- There are null or undefined assignments to variables that do not have a type "X | null | undefined"

For the above reasons when compiling a project with the following strict compiler flags there are compilation errors:
- noImplicitAny: true
- noImplicitReturn: true
- strictNullChecks: true

**Expected behavior**
Compiling the project using the above flags should throw no compilation errors.

**Comment by cagataycivici** [comment]
If more users demand it, we'll reconsider supporting the styleguide.

**Comment by Maximaximum** [comment]
It would be great to reconsider this, because after switching to Ivy and enabling full template checks, a lot of errors are thrown

**Comment by Da13Harris** [comment]
These days, Angular uses strict mode by default, which causes these incompatibilities to be more common and forces developers to work around the issues.

Here is the advice from the Angular documentation to library authors:

> As a library author, you can take several measures to provide an optimal experience for your users. First, enabling strictNullChecks and including null in an input's type, as appropriate, communicates to your consumers whether they can provide a nullable value or not.

While I understand this would be a very significant undertaking, I believe it will make PrimeNG (and the other Prime libraries) more sustainable and competitive over time, as strict types become the standard for more and more projects.
