### ISSUE TITLE
MultiSelect Filter in Datatable crashes app when filterMatchMode="contains"

### ISSUE THREAD

**Issue by zkonstas** [primefaces/primeng#3161]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When using a multi-select filter in a datatable column and setting filterMatchMode="contains", then the application crashes with the following error:

ERROR TypeError: filter.toLowerCase is not a function

Also this seems related to this:
https://github.com/primefaces/primeng/issues/2403

**Expected behavior**
The application should not crash and the datatable should apply a "contains" filter to that column for each value of the selected values in the multi-select filter

**Minimal reproduction of the problem with instructions**
In the demo: https://www.primefaces.org/primeng/#/datatable/filter

do the following change in the datatablefilterdemo.html:

FROM:
 <p-column field="color" header="Color (Custom)" [filter]="true" **filterMatchMode="in"** [style]="{'overflow':'visible'}">

TO:
 <p-column field="color" header="Color (Custom)" [filter]="true" **filterMatchMode="contains"** [style]="{'overflow':'visible'}">

**Comment by cagataycivici** [comment]
This seems expected, contains is string search, for a collection search us in instead.
