### ISSUE TITLE
Bug in Multiselect findLabelByValue method

### ISSUE THREAD

**Issue by am4apps** [primefaces/primeng#3162]
[x] bug report => Search github for a similar issue or PR before submitting

**Current behavior**
You set the formControlName with a value(Object), value selected OK, labels display null,null...

**Expected behavior**
You set the formControlName with a value(Object), value selected OK, labels display the label properly 

**Minimal reproduction of the problem with instructions**
Assigned dynamically from another Object the Multiselect selected values.

**What is the motivation / use case for changing the behavior?**
Solve the findLabelByValue method to display labels properly when value is assigned with Dynamically from another Object

**Solution**
https://github.com/primefaces/primeng/pull/3160

* **Angular version:** 4.0.X

* **PrimeNG version:** 4.1.0.rc2

**Comment by cagataycivici** [comment]
Fixed via;

#1962
