### ISSUE TITLE
primeNG  multiple calendars on a page

### ISSUE THREAD

**Issue by Mounika30** [primefaces/primeng#3163]
I am using primeng multiple calendars on a page, whenever you select  a date in a first calendar Input , it gets populated with the date and  the other calendar input also gets populated with the selected date(first selected date of calendar input)

**Comment by CreamFraiche** [comment]
you need to have them set to different ngModels.... the ngModel attribute has to be different for both

**Comment by Mounika30** [comment]
I am using this calendar very generic ,so can't i use one calendar and populate each calendar input with different value.
just want to avoid duplication.pls suggest



app.component.ts:

export class AppComponent{
 private date3:Date
columnDefs = [
      
        {headerName: "Comments", field: "commenttxt", width: "30%"},
        { headerName: "StartDate", field: "strtdate",width: "10%",type:"date"},    
        { headerName: "Date/Time", field: "formattedDate", width: "20%",type:"date"},        
    ];
   
}

app.component.html file :
<p-column *ngFor="let col of column" [field]="col.field" [header]="col.headerName">     
<template *ngIf="col.type==='date'"  pTemplate="filter" let-col >
 
       <p-calendar [(ngModel)]="date3"  [showIcon]="true"  appendTo="body" ></p-calendar>

      </template>
</p-column

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview
