### ISSUE TITLE
PickList shows unexpected behaviour with metaKeySelection='false'

### ISSUE THREAD

**Issue by twdnr** [primefaces/primeng#3169]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/Wj39h1?p=preview  (Plunkr seems to be down or under load - can't fork)

**Current behavior**
PickList even with metaKeySelection="false" allows to select multiple elements. De-selecting an element of a multi-element selection does not work. Even if you don't hold any meta/control-key every click will add an element to the selection. In fact, you can only add more elements to a selection.

**Expected behavior**
Only on element should be selectable at a time when metaKeySelection="false".

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
WebStorm (latest), Mac OS X (latest)

* **Angular version:** 4.1.3

* **PrimeNG version:** 4.0.3, 4.1.0-rc.2

* **Browser:** Checked only Chrome, Safari on Mac OS X so far

* **Language:** TypeScript 2.3

* **Node (for AoT issues):** `node --version` =   8.1.2

**Comment by twdnr** [comment]
**Possible Solution:**
The onItemClick method in picklist.ts, the last `selectedItems.push(item);` will not clear the array. Therefore:
```
selectedItems.length = 0;
selectedItems.push(item);
```
might solve the problem.

**Comment by cagataycivici** [comment]
Should be;

[metaKeySelection]="false"

**Comment by twdnr** [comment]
You are wrong! Plunkr seems to run again now:

**http://plnkr.co/edit/JqlKYPbJA08rXnJmJQua?p=preview**

Please verify! Just click without pressing any meta key.

**Comment by twdnr** [comment]
Occurs on Safari and Chrome on Mac OS.

**Comment by twdnr** [comment]
Not solved. Reopened at #3182 - please verify my suggested fix to this problem.

**Comment by cagataycivici** [comment]
Review for 4.1.1

**Comment by cagataycivici** [comment]
Not sure if you understand what metaKeySelection works, here it does exactly what it is supposed to do. From docs;

Multiple items can either be selected using metaKey or toggled individually depending on the value of metaKeySelection property value which is true by default. On touch enabled devices metaKeySelection is turned off automatically.

**Comment by twdnr** [comment]
Ok, if that's the actual intention of the feature. I just wanted to avoid any multiple selections in any of the lists (pure single selection only). So I misunderstood the purpose of [metaKeySelection].

Meanwhile I forked pick-list and added that single-select-only feature for myself.

Sorry for the circumstances!
