### ISSUE TITLE
Add target and appendTo to all menu types

### ISSUE THREAD

**Issue by Tempus35** [primefaces/primeng#3170]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Menu components, including TieredMenu, SlideMenu etc do not allowing attaching/targeting where to open

**Expected behavior**
The ability to send in a target or set the appendTo behavior of all menu types.

**What is the motivation / use case for changing the behavior?**
Wanting to use a slideMenu not a contextMenu but I can not force target or attach points.

* **Angular version:**
Angular 4.2.3

* **PrimeNG version:** 
Prime 4.1.0-rc.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All

**Comment by cagataycivici** [comment]
Please create separate issue tickets so we can track each them properly.
