### ISSUE TITLE
Touch support for DragDrop

### ISSUE THREAD

**Issue by Zorgatone** [primefaces/primeng#3176]
**I'm submitting a ...**  (check one with "x")
- [x] bug report => Search github for a similar issue or PR before submitting
- [ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
- [ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Current behavior**
When trying to drag&drop on mobile (touch, hold, slide and release the finger on the screen) the page/viewport scrolls instead of dragging the html/dom element.

**Expected behavior**
It should drag&drop correctly how the desktop browsers do.

**Minimal reproduction of the problem with instructions**
You can navigate in a mobile browser to the primeNg documentation page (drag&drop section) or use the following code example on Plunkr (try to drag the small blue square onto the larger green square and it should alert message)

http://plnkr.co/edit/5BBUYLWUMikXyRaBX6bg?p=preview

**What is the motivation / use case for changing the behavior?**
Because all the other elements I tested worked on mobile, but drag&drop doesn't. Also it is very difficult to implement a drag&drop on mobile, so I think it's very important to give ready-to-use drag&drop element support directly in the primeNg library.

**Please tell us about your environment:**
Tested the drag&drop isn't working on iOS Safari, iOS Chrome and Android Chrome mobile browsers.

* **Angular version:** ^4.0.0

* **PrimeNG version:** 4.0.3

* **Browser:** Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView
 
* **Language:** TypeScript 2.3.4

* **Node (for AoT issues):** `node --version` = v8.1.2

**Comment by digaus** [comment]
Any progress on this?

**Comment by toketeeman** [comment]
Any more progress on this? We are in dire need to have PrimeNG drag-and-drop touch-ready.

**Comment by brennvs** [comment]
Please make it available for touch devices asap, thank you very much.

**Comment by digaus** [comment]
I think the problem is that touch devices do not support the native drag and drop implementation. Did a bit myself with manually copying the element on touch start but getting the element where you drop is difficult since you have to get it by calculating using the current position of the touch event and getting the element on that coordinate. Then you have to check if that element is wrapped by a parent element containing the droppable directive. 

It is possible but hard to do.

**Comment by kenyx89** [comment]
Moving to [jqTree](https://mbraak.github.io/jqTree/) for displaying hierarchical data.

**Comment by atruptoneatma** [comment]
Any Progress?

**Comment by digaus** [comment]
@atruptoneatma Switched to angular/cdk drag and drop which is far superior. It has so many more possibilities.

**Comment by atruptoneatma** [comment]
@digaus Thanks. I got angular/cdk  drag and drop, and it is helped me.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by puschie286** [comment]
still not working
@mertsincan can you reopen the issue ?

**Comment by ThibaudTeachup** [comment]
No correction has yet been made to this feature?

**Comment by chrisbrugger** [comment]
@mertsincan or @Zorgatone can you reopen this issue? This is still not working on mobile. 
This issue is not resolved and seems to be ignored for years. 
I guess for now I will need to use [Dragula ](https://github.com/valor-software/ng2-dragula)or [Angular CDK](https://material.angular.io/cdk/drag-drop/overview) to solve this, but it would be nice to have this feature in PrimeNG as well.

**Comment by Zorgatone** [comment]
> @mertsincan or @Zorgatone can you reopen this issue? This is still not working on mobile. 
> This issue is not resolved and seems to be ignored for years. 
> I guess for now I will need to use [Dragula ](https://github.com/valor-software/ng2-dragula)or [Angular CDK](https://material.angular.io/cdk/drag-drop/overview) to solve this, but it would be nice to have this feature in PrimeNG as well.

I can't seem to be able to reopen this issue myself, unfortunately.

**Comment by devalvesg** [comment]
please, reopen this issue urgent!

**Comment by Chocobozzz** [comment]
Hi,

Drag and drop doesn't work on mobile. Can you reopen the issue? Thank you!
