### ISSUE TITLE
color picker in reactive forms doesn't select color

### ISSUE THREAD

**Issue by shalaby** [primefaces/primeng#3179]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/O5XN0CGMBWERE5ByaWDY?p=preview

**Current behavior**
in reactive form with pre defined value for the color control, this initial value doesn't get selected.
`myForm: FormGroup;
   constructor(public fb: FormBuilder) {
     let color = 'ff0000';
     this.myForm = this.fb.group({
      color: [color]
    });
   }`
**Expected behavior**
the color should be selected

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.2.4

* **PrimeNG version:** 4.1.0-rc.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [ TypeScript 2.3 ]

* **Node (for AoT issues):** `node --version` =   8

**Comment by toregua** [comment]
Almost same plnkr with a button that show that reactive form is not valid at first load until a value is choose with the picker : 
http://plnkr.co/edit/zLVnYnRHdqmwI3njTu4T?p=preview
