### ISSUE TITLE
MenuModel "visible" property ignored

### ISSUE THREAD

**Issue by parisgianluca** [primefaces/primeng#3180]
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

The **visible** property in MenuModel API is ignored.

Documentation
https://www.primefaces.org/primeng/#/menumodel

Setting **visible** to false still shows the item. I'm using Angular v4.0.0 with PrimeNG Ultima, working with MenuModel inside MenuBar.

**Comment by cagataycivici** [comment]
Please post this question at Ultima-NG forum and our team will pick it up for next ultima release.
