### ISSUE TITLE
p-dialog Bootstrap footer style issue with PrimeNG 4.0

### ISSUE THREAD

**Issue by adama357** [primefaces/primeng#3183]
**I'm submitting a ...** 
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

We just upgraded to PrimeNG 4.0.  Now, when using the [free] Bootstrap theme, the p-dialog footer content looks a bit odd, with a misplaced horizontal gray line above the buttons here:

![dialogfooter](https://user-images.githubusercontent.com/20462430/27449132-ed6ec970-574c-11e7-9eff-c88132ca3c41.jpg)

This can be seen on the [p-dialog page](https://www.primefaces.org/primeng/#/dialog) if you turn on the free Bootstrap theme.  (It displays just fine with the default theme.)  

On a related note, in the documentation source tab, it still says `<div class="ui-dialog-buttonpane ui-widget-content ui-helper-clearfix">`, but the actual preview no longer contains "ui-widget-content", and before I removed it from our own code, it looked even more odd, with an entire rectangle enclosing the buttons. 

So I guess there are really two issues: 
- [ ] Bootstrap theme display bug
- [ ] Documentation is seemingly outdated

Thank you for your time. 

* **PrimeNG version:** 4.0.3

* **Browser:** [Chrome 58 | Firefox 53]

**Comment by alialtun14** [comment]
I think this problem is continuing ...

https://github.com/primefaces/primeng/issues/3426
