### ISSUE TITLE
datatable and autocomplete:  thin color column feature

### ISSUE THREAD

**Issue by alialtun14** [primefaces/primeng#3186]
[x] feature request

It would be better if the datatable and autocomplete components had a thin color column feature so that the row coloring depend on row data could be done on the pillar. To meet this need in our project, we tried to produce a solution by playing with CSS. But such solutions are both troublesome and can cause unexpected side effects.

![qlass](https://user-images.githubusercontent.com/782196/27472139-963c1578-57fa-11e7-9915-696d75489e15.png)

**Comment by cagataycivici** [comment]
Data part can be done with rowStyleClass, for other please create an issue like styleclass support to Dropdown.
