### ISSUE TITLE
optional zebra style coloring to datatable rows

### ISSUE THREAD

**Issue by alialtun14** [primefaces/primeng#3187]
[x ] feature request

Zebra style coloring is applied to the datatable component's rows  as default. Is this feature be made optional? For a modern and cleaner look, the DataTable may also require that the background is completely white (or a different color preference). 

As seen in the following image, to meet this need  we tried to produce a solution by playing with CSS. But such solutions are both troublesome and can cause unexpected side effects.

![datatable](https://user-images.githubusercontent.com/782196/27472815-13323830-57fd-11e7-89cb-dac479cfaa56.png)

**Comment by cagataycivici** [comment]
You can override css to remove zebra.
