### ISSUE TITLE
autocomplete ngModel not updated before onUnselect event callback is called, but is before onSelect

### ISSUE THREAD

**Issue by heavydawson** [primefaces/primeng#3188]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/Wj39h1?p=preview

**Current behavior**
The ngModel variable of autocomplete is correctly updated prior to the callback function for "onSelect" but not updated prior to the callback for "onUnselect" This means the when an object is unselected, the callback code is looking at an out-dated ngModel
The model is updated at some point after the callback, but that's too late.

**Expected behavior**
The ngModel will be updated prior to the "onUnselect" callback and the callback function will see the latest ngModel at that time.

**Minimal reproduction of the problem with instructions**
https://embed.plnkr.co/z3jhPHGkERNZRiyofQnn/

Type in multiple entries in the autocomplete, and the value of the ngModel at the time of the callback will be displayed in the text underneath the autocomplete box. As you add elements their correctly reflected in the text below the autocomplete, but if you remove elements, they do not get removed from the text as they're not removed from the underlying ngModel at the time of the callback.

**What is the motivation / use case for changing the behavior?**
autocomplete behaviour is different for "onSelect" and "onUnselect". I don't think it should be.
**Please tell us about your environment:**
node 7.0.0
Mac 10.12.4

* **Angular version:** 2.0.X
Running Angular 4.2.3
* **PrimeNG version:** 2.0.X
Running PrimeNG 4.1.0-rc2
* **Browser:** 
all 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES5
* **Node (for AoT issues):** `node --version` =   
7.0.0 (seeing the issue in development mode, so no AOT involved)

**Comment by shashi97** [comment]
(onUnselect)="functionName($event)"

functionName(event) {
// event has selected for delete object then remove from model that you have bind with

}

**Comment by skolli853780** [comment]
I am trying to delete an item added to the Autocomplete, model tied to autocomplete is not getting updated.. I have created an issue for this.. https://github.com/primefaces/primeng/issues/3864

Any insights on what is going on? I am on Angular 4, PrimeNG 4.2

**Comment by skolli853780** [comment]
With PrimeNG 2.0, model variable was getting updated when an select and unselect event was fired.. with PrimeNG 4.0, unselect event - if I add 1 item and delete it, model variable still shows it as 1 items.. model variable is not up to date.. if I put timeout, then variable is updated..

**Comment by cagataycivici** [comment]
Still happens with 4.2.2?

**Comment by skolli853780** [comment]
yes..very easy to reproduce...print the autocomplete model variable on select and unselect action of autocomplete 

select something from autocomplete, model variable is updated.. delete the autocomplete text by clicking on x icon, check the console log.. model variable is not updated.. still shows the value that was selected..if I add 2 items to autocomplete and delete 1 , model variable is updated but if I delete last item.. model variable still shows 1 item.. I think last item is not getting deleted from model variable

**Comment by cagataycivici** [comment]
Merged, thank you.
