### ISSUE TITLE
Contextmenu top and left incorrect

### ISSUE THREAD

**Issue by martijnhiemstra** [primefaces/primeng#3189]
I am using the context menu with the tree component. When I right click on the tree the contextmenu appears and then disappears. When I hold the right mouse button in then the menu stays visible and I can select the menu options.

The problem is with the inline styling of the context menu. Since the top and left are too far from the mouse click the menu immediately disapears. The <p-contextmenu component has an inner div and it has inline styling like this:

`
left: 229px;
top: 177px;
display: block;
visibility: visible;
opacity: 1.032;
`
The top and left are incorrect. The context menu should be more to the top and the left. 

Since the position is determined by inline styling and by a "sub" div of <p-contextmenu I can't override the value unless I use this in my css. 
`
div.ui-contextmenu {
  left: 200px !important;
  top: 170px !important;
}
`
Where can I file a bug report?

**Comment by cagataycivici** [comment]
Can you replicate at live showcase?

**Comment by martijnhiemstra** [comment]
Yes I can. When I view the live showcase, the same thing happens. I right click, the menu appears and then disappears. I can see that the location of the menu is too far off from where I right click on the tree.

I am using 54.0 (64-bit) Firefox for linux (Ubuntu).

**Comment by miresk** [comment]
@martijnhiemstra have you tried appendTo="body" on your contextMenu? I think it could help if the menu appears too far from where you click

**Comment by cagataycivici** [comment]
This looks good to me;

http://localhost:4200/#/contextmenu

Please provide a plunkr and we'll review again.

**Comment by mahesh5b5** [comment]
Same issue coming when Im using it with my p-datatable the position is not proper please help
