### ISSUE TITLE
Update the setup

### ISSUE THREAD

**Issue by lilling** [primefaces/primeng#319]
the setup is no longer up to date with the whole chang of RC.0.

**Comment by cagataycivici** [comment]
We'll do it tonight after releasing beta5 that brings compatibility with RCs

**Comment by lilling** [comment]
Thank you for the quick reply!
בתאריך 5 במאי 2016 19:31,‏ "Çağatay Çivici" <notifications@github.com> כתב:

**Comment by cagataycivici** [comment]
Schedule to tomorrow along with beta5 release.
