### ISSUE TITLE
p-confirmdialog both p-footer and .ui-dialog-footer visible with custom p-footer

### ISSUE THREAD

**Issue by L-VE** [primefaces/primeng#3190]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/ah9or9VvdNvCX36l1skp?p=preview

**Current behavior**

When using a ConfirmDialog with a custom footer, both a .ui-dialog-buttonpane and .ui-dialog-footer are created in the HTML.

This is because the `ngIf's` to check whether a custom footer is used or not are placed on both the `.ui-dialog-buttonpane`. The one surrounding the `<ng-content select="p-footer">` and the one inside the `.ui-dialog-footer`.

```
<div class="ui-dialog-buttonpane ui-widget-content ui-helper-clearfix" *ngIf="footer">
                <ng-content select="p-footer"></ng-content>
</div>
<div class="ui-dialog-footer ui-widget-content">
            <div class="ui-dialog-buttonpane ui-helper-clearfix" *ngIf="!footer">
                <button type="button" pButton [icon]="rejectIcon" [label]="rejectLabel" (click)="reject()" *ngIf="rejectVisible"></button>
                <button type="button" pButton [icon]="acceptIcon" [label]="acceptLabel" (click)="accept()" *ngIf="acceptVisible"></button>
            </div>
</div>
```
The `*ngIf="!footer"` on the second `.ui-dialog-buttonpane` should be moved to his parent, the `.ui-dialog-footer`.

**Expected behavior**

With using a custom footer in the ConfirmDialog, only the .ui-dialog-buttonpane is expected to be there.
With the default footer, the .ui-dialog-footer is expected.

**Minimal reproduction of the problem with instructions**

Press the `show dialog` button in the plunkr

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

angular 4.2.4

* **PrimeNG version:** 2.0.X

primeng 4.1.0-rc.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Fixed in RC3.
