### ISSUE TITLE
p-multiSelect in datatable row: appendTo="body" invalidates filter="false'

### ISSUE THREAD

**Issue by rogerleuthner** [primefaces/primeng#3191]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Filter appears even though filter="false" when used in conjunction with appendTo="body" tag

My example is as a column in a datatable, not sure whether behavior is similar stand alone.

**Expected behavior**
filter should not show up

**Minimal reproduction of the problem with instructions**
Create table with a column of p-multiSelect with [(ngModel)], use the filter='false' and appendTo='body' together and the filter shows up.  Remove the appendTo tag and the filter does not show up.

**What is the motivation / use case for changing the behavior?**
Seems like the tags should be able to be used in conjunction.

**Please tell us about your environment:**
Weblogic, war deployment.

* **Angular version:** 2.0.X
Release 4.2.0-rc.2

* **PrimeNG version:** 2.0.X
Release 4.1.0-rc.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Firefox
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

* **Node (for AoT issues):** `node --version` =

**Comment by Mrtcndkn** [comment]
Hi,
I think the problem is not about appendTo and filter options used together. When you use filter="false" without binding false is just a string for the template so it rendered as true you should use one way binding [filter]="false".
If issue persists after this feel free to open the ticket again.
