### ISSUE TITLE
Add filtering in TreeTable

### ISSUE THREAD

**Issue by helenegodart** [primefaces/primeng#3193]
* **I'm submitting a**
```
[ ] bug report
[X] feature request
[ ] support request 
```

* **What is the motivation / use case for changing the behavior?**
As far as I can see, sorting is in the Roadmap but not filtering. If possible, it could be useful to be able to add filters, as we can do it in DataTable.

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** all

Thanks !

**Comment by LorenaGdL** [comment]
This seems a good reference to do it: https://github.com/ddvkid/ng-treetable

**Comment by harogaston** [comment]
Duplicated #1683 Filtering for Tree

**Comment by helenegodart** [comment]
I'm not sure about duplicating, as Tree and TreeTables are two different components. That's why I opened a new feature request.

**Comment by cagataycivici** [comment]
TreeTable will be reimplemented, please monitor;

#4813

**Comment by jingweihaha** [comment]
When is filter going to be implemented?

**Comment by umdstu** [comment]
@cagataycivici - Are you planning on adding this to the new TreeTable? If so, what version? Thank you!
