### ISSUE TITLE
Use a DataTable with resizableColumns and scrollable may cause unresponsive web page or lag css animation.

### ISSUE THREAD

**Issue by mix5003** [primefaces/primeng#3195]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/XRn8ECiOCeVOQB2g85Ni?p=preview
animation will lag when move mouse.

**Current behavior**
When use resizableColumns with scrollable table. when mouse move it call `calculateScrollbarWidth` and make DOM change every times. so it may cause unresponsive web page.

**Expected behavior**
I don't know. may be cache a `calculateScrollbarWidth` result. so it not touch a DOM.

**Minimal reproduction of the problem with instructions**
Use a `DataTable` with `resizableColumns` and `scrollable`
(only `resizableColumns` can make a little laggy but when use with `scollable` i think it significant drop performance)

**Please tell us about your environment:**

* **Angular version:** 4.1.2

* **PrimeNG version:** 4.0.3

* **Browser:** all (up to cpu power)
 
* **Language:** TypeScript 2.3.2

* **Node (for AoT issues):** `node --version` =   v7.7.4

**Comment by cagataycivici** [comment]
Fixed via PR, thank you.
