### ISSUE TITLE
Autocomplete inputtext content not shown

### ISSUE THREAD

**Issue by oixan** [primefaces/primeng#3199]
Good Morning,

I found a problem on Autocomplete component.
Version project Angular 4.2.4 - Primegn 4.1.0-rc.2,

The problem happen when i type some partial text in the inputText then i choose a field from the suggest lists and the input text is update correctly. But as soon as i leave with 1 click outside the  input text the content is not showed anymore. The value is still in the form control, i checked but is not showed.

i created a plunker, Just follow the steps to see the problem.
http://plnkr.co/edit/dQZXQNasdDTJJDWNBZ0B?p=preview

**Comment by Mrtcndkn** [comment]
Hi,

The plunkr you created is not working. I tried your steps locally and I couldn't replicate the problem. Could you please create a new plunkr for the situation. @oixan 

Regards,
Mertcan

**Comment by oixan** [comment]
Have you tried to refresh the page? the plunker is working to me.

Anyway i have created a new plunker fork and a video to show the problem.

Plunker
http://plnkr.co/edit/pjpvCLJitsi38HjSNQ2r?p=preview

Video
https://www.screencast.com/t/hs1l3UGTkOb

**Comment by s-nesbigall** [comment]
Hi,

I can also reproduce this error on the primeng autofill page:
[https://www.primefaces.org/primeng/#/autocomplete](url)

Like mentioned in the video above one must select the value using the keyboard. Using the mouse to select the list value works fine.

**Comment by Mrtcndkn** [comment]
https://github.com/primefaces/primeng/issues/2197
