### ISSUE TITLE
GMap and Overlay panels

### ISSUE THREAD

**Issue by ar53n** [primefaces/primeng#3205]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/Wj39h1?p=preview

**Current behavior**

Not rendered google maps when it in overlays panel

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.0.X

* **PrimeNG version:** 4.1.3

**Comment by Mrtcndkn** [comment]
https://github.com/primefaces/primeng/issues/1806 this is fixed for next release
