### ISSUE TITLE
InputMask + Calendar don't decorate its inner input field with "required" and "pattern" attribute and validation states

### ISSUE THREAD

**Issue by KatzeKahn** [primefaces/primeng#3208]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Adding a "required" attribute to the <p-inputMask> does not affect the inner input field. No validation state classes like "ng-invalid ng-touched ng-dirty" are being added. Beside the fact, that this seems like a bug to me, it not possible to style invalid input fields (requires additional CSS rules/hacking).

**Btw, same issue for the "pattern" build-in validator attribute!**

_From Chrome inspector:_

`<p-inputmask styleclass="form-control" required class="ng-invalid ng-dirty ng-touched"><input pinputtext="" class="form-control ui-inputtext ui-corner-all ui-state-default ui-widget" id="testfield4" type="text" name="testfield4"></p-inputmask>`

**Expected behavior**
The inner input needs to be decorated with the "required" attribute and validation state classes.

**Minimal reproduction of the problem with instructions**
Just add a required attribute to <p-inputmask> and check Html of inner text input.

**What is the motivation / use case for changing the behavior?**
Currently, default styling of invalid input fields does not work with InputMask element.

**Please tell us about your environment:**

* **Angular version:** 4.0.1

* **PrimeNG version:** 4.1.0-rc.2

* **Browser:** [all]

 
* **Language:** [all]

**Comment by cagataycivici** [comment]
The custom element is decorated and the styles are created according to it, these are custom elements not directives so this is expected.

**Comment by KatzeKahn** [comment]
I don't agree with you. Independently if it's a custom element, you should follow the general approach to decorate the input elements with those classes as well. Since I (and probably others) don't use your stylesheets, it requires us to write separate CSS rules.
