### ISSUE TITLE
Inline styles do not work with Angular2 RC

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#321]
When a custom element has inline style like;

```xml
<p-panel style="width:500px"
```

It is not applied as somehow angular2 displays style="unsafe" when we bind it to attr.style in internal element.

So far our new options seems like;

```xml
[style]="{width:'500px'}"
```

and pass the object to ngStyle internally which works fine.

We need to update all components to this code.

**Comment by LucasFrecia** [comment]
I cannot get around this and found your post, could this be instance of same issue?

Component template:
`[style]='url' `
 
Component export class:
`this.url = "background-image:url(data:image/jpeg;base64," + this.imageValue + ")";`
 
Console display:
`ng-reflect-style="unsafe"`

**Comment by MiDrescher** [comment]
This width syntax is not satisfactory for me, when it comes to style binding: Suppose I create my table columns with an ngFor-statement, e.g.:

        <p-column *ngFor="let col of columns" [field]="col.field" [header]="col.header" [style.width]="col.width"></p-column>

In this example, I would like to set the column widths from my view model ("col"), the same way as I set the field and the header. [style.width] is standard Angular style binding syntax, but it will not work for the p-column in the example above. How would I do it?
