### ISSUE TITLE
ContextMenu - enable left click listener

### ISSUE THREAD

**Issue by miresk** [primefaces/primeng#3215]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Currently it is possible to open context menu only with a right click 

**Expected behavior**
We should be able to open context menu also on left click. I suggest using some property like leftClick="true" or something similar that would allow us to do that.

* **Angular version:**
4.2.2

* **PrimeNG version:**
4.1.0-rc.2

**Comment by cagataycivici** [comment]
Sounds good.

**Comment by cagataycivici** [comment]
PR merged.
