### ISSUE TITLE
[Feature] Instructions on how to get a development environment of PrimeNG going

### ISSUE THREAD

**Issue by gatapia** [primefaces/primeng#322]
I have tried playing around with npm commands to get primeng compiling from source but its beyond me.  Currently I have hacks where I have fixed small bugs in the generated (compiled) primeng javascript.  This is painful, would rather work on the source and rebuild may even submit a patch or two.

**Comment by cagataycivici** [comment]
I quickly came up with this, hope this helps;

https://github.com/primefaces/primeng/wiki/Building-From-Source

**Comment by gatapia** [comment]
sweet!

perhaps save the package.json as package.json.devel so its easier to keep in sync than a wiki page.

**Comment by lebnic** [comment]
Works, thanks
