### ISSUE TITLE
display full date in separate input boxes (dd /mm / yyyy)

### ISSUE THREAD

**Issue by chrisj-skinner** [primefaces/primeng#3220]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
n/a

**Expected behavior**
Is it possible to seperate the day month and year into separate input boxes. Essentially being able to  tab between the [day] [month] [year]. Can you select to display just the day / month or year. This can currently be done for the 'Time' but I don't see documentation to display just the date elements.

**What is the motivation / use case for changing the behavior?**
Better UI on mobile - see image attached

![calendar](https://user-images.githubusercontent.com/5794048/27597223-a65d0770-5b59-11e7-9e62-32740ee0bda7.PNG)

**Comment by KatzeKahn** [comment]
On desktop devices, I would definitely NOT prefer such an approach. A better solution would be to navigate through each block (day, month, year, hour, minutes) by using the tab + the left/right arrow keys and then adjust the date block with the up/down arrow keys (including modulo operations). Currently, this feature is still missing.

And even on mobiles devices I would NOT separate the blocks. Instead, take iOS as an example and provide a picker panel to easily select your values with the finger.
https://developer.apple.com/ios/human-interface-guidelines/ui-controls/pickers/

**Comment by cagataycivici** [comment]
Closing it until more users demand it, from UX point of view, one field is easier in my opinion.

**Comment by DavyDeDurpel** [comment]
I'm a big fan of KatzeKahn's proposal.  Using the keyboard arrows for scrolling up and down would make this calendar the best ever ;-)
