### ISSUE TITLE
Calendar: Prevent input of invalid characters

### ISSUE THREAD

**Issue by KatzeKahn** [primefaces/primeng#3221]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
n/a

**Expected behavior**
Instead of clearing invalid inputs onBlur (which might be a good fallback anyway), prevent the input of invalid characters in advance. Only numeric input should be allowed. This should be easily implemented by catching and checking input's (keydown) event.

This probably presumes that only single date blocks (days, month, year, hours, minutes) can be selected by the user which is the desired behavior either way. See my comment here: #3220.

**What is the motivation / use case for changing the behavior?**
Anticipate and prevent potential input errors and avoid user frustration.

**Comment by cagataycivici** [comment]
This is too complex, easier to validate the input instead of blocking what user tries to enter.
