### ISSUE TITLE
Double click based transfer on PickList

### ISSUE THREAD

**Issue by nmobregon** [primefaces/primeng#3223]
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Expected behavior**
Move to right/left on item double click

**What is the motivation / use case for changing the behavior?**
Would be great to avoid user from clicking different places (item and button), and have the possibility to double click an item from one list in order to move it to the other list

* **PrimeNG version:** 4.1.0-rc.2

Thanks in advance and keep up the good work

**Comment by SIlver--** [comment]
For now, if wrap your items in a `ng-template` block, you can assign the `ondblclick` event to a div and go about running the logic this way.

**Comment by nmobregon** [comment]
Thanks @SIlver--, that seems like a good approach. I'm going to try it right now.
Would be nice to have it natively though.

**Comment by VinyP** [comment]
@cagataycivici any way to disable the double click on p-picklist?

**Comment by Aeptitude** [comment]
There isn't a way to disable it. There should be! 
A workaround I figured out;

    <p-pickList [source]="sourceItems"
    (onMoveToTarget)="manageItems()">

So in the manageItems method, check the list and if an item has been moved over that you didn't want, remove it manually.

**Comment by yuvalmor96** [comment]
you can  disable the double click on p-picklist by using event.stopPropagation();

HTML

`<p-pickList [source]="sourceProducts" [target]="targetProducts" sourceHeader="Available" targetHeader="Selected" 
    dragdrop="true"
    [responsive]="true" [sourceStyle]="{'height':'300px'}" [targetStyle]="{'height':'300px'}" filterBy="name"
    sourceFilterPlaceholder="Search by name" targetFilterPlaceholder="Search by name">
    <ng-template let-product pTemplate="item">
        <div (dblclick)="return($event)"  class="product-item">
                      {{product.descripcion}}
        </div>
    </ng-template>
</p-pickList>`

TS
`  return(event){
    event.stopPropagation();
  }`

}

**Comment by ashub1118** [comment]
@yuvalmor96 I tried disable the  event propagation on double click as suggested b you, it's not working.  Items are still getting transferred. Can anyone please suggest how can i disable it.

**Comment by DanielH432** [comment]
@ashub1118 here you go:
In the `div` that produces each product in the pick list, add a call to a modified (shown below) version of @yuvalmor96's `return()` function.

*The product template*
`<ng-template let-product pTemplate="item">
      <div (dblclick)="return($event)" class="grid"> // <- RIGHT HERE
        <div class="col-6">
          <h5 class="">{{ product.name }}</h5>
          <span>{{ product.SKU }}</span>
        </div>

        <div class="col-6">
          <label for="quantity" style="display: block">
            <div class="grid">
              <span class="col-8">Quantity</span>
              <span class="col-4">
                Max: {{ product.location_quantity.quantity }}
              </span>
            </div>
          </label>

          <p-inputNumber
            [min]="1"
            [max]="product.location_quantity.originalVal"
            [(ngModel)]="product.location_quantity.quantity"
            [showButtons]="true"
            inputId="quantity"
            decrementButtonClass="blue-400"
            incrementButtonClass="blue-400"
            incrementButtonIcon="pi pi-plus"
            decrementButtonIcon="pi pi-minus"
          >
          </p-inputNumber>
        </div>
      </div>
    </ng-template>`

*The modified return() function*
`  return(event: any) {
    event.preventDefault();
    event.stopPropagation();
    return false;
  }`
