### ISSUE TITLE
Resize support for frozen columns

### ISSUE THREAD

**Issue by ksCookj** [primefaces/primeng#3224]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/ugnXQb9uR3X3NI6sqlLs

**Current behavior**
When trying to resize a column the header resizes but the body column

**Expected behavior**
When resizing column both the header and body column will maintain the same width

**Minimal reproduction of the problem with instructions**
Use a DataTable with resizableColumns, scrollable and frozen column

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.0.0

* **PrimeNG version:** 4.0.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** TypeScript 2.0.3

* **Node (for AoT issues):** `node --version` =   v7.7.4

**Comment by pragatir** [comment]
@cagataycivici Is this being planned to be supported soon?

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.

**Comment by bharatpatil** [comment]
This is still an issue with the latest PrimeNG TurboTable.
