### ISSUE TITLE
Immutable property for data components

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#3227]
Bring back ngDoCheck to restore backward compatibility, if new immutable property (true by default) is enabled then use regular setter change detection, if not use ngDoCheck. This applies to;

- DataTable
- DataGrid - Done
- DataList - Done
- AutoComplete
- Growl

**Comment by gjenner** [comment]
is there a work around?  splice and push not reflected in p-datatable

**Comment by cagataycivici** [comment]
To get them reflected you need to set [immutable]="false"

**Comment by gjenner** [comment]
Can't bind to 'immutable' since it isn't a known property of 'p-dataTable'.
            <p-dataTable [value]="ocDiagnosisDisplayed" [immutable]="false" [resizableColumns]="true" selectionMode="single" [(selection)]="oChronicSelected" (onRowSelect)="onChronicRowSelect($event)">

**Comment by cagataycivici** [comment]
You need rc3 for this which is due tomorrow.

**Comment by gjenner** [comment]
sorry, same error with rc3

**Comment by cagataycivici** [comment]
Weird, it works for me.

**Comment by gjenner** [comment]
can you post an example that has [immutable], I still get

**Comment by sudheerj** [comment]
Showcase is already updated with details. You can find the example here 
https://github.com/sudheerj/primeng-4.1/blob/master/src/app/components/datatable/datatabledemo.component.html

**Comment by gjenner** [comment]
uninstalled and reinstalled primeng, now it works, thank you.  problem, 
p-radiobutton style="margin-left: 10px;" fails

**Comment by sudheerj** [comment]
That's great. You might have older versions.

**Comment by gjenner** [comment]
Problem, p-radioButton no longer accepts inline style, i.e. 

<p-radioButton style=”margin-left: 10px;”>

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com
