### ISSUE TITLE
use dropdown in Dialog

### ISSUE THREAD

**Issue by cyberrranger** [primefaces/primeng#3235]
[X] bug report => Search github for a similar issue or PR before submitting

http://plnkr.co/edit/r6Alr8?p=preview

![screenshot 2017-06-28 15 35 34](https://user-images.githubusercontent.com/21671762/27639773-8406a942-5c17-11e7-88df-b3b4df585dd9.png)

Regards
Patrick

**Comment by miresk** [comment]
I can confirm this behaviour. You can easily fix it though just by adding [style]="{'width':'100%'}" to <p-dropdown>

**Comment by cyberrranger** [comment]
the width is not the Problem, Show the items positions, Example "rome"

**Comment by SIlver--** [comment]
Still having this issue. Does anyone know the CSS to fix it?

**Comment by SIlver--** [comment]
In the [documentation, as stated in Overlays Inside,](https://www.primefaces.org/primeng/#/dialog )you're supposed to do this

`<p-dialog [contentStyle]="{'overflow':'visible'}">
    <p-dropdown></p-dropdown>
</p-dialog>
`

**Comment by cyberrranger** [comment]
thx
