### ISSUE TITLE
How to write export to excel for nested Object in Angular 2 

### ISSUE THREAD

**Issue by dp1709** [primefaces/primeng#3238]
We are working on nested objects for which we need export functionality.
Structure of object JSON looks like:

{
		"Id": 166,
		"Name": "Test",
                 .
                 .
		"Steps": [
			{
				"stepId": 1,
				"stepName": "step1",
				"stepDesc": "step1 desc",
                                 "innerMap" : {
                                          "key" : "value"
                                  }
			},
			{
				"stepId": 2,
				"stepName": "step2",
				"stepDesc": "step2 desc",
                                 "innerMap" : {
                                          "key" : "value"
                                  }
			},
		],

}

I am using prime ng datatable to show this data .
Export feature provided by prime-ng p-datatable, shows inner objects as [object Object] instead of the values. 

Can it be handled internally or I need to write this conversion explicitly ?

**Current behavior**
In current excel data is displayed as: 
12	Test [object Object]	[object Object]	[object Object]	[object Object]

**Expected behavior**
12	Test 
               Step 1 Step1 Desc 
                                     Inner map 1 2 .....

@angular/core: 4.1.3
PrimeNG version: 4.0.2
Browser Chrome

**Comment by kenisteward** [comment]
on each of the nested object append a toString() function that emits what you actually want to show in the export.  That's how I handled it.  I have special classes for complex object exports that all implement .toString()

**Comment by cagataycivici** [comment]
Please provide a plunkr and we'll review again.

http://plnkr.co/edit/Qi2Nw2imLpDUF8NJinYw?p=preview

**Comment by satizkumar** [comment]
Is there any option to export  xl download for primeNg Nested table ?

**Comment by pramodkharade** [comment]
I am also facing same issue for nested object while exporting csv. Anybody having solution for same. it would be the great help.
