### ISSUE TITLE
I'm having problems with Two-way Data Binding (NgModel) in the autoComplete component.

### ISSUE THREAD

**Issue by ryanfrnnds** [primefaces/primeng#3239]
I needed to create an autoComplete abstraction in a mine project.

![image](https://user-images.githubusercontent.com/7664019/27655297-4e42b522-5c1b-11e7-8339-479ad7cc037e.png)
Please read the content in commentary on the IMAGE
I needed to execute the eventNgModel shown in the above image in all the methods below so that the Binding is done from the 'prime' layer to the layer of my application going through my abstraction.

   Private change (event: any) {
     This.acaoEventNgModel ();
     This.eventOnChange.emit (event);
   }
   Private onSelect (event: any) {
     This.acaoEventNgModel ();
     This.eventOnSelect.emit (event);
   }
   Private onUnSelect (event: any) {
     This.acaoEventNgModel ();
     This.eventOnUnselect.emit (event);
   }

I will now show my Application that uses my AutoComplete Abstraction
![image](https://user-images.githubusercontent.com/7664019/27655606-588b978c-5c1c-11e7-8f12-b1d0d9fc9809.png)

Since Two-way Data Binding is not working I needed to make these adaptations to simulate a Two-way Data Binding.

And I also had this problem with the Template that I had to solve like this, since I did not find a method or event that tried to show a LabelFunction for AutoComplete without using the Template.
![image](https://user-images.githubusercontent.com/7664019/27655875-4f823d2a-5c1d-11e7-9e06-f23ad3bc4455.png)

So I'd like to check if you can help me with this. It may be that I am doing wrong or not going the right way. Anyway I started at Angular 1 month only and I have a lot to learn. So if you can help me thank you, I have not found any solutions or problems like my own.

Organizing more images:

1 HTML that makes use of my abstration
![image](https://user-images.githubusercontent.com/7664019/27656171-61671960-5c1e-11e7-9f34-d46e697e6dcf.png)
2 HTML Component Angular
![image](https://user-images.githubusercontent.com/7664019/27656330-f1a93e90-5c1e-11e7-9dbb-e41e76409f65.png)

**Comment by cagataycivici** [comment]
Please use forum for support requests and questions.
