### ISSUE TITLE
DataTable: Paging with virtual scroll should correctly update the current scroll position

### ISSUE THREAD

**Issue by kenisteward** [primefaces/primeng#3240]
[ X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/oO1aJdPJG9C7RoZmzceG?p=preview

**Current behavior**
When you have a paginator and virtualscroll with scrollable set paging DOESN'T update the virtual scroll context.  This is confusing because scrolling CORRECTLY updates the current page.

**Expected behavior**
Paging should update scrolling position and scrolling should update paging (as it already does)

**Minimal reproduction of the problem with instructions**
go to the plunker 
click a page
see that it doesn't update scrolling.
now scroll
see that it correctly udpates paging

**What is the motivation / use case for changing the behavior?**
Consistency in the control for a datatable

**Please tell us about your environment:**
VS Code

* **Angular version:** 2.0.X
4.1.3

* **PrimeNG version:** 2.0.X
4.1.0.rc1

* **Browser:**
only tried chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

**Comment by kenisteward** [comment]
@cagataycivici  where are the contributing rules??

**Comment by cagataycivici** [comment]
Paging and Virtual scroll is not a supported combination at the moment, it is either paginator or virtual scroll since they do the same. If there is more demand, we'll reconsider, thank you.

**Comment by kenisteward** [comment]
Oh okay. It just seemed odd to me that the onvirtualscroll event returns
the page to go to but clicking a page didn't exactly return where to scroll
to. I suppose I could simply on page update the body scroll by hand.  If I
could find the best place to do it in the lib would a PR be okay?
