### ISSUE TITLE
[p:selectOneButton] Support of click or unselect events

### ISSUE THREAD

**Issue by mossaab0** [primefaces/primeng#3241]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**What is the motivation / use case for changing the behavior?**
Currently, `p:selectOneButton` supports only the `change` event. As a consequence, selecting any button fires an AJAX request. However, nothing happens when an already selected button is unselected. I'd like an appropriate AJAX request to be fired as well.
My understanding is that `p:selectOneRadio` already supports the `click` event. Hence, it makes sense to support this functionality in `p:selectOneButton` as well.

**Comment by mdzaebel** [comment]
See https://github.com/primefaces/primefaces/issues/2483
