### ISSUE TITLE
Calander -> TimeOnly - set as a counter and not as a time

### ISSUE THREAD

**Issue by eliadAyehu** [primefaces/primeng#3242]
I need a Time Only component that we can set a counter. for example:
(56:65) - what means 56 hours and 65 minutes.

today we can set in TimeOnly (23:59). we need to increase the hours to 99.

does primeNg have already something we can use ? or it is a new feature ?

actually we need input to limit the hours and minutes the same as in years (1900:2090).

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows

* **Angular version:** 2.0.X
Angular 4.1

* **PrimeNG version:** 2.0.X
4.0.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Please use forum for support requests and questions, you may also create a new issue ticket to request new components.
