### ISSUE TITLE
Responsive TreeTable

### ISSUE THREAD

**Issue by cyberrranger** [primefaces/primeng#3249]
```
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
``
is this feature planned?
https://www.primefaces.org/primeng/#/treetable

Regards
Patrick

**Comment by cagataycivici** [comment]
TreeTable is subject for rewrite in PrimeNG 4.2, we'll check this for 4.2.

**Comment by lanbin45** [comment]
@cagataycivici Could you tell me when this enhancement will be implemented? as far as I known, it did not finished in the latest version.

**Comment by finalxcode** [comment]
@cagataycivici when this enhancement will be implemented?

**Comment by cagataycivici** [comment]
TreeTable will be reimplemented, please monitor;

#4813
