### ISSUE TITLE
editor become disabled!

### ISSUE THREAD

**Issue by akshath4u** [primefaces/primeng#325]
If you type single word and hit enter in a quick interval after one or two line the editor become disabled. I can't type anything.

<img width="899" alt="screen shot 2016-05-06 at 3 02 00 pm" src="https://cloud.githubusercontent.com/assets/9428527/15069516/bad79172-139b-11e6-9234-02909d040623.png">

**Comment by cagataycivici** [comment]
Can you replicate the same at;

http://quilljs.com/

**Comment by cagataycivici** [comment]
Cannot replicate
