### ISSUE TITLE
NgModel support for OrderList

### ISSUE THREAD

**Issue by claudiuconstantin** [primefaces/primeng#3255]
**I'm submitting a:**
```
[ ] bug report
[x] feature request
[ ] support request
```

**Current behavior**
You cannot use `formControlName ` on a `p-orderlist`

**Expected behavior**
You should be able to use `formControlName ` on a `p-orderlist` in order to map the value to a form control. This might be achieved by implementing [ControlValueAccessor](https://angular.io/api/forms/ControlValueAccessor) in `p-orderlist`

**What is the motivation / use case for changing the behavior?**
Using the `p-orderlist` value in an Angular form might be very useful

**Please tell us about your environment:**

* **Angular version:** ^4.2.0

* **PrimeNG version:** ^4.0.0

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
