### ISSUE TITLE
Error when selecting a day on a p-calendar inside an editor column

### ISSUE THREAD

**Issue by wcgomes** [primefaces/primeng#3256]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/Wj39h1?p=preview

**Current behavior**
When selecting a day on a **p-calendar inside a pTemplate="editor" column of  a p-datatable**, the date is set correctly but the following error occur: 

_"TypeError: Cannot read property 'editable' of undefined at DataTable.webpackJsonp.../../../../primeng/components/datatable/datatable.js.DataTable.handleRowClick"_

The error is happening in the following line on DataTable.js DataTable.prototype.handleRowClick function:
`       var column = this.columns[this.domHandler.index(cell)];
            if (column.editable) {
                this.switchCellToEditMode(cell, column, rowData);
                return;
            }
 }`

The `this.columns[this.domHandler.index(cell)` is returning the day of week index of the calendar, not the column index of the datatable.

**Expected behavior**
The date should be set correctly (as it is) but without the error.

**Minimal reproduction of the problem with instructions**

1. Create a editable p-datatable with 3 columns
2. Create a editable column with a p-calendar pTemplate="editor"
3. Select any day between Sunday and Tuesday => **no erros**
4. Select any day after Tuesday => **error**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.2.4

* **PrimeNG version:** 4.1.0-RC1 and 4.1.0-RC2
**_It's working on correctly on 4.0.3._**

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by AndreK0** [comment]
I have the same issue:
angular: 4.1.1
primeNG: 4.1.0

**Comment by wcgomes** [comment]
Problem still on primeng 4.1.1 and angular 4.3.1.

**Comment by mlakhara** [comment]
Problem still persists. I tried overiding the findCell method to go up to the parent where it finds the actual TD element with class 'ui-editable-column' but this gives the error that parentNode is null after reaching TR element of the calendar.

**Comment by cagataycivici** [comment]
Can you replicate at;

https://www.primefaces.org/primeng/#/datatable/editable

**Comment by mlakhara** [comment]
Yes Here is the gif for the same
![calendar_error](https://user-images.githubusercontent.com/3102446/29650138-74710fec-88b6-11e7-94b2-9d96dc287860.gif)

This is because in handleRowClick tries to find the parent td for getting the editable cell. However in case of calendar, it gets a different td (in calendar template) and that throws the code off. I tried to modify the code to find the td with the given proper editable class .ui-editable-cell by going up the chain recursively. However it breaks in the middle when it can't find the parent to tr of the calendar. I was not able to solve that part.

**Comment by cagataycivici** [comment]
That is because popup of calendar is removed from dom when it gets hidden.

**Comment by cagataycivici** [comment]
Fixed by using the onClick of cell instead, so a rollback to 4.0.x. This was also breaking other cases like dropdown so fixed now for good.

**Comment by marialva1705** [comment]
Hi, I'm doing an application in angulr 5 but I'm having problems with the MomentDateAdapter.setLocale specifically with the Chinese language. I get this error by console 
ng:///ViewsModule/MainTabComponent.ngfactory.js:72 ERROR TypeError: Cannot read property 'firstDayOfWeek' of null
    at MomentDateAdapter.setLocale (webpack-internal:///../../../material-moment-adapter/esm5/material-moment-adapter.es5.js:73)
    at new MomentDateAdapter (webpack-internal:///../../../material-moment-adapter/esm5/material-moment-adapter.es5.js:57)
    at createClass (webpack-internal:///../../../core/esm5/core.js:12646)
    at _createProviderInstance (webpack-internal:///../../../core/esm5/core.js:12623)
    at createProviderInstance (webpack-internal:///../../../core/esm5/core.js:12464)
    at createViewNodes (webpack-internal:///../../../core/esm5/core.js:13936)
    at createEmbeddedView (webpack-internal:///../../../core/esm5/core.js:13826)
    at callWithDebugContext (webpack-internal:///../../../core/esm5/core.js:15263)
    at Object.debugCreateEmbeddedView [as createEmbeddedView] (webpack-internal:///../../../core/esm5/core.js:14575)
    at TemplateRef_.createEmbeddedView (webpack-internal:///../../../core/esm5/core.js:11901).
