### ISSUE TITLE
Horizontal scrollbar disappears primeng when no records found

### ISSUE THREAD

**Issue by jayordway** [primefaces/primeng#3257]
Horizontal scroll bar on primeng data table disappears when there are no records.

**Comment by cagataycivici** [comment]
Unable to replicate;

<img width="641" alt="screen shot 2017-08-25 at 15 28 40" src="https://user-images.githubusercontent.com/686247/29714092-265dd96c-89aa-11e7-8094-ab5f7cbec28b.png">
