### ISSUE TITLE
Datatable Row Selection Accessibility: Potential fix

### ISSUE THREAD

**Issue by dausm** [primefaces/primeng#3258]
[ ] bug report => Search github for a similar issue or PR before submitting
[ x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/Wj39h1?p=preview

**Current behavior**

I’m currently working on a project where I am utilizing the PrimeNG datatable. Users will need the ability to select multiple rows. There is not any problem with their functionality but with their accessibility. 
Currently I have not figured out a workaround for my project but figured I would offer a solution for the repository. Just trying to help.

For both the radio and checkbox templates add the following code to the input tags:
```
(click)="handleClick($event)" (keyup.enter)="handleClick($event)"
(focus)="onFocus($event)" (blur)="onBlur($event)" tabindex="0"
```

Add the additional class expression to the proceeding divs that wrap the font-awesome spans
`'ui-state-focus':focused`

Finally for each component class add:
```
public focused: boolean;

onFocus(event) {
    this.focused = true;
}

onBlur(event) {
    this.focused = false;
}
```
I noticed that the PrimeNG Checkbox was accessible so I essentially used that code.

**Expected behavior**
All datatable selection options would be ADA Section 508 compliant

**Minimal reproduction of the problem with instructions**
As of now no datatable selection options are selectable using the keyboard.

**What is the motivation / use case for changing the behavior?**
Making the datatable more accessible.

**Please tell us about your environment:**

* **Angular version:** 4.2.0

* **PrimeNG version:** 4.1.0-rc.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` = v6.9.5

**Comment by cagataycivici** [comment]
Tracked at #713
