### ISSUE TITLE
DataTable. Cursor within filter field jumps to the end in Chrome

### ISSUE THREAD

**Issue by ctrl-brk** [primefaces/primeng#3260]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
In Chrome every time filtering takes place the cursor jumps to the end of the filter input field.
Works fine in Firefox.

**Expected behavior**
Chrome should works the same as Firefox

**Minimal reproduction of the problem with instructions**
Using Chrome go to [https://www.primefaces.org/primeng/#/datatable/filter](https://www.primefaces.org/primeng/#/datatable/filter). Enter 'a' the filter for "Vin" column. Press "Home" key and enter another 'a' character. Cursor will jump to the end of the input value.

**Comment by cagataycivici** [comment]
I'm afraid I can't replicate with 4.1.3
