### ISSUE TITLE
Improve ContextMenu collision detection

### ISSUE THREAD

**Issue by miresk** [primefaces/primeng#3261]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Submenu is position properly only when it is opened on the right side of the viewport. It is displayed correctly on the left side then. (this was fixed in #1596)

**Expected behavior**
Could you please also fix the position of the submenu when it is open at the bottom of the page? It overflows the bottom of the viewport.
![contextmenu-issue](https://user-images.githubusercontent.com/2345749/27722506-6ad30fcc-5d68-11e7-9372-1c740389ef64.jpg)

**What is the motivation / use case for changing the behavior?**
Submenu should reposition itself on all sides of the viewport, not just when open near the right edge

* **Angular version:** 4.2.2

* **PrimeNG version:** 4.1.0

**Comment by mlandry-devolutions** [comment]
We use the contextMenu in a p-tree in our app and we have this exact issue. Is it planned to be fix in the future ?
Thanks!

**Comment by danieljones740** [comment]
Is there a plan to fix this?  We use the contextMenu component in our application and it frequently overflows its container.

**Comment by cagataycivici** [comment]
Is it reproducible at?

https://www.primefaces.org/primeng/#/contextmenu
