### ISSUE TITLE
Some lines in the tables disapear when Zoom in and Zoom out

### ISSUE THREAD

**Issue by Agisbert** [primefaces/primeng#3265]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

Not plunkr, your own page is enough:
https://www.primefaces.org/primeng/#/datatable

**Current behavior**
In FIREFOX, depending on the zoom of the browser (Ctrl +/-) you have in the screen, some division lines of the table, appear and disapear. This behaviour is not present in Chrome. 

**Expected behavior**
Showing all the lines no matter the zoom you use in the browser.

**Minimal reproduction of the problem with instructions**
Go to https://www.primefaces.org/primeng/#/datatable, Zoom in and Zoom out, you will see some lines of the tables appearing and disapearing. 

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X
Whatever is in your webpage. 

* **PrimeNG version:** 2.0.X
Whatever is in your webpage. 

* **Browser:** [Firefox XX ]

* **Language:** []

* **Node (for AoT issues):** `node --version` =   
Whatever is in your webpage.

**Comment by cagataycivici** [comment]
I'm unable to replicate with latest PrimeNG.
