### ISSUE TITLE
Add wildcard functionality to DataTable filter

### ISSUE THREAD

**Issue by ctrl-brk** [primefaces/primeng#3268]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request
```

**Minimal reproduction of the problem with instructions**
Would be very helpful to be able to use wildcard search characters (like * and ?) in addition to already existing filter types.

**Comment by cagataycivici** [comment]
Isn't * contains and ? startsWith? Request is not clear to me.
