### ISSUE TITLE
Allow buttonText customization for p-schedule like fullcalendar

### ISSUE THREAD

**Issue by Sebi55** [primefaces/primeng#3271]
**I'm submitting a ...**
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
The buttonText for the labels "today", "month", etc. are in english.
FullCalendar though is offering a parameter buttonText which lets you set these labels.
https://fullcalendar.io/docs/text/buttonText/
Maybe I have overseen this feature on p-schedule but I cannot find it.

**Expected behavior**
Add a property to p-schedule which allows setting this property.

**What is the motivation / use case for changing the behavior?**
This would allow multiple languages for the buttons.

* **Angular version:** 4.2.4

* **PrimeNG version:** 4.1.0-rc.3

* **Browser:** all
 
* **Language:** all

**Comment by negberts** [comment]
I would like this feature as well!

**Comment by negberts** [comment]
@Sebi55 I fixed it by including locale/nl.js after de import of fullcalendar.min.js and then setting locale='nl' in p-schedule. The button texts are now in Dutch

**Comment by cagataycivici** [comment]
Glad to hear issue is resolved.

**Comment by jbiversen** [comment]
I have tried using the same approach (including a language locale .js file and setting the same locale on p-schedule), but only the month weekday names are translated, not the button texts, and not the all-day text. I am using primeng v. 5.0.2, and fullcalendar v. 3.7.0. 

This is part of my code:

`<p-schedule #eventSchedule 
                    [events]="scheduleMeetings"
                    [header]="headerConfig"
                    [options]="scheduleConfig"
                    locale="da"
                    (onEventClick)="openEvent($event)"
                    (onDayClick)="createEvent($event)"
                    (onEventResize)="resizeEvent($event)"
                    (onEventDrop)="dropEvent($event)"></p-schedule>`

`    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.19.2/moment.min.js"></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.7.0/fullcalendar.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.7.0/locale/da.js'></script>`
