### ISSUE TITLE
Autocomplete reactive form with dropdown true. No list appear on click arrow button.

### ISSUE THREAD

**Issue by oixan** [primefaces/primeng#3272]
I'm submitting a ...
[ x ] bug report 
[ ] feature request
[ ] support request 

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/RYUqrAO3nVzT0JgGNIED?p=preview

**Current behavior**
On click arrow down button nothing happend.

**Expected behavior**
On click arrow down the suggest list should appear.

** about your environment:**
Angular 4. Autocomplete with reactive form.
"primeng": "^4.1.0-rc.3",

**Comment by oixan** [comment]
to solve the problem just mimic the remote call with setTimeout on onDropdownClick event. In my case i filtered the list locally So the problem appear.

**Comment by cagataycivici** [comment]
Hmm, when I click the button the list shows up for me.
