### ISSUE TITLE
InputMask doesn't work with Samsung Mobile

### ISSUE THREAD

**Issue by frcandia** [primefaces/primeng#3275]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
In Samsung mobile (S7, Tablet S2, etc) using "Samsung Keyboard" access the PrimeNG's example page and try type into a mask component. 

https://www.primefaces.org/primeng/#/inputmask

**Current behavior**
When is typing the values into the component don't work, some values are not accepted and some times the component is fill out with random numbers

**Minimal reproduction of the problem with instructions**
Just access in Samsung mobile (S7, Tablet S2, etc) using "Samsung Keyboard" the PrimeNG's example page and try type into a mask component. 

https://www.primefaces.org/primeng/#/inputmask

<b>A workaround when the mask is just numbers is put the directive type="tel". This works in Samsung Keyboard.</b>

Example:
```<p-inputMask unmask="true" [(ngModel)]="myModel" mask="999.999.999-99" type="tel" ></p-inputMask>```

* **Angular version:** 4.0.X

* **PrimeNG version:** 4.1.0-rc.3 

* **Browser:** [all, but using Samsung Keyboard from Samsung Mobile (S7, Tablet S2, etc) ]

* **Language:** [all]

* **Node (for AoT issues):** `node --version` =   v6.11.0

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
