### ISSUE TITLE
Bug: 4.1.0-rc.3 multiple selection broken in Data Table

### ISSUE THREAD

**Issue by kcsahoo** [primefaces/primeng#3277]
Works in rc.2
In rc.3, it works like single selection.
When you click on one checkbox, it deselects other checked ones.

**Comment by Mrtcndkn** [comment]
It works normally in my local could you please create a plunkr.

**Comment by sudheerj** [comment]
Yes, I too can't replicate the issue. Please try with rimraf clean install.

**Comment by kcsahoo** [comment]
No it did not help.
I am using
 <p-dataTable #dt [value]="rowData" selectionMode="multiple" [(selection)]="modelPoePartIdsToDelete" [responsive]="true" [globalFilter]="gb" exportFilename="ModelPOEParts"
                 (onRowSelect)="onRowSelect($event)" (onRowUnselect)="onRowUnselect($event)">
        <p-footer>(Count: {{rowCount}})</p-footer>
        <p-column [style]="{'width':'38px'}" selectionMode="multiple"></p-column>
        <p-column field="id" header="id" [sortable]="true" hidden="hidden"></p-column>
        <p-column field="poePartId" header="poePartId" [sortable]="true" hidden="hidden"></p-column>
        <p-column field="vehicleModelId" header="vehicleModelId" [sortable]="true" hidden="hidden"></p-column>
        <p-column field="description" header="Description" [sortable]="true"></p-column>
        <p-column field="dependencies" header="Dependencies" [sortable]="true"></p-column>
        <p-column field="partNumber" header="Part No" [sortable]="true"></p-column>
        <p-column field="price" header="Price" [sortable]="true"></p-column>
    </p-dataTable>

This is working with rc.2 version

**Comment by mix5003** [comment]
plunkr for this case
http://plnkr.co/edit/gevJEpU3aof05z6bkOiP?p=preview

if you click at checkbox it will work correctly. but if you click at other column (for example if you click at Year column)  it will select as single select mode.

**Comment by kcsahoo** [comment]
You are using rc.2 and it works there.
In rc.3 only it breaks.

**Comment by mix5003** [comment]
sorry. i update to rc3. and  now it broken every time.

**Comment by Mrtcndkn** [comment]
Enabling both selectionMode for p-datatable and p-column causes the issue.

**Comment by cagataycivici** [comment]
You need to add [metaKeySelection]="false"

**Comment by cagataycivici** [comment]
Fix checked in, @Mrtcndkn verify please.

**Comment by Mrtcndkn** [comment]
It is working great. Ready for next release.
