### ISSUE TITLE
AutoComplete panel is hidden in DataTable

### ISSUE THREAD

**Issue by adrienverge** [primefaces/primeng#328]
When using an `AutoComplete` component in a `DataTable`, the suggestion panel doesn't go out of the table row. As a consequence, only one or two choices can be clicked. See the following screenshot:

![datatable autocomplete](https://cloud.githubusercontent.com/assets/5244945/15119564/ca7f16e0-1611-11e6-9794-b7446ae81873.png)

The code I use is a simple copy-paste from the doc: a "multiple" autocomplete in a "template" column. (I tried to make a plunker snippet with PrimeNG, but I had a hard time linking the libs...)

```html
<p-dataTable [value]="groups">
  <p-column field="name" header="Name"></p-column>
  <p-column field="content" header="Content">
    <template let-group="rowData">
      <p-autoComplete [(ngModel)]="group.items"
                      [suggestions]="filteredCountriesMultiple"
                      (completeMethod)="filterCountryMultiple($event)"
                      [minLength]="1"
                      field="name"
                      [multiple]="true"
                      style="width:100%">
      </p-autoComplete>
    </template>
  </p-column>
</p-dataTable>
```

**Comment by cagataycivici** [comment]
You need to set overflow:visible in the column;

```html
<p-column field="content" header="Content" style="{'overflow':'visible'}">
```

**Comment by sumanballapuramgh** [comment]
i have a problem rendering autocomplete within Datatable. 
The Autocomplete suggestions are opened for all the columns irrespective of specific column. 

Here is the code-snippet:
 <p-dataTable [value]="cars" [editable]="true">
                <p-column field="vin" header="Vin" [editable]="true"></p-column>
                <p-column field="year" header="Year" [style]="{'overflow':'visible'}">
                    <template let-col let-car="rowData">
                        <p-autoComplete [(ng-model)]="country" [id]="car['vin']" [suggestions]="filteredCountriesSingle" (completeMethod)="filterCountrySingle($event)"
                            field="name" [size]="30" [minLength]="1">
                        </p-autoComplete>
                    </template>

                </p-column>

Any help is much appreciated

![autocomplete-issue](https://cloud.githubusercontent.com/assets/13904099/17099393/ab1a712c-5285-11e6-97b8-e1b7d82a8f03.jpg)

**Comment by sumanballapuramgh** [comment]
i have a problem rendering autocomplete within Datatable.
The Autocomplete suggestions are opened for all the columns of all rows irrespective of desired column for a specific row.

Here is the code-snippet:
![autocomplete-issue_code](https://cloud.githubusercontent.com/assets/13904099/17099608/19755424-5287-11e6-9afa-11d303544c4f.png)
Any help is much appreciated.

![autocomplete-issue](https://cloud.githubusercontent.com/assets/13904099/17099455/19f1b2d6-5286-11e6-8cbf-00f0714865bb.jpg)

**Comment by vvvttt** [comment]
@sumanballapuramgh, did you find any solution for your issue?

**Comment by deoxyseia** [comment]
I try using `style="{'overflow':'visible'}"` but error persist:

<img width="1413" alt="captura de pantalla 2016-10-14 a las 20 39 34" src="https://cloud.githubusercontent.com/assets/1824764/19406643/07d3c7e8-924f-11e6-8f59-94f7ba464874.png">

I'm using:

- Angular Final release.
- primeng
- 1.0.0-beta.17
- primeui 4.1.15
- Olympos theme 1.0.2

**Comment by harveenchadha** [comment]
Please use appendTo="body"
