### ISSUE TITLE
disabledDates in calendar are not updating

### ISSUE THREAD

**Issue by wsz34** [primefaces/primeng#3283]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/FykwvAeH0BhdxZUiF6RG?p=preview

**Current behavior**
First dates set as disabledDates are marked in the calendar as disabled. But if I update disabledDates property in the component, I have to go to the next month and then back to see changes.

**Expected behavior**
After changing disabledDates value, changes should be visible in the calendar instantly.

**Minimal reproduction of the problem with instructions**
Open plnkr case http://plnkr.co/edit/FykwvAeH0BhdxZUiF6RG?p=preview
Run it
Open the calendar
Notice disabled dates
Click on "Click me" button (now all the disabled dates are cleared)
Notice that disabled dates are still in the calendar
Go to next month
Go back to this month
Notice that disabled dates disappeared only now

* **Angular version:** 4.1.3
* **PrimeNG version:** 4.1.0-RC2
* **Browser:** all
* **Language:** all

**Comment by EugeneBugor** [comment]
Same behavior.
**Plunker Case:** http://plnkr.co/edit/zI22N5Vknm8zMoNOeO46?p=preview
