### ISSUE TITLE
RadioButton onClick doesn't work when user clicks on label

### ISSUE THREAD

**Issue by lavamen** [primefaces/primeng#3286]
When user clicks on label onClick event is not fired. But it works if user clicks on radio button directly.

**Angular version:** 4.1.0
**PrimeNG version:** 4.0.3
The latest Chrome

**Comment by cagataycivici** [comment]
Works for me at;

https://www.primefaces.org/primeng/#/radiobutton

**Comment by lavamen** [comment]
It doesn't work
I created an exemple
http://plnkr.co/edit/upCMls6dQBWSbbCl0WBV?p=preview
When you click on text of a radio button and on the radio button, it is a different result
![screenshot_1](https://user-images.githubusercontent.com/29777634/29669629-173373e6-88b2-11e7-80bd-8d9896b69a58.png)

**Comment by lavamen** [comment]
Sorry, I gave invalid link, this is a correct link
http://plnkr.co/edit/FzxSBxFVvrh8E2PEJKtV?p=preview

**Comment by Rebirthen** [comment]
I got it. Take good care of inputId. 
`<div *ngFor="let vars of variables | keyvalue" class="p-col-12 p-field-checkbox" >
          <p-radioButton
            name="group"
            inputId="{{vars.key}}"   
            [value]="vars.key"
            [(ngModel)]="selectedNodeType"
            (change)="handleNodeChange()"
          ></p-radioButton
          ><label [for]="vars.key">Add {{ vars.key }}</label>
        </div>`
