### ISSUE TITLE
rowStyleClass does not work when css class is defined in component.

### ISSUE THREAD

**Issue by overflowz** [primefaces/primeng#3287]
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/nCpYqbKQfgoVeFdKyDWr?p=preview

**Current behavior**
It does not highlight rows when css class is defined in the component's css file, but works if we move css class to global styles.

**Expected behavior**
It should highlight rows in DataTables when loading css from a component css.

**Please tell us about your environment:**

Using Windows, VSCode, NPM package manager and ng serve via angular-cli.

* **Angular version:** 4.0.0

* **PrimeNG version:** 4.1.0-rc.3

* **Browser:** Chrome 59.0.3071.109

 
* **Language:** TypeScript 2.3.4

* **Node (for AoT issues):** `node --version` =  7.9.0

Also, here is the SO answer (and I had the same problems) which was answered in 2016. https://stackoverflow.com/a/40711105/1444038

**Comment by brpradeepprabhu** [comment]
use  ViewEnacapsulation and please update your code like this 

import { Component,ViewEncapsulation } from '@angular/core';

@Component({
  selector: 'my-app',
  templateUrl: 'app/app.template.html',
  styleUrls: ['app/app.component.css'],
  encapsulation:ViewEncapsulation.None
})

**Comment by overflowz** [comment]
It worked, thanks!

but as far as I understand, encapsulation tells class to not define styles (in this case) for current module but globally.

I think best and closest way is to use /deep/ method (found via a lot of googling).

Regards.
