### ISSUE TITLE
Issue with autoComplete and field attribute

### ISSUE THREAD

**Issue by stephanecot** [primefaces/primeng#3289]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

My case is simple.
In primeng 4.0.x, I had the following code:

`
<p-autoComplete formControlName="wording"  ... />
`

With this form config:

`
        const row: FormGroup = fb.group({ 
            id: fb.control(''),
            required: fb.control(false),
            wording: fb.control('', [Validators.required, this.validWording.bind(this)]),
            type: fb.control(null, Validators.required),
            labels
        });
`

When I display my HTML form in edit mode, the result input is correctly filled with my data.

When I switch to PrimeNg 4.1.RC, my input from autoComplete is empty !
Standard `<input>`, `<p-dropdown>` et `<p-checkbox>` are still working too.

**Please tell us about your environment:**
* **Angular version:** 4.2.5
* **PrimeNG version:** 4.1 RC 2 & 3

**Comment by stephanecot** [comment]
Any news on this issue ?

**Comment by stephanecot** [comment]
I have found the reason of the bug.
I have made a Plunker for it:
http://plnkr.co/edit/W143ZGDSFPcCSMyCrASI

It's the "field" attribute which cause this bug.

Take my plunker, change the primeng version: 'primeng': 'npm:primeng@4.0.1' and the input field is OK, change to 4.1.x, with a field attribute, the input is KO.

**Comment by cagataycivici** [comment]
Fixed via https://github.com/primefaces/primeng/issues/3360
