### ISSUE TITLE
Multi Row Grouping Feature for DataTable

### ISSUE THREAD

**Issue by xiongyayun428** [primefaces/primeng#3290]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/Wj39h1?p=preview

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.2.5

* **PrimeNG version:** 4.1.0-rc.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript 2.3.4 | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   

---------------------------------------------------------------------------------------------

I want to be as shown below

![image](https://user-images.githubusercontent.com/11458959/27825481-3f47a624-60e2-11e7-843b-9e4aaea61e79.png)

```ts
<p-dataTable [value]="datas" [sortField]="sortField" sortMode="multiple" rowGroupMode="rowspan" [multiSortMeta]="multiSortMeta">
    <p-header>result</p-header>
    <p-column *ngFor="let col of header" [field]="col.field" [header]="col.header" [filter]="true" sortable="true" filterMatchMode="contains" filterPlaceholder="Search"></p-column>
</p-dataTable>
```

I need dynamic column, dynamic lines, data is an inter-bank,
I tried to use the following
```ts
<p-dataTable [value]="sales">
    <p-headerColumnGroup>
        <p-row>
            <p-column header="Brand" rowspan="3"></p-column>
            <p-column header="Sale Rate" colspan="4"></p-column>
        </p-row>
        <p-row>
            <p-column header="Sales" colspan="2"></p-column>
            <p-column header="Profits" colspan="2"></p-column>
        </p-row>
        <p-row>
            <p-column header="Last Year"></p-column>
            <p-column header="This Year"></p-column>
            <p-column header="Last Year"></p-column>
            <p-column header="This Year"></p-column>
        </p-row>
    </p-headerColumnGroup>
    
    <p-column field="brand"></p-column>
    <p-column field="lastYearSale"></p-column>
    <p-column field="thisYearSale"></p-column>
    <p-column field="lastYearProfit"></p-column>
    <p-column field="thisYearProfit"></p-column>
    
    <p-footerColumnGroup>
        <p-row>
            <p-column footer="Totals:" colspan="3"></p-column>
            <p-column footer="$506,202"></p-column>
            <p-column footer="$531,020"></p-column>
        </p-row>
    </p-footerColumnGroup>
</p-dataTable>
```

But only support at the bottom of the head and an inter-bank, don't know an inter-bank body data

**Comment by bhaidar** [comment]
@cagataycivici When is this feature going to ship? Thanks

**Comment by rev87** [comment]
@cagataycivici Hi, I would like to ask if there is any progress on this feature? Thank you :)

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
