### ISSUE TITLE
p-dialog - onHide runs when Dialog is initialised

### ISSUE THREAD

**Issue by MarkPerryBV** [primefaces/primeng#3292]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/C97uYUtuk4QxT3XSiX7m?p=preview

**Current behavior**
the (onHide) event emitter emits when the app.component loads

**Expected behavior**
The (onHide) event should NOT fire when the modal is already "hidden"

**Minimal reproduction of the problem with instructions**
Just add a p-dialog (initialised to hidden) and attach a (onHide) function which logs.

**What is the motivation / use case for changing the behavior?**
No need to fire event handlers when nothing has changed,

* **Angular version:** 2.0.X
Latest

* **PrimeNG version:** 2.0.X
Latest

* **Browser:** [all]
 
* **Language:** [all]

**Comment by cagataycivici** [comment]
Fixed for 4.1.1
