### ISSUE TITLE
Add tooltipZIndex property

### ISSUE THREAD

**Issue by ARandomDude** [primefaces/primeng#3294]
**I'm submitting a ...**
```
[X] bug report
[ ] feature request 
[ ] support request
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/78IBU8g0UvINCmQ7aV26?p=preview

**Current behavior**
In a p-dialog with an input with a pTooltip, the tooltip gets shown on hover as expected; but when clicking the input, the tooltip moves behind the dialog.

**Expected behavior**
I would expect that, on clicking the input, the tooltip stays on top of the dialog.

**Minimal reproduction of the problem with instructions**
See the Plunkr above. Click the "dialog" button and then hover and then click the input.

As I can see, the problem is that everytime the dialog or a component inside it gets clicked, the p-dialog's z-index is increased by one (this is probably intended behavior; but leads to the above issue).

-----

Temporary workaround for other users: Just assign the tooltips a z-index high enough that the abovementioned increase will not overshadow the tooltip, e.g.:
`body div.ui-widget.ui-tooltip
{
    z-index: 3000 !important;
}`

**Comment by cagataycivici** [comment]
Added tooltipZIndex to tooltip directive to managing these easier as I currently think it is easier to handle on your side, defaults to auto and in your case should be a higher value.
