### ISSUE TITLE
New grid system based on flex

### ISSUE THREAD

**Issue by Tuizi** [primefaces/primeng#3298]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**

The current grid system is based on the float layout.

**Expected behavior**

Add a new grid system based on the flex layout (because we are in 2017)

**What is the motivation / use case for changing the behavior?**

No need to present the popular display property: `flex`. PrimeNG is the only new framework that still use the old layout system: float. It could be great to have a grid system based on `display: flex` and even better in the future, based on `display: grid`

**Comment by ova2** [comment]
+1

I hate outdated float based layout too. For now, we can use Flexbox in Bootstrap 4. There is one section in the upcoming book which describes Flexbox intergration in PrimeNG. Project is here: https://github.com/ova2/angular-development-with-primeng/tree/master/chapter2/graphic-editor-bootstrap4

**Comment by Tuizi** [comment]
@ova2 On our side we will switch from PrimeNG grid system to Angular official Flex Layout system https://github.com/angular/flex-layout/wiki/Responsive-API

**Comment by ova2** [comment]
I don't like Angular directives and prefer pure CSS solution for Flexbox
layout (pure CSS works faster). Names are also shorter. My choice is
Bootstrap 4 Layout system. It's very powerful.

Am 04.07.2017 22:53 schrieb "Fabien Rogeret" <notifications@github.com>:

**Comment by bogacg** [comment]
I'm also working with Flex layout now (Angular Flex Layout) and I see PrimeNG is not compatible. 
For example I've tried GMaps component and `width:100%` is not rendered, only specific pixel values.

**Comment by intergleam** [comment]
@Tuizi  Flex Layout is still in beta and full of bugs

**Comment by Tuizi** [comment]
@intergleam We use it here for 4 months and no blocking bugs. Angular will start to be more active with FlexLayout, I know its a beta but everything we were expecting work perfectly with this version right now

**Comment by intergleam** [comment]
I have     "@angular/common": "2.4.8", tried to install     "@angular/flex-layout": "^2.0.0-beta.8", and I have a bunch of errors... 

`WARNING in ./~/@angular/flex-layout/media-query/breakpoints/break-points-token.js 
13:29 export 'InjectionToken' was not found in '@angular/core'`

and much more

**Comment by Tuizi** [comment]
You should consider updating your Angular version, they will not support 2.4.x. It's in bold at the beginning of the [Readme](https://github.com/angular/flex-layout)

**Comment by AlejandroFlorin** [comment]
+1 for this feature. It would be nice if we could use the other flexbox alignment options with the grid system (horizontal and vertical alignment, etc.)

**Comment by cagataycivici** [comment]
FlexGrid coming soon for 6.1.4.

**Comment by cagataycivici** [comment]
Implemented for 6.1.4.

**Comment by cagataycivici** [comment]
https://www.primefaces.org/primeng/#/flexgrid

**Comment by SarvagyaS** [comment]
I have bought Ultima theme. But, there are no styles for flexgrid classes in theme's CSS file. I am using flexgrid.css but that makes the page very unattractive.

**Comment by scblur869** [comment]
how long before the current Grid CSS is removed and FlexGrid is fully documented and all examples updated on the site with FlexGrid?

**Comment by cicciogeppo88** [comment]
Hello, 
will it be possible to update the ultima primeng templates in order to use the flexgrid system? they are currently outdated and misleading, 

Thanks,
