### ISSUE TITLE
p-Calendar select day from other month

### ISSUE THREAD

**Issue by cyberrranger** [primefaces/primeng#3302]
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

show on:
https://www.primefaces.org/primeng/#/calendar

and a example
https://jqueryui.com/datepicker/#other-months

![screenshot 2017-07-05 10 32 31](https://user-images.githubusercontent.com/21671762/27856124-51f5c356-616d-11e7-87f1-aee6456ed4c4.png)

i cant select June 30 (or August 1) before i change the month to June / August

Regards
Patrick

**Comment by wsz34** [comment]
Have you tried setting selectOtherMonths to true?

**Comment by cyberrranger** [comment]
now yes :)

thx
