### ISSUE TITLE
Required validation for Editor

### ISSUE THREAD

**Issue by gsyjdcg** [primefaces/primeng#3308]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

The p-editor component with the "required" attribute does not detect that it is filled when only one character is inserted

**Expected behavior**

The p-editor component with the "required" attribute should indicate that it is complete when only one character has been entered.

**Please tell us about your environment:**

Windows 10, vscode,

* **Angular version:** 4.2.5

* **PrimeNG version:** 4.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

TypeScript 2.4.0

* **Node (for AoT issues):** `node --version` =   7.10.0

**Comment by rafa-as** [comment]
@cagataycivici do you accept PR for this bug?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
