### ISSUE TITLE
AutoComplete - Suggestions display issue when suggestions above

### ISSUE THREAD

**Issue by MarkPerryBV** [primefaces/primeng#3312]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
If the list of suggestions needs to render above the textbox then when you narrow the selection the suggestions box detaches from the textbox element.

**Expected behavior**
The suggestions list need to stay anchored to the element. Either above or below.

**Minimal reproduction of the problem with instructions**
![autocompletebug](https://user-images.githubusercontent.com/10271490/27869101-c65d0a0a-6196-11e7-841e-80792f2e2ae5.gif)

* **Angular version:** 2.0.X
Latest

* **PrimeNG version:** 2.0.X
Latest

* **Browser:** [all]
 
* **Language:** [all]

**Comment by cagataycivici** [comment]
This works fine with Angular 4.1.0, unfortunately 4.2.0 and newer broke it, so had to add a workaround for the fix.
