### ISSUE TITLE
appendTo for SlideMenu

### ISSUE THREAD

**Issue by Tempus35** [primefaces/primeng#3313]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
I can not duplicate my exact code, I am not allowed to share it. What I have those is a grid of rows and columns, with each square in that grid able to have multiple objects. Each object can open this slideMenu but when you click an object (All of these is made based on data on load) it opens the menu in some crazy position.

**Current behavior**
Currently there is no way to tell the slideMenu to attachTo a point or use a target as the point. Both these options are in the contextMenu.

**Expected behavior**
The slideMenu to have similar inputs/functions as the contextMenu which would allow setting the attachTo or target.

**Minimal reproduction of the problem with instructions**
Add a slideMenu that is dynamically made and opened in various places on a page, see it not be in the right places.

**What is the motivation / use case for changing the behavior?**
I have a slideMenu that is dynamically created and asked to open on various points on the page, when it does so it is not opening where you click but off by a lot.

**Please tell us about your environment:**

* **Angular version:** 2.0.X
4.2.5

* **PrimeNG version:** 2.0.X

4.1.0-rc.2
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All
* **Node (for AoT issues):** `node --version` =

**Comment by ntkolev** [comment]
I would also like to see this feature implemented.
