### ISSUE TITLE
Add required property to InputMask

### ISSUE THREAD

**Issue by robellisetcc** [primefaces/primeng#3317]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
p-inputMask does not have an @Input() for 'required' attribute

**Expected behavior**
If the form is using ngNativeValidate, clicking a submit button should show the html5 validation message on a p-inputMask control if the value for the field is empty.  Either 'required' or [required]="true" in the markup for the p-inputMask should recognize the field as ng-invalid if no value is entered.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/81NzSj?p=preview

**What is the motivation / use case for changing the behavior?**
While a form should not rely on html5 validation, the native html5 validation allows the form to notify the user which required field they did not fill out and also shifts focus to that field.

**suggested code change**:
add  @Input() required: boolean = false; to the p-inputMask component.
add [required]="required" to the input control in the html of the p-inputMask template

* **Angular version:**  
4.1.2

* **PrimeNG version:** 2.0.X
4.0.3

* **Browser:** 
Chrome , IE
 
* **Language:** 
ES5

**Comment by scurk1415** [comment]
I would also like for this to be implemented.

**Comment by cagataycivici** [comment]
Fixed at 3503
