### ISSUE TITLE
Paginator rendering issues with some themes

### ISSUE THREAD

**Issue by bomberblue07** [primefaces/primeng#3319]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**Current behavior**

Paginator buttons do not seem to render properly with the Lightness theme

**Expected behavior**

They should render properly

**Minimal reproduction of the problem with instructions**

Just go to the paginator demo page (https://www.primefaces.org/primeng/#/datatable/paginator) and change the theme to Lightness

**What is the motivation / use case for changing the behavior?**

I want to be able to use the Lightness theme with the paginator

**Please tell us about your environment:**

* **Angular version:** 4.1.3

* **PrimeNG version:** 4.1.rc.3

* **Browser:** [Chrome]

 
* **Language:** [TypeScript 2.3]

**Comment by sudheerj** [comment]
I can see the issue. So there should be a better color contrast for Ludvig, Redmond, lightTheme and so on.Thanks.
