### ISSUE TITLE
Schedule component throws error

### ISSUE THREAD

**Issue by pantonis** [primefaces/primeng#332]
I have updated to primeng beta5

Im getting following error when trying to use schedule control:

![image](https://cloud.githubusercontent.com/assets/3295086/15174691/99fe74c4-176b-11e6-87f6-6a34e5f6be16.png)

**Comment by pantonis** [comment]
dont know if that helps

![image](https://cloud.githubusercontent.com/assets/3295086/15175144/b49c4bec-176d-11e6-86f2-ee0bb306b1ba.png)

**Comment by pantonis** [comment]
anyone knows what is the problem?

**Comment by cagataycivici** [comment]
You need to add fullcalendar to your page;

http://fullcalendar.io/

If you have primeui-ng-all.min.js already, just add;

```xml
<link rel='stylesheet' href='fullcalendar/fullcalendar.css' />
<script src='lib/moment.min.js'></script>
<script src='fullcalendar/fullcalendar.js'></script>
```
