### ISSUE TITLE
Just a general question.

### ISSUE THREAD

**Issue by webdevaman** [primefaces/primeng#3322]
Just Asking a general Question here, out of curiosity.
Why don't you guys just use Bootstrap for css part in this project, like you use chart.js for charts and font-awesome for icons.
I'll be more happy to use Bootstrap with Primeng.

**Comment by sudheerj** [comment]
There are around 17 themes which gives more options for the users. Bootstrap CSS Framework is best in the industry but that shouldn't be the only option. There is bootstrap theme as well.The strategy is similar to PrimeFaces multi theme approach.

Please use forum for questions.
