### ISSUE TITLE
Bug: 4.1.0-rc.3 there is no way to deselect a node in TreeTable unless select mode set to checkbox

### ISSUE THREAD

**Issue by steve3d** [primefaces/primeng#3325]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

No need for Plunkr case, just go to official demo here: https://www.primefaces.org/primeng/#/treetable

**Current behavior**
there is no way to deselect a selected node unless the selection mode set to checkbox mode.

**Expected behavior**
no matter what selection mode is set to, there should be a way to deselect a selected node by click the selected node again.

**What is the motivation / use case for changing the behavior?**
no need for this, there is a `onNodeUnselect` event but there is no way to unselect a node?

**Comment by Mrtcndkn** [comment]
You can unselect a node simply using the metakey.  @steve3d

**Comment by steve3d** [comment]
use a metakey to unselect is not as simple as click the selected rows again.

btw, which key is metakey by default？

**Comment by Mrtcndkn** [comment]
That is by design if any other request come about this context we will conside but for now. Metakey for mac is cmd and for windows ctrl.
