### ISSUE TITLE
DataTable loading indicator Input

### ISSUE THREAD

**Issue by miniplus** [primefaces/primeng#3329]
**I'm submitting a ...**
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Loading icon for datatable is hardcoded as `fa-circle-o-notch`

**Expected behavior**
Allow user to use another icon as a loading indicator through a simple Input property

**What is the motivation / use case for changing the behavior?**
Throughout my entire app, I'm currently using a different font awesome loading indicator.
This causes the loading indicators to be inconsistent.

* **PrimeNG version:** 2.0.X
4.1.0-RC3

**Comment by sudheerj** [comment]
This one make sense to customize the icon. You can update PR with showcase documentation too. I mean property.

**Comment by miniplus** [comment]
Updated the docs as well, missed those.

**Comment by cagataycivici** [comment]
Merged, thank you.
