### ISSUE TITLE
Error in splitbutton - @angular/router-deprecated

### ISSUE THREAD

**Issue by ishara** [primefaces/primeng#333]
I am getting fallowing error.

node_modules/primeng/components/splitbutton/splitbutton.d.ts(4,24): error TS2307: Cannot find module '@angular/router-deprecated'.

**Comment by cagataycivici** [comment]
You also need to map it, please see;

https://github.com/primefaces/primeng-quickstart/blob/master/systemjs.config.js

**Comment by ishara** [comment]
I am using angular2-seed , and try with fallowing changes, but no luck

https://github.com/mgechev/angular2-seed/compare/master...cagataycivici:master

**Comment by ishara** [comment]
If I app import like this 

This is work.
import {Column} from "primeng/components/column/column"; 

This is not working
import {Column} from 'primeng/primeng';

**Comment by ishara** [comment]
This is fixed , angular2-seed does not included '@angular/router-deprecated'  in package.json
