### ISSUE TITLE
Building primeng and consuming locally

### ISSUE THREAD

**Issue by sgentile** [primefaces/primeng#3331]
I have pulled the primeng code and followed the instructions in the wiki.   I can successfully run ng serve.

My question now is - how are you creating the distribution via npm - ie. when I install from git I see it has the components and resources inside.   However, if I npm install locally via file path, it does not include the components and the resources.

Could you share the steps used to create the package ?

**Comment by sudheerj** [comment]
Please use forum for questions. This github tracker is specific to bugs or enhancements.Thanks.
