### ISSUE TITLE
Add filterField to Column

### ISSUE THREAD

**Issue by overflowz** [primefaces/primeng#3333]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
Currently, I have defined e.g role model as:
````
{ id: number, name: string }
````

I'm setting display name on column like this:
````
<p-column field="role.name" ...></p-column>
````

and I also have filter dropdown template, full column code:
````
<p-column field="role.name" header="role" [sortable]="true" sortField="role.id" [filter]="true" filterPlaceholder="Search" filterMatchMode="equals">
    <ng-template pTemplate="filter" let-col>
      <p-dropdown appendTo="body" [options]="roles" (onChange)="dataTable.filter($event.value?.id, col.field, col.filterMatchMode)"
        styleClass="ui-column-filter">
      </p-dropdown>
    </ng-template>
  </p-column>
````

I would like to filter by a role.id, rather than the role.name. If I add custom field (e.g filterField="role.id" and replace onChange event to `dataTable.filter($event.value?.id, col.filterField, col.filterMatchMode)` respectively, it does not pick up the value, it's always null).

* **Angular version:** 4.0.X

* **PrimeNG version:** 4.1.0-rc.3

* **Language:** all

* **Node (for AoT issues):** `node --version` = 8.1.2

**Comment by miniplus** [comment]
Why not make a filter function in your component, which you pass the params to and get the id out of the value yourself? Something along the lines of:

```html
(onChange)="filter(dataTable, event.value, col.field, col.filterMatchMode")
```
```javascript
filter(dataTable, value, field, matchMode) {
  if (value.id) {
    dataTable.filter(value.id, field, matchMode);
  } else {
    dataTable.filter(value, field, matchMode);
  }
}
```

**Comment by overflowz** [comment]
Not sure how to explain, but if I don't have option like "field=role.id" then datatable.filter(..) can't filter by role id at all.

**Comment by cagataycivici** [comment]
If we add filterField property, will that help? Defaults to field and you can customize it, similar to sortField.

**Comment by overflowz** [comment]
It will help, indeed.

**Comment by unaor** [comment]
is this working I have a nested json object and im trying to use the filterField yet its not working
data is displayed currectly though
```
<p-column field="equipmentInterfaceInfo" [filter]="true" filterPlaceholder="Interface Info" filterMatchMode="contains" filterField="equipmentInterfaceInfo.id" [editable]="true">
     <ng-template let-col let-interface="rowData" pTemplate="body">
      <span>{{interface.equipmentInterfaceInfo.id}} - {{interface.equipmentInterfaceInfo.description}}</span>
    </ng-template>
```

**Comment by hlaghari** [comment]
@unaor were you able to resolve your issue, as i am also facing the same issue where where i have bound me datatable with the array of json objects returned by the API and my columns are displaying fields from nested objects like {{row.object2.property1}} and the GlobalFilter is not working on all such fields. the global filter, however, is working with top level fields like {{row.property2}}. 

your response will be highly appreciated. 

regards.
