### ISSUE TITLE
Floating labels for Inputs

### ISSUE THREAD

**Issue by gtzinos** [primefaces/primeng#3334]
Hi,

I am using dropdown list and when a user select an item the placeholder isn't more visible. I created a topic at the forum (https://forum.primefaces.org/viewtopic.php?f=35&t=51604) and we decided that is good to have this feature for dropdown element (maybe for more other elements), it gives the user a better experience.

**Comment by cagataycivici** [comment]
We have this covered in themes such as Ultima or Barcelona but can do it for core as well.

**Comment by kc13greiner** [comment]
@cagataycivici Does this also work for dropdowns now?

**Comment by ccasallas** [comment]
@cagataycivici How does it work for dropdown with ultima theme?
I tried with **<span class="md-inputfield">** and **<span class="ui-float-label">** but it does not work.

**Comment by VNYoeri** [comment]
I don't know about dropdowns, but I seem to be able to get things "working" with p-autoComplete, by doing the following:
`<span class="md-inputfield"><p-autoComplete id="products"><ng-template><!--Some code here--></ng-template></p-autoComplete><label for="products">Product</label></span>`

By "working" I mean, when initialising the component, the label floats and the selected item is readable.
When selecting another item, it still works.
Clearing the input-field is a bug-trigger, see also the GIF below. 
![p-autocomplete-floating-label-bug](https://user-images.githubusercontent.com/28541690/31491401-6d3dfe08-af47-11e7-89eb-137edbff829e.gif)

If this comment (or the bug I describe above) isn't on-topic, my apologies and please, let me know so I can make a new topic.

**Comment by AlejandroFlorin** [comment]
Doesn't work with drop downs
