### ISSUE TITLE
DataTable : Horizontal Scroll issue with resizable and reorderable columns

### ISSUE THREAD

**Issue by rajhiMeher** [primefaces/primeng#3336]
Current behavior : 
When using scrollable="true" and fixing scrollHeight or scrollWidth, the functionnalities "resizable and reorderable columns" doesn't work any more.

Expected behavior 
Coexist the Horizontal Scroll with resizable and reorderable columns.

Angular version : 4.2.5
PrimeNG version: 4.1.0-rc.3

**Comment by cagataycivici** [comment]
Duplicate of 2399
