### ISSUE TITLE
Error in Calendar when validating input value

### ISSUE THREAD

**Issue by sabotup** [primefaces/primeng#3338]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/3GPKSVCNUdx7XOkap2dt

**Current behavior**
If you type some invalid date value directly, validation does it job, says date is not valid and text you introduced is kept in the input box of the calendar. However, if you select a valid date using calendar dropdown, and for example, remove two digits of the date (creating an invalid date), validation works, but text in the input box disappears. This behavior is not consistent with the one described before and also confuses the end user, because invalid date message is shown, but no text is on the input field.

**Expected behavior**
Text in the input box does not disappear after introducing a valid date and removing 2 digits for example. So if an invalid value is introduced, it is kept so user understands what is wrong.

**Minimal reproduction of the problem with instructions**
Follow the instructions in "Current behavior" in provided Plunkr

**What is the motivation / use case for changing the behavior?**
It is an inconsistent behavior and confuses end user.

**Please tell us about your environment:**
Windows 7

* **Angular version:** 2.0.X and 4.0.X

* **PrimeNG version:** 2.0.X and 4.0.X

* **Browser:** Chrome 59

**Comment by cagataycivici** [comment]
Manual input is also cleared in my case so behavior seems consistent to me. If more users demand this, we'll reopen. Also this should be an option like keepInvalidDate or so.

**Comment by sabotup** [comment]
It is only cleared after you introduce a valid date first. If you add the
first time an invalid date (aaaaa, e.g.), it will not clear. Anyways IMHO,
it is not consistent since the field is cleared, but the calendar stays in
invalid state when you use built in validator. So user will see a message
saying that the date is invalid, but there is not date in the field.



2017-07-19 9:54 GMT+02:00 Çağatay Çivici <notifications@github.com>:

**Comment by stephendougherty** [comment]
I would be very keen to see an option to keepInvalidDate for example. I would feel this results in a better user experience for our particular use case.

**Comment by KarlHawkins** [comment]
Id like the option to retain invalid input for the date picker, thanks

**Comment by bloodykheeng** [comment]
try this ive noted prime react uses UTC so it includes a time zone and mysql doesnt like that so u have to format before storing in database also format value for the calender to be in utc

see below how i handle submit

```
 const handleSubmit = async (data) => {
        // Format `start_date` and `end_date` to MySQL-compatible datetime
        if (data.start_date) {
            data.start_date = moment(data.start_date).format("YYYY-MM-DD HH:mm:ss");
        }
        if (data.end_date) {
            data.end_date = moment(data.end_date).format("YYYY-MM-DD HH:mm:ss");
        }
        setCreactMutationIsLoading(true);
        // event.preventDefault();
        console.log("data we are submitting : ", data);
        creactMutation.mutate(data);
    };

```



see below how i format the value the calendar component access

```
 <Field name="start_date">
                                {({ input, meta }) => (
                                    <div className="p-field m-4">
                                        <label htmlFor="start_date">Start Date</label>
                                        <Calendar
                                            id="start_date"
                                            {...input}
                                            value={
                                                input.value
                                                    ? moment.utc(input.value).toDate() // Converts to a UTC Date object
                                                    : null
                                            }
                                            showIcon
                                            dateFormat="dd/mm/yy"
                                            showButtonBar
                                            className={classNames({ "p-invalid": meta.error && meta.touched })}
                                        />
                                        {meta.error && meta.touched && <small className="p-error">{meta.error}</small>}
                                    </div>
                                )}
                            </Field>

```
