### ISSUE TITLE
Tick in Checkbox is displaced

### ISSUE THREAD

**Issue by ova2** [primefaces/primeng#334]
Checkbox in Chrome looks not good. Tick is displaced. See the screenshot.

![checkbox-primeng-chrome](https://cloud.githubusercontent.com/assets/767334/15178868/accd0be4-1778-11e6-861c-019764b63ac3.png)

**Comment by cagataycivici** [comment]
I don't see this at;

http://www.primefaces.org/primeng/#/checkbox

**Comment by ova2** [comment]
Strange. I can see this. I use Windows 8.1 and Chrome 50.0.2661.94. Zooming 100% (standard). Other browsers seem to be ok. It seems to be a browser bug. Don't know.

**Comment by cagataycivici** [comment]
I'll check with my colleagues. @mertsincan @Mrtcndkn @onursenture Can you guys test this in your environments, Mert uses windows so let's see.

**Comment by mertsincan** [comment]
Hi Oleg,
I didn't see this bug. I use Windows8.1 and Chrome 50.0.2661.102. I think it is a browser bug. Can you please try this issue with Chrome 50.0.2661.102?

My screenshot;
![checkbox](https://cloud.githubusercontent.com/assets/11868120/15349354/d6445a06-1cda-11e6-8690-c91c01f30d5e.PNG)

**Comment by onursenture** [comment]
Chrome Version 50.0.2661.102 (64-bit), OS X El Capitan 10.11.4 
<img width="663" alt="screenshot 2016-05-18 13 42 43" src="https://cloud.githubusercontent.com/assets/244957/15355948/73836d0c-1cfe-11e6-8df5-9c45a8bb00a7.png">

**Comment by ova2** [comment]
50.0.2661.102 renders the checkboxes correct. I will check today at home if the other version is correct and give your a feedback.

**Comment by ova2** [comment]
It was not the browser, it were my settings in Chrome. I had choose font size "Big" in Chrome. If I choose "Medium", it looks good.

You have in theme.css

`
.ui-widget .ui-widget {
    font-size: 1em;
}
`

If I remove this, everything looks good in any font resolution.
