### ISSUE TITLE
p-menu visible flag not working

### ISSUE THREAD

**Issue by jnewman30** [primefaces/primeng#3340]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/V2n8QJ4SAMPCysGR3oic?p=preview

**Current behavior**
If you set the visible flag to false it has no effect.

**Expected behavior**
I would expect the menu item would not render.

**Minimal reproduction of the problem with instructions**
1. Add the p-menu tag and point it to a set of items
2. Add two items and set the visible flag on one of them to false
3. When you run the app both items will be rendered

**What is the motivation / use case for changing the behavior?**
I have several pages using the same menu component. The parent of the pages also uses the component and I would like to disable the back button on the parent page.

* **Please tell us about your environment:**
  * os: win32 x64
  * npm: 5.1.0
  * node: 8.1.3
  * typescript: 2.4.1
  * **PrimeNG version:** 4.1.0-rc.3
  * **Angular version:** 4.2.6
    * angular/animations: 4.2.6
    * angular/common: 4.2.6
    * angular/compiler: 4.2.6
    * angular/core: 4.2.6
    * angular/forms: 4.2.6
    * angular/http: 4.2.6
    * angular/platform-browser: 4.2.6
    * angular/platform-browser-dynamic: 4.2.6
    * angular/router: 4.2.6
    * angular/cli: 1.2.0
    * angular/compiler-cli: 4.2.6
    * angular/language-service: 4.2.6

* **Browser:** 
  * Chrome: 59.0.3071.115 (Official Build) (64-bit)
  * Microsoft Edge: 40.15063.0.0

* **Language:** 
  * typescript: 4.4.1 / ES5

**Comment by jefftham** [comment]
this issue is tracked by #3072

**Comment by cagataycivici** [comment]
Duplicate

**Comment by jonnomk** [comment]
This is still an issue for the Steps component in PrimeNG v.11.4.0.   If I set visible to false, the item still renders.
