### ISSUE TITLE
asp-prerender /w primeng (need workaround?)

### ISSUE THREAD

**Issue by Ya-Wang** [primefaces/primeng#3341]
[X ] bug report 
[ ] feature request

Net Core backend w/ webpack 2.18.0 
* **Angular version:** 4.1.2
* **PrimeNG version:** 4.1.0-rc.3

Seems like I cannot use primeng because it uses Event. That isn't supported by asp-prerender, is there a workaround? I really want to use asp-prerender with my application as SEO is important. 

See below

![image](https://user-images.githubusercontent.com/3073708/28047455-221f1624-65b8-11e7-9da3-05dee023c4b6.png)

Thanks everyone!

**Comment by cagataycivici** [comment]
Please use forum for questions and support requests, thank you.
