### ISSUE TITLE
Unexpected 'ui-btn' label for icon only toggleButton control

### ISSUE THREAD

**Issue by silver-486** [primefaces/primeng#3347]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report 
```
**Plunkr Case (Bug Reports)**

http://plnkr.co/edit/wp9R54QTXWHToHJCHzqK?p=preview

**Current behavior**
**<p-toggleButton>** with empty string setup as **onLabel** and **offLabel** property looks as button with "**ui-btn**" label

**Expected behavior**
It's expected to be button without any labels

**Minimal reproduction of the problem with instructions**
Just add the following code on the page
`<p-toggleButton onLabel="" offLabel=""></p-toggleButton>`
http://plnkr.co/edit/wp9R54QTXWHToHJCHzqK?p=preview

**What is the motivation / use case for changing the behavior?**
This case is often used

**Please tell us about your environment:**
Win 10, Atom IDE, npm (5.0.3)

* **Angular version:** 2.0.X
Angular 4.1.0

* **PrimeNG version:** 2.0.X
"primeng": "4.1.0-rc.3"

* **Browser:** 
Chrome (the latest)
Firefox 55.0.b7
Opera 48
 
* **Language:** 
"typescript": "2.3.2"

* **Node (for AoT issues):**
 `node --version` =  v8.1.1

**Comment by cagataycivici** [comment]
You need to add onIcon and offIcon as well. Your current code has nothing.
