### ISSUE TITLE
Don't working autoResize without specify cols and rows

### ISSUE THREAD

**Issue by sergey-malykh** [primefaces/primeng#3349]
**I'm submitting a ...**  (check one with "x")
[ x ] bug report 

**Current behavior**
If I don't specify input cols and rows on <textarea>, autoResize don't working

**Expected behavior**
autoResize work like example from documentation.
> <textarea pInputTextarea autoResize="autoResize"></textarea>

like this [https://www.primefaces.org/primeng/#/inputtextarea](https://www.primefaces.org/primeng/#/inputtextarea)

**Minimal reproduction of the problem with instructions**
[http://plnkr.co/edit/jIiNBCelEDfOwuuBePoq?p=preview](http://plnkr.co/edit/jIiNBCelEDfOwuuBePoq?p=preview)

**What is the motivation / use case for changing the behavior?**

* **Angular version:** 4.0
* **PrimeNG version:** 4.0.0-rc.3
* **Browser:** Chrome 59
* **Language:** TypeScript 2.4

**Comment by cagataycivici** [comment]
Works better if you provide these values, will add to docs.
