### ISSUE TITLE
BloackableUI interface for Dropdown

### ISSUE THREAD

**Issue by Helayxa** [primefaces/primeng#3350]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
I can't set a Dropdown as a target of the BlockUI, because it doeesn't implement BlockableUI

**Expected behavior**
Dropdown should implement BlockableUI in order to set a Dropdown as a target of a BlockUI

**What is the motivation / use case for changing the behavior?**
My Dropdown is supplied by a backend service, so the data arrives asynchronously. I would like to display a loader with the BlockUI component in order to let the user know that there's a loading time before he could see the data in the Dropdown.

**Comment by cagataycivici** [comment]
Not sure, dropdown is too small to get blocked. Maybe you can set the placeholder as "Loading" before the data arrives, sounds better to me than blocking it. BlockableUI is mostly good for panel components.
