### ISSUE TITLE
Context Menu problems with Firefox

### ISSUE THREAD

**Issue by CyleClone** [primefaces/primeng#3353]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Trying to open a ContextMenu in Firefox results in the CM closing right after. Moving the mouse while holding right-mouse-button (to open the CM) resolves it.

**Expected behavior**
ContextMenu should stay active until user performs another action

**Browser:** [Firefox 54.0]

**Comment by cyberrranger** [comment]
for demo show
https://www.primefaces.org/primeng/#/contextmenu

**Comment by cagataycivici** [comment]
Fixed via PR
