### ISSUE TITLE
DataTable -  columns get misaligned when there are hidden columns  

### ISSUE THREAD

**Issue by amitgaikwad02bright** [primefaces/primeng#3356]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
updated with 4.1.0 final release
http://plnkr.co/edit/ShrMHPjd1YOrim043Iec?p=preview

**Current behavior**

 If some column is hidden, others columns get misaligned

**Expected behavior**

columns  should be aligned

**Minimal reproduction of the problem with instructions**

1. set dynamic columns configuration in template
 <p-column *ngFor="let col of columnDefs" [field]="col.field"
       [header]="col.header"
        [style]="{'width': col.width}" [hidden]="col.hidden"></p-column>
2. in column configuration, set column width , set some column as hidden
 columnDefs : [] = [
            {field: 'vin', header: 'Vin', width:'300px',hidden:true},
            {field: 'year', header: 'Year',width:'150px'},
            {field: 'brand', header: 'Brand',width:'200px'},
            {field: 'color', header: 'Color',width:'120px'}
        ];
  
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.2.0

issue seems with other version also

* **PrimeNG version:** 4.1.0- RC 3 , 4.1.0 final

issue is not present in 4.1.0 RC2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
ALL

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by deniskkk** [comment]
same here

**Comment by ctrl-brk** [comment]
For me they are misaligned even if I don't specify any width.

**Comment by amitgaikwad02bright** [comment]
done little analysis on datatable code base..
in ScrollableView component template 
```
<colgroup class="ui-datatable-scrollable-colgroup">
       <col *ngFor="let col of columns" [ngStyle]="col.style"/>
</colgroup>
```
its not considering col.hidden property.
adding [style.display]="col.hidden ? 'none' : 'table-column' " will resolve this

```
<colgroup class="ui-datatable-scrollable-colgroup">
          <col *ngFor="let col of columns" [ngStyle]="col.style" [style.display]="col.hidden ? 'none' : 'table-column'"/>
```
  </colgroup>

Not sure how to contribute to code :( (never been part of open source project contributions) ,  so pasting code here, so code contributors can use this to resolve issue.

**Comment by hle09** [comment]
The problem is that it's using "columns" instead of "dt.visibleColumns()":

Old codes in 4.0.1:
                    <colgroup class="ui-datatable-scrollable-colgroup">
                        <col *ngFor="let col of **dt.visibleColumns()**" />
                    </colgroup>

New codes in 4.1.0:
                    <colgroup class="ui-datatable-scrollable-colgroup">
                        <col *ngFor="let col of **columns**" [ngStyle]="col.style"/>
                    </colgroup>

**Comment by cagataycivici** [comment]
Tracked at #3471

**Comment by sahil1989** [comment]
@amitgaikwad02bright you are a superstar, your workaround just came in front of me at the right time, otherwise I would have burned hell lot of time in fixing this one. Thanks again for your workaround
