### ISSUE TITLE
Append sep={csvSeparator} to allow for seemless integration when the csvSeparator is not ',' for a datatable

### ISSUE THREAD

**Issue by kenisteward** [primefaces/primeng#3358]
```
[ X] bug report => Search github for a similar issue or PR before submitting
[ X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Currently when you export a csv and use the csv separator, it does not append sep={yourSeparator} in the file.  This causing issues with loading in excel because excel requires that you have that at the top so it knows how to separate the data.

**Expected behavior**
either simple sep={yourSeparator} is appended here 
https://github.com/primefaces/primeng/blob/41d29a59f308b7ea66b8bd136c9871ee7462e49a/src/app/components/datatable/datatable.ts#L2277-L2281

or allow a callback function that is beforeExport that happens right before the export happens that allows you to manipulate the raw data in the blob. 

**Minimal reproduction of the problem with instructions**
any datatable with exportCSV() functionality with the csvSeparator set to anything other than comma

**What is the motivation / use case for changing the behavior?**
The idea would be to allow commas in the content by changing the csvSeparator and still be compatible with csv parsers like excel.

@cagataycivici as stated above a simple change to the exportCSV() function would allow for almost seemless integration with CSV->excel.  just a 1 line change from

```

public exportCSV() {
   let data = this.filteredValue||this.value;
   let csv = '\ufeff';
...
}
```

to

```
public exportCSV() {
   let data = this.filteredValue||this.value;
   let csv = '\ufeff';
   csv += this.csvSeparator + '\r\n\'
...
```

I'd gladly make a PR if needed.

**Comment by kenisteward** [comment]
@cagataycivici any update on this or exports for excel.  I know it's on the roadmap but is there a particular version target?

**Comment by cagataycivici** [comment]
The change break it on my mac where I can't open the file with excel anymore.

**Comment by kenisteward** [comment]
I posted the wrong code.  It should be csv += 'sep' + this.csvSeperator +
'\r\n'

My apologies

**Comment by cagataycivici** [comment]
Thanks, will review again tomorrow.

**Comment by kenisteward** [comment]
As i saw you post today I noticed another missing character....

I should not have wrote it on my phone haha.

 It should be csv += 'sep=' + this.csvSeperator + '\r\n'

there needs to be an equals sign after the sep and before the separator and carriage return

**Comment by cagataycivici** [comment]
This is what I get with it;

![screen shot 2017-09-12 at 10 09 36](https://user-images.githubusercontent.com/686247/30312495-8ab08cf6-97a2-11e7-8f09-7996cc0a369f.png)

Please provide a proper PR.

**Comment by kenisteward** [comment]
@cagataycivici #3921 pull request
