### ISSUE TITLE
Update Dialog position when positionLeft or positionTop is changed

### ISSUE THREAD

**Issue by MarkRyanDev** [primefaces/primeng#3359]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

http://plnkr.co/edit/jVUv1euMIHMRmhe5bUEF?p=preview

**Current behavior**

When positionLeft and positionTop are changed, the dialog does not move. It will update its position properly if you toggle it on and off.

**Expected behavior**

The dialog should move as positionLeft and positionTop are changed.

**Minimal reproduction of the problem with instructions**

see plunkr, use the buttons to move it around
note that its position is not updated until it is toggled off and on

**What is the motivation / use case for changing the behavior?**

I am trying to dynamically move a dialog around when the window is resized and it won't move properly.

**Please tell us about your environment:**

MacOS, IntelliJ, Tomcat

* **Angular version:** 4.1.2

* **PrimeNG version:** 4.0.1

* **Browser:** Chrome 59

 
* **Language:** TypeScript 2.3.2

**Comment by dkrysiak** [comment]
My dirty fix for the problem:

component.html:
```html
<p-dialog #dialog>
```

component.ts:
```typescript
@ViewChild('dialog', { read: ElementRef })  
protected dialogElement: ElementRef;
```

and later, in appropriate method:
```typescript
this.dialogElement.nativeElement.children[0].style.top = positionTop + 'px';
```

Seems like the generic solution for the problem directly in PrimeNG should be pretty simple too.

**Comment by lasimone** [comment]
I was able to call:

@ViewChild("dialog") dialog: Dialog;
this.dialog!.positionOverlay();

to get it to work.

**Comment by yigitfindikli** [comment]
positionTop and positionLeft properties deprecated with new Dialog implementation. You can use style instead.
