### ISSUE TITLE
Offsets for Grid CSS

### ISSUE THREAD

**Issue by paulswan** [primefaces/primeng#3362]
**I'm submitting a ...**  
```
[ ] bug report
[x] feature request 
[ ] support request
```

**Expected behavior**
Similar to Bootstrap Offsetting columns:
[http://getbootstrap.com/css/#grid-offsetting](url)

**What is the motivation / use case for changing the behavior?**
It would be nice to have left and right aligned buttons on large screens without a big gap between them on a smaller screen.

**Comment by MuratcanKatirci** [comment]
Dear @paulswan 
Did you look at PrimeNG's awesome grid CSS which includes vital features as nested or responsive positioning?
https://www.primefaces.org/primeng/#/grid

**Comment by ctrl-brk** [comment]
Do you have a DataTable plunker I can start from?
