### ISSUE TITLE
Dynamic frozen columns in Datatable

### ISSUE THREAD

**Issue by HoganHu0520** [primefaces/primeng#3364]
LIke #2237 .

**Plunkr Case (Bug Reports)**

http://plnkr.co/edit/PCqOtWWNE5yXgGiJhW5X?p=preview

**Current behavior**
Can not change frozen columns after initialize datatable.

**Expected behavior**
Dynamic choose frozen columns.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.3.X

* **PrimeNG version:** 4.1.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by pavithrancr** [comment]
Thanks for fixing this Hogan. 
When can a build be expected with this fix?

**Comment by cagataycivici** [comment]
Tracked at 3345

**Comment by felipebri23** [comment]
I have the same issue

Angular version: 5.0.0
PrimeNG version: 5.0.0
Browser: [Chrome 56 | Firefox 45.0.1 ]
Language: [all | TypeScript 2.0 | ES6/7 | ES5]
