### ISSUE TITLE
Datatable renders badly after upgrade to 4.1.0-rc.3

### ISSUE THREAD

**Issue by unaor** [primefaces/primeng#3366]
I noticed my datatable is now renders badly
reverting to version 4.0.0-rc.3 fixes the issue

here is the relevant table code

`<p-dataTable #dt [value]="alerts" [rows]="25" [paginator]="true" (onFilter)="updateTotal()"
 [scrollable]="true" scrollHeight="500px" [rowStyleClass]="addPopup" (onRowClick)="emitShowDialogEvent($event.data)">`

**Comment by cagataycivici** [comment]
Provide a plunkr please;

http://plnkr.co/edit/Qi2Nw2imLpDUF8NJinYw?p=preview
