### ISSUE TITLE
DataTable - Add filter to column when using column toggler

### ISSUE THREAD

**Issue by randomgithubdev** [primefaces/primeng#3368]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**

When using column toggler of DataTable, it is not possible to add a filter to a specific column. only filters to all columns are enabled.

**Expected behavior**

Using column toggler together with column filter of DataTable should provide the option to define a filter to a specific column.

* **Angular version:** 4.0.X

* **PrimeNG version:** 4.0.0-rc.3

**Comment by cagataycivici** [comment]
Not sure why column toggler requires a filter, we'll reconsider if there is more demand.

**Comment by randomgithubdev** [comment]
Filter to a specific column in DataTable (not filter to column toggler)

**Comment by eranflom** [comment]
I am not sure the request is completely clear...
When using the object datatable, you can use the following two attributes: coltoggler and filter.
When you use only the filter attribute (without using coltoggler) - you can add a filter to each column separately.
Somehow when you choose to use the coltoggler attribute - the filter attribute can not be used on a specific column - but only one filter for the entire table.

This makes no sense. Why is there a relation between adding the coltoggler 

So we don't think that "column toggler requires a filter" - it just that using it interfere with the filters that were set on specific columns. Why?
