### ISSUE TITLE
Allow to disable a single row selection on DataTable

### ISSUE THREAD

**Issue by parisgianluca** [primefaces/primeng#3369]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
In a DataTable with selection, it is not possible to disable a single checkbox in a row based on a condition

**Expected behavior**
Allow to disable a single row selection based on a condition (disableSelection)

**Comment by LsKLele** [comment]
+1 on this request, this would be very useful.
Thank you

**Comment by steigerm** [comment]
Another +1.
I am currently looking for something like this. Although in my case I have a multiple selection datatable where I need to display a number of rows but also need to disable selection for some of them.

**Comment by sryara** [comment]
I have implemented this using templating in primeng . Here is my repo https://github.com/sryara/primeng-webpack-datatable-checkbox

**Comment by rich4756** [comment]
This seems to be a duplicate of https://github.com/primefaces/primeng/issues/1681

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
