### ISSUE TITLE
Add life property to Tooltip

### ISSUE THREAD

**Issue by saximoer3** [primefaces/primeng#3370]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Expected behavior**
i need a property to hide the tooltip in milliseconds by setTimeout.
i think some people need it too.

like this:
@Input() life: number;

ngAfterViewInit(): void {
      if( this.life ){
              setTimeout(() => {  this.deactivate() }, this.life);
      }
}

**Comment by aervin** [comment]
Same as my feature request in [#3516](https://github.com/primefaces/primeng/issues/3516)
