### ISSUE TITLE
Triggers onRowClick() method when you select a row in DataTable

### ISSUE THREAD

**Issue by EugeneBugor** [primefaces/primeng#3374]
**Plunker Case:**
http://plnkr.co/edit/QHCwqeKuX2dwvPLNUMzG?p=preview

**Issue Description:**
When you tap on a row's checkbox to invoke onRowSelect() method, onRowClick() method invokes too in component DataTable.

**Issue Details:**
This behavior occurred with primeng v4.1.0-rc.3. In the previous version of primeng a described problem doesn't exist.

**Environment Details:**
Angular: 4.X
PrimeNG: v4.1.0-rc.3;
Browsers: all

**Comment by cagataycivici** [comment]
That is expected, onRowClick is always triggered even there is no selection.
