### ISSUE TITLE
X button in input using IE does not clear value in autoComplete component

### ISSUE THREAD

**Issue by wsz34** [primefaces/primeng#3375]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Visible in documentation https://www.primefaces.org/primeng/#/autocomplete

**Current behavior**
Using IE browser after click on X button in autoComplete input does not clear selected value

**Expected behavior**
X button behavior should be the same as using keyword backspace or delete buttons. After deleting text from input, selected object variable should be set to null

**Minimal reproduction of the problem with instructions**
Open https://www.primefaces.org/primeng/#/autocomplete with Internet Explorer 11
Start typing any country (for example, Australia)
Select any country
Click on "X" icon/button on the right side of the input
Notice that on the right text is still "Country: Australia", should be "Country: none"

* **Angular version:** 4.1.3

* **PrimeNG version:** 4.1.0-rc3

* **Browser:** IE 11

**Comment by MuratcanKatirci** [comment]
In IE version 11.0.25, X button works fine and clears the value when it is clicked on.

**Comment by wsz34** [comment]
I'm using 11.0.43 and it does not work as expected

**Comment by jevgenimarenkov** [comment]
The problem exists in PrimeNG 5.2.

**Comment by yigitfindikli** [comment]
IE support is deprecated.
