### ISSUE TITLE
PrimeNg OnRowUnselect doesnt fire

### ISSUE THREAD

**Issue by Mounika30** [primefaces/primeng#3378]
I am using Data table selection mode as multiple and when I use both onRowSelect and onRowUnselect events, onRowUnselect event doesnt fire.

https://plnkr.co/edit/usl6ovHePa5c1QWayGag

**Comment by anirudh-jagithyala** [comment]
your plunkr code uses wrong event name to call deselect "(onRowUnSelect)="rowDeselected($event)""

Use the event "onRowUnselect" and not "onRowUnSelect".
The event names are case sensitive.

**Comment by Mrtcndkn** [comment]
Yes, @anirudh-jagithyala  is right.
