### ISSUE TITLE
Footer for Listbox and Add Fixed Header

### ISSUE THREAD

**Issue by dhniels** [primefaces/primeng#3379]
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap

it would be nice to have an option to enable a footer/buttons, similar to p-dialog in list box. See screenshot of an example i built:

![screen shot 2017-07-12 at 12 58 13 pm](https://user-images.githubusercontent.com/7034022/28134925-ce0e9e9c-6701-11e7-9cca-386d814620d2.png)

another feature i would like to see as well is when you set the search filter on listbox and you have listbox set to have a max-height, the search filter scrolls _with_ the content (see gif below). it should remain fixed at the top, or have an optional setting to allow that. 

![jul-12-2017 13-01-32](https://user-images.githubusercontent.com/7034022/28135099-578daad2-6702-11e7-8f02-e6ba5ff83e6e.gif)

**Comment by cagataycivici** [comment]
Is this multiSelect or listbox? My screenshot from MultiSelect has scrollable content with fixed header.
<img width="215" alt="screen shot 2017-08-25 at 10 53 07" src="https://user-images.githubusercontent.com/686247/29704720-ae057540-8983-11e7-9f8e-c7087b7404d8.png">

**Comment by dhniels** [comment]
Well, in my particular circumstance I chose ListBox because I wanted the panel only, I didn't want to attach it to an the input field like multi select. I see that they are almost identical. However the listbox header isn't fixed like the multi select is.

**Comment by cagataycivici** [comment]
Yes, I've also seen that when porting Listbox to PrimeReact and fix it there so we should do the same here. Will add a template for footer part as well.
