### ISSUE TITLE
Tree add loading status

### ISSUE THREAD

**Issue by easyping** [primefaces/primeng#3381]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Add the loading status, as with DataTable

**Expected behavior**
Thus, e.g. at load lazzing, the user will be notified that the data is being loaded.

**Comment by SefaMuratcanKatirci** [comment]
Hello,
Actually, tree table has lazy loading property. Didn't it satisfy your project? Could you please explain your request more?

**Comment by easyping** [comment]
Hello,
right, there is the lazy loading facility, but it should also be possible to display the loading icon as with DataTable when loading longer the data.

Furthermore, I would also use this loading icon, to show users, that insert a new node take a while, because there are loading, before the node is inserted.

It is mainly about showing the user that the current triggered action is still working.
At DataTable it is beautifully solved, with the attributes loading.
