### ISSUE TITLE
Cannot add more than one class in multiselect control

### ISSUE THREAD

**Issue by pantonis** [primefaces/primeng#3383]
In multiselect control I cannot add more than one class in styleClass attribute

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Please tell us about your environment:**
Windows 10 

* **Angular version:** 4.2.5

* **PrimeNG version:** 4.0.2
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5] Typescript 2.3

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview
