### ISSUE TITLE
Filtering by notEquals raises "TypeError: Cannot read property 'equals' of undefined"

### ISSUE THREAD

**Issue by alex-dev** [primefaces/primeng#3388]
[x ] bug report
[ ] feature request
[ ] support request

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/ko1TUjDqwi98UtnMx7Tt

**Current behavior**
It is impossible to filter with filterMatchMode set to notEquals. Trying just raise an error due to trying to access equals of an undefined this.

**Expected behavior**
Filter the data table and show only rows not matching the value.

**Minimal reproduction of the problem with instructions**
Choose a value from the dropdown and look at the console.

* **Angular version:** 4.1.3

* **PrimeNG version:** 4.1.0

**Comment by alex-dev** [comment]
Just made a PR fixing the problem in the simplest way I could find.
[#3389](https://github.com/primefaces/primeng/pull/3389)

**Comment by ctrl-brk** [comment]
From the docs: `Default match mode is "startsWith" and this can be configured using filterMatchMode property of column object that also accepts "contains", "endsWith", "equals" and "in"`
So, strongly speaking it's not a bug.

**Comment by alex-dev** [comment]
"[Defines filterMatchMode; "startsWith", "contains", "endsWidth", "equals", "notEquals" and "in".](https://www.primefaces.org/primeng/#/datatable)"

And by me, a functionality in the code, not marked anywhere as non-functional, should work.
