### ISSUE TITLE
[bug report] <p-growl> doesn't dismiss automatically due to the Unexpected token error

### ISSUE THREAD

**Issue by bluegray1015** [primefaces/primeng#3391]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

[p-growl] message doesn't dismiss automatically. We only can close it manually.

**Expected behavior**

The <p-growl> message should dismiss in 3 seconds for the default setting.

**Minimal reproduction of the problem with instructions**

Because growl doesn't dismiss automatically, in order to trace this issue, I copied the source code (https://github.com/primefaces/primeng/blob/master/src/app/components/growl/growl.ts) into my local machine and ran it in debug mode, then I got the Unexpected token error in this section
```
ngDoCheck() {
    if (!this.immutable && this.container) {
      let changes = this.differ.diff(this.value);
      if (changes) {
        this.handleValueChange();
      }
    }
  }
```
<a href="https://www.flickr.com/gp/bluegray_he/S2t8te" title="primeng_growl_error1"><img src="https://farm5.staticflickr.com/4262/35863850236_3104fcb295_z.jpg" width="640" height="81" alt="primeng_growl_error1"></a>

It indicated the error which occurred in 
`webpack-internal:///.src/app/shared/growl.component.ts:39:9`. 
So I checked it, which is as below:

<a href="https://www.flickr.com/gp/bluegray_he/st58zb" title="primeng_growl_error2"><img src="https://farm5.staticflickr.com/4317/35863850016_13efdb74fd.jpg" width="421" height="183" alt="primeng_growl_error2"></a>

If I remove `if (!this.immutable && this.container) {`, growl message will work properly. However, when I run the e2e test using the protractor, I encounter timeout issue. (https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular)

**What is the motivation / use case for changing the behavior?**

If growl message doesn't dismiss automatically, users have to close every message one by one manually, it's not good for user experience.

**Please tell us about your environment:**

Operating system: MacOSX 10.12.5
IDE: IntelliJ IDEA Ultimate

* **Angular version:** Both of 4.2.3 and 4.2.6 have the same issue.

* **PrimeNG version:** Both of 4.1.0-rc.3 and 4.1.0 have the same issue.

* **Browser:** [Chrome Version 59.0.3071.115 (Official Build) (64-bit) ]

 
* **Language:** [TypeScript 2.4.1]

* **Node (for AoT issues):** `node --version` =   8.1.4

**Comment by MuratcanKatirci** [comment]
Hello,
I had the same issue with you. Then, I have realized that we should bind immutable  with brackets.
Here you can see the related part : 

`<p-growl [immutable] ="false" life ="1000" [(value)]="msgs"></p-growl>`
msgs is a Message object that you can examine in [PrimeNG-growl](https://www.primefaces.org/primeng/#/growl) page.

Finally, dismissing worked fine in my project. Could you please share your related html code ?

**Comment by bluegray1015** [comment]
hi, immutable has a default value, so in theory, you don't need to bind immutable object with brackets. In other words, this Unexpected token error shouldn't happen.

Anyway, when I bind this immutable object like this
`<p-growl [(value)]="growlService.messages" [life]="10000" [immutable] ="false"></p-growl>`

It's working properly now. Very appreciate your suggestion. :)

**Comment by bluegray1015** [comment]
When I put [immutable] ="false" in HTML, it occurs `ScriptTimeoutError in Protractor just like I removed this line `if (!this.immutable && this.container) {`.  The error message is `Timed out waiting for asynchronous Angular tasks to finish after 11 seconds. This may be because the current page is not an Angular application. Please see the FAQ for more details: https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular
While waiting for element with locator - Locator: by.buttonText("Upload")`.

Hope someone has any idea about this.

**Comment by SefaMuratcanKatirci** [comment]
Hi again,
Sorry, but I don't understand. Did it work or not?

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a plunkr;

http://plnkr.co/edit/Qi2Nw2imLpDUF8NJinYw?p=preview
