### ISSUE TITLE
Tooltip set "null" at the begining of the word (IE11)

### ISSUE THREAD

**Issue by Danieleeee** [primefaces/primeng#3393]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

![1](https://user-images.githubusercontent.com/22749175/28213729-a5aaa5c0-68a7-11e7-99eb-2b7a64136d47.png)

This is the code:
`pTooltip="Data elaborazione di riferimento" tooltipPosition="top"`

**Please tell us about your environment:**

Windows 7, IE11

* **Angular version:** 4.2.6

* **PrimeNG version:** 4.1.0

* **Browser:** IE 7

**Comment by Danieleeee** [comment]
We have slow performance respect 4.0.3

**Comment by MuratcanKatirci** [comment]
Hello,
Could you please share more of your code?  You can upload it to[ plunkr ](http://plnkr.co/edit/?p=catalogue)and provide us its link.

**Comment by Danieleeee** [comment]
If you use tooltip in IE11 you will see that this is the behavior.
The code used is the same as version of PrimeNG 4.0.3

**Comment by jgill248** [comment]
I have the same behavior in any use of tooltip in IE 11.
`<div class="pull-right" pTooltip="some text" tooltipPosition="left">`

![image](https://user-images.githubusercontent.com/8699876/28383474-425617c0-6c8f-11e7-9632-077f3395245d.png)

using "primeng": "4.1.0",

**Comment by BearInHat** [comment]
This is the same in Edge as well.  When this.tooltipText.innerHTML = null; (line 126) is hit, the Microsoft behaviour is to set the innerHTML/innerText to "null", then the next line appends the tool tip text to that.  Our current work around is setting [escape]="false".

**Comment by Suncrusher** [comment]
I do have the same Problem wie IE 11 and Edge on Win 10. 

I can reproduce this also on the sample page: https://www.primefaces.org/primeng/#/tooltip
