### ISSUE TITLE
The p-calendar shows  NaN when changing showTime at runtime

### ISSUE THREAD

**Issue by epaitz** [primefaces/primeng#3396]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When showTime is set to false by default, and then showTime is changed to true at runtime, there is no time value shown and clicking the up/down arrows will cause several NaN values to appear.

**Expected behavior**
Defaulting showTime to false and then changing showTime to true at runtime should not show NaN values and display a correct date/time value. 

**Minimal reproduction of the problem with instructions**
See the following Plunkr fork that tires to demonstrate the bug report. 
http://plnkr.co/edit/bDkR7iyMyXfyX6PG3wJ5?p=preview

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.2.6

* **PrimeNG version:** 4.1.0

* **Browser:** [Chrome 54 | Firefox 52 | IE 11]

 
* **Language:** [TypeScript X.X | ES5]

**Comment by MuratcanKatirci** [comment]
In p-calendar tag, you should provide a **[(ngModel)] = "value(date variable)"**  which holds the date value and displays it when showTime is **true**. In your situation, you are allowing and forbidding displayin showTime while there is no date value in your component.

Please have a look at : https://www.primefaces.org/primeng/#/calendar

**Comment by epaitz** [comment]
Thank you very much for the reply. I have altered the plunker as you have suggested to include a date1 and date2 values that are bound to the calendar controls using [(ngModel)] but the second calendar control still shows NaN values if I check the showTime checkbox and click the up/down arrows to change the time. Please let me know if I am missing something or if there is anything else I can do to prevent this behavior. Thanks.

**Comment by SefaMuratcanKatirci** [comment]
I think you should try to use ngModel in  p-calendar tag. It's being empty can cause some NaN values(which can be a boolean value ).

**Comment by epaitz** [comment]
I'm sorry but I do not understand your last comment. I have already altered the plunker link to include [(ngModel)] in the p-calendar tag and it still behaves the same way and displays NaN values. 

`<p-calendar [(ngModel)]="date2" showIcon="true" [showTime]="showTime2" [timeOnly="timeOnly2"></p-calendar>`

Can you please take a look at the Plunker link? Please let me know how I can fix this NaN display behavior.

**Comment by cagataycivici** [comment]
Replicated.
