### ISSUE TITLE
Structural CSS not showing up in docs

### ISSUE THREAD

**Issue by kc13greiner** [primefaces/primeng#3397]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
The https://www.primefaces.org/primeng/#/theming page section on structural CSS classes is blank

**Expected behavior**
I would expect a list of the structural CSS classed provided with PrimeNG

**Minimal reproduction of the problem with instructions**
Go to https://www.primefaces.org/primeng/#/theming and look at the Structural CSS section

**What is the motivation / use case for changing the behavior?**
I want to see the classes listed with a description so I can better learn how to use PrimeNG

**Comment by MuratcanKatirci** [comment]
Actually, if you opened PrimeNG in your IDE(like ATOM) as a project, you can see the CSS classes  in those paths : 

` 'assets/showcase/css/primeng.css';
 'assets/showcase/css/code.css';
 'assets/showcase/css/site.css';`

Displaying all classes in theming page would be so messy in terms of the crowd of the classes.
If you would like to learn how to use PrimeNG, try to use components (datatable, button , contextmenu etc.). You don't need to study on CSS classes at the beginning. Try to do a simple app such as Todo List with PrimeNG components.

**Comment by MuratcanKatirci** [comment]
If you insist on examining the CSS classes you can found them here:

https://github.com/primefaces/primeng/tree/master/src/assets/showcase/css

**Comment by kc13greiner** [comment]
@SefaMuratcanKatirci I appreciate the response. However, if you look at the docs page I linked you will see that the section is incorrectly blank. While the other sections are populated

**Comment by SefaMuratcanKatirci** [comment]
Dear kc13greiner,
I got what you meant but it makes the page so messy that sharing styles of all components. Instead, their all style documentation can be found at bottom of the related component's page.
Finally, the section you have informed us about is intentionally left blank.
Thanks

**Comment by cagataycivici** [comment]
Added docs to clear this up.
