### ISSUE TITLE
"yarn clean" breaks primeng

### ISSUE THREAD

**Issue by Mario-Eis** [primefaces/primeng#3398]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

Project builds fine before "yarn clean". Afterwards, OR if there is a .yarnclean file present, there will be the following error:

```
    ERROR in ./node_modules/css-loader?sourceMap!./node_modules/primeui/themes/omega/theme.css
    Module not found: Error: Can't resolve './images/slider_handles.png' in 'C:\Users\Mario\Documents\projects\rauch\tool-configurator\node_modules\primeui\themes\omega'
     @ ./node_modules/css-loader?sourceMap!./node_modules/primeui/themes/omega/theme.css 6:22381-22419
     @ ./node_modules/css-loader?sourceMap!./node_modules/sass-loader/lib/loader.js?sourceMap!./src/styles/global.scss
```

**Expected behavior**

Project should be able to build after "yarn clean".

**Minimal reproduction of the problem with instructions**

NPM Project with PrimeNg as a dependency. yarn --> yarn clean --> dist

**What is the motivation / use case for changing the behavior?**

Support "yarn clean"

**Please tell us about your environment:**

Windows 10, IntelliJ IDEA, NPM

* **Angular version:** 4.3.0
* **PrimeNG version:** 4.1.0
* **Language:** TypeScript 2.4.1
* **Node (for AoT issues):** `node --version` =  v8.1.1

**Comment by cagataycivici** [comment]
Provide a PR please for yarn support, we support npm right now.
