### ISSUE TITLE
Datatable : onLazyLoad event fire twice when "first" property is different from 0

### ISSUE THREAD

**Issue by loic49** [primefaces/primeng#3399]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

When I defined "first" property to a value different from 0, onLazyLoad event is fired twice. Indeed, event is fired on ngOnInit and on the set of "first" property when value is différent from 0.

**Expected behavior**

Event onLazyLoad should fire once even if "first", "order", "filter" properties are initialized with a value different from defaults.

**Please tell us about your environment:**

* **Angular version:** 4.2.6

* **PrimeNG version:** 4.1.0

* **Browser:** Chrome

**Comment by cagataycivici** [comment]
Replicated.
