### ISSUE TITLE
Datatable Change Detection Broken. it was working fine on v2.0.6

### ISSUE THREAD

**Issue by jefftham** [primefaces/primeng#3406]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Bug on v4.1.0:
http://plnkr.co/edit/6Ftd5aBV8PhXTKVqXyed?p=preview

Working on v2.0.6
http://plnkr.co/edit/JKsgeuRHcj3TXM3SDI11?p=preview

**Current behavior**

DataTable render value from an array. The datatable is not re-render when the value change. 
FYI, v2.0.6 is working fine.

**Expected behavior**

Datatable is expected to update/refresh when its value change.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

It is a basic feature of datatable. it should be backward-compatible.

**Please tell us about your environment:**

Windows 10, node, npm, typescript, ...

* **Angular version:** 4.2.6

* **PrimeNG version:** 4.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   8.1.4

**Comment by brachi-wernick** [comment]
I fixed your plnkr in a for : http://plnkr.co/edit/1EDQ8FxXaqPOx0OhChOr?p=preview
you just need to add `[immutable]=false`

**Comment by jefftham** [comment]
Great!! Thanks @brachi-wernick, i just saw the newly added document about "Change Detection".

@cagataycivici, i think the better design is to set `immutable = false` to provide backward compatibility.
