### ISSUE TITLE
ng-template in p-multiselect

### ISSUE THREAD

**Issue by akashshelke22** [primefaces/primeng#3412]
**Is there any option to add ng-template in p-multiselect or HTML in multiselect dropdown label**

 
 
 
 
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Angular version:** 4.0.1

* **PrimeNG version:** 4.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [TypeScript 2.2.2]

**Comment by cagataycivici** [comment]
Duplicate -> #2165
