### ISSUE TITLE
p-dropdown, unable to display data which is in a different format like ({id: ' ' , name: ' ').

### ISSUE THREAD

**Issue by MSAJJAN-EEOC** [primefaces/primeng#3416]
**I'm submitting a feature request**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[* ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

currently in p-dropdown we can only bind data which is an array of items in ({label:' ', value:' '})  format. it would be very helpful if we can pass array of items in a different format like ({id: ' ' , name: ' ') , ({id: ' ' , code: ' ').

**Comment by cagataycivici** [comment]
You need to give the object as the value.

**Comment by MSAJJAN-EEOC** [comment]
could you please give a working example . when i give object as the options its showing blank options. 
I also tried using <ng-template> but coudn't make it work. It would be helpful if its explained in the documentation.
