### ISSUE TITLE
Virtual Scroll Data Table doesn't work at all in IE or Edge

### ISSUE THREAD

**Issue by wooleverj** [primefaces/primeng#3418]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/ZPYbjWMTdnNTGlrMMmhY?p=preview

https://www.primefaces.org/primeng/#/datatable/scroll

**Current behavior**
Virtual Scroll table does not work with IE or Edge.

**Expected behavior**
It is expected that virtual scrolling table should work with at least IE 11 and Edge

**Minimal reproduction of the problem with instructions**
open plunker or primeNG example in IE 11 or Edge and see the table does not display.

**What is the motivation / use case for changing the behavior?**
Our App needs to be compatible with at least IE 11 and Edge

**Please tell us about your environment:**

* **Angular version:** 2.0.X
Angular 4 +

* **PrimeNG version:** 2.0.X
PrimeNG 4.1.0

* **Browser:** [ IE 11 | Edge ]

 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Browsers have a limit on maximum height due to this restriction, issues like this may occur. At showcase, we'll reduce the total rows to around 300K to make sure it runs on IE.
