### ISSUE TITLE
Calendar clicking on button icon not opening calendar IE9/IE10 with primeng 2.X as well.

### ISSUE THREAD

**Issue by ankati** [primefaces/primeng#3420]
Hello,

I saw this issue was fixed 4.X, but not in 2.X.
Can we have this fix in 2.X as well since I am not thinking to upgrade 4.X.
https://github.com/primefaces/primeng/issues/2213

Current behavior

When using calendar with showIcon and clicking on the icon, then the calendar does not open. Clicking on the input still works. Works on Chrome, but not on IE9/IE10.

Angular version: 2.0.X
2.4.9

PrimeNG version: 2.0.X
2.0.1

Reason for not being upgraded is:
When I am trying to upgrade I see some other issues like compatibility of angular version, looks like its expecting angular 4.X, due to this reason we are planning to continue with primeng 2.X itself.

Thanks.

**Comment by ankati** [comment]
Its not in primeng 2.X

**Comment by cagataycivici** [comment]
PrimeNG 2.x is only supported for PRO users, you need to upgrade.
