### ISSUE TITLE
Root label and content data not changing - in dynamic orgchart

### ISSUE THREAD

**Issue by alrahmanak** [primefaces/primeng#3425]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/Qi2Nw2imLpDUF8NJinYw?p=preview

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by arqcon** [comment]
I using org chart and building the model dynamically on every request. All children nodes of organization chart gets updated for every request, but not the root element

**Comment by AliNaffaa** [comment]
Here is workaround:
1. clear data
2. call method with new Promise
this.ivrData = [];
private waitAndSetData(event) {
       new Promise(resolve => {setTimeout(resolve, 1)}).then(() => {
            this.ivrData = this.ivrMap.get(event.data.key);
            this.ivrData = [...this.ivrData];
       });
    }

**Comment by neel015** [comment]
Is this fixed? I am using primeng 4.3.0 and am facing the same issue

**Comment by neel015** [comment]
> Here is workaround:
> 
> 1. clear data
> 2. call method with new Promise
>    this.ivrData = [];
>    private waitAndSetData(event) {
>    new Promise(resolve => {setTimeout(resolve, 1)}).then(() => {
>    this.ivrData = this.ivrMap.get(event.data.key);
>    this.ivrData = [...this.ivrData];
>    });
>    }

Can you show more details on this?

**Comment by yigitfindikli** [comment]
This is related to Change Detection, you need to trigger it. You can use the spread operator or clear the array and fill it up again.
