### ISSUE TITLE
There is a extra horizantal line line in the footer section of dialog form

### ISSUE THREAD

**Issue by alialtun14** [primefaces/primeng#3426]
[x ] bug report

Current behavior

1) There is a extra horizantal line line in the footer section of dialog form. 
2) Additionally the height of footer is lager (2x16px) than expected .
 
The related  code part
`	<p-footer>
		<div class="ui-dialog-buttonpane ui-helper-clearfix">
		</div>
	</p-footer>
`

Angular version: 4.3.0
PrimeNG version: 4.1.0
Ultima version: 4.0.2
Chrome Version 60.0.3112.66
Windows 10 64 bit

![footer](https://user-images.githubusercontent.com/782196/28313707-289e47ee-6bb8-11e7-8ea5-4704a80095c4.png)

**Comment by cagataycivici** [comment]
Remove <div class="ui-dialog-buttonpane ui-helper-clearfix"> </div>

**Comment by sbley** [comment]
> Remove

Hi @cagataycivici, what do you mean by your comment? Has this been resolved?

**Comment by TakanashiOuken** [comment]
Same here. ui-dialog-footer causing problems

**Comment by adama357** [comment]
It looks like this has maybe been fixed.  In the documentation, it now just has you putting content directly in a <p-footer> tag, without any inner div with classes.  When I removed the inner div from my code, it now looks how it should.
