### ISSUE TITLE
[DataTable] OnRowSelect does not work well with checkbox column

### ISSUE THREAD

**Issue by StevenLiekens** [primefaces/primeng#3427]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/oVkoz5?p=preview

**Current behavior**

The checkbox in the header row does not trigger `onRowSelect` or `onRowDeselect`

**Expected behavior**

The header row should trigger `onRowSelect` and `onRowDeselect` for all affected rows.

**Minimal reproduction of the problem with instructions**

See Plunkr. Check the boxes and observe what happens.

* **Angular version:** 4+

* **PrimeNG version:**  4.1.0

**Comment by Ketec** [comment]
That looks normal - because you did not select individual row.
There is a separate event "onHeaderCheckboxToggle" for header.

**Comment by StevenLiekens** [comment]
Okay so can I use onHeaderCheckboxToggle to know which rows were affected? Where is the documentation?

**Comment by Ketec** [comment]
It unfortunately does not return affected rows. Perhaps selectionChange would work better in this case - you get a list of selected items and both rows/header fire it.

**Comment by StevenLiekens** [comment]
That gives me all the selected rows without telling me which ones were added or removed.

**Comment by StevenLiekens** [comment]
I honestly don't know if this is a bug or a feature request. I marked this as a bug because the name `onRowSelect` says nothing about how the row was selected.

**Comment by Ketec** [comment]
Firing large number of onRowSelects there would be bad for performance (in my case that would be up to 30 thousand events in some cases). 
Global select would return an array most likely even if they add something new, which would not help you much. This is where data stores become useful to store states etc (like ngrx).

**Comment by StevenLiekens** [comment]
Okay then I propose that `onRowSelect` and `onRowDeselect` should be triggered once per click of the header checkbox. The `data` property of the event object should be an array of `dataKey` of the affected rows.  
If no `dataKey` is specified then use the entire row object instead, or just don't raise the event at all.

**Comment by priyaponni** [comment]
Hi, Is anyone working on this item? We also need an even for the header checkbox check/uncheck hooks. Thanks!

**Comment by cagataycivici** [comment]
There is onHeaderCheckboxToggle that passes the state as $event.checked. Should be in docs as well.

**Comment by StevenLiekens** [comment]
@cagataycivici how can we use that to create a transaction log of which rows were affected by clicking the header checkbox?

**Comment by arjunsinghk3** [comment]
There is also issue with other columns having check boxes. If column i click outside the checkbox but inside the column itself then onRowSelect event gets fired and even type returns row. But expected behavior should be that click on the column having checkbox should not trigger onRowSelect if i click outside the check box.

**Comment by vayyasi** [comment]
I am also facing the same issue if i am clicking on outside of the checkbox onRowSelect is getting triggered
