### ISSUE TITLE
datatable sorting uses previous sort results - unreliable sort order

### ISSUE THREAD

**Issue by Ketec** [primefaces/primeng#3429]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**

Each time the result is sorted, the previous sort order is used which causes the sorted order to change when all the values for the column are identical.

By standard ECMAScript standard does not guarantee sort stability- it may also be affected by the order of the input.
http://plnkr.co/edit/kmToOB4ebbJLZ7adM83g?p=preview
can show some of these anomalies. Filter value2: a, then sort value2.  Sort order goes from c,e,f,h,i to f,h,i,c,e (should be i,h,f,e,c).

**Expected behavior**

Data order is preserved on subsequent sorting and consistent (a,b,c,d -> d,c,b,a -> a,b,c,d)

**Comment by cagataycivici** [comment]
This has been discussed a couple of times, sorting depends on browser so we depend on standard although I agree that is not super stable right now.
