### ISSUE TITLE
Datatable scrollable scrollbar offset while typing in filter box

### ISSUE THREAD

**Issue by Ketec** [primefaces/primeng#3432]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/DsB7S8Lqsljliahp4yRM?p=preview

**Current behavior**

Filter something so the scroll bar vanishes. The reserved space is not removed until you press enter or click somewhere. The automatic filter while typing does not trigger whatever code recalculates and removes the reserve.

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

This causes data to become offset with headers until some sort of action later - which in return causes sudden visual change as columns are resized.

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
