### ISSUE TITLE
Datatables with a context menu can show the wrong selection

### ISSUE THREAD

**Issue by Streammz** [primefaces/primeng#3433]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/eZwW5eIDHmFcpBK7PJTt?p=preview

**Minimal reproduction of the problem with instructions**

Using the Plunkr above:

1. Left-click on a row to select it
2. Right-click the selected row to open the context-menu
3. Right-click another row to open another context menu

**Current behavior**

By executing the steps in the Minimal Reproduction mentioned above, you can force the context menu to display the wrong selection.

After these steps, both the first row and the second row appear to be selected, but only the second row actually is.

**Expected behavior**

I'm expecting only the second row to appear selected

**What is the motivation / use case for changing the behavior?**

The selection may look odd/inconsistent to the user occasionally, which make them thing they have to re-select what they selected

**Please tell us about your environment:**

Windows 10, VS2017, Node.js, Angular CLI (local 1.0.1, global 1.1.2, using local version)

* **Angular version:** 4.0.3

* **PrimeNG version:** 4.1.0-rc.2

* **Browser:** Reproduced in Chrome and Edge, untested in others
 
* **Language:** Using Typescript with ES5/6

* **Node (for AoT issues):** `node --version` = `v6.11.0`

**Comment by cagataycivici** [comment]
Try with 4.1.3 please, I can't replicate this.
