### ISSUE TITLE
p-fileUpload doesn't work any more since version 4.1.0

### ISSUE THREAD

**Issue by loic49** [primefaces/primeng#3435]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

**Expected behavior**

I use fileUpload in auto mode. I have a Choose button, when I click on it the select file window opened, then I select my file and upload start.

**Minimal reproduction of the problem with instructions**

In my HTML code, I define fileUpload in auto mode :

```
            <p-fileUpload name="test" auto="auto"
                url="/myUrl >
            </p-fileUpload>
```
When I click on Choose button, nothing append. I haven't got the select file window :(

In the source (fileupload.ts) click event is missing on button (line 15), missing script : 

`(click)="onChooseClick($event, fileinput)"`

* **Angular version:** 4.2.6

* **PrimeNG version:** 4.1.0

* **Browser:** Chrome

**Comment by cagataycivici** [comment]
With 4.1.0, It works fine at;

https://www.primefaces.org/primeng/#/fileupload

There is no (click)="onChooseClick($event, fileinput)" in our code

**Comment by loic49** [comment]
It works fine in your example but your're in basic mode. In advanced mode (which is default mode) this is not working. On your example page, we have no example in advanced mode with auto enabled.  In my previous message, I'm telling about onChooseClick function, sorry this function exists in your previous versions but doesn't exists anymore.

In actual source, I don't see any code which can open select file window.

**Comment by loic49** [comment]
In my example :

`<p-fileUpload name="test" auto="auto"
                url="/myUrl >
            </p-fileUpload>`

there's no upload and cancel button. There's only auto enabled.

**Comment by ppennings** [comment]
We have the same problem, seems the onChooseClick event has been replaced with a mouseup event ?

**Comment by loic49** [comment]
It has not been replaced by mouseup event, it has been deleted. To open file select window we must have code to simulate click on fileinput control :

`fileInput.click();`

But it doesn't exists anymore.

**Comment by loic49** [comment]
It seems problem disapear on version 4.1.3.
