### ISSUE TITLE
Add blockScroll property to Dialog

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#3438]
When enabled body scroll is blocked.

**Comment by dhniels** [comment]
So glad for this fix, thanks a ton!

I wonder if this property should also be added to dropdown, autocomplete etc? Or perhaps a default behavior?

The reason I bring this up here is I'm experiencing this issue in several places where the same thing is happening, but inside the dialog content. 

I have a dropdown inside a dialog, for example, and when i scroll the dropdown panel, it also scrolls the dialog content (assuming its overflowing)
