### ISSUE TITLE
[Bug] DataTable with Dropdown has exception on click event

### ISSUE THREAD

**Issue by hintdesk** [primefaces/primeng#3443]
[ x] bug report => Search github for a similar issue or PR before submitting

http://plnkr.co/edit/zhA8geLzaRJgJqfrgszK?p=preview

**Current behavior**
When we click on the cell and change the value by selecting one from the dropdown box. There is an exception (see Console log in browser)

**Expected behavior**
No exception

**Angular version:**
See Plunker example above

**PrimeNG version:**
See Plunker example above

**Browser:**
Firefox

![1](https://user-images.githubusercontent.com/23084655/28359101-7606aa26-6c71-11e7-9881-4a2d4fcbcc01.PNG)

**Comment by cagataycivici** [comment]
Can be fixed with [lazy]="false" on 4.1.1
