### ISSUE TITLE
Dropdown shows focus on second tab click

### ISSUE THREAD

**Issue by ljubomir** [primefaces/primeng#345]
When user navigates through a standard multiple-input form, it takes two Tab clicks to focus the dropdown control. 
The firstr focus is on the hidden select element, and the second one ( which is visible) is on the readonly input field.

If the select element has **tabindex** attribute set to "**-1**" then the navigation works as expected.

**Comment by ljubomir** [comment]
Something similar is happening with Checkbox component - but since there is no visible focusable control as in the previous case (Dropdown) - there the checkbox gets visually completely ignored (although the hidden checkbox is actually focused and by hitting spacebar i can toggle its value).

**Comment by cagataycivici** [comment]
Can't replicate with RC4.

http://www.primefaces.org/primeng/#/dropdown

I can navigate with single tab.

**Comment by akashshelke22** [comment]
**@cagataycivici** If you want to replicate this then set tabindex to drop down. It takes 2 tabs for actual focus on drop down. First tab focuses on outer div and second tab focuses on options.

**Comment by fmontes** [comment]
Having the same issue, only happen when you add ```tabindex``` to the ```p-dropdown```

**Comment by eniwetok** [comment]
Same here , please reopen 

> Having the same issue, only happen when you add tabindex to the p-dropdown

**Comment by emsedano** [comment]
same here

**Comment by lasimone** [comment]
Same problem here

**Comment by Gilbert1391** [comment]
Same issue, any work around?

**Comment by waratah** [comment]
SEE ALSO https://github.com/primefaces/primeng/issues/8235

**Comment by ssameermd** [comment]
I used this as a workaround to set the tabindex of button associated with autocomplete to -1.

ngAfterViewInit() { 
   $(":button.ui-autocomplete-dropdown").attr('tabindex', -1);
  }

**Comment by crazyjavatricks** [comment]
Issue still exists in primeNg 11.
