### ISSUE TITLE
Fileupload drag'n drop placeholder

### ISSUE THREAD

**Issue by luanfagu** [primefaces/primeng#3451]
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**What is the motivation / use case for changing the behavior?**
Show a message inside fileupload drag and drop field, so the user will know what to do

**Comment by cagataycivici** [comment]
Will reconsider if more users demand it.

**Comment by ankitminglani** [comment]
any idea if this will be provided in the future? its confusing for users to know intuitively if they can even drag and drop in that empty upload box. a label would definitely help!

please comment.

**Comment by mateofacu** [comment]
+1

**Comment by DanWahlin** [comment]
Definitely something that would be nice to have. I can hack the DOM/CSS to add something like that, but providing a way to show a label there and adjust the height via a property would be great. The following works to add some height and an initial value (adding/removing the text content via the DOM would be better), but would be great to have properties to control this:

::ng-deep .ui-fileupload-content {
    min-height: 50px;
}

::ng-deep .ui-fileupload-content:before {
    content: 'Drop files here';
}

**Comment by vahidvdn** [comment]
+1

**Comment by vahidvdn** [comment]
You can this class: `.ui-fileupload-content.ui-fileupload-highlight`

This must be documented.
