### ISSUE TITLE
Sticky and Life per Growl message

### ISSUE THREAD

**Issue by MSAJJAN-EEOC** [primefaces/primeng#3452]
**I'm submitting a ...**  
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ *] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
currently can only give delay or sticky option for the element p-growl 

**Expected behavior**
ability to give delay and sticky option for individual message satisfies many scenarios unlike the existing use case.

**Comment by ChamNouki** [comment]
This feature could be greatly appreciated.
More over it could be great to be able to stick dynamically a message when the user puts the mouse over it.

**Comment by anazard** [comment]
cant it be done through a mouse event that triggers a method that pushes new items onto the messages array, @ChamNouki ?

**Comment by byunru** [comment]
5.0.2, still waiting ...

**Comment by whiteblackkeys** [comment]
it would be great!

**Comment by tadamczak** [comment]
Any chance of having this issue fixed? Why it got removed from milestone?

**Comment by stevenvanryckeghem** [comment]
I've encountered this: https://www.npmjs.com/package/primeng-advanced-growl
Is it possible to incorporate that to the PrimeNG library so we're not dependent on a 3rd party library?

Looks like there is a lot of demand for this issue...

**Comment by cagataycivici** [comment]
Use toast please.
