### ISSUE TITLE
primefaces.org/primeng website is broken

### ISSUE THREAD

**Issue by kalypzo** [primefaces/primeng#3453]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Website breaks when clicking on any links in the navbar for primefaces.org/primeng

**Expected behavior**
Ability to navigate throughout the website

**Minimal reproduction of the problem with instructions**
Navigate to primefaces.org/primeng and click on any link

**Comment by mikeyg123** [comment]
works for me

**Comment by fxmfr** [comment]
Sometimes, I have the same issue. Some links are working, some not. But only from time to time. For me, in most cases after an hour or so it's working again.
I'm using Chrome 59.

**Comment by kalypzo** [comment]
Seems like it's working now, I'll close this issue
