### ISSUE TITLE
DataTable Loading Status Icon not working on (4.1.1), worked fine on (4.1.0)

### ISSUE THREAD

**Issue by mrbalcos** [primefaces/primeng#3457]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
```

**Current behavior**
Loading Icon does not display while data is loaded on DataTable

**Expected behavior**
Loading Icon should be displayed while the model assigned for Loading is set to True

**Please tell us about your environment:**
Windows 7

* **Angular version:** 2.0.X
Angular 4

* **PrimeNG version:** 2.0.X
PrimeNG 4.1.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All Browsers

**Comment by mseemann** [comment]
the `laodingIcon `porperty is dfined at `pScrollableView `but is used in `p-dataTable`. so 

`<i [class]="'fa fa-spin fa-2x ' + loadingIcon"></i>`

will result in `<i class="'fa fa-spin fa-2x undefined "></i>`

**Comment by miniplus** [comment]
I made the PR for that previously, so I'm to blame here. Sorry people!
Already made a PR with a fix.
