### ISSUE TITLE
Relate dropdown id with label for element

### ISSUE THREAD

**Issue by ljubomir** [primefaces/primeng#346]
Having keyboard user experience in mind, it would be nice if labels that are related to the dropdown controls can trigger focus of the appropriate dropdown components when clicked upon, like this:

`<label for="my_country">Country</label>
<p-dropdown [options]="countries" [(ngModel)]="model.country" id="my_country"></p-dropdown>`

When i manually move the **id** attribute to the readonly input field then this behavior is achieved.

**Comment by jcde** [comment]
+1

**Comment by cagataycivici** [comment]
Adding inputId;

```xml
<label for="city">City</label>

<p-dropdown inputId="city" [options]="cities" [(ngModel)]="selectedCity" placeholder="Select a City"></p-dropdown>
```

**Comment by battmanz** [comment]
Did Angular 4 break this? I'm trying it with Angular 4 and it's not working.

**Comment by JamalGuyo** [comment]
This issue is still there in primeng v17.3. 
`<label for="user">User</label>
<p-dropdown [options]="users" [(ngModel)]="model.user" id="user"></p-dropdown>
`
The label is not focusing on the p-dropdown. same issue with multiselect.
