### ISSUE TITLE
Header template for Listbox

### ISSUE THREAD

**Issue by pierfreeman** [primefaces/primeng#3460]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

Currently, component like dropdown and listbox do not provide a built-in subcomponent for adding elements to the options list.

**Expected behavior**

It would be nice to add this feature, similar to the filter option. If an hypotetical option "add" is set to true, then in the same filter header should appear a "+" button. 
The subcomponent should carry with him a event, like "onAddOption" to be binded to a custom method.

**What is the motivation / use case for changing the behavior?**

For my project every time I use a listbox/dropdown with filter option set on, there always is an "add" button for adding new options. So it would be useful to have it built-in.

**Comment by cagataycivici** [comment]
Better to offer a template header so you can place custom content.
