### ISSUE TITLE
Calendar: Inner input element misses the name attribute

### ISSUE THREAD

**Issue by KatzeKahn** [primefaces/primeng#3461]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

The name attribute is not added to the inner Html input element. For this reason, Edge is showing a full dropdown list of input suggestions that hides the date grid underneath.

**Expected behavior**

Adding the name property to the inner input element will fix the issue.

**Please tell us about your environment:** Windows 10

* **Angular version:** 4.1.0

* **PrimeNG version:** 4.1.0

* **Browser:** Edge 14

**Comment by cagataycivici** [comment]
Will add name property.
