### ISSUE TITLE
DataTable Performance Optimizations

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#3468]
DataTable requires optimizations as large number of rows slows it down and causes lags. Check which events trigger unnecessary change detection and reimplement them with NGZone, runOutsideAngular approach to avoid unnecessary change detection. Room for improvements are;

- Resizable columns document mouse move listener
- Scrollable table scroll listener
- Editable document click listener binding

**Comment by cagataycivici** [comment]
Changes are in, performance gain is significant, lags are gone.

**Comment by ova2** [comment]
Congrats. Good catch with runOutsideAngular. It's also used with Analytic Scripts, etc.

**Comment by steefzuid2** [comment]
Hey,

What about the actual commits that should acompany this ticket? I don't see any commits, I don't see any performance improvements either?

**Comment by steefzuid2** [comment]
Ahh, I found the commits!. But if I use a datatable in my application I see a doCheck event on the component for every mouse move, even outside the component. I would expect that the checks do not popup since the document.onmousemove is running outside angular?
