### ISSUE TITLE
Datatable header improve styling options

### ISSUE THREAD

**Issue by Ketec** [primefaces/primeng#3469]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Datatable header, when using sort and filter, does not allow positioning, overflow, margins etc.
All 3 elements are in th -> span, span, input.
Therefor i cannot for example align the sort icon to the right. 
Flex moves the sort icon to a new row if column is resized ().

**Expected behavior**
For example:
```
            <div class="title-sort-wrapper">
                <span class="ui-column-title" *ngIf="!col.selectionMode&&!col.headerTemplate">{{col.header}}</span>
                <span class="ui-column-title" *ngIf="col.headerTemplate">
                    <p-columnHeaderTemplateLoader [column]="col"></p-columnHeaderTemplateLoader>
                </span>
                <span class="ui-sortable-column-icon fa fa-fw fa-sort" *ngIf="col.sortable"
                      [ngClass]="{'fa-sort-desc': (dt.getSortOrder(col) == -1),'fa-sort-asc': (dt.getSortOrder(col) == 1)}"></span>
            </div>
```
A wrapper around the text, icon separates it from the filter input field (should always be on a separate line). By default it may not need to do anything - but it provides the class and a container users can manipulate/change with css to their needs.
Like using flex layout for the wrapper, space between and overflow hidden on the title element.

The title could have a support for tooltip (in case columns are narrow and text won't fully fit).
**What is the motivation / use case for changing the behavior?**
I would like to have the title text hide, keeping icon on the same row, aligned right.
Like: http://imgur.com/jbRAV87

**Comment by pantonis** [comment]
Yes this is highly needed.

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
