### ISSUE TITLE
Dialog Component - Setting Resizeable False doesn't remove resize handle 

### ISSUE THREAD

**Issue by GraemeSMiller** [primefaces/primeng#347]
On setting resizeable false on a dialog the resize handle remains. On hovering cursor changes but the resize isn't allowed.

I would expect that the resize handle and cursor tooltip vanish if resizeable is set to false.
![image](https://cloud.githubusercontent.com/assets/2472587/15218745/25428eb0-1859-11e6-8109-8472905fa8e1.png)

**Comment by Mrtcndkn** [comment]
https://github.com/primefaces/primeng/commit/23f992012d12cfc792eee596f7a9da6514fcff58
