### ISSUE TITLE
Datatable - Cannot read property 'tagName' of null - when editable true

### ISSUE THREAD

**Issue by Benny739** [primefaces/primeng#3478]
There's an error in Datatable, when editable=true and you mark more than one column with the mouse.
Cannot read property 'tagName' of null
`    DataTable.prototype.findCell = function (element) {
        var cell = element;
        while (cell.tagName != 'TD') {
            cell = cell.parentElement;
        }
        return cell;
    };
`

Error is also in the examples present: https://www.primefaces.org/primeng/#/datatable/editable

![ashampoo_snap_2017 07 21_13h58m26s_013_](https://user-images.githubusercontent.com/13584853/28462722-b4cc54c0-6e1c-11e7-9357-314eeee367b7.png)

**Comment by jampueroc** [comment]
I have the same problem

The line 1422 in datatable.js , should by:
`while (cell && cell.tagName != 'TD')`

**Comment by JimmySpicy** [comment]
Hello, I am facing the same issue.

![cannot_read_property_tagname_of_null](https://user-images.githubusercontent.com/10233387/28727180-33a181ba-73c4-11e7-9898-2a325df4cf56.PNG)


@jampueroc  Thanks for sharing your solution, I will test.

**Comment by cagataycivici** [comment]
Somehow I can't replicate but added checks anyway.
