### ISSUE TITLE
InputSwitch - Initial value not working

### ISSUE THREAD

**Issue by PhilippRoessner** [primefaces/primeng#348]
When the bound property of inputSwitch is true while initialization, the inputSwitch shows the false - state.
See -> [showcase](http://primefaces.org/primeng/#/inputswitch) -> InputSwitch #2 shows "Labels - true", but switch is off

**Comment by Mrtcndkn** [comment]
https://github.com/primefaces/primeng/commit/88eef797370549870f7dbc780549f8d41ca1be3b
