### ISSUE TITLE
Dropdown should open using the enter key

### ISSUE THREAD

**Issue by jgill248** [primefaces/primeng#3480]
I'm submitting a ... (check one with "x")

[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
Expected behavior
Pressing the enter key should open the dropdown list when the dropdown has focus and the dropdown list is not open.

What is the motivation / use case for changing the behavior?
Mirrors behavior for the native HTML select element (and other similar controls, e.g. angular material's select).

https://www.w3schools.com/tags/tag_select.asp

Please tell us about your environment:
Windows 10

PrimeNG version: 4.1.0

Browser: All

**Comment by cagataycivici** [comment]
space or alt+down opens it, I don't think that native select element opens up on enter key so p-dropdown does the same.

**Comment by jgill248** [comment]
this is an unmolested example of of straight html:
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select
if the drop down has focus, enter does open it.

**Comment by jabernalv** [comment]
I solve this problem setting a ref in Dropdown an in @keydown.enter of Dropdown I put
(this.$refs.ref_name as InstanceType<typeof Dropdown>).show();
