### ISSUE TITLE
Dropdown not selecting item on enter keyDown

### ISSUE THREAD

**Issue by jgill248** [primefaces/primeng#3481]
I'm submitting a ... (check one with "x")

[x] bug report => Search github for a similar issue or PR before submitting
[] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
Expected behavior
Using the enter key to select an item in the drop down list does not fire onChange and does not update the model binding.

What is the motivation / use case for changing the behavior?
This prevents users from using the keyboard to interact with the drop down control.  A work around using keyup.enter does not work either.

Please tell us about your environment:
Windows 10

PrimeNG version: 4.1.0

Browser: All

**Comment by burhanyldz** [comment]
#2845
