### ISSUE TITLE
Text input readonly attribute

### ISSUE THREAD

**Issue by just-paja** [primefaces/primeng#3482]
PrimeNG needs to support readonly attribute for inputs. It was already mentioned and closed as #117 stating that issue is too common. Requesting to add support for readonly attribute to Text input.

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**What is the motivation / use case for changing the behavior?**
There is behavioral and semantic difference between [readonly](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-readonly) and [disabled](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-disabled)

* **PrimeNG version:** 4.1.1
* **Browser:** all
* **Language:** all

**Comment by cagataycivici** [comment]
Provide separate tickets per component please as this issue is too broad.

**Comment by just-paja** [comment]
@cagataycivici, "Text input read only attribute" is too broad? Can you please provide an example of less broad issue? I think this relates only to text input component.

**Comment by sabithpocker** [comment]
```css
.ui-widget.read-only:disabled{
	opacity: 1;
	background-color: #dddddd;
}
```

```html
                <input
                  type="text"
                  class="read-only"
                  disabled="disabled"
                  name="name"
                  [(ngModel)]="model.name" pInputText>
```
