### ISSUE TITLE
SelectButton: add custom style to each button option 

### ISSUE THREAD

**Issue by pierfreeman** [primefaces/primeng#3485]
I'd like to have a different color for each button in SelectButton. Is there a way to define a style scoped only to the specific option, for example like using ng-template?

**Comment by cagataycivici** [comment]
No but we can add styleclass to selectitem api to do it.

**Comment by MarMic1** [comment]
Is there a way to use ng template like in the dropdown for selectbutton. I want to use my translation pipe in html. So i need a ngTemplate for the options to translate them. @cagataycivici

**Comment by kirillzhk** [comment]
@cagataycivici 
I need to color all buttons depends on value inside the button. 
Could you please advise how to use styleclass for SelectButton? I have tried different options, but i can't add any custom class of something like that. Might you have some example for it? 
![image](https://github.com/user-attachments/assets/13e7540f-3c3e-4062-a300-aa4502a27543)

button 40 - i need to have green
button 41 - i need to have red
button 42 - i need to have blue
button 43 - i need to have green
... ect

**Comment by paweluz** [comment]
It seems like this issue exists again, I need to have each button with different style, I used to pass a value as a list of SelectItems with a styleClass defined, and it was working. Currently I am migrating from angular15 to angular 19 and this feature stopped working. Are there any plans to make it work again ?
