### ISSUE TITLE
 showUploadButton ="false" not working

### ISSUE THREAD

**Issue by ketimaBU** [primefaces/primeng#3487]
Hi, 
the  showUploadButton setted false is not working is still showin the upload button 
regards

**Comment by nni123** [comment]
[showUploadButton]="false" or [showCancelButton]="false"

**Comment by ketimaBU** [comment]
I am sorry, I feel stupid thanks

**Comment by Mrtcndkn** [comment]
I think the problem is solved according to @nni123's answer.

**Comment by neoswf** [comment]
@ketimaBU you are not stupid. It did not work for me as well. It is the only property, in the list of properties I am using, that need to be configured this way.

Thank you @Mrtcndkn for this great lib!!!

**Comment by ajcastro** [comment]
Why it is solved with square brackets? I though square brackets are for variables

**Comment by guardiannite** [comment]
@ajcastro  You are correct, square brackets are for variables, but when you don't use them the value gets treated as a string.  The string "false" in JavaScript is actual a truthy statement.  [MDN Web Docs - Truthy](https://developer.mozilla.org/en-US/docs/Glossary/Truthy)

Any non empty string will get treated as true.
 e.g.
showUploadButton="true"
showUploadButton="pizza"
showUploadButton="false"

If you wanted to set it to false and not use square brackets, you could set it to an empty string:
showUploadButton=""
