### ISSUE TITLE
IE - 'null' shown before tooltip's text

### ISSUE THREAD

**Issue by guy-eizon** [primefaces/primeng#3490]
When using pTooltip and changing the tooltip's text, IE is rendering the text with a 'null' prefix.
This null from some reason is shown as text (only in IE) due to the innerHtml assignment to null in the updateText() method.
Changing the assignment to empty string ('') fixes to issue.

**Comment by cagataycivici** [comment]
Fixed via PR https://github.com/primefaces/primeng/pull/3489
