### ISSUE TITLE
have to refresh browser to use file upload component 2nd time

### ISSUE THREAD

**Issue by ericxchang** [primefaces/primeng#3491]
Even with the very 1st example (advance file upload) in primeng page (https://www.primefaces.org/primeng/#/fileupload), after successfully upload one file, 2nd time select file, nothing will be listed. I saw this issue on chrome and IE 11, firefox seems ok.
Just found out the 4.0.0-rc3 version does not have this issue.

**Comment by nni123** [comment]
https://www.primefaces.org/primeng/#/fileupload

Above link works fine for me in chrome 59 version, firefox (most consistent performer) & Edge. In advance mode filename names remain after upload e.g. file0.jpg, file1.jpg etc stays in description box

**Comment by cagataycivici** [comment]
It all works for me, description box is for demo purposes, it lists what is uploaded, if you remove ng-template with pTemplate="content", they will go away.
