### ISSUE TITLE
OverlayPanel position is wrong on the second open

### ISSUE THREAD

**Issue by BecseiMiklos** [primefaces/primeng#3492]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

```
**Current behavior**
I use a p-overlayPanel to display an image preview in a datatable. When I click the button which invokes the toggle method of the overlayPanel, everything works well, it aligns to the target component that I want, but, on the second click, it sticks to the top of the screen. The whole page is contained by an ng-template tag. I tried to use appendTo="body", but it shows the same behaviour. Any idea what am I doing wrong?

* **Angular version:** 4.3.0

* **PrimeNG version:** 4.1.0

* **Browser:** [Chrome]

**Comment by cagataycivici** [comment]
Unable ot replicate please provide a plunkr;

http://plnkr.co/edit/Qi2Nw2imLpDUF8NJinYw?p=preview
