### ISSUE TITLE
Template support for Tooltip

### ISSUE THREAD

**Issue by tbetous** [primefaces/primeng#3496]
```
[x] bug report
[x] feature request 
[ ] support request 
```

I am currently using pTooltip and before that I used tooltip from ngx-bootstrap. I used to make templates and used them in my tooltip like this :  

```
<i class="fa fa-circle text-default" aria-hidden="true" [pTooltip]="defaultTooltip" tooltipPosition="top">
<ng-template #defaultTooltip>
    Something to display
</template>

```

Here it displays `[Object object]`. I wonder if it is possible to display what is actually inside my template.

**Comment by cagataycivici** [comment]
This is not supported, changing the title according to it.

**Comment by MrBlaise** [comment]
I would love this feature as well.

**Comment by pabloaccorinti** [comment]
+1

**Comment by djagielo** [comment]
+1

**Comment by madvlad** [comment]
+1

**Comment by madvlad** [comment]
+1

**Comment by danailvidev** [comment]
+1

**Comment by speti43** [comment]
Set escape to false, and it will render html:
`<div pTooltip="Some text <br> next line" tooltipPosition="top" [escape]="false"></div>`

Docs:
http://primefaces.org/primeng/#/tooltip

**Comment by keschr** [comment]
+1

**Comment by FabienDehopre** [comment]
> Set escape to false, and it will render html:
> `<div pTooltip="Some text <br> next line" tooltipPosition="top" [escape]="false"></div>`
> 
> Docs:
> http://primefaces.org/primeng/#/tooltip

This won't work if your tooltip contains an `*ngIf` or `*ngFor`. It would be great if pTooltip can accept a template reference.

**Comment by noamyg** [comment]
+1

**Comment by eXpertise7** [comment]
> <div pTooltip="Some text <br> next line" tooltipPosition="top" [escape]="false"></div>

@speti43 it does work, what you have written, but it won't apply css class next to HTML element

PrimeNG please consider doing it in the future

**Comment by Ccappuccino** [comment]
+1

**Comment by yokrysty** [comment]
+1

**Comment by Silvest89** [comment]
+1

**Comment by ThoSap** [comment]
+1

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by stephanebouget** [comment]
Hi,
just tested on fresh **14.2.2** release
**The enhancement has not been made.**

We need to add dynamic components into the ptooltip component.
With the "escape" parameter to false, basic html is just transcribed.

For instance, in my case, i need to add a custom component into the tooltip, like that : 
![image](https://user-images.githubusercontent.com/13203455/202160552-3f7737a5-c3ae-4c7b-94e9-fc8e56ff04df.png)

but it's just "pasted" into the tooltip.

@mertsincan is it possible to reopen the issue ?

**Comment by ThoSap** [comment]
+1

**Comment by JacobSiegle** [comment]
Trying to port from https://ng-bootstrap.github.io/#/components/tooltip/api and the template support is def a nice feature to have

**Comment by kyjus25** [comment]
I was able to get a templateRef to show in the tooltip, but am having issues getting *ngIfs and interpolated values to show when the tooltip is rendered. It works after an ngModel change, so not sure what is happening. Would anyone be interested in seeing if they can help fix?

https://user-images.githubusercontent.com/6710794/227332950-2aa73a10-f856-484f-988f-ef18d7abaca9.mov

**Comment by kyjus25** [comment]
PR Updated and ready to merge!
