### ISSUE TITLE
Partial preselection in Tree fails 

### ISSUE THREAD

**Issue by MadUser** [primefaces/primeng#3498]
**I'm submitting a ...** 
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
on checkbox mode, when passing selection with list of items, the partial selection behavior doesn't  work (no fa-minus icon), the partial selected nodes checkbox stays empty.
It looks like only on click you trigger the propagate up which sets the partialSelected to true.
I think you should do the same when setting the selection input.

**Expected behavior**
set partial selected items with fa-minus icon.

* **Angular version:** 4.2.6

* **PrimeNG version:** 4.0.3

**Comment by nkvaratskhelia** [comment]
I have the same issue.

Angular version: 4.4.3
PrimeNG version: 4.2.1

**Comment by cagataycivici** [comment]
Duplicate https://github.com/primefaces/primeng/issues/3579

**Comment by RaviSambaraju** [comment]
Hi,

 I have an issue in Treetable.

<p-treeTable [value]="files" [(selection)]="selectedFiles2" (onNodeUnselect)="nodeUnselect($event)" (onNodeSelect)="nodeSelect($event)"
          selectionMode="checkbox">
          <p-column field="name" header="Permissions"></p-column>
        </p-treeTable>
I'm passing some data(pre-selection data) to  [(selection)] attribute. I have child data with check at this time  the parent check box  is not updating with minus.

My Output:
![wrong senario](https://user-images.githubusercontent.com/19923384/31994043-dfdad602-b99c-11e7-85d2-8c98d8c40643.png)


Expected Output:

![expected output](https://user-images.githubusercontent.com/19923384/31994050-e5a113da-b99c-11e7-91bc-730630d0f74c.png)

Any help is highly Appreciated.

**Comment by RaviSambaraju** [comment]
I got solutions for this problem, Simply we need to set partialSelected = "true" in seletion array at particular node  which we required.

**Comment by nkvaratskhelia** [comment]
You mean we have to manually check the data in all nodes(if they are partial or not) and set the partialSelected = "true" property on those nodes that are partial?

**Comment by RaviSambaraju** [comment]
Exactly..

**Comment by jigneshkhatri** [comment]
Found a workaround for pre-selection of multiple check-boxes (programmatically) in primeng Tree. You can find working example here: https://github.com/jigneshkhatri/primeng-treenode-preselect

**Comment by wiz-t-fujioka** [comment]
複数Ortho、複数IOSのようなレイヤリスト構成の「半月」（partialSelected）制御は極めて困難です。
多数の試験コードを実行しましたが、先頭ノードと配下の各親ノード間で、
完全に整合された「半月」（partialSelected）制御は、実現できそうな見込みがありません。
（先頭ノードのみを除けば、実現できそうです）

https://github.com/primefaces/primeng/issues/12714
https://stackoverflow.com/questions/69899723/primeng-p-tree-preselect-not-working-with-partialselected-selectable-set-to-tru

<img width="978" height="719" alt="Image" src="https://github.com/user-attachments/assets/125ee20f-a040-4af7-a0a3-0510b6a603d8" />
