### ISSUE TITLE
[BUG REPORT] Datatable: error 'tagName' on edit

### ISSUE THREAD

**Issue by jampueroc** [primefaces/primeng#3499]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

http://plnkr.co/edit/upCMls6dQBWSbbCl0WBV?p=preview

**Current behavior**

On delete, or change element on Datatable, throw the following error:
`TableBody.html:15 ERROR TypeError: Cannot read property 'tagName' of null`
![prime_error](https://user-images.githubusercontent.com/9870984/28531344-96322b8a-7064-11e7-9690-49b4fc375cf3.PNG)

**Expected behavior**

No errors

**Minimal reproduction of the problem with instructions**

In plnkr click on field and delete an element 

Similar Issues (not bug report):
https://github.com/primefaces/primeng/issues/3478
https://github.com/primefaces/primeng/issues/3456

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

npm: 5.3.0

* **Angular version:** 2.0.X

I had 4.2.6 and I have changed to 4.3.1 and still happens

* **PrimeNG version:** 2.0.X

4.1.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

* **Node (for AoT issues):** `node --version` =   
v6.11.1

**Comment by rakylegend** [comment]
Hi,
Same error happened to me also, when i first load the data table with editor option no error occurred. when autocomplete changes the html template error occurred.
Before change the template
![before change td element](https://user-images.githubusercontent.com/21354536/28616444-6d4ead12-721a-11e7-8e0c-b8292a5af3bb.png)
After
![after](https://user-images.githubusercontent.com/21354536/28616456-771ffc24-721a-11e7-8b3b-1b166b8d024c.png)

Angular 4.3.1
PrimeNG 4.1.1

**Comment by cagataycivici** [comment]
Try with 4.1.3 please.
