### ISSUE TITLE
Duplicate property declaration in Calendar CSS

### ISSUE THREAD

**Issue by elanalynn** [primefaces/primeng#3501]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
There is no effect on behavior, but the `position: absolute;` property appears twice on `.ui-calendar button` class in the calendar.css file (lines 7 and 11).

**Expected behavior**
There should only be one position property in the class.

**What is the motivation / use case for changing the behavior?**
It will be easier to debug styling issues without duplicate properties.

* **PrimeNG version:** 2.0.X
4.1.2

**Comment by cagataycivici** [comment]
As the issue is not a defect, removing milestone and won't add to release notes. But change is applied to 4.1.2.
