### ISSUE TITLE
Add required property to AutoComplete, Spinner and InputMask

### ISSUE THREAD

**Issue by dhniels** [primefaces/primeng#3503]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request 
```

**What is the motivation / use case for changing the behavior?**
Looking at the documentation on PrimeNG site, it appears that p-dropdown has a "required" property, but the autocomplete does not. It seems highly important that required also be a property of autocomplete because it something that would be used in forms. In my case, I have in several places autocompletes inside table cells that I would like to set to required and use angulars built in validation classes to style them. 

* **Angular version:** 4.3.1

* **PrimeNG version:** 4.1.1

**Comment by progmancod** [comment]
Please, this is very important!

**Comment by dhniels** [comment]
Is there any workaround way to do this until the feature is added? Its very important in our application as we have several autocompletes that need a required attribute.

**Comment by Jonatino** [comment]
I would like this as well!
