### ISSUE TITLE
Spinner allow  +,-,% values 

### ISSUE THREAD

**Issue by Gurumurthy-Chimpigar** [primefaces/primeng#3507]
Hi Ng prime team,
The spinner control in ng prime is allowing user to enter +,-,% values .Due to this we are not able to shown validation message as "Please enter valid number" when user enter only symbols. The singe symbols(+,-,%) is considered as null value in the form group variable.
<p-spinner size="1" [maxlength]="1" formControlName="count" [min]="0" [max]="8" (onChange)="onCountChange(i)"></p-spinner>

Please do needful

**Comment by mertsincan** [comment]
Hi,

Please use inputNumber component.

Best Regards,
