### ISSUE TITLE
 Undefined variable: "$inputGroupTextColor"

### ISSUE THREAD

**Issue by Rookian** [primefaces/primeng#3508]
ERROR in ./~/css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader!./~/sass-loader!./src/styling/styles.scss Module build failed: undefined ^
Undefined variable: "$inputGroupTextColor" in ...\node_modules\primeng\resources\themes\_theme.scss (line 153, column 16)

**Comment by wcgomes** [comment]
I had this problem today. This is a new sass variable $inputGroupTextColor in primeNG 4.1.1. I just created it in my variables file before importing _theme.scss.

**Comment by cagataycivici** [comment]
Built-in themes have no issue, if you are using the _theme.scss file then you need to define this variable since input groups are a new feature.
