### ISSUE TITLE
Dropdown filter: Keypress up/down does not work

### ISSUE THREAD

**Issue by lebnic** [primefaces/primeng#3511]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/LeNTzIwAAy0pUsqynA9q?p=preview

**Current behavior**Arrow up/down can't be used to navigate inside 'filter' dropdowns

**Expected behavior**
Should work similar to 'autocomplete' component, where arrow keys up/down can be used to navigate quickly to visible values in dropdown

**Minimal reproduction of the problem with instructions**
- Open plnkr above
- click on dropdown
- press arrow key down on your keyboard
- observe dropdown list value are not highlighted

**What is the motivation / use case for changing the behavior?**
This behaviour is counter-intuitive and forces user to click on the dropdown, enter the desired string in the search box, and then click onto the desired value... Would be better if user could simply use arrow keys up/down, because his hands are already on the keyboard when he's entering the search string...

**Please tell us about your environment:**
Linux

* **Angular version:** 2.0.X
4.2.0

* **PrimeNG version:** 2.0.X
4.1.2-SNAPSHOT

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

* **Node (for AoT issues):** `node --version` =   
v6.9.4

**Comment by SefaMuratcanKatirci** [comment]
#3342
