### ISSUE TITLE
Font Awesome icons are screwed up

### ISSUE THREAD

**Issue by intergleam** [primefaces/primeng#3513]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
squares instead of icons

**Expected behavior**
expect font awesome to work

**Minimal reproduction of the problem with instructions**

* **Angular version:** 2.0.X
2.4.8
* **PrimeNG version:** 2.0.X
2.0.3

* **Browser:**all

**Comment by cagataycivici** [comment]
Provide a plunkr please, also better to post this at forum, you probably miss font awesome in your project as a dependency.

**Comment by intergleam** [comment]
so you are saying font awesome supposed to work fine?

**Comment by intergleam** [comment]
i tried installing font awesome in Barcelona as said [here](https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/include-font-awesome.md) and this is what I have
![image](https://user-images.githubusercontent.com/2155554/29110706-3d40df9c-7cf0-11e7-930a-142122596665.png)

**Comment by intergleam** [comment]
i submitted a [new issue](https://github.com/primefaces/primeng/issues/3615)
