### ISSUE TITLE
Loading feedback for DataTable does not work anymore in 4.1.1

### ISSUE THREAD

**Issue by baltoaca** [primefaces/primeng#3514]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

Same code with 4.1.1: http://plnkr.co/edit/YpUOCL4IGIxtUqqEmTqJ?p=preview
Same code with 4.1.0: http://plnkr.co/edit/lnB89tmMnZKHEnbkSCED?p=preview

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

Also present in the Basic DEMO for DataTable

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.2.6

* **PrimeNG version:** 4.1.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Should be resolved with 4.2.1.
