### ISSUE TITLE
rowStyleClass in DataTable fires indefinitely

### ISSUE THREAD

**Issue by pantonis** [primefaces/primeng#3520]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
```
 <p-dataTable #dataTable class="custom-datatable" [ngClass]="isLoading === true ? 'not-visible' : 'visible'" [value]="data"
                    [rows]="10" [paginator]="true" [rowsPerPageOptions]="[5,10,20,50,100]" resizableColumns="true" [globalFilter]="gb"
                    [rowStyleClass]="lookupRowStyleClass">
                    <p-column field="Name" header="Name" [sortable]="true"></p-column>
                    <p-column field="Status" [sortable]="true" [style]="{'width':'55px', 'text-align': 'center'}">
                        <ng-template let-file="rowData" pTemplate="body">
                            <i class="fa fa-check-circle check-box-icon" aria-hidden="true" *ngIf="file.Status && file.Status === true"></i>
                        </ng-template>
                    </p-column>
                </p-dataTable>


public lookupRowStyleClass(item: Client) {
        if (item && item.Id != 1) {
            return 'cell-red';
        }
        return '';
    }
```

**Current behavior**
The lookupRowStyleClass fires all the time indefinitely

**Expected behavior**
Shouldnt file all the time but only when the data are loaded

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

WIndows 10, VS Code, npm, angular-cli

* **Angular version:** 4.2.5

* **PrimeNG version:** 4.1.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All of them
 
* **Language:** TypeScript 2.3.0

* **Node (for AoT issues):**

**Comment by pantonis** [comment]
Please see call stack attached:
![datatable-bug](https://user-images.githubusercontent.com/3295086/28664449-3d4e61f2-72c9-11e7-801d-398813eb7215.png)

**Comment by pantonis** [comment]
Any news. It causes chrome to become unresponsive

**Comment by pantonis** [comment]
Any word on that?

Still wondering how did the performance of the Datatable was improved if such a major bug causes chrome to be unresponsive?

**Comment by cagataycivici** [comment]
Use rowStyleMap instead of rowStyleClass as rowStyleClass is likely to be removed due to performance costs.
