### ISSUE TITLE
Custom filterFunction for datatable filters similar to sortFunction

### ISSUE THREAD

**Issue by Ketec** [primefaces/primeng#3521]
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
Datatable filter cannot be used with objects/arrays.
If i pass in a object (or array of objects), for example `{name: 'test', id: 1}` I would like to be able to have the column filtered by name. Because in a custom column template i use the name field as  a display value but on rowclick i need to get the id to further doSomething() with the id. Therefor the object as data.

In some cases i may have an array of items or array of objects:
`[1,2,3,4,5] or [{role: 'test', id: 1},{role: 'test2', id: 2}]`

Or when using a range filter component (like from year to year).

**Expected behavior**
Can specify custom filter method similar to sortFunction.

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.

**Comment by kareljan** [comment]
Can we reopen this? still not available in the new TurboTable. 
I would also like this.
