### ISSUE TITLE
Growl sticky input is not taken into account

### ISSUE THREAD

**Issue by bentfc** [primefaces/primeng#3522]
Last version of primeng:

On source code: a bug was introduced 10 days ago on commit "e01630c5afb6d930f29ce48c6abd06242bdaf99b".
The method "clearTrigger" does not test the sticky value anymore. So every displayed message is automatically removed from the messages list.

Linked to issue #3228

**Comment by billfranklin** [comment]
Confirm that this is an issue, we had to modify the growl.js to include the "if (!this.sticky)" check on the clearTrigger to get sticky to work..

**Comment by Merve7** [comment]
Unable to replicate, please provide a test case based on plunkr below and we’ll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview
