### ISSUE TITLE
Chips - Add new chip on Tab keypress

### ISSUE THREAD

**Issue by nmobregon** [primefaces/primeng#3527]
**I'm submitting a ...**
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
The items are added only when I press Enter key

**Expected behavior**
Would be great to have the text I'm writing appended as new chip on Tab key press. 
For multiple mail inputs, this is the most popular way of handling it.

**Minimal reproduction of the problem with instructions**
Write text in p-chips component, press tab, and the cursor moves to the next component instead of adding a new chip

**What is the motivation / use case for changing the behavior?**
Users are used to input mail addresses this way

* **PrimeNG version:** 4.1.0-rc.2

* **Browser:** [Chrome]
 
Thanks in advance

**Comment by HuseyinTurkmenoglu** [comment]
I solved this problem, and i sended 'pull request'.

It's here : [#3565](https://github.com/primefaces/primeng/pull/3565)

**Comment by nmobregon** [comment]
Hi, thanks @cagataycivici for implementig the tab button functionality.
Testing it I've found that you cannot focus next field when chips input element is empty.

Here is the [issue](https://github.com/primefaces/primeng/issues/3654) for that "bug"(¿?), guess so, because you get trapped in the component when addOnTab is enabled

Thanks!

**Comment by HuseyinTurkmenoglu** [comment]
I added a [pull request](https://github.com/primefaces/primeng/pull/3673)
