### ISSUE TITLE
DataTable - Cannot read property 'parentNode' of null

### ISSUE THREAD

**Issue by JimmySpicy** [primefaces/primeng#3528]
Hello, 

I am submitting a bug, error on DataTable.
Actually, the issue is coming with the same behavior as the issue #3478 

Please advise
![cannotreadproperty parentnode ofnull](https://user-images.githubusercontent.com/10233387/28727809-71e0ce16-73c6-11e7-84e7-bcbbe049d523.PNG)

Thanks
Regards

**Comment by JimmySpicy** [comment]
_Hello,
The code in line 972 in datatable.js 
instead of :
 if (this.editable) {
            var cell = this.findCell(event.target);
            var column = this.columns[this.domHandler.index(cell)];
            if (column.editable) {
                this.switchCellToEditMode(cell, column, rowData);
                return;
            }
        }

From my point of view should/could be:

  if (this.editable) {
            var cell = this.findCell(event.target);
            **if ( cell !== null ){**
            var column = this.columns[this.domHandler.index(cell)];
            if (column.editable) {
                this.switchCellToEditMode(cell, column, rowData);
                return;
            }
            **}**
        }

In that way the error is not coming.
Please advise.

Thanks
Regards
Jimmy

**Comment by jmesa-sistel** [comment]
I think you should create a pull request so primeng team can review it. And add a reference to this issue in the pull request so they can close it easily if the pull request is fine.

**Comment by cagataycivici** [comment]
Fixed at #3478
