### ISSUE TITLE
Request Grid CSS support responsive-utilities like .visible-sm-*, .hidden-sm, etc 

### ISSUE THREAD

**Issue by jefftham** [primefaces/primeng#3532]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

the current grid css work fine, but users cannot get rid of Bootstrap.
.visible and .hidden are very base classes for grid css.

**Expected behavior**

expected to support several css classes like Bootstrap.
[Boostrap responsive-utilities](http://getbootstrap.com/css/#responsive-utilities)

**What is the motivation / use case for changing the behavior?**

complete the functionalities of grid css.

* **Angular version:** 4.2.6

* **PrimeNG version:** 4.1.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   8.1.4

**Comment by stephanecot** [comment]
I need that for the datatable.

**Comment by pkelleter** [comment]
+1
No comment by the developers so far? This really is a standard requirement for grids i would say.

**Comment by shorstki** [comment]
Definitely needed. Would be great to have such features like on Bootstrap grid.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
