### ISSUE TITLE
Input: Calendar: Forward and back button is not working properly

### ISSUE THREAD

**Issue by nsharma62** [primefaces/primeng#3534]
Suppose we have set minDate = Jan 2000 and maxDate = Dec 2030 then after reaching to the maxDate the forward arrow leads us to the minDate and when we are on minDate then Backward arrow just only rotate months of year 2000.

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below, create a new issue and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview
