### ISSUE TITLE
Tooltip using in MenuItem

### ISSUE THREAD

**Issue by t0masphp** [primefaces/primeng#3535]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
MenuItem interface now not support tooltips, in case if i try create something like toolbar by p-menubar, and use only icons, i can't set tooltip for items.

**Expected behavior**
I can add to menu item params tooltip?: string and tooltipPosition?: string; witch provide using pTooltip directive in menu.

**What is the motivation / use case for changing the behavior?**
Create toolbar, custom submenu with icons only.

**Please tell us about your environment:**
Linux

* **Angular version:** 4.X.X
4.3.2

* **PrimeNG version:** 4.0.X
4.1.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript
* **Node (for AoT issues):** `node --version` =   
v8.1.2

**Comment by cagataycivici** [comment]
This is currently utilized by some of the premium templates like Barcelona, please create separate issues like; 

"Tooltip support for MenuBar MenuItems" as not all menu components implement the full set of menuitem apis.

Note that for p-menu components, we'll use simple title attribute instead of p-tooltip.
