### ISSUE TITLE
Readonly attribute of p-editor component does not reflect changes

### ISSUE THREAD

**Issue by QuentinLeGoff** [primefaces/primeng#3536]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/0DzGbzNPYLOTkInP7i2i?p=preview

**Current behavior**
The change of readonly attribute doesn't work.

**Expected behavior**
Change the readonly attribute dynamiccaly should work and freeze or not the p-editor component

**Minimal reproduction of the problem with instructions**
Readonly attribute is set to true so the editor cannot be change.

1. Set readonly attribute to false with checkbox component

**Please tell us about your environment:**

* **Angular version:** 4.3.1

* **PrimeNG version:** 4.1.2

* **Browser:** [all]
 
* **Language:** [TypeScript 2.3 | ES6/7 | ES5]

**Comment by ankurmay1988** [comment]
Do we have any workarounds for this in Angular 4.3 ?
