### ISSUE TITLE
Slider doesn't work when using range + orientation vertical

### ISSUE THREAD

**Issue by Tuizi** [primefaces/primeng#3540]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/UEegqgJdrC78E9xeLhrQ

**Current behavior**
Using the Slider in vertical mode with Range doesn't work.

**Expected behavior**
Being able to use the slider with range working in vertical like it does in horizontal.

**What is the motivation / use case for changing the behavior?**
Using the slider with range should not be dependant of the slider orientation?

* **Angular version:** 4.1.3

* **PrimeNG version:** 4.1.2

* **Browser:** [all]
 
* **Language:** [TypeScript 2.3.4]

**Comment by HuseyinTurkmenoglu** [comment]
I solved this problem, and i sended 'pull request'.

It's here : [#3566](https://github.com/primefaces/primeng/pull/3566)
