### ISSUE TITLE
Ability to cancel dropping node from p-tree

### ISSUE THREAD

**Issue by ChamNouki** [primefaces/primeng#3544]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behaviour**
When you subscribe to onNodeDrop event it's already too late to forbid dropping here for business logic.

**Expected behaviour**
It could be great to be able to cancel drop event if we don't authorize node to be dropped here.

**Minimal reproduction of the problem with instructions**
Simply use a p-tree in your template. Subscribe to onNodeDrop event and in the callback method, it's impossible to prevent dropping from happening.

**What is the motivation/use case for changing the behaviour?**
My tree is actually composed of several depth levels and my business logic told me that a node of depth 3 can't be moved to a depth 2 node.

**Please tell us about your environment:**
OSX, WebStorm, NPM

* **Angular version:** 4.3.2

* **PrimeNG version:** 4.1.2

* **Browser:** all
 
* **Language:** all

**Comment by Abdelghani90** [comment]
I am having the same issue.

**Comment by lingarajsureban** [comment]
I am also looking for the same solution...

**Comment by Abdelghani90** [comment]
Is there any updates related to this issue?

**Comment by zivlevy** [comment]
Same issue here, need to prevent drop of leaf onto another leaf

**Comment by akila89** [comment]
I am also looking for the same solution..

**Comment by HolyMacarony** [comment]
the same for me

**Comment by mojo2405** [comment]
I tried to figure out how to get the index of the dragNode and dropNode.
for the dragNode - you can use this.tree.dragNodeIndex
though I didn't find how to get it for the dropNode.
In addition - I want to disable the option to drag nodes 'over' each other and I couldn't find how to do so.
Did anyone had luck with that ? maybe @KapilSachdev ?

**Comment by KapilSachdev** [comment]
As per the implementation you may not get the `dropNodeIndex`. (I didn't used it in my case.)
What do you mean by disabling the option to _drag nodes 'over' each other_ ?
(If the drag feature is enabled it will effect every node until explicitly disabled.)

**Comment by mojo2405** [comment]
My goal is to drag and drop to save level and same level only.
For example : 
-
| - Folder 1
    | - Node 1
    | - Node 2
    | - Folder 1.1
        | - Node 3
| - Folder 2
    | - Node 4
    | - Node 5

Node 1 and 2 can switch places but they can not be dragged to folder 1.1 or Folder 2

**Comment by mojo2405** [comment]
found the solution for that. Just added this code  :

`UITreeNode.prototype.onDropNodeDragOver = function (event) {
            return;
        };`

**Comment by KapilSachdev** [comment]
Good that you found the solution, this way you can also customize the dragging with drop.
However, if it was only to disallow the drop but show dragging (you were also trying to not show the drag move as it look) one might also add custom levels to node data and use `allowDrop`.

```javascript
{
   id: 1,
   label: "Folder 1",
   level: 1,
   children: [
     {
       id: 1,
       label: "Node 1",
       level: 2,
       children: [
         ]
      }
   ],
   id: 1,
   label: "Folder 2",
   level: 1,
   children: [...]
 }
```

and `return false` on `drop` on the condition one is interested in, like in your case siblings are allowed else restricted.

**Comment by mojo2405** [comment]
great ! 
so now here is my code :
node_dropped(e: any) {
        // If parents are equals and not dropping on same node and dropIndex exist(not allowing to drop a folder inside a folder)
        if (e.dragNode.parent === e.dropNode.parent && e.dragNode !== e.dropNode && e.dropIndex) {
            e.accept();
        }
    }

**Comment by oleksiyo** [comment]
Hi Everyone
I faсed with a similar problem
I would like to cancel dropping for business logic, but faced with error 'TypeError: Cannot read property 'splice' of null'.  my tree like this
`<p-tree #tree
                    selectionMode="single"
                    droppableNodes="true"
                    draggableNodes="true"
                    [validateDrop]="true"
                    [contextMenu]="cm"
                    [value]="companyTree"
                    [(selection)]="selectedNode"
                    (onNodeSelect)="nodeSelect($event)"
                    (onNodeContextMenuSelect)="nodeContextMenuSelect($event)"
                    (onNodeDrop)="onDrop($event)">`
and
`onDrop(event) {
    if (my_condition) {
        event.accept();
    } else {
    ....
    }
}`

and what I have
![image](https://user-images.githubusercontent.com/3090145/54346724-3e696a00-464e-11e9-831f-7b344b5457cc.png)
it throws in tree.js
` UITreeNode.prototype.processNodeDrop = function (dragNode) {
        var dragNodeIndex = this.tree.dragNodeIndex;
        this.tree.dragNodeSubNodes.splice(dragNodeIndex, 1); // ---- this line throws error`

can someone help me?

**Comment by MayankArora20** [comment]
How to capture UITreeNode, I am always getting it as undefined

**Comment by aidacam** [comment]
@cagataycivici, the parent of the dragnode is not accessible if the event is not accepted, can this be fixed?

**Comment by georges-fd** [comment]
> ## My goal is to drag and drop to save level and same level only.
> For example :
> 
> ```
> | - Folder 1
>     | - Node 1
>     | - Node 2
>     | - Folder 1.1
>         | - Node 3
> | - Folder 2
>     | - Node 4
>     | - Node 5
> ```
> 
> Node 1 and 2 can switch places but they can not be dragged to folder 1.1 or Folder 2 Node 1 can not be dragged "over" / "inside" Folder 1.1

Did you fine any solution? this is so absurd this issue been here from 2018, i cant believe that there is no solution for this.

**Comment by mojo2405** [comment]
Hi!
Since this keeps surfacing, I am posting my solution:
HTML:
` <p-tree (onNodeDrop)="node_dropped($event)" .... /p-tree>`
TS:
`node_dropped(e) {
        // If parents are equals
        if (e.dragNode.parent === e.dropNode.parent) {
            e.accept();
        }
        this.iniService.change_state(false);

    }`

Cheers 🍺
