### ISSUE TITLE
Validation Clears When Pressing Enter Editable Datatable

### ISSUE THREAD

**Issue by Jonatino** [primefaces/primeng#3547]
[X] bug report => Search github for a similar issue or PR before submitting

https://www.primefaces.org/primeng/#/datatable/editable

**Current behavior**
Upon pressing enter in a editable column which is required, the validation is cleared while clicking out of the field continues to show validation error.

**Expected behavior**
Validation error should still show up if user hits enter.

**Minimal reproduction of the problem with instructions**

![alt text](http://i.imgur.com/Oq7AhLO.gif)

Click editable field and clear it
Press enter

**What is the motivation / use case for changing the behavior?**
User's might not know that the field is invalid.

**Please tell us about your environment:**
Windows 10 x64 Chrome/FF/IE

* **Angular version:** 2.0.X
Angular 4.1.3

* **PrimeNG version:** 2.0.X
PrimeNG 4.1.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
ALL
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.4.2, ES5

**Comment by lhysrc** [comment]
How to add validation for the editable DataTable? 😂

**Comment by megetron** [comment]
@Jonatino , how did you force datatable validation?

**Comment by thichnguyen** [comment]
How to validation for editTable DataTable?
If data is invalid (null,...), press enter key or tabspace. I wan't to focus this field and to show tooltip.
Please support for me!
