### ISSUE TITLE
SelectItemGroup support for Dropdown

### ISSUE THREAD

**Issue by dhniels** [primefaces/primeng#3548]
[x] feature request 

**Codepen example**
https://codepen.io/moroshko/pen/qbRNjV

It would be nice to have an option to create sections (or styleable, non-selectable items) within .ui-autocomplete-items and .ui-dropdown-items. See this example from [React-Autosuggest](http://react-autosuggest.js.org/) or at their codepen link above.

Screenshot of the example linked above:
![screen shot 2017-08-01 at 1 16 20 pm](https://user-images.githubusercontent.com/7034022/28842853-796b667a-76bc-11e7-9a28-1000151056c3.png)

* **Angular version:** 2.0.X
4.3.2

* **PrimeNG version:** 2.0.X
4.1.2

**Comment by cagataycivici** [comment]
We have this at PrimeFaces;

https://www.primefaces.org/showcase/ui/input/oneMenu.xhtml

Can do similar for p-dropdown as well using new SelectItemGroup API.

**Comment by cagataycivici** [comment]
Scheduled for 5.3.

**Comment by cagataycivici** [comment]
Done!

<img width="173" alt="screen shot 2018-01-29 at 16 10 40" src="https://user-images.githubusercontent.com/686247/35512145-bebb4e52-050f-11e8-8b64-33fe0db0b076.png">

**Comment by ochiers** [comment]
It is very useful if we can choose the group header as an option of the dropdown.

It's like if Germany is a global option.

**Comment by InvincibleViolet** [comment]
can we achieve grouping for p-autocomplete using selectItemgroup?
