### ISSUE TITLE
DataTable with dataKey wont update view properly

### ISSUE THREAD

**Issue by lazarevicivica** [primefaces/primeng#3549]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/RN3sHlBDNGIWE7793Co7?p=preview

**Current behavior**

The bug manifests if dataKey property is set on DataTable, and DataTable has context menu. After opening context menu DataTable wont refresh properly. For instance, if you set selection to empty array table view will not update.

**Expected behavior**
DataTable should behaive the same no matter if dataKey is set or not. 

**Minimal reproduction of the problem with instructions**
Please visit>
http://plnkr.co/edit/RN3sHlBDNGIWE7793Co7?p=preview

* **Angular version:** 4.3.2

* **PrimeNG version:** 4.1.2

* **Browser:** [all | Chrome XX | Firefox XX ]
 
* **Language:** [ TypeScript]

**Comment by lazarevicivica** [comment]
Inside of method DataTable::onRowRightClick(event, rowData) class member **preventSelectionKeysPropagation** is set to true. 

`    onRowRightClick(event, rowData) {
/*... */
        this.preventSelectionKeysPropagation = true;
}
`

I don't understand why is this variable needed at all, there must be some reason, but it is causing problem. There is 

`        if(this.dataKey && !this.**preventSelectionKeysPropagation**) { /*...code to update selection*/
`

inside of set selection(val:any).

Variable **preventSelectionKeysPropagation** should be set to false after context menu is hidden, otherwise selection will not be updated.

**Comment by sviswanathjcet** [comment]
<p-dataTable #dt [value]="cars" [(selection)]="selectedItems" [editable]="true" (onEditInit)="onEditInit($event)" (onEdit)="onEdit($event)" (onEditCancel)="onEditCancel($event)" (onEditComplete)="onEditComplete($event)">
<p-column [style]="{ 'width':'38px', 'text-align':'center' }" selectionMode="multiple">
<p-column field="vin" header="Vin" [editable]="true">
<p-column field="year" header="Year" [editable]="true">

<input type="number" class="ui-inputtext ui-widget ui-state-default ui-corner-all"
[(ngModel)]="rowData[col.field]" [ngModelOptions]="{standalone:true}"
(onchange)="dataTableOnBlur($event, col, rowData, rowIndex, dt)" />


<p-column field="color" header="Color" [editable]="true">
On Change event is not firing . I tried blur but its triggering even though the value not changed. Can you help me on this ?
