### ISSUE TITLE
Multiselect - filter option does not work

### ISSUE THREAD

**Issue by vufrontend** [primefaces/primeng#3550]
[x ] bug report 

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/Qi2Nw2imLpDUF8NJinYw?p=preview

**Current behavior**
Filter option does not work. I think the reason is that team always set default value is true. I found it on your code ` @Input() filter: boolean = true;`

**Please tell us about your environment:**

* **Angular version:** 4.0.0

* **PrimeNG version:** 4.1.0-rc.3

* **Browser:** [all]
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** 8.1.2

**Comment by lebnic** [comment]
Works in 4.2.0-rc.1

**Comment by CoachHockey** [comment]
I'm still not seeing it work in 4.2.0-rc.1.  Possibly unrelated, but the comma-delimited list for selected items in the multiselect does not have a space between items anymore.  Will create a separate issue report with details, however.

**Comment by cagataycivici** [comment]
[filter]="false" to disable it.
