### ISSUE TITLE
Slider broken for big values

### ISSUE THREAD

**Issue by lebnic** [primefaces/primeng#3556]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/REjSm9lapHqU2SurDosx?p=preview

**Current behavior**

Slider used to change a big number does not follows mouse position
Bug already repported, closed, but was not entirely fixed: https://github.com/primefaces/primeng/issues/2145

**Expected behavior**

Slider should slide with ease and follow mouse position when clicked

**Please tell us about your environment:**

Linux

* **Angular version:** 4.0.0

* **PrimeNG version:** 4.0.0

* **Browser:** all
 
* **Language:** all

* **Node (for AoT issues):** `node --version` =   v6.9.4

**Comment by Foszcz** [comment]
same issue

**Comment by cagataycivici** [comment]
Tracked at 2145.
