### ISSUE TITLE
Column Grouping support for Scrollable Table with Frozen Columns

### ISSUE THREAD

**Issue by dean3u** [primefaces/primeng#3559]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
(modified from Column Grouping demo -- https://www.primefaces.org/primeng/#/datatable/colgroup)
[1] http://embed.plnkr.co/Zpq3VA/ (first column frozen)
[2] http://embed.plnkr.co/eRUcbL/ (no columns frozen)

**Current behavior**
In [Plunkr [1]](http://embed.plnkr.co/Zpq3VA/), the first column ("Brand") spans 2 rows, and is frozen.  The "Brand" header is duplicated.
For comparison, [Plunkr [2]](http://embed.plnkr.co/eRUcbL/) contains the same table, but without the first column frozen.

**Expected behavior**
The expected behavior is that the header for the first column ("Brand") only appears once in the table, and stays fixed when scrolling horizontally.

**Minimal reproduction of the problem with instructions**
The problem should be clear visually, i.e., the first column header appears twice.

**What is the motivation / use case for changing the behavior?**
The use case is that a column whose header spans multiple rows can be fixed during horizontal scrolling.

* **Angular version:** 2.0.X
Angular 4.0.0

* **PrimeNG version:** 2.0.X
PrimeNG 4.1.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.3.4

**Comment by kj-johnson** [comment]
We are having the same issue in the same situation.

**Comment by cagataycivici** [comment]
This was not supported so added changes to make it work like;

```xml
<p-dataTable [value]="sales" scrollable="true" scrollHeight="200px" frozenWidth="300px" unfrozenWidth="400px" [style]="{'margin-top':'30px'}">
    <p-header>Column Group and Frozen Columss</p-header>
    <p-headerColumnGroup frozen="true">
        <p-row>
            <p-column header="Brand" rowspan="2"  [style]="{'width':'300px', height:'56px'}"></p-column>
        </p-row>
    </p-headerColumnGroup>
    
    <p-headerColumnGroup>
        <p-row>
            <p-column header="Last Year" colspan="2" [style]="{'width':'250px'}" ></p-column>
            <p-column header="This Year" colspan="2" [style]="{'width':'250px'}"></p-column>
        </p-row>
        <p-row>
            <p-column header="Last Year" [style]="{'width':'125px'}"></p-column>
            <p-column header="This Year" [style]="{'width':'125px'}"></p-column>
            <p-column header="Last Year" [style]="{'width':'125px'}"></p-column>
            <p-column header="This Year" [style]="{'width':'125px'}"></p-column>
        </p-row>
    </p-headerColumnGroup>
    
    <p-column field="brand" [style]="{'width':'200px'}" frozen="true"></p-column>
    <p-column field="lastYearSale" [style]="{'width':'125px'}"></p-column>
    <p-column field="thisYearSale" [style]="{'width':'125px'}"></p-column>
    <p-column field="lastYearProfit" [style]="{'width':'125px'}"></p-column>
    <p-column field="thisYearProfit" [style]="{'width':'125px'}"></p-column>
</p-dataTable>
```
