### ISSUE TITLE
error in ng-cli

### ISSUE THREAD

**Issue by zigzag95** [primefaces/primeng#356]
deprecated-router is now not supported by ng-cli. primeng still have dependencies with router-deprecated

I get this error: zone.js:101 GET http://localhost:4200/vendor/@angular/router-deprecated 404 (Not Found)

**Comment by softEngJason** [comment]
Hi @zigzag95 !  We also ran into this problem earlier today.  We fixed it by npm installing @angular/router-deprecated.  We then added @angular/router-deprecated to our barrels in the system.config.ts.  Consider this a temporary hack for now.

-----------

The potential real fix for this, is to replace the import statement in the splitbutton component with  `import { Router  } from '@angular/router'`

**Comment by zigzag95** [comment]
Would you like I make a PR for this fix?

**Comment by cagataycivici** [comment]
Sure, please. It would be a good pointer. We couldn't check the new router yet, we should to it for next week's beta6.
