### ISSUE TITLE
FileUpload - can't repick file after it was deleted from queue

### ISSUE THREAD

**Issue by maciekstary** [primefaces/primeng#3564]
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
In Advanced Mode, if you pick one file and then cancel it (delete from queue) you cannot re-pick it. You can pick other file but not the one you've just picked.
The problem occurs on Chrome and Edge.
On Firefox works fine.

**Expected behavior**
Cancelling file allows repicking it.

**Minimal reproduction of the problem with instructions**
You can face the issue on offical PG page
https://www.primefaces.org/primeng/#/fileupload

**Please tell us about your environment:**
Angular version: 4.3.2
PrimeNG version: 4.1.2
Browser: [Chrome | Edge] (works on Firefox!)

**Comment by cagataycivici** [comment]
Should be fixed with 4.2.1.
