### ISSUE TITLE
autocomplete panel stay open attribute

### ISSUE THREAD

**Issue by dhniels** [primefaces/primeng#3569]
**I'm submitting a ...**
```
[x] feature request 
```

**Current behavior**
The autocomplete panel opens and closes with the onDropdownClick event on the dropdown button, which is how i use it throughout my app. 

**What is the motivation / use case for changing the behavior?**
It would be nice to have an attribute to keep the autocomplete panel open. In my case, i am essentially setting it up like a ListBox, but that way I can re-use my custom component without having to re-do it as a listbox and maintain consistency for the user since the autocomplete is used in several places. 

screenshot of an example i made:
![screen shot 2017-08-03 at 2 37 37 pm](https://user-images.githubusercontent.com/7034022/28942657-6da984ea-7859-11e7-9d38-6b8609b6ffd7.png)

* **Angular version:** 2.0.X
4.3.2

* **PrimeNG version:** 2.0.X
4.1.2

**Comment by cagataycivici** [comment]
So when should it close? Which behaviour should be disabled when stayOpen is true?

**Comment by dhniels** [comment]
@cagataycivici im thinking it would just stay open all the time - so it wont close. its just acting as a permanently open list, similar to listbox. the onClose or whatever behavior would be disabled, so its always open. does that make sense?

**Comment by dhniels** [comment]
this could apply to both autocomplete and dropdown.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
