### ISSUE TITLE
[Question] How to deploy primeng + angular2 app

### ISSUE THREAD

**Issue by sdmoralesma** [primefaces/primeng#357]
I totally refuse to use [angular2-seed](https://github.com/mgechev/angular2-seed) project for a small/medium sized application.

- How are you guys deploying primeng apps?
- Which simpler options do we have?
- Any best practice to share?

Thank you

**Comment by cagataycivici** [comment]
Hi, please use forum for discussions.  I think webpack is a common solution.

**Comment by SRICHANDANCHINNAM** [comment]
I am deploying my application to Tomcat Server(Putting war file in webapp and running tomcat)... In that i am not able to see p-dropdown arrow icon (pi pi-chevron-down)...

But i am able to see, when running application in local...
