### ISSUE TITLE
p-dataTable emptyMessage is not displayed when the virtualScroll property is set to true 

### ISSUE THREAD

**Issue by sreedevi-koppula** [primefaces/primeng#3571]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/Qi2Nw2imLpDUF8NJinYw?p=preview

**Current behavior**

Datatable is not displaying the emptyMessage 'No records found' when the data is empty and virtualScroll="true"

**Expected behavior**

Datatable should display the emptyMessage 'No records found' when the data is empty and virtualScroll="true"

**Minimal reproduction of the problem with instructions**

Setting the virtualScroll property to true doesn't display the empty message
<p-dataTable #dt name="testTable" [value]="[]" [styleClass]="p-table" scrollable="true" virtualScroll="true" [lazy]="true" [rows]="10" [totalRecords]="0" (onLazyLoad)="loadEvent($event)">

**What is the motivation / use case for changing the behavior?**

When there is no data in the table, the emptyMessage should be displayed

**Please tell us about your environment:**

* **Angular version:** 2.0.X

Angular 4.0.0

* **PrimeNG version:** 2.0.X

primeng 4.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview
