### ISSUE TITLE
It's possible select a row of dataTable with mouseover event

### ISSUE THREAD

**Issue by alejandrohn** [primefaces/primeng#3576]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

**Expected behavior**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [ TypeScript  2.2.1]

* **Node (for AoT issues):** `node --version` =   8.1.4

In the doc primeng it puts for select a row this => 'In single mode, a row is selected on click event of a row' and add the event (onRowSelect) but it is only invoked with the click event, exist any function to select the row with over event?

**Comment by alejandrohn** [comment]
In the doc primeng it puts for select a row this => 'In single mode, a row is selected on click event of a row' and add the event (onRowSelect) but it is only invoked with the click event, exist any function to select the row with over event?

**Comment by cagataycivici** [comment]
It is not possible to select it with hover ,if more users demand it, we'll reconsider.
