### ISSUE TITLE
Tree - Treetable default selection is not updating the checkboxes

### ISSUE THREAD

**Issue by pabhishek09** [primefaces/primeng#3579]
On passing a TreeNode[] variable to the selection attribute in the p-treetable, the checkboxes are not getting updated as per the selection, allowing the same option to be selected twice.

**Comment by vscodeguru** [comment]
#3285 i have the same issue... 
Still no response from them...

**Temp Solution**
so i use p-treetable without check bock & place check box in template body & write my own code for tree checkbox check/uncheck part

**Comment by Priyanka13086** [comment]
i was also facing the same issue. so i have used ng-template and then i have taken input type checkbox and then i have one property "isSelected" in json. and while retrieving values i have looped the json in a recursive way and then compare the values from database and my json then i make the same object found "isSelected" property true.



Sample code:

HTML:   <p-treeTable class="" [value]="allgroups" [(selection)]="selectedFiles2">
            <p-column field="groupName">
              <ng-template let-col let-node="rowData" pTemplate="body">
                <input [(ngModel)]="node.data.isSelected" value="{{node.data.groupName}}" type="checkBox" (change)="onNodeSelection($event)"/>
                
                <span>{{node.data.groupName}}</span>
              </ng-template>

            </p-column>
          </p-treeTable>



JSON: 
export class Group {
    GroupName: string;
   StartDate : string;
    isSelected : boolean;
}


Component:

**Comment by cagataycivici** [comment]
Tree also has the same problem I guess, will be worked on for upcoming 4.3.

**Comment by cagataycivici** [comment]
In checkbox mode, when inititing a tree with preselections, also set **partialSelected**
property on node so that minus icon can be displayed when necessary.

**Comment by jigneshkhatri** [comment]
Found a workaround for pre-selection of multiple check-boxes (programmatically) in primeng Tree. You can find working example here: https://github.com/jigneshkhatri/primeng-treenode-preselect

**Comment by chennoam7** [comment]
Hi,
This is a very nice workaround, however I think that it should be working two way binding without writing many lines of code.

Can you please fix the bug, I'm trying to do the selection from ts too, with no luck.

Thank you for your great control and big effort.

Best regards,
Chen

**Comment by maKSiM89** [comment]
Hey! Do we have an update on this? 

How we can select the node by default ? Only with looping and moving nodes to the selectedNodes for selection attr?
for a large datasets it is a very expensive operation :(

thanks
