### ISSUE TITLE
primeng 'p-fieldset' is not a known element

### ISSUE THREAD

**Issue by dahechjamila** [primefaces/primeng#3580]
Trying to integrate primeng fieldset with angular4 app,
```
    <div>
    	<p-fieldset legend="Godfather I">
    The story begins as Don Vito Corleone, the head of a New York Mafia family, oversees his daughter's wedding. 
</p-fieldset>
    </div>
```
  
i got this error:
```
 Uncaught Error: Template parse errors:
'p-fieldset' is not a known element:
1. If 'p-fieldset' is an Angular component, then verify that it is part of this module.
2. If 'p-fieldset' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
    
    <div>
    	[ERROR ->]<p-fieldset legend="Godfather I">
    The story begins as Don Vito Corleone, the head of a New York ")

```
the primeng version in the package.json file : 4.1.2
any idea please to fix that ?

**Comment by HuseyinTurkmenoglu** [comment]
If you add correctly this;

 `import {FieldsetModule} from 'primeng/primeng';`  

in your @NgModule and it should be ok.

**Comment by dahechjamila** [comment]
The mistake is that i imported the FieldsetModule in the top higher module (app.module.ts).
Thanks.

**Comment by HuseyinTurkmenoglu** [comment]
I've fixed it like this. 

I tell you my solution.

I added  `import {FieldsetModule} from 'primeng/primeng';`  in the app.component.ts and app.module.ts ( necessary which file (for you)) 

And I added  inside the angular-cli.json ;
```
"styles": [
        "../node_modules/primeng/resources/primeng.css",
        "../node_modules/font-awesome/css/font-awesome.min.css",
        "../node_modules/primeng/resources/primeng.min.css",
        "../node_modules/primeng/resources/themes/omega/theme.css",
        "styles.css"
```
Already done for package.json : 
```

    "font-awesome": "^4.7.0",
    "primeng": "^4.1.0-rc.3",
```
And It's working.

**Comment by tsowmya** [comment]
Uncaught Error: Template parse errors:
'p-fileUpload' is not a known element: If 'p-fileUpload' is an Angular component, then verify that it is part of this module.


This is the error when  i am trying to upload the image into an angular form . can anyone please suggest me the approach to fix this problem
