### ISSUE TITLE
Calendar feature request: add property to step to 24th hour in time picker. 23 > 24 > 00

### ISSUE THREAD

**Issue by vegarda** [primefaces/primeng#3581]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

When you step in the hour picker it goes 23 > 00, but I would like for it to 23 > 24 > 00.

**Comment by cagataycivici** [comment]
We'll reconsider it if more users require it, thank you.
