### ISSUE TITLE
p-tabView: style does not work

### ISSUE THREAD

**Issue by qingming418** [primefaces/primeng#3582]
<p-tabView></p-tabView>
How to use 'style' or 'styleClass'  on p-tabView?

**Comment by HuseyinTurkmenoglu** [comment]
If you add correctly this;

import {TabViewModule} from 'primeng/primeng';

in your @NgModule and it should be ok.

And than, you can add  in the index.html : 

 ```
 <link rel="stylesheet" type="text/css"  ref="node_modules/primeng/resources/themes/omega/theme.css" />
 <link rel="stylesheet" type="text/css" href="node_modules/font-awesome/css/font-awesome.min.css" />
 <link rel="stylesheet" type="text/css" href="node_modules/primeng/resources/primeng.min.css" />
```
After, add in the angular-cli.json file;

```
 "../node_modules/primeng/resources/primeng.css",
        "../node_modules/font-awesome/css/font-awesome.min.css",
        "../node_modules/primeng/resources/primeng.min.css",
        "../node_modules/primeng/resources/themes/omega/theme.css",
        "styles.css"
```

Now, you can use.

I hope it helps.

**Comment by cagataycivici** [comment]
{code}
<p:tabView [style]="{'margin-top':'30px'}" styleClass="mytabs"
{code}

**Comment by qingming418** [comment]
thank you

**Comment by KrishnaAnanthi** [comment]
Is it ok to use inline styling like this?
 [style]="{'margin-top':'30px'}"
I tried using styleClass="mytabs" but css added for mytabs is not taking effect

.mytabs{
padding:0
}

Even with important css as not taking
