### ISSUE TITLE
data table column toggler - few fields to be unchecked onload

### ISSUE THREAD

**Issue by amit509** [primefaces/primeng#3583]
Hi All,

While I am using column toggler I want some fields to be unchecked and hide on load but all the fields are checked and shown in table.

How can I achieve this requirement?

Thanks in advance.

**Comment by chinaowl** [comment]
I would also like to know how to do this.

**Comment by ruosifan** [comment]
I am also interested in this.

**Comment by cagataycivici** [comment]
Please use forum for cases like these. Basically if you leave it out from the value, they will be unchecked.
