### ISSUE TITLE
Calendar with time should keep panel open when selecting a day value

### ISSUE THREAD

**Issue by abizit** [primefaces/primeng#3584]
Hello, Im using the Calendar with time as shown in https://www.primefaces.org/primeng/#/calendar. Im wondering if is it possible for the popup to not close when a day is selected.
My code is as follows: 
```
<p-calendar id="expiry" formControlName="ExpirationDate" [showTime]="true"
                                            [readonlyInput]="true" [hourFormat]="24" [monthNavigator]="true"
                                            [yearNavigator]="true" [yearRange]="'1980:2050'"
                                            [styleClass]="'p-dt-picker'"></p-calendar>
```
Using Angular 4+ with Angular cli 1.2.6

**Comment by HuseyinTurkmenoglu** [comment]
Did you do  `[inline]="false" ` for the popup to not close when a day is selected ?

If you didn't, could you try pls ?

I hope its helps.

**Comment by HuseyinTurkmenoglu** [comment]
Did you do `[inline]="true"` ?

If you didn't, could you try please?

I hope it's helps  in finding a solution.

**Comment by abizit** [comment]
@HuseyinTurkmenoglu I did but picker is now no more a popup. I want the picker to be popup just not close when selecting a day. 

Thanks.

**Comment by cagataycivici** [comment]
Why do you need to keep it open?

**Comment by abizit** [comment]
@cagataycivici well i want the user to be able to change the time as well at one go. Right now user needs to select the day and open the picker again to change the time.

**Comment by DavyDeDurpel** [comment]
+1
