### ISSUE TITLE
reset should scroll the scrollable table to top

### ISSUE THREAD

**Issue by sreedevi-koppula** [primefaces/primeng#3585]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/Qi2Nw2imLpDUF8NJinYw?p=preview

**Current behavior**

Suppose the user keeps scrolling towards the bottom of datatable, and somewhere when in the mid of the datatable, the user enters search data in the search box which is going to make a backend call. The results fetched from the backend call are displayed at the current position of the datatable rather than moving the control to the top of the datatable and then displaying the search results.

**Expected behavior**

With lazy loading and virtual scrolling enabled on a datatable, triggering a search should reset the table position to the top and then display the search results.

**Minimal reproduction of the problem with instructions**

1. Enable lazy loading and virutalScroll on the datatable
2. Load the datatable with 1000 entries
3. Scroll to the bottom (somewhere near the bottom) of the table.
4. Type search text in the search box (search box is binded with the table using globalFilter)
5. Typing text in search box makes a backend call and fetches the results.
6. The results are seen to be displayed at the current position of the table, rather than resetting the table position to the top and then displaying the results

* **Angular version:** 4.0.0

* **PrimeNG version:** 4.0.2

* **Browser:** Chrome

 
* **Language:** TypeScript

**Comment by alokkarma** [comment]
facing the same issue ? Angular version  >2  primeNg >2. I thought updating the primeNg version will solve this but seems like issue exist in new version as well.

**Comment by mmlitvin** [comment]
Additional Case: when table is paginated and has multiple pages of data... if user scrolled to the bottom of the 1st page clicking next page should result in the scrollbar to go all the way up so user could see the 1st entry of the 2nd page and not the last entry of the 2nd page

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.

**Comment by tariqzak** [comment]
@sreedevi-koppula @cagataycivici @mertsincan  were you able to resolve this issue? I am also facing this issue with Primeng 7 - Angular 7 version.

**Comment by philipebr** [comment]
I am also facing this issue too with Primeng 7.1.0 - Angular 7 version.

**Comment by philipebr** [comment]
@cagataycivici  @sreedevi-koppula  @mertsincan  @tariqzak 
I am also facing this issue too with Primeng 7.1.0 - Angular 7 version.

**Comment by pedy711** [comment]
This is still a problem. Any solution for it yet?

**Comment by mcrtricolor** [comment]
Still a problem on primeng 12.
