### ISSUE TITLE
Resizable columns not working on DataTable with frozen columns

### ISSUE THREAD

**Issue by mikunis** [primefaces/primeng#3587]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/hriaSkldwmgKY3BpjNK6?p=preview

**Current behavior**
When you try to resize any unfrozen column (resize mode fit) on a DataTable with frozen columns only the table header is resized.

**Expected behavior**
When resizing a column both the table header and the data rows should be resized. 

**Minimal reproduction of the problem with instructions**
The current behavior can be checked on (the primeng version was updated to 4.1.2 from the plunker template)
http://plnkr.co/edit/hriaSkldwmgKY3BpjNK6?p=preview

**What is the motivation / use case for changing the behavior?**
Improve the DataTable component so columns can be resized on tables with frozen columns

* **Angular version:** 4.3.1.

* **PrimeNG version:** 4.1.2

* **Browser:** all
 
* **Language:** all

* **Node (for AoT issues):** `node --version` =

**Comment by HuseyinTurkmenoglu** [comment]
Your Plunker code not work. Can you fix your code, because i want to look your error?

**Comment by mikunis** [comment]
Updated plunker

**Comment by cagataycivici** [comment]
Duplicate 3224
