### ISSUE TITLE
datatable sortableRowGroup incorrect name in demo

### ISSUE THREAD

**Issue by adrianabreu** [primefaces/primeng#3588]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
no need plunk

**Current behavior**
The webpage actually displays the property 'sortableRowGroup' as 'sortableGroupRow'

https://github.com/primefaces/primeng/blob/7640fe2b161535f33e39d057ef20640124ecca6d/src/app/showcase/components/datatable/datatabledemo.html#L1120

**Expected behavior**

Expected to the docs to have the right property name 'sortableRowGroup'

**Comment by cagataycivici** [comment]
Fixed via PR.
