### ISSUE TITLE
Disabled property for PickList

### ISSUE THREAD

**Issue by pierfreeman** [primefaces/primeng#3590]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

It would be nice to have in the PickList component the following properties: 
- disabled
- min/max, for specifying the limits for the target. If exceeding these limits, the subcomponent should disabled itself.

**Comment by loliparra80** [comment]
Yes, and for more filter control, it would be fine if not just control the keyup event, because if clear the text of the filter with the "cut" option of mouse menu or with the cross sign that appears in IE, the filter doens't update.
