### ISSUE TITLE
Optima, Barcelona etc - Mobile menu items are in reversed order

### ISSUE THREAD

**Issue by intergleam** [primefaces/primeng#3594]
[x] bug report

**Current behavior**
Mobile menu items are in reversed order
https://www.primefaces.org/barcelona-ng/#/

non mobile screen: 
![image](https://user-images.githubusercontent.com/2155554/29026655-8af73784-7b85-11e7-9e0c-cc6634ee45e7.png)

mobile screen: 
![image](https://user-images.githubusercontent.com/2155554/29026667-a2287f08-7b85-11e7-8a07-484cc2bbcb78.png)

**Expected behavior**
Mobile menu items are in same order as non-mobile menu

**Minimal reproduction of the problem with instructions**
switch to mobile mode with F12 and see

**Comment by cagataycivici** [comment]
It is by design.

**Comment by intergleam** [comment]
but this is wrong design, that an error
