### ISSUE TITLE
Custom Editor for DataTable cell?

### ISSUE THREAD

**Issue by ishara** [primefaces/primeng#360]
How can Add custom cell editor for DataTable ?

**Comment by Mrtcndkn** [comment]
Do you need something like this http://www.primefaces.org/primeng/#/datatableeditable ?

**Comment by ishara** [comment]
Yes , but I need to add Calendar , Dropdown  and myOwnCell Editor component to DataTable cell.

**Comment by Mrtcndkn** [comment]
Then take a look at this one please http://primefaces.org/primeng/#/datatabletemplating

**Comment by ishara** [comment]
It seems for custom cell rendering solution, I need to add 'p-calendar' component  in to the table cell.

**Comment by cagataycivici** [comment]
<img width="1092" alt="screen shot 2017-01-05 at 22 50 58" src="https://cloud.githubusercontent.com/assets/686247/21695333/fe0ada42-d391-11e6-998d-1dda6525e7de.png">

Ready for 2.0.

**Comment by mukeshkamboj** [comment]
@cagataycivici 
Thanks for the above example.
How we can show the date along with time?

**Comment by mukeshkamboj** [comment]
@MJuma Thanks for your response. Yes this is true. I used it. :-)

**Comment by jtraband** [comment]
I'm having trouble using almost exactly the same code in the treeTable. No error but no display either. Any ideas?

**Comment by deveshsinghal22** [comment]
@cagataycivici I am facing an issue in the same scenario.
As soon As I push a new object in the array, to add a new row. data table, replaces each row with the new added json, which has the json fields like null/blank.

**Comment by cagataycivici** [comment]
Please create a new issue ticket for new cases to be reviewed.

**Comment by nag0538** [comment]
how to save the data to back end after changes made?
