### ISSUE TITLE
Calendar bugs if both showtime='true' and selectionmode='multiple' are chosed.

### ISSUE THREAD

**Issue by TahirMehdi** [primefaces/primeng#3600]
[x] bug report 
I fixed it in https://github.com/primefaces/primeng/pull/3601, please review my pull request

If you try to use  
```
<p-calendar [(ngModel)]="dates" [showTime]="true" selectionMode="multiple" readonlyInput="true"></p-calendar> 

```
time does appear, but if you will try to use handles - primeng crashes. I found out, that the problem is in updateTime() function in calendar.ts. Seems it wasn't updated to handle isSingleSelection(). So i went ahead and updated it.

**Comment by cagataycivici** [comment]
Multiple date selection with time is not supported as it is a confusing UI.
