### ISSUE TITLE
very slow sorting of datatable

### ISSUE THREAD

**Issue by pantonis** [primefaces/primeng#3603]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/Qi2Nw2imLpDUF8NJinYw?p=preview

**Current behavior**
I loaded a table with 1000 rows and three columns (Id, Name, Address). Sorting is extremely slow

**Expected behavior**

**Please tell us about your environment:**

* **Angular version:** 4.2.6

* **PrimeNG version:** 4.1.2

* **Language:** Typescript "~2.2.0"

* **Node (for AoT issues):** `node --version` =   v6.10.3

**Comment by cagataycivici** [comment]
I'd suggest trying lazy loading for huge datasets with pagination.

**Comment by pantonis** [comment]
you mean server side?

**Comment by pantonis** [comment]
1000 is not huge dataset. Why did you close this issue?
