### ISSUE TITLE
Orderlist: drag&drop in Firefox navigates to the value of dragdropscope

### ISSUE THREAD

**Issue by aikrez** [primefaces/primeng#3605]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/OUs44NGWfO7anCv5nqLs?p=preview

**Current behavior**

When you order an item in Firefox, a navigation gets triggered to the value in dragdropScop
In the example the dragdropScope is 'cars', navigation gets triggered to www.cars.com

**Expected behavior**

There should be no navigation

**Minimal reproduction of the problem with instructions**

Order an item

**Please tell us about your environment:**

* **Angular version:** 4.2.6

* **PrimeNG version:** 4.1.0, 4.1.2, 4.2.1

* **Browser:** Firefox 53 32bit
 
* **Language:** TypeScript 2.0.3

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
@Merve7 review please.
