### ISSUE TITLE
Range selection mode for Calendar

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#3609]
Add new selectionMode="range" to calendar to allow selecting a range of dates.

**Comment by Eashwarswamy** [comment]
Hi,
selectionMode="range" - Actually it allows the users to select the date range, But if we use the [showTime]="true" with the **selectionMode="range"** then we cannot update hours and minutes, page url is replacing with the '#'

Example Issue scenario

<p-calendar selectionMode="range" readonlyInput="true" [showTime]="true"></p-calendar>

But If we use only the time without the Range mode then **p-calender** works as expected.

<p-calendar  readonlyInput="true" [showTime]="true"></p-calendar>

Any Help would be grateful.

Thanks,
Eashwar

**Comment by unaor** [comment]
Im also experiencing this bug using "primeng": "^5.0.2",
