### ISSUE TITLE
TabCell after ajax call in primefaces datatable p:cell

### ISSUE THREAD

**Issue by RamiOthman** [primefaces/primeng#3610]
**Current behavior**
I created a datatable with primefaces of which there are two columns each depends on the other. (Column1 = column2 * 2 and column2 = column1 / 2). I used the component "p: celledit", when I modify column1 and I validate, column2 changes automatically, for the update, I used omnifaces with the Ajax.updateRow (table, index) method. Everything is fine, except that I have to use the tab button to navigate between the editable columns, the Ajax call assigns the dom, and so the event no longer works in the edited column. Any suggestion please

**Comment by cagataycivici** [comment]
This is PrimeNG tracker, please use PrimeFaces one instead.
