### ISSUE TITLE
template checkbox in datatable  ,it'is error

### ISSUE THREAD

**Issue by pumpkinp** [primefaces/primeng#3613]
i template checkbox in datatable ,and checkbox bind a array,but i select a check,all check selected,
value is a object,but i console bind array,it is ['[object object]']

http://plnkr.co/edit/j2U254j0SNNmBVn6p8mZ?p=preview

**Comment by HuseyinTurkmenoglu** [comment]
Hi,

I examined your code from plunker. Your checkbox are not working.

I think, you can change your code as follows (  3-7 lines  in your app.template.html)

`<p-column header="Selected" [style]="{'width':'40px'}" selectionMode="multiple"> </p-column>`

**Comment by pumpkinp** [comment]
@HuseyinTurkmenoglu nono ,i want use template because ineed can only select two row

**Comment by cagataycivici** [comment]
Please use forum for cases like these.
