### ISSUE TITLE
Primeng is not working in smart tv(LG) webos browser

### ISSUE THREAD

**Issue by vinodkumar526** [primefaces/primeng#3614]
**This Request regarding browser compatibility issue of primeng on smart-tv**

**Current behavior**
Am using primeng 4.1.1, its working fine with desktop as well as mobile and also in traditional browsers but its not working in smart-tv(tested in possible smart tv's like VU and LG).
Without primeng , angular4.0.0 + html5+bootstrap3+jquery is working fine.

**Expected behavior**
Angular 4.0.0 With primeng 4.1.1 it should work fine in all the browsers.

**Minimal reproduction of the problem with instructions**
usage of javascripts in primeng should support all the browsers even in embedded browsers which smart tv's and devices have.

**What is the motivation / use case for changing the behavior?**
If primeng gives support for those smart-tv browsers then users can access from smart-tv browsers too.

**Please tell us about your environment:**
Development environment:
Windows 8.1 os
Visual studio code
primeng 4.1.1
angular 4.0.0
@angular/cli 1.0.0

User Device:
LG smart Tv
WebOS browser

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Working in all traditional browsers which is mentioned above but not in embedded browsers like smart-tv's have.
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.2.0
es2016

***Node** `node --version` 
Node js: 7.9.0
npm : 5.3.0

**Comment by cagataycivici** [comment]
Does plain Angular work?

**Comment by cetincakiroglu** [comment]
Hi,

We couldn't replicate the issue with the latest PrimeNG release, if the issue still exists please provide a StackBlitz example by using [PrimeNG Issue Template ](https://stackblitz.com/github/primefaces/primeng-issue-template) and re-open the issue.

Regards
