### ISSUE TITLE
installing font awesome screws up Ultima/Barcelona icons

### ISSUE THREAD

**Issue by intergleam** [primefaces/primeng#3615]
```
[x ] bug report 
```
**Current behavior**
installing font awesome screws up Ultima/Barcelona icons

**Minimal reproduction of the problem with instructions**
download Barcelona
`npm i`
install font awesome [according to instruction](https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/include-font-awesome.md)
`ng serve`

![image](https://user-images.githubusercontent.com/2155554/29112729-65fb99a2-7cf7-11e7-92f1-c895368613c2.png)

**Please tell us about your environment:**
win x64

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

angular/animations "^4.2.0",
    angular/common "^4.2.0",
    angular/compiler "^4.2.0",
    angular/core "^4.2.0",
    angular/forms "^4.2.0",
    angular/http "^4.2.0",
    angular/platform-browser "^4.2.0",
    angular/platform-browser-dynamic "^4.2.0",
    angular/router "^4.2.0",
    "chart.js "2.1.3",
    "classlist "^1.0.1",
    "core-js "^2.4.1",
    "font-awesome "^4.7.0",
    "fullcalendar "^3.1.0",
    "intl "^1.2.5",
    "jquery "^3.1.1",
    "moment "^2.17.1",
    "nanoscroller "0.8.7",
    "primeng "~4.1.0",
    "quill "^1.1.8",
    "rxjs "^5.2.0",
    "web-animations-js "^2.2.2",
    "zone.js "0.8.5"

* **Browser:** 
All

**Comment by cagataycivici** [comment]
Font Awesome is not supported in material themes, use material icons instead. Or build font-awesome with a different prefix than .fa.
