### ISSUE TITLE
Edge browser throws 404 error because of missing src-files

### ISSUE THREAD

**Issue by KatzeKahn** [primefaces/primeng#3616]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

The Edge browser throws 404 errors for ALL components because "*.js.map" points to "src"-folder files which are not available.

**Example error:**
```
HTTP 404: NICHT GEFUNDEN: Der Server hat keine Übereinstimmungen für den angeforderten URI (Uniform Resource Identifier) gefunden.
http://{myPath}/primeng/src/app/components/button/button.ts
```
The errors occur since the src-files are simply not there. They are not delivered with the NPM-package.

**Expected behavior**

No errors anymore. ;)

* **Angular version:** 4.0.1

* **PrimeNG version:** 4.0.1

* **Browser:** [Edge] Chrome and Firefox ignore the errors.

**Comment by cagataycivici** [comment]
We don't provide the source files, maybe we should not include map files as well.
