### ISSUE TITLE
programatic element (pre-)selection on datatable fails when using dataKey

### ISSUE THREAD

**Issue by gdj1975** [primefaces/primeng#3618]
I'm submitting 
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/UZiAHEmvc3IldUTHTNyH?p=preview

**Current behavior**
Setting a selected item on a datatable that uses a dataKey does not work in single selction mode. The selection object and the selection keys are not correctly initialized, when selection is a single object instead of an array.

**Expected behavior**
Setting the selected item as object in single selection mode should use the datakey property to check equality.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/UZiAHEmvc3IldUTHTNyH?p=preview

** Issue and Fix
https://github.com/primefaces/primeng/blob/d75ad835f4434cccc02f1fbed644c4340188b7ac/src/app/components/datatable/datatable.ts#L851-L855

            if(this._selection) {
                if (Array.isArray(this._selection)) {
                    for(let data of this._selection) {
                        this.selectionKeys[String(this.objectUtils.resolveFieldData(data, this.dataKey))] = 1;
                    }
                }
                else {
                    this.selectionKeys[String(this.objectUtils.resolveFieldData(this._selection, this.dataKey))] = 1;
                }
            }

* **PrimeNG version:** 4.1.2

**Comment by hugograf** [comment]
I can confirm this error. The fix of "gdj1975" would fix this problem!

**Comment by cagataycivici** [comment]
Got it, thanks.
