### ISSUE TITLE
global filter does not get results from a column template, when its stored as an array. 

### ISSUE THREAD

**Issue by dpcamp** [primefaces/primeng#3621]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/Qi2Nw2imLpDUF8NJinYw?p=preview

**Current behavior**
global filter doesn't appear to be filtering through a column that is using a template that has data nested in an array (not sure if I'm explaining that right)

**Expected behavior**
global filter should return results of rows with columns using templates

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/od72R0?p=preview

**What is the motivation / use case for changing the behavior?**
i need to have data that is nested in an array in my json object to be retrievable through search in my datatable. 

**Please tell us about your environment:**
Windows10/Ubuntu16, Visual Studio Code, npm

* **Angular version:** 2.0.X
4.2.0
* **PrimeNG version:** 2.0.X
4.1.0

**Comment by dpcamp** [comment]
If there are any workarounds, that would be a huge help as well, thanks!

**Comment by cagataycivici** [comment]
I couldn't understand this, sorry.

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
