### ISSUE TITLE
ngIf not respected in DataTable p-column

### ISSUE THREAD

**Issue by Jonatino** [primefaces/primeng#3622]
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

https://plnkr.co/edit/zlAu1TAjRdXfbsp0KVAI?p=preview

**Current behavior**
ngIf is not respected

**Expected behavior**
The row should go away when "deleted" is set to true

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/zlAu1TAjRdXfbsp0KVAI?p=preview

**Please tell us about your environment:**
Windows 10

* **Angular version:** 2.0.X
4.3.3

* **PrimeNG version:** 2.0.X
4.1.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
ALL
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ALL

**Comment by mattscu** [comment]
this has nothing to do with primeng, thats because you're using *ngIf on ng-template...

try  [ngIf] instead of *ngIf (*ngif is syntax sugar for ng-template [ngIf]...)

https://angular.io/api/common/NgIf#syntax
