### ISSUE TITLE
SET value to <p-inputMask> primeng

### ISSUE THREAD

**Issue by ghcsantos1978** [primefaces/primeng#3624]
I want to set a value to <p-inputMask> primeng. The value comes on a back end and i want to populate the component <p-inputMask>, but the value is not populate. I am using the component in template like this

`<div class="col-sm-4">
                <div class="form-group">
                    <label>Data Nascimento:</label>
                    <br>
                    <p-inputMask  mask="99/99/9999" [(ngModel)]="criancaEntity.dataNascimento"></p-inputMask>
                </div>
            </div>
`

anybody can i help me?

**Comment by KatzeKahn** [comment]
Similar problem here: The InputMask gets initialized with the ngModel-value but the onComplete-Event is NOT triggered initially. :(

**Comment by KatzeKahn** [comment]
Any updates on that?

**Comment by henriquemunizc** [comment]
Same problem here. When I don't match the mask, it erases the field, but the value and the validity does not update.

**Comment by igor-shubin** [comment]
We have the same problem. Are there any updates?

**Comment by anton-beetroot-23071996** [comment]
Face the similar issue on primeng: 8.0.3.
I populate ngModel value from backand, value is displayed in UI, but element stay invalid untill I focus and unfocus the element. 
Any updates on this ? The issues looks like very old ...

**Comment by jvmorosini** [comment]
Fixed on 8.0.3

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
