### ISSUE TITLE
KeyCode 13 navigation on editable cells

### ISSUE THREAD

**Issue by EddLeGuerrier** [primefaces/primeng#3625]
**I'm submitting a ...** 

[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already 
[ ] support request => Please do not submit support request here, instead see 

I know that with the 2124 issue, you've added the possibility to navigate to next cell with the "Tab" key. But I don't understand why the "Enter" (chr 13) key does not navigate to next cell too? Or else, a property on the list could ask which keycode is used for navigation?

Personnaly, I'm using a RFID scanner to fill 1 cell and after a scan, the last key that is sent is the enter key. For the moment, I can't navigate to next cell automatically. I want to be able to navigate automatically to next editable cell without hitting the tab key. So choosing which key code will navigate to next cell should be great.

Or a cell fucus (I don't know what cell selection on the road map will do) on any cell we want should be great too.

**Comment by cagataycivici** [comment]
If more users have the same point of view, we'll reconsider. Thank you.

**Comment by nhamzehn** [comment]
We also need this feature, could you please add it?
Thanks in advanced
