### ISSUE TITLE
Export support for column group

### ISSUE THREAD

**Issue by sambanthar** [primefaces/primeng#3626]
datatable export not export table group header

**Comment by HuseyinTurkmenoglu** [comment]
Hi,
I tried to datatable export and using here -£> http://primefaces.org/primeng/#/datatable/export

It exported table group header :
![header](https://user-images.githubusercontent.com/12368632/29158998-c530705a-7db5-11e7-9439-7bee6fe38b1f.png)

May be i understood wrong to you, could you explain  your issue ? ( Please use screenshoot or plnkr.co for good understanding :) )

Have nice a day.

**Comment by HuseyinTurkmenoglu** [comment]
Is that what you mean by saying "Group header"?  -> [DataTable - Column Grouping](http://primefaces.org/primeng/#/datatable/colgroup)

Are you using this ?

**Comment by sambanthar** [comment]
yes

**Comment by HuseyinTurkmenoglu** [comment]
Can you share an example (with Excel tables or a simple code sample)?

**Comment by sambanthar** [comment]
![image](https://user-images.githubusercontent.com/13174217/29765720-ddbdae24-8bf9-11e7-803c-0f5bbce1893e.png)


assume that is my datatable it display correct but when i click csv export button which is provide in the site.

this is the result i get in my excel.


![image](https://user-images.githubusercontent.com/13174217/29765734-e66e5c58-8bf9-11e7-8864-1233a0abf28b.png)

please help me

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.

**Comment by AndaP94** [comment]
Hi, i saw this open question, export csv with header groups? i use primeNg 11.4 on Angular and try to export a table with more groups, is there any example, how i can export it?

![image](https://user-images.githubusercontent.com/35493881/147073170-031bd4d7-c83b-4fe9-bd2a-902870925308.png)

this is the template i want. Thank you
