### ISSUE TITLE
AutoComplete broken with ui-fluid and inputGroup

### ISSUE THREAD

**Issue by rferrerasm** [primefaces/primeng#3629]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

http://plnkr.co/edit/90JYGT6jLHUw4d94PHil?p=preview

**Current behavior**

When used along `ui-fluid` `AutoComplete ` doesn't stretch to full width. Moreover, it doesn't show the placeholder content.

![image](https://user-images.githubusercontent.com/678795/29161360-3d00666c-7db6-11e7-98c2-e71231191df0.png)

**Expected behavior**

It should stretch to the column's width and show the placeholder text.

**Minimal reproduction of the problem with instructions**

Check Plunkr case.

**Please tell us about your environment:**

* **Angular version:** 4.3.1

* **PrimeNG version:** 4.1.1, 4.1.2

* **Browser:** IE 11, Firefox 54, Chrome 60.

**Comment by rferrerasm** [comment]
Forgot to add that it happens when using `inputGroup`s.

**Comment by GrahamHotchkiss** [comment]
Styling issue with inputGroup- (.ui-inputgroup .ui-inputtext:not(:last-child) - would be be fixed if the <div class="ui-autocomplete-panel ...> was placed **before** the input instead of **after** it. Autocomplete functionality still works if I switch the order around in Crome dev tools.

**Comment by rickdroio** [comment]
I've got the same issue in my project. Do you have any solution for that?

**Comment by GrahamHotchkiss** [comment]
Rickdroio - if you are referring to the missing right hand border issue, then my workaround was to close the input group with an empty addon (after the autocomplete):

<span class="ui-inputgroup-addon cust-ui-autocomplete-after"></span>
 .cust-ui-autocomplete-after { min-width: 3px; padding: 0; background: none; border-left: none; }

Not very elegant, but this should be fixed by the primefaces folks not us!

**Comment by gsingara** [comment]
I found issue with Primeng AutoComplete input control,
see the image from Primeng site,the highlighted "div"  rendered inside "p-autocomplete" tag.
![primeauto](https://user-images.githubusercontent.com/39909140/40920197-728389be-6829-11e8-824a-b2d3c1d48bda.png)
But in my Application it is rendered outside of the Tag.check below attached images

![otsite](https://user-images.githubusercontent.com/39909140/40920663-d86dd97c-682a-11e8-8b8e-eaeeb28d4fc5.png)
![otsiteauto](https://user-images.githubusercontent.com/39909140/40920666-dc08c54c-682a-11e8-8d2b-a9200477fe55.PNG)

Any Idea?
