### ISSUE TITLE
[SliderModule] Slider UI works terrible with `step` attribute on big values.

### ISSUE THREAD

**Issue by vadjs** [primefaces/primeng#3633]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/6bF5BAnDdjwm6IJqnS3v?p=preview

**Current behavior**
Slider UI have serious lags during mouse interactions when it has big value ranges and big steps. For example: it has big lags with `[min]='500000' [max]='15000000' [step]='100000'` values.

**Expected behavior**
Have no lags.

**Minimal reproduction of the problem with instructions**

- Open http://plnkr.co/edit/6bF5BAnDdjwm6IJqnS3v?p=preview
- Interact with slider
- You will see the lags

**What is the motivation / use case for changing the behavior?**

Have no lags.

**Please tell us about your environment:** Windows 10(but should represents on all platforms)

* **Angular version:** 4.2.6

* **PrimeNG version:** 4.1.0

* **Browser:** all

 
* **Language:** all

* **Node (for AoT issues):** `node --version` = 8.1.3

**Comment by vadjs** [comment]
I think this bug could be fixed with using Hammer.js library.

**Comment by Foszcz** [comment]
same issue

**Comment by cagataycivici** [comment]
Duplicate at 2145
