### ISSUE TITLE
custom list of objects to dropdown 

### ISSUE THREAD

**Issue by lilling** [primefaces/primeng#364]
dropdown gets only array of objects that has two properties:
`{label: 'Audi', value: 'Audi'}` as strings. otherwise either you get exception `Cannot read property 'label' of undefined` if has'nt got label property, or the ngmodel wont change if the value property is an object

It would be great if the developer will be able to fill the dropdown with custom objects and a property to show to the user. something like value in data table and field in column.

**Comment by brtnshrdr** [comment]
https://github.com/primefaces/primeng/pull/370 should give you that feature if and when it's merged :)

**Comment by lilling** [comment]
@brtnshrdr thx!

do you know if they're going to do this feature?

**Comment by brtnshrdr** [comment]
No idea! But I made a pull request so we can only wait and see!

**Comment by monoflash** [comment]
The same problem:

Template:
```
<p-dropdown [options]="item.rates">
            <template let-element>
              <li style="position: relative">
                <div>111111</div>
              </li>
            </template>
</p-dropdown>
```

Error:
![Error](http://p.jiq.ru/on42+)

**Comment by cagataycivici** [comment]
Fixed for beta10.

**Comment by victorcarvalhosp** [comment]
Can you give some working example? I updated to beta.11 and still got this error...

**Comment by christoferw** [comment]
"fieldLabel" is not in the current master branch available, as far as i could see there have been a merge conflict which moved that fix out again?
@cagataycivici am i right?
