### ISSUE TITLE
PrimeNg and Angular2-Universal conflict

### ISSUE THREAD

**Issue by marcodafonseca** [primefaces/primeng#3643]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ x ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Server error is thrown when refreshing

**Expected behavior**
Page to load

**Minimal reproduction of the problem with instructions**
It seems to be a conflict between "primeng": "^2.0.0" and "angular2-universal": "~2.0.10"

**What is the motivation / use case for changing the behavior?**
PrimeNg does not appear to work with angular2-universal for server-side rendering

**Please tell us about your environment:**
OS: Win10
Package Manager: NPM
Server: IIS

* **Angular version:** 2.0.X
Angular: 2.0.0

* **PrimeNG version:** 2.0.X
PrimeNg: 2.0.6

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Any
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript: 2.3.3

Example error message:
`An unhandled exception occurred while processing the request.

Exception: Call to Node module failed with error: TypeError: element.querySelector is not a function
at DomHandler.findSingle (C:\inetpub\AspNetCoreWebApps\PIMeo\node_modules\primeng\components\dom\domhandler.js:54:24)
at Dropdown.updateDimensions (C:\inetpub\AspNetCoreWebApps\PIMeo\node_modules\primeng\components\dropdown\dropdown.js:154:42)
at Dropdown.ngAfterViewInit (C:\inetpub\AspNetCoreWebApps\PIMeo\node_modules\primeng\components\dropdown\dropdown.js:69:14)
at AppView._View_DataTable19.detectChangesInternal (DataTable.ngfactory.js:1967:59)
at AppView.detectChanges (C:\inetpub\AspNetCoreWebApps\PIMeo\node_modules\@angular\core\bundles\core.umd.js:9566:18)
at AppView.detectContentChildrenChanges (C:\inetpub\AspNetCoreWebApps\PIMeo\node_modules\@angular\core\bundles\core.umd.js:9584:23)
at AppView._View_ColumnHeaders7.detectChangesInternal (ColumnHeaders.ngfactory.js:587:8)
at AppView.detectChanges (C:\inetpub\AspNetCoreWebApps\PIMeo\node_modules\@angular\core\bundles\core.umd.js:9566:18)
at AppView.detectContentChildrenChanges (C:\inetpub\AspNetCoreWebApps\PIMeo\node_modules\@angular\core\bundles\core.umd.js:9584:23)
at AppView._View_ColumnHeaders1.detectChangesInternal (ColumnHeaders.ngfactory.js:244:8)`

Resolution being sought:
If I am doing something wrong or if there is a newer version of PrimeNg that is still compatible with Angular 2 then can I please be advised which is compatible with Angular2-universal? Alternatively, I seek advice on how to lazy-load PrimeNg modules  as I'm pretty new to this stuff. This refresh error only happens on pages using a PrimeNg control. Any other page I can refresh with ease.

**Comment by strings28** [comment]
PrimeNG how requires Angular 4.  Not sure why, but it is required at present. I'm looking for an answer to this myself and will follow up if I find anything.

**Comment by marcodafonseca** [comment]
Thanks, hey. Would really appreciate it if you do.

**Comment by marcodafonseca** [comment]
A work-around I just found... It's not ideal, but it could help... https://stackoverflow.com/questions/40751383/angular-universal-dynamic-imports-for-browser-only

**Comment by dockleryxk** [comment]
@marcodafonseca did you get this work-around to work? I could not

**Comment by marcodafonseca** [comment]
@dockleryxk Actually yes. I did manage, thankfully! :)

I'm going to setup a primeng-mock module eventually so other people with this issue can just reference that for assistance with the issue, but essentially here is what I needed to do:

Firstly, import IsBrowser from angular2-universal
`import { isBrowser } from 'angular2-universal';`

This will be used in an "if" statement later to either import the actual primeng module or to import a mock module which you will need to create.

What you will want to do next is in your file where you create your @NgModule component for your project you will want to take your "imports" object and set it up as an array which will later be assigned to your @NgModule

Next: I created an AbstractMock class as the contents of it will need to be extended into all of your mock modules. This is how the AbstractMock class looks:
`import { ControlValueAccessor } from '@angular/forms';

export abstract class AbstractMock implements ControlValueAccessor {
    private innerValue: any = '';

    private onTouchedCallback: () => void = () => { };
    private onChangeCallback: (_: any) => void = () => { };

    writeValue(value: any) {
        if (value !== this.innerValue) {
            this.innerValue = value;
        }
    }

    registerOnChange(fn: any) {
        this.onChangeCallback = fn;
    }

    registerOnTouched(fn: any) {
        this.onTouchedCallback = fn;
    }
}`

Next: create a mock module for one of the components you are using. For help here I will show the code for a pretty simple and small one. Here is my code for a mock of the Dropdown module:
`import { Component, forwardRef, Input, Output, EventEmitter } from '@angular/core';
import { NG_VALUE_ACCESSOR } from '@angular/forms';
import { AbstractMock } from "./abstract-mock";

export const CUSTOM_INPUT_CONTROL_VALUE_ACCESSOR: any = {
    provide: NG_VALUE_ACCESSOR,
    useExisting: forwardRef(() => DropdownModuleMock),
    multi: true
};

@Component({
    selector: 'p-dropdown',
    template: 'loading...',
    providers: [CUSTOM_INPUT_CONTROL_VALUE_ACCESSOR]
})
export class DropdownModuleMock extends AbstractMock {
    @Input() filter: boolean;
    @Input() options: any[];
    @Input() editable: boolean;
    @Input() autoWidth: boolean;
    @Input() style: string;
    @Input() styleClass: string;
    @Input() placeholder: string;
    @Output() onChange: EventEmitter<any> = new EventEmitter<any>();
}`
**Note** You would need to create an Input\Output property for every attribute your code is referencing. You could add for everything Primeng caters for, but they have so many that I only focused on what I'm actually using...

Now that you have those basics setup you will need to import it into your application.

Here is an example of how that would look:
`
// Create imports array object which will contain all modules to be imported into your application
let imports = [
    UniversalModule, 
    RouterModule.forRoot(AppRoutes),
    FormsModule,
    ReactiveFormsModule,
];

// Add either PrimeNg module or Mock Module to the import array based on whether the code is being run in the browser or from the server

if (isBrowser) {
    let DropdownModule = require('primeng/components/dropdown/dropdown').DropdownModule;

    imports.push(DropdownModule);
}
else {
    let DropdownModuleMock = require('./components/primeng-mocks/dropdown-mock.component').DropdownModuleMock;

    AppDeclerations.push(DataTableColumnMock); // **Quick note about this**: Because the mock module isn't a proper module it must rather be declared as a component as opposed to imported as a module. In this case, I have an 'AppDeclerations' array that houses all of my declerations.
}

// Then setup your application with your setup and get going
@NgModule({
    bootstrap: [AppComponent],
    declarations: AppDeclerations,
    imports: imports,
    providers: AppProviders
})
export class AppModule {
}
`

Hope this can help you :)

**Comment by dockleryxk** [comment]
@marcodafonseca thank you for this great reply, I hope many people stumble upon it because it does help, however, I am using Angular 4, which has universal merged in. Unfortunately there is no 'isBrowser' but only 'isPlatformBrowser' and 'isPlatformServer' and you have to have an injected 'PLATFORM_ID' token, and there is no way to do this in the app module that I know of.

However, I did find a way to split my app module into 3 parts: Browser, Server, and both. I did it like [this](https://github.com/pquarme/cli-universal-demo/tree/master/src/app). Maybe it will help you sometime! Thanks again

**Comment by marcodafonseca** [comment]
@strings28 I have a theory about their Angular 4 and Angular 2 versions being so vastly different... From what I could tell from a brief look (so I could very well be wrong) is that their Angular 4 version is built in Typescript and Angular 2 is actually just straight up javascript with Typescript Typings, so that's why it's JS is so dependent on browser-related objects (window/document/etc...) being available...

This is, however, an assumption on my part...

**Comment by marcodafonseca** [comment]
@dockleryxk Awesome! Will definitely keep this in mind eventually when I upgrade my project to Angular 4. Thanks

**Comment by cagataycivici** [comment]
So I take it as issue resolved?

**Comment by MarkPieszak** [comment]
If possible, the whole library should be using Renderer and not nativeElements themselves (since those only truly exist in the browser).

@cagataycivici
