### ISSUE TITLE
Unresolved bugs in V4.1.3 

### ISSUE THREAD

**Issue by kcsahoo** [primefaces/primeng#3645]
The following issues reporting bugs introduced after V4.0.3 are still unresolved:
Issue #3471
Issue #3466
Because of these issues, dynamic OrderList is not usable and scrollable feature of datatable breaks header alignment if there is a hidden field in datatable columns.
If anyone uses these features, V4.0.3 is the last release in which it worked. So they should not upgrade.
Although PrimeNG team is not prioritizing these issues, I hope the team will resolve it soon.

**Comment by cagataycivici** [comment]
Tracking at those issues.
