### ISSUE TITLE
dropdown in table bug

### ISSUE THREAD

**Issue by lilling** [primefaces/primeng#365]
when dropdown is in table it is sliced byb the borders of the containing cell

![capture](https://cloud.githubusercontent.com/assets/11631465/15274074/6b60e0b6-1ab3-11e6-99d8-19166897a102.PNG)

**Comment by ProvoK** [comment]
same here, with multiline component though

**Comment by cagataycivici** [comment]
You need to set overflow:visible in the column;

```html
<p-column field="content" header="Content" style="{'overflow':'visible'}">
```

**Comment by lilling** [comment]
Tnx. It would be great if it was documented in your site.
בתאריך 16 במאי 2016 12:20,‏ "Çağatay Çivici" <notifications@github.com> כתב:

**Comment by cagataycivici** [comment]
@lilling Sure, we'll add it.

**Comment by opiepj** [comment]
I think you forgot the `[style]`
``` html
<p-column header="content" header="Content" [style]="{'overflow':'visible'}">
```
Otherwise
``` html
<p-column header="content" header="Content" style="{'overflow':'visible'}">
```
will give you:
![image](https://cloud.githubusercontent.com/assets/7416676/18015541/fe2d3894-6b7c-11e6-9cb3-919bed81c692.png)
