### ISSUE TITLE
Row Group with Row expansion. Colspan for row expansion template

### ISSUE THREAD

**Issue by gopalakrishnach** [primefaces/primeng#3651]
Environment
PrimeFaces version: 4.1.3
Does it work on the newest released PrimeFaces version? No
Expected behavior: When p-datatable has Row Group and Row Expansion the colspan of the row expansion template must be total number of visible columns - 1. Since the p-datatable has Row Group the first column is sortfield and in some rows the first column will span more than one row so you must not take this column into colspan of row expansion. We must have better way to set/determine colspan of row expansion template

Actual behavior: Row expansion colspan is taking all visible columns which is leading to expanded row to expand more than row width of p-datatable

Steps to reproduce. Below is my code
`
<p-dataTable #contractsDT class='primeNGDataTable' [value]="contracts" [responsive]="true" rowGroupMode="rowspan" sortField="sector" expandableRows="true"> <p-headerColumnGroup> <p-row> <p-column header="Name" rowspan="2" [style]="{'width':'110px'}"></p-column> <p-column header="Age" rowspan="2"></p-column> <p-column header="Address" [style]="{'width':'100px'}" rowspan="2"></p-column> <p-column header="Age" rowspan="2"></p-column> <p-column header="Father" colspan="2"></p-column> <p-column header="Mother" colspan="2"></p-column> </p-row> <p-row> <p-column header="First Name"></p-column> <p-column header="Last Name"></p-column> <p-column header="First Name"></p-column> <p-column header="Last Name"></p-column> </p-row> </p-headerColumnGroup> <p-column field="name" [style]="{'width':'110px'}"></p-column> <p-column field="age"></p-column> <p-column field="address"></p-column> <p-column [style]="{'width':'100px'}"> <ng-template let-data="rowData" pTemplate="body"> <span style="line-height:2;"> {{data.shortaddress}} </span> <a *ngIf="data.addresses!== null && data.addresses.length > 0" (click)="contractsDT.toggleRow(data)" style="float:right"> <i *ngIf="!contractsDT.isRowExpanded(data)" class="fa fa-chevron-circle-right"></i> <i *ngIf="contractsDT.isRowExpanded(data)" class="fa fa-chevron-circle-down"></i> </a> </ng-template> </p-column> <p-column field="ffname"></p-column> <p-column field="flname"></p-column> <p-column field="mfname"></p-column> <p-column field="mlname"></p-column> <ng-template let-data pTemplate="rowexpansion"> <p-dataTable selectionMode="single" [value]="data.contractPositions"> <p-column field="addrL1" header="Address Line 1" [style]="{'width': '30px'}"></p-column> <p-column field="addrL2" header="Address Line 2" [style]="{'width': '30px'}"> </p-column> <p-column field="city" header="City" [style]="{'width': '30px'}"></p-column> <p-column field="state" header="State" [style]="{'width': '30px'}"></p-column> </p-dataTable> </ng-template> </p-dataTable>
`
![capture2](https://user-images.githubusercontent.com/30936705/29230391-b4687398-7e97-11e7-880c-653221ad11b1.PNG)

![capture](https://user-images.githubusercontent.com/30936705/29230396-baadbec0-7e97-11e7-8d2e-c5f0bf05668a.PNG)

**Comment by gopalakrishnach** [comment]
Hi,

Any comments on this please. We want to know whether this feature will be available in future releases.

**Comment by gopalakrishnach** [comment]
Is this issue still open and is valid? Please respond and let us know.

**Comment by cagataycivici** [comment]
http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview

Not clear, please provide more details, we'll review again and reopen if necessary.

**Comment by gopalakrishnach** [comment]
Hi,

What is not clear man.  

In below screen shot see the highlighted red region. It is going beyond the rows of datatable since for expanded row you are taking colspan as number of visible columns. But we need a way to set the column span. In my case row expander columnspan must be one less than total number of columns since the first column is sorted column

![image](https://user-images.githubusercontent.com/30936705/31791636-151d5fac-b4ce-11e7-8fb7-06b339402d03.png)

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
