### ISSUE TITLE
The Bootstrap theme for the Lightbox component always shows the previous and next arrows. 

### ISSUE THREAD

**Issue by AthenaMarine** [primefaces/primeng#3652]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/Qi2Nw2imLpDUF8NJinYw?p=preview

Plunkr case not required.  Can see the issue on the PrimeFaces component examples page: https://www.primefaces.org/primeng/#/lightbox

**Current behavior**

 1. Choose the Bootstrap theme.
 2. Click on the Watch Video link.
 3. Note the blue previous and next arrows are visible on the overlay for the video. (bug.)

**Expected behavior**

 4. Choose another theme.
 5. Click on the Watch Video link.
 6. Note that the previous and next arrows are _not_ visible on the overlay for the video. (expected.)

**Minimal reproduction of the problem with instructions**

See the current and expected behavior listed above.

**What is the motivation / use case for changing the behavior?**

Videos in the lightbox component should not have previous and next arrows on the overlay.

**Please tell us about your environment:**

Mac OSX 10.12.6
Latest NPM package manager

* **Angular version:** 2.0.X

Angular 4.3.3

* **PrimeNG version:** 2.0.X

PrimeNG Latest and 4.1.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome 60.0.3112.90 (Official Build) (64-bit)
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
CSS
* **Node (for AoT issues):** `node --version` =   
N/A

**Comment by cagataycivici** [comment]
Bootstrap theme is deprecated in favor of Avalon

**Comment by AthenaMarine** [comment]
So what mobile friendly theme do you support instead of Bootstrap?  Avalon does not look mobile friendly.  It needs to pass on the Google Mobile Friendly test site.
