### ISSUE TITLE
sortMode="multiple" does not work

### ISSUE THREAD

**Issue by WildSlinkys** [primefaces/primeng#3653]
1. Go to demo page
2. On multiple sort table click the color column header
3. Then click the brand header.

Sorting should be applied color first, then brand but is not working.

**Comment by cyberrranger** [comment]
you meen https://www.primefaces.org/primeng/#/datatable/sort?

use CTRL to select more than one header

**Comment by WildSlinkys** [comment]
Oh sorry I didn't realise - that should probably be documented more clearly.
