### ISSUE TITLE
Adding "showFileChooser" to the "p-fileUpload" api

### ISSUE THREAD

**Issue by ningacoding** [primefaces/primeng#3656]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**What is the motivation / use case for changing the behavior?**
Sometimes we dont want/need a Button/Panel (of p-fileUpload) to choose a file or files.

Sometimes we need an Image, (profile image for example), or anything to replace the button with another element, images, icons, a custom button, (without default primeng styles), EVENTS, etc.

**Please tell us about your environment:** N/A

* **Angular version:** N/A

* **PrimeNG version:** 4.1.2

* **Browser:** All
 
* **Language:** All

* **Node (for AoT issues):** `node --version` =   N/A

Please add a method to the API of p-fileUpload, something like:

``` 
fileChooser() { // or whatever you whant to name the method
   // this.fileinput -> is the input from p-fileUpload component
    this.fileinput.nativeElement.click(); // tested with IE9/IE10/IE11/Chrome
}
```

You just have to add #fileinput to both inputs (advanced, single) because advanced already have it, but not single.

We also need to access to the error messages, something like:

```
errorMessages() {
    return this.msgs; // this.msgs from p-fileUpload component but only errors
}
```

So we can hide the p-fileUpload component and use the api since another element like:

```
<!-- #fileUploader -> is the p-fileUpload component ussage -->
<div class="something" (click)="fileUploader.fileChooser()"></div>
```

And to know the errors in background ussing **errorMessages()**

**Comment by QiZZ121** [comment]
when i use "p-fileupload" in IE9;
I can't choose files successfully to this component.why? @cagataycivici

**Comment by mdmota** [comment]
https://github.com/primefaces/primeng/issues/5781 @cagataycivici
