### ISSUE TITLE
Add styleClass to message API

### ISSUE THREAD

**Issue by wzengguang** [primefaces/primeng#3659]
```
<p-growl [(value)]="msgs" [styleClass]="thisStyleClass"></p-growl>
```
above,  to display a message;
```
        this.msgs = [];
        this.msgs.push({severity:'info', summary:'Message 1', detail:'PrimeNG rocks'});
        this.msgs.push({severity:'info', summary:'Message 2', detail:'PrimeUI rocks'});
```

but , I think  make  "styleClass" is a property of the Message to custom the style is more convenient.
like that:
```
this.msgs.push({severity:'info', summary:'Message 1', detail:'PrimeNG rocks', styleClass:'thisStyleClass'});
```

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
