### ISSUE TITLE
Growl: Severity classes

### ISSUE THREAD

**Issue by ghost81** [primefaces/primeng#366]
No matter what severity I give to my messages there is no difference in the colors of the text/background.
Example for severity "error":

&lt;p-growl sticky="true"&gt;
...................       
            &lt;div aria-live="polite" class="ui-growl-item-container ui-state-highlight ui-corner-all ui-shadow ui-growl-message-error"&gt;  
.........................
                     &lt;span class="ui-growl-image fa fa-2x ui-growl-image-info fa-close"&gt;</span> 
..........................
    &lt;/p-growl&gt;

**Comment by cagataycivici** [comment]
It depends on theme, what is your theme?

**Comment by ghost81** [comment]
Found the problem....it was just a typo
