### ISSUE TITLE
Clear icon for AutoComplete

### ISSUE THREAD

**Issue by zhangkang1521** [primefaces/primeng#3660]
when selected item contains many character,we need typewrite BackSpace key too many times,it's not convenient!

**Comment by sanketsw** [comment]
I need this feature too. something like <p-autoComplete type="search" ...

**Comment by kevinhaeni** [comment]
I also have need for this.

**Comment by jklapwijk** [comment]
Would be handy!

**Comment by MayerMar** [comment]
Please don't let this request die, a built-in solution would be great

**Comment by dev-amitkmishra** [comment]
Any update on this?

**Comment by Laoujin** [comment]
Building on @sanketsw answer:

```
<p-autoComplete #ref type="search" (onBlur)="onBlur()" ... />
```

```
import {AutoComplete} from 'primeng/autocomplete';


@ViewChild('ref') ref: AutoComplete;

onBlur(): void {
  if (!this.ref.inputEL.nativeElement.value) {
      // Set to null manually:
      this.control.setValue(null);
      this.value = null;
  }
}
```

**Comment by augustobreno** [comment]
I also need this feature. Dropdown does it very well with [showClear]="true".

**Comment by augustobreno** [comment]
There's a Pull Request above to fix this.

**Comment by vochitan90** [comment]
What is the status on this issue? Is it merged to latest release?

**Comment by telion2** [comment]
Whats the status of this ticket? Vuetify supports it for e.g.. It rather annoying if we need to switch to vuetify due to something this trivial. And if there is a Pull Request, why not merge or fix it?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
