### ISSUE TITLE
File upload doesn't show content template in most cases

### ISSUE THREAD

**Issue by mnn** [primefaces/primeng#3661]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
In previous versions we had a fully functional file upload template set up. In current version template with type "content" is not showing by default (when nothing was touched), is only shown when selecting a file when auto is not enabled, is showed during file upload process, but again removed after file upload is completed. This issue is present even when copying your "advanced" example. Array with uploaded files is fine, issue seems to be related just to a template.

**Expected behavior**
Template is being shown as demonstrated on your showcase page (after uploading template is not removed = files are listed).

**Minimal reproduction of the problem with instructions**

Don't know any server accepting upload requests from pluncker (CORS), so I am only pasting code which fails against our server and Apiary as well.

```html
  <p-fileUpload name="demo[]"
                url="...removed..."
                (onUpload)="onUploadExample($event)"
                multiple="true"
                accept="image/*"
                maxFileSize="1000000"
  >
    <ng-template pTemplate type="content">
      <div style="color: red">content</div>
      <ul *ngIf="uploadedFilesExample.length">
        <li *ngFor="let file of uploadedFilesExample">{{file.name}} - {{file.size}} bytes</li>
      </ul>
    </ng-template>
  </p-fileUpload>
```

```ts
  uploadedFilesExample: any[] = [];
...
  onUploadExample(event: any): void {
    for (let file of event.files) {
      this.uploadedFilesExample.push(file);
    }
  }
```

It is mostly your example with only minor changes (names and added div to a template to be able tell when the template is actually being present).

PS: I also tried `<ng-template pTemplate="content">` which is **not** working as well.

**Please tell us about your environment:**

Kubuntu LTS 16.04, IntelliJ IDEA, npm, webpack (I don't think anything is relevant.)

* **Angular version:** 4.1.3

* **PrimeNG version:** 4.1.2

* **Browser:** Chromium 59, Firefox 54
 
* **Language:** TypeScript 2.4.1

* **Node (for AoT issues):** `node --version` = 7.7.3

**Comment by arsonry** [comment]
I'm seeing this issue as well.  As mnn mentioned even if using `<ng-template pTemplate="content">` The issue is still present.  Would be nice to know if there are any plans for this to be addressed.

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview

**Comment by TheParad0X** [comment]
Same problem here. As soon as I add a <ng-template pTemplate type="content"> in my FileUpload, I don't see the files after I selected them. Without it, I see them.

**Comment by TheParad0X** [comment]
Here is a Plunkr: http://plnkr.co/edit/peiWTIlaXCX0RRCNq0Pw?p=preview
When removing the ng-template tags, selected files are shown (before upload)

**Comment by rogatum** [comment]
Hi. If we remove the `<ng-template pTemplate type="content">` wrapper, the preview content shows up.

**Comment by lippomano** [comment]
same issue in PrimeNG version: 4.3.0

**Comment by MikeZyatkov** [comment]
I tried `<ng-template pTemplate="content">`, pass and clear form in my onUploadHandler method. 
It worked.

**Angular version**: 4.3.5
**PrimeNG version**: 4.3.0

```
<p-fileUpload #form name="demo[]" (onSelect)="onFileSelect()" customUpload="true" (uploadHandler)="onUploadHandler($event, form)"
              multiple="multiple" maxFileSize="1000000">
  <ng-template pTemplate="content">
    <ul *ngIf="uploadedFiles.length">
      <li *ngFor="let file of uploadedFiles">{{file.name}} - {{file.size}} bytes</li>
    </ul>
  </ng-template>
</p-fileUpload>
```
```
onUploadHandler(event, form) {
    form.clear();
    for(let file of event.files) {
      this.uploadedFiles.push(file);
    }
  }
```

**Comment by IvanGo82** [comment]
onUpload is never triggered.

I think i found a solution:

https://github.com/primefaces/primeng/blob/master/src/app/components/fileupload/fileupload.ts
line 325

change: 
`....
case HttpEventType.Response: 
....
`
to :
`.... 
 case HttpEventType.Response:
 case http_1.HttpEventType.ResponseHeader: 
....
`

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
