### ISSUE TITLE
ui-fluid pInputText width 100%

### ISSUE THREAD

**Issue by papiroca-tm** [primefaces/primeng#3662]
I can not understand in any way how to make the width of the pInputText 100%, I use the class ui-fluid from the documentation, I try to prescribe the styles but nothing comes out. How to stretch the imputfield by 100% within the container ??

```
<div class="ui-g ui-fluid">
  <div class="ui-g-4">label</div>
  <div class="ui-g-8">
    <input type="text" pInputText [(ngModel)]="someModel" placeholder="..." [disabled]="true">
  </div>
</div>

<div class="ui-g">
  <div class="ui-g-4">label</div>
  <div class="ui-g-8">
    <input type="text" pInputText [style]="{'width': '100%'}" [(ngModel)]="someModel" placeholder="..." [disabled]="true">
  </div>
</div>
```

primeng 4.1.0
angular 4
chrome

**Comment by johnfabian** [comment]
I had that same issue, I don't understand how the ui-fluid really works to be honest but I added my style as such: <input #gb type="text" style="width:50%" pInputText placeholder="Search">

**Comment by diogochuck** [comment]
You must import the InputText module like
`import {InputTextModule} from 'primeng/components/inputtext/inputtext';`
