### ISSUE TITLE
auto change distance between nodes 

### ISSUE THREAD

**Issue by AmanyAbdelkaderK** [primefaces/primeng#3663]
After Collapse , the children spaces didn't hide . the chart doesn't redraw tree to reduce the spaces of collapsed items. 

How can i make this distance reduce when collapse children and increase when expand again?

**Comment by amabdelmongy** [comment]
Any estimation for this fix

**Comment by cagataycivici** [comment]
http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview

Not clear, please provide more details, we'll review again and reopen if necessary.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
