### ISSUE TITLE
Add MessageBox component

### ISSUE THREAD

**Issue by ctrl-brk** [primefaces/primeng#3666]
**I'm submitting a ...**
```
[x] feature request
```

**Current behavior**
ConfirmDialog is a useful component when you asking user a question. But sometimes you only need to bring his attention without making a choice. MessageBox component would fit there.

**Expected behavior**
Create a component similar to ConfirmDialog but only having one button.

**Comment by billfranklin** [comment]
What's the difference in what you want vs a growl?

**Comment by KeithGillette** [comment]
It seems like this feature request could be closed, as ConfirmDialog now has `acceptVisible: boolean` & `rejectVisible: boolean` properties, so it can easily be made into a single-button modal dialog.

Now generalizing it into a `ChoiceDialog` which supports an arbitrary number of buttons would be very useful …

**Comment by Luperco** [comment]
Great, thank you

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by Luperco** [comment]
HI,
thanks, but the problems was already solved, for me, with acceptVisible and rejectVisible properties.

**Comment by cetincakiroglu** [comment]
Hi,

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 
For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
