### ISSUE TITLE
p-dropdown does not display correct label when ngModel variable is an object

### ISSUE THREAD

**Issue by rfmatos** [primefaces/primeng#3667]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Test Case**

http://plnkr.co/edit/iSPkTR5Y581I50bFFnLO?p=preview

**Current behavior**

In p-dropdown if you are using an object for selectedItem there is unreliable behavior in that the displayed label does not always match the selected option.

**Example (see above plunkr for a more complete example)**

component ts:
```
itemList: SelectedItem[];
selectedItem:  SomeObject; // not a string
```

template:
```
<p-dropdown name="classes" [options]="itemList" [(ngModel)]="selectedItem"></p-dropdown>
```

**Expected Behavior**
You should be able to set the ngModel to an object as well as a string.

This expectation seems to be shared by commenters to issue #1010 and #2686 so if this is incorrect then maybe the documentation should be clarified.

**What is the motivation / use case for changing the behavior?**
I have need of setting the dropdown to object values that are maintained in a subscription in a service.  The work around involves maintaining a map of objects and then getting the id value string from the dropdown an then translating that back and forth to the object/id.  It's a bit cumbersome and would be better if I can just set and get the selected item as the object from the p-dropdown.

**Comment by alannsiqueira** [comment]
up

**Comment by blinkxzero** [comment]
This used to work in PrimeNG 2.x.x, and has been keeping me from updating to PrimeNG 4.x.x. 

Any dropdown that is assigned to a string works, but any dropdown I programmatically assign to an object will no longer select the option (although the value in my model is correctly set to the object).

**Comment by cmargulhano** [comment]
same here

**Comment by rfmatos** [comment]
From my description above:
"The work around involves maintaining a map of objects and then getting the id value string from the dropdown an then translating that back and forth to the object/id"

**Comment by cmargulhano** [comment]
I did this:
```
        while(this.itemList.length > 0) {
            this.itemList.pop();
        }
```
instead:

```
       this.itemList = [];
```

and it works.

**Comment by cagataycivici** [comment]
The usage is wrong at plunkr, it does not use SelectItem API, should be;

http://plnkr.co/edit/O19GAi620tNhhT7DpOSz?p=preview

In selectItem api, value must be an object if you are expecting that object bound to NgModel, compare two plunkrs and it'll be clear.

**Comment by rfmatos** [comment]
Yes, I see thanks very much.

**Comment by jschank** [comment]
I had this problem too. I was setting my options on the p-dropdown using the async pipe like this:
```
 <p-dropdown [options]="statuses$ | async" [(ngModel)]="selectedStatus" (ngModelChange)="onStatusChange($event)" optionLabel="name" [autoWidth]="false" [style]="{ width: '200px' }"></p-dropdown>
```

And then in the component.ts, I was assigning an object to the selectedItem value.

It looks to me, like p-dropdown matches object by object identity. So you need to set the selected item to the one of the choice items. Not an object with the same properties. When I used rxjs tap to capture the collection, I was able to get success when I searched the captured collection for the matching ID.

It would be nice, if primeng supported specifying a property to match on. Like it does for a property to display as the label.

**Comment by xodeeq** [comment]
This issue came up for me in prime-ng 16.2.0 - with the dropdown selecting the first option irrespective of the item I programatically assign to the ngModel binded property. I was able to resolve it by removing the dataKey property from my dropdown. An idea which I tried out after reading the final "Follow up" sentence from @jschank 's comment.
