### ISSUE TITLE
Dropdown filter on datatable hidden behind table

### ISSUE THREAD

**Issue by jgrant95** [primefaces/primeng#3668]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/Qi2Nw2imLpDUF8NJinYw?p=preview

**Current behavior**

On a datatable with a dropdown filter, by default the filter list appears to show behind the table itself. However I found 'fixes' saying to put [style]="{'overflow':'visible'}" onto p-column. In doing this another issue arises where the text in each cell inherits this overflow and it means the text overlaps the following columns text. 

**Expected behavior**

The dropdown filter should really just appear and not have to change any styling myself.

**Comment by bomberblue07** [comment]
I have this issue as well

**Comment by bomberblue07** [comment]
@jgrant95 Try adding `appendTo=body` to your p-dropdown in your table. That ended up working for me

**Comment by jgrant95** [comment]
Nice one! Worked for me too. Thanks

**Comment by BenjaminDavidMoore** [comment]
You can also use `[style]="{'overflow': 'visible'}"` on the column
