### ISSUE TITLE
VirtualScroll doesn't update

### ISSUE THREAD

**Issue by GuzzoLM** [primefaces/primeng#3674]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Tryed to make a plunker of this, but I'm not sure if I did right. Other people weren't able to run the app.

**Current behavior**
My table shows the content of an array(watchedEvents) that my component receive via input from a prent component. The parent component watches an Observable from a service in order to update this array.
At the onLazyLoad event, triggered by scroll, I call a function that should update fetch new data from back-end and updates the Observable in the service. The function works, I manage to get the data in the service, but the table doesn't update.

**Expected behavior**
The table should update when the service get the data from back-end. If I change from VirtualScroll to paginated table, I achieve the expected behaviour, so I guess the problem is not in the binding with the parent components.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Updating virtualscroll is not working at all.

**Please tell us about your environment:**

Windows 7, Visual Studio, npm, IIS, MSSQL Server

* **Angular version:** 4.0.0

* **PrimeNG version:** 4.1.3

* **Browser:** [ Chrome ]
 
* **Language:** [ TypeScript 2.2 ]

**Comment by mseemann** [comment]
I guess the problem was introduced in this commit: https://github.com/primefaces/primeng/commit/e0383f8dbb13d4833b4645bf0290822e4de27e13 and is present since verison 4.1.1. The scroll listeners are registered with ngZone runOutsideAngular. The event handlers are native Eventhandlers (e.g. addEventListener is used) In the event handler there is no `ngZone.run` that informs angualr to run it's changedetection. 

Workaround until this problem ist fixed: you can do it in your lazyLoad-Eventlistener:

```
  public lazyload(lazyLoadEvent: LazyLoadEvent) {
    this.ngZone.run( () => {
       make your changes..
    });
  }
```

**Comment by GuzzoLM** [comment]
@mseemann This worked for me, thanks!

I was going to close this issue, but the fact remains that the funtionality is not working properly. I think this issue should stay open for now, while a more consistent solution doesn't come up.

**Comment by cagataycivici** [comment]
Try with 4.2.2 please.
