### ISSUE TITLE
File Upload with forms and reactive forms

### ISSUE THREAD

**Issue by ghost** [primefaces/primeng#3676]
Hi all;
It is such a great chance to end my UI quest journey for Angular here :)))
I have worked on two projects using this awesome library, but always find same problem when I want to upload files with Form data...
I know there are workarounds for that using forking and joining http calls, but it will be nice if it is natively available in primeNG... even in Angular 4, there is no file in forms handling yet.

thanks for considering this (I can tell it is more a feature request than issue)

Happy NG coding ;)

**Comment by AyhamNasser** [comment]
reactive forms with file upload do you have any example or workaround?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
