### ISSUE TITLE
[p-dataTable] interpolated initial global filter value not applied

### ISSUE THREAD

**Issue by fatsu** [primefaces/primeng#3679]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/pmAoZVlpg9SBhiUSAAPJ?p=preview

**Current behavior**
p-dataTable does not apply the global filter value when it is (initially) set with interpolation.

**Expected behavior**
Expect initial global filter to be applied (AfterViewInit).

**Angular version:** 4.2.6

**PrimeNG version:** 4.1.0

**Comment by rtm** [comment]
I have a related problem. My table is filled asynchronously (i.e. `value="data | async"`). If I call `dt.filter` in `ngAfterViewInit`, the table is not ready yet and it crashes. When and how can I call the filter to ensure that the initial criteria are applied when the table is loaded?

**Comment by Abbraxar** [comment]
@rtm you can set filters in declarative way in your template:
``` html
<p-dataTable #dt
  [value]="data | async"

  [filters]="dtState.filters"
  [first]="dtState.first"
  [rows]="dtState.rows"
  [sortField]="dtState.sortField"
  [sortOrder]="dtState.sortOrder"
  [totalRecords]="dtState.totalRecords"
>
</p-dataTable>
```
With this strategy, you just have to set `dtState.filters` in the component (I do this first in ngOnInit) to change filters.
You can of course even use async pipe with your datatable configuration.

**Comment by rtm** [comment]
@Abbraxar Thank you, works like a charm, once I upgraded to 4.2.2 in order to avoid the error where it was trying to access `length` on `this.value` when it was still `null`.

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
