### ISSUE TITLE
[p-dataTable] hard-coded initial global filter value causes exception

### ISSUE THREAD

**Issue by fatsu** [primefaces/primeng#3680]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/QQCD0KiXMYQWVySMP0Jt?p=preview

**Current behavior**
p-dataTable causes exception when using initial hard-coded global filter value.

**Expected behavior**
Expect initial global filter to be applied (AfterViewInit).

**Angular version:** 4.2.6

**PrimeNG version:** 4.1.0

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
