### ISSUE TITLE
Global Filter is not working on Primeng v2.0.0

### ISSUE THREAD

**Issue by sudhakar-sekar** [primefaces/primeng#3681]
In angular2 and typescript, I want to filter the data in all columns in data table global filter using primeng v2.0.0 and Angular v4.0.0. . But, it's not working.
Can anyone help me to resolve this issue.

Not getting any errors, when typing on global filter input text box. No reaction on data table after added on global filter attribute.

- I am getting the data table values from database and display the values using Primeng p-datatable. 
- Used dynamic columns and also used template for some columns.
- I am using one pipe to filter the specific column in datatable, like these [value]="rows | searchFilter: searchField".
- I want to add the global filter for that data table and looked on Primeng data table filter page and done the same like that, but the global filtering is not working, even the separate column filtering using [filter]="true" is also not working.

I am referred the below link,
https://www.primefaces.org/primeng/#/datatable/filter

I am used global filter and the code snippet is as follows,
```
<div class="ui-widget-header" style="padding:4px 10px;border-bottom: 0 none">
            <i class="fa fa-search" style="margin:4px 4px 0 0"></i>
            <input #filteredValue type="text" pInputText placeholder="Global Filter">
</div>
<p-dataTable [value]="rows | searchFilter: searchField" sortMode="multiple" emptyMessage="{{emptyMesage}}" [rows]="10" [paginator]="true" [pageLinks]="3" [rowsPerPageOptions]="[5,10,20]"   (onRowDblclick)="onRowSelect($event)" selectionMode="single" [lazy]="true"[totalRecords]="totalRecords" (onLazyLoad)="loadDataLazy($event)" [globalFilter]="filteredValue">
            <p-column *ngFor="let col of cols" [field]="col.field" [header]="col.header"  
                     [sortable]="col.sortable">
            </p-column>
</p-dataTable>
```

**Comment by cagataycivici** [comment]
Update to PrimeNG 4.1.3 please.

**Comment by sudhakar-sekar** [comment]
Thanks for your reply.... It's not working even 4.1.3 also.
I am updated PrimeNG to 4.1.3 version. But, it's not working?
Same no issues appeared and not filtered data in any column.
