### ISSUE TITLE
Calendars inline with icons overlapping

### ISSUE THREAD

**Issue by LorenaGdL** [primefaces/primeng#3684]
**I'm submitting a ...** 
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/b7szTm?p=preview

**Current behavior**
When using two calendar components inline, with icons enabled, second calendar overlaps with first calendar's icon. If no icons shown, everthing correct. Also correct when stacking.

**Expected behavior**
The calendars should concatenate without overlapping

**Minimal reproduction of the problem with instructions**
Refer to Plunker above

**Please tell us about your environment:** Windows 7, Visual Code, webpack, node.js

* **Angular version:** 4.3.2

* **PrimeNG version:** 4.1.3

* **Browser:** [Chrome | Firefox ] (I guess all)
 
* **Language:** [n/a]

Cheers

**Comment by SinalyVector** [comment]
Same problem using one calendar component and one button inline
