### ISSUE TITLE
Documentation: DataTable with Column Grouping

### ISSUE THREAD

**Issue by billfranklin** [primefaces/primeng#3686]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
Need to update the documentation for the DataTable, especially in the Column grouping section, to warn users to use [tableStyle]="{'table-layout':'auto'}" on the p-dataTable when you need to resize columns when you have more than one header row.

**Comment by cagataycivici** [comment]
table-layout auto is not supported in resize and/or scroll

**Comment by billfranklin** [comment]
so, did you update the documentation on the DataTable component page, or just confirm what was already said?
