### ISSUE TITLE
Clicking close icon on the Confirm dialog is invoking reject action.

### ISSUE THREAD

**Issue by raviganesh12** [primefaces/primeng#3692]
**Current behavior**
When using confirm dialog clicking on close icon is taking the action as reject.

**Expected behavior**
It should just close the confirm dialog.

**Minimal reproduction of the problem with instructions**
The behaviour can be seen in your showcase link below. clicking close icon takes the action as reject.
https://www.primefaces.org/primeng/#/confirmdialog

**What is the motivation / use case for changing the behavior?**
I have a scenario where user is navigating away from a page with unsaved data. we will ask him to select yes / No to save data before navigating away. Yes will save. No will navigate to new page with out saving. clicking close will remain on the current page.

* **Angular version:** 4.3.2

* **PrimeNG version:** 4.1.2

**Comment by cagataycivici** [comment]
Try with 4.2.2 please, should be working with it.
