### ISSUE TITLE
p-multiselect as header filter template on p-datatable triggers sort on click

### ISSUE THREAD

**Issue by mrbalcos** [primefaces/primeng#3694]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
```

**Current behavior**
When using a p-mutliSelect within <ng-template pTemplate="filter"> of a datatable header column, if I click on the checkbox to select, or in some parts of the multiselect control, it triggers sorting of that column. 

[sortable] is set to true

**Expected behavior**
This should not trigger sorting.

* **Angular version:** 4.3.1

* **PrimeNG version:** 4.1.0

* **Browser:** All
 
* **Language:** [ TypeScript 2.3.4 ]

code snippet:
`<p-dataTable [value]="loadSubmissionQueueData" [rows]="10" [paginator]="true" [pageLinks]="5" alwaysShowPaginator="false" [totalRecords]="totalRecords" [lazy]="true" (onLazyLoad)="loadData($event)" resizableColumns="true" columnResizeMode="expand" [loading]="loading" rowHover="true" sortField="queueTimeStamp" sortOrder="-1" #dt>`

`<p-column field="participationStatusDesc" header="Participation Status" [filter]="true" [sortable]="true"><ng-template pTemplate="filter"><p-multiSelect [options]="participationStatusList" [(ngModel)]="selectedParticipationStatusFilter" styleClass="ui-multiselect-custom" (onChange)="displayButtonPanel(true)" maxSelectedLabels="1" [filter]="false" defaultLabel="" id="ddlParticipationList"></p-multiSelect>
                    </ng-template>
                </p-column>`

**Comment by mrbalcos** [comment]
I was able to do a work around by:

adding (click)="preventClick($event) this on the multi-select

`
// prevent trigger of sorting when multi-select was clicked
    preventClick(event: any) {
        event.stopPropagation();
    }
`

**Comment by ghiscoding** [comment]
@mrbalcos this helps but it doesn't fully fix the problem. With your patch, I got it working like 90% of the time with  `p-multiselect` and `p-dropdown`. The dropdown seems to be more problematic as sometime it seems to get stuch, and the only way to make it unstuck is to sort which re-enables the dropdown click. 

The other downside of this is that clicking somewhere else doesn't close the dropdown or multiselect, which is a bit annoying

**Comment by mrbalcos** [comment]
@ghiscoding , yes you are right, the work around I mentioned above is actually causing issues, since when we stopPropagation, at some point, clicking the mutli-select will not display the options anymore.

**Comment by mrbalcos** [comment]
ok, so after sometime, it will stop responding again. so yes, calling optimus prime for help.

**Comment by mrbalcos** [comment]
although i didn't need to do it, it was fixed by adding appendTo="body". I just had to do some work around that area for my specific requirements but it solved the issue

**Comment by ghiscoding** [comment]
hmm could you please provide more details on how you fixed it? I'd like to be able to fix it as well, I find this issue annoying and I would seriously prefer if they change the clickable area to be only the header title instead of the entire area.

**Comment by ghiscoding** [comment]
@mrbalcos would you be able to provide the code that you changed to get this working? Thanks
