### ISSUE TITLE
autocomplete dropdown data bug in example

### ISSUE THREAD

**Issue by Ketec** [primefaces/primeng#3695]
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
https://www.primefaces.org/primeng/#/autocomplete

Noticed a bug - open the dropdown, filter something (like audi), then delete it - the dropdown list does not update.

**Comment by cagataycivici** [comment]
I can't replicate, note that the dropdown implementation behavior is up to you.

**Comment by Ketec** [comment]
This bug is in your own site. Not mine - like on the link above. I can replicate it on multiple browsers
![image](https://user-images.githubusercontent.com/25903372/29550824-8cc4e3ba-8718-11e7-8662-62bf9d391bb7.png)
