### ISSUE TITLE
DataTable resizableColumns

### ISSUE THREAD

**Issue by nmingaleev** [primefaces/primeng#3698]
resizableColumns="true" doesn't work correctly if the table has a ratio width (the resizable column changes it`s size in both directions). 
![default](https://user-images.githubusercontent.com/16058740/29453126-c2913874-8432-11e7-8f85-09c44f2a7a10.png)
![default](https://user-images.githubusercontent.com/16058740/29453183-ea29c3a6-8432-11e7-904b-27f10ab0c836.png)

**Comment by nmingaleev** [comment]
<H2>This demonstrates problem with resizing columns</H2>


<p-dataTable [value]="data" resizableColumns="true" [style]="{'width':'100%'}">
  <p-column header="Delete button">
    <ng-template let-rule="rowData" pTemplate="body" let-i="rowIndex" *ngIf="!rule?.deleted">
      <button (click)="deleteEntry(i)">Delete</button>
    </ng-template>
  </p-column>
  <p-column field="text" header="Text" [style]="{'width': '20%'}">
    <ng-template let-col let-rule="rowData" pTemplate="body" *ngIf="!rule?.deleted">
      <span>{{rule.text}} - Is Deleted:{{rule.deleted}}</span>
    </ng-template>
  </p-column>
  <p-column header="Some text" [style]="{'width': '20%'}">
    
  </p-column>
</p-dataTable>

In the beginning it works fine, but if you change the size of the table, columns start resizing in both directions

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview

**Comment by nmingaleev** [comment]
Here is the code: http://plnkr.co/edit/7RYCgTPIobb7EBjEWscn?p=preview
