### ISSUE TITLE
p-multiSelect issues with ModalModlue from "ngx-modal"

### ISSUE THREAD

**Issue by uzumakro** [primefaces/primeng#3700]
### Auto close functionality doesn't working and after making a selection and closing the p-multiselect, it is not no longer possible to reopen it.

I have inserted a p-multiSelect component on a ngx-modal Window and have faced two issues:

=> The auto close functionality is not working
=> Selecting a value of the p-multiSelect make it impossible to reopen it later.

After debugging a bit i think the problem is coming from that part of your code:

MultiSelect.prototype.bindDocumentClickListener = function () {
        var _this = this;
        if (!this.documentClickListener) {
            this.**documentClickListener** = this.renderer.listen('**document**', 'click', function () {
              debugger;
                if (!_this.selfClick && !_this.panelClick && _this.overlayVisible) {
                    _this.hide();
                }
                _this.selfClick = false;
                _this.panelClick = false;
                _this.cd.markForCheck();
            });
        }
    };

The **documentClickListener** never get called (the modal view propably stop the propagation of that click event). Consequence of that the panelClick variable is not reset, making further opening of the p-mulitselect impossible.

Any idea about how to solve that issue without modifing the source code?

Thank you in advance.

**Comment by cagataycivici** [comment]
Seems it has to be fixed by ngx-modal, not sure why they stop propagation, it will break compatibility with other components.

**Comment by LinaAbdelaziz** [comment]
Hello @uzumakro ,
I know it's an old discussion but I have the exact same issue, have you found any solution? 

Thank you in advance
