### ISSUE TITLE
Filtering  is not working with Virtual scroll (Lazy loading) in PrimeNG data table. Filtering and lazy loading don't work together

### ISSUE THREAD

**Issue by akashdeepg12** [primefaces/primeng#3703]
Filtering  is not working with Virtual scroll (Lazy loading) in PrimeNG data table. Filtering and lazy loading don't work together.

Is there is other alternative solution ?

**Comment by alokkarma** [comment]
what is the issue you are facing can you please elaborate more?

**Comment by akashdeepg12** [comment]
**html** =>
<p-dataTable [value]="carsLarge" scrollable="true" scrollHeight="300px" [rows]="5" virtualScroll="virtualScroll" [style]="{'margin-top':'30px'}" 
    [lazy]="true" [totalRecords]="totalRecords" (onLazyLoad)="loadCarsLazy($event)">
    <p-column field="brand" header="Brand" filter ="true"></p-column>

</p-dataTable>

**component** =>
   loadCarsLazy(event: LazyLoadEvent) {
        //for demo purposes keep loading the same dataset 
        //in a real production application, this data should come from server by building the query with LazyLoadEvent options 
        
       setTimeout(() => {
            if(this.datasource) {
                this.carsLarge = this.datasource.slice(event.first, (event.first + event.rows));
            }
        }, 250);
        
    }


if we enable filter="true",then filtering is not working with lazy load.You can see by enable filter="true"  in below demo link :=>
http://plnkr.co/edit/V3JY3MASoc1Dh2pm5IJO?p=preview

**Comment by cagataycivici** [comment]
You have to filter it yourself at backend in lazy mode.

**Comment by mohanramphp** [comment]
@cagataycivici  I agree but how to pass column reference in the lazy load callback when user filters particular column.

Right now, when user do column search lazy load callback is called with event, how to pass column reference and search value text to the lazy load callback
