### ISSUE TITLE
Custom sorting with sortMode equal multiple breaking sorting arrow indicator

### ISSUE THREAD

**Issue by kbadruka** [primefaces/primeng#3710]
**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/6EYIDSqGd8OAzOrREJXX?p=preview

**Current behavior**

Clicking on Second datatable 'Brand' column does the sorting but sorting arrow's are not changed to show asc/desc order.

**Minimal reproduction of the problem with instructions**

Click on 'Brand' column header in second datatable.

* **Angular version:** 2.4.7

* **PrimeNG version:** 2.0.6

* **Browser:** [all]

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview

**Comment by denniseffing** [comment]
I have the same issue, it seems like the class "ui-state-active" isn't added to the <th> element and the class "fa-sort-asc/dsc" isn't added to the <span> element displaying the arrows.

- **Angular version:** 4.0.0

- **PrimeNG version:** 4.1.1

- **Browser:** [all]

**Comment by ztgluis** [comment]
For anyone running into this, removing the brackets from sortMode will make it work, but custom sort function won't work as described in #664
