### ISSUE TITLE
Calendar - add/support Enabled Dates

### ISSUE THREAD

**Issue by billfranklin** [primefaces/primeng#3712]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

Currently, you cannot provide a list of dates that are the only enabled dates on the Calendar control

**Expected behavior**

Would be able to provide a list of enabled dates, and all other dates would be disabled

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Provide a way of showing a user a Calendar with only the dates that have data enabled.

* **Angular version:** 4.x
* **PrimeNG version:** 4.1.3

**Comment by Mamathadannoor** [comment]
hi,
how to get minutes to round time in calender?.

**Comment by billfranklin** [comment]
@Mamathadannoor, this is not the place for programming help.  Try stackoverflow or the primeng forums

**Comment by cagataycivici** [comment]
You can use disabledDates instead of this, adding enabledDates would complicate things on our side.

**Comment by billfranklin** [comment]
so, you'd rather have us provide every other possible future and past date to the disabledDates property?  Adding enabledDates was easy for us to do to workaround this limitation.

**Comment by rstevens354** [comment]
@billfranklin  have you created this workaround - would you be able to share?

Its crazy that this feature doesnt exist (if disabledDates does)
