### ISSUE TITLE
Lint errors and contribution guidelines

### ISSUE THREAD

**Issue by jamarzka** [primefaces/primeng#3713]
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
Currently there are hundreds of lint errors and no contribution guidelines

**Expected behavior**
No lint errors and included contribution guidelines

I'd like to create a PR to improve the file upload dragover performance but there are a lot of lint issues and inconsistent coding styles. Do you plan on eventually adhering to current tslint.json?

**Comment by cagataycivici** [comment]
Yes, we'll tweat tslint.json according to our own guideline.
