### ISSUE TITLE
Copy mode for Tree drag drop

### ISSUE THREAD

**Issue by DavidDomB** [primefaces/primeng#3717]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/Qi2Nw2imLpDUF8NJinYw?p=preview

**Current behavior**

Tree drag and drop feature always moves the node from source.

**Expected behavior**

I want to have control of the operations on drag and drop feature, e.g. copy a node or just do something in the backend.

This can be achieved using `pDraggable` and `pDroppable` directives, but to use drag and drop, I have to set `draggableNodes="true"` and `droppableNodes="true"`. In the source code `event.preventDefault()` is called on drag or drop, respectively, when this properties are false. 

**Minimal reproduction of the problem with instructions**
Enable drag and drop feature in a tree component. Drag and drop a node into another. The source node is moved to the target node.

**What is the motivation / use case for changing the behavior?**

Be able to control what to do on drag and drop events.

* **Angular version:** 4.2.5
* **PrimeNG version:** 4.1.3

**Comment by Anj21** [comment]
Is this question is resolved, if yes, please provide the solution. i don't want to remove node on drag.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
