### ISSUE TITLE
Dialog position after screen resize

### ISSUE THREAD

**Issue by brian428** [primefaces/primeng#372]
Dialog seems to always appear at whatever the center location is when the component is created. It should probably update it's position if the screen size changes?

For example, open the Dialog page in the showcase, then close the dialog, then resize your browser window, then open the dialog again. Notice that its location is now incorrect (and depending on how much you resize the window, it may be off the screen).

**Comment by cagataycivici** [comment]
This is by design as it is in responsive mode by default. I can't replicate the off screen issue.
