### ISSUE TITLE
Loading status for AutoComplete

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#3724]
Display an icon when a search is in progress.

**Comment by catahoc** [comment]
Hi, @cagataycivici,
you've broken suggestions work with AsyncPipe by this change!
When I write [suggestions]="items | async", first AsyncPipe message (null) puts dropdown into "loading=false" state and second message (actual found items) is ignored. This is specifics of how ASyncPipes are working (they send null message before loading async values)

**Comment by catahoc** [comment]
Created an issue for this: https://github.com/primefaces/primeng/issues/5030
