### ISSUE TITLE
Request: rename DataTable's virtualScroll input name

### ISSUE THREAD

**Issue by vegarda** [primefaces/primeng#3725]
https://github.com/primefaces/primeng/blob/master/src/app/components/datatable/datatable.ts#L297

The name "virtualScroll" is conflicting with other libraries, is it possible to change it to something PrimeNG-like?

**Comment by cagataycivici** [comment]
Why would it do so?

**Comment by vegarda** [comment]
I'm using https://github.com/rintoj/angular2-virtual-scroll in a project for virtual scroll elements other than a table, and it doesn't work together with PrimeNG's DataTable with virtual scroll.

https://github.com/rintoj/angular2-virtual-scroll/blob/master/src/virtual-scroll.ts#L24

**Comment by cagataycivici** [comment]
Should be handled on the other side.
