### ISSUE TITLE
DataGrid Column Freezing and Column Grouping wont work together.

### ISSUE THREAD

**Issue by v8-suresh** [primefaces/primeng#3726]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://plnkr.co/edit/lPU5ZntDj7K7JJORkzWQ?p=preview

**Current behavior**
Column Freezing feature and Column Grouping feature works independently. But as a combination these features giving undesired results. 

**Expected behavior**
Column freezing and column grouping should work together fine.

* **Angular version:** 4.2.6

* **PrimeNG version:** 4.1.0

* **Browser:** 
All

**Comment by cagataycivici** [comment]
Try with PrimeNG 4.2.2 please and set frozen="true" on a headerColumnGroup for the frozen part. So you need to provide two <p-headerColumnGroup> components, one with frozen="true" and one not.
