### ISSUE TITLE
GlobalFilter datatable is not working on PrimeNG 4.1.3

### ISSUE THREAD

**Issue by sudhakar-sekar** [primefaces/primeng#3728]
In angular2 and typescript, I want to filter the data in all columns in data table global filter using PrimeNG v4.1.3 and Angular v2.0.0 . But, it's not working.
Can anyone help me to resolve this issue.

Not getting any errors, when typing on global filter input text box. No reaction on data table after added on global filter attribute.

I am getting the data table values from database and display the values using Primeng p-datatable.
Used dynamic columns and also used template for some columns.
I am using one pipe to filter the specific column in datatable, like these [value]="rows | searchFilter: searchField".
I want to add the global filter for that data table and looked on Primeng data table filter page and done the same like that, but the global filtering is not working, even the separate column filtering using [filter]="true" is also not working.
I am referred the below link,
https://www.primefaces.org/primeng/#/datatable/filter

I am used global filter and the code snippet is as follows,

```
<div class="ui-widget-header" style="padding:4px 10px;border-bottom: 0 none">
            <i class="fa fa-search" style="margin:4px 4px 0 0"></i>
            <input #filteredValue type="text" pInputText placeholder="Global Filter">
</div>
<p-dataTable [value]="rows | searchFilter: searchField" sortMode="multiple" emptyMessage="{{emptyMesage}}" [rows]="10" [paginator]="true" [pageLinks]="3" [rowsPerPageOptions]="[5,10,20]"   (onRowDblclick)="onRowSelect($event)" selectionMode="single" [lazy]="true"[totalRecords]="totalRecords" (onLazyLoad)="loadDataLazy($event)" [globalFilter]="filteredValue">
            <p-column *ngFor="let col of cols" [field]="col.field" [header]="col.header"  
                     [sortable]="col.sortable">
                <template *ngIf="col.field === 'createdDate'" let-col let-data="rowData" pTemplate>
                    <span class="col-date">{{ data[ col.field ] | date : "MM/dd/yyyy" }}</span>
                </template>
                <template *ngIf="objectType === 'data' && col.field === 'status'" let-col let-rowdata="rowData" pTemplate>
                    <button type="button" [style.float]="'center'" pButton class="ui-button-secondary" label="{{rowdata[col.field]}}"
                        [disabled]="rowdata[col.field] == 'Draft'" (click)="toggleStatus(rowdata)"></button>
                </template>
                <template *ngIf="objectType === 'data' && col.field === ''" pTemplate let-col let-rowdata="rowData">
                    <p-toggleButton [style.float]="'center'" onLabel="Start" offLabel="Stop" (click)="toggleButton(rowdata)"></p-toggleButton>
                </template>
                <template *ngIf="objectType === 'Model' && col.field === 'mappeddata'" pTemplate let-col let-rowdata="rowData">
                    <div *ngFor="let data of rowdata[col.field]"> 
                        <a (click)="onClick(event)">{{ data}} </a>
                        </div>
                </template>
            </p-column>
</p-dataTable>
```

**Comment by guntram** [comment]
This one got broken, it worked before the update to 4.1.3

**Comment by guntram** [comment]
I think for me it was caused by the DataTable not being initialized properly due to `*ngIf="myTableDataArray"` set either on the #globalFilter wrapping div and/or on the `<p-dataTable...`-Element!
Removing those `*ngIf`s solved the problem, and the `@Input() globalFilter` field contains the `<input #globalFilter` object again!! :)

**Comment by guntram** [comment]
I think, your problem is the other way round:
I bet your globalFilter field object is initialized, and the @Input globalFilter contains the correct object, but the filter does not find your values due to the *ngIfs...
(maybe)

**Comment by guntram** [comment]
I got to add: I really need the *ngIf="array" because the DataTable crashes if i do not use it and the array is empty (it is filled async).
So I have to give up on the filtering functionality :(

**Comment by bhaidar** [comment]
In my case, I have really a very basic datatable. The global filter is not filtering anything. I am using Primeng 4.1.1.

Any idea how to fix the global filter issue? Thanks

**Comment by guntram** [comment]
removed any ngif to check if it is still not working?

Am 04.09.2017 21:22 schrieb "Bilal Haidar" <notifications@github.com>:

**Comment by bhaidar** [comment]
Actually I posted here with a plunkr. 

Where shall I remove the ngIfs? 

https://github.com/primefaces/primeng/issues/3833

**Comment by guntram** [comment]
sry i just quickly replied per email, didn't check the plunker.
from overviewing your plunk my comment (concerning the ngif) was pretty
stupid :(

2017-09-05 9:06 GMT+02:00 Bilal Haidar <notifications@github.com>:

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=info

**Comment by pankajbhasker** [comment]
<ng-template #tabularleResult>
    <p-dataTable [value]="detailGridResults" [globalFilter]="gb" #dt [rows]="10" [paginator]="true" selectionMode="single" [pageLinks]="3">
        <p-column *ngFor="let field of fields" [field]="field.id" [header]="field.title" [sortable]="field.sorting" [filter]="true">
            <ng-template let-row="rowData" pTemplate="body">
                {{row.tabularGridMap[field.id] }}
            </ng-template>
        </p-column>
    </p-dataTable>
</ng-template>
