### ISSUE TITLE
retrieve p-tree values in ts file 

### ISSUE THREAD

**Issue by seebhoopi** [primefaces/primeng#3739]
Hi all,

i need to access filesTree8 values in ts file for my internal operations. Please help how to do this.

 <p-tree [value]="filesTree8"   (onNodeDrop)="onNodeDrop($event)" (onNodeSelect)="nodeSelect($event)" (onNodeUnselect)="nodeUnselect($event)" selectionMode="multiple" [(selection)]="selectedItems" draggableNodes="true" droppableNodes="true" dragdropScope="files"></p-tree>
    <div>Selected Nodes: <span *ngFor="let file of selectedItems">{{file.label}}</span></div>

Thanks,
Bhoopathi

**Comment by cagataycivici** [comment]
Please use forum for questions.
