### ISSUE TITLE
Using @angular/router-deprecated instead of @angular/router is causing issues in several components

### ISSUE THREAD

**Issue by joe380** [primefaces/primeng#374]
Components which are going to have problems:

- breadcrumb
- contextmenu
- megamenu
- menu
- menubar
- panelmenu
- slidemenu
- tabmenu
- tieredmenu

Is there a way to used these components with new @angular/router?

**Comment by robert-king** [comment]
same with autocomplete, once i added directive Autocomplete. Ended up uninstalling primeng.

**Comment by joe380** [comment]
A quick fix (temporary solution) is to provide also deprecated router:

> in package.json you need both:

- "@angular/router": "^2.0.0-rc.1"
- "@angular/router-deprecated": "^2.0.0-rc.1"

> in bootstrap file you do it like this:

- import { ROUTER_PROVIDERS } from '@angular/router'
- import { ROUTER_PROVIDERS as ROUTER_PROVIDERS_D} from '@angular/router-deprecated'

`
bootstrap(AppComponent, [
     //build in providers
    HTTP_PROVIDERS, ROUTER_PROVIDERS, ROUTER_PROVIDERS_D,
    //app injectables 
    APP_ACTIONS, provideStore(APP_REDUCERS),
    instrumentStore(),
    provide(AppStateStore, {useExisting:Store}),
    devtoolsConfig({
          position: 'bottom',
          visible: true,
          size: 0.3
      }) 
    ])
    .catch(err => console.error(err));
`

**Comment by ajayambre** [comment]
Same issue. Please upgrade to RC1 and remove <code>@angular/router-deprecated</code> dependency.

**Comment by wernerjacobs** [comment]
Experienced the same issue, workaround from joe380 did solve the problem for the moment.

**Comment by ammar91** [comment]
Same issue. 
@joe380 Thanks for the workaround .

However, I'm using Contextmenu so when I right click, the position for menu seems to be off. It's open a bit far right and bottom. Like If I click on first row, it open up in 2nd row and far right (see image below).
 Any thoughts?

![screen](https://cloud.githubusercontent.com/assets/7683970/15429977/ba6ecf94-1ebc-11e6-82c4-5c4d94f9bbd3.png)

**Comment by brian428** [comment]
+1. Mixing the use of the deprecated router with the current one (used by my apps outside of PrimeNG) is _really_ not a fun problem to deal with.

**Comment by IsuruCham** [comment]
After the new update to v.1.0.0-beta.7 (https://github.com/primefaces/primeng/issues/388) , this issue is resolved.
Thanks primeng team.

**Comment by cagataycivici** [comment]
Closing as tomorrow's beta9 even use the new new new router of RC3.
