### ISSUE TITLE
selectedItemLabel for Dropdown

### ISSUE THREAD

**Issue by agilehobo** [primefaces/primeng#3742]
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
At this time the dropdown can only show 'label' after an item is selected even we can define template for dropdown's item.

**Expected behavior**
Ability to use template to display more information than just a label.

**Please tell us about your environment:**

* **Angular version:** 4.x

* **PrimeNG version:** 4.1.3

* **Browser:** [all]

 
* **Language:** [all]

**Comment by nimai** [comment]
I think that's what suggestion #3803  tries to fix. I'm eager to have that feature too.

**Comment by agilehobo** [comment]
@cagataycivici 

A bit eager but do you have an ETA for it? Thanks

**Comment by agilehobo** [comment]
Sad when it will not available in 4.3. Hope it will be scheduled in 4.3.x or 4.SOON :-D

**Comment by markgoho** [comment]
Has anyone found workarounds for this issue in the meantime? Anything even largely hacky would be appreciated.

**Comment by agilehobo** [comment]
@markgoho 

At this time I display detail information below the dropdown. You need to handle when user selects another the drop down item.

HTH

**Comment by kapiladiyecha** [comment]
+1 This would be helpful to translate(i18n) **options values** using `ngx-translate`.

**Comment by broweratcognitecdotcom** [comment]
What a disappointing oversight...

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
