### ISSUE TITLE
dropdown with translation

### ISSUE THREAD

**Issue by hkashlan** [primefaces/primeng#3743]
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ X] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
```
    <p-dropdown [(ngModel)]="reportOption" [options]="reportOptions">
            <ng-template let-rprtOption pTemplate="item">
                {{ rprtOption.label | translate }}
            </ng-template>
        </p-dropdown>
```

I am using the dropdown with translation, 
and it is working with template, but it doesn't reflect the label :(

bellow my code

**Current behavior**
I can not see the translation in the label

**Expected behavior**
able to use translation in the drop down label

* **Angular version:** 4.3.0

* **PrimeNG version:** 4.1.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=info

**Comment by hkashlan** [comment]
Sorry for delay, but what I did, I copied dropdown.ts and this is the line i changed

`<label [ngClass]="{'ui-dropdown-label ui-inputtext ui-corner-all':true }" *ngIf="!editable&&(label !== null)">{{label | translate}}</label>
        `

please note I add the translate pipe line,

is there another way to add the translation,

BTW I can do a test case because **I can't provide template for lebal**

**Comment by Adista9** [comment]
add
 

```
<ng-template let-rprtOption pTemplate="selectedItem">
   {{ rprtOption.label | translate }}
</ng-template>
```
