### ISSUE TITLE
Make expand/collapse icons configurable in DataTable

### ISSUE THREAD

**Issue by preethi29** [primefaces/primeng#3744]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
Expand and Collapse icon in Datatable is defaulted to 'fa-chevron-circle-right' and 'fa-chevron-circle-down'

**Expected behavior**
Expand and Collapse icon can be made configurable. A property can be provided in p-datatable to configure the expanded icon and collapsed icon. The icon can be applicable for both row expansion and row groups.
For example:
`<p-datatable [value]="cars" expandedRows="true" expandedIcon="fa-caret-down" collapsedIcon="fa-caret-right"></p-datatable>`

Pull request: https://github.com/primefaces/primeng/pull/3745

**What is the motivation / use case for changing the behavior?**
Making icons configurable gives more flexibility and customization

**Comment by pantonis** [comment]
That is a very nice option to have
