### ISSUE TITLE
Allow p-toggleButton label and/or icon to be set with only one parameter

### ISSUE THREAD

**Issue by adama357** [primefaces/primeng#3747]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Hello!  p-toggleButton seems to assume I always want a different label _and_ icon.  It would be convenient if I could, say, set label="Section 1", instead of onLabel="Section 1" and offLabel="Section 1".  Same goes for icons.  

Then the "label" parameter would be ignored / overridden by "onLabel" and/or "offLabel".

(Obviously you'd never want to use both "label" _and_ "icon", since that would make it quite difficult to see if the button is on or off; but that would be the programmer's fault, not the button's.)

Thank you for your time!

**Comment by cagataycivici** [comment]
Thank you, if more users will demand it.
