### ISSUE TITLE
Error while running npm start of primeng project 

### ISSUE THREAD

**Issue by Nagasai-Aytha** [primefaces/primeng#3748]
Hi 

I am getting below error while running npm start 

Unhandled Promise rejection: Template parse errors:
'p-header' is not a known element:
1. If 'p-header' is an Angular component, then verify that it is part of this module.
2. If 'p-header' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("e]="licenseData" [rows]="10" [paginator]="true" [globalFilter]="gb" resizableColumns="true">
      [ERROR ->]<p-header>All Vendor Licenses</p-header>
    <p-column field="softwareAssetTag" header="AssetTag"  ["): LicenseTableComponent@19:6 ; Zone: <root> ; Task: Promise.then ; Value: SyntaxError Error: Template parse errors:
'p-header' is not a known element:
1. If 'p-header' is an Angular component, then verify that it is part of this module.
2. If 'p-header' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("e]="licenseData" [rows]="10" [paginator]="true" [globalFilter]="gb" resizableColumns="true">
      [ERROR ->]<p-header>All Vendor Licenses</p-header>
    <p-column field="softwareAssetTag" header="AssetTag"  ["): LicenseTableComponent@19:6

My tsconfig.json file below
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "declaration": false,
    "removeComments": true,
    "noLib": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es6", "es2015", "dom"],
    "sourceMap": true,
    "pretty": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitUseStrict": false,
    "noFallthroughCasesInSwitch": true,
    "typeRoots": [
      "./node_modules/@types",
      "./node_modules"
    ],
    "types": [
      "node"
    ]
  },
  "exclude": [
    "node_modules",
    "dist",
    "src"
  ],
  "compileOnSave": false
}

Could you please help on fixing this issue?

**Comment by HuseyinTurkmenoglu** [comment]
Sometimes, I'm forgetting to add those app.module.ts and my .ts files, may be you too and there occur an error.

Could you check to add correctly primeng components for app.module.ts and your using .ts files? 

**_For example_**
I need to add primeng calendar component,
Firstly I should add in the app.module.ts this -> import {CalendarModule} from 'primeng';
And  I also add  in the app.component.ts this->import {CalendarModule} from 'primeng'; 

I hope it helps,

**Comment by cagataycivici** [comment]
Use forum for questions please.
