### ISSUE TITLE
Date selection needs double click on IE when placeholder property is used

### ISSUE THREAD

**Issue by pnowak2** [primefaces/primeng#3751]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

https://plnkr.co/edit/cyP5LM0cq4KTDKIwCSm2?p=preview

**Current behavior**
Try to select date with IE when placeholder property is defined, just one click to select date

**Expected behavior**
Date is selected, popup dissapears, input is filled in

**Minimal reproduction of the problem with instructions**
Select a date with IE, does not work with one click on day
https://plnkr.co/edit/cyP5LM0cq4KTDKIwCSm2?p=preview

Remove placeholder attribute and try again, this time works properly.

**What is the motivation / use case for changing the behavior?**
This is as bug

* **Angular version:** 4.0.X

* **PrimeNG version:** all
* **Browser:** [IE 10> ]

 
* **Language:** [all]

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.

Please provide a stackblitz case for us using;

https://stackblitz.com/github/primefaces/primeng-issue-template
