### ISSUE TITLE
Datalist index not working

### ISSUE THREAD

**Issue by acba** [primefaces/primeng#3753]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...** 
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Index value is always 0.

**Expected behavior**
It should display the right index, something between 0 and the array length.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/5F2xRNZ6PZlZvS4MWLWc?p=preview

**Please tell us about your environment:**
Windows 7, running with development environment with ng serve.

* **Angular version:** 
```
@angular/cli: 1.3.0
node: 8.1.2
os: win32 x64
@angular/animations: 4.3.1
@angular/common: 4.3.1
@angular/compiler: 4.3.1
@angular/core: 4.3.1
@angular/forms: 4.3.1
@angular/http: 4.3.1
@angular/platform-browser: 4.3.1
@angular/platform-browser-dynamic: 4.3.1
@angular/router: 4.3.1
@angular/cli: 1.3.0
@angular/compiler-cli: 4.3.1

```
* **PrimeNG version:** 4.1.3

* **Browser:**
Windows 7 Chrome Version 60.0.3112.101 (Official Build) (64-bit) 

* **Language:**
Typescript 2.2.2

**Comment by alokkarma** [comment]
Seems like you have missed this function which will trigger onClick:
`onRemoverPessoa(index:any) {
     console.log(index);
   }`
after adding this I am getting the correct index

**Comment by acba** [comment]
I've tried to make it work correctly, but it seems I am missing something.

Can you share a plunkr with the index working ?
I changed a bit my plunkr but index still always shows 0 for me.

http://plnkr.co/edit/II1cdwL9fC0X0VpAedIb?p=preview

**Comment by acba** [comment]
Ok, I realized that the index is relative to the view and not to the data array.
So, if i got a datalist with 1 row per page, it will always be 0. If it's 5 rows per page, then the first page will have indexes from 0 to 4, the next page will go back to 0. And so on.

I got my desired functionality with 
`{{i +  dt.first}}`
