### ISSUE TITLE
Add MultiSelect Separator Option

### ISSUE THREAD

**Issue by TylerBrinkley** [primefaces/primeng#3754]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**What is the motivation / use case for changing the behavior?**
Instead of the default comma separating selected options I'd like to customize it with a different separator, ' | '. Please add an option to specify different MultiSelect separators.

**Comment by cagataycivici** [comment]
Duplicate of https://github.com/primefaces/primeng/issues/4209

**Comment by TylerBrinkley** [comment]
I don't see how that is a duplicate but maybe I just don't understand their request.
