### ISSUE TITLE
Range calendar: highlight is incorrect if start and end dates are in different months

### ISSUE THREAD

**Issue by xiluo58** [primefaces/primeng#3755]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Only start date is highlighted correctly.
<img width="480" alt="screen shot 2017-08-25 at 11 33 16 pm" src="https://user-images.githubusercontent.com/6549391/29721194-c9e92a34-89ee-11e7-8271-d1b6e4c039cd.png">

**Expected behavior**
All dates between start and end should be highlighted

**Minimal reproduction of the problem with instructions**
It can be reproduced on https://www.primefaces.org/primeng/#/calendar

**Comment by Bartosz-D3V** [comment]
+1

**Comment by cagataycivici** [comment]
Duplicate https://github.com/primefaces/primeng/issues/3926
