### ISSUE TITLE
ng-template not working then p-tree data has "type" property

### ISSUE THREAD

**Issue by valakhosravi** [primefaces/primeng#3759]
**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/BksBGUA1iMrEruyK4j0e?p=preview

**Current behavior : acting like normal tree component**

**Expected behavior : templates like it has been expected**

**Comment by Merve7** [comment]
We've tried to replicate with your code in plunker but unable. Please try PrimeNG 6.0.0-alpha.2. If so, please provide a case for us using;
https://stackblitz.com/github/primefaces/primeng-issue-template

**Comment by yigitfindikli** [comment]
Working correctly in  7.0.0-beta.1.
