### ISSUE TITLE
p-inputMask always decorated as valid even if mask is not complete

### ISSUE THREAD

**Issue by KatzeKahn** [primefaces/primeng#3766]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

The p-inputmask component is always marked as valid even the input does not match the mask pattern.

`<p-inputmask styleclass="form-control" ng-reflect-required="false" ng-reflect-mask="99:99:99:99" ng-reflect-slot-char="dd:hh:mm:ss" ng-reflect-auto-clear="false" ng-reflect-input-id="meter_cycle" ng-reflect-style-class="form-control" ng-reflect-disabled="false" ng-reflect-unmask="false" ng-reflect-name="meter_cycle" ng-reflect-is-disabled="false" class="ng-valid ui-inputwrapper-filled ng-touched ng-dirty" ng-reflect-model="01:hh:mm:ss">
    <input pinputtext="" class="form-control ui-inputtext ui-corner-all ui-state-default ui-widget ui-state-filled" ng-reflect-ng-class="form-control" id="meter_cycle" type="text" name="meter_cycle">
</p-inputmask>`

**Expected behavior**

Decorate component with ng-valid if mask is not complete.

* **Angular version:** 4.1.0

* **PrimeNG version:** 4.1.3

**Comment by cagataycivici** [comment]
We'll reopen if more users demand it.

**Comment by KatzeKahn** [comment]
Why do you close it? The sense of an input mask is to prevent incorrect user inputs. This also includes checking the mask being completed. I understand completeness must not be mandatory (e.g. license tags can be different: "A-BB1234" vs. "A-BB12").

BUT, there are clear uses cases where completeness is crucial like credit card numbers or the IBAN. A good solution would be to add an @Input to make completeness check controllable.

**Comment by PabloGBello** [comment]
I have the same problem. The input is always marked as valid. You have to reopen this issue...

**Comment by gspeach** [comment]
I have to agree here that you should be able to mark these fields as invalid. It kind of breaks the uniform behaviour of invalid field behaviour. If someone is submitting my form they have no idea it's because of the mask isn't complete because it still shows as valid visibly.

**Comment by malbarmawi** [comment]
any update ??

**Comment by malbarmawi** [comment]
At the first time the p-inputMask  work as expected I can see the state is invalid but after I enter any value of clear exsisting value the state still valid

**PrimeNG version**: 5.2.4

**Comment by madvlad** [comment]
Reopen this. It's still a bug and it makes your inputMask element unusable.

**Comment by hemendraub** [comment]
Fix this issue.

**Comment by madvlad** [comment]
Reopen this issue. @cagataycivici

**Comment by hepple** [comment]
I can't use this control in this state

**Comment by talipovdaniyar** [comment]
What the current status of this issue?

**Comment by jsilveira2** [comment]
I found an interim solution via scss, I am using it, but I think it would be interesting for primeng to work for this validation to work on its own.

But for those who need an interim solution you can use this:

```
p-inputMask.ng-invalid.ng-touched {
    input {
        border: 1px solid #e17576;
    }
}

p-inputMask.ng-valid.ng-touched {
    input {
        border: 1px solid green;
    }
}
```

**Comment by midhunadarvin** [comment]
I am still getting this Issue. If we set a formControl to the p-inputMask element. It is shown as valid even if the input is not complete.

**Comment by michaelakin** [comment]
I am getting this problem also.  Please fix.

**Comment by michas84** [comment]
Please fix.

**Comment by adeelbhaloo-tag** [comment]
this is still not working! Primeng ver 15.2. Please reopen this issue

**Comment by Reshaw1** [comment]
This issue is still relevant in 2025, this is just ridiculous at this point.
