### ISSUE TITLE
Drag support to InputSwitch

### ISSUE THREAD

**Issue by jisqaqov** [primefaces/primeng#3768]
I would like to suggest new component Slide toggle. It is an on/off control that can be toggled via clicking or dragging. The slide-toggle behaves similarly to a checkbox, though it does not support an indeterminate state. For example visit https://material.angular.io/components/slide-toggle/overview

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
