### ISSUE TITLE
Hiding Upload and Cancel button with auto="false" => enable upload automatically

### ISSUE THREAD

**Issue by agilehobo** [primefaces/primeng#3769]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
I define FileUpload component to use my own button to upload file and it works fine. Then I want to hide Upload and Cancel button as below but the file is uploaded **automatically** after I choose one.

```
        <p-fileUpload
                maxFileSize="1000000"
                accept="image/*"
                name="picture"
                auto="false"
                showUploadButton="false"
                showCancelButton="false"
                customUpload="true"
                (uploadHandler)="upload($event)"
                #fileUpload></p-fileUpload>
```
If I remove 'auto="false"', Upload and Cancel button appears.

**Please tell us about your environment:**

* **Angular version:** 4.3.5

* **PrimeNG version:** 4.1.3

* **Browser:** [all ]

 
* **Language:** [all]

**Comment by cagataycivici** [comment]
[auto]="false"

**Comment by ajcastro** [comment]
https://github.com/primefaces/primeng/issues/3487#issuecomment-317217452
