### ISSUE TITLE
HTML support in tooltip

### ISSUE THREAD

**Issue by PhilippRoessner** [primefaces/primeng#377]
Is it possible to insert a linebreak inside of the tooltip? Maybe render html directly?

thx!

**Comment by cagataycivici** [comment]
HTML is supported now

**Comment by privet56** [comment]
html support is broken after implementing
https://github.com/primefaces/primeng/issues/1558
is it planned to support html again?

**Comment by privet56** [comment]
a possible solution to support html in tooltip could be the usage of DomSanitizer.
Example: this Pipe uses DomSanitizer https://github.com/privet56/ng2Goodies/blob/master/sani.ts

**Comment by severinkehding** [comment]
i would love to see the html support back as well :(

**Comment by cagataycivici** [comment]
Available now

**Comment by ctrl-brk** [comment]
Would be nice to have the same for the DataTable emptyMessage

**Comment by cagataycivici** [comment]
Better to create a named template for it. Please file a new issue with this request.

**Comment by ctrl-brk** [comment]
Already did ;)
https://github.com/primefaces/primeng/issues/2395
