### ISSUE TITLE
p-inputMask: Improve horizontal cursor key navigation

### ISSUE THREAD

**Issue by ghost** [primefaces/primeng#3773]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

If you navigate through the input field by using the left/right cursor keys, the cursor also considers the position of the fixed characters (i mean those where you don't enter text). So you need to hit the keys a lot more than necessary.

**Expected behavior**

It would be much more useful if the cursor only jumps to the actual input positions and skips the fixed text.

**What is the motivation / use case for changing the behavior?**

It would futher improve the usability of the input mask. At the moment, the input mask doesn't behave very solid.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
