### ISSUE TITLE
RTL support for Steps

### ISSUE THREAD

**Issue by eliafengar** [primefaces/primeng#3774]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/na4oMR?p=preview

**Current behavior**
p-steps doesn't respect 'rtl'

**Expected behavior**
p-steps to respect 'rtl' and switch the direction of the numbers

**Please tell us about your environment:**
Windows, Visual Studio Code, npm, Apache Server, Chrome debugging

* **Angular version:** 4.0.0

* **PrimeNG version:** 4.0.3

**Comment by FawzyMokhtar** [comment]
You can fix this by adding the `display: flex` on the `ul` that holds the steps.

```scss
body .ui-steps {
  ul[role='tablist'] {
    display: flex;
  }
}
```
