### ISSUE TITLE
confirm-dialog: icon next to message taking up room while icon parameter = null

### ISSUE THREAD

**Issue by L-VE** [primefaces/primeng#3776]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/XKPGsExv1yCiripKKvyU?p=preview

**Current behavior**

When not specifying an icon to display next to the message, it still takes up space (margin) even though no icon is displayed (due do .fa) 
`<i [ngClass]="'fa'" [class]="icon"></i>`

**Expected behavior**

When not specifying an icon to display next to the message, the \<i> tag should not even be displayed or defined.

**Minimal reproduction of the problem with instructions**

Check out the examples in the plunkr specified above.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Ubuntu, Intellij

* **Angular version:** 2.0.X

4.2.6

* **PrimeNG version:** 2.0.X

4.1.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Try with 4.2.2 please.
