### ISSUE TITLE
Hi Team,

### ISSUE THREAD

**Issue by RenukadeviV** [primefaces/primeng#3779]
Team,

When I try to select multiple items from listbox by clicking the label (not the checkbox) the selection does not persist and only that particular item gets selected. But this works perfectly when I select the checkbox.

I would like to select items by clicking the label as well and it should work just like checking on the checkbox.

I'm using primeng 4.1.3 for my application.

Could you please respond at the earliest?

Thanks &Regards,
 Renukadevi V

**Comment by ASK83** [comment]
I came across this also. As they explained this is by design and if you set the property [metaKeySelection]="false" on p-listbox you can achieve your desired behavior.

**Comment by RenukadeviV** [comment]
Thanks a lot!! It is working!!
