### ISSUE TITLE
Change InputMask component to a directive

### ISSUE THREAD

**Issue by sousajunior** [primefaces/primeng#3782]
**I'm submitting a ...**
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Expected behavior**
Today, inputMask its a component and this limit your use, because you can not put mask on whatever you want.
I think that will be a great change if the inputMask be a directive same as inputText, because you'll can use it on inputs, calendars, auto-complete, list-box, multi-select ...  

Another thing to consider is that you cannot put a mask as dd/mm/yyyy in calendar, you are limited to use calendar chooser to set date, and for most users its necessary to put date without worry yourself insertion of '/' character manually.

It's only a idea, but if someone think equals, give a like to this feature request.

**Comment by augustoeliezer** [comment]
**All inputs** needs a directive to define a mask.

Example the calendar with [mask](https://www.primefaces.org/showcase/ui/input/calendar.xhtml)

**Comment by tiagodws** [comment]
Such an important feature for an UI component library. 

Could we please at least know if this is going to be done in the foreseeable future, or if there's no chance of that happening, @cagataycivici ? :)

**Comment by xandecf** [comment]
Any update on this issue?  @cagataycivici

**Comment by mikaelboff** [comment]
any updates on this?

**Comment by mikaelboff** [comment]
@cagataycivici

**Comment by jackstuard** [comment]
> **All inputs** needs a directive to define a mask.
> 
> Example the calendar with [mask](https://www.primefaces.org/showcase/ui/input/calendar.xhtml)

this sounds perfect, primefaces has implemented.

**Comment by ThomasDecavele** [comment]
> 
> 
> **All inputs** needs a directive to define a mask.
> 
> Example the calendar with [mask](https://www.primefaces.org/showcase/ui/input/calendar.xhtml)

Primefaces calendar demo url was changed to: [https://www.primefaces.org/showcase/ui/input/calendar/calendar.xhtml](https://www.primefaces.org/showcase/ui/input/calendar/calendar.xhtml) 
That example named "Mask" is indeed what we're looking for to be implemented at PrimeNg as well. 

Hopefully it'll get implemented soon. For now we only have hacky solutions. 

Or maybe I can try ['racoon-mask-primeng' from @shogogan](https://github.com/shogogan/racoon-mask).

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by DaSchTour** [comment]
Well inputMask is still a component and not a directive. So this is not solved :(

**Comment by tristanjayvirtudazo** [comment]
What is the status of this feature?
