### ISSUE TITLE
Calling Add or AddAll method of the MessageServices should not remove previous messages

### ISSUE THREAD

**Issue by UrzaUrza** [primefaces/primeng#3784]
**I'm submitting a ...**
```
[x] bug report
[x] feature request
[ ] support request
```
Hi,
I don't know if it's a bug or if the current behavior is expected.

**Current behavior**
When calling messageService.Add(myMessage), previous added messages are removed

**Expected behavior**
When calling messageService.Add(myMessage), previous added messages are kept. So we could add messages from differents services.

**Workaround/Hack**
Modify growl.js (line 34) and messages.js (line 25).
Replace:
```
this.subscription = messageService.messageObserver.subscribe(function (messages) {
	if (messages instanceof Array)
		_this.value = messages;
	else
		_this.value = [messages];
});
```
With:
```
this.subscription = messageService.messageObserver.subscribe(function (messages) {
	if(!_this.value) {
		_this.value = [];
	}
	if (messages instanceof Array)
		_this.value.push.apply(_this.value, messages);
	else
		_this.value.push(messages);
});
```

**Please tell us about your environment:** Windows 7, Npm, Node

* **Angular version:** 4.3.3

* **PrimeNG version:** 4.2.0-rc.1

* **Browser:** [all]

 
* **Language:** [TypeScript]

**Comment by superamadeus** [comment]
The solution provided still doesn't result in the growl messages appearing as expected. Either the messages all disappear at the same time, or they never disappear (as far as my testing can tell).

**Comment by UrzaUrza** [comment]
That's working in my project, maybe because i've set growl messages to stay until user dissmiss it:
<p-growl [sticky]="true"></p-growl>

**Comment by markusu49** [comment]
Confirmed. `messageService.addAll` displays all messages at the same time, `messageService.add` overwrites the previous one. Another workaround for an action that emits multiple messages very quickly might be to collect them somewhere and use `addAll`.

**Comment by UrzaUrza** [comment]
Thank cagataycivici for the fix, it seems to work well.
