### ISSUE TITLE
Datatable column object support

### ISSUE THREAD

**Issue by Ketec** [primefaces/primeng#3785]
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Can only  filter/sort column if the field value is a simpel datataype - string/number.

**Expected behavior**
Allow use of objects:
`{userinfo: {id: 123, name: test}}`
In column conf `field: userinfo`.
With optional displayField value:
`displayField: name`
If displayField is present, filter and sort should also use displayField value instead of the whole object.

Object use like that would allow accessing vital ID info on row select etc actions but visually it would show the name to the user.

**Comment by cagataycivici** [comment]
There is sortField and filterField to do this other way. field can be "userInfo.id" as well
