### ISSUE TITLE
Separate datatable checkcolumn and row selection.

### ISSUE THREAD

**Issue by Ketec** [primefaces/primeng#3787]
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
To use checkcolumn, you need to enable multiselect. This also allows selecting multiple items by clicking on the row.

**Expected behavior**
To be able to select multiple rows with a checkbox (mass delete etc) but only one row when row is clicked (to open some dialog or edit window etc).
Currently the closest way to achieve this is to use meta selection - but this still allows using CRTL key to select multiple and does not allow deselecting the row.

A way to separate them or disable meta key selection ( metaKeySelection does not work here - it allows selecting multiple all the time, but instead would need reverse - never allow multiple selection even if meta key is pressed - but allow it if checkcolumn is used).

**Comment by cagataycivici** [comment]
WE'll reconsider if more users demand it, thank you.
