### ISSUE TITLE
Allow the binding of contextmenu event on tree nodes even without a primeng contextmenu attached to the tree.

### ISSUE THREAD

**Issue by DefJunx** [primefaces/primeng#3789]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Right now, as far as I could understand by looking at the source code and by testing on my side, you can't bind directly the contextmenu event on the tree nodes if you don't have a primeng contextmenu attached to the tree.

**Expected behavior**
It would be nice to be able to bind the contextmenu event on the tree nodes even in case there's no primeng contextmenu attached to the tree. It would allow more flexibility.

**PS:** this should be notified on the documentation if it's correct.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
