### ISSUE TITLE
Inject custom HTML in MenuItem label

### ISSUE THREAD

**Issue by dhniels** [primefaces/primeng#3793]
**I'm submitting a ...** 
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already 
[ ] support request => Please do not submit support request here, instead see 

**Expected behavior**
I dont know if this is possible, but on MenuItem for example, the labels are created inside the component and not the template. Heres an example from my app:
`private actions: MenuItem[] = [
		{label: 'Delete', icon: 'fa-times', command: () => this.bulkDelete() }
	];`

Is there a way to inject custom html into the label? for example, from the code above, insert a `span` tag  after the Delete text? 

If try to do it that way now, it just displays the raw HTML.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
