### ISSUE TITLE
while using ngx-bootstrup-modal <p-calendar> not closed properly

### ISSUE THREAD

**Issue by sivakumarkarunamoorthy** [primefaces/primeng#3794]
while using ngx-bootstrup-modal <p-calendar> not closed properly

**Comment by germansokolov13** [comment]
I think I had a similar issue with a different modal component and the PrimeNG Calendar. In my case click on the modal itself would stop click event propagation to prevent modal closing as if it was clicked outside. I.e. if you click outside then modal closes, but if you click inside then outside is prevented by stopPropagation. And that would also prevent Calendar closing.
The problem with your modal may be similar but I may be wrong. Bootstrap's modal should be better than mine, so maybe it's something different.

**Comment by cagataycivici** [comment]
Use p-dialog instead.
