### ISSUE TITLE
Autocomplete getting cleared on reselection of the same suggestion

### ISSUE THREAD

**Issue by amakm** [primefaces/primeng#3799]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/Ghf3n1AOBXAtau2d5zFC?p=preview

On reselection of the same suggestion in the autocomplete, the input is getting cleared even though the ngModel is updated.
This is happening only if I'm updating the 'field' attribute of the selected item in 'onSelect()' method.

**Current behavior**
Autocomplete doesn't show the field of the selected item.

**Expected behavior**
Autocomplete should show the field of the selected item.

**Minimal reproduction of the problem with instructions**

*STEPS TO REPRODUCE*
1. Type 'a' in autocomplete input.
2. Select the first suggestion.
3. Clear the autocomplete input.
4. Type something again in the autocomplete input.
5. Select the same suggestion which was selected in Step-2.
6. The autocomplete will be cleared instead of showing the field of the selected item.

*MINIMAL DEMO*
http://plnkr.co/edit/Ghf3n1AOBXAtau2d5zFC?p=preview

**What is the motivation / use case for changing the behavior?**
My requirement is to customize the data shown in the autocomplete input.
Since there is no templating option for selected item in autocomplete single mode, I have to update the field attribute in 'onSelect()' method.

**Please tell us about your environment:** 
* **OS:** macOS 10.12.5

* **Angular version:** 4.3.1

* **PrimeNG version:** 4.1.1

* **Browser:** Chrome 60
 
* **Language:** TypeScript 2.3.4

* **Node (for AoT issues):** `node --version` =   7.3.0

**Comment by Merve7** [comment]
We update input field and after that, we update ng-model and onSelect function because you can use selected value. Therefore  you can use code like this; 
```
<p-autoComplete #auto placeholder="Start typing..." [(ngModel)]="selectedStudent"
                    [suggestions]="students" field="label" (onSelect)="onSelectStudent($event)"
                    (completeMethod)="searchStudents($event.query)">
        <ng-template let-item pTemplate="item">
            <span>{{item.id}} - {{item.name}}</span>
        </ng-template>
    </p-autoComplete>
```
```this.auto.inputEL.nativeElement.value = item.label;```
