### ISSUE TITLE
data-table lazy loading on scroll

### ISSUE THREAD

**Issue by lilling** [primefaces/primeng#380]
I see that you implemented it on DataScroller. Is there an implementation to DataTable to?

**Comment by philXeven** [comment]
+1

**Comment by asnp87** [comment]
+1

**Comment by NNemec** [comment]
+1
In fact, the different data modules seem to have somehow overlapping feature sets, but it is hard to see the system behind these. One, or fewer basic modules with orthogonal, combinable and consistent features would be much more powerful in the long run.

**Comment by cagataycivici** [comment]
2.0.1 has VirtualScrolling for this.
