### ISSUE TITLE
Multi Select Listbox Unchecks previously selected items when a label is selected

### ISSUE THREAD

**Issue by jgill248** [primefaces/primeng#3800]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Even on the PrimeNg site, in the multi select list box, you can check multiple items, but then if you select another option by clicking the label, all previously selected items are unchecked.

**Expected behavior**
Previously selected items stay checked

**What is the motivation / use case for changing the behavior?**
These seems like bad behavior.  The user is confused when just trying to add to their multiple selections

* **PrimeNG version:** 2.0.X
4.1.3

**Comment by kevlapinski** [comment]
Had the same problem.
This property will fix the issue,
[metaKeySelection]="false"
