### ISSUE TITLE
Add "clear" action in dropdown filter

### ISSUE THREAD

**Issue by washingtong33k** [primefaces/primeng#3802]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request
```

**Current behavior**
Currently, there are no clear option in the dropdown filter. 

**Expected behavior**
Add an "X" icon after the dropdown input, so i can click there and clear the filter

**What is the motivation / use case for changing the behavior?**
It's a shortcut to not hit backspace

**Please tell us about your environment:**

* **PrimeNG version:** 4.1.3

* **Browser:** all
 
* **Language:** all

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
