### ISSUE TITLE
FileUpload in auto and basic modes doesn't work when adding KML MIME type in accept

### ISSUE THREAD

**Issue by bomberblue07** [primefaces/primeng#3804]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/Qi2Nw2imLpDUF8NJinYw?p=preview

**Current behavior**
When I try to upload a file with a p-fileUpload with this property `accept="application/vnd.google-earth.kml+xml"` it doesn't actually execute the request when I select a file

**Expected behavior**
It should restrict my upload to files of the KML type and execute the request when my file is selected.

**Minimal reproduction of the problem with instructions**
Create a p-fileUpload with these settings:

`<p-fileUpload mode="basic" name="file" url="./uploadKML" auto="true"
                      chooseLabel="Upload KML" accept="application/vnd.google-earth.kml+xml"></p-fileUpload>`

Plunkr example: http://plnkr.co/edit/ZQP8vnkLyWHZljT7Enfv?p=preview

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.3.X

* **PrimeNG version:** 4.2.0-rc.1

* **Browser:** [all]

 
* **Language:** [all]

**Comment by bomberblue07** [comment]
Still doesn't execute the request in 4.2.0

**Comment by bomberblue07** [comment]
Still seeing this in the latest version. It seems to happen on the JSON MIME type as well

**Comment by sgentile** [comment]
the content-type is multipart, accept isn't a mime type ?  you can do accept="*.kml"

**Comment by bomberblue07** [comment]
@sgentile I forgot you can also limit by file extension with accept, not just MIME types, thank you. Doing just that works for me! Closing.
