### ISSUE TITLE
Multi level row grouping in datatable

### ISSUE THREAD

**Issue by UIcode123** [primefaces/primeng#3805]
Hi,

https://www.primefaces.org/primeng/#/datatable/rowgroup... in this link rows are grouped by brand(Audi, BMW and so on). But how can I add more levels.. like below rows are grouped by brand and color both:
Audi
|
Black
|
(All those items where brand is Audi and color is black)
any ideas how to achieve this?

**Comment by arunprasadkumaran** [comment]
@UIcode123 , Looks like the feature is not supported by primeng yet. Have you found any alternate solution for multi row grouping with different fields?

**Comment by UIcode123** [comment]
@arunprasadkumaran , though I was able to acheive grouping feature by making changes to existing library. that was not at all a good idea and faced with many other problems. So I suggest not to go with that approach.

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.

**Comment by Inaamhusain** [comment]
Is there any example which shows this feature?
I am looking for one to implement.
