### ISSUE TITLE
MultiSelect dropdown onBlur event fires when tick or untick item not when "onBlur"

### ISSUE THREAD

**Issue by chris601** [primefaces/primeng#3809]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/Qi2Nw2imLpDUF8NJinYw?p=preview

**Current behavior**
MultiSelect dropdown onBlur event fires when tick or untick item.

**Expected behavior**
onBlur should fire when moving away from the multiselect not when ticking and unticking selections 

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
I want to use the multiselect onblur in my application. and am forced at the moment to use onChange as I feel currently it works better.

**Please tell us about your environment:**
net core 1.1, Visual studio 2017 (updated to latest), ng4

primeng 4.2.0-rc.1

* **Browser:** [Chrome]
 
* **Language:** "typescript": "2.5.2",  "es6-shim": "0.35.3",

* **Node (for AoT issues):** `node --version` =  "7.9.0"

**Comment by cetincakiroglu** [comment]
Hi,

We couldn't replicate the issue with the latest PrimeNG release, if the issue still exists with the latest PrimeNG version, please provide a StackBlitz example by using [PrimeNG Issue Template ](https://stackblitz.com/github/primefaces/primeng-issue-template) and re-open the issue.

Regards
