### ISSUE TITLE
DataTable Column Reorder and Resize does not work with Scrollable tables

### ISSUE THREAD

**Issue by devmasao** [primefaces/primeng#381]
On a scrollable datatable, the resizeableColumns and reorderableColumn settings do not work. I cloned the source code and added the scrollable attribute the Resizeable Column Showcase to verify the issue.
Similar issue to #273 

`<p-dataTable [value]="cars" reorderableColumn="true" scrollable="true">...</p-dataTable>`

`<p-dataTable [value]="cars" resizableColumns="true" scrollable="true" scrollHeight="200" scrollWidth="75%" columnResizeMode="expand">...</p-dataTable>`

**Comment by guntram** [comment]
1st of all, the checks are like
```
if (this.reorderableColumns) { ...
```
which always results to true if this option is set. If it is set to "false", this string results to be truthy...

The issue can be fixed if you change the template, add the ```[draggable], (dragstart)``` and so on, which is not included in the template part for the scrollable stuff.

Also, you need to append the ```ui-column-resizer-helper, ui-datatable-reorder-indicator-up and ui-datatable-reorder-indicator-down``` after the ```</table>```

**Comment by guntram** [comment]
Maybe it was excluded because FF does not allow it (column ordering is disabled):
[ScrollLinkedEffects](https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects)
But in IE11 it is working... :sweat_smile:
