### ISSUE TITLE
Update Schedule to FullCalendar 3.5.0

### ISSUE THREAD

**Issue by vadjs** [primefaces/primeng#3813]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

Ater updating FullCalendar package to v3.5.0 here are appears error ```Cannot read property 'url' of undefined```
Fullcalendar v3.5.0 have major changes. That's why problem appeared.

**Expected behavior**

No errors

**Minimal reproduction of the problem with instructions**

Use last version of PrimeNG(4.2.0-rc.1).
Use last version of FullcCalendar.
Get error in any case.

**What is the motivation / use case for changing the behavior?**

Worning module.

**Please tell us about your environment:** windows

* **Angular version:** 4.3.6

* **PrimeNG version:** 4.2.0-rc.1

* **Browser:** all

 
* **Language:** all

* **Node (for AoT issues):** `node --version` =   8.1.3

**Comment by baljeet** [comment]
Any luck with the issue? I am also facing the same error

**Comment by tplessis** [comment]
Same here, but only in production with AOT. Going back to version 3.4.* of fullcalendar fixed the issue.

**Comment by baljeet** [comment]
Thanks @tplessis 
Worked for me as well.

**Comment by 200ljx** [comment]
@tplessis Thanks a lot!

**Comment by cagataycivici** [comment]
Adding a null check fixed the issue;

https://github.com/primefaces/primeng/commit/2f5dda075405769bf226792c3f06737166bafd8d
