### ISSUE TITLE
Slider Filter on DataTable, does not filter when clicked

### ISSUE THREAD

**Issue by anirudh-jagithyala** [primefaces/primeng#3814]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[* ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
https://www.primefaces.org/primeng/#/datatable/filter 

**Current behavior**

1) Open the DataTable with slider filter , For example the main site : https://www.primefaces.org/primeng/#/datatable/filter
2) Use the slider filter to slide across the Data column, Filtering works.
3)use the slider and click on various slider location values, Filtering does not work but the Slider filter value changes.
**Expected behavior**

Slider Filter to Filter data for the value changes of the the slider either by clicking or dragging it.

**Comment by cagataycivici** [comment]
Demo is fixed using onChange instead and a timer for better performance to avoid filtering during slide.
