### ISSUE TITLE
DataTable with scrollHeight and frozenWidth makes frozen columns not scrollable not only horizontally, but vertically

### ISSUE THREAD

**Issue by opetriienko** [primefaces/primeng#3816]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Dem**
Please see "Frozen Columns" example here:
https://www.primefaces.org/primeng/#/datatable/scroll

**Current behavior**
If we set frozenWidth and scrollHeight to the <p-dataTable> frozen columns' section become not scrollable at all. Not only horizontally(what is expected), but vertically as well. We can scroll vertically only right side of the table(unfrozen columns).

**Expected behavior**
Frozen columns' section should be scrollable vertically as well.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.3.6

* **PrimeNG version:** 4.1.3

* **Browser:** [all]

 
* **Language:** [TypeScript X.X]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
If more users demand it, we'll do the enhancement.

**Comment by Fredz66** [comment]
I concur, I'd like to see this feature implemented as well, or at least a workaround. Thanks.

**Comment by Fredz66** [comment]
Can someone give me some pointers to get started on this issue, I would really appreciate. Thanks.
