### ISSUE TITLE
Error: 'EditorModule' is not exported by node_modules\primeng\primeng.js

### ISSUE THREAD

**Issue by aijingsun6** [primefaces/primeng#3818]
env:
node:v6.11.2
npm:3.10.10
angular:4.2.4
os:window 7(Windows_NT 6.1.7601)
logs when using rollup in ng4

aot/src/main-aot.js → aot/dist/build.js...
The final argument to magicString.overwrite(...) should be an options object. See https://github.com/rich-harris/magic-string
'SharedModule' is not exported by 'node_modules\primeng\components\common\shared.js'
'SharedModule' is not exported by 'node_modules\primeng\components\common\shared.js'
'EditorModule' is not exported by 'node_modules\primeng\components\editor\editor.js'
'EditorModule' is not exported by 'node_modules\primeng\components\editor\editor.js'
'PaginatorModule' is not exported by 'node_modules\primeng\components\paginator\paginator.js'
'PaginatorModule' is not exported by 'node_modules\primeng\components\paginator\paginator.js'
'DataTableModule' is not exported by 'node_modules\primeng\components\datatable\datatable.js'
'DataTableModule' is not exported by 'node_modules\primeng\components\datatable\datatable.js'
'ContextMenuModule' is not exported by 'node_modules\primeng\components\contextmenu\contextmenu.js'
'ContextMenuModule' is not exported by 'node_modules\primeng\components\contextmenu\contextmenu.js'
'Ng2TableModule' is not exported by 'node_modules\ng2-table\components\ng-table-module.js'
'Ng2TableModule' is not exported by 'node_modules\ng2-table\components\ng-table-module.js'
[!] Error: 'EditorModule' is not exported by node_modules\primeng\primeng.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
aot\src\app\app.module.js (14:9)
12: import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
13: import { BsDropdownModule } from 'ngx-bootstrap';
14: import { EditorModule } from 'primeng/primeng';
             ^
15: import { CoreModule } from './core/core.module';
16: import { AdminSharedModule } from './shared/shared.module';

**Comment by aijingsun6** [comment]
i fix myself

plugins: [
    nodeResolve({jsnext: true, module: true}),
    commonjs({
      include: [
        'node_modules/rxjs/**',
        'node_modules/rxjs/**',
        'node_modules/primeng/**'
      ],
      namedExports: {
        // left-hand side can be an absolute path, a path
        // relative to the current directory, or the name
        // of a module in node_modules
        'node_modules/primeng/components/common/shared.js': [ 'SharedModule' ]
      }
    }),
    uglify()
  ]

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=info

**Comment by softengi** [comment]
@aijingsun6, on including your configuration, I am getting error -

> Error: Duplicate export 'SharedModule'

Any suggestions?
