### ISSUE TITLE
Error: Duplicate export 'SharedModule'

### ISSUE THREAD

**Issue by aijingsun6** [primefaces/primeng#3819]
env:
nodejs: v6.11.2
npm:3.10.10
ng:4.2.4
logs below:
aot/src/main-aot.js → aot/dist/build.js...
The final argument to magicString.overwrite(...) should be an options object. See https://github.com/rich-harris/magic-string
[!] Error: Duplicate export 'SharedModule'
node_modules\primeng\components\common\shared.js (524:22)
522: export { shared_15 as TemplateLoader };
523: var shared_16 = shared.SharedModule;
524: export { shared_16 as SharedModule };
                           ^

**Comment by aijingsun6** [comment]
i am sorry, it's my fault

**Comment by justmatt25** [comment]
What did you do to fix this? I got the same error
