### ISSUE TITLE
TreeTable: Documentation error

### ISSUE THREAD

**Issue by steigerm** [primefaces/primeng#3824]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
selectionMode ist currently documented as "single" or "multiple" 
But the demo source code shows that for multiple selections using checkboxes the selectionMode must be set to "checkbox"

**Expected behavior**
Correct documentation

**Minimal reproduction of the problem with instructions**
Just look at the website

* **PrimeNG version:** 4.1.2

* **Browser:** all

**Comment by davisb10** [comment]
@steigerm A pull request to update the documentation has been entered.

**Comment by steigerm** [comment]
Thx
