### ISSUE TITLE
TreeTable: Add methods to collapse/expand nodes

### ISSUE THREAD

**Issue by steigerm** [primefaces/primeng#3825]
There are currently events onNodeExpand/onNodeCollapse but no methods to do it programmatically

**Comment by cagataycivici** [comment]
I don't think it is necessary, at your model if you set TreeNode.expanded = true|false then UI will be updated accordingly.

**Comment by steigerm** [comment]
Thanks for the information!
Good to know that this works bidirectional.

@cagataycivici Maybe another pointer to enhance the documentation.
