### ISSUE TITLE
GlobalFilter not working in 4.1.1

### ISSUE THREAD

**Issue by bhaidar** [primefaces/primeng#3833]
**I'm submitting a ...**
```
[X] bug report
[ ] feature request
[ ] support request
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/RdK9oNGwNrugKcWBIKUW?p=preview

**Current behavior**
I have a Datatable with onLazyLoad enabled. When using the Global Filter, I can see a spinner running but then the data is not filtered. 

**Expected behavior**
To filter the data with whatever text I input into the Global Filter.

**Minimal reproduction of the problem with instructions**
Try to filter the Datatable

**Please tell us about your environment:**
Visual Studio Code / Windows 10

* **Angular version:** 4.3.1

* **PrimeNG version:** 4.1.1

* **Browser:** Chrome 60
 
* **Language:**  TypeScript 2.4

**Comment by oixan** [comment]
The Global filter work to me. You are passing always the same array so you cant see any change.
I forked your example and now work. 

http://plnkr.co/edit/nW5J8DlF4oRMHY0ck3AR?p=preview

**Comment by bhaidar** [comment]
Thanks @oixan 
In the control's page, they don't mention or do any such filtering. 
https://www.primefaces.org/primeng/#/datatable/filter

Also, the getAgencies() function is used originally to get data from the server. How can I use the same function to do both, bring in data from the server and use it also for search?

**Comment by oixan** [comment]
It basically the same just make your server call in the getAgencies() method and update this.records after you get your data. The datatable will be update with the new values.

**Comment by bhaidar** [comment]
Thanks @oixan. just any idea how come the demo on primeNG page doesnt do any filtering in the code yet it works?

**Comment by oixan** [comment]
i dont really know
