### ISSUE TITLE
ConfirmDialog causes ExpressionChangedAfterItHasBeenCheckedError 

### ISSUE THREAD

**Issue by nartc** [primefaces/primeng#3834]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Below is my plukr case to the replicated issue. 

http://plnkr.co/edit/sItbGl

**Current behavior**

Clicking a checkbox inside of a dataTable with confirmationDialog tied to onChange() triggers ExpressionChangedAfterItHasBeenCheckedError in the console.

**Expected behavior**

Shouldn't trigger the Error

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/sItbGl

However, when I go into the system.config.js to mess around with the PrimeNG version, PrimeNG 4.1.0-rc.2 seems to be working fine and does not produce this error. 4.1.0, 4.1.3 and 4.2.0-rc.1 all produce the error.

The error only shows when having the confirmationDialog tied to the checkbox's onChange. 

**What is the motivation / use case for changing the behavior?**

Toggle a boolean filed of a model on the DataTable. Use-case: an Order that has isDelivered boolean field. Once the order has been delivered, an admin user can check the box to toggle the boolean value which can be used to trigger various others data (revenue goes up, inventory goes down...etc..) and at the same time, disable the checkbox. The ConfirmationDialog is to warn the admin user before checking.

**Please tell us about your environment:**

MEAN Stack

* **Angular version:** 4.0.0

* **PrimeNG version:** 4.2.0-rc.1

**Comment by JohannesBusch** [comment]
same on 4.2.1

**Comment by ki2ga** [comment]
I have the same issue on angular 4.4.6 and primeng 4.3.0

**Comment by patriknil90** [comment]
Same with 5.0.0-rc.0

**Comment by Franky238** [comment]
+1 on 5.2.3
more details: 
when you want to call ConfirmationService in ngAfterViewCheck() you will get error: 
`ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'display: none'. Current value: 'display: block'.`

**Comment by yigitfindikli** [comment]
I couldn't replicate it, please try with latest PrimeNG.
