### ISSUE TITLE
Datatable with edit mode Cannot read property querySelectorAll

### ISSUE THREAD

**Issue by lippomano** [primefaces/primeng#3836]
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

I have recently updated to primeng 4.2.0-rc1 and in datatable when I try to edit I see this error
Cannot read property 'querySelectorAll' but the edit works fine.

This happens when I try to save for example a symbol than I have correctly an error because is not permitted and I reload the table, after that every edit gives me this error.

**Comment by Merve7** [comment]
Please tell me about other environment for example browser

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
