### ISSUE TITLE
Resizable Column not working

### ISSUE THREAD

**Issue by bhaidar** [primefaces/primeng#3839]
In the following plunkr. You notice that resizableColumns="false" yet I am still being able to resize.

I am facing issue with resizing columns. The header cells change size, and the data cells remain the same. So they are not aligning together.

I couldn't replicate the same behavior but at least setting resizableColumns="false" keep on resizing.

http://plnkr.co/edit/pSC9L9T9amo1jB9A1ewo?p=preview

**Comment by oixan** [comment]
Just write [resizableColumns]="false".

**Comment by cagataycivici** [comment]
Not a valid issue.
