### ISSUE TITLE
The new model based approach to menubar is not very "component" based

### ISSUE THREAD

**Issue by joe380** [primefaces/primeng#384]
Hello,
the old menubar component before beta.6 was kind a better because it allowed the user to specify the style, visual, layout, etc of the menu and could (if wanted) make a reference to all layers of menu.

Now you just have a model ,in which it is only possible to specify label and icon and (fortunatelly) a user specific command to do something if clicked. 
This new model based component is not something what user is expecting from a component library.
With menubar primeng is becomming more a framework than a component library which should give you as much freedom as possible to style your components.

Example:
With old menubar it as possible to specify the css width attribute of submenus based dynamically on the text length of a single \<li\> element because the users specified the \<ul\> and \<li\> elements with ngFor.

With the new one it is not possible to make the width dynamic for each submenu depending on the width, and the result is than show in the image. (wrapped text)

![capture](https://cloud.githubusercontent.com/assets/2151234/15421689/f5e8237e-1e74-11e6-8a6d-1e0e3fc75570.PNG)

The solution would be to also provide an old menu component where user has the freedom.
Thanks,
Jano

**Comment by Pranen** [comment]
Hi,

I would also propose to add a style/styleClass attribute to the MenuItem.

In the old menubar component, we marked the selected menubar/item, and with the new model, I don't see a possibilty to do this again.

Regards & Thanks,
Peter

**Comment by cagataycivici** [comment]
@Pranen please create a new ticket for this request.

@joe380 style and style class should solve this, new api is more flexible and more angular centric, old one was jquery centric. New model can handle change detection like removing or adding an item to menu, old one has various limitations.

**Comment by IsuruCham** [comment]
@cagataycivici 
Hi,
There seems to be no functions in the new menu bar in which we can add menu items to the very right of the menu bar (like in the new tool bar), as in most modern navigation bars. Also can we manipulate the menu bar to achieve a  change of collapsed drop down like menu when the browser size changes (responsive) ?
Thanks.

**Comment by dbrezoev** [comment]
Where can we see examples with these properties style and styleClass? I cant change the color of the text with it for example or make it not to collapse when shown in narrow screen. Any clues? Thanks
