### ISSUE TITLE
on filtering datatable only get current column filter data value how can i get all columns filter data in $event

### ISSUE THREAD

**Issue by shashi97** [primefaces/primeng#3840]
Version - "primeng": "^4.2.0-rc.1",

 <p-dataTable [value]="salesOffices" scrollable="true" [paginator]="false" [rows]="pageSize" [responsive]="true" (onSort)="onSorting($event)"
        (onFilter)="onFiltering($event)">

onFiltering(event) {
    this.paginationService.setFilterValues(event.filters);
  // I can only get current column filter value in "event" how can i get all the filter value from datatable?
  }

**Comment by cagataycivici** [comment]
event.filteredValue

**Comment by rahulccactus** [comment]
Hi @shashi97 ..Same functionality i achieved by using one of angular life cycle event, i.e ngAfterViewChecked().
In p-table, assign template reference variable (#tempTable) & in  ngAfterViewChecked() function you can use event.filteredValue.You get all
filtered values.
for example
In Html
<p-table #tempTable></p-table>
In ts
@ViewChild('tempTable', { static: false }) DataTableVar: DataTable;

&&
ngAfterViewChecked(){
console.log('this.DataTableVar', this.DataTableVar.filteredValue);

}

You will get filtered data

##Hope you will get what you want

Thanks 
Rahul Chamle
