### ISSUE TITLE
Add slotLabelFormat property to Schedule

### ISSUE THREAD

**Issue by rferrerasm** [primefaces/primeng#3841]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Add the [slotLabelFormat](https://fullcalendar.io/docs/agenda/slotLabelFormat/) property of FullCalendar to Schedule.

* **PrimeNG version:** 4.1.3

**Comment by ohtwadi** [comment]
You can use the existing options property.

See an example here: https://github.com/primefaces/primeng/issues/1976#issuecomment-301396390

**Comment by rferrerasm** [comment]
Thanks.
