### ISSUE TITLE
Feature request: Changes calendar property "disabledDays" to "disabledWeekDays" and create "disabledMonthDays"

### ISSUE THREAD

**Issue by upmauro** [primefaces/primeng#3844]
**I'm submitting a ...**  

[X] feature request

**What is the motivation / use case for changing the behavior?**

Before creating the pull request I would like to discuss whether it will be accepted or not.

My system, and I think several others (mainly billing) have the need to deactivate a few days in the month in the selection of the calendar. Doing this through "disabledDates" gets tricky as it would be necessary to deny all existing dates.

I suggest that the name of the "disabledDays" property (used today to disable days of the week) be changed to disabledWeekDays and that the "disabledMonthDays" property <Array [int (1..31)]> be created.

What do you think about it? Can I create the pull request?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
