### ISSUE TITLE
VirtuaScroll option to work as DataScroller

### ISSUE THREAD

**Issue by GuzzoLM** [primefaces/primeng#3845]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
DataTable VirtuallScroll works pretty much like a paginator: Scroll down and you see the next page, scroll up and you see previous page.
This behaviour seems odd to me, because if I scroll down and then scroll up, I'll be sending a request to my backend to fetch data that already have been fetched befor.
Is there a way to change this behaviour?

**Expected behavior**
I expected DataTable VirtualScroll to behave like the DataScroller.

**What is the motivation / use case for changing the behavior?**
The whole point of using a VirtualScroll is to avoid pagination and data loading every time a change page occurs. With the current behavior, VirtualScroll miss this point.
So it would be nice if there was an option to change this behaviour to one that works more like the DataScroller.

* **PrimeNG version:** 4.1.3

* **Browser:** [all]

**Comment by lippenacif** [comment]
I'm needing the same feature!

**Comment by adrianabreu** [comment]
I need this feature too, I'm trying to play with the datatable behaviour, but it will trigger the change detector too many times

**Comment by cagataycivici** [comment]
We have a new component for virtual scroll;

https://github.com/primefaces/primeng/issues/6869
