### ISSUE TITLE
Specify animation parameters

### ISSUE THREAD

**Issue by jarinwhite** [primefaces/primeng#3846]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Cannot control animation parameters such as transition speed, type, etc.

**Expected behavior**
Would like to be able to control animation parameters using Angular 4.2+ animation inputs. We recently purchased the Avalon theme (which is great, thank you!) but would like to speed up some of the animation transitions. Please see here for how this is done: https://www.yearofmoo.com/2017/06/new-wave-of-animation-features.html

**Comment by danielordonez** [comment]
Would like to see this too

**Comment by cagataycivici** [comment]
Issue is not clear and too broad. Please use Avalon forum for questions.

**Comment by jarinwhite** [comment]
This is not specific to Avalon. Please try to understand what your paying customers are suggesting rather than simply closing the issue as "too broad". The article I linked is very clear about what I'm talking about.

For instance, the Dialog component. https://github.com/primefaces/primeng/blob/master/src/app/components/dialog/dialog.ts

You are specifying on lines 41 & 42 that the animation speed is 400ms. This should be adjustable, but is currently not without extending and overriding the component's template. Angular now has a way to control those speeds with animation parameters as shown in the article I linked in the original issue.
