### ISSUE TITLE
Spinner allows to input characters on Android

### ISSUE THREAD

**Issue by arjunshankar** [primefaces/primeng#3847]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Open this link on an Android device. 
https://www.primefaces.org/primeng/#/spinner

**Current behavior**
Spinner allows the user to enter character, spaces, special characters etc.

**Expected behavior**
Only numbers should be allowed.

**What is the motivation / use case for changing the behavior?**
Spinner broken on Android devices.

**Please tell us about your environment:**
Tested on Android 7,6,5
Devices: Samsung S7,S6,S5 
Browsers: Chrome, Opera

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by anjelchen** [comment]
not only on android.

spinner enables again to input non-numeric characters. on blur they are not shown, but they stay in model.

**Comment by yigitfindikli** [comment]
Spinner is deprecated you can use InputNumber instead of Spinner.
