### ISSUE TITLE
Set Paginator page programmaticlly (@Input())

### ISSUE THREAD

**Issue by JoCoaker** [primefaces/primeng#3849]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Cant set Paginator on Load (Programmaticly)

**Expected behavior**
Set Page over Input

**What is the motivation / use case for changing the behavior?**
When I go back to the table, the page I was on before should be saved and it should return back to the page.

**Comment by cagataycivici** [comment]
Use the first property to do so, if that doesn't work, provide a plunkr please;

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview
