### ISSUE TITLE
filtering / paging issues in datatable

### ISSUE THREAD

**Issue by fripp0971** [primefaces/primeng#385]
**First Issue**

Using the datatable, i set filter up as true on each column. I have 20 rows showing in each page of the grid. If I use a dataset with say 100 records, I initially get 5 page links in the paginator. This is correct obviously.

If I use a filter at the top of a column to search on something that brings the record set down to say 40 records, the paginator adjusts and only shows 2 page links. This is also correct.

Now if I try to sort by clicking the column header, even though the number of records isn't being changed, the paginator resets to its full page number. 

**Second Issue**

If I setup a global filter on the datatable but don't allow per column filtering, the filtering works as intended, but then column sorting no longer works. This combination seems to be broken.

Thanks!!!

**Comment by fripp0971** [comment]
Any update?

**Comment by cm0s** [comment]
I encountered same issue

**Comment by cm0s** [comment]
The problem seems to come from the updatePaginator() function which only use this.value instead of also taking into account the this.filteredValue.

A solution will be to replace this line of code : 
`this.totalRecords = this.lazy ? this.totalRecords : (this.value ? this.value.length: 0);`

by something like :

    if (!this.lazy) {
        this.totalRecords = this._filteredValue ? this._filteredValue.length : this.value ? this.value.length : 0;
    }

I didn't tested it yet.

**Comment by edangerfield** [comment]
Same issue here.  Using the following:
"primeng": "1.0.0-beta.11",
"primeui": "4.1.14"

**Comment by mariahlynne** [comment]
This issue is still present in RC4. Any update as to when it might be fixed?

**Comment by cagataycivici** [comment]
Does it happen with 2.0.2?

**Comment by cagataycivici** [comment]
I'm unable to replicate on 4.x, should be fine with 2.0.2 as well as nothing related has changed. Please provide a plunkr that replicates the issue and we'll review.
