### ISSUE TITLE
enhancement

### ISSUE THREAD

**Issue by ihabsalem** [primefaces/primeng#3851]
Hi,

Kindly I would like to provide an enhancement for the popup menu component, you are showing/hiding the menu using pure display block/none in CSS, it would be great if you include it in a class, so we can animate the showing/hiding.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by cagataycivici** [comment]
Which component is this?

**Comment by pos-isalem** [comment]
it's on menu component

clicl [here](https://www.primefaces.org/primeng/#/menu) for the link

**Comment by yigitfindikli** [comment]
You can use showTransitionOptions and hideTransitionOptions.
