### ISSUE TITLE
Changes made in datatable template not reflected in prod build

### ISSUE THREAD

**Issue by ManojSethuraman** [primefaces/primeng#3852]
HI,

I have added primeng module , in which I have made some changes by updating the templates for datatable component by adding emptymessage as an innerhtml as below

`<div [innerHTML]=\"dt.emptyMessage\"></div>`

 and edited the css files. The changes are getting reflected perfectly in dev build. But when prod build is done, I could not see them reflected.

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=info
