### ISSUE TITLE
Spinner silently discards manually entered decimal value if step value is a whole number

### ISSUE THREAD

**Issue by madnaelo** [primefaces/primeng#3853]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/u9Ue9crSWLcvmjUiQsmB

**Current behavior**
If step value in primeng spinner is a whole number, then manually entered decimal value is not submitted. Rather decimal part is discarded silently, without letting the model or user know. E.g. step value is 1, then if user manually enters a value 100.3, the value submitted to model is 100 and not 100.3.

**Expected behavior**
If step value in primeng spinner is a whole number, then manually entered decimal value should be submitted to model, and decimal part should not be discarded. Or at least there should be a parameter to enable/disable this behaviour. Or at there should be a parameter from which model can know about the decimal part.

**Minimal reproduction of the problem with instructions**
Plunker case attached above.
- Set primeng spinner value to 1.
- Enter a value 100.3 in primeng spinner.
- print the value submitted by primeng spinner. The value printed is 100, whereas the value shown in the primeng spinner is 100.3

**What is the motivation / use case for changing the behaviour?**
There are two problems with silently discarding decimal part. 1) Model can never know and inform user if value was discarded. 2) There are occasions where we mostly need integer input, but still there are edge cases where user should be able to enter decimal values manually. We can't do so with current implementation of primeng spinner. We have to either give up integer step value, or manual entry of decimal value.

**Please tell us about your environment:**
angular 4.0.0
primeng 4.1.0 rc2

Browser: all
 
Language: all

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
