### ISSUE TITLE
IE 11 Menubar Issue

### ISSUE THREAD

**Issue by saikiranmandhala** [primefaces/primeng#3854]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
The Menubar has still issue in IE 11, Open the below URL in IE 11 and then hover on Help -> Search
On Hover, the ul is closing whenever I try to click on child item.

[https://www.primefaces.org/primeng/#/menubar](url)

**Comment by ADefWebserver** [comment]
It works for me with IE 11.608 Windows 10. 
I do have to move my mouse much slower and more carefully than in Chrome.

**Comment by saikiranmandhala** [comment]
but we can not insist users to do the same...they come to application to do certain things but not to check Menubar carefully :(

**Comment by saikiranmandhala** [comment]
I have a input on this issue, 
`<ul class="ui-menu-list ui-widget-content ui-corner-all ui-helper-clearfix ui-menu-child ui-shadow" style="left: 0px; z-index: 1025;top:28px">
`
For child there is a inline style `top:28px`  this is causing the issue. If i remove this then it is working fine in IE. I looked for this style in the source code  but i dnt see anywhere this linline style...Any help on this would be appreciated greatly...thanks

**Comment by saikiranmandhala** [comment]
git this fixed, 
if(this.root) {
                //sublist.style.top = this.domHandler.getOuterHeight(item.children[0]) + 'px';
                sublist.style.left = '0px'
            }
            else {
                //sublist.style.top = '0px';
                sublist.style.left = this.domHandler.getOuterWidth(item.children[0]) + 'px';
            }

I have commented out **top** style property. It is working fine IE11 & chrome 61.0.3163.79

**Comment by yigitfindikli** [comment]
IE support is deprecated.
