### ISSUE TITLE
'Move all' buttons should not move filtered item.

### ISSUE THREAD

**Issue by queueseven** [primefaces/primeng#3855]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/yzP7UAPLnZs1BjN7iz4C

**Current behavior**
When filtering the a list of the PickList component and then clicking the 'move all' button of that list, *all* items are moved to the other list instead of only the visible items.

**Expected behavior**
Moving 'all' items of a list should only move the currently visible items.

**Minimal reproduction of the problem with instructions**
Filter the left list of the plunkr by 'bar', then click the 'move all to right' button.
All 3 items are moved to the right list, instead of only the single 'bar' item.

**What is the motivation / use case for changing the behavior?**
Currently, the combination of filtering/moving all makes no sense

* **PrimeNG version:** 4.1.3

Fixing this should be trivial, as far as I see.

**Comment by davisb10** [comment]
@queueseven I have submitted a pull request to resolve this issue. It should now only push the items that are currently visible.
