### ISSUE TITLE
Calendar Input Formats

### ISSUE THREAD

**Issue by sgentile** [primefaces/primeng#3857]
When typing directly into the calendar control it only supports typing "mm/dd/yyyy" 

I have not found any option to allow input such as :  "m/d/yy"  where the user doesn't have to type '01' they can just type '1' - same with days

**Comment by michaelshuck** [comment]
i've noticed something similar. When in single selection mode using dateFormat of yy-mm-dd, I get a validation error when I attempt to enter dates with a "0" value in the day as in 2017-09-01 but it works fine if I enter 2017-09-11.  Same problem when using range selection mode.

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=info
