### ISSUE TITLE
Wrong Index in $event.index on onOpen in Accordion

### ISSUE THREAD

**Issue by PhilippRoessner** [primefaces/primeng#386]
When my component initializes, the correct index is send to my "setSelectedLeistungIndex"-Method. When I have three items in my array, and I click the second tab, Index = 1. After saving the data of my "leistungen"-Array, I refresh the rows in my array like 

`leistungen[index] = savedLeistung;`

When I then click the second tab, Index = 5, the third tab's Index = 4. So also the order is strange then.

```
    <p-accordion (onOpen)="setSelectedLeistungIndex($event)">
        <p-accordionTab *ngFor="let leistung of leistungen" [selected]="leistung===selectedLeistung">
            <header>
                {{leistung.name}} 
            </header>
        </p-accordionTab>
    </p-accordion>
```

**Comment by cagataycivici** [comment]
What does leistungen[index] = savedLeistung;? How can we replicate this issue?

**Comment by cagataycivici** [comment]
Can't replicate.

**Comment by pjmagee** [comment]
I'm actually having a similar issue with the index being entirely wrong (from a list that has say 5 items, i get index number 11 coming back from the event)
