### ISSUE TITLE
create cohesive select menu appearance

### ISSUE THREAD

**Issue by dhniels** [primefaces/primeng#3862]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request 
```

**Current behavior**
Any component using an html `select` element (such as the date picker inside Calendar) has inconsistent appearance across browsers. Firefox's implementation of `select` is particularly egregious 

**What is the motivation / use case for changing the behavior?**
Building a custom `select` will allow it to be styled consistently across browsers, without having to use additional CSS resets or normalize.

**Comment by gkiosov** [comment]
Yeah. It's kinda weird when you can customize any element but can't do nothing with this raw default selects in calendar — this spoils the whole design.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
