### ISSUE TITLE
Avalon has outdated gradient syntax

### ISSUE THREAD

**Issue by jarinwhite** [primefaces/primeng#3863]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
This is a premium theme, so I imagine you don't want me to make a plunkr :)

**Current behavior**
In _mixins.scss in the Avalon theme, the `background-gradient-top2bottom` and `background-gradient-left2right` themes are using outdated syntax which SASS complains about: `Gradient has outdated direction syntax. New syntax is like 'to left' instead of 'right'.`

**Comment by cagataycivici** [comment]
@Merve7 Please check this, Paradise also likely to use this syntax.

**Comment by cagataycivici** [comment]
Fixed in latest update
