### ISSUE TITLE
AutoComplete passes wrong item to Unselect in multiple mode

### ISSUE THREAD

**Issue by skolli853780** [primefaces/primeng#3864]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/Qi2Nw2imLpDUF8NJinYw?p=preview

**Current behavior**

I have added items to Autocomplete field, and when I delete an item, Model variable in the component is not getting updated.. issue similar to https://github.com/primefaces/primeng/issues/213

**Expected behavior**

When an item is deleted from Autocomplete field, it should update the value array on the model side
**Minimal reproduction of the problem with instructions**

Add couple of items to Autocomplete field and print log of the Model variable in Component.. items are not delete in the value array

**What is the motivation / use case for changing the behavior?**

We have upgraded to Angular 4.0 and PrimeNG 4.0, started seeing this issue.. never seen this issue before

**Please tell us about your environment:**

* **Angular version:** 2.0.X

Angular 4.3

* **PrimeNG version:** 2.0.X
Angular 4.2.0-rc.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   6.11

**Comment by cagataycivici** [comment]
Duplicate #3188
