### ISSUE TITLE
Day in Calendar/Daypicker

### ISSUE THREAD

**Issue by ernitingoel** [primefaces/primeng#387]
Can we also have the day in the DayPicker after selecting a date? Like 'Wednesday' in the image below

https://www.dropbox.com/s/p7ukyf5h8rvjhel/Capture.JPG

**Comment by ernitingoel** [comment]
Reference: http://forum.primefaces.org/viewtopic.php?f=35&t=45608&p=142711#p142711

**Comment by cagataycivici** [comment]
This is already possible with a format like;

`<p-calendar [(ngModel)]="date1" dateFormat="MM d, yy DD"></p-calendar>`

More info about pattern;

https://api.jqueryui.com/datepicker/
