### ISSUE TITLE
Paginator causes route reset

### ISSUE THREAD

**Issue by stevenxi** [primefaces/primeng#3871]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see 
```

**Current behavior**
DataTable - Paginator, when current page reach the first or last page. The "move to first" or "move to last" icon in the paginator looks disabled. But when you click the disabled icon, whole application been redirect to the default route.

**Expected behavior**
The clicking disabled "move to first" or "move to last" page icon should do nothing.

**Minimal reproduction of the problem with instructions**
The demo page of official site: https://www.primefaces.org/primeng/#/datatable/paginator
Click the |< icon after open the page.

![capture](https://user-images.githubusercontent.com/3340119/30173650-4c5a4a24-93f0-11e7-8e89-c2046785a1ef.PNG)

**Please tell us about your environment:**
Chrome 60.0.3112.113

* **Angular version:** 2.0.X
Demo site

* **PrimeNG version:** 2.0.X
It's the official site demo page, so I would assume it's the latest version.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome 60.0.3112.113

**Comment by davisb10** [comment]
@stevenxi I have created a pull request to fix this issue. It was caused by not preventing the default event for the button click when you were already on the first/last page.

**Comment by stevenxi** [comment]
Thanks @davisb10
