### ISSUE TITLE
p-calendar [showIcon]="true" breaks animation

### ISSUE THREAD

**Issue by stevek202** [primefaces/primeng#3872]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/QIfw07?p=preview

**Current behavior**
When adding [showIcon]="true" to a p-calendar the animations stop working.

**Expected behavior**
The animations should continue to behave normally whether showIcon is true or false

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

I'm not sure how the button is rendered, but something about it causes animations to break, ideally they would not break.

**Please tell us about your environment:**

Windows 10, Visual Studio 2015, angular-cli, node lite server/iis

* **Angular version:** 4.3.3

* **PrimeNG version:** 4.1.2

* **Browser:** Chrome

Currently I am only using Chrome

**Comment by cagataycivici** [comment]
Your plunkr crashed my browser, it is just a button.

**Comment by stevek202** [comment]
Yeah, that's the problem.  Adding a button to a date picker shouldn't crash the browser when doing animations.

**Comment by stevek202** [comment]
This issue was closed with the justification that my plunkr crashed a browser, where that crashing is exactly what the issue is.  I would request that it be looked at again, it would be nice to resolve this.
