### ISSUE TITLE
RadioButton onClick doesn't work when user clicks on label 

### ISSUE THREAD

**Issue by lavamen** [primefaces/primeng#3873]
This is a copy of #3286 
I added a link that shows the problem

http://plnkr.co/edit/FzxSBxFVvrh8E2PEJKtV?p=preview

When you click on text of a radio button and on the radio button, it is a different result

**Comment by cagataycivici** [comment]
Should work with 4.2.2.

**Comment by tgupta694** [comment]
This still does not work with the latest version 
my version in package.json is  "primeng": "^4.3.0",

**Comment by lavamen** [comment]
I confirm (using the example on plnkr.com and the version 4.3.0) that it doesn't work

**Comment by citizentim** [comment]
Just came across this as I was experience the same issue.  I've upgraded to 4.2.2 and then to 4.3.0 in my own dev environment, and in neither case do I experience the issue anymore.  I guess without a test case it's difficult to say.

**Comment by cagataycivici** [comment]
Reopen for review.

**Comment by cagataycivici** [comment]
Does it work with 5.0-RC0?

**Comment by lavamen** [comment]
I checked for 5.0-RC0, it's work !

**Comment by cagataycivici** [comment]
Good to hear!
