### ISSUE TITLE
p-splitButton calls to click event when DropDown menu is clicked

### ISSUE THREAD

**Issue by Ninja-Coding-Git** [primefaces/primeng#3877]
`<p-splitButton>` calls to (click) event when DropDown menu is clicked, wich is wrong.

PrimeNG version: 4.1.3
Browser: any
How to reproduce: click the menu button of splitButton

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview

**Comment by saikiranmandhala** [comment]
this is happening with 8.1.1 vesion.

**Comment by aberonni** [comment]
For anyone still struggling with this, make sure to bind to `(onClick)` and not to `(click)`
