### ISSUE TITLE
Pagination not properly working while doing filter functionality when the user doing second filter in the same search result

### ISSUE THREAD

**Issue by sarunTech** [primefaces/primeng#3878]
### Pagination not properly working while doing filter functionality when the user doing second filter in the same search result

Open the url 'http://primefaces.org/primeng/#/datatable/filter' in IE browser
Click on '>|' and go to last page of the result. 
![image](https://user-images.githubusercontent.com/31478097/30198596-1fecb34a-948c-11e7-85f4-58b65014519e.png)

Click on the filter text box. System moving to the first page when the user place the cursor on the filter box.
![image](https://user-images.githubusercontent.com/31478097/30198627-49a57578-948c-11e7-84e8-7baed187d2e9.png)

**Comment by cagataycivici** [comment]
Unable to replicate
