### ISSUE TITLE
DataTable in lazy (virtual scrolling) mode displays first slice of data repeatedly

### ISSUE THREAD

**Issue by evaldasstu** [primefaces/primeng#3879]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/gkNnbH5DlT28RhCaCTuL?p=preview

**Current behavior**
When scrolling down, the first slice of requested rows from the data source is being displayed repeatedly, despite that the array assigned to the DataTable is being updated.

**Expected behavior**
When scrolling down, successive entries should be displayed.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/gkNnbH5DlT28RhCaCTuL?p=preview
Scroll down the table

**What is the motivation / use case for changing the behavior?**
Can't get Data Tables to work in lazy mode.

This issue might be related to bug [#3377 DataTable with Virtual Scroll flickers](https://github.com/primefaces/primeng/issues/3377) . In 4.1.1 and earlier versions the table flickers, but the issue that I'm describing here doesn't manifest and successive entries are displayed correctly when scrolling down.

**Please tell us about your environment:**

* **Angular version:** 4.2.6

* **PrimeNG version:**  4.1.2 up to 4.2.0-rc.1.

* **Browser:** At least: Chrome 60.0.3112.113 | Firefox 55.0.3 | Edge 40.15063.0.0

**Comment by cagataycivici** [comment]
Tracked at #3907
