### ISSUE TITLE
Schedule documentation error

### ISSUE THREAD

**Issue by rferrerasm** [primefaces/primeng#3881]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
In the "Events" section, the code sample of `handleEventClick()` shows the event containing the fields `event`, `jsEvent` and `view`.

The `event` field should be `calEvent`.

**Comment by davisb10** [comment]
@rferrerasm This is incorrect. According to the documentation on [eventClick](https://fullcalendar.io/docs/mouse/eventClick) the parameters are 'event', 'jsEvent' and 'view'. In the example below the function definition, they are naming the 'event' param as 'calEvent' but it is just a name. The parameter is still event.

**Comment by rferrerasm** [comment]
Isn't this the code that emits the event?

https://github.com/primefaces/primeng/blob/master/src/app/components/schedule/schedule.ts#L191

The parameters of the handler can be called whatever, but the emitted object has the properties `calEvent`, `jsEvent` and `view`.

**Comment by davisb10** [comment]
My apologies. I went all the way back to the full calendar js implementation. However, you are correct. I have submitted a pull request to update the documentation.
