### ISSUE TITLE
p-autocomplete highlight the existing text upon click

### ISSUE THREAD

**Issue by mengullojerome** [primefaces/primeng#3885]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
I can't figure out how to replicate this on the p-autocomplete component:

`
<input type="text" onclick="this.select()"/>
`

Also please note that the p-autocomplete is dynamically added.

Maybe there needs to be an enhancement for this.

<b>Expected behavior</b>
The pre-existing text in the autocomplete should be highlighted.

<b>Please tell us about your environment:</b>

<b>OS:</b> Windows 7

<b>Angular version:</b> 2.3.1

<b>PrimeNG version:</b> 2.0.2

<b>Browser:</b> Chrome

<b>Language:</b> TypeScript 2.0.3

<b>Node (for AoT issues):</b> node --version = 6.0.42

**Comment by cagataycivici** [comment]
Issue is not clear.

**Comment by jjacobs33589** [comment]
I'm wondering this too @cagataycivici 
I have a datatable that has quite a few rows in it and I want the existing contents of each cell to be highlighted when the cell comes into focus (clicked or tabbed intO).
This will allow users to tab through the table without having to backspace and delete what's already in each cell. 
On a regular input type, this can be done as shown above with
(click)="$event.target.select()"

I've tried several ways with the primeng datatable but haven't been successful. Is there any way to highlight existing text in an editable datatable when a cell is clicked on?

**Comment by miguellara78** [comment]
Just in case you were still looking for an answer to this, or for future reference for other people, the above is do-able with the flowing code added to the <p-autoComplete /> element:

(onFocus)="$event.target.select()"

P.S. This is true on Angular 7  PrimeNG 7
