### ISSUE TITLE
Primeng Button hover animation only available before you click button

### ISSUE THREAD

**Issue by michaelstievenart** [primefaces/primeng#3886]
Im submitting a bug report

Issue can be shown on standard plunkr as well as on latest Ultima page. (I use Ultima in a project)
http://plnkr.co/edit/Qi2Nw2imLpDUF8NJinYw?p=preview

**Current behavior**
1. When I hover over button before any clicks are made on it, there is a clear hover animation (colour is darker)
2. Once I click button, and I hover over button there is no hover animation present (button retains the darker colour)
3. I have to manually click on page (some other element) in order for the button to become "deselected" adn for the hover animation to be available.

**Expected behavior** - Mirror material design behaviour
1. When I hover over button before any clicks are made on it, there is a clear hover animation (colour is darker)
2. Once I click button, and I hover over button there is hover animation present. Button goes back to preclicked state immediately after being clicked.

* **Angular version:** 4.3.2

* **PrimeNG version:** 4.1.1
Iv looked at current Ultima demo page -> this 'bug' is present

* **Browser:** [Chrome 59.0.3071.115 (Official Build) (64-bit) | Firefox 55.0.2 (64-bit)]

**Comment by cagataycivici** [comment]
Thanks, we'll review this for next week's Ultima update. When you click it, the button background color gets lighter as it has focus but I agree that hovering a focused button should also darken it.

**Comment by michaelstievenart** [comment]
Awesome, great to hear.

**Comment by michaelstievenart** [comment]
Hi has there been any movement on this issue?

**Comment by cagataycivici** [comment]
Decided to handle this at Ultima side, @onursenture what is the material behavior here?

**Comment by onursenture** [comment]
We can check newest material buttons for web here @cagataycivici  https://material-components-web.appspot.com/button.html 

They don't have any hover when ripple is active. But when there is no ripple they prefer darkening.

**Comment by michaelstievenart** [comment]
Hi guys, just to clarify, what is the final decision here?
