### ISSUE TITLE
AutoComplete doesn't show suggestion when typing the same first letter to another dynamic autocomplete

### ISSUE THREAD

**Issue by mengullojerome** [primefaces/primeng#3889]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
<b>Scenario:</b>
There are p-autoComplete components that are dynamically added to a p-dataTable.

<b>STEPS TO REPRODUCE</b>

1. Type 'a' in autocomplete input. A list of suggestions should appear.
2. Select any of the suggestions.
3. Choose a different p-autoComplete and type 'a' once again.

<b>Current behavior</b>
Nothing is shown. (Though logging the suggestions list shows that there are items in the suggestions)

<b>Expected behavior</b>
Autocomplete should show the suggestions dropdown.

<b>Please tell us about your environment:</b>

<b>OS:</b> Windows 7

<b>Angular version:</b> 2.3.1

<b>PrimeNG version:</b> 2.0.2

<b>Browser:</b> Chrome

<b>Language:</b> TypeScript 2.0.3

<b>Node (for AoT issues):</b> node --version = 6.0.42

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=info
