### ISSUE TITLE
npm build --prod error

### ISSUE THREAD

**Issue by giovannicandido** [primefaces/primeng#3895]
angular cli compiler with *--prod* flag throw the error:

> ERROR in ng:///home/giovanni/Projects/atende/cont-platform/client/node_modules/primeng/components/dropdown/dropdown.d.ts.Dropdown.html (6,13): Type 'string' is not assignable to type 'boolean'.

**Comment by johnhwright** [comment]
See #3781

**Comment by giovannicandido** [comment]
Thanks @johnhwright 
Closing as duplicated
