### ISSUE TITLE
Tooltip, Growl and Datagrid support for Angular Universal

### ISSUE THREAD

**Issue by imichelakos** [primefaces/primeng#3899]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[X] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/Qi2Nw2imLpDUF8NJinYw?p=preview

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Our apps should be SEO friendly.
**Please tell us about your environment:**

* **Angular version:** 2.0.X

4.3.0
* **PrimeNG version:** 2.0.X

4.0.0-rc.2
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Tyoescript 2.2.2
* **Node (for AoT issues):** `node --version` =   7.5.0

**Comment by cagataycivici** [comment]
Feedback is welcome here.

**Comment by scurk1415** [comment]
All he wants is that those components work with Angular Universal.

I know that Tooltip gets this error `Event is not defined` with `__metadata("design:paramtypes", [Event]),`

**Comment by NazirTemirov** [comment]
Is there any progress? I want to use Editor https://www.primefaces.org/primeng/#/editor, and I have the same problem during the prerender: Event is not defined.

**Comment by dennyak47** [comment]
Same problems here. pSortableColumn use MouseEvent of window object, not support for Angular Universal

**Comment by wealth** [comment]
stack trace when using growl with ssr:
`
ERROR ReferenceError: window is not defined
    at tick (/home/prog/dev/ang/dist/server.js:51261:17)
    at DomHandler.fadeIn (/home/prog/dev/ang/dist/server.js:51264:9)
    at Growl.handleValueChange (/home/prog/dev/ang/dist/server.js:161478:25)
    at Growl.set [as value] (/home/prog/dev/ang/dist/server.js:161443:22)
    at updateProp (/home/prog/dev/ang/dist/server.js:12910:37)
    at checkAndUpdateDirectiveInline (/home/prog/dev/ang/dist/server.js:12617:19)
    at checkAndUpdateNodeInline (/home/prog/dev/ang/dist/server.js:14184:20)
    at checkAndUpdateNode (/home/prog/dev/ang/dist/server.js:14127:16)
    at prodCheckAndUpdateNode (/home/prog/dev/ang/dist/server.js:14851:5)
    at Object.I.o.ɵvid.n [as updateDirectives] (/home/prog/dev/ang/dist/server.js:154947:49909)
`

**Comment by cagataycivici** [comment]
Growl and DataGrid are removed.
