### ISSUE TITLE
MegaMenu: click doesn't work

### ISSUE THREAD

**Issue by Pranen** [primefaces/primeng#390]
Hi,

Just upgraded to the newest version of primeng and wanted to migrate the megamenu.
I've added a command and an url to the items in the menu, but the click-handler (set a breakpoint there) was never called.

I hope I haven't configured wrong items - here are my navItems:

`this.navItems = [
            {
                label: 'Item1',
                items: [[
                    {
                        label: 'Sub-item 1',
                        command: (event) => {
                            console.log('1', event);
                        }
                    },
                    {
                        label: 'Sub-item 4',
                        url: 'http://www.test.com'
                    }
                ]],
                command: (event) => {
                    console.log('link1', event);
                }
            }]`

Regards,
 Peter

**Comment by cagataycivici** [comment]
We've done some improvements in beta7 regarding menus and I can't replicate this case with it, so marking as resolved.
