### ISSUE TITLE
Reorder and Resize Columns not working with Scrollable true

### ISSUE THREAD

**Issue by bhagath007** [primefaces/primeng#3900]
Hi There,

Below is my sample Data Table. 

<p-dataTable
    [value]="samplesource" 
    resizableColumns="true" 
    columnResizeMode="expand" 
    selectionMode="multiple" 
    scrollable="true" 
    scrollHeight={{soucreTableHeight}} 
   [(selection)]="sampleSelection"
   [headerCheckboxToggleAllPages]="true"
   [globalFilter]="gb" #dt [rows]="10">
            <p-header title="Show/Hide Columns">
                <div style="text-align:right">
                    <p-multiSelect [options]="sourceColumnOptions" [(ngModel)]="columnOptions">
                    </p-multiSelect>
                </div>
            </p-header>
            <p-column [style]="{'width':'38px'}" selectionMode="multiple"></p-column> 
            <p-column *ngFor="let col of columnOptions" [field]="col.field" [header]="col.header" 
                               [style]="{'text-align':col.align}"  [sortable]="true">
            </p-column>
</p-dataTable>

I want to use reorder and resize columns but it's working when scrollable is true.

Currently I am using -
* **Angular version:**4.2.6
* **PrimeNG version:**4.1.2

Can anyone help me on this?

Thanks!

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview

**Comment by bhagath007** [comment]
Hi There,

I have replicated the issue in the below plunkr link. Please go through once and help me. 
Issue: Reorder Columns and resize columns not working when scrollable = true

http://plnkr.co/edit/DojpxL5czcNTW9pyN5CK?p=preview

Thanks!
