### ISSUE TITLE
OrderList / PickList icon in input field looks like crap (Barcelona Theme)

### ISSUE THREAD

**Issue by queueseven** [primefaces/primeng#3902]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
The icon in the input field is rendered over the text

**Expected behavior**
The icon should not be rendered over the text

**Minimal reproduction of the problem with instructions**

Add the `filterBy` property to the OrderList in the demo application's sample page, so line 230 looks like this:

    <p-orderList filterBy="brand" [value]="orderListCars" [listStyle]="{'height':'250px'}" [responsive]="true" header="OrderList">

Result:

![image](https://user-images.githubusercontent.com/3126597/30271633-521ec2ce-96f1-11e7-9081-ca29ff1a6b0c.png)

**Comment by cagataycivici** [comment]
Thanks, @Merve7 can you check this on Barcelona ?

**Comment by MarMic1** [comment]
Same issue on Ultima Theme.(Picklist)

**Comment by cagataycivici** [comment]
Please use premium template forums, the support monitors them, this tracker is for PrimeNG itself.
