### ISSUE TITLE
Bug if i use more than one pDraggable zone

### ISSUE THREAD

**Issue by cyberrranger** [primefaces/primeng#3903]
[X] bug report => Search github for a similar issue or PR before submitting
**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/14PGggZsvu64jVVDq9TV?p=preview

**Minimal reproduction of the problem with instructions**
if i drag "pDraggable one" over "pDroppable two" i become a green "+" icon

![img_0269](https://user-images.githubusercontent.com/21671762/30272991-5c599132-96f7-11e7-8a7d-e0bbb79bfbeb.jpeg)

* **Angular version:** 4.3

* **PrimeNG version:** 4.1.3

 
* **Language:** [TypeScript]

**Comment by burfom88** [comment]
I'm having the same problem. It doesn't seem to matter what the names of the draggable and droppable elements are - I can drag any element that has 'pDraggable' onto any element that has 'pDroppable'.

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
