### ISSUE TITLE
Function to call a clear field on a calendar by a external component

### ISSUE THREAD

**Issue by coppolaop** [primefaces/primeng#3904]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
It's not possible to clear the calendar field through an external button

**Expected behavior**
A function to clear the field that can be called by an external component

**Comment by cagataycivici** [comment]
You can just clear the bound value and calendar will reflect the change.
