### ISSUE TITLE
multiSelect's onChange not fired if selected items are set programmatically

### ISSUE THREAD

**Issue by Zvezdin** [primefaces/primeng#3905]
**I'm submitting a ...** 
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
The onChange method of a p-Multiselect is not fired if the selected items (two-way ngModel) are changed programmatically. The component's selected items are updated correctly.
**Expected behavior**
The onChange method should fire.

If the current is the correct behavior, would you recommend me a way to fire the component's onChange method. I am using it in a datatable for filtering. Since both are declared in the html, I don't know how to filter the table from my TypeScript.

**Setup**

My setup and code is exactly the same as the multiselect in [your datatable filter documentation.](https://www.primefaces.org/primeng/#/datatable/filter)

**Minimal reproduction of the problem with instructions**

Have a p-multiselect component and change its values programmatically.

**Comment by cagataycivici** [comment]
This is expected, onChange is for user interaction like other on* events. This applies to whole components. Since you do it programmatically, you can just call your onChange handler manually.

**Comment by Zvezdin** [comment]
But how do I call my onChange handler manually, if the onChange code is declared in the html? I have to somehow trick the multiselect into firing that event, but I don't know how.

**Comment by MobackChetanKumar** [comment]
Do we have an event which will fire when multi-select checkbox selected??
