### ISSUE TITLE
Virtual scroll + lazy load repeating rows 

### ISSUE THREAD

**Issue by ak05** [primefaces/primeng#3907]
When using virtual scroll and lazy loading new data are displayed with already loaded records. So you have to scroll all the time from the beginning of the table. You can reach last records only if all records are already loaded

primeng 4.2.0-rc.1

`<p-dataTable [value]="objects" loadingIcon="fa-spinner"
                     scrollable="true" [rows]="11" virtualScroll="true" scrollHeight="451px"
                     lazy="true" [totalRecords]="totalRecords" (onLazyLoad)="loadObjectsLazy($event)">`
`    ...`
`</p-dataTable>`

`loadObjectsLazy(event: LazyLoadEvent) {`
`      this.searchService.getObjects(this.search).then((data: any) => {`
`        this.totalRecords = data.totalOfRecords;`
`        this.objects = data.objects;`
`        this.search.offset = this.search.offset + data.objects.length;`
`      });`
`}`

**Comment by Mysame** [comment]
This is still very much present in 4.2.0. Sure it "works", but the way it looks is really bad. If you have a lazy-load table showing values from 200 -> 0, you'll keep repeating 200 -> 190 until it suddenly manages to load something within the "timer" and suddenly shows 140 (for example). Really lazily done.

**Comment by ryanreliford** [comment]
Hi,
I'm still seeing this issue in primeng 4.2.2.  If attribute [rows] is set to 100, [lazy]="true", and virtualScroll="true" and I fetch 100 datarows, I can scroll to the bottom of the table but my (onLazyLoad) method does not fire.  If I decrease [rows] attribute to 10, the (onLazyLoad) event fires and the $event meta has rows = 20 but the data in the table is looping as described in the initial defect description.  Can someone please advise?
 
angular-cli: 1.0.0-beta.28.3
node: 6.10.0
os: win32 x64
@angular/animations: 4.4.4
@angular/cli: 1.4.1
@angular/common: 4.4.4
@angular/compiler: 4.4.4
@angular/compiler-cli: 4.4.4
@angular/core: 4.4.4
@angular/forms: 4.4.4
@angular/http: 4.4.4
@angular/language-service: 4.4.4
@angular/platform-browser: 4.4.4
@angular/platform-browser-dynamic: 4.4.4
@angular/router: 4.4.4

**Comment by sourour** [comment]
Hi, Any updated please ? I get same issue using primefaces 6.1

**Comment by MoxCrox** [comment]
Unfortunatly , as of PrimeNG 8.0.0, this is always an issue....
