### ISSUE TITLE
Column reordering does not work with Scrollable Table

### ISSUE THREAD

**Issue by bhagath007** [primefaces/primeng#3910]
Hi There,

#3900 

I have replicated the issue in the below plunker link. Please go through once and help me.
Issue: Reorder Columns and resize columns not working when scrollable = true

http://plnkr.co/edit/hUIloCBeA34gMMoSnhA8?p=preview

Thanks!

**Comment by winarg** [comment]
Event onColReorder fires correctly but the columns are not drawn
