### ISSUE TITLE
DataTable+Virtual Scrolling+LazyLoad doesn't update on scrolling. It changes on click.

### ISSUE THREAD

**Issue by goluhaque** [primefaces/primeng#3914]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://plnkr.co/edit/CoSqvdoZkVnA4vDpSMWD

**Current behavior**
Next set of rows do not updated on scrolling. Click on the datatable, the rows then get updated. Check the console and you will find that an onClick listener has been fired. Click again, the previous page of data gets displayed. 

**Expected behavior**
DataTable should update by itself. Clicking shouldn't create a difference.

**Minimal reproduction of the problem with instructions**
Scroll down to row 41/45. Repeat the steps given in the current behaviour section.

**Please tell us about your environment:**

* **Angular version:** 4.2.6

* **PrimeNG version:** 4.2.0-rc.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome Version 60.0.3112.113 (Official Build) (64-bit)

**Comment by cagataycivici** [comment]
Unable to replicate with 4.2.2, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=info
