### ISSUE TITLE
When I Build as --prod I get this error

### ISSUE THREAD

**Issue by Ramprits** [primefaces/primeng#3916]
ERROR in ng:///C:/AdventureWorkApplication/AdventureWorkApplicationClient/pluralsight-primeng/node_modules/primeng/components/dropdown/dropdown.d.ts.Dropdown.html (6,13): Type 'string' is not assignable to type 'boolean'.
ERROR in ng:///C:/AdventureWorkApplication/AdventureWorkApplicationClient/pluralsight-primeng/node_modules/primeng/components/dropdown/dropdown.d.ts.Dropdown.html (6,13): Type 'string' is not assignable to type 'boolean'.

**Comment by charlatan154** [comment]
[#3781](https://github.com/primefaces/primeng/issues/3781)

**Comment by cagataycivici** [comment]
Duplicate
