### ISSUE TITLE
Tables Inside Borders Problem

### ISSUE THREAD

**Issue by agustin18** [primefaces/primeng#3924]
Sorry for my English and my programming level, I'm very new

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview

**Current behavior** and **Expected behavior**

Some time ago I downloaded from the primeng page the expandable tables function, and it worked in a separate project. But now that I want to add it to a project that I'm working on, and it doesn't work properly. I can't see the borders of the table, if I add borders to the table  only see the outside ones, but the inside ones its impossible whatever i do. I give you a screenshots of how I see it in the separate project

https://image.prntscr.com/image/N7lAZ8TWQI_wskPakKsImw.png
[https://image.prntscr.com/image/N7lAZ8TWQI_wskPakKsImw.png](url)
 and how it looks in the project I want to insert.

https://image.prntscr.com/image/qxsld7SCQJqMSuEOJprD8Q.png
[https://image.prntscr.com/image/qxsld7SCQJqMSuEOJprD8Q.png](url)

I tried to load the plunker but I don't think I did it correctly.

Thank you so much for everything.

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **PrimeNG version:**  "4.2.0-rc.1",
 

* **Browser:** [Firefox 55.0.3 (32-bits)]
 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =  6.11.3

**Comment by cagataycivici** [comment]
Please use forum for support requests. Thank you.
