### ISSUE TITLE
Date range picker display bug

### ISSUE THREAD

**Issue by vadjs** [primefaces/primeng#3926]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://primefaces.org/primeng/#/calendar

**Current behavior**

When date range picked more than 1 current month appears display bug: several days in range are not highlighted.

**Expected behavior**

All days sould be highlighted.

**Minimal reproduction of the problem with instructions**

http://primefaces.org/primeng/#/calendar
Pick 1 aug 2017 as start of range, pick 30 sept as end of range. You will see that 30, 31 aug and 1 sept will be inactive.

**What is the motivation / use case for changing the behavior?**

Users now confusing by this bug. Stopping cunfusing users.

**Please tell us about your environment:**

* **Angular version:** 4.2.4

* **PrimeNG version:** 4.2.0

* **Browser:** all

 
* **Language:** all

* **Node (for AoT issues):** `node --version` =

**Comment by FergusZhou** [comment]
+1

**Comment by wryly** [comment]
+1

**Comment by dandreaj** [comment]
+1
