### ISSUE TITLE
OrderList throws a "Cannot read property getBoundingClientRect of undefined"

### ISSUE THREAD

**Issue by claudiuconstantin** [primefaces/primeng#3933]
**I'm submitting a ...**
```
[X] bug report
[ ] feature request
[ ] support request
```

* **Minimal reproduction of the problem with instructions**
Reproducible in the official demo: https://www.primefaces.org/primeng/#/orderlist

1. Select an item
2. Unselect the item
3. Press any reorder button -> `ERROR TypeError: Cannot read property 'getBoundingClientRect' of undefined`

* **Angular version:** 4.3.6
* **PrimeNG version:** 4.2.0

Note: possibly the same problem as [here](https://github.com/primefaces/primeng/issues/1292) or [here](https://github.com/primefaces/primeng/issues/1002).

**Comment by cagataycivici** [comment]
Fixed via PR, thank you.
