### ISSUE TITLE
MessageService doesn't display separate messgaes

### ISSUE THREAD

**Issue by jdell64** [primefaces/primeng#3934]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/d1WHJnVWYyAMQnFF7Zau?p=preview

**Current behavior**
All messages, regardless of level, are treated at the same level.

**Expected behavior**
 I could be using the service incorrectly, but I imagine when I `addAll` it should add separate messages and when I display them, it should display them all separately.

**Minimal reproduction of the problem with instructions**
In the producer of the messages:
```
testMessageService() {
        this.messageService.addAll([
            {severity: 'success', summary: 'Service Message', detail: 'Via MessageService (severity: success)'},
            {
                severity: 'info',
                summary: 'Fun Fact (severity: info)',
                detail: 'Machines to make frozen beverages were invented by Omar Knedlik in the late 1950s.'
            },
            {severity: 'warn', summary: 'Obvious Warning! (severity: warn)', detail: 'Hot water is Hot'},
            {severity: 'error', summary: 'Error (severity: error)', detail: 'you cannot divide by 0.'},
        ])
    }
```
in the consumer/displayer of the messages: 
```
 ngOnInit() {
        this.messageService.messageObserver.subscribe((msg) => {
            console.log(msg);
            this.feedbackMessages.push(msg)
        });
    }
```
see plunker
http://plnkr.co/edit/d1WHJnVWYyAMQnFF7Zau?p=preview

**What is the motivation / use case for changing the behavior?**
To display multiple messages to a user. 

* **Angular version:** 
@angular/cli: 1.3.2
node: 6.11.1
os: darwin x64
@angular/animations: 4.3.6
@angular/cdk: 2.0.0-beta.8
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/core: 4.3.6
@angular/flex-layout: 2.0.0-rc.1
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/router: 4.3.6
@angular/cli: 1.3.2
@angular/compiler-cli: 4.3.6
@angular/language-service: 4.3.6

* **PrimeNG version:** 
    "primeng": "^4.2.0",

* **Browser:** 
all
 
* **Language:** 
all

**Comment by cagataycivici** [comment]
Duplicate #3784

**Comment by markusu49** [comment]
I don't think this is a duplicate of #3874. Displaying multiple messages with `addAll` works fine with p-growl, but with p-messages they look strange (see plunker provided by @jdell64).
