### ISSUE TITLE
Click in dropdown button autocomplete dont show suggestions list

### ISSUE THREAD

**Issue by bondcs** [primefaces/primeng#3935]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
This issue is visible in primeng demonstration page.

**Current behavior**

Clicking in dropdown button autocomplete.

Primeng: 4.2.0
Angular: 4.1.2
Os: Ubuntu
Browsers testing: Chrome, Firefox

Thanks for

**Comment by pecko** [comment]
It works with primeng 4.1.3.

**Comment by reinpeter** [comment]
Reproduced here. Introduced in 4.2.0.
See also https://github.com/primefaces/primeng/issues/3829
which includes rootcause/fix.

**Comment by cagataycivici** [comment]
Duplicate 3829
