### ISSUE TITLE
Add baseZIndex and autoZIndex property to Calendar and Dialog

### ISSUE THREAD

**Issue by Abhinav3414** [primefaces/primeng#3940]
**I'm submitting a ...**   
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**Current behavior**

I am using modal dialogue and p-calendar inside it, but due to incremental z-index feature of primeNG, calendar goes in background as I click on modal's input field of p-calendar.
Is there any fix provided by PrimeNG on this, other than setting z-index manually (at a higher value) to DOM handle.?

**Expected behavior**

My requirement is that when the calendar component is still active, and I click inside input field of calendar, Calendar should not go back of modal. It should remain at higher z-index than p-dialog.

**Environments:**
Windows 10, Eclipse Neon.3 Release (4.6.3)

latest 4 x of angular and prime

**Comment by SimonGeering** [comment]
I am also able to replicate this issue.

**Comment by mx0c** [comment]
How do i fix this problem?

**Comment by Abhinav3414** [comment]
Not a permanent or not a standard solution, but I am using important tag for now, as a work around.
.ui-datepicker {
	z-index: 100000 !important;
}

**Comment by mx0c** [comment]
Thanks for your reply! Fixed it now like this: `<p-calendar placeholder="endDate" [showIcon]="true" [style]="{'position': 'fixed', 'overflow': 'visible', 'z-index': '999'}" [(ngModel)]="endDate"></p-calendar>`

**Comment by cagataycivici** [comment]
To disable automatica layering, set [autoZIndex]="false", if you want to keep it but want to use a different higher value then 1000 use [baseZIndex]="100000". If autoZIndex is true then when calendar is displayed zIndex would be 100001.

**Comment by sgentile** [comment]
This should not have been marked as fixed - it isn't fixed:

![image](https://user-images.githubusercontent.com/132404/38680903-7266052e-3e35-11e8-9933-fe806906df2a.png)

```
div *ngSwitchCase="StartDate'">
              <p-calendar [autoZIndex]="false" [baseZIndex]="9999"  [showIcon]="true"></p-calendar>
            </div>
```

It is hidden by the p-table - no matter what I set the baseZIndex it is still 'hidden' by the table header

**Comment by leonetosoft** [comment]
@sgentile mesma coisa aqui.

https://ibb.co/n6kKhd

**Comment by tiger5226** [comment]
Yeah, I have the problem too...

<img width="354" alt="screen shot 2019-02-22 at 8 34 12 pm" src="https://user-images.githubusercontent.com/3402064/53279778-44b89600-36e1-11e9-9a74-b3214b03f931.png">

It just really sucks when you can use the library so easily and then you run into something like this without a way to fix it.

**Comment by emregozel** [comment]
I have a quick fix. If you are using dialog component fix this CSS with calendar crop problem.

```
::ng-deep .ui-dialog-resizable .ui-dialog-content {
    overflow: unset;
}
```

**Comment by Hypenate** [comment]
I added ` appendTo="body"` to get it to work.
