### ISSUE TITLE
editor readonly property is not working second time.

### ISSUE THREAD

**Issue by saikiranmandhala** [primefaces/primeng#3941]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
In my page i have multiple editors and i am using [readonly]="isEditable" property to set dynamically the behavior of the editor. On the screen i am also providing a button to User to enable/disable a specific editor.
readonly feature is working only for the first time.

**Comment by QuentinLeGoff** [comment]
#3536 
Seems to be a problem with Quill. I tried to play with the quill attribute and it didn't work.

**Comment by cagataycivici** [comment]
Seems to be a quill issue
