### ISSUE TITLE
Can We Add headers to children in Tree table

### ISSUE THREAD

**Issue by csomethingr** [primefaces/primeng#3945]
I have a Parent Tree and a Children Tree and As I Can set  headers for Parent Tree I need to set headers for children tree is there a possible way to do so?
A sample of what i want is show as below using TreeTable
![ptreetable](https://user-images.githubusercontent.com/31129278/30431284-ba6662b0-997b-11e7-8e3d-17b858c093b3.png)

**Comment by cagataycivici** [comment]
Please use forum for questions.
