### ISSUE TITLE
Ultima 4.2 has many TS Lint and SonarQube errors

### ISSUE THREAD

**Issue by kc13greiner** [primefaces/primeng#3949]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
I am using Ultima 4.2 for a website. After copying in the app.*.ts files and running Angular CLI -> ng lint I get dozens of errors. There should be no errors.

As part of my build process, I run SonarQube. The Ultima app.*.ts files have CRITICAL and MAJOR issues, as well as several MINOR issues.

There are also many unused imports.

**Expected behavior**
The code should at least be free of TS Lint errors, but SonarQube would be nice too

**Minimal reproduction of the problem with instructions**
Run `ng lint` or `sonar-scanner` on the Ultima 4.2 code

**What is the motivation / use case for changing the behavior?**
My build breaks because of the Ultima code

**Comment by cagataycivici** [comment]
Fixed in latest Ultima release.
