### ISSUE TITLE
exportCSV with custom delimiter instead of just comma

### ISSUE THREAD

**Issue by nat2k5us** [primefaces/primeng#3950]
Is it possible to change the delimiter to be a semicolon in the exportCSV ?

maybe like below when we want to use semicolon as the delimiter instead of comma.            (click)="dt.exportCSV(';')"

**Comment by nat2k5us** [comment]
Never mind - the option is already avaialbe to be set on the datatable as "csvDelimiter"

**Comment by Sumragen** [comment]
@nat2k5us Hello! 
Maybe, if this is not an irrelevant ticket now, does it make sense to close it?

**Comment by nat2k5us** [comment]
Yes - please close it
