### ISSUE TITLE
How to prevent focus of filter on open of dropdown

### ISSUE THREAD

**Issue by marcodafonseca** [primefaces/primeng#3951]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ x] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

**Current behavior**
When opening a dropdown that has "filter = true" the input text box gains focus by default. 

**Expected behavior**
The above is somewhat frustrating from a mobile device. How does one disable the focus, so the keyboards on mobile don't appear?

**Minimal reproduction of the problem with instructions**
```
<p-dropdown [filter]="true"></p-dropdown>
```

**What is the motivation / use case for changing the behavior?**
Make usability from a mobile device more enjoyable

**Please tell us about your environment:**
OS: Win10
IDE: VS2015 update 3
PM: Nuget\npm
Server: IIS

* **Angular version:** 2.0.X
Angular 2.0.0

* **PrimeNG version:** 2.0.X
PrimeNg 2.0.6

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Any
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS

* **Node (for AoT issues):** `node --version` =   
6.9.1

**Comment by cagataycivici** [comment]
Please use forum for questions.
