### ISSUE TITLE
VirtualScroller for MultiSelect

### ISSUE THREAD

**Issue by rklempert** [primefaces/primeng#3952]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**What is the motivation / use case for changing the behavior?**
When using Multiselect with 3000-8000 or more items the control takes 5-6 seconds to open and every checkbox takes 3-4 seconds to register a click.  Adding in Virtual Scrolling would make this control faster with large datasets. Tree Control could use similar enhancement. Datatable already supports this.

**Please tell us about your environment:**
Windows 7, VS Code

* **Angular version:** 
4.3.6

* **PrimeNG version:** 
4.1.3

* **Browser:** all. worse in IE
 
* **Language:** TypeScript 2.4

* **Node (for AoT issues):** `node --version` =

**Comment by Franky238** [comment]
It will be better to add lazy behavior. And lazy behavior with combination with virtual scrolling will have very good performance.

**Comment by harikrishnan-u01** [comment]
Hi Team,

I am using the multiselect in my project (IE 11 and above). This works for smaller datasets.
There is a scenario were we have 2500 records to be displayed in this multiselect. But this is causing performance issues as mentioned in the above description.

Is there any fix planned for this? virtual scrolling would really help.

Thanks,
Hari

**Comment by harikrishnan-u01** [comment]
Hi Team,

Is there a limitTo attribute so that we can specify how many values should be displayed in the multi-select? This way for huge datasets we can display only say 20 values and if needed the user can search and get the values what they need.

Is this possible to do as a quick fix? 

Thanks,
Hari

**Comment by leonardolessa** [comment]
Hi @cagataycivici,
Is there any plan to work on this issue?

**Comment by anafreitas** [comment]
Hi @cagataycivici,
Is there any plan to work on this issue?

**Comment by cuneytcalishkan** [comment]
Hello,
What about simple dropdowns? Any plan to integrate this feature to p-dropdown component?
Cheers,
Cuneyt
