### ISSUE TITLE
Updating sorted data causes shuffle behavior

### ISSUE THREAD

**Issue by caseylutz** [primefaces/primeng#396]
I've written up a plnkr here showcasing the issue. 

https://plnkr.co/edit/thxW3u?p=preview

Steps to reproduce are as follows: 

1. Bind a data set with a field that won't change often between cycles
2. Sort by the field (in this case, sort by Class, it doesn't change much)
3. Initiate a change to the data (in this plunkr, click The Button)
4. Now cause an event cycle (move your mouse over the table or something)

Long and short of it is that the data rows in the dataTable will all start to "jumble" around.

**Comment by GraemeSMiller** [comment]
Any update on this bug? Is it likely to make it into Beta 9?

**Comment by cagataycivici** [comment]
I've replicated and added a fix that seems to prevent resort which is main cause of shuffle.

**Comment by GraemeSMiller** [comment]
Ok - so does that mean it now no longer re-sorts correctly if the underlying data changes?

E.g. Apply sort by date, change a date value and it won't be sorted until you manually re-apply sort on data column?

**Comment by cagataycivici** [comment]
No, it should still sort when underlying data changes, but only once, with this bug it was sorting even on mouseover  :)

**Comment by GraemeSMiller** [comment]
Great Thanks for that - it is a really nice feature to have.

**Comment by mikedunham** [comment]
This appears to be happening in 4.1.3 and 4.2.1

**Comment by LuminalZero** [comment]
This issue is still present in 4.3.0

**Comment by LuminalZero** [comment]
For anyone still running into this...
This bug presented itself via a DataTable that had the immutable property set to false. After sorting the DataTable and then altering one of the records, the shuffling behavior appeared while moving the mouse (i.e. during change detection cycles). I was able to fix my particular problem by making a ViewChild of the DataTable, and then calling this.dataTableViewChild.preventSortPropagation = true after altering the record.
