### ISSUE TITLE
Remove enableLoader and built-in loading status management from lazy

### ISSUE THREAD

**Issue by steve3d** [primefaces/primeng#3963]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Current version of datatable will show the loading indicator if it's enabled and will hide the the loading indicator when some data is loaded/fetched by the `onLazyLoad` event, In some cases, if there is no data at all, the loading indicator will never be hidden.

Under any situation, lazy loaded with no data is correct, but current design is no way to detect this. so when lazy load get no data at all, the loading indicator will never be hidden. In visual, this seems that the data load is never end, but the load process is correctly finished with just no data.

**Comment by xtoff** [comment]
I have the same issue

**Comment by tapaccos** [comment]
Hi thre xtoff ,could you mind explaining how?

I have tried checking for the length to the variable that the datatable is looking for and tried setting it to 
[], null even undefined.
The weird thing is that the empty message is shown on table yet spinning still going on

**Comment by xtoff** [comment]
In my loadLazy function (onLazyLoad), I set the value of my datatable [], the first time when this function is called. But in my case there is no data loaded on page load. Only when I click a search button. Maybe you should check if your value binded to your datatable is empty and set it [] in you lazy load function?

**Comment by ejamsa** [comment]
Another solution would be to set lazy to false and use loading property instead.

**Comment by cagataycivici** [comment]
So when there is no data to load, change detection is not triggered so loading indicator is not turned off, I guess best solution is removing the built-in loading for lazy mode and let the page author manage it manually.
