### ISSUE TITLE
Freeze Growl message onHover and remove after onMouseLeave

### ISSUE THREAD

**Issue by MrBlaise** [primefaces/primeng#3965]
**I'm submitting a ...** 
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

I would like to be able to freeze a growl message when I hover on it and clear it after a delay when I move away the mouse. For example I set life to 3000, after 2 seconds I hover on the message it stays there, when I move the cursor away it would disappear after some time (maybe equal to life or less)

To do this I only need an onMouseLeave event and access to the current removeAll timeout.

Thank you!

**Comment by cagataycivici** [comment]
Growl is removed in favor of Toast.
