### ISSUE TITLE
DataTable displays Emptymessage twice when using frozen columns

### ISSUE THREAD

**Issue by jizza** [primefaces/primeng#3966]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/oX8VCCP8mzlU4dMK5Wiu?p=preview

**Current behavior**

When using frozen columns, the emptymessage is displayed in both the frozen columns and the unfrozen columns

**Expected behavior**

When there are no results, the message should appear only once like it does when not using frozen columns

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.3.6

* **PrimeNG version:** 4.0.3

* **Browser:** [all]

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
