### ISSUE TITLE
RTL mode for Tree

### ISSUE THREAD

**Issue by abadr82** [primefaces/primeng#3968]
The RTL Mode didn't work correctly with tree Component. I had to add this entry in the CSS Primeng file.

.ui-rtl .ui-tree .ui-treenode-children {
    margin: 0;
    padding: 0 1em 0 0;
}

**Comment by EitanD1** [comment]
but you still need to change the caret from 'fa-caret-right' to 'fa-caret-left'

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
