### ISSUE TITLE
Maximum selectable items for Listbox

### ISSUE THREAD

**Issue by mengullojerome** [primefaces/primeng#3969]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
<b>FEATURE REQUEST</b>
Please give p-listbox with checkboxes a maximum/minimum number of checked options.

<b>Please tell us about your environment:</b>

<b>OS:</b> Windows 7

<b>Angular version:</b> 2.3.1

<b>PrimeNG version:</b> 2.0.2

<b>Browser:</b> Chrome

<b>Language:</b> TypeScript 2.0.3

<b>Node (for AoT issues):</b> node --version = 6.0.42

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
