### ISSUE TITLE
DataTable does not perform lazy loading as expected

### ISSUE THREAD

**Issue by rmccleave559** [primefaces/primeng#3974]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/SF8dZimFaCxAErABwhIT?p=preview

**Current behavior**
When loading the dataset with object Ids you can see the numbers go out of sync when a lazy load occurs ie row 40 has an Object ID of 20. 
![image](https://user-images.githubusercontent.com/15269330/30534881-021c41f4-9c58-11e7-8ddd-6ecd0f52257a.png)

Changed the rows property to 40 and the loading of data on the display seems to broken. It loads the data correctly but on certain parts off the scroll there are no rows loaded. 
![image](https://user-images.githubusercontent.com/15269330/30534902-17bd693e-9c58-11e7-8df9-042ce8a4ab8c.png)

**Expected behavior**
I would expect the the scroller to load the next 40 before I see row 40 and for it to display the rows immediately after.

**Minimal reproduction of the problem with instructions**
Just scroll through the datatable with the row property set to 20 and then try it on 40.

**What is the motivation / use case for changing the behavior?**
So it works?

Windows 10, VS Code, Angular CLI

* **Angular version:** 2.0.X
4.2.4

* **PrimeNG version:** 2.0.X
4.2.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 
Firefox
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.3.3

**Comment by rmccleave559** [comment]
Had to fix the plunk, it didn't save :(

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=info

**Comment by rmccleave559** [comment]
plunker is still showing the case I presented
