### ISSUE TITLE
MultiSelect add support for keyboard events

### ISSUE THREAD

**Issue by brachi-wernick** [primefaces/primeng#3975]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

**Expected behavior**
when multiselect panel is closed, and it is in focus, I want be able to open it by `SPACE`, then focus will be on the first option, then `KEYDOWN` and `KEYUP` should select the next option and highlighte it.
when hit `SPACE` the highlited option is checked or unchecked.
hitting `tab` will close the panel and move the focus to the multiselect itself. (closed)

![keyboard](https://user-images.githubusercontent.com/3658085/30536133-54a086d2-9c6d-11e7-8ea0-0d0329dd83b8.gif)

**Comment by jordache16** [comment]
Are there plans to support this in an upcoming release? This seems like a glaring missing piece with the multi-select control.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
