### ISSUE TITLE
Issue with not empty target list at initial (PickList)

### ISSUE THREAD

**Issue by gtzinos** [primefaces/primeng#3979]
Hi,

I found an opened issue from may on stackoverflow, can someone help us ?

https://stackoverflow.com/questions/43978134/how-to-exclude-selected-items-in-primeng-picklist

**Comment by Sumragen** [comment]
@gtzinos Hello,

Could you provide more detailed information regarding this issue?
As I understood, the main idea is changing list of selected items programmatically. To make some items as selected and not. Am I correct?

**Comment by gtzinos** [comment]
Hi @Sumragen, i am sorry for misunderstanding, the problem is when you define the target list as a non empty array. Then it doesn't remove from the source list the selected items, it just show them duplicate at the left and at the right side. Is it clear now ?

**Comment by Sumragen** [comment]
@gtzinos 
Yes, now it clearly for me.
Thanks.

**Comment by cagataycivici** [comment]
Much better is you managing this on your side, so when you provide the source, also remove the items from source.

**Comment by gtzinos** [comment]
@cagataycivici Really ?

**Comment by crissty** [comment]
Hi guys,
I also think that this behavior will have to be controller by the component PickList.

Any update about this matter?

Thank you!
