### ISSUE TITLE
Visible flag support for TabMenu

### ISSUE THREAD

**Issue by k20human** [primefaces/primeng#3980]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/GdTQLcY39KyrhRMFxY94?p=preview

**Current behavior**
`visible` flag is not supported by TabMenu component, meanwhile MenuItem interface contains such property

**Expected behavior**
If `visible` property is set to false, tabMenu item must be hidden.

**What is the motivation / use case for changing the behavior?**
Same problem has described in #3072

* **PrimeNG version:** 4.2.1

**Comment by k20human** [comment]
Hi,

Any news on this ?

**Comment by feder89** [comment]
https://github.com/primefaces/primeng/commit/19c59612b6876eb3fccf1a9603495eabf4ee1285
This solution doesn't works, I'm using primng 4.2.2 and on tabmenu component, visible property has no effect.
My workaround on file \primeng\components\tabmenu\tabmenu.js is:



`<div [ngClass]=\"'ui-tabmenu ui-widget ui-widget-content ui-corner-all'\" [ngStyle]=\"style\" [class]=\"styleClass\">`           

`<ul class=\"ui-tabmenu-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all\" role=\"tablist\">`

`<ng-template ngFor let-item [ngForOf]=\"model\">`
     
`<li *ngIf=\"item.visible===true\"  [ngClass]=\"{'ui-tabmenuitem ui-state-default ui-corner-top':true,'ui-state-disabled':item.disabled, 'ui-tabmenuitem-hasicon':item.icon,'ui-state-active':activeItem==item}\" [routerLinkActive]=\"'ui-state-active'\" [routerLinkActiveOptions]=\"item.routerLinkActiveOptions||{exact:false}\">         `
           
`<a *ngIf=\"!item.routerLink\" [href]=\"item.url||'#'\" class=\"ui-menuitem-link ui-corner-all\" (click)=\"itemClick($event,item)\" [attr.target]=\"item.target\" [attr.title]=\"item.title\">  `

`<span class=\"ui-menuitem-icon fa\" [ngClass]=\"item.icon\" *ngIf=\"item.icon\"></span>                   <span class=\"ui-menuitem-text\">{{item.label}}</span>`
</a>

`<a *ngIf=\"item.routerLink\" [routerLink]=\"item.routerLink\" [queryParams]=\"item.queryParams\" class=\"ui-menuitem-link ui-corner-all\" (click)=\"itemClick($event,item)\"\n                        [attr.target]=\"item.target\" [attr.title]=\"item.title\">`

`<span class=\"ui-menuitem-icon fa\" [ngClass]=\"item.icon\" *ngIf=\"item.icon\"></span>
<span class=\"ui-menuitem-text\">{{item.label}}</span>`
`</a>`
`</li>`
`</ng-template>`
`</ul>`
`</div>`
` ",`
