### ISSUE TITLE
Empty p-dropdown UI looks broken

### ISSUE THREAD

**Issue by ASK83** [primefaces/primeng#3983]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
```
**Current behavior**
When the options list is empty the dropdown UI looks broken as bellow.

![capture](https://user-images.githubusercontent.com/17345249/30559301-cbe089d4-9c79-11e7-8a3d-658a7e62c3e3.PNG)

**Expected behavior**
Empty dropdown should look like a regular dropdown but no optoins to select from.This was working correctly before the latest two new versions

**What is the motivation / use case for changing the behavior?**
Better user interface. Because as it is right now the control looks broken if empty.

**Please tell us about your environment:**

* **Angular version:
4.4.1

* **PrimeNG version:
4.2.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
ALL
 
* **Language:** TypeScript 2.4.2

* **Node (for AoT issues):** `node --version` =

**Comment by kito99** [comment]
@cagataycivici this is a big issue :-).

**Comment by cagataycivici** [comment]
Seems to be a duplicate

https://github.com/primefaces/primeng/issues/4013
