### ISSUE TITLE
TreeTable: allow to configure how to select rows

### ISSUE THREAD

**Issue by ili** [primefaces/primeng#3986]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
It would be very useful to override current selection behavior for `TreeTable` in `selectionMode = checkbox` 
You see, now selection is done via row click & expand is done via click on expand toggle. Expand toggle - is very small so, we do play pixel hunting. Another bad point is: if I do need to see what is checked and what is not in collapsed node I do need to expand it, and it is very often when I do miss small toggle and check/select (or uncheck/unselect) node instead of expanding it. Because check state/selection  is changed for all sub-nodes I do loose current model state.

In another words I do edit my data occasionally without any need. And what if there are 30-50 sub-nodes in tree, and before I have occasionally changed selection there were selected only 5? And I do not remember witch to restore them manually. 

So you see, in case when I'm using `TreeList` to edit one to many relationships it is not a convenient to use row click for selection and toggle click for expand.

It would be great to have an option, to change behavior as:
* expand or collapse on row click
* change selection on check box click

**Comment by cyberrranger** [comment]
overwrite  (onNodeSelect)="nodeSelect($event);" to expand or collapse on row click

`
	nodeSelect(event) {
		event.expanded = !event.expanded;
		this.tree = [...this.tree];
}`

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
