### ISSUE TITLE
AutoComplete cuts long placeholder text

### ISSUE THREAD

**Issue by bossqone** [primefaces/primeng#3989]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/JHyOauB8hM0HHfsXGhrk?p=preview

**Current behavior**
Too long placeholder text is cut when AutoComplete component has `[multiple]=true`.

**Expected behavior**
Display whole placeholder.

* **PrimeNG version:** 4.2.1

**Comment by cagataycivici** [comment]
You can use inputStyle to adjust this.
