### ISSUE TITLE
Datatable with resizableColumns="true" will break if table contains hidden columns

### ISSUE THREAD

**Issue by unaor** [primefaces/primeng#3991]
As described if a table contains an hidden column it will fail

```
<p-dataTable #dt [value]="compliances" [rows]="25" [paginator]="true" (onFilter)="updateTotal()"
 [scrollable]="true" scrollHeight="500px" [rowStyleClass]="isExcluded" [rowHover]="true"
 selectionMode="multiple" [(selection)]="selectedCompliances" dataKey="macAddress" resizableColumns="true">
    <p-column [style]="{'width':'38px'}" selectionMode="multiple" styleClass="compliance-table-checkbox"></p-column>
    <p-column field="date" header="Date"></p-column>

    <p-column field="switchIp" [filter]="true" filterPlaceholder="Switch IP"></p-column>

    <p-column field="description" [filter]="true" filterPlaceholder="IF Name" filterMatchMode="contains"></p-column>
    <p-column field="macAddress" [filter]="true" filterPlaceholder="MAC Address" filterMatchMode="contains"></p-column>
    <p-column field="stationIp" [filter]="true" filterPlaceholder="IP Address" filterMatchMode="contains"></p-column>

    <p-column field="groupName" hidden=true></p-column>
</p-dataTable>
```
Im getting the following error

> TypeError: Cannot read property 'style' of undefined
>     at DataTable.webpackJsonp.../../../../primeng/components/datatable/datatable.js.DataTable.fixColumnWidths (datatable.js:1384)
>     at DataTable.webpackJsonp.../../../../primeng/components/datatable/datatable.js.DataTable.initResizableColumns (datatable.js:1297)
>     at DataTable.webpackJsonp.../../../../primeng/components/datatable/datatable.js.DataTable.ngAfterViewChecked (datatable.js:464)
>     at callProviderLifecycles (

im using version: primeng@4.1.0-rc.2

**Comment by fedemarengo** [comment]
Try with [hidden]="true"
