### ISSUE TITLE
Calendar range/multiple default values cause error

### ISSUE THREAD

**Issue by MiguelAngelLV** [primefaces/primeng#3996]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

Example:
http://plnkr.co/edit/djr4zpNiJyVXJqOapkHp?p=preview

**Current behavior**
Fail when you set a default value with range / multiple dates because calendar expected a Date instead of a array

**Expected behavior**
Calendar must check if is a array or date in this line:
https://github.com/primefaces/primeng/blob/master/src/app/components/calendar/calendar.ts#L1123

**Minimal reproduction of the problem with instructions**
Set a range/multiple type date and set array Dates as default value.

**What is the motivation / use case for changing the behavior?**
Resolve the problem

**Please tell us about your environment:**
Linux,  Angular 4.4. and Prime 4.2.1

* **Browser:**  ALL

**Comment by nicobytes** [comment]
Yes! the error is in https://github.com/primefaces/primeng/blob/master/src/app/components/calendar/calendar.ts#L1123...

**Comment by ningacoding** [comment]
this error is still active PrimeNG version 5.2.5

**Comment by saachinsiva** [comment]
I am still getting this error @5.2.7
