### ISSUE TITLE
Editor: Auto-Resize or Layout fix

### ISSUE THREAD

**Issue by MarcelCremer** [primefaces/primeng#401]
Hello everyone,

when you type in more text into the editor than expected, the layout of the editor component will break.

Example: http://www.primefaces.org/primeng/#/editor
How: Keep Return pressed until the content is larger than the component.

I would suggest, it should stay in it's height and optionally resize in height.

Best Regards
Marcel

**Comment by cagataycivici** [comment]
We've updated the editor and it seems to working with it. I've seen the issue with the beta6 editor, beta7 editor fixes this.
