### ISSUE TITLE
Floating labels for calendar, dropdown, multiselect, etc.

### ISSUE THREAD

**Issue by ccasallas** [primefaces/primeng#4011]
I'm submitting a:
```
[ ] bug report
[ X ] feature request
[ ] support request
```
Currently floating labels is a feature only available for input texts. Please extend this feature to other components like calendar, dropdown, multiselect, textarea, autocomplete, etc.  It will improve user experience and will make components more consistent regarding its placesholders and labels behavior, at least in ultima theme that is based on google materials which all components have floating labels.

We are discussing about this on the following posts of primeng forum:

https://forum.primefaces.org/viewtopic.php?f=35&t=52546

https://forum.primefaces.org/viewtopic.php?f=45&t=49681&p=157407

regards,

Carlos

**Comment by jonathanbruno** [comment]
Yeah ..it would be great !!!

**Comment by cagataycivici** [comment]
Some already seem to support it, please create separate issue tickets for each one so we can track them one by one like https://github.com/primefaces/primeng/issues/3955

**Comment by VNYoeri** [comment]
@cagataycivici seriously? This issue had separate issue, for example: #4145 . But then those were closed stating "duplicate of #4011"... ? The least that could be done is reopen the "duplicate" issues (which, eventually, do not seem to be real duplicates... )

**Comment by VNYoeri** [comment]
@cagataycivici thanks for the update! 👍 (linked/referenced issues have been fixed, so that's even worth a 🥇 )
