### ISSUE TITLE
Autocomplete: enable multiple selection at once

### ISSUE THREAD

**Issue by lionelmbafumoya** [primefaces/primeng#4016]
**I'm submitting a ...**
```
[x] feature request
```

**Current behavior**
Given an autocomplete with the multiple attribute set to true, the values have to be selected one at the time with the panel closing each time.

**Expected behavior**
It would useful to be able to select multiple values at once similar to the MultiSelect behavior.

**Minimal reproduction of the problem with instructions**
1. Go to https://www.primefaces.org/primeng/#/autocomplete
2. Type the letters 'Bel' and try to add 'Belgium' and 'Belarus' at the same time in the Multiple autocomplete component.

**What is the motivation / use case for changing the behavior?**
The goal of an autocomplete that selects multiple values is to not only have real-time suggestions but also to be able to select as many values as needed (Similar to the MultiSelect component).
It is counter-intuitive to have to type similar queries when they share common letters.

**Please tell us about your environment:**

* **Angular version:** 4.0.2

* **PrimeNG version:** 4.2.1

* **Browser:** Chrome 60.0.3112.113

**Comment by cagataycivici** [comment]
We'll reconsider if more users demand it, thank you.

**Comment by bevrard** [comment]
We also need this feature.
Could you reconsider the demand?
Thanks in advance!

**Comment by s13571** [comment]
It would be really great in my current project. Please reconsider, it's awesome feature

**Comment by joster422** [comment]
+1

**Comment by mamoun90** [comment]
+1

**Comment by PCASME** [comment]
+1

**Comment by bossqone** [comment]
+1

**Comment by vatsalpande** [comment]
+1. Highly needed.

**Comment by changulpaye** [comment]
+1 Required in current project please consider it

**Comment by souravsaraf** [comment]
+1 Required. Please consider.

**Comment by bhanuunrivalled** [comment]
required 
consider it

**Comment by mcrtricolor** [comment]
Please consider adding this feature.

**Comment by SunnoSakib** [comment]
+1

**Comment by ibrdavid** [comment]
+1

**Comment by MSauer89** [comment]
+1
