### ISSUE TITLE
When using custom file uploads, selected file does not clear

### ISSUE THREAD

**Issue by brianjly** [primefaces/primeng#4018]
When using uploadHandler to implement custom upload, the selected file is not cleared.  For example, I select the first file to upload, the file is succesfully added to my array.  When I click the upload button again, I do not get the option to select a new file.  Instead, the previous file I selected is added to the array again.

**Comment by Sumragen** [comment]
@brianjly Hello,

Why did you think that incorrect behavior? If you want upload new files - push "cancel" button to clear array of files after uploading.
Or, as an example, you can trigger that programmatically, like this
```html
<p-fileUpload #form name="myfile[]" customUpload="true" (uploadHandler)="myUploader($event, form)"></p-fileUpload>
```
Where custom uploader looks like
```typescript
myUploader(event, form){
    for(let file of event.files) {
        this.uploadedFiles.push(file);
    }
    form.clear();
}
```

**Comment by brianjly** [comment]
@Sumragen thank you so much, just what I was looking for. closing the issue now

**Comment by sridhark158** [comment]
@Sumragen thank you :)

**Comment by himanshubudhlakoti** [comment]
Hi,
When i wrote 
myUploader(event, form){
**console.log(form , "my file form")**
    for(let file of event.files) {
        this.uploadedFiles.push(file);
    }
    form.clear();
}

**then it is printing "undefined" at console**
please suggest me i want to also clear selected file dynamically without clicking on cut button
when it has been uploaded

**Comment by Soharab-Shaikh** [comment]
@himanshubudhlakoti 
I think you just forgot to use **#form**

`<p-fileUpload **#form** name="myfile[]" customUpload="true" (uploadHandler)="myUploader($event, form)"></p-fileUpload>`

**Comment by alioshr** [comment]
Hello there ... 

Another thing I have noticed is that the "choose" button is disabled upon an error or wathever happens after trying to upload. How can I re-enable this button after trying/successfully uploading a file?

**Comment by gfeller** [comment]
@alioshr 
This works
`async myUploader(event, fileUpload: FileUpload) {
	fileUpload.clear();
	fileUpload.uploadedFileCount = 0; // <-- 

}`

**Comment by dnordahl1** [comment]
This seems like a bug that should be reopened.  The clear() function should include clearing the uploadedFileCount
