### ISSUE TITLE
Projecting Accordion into a container with *ngIf cause all accordion tabs to be shown as open

### ISSUE THREAD

**Issue by guy-eizon** [primefaces/primeng#4019]
When using p-accordion and projecting it into `ng-content` that is wrapped with a container that has `*ngIf` on it - the accordion tabs are shown as open. 
This happens when `ngIf` is set to false on init.
Here is a link to the bug's reproduction:

https://angular-kbnwvy.stackblitz.io/

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview
