### ISSUE TITLE
Grid with sorted column shuffling wildly on hover after changing underlying data

### ISSUE THREAD

**Issue by GraemeSMiller** [primefaces/primeng#402]
If you update the data underlying the grid and you have sorted a column the grids seems to shuffle wildly if you have your cursor inside the grid. Rows are swapping position rapidly. Happens in multiple grids I have created. I have templated columns, paging enabled, not lazy loading.  Nothing strange - no extra js or functionality. Data source is just an array. it only seems to happen if a column has been sorted.

Repro for me: Sort Column, change data (if am doing it with checkbox template within row), move mouse over grid and it looks like this (ignore bottom left part it is the tool for recording gif)
![demo](https://cloud.githubusercontent.com/assets/2472587/15505550/e779c88e-21bb-11e6-9c53-c2f2027c17c0.gif)

If I don't sort the data it works fine. If I re-sort the data on the same or different column the data stops shuffling until I then update it again. Once I update the shuffling starts again. Another weird thing once shuffling starts if I hover over the column headers (not clicking) the rows change order.

This started after the change was that was discussed to allow underlying data to refresh but keep the sort order. Using latest Beta 6.

**Comment by GraemeSMiller** [comment]
Just noticed - this is pretty much a dupe of Sorting by commonly re-used field yields shuffling behavior https://github.com/primefaces/primeng/issues/396

**Comment by cagataycivici** [comment]
Tracking at 396.
