### ISSUE TITLE
[DataTable] filterPlaceholder does not show up when using a custom ng-template filter

### ISSUE THREAD

**Issue by TheParad0X** [primefaces/primeng#4022]
Hello,

Not sure if it is a bug, but the placeHolder only works if no custom filter is defined. Thus, the following does not show the placeholder:

```
<p-column field="aField" [filter]="true" filterMatchMode="contains" filterPlaceholder="Filter">
      <ng-template pTemplate="filter" let-col>
        <input #myFilter type="text" pInputText style="width:100%" (input)="dt.filter($event.srcElement.value,col.field,col.filterMatchMode);"
          class="ui-column-filter" />
      </ng-template>
    </p-column>
```

How can I use the placeholder in my own filter ?

Cheers,
Para

**Comment by cagataycivici** [comment]
It is expected, that is for built-in filters. For custom ones you need to define it yourself.

```
<p-column field="aField" [filter]="true" filterMatchMode="contains" filterPlaceholder="Filter">
      <ng-template pTemplate="filter" let-col>
        <input #myFilter type="text" pInputText style="width:100%" (input)="dt.filter($event.srcElement.value,col.field,col.filterMatchMode);"
          class="ui-column-filter" placeholder="Filter"/>
      </ng-template>
    </p-column>
```

**Comment by shehza-scs** [comment]
Hi,
I am filtering the same way, but once my filter results are returned my search field is cleared automatically. I am not sure what is it, which is clearing the filter text field. if you can help. It would be great.
My code is:
  <p-column   *ngFor="let col of cols;let i=index" [field]="col.field"   [header]="(col.header  | capitalize) "  [filter]="true" filterPlaceholder="Search"   [sortable] = "false"
            [style]=" {'white-space':'nowrap', 'overflow':'hidden','text-overflow':'ellipsis','font-size': '19px' ,    'font-family': 'initial'} ">
    <ng-template pTemplate="filter" let-col >
      <input #fil pInputText   class="ui-column-filter"     type="text"   style="size:25px" placeholder="Search"   (input)="dt.filter($event.srcElement.value,col.field,'');"  />
      <i #close  class="fa fa-close close-icon-margin" (click)="dt.filter($event.target.value=null,col.field,'')" ></i>
    </ng-template>
  </p-column>
Thanks
