### ISSUE TITLE
overlayPanel moves on scroll

### ISSUE THREAD

**Issue by tommyc38** [primefaces/primeng#4024]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

Below is my plunkr:

http://plnkr.co/edit/m0tpiaqJozzhEqUbeDKm?p=preview

**Current behavior**

If the overlayPanel is nested in a fixed element it moves when scrolled.  Please see the simple plunkr demonstrating this.  

**Expected behavior**

I would expect that the overlayPanel would stay attached to the element when scrolled.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
there is appendTo property for this

**Comment by tommyc38** [comment]
@cagataycivici can you please post a Plunker because I already tried this and other options with no luck.

**Comment by tommyc38** [comment]
@cagataycivici can you please use my plunkr to show how this is fixed?  I don't understand why others aren't having this same issue.

**Comment by rajjaiswalsaumya** [comment]
This is the issue. Can someone provide a fix?
