### ISSUE TITLE
Calendar initial value not visible in input text to edit

### ISSUE THREAD

**Issue by abdhafid** [primefaces/primeng#4026]
I can't edit calendar value when it's from server
I have :
`<form (ngSubmit)="save()" #cForm="ngForm">
     <p-calendar [(ngModel)]="selected.dateCommande"
                        [showIcon]="true"
                        #dateCommande="ngModel"
                    name="dateCommande"></p-calendar>`

When I create model, I select one date, it's show in input calendar, I save (in database).
But when I access of this page for edit, the inputtext of calendar is blank.

I have this message error : ERROR Error: Uncaught (in promise): Unexpected literal at position 2

I use :
* **Angular version:** 4.3.2
* **PrimeNG version:** 4.2.1

Any suggestion 
Thanks

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview

**Comment by asadsahi** [comment]
@cagataycivici having same issue, this is to do with initializing value:

I think datetime picker doesn't except string datetime, if we new Date(strindate), it sets the initial value.

Also initial value with null and fortmat set as 'dd.mm.yyyy' displays like this:

![image](https://user-images.githubusercontent.com/3470892/32704213-84654b8e-c7f9-11e7-9595-1abd38c83a1c.png)
here is calendar config:

`        <p-calendar id="date" dateFormat="dd.mm.yy" formControlName="date" [showIcon]="true"></p-calendar>
`

**Comment by kjozic** [comment]
I can confirm this. The following code works well:

```
interface UserData {
  id: number;
  first_name: string;
  last_name: string;
  gender: string;
  date_of_birth: Date;
  address: string;
  email: string;
  phone: string;
}

...

  private initForm(ud: UserData): void {
    this.userDataForm = this.formBuilder.group({
      "id": ud.id,
      "first_name": [ud.first_name, Validators.required],
      "last_name": [ud.last_name, Validators.required],
      "gender": [ud.gender, Validators.required],
      "date_of_birth": [new Date(ud.date_of_birth), Validators.required],
      "address": [ud.address, Validators.required],
      "email": ud.email,
      "phone": ud.phone
    });
  }

...

<p-calendar id="dateOfBirth" dateFormat="dd.mm.yy." formControlName="date_of_birth"></p-calendar>
```

But in this case ```"date_of_birth": [ud.date_of_birth, Validators.required],``` empty picker is displayed and the following error is thrown:
```
ERROR Error: Unexpected literal at position 2
    at viewWrappedDebugError (core.js:9764)
    at callWithDebugContext (core.js:15066)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (core.js:14593)
    at ViewRef_.detectChanges (core.js:11577)
    at eval (core.js:5907)
    at Array.forEach (<anonymous>)
    at ApplicationRef.tick (core.js:5907)
    at eval (core.js:5740)
    at ZoneDelegate.invoke (zone.js:388)
    at Object.onInvoke (core.js:4749)
```

**Comment by lucastoneatto** [comment]
I have the same message error : ERROR Error: Uncaught (in promise): Unexpected literal ...

I use :
Angular version: 5.1.2

I think it's the format of the date. from the server I have '2018-03-09 10:00:00', but I do not know how to modify it to be accepted by the component.

**Comment by 839998664** [comment]
I am facing the same issue, have been reading since past week to find a solution...

**Comment by bluesektor** [comment]
Had the same problem. Only thing that worked was this..
let tmpDate: string = moment(this.form.get('purchaseDate').value).format('YYYY.MM.DD');
expirationDate = new Date(tmpDate);

Calendar control
 <p-calendar  [(ngModel)]="expirationDate"    [showIcon]="true"></p-calendar>

credit to this post;
https://stackoverflow.com/questions/46051318/error-missing-number-at-position-0-when-using-setvalue-angular-4
