### ISSUE TITLE
Calendar not correct ng-template render

### ISSUE THREAD

**Issue by ar53n** [primefaces/primeng#4027]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview

**Current behavior**

Because this code we have inccorect rendering calendar in Ultima layout too
[https://github.com/primefaces/primeng/blob/2b822a4037051fe3b3b519a9b885a3869a4aaae6/src/app/components/calendar/calendar.ts#L75](https://github.com/primefaces/primeng/blob/2b822a4037051fe3b3b519a9b885a3869a4aaae6/src/app/components/calendar/calendar.ts#L75)
Maybe need without `!`

![Calendar](https://user-images.githubusercontent.com/7085102/30852229-c01ea316-a2b3-11e7-9a38-84f8e955eb57.png)

**Expected behavior**
I have correct rendering

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.3.6

* **PrimeNG version:** 4.2.1

* **Browser:** [all]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Fixed in 4.2.2.
