### ISSUE TITLE
Row Grouping on DataTable

### ISSUE THREAD

**Issue by lilling** [primefaces/primeng#403]
I would like to group rows like in this url:

https://datatables.net/examples/advanced_init/row_grouping.html

**Comment by cagataycivici** [comment]
With a separate group row or with Rowspan. Same idea of upcoming 
<img width="1082" alt="rg1" src="https://cloud.githubusercontent.com/assets/686247/21002254/6a6eb9cc-bd2d-11e6-9cab-7f885894acf8.png">
![rg2](https://cloud.githubusercontent.com/assets/686247/21002255/6a6ff4cc-bd2d-11e6-9bdc-b2cf154fb473.png)
![rg3](https://cloud.githubusercontent.com/assets/686247/21002256/6a70fed0-bd2d-11e6-9825-125ed0f843b8.png)


PrimeFaces row grouping.

**Comment by cagataycivici** [comment]
Also added support for toggleable row groups as well as summary rows.

<img width="1088" alt="screen shot 2016-12-12 at 23 13 51" src="https://cloud.githubusercontent.com/assets/686247/21115175/b8cd8e84-c0b8-11e6-834e-09b53e204158.png">

**Comment by uroti** [comment]
It is possible a multi row grouping  with different fields?

**Comment by arunprasadkumaran** [comment]
@uroti,  Looks like the feature is not supported by primeng yet. Have you found any alternate solution for multi row grouping with different fields?

**Comment by bhaidar** [comment]
I found this to be the closest to what I need:

https://embed.plnkr.co/plunk/WBzEyH

**Comment by leventkalay** [comment]
Because Primeng datatable is removed, Row groups with summary rows does not exist in primeng table. How can i row grouping with summary row(total) in primeng table.

**Comment by pheakdeykm** [comment]
Row groups with summary rows does not exist in primeng table. How can i create a table using row grouping with summary row(total) in primeng table.
