### ISSUE TITLE
Uncaught (in promise): Extra/unparsed characters found in date

### ISSUE THREAD

**Issue by bhaidar** [primefaces/primeng#4030]
Hi,

I am getting this exception locally on my PC when I try to add a new Event on the schedule when inside Week view.

The same exception is being generated on the primeng website.

Any idea whats going on?

Bilal

````
vendor.d1fad0b57b856be3f615.bundle.js:1 ERROR Error: Uncaught (in promise): Extra/unparsed characters found in date: T04:30:00
    at u (polyfills.87872b4620f338d00d4f.bundle.js:1)
    at polyfills.87872b4620f338d00d4f.bundle.js:1
    at t.invokeTask (polyfills.87872b4620f338d00d4f.bundle.js:1)
    at Object.onInvokeTask (vendor.d1fad0b57b856be3f615.bundle.js:1)
    at t.invokeTask (polyfills.87872b4620f338d00d4f.bundle.js:1)
    at r.runTask (polyfills.87872b4620f338d00d4f.bundle.js:1)
    at i (polyfills.87872b4620f338d00d4f.bundle.js:1)
    at e.invokeTask [as invoke] (polyfills.87872b4620f338d00d4f.bundle.js:1)
    at p (polyfills.87872b4620f338d00d4f.bundle.js:1)
````

**Comment by bhaidar** [comment]
Any feedback, please? The online sample on the Primeng website is having this exception.  Check it out.

Thanks

**Comment by bhaidar** [comment]
None is facing this issue but me? Any feedback please.

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview

**Comment by sudheerj** [comment]
Hi Cagatay,

          I can able to replicate the issue in showcase. 

Go to-->Schedule example-->select week view--> Click on non all-day(any time)

Then we can find this error.

@cagataycivici

**Comment by cagataycivici** [comment]
Assigned to @Merve7 for review

**Comment by cagataycivici** [comment]
It was an issue with demo and fixed it.

**Comment by bhaidar** [comment]
It is am issue with the control also locally. I'm facing it still.

Shall I upgrade?
