### ISSUE TITLE
Dynamic columns with checkbox selection column

### ISSUE THREAD

**Issue by winarg** [primefaces/primeng#4032]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview

**Current behavior**
If there is a checkbox selection column along with a for loop with columns to show, the columns are not shown and the checkbox column uses all the table width

**Expected behavior**
Show the checkbox column as a normal column along with the rest columns

**Minimal reproduction of the problem with instructions**
<p-header>Checkbox Selection</p-header>
<p-column *ngFor="let col of columns">

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.3.6

* **PrimeNG version:** 4.2.1

* **Browser:** [all]

 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =

**Comment by winarg** [comment]
Any progress with this bug?

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview
