### ISSUE TITLE
Setting width of AutoComplete does not set the width of the input

### ISSUE THREAD

**Issue by mdonato7** [primefaces/primeng#4037]
**I'm submitting a ...**  
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://plnkr.co/edit/eRzojjCMdAS3IOoGWOa7?p=preview

**Current behavior**
When using `[style]="{ 'width' : '95%' }"` the suggestions list correctly expands to 95% width, but the text input does not.

**Expected behavior**
I would expect both the input and suggestions to expand to 95% width

**Minimal reproduction of the problem with instructions**
See plunkr for details. The important bit is here:

```
<div style="width: 100%">
  <p-autoComplete 
    [suggestions]="suggestions" 
    (completeMethod)="search($event)" 
    [style]="{'width':'95%'}"> <!-- I would expect this to set the input width as well, it currently does not -->
  </p-autoComplete>
</div>
```

**What is the motivation / use case for changing the behavior?**
As far as I can tell there is currently no way to expand the input of a p-autoComplete without css hacks rather than binding to style. Binding to style would be more consistent with other primeng controls.

**Please tell us about your environment:**

* **Angular version:** 4.3.6

* **PrimeNG version:** 4.1.2

* **Browser:** Chrome 61

**Comment by armst0910** [comment]
try this 

`<div style="width: 100%">
  <p-autoComplete 
    [suggestions]="suggestions" 
    (completeMethod)="search($event)" 
    [style]="{'width':'95%'}" [inputStyle]="{'width': '100%'}"> 
  </p-autoComplete>
</div>`

**Comment by Anandhsa09** [comment]
it's not working.

**Comment by Jo-Chris** [comment]
```
<p-autoComplete
  class="ui-fluid"
  [...]
</p-autoComplete>
```

```
::ng-deep {
  .ui-autocomplete-input-token {
    width: 100%;
  }
```
  
  add this, did the trick for me

**Comment by zaynOm** [comment]
I'm having the same issue. I'm using tailwind, and i can't get it to work
