### ISSUE TITLE
Custom content for tabview headers

### ISSUE THREAD

**Issue by kito99** [primefaces/primeng#4038]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Tab menu label is only a string. 

**Expected behavior**
Add a facet so that developers can add their own content into the tab.

**What is the motivation / use case for changing the behavior?**
Needed alternate styling for selected tabs that is difficult with plain CSS.

**Please tell us about your environment:**
Mac OS X, Angular CLI

* **Angular version:** 2.0.X
4.2

* **PrimeNG version:** 2.0.X
4.2

**Comment by StAn187** [comment]
Will this ever be implemented? Currently adding additional components to the tab navigation using directives but this feels a little hacky ...

**Comment by dkvwu** [comment]
Is there any update?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
