### ISSUE TITLE
Menubar dropdown does not work on Android (No submenu is visible)

### ISSUE THREAD

**Issue by Venthe** [primefaces/primeng#4041]
Problem only happens on Android. Tested additionally on Chrome desktop, iOS, IE and Firefox

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
```

**Example**
https://www.primefaces.org/primeng/#/menubar

**Current behavior**
On clicking menu with dropdown nothing happens

**Expected behavior**
Dropdown works

**Minimal reproduction of the problem with instructions**
Just try to use dropdown. Z-index does not work.

**Please tell us about your environment:**
Node/Yarn

* **Angular version:** 4.4.2

* **PrimeNG version:** 2.2.1

* **Browser:** [Mobile Chrome 61.0.3163.98]
 
* **OS:** [4.2.2]

* **Language:** [TypeScript 2.5.x | TypeScript 2.4.x]

* **Node (for AoT issues):** `node --version` =

**Comment by yigitfindikli** [comment]
Unable to replicate with latest PrimeNG, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
