### ISSUE TITLE
P-datatable style issue after closing p-confirmdialg

### ISSUE THREAD

**Issue by rezord** [primefaces/primeng#4042]
I have p-datatable with class=ui-datatable. In some situation, I open a message box and after confirmation, some data will be added to the data table. But after closing message box a horizontal scroll box appeared.
If I don't show the message box, everything is fine!

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview
