### ISSUE TITLE
508 compatibility for DataTable checkbox

### ISSUE THREAD

**Issue by MSAJJAN-EEOC** [primefaces/primeng#4044]
**I'm submitting a ...** 
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Multi select checkboxes (p-dtCheckbox) in Multi Select Datatable(p-dataTable)  not Accessible by keyboard. And when we access it by JAWS and check the checkbox using space key it says ‘checkbox checked’ but nothing happens. when we hit space key again it says checkbox unchecked but nothing happens.

**Expected behavior**
And when we access it by JAWS and check the checkbox using space key it should say ‘checkbox checked’ and checkbox should be checked . when we hit space key again it should say checkbox unchecked and un-check the checkbox.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
when blind people read the page by using JAWS and access it, they should be able to toggle the checkbox.

**Please tell us about your environment:**

* **Angular version:**  4.1.0

* **PrimeNG version:**  4.1.3

* **Browser:** 
 | Chrome Latest | Firefox Latest | IE 11

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
