### ISSUE TITLE
508 compatibility for pButton

### ISSUE THREAD

**Issue by MSAJJAN-EEOC** [primefaces/primeng#4045]
**I'm submitting a ...**  
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
Icons in buttons (pButton) are being read by JAWS. 

**Expected behavior**
Icons in buttons (pButton)shouldn’t be read by JAWS. 
In case of icon only buttons we can use titles for reading

**What is the motivation / use case for changing the behavior?**
Blind people cannot understand when the icons are read by JAWS

* **Angular version:**  4.1.0

* **PrimeNG version:** 4.1.3

* **Browser:** 
 Chrome Latest | Firefox Latest | IE 11

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
