### ISSUE TITLE
Ability to always show first and/or last n amount of pages

### ISSUE THREAD

**Issue by bakasmarius** [primefaces/primeng#4050]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
The current paginator is nice, but it would be also nice to have additional options that would be very helpful if you have lots of pages, i.e. 100 or even 1000, mainly because user does not know how many pages there are in total, unless he clicks the last page button.

Something like this:
![alt text](https://www.technovelty.org/static/images/paginator-skip.png "Random paginator from google")

So it could have two additional properties with default values set to zero: 
* firstPagesLinkSize - if set to n, it would ALWAYS show the first n pages (if total pages >= n)
* lastPagesLinkSize - if set to n, it would ALWAYS show the last n pages (if total pages >= n)

For example, if you set these properties:
firstPagesLinkSize = 2, pageLinkSize = 1, lastPagesLinkSize = 5
And you have 20 pages and currently you are in page number 7, you would see:
[1] [2] [...] [<<] [7] [>>] [...] [16] [17] [18] [19] [20]

Each of the setting, if set, would also remove the first [|<] and/or the last [>|] buttons, accordingly.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
