### ISSUE TITLE
FileUpload support for Cordova

### ISSUE THREAD

**Issue by amirsasani** [primefaces/primeng#4051]
I have problems with `cordova webview` and `p-fileupload`!
I am making an app with angular and now I want to make a mobile app from the angular app, but the problem is when I want to choose a file from mobile app, nothing happened but in browser it works correctly.
```
angular version: 2.3.1
tested devices: samsung galaxy s7 edge, android 7.0 AND samsung S5, android 4.4.2
```

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
