### ISSUE TITLE
How to update slider programatically?

### ISSUE THREAD

**Issue by untitledlt** [primefaces/primeng#4055]
```
[x] feature request
```

**Current behavior**
After changing value in controller, slider position does not update.

**Expected behavior**
Update slider position after changing value in controller or add a method to change value.

**Comment by cagataycivici** [comment]
This works;

```
<button (click)="val1 = 10"></button>
<p-slider [(ngModel)]="val1" [style]="{'width':'200px'}"></p-slider>
```

When the button is clicked, slider value is set to 10.
