### ISSUE TITLE
onReorder event does not fire on dragging and dropping list items

### ISSUE THREAD

**Issue by GregKass** [primefaces/primeng#4059]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview

**Current behavior**

`onReorder` does not fire `onDragEnd`, only on mouse events

**Expected behavior**

`onReorder` should emit after dragging and dropping an item to a new location

**Minimal reproduction of the problem with instructions**

[Plunker Demo](http://plnkr.co/edit/p6twagoRixXZs2WGC6Jl?p=preview)

Select an item and move via arrows, then move by drag-drop and check console log

**What is the motivation / use case for changing the behavior?**

To be able to respond to all forms of changes to the order of the list

**Please tell us about your environment:**

* **Angular version:** 4.3.2

* **PrimeNG version:** 4.2.0

* **Browser:** [**all** | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [**all** | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Fixed in 4.2.2
