### ISSUE TITLE
Calendar onBlur function not working

### ISSUE THREAD

**Issue by ernitingoel** [primefaces/primeng#406]
I was trying the calendar onBlur function, it's not working though onSelect is working fine.

**Comment by Mrtcndkn** [comment]
Locally it's working fine .

<p-calendar [(ngModel)]="date1" (onBlur)="test()"></p-calendar>

i have my component with onBlur callback and in my ts i have a test function and its working.

**Comment by ernitingoel** [comment]
I may need to try it on the latest version then

**Comment by amar33333** [comment]
I guess OnBlur event is retaining  the  previous  value  of calendar , why ?
IN-Template.
`<p-calendar [(ngModel)]="paymentdata.date" [dateFormat]="date_hadler.convertBoDateFormat2NgPrime(boDateFormat)" tabindex="0"
      [minDate]="minDateValue" id="datepickerImage" placeholder='{{boDateFormat | uppercase}}' [showIcon]="true"
      (onBlur)='ValidateDate($event)'>
    </p-calendar>`
IN TS
`ValidateDate(event) {
        console.log(this.paymentdata.date);}`
in console  i am  getting  the  old value not the current  value , why ?
