### ISSUE TITLE
DataTable sorted & filtered columns with Multi-Select screws up CSS

### ISSUE THREAD

**Issue by MHacker9404** [primefaces/primeng#4060]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview

**Current behavior**
If you have a DataTable column that is sortable, and filtered with a MultiSelect - when you sort the column - the multi-select template gets 'hidden'

**Expected behavior**

Should act more like a regular filter field

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   

![image](https://user-images.githubusercontent.com/4184348/30991427-a1d6982e-a46a-11e7-9105-c83a68fa9fdf.png)
![image](https://user-images.githubusercontent.com/4184348/30991437-af4df8c6-a46a-11e7-8052-188c51d17bd8.png)

**Comment by MHacker9404** [comment]
I've update my fork at [https://github.com/MHacker9404/primeng](url) to support the bootstrap theme in the themeswitcher, and and adding sorting to the datatable/filter demo component that shows the issue.

**Comment by cagataycivici** [comment]
Does it only happen in bootstrap theme?

**Comment by MHacker9404** [comment]
As far as I could tell  yes – that was the only theme that showed the issue

**Comment by cagataycivici** [comment]
Sorry, bootstrap theme is not maintained anymore in favor of Avalon theme.
