### ISSUE TITLE
DataTable RowGrouping with Lazy Loading

### ISSUE THREAD

**Issue by MateuszKaczmarczyk** [primefaces/primeng#4063]
**I'm submitting a ...**
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When using lazy loading, we currently can filter and sort data on server side, but we cannot group it. Row grouping works only on client side, on loaded data set, and because of that we can't use lazy loading and row grouping together.

**Expected behavior**
It would be great if we could send to server info about column, that will be used to group data, and server will return grouped, filtered and sorted data. 

**What is the motivation / use case for changing the behavior?**
As I mentioned above, for now I can't use RowGrouping with Lazy Loading, and i need to display large data set (above 1 million records). It can't be done without server-side pagination. I also need dynamic RowGrouping - user selects column, and data dynamically regroups.

* **Angular version:** 4.4.4

* **PrimeNG version:** 4.2.1

**Comment by wooleverj** [comment]
I also have this same need.  I was able to make a very hacked solution by directly editing the dom to make the normal rows look like groups.  It would be much cleaner to have the datatable be able to handle this directly.

**Comment by cagataycivici** [comment]
Grouping is for rendering purposes, if you sort it according to the group field, it should work. Grouping = Sorting actually.
