### ISSUE TITLE
datatable sorting data on mousemove and keypress

### ISSUE THREAD

**Issue by mikedunham** [primefaces/primeng#4065]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Object array bound to datatable with sort set on a date value desc, mouseover, keypress and mouse click will cause some rows to shift positions in the underlying array. This is the same behavior in #396 and #402

**Expected behavior**
Data array should not change

* **PrimeNG version:** 4.1.3 - 4.2.1

* **Browser:** Could only reproduce in Chrome, currently using version 61

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview
