### ISSUE TITLE
Dropdown filter has incorrect width under fluid mode

### ISSUE THREAD

**Issue by bossqone** [primefaces/primeng#4067]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/UcMvApArFWvDAgaxxmF5?p=preview

**Current behavior**
With `[autoWidth]=false` and fluid layout, filter doesn't take full width of it's container.
![screenshot of issue in Poseidon theme](https://i.imgur.com/diRiRuk.png)

**Expected behavior**
Filter should take full width of it's container.

* **PrimeNG version:** 4.2.1

**Comment by bossqone** [comment]
@Merve7 Hi, I saw your fix and I have a question. How it behaves when `style` param is not defined? Do I need to specify `style.width` everytime I want to use dropdown component?

Could you please provide an example of usage? Thank you.

**Comment by cagataycivici** [comment]
style.width is a problem, it will throw an exception, I have to revert it.

**Comment by cagataycivici** [comment]
Removed style.width binding and merged the PR to fix this, thank you.
