### ISSUE TITLE
Advanced growl messages

### ISSUE THREAD

**Issue by kreuzerk** [primefaces/primeng#4070]
Hi there. I have written a wrapper around your growl module called primeng-advanced-growl. This wrapper brings some more functionality to the primeng growl module. It improves the non sticky features for messages. Each message will dissappear after its specified time elapses and not with all the other messages. Furthermore the wrapper adds pausable hover features for messages that disappear after a given lifetime. To see how things look like in action please click on the demo link below.

**Module**: https://www.npmjs.com/package/primeng-advanced-growl
**Demo**: https://primeng-advanced-growl.firebaseapp.com/

The base functionality is written in RxJS. The only dependency that is additionaly needed is angular2-uuid. The other dependencies that the module uses are already needed by angular.

**I would like to ask you if you would be interested to adopt those functionalities directly into primeng**

**What is the motivation / use case for changing the behavior?**
The consumer of primeng growl gets more functionality. It is great that each message has a given lifetime. With such functionality you could easily display all messages that arrive over time and let them dissappear in the order they arrived. If the consumer then wants to have more informations about a message he can pause a message or all messages by just hovering over them.

**Comment by cagataycivici** [comment]
Growl is deprecated, please use Toast instead.
