### ISSUE TITLE
Adobe Experience Design CC Sticker Sheet

### ISSUE THREAD

**Issue by davisb10** [primefaces/primeng#4073]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

I am currently a developer and UI/UX designer. I love the component library but would love to be able to use the components in my design and prototyping in Adobe Experience Design CC. 

Let me know if this a possibility.

Thanks so much.

**Comment by cagataycivici** [comment]
I'm afraid we don't have a file for adobe experience design, we use mostly sketch for designing.

**Comment by davisb10** [comment]
@cagataycivici I know this was closed a while ago, but would I be able to see a copy of the Sketch designs so I could make an 'Unofficial' PrimeNG Adobe XD sticker sheet?

Let me know. Thanks.
