### ISSUE TITLE
Calling functions during runtime in TreeTable & Expandable DataTable

### ISSUE THREAD

**Issue by nsksaisaravana** [primefaces/primeng#4075]
I really love primeng components and I was using Angular UI Grid for Angular 1.x and for Angular 2+ I am using TreeTable and Expandable Datatable.

I am not able to define columns for the expandable child rows and calling functions during runtime. Please check UI Grid and we can apply functionalities in the Tree Component and Expandable Datatable components.

**The customer has got a lot of different types of documents and based on document type e.g PDF, DOCX, XLSX I have to show the image of the document.**

**Comment by cagataycivici** [comment]
Request not clear, please provide details and examples.

**Comment by nsksaisaravana** [comment]
In the expandable or Tree grid, i would like to show the Invoice Header and Invoice Details. Parent is the Invoice header and Child is the Invoice detail. Invoice header columns will be different and Invoice details columns will be different, how can I declare those columns in the expandable grid or Tree grid. During runtime, I would like to bind the image to the invoice details rorws or bind click events to the rows.

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
