### ISSUE TITLE
Progress Spinner -New Component.

### ISSUE THREAD

**Issue by nsksaisaravana** [primefaces/primeng#4077]
I really enjoying all components in PrimeNG but I am missing Progress Spinner, I really love Netflix progress Spinner, Please add similar one in PrimeNG

**Comment by cagataycivici** [comment]
Do you have an example?

**Comment by nsksaisaravana** [comment]
Similar like Angular Material Progress spinner but i love Netflix progress spinner.

https://material.angular.io/components/progress-spinner/overview

**Comment by cagataycivici** [comment]
Available for 4.2.3.

**Comment by nsksaisaravana** [comment]
Thanks a lot of and I hope I am little dependent on Angular Material. PrimeNG going to fulfill almost all my required angular components !!!

**Comment by ambujkhanna** [comment]
I am using "ProgressSpinnerModule" and it fires an error

[ts] Module '"d:/Projects/Staff_Assignment/StaffAssignment/node_modules/primeng/primeng"' has no exported member 'ProgressSpinnerModule'.
