### ISSUE TITLE
Pagination for PickList

### ISSUE THREAD

**Issue by jisqaqov** [primefaces/primeng#4079]
Hello. PickList could not display if there are too many records. For instance i have at most 300 records. In my case PickList rows become too small and i can not even see anything.
Could you please add pagination. I assume PickList is only for small number of records;

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
