### ISSUE TITLE
Cannot use HTML in datatable column headers

### ISSUE THREAD

**Issue by fis-dan-wnuk** [primefaces/primeng#408]
I am trying to implement a checkbox column in my data table for multi select. It doesn't appear as though I can set the header for this column to a 'master checkbox' element as the column is set to string type and only accepts a string. If I do [header]="getCheckboxHeader()" it will display the HTML as plain text.

Can this be made more flexible? Maybe let multiple templates be passed in, one for the header and one for the row content?

**Comment by fernandocode** [comment]
Possibly this other issue: #98, already covers this issue, it was not currently implemented by a bug in the angular that has not been fixed yet.

**Comment by fis-dan-wnuk** [comment]
Ah, you are correct. I'll close my issue.
