### ISSUE TITLE
iOS dropdown not closing

### ISSUE THREAD

**Issue by mfrro** [primefaces/primeng#4082]
**I'm submitting a ...** 
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/U3YKdD5BRFziueNyHqcS?p=preview
Tapping next to dropdown should close it. Doesn't work on iOS.

**Current behavior**
When a dropdown is open and I tap somewhere else on the page, the dropdown remains open.

**Expected behavior**
When I tap anywhere on the page besides the dropdown, the dropdown should close. If I tap on another element, say a texfield, the dropdown is closed as expected. The issue appears only when I tap on an empty space on the page.

**What is the motivation / use case for changing the behavior?**
This is common behaviour for closing dropdowns. Thanks for having a look.

* **Angular version:** 4.1.3

* **PrimeNG version:** 4.1.1

* **Browser:** [iOS‎ 9.3.5 Safari]
 
* **Language:** [all]

**Comment by vangnd** [comment]
Anybody working on this issue?

**Comment by dmitryy90** [comment]
guys, do you have any updates on this issue?

**Comment by gnguyen83** [comment]
Our custom is complaining about this behaviour in our web app, because we use primeNg. I'll be happy if you guys finally have a fix for this problem.

**Comment by cyber-greg** [comment]
Same problem with Ionic when using app in iOS or Android hybrid compiled mode.
No problem with desktop browser.
Maybe it's a touch event instead of click event problem for the blur?

**Comment by rcarduner** [comment]
Having the same issue with p-calendar as well as p-dropdown with PNG 12 on iOS 12.  Probably other controls are affected as well.

In line with the previous comment, I haven't tested Overlay Panel, but looking at **bindDocumentClickListener()** I would guess that it is working correctly; and probably a similar solution should be used for other controls with any kind of overlay: 
**overlaypanel.ts**
![image](https://user-images.githubusercontent.com/15037926/147594879-bc2e9452-cde0-4ce3-8d6f-afd6987eb105.png)

**dropdown.ts**
![image](https://user-images.githubusercontent.com/15037926/147594783-a4e44483-8013-4810-b819-78f600fd7308.png)

**Comment by cetincakiroglu** [comment]
Hi,

If the issue still exists with the latest PrimeNG version, please provide a StackBlitz example by using [PrimeNG Issue Template ](https://stackblitz.com/github/primefaces/primeng-issue-template) and re-open the issue.

Regards
