### ISSUE TITLE
Allowing more p-confirmDialog on the same page

### ISSUE THREAD

**Issue by pierfreeman** [primefaces/primeng#4087]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

I know that someone already asked for it, but there is no issue opened.
It would be nice to have the chance to set more than one confirmDialog on the same page. In my application I need different confirmDialogs, with a slightly different template (edit/delete confirmation, auto-logout alert). 
I'd like to use the advantages of ConfirmationService, instead of using several p-dialogs and putting a lot of HTML for each case.

**Comment by cagataycivici** [comment]
But you can customize all parts of ConfirmDialog using confirmation service like icons, messages, buttons and so on.

**Comment by pierfreeman** [comment]
Yeah sorry, in my p-confirmDialog I was setting the template directly in the HTML, so I wasn't  able to override it dynamically.
Now I set only one dialog, with nothing set in the HTML, and confirmation service always render a different dialog for each feature, each one with their one footer buttons, etc...

Thanks, issue can be closed.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
