### ISSUE TITLE
@ngIf in a dialog only works on initial display

### ISSUE THREAD

**Issue by hpdrago** [primefaces/primeng#4090]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview

**Current behavior**
I have a p-dialog.  I conditionally display text with *ngIf=<condition> which works on the initial display of the form.  After the dialog has been displayed and the <condition> changes, the div convent does not change.  Here's the html:

        <div *ngIf="!displayProgressBar">
            <h1>Progress YYY</h1>
        </div>

        <div *ngIf="displayProgressBar">
            <h1>Progress XXX</h1>
        </div>

"Progress YYY" displays when the dialog initially displays as the displayProgressBaris false, but when the displayProgressBaris set to true, no changes are reflected.  It still displays "Progress YYY" not "ProgressXXX"

**Expected behavior**
The div content should change based on the value of the displayProgressBar flag after the dialog has been displayed.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

What I am trying to do is display a "progress bar" after the user has clicked on the save button on the dialog.  After the save is complete (Observable), the progress bar (Angular Material progress BAR) is hidden and the form is closed.  I had tried the primeng progress bar to overlay the whole dialog while the save is in progress, but that didn't work either.  I believe I am missing something when it comes to animations and dialog boxes.  Thanks for any help.

**Please tell us about your environment:**

* **Angular version:** 2.0.X
4.4.3

* **PrimeNG version:** 2.0.X
4.2.0-rc.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=info
