### ISSUE TITLE
Keyboard navigation support for Tree

### ISSUE THREAD

**Issue by gtzinos** [primefaces/primeng#4091]
Hello guys,

First of all thanks for your great job. We use more of your components for our apps. I would like to request an important feature for treeview component. More people use apps every day for their job and they don't like to use mouse instead they use their keyboard (up, down, enter to select). Is it possible to make treeview component focusable ? It doesn't use any tabindex to focus it with keyboard.

Thanks.

**Comment by cagataycivici** [comment]
Thanks it was already planned as we've done it for PrimeFaces Tree before, will do the same for p-tree as well.

**Comment by gtzinos** [comment]
Great !!!

**Comment by karol-depka** [comment]
Hi. Would you maybe accept help in implementing this?

**Comment by jmesa-sistel** [comment]
@cagataycivici any news about this issue?
I think the change is big enough to NOT be accepted by a pull request, but can we help doing a pull request with this improvement?

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/issues/1861
