### ISSUE TITLE
Keyboard navigation support for Picklist

### ISSUE THREAD

**Issue by gtzinos** [primefaces/primeng#4092]
Hello again guys,

I would like to request one more important feature for picklist component. As i said at https://github.com/primefaces/primeng/issues/4091 "More people use apps every day for their job and they don't like to use mouse instead they use their keyboard (up, down, enter to select)". Is it possible to make picklist component focusable ? It doesn't use any tabindex to focus it with keyboard.

Thanks.

**Comment by MikeDub** [comment]
I definitely second this idea. Usability from both the mouse and the keyboard perspective is essential.
I personally find in web forms using the keyboard only is much quicker provided is has been setup correctly.

**Comment by lucini** [comment]
Is this solved, isn't?

**Comment by foxx9** [comment]
Hi, looking at the code https://github.com/primefaces/primeng/blob/13.0.02/src/app/components/picklist/picklist.ts, 
it seems that some keyboard interaction is implemented like up and down to focus and enter key to make the focused  element active, but it does not handle moving elements from left to right.

```typescript
onItemKeydown(event: KeyboardEvent, item: any, selectedItems: any[], callback: EventEmitter<any>) {
        let listItem = <HTMLLIElement> event.currentTarget;

        switch(event.which) {
            //down
            case 40:
                var nextItem = this.findNextItem(listItem);
                if (nextItem) {
                    nextItem.focus();
                }

                event.preventDefault();
            break;

            //up
            case 38:
                var prevItem = this.findPrevItem(listItem);
                if (prevItem) {
                    prevItem.focus();
                }

                event.preventDefault();
            break;

            //enter
            case 13:
                this.onItemClick(event, item, selectedItems, callback);
                event.preventDefault();
            break;
        }
    }

```

I also think it is a missing feature to use left/right arrow keys or enter key in order to use the pick-list component

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
