### ISSUE TITLE
Undetermined progress bar

### ISSUE THREAD

**Issue by ntkolev** [primefaces/primeng#4093]
**I'm submitting a ...**
```
[x] feature request 
```
Currently the progress bar does not have an undetermined mode (see for example https://material.angular.io/components/progress-bar/overview)

I would like to have that since we're using the PrimeNG library for our project and we have that use case.

Regards, Nikola

**Comment by ridhanie** [comment]
I would like to see if PrimeNG can have the same undetermined mode.
