### ISSUE TITLE
Lazy scrollable datatable: not stable data

### ISSUE THREAD

**Issue by ekoch** [primefaces/primeng#4096]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/t8mRRI4ipugTV1pTUr2N?p=preview

**Current behavior**
Select checkbox at index 11. Scroll the table down until index 21. Line at Index 21 is line 11, selected, and then (about 500ms later) becomes line 21, not selected.

**Expected behavior**
Not showing line 21 (and others with greater index) at all until data is loaded.
And even better: start lazy loading before reaching the bottom of the list. Then if the user scroll not too fast, he will never see incorrect data / end of the loaded data set

**What is the motivation / use case for changing the behavior?**
Such scroll is not very pleasant to use. Seeing data switching from previous to next values feel like something buggous happends. The user may be lost, wondering if he has see all its items or not. 

**Please tell us about your environment:**
Ubuntu, IntelliJ, node.js, npm

* **Angular version:** 4.2.6

* **PrimeNG version:** 4.2.1

* **Browser:** Chrome Version 61.0.3163.100
 
* **Language:** [all]

**Comment by cagataycivici** [comment]
Should be fixed by;

https://github.com/primefaces/primeng/commit/ebfd396bbde58d51a0c9d92e8fe60469cbb46386
