### ISSUE TITLE
Datatable paginator performance issue

### ISSUE THREAD

**Issue by kevlapinski** [primefaces/primeng#4098]
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Plunkr Case (Bug Reports)**
None, but can work on providing one if needed.

**Current behavior**
Switching between pages on datatable using paginator causes hanging/long loading of pages.
Once the datatable is loaded, the rows per page needs to be changed before selecting pages for datatable to work properly.
If a page is selected without changing the rows per page first, the datatable hangs/freezes.
But if the rows per page is changed after datatable is loaded then datatable page switching functions as expected.

**Expected behavior**
Datatable should not hang when switching between paginator pages. Datatable should function the way it does after my workaround... without having to actually do the workaround.

* **Angular version:** 4.3.6

* **PrimeNG version:** 4.2.1

* **Browser:** [Chrome XX]
 
* **Language:** [TypeScript 2.5.2]

**Comment by kevlapinski** [comment]
**Update: The workaround for this issue required me to bind the 'rows' attribute to a variable on the javascript side.
rows="25", causes the performance issue
[rows]="rowCount", with rowCount=25 on the javascript side, fixes the issue

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=info
