### ISSUE TITLE
Datatables - Filtered table doesn't reflect updates to underlying data

### ISSUE THREAD

**Issue by GraemeSMiller** [primefaces/primeng#410]
If table is filtered and underlying data is updated the filtered view doesn't update.

See Plunk [here ](https://embed.plnkr.co/nKSC4KhKqEzWnDrAPqng/)
- Filter to show one row (In Plunk search box type Test)
- Update underlying data by button "Click Me" (Adds new entry called Test As Well and changes one entry to contain text Test)
- Filtered Rows don't change to include new data (also in my plunk pager page count changes again)
- Clear filter 
- Row data now shows correctly 
- Use same search text again - the 3 rows with Test text show

Expected
If a filter is applied and dataset changes then the filtered view should update to display the updated data

**Comment by GraemeSMiller** [comment]
Updated this to include Plunk repro - sorry forgot at the time

**Comment by marobright** [comment]
I'm having a similar issue.

The data in my data table come from an array. Updating the data in the array when the table is not filtered and the changes are reflected. However do the same thing on a filtered grid and the changes are no longer reflected.

Did you ever find a solution to this?

**Comment by GraemeSMiller** [comment]
Nope. Still have the issue.

**Comment by marobright** [comment]
This is how I got around it. When you filter a DataTable the data is held in a separate filteredList array. So whenever you update the underlying data if you reapply filters, the filteredList data is refreshed reflecting the updated values. Something like:

Declare this in your component to access the primeNG DataTable component:

`@ViewChild(DataTable) dataTableComponent: DataTable;`

Then whenever you modify the underlying data call something like:

```
if (this.dataTableComponent.hasFilter())
      {
        this.dataTableComponent.filter();
      }

```

**Comment by cagataycivici** [comment]
This should be fixed with newer releases, ngDoCheck reapplies filter if underlying data changes.

**Comment by GraemeSMiller** [comment]
Great our users will really like that!
