### ISSUE TITLE
Better documentation for AutoComplete immutable

### ISSUE THREAD

**Issue by lpenet** [primefaces/primeng#4103]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

I spent quite some time migrating an angular app from angular 4.0.0 / primeng 4.0.0 to angular 4.4.4 / primeng 4.2.2

What took me most of the time was  understanding the changes to the p-autoComplete. Finally, after much tweaking and debugging, I figured that all I had to to was do add 

    [dropdownMode]="'current'"
    [immutable]="false"

to the properties of existing p-autoComplete.

dropdownMode can be understood by reading other tickets and the standard doc. But I found nothing really clear about "immutable". The actual doc "Defines how the suggestions should be manipulated." is quite unclear to me.

So, I suggest that you provide additional doc on this immutable property.

**Comment by ryanbonial** [comment]
I'm not sure if it the same issue, but this change tripped me up too. In my case I found that my autocomplete was not showing any results. Adding `[immutable]="false"` to the autocomplete allowed the results to show, but the actually change I needed was to only set the results once in the autocomplete and exclude the immutable attribute (it defaults to true). Example:

Before (broken):
 ``` javascript
filterCountrySingle(event) {
    const query = event.query;        
    this.filteredCountriesSingle = []; // <--- this causes a problem
    this.countryService.getCountries(query)
        .subscribe(countries => {
            this.filteredCountriesSingle = countries;
        });
}
```
After (working):
 ``` javascript
filterCountrySingle(event) {
    const query = event.query;        
    this.countryService.getCountries(query)
        .subscribe(countries => {
            this.filteredCountriesSingle = [...countries];
        });
}
```

**Comment by kathirnk** [comment]
Thanks very much this saved my time.

**Comment by hsntngr** [comment]
Why using those components is that annoying. I mean I assuming you are using them as an inventor
