### ISSUE TITLE
DataTable Loading Animation Stuck With Lazy Loading

### ISSUE THREAD

**Issue by IsItBroken** [primefaces/primeng#4104]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/VZZNPPWfArygMi4p9ZrO?p=preview

**Current behavior**
For the DataTable when you set the lazy flag but supply a value up front the loading animation stays up.

**Expected behavior**
When the DataTable initializes it should check if the value array already has values before emitting the lazy load event.

**Minimal reproduction of the problem with instructions**
Set the DataTable to lazy and supply values upfront. 

**What is the motivation / use case for changing the behavior?**
We have the first page's data initially but need to keep the DataTable as lazy because when sorting we need to lazy load the new data and the lazy load event on sort won't fire without lazy set to true.  This was working as expected prior to version 4.2.

**Please tell us about your environment:**
Windows 7, VSCode, NPM, Tomcat

* **Angular version:** 2.0.X
4.4.4

* **PrimeNG version:** 2.0.X
4.2.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

* **Node (for AoT issues):** `node --version` =   N/A

**Comment by cagataycivici** [comment]
Duplicate #3963
