### ISSUE TITLE
SelectOneMenu ajax call does not update form on first call

### ISSUE THREAD

**Issue by vikashdanee** [primefaces/primeng#4105]
<p:selectOneMenu id="drawSelector" value="#{globalOptions.currentDrawNumber}">
                    <f:selectItems value="#{globalOptions.drawList.selects}"/>
                    <p:ajax event="change" update="@all"/>
 </p:selectOneMenu>

I have used update="@all" to refreshed all pages as I have two pages on single screen. When first time I change the value of SelectOnemenu component page is not refreshed. After second time everything works fine.

**Comment by cagataycivici** [comment]
This is PrimeNG tracker, use PrimeFaces instead please.
