### ISSUE TITLE
RuntimeError: Unexpected value 'MultiSelectModule' imported by the module 'SomeModule'. Please add a @NgModule annotation

### ISSUE THREAD

**Issue by penrique** [primefaces/primeng#4106]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**

Error: Unexpected value 'MultiSelectModule' imported by the module 'SomeModule'. Please add a @NgModule annotation

**Expected behavior**

**Minimal reproduction of the problem with instructions**
 @angular: 4.4.4
typescript: 2.5.3
primeng: 4.2.2

Just import said module and try using it, as soon as it is about to load error pops up

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.4.4

* **PrimeNG version:** 4.2.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=info
