### ISSUE TITLE
navlinks in schedule component

### ISSUE THREAD

**Issue by dhaval-aspire** [primefaces/primeng#4109]
**I'm submitting a ...** 
```
[x] bug report
```

**Current behavior**
Currently no option provided for navLinks of fullcalendar in schedule

**Expected behavior**
there should be one input property for that allowed to set navLinks

* **PrimeNG version:** 4.2.2 but also checked in master branch and it seems not even there

**Comment by aryanpatel** [comment]
Any update on this one? I also need navLinks to go to dayView on click action on date

**Comment by aryanpatel** [comment]
@dhaval-aspire Thanks for response. Can you give me hint of how you have customized it?

**Comment by dhaval-aspire** [comment]
After downloading from https://github.com/primefaces/primeng/tree/4.2.2  copy folder located at 'src/app/components/schedule' put in your project ,
now in your app module instead of importing schedule module from primeng, import from schedule.ts 

Now if you look schedule.ts file it is wrapper of fullcalendar so , create one input property
```
@Input() navLinks  = true;
```
and 
```
    ngOnInit() {
        this.config = {
            theme: true,
            header: this.header,
            navLinks  : this.navLinks
            ...
```
