### ISSUE TITLE
Export Sidebar from 'primeng' shorthand

### ISSUE THREAD

**Issue by pantonis** [primefaces/primeng#4110]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Project does not compile with following error "Module '/node_modules/primeng/primeng' has no exported member 'SidebarModule'"

**Expected behavior**
Should compile

**Please tell us about your environment:**

WIndows 10, npm, angular-cli

* **Angular version:** 2.0.X
4.2.5

* **PrimeNG version:** 2.0.X
4.2.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typscript

**Comment by bjareczek** [comment]
@pantonis , what does one have to do to get a PR reviewed? Thx.

**Comment by pantonis** [comment]
I suppose he will do it once he wants :)

**Comment by bjareczek** [comment]
Lol.  Ok -- I'd love to  help more, but may hold off on that!  Thx, @pantonis
