### ISSUE TITLE
Calendar timeOnly bugs

### ISSUE THREAD

**Issue by ili** [primefaces/primeng#4113]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
Sample:

http://plnkr.co/edit/QXiptEfVKKwK3XJmzry8?p=preview

**Current behavior**
If we do use calendar in `timeOnly` mode:
* if `dataType` is set to `string` - editing does not affect model (neither direct input nor using editor)
* if `dataType` is default only manual input affects model

**Comment by cagataycivici** [comment]
Duplicate #4125

**Comment by ili** [comment]
@cagataycivici sorry but I don't see the same case in #4125 
I'v checked v4.3.0, plunk & issue are updated

Please, reopen the issue
