### ISSUE TITLE
Datatable's scrollHeight does not change on a binding anymore (broken since 4.2.2)

### ISSUE THREAD

**Issue by ARandomDude** [primefaces/primeng#4114]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/4YrOKBik8IIX6uguThsE?p=preview
(Wait for 5 and then 10 seconds after running)

**Current behavior**
When a datatable's scrollHeight is set to a fixed value, the height and scrollbar is set as expected. But when the input is set via a binding variable (thus, [scrollHeight]="myvariable"), the scrollHeight is only set once at the beginning and never updates -- but it did update in PrimeNg <= 4.2.0.

**Expected behavior**
I would expect the scrollHeight to update again.

* **Angular version:** 4.2.6

* **PrimeNG version:** 4.2.2

* **Browsers:** All

**Comment by kroeder** [comment]
Works in 4.2.1 as well, not only in <= 4.2.0

**Comment by karloscode** [comment]
Same behaviuor form me

Angular version: 5.0.0
PrimeNG version: 5.0.0
Browser: [Chrome 56 | Firefox 45.0.1 ]
Language: [all | TypeScript 2.0 | ES6/7 | ES5]

**Comment by digaus** [comment]
Any news on this?

**Comment by bbuehrer** [comment]
I have the same problem with primeng 5.0.2.

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
