### ISSUE TITLE
MessageService Growls from slider events behave erratically

### ISSUE THREAD

**Issue by saturnine42** [primefaces/primeng#4115]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/XJrj8m?p=preview

**Current behavior**
Growl messages created from a slider event don't behave correctly. Sometimes they don't appear; when they do, when they start to fade they pop back again. I seem to get the issue whether I use MessageService or not.

**Expected behavior**
The growls created from the slider event should behave the same as those created from a button click; i.e. appear immediately and then fade and not come back.

**Minimal reproduction of the problem with instructions**
The referenced plunkr will create growls from both button clicks and moving the slider with the slider growls exhibiting the issue.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.4.0

* **PrimeNG version:** 4.2.1

* **Browser:** Chromium 60 | Firefox 58
(Haven't tried others)
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Works for me.

**Comment by RandomPrecision1** [comment]
Perhaps the issue is that if you don't drag the slider knob exactly, it doesn't fire? If you click on the bar itself to change the value, that may fire onChange(), but it doesn't fire onSlideEnd().

In the plunker you can set the slider to any value without ever triggering a message by just clicking the bar.
