### ISSUE TITLE
Datatable before select events to cancel selections

### ISSUE THREAD

**Issue by Ketec** [primefaces/primeng#4118]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behaviour**
Currently you cannot cancel row selection (header checkbox, checkbox or row click).

**Expected behavior**
It should  trigger event where we could return false or true (default true) so we can cancel specific row select. It should also provide the row data (so you can check for some value and decide if it should be checked). It should not check the checkbox for that row or trigger any select events and not populate selection or deselect rows (in case of single select).

**Comment by fullammo** [comment]
Would love this enhancement. In my case checkbox column selection gets messed up by my integrated contextMenu. Would be nice to prevent contextMenu's row selection capability.

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
