### ISSUE TITLE
E2E tests slowdown after primeng update

### ISSUE THREAD

**Issue by wsx-15** [primefaces/primeng#4120]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
After updating PrimeNG we noticed that Protractor tests slowed down significantly - time nearly doubled. There appears to be a bigger delay between actions (writing text to input etc.). We managed to pinpoint which version caused slowdown and it appears to be 4.1.2->4.1.3. The issue is still present in 4.2.1

* **Protractor version:** 5.1.2

* **Angular version:** 4.2.6

* **PrimeNG version:** 4.2.1

* **Browser:** [Chrome XX]

**Comment by cagataycivici** [comment]
No idea what can be done here.
