### ISSUE TITLE
DataTable isSelected check performance improvement

### ISSUE THREAD

**Issue by Ketec** [primefaces/primeng#4122]
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
```
    isSelected(rowData) {
        if(rowData && this.selection) {
            if(this.dataKey) {
```

if `this.selection` is [], it does not return false. Empty array is still true. It may need a extra  `&& this.selection.length > 0`.
**Expected behavior**
It should properly return false if selection is empty. This may also affect performance because angular change detection calls this method for every row on every mouse click or even mouse move and it constantly triggers all the logic inside (a grid with a thousand rows could easily trigger it tens of thousands of times every second).

**Comment by cagataycivici** [comment]
This broke the table so reverted.

**Comment by Ketec** [comment]
Broke how, i have  separate checkout of the code here for datatable so i could keep some critical fixes i need in place while/if they are fixed. And this one has been working fine on multiple different grids.
