### ISSUE TITLE
PrimeNG - Calendar Issues with TimePicker in TimeOnly mode.

### ISSUE THREAD

**Issue by pjhaan** [primefaces/primeng#4125]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
There are four separate issues with the time picker all revolving around the AM/PM portion of the time.  The issues and how to reproduce them are outlined in the attached plnkr.  

**Expected behavior**
The Hours and AM/PM values should change correctly when hitting the arrows on the time picker.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/BTGG7n?p=preview

**What is the motivation / use case for changing the behavior?**
We have an "Hours of Operation" feature that allows users to select their business hours.  The way it currently functions makes it difficult to select the right time of day.

* **Angular version:**  
4.2.6

* **PrimeNG version:** 
4.2.2

* **Browser:**
Chrome, Firefox, IE, Edge
 
* **Language:** 
ES5

**Comment by cagataycivici** [comment]
Some are fixed in other issues, please create separate issues in future if some of these persist in 4.3.0
