### ISSUE TITLE
DataTable shift click selection does not work with lazy load

### ISSUE THREAD

**Issue by wooleverj** [primefaces/primeng#4127]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://embed.plnkr.co/y0t5koCYCIHTVcHITso9/

**Current behavior**
The shift click with lazy load only selects items you currently have in the view.  See plunker for more details.

**Expected behavior**
I am expecting the shift click to select all the items between the last selected and shift select.  

**Minimal reproduction of the problem with instructions**

As the plunker suggests if you click on an item and scroll passed the lazy load and shift click then scroll back up it only selects the items that were in the view port.  If shift click is to work with lazy load there needs to be a way that all the items between clicks gets highlighted.

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.

**Comment by giorgiootto** [comment]
p-datatable and p-table, both, dont work. Version 5.2.7
