### ISSUE TITLE
fileupload - IE Fails to load selected files on second attempt

### ISSUE THREAD

**Issue by mpierce5** [primefaces/primeng#4128]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Error occurs on primeng site - https://www.primefaces.org/primeng/#/fileupload

**Current behavior**
In IE 11 when selecting a file after the first upload is complete, fileupload component fails to show the file that the user select has selected.

**Expected behavior**
When selecting a file the second time the file should appear in the list of files to be uploaded.

**Minimal reproduction of the problem with instructions**
 --BUG OCCURS IN IE 11
1. Navigate to https://www.primefaces.org/primeng/#/fileupload
2. On advanced example click "Choose"
3. Select a file and click open.  
  * File appears in list of files to upload
4. Click upload button (file uploads)
5. Click "Choose" button again
6. Select another file and click open.
  * Error - File does not appear in list of files to upload
7. Click "Choose" button again
8. Select another file and click open.
  * File appears in list of files to upload as expected

**What is the motivation / use case for changing the behavior?**
Discrepancy in functionality between browsers. Causes confusion when using file upload when the selected file does not appear in the list (bug)

**Please tell us about your environment:**
IE 11 - version: 11.1106.10586.0
Windows 10

* **Angular version:** 
^2.0.0 -Latest

* **PrimeNG version:**
^4.2.1 - Latest

* **Browser:** 
IE 11
 
* **Language:** 
TypeScript 2.3.3

**Comment by cagataycivici** [comment]
Try witjh 4.2.2 please
