### ISSUE TITLE
Bug: Loading Symbol Persists on DataTable

### ISSUE THREAD

**Issue by ericrovtar** [primefaces/primeng#4135]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Here is a video showing the issue, since this is difficult to capture in a Plunkr: [PrimeNG.zip](https://github.com/primefaces/primeng/files/1368799/PrimeNG.zip)

Specific details are also below.

**Current behavior**
After updating to 4.2.2, DataTable shows a perpetually loading symbol which prevents user interaction with the table.

**Expected behavior**
Loading symbol should not remain after data is loaded.

**Minimal reproduction of the problem with instructions**
It is happening on all instances where we use the DataTable throughout our app. This does not seem to happen with static data.

It has something to do with the `lazy` attribute is set to `true`. If I set `lazy` to `false` (besides the `onLazyLoad` method no longer being called, thus breaking the data loading), the persistent loading spinner is gone.

All instances of our DataTable use set the following attributes:

- lazy: true
- paginator: true
- resizableColumns: true
- columnResizeMode: expand
- responsive: true
- scrollable: true
- onLazyLoad

Some combination of these things is what is triggering the issue.

**What is the motivation / use case for changing the behavior?**
So we can properly upgrade to the latest version and fix the Calendar validation issue.

**Please tell us about your environment:**
macOS High Sierra, Visual Studio Code, webpack

* **Angular version:** 4.1.3

* **PrimeNG version:** 4.2.2

* **Browser:** Chrome 61.0.3163.100 | Firefox XX | Safari 11.0

 
* **Language:** all

* **Node (for AoT issues):** `node --version` =

**Comment by ericrovtar** [comment]
Looked into this a bit more...

The bug seems to be that `div.ui-datatable-loading` is rendered in the HTML whenever `[lazy]=true`.

This can be overwritten in the CSS by adding `display: none;` to the `.ui-datatable .ui-datatable-loading` and `.ui-datatable .ui-datatable-loading-content` classes.

**Comment by chris-jones-pixitmedia** [comment]
Just noticed the same behaviour after updating primeng. If you want to retain the behaviour of the spinner (i.e. show it when data is loading, hide it when data has loaded), add the following to your scss:

```
    p-datatable {
      &[ng-reflect-loading="false"] {
        .ui-datatable {
          .ui-datatable-loading,
          .ui-datatable-loading-content {
            display: none;
          }
        }
      }
    }
```

Obviously, this is just a workaround until the bug is fixed, but seems to work.

**Comment by ericrovtar** [comment]
@chris-jones-pixitmedia Nice! We don't use the loading spinner at all, so my take was to just hide it outright, but your solution works for anyone who might use it.

**Comment by cagataycivici** [comment]
[enableLoader]="false"
