### ISSUE TITLE
DataGrid: the 'rows' parameter is actually the amount of items to display 

### ISSUE THREAD

**Issue by SebastianFree** [primefaces/primeng#4143]
As can be seen on the current showcase page for the DataGrid, the 'rows' parameter is set to 20, not indicating the amount of rows but indicating the amount of items to display per page.

Is this a bug? Some unfinished feature? An intermediary state in development?<BR>
How I understand the component from its description, we specify the amount of rows and through that the pages and items in the page adjust automatically to the given size of the component.

Please advise.

**Comment by cagataycivici** [comment]
Use forum for questions please, documentation has information as well.
