### ISSUE TITLE
Datatable sort icons / classes

### ISSUE THREAD

**Issue by westwick** [primefaces/primeng#4147]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

I'd like to be able to customize the look of the datatable header by supplying different sort icons. Additionally I'd like to be able to specify that it should be to the left of the label instead of to the right (although this can probably be accomplished with just css - I haven't dug too far). I hope I haven't missed this somewhere else, I searched the docs, issues and roadmap and didn't see it.

The sorticon can probably be changed with just css as well, however it would feel kind of 'hacky' since the classes being applied are `fa fa-sort` etc. So it'd also be nice to maybe supply a custom class for the different column sort states. 

**What is the motivation / use case for changing the behavior?**
Allow more customization of the controls

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
