### ISSUE TITLE
Styling button on button bar file-upload

### ISSUE THREAD

**Issue by dinhquyf0** [primefaces/primeng#4151]
![image](https://user-images.githubusercontent.com/14790204/31431183-24d714f6-ae9d-11e7-9301-62be4b8cdd57.png)
How can I style these button. 
Here is my css but it's not work. Any one help me? Thanks!
.ui-fileupload-buttonbar .ui-button .ui-fluid {
  width: 100px !important;
}

**Comment by cagataycivici** [comment]
Please use forum for questions and support requests.
