### ISSUE TITLE
p-dropdown template on p-datatable triggers sort on click

### ISSUE THREAD

**Issue by Merve7** [primefaces/primeng#4152]

**Comment by sviswanathjcet** [comment]
<p-dataTable #dt [value]="cars" [(selection)]="selectedItems" [editable]="true" (onEditInit)="onEditInit($event)" (onEdit)="onEdit($event)" (onEditCancel)="onEditCancel($event)" (onEditComplete)="onEditComplete($event)">
<p-column [style]="{ 'width':'38px', 'text-align':'center' }" selectionMode="multiple">
<p-column field="vin" header="Vin" [editable]="true">
<p-column field="year" header="Year" [editable]="true">

<input type="number" class="ui-inputtext ui-widget ui-state-default ui-corner-all"
[(ngModel)]="rowData[col.field]" [ngModelOptions]="{standalone:true}"
(onchange)="dataTableOnBlur($event, col, rowData, rowIndex, dt)" />


<p-column field="color" header="Color" [editable]="true">
On Change event is not firing . I tried blur but its triggering even though the value not changed. Can you help me on this ?
