### ISSUE TITLE
DataTable - Allow show/hide columns selection from component template column implementation

### ISSUE THREAD

**Issue by kentonbmax** [primefaces/primeng#4153]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Show/hide columns requires using backing array of columns on the component and ngFor in the template. Limits the use of format through ng-templates if you have lots of columns and different types of data. 

**Expected behavior**
Support show/hide from a context menu and allow users to define tables columns individually. 
consider the show hide in this example [angular 4 datatable](https://www.npmjs.com/package/angular-4-data-table)

**What is the motivation / use case for changing the behavior?**

- ease of use, simple show hide (you already have the hide property), transitioning companies to newer technology without road blocks. Almost every other example uses columns defined in the template, it always happens that you need almost all the features in a specific implementation. 
- I have seen the pipe example and it is not maintainable. 

**Please tell us about your environment:**
angular 4, VSC, TS

* **Angular version:** 2.0.X
4.4.3

* **PrimeNG version:** 2.0.X
4.2.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X
Chrome, Edge, IE 11
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
2.3.4
* **Node (for AoT issues):** `node --version` =   
8.4

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.

**Comment by viswa-optimusprime** [comment]
@cagataycivici  Do you have this feature in new turbo table ?

**Comment by viswa-optimusprime** [comment]
@kentonbmax  Hi , Did you check this feature in primeng turbo table?
