### ISSUE TITLE
onValueChange callback not invoked on DataTable

### ISSUE THREAD

**Issue by dzhavat** [primefaces/primeng#4158]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**

http://plnkr.co/edit/nrISQ14EaMah5Z3ijJUj?p=preview

**Current behavior**

When listening for the `onValueChange` event on a `DataTable`, the callback is never invoked. 

**Expected behavior**

The `onValueChange` callback should be invoked whenever `DataTable`'s value gets updated.

**Minimal reproduction of the problem with instructions**

1. Open the Plunkr example.
2. Click on the add button to add a new record to the `cols` array.
3. Open the console and see if there is something logged out
4. Change the event binding on the `dataTable` in the template to `valueChange`
5. Click again on the add button and check the console
6. Now you should be able to see the new value

**What is the motivation / use case for changing the behavior?**

Consistency between the documentation and the actual implementation.

**Please tell us about your environment:**

* **PrimeNG version:** 4.2.2

**Comment by sviswanathjcet** [comment]
Can you work on this issue as high priority? We are using primeng datatable in our application. Because of this issue we are looking for different Kendo UI grid .It would be helpful if we have this feature. We appreciate your work on primeng

**Comment by dzhavat** [comment]
The fix is pretty simple. I've already submitted a PR. Now it's up to the
maintainers to decide if they're going to merge it.

@sviswanathjcet this feature is working fine. The problem is that it's
bound to `valueChange` and not to `onValueChange`, which is mentioned in
the docs.

**Comment by sviswanathjcet** [comment]
Thank you so much for the reply. I am new to primeng. Where i can find primeng doc?

**Comment by dzhavat** [comment]
[Here](https://www.primefaces.org/primeng/#/datatable) you can find the docs for DataTable. If you need a different component just look at the sidebar.

**Comment by cagataycivici** [comment]
I don't understand this one, valueChange is the syntactic sugar part to write the value back;

```
[(value)]
```

See two-way binding at;

https://angular.io/guide/template-syntax

So when the datatable changes the data internally, it writes it back using this but I don't think we ever use it since DataTable does not change the bound data, it is only one-way, I actually cannot remember why we have this in the first place. 

What is your use case here? What is the difference between onValueChange and valueChange?

**Comment by dzhavat** [comment]
> What is your use case here? What is the difference between `onValueChange` and `valueChange`?

I don't have a use case. I just noticed that there's a difference between the [documentation](https://github.com/primefaces/primeng/blob/master/src/app/showcase/components/datatable/datatabledemo.html#L1628) and the [implementation](https://github.com/primefaces/primeng/blob/master/src/app/components/datatable/datatable.ts#L676) and decided to make a PR with a fix. 

I can see here in GitHub that the [`valueChange` event was added to the `DataTable`](#3593) 3 months ago (August 7th). The [documentation for that property](https://github.com/primefaces/primeng/commit/5dd45c75c1bab90e7059baecae306203a4dcdc37) was added by you later that day.

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.

**Comment by sviswanathjcet** [comment]
@cagataycivici When 5.1.0 will be released ? is it on July 17, 2018 because label is assigned to that date
