### ISSUE TITLE
AutoComplete - Dropdown click does not invoke complete method

### ISSUE THREAD

**Issue by joerter** [primefaces/primeng#4164]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/whXw39tV90gtBJA6bDP1?p=preview

**Current behavior**
When clicking the dropdown button, the method bound to the onCompleteMethod event is not called.

**Expected behavior**
The method bound to the onCompleteMethod should be called, and the suggestions panel should display.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/whXw39tV90gtBJA6bDP1?p=preview

* **Angular version:** 4.2.6
* **PrimeNG version:** 4.2.0

* **Browser:** all
 
* **Language:** Typescript

**Comment by VNYoeri** [comment]
After updating the Plunkr so that is uses PrimeNG 4.2.2, the dropdown works just fine without any further adjustments to your code :)

For the record: in PrimeNG version 4.1.X you had to call a separate event "onDropdownClick".

**Comment by joerter** [comment]
Woops! Thank you, I'll close this now.
