### ISSUE TITLE
Dynamic column grouping for DataTable

### ISSUE THREAD

**Issue by JagannathLenka** [primefaces/primeng#4166]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview

**Current behavior**

For the below code, my data looks something like this

data = [
              {class_1_value: 1 , class_1_section: "A",  class_1_teacher: "ms brown",
               class_1_value: 1 , class_1_section: "B",   class_1_teacher: "ms white",
               class_1_value: 1 , class_1_section: "C",   class_1_teacher: "ms sunshine"},
              {class_2_value: 2 , class_2_section: "A", class_2_teacher: "ms brown2",
               class_2_value: 2 , class_2_section: "B", class_2_teacher: "ms white2",
               class_2_value: 2 , class_2_section: "C", class_2_teacher: "ms sunshine2"},
]
 
<p-dataTable [value]="data" [resizableColumns]="true" scrollable="true" scrollHeight="200px" >       
    <p-column class="a" *ngFor="let col of arr  " [field]="col.field" [header]="col.header" [style]="col.width" ></p-column>
</p-dataTable>

In this, I want to put a grouping for each 3 columns (Section A, Seciton B, Section C). The names of the section will be dynamic.

Is this doabl?

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Please use forum for support requests.
