### ISSUE TITLE
Property Visible in menumodel does not work, Im using menubar

### ISSUE THREAD

**Issue by xyz765** [primefaces/primeng#4170]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

           { label: 'logout', icon: 'fa-pencil', visible: true, command: () => { this.logout() }},
            {label: 'logout2', icon: 'fa-pencil', visible: false, command: () => { this.logout() }  }

Both are visible

**Expected behavior**

Only the first one option visible  'logout" 

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.3.6

* **PrimeNG version:** 4.2.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by sourdoth** [comment]
same here, two element show in menu

.ts
this.item [{label: 'user', routerLink: ['/user-list'] visible:true},{label: 'rol', routerLink: ['/rol-list'] visible:false}];
HTML
<p-panelMenu [model]="items"  [multiple]="false"></p-panelMenu>
