### ISSUE TITLE
TabView expression changed after it was checked

### ISSUE THREAD

**Issue by OscarCenito** [primefaces/primeng#4171]
**I'm submitting a ...**  
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Angular version 4.4.3
PrimeNg version 4.2.2

When I use TabView I get the follow error:

> ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: 'true'.
    at viewDebugError (core.es5.js:8434)
    at expressionChangedAfterItHasBeenCheckedError (core.es5.js:8412)
    at checkBindingNoChanges (core.es5.js:8576)
    at checkNoChangesNodeInline (core.es5.js:12448)

which occurs in TabPanel.html. on this line:

`  <p-templateLoader [template]="contentTemplate" *ngIf="contentTemplate&&(cache ? loaded : selected)"></p-templateLoader>`

What am I missing?

My template code looks like this:

> <p-tabView 
>     *ngIf="items.length > 0"
>     [controlClose]="true"
>     (onClose)="onCloseControl($event)">
>         <p-tabPanel       
>         [cache]="true" 
>         [header]="item.label" 
>         [closable]="(item.isEditing$ | async)"
>         *ngFor="let item of items">
>             <ng-template pTemplate="content">
>                 <tags [currentControllerConfig]="item.controllerConfig"></tags>
>             </ng-template>
>         </p-tabPanel>
>         <p-tabPanel
>             [disabled]="!(addItem.isEditing$ | async)"
>             [closable]="addItem.canBeClosed"
>             [leftIcon]="addItem.icon">
>         </p-tabPanel>
> </p-tabView>

Got a similar issue with the property 'selected' on the interface MenuItem, but I extended the interface to include this property and lost that behavior. Seems like there is some logic in the code which isn't reflected in the interfaces?

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview

**Comment by theFlyingCat04** [comment]
Same Problem over here. With Plunkr:
http://plnkr.co/edit/zuoarFerpRoYPBY396R5?p=info

Problem occurs when a tab is initially visible (via boolean expression in ngIf) and then has to disappear. The other way round the  ExpressionChangedAfterItHasBeenCheckedError is not raised.
