### ISSUE TITLE
Sticky Column Headers

### ISSUE THREAD

**Issue by smitpsanghavi** [primefaces/primeng#4172]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Expected behavior**
The headers should be sticky and should be visible even if we have scrolled down and the headers are outside the viewport.

**Minimal reproduction of the problem with instructions**
Existing implementation in PrimeUI : https://www.primefaces.org/primeui/#datatableSticky

**What is the motivation / use case for changing the behavior?**
Makes it easier to view datasets which go all the way down. Specifically useful for virtual scrolling.

**Comment by pantonis** [comment]
According to this excellent article [Design better data tables](https://uxdesign.cc/design-better-data-tables-4ecc99d23356) sticky headers is a basic requirement for good UX

**Comment by markleppke** [comment]
Possibly make sticky directive that could be applied to any set of elements. (navigation menues, table row, etc.)

**Comment by smitpsanghavi** [comment]
Stick is available since PrimeNG 7
