### ISSUE TITLE
New component: Form wizard

### ISSUE THREAD

**Issue by dennisholmer** [primefaces/primeng#4174]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

How about a form wizard component? Here is a library for AngularJS as example [angular-wizard](https://github.com/angular-wizard/angular-wizard).

Suggested features:

- Validation for every step (based on Angular form validation)
- Customizable button texts (E.g. for localization)
- Dynamic steps (Adding/Removing steps depending on e.g. selections in previous steps)
- Dynamic loading of step (Do not load step content until it is reached)

**Comment by sudheerj** [comment]
During development of our book, we developed wizard kind of component with the help of steps component https://www.npmjs.com/package/primeng-extensions-wizard

**Comment by davisb10** [comment]
Can this request be reevaluated? This would be a very useful feature to be included in the main library and not in an extension library, as the extension package is currently 2 years old with outdated dependencies. 

I'm open to working on it / adding pull requests if needed.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
