### ISSUE TITLE
scrollable datatable with frozen columns be misaligned with difference style

### ISSUE THREAD

**Issue by lsa-shanghai** [primefaces/primeng#4175]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/TRcCLvTlVg3J5sVEEwJs?p=preview

**Current behavior**

With p-datatable scroll  sample code,  rows will misalign if:
1. with other theme
 
    <link rel="stylesheet" href="https://unpkg.com/primeng@4.2.2/resources/themes/bootstrap/theme.css" />
2. with other font-size:
body {
  padding: 2em;
  font-size: 13px; 
  font-family: Arial, Helvetica, sans-serif;
}

**Expected behavior**

It should be nothing to do with style. 

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/TRcCLvTlVg3J5sVEEwJs?p=preview

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.2.X

* **PrimeNG version:** 4.2.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
You need to set manual height to the brand column in the plunkr. Heights are not auto calculated to avoid performance issues. More info and a sample at;

https://www.primefaces.org/primeng/#/datatable
