### ISSUE TITLE
Datatable footer function called every mouse click

### ISSUE THREAD

**Issue by sviswanathjcet** [primefaces/primeng#4177]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")

Datatable footer function called every mouse click
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview

http://plnkr.co/edit/aOhpjb?p=preview

**Current behavior**
Datatable footer function called every mouse click

http://plnkr.co/edit/aOhpjb?p=preview

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.X
4.4.X

* **PrimeNG version:** 4.2.2.X
4.2.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by sviswanathjcet** [comment]
<p-dataTable #dt [value]="cars" [(selection)]="selectedItems" [editable]="true" (onEditInit)="onEditInit($event)" (onEdit)="onEdit($event)" (onEditCancel)="onEditCancel($event)" (onEditComplete)="onEditComplete($event)">
  <p-column [style]="{ 'width':'38px', 'text-align':'center' }" selectionMode="multiple"></p-column>
  <p-column field="vin" type="number" header="Vin" [editable]="true">
    <ng-template let-col let-rowData="rowData" pTemplate="editor">
      <input type="number" class="ui-inputtext ui-widget ui-state-default ui-corner-all"
             [(ngModel)]="rowData[col.field]" [ngModelOptions]="{standalone:true}"
             (change)="onCellEditorInput($event, col, rowData)" />
    </ng-template>
    
  </p-column>
  <p-column field="year" type="number"  header="Year" [editable]="true">
    <ng-template let-col let-rowData="rowData" pTemplate="editor">
      <input type="number" class="ui-inputtext ui-widget ui-state-default ui-corner-all"
             [(ngModel)]="rowData[col.field]" [ngModelOptions]="{standalone:true}"
             (change)="onCellEditorInput($event, col, rowData)" />
    </ng-template>
  </p-column>
  <p-column field="color"  [editable]="false" footer="true">
     <ng-template  pTemplate="footer">
       <span>{{calculateTotal()}}</span>
     </ng-template>
    <ng-template let-col let-rowData="rowData" pTemplate="body" >
               <input type="number"  ng-bind="rowData[col.field]"/>
       </ng-template>
  </p-column>
</p-dataTable>

**Comment by cagataycivici** [comment]
Please update the issue to answer the questions above to provide more info.

**Comment by sviswanathjcet** [comment]
@cagataycivici . Thank you so much for the reply. Please find below plunker.The footer function called even for mouse click

http://plnkr.co/edit/aOhpjb?p=preview

**Comment by sviswanathjcet** [comment]
![image](https://user-images.githubusercontent.com/8823651/31782535-70f59918-b4b8-11e7-91e5-5d3eed080169.png)

log attched

**Comment by sviswanathjcet** [comment]
@cagataycivici  Can i get any update on this ?

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
