### ISSUE TITLE
Katex support for Editor

### ISSUE THREAD

**Issue by JairDiaz23** [primefaces/primeng#4182]
[ x] bug report => Search github for a similar issue or PR before submitting

**Current behavior**
I can't use formula format when using the p-editor selector from primeng. I tried to add a custom toolbar from the editor and everythings works fine, but when I try to add a formula format from quill I receive a:
```
 "window.katex.render is not a function
    at Function.create (eval at webpackJsonp.../../../../script-loader/addScript.js.module.exports "
```

I added the CDN of katex in the index.html by adding the next lines:
```
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0-alpha/katex.min.css" integrity="sha384-FkMHIpkXHDi3o2XSOOa5/9TpXg4AX4DXPSC6z28hi2Eqn/27ea8MTV18rTq9OyQR" crossorigin="anonymous">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0-alpha/katex.min.js" integrity="sha384-wt0V9VomB0kx/jgLEkR18Slo+aNALuRwOOrWkicjQ0HHpFqu0JKzaFkbtmsku5a/" crossorigin="anonymous"></script>
```

but It doesn't seem to work. Does anyone have any idea why this happen?

* **Angular version:** 4.2.4
* **PrimeNG version:** 4.2.2

**Comment by sudheerj** [comment]
AFAIK, it supports only Toolbar module.

@cagataycivici Is it editor supports other modules as well(Formula,keyboard,history and so on)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
