### ISSUE TITLE
Footer label going outside the horizontal scroll bar in primeng datatable 

### ISSUE THREAD

**Issue by parth23** [primefaces/primeng#4184]
**Current behavior**
Note: Copy and paste below url in your browser if it not open on a click.
[https://stackoverflow.com/questions/46764261/footer-label-going-outside-the-horizontal-scroll-bar-in-primeng-datatable](url)
`<p-dataTable [value]="cars" scrollable="true" scrollHeight="200px" scrollWidth="600px" [style]="{'margin-top':'30px'}">
        <p-header>Vertical and Horizontal</p-header>
        <p-column field="vin" header="Vin" footer="Vin" [style]="{'width':'250px'}"></p-column>
        <p-column field="year" header="Year" footer="Year" [style]="{'width':'250px'}"></p-column>
        <p-column field="brand" header="Brand" footer="Brand" [style]="{'width':'250px'}"></p-column>
        <p-column field="color" header="Color" footer="Color" [style]="{'width':'250px'}"></p-column>
    </p-dataTable>`
**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

* **Angular version:**4.2.0

* **PrimeNG version:** 4.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript 2.3.3. | ES6/7 | ES5]

**Comment by sudheerj** [comment]
I can't replicate the issue in PrimeNG showcase(IE and Chrome). But I can see the behavior in your thread.

**Comment by parth23** [comment]
@sudheerj my screen resolution is: 1366 x 768

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview

**Comment by MarkRyanDev** [comment]
Here's a plunkr http://plnkr.co/edit/3zrfL9BYsiioL8dOAbQA?p=preview

**Comment by parth23** [comment]
@MarkRyanDev  Thanks for creating plnkr demo. @cagataycivici  please reopen this issue

**Comment by sviswanathjcet** [comment]
@cagataycivici I am also facing same issue. is there any work around for this ?
![image](https://user-images.githubusercontent.com/8823651/32798761-eb76d4e8-c932-11e7-9397-e04ccc898bd8.png)

**Comment by sviswanathjcet** [comment]
@cagataycivici  can you fix this issue ?

**Comment by sviswanathjcet** [comment]
Footer should be inside scroll bar

**Comment by JonaliDas** [comment]
I am facing issue. I am using primeng 6.0.0-beta-1.  Any fix for this issue ??
