### ISSUE TITLE
Calling "dt.reset()" doesn't reset dropdown selected option

### ISSUE THREAD

**Issue by parisgianluca** [primefaces/primeng#4185]
I'm submitting a
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
dt.reset() resets all filters, but does not reset the selected option on a dropdown item filter.

**Expected behavior**
The method should select the "placeholder" option on a dropdown when called

* **Angular version:** 5.0.0 rc2

* **PrimeNG version:** 4.2.2

* **Browser:** all

**Comment by cagataycivici** [comment]
Custom filters should be reset by you, datatable does not know the content of the custom filters.
