### ISSUE TITLE
CSS not loading 

### ISSUE THREAD

**Issue by steve-frank** [primefaces/primeng#4187]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...** 
```
[X ] bug report => Search github for a similar issue or PR before submitting

```

**Current behavior**
I have imported DataTableModule and SharedModule as follows:
`import {DataTableModule,SharedModule} from 'primeng/primeng';`

and in  my html, I have following code : 

```
<p-dataTable [value]="allSubjects">
<p-column *ngFor="let col of cols" [field]="col.field" [header]="col.header"></p-column>
</p-dataTable>
```
the data gets loaded and it is is shown on UI like this : 
![image](https://user-images.githubusercontent.com/31277095/31611841-7b209056-b232-11e7-97e9-8afdb576b682.png)

The styles which are there in primeng.css. and in ..omega/theme.css are not getting applied.

I have imported this styles correctly as directed on https://www.primefaces.org/primeng/#/setup page and  also checked it in the browser debugger. 
when I manually set the class from these stylesheets to any div like this : 
<div class="ui-datatable"/> , I can see the content in the browser debugger, style section.

but its not getting applied on its own.

please help.!! 

* **Angular version:** 4.3.0

* **"primeng": "^4.2.2",

tested in 
* **Browser:** [Chrome XX ]

 
* **Language:** [TypeScript 2.3.4 |]

**Comment by sudheerj** [comment]
You need to build the CSS if you are trying with showcase.

https://github.com/primefaces/primeng/wiki/Building-From-Source

Or else look into these setups

https://github.com/ova2/angular-development-with-primeng
