### ISSUE TITLE
The UTC time format still does not work in the calendar.

### ISSUE THREAD

**Issue by MaxBurda** [primefaces/primeng#4188]
Now the calendar displays only local time. The properties [utc]="true"  does not work.
This can be seen from the example.
Please click on the link and choose any date.
https://stackblitz.com/edit/prime-ng-calendar?embed=1&file=app/calendar/calendar.component.html

* **Angular version:** 4.4.5

* **PrimeNG version:** 4.2.2

![utc](https://user-images.githubusercontent.com/11576087/31669474-d6c7d8f2-b35d-11e7-9929-9320306996fe.jpg)

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/issues/3611
