### ISSUE TITLE
Disabled button should force removal of ui-state-hover class

### ISSUE THREAD

**Issue by brian428** [primefaces/primeng#419]
Just a small bug, but if you have a button with its disabled property bound:

```
<button pButton type="button" label="Deselect" icon="fa fa-minus-circle" title="Deselect"
        [disabled]="selectedItems.length === 0" (click)="onDeselectClick()"></button>
```

If the click handler clears the `selectedItems` array, the disabled binding is updated and the button becomes disabled. But the `ui-state-hover` class is still applied to the button, meaning it is now disabled **and** still lit up with the hover class.

**Comment by cagataycivici** [comment]
Fix checked in, thank you.
