### ISSUE TITLE
p-autocomplete suggestions box not displaying as expected

### ISSUE THREAD

**Issue by thirumalai-kc** [primefaces/primeng#4190]
Current behavior
p-autocomplete suggestions box not displaying as expected

Expected behavior
Suggestions box should be displaying on typing or entering backspace char by char

Minimal reproduction of the problem with instructions
<p-autoComplete placeholder="Start typing name to see suggestions" formControlName="customerRequest" [suggestions]="customerResults" (completeMethod)="searchCustomer('customer_name', $event.query)" minLength="2" field="accountName" (onSelect)="setCustomerRequest($event)">

Result: Start type 'ab' - Got results for 'ab' from backend and the suggestions box displayed
Then type 'c' - Got results for 'abc' from backend but suggestions box not displayed
Then remove 'c' - Got results for 'ab' from backend but suggestions box not displayed

Expected: Suggestions box should be displayed as expected

There is no issues in the data received from backend in all above cases. Please address this issue.

Angular version: 4.3.1
PrimeNG version: 4.2.X
Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Language: [all | TypeScript X.X | ES6/7 | ES5]

**Comment by prashantbirajdar** [comment]
having same problem but it was working in last month as expected. don't know what was changed

**Comment by jayordway** [comment]
I am experiencing the same with 4.2.2
