### ISSUE TITLE
p-multiselect template on p-datatable closes on click

### ISSUE THREAD

**Issue by kcsahoo** [primefaces/primeng#4192]
Inside datatable, multiselect template closes on click of an entry.

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview

**Comment by kcsahoo** [comment]
When you have a multi select in a data table column through, ng-template, the multi-select window closes when you click on any item in the list. Then it does not allow to select multiple items.

**Comment by kcsahoo** [comment]
The code is
<p-column field="variants" header="Variants" [style]="{'overflow':'visible'}">
                        <ng-template let-col let-data="rowData" let-rowIndex="rowIndex" pTemplate="body">
                            <p-multiSelect [style]="{'width':'100%'}" id="selectedVariants" name="selectedVariants"
                                           [options]="variantList" [(ngModel)]="data.variants" (onChange)="updateSelectedInteriorColour(data.id, $event)"
                                           defaultLabel="Choose Variants">
                            </p-multiSelect>
                        </ng-template>
</p-column>

**Comment by kcsahoo** [comment]
Is the issue similar to #4152 ?

**Comment by cagataycivici** [comment]
Is this an editable table? So does the cell close?

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a plunkr;

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=info

**Comment by Naveed1842** [comment]
facing same issue.We are using multiselect inside the p-table and whenever user try to select multiple options the multiselect close after one selection
@cagataycivici
