### ISSUE TITLE
Calendar should switch to month of today if today is clicked

### ISSUE THREAD

**Issue by ddivita** [primefaces/primeng#4194]
**I'm submitting a feature request
```

[X] feature request 
```
When the calendar is active it would be nice if the date value would be followed in the calendar:

Move the calendar back before today's date:
![image](https://user-images.githubusercontent.com/3431250/31680806-6b977fe8-b343-11e7-9f00-1b32fe8ca0f9.png)

Set the date to today and you will notice the calendar is still set to the last position (in this case July):
![image](https://user-images.githubusercontent.com/3431250/31680947-d41be374-b343-11e7-995c-3c9a2bf3e36f.png)

It would be nice if the calendar would move to the date / date range indicated by the input box.

**Comment by sudheerj** [comment]
The description is quite not clear. Can you please explain bit further on expected behavior
