### ISSUE TITLE
Tabmenu - class ui-state-active is not set correctly on <a> and <li> elements when routing with guards

### ISSUE THREAD

**Issue by fxmfr** [primefaces/primeng#4197]
**I'm submitting a ...** 
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
[http://plnkr.co/edit/6QjDRAyY6u72olX7qPXS?p=preview](http://plnkr.co/edit/6QjDRAyY6u72olX7qPXS?p=preview)

**Current behavior**
When routing with guards (CanActivate, CanDeactivate) active items of tabmenu getting out of sync with router.
Maybe other menu components are affected as well.

**Expected behavior**
Active classes should always reflect routers current route/url.

**Minimal reproduction of the problem with instructions**
In plunkr above:

- click Page 2
- click Page 3
- `<a>`-element of tab 2 and `<li>`-element of tab 3 now have class 'ui-state-active'

ui-state-active classes should only be added to tab 2.

**What is the motivation / use case for changing the behavior?**
Users should see correct activated tab corresponding to the current url.

**Please tell us about your environment:**
Windows 10

* **Angular version:** 
4.4.4

* **PrimeNG version:**
4.2.2

* **Browser:** 
Chrome 61

**Comment by sabithpocker** [comment]
Is this fixed already? Or a workaround while this is being fixed? I have the same issue with Tabs when traversing to a route with multiple Guards.

**Comment by fxmfr** [comment]
@sabithpocker just to clarify, the problem mentioned here (my issue described above) is **not** fixed.
I'm glad to hear that your issue (which is different from this one) is fixed.

**Comment by danailvidev** [comment]
If your using canActive and canDeactivate guards and comment line 62 https://github.com/primefaces/primeng/blob/master/src/app/components/tabmenu/tabmenu.ts , then subsribe to  this.router.events.subscribe( event => if( event instanceof NavigationEnd) this.activeItems = yourMenuitem[intex]) will work

**Comment by debunnell** [comment]
A quick workaround is to store the MenuItem from the last successful navigation. Then set the activeItem back to the stored item whenever there is a NavigationCancel event. 

The menu item will be selected briefly and then snap back to the previous item but I don't consider that a problem.

    @ViewChild(TabMenu) menu: TabMenu;
    lastActiveItem: MenuItem;

    constructor(
      private router: Router
    ) { }

    ngOnInit() {

      this.router.events.subscribe(e => {
        if(e instanceof NavigationEnd){
          this.lastActiveItem = this.menu.activeItem;
        }
        if(e instanceof NavigationCancel){
          this.menu.activeItem = this.lastActiveItem;
        }
      });
    }

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG (you can check at https://www.primefaces.org/primeng/#/tabmenu/info). If the issue still persists with the new version please create a new issue with our stackblitz template.

**Comment by tamasbege** [comment]
This issue is still present in the 9.0.5 PrimeNG with Angular 8. When using guards with tabmenu, if the navigation is not successful, two tabs remain active.
The workaround solves the problem however...
