### ISSUE TITLE
Pie chart displaying label value with percentages

### ISSUE THREAD

**Issue by tsvetomirivanovv** [primefaces/primeng#4198]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview

**Current behavior**
Pie chart data displays only values. = 
"Label 1:  50"
"Label 2:  50" 

**Expected behavior**
 Pie chart data displays values + percentages = 
"Label 1:  50 (50%)"
"Label 2:  50 (50%)" 

**Minimal reproduction of the problem with instructions**
Adding the following code gives you percentages of all the values:

this.options{
tooltips: {
        callbacks: {
          label: function (tooltipItem, data) {
            let allData = data.datasets[tooltipItem.datasetIndex].data;
            let tooltipLabel = data.labels[tooltipItem.index];
            let tooltipData = allData[tooltipItem.index];
            let total = 0;
            for (let i in allData) {
              total += allData[i];
            }
            let tooltipPercentage = Math.round((tooltipData / total) * 100);
            return tooltipLabel + ': ' + tooltipData + ' (' + tooltipPercentage + '%)';
          }
        }
      }
}

**What is the motivation / use case for changing the behavior?**
 It is really useful to have a percentage display. It makes your life easier if you need to calculate statistics

**Comment by sudheerj** [comment]
The options property allows you for the customization. Is it not happening?

https://www.primefaces.org/primeng/#/chart

**Comment by tsvetomirivanovv** [comment]
Yes it allows you, but you have to figure it out yourself. the 'tooltips' code that I suggested can be implemented in the component itself and to be turned on and off like other PrimeNg components like for example [asPercentages]=true

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
