### ISSUE TITLE
New component: Splitter

### ISSUE THREAD

**Issue by spyderz42** [primefaces/primeng#4205]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

I checked the roadmap, and this may be what you are calling the splitter, but I would like to be able to create multiple panels (in my case 3) where my users can click on the divider between the panels increase or decrease size on 1 which would effect the others. (Similar appearance to a mail client, 1 panel on the left, 2 panels on the right with the ability to increase the viewing area for any of them).

**Comment by cagataycivici** [comment]
Tracked at #1144
