### ISSUE TITLE
Create PrimengEvent type

### ISSUE THREAD

**Issue by spyderz42** [primefaces/primeng#4206]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
When creating typescript functions on my components to handle events, I have to declare them as type any. It would be nice if I could declare them as type PrimengEvent.. or QueryEvent { original: event, query: string } so I can get the type safety that typescript provides. I know there are more than just QueryEvents, but it would be nice if we could have them all defined and as a child of a PrimengEvent.

**Comment by cagataycivici** [comment]
We'll reconsider if more users demand it, thank you for the feedback.
