### ISSUE TITLE
Does importing from primeng/primeng over specific componets makes any difference when you build with AOT+Tree Shaking

### ISSUE THREAD

**Issue by shanmohan** [primefaces/primeng#4208]
As per the [documentation](https://www.primefaces.org/primeng/#/setup) , Importing specific components over *primeng/primeng* will reduce the file size. i am not sure if this is true in the context of AOT + Tree Shaking. i have tested this with both type of imports and i don't see any size difference.

**Previous Import Statement**

import { DataTableModule, MultiSelectModule, SelectItem } from 'primeng/primeng';

**File Size**
Time: 366129ms
chunk {0} main.b3120847580edd0cbfe0.bundle.js (main) 8.14 MB {2} [initial] [rendered]
chunk {1} styles.8b6c6f216929b068ca54.bundle.css (styles) 657 kB {3} [initial] [rendered]
chunk {2} vendor.22b6c5b2043fa079dd8c.bundle.js (vendor) 1.5 MB [initial] [rendered]
chunk {3} inline.3221e97e02d32c9be6f5.bundle.js (inline) 1.42 kB [entry] [rendered]

**New Import Statement**

import { SelectItem } from 'primeng/components/common/api';
import { DataTableModule } from 'primeng/components/datatable/datatable';
import { MultiSelectModule } from 'primeng/components/multiselect/multiselect';

**File Size**
Time: 370291ms
chunk {0} main.b3120847580edd0cbfe0.bundle.js (main) 8.14 MB {2} [initial] [rendered]
chunk {1} styles.8b6c6f216929b068ca54.bundle.css (styles) 657 kB {3} [initial] [rendered]
chunk {2} vendor.22b6c5b2043fa079dd8c.bundle.js (vendor) 1.5 MB [initial] [rendered]
chunk {3} inline.3221e97e02d32c9be6f5.bundle.js (inline) 1.42 kB [entry] [rendered]

**Build command :** 

ng build --aot --no-sourcemap --prod

PrimeNG Version :  "primeng": "^4.2.2",
Angular Version : 4.4.5

Am i doing anything wrong or anyone else has experienced the same? i just want to be sure the if single import is fine as it keeps code from cluttering from too many import statement if there is no value addition.

**Comment by sudheerj** [comment]
Personally I didn't check these figures anytime. What about the difference in values if you don't use AOT.

**Comment by cagataycivici** [comment]
Use forum for questions please.
