### ISSUE TITLE
label template for MultiSelect

### ISSUE THREAD

**Issue by spnm** [primefaces/primeng#4209]
In MultiSelect we should have an option selectedLabelTemplate that we should define a template like this:
`selectedLabelTemplate = "<span>{0}</span>"`

As it is in:
`selectedItemsLabel {0} items selected`

**Comment by cagataycivici** [comment]
Duplicate of #4209

**Comment by reinpeter** [comment]
@cagataycivici  did you mark this ticket a duplicate of itself and close it?
