### ISSUE TITLE
Calendar model language does not change when locale changes

### ISSUE THREAD

**Issue by scurk1415** [primefaces/primeng#4210]
```
[X] bug report
[ ] feature request
[ ] support request
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/78SgJckNGHiLsfSFhUXj?p=preview

**Current behavior**
Calendar model language does not change when locale changes.

**Expected behavior**
The language should change.

Description:
The language in the input should change when locale changes. The language only changes if we change the date or just focus and blur the input. It doesn't change when the locale changes. I guess the model value should be reinitialized when locale changes.

PS: Only the month names change in the plunker example, because changing the other fields isn't needed to prove my point.

PS2: don't mind the code

* **Angular version:**
Plunker version: 4.2.6
Dev environment version: 4.4.4

* **PrimeNG version:** 
Plunker version: 4.2.0
Dev environment version: 4.2.2

**Comment by PsyGik** [comment]
Any updates on this? Still an issue in ver `5.2.0`

**Comment by akhilbabu** [comment]
anu updates  ?

**Comment by PunkHaz4rd** [comment]
Any update ?

**Comment by achimoraites** [comment]
As a workaround you could do the following:
1) add view children:
` @ViewChildren(Calendar) calendars: Calendar[];`

2 on language change execute the following:
```
    //  this.locale changes depending on laguage selected
      this.locale = this.updateLocale(language);
      this.calendars.forEach(calendar => {
        calendar.locale = {... this.locale};
        calendar.updateInputfield();
      });
```

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.

**Comment by DAVIAMERICO242** [comment]
same 45 years later
