### ISSUE TITLE
Project doesn't run locally

### ISSUE THREAD

**Issue by johnfabian** [primefaces/primeng#4211]
Is there a way for this project to run locally? I pulled down all the files but when doing ng serve none of the css files are found. Your demo site is blocked on gov network so can't access it since it's on some list that isn't secure, probably your web host so I'm trying to run the project locally without success. It compiles and runs but no themes or css files found. Is this made to run with angular cli? 

Also, why are none of the component css files not reference in the components and are all imported into the styles.css file? I tried changing all the css files to scss and fixed all the path issues with fonts and images but still have problems.

**Comment by cagataycivici** [comment]
Please use forum for questions.

**Comment by Brunocroh** [comment]
You need build a sass first

[documentation here](https://github.com/primefaces/primeng/wiki/Building-From-Source)

**Comment by johnfabian** [comment]
ok thank you very much, I was just trying to build with cli but Ill build
the sass first, thanks.
