### ISSUE TITLE
Remove incorrect [ngClass] property on .ui-datatable-scrollable-wrapper

### ISSUE THREAD

**Issue by nate-knight** [primefaces/primeng#4213]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview

**Current behavior**
Non-existing 'max-height' class is getting applied to scrollable tables on the .ui-datatable-scrollable-wrapper node.

**Expected behavior**
.ui-datatable-scrollable-wrapper should not have 'max-height' applied as a class to .ui-datatable-scrollable-wrapper. The style 'max-height' is already being applied to another element, .ui-datatable-scrollable-body, which is correct.

**Minimal reproduction of the problem with instructions**
See 'max-height' class getting applied to .ui-datatable-scrollable-wrapper node:
http://embed.plnkr.co/coNQlXE9NVgonQHf2urP/

**What is the motivation / use case for changing the behavior?**
To clean up superfluous code that may cause confusion.

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X
4.2.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X 
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Fixed via PR
