### ISSUE TITLE
Shift Key selection for Tree

### ISSUE THREAD

**Issue by kimiiic** [primefaces/primeng#4216]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Tree UI multiple selections by using shift key does not work. Multiple selections could be triggered by using CTRL key but not SHIFT key.

I am using Primeface v6.0

**Comment by skormel** [comment]
This feature would be very usefull for our project. Any posibility to include it?

**Comment by StevenSwitten** [comment]
Any news on this?

**Comment by kimiiic** [comment]
Hi All,

I believe this wonderful feature has been added to 6.2 which I am currently using.

No issues with both ctrl and shift selection.

**Comment by StevenSwitten** [comment]
It works with ctrl but not with shift.

https://www.primefaces.org/primeng/#/tree

**Comment by StevenSwitten** [comment]
> Hi All,
> 
> I believe this wonderful feature has been added to 6.2 which I am currently using.
> 
> No issues with both ctrl and shift selection.

How did you get this to work then? It clearly does not work with shift, and there is no code to implement it in tree.ts
