### ISSUE TITLE
Chips input - ability to auto create chip when focus is left

### ISSUE THREAD

**Issue by ryanrupp** [primefaces/primeng#4218]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Currently, the chips component requires either an enter or tab (if enabled) to be performed by the user to create a chip. If they enter some text but forget to hit enter or tab then a chip is not created and the input is not reflected via ngModel.

**Expected behavior**
A configuration option is available so that when the user leaves the focus of the input component it can automatically create a chip from any outstanding input.

**What is the motivation / use case for changing the behavior?**
Easier for the users to use when they're only entering a single value and it may be the first time using the control. Reduces the possibility of unexpected behavior as the control then will effectively behave like an input text box.

**Comment by cagataycivici** [comment]
Fixed via PR, thank you.
