### ISSUE TITLE
DataTable Header alignment

### ISSUE THREAD

**Issue by aabruc** [primefaces/primeng#4219]
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

**Current behavior**
Datatable  with scrollable=true, having issue with header , it is not aligned with columns (new bug, this worked at further versions!).
I'm working with PrimeNg 4.1.2 and I have this issue with nearly all my tables.
First I thought, this is a problem with dynamic columns (the headers of this tables never fit), but unfortunately it occurs at tables with fix columns also.

**Expected behavior**
Headers and columns have the same width.

**Minimal reproduction of the problem with instructions**
Here the definition of my column:
 <p-column *ngFor="let column of tableColumns"
                  field="{{column.field}}"
                  header="{{column.header}}"
                  sortable="true">
  </p-column>
You see: Nothing special with styles. 

**What is the motivation / use case for changing the behavior?**
We really need a fast solution, because it looks confusing.

**Please tell us about your environment:**
Windows10, node.js, npm
Angular version: 4.0 +
PrimeNg version: 4.2.1 (with the 3377 bugfix)
Browser: Chrome, Firefox, IE, Edge

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=info

**Comment by aabruc** [comment]
Thank you for the response.
Yesterday I could solve the issue:

My table is embedded in a p-dialog. The combination of a p-dataTable with scrollable=true and scrollHeight=... and a p-dialog doesn't work well. Both the table scrollbar is miscalculated as well as the header widths..

When I delete the DataTable scrollable and scrollHeight attributes and let the dialog making the scroll work, both the scrollbar and the header widths are calculated right.

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
