### ISSUE TITLE
Multiselect disabled attribute is ignored

### ISSUE THREAD

**Issue by gatapia** [primefaces/primeng#422]
[disabled]="true" on multiselect does not disable the list.

**Comment by IsuruCham** [comment]
yeah. I detected it too

**Comment by IsuruCham** [comment]
@cagataycivici 
Hi, how can I get the latest version (v1.0.0-beta.7-SNAPSHOT) ?
When I change the version of primeng as above and execute "npm update" it gives me an error of 

No compatible version found: primeng@'>=1.0.0-beta.7-SNAPSHOT <2.0.0'
Valid install targets:
["0.1.0","0.2.0","0.3.0","0.4.0","0.5.0","0.6.0","0.7.0","0.8.0","0.8.1","0.8.2","0.9.0","0.9.1
0-beta.4","1.0.0-beta.5","1.0.0-beta.6"]

Thanks.

**Comment by cagataycivici** [comment]
Please get beta8.
