### ISSUE TITLE
Pagination for AutoComplete

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#4220]
Add pagination so that huge number of results can be displayed without performance issues..

**Comment by dydFreeman** [comment]
Any ETA on this? Thanks : )

**Comment by leandroZanatta** [comment]
any updates on this? It's crucial for my business!!!!

**Comment by AlejandroFlorin** [comment]
+1 on request for this feature

**Comment by avbravo** [comment]
For Java server faces?

**Comment by Hawkinks** [comment]
Would be awesome!

**Comment by ben12** [comment]
Could be implemented using infinite scroll.

This "old" refused pull request #6645 can be a starting point ?

**Comment by bhammer88** [comment]
is this still not available?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
