### ISSUE TITLE
How to clean Primeng Schedule (p-schedule)

### ISSUE THREAD

**Issue by Schim57300** [primefaces/primeng#4222]
Good eveving,

Our application ran under Angular 2.1 with prime-ng 1.0.0-beta.17.
Our calendar component (Schedule => p-schedule) used to be initialized with an array of event.

When clicking a "refresh" button, we clean the calendar before getting updated data from the back end:
-  Template: <p-schedule [locale]="fr" [events]="eventList" >
- Typescript: this:eventList = [];
- Typescript: call a service and get list of events
- Typescript: store received events in this.eventList. (for each event received, this.eventList.push(receivedEvent)  )

It worked.

Since we have upgraded to angular 4.3 and primeng 4.1.0, I'm not able to clean the calendar anymore.
Even the command " this:eventList = [];" is executed, the calendar keep its values.
Once the service has been called, each event received is duplicated.

Would you mind helping me please? How can I clean my calendar before getting data from my back end?

Thanks in advance

Eric

**Comment by sudheerj** [comment]
This is not an issue. Please find the more details in forum link.Please continue the discussion in the forum https://forum.primefaces.org/viewtopic.php?f=35&t=52915

**Comment by Schim57300** [comment]
Good afternoon,

It appears I have done properly the upgrade.
The problem is now solved, everything is described in the forum. Hope this will help someone :-D

Thank you very much for your appreciated help

Schim

**Comment by sudheerj** [comment]
Glad to hear it works.
