### ISSUE TITLE
DataTable resizableColumns creates scrollbar when resizing window from higher to lower.

### ISSUE THREAD

**Issue by overflowz** [primefaces/primeng#4223]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/76uqgDdOc36xAQMr1fzQ?p=preview

**Current behavior**

When you add `resizableColumns` property to datatable and you render it on a bigger screen and try to resizing window, it does not fit table like it should, but creates scrollbar to scroll the table instead. But if you render it on small screen and resize window to higher one, it works as expected.

**Expected behavior**

When you resize window, datatable should fit to window, rather than create scrollbar to scroll table (works fine if you open page in a small window and resize to higher one, but not vice-versa).

* **Angular version:** 4.4.1

* **PrimeNG version:** 4.2.2

* **Browser:** Chrome 61.0
 
* **Language:** all

* **Node (for AoT issues):** `node --version` =   8.6.0

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
