### ISSUE TITLE
PickList: hide 'select all' and 'move all up/down' buttons

### ISSUE THREAD

**Issue by pierfreeman** [primefaces/primeng#4225]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
It would be useful to have the chance to customize target and source controls, as well as the middle buttons, for example hiding the 'select/move all' buttons (for my project it would be better not to show to users these buttons)

**Comment by cagataycivici** [comment]
You can use css for the time being until properties are provided, a PR will speed it up for sure.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
