### ISSUE TITLE
DataTable - multiple sort not working with either scrollable tables or lazy tables

### ISSUE THREAD

**Issue by gatapia** [primefaces/primeng#423]
sortMode="multiple" does not work with scrollable="true".

Also does not work with laze="true" (no multipleSortMetadata in the onRefresh method)

**Comment by pserafin** [comment]
confirmed. Same behaviour with Angular2 

        <p-dataTable [value]="loginHistModel" sortMode="multiple" [lazy]="true" (onLazyLoad)="loadLoginHist($event)" [totalRecords]="loginHistLen"
                     [rows]="10" [paginator]="true" [responsive]="true" [pageLinks]="6" [rowsPerPageOptions]="[5,10,20]" >

    loadLoginHist(event: LazyLoadEvent) {
        console.log(event);
    }

/*
filters: Object
first: 0
multiSortMeta: undefined
rows: 10
sortField: "Message"
sortOrder: 1
__proto__: Object
*/
So sortMode always works as single.

**Comment by DevWurm** [comment]
Exactly the same problem for me. Please fix it, it's a realy necessary feature!

**Comment by katrina-engelbrecht** [comment]
I have the same problem. Pls. solve it!!

**Comment by cagataycivici** [comment]
Does it happen with 2.0.2?

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.

**Comment by rebelsyn** [comment]
I've got the latest.  Trying to use multiple sort with lazy load datatable.  Looks like multiSortMeta array only holds one object like so event.multiSortMeta: [{ field: event.sortField, order: event.sortOrder }].

I only ever get the one object.  in the array and it is always the same field and order that I would get in the default sort mode.
