### ISSUE TITLE
Position properties in ConfirmationDialog like in Dialog Module.

### ISSUE THREAD

**Issue by McQuinTrix** [primefaces/primeng#4230]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
There is no positionTop input value

**What is the motivation / use case for changing the behavior?**
To make it uniform to other dialogs

* **Angular version:** 4.3.6

* **PrimeNG version:** 4.2.1

**Comment by yigitfindikli** [comment]
You can use the position property. Please see: https://www.primefaces.org/primeng/showcase/#/confirmdialog
