### ISSUE TITLE
DataTable.exportCSV() bugs/feedback

### ISSUE THREAD

**Issue by gatapia** [primefaces/primeng#424]
- would love a way of setting the filename (currently called 'download' in chrome)
- not working in IE11
- not including the footer
- colspans ignored
- hidden columns should not be exported
- Does not handle data with commas.  Needs to double quote values to support values with comma

**Comment by pantonis** [comment]
+1

**Comment by GraemeSMiller** [comment]
For API comparision Telerik Kendo grid export works well - http://docs.telerik.com/kendo-ui/controls/data-management/grid/excel-export

**Comment by loic49** [comment]
+1

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.

**Comment by soumyagangamwar** [comment]
exportCSV() p-table giving length undefined error
