### ISSUE TITLE
More Unit and E2E Tests

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#4241]
We should add more unit and e2e tests to the suite. @Merve7 will be responsible for the test suite enhancements after 4.3.0. We'll close this issue once we have a significant test coverage.

**Comment by sujithtomy** [comment]
Hello, 
I am writing e2e tests using Protractor for p-dropdown.  How to select the p-dropdown option ? does anyone have idea? Please help... please....

**Comment by cagataycivici** [comment]
We've significant amount of tests now thanks to @yigitfindikli
