### ISSUE TITLE
Use p-dropdown in Paginator rows per page

### ISSUE THREAD

**Issue by MKKnapinski** [primefaces/primeng#4242]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview

**Current behavior**

Different styling of paginator, depending on browser used.

**Expected behavior**

Consistent styling of paginator, despite of used browser.
**Minimal reproduction of the problem with instructions**

Datatable with paginator. Open in IE, Firefox and Chrome

**What is the motivation / use case for changing the behavior?**

Incostitent styles in website.

**Please tell us about your environment:**

Windows 7 64-bit, IntelliJ Ultimate 2017.2.5, Webpack

* **Angular version:** 2.0.X

![dropdown](https://user-images.githubusercontent.com/20905271/31930021-7ece31b4-b89e-11e7-98e2-9e0c62242655.png)

* **PrimeNG version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Much better now!

<img width="1092" alt="screen shot 2017-10-25 at 23 23 31" src="https://user-images.githubusercontent.com/686247/32021261-8bc8b13a-b9db-11e7-89aa-d425a46454ee.png">

**Comment by MKKnapinski** [comment]
Nice, good job :)

**Comment by andresilva5** [comment]
Is it possible to change rows per page in typescript with button example click="changeTo5()"?

function changeTo5(){
    this.paginator.xxxxxxxxxxxxx("5");
}

**Comment by amirensit** [comment]
@andresilva5, Did you get a solution to your problem ?
