### ISSUE TITLE
Badges for menu components

### ISSUE THREAD

**Issue by vangalder** [primefaces/primeng#4245]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

FEATURE REQUEST: I'm tasked with coming up with badge functionality for `p-menubar`.

1. Are there currently any plans to add that functionality in the future?
2. Is there a way I can pass an identifier in for a top-level menu item?

Love this library, thanks!

tvg

**Comment by cagataycivici** [comment]
We'll add badges to all menus so expanding the issue.

**Comment by jcgil69** [comment]
Do you have any plan to include this in version 6?

**Comment by JanRAndersson** [comment]
I'm using PrimeNg 7. 
I can see that there's a property "badge" in the interface "MenuItem".
Is the functionality implemented in version 7?

**Comment by twohappy** [comment]
@JanRAndersson seems 'badge' & 'badgeStyleClass' are used only in premium templates..

**Comment by Cito** [comment]
Unfortunately, these properties are ignored in the PrimeNG MenuItem template. It would be easy and very helpful to add something like `<span class="ui-menuitem-badge" *ngIf="item.badge" [ngClass]="item.badgeStyleClass">{{item.badge}}</span>` to the template.

**Comment by CD-UNCC** [comment]
Whats going on with this? On 11.0 and the badge stuff is still ignored

**Comment by bgl3317** [comment]
Is there a reason this request is being ignored? Why have badge at all in the documented properties of MenuItem if it's simply unusable? It's confusing and misleading.

**Comment by bernardosimonetto** [comment]
I completely agree with you, it's misleading.

Referring to https://github.com/primefaces/primeng/commit/2f8b865cf7c44af151285e60415817c980c7fce2 it seems to be available only for "premium templates"

**Comment by Donnerstagnacht** [comment]
Is there a news on this topic?

**Comment by cetincakiroglu** [comment]
Hi,

We've added the badge property in menuItem API to create badge and badgeStyleClass for styling.
