### ISSUE TITLE
Datatable scrollbars are not shown when too many columns exist on datatable

### ISSUE THREAD

**Issue by pantonis** [primefaces/primeng#4247]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/bbMoudhxbxCZNJxUFUs9?p=preview

**Current behavior**
When there are many columns and don't fit in the screen the horizontal scrollbar is not visible

**Expected behavior**
Horizontal scroll bar should be visible if columns don't fit in the screen

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
This is a critical bug as this is standard functionality of a datatable. 

**Please tell us about your environment:**

* **Angular version:** 2.0.X
Latest Angular 

* **PrimeNG version:** 2.0.X
4.2.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All browsers
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
You need to define widths for columns like [style]="{width: '100px'}" on DataTable to show up the horizontal scrollbar. Or you can use percentages for columns and use scrollWidth on DataTable.

**Comment by pantonis** [comment]
No I shouldn't width should be set to auto. If I set this to auto text overlaps the text of the column next to it. This is a bug.

**Comment by atomsbaza** [comment]
I also have this problem too

**Comment by tpmehta96** [comment]
I am using the latest version of Google chrome browser, Angular and PrimeNG, but this issue still persists.
Using scrollHeight works well, but using scrollWidth does not work with scrollable = true.
Please reopen the ticket.
