### ISSUE TITLE
AutoComplete Panel doesn't always hide

### ISSUE THREAD

**Issue by ericrovtar** [primefaces/primeng#4248]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview

**Current behavior**

Inconsistently, there are times where the `ui-autocomplete-panel` div doesn't set its `display` property to `none` when clicking an option. This results in the the border being displayed as pictured.

![screen shot 2017-10-24 at 11 29 18 am](https://user-images.githubusercontent.com/3474545/31952818-85a08396-b8af-11e7-9e1c-d8d30506f05f.png)

**Expected behavior**

The `div` should always set its `display` property to `none` whenever the user select an option.

**Minimal reproduction of the problem with instructions**

1) Click dropdown arrow of AutoComplete to view suggestions
2) Click on a suggestion
3) Usually happens only with the first selection, but not consistently.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.4.4

* **PrimeNG version:** 4.2.2

* **Browser:** [all ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
How to replicate?

**Comment by Abbraxar** [comment]
@ericrovtar the plunker you sent is the basic one. Did you forgot to fork and save yours ?

**Comment by cagataycivici** [comment]
Anyway I assume this is related to

https://github.com/primefaces/primeng/issues/4162
