### ISSUE TITLE
TabView with confirmDialog: how to cancel onChange tab on reject

### ISSUE THREAD

**Issue by pierfreeman** [primefaces/primeng#4249]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
Hi, for my TabView I'm using a confirmDialog which is triggered on the 'onChange' event. If the user rejects, the change must be canceled and the active tab must remain the same as before.

Currently I tried two ways:
- using activeIndex property of TabView, saving locally the current view index before the change and restore it if the user rejects,
- using e.preventDefault() for cancelling the full change event

but none of them is working.

How can I achieve this?

**Comment by cagataycivici** [comment]
Please use support forum for questions, thank you;

https://forum.primefaces.org/viewforum.php?f=35&sid=41e26b0f408179932c7798fd3c982a57
