### ISSUE TITLE
DataTable performance in IE

### ISSUE THREAD

**Issue by gatapia** [primefaces/primeng#425]
I just started testing IE and performance of the datatable is really bad.  This is in IE11, I have not had the courage to test older IEs yet.

**Comment by cagataycivici** [comment]
I think it is related to Angular, I'm not sure how we can improve it. Which part is slow? Rendering of data?

**Comment by gatapia** [comment]
yes rendering is slow.  displaying large tables (> 400 rows or so) is basically unusable (using scrollable tables).  A quick profile reveals nothing only es6-shim, angular2-polyfills, etc.  The regular useless stacktraces.

**Comment by gatapia** [comment]
This is an angular 2 issue.  For a quick fix (IE11 only) use core.js instead of es6-shim.  From the [angular 2 issue](https://github.com/angular/angular/issues/8112) a work around is:

_1. npm i core-js --save
2. replace references to node_modules/es6-shim/es6-shims.min.js with node_modules/core-js/client/core.min.js ._
