### ISSUE TITLE
Expand rowgroups by clicking anywhere in the subheader

### ISSUE THREAD

**Issue by Aldrixan** [primefaces/primeng#4250]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/kJ1D5saQkzbYS9fs0KtJ?p=preview

**Current behavior**

I would like to be able to have logic to expand a rowgroup by clicking anywhere in the subheader similar to how you can with the individual rows by adding the following code

`(onRowClick)='dt.toggleRow($event.data)'`

In the plunkr above, in order to expand the row group, you must click the expand icon on the left, but once that is expanded, you can expand any single row by clicking anywhere in the row.  I would like the same ability on the group headers.

**Expected behavior**

I would like something along the lines of 

`(onRowGroupClick)='dt.toggleRowGroup($event.data)'`

I have currently accomplished this by modifying the following function of the datatable.js file along with the corresponding call to this function in the template

`DataTable.prototype.onRowGroupClick = function (event, row)
    {
        if (!this.sortableRowGroup && !this.rowGroupToggleClick)
        {
            this.toggleRowGroup(event, row);
        }
...
    }`

The current modification is restricted to non-sortable group headers.  If this could be accomplished in another way that doesn't include this restriction that would be preferred but I do not currently have that need.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

To be able to expand/collapse row groups without being tied strictly to the expander icon

**Please tell us about your environment:**

Windows, IIS

* **Angular version:** 4.0.0

* **PrimeNG version:** 4.2.2

* **Browser:** [all]

* **Language:** [all]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.

**Comment by milocosmopolitan** [comment]
With recent turbo table, this could be done on templating. 

if each rowGroupMetadata[rowGroup] is object that contains toggle status like
`{ index: 0, size: 1, toggle: false }`

template can hide `<tr>` with
`<tr [hidden]="!rowGroupMetadata[rowData[rowGroupKey]].toggle">`

then all you need is click event handler which will update the toggle status of the rowGroup

```javascript
toggleRowGroup(rowGroup) {
    this.rowGroupMetadata[rowGroup].toggle = !this.rowGroupMetadata[rowGroup].toggle
}
```


**Component Template**
```html
.
.
.
<ng-template pTemplate="body" let-rowData let-columns="columns" let-rowIndex="rowIndex">
  <tr class="ui-widget-header grid-row-group" *ngIf="rowGroupMetadata[rowData[rowGroupKey]].index === rowIndex" 
 (click)="toggleRowGroup(rowData[rowGroupKey])">
    <td [attr.colspan]="cols.length">
      <div>
        <span style="font-weight:bold">{{rowData[rowGroupKey]}}</span>
        <span>{{rowGroupMetadata[rowData[rowGroupKey]].size}} items</span>
      </div>
    </td>
    <td>{{rowGroupMetadata[rowData[rowGroupKey]].index}} | {{rowIndex}}</td>
  </tr>
  <tr [hidden]="!rowGroupMetadata[rowData[rowGroupKey]].toggle">
    <td *ngFor="let col of columns">
      {{rowData[col.field]}}
    </td>
    <td>{{rowIndex}}</td>
  </tr>
</ng-template>
.
.
.
```

**Component TS file**
```javascript
  .
  .
  .
  rowGroupKey = 'facility_type';

  cols = [
    { field: 'col1', header: 'Column 1' },
    { field: 'col2', header: 'Column 2' },
    { field: 'col3', header: 'Column 3' },
    { field: 'col4', header: 'Column 4' },
    { field: 'col5', header: 'Column 5' }
  ];
 
  toggleRowGroup(rowGroup) {
    this.rowGroupMetadata[rowGroup].toggle = !this.rowGroupMetadata[rowGroup].toggle
  }

  updateRowGroupMetaData(data) {

    // Todo: make this function part of GridService;
    this.rowGroupMetadata = {};

    if (!this.rowGroupKey) {
      throw new Error('Must have rowGroupKey')
    }
    if (data) {
      for (let i = 0; i < data.length; i++) {
        const rowData = data[i];
        const rowGroup = rowData[this.rowGroupKey];
        if (i === 0) {
          this.rowGroupMetadata[rowGroup] = { index: 0, size: 1, toggle: false };
        } else {
          const previousRowData = data[i - 1];
          const previousRowGroup = previousRowData[this.rowGroupKey];
          if (rowGroup === previousRowGroup) {
            this.rowGroupMetadata[rowGroup].size++;
          } else {
            this.rowGroupMetadata[rowGroup] = { index: i, size: 1, toggle: false };
          }
        }
      }
    }
  }
```
