### ISSUE TITLE
ui-btn displayed as default text when there is no label set on buttons.

### ISSUE THREAD

**Issue by BustyLoli-Chan** [primefaces/primeng#4252]
https://github.com/primefaces/primeng/blob/d06afd823cbac923b5cf3042b33efa64ba4ba53e/src/app/components/button/button.ts#L34

It would be nice to have the option to have an empty label, instead of all buttons just defaulting to have the text `ui-btn` when `btn.label` is falsey. I can think of a lot of situations in which an end user would prefer to just have a button that's _just empty_. I can think of almost **0** situations where the end user would prefer to have their button say `ui-btn`.

Edit: it is known by issue https://github.com/primefaces/primeng/issues/1657 that you can hide the text by adding 
```
.ui-button-text-only .ui-button-text{
    display: none !important;
}
```
but I'd be lying if I said this doesn't seem dumb and like it shouldn't even be necessary or an issue to begin with.

Edit edit: I have opened a pull request for this issue here.
https://github.com/primefaces/primeng/pull/4254

**Comment by cagataycivici** [comment]
I can't replicate the issue to begin with, create a plunkr please.

**Comment by BustyLoli-Chan** [comment]
http://plnkr.co/edit/dSx8dBkXUQJXWtZHIOvc?p=preview
Ok done.
