### ISSUE TITLE
No Scope attribute on datatable headers

### ISSUE THREAD

**Issue by joechrisman** [primefaces/primeng#4253]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
There is no way to set the scope on the headers

**Expected behavior**
There should be a way to set the scope on TH tags

* **Angular version:** 2.0.X
4.3.5

* **PrimeNG version:** 2.0.X
4.2.2

* **Browser:** 
Chrome 61
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.2

**Comment by cagataycivici** [comment]
Merged PR

**Comment by cagataycivici** [comment]
Related https://github.com/primefaces/primeng/issues/4255
