### ISSUE TITLE
Slider onSlideEnd event does not trigger due to ngZone.runOutsideAngular()

### ISSUE THREAD

**Issue by RandomPrecision1** [primefaces/primeng#4257]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**

http://plnkr.co/edit/owUi6X4tMR4bpxZTAXkH

I actually had a typo when I first submitted the plunker - I'll investigate it a little more to see if I can make it more simply recreate the situation I'm seeing in a larger app.

In the meantime, in my plunker app there are three sliders. We're listening to:

* The onChange event of the 1st
* The onSlideEnd event of the 2nd
* The onSlideEnd event of the 3rd (but in an NgZone.run() block to force it to Angular context)

If you drag each of the sliders to change the value but release the mouse button outside of the slider control, only the 1st and 3rd will correctly update the value on-screen. In my plunker, the 2nd will work if you release the mouse button on the control - in a larger app I've been working with, the value is not updated even if the button is released on the control.

Reverting the version of primeng back to 4.1.2 in systemjs.config.js makes the 2nd and 3rd sliders behave identically.

**Current behavior**
As of primeng 4.2.0, the Slider component is no longer always emitting events from onSlideEnd. Note that in the Slider component's bindDragListeners(), most code runs outside of an Angular context. The event for onChange re-enters an Angular context, but this does not happen for onSlideEnd. Therefore, event listeners do not properly fire.

Additional debugging steps are listed above in the description of the attached plunker.

**Expected behavior**
I expect onSlideEnd to always trigger event handlers as it did pre-4.2.0.

**Minimal reproduction of the problem with instructions**
I've created a [plunker here](http://plnkr.co/edit/owUi6X4tMR4bpxZTAXkH) demonstrating the behavior. Event handling for onChange and onSlideEnd are implemented identically and should update the counters in the app.component. However, onSlideEnd does not always cause the value to be updated.

**What is the motivation / use case for changing the behavior?**
We (and surely others) use this event as a more user-friendly way to trigger events than on every onChange() event.

I made a fork of the repo and made this change - I submitted a pull request [here](https://github.com/primefaces/primeng/pull/4258) to add an ngZone.run() around the event to bring it back into Angular.

**Please tell us about your environment:** n/a

* **Angular version:** 4+

* **PrimeNG version:** 4.2.2

* **Browser:** all
 
* **Language:** TS

**Comment by cagataycivici** [comment]
Fixed via PR #4258
