### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Elanor-L** [primefaces/primeng#426]
Adding a parameter to choose how many years should be displayed in the Year Navigator

**Comment by cagataycivici** [comment]
There is already yearRange.

**Comment by Elanor-L** [comment]
When I wrote the message, there wasn't. But thanks anyway !

**Comment by cagataycivici** [comment]
I know, we're reviewing all issues now and updating them with current stage of codebase.

**Comment by mcbroh** [comment]
Hi, 
Wondering if there are plans to support beforeClose event on dynamic dialog, something similar to angular material dialog beforeClose event, or maybe i am just missing something?
