### ISSUE TITLE
Datatable GlobalFilter OnPush support

### ISSUE THREAD

**Issue by patriknil90** [primefaces/primeng#4262]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**

Change in global filter doesn't get detected on input when implementing changeDetectionStrategy.onPush (it's lagging behind).

**Expected behavior**

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/9ikDgEi4mSXWjMrxMiub?p=preview

Write "Hako" or "Patrikk" and see that the datatable doesn't get filtered correctly.

**What is the motivation / use case for changing the behavior?**

Should support OnPush strategy.

**Please tell us about your environment:**

* **Angular version:** 4.2.6

* **PrimeNG version:** 4.2.2

* **Browser:** Chrome

**Comment by patriknil90** [comment]
I read the following in [this blogpost](https://www.primefaces.org/primeng-5-0-2-released/):

> Roadmap
> Our current focus is on adding more tests to the suite and speeding up the DataTable performance which are our tasks for the next sprint.

As OnPush strategy is fundamental for optimal performance, would it be possible to see this fix (and if you have other open issues regarding datatable combined with onpush) in the near future?

As PrimeNg delivers the most advanced (and best? ;) ) datatable component for angular out there (as I know of), I am sure that there are more than me who wants to list large data sets with OnPush strategy to speed things up and still be able to use the global filter!

**Comment by mmlitvin** [comment]
Strongly Agree!

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.

**Comment by kwakiutlCS** [comment]
While the p-dataTable fix works, the p-table also has this problem.
With version 5.2.3
https://plnkr.co/edit/wA4Qa4a3EjWUxxX1SP78?p=preview
