### ISSUE TITLE
p-dialog footer isn't at the bottom when [height] is set

### ISSUE THREAD

**Issue by fxmfr** [primefaces/primeng#4266]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
[http://plnkr.co/edit/C1e9bXqC9WYwhQr8TJw6?p=preview](http://plnkr.co/edit/C1e9bXqC9WYwhQr8TJw6?p=preview)

**Current behavior**
If `[height]` is specified for a `<p-dialog>`, `<p-footer>` is not positioned at the bottom of the dialog.

**Expected behavior**
Expecting a footer at the bottom.

**Minimal reproduction of the problem with instructions**
In plunkr above, click the button. Footer is shown under content instead of dialog's bottom.

**What is the motivation / use case for changing the behavior?**
A footer is commonly expected at the bottom of something.

**Please tell us about your environment:**
Windows 10

* **Angular version:**
4.4.4

* **PrimeNG version:**
4.2.2

* **Browser:**
Chrome 62

**Comment by cagataycivici** [comment]
Use contentStyle instead like [contentStyle]="{height: '200px'}"

**Comment by ziXet** [comment]
@cagataycivici setting contentStyle did not work for me. primeng 5.2.5

**Comment by dannygoncalves** [comment]
@cagataycivici this issue seems to persist, (sorry about necroing an old thread) but I just tried both approaches with no luck, am I doing something wrong?
