### ISSUE TITLE
Tree: Cannot read property 'dragStart$' of null [Plnkr included]

### ISSUE THREAD

**Issue by gojas** [primefaces/primeng#4267]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/CH1xKN?p=preview

**Current behavior**
ERROR TypeError: Cannot read property 'dragStart$' of null

**Expected behavior**
DragDropService should exist

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/CH1xKN?p=preview

* **Angular version:** 4.2.6

* **PrimeNG version:** @4.2.2

* **Browser:** [Chrome, Firefox ]
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
I think you need to inject a TreeDragDropService in your component.

**Comment by gojas** [comment]
Thanks for quick response. :+1: 

But this IS example from doc itself, Plnkr is the same...

**Comment by gojas** [comment]
Thanks for quick response, i totally forgot to import it :+1:

**Comment by tarockx** [comment]
I know this is an old issue, but I'm writing here just to point out that I didn't find this anywhere in the current (v17) `p-tree` documentation, so I imagine there might be people that still encounter this issue.

To be clear, you must add `TreeDragDropService` to your array of providers (either in the component or in the app module) to avoid this issue. You do not need to actually inject an instance of it in the component itself (which is what was making me confused about the previous answers)
