### ISSUE TITLE
Cell navigation fails when a column is hidden

### ISSUE THREAD

**Issue by el7lme** [primefaces/primeng#4270]
If datatable have hidden columns,  and pressing Tab. focus will stuck and lost.
Also is there any way to use "Enter Key" instead or with "Tab Key"

Thanks

**Comment by cagataycivici** [comment]
Is this an editable datatable?

**Comment by el7lme** [comment]
Yes, editable datatable

**Comment by cagataycivici** [comment]
How do you hide it, with visible prop?

**Comment by el7lme** [comment]
I used [hidden]="HeaderACCType!=2"  as ("HeaderACCType!=2") internal condition

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.

**Comment by el7lme** [comment]
@cagataycivici 
I tried p-table, still the problem. when hidden column between some columns, Tab lost.
I used  "<td pEditableColumn [hidden]="HeaderACCType!=2">"
