### ISSUE TITLE
p-radiobutton and p-checkbox Icon Style

### ISSUE THREAD

**Issue by kboyd31** [primefaces/primeng#4271]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Feature Descripton**
I would like to ask for the ability to change the icon for radio and check boxes. Currently they are hard coded to use font awesome icons and a very specific one. It would be nice if we could overwrite this with our own icon if we wanted to help make our own themes a bit more flexible. As it is, I am unable to use this component because the styling is much different than our existing inputs.

**What is the motivation / use case for changing the behavior?**
More flexible styling of the Radio and Check box components. 

* **Angular version:** 2.0.X
4.0.0

* **PrimeNG version:** 2.0.X
4.2.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
