### ISSUE TITLE
Cannot upload files in succession in IE 11

### ISSUE THREAD

**Issue by chinaowl** [primefaces/primeng#4273]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
In IE 11, I can successfully upload one file. However, if I try to choose a second file, it will not show up in the box and the upload button is disabled. The only way I can continue uploading is if I click the choose button again and select a _different_ file from the one I just tried (and failed) to upload. I recorded a video of this behavior: https://streamable.com/cahkm 

**Expected behavior**
Just like how it behaves in Chrome, I should be able to upload one file after another.

**Minimal reproduction of the problem with instructions**
See [the PrimeNG demo page](https://www.primefaces.org/primeng/#/fileupload).

**Please tell us about your environment:**
* **Angular version:** 4.4.5
* **PrimeNG version:** 4.2.2
* **Browser:** IE 11
* **Operating system:** Windows 10

**Comment by yigitfindikli** [comment]
Unable to replicate with latest PrimeNG, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
