### ISSUE TITLE
pTooltip adds multiple elements on Body element

### ISSUE THREAD

**Issue by hardikBharadava** [primefaces/primeng#4275]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

when hover on element pTooltip is shown on Body element, moving cursor on that tooltip Element, it is showing many elements on Body and not hiding previous one, when on focus out of the element.

**Expected behavior**

It should add only single element for single tooltip, and must hide on mouse/focus leave

**Minimal reproduction of the problem with instructions**
having an Array of anchor tag, generating it using `ngFor` and only title is applying dynamic, all other tooltip code is same for all. [Check Video Here](https://www.screencast.com/t/Ufe6Hh83J)

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** ^4.3.X
* **angular/cli:** 1.4.7
* **node:** 6.11.0
* **os:** win32 x64
* **angular/animations:** 4.3.6
* **angular/common:** 4.4.3
* **angular/compiler:** 4.4.3
* **angular/core:** 4.4.3
* **angular/forms:** 4.4.3
* **angular/http:** 4.4.3
* **angular/platform-browser:** 4.4.3
* **angular/platform-browser-dynamic:** 4.4.3
* **angular/router:** 4.4.3
* **angular/cli:** 1.4.7
* **angular/compiler-cli:** 4.3.6
* **angular/language-service:** 4.3.6
* **typescript:** 2.3.4
* **PrimeNG version:** 4.2.2

* **Browser:** [ Chrome Version 61.0.3163.100 (Official Build) (64-bit) ]

 
* **Language:** [TypeScript 2.3.4 ]

* **Node (for AoT issues):** `node --version` =   6.11.0

**Comment by marcbruederlin** [comment]
PR #4690 fixes this issue.

**Comment by Merve7** [comment]
Changed tooltip implementation and the issue is fixed. Please try with the new version.
