### ISSUE TITLE
Able to select Min Max dates when the field is editable by typing in the input field

### ISSUE THREAD

**Issue by mahesh5b5** [primefaces/primeng#4276]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

This is to report that We are able to select Min Max dates when the field is editable. Please find the screenshot.

Steps to reproduce the Issue-

1.  Import calendar module from primeng.
2. Remove "readonly" from the calendar and make the field is editable.
3. Use min-max attributes to disable past and future calendar dates.
4. Try entering past or future dates.

Observation/ Expectation- 
**Even though we type future date or past date it should not let the user to select or navigate to the month typed.**

**Attached Screenshot for checking this issue.**

<img width="259" alt="min_date issue" src="https://user-images.githubusercontent.com/5457009/32047659-4ace2b40-ba64-11e7-80b9-f16803ef3f96.PNG">

**Comment by mahesh5b5** [comment]
**Please mark it as an importan and urgent fix** 👍

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=info

**Comment by mahesh5b5** [comment]
@cagataycivici  pls add CalendarModule and add p-calendar to the dom. Give min max dates. Remove readonly on the input tag. try entering date greater than your max date manually in the input box. You can observe the selection of the disabled date. 

Please check the screenshot which is taken from primeNg website only.

**Comment by mahesh5b5** [comment]
Please reopen the issue.
