### ISSUE TITLE
InputText floating label content overlap

### ISSUE THREAD

**Issue by bsh314** [primefaces/primeng#4277]
```
[x] bug report
[ ] feature request
[ ] support reques
```
**Current behavior**
Floating label of InputText is overlaping on input content

**Expected behavior**
Floating label of InputText must stay raized while input has content

**Minimal reproduction of the problem with instructions**
Current state of PrimeNg documentation has this problem
[PrimeNg InputText Documentation](https://www.primefaces.org/primeng/#/inputtext)

**What is the motivation / use case for changing the behavior?**
This awesome feature is required for Material style themes

* **Angular version:** 4.4.X

* **PrimeNG version:** 4.2.X
 
* **Language:** TypeScript 2.5.X, ES6

**Comment by bsh314** [comment]
Cache issues.....

**Comment by Sandesh-Solabannavar** [comment]
I'm Facing this issue.
![image](https://user-images.githubusercontent.com/23529429/35605343-49bb9a5c-066e-11e8-8b79-511b178b9281.png)

**Comment by Sljux** [comment]
I'm having the same issues with primeng@5.2.7 and angular@5.2.9
The class `ui-state-filled` is not added to the input element, and the label overlaps the text on blur

**Comment by intergleam** [comment]
why is it closed? I have the same issue

**Comment by intergleam** [comment]
@bsh314 no it's not "Cache issues....."

**Comment by intergleam** [comment]
forgot to import `InputTextModule`

**Comment by chauhanvipul87** [comment]
I had the same problem, Just imported the InputTextModule and done.

**Comment by kishorekcs** [comment]
I have a input text box with border, wish to add label on the border-top-style. (Primeng p-float-label goes up on focus. Wish to fix it up by default)
Now I'm getting a strikethrough type of look. How do I over come this?

**Comment by fontenele** [comment]
just invert input with label order... put first input then label after input inside p-floatLabel
