### ISSUE TITLE
problem with update from 4.2.2 to 4.3.0

### ISSUE THREAD

**Issue by sourdoth** [primefaces/primeng#4278]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Hi, i update from 4.2.2 to 4.3.0-RC1 and i get this error to compile:

ERROR in C:/quickstart/web/node_modules/primeng/primeng.d.ts (54,15): Cannot find module './components/progressbar/progressspinner'.

ERROR in C:/quickstart/web/src/app/app.component.ts (125,13): Cannot invoke an expression whose type lacks a call signature. Type '((...items: MenuItem[]) => number) | ((...items: MenuItem[][]) => number)' has no compatible call signatures.
C:/quickstart/web/src/app/app.component.ts (128,13): Cannot invoke an expression whose type lacks a call signature. Type '((...items: MenuItem[]) => number) | ((...items: MenuItem[][]) => number)' has no compatible call signatures.

ERROR in C:/quickstart/web/src/app/app.component.ts (125,13): Cannot invoke an expression whose type lacks a call signature. Type '((...items: MenuItem[]) => number) | ((...items: MenuItem[][]) => number)' has no compatible call signatures.
C:/quickstart/web/src/app/app.component.ts (128,13): Cannot invoke an expression whose type lacks a call signature. Type '((...items: MenuItem[]) => number) | ((...items: MenuItem[][]) => number)' has no compatible call signatures.

can you help me please, thanks :)

* **Angular version:** 4.X.X

* **PrimeNG version:** 4.3.0-RC1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by upstreamosGH** [comment]
The following row in ../node_modules/primeng/primeng.d.ts
`export * from './components/progressbar/progressspinner';`
should be
`export * from './components/progressspinner/progressspinner';`
I manually change it, and it works. I'll wait the fix in the next release...

**Comment by cagataycivici** [comment]
Try **4.3.0-rc.2** please.

**Comment by RoseReatherford** [comment]
@cagataycivici I'm still having this exact issue in 4.3.0-rc.2. I noted the file was changed as direct by @upstreamosGH, but still cannot build.
