### ISSUE TITLE
DataScroller does not update automatically when data change (even with spread operator)

### ISSUE THREAD

**Issue by pierfreeman** [primefaces/primeng#4279]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
As the title suggests, DataScroller is not updated automatically when the underlyining data changes, for example when adding/removing records.
I tried both with .push() and methods that triggers the update, for instance slice() and the spread operator, but none of them is working.

Since DataTable and DataList work well with this methods, I expect that also DataScroller work like this...also because that the docs say that it **should** work.

**Comment by cagataycivici** [comment]
Unable to replicate, the records showed up in my case, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=info

**Comment by mlangwell** [comment]
I am having the exact same problem that is listed above. I populate the data source with an initial Array<any> and then after I populate it I do some filtering behind the scene based on user selection. I have used splice, slice, spread operator, immutable true/false, and I even tried creating a whole new Array<object> and assigning my existing object to it. None of this worked. This would be heck of a lot easier if you guys just made the datascroller work with pipes. I have wasted a lot time trying to get this to work.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
