### ISSUE TITLE
Dialog mask is not removed on destroy.

### ISSUE THREAD

**Issue by TheSilvermind** [primefaces/primeng#428]
Version; "primeng": "1.0.0-beta.6"

It seems when Dialog.prototype.ngOnDestroy is called that the mask is not removed from the dom.
I suggest to change this code at line 183:
`Dialog.prototype.ngOnDestroy = function () {`
`    // new`
`    this.disableModality();`
`    // old`
`    // this.mask = null;`
`    ...`
`}`

**Comment by Chadley08** [comment]
I am also having this issue.

**Comment by TheSilvermind** [comment]
@Chadley08
You can change line 184 in dialog.js from
`this.mask = null;`
to
`if (this.disableModality) {`
`    this.disableModality();`
`}

**Comment by Chadley08** [comment]
Confirmed this fix as working for me.

**Comment by cagataycivici** [comment]
Fix checked in, thank you.
