### ISSUE TITLE
Radiobutton inside Multiselect

### ISSUE THREAD

**Issue by GuzzoLM** [primefaces/primeng#4282]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

http://plnkr.co/edit/uo5GNgeigzM8KgxXmvBV?p=preview

I'm trying to implement a radiobutton inside a multiselect dropdown. Made a working example in the plunker link above. But when I try to reproduce in my application it didn't worked fine.

My problem is that the binding with ngModel is not working properly. When I change the slection of the radiobutton, the ngModel changes acordinly. But if I start the application with a pre-selected value, the radiobutton does not show it. However, if I change the value of the ngModel with some other function(by clicking some button, for example) the radiobutton starts to show the selection.

My workarownd was to create a function that is fired when you first click the multiselect. This function changes the value of the ngModel to a random string and after 1ms timeout changes the ngModel to its original value.

You can see the workaround below:

```
private multiSelectRadioTicker() {
      if (this._firstTimeRadioButton) {
        this._bufferRadioButton = this._carResponsible;
        this._carResponsible= 'XXX';
        setTimeout(() => { this.multiSelectRadioRestore(); }, 1);
        this._firstTimeRadioButton = false;
      }
}
private multiSelectRadioRestore() {
    this._carResponsible= this._bufferRadioButton;
}
```
```
<p-multiSelect [options]="myCarsOptions"
                       [(ngModel)]="_myCars"
                       [filter]="true"
                       [maxSelectedLabels]="1"
                       selectedItemsLabel="{0} Selected"
                       defaultLabel="None"
                       [style]="{'width':'100%'}"
                       (onChange)="changeCarSelection()"
                       (click)="multiSelectRadioTicker()">
          <ng-template let-centro let-i="index" pTemplate="item">
            <p-radioButton name="groupCar" value="{{car.value}}" [(ngModel)]="_carResponsible"></p-radioButton>
            <div style="font-size:14px;float:right;margin-top:4px">{{car.label}}</div>
          </ng-template>
 </p-multiSelect>
```

Hope someone can help me find out what is wrong with my ngModel binding. Is it possible to be an error with the p-radiobutton?

Also I checked the feature request option too, in case you find this tool interesting.

Best regards. 

**Minimal reproduction of the problem with instructions**
The ngModel value is received by an Observable from the backend of my application. The tool can be found in the plunker. The plunker actually works, the problem is only when I try to use in my application with the Observable.

**Please tell us about your environment:**

* **ASP.NET Standard application serving Angular App, using Visual Studio 2017, IIS

* **PrimeNG version:** 4.2.1

* **Browser:** [Chrome | Firefox ]
 
* **Language:** [TypeScript 2.2]

**Comment by cagataycivici** [comment]
Please use forum for support requests, thank you.

https://forum.primefaces.org/viewforum.php?f=35
