### ISSUE TITLE
Listbox is not working

### ISSUE THREAD

**Issue by s13571** [primefaces/primeng#4283]
**I'm submitting a ...**
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://embed.plnkr.co/nTbkAG5fdDvr8zUyINbW/

**Current behavior**
Listbox is not working with array of objects, does not display data and header. All you can see is filter box and empty list of objects. With SelectItem[] it displays data but still doesn't display header.

**Expected behavior**
To work as in Prime Ng example

**Minimal reproduction of the problem with instructions**
http://embed.plnkr.co/nTbkAG5fdDvr8zUyINbW/

* **Angular version:** 4.2.4

* **PrimeNG version:** 4.2.2

**Comment by cagataycivici** [comment]
You need 4.3.0-RC1 at least.
