### ISSUE TITLE
p-datatable: Unexpected behaviour when sorting on fields with identical content

### ISSUE THREAD

**Issue by Aarkon** [primefaces/primeng#4284]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**No Plunker**
I encounter this in a non-open source-project, so I won't publicly display our code because I'm not entirely sure if I am allowed to. Still, I don't want to keep my observations to myself.

**Current behavior**
Everytime I sort a datatable on a field where all fields of the column have identical content, the first two rows get swapped.

e.g.:

| First Column | Second Column |
| ------------- | ------------- |
| A  | C |
| B | C |
| E | F |

Clicking on "Second Column" will make the rows beginning with "A" and "B" switch places and continue to do so on every click.

**Expected behavior**
After sorting once, further clicks should not change the order of the rows anymore.

**Please tell us about your environment:**

* **Angular version:** 4.4.6

* **PrimeNG version:** 4.2.1 - 4.3.0-rc1

* **Browser:** [all]

* **Language:** [ TypeScript 2.5.3 | ES6/7 ]

* **Node (for AoT issues):** `node --version` =   8.1.2

**Comment by cagataycivici** [comment]
On which browsers does this happen, there is a known chrome thing related to this.

**Comment by Aarkon** [comment]
Holy moly, you're right, this does not happen on, e.g., Firefox. I really did not expect this to be browser dependent.

**Comment by Yonet** [comment]
Similar problem happening only on Chrome 62. Is there a fix for this?
