### ISSUE TITLE
Multiselect - Select only when checkbox is clicked

### ISSUE THREAD

**Issue by GuzzoLM** [primefaces/primeng#4285]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
In a multiselect, whenever the user clicks an option, the option is selected.

**Expected behavior**
It could be useful if there was a wayto only enable option select if the user clicks the checkbox.

**Comment by sudheerj** [comment]
Can you please elaborate about expected behavior. Do you want to select through checkbox only(not through label)?

**Comment by GuzzoLM** [comment]
@sudheerj yes, I want an option to disable selecting through label.

**Comment by kvabhishek** [comment]
I am also looking for similar functionality in the Datatable. Did you find a solution? Please help.

**Comment by cagataycivici** [comment]
We'll reconsider if more users demand this behavior.
