### ISSUE TITLE
p-calendar Hour does not display correctly when the hour is set to 12 for 12 hour time

### ISSUE THREAD

**Issue by nickcausey** [primefaces/primeng#4289]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Current behavior
If you create a Calendar with hourFormat set to '12' and currentHour is set to 12, then toggle the AM/PM stepper, the input box will display the hour as 12 when set to PM, and 00 when set to AM.

Expected behavior
The AM/PM stepper should not affect the display of the hour when 12 hour time is selected.
The time should display as 12:XX AM when the AM toggle is selected, and 12:XX PM when the PM toggle is selected

Minimal reproduction of the problem with instructions
http://plnkr.co/edit/hUfvzi7KbY93wQf3snH9?p=preview

What is the motivation / use case for changing the behavior?
This bug results in the time picker displaying times incorrectly when 12 hour time is selected. For those who use 12 hour time, this is confusing and the time picker is not a viable option with this bug.

Please tell us about your environment:
Win 10
VS Code

Angular version: 4.4.3

PrimeNG version: 4.3.0-rc.1

Browser: all
 
Language: all

**Comment by cagataycivici** [comment]
Duplicate https://github.com/primefaces/primeng/issues/4312
