### ISSUE TITLE
Ability to define optionValue, optionDisabled, optionGroup in Select components

### ISSUE THREAD

**Issue by serlopez46** [primefaces/primeng#4295]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case**
http://plnkr.co/edit/GuEdxXOOClLs2RoeExJd?p=preview

**Current behavior**
Field 'value' from SelectItem is set in ngModel / FormControl.
When using an object array as options (#4274) the object is set instead.

**Expected behavior**
Since we already have optionLabel when using an object array as options, it would be greatly appreciated if we could define an **optionValue** in order to select a field of the object instead of the whole object (id for example).

**What is the motivation / use case for changing the behavior?**
Being able to use an array of objects as options for Dropdown and similar components but still be able to set only one of the object fields as the input value.

**Comment by Thunderlemon** [comment]
FWIW: I was able to workaround this by using/modifying the method located in `ObjectUtils`.

```   
generateSelectItems(items: any[], label: string, value?: string): SelectItem[] {
    let selectItems: SelectItem[] = [];
    if(items && items.length) {
        for(let item of items) {
            selectItems.push({label: this.objectUtils.resolveFieldData(item, label), value: value ? this.objectUtils.resolveFieldData(item, value) : item});
        }
    }
    return selectItems;
}
```

This way you can pas in an Object[] and specify both the label and the value.

**Comment by shamoh19** [comment]
is there any option to set string to dropdown value instead of passing entire object?

**Comment by yelhouti** [comment]
any ETA on this, can I make a pull request to fix it? thanks in advance

**Comment by sevenposchnappi** [comment]
same issue in autocomplete

**Comment by yelhouti** [comment]
You can find it implemented here in the meantime, I'll try to keep my branch up to date:
https://github.com/yelhouti/primeng/releases/tag/8.0.0-rc2

**Comment by PIlepRusel** [comment]
is the new feature not yet deployed ?

**Comment by jsilveira2** [comment]
Hello @yelhouti this can already be used from the version 8.0.3?

**Comment by yelhouti** [comment]
primeng team refused to merge my PR, so I deployed it in my fork, to use it, use this instead of the version number in your package:
```
"primeng": "https://github.com/yelhouti/primeng/releases/download/8.0.0-rc2/primeng-8.0.0-rc.2-SNAPSHOT.tgz",
```

**Comment by jsilveira2** [comment]
I do not understand, there are many issus open with this same request and several people would certainly use this feature and yet the primeng people do not give us answers or accept implementations. Why that @cagataycivici ??

**Comment by rafa-as** [comment]
some news @cagataycivici ?

**Comment by vishal4799** [comment]
@yelhouti, did the prime team provide any explanation while refusing your PR?

**Comment by yelhouti** [comment]
yes: company policy
Although the project is opensource, it is not community driven, only employees can add new features.

**Comment by yelhouti** [comment]
@cagataycivici thanks for assigning this, you people rock!

**Comment by cagataycivici** [comment]
PrimeReact and PrimeVue has optionValue so PrimeNG will get it in 9.0.1 as well.

**Comment by cagataycivici** [comment]
Moved to 9.1.0 as 9.0.x is for maintenance and 9.1.x is for new stuff like this, new Galleria, Virtual Scroll Tree...

**Comment by yelhouti** [comment]
Any ETA for this please? just wondering to know when to upgrade my fork :) thanks

**Comment by cagataycivici** [comment]
9.1.0 is already packed with features and enhancements and this issue deserves more attention so moving to PrimeNG 10 which is not too far away.

**Comment by dbaghel** [comment]
Thanks cagataycivici,

It's a really important feature. We need to do lot of hacks to work around it. This is very basic thing missing. Looking forward to PrimNG10

**Comment by Un1xMida** [comment]
so i have nothing left to say after all this time we have been waiting for this tiny little feature but u wont accept the PR also u wont do it urself so tell us please what to do in this case !

**Comment by cagataycivici** [comment]
Hey all, scheduled for 10.1.0, this one has high priority.

**Comment by yelhouti** [comment]
@cagataycivici https://github.com/primefaces/primeng/pull/9359

**Comment by milosrusov** [comment]
This worked for me:
(onChange)="someVariable = $event.value.value"
I know it's a bit dirty though

**Comment by gustavobmichel** [comment]
I really welcome this change. I hadn't realised that you can intercept the change by using `ControlValueAccessor`. So I created a small example on Stackblitz where you can see that: [https://stackblitz.com/edit/primeng-autocomplete-demo-t47r9j](https://stackblitz.com/edit/primeng-autocomplete-demo-t47r9j)

Maybe it'll help someone until we get this.

**Comment by cagataycivici** [comment]
![screely-1604318223888](https://user-images.githubusercontent.com/686247/97866246-a33e7000-1d1c-11eb-9bba-84f18ffa8958.png)

**Comment by hakansan** [comment]
we are waiting for the new version

**Comment by gustavobmichel** [comment]
@cagataycivici will the feature be available for Auto complete components as well? I saw the tagging for SelectButton, Multi select and list box. Thanks

**Comment by sserje06** [comment]
@cagataycivici I hope you are well, I am on version 10 of PrimeNG and I have tried everything that works, bring the value (id) of the object and I tried this last change that you showed in your image but it does not work, this was already released in the last version ?

**Comment by Exlord** [comment]
same here v10 but `optionValue` is not a valid attribute of `p-dropdown` ??
I even looked throw the source code and `optionValue` is nowhere to be found , but the docs says I can use it ???
