### ISSUE TITLE
Tree issue

### ISSUE THREAD

**Issue by belvo6** [primefaces/primeng#4297]
Hello i have a problem with tree component in PrimeNG
just wanna drag and drop in tree the nodes whitch are the siblings .

**Current behavior**
I can drag and drop each node to each node.

**Expected behavior**
Example here : 
1. Fruit          
     1.1 Apple
     1.2 Pear
2. Vegetables
  2.1 Onion
 2.2 Tomato
  and i can drag an drop only apple with pear or onion with tomato or fruit with vegetables :)
thx

* **PrimeNG version:** 4.2.2

**Comment by chrishawn** [comment]
setting or eventhandle for this would help a lot

**Comment by yigitfindikli** [comment]
fixed in https://github.com/primefaces/primeng/commit/50c4bbea162aafbf7320bf0e0814aa1f15a99737
