### ISSUE TITLE
4.3.0-RCX autocomplete remains in focus with input as readonly (blocking page)

### ISSUE THREAD

**Issue by huineng** [primefaces/primeng#4298]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[x ] feature request 
```
**Current behavior**
I have a user story where the autocomplete input becomes readonly after selection (onSelect)
With the latest 4.3 X release that input field remains on focus meaning the whole form (whole page) becomes unselectable

**Expected behavior**
Autocomplete should get out of focus .. this.onfocus=false; when input element is in readmode

Maybe a code can be added with onblur or onselect that checks if the input element is in readmode (or maybe also disabled)

If that is the case then this.onfocus = false

ps maybe the onInputBlur is never called when a input element is in readonly

thanks

**Comment by bogacg** [comment]
I see same problem, focus not leaving `autoComplete`, when `forceSelection` is used with object selection.

**Comment by SpiderPork** [comment]
I can confirm the problem with 4.3 RC2

**Comment by sviswanathjcet** [comment]
I have same issue. Please find the plnkr. Its holding my project. Can you tell me the workaround please?
@cagataycivici  https://plnkr.co/edit/cvnYa6?p=preview

<p-autoComplete [(ngModel)]="seletedProject"
							[suggestions]="filterProjectSingle"
							(completeMethod)="filterProjectSingleEvent($event)" field="projectName"
							[size]="30" placeholder="Projects" [minLength]="1"
				       [multiple]="false" [forceSelection]="true"
							[dropdown]="true" (onSelect)="selectProject($event)"></p-autoComplete>

**Comment by ili** [comment]
The same problem with 4.3.0: focus is not leaving when value is selected for autocomplete in Force Selection mode. Only way to "tab" from the control is to clear it's input.

Plnkr: http://plnkr.co/edit/C7b0lSV30CRk496KomWx?p=preview 

P.S. the interesting point is: when `forceSelection="true"` after `onBlur` event `onSelect` event is fired. And it is fired **only** when value is selected.

**Comment by ili** [comment]
Yap, yes, here is the problem:
`this.selectItem` is called `onInputBlur`
https://github.com/primefaces/primeng/blob/master/src/app/components/autocomplete/autocomplete.ts#L521

and here: https://github.com/primefaces/primeng/blob/master/src/app/components/autocomplete/autocomplete.ts#L359 this method returns focus to the input 

:(( fix needed
And

**Comment by sviswanathjcet** [comment]
is this issue fixed with forceselection=true?

**Comment by faizu88** [comment]
As this issue is fixed in PrimeNG 5.0.0-RC0 [Angular v5],  But still this is an issue for those who using Angular v4.  
From your note it's clear that PrimeNg do not have plans to do a new release on PrimeNG 4.x branch. So will I be getting patch release or not?

**Comment by svinesh3691** [comment]
Agreed with @faizu88

**Comment by alaa9jo** [comment]
Totally agree with @faizu88 , we need a patch for this issue, for now I had to use the fix suggested by @ili and it worked like a charm

**Comment by huineng** [comment]
The implementation is not correct in my opinion

(as mentioned above ) whenever forceselection is set to true and you have made a selection 
THEN whenever you want to click on a control like another button , the first thing that happens is that the onInputBlur is being called which in turns calls the onselect (again..)

this makes this implementation useless in any form with just an autocomplete and a submit button, (users might think the submit button is not working) 

I've sold this issue for the moment by resetting the suggestions to undefined so that this line is evaluated false. Hope this might help for other people

ps my suggestions are from a http call, others might have predefined suggestions, so for them a different solution might be found

```
if(this.forceSelection && this.suggestions) {
```

https://github.com/primefaces/primeng/blob/master/src/app/components/autocomplete/autocomplete.ts#L512

**Comment by NAMSGithub** [comment]
confirmed that updating primeNG when experiencing this bug using Angular 5 fixed this for me.

**Comment by sbkpilot1** [comment]
I had the same issue and can confirm as well that upgrading to PrimeNG 5.0.2 (^5.0.0) fixed this issue :)

**Comment by flhaz** [comment]
Hi, thank your for this great lib, Is there any solution for those are stuck on version 4 of Angular ?

**Comment by preterer** [comment]
Another solution (the proper one, not a hacky one) is to clear your suggestions in the `onSelect`.
You also have to clear your result `onDropdownClick` if you are using dropdown mode, or you will be stuck with the once selected value.
