### ISSUE TITLE
Enhancement: OrderList: new property to place "order panel" on the left or right side

### ISSUE THREAD

**Issue by jefftham** [primefaces/primeng#4299]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

"order panel" is the panel that move item up and down.
The current design hard coded the "order panel" on the left side.

**Expected behavior**

Expected to let programmer change the place easily without deep learning the CSS. A new property is needed. eg. [orderPanel]="right"

**What is the motivation / use case for changing the behavior?**

Improvement

* **Angular version:** 4

* **PrimeNG version:** 4.2.2

**Comment by JacobSiegle** [comment]
#6506 fixed but the PR was denied.

**Comment by cagataycivici** [comment]
controlsPosition="right" handles this, new OrderList is based on Flex which enables easier customization. Thanks for the feedback @JacobSiegle
