### ISSUE TITLE
p-dropdown doesnt open when tabbed into with keyboard

### ISSUE THREAD

**Issue by dhniels** [primefaces/primeng#4303]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report 

```

**Current behavior**
When you click into p-dropdown or p-calendar, it opens the dropdown/datepicker. When I am tabbing around the inputs with the keyboard, p-calendar opens the datepicker when focused, but dropdowns dont open when it receives focus from the keyboard tabbing.

**What is the motivation / use case for changing the behavior?**
Proper focus behavior and styling on `:focus` is important for accessibility

**Comment by cagataycivici** [comment]
It should not receive focus as this behavior is based on native select element, at least on mac. You can use alt+down to open it while it has focus. If more users demand this, I guess we can add openOnFocus property in the future.

**Comment by dhniels** [comment]
Thanks for the clarification. I would definitely toss in my hat for an openOnFocus feature. Thanks!
