### ISSUE TITLE
Stacked Chart

### ISSUE THREAD

**Issue by bevrard** [primefaces/primeng#4304]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Expected behavior**
Would it be possible to add the stacked chart from chart.js in the PrimeNg module?
http://www.chartjs.org/samples/latest/charts/bar/stacked.html

**Comment by cagataycivici** [comment]
Please use forum for questions, PrimeNG Charts are chart.js by the way.
