### ISSUE TITLE
Primeng Datatable -Horizontal scroll not coming in Chrome browser

### ISSUE THREAD

**Issue by PriyadharshiniMadheswaran** [primefaces/primeng#4308]
Horizontal Scroll Bar not coming in Chrome browser whereas in internet explorer by default the horizontal scroll bar is coming.If scroll width is set in the gridview for different resolutions in CHrome the gridview is not displaying properly
**Chrome Browser**
![image](https://user-images.githubusercontent.com/32955023/32171255-8d16ea50-bd9d-11e7-815b-8c7bfdbff6e6.png)
**Internet Explorer**
![image](https://user-images.githubusercontent.com/32955023/32171339-c60c0610-bd9d-11e7-8d43-d1572904d1e5.png)

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=info

**Comment by pantonis** [comment]
@cagataycivici  This is a bug and I dont understand why you avoid it. I have already open a ticket in which you provided a dirty workaround. 
https://github.com/primefaces/primeng/issues/4247
