### ISSUE TITLE
Toggleable Row Groups With Checkbox Selection

### ISSUE THREAD

**Issue by amit509** [primefaces/primeng#4310]
Hi All,

I have integrated "Toggleable Row Groups" data table and I wanted to add "Checkbox Selection" functionality to it.

Basically check boxes on "rowgroupheader" and on "header" to select all.

Can any one help me out to achieve this?

Thanks in advance.

**Comment by cagataycivici** [comment]
Please use forum for questions.

**Comment by kvabhishek** [comment]
Hi Amit, Did you find a solution for this? I am also looking for same feature. Please put some light on that.
