### ISSUE TITLE
Time picker displays 00 for hours for 12 hour time

### ISSUE THREAD

**Issue by CNitschelm** [primefaces/primeng#4312]
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/hUfvzi7KbY93wQf3snH9?p=preview

**Current behavior**
The time picker input box displays 00 in the hours section when 12 hour time is selected.
Additionally, when you type in "12:XX AM" where XX are digits, the picker switches it to PM.

**Expected behavior**
00 should never displayed in the hour section for 12 hour time. 12 hour time never has a 00 in the hour. 

24 hour time: 23:59 -> 00:00
12 hour time: 11:59 PM -> 12:00 AM

Additionally, when you type in "12:XX AM" where XX are digits, the picker should not switch it to PM, and it should instead remain AM.

**Minimal reproduction of the problem with instructions**
See Plunker

**What is the motivation / use case for changing the behavior?**
This behavior is extremely confusing for 12 hour time users, and those not familiar with 24 hour time may be unable to use the picker. 

**Please tell us about your environment:**
VSCode, Windows 10

* **Angular version:** 4.4.3

* **PrimeNG version:** 4.3.0

* **Browser:** All
 
* **Language:** All

**Comment by CNitschelm** [comment]
@cagataycivici @pjhaan As requested in #4125

**Comment by cagataycivici** [comment]
Fixed via PR https://github.com/primefaces/primeng/pull/4346

**Comment by JonKruger** [comment]
Any word on when this will go live?

**Comment by CNitschelm** [comment]
It was just pulled in, so probably in the next release. Judging based on history of X.X.1 releases, it should go live pretty soon.

**Comment by CNitschelm** [comment]
@cagataycivici Will this fix be going into a 4.3.1 or will it only be in an Angular 5 compatible version?
