### ISSUE TITLE
Progress Spinner does not work in IE

### ISSUE THREAD

**Issue by ADefWebserver** [primefaces/primeng#4313]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
```
**Current behavior**
This page does not work in Internet Explorer Web browser: https://www.primefaces.org/primeng/#/progressspinner

**Expected behavior**
It should work as it does in the Chrome web bowser 

**Minimal reproduction of the problem with instructions**
Navigate to:
https://www.primefaces.org/primeng/#/progressspinner 
using Internet Explorer 11 on a Windows 10 PC and view the example

* **Please tell us about your environment:** Windows 10 PC

* **Angular version:** Angular 4

* **PrimeNG version:** PrimeNG 4.3.0

* **Browser:** IE 11

**Comment by Lolash** [comment]
https://caniuse.com/#search=svg%20animation - I see, that animation is not supported by IE, so there should another approach used probably

**Comment by EricHislop** [comment]
@cagataycivici Is there any update on this issue? It's just PrimeNG says it supports IE9+

**Comment by ssabah** [comment]
As a workaround, you can provide a default style for the SVG because SVG animation is not supported in IE.

```
.ui-progress-spinner-circle {
  stroke: red;
  stroke-dasharray: 89, 200;
  stroke-dashoffset: -35px;
}
```

**Comment by cagataycivici** [comment]
Set to 6.1.6, @yigitfindikli

**Comment by mertsincan** [comment]
Thanks a lot, @ssabah and @yigitfindikli ;)
