### ISSUE TITLE
TS2339: Property 'disabled' does not exist on type 'MenuItem | MenuItem[]'

### ISSUE THREAD

**Issue by corvinrok** [primefaces/primeng#4314]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
```

**Current behavior**
In an angular component with the following property definition:
`    private menuItems: MenuItem[];`
Later in a method of the component we try to access the `disabled` property inside of that `menuItem` .
`                    this.menuItems[MainMenu.view].items[ViewMenu.toggleProperties].disabled = !this.propertyPaneToggleAvailable;`

But this produces the following Typescript error:
```
ERROR in ./ClientSide/app/panels/panel-main-menu/panel-main-menu.component.ts
[tsl] ERROR in C:\git\myproject\ClientSide\app\panels\panel-main-menu\panel-main-menu.component.ts(59,84)
      TS2339: Property 'disabled' does not exist on type 'MenuItem | MenuItem[]'.
  Property 'disabled' does not exist on type 'MenuItem[]'.
```
This error only exists once I upgrade from primeng 4.2.2 to version 4.3.0

**Expected behavior**
This property exists in the definition of `MenuItem`, and it should not throw an error like this. In version 4.2.2, this code did not give this error.  

**Minimal reproduction of the problem with instructions**
See above, already shown in code

**What is the motivation / use case for changing the behavior?**
This is a new error that seems to be a false positive.

**Please tell us about your environment:**
Windows 7

* **Angular version:** 4.4.6

* **PrimeNG version:** 4.3.0

* **Browser:**  Chrome 
 
* **Language:**  TypeScript 2.5.3

* **Node (for AoT issues):** `node --version` =   7.10.1

**Comment by Guoye** [comment]
see #3640 
cagataycivici closed this in c227ef9 9 days ago

**Comment by corvinrok** [comment]
@Guoye  wrong. This is new with 4.3.0 . It was introduced by it, not fixed by it. I saw from primeng that it is to be fixed in 4.3.1, which apparently isn't out yet.

**Comment by cagataycivici** [comment]
You need to cast it;

```
(<MenuItem> this.menuItems[MainMenu.view].items[ViewMenu.toggleProperties]).disabled = !this.propertyPaneToggleAvailable;
```

**Comment by corvinrok** [comment]
No. Not it at all.
