### ISSUE TITLE
p-listbox,p-multiselect... SelectedItem: Allow to disable individual items

### ISSUE THREAD

**Issue by RSginer** [primefaces/primeng#4315]
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
I can't do
**Expected behavior**
The SelectedItem interface has disabled property

**What is the motivation / use case for changing the behavior?**
I want to disable SelectedItems on the p-list, p-multiselect, etc

**Comment by cagataycivici** [comment]
Issue is too broad, please create separate tickets for each one.
