### ISSUE TITLE
PDFViewer

### ISSUE THREAD

**Issue by webnegar** [primefaces/primeng#4318]
Hi Team,

Please add PDFViewer Component (view or modify and sign PDF files in angular).
#
tnx

**Comment by jaggi510** [comment]
Hi, 

Any timeline/consideration for this enhancement?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by nayasanjit** [comment]
Is there any progress on this?
