### ISSUE TITLE
VirtualScroll does not show last page

### ISSUE THREAD

**Issue by EugeneBugor** [primefaces/primeng#4321]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/pvQoRPPGoEvYyvGpScfx?p=preview

**Current behavior**
After updating to PrimeNG 4.3.0 DataTable virtual scrolling does not work with the last partial page.
In the scenario of the plunker case we have 45 total records. The offset to load a new chunk of records is 10. Scrolling down to the end gives only penultimate chunk of records. It is easy to notice that on the bottom of the scroll the offset is 30. 

P.S. in my description 'offset' means 'first' property binding of "DataTable" component

**Expected behavior**
DataTable component should show  the last partial page of the records.

**Minimal reproduction of the problem with instructions**
Fallow the link to plunker case for [issue reproduction](http://plnkr.co/edit/pvQoRPPGoEvYyvGpScfx?p=preview)

**What is the motivation / use case for changing the behavior?**
Probably updating 'offset' value when the last record + 1 is shown will make a sense. For now 'offset' value updates, but only to the same value until the last value is hidden.

**Please tell us about your environment:**
Operating system: *, 
IDE: JetBrains WebStorm v2017.1.4, JetBrains IntelijIdea: 2017.2.5, 
Package manager: npm.

* **Angular version:** 4.4.6

* **PrimeNG version:** 4.3.0

* **Browser:** all
 
* **Language:** all

* **Node version:**   8.4.0

**Comment by cagataycivici** [comment]
You need to use the event.rows;

```
this.records = this.allRecords.slice(event.first, event.first + event.rows);
```

**Comment by EugeneBugor** [comment]
@cagataycivici ,  Okay, but it is not fix the issue. I updated [the plunker](http://plnkr.co/edit/pvQoRPPGoEvYyvGpScfx) . In this case we cannot request 11th record. Total records is always 10 elements.

**Comment by EugeneBugor** [comment]
@cagataycivici , and also, with <event.rows> we request <this.rows*2> records, but expect to fetch <this.rows> amount of elements.
