### ISSUE TITLE
p-dialog component does't works properly in mobile browser.

### ISSUE THREAD

**Issue by alialtun14** [primefaces/primeng#4323]
From the very beginning p-dialog component hasn't work properly in mobile browser. 
![dialog](https://user-images.githubusercontent.com/782196/32234186-6b2d7f0c-be5c-11e7-9236-39e365e5075b.png)

**Comment by cagataycivici** [comment]
Set responsive to true.

**Comment by alialtun14** [comment]
The code which you use in primeng showcase
<p-dialog header="Godfather I" [(visible)]="display" modal="modal" width="300" [responsive]="true">

The code which I use in my project.
<p-dialog [(visible)]="_opt.show.self" [responsive]="true" showEffect="fade" [modal]="true" appendTo="body" width="500">

Responsive is set to true in these code . But it hasn't work properly.
