### ISSUE TITLE
Dynamic height support to Chart

### ISSUE THREAD

**Issue by fernandocode** [primefaces/primeng#4324]
[x] bug report

[**Plunkr Example Bug**](http://plnkr.co/edit/ter5UxW74v83nAkSbuRA?p=preview)

I'm trying to specify a height for my horizontalBar, except that it seems to bind to the canvas the value is lost and 150px is added.

In the example I dynamically check the size of the list and calculate the height of the graph, except that the graph does not keep that size. It looks like there is something wrong the moment the chart size changes.

I made an example where I add the size in the code and not the recalculation dynamically, as this the defined size is respected: [Example with fixed heigh](http://plnkr.co/edit/dARZH8OjvEVVQ9fEakDz?p=preview)t.

>Note: in options `maintainAspectRatio: false`

* **Angular version:** 4.2.6

* **PrimeNG version:** 4.3.0

* **Browser:** [all]
 
* **Language:** [TypeScript]

**Comment by fernandocode** [comment]
I discovered where the `height `value was being lost by analyzing the path of the `height `until it was applied to the [`Chart.js`](https://github.com/chartjs/Chart.js) `canvas`.

In the [`resize()` method of chart.js](https://github.com/chartjs/Chart.js/blob/master/src/core/core.controller.js#L177), I calculate the new `height `for the chart, where `aspectRatio `is `false `in our configuration, then calling `helpers.getMaximumHeight(canvas) `to get the new `height`.

In the [`getMaximumHeight(canvas)` method in `Helpers`](https://github.com/chartjs/Chart.js/blob/master/src/core/core.helpers.js#L481-L492) it is checked if the `canvas `element has any `parentNode`, if it does not have `canvas ``height `pickup, if it has (which is our case, the `div `around the `canvas` `p-chart` template) calculates the height based on the height of the `canvas.parentNode`. In our case the `div `around the `canvas` is the `parentNode`, and it has no defined `height`, and it ends up returning a default `height `of `150`.

## Solution

[In this example](http://plnkr.co/edit/ter5UxW74v83nAkSbuRA?p=preview), I copied the [primeng `p-chart` component](https://github.com/primefaces/primeng/blob/master/src/app/components/chart/chart.ts) and made a change to the component template to apply the bind variable's `height `also in the `div `element to the `canvas `throne.

[This is working perfectly for me.](http://plnkr.co/edit/ter5UxW74v83nAkSbuRA?p=preview)

I'm going to submit a pull request, with this change, please check if this can have any side effects.

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/issues/4577
