### ISSUE TITLE
Bug with overlaypanel in 4.3.0

### ISSUE THREAD

**Issue by dhniels** [primefaces/primeng#4327]
I have a delete confirmation overlaypanel that appears when clicking an "X" icon in my app. it is inside a p-dialog component if that matters...

 after updating to primeNG 4.3.0 the overlaypanel no longer appears. Upon inspection, it appears that it is not toggling `display: none` to `display: block` as it normally should. Are you able to reproduce?

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=info

**Comment by mronus** [comment]
@cagataycivici - We've the same issue with p-overlayPanel. It happens only for some of components on our application, especially when not using appendTo. I couldn't reproduce this on components other than broken ones yet, but I can see that it gets fixed when adding appendTo to the broken components.

I had to apply a workaround like the following to come over this issue.

```html
<button (click)="togglePanel($event)">Test</button>
```
```typescript
function togglePanel(event: any) {
  this.overlayPanel.toggle(event);
  this.overlayPanel.el.nativeElement.classList.toggle('menu-open');
}
```
```css
.menu-open {
  display: block !important;
}
```

**Comment by richteri** [comment]
We also have this issue, I'll try to create a plnkr for it.

**Comment by dhniels** [comment]
@mronus I'm having the exact same behavior as yours. Applying appendTo body fixes it, as does your fix. Definitely a bug introduced in 4.3.0 somewhere.

**Comment by dhniels** [comment]
Still have this bug in v5. updated to 5.0.2 and the issue persists.

**Comment by dhniels** [comment]
@cagataycivici please re-open this issue. 

i was finally able to create a [working example](http://plnkr.co/edit/CJQBFfqFg3fjdtreKGQy?p=preview) of the bug. See the Plunker.

It appears that if the overlaypanel has position:fixed it breaks the toggle between `display: none` and `display: block`, or at least, I think this is the culprit. Please investigate.

**Comment by rikan** [comment]
the same issue
in 4.2 this code can show overlayPanel.
`this.overlayPanel.show(null, this.contentRef.nativeElement)`
but in 4.3.0 it not working, 
even give click event parameter, the overlayPanel is still display:none.

**Comment by dhniels** [comment]
no response in a over a month on this issue. sometimes i wonder if the primeNG team just cherrypicks issues and closes ones they dont want to deal with because there is broken functionality all over the place that is completely unaddressed. When I create issues they are immediately closed and never looked at again 50% of the time. Im beginning to regret my choice using PrimeNG in my application.

**Comment by dhniels** [comment]
I'm still having this issue in PrimeNG 5.2.4. For what its worth I tested with both Chrome and FireFox, and I could only replicate it in Chrome.

**Comment by cagataycivici** [comment]
Set to review for 5.2.5

**Comment by acarboni71** [comment]
PrimeNG 5.2.7 still has this problem. Please, help
