### ISSUE TITLE
Incompatibility between ResizableColumns and RowsPerPageOptions

### ISSUE THREAD

**Issue by lusid** [primefaces/primeng#4328]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
I have demonstrated the issue in the Plunkr below.
http://plnkr.co/edit/Z3U9EiXt0PXnGm8k3mux?p=preview

**Current behavior**
In the p-dataTable component, when using [paginator]="true", [resizableColumns]="true", and [rowsPerPageOptions]="[10,20,etc]", the select box dropdown contents for the number of items per page is hidden when clicked in the first example.

**Expected behavior**
The expected behavior can be seen by setting [resizableColumns]="false". This is demostrated in the same Plunkr I've provided. The dropdown opens as expected in the second example.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/Z3U9EiXt0PXnGm8k3mux?p=preview

**What is the motivation / use case for changing the behavior?**
Resizable columns is a useful feature to have alongside adjustable record counts per page, and it worked fine in PrimeNG 4.2.* before you guys swapped the plain html select control out for your own dropdown control.

**Please tell us about your environment:**
Mac OS High Sierra, VS Code, NPM, nginx

* **Angular version:** 4.2.6

* **PrimeNG version:** 4.3.0

* **Browser:** [Chrome 61.0.3163.100]
 
* **Language:** [TypeScript 2.6.1]

* **Node (for AoT issues):** `node --version` =   v8.4.0

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
