### ISSUE TITLE
Datatable paginator add template feature

### ISSUE THREAD

**Issue by Ketec** [primefaces/primeng#4329]
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behaviour**
There is a simple pagination with buttons and not information about total pages and/or records.

**Expected behavior**
Allow templating to provide custom displays for extra pagination info.
For example:
```
<div class="ui-paginator-bottom-wrapper" *ngIf="paginator">
                <div class="ui-paginator-bottom ui-paginator ui-widget ui-widget-header">
                    <span class="status-label">
                        {{totalRecords < 1 ? 0 : first + 1}} - {{totalRecords > 0 ? ((rows + first) <= totalRecords ? (rows + first) : totalRecords) : 0}} of {{totalRecords ? totalRecords : 0}}
                    </span>
                </div>
                <p-paginator [rows]="rows" [first]="first" [totalRecords]="totalRecords" [pageLinkSize]="pageLinks" styleClass="ui-paginator-bottom"
                             [alwaysShow]="alwaysShowPaginator"
                             (onPageChange)="onPageChange($event)" [rowsPerPageOptions]="rowsPerPageOptions"
                         *ngIf="paginator && (paginatorPosition === 'bottom' || paginatorPosition =='both')"></p-paginator>
            </div>
```
Would right now show total records and current page records ( with 100 records per page it would be 1-100 of 1000, next page 101-200 of 1000). 
Make this possible through custom templating (providing access to required paginator values).
Optionally could make the whole paginator section templateable so custom paginator designs could be implemented.

**Comment by Ketec** [comment]
Does it provide access to paginator variables like:
`[rows]="rows" [first]="first" [totalRecords]="totalRecords" [pageLinkSize]="pageLinks"`

Or is it just static template that has no connection to the paginator itself? 

For example:
`<ng-template let-totalRecords="totalRecords">{{totalRecords}}</ng-template>`

**Comment by cagataycivici** [comment]
Currently static, if you need more info on page state, please create a separate ticket and we'll do it for 5.0.1

**Comment by izy2nv** [comment]
@cagataycivici Is there a fix for rowsPerPageOption for 'ALL' in case user wants to display all records on datatable page (without pagination)
