### ISSUE TITLE
Totals in datatable

### ISSUE THREAD

**Issue by pantonis** [primefaces/primeng#433]
Hi,

I'm trying to add total under a column. I suppose there is not built-in way to do it so I tried to do it manually. I am using RxJS to get the data from a rest endpoint and I am assigning a local variable with initial value of 0 to the footer column. Problem is that the value is not updated on the table after I get the results and I still see 0.

**Comment by joe380** [comment]
I do not have this tried out, but try to inject **ChangeDetectorRef** from **@angular/core** and in subscribe method after setting updating a local variable(s) call **changeDetectorRer.markForCheck()**

**Comment by pantonis** [comment]
@joe380 I have changeDetection: ChangeDetectionStrategy.CheckAlways

and calling changeDetectorRer.markForCheck() after my number property is updated.

Result. Everything is gone from the screen. No data at all

**Comment by cagataycivici** [comment]
Please use forum for such discussions;

http://forum.primefaces.org/viewforum.php?f=35

**Comment by afras21** [comment]
Instead of footer , I need in the end of the Tables . Both vertically and Horizontally and their cross matrix sum
