### ISSUE TITLE
fix 4122  datatable isSelected missing from 4.3.0

### ISSUE THREAD

**Issue by Ketec** [primefaces/primeng#4330]
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
Fix made in is missing in 4.3.0 release.
https://github.com/primefaces/primeng/issues/4122

**Comment by cagataycivici** [comment]
This broke the table so reverted, with this no selection was highlighted.

**Comment by Ketec** [comment]
This is unusual, i have the latest 4.3 datatable code i use to keep critical fixes in place - and i do not see any problems with my tables. 
`if(rowData && this.selection && this.selection.length) `
