### ISSUE TITLE
Reset method support for Scroll

### ISSUE THREAD

**Issue by EugeneBugor** [primefaces/primeng#4331]
**I'm submitting a ...** 
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/PTcjmhRxUVajXri7RzQ1?p=preview

**Current behavior**
In the scenario of [plnkr case](http://plnkr.co/edit/PTcjmhRxUVajXri7RzQ1?p=preview) we have 40 total records and 10 rows per partial page. When we scroll to the bottom of the grid and click on "Reset" button, DataTable grid reset "first" binding property but virtual scroll saves. 

**Expected behavior**
"Reset" method result suppose to scroll up to the start of the grid.

**Minimal reproduction of the problem with instructions**
Link to [plnkr case](http://plnkr.co/edit/PTcjmhRxUVajXri7RzQ1?p=preview) for reproduction.

**What is the motivation / use case for changing the behavior?**
Clear virtual scroll in DataTable on reset() method.

**Please tell us about your environment:**
Operating system: *,
IDE: JetBrains WebStorm v2017.1.4, JetBrains IntelijIdea: 2017.2.5,
Package manager: npm.

* **Angular version:** 4.4.6

* **PrimeNG version:** 4.3.0

* **Browser:** all
 
* **Language:** all

* **Node:** 8.4.0

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
