### ISSUE TITLE
autocomplete with forceSelection bug

### ISSUE THREAD

**Issue by ili** [primefaces/primeng#4332]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
Autocomplete with `forceSelection` clears input if it contains lead or trailing spaces

**Expected behavior**
Value should not be cleared

**Minimal reproduction of the problem with instructions**

Here: https://github.com/primefaces/primeng/blob/master/src/app/components/autocomplete/autocomplete.ts#L519 is the problem.

while `inputValue` is trimmed - `itemValue` is not. So if I do have " this value starts with space" presented both in input & in suggestions comparison will fail. so condition should be 
```
if(itemValue && inputValue === itemValue.trim()) 
```

**Comment by ili** [comment]
Pls, reopen an issue, looking current master state the problem is still present

**Comment by aamir1995** [comment]
@ili this problem is still happening.

**Comment by cagataycivici** [comment]
PR added, thanks.
