### ISSUE TITLE
p-datatable w/ metaSelectionKey="false" does not emit row data on selection

### ISSUE THREAD

**Issue by kc13greiner** [primefaces/primeng#4335]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/RojMuMDqnXV8kGTYWgpE?p=preview

**Current behavior**
When the `p-datatable` attribute `metaKeySelection` is set to `false` and `selectionMode` is set to `single`, no row data is emitted on row selection 

**Expected behavior**
Emission of row data should occur if `metaKeySelection` is set to `false`

**Minimal reproduction of the problem with instructions**
Create a datatable with metaSelectionKey="false" and selectionMode="single" (see aforementioned plunker)

**What is the motivation / use case for changing the behavior?**
Users should be able to click on a row to unselect, not have to use  ctrl/command to unselect

**Please tell us about your environment:**
MacOX, IntelliJ 2017

* **Angular version:** 4.4.6

* **PrimeNG version:** 4.3.0

* **Browser:** all
 
* **Language:** all

**Comment by ChrisBadalucco** [comment]
Also seeing the issue for Windows 7 on Firefox Developer Edition & Chrome.

**Comment by Pikadili83** [comment]
The same problem here...
