### ISSUE TITLE
Floating labels for calendar

### ISSUE THREAD

**Issue by ccasallas** [primefaces/primeng#4336]
I'm submitting a:
```
[ ] bug report
[x] feature request
[ ] support request
```
I create a separated ticket to track floating labels enhancement on calendar according to  #4011  (at least in ultima theme).

**Comment by tengel92** [comment]
Floating labels do appear to be working in Utlima 4.3.0 for the calendar component. I agree they do not work on dropdown, multiselect etc and some other input components though.

![screen shot 2017-11-02 at 12 19 30 pm](https://user-images.githubusercontent.com/9407887/32340283-209f23a6-bfc8-11e7-8bdb-a9bb5913a184.png)
![screen shot 2017-11-02 at 12 19 19 pm](https://user-images.githubusercontent.com/9407887/32340281-2062d6c6-bfc8-11e7-90bd-ba0355ad28db.png)

**Comment by cagataycivici** [comment]
Please use ultima forum to report issues, this tracker is for PrimeNG
