### ISSUE TITLE
Floating labels for dropdown

### ISSUE THREAD

**Issue by ccasallas** [primefaces/primeng#4337]
I'm submitting a:
```
[ ] bug report
[x] feature request
[ ] support request
```
I create a separated ticket to track floating labels enhancement on dropdwon according to  #4011 (at least in ultima theme).

**Comment by cagataycivici** [comment]
Please use ultima forum to report issues, this tracker is for PrimeNG

**Comment by plukhi17** [comment]
p-dropdown with ui-float-label is not working.
1. it works if we click on dropdown list
2. it doesn't work if we use keyboard event.
