### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError - When showing a ConfirmDialog in response to a dropdown value selected

### ISSUE THREAD

**Issue by rezord** [primefaces/primeng#4341]
After changing the value of dropdown I open a confirm dialog box but it generates ExpressionChangedAfterItHasBeenCheckedError . I have created a test case:
http://plnkr.co/edit/aNtTSjBF5As641tz61Xe?p=info

**Comment by cagataycivici** [comment]
This was fixed quite some time ago, please try with a new release.
