### ISSUE TITLE
Add a "dataProperty" property to p-column.

### ISSUE THREAD

**Issue by ayush987goyal** [primefaces/primeng#4344]
This will solve the problems of filtering and exporting DataTable in case the column data is an object.

Right now when a column contains data in form of object ( example when templating), exporting the column will show [Object Object] in the CSV. Also the column filtering does not work in such cases.

By adding this property, the filtering/exporting can be done with that property of the data object.

**Comment by cagataycivici** [comment]
Please provide a plunkr to describe your problem in the first place and we'll review again.

**Comment by ayush987goyal** [comment]
Here is the plunkr describing the problem.

[https://embed.plnkr.co/iuuydN5JS2xi0tlQcJay/](url)

**Comment by ayush987goyal** [comment]
Can the issue be reopened again please?
