### ISSUE TITLE
p-dataTable inline editing disabled when selectionMode="multiple"

### ISSUE THREAD

**Issue by vangalder** [primefaces/primeng#4345]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

I'm using PrimeNG v4.3.0-rc2 and I cannot get the inline editor to activate when I double-click on a row when the `p-dataTable` has the attribute `selectionMode="multiple"`.

This is an impediment for a project I'm working on, since I need both functionalities:
1. users can select mutiple rows
2. users can edit a field in a row by double-clicking on it

Maybe one way to approach this would be to unselect the row(s) and switch to inline edit when a user double-clicks on an editable field, since at that point the user has obviously changed what they're doing (i.e. editing instead of selecting).

Or perhaps it would be useful to have a method that I can invoke to cause a field to go to inline edit mode when it is double-clicked.

Thanks!

**Comment by cagataycivici** [comment]
Edit+row selection is not a supported combination as they conflict on row click. Use a column based selection instead like radio or checkbox on p-column.
