### ISSUE TITLE
Scoping for MessageService

### ISSUE THREAD

**Issue by Harlantr** [primefaces/primeng#4347]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
I'm not sure if this is a bug or a feature request.

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/F5dxgJ2xmjvnfiToGSiz?p=preview

**Current behavior**
After adding a message with `messageService.add()`, the message appears in all `p-messages` and `p-growl` components present on the current page.

**Expected behavior**
The MessageService should only apply the messages to one specific `p-messages` or `p-growl`.  I do not believe this functionality currently exists.

**Minimal reproduction of the problem with instructions**
1. Navigate to the attached plunkr
2. Press the "Add Message" button

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
* **Windows 7**
* **Angular version:** 4.2.6
* **PrimeNG version:** 4.3.0
* **Browser:**
  * Tested on:
    * Chrome 60.0.3112.101
    * IE 11
 
* **Language:**
  * TypeScript 2.3.3

* **Node (for AoT issues):** `node --version` =   
  * 6.11.2

**Comment by cedricclaus** [comment]
A proposition :

-  add an optional "key" property to p-growl and p-message components
-  add an optional "key" property on Message Model.
-  the components display messages only for matching key

We already have this behaviour for p-confirmDialog that allow to have multiple confirm dialogs in component tree.

**Comment by ryanreliford** [comment]
Any update?

**Comment by mnhock** [comment]
For us it would be very helpful as well.
