### ISSUE TITLE
Wrong OverlayPanel positioning inside a relative positioned element

### ISSUE THREAD

**Issue by gsuveti** [primefaces/primeng#4353]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://plnkr.co/edit/CRIgzX?p=preview

**Current behavior**

The overlay positioning is wrong.  The overlay is inside an element that has position:relative and the calculated top distance is bigger than expected by the height of the top menu bar.

**Expected behavior**

The overlay should be placed just below the button.

**Minimal reproduction of the problem with instructions**
- Open the plunker.
- Click the "Basic overlay" button

**Comment by cagataycivici** [comment]
This is expected, use appendTo="body".
