### ISSUE TITLE
AutoComplete focus problem (forceSelection)

### ISSUE THREAD

**Issue by mvulpe29** [primefaces/primeng#4358]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://plnkr.co/edit/FkF5svdb9neabnc6gSrT?p=preview

**Current behavior**
The autoComplete component gets stuck once selecting a value from the suggestion list when using forceSelection = true

**Expected behavior**
After selecting an item and pressing tab or clicking somewhere else the focus should move from the autocomplete component.

**Minimal reproduction of the problem with instructions**
on the included plunkr app select a value from the list (john or dan) and press tab (or click the other input)

**Comment by cagataycivici** [comment]
#4298
