### ISSUE TITLE
The UTC time format still does not work in the calendar.

### ISSUE THREAD

**Issue by MaxBurda** [primefaces/primeng#4359]
Now the calendar displays only local time. The properties [utc]="true"  does not work.
This can be seen from the example.
Please click on the link and choose any date.
https://stackblitz.com/edit/prime-ng-calendar?embed=1&file=app/calendar/calendar.component.html

* **Angular version:** 5.0.0

* **PrimeNG version:** 4.3.0

![utc](https://user-images.githubusercontent.com/11576087/32436959-6d16c3e6-c2ee-11e7-9d26-23de79146eaf.jpg)

**Comment by soares741** [comment]
I have similar issues with the UTC flag and the calendar.

UTC time is: 10/11/2017 23:59:59:999
CET time is: 11/11/2017 00:59:59:999

In this image I have the flag 'UTC="true"'
The date is displayed correctly on the input box but on the calendar it selects the day 11
The time isn't correct either in the calendar or input box

![with utc flag](https://user-images.githubusercontent.com/9722559/32504332-d70088ae-c3df-11e7-9edd-0e459407f8de.png)

**Comment by MaxBurda** [comment]
In my project, I use a workaround.
I use two dates.

The first (**fixed**) for display on the UI
`this.dateFix = new Date(this.date.getTime() + (this.date.getTimezoneOffset() * 60 * 1000));`

And the second (**true**) for sending to the server.
`this.date = new Date(this.dateFix.getTime() - (this.date.getTimezoneOffset() * 60 * 1000));`

https://stackblitz.com/edit/prime-ng-calendar-workaround?embed=1&file=app/calendar/calendar.component.ts

But this is an ugly way.
It would be nice if PrimeNG fixed this mistake.

**Comment by cagataycivici** [comment]
Does it still happen with 5.0.0-RC?

**Comment by derandreasberger** [comment]
Hello @cagataycivici!
I pulled the latest source and tried out UTC functionality. The pull-request i just posted would fix the issues I was able to identify when using timestamps with primeng calendar. Please review and let me know what you think!
Thanks!

**Comment by cagataycivici** [comment]
Merging, thanks.

**Comment by nivasn** [comment]
![image](https://user-images.githubusercontent.com/30048219/37213008-d0652960-237e-11e8-9ba2-0ddbf3ed3456.png)
![image](https://user-images.githubusercontent.com/30048219/37213116-16514170-237f-11e8-8188-f5a513be5d7d.png)
![image](https://user-images.githubusercontent.com/30048219/37213180-3aa55dae-237f-11e8-9833-fb0f521ae4e6.png)

The date issue still prevails, Please take a look at the screenshots. 
PrimeNg Version: 5.2.1
Anglar Version: 5.0.0

**Comment by fitness23** [comment]
> In my project, I use a workaround.
> I use two dates.
> 
> The first (**fixed**) for display on the UI
> `this.dateFix = new Date(this.date.getTime() + (this.date.getTimezoneOffset() * 60 * 1000));`
> 
> And the second (**true**) for sending to the server.
> `this.date = new Date(this.dateFix.getTime() - (this.date.getTimezoneOffset() * 60 * 1000));`
> 
> https://stackblitz.com/edit/prime-ng-calendar-workaround?embed=1&file=app/calendar/calendar.component.ts
> 
> But this is an ugly way.
> It would be nice if PrimeNG fixed this mistake.

Thank you, thank you, thank you! I have been trying to fix this for 2 days straight. This works great!
