### ISSUE TITLE
DataTable - Editing break when custom column uses Angular Pipe's

### ISSUE THREAD

**Issue by ammar91** [primefaces/primeng#436]
One of my datatable column has a custom template "unit price" that I 'm formatting with angular builtin currency pipe

`<p-column field="unitPrice" [style]="{'width': '100px'}" [editable]="true">`
   `<template let-col let-currentInvoiceItem="rowData">`
      `{{currentInvoiceItem[col.field] | currency: 'USD': true : '1.2-2'}}`
     `</template>`
`</p-column>`

Table renders well but as soon as I start editing value. Like If I enter 1, it throws an error

![error2](https://cloud.githubusercontent.com/assets/7683970/15650906/66a32942-2695-11e6-88e7-7d7ae6ee6065.PNG)

**Comment by ammar91** [comment]
I'm wondering if this could be fix in beta 9.

**Comment by ammar91** [comment]
Any ETA for this issue? Still looking to have it fix sometime soon.

**Comment by wujitouch** [comment]
That looks more like a type issue. Are you sure currentInvoiceItem.unitPrice is a number and not a string?

**Comment by cagataycivici** [comment]
Does it still happen with 2.0.2?

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
