### ISSUE TITLE
Clear icon for Dropdown

### ISSUE THREAD

**Issue by nsksaisaravana** [primefaces/primeng#4363]
Kindly add clear icon inside all type of input type.

**Comment by VinyP** [comment]
Would love this feature also. Also, Primeng rocks! Thank you for all your hardwork : )

**Comment by mkp05** [comment]
Agree, but IMHO dropdown will have one of highest priorities as in most of other fields you can enter the field and use keyboard - in dropdown... not :(

**Comment by gsteiner89** [comment]
Dont know if its still on the pipeline, its not in a milestone any longer, but i cant agree more.
Dropdown feels unhandy without a function to deselect.

For all those who need the feature as fast as I do, take a look at (https://github.com/ng-select/ng-select#examples)

**Comment by nsksaisaravana** [comment]
@gsteiner89 Thanks for sharing, looks good.

**Comment by nsksaisaravana** [comment]
@cagataycivici any idea when we get these features? Please, give these awesome features.

**Comment by cagataycivici** [comment]
Not sure about all inputs but we can start with dropdown for sure.

**Comment by cagataycivici** [comment]
<img width="185" alt="screen shot 2018-03-05 at 10 27 40" src="https://user-images.githubusercontent.com/686247/36962286-f2fe511c-205f-11e8-95b0-d5a18f504bc4.png">

**Comment by mkp05** [comment]
Nice, thank you.

When it comes to other inputs the reason may be for example IE - it has it's own "x" for most inputs (other browsers not) which (and it seems to be a bug, but I tried some time ago - maybe it's fixed) does not trigger change PrimeNGs events in on some inputs. It will make controls look and work totally the same on all browsers.

**Comment by rafa-as** [comment]
@cagataycivici it's possible to dispatch the change event when clear the dropdown to full control of this functionality? If don't use ngModel to bind the values, you need that the change event fires

**Comment by alexandrusin** [comment]
hi,
is there a way to remove this functionality?

**Comment by azulinternet** [comment]
The "clear icon" can be hide via CSS:
```
.ui-dropdown .ui-dropdown-clear-icon {
  display: none;
}
```

Not ideal, but...

**Comment by cagataycivici** [comment]
5.2.2 is now available;

https://www.primefaces.org/primeng-5-2-2-released/

The icon is invisible by default, [showClear]="true" enables it.
