### ISSUE TITLE
attr.readonly is incorrect in spinner

### ISSUE THREAD

**Issue by huineng** [primefaces/primeng#4366]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
```

**Current behavior**
attr.readonly is wrong and should not be used 
it will lead to html code  readonly="false"  but the only acceptable value in html is readonly

https://github.com/primefaces/primeng/blob/a5636678c03a40f2a4f9e2ceaf2a9fd1b8d30b8f/src/app/components/spinner/spinner.ts#L18

**Expected behavior**
please change [attr.readonly]=readonly in spinner to [readonly]=readonly

thanks

**Comment by huineng** [comment]
you changed that in your commit https://github.com/primefaces/primeng/commit/a5636678c03a40f2a4f9e2ceaf2a9fd1b8d30b8f#diff-a8c8d16b87c6a1c9d311deb4a0f2e550 i think for disabled etc.. this is fine, but not for readonly

**Comment by huineng** [comment]
It's not a big issue anymore as i have changed false into null, but it's still incorrect as in your documentation https://www.primefaces.org/primeng/#/spinner

readonly | boolean | false | When present, it specifies that the element should be read-only.

but it's better to change this into null

**Comment by cagataycivici** [comment]
Fixed the doc, thanks
