### ISSUE TITLE
Data Table - Filter and Scroll with DropDown (DropDown options cut off)

### ISSUE THREAD

**Issue by JacobSiegle** [primefaces/primeng#4369]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/RnyvH7U33NmCdgH9MrTt?p=preview

**Current behavior**
Datatable with filter and scroll causes multi drop down not to show.

**Expected behavior**
multi drop down option show

**Minimal reproduction of the problem with instructions**
See plunker above

* **Angular version:** 2.0.X
Angular - 4.1.3

* **PrimeNG version:** 2.0.X
PrimeNG - 4.3.0

If "ui-datatable-scrollable-body" is moved into "ui-datatable-scrollable-header" the issue is fixed.

**Comment by nartc** [comment]
That is due to `ui-datatable-scrollable-header` having `overflow: hidden`. Purpose for this is out of my domain right now but if it's something that does not concern you. You can remove that `overflow: hidden`.

**Comment by JacobSiegle** [comment]
Thanks! Didn't have enough time to look into it yet also but can confirm changing the overflow does fix the issue, I overrode it in my component for now.

**Comment by cagataycivici** [comment]
Try appendTo="body" on Dropdown.

**Comment by deepblue1004** [comment]
this issue not solve if we set table zoom: 0.8

position of the dropdown not correct, due to <body> didn't apply "zoom"
