### ISSUE TITLE
Supporting Angular 4.4.6/5.0.0

### ISSUE THREAD

**Issue by OnlyAGhost** [primefaces/primeng#4371]
Has anyone seen the following error?:
Error: Object prototype may only be an Object or null: undefined
  Evaluating https://localhost:3443/node_modules/@angular/platform-browser/bundles/platform-browser-animations.umd.js

We had primeng working in Angular2, trying to upgrade to v4 or v5 and switching all the animations around seems to have screwed things up. We are importing BrowserAnimationsModule in our app.modules

Thanks!
Brian

**Comment by cagataycivici** [comment]
Please use forum for questions and support requests.
