### ISSUE TITLE
ProgressSpinner Module doesn't work

### ISSUE THREAD

**Issue by ambujkhanna** [primefaces/primeng#4373]
As per instruction I have imported module 
`import {ProgressSpinnerModule} from 'primeng/primeng';` 
and declared under "imports" but it shows me en error.

> [ts] Module '"d:/Projects/Staff_Assignment/StaffAssignment/node_modules/primeng/primeng"' has no exported member 'ProgressSpinnerModule'.

I am using PrimeNG Version 4.3.0

**Comment by cagataycivici** [comment]
Fixed in 5.0-RC0
