### ISSUE TITLE
Custom content after p-tabView tabs

### ISSUE THREAD

**Issue by AndreaBarbasso** [primefaces/primeng#4378]
**I'm submitting a ...**
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

I'd love to be able to add some custom content after the `p-tabView`'s tabs, floating the opposite way from them. It might be done the same way as the `p-dataTable`'s EmptyMessage:
```
<ng-template pTemplate="customcontent">
  Custom content goes here
</ng-template>
```
This is how it should render:
![alt text](https://i.imgur.com/jY8IJDY.png "View")

I did it on-the-go by adding the `ng-template` after the last `li`. Any chance of this happening? Thanks!

**Comment by yigitfindikli** [comment]
You can use ng-template pTemplate="content".
