### ISSUE TITLE
PickList: disabled property only on control buttons

### ISSUE THREAD

**Issue by pierfreeman** [primefaces/primeng#4380]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
Hi, first of all thanks for adding disabled property on the PickList, is really useful.

Another suggestion to enhance this component would be giving more control about this property, like having a more 'fine-grained' disabled on the control buttons.

One use case would be to disable the 'move-to-target' or 'move-to-source' buttons if a minimum or maximum value is reached on one of the two lists.

**Comment by stephanie-dm** [comment]
Another important thing to notice about this question is that it's not only the buttons that should be disabled in this example, but also moving items by double clicking or dragging them should not be possible anymore.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
