### ISSUE TITLE
Global filter only with displayed data

### ISSUE THREAD

**Issue by marcegige** [primefaces/primeng#4381]
Hello, I need to use global filter on p-dataTable, it works well, but it´s filtering by all attributes of the object received.
I only want to apply the filter on displayed data, because it´s displaying some rows that do not have the value passed on the input.

For example I have this:
{
 BookingId: 14671,
 Code: "TJDEXQ",
 ILN: 62008318,
 VendorLocator: "JJA",
 IssuingCountry: "ES"
}

I´m displaying in datatable only Code, ILN and IssuingCountry, when I apply the filter for example with value "14", the row who contains this object is displaying, because global filter evaluate the entire object.

How can I solve this? Any ideas? Thank you!

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
