### ISSUE TITLE
AutoComplete

### ISSUE THREAD

**Issue by guilhermedclima** [primefaces/primeng#4388]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
Good evening, I'm having problems with my autocomplete, it worked without problems.
but after updating the angular-cli he stopped showing the suggestions. but continues to call the api and the response returns successfully

**Comment by VinyP** [comment]
i've also have this issue. Temp fix is to go inside your Node Modules > primeng > components > autocomplete > autocomplete.js

Change:  if (this.panelEL && this.panelEL.nativeElement && this.loading) to 
                **if (this.panelEL && this.panelEL.nativeElement && this.loading === false)** 
`    AutoComplete.prototype.handleSuggestionsChange = function () {
        if (this.panelEL && this.panelEL.nativeElement && this.loading === false) {
            this.highlightOption = null;
            if (this._suggestions && this._suggestions.length) {
                this.noResults = false;
                this.show();
                this.suggestionsUpdated = true;
                if (this.autoHighlight) {
                    this.highlightOption = this._suggestions[0];
                }
            }
            else {
                this.noResults = true;
                if (this.emptyMessage) {
                    this.show();
                    this.suggestionsUpdated = true;
                }
                else {
                    this.hide();
                }
            }
        }
        this.loading = false;
    };`

**Comment by sudheerj** [comment]
Can you provide the environment details(Angular, CLI and PrimeNG versions). It would be helpful to replicate the issue with plunker example.

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=info
