### ISSUE TITLE
Update Chart.js dependency

### ISSUE THREAD

**Issue by AndreaBarbasso** [primefaces/primeng#4391]
**I'm submitting a ...**
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
The supported version of chart.js is 2.1.3, which has been released a year and a half ago. Since then, newer versions added a lot of options for customizability, and some critical bug fixes. Is it possible to upgrade to a newer version, if not to the latest (2.7.1)?

**Comment by sudheerj** [comment]
Earlier I tried with latest versions which works perfectly with PrimeNG.

**Comment by cagataycivici** [comment]
Updated 2.7.1 officially.
