### ISSUE TITLE
Frozen & unfrozen column headers height not synchronized

### ISSUE THREAD

**Issue by rkdvep** [primefaces/primeng#4393]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/NCt0ymuMjOfnQZVMgtmx?p=preview

**Current behavior**
When creating a table with frozen columns, and the frozen column headers need less height than the unfrozen column headers, the headers become unsynchronized.

**Expected behavior**
The frozen and unfrozen columns have the same height, regardless of header height requirements on either side.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/NCt0ymuMjOfnQZVMgtmx?p=preview

**What is the motivation / use case for changing the behavior?**
Table becomes much less useful if items on the left don't line up with items on the right.

**Please tell us about your environment:**

Windows 7, Visual Studio Code, NPM, NodeJS

* **Angular version:** 2.0.X

Angular 4.4.5

* **PrimeNG version:** 2.0.X

PrimeNG4.3.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
From the docs;

`
In this case, if frozen and scrollable cells have content with varying height, misalignment might occur. To avoid a performance hit, DataTable avoid expensive calculations to align the row heights as it can be easily done with CSS manually.
`

More info at DataTable docs.

**Comment by spence95** [comment]
vcxzvz
