### ISSUE TITLE
AutoComplete hijacks users control

### ISSUE THREAD

**Issue by Mysame** [primefaces/primeng#4395]
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://plnkr.co/edit/P4L7eGEIYJNTwiYyDr4j?p=preview

**Current behavior**
After inputting a valid value, it's impossible to escape the Autocomplete control.
Nor by tab nor by clicking anywhere else.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.4

* **PrimeNG version:** 4.3.0

* **Browser:** all

**Comment by cagataycivici** [comment]
Fixed in 5.0.0-RC0
