### ISSUE TITLE
Add headerCheckboxMode to DataTable

### ISSUE THREAD

**Issue by sgentile** [primefaces/primeng#4396]
If I filter the data, then select all with the headerCheckboxToggleAllPages enabled - it's setting the 'selection' to all the data, not all the data that matches the filter.

**Comment by cagataycivici** [comment]
This should be an option I guess like headerCheckboxMode="all|visible"

**Comment by vivekimsit** [comment]
@cagataycivici is there any workaround you can suggest?

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.

**Comment by vivekimsit** [comment]
@cagataycivici since there is no `5.1.0` but `5.2.0` can we assume it has been solved?
