### ISSUE TITLE
Autocomplete - paste via mouse doesn't work

### ISSUE THREAD

**Issue by danbanswer** [primefaces/primeng#4397]
To reproduce: 
Go to the autocomplete demo page (https://www.primefaces.org/primeng/#/autocomplete) 
Type an "a" in any of the autocomplete boxes. This works and the dropdown will show. Now copy the "a" and delete it (or cut it). 
Right click and choose "Paste" - the "a" appears but the dropdown doesn't open. 

If you paste via the keyboard the dropdown opens correctly.

This sounds very similar to a primefaces autocomplete bug: https://github.com/primefaces/primefaces/issues/831 which has apparently been fixed. Also somewhat similar to a primeng bug in the spinner: https://github.com/primefaces/primeng/issues/3970 . If it's appearing in two different components then it's very possible that it occurs in additional places.

**Comment by mmlitvin** [comment]
This is still a problem in both: Firefox and Chrome. Please provide the milestone for fixing this defect. Thank you

**Comment by mattfors** [comment]
@mmlitvin I've got a fix for this just haven't had time to make the change in prime's stuff. All it needs is an onPaste on the two input fields.

What I did for my project was to extend AutoComplete and call back into their keydown:
```
...
export class YourAutocompleteComponent extends AutoComplete {
  onPaste(event: ClipboardEvent) {
    this.onKeydown(event);
  }

}
...
```

Copy the entire @Component({}) and add the onPaste event to both input fields.
`(paste)="onPaste($event)"`
