### ISSUE TITLE
Usage question: OverlayPanel Inside a p-datatable

### ISSUE THREAD

**Issue by megetron** [primefaces/primeng#4398]
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ x] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Hi guys,
Just a small usage question of how can you use primeng overlayPanel inside a p-datatable.

I am trying to implement something similar to the editable [example](https://www.primefaces.org/primeng/#/datatable/editable) very similar to the date picker you see there.
The only change I would like to make is that instead open a datepicker control, it will open a cutom control I created (address picker).

So I just implement editable datatable and OnEdit I am trying to launch the overlaypanel (with the custom control in it).

but unfortunately, the overlaypanel in onEditInit is undefined, just struggling to make it work. share my code here, please advice:

```
<p-dataTable [value]="locations" [editable]="true" [responsive]="true" (onEditInit) ="onEditInit($event, op3)">
  <p-column field="address1" header="Address" [editable]="true" [style]=" {'overflow':'visible' }"  >
    <ng-template let-col let-location="rowData" letrowData pTemplate="body" let-i="rowIndex">
       {{ location.address1 }} 
    </ng-template>
   
    <ng-template let-location="rowData" pTemplate="editor" let-i="rowIndex">
       <p-overlayPanel #op3 appendTo="body">
         <sd-address formControlName="address1" name="address1" [(ngModel)]="locations[i].address1"></sd-address>
       </p-overlayPanel>
    </ng-template>
  </p-column>
</p-dataTable>


onEditInit(event, overlaypanel: OverlayPanel) {
  if(event.column.field == "address1")
    overlaypanel.toggle(event);
}
```

**Comment by cagataycivici** [comment]
Please use forums for questions and help requests.
