### ISSUE TITLE
Add a "dataProperty" property to p-column

### ISSUE THREAD

**Issue by ayush987goyal** [primefaces/primeng#4400]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
```

**Plunkr Case (Bug Reports)**

[https://embed.plnkr.co/iuuydN5JS2xi0tlQcJay/](https://embed.plnkr.co/iuuydN5JS2xi0tlQcJay/)

**Current behavior**
Right now when a column contains data in form of object ( example when templating), exporting the column will show [Object Object] in the CSV. Also the column filtering does not work in such cases.

**Expected behavior**
This new property can be used for exporting the data/filtering.

**Please tell us about your environment:**

* **Angular version:** 4.2.4

* **PrimeNG version:** 4.3.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =  7.6.0

**Comment by sudheerj** [comment]
In PrimeFaces, there was an exportFunction attribute for column tag to export customized data. May be similar property can be implemented here as well. But it is specific to export functionality and not include filtering support.

**Comment by cagataycivici** [comment]
Could be done with;

```
field="index.name"
```
