### ISSUE TITLE
RTL support for DataTable

### ISSUE THREAD

**Issue by webnegar** [primefaces/primeng#4402]
![datatable-rtl](https://user-images.githubusercontent.com/7112978/32599135-d57c3434-c550-11e7-863c-2bca08fd724c.png)

`<span class="ui-row-toggler fa fa-fw ui-clickable a-chevron-circle-left" ng-reflect-klass="ui-row-toggler fa fa-fw ui-cli" ng-reflect-ng-class="fa-chevron-circle-right"></span>`

correct: (fa-chevron-circle-righ)
`<span class="ui-row-toggler fa fa-fw ui-clickable fa-chevron-circle-right" ng-reflect-klass="ui-row-toggler fa fa-fw ui-cli" ng-reflect-ng-class="fa-chevron-circle-right"></span>`

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
