### ISSUE TITLE
Blur when clicking on autocomplete drop down buttton

### ISSUE THREAD

**Issue by urielTwito** [primefaces/primeng#4403]
**I'm submitting a ...**  

[x] bug report => Search github for a similar issue or PR before submitting
**Current behavior**
when using autocomplete 
<p-autoComplete> and clicking  on the drop down button I  get onBlur event.

if you open the devtools console you can  see that each time you click on the drop down button, a message is displayed in the console.

you can see this behavior 
here
 https://stackblitz.com/edit/angular-qzm6cx?file=app%2Fapp.component.html

**Comment by cagataycivici** [comment]
Yes, because dropdown button is a separate element causing a blur of input.
