### ISSUE TITLE
ViewEncapsulation.Emulated full support

### ISSUE THREAD

**Issue by AndreaBarbasso** [primefaces/primeng#4404]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Styling custom components containing primeng components via their .scss (or .css) files generated with angular-cli while in ViewEncapsulation.Emulated mode (angular's default) and imported in styleUrls is not safe.
The problem is about primeng's DOM manipulation and Angular's Shadow DOM emulation. Take a look at this screenshot:
![Screenshot](https://i.imgur.com/zG2Pzni.png)

As you can see, the behaviour is not clear at a first glance.
Angular calls viewEncapsulation's properties propagation at startup, and every time the DOM is manipulated using Angular elements. Every element you see with a `_ngcontent-c25` attribute is written directly inside `<p-_____>` tags. Those elements are then injected into the DOM via `<ng-content>` elements, so Angular knows that the DOM has been manipulated, knows that it is working in ViewEncapsulation.Emulated mode, then applies to those elements the `_ngcontent-xyz` attribute, where xyz is the last part of the first `_nghost-xyz` it encounters while navigating towards the document root.
All elements added later to the DOM by primeng via `appendChild` or similar are completely transparent to Angular, so they don't receive any attribute, thus not receiving any custom style relative to the parent's custom component.

**Expected behavior**
Primeng should apply those attributes by itself (as Angular does) every time some elements are injected into the DOM.

**What is the motivation / use case for changing the behavior?**
This would allow to use Angular's Emulated Shadow DOM in a completely transparent way, with no unexpected behaviour, adopting a clean way to write style rules.

**Comment by cagataycivici** [comment]
Which dom manipulation are you referring to?

**Comment by AndreaBarbasso** [comment]
Upon further investigation, in fact, it doesn't seem to be related to the Dialog's call of an `appendChild`, since the same problem is seen on the Fieldset, which does not have any `appendChild`s in it.
Let's just compare PrimeNG's Fieldset code, with the generated one (on plunkr, to avoid any environment-related error):

![Screenshot](https://i.imgur.com/N3kd2Ci.png)
[Plunkr](http://plnkr.co/edit/HMQF2pOisIf4KfKgvTmG?p=preview)

As you can see, the emulated DOM's attribute is applied only to the component root, and to everything in a `<ng-content>`, but everything else stays untouched. This is why I can't apply, for example (like in the plunkr), a border to `div.ui-fieldset-content`.

**Comment by AndreaBarbasso** [comment]
@cagataycivici do you have any thought on this?

**Comment by nanoTitan** [comment]
Any update on this?

PrimeNG seems like it should support the default Angular viewEncapsulation (emulated) out of the box. To my surprise, it seems like it doesn't. That requires a lot of hacks or work arounds that aren't optimal. One is using /deep or ng-deep which is deprecated. The other is to use ViewEncapsulation.None which is the same as making everything global. Neither is ideal.

**Comment by micdenny** [comment]
I'm confused, and concerned me too, in fact there's a lot of discussion down the `::ng-deep` keywork deprecation: https://github.com/angular/angular/issues/25160

What is clear is that to manipulate primeng styles we should use ::ng-deep because of what explained up here.

**Comment by cagataycivici** [comment]
PrimeNG 10 uses view encapsulation none, there is also a new guide on styling using the new theming system of 10.
