### ISSUE TITLE
When clicking on AutoComplete dropdown button it does not close other list

### ISSUE THREAD

**Issue by urielTwito** [primefaces/primeng#4405]
**I'm submitting a ...**  

[x] bug report => Search github for a similar issue or PR before submitting

**Current behavior**
When having 2 autoComplete controls on the same page 
 clicking on the first one drop down button causes  the list of values to opens (this is good)
 clicking on the second drop down button  causes the list of values to open (this is good)
    but it does not close the first list. this is the problem

**Expected behavior**
I expect the first list to be closed, 
this should be the same behavior as clicking on any other place on the page.

please look here to see it happens
https://stackblitz.com/edit/angular-qzm6cx?file=app%2Fapp.component.html

**Comment by cagataycivici** [comment]
Replicated
