### ISSUE TITLE
Carousel component runs angular change detection cycle

### ISSUE THREAD

**Issue by albertoml** [primefaces/primeng#4406]
**I'm submitting a ...**  (check one with "x")
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

Current behavior
In file carousel.js there is a function like this:

`Carousel.prototype.startAutoplay = function () {
        var _this = this;
        this.interval = setInterval(function () {
            if (_this.page === (_this.totalPages - 1))
                _this.setPage(0);
            else
                _this.setPage(_this.page + 1);
        }, this.autoplayInterval);
    };
`

This "setInterval" runs the angular change detection cycle, cause of this the protractor e2e tests never run and return time out, because protractor wait until all calls over angular zone finish.

Expected behavior
The "setInterval" function have to be in other zone using the library NgZone.

Minimal reproduction of the problem with instructions
My workaround proposed was create a e2e environment in angular and set the "autoplayInterval" property to empty value, with this value the setInterval function is not run
And in the rest environment set the value as you want.

What is the motivation / use case for changing the behavior?
This bug broke all protractor tests.

Angular version: 4.4.4
PrimeNG version: 4.2.1
Browser: all
Language: all

**Comment by cagataycivici** [comment]
But if we move it to runOutsideAngular then UI won't be updated.
