### ISSUE TITLE
open a special page with paginator

### ISSUE THREAD

**Issue by cyberrranger** [primefaces/primeng#4408]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/MUAr1vlV1whVJRHGqbXC?p=preview

**What is the motivation / use case for changing the behavior?**
Change the page from paginator with TS

**Please tell us about your environment:**
ALL

* **Angular version:** 4.X

* **PrimeNG version:** 4X

* **Browser:** [all]
 
more show https://forum.primefaces.org/viewtopic.php?f=35&t=52061&p=159083#p159083

**Comment by sudheerj** [comment]
Can you elaborate the description with version details in a required format. Otherwise it will be treated as invalid issue.

**Comment by cyberrranger** [comment]
@sudheerj done

**Comment by cagataycivici** [comment]
You can use first prop;

```
<p-paginator [first]="10" [rows]="10"
```

This will open the second page.

**Comment by cyberrranger** [comment]
now i understand, first is not the Page number, first is a item in the list, thx
