### ISSUE TITLE
[resizable] is not a property of <p-column> in dataTable

### ISSUE THREAD

**Issue by TaylorZaneKirk** [primefaces/primeng#4411]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

According to the docs (https://www.primefaces.org/primeng/#/datatable) under "Properties":

```
resizable | boolean | true | Whether the column is resizable when resizableColumns is enabled at DataTable.
```

However, including this property (tried as [resizable], resizable, (resizable), and *resizable) will crash the app and provide the following error:

```
Unhandled Promise rejection: Template parse errors:
Can't bind to 'resizable' since it isn't a known property of 'p-column'.
```

In the actual code of dataTable, the resizable property of the column is simply set to whatever the value of [resizableColumns] property of datatable instead of having the resizable property that the docs would seem to indicate should exist.

```
[ngClass]="{'ui-state-default ui-unselectable-text':true, 'ui-sortable-column': col.sortable, 'ui-state-active': dt.isSorted(col), 'ui-resizable-column': dt.resizableColumns, 'ui-selection-column':col.selectionMode,
                            'ui-helper-hidden': col.hidden}"
```

**Expected behavior**

I would like to see either the docs be changed to reflect what can actually be done/used

or, even better,

I would like for [resizable] to be implemented as the docs seem to suggest

**Minimal reproduction of the problem with instructions**

Demo:
http://plnkr.co/edit/dUBTR9vqC3CpO69Y9UrH?p=preview

**What is the motivation / use case for changing the behavior?**

Documentation should reflect functionality

* **PrimeNG version:** 3.10.10

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome, latest

**Comment by cagataycivici** [comment]
You need PrimeNG 5.0.0-RC for this.
