### ISSUE TITLE
Built application includes all PrimeNG modules (even unused ones)

### ISSUE THREAD

**Issue by fibinger** [primefaces/primeng#4412]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
I use Angular CLI (v1.5.0) to build my application. Generated vendor.bundle.js asset is much bigger then previously (before version 5.0.0-RC0), because it includes every single PrimeNG module:
![image](https://user-images.githubusercontent.com/1809787/32632233-20db1984-c5a3-11e7-841f-0511d6fd3235.png)

**Expected behavior**
It should contain only those PrimeNG modules included in the project, in version 4.* for me it was looking like that:
![image](https://user-images.githubusercontent.com/1809787/32632301-61cae622-c5a3-11e7-8038-948a48e86566.png)

**What is the motivation / use case for changing the behavior?**
Keeping the application as small as possible.

* **Angular version:** 5.0.0-rc0

* **PrimeNG version:** 5.0.0-RC0

* **Language:** [TypeScript 2.4.2]

* **Node (for AoT issues):** `node --version` =  6.11.4

**Comment by dzhavat** [comment]
I “suffered” from the same thing. Turns out if you just import from `primeng/primeng` the final bundle with include some stuff you haven't used. I fixed that by including directly the components that I was using. Something line 

`import { DataTableModule } from 'primeng/components/datatable/datatable';`

Sure it's a bit more hassle but now I don't include the whole “jungle” :D 

You can also refer to this [post in the forum](https://forum.primefaces.org/viewtopic.php?p=160826#p160826).

**Comment by fibinger** [comment]
@dzhavat you are absolutely right. It worked! :)
Quite annoying IDEs are suggesting barrel imports by default, so it's necessary to amend those imports manually, but it's worth doing it anyway.

Thanks.

**Comment by cagataycivici** [comment]
We'll update the docs import section to include the actual path to avoid future issues.

**Comment by xdavipereira** [comment]
hi
i was wondering if with new versions the problem continue or is safe to use what is said in the docs
that way 

`import {TableModule} from 'primeng/table';`

or 

`import {TableModule} from 'primeng/components/table/table'`

Can I use `import { TableModule } from 'primeng/primeng';` on ^6.1.4 version or is there the same problem?

**Comment by UesleyCarossi** [comment]
Using version 9, this form of import (import {TableModule} from 'primeng/components/table/table') is no longer implemented, leaving only this form (import {TableModule} from 'primeng/table') that ends up compiling all modules.

Any solution?

**Comment by fheinz7** [comment]
> Using version 9, this form of import (import {TableModule} from 'primeng/components/table/table') is no longer implemented, leaving only this form (import {TableModule} from 'primeng/table') that ends up compiling all modules.
> 
> Any solution?

I have the same problem

**Comment by faizangithub-tech** [comment]
> > Using version 9, this form of import (import {TableModule} from 'primeng/components/table/table') is no longer implemented, leaving only this form (import {TableModule} from 'primeng/table') that ends up compiling all modules.
> > Any solution?
> 
> I have the same problem

>i am facing a same problem it tooks 5 mins to compile all of modules ..

**Comment by Olmer1st** [comment]
Hi,
I have the same issue, 5mb bundle size, it's exeed all budget limits.

**Comment by KrakenZ** [comment]
any news on this?
