### ISSUE TITLE
Custom Sorting is not working?

### ISSUE THREAD

**Issue by viveknuna** [primefaces/primeng#4413]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Custom Sorting is not working, It's not even calling mysort function.
I have a column named as Name which is varchar in DB, Name can be alphanumeric, numeric or only alphabetical.

`<div class="primeng-datatable-container text-center"
                         [busyIf]="primengDatatableHelper.isLoading">
                        <p-dataTable #dataTable
                                     (onLazyLoad)="searchTaxtest($event)"
                                     [value]="primengDatatableHelper.records"
                                     rows="{{primengDatatableHelper.defaultRecordsCountPerPage}}"
                                     [paginator]="false"
                                     [lazy]="true"
                                     emptyMessage="{{l('NoResultsFound')}}"
                                     ScrollWidth="100%"
                                     responsive="primengDatatableHelper.isResponsive"
                                     resizableColumns="primengDatatableHelper.resizableColumns">
                            <p-column field="testCode" header="{{l('Code')}}" [sortable]="custom" (sortFunction)="mysort($event)" [style]="{'width':'25%', 'text-align':'left'}"></p-column>
                            <p-column field="testName" header="{{l('Name')}}" [sortable]="true" [style]="{'width':'25%', 'text-align':'left'}"></p-column>
                            <p-column field="testDesc" header="{{l('Description')}}" [sortable]="true" [style]="{'width':'35%', 'text-align':'left'}"></p-column>
                            <p-column field="" header="{{l('Actions')}}" [sortable]="false" [style]="{'width':'15%'}">
                                <ng-template let-record="rowData" pTemplate="body">
                                    <div class="clear-fix">
                                        <button class="btn btn-xs btn-primary" (click)="taxtest.edittest(record)"> <i class="fa fa-edit"></i></button>
                                        <button class="btn btn-xs btn-danger" (click)="onDeleteClick(record, $event)"><i class="fa fa-trash-o"></i></button>
                                    </div>
                                </ng-template>
                            </p-column>
                        </p-dataTable>
                        <div class="primeng-paging-container">
                            <p-paginator rows="{{primengDatatableHelper.defaultRecordsCountPerPage}}"
                                         #paginator
                                         (onPageChange)="searchTaxtest($event)"
                                         [totalRecords]="primengDatatableHelper.totalRecordsCount"
                                         [rowsPerPageOptions]="primengDatatableHelper.predefinedRecordsCountPerPage">
                            </p-paginator>
                            <span class="total-records-count">
                                {{l('TotalRecordsCount', primengDatatableHelper.totalRecordsCount)}}
                            </span>
                        </div>
                    </div>` 
`mysort(event) {
        console.log(event);
        let comparer = function (a, b): number {
            let result: number = -1;

            if (a > b) result = 1;
            return result * event.order;
        };

        this.primengDatatableHelper.records.sort(comparer);
        //event.field = Field to sort
        //event.order = Sort order
    }`

**Expected behavior**
Custom Sorting should work for all the datatype.

* **Angular version:** 4.3.1

* **PrimeNG version:** 4.1.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=info
