### ISSUE TITLE
Modal with custom header and footer does not scale properly

### ISSUE THREAD

**Issue by Lolash** [primefaces/primeng#4420]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/vOb8jjCqconCwNLrWvZQ?p=preview

**Current behavior**
When I create a modal with custom header and footer - using p-header and p-footer elements, on lower resolutions(e.g. mobile) footer is not visible. Please take a look at Plunker and reduce the size of the window.

**Expected behavior**
Scaling mechanism of the window should take custom header and footer into consideration.

* **Angular version:**
4.4.*

* **PrimeNG version:**
4.3.*

* **Browser:** [all]

**Comment by yigitfindikli** [comment]
Unable to replicate with latest PrimeNG, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
