### ISSUE TITLE
ContextMenu should not disappear on clicking on a disabled menu item

### ISSUE THREAD

**Issue by Deilan** [primefaces/primeng#4422]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
`ContextMenu` disappears on clicking on it's disabled menu item.

**Expected behavior**
`ContextMenu` doesn't disappear on clicking on it's disabled menu item.

**What is the motivation / use case for changing the behavior?**
The current behavior contradicts the generally accepted UX.

**PrimeNG version:**
4.3.0

**Comment by sudheerj** [comment]
As of now, the contextmenu toggles based on the click event anywhere in the document excepts the target button component.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
