### ISSUE TITLE
Routing animations with dataList

### ISSUE THREAD

**Issue by bchampion** [primefaces/primeng#4426]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)** (use Chrome)
https://plnkr.co/edit/4ZChcdFnZsffi2Wc7MdH?p=preview

**Current behavior**
As you can try on the plunkr (link above), when I click on "Page" link, it routes to Page component with a ":leave" transition.
The transition works fine but the dataList's content disapear. It keeps the "li" tag but lose the rest.
Can be reproduced with dataScroll.

**Expected behavior**
The content should stay until the end of the animation.

**Minimal reproduction of the problem with instructions**
Cf. Above plunkr

**What is the motivation / use case for changing the behavior?**
Add routing animations with dataList.

* **Angular version:** 4.2.4

* **PrimeNG version:** 4.2.2

* **Browser:** 
[Chrome ]
 
* **Language:** 
[TypeScript]

* **Node (for AoT issues):** `node --version` =   v6.3.0

**Comment by cagataycivici** [comment]
Not sure how we can resolve this, pTemplateWrapper destroys the view to avoid memory leaks but it seems Angular calls it immediately on animation starts.
