### ISSUE TITLE
Whether to support the Chinese version?

### ISSUE THREAD

**Issue by badounan** [primefaces/primeng#4429]
I want to use primeng.

Whether to support the Chinese version? 

Is there a Chinese language pack?

**Comment by sudheerj** [comment]
Are you expecting Chinese version for all component labels. As of now there is no chinese language pack.There is one request on Autocomplete component as well. https://github.com/primefaces/primeng/issues/1318

**Comment by cagataycivici** [comment]
Please use forum for questions.
