### ISSUE TITLE
Cannot override legend styling in fieldset

### ISSUE THREAD

**Issue by Chadley08** [primefaces/primeng#443]
I have a fieldset with a legend. I want to change the legend styling so that it is centered above the content. I have tried using a CSS selector on .ui-fieldset.legend but it seems to have no effect. I can manually change the margins (setting left and right to auto) in the Chrome dev tools to see the desired effect.

Is there a way to override the legend styling?

**Comment by cagataycivici** [comment]
Where do you write the css, try ViewEncapsulation.NONE in your component.

**Comment by bsanders1979** [comment]
Having the same issue here, but with <fieldset>. The issue for me is that I have an external CSS file (css.css.js) which transforms .ui-fieldset into .ui-fieldset[_ngcontent-%COMP%]. However, <fieldset> does not have the _ngcontent attribute, only <p-fieldset>. Applying like so works: [style]='{...}'

**Comment by Chadley08** [comment]
Ok, I will try cagataycivici's approach above and get back to you.

**Comment by cagataycivici** [comment]
No issue on our side, this is related to style scoping, ViewEncapsulation to NONE will work.
