### ISSUE TITLE
RTL support for Dropdown

### ISSUE THREAD

**Issue by SNouri2005** [primefaces/primeng#4433]
hi 
primeng dropdown not support for rtl direction??

**Comment by eetty** [comment]
I need it also. thank you!

**Comment by eetty** [comment]
multiselect also in plan? also needed

**Comment by jwhijazi** [comment]
still not supported right?

**Comment by jwhijazi** [comment]
still not supported right?

**Comment by tamitam** [comment]
Any answer??? Also need this...

**Comment by riva-dev** [comment]
Is there is a css that I can use meanwhile?
this **DOESN'T** work for me
```
:host>>> .ui-dropdown-panel .ui-dropdown-item{
  text-align: right;
  font-size: 12px;
}
```

**Comment by eliafengar** [comment]
+1 Here, The RTL Option for DropDown is not working

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
