### ISSUE TITLE
onAfterShow does not fire for modal dialogs

### ISSUE THREAD

**Issue by Chadley08** [primefaces/primeng#444]
The onAfterShow event is not working for modal dialogs. The event never fires. I have it wired up the same way as my onBeforeShow event which is working fine.

**Comment by Mario-Eis** [comment]
True, same problem here! It only fires when the ESC button is used to close the modal.

**Comment by howlettt** [comment]
+1

**Comment by cagataycivici** [comment]
Unable to replicate with 2.0.x.
