### ISSUE TITLE
Datatable should scroll horizontally as needed when reordering columns

### ISSUE THREAD

**Issue by danbanswer** [primefaces/primeng#4445]
**I'm submitting a ...**

[X] bug report

**Plunkr Case**
http://plnkr.co/edit/TNXPdzeS48iT24KIeUnx?p=preview

**Description**
If you have a datatable with reorderableColumns=true and with a horizontal scrollbar and you try to drag a column past the visible edge of the datatable, the datatable should scroll to let you drop it after columns that aren't currently visible (see the plunkr)

Reproduced in latest Chrome and Firefox for Mac (10.13.1) and Chrome for Windows 10. Didn't try other environments.

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
