### ISSUE TITLE
stop cell data from overlapping other cells

### ISSUE THREAD

**Issue by nat2k5us** [primefaces/primeng#4446]
http://plnkr.co/edit/Wh6bfj6Q4cuPVUFdIFcb?p=preview

Look at the first cell in the Plunker - the data overflows into the next cell.

**Comment by nat2k5us** [comment]
Fixed by setting the  overflow to hidden on the column
<p-column field="enterImage" header="Enter" [editable]="true" [style]=" {'overflow':'hidden' }" ></p-column>

**Comment by sudheerj** [comment]
By default the table data will be wrapped. Since you are using scrollable table with different width columns the content is overlapped.

![image](https://user-images.githubusercontent.com/3127317/32924063-d8b83ad2-cb75-11e7-8d2e-518f3a66a885.png)

**Comment by ctrl-brk** [comment]
You can also make this behavior global. That's what I use:
`.ui-datatable .ui-datatable-data>tr>td {overflow: hidden; text-overflow: ellipsis; white-space: nowrap}`

**Comment by Hadas97** [comment]
I have the same problem just with primeng turbo table, I tried to add  [style]=" {'overflow':'hidden' }" to - <tr>, <td>, and even to <div>(cus turbo table doesnt have p-column element.. ) but none of them solved the problem.. 
anyone know how to solve it?

**Comment by viswa-optimusprime** [comment]
i have same problem in cell overlapping with turbo table ? How to solve it?
