### ISSUE TITLE
DataTable - Filter - Piping values breaks filter 

### ISSUE THREAD

**Issue by billiaug** [primefaces/primeng#4447]
Adding a filter pipe to the table values breaks the filter. 
Filter still works but with the old, initial value format.

`<p-column [filter]="true" field="date" filterPlaceholder="Date" [sortable]="true">
        <ng-template let-cell="rowData" pTemplate="body">{{cell.date | date:'dd/MM/y' }}</ng-template>
    </p-column>`

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
