### ISSUE TITLE
DataTable.reset() shouldn't reset the sortOrder to 1

### ISSUE THREAD

**Issue by kito99** [primefaces/primeng#4451]
Unless I'm mistaking the intention of this method, I would expect the `sortOrder` to be set to the original value set in the template. 

https://github.com/primefaces/primeng/blob/a4dfda18bd605bd76c7b3232b6db5add135b3ece/src/app/components/datatable/datatable.ts#L2495

This causes a problem if you have initialized the `sortOrder` to a value and call `reset()`, expecting it to return the original value.

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
