### ISSUE TITLE
Datatable & ngModel on the same page = performance issues

### ISSUE THREAD

**Issue by ctrl-brk** [primefaces/primeng#4452]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/AgzXCYSkXFmPev5zmHhd?p=preview

**Current behavior**
When there's a datatable with some decent number of rows and you are starting to type into some input control bound to ngModel there are noticeable delays during typing.
If the input field is not bound then everything is normal.

**Expected behavior**
There should be no delays caused by Datatable when entering data

**Minimal reproduction of the problem with instructions**
Use plunker and try to quickly type in the two fields there. Notice the difference.

**Comment by cagataycivici** [comment]
Try PUSH change detection on the DataTable part so typing does not trigger a change detection on DataTable.

**Comment by ctrl-brk** [comment]
@cagataycivici And how do I do that? Could you update the plunker please?

**Comment by ctrl-brk** [comment]
Ok. OnPush helps a bit but there's filtering issue I reported here: https://github.com/primefaces/primeng/issues/4501

But the performance in general is still an issue. There are just 3000 records - it's not that many at all but you can experience significant delays on initial load and filtering.
