### ISSUE TITLE
document typo in listbox api

### ISSUE THREAD

**Issue by ReDragon710** [primefaces/primeng#4455]
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
in the listbox API documentation, there is a typo in the properties
there is no propery name listStyle and there are two 'style' properties, in the example it is clear that there are 'style' and 'listStyle' properties.

**Expected behavior**
the documentation should have 'style' and 'listStyle' properties.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
fix documentation

**Comment by ReDragon710** [comment]
![listbox-code](https://user-images.githubusercontent.com/12182798/32884148-1086b380-cac2-11e7-9c82-ec3e0f7c6efa.png)
![listbox-doc](https://user-images.githubusercontent.com/12182798/32884149-10a18156-cac2-11e7-8464-94718b67ba06.png)

**Comment by sudheerj** [comment]
Fixed,Thanks.
