### ISSUE TITLE
onUpload function is not working!

### ISSUE THREAD

**Issue by Iamguy84** [primefaces/primeng#4456]
Hi Folks,

```
<h3 class="first">Advanced</h3>
<p-fileUpload name="demo[]" url="./upload.php" (onUpload)="onUploadHandler($event)" multiple="multiple" accept="image/*" maxFileSize="1000000">
    <ng-template pTemplate type="content">
        <ul *ngIf="uploadedFiles.length">
            <li *ngFor="let file of uploadedFiles">{{file.name}} - {{file.size}} bytes</li>
        </ul>
    </ng-template>
</p-fileUpload>
```

```
  onUploadHandler(event:any) {
    alert('test');
      for(let file of event.files) {
          this.uploadedFiles.push(file);
      }
  }
```

 onUploadHandler function is not working. what's wrong?
 I am using PrimeNG - ^5.0.0-rc.0. Any idea?

**Comment by sudheerj** [comment]
I can't replicate the issue in showcase. Can you please provide the plunker example.

**Comment by Iamguy84** [comment]
Plunker is not good thing to me and too slow. But I have downloaded sample QuickStart with Webpack from https://github.com/primefaces/primeng-quickstart-webpack and changed something code. 
Please check your gmail.
Thanks

**Comment by Iamguy84** [comment]
@sudheerj Your gmail is not working.
I got message and it says:
"Your message wasn't delivered because the recipient's email provider rejected it."
Please correct your email address!

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=info

**Comment by Iamguy84** [comment]
ok. Please review it as below:
http://embed.plnkr.co/xeFMJJ90OdgBteIeVIGz/

**Comment by Iamguy84** [comment]
Any news?
