### ISSUE TITLE
Please add a search in API Documentation to your website

### ISSUE THREAD

**Issue by eladcandroid** [primefaces/primeng#4459]

**Comment by uditalias** [comment]
+1

**Comment by sudheerj** [comment]
Is it for finding the component or any keyword search?

**Comment by eladcandroid** [comment]
@sudheerj  
Something like the search in GitBook 
(for example: https://swimlane.gitbooks.io/ngx-datatable/content/)

**Comment by eladcandroid** [comment]
Any good news?

**Comment by cagataycivici** [comment]
No, we're busy with other tasks, feel free to contribute with a PR.
