### ISSUE TITLE
Padding solution of hours minutes and seconds in calendar is weird

### ISSUE THREAD

**Issue by Franky238** [primefaces/primeng#4460]
**I'm submitting a ...** 
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Problem**
```
<div class="ui-hour-picker">
  <a href="#" (click)="incrementHour($event)">
    <span class="fa fa-angle-up"></span>
  </a>
  <span [ngStyle]="{'display': currentHour < 10 ? 'inline': 'none'}">0</span>
  <span>{{currentHour}}</span>
  <a href="#" (click)="decrementHour($event)">
    <span class="fa fa-angle-down"></span>
   </a>
</div>
```
I am pointing on implementation of this part of code. This solution is used for hours, minutes and seconds. Why `<span [ngStyle]="{'display': currentHour < 10 ? 'inline': 'none'}">0</span>` is used as padding? In javascript can be used better solutions. It will be better testable (like selenium and other).

**Current behavior**
Solution of padding time numbers is weird and bad testable.

**Expected behavior**
Do not use `span` with `display: none` for padding of numbers

**Comment by yigitfindikli** [comment]
Unable to replicate with latest PrimeNG, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
