### ISSUE TITLE
Datatable scrollHeight can't be changed

### ISSUE THREAD

**Issue by filip12345678910** [primefaces/primeng#4461]
**I'm submitting a ...**

[x] bug report
[ ] feature request
[ ] support request

**Plunkr Case (Bug Reports)**

http://plnkr.co/edit/nglMn9zwXskBZNHD59wv?p=preview

**Current behavior**
The datatable height stays the same despite changing scrollHeight.

**Expected behavior**
Change the height.

**Please tell us about your environment:**
Windows 10

* **Angular version:** 4.3.6

* **PrimeNG version:** 5.0.0-rc.0
It used to work, I think it was 4.1.0.

* **Browser:** [Chrome|Firefox ]
 
* **Language:** [ TypeScript ]

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.

**Comment by birjega** [comment]
The problem still persists in p-table. --> changing the value for scrollHeight should work. 
We need "public" access to setScrollHeight().

**Comment by rxjucse** [comment]
Facing same issue. New p-table also doesn't support bind dynamic value in scrollHeight

**Comment by birjega** [comment]
Upgrade to latest version. It works now. Make scrollHeight variable and use css calc() for value on a change window height event.

**Comment by rxjucse** [comment]
Thanks. Solved with the new update table

**Comment by misan128** [comment]
I'm having an issue when updating the totalRecords prop of the TurboTable via http response subscriptions. I have binded the totalRecords to a component poperty initialized to 0 and when I get the data I update the value of totalRecords but the table doesn't change its height. Any Ideas of how to workaround this?
