### ISSUE TITLE
OverlayPanel doesn't show anymore

### ISSUE THREAD

**Issue by FLNacif** [primefaces/primeng#4462]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

Plunker: http://plnkr.co/edit/sfA61yCxuyj0LffojHus?p=preview

**Current behavior**
The overlaypanel component doesn't show up anymore. Looking to the HTML at the console seems that the display property isn't being updated even though it has the bind. It used to work a few time ago.

**Expected behavior**
When you call the toggle function the overlaypanel should appear.

**Minimal reproduction of the problem with instructions**
When a trigger the overlaypanel component it doesn't show up at the screen.

**Please tell us about your environment:**
PrimeNG version 4.3.0 in Chrome Browser
* **Angular version:** 2.0.X
Angular version 4

* **PrimeNG version:** 2.0.X
PrimeNG version 4.3.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by rkdvep** [comment]
The issue is the overlayPanel custom style, removing it fixes the issue

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=info

**Comment by FLNacif** [comment]
I provided a plunker in the issue opening. Is it not available?
@rkdvep Your solution worked, but I want to position the panel just above an icon, and the only solution I found was that. Any advice?
Thank you

**Comment by rkdvep** [comment]
@FLNacif you can pass a target argument with the toggle method. however, this only works in-html. example: http://plnkr.co/edit/hB37itsJeqngZy8dkOaJ

and your plunker is not based on the official plunker as far as I can see, so I think he wants you to use that!

**Comment by aminecmi** [comment]
@rkdvep I'm having the exact same issue. 
The problem is only occurring on the 5.0.0-rc.0 version, and was working fine on 4.1.3.

Is there any way to still apply custom style to the panel ?
