### ISSUE TITLE
Tree component parent expand not working always

### ISSUE THREAD

**Issue by Hesesses** [primefaces/primeng#4464]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
I want to expand a node when new child is added as child

**Current behavior**
The parent node is expanded only if there are child nodes already

**Expected behavior**
The parent node is expanded always when using .expand() 

* **Angular version:** 4.4.6
* **PrimeNG version:** 4.3.0

```
<tree-root [nodes]="levels" [options]="treeOptions"
        (moveNode)="onMoveNode($event)"
        (activate)="onActivate($event)"
        (deactivate)="onDeactivate($event)"
        (event)="onEvent($event)"
      >
        <ng-template #treeNodeTemplate let-node="node" let-index="index">
          <div class="level">
            {{ node.data.name }}
            <button class="btn btn-sm btn-success float-right" (click)="addLevel(node)"><i class="fa fa-plus"></i></button>
          </div>

        </ng-template>
      </tree-root>

addLevel(parent) {
    let newLevel = {
      level_id: parent.data.id,
      name: parent.data.name + " copy",
    };

    this.levelService.addLevel(newLevel)
      .then(level => {
        parent.data.children = parent.data.children || [];
        parent.data.children.push(level.data);

        parent.expand();
        this.tree.treeModel.update();
      });
  }
```

See video:
https://www.useloom.com/share/ce8709b4a27448e7a2eb0f56bbc92ad2

**Comment by cagataycivici** [comment]
Where is the expand method?

**Comment by Hesesses** [comment]
@cagataycivici its a method for treenode

**Comment by Hesesses** [comment]
Any ideas?

**Comment by cagataycivici** [comment]
Provide a plunkr please;

http://plnkr.co/edit/Q5hZgBA6DlXf55UvyVqw?p=preview

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
