### ISSUE TITLE
Multiselect improvements

### ISSUE THREAD

**Issue by ova2** [primefaces/primeng#447]
The Multiselect component http://www.primefaces.org/primeng/#/multiselect is a great one (this is what we missed in PrimeFaces!).

But it needs to be improved. I will try to summarize the issues:
- Key navigation doesn't work in the popup (you can navigate and select checkboxes by arrow keys and space / enter key)
- The more items selected, the more grows the input field. It can be very long and looks ugly. I suggest to set the fixed length (layout is not broken then). If some items not fit the available length (visible space), they should be displayed as ... (ellipses). This is what our UX and interaction designer prefer.
- Selected items are shown comma separated as e.g. `Audi,Fiat,Ford,...` There are no space after comma. Can you show them please as `Audi, Fiat, Ford, ...`

One question yet. I haven't tried, but do nested items supported too? You know, you can create nested SelectItem's in JSF :-). There SelectItem and SelectItemGroup in JSF.

Thanks!

**Comment by rahuja910** [comment]
+1 
In addition to the above I would also suggest having the option of making multiselect do a "contains" search rather than a "begins with" search.

Thanks

**Comment by ova2** [comment]
Search mode should be configurable. I'm personally don't need search at all. The most worst thing is the growing of the select field when you choose more and more items. That breaks the layout and moves the multiselect to the next row in the grid system, etc. A fix width aligned to other inputs / selects is always the best UI. We developed an own multiselect which shows ... (ellipses) when more items are available.

**Comment by mmakarios** [comment]
@ova2 Your modified multiselect is publicly available? I'm struggling with this since I have a lot of columns.

Thanks!

**Comment by michalig** [comment]
@mmakarios I did something that can help you - I described it here in details:
https://github.com/primefaces/primeng/issues/987

It's not in the main codebase unfortunately...

**Comment by cagataycivici** [comment]
Please create separate tickets so we can handle each case one by one.

**Comment by ova2** [comment]
Created all three issues listed above.
