### ISSUE TITLE
using a router to switch tab contents with PrimeNg Dialog and TabMenu does not seem to work like it did with angular 4

### ISSUE THREAD

**Issue by markuswurtz** [primefaces/primeng#4473]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

relevant components are Dialog and TabMenu from primeng and Router from angular 
here are the relevant code samples.

```
export class ModalComponent {
  menuItems: MenuItem[];
  ngOnInit()
  {
     this.menuItems = [
            { label: 'Login', routerLink: ['login'] },
            { label: 'Register', routerLink: ['register'] }
        ];
    }
}
```

```
path: 'auth', component: ModalComponent, outlet: 'modal',
        children: [
            { path: '', component: LoginFormComponent },
            { path: 'register', component: RegistrationFormComponent},
            { path: 'login', component: LoginFormComponent}
        ]

```
```
<p-dialog [showHeader]="false" [(visible)]="display" (onHide)="onHide()" [modal]="true"[dismissableMask]="true" [resizable]="false">

        <p-tabMenu [model]="menuItems" [activeItem]="menuItems[0]"></p-tabMenu>
        <router-outlet></router-outlet>
    </p-dialog>
```

**Current behavior**
The dialog opens on a default tab as expected, when I navigate to the second tab the contents of the first tab stay, but the second tab contents display above the first.
I'm posting this as a bug because before I updated to angular 5 it was working as expected.

**Expected behavior**
I expect the contents of the second tab to replace the first tabs contents

**Minimal reproduction of the problem with instructions**

Steps to reproduce would be to use a Dialog with a TabMenu component for navigation and to use a router to display whatever you want based on which tab you are on.

**What is the motivation / use case for changing the behavior?**
I'm attempting to implement a login/register form as a modal.

**Please tell us about your environment:**

* **Angular version:** 5.0.0

* **PrimeNG version:** 5.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
I believe it happens on all browsers, I tested Chrome, FireFox, and Edge
 
* **Language:** [TypeScript 2.4.2]

**Comment by jhonnathan78** [comment]
Same thing happens on my end with the megamenu but I get no errors in the console.

**Comment by jhonnathan78** [comment]
Ok so it looks like the routerLink property only works on child items. That is how the template for the component was built, that sucks! We should be able to link to a component from a parent item as well. What if I don't have any children items and I just want the user to click the main item.
