### ISSUE TITLE
Menubar doesn't show submenus on Android

### ISSUE THREAD

**Issue by patrickgdl** [primefaces/primeng#4477]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report 
```

**Plunkr Case (Bug Reports)**
Check this plunkr with Chrome's mobile view.

http://plnkr.co/edit/RTya1JBmo33TjTxhlJsx?p=preview

or the showcase on Android's chrome:

https://www.primefaces.org/primeng/#/menubar

**Current behavior**
On clicking menu with submenus nothing happens

**Expected behavior**
Submenus appears.

**Minimal reproduction of the problem with instructions**
Z-index does not work. Maybe another option.

* **Angular version:** 4.1.3

* **PrimeNG version:** 4.3.0

* **Browser:** [Chrome 62 | Mobile Chrome 62 ]
 
* **Language:** [TypeScript 2.4]

**Comment by skidrou** [comment]
This problem has already been mentioned several times but without due attention. It is a serious problem for those who use PrimeNG focused on mobile web. Please, check it.

**Comment by skidrou** [comment]
The workaround I found was remove the `this.activeItem = null;` from the `menubar.ts` function `itemClick()` and `listClick()`. I don't kwow if it was the best practice, but work for me.

**Comment by gmdvdv** [comment]
Yes, menu on Android don't work (
see there https://chatapp-ebf48.firebaseapp.com/

**Comment by doomevaristo** [comment]
Same problem here, had to waste some hours on workarounds to develop another component for mobile resolutions.

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
