### ISSUE TITLE
DataTable (onLazyLoad) [sortable] does not function

### ISSUE THREAD

**Issue by supermoon123** [primefaces/primeng#4479]
[ x ] bug report

Plunkr Case (Bug Reports)
https://plnkr.co/edit/13Wxqakyqj4cdgnSVijk?p=preview

Current behavior
dataTable with onLazyLoad [sortable] field does not function

Expected behavior
1.) dataTable with onLazyLoad [sortable] should sort results

Minimal reproduction of the problem with instructions
https://plnkr.co/edit/13Wxqakyqj4cdgnSVijk?p=preview

1.) Run plnkr project
2.) click column Id to sort field

What is the motivation / use case for changing the behavior?
1.) Accuracy in sorting records displaying

Please tell us about your environment:

Angular version: 5.0.`

PrimeNG version: 5.0.

Language: [all | TypeScript X.X | ES6/7 | ES5]

**Comment by cagataycivici** [comment]
You have a misunderstanding, in lazy mode you have to implement filtering at backend yourself.
