### ISSUE TITLE
OverlayPanel Positioning

### ISSUE THREAD

**Issue by bohms27** [primefaces/primeng#448]
Right now, the overlay panel always appears below and to the right of the target div no matter where the div is on the page. I would like to request an option for it to appear to the left if there is not enough screen real estate on the right side. More of a "dynamic positioning" of the overlay panel instead of always appearing below and to the right. 

As a temporary fix, implementing an option to make the panel appear to the left OR right based on the setting would be great.

**Comment by izll** [comment]
+1

**Comment by MarcelCremer** [comment]
+1

**Comment by adenizc** [comment]
+1

**Comment by skdhir** [comment]
+1

**Comment by alexandr8558** [comment]
+1 
It would be perfect if we can do something like

<p-overlayPanel [position]="bottom-center"> 
</p-overlayPanel>

top | bottom | rigth | left -> this will force the overlay panel to show there. This Feature is lesser important than the next one.
left | center | rigth -> this will "move" the overlay panel in X axys to display centered relative to its parent. rigth is your default value . Its like changing left attribute of ui-overlaypanel manually.

**Comment by cagataycivici** [comment]
Try with 4.x please, it has collision detection improvements.

**Comment by zfanning** [comment]
Tried it with 4.x and same result. Is there not a way to specify top/bottom, left/right?

**Comment by zfanning** [comment]
Problem was that it is bigger than the "container" which was a component. Changing the aboslutePosition prototype code fixed the issue. I think that the logic in that function needs to be updated. I'll try tonight and submit a PR. (I have no idea how to contribute, I'll have to do some research on that as well)

**Comment by BustyLoli-Chan** [comment]
Is there still no way to do this? 
I've just started looking at primeNG as it's being adopted for use in our company and I want to be able to use the overlay because it looks amazing, however because of where it shows up on the page and because of various resolutions we support, the panel actually ends up being cut off.

**Comment by prashantbirajdar** [comment]
+1

**Comment by StatikVerse** [comment]
This is probably hard to do. Lol.

**Comment by dhniels** [comment]
Relates to https://github.com/primefaces/primeng/issues/2567

**Comment by jbermanwebguru** [comment]
I fixed this by creating a div element with a certain size, and using that as the target when opening the overlay. 

```html
<div
  #overlayTarget
  style="width: 200px; height: 30px; margin-top: -30px;"
></div>
```

```typescript
export class MyComponent {
  @ViewChild('overlayTarget')
  overlayTarget: ElementRef;

  @ViewChild('myDialog')
  myDialog: OverlayPanel;

  @HostListener('click', ['$event'])
  onClick(event: MouseEvent) {
    this.myDialog.show(event, this.overlayTarget.nativeElement);
  }
}
```

**Comment by buseodaci** [comment]
> I fixed this by creating a div element with a certain size, and using that as the target when opening the overlay.
> 
> ```
> <div
>   #overlayTarget
>   style="width: 200px; height: 30px; margin-top: -30px;"
> ></div>
> ```
> 
> ```ts
> export class MyComponent {
>   @ViewChild('overlayTarget')
>   overlayTarget: ElementRef;
> 
>   @ViewChild('myDialog')
>   myDialog: OverlayPanel;
> 
>   @HostListener('click', ['$event'])
>   onClick(event: MouseEvent) {
>     this.myDialog.show(event, this.overlayTarget.nativeElement);
>   }
> }
> ```

Can you share all code ?

**Comment by desprit** [comment]
@buseodaci 

This is actually all code :)
The `show` method (as well as `toggle`) accepts an optional argument `target` which is an HTML element of your choice. In my case, I have a table where the last column has a button to open an overlay window. Once clicked, I create a target element like this:
```
const target = event.target.closest("tr").querySelector(".the-first-cell-class")
```
I then pass it to the `show` method.

**Comment by buseodaci** [comment]
@desprit Thank you for your comment it was long time ago. I didn't use overlay panel. I just create this.
Might be help to anybody. 
[https://stackblitz.com/edit/angular-overlay-ngfor-rx](url)

**Comment by NejcCarl** [comment]
In primeng 9 there is no option for orientation. If you look at the source code, there are two classes that deal with left to right and up and down orientation: .ui-overlaypanel-shifted and .ui-overlaypanel-flipped.

So if you want to change the overlay orientation from right to left you can just apply the styles from these classes in your components styles for example:
::ng-deep .ui-overlaypanel {
   margin-right: 58px !important;
 
   &:after {
      margin-right: -8px;
      left: auto;
      right: 1.25em;
      margin-left: auto;
   }
 
   &:before {
      display: none;
   }
 }

**Comment by hanockjoseph** [comment]
<img width="707" height="358" alt="Image" src="https://github.com/user-attachments/assets/3476c547-2a9e-41d5-ba4e-3269e57dd530" />

p-overlaypanel is breaking if it is shown towards left (angular 20, primeng 20, tailwindcss 3.4.17). this issue is not there if overlay is opened to right side


```
<div class="cursor-pointer flex-shrink-0" style="transform: translateY(3px);"  pTooltip="Notification"  tooltipPosition="bottom" #bell (click)="op.toggle($event)">
                    <p-overlaybadge [value]="members.length" severity="danger">
                    <i class="pi pi-bell !text-white" style="font-size: 1.5rem;"></i>
                </p-overlaybadge>
                </div>
<p-popover #op [appendTo]="'body'"  [styleClass]="'notification-popover'">
        <div class="flex flex-col gap-4 w-[25rem]">
            <div>
                <span class="font-medium text-surface-900 dark:text-surface-0 block mb-2">Notifications</span>
                
            </div>
            <div>
                <ul class="list-none p-0 m-0 flex flex-col gap-4">
                    @for(member of members; track member) {
                    <li class="flex items-center gap-2">
                        <img [src]="'https://primefaces.org/cdn/primeng/images/demo/avatar/' + member.image" style="width: 32px" />
                        <div>
                            <span class="font-medium">{{ member.name }}</span>
                            <div class="text-sm text-muted-color">{{ member.message }}</div>
                        </div>
                        <div class="flex items-center gap-2 text-muted-color ml-auto text-sm">
                            <span>{{ member.time }}</span>
                        </div>
                    </li>
                    }
                </ul>
            </div>
        </div>
    </p-popover>
```
