### ISSUE TITLE
DataTable (onLazyLoad) [virtualScroll] false trigger / fire

### ISSUE THREAD

**Issue by supermoon123** [primefaces/primeng#4480]
[ x ] bug report

Plunkr Case (Bug Reports)
https://plnkr.co/edit/ol1hs31QrGDqnJcDKri4?p=preview

Current behavior
dataTable with onLazyLoad [virtualScroll] continues to fire 

Expected behavior
1.) dataTable with onLazyLoad [sortable] should trigger only once

Minimal reproduction of the problem with instructions
https://plnkr.co/edit/ol1hs31QrGDqnJcDKri4?p=preview

1.) Run plnkr project in **Chrome**
2.) with grid in focus click your keyboard down arrow one time.
3.) virtual scroll continues to fire displaying record (1 and 2) then (2 and 3) **infinite loop**

![giphy 1](https://user-images.githubusercontent.com/13890896/33003867-7a3de6e2-cd8b-11e7-8f42-efe55e503e9e.gif)

What is the motivation / use case for changing the behavior?
1.) Accuracy in records displaying when utlizing [virtualScroll]="true"

Please tell us about your environment:

Angular version: 5.0.`

PrimeNG version: 5.0.

Browser Type:
Chrome

Language: [all | TypeScript X.X | ES6/7 | ES5]

**Comment by cagataycivici** [comment]
Unable to replicate with 5.x, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Q5hZgBA6DlXf55UvyVqw?p=preview
