### ISSUE TITLE
Ability to lock DataTable Selection

### ISSUE THREAD

**Issue by Ketec** [primefaces/primeng#4482]
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Expected behaviour**
To be able to prevent selection events (row, checkbox, radio, select all etc) that would trigger any of the selection events. 
For example:
User selects a row, a side panel opens and edits data. User clicks another row.
Now i would need to catch this before any data changes and prevent row selection and ask the user to save or continue/cancel.

A current temp change i use example:
```
    toggleRowsWithCheckbox(event) {
        if(this.datatableLock) {
            event.originalEvent.stopImmediatePropagation();
            event.originalEvent.preventDefault();
            this.sidebarProvider.emitNavigationBlockEvent();
        } else {
            if(event.checked) {
                this.selection = this.headerCheckboxToggleAllPages ? this.value.slice() : this.dataToRender.slice();
            } else {
                this.selection = [];
            }

            this.selectionChange.emit(this.selection);

            this.onHeaderCheckboxToggle.emit({originalEvent: event, checked: event.checked});
        }
    }
```
1. A datatable property that if set, would prevent selection.
2. Trigger a event "toggleRowsWithCheckboxPrevent" - to detect that an attempt to click something was made.

Or some sort of observable/callback based solution -  `onBeforeRowClick` where you can return true to continue, false to prevent.

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
