### ISSUE TITLE
New releases does not specify bug fixes and new features added

### ISSUE THREAD

**Issue by Rushipk** [primefaces/primeng#4484]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview

**Current behavior**
I want to move to the latest version of primeng but the problem is new version(releases) does not mentioned anything about the new features added or bug fixes that are provided in that release.

**Expected behavior**
With each new release whatever big fixes OR new features added should be given with every new release.
 
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X
4.4.4
* **PrimeNG version:** 2.0.X
4.2.0
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by amitdahan** [comment]
I think they list the changelog in their blog: https://www.primefaces.org/category/primeng/

**Comment by cagataycivici** [comment]
Please visit our blog for details about each release.
