### ISSUE TITLE
Dropdown asynchronous placeholder is ignored if options were set beforehand

### ISSUE THREAD

**Issue by amitdahan** [primefaces/primeng#4485]
**I'm submitting a ...**
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/xaDlfzUGjzuEMZi5BfaI?p=preview

**Current behavior**
While setting a <p-dropdown> with `options` and a `placeholder`, if the placeholder is being used with the `async` pipe, and "arrives" (or resolves rather) after `options` do, the first option already gets selected and placeholder is not being seen.

**Expected behavior**
Even if `placeholder` arrived a few milliseconds later, I expect to see it and not to have a choice already selected for me.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/xaDlfzUGjzuEMZi5BfaI?p=preview
bind `[placeholder]` to an async source that'll resolve after `[options]` does (whether `options` is async or not does not matter, only matters if it resolves before or after `[placeholder]`).

**What is the motivation / use case for changing the behavior?**
We're **ALWAYS** setting `[placeholder]` to `'PATH.TO.TRANSLATION' | translate` since we're using `@ngx-translate` in our project to translate our strings. Sounds like a common enough use case to me. We've found that in some specific cases the `translate` pipe resolves a millisecond later than our `options` source (sometimes we cache it, so it's quick).

**Possible solution**
A naive solution would be to set a flag when setting the selected option to be `options[0]` because there wasn't a placeholder, and then listen to `ngOnChanges` for a new placeholder, and revert back to no options selected if the flag was set (remove the flag when value changes via any other way - like writeValue or any other <p-dropdown> specific way).
I feel like this solution wouldn't be much sophisticated but doesn't sound like it'd break anything.
I've never contributed to this project but if this seems reasonable I have no problem implementing this.

* **Angular version:** 5.0.2

* **PrimeNG version:** 5.0.0 (happened on 4.3.0 as well)

* **Browser:** all
 
* **Language:** all

**Comment by karolgebert** [comment]
+1

**Comment by gschafra** [comment]
Same here, also using translation pipe. Specs:

- **Angular Version**: v7.2.12
- **PrimeNG Version**: v7.1.0
- **Browser**: all
- **Language**: all

**Comment by twopelu** [comment]
Same problem here with PrimeNG 7.1.3.

When using a simple text like:
`placeholder="empty value"`
or even with string interpolation:
`placeholder="{{ emptyValueMsg }}"`
it works fine.

But when using translation pipe:
`placeholder="{{ 'empty_value_msg ' | translate }}"`
it doesn't work.
It selects the first value in options.

May be related to this other issue:
https://github.com/primefaces/primeng/issues/1585

**Comment by twopelu** [comment]
I have tried a workaround but it doesn't work either.

It seems it has something to do with async behaviour.

If I add a property with the placeholder message in the typescript code of the component and use the translate.get() (@ngx-translate), which returns an observable, it happens the same as when using the translate pipe.

**Comment by flufiorau** [comment]
Maybe my version will save you))
`placeholder="{{('register.form.'+control.placeHolder | translate) || ' '}}"`
It works 100% for me

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
