### ISSUE TITLE
how to make two columns as default sorting columns in primeng datatable

### ISSUE THREAD

**Issue by sivanandhu** [primefaces/primeng#4487]
how to make two columns as default sorting columns in primeng datatable
<p-dataTable [value]="itemList" [emptyMessage]="itemErrorMessage" scrollable="true"	
		[rows]="50" [rowsPerPageOptions]="[50, 75, 100]" [pageLinks]="3" [multiSortMeta]="[{field: 'createDate', order: -1}, {field: 'ID', order: -1}]"
		[paginator]="itemList.length > 50" [responsive]="true" [scrollHeight]="scrollableValue" sortMode="multiple" (onSort)="changeSort($event)">

It is not working.................

Anyone help me!!!!!!!!!

**Comment by cagataycivici** [comment]
Please use forum for support requests, you need to use multiSortMeta, documentation has information already.
