### ISSUE TITLE
Non-possible value still set after changing Dropdown options

### ISSUE THREAD

**Issue by serlopez46** [primefaces/primeng#4489]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/bd9leiHakoDaL9xhWno8?p=preview

**Current behavior**
When dropdown options change the following code is executed:
```
Dropdown.prototype.updateSelectedOption = function (val) {
        this.selectedOption = this.findOption(val, this.optionsToDisplay);
        if (!this.placeholder && !this.selectedOption && this.optionsToDisplay && this.optionsToDisplay.length && !this.editable) {
            this.selectedOption = this.optionsToDisplay[0];
        }
        this.selectedOptionUpdated = true;
    };
```
If the current value cannot be found in the new options, the first option is selected if there is no placeholder and the dropdown is not editable. 
Therefore, when using placeholder and editable="false", after changing the dropdown options a non-possible value is still selected.

**Expected behavior**
Dropdown value should be set to null if current value is not found in options array, placeholder is set and editable="false".

**Minimal reproduction of the problem with instructions**
Change value in the first dropdown.
The second dropdown now has a value that is not in any of the current options.

**What is the motivation / use case for changing the behavior?**
Don't save wrong values after sending the form.

**Comment by cagataycivici** [comment]
We need more feedback on this, right now is sounds like you should control the child value at changeParentOption method when you change the options so not taking any action right now. I think native select element would do the same in this case.
