### ISSUE TITLE
Generic drag and drop between any two primeng components.

### ISSUE THREAD

**Issue by alokparikh16** [primefaces/primeng#4491]
Is it possible to get a generic drag n drop functionality between any two primeng components.
I am having an requirement where I want to drag row data from p-datatable to treetable component.

Primeng provides tree dragdrop service but it is specific to only tree component.
Can we have an similar service which can be used to drag and drop data between different components.

* **Angular version:** 4.0.5

* **PrimeNG version:** 4.3.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
