### ISSUE TITLE
Ability to unsort Data

### ISSUE THREAD

**Issue by ErBahuguna** [primefaces/primeng#4493]
I am using the PrimeNg sort filter for sorting purpose.
But when i click on any column its sorts asc and then desc.
But when i again click on this it should unsort it.
Or if unset the fields specified in datatable 
[sortField]="sortF" [sortOrder]="sortO"
It should unsort but its still highlighted.

**Comment by DmitriyKhirniy** [comment]
DataTable can not unset sort state for specified column by clicking on it. You can unset it by clicking to another column to sort it, if you have single sort options
If you want default sort options for specified column, you should write something like that: 
[sortField]="'name'" [sortOrder]=-1

**Comment by ErBahuguna** [comment]
Is there any way to unsort all columns from component.ts?

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.

**Comment by mayankkrshah** [comment]
I am using the new p-table. But in that as well there is no option to unsort the column or bring back the column sorting to its original state. Currently it sorts based on ascending and descending , but what I want is once it clicks on the header for the 3rd time it should reset back to the original state. Please help
