### ISSUE TITLE
Headers missalignment

### ISSUE THREAD

**Issue by donriver** [primefaces/primeng#4494]
http://plnkr.co/edit/gzfrNBitvMjleQE6j42A?p=preview
in this sample I reproduse simplifyed version of our component that use PrimeNG p-datatable component with dynamic columns and asyncronous setting of data and columns

**Current behavior**

- In some cases width of the datatable calculated wrong when scrolling enabled
- In some cases headers and data columns became missaligned 

**Expected behavior**
width of datatable should be calculated according to given columns widths
Headers and data columns should be aligned

**Minimal reproduction of the problem with instructions**
open plunker sample, repeat actions from gifs
1. press "**100 Columns**" button
resize second column
press "**10 Columns**" button - table width inside scrollable area doesn't changed and columns are wider than it should be
try to resize some column - huge missalignment between headers and data
![headers missalignment 1](https://user-images.githubusercontent.com/22830620/33067800-591aa15e-cec0-11e7-9f48-81cb711d001c.gif)

2. press "**10 columns Async**" button
increaze size of second column
repeat two previous steps
![headers missalignment 3](https://user-images.githubusercontent.com/22830620/33071068-3de1f51c-cecb-11e7-999f-c2c60a7499ca.gif)

**Please tell us about your environment:**
Windows 10
1) plunker
2) VS Code, npm, Angular CLI

* **Angular version:** 4.3.5

* **PrimeNG version:** 4.3.0

* **Browser:** Chrome 62.0.3202.94 64bit | Firefox 56.0.2 | IE 11/Edge | Opera 36.0.2130.80
 
* **Language:** TypeScript 2.3.4

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
