### ISSUE TITLE
DataTable -move alignScrollBar call in updateDataToRender instead of in ngAfterViewChecked to improve performance

### ISSUE THREAD

**Issue by amitgaikwad02bright** [primefaces/primeng#4499]
**Current behavior**

alignScrollBar method is called in ngAfterViewChecked.
ngAfterViewChecked hook gets called after every change detection in application. even though events are unrelated to datatable component ngAfterViewChecked get called which calls alignScrollbar.
e.g; if page has any dropdown/input box, on their event also DataTable's alignScrollbar get called, which is not related.
alignScrollbar method has calls to DOM api offsetHeight, which is performance heavy & causes re-flow
https://gist.github.com/paulirish/5d52fb081b3570c81e3a

**Expected behavior**
can we move alignScrollBar method call inside updateDataToRender.
I guess, updateDataToRender method is place which will called when data rendered is changed.
& alignScrollBar should be called only whenever data rendered is changed.

**Comment by cagataycivici** [comment]
But we need the dom to be updated, that happens at afterViewChecked.

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
