### ISSUE TITLE
OverlayPanel doesn't show if custom css is applied to it.

### ISSUE THREAD

**Issue by aminecmi** [primefaces/primeng#4500]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

http://plnkr.co/edit/WvpoXsRbqUW01bWIYkAe?p=preview

**Current behavior**
Adding custom style to an overlaypanel make it unusable. It doesn't appear anymore. 

**Expected behavior**
The overlaypanel should appear (the same code wasn't causing any issue with the 4.1.3 version)

**Minimal reproduction of the problem with instructions**
- Click on the button.
- Nothing happen.
- Remove the css from the css file.
- Click on the button
- The overlaypanel appear.

**Please tell us about your environment:**

* **Angular version:** 5.0.0

* **PrimeNG version:** 5.0.0-rc.0/5.0.0/4.3.0

* **Browser:** tested on Chrome and Safari
 
* **Language:** TypeScript 2.6.1

**Comment by nartc** [comment]
Somehow it does not appear if the position is fixed. It does appear if you change the position to something else though.

**Comment by aminecmi** [comment]
@nartc it seams so, yes. 

But what if I need to have the panel fixed ?

**Comment by aminecmi** [comment]
I downgraded to v4.1.3 where this works as expected.

**Comment by skaor** [comment]
There is a fix for that other than downgrade the version or changing the position ???

**Comment by trailofdad** [comment]
This is still an issue!
