### ISSUE TITLE
Multi Row Grouping for DataTable

### ISSUE THREAD

**Issue by jisqaqov** [primefaces/primeng#4505]
Add rowspan and colspan attributes for rows in datatable. Currently primeng supports only grouping of headers.
See attached file.
[table.xlsx](https://github.com/primefaces/primeng/files/1494782/table.xlsx)

**Comment by rkdvep** [comment]
just add a style component to the column, e.g.:  [style]="{'width':'250px'}"

**Comment by jisqaqov** [comment]
You are completely wrong. rowspan works with td tag.

**Comment by rkdvep** [comment]
My fault, I misunderstood. Use a custom template for (one of) the columns. example implementation: http://plnkr.co/edit/k520pKFYl2FA7SJENMQe?p=preview

**Comment by jisqaqov** [comment]
Again, You are completely wrong. I need to deal with rows not columns. Rows are quite different.

**Comment by jisqaqov** [comment]
See attached file

**Comment by rkdvep** [comment]
Your attached file shows rows & columns of variable sizes, I'm afraid you'll have to be a bit more specific

**Comment by jisqaqov** [comment]
Exactly, i want to reproduce such table using prime ng DataTable. Otherwise, i have to use html tables.
The point is some columns and rows grouped. In fact, i want to group rows.

**Comment by rkdvep** [comment]
Ah, https://www.primefaces.org/primeng/#/datatable/rowgroup the docs have an extensive guide on how to do this

**Comment by jisqaqov** [comment]
Again, You are completely wrong. You can make only first column row grouping. I need to group rows on custom. Could you please stop following this thread.

**Comment by jisqaqov** [comment]
Instead of showing me docs, first, try to reproduce the problem.

**Comment by cagataycivici** [comment]
What do you mean by group rows on custom?

**Comment by jisqaqov** [comment]
I want to groups rows. In fact, i can group columns in DataTable but not rows. I know there are expandable rows feature, but i want to group some rows, others remain as it is. See attached file. To be specific i want to manipulate with rowspan attribute td tag of body of the DataTable.

**Comment by jisqaqov** [comment]
I think it is a great feature to customize rows. See picture. It has rows grouped. Currently, you can not do this in DataTable.
![image](https://user-images.githubusercontent.com/20530024/33201341-4ea162bc-d122-11e7-8cb7-cfdcf2d284d1.png)

**Comment by HamoudaJoe** [comment]
did you find a solution to your problem? because I hava the same

**Comment by jisqaqov** [comment]
I used html table. So i could handle rowspan and colspan manually. Unfortunately, primeng does not have such feature yet.

**Comment by jisqaqov** [comment]
When you could add such feature?

**Comment by cagataycivici** [comment]
Should be a new feature like multi row grouping, we can't do this before improving the performance of DataTable. I'd suggest going with a plain table at the moment.

**Comment by jisqaqov** [comment]
Ok, looking forward to this feature.

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.

**Comment by MHacker9404** [comment]
How do we get access to the 5.1.0 release?

**Comment by cagataycivici** [comment]
New p-table can do this. DataTable is deprecated in favor new p-table and not maintained anymore.

**Comment by patilragini** [comment]
@jisqaqov 
i want to use same table format as shown in attached file can pl share row col format in primeng i tried with p-datable but it is very slow and not able to  merge multiple row
