### ISSUE TITLE
concatenate fields property in-column

### ISSUE THREAD

**Issue by alialtun14** [primefaces/primeng#4506]
It would be great, we concatenate fields in p-column component without using ng-template.

Before concatenation 
---------------------------
<p-column field="year"	 	header="Year" 		[sortable]="true"></p-column>
<p-column field="month"	header="Month" 		[sortable]="true"></p-column>

After concatenation 
-------------------------
<p-column field="year, month"	 header="Year, Month" 	[sortable]="true"></p-column>

**Comment by sudheerj** [comment]
In my opinion ng-template would be the right way to do for this kind of customization. If we concatenate the columns into single column then it will create an issue with all datatable features(filter,edit etc)

**Comment by cagataycivici** [comment]
ng-template is great, gives more flexibility without complicating code on our side :)

**Comment by ningacoding** [comment]
if is that great, why we cant filter with multiple fields with the filter method of Table component?
