### ISSUE TITLE
Disable upload in FileInput dinamically

### ISSUE THREAD

**Issue by lippomano** [primefaces/primeng#4507]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[x ] support request => Please do not submit support request here, instead see
```

I want to disable the FileInput dinamically, and of course during the upload is it possible?

Now I tried with this code:
```
@ViewChild('fileInput') fileInput: FileUpload;

  onBeforeUpload(event) {
    this.fileInput.disabled = true;
  }
```
But it remains abilited and if I click the button multiple times during the upload I have multiple uploads
this is my component:

```
<p-fileUpload mode="basic" #fileInput name="file" url="{{url}}" auto="auto"
		(onBeforeUpload)="onBeforeUpload()"
		chooseLabel="Carica" (onUpload)="onUpload($event)"
		(onProgress)="onProgress($event)" (onError)="onError($event)"
		multiple="multiple" (onBeforeSend)="onBeforeSend($event)"
		accept="{{uploadAcceptedFormat}}" maxFileSize="{{maxSize}}">
</p-fileUpload>
```

* **Angular version:** 4.4.4

* **PrimeNG version:** 4.2.0-rc.1

**Comment by cagataycivici** [comment]
Can you try with 5.0.0?

**Comment by lippomano** [comment]
@cagataycivici  Sorry for late response, just tried with 5.2.0-rc1 and the upload button still not disabled

**Comment by parisgianluca** [comment]
This is still a problem

**Comment by newaeonweb** [comment]
the issue was closed but the problem still unsolved, any way to accomplish this @cagataycivici ? thanks in advance.
