### ISSUE TITLE
column toggle not working on resizable datatable

### ISSUE THREAD

**Issue by fripp0971** [primefaces/primeng#451]
I setup a datatable with resizable turned on (with expand setting) and when I toggle the hidden true or false of any column, it won't add them to the grid. I can see it adds a border, but not the whole column.

If i turn off resizable, it works fine, but then doesn't allow for resize.

This is a new thing since it worked in beta 6

**Comment by johnjill** [comment]
We encountered the same issue.  It also happens on fit mode. We are currently using primeng 2.0.0.  Any update on this issue?

**Comment by cagataycivici** [comment]
Depends on how you implement column toggler, I'd suggest hiding the column instead of removing it from dom. 

```xml
<p-dataTable [value]="cars" resizableColumns="true">
        <p-header>
            <div style="text-align:left">
                <p-multiSelect [options]="columnOptions" [(ngModel)]="cols"></p-multiSelect>
            </div>
        </p-header>
        <p-column *ngFor="let col of dtCols" [field]="col.field" [header]="col.header" [hidden]=!isVisible(col)"></p-column>
    </p-dataTable>
```

```typescript
export class DataTableColTogglerDemo implements OnInit {

    cars: Car[];
    
    cols: any[];
    
    dtCols: any[];
    
    columnOptions: SelectItem[];
        
    constructor(private carService: CarService) { }

    ngOnInit() {
        this.carService.getCarsSmall().then(cars => this.cars = cars);
        
        this.dtCols = [
            {field: 'vin', header: 'Vin'},
            {field: 'year', header: 'Year'},
            {field: 'brand', header: 'Brand'},
            {field: 'color', header: 'Color'}
        ];
        
        this.cols = this.dtCols.slice(0);
                
        this.columnOptions = [];
        for(let i = 0; i < this.cols.length; i++) {
            this.columnOptions.push({label: this.cols[i].header, value: this.cols[i]});
        }
    }
    
    isVisible(dtCol) {
        for(let col of this.cols) {
            if(col.field === dtCol.field) {
                return true;
            }
        }
        
        return false;
    }
}
```

When I do this instead of the showcase example which just removes columns so loses width information, it works fine;

https://www.primefaces.org/primeng/#/datatable/coltoggler

**Comment by kevinrstone** [comment]
Isn't this bad for performance? What is the technical reason it doesn't work when using the showcase example?

**Comment by kentonbmax** [comment]
Selecting the column again adds it to the left or bottom of the array. Thoughts on work around?

**Comment by Zhorius** [comment]
@cagataycivici but it doesnt work when I have initially some columns excluded, when i try to chose in dropdown initially hidden column, it isnt shown in table
