### ISSUE TITLE
Cannot use resizableColumns together with dynamic visibility

### ISSUE THREAD

**Issue by Archina** [primefaces/primeng#4510]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

Affected component dataTable

Setup `p-dataTable` with the attribute `resizableColumns="true"` containing n `p-column`s with one way data-binding on the attribute `hidden`.

Example:
```
<p-dataTable [value]="cars" resizableColumns="true">
    <p-column field="vin" header="Vin"></p-column>
    <p-column field="year" header="Year" [hidden]="toggleableVariable"></p-column>
    <p-column field="brand" header="Brand"></p-column>
    <p-column field="color" header="Color"></p-column>
</p-dataTable>
```

If hidden is changed after the initalisation of p-dataTable, resizing starts to behave ~weird~. The resize preview does not fit the actual modification on the column width.

Fix within the method `onColumnResizeEnd`:
```
let nextColumn = this.resizeColumn.nextElementSibling; //This must be the next visible Column though.
while(nextColumn.classList.contains("ui-helper-hidden")){
    nextColumn = nextColumn.nextElementSibling;
}
```

**Expected behavior**
Column should still be resized correctly.

**Minimal reproduction of the problem with instructions**
See above

**What is the motivation / use case for changing the behavior?**
Allowing to join column visibility with the resizeability feature.

**Please tell us about your environment:**

* **Angular version: 5
* **PrimeNG version: recent

* **Browser:** [Chrome | Firefox | Edge ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by shayts** [comment]
@cagataycivici  I'm trying to add new columns to the datatable after it was created (on user click) but it doesn't work when setting  resizableColumns="true".
I'm guessing it's the same bug as with hidden columns. am I wright? If so are you planning to make a new build with this fix?
