### ISSUE TITLE
Errors for scrollable table with both resizable and frozen columns 

### ISSUE THREAD

**Issue by thefatoneinthecorner** [primefaces/primeng#4512]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Forked: http://plnkr.co/edit/F4SA6VUujzofjb3s7Ejd?p=preview

**Current behavior**
Errors in the console, possibly leading to Ngrx store/router problems (component not deleted when navigating away?).

Bug tracked down to datable.ts line 2259 (iterating over bodyCols in fixColumnWidths - should stop on bodyCols.length, not columns.length).

**Expected behaviour**
No Errors.

**Minimal reproduction of the problem with instructions**
Load the above Plunkr and examine the Javascript console.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

OS X 10.11.16

* **Angular version:** 2.0.X

4.2.6

* **PrimeNG version:** 2.0.X

4.3.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Safari 11.0.1 and Chrome 61.03.3163

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by winarg** [comment]
Any info regarding this issue?
It happens and in the latest PrimeNG version 5.0.2
