### ISSUE TITLE
Autocomplete: list of possible values does not hide onSelect (v5.0.0)

### ISSUE THREAD

**Issue by jizza** [primefaces/primeng#4514]
I'm submitting a 
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

PrimeNG 4.3.0: http://plnkr.co/edit/RWznIqcyiKh9zrdXEkSt?p=preview (autocomplete remains in focus)
PrimeNG 5.0.0: http://plnkr.co/edit/RblloTUe20TOKFz06UbU?p=preview (list of possible values does not hide)

**Current behavior**
In PrimeNG 4.3.0, Autocomplete remains in focus with forceSelection (#4298). This bug should've been fixed in release 5.0.0. However it introduced another bug: The list of possible values does not hide when selecting a value using your mouse. This issue occurs both with and without the forceSelection attribute. When using the keyboard (enter) it seems to work. As most of my users depend on their mouse for such actions, this issue makes autocomplete unusable.

**Expected behavior**
Autocomplete should select the clicked value and then hide the list of possible values.

* **Angular version:** 4.0.X

* **PrimeNG version:** 5.0.X

**Comment by xeeqqw** [comment]
+1
error in console: `ERROR TypeError: Cannot read property 'nativeElement' of undefined`

**Comment by cagataycivici** [comment]
Tracked at https://github.com/primefaces/primeng/issues/4483
