### ISSUE TITLE
DataTable resize with fit mode does not adjust after screen resize

### ISSUE THREAD

**Issue by brian428** [primefaces/primeng#4515]
**I'm submitting a ...**  (check one with "x")
```
[X] Not sure if this is a bug report or a feature request
```
**Plunkr Case (Bug Reports)**
Simply open the DataTable resize docs (https://www.primefaces.org/primeng/#/datatable/colresize) and then shrink the size of your browser window. Instead of adjusting to the new window size, the table with "fit" mode keeps the same width and adds horizontal scrollbars. 

**Expected behavior**
Table should resize to adjust to the new window width.

* **PrimeNG version:** 4.3.0

**Comment by cagataycivici** [comment]
We rather not as resizable columns have fixed width. We display a scrollbar instead.

**Comment by brian428** [comment]
In that case, it probably makes sense to update the docs to state that fit mode is basically ignored if column resize is enabled?
