### ISSUE TITLE
SPINNER: property "readonly"="false", unexpected block edit mode

### ISSUE THREAD

**Issue by TishchenkoAlex** [primefaces/primeng#4517]
[x] bug report

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/h9MB65fU3xQCgmQoZOfR?p=preview

* **Angular version:** 5.0.1

* **PrimeNG version:** 5.0.0

* **Browser:**  Chrome 62

**Comment by sudheerj** [comment]
The issue is not created in valid format. Can you describe further about the issue with plunker example.

**Comment by TishchenkoAlex** [comment]
http://plnkr.co/edit/h9MB65fU3xQCgmQoZOfR?p=preview
Bug example:

<p-spinner readonly="false"></p-spinner>
 
After set readonly property of spinner to "false", I'm can't  edit in spinner component. (buttons Up & Down still change value but direct input from keyboard not work)

**Comment by cagataycivici** [comment]
[readonly]="false"

**Comment by TishchenkoAlex** [comment]
Ok, @cagataycivici, this suggestion [readonly]="false" nothing change ((. 
this code block dorect edit in SPINNER component
(look plnkr)
`<p-spinner [readonly]="false"></p-spinner>
http://plnkr.co/edit/h9MB65fU3xQCgmQoZOfR?p=preview

**Comment by huineng** [comment]
https://github.com/primefaces/primeng/issues/4366
