### ISSUE TITLE
Toolbar BlockableUI

### ISSUE THREAD

**Issue by jisqaqov** [primefaces/primeng#4518]
Make Toolbar component implement BlockableUI . In fact, make Toolbar used with BlockUI component

**Comment by sudheerj** [comment]
What is the purpose of having BlockackableUI for toolbar. I never see these scenarios.However you can use BlockUi target as toolbar component

**Comment by jisqaqov** [comment]
For instance, Toolbar can be a group of buttons. So if i block toolbar, all buttons, items of toolbar will be unavailable. I think it is reasonable, because i do not need to block each item itself.

**Comment by sudheerj** [comment]
The blockUI support is added for Toolbar component in 5.0.3 release.
