### ISSUE TITLE
In Angular v4.x , AOT build fails after upgrade primeng 4.1.2 to 5.0.0 version

### ISSUE THREAD

**Issue by jayakumar-ilink** [primefaces/primeng#4525]
For this #4423 issue fix, upgraded the PrimeNG version 4.1.2 to 5.0.0

In Angular v4.x , AOT build fails after upgrade primeng 4.1.2 to 5.0.0 version
![image](https://user-images.githubusercontent.com/33628624/33199678-3c94a3b4-d117-11e7-8f9e-91498013a279.png)

**Comment by cagataycivici** [comment]
You need Angular 5 to run PrimeNG 5 due to AOT restrictions.
