### ISSUE TITLE
Clear icon for AutoComplete

### ISSUE THREAD

**Issue by mohammadalnatour** [primefaces/primeng#4526]
How can i add x to clear the value of the autocomplete filed ?

**Comment by spersico** [comment]
+1

**Comment by dydFreeman** [comment]
By adding the [type]="'search'" on the autocomplete component.

```
<p-autoComplete ... [type]="'search'">
</p-autoComplete>
```

By default is 'text'.
Anyway, by doing this what you get is only a 'graphical' value clear , since the model is not affected (`onClear` method is not triggered when clicking on X icon).

**Comment by dydFreeman** [comment]
A solution for manually triggering a model reset would be the following:

```
<p-autoComplete #autocomplete ...></p-autocomplete>

@ViewChild('autocomplete')
  ac: AutoComplete;

this.ac.el.nativeElement.onsearch = (event) => {
    // handling model reset
};
```

The `onsearch `method is called every time we click on the X icon.
This works only on webkit based browser (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search)

**Comment by dev-amitkmishra** [comment]
@dydFreeman Please provide the working demo of this, this will be really helpful till this feature is not getting included

**Comment by cagataycivici** [comment]
3660

**Comment by ikgeor** [comment]
+1
