### ISSUE TITLE
Fieldset is always toggleable

### ISSUE THREAD

**Issue by ketsching** [primefaces/primeng#4527]
**I'm submitting a
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/aZiF4xRDr2rmcTx1ywE9?p=preview

**Current behavior**

Fieldset is always toggleable even `toggleable` is set to `false`.

**Expected behavior**

Fieldset is only toggleable if `toggleable` is set to true.

**Minimal reproduction of the problem with instructions**
Example can be found in Plunkr Case above. Since commit 5c531172696af24b60956e0e505d803974b46950 `*ngIf="toggleable"`is missing in the fieldset template.

**What is the motivation / use case for changing the behavior?**
Fieldsets are always toggleable since upgrading to primeng@5.0.1

* **Angular version:** 5.0.2
* **PrimeNG version:** 5.0.1
* **Browser:** [all ]
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by aamir1995** [comment]
+1

**Comment by cagataycivici** [comment]
Fixed and added a unit test

**Comment by maplion** [comment]
@cagataycivici  I manually added this change in and it makes the big plus(+) go away (yey!), but the fieldset itself is still always toggable (e.g. if I click the legend text, it still toggles).

**Comment by aamir1995** [comment]
@maplion I think is fixed and will be available in coming release.

**Comment by maplion** [comment]
@aamir1995 Are you sure?  I pulled the most recent version and saw the *ngIf="toggleable" fix included, but I could still toggle fieldsets off of legend text.

**Comment by aamir1995** [comment]
@maplion If you have reproduced the issue then please open new issue.

**Comment by ragavanrajan** [comment]
I am facing the same issue. It is always toggleable. How to fix it. ?

**Comment by maplion** [comment]
@ragavanrajan If you never need toggable elements, what I did as a workaround until it is resolved is to extract the fieldset component from the primeng library, then I put this in my project as a component and loaded my fieldset from it instead of primeng, then inside the fieldset template [which I extracted into its own html file so it is easier to read], I commented out the following lines (the link lines):

```
<fieldset [attr.id]="id" [ngClass]="{'ui-fieldset ui-widget ui-widget-content ui-corner-all': true, 'ui-fieldset-toggleable': toggleable}"
    [ngStyle]="style" [class]="styleClass">
    <legend class="ui-fieldset-legend ui-corner-all ui-state-default ui-unselectable-text">
        <!-- <a href="#" (click)="toggle($event)" [attr.aria-controls]="id + '-content'" [attr.aria-expanded]="!collapsed" [attr.tabindex]="toggleable ? null : -1"> -->
            <span class="ui-fieldset-toggler fa fa-w" *ngIf="toggleable" [ngClass]="{'fa-minus': !collapsed,'fa-plus':collapsed}"></span>
            <span class="ui-fieldset-legend-text">{{legend}}</span>
            <ng-content select="p-header"></ng-content>
        <!-- </a> -->
    </legend>
    <div [attr.id]="id + '-content'" class="ui-fieldset-content-wrapper" [@fieldsetContent]="collapsed ? 'hidden' : 'visible'"
        [ngClass]="{'ui-fieldset-content-wrapper-overflown': collapsed||animating}" [attr.aria-hidden]="collapsed" (@fieldsetContent.done)="onToggleDone($event)"
        role="region">
        <div class="ui-fieldset-content">
            <ng-content></ng-content>
        </div>
    </div>
</fieldset>
```
