### ISSUE TITLE
 method (onFilter)="someMethod($event) constantly called

### ISSUE THREAD

**Issue by AlexKulbako** [primefaces/primeng#4531]
I have a code:
```
 <p-dataTable #dt [value]="userList.items" [rows]="pageSize" [paginator]="true" (onSort)="onChangeSort($event)" (onFilter)="onFilter($event)"
    (onPage)="onPage($event)" filterDelay="300">

  public onFilter(event): void {
    this.filterExpression = this.getFiltersExpression(event.filters);
    this.fillUserList();
  }
```
When i try to put something in input designated [filter] = "true",
` <p-column field="Email" [filter]="true" filterPlaceholder="Search"></p-column>
`
my onFilter() method is infinitely called until until I delete all the characters from the input. "Well done"....

The version of primeng is  "4.3.0",

**Comment by cagataycivici** [comment]
Unable to replicate in my case, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Q5hZgBA6DlXf55UvyVqw?p=preview
