### ISSUE TITLE
Multiline textbox in editable DataTable?

### ISSUE THREAD

**Issue by Greatshock** [primefaces/primeng#4532]
How do I make multiline editor texbox in datatable?

I use `word-wrap: break-word;` style in my datatable, the result is the following:
![2017-11-24 21 04 10](https://user-images.githubusercontent.com/24393175/33220658-1139d3e4-d15b-11e7-91f2-ddb6b7bb6eac.png)

However, when I enter editing mode there is only one line:
![2017-11-24 21 07 52](https://user-images.githubusercontent.com/24393175/33220735-93a6d48a-d15b-11e7-8f46-2467066dbadd.png)

How can I make it multiline?

**Comment by cagataycivici** [comment]
Please use forum for support requests.
