### ISSUE TITLE
Page change number issue. 

### ISSUE THREAD

**Issue by Pinank** [primefaces/primeng#4533]
Not able to change the page number of the paginator. My code is

` <p-paginator #paginator
                     [rows]="paginateItem"
                     [totalRecords]="totalData"
                     [rowsPerPageOptions]="recordsPerPage"
                     (onPageChange)="onPageChange($event, paginator)">
        </p-paginator>`

Now if user changes the page size than it should move to first page and fetch data of that page. At present it's doing the same but the paginator page number keeps selected.  Here is the screensort
- 
![screen shot 2017-11-25 at 4 08 31 pm](https://user-images.githubusercontent.com/3683505/33229757-e9a99d1e-d1fa-11e7-9036-1485dc77fc28.png)

In above screen its showing page 4 selected but in actually its data of 1st page. So it should show 1st page selected. 

Here is the scene.

1. Change page size to 30.
2. Move to 2nd page.
3. Change page size to 10.

It will show wrong page selected but in grid will load data of 1st page.

Can anyone help me with this please.

**Comment by cagataycivici** [comment]
Please use forum for support requests, also make sure to add a plunkr.

http://plnkr.co/edit/Q5hZgBA6DlXf55UvyVqw?p=preview
