### ISSUE TITLE
p-dropdown styles are only applied to div

### ISSUE THREAD

**Issue by tiger5226** [primefaces/primeng#4537]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

plunker example
http://plnkr.co/edit/iVyfTwwLaJaN516t8Qt4?p=preview

**Current behavior**
The bug is around styles for the p-dropdown component. You will notice in the plunker that the dropdown does not stretch, even when setting the style directly and through a style class. 

**Expected behavior**
I expect that if I use inline style for width at 100% that it works. I can easily add this via chrome debugger and get the expected result. See attached screenshots. 

**Minimal reproduction of the problem with instructions**

see plnkr http://plnkr.co/edit/iVyfTwwLaJaN516t8Qt4?p=preview

**Please tell us about your environment:**
Mac OSX

* **Angular version:** 2.0.X
5.0.3
* **PrimeNG version:** 2.0.X
5.0.2

* **Browser:** 
Chrome
 
![screen shot 2017-11-26 at 4 52 32 pm](https://user-images.githubusercontent.com/3402064/33244977-63eb084a-d2cf-11e7-893f-8b066c7da7cd.png)
![screen shot 2017-11-26 at 4 52 12 pm](https://user-images.githubusercontent.com/3402064/33244980-6686f0c8-d2cf-11e7-9247-98747f4cc084.png)
![screen shot 2017-11-26 at 4 52 12 pm](https://user-images.githubusercontent.com/3402064/33244990-769a1170-d2cf-11e7-8db3-edbdf812a6e6.png)
![screen shot 2017-11-26 at 4 51 00 pm](https://user-images.githubusercontent.com/3402064/33244993-7a95e10a-d2cf-11e7-9d36-839163f06a05.png)

**Comment by tiger5226** [comment]
FYI workaround for me was to use internal ng class in css

`.ng-valid{
    width: 100%;
}`

This fixes the problem and allows it to stretch. 

![screen shot 2017-11-26 at 5 33 22 pm](https://user-images.githubusercontent.com/3402064/33245031-f580a076-d2cf-11e7-97ae-11f78ccfc00f.png)

**Comment by cagataycivici** [comment]
Please try [autoWidth]="false" as well.
