### ISSUE TITLE
Add style to Panel Header

### ISSUE THREAD

**Issue by hkashlan** [primefaces/primeng#4539]
**I'm submitting a ...**  
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
I need to change the panel header background depends on DB values
**Expected behavior**
to have header style attribute allow me to change the header panel
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

I have a dashboard and each panel has unique header background depends on DB value

* **Angular version:** 5.0.X

* **PrimeNG version:** 4.2.2

* **Browser:** [all ]

**Comment by cagataycivici** [comment]
You can do it with styleClass;

```
.my-panel .ui-panel-titlebar {
     background: #blue
}
```

```
<p-panel styleClass="my-panel"
```

**Comment by hkashlan** [comment]
Thank you for your reply, 
so I need to create a predefined classes like my-panel-red, my-panel-green

but what I want to make it dynamic depend on DB like:

`<p-panel *ngFor="let item of this.dashboardAndResults"[styleClass]="item.data?.panelClass" **[pnlTitleStyle]="{'background': item.titleColor}**>`

for now I will create a predefined classes without ability to change it from DB.

**Comment by eduardowickertg** [comment]
@cagataycivici didn't understand it properly, here's your solution, @hkashlan :

`<p-panel [ngClass]="{'my-panel-red': item.data}"></p-panel>`

now you can change the way you want :)
