### ISSUE TITLE
Datatable resizableColumns does not work correctly with checkbox selection and columnResizeMode="expand"

### ISSUE THREAD

**Issue by winarg** [primefaces/primeng#4545]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/OahYZYUy2PgzHdHajhWF?p=preview

**Current behavior**
When the button is clicked is simulates a change of columns and data. On every other click, the data will be lost, and on the next click will be shown again

**Expected behavior**
Just show the data on every click

**Minimal reproduction of the problem with instructions**
Click the button with the label "PrimeNG"

**What is the motivation / use case for changing the behavior?**
Use a table that dynamically changes columns

**Please tell us about your environment:**

* **Angular version:** 2.0.X
4.4.4

* **PrimeNG version:** 2.0.X
4.3.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
