### ISSUE TITLE
[(selection)] on Mobile View

### ISSUE THREAD

**Issue by Atrastea** [primefaces/primeng#4546]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...** 
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
If you have a primeNg-datatabale and you have [(selection)]="someVariable" on it, it works till the point when you set your Browser to Mobile View and select a Raw. 
In this case and only on mobile View "someVariable" will be undefined

**Expected behavior**
[(selection)]="someVariable" would have the selected Row

**Minimal reproduction of the problem with instructions**
create a Datatable put [(selection)] on it.
Set Browser to mobile view
select a row and see the variable is undefined

**Comment by ddyrcz** [comment]
The same issue here, I have PrimeNG 4.3

**Comment by Atrastea** [comment]
Thanks for the Hint.

Updated to 5.0.2 works now.
