### ISSUE TITLE
Angular4 PrimeNG CSV export

### ISSUE THREAD

**Issue by jaafriadnane** [primefaces/primeng#4547]
I'm using primeNG **4.3.0** in an angular4 project,

CSV export of primeng add a semicolon at the end of each line,

I know that this is caused by the column I use to delete lines :    

`<p-column [style]="{'width':'50px'}" styleClass="col-button" header="">             <ng-template let-device="rowData" pTemplate="body">                 <button type="submit" [routerLink]="['/', { outlets: { popup: 'device/'+ device.id + '/delete'} }]"                     replaceUrl="true" class="button-delete btn btn-danger btn-sm">                     <span class="fa fa-remove"></span>                     <span class="hidden-md-down"></span>                 </button>             </ng-template>         </p-column>` 

I have tried the : [exportable]="false" in the p-column but it does not work.

any ideas please ?
--

**Comment by cagataycivici** [comment]
Try with 5.0.x please to take advantage of [exportable]="false"

**Comment by jaafriadnane** [comment]
Hello, thank you for your answer,

I tried the new version, i'm now on the 5.0.2 and I have the same issue even though i use the  [exportable]="false",

I always have a comma (csv Separator) at the end of every line.

I took a look at the code, for exemple the header :

`        for (var i = 0; i < this.columns.length; i++) {
            var column = this.columns[i];
            if (column.exportable && column.field) {
                csv += '"' + (column.header || column.field) + '"';
                if (i < (this.columns.length - 1)) {
                    csv += this.csvSeparator;
                }
            } 
        }`

I think that it is better to verify that ( i < (nbrOfExportableColumns - 1) ) before adding the separator,

in my case i have 10 exportable columns and i have 14 columns in my table, 4 columns are not exportable so the condition  if (i < (this.columns.length - 1)) passes on the last exportable column ...

thank you in advance
