### ISSUE TITLE
helper lines for p-treeTable

### ISSUE THREAD

**Issue by webnegar** [primefaces/primeng#4549]
please add helper lines for p-treeTable like attached picture.
![sample-lines](https://user-images.githubusercontent.com/7112978/33290747-ebdaf9d6-d3d8-11e7-8bd9-92b74e6d31da.png)

tnx

**Comment by cagataycivici** [comment]
We'll rewrite TreeTable in 5.2, current one does not allow helper lines due to a workaround we had to do for an Angular bug.
