### ISSUE TITLE
problem when using inputswitch inside tabView->tabPanel

### ISSUE THREAD

**Issue by samehelhawary** [primefaces/primeng#455]
Problem when using inputswitch inside tabpanel.
Inputswitch width is changed to 0 and user interface functionality is not working but the value (true - false) is toggled when click inputswitch.

**Comment by sievert** [comment]
If you use the InputSwitch inside a Dialog, the width is set to 6px.

**Comment by MarcelCremer** [comment]
+1
I tried to put it in several containers, but it looks like the "DomHandler" doesn't find the correct element. Idk how to fix it though.

**Comment by cagataycivici** [comment]
Fixed via #972
