### ISSUE TITLE
Lisbox bug

### ISSUE THREAD

**Issue by jisqaqov** [primefaces/primeng#4552]
when i used Listbox component on the demo page i found a bug. it was written in console of the browser:
Cannot read property 'remove' of undefined
![image](https://user-images.githubusercontent.com/20530024/33304210-b520bb70-d431-11e7-82d9-8c7f852e75d8.png)

**Comment by deniskrafczyk** [comment]
i think its the same as #4553

**Comment by cagataycivici** [comment]
Chrome 63 should fix this.
