### ISSUE TITLE
DataTable - Column Toggler , Throws undefined error while selecting columns 

### ISSUE THREAD

**Issue by HarisHrz** [primefaces/primeng#4553]
**Current behavior**
Typeerror "Cannot read property 'remove' of undefined" when I tried to select and unselect different columns from column toggler repeatedly,  I got the error in my localhost ( my application) and in PrimeNg website as well.
![primeng_coltoggler_error](https://user-images.githubusercontent.com/10586659/33304350-3f3f3dda-d42e-11e7-9229-cb745c5ac28c.PNG)
![primeng_coltoggler_error_local](https://user-images.githubusercontent.com/10586659/33304351-3f6978d4-d42e-11e7-9727-7ee3e23fa61d.PNG)

**Expected behavior**
User should be able to select/unselect columns repeatedly, 

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

Google Chrome Version 62.0.3202.94 (Official Build) (64-bit)

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by linpengfei** [comment]
my also have this question，is this a bug for chorme？

**Comment by SusanAWAL** [comment]
I have the same problem in Google chrome.
no problem using firefox, but I need to run my page in chrome, so any solution?

**Comment by HarisHrz** [comment]
Yes , It's a bug in Chrome, Which is not yet solved
https://stackoverflow.com/questions/47527795/angular-throws-error-on-primeng-datatable-column-toggler

**Comment by cagataycivici** [comment]
Chrome 63 should fix this.
