### ISSUE TITLE
Unable to create nested headers with dynamic data using loops etc.

### ISSUE THREAD

**Issue by Ram-SR** [primefaces/primeng#4557]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by Ram-SR** [comment]
![capture](https://user-images.githubusercontent.com/20413059/33316947-9385a346-d3ea-11e7-9ccf-70cf4c9b7d82.PNG)

The nested headers in that image or coming dynamically. I don't want to hard code them using `<p-column>`. Headers should be based on dynamic data

**Comment by Ram-SR** [comment]
```
    <p-headerColumnGroup>
        <p-row>
            <p-column header="" rowspan="4"></p-column>
            <!-- <p-column header="Sale Rate" colspan="4"></p-column> -->
        </p-row>
        <p-row>
            <p-column header="PRESENT TODAY" colspan="4"></p-column>
            <p-column header="IN - TIME INTERVAL" colspan="2"></p-column>
        </p-row>
        <p-row>
            <p-column header="Count" colspan="2"></p-column>
            <p-column header="Percentage" colspan="2"></p-column>
            <p-column header="Before 10.00am" colspan="1" rowspan="2"></p-column>
            <p-column header="After 11.00am" colspan="1" rowspan="2"></p-column>
        </p-row>
        <p-row>
            <p-column header="Count"></p-column>
            <p-column header="Percentage"></p-column>
            <p-column header="Before 10.00am"></p-column>
			<p-column header="After 11.00am"></p-column>
        </p-row>
    </p-headerColumnGroup>
```


For now, I hard coded like this.

**Comment by cagataycivici** [comment]
Please use forum for support requests, I believe if you have json structure you can generate p-headerColumnGroup, p-row and p-column yourself using ngFor.
