### ISSUE TITLE
CSS rules are too broad

### ISSUE THREAD

**Issue by MrBlaise** [primefaces/primeng#4558]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behaviour**
The common css is too broad and can cause unexpected changes, I had a problem with the one in this commit: 39e63f38bc18af9b15f6fd5fa964c8aba5d71ff9 After I upgraded to 5.x some of my buttons were messed up (they lost their border radius)

**Expected behaviour**
CSS classes should only change primeng specific components (using a wrapper)

**Comment by cagataycivici** [comment]
Please create separate tickets for each case, as this issue itself is too broad. Feel free to send a PR as well.
