### ISSUE TITLE
PrimeNG [datatable] filterMatchMode="lte", is it working in PrimeNG 5.0.2?

### ISSUE THREAD

**Issue by helloneoberg** [primefaces/primeng#4563]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview

**Current behavior**

I read your user guide ver 6.1

filterMatchMode defines which built-in filtering algorithm would be used per column, valid values
for this attribute are;- 
startsWith: Checks if column value starts with the filter value.
endsWith: Checks if column value ends with the filter value.
contains: Checks if column value contains the filter value.
exact: Checks if string representations of column value and filter value are same.
**lt: Checks if column value is less than the filter value.
**lte:** Checks if column value is less than or equals the filter value.
**gt:** Checks if column value is greater than the filter value.
**gte:** Checks if column value is greater than or equals the filter value.**
equals: Checks if column value equals the filter value.
in: Checks if column value is in the collection of the filter value.

Is lt, lte, gt, gte working in "primeng": "^5.0.2"?

**Expected behavior**

Expected to work in "primeng": "^5.0.2"

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Window 10

* **Angular version:** 2.0.X

Angular 4.3.0

* **PrimeNG version:** 2.0.X

PrimeNG 5.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome 62.0.3202.94

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.3
* **Node (for AoT issues):** `node --version` =

**Comment by sudheerj** [comment]
The filtermatchmode values doesn't support numeric comparison operators and it is clear from the doc as well. V6.1 guide is for PrimeFaces but not PrimeNG.

**Comment by helloneoberg** [comment]
Thank you so much. Can you point me to the documents for PrimeNG?

**Comment by sudheerj** [comment]
There is no separate apart from showcase documentation.

**Comment by helloneoberg** [comment]
Thank you @sudheerj
