### ISSUE TITLE
Reactive form support inside DataTable

### ISSUE THREAD

**Issue by alex912004** [primefaces/primeng#4564]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://embed.plnkr.co/6NiGbkqoscwOjzyMnRGI/

**Current behavior**

Input with formControl not working in template p-column. Template 'editor' not working with flag [editable]

**Expected behavior**

Input and template working

**Minimal reproduction of the problem with instructions**

Input in first table or click row in second table
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.0.3

* **PrimeNG version:** 5.0.2

* **Browser:** [Chrome 62 | Firefox 57 ]

 
* **Language:** TypeScript 2.4

* **Node (for AoT issues):** `node --version` =   v6.12.0

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
