### ISSUE TITLE
Calendar invalidDate 

### ISSUE THREAD

**Issue by FiReBlUe45** [primefaces/primeng#4566]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Bug Reports**
The bug is a difference in behavior between local and production development. 

**Current behavior**

When I manually enter a date with an incorrect format, "invalidDate" is added to the error list.

In local it works but it doesn't work production.

IN LOCAL
![image](https://user-images.githubusercontent.com/7797712/33364981-fe645728-d4e6-11e7-9c7f-9f96b5ddc06c.png)

IN PROD
![image](https://user-images.githubusercontent.com/7797712/33364957-e4426754-d4e6-11e7-9536-0b488eecb12c.png)

* **Angular version:** 4.2.4 I can't use version 5

* **PrimeNG version:** 4.1.0

* **Browser:** [all ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 ]

* **Node (for AoT issues):** `node --version` = v7.10.0  

an idea?

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Q5hZgBA6DlXf55UvyVqw?p=preview
