### ISSUE TITLE
Get Lat and Long

### ISSUE THREAD

**Issue by AshishTiwariMEAN** [primefaces/primeng#4567]
How we can get lat and long when we drag marker. Also can you please check my below code with HTML.

**app.componet.ts**
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent {
  options: any;
  overlays: any[];
  title = 'app';

  constructor() { }
  // tslint:disable-next-line:use-life-cycle-interface
  ngOnInit() {
    this.options = {
      center: { lat: 36.890257, lng: 30.707417 },
      zoom: 12
    };
    this.overlays = [new google.maps.Marker({
      position: { lat: 36.879466, lng: 30.667648 }, title: 'Konyaalti'
      , icon: 'assets/map-icon.png', draggable: true
    })];
  }
  handleMarkerDraggend(e) {
   console.log(e.long);
  }
}

HTML ---
<p-gmap [options]="options" [overlays]="overlays" (onOverlayDragEnd)="handleMarkerDraggend($event)" [style]="{'width':'100%','height':'320px'}" ></p-gmap>

Can you please suggest what we can do here also please suggest if any thing wrong in my code.

**Comment by cyberrranger** [comment]
show
https://www.primefaces.org/primeng/#/gmap

i found:

 handleMapClick(event) {
        this.dialogVisible = true;
        this.selectedPosition = **event.latLng**;
    }

and selectedPosition is from typ any
{lat: this.selectedPosition.lat(), lng: this.selectedPosition.lng()}

**Comment by AshishTiwariMEAN** [comment]
import { Component } from "@angular/core";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"]
})
export class AppComponent {
  options: any;
  overlays: any[];
  title = "app";
  selectedPosition: any;
  map: google.maps.Map;
  dialogVisible: boolean;

  constructor() {}
  // tslint:disable-next-line:use-life-cycle-interface
  ngOnInit() {
    this.options = {
      center: { lat: 36.890257, lng: 30.707417 },
      zoom: 12
    };
    this.overlays = [
      new google.maps.Marker({
        position: { lat: 36.879466, lng: 30.667648 },
        title: "Konyaalti",
        icon: "assets/map-icon.png",
        draggable: true
      })
    ];
  }
  handleMarkerDraggend(e) {}
  handleMapClick(event) {
    this.dialogVisible = true;
    this.selectedPosition = event.latLng;
  }
}

If we write e.lat and long then it's getting undefined. This is a center position. So how we can get actual lat and long in this case ?

**Comment by cyberrranger** [comment]
handleMapClick(event) {
this.dialogVisible = true;
this.selectedPosition = event.latLng;
}

was an example from the demo page....

try it once:

handleMarkerDraggend(event) {}
this.dialogVisible = true;
this.selectedPosition = event.latLng;
}

**Comment by AshishTiwariMEAN** [comment]
Thank you for your quick response, Here is my updated code :
 handleMarkerDraggend(e) {
    this.dialogVisible = true;
    this.selectedPosition = e.latLng;
    console.log('Hello' , this.selectedPosition);
  }
Result : 
Hello undefined

**Comment by rohitgrover** [comment]
you can use below function to get latitude and longitude on mouse drag

handleMarkerDraggend(e) {
    console.log(e.overlay.internalPosition.lat());
    console.log(e.overlay.internalPosition.lng());
  }

This will give you the dragged latitude and longitude.

**Comment by AshishTiwariMEAN** [comment]
Thank you much. It's working fine.

**Comment by cagataycivici** [comment]
Please use forum for support requests in the future.
