### ISSUE TITLE
OverlayPanel display position on the page top not related to the div

### ISSUE THREAD

**Issue by govindarajkp** [primefaces/primeng#4568]
I am using the OverlayPanelModule in my application, always the panel display the bottom of the page. not on the proper position.
```
<p-dataTable class="backLogChanges"  scrollable="true"   [value]="changes" [rows]="10" [paginator]="true" [pageLinks]="3" [rowsPerPageOptions]="[5,10,20]" [sortMode]="single" resizableColumns="true" columnResizeMode="expand" tableStyleClass="table-hover" [globalFilter]="gb" (onFilter)="onFilter($event)" *ngIf="!loading"
    [attr.sortField]="defaultSortField()" [sortOrder]="-1" #dt>
        
        <p-column *ngFor="let col of cols" [field]="col.field" [header]="col.header" [sortable]="col.sortable" [filterMatchMode]="col.filterMatchMode" [filter]="col.filter" [style]="col.width?{'width': col.width+'px'}:''">
          <ng-template let-column let-change="rowData" pTemplate="body">
<span (mouseenter)="op2.show($event)">{{ change[column.field] | slice:0:64 }}</span>
</ng-template>
        </p-column>
    </p-dataTable>
```

```
<p-overlayPanel #op2 [dismissable]="true" [showCloseIcon]="true">
    Testing
</p-overlayPanel> 
```

**Comment by govindarajkp** [comment]
after setting appendTo property working fine.
```
<p-overlayPanel #op2 [dismissable]="true" [showCloseIcon]="true" [appendTo]="'body'">
		Testing
	</p-overlayPanel>
```

**Comment by cagataycivici** [comment]
Glad to hear.

**Comment by theNotoriousHxc** [comment]
I had a similar situation with @govindarajkp. In the documentation it's null.  Shouldn't there by a default value for [appendTo]?

**Comment by jbermanwebguru** [comment]
I fixed this by creating a div element with a certain size, and using that as the target when opening the overlay. 

```html
<div
  #overlayTarget
  style="width: 200px; height: 30px; margin-top: -30px;"
></div>
```

```typescript
export class MyComponent {
  @ViewChild('overlayTarget')
  overlayTarget: ElementRef;

  @ViewChild('myDialog')
  myDialog: OverlayPanel;

  @HostListener('click', ['$event'])
  onClick(event: MouseEvent) {
    this.myDialog.show(event, this.overlayTarget.nativeElement);
  }
}
```

**Comment by neotic82** [comment]
> after setting appendTo property working fine.
> 
> ```
> <p-overlayPanel #op2 [dismissable]="true" [showCloseIcon]="true" [appendTo]="'body'">
> 		Testing
> 	</p-overlayPanel>
> ```

it worked for me but in this other way in Angular

<p-overlayPanel #op2 [dismissable]="true" [showCloseIcon]="true" **appendTo="body"**>
        Testing
</p-overlayPanel>

**Comment by fabio-blanco** [comment]
@cagataycivici the default behavior (with appendTo as null) is really bizarre. This should default to body as the class p-overlaypanel defaults to "position: absolute" or this behavior should be better described on the docs page. It took me some time to find out why the overlay panel wasn't working as it should! It's in fact not obvious!
