### ISSUE TITLE
When is the stable release date?  

### ISSUE THREAD

**Issue by ishara** [primefaces/primeng#457]
What is your release plan ? and can I have release road-map?

**Comment by sdmoralesma** [comment]
the release date depends on the release of angular2, you can track the release of ang2 here: https://github.com/angular/angular/milestones. 

As for the primeng roadmap:
> Roadmap
> 
> We need to do a couple of more things to do before releasing 1.0 final, these are fileupload and inputmask components along with enhancements to the datatable. Not definite yet but a spreadsheet component is also being considered. We’d like to do 1.0.final after Angular2 goes final so our roadmap depends on Angular2 release.

Source: http://blog.primefaces.org/?p=3937
Please use the forum for this discussions.

**Comment by luking4** [comment]
Angular2 is released now. Any dates for Primeng release?

**Comment by sdmoralesma** [comment]
Angular2 has not been released: https://github.com/angular/angular/milestones . You are probably referring to the rc2 but keep in mind that this is not the final. Primeng beta9 is scheduled for the last week of June: https://twitter.com/prime_ng/status/744238701962760192?lang=en

Right now (20/June/2016) is difficult to know when will be released either angular2 or primeng (last quarter of the year seems probable). However both projects are very stable (although not production ready).

**Comment by cagataycivici** [comment]
PrimeNG will be released a month after Angular2 final. It still changes between RCs so we can't leave beta now.
