### ISSUE TITLE
the value of the field in the ng-template appears on the next line

### ISSUE THREAD

**Issue by alialtun14** [primefaces/primeng#4570]
When ng-template is used in a p-dataTable component, the value of the field in the ng-template appears on the next line.

The related code part 

`<p-column field="katur_exp" 	header="·Karne·" 		[sortable]="true">`
` <ng-template let-oRow="rowData" pTemplate="body">`
`    <div (click)="vShw_open($event, oRow)">{{oRow.katur_exp}}</div>`
`  </ng-template>`
`</p-column>`

`<p-column field="ogren_exp"	header="·Öğrenci·"         [sortable]="true"  *ngIf="_lFiltr"></p-column>`
`<p-column field="akyil_exp"	 	header="·Akademik Yıl·" [sortable]="true"></p-column>`
`<p-column field="sinif_exp"	 	header="·Sınıf·"	 	[sortable]="true"></p-column>`
`<p-column field="perso_exp"	header="·Öğretmen·" 	[sortable]="true"></p-column>`
`<p-column field="dmy_atarih" 	header="·Tarih·" 		[sortable]="true"></p-column>`
`<p-column field="cgun"		header="·Gelmedi·"	 	[sortable]="true"></p-column>`
`<p-column field="igun"		header="·izinli·" 		[sortable]="true"></p-column>`
`<p-column field="orta"		 	header="·Ortalama·" 	[sortable]="true"></p-column>`
`<p-column field="durum_exp"	header="·Durum·" 		[sortable]="true"></p-column>`
`

![primeng](https://user-images.githubusercontent.com/782196/33375383-050fb52c-d50a-11e7-875a-5490712189e6.jpg)

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Q5hZgBA6DlXf55UvyVqw?p=preview
