### ISSUE TITLE
Calendar with milliseconds

### ISSUE THREAD

**Issue by GermanoGuerrini** [primefaces/primeng#4571]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
My indeed pretty special use case requires a calendar that can handle milliseconds too.
I extended the Calendar and CalendarModule classes to add it to my project.
I was wondering whether you might be interested in a pull request or it's beyond your features scope.
![schermata da 2017-11-29 15-10-09](https://user-images.githubusercontent.com/228778/33379133-81d4cf54-d517-11e7-84b9-9c6d4f1251eb.png)

**Comment by summercongcong** [comment]
Hello,I want to a calendar like your, Can you speak tell me how to do? Thanks. @GermanoGuerrini

**Comment by cagataycivici** [comment]
Sure we can do this in a future release.

**Comment by mccoy1** [comment]
This is quite an old ticket, I'd like to put a plug for this again. This would be a useful addition to the calendar.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
