### ISSUE TITLE
TextArea typing is slow and CPU spikes with keystrokes.

### ISSUE THREAD

**Issue by msalman76** [primefaces/primeng#4574]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/MPKBiMaaxvFNVNvYUe2x?p=preview

**Current behavior**

TextArea typing is lagging when used in Dialog along with a simple DataTable. Specially in IE the typing is extremely slow and CPU spikes through the roof while typing fast in the text area.

**Expected behavior**

TextArea typing should not spike CPU and there should be no lag while typing fast.

**Minimal reproduction of the problem with instructions**

click the show button to pop the dialog which has the TextArea field and start typing fast to see the screen jitters and lag.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome, Firefox but in IE its the worst.
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by ctrl-brk** [comment]
I have a similar issue reported here https://github.com/primefaces/primeng/issues/4452 which was closed for unknown reason. Switching to onPush (though in this case you have to move datatable part to a separate component) helps a bit, but it's not clear in general why datatable is so slow having not that many records.

**Comment by cagataycivici** [comment]
Tracking at;

https://github.com/primefaces/primeng/issues/4688
