### ISSUE TITLE
Edit callback support for custom editors

### ISSUE THREAD

**Issue by TishchenkoAlex** [primefaces/primeng#4575]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
onEditComplete, onEdit, onEditCancel events NOT triggered when column has edit template.

**Expected behavior**
DataTable: onEditComplete, onEdit, onEditCancel events must triggered

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/VDAOqGmveqZW5cW6rL9c?p=preview

**Please tell us about your environment:**
MacOS

* **Angular version:** 5.0.2
* **PrimeNG version:** 5.0.2
* **Browser:** [Chrome 62] 
* **Language:** TypeScript 2.4.2

**Comment by brainsbucket** [comment]
+1
Have you found a workaround ?

**Comment by TishchenkoAlex** [comment]
@brainsbucket no :-(

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
