### ISSUE TITLE
Ptooltip on iOS mobile devices

### ISSUE THREAD

**Issue by agisbert** [primefaces/primeng#4583]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://embed.plnkr.co/ax6qmPkcPrAJ3CphTpFw/
https://embed.plnkr.co/3lhW6PxuCtGCyPkrkXjD

**Current behavior**
In mobile devices, such as ipad and iphones, if any html element has a ptooltip in it, it is required to double tap the screen to perform the action.

**Expected behavior**
Given the problem with the :hover css properties in mobile devices, it would be nice to disable tooltips for these cases. 

**Minimal reproduction of the problem with instructions**
Tap on:

`<a href="https://www.google.com" pTooltip="Im a tooltip"  tooltipPosition="top"></a>`

See the tooltip, tag again to navigate. 

**Please tell us about your environment:**
iOS 11; Iphone se, iphone 6, ipad mini, ipad pro

* **Angular version:** 4.4.4

* **PrimeNG version:** 4.2.1

* **Browser:** [iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
 
* **Language:** [ TypeScript 2.4.2 ]

* **Node (for AoT issues):** `node --version` =   8

**Comment by cagataycivici** [comment]
So proposal is to disable pTooltip on iOS?

**Comment by zealitude** [comment]
Agree to disable, if the pTooltip is attached to a button, it will also affect the button operation in mobile device.

**Comment by cyberrranger** [comment]
@cagataycivici @zealitude same problem here, the double tap is annoying. 
Is there already a solution?

**Comment by DavyDeDurpel** [comment]
There's a workaround.  You could do something like this

[pTooltip]="showTooltip('Remote View')"

Where showTooltip returns null in case it's a mobile browser.
But I totally agree to disable button tooltips on mobile safari as I can't think of any case where a tooltip is useful on a (toggle)button.

**Comment by cyberrranger** [comment]
@DavyDeDurpel thx for your workaround

**Comment by Cobr3n** [comment]
some error 
 ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'text: Add filter'. Current value: 'text: null'.

**Comment by bigantal** [comment]
I overcome the problem with a not too elegant solution.
I added a parent div on top of the input with an onclick event.
`<div #infoIconContainer class="toolTipDiv" (click)="forceFocus()">
	<input #inputField type="text" pTooltip="{{text}}"  ....`
And function does the focus programatically.
`forceFocus() {`
`      if (this._globalService.isIos()) {`
`			this.inputField.nativeElement.blur();`
`			setTimeout(() => {`
`				this.inputField.nativeElement.focus();`
`			}, 100);`
`			return false;`
`		}`
`	}`

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
