### ISSUE TITLE
Document the lazy requirement for virtual scroll

### ISSUE THREAD

**Issue by jdp80** [primefaces/primeng#4584]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/tYCqxKMhajxqrHVbG8EM?p=preview

**Current behavior**
The table updates but the offset top callback does not run, meaning that the changes to data are not visible within the visible component area

**Expected behavior**
Before 4.3.0, virtualScroll did not require lazy loading enabled to work.

**Minimal reproduction of the problem with instructions**
Create a large dataset with a small rows count, observe that the callback of DataTable ScrollableView.onVirtualScroll does not get called unless DataTable.handleChange runs.
With default immutable, this can only happen from the DataTable value setter

**What is the motivation / use case for changing the behavior?**
Documentation does not specify this as a mandatory combination

* **Angular version:** 
* **PrimeNG version:** 
Confirmed in
Angular 4.4.4 + PrimeNG 4.3.0
Angular 5.x + PrimeNG 5.0.0

**Comment by jdp80** [comment]
This also means that local sorting / filtering stop working

**Comment by cagataycivici** [comment]
Will be documented.

**Comment by nate-knight** [comment]
Is lazyloading a requirement for virtual scrolling going forward or is this going to be fixed?

**Comment by cagataycivici** [comment]
Tracked at;

https://github.com/primefaces/primeng/issues/7419
