### ISSUE TITLE
PickList reset filters feature

### ISSUE THREAD

**Issue by s13571** [primefaces/primeng#4589]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
After typing something into filter it stays there untill we manually remove it or change it

**Expected behavior**
It would be great to be able to reset filters from our code. For instance if someone type an email and move all the users from source to target I would like to clear the filters. Now it stays as we typed it with no way to reset it.

* **Angular version:** 5.0.X

* **PrimeNG version:** 4.3.0-rc.2

**Comment by cagataycivici** [comment]
How about adding a reset() method?

**Comment by s13571** [comment]
That would be great

**Comment by cagataycivici** [comment]
Added resetFilter with an example in doc.

**Comment by N1k0la-89** [comment]
[showSourceFilter]="someVarOnCloseBecomesZeroOnOpenBecomesOne > 0"
[showTargetFilter]="someVarOnCloseBecomesZeroOnOpenBecomesOne > 0"

this way you can enable onModalOpen, and disable onModalCLose
