### ISSUE TITLE
Schedule has weird scrollbar inside calender

### ISSUE THREAD

**Issue by truongnmt** [primefaces/primeng#459]
I forked the sample quickstart project and implement Schedule feature in this repo:
https://github.com/truongnmt/primeng-quickstart

Somehow the UI has a weird scrollbar inside the calender:
http://i.imgur.com/gpUyDMR.png

Tested on firefox, chrome display no problem.
Update: same result on hompage http://www.primefaces.org/primeng/#/schedule

**Comment by cagataycivici** [comment]
We're unable to replicate.
