### ISSUE TITLE
p-fileUpload not capturing invalidFileSizeMessageSummary (any of the invalid messages)

### ISSUE THREAD

**Issue by sgentile** [primefaces/primeng#4591]
http://plnkr.co/edit/3gGBMHFNhkaLagspUGt7?p=preview

As you can see the message is the one from the fileupload component, it's not showing my own message

```
<p-fileUpload name="images[]" invalidFileSizeMessageSummary="invalidImageFileSizeMessageSummary" multiple="multiple"
                      maxFileSize="10"> 
                     
                      </p-fileUpload>                                       
                      {{invalidImageFileSizeMessageSummary}}  
```

It should set the invalidImageFileSizeMessageSummary property ?

**Comment by sgentile** [comment]
basically I want to be able to show the message where I want it to be - not hardcoded inside the fileupload control

**Comment by cagataycivici** [comment]
No it doesn't work like that, it is not a variable. We'll consider exposing this if there is more demand.
