### ISSUE TITLE
SlideMenu nested items overlapped by back button

### ISSUE THREAD

**Issue by mfrro** [primefaces/primeng#4592]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/Ynw1EGn1fvk00HJWAxZy?p=preview

**Current behavior**
When using the SlideMenu with nested items, the last item is overlapped by the back button.

**Expected behavior**
All items should be visible.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/Ynw1EGn1fvk00HJWAxZy?p=preview
Versions etc. should be visible in the plnkr.

**Comment by cagataycivici** [comment]
You need to increase viewportHeight property.

**Comment by mfrro** [comment]
@cagataycivici thanks for your response. Increasing the viewportHeight is a solution if I don't want any scrollbars. If I want scrollbars however (e.g. because the menu might be too long otherwise), the last item will not be visible because it's overlapped by the back button. So I'd still consider this a bug.
