### ISSUE TITLE
Chips component limits length of input text

### ISSUE THREAD

**Issue by RandomPrecision1** [primefaces/primeng#4593]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/Ytpv0aiBLh3ljk3Lf8qq?p=preview

**Current behavior**
Check out the plunkr, the chips component limits the length of input text to 10em, even if a longer string is entered into the field. I'm not sure if that's necessary for any reason - I just recently noticed it and thought "hey this is wack"

**Expected behavior**
I would expect the entire chips text field would be visible, if sufficient text is entered.

**Minimal reproduction of the problem with instructions**
Please see the attached plunkr above - I've got two text inputs that are chips-enabled. If you copy the bit of text I have into the two inputs, you'll see the current behavior limits the visible text. My suggested change is to utilize the entire length of the input.

**What is the motivation / use case for changing the behavior?**
I'm developing a system that uses chips where users may copy/paste multiple entries that we translate into chips - this can easily exceed 10em worth of text, so it's cut off, despite there being available space in the input field.

**Please tell us about your environment:**

* **Angular version:** ^4.0

* **PrimeNG version:** ^4.0

* **Browser:** all
 
* **Language:** all

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
