### ISSUE TITLE
DataTable: footerColumnGroup misalignment 

### ISSUE THREAD

**Issue by TishchenkoAlex** [primefaces/primeng#4597]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

table config: 
`<p-dataTable [value]="dataSource" [editable]="true" dataKey="index" [(selection)]="selection" [scrollable]="true" [resizableColumns]="true"
  sortMode="multiple">`

**Expected behavior**
fotter 
**Minimal reproduction of the problem with instructions**
https://youtu.be/8V7wjHH-xZ4

**What is the motivation / use case for changing the behavior?**
misalignment looks worse

**Current behavior**
footerColumnGroup misalignment when resize browser window

**Minimal reproduction of the problem with instructions**
https://youtu.be/8V7wjHH-xZ4

**Please tell us about your environment:**
MacOS

* **Angular version:** 5.0.2
* **PrimeNG version:** 5.0.2
* **Browser:** [Chrome 62] 
* **Language:** TypeScript 2.4.2

**Comment by cagataycivici** [comment]
Please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Q5hZgBA6DlXf55UvyVqw?p=preview

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
