### ISSUE TITLE
Hide p-fileUpload choose button 

### ISSUE THREAD

**Issue by webnegar** [primefaces/primeng#4599]
hi
there are 2 properties in in p-fileUpload for show or hide UploadButton & CancelButton (showUploadButton , showCancelButton), but there is no property for show/hide "choose button", only we can change its label text, is it possible through property binding?

**Comment by cagataycivici** [comment]
Why would you need to hide it?

**Comment by namdeok** [comment]
Hi, even i have similar requirement as i have to show custom choose button in the content,not in the header section.

**Comment by cagataycivici** [comment]
You can just hide it with css. .ui-fileupload-choose should be display:none.

**Comment by ZergHunter3000** [comment]
Same reason you would need to hide the Upload button.  To prevent them from uploading.  This case occurs when [auto]="true", as you no longer need to hide the Upload button to prevent uploading, but rather the Choose button since it automatically starts the upload.

**Comment by ajcastro** [comment]
@cagataycivici it didn't work

**Comment by timgitsit2** [comment]
```
.ui-fileupload-choose {
  display: none !important;
}
```
