### ISSUE TITLE
p-inputMask' is not a known element

### ISSUE THREAD

**Issue by quinhone** [primefaces/primeng#4601]
[Angular]
'p-inputMask' is not a known element:
1. If 'p-inputMask' is an Angular component, then verify that it is part of this module.
2. If 'p-inputMask' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

**Comment by sudheerj** [comment]
I think you forgot to include InputMask module.
