### ISSUE TITLE
Documentation: DataTable paginatorPosition is not showcased

### ISSUE THREAD

**Issue by stedel** [primefaces/primeng#4603]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
PrimeNG currently supports altering the position of a DataTable paginator by the attribute _paginatorPosition_ with values: bottom, top and both. The default setting is bottom.
The documentation of the paginator module does not mention this setting either.

**Expected behavior**
This attribute should be showcased in its showcase at <https://www.primefaces.org/primeng/#/datatable/paginator>.

**What is the motivation / use case for changing the behavior?**
Searching for a way to show the paginator at the top of a datatable lead to the discovery of issue #635, that actually provides a solution.

* **Angular version:** 5.x.x

* **PrimeNG version:** 5.x.x
Current master commit does not include additional documentation.

**Comment by cagataycivici** [comment]
DataTable doc states this, not sure we need a demo for it though. Paginator has no paginatorPosition, this prop belongs to DataTable.

**Comment by richardshergold** [comment]
@cagataycivici where is PaginatorPosition mentioned in the docs - do you have a link please?
