### ISSUE TITLE
p-inputMask component with width: 100%

### ISSUE THREAD

**Issue by quinhone** [primefaces/primeng#4606]
I need to put a class in the p-inputMask component, but it only gives option to put in the input, I need to leave it with width 100%, I tried inline, but it loses the other properties

**Comment by nartc** [comment]
To my understanding, you'd want something like : <p-inputMask someProperty="someClassNameThatHasWidthStyle">

**Comment by quinhone** [comment]
exactly, only that the component does not have property for this, it only for inline

**Comment by nartc** [comment]
Can you please make a plunker addressing your use-case?

**Comment by cagataycivici** [comment]
Please use forum for support requests, issue is not clear to me as well.

```
<p-inputMask styleClass="yourclass"
```

Should work as well.
