### ISSUE TITLE
FilterPlaceHolder property for MultiSelect

### ISSUE THREAD

**Issue by tL4302** [primefaces/primeng#4607]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

**Current behavior**

When I set filter=true on a multiselect, an input shows up that allows me to filter through dropdown options. However the input is blank and it would be nice to customize a placeholder for this.

**Expected behavior**

Allow the user to set the placeholder text in another attribute.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Would be nice to have this kind of UI customization to call out the search box.

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by nartc** [comment]
Made a pull request for this. Just wait for it to be reviewed and merged :)

**Comment by tL4302** [comment]
You guys are the best. I'll keep an eye on it, thanks :)
