### ISSUE TITLE
Datatable virtual scroll can sometimes lead to blank entry lists

### ISSUE THREAD

**Issue by cvtoro** [primefaces/primeng#4608]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
**Virtual Scroll**
If you scroll to load more entries and very quickly scroll back up before the entries finish loading then the grid display is just blank. This behavior is seen from the showcase https://www.primefaces.org/primeng/#/datatable/scroll
![virtual_scroll_blank](https://user-images.githubusercontent.com/8909902/33578871-c909071c-d8fc-11e7-9979-d29c8dd80120.png)

**Expected behavior**
The grid should be displaying the entries at the current scroll position, it looks like lazy load event doesn't get triggered with the updated scroll position.  

**Minimal reproduction of the problem with instructions**
Scroll down to retrieve the next listing then quickly scroll back up. You will see a blank grid
http://plnkr.co/edit/BhY4d6JUKRqk88CRyMbJ?p=preview

**What is the motivation / use case for changing the behavior?**
The entries should be updated accordingly when the scroll position is changed

**Please tell us about your environment:**
Windows

* **Angular version:** 2.0.X
present in version Angular 2 rc 5.0.0

* **PrimeNG version:** 
present in 5.0.2

* **Browser:** all

**Comment by cagataycivici** [comment]
Can you replicate at Showcase?

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.

**Comment by theeGwandaru** [comment]
This issue still exists with p-table
