### ISSUE TITLE
Float Label for Dropdown

### ISSUE THREAD

**Issue by s13571** [primefaces/primeng#4609]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
Every form component except Dropdown have a floating label option. It works with autocomplete so it would be great if it would work with dropdown to keep all inputs the same.

**Expected behavior**
Dropdown has no floating label which makes it look bad in forms.

* **Angular version:** 5.0.X

* **PrimeNG version:** 4.3.0-rc.2

**Comment by cagataycivici** [comment]
#4578
