### ISSUE TITLE
Accordion activeIndex doesn't work initially

### ISSUE THREAD

**Issue by DanielChicot** [primefaces/primeng#4610]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://plnkr.co/edit/9evYJTUINseQ3syIlNQY

**Current behavior**
After upgrading to primeng 5 using an array of integers for activeIndex couple d with multiple = true doesn't seem to work. No tabs are open.

**Expected behavior**
The tabs specified in the activeIndex property should be open

**Minimal reproduction of the problem with instructions**

Please see example at:
https://plnkr.co/edit/9evYJTUINseQ3syIlNQY

**What is the motivation / use case for changing the behavior?**

So that is works as described in the documentation.

**Please tell us about your environment:**

Linux, emacs, yarn, node.

* **Angular version:** 2.0.X
5.0.0

* **PrimeNG version:** 2.0.X
5.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome. Firefox

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.4.2

* **Node (for AoT issues):** `node --version` =   
9.2.0

**Comment by nartc** [comment]
For some reason, `openTabs(): number[] {
    return this._openTabs.map(tab => tab);
  }` works. It might actually require you to make change to the `activeIndex` array to trigger the tabs.

**Comment by DanielChicot** [comment]
Great, so it does, thanks so much,
