### ISSUE TITLE
Calendar default locale

### ISSUE THREAD

**Issue by parisgianluca** [primefaces/primeng#4612]
**I'm submitting a ...** 
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
We have to set the locale for each component within we use the calendar component

**Expected behavior**
Set the locale once and retrieve it in all calendars

**Comment by cagataycivici** [comment]
Set it once where?

**Comment by parisgianluca** [comment]
In a specific TranslationModule which can be inizialized in the app component, you should add a specific translate option on some components, which will pick labels from TranslationModule configuration.

Just an idea, obviously

**Comment by yigitfindikli** [comment]
You can use our new [I18N API](https://primefaces.org/primeng/showcase/#/i18n)
