### ISSUE TITLE
p-autocomplete should support SelectItem

### ISSUE THREAD

**Issue by Mysame** [primefaces/primeng#4622]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
```

It would make a lot of sense to allow a suggestion list of "primeng/components/common/selectitem" to be used in p-autocomplete, bringing it more in line with how p-dropdown works.

This would allow us to pass a list with {label: string, value: any}, instead of mucking about with (buggy #2242) templating and the "field" property.

**Comment by cagataycivici** [comment]
Not sure, many users don't like SelectItem so we had added support for any object for select components lately. This is like going against the general feedback. I'll check 2242 instead.
