### ISSUE TITLE
DataTable column resizing does not consider next column minWith

### ISSUE THREAD

**Issue by vincent** [primefaces/primeng#4624]
**I'm submitting a ...** 
```
[x] bug report
[ ] feature request
[ ] support request
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/zMgAMScZMo9JPENaR8Nc?p=preview

**Current behavior**
Resize the first column, the next one can be sized down to 15px, even if a `minWidth` has been given.

**Expected behavior**
The next column should not be downsized below its `minWidth`

* **Angular version:** 4.4.X

* **PrimeNG version:** 4.3.0

* **Browser:** [all]
 
* **Language:** [all]

**Comment by cagataycivici** [comment]
Merged PR, thank you.
