### ISSUE TITLE
ULTIMA - Deprecated method in nanoscroller

### ISSUE THREAD

**Issue by AndreaBarbasso** [primefaces/primeng#4626]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
No need for plunkr, since it comes out while building.

**Current behavior**
Console warning:
`nanoscroller\bin\css\nanoscroller.css
Node#moveTo was deprecated. Use Container#append.`

**Expected behavior**
Since nanoscroller is deprecated, I think it's time to find an alternative...

**Minimal reproduction of the problem with instructions**
Run a `ng build --prod --aot`.

**What is the motivation / use case for changing the behavior?**
Code and project mantainability.

* **Angular version:** 5.1.0
* **Angular CLI version:** 1.6.0

* **PrimeNG version:** 5.0.2
* **ULTIMA version:** 5.0.0

* **Node (for AoT issues):** 8.5.0

**Comment by cagataycivici** [comment]
We've created our own scroller in PrimeNG so will replace nano with p-scrollPanel after 5.1 so this issue is obselete as a result.
