### ISSUE TITLE
Need AngularJS UI-GRID in PrimeNG

### ISSUE THREAD

**Issue by nsksaisaravana** [primefaces/primeng#4629]
I love all components in PrimeNG but I am missing UI-GRID in PrimeNG. AngularJS UI-GRID is an awesome component but same functionality component is not available in the PrimeNG. Please add it.

http://ui-grid.info/docs/#/tutorial

**Comment by sudheerj** [comment]
It is available as datatable component in PrimeNG library. You can raise a feature request for any new features.

**Comment by nsksaisaravana** [comment]
@sudheerj I am missing Expandable grid, UI-GRID has got separate columns for the child grid and during run time we can assign click events.

**Comment by nsksaisaravana** [comment]
@sudheerj  The save state feature allows you to save the current look of the grid and restore it upon returning to the grid

**Comment by nsksaisaravana** [comment]
Please check the screenshot below, header can different columns and details can have different columns. During run time i can assign image according to the document type and assign click events during run time.

![image](https://user-images.githubusercontent.com/17681573/33804645-5d6201ca-ddfd-11e7-829c-ce1338c96646.png)


![image](https://user-images.githubusercontent.com/17681573/33804616-b59fa794-ddfc-11e7-97ad-b6813df402b5.png)

**Comment by cagataycivici** [comment]
Please create a specific feature request like feature x for PrimeNG datatable.
