### ISSUE TITLE
Autosize treetable columns

### ISSUE THREAD

**Issue by finalxcode** [primefaces/primeng#4630]
Hi,

I think this would be a great addition to the TreeTable component to be able to specify that a column should resize either to its content's width or header width.

Thanks !

**Comment by cagataycivici** [comment]
We'll check this in new TreeTable implementation, thanks.

**Comment by finalxcode** [comment]
@cagataycivici that's great!

**Comment by cagataycivici** [comment]
TreeTable will be reimplemented, please monitor;

#4813
