### ISSUE TITLE
Lightbox content behind the overlay mask when opened from a Dialog

### ISSUE THREAD

**Issue by sebaiona** [primefaces/primeng#4633]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/Hzii86TTawHy1PUxF4FV?p=preview

**Current behavior**

When we open a Lightbox from a Dialog, there is a problem of positions of layers.
The content of the lightbox (I put a random pdf in the plunkr) is not accessible because the mask is above it.

**Expected behavior**

Be able to access the lighbox content, for example a pdf like in my plunkr example.

**Minimal reproduction of the problem with instructions**

Just click on "`Show`" (opens the dialog) and then on "`See PDF in Lightbox`"

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.0.X

* **PrimeNG version:** 5.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by cagataycivici** [comment]
Can you try appendTo="body" on lightbox?

**Comment by sebaiona** [comment]
Thanks a lot!!

I didn't think about that. Your solution works perfectly!
