### ISSUE TITLE
Enhancement: include columns IDs when exporting via exportCSV in datatable

### ISSUE THREAD

**Issue by mmlitvin** [primefaces/primeng#4637]
I'm submitting a ...

[ x] feature request
For export function in datatable I'd like the capability to specify what data from column should be exported: column.field versus column.header or in fact both. 

As it currently stands, datatable exportCSV function will export headers if they exist, and if not then fields
 //headers
        for(let i = 0; i < this.columns.length; i++) {
            let column = this.columns[i];
            if(column.exportable && column.field) {
                csv += '"' + (column.header || column.field) + '"';
                
               

My Use Case: 
I have a table with data that needs to support both: export and import function. 
In order to support import I need to identify columns in exported data. Using columns titles for this purpose  is a bad idea since my web app is internationalized. 
So  if user1 exports in russian I have russian headers in files. 
If english user2 tries importing this file - it will fail unless I iterate over all possible translations of headers. It is not efficient and error prone. Best approach would be to have both: column Names and column Ids

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
