### ISSUE TITLE
Pagination is reset to first page after deleting a row from second page

### ISSUE THREAD

**Issue by syeddk** [primefaces/primeng#4639]
Hi,

I have 27 rows table with 25 max rows per page, when i try to delete a row from second page pagination is reset to first page. 

i have splice in delete method
ex: resultarray.splice(26, 1);
<p-dataTable  [value]="resultarray" [rows]="25" paginator="true" paginatorPosition="top" pageLinks="0">

i am using angular 2.3.1 and primeng 2.0.3 versions

Any suggestions please

**Comment by cagataycivici** [comment]
Please use forum for questions. Please update your versions as well since they are very old.
