### ISSUE TITLE
DataTable columns reorder doesn't work in FF

### ISSUE THREAD

**Issue by Karolis92** [primefaces/primeng#464]
DataTable's columns reorder feature doesn't work in Firefox.
Tried on 46.0.1 and 47 versions.
Reproducible in http://www.primefaces.org/primeng/#/datatablecolreorder

**Comment by mjsafa** [comment]
Same Issue. 1+

**Comment by anupamarachuri** [comment]
Did this issue get fixed? I dont see the reorder working withe syntax on their website. Please let me know if anyone was able to get it right.

**Comment by cagataycivici** [comment]
Works for me on 51.
