### ISSUE TITLE
p-dropdown won't close ios keyboard after selection

### ISSUE THREAD

**Issue by helloneoberg** [primefaces/primeng#4640]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview

**Current behavior**

After selection, user will still see the Done button right at the bottom of the screen

**Expected behavior**

After selection, the Done button will disappear

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

To user, if they see the Done button, they are wondering if they still have undone step to do

**Please tell us about your environment:**

IOS 11

* **Angular version:** 2.0.X

Angular 4

* **PrimeNG version:** 2.0.X

PrimeNG 4.3.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 IOS 11 Safari

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.0 ES5

* **Node (for AoT issues):** `node --version` =   
Node 6.3

**Comment by cagataycivici** [comment]
#4082
