### ISSUE TITLE
p-dialog - How to detect scroll position top or bottom when modal content scroll

### ISSUE THREAD

**Issue by smartHasmukh** [primefaces/primeng#4642]
I am making chat module using prime Ng. I have used `p-dialog` for chat screen. When user scroll to top position `0(ZEER)` then I have to show chat history same as `Skype`.
I need to detect top and bottom position using `ui-dialog-content ui-widget-content` these class(section). 
In p-dialog set dynamic height in `ui-dialog-content ui-widget-content` class. So I want to get the position top or bottom using this class.

** OR **
If you have any p-dialog content scroll method then Please suggest me.

Thanks in Advance

![traddle](https://user-images.githubusercontent.com/8941195/33818663-2a6669fe-de6c-11e7-8e1a-61cb036cc75d.png)

**Comment by cagataycivici** [comment]
Please use forum for questions, thank you.

**Comment by smartHasmukh** [comment]
@cagataycivici  Why close this issue?
