### ISSUE TITLE
Datatable: Frozen columns cell height not consistent.

### ISSUE THREAD

**Issue by dlinx** [primefaces/primeng#4643]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/rea2UKF1UtrsJ7hZuM1e?p=preview

**Current behavior**

Table cell height not consistent for frozen columns.

**Expected behavior**

All cells in one row should have same height.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.2.4

* **PrimeNG version:** 4.3.0

* **Browser:** [ Chrome 62.0.3202.94]

 
* **Language:** [all ]

* **Node (for AoT issues):** `node --version` =

**Comment by JacobSiegle** [comment]
See notes in #644. The only fix for now is to statically set the height of your cells or remove text wrap.

**Comment by cagataycivici** [comment]
This is documented at datatable documentation, feel free to provide an alternative solution as well.
