### ISSUE TITLE
Schedule locale not working

### ISSUE THREAD

**Issue by jbiversen** [primefaces/primeng#4645]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/kX6xArNoS5YpVw2K162D?p=preview

**Current behavior**

The buttons at the top of the schedule are not translated into danish, even though the p-schedule tag has the locale attribute set to "da" and the index.html file should load the danish locale file.

* **Angular version:** 2.0.X

Angular 4.2.6 (see plunkr)

* **PrimeNG version:** 2.0.X

PrimeNG 5.0.2 (see plunkr)

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome 62.0.3202.94 Windows 10

**Comment by cagataycivici** [comment]
Probably you haven't included the translations;

https://fullcalendar.io/docs/text/locale/

**Comment by jbiversen** [comment]
Thanks for the answer. I did include the the translation (see the plunkr) using this line in index.html

<script src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.7.0/locale/da.js'></script>

**Comment by ptrovatelli** [comment]
Hi,
For i18n, apart from the basics with the "locale" variable, you also need to do the below changes:
1) package.json: add jquery-datepicker (npm i jquery-datepicker --save)
2) .angular-cli.json: add your locale from moment and fullcalendar, include jquery-datepicker source code under the "scripts" part

If you're not using angular-cli, the 2) may be different. For example using "angular-meteor" i did it by adding the CDN scripts into the index.html

Example with angular-cli, under scripts section (+ for added lines. Beware of adding the fullcalendar locale after the main fullcalendar source code)
```
         "../node_modules/moment/moment.js",
+        "../node_modules/moment/locale/fr.js",
+        "../node_modules/jquery-datepicker/jquery-datepicker.min.js",
         "../node_modules/chart.js/dist/Chart.js",
         "../node_modules/fullcalendar/dist/fullcalendar.js",
+        "../node_modules/fullcalendar/dist/locale/fr.js",

```

You may find a primeng fork with a working i18n for French here: 
https://github.com/ptrovatelli/primeng/tree/Scheduledemo_i18n_French

See the full diffs here for adding i18n: 
https://github.com/ptrovatelli/primeng/compare/master...ptrovatelli:Scheduledemo_i18n_French

NB: I am a little bit ahead of the main primeng repo with some of the libraries at the moment and I have added some functionalities in the demo but the instructions given above should suffice to get i18n working. 
In case of issues, see full diff from the main primeng repo: 
https://github.com/primefaces/primeng/compare/master...ptrovatelli:Scheduledemo_i18n_French

**Comment by jbiversen** [comment]
I have found the solution to my own problem: I was importing jQuery later in the code which overwrote the fullcalendar function added to the jQuery object.

**Comment by cagataycivici** [comment]
Added docs
