### ISSUE TITLE
Serenity Theme - Datatable Checkbox event

### ISSUE THREAD

**Issue by kvabhishek** [primefaces/primeng#4647]
I have recently bought the Serenity Theme from PrimeNG Angular. We are using Angular 4 for development.

In the Datatable, 'on mouse click' on each row the checkbox is checked as well as the row is selected. When checkbox is unchecked or checked there is no event triggered. The event is triggered only when row is selected and unselected.

Since application users can click on checkbox as well as rows, and also we have multi-select options as well, this event is key for us to proceed. Please help to provide this event on click of checkbox in the datatable.

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Q5hZgBA6DlXf55UvyVqw?p=preview

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
