### ISSUE TITLE
put colors on mutlitple steps

### ISSUE THREAD

**Issue by vlafargue** [primefaces/primeng#4648]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[x] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
Hello world, I was trying to implemente a step module in my project but I'm exposed to a probleme. I was trying to make a step by step registration and to put each step passed on the same color as an active step and keep the incoming step in another style. Like this
![image](https://user-images.githubusercontent.com/26387042/33838209-1cd17144-de8f-11e7-8c9b-342a1c16ee0d.png)

I don't know if it's possible with some skills or not. I known that seems a special behaviour but tell me your opinion about this point.

**Comment by sudheerj** [comment]
You can't make it with style and styleClass attributes because they will be applied on container. The decision needs to be reviewed by seeing the behavior of steps component in the web.

**Comment by cagataycivici** [comment]
Please use forum for support requests.
