### ISSUE TITLE
dataTable when scrollable and scrollheight is set - style issue

### ISSUE THREAD

**Issue by Floppynator** [primefaces/primeng#465]
a dataTable style is broken when scrollable and scrollHeight attribute is set.

**Comment by rahuja910** [comment]
any update on this?

**Comment by sittingbool** [comment]
Same here. IfI set a percentage value into the scrollHeight it sets the max-height of the body to 0px

**Comment by sittingbool** [comment]
The error happens Here: https://github.com/primefaces/primeng/blob/master/components/datatable/datatable.ts#L1620.

My Setup: I have the table inside a tab-panel. The first tab has a selection which changes the list shown in the table, the second has the table. After I change tabs, select and come back to the table this line will set 0px and never be called again.

**Comment by cagataycivici** [comment]
Unable to replicate with newer versions, please try with 2.0.2.

**Comment by BartoszBaczek** [comment]
This issue still affects me - both on 2.0.2 and 2.0.3

**Comment by cagataycivici** [comment]
Can you provide a plunkr please?

**Comment by BartoszBaczek** [comment]
Yup, I'm working on it right now.

**Comment by cagataycivici** [comment]
Thanks, we'll do 4.0.RC1 on wednesday, I can ask my colleague to check this until then.

**Comment by BartoszBaczek** [comment]
There is everything fine with with scrollWidth. The scrollHeight is the one, that seems to have problems:

http://plnkr.co/edit/lwsjtNJCWW5qEBtOOXiY?p=preview

**Comment by ericrovtar** [comment]
Was there ever a fix for this? I'm still finding the issue in the latest npm package.
