### ISSUE TITLE
DataTable - Selection bind is not updated on touch screen devices

### ISSUE THREAD

**Issue by brunonm** [primefaces/primeng#4651]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/BBRcy61lw7F4db2T9Z5x

**Current behavior**

When select a row on touch screen devices, the selection bind is not updated. You can check this behaviour with "ctrl+shift+m" on Chrome, selecting a row, selecting another row and see the console.

**Expected behavior**

The selection bind should update.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.3.X

* **PrimeNG version:** 4.3.X

* **Browser:** all

 
* **Language:** all

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Touch screen desktop/laptops or mobile devices? Can you try with [metaKeySelection]="false"

**Comment by brunonm** [comment]
@cagataycivici 
Both types. I'll test the [metaKeySelection] option.

**Comment by brunonm** [comment]
@cagataycivici 
When metaKeySelection is true, the selection bind is always undefined, regardless of the device type.
You can check the plunkr above. :-)

**Comment by cagataycivici** [comment]
I think this is duplicate;

https://github.com/primefaces/primeng/issues/4335

Try with PrimeNG 5.0.2 please

**Comment by brunonm** [comment]
@cagataycivici this is another bug and continues on 5.0.2 release. Could you re-open this issue?

**Comment by brunonm** [comment]
Thank you, @cagataycivici.
