### ISSUE TITLE
Clicking on a checkbox in a DataTable sortable column header shouldn't sort the table

### ISSUE THREAD

**Issue by danbanswer** [primefaces/primeng#4656]
**I'm submitting a ...**  

[X] bug report

This is the same as #3361 (which was apparently closed because the submitter didn't create a plunkr)

**Plunkr Case (Bug Reports)**

http://plnkr.co/edit/ZrqZ5lJbFLl8m67CmLIJ?p=preview

**Current behavior**
Trying to use p-checkbox in a filter template for a sortable column in a DataTable.
Clicking on the checkbox also sorts data.

This also happens if you add a p-multiselect and click on one of the checkboxes in the dropdown. It probably happens with other controls or plain html elements.

**Expected behavior**
Clicking on a checkbox or other control in the header (except for the up/down arrow of course) should not sort the data in the column.

**Minimal reproduction of the problem with instructions**
Go to the plunkr and click on the checkbox a few times 

**Please tell us about your environment:**
MacOS 10.13.1

* **Angular version:** 4.2.6

* **PrimeNG version:** 4.1.0

* **Browser:** All the browsers I checked - Chrome, Safari and Firefox

**Comment by cagataycivici** [comment]
Unable to replicate with 5.0.2, please try with a newer version.

**Comment by danbanswer** [comment]
Confirmed - fixed for (at least) p-checkboxes and p-multiSelects in 5.0.1.
