### ISSUE TITLE
Document rowStyleMap usage in DataTable

### ISSUE THREAD

**Issue by TheParad0X** [primefaces/primeng#4658]
Hi,

I am struggling with the rowStyleMap of the datatable. I would like to change the color of a row depending on its content. How can I do this ? I could not find any good example, and the documentation is a bit dire.

Cheers,
Tim

**Comment by Aarkon** [comment]
In Angular, you can define a variable (e.g. named 'rowStyleMap') in the component like so:

`
  rowStyleMap = {'black': 'strong'};
`

In the html of the datatable, apply it like this:

`<p-dataTable .. [rowStyleMap]="rowStyleMap" dataKey="color">"`

Now, whenever a row has the string 'black' in it's column 'color', the styling will be applied.
