### ISSUE TITLE
Custom content support for DataTable Loader

### ISSUE THREAD

**Issue by waldo2188** [primefaces/primeng#4662]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
The datatable spinner is made with a font from Font Awesome.

**Expected behavior**
PrimeNg has a wonderful ProgressSpinner. I'm asking myself, how to user the ProgressSpinner in place of the one made with Font Awesome.
I think it will be a good thing if we can choose between the two spinner type.

**Comment by sudheerj** [comment]
Are you expecting that spinner should support customized icons apart from font-awesome icons?

**Comment by waldo2188** [comment]
I'm expecting that the spinner of the datatable component can be the one displayed by the ProgressSpinner  component.

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
