### ISSUE TITLE
the position of p-menu

### ISSUE THREAD

**Issue by alialtun14** [primefaces/primeng#4665]
1.  When I click the menu link on the page,  p-menu appears far away from the menu link.

2.  Second problem is the width of the menu item is not enough to set the menu-item on the line.

The related code I used

`
// template
<p-menu #mLst popup="popup" [model]="mListe" appendTo="body"></p-menu>

// ngOnInit 
this.mListe = [{ label: '·Okul Sözleşmesi Ekle·',  icon: 'ui-icon-add',  command: (evt)=>this.vWrp_open(evt, 1)},
{ label: '·Anaokulu Sözleşmesi Ekle·', icon: 'ui-icon-add',  command: (evt)=>this.vWrp_open(evt, 2)}]

// CSS
body .ui-menu .ui-menu-list li.ui-menuitem .ui-menuitem-link{ 
padding: .625em 0 0 .625em;  
}

`
![menu](https://user-images.githubusercontent.com/782196/33980878-f579dc30-e0aa-11e7-9bdf-1a414d20ce0b.png)

**Comment by sudheerj** [comment]
Not able to replicate the issue on showcase. The second issue can be solved using style and styleClass properties of menuitem. Please create a plunker example if you still can able to replicate the issue. Closing for now.

**Comment by hmoreras** [comment]
@alialtun14 , Did you found a solution for the first point ? I am having the same issue.

**Comment by alialtun14** [comment]
I found the solution. The solution is to put each menu icons into separete divs. 

The related code I have used

`<div class="ui-md-1 ui-g-12"> 
<div class="ui-g-3"> <a (click)="search($event)"> <i class="fa ui-icon-search"> </i></a></div>
<div class="ui-g-3"> <a (click)="sdetail($event)"> <i class="fa ui-icon-arrow-drop-down"> </i></a></div> 
<div class="ui-g-6"> <a (click)="menu($event)"> <i class="fa ui-icon-more-vert"> </i></a></div>
</div>`

**Comment by alialtun14** [comment]
I found the solution. The solution is to put each menu icon into seperate div.

The code part I have used

    `  
    <div class="ui-md-1 ui-g-12 pad00"> 
        <div class="ui-g-3"> <a (click)="src1($event)"> <i class="fa ui-icon-search"> </i></a></div>
        <div class="ui-g-3"> <a (click)="src2($event)"> <i class="fa ui-icon-arrow-drop-down"></i></a></div> 
        <div class="ui-g-6"> <a (click)="menu($event)"> <i class="fa ui-icon-more-vert"> </i></a></div>
    </div>
    `
