### ISSUE TITLE
Dropdown should keep scroll position

### ISSUE THREAD

**Issue by OlenaTaras** [primefaces/primeng#4666]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/wbYeoCefvCttkFFA5JMW?p=preview

**Current behavior**
Click on dropdown, and observe: the content inside panel is scrolled to bottom. Close the dropdown and then open it again: second time the content is scrolled to the top.

**Expected behavior**
The dropdown should always show the top of the content when panel is opened. 

**Minimal reproduction of the problem with instructions**
Twice reopen the dropdown at this example and you will see the bug:
http://plnkr.co/edit/wbYeoCefvCttkFFA5JMW?p=preview

**What is the motivation / use case for changing the behavior?**
When users open the dropdown, they shouldn't be confused.

**Please tell us about your environment:**
Windows 10 version 1607

* **Angular version:** 2.0.X
Angular 4.4.6

* **PrimeNG version:** 2.0.X
PrimeNG 4.3.0

* **Browser:** 
Version 63.0.3239.84 (Official Build) (64-bit)
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Thought about this and current code scrolls to the selected item which is the requested behavior by the users in the past so no action will be taken.
