### ISSUE TITLE
autocomplete onModelChange should be be triggered onInput if forceSelection is true

### ISSUE THREAD

**Issue by huineng** [primefaces/primeng#4668]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
```
**Current behavior**

onModelChange is being emitted after each keystroke (input).. when forceselection is enabled this should not be the case

**Expected behavior**

in a reactive form we listen to form validations, when an autocomplete value is required, then we want only that control to be valid once the value is selected.

So the onmodelchange should be removed from the oninput if the forceselection is true
https://github.com/primefaces/primeng/blob/master/src/app/components/autocomplete/autocomplete.ts#L303

```
let value = (<HTMLInputElement> event.target).value;
        if(!this.multiple && ! this.forceSelection) {
            this.onModelChange(value);
        }
```

**Comment by a-trifyllis** [comment]
The problem with this is that if on the FormControl we have a required Validator if we write a value in autocomplete then manuall delete it (with backspace) the valueChanges is not fired on the form
