### ISSUE TITLE
Documentation issue for tree - wrong text in table Events

### ISSUE THREAD

**Issue by SlingingCode** [primefaces/primeng#4671]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

https://www.primefaces.org/primeng/#/tree
Under headline Events. In the table, last row for event onNodeDrop, the column Description contains wrong information.

> Callback to invoke when a node is selected with right click

**Expected behavior**
A more fitting information text.

**Minimal reproduction of the problem with instructions**

https://www.primefaces.org/primeng/#/tree
Scroll to headline Events

**Comment by sudheerj** [comment]
Thanks, Updated.
