### ISSUE TITLE
Frozen Columns support for Virtual Scroll

### ISSUE THREAD

**Issue by ViktorPlohl** [primefaces/primeng#4672]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

https://plnkr.co/edit/OGsSjP7H9Lws96hxsX9V?p=preview

**Current behavior**
Virtual scroll with frozen column makes the datatable unusable.

**Expected behavior**
Virtual scroll with frozen column should work

**Minimal reproduction of the problem with instructions**
See:
https://plnkr.co/edit/OGsSjP7H9Lws96hxsX9V?p=preview

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [ all ]
 
* **Language:** [ all]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
