### ISSUE TITLE
DataScroller buffer not documented

### ISSUE THREAD

**Issue by mfrro** [primefaces/primeng#4673]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
Don't know if this is the right place to report this, but:
In the documentation of the datascroller (https://www.primefaces.org/primeng/#/datascroller) the property 'buffer' is only visible in the source of the example, but isn't listed as a property. I'm reporting it because I spent quite a while trying to figure out how to implement buffering, but couldn't find anything.

**Comment by sudheerj** [comment]
Fixed.Thanks.
