### ISSUE TITLE
Datatable export to CSV exports raw data

### ISSUE THREAD

**Issue by mirkara** [primefaces/primeng#4675]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[X] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

**Current behavior**

Datatable export to CSV exports the pre-transformed data. For example if I have 
```
    <p-column field="date" header="Data">
      <ng-template let-col let-item="rowData" pTemplate="body">
        <span>{{item[col.field] | date: "dd/MM/yyyy"}}</span>
      </ng-template>
```
And the data is saved as a long and the date pipe transforms that into dd/MM/yyyy. 

The CSV will contain the long and no dd/MM/yyyy

**Expected behavior**

The CSV should export the transformed data, dd/MM/yyyy.

**Minimal reproduction of the problem with instructions**

In a datatable show a transformed field of an object. 
Export to CSV

The datatable will show the transformed field but the CSV will have the raw data.

Eg
```
object = { name: '123456' }

...
    <p-column field="name" header="Data">
      <ng-template let-col let-item="rowData" pTemplate="body">
        <span>{{item[col.field] | date: "dd/MM/yyyy"}}</span>
      </ng-template>
...

date transforms 123456 into dd/MM/yyyy
```

**What is the motivation / use case for changing the behavior?**

The CSV data is difficult to comprehend without the transformation.

Ubuntu, VS Code, npm

    Angular version: 4.3.5

    PrimeNG version: 4.3.0

    Browser: [Chrome Version 62.0.3202.94 (Official Build) (64-bit) | Firefox 57.0 (64-bit) ]

    Language: [Typescript 2.3.4]

    Node (for AoT issues): node --version =
    n/a

**Comment by cagataycivici** [comment]
I don't think we can access the ng-template contents and the rendered output of it so not sure how to solve this.

**Comment by mirkara** [comment]
Is there an alternative way to generate a CSV? Or is the only option to transform the data in the data object and not use UI pipes to transform the data?

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
