### ISSUE TITLE
Minify the html template in  primeng distributions

### ISSUE THREAD

**Issue by btpka3** [primefaces/primeng#4677]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ *] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
None

**Current behavior**

Currently PrimeNG using inline html template (Such as [p-panel](https://github.com/primefaces/primeng/blob/5.0.2/src/app/components/panel/panel.ts#L11) etc). But it was compiled to javascript string which can not be minfied( remove blanks, new lines, comment etc). This increase the http traffic a little.

**Expected behavior**
- Minify the inline html template.
- Or using standalone html template instead of inline one

**Minimal reproduction of the problem with instructions**
None

**What is the motivation / use case for changing the behavior?**

Decrease the http traffic.

**Please tell us about your environment:**

- angular cli : 1.6.1
 

* **Angular version:** 5.1.1

* **PrimeNG version:** 5.0.2

* **Browser:** [all]

 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =   8.1.1

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
