### ISSUE TITLE
Import functionality

### ISSUE THREAD

**Issue by ravikanje** [primefaces/primeng#4678]
Hi Team,

Like dataexporter is there any control for Importing excel data to prime ng grid

**Comment by sudheerj** [comment]
No, there is no component like that. I didn't find these kind of components in the web too.

**Comment by ravikanje** [comment]
Sudheerj thanks for your quick reply,

do we have any option for Importing excel data and binding to prime ng grid. or do we need to import excel data with any other npm module and then prepare data model for prime ng grid ,

Thanks in advance,

**Comment by sudheerj** [comment]
Yes, you need to use external modules to extract the excel content and then prepare the data model for primeng table/grid.
