### ISSUE TITLE
Dropdown inside container with overflow: hidden 

### ISSUE THREAD

**Issue by e-oz** [primefaces/primeng#468]
Hello. I'm impressed how much useful directives you have - thank you!

There is one issue with dropdown: when parent element (container) has "overflow: hidden" and fixed height, dropdown menu will be clipped after container's height limit.
<img width="1206" alt="screen shot 2016-06-08 at 16 39 23" src="https://cloud.githubusercontent.com/assets/526352/15898470/c2af36ae-2d98-11e6-99b0-8a20196bb0ca.png">

I know one way how it can be solved (and how ng-material is doing it): attach popup menu part as a child of the `<body>`, with fixed position, intercept all key-down events and all scroll events, right from the  `<body>`.
But maybe there are other ways - you have a lot of elements done and it means you have a lot of experience, so maybe you'll find even better ways to fix it.

**Comment by brian428** [comment]
Just a note: the same thing happens with the Calendar component.

**Comment by gilhanan** [comment]
you can try `<p-dropdown appendTo="body" ...`

**Comment by brian428** [comment]
Doesn't work, unfortunately. :-/

**Comment by cagataycivici** [comment]
appendTo="body" fixes this for me.

**Comment by brian428** [comment]
I think the problem I have with appendTo is actually the positioning/available space calculation issue I created in https://github.com/primefaces/primeng/issues/2128.

**Comment by akshaya-r** [comment]
> you can try `<p-dropdown appendTo="body" ...`

this worked for me!

**Comment by mikeveltman** [comment]
> you can try `<p-dropdown appendTo="body" ...`

This resets the styling I have made for the dropdown menu.

**Comment by mbsanchez** [comment]
appendToBody doesn't work for me.

**Comment by mbsanchez** [comment]
I solved my issue, just i forgot to import the BrowserAnimationsModule

import {BrowserAnimationsModule} from '@angular/platform-browser/animations';

**Comment by psriniv** [comment]
Worked for me

**Comment by AlHanouf-BH** [comment]
it didn't work out for me. Tried as below shown :

![image](https://user-images.githubusercontent.com/88277365/171144911-7d29d8eb-3b62-471e-b7bb-8901d34c428f.png)
