### ISSUE TITLE
PrimeNg Growl component causes Protractor synchronisation with Angular failure

### ISSUE THREAD

**Issue by aozolin** [primefaces/primeng#4681]
**I'm submitting a bug report**

**Current behavior**
Growl component uses timeout() so the protractor thinks that the angular is busy and waits until timeout forever. That causes such test cases to fail. 
It looks like to fix the issue you need to put the timeout to outside of angular zone.
Please follow the link - #https://github.com/angular/protractor/issues/4584. It describes the issue.

**Expected behavior**
Protractor works with Growl component successfully.

**Minimal reproduction of the problem with instructions**
1. Download and unzip attached test project
2. Cd to the project folder
3. Run node/npm install    to build the project
4. Run node/npm run pree2e    to download required drivers
5. Run node/npm run e2e:dev  to run test case and reproduce the issue

**What is the motivation / use case for changing the behavior?**
The existing behaviour makes auto test cases unworking and blocking autotesting at all.

**Please tell us about your environment:**
The issue is reproducible using PrimeNg showcase from https://www.primefaces.org/primeng/#/growl 

* **Angular version:** 2.0.X
The issue is reproducible using PrimeNg showcase from https://www.primefaces.org/primeng/#/growl 

* **PrimeNG version:** 2.0.X
The issue is reproducible using PrimeNg showcase from https://www.primefaces.org/primeng/#/growl

* **Browser:** 
all
 
* **Language:**
all

* **Node (for AoT issues):** `node --version` =   v6.9.5
[e2e.zip](https://github.com/primefaces/primeng/files/1567938/e2e.zip)

**Comment by tjlittle** [comment]
+1. This issue is huge for us. I'd rather not use PrimeNG at all, then have to depend on wait sleeps in end-to-end tests.

**Comment by yelhouti** [comment]
this Bug has been reintroduced in Toast
