### ISSUE TITLE
Listbox with multiselect checkbox click text unselects all

### ISSUE THREAD

**Issue by orwtech** [primefaces/primeng#4689]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a feature request for the Listbox with multiselect checkboxes.**  (check one with "x")
```
Having a listbox with multiselect and checkboxes one can click the checkboxes and select more items in the list. But when by accident you click the text of one of the checkboxes then the entire selection is leared and only the last one is selected. I know you can avoid the accident from happening holding down the Ctrl key while clicking the text - but most end-users are not aware of this.

Therefore it would be a nice extension to have a attribute on the p-listbox to be able to override this default behavior.

[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** > 4.3.X

* **PrimeNG version:** > 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Set [metaKeySelection]="false" to disable this behavior.
