### ISSUE TITLE
 PrimeNG DataTable - excel like filter missing

### ISSUE THREAD

**Issue by sanket360** [primefaces/primeng#469]
I am using PrimeNG beta7 with Angular2 RC.

I my sample of p-dataTable, I have enabled column filter using [filter]="true" but this just give normal text filter option.

```
<p-dataTable [value]="products" [rows]="2" [paginator]="true" [pageLinks]="3" >
    <header>List of products</header>
    <p-column field="productName" header="productName" [sortable]="true"></p-column>
    <p-column field="productCode" header="productCode" [filter]="true"></p-column>
    <p-column field="releaseDate" header="releaseDate" [filter]="true"></p-column>
    <p-column field="description" header="description"></p-column>
</p-dataTable>
```

How do I apply excel like filter on this?

Cheers
Sanket

**Comment by lilling** [comment]
numeric, textual, date, etc'
https://support.office.com/en-us/article/Filter-data-in-an-Excel-table-7d8e9739-2898-4bfe-9d0f-c6204e6e5c8a

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
