### ISSUE TITLE
Datatable Directives handle | pScrollbaleView

### ISSUE THREAD

**Issue by alokparikh16** [primefaces/primeng#4692]
We are using p-datatable with virtual scroll and load DOM data on demand. As per current behaviour, lazyLoadEvent will be executed when the last element in DOM is visible in viewport.

However, we want to call the lazyLoadEvent before the last record is visible in viewport and keep the DOM updated with latest data everytime a threshold limit is reached. This is to avoid showing the loading icon on UI.

I am trying to manually set the viewport and other scrollable variables which trigger the lazyloadevent but since p-datatable internally uses directive pScrollableView, I am not able to get the handle of these elements.

Is there any way I can get access to these variables inside directives or how can I call the lazyLoadEvent  on my custom conditions?

Angular version: 4.3.5
Angular CLI version: 1.0.6
PrimeNG version: 4.3.0

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
