### ISSUE TITLE
Focus method for all Input Components

### ISSUE THREAD

**Issue by MarkPerryBV** [primefaces/primeng#4694]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

We are making extensive use of all the input components from PrimeNG.

Our UX person has just asked that we "focus" the first form field in forms when they appear on screen.
Since the actual `input` element is hidden away within the PrimeNG component template we can't actually access it to fire the `.focus()` methods on the native DOM Element. Also the PrimeNG components don't offer an "export" that allows us access to the DOM element either.

I would like it if each input component exposed a "focus()" method so I can focus certain controls when I need to.

**Comment by veksen** [comment]
Pretty important for UX - is there any workaround?

**Comment by veksen** [comment]
Ended up rewriting our own Autocomplete component because the original does not properly autofocus nor doesn't support programmatically focus on the input.

**Comment by cetincakiroglu** [comment]
Hi,

Since this problem occurs across many components, I'm closing this issue and merging them into one https://github.com/primefaces/primeng/issues/11807. We'll fix them altogether.

Thanks for your support and report!
