### ISSUE TITLE
Calendar - Keyboard Navigation Support

### ISSUE THREAD

**Issue by MarkPerryBV** [primefaces/primeng#4695]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Our UX person has asked that when the calendar pop-over appears that we are able to select dates using the arrow keys on the keyboard to move the currently highlighted date. The "enter" key would then be used to select the date currently highlighted.

**Comment by chavalipraveen** [comment]
We have the exact same requirement. Is this something that's on the near term roadmap?

**Comment by Pikadili83** [comment]
Any progress with this issue? It should also support range selection using a keyboard and accessibility improvements...

**Comment by brian428** [comment]
+1. Keyboard navigation would be great, but please at least make the enter key work. Having to hit tab or use the mouse after typing in a date is very unintuitive.
