### ISSUE TITLE
Programatically unselect the checkbox in the Datatable

### ISSUE THREAD

**Issue by Mounika30** [primefaces/primeng#4696]
I want to programatically unselect the rows in the datatable using a cancel button . when i click the cancel button the selected rows should be unselected.
I went through the documentation but couldnt find any clue.

Here is the plunker:
http://plnkr.co/edit/wltvkC7pPQHRaMF8ChQR?p=preview

**Comment by nareshurs** [comment]
Hi Mounika30,

It will work if you update model to empty array. Below is plunker

http://plnkr.co/edit/yRnfwl0FQ6OvRP0v9JhL?p=preview

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
