### ISSUE TITLE
[Request] Dropdown w/ Filter should focus on the filter element

### ISSUE THREAD

**Issue by gatapia** [primefaces/primeng#470]
When a dropdown's menu is displayed the filter element should automatically request cursor focus.  Just seems like a more natural UX workflow.

**Comment by izll** [comment]
+1

**Comment by blinkxzero** [comment]
Is this possible to do with any of the latest updates?

**Comment by Scobee** [comment]
@gatapia  did you manage to solve this ?

**Comment by blinkxzero** [comment]
I haven't been able to solve this issue yet either, and it's a high demand item from my clients. Hopefully we'll get an update soon.

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
