### ISSUE TITLE
Not able to define different columns names for child rows in Expandable and Tree datatable

### ISSUE THREAD

**Issue by nsksaisaravana** [primefaces/primeng#4701]
Currently, columns are common for Parent and child rows, we should able to define different columns for child rows. Please add this feature.

**Comment by WhistlerHusky** [comment]
I was about to request this feature too, I want the table to be able to expand for column 'A', and 'B' like this [jtable](http://jtable.org/).

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
