### ISSUE TITLE
Add onClick event to Dropdown

### ISSUE THREAD

**Issue by phanibits** [primefaces/primeng#4702]
I would like to compute dropdown options dynamically when the user clicks on it. Currently it supports only the following events.
- onFocus
- onBlur
- onChange

Please add support for onDropdownClick and onClick. SplitButton already has these.

Thanks

**Comment by cagataycivici** [comment]
Added onClick, we'll reconsider onDropDownClick when more users demand it.

**Comment by niran-manandhar** [comment]
onDropdownClick  fires click event

**Comment by frnkgns** [comment]
its 2026 and we need it
