### ISSUE TITLE
DataTable:selectionMode and editable property can't working together

### ISSUE THREAD

**Issue by ranxiangfu** [primefaces/primeng#4704]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/6q5v84DWolH6DeAdi70w?p=preview

**Current behavior**
plug-in : DataTable
problem : When i set 
```html
    ...
    <p-dataTable [value]="dataList" editable="true" selectionMode="'single'">
        <p-column field="threshold" header="Threshold" editable="true" >
    ...
```
but the **editable="true"** is not working.Incell editing is unabled. 

**Expected behavior**
When i set  **editable="true" selectionMode="'single'"**,they shold working together. 

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:**
angular 5.0

* **PrimeNG version:** 
primeng 5.0.0-rc.0

* **Browser:**
Google Chrome 62.0.3202.94
 
* **Language:** 
typescript:2.4.2; ES6
* **Node (for AoT issues):** `node --version` =   v6.11.2

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
