### ISSUE TITLE
Calendar time picking doesn't work with range or multiple selection

### ISSUE THREAD

**Issue by akorchev** [primefaces/primeng#4705]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/IPO9mNnEnWcXGYusgBtG?p=preview

**Current behavior**

The calendar component doesn't support multiple or range selection and showTime=true. When the user tries to select the time there is a JS error because the time handling code can't handle the case when `this.value` is array. 
**Expected behavior**

The calendar should support time picking in multiple and range selection.
**Minimal reproduction of the problem with instructions**

```
<p-calendar selectionMode="range" [showTime]="true"></p-calendar>
<p-calendar selectionMode="multiple" [showTime]="true"></p-calendar>
```
**Steps to reproduce**
1. Make sure `selectionMode` is set to either `range` or `multiple`. Set `showTime` to `true`.
2. Open the calendar and click on a day of the month.
3. Try to change the time.
4. The browser will reload the current page and a JS error will be logged in the developer tools.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
As documented, this is not supported at the moment.

**Comment by akorchev** [comment]
Sorry, didn't find it in the docs. How about https://github.com/primefaces/primeng/pull/4706? It kind of works and at least there is no runtime exception.

**Comment by cagataycivici** [comment]
PR merged, thank you.
