### ISSUE TITLE
Tooltip stick on screen under Safari Mac Os

### ISSUE THREAD

**Issue by tleveque23** [primefaces/primeng#4707]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/DalIlkPsAa6Sp1hmcgeb?p=preview

**Current behavior**
If there is a tooltip on a element like a button, it will never disappear from the page

**Expected behavior**
Should disappear when user blur from element

**Minimal reproduction of the problem with instructions**
Check the plunker.
Just create a button and add a tooltip on it. Test on Safari Mac

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X
5.1.x

* **PrimeNG version:** 2.0.X
5.0.x

* **Browser:** 
MacOs Safari
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 5.2.3, please try with a newer version.

**Comment by tleveque23** [comment]
I confirm that it is fixed on PrimeNg 5.2.3. Thanks

**Comment by tleveque23** [comment]
Sorry bu it is not fixed completely.
If there is a show delay set, the bug is still present.
You can try it here:
http://embed.plnkr.co/fFqL2L2Ui4BtCwq0Zj6b/

**Comment by tleveque23** [comment]
Why is that still closed? Do I need to create a new one?
