### ISSUE TITLE
Hide checkboxes and selections on Tree Component for child nodes

### ISSUE THREAD

**Issue by westerncj** [primefaces/primeng#4709]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
Is there any way we can add a feature to hide the checkbox on some of the nodes for the **tree** component? For example, I may want to see a checkbox on the parent node that will propagate down to its child nodes so that they are selected, but not show the checkbox or highlighting on the children.

**Comment by cagataycivici** [comment]
There is selectable property on TreeNode node api.
