### ISSUE TITLE
reorderableColumns does not work correctly in a scrollable table with frozen/unfrozen columns

### ISSUE THREAD

**Issue by 007304wz** [primefaces/primeng#4711]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/keRJPMHKyzKzV4qa2OxB?p=preview

**Current behavior**
When you try to reorder the columns in unfrozen view area, it can not work correctly. For example, when you try to switch the columns 3 and 4, columns 1 and 2 will exchange the position; when you try to switch columns 5 and 6, columns 3 and 4 will exchange

**Expected behavior**
The columns' position can be changed correctly, and the column in unfrozen view cannot change position with the column sitting in frozen view.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
Sometimes the users need to check different fields that are in unfrozen area, so they are more like to move these columns to easy-to-get position.

**Please tell us about your environment:**
Windows 10

* **Angular version:** 2.1.0

* **PrimeNG version:** 4.3.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
DataTable is deprecated in favor of new p-table and not maintained anymore.
