### ISSUE TITLE
editing grid inline 

### ISSUE THREAD

**Issue by oixan** [primefaces/primeng#4713]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Expected behavior**
Example https://imgur.com/a/keGM7

Is there some plane to add a inline edit mode for grid component?

Inline Editing mean that every row have 2 buttons. edit - delete. 
When i click the edit button only the row selected must change to edit mode. 
The button in the row now should be - save - cancel.

**What is the motivation / use case for changing the behavior?**
Boss ask for  this. :D

**Comment by sudheerj** [comment]
The row editing is available in PrimeFaces datatable component. There is already feature request on this. https://github.com/primefaces/primeng/issues/2048
