### ISSUE TITLE
Integrate pTooltip with pMenu* via MenuModel API extension

### ISSUE THREAD

**Issue by KeithGillette** [primefaces/primeng#4714]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Currently the `MenuModel` includes a `title` property which sets the `title` element attribute on the various `pMenu*` templates, providing basic tooltip functionality via the browser's native support for displaying the `title` attribute of an HTML element.

**Desired behavior**
Display the `pTooltip` component on hover of a `pMenu*` menu item, via properties passed from a new `tooltip` property on the `MenuItem` API with properties corresponding to the `pToolTip` API:
 * pTooltip
 * tooltipPosition	
 * tooltipEvent	
 * positionStyle	
 * tooltipDisabled	
 * appendTo	
 * hideDelay	
 * showDelay	
 * tooltipStyleClass
 * escape
 * tooltipZIndex	

**What is the motivation / use case for changing the behavior?**
Consistent user (and developer) experience in displaying tooltips, regardless of the component in which the tooltip is embedded.

**Comment by tiger5226** [comment]
I agree with this. Sort of weird that by default the tooltip of the menus for example in the p-menubar do not have the same tooltip label as when p-tooltip is used.

**Comment by sourabh8003** [comment]
Implemented a fix in PR #5422

**Comment by flkeller** [comment]
any intention to implement this feature in the near future?

**Comment by KeithGillette** [comment]
Tooltip added to MenuModel in [release 12.1](https://github.com/primefaces/primeng/blob/master/CHANGELOG.md#1210-rc1-2021-08-11).
