### ISSUE TITLE
Id of p-calandar input [Angular]

### ISSUE THREAD

**Issue by mza97** [primefaces/primeng#4715]
I'm submitting a bug when using the p-calandar with angular 5.

I'm adding the method: (keydown)="onKey($event)", where in $event i'm looking for the input's id (set whith [id]="blabla").

But when I check the id (myDatePicker.inputfieldViewChild.nativeElement.id), there is only a string "[object Object]".

http://plnkr.co/edit/YuOv0F8yl2PnZj9deS27?p=preview

**Comment by cagataycivici** [comment]
[inputId]="'datePicker'"

or

inputId="datePicker"
