### ISSUE TITLE
Row not unselecting on click - PrimeNg Docs

### ISSUE THREAD

**Issue by johnhwright** [primefaces/primeng#4716]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
> In single mode, a row is selected on click event of a row. If the row is already selected then the row gets unselected.

Try it on your own docs here:
https://www.primefaces.org/primeng/#/datatable/selection

Doesn't seem to work on any of the tables. The same is also true locally as well.

**Expected behavior**
Clicking the selected row would unselect it.

* **Browser:** all

**Comment by sudheerj** [comment]
By default metaKeySelection is true. That is we should use metaKey(ctrl or command) for selecton and unselection.

https://www.primefaces.org/primeng/#/datatable
