### ISSUE TITLE
Support composite icon inside a button with no label

### ISSUE THREAD

**Issue by TMaster** [primefaces/primeng#4719]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[X] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/U77VFR9CCXidjUwJLyxa?p=preview

(Notice that although the `label` property is not set, there is a label in the button named **ui-btn**

**Current behavior**
When adding an icon button (button that contains only icon and no text) everything works fine.
**However** if I want a composite icon (I'm using [font-awesome SVG framework](https://fontawesome.com/how-to-use/svg-with-js#power-transforms)) I can not use the  `icon` property so I add the composite icon inside the button. when I do that, the span for the label is rendered although the `label` property is null.

**Expected behavior**
I wish to use the font-awesome's svg framework with (the ability to scale and transform icons) in the primeng's button component.
I want to use the button component providing a complex icon with no text.

**Minimal reproduction of the problem with instructions**
 - Make sure you have [font-awesome 5 installed with the application ](https://fontawesome.com/get-started/svg-with-js)(with the js files).
- copy the following code to the x.component.html:
```html
<button pButton label="123">
<div class="fa-2x">
<span class="fa-layers fa-fw">
    <i class="fas fa-server"  ></i>
    <i class="fa-inverse fas fa-plus" style="color:rgba(70,70,70,0.95)" data-fa-transform="shrink-5 down-5 left-5"></i>
  </span>
</div>
</button>
```

**What is the motivation / use case for changing the behavior?**
I want to use the font-awesome abilities as well as prime ng fantastic components.

**Please tell us about your environment:**

Web Storm
* **Angular version:** 2.0.X
5.1.0

* **PrimeNG version:** 2.0.X
5.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 62
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS 2.6

* **Node (for AoT issues):** `node --version` =   9

**Comment by cagataycivici** [comment]
It seems a bit complex to support, maybe you can do it easier with "ui-button" and some padding.

```xml
<button class="ui-button" style="padding:.25em .5em">
 <div class="fa-2x">
   <span class="fa-layers fa-fw">
      <i class="fas fa-server"  ></i>
       <i class="fa-inverse fas fa-plus" style="color:rgba(70,70,70,0.95)" data-fa-transform="shrink-5 down-5 left-5"></i>
      </span>
      </div>
</button>
```
