### ISSUE TITLE
GMap Reset after changing parent from display: none to display: block

### ISSUE THREAD

**Issue by abdullahcolt** [primefaces/primeng#472]
I have a map hidden in an accordion. So the container's display property is originally 'none'. When I set its property to display: block; I need to be able to run something of the sort:

google.maps.event.trigger(map, 'resize');
as seen here:

http://stackoverflow.com/questions/3360494/keep-a-google-maps-v3-map-hidden-show-when-needed

I can't get the map object inside of my component. Is there way to do so?

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
