### ISSUE TITLE
p-autoComplete: wrong position of the list of suggestions (case: append to element which has position:relative;)

### ISSUE THREAD

**Issue by donriver** [primefaces/primeng#4721]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/wRK0Sfv9ABO1VXjDnyaj?p=preview

**Current behavior**
Incorrect position of the list.

**Expected behavior**
The list should appear under input element. 

**Minimal reproduction of the problem with instructions**
Type 'a' in the input field for autocomplete in the example. 
That error can be reproduced if autocomplete is appended to  DIV element which has the relative position.  

**Please tell us about your environment:**

* **Angular version:** 5.1.0

* **PrimeNG version:** 5.0.2

* **Browser:** [ Chrome 63.0.3239.84 | Firefox 57.0.2 | IE 11 ]

 
* **Language:** [TypeScript 2.5.3 ]

**Comment by cagataycivici** [comment]
This is expected and outside of the scope of PrimeNG. Better to handle it on your side, we have no control outside of the component. When appendTo is used, absolute positioning is used so you should not append it to a component that is inside relative.
