### ISSUE TITLE
Lifetime per Growl message enhancement

### ISSUE THREAD

**Issue by woteska** [primefaces/primeng#4732]
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**What is the motivation / use case for changing the behavior?**

Creating a notification service, where it can handle more than one notification at the same time, with different severity, lifetime, id, and so on... I have wrote a Stackoverflow question, attached image:
https://stackoverflow.com/questions/47985377/how-can-i-create-multiple-primeng-p-growl-instances-with-different-lifecycles-us

**Please tell us about your environment:**

Win10, IntelliJ Idea Ultimate the latest, Latest LTS Node.js (v8.9.1) with 5.5.1 npm, localhost...

* **Angular version:** The latest Angular, Angular CLI: 1.6.2, Angular ^5.1.2

* **PrimeNG version:** "primeng": "^5.0.2",

* **Browser:**  Chrome 63.0.3239.84 (x64)

* **Language:** "typescript": "~2.6.2"

* **Node (for AoT issues):**  v8.9.1

**Comment by cagataycivici** [comment]
Growl is removed in favor of Toast.
