### ISSUE TITLE
[hidden] ui-message shows

### ISSUE THREAD

**Issue by daleclements** [primefaces/primeng#4739]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When a div has both a [hidden] property and a .ui-message class, the [hidden] property is not respected

**Expected behavior**
[hidden] should be respected, or at least [hidden] used to be respected not long ago

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/9uKIEUSIvayOnfVXxj4t?p=preview

**What is the motivation / use case for changing the behavior?**
It didn't used to do this. I haven't updated my primeng or angular versions, or changed the load order of the css, but it used to work fine and now it doesn't. If it's an issue with .ui-message, it may be an issue with other classes as well. It seems like the .ui-message class having a "display" property causes it to be overridden.

**Comment by cagataycivici** [comment]
This seems to be expected, from the mozilla docs;

>  Changing the value of the CSS display property on an element with the hidden attribute overrides the behavior.

Message has display inline-block so this is expected.
