### ISSUE TITLE
PrimeNG.css => primeng.scss?

### ISSUE THREAD

**Issue by dharapvj** [primefaces/primeng#4740]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Currently, the npm package build contains single css for primeng. It contains CSS for all 70 components of primeng. Only themes are provided in SCSS format.

**Expected behavior**
Even the main compoent style should be available as SCSS so that end users can pick and choose only what we need and reduce amount CSS getting bundled and parsed in the application.

**What is the motivation / use case for changing the behavior?**
Smaller bundles size for application. Faster to download and faster to parse.

**Please tell us about your environment:**
Angular CLI 1,6,1

* **Angular version:** 2.0.X
Angular 5.1

* **PrimeNG version:** 2.0.X
PrimeNG latest

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by cagataycivici** [comment]
#4623

**Comment by liliom55** [comment]
Hi @cagataycivici 
Is there any way to have primeng.scss instead of primeng.css? Thank you.
