### ISSUE TITLE
New Table Component aka TurboTable

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#4743]
Create a template driven new table component to succeed p-dataTable. New p-table is designed to be lightning fast compared to p-dataTable and much more flexible.

**Comment by jisqaqov** [comment]
I think a very good feature should also be rowspan and colspan for rows. Currently available only for headers. Is it in a plan?

**Comment by cagataycivici** [comment]
@jisqaqov p-table has a template driven approach so it is easy to implement this on your side since you have full control over markup, we'll add a demo as well as a sample.

**Comment by jisqaqov** [comment]
It should be considered that rows can have columns with multiple number of rowspan and cospan attributes.

**Comment by jisqaqov** [comment]
I guess currently you support rowgouping by only one column, but it is not enough. It should support any number of rowspan and colspan

**Comment by cagataycivici** [comment]
We've added a demo, it is up to you how you implement it, new TurboTable does not limit this like the old one.

**Comment by pantonis** [comment]
@cagataycivici In order to use this table do we need to migrate from the old datatable?

**Comment by pantonis** [comment]
Downloaded latest code from master and while clicking in table I get

```
ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'table'
Error: Cannot match any routes. URL Segment: 'table'
```

**Comment by cagataycivici** [comment]
No you don't, old one is p-dataTable, new one is p-table. It is being documented now to be released next week. The route seems to be missing yes, we'll add it.

**Comment by nsksaisaravana** [comment]
Awesome guys, please add features like ag-grid.

**Comment by Ketec** [comment]
How much backwards compatibility will it have  with old table? Since we use it around 9 different places, would they all have to be fully redesigned, different properties and setup logic or can old tables be migrated with some adjustments (keeping col definitions, templates, event handlers etc)?  
  
Also will it have a kind of click event prevention option (based of some condition, cancel selection/selection events - like onBeforeSelect or something)?

**Comment by cagataycivici** [comment]
There is no backwards compatibility because it is a brand new component. Old one still works but will be phased out in a future release. There are similarities but also significant differences. You should be able to migrate slowly as old one still be there and looks the same as the new one.

**Comment by maxkorz** [comment]
@cagataycivici Hi. Does the new component support all the features that DataTable has? Filtering, Sorting, Pagination, Lazy Loading?

**Comment by bbuehrer** [comment]
The theme doesn't work for header and body.
How can i use custom-sort? i only find pSortableColumn.

**Comment by Levent0z** [comment]
Please do not phase out the old one. We've built our own functionality on it, and it would be a shame to not be able to upgrade in order not to lose dataTable.

**Comment by SteamWind** [comment]
Sad that the bootstrap theme doesn't work on this new table. It is planed to be supported?

**Comment by tavaneftekhar** [comment]
Is there any hope for a step-by-step guide to converting an old datatable to work as a new table? I have to migrate a lot of tables and want to make sure I'm not missing anything important.

**Comment by PabMendez** [comment]
the documentation is vague, I'm trying to dynamically set the colspan and rowspan and I can not find any meaningful information in the demo
