### ISSUE TITLE
column resizer needs to have a higher z-index than the column header span

### ISSUE THREAD

**Issue by tiger5226** [primefaces/primeng#4744]
I will be brief here. 

1 - Column Resizer

The [column resizer](https://github.com/primefaces/primeng/blob/master/src/app/components/datatable/datatable.ts#L87) that is added to allow a user to drag left/right to resize the column needs to have a higher `z-index` than the header label. Otherwise when the user drags too far left, the column resizer is no longer clickable. The fix for this is simple and should be included. 

```
.ui-datatable .ui-column-resizer{
    z-index: 1;
}
```

2 - The column header should show ellipses if the user drags to far left hiding part of the header. 

```
//Show column text with ellipsis if text overflows.
.ui-datatable thead th, .ui-datatable tfoot td {
    text-overflow: ellipsis;
}

```
3 - If the table data is hidden by being the column width being too little, ellipses should be shown as well. 

```
//Show table data with elippsis if text over flows
.ui-datatable-data>tr>td{
    text-overflow: ellipsis;
}

```

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
