### ISSUE TITLE
 ConfirmDialog blocked by child component`s confirmDialog.

### ISSUE THREAD

**Issue by cumtfc** [primefaces/primeng#4745]
### ConfirmDialog blocked by child component`s confirmDialog.

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**

I used comfirmDialog in two components, and component A is a child of component B.
when I called `this.confirmationService.confirm()` in component B. The confirmDialog was blocked.
When I remove component A from B, everything is normal.

**Please tell us about your environment:**

Windows 10 
WebStrom 
npm
* **Angular version:** 4.4.X

* **PrimeNG version:** 4.3.0.X

* **Browser:** 
Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.2

* **Node (for AoT issues):** `node --version` =   
6.3

**Comment by cagataycivici** [comment]
This is not a valid issue ticket, it misses a plunkr to demonstrate the issue. Please follow the issue guideline before creating new issues.
