### ISSUE TITLE
Accordion RTL icon is wrong

### ISSUE THREAD

**Issue by jonyadamit** [primefaces/primeng#4749]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

See accordion section in the [example page for RTL](https://www.primefaces.org/primeng/#/rtl).

**Current behavior**
An arrow points in the opposite direction of the content.

**Expected behavior**
An arrow points in the direction of the content.

**Minimal reproduction of the problem with instructions**
As above, see examples page.

Problem relates to the [Accordion](https://github.com/primefaces/primeng/blob/a3a13698627c63c7005a8402d92b0c878de12168/src/app/components/accordion/accordion.ts#L16) component, but applies to any component that supports (or would eventually support) RTL, such as all the menu components, or the treetable component.

**What is the motivation / use case for changing the behavior?**
To better support RTL.  I consider this a bug and not a feature request since RTL is supposedly supported by this component.

**Comment by mrmashal** [comment]
Could you please provide some description on the current state of this issue?
