### ISSUE TITLE
New Component: Loading Bar

### ISSUE THREAD

**Issue by ghost** [primefaces/primeng#4750]
hello :)

First of all, thank you for this awesome set of UIs for Angular.

Please is there any chance to include such component (Loading Bar) in the next version
http://akserg.github.io/ng2-webpack-demo/#/slim

src in MIT license : https://github.com/akserg/ng2-slim-loading-bar
Happy Coding!

**Comment by cagataycivici** [comment]
Set to 6.0, thanks for the feedback.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
