### ISSUE TITLE
Add focus() method to Dropdown

### ISSUE THREAD

**Issue by PetzeltA** [primefaces/primeng#4752]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

http://plnkr.co/edit/BuWcV0?p=preview

**Current behavior**
The dropdown disappears

**Expected behavior**
The dropdown ist shown focused

**Minimal reproduction of the problem with instructions**
See Plunker

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.0.3

* **PrimeNG version:** 5.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by eduardowickertg** [comment]
Seems like a issue with Renderer2 selectRootElement destroying elements child, take a look here: https://github.com/angular/angular/issues/19554

**Comment by PetzeltA** [comment]
OK - there should be a better way to set the focus on a dropdown.
I now user applyFocus but this leads to a new Problem. I now get an ExpressionChangedAfterItHasBeenCheckedError!
See this Punker: http://plnkr.co/edit/sT45o9?p=preview

**Comment by cagataycivici** [comment]
Added focus() method.

```xml
<p-dropdown #dd
```

You can get the instance with @ViewChild and call .focus()
