### ISSUE TITLE
[minDate-maxDate] may not update in Calendar

### ISSUE THREAD

**Issue by lucifer-AM** [primefaces/primeng#4755]
PrimeNG@v[4.3.0].

Hi,
I am facing an issue in p-calendar tag as I am not able to update the [minDate] of the p-calendar component.

The scenario is as follows:-

I have two p-calendar tags in my DOM.

First one is used to set the [minDate] of the second p-calendar tag.

The [minDate] only reflects after I try to write something on the second p-calendar input tag.

I think the second p-calendar component does not update the [minDate] after the [minDate] model changes. It is taking the previously set [minDate] until the component is updated from the DOM.

Awaiting reply.

Thank you @cagataycivici

**Comment by connectingbussiness** [comment]
I had got the same issue the p-calender validations is not updating until i change the month.

**Comment by skormel** [comment]
I have the same issue validations are not updated until I change the month.

**Comment by yanjunze** [comment]
I found in the source code there is some follow judge code:
`if(this.currentMonth && this.currentYear) {
            // refresh the minDate or maxDate UI.
}`
But in January `this.currentMonth===0` so it can't refresh the UI immediately.
Forgive my poor English.

**Comment by devoutsoft** [comment]
How i can this fix?)

**Comment by juanmag4** [comment]
You can change the source code for a temporary fix until someone in primeng fix it. Something like this:
`if ((this.currentMonth != undefined || this.currentMonth != null) && this.currentYear) { }`
Nice catch @yanjunze .
Also, sorry for my bad English.

**Comment by rishuvaid** [comment]
Encountered the same issue. Following..

**Comment by JPecko** [comment]
Works after changing and choose other month.
+1 same use case, same problem.

**Comment by cagataycivici** [comment]
I can't replicate, here is my case;

http://plnkr.co/edit/SCe6pwFbTayipI2EU1g9?p=preview

Please replicate using the plunkr above

**Comment by connectingbussiness** [comment]
This issue arises when the current month must be january. In all other cases it works.
I mean when u make change in the month of January it doesn't work.

**Comment by cagataycivici** [comment]
PR merged

**Comment by shinde-prasad** [comment]
![image](https://user-images.githubusercontent.com/28087544/62546542-4afe9100-b881-11e9-8c6b-3d80f394fe07.png)

PLease see the above image, I am using primeng p-calendar and adding minDate, maxDate,showOtherMonths,selectOtherMonths,monthNavigator,yearNavigator,yearRange
as TRUE. But I am getting those year offset selected in year range but month selections are shown as disabled.

Now if I click no next arrow button and go till december then it comes directly to year 2020.

I am confused about this weird behaviour.
