### ISSUE TITLE
Datatable selection causing duplicates when mixing ctrl-click and shift-click selection

### ISSUE THREAD

**Issue by Hauwk** [primefaces/primeng#4756]
Duplicate items are added when mixing ctrl-click and shift-click selections.

After shift-selecting a range of data, ctrl-clicking on an unselected row resets the _anchorRowIndex_, which causes a shift-click to an already selected row to add the range between _anchorRowIndex_ and clicked row index without checking if items are already selected.

Reproducible on primefaces.org demo site.

**Steps**
- Navigate to https://www.primefaces.org/primeng/#/datatable/selection
- In the table with "Multiple Selection" header...
- Single-click first row
- Shift-click third row
- Ctrl-click fourth row
- Shift-click first row

**Expected**
List of selected items below table to show only the 4 selected items

**Actual**
List of selected items below table shows 7 items even though only 4 are selected. 3 are duplicates.

I believe that datatable.ts#L1422, inside _selectRange_, it should check if the row is already selected (with _this.isSelected(rangeRowData)_) before continuing to select the row.

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
