### ISSUE TITLE
File-upload control Choose button support drag and drop in IE and Edge.

### ISSUE THREAD

**Issue by asanka-indrajith** [primefaces/primeng#4757]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[x] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When dragging files over Choose button in advanced mode and basic mode, it shows error icon and doesn't support dropping files. It's also there in the PrimeNG [demo ](https://www.primefaces.org/primeng/#/fileupload) as well

**Expected behavior**
User should be able to drag and drop files to choose button in basic and advanced mode.

* **Angular version:** 4.4.6

* **PrimeNG version:** 4.3.0

* **Browser:** IE & Edge

**Comment by npoirey** [comment]
Drag and drop on basic mode works as expected on chrome and firefox but should indeed work also for IE11 & Edge. Right now I had to do a workaround using 2 p-fileupload imbricated. This is far from perfect and doesn't work completely because of #4733.

**Comment by JACrazy** [comment]
Drag and drop is currently working for me on 5.2.0, but I tested also on 4.3.0 and had no issue. 
Check that your IE session is not elevated. For example, if your Visual Studio is running as administrator and you use IE as the default debugging browser, it will not work with drag and drop. This was the problem I originally had that brought me to this thread.

**Comment by asanka-indrajith** [comment]
@JACrazy : We are talking about upload control in basic mode not the advanced mode. Basic mode doesn't work. see [demo](https://www.primefaces.org/primeng/#/fileupload)

**Comment by JACrazy** [comment]
@asanka-indrajith Never mind, I missed the part where you specified dragging onto the choose button. Even in advanced mode it doesn't work, like you originally said.

**Comment by cagataycivici** [comment]
This is by design, content section is droppable, not the button bar.
