### ISSUE TITLE
How to add custom styling to existing component without using !important ? 

### ISSUE THREAD

**Issue by PardeepJain** [primefaces/primeng#476]
Working on project using Primeng, but got confused why my custom css classes always append at the start instead of at the end ? i can do anything styling using `!important` but this is not correct approach always.

suppose i am using like this :- 

<button pButton type="text" (click)="count()" label="Click" class="red"></button>

but after checking console found classes append to pButon are like this - 

class="red ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only"

why class `red` is not at the end ?

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
