### ISSUE TITLE
Calendar: click on month to select whole month as a range

### ISSUE THREAD

**Issue by lebnic** [primefaces/primeng#4760]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
Would be useful to be able to *click on current month* to select all days of this month, when calendar selectionMode is Range
![image](https://user-images.githubusercontent.com/6682795/34574696-30524508-f146-11e7-9fa7-9c210e67926c.png)

**Comment by cagataycivici** [comment]
If more users demand it, we'll reconsider, thank you.
