### ISSUE TITLE
Ultima Theme showing issues when using resizableColumns with filters in DataTable component

### ISSUE THREAD

**Issue by sTheCoder** [primefaces/primeng#4761]
When using Ultima Theme, combining filters with resizableColumns on DataTable component, there was a visual bug as shown in plunker. The filter gets inline with the header's title. When using dropdowns, things got more ugly. (Maybe this is not necessarily connected with ultima theme. The plunker included shows this behavior even thou minimal styles were included, I noticed however that when using the free Omega theme this issue was absent)

I would like to see a similar behavior of filters, just like when used without resizable columns feature.

Plunker here: https://plnkr.co/edit/eWOuD2CqUoSM2JoOlCDf?p=preview

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
