### ISSUE TITLE
DataTable: Sorting not possible because template header content is not clickable since PrimeNG v5.x

### ISSUE THREAD

**Issue by jgsbb** [primefaces/primeng#4762]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/JeSK88Bgq0cRdsNggDRx?p=preview

**Current behavior**
If there is an html element inside the ng-template header the content is not clickable. So the column is not sortable by clicking o the table template header content such as `<span/>` or `<i/>.`

It works with PrimeNG v4.x but not anymore with PrimeNG v5.x.

**Expected behavior**
Behavior like with PrimeNG v4.x. Table template header content is clickable and it triggers the sorting.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/JeSK88Bgq0cRdsNggDRx?p=preview

**What is the motivation / use case for changing the behavior?**
Usability.

* **Angular version:** 5.0.1

* **PrimeNG version:** 5.0.2

* **Browser:** all

 
* **Language:** TypeScript 2.6

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
