### ISSUE TITLE
Can't bind to 'model' since it isn't a known property of 'p-splitButton'

### ISSUE THREAD

**Issue by mmlitvin** [primefaces/primeng#4763]
When trying to use p-splitButton component in primeNg 5.0.2 getting errors in Chrome Dev Tools Console
_Can't bind to 'model' since it isn't a known property of 'p-splitButton'.
1. If 'p-splitButton' is an Angular component and it has 'model' input, then verify that it is part of this module.
2. If 'p-splitButton' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("<p-splitButton label="Save" icon="fa-check" 
  (onClick)="onClick()" [ERROR ->][model]="items"></p-splitButton>"): ng:///app/app.template.html@1:24
'p-splitButton' is not a known element:_

Plunker
https://plnkr.co/edit/pDRDUbUKqhoF6qLYpTe8?p=preview

**Comment by authnettest622** [comment]
Hi,
We are also facing same issue when using component from shared module which has a input model .
Any Clues why you were receiving this error?

Your help will be appreciated.

**Comment by cagataycivici** [comment]
Not a PrimeNG issue, there seems to be a config problem on your side.

**Comment by jayyren** [comment]
Hi, guys! @authnettest622 @mmlitvin have you solved this issue? Came across with same error, can't understand why
