### ISSUE TITLE
feat: Table state saver

### ISSUE THREAD

**Issue by mouradghafiri** [primefaces/primeng#4764]
hello;

please, could we , on the dataTable or the next turboTable, save the state of columns change on refresh or navigation.

Scenario: populate the table with some date and hide some columns using ColToggler, refresh the page or go to another route and come back, everything goes to initial state of the table.

is it possible to add an input or a property to tell the the table to save the state to the local storage for example and load it automatically on navigation or refresh.

Thanks

**Comment by cagataycivici** [comment]
Duplicate
