### ISSUE TITLE
(onPageChange) not working in dataTable

### ISSUE THREAD

**Issue by agustinbreit** [primefaces/primeng#4765]
I'm working with the latest relase (5.0.2) and I can't access to the paginator onChangePage event via the DataTable.

 <p-dataTable #datatable [value]="supports"  [paginator]="true" paginatorPosition="both" (onPage)="changePage($event)" (onPageChange)="paginate($event)" [rows]="1" [responsive]="true">

then in my .ts I have: 

paginate(event){
        console.log(event);
       
    }
    changePage(event){
        console.log(event);
     
    }

the onPage function works but not the paginate function. 

am I doing something wrong? 

I need to implement a custom pagination...

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue.
