### ISSUE TITLE
datatable with rowexpansion inner table not showing fields data

### ISSUE THREAD

**Issue by jhonnathan78** [primefaces/primeng#4766]
I have a parent table with an ng-template with rowexpansion and then a child table. In the child table none of my data fields are showing the data. If I bind to the object properties with the data right after the ng-template with the rowexpansion then the data shows.

example:

```
<p-dataTable [value]="actions expandableRows="true" [expandedRows]="expandedRows">
  ...Primary table p-columns left out since they work and only the table below is causing issues....

  <ng-template let-action pTemplate="rowexpansion">
    <!--This works-->
    {{action.action_id}}

    <!--This does not work-->
    <p-dataTable [value]="action">
      <p-column field="action_id" header="ID"></p-column>
    </p-dataTable>
  </ng-template>
</p-dataTable>
```

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
