### ISSUE TITLE
Adding a TreeNode object to the [selection] input of a p-tree component using typescript doesn't set the partialSelected field of parent nodes

### ISSUE THREAD

**Issue by rolpereira** [primefaces/primeng#4767]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/y0iuBLtCnmzebxdzeJiv?p=preview

**Current behavior**
Assuming a `p-tree` component that is using the "checkbox" style of node selection and that has the following nodes:

```
  A
  +-> B
  +-> C
```

after clicking on the "C" node with the mouse, the "A" get partially selected as seen on this image:

![mouse_click](https://user-images.githubusercontent.com/45408/34632045-3b09e2b4-f26b-11e7-9a49-0f0348c50237.png)

However if the array used as the "selection" input of the `p-tree` get update via typescript code, for example as part of a `(click)` callback of a button then the "A" node doesn't get a `[-]` checkmark as seen on this image:

![button_callback](https://user-images.githubusercontent.com/45408/34632105-93375444-f26b-11e7-8c5b-320d4ad3dbe1.png)

It's possible that this is related to issue #3579 

**Expected behavior**
Updating the [selection] input array should trigger the same behaviour as when clicking on the node with the mouse.

**Minimal reproduction of the problem with instructions**
See Plnkr http://plnkr.co/edit/y0iuBLtCnmzebxdzeJiv?p=preview

Alternatively you can clone from this repo: https://github.com/rolpereira/primeng-treenode-parent-checkbox-issue
Just run the code using the angular-cli `ng serve` command, open the browser and click on the "Select C node" button.

**What is the motivation / use case for changing the behavior?**
Needed to implement a functionality where when the user clicks on a node of a `p-tree` component, other nodes of the same tree will also be automatically selected as if the user had already clicked on them.

(The demonstration repo above uses the `(click)` callback of a `<button>` element instead of the click on the `p-tree` nodes in order to simplify the code needed to show this issue.)

**Please tell us about your environment:**
Windows 10, latest version of Visual Studio Code

* **Angular version:** 5.1.2

* **PrimeNG version:** 5.0.2

* **Browser:** only tested on latest Firefox and Chrome, the issue occurs on both browsers
 
* **Language:** typescript 2.5.3 and ES5

**Comment by ofekdeitch** [comment]
+1

**Comment by yigitfindikli** [comment]
You can use TreeNode's partial selected property like this: https://stackblitz.com/edit/github-xszgdz .
