### ISSUE TITLE
empty footer is being displayed in panel if embedded datagrid has its own footer

### ISSUE THREAD

**Issue by godfryd** [primefaces/primeng#4768]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/3tdpLiEt2NI8LSJiECn3?p=preview

**Current behavior**
Empty footer in the panel is being displayed.

**Expected behavior**
If not footer is defined in panel then no footer is displayed

**Minimal reproduction of the problem with instructions**
Add datatable with footer to panel.

**What is the motivation / use case for changing the behavior?**
Empty footer cluters UI.

**Please tell us about your environment:**
* **Angular version:** 5.0.0
* **PrimeNG version:** 5.0.2
* **Browser:** only checked in Chromed
 
* **Language:** TypeScript 2.4.2

* **Node (for AoT issues):** `node --version` =   6.11.4

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
