### ISSUE TITLE
Steps menu + input file probelm

### ISSUE THREAD

**Issue by Iamguy84** [primefaces/primeng#4770]
Hi,
I have created sample Steps menu. Here is my code as below:
**In Html:**
```
<div [ngSwitch]="activeIndex">
  <p-steps [model]="stepsItems" [(activeIndex)]="activeIndex" [readonly]="false"></p-steps>
  <br>
  <div *ngSwitchCase="PageNames.page1">
    <div>
      <input type="text" pInputText [(ngModel)]="property"/>
      {{property}}
    </div>
    <br>
    <div>
      <input type="file" pInputText />
    </div>
  </div>

  <div *ngSwitchCase="PageNames.page2">
       This is page number 2.
  </div>
</div>
```
**In Typescript:**
```
  property:string;
  stepsItems: MenuItem[];  
  PageNames = PageNames;
  activeIndex = PageNames.page1; //Default page
    
  constructor() {
      this.stepsItems = [
            {
                label: 'Step 1 page'
            },
            {
                label: 'Step 2 Page'
            },
        ];
  }
```
I filled input text value and input file
![step 1](https://user-images.githubusercontent.com/13044221/34660761-b8b80540-f466-11e7-8646-6934bb1ec676.PNG)

Now i am going to click **step 2 page** then go back to **step 1 page**. 
![step 2](https://user-images.githubusercontent.com/13044221/34660990-4eb6816a-f468-11e7-86e6-3427b4644473.PNG)

The input text value is already previous data model but input file value is gone.
I think data binding does not support input file
Can you please tell me how to i fix it?
Any Idea?

Ref:
[https://plnkr.co/edit/dPB5DFzfmKwGlkmFjqrp?p=preview](url)

I am waiting for your response.
Thanks in Advance

**Comment by cagataycivici** [comment]
Please use forum for support requests.
