### ISSUE TITLE
DataTable with a lot of content and Responsive design

### ISSUE THREAD

**Issue by sebaiona** [primefaces/primeng#4773]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/3T1w7Q4finFe0J9Z5Azx?p=preview

**Current behavior**

When content is too big in a DataTable it's unreadable.
If I put a `"table-layout: auto"` on the `table` element, then it goes out of the page.

**Expected behavior**

It would be interesting that columns that doesn't fit goes in an expandable area.

Datatables.net does it and it's an amazing feature !
Columns widths adjust depending on the content and it shrinks until there is no place. Then column content is put in an expandable area.

For example if you follow this link and you reduce the width of the page you will see how it works: 
https://datatables.net/extensions/responsive/examples/initialisation/ajax.html

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
DataTable is deprecated and will be removed in favor of new p-table (aka TurboTable) of 5.1.0 so closing the issue.
