### ISSUE TITLE
Arrow icons and another icon just after [ in TreeTable ]

### ISSUE THREAD

**Issue by Abhinav3414** [primefaces/primeng#4774]
I'm submitting a ...

[x] feature request  => Please check if request is not on the roadmap already 

**Current behavior**
Currently we have one icon in TreeTable which expands and collapses the row item.
We want another icon which can be placed next to it and have expand and collapse behavior as well.

**Expected behavior**
We want same icon behavior in tree table as in tree right now.
Example: 
Collapsed state :  fa-caret-right [fa-folder] SomeFolderName
Expanded state : fa-caret-down [fa-folder-open] SomeFolderName

Environments:
Windows 10, Eclipse Oxygen.1a Release (4.7.1a)

latest 5 x of angular and prime

**Comment by djay1977** [comment]
use ng-template to do this. Example : 
      <p-column header="{{'index-type-elem' | translate}}" [style]="{'width':'60%'}">
        <ng-template let-col let-node="rowData" pTemplate="body">
          <i class="index-icon icon fa fa-{{getIndexIcon(node)}}"></i> {{node.data.LIB_TYPE_ELEM}}
        </ng-template>
      </p-column>

**Comment by djay1977** [comment]
Use ng-template to do this. Example: 
`      <p-column header="{{'index-type-elem' | translate}}" [style]="{'width':'60%'}">
        <ng-template let-col let-node="rowData" pTemplate="body">
          <i class="index-icon icon fa fa-{{getIndexIcon(node)}}"></i> {{node.data.LIB_TYPE_ELEM}}
        </ng-template>
      </p-column>`

**Comment by Abhinav3414** [comment]
@djay1977  it works, is there any handle to change icon when row is expanded and collapsed ?

**Comment by djay1977** [comment]
expandedIcon & collapsedIcon properties on p-treetable

**Comment by Abhinav3414** [comment]
@djay1977  expandedIcon & collapsedIcon properties on p-treetable works for toggle button given in pT-treetable.
I am looking for expand and collapsed icons inside the template you have suggested.
When we expand a row, toggle button should change and the folder icon next to it should also open.

**Comment by cagataycivici** [comment]
TreeTable will be reimplemented, please monitor;

#4813
