### ISSUE TITLE
Calendar UI does not update in some cases

### ISSUE THREAD

**Issue by designus** [primefaces/primeng#4775]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/okzYh53odGHzV5zOjWgf?p=preview

**Current behavior**
Calendar UI is not updated when disabledDays input property is changed. Calendar UI is only updated  when some event is triggered manually (e.g: click on next month)

**Expected behavior**
Calendar UI should update whenever input props are changed. 

**Minimal reproduction of the problem with instructions**
Toggle disabledDays on and off and check calendar UI. 

**Please tell us about your environment:**
* **Angular version:** 4.1.3
* **PrimeNG version:** 4.3.0
Same problem occurs  in the most recent versions as well. Check plunk link. 

**Other info**
It seems that the problem lies within this line: 
https://github.com/primefaces/primeng/blob/master/src/app/components/calendar/calendar.ts#L386
"this.currentMonth" is zero based. So if we are in January, "this.currentMonth" value is 0 which results in condition being false.

**Comment by ppsdang** [comment]
I am also getting this issue while setting minDate

**Comment by designus** [comment]
In my case, as a temporary solution until this is fixed I added ChangeDetectorRef class detectChanges() method after setting disabledDays property.

**Comment by jbreitenbach** [comment]
It seems like this dev fixed the issue (I managed to replicate the fix in my own project) but it doesn't appear to have been submitted for review?

https://github.com/Aask/primeng/commit/3ff34fc91243a0a08b8cf606b0bc9752be2b3eab

**Comment by jbreitenbach** [comment]
@designus I'm not seeing that adding ```js  .detectChanges(); ``` has any effect. 
However, changing the month seems to work.

**Comment by designus** [comment]
Yes you are right, it is only for the first month of the year.  Thanks for the fix.

**Comment by cagataycivici** [comment]
Cases are minDate, maxDate, disabledDays and disabledDates
