### ISSUE TITLE
DataTable does a lot of avoidable Layout Trashing

### ISSUE THREAD

**Issue by hasbel** [primefaces/primeng#4776]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When the datatable component is running the function fixColumnWidths(), it does a lot of layout trashing. This results in a noticeable drop in FPS and waistes CPU time.

**Expected behavior**
Layout trashing should be avoided whenever possible to help improve performance.

**Minimal reproduction of the problem with instructions**
Create an Angular App that includes a resizable / reponsive p-dataTable component. Fill it up with data. Check the performance profiler in your browser to see that a lot of time is spent re-doing the layout multiple times in a row due to layout trashing. This results in a noticeable FPS drop.

**What is the motivation / use case for changing the behavior?**
Avoid layout trashing to reduce browser freezes.

* **PrimeNG version:** 
5.0.0

* **Browser:** 
All
 
* **Language:**
All

**Comment by hasbel** [comment]
I identified the line responsible as line 2239 of datatable.ts:
```typescript
if(bodyCols) {
    for (let i = 0; i < bodyCols.length; i++) {
        bodyCols[i].style.width = columns[i].offsetWidth + 'px';
    }
}
```

**Comment by cagataycivici** [comment]
p-dataTable is deprecated in favour of 5.1.0's new p-table so we're not doing any development on it anymore.
