### ISSUE TITLE
 DataTable RowGroups expand a specific entry

### ISSUE THREAD

**Issue by CyleClone** [primefaces/primeng#4778]
**I'm submitting a ...** 

[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap

http://plnkr.co/edit/OqpT6ngT01gNh360xqmQ?p=preview

**Expected behavior**
What I need is to be able to expand a specific rowgroup. In my current project i would need to expand the last rowgroup. It's already possible to expand a specific row/multiple rows in a non-rowgroup datatable, but that does not quite work with a rowgroup-datatable.

**Comment by cagataycivici** [comment]
DataTable is deprecated and will be removed in favor of new p-table (aka TurboTable) of 5.1.0 so closing the issue.
