### ISSUE TITLE
<p-dropdown> delay 3-4s with big data

### ISSUE THREAD

**Issue by gieboyz** [primefaces/primeng#4781]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[X] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
Hi facing some problem with big data on <p-dropdown>. i was using "lazy" but still no effect.
the problem is, when i first time click the dropdown with big data, it will delay around 3-4s.

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/UCvq6F1RW4DwgIyqbuiz?p=preview

* **Angular version:** ^5.0.0

* **PrimeNG version:** ^5.0.0-rc.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome.
Mozilla
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
This is expected, dropdown is not suitable to display huge number of data, try an alternate ui instead like an AutoComplete.
