### ISSUE TITLE
PrimeNG 5.0.2 CSV export (csv Separator problem)

### ISSUE THREAD

**Issue by jaafriadnane** [primefaces/primeng#4783]
Hello, thank you @cagataycivici for your answer on the #4547,

I tried the new version, i'm now at the 5.0.2 and I have the same issue even though i use the [exportable]="false",

I always have a comma (csv Separator) at the end of every line.

I took a look at the code, for exemple the header :

`for (var i = 0; i < this.columns.length; i++){ 
var column = this.columns[i]; 
if (column.exportable && column.field) {
 csv += '"' + (column.header || column.field) + '"'; 
if (i < (this.columns.length - 1)) {
 csv += this.csvSeparator; 
} } }`

I think that it is better to verify that ( i < (nbrOfExportableColumns - 1) ) before adding the separator,

in my case i have 10 exportable columns and i have 14 columns in my table, 4 columns are not exportable so the condition if (i < (this.columns.length - 1)) passes on the last exportable column ...

thank you in advance

**Comment by cagataycivici** [comment]
DataTable is deprecated in favor new p-table and not maintained anymore.
