### ISSUE TITLE
Progress Bar with indeterminate mode not work correctly on Ultima template.

### ISSUE THREAD

**Issue by CarlinhosSousaJunior** [primefaces/primeng#4784]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
The p-progressBar with indeterminate mode not work as expected on ultima template, it doesn't has effects, staying only static.

![image](https://user-images.githubusercontent.com/17458197/34768509-249ec95c-f5e2-11e7-86f1-8be18d54e15f.png)

**Comment by SeanLeitzinger** [comment]
Is this going to get fixed?

**Comment by CarlinhosSousaJunior** [comment]
@SeanLeitzinger do you have the same problem ?

**Comment by SeanLeitzinger** [comment]
Yes. I ended up just using a solution I found some place else outside of primeNG. Also have issues with the spinner when using [loading]="loading" on p-table.

**Comment by CarlinhosSousaJunior** [comment]
@SeanLeitzinger So, i have the same problem with p-table too.

**Comment by CarlinhosSousaJunior** [comment]
@SeanLeitzinger  If you need a temporary solution, you can write this code that will override primeng css.

```
body .ui-progressbar .ui-progressbar-value {
    height: 0 !important;
}
```

**Comment by cagataycivici** [comment]
@Merve7 Please check this one.

**Comment by cagataycivici** [comment]
By the way, Ultima forum is better to get faster responses as this tracker is for PrimeNG.

**Comment by CarlinhosSousaJunior** [comment]
@cagataycivici Ok, thank you for your tip !

**Comment by Merve7** [comment]
We fixed for next Ultima release
