### ISSUE TITLE
Spinner buttons emit change event on mouse down causing problems when you long click buttons.

### ISSUE THREAD

**Issue by Zbulu** [primefaces/primeng#4786]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/IO2oR7tfyUPFIXeA5Hxk?p=preview
I've updated issue with plunker demo

**Current behavior**
When I add spinner with following settings: 
```html
<p-spinner [ngModel]="model | async" (ngModelChange)="onChange($event)"
[ngModelOptions]="{updateOn: 'blur'}"></p-spinner>
```
onChange($event) is called on mouseDown click which causes no problems when user wants to click only once or twice, however there is a problem when user decides to hold that mouse longer to actually spin the value by couple of steps, when the user finally release the mouse button there is no event fired with the final value

**Expected behavior**
ocChange($event) should be called on mouseUp passing the final value 

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.1.3

* **PrimeNG version:** 5.0.2

* **Browser:** [Chrome XX  ]

 
* **Language:** [ TypeScript ]

* **Node (for AoT issues):** `node --version` =   6.12.1

**Comment by cagataycivici** [comment]
Spinner does not support [ngModelOptions]="{updateOn: 'blur'}"
