### ISSUE TITLE
Lightbox: Custom Launch UI and Close Button

### ISSUE THREAD

**Issue by markleppke** [primefaces/primeng#4789]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Launch lightbox with text and an optional close icon.
WIth the two available modes, there is not a way to configure the lightbox to use an anchor tag and then have the image launched have a close icon. One can the content mode to use an anchor tag to launch it. However when doing so, the close icon is hidden (it assumes the content being launched is a video when using a custom ui for launching the lightbox)

Recommend that the light box be configurable to allow a user to provide a custom launch UI, that then opens up the image lightbox with close button.

**Comment by cagataycivici** [comment]
Lightbox will be deprecated in favor of the upcoming modern Galleria so closing.
