### ISSUE TITLE
How to attach ContextMenu to an specific element

### ISSUE THREAD

**Issue by jmfvarela** [primefaces/primeng#479]
Is it posible?
I can see in source code that ConextMenu is always in `body` and not for an specific element:
`this.documentRightClickListener = this.renderer.listenGlobal('body', 'contextmenu', (event) => {
`
Is it correct?

**Comment by marcinkaszuba** [comment]
I agree with @jmfvarela that it should not be solved like this. Imagine that you want to display multiple different context menus on a single page. All of them are being displayed at once, while each of them should be assigned to the specific element and fire according to the element which was clicked.

**Comment by ammar91** [comment]
Any updates on this?

**Comment by ammar91** [comment]
@cagataycivici Can you please look at this one as well and put a fix for this in RC1?

**Comment by kt215** [comment]
This is how I attach a context menu to a div:

```html
   <div (contextmenu)="cm.show($event)">
   </div>
   <p-contextMenu #cm [model]="contextMenu"></p-contextMenu>
```

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
