### ISSUE TITLE
OnSelect event does not fire on dates typed in calendar

### ISSUE THREAD

**Issue by Lolash** [primefaces/primeng#4791]
[x] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/AtoXDBndnMZaobUrbzFn?p=preview the counter increases every time onSelect event is fired

**Current behavior**
When I type in date (instead of selecting it) the OnSelect event is not fired. Moreover, when I delete the whole date it is also not fired.

**Expected behavior**
I'd like to have an event, which will be fired, when the value is set (does not matter if it's selected from date picker, typed in or deleted to null).

* **Angular version:** 5.1.X

* **PrimeNG version:** 5.0.X

* **Browser:** all
* **Language:** TypeScript 2.5.x

**Comment by jotapsl** [comment]
Does swapping (onChange) for (ngModelChange) works for your use case?

**Comment by cagataycivici** [comment]
That is expected, onSelect is for selecting with mouse. You can try ngModelChange for sure.
