### ISSUE TITLE
ContextMenu get element of right clicked cell in datatable

### ISSUE THREAD

**Issue by fplini** [primefaces/primeng#4792]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

I have a lot of datatable and I want to add a context menu on each datatable (this is very simple).
My context menu has only one item "Copy" that must copy the value of the clicked cell.
At present I didn't find a way to get the value of the clicked cell.

* **Angular version:** 5.0.3

* **PrimeNG version:** 5.0.2

* **Browser:** [all]
 
* **Language:** [TypeScript 2.4.2]

* **Node (for AoT issues):** `node --version` = v6.9.1

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
