### ISSUE TITLE
Allow keyboard input of time in calendar component

### ISSUE THREAD

**Issue by Deilan** [primefaces/primeng#4795]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**What is the motivation / use case for changing the behavior?**
Accessibility

**Comment by cagataycivici** [comment]
It is alredy possible.

**Comment by Deilan** [comment]
@cagataycivici Will the demo at https://www.primefaces.org/primeng/#/calendar be updated for this case?

**Comment by pshahidi** [comment]
I do not see the keyboard navigation work on p-calendar, @cagataycivici  could you elaborate on, what do you mean  by 'is already possible'

**Comment by h1ghland3r** [comment]
Hello, is there an update regarding this functionality?
