### ISSUE TITLE
ui-fluid breaks buttons with icon but without label

### ISSUE THREAD

**Issue by newq** [primefaces/primeng#4796]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
```
**Plunkr Case (Bug Reports)**
Variant of the problem can be observed on PrimeNG show-case: https://www.primefaces.org/primeng/#/inputgroup
"Button Addons". The third input element. The green / red, Check / Close buttons of the button group.
In Firefox you will see the width is broken.

or on theme examples: https://www.primefaces.org/verona-ng/#/forms
look for the "Icon Only" Button in the section "Buttons".
In Firefox you will see the width is broken

Chrome example follows below.

**Current behavior**
The width of a `button` with only an icon and no label is broken if it is inside an element with `ui-fluid` class. This can be also observed on `p-calendar` and in button groups (see example above or code below).
In Firefox the width is too small, in Chrome the width is too large (and alignment is incorrect).

**Minimal reproduction of the problem with instructions**

```
<div class="ui-g ui-fluid">
    <div class="ui-g-12">
        <button pButton type="button" label="Button1"></button>
    </div>
    <div class="ui-g-12">
        <button pButton type="button" icon="fa-check"></button>
    </div>
    <div class="ui-g-12">
        <button pButton type="button" icon="fa-check" label="Button2"></button>
    </div>
    <div class="ui-g-12">
        <p-calendar [showIcon]="true"></p-calendar>
    </div>
</div>
```

In Firefox you will see broken width (too small) and in Chrome you will see that the button for the calendar element is too large and alignment is wrong as a result.

* **Angular version:** 5.0.0

* **PrimeNG version:** 5.0.2

* **Browser:** Chrome, Firefox and maybe others

This bug is a result of the following css rule

`
body .ui-fluid .ui-button-icon-only {
    width: auto;
}
`

**Comment by cagataycivici** [comment]
It is by design, we keep icon only buttons as they are, not 100% as it looks out of the place. You can override this decision with your custom css though.

```css
body .ui-fluid .ui-button-icon-only { width: 100%; }
```

**Comment by newq** [comment]
I do understand that you don't want to make an icon only button autosize to the full width. (but one could argue that's what the user intended with ui-fluid). 
But please fully read what else is affected: your p-calendar component with "showIcon" attribute to true is displayed broken for example. That can not be by design - just display it's padding etc correctly and autosize the input (like you do). 

Please fix this at least in your paid Themes.

I attached a screenshot this time. Thanks!

![primeng_bugs](https://user-images.githubusercontent.com/1396070/37912897-d26a4f7c-3113-11e8-89d6-6be4b771d0b1.png)
