### ISSUE TITLE
styleClass is broken for dropdown

### ISSUE THREAD

**Issue by paultaman** [primefaces/primeng#480]
styleClass does not currently set the class style for dropdowns

```
<div [ngClass]="{'ui-dropdown ui-widget ui-state-default ui-corner-all ui-helper-clearfix':true,'ui-state-hover':hover&&!disabled,'ui-state-focus':focus,'ui-state-disabled':disabled}" 
            (mouseenter)="onMouseenter($event)" (mouseleave)="onMouseleave($event)" (click)="onMouseclick($event,in)" [ngStyle]="style" [class]="styleClass">
```

I believe the issue is that the styleClass assignment to [class] above does nothing.

**Comment by cagataycivici** [comment]
I can't replicate;

{code}
<p-dropdown [options]="cities" [(ngModel)]="selectedCity" styleClass="my-class"></p-dropdown>
{code}

my-class ends up at the main div element of p-dropdown.
