### ISSUE TITLE
Master Detail data table

### ISSUE THREAD

**Issue by nsksaisaravana** [primefaces/primeng#4801]
Please provide master detail grid as shown below. Master having different columns and details having different columns.

![image](https://user-images.githubusercontent.com/17681573/34861432-de79f2ac-f7b8-11e7-9f48-3c9db318cfaa.png)

**Comment by matthiasscudlik** [comment]
why don't you just use two tables?

**Comment by cagataycivici** [comment]
There is expandable rows feature for this already.
