### ISSUE TITLE
Row based styling for TreeTable

### ISSUE THREAD

**Issue by Abhinav3414** [primefaces/primeng#4803]
I'm submitting a ...

[x] feature request => Please check if request is not on the roadmap already

**Current behavior**
Currently there is not handle for treetable rows such that alternate row color styling can be implemented on them. 
I am able to do it but only for root rows. 

**Expected behavior**
I am using primeNG tree table for angular4 and I am trying to style it that odd and even rows has different colors consistently across all rows, irrespective of the rows expanded or collapsed.

**What is the motivation / use case for changing the behavior?**
We want to get alternate row colors consistently across all rows in tree table to make it look nicer.

**Environments:**
Windows 10, Eclipse Oxygen.1a Release (4.7.1a)

latest 5 x of angular and prime

**Comment by cagataycivici** [comment]
TreeTable will be reimplemented, please monitor;

#4813
