### ISSUE TITLE
splitbutton cant pass parameter

### ISSUE THREAD

**Issue by gravin** [primefaces/primeng#4805]
split button nearly no usage!
i used split button in datatable, looks item data not passed as event 
the event is as below, no usage actually.

{"originalEvent":{"isTrusted":true},"item":{"label":"Edit","icon":"fa-edit"}}

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.

**Comment by santoshkumar611** [comment]
how to send a parameter to command method if split button using with p-table??

**Comment by zeeshanadnan** [comment]
For the split button you can use its onClick and onDropdownClick events and in both you can pass parameters. So in onClick & onDropdownClick event pass the datatable parameter store it in a variable and when the related functions are called use the variable value.

**Comment by wisdom-17** [comment]
> For the split button you can use its onClick and onDropdownClick events and in both you can pass parameters. So in onClick & onDropdownClick event pass the datatable parameter store it in a variable and when the related functions are called use the variable value.

Hi @zeeshanadnan ,

Thanks for the explanation. It makes sense.

I am using Primevue 3.18.0 and it looks like there is no longer a onDropdownClick event for the split button component. So I was able to half implement your solution; it works if the user clicks on the button part of the split button first. If they click on the dropdown part of the button without clicking on the button part, I am unable to capture the event and store the row data in a variable. Hope this makes sense :/

Here is my summarised code:

```
        <SplitButton
          icon="pi pi-pencil"
          class="p-button-rounded p-button-success mr-2"
          @click="onClickEditButton(slotProps.data)"
          @dropdownClick="onClickEditButton(slotProps.data)"
          :model="editMenuItems"
        />
```

**Comment by faycal1** [comment]
in fact it so easy here the solution i get 
`<Column  header="Action" >
      <template #body="{ data }">
          <SplitButton
              icon="pi pi-ellipsis-v"
              text
              :model="[
                  { label: 'Edit', icon: 'pi pi-fw pi-pencil', command: () => editAction(data) },
                  { label: 'Delete', icon: 'pi pi-fw pi-trash', command: () => deleteAction(data) }
              ]"
          ></SplitButton>

      </template>
  </Column>`

**Comment by tarakeshp** [comment]
I am able to solve the issues as below.
Problem: How to pass row data to a splitbutton inside a table (actions column)
```
const getItems = function(data) {
    return [
    {
        label: 'Update',
        icon: 'pi pi-refresh',
        "row-data": data,
        command: (d) => {
            const rowData = d.item["row-data"] || arguments[0];
            console.log(rowData);
        }
    }]    
}
......
<DataTable>
    <Column>
        <template #body="{ data }">
            <SplitButton label="Save" icon="pi pi-plus"  :model="getItems(data)" />
        </template>
    </Column>
</DataTable>
```

**Comment by ibandim123** [comment]
> in fact it so easy here the solution i get
> 
> ```
> <Column  header="Action" >
>       <template #body="{ data }">
>           <SplitButton
>               icon="pi pi-ellipsis-v"
>               text
>               :model="[
>                   { label: 'Edit', icon: 'pi pi-fw pi-pencil', command: () => editAction(data) },
>                   { label: 'Delete', icon: 'pi pi-fw pi-trash', command: () => deleteAction(data) }
>               ]"
>           ></SplitButton>
> 
>       </template>
>   </Column>
> ```

Not work for me...
