### ISSUE TITLE
Dropdown breaks if selectItem value is an object

### ISSUE THREAD

**Issue by paultaman** [primefaces/primeng#481]
If dropdown selectItem value is an object, selecting any element besides the first element will yield the first element instead.

Looking at the dropdown code, it accesses the value of the object with the below code:

`let selectedOption = this.options[this.findItemIndex(item.dataset.value, this.options)];`

When inspecting the onChange event that is emitted, $event.originalEvent.target.dataset yields the below data:

```
dataset: DOMStringMap
  label: "EUR"
  value: "[object Object]"
```

So when findItemIndex(...) executes, it's comparing the string "[object Object]" using the == operator to selecItems within the options list, which will return true when compared to any element in the list.

**Comment by paultaman** [comment]
On a little further investigation, ListBox also uses selectItem as the underlying object and does not have this same issue. 

In comparison, listBox uses this code:
`let selectedItem = this.domHandler.findSingle(item.parentNode, 'li.ui-state-highlight');`

While dropdown uses this code:
`let selectedOption = this.options[this.findItemIndex(item.dataset.value, this.options)];`

This may be an option if you can't find a way to correctly set the value of dataset.

**Comment by cagataycivici** [comment]
We'll review, thank you.

**Comment by cagataycivici** [comment]
Tracking at #364
