### ISSUE TITLE
New TreeTable

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#4813]
Reimplement TreeTable based on the architecture of new p-table (successor of p-dataTable). Initial feature set would be;

- High performance
- Template driven
- Sort
- Page
- Scrollable
- Frozen Columns
- Lazy Loading
- Incell Edit
- Row and Cell based styling
- Resizable Columns
- Reorderable Columns
- Responsive
- Selection
- Column Group
- ContextMenu
- Column Toggle

**Comment by nsksaisaravana** [comment]
Can't wait for this!! Thanks guys for your contribution.

**Comment by jingweihaha** [comment]
Thanks, guys!

**Comment by asingh3886** [comment]
Any idea when we get these features?

**Comment by vayamdevindia** [comment]
Its end of feb 2018...any updates on this

**Comment by Bathri** [comment]
@cagataycivici May I know is the above features are updated in tree component?

**Comment by alex-snap** [comment]
Please, give these awesome features..

**Comment by aldrindizonh** [comment]
i hope they will release this awesome feature!

**Comment by cagataycivici** [comment]
New TreeTable is schedule for PrimeNG 6.0, we plan to sync it with Angular 6.0 release which is due april I believe. We'll be at NgConf in mid april so new p-treeTable will be ready by then.

**Comment by aldrindizonh** [comment]
hello @cagataycivici , is your new version of PRIMENG will include the tree table drag and drop?

**Comment by goel-sunny** [comment]
when will new TreeTable will come , i need the  re sizable feature , search , filtering features

**Comment by bhuvhi** [comment]
Please provide us the release date for the new tree table. In need of pagination, virtual scroll badly.

**Comment by cagataycivici** [comment]
It should be ready by the end of April so 1 month from now.

**Comment by goel-sunny** [comment]
can you provide me idea how i search a data in case of lazy loading because data is available in the JSON file so it is available in the object at time of expansion but in this secenerio i dont get the data. any suggestion.

**Comment by bhuvhi** [comment]
Do you have plans to support lazy loading within the child nodes? For example, onNodeExpand, load 10 child nodes and when you scroll, load more.

**Comment by vjpc** [comment]
@cagataycivici Hi, could you please share the plan for new tree table when it will be available,

**Comment by l2018ng** [comment]
Will PrimeNG 6.0 be compatible with Angular 5?  Will the tree control have search/filter capabilities?

**Comment by JacobSiegle** [comment]
The details of the tree table are shared here for anyone interested. https://www.primefaces.org/primeng-5-2-5-released/

**Comment by eltigree** [comment]
Hi thanx primeng team for this new release, but where i can find this changes? i cant find this under the link you deployed and the documentations seems not actual. so how i can filter for example on this treetable?

**Comment by eltigree** [comment]
i tried the filter from new p-table, but still not working, will this come in release 6.0?

**Comment by cagataycivici** [comment]
Implementation starts next week, I'll keep you updated here.

**Comment by cagataycivici** [comment]
Implementation has started yesterday, should be available next week with 6.0.0-alpha.2.

![screen shot 2018-05-22 at 15 09 06](https://user-images.githubusercontent.com/686247/40361627-abafe1c6-5dd2-11e8-957a-b14b43ec39ae.png)

**Comment by cyberrranger** [comment]
@cagataycivici very nice, please don't forgot responsive view

**Comment by cagataycivici** [comment]
Not sure how a TreeTable can be responsive though.

**Comment by cyberrranger** [comment]
@cagataycivici  show http://examples.sencha.com/gxt/4.0.3/#ExamplePlace:basictreegrid

![screenshot 2018-05-23 09 11 22](https://user-images.githubusercontent.com/21671762/40408871-4b2240aa-5e69-11e8-9a3e-200682b4fead.png)

the solution from sencha is not bad, you can scroll from left to right, the width from the treetable is not 100% from the device

**Comment by cagataycivici** [comment]
What we have now is;

<img width="1326" alt="screen shot 2018-05-23 at 15 48 42" src="https://user-images.githubusercontent.com/686247/40425376-dd5d6f76-5ea0-11e8-9ec8-b8b24b6de7e1.png">
<img width="353" alt="screen shot 2018-05-23 at 15 48 48" src="https://user-images.githubusercontent.com/686247/40425377-ddc96a00-5ea0-11e8-9448-f3c4140c544d.png">

**Comment by cyberrranger** [comment]
could work, let's see

is a special responsive template?

**Comment by cagataycivici** [comment]
It is very flexible as you have full control over the markup, I've created a demo.

https://github.com/primefaces/primeng/blob/master/src/app/showcase/components/treetable/treetableresponsivedemo.ts
https://github.com/primefaces/primeng/blob/master/src/app/showcase/components/treetable/treetableresponsivedemo.html

**Comment by cyberrranger** [comment]
i can see, thank you very much

PS can you extend your demo data to long names?

you used short names: 
Documents / Work / Home

but no long names:
"Picture_with_a_horse.png" / "A very long name in the new Tree Table"

**Comment by cagataycivici** [comment]
All features that I've listed in the original post has been completed and new TreeTable will be released with alpha.2 in a couple of days, it is being documented now. Would be great to receive feedback before 6.0 final.

**Comment by eltigree** [comment]
onNodeSelect not working in beta-version

**Comment by dmeh89** [comment]
Nice job with the new implementation, it works much better than the last one. So... What about row reordering? There's any plan to add this feature in the next weeks?

**Comment by AravindBJ** [comment]
@cagataycivici There is a difference in column alignment between scrollable columns and Frozen columns in Frozen rows of tree table (under scroll section). Kindly look into it.

**Comment by samu9349** [comment]
Can u please help me out?
i am using PrimeNg v: 5.2.3
can u please share is there any working code for treetable? 
am getting Can't bind to 'rowNode' since it isn't a known property of 'p-treeTableToggler'.

i have imported below modules in app.module
 import {TreeTableModule} from 'primeng/treetable';

**Comment by cyberrranger** [comment]
> New TreeTable is scheduled for PrimeNG 6.0

**Comment by San3131** [comment]
For tree table, prime documentation shows that we can reorder column what about reordering rows. I need an ability to reorder rows. How can I achieve this? In my case, I had used prime tree table and I've combination of groups rows alongside rows which aren't group. I only want to reordered non grouping rows. I couldn't figure out any directive or so for row drag and drop. Is there any solution to solve this issue?
