### ISSUE TITLE
add refresh button in paginator to reload data table

### ISSUE THREAD

**Issue by godfryd** [primefaces/primeng#4815]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Could you add a refresh button to paginator or generally to data table to reload data?
See example below:
![image](https://user-images.githubusercontent.com/176567/34927775-01b60eac-f9b9-11e7-8bfb-be2cde4cf8de.png)

**Comment by olingerc** [comment]
I agree with this. Especially in the case of lazy loading one needs a way to trigger a reload without losing the current settings like sorting. The datatable.reset method loses all current settings.

**Comment by cagataycivici** [comment]
Use paginatorLeftTemplate and paginatorRightTemplate to add your refresh icon to reset the data or do something else.

**Comment by pantonis** [comment]
@cagataycivici can you give an example of how paginatorLeftTemplate  is used?
