### ISSUE TITLE
Basic FileUpload fails to clear input field on call to clear()

### ISSUE THREAD

**Issue by brooms** [primefaces/primeng#4816]
**I'm submitting a ...** 
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
A call to FileUpload.clear() does not clear the native input field when in basic mode

**Expected behavior**
Native input field should be cleared

**Minimal reproduction of the problem with instructions**
- Create a basic FileUpload component with customUpload="true"
`<p-fileUpload class="file-upload-button" chooseLabel="Open" mode="basic" customUpload="true" (uploadHandler)="onUpload($event)" (onSelect)="onSelect($event)"></p-fileUpload>`
- Upload a file, force a call to clear() after the file has been successfully uploaded
- Try uploading the same file again, file can be selected but will fail to upload since a change event is never fired

Attempting to upload the same file twice using the basic FileUpload component fails even after a call to clear().  Adding `this.basicFileInput.nativeElement.value = '';` to clearInputElement() (when not in advanced mode) seems to resolve the issue.

* **Angular version:** 5.0.2

* **PrimeNG version:** 5.0.2

* **Browser:** Chrome
 
* **Language:** TypeScript 2.4.2

* **Node (for AoT issues):** 9.3.0

**Comment by JamboBuenna** [comment]
Bump :-)

After calling fileUploader.clear() selecting the same file does not appear to fire the onSelect event again.

**Comment by seralej** [comment]
hi brooms, may you please let me know hoy did you force the call to clear()? i want to clear the form and hide files after submit.

thanks in advance!

**Comment by amitesh786** [comment]
I have 2 solutions, and it works, you can also try -

** First one -> **
**HTML**
`<p-fileUpload #fileUpload (uploadHandler)="uploadFile($event, fileUpload)">`

**TS**
`uploadFile(event, fileUpload) {
    this.uploadService.doSomething(event.files[0]).subscribe(x => {
       ...do some stuff...
       fileUpload.clear(); // this will clear your file
    });
}`

** Second one - if you're using angular then -> **

**HTML**
`<p-fileUpload #fileUpload (uploadHandler)="uploadFile($event)">`

**TS**
` @ViewChild('fileUpload', {static: false}) fileUpload: any;`
`uploadFile(event, fileUpload) {
    this.uploadService.doSomething(event.files[0]).subscribe(x => {
       ...do some stuff...
       this.clear(); // this will clear your file
    });
}`

`clear() {
		this.fileUpload.clear();
	}`
Try I hope it will work in your case.

**Comment by seralej** [comment]
Cheers mate! it worked for me, i really apreciate!
