### ISSUE TITLE
name property for p-spinner

### ISSUE THREAD

**Issue by jisqaqov** [primefaces/primeng#4821]
add "name" property for p-spinner component because i get exception ( If ngModel is used within a form tag, either the name attribute must be set or the form
      control must be defined as 'standalone' in ngModelOptions.)  to use in a form

**Comment by jupin-r** [comment]
You can add name to spinner widget yourself. Check out my demo http://plnkr.co/edit/QChAEripFNF809gVj4rK?p=preview

I don't think that this issue is valid feature request and should be closed.
