### ISSUE TITLE
Picklist - filter is not retriggered after move

### ISSUE THREAD

**Issue by coettl** [primefaces/primeng#4827]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request 
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/BosE7sLXz21SE6DIQ9EJ?p=preview

**Current behavior**
After i move an element from the available side to the selected side with an active filter on the selected side, the filter for the selected side is not retriggered.

**Expected behavior**
When i move an element from the available side to the selected side with an active filter i expect that the filter is retriggerd.

**Minimal reproduction of the problem with instructions**
1. Go to http://plnkr.co/edit/BosE7sLXz21SE6DIQ9EJ?p=preview
2. Set the filter on the right side to "a"
3. Select "Christian" on the left side and click ">" 
4. Christian is not shown in the right filtered list

* **Browser:** [all]
 
* **Language:** [all]

**Comment by cagataycivici** [comment]
Not sure, let's wait for more feedback. It would be confusing for the user to hide the item after move as well. That's another point of view.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
