### ISSUE TITLE
Problem with html special (+unicode) chars in menu and dialog title

### ISSUE THREAD

**Issue by beatjost** [primefaces/primeng#4829]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

https://plnkr.co/edit/cDwYBcLXIJQmf1CTpkVo?p=preview

**Current behavior**
HTML special chars (umlaut) like &amp; or &ouml; are displayed as plain text.

**Expected behavior**
Chars should be converted to the specific character...
https://www.w3schools.com/html/html_symbols.asp 

**Minimal reproduction of the problem with instructions**
Open plunker and see the first menu-item.

**What is the motivation / use case for changing the behavior?**
Like to properly define special chars.

**Please tell us about your environment:**

Windows/Linux

* **Angular version:** 2.0.X
Angular 5.2.0

* **PrimeNG version:** 2.0.X
PrimeNG 5.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
any
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
This is expected due to interpolation, Angular does display them as they are and we rather not use innerHTML here. You can use header component with custom content for dialog though with innerHTML.
