### ISSUE TITLE
TurboTable custom filtering

### ISSUE THREAD

**Issue by AndreaBarbasso** [primefaces/primeng#4830]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
It seems that the new TurboTable only accepts the same filters as the old DataTable, except a few more, and does not allow customization.

**Expected behavior**
It would be great to be able to pass to a given column (or to the whole TurboTable, if necessary) a custom filtering function (`filterFunction(value, filter)`).

**What is the motivation / use case for changing the behavior?**
I've seen a few DataTable filter requests in PrimeNG issues. Customization would prevent this, and at a fairly cheap price (the filtering function may be either a `column` attribute, or passed in the `Table.filter` method, instead of the `matchMode` parameter).

**Comment by cagataycivici** [comment]
TurboTable is not released yet, please do not create issues for an unreleased component.

**Comment by kareljan** [comment]
TurboTable is released now. But this is not in it, so can you reopen this issue?

**Comment by hyzyla** [comment]
Would be nice feature
