### ISSUE TITLE
fullTemplateTypeCheck option incompatibility

### ISSUE THREAD

**Issue by TishchenkoAlex** [primefaces/primeng#4832]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
https://blog.angular.io/angular-5-2-now-available-312d1099bd81
After ng build --prod with new  **fullTemplateTypeCheck** options error stack:

ERROR in node_modules/primeng/components/datatable/datatable.d.ts.ColumnHeaders.html(7,17): : Property 'tabindex' does not exist on type 'ColumnHeaders'.
node_modules/primeng/components/datatable/datatable.d.ts.TableBody.html(38,103): : Expected 1 arguments, but got 2.
node_modules/primeng/components/datatable/datatable.d.ts.TableBody.html(40,103): : Expected 1 arguments, but got 2.
node_modules/primeng/components/panelmenu/panelmenu.d.ts.PanelMenu.html(19,130): : Expected 0 arguments, but got 1.
node_modules/primeng/components/multiselect/multiselect.d.ts.MultiSelect.html(46,92): : Property 'i' does not exist on type 'MultiSelect'.
node_modules/primeng/components/orderlist/orderlist.d.ts.OrderList.html(12,149): : Property 'disabled' does not exist on type 'OrderList'.
node_modules/primeng/components/orderlist/orderlist.d.ts.OrderList.html(17,162): : Expected 2 arguments, but got 1.
node_modules/primeng/components/orderlist/orderlist.d.ts.OrderList.html(26,152): : Expected 2 arguments, but got 1.

**Comment by Ayuob-Alfouzan** [comment]
I upgraded to 5.2.4 and more than half of the errors are fixed, but I still have 4 remaining,

ERROR in node_modules\primeng\components\tabview\tabview.d.ts.TabPanel.html(6,31): : Property 'columns' does not exist on type 'TabPanel'.
node_modules\primeng\components\megamenu\megamenu.d.ts.MegaMenu.html(18,178): : Property 'child' does not exist on type 'MegaMenu'.
node_modules\primeng\components\megamenu\megamenu.d.ts.MegaMenu.html(18,67): : Property 'child' does not exist on type 'MegaMenu'.
node_modules\primeng\components\megamenu\megamenu.d.ts.MegaMenu.html(18,154): : Property 'child' does not exist on type 'MegaMenu'.

**Comment by steverob2k** [comment]
I submitted a PR for the TabPanel issue - [https://github.com/primefaces/primeng/pull/5469](url)

**Comment by christian-laakmann** [comment]
Hi @cagataycivici,

this isssue has not been fixed completely and should be reopended.

See comments above and PR #5467 by @h-arora
