### ISSUE TITLE
Uncaught TypeError: this._reflector.guards is not a function

### ISSUE THREAD

**Issue by MHacker9404** [primefaces/primeng#4833]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => Search github for a similar issue or PR before submitting
```
**Current behavior**
clone the repository
ng build
ng serve
console exception with that message

**Expected behavior**
no exception

**Please tell us about your environment:**
Windows 10

* **Angular version:** 2.0.X
5.2.0

* **PrimeNG version:** 2.0.X
5.0.3-SNAPSHOT

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome

**Comment by MHacker9404** [comment]
dis

**Comment by cagataycivici** [comment]
This happened to us before and upgrading node.js fixes it.

**Comment by MHacker9404** [comment]
Running the most recent version of nodejs - kinda hard to update it

**Comment by SickBeat** [comment]
Hey so why was this closed? did someone figure it out? It didn't work for me.

**Comment by xblaster** [comment]
Same issue here, latest version of nodejs. Please reopen it

**Comment by balazs630** [comment]
As said: "this will be an issue with @angular 5.2.0 - is not an issue with 5.1.1"
In your package.json file, set angular core dependencies to "~5.1.0", delete node_modules and do a fresh npm install under your project.

**Comment by serdanilov** [comment]
I am still having this issue, tryied angular 5.2.5, switched to 5.1.0 , the issue persists. 
Node.js is 9.5.0

**Comment by NaifousBS** [comment]
I had the same issue after importing a project and trying to do `npm install` and get my `node_modules` from `package.json` file.
The main cause is probably the incompatibility between versions in your project.
I resolved this with upgrading my general modules & workspace modules.

Steps to reproduce:

- Remove `node_modules` folder from your project (`rm -rf ./node_modules`)
- `sudo npm install -g npm-check-updates` if you don't have it
- `ncu -u` in your project workspace where is located `package.json` file
- Then `sudo npm install`
- `ncu -g` to check outdated general modules
- `sudo npm install -g {OUTDATED_MODULE}` for each outdated module you have in your general modules list

**Comment by waitingsong** [comment]
It seems issue resolved with ionic cli v3.20.0

cli packages: (d:\program\nvm\v8.10.0\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.1.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.10.0
    npm               : 5.6.0
    OS                : Windows 7

--------------
  "dependencies": {
    "@angular/common": "~5.2.9",
    "@angular/compiler": "~5.2.9",
    "@angular/compiler-cli": "~5.2.9",
    "@angular/core": "~5.2.9",
    "@angular/forms": "~5.2.9",
    "@angular/http": "~5.2.9",
    "@angular/platform-browser": "~5.2.9",
    "@angular/platform-browser-dynamic": "~5.2.9",

**Comment by ivancho2802** [comment]
Hola si es en ionic lo resolvi con
`ionic cordova platform rm android`
`ionic cordova platform add android`
resulta que habian algunos plugin que no se instalaron funciono para mi agradezco los comentarios

**Comment by matiasAS** [comment]
no entiendo @ivancho2802 , que relación tiene ese error con la solución?

**Comment by madurimanoj** [comment]
so, how do we solve this issue? @serdanilov @MHacker9404 @cagataycivici @SickBeat @xblaster @balazs630

**Comment by sanjaykumarns** [comment]
Faced this issue with angular 5.1.1 and node version 8.15.0. Is this issue is solved or not?

**Comment by sergioChL** [comment]
I have the same problem here, I have removed and added the folders but still resolving the same error when installing the android apk or running "ionic cordova run browser"

my info

 @ionic/cli-utils  : 1.19.3
    ionic (Ionic CLI) : 3.20.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.2.4
    Cordova Platforms  : android 8.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.15.0
    npm               : 6.4.1
    OS                : macOS
    Xcode             : Xcode 10.3 Build version 10G8

Environment Variables:

    ANDROID_HOME : /Users/user/Library/Android/sdk

Misc:

    backend : pro
