### ISSUE TITLE
Blur event getting fired when clicking on autocomplete's suggestions list

### ISSUE THREAD

**Issue by av89** [primefaces/primeng#4835]
Hi,

I have a requirement wherein i have to hide the autocomplete control on lost focus.

But autocomplete blur event gets fired even if we are selecting items from the suggestions list, which is not expected because we are still in scope of the control.

Is there any solution for this? 

Thanks in advance!

**Comment by cagataycivici** [comment]
This is expected, list is actually another element which causes blur of the input when clicked.
