### ISSUE TITLE
CardModule is not an exported member of primeng/primeng

### ISSUE THREAD

**Issue by VNYoeri** [primefaces/primeng#4836]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/LLIzWVTkWGCnw050FjRr?p=preview

**Current behavior**
Importing CardModule gives a typescript compile-error:
`ERROR in src/app/shared/shared.module.ts(5,103): error TS2305: Module '"C:/sources/fin-web/fin-bestelaanvragen/bestelling-spa/node_modules/primeng/primeng"' has no exported member 'CardModule'.`

Note: the `primeng/exports/` has no `card.js`, whereas the `primeng/src/app/components` does contain a card-folder and a `card.ts` file with an exported member `CardModule`.

**Expected behavior**
CardModule should be included when pulling changes.

**Minimal reproduction of the problem with instructions**
Import CardModule in a project that uses primeng as a node_module.

**Please tell us about your environment:**
'ts':   'npm:plugin-typescript@4.0.10/lib/plugin.js',
'typescript':  'npm:typescript@2.0.3/lib/typescript.js',

* **Angular version:** 5.0.X

* **PrimeNG version:** 5.0.2

**Comment by cagataycivici** [comment]
Seems to be fixed in after 5.0.2, I can see it exported, still you should import from "primeng/card" instead.
