### ISSUE TITLE
Datatable (selectionmode multiple) header checkbox status is enabled when no rows present for a case.

### ISSUE THREAD

**Issue by kartik468** [primefaces/primeng#4837]
[app.zip](https://github.com/primefaces/primeng/files/1638491/app.zip)

Header checkbox remains checked when we clear the value after the table is rendered. (in this case after button click)
Attached the files for the same.

Explanation of code:

**app.component.html**
********************************
<p-dataTable #dqListDataTableRef [value]="cars" [(selection)]="selectedCars" dataKey="vin">

  <p-column selectionMode="multiple"></p-column>
  <p-column field="vin" header="Vin"></p-column>
  <p-column field="year" header="Year"></p-column>
  <p-column field="brand" header="Brand"></p-column>
  <p-column field="color" header="Color"></p-column>
</p-dataTable>

<button type="button" class="btn btn-large btn-block btn-default" (click)="onEmptyClick()">Empty</button>
********************************

**app.component.ts**
********************************
import { Component, ViewChild } from '@angular/core';
import { DataTable } from 'primeng/primeng';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {

  @ViewChild('dqListDataTableRef') dqListDataTableRef: DataTable;

  selectedCars = [];

  cars = [
      { 'brand': 'VW', 'year': 2012, 'color': 'Orange', 'vin': 'dsad231ff' },
      { 'brand': 'Audi', 'year': 2011, 'color': 'Black', 'vin': 'gwregre345' },
      { 'brand': 'Renault', 'year': 2005, 'color': 'Gray', 'vin': 'h354htr' },
      { 'brand': 'BMW', 'year': 2003, 'color': 'Blue', 'vin': 'j6w54qgh' },
      { 'brand': 'Mercedes', 'year': 1995, 'color': 'Orange', 'vin': 'hrtwy34' },
      { 'brand': 'Volvo', 'year': 2005, 'color': 'Black', 'vin': 'jejtyj' },
      { 'brand': 'Honda', 'year': 2012, 'color': 'Yellow', 'vin': 'g43gr' },
      { 'brand': 'Jaguar', 'year': 2013, 'color': 'Orange', 'vin': 'greg34' },
      { 'brand': 'Ford', 'year': 2000, 'color': 'Black', 'vin': 'h54hw5' },
      { 'brand': 'Fiat', 'year': 2013, 'color': 'Red', 'vin': '245t2s' }
    ];

  onEmptyClick() {
    this.cars = [];
    this.dqListDataTableRef.reset();
    console.log(this.selectedCars);
  }
}

********************************

Steps to reproduce:
1- You can see datatable rendered with the above car rows.
2- Click the Empty button on which value of cars is set to empty.
3- You can see empty datatable but with header checkbox checked. (it should be unchecked)

I have tried using datatable.reset() but it is not working. 
Please let me know if it is bug or there is a solution that i am missing.

**Comment by cagataycivici** [comment]
DataTable is deprecated and maintained anymore in favor of new p-table so closing the issues. Note that p-table should have this working fine.

**Comment by kartik468** [comment]
Well thanks for your feedback, 
I want to know Which version of angular supports p-table (turbo table)?
