### ISSUE TITLE
New import system fails under AOT

### ISSUE THREAD

**Issue by MedinaGitHub** [primefaces/primeng#4841]
I want to use the new turboTable but my import doesn't work

**Comment by sebaiona** [comment]
Same thing for me.

In fact, when I take this example I have the same problem too : 
`import {ButtonModule} from 'primeng/button';`

When I updated the package I had `UNMET PEER DEPENDENCY primeng@5.2.0-rc.1`...

Is there a particular dependy that I would need ?

**Comment by jbgarr** [comment]
@MedinaGitHub Can you share whatever errors you're getting? That would help the debugging process I'm sure.

**Comment by cfarver888** [comment]
I'm seeing similar issues after upgrading. I'm using primeng 5.2.0-rc.1 and Angular 5.2.1.

I imported the new TableModule into my app.module file as described in the documentation, but the IDE  (Visual Studio Code) isn't recognizing it as a component. That being said, it _is_ working in my app...
The error message I'm getting is:

> [Angular]
> 'p-table' is not a known element:
> 1. If 'p-table' is an Angular component, then verify that it is part of this module.
> 2. If 'p-table' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

**Comment by cagataycivici** [comment]
It works for me at primeng-quickstart-cli, please compare;

https://github.com/primefaces/primeng-quickstart-cli

I'm unable to replicate.

**Comment by patriknil90** [comment]
With ng build --watch, everything works. When trying to ng build --prod:

Unexpected value 'TableModule in C:/www/struktur/protected/views/hyperion/node_modules/primeng/table.js' imported by the module 'ProjectModule in
C:/www/struktur/protected/views/hyperion/src/app/project/project.module.ts'. Please add a @NgModule annotation

**Comment by patriknil90** [comment]
update: 
Seems like this isn't only for the TableModule for me. Tried to change import { CalendarModule } from "primeng/primeng" to be imported from "primeng/calendar" instead and got the same error there.

The problem is that I can't seem to import TableModule from "primeng/primeng" which in the Calendar case seems to fix it.

**Comment by PoTato-C** [comment]
We've got the exact same issue in a project too, with the build --prod and it happens for the Table but also if we try to import an element with the new import style 'primeng/element'

**Comment by patriknil90** [comment]
tried adding export * from './components/table/table'; to node_modules/primeng/primeng.d.ts but get the following intellisence error: 

[ts] Module './components/datatable/datatable' has already exported a member named 'ScrollableView'. Consider explicitly re-exporting to resolve the ambiguity.
[ts] Module './components/datatable/datatable' has already exported a member named 'TableBody'. Consider explicitly re-exporting to resolve the ambiguity.

**Comment by patriknil90** [comment]
Okay, took another approach.

Adding the file table.d.ts in node_modules/primeng with the code

`export * from './components/table/table';`

made it work. Every other module than table needs to be imported from "primeng/primeng" when building with --prod.

**Comment by bias-keenly** [comment]
Having same issue.  Seems to be AOT related.  Building without AOT or prod flag builds ok with new 'primeng/[component_name]' pathing.  With AOT need to use old pathing 'primeng/primeng' or the full path to component

**Comment by david-lee** [comment]
@bias-keenly You are right. It looks AOT issue. When I run by `ng serve --aot` then I got an error like `Please add a @NgModule annotation.` It worked fine with '--aot' option. 
I tested with `import { InputTextModule } from 'primeng/inputtext';`

**Comment by cagataycivici** [comment]
I've replicated the situation, thank you for the feedback. For my case it only happens on AOT build with prod. Adding d.ts files fixes this, so we'll do an 5.2.RC2 on 22nd with these changes.

**Comment by cagataycivici** [comment]
d.ts files of single modules will also be published to npm now which fixes the issue.

**Comment by writeless** [comment]
Hi @cagataycivici I'm using the last release in npm (5.2.0-rc.1) and get the error yet.
Do you have the date for new release with fix? thanks

I tried import module from specific module and from main module, and get errors:

**from specific module**
`import { InputTextModule }  from 'primeng/inputtext';`

> "ERROR in : Unexpected value 'InputTextModule in E:/_writeless/prime/node_modules/primeng/inputtext.js' imported by the module 'AppModule in E:/_writeless/prime/src/app/app.module.ts'. Please add a @NgModule annotation."

**from main module**
`import { InputTextModule }  from 'primeng/primeng';`

> ERROR in : Unexpected value 'InputTextModule in E:/_writeless/prime/node_modules/primeng/primeng.d.ts' imported by the module 'AppModule in E:/_writeless/prime/src/app/app.module.ts'. Please add a @NgModule annotation.
> node_modules/primeng/components/common/api.d.ts(1,28): error TS2307: Cannot find module '../dom/domhandler'.
> node_modules/primeng/components/autocomplete/autocomplete.d.ts(2,28): error TS2307: Cannot find module....

**Comment by scurk1415** [comment]
When will RC2 be available?

**Comment by adama357** [comment]
It just became available, and it works! Thanks! :)

**Comment by ozturki** [comment]
It does not seem to be fixed.

**Comment by ozturki** [comment]
import { TableModule } from 'primeng/table';
does not work
import { TableModule } from 'primeng/components/table/table';
works

**Comment by cagataycivici** [comment]
Sorry, we can't replicate and many users reported that issue is fixed.

**Comment by MarvinZ** [comment]
I had the same issue, and also with _MultiSelectModule_

so I had to do this: 

//other prime components
import { TabViewModule } from 'primeng/primeng';
import { FieldsetModule } from 'primeng/primeng';
import { InplaceModule } from 'primeng/primeng';
import { GrowlModule } from 'primeng/primeng';

// components that caused building for prod errors...
**import { TableModule } from 'primeng/components/table/table';
import { MultiSelectModule } from 'primeng/components/multiselect/multiselect';**


and now it works

In Dev mode, everything works fine

**Comment by mikeplacko** [comment]
Why is it that primeng.js (and prime.d.ts) at the root of the project does not contain an export for the new Table component? It's the only module missing and perhaps is causing some of the odd behavior. It doesn't appear to be needed in my code, but its still odd that no export exists here.

**Comment by ivijan** [comment]
it is weird that in order to import TableModule I need to use 
import { TableModule } from 'primeng/table';
it should be listed in main primeng importer
{ * } from 'primeng/primeng';

**Comment by slmmm** [comment]
This is still an issue experiencing with primeng@5.2.7.
Is there a fix or workaround?
