### ISSUE TITLE
new turbo table questions

### ISSUE THREAD

**Issue by bbuehrer** [primefaces/primeng#4842]
1. The theme doesn't work for header and body. it looks like different to the old dataTable.
2. How can i use custom-sort? i only find pSortableColumn wich is bind to a fixed field.
3. Can i set the width in em of each column without set the width of the table?

**Comment by bbuehrer** [comment]
The problem to dynamically set the scrollHeight is also as with the old dataTable:
[scrollHeight]="tableScrollHeight"
When i set tableScrollHeight in the ts-file then it only works at startup.

**Comment by cagataycivici** [comment]
Please use forum for questions instead of issue tracker.

**Comment by bbuehrer** [comment]
I will set the scrollHeight of TurboTable on the window.resize-event of app.component.
I set the scrollHeight to event.target.innerHeight - 50px
This works on startup, but when i resize the Browser-Window, then the schrollHeight of the Turbo-Table never changed.
