### ISSUE TITLE
Dropdown styling issue

### ISSUE THREAD

**Issue by mdevraj** [primefaces/primeng#4844]
**I'm submitting a bug 

```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

In the demo, 

https://www.primefaces.org/primeng/#/dropdown

**Current behavior**
when the dropdown loads downwards, the border is regarded. The same is not true when the dropdown loads upwards.
![downwards](https://user-images.githubusercontent.com/16409490/35049331-a2aa3690-fbc5-11e7-93c3-ce9d19c558ee.png)
(The space between the dropdown and the panel exists and there is no overlap)

![upwards](https://user-images.githubusercontent.com/16409490/35049332-a2f630ae-fbc5-11e7-82e7-95c655d79ac7.png)
(The space between the dropdown and the panel is not there and clearly overlaps)

**Expected behavior**
The expectation is that the behaviour should be the same in both scenarios.

**Comment by cagataycivici** [comment]
I think it is there mathematically, the shadow makes it look different.
