### ISSUE TITLE
Bootstrap theme support for TurboTable

### ISSUE THREAD

**Issue by ARandomDude** [primefaces/primeng#4845]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
(not sure if bug or feature request)

In the node_modules folder, in primeng/resources/themes, it seems every theme but bootstrap has been updated to contain styles for .ui-table and everyone, apart from bootstrap, received a theme.scss. Also, the bootstrap theme option is gone from the demo site -- does that mean the bootstrap theme is dropped or will there be bootstrap support for the new TurboTable?

**Comment by cagataycivici** [comment]
Sorry, bootstrap theme is deprecated in favor of Avalon.
