### ISSUE TITLE
Autocomplete "required" property issue with "ngNativeValidate" Directive

### ISSUE THREAD

**Issue by ayush987goyal** [primefaces/primeng#4851]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

http://plnkr.co/edit/MjGUs7gduM0SOCGFqzAT?p=preview

**Current behavior**

The native validation trigger even if the required property is set to false.

**Expected behavior**

It should behave like it would without the ngNativevalidate directive.

**Minimal reproduction of the problem with instructions**
1. In the plnkr click on submit button without entering anything in the input.
2. The native validation triggers even when required is set to false

**Please tell us about your environment:**

* **Angular version:** 5.0.X

* **PrimeNG version:** 5.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
