### ISSUE TITLE
GlobalFilter doesn't update table on search input clear.

### ISSUE THREAD

**Issue by dlinx** [primefaces/primeng#4853]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/vuLyuNgUf36urSNwFyLh?p=preview

**Current behavior**

1) Search text in global filter. It will filter the data in datatable.
2) click on cross button of global filter, it will clear search input but it will not reflect on datatable.
**Expected behavior**

Datatable should display all records as there is no string in global filter.

**Minimal reproduction of the problem with instructions**
Use search input instead of text input. (type="search") for global filter input.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.0.0

* **PrimeNG version:** 5.0.2

* **Browser:** [ Chrome 63.0.3239.132]

 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
DataTable is deprecated and not maintained anymore in favor of p-table aka TurboTable of 5.2.
