### ISSUE TITLE
Versioning on the PrimeNG Documentation Website

### ISSUE THREAD

**Issue by ayush987goyal** [primefaces/primeng#4854]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
I think we should have version support on the PrimeNG docs website. Sometimes new properties/methods are added to an existing component in a new version which cannot be used in older versions. A simple dropdown mentioning the available major versions and its corresponding docs will certainly help a lot. This type of feature is maintained on Angular's docs website as well.

**Comment by bniedermeyer** [comment]
This would be great to have. Only displaying docs for the most recently published version (including RC releases) causes confusion as seen in #4959.

**Comment by Cecilya** [comment]
I support this. Either make old documentations available (e.g. as the suggested drop-down menu) OR mark each feature with the version it applies to. The former would probably be less of a hassle to implement.

**Comment by vlodko** [comment]
@ayush987goyal agree 100%.
I was looking at p-growl page and found a really useful `key` property, but it didn't work for me :(
Then I pulled the code for v4.3.0 and guess what - it wasn't in the component!
Thousands of people are still using 4.x version but docs already refers to 5.x and there is no easy way to get back docs for 4.x 👎

**Comment by cagataycivici** [comment]
Added the version to the footer, for older versions you can run them locally by forking from the tags. We rather not deploy all 80+ releases to the public demo.
