### ISSUE TITLE
Bug in Turbotable export 

### ISSUE THREAD

**Issue by pantonis** [primefaces/primeng#4858]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When trying to export a table I get ```Cannot read property 'length' of undefined
    at Table.exportCSV (table.js:659)```

The bug exists because I didnt declare columns to ts code but instead I created the table using HTML and as a result ```this.columns``` int the following code of table.js is undefined:

```
for (var i = 0; i < this.columns.length; i++) {
	var column = this.columns[i];
	if (column.exportable !== false && column.field) {
		csv += '"' + (column.header || column.field) + '"';
		if (i < (this.columns.length - 1)) {
			csv += this.csvSeparator;
		}
	}
}
```

**Comment by cagataycivici** [comment]
Yes, columns should be dynamic for export to work, I've added this to the docs now.

**Comment by pantonis** [comment]
What about no dynamic columns? Hiw is this going to work?
