### ISSUE TITLE
build --prod

### ISSUE THREAD

**Issue by vtumino** [primefaces/primeng#4859]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**

- build --prod 
- import {CalendarModule} from 'primeng/calendar;

in an angular 5 app I get a:
`Unexpected value 'CalendarModule in [...]/node_modules/primeng/calendar.js' imported by the module 'MyModule' Please add a @NgModule annotation.`  

- import {CalendarModule} from 'primeng/primeng;

instead and all works like a charm.

**Please tell us about your environment:**

* **Angular version:** 5.2.1

* **PrimeNG version:** 5.2.0-rc.1

* **Browser:** [all]
 
* **Node (for AoT issues):** 9.4.0

**Comment by cagataycivici** [comment]
I'm unable to replicate, sorry. Please compare your project with;

https://github.com/primefaces/primeng-quickstart-cli

It uses new 'primeng/{module}' convention.

**Comment by KingdaCrash** [comment]
I'm getting the same error while using table (the new turbo table) or InputSwitch

**Comment by ozturki** [comment]
Same issue
