### ISSUE TITLE
Quill editor jumps to the beginning when text typed very fast

### ISSUE THREAD

**Issue by Toktik** [primefaces/primeng#486]
The title is self-describing.

How to reproduce:
1) Go to primeng editor demo
2) Type like this: http://www.giphy.com/gifs/3o72FjSNKHSP7SkUPC

**Comment by cagataycivici** [comment]
Can you replicate at;

http://beta.quilljs.com/

**Comment by Toktik** [comment]
No, I could not.

**Comment by cagataycivici** [comment]
We've checked and this is already fixed if you use beta8 with quill beta release, we'll update the showcase soon as well.

**Comment by Diazbesjorge** [comment]
Many thanks Çağatay this is working well for us now.
