### ISSUE TITLE
calendar set firstDayOfWeek withotu whole locale object

### ISSUE THREAD

**Issue by Ketec** [primefaces/primeng#4860]
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
The default  week start being Sunday (which savage country has week start on Sunday?) Does not work for us. 
The calendar is used in 8 different places/components and defining whole locale every single time i use a calendar in a component is a complete overkill.

**Comment by cagataycivici** [comment]
On the long run, it is better to handle these with locales, otherwise we'll end up duplicating all locale props.

**Comment by Ketec** [comment]
The locale should at least extend the default (use properties in  component conf, rest should be default) - right now you have to  set up the entire locale object each time you use the component.

Right now the calendar is in ~12 places - which means 12 times i'v had to to copy paste the locale object. 
There does not seem to be a global way to set locale for primeng in appcomponent or appmodule for example.
