### ISSUE TITLE
Improve TurboTable virtual scroll

### ISSUE THREAD

**Issue by codehunter13** [primefaces/primeng#4864]
Hi, 

First of all, thx for the new TurboTable :)

Is it possible to change the virtual scroll implementation of the new TurboTable. When you reach the end of the already loaded items and you scroll  a little further, you see a grid with no rows until the new items are fetched.  See the attachement with a screenshot form your demo site
![2018-01-18 15_32_13-primeng](https://user-images.githubusercontent.com/7559059/35103023-fb47f05e-fc64-11e7-9421-ce602da95048.png)

Solutions:
1. disable scrolling when the last loaded row gets visible until the new rows are loaded
2. (Best option) Start loading new rows before the last row is reached. This way the user even doesnt notice that not all rows are fetched.

Regards,
Glenn

**Comment by cagataycivici** [comment]
We'll check this to make it smoother after 5.2.

**Comment by codehunter13** [comment]
Great!

**Comment by cagataycivici** [comment]
VirtualScrolling for Table is reimplemented from the ground up (#8855) and this particular case i no longer an issue with the new implementation.
