### ISSUE TITLE
unable to persist model in Auto Complete 

### ISSUE THREAD

**Issue by Mounika30** [primefaces/primeng#4866]
I have a space  character before the options in the suggestions list .so when i select the option with space and once I blur out of the autoComplete then model doesnt persist.
For example : In the plunker  when uou click on the show ,auto-complete  will display and if there is a space before " NEWYORK" then  the model doesnt persist.

Here is  the plunker 👍 

http://plnkr.co/edit/H4ys4rCtgwITR2RqCoQE?p=preview

**Comment by cagataycivici** [comment]
Try with 5.2.3 please, should work with it.
