### ISSUE TITLE
Spinner do not allow decimal input

### ISSUE THREAD

**Issue by oumarkona** [primefaces/primeng#4867]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/ZkRNKau7N9ab3OR4EJWE?p=preview

**Current behavior**

1) When you enter 123.23 spinner do not allow you to enter dot. For this value, you can only enter 123 but not .23
2)  If you press dot key and any other number together, you can enter decimal number.
3) When you have decimal number  in spinner like 123.23:

- if you modify it like 1023.23:
    - First one you spinner put separator in whole part as 1,023.23 => ok
    - Second one, spinner put focus at the end of number => nok
- if you modify it like 1023.2453:
    - First one you spinner put separator both in whole and decimal part as 1,023.2,453 => nok
    - Second one, spinner put focus at the end of number => nok

**Expected behavior**

 1) Spinner most allow to enter decimal number without any keys combinaision
 2) Do not put separator in decimal part

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.0.X

* **PrimeNG version:** 5.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   8.9.1

**Comment by cagataycivici** [comment]
Try 5.2.-RC1 please.

**Comment by oumarkona** [comment]
we will wait for final release not candidate.
