### ISSUE TITLE
TurboTable Frozen columns and Virtual scroll

### ISSUE THREAD

**Issue by felipebri23** [primefaces/primeng#4868]
### I have a p-table component that has virtual scroll and frozen columns. When the onLazyLoading event occurs, the frozen-body part of the ng-template is updated correctly, but the ng-template body part is not updated. Attached image of what happens.

![image](https://user-images.githubusercontent.com/28927144/35106583-e3aa078e-fc6e-11e7-8c28-d26141f0adba.png)

* **Angular version:** 5.0.X

* **PrimeNG version:** 5.2.0-rc.1"

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by cagataycivici** [comment]
Could you please add a plunkr?

**Comment by felipebri23** [comment]
Plunkr: http://plnkr.co/edit/DW6CAF?p=preview

**Comment by karloscode** [comment]
Hello, same problem here, any ideas please?
