### ISSUE TITLE
New Import system is not working

### ISSUE THREAD

**Issue by codehunter13** [primefaces/primeng#4870]
Hi,

The new import system as documented on your website is not working:
import { ButtonModule } from 'primeng/button'; gives the error:
[at-loader] ./ClientApp/app/shared/shared.module.ts:9:30 
    TS7016: Could not find a declaration file for module 'primeng/button'. 'C:/Projects/Pleegzorg/Pleegzorg.Web/node_modules/primeng/button.js' implicitly has an 'any' type.
  Try `npm install @types/primeng/button` if it exists or add a new declaration (.d.ts) file containing `declare module 'primeng/button';` 

Regards,
Glenn

**Comment by cagataycivici** [comment]
Can you send us a sample project to help us replicate, we've tried several times with no luck.

**Comment by cagataycivici** [comment]
Can you please create a file name button.d.ts under node_modules/primeng with the following content and try again;

button.d.ts
```
export * from './components/button/button';
```

**Comment by cagataycivici** [comment]
<img width="137" alt="screen shot 2018-01-19 at 15 57 36" src="https://user-images.githubusercontent.com/686247/35151977-80e5311e-fd31-11e7-94b0-778f91df9321.png">

**Comment by cagataycivici** [comment]
Tracked at;

https://github.com/primefaces/primeng/issues/4841
