### ISSUE TITLE
More than one data table in expander (is losing format for displayed table).

### ISSUE THREAD

**Issue by IrishCass** [primefaces/primeng#4871]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/Q5hZgBA6DlXf55UvyVqw?p=preview

**Current behavior**

We are using a PrimeNG datatable (version 4.2.1).
One of the columns is an expander column.
Within the expanded column, we have 2 data tables, only one will be visible for an expanded row.
If these data tables have different structures, we see strange results.
When you initially expand out a row of Sub Table Format 1, everything is ok.
Next, if you expand out a row of Sub Table Format 2, it displays just fine, however, the previously expanded row for Sub Table Format 1 is cleared out and you see nothing but empty rows and empty header where the data was previously displayed.

**Expected behavior**
Would like to be able to dynamically display different table formats underneath the expanded row based upon criteria of the expanded row.

**Minimal reproduction of the problem with instructions**
                <p-dataTable #dt [value]="ictdataHeaderRptResults" selectionMode="multiple" [(selection)]="selectedIct" (onRowSelect)="onRowSelect($event)"
                    [paginator]="true" [rows]="15" [responsive]="true" [globalFilter]="gb" [contextMenu]="cm" [rowsPerPageOptions]="[15,30,45,75,100,200,500,1000]"
                    expandableRows="true" (onRowExpand)="expandRow($event)" scrollable="true" paginatorPosition="top">
                    <p-header>
                        <div class="ui-helper-clearfix">
                            <span style="float:left">
                                <button type="button" pButton icon="fa-file-excel-o" iconPos="left" class="btn" label="Excel Listing" (click)="exportIctRptToExcel()"></button>
                                <button type="button" pButton icon="fa-file-excel-o" iconPos="left" class="btn" label="Excel GRR" (click)="exportGrrToExcel()"></button>
                                <button type="button" pButton icon="fa-file-excel-o" iconPos="left" class="btn" label="Excel Board" (click)="exportBoardToExcel()"></button>
                                <button type="button" pButton icon="fa-undo" iconPos="left" (click)="clearSelections()" class="btn" label="Clear Selected Rows"></button>
                                <button type="button" pButton icon="fa-refresh" iconPos="left" (click)="queryICT(dt)" class="btn" label="Refresh Data"></button>
                            </span>
                            <div class="tblTitle">ICT Data Listing</div>
                        </div>
                    </p-header>
                    <p-column expander="true" styleClass="col-icon" [style]="{'width':'25px'}"></p-column>
                    <p-column field="AssemblySerialNumber" header="Board" [sortable]="true" [style]="{'width':'200px'}" [filter]="true" filterPlaceholder="Search"
                        filterMatchMode="contains"></p-column>
                    <ng-template let-rec pTemplate="rowexpansion">
                        <div class="expandTbl">
                            <div class="expandRow">
                                <div class="expandBoardTableCell">
                                    <p-header>
                                        <div class="ui-helper-clearfix">
                                            <div class="tblTitle">ICT Test Data for Board: {{rec.AssemblySerialNumber}}</div>
                                        </div>
                                    </p-header>
				    <div *ngIf="format1">
                                      <p-dataTable #dt2 [value]="expandedBoards[rec.InstanceId]">
                                        <p-column field="Name" header="Name" [sortable]="true" [filter]="true" filterPlaceholder="Search" filterMatchMode="contains"></p-column>
                                        <p-column field="Measured" header="Measured" [sortable]="true" [filter]="true" filterPlaceholder="Search" filterMatchMode="contains">
                                            <ng-template let-col let-rec="rowData" pTemplate="body">
                                                <span #x>{{ checkNeg(x, rec) }} {{rec[col.field]}}</span>
                                            </ng-template>
                                        </p-column>
                                        <p-column field="HighTolerance" header="HighTolerance" [sortable]="true" [filter]="true" filterPlaceholder="Search" filterMatchMode="contains"></p-column>
                                        <p-column field="LowTolerance" header="LowTolerance" [sortable]="true" [filter]="true" filterPlaceholder="Search" filterMatchMode="contains"></p-column>
                                      </p-dataTable>
                                    </div>
				    <div *ngIf="format2">
                                      <p-dataTable #dt3 [value]="expandedBoards[rec.InstanceId]">
                                        <p-column field="Pins" header="Pins" [sortable]="true" [filter]="true" filterPlaceholder="Search" filterMatchMode="contains"></p-column>
                                      </p-dataTable>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </ng-template>
                </p-dataTable>

**What is the motivation / use case for changing the behavior?**

Flexibility in displaying sub-tables.

**Please tell us about your environment:**
IIS

* **Angular version:** 2.0.X
5.0.0

* **PrimeNG version:** 2.0.X
4.2.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
IE, Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.4.2

* **Node (for AoT issues):** `node --version` =   
v6.11.2

**Comment by cagataycivici** [comment]
DataTable is deprecated and will be removed in the future in favor of new p-table, please try the new table which should not have this issue.
