### ISSUE TITLE
Autocomplete forceSelection bug with dropdown

### ISSUE THREAD

**Issue by Spiral1401** [primefaces/primeng#4874]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/KyBcP8Tc0J13G2DkjiLp?p=preview

**Current behavior**
With forceSelection=true, Value doesn't change when one is already selected

**Expected behavior**
Value to change

**Minimal reproduction of the problem with instructions**
Open autocomplete dropdown, click "Rome". Open again, click "London". Value doesn't change. Clearing the value and choosing one from scratch works.

* **Angular version:** 2.0.X
5.0.0

* **PrimeNG version:** 2.0.X
5.2.0-rc.1

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/commit/4d611945ec2aa4fdbcfd14897290d5cf8caf2ee6
