### ISSUE TITLE
ShiftKey based range selection for TurboTable

### ISSUE THREAD

**Issue by ARandomDude** [primefaces/primeng#4881]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
(not sure if bug or feature request)

When holding down the shift key in a DataTable, you could select multiple rows. There does not seem to be a way in the new TurboTable to do this; it does not work on the demo page and is not mentioned anywhere. Is this a bug or was this feature removed? I deem it as an important feature.

**Comment by cagataycivici** [comment]
It was not removed but left out of the scope of 5.2.RC1, we'll do it now for RC2.
