### ISSUE TITLE
scrollHeight not dynamically on new Turbo Table

### ISSUE THREAD

**Issue by bbuehrer** [primefaces/primeng#4884]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

The property "scrollHeight" only works on startup and not dynamically.
[scrollHeight]="myTableScrollHeight"
PrimeNg 5.2.0-RC1

**Comment by ARandomDude** [comment]
See #4114 for this.

By the way, setting an percentage value as scrollHeight (etc 100%) does not make the table adapt when e.g. the browser window is resized.

**Comment by bbuehrer** [comment]
I set the scrollHeight in px (sample: browser window height-60px) and it does not make the table adapt when the browser window is resized.

**Comment by bbuehrer** [comment]
The problem is also in PrimeNg 5.2.0-RC2

**Comment by Ketec** [comment]
Well this is a completely breaking change. I cannot migrate over to new table without this.

**Comment by lbdorrou** [comment]
I temporarily fixed this in our project with a little bit of a hack, all you need to do is convince the grid that the scroll height has changed.

I just toggle between 100% and 99% on a window resize. Not the cleanest solution, but it works for now

`onResize() {
    this.scrollHeight = this.scrollHeight === '100%' ? '99%' : '100%';
  }`

`[scrollable]="true" [scrollHeight]="scrollHeight" (window:resize)="onResize($event)"`
