### ISSUE TITLE
Set lazy as false in TurboTable

### ISSUE THREAD

**Issue by pantonis** [primefaces/primeng#4885]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Lazy is not defined and has as a result to throw error. As it was before when using globalfilter this.lazy was undefined and an error was thrown

**Comment by cagataycivici** [comment]
How can we rep
