### ISSUE TITLE
PrimeNG export csv with style

### ISSUE THREAD

**Issue by saptarshi007** [primefaces/primeng#4887]
Hello there,
I am exporting a table using p-dataTable. All is good. But problem is I want to apply some style in excel sheet while exporting so that after export its looks professional. 
I am not able to find any hints or materials on how to do it by primeng.
Please help!

**Comment by cagataycivici** [comment]
I don't think it is possible, you need to write your own exporter. You may use the one from PrimeNG to get an idea.
