### ISSUE TITLE
Sorting a TurboTable calls the onLazyLoad function twice

### ISSUE THREAD

**Issue by ARandomDude** [primefaces/primeng#4889]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/WkS8CW641gowwpgxzHaA?p=preview
(Click on the table headers)

**Current behavior**
When the new turbo table is in lazy mode, clicking on a header to sort the table calls the lazy load function twice.

**Expected behavior**
The function should be called once.

**Please tell us about your environment:**
See Plunkr.

**Comment by banderberg** [comment]
@cagataycivici this is not resolved.  Sorting p-table causes onLazyLoad to fire once from onClick and then again when the sortOrder setter is called.

**Comment by calchuchesta** [comment]
Any idea when this might be fixed? I'm facing this exact issue.

**Comment by Okz1** [comment]
You can try something like this !this.loading && this.lazyLoadData()

**Comment by NathanAlcantara** [comment]
> You can try something like this `!this.loading && this.loadData()`

This helps, but i think that is a workaround not a behavior
