### ISSUE TITLE
Wrong dropdown layout with Bootstap

### ISSUE THREAD

**Issue by sentyaev** [primefaces/primeng#489]
primeng 1.0.0-beta.8
primeui 4.1.10
bootstrap 3.3.6

![prime_bootstrap](https://cloud.githubusercontent.com/assets/2112331/16099589/be9c7ae4-3361-11e6-8386-3791ecbb9dd6.png)

**Comment by sentyaev** [comment]
I workaround it by changing 
  `.ui-dropdown .ui-dropdown-trigger { width: 20px; }`
  `.ui-dropdown {padding-right: 20px;}`

**Comment by cagataycivici** [comment]
Bootstrap has box-sizing: border-box for everything which is likely to break some of our components, so we can't add this css to our core as it will break cases where bootstrap is not included on page, so you have to keep it in your app as the workaround.
