### ISSUE TITLE
Turbo Table global filter issue

### ISSUE THREAD

**Issue by kcsahoo** [primefaces/primeng#4892]
The global filter throws error on input.
Throws length of undefined error in line 575 in the component js file.
My table template is:
<p-table #dt [value]="rows" reorderableColumns="true" scrollable="true" scrollHeight="700px">
        <ng-template pTemplate="caption" let-company>
            <i class="fa fa-search" style="margin:4px 4px 0 0"></i>
            <input type="text" pInputText size="70" placeholder="{{'companies.management.Search' | translate}}" (input)="dt.filterGlobal($event.target.value, 'contains')" style="width:auto">
            <button pButton type="button" *ngIf="canManageCompanies" class="ui-button-secondary" (click)="newCompany(company)" icon="fa-plus-square-o" label=" {{'companies.management.NewCompany' | translate}}" style="float:right"></button>
        </ng-template>
        <ng-template pTemplate="header">
            <tr>
                <td style="display:none"></td>
                <td style="width:70%;text-align:center;">{{'companies.management.Name' | translate}}</td>
                <td style="width:10%;text-align:center;">{{'companies.management.Users' | translate}}</td>
                <td style="width:10%"></td>
                <td style="width:10%"></td>
            </tr>
        </ng-template>
        <ng-template pTemplate="body" let-company>
            <tr [pSelectableRow]="company">
                <td style="display:none">{{company.id}}</td>
                <td style="width:70%">{{company.name}}</td>
                <td style="width:10%">{{company.applicationUsers}}</td>
                <td style="width:10%"><button type="button" pButton (click)="editCompany(company)" class="ui-button-secondary" icon="fa-pencil-square-o" label="{{'companies.management.Edit' | translate}}"></button></td>
                <td style="width:10%"><button type="button" pButton (click)="deleteCompany(company)" class="ui-button-secondary" icon="fa-trash-o" label="{{'companies.management.Delete' | translate}}"></button></td>
            </tr>
        </ng-template>
        <ng-template pTemplate="summary">
            (Count: {{rowCount}})
        </ng-template>
    </p-table>

**Comment by mehmet2006** [comment]
I am getting same problem.
I am using firebase firestore to get data.
I fill the table without any problem.
But global filter throws error:

`ERROR TypeError: Cannot read property 'length' of undefined
    at Table._filter (table.js:575)
    at Table.filter (table.js:540)
    at Table.filterGlobal (table.js:550)
    at Object.eval [as handleEvent] (UsersComponent.html:11)
    at handleEvent (core.js:13540)
    at callWithDebugContext (core.js:15049)
    at Object.debugHandleEvent [as handleEvent] (core.js:14636)
    at dispatchEvent (core.js:9955)
    at eval (core.js:10580)
    at HTMLInputElement.eval (platform-browser.js:2628)`

**Comment by bias-keenly** [comment]
It is confusing, was having the same issue.  You need to define the column dictionary and assign to [columns] on the p-table like the example.  The global filter uses this.columns to figure out the columns to sort on.  Without that defined will get that error.

**Comment by mehmet2006** [comment]
@bias-keenly you are right. I've just created table dynamically and it works. both global and normal filtering works when table is created dynamically.

When I tried to add cols to the manually created table, filtering didnt work right...

**Comment by pantonis** [comment]
Maybe related to this https://github.com/primefaces/primeng/issues/4885.
For a temp workaround I set [lazy]="false"

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/issues/4908

**Comment by togbyte** [comment]
I ran into a similar issue, but resolve it by setting appropriate field and add to template body.

Global filtering works if you set [columns]="cols" where 
this.cols=[ {field: "col1-field", header:"col1-header"}]

Only col1-field is searchable if you specify columns in your pTemplate="body". For example,

<ng-template pTemplate="body" let-leave let-columns="columns">
