### ISSUE TITLE
TurboTable columns cannot be resized when columnResizeMode="expand" and scrollable="true"

### ISSUE THREAD

**Issue by ARandomDude** [primefaces/primeng#4893]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/tDKCcQHBIMGprgnllR6D?p=preview
(Resize a column)

**Current behavior**
If a TurboTable has set the following properties, resizing a column does not work and throws an error.

If set:
resizableColumns="true" 
columnResizeMode="expand"
scrollable="true"

Error thrown:
Cannot read property 'nativeElement' of undefined
    at Table.onColumnResizeEnd (table.js:789)
    at ResizableColumn.onDocumentMouseUp (table.js:1624)
   ...

**Please tell us about your environment:**
See the Plunkr.

**Comment by cagataycivici** [comment]
It is a known issue that was left out in RC1 so good catch :)
