### ISSUE TITLE
Eye icon to multiselect to hide all unselected items in list

### ISSUE THREAD

**Issue by mcwebdev** [primefaces/primeng#490]
I added a little eye icon to toggle show/hide selected list items in the multiselect component. I was going to use elementRef to add display none to unselected items but appears I cant drill into that component using dom manipulation, or that dom manipulation is now deprecated in ng2 for performance reasons?

http://thankweb.com/multiselect.png
`.ui-datatable-header .ui-widget-header:after {
    content: "\f06e";
    position: absolute;
    right: 23px;
    z-index: 99;
    top: 10px;
    font: normal normal normal 14px/1 FontAwesome;`

**Comment by cagataycivici** [comment]
What is the purpose of the eye icon? Why hide them all?

**Comment by mcwebdev** [comment]
In some layouts it may not be desirable to have the labels span above the component. The eye icon could toggle the visibility off of unselected  menuItems.This might be useful in a long list like stock tickers. The user may scroll a list of 100 menuItems get half way down and want to see what was selected. Clicking the eye icon will hide all the menuItems that have not been picked. Now the user can scroll a smaller list and easily see what they selected.

**Comment by mcwebdev** [comment]
A click on the eye icon would toggle this css

`ul.multiselect li{display:none;}

ul.multiselect li.ui-state-highlight{display:block;}
`

**Comment by cagataycivici** [comment]
Could you please provide screenshot on where the eye icon should be displayed.

**Comment by dsoltesz** [comment]
![ddl1](https://cloud.githubusercontent.com/assets/1462985/18669446/f9d714be-7eef-11e6-82f5-22a5e99dc49c.png)
![ddl2](https://cloud.githubusercontent.com/assets/1462985/18669447/f9da9d46-7eef-11e6-9a83-4f4b0ae5614c.png)

clicking eye toggles the list to see all plus selected or just selected

**Comment by cagataycivici** [comment]
We'll consider this and reply at jira.

**Comment by mcwebdev** [comment]
I have an edited version of your component with the enhancements. Let me know if you would like the snippet.

**Comment by cagataycivici** [comment]
We'd appreciate a PR for sure.

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.

**Comment by mcwebdev** [comment]
Can you update the demo showcase with example of this working? I don't think you understood our request. I don't see any "eye" icon that toggles the visibility of 'unselected' items.

Thanks

**Comment by cagataycivici** [comment]
This is a feature request that is not implemented @mrtcndkn.

**Comment by mcwebdev** [comment]
Thanks, I will get a PR in sometime later this week.

**Comment by cagataycivici** [comment]
We've decided to do it however please create a ticket at your PRO jira to discuss details.
