### ISSUE TITLE
Make Dialog Container Clickable

### ISSUE THREAD

**Issue by mmmaxi** [primefaces/primeng#4900]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When there is a Dialog Container which is moveable this isn't really obvious for the end user.

**Expected behavior**
It would be great if the Dialog Container would have a clickable boarder, where the mouse turns into a hand. 

**What is the motivation / use case for changing the behavior?**
The user would be able to better understand the possibility to move the Dialog Container

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
[all]

**Comment by ctrl-brk** [comment]
You can add a css style for ui-dialog-titlebar:hover or ui-dialog-title:hover

**Comment by cagataycivici** [comment]
Better to handle on your side with hover with css.
