### ISSUE TITLE
Right-click in data-table editable field stop the edition in Firefox

### ISSUE THREAD

**Issue by tleveque23** [primefaces/primeng#4901]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

No plunker needed, just your own demo site: https://www.primefaces.org/primeng/#/datatable/editable

**Current behavior**
If you use Firefox v56,v57+ and if you have an editable cell in a data-table and you right click in the input field, the editor is closed and back in read-only mode!

**Expected behavior**
Should stay in edition mode and let us use the contextual menu.

**Minimal reproduction of the problem with instructions**
Just go to https://www.primefaces.org/primeng/#/datatable/editable and try on any "year" cell.

**What is the motivation / use case for changing the behavior?**
We need to be able to use the contextual menu to paste or copy any text.

**Please tell us about your environment:**

* **Angular version:** 2.0.X
5.2

* **PrimeNG version:** 2.0.X
5.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Firefox 56, Firefox 57
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by tleveque23** [comment]
Also, note that if you have a tooltip on that field, the tooltip will stick there forever!

**Comment by cagataycivici** [comment]
I'm sorry but I have to close this because DataTable is not maintained anymore in favor of p-table.
