### ISSUE TITLE
Multiselect updateLabel fails when selectedItemsLabel does not include {}

### ISSUE THREAD

**Issue by michaelplavnik** [primefaces/primeng#4905]
I'm submitting a bug report.

_I am not attaching plunker fork, as the issue is best demonstrated by the source code_

In [multiselect.ts](https://github.com/primefaces/primeng/blob/master/src/app/components/multiselect/multiselect.ts) component in updateLabel() function at line 394 code assumes presence of the `{}` in the value of `selectedItemsLabel` property (e.g. [0] on the regex matches). 
Documentation does not require such presence, and requiring it prevents simple and useful use cases, e.g. displaying the same string to the user when nothing or all is selected when implementing filter parameters.

**Fix is trivial, please implement it.**

**Comment by bfaulk96** [comment]
Experiencing the same problem. This either needs to be fixed or documented, and the fix is not difficult.

**Comment by Pikadili83** [comment]
This problem is still present (v5.2.6). Whenever I provide plain text to be used as selectedItemsLabel, it gets reverted to the default value ({0} selected).

**Comment by magnusjohannessen** [comment]
I am also still having this problem (v 7.1.0)
