### ISSUE TITLE
Add globalFilterFields to TurboTable

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#4911]
To support global filtering in static columns and to provide flexibility even with dynamic columns to restrict which columns global filtering should be applied on e.g.

```
[globalFilterFields]="['vin','year']"
```

**Comment by tharris9d** [comment]
Thanks, This helped a ton!

**Comment by Ben197** [comment]
Thanks cagataycivici a more detailed explenation would be nice !
