### ISSUE TITLE
TurboTable clear of data does not work if filter is present

### ISSUE THREAD

**Issue by pantonis** [primefaces/primeng#4913]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/wLCdKtxQSmsL8VbzfD2q?p=preview

**Current behavior**
TurboTable clear of data does not work if global filter is present.

**Expected behavior**

**Minimal reproduction of the problem with instructions**
Open the plnkr and then type in Merceded  in the global filter, You will see only one row at the table. Then click None button (clears the cars array). You will notice that the table is not cleared

**Comment by cagataycivici** [comment]
I can't replicate with latest changes so assuming that it got fixed by now, if issue persists, please create a new issue ticket.
