### ISSUE TITLE
PrimeNG DataTable - no results are shown in table when enter date type

### ISSUE THREAD

**Issue by Mljaks** [primefaces/primeng#4914]
Hello!
I have input type="text" to search data on PrimeNG DataTable.

<input #searchInput class="form-control mr-sm-2" type="text" placeholder="">
I have problem to search data by date. Date format is [dateFormat]="'dd.mm.yy'".

<ng-template let-col let-doc="rowData" pTemplate="body">
            {{doc[col.field]|dateFormat}}
</ng-template>

Anyone has some idea when enter value "14.2.2018" into input (searchFilter type"text") to be shown data in Datatable?

Angular 5
Primeng": "5.0.2"

**Comment by cagataycivici** [comment]
DataTable is deprecated in favor new p-table so not maintained anymore. Please migrate to new p-table.
