### ISSUE TITLE
long delay of 1 second of menu onItemMouseLeave 

### ISSUE THREAD

**Issue by ASK83** [primefaces/primeng#4917]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/Q5hZgBA6DlXf55UvyVqw?p=preview

**Current behavior**
After leaving the menu item it takes 1 second to clear the item which seems to be foreever for menus. 
**Expected behavior**
There should not be any delay when the mouse left the menu item.

**Minimal reproduction of the problem with instructions**
Just go to the primeng demo and go over menus it can be seen that it takes 1 second to clear the css after the mouse left the item. 

**What is the motivation / use case for changing the behavior?**
User interface would be lagy if have a 1 second delay in menu active/deactivation.

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X
"primeng": "^5.2.0-rc.1"

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Delay is handy to avoid closing the menu if users moves quickly, still set to 250ms to hide it faster.
