### ISSUE TITLE
p-calendar feature: two-month display

### ISSUE THREAD

**Issue by murraybauer** [primefaces/primeng#4919]
```
[x] feature request
```
**Two-month display for calendar**

Commonly needed to make range selection easier, particularly for reporting page UI's

Example using ngx-bootstrap [ngx-boostrap](https://valor-software.com/ngx-bootstrap/#/datepicker)

![image](https://user-images.githubusercontent.com/6551873/35255828-bb24e7ee-003c-11e8-94ee-9c76813c466f.png)

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/issues/4759
