### ISSUE TITLE
Support New Angular2 Form APIs

### ISSUE THREAD

**Issue by t246246** [primefaces/primeng#492]
With Angular 2.0.0-rc.2, we see the following warning when we are using forms:
```
It looks like you're using the old forms module. This will be opt-in in the next RC, and
     will eventually be removed in favor of the new forms module. For more information, see:
     https://docs.google.com/document/u/1/d/1RIezQqE4aEhBRmArIAS1mRIZtWFf6JxN_7B4meyWK0Y/pub
```
So when I switched to new form (comes from @angular/forms) to avoid this warning, ngModel no longer works without name property, (check also https://github.com/angular/angular/issues/9230), that means some of your component (or at least the corresponding example on your doc) does not work with new forms, for example,  [&lt;p-dropdown&gt;](http://www.primefaces.org/primeng/#/dropdown).

The error is
```
Name attribute must be set if ngModel is used within a form.
                      Example: <input [(ngModel)]="person.firstName" name="first">
```
and even after adding name tag and removing `<form>` element
```
browser_adapter.ts?9397:74 Error: No value accessor for ''
    at new BaseException (eval at <anonymous> (vendor.bundle.js:1),
    [...]
```

So I am asking you if there are plan to support it.

Best Wishes,

**Comment by cagataycivici** [comment]
Somehow ngModel without name worked for me;

```html
<input type="text" size="30" pInputText [(ngModel)]="text" />
```

I have disableDeprecatedForms(), provideForms() configured in bootstrap.

Getting no value accessor for p-dropdown though.

**Comment by cagataycivici** [comment]
Updated to new router and new forms of RC2
