### ISSUE TITLE
Continuous scroll between months

### ISSUE THREAD

**Issue by bladerunner41** [primefaces/primeng#4920]
```
[x] feature request
```
**Calendar - continuous scroll between months**

Many UI libraries, are implementing this.  Example: [fuel-ui datepicker](http://fuelinteractive.github.io/fuel-ui/#/component/datepicker)

![image](https://user-images.githubusercontent.com/6551873/35255919-146ded50-003d-11e8-94b6-9e3cd5f64951.png)

**Comment by yigitfindikli** [comment]
We'll reconsider if there is more community feedback on this. Thank you for your report.
