### ISSUE TITLE
TouchUI mode for Calendar

### ISSUE THREAD

**Issue by murraybauer** [primefaces/primeng#4921]
```
[x] feature request
```
**Calendar -TouchUI mode**

A datepicker is about the only input that commonly needs touch optimised version for mobile/tablet.

See example of[ angular-material TouchUI](https://material.angular.io/components/datepicker/overview) mode

**Comment by Ketec** [comment]
When this is implemented - could the time selector also be improved, clicking up and down arrows is a rather unusual approach instead of the usual ones (for material design you may see circular "clock" style or a scrollable list to choose value from)
