### ISSUE TITLE
p-dropdown enhancement/bug: item template not shown when selected

### ISSUE THREAD

**Issue by murraybauer** [primefaces/primeng#4922]
```
[X] feature request
```
The current selected value shown on the dropdown needs to use the item template as displayed in the dropdown options list.  Currently it is ignored/lost.

![image](https://user-images.githubusercontent.com/6551873/35256022-8979f2ec-003d-11e8-97f1-6b57245c9006.png)

An custom item template is often used to display critical information about an item - think an item title and important sub title or icon that needs to remain shown once the item is selected and on edit forms when data is repopulated.

This is how [ng ui-select2](https://valor-software.com/ng2-select/) works, but the library needs the full bootstrap css which interferes with a lot of things.

**Comment by cagataycivici** [comment]
There is selectedItemTemplate for this.
