### ISSUE TITLE
[5.2.0-rc.1] Does not build in prod mode

### ISSUE THREAD

**Issue by jw61** [primefaces/primeng#4931]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Even a fresh clone of primeng-quickstart-cli without any modifications does not build in prod mode with PrimeNG 5.2.0-rc.1 using the command `ng build -prod`. This results in the error:
`ERROR in : Unexpected value 'TableModule in C:/tmp/primeng-quickstart-cli-master/node_modules/primeng/table.js' imported by the module 'AppModule in C:/tmp/primeng-quickstart-cli-master/src/app/app.module.ts'. Please add a @NgModule annotation.`

![primeng](https://user-images.githubusercontent.com/25868056/35266400-25c33316-001b-11e8-9745-979d40c5e2cf.png)

**Expected behavior**
PrimeNG 5.2.0-rc.1 should build in prod mode

**Minimal reproduction of the problem with instructions**
- Download primeng-quickstart-cli from https://github.com/primefaces/primeng-quickstart-cli
- Run: npm install
- Run: ng build -prod
- `ERROR in : Unexpected value 'TableModule in C:/tmp/primeng-quickstart-cli-master/node_modules/primeng/table.js' imported by the module 'AppModule in C:/tmp/primeng-quickstart-cli-master/src/app/app.module.ts'. Please add a @NgModule annotation.`

**What is the motivation / use case for changing the behavior?**
Can't deploy PrimeNG if can't build in prod mode.

**Please tell us about your environment:**
Angular CLI: 1.6.3
Node: 8.9.4
OS: win32 x64
Angular: 5.2.1

* **Angular version:** 5.2.1

* **PrimeNG version:** 5.2.0-rc.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome: 63
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.4.2

* **Node (for AoT issues):** `node --version` =   
Node: 8.9.4

**Comment by ngohuunam** [comment]
me too

**Comment by cagataycivici** [comment]
Please do a search before creating new issues to help us out.

https://github.com/primefaces/primeng/issues/4841
