### ISSUE TITLE
Pipe on enum or boolean

### ISSUE THREAD

**Issue by wilson-young** [primefaces/primeng#4932]
I created a p-Table with filter when i received data from API there are enum and boolean
i created a pipe for showing "active" on table instead of showing "1"

```
<p-column field="is_active" header="Status" [filter]="true" filterMatchMode="equals" [sortable]="true">
        <ng-template pTemplate="filter" let-col>
            <p-dropdown [options]="isActive" [style]="{'width':'100%'}" (onChange)="dt.filter($event.value,col.field,col.filterMatchMode)" styleClass="ui-column-filter"></p-dropdown>
        </ng-template>
        <ng-template let-col let-bank="rowData" pTemplate="body">
            {{bank[col.field] | isActive}}
          </ng-template>
      </p-column>
```

but the problem is in global search. it search based on the boolean or enum instead of the character that show in table. is there any solution for this case?

![image](https://user-images.githubusercontent.com/9879527/35266937-4bd2fc94-0057-11e8-84b6-742d3a0b5968.png)

**Comment by cagataycivici** [comment]
I'm sorry but I have to close this because DataTable is not maintained anymore in favor of p-table.

**Comment by wilson-young** [comment]
is this issue solved on turbotable?
