### ISSUE TITLE
Dropdown items get loaded to DOM only after pressing on caret

### ISSUE THREAD

**Issue by TMaster** [primefaces/primeng#4935]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
The dropdown populate the items only after I press the caret button.

**Expected behavior**
The dropdown should populate the options items when rendering the control 

**Minimal reproduction of the problem with instructions**
Just copy the following code:

```<p-dropdown [options]="[{label: 'tomer'}, {label: 'tomer'}, {label: 'tomer'}, {label: 'tomer'} ]" placeholder="Select a something" ></p-dropdown>```

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows 7.
npm 5.5.1
Angular 5.5.1
primeNG:  5.0.2

Browser: chrome

 
* **Language:** TypeScript 2.4.2

* **Node (for AoT issues):** `node --version` =9.0.0

**Comment by cagataycivici** [comment]
Provide a plunkr please, otherwise we won't be able to work on it as this is not something we can replicate.

**Comment by TMaster** [comment]
found the problem. Thanks

**Comment by perkma** [comment]
I have the same problem. Maybe it would be helpful if you could describe what you did to fix this.
