### ISSUE TITLE
TurboTable: Resizing column not work well with fixed width in colgroup template

### ISSUE THREAD

**Issue by thornidlo** [primefaces/primeng#4940]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/OmOjnSSkQWUtKmXMGmDN?p=preview

**Current behavior**
When custom width is set via colgroup template and resizableColumns=true, then resize is correct for content, but not header. If i try resize last header column, there is error in console:

  TypeError: Cannot read property 'offsetParent' of null
    at Table.onColumnResizeEnd (table.ts:1062)
    at ResizableColumn.onDocumentMouseUp (table.ts:1706)
    ..
When columnResizeMode=expand is added, then there is console error:

zone.js:169 Uncaught TypeError: Cannot read property 'nativeElement' of undefined
    at Table.onColumnResizeEnd (table.ts:1094)
    at ResizableColumn.onDocumentMouseUp (table.ts:1706)
    ..

**Expected behavior**
1) allow me resize when set "fixed" width of column in colgroup and resizableColumns is set 
2) allow me resize when columnResizeMode is set to expand 
3) both 1) 2) when scrollable is set and horizontal scrollbar is shown, because i'm working with tables with many columns and header column texts are not usually short

* **Angular version:** 2.0.X
5.0

* **PrimeNG version:** 
5.2.0-rc.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
chrome, ff, opera

**Comment by cagataycivici** [comment]
You need RC2 for this;

https://github.com/primefaces/primeng/issues/4893

Please do a search before creating new tickets.

**Comment by pedrolps12** [comment]
I have version RC2
"primeng": "5.2.0-rc.2", 
and I can not change the width of the rows when I use a colgroup.
