### ISSUE TITLE
TurboTable: tab key navigation breaks after typing in input field

### ISSUE THREAD

**Issue by pschaffl** [primefaces/primeng#4942]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
I have an editable table with a date column (p-calendar) and a number column (pInputText). 
When I fill in the data just using the keyboard, entering the first date works as expected, and after pressing tab the text cell receives the class .ui-editing-cell, still as expected. As soon as I begin typing the number, the class .ui-editing-cell disappears from the cell. When I try to move on to the next date cell pressing the tab key, an error occurs in Table.moveToNextCell() (cannot find parentElement of undefined), because Table.findCell has not found the editing cell. 

**Expected behavior**
The cell being edited keeps the class .ui-editing-cell when the input field is edited, and the focus moves on to the next cell when the tab key is pressed.

**Please tell us about your environment:**
Ubuntu 16.04

* **Angular version:** 5.2.1

* **PrimeNG version:** 5.2.0-rc.2

* **Browser:** Chromium 63 | Firefox 57.0.4
 
* **Language:** TypeScript 2.6.2

**Comment by cagataycivici** [comment]
Create a plunkr please if you like this to be reviewed.

**Comment by pschaffl** [comment]
Thank you. Creating a plunk helped to identify the problem and find a solution:
http://plnkr.co/edit/fdIlcQzLvsbKngBKZ3VO?p=preview
I accidentally removed the css class ui-editable-column from the cell.
