### ISSUE TITLE
Missing common selection mode in TurboTable (as in DataTable)

### ISSUE THREAD

**Issue by ARandomDude** [primefaces/primeng#4943]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

I've already mentioned this in #4894, but since RC2 is out now and since I think it's really important, I want to emphasize this:

Take a look at the selection demo of the old datatable. The multiple mode meant that normal clicks behave as in single mode, but you have the option of holding the CTRL or SHIFT keys to make multiple selections. I think this is a very common usecase and ubiquitous in a lot of controls in applications.

With the new multiple selection mode in TurboTable behaving differently, there is no "native" way of implementing the beforementioned behavior.

Please re-implement a way to achieve this behavior.

**Comment by cagataycivici** [comment]
If more users demand it, why not. Right now only 2 up votes. We probably need 20 and so to do it.

**Comment by ARandomDude** [comment]
I understand and respect your decision; but please keep in mind that this may keep users from updating to the new TurboTable. Also Wijmo, Kendo UI, and Teradata, to name a few, support this behavior (as do most UI frameworks).

**Comment by andreeapNRO** [comment]
This has 9 votes, but it was requested in several threads. It would be good to extend the table with this feature.

**Comment by bossqone** [comment]
@ARandomDude please upgrade to v5.2.1 and use `metaKeySelection` option (boolean, set it to `true`). Example available here: https://www.primefaces.org/primeng/#/table/selection

**Comment by cagataycivici** [comment]
See;

https://primefaces.org/primeng/showcase/#/table/selection
