### ISSUE TITLE
Error with DataGridModule in 5.2.0-rc.2

### ISSUE THREAD

**Issue by sebaiona** [primefaces/primeng#4944]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/Q5hZgBA6DlXf55UvyVqw?p=preview

**Current behavior**

When I import `DataGridModule` I have an error.
In fact I didn't needed it yet so I commented it, and everything is now ok !

See what I have in Chrome console if I keep it : 
```
Uncaught Error: Template parse errors:
Can't bind to 'dropdownAppendTo' since it isn't a known property of 'p-paginator'.
1. If 'p-paginator' is an Angular component and it has 'dropdownAppendTo' input, then verify that it is part of this module.
2. If 'p-paginator' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("s" *ngIf="paginator && (paginatorPosition === 'top' || paginatorPosition =='both')"
                [ERROR ->][dropdownAppendTo]="paginatorDropdownAppendTo"></p-paginator>
            <div class="ui-datagrid-con"): ng:///DataGridModule/DataGrid.html@7:16
Can't bind to 'dropdownAppendTo' since it isn't a known property of 'p-paginator'.
1. If 'p-paginator' is an Angular component and it has 'dropdownAppendTo' input, then verify that it is part of this module.
2. If 'p-paginator' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("*ngIf="paginator && (paginatorPosition === 'bottom' || paginatorPosition =='both')"
                [ERROR ->][dropdownAppendTo]="paginatorDropdownAppendTo"></p-paginator>
            <div class="ui-datagrid-foo"): ng:///DataGridModule/DataGrid.html@16:16
```

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by codehunter13** [comment]
I got the same error.
Angular 5.2.1
PrimeNG: RC2

Regards,
Glenn

**Comment by codehunter13** [comment]
"I had this happen to me, it was simply Chrome refusing to reload paginator.js from the server. "
cleared my cache but still have this issue. also with the non rc version. somebody an idea?

**Comment by cagataycivici** [comment]
Unable to replicate with 5.2.3.
