### ISSUE TITLE
Use HTTPClient in FileUpload

### ISSUE THREAD

**Issue by netstart** [primefaces/primeng#4945]
```
[ x  ] feature request
```
Please change upload request from p-FileUpload to use HttpClient (Angular 4.3+), 
In this case I can  use interceptor to show my LoadingComponent in any upload requests.

Is better to add Bearer authentication header too.

**Comment by atmjesus** [comment]
I'm also waiting for this. It would be nice for adding headers and for using Angular HttpInterceptor.

Thanks

**Comment by kkdattaGIT** [comment]
@cagataycivici  This change broke OnUpload method. Now, event does not have the Response object coming back from server.

**Comment by mfcar** [comment]
> @cagataycivici This change broke OnUpload method. Now, event does not have the Response object coming back from server.

Same here.

**Comment by juri33** [comment]
That changes a lot and breaks a lot. Not a good idea to to this in a minor update ...

**Comment by jeslomo** [comment]
Same here, the method beforeUpload crash when read "event.xhr".

 onBeforeSend(event) {   
      event.xhr.setRequestHeader('bla bla bla');
  }

**Comment by jotae1e** [comment]
This is not minor update, folks.  If you use .upload() method to send a file and variables, this will not work.  

It's a very big update.

**Comment by namnhcntt** [comment]
I upgraded to 7.0.5, but the upload event does not call my HTTP_INTERCEPTORS in app.module.ts. Anyone can fix this? 
(I have another library that call my HTTP_INTERCEPTORS in the same application)

**Comment by szabolcssimonyi** [comment]
Today I realized xhr surprizingly disappeared from onBeforeSend $event in 7.0.0 and 7.0.3 too!! Is this possible to change released versions like that? It breaks my app since i append authentication to the header at this event.

**Comment by szabolcssimonyi** [comment]
Must agree with @jotae1e, made me a bad day too...
