### ISSUE TITLE
p-tableHeaderCheckbox and p-tableCheckbox is not a know element

### ISSUE THREAD

**Issue by mlangwell** [primefaces/primeng#4947]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/Q5hZgBA6DlXf55UvyVqw?p=preview

**Current behavior**

I import { TableModule } from 'primeng/components/table/table' just like every other module/component I have used. The table seems to work just fine. However, when I try to use the p-tableHeaderCheckbox or the p-tableCheckbox it throws an error saying they are not a know element. This is very crucial for our team and a very desirable feature. I created a plunker and it seems to work just fine. Do I need to import the checkboxes from somewhere else?

**Expected behavior**

This to work! :)

**Minimal reproduction of the problem with instructions**

All I did was copy/paste the code from the documentation for the table with checkboxes.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10, VS Code, NPM

* **Angular version:** 2.0.X

5.1.2

* **PrimeNG version:** 2.0.X

5.2.0-rc.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome, Firefox
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.4.2

* **Node (for AoT issues):** `node --version` =   
 6.11.0

**Comment by bolodania** [comment]
You should update primeng to 5.2.0-rc.2 version.

**Comment by syn-anujasaraogi** [comment]
I'm facing similar issue. Do we have a solution to the problem?

**Comment by bolodania** [comment]
I had the simillar issue but it was fixed by updating primeng to 5.2.0-rc.2. Are you sure that you have the latest version?

**Comment by syn-anujasaraogi** [comment]
Yupp. It resolved after taking latest. Thanks

**Comment by cagataycivici** [comment]
These features are added in 5.2.0-RC2 so you'd need RC2 to avoid this error.
