### ISSUE TITLE
TurboTable: Sorting and row groups don't seem to work together? 

### ISSUE THREAD

**Issue by adama357** [primefaces/primeng#4948]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/ynotZJbCQFduGsM7yJEA?p=preview

**Current behavior**
In the Plunkr, if you sort by Vin or Color, you'll notice that, while the columns are sorted correctly, the row group headers don't appear at the correct spot. I'm using the row group code found [in the documentation](https://www.primefaces.org/primeng/#/table/rowgroup). 

Meanwhile, if I replace [pSortableColumn]="col.field" and [field]="col.field" with pSortableColumn="col.field" and field="col.field", as suggested in #4846, when I try to sort by any column, all the column headers become highlighted, and sorting no longer happens. 

**Expected behavior**
As with p-dataTable, if you have row groups, all other sorting should be secondary, e.g., under Brand, Vin should be sorted separately.  I'm sure there is probably a simple way to do this programmatically. But it seems like either there should be some kind of built-in way for this to work, or else the work-around should be in the documentation.

**Please tell us about your environment:**
Windows 10

* **Angular version:** 5.0.0

* **PrimeNG version:** 5.2.0-rc.2

* **Browser:** [Chrome 63 | Firefox 57]

**Comment by bias-keenly** [comment]
Had that issue too.  Modified their doc code to work with sorting.

http://plnkr.co/edit/wDwhHlLlneTi0SIe6W9J?p=preview

**Comment by adama357** [comment]
@bias-keenly In your Plunk, when sorting by Vin or Color, you end up with three groups, labelled "Brand B", "Brand A", and then "Brand B" again. Looking at the p-dataTable documentation, it looks like the Subheader row group functionality is supposed to behave like this, so this is at least better than the way the p-table documentation works with sorting.  

Another possibly desirable behavior is for the groups to stick together, e.g., there's always "Brand A", then "Brand B", and you can sort the columns within those groups.

**Comment by cagataycivici** [comment]
There is no built-in row groups functionality, there is a demo to show how can be done in one way, so it is up to you how to do the sorting, note that there is customSorting available as well if you'd like to customize.

**Comment by jypandey1990** [comment]
@cagataycivici Can I get an example on above issue. Because grouping is distorted, if we do sorting on grouped data on different column. How to implement such scenario? Help would be appreciated.
