### ISSUE TITLE
New methods for Schedule

### ISSUE THREAD

**Issue by karser** [primefaces/primeng#495]
Hello, thanks for awesome components!
I have a small question, is there a way to obtain fullCalendar instance from schedule component?
For instance, in order to call [gotoDate](http://fullcalendar.io/docs/current_date/gotoDate/
) method I have to do the following:
```javascript
jQuery('.ui-widget').fullCalendar('gotoDate', date);
```

**Comment by cagataycivici** [comment]
Added new methods;

prev(), next(), prevYear(), nextYear(), gotoDate(date), incrementDate(duration), getDate(), today()

```xml
<p-schedule [events]="events" #fc></p-schedule>

<button type="button" pButton (click)="back(fc)"></p-button>
```

```typescript
export class MyModel {

    back(fc) {
        fc.prev();
    }
    
}
```
