### ISSUE TITLE
pKeyFilter has an issue in custom filters with RegExp

### ISSUE THREAD

**Issue by david-lee** [primefaces/primeng#4950]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
It doesn't validate properly a custom filter with RegExp. It is supposed to check ALL input values entered previously with the RegExp but it checks with a single input value entered right now.
'pValidateOnly' isn't set so it is false.
```
<input pInputText type="text" name="day"  [pKeyFilter]="dayRegx"  [(ngModel)]="client.day" maxlength="2">
```
RegExp: dayRegx

```
/^[1-3][0-9]?$/
```
**_After I enter 1 and then tried to enter 0 or 4 then it is blocked but if you enter 3 then is ok. 
It is because it doesn't check with '10 or 14' but only '0' or '4'. I found it from the pKeyFilter class._**

**Expected behavior**
It should test ALL input values with given custom RegExp. Do not check for only one input value.

**Please tell us about your environment:**

OS: MacOS Sierra
IDE: Visual Studio Code
Using NPM v5.6

* **Angular version:**
Angular CLI: 1.6.4
Node: 8.9.4
OS: darwin x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router
```
@angular/cli: 1.6.4
@angular-devkit/build-optimizer: 0.0.38
@angular-devkit/core: 0.0.25
@angular-devkit/schematics: 0.0.48
@ngtools/json-schema: 1.1.0
@schematics/angular: 0.1.13
@schematics/schematics: 0.0.13
typescript: 2.6.2
webpack: 3.10.0
```
* **PrimeNG version:** 
5.2.0-rc.2

**Comment by solael** [comment]
Any update to the issue? Such a pity that it doesn't work with Regex...

**Comment by cagataycivici** [comment]
No, keyFilter checks the current key, it is a common misunderstanding. You need to enable validation mode to enable whole value.
