### ISSUE TITLE
p-table filtering without Dynamic column

### ISSUE THREAD

**Issue by wilson-young** [primefaces/primeng#4951]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[x ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

is there any documentation about filtering without using dynamic column? i dont want to use dynamic column because i wish to put button, image, etc on each row or pipe for each cell data.

**Comment by tigrenok00** [comment]
+1
I tried using the following way, but it doesn't work (no results are found):
`<input pInputText type="text" (input)="dt.filter($event.target.value, userId, 'contains')"> `

**Comment by cagataycivici** [comment]
You can have dynamic columns + filtering using ngSwitch, actually static columns is easier. Not sure why it hasn't worked for you. Could be;

```xml
dt.filter($event.target.value, 'userId', 'contains')"
```
