### ISSUE TITLE
Fixed documentation example in PR #4953

### ISSUE THREAD

**Issue by kroeder** [primefaces/primeng#4954]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Documentation said to use `formGroup.get['formControlName']` instead of `formGroup.get('formControlName')`

**Expected behavior**
Show `formGroup.get('formControlName')`

**What is the motivation / use case for changing the behavior?**
PR Info said I have to open up an issue to the PR https://github.com/primefaces/primeng/pull/4953

**Comment by cagataycivici** [comment]
We've settled on myFormGroup.controls['cities']
