### ISSUE TITLE
TurboTable: Missing column header borders in FF/IE

### ISSUE THREAD

**Issue by ARandomDude** [primefaces/primeng#4956]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/YNPi0CMkzaQ1z0AVoaC3?p=preview

**Current behavior**
In FF/IE, there are no column header borders. In Chrome, everything looks good.

**Expected behavior**
There should be column header borders.

**Possible solution**
Set the background-color in the tr, not in the th. It could also be solved by making the th elements position: static -- but then, the column resizer dissappears into nirvana :)

* **Browser:** [ Firefox 58.0 | IE 11.786.15063.0 (Update version: 11.0.49)]

**Comment by cagataycivici** [comment]
Unable to replicate with 5.2.3.
