### ISSUE TITLE
p-button not available in ButtonModule

### ISSUE THREAD

**Issue by bniedermeyer** [primefaces/primeng#4959]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Repro Plunkr: http://plnkr.co/edit/nrjaF8rDAdAsD5Uvl88L?p=preview

**Current behavior**
Using the p-button component causes the following error:
```
zone.js:571 Error: Uncaught (in promise): Error: Template parse errors:
'p-button' is not a known element:
1. If 'p-button' is an Angular component, then verify that it is part of this module.
2. If 'p-button' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("


[ERROR ->]<p-button label="This is a button" (onClick)="onClick($event)"></p-button>
{{counter}}"): ng:///app/app.template.html@4:0
Error: Template parse errors:
'p-button' is not a known element:
1. If 'p-button' is an Angular component, then verify that it is part of this module.
2. If 'p-button' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
```
**Expected behavior**
[Per documentation](https://www.primefaces.org/primeng/#/button) the p-button component should be available for use within the `ButtonModule`. ` p-button` is not marked as a beta or upcoming feature so I would expect it to be available.

**Minimal reproduction of the problem with instructions**
(See above plunkr)
1. Import `ButtonModule` into AppModule
2. Add `<p-button label="This is a button" (onClick)="handleClick($event)"></p-button>` to `app.component.html`
3. Run App

**What is the motivation / use case for changing the behavior?**
Even though other directives like `pButton` are available for use - we would like to use native PrimeNG components as much as possible in our apps. If there are no plans for the use of  `p-button` references to it should be removed from documentation.

**Please tell us about your environment:**
- Windows 10

* **Angular version:** 
5.0.0
* **PrimeNG version:** 
5.0.2
* **Browser:**
All 
* **Language:** 
Typescript  2.4.2

* **Node (for AoT issues):** `node --version` =   8.8.0

**Comment by AndreaBarbasso** [comment]
Docs actually point to 5.2.0-RC2, and `p-button` isn't avilable in version 5.0.2.
#4854 really seems like a good issue, doesn't it? :)

**Comment by bniedermeyer** [comment]
@AndreaBarbasso ahh... ok that makes total sense now. Thanks for the heads up.  Yes #4854 sounds like a really good solution - it's weird that the featured docs are for something in RC when there are previous versions available to use. I'll go ahead and close for now. 

Do you know if documentation for 5.0.2 is available anywhere?

**Comment by AndreaBarbasso** [comment]
I think the only way to look at past docs is through file history on git... Not convenient at all.
