### ISSUE TITLE
[Feature Request] autocomplete "field" could be splitted in name/value

### ISSUE THREAD

**Issue by sdmoralesma** [primefaces/primeng#496]
According to documentation for autocomplete component:

> field - Field of a suggested object to resolve and display.

It would be great if we could use one parameter to display a name and other to resolve. A suggestion could be:

> fieldName - Field of a suggested object to display.
> fieldValue  - Field of a suggested object to resolve.

**Comment by cagataycivici** [comment]
Not sure, fieldValue is always the object itself which has everthing init. I'll reopen if more users request the same.

**Comment by spinettaro** [comment]
Hi, I agree with @sdmoralesma  because I would like to display something and resolve it with another value
