### ISSUE TITLE
Gantt chart

### ISSUE THREAD

**Issue by allarth** [primefaces/primeng#4960]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Expected behavior**
[https://code.daypilot.org/50224/angular-4-gantt-chart-quick-start-project](https://code.daypilot.org/50224/angular-4-gantt-chart-quick-start-project)

**What is the motivation / use case for changing the behavior?**
to develope software that manage activities of persons

**Comment by davisb10** [comment]
@allarth Just an FYI. Your link above does not work. Its a valid address, however when copy-pasted it does not go to that address.

**Comment by allarth** [comment]
sorry, now work

**Comment by Vbboi24** [comment]
+

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by kaplan-alvaromoron** [comment]
It doesn't seem like this has been implemented. Can someone reopen that issue?
