### ISSUE TITLE
dataTable virtualisation without lazy does not update scrollTable.top.y

### ISSUE THREAD

**Issue by Mysame** [primefaces/primeng#4964]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/m7x0OzvikVjrifzT8lGS?p=info

**Current behavior**
If you scroll down a dataTable with virtualisation but not with lazy, the content gets virtualised correctly but it's also out of view, becaue the scrollTable.top.y never gets changed, due to virtualScrollCallback never being called.

**Expected behavior**
Virtual content scrolls down with the user

**Minimal reproduction of the problem with instructions**
Scroll down just enough so you can see the last number in the plnkr change, indicating that the content has indeed been changed. However, you continue scrolling into total white.

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and not maintained anymore, please consider migrating to p-table.
