### ISSUE TITLE
Primeng KeyFilter not working well

### ISSUE THREAD

**Issue by tienvvpowergate** [primefaces/primeng#4968]
i am using KeyFilter Module of primeng here is my code :  

    `<input type="text" pInputText [(ngModel)]="price.TintCost" [pKeyFilter]="patternDecimal" name="tintCost" required="true" />`

here is my typescrip code :

    `patternDecimal: RegExp = /^[0-9]+(\.[0-9]{1,2})?$/;`

and here is version of primeng :|

    `"primeng": "^5.2.0-rc.1",`

i tested in regex then i can type dot(.) but when i apply to KeyFilter, it doesn't allow the dot(.). Someone help me, please

**Comment by david-lee** [comment]
I had the same problem and created an issue #4950. 
It doesn't test with whole input values but test with a last value you enter. That's why it doesn't work properly. I tried several ways and gave up. I ended up with my own directive.

**Comment by tienvvpowergate** [comment]
Thanh you David-lee, I guess so :(

**Comment by cagataycivici** [comment]
No, keyFilter checks the current key, it is a common misunderstanding. You need to enable validation mode to enable whole value.

You need to create a feature request to check against the whole value.

**Comment by fedeolto** [comment]
I see this post is 1 year old, but just wanted to point out that I had the same issue with KeyFilter and [Mask](https://www.primefaces.org/primeng/#/inputmask) worked well for me
