### ISSUE TITLE
Error on use filter with p-dropdown: Can't bind to 'options'

### ISSUE THREAD

**Issue by calebeaires** [primefaces/primeng#4969]
```
[*] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

options is not part of the p-dropdown component.

**Expected behavior**

I have imported all modules (    BrowserModule, FormsModule, ReactiveFormsModule ), but it gives this error

```

Can't bind to 'options' since it isn't a known property of 'p-dropdown'.
1. If 'p-dropdown' is an Angular component and it has 'options' input, then verify that it is part of this module.
2. If 'p-dropdown' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("vent.target.value, opt.field, 'contains')">
                    <p-dropdown *ngSwitchCase="'brand'" [ERROR ->][options]="brands" [style]="{'width':'100%'}" (onChange)="dt.filter($event.value, col.field, 'equals'"): ng:///SharedModule/TableViewWidgetComponent.html@34:56
'p-dropdown' is not a known element:
1. If 'p-dropdown' is an Angular component, then verify that it is part of this module.
2. If 'p-dropdown' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("xt type="text" (input)="dt.filter($event.target.value, opt.field, 'contains')">
                    [ERROR ->]<p-dropdown *ngSwitchCase="'brand'" [options]="brands" [style]="{'width':'100%'}" (onChange)="dt.filt"): ng:///SharedModule/TableViewWidgetComponent.html@34:20
```
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.0.X

* **PrimeNG version:** 5.2.0-rc.2

 
* **Language:** TypeScript ~2.5.3

* **Node (for AoT issues):** `node --version` =  v8.9.1

**Comment by mlangwell** [comment]
Hi @calebeaires I had a similar issue and it was due to the FormsModule. I see that you have imported it, but have you imported it into the module you are using the module in? Any feature module will need both DropdownModule and FormsModule imported to work.

**Comment by cagataycivici** [comment]
Not a PrimeNG issue.

**Comment by chirugampala** [comment]
@cagataycivici can you provide any solution for this error.

**Comment by chirugampala** [comment]
ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'selected' since it isn't a known property of 'p-dropdown'.
1. If 'p-dropdown' is an Angular component and it has 'selected' input, then verify that it is part of this module.
2. If 'p-dropdown' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
  optionLabel="label"
  (onChange)="onStockChange($event)"
  [ERROR ->][selected]="selectedStock"
></p-dropdown>

**Comment by chirugampala** [comment]
@cagataycivici please help me on this error.

**Comment by NayanaRavi94** [comment]
I have same error with p-dropdown . I have imported FormsModule and DropDownModule in app.module.ts file. But issue is still not resolved. Plese provide solution for this error
