### ISSUE TITLE
p-inputMask support for style text-transform:uppercase

### ISSUE THREAD

**Issue by bugreport0** [primefaces/primeng#4970]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/1PlS0PSgIeUqH0nu6TXf?p=preview

**Current behavior**

When using the text-transform inside a p-inputMask, it doesn't work. By the console looks that this feature is not supported.

**Expected behavior**

In case of mask with aaa for example together with style containing text-transform: uppercase the text should be displayed as AAA

**Minimal reproduction of the problem with instructions**

check the Plunker: http://plnkr.co/edit/1PlS0PSgIeUqH0nu6TXf?p=preview
when typing the first three letters should be in uppercase

**Please tell us about your environment:**

Angular5

* **PrimeNG version:** 2.0.X

PrimeNG 5.0.2.RC2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

* **Node (for AoT issues):** `node --version` =

**Comment by RogerioTeixeira** [comment]
try like this:
<p-inputMask mask="aaa-9999" id="vehicle" **[style]="{'text-transform': 'capitalize'}"**></p-inputMask>

**Comment by bugreport0** [comment]
It works this way, it's the normal behavior not work with the normal style?
