### ISSUE TITLE
[onChange] doesn't work for angular 5.2.0

### ISSUE THREAD

**Issue by RobinLu96** [primefaces/primeng#4974]
Angular version 5.2.0
onChange($event) doesn't work in my code. No matter how do I modify the typescript file(.ts) in my code, the (onChange) = "onChange($event)" seems doesn't work at all. The purpose for the code is select A first, then select B with the same value. From the console, it seems the onchage(event) will never been used after I selected something from my first dropdown.
`   
    <div class="ui-grid-col-3" >   
    <b>DROP DOWN TO SELECT A</b>
    <p-dropdown [options]="A" [(ngModel)]="selcetedA" [style]="{'width':'100%'}" filter = "true" (onChange)="onChange($event)">
	</p-dropdown>
	</div>
    <div class="ui-grid-col-3" >    
    <b>DROP DOWN TO SELECT B</b>
    <p-dropdown [options]="B" [(ngModel)]="selectedB" [style]="{'width':'100%'}" filter = "true" >
	</p-dropdown>
	</div>`

`constructor(private sssService: SssService,
          private router: Router ) {
           this.A = [          
            {label: 'Assembly N', value: 'AN'},
            {label: 'Assembly S', value: 'AS'},
            ];
            this.B = [
            {label: 'North ASSEMBLY SILO', value: "AN"},
            {label: 'SOUTH ASSEMBLY SILO', value: "AS"},
           // {label: 'SOUTH ASSEMBLY SILO', value: 'AS'},
            ];
          //  this.siloshow = this.silos;
         }
            onChange($event){
              if(event) {
           //I modify the code here
          }
        }`

**Comment by AndreaBarbasso** [comment]
Hi,
I suggest to look at some Angular tutorials, since there are a few errors and misconceptions in your code.
I fixed it a little, and you can see that everything works: [Plunkr](http://plnkr.co/edit/w3QNXWP0w1vcuRCdFOMi?p=preview).
I've been a CS student myself, so keep going on and don't stop on the surface of knowledge! :)

**Comment by RobinLu96** [comment]
@AndreaBarbasso But I still can't get the label string.....

**Comment by jrcayetano** [comment]
If you want get the label string you must set something like this:

`this.A = [ {label: 'Assembly N', value: {label: 'Assembly N, value: 'AN'} }]`

**Comment by cagataycivici** [comment]
Not a PrimeNG issue.
