### ISSUE TITLE
Drag and Drop doesn't work after update Angular version (to 5+)

### ISSUE THREAD

**Issue by leonardobrancalhao** [primefaces/primeng#4975]
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Please tell us about your environment:**
* **Angular version:** 5.2.0
* **PrimeNG version:** 5.0.2

After update to angular 5, drag and drop doesn't work anymore, and don't present any console errors.

**Comment by cagataycivici** [comment]
This is not a valid issue ticket, it misses a plunkr to demonstrate the issue. Please follow the issue guideline before creating new issues.

Live examples work by the way.
