### ISSUE TITLE
peerDependencies to primeui is not needed anymore

### ISSUE THREAD

**Issue by ova2** [primefaces/primeng#498]
Hi Cagatay,

You said, primeng doesn't require primeui anymore http://blog.primefaces.org/?p=3937 But package.json has a peerDependency to primeui https://github.com/primefaces/primeng/blob/master/package.json

NPM 3 shows a warning if you don't have primeui installed as dependency below node_modules. Can you remove peerDependencies from package.json please? Thanks.

**Comment by sdmoralesma** [comment]
The package that you are referring to is a wrapper for javascript AND css files, right now that dependency is necessary because primeng is using the _styling_ provided in the package.

Extracted from the installation guide:
```
<link rel="stylesheet" type="text/css" href="node_modules/primeui/themes/omega/theme.css" />
<link rel="stylesheet" type="text/css" href="YOUR_PATH/font-awesome.min.css" />
<link rel="stylesheet" type="text/css" href="node_modules/primeui/primeui-ng-all.min.css" />
```

**Comment by ova2** [comment]
Aha, thanks for clarification. But peerDependencies is for JS modules. AFAIK, you can not really have CSS modules. That means, we can delete peerDependencies without drawbacks. Maybe I have missunderstood you.

**Comment by sdmoralesma** [comment]
peerDependencies are Not JS exclusively, in fact, you can have in your npm-package any type of file that is needed. In this case primeui is providing javascript + css files, although primeng is not using anymore the JS files, the css styling is still necessary. peerDependencies is only saying: "hey I need this package installed before you can use me", no matter if it is or not a JS dependency.

You can see by yourself what is inside the package: https://github.com/primefaces/primeui-distribution , that's what npm will package and publish. This peerDependency can not be removed by now.

Hope to have solved your question :)

**Comment by ova2** [comment]
Ah ok, I overlooked this CSS dependency. Closed the issue.
