### ISSUE TITLE
InputTextarea does not resize initial value

### ISSUE THREAD

**Issue by irbian** [primefaces/primeng#4980]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/8bQOjvCYpjgMhTNgPTFD?p=preview

**Current behavior**
I don´t know if it would better two reports, but I´ll explain them here

- First issue, when first load, the textinputarea dont resize until clicked. As a workaround I have call the resize method on init
- Second issue, the height is calculated on the cols and character number, no on the width. That means that the height will be too long, or too short, depending on the current cols value. A different approach would be to calculate the height based on the width

* **PrimeNG version:** 5.0.2

* **Browser:** Chrome

**Comment by cagataycivici** [comment]
We'll check the #1 but #2 requires a rewrite and not sure if it is a vital problem on smaller screens anyway.

**Comment by cagataycivici** [comment]
Need more feedback on this, maybe users want to expand it on click. Maybe an attribute it needed to make it customizable.
