### ISSUE TITLE
Ultima css selectors broken with prime 5.2.0

### ISSUE THREAD

**Issue by mfrro** [primefaces/primeng#4983]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
The css class ui-menu-list doesn't exist anymore in prime 5.2.0. Because of this, the ultima css theme isn't applied correctly. Observed with theme-blue.css, Ultima Version 5.0.0.

**Expected behavior**
Menu items shouldn't have the default a-tag style.

**Minimal reproduction of the problem with instructions**
Implement a primeng menu with the ultimate theme.

* **Angular version:** 5.2.1

* **PrimeNG version:** 5.2.0-rc.2

* **Browser:** [all ]

**Comment by cagataycivici** [comment]
Please use Ultima forum not the PrimeNG issue tracker to report issues: Ultima does not support PrimeNG 5.2 yet and we've mentioned on release announcements that premium themes will have problems with menus and TurboTable so they will be updated when 5.2 comes out.
