### ISSUE TITLE
When is inputnumber coming out?

### ISSUE THREAD

**Issue by nmobregon** [primefaces/primeng#4984]
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
Hi, I read an answer written by @cagataycivici from [last July](https://github.com/primefaces/primeng/issues/1334) saying that currency mask would be implemented within the inputnumber component.

Are there any good news about this feature? We're really needing it.

Thanks in advance.

**Comment by cagataycivici** [comment]
Not in our immediate plans due to other tasks with higher priority, I don't have a date sorry.
