### ISSUE TITLE
Keyboard accessibility for MultiSelect Header Checkbox

### ISSUE THREAD

**Issue by skhattry** [primefaces/primeng#4985]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Tab doesn't stop at the select all checkbox in p-multiselect.

**Expected behavior**
Select all checkbox in p-multiselect should be reachable via keyboard

**What is the motivation / use case for changing the behavior?**
This will improve the control's accessibility

**Please tell us about your environment:**
* **Angular version:** 2.0.X
4.1.3

* **PrimeNG version:** 2.0.X
4.2.1

* **Browser:** 
Tested on Microsoft Edge and Mozilla Firefox

**Comment by leonliang33** [comment]
I am also blocked on this issue, is there plans for this fix soon?

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/issues/6025
