### ISSUE TITLE
Vertical PickList

### ISSUE THREAD

**Issue by jjayaraman** [primefaces/primeng#4987]
Is there any option to display Picklist component layout orientation vertically, instead of the default horizontal layout?

We want to choose and move the element's top to down, instead of left to right layout?

![capture](https://user-images.githubusercontent.com/3359193/35445580-f43f104e-02a9-11e8-9210-f36c4bdf3b88.PNG)

May thanks, your PrimeNG components are very helpful and nice.

**Comment by cagataycivici** [comment]
No, but we can use this issue to create a feature.

**Comment by jjayaraman** [comment]
Thanks for the clarification. Yes, that feature could be useful in some cases.

**Comment by slakshmikanthan** [comment]
is this feature implemented ?

**Comment by luanalbm** [comment]
You can do it on CSS, but I'm still trying to set the center buttons.

::ng-deep .p-picklist {
  flex-direction: column !important;
}

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by Emiliorth** [comment]
Any news here?
