### ISSUE TITLE
Localized control type is not appropriate and IsExpandCollapsePattern is false for p-dropdown and p-multiselect

### ISSUE THREAD

**Issue by skhattry** [primefaces/primeng#4988]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
Control type reported is group and IsExpandCollapsePattern is false

**Expected behavior**
Control type should be combo box and IsExpandCollapsePattern should be True

**Please tell us about your environment:**
Windows Inspect tool which is part of the Windows SDK was used to check these properties.

* **Angular version:** 2.0.X
4.1.3

* **PrimeNG version:** 2.0.X
4.2.1

* **Browser:**
Microsoft Edge

**Comment by cagataycivici** [comment]
Issue is not clear to me, please follow the issue ticket creation guide.
