### ISSUE TITLE
Name property for p-dropdown items is incorrect

### ISSUE THREAD

**Issue by skhattry** [primefaces/primeng#4989]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
Name property for items of p-dropdown are incorrect. If the items for the p-dropdown say are fruits like apple, mango and banana then the name property reported is appleapple, mangomango and bananabanana respectively.

**Expected behavior**
Name property should be proper

**What is the motivation / use case for changing the behavior?**
The narrator is ready out incorrectly since the name property is improper.

* **Angular version:** 2.0.X
4.1.3

* **PrimeNG version:** 2.0.X
4.2.1

* **Browser:** 
Microsoft Edge

**Comment by cagataycivici** [comment]
Issue is not clear, no plunkr is provided. Please follow the issue creating guideline. And always try with the latest PrimeNG.
