### ISSUE TITLE
TimeLine component

### ISSUE THREAD

**Issue by netstart** [primefaces/primeng#499]
Can I offer an ideia?

It's necessary (for me) a timeline component, vertical and horizontal.

**Comment by cagataycivici** [comment]
Like we have in PrimeFaces?

http://www.primefaces.org/showcase/ui/data/timeline.xhtml

**Comment by netstart** [comment]
The timeline from primefaces is interesting.

I like  this
   http://akveo.com/blur-admin-mint/#/components/timeline
from template
  https://github.com/akveo/blur-admin

**Comment by cagataycivici** [comment]
Added to roadmap, will reopen once we pick it up;

https://github.com/primefaces/primeng/wiki/Roadmap

**Comment by zinderud** [comment]
wait for timeline

**Comment by Priluka** [comment]
any news about timeline ?

**Comment by vignesh1689** [comment]
Eagerly wating for the PrimeNG Timeline component same like in PrimeFaces, any updates on release date?

**Comment by tonymporter** [comment]
timeline from primefaces, I'm interested too!

**Comment by dev-thinks** [comment]
Hello @cagataycivici, fyi, looks like roadmap got updated recently in favor of Prime10 and all these items are not in there in roadmap now. any updates?
