### ISSUE TITLE
IsselectionItemPattern is false for p-accordiontab

### ISSUE THREAD

**Issue by skhattry** [primefaces/primeng#4990]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
IsSelectionItemPattern is false for p-accordiontab

**Expected behavior**
IsSelectionItemPattern should be true for p-accordiontab

**What is the motivation / use case for changing the behavior?**
Narrator is not behaving correctly because of this.

**Please tell us about your environment:**
Windows Inspect tool which is part of the Windows SDK was used.

* **Angular version:** 2.0.X
4.1.3

* **PrimeNG version:** 2.0.X
4.2.1

* **Browser:** 
Microsoft Edge

**Comment by cagataycivici** [comment]
Issue is not clear to me, please read the issue guide.
