### ISSUE TITLE
filterMatchMode="contains" throws filter.toLowerCase is not a function error

### ISSUE THREAD

**Issue by mlangwell** [primefaces/primeng#4992]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/Q5hZgBA6DlXf55UvyVqw?p=preview

**Current behavior**

Since turbotable seems to be extremely buggy right now, our team has resorted to using datatable. I added filterMatchMode="contains" to one of my columns and it throws a filter.toLowerCase is not a function error when selecting from a multiselect dropdown or a regular dropdown. Very easily reproduced. 

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10

* **Angular version:** 2.0.X

5.2.0

* **PrimeNG version:** 2.0.X

5.2.0-rc.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and not maintained anymore, please consider migrating to p-table.
