### ISSUE TITLE
Charts not responsive inside a p-fieldset (but works inside a p-panel).

### ISSUE THREAD

**Issue by mikza** [primefaces/primeng#4998]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

Put a chart with the responsive option inside a p-fieldset. Try to resize the page. The chart won't resize at all.

**Expected behavior**

The chart should resize itself. It does work properly inside e.g a p-panel, but as soon as I change the p-panel to a p-fieldset I lose all responsiveness on my charts.

* **Angular version:** 5.0.X

* **PrimeNG version:** PrimeNG 5.0.2

* **Browser:** all

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a plunkr at;

http://plnkr.co/edit/qtZi5lB3DjkNt7Kdivg9?p=preview
