### ISSUE TITLE
ColorPicker Component

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#50]

**Comment by garethlewis** [comment]
Is there any update on when we can expect to get this component?  I'm currently using the angular2-color-picker from https://github.com/Alberplz/angular2-color-picker which doesn't work with Angular 2.0.1 onwards.

**Comment by cagataycivici** [comment]
Issue tracker cleanup, moved to roadmap. Will reopen when it is picked up from our todo list.

https://github.com/primefaces/primeng/wiki/Roadmap

**Comment by cagataycivici** [comment]
Available in 4.1.
<img width="245" alt="screen shot 2017-06-03 at 12 49 29" src="https://cloud.githubusercontent.com/assets/686247/26752792/8edd9e22-4860-11e7-9138-597d553a27a7.png">
