### ISSUE TITLE
does primeng and the backended ui components are licensed under Apache 2.0?

### ISSUE THREAD

**Issue by redhatlinux10** [primefaces/primeng#500]
for example, [igniteui-angular2](https://www.npmjs.com/package/igniteui-angular2) is licensed under MIT, but the backended [igniteui](http://www.igniteui.com/) is licensed under a commecial license, this makes igniteui-angular2 not suitable for my needs .
does primeng like this?

**Comment by cagataycivici** [comment]
We don't have any backend components and css part of PrimeNG uses PrimeUI, everything is under apache except the premium layouts and themes like rio, modena which are totally optional. Our business model is based on commercial support called PrimeNG PRO and the premium layouts and themes so no need to worry about license :)
