### ISSUE TITLE
Table - onEditComplete should be also called on blur

### ISSUE THREAD

**Issue by amitsol** [primefaces/primeng#5003]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Current onEditComplete is only getting called if user press enter key.

**Expected behavior**
If by any means user completes the editing this event should be fired. On blur of the element can be a good event to fire onEditComplete. Current if I enter some value in editable field and if I dont press the enter key, this event is not getting fired.

**Please tell us about your environment:**
Windows

* **Angular version:** 2.0.X
Angular 5
PrimeNG 5.2.0-rc.2

**Comment by cagataycivici** [comment]
Since you have full control over the editor template, you can decide to call complete on blur. We rather not do it, as there may have multiple editors inside a single cell where calling complete on blur may not be desired behavior for some users.

**Comment by kapiladiyecha** [comment]
Thanks @cagataycivici  for the information.
However, it is lake of documentation, people expecting `onEditComplete` would be trigger once edit completed.

See below docs image for the reference.

![image](https://user-images.githubusercontent.com/6995248/37649025-9c2d5096-2c6b-11e8-9f86-a9d32b0ecf37.png)

![image](https://user-images.githubusercontent.com/6995248/37649009-8ee01fe0-2c6b-11e8-9f0e-068e79865fab.png)

Thanks
