### ISSUE TITLE
Feature - Horizontal scroll synchronisation 

### ISSUE THREAD

**Issue by rafa-as** [primefaces/primeng#5008]
**I'm submitting a ...**
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Expected behavior**
Add the possibility to synchronise the horizontal scroll between two or more tables.

**What is the motivation / use case for changing the behavior?**
Sometimes its necessary to use two separate tables with the same columns but one of them doesn't have header because are the same that the first table. At this point, if the table has horizontal scroll the synchronisation is mandatory to maintain the columns aligned.

I have almost all the work completed to do the pull request, but I want to know if this feature is welcome on PrimeNG @cagataycivici

**Comment by jgildebernabe** [comment]
Will be nice to have this implemented 👍

**Comment by cagataycivici** [comment]
If more users demand it, we'll consider this.

**Comment by rafa-as** [comment]
If you want I can do the PR and you can review it.

** Sorry for close and re-open

**Comment by SaraMorera** [comment]
Cool! that feature would solve one of the issues we have in our admin

**Comment by felipebri23** [comment]
I have the same problem

**Comment by rafa-as** [comment]
@cagataycivici what do you think about this? you want the PR ?

**Comment by rafa-as** [comment]
@cagataycivici you have some idea if this feature will be implemented?

**Comment by rafa-as** [comment]
@cagataycivici you want a PR?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
