### ISSUE TITLE
Calendar - Complete implementation of OnChanges / Input() setters

### ISSUE THREAD

**Issue by Mysame** [primefaces/primeng#5009]
**I'm submitting a ...**  (check one with "x")
```
[ x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
```

Calendar unfinished setters / onChanges implementation:
- dateFormat
- hourFormat
- icon

Completed:
- minDate
- maxDate
- disabledDates
- disabledDays
- showTime
- locale

calling initTime() in ngOnChanges will pretty much solve the important ones (dateFormat, hourFormat). 
As of now you need to select a new date to see any changes.

**Comment by cagataycivici** [comment]
We'll reconsider if more users demand it. Not sure if it is a common case to change the format or icon during runtime.
