### ISSUE TITLE
Datatable runtime grouping

### ISSUE THREAD

**Issue by luking4** [primefaces/primeng#501]
Hi,
Data table is really one of the best Angular2 grid available in the market but 
grouping functionality displayed in demo at,
http://www.primefaces.org/primeng/#/datatablegroup
looks to be design time where you have to specify columns to be grouped while coding.

I am expecting grouping columns by user (Drag and Group) while application is running in browser.

For example,
http://ui-grid.info/docs/#/tutorial/209_grouping

![primeng_grid_grouping](https://cloud.githubusercontent.com/assets/19908616/16218592/18aa7b0a-379d-11e6-8a1d-68ce2f6d380d.JPG)

Is it possible to achieve? If so, could you show snippet of it?

**Comment by tactic-albam** [comment]
I'd like it

**Comment by BartoszBaczek** [comment]
It is something, that we would definitely need in our app. Is there any roadmap on this feature?

**Comment by cagataycivici** [comment]
I don't understand the requirement.

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
