### ISSUE TITLE
Custom filter for formatted date columns

### ISSUE THREAD

**Issue by fplini** [primefaces/primeng#5010]
Hi all, 
In my table I have many date columns. The field value is a number (timestamp) and I format the value with a DatePipe. When I want to filter a date for ex. '29/01/2018' it not works because it compare the string with a long.

Is there a way to do this or is it a possible feature?

**Comment by cagataycivici** [comment]
Please use forum for questions not the issue tracker.

**Comment by fplini** [comment]
It was a feature request not an issue tracker
