### ISSUE TITLE
TurboTable can't use resize and scroll together

### ISSUE THREAD

**Issue by aunkang** [primefaces/primeng#5011]
I try to add [resizableColumns]="true" and pResizableColumn with 
[scrollable]="true" scrollHeight="200px" but when i resize column only th of table that resize.
![column-bug](https://user-images.githubusercontent.com/21077653/35508480-16221d48-0523-11e8-9f57-62e36fea7ab8.jpg)

**Comment by cagataycivici** [comment]
This is not a valid issue ticket, it misses a plunkr to demonstrate the issue. Please follow the issue guideline before creating new issues.

**Comment by winarg** [comment]
I've seen this error and can be reproduced in the following link
https://angular-9lvke9.stackblitz.io

**Comment by cagataycivici** [comment]
A colgroup is required to support resize + scroll.

**Comment by aunkang** [comment]
thanks

**Comment by shaikhspear16** [comment]
You mean Add Colspan?
Can you please tell me exactly what needs to be done to have column resize and scroll work. I have a demo here:
https://stackblitz.com/edit/github-tatj4e-zimyuu

**Comment by winarg** [comment]
Example based on stackblitz

<h3 class="first">Vertical</h3>
<p-table [columns]="cols" [value]="cars1" [scrollable]="true" scrollHeight="200px"  [resizableColumns]="true">
    <ng-template pTemplate="colgroup"
                     let-tableColumns>
                     <colgroup>
                     <col *ngFor="let col of tableColumns"
                 >
                     </colgroup>
    </ng-template>
    <ng-template pTemplate="header" let-columns>
        <tr>
            <th *ngFor="let col of columns" pResizableColumn>
                {{col.header}}
            </th>
        </tr>
    </ng-template>
    <ng-template pTemplate="body" let-rowData let-columns="columns">
        <tr>
            <td *ngFor="let col of columns"  class="ui-resizable-column">
                {{rowData[col.field]}}
            </td>
        </tr>
    </ng-template>
</p-table>
