### ISSUE TITLE
TurboTable: sortField+sortOrder with lazy loading triggers onLazyLoad callback three times on init

### ISSUE THREAD

**Issue by akaufmann** [primefaces/primeng#5012]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/tN8Y1XU3LfAplXsVdx06?p=preview

**Current behavior**
The `onLazyLoad` callback is triggered three times on init when you use the sortField and sortOrder properties.

**Expected behavior**
The `onLazyLoad` callback is triggered only once on init after the sortField and sortOrder properties have been set.

**Minimal reproduction of the problem with instructions**
See Plunkr.

* **Angular version:** 5.2.1

* **PrimeNG version:** 5.2.0-rc.2

* **Browser:** all

**Comment by banderberg** [comment]
This is not entirely fixed.  Turbotable with lazy load enabled fires the onLazyLoad event twice, once from onClick, and then again from the sortOrder setter.
