### ISSUE TITLE
Turbo-table edit column with p-dropdown doesn't revert to output mode when loosing focus

### ISSUE THREAD

**Issue by tigrenok00** [primefaces/primeng#5015]
Hi,
I have a <p-cellEditor> with a p-dropdown inside for an input template and a span for an output table. When I select value in the dropdown, the input template stays in place even after the dropdown looses focus. The only ways to revert to output mode are Enter/ESC or entering edit mode in another cell.
How can I stop the cell with the dropdown from staying in edit mode after dropdown got blur?

Thanks

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
* **Angular version:** 5
* **PrimeNG version:** 5.2.0-RC2

**Comment by cagataycivici** [comment]
Sorry but this can't be supported, we've worked on this before, there are various technical limitations.

**Comment by satvik1986** [comment]
is it possible to edit columns in turbotable using buttons inline ?
