### ISSUE TITLE
TurboTable p-template body let-* alias for rowData not working

### ISSUE THREAD

**Issue by jmmygoggle** [primefaces/primeng#5016]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/2Ojza3oQvg10LrnGlQdq?p=preview

[plunk-2Ojza3oQvg10LrnGlQdq.zip](https://github.com/primefaces/primeng/files/1675306/plunk-2Ojza3oQvg10LrnGlQdq.zip)

**Current behavior**
Unable to create an arbitrary context property/alias using `let-<alias>` syntax for PrimeNG (Turbo)Table `rowData` value within `ng-template` with `pTemplate="body"`.

**Expected behavior**
Deprecated PrimeNG DataTable allows `let-myAlias="rowData"` to create `myAlias` reference for the `rowData` value for use within the table widget markup, but specifically in `ng-template` elements where this `let-<alias>` attribute is assigned.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/2Ojza3oQvg10LrnGlQdq?p=preview
* The `app.template.html` displays broken TurboTable and functional DataTable when attempting to make a `let-<alias>` w/ `rowData`.
* The `app.template.html` file also has a commented section that displays a working TurboTable example that uses `let-rowData` and does not attempt to make an alias.

**What is the motivation / use case for changing the behavior?**
Fixing this would provide prior expected behavior from original DataTable which continues to work in  other `let-<alias>` behavior such as `rowIndex`.

**Please tell us about your environment:**

macOS and Debian, Intellij IDEA, NPM, webpack-dev-server and Apache

* **Angular version:** 5.2.x (5.2.2, 5.2.0 and 5.0.0 tested)

* **PrimeNG version:** 5.2.0-rc.2

* **Browser:** [Chrome Version 63.0.3239.84 (Official Build) (64-bit) | Chrome Version 62.0.3202.94 (Official Build) (64-bit)]
 
* **Language:** TypeScript 2.x (2.0.3 and 2.4.2 tested)

* **Node (for AoT issues):** `node --version` = v8.9.4

**Comment by cagataycivici** [comment]
`let-data="$implicit"`
