### ISSUE TITLE
TurboTable - Resize Column doesn't resize body, only header is resized

### ISSUE THREAD

**Issue by amitsol** [primefaces/primeng#5017]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

https://plnkr.co/edit/3g9WutUvZoDTH6m4LuLi?p=preview

**Current behavior**
If the table is scroll-able (horizontal and vertical) and all columns are re-sizable when user re-sizes the column only header is getting resized & body column's width remains unchanged.

**Expected behavior**
When user re-size the columns, header, body and footer part of the column should resize.

**Please tell us about your environment:**
Windows-7
Angular 5.0.5
PrimeNg 5.2.0-rc.2

**Comment by fplini** [comment]
I confirm. I also have the same problems [Screen](https://s17.postimg.org/8y282tbin/2018-01-31_12_03_13-_EASY.png)

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/issues/5032
