### ISSUE TITLE
Primeng components are not working with bootstrap grid system.

### ISSUE THREAD

**Issue by bugreport0** [primefaces/primeng#5019]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/wvZ9R0Kulu2QTFmbxBYe?p=preview

**Current behavior**

when using bootstrap grid system and primeng (with form-control class), the components are not fitting as normals html5 components.

**Expected behavior**

we expect that the primeng components behave like any other html5 ones.

**Minimal reproduction of the problem with instructions**

Check http://plnkr.co/edit/wvZ9R0Kulu2QTFmbxBYe?p=preview
As you can see under the primeng components (here the fields are Arrival Date, and Mask Case), the size of the component doesn't fit in the external area, like any other html 5 component.

**What is the motivation / use case for changing the behavior?**

Use primeng with bootstrap grid system

**Please tell us about your environment:**

* **Angular version:** 2.0.X

5.2.2
* **PrimeNG version:** 2.0.X

5.2.0-RC2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
You need to use ui-fluid.

**Comment by bugreport0** [comment]
thank you Cagatay, I updated the plunker with your proposed solution, it works perfectly:
http://plnkr.co/edit/wvZ9R0Kulu2QTFmbxBYe?p=preview
