### ISSUE TITLE
Table completely fails with large dataset

### ISSUE THREAD

**Issue by Ketec** [primefaces/primeng#5020]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[x ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
A very basic table  (the toggle example from docs) fails when a large (22k entries) data array is bound to the table.  
The release notes said it can do 5000 in 0.5s - yet it can't do 20k+. I'm forced to close the chrome process, because the whole page freezes.

Measuring time it takes ~25s for 5000 rows. There is no templating, no listeners etc in place - just vanilla basic table.

There are only 10 columns.

CPU usage hits up to 30% on a i5.

Trying to select anything (to copy text) has a noticeable, almost 1s delay and cpu usage goes up noticeably (+10 to 15%).

**Comment by cagataycivici** [comment]
It is not a good engineering practice to load 22k to your user's browsers. You should really use **lazy** loading for 22k entries as result will be the same when you use a simple ngFor instead of p-table.

**Comment by Ketec** [comment]
There is still a noticeable delay even at smaller amounts - a few thousand
can take 10-s of seconds.
