### ISSUE TITLE
Paginator does not appear in DataList in 5.2.0-RC2

### ISSUE THREAD

**Issue by PaulWoods4422** [primefaces/primeng#5021]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/C3ED9qRcMZpxao09pwVK?p=preview

**Current behavior**
Paginator does not appear in DataList in 5.2.0-RC2

**Expected behavior**
Paginator appeared in 5.0.2

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/C3ED9qRcMZpxao09pwVK?p=preview

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows / VS Code.

* **Angular version:** 2.0.X
5.0.2

* **PrimeNG version:** 2.0.X
5.2.0-RC.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Firefox
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS 2.5
* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
[paginatorPosition]="'both'"

or

paginatorPosition="'both'"
