### ISSUE TITLE
If initial totalRecords is empty, table has no height

### ISSUE THREAD

**Issue by Ketec** [primefaces/primeng#5022]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Took me a while to notice - but if the initial totalRecords is null/empty, the table body has 0 height.
Updating it after init has no effect.

**Expected behavior**
totalRecords should be able to be set after init - in a subscription for or @Input().

**Comment by cagataycivici** [comment]
Is this for VirtualScrolling on p-table?

**Comment by Ketec** [comment]
Yes for the virtual scroll - not sure if anything else even uses it?

**Comment by cguerrero-73** [comment]
I have the same problem, the totalRecords property is not refresh after the grid is initialized or when execute a lazy load event to load data.

**Comment by felipebri23** [comment]
I have the same problem

**Comment by karloscode** [comment]
Any upgrades to fix this issue? 
We have the same problem.

**Comment by bbuehrer** [comment]
I have the same problem. 

When should this be solved?

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/issues/5303
