### ISSUE TITLE
tabble lazyload "smart" buffer/earlier event.

### ISSUE THREAD

**Issue by Ketec** [primefaces/primeng#5024]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Currently triggering lazy load starts too late, allowing user to get stuck on "blank" grid view.

**Expected behavior**
Allow smarter lazy load that loads new rows before empty ones come into view.

**Comment by cagataycivici** [comment]
This is not a valid issue ticket, it misses a plunkr to demonstrate the issue. Please follow the issue guideline before creating new issues.

**Comment by Ketec** [comment]
Demonstrate a feature request in a plunkr? Even the demo on the page for virtual scroll has the same issue.  
But doesn't matter. Moved to a ag-grid instead.
