### ISSUE TITLE
Calendar Bug: Calendar closes on clicking on a greyed out date

### ISSUE THREAD

**Issue by AnthonyRyanAtherton** [primefaces/primeng#5025]
Hello, not sure if this is a bug or not but wanted to be sure.

[ x] bug report =>

**Current behavior**
The option to see days from other months is on and when the user selects a grey date from the other months the calendar  closes. For instance, you are looking at the month of January and you click the first date in the calendar which is the 31st of December then the calendar closes.

**Expected behavior**
When a date from another month, that is grey, the calendar should remain open.

* **Angular version:** 4.3.6

* **PrimeNG version:** 4.3.0

Chrome

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a plunkr at;

http://plnkr.co/edit/qtZi5lB3DjkNt7Kdivg9?p=preview
