### ISSUE TITLE
Label overlapping the input

### ISSUE THREAD

**Issue by Sandesh-Solabannavar** [primefaces/primeng#5028]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/Q5hZgBA6DlXf55UvyVqw?p=preview

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.0.0

* **PrimeNG version:** latest

* **Browser:** Chrome 63

I'm facing this issue, i'm doing model binding for the input fields in ngOnInit method.
The label and text are coming overlapped.

![image](https://user-images.githubusercontent.com/23529429/35605445-bddfd4de-066e-11e8-8a75-6c647f36ad88.png)

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a plunkr at;

http://plnkr.co/edit/qtZi5lB3DjkNt7Kdivg9?p=preview
