### ISSUE TITLE
Disabled accordion tabs are not compliant with high contrast standards

### ISSUE THREAD

**Issue by skhattry** [primefaces/primeng#5029]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Disabled accordion tab items text is appearing as yellow in black theme and grey in white theme.

**Expected behavior**
Disabled accordion tab items text should be in compliance with High contrast standards.
Disabled accordion tab items text should be in green color in black theme and brown color in white theme.

**Minimal reproduction of the problem with instructions**
Create an accordion and view the disabled tabs in high contrast theme

**What is the motivation / use case for changing the behavior?**
Users using high contrast themes would be affected.

* **Angular version:** 2.0.X
4.2.1

* **PrimeNG version:** 2.0.X
4.1.3

* **Browser:** 
Firefox
Firefox version: 56.0b8

**Comment by cagataycivici** [comment]
This depends on the theme you use where you can customize this behavior.
