### ISSUE TITLE
Layout issue with vertical scroll 

### ISSUE THREAD

**Issue by fplini** [primefaces/primeng#5031]
It seems to be an issue when I have a p-table with scrollable=true and for example scrollHeight=300px.
If I have only few records (ex. 3 records) and the v-scroll isn't needed, the width of header and body columns aren't the same.

this is a screen with scrollable true and scrollHeight, as you can see the headers and columns aren't aligned 
[Scroll](https://s17.postimg.org/mdp8s0jxr/scroll.png)

And here a screen without scroll
[No scroll](https://s17.postimg.org/6s7x7w07z/scroll.png)

**Comment by fplini** [comment]
Update: I noticed that the issue come out when I also have few columns. If I duplicate the columns I don't have the issue.

**Comment by cagataycivici** [comment]
Provide a plunkr please for your issues to be reviewed.

**Comment by fplini** [comment]
https://plnkr.co/edit/wSfi6wWVo1lk6FZsJqgh?p=preview

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/issues/5032
