### ISSUE TITLE
Better resize support for Scrollable Tables

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#5032]
Improve resize implementation by utilizing colgroups. Add examples to showcase with cases like;

scroll + resize fit
scroll + resize expand
scroll + variable widths + resize

**Comment by mickeyjohn** [comment]
The workaround works for me is always showing the vertical scrollbar to void unaligned header and body is: 
```
body .ui-table-scrollable-body {
    overflow-y: scroll;
}
```
Hope this to be improved very soon. Thanks.
