### ISSUE TITLE
SplitButton: On Firefox arrow is shifted vertically

### ISSUE THREAD

**Issue by Venthe** [primefaces/primeng#5034]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://www.primefaces.org/primeng/#/splitbutton

**Current behavior**
![image](https://user-images.githubusercontent.com/1686874/35627208-822aec56-0698-11e8-92c6-1798a5156934.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/1686874/35627239-97539254-0698-11e8-90e6-27c61732a0ba.png)

**Minimal reproduction of the problem with instructions**
Open PrimeNG demo site with **firefox**

**What is the motivation / use case for changing the behavior?**
:)

**Comment by 007304wz** [comment]
same problem in IE/Edge

**Comment by mertsincan** [comment]
Could you please try the following CSS for this issue?

```
.ui-splitbutton-menubutton.ui-button-icon-only .ui-button-text {
   overflow: visible;
}
```

**Comment by fperezgaliana** [comment]
Using this CSS makes the split buttons look fine. Tested on Firefox, Chrome and Opera.

**Comment by cagataycivici** [comment]
Fixed at;

https://github.com/primefaces/primeng/issues/5215
