### ISSUE TITLE
p-table with onRowClick

### ISSUE THREAD

**Issue by Galiza** [primefaces/primeng#5036]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

Here we have a plunkr of the issue:
**http://plnkr.co/edit/6AYjmQ?p=preview**

**Current behavior**
When using the p-table and using the "(onRowClick)", and you click at the row, nothing happens.

**Expected behavior**
WHen using the p-table and using the "(onRowClick)", the row should emit the event.

**Minimal reproduction of the problem with instructions**
Example showed at the plunkr link.

* **PrimeNG version:** 5.2.0-rc.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 

After analyzing the code and the issue, I was able to find a workaround of the problem. When you place the Directive: [pSelectableRow] at the tag <tr>, the onRowClick will work.
The documentation does not says that you need the Directive when using the method onRowClick for it to work.

**Comment by cagataycivici** [comment]
See #5037

**Comment by Galiza** [comment]
@wz2b Yeah, I found that out by looking inside PrimeNG code and some stuff wasn't really making any sense, that's how I figured it out.
But I wish I had the time to go back to it and make this change. We had to go with what they recommended at the other issue.
Thanks for showing me another solution to this issue, I will now know what to do next time I need to use it.
