### ISSUE TITLE
Lazy Datatable: Debouncing LazyLoadEvent ?

### ISSUE THREAD

**Issue by TheParad0X** [primefaces/primeng#5039]
For lazy datatables, every keystroke in a filter triggers a LazyLoadEvent. Is there a way to debounce this feature ? Something along the lines of an optional parameter for milliseconds to wait before firing the event.

Cheers

**Comment by cagataycivici** [comment]
If you are referring to p-table, you have full control over the filter elements so you can apply debounce on keystroke.
