### ISSUE TITLE
Row reordering with DragDrop for TurboTable

### ISSUE THREAD

**Issue by luking4** [primefaces/primeng#504]
Hi,
One of the important functionality of datatable could be dragging and dropping rows within table.

Even though draggable and dropable component is available and example shows how to drag and drop from outside into datatable as below,

http://www.primefaces.org/primeng/#/dragdrop

There is no example or feature telling about dragging and reordering row within datatable like below example.

http://blog.primefaces.org/?p=3026
http://www.guriddo.net/demo/guriddojs/integrations/drag_drop_rows/index.html

Is it possible? if so, could you please provide code for it?

**Comment by reach4thelasers** [comment]
I would love to see this feature also

**Comment by zibeeze** [comment]
+1

**Comment by skdhir** [comment]
+1

**Comment by rklempert** [comment]
We need this functionality as well. We are currently combining ng2-dnd with p-datatable. However, it doesn't work as nice because as you drag [value] keeps getting updated nonstop and all the rows flicker back and forth. The only way to control it is to specify [rowTrackBy] function to be () => {}. This was present in 1.1.1, but was removed in 1.1.3.

**Comment by akj123** [comment]
+1

**Comment by cyberrranger** [comment]
+1

**Comment by phoenixchinar** [comment]
+1

**Comment by taivu** [comment]
would beer someone to add this.

**Comment by gabrielalack** [comment]
+1

**Comment by vatsalpande** [comment]
+1

**Comment by a-kolybelnikov** [comment]
+1
any update on this request? maybe an estimated release date? need it badly.

**Comment by mgudesblatart** [comment]
+1

**Comment by guntram** [comment]
@taivu how much beer?? :beers:

**Comment by domantasjurkus** [comment]
+1

**Comment by GuzzoLM** [comment]
My issue was similar, I had to drag a row from table A and drop into a row of table B.
Managed to do this with ng-template, but it would be really nice to see  an out-of-the-box funcionality doing this.

**Comment by jrotondo-madaket** [comment]
Upvoted. Need this.

**Comment by israelkozitz** [comment]
+1

**Comment by arwindgao** [comment]
+1

**Comment by akolybelnikov** [comment]
I needed user to be able to reorder rows in the datatable by dragging. I have implemented it with ng2-dragula directive:
https://alligator.io/angular/drag-drop-ng2-dragula/
It has worked out-of-the-box and even the transition graphics are looking fine. Perhaps this can help somone out.

**Comment by arwindgao** [comment]
@akolybelnikov  hi, ur post is really helpful for simple html tag, but i want to know if i can integrate the dragular into primeng's data-table component, just like this post(https://github.com/primefaces/primeng/issues/2209), would you like to help on this, thanks advance.

**Comment by arwindgao** [comment]
It's works!!! Thanks!!! @akolybelnikov

**Comment by lasimone** [comment]
+1

**Comment by jrotondo-madaket** [comment]
Thanks so much @akolybelnikov! Your Plunker is genius!

**Comment by jrotondo-madaket** [comment]
One quick note about @akolybelnikov's plunker, after I implemented the solution, my app failed it's aot build. The "bag" declared in the primeNG table doesn't have a value within the typescript file, and Angular didn't like that.

For me, the solution was just to not pass the bag into primeDragula. It doesn't seem to need it:
`<p-dataTable [value]="rows" [tableStyle]="{ 'table-layout': 'auto' }" 
       primeDragula 
       [dragulaModel]="rows" 
       [dragulaOptions]="{ childContainerSelector: 'tbody', initAfterView: true }"
      #datatable>`

I hope that helps someone.

**Comment by jdashcode** [comment]
+1

**Comment by thegodfather904** [comment]
+1

**Comment by healydwya** [comment]
+1

**Comment by andregodasi** [comment]
+1

**Comment by tburger** [comment]
+1

**Comment by rich4756** [comment]
+1

**Comment by Guttz** [comment]
+1

**Comment by cagataycivici** [comment]
We'll try this for new TurboTable targeting 5.2.0-RC2

**Comment by cagataycivici** [comment]
Moved to RC3 as we need to release RC2 asap.

**Comment by cagataycivici** [comment]
Checkmate!

![reorder](https://user-images.githubusercontent.com/686247/36909683-c6666c00-1e4f-11e8-88c2-648b5ef2f449.gif)

**Comment by jdashcode** [comment]
Niiiiiiice

**Comment by alexwiese** [comment]
For those who are interested you can make the entire row draggable (not just the handle) by applying the handle directive to the actual cell.

          <td *ngFor="let col of columns" pReorderableRowHandle>
            {{rowData[col.field]}}
          </td>

**Comment by shorstki** [comment]
Any hook for handling reorder like onDragEnd? Can't find anything in the docs
