### ISSUE TITLE
Multiple filters on a field in TurboTable

### ISSUE THREAD

**Issue by sebaiona** [primefaces/primeng#5040]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

When you filter a field and then you want to add another filter to this same field, it replaces the previous one.

**Expected behavior**

The possibility to set two filters on a same field. 
For example I'd want to set `gt` a value and `lt` another value on a date field.

**Comment by diegoflores** [comment]
any update on this?

**Comment by alpernakin** [comment]
up?

**Comment by alpernakin** [comment]
I sorted the problem on this pull request: https://github.com/primefaces/primeng/pull/5976

**Comment by matt14m** [comment]
Need this as well. For filtering on a time range.

**Comment by ElliotSchmelliot** [comment]
@matt14m Check out [this SO post](https://stackoverflow.com/questions/50098545/primeng-datatable-date-range-filter) on achieving date range filtering using this control. Worked great for me, although I do agree that being able to add multiple filters more directly would be a plus.

**Comment by fwin02208** [comment]
any update for this?

**Comment by yigitfindikli** [comment]
You can use our new [p-columnFilter](https://primefaces.org/primeng/showcase/#/table/filter) for this.
