### ISSUE TITLE
TurboTable: misaligned columns when scrollable and checkbox

### ISSUE THREAD

**Issue by awallat** [primefaces/primeng#5041]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/0iHVlfZkxzg98lnlMlph?p=preview

**Current behavior**
When I use a turbo table with checkbox selection the table looks fine. But when I activate scrolling, then the columns of the body are misaligned.

**Expected behavior**
The columns should be correctly aligned with the table header.

**Minimal reproduction of the problem with instructions**
See plunkr.

* **Angular version:** 2.0.X
Angular 5.x

* **PrimeNG version:** 2.0.X
5.2.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome

**Comment by n-gottschalt** [comment]
I have found the same issues. Without the scrollable attribute, the table resizes with no issues. With, it misaligned the headers and resizing causes data overlapping.

**Comment by bmhumadi** [comment]
I get an issue when styling the scrollbar to have less width, the header no longer aligns with the columns. Please fix! or let us know how to?

**Comment by JacobSiegle** [comment]
You explicitly put the header column to have a width of -
<th style="width: 2.25em">

Apply the same to the body - 
<td style="width: 2.25em">
        <p-tableCheckbox [value]="rowData"></p-tableCheckbox>
</td>

Looks like a glitch in the turbo table docs that needs to be fixed, but is working as intended.

**Comment by awallat** [comment]
@JacobSiegle Thanks for the information. With that the table is correctly displayed.
However I still wonder if the documentation is wrong or if there's a bug in the table, since I do not have to add the width to the body for non-scrollable tables.

**Comment by cagataycivici** [comment]
Have you checked the scroll+resize example;

https://www.primefaces.org/primeng/#/table/colresize

**Comment by cagataycivici** [comment]
If you have custom width at headers, then you need to add the same to the body as well. We sure can add this to the docs. Easiest way is using a colgroup template though since it will be moved to header and body divs, so widths can be managed from a single element instead of two here. Image you have a footer, that makes it 3.
