### ISSUE TITLE
Atribute visible from MenuItem is not work in SplitButton

### ISSUE THREAD

**Issue by netstart** [primefaces/primeng#5042]
```
[ x ] bug report

```

**What is the motivation / use case for changing the behavior?**
Atribute visible from MenuItem is not work in SplitButton

**Please tell us about your environment:**
Windows 10
IDE: Webstorm

* **Angular version:** 5.2.1
* **PrimeNG version:** 5.2.0

* **Browser:**
Versão 63.0.3239.132 (Versão oficial) 64 bits
 
* **Language:** 
    "typescript": "~2.6.1"
    "target": "es5",

* **Node (for AoT issues):** 
v9.2.1

**Comment by skormel** [comment]
I updated primeng from 5.0.2 to 5.2.0 and visible property from menuitem of all the contextmenu stop working (always it's shown). I revert to 5.0.2 and start working again.
