### ISSUE TITLE
Add spinner / loading image into dropdown and multiselect component

### ISSUE THREAD

**Issue by carloshn90** [primefaces/primeng#5052]
Do you take into consideration the opportunity to add a spinner when we are using the components for asynchronous requests?

```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Comment by caitlinrouille** [comment]
This would be really helpful as well.

**Comment by skorunka** [comment]
Very welcomed feature!

**Comment by chandankgithub** [comment]
Ideally, this should have been placed before. 

> We can do this if there is more demand for sure.

I think this is basic need. This should have been from before. Anyways I am upvoting for the same :)

**Comment by PicOLinO** [comment]
Upvote

**Comment by DorWeid** [comment]
Any news regarding this issue ?

**Comment by jermylucas** [comment]
+1

**Comment by harpreetjohal** [comment]
+1

**Comment by Medmj** [comment]
+1

**Comment by Karim-Oodrive** [comment]
+ 1  How can  you forget to develop loading !!!!!!!!

**Comment by ppaulis** [comment]
+1

**Comment by thanhbinh710** [comment]
+1

**Comment by leopardy** [comment]
Did this ever go anywhere? This is still much needed/wanted.

**Comment by sechouaya** [comment]
Any news regarding this request .

**Comment by JudithMMolina** [comment]
I think there should be spinners in all form related components

**Comment by rene-guerrero** [comment]
It will help a lot

**Comment by Th14go** [comment]
+1

**Comment by bayburin** [comment]
+1

**Comment by ylerjen** [comment]
To people still looking for this request to be implemented, there's a workaround you can use in the meanwhile.
The dropdown has a "DropdownIcon" @Input. Just set it to ` dropdownIcon="pi pi-spinner pi-spin"` and a loading icon will appear instead of the chevron.

**Comment by picolino** [comment]
@ylerjen Four years 💥

**Comment by francowhyline** [comment]
Any news? 4 years since this was posted.

**Comment by laverix** [comment]
+1

**Comment by lothern** [comment]
+1

**Comment by LucasEduardoRomero** [comment]
+1 here

**Comment by mycahmason** [comment]
+1

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by MisterMunchkin** [comment]
Hi! Currently using p-dropdown on Angular 15, there's still no [loading] input for dropdown. I assumed it would be like p-button where you could just have something like 
```
[loading]="isLoading"
```

**Comment by enzotrucchi** [comment]
upvote in 2023!

**Comment by ilibilibom** [comment]
+1

**Comment by leeocoder** [comment]
+ 1

**Comment by tri-harmoney** [comment]
There is still no loading state for the multi select, why is this ticket closed? Am I missing something? We would like to start getting the list of items on click, but then we need a loading state. Is this already possible? If not we should re-open this ticket.

**Comment by jin-harmoney** [comment]
@mertsincan as far as I know, this has not been implemented in a different issue and still highly requested. Could you reopen the issue?

**Comment by avytak** [comment]
@mertsincan @cagataycivici could you please review that request? It would be nice to have that feature implemented for dropdown and multiselect.

**Comment by lixaotec** [comment]
+1

**Comment by phuctjoin** [comment]
+1

**Comment by james913** [comment]
I add my plus for this request. Will be so useful

**Comment by anusha-nt** [comment]
+1

**Comment by igorknext** [comment]
upvote in 2024!

**Comment by nicolasnevraumont** [comment]
+1

**Comment by eironman** [comment]
+1

**Comment by mionelTX** [comment]
+1

**Comment by janfess** [comment]
+1
