### ISSUE TITLE
p-listbox - onDblClick - event not returning list element

### ISSUE THREAD

**Issue by jjayaraman** [primefaces/primeng#5059]
I tried to use p-listbox - onDblClick - event and it is not returning the selected list element.

Instead the event object only has the below value,
 {"originalEvent":{"isTrusted":true}}

HTML Code:- 

   
            <p-listbox [options]="selectedTables" (onDblClick)="tableListBoxSelectEvent($event)" [listStyle]="{'min-height':'100px','max-height':'100px'}">
                <ng-template let-table pTemplate="item">
                    <div class="ui-helper-clearfix">
                        <span style="float:left;">{{table.tableLabel}}</span>
                    </div>
                </ng-template>
            </p-listbox>

Typescript Code:-

	  // Table select event from the Selected tables list box
	  tableListBoxSelectEvent(event) {
		console.log('this.choosenTable >> ' + JSON.stringify(event));
	 }

**Comment by jjayaraman** [comment]
It turns out that I need to have a field called 'value' in the JSON. If not it did not work.
It took quite long for me to know about with the help of stackoverflow, and it works now.

https://stackoverflow.com/questions/48587764/angular5-primeng-p-listbox-ondblclick-event-issue

**Comment by cagataycivici** [comment]
Glad to hear.
