### ISSUE TITLE
Clear button for Calendar

### ISSUE THREAD

**Issue by anikets43** [primefaces/primeng#506]
Hi @cagataycivici 

Is there any option to validate the date format when date is entered manually. Also, is it possible to have a clear button inside the control to clear the input field or any similar behavior.

Thanks in advance.
Aniket

**Comment by cbelhaffef** [comment]
Hi, 
I support the idea to have clear button, because i didn't find how i can clear value from calendar.

Thank you.

**Comment by hungerregnuh** [comment]
not the best solution, but if you get a reference to the element via ViewChild

you can set the value and use updateInputField() to get the behavior you want...

eg;
```
@ViewChild('p-calendar') calendar: Calendar;
this.calendar.value = null;
this.calendar.updateInputField();
```

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.

**Comment by jayordway** [comment]
Why was this closed, a clear button was not added to the calendar?

**Comment by Mrtcndkn** [comment]
Sorry for the misunderstanding. I will discuss it with my colleagues and will get back to you from here about the decision.

**Comment by cagataycivici** [comment]
Scheduled for 4.1.1

**Comment by jhlothamer** [comment]
This new feature does not appear on the 4.1.1 milestone list.  Nor is it on 4.1.2.  Can we get an update on when this feature?  Thanks!

**Comment by bossqone** [comment]
@cagataycivici any updates on this?

**Comment by cagataycivici** [comment]
Set to 4.1.4

**Comment by coppolaop** [comment]
There is any way to call this clear function by an external button?

**Comment by saver711** [comment]
This never added
it is 16.2.0 now
