### ISSUE TITLE
Upgrade to Font Awesome 5

### ISSUE THREAD

**Issue by RockGuitarist1** [primefaces/primeng#5060]
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Upgrade Font Awesome to Font Awesome 5.

Those of us who are now on Font Awesome 5 have to also keep a version of Font Awesome 4 on our websites as well, or a good bit of icons will not appear.

**Comment by jotapsl** [comment]
+1

**Comment by rafa-as** [comment]
Duplicate: https://github.com/primefaces/primeng/issues/4488

**Comment by cagataycivici** [comment]
See;

https://github.com/primefaces/primeng/issues/5098
