### ISSUE TITLE
Turbo Table column width miss aligned with Global Filter or in popup/modal when using scrollable true

### ISSUE THREAD

**Issue by ravikzm** [primefaces/primeng#5062]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/Nxca3ovCbtvx9kpGds0q?p=preview

**Current behavior**
The columns width are getting miss aligned in popup/modal when using scrollable true

Updated Plunker : http://plnkr.co/edit/LSJ06RGT2cUSGrfQEDy8?p=preview

**Expected behavior**
Columns width should not miss align in popup/modal when using scrollable true

* **Angular version:** 5.x.x

* **PrimeNG version:** 5.2.0
![image](https://user-images.githubusercontent.com/29487440/35774830-3b000f7e-0930-11e8-9738-7e34701ccfb8.png)

**Update**
I have noticed the same issue when using the **_Global Filter_** or **_individual column filter_** with Scrollable = true
and updated the Plunker
http://plnkr.co/edit/LSJ06RGT2cUSGrfQEDy8?p=preview
![image](https://user-images.githubusercontent.com/29487440/35787435-fcd78318-09e2-11e8-824a-2f3588bb4d07.png)

**Comment by ravikzm** [comment]
**Update**
I have noticed the same issue when using the Global Filter with Scrollable = true 
and updated the Plunker
http://plnkr.co/edit/LSJ06RGT2cUSGrfQEDy8?p=preview 
![image](https://user-images.githubusercontent.com/29487440/35787411-c641b8a0-09e2-11e8-9dcd-ce60630bbb30.png)

**Comment by AndreaBarbasso** [comment]
I've stepped into this bug myself, right now as a workaround I'm using a `*ngIf` binded to the same variable applied to the `[(visible)]` attribute. Not the prettiest thing (and not useful in many cases), but it might interest you: [you can see it in action here](http://plnkr.co/edit/Wy7biU5CruIP0Jq52DW9?p=preview).

**Comment by ravikzm** [comment]
@AndreaBarbasso thanks for workaround for the turbo table in Popup and works well. But I need a fix for the issue when using the global filter /column level filter.

**Comment by cagataycivici** [comment]
Ran your samples, unable to replicate with 5.2.4, seems it has been fixed already after recent improvements to scrolling tables.
