### ISSUE TITLE
Last modules of Version 5.0.2 like KeyFilter, Table and so on not installable via npm

### ISSUE THREAD

**Issue by alfredods** [primefaces/primeng#5063]
Hello,

the new modules in Primeng are not installable via npm. When I get the version 5.0.2 many modules are downloades into my application but not th new one like KeyFilter, Table, Card, etc. Did you forget something?

Regards

Alfredo

**Comment by Caixotim** [comment]
This is a problem with primeng.js that is not exporting the new modules.
They need to update it to export the new modules.

**Comment by cagataycivici** [comment]
Should be fixed by 5.2.x.
