### ISSUE TITLE
DataTable no-wrap for column headers

### ISSUE THREAD

**Issue by ModestasK** [primefaces/primeng#5065]
I've been using the PrimeReact for a bit and seems like there is no easy way of controlling the header column text wrapping as it wraps by default if the stuff does not fit within the screen. The only solution I found working was to put the table inside of parent element and set it's width to some high number making sure that the table fits nicely.
Like bellow exmaple:
![image](https://user-images.githubusercontent.com/24589080/35779947-993dcee8-09dd-11e8-819f-449ea5adb947.png)
I edited 2 columns manually for "Source" and "Name", but the others like "Age" and "Des" are completely off and overlaps on each other since the full table does not fit.
Any thoughts how to set "no wrap for column headers" without altering one by one manually?
This would especially be useful when having dynamic columns.

Thanks!

**Comment by cagataycivici** [comment]
Please use PrimeReact issue tracker, not the PrimeNG. Thank you.
