### ISSUE TITLE
TurboTable - Weird behaviour editing turbotable with non editable frozen column

### ISSUE THREAD

**Issue by rafa-as** [primefaces/primeng#5068]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://plnkr.co/edit/8qsy0AjfvZ82hcmeUiAU?p=preview

**Current behavior**
When make one turbotable editable, with one frozen column (the frozen column is not editable), we can't do a complete edition. When types one character inside the cell inputs these loses the focus.

**Expected behavior**
The inputs does not loses the focus and the edition continues until the user leave the input or press ESC or Enter keys.

**Minimal reproduction of the problem with instructions**
Inside the plunkr: https://plnkr.co/edit/8qsy0AjfvZ82hcmeUiAU?p=preview

1. Click inside one cell (the frozen column is not editable).
2. Type some character, for example: 1
3. You can look that the input loses the focus and the edition is finished.

**Please tell us about your environment:**
OS: MAC OS X High Sierra 10.13.3
IDE: WebStorm 2018.1 EAP
Package Manager: Yarn 1.3.2
Node: 9.5.0
Angular-cli: 1.6.7

* **Angular version:** 5.2.3

* **PrimeNG version:** 5.2.0

* **Browser:** all
 
* **Language:** all

* **Node (for AoT issues):** `node --version` = 9.5.0

**NOTE**: I have also AOT.
**NOTE 2**: I found some extra information: If you change the index used on the input ngModel to i+1, the binded data is wrong (obviously is the second row) but the edition behaviour its correct.
`<input type="text" [(ngModel)]="rowData[i]">` app/app.template.html:42

**Comment by rafa-as** [comment]
some news here?

**Comment by rafa-as** [comment]
The same behaviour on:
* **Primeng**: 5.2.4
* **Angular**: 5.2.10
* **Angular-cli**: 1.7.4

**Comment by cagataycivici** [comment]
This is weird, not sure why it fails like that, it is due to index of ngFor, if you use a column index it works;

```
<ng-template pTemplate="body" let-rowData let-columns="columns">
            <tr>
                <td *ngFor="let col of columns" pEditableColumn>
                    <p-cellEditor>
                        <ng-template pTemplate="input">
                            {{i}} - 
                            <input type="text" [(ngModel)]="rowData[col]">
                        </ng-template>
                        <ng-template pTemplate="output">
                            {{rowData[col]}}
                        </ng-template>
                    </p-cellEditor>
                </td>
            </tr>
        </ng-template>
```

```
this.cols = [
            0,1,2,3,4
        ];
```

**Comment by rafa-as** [comment]
It's something like this?

```javascript
<ng-template pTemplate="body" let-rowData let-columns="columns">
    <tr>
      <td *ngFor="let col of columns;let i = index" pEditableColumn>
        <p-cellEditor>
          <ng-template pTemplate="input">
            <input type="text" [(ngModel)]="rowData[i]">
          </ng-template>
          <ng-template pTemplate="output">
            {{rowData[i]}}
          </ng-template>
        </p-cellEditor>
      </td>
    </tr>
  </ng-template>
```
