### ISSUE TITLE
AutoComplete - .show() does not show the suggestions anymore after selection

### ISSUE THREAD

**Issue by kevinhaeni** [primefaces/primeng#5069]
*I'm submitting a ...**  (check one with "x")
```
[*] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
PrimeNG 4.1.0-rc.2 (WORKING)
https://plnkr.co/edit/FPLuWvmyFS9LSbX1OyPj?p=preview

PrimeNG 5.2.0 (NOT WORKING ANYMORE)
https://plnkr.co/edit/QBxTghBgpZqD549o32kj?p=preview

**Current behavior**
After selecting a suggestion, autoComplete.show() does no longer show the suggestions. This was working in version 4.x

When not selecting any suggestion, and just making the autoComplete lose and get focus again, it does work. As soon as a suggestion is clicked, it will not show again.

See "Minimal reproduction of the problem with instructions" on how to reproduce.

**Expected behavior**
The list of suggestions should show up again

**Minimal reproduction of the problem with instructions**
1) Search for "Smith"
2) Select "Smith John"
3) Click somewhere on the for the autocomplete to lose focus
4) Click inside the autocomplete

**What is the motivation / use case for changing the behavior?**
When the users select one suggestions out of n, it might have been the wrong one and they would like to choose another one without having to perform the same search again. 

* **Angular version:** 5

* **PrimeNG version:** Version 4 seems to be ok, in Version 5 the problem occurs

**Comment by cagataycivici** [comment]
show() requires the input to be focused.
