### ISSUE TITLE
PrimeNG Production Builds (ng build) not optimised

### ISSUE THREAD

**Issue by MarkPerryBV** [primefaces/primeng#5071]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
```
**Current behavior**
When building the PrimeNG with `ng build --prod` the template HTML is still present in the production builds causing the size of the minified file to be larger than needed.

**Expected behavior**
I would expect the HTML templates to be AoT compiled out of the production builds.

**Minimal reproduction of the problem with instructions**
Clone the following repo:
https://github.com/primefaces/primeng-quickstart-cli
Run `ng build --prod`
Inspect the `/dist/main.js` file (scroll to bottom) and you will see a load of HTML templates and components which have not been removed or AoT compiled.

**What is the motivation / use case for changing the behavior?**
To reduce the size of the production builds.

* **Angular version:** 2.0.X
5+

* **PrimeNG version:** 2.0.X
5.2.0

**Comment by cagataycivici** [comment]
This is not a PrimeNG issue, refer to Angular CLI for details.
