### ISSUE TITLE
Feature request: scroll to selection for TurboTable 

### ISSUE THREAD

**Issue by bniedermeyer** [primefaces/primeng#5072]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
It would be awesome if the TurboTable exposed a way to programmatically scroll to a selected row.

In my use case I would like to display multiple data points on a chart - when the user clicks on a data point I would like to have the TurboTable scroll to the row containing more information on that data point without requiring the user to scroll themselves. Ideally this could be controlled by passing the dataKey of the row that should be displayed to the method so that there is minimal performance impact.

**Comment by enjoi2349** [comment]
Also think this would be awesome! And kinda essential when displaying large lists without having people need to scroll all the way down to find the focused row.

**Comment by kc13greiner** [comment]
This would be so useful!

Possibly, also 'page to selection' if the table is using pagination.

**Comment by verookasalt** [comment]
Please add this feature. I am doing CRUD operations and when we get past the fixed scrollHeight the user has to manually scroll to the item in the list.

**Comment by kucharzyk** [comment]
"Page to selection" is one of the features I waiting for.

if I have paginated table and select element It should be visible (page should change)

**Comment by mmlitvin** [comment]
Strongly agree. Very much needed feature!

**Comment by mmlitvin** [comment]
Agree on "Possibly, also 'page to selection' if the table is using pagination." as well!

**Comment by mmlitvin** [comment]
Has anybody come up with temporary solution ? 
I used to be able to parse DOM elements  for p-dataTable and find <tr> I am interested in scrolling to and them update the div.offsetTop to trigger the scroll

But in this new turbotable it does not look like all <tr> elements are created but only those that are visible on the  screen.  SO I am I out of ideas on how to circumvent it.

**Comment by waustinlynn** [comment]
We could really use this as well!

**Comment by mmlitvin** [comment]
cagataycivici...Any progress here or timeline here? Thank you

**Comment by HorseBadorties** [comment]
I'm using a "handmade" Element.scrollIntoView solution like this: [Stackblitz example](https://stackblitz.com/edit/primeng-table-scroll)

**Comment by DarkAurore** [comment]
Thanks a lot @HorseBadorties that's just what I needed, great perfectly working example :)

**Comment by Spac3JaM** [comment]
Unfortunately @HorseBadorties solution won't work in our case, because we have a virtualized table, which loads its rows on LazyLoad event from the server.

**Comment by mmlitvin** [comment]
Same here.. lazy loading

**Comment by aspramsh** [comment]
Any news related to this feature @cagataycivici?

**Comment by mmlitvin** [comment]
It has been a year. Status please?

**Comment by ruchilabaruah** [comment]
Is scroll to selected row feature added ?

**Comment by sridhark158** [comment]
+1

**Comment by codehunter13** [comment]
almost 2 years ... cannot understand  this is not implmented yet.

**Comment by sridhark158** [comment]
@codehunter13  this worked for me   
scrollToView(event) {
    setTimeout(() => {
      event.target.parentElement.scrollIntoView({behavior: 'smooth'});
    }, 0);
  }

**Comment by codehunter13** [comment]
> @codehunter13 this worked for me
> scrollToView(event) {
> setTimeout(() => {
> event.target.parentElement.scrollIntoView({behavior: 'smooth'});
> }, 0);
> }

I use the same code but the problem is finding te right place to call it.
which event are you using and is it with lazy load/virtual scrolling?
Is there an event that fires after the first rows are lazy loaded

**Comment by mickeyjohn** [comment]
@HorseBadorties: It used to worked for me but not now with PrimeNg version 9.1.2. For the items passed the end of the table's viewport, It will not able to scroll up to make the row viewable. It seems that the causes rooted from update into "flex". Any thought to make it work again?

**Comment by mmlitvin** [comment]
Is there a plan to implement this?

**Comment by j0hnwhyte** [comment]
@HorseBadorties this is the most elegant solution I've found yet. Still it'd be great to have it native on the table element, currently there's no way to have the table start in a certain scroll state.

A possible use case is the classic master-detail view, where the table has to show the selected item without making the user scroll to it.

```typescript
  @ViewChildren("row", {read: ElementRef}) rowElement!: QueryList<ElementRef>;
  private readonly subscriptions = new Subscription();

// ...

    this.subscriptions.add(
      combineLatest([this.users$, this.route.paramMap]).pipe(
        map(([users, params]) => {
          const uid = params.get('uuid') || "";
          this.selectedUser = users.find(u => u.Uuid === uid);

          if (this.selectedUser) {
            // After the rows have been rendered
            setTimeout(() => {
              const el = this.rowElement.find(r => r.nativeElement.getAttribute("uuid") === uid)!;
              el.nativeElement.scrollIntoView({inline: "start", block: "start"});
            })
          }
        }),
      ).subscribe()
    );
```

**Comment by VictorPetch** [comment]
Not sure if this helps, but in my case I solved with this:

- Add #row tag and the unique attribute of your table in html

` <ng-template pTemplate="body" let-apmItem">`
           ` <tr  #row [attr.id]="apmItem.dataTableId">`
     

- Add this in your setup       

`@ViewChildren("row", { read: ElementRef })`
    `rowElement: QueryList<ElementRef>;`

- Add this inside any function (possibly called when you push a button):
            `
setTimeout(() => {
                const el = this.rowElement.find(
                    (r) =>
                        r.nativeElement.getAttribute("id") ===
                        (this.dataTable.items.length - 1).toString()
                );
                el.nativeElement.scrollIntoView({
                    inline: "start",
                    block: "start",
                });
            });
`
It will go to the row with dataTableId === 2. setTimeout is needed here because you need to be sure your element is loaded.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
