### ISSUE TITLE
Weird behavior when editing p-spinner and min is set

### ISSUE THREAD

**Issue by jupin-r** [primefaces/primeng#5073]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/fjogsntqqwgvGJnKiZbB?p=preview

**Current behavior**
Min is set to number different from zero, e.g. 50. If you start typing a value 1000 and press number 1, then the spinner value is changed to value 50. If you type whole number 1000 the result is 5000. The typed text is changed too early (while typing).

**Expected behavior**
The value of the spinner is changed when user finish typing.

**Minimal reproduction of the problem with instructions**
angular 4+ w/ primeng 4.3.0+.
use component spinner and set min attribute to value greather than zero

**What is the motivation / use case for changing the behavior?**
A user should be able to type right value immediately.

**Comment by sander1693** [comment]
I totally agree with you. It's a weird behaviour. I use onBlur event to controll min & max, but when you keep pressed a spinner button the event isn't called.
