### ISSUE TITLE
RadioButton Header name

### ISSUE THREAD

**Issue by nusivtech** [primefaces/primeng#5076]
Hi,
I am using [Radio Button Single selection](https://www.primefaces.org/primeng/#/datatable/selection). Trying to add a header for that column and not finding any solution. Attached file for reference .
Please help

![radiobutton_primeng](https://user-images.githubusercontent.com/15810812/35824237-dcd963f2-0a77-11e8-991d-4d0e42936ecc.png)

**Comment by ManojSethuraman** [comment]
I think for Radio Selection you can't have a common select option, its available for Checkbox selection, but refer the docs once

**Comment by nusivtech** [comment]
I was looking for header label only.

**Comment by girijass** [comment]
I am also looking how to add level header on radio button column. Please let me know if anyone having any solution.

**Comment by cagataycivici** [comment]
DataTable is deprecated so closing the issue, note that this is trivial to do in p-table as you have full control over the rows and cells so you can place your label inside the header.
