### ISSUE TITLE
Turbotable selection of Rows on click of Rows

### ISSUE THREAD

**Issue by ManojSethuraman** [primefaces/primeng#5078]
### Previously in DataTable if we click on any area of the Row, the particular Row will be selected, but now only if you click on the checkbox / radio button its getting selected.

**Current behavior**
Turbo Table Row Selection happens only on click of Row Level Checkbox.
**Expected behavior**
Turbo Table Row Selection Should happen on click of the Row anywhere.

**Comment by cs-ridvantanik** [comment]
Is there any release plan for this issue?

**Comment by cs-ridvantanik** [comment]
@ManojSethuraman Actually it is working like expected. One should not forget to bind [pSelectableRow]="rowData" in the row of the body template.

**Comment by cagataycivici** [comment]
This is by design, row selection is not triggered on click of clickable elements like inputs, p-dataTable is same as well.
