### ISSUE TITLE
Add FontAwesome 5 support

### ISSUE THREAD

**Issue by dhniels** [primefaces/primeng#5079]
**I'm submitting a ...** 
```
[x] feature request
```

**Current behavior**
FontAwesome 5 breaks FontAwesome 4 because the syntax has changed. For example, before you would do `fa fa-circle-o` for an outline circle icon, in the new version they've changed the whole prefix system. Now you would do `far fa-circle` for an outline circle and `fas fa-circle` for a solid circle. They've also removed aliases so now every icon only has one class name.

FontAwesome also provides a js shim file to add backwards compatibility quick and easy. I don't know if that will be useful here, you may have to do a full, proper upgrade using find and replace to update all the obsolete FA class names.

See their guide on how to use FA5 when upgrading from FA4:
https://fontawesome.com/how-to-use/upgrading-from-4

**Please tell us about your environment:**

* **Angular version:** 
5.2.3

* **PrimeNG version:** 
5.2.0

**Comment by rafa-as** [comment]
Duplicate: https://github.com/primefaces/primeng/issues/4488 and https://github.com/primefaces/primeng/issues/5060

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/issues/5098

**Comment by rcbyron** [comment]
#5098 #5060 #4488 seem to be related, but not exactly duplicate issues. I really hope PrimeNG will add support for FA5 SVG core. This way we can fully switchover to minified SVGs instead of web fonts. Moreover, we could reduce bundle size by only importing the icon svgs that we need.

**Comment by SteamWind** [comment]
Font Awesome now provide a component for their icons:
https://fontawesome.com/how-to-use/on-the-web/using-with/angular
It's hard to use it in buttons by exemple...
