### ISSUE TITLE
Migration to new forms api

### ISSUE THREAD

**Issue by xgrommx** [primefaces/primeng#508]
Angular 2 has a new module `@angular/forms` with new api. Previous api will be deprecated soon. Here a specification https://docs.google.com/document/u/1/d/1RIezQqE4aEhBRmArIAS1mRIZtWFf6JxN_7B4meyWK0Y/pub

**Comment by cagataycivici** [comment]
We've already done it, please see;

https://github.com/primefaces/primeng/issues/492
