### ISSUE TITLE
p-dialog component does't works properly in mobile browser

### ISSUE THREAD

**Issue by alialtun14** [primefaces/primeng#5081]
[From the very beginning](https://github.com/primefaces/primeng/issues/4323)   p-dialog component hasn't work properly in mobile browser. 

This problem also can be seen by opening overlays demo on primeng ultima showcase pages. 

My code related this dialog form. I have used  [responsive]="true"

    `<p-dialog [(visible)]="_opt.show.self" [responsive]="true" showEffect="fade" [modal]="true" 
    appendTo="body" [width]="nWidth">
    `
![img_20180206_054140](https://user-images.githubusercontent.com/782196/35845662-afcc8cda-0b13-11e8-8207-cfc4579fdda8.jpg)

https://www.primefaces.org/ultima-ng/#/overlays

![screenshot_20180206-054434](https://user-images.githubusercontent.com/782196/35845665-b1e66068-0b13-11e8-86c5-fc70f40c315f.jpg)

**Comment by cagataycivici** [comment]
It works fine in our test cases.

**Comment by visat09** [comment]
if you resize browser from large screen it's work fine 

but it does't works properly in mobile screen

... i think @alialtun14 you can use "styleClass"

https://stackoverflow.com/questions/44842290/dialog-component-in-primeng-no-responsive-on-mobile-view

![image](https://user-images.githubusercontent.com/6519797/43937280-ec755464-9c86-11e8-8c3f-cd71ac874afb.png)

**Comment by alialtun14** [comment]
Thank you @visat09 for your valuable information.

**Comment by alialtun14** [comment]
> It works fine in our test cases.

I do not think so.  The screenshow is belong to official primeng modal page showcase. I take this 10 minutes ago. 

![modal](https://user-images.githubusercontent.com/782196/43953577-bfd82784-9c99-11e8-9566-ccaa9a43311d.jpg)
