### ISSUE TITLE
Unable to use font-awesome version 5+ in primeng button control.

### ISSUE THREAD

**Issue by Ramprits** [primefaces/primeng#5082]
![image](https://user-images.githubusercontent.com/21260321/35850611-6e6bb788-0b4b-11e8-8d92-2ea3eafbc505.png)

Could you please help or update latest version of font-awesome

**Comment by rafa-as** [comment]
Duplicate: #4488  #5060 #5079

**Comment by cagataycivici** [comment]
See;

https://github.com/primefaces/primeng/issues/5098
