### ISSUE TITLE
p-dropdown filter issue

### ISSUE THREAD

**Issue by Rainpia** [primefaces/primeng#5085]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

for dropdown list [ filter = true] , 

- 1, filter input enter something, then options will be filter, ;
- 2, do not delete the filter value, change the options list;
- 3, the new options list is gone and the filter value is empty,

**Expected behavior**

- 1, the filter value should have value, and the new options list will be filterd
- 2, or the filter value should be null and the new options list should be exist.

**My Analysis**
Problem : when change options, this.filterValue is remaining, but the input value is gone.

**My solution**
[*] these part code is what i add. when options change, delete the filter value; and implement expected behavior 2.
but expected behavior 1 should be more reasonable.
```
@Input()
  get options(): any[] {
    return this._options;
  }
  set options(val: any[]) {
    const opts = this.optionLabel
      ? this.objectUtils.generateSelectItems(val, this.optionLabel)
      : val;
    this._options = opts;
    this.optionsToDisplay = this._options;
    this.updateSelectedOption(this.value);
    this.optionsChanged = true;
   [*]  if (this.filterViewChild && this.filterViewChild.nativeElement) {
   [*]   this.filterViewChild.nativeElement.value = "";
   [*]  }
   [*]  this.filterValue = null;

    if (this.filterValue && this.filterValue.length) {
      this.activateFilter();
    }
  }
```

**Comment by lasimone** [comment]
+1

**Comment by cagataycivici** [comment]
We can replicate the issue with 5.2.4, it works like you have described, please provide a sample at;

https://stackblitz.com/github/primefaces/primeng-issue-template

**Comment by Rainpia** [comment]
yes, i added sample.
https://stackblitz.com/edit/github-rqe167
