### ISSUE TITLE
acceptLabel - rejectLabel are not settable with ConfirmationService

### ISSUE THREAD

**Issue by graphicsxp** [primefaces/primeng#5090]
It should be possible to set acceptLabel property when creating a dialog with the ConfirmationService.

**Comment by nelsonduvall** [comment]
This seems not to be fixed in primeng v7.1.0 using the confirmation service. The labels are set but "ignored" in the dialog - the default labels are displayed instead.

**Comment by xrkolovos** [comment]
Prime ng "primeng": "8.1.1" not fixed as well

**Comment by MiRush94** [comment]
this is still not working when using the confirmation service in version 9.1.3

acceptVisible and rejectVisible also have no effect when set from the confirmation service and yes, we don't always have static text as labels etc. so this should be fixed soon.

**Comment by waratah** [comment]
Just found this problem on "primeng":  9.1.3.  after upgrading from 8.1.4.

**Comment by mittal-sahab-sudo** [comment]
Is this issue resolved yet ? I am finding this issue is in Prime ng 16.0.2
