### ISSUE TITLE
File upload URL

### ISSUE THREAD

**Issue by Iamguy84** [primefaces/primeng#5091]
Hi folks,

```
<p-fileUpload mode="basic" accept="image/*" multiple="multiple" maxFileSize="1000000" (onSelect)="onFileSelect($event)" auto="false" chooseLabel="Browse"></p-fileUpload>
<ul *ngIf="uploadedFiles.length">
    <li *ngFor="let file of uploadedFiles">{{file.name}} - {{file.size}} bytes</li>
</ul>
```

I am getting error message and it says:
POST http://localhost/undefined 404 (Not Found)

I want without URL post. Any idea?

I am waiting for your response.

Thanks in Advance.

**Comment by cagataycivici** [comment]
Please refer to the fileupload documentation, I guess you need the customUpload as enabled.
