### ISSUE TITLE
how to add button inside tabview in primefaces

### ISSUE THREAD

**Issue by mounika544** [primefaces/primeng#5092]
<p:tabView value="#{buildingCoverageWeekend.shifts}" var="shift" cache="false">
                                        <p:ajax event="tabChange" listener="#{buildingCoverageWeekend.onTabChange}"  />
                                        <p:tab title="#{shift.short_name}"    titleStyle="#{buildingCoverageLeftPane.tabStyle}"  disabled="#{buildingCoverageLeftPane.isTabDisabled(shift.id)}">
                                            <ui:include  src="overtime/buildingCoverageLeftPane.xhtml"/>
                                        </p:tab>
                                    </p:tabView>

**Comment by AndreaBarbasso** [comment]
Wrong repo! :)
[primefaces](https://github.com/primefaces/primefaces)

**Comment by cagataycivici** [comment]
Please create the issue in PrimeFaces.
