### ISSUE TITLE
"disabled" property not working on tableRadioButton and tableCheckbox

### ISSUE THREAD

**Issue by UrzaUrza** [primefaces/primeng#5095]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When the "disabled" property is set to true on tableRadioButton or tableCheckbox, the row is still selectable.

**Expected behavior**
When the "disabled" property is set to true on tableRadioButton or tableCheckbox, the row is not selectable.

* **PrimeNG version:** 5.2.0

**Comment by sashaSavych** [comment]
The same for me :(
"disabled" property sets just style

**Comment by jun58** [comment]
It same for me ~~

**Comment by noamichael** [comment]
I submitted a PR:

#5515

**Comment by cagataycivici** [comment]
Set to 5.2.5.

**Comment by cagataycivici** [comment]
PR merged, thank you.

**Comment by jmaruiz** [comment]
Can you do the same with tableHeaderCheckbox? That does not obey disabled styling or functionality.
