### ISSUE TITLE
Icon does not appear in p-selectButton

### ISSUE THREAD

**Issue by liliom55** [primefaces/primeng#5096]
@vincent 
**I'm submitting a ...
[x] bug report 

**Plunkr Case (Bug Reports)**

**Current behavior**
Does not show icon 

**Expected behavior**
Should shows icon

**Please tell us about your environment:**
Operating system: Windows 7
IDE: Vscode
npm:5.6.0

* **Angular version:
angular: "^5.1.0"
angular/cli: "^1.6.6"

* **PrimeNG version:
"primeng": "^5.2.0-rc.2",

* **Browser:
IE11,Mozila Firefox
 
Language:TypeScript 

`<p-selectButton [options]="types" [(ngModel)]="selectedType"></p-selectButton>
`
`this.types = [
            {label: 'Paypal', value: 'PayPal', icon: 'fa fa-fw fa-cc-paypal'},
            {label: 'Visa', value: 'Visa', icon: 'fa fa-fw fa-cc-visa'},
            {label: 'MasterCard', value: 'MasterCard', icon: 'fa fa-fw fa-cc-mastercard'}
        ];
`

**Comment by liliom55** [comment]
@vincent @csokun @jfarcand @Skyr @bossqone 
Could you please response this issue. I need a solution.

**Comment by Skyr** [comment]
I can't see why you are mentioning me. I'm neither related to this project nor to this bug.

**Comment by gamefundas** [comment]
The feature was added to recent versions of PrimeNg. Please confirm your package.json for 5.2.x version and perhaps clear your browser cache.

**Comment by liliom55** [comment]
Thank you so much

**Comment by liliom55** [comment]
Skyr:
I realy sorry if I bother you. I had no mean by mention you. I was in urgent situation so I thought if I mention all member, somebody can help me sooner. Anyway I apologize you.

**Comment by cagataycivici** [comment]
Update the PrimeNG version to latest to get this feature please.
