### ISSUE TITLE
p-editor loses <br> tags when using FormGroup.patchValue()

### ISSUE THREAD

**Issue by seanjrankin** [primefaces/primeng#5097]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://plnkr.co/edit/igeMw9WfhW6Nq0uD6oPe?p=preview

**Current behavior**
I have components that have edit and view states. When they enter edit mode, they patch the formGroup using patchValue to ensure the formData is up-to-date.  When I do this in Chrome, the p-editor appears to strip out the `<p><br></p>` blocks. This causes issues on our site if the user toggles in and out of edit mode, or the form data is patched via websocket. This appears to only happen in Chrome.

**Expected behavior**
Patch value does not destroy lose any data.

**Minimal reproduction of the problem with instructions**
See plunker above

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows 10

* **Angular version:** 4.3.1

* **PrimeNG version:** 4.3.0

* **Browser:** [Chrome 63.0.3239.132 ]

 
* **Language:** [all | TypeScript 2.4 | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =  8.1.2

**Comment by cagataycivici** [comment]
Please try with 5.2.4 and newer, should be fixed with it.
