### ISSUE TITLE
Allow same behavior for multiple selections in TurboTable as in DataTable

### ISSUE THREAD

**Issue by simdevmon** [primefaces/primeng#5099]
**I'm submitting a ...** 
```
[ ] bug report 
[x] feature request
[ ] support request 
```

**Current behavior**
When I migrate from DataTable to TurboTable there is a different behavior in multiple row selection. 

_DataTable_
On a simple click the selection changes to the current row and only if I hold down CTRL multiple rows are selected.
https://www.primefaces.org/primeng/#/datatable/selection

_TurboTable_
On a simple click the row is added to the selection, but the existing selection remains.
https://www.primefaces.org/primeng/#/table/selection

**Expected behavior**
It would be good if there was a possiblity to have the same behavior on multiple row selection for TurboTable as it was for DataTable. 

**What is the motivation / use case for changing the behavior?**
When clicking through a list of data with a detail view, the main use case is only to have one row selected and multiple rows only for bulk operations. 

**Angular version:**
5.2.3

**PrimeNG version:**
5.2.0

**Comment by dpaquette** [comment]
I ran into this today while migrating from Data Table to Turbo Table. It would be nice to have the option here to require Ctrl+Click for multiple select since our current implementation assumes that behaviour.

**Comment by andreeapNRO** [comment]
Any news for this item?

**Comment by bossqone** [comment]
I've checked documentation and there stays:

> By default each row click adds or removes the row from the selection, if you prefer a classic metaKey based selection approach enable metaKeySelection true so that multiple selection or unselection of a row requires metaKey to be pressed. Note that, on touch enabled devices, metaKey based selection is turned off automatically as there is no metaKey in devices such as mobile phones.

Does it solve your issue?

**Comment by andreeapNRO** [comment]
I just checked this, but it doesn't work (i am using the new component called - Turbo Table). I guess that the documentation is the old component ... ?

**Comment by bossqone** [comment]
@andreeapNRO please check https://www.primefaces.org/primeng/#/table/selection

**Comment by andreeapNRO** [comment]
Thank you, it works (i had an issue with the primeng version - wasn't updated - and i have noticed it after i put the comment).

**Comment by cagataycivici** [comment]
I've reintroduced metaKeySelection to 5.2.x recently.

**Comment by dpaquette** [comment]
@cagataycivici Excellent, thank you. Is there a changelog anywhere for Primeng releases?

**Comment by Janatbek** [comment]
@dpaquette https://www.primefaces.org/blog/
