### ISSUE TITLE
Provide the possibility to set the title attribute in picklist buttons

### ISSUE THREAD

**Issue by coettl** [primefaces/primeng#5100]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

**Current behavior**
there is no possibility to set the title attribute in picklist buttons, for example for the double right button

**Expected behavior**
an @input() property where we can set a title attribute for the shown buttons

**What is the motivation / use case for changing the behavior?**
The title attribute could be used for extra informations e.g. tooltip.

* **Angular version:** 2.0.X
all versions

* **PrimeNG version:** 2.0.X
all versions

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all browsers
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all languages

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
