### ISSUE TITLE
DataScroller onLazyLoad not called without totalRecords

### ISSUE THREAD

**Issue by mfrro** [primefaces/primeng#5101]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
With 5.2.0 the onLazyLoad method doesn't get called when the totalRecords property of the datascroller isn't set.

**Expected behavior**
With 5.2.0-rc.2 it worked without the totalRecords property being set. 

**What is the motivation / use case for changing the behavior?**
This was useful, because the total record count isn't always known (e.g. with firebase data).

* **Angular version:** 5.2.1

* **PrimeNG version:** 5.2.0

* **Browser:** all
 
* **Language:** TypeScript 2.6.2

**Comment by rafa-as** [comment]
Same here!

**Comment by cagataycivici** [comment]
DataTable is deprecated, please use p-table instead.

**Comment by MiselKING** [comment]
This is related to "DataScroller" component and it's still an issue... Here is [stackblitz](https://stackblitz.com/edit/angular-ubfblg) example to reproduce this issue...
