### ISSUE TITLE
Context Menu on turbo-table won't close

### ISSUE THREAD

**Issue by tigrenok00** [primefaces/primeng#5105]
I'm using contextMenu on a turbo-table row, with usage like in the example code, however, the context menu won't dissapear when clicking outside the table or when left-clicking on a row. It only moves to another row on right-click. 
In also doesn't close even when clicking on the menu options.

Angular version: 5
PrimeNG version: 5.2.0

**Comment by cagataycivici** [comment]
Unable to replicate;

https://www.primefaces.org/primeng/#/table/contextmenu
