### ISSUE TITLE
Carousel page link not selected and prev/next button not enabled

### ISSUE THREAD

**Issue by OnTheArk** [primefaces/primeng#5106]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
If values for Carousel come from a service as an observable then carousel is populated but page links are not selected and next/prev button are not enabled/clickable.

**Expected behavior**
The first page link should be selected, the prev button should be disabled and if there are multiple pages the next button should be enabled.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/NvDblheeJ2BVSM02eWcS?p=preview

* **Angular version:** 5.0.X

* **PrimeNG version:** 5.2.X

* **Browser:** [all]

 
* **Language:** [ TypeScript 2.5]

**Comment by georgeos** [comment]
I found the solution.

The problem is with the observable. If you put your main div using a variable which responds to true after the observable is loaded, then the problem will dissapear.

http://plnkr.co/edit/63nrvGadTmYNIwe5mYBX?p=preview

**Comment by cagataycivici** [comment]
Glad to hear.
