### ISSUE TITLE
TurboTable: onEditInit event does not contain column information

### ISSUE THREAD

**Issue by simdevmon** [primefaces/primeng#5107]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report 
[ ] feature request
[ ] support request 
```

**Current behavior**
If I bind the onCellInit event on TurboTable, event.column is undefined. 

**Expected behavior**
I would expect the correct event data when binding onEditInit.

**Minimal reproduction of the problem with instructions**

I tried to move the example to Punkr, but I got the error that `p-cellEditor` is not an Angular element. 

```
<p-table [columns]="cols" [value]="cars" (onEditInit)="onCellEdit($event)">
    <ng-template pTemplate="header" let-columns>
        <tr>
            <th>Vin</th>
            <th>Year</th>
            <th>Brand</th>
            <th>Color</th>
        </tr>
    </ng-template>
    <ng-template pTemplate="body" let-rowData let-columns="columns">
        <tr>
            <td pEditableColumn>
                <p-cellEditor>
                    <ng-template pTemplate="input">
                        <input type="text" [(ngModel)]="rowData.vin">
                    </ng-template>
                    <ng-template pTemplate="output">
                        {{rowData.vin}}
                    </ng-template>
                </p-cellEditor>
            </td>
        </tr>
    </ng-template>
</p-table>
```

```
onCellEdit(event: any) {
event.column // is undefined.
}
```

**Angular version:** 5.2.3

**PrimeNG version:** 5.2.0

**Comment by simdevmon** [comment]
I think it is also related to https://github.com/primefaces/primeng/issues/4962. 

I changed it now to:
`<td *ngFor="let col of columns" style="overflow: hidden;" [pEditableColumn]="row" [pEditableColumnField]="col">`

And I can access the data now, but I think the documentation is wrong.
https://www.primefaces.org/primeng/#/table

The column data can be accessed with event.**field** and not with event.**column** as written in the documentation.

**Comment by cagataycivici** [comment]
Will check the docs again.

**Comment by cagataycivici** [comment]
Docs fixed.
