### ISSUE TITLE
TurboTable : CSV Export doesnt work if [columns] not provided

### ISSUE THREAD

**Issue by amitsol** [primefaces/primeng#5114]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://plnkr.co/edit/Rl0wldPXBzyMY7sSQF5E?p=preview

**Current behavior**
If [columns] are not provided and th & td is created individually then exportCSV() doesnt work. 

<p-table #dataTable [value]="cars" columnResizeMode="expand"
      [scrollable]="true" scrollHeight="200px" [style]="{width: '200px'}" columnResizeMode="fit" [resizableColumns]="true">
    <ng-template pTemplate="header" let-columns>
        <tr>
            <th Style="width: '100px'"  pResizableColumn>
                Vin
            </th>
            <th Style="width: '100px'"  pResizableColumn>
                Color
            </th>
        </tr>
    </ng-template>

ERROR TypeError: Cannot read property 'length' of undefined
    at Table.exportCSV (VM2179 table.js:826)

**Expected behavior**
Export should work irrespective the [columns] are provided. Column names can be derived from Table element's headers.

**PrimeNG version**
5.2.0 Final

**Comment by cagataycivici** [comment]
This is documented;

`Table can export its data in CSV format using exportCSV() method. By default whole data is exported, if you'd like to export only the selection then pass a config object with selectionOnly property as true. Note that  columns should be dynamic for export functionality to work and column objects must define field/header properties.`

**Comment by colinbull** [comment]
I know this is a closed issue, but just wanted to mention it is possible to get the data exported with static columns, although some of the bells and whistles are missing. 

```   
    <p-table
        [value]="searchResults"
        [autoLayout]="'true'"
        [paginator]="true"
        [lazy]="true"
        [rows]="stats.pageSize"
        [totalRecords]="stats.totalElements"
        [loading]="isLoading"
        (onLazyLoad)="setPage($event)"
        [style.height]="'100%'"
        scrollHeight="100%">
        <ng-template pTemplate="header">
          <tr>
            <th style="width: 50px"></th>
            <th>Source Id</th>
            <th>Source System</th>
            <th>Active</th>
          </tr>
        </ng-template>
        <ng-template pTemplate="caption">
            <div class="ui-helper-clearfix">
                <button mat-icon-button style="float: left" matTooltip="Export CSV" type="button" (click)="exportCsv()">
                    <mat-icon>save_alt</mat-icon>
                </button>
            </div>
        </ng-template>
        <ng-template pTemplate="body" let-evnt>
            <tr>
                <td>
                    <button mat-icon-button [routerLink]="'/contract/' + evnt.id">
                        <mat-icon>edit</mat-icon>
                    </button>
                </td>
                <td>{{evnt.sourceId}}</td>
                <td>{{evnt.sourceSystem}}</td>
                <td style="text-align: center" [attr.exportValue]="evnt.isActive.toString()">
                    <mat-checkbox disabled="true" [checked]="evnt.isActive"></mat-checkbox>
                </td>
            </tr>
        </ng-template>
    </p-table>
```

Given this table, you can extract the data from it using the following service. 

```   
    import {Injectable} from "@angular/core";

    export class TableCell {
    constructor(public index: number,
                public data: string) {}
    }

    export class TableData {
    constructor(
        public headers : TableCell[],
        public data : TableCell[][]
    ) {}
    }

    @Injectable()
    export class ExportService {

        private readRowCells(cells: HTMLCollectionOf<HTMLTableCellElement | HTMLTableHeaderCellElement>) : TableCell[] {
            let rowData = [];
            for (let cellIndex = 0; cellIndex < cells.length; cellIndex++) {
            let cell = cells.item(cellIndex);
            let exportable = cell.attributes.getNamedItem("exportable");

            if(!exportable || (exportable && exportable.value !== "false")) {
                let text = "";
                let exportValue = cell.attributes.getNamedItem("exportValue");
                if(exportValue) {
                text = exportValue.value;
                } else {
                text = cell.innerText;
                }
                if (text !== "") {
                rowData.push({index: cellIndex, data: text.trim()});
                }
            }
            }

            return rowData;
        }

        private readTable(table : HTMLTableElement) : TableData {
            let headers = this.readRowCells(table.rows.item(0).cells).filter(c => {
            return c.data !== "";
            });


            let dataRows = [];
            for (let rowIndex = 1; rowIndex < table.rows.length; rowIndex++) {
            let rowData = this.readRowCells(table.rows.item(rowIndex).cells).filter(c => {
                return headers.findIndex(h => {
                return h.index === c.index;
                }) !== -1
            });

            dataRows.push(rowData);
            }

            return new TableData(headers, dataRows);
        }

        private csvTryQuote(data:string) {
            if(data.includes(',')) {
            return '"' + data.replace(/"/g, '""') + '"';
            }

            return data.replace(/"/g, '""');
        }

        private toCsv(data:TableData) {
            let csv = '\ufeff';
            let csvSeparator = ',';

            data.headers.forEach((cell, i) => {
            csv += this.csvTryQuote(cell.data);

            if (i < (data.headers.length - 1)) {
                csv += csvSeparator;
            }

            });

            data.data.forEach((row, j) => {
            csv += '\n';

            row.forEach((cell, i) => {
                csv += this.csvTryQuote(cell.data);

                if (i < (row.length - 1)) {
                csv += csvSeparator;
                }
            });
            });

            return csv;
        }

        private toJson(data:TableData) {
            let rows = [];

            data.data.forEach((row, j) => {
            let obj = {};

            row.forEach((cell, i) => {
                obj[data.headers[i].data] = cell.data
            });

            rows.push(obj);
            });

            return JSON.stringify(rows);
        }

        export(data:string, mimeTypeAndCharset:string, filename:string) {
            let blob = new Blob([data], {
            type: mimeTypeAndCharset
            });

            if (window.navigator.msSaveOrOpenBlob) {
            navigator.msSaveOrOpenBlob(blob, filename);
            }
            else {
            let link = document.createElement("a");
            link.style.display = 'none';
            document.body.appendChild(link);
            if (link.download !== undefined) {
                link.setAttribute('href', URL.createObjectURL(blob));
                link.setAttribute('download', filename);
                link.click();
            }
            else {
                data = mimeTypeAndCharset + ',' + data;
                window.open(encodeURI(data));
            }
            document.body.removeChild(link);
            }
        }

        exportCsv(table : HTMLTableElement, filename:string) {
            let csv = this.toCsv(this.readTable(table));
            this.export(csv,'text/csv;charset=utf-8;', filename);
        }

        exportJson(table : HTMLTableElement, filename:string) {
            let csv = this.toCsv(this.readTable(table));
            this.export(csv,'application/json;charset=utf-8;', filename);
        }
    }
``` 

Inject this service into your view, then get a reference to the PrimeNG table `@ViewChild(Table) resultTable;`, and bind the button click to 

```
    exportCsv() {
        let tableRef: ElementRef<HTMLTableElement> = this.resultTable.tableViewChild;
        let table = tableRef.nativeElement;

        this.exportService.exportCsv(table, "Contracts.csv");
    }
```

**Comment by mayu024** [comment]
> I know this is a closed issue, but just wanted to mention it is possible to get the data exported with static columns, although some of the bells and whistles are missing.
> 
> ```
>     <p-table
>         [value]="searchResults"
>         [autoLayout]="'true'"
>         [paginator]="true"
>         [lazy]="true"
>         [rows]="stats.pageSize"
>         [totalRecords]="stats.totalElements"
>         [loading]="isLoading"
>         (onLazyLoad)="setPage($event)"
>         [style.height]="'100%'"
>         scrollHeight="100%">
>         <ng-template pTemplate="header">
>           <tr>
>             <th style="width: 50px"></th>
>             <th>Source Id</th>
>             <th>Source System</th>
>             <th>Active</th>
>           </tr>
>         </ng-template>
>         <ng-template pTemplate="caption">
>             <div class="ui-helper-clearfix">
>                 <button mat-icon-button style="float: left" matTooltip="Export CSV" type="button" (click)="exportCsv()">
>                     <mat-icon>save_alt</mat-icon>
>                 </button>
>             </div>
>         </ng-template>
>         <ng-template pTemplate="body" let-evnt>
>             <tr>
>                 <td>
>                     <button mat-icon-button [routerLink]="'/contract/' + evnt.id">
>                         <mat-icon>edit</mat-icon>
>                     </button>
>                 </td>
>                 <td>{{evnt.sourceId}}</td>
>                 <td>{{evnt.sourceSystem}}</td>
>                 <td style="text-align: center" [attr.exportValue]="evnt.isActive.toString()">
>                     <mat-checkbox disabled="true" [checked]="evnt.isActive"></mat-checkbox>
>                 </td>
>             </tr>
>         </ng-template>
>     </p-table>
> ```
> Given this table, you can extract the data from it using the following service.
> 
> ```
>     import {Injectable} from "@angular/core";
> 
>     export class TableCell {
>     constructor(public index: number,
>                 public data: string) {}
>     }
> 
>     export class TableData {
>     constructor(
>         public headers : TableCell[],
>         public data : TableCell[][]
>     ) {}
>     }
> 
>     @Injectable()
>     export class ExportService {
> 
>         private readRowCells(cells: HTMLCollectionOf<HTMLTableCellElement | HTMLTableHeaderCellElement>) : TableCell[] {
>             let rowData = [];
>             for (let cellIndex = 0; cellIndex < cells.length; cellIndex++) {
>             let cell = cells.item(cellIndex);
>             let exportable = cell.attributes.getNamedItem("exportable");
> 
>             if(!exportable || (exportable && exportable.value !== "false")) {
>                 let text = "";
>                 let exportValue = cell.attributes.getNamedItem("exportValue");
>                 if(exportValue) {
>                 text = exportValue.value;
>                 } else {
>                 text = cell.innerText;
>                 }
>                 if (text !== "") {
>                 rowData.push({index: cellIndex, data: text.trim()});
>                 }
>             }
>             }
> 
>             return rowData;
>         }
> 
>         private readTable(table : HTMLTableElement) : TableData {
>             let headers = this.readRowCells(table.rows.item(0).cells).filter(c => {
>             return c.data !== "";
>             });
> 
> 
>             let dataRows = [];
>             for (let rowIndex = 1; rowIndex < table.rows.length; rowIndex++) {
>             let rowData = this.readRowCells(table.rows.item(rowIndex).cells).filter(c => {
>                 return headers.findIndex(h => {
>                 return h.index === c.index;
>                 }) !== -1
>             });
> 
>             dataRows.push(rowData);
>             }
> 
>             return new TableData(headers, dataRows);
>         }
> 
>         private csvTryQuote(data:string) {
>             if(data.includes(',')) {
>             return '"' + data.replace(/"/g, '""') + '"';
>             }
> 
>             return data.replace(/"/g, '""');
>         }
> 
>         private toCsv(data:TableData) {
>             let csv = '\ufeff';
>             let csvSeparator = ',';
> 
>             data.headers.forEach((cell, i) => {
>             csv += this.csvTryQuote(cell.data);
> 
>             if (i < (data.headers.length - 1)) {
>                 csv += csvSeparator;
>             }
> 
>             });
> 
>             data.data.forEach((row, j) => {
>             csv += '\n';
> 
>             row.forEach((cell, i) => {
>                 csv += this.csvTryQuote(cell.data);
> 
>                 if (i < (row.length - 1)) {
>                 csv += csvSeparator;
>                 }
>             });
>             });
> 
>             return csv;
>         }
> 
>         private toJson(data:TableData) {
>             let rows = [];
> 
>             data.data.forEach((row, j) => {
>             let obj = {};
> 
>             row.forEach((cell, i) => {
>                 obj[data.headers[i].data] = cell.data
>             });
> 
>             rows.push(obj);
>             });
> 
>             return JSON.stringify(rows);
>         }
> 
>         export(data:string, mimeTypeAndCharset:string, filename:string) {
>             let blob = new Blob([data], {
>             type: mimeTypeAndCharset
>             });
> 
>             if (window.navigator.msSaveOrOpenBlob) {
>             navigator.msSaveOrOpenBlob(blob, filename);
>             }
>             else {
>             let link = document.createElement("a");
>             link.style.display = 'none';
>             document.body.appendChild(link);
>             if (link.download !== undefined) {
>                 link.setAttribute('href', URL.createObjectURL(blob));
>                 link.setAttribute('download', filename);
>                 link.click();
>             }
>             else {
>                 data = mimeTypeAndCharset + ',' + data;
>                 window.open(encodeURI(data));
>             }
>             document.body.removeChild(link);
>             }
>         }
> 
>         exportCsv(table : HTMLTableElement, filename:string) {
>             let csv = this.toCsv(this.readTable(table));
>             this.export(csv,'text/csv;charset=utf-8;', filename);
>         }
> 
>         exportJson(table : HTMLTableElement, filename:string) {
>             let csv = this.toCsv(this.readTable(table));
>             this.export(csv,'application/json;charset=utf-8;', filename);
>         }
>     }
> ```
> Inject this service into your view, then get a reference to the PrimeNG table `@ViewChild(Table) resultTable;`, and bind the button click to
> 
> ```
>     exportCsv() {
>         let tableRef: ElementRef<HTMLTableElement> = this.resultTable.tableViewChild;
>         let table = tableRef.nativeElement;
> 
>         this.exportService.exportCsv(table, "Contracts.csv");
>     }
> ```
> also note that is is possible to exclude data and change how it is exported using the `exportable` attribute on the header columns and `exportValue` attribute on the cells.

Thanks it works perfect. :)

**Comment by EitanD1** [comment]
colin, great solution, but it exports only the current page, if paging enabled, or doesnt work on scrollable tables.
do you have a workarround for any of these situations?
thanx

**Comment by colinbull** [comment]
No not really, In this instance I'd probably just send a query off to the server, with a page size at least as large as the total result returned and get it to generate the report as a CSV / JSON whatever. This is probably more efficient in terms of resource usage as the results could be streamed directly from the DB when generating the report.

**Comment by satizkumar** [comment]
Is there any option to export download xl for <p-treeTable> ?

**Comment by madhav5589** [comment]
> Is there any option to export download xl for ?

What do you mean by export download xl?

**Comment by madhav5589** [comment]
> This is documented;
> 
> `Table can export its data in CSV format using exportCSV() method. By default whole data is exported, if you'd like to export only the selection then pass a config object with selectionOnly property as true. Note that columns should be dynamic for export functionality to work and column objects must define field/header properties.`

Can you please provide the link of this documentation?
Thanks.
