### ISSUE TITLE
TurboTable Template col width?

### ISSUE THREAD

**Issue by cyberrranger** [primefaces/primeng#5115]
in DataTable ich can change the width with "styleClass="col-button"" show https://www.primefaces.org/primeng/#/datatable/templating

bin in the new TurboTable i cant find a solution the works with https://www.primefaces.org/primeng/#/table/rowgroup (Subheader)

**Comment by asingh3886** [comment]
Need action buttons like delete,edit in the each row just like we had in https://www.primefaces.org/primeng/#/datatable/templating

**Comment by cagataycivici** [comment]
You can style the th, td or col elements.
