### ISSUE TITLE
p-Table - Custom filterMatchMode

### ISSUE THREAD

**Issue by Mimis40** [primefaces/primeng#5119]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
There are a defined list of filterMatchModes

**Expected behavior**
An extra filterMatchMode is added -- 'Custom' and the ability is given to provide a function to be called

**What is the motivation / use case for changing the behavior?**
With the new p-Table that has come out, it's now easier than ever to have custom inputs. One problem that I am running into though is that I have a date column formatted with a date pipe ( date | 'MM/dd/yyyy' ). I want users to be able to type into an input partial text and have the column be able to filter it. 

**Possible Implementation**
The ability to pass a function reference instead of a string to Table.filter. The function would have a parameter named rowData and would return a boolean to specify whether or not it should be added to the list of filtered items.

**Comment by ernespa** [comment]
In our project we need to filter by words that may contain characters with accent marks, so if you filter by the name "Lopez" it should include "López" in the filtered items. We could achieve that by replacing the special characters with normal ones in a custom filter. I think there is no other way to achieve this, correct me if I'm wrong.

**Comment by kevindrc** [comment]
can you share me the custom filter code to do your work?
I have the same issue facing and it can help me.

**Comment by yigitfindikli** [comment]
You can use [FilterService](https://primefaces.org/primeng/showcase/#/table/filter) for this.
