### ISSUE TITLE
Why is selecting tab not working in PrimeNG?

### ISSUE THREAD

**Issue by viveknuna** [primefaces/primeng#5120]
I'm trying to select Tab2 by default, But it's not working correctly, It's selecting both tabs and I can see both Hello and World on screen.

```
<p-tabView>
    <p-tabPanel header="Tab1">
        Hello
    </p-tabPanel>
    <p-tabPanel header="Tab2" [selected]="true">
        World
    </p-tabPanel>
</p-tabView>
```

I'm using primeng version 4.1.2.

Reference: https://www.primefaces.org/primeng/#/tabview

**Comment by cagataycivici** [comment]
Please update to latest PrimeNG to have this issue resolved.
