### ISSUE TITLE
Chips component "max" is limiting does not work

### ISSUE THREAD

**Issue by kartheininger** [primefaces/primeng#5123]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/xW9NA42ZuZix8hRIBnbE?p=preview
Enter something into the chip which is 4 or more characters long

**Current behavior**
Instead of limiting the number of entered items, it limits the length of a single item
The check regarding max and item.length seem to be wrong :) 
https://github.com/primefaces/primeng/blob/master/src/app/components/chips/chips.ts#L165

**Expected behavior**
With primeNG 4 it was limiting the number of items the user can enter in a chip component. And according to the documentation the "max"-attribute should be the "Maximum number of entries allowed."

**Minimal reproduction of the problem with instructions**
- Use chips component
- Set "max" to e.g. 4
- Try to enter something which is 4 or more charaters long

**Comment by amangupta17** [comment]
Is there a work around to fix this until you fix it in the next patch?

**Comment by kartheininger** [comment]
We did a quick&dirty workaround, attached a method to the onAdd-event and then just ignoring/removing the last element again:

`	if (this.chipsElements.length >= 5) {
			this.chipsElements.splice(5);
		}
`

**Comment by andreyRybchuk** [comment]
Is this fixed or not? For me, it still doesn't work.

**Comment by enzolry** [comment]
Still doesn't work 4 years later :/
