### ISSUE TITLE
TurboTable: make pResizableColumn a boolean operator

### ISSUE THREAD

**Issue by kareljan** [primefaces/primeng#5127]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
add pResizableColumn as an attribute to the column to make ik resizable. 
```
<th *ngFor="let col of columns" pResizableColumn>
  {{col.header}}
</th>
```

**Expected behavior**
make it accept a boolean, so the resize possibility can be set through code.
```
<th *ngFor="let col of columns" [pResizableColumn]="col.resize">
  {{col.header}}
</th>
```

**What is the motivation / use case for changing the behavior?**

It will make it possible to configure whether a column is resizable or not.
The same counts for pReorderableColumn and pSortableColumn

**Comment by cagataycivici** [comment]
Will check this.

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/issues/5243
