### ISSUE TITLE
TurboTable: rowStyleClass in p-table

### ISSUE THREAD

**Issue by deniskrafczyk** [primefaces/primeng#5129]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
In the deprecated p-datatable was a property named rowStyleClass to change the style for each rows. 
Something like this: 
`<p-dataTable [value]="cars" [rowStyleClass]="isRowValid" [editable]="true">`
Sadly there is no similar property for the new Turbotable. 

**What is the motivation / use case for changing the behavior?**
I want to highlight correct/incorrect customer inputs in turbotables.

* **Angular version:** 5.2.4
* **PrimeNG version:** 5.2.0

Is there any way in the current version to add a similar behaviour?

Thanks in advance, 
Denis

**Comment by marslan2037** [comment]
you can use style attribute for each <tr>

**Comment by deniskrafczyk** [comment]
Tanks a lot for your answer. But i dont think i can. 
Maybe i should explain it more. I want to validate the custom input in each row with the isRowValid function in the rowStyleClass attribute:
`<p-dataTable [value]="cars" [rowStyleClass]="isRowValid" [editable]="true">`

The function returns a styleClass like this:

`  isRowValid(rowData: any) {
   // do some validation stuff
   // return invaidInput if invalid
        return 'invalidInput';
  }`

css:
`tr.invalidInput > td {
	background-color: lightcoral;
}`

The style class from turboTable got this definition: 
> Inline style of the component.

So to my understanding this attribute styles the complete table, not each row itself.

I hope i explained it understandable.

Thanks a lot, cheers,
Denis

**Comment by kaustubhtalathi** [comment]
@deniskrafczyk: You should use ng-template so that you can set the ngClass attribute of each row. 

[https://www.primefaces.org/primeng/#/table/style](https://www.primefaces.org/primeng/#/table/style
)<p-table [columns]="cols" [value]="cars">
    <ng-template pTemplate="header" let-columns>
        <tr>
            <th *ngFor="let col of columns">
                {{col.header}}
            </th>
        </tr>
    </ng-template>
    <ng-template pTemplate="body" let-rowData let-columns="columns">
        <tr [ngClass]="rowData.year > 2010 ? 'new-car' : null">
            <td *ngFor="let col of columns" [ngClass]="rowData[col.field] <= 2010 ? 'old-car' : null">
                {{rowData[col.field]}}
            </td>
        </tr>
    </ng-template>
</p-table>

**Comment by deniskrafczyk** [comment]
yea. works like a charm. thank you very much for this.

**Comment by cagataycivici** [comment]
Yes, row class per row is pretty common so I've added a demo;

https://www.primefaces.org/primeng/#/table/style
