### ISSUE TITLE
Feature Request: Autocomplete event when scrolled to bottom

### ISSUE THREAD

**Issue by PeterVdBoogaard** [primefaces/primeng#513]
see http://forum.primefaces.org/viewtopic.php?f=35&t=46022

**Comment by Popieul** [comment]
Same problem.

**Comment by Korozu** [comment]
UP, I need this feature too, is it possible to work on it?

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.

**Comment by Popieul** [comment]
Can we have the name of the event for scroll loading ? Because i didn't see in the github source code the event for  lazyLoading on autoComplete component.
