### ISSUE TITLE
TurboTable refresh data resets current page 

### ISSUE THREAD

**Issue by pantonis** [primefaces/primeng#5130]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/3fCevmLlcgpYntK2Fo98?p=preview

**Current behavior**
When you have sorting enabled for a column and you are not in first page but in any other page (2,3,4 etc...) and data are refreshed, paginator immediately jumps in first page.
The same thing happens when you have something typed in global filter current page is not preserved

**Expected behavior**
Current page must be preserved

**Minimal reproduction of the problem with instructions**
Please run the plnkr above

**Comment by PiotrMistu** [comment]
Same situation in p-table any solutions !

**Comment by pantonis** [comment]
I already commited a fix but what declined by the owner of the repo

**Comment by burzum619** [comment]
I am dealing with this issue and have yet to find a solution. It is making this component virtually unusable when it comes to live data. My app has period polling every 5 seconds, and each time new data comes in, the page reverts to the first page. I've tried hacking my way around it, but no luck so far.

**Comment by burzum619** [comment]
@pantonis would it be possible for you to share your solution with me? I am eager to figure out a way around this behavior. Setting the "page" and "first" properties explicitly after updating my data object made no difference - it is always overwriten.

**Comment by pantonis** [comment]
@burzum619 What I did what to remove this.first = 0;

This:
```
 _filter() {
        this.first = 0;
......
```

becomes this:

```
 _filter() {
        ......
```

**Comment by cagataycivici** [comment]
Maybe we can add an option.

**Comment by pantonis** [comment]
also another problem with this behavior when data is refreshed is you are in page 4 and type something in global filter and then new data comes in filtering does not work

**Comment by cagataycivici** [comment]
You can solve this by adding [resetPageOnSort]="false", available in upcoming 5.2.5.

**Comment by pantonis** [comment]
@cagataycivici I will test it and let you know

**Comment by pantonis** [comment]
@cagataycivici This works partially. When set [resetPageOnSort]="false" and you sort, go topage 3 and then type something in the global filter, then clear filter,  table jumps to first page always

**Comment by stuarthallows** [comment]
If using lazy loading you can reload the page with;
    `tableX.onLazyLoad.emit(tableX.createLazyLoadMetadata());`
a bit hacky, but works.
