### ISSUE TITLE
Menubar active item not disappearing with OnPush strategy

### ISSUE THREAD

**Issue by parisgianluca** [primefaces/primeng#5131]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/qKSw3aLpixcJhv0WNBj8?p=preview

**Current behavior**
If the component that contains the `<p-menubar>` uses `ChangeDetectionStrategy.OnPush`, the active item of the menubar won't disappear after leaving the menu

**Expected behavior**
The active item should disappear after leaving the menu with mouse

* **Angular version:** 
5.2.3

* **PrimeNG version:** 
5.2.0

**Comment by dragosheroiu95** [comment]
Any method to solve this ?

**Comment by parisgianluca** [comment]
Still struggling with this problem
