### ISSUE TITLE
Turbotable scroll synchronization

### ISSUE THREAD

**Issue by felipebri23** [primefaces/primeng#5132]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://plnkr.co/edit/9evS0u?p=preview

**Current behavior**

![image](https://user-images.githubusercontent.com/28927144/36149842-a1159cfa-10c1-11e8-9210-c08f3ca04068.png)

**Expected behavior**

* **Angular version:** 5.2.X

* **PrimeNG version:** 5.2.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by rafa-as** [comment]
@felipebri23 this feature might be something similar that this https://github.com/primefaces/primeng/issues/5008 ?

**Comment by snavarropino** [comment]
It would be great to have this fixed. I was planning using this Turbotable...

**Comment by cagataycivici** [comment]
Duplicate;

https://github.com/primefaces/primeng/issues/5008
