### ISSUE TITLE
Add panelStyle and panelStyleClass to p-splitbutton

### ISSUE THREAD

**Issue by dhniels** [primefaces/primeng#5136]
im not sure about panelStyle but panelStyleClass was added to the p-calendar so you could assign a class to the datepicker panel that dropped down. it would be nice to be able to add and document panelStyle and panelStyleClass to the menu that appears with the Split Button as well.

**Comment by cagataycivici** [comment]
There is menuStyle and menuStyleClass for SplitButton, renamed like these since they are menus.
