### ISSUE TITLE
p-table scroll issue

### ISSUE THREAD

**Issue by kcsahoo** [primefaces/primeng#5139]
This is an issue with new Turbo table
When scroll height is chosen which is more than the actual height due to less no of rows, the scroll bar still shows.
Then the headers do not align with actual data rows.
This was an issue in datatable which was resolved.

**Comment by cagataycivici** [comment]
Unable to replicate, provide a plunrk please.

**Comment by bluelbow** [comment]
You can simply go to the example in the scroll section and zoom to 150% with Google Chrome:
https://www.primefaces.org/primeng/#/table/scroll

The issue, to me, is related to the scroll bar being there or not.

**Comment by akshetty9** [comment]
Any solution to fix this? Scroll bar should not appear when actual height is less than scroll height

**Comment by m-git-hub** [comment]
Hi,
I had this problem before, now I found one quick solution for this problem,
you can add below css into your main css file. Then you will not have this problem.

.ui-table-scrollable-header {
  overflow-y: scroll;
}

Hope it could solve your problem.
