### ISSUE TITLE
AOT build with rollup is failing

### ISSUE THREAD

**Issue by aamir1995** [primefaces/primeng#5140]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/Nxca3ovCbtvx9kpGds0q?p=preview

**Current behavior**

I am using [Angular-seed](https://github.com/mgechev/angular-seed) in my project, the project uses System.js and rollup as module bundler. when I try just regular build, it is working fine but the AOT build with Rollup causing this error. might this be the issue with primeng?
![image](https://user-images.githubusercontent.com/10736453/36200259-e4a2dd66-119d-11e8-8f67-bbacac215214.png)

**Expected behavior**

AOT build should work fine with primeng and systemjs/rollup.

**Minimal reproduction of the problem with instructions**

`git clone --depth 1 https://github.com/mgechev/angular-seed.git`
`cd angular-seed`
[Add-PrimeNG](https://github.com/mgechev/angular-seed/wiki/Add-PrimeNG)
run `npm run build.prod.rollup.aot`

* **Angular version:** 2.0.X

5x

* **PrimeNG version:** 2.0.X

5.2.0
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

* **Node (for AoT issues):** `node --version` =   
v8.9.1

**Comment by kaustubhtalathi** [comment]
Can you try using [Angular CLI](https://cli.angular.io/)?

**Comment by brian428** [comment]
The build system can't just be swapped out. Switching to a CLI build would probably take several weeks of refactoring. Anyone with a project older than a year or so is probably using a SystemJS-based build, because the CLI really only became a viable option in the last year or so. Before that, everyone (including the Angular team themselves) were recommending SystemJS.

**Comment by aamir1995** [comment]
Agreed with @brian428, switching to Angular-CLI is not a smart choice, it will be a really time-consuming process.

**Comment by kaustubhtalathi** [comment]
Agreed that it is a hassle but it is a one time effort which is worth. Anyways, I have one application which is using this seed and using PrimeNG. I'll take look if I can find the issue. One thing I noticed while comparing system js config file is that the primeng package is missing mapping to main. Mine looks like below:
`primeng: {
				main: 'primeng',
				defaultExtension: 'js'
			}`

**Comment by cagataycivici** [comment]
I don't think this is PrimeNG related, it seems a config issue on your end.
