### ISSUE TITLE
<p-growl> doesn't change color according to severity

### ISSUE THREAD

**Issue by flavioasrocha** [primefaces/primeng#5141]
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
 Background of the <p-growl> notification doesn't change(it's always white), although the icon change according to severity value.

**Expected behavior**
Notification background color changes according to severity value

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
Creating a notification service, where it can handle more than one notification at the same time, with different severity

**Please tell us about your environment:**

* **Angular version:** ^5.2.0X

* **PrimeNG version:** ^5.2.0X

* **Browser:** Chrome 63.0.3239.84 (x64)

 
* **Language:** "typescript": "~2.5.3"

**Comment by mlangwell** [comment]
We are experiencing the same problem with our growls 

`this._messageService.add({ severity: 'info', summary: 'Saved', detail: 'Settings have been saved.' });`

Shows yellow growls still but updates the icon

**Comment by mlangwell** [comment]
Looking through the CSS I do not see the classes that the growl is targeting for the different severity's.

```
ui-growl-message-info':msg.severity == 'info',
'ui-growl-message-warn':msg.severity == 'warn',
'ui-growl-message-error':msg.severity == 'error',
'ui-growl-message-success':msg.severity == 'success'
```

However, I do see:

```
ui-messages-info
ui-messages-warn
ui-messages-error
ui-messages-success
```

**Comment by upondeep** [comment]
Same issue here. Any solutions?

**Comment by memetz** [comment]
I have a similar problem, I'm using an rxjs Subject to assign messages to a growl component via a service. If If I do .next(ArrayOfMessages) and is only a single message severity is fine, but if I push multiple messages the severity would be the same as the first message.

**Comment by cagataycivici** [comment]
We could not see the issue, please provide a plunkr;

http://plnkr.co/edit/qtZi5lB3DjkNt7Kdivg9?p=preview

**Comment by memetz** [comment]
Hi Cagatay,
thanks for replying. I deleted the comment shortly after I posted it on the
issue coz I found out there was a bug in my code, so all good. Sorry for
any inconvenience and thanks for the hard work you are putting on.
cheers

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by upondeep** [comment]
K, I solved it by using css 
```
.ui-growl-message-success .ui-growl-item {
  background-color: #42A948;
}
```
etc

**Comment by chrispruitt** [comment]
I'm seeing this issue as well. No color change. Also seems to be missing some styling.

![image](https://user-images.githubusercontent.com/7242712/40733171-a64a5b98-63fa-11e8-8b5a-e64a5eb32b69.png)

**Comment by chrispruitt** [comment]
I'm seeing this issue as well. Icons change, but no color change. Also seems to be missing some styling within the item container for me.

![image](https://user-images.githubusercontent.com/7242712/40733373-0f710d4c-63fb-11e8-8dff-ed25643dab3d.png)

**Comment by chrispruitt** [comment]
Experiencing the same issue. No color change. Icons do change, but I also seem to be missing some css in the item container.

![image](https://user-images.githubusercontent.com/7242712/40733493-6392a52a-63fb-11e8-98cd-8e67bd06b646.png)

**Comment by cagataycivici** [comment]
As we're unable to replicate, if the issue still persists, please create a new ticket and provide a stackblitz link that demonstrates the problem;

https://stackblitz.com/github/primefaces/primeng-issue-template
