### ISSUE TITLE
Autocomplete does not emit onClear event with forceSelection

### ISSUE THREAD

**Issue by Lolash** [primefaces/primeng#5142]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

http://plnkr.co/edit/YEb5oLuiBEPFqugmWHxV?p=preview

**Current behavior**
Autocomplete with forceSelection option set on true does not emit onClear event, when value is cleared because of typing incorrect value.

**Expected behavior**
OnClear event should emit when value is cleared because of forceSelection option.

**Minimal reproduction of the problem with instructions**
Scenario in the exemplary plunkr:

1. Open console (F12) to be able to observe console.log.
2. Choose Volvo.
3. Delete last 'o' from 'Volvo' to have 'Volv'.
4. Deselect input field.
5. Value is cleared.
6. There is no console.log. (onClear event hasn't emitted)

**What is the motivation / use case for changing the behavior?**
To be able to watch for empty values properly.

* **Angular version:** 5.2.0

* **PrimeNG version:** 5.2.0

* **Browser:** [all]
 
* **Language:** [all]

**Comment by Strgy** [comment]
Same issue here. 
@Lolash as a workaround until this is fixed, i used (onClear) and (ngModelChange). I use onClear to do actions when user manually deletes everything from input field, and I use ngModelChange event to do whatever when object is null ( which happens when forceSelection is called).

**Comment by BootsThunderclap** [comment]
That workaround is working for me, and I'm just hopeful that the order of events will always send the right object (or non-existence of) to the function. In my template, I'm using (onSelect)="onSelectUser(selectedUser)" (onClear)="onSelectUser()" (ngModelChange)="onSelectUser()", and my implementation of onSelectUser() is:

`public onSelectUser(user?: UserSearchResult) {
if (user) {
      this.userForm.controls.Email.setValue(user.email);
      this.userForm.controls.UserName.setValue(user.userName);
    } else {
      this.userForm.controls.Email.setValue("");
      this.userForm.controls.UserName.setValue("");
    }
  }`

I think the only reason this works is because (onSelect) is firing after (ngModelChange), but I'm not sure that will always be reliable.

**Comment by florentL** [comment]
I reproduced the same behaviour as explained by @Lolash with the last version of primeNg (v5.2.2).

The workaround is not working everytime for me. It seems to work randomly.

Here my scenario (for not multiple mode):
- enter a valid value by selecting one suggestion from the autocomplete,
- remove one character,
- hit the tab button

This scenario will not trigger ngModelChange all the time.
