### ISSUE TITLE
Turbo Table Frozen Scroll Columns Misaligned, Scrollbar Margin Missing

### ISSUE THREAD

**Issue by JacobSiegle** [primefaces/primeng#5143]
**I'm submitting a ...**  (check one with "x")
bug report

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/YIXMm1SMUxmGpHTA5ZOu?p=preview

**Current behavior**
Frozen table columns with scroll don't align as in 5.2.0-rc.2

**Expected behavior**
Columns align

**Minimal reproduction of the problem with instructions**
Load the plunker which is on 5.2.0-rc.2.
Click the turbo table button.
Scroll to the end of the table and see the the columns align.

Go into systemjs.config.js and change to 'npm:primeng@5.2.0'
Click the turbo table button.
Scroll to the end of the table and see the the columns don't align.

**Comment by JacobSiegle** [comment]
This seems patched in the newest 6.0.0-SNAPSHOT. Will confirm on release.

**Comment by cagataycivici** [comment]
Glad to hear.
