### ISSUE TITLE
DataTable - custom emptymessage not workding

### ISSUE THREAD

**Issue by avarndell** [primefaces/primeng#5146]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/Nxca3ovCbtvx9kpGds0q?p=preview

**Current behavior**

 <p-dataTable [value]="userInfo.userOrders" responsive="true" >
            <p-column field="orderId" header="Order #"> </p-column>
            <p-column field="orderStatus" header="Order Status"></p-column>
            <p-column field="createdDate" header="Order Date" sortable="true">
                <ng-template let-col let-createdDate="rowData" let-ri="rowIndex" pTemplate="body">
                    <span>{{createdDate[col.field] | date: 'MM/dd/yyyy'}}</span>
                </ng-template>
            </p-column>
            <ng-template pTemplate="body" *ngIf="userInfo.userOrders.length==0">
                No Orders or You are not Logged In
            </ng-template>
        </p-dataTable>
**Expected behavior**

The "No Orders or You are not Logged In" is not showing.  Instead No records found.
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
windows 7

* **Angular version:** 2.0.X
angular 5.2.4

* **PrimeNG version:** 2.0.X
Version 5.2.0

* **Browser:**
 all
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
DataTable is deprecated and not maintained anymore, please consider migrating to p-table instead.
