### ISSUE TITLE
Primeng Calendar stopped formatting with columns

### ISSUE THREAD

**Issue by arambrosius** [primefaces/primeng#5147]
**I'm submitting a ...**
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
![image](https://user-images.githubusercontent.com/35042830/36222296-887dc3be-1186-11e8-82f3-a72ec2c37eff.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/35042830/36222260-71a2f434-1186-11e8-941d-55808d92a34a.png)

**Minimal reproduction of the problem with instructions**
 <p-calendar [(ngModel)]="value" [inline]="true"></p-calendar>

* **Angular version:** 5.2.5

* **PrimeNG version:** 5.2.5

* **Bootstrap version:** 4.0.0

* **Browser:** Chrome

I noticed this happened once I upgraded to bootstrap 4.

**Comment by cagataycivici** [comment]
I think there is an issue with your configuration, unable to replicate the problem. Provide a plunkr if it helps.
