### ISSUE TITLE
Add demo for expandable row groups

### ISSUE THREAD

**Issue by yasin-mansour** [primefaces/primeng#5148]
### 
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
There is no expandable row groups support in the new turbo Table

**Expected behavior**
Since DataTable marked as deprecated in the last release, I would like to have a support for expandable row groups in the turbo Table, so I can easily migrate from DataTable to turbo Table.

**Please tell us about your environment:**

* **Angular version:** 5.0.0

* **PrimeNG version:** 5.2.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by ivijan** [comment]
+1 for implementation of expandable row groups!
