### ISSUE TITLE
filterGlobal on TurboTable not including all possible rows

### ISSUE THREAD

**Issue by Vendium** [primefaces/primeng#5149]
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
TurboTable -> filterGlobal
A search on "s" does not show the row with column value "es"

**Expected behavior**
Show the row with colum value "es"

**What is the motivation / use case for changing the behavior?**
Bug

**Please tell us about your environment:**
Windows, Angular CLI 1.6.8

* **Angular version:** 
5.2.4

* **PrimeNG version:** 
5.2.0

* **Browser:**
Tested at Chrome

**Comment by ginobili** [comment]
I'm also having this issue with Turbotable and global search.

**Comment by mousedown** [comment]
The global filter in p-table is a huge step backwards from turboTable's predecessor. Appears to be no change in 5.2.1

**Comment by cagataycivici** [comment]
Hi guys, we can't replicate at;

https://www.primefaces.org/primeng/#/table/filter

Any chance for a plunkr or a scenario we can check online?

**Comment by mousedown** [comment]
Can't speak for  Vendium , but Global filter is working as intended for me.  Thanks cagataycivici.

**Comment by Vendium** [comment]
It seems that we only have printed the value but not added it to the searchable dataset so it was an error on our side

**Comment by cagataycivici** [comment]
Glad to hear.
