### ISSUE TITLE
Confirm dialog

### ISSUE THREAD

**Issue by lpenet** [primefaces/primeng#515]
A small, but handy feature found in PrimeFaces that I would like to find in PrimeNG is the confirmDialog.

http://www.primefaces.org/showcase/ui/overlay/confirmDialog.xhtml

**Comment by cagataycivici** [comment]
UI part is simple but do you mean global confirm functionality as well, that sounds tricky a bit.

**Comment by lpenet** [comment]
Yep, I mean that. The way p:confirm works with p:commandButton, for instance, is quite handy.

**Comment by cagataycivici** [comment]
This is available for some time, so closing.
