### ISSUE TITLE
Sorting a List with Comparator breaks header sorting in datatable

### ISSUE THREAD

**Issue by protonbart** [primefaces/primeng#5150]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/Nxca3ovCbtvx9kpGds0q?p=preview

**Current behavior**

Im sorting a List in java code when returnign a list to a datatable, the data loads as sorted in java method in bean but clicking on the dtatabale headers per column do not work anymore. 
Also tried using sortMode="Multiple"

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
Not working as expected for sorting data in a datatable

**Please tell us about your environment:**
Windows, Eclipse

* **Angular version:** 2.0.X

* **PrimeNG version:** 4.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Firefox and chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
DataTable is deprecated and not maintained anymore, please consider migrating to p-table instead.
