### ISSUE TITLE
ng-invalid keeps set in calendar when manually inserted date

### ISSUE THREAD

**Issue by hrestrepop** [primefaces/primeng#5152]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

![](https://image.ibb.co/fFVw6S/p_calendar.gif?raw=true)

**Current behavior**

When I manually change date year the p-calendar component keeps the class `ng-invalid`, thus this causes issues if you're using validations.

**Expected behavior**

The `ng-invalid` class should appear only if the inserted date is invalid no matter what the input method is (typing, selection from overlay etc).

**Please tell us about your environment:**

* **Angular version:** 4.3.1

* **PrimeNG version:** 4.1.3

* **Browser:** Chrome 64.0.x

 
* **Language:** TypeScript 2.3.4

* **Node (for AoT issues):** `node --version` =  v8.4.0

**Comment by Merve7** [comment]
Please try with PrimeNG 5.2.4. If the problem still exists,please create a plunker example or send your code.
http://plnkr.co/edit/qtZi5lB3DjkNt7Kdivg9?p=preview
