### ISSUE TITLE
TreeTable: onNodeSelect and onRowDblclick not working togheter

### ISSUE THREAD

**Issue by andreeapNRO** [primefaces/primeng#5155]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
I want to add a TreeTable into my project and i need both events: 
- onNodeSelect - to show a menu button and a text inside a specific column when the row is selected.
- onRowDblclick - to open the details page of that element
Only _onNodeSelect_ event is always fired (also on double click).

**Expected behavior**
The onRowDblclick should fire when double clicking on the row/node (not _onNodeSelect_)

**Minimal reproduction of the problem with instructions**
<p-treeTable #tree [value]="items" selectionMode="multiple" [(selection)]="selectedItems" (onNodeSelect)="onNodeSelect($event)" 
  (onRowDblclick)="onRowDblClick($event)" >
</p-treeTable>

* **Angular version:** 5.0.0
* **PrimeNG version:** 5.2.0-rc.2

**Comment by cagataycivici** [comment]
TreeTable will be reimplemented so not accepting issues for the current one.

**Comment by Rj1427** [comment]
try to use selectionMode="single" on p-treeTable
