### ISSUE TITLE
DataGrid p-footer display glitch

### ISSUE THREAD

**Issue by TheRealFenrir** [primefaces/primeng#5156]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/wYNc6cJclbRoON8lHqHX?p=preview

**Current behavior**
The footer is displayed with rounded corners on top, like a header.

**Expected behavior**
The footer should have rounded corners on the bottom.

**Minimal reproduction of the problem with instructions**
Make a DataGrid with a p-footer.

**What is the motivation / use case for changing the behavior?**
Correct the display of the footer.

**Comment by cagataycivici** [comment]
Merged the PR.
