### ISSUE TITLE
Autocomplete readonly and forceSelection not work on multiple mode

### ISSUE THREAD

**Issue by zeatan** [primefaces/primeng#5159]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/4uaLxlmSZEPfIZoKVcEM?p=preview

**Current behavior**

Autocomplete readonly and forceSelection not work on multiple mode
(On single mode, These work fine.)

**Expected behavior**

readonly  or forceSelection  works fine on multiple mode, as same as on single mode.
 
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.2.0

* **PrimeNG version:** 5.2.2

* **Browser:** all 

* **Language:** TypeScript 2.6.2
 
* **Node (for AoT issues):** `node --version` =   v6.13.0

**Comment by Merve7** [comment]
forceSelection fixed in https://github.com/primefaces/primeng/issues/5498
