### ISSUE TITLE
DataTable emptymessage template not working

### ISSUE THREAD

**Issue by MarcOne68** [primefaces/primeng#5160]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
emptymessage template not working

**What is the motivation / use case for changing the behavior?**
There is a bug in TableBody HTML Template

        <tr *ngIf="dt.isEmpty()" class="ui-widget-content ui-datatable-emptymessage-row" [style.visibility]="dt.loading ? 'hidden' : 'visible'">
            <td [attr.colspan]="dt.visibleColumns().length" class="ui-datatable-emptymessage">
                <span *ngIf="!dt.emptyMessageTemplate">{{dt.emptyMessage}}</span>
                <ng-template *ngIf="dt.emptyMessageTemplate">
                    <ng-container *ngTemplateOutlet="dt.emptyMessageTemplate"></ng-container>
                </ng-template>
            </td>
        </tr>

The **&lt;ng-template&gt;** tag must be replaced with **&lt;ng-container&gt;**

**Comment by VDubber** [comment]
I am run into this issue as well. Please fix!

**Comment by bandedos** [comment]
I also have problems with this. Please fix it!

**Comment by cagataycivici** [comment]
DataTable is deprecated, please use p-table instead.
