### ISSUE TITLE
drag and drop two browser

### ISSUE THREAD

**Issue by allarth** [primefaces/primeng#5161]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Expected behavior**
[http://embed.plnkr.co/JbG8Si](http://embed.plnkr.co/JbG8Si)

**What is the motivation / use case for changing the behavior?**
If i open this example in two browser i can drag item between two browser. Is possible
replicate in Prime NG?

**Comment by cagataycivici** [comment]
Please use forum for questions.
