### ISSUE TITLE
Firefox / IE 11 toolbar with splitButton issue

### ISSUE THREAD

**Issue by cyberrranger** [primefaces/primeng#5162]
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

https://www.primefaces.org/primeng/#/toolbar

**Minimal reproduction of the problem with instructions**
on left side Mozilla Firefox (current Version)
on right side Google Chrome (current Version)

![fehler saas](https://user-images.githubusercontent.com/21671762/36308255-15cf99e6-1320-11e8-92b5-a356efdcd246.png)

**Comment by reimersjc** [comment]
This also affects IE 11. Safari (11.0.3) is ok.

**Comment by cyberrranger** [comment]
> This also affects IE 11. Safari (11.0.3) is ok.
i update the topic
