### ISSUE TITLE
Could onSort happen after updateDataToRender

### ISSUE THREAD

**Issue by orsolli** [primefaces/primeng#5164]
Why does onSort invoke before the data to render is updated? Would it be a problem to put the `onSort.emit` after `updateDataToRender` outside of the `if` clause?

https://github.com/primefaces/primeng/blob/b3e3c453be27aed3db0116daaafbbacaccd6582e/src/app/components/datatable/datatable.ts#L1214-L1223

Suggested change:
```
        }
        
        this.updateDataToRender(this.filteredValue||this.value);
        this.onSort.emit({
            field: this.sortField,
            order: this.sortOrder,
            multisortmeta: this.multiSortMeta
        });
    }
```

**Comment by cagataycivici** [comment]
DataTable is deprecated, please use p-table instead.
