### ISSUE TITLE
DataTable exported CSV save as defaults to .txt instead .csv

### ISSUE THREAD

**Issue by KGJava** [primefaces/primeng#5165]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

https://www.primefaces.org/primeng/#/datatable/export

**Current behavior**
1. Go to primeng datatable export showcase(https://www.primefaces.org/primeng/#/datatable/export)
2. Click on All data export. Csv file is opened in Excel.
3. In the opened excel file, click on File and then save as.
4. Save window opens and default file type selected in file type drop down is Unicode Txt(.txt)

**Expected behavior**
1. Go to primeng datatable export showcase(https://www.primefaces.org/primeng/#/datatable/export)
2. Click on All data export. Csv file is opened in Excel.
3. In the opened excel file, click on File and then save as.
4. Save window opens and default file type selected in file type should be CSV.

**Minimal reproduction of the problem with instructions**
1. Go to primeng datatable export showcase(https://www.primefaces.org/primeng/#/datatable/export)
2. Click on All data export. Csv file is opened in Excel.
3. In the opened excel file, click on File and then save as.
4. Save window opens and default file type selected in file type drop down is Unicode Txt(.txt)

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** All version after 2.0

* **PrimeNG version:** 5.2.0-rc.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All.
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
DataTable is deprecated, please use p-table instead.
