### ISSUE TITLE
PrimeNG emptyMessage=" " attribute for datatable is not found.

### ISSUE THREAD

**Issue by Sarvesh19** [primefaces/primeng#517]
<p-dataTable  #datatable [value]="jobData" [rows]="20" [paginator]="true"
		[responsive]="true" emptyMessage="No Record Found"
		selectionMode="single" columnResizeMode="expand" (onPage)="onPageChanged($event)" >
<p-column expander="true" styleClass="iw-chevron-right-icon"></p-column>
		<p-column field="finOrVin" styleClass="vinfin" header="header" sortable="custom" (sortFunction)="sort($event)">
		<p-column field="state"  styleClass="status" header="Status"  sortable="custom" (sortFunction)="sort($event)">
		</p-column>
</p-dataTable>

**Comment by cagataycivici** [comment]
This attribute doesn't exist, have you seen it documented somewhere?
