### ISSUE TITLE
p-dataTable scrollheight in % wrong calculation 

### ISSUE THREAD

**Issue by Riclas1** [primefaces/primeng#5175]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
After updating Primeng from 4.1.2 to 5.2.0 our Table height not working any longer as expected.
Our Code is setting the property with % to set the value related to the parent element height and to keep the table responsive for page height changes. 
Now after Fix #1905 the table scrollheight seems to be calculated. After a little debugging it seems the table height in px is different as before. And it is not updating anymore if the page height is changing.

Before update the version tabelheight in devtools 839px after 100px

**Expected behavior**
The table should be shown if we use it with 80% scrollheight 80% from parent-element height. Of course the table scrollheight should also change if the parent element height is changing.

**Minimal reproduction of the problem with instructions**
<p-table [value]="mspatches"  [scrollable]="true" scrollHeight="80%">

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows 7, node.js server

* **Angular version:** 4.2.4
System.js 0.19.39

* **PrimeNG version:** 5.2.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [Typescript ES5]

* **Node (for AoT issues):** `node --version` = non

**Comment by cagataycivici** [comment]
DataTable is deprecated and not maintained anymore, please consider migrating to p-table instead.

**Comment by hughanderson4** [comment]
@cagataycivici  Please re-open it, and change the title.  Although the title says dataTable, the content of the bug report is about p-table and we have this same (serious) problem in 5.2.0 when using p-table.

**Comment by hughanderson4** [comment]
@cagataycivici nevermind, I see that @brian428 has already opened an issue for it with a demo Plunkr in [5235](https://github.com/primefaces/primeng/issues/5235)
