### ISSUE TITLE
TurboTable: When selectionMode=multiple, can't select by checkbox

### ISSUE THREAD

**Issue by lusid** [primefaces/primeng#5179]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
When selectionMode="multiple" is set on p-table, you can select a row by clicking the row and you can deselect it by clicking the row or the checkbox, but you can't select the row using the checkbox.

**Expected behavior**
You should be able to select a row by clicking the checkbox or the entire row.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/gO4f2bLzGLPhg9k0im3s?p=preview

**What is the motivation / use case for changing the behavior?**
This functionality works in the old p-dataTable component.

**Comment by lusid** [comment]
As a side note, the sample Plunkr you tell people to use in your issue tracker includes the import of TableModule on line 66, but I had to add it to the imports on line 137. Caused me some grief when I went to try to repro it for you.

**Comment by mousedown** [comment]
I've also seen this 

https://github.com/primefaces/primeng/issues/5262

**Comment by mousedown** [comment]
.. so I amended Table.js to have the additional check for checkbo. I don't need the use case of selecting the row by the row. I have teh checkbox for that. 

<img width="884" alt="screen shot 2018-03-05 at 14 19 32" src="https://user-images.githubusercontent.com/491789/36979797-748e4690-2080-11e8-90ed-5e8abc07b7a2.png">

**Comment by mousedown** [comment]
@cagataycivici  This seams related https://github.com/primefaces/primeng/issues/5229 Feature Req. I assumed this was a bug. They seam related - I needed to hack my version to move past. Are you able to advise please?

**Comment by cagataycivici** [comment]
Will review for 5.2.4.

**Comment by yonatanayalon** [comment]
A simple CSS solution that worked for me: 

in global **style.css**:

`.ui-chkbox {
  pointer-events: none;
}`

**Comment by arjendevries** [comment]
Is this issue that you can't actually click on the checkbox, but on the rest of the row?  Strangely enough when i removed selectionMode="multiple" it behaved as expected.  I could click only on the checkbox to select my row, but not anywhere else, which is what I wanted.

**Comment by marslan2037** [comment]
i have same issue, i need click on anywhere on row and checkbox, but its not working

**Comment by mousedown** [comment]
@arjendevries - Yes, that's the one. I actually wanted multiple tho. 

yonatanayalon's fix confirmed. thank you

**Comment by cagataycivici** [comment]
This is expected behavior because the table in plunkr has row selection and checkbox selection enabled which conflicts, you should not used them both at the same time since they are alternatives.

**Comment by marslan2037** [comment]
@cagataycivici i need both at the same time :(

**Comment by yonatanayalon** [comment]
You can differentiate and know you clicked a checkbox via the current event information:

> <p-table ... (onRowSelect)="onRowSelect($event)" .../>
> 
>   onRowSelect(asset) {
>     if (event.target['nodeName'] !== "P-TABLECHECKBOX") {
>       console.log("clicked on a Checkbox")
>     }
> else {
> console.log("clicked on a Row")
> }
>   }

**Comment by marslan2037** [comment]
@yonatanayalon what is nodeName here ?

**Comment by yonatanayalon** [comment]
@marslan2037 Sorry for that - look at my updated comment

**Comment by ZergHunter3000** [comment]
@cagataycivici If you're going to claim they should not be used at the same time, then please update your documentation to reflect this here: https://www.primefaces.org/primeng/#/table/selection

Includes the following code for checkbox selection:

![image](https://user-images.githubusercontent.com/2403364/39632596-83016fa4-4f83-11e8-90e9-df66b211ecb3.png)


Wherein which `[pSelectableRow]="rowData"` is preventing the selection of the checkbox in your checkbox example.

**Comment by bkoukoori** [comment]
how to make all the checkboxes selected on page load?

**Comment by bkoukoori** [comment]
how to make all the checkboxes selected on page load?

**Comment by niltonjacintho** [comment]
> A simple CSS solution that worked for me:
> 
> in global **styles.css**:
> 
> `.ui-table-tbody .ui-chkbox { pointer-events: none; }`
> http://plnkr.co/edit/ByEdALuiKJgQfiN7hVQy?p=preview

PERFECT!!
