### ISSUE TITLE
Typo in Documentation of InputMask Demo Documentation

### ISSUE THREAD

**Issue by davisb10** [primefaces/primeng#5182]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

Input Mask Documentation states:
`import {InputMaskModule} from 'primeng/inputmas';`

**Expected behavior**

Should be:
`import {InputMaskModule} from 'primeng/inputmask';`

**Comment by cagataycivici** [comment]
Fixed already.
