### ISSUE TITLE
p-tabMenu should specify item ID attribute

### ISSUE THREAD

**Issue by fibinger** [primefaces/primeng#5184]
**I'm submitting a ...
```
[*] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When tab menu item is a router link - ID attribute is not set (as specified in menu configuration). 

**Expected behavior**
It should work exactly as in non-router link case.

The fix is simply moving the attribute also to the other *ngIf case:

![image](https://user-images.githubusercontent.com/1809787/36439667-e6196bfe-166d-11e8-8f74-d48eeba1b0f0.png)

**Comment by angelasrc** [comment]
When the fix for this bug is planned?

**Comment by cagataycivici** [comment]
5.2.5.
