### ISSUE TITLE
Dropdown Should select item when typing

### ISSUE THREAD

**Issue by bohms27** [primefaces/primeng#5185]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr**
http://plnkr.co/edit/WPpOeYlmfmRIklspq7NT?p=preview

**Current behavior**
Dropdowns do not allow typing to select items like a normal html select does. Filtering helps, but it still does not select a default for you when starting to type

**Expected behavior**
Dropdowns should allow typing to select items, and default to the first item of that letter. For instances if I have Ab, Ac, Ad, Bb, Bc in a dropdown as options, I should be able to type Ac and it picks that one for me, like a normal select html dropdown would. When using filters, it filters it down, but I still have to do another mouse click or use arrow keys to select which one. I would love for it to automatically select and set it for me. 

**Minimal reproduction of the problem with instructions**
see Plunker

**What is the motivation / use case for changing the behavior?**
User suggestion to minimize the amount of clicks required to perform their job. Our users operate quickly and any extra clicks or key strokes hinder their production. 

**Please tell us about your environment:**
N/A

* **Angular version:** 5.0.5

* **PrimeNG version:** 4.3.0

* **Browser:** all
 
* **Language:** all

* **Node (for AoT issues):** n/a

**Comment by jakob-bebop** [comment]
+1

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/issues/873
