### ISSUE TITLE
Support table style class for TurboTable (like 'tableStyleClass' in DataTable)

### ISSUE THREAD

**Issue by thojo** [primefaces/primeng#5189]
**I'm submitting a ...**
```
[ ] bug report
[x] feature request/primeng/wiki/Roadmap
[ ] support request
```

**Current behavior**
_DataTable_ has an (undocumented?) property `tableStyleClass` for setting css classes on the table elements:
https://github.com/primefaces/primeng/blob/4e7aceb68f821599fa19d66297a8d73193409fea/src/app/components/datatable/datatable.ts#L565

**Expected behavior**
_TurboTable_ is missung such a property and I coudn't find any other (reasonable) possibility to achieve it.

**What is the motivation / use case for changing the behavior?**
Setting the css classes for the table element is very handy for custom styling, e.g. using the Bootstrap classes to cutomize the table style or applying diffenrent themes. With _DataTable_ this was relally straight forward. But because _DataTable_ is deprecated and I want to benefit from _TurboTables_ optimizations, it would be great to have this possibility, too.

* **PrimeNG version:** 5.2.0

**Comment by cagataycivici** [comment]
Why not add

```
.ui-table table {
   //your styles
}
```

**Comment by dragontheory** [comment]
Is there no simple API way to turn off table-striping?

**Comment by psini** [comment]
Can i make i pull request for that , i have the same issue

**Comment by psini** [comment]
Are there some problem with my pull request? if you give me some feedback can i adjust the pull.
Thank you
