### ISSUE TITLE
Quill.js problem with IE10 

### ISSUE THREAD

**Issue by Toktik** [primefaces/primeng#519]
It seems like quill.js does not load correctly in IE10.

Just open http://www.primefaces.org/primeng/#/editor, it complains with
`SCRIPT5022: Error: [Parchment] Invalid definition`

And afterwards
`ReferenceError: 'Quill' is undefined`

Cannot reproduce on quill.js demo.

**Comment by cagataycivici** [comment]
We'll check, thanks.

**Comment by Toktik** [comment]
No, it's only on IE10. If you could help understanding what's going on I can help with PR. I spent some time but didn't understand why it happens.

**Comment by gatapia** [comment]
Reproduced in IE10 only (have not tried 9 and works ok in 11)

**Comment by Diazbesjorge** [comment]
This is a critical issue for us as it is breaking our whole app in IE10. Do you think it will be possible to get a fix?

**Comment by gatapia** [comment]
Any update on this one?

**Comment by alaycock** [comment]
Quill has no intention of supporting IE10. 

https://github.com/quilljs/quill/issues/936

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.

**Comment by eassymo** [comment]
Yes, still persists. 
Ussing latest version of PrimeNG ~5.2.0
