### ISSUE TITLE
AutoComplete broken with ui-fluid

### ISSUE THREAD

**Issue by Lempkin** [primefaces/primeng#5190]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When in a ui-fluid div, the button with the arrow (which allow to unfold options) is sent to a new line
I saw defect #3629 but I still have the bug

I cannot reproduce my problem on plunker, seems that this is working : http://plnkr.co/edit/saywYpSnb0n0DQgoTEUA?p=preview
What I don't understand is, on my app, on the p-autocomplete I got this css applied : 
.ui-fluid p-autocomplete, .ui-fluid .ui-autocomplete, .ui-fluid .ui-autocomplete-input {
    width: 100%;
}
I can see it in source code v4.3.0 (https://github.com/primefaces/primeng/blob/4.3.0/src/app/components/autocomplete/autocomplete.css l 145)
But this css does'nt apply in plunker.

**Expected behavior**
input and button should be on the same line

**Please tell us about your environment:**

* **Angular version:** 
4.3.6

* **PrimeNG version:** 
4.3.0

* **Browser:** 
Chrome
 
* **Language:** 
TypeScript 2.1.5

**Comment by cagataycivici** [comment]
Try with 5.2.4 please.
