### ISSUE TITLE
Multiple iterations by clicking multiselect

### ISSUE THREAD

**Issue by FelipeCorso** [primefaces/primeng#5194]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

I made a fork of the repository to simulate the problem.
Is available in: https://github.com/FelipeCorso/primeng/tree/defect
Clone the repository and execute:
`yarn install`
`yarn start`

Go to the following page: http://localhost:4200/#/multiselect

**Current behavior**

With current behavior, when a multiselect is clicked it iterates four times for each list item. If I have more than one multiselect component on the page, it will be iterated four times over all items in all multiselect. This behavior can greatly compromise page performance, depending on the number of components and elements of each page. This is related to issues  #4781 and #3952. I think this problem is caused by excessive checking performed by the `isSelected(option.value)` method on the `multiselect.ts` file.

**Expected behavior**

The expected behavior is that each list item is not iterated four times and that the action performed on a multiselect does not interfere with other components of the same type available.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Because the performance of the application is being compromised when there are many items in the multiselect.

**Please tell us about your environment:**

WebStorm;
Yarn.

* **Angular version:** 5.2.5

* **PrimeNG version:** 5.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All browsers.
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

* **Node (for AoT issues):** `node --version` =   
v8.9.4

**Comment by cagataycivici** [comment]
You may try PUSH change detection so other components do not get change detection
