### ISSUE TITLE
Issue p-table multiselection (shift)+ filter

### ISSUE THREAD

**Issue by fplini** [primefaces/primeng#5195]
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

I found a strange behavor on p-table with selectionMode = multiple (by row) and filter.
If I filter a column and then try to select some rows with "shift" button, the selected rows are not aligned.
It seems to select rows by index.

Ex. I have 10 rows, after filter a column I got 5 rows.
Select first 3 rows, If I remove filter the selected rows aren't the same.

I past some screen to try to explain better.

[Link 1](https://postimg.org/image/5iqd938yz/4934fbd4/)

Another example:
[Original results](https://s17.postimg.org/whu84iay7/2018-02-21_15_03_16-_EASY.png)
[Filter results by column 1 and 2 and select with shift from first to last row](https://s17.postimg.org/de0wnty0f/2018-02-21_15_06_07-_EASY.png)
(Not all rows are selected, this is the first issue)

[At the end, remove all filters](https://s17.postimg.org/o0uptqbfz/2018-02-21_15_07_02-_EASY.png)
As you can see there are some selected rows that I never selected.

Plunkr: [http://plnkr.co/edit/UdHRtl0bVXFVt0GIWtwb?p=preview](http://plnkr.co/edit/UdHRtl0bVXFVt0GIWtwb?p=preview)
Step to verify issue:
1) Filter ID column with '2'
2) Trye to select from first row to last row with 'SHIFT'
3) Remove filter

I hope I Been clear

**Comment by cagataycivici** [comment]
Should be fixed in 5.2.4
