### ISSUE TITLE
Favicon icon

### ISSUE THREAD

**Issue by punnepallivenkat** [primefaces/primeng#5201]
Is favicon not displaying in IE browser?

**Comment by cagataycivici** [comment]
Not PrimeNG related.

**Comment by punnepallivenkat** [comment]
If came more data the canvas bar chart is not showing clearly..some unwanted black lines are occurring please find an attached screenshot.

https://user-images.githubusercontent.com/36731114/37386496-a2b4fde8-277e-11e8-979e-7ea389b82192.jpg
