### ISSUE TITLE
Lazy Loading changing page, when it's sorted

### ISSUE THREAD

**Issue by PiotrMistu** [primefaces/primeng#5202]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[x] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
When i made p-data table with Lazy everyting is working fine , but i have problem with one think.
When i add sorting server side my table always change me data for first 0 and page for 1.

<p-dataTable    [value]="gridData" [rows]="rows" [paginator]="true" [pageLinks]="3" [rowsPerPageOptions]="pageSize"
             [totalRecords]="totalRecords" [lazy]="true" (onLazyLoad)="loadCarsLazy($event)">
  <p-column field="_id" header="nazwa" [filter]="true"></p-column>
  <p-column styleClass="col-button" [style]="{'text-align':'center'}">
    <.ng-template let-car="rowData" pTemplate="body" >
      <button. class="btn-danger btn-sm" type="button">Remove</button>
    </ng-template.>
  </p-column>
</p-dataTable>

and my lazy 
 loadCarsLazy(e) {
    const page =  (Number(e.first) / Number(e.rows)) + 1;
    this.getContentTypeToTable(e.rows,  page, e.filters._id ); /// backEnd request 
  }

**Expected behavior**
Ofc i want to not change page for 1 and first on 0. I want to stay at this page and sort it.

**What is the motivation / use case for changing the behavior?**
For example i used Kendo UI and them it is working like i sad at expected behavior.

**Please tell us about your environment:**

* **Angular version:** 2.0.X
5.2.4

* **PrimeNG version:** 2.0.X
Latest 5.2.0Rc

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrom / Firefox
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.5.3

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
DataTable is deprecated and not maintained anymore, please consider migrating to p-table instead.
