### ISSUE TITLE
Ability to disable some of the items in <p-dropdown>

### ISSUE THREAD

**Issue by michael-veitch** [primefaces/primeng#5203]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[x ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
I know that this feature has been requested numerous times on this GitHub and it was even due to be released in version 4.1.1 but has seemed to have since disappeared.  
Is there any indication that this feature will be added?  I took a look at the roadmap and it doesn't seem to be apart of it. 

It would be nice if this feature could be added, I can think many use cases where there are disabled items in a dropdown list.

Thanks :)

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/issues/586
