### ISSUE TITLE
Allow for multiselect to be set programatically 

### ISSUE THREAD

**Issue by Venthe** [primefaces/primeng#5204]
**I'm submitting a ...**  (check one with "x")

- [x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap

**What is the motivation / use case for changing the behavior?**
I want to set default value for multiselect on page load and/or change it's value in other place of the app

**Comment by Venthe** [comment]
http://plnkr.co/edit/AY3EcfKS2yRtKmMc1qYR?p=info

Sample usage

**Comment by Venthe** [comment]
Possible mis-interpretation, see https://github.com/primefaces/primeng/issues/5267

**Comment by cagataycivici** [comment]
Issue is not clear.
