### ISSUE TITLE
Tooltip 'top' position out of bound

### ISSUE THREAD

**Issue by samized** [primefaces/primeng#5208]
Is there a reason why only left and right tooltip position try trough all options to avoid out of bound positions?
https://github.com/primefaces/primeng/blob/cec0efe9ebfbaf8bfcd3b782d119caaeecf580a7/src/app/components/tooltip/tooltip.ts#L219-L267

I would suggest to go like 'top' > 'bottom' > 'left' > 'right' and same for 'bottom'

**Comment by cagataycivici** [comment]
It is unlikely that screen is that small to try left and right so they are neglected.
