### ISSUE TITLE
TurboTable Keyboard Support

### ISSUE THREAD

**Issue by thenninger** [primefaces/primeng#5209]
**I'm submitting a ...**
```
[ ] bug report
[x] feature request
[ ] support request
```

**Expected behavior**
TurboTable supports accessibility features primarily keyboard support for sorting, filtering, and selecting; ideally it would be WCAG compliant.

Creating this issue again for the new TurboTable because open issues regarding this for the DataTable were closed like this one:
https://github.com/primefaces/primeng/issues/713

**Comment by cagataycivici** [comment]
The issue is too broad, please create separate tickets as the component is very complex with a lot of elements. For example, some of the elements already have keyboard support, we need more details with a separate issue ticket.
