### ISSUE TITLE
[feature request] would you please provider navigation component ?

### ISSUE THREAD

**Issue by bruceauyeung** [primefaces/primeng#521]
what i am talking about is similar like this : 
_current location：loc1 > loc2 > loc3_

it seems there is no navigation conponent in primeng.

would you please provide one?

version information:
"primeng": "1.0.0-beta.8",
"primeui": "4.1.12"

**Comment by GraemeSMiller** [comment]
Isn't that the breadcrumb http://www.primefaces.org/primeng/#/breadcrumb?

**Comment by cagataycivici** [comment]
Sounds like breadcrumb but do you want it to be integrated to the router or sth?

**Comment by redhatlinux10** [comment]
i found nav/breadcrumb round and round, but i didn't found it.
yes, this breadcrumb is what i'm looking for. it would be better if it can be integrated to router. for example:
if i jump to another component through `routerlink`, breadcrumb automatically be updated.
if i jump to another component through  `this.router.navigate()`, breadcrumb automatically be updated.

**Comment by redhatlinux10** [comment]
hi @cagataycivici , any process on integrating breakcrumb with router ?

**Comment by netstart** [comment]
Waiting....

**Comment by netstart** [comment]
Little ugly code, to help

`
export class BreadcrumbComponent implements OnInit, OnDestroy {

  @Input() model: MenuItem[] = [];

  private sub: any;

  constructor(private router: Router, private breadcrumbService: BreadcrumbService) {
    this.sub = this.router.events.subscribe((navigationEnd: NavigationEnd) => {
      let url: string = navigationEnd.urlAfterRedirects ? navigationEnd.urlAfterRedirects : navigationEnd.url;
      let arrUrl: string[] = url.split('/');

      this.model = [];
      arrUrl.forEach(key => {
        if(key){
          let partBreadCrumb = key.substr(0, 1).toUpperCase() + key.substr(1);
          this.model.push({label: partBreadCrumb});
        }
      });

    });
  }

  ngOnInit() {
    this.breadcrumbService.addAll(this.model);
  }

  itemClick(event: any, item: MenuItem) {
    if (!item.url || item.routerLink) {
      event.preventDefault();
    }

    if (item.command) {
      if (!item.eventEmitter) {
        item.eventEmitter = new EventEmitter();
        item.eventEmitter.subscribe(item.command);
      }

      item.eventEmitter.emit(event);
    }

    if (item.routerLink) {
      this.router.navigate(item.routerLink);
    }
  }

  ngOnDestroy() {
    this.sub.unsubscribe(); //In order to avoid memory leaks we can unsubscribe

    if (this.model) {
      for (let item of this.model) {
        if (item.eventEmitter) {
          item.eventEmitter.unsubscribe();
        }
      }
    }

  }

}
`

**Comment by cagataycivici** [comment]
Breadcrumb supports router with routerLink and routerLinkActive.
