### ISSUE TITLE
slideMenu keeps overflow scrollbar even on item lists smaller than viewportHeight

### ISSUE THREAD

**Issue by blackholegalaxy** [primefaces/primeng#5211]
## I'm submitting a ...
```
[x] bug report
[ ] feature request
[ ] support request
```

## Repro (click on language item to see the bug)
https://prime-slidemenu-bug.stackblitz.io

## Current behavior
 * When on slideMenu, if the second list is bigger than first one. 
 * And the second one is long enough to overpass the viewPortHeight so the scrollbar must appear.

**Then** going to the second list then back keep the scroller displayed even on the first (short) list.

Please note scrolling to the bottom of the second list make it worst: it keeps the scroll position between second and first list.

## Expected behavior
Scroller should disappear as soon as we are on a list with height smaller than viewPortHeight.

## Minimal reproduction of the problem with instructions

Have a slideMenu with child items list bigger than main items list.

## What is the motivation / use case for changing the behavior?
Proper expected behavior for good UX experience.

## Please tell us about your environment:

* **Angular version:** 5.2.0
* **PrimeNG version:** 5.2.0
* **Browser:** all
* **Language:** typescript

**Comment by cagataycivici** [comment]
Reverted due to aot errors

**Comment by blackholegalaxy** [comment]
@cagataycivici any progress on that problem?
