### ISSUE TITLE
Feature request: confirmation tooltip

### ISSUE THREAD

**Issue by blackholegalaxy** [primefaces/primeng#5213]
## I'm submitting a ...
```
[ ] bug report
[x] feature request (not in roadmap)
[ ] support reques
```

## Feature description

![confirmation-popup](https://user-images.githubusercontent.com/11064123/36645727-2bbf76e6-1a3b-11e8-95c9-051219c45905.PNG)

We would like to have a confirmation "tooltip". When we click on element, we then make a small popup with title and two buttons to confirm/cancel the action. It could be based on the same process than confirmDialog but not on modal.

The intent is to have a less intrusive confirmation than a window centered modal. So the confirmation can occur more "in place".

A good example can be the bootstrap confirmation plugin:  http://bootstrap-confirmation.js.org/

**Comment by cagataycivici** [comment]
I like it, will do.

**Comment by blackholegalaxy** [comment]
Any news on that @cagataycivici

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by KeithGillette** [comment]
For anyone finding this thread, I believe the requested functionality was implemented in the [ConfirmPopup component](https://www.primefaces.org/primeng/confirmpopup).
