### ISSUE TITLE
SplitButton buttons misaligned on Firefox

### ISSUE THREAD

**Issue by Golodnyi** [primefaces/primeng#5215]
Firefox 58.0.2 (64-bit)
![2018-02-26 09-38-18](https://user-images.githubusercontent.com/3991696/36650964-d377e6f0-1ad8-11e8-92ec-79e4492146ea.png)

**Comment by Svancara** [comment]
this is still there

**Comment by Svancara** [comment]
![obrazek](https://user-images.githubusercontent.com/109393/37093518-e35217ce-220f-11e8-850a-64e89316a6c0.png)
