### ISSUE TITLE
Customized Build

### ISSUE THREAD

**Issue by rdheepan** [primefaces/primeng#5217]
Can i make a customised build so that only things that are needed for Turbo Table can be built and used in my application?

**Comment by rohitsindhu90** [comment]
Hi

Yes , you can download the source from git and you can customize what ever
you want.

**Comment by rdheepan** [comment]
@rohitsindhu90 , Thank you!. But the issue with that is i need to know what are all mandatory folders to include and what to exclude. Is there any inbuild mechanism where i can select what i want the build can be downloaded from there like in bootstrap?

**Comment by JacobSiegle** [comment]
No, I don't think anything exists where you can optionally download a bundle like bootstrap. You have to build it yourself and include it in your project yourself. If you want to take things out just delete the files you don't want and the run the CLI to find all the refs to those files you need to remove.

**Comment by cagataycivici** [comment]
Use forum for questions please.
