### ISSUE TITLE
Please add a demo of filtering a TurboTable of static columns 

### ISSUE THREAD

**Issue by bomberblue07** [primefaces/primeng#5223]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
There is no demo in the showcase of TurboTable filters of static columns. I'm having trouble migrating over my existing DataTables to TurboTables because they have static columns, and only some of those columns have filters (not all of them, like in the showcase). I'd like a demo in the showcase so I know how it's done, please.

**Comment by bugreport0** [comment]
I also realized that turbo table with RowGrouping and Filtering is not working.
also when using RowGrouping the global filter is not working too..

**Comment by bomberblue07** [comment]
I did this myself by adding a [columns] to my table and specifying my columns dynamically in the template, but it references a static array in the component. This post in the PrimeNG forums provided a good basis example: 

https://forum.primefaces.org/viewtopic.php?f=35&t=54420
