### ISSUE TITLE
Shadow is not removed above use overlay

### ISSUE THREAD

**Issue by netstart** [primefaces/primeng#5225]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
```
Steps to reproduce the bug
1 - Open https://www.primefaces.org/barcelona-ng/#/
2 - Navigate to https://www.primefaces.org/barcelona-ng/#/overlays using menu home> components> Overlay
3 - Click in first image of the LightBox
4- Click back button from browser
5 - See, shadow is not removed and we don't use anything don't click in meny, buttons, etc.

* **Browser:** 
Chrome 64.0.3282.167 (Versão oficial) 64 bits

**Comment by cagataycivici** [comment]
Report at Barcelona-NG forum please, this is the tracker for PrimeNG.
