### ISSUE TITLE
Checkbox only way to select data

### ISSUE THREAD

**Issue by ochiers** [primefaces/primeng#5229]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
DataTable, TreeTable, ListBox, MultiSelect can be use in CheckBox selectionMode.
And to select a row, an option you can click everywhere on the row.

**Expected behavior**
That we have an attribut to specifies the enable way to select data, like the checkbox only.
So to select data, we must use the checkbox and not the row in a random way.

**What is the motivation / use case for changing the behavior?**
I use TriCheckBox, InputSwitch in the template of my TreeTable and on every change of them, the row is select or unselect.
I need them stay in the same state : selected.

Sorry for my english.

**Please tell us about your environment:**

Win7, Eclipse/ VS Code, Tomcat 9...

* **Angular version:** 4.3.6

* **PrimeNG version:** 4.3.0

* **Browser:** [all]

 
* **Language:** [TypeScript]

**Comment by cagataycivici** [comment]
If more users demand this behavior we'll re-evaluate, currently no plans to change the current behavior as it will add complexity. But if there is more demand, why not. We'll reopen if more users request it at forums and issue tracker. Thank you for the feedback.
