### ISSUE TITLE
Dialog becomes unusable after moving rapidly

### ISSUE THREAD

**Issue by julaudo** [primefaces/primeng#5231]
**I'm submitting a ...**
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/2CQQhZTmRuQDDwKCRPfW?p=preview

**Current behavior**
This is the official PrimeNG show case for Dialog (https://www.primefaces.org/primeng/#/dialog)
Click on "Show" to show the dialog. After moving the dialog to outside the parent (for example, over the chrome tab), the dialog keeps following the cursor event after releasing the mouse button. The dialog becomes unusable.

**Expected behavior**
When releasing the mouse button, the dialog should stop moving.

* **Angular version:** 4

* **PrimeNG version:** 5.2.0

* **Browser:** [all]
 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` = v6.11.0

**Comment by JacobSiegle** [comment]
If I release the dialog drag click out of window scope, then return the mouse back on screen the dialog stays attached to the mouse. Another click will release the dialog if it's stuck to the mouse from the previously mentioned action.

Doesn't sound exactly like what you're describing, can you confirm?

**Comment by julaudo** [comment]
I confirm it's not the bug I wanted to describe. I really couldn't release the dialog, but now I can't reproduce it

**Comment by asingh3886** [comment]
Yes. @julaudo is correct. I am facing the same issue.
