### ISSUE TITLE
max-height of  p-listbox  in p-dialog is ignored

### ISSUE THREAD

**Issue by janminarik** [primefaces/primeng#5232]
**Current behavior**

I have p-listbox in p-dialog. When I have more items than the height of a listbox property max-height is ignored and listbox height is not limited.

**Expected behavior**
Height of listbox will be equal max-height.

**Angular version:** 5.2.0

**PrimeNG version:** 5.2.0

**Browser**: Chrome Version 64.0.3282.186 (Official Build) (64-bit)

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/k2ThxfZn3DyLcS3tQnHb?p=preview

**Comment by cagataycivici** [comment]
Provide a plunkr please, I can't see the issue.

**Comment by janminarik** [comment]
@cagataycivici : http://plnkr.co/edit/k2ThxfZn3DyLcS3tQnHb?p=preview

**Comment by cagataycivici** [comment]
See

https://github.com/primefaces/primeng/issues/5291
