### ISSUE TITLE
Turbo Table sorting not working with date 

### ISSUE THREAD

**Issue by albamariana** [primefaces/primeng#5236]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Will provide a plunkr case ASAP 

**Current behavior**
Im using the new turbo table and I have an array of dates that is being sorted accordingly on my service, when I load it on the table the very first date its not in order, the rest seem to be ok, when I sort the table by the date it doesn't sort all dates as well.
**Expected behavior**
The table should be sorted in order by date after it comes from my service 

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**
Windows, Ubuntu

* **Angular version:** 2.0.X
Angular 5.0 version

* **PrimeNG version:** 2.0.X
Prime 5.2.0-rc.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** 
v6.9.2

**Comment by cagataycivici** [comment]
Unable to replicate locally, please create a new issue when the plunkr is ready so we can take a look.
