### ISSUE TITLE
After updating the primeng version 5.0.2 to primeng 5.2.0 Chart js(line chart) is not loading properly

### ISSUE THREAD

**Issue by sruthymoljoseph** [primefaces/primeng#5239]
After updating the primeng version 5.0.2 to primeng 5.2.0 Chart js(line chart) is not loading properly.
I have checked the chartjs source code. and i have observed only one change.

 **primeng 5.0.2 Chart js**
template: "\n <div>\n <canvas [attr.width]=\"width\" [attr.height]=\"height\"(click)=\"onCanvasClick($event)\"></canvas>\n </div>\n "

 **primeng 5.2.0 Chart js**
template: "\n  <div style=\"position:relative\" [style.width]=\"width\" [style.height]=\"height\">\n            <canvas (click)=\"onCanvasClick($event)\"></canvas>\n </div>\n    "

**Expecting behavior**

![image](https://user-images.githubusercontent.com/33513494/36839781-0126c386-1d69-11e8-8a5d-72f80d06e96d.png)

**Current behavior**
![image](https://user-images.githubusercontent.com/33513494/36839827-2254e5e2-1d69-11e8-8922-7271c7ae3ea9.png)

Can anyone help me for resolving this issue.

**Comment by dlaynes** [comment]
Use css:
`.my-special-div canvas { width: 100%; height: 100% }`

**Comment by sruthymoljoseph** [comment]
Thanks for the Reply. But still not working.
Parent div's height is 250px and width is 7000px. and for canvas i havent give any hight and width.
But dynamically canvas hight and width are adding as width: 300px and height: 150px.
Couldn't resolve the issue
@dlaynes : after adding the css to 100%, its behaving like below screenshot.

![image](https://user-images.githubusercontent.com/33513494/36884818-3a997bea-1e09-11e8-8420-05d0fc95e165.png)

**Comment by cagataycivici** [comment]
Doesn't seem to be an issue with showcase that runs on 5.2.

https://www.primefaces.org/primeng/#/chart/bar
