### ISSUE TITLE
p-dropdown doesn't work if given inside p-dialog

### ISSUE THREAD

**Issue by dsrvasanth** [primefaces/primeng#524]
simple p-dropdown doesn't work inside a modal dialog(p-dialog). Unable to select the element in the dropdown.

**Comment by cagataycivici** [comment]
Try setting autoWidth to false or giving a fixed width.

**Comment by dsrvasanth** [comment]
Additional details:

I have a get method which reads the static currencies list like below
get currencies():SelectItem[]{
        let ccyDropDown:SelectItem[] = [];
        Constants.CURRENCIES.forEach(ccy=>{
            ccyDropDown.push({label:ccy,value:ccy})
        })
        return ccyDropDown;
}

And i have p-dropdown as
<p-dropdown [options]="currencies" [(ngModel)]="baseCCY" [style]="{'width':'109px'}"></p-dropdown>

**Comment by NishantHadole** [comment]
Although bit late - **https://github.com/primefaces/primeng/issues/567#issuecomment-230944471**
