### ISSUE TITLE
p-inputMask  does not set fixed value +922?

### ISSUE THREAD

**Issue by junaidzubair10p** [primefaces/primeng#5240]
Following is prime input box with mask set to +922-999999999.

` <p-inputMask formControlName="phonNumber"
                                                     styleClass="form-control"
                                                     mask="+922-999999999"
                                                     placeholder="+966-xxxxxxxxx"></p-inputMask>`

When this input get focus, it display something like (+_22-_________). Here, how would I make 9 fixed value after plus (+) sign as it happens in case where other than 9 is supplied.
I want to make number nine (9) as fixed value. I am unable to make it fixed value.

**Comment by cagataycivici** [comment]
Please use forum for support requests.

**Comment by aminTiz** [comment]
There is for sure bug in this area. When you pass for example +922 pragmatically it shows under line but if user enters it by keyboard it works fine.

**Comment by prabugithub** [comment]
Is there any solution for this?
