### ISSUE TITLE
p-editor automatically gains focus when intializing model with data.

### ISSUE THREAD

**Issue by dafranklin** [primefaces/primeng#5244]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When i have a component with various form controls and an editor at the end of it, if i load data in my editor's ngModel when initializing the component, the editor automatically gains focus. 
This doesn't happen if the model is initialized  with an empty string. 

**Expected behavior**
Focus should either be on the first input or not on any controls at all. But it shouldn't be on the editor (which in my case is the last control at the bottom of the page).

**Minimal reproduction of the problem with instructions**
available plunker: http://plnkr.co/edit/n0nLuan8I2OuWM7yegmC?p=preview

What i see happening here : the page loads at the level of the p-editor instead of the top of the page.
If you go in the app.component.ts if you change the line: 
this.comment="focus should be on input above";
with 
this.comment="";
Then there is no problem.

I believe this must be related to quill somehow as this issue on quill-react perfectly describe my issue except i have it with primeng editor:
https://github.com/zenoamaro/react-quill/issues/317

**Please tell us about your environment:**
Windows 10.
Browsers: firefox quantum and latest chrome version
Angular : 5.2.4
Primeng: 5.2.0
Quill:1.3.5

**Comment by charlatan154** [comment]
Same issue here. I have four p-editor instances at the bottom of my view and the first one gets autofocus while view initializes.

**Comment by cagataycivici** [comment]
This seems to be related to the quill not PrimeNG.

**Comment by dafranklin** [comment]
What am i suppose to do? go to quill github and tell them I have a problem  using quill through another library? If I do that they'll just send me right back here...

**Comment by kandangit** [comment]
I am also having an issue with Quill. The editor gains focus when it has any value. 

I have a function that shows an alert in case the user unloads a page. It checks that the page form has changed, which is only true when any input gains focus. But with p-editor, this always happens as it gets focus by default.

**Comment by smitpsanghavi** [comment]
I tried this:
`<p-editor formControlName="SpecificationsAndConditions" [(ngModel)]="model.SpecificationsAndConditions" (onInit)="onEditorInit($event)">`

`private onEditorInit(event: any) {
event.editor.root.blur()
}`

The cursor is no more present in the editor window which means that blur() has worked. But the window has already scrolled to the editor area because I think it has executed the focus() before the blur() method.

Any help is appreciated.

**Comment by TravisS25** [comment]
My work around for this is to use viewchild and grab editor and use its writeValue function which doesn't auto focus but doesn't set value if using reactive forms so one must set it when they go to submit their form.

```
// .html
...
<p-editor></p-editor>
...

// .ts
@ViewChild(Editor, {static: false}) public editor: Editor
public form: FormGroup;

ngAfterViewInit(){
    this.editor.writeValue(value)
}

submit(){
    this.form.controls.editor.setValue(value);
    ...
}

```

Hope this helps someone

**Comment by EOussama** [comment]
> I tried this:
> `<p-editor formControlName="SpecificationsAndConditions" [(ngModel)]="model.SpecificationsAndConditions" (onInit)="onEditorInit($event)">`
> 
> `private onEditorInit(event: any) { event.editor.root.blur() }`
> 
> The cursor is no more present in the editor window which means that blur() has worked. But the window has already scrolled to the editor area because I think it has executed the focus() before the blur() method.
> 
> Any help is appreciated.

This one worked perfectly, thanks.

**Comment by Erlemorgaine** [comment]
We are still having this issue. It seems that it is possibly caused because the quill editor is used in this way:

`editor.dangerouslyPasteHTML(html);`

It seems that this could be fixed by changing to this:

`editor.setContents(editor.clipboard.convert(html));`

[https://github.com/zenoamaro/react-quill/pull/321#issuecomment-386888042](url)

Could this please be fixed?

**Comment by meistaiwan** [comment]
Erlemorgaine I'm not an expert on github but if this is closed could you create a new issue, focusing on the idea that it isn't strictly a quill issue but an issue with primeng's integration implementation with quill so it gets attention?
