### ISSUE TITLE
TurboTable Frozen columns and Virtual scroll bottom alignment

### ISSUE THREAD

**Issue by sky007** [primefaces/primeng#5245]
**I'm submitting a ...** 
```
[x] bug report
[ ] feature request
[ ] support request 
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/angular-abqgls?embed=1&file=app/app.component.ts

**Current behavior**
When you have a virtualscroll and the table has an horizontal scroll the last row of the body won't align with the frozen row on the bottom. 

![image](https://user-images.githubusercontent.com/1032882/36900059-05cd7ca4-1e22-11e8-9288-1afe0e7aaa81.png)

**Expected behavior**
The frozenbody rows aligns correctly with the body rows.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/angular-abqgls?embed=1&file=app/app.component.ts

**What is the motivation / use case for changing the behavior?**
Correct alignment for the user and the looks of the turbotable

**Please tell us about your environment:**
* **Angular version:** 5.X
* **PrimeNG version:** 5.2.0

* **Browser:** All

**Comment by wishnu2016** [comment]
Same Issue for me also.,Any solution ?

**Comment by sky007** [comment]
Haven't got any solution, but I know the cause of the disalignment. It's because the table has an position: absolute which ignores the padding-bottom: 17px that makes the alignment correct.

**Comment by sky007** [comment]
It's nice that the horizontal scroll is fixed, but I see there are some issue with when there is no horizontal scrollbar. I have updated the stackblitz on another fork.

In full browser:
[Full-Browser](https://turbotable.stackblitz.io/)

In edit mode:
[Edit Mode](https://stackblitz.com/edit/turbotable)
