### ISSUE TITLE
grouped p-dropdown value setting is not working using [(ngModel)]

### ISSUE THREAD

**Issue by ASK83** [primefaces/primeng#5246]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When using grouped p-dropdown the value cannot be set using ngModel.

**Expected behavior**
Whenever there is a predefined value linking the p-dropdown to a value the value should be set like the regular p-dropdown

**Minimal reproduction of the problem with instructions**
Here is the link I am showing the issue with grouped p-dropdown vs simple p-dropdown
http://plnkr.co/edit/RNHTvMjGuPXEgmpqC7hE?p=preview

**What is the motivation / use case for changing the behavior?**
It is a common use case to have default values for the dropdown that needs to be set.

**Please tell us about your environment:**

* **Angular version:** 2.0.X
@Angular 5.2.5

* **PrimeNG version:** 2.0.X
5.2.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All of them
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript
* **Node (for AoT issues):** `node --version` =   
8+

**Comment by cagataycivici** [comment]
Fixed via;

https://github.com/primefaces/primeng/issues/5080
