### ISSUE TITLE
Add support for max-height and max-width on ScrollPanel

### ISSUE THREAD

**Issue by bushybuffalo** [primefaces/primeng#5250]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

The ScrollPanel component needs fixed height and width in order to work.

**Expected behavior**

I would like to be able to set a max-height or max-width property, in order for its dimensions to be dynamic. This way, its size would fit its content, up to a max dimension where it would start scrolling.
This is the behaviour you can get with a standard browser scrollbar using . 

**Minimal reproduction of the problem with instructions**

We can get the expected behaviour with a standard browser scrollbar, by setting `overflow-y: scroll` along with `max-height: 200px` for example.
See http://plnkr.co/edit/52Wf63L24VVwJHbVOUrO?p=preview

**What is the motivation / use case for changing the behavior?**

I want to use ScrollPanel in a UI which is displayed over a map. This involves transparency, among over things. The user can interact with the map everywhere it is not covered by the UI.
Since the height of ScrollPanel needs to be fixed, some part of the map is remains visible (because I removed the ScrollPanel's background color) but the user cannot interact with it anymore, since it is now covered by the UI.
if the ScrollPanel had a dynamic height, this would not be an issue anymore.

**Please tell us about your environment:**

* **Angular version:** 5.1.3

* **PrimeNG version:** 5.2.0

* **Browser:** all

 
* **Language:** all

* **Node (for AoT issues):** `node --version` = 8.9.1

**Comment by mertsincan** [comment]
- Added max-height support to ScrollPanel 
- It works as expected with max-width:...px. Please check it.

**Comment by scurk1415** [comment]
How does this work exactly? I added max-height style to the scroll panel and it does not work

**Comment by dandohotaru** [comment]
Unfortunately it might work for static content but not for dynamic one. 
Please check [this stackblitz](https://stackblitz.com/edit/primeng-issues-scrollpanel-height) for a broader example detailing the issue with "primeng": "8.0.0"

**Comment by jotefer** [comment]
Wrapping `<p-scrollPanel/>` with `*ngIf` solves dynamic max-height problem.
