### ISSUE TITLE
Selecting a row with double click using TurboTable

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#5256]
Add pSelectableRowEvent to the directive so that users can switch between click and dblclick.

**Comment by asingh3886** [comment]
Thanks for this awesome feature. Though I am still not able to use this.
I am getting error "**ng:Can't bind to pSelectableRowDblClick, since isn't known property of tr**"


  <ng-template pTemplate="body" let-rowData let-columns="columns">
      <tr [pSelectableRowDblClick]="rowData">
        <td *ngFor="let col of columns">
          {{rowData[col.field]}}
        </td>
      </tr>
    </ng-template>
