### ISSUE TITLE
Turbo table - cannot expand row by clicking on it

### ISSUE THREAD

**Issue by tigrenok00** [primefaces/primeng#5257]
Hi,

In previous table I could expand the row using (onRowClick)="dtOrderDetails.toggleRow($event.data)" , however, this does not seem to work on p-table, only expansion with the expander icon.
Am I missing something?

Thank you

Angular version: 5
PrimeNG version: 5.2.0

**Comment by bossqone** [comment]
Turbo Table is more template oriented, so basically you can bind `click` event directly on your row.
For example:
```html
<p-table [columns]="cols" [value]="cars" [paginator]="true" [rows]="10">
    <ng-template pTemplate="header" let-columns>
        <tr>
            <th *ngFor="let col of columns">
                {{col.header}}
            </th>
        </tr>
    </ng-template>
    <ng-template pTemplate="body" let-rowData let-columns="columns">
        <tr (click)="onRowClick(rowData)"> <------ here you can attach click event listener
            <td *ngFor="let col of columns">
                {{rowData[col.field]}}
            </td>
        </tr>
    </ng-template>
</p-table>
```

**Comment by tigrenok00** [comment]
@bossqone Wow, the pRowToggler solution is really elegant and works perfectly. Thank you very much!

**Comment by michaelhalbig** [comment]
Hi, the new template solution is great - but I cannot expand a single row. I set rowExpandMode to single - but it still expands all rows. Also I do not understand why the dataKey needs to be set if I use row expansion? Are you storing all keys of the selection in a list? (I dont have a uniqe key for my records)
