### ISSUE TITLE
Clicking on checkbox too quickly in Listbox sometimes causes previously selected values to be deselected

### ISSUE THREAD

**Issue by z3d** [primefaces/primeng#5258]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When multiple selection with checkboxes is enabled in the ListBox, and we select some options using checkboxes, rapidly clicking on another option removes the previously selected options. It appears as if this happens if we click too quickly on an option after selecting a previous option (waiting a few seconds avoids the issue).

**Expected behavior**
Selecting options using checkbox should not deselect previous options, no matter how quickly the options are selected.

**Minimal reproduction of the problem with instructions**
Go to [https://www.primefaces.org/primeng/#/listbox] and choose the cities demo. Rapidly click on checkboxes to select cities. Occasionally, clicking on a city soon after clicking on another one, will deselect all previously selected cities

**What is the motivation / use case for changing the behavior?**
Bug. It should be possible to rapidly click on multiple Listbox checkbox options without losing the previously selected options..

**Comment by cagataycivici** [comment]
I'm unable to replicate.
