### ISSUE TITLE
Select event not triggered on p-calendar after entering the date using keyboard and losing focus without clicking the calendar.

### ISSUE THREAD

**Issue by pratiksanglikar** [primefaces/primeng#5265]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Here's the plunkr showing the issue.
http://plnkr.co/edit/mnPJJGtb7FMHvWGS2IuO?

**Current behavior**
After entering the date manually in the p-calendar, and losing focus without clicking on the date, the select event is not fired and the ngModel is not updated.

**Expected behavior**
After entering the date manually in the p-calendar, and losing focus without clicking on the date, the select event should be fired and new date should be in the ngModel.

**Minimal reproduction of the problem with instructions**
1. Enter the date in the datepicker manually (type it)
2. lose focus of the input without clicking the date.
3. Notice that the select event is not triggered.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.0.x

* **PrimeNG version:** 4.3.0

* **Browser:** 
Browser all
 
* **Language:** 
TypeScript 2.2

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
selectEvent is only fired when a date is selected with a mouse event, you need to use onBlur or onInput instead when dealing with an input.
