### ISSUE TITLE
Multiselect : UpdateLabel is not called when a selected item is removed programatically

### ISSUE THREAD

**Issue by graphicsxp** [primefaces/primeng#5267]
I declare the multiselect component as follow  

`<p-multiSelect [options]="myOptions" [(ngModel)]="myArray" [optionLabel]="'defaultLabel'" [dataKey]="'id'"></p-multiSelect>`

All works fine except if I programatically remove a selected item from myArray. By doing so, the item is correctly unchecked from the multiselect, however the selected labels are not refreshed. This is because the method UpdateLabel does not get called.

Could you fix this ?

**Comment by cagataycivici** [comment]
Unable to replicate, make sure you have a new reference of the selection property instead such as;

```
this.selectedCars1 = this.selectedCars1.filter((item, index) => index !== 0);
```

Above removes the first item from selection and label will be updated properly.
