### ISSUE TITLE
Add onHover to Charts

### ISSUE THREAD

**Issue by theunreal** [primefaces/primeng#5268]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
There is no onHover event for charts.

**Expected behavior**
onHover event is supported by Chart.js as described here: http://www.chartjs.org/docs/latest/general/interactions/events.html?h=click

**What is the motivation / use case for changing the behavior?**
Cover common chart usage

* **PrimeNG version:** 5.0.2

 
* **Language:** TypeScript 2.4.0

**Comment by mouradghafiri** [comment]
https://github.com/primefaces/primeng/blob/0c26a009a181e7d316f88b5f1ee08e9e5ecc32da/src/app/components/chart/chart.ts#L9

just add (mouseover)="onCanvasMouseOver($event)"

and implement onCanvasMouseOver function then  emit what you want as output of the componenet
@Output() onMouseOver : EventEmitter<any> = new EventEmitter();

onCanvasMouseOver(event) {
        if(this.chart) {
            let element = this.chart.getElementAtEvent(event);
            let dataset = this.chart.getDatasetAtEvent(event);
            if(element&&element[0]&&dataset) {
                this.onMouseOver .emit({originalEvent: event, element: element[0], dataset: dataset});
            }
        }
    }

if it works as you want, try to contirbute to PrimeNG ;)
