### ISSUE TITLE
autocomplete keyboard nav autoscroll

### ISSUE THREAD

**Issue by Ketec** [primefaces/primeng#5269]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
Does not scroll selected item into view.

**Expected behavior**
Scrolls selection into view

Example:
I implemented following directive for my extended component:

```
@Directive({
    selector: '[autoscroll]'
})
export class AutoScrollDirective {
    @Input() set autoscroll(value: boolean){
        if(value){
            this.elementRef.nativeElement.scrollIntoView({block: 'nearest'});
        }
    }
    constructor(private elementRef: ElementRef){}
}


[autoscroll]="highlightOption==option"
```

It does have some cross browser issues due to some not supporting the params for scrollintoview.
Also direct dom manipulation (renderer2  does not allow this anymore).

**Comment by cagataycivici** [comment]
Works for me at;

https://www.primefaces.org/primeng/#/autocomplete
