### ISSUE TITLE
Turbo Table Row Expansion Issue, when it contains another turbo table

### ISSUE THREAD

**Issue by ayush987goyal** [primefaces/primeng#5279]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Stackblitz Case (Bug Reports)**
Please refer the below url for the issue reporduction

https://stackblitz.com/edit/turbo-table-row-exp-issue

**Current behavior**

The turbo table is not properly styled inside the row-expansion of another turbo table.

**Expected behavior**

The table inside another table must be styled properly

**Minimal reproduction of the problem with instructions**

Expand the rows of the table in the mentioned URL
https://stackblitz.com/edit/turbo-table-row-exp-issue

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.2.X

* **PrimeNG version:** 5.2.1

**Comment by christysalter** [comment]
Your nested table is trying to display in the first column of the parent table. Wrap your expansion p-table in a td with colspan set
`<tr>
      <td [attr.colspan] = "5">
            <p-table>
                  ...
            </ptable>
      </td>
</tr>`

**Comment by pratiksa** [comment]
I got my solution, i had set the wrong dataKey
