### ISSUE TITLE
Dropdown with default value does not work properly with clear button

### ISSUE THREAD

**Issue by rafa-as** [primefaces/primeng#5280]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/zIEhdMlGSNzCqmhZU41h?p=preview

**Current behavior**
![bug-dropdown](https://user-images.githubusercontent.com/594574/37092850-9c216db6-220d-11e8-84c2-6d7f5f195de6.gif)

**Expected behavior**
Open the dropdown.

**Minimal reproduction of the problem with instructions**
1. Create a dropdown with selected/default value
2. Click clear button
3. Try to open the dropdown

**What is the motivation / use case for changing the behavior?**
Obviously this error makes the dropdown unusable.

**Please tell us about your environment:**
OS: MAC OS X High Sierra 10.13.3
IDE: WebStorm 2018.1 EAP
Package Manager: Yarn 1.5.1
Node: 9.7.1
Angular-cli: 1.7.2

* **Angular version:** 5.2.7

* **PrimeNG version:** 5.2.1

* **Browser:** all
 
* **Language:** all

* **Node (for AoT issues):** `node --version` = 9.7.1

**Comment by perkma** [comment]
The clear button does not emit an onChange event. Is that an intended behavior?

**Comment by rafa-as** [comment]
I don't know @perkma but for me is another bug

**Comment by davisb10** [comment]
It is performing the same way even in the demo. This needs to fixed soon as it breaks the entire dropdown and makes in unusable.

**Comment by blackholegalaxy** [comment]
Agreed. The dropdown is unusable

**Comment by nakurd** [comment]
please make it optional.

**Comment by mlangwell** [comment]
Observing the same behavior, and I agree our team needs the clear icon optional.

**Comment by jamieathans** [comment]
Workaround to hide the clear button:

Add the following in global styes.scss:

```
p-dropdown {
  .ui-dropdown-clear-icon {
    display: none;
  }
}
```

**Comment by EleanorHughes** [comment]
Any idea when this is going to be fixed? We need both the clear button and the dropdowns in our application

**Comment by cagataycivici** [comment]
5.2.2 is now published with this fix and others;

https://www.primefaces.org/primeng-5-2-2-released/
