### ISSUE TITLE
p-dropdown clearvalue icon is clearing even when the control is set to disabled

### ISSUE THREAD

**Issue by ASK83** [primefaces/primeng#5286]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/kp2rDPVGXyQgQIfhrnPB?p=preview

**Current behavior**
You can clear the preselected value even when the dropdown is set to be disabled.

**Expected behavior**
Not be able to clear a disabled dropdown. It would even be a good idea to give the user the functionality to have or not to have the clear button.

**Minimal reproduction of the problem with instructions**
plunker shows the issue

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X
> 5.2.0

* **PrimeNG version:** 2.0.X
5.2.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by billfranklin** [comment]
Must agree with this.  You should always honor the status of the control.
