### ISSUE TITLE
TurboTable isEnabled() logical error.

### ISSUE THREAD

**Issue by lhysrc** [primefaces/primeng#5287]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Minimal reproduction of the problem with instructions**
There are many `...Disabled` properties in the TurboTable's directives, and the logic of all  `isEnabled()` methods is wrong! 
`Disabled !== false;` is still disabled.
One of them:
<https://github.com/primefaces/primeng/blob/057f2db9c8a86af1fa95f12b46112c16d66ea7f2/src/app/components/table/table.ts#L2465>
should be
```
isEnabled() {
   return this.pEditableColumnDisabled !== true;  
}
```

* **Angular version:** 5.2.7

* **PrimeNG version:** 5.2.1

**Comment by AndreaBarbasso** [comment]
The logic itself is not broken, but attribute naming REALLY is.  
From docs: 
> For dynamic columns, setting pResizableColumnDisabled property as false disables resizing for that particular column.

That's so counterintuitive.

**Comment by lhysrc** [comment]
@AndreaBarbasso 
The attribute can be rename to pResizableColumn**Enabled**, and let it has a default value `true`.

**Comment by cagataycivici** [comment]
Docs were wrong (fixed now), note that undefined/null makes it still enabled so logic and naming is correct actually. You disable it when you actually disable it. [pResizableColumnDisabled]="true", same logic as inputtext.

**Comment by cagataycivici** [comment]
Replicated
