### ISSUE TITLE
Dropdown clear functionality should emit onChange 

### ISSUE THREAD

**Issue by Ayuob-Alfouzan** [primefaces/primeng#5288]
**I'm submitting a**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
The clear functionality of the dropdown list is very nice and needed, an enhancement over that is to trigger an onChange action to know that the user cleared the list and do something with that information. Just like if he selected an item from list.

**Expected behavior**
I need to know when a user cleared his selection

**Minimal reproduction of the problem with instructions**
Click on the clear icon, onChange should be triggered,

**Please tell us about your environment:**

* **Angular version:** 5.2.1

* **PrimeNG version:** 5.2.1

**Comment by raymond-kolorbox** [comment]
Here is a workaround for clear handler, add this in onChange function
```
$('.ui-dropdown-clear-icon').on('click', () => {
    this.clearAction();
});
```
