### ISSUE TITLE
max-height of p-listbox is ignored 

### ISSUE THREAD

**Issue by axinedy** [primefaces/primeng#5291]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
The max-height property of second p-listbox is ignored (It has ng-template for displaying two columns in each item).

**Expected behavior**
Height of both listboxes will be equal to max-height

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/JHHfZM3qHc8MDcr0dGFx?p=preview

**Please tell us about your environment:**

* **Angular version:** 5.2.7

* **PrimeNG version:** 5.2.0

* **Browser:** [Chrome 64 | Firefox 58.0.2]

**Comment by cagataycivici** [comment]
Try with 5.2.0 please, plunkr has 4.2. I can't see any problems with 5.2.

**Comment by axinedy** [comment]
I have this problem with PrimeNG 5.2.0 and Angular 5.2.7, I never tried this with previous versions of PrimeNG  суббота, 10 марта 2018г., 01:17 +07:00 от Çağatay Çivici  notifications@github.com :
