### ISSUE TITLE
TurboTable is very slow with 5000 rows

### ISSUE THREAD

**Issue by bbuehrer** [primefaces/primeng#5293]
I'm submitting a ...
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/zh1p5d3NKGI6AQNElhkP?p=info

**Current behavior**
TurboTable is very slow with 5000 rows

**Minimal reproduction of the problem with instructions**
Example 1:
I fill the TurboTable with 5000 rows (with 8 columns).
This takes 8 seconds on my Windows-PC an 30 seconds on my tablet (Samsung Galaxy TAB A 10.1 2016)
During this time, the browser stops responding.

Example 2:
I use the virtual scrolling and lazy loading mechanism.
The 5000 objects are in the memory in an array.
On the onLazyLoad-event i put 40 objects in the virtualArray ([value]="virtualArray").
The virtualScrollDelay is 0.
During the scrolling, the new row-paint is very slow.

For example with the DataScroller with [rows]="20" it works fine without an delay during the scrolling.

* **Angular version:** 5.2.0

* **PrimeNG version:** 5.2.1

* **Browser:** [Chrome 64 | Firefox 58 ]

**Comment by cagataycivici** [comment]
Performance of TurboTable is similar to native *ngFor as it uses it. So your case is not related to PrimeNG but with Angular itself, I've tried with an ngFor without TurboTable to render 5K rows with 8 columns and results are same. You should really check out pagination, virtual scrolling works for me fine as well, not sure how you implement it on your side. 5K array should not be in array, you should get it with lazy loading from the serve 40 by 40.

**Comment by bbuehrer** [comment]
This is not quite true. A standard html table takes at most half the time (3 - 4 seconds) than the primeng turbo table.


Why you are writing something of 0.5 seconds here:

https://www.primefaces.org/primeng-5-2-0-rc1-released-turbotable/

**Comment by sonamsdiwate1983** [comment]
I am able to reproduce same issue
