### ISSUE TITLE
TurboTable's single selection should allow a Datatable-like "no empty-selection" mode.

### ISSUE THREAD

**Issue by AndreaBarbasso** [primefaces/primeng#5294]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
TurboTable's selected row in `selectionMode="single"` can be unselected by clicking on it again.
**Expected behavior**
This is fine, but it would be nice to have an attribute to avoid this, because the old DataTable did not work that way (once you selected something, you could not have an empty selection ever again).
I'm actually using a workaround right now (with `onRowUnselect` selecting the row again), but it's kinda gimmicky.

* **PrimeNG version:** 5.2.1

**Comment by cagataycivici** [comment]
[metaKeySelection]="true"

**Comment by ivijan** [comment]
Hello,
it would be great to mention about selectionChange and metaKeySelection in tubro table documentation!

I had problem with single selection and null value of data... luckily I solved it by checking out the code and this issue.
