### ISSUE TITLE
Dropdown clear break when use more than one dropdown

### ISSUE THREAD

**Issue by upmauro** [primefaces/primeng#5299]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
```
**Minimal reproduction of the problem with instructions**

![peek 2018-03-08 16-10](https://user-images.githubusercontent.com/106457/37171432-a503d4de-22ec-11e8-9372-abfbb7637e33.gif)

1 - Select element in the first dropdown 
2 - Select element in the second dropdown
3 - Clear the first dropdown
4 - Try open items in first dropdown, the items not appear

* **Angular version:** 2.0.X
5.2.8
* **PrimeNG version:** 2.0.X
5.2.1

* **Browser:** [all |

**Comment by victorguimaraessilva** [comment]
UPPPP

**Comment by upmauro** [comment]
changed onMouseclick to check if clear button is clicked using:

`this.clearClick = (<Element>event.target).classList.contains('ui-dropdown-clear-icon');`

and removed all others checks and sets about  this.clearClick

**Comment by rafa-as** [comment]
The issue is not when have more than one dropdown.

Duplicated https://github.com/primefaces/primeng/issues/5280

**Comment by cagataycivici** [comment]
#5280
