### ISSUE TITLE
create chart lines without curves

### ISSUE THREAD

**Issue by Perezmarc** [primefaces/primeng#530]
I guess it's done by changing the type property to something, but can't find any list on all types available.

<p-chart type="line" height="50px" [data]="volumeSalesData"  [options]="volumeSalesOptions"></p-chart>

Thanks!

**Comment by Perezmarc** [comment]
Anyone?

**Comment by MarcelCremer** [comment]
PrimeNG uses chartjs for drawing charts. As for this. you can set chartjs options via [options]="options" property (http://www.primefaces.org/primeng/#/chart).

All available options are documented on the chartjs website:
http://www.chartjs.org/docs/#line-chart-data-structure
(most likely you like to use a lineChart with {lineTension:0}).

**Comment by Perezmarc** [comment]
nice and easy!
Thanks!
