### ISSUE TITLE
5.2.1 bug: p-table paginator has a clear icon that provides undefined functionality

### ISSUE THREAD

**Issue by hughanderson4** [primefaces/primeng#5301]
```
[ X ] bug report => Search github for a similar issue or PR before submitting
```

**Demo Plunkr**
http://plnkr.co/edit/493NsR?p=preview

**Current behavior**

Since version 5.2.1 we have new clear icon appearing in dropdowns.
It is now appearing in paginator of p-table who has `rowsPerPageOptions` attribute.
This functionality is unwanted and undefined for the rowsPerPageOptions dropdown.
We must always have a value for Rows Per Page, so the user must not have the ability to clear it.

**Expected behavior**

This new little clear icon should be suppressed in the p-table p-paginator.

**Minimal reproduction of the problem with instructions**
See the Demo Plunkr which has a p-table with a p-paginator with a p-dropdown with the unwanted clear icon.
Try clicking the clear icon in the paginator.  See it provides no functionality.

**What is the motivation / use case for changing the behavior?**

User should never be able to clear the Rows Per Page which would cause undefined pagination.

**Please tell us about your environment:**

Windows 10, VS 2017, npm

* **Angular version:** 2.0.X

5.2.0

* **PrimeNG version:** 2.0.X

5.2.1 *please note* this bug is new since 5.2.1, and did not exist in 5.2.0.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All browsers.  see demo Plunkr
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS 2.6.2

**Comment by hughanderson4** [comment]
Related to #5285 and #5286

**Comment by pkerblaze** [comment]
Also you can see it on the documentation page 
https://www.primefaces.org/primeng/#/paginator

**Comment by cagataycivici** [comment]
Fixed as well.
