### ISSUE TITLE
Issue of dialog

### ISSUE THREAD

**Issue by Champion-Chen** [primefaces/primeng#5304]
After upgrade from 5.2.0, this position issue fixed, but new issue appears:
1. drag dialog and release, dialog resotre its position, eg: https://www.primefaces.org/primeng/#/dialog
2. open a new dialog in host dialog, new dialog may be hidden by its parent, and this was ok in 5.2.0. for this reason i have to rollback to 5.2.0(seems "dialog with upload cause ExpressionChangedAfterItHasBeenCheckedError when show" issue has been fixed ).
3. suggestion: close host dialog can force to shut down the child dialog, like dialog in winform. (if both is modal, seems not a problem).

**Comment by cagataycivici** [comment]
#5271
