### ISSUE TITLE
Compile error after 5.2 Upgrade.

### ISSUE THREAD

**Issue by asingh3886** [primefaces/primeng#5307]
I am getting a compile error "TS2559: Type 'TreeNode[]' has no properties in common with type 'TreeNode'" after upgrading to 5.2

@cagataycivici : Please help here to resolve this issue.

**Comment by cagataycivici** [comment]
I'm unable to replicate.

**Comment by JairDiaz23** [comment]
I have the same problem. It happens to me after trying to migrate from angular 4 to angular 6.
