### ISSUE TITLE
P-autocomplete undefined form value on submit

### ISSUE THREAD

**Issue by NikhilRadadiya** [primefaces/primeng#5308]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/NNu82R?p=preview

**Current behavior**

I'm using `p-autoComplete` as a form input, when I submit form 2-3 times I get name value as undefined. I get this behavior when I was testing the server side validation. If I have error on form and re-submit the form after correcting the error when submitting the form it shows undefined value. sometimes it happens when submitting for 2nd,3rd time

**Expected behavior**

it should give selected value from autocomplete no matter how many times form submitted.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.2.4

* **PrimeNG version:**4.3.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript ^2.5.3 | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Unable to replicate, a plunkr will help.
