### ISSUE TITLE
The rich text editor do not keep multiple space in html.

### ISSUE THREAD

**Issue by tleveque23** [primefaces/primeng#5309]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
No Plunker needed, just look at the official demo: https://www.primefaces.org/primeng/#/editor

**Current behavior**
When inserting multiple spaces between string, the resulting html contain only one.

**Expected behavior**
Multi space characters should be kept (replaced by the nbsp code or any other technic)

**Minimal reproduction of the problem with instructions**
Go to https://www.primefaces.org/primeng/#/editor, add some space between word and look at the resulting html at the bottom.

**What is the motivation / use case for changing the behavior?**
Users want to align things using spaces

**Please tell us about your environment:**

* **Angular version:** 5.2.5

* **PrimeNG version:** 5.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
I think this is quill related, not PrimeNG.

**Comment by tleveque23** [comment]
Are you sure. Quill editor does not provide any method to get the html version out of it. So it is surely done by PrimeNg.
