### ISSUE TITLE
Editor issue w/ bet9 + RC3 - No value accessor for ''

### ISSUE THREAD

**Issue by gatapia** [primefaces/primeng#531]
After upgrading to beta9 / RC3 the editor component no longer works.  The`[(ngModel)]="text"` throws the error `No value accessor for ''`.

I am not using a form so I dont think I should be using the new forms stuff / formControlName.  However, I could be wrong.

I am basically copying the demo: http://www.primefaces.org/primeng/#/editor and no luck.

**Comment by ibespwn** [comment]
+1 for this issue on MultiSelect in a data table like http://www.primefaces.org/primeng/#/datatablecoltoggler.

**Comment by digitalcraftco** [comment]
For me it turned out I had some components still pulling from @angular/common instead of @angular/forms for NG_VALUE_ACCESSOR, ControlValueAccessor. Changed it to this and solved the  No value accessor for '' error.

`import {NG_VALUE_ACCESSOR, ControlValueAccessor} from '@angular/forms';`

**Comment by monoflash** [comment]
In Angular2 rc3 replace ```from '@angular/forms';``` to ```from '@angular/forms/index';```

Example
import {NG_VALUE_ACCESSOR, ControlValueAccessor} from '@angular/forms';
change it to
import { NG_VALUE_ACCESSOR, ControlValueAccessor } from '@angular/forms/index';

**Comment by gatapia** [comment]
I just ended up upgrading my whole app to the new forms. Pain in the butt but this document really helps:
https://docs.google.com/document/u/1/d/1RIezQqE4aEhBRmArIAS1mRIZtWFf6JxN_7B4meyWK0Y/pub

**Comment by spali** [comment]
@monoflash thx this was it.
In my case changed this in togglebutton.js directly in the node_modules folder of primeng and it worked. So it looks like it requires just some small fixes for rc3 in the components for this issue.

**Comment by ducduongtmb** [comment]
@gatapia 
I use Rc4 and I have same problem with http://www.primefaces.org/primeng/#/autocomplete . 

**demo.html** file 
```
<p-autoComplete  [suggestions]="filteredKnw" (completeMethod)="filterKnw($event)" [minLength]="1"
                      [multiple]="true" [(ngModel)]="tags" #tags="ngModel">
    </p-autoComplete>
```

in **demo.ts** file I decalre tags variable :
**tags:any[];**

I don't understand why this bug happen .

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
