### ISSUE TITLE
onRowDblclick triggers select-then-unselect when using a select mode

### ISSUE THREAD

**Issue by mconner** [primefaces/primeng#5310]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/ERdhcbYgq4oRApzCqmNu?p=preview

**Current behavior**

onRowDblclick event works, but if you have selectionMode="checkbox", then it selects and deselects the row.  This is because a click still comes through even if looking for dblClick events.

**Expected behavior**

The click should be debounced so that only either click or dblClick events fire, not both.
Either that, or (more preferably) allow for onRowClick handler, and allow for disabling default behavior which selects/deselects the row by click, and add methods to programatically select/deselect a node.

**Minimal reproduction of the problem with instructions**

See the plunkr, double-click on the nodes, see that the node and its children are selected/deselected.

**What is the motivation / use case for changing the behavior?**

I'd like to expand/contract the node by clicking on it with a dblClick, and select with a metakey click.

**Please tell us about your environment:**

Win 7, IntelliJ, npm, ng serve  or JBoss, 

* **Angular version:** 5.0.2

* **PrimeNG version:** 5.2.0

* **Browser:** Chrome 

 
* **Language:** TypeScript 2.4.2

* **Node (for AoT issues):** `node --version` =   8.9.1

**Comment by cyberrranger** [comment]
same problem

**Comment by cagataycivici** [comment]
Please try the new TreeTable as this issue is related to the old one.
