### ISSUE TITLE
Fixed position support for OverlayPanel

### ISSUE THREAD

**Issue by dhniels** [primefaces/primeng#5311]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report 
```

**Plunkr Case (Bug Reports)**
Open this plunker, open the dialog with the button, and open the overlaypanel with the button inside the dialog. this is a barebones version of what im doing in my app.
http://plnkr.co/edit/umy6yBOAM7e1fYvm2q7A?p=preview

**Current behavior**
I try to use an overlay panel to center inside the viewport and give it a position fixed. when i apply those styles, the toggle breaks. when you click to toggle it, .ui-overlaypanel stays stuck on display:none instead of toggling to display: block

**Expected behavior**
It should toggle between display:none and display: block when showing and hiding.

**Please tell us about your environment:**
macOS High Sierra 

* **Angular version:** 2.0.X
Angular 5 latest

* **PrimeNG version:** 2.0.X
PrimeNG 5.2.1 (this issue has been around for a long time before 5.2.1)

* **Browser:** 
all

**Comment by c123dl** [comment]
hi, 
i see this issue is still open, any bug fix estimated for this?

**Comment by Michael-Ziluck** [comment]
@c123dl Ahh, first time trying to communicate with PrimeNG, huh? They basically never reply unless you have a license. Which is fine, I just wish they were more transparent about how that process works.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
