### ISSUE TITLE
p-table - Multi select Checkbox and reorder columns are not working fine RC5.2.0

### ISSUE THREAD

**Issue by AbhijitMuke** [primefaces/primeng#5314]
When I have a p-table with `pReorderableColumn` all work fine, but when I add `tableHeaderCheckbox` to use multi-select using a checkbox, the reorder column functionality work wrong.

Plunkr - [Column Reorder Demo](http://plnkr.co/edit/XsLRK4GhJe5WQk5QYHg7?p=preview)

**Comment by cagataycivici** [comment]
Try 5.2.2 please, that should fix it.

**Comment by sabriquraan** [comment]
same issue with me 
 "primeflex": "^3.2.1",
    "primeicons": "^5.0.0",
    "primeng": "^14.0.2",
