### ISSUE TITLE
Tooltips only work for input elements

### ISSUE THREAD

**Issue by bPopovska** [primefaces/primeng#532]
Up to version beta-9, tooltips only work in input elements.
It would be very helpful if in a future version you could support tooltips for span and div elements as well.

**Comment by payaircargo** [comment]
Agreed!

**Comment by CelsoSantos** [comment]
I'd like to update this request with the ability to include a tooltip on other places such as a Panel header.

It would be tremendously helpful we could show not only a collapse button for a panel but also a tooltip.

**Comment by cagataycivici** [comment]
It works on any element, it binds to mouseover or mouseout, so does not care about target actually.

**Comment by prassannajohnpaul** [comment]
Tool tip doesn't work with schedule events.

**Comment by vredchenko** [comment]
"It works on any element, it binds to mouseover or mouseout, so does not care about target actually." that is simply not the case - I have a `<button>` and an `<input>` next to each other - works on the latter but not the former. `primeng@4.1.2`

**Comment by ikennai** [comment]
I ran into this issue as well trying to use tooltips on anchor elements.  I found a fix that seems to work. For our anchor tags I used css psuedo class ::after 

`a::after { content: ' '; width: 1px; height: 1px; }` 

the height/width may or may not be necessary - test accordingly, but it seemed to allow prime ng tooltips to treat inline elements the same way it treats the inline-block type elements like input fields
