### ISSUE TITLE
Turbotable column style when 'pSortableColumnDisabled'

### ISSUE THREAD

**Issue by sebaiona** [primefaces/primeng#5329]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
 
**Plunkr Case (Bug Reports)**
See in the Plunkr below the column 'Brand' is disabled :

http://plnkr.co/edit/egBhS1DJhY2Ud1ByfGBp?p=preview

**Current behavior**

Now the disabled column has the sorting class (which let the user thinks it's sortable) whereas it's not sortable.

**Expected behavior**

The column shouldn't have the 'ui-sortable-column' class

**Minimal reproduction of the problem with instructions**

* **PrimeNG version:** 5.2.2

**Comment by jupin-r** [comment]
I agree with you, but this issue is nice to have. It is enough for me that the column brand does not have the sorting arrows.

**Comment by sebaiona** [comment]
I didn't say it's a big deal, but it's not really logical...
