### ISSUE TITLE
primeng tree checkbox selection

### ISSUE THREAD

**Issue by dgorobopec** [primefaces/primeng#533]
Hi guys,
first i want to thank you for the job you are doing with primeng it helps a lot !

Now i wanted to know if there will be an implementation of the tree selection checkbox such as in primefaces ( you can find what i am talking about here : http://www.primefaces.org/showcase/ui/data/tree/selection.xhtml) ?

I know that primeng is still in its early releases and that you'll add a lot more of content in next updates but i was just wondering if it was planed for a near release :) thank you very much. have a nice day !

**Comment by lilling** [comment]
@dgorobopec if you mean the option with the tri state check box then :+1::+1::+1:

**Comment by dgorobopec** [comment]
@lilling yes, the third example on the link i provided.

**Comment by vishal3007** [comment]
I am also looking for the same..Any idea by when it will be available?

**Comment by h3llrais3r** [comment]
Any update on this? Is this something that can/will be added in the (near) future?

**Comment by dgorobopec** [comment]
@h3llrais3r I don't know.
And as it is an old issue without a good label i don't know if the project team knows about this.

**Comment by h3llrais3r** [comment]
@cagataycivici any thoughts on this?

**Comment by cagataycivici** [comment]
Yes it is planned before the end of year, we will do a similar solution as we did for PrimeFaces. We will also add drag drop support to tree, these 2 are the upcoming important features to Tree.

**Comment by h3llrais3r** [comment]
Thanks for your feedback. Looking forward to this feature. 👍
