### ISSUE TITLE
Shift key selection only works on first page

### ISSUE THREAD

**Issue by bbuehrer** [primefaces/primeng#5330]
```
[x] bug report => Search github for a similar issue or PR before submitting
```

1. Multiselect with shift-key only works on first page.

2. If i select entries on a page and then switch to another page and select entries there, then the entries on the previous page remain selected. This is a problem because I can not see anymore on which pages entries are selected. It would be better to deselect the entries when the page is changing.

**Comment by jupin-r** [comment]
Could you demonstrate the bug in plunker?

**Comment by mouradghafiri** [comment]
Hello
I think this a normal behavior from the UI perspective, you just need to find a UX for your use case.
Maybe add them in the footer or the header, so the user know what is already selected.

Good luck

**Comment by bbuehrer** [comment]
No, i cannot demonstrate it on plunker.
Plunker does not have the latest version of PrimeNG with Shift-Key and metaKeySelection.

**Comment by bbuehrer** [comment]
1. Multiselect with shift-key only works on first page.

Is a correction of this bug planned?
