### ISSUE TITLE
Floating label support for Chips

### ISSUE THREAD

**Issue by axinedy** [primefaces/primeng#5332]
Hello.
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/CTjRHdNfZUfWEVOnd7BO?p=preview

**Current behavior**
Floating label doesn't floats up on chips input. Input text overlaps grey label text

**Expected behavior**
Floating label will float up on chips input like on simple text input field

* **Angular version:** 5.2.8

* **PrimeNG version:** 5.2.3

* **Browser:** [ Chrome 64 | Firefox 58 ]

**Comment by tarekz** [comment]
I am actually having the opposite issue. The label floats up, but when I reset the form, the label stays up.

**Comment by yigitfindikli** [comment]
https://primefaces.org/primeng/showcase/#/floatlabel
