### ISSUE TITLE
Chips Separator

### ISSUE THREAD

**Issue by adama357** [primefaces/primeng#5333]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
If I have a comma-separated list of IDs, in order to enter them in a p-chips input, I'd need to, for each ID, copy it, paste it in the chips input, and then press enter. 

**Expected behavior**
It would be nice if the p-chips component would take in a "separator" parameter, such that if I set separator = "," I can just paste in the comma-separated list of IDs and press enter. 

Thank you for your time!

**Comment by marcelocaser** [comment]
this is very necessary!!!! ;)
