### ISSUE TITLE
p-calendar [utc]='true' highlights day before selected date

### ISSUE THREAD

**Issue by jonhiga** [primefaces/primeng#5334]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

https://plnkr.co/edit/YLpToS9AwkNVKYzfRPp8?p=preview

**Current behavior**
For browsers in the US, the pop-up calendar highlights the date before the date selected. For example, if 2018 March 1 is the current value, then the pop-up calendar displays 2018 February with 2018 February 28 highlighted.

**Expected behavior**
The date in the input box should match the highlighted date in the pop-up calendar. The month shown in the pop-up calendar should match the month of the date in the input box.

**Minimal reproduction of the problem with instructions**
Use `<p-calendar [utc]='true'>` to select any date, using any browser in a United States time zone.
Click on the calendar again to see which date is highlighted.

**What is the motivation / use case for changing the behavior?**
`<p-calendar [utc]='true'>` is fundamental use of the Calendar component.
Since `.toJSON()` serializes in UTC, working with UTC midnight instances of `Date` is easier
than working with local midnight when representing Java 8 `LocalDate` fields.

**Please tell us about your environment:**
Fedora 26

* **Angular version:** 5.2.8

* **PrimeNG version:** 5.2.3

* **Browser:** all
 
* **Language:** TypeScript 2.6.2

* **Node (for AoT issues):** 8.9.4

**Comment by cagataycivici** [comment]
Please see;

https://github.com/primefaces/primeng/issues/5853
