### ISSUE TITLE
Dropdown to call onChange() only on keyboard enter instead of arrow up/down

### ISSUE THREAD

**Issue by arsunda** [primefaces/primeng#5335]
**I'm submitting a ...**  (check one with "x")
```
[? ] bug report
[x ] feature request 
```

**Current behavior**
The (onChange) behaviour is called when using the dropdown with the keyboard up/down arrows

**Expected behavior**

Most dropdowns do not do this by default, instead the actual value is only changed when pressing enter with the value you want to have focused. 

**What is the motivation / use case for changing the behavior?**
I am working on accessibility, and some of our dropdowns open panels/alerts when clicked. There is no way to browse the options in a dropdown with the keyboard without triggering these events (and hence loosing focus on the dropdown). I want to be able to browse the dropdown with the up/down keys and then press enter to choose the value i want

The workaround I currently see for this is to capture the original event and prevent the default onChange() behaviour, (maybe store current value somewhere) and then call it seperately on keydown.enter

OR

have the onChange() event not trigger the sidepanel/alert function, only change the value. In addition have a button adjacent to the dropdown to call the corresponding function on press. But this ruins the experience for users as there are more clicks

* **Angular version:** 2.0.X
Angular 5.1.3

* **PrimeNG version:** 2.0.X
Prime 5.2.9

**Comment by abelardolg** [comment]
+100

**Comment by cagataycivici** [comment]
As the value is changed, we must call onChange since model is updated. The behavior depends on browsers for native select and p-dropdown picks an opinion.

**Comment by arsunda** [comment]
The problem is that value should only be changed on **SELECTING** a value, not while **NAVIGATING** with up/down arrow keys?

**Comment by tibinvpaul** [comment]
Hey @arsunda - were you able to find out any workaround for this issue? Thanks.

**Comment by arsunda** [comment]
@tibinvpaul I don't remember getting any undefined events, but one of the workarounds we used was to have a "Save" button that would take the model changes and use it. You might also want to try listening to something like a focusout event to use the model changes when the user closes the dropdown

**Comment by sbkpilot1** [comment]
this is a design flaw... dropdowns don't work this way.  The user is free to "browse" the list before making a selection.  A selection is made only by actively clicking on an item or pressing ENTER with the item highlighted.

The current implementation is very strange and non-intuitive.

**Comment by ty-ler** [comment]
Still experiencing issues with this behavior. It's not at all how our users expect using the arrow keys to work. 

For example, we have multiple dropdowns, all with the same dropdown options. If we select a value in one of the dropdowns, and another dropdown already has that value selected, we want to deselect on the dropdown which was already selected. This weird behavior completely breaks our expected workflow as when we are **just navigating the options** by using the arrows keys, almost all of our other dropdowns will become unselected.

Please at least give us an Input to control this...

**Comment by EliasKokkinos** [comment]
> Still experiencing issues with this behavior. It's not at all how our users expect using the arrow keys to work.
> 
> For example, we have multiple dropdowns, all with the same dropdown options. If we select a value in one of the dropdowns, and another dropdown already has that value selected, we want to deselect on the dropdown which was already selected. This weird behavior completely breaks our expected workflow as when we are **just navigating the options** by using the arrows keys, almost all of our other dropdowns will become unselected.
> 
> Please at least give us an Input to control this...

I havent passed it through thorough testing yet, but this should work.

Use a boolean and the events for onShow and onHide (open and closing boolean).
If this value is true then 'return' from your function ('loadOptions()' in my case). On close change the boolean and run the function you want triggered ('loadOptions' in my case).
Keep 'onChange()' for the case the user opened and closed and then they use arrow keys (while dropdown is closed) to change the option. In this case they have it focused and their selection should trigger the change.

![image](https://github.com/primefaces/primeng/assets/26279227/d85b618f-9c29-47ad-b75e-ec6f211e25fc)

I hope this helps.
