### ISSUE TITLE
p-dialog - Size of dialog gets stuck on window zoom or resize

### ISSUE THREAD

**Issue by callumbloomfield** [primefaces/primeng#5336]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

http://plnkr.co/edit/Z721ta8OekKOPk6lwc8f

(You can't actually zoom in on the render window to reproduce the bug, you will need to do it in a separate browser window)

**Current behavior**
When any p-dialog has been created, and you zoom in or resize the page, the dialog will no longer resize responsively as you zoom out again.

**Expected behavior**
The p-dialog should continue to be responsive and return to the original size after you zoom out again

**Minimal reproduction of the problem with instructions**
As mentioned previously

**What is the motivation / use case for changing the behavior?**
The dialog should continue to remain responsive and at the same size after zooming in/out

**Please tell us about your environment:**
Win 10, VS Code, ng serve

* **Angular version:** 5.0.x

* **PrimeNG version:** Latest

* **Browser:** all
 
* **Language:** all

Images of issues at: https://imgur.com/a/twvWN
Thanks.

**Comment by dicbrus** [comment]
Confirm the bug.

**Comment by dicbrus** [comment]
@glubbert thanks for workaround

**Comment by Codinger386** [comment]
I know it's not directly connected to the problem, but how can I access `this.dialog` if I added the dialog in the template with `<p-dialog ...`?
