### ISSUE TITLE
p-contextmenu option to have one context-menu shown at a time [for list]

### ISSUE THREAD

**Issue by namnn** [primefaces/primeng#5337]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
I have a list of item, each of which has its own contex-menu.
If I right-click on one, and right-click another one, 2 context-menus are shown.
I understand this may be the use-case for someone else, but for those who want a singleton view of context-menu, they have no options.
No event callback on show, hide or toggle

**Expected behavior**
Should provide either
- option to have one context-menu show at a time, or
- callback event on show, hide and toggle

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
One context-menu shown at a time for a list

**Please tell us about your environment:**

* **Angular version:** 5.2.8

* **PrimeNG version:** 5.2.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by jiangyh1024** [comment]
@cagataycivici  when should this functionality will be added?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
