### ISSUE TITLE
p-chips - insert new word between existing chips

### ISSUE THREAD

**Issue by axinedy** [primefaces/primeng#5338]
Hello
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
It's possible to delete a chip at any place of list by clicking 'x'.  You can put the cursor at the end of chips input, so a new word can be added to the end of list only.

**Expected behavior**
Ability to create/delete chips at any list position. Cursor can be placed between any chips by mouse or by left/right keys.

Thank you

**Comment by applitopia** [comment]
Optionally a Drag&Drop functionality to reorder chips would be nice.

**Comment by axinedy** [comment]
+1! Would be nice
--
Regards,
Denis.  четверг, 21 июня 2018г., 15:33 +07:00 от Applitopia  notifications@github.com :

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
