### ISSUE TITLE
p-table sorting reset in modal data

### ISSUE THREAD

**Issue by srjkrl20011991** [primefaces/primeng#5339]
Hi, I click on button after that modal is pop up. In modal I took p-table with sorting.I closed the p-table and again open sorting remain as it is. nay solution to reset sorting in modal data.

**Comment by jupin-r** [comment]
I think that is not bug report nor feature request, but support request.
There is the rule for new issue for support request - Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Comment by cagataycivici** [comment]
Please use forum for questions.
