### ISSUE TITLE
Canvas bar chart not showing properly

### ISSUE THREAD

**Issue by punnepallivenkat** [primefaces/primeng#5340]
If came more data the canvas bar chart is not showing clearly..some unwanted black lines are occurring please find an attached screenshot.

https://user-images.githubusercontent.com/36731114/37386496-a2b4fde8-277e-11e8-979e-7ea389b82192.jpg

**Comment by jupin-r** [comment]
The primeng p-chart is wraper over chart.js therefore this issue is not related to primeng, but Chart.js. I think that the black lines are overlaped labels of values.

**Comment by cagataycivici** [comment]
Issue is related to chart.js.
