### ISSUE TITLE
RTL support for scrollable tables

### ISSUE THREAD

**Issue by tigrenok00** [primefaces/primeng#5346]
Hello,
When adding ` [scrollable]="true" scrollHeight="500px"` to the p-table, the scrollbar added on the left side but the extra-space in the headers is added on the right side, causing the headers to be misaligned.
I am working with RTL body.
How can this be resolved?

![image](https://user-images.githubusercontent.com/23075641/37390858-11a5ae80-2772-11e8-9243-7f2923ebc559.png)

This is with version 5.2.3

**Comment by webnegar** [comment]
> This problem exists in newer versions (7.0) too.
> is there any plan to solve it?
> 
> ![problem](https://user-images.githubusercontent.com/7112978/50544874-94666e00-0c18-11e9-9dc0-e13bccee22a8.jpg)

do you have any plan to solve it?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
