### ISSUE TITLE
Confirmation Box 

### ISSUE THREAD

**Issue by AshishTiwariMEAN** [primefaces/primeng#5347]
Hello,

Can you please check below code, I want to use confirmation box in CanDeactivate Gaurd. 

So can you please suggest me how we can implement prime ng confirmation in CanDeactivate.

@Injectable()
export class ConfirmDeactivateGuardSettings implements CanDeactivate<ViewSettingsComponent> {

  canDeactivate(target: ViewSettingsComponent) {
    if (target.isFormChanged) {
      return window.confirm('You havent saved your changes. Are you sure you want to leave this page?');
    }
    return true;
  }
}

**Comment by cagataycivici** [comment]
Please use forum for support requests.
