### ISSUE TITLE
Turbo table: rowIndex attribute is not attached to event for onRowSelection event

### ISSUE THREAD

**Issue by ccasallas** [primefaces/primeng#5349]
**I'm submitting a:**
```
[ ] bug report
[ x ] feature request
[ ] support request
```
Please attach rowIndex attribute to event object for onRowSelect event, for the following code only is attached to the event the data attribute:

```
<ng-template pTemplate="body" let-role let-rowIndex="rowIndex">
    <tr [pSelectableRow]="role" [pSelectableRowIndex]="rowIndex">
      <td>{{role.fullName}}</td>
    </tr>
</ng-template>
```
Or is there another way to get the rowIndex on row selection?

* **Angular version:** 5.2.0

* **PrimeNG version:** 5.2.0

**Comment by cagataycivici** [comment]
Merged PR

**Comment by ccasallas** [comment]
thanks!
