### ISSUE TITLE
TurboTable: column lines do not appear in <th> cells in the header when pResizableColumn is used in Firefox

### ISSUE THREAD

**Issue by bomberblue07** [primefaces/primeng#5353]
The lines render normally in Chrome.

**Comment by bomberblue07** [comment]
You can see it in the showcase on Firefox, too: https://www.primefaces.org/primeng/#/table/colresize

**Comment by bomberblue07** [comment]
Still a problem in 5.2.5

**Comment by cagataycivici** [comment]
Fixed in 6.0.0-beta.1 in another case.
