### ISSUE TITLE
Scrollable p-table - header and columns are misaligned

### ISSUE THREAD

**Issue by ctrl-brk** [primefaces/primeng#5354]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
```
When scrolling is enabled for p-table the header columns don't align with body columns.
Here's the screenshot of the demo page (https://www.primefaces.org/primeng/#/table/scroll) at 200% magnification.
![image](https://user-images.githubusercontent.com/5613056/37434482-5a7dd9a6-27a5-11e8-916a-f14d0ddca73a.png)

**Comment by tigrenok00** [comment]
I wish they would fix this or at least respond... There are tons of issues open on this and they are being ignored...

**Comment by bluelbow** [comment]
I'm having the same issue.
To workaournd the issue change the css to something like that:

`.ui-table-scrollable-header-box {
    margin-right: 17px !important;
}

.ui-table-scrollable-body {
    margin-right: 17px !important;
}`

It's not beautiful, but at least the column are aligned.

**Comment by cagataycivici** [comment]
@tigrenok00 This is from the issue template;

```
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Waiting Time: ~8 weeks.
```

Afaik, there is no way to catch the zoom event so there is a technical limitation here. Feel free to send a PR if you have a solution.

**Comment by damatri** [comment]
@ bluelbow 
only having:

```
.ui-table-scrollable-header-box {
margin-right: 17px !important;
}
```

is sufficient though

**Comment by damatri** [comment]
Thanks :)

**Comment by amir-mehrizi** [comment]
hi everyone. i had the same problem and i studied the all issues carefully and finally i fix the problem. you can use the CSS class and you can see that the problem is perfectly done.
something that is really important and crucial is, you must write all codes in CSS style together.

.ui-table-scrollable-header-box {
margin-right: 17px !important;
}

.ui-table-scrollable-body {
margin-right: 17px !important;
}
///// this code below is for width of the scroll bar
::-webkit-scrollbar {
width: 10px;
}
.ui-table-scrollable-header {
overflow-y: scroll;
}

i think that this helps you.

**Comment by n0script** [comment]
all these "workarounds" didnt work out for me, just if table scroll is active all the time

.ui-table-scrollable-header-box th:last-child {
    padding-right: 20px !important;
  }

 works with and without scrollbar

**Comment by rubmz** [comment]
This issue is far from being close ... Just saying... If you got a vertical scrollbar that is on 'auto' it causes the headers to be sometimes aligned and sometimes misaligned based on the existence of the scrollbar on the body part...

**Comment by capc0** [comment]
still an issue on version 9 LTS for me

**Comment by catonice** [comment]
Version: 10.0.0
Still an issue for me - we went with making the container scrollable for now but this isn't an ideal situation

**Comment by mcrtricolor** [comment]
I'm having the same problem with 11.0, it's like the header doesn't know if the table is scrolling or not, always put that padding-right there.

**Comment by capc0** [comment]
FYI this is my workaround for this issue.

```html
<p-table #table>...</p-table>
```

```ts
@ViewChild('table', { static: true }) public table: Table;

ngAfterViewInit() {
    this.resizeObs = new window.ResizeObserver(() => {
        this.checkScrollBarAlignment();
    });
    this.resizeObs.observe(this.table?.el?.nativeElement);
}


// if offsetWidth or offsetHeight is 0, the table is not visible/rendered on screen
checkScrollBarAlignment() {
    if (this.table?.scrollableViewChild && (this.table?.el?.nativeElement as HTMLElement).offsetWidth !== 0 && (this.table?.el?.nativeElement as HTMLElement).offsetHeight !== 0) {
        (this.table.scrollableViewChild as ScrollableView).alignScrollBar();
        this.cd.markForCheck();
    }
}
```

**Comment by rolandsoh96** [comment]
I am using Angular 11 with Primeng 10.0.3.  The below code works for me.

  ::ng-deep .p-datatable-scrollable-header-box {
      padding: 0 !important;
  }

**Comment by mcrtricolor** [comment]
I'm using Primeng 11.2.3 and the bug still exists. It doesn't happen on Mac, but i don't know if it happens on Linux OS.

This is my workaround:
- I check if there is scroll in table, if there is one then apply some style with padding 17px in the header, in other case i remove it and apply 0 instead.
`
configureScrollTable() {   
  let isMacLike = /(Mac|iPhone|iPod|iPad)/i.test(navigator.platform);   
  if (!isMacLike) {     
    let elementTable: any = document.getElementsByClassName('p-datatable-scrollable-body');     
    let elementHeader: HTMLCollection = document.getElementsByClassName('p-datatable-scrollable-header-box');     
    setTimeout(() => {       
      for (let j = 0; j < elementTable.length; j++) {         
        let scrollHeightTable: number = elementTable[j].scrollHeight;         
        let offsetHeightTable: number = elementTable[j].offsetHeight;         
          if (scrollHeightTable > offsetHeightTable) {           
            for (let i = 0; i < elementHeader.length; i++) {             
              elementHeader[i].classList.remove('cabezalTablaSinPadding');             
              elementHeader[i].classList.add('cabezalTablaConPadding');           
            }         
          } else {           
            for (let i = 0; i < elementHeader.length; i++) {             
              elementHeader[i].classList.remove('cabezalTablaConPadding');             
              elementHeader[i].classList.add('cabezalTablaSinPadding');           
            }         
          }       
        }     
      });   
   }
 }
.cabezalTablaConPadding.p-datatable-scrollable-header-box {
  padding-right: 17px !important;
}
.cabezalTablaSinPadding.p-datatable-scrollable-header-box {
  padding-right: 0 !important;
}
`

**Comment by danbord** [comment]
I have found a new simple workaround... Seems to work pretty well on my side :

p-table {
    cdk-virtual-scroll-viewport {
        overflow-y: scroll !important;
    }
}

**Comment by PHuhn** [comment]
Hey, I tried all of the CSS fixes, but none worked for my grid with filters.  I looked at the demos and removed all width CSS and the misalignment was fixed.

**Comment by fjh352** [comment]
i have found if we remove the logic inside the scrollableviewChild.ngAfterViewChecked, the table will be align.

@ViewChild('table') table: any;

    ngAfterViewInit() {
        this.table.scrollableViewChild.ngAfterViewChecked = () => {
            return _.noop();
        };
    }

**Comment by Siddharth77** [comment]
My Scenario is as below:
1. I have primeNg grid with frozen and non-frozen columns, row data, which has different sections.
2. Have separated div like colgroup, frozen/nonfrozen header, frozen/non-frozen body.
2. I have default filter with some customization in header.
3. When filtering data grid is misaligned with header and columns, data of x column is showing in y column
4. Did below fix and loved CSS though tried with JS solution but it was requiring unnecessary extra coding.
5. Fix: 
.ui-table .ui-table-scrollable-body-table {
   min-height: 1px !important;
 }
Hope it helps!
