### ISSUE TITLE
Calendar: selecting date requires doubleclick if minDate or maxDate are assigned a new Date object

### ISSUE THREAD

**Issue by rejj** [primefaces/primeng#5355]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
If the minDate or maxDate field of a p-calendar is assigned a newly created Date object, a double-click is then required to select a date from the popup

**Expected behavior**
User should be able to select a date with a single click, as per normal

**Minimal reproduction of the problem with instructions**
Plunker: http://plnkr.co/edit/yvk40ILn5TNJl4vK9GpH?p=preview

The minimal repro example in the calendar just assigns a new Date() to the minDate field, to show this bug in operation.

After that I included an example more along the lines of what I am trying to do - have calculated min/max dates based on values at run time. In this case, have a calendar representing a "start date" that must be at least one day before the value of the "end date" calendar, and vice-versa for end date being at least one day after start.

The start/end example lets the user select one date as per normal just fine, but after that every subsequent selection requires two clicks.

**What is the motivation / use case for changing the behavior?**
This is an interface bug

**Please tell us about your environment:**

* **Angular version:** 4.4.4

* **PrimeNG version:** 4.1.2

* **Browser:** checked in [Chrome 66.0.3359.26 | Safari 11.0.3 ] but probably all
 
* **Language:** [all]

**Comment by rexorient** [comment]
Thank you!   I ran into the same problem... at least now I know that by removing the maxDate I had set that this problem goes away.    Please fix this!

**Comment by rejj** [comment]
Sorry for the "bump" style comment, but it has been about a month and a half and as of writing this issue has fallen to halfway down page 9 on the issues list and I'm worried about it being missed and forever falling in to the pit of obscurity.

Any chance this can be looked at please?

thanks

**Comment by cagataycivici** [comment]
When the minDate and maxDate changes, the calendar re renders the UI, when these values are bound to functions Angular does not even trigger the onDateSelect event so can't think of a way to support such cases. Solution is to keep your min/max in separate variables like maxDate1 and minDate2, at onDateSelect you need to update these variables. This will prevent the event issues and will be more performant.
