### ISSUE TITLE
minDate and maxDate attributes on p-calendar

### ISSUE THREAD

**Issue by joao-fidalgo** [primefaces/primeng#536]
Is it possible to set minDate/maxDate attributes based on a form variable?

For example, i have two datepickers, and i want p-calendar1 to block dates superior to p-calendar2.

**Comment by joao-fidalgo** [comment]
It is possible. E.g: minDate={{ form.value.maxDate }}

**Comment by mariyadasu** [comment]
Good it's working thanks
