### ISSUE TITLE
p-growl shows null if details are not used in IE11

### ISSUE THREAD

**Issue by hishamahamad** [primefaces/primeng#5360]
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Shows 'null' when details are not used in IE, this is not an issue in Chrome

**Expected behavior**
Should ignore details if details not used, like how Chrome is doing

**Please tell us about your environment:**
Visual Studio Code on Windows 10

* **Angular version:** 5.0.X

* **PrimeNG version:** 5.2.X

* **Browser:** IE 11

 * **Screenshot (cannot include the whole page due to a client confidentiality clause):** 
![screenshot 13](https://user-images.githubusercontent.com/28817165/37464601-d0d50186-287e-11e8-91b7-430dad7db573.png)

* **Language:** TypeScript

**Comment by cagataycivici** [comment]
@Merve7 Please check this.

**Comment by hishamahamad** [comment]
I can't seem to even create a StackBlitz, since the primeng modules won't register themselves in the app.module file. I'm not alone in this (https://github.com/stackblitz/core/issues/300).

Also, this is an IE issue only, so I wouldn't be too sure if the bug would appear in StackBlitz. 

As to why I'm fixated on IE, enterprises love legacy apps. But you already knew that.
