### ISSUE TITLE
Individual timeouts for Growl Messages

### ISSUE THREAD

**Issue by ottosson** [primefaces/primeng#5362]
**I'm submitting a ...**
```
[ x ] feature request
```

**Current behavior**
When using growl with message service and add two messages at different times (but before timeout of first message), both messages will disappear simultaneously after second (last) message timeout is hit.  The first growl timeout is reset when another message has been added.

**Expected behavior**
The first message should disappear after its timeout is hit and the second should disappear when its timeout is hit.

**Minimal reproduction of the problem with instructions**
https://www.primefaces.org/primeng/#/growl
Click `add with service` two times with slight delay.

**What is the motivation / use case for changing the behavior?**
I don't want to see messages longer time than stated in timeout. If messages are continually added the first message will potentially never disappear and to read the last you will have to scroll the page.

**Please tell us about your environment:**
Windows 10

* **Angular version:** 2.0.X
5.2.6

* **PrimeNG version:** 2.0.X
5.2.0

**Comment by cagataycivici** [comment]
Growl is removed in favor of Toast.
