### ISSUE TITLE
p-table does not reset paging component

### ISSUE THREAD

**Issue by falexandre** [primefaces/primeng#5364]
**I'm submitting a ...**  (check one with "x")
```
[X] bug repor
[ ] feature request
[ ] support request
```

**Plunkr Case (Bug Reports)**
``
Note: Component p-table it's not working on  Plunkr 
``
https://stackblitz.com/edit/angular-tstheq

**Current behavior**
p-table component in onLazyLoad mode is not resetting pagination after refreshing information

**Expected behavior**
After removing the object from the arraylist the page component should go to the first page
``Note: Only using with the lazyLoadGrid event happens the same ``

**Minimal reproduction of the problem with instructions**
1. Click on page five
2. Click the delete button
``Note that the pager did not reset ``

**What is the motivation / use case for changing the behavior?**
Usability

**Please tell us about your environment:**
Visual Studio Code on Windows 10

* **Angular version:** 5.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [all]

* **Language:** [TypeScript 2.6.X ]

**Comment by cagataycivici** [comment]
Since it is a lazy table, you need to update totalRecords as well so that paginator can adjust.

**Comment by kk1687** [comment]
The issue is there even with v9, what could be the workaround ?
