### ISSUE TITLE
Dynamic ng-template in p-table or p-dataTable

### ISSUE THREAD

**Issue by Danieleeee** [primefaces/primeng#5367]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Expected behavior**
In Dynamic columns I can do this:
`<p-dataTable [value]="cars">
    <p-column *ngFor="let col of cols" [field]="col.field" [header]="col.header" [style]="col.style"></p-column>
</p-dataTable>`

How I can add dynamic(different) template for every columns like this?
`<ng-template pTemplate="filter" let-col>
                    <p-calendar (onSelect)="setFiltri(col.value,col.field)" [(ngModel)]="dataStato" dateFormat="dd/mm/yy" [locale]="calendario" appendTo="body"></p-calendar>
                </ng-template>`

* **PrimeNG version:** 5.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
You can use *ngSwitch, there is an example at;

https://www.primefaces.org/primeng/#/table/filter
