### ISSUE TITLE
AutoComplete - ui-state-filled is not updated when remove items thought backspace

### ISSUE THREAD

**Issue by rafa-as** [primefaces/primeng#5369]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/WxEuqszacvMAP5R6Hc9G?p=preview

**Current behavior**
When remove some value on AutoComplete multiple component thought the backspace key the input filled state is not updated properly.

**Expected behavior**
Apply the same behaviour as when you remove thought the chips cross.

**Minimal reproduction of the problem with instructions**
Try it on the provided plunkr - http://plnkr.co/edit/WxEuqszacvMAP5R6Hc9G?p=preview

1. Select one option on the autocomplete.
2. Remove thought backspace.
3. Look at the floating label doesn't come back to the initial position.

**What is the motivation / use case for changing the behavior?**
Get autocomplete component working properly with statuses.

**Please tell us about your environment:**
OS: MAC OS X High Sierra 10.13.3
IDE: WebStorm 2018.1 EAP
Package Manager: Yarn 1.5.1
Node: 9.8.0
Angular-cli: 1.7.3

* **Angular version:** 5.2.9

* **PrimeNG version:** 5.2.3

* **Browser:** all
 
* **Language:** TypeScript 2.6.2

* **Node (for AoT issues):** `node --version` =  9.8.0

**Comment by cagataycivici** [comment]
Fixed via PR, thank you.
