### ISSUE TITLE
DataTable selection two-way binding change detection not working

### ISSUE THREAD

**Issue by mdonato7** [primefaces/primeng#537]
Programmatically changing the value of the object bound to `[(selection)]` no longer updates the data table correctly. The following code worked as expected in beta 8: clicking on the detail link in any row would show that row's detail:

```
<p-dataTable [value]="items" selectionMode="single"  [(selection)]="selectedRow">
    <p-column field="Name" header="Name"></p-column>
    <p-column>
        <template let-item="rowData">
            <div>
                <a (click)="selectedRow=item;showDetail=true;">detail</a>
            </div>
        </template>
    </p-column>
</p-dataTable>
<div *ngIf="showDetail">    
    ID: {{selectedRow.ID}}
    Name: {{selectedRow.Name}}
    <a (click)="showDetail=false;">close</a>
</div>
```

In beta 9, selectedRow is undefined in the above example. The workaround is to remove the two-way binding to selection and manually handle changing the value of selectedRow with the `onRowSelect` event.

**Comment by mrmateo** [comment]
@mdonato7  - I have somewhat similar code using beta 10 and it is working correctly for me. Are you still seeing this error?

**Comment by mdonato7** [comment]
I can still reproduce this issue in beta 9 & 10, but it appears to be fixed in 11. I will close this issue based on that.
