### ISSUE TITLE
 This site appears to use a scroll-linked positioning effect.

### ISSUE THREAD

**Issue by janminarik** [primefaces/primeng#5371]
**Summary**
In PrimeNG [Avalon template] I get warnning message in Firefox

This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!

**Expected behavior**

No warnings in console.

 **Actual behavior**

This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!

**Angular version**: 5.2.0

**PrimeNG version**: 5.2.3

**Browser:** Firefox 59.0.1 64bit

**Language:** TypeScript 2.4.2

**Comment by cagataycivici** [comment]
Please use the Avalon-NG support forum;

https://forum.primefaces.org/viewforum.php?f=70

And our team will assist.
