### ISSUE TITLE
Use indexOf() instead of includes() in Accordion Component

### ISSUE THREAD

**Issue by ericrovtar** [primefaces/primeng#5372]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/qtZi5lB3DjkNt7Kdivg9?p=preview

**Current behavior**
Line 184 of your Accordion component uses `.includes()`, which isn't supported in IE11.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

https://github.com/primefaces/primeng/blob/master/src/app/components/accordion/accordion.ts#L184

**Expected behavior**
Could you replace this by the globally supported, `indexOf()`? Yes, I know it's annoying but it's really only one line that's making that component throw a ton of errors in IE11 (which our team still has to support).

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Changing one line will make this component fully compatible with IE11.

**Please tell us about your environment:**
Windows, VS Code

* **Angular version:** 5.X
5.2.1

* **PrimeNG version:** 5.X
5.2.1

* **Browser:** [IE 11]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by bossqone** [comment]
You can enable core-js polyfill in angular-cli project:
- open `src/polyfills.ts`
- add line `import 'core-js/es7/array';`

**Comment by ericrovtar** [comment]
Thanks, @bossqone. I didn't know that was a feature of Angular, tbh.

Looks like our project is only importing the `es6` versions of the polyfills. Does your team recommend always using the `es7` version?

Thanks again.

```
import 'core-js/es6/array';
import 'core-js/es6/date';
import 'core-js/es6/function';
import 'core-js/es6/map';
import 'core-js/es6/math';
import 'core-js/es6/number';
import 'core-js/es6/object';
import 'core-js/es6/parse-float';
import 'core-js/es6/parse-int';
import 'core-js/es6/regexp';
import 'core-js/es6/set';
import 'core-js/es6/string';
import 'core-js/es6/symbol';
```

**Comment by bossqone** [comment]
Hey @ericrovtar, from my point of view is good to use new language features if they can be polyfilled for older browsers. You can import only stuff you really need, so it won't increase bundle size so much.

**Comment by ericrovtar** [comment]
Thanks, @bossqone. I'll review with my higher ups who know Angular a bit more than I do. I appreciate the support and easy fix.
