### ISSUE TITLE
Selection issue in Turbo table 

### ISSUE THREAD

**Issue by marslan2037** [primefaces/primeng#5373]
there are couple of issues, 

1) when selectionMode is single, click on anywhere on row(other than checkbox) works fine, but click on check run onRowSelect and onRowUnselect at the same time, respectively.

2) with selectionMode="single", if row is selected by click on anywhere on row and you click on checkbox it gives error, (this.selection.filter is not a function) and do not unselect it.

3) when selectionMode is multiple,  click on anywhere on row(other than checkbox) works fine, click on checkbox when row is already selected works fine too, but when click on checkbox first time it run select and unselect at them same time. 

4) when one row is selected and you try to select another row by using checkbox , it gives error too when selectionMode is single and run both select and unselect at the same time when selectionMode is multiple 

here you can see all, 
http://plnkr.co/edit/gO4f2bLzGLPhg9k0im3s?p=preview

**Comment by marslan2037** [comment]
i have found a solution for it by adding little css,

.ui-table-tbody .ui-chkbox {
    pointer-events: none;
}

by doing this click works fine but now we have another issue, primeng doc suggest click on row fires a onRowSelect event and event.type tell us what type of click is this (like row, checkbox and radio) but by adding this css it always return event.type row and this is also a very much issue for me :( 

Need to fix this as soon as possible

**Comment by cagataycivici** [comment]
You can use metaKeySelection to configure these behaviors. Also if issue persists, please create a new ticket with a stackblitz template.

**Comment by marslan2037** [comment]
@cagataycivici how ?

**Comment by marslan2037** [comment]
it works using  metaKeySelection="true"

**Comment by marslan2037** [comment]
@cagataycivici here you can check it live, 
https://stackblitz.com/edit/primeng-turbo-table-os7cjs?file=app%2Fdata-table%2Fdata-table.component.html

right click on grid then left won't work on any other row
