### ISSUE TITLE
Template for TabView headers

### ISSUE THREAD

**Issue by ahmedGomaa90** [primefaces/primeng#5374]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report 
[x] feature request 
[ ] support request 
```

Sometimes we need to add a custom template for the tab header such as tooltips, so please provide support for template same as the content

thanks

**Comment by steigerm** [comment]
+1
Was actually looking for this today.

**Comment by OskarsPakers** [comment]
There is already support for header templates in TabView component. 
It is also documented in showcase https://primefaces.org/primeng/showcase/#/tabview section Custom Headers.
