### ISSUE TITLE
pInputText - Add clear button

### ISSUE THREAD

**Issue by rafa-as** [primefaces/primeng#5376]
**I'm submitting a ...**
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Expected behavior**
Be able to clear the pInputText like pDrowdown for example.

**What is the motivation / use case for changing the behavior?**
Has the same behaviour on all inputs set.

**Comment by rafa-as** [comment]
@cagataycivici it's something that the external contributors can do or can do it only the primeng team?

**Comment by cagataycivici** [comment]
We can add a demo but this better not be built-in. I'll ask a teammate to create the demo.

**Comment by rafa-as** [comment]
@cagataycivici som feedback by the teammate?
