### ISSUE TITLE
Custom Pagination on TurboTable 

### ISSUE THREAD

**Issue by comlabmohan** [primefaces/primeng#5378]
Hi Team,

Is there any way **manually trigger** the pagination on **TurboTable** . I didn't see **table.paginate()** method which i have already used in Datatable.

**Older Datatable Implemenatation:**

  this.datatableSample.first = ((this.currentPage - 1) * this.datatableSample.rows);
  this.datatableSample.rows = this.datatableSample.rows;
 this.datatableSample.paginate();

My page is having **pagenumber textbox** and **goto** **Button**, whenever user is typing number on textbox and clicking the button  the table has to paginate to that page . 

How to achieve the same in **Turbotable** . 

Please Help to resolve this issue

**Comment by steve-kuennen** [comment]
This would be an extremely helpful enhancement.  The built in paginator leaves a lot to be desired so I'd like to implement my own and simply call paginate on the grid as comlabmohan has suggested. Any chance we'll see this enhancmenet in the next few months?

**Comment by cagataycivici** [comment]
If you bind to the first property, changing it programmatically will cause pagination.

**Comment by MSCapNG** [comment]
Hi Team,
    Please let us know,how can we change page programmatically in turbo table. 

Thanks

**Comment by aziz52** [comment]
Hi Team,

Suppose I have a pagination in turbo-table, can I customize it to look like
page1, page2, ...., last page and perform the pagination accordingly based on the records present in p-table??
