### ISSUE TITLE
TurboTable: filter doesn't work when lazy is active

### ISSUE THREAD

**Issue by mainsys-crm** [primefaces/primeng#5379]
I use TurboTable and I need sort function and filter. Lazy loading is set to true, but when I try to filter, nothing happened.

--> When [lazy]=true, filter doesn't work. Nothing happened. (but sort function works)
--> If I set lazy to false, filter works but "onLazyLoad" event isn't triggered but i need it for my sort Function.

**Comment by cagataycivici** [comment]
You need to implement filter-sort yourself if lazy is enabled by hitting the backend.
