### ISSUE TITLE
p-table column reordering not working

### ISSUE THREAD

**Issue by jonbarthol** [primefaces/primeng#5380]
I'm submitting a ...

[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Plunkr Case (Bug Reports)**
This is reproducible on the PrimeNG demo page:
(https://www.primefaces.org/primeng/#/table/reorder)

**Current behavior**
When dragging a column to a new position, the new position is sometimes wrong. If I'm dragging a column to the left, and the mouse cursor is just to the left of a column boundary, the dragged/dropped column ends up one column too far to the left. Similarly, if I'm dragging a column to the right, and the mouse cursor is just to the right of a column boundary, the dragged/dropped column ends up one column too far to the right.

**Expected behavior**
The dragged/dropped column should be positioned where the up/down arrows indicate.

**Comment by cagataycivici** [comment]
Unable to replicate, please try with 6.x, there was a related issue fixed.

**Comment by jonbarthol** [comment]
This is still a bug. I just replicated the issue on the demo page again. Will open new issue.
