### ISSUE TITLE
Composite key for dataKeys

### ISSUE THREAD

**Issue by Raviowitch** [primefaces/primeng#5383]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/qtZi5lB3DjkNt7Kdivg9?p=preview

**Current behavior**
For now, datakey is only for one column.
example: dataKey="vin"

**Expected behavior**
Be able to give a array of column name.

**What is the motivation / use case for changing the behavior?**
Expandable row for table with composite key.

**Please tell us about your environment:**

* **Angular version:** 5.0

* **PrimeNG version:** 5.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by cagataycivici** [comment]
Like [dataKey]="['vin','brand']"?

**Comment by getjavajobs** [comment]
Hi,

I think that all these raised issues are related to the same problem - dataKey can't be always represented as single property of row:

https://github.com/primefaces/primeng/issues/5383
https://github.com/primefaces/primeng/issues/5574
https://github.com/primefaces/primeng/issues/5645

In my case I have array of arrays (trying to build table with expandable rows) and the dataKey for me is the rowData[0][0]

Is it possible to specify function that will generate unique dataKey based on rowData? In this case it can solve all problems

As a workaround for now I managed to mark row as expanded via let-expanded="isExpanded(rowData)" of body template.

**Comment by ammar91** [comment]
@cagataycivici Any plan to add this feature in the upcoming release?

**Comment by togbyte** [comment]
I need this feature as well.

**Comment by CyleClone** [comment]
Selection and Datakey isn't compatible with one another. What we'd need would be to be able to use datakey for row grouping, but have a selection that would still select (and mark) specific rows, not be based on the field used in datakey.

**Comment by niran-manandhar** [comment]
any solutions yet?

**Comment by SarahShhaltough** [comment]
<p-table
...
dataKey="key1" dataKey="key2">
I use this way and it works fine :D

**Comment by sanchaykothari** [comment]
I am using row grouping table with single selection and facing the same issue. Both The Functionality uses dataKey. Any alternative to do so ?

**Comment by sarojsahu81394** [comment]
I am also facing the same issue. if dataKey value will be same for two row it expands both the row.
Is there is solution to do that.

**Comment by DevByColton** [comment]
I created a pipe to add a `compositeDataKey` property to the object. It will join the values of the object properties together to create a unique value for each object. Example below

```
@Pipe({
  name: 'compositeDataKey'
})
export class CompositeDataKeyPipe implements PipeTransform {

  /**
   * Appends the compositeDataKey property to the object.
   * This 'compositeDataKey' property should be set to the [dataKey] input on p-table.
   *
   *
   * Example:
   *
   * <p-table [dataKey]="'compositeDataKey'">  <!-- dataKey input -->
   *   <ng-template pTemplate="header">
   *     ...
   *   </ng-template>
   *   <ng-template pTemplate="body">
   *     <a href="#" [pRowToggler]="object | compositeDataKey:['property1', 'property2']"> <!-- compositeDataKey pipe -->
   *       <i [ngClass]="expanded ? 'pi pi-chevron-down' : 'pi pi-chevron-right'"></i>
   *     </a>
   *   </ng-template>
   * </p-table>
   *
   * @param object
   * @param properties
   */
  transform(object: any, properties: any[]): any {
    if (object && properties?.length) {
      object.compositeDataKey = properties.map(property => object[property]).join('-');
    }
    return object;
  }
}
```

**Comment by suhailk4** [comment]
dataKey also takes a function as reference ( function without parenthesis) so you need to create a function and bind that to datakey , the function should return the keys that you want to combine with different columns as in primeNG we have 
    public static resolveFieldData(data: any, field: any): any {
        if(data && field) {
            if (this.isFunction(field)) {
                return field(data);
            }
            else if(field.indexOf('.') == -1) {
                return data[field];
            }
            else {
                let fields: string[] = field.split('.');
                let value = data;
                for(let i = 0, len = fields.length; i < len; ++i) {
                    if (value == null) {
                        return null;
                    }
                    value = value[fields[i]];
                }
                return value;
            }
        }
        else {
            return null;
        }
    } 
in above function it is checking if we have field a funtion , if yes then it calls the function we passed that function returns composite keys  . 

NOTE: The above function is just for understanding which is already in library so all we need to is  below code
----------------------HERE IS THE WAY TO IT --------------

 in html  [datakey]="someFucntion" 


in .ts 

someFunction(data: dataType) {
   
     // return data.field3 + data.field2 + data.field3 and so on ...
    return data.vin + data.brand;
}

**Comment by EthanTuning** [comment]
Is there any word on if this is possible?

**Comment by suhailk4** [comment]
> Is there any word on if this is possible?

please see my above comment - https://github.com/primefaces/primeng/issues/5383#issuecomment-728713523

**Comment by gokce-akcan** [comment]
Above solution didn't work for table with checkboxes. It checked all items in the list when using function. https://github.com/primefaces/primeng/issues/5383#issuecomment-728713523

Added a new unique key to the data.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
