### ISSUE TITLE
Wrong time value in input calendar

### ISSUE THREAD

**Issue by viveksaluja** [primefaces/primeng#5384]
I am giving 07:10 as input but The <p-calendar> Shows 08:40 PM. This occurs during timezone America/New_York
{{ data.time }} => 07:10 am 

But its working fine in case of IST time zone i.e Asia/Kolkata

My html is
<p-calendar [formControl]="form.controls['time']" [(ngModel)]="data.time"  dataType="string" [timeOnly]="true" [stepMinute]="5" hourFormat="12" inputStyleClass="ngPrimeDatePicker"> </p-calendar>

![joxi_screenshot_1521545181128](https://user-images.githubusercontent.com/28475360/37652023-7ab57930-2c10-11e8-8a6b-c30690306215.png)

**Comment by cagataycivici** [comment]
Please provide a working stackblitz template, demonstrating the issue. Also I'd suggest using dataType="date"
