### ISSUE TITLE
Editor not correctly displaying content

### ISSUE THREAD

**Issue by StickNitro** [primefaces/primeng#5386]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

http://plnkr.co/edit/RgVA9nevWIDITyb83rW5?p=preview

**Current behavior**
Not sure if this is a priming issue but this is the starting place, when I save the content of editor it returns the correct html, In the plunker example you can see the HTML displayed in the inplace display in two paragraph elements.

However, when the editor displays the text is displayed on a single line (as if the paragraph elements have been remove)

As you can see from the plnkr I am using model driven forms and setting the content through `patchValue` on init.

**Expected behavior**
The editor should render the content correctly, in the case of the plunker I would expect to be rendered as two <p> elements

**Minimal reproduction of the problem with instructions**
See plnkr above

* **Angular version:** 5.X
Angular 5.0.0

* **PrimeNG version:** 5.X
PrimeNG 5.2.0

* **Browser:** 
Chrome and Safari

**Comment by cagataycivici** [comment]
Unable to replicate with 6.x, if issue persists please create a new issue ticket and provide a test case using link below;

https://stackblitz.com/github/primefaces/primeng-issue-template

Thank you.

**Comment by bedodavid** [comment]
I have the issue:

```
<p-editor [ngClass]="getSliderHeight()" [(ngModel)]="myNote.text"  name="text" id="text" #my_editor [placeholder]="'FORM.LABEL' | translate" required>
    <p-header class="d-flex align-self-start">
         <ng-container [ngTemplateOutlet]="editorToolbar"></ng-container>
     </p-header>
</p-editor>
```
```
<ng-template #editorReleaseNotesToolbar>
  <span class="ql-formats">
    <button class="ql-header font-weight-bold" value="3" aria-label="Header">H<sub>3</sub></button>
  </span>
  <span class="ql-formats">
    <button class="ql-bold" aria-label="Bold"></button>
    <button class="ql-italic" aria-label="Italic"></button>
  </span>
  <span class="ql-formats">
    <button class="ql-script" aria-label="super" value="super"></button>
    <button class="ql-blockquote" aria-label="Block Quote"></button>
  </span>
  <span class="ql-formats">
    <button class="ql-list" title="List" value="ordered"></button>
    <button class="ql-list" title="Bullet" value="bullet"></button>
    <button class="ql-indent" title="Intend" value="-1"></button>
    <button class="ql-indent" title="Intend" value="+1"></button>
    <select title="Text Alignment" class="ql-align">
     <option selected>Gauche</option>
     <option value="center" label="Center"></option>
     <option value="right" label="Right"></option>
     <option value="justify" label="Justify"></option>
    </select>
  </span>
<ng-template>
```


then in the controller:
  ```
@ContentChildren('editorRN_DE') germanTextEditor: QueryList<any>;

myNote.text = '<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. </p><ol><li>At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. </li><li>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. </li><li>At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</li></ol>'
```

It should be 3 list item in the editor, bu instead i have only one

![image](https://user-images.githubusercontent.com/37118163/75170924-87b5ab00-5733-11ea-8817-eef8a5470553.png)

**Comment by adam-kuhn** [comment]
I'm having a similar issue. @bedodavid I know it's been a while but have you found a solution?
