### ISSUE TITLE
Missing contentElement of DataScroller

### ISSUE THREAD

**Issue by joaolevada** [primefaces/primeng#5388]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
The contentElement attribute of DataScroller is undefined, after the "Refactor on DataScroller" revision.

**Expected behavior**
The attribute should point to the contentViewChild.nativeElement

**Minimal reproduction of the problem with instructions**
Check the method bindScrollListener() of DataScroller

* **Angular version:** 5.X
Angular 5.2

* **PrimeNG version:** 5.X
PrimeNG 5.2.x

**Comment by cagataycivici** [comment]
Seems to be fixed in a previous release.
