### ISSUE TITLE
Icon doesn't work on <p-button></p-button> selector

### ISSUE THREAD

**Issue by Zbulu** [primefaces/primeng#5389]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
See the link to plunkr

http://plnkr.co/edit/xMBybWfw4FxIpeqzZKWy?p=preview

**Current behavior**
when using 
```html
<p-button icon="fa-minus" label="Delete"></p-button>
```
the icon is not correctly displayed

when one uses alternative syntax:
```html
<button pButton icon="fa-minus" label="Delete"></button>
```
icon is displayed however generated html is different 

**Expected behavior**
Icon should be correctly displayed

**Minimal reproduction of the problem with instructions**
go to http://plnkr.co/edit/xMBybWfw4FxIpeqzZKWy?p=preview
where you can observe incorrect behavior
or just add following code to your template:
```html
<p-button icon="fa-minus" label="Delete"></p-button>
```

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.2.0

* **PrimeNG version:** 5.2.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by tengel92** [comment]
I believe you'll need to add fa before the fa-minus. 
So `<p-button icon="fa fa-minus" label="Delete"></p-button>`

instead of  `<p-button icon="fa-minus" label="Delete"></p-button>`

**Comment by Zbulu** [comment]
That worked

**Comment by cagataycivici** [comment]
Doc fixed
