### ISSUE TITLE
primeng@1.0.0-beta.9 npm package does not contain systemjs.config.js file

### ISSUE THREAD

**Issue by jbialas-bb** [primefaces/primeng#539]
Performing `npm view primeng@1.0.0-beta.9` does not install the systemjs.config.js file as it is not included in the package.

Running `npm view primeng@1.0.0-beta.9` shows that the tarball is found at https://registry.npmjs.org/primeng/-/primeng-1.0.0-beta.9.tgz and untarring shows that the file is not included. Doing the same for the beta.8 package shows that it is included.

**Comment by jbialas-bb** [comment]
This was changed in f95857b

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
