### ISSUE TITLE
roblem while changing an input field (create using ng-template ) in checkbox selection feature.

### ISSUE THREAD

**Issue by goel-sunny** [primefaces/primeng#5390]
while i am selecting the a row by clicking the checkbox , and after selection when i am going to change the input field column of that row , at the time of clicking of that input field the entire row goes dis selecting, so is their is no combination possible of checkbox selection and input or button features using ng-template directive in angular2+.

**Comment by cagataycivici** [comment]
This is not a valid issue ticket as a stackblitz template is missing to demonstrate the issue. Please follow the issue guideline before creating new issues. If the issue still persists with the new version please create a new issue with our stackblitz template. Thank you.
