### ISSUE TITLE
Error during p-dialog autoAlign when NgAfterViewChecked

### ISSUE THREAD

**Issue by LoganFievez** [primefaces/primeng#5391]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
I have a dialog in my project and when I resize the window in Google Chrome only (ctrl + / ctrl - ), by default, the dialog is moving to the center of the screen but it's fixed and I cannot drag it again.

**Solution found**
So, after checking the documentation, I assumed that the autoAlign property is set by default to false. But, when I check the source code on GitHub on master branch, I discovered that autoAlign is set by default to true

* **PrimeNG version:** 5.X
5.2.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome

**Comment by cagataycivici** [comment]
I can't replicate, maybe step by step instructions can help. Docs are fixed by the way at code.
