### ISSUE TITLE
p-table after using filter(), cannot get table properties synchronously

### ISSUE THREAD

**Issue by YifeiCai** [primefaces/primeng#5394]
**Current behavior**
p-table: after using filter(), cannot get table properties, e.g. totalRecords and filteredValue, immediately. After 1s by using setTimeout, I could get expected values. It appears that filter() is asynchronous. This would result in big trouble by updating table from p-dataTable to p-table.

**Expected behavior**
get filtered value synchronously.

**What is the motivation / use case for changing the behavior?**
updating table from p-dataTable to p-table

**Please tell us about your environment:**

* **Angular version:** 5.0.3

* **PrimeNG version:** 5.2.3

* **Browser:** all
 
* **Language:**  TypeScript 2.4.2

**Comment by cagataycivici** [comment]
This is not a valid issue ticket as a stackblitz template is missing to demonstrate the issue. Please follow the issue guideline before creating new issues. If the issue still persists with the new version please create a new issue with our stackblitz template. Thank you.
