### ISSUE TITLE
Turbo table (p-table) p-cellEditor input blur event not getting triggered unless clicking.

### ISSUE THREAD

**Issue by kapiladiyecha** [primefaces/primeng#5395]
**I'm submitting a ...** 
```
[x] bug report

```

**Current behavior**
p-cellEditor input (blur) event not getting triggered unless **clicking**.

**Expected behavior**
p-cellEditor input (blur) event should be triggered on tab/esc or any other event which is causing un-focus from the element(standard behavior of **blur** event).

**Minimal reproduction of the problem with instructions**
Step 1: `p-table` with `onEditInit` event

Step 2: `p-cellEditor` like below

 ```
<p-cellEditor>
 
	<ng-template pTemplate="input">
	  <input type="text"
			 [(ngModel)]="record[col.field]"
			 (blur)="onColumnEditComplete($event, col, record)"/>
	</ng-template>
	
	<ng-template pTemplate="output">
	  <span>{{record[col.field]}}</span>
	</ng-template>
	
</p-cellEditor>
```

![p-table-issue](https://user-images.githubusercontent.com/6995248/37693949-f90f1a46-2cfd-11e8-9fa2-d3ef99de4894.gif)

* **Angular version:** 5.2.6

* **PrimeNG version:** 5.2.3

**Comment by kapiladiyecha** [comment]
## Workaround to above issue:

use `(keydown.tab)` / `(keydown.shift.tab)` / `(keydown.enter)`  / `(keydown.shift.enter)` / `(keydown.esc)` / `(keydown.shift.esc)` instead **`(blur)`** event.

## Suspected cause/resolution of this issue:

Before triggering blur event editing element dom `pTemplate="input"` is getting removed, so an event is not getting triggered.

So resolution maybe adding **100ms timeout(which allow event to be triggered) before switching** between `pTemplate="input"` to `pTemplate="output"` in core library.

Thanks

**Comment by cagataycivici** [comment]
This is not a valid issue ticket as a stackblitz template is missing to demonstrate the issue which is vital for us to provide asistance to your case. 

Please follow the issue guideline before creating new issues. If the issue still persists with the new version please create a new issue with our stackblitz template.

**Comment by kentonbmax** [comment]
I'm having this issue as well. onRowUnselect also does not return the unselected row data or an index. Anyone have a solution or work around?

**Comment by earshinov** [comment]
@kapiladiyecha , @kentonbmax , Either I got you wrong or the issue does not reproduce in 7.1.0.

StackBlitz: https://stackblitz.com/edit/primeng-celleditor-input-blur
