### ISSUE TITLE
Tooltip alignment issue:

### ISSUE THREAD

**Issue by punnepallivenkat** [primefaces/primeng#5398]
Hi ,

Tooltip top alignment is correctly working fine when the page is loading the first time and do any other actions in  the same page and go back to the previous page then that time tooltip top alignment is a move to left.Please find the attached zip file.

[Recording_6 zip.zip](https://github.com/primefaces/primeng/files/1833145/Recording_6.zip.zip)

Thanks,
Venkat P

**Comment by JacobSiegle** [comment]
Tried to reproduce it by toggling display with ngIf and hidden. Neither had the same effect. Can you create a plunk to reproduce?

**Comment by cagataycivici** [comment]
This is not a valid issue ticket as a stackblitz template is missing to demonstrate the issue which is vital for us to provide assistance to your case. 

Please follow the issue guideline before creating new issues. If the issue still persists with the new version please create a new issue with our stackblitz template.
