### ISSUE TITLE
p-selectButton : Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'

### ISSUE THREAD

**Issue by oumarkona** [primefaces/primeng#5399]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

When select button display an dialog or confirm popup, i get following error:

_**ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'.**_

Thank you for your understanding and your investigating.

**Expected behavior**

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/M6Vhk7WeQWFPsKXOHIM0?p=preview

**What is the motivation / use case for changing the behavior?**

Open popup when select button is selected

**Please tell us about your environment:**

PhpStorm

* **Angular version:** 5.2

* **PrimeNG version:** 5.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   8.9.4

**Comment by JacobSiegle** [comment]
Same issue as https://github.com/primefaces/primeng/issues/5004.

**Comment by CMoTheBoss** [comment]
Same behavior occurs with the p-InputSwitch when using the (onChange) event.  

Angular 5.1

PrimeNG 5.0.0 -  5.2.7; Also tested on 6.0.0

**Comment by cagataycivici** [comment]
This has been fixed before, please try with the latest version. It was a bug related to Dialog.
