### ISSUE TITLE
Error in Angular2 rc3

### ISSUE THREAD

**Issue by monoflash** [primefaces/primeng#540]
![Error](http://p.jiq.ru/1fXkd+)

```
platform-browser.umd.js:2311 Error: Name attribute must be set if ngModel is used within a form.
                      Example: <input [(ngModel)]="person.firstName" name="first">
```

The error appears on all components that use the input select checkbox textarea and etc ...

**Comment by dbrezoev** [comment]
I have similar problem when using dropdown `[(ngModel)]` binding causes `ORIGINAL EXCEPTION: No value accessor for ''` I think it is only in rc3.

**Comment by garethlewis** [comment]
I had this problem earlier today when using Beta 9 of NGPrime.  If where you are using the p-dialog you have the old @angular/forms declarations, this is going to happen.  p-dialog uses the new Angular forms version 0.1.1 and when mixed with the old versions of Angular forms, causes this issue.  Update your forms to use the new formGroup object and it will work.

**Comment by cagataycivici** [comment]
Not PrimeNG related, closing.
