### ISSUE TITLE
Paginator issue #2731 is closed but fix is not ported to 4.3 or 5.x

### ISSUE THREAD

**Issue by cdaughtr** [primefaces/primeng#5400]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/qtZi5lB3DjkNt7Kdivg9?p=preview

**Current behavior**

Errors using Firefox WAVE plugin on page using the paginator: Errors (4), 4 X Empty link.

This PR, https://github.com/primefaces/primeng/pull/3037, issue #2731, should fix the errors, but it appears that the fix did not get ported to 4.3 or 5.x.  Have installed primeng latest 4.3 and latest 5.x and the changes are not there when using inspector.  Also, have looked at the latest code in github primeng repository and do not see the changes from this PR.  Can this fix be ported to the latest 5.x?

**Expected behavior**

No 'Empty Link' errors from paginator using WAVE Evaluation Tool.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.X

* **PrimeNG version:** 5.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by anfeloaiza** [comment]
#2731 is not ported to 6.x either, please do so

**Comment by cagataycivici** [comment]
Not a valid issue report, backport requests are exclusive to PRO users I'm afraid.
