### ISSUE TITLE
Open Dropdown When Tab-Focused

### ISSUE THREAD

**Issue by maplion** [primefaces/primeng#5401]
**I'm submitting a ...**  (check one with "x")
```
[ x ] feature request 
```

**Current behavior**
When one clicks in a dropdown (especially with a filter), it opens and one can type immediately.  If one tabs into the dropdown, however, it does not open and extra keys must be pressed; but even then, the focus is not in the filter, so one can't start typing without clicking into the filter window.

**Expected behavior**
I expect that tabbing into a dropdown works the same as clicking it.

**My current solution:**
I didn't make a pull request because I am unsure of the fallout or Primeng's preferred methodology, but I was able to resolve this issue by changing two lines of code within the `dropdown.ts`.  I have the `onInputFocus(event)` call the `onMouseclick(event)` and then comment out `this.focusViewChild.nativeElement.focus();` within the `if (!this.itemClick && !this.clearClick)` conditional:

```
    onMouseclick(event) {
        if (this.disabled || this.readonly) {
            return;
        }

        this.selfClick = true;
        this.clearClick = this.domHandler.hasClass(event.target, 'ui-dropdown-clear-icon');

        if (!this.itemClick && !this.clearClick) {
            // this.focusViewChild.nativeElement.focus();

            if (this.panelVisible) {
                this.hide();
            } else {
                this.show();
                if (this.filterViewChild !== undefined) {
                    setTimeout(() => {
                        this.filterViewChild.nativeElement.focus();
                    }, 200);
                }
            }
        }
    }
...

    onInputFocus(event) {
        this.focus = true;
        this.onFocus.emit(event);
        this.onMouseclick(event);
    }
```

**What is the motivation / use case for changing the behavior?**
Better usability, especially on forms.

**Please tell us about your environment:**
Windows 10, Visual Studio Code

* **Angular version:** 5.X
5.2.6

* **PrimeNG version:** 5.X
5.2.3

* **Browser:** 
Chrome / Edge / Firefox
 
* **Language:** 
Typescript

**Comment by cagataycivici** [comment]
Tab does not open a native element as well, alt+down key opens it like p-dropdown.

**Comment by maplion** [comment]
@cagataycivici Did you close this because you added this feature or you're ignoring the request?
