### ISSUE TITLE
Feature: allow tabMenu tab to be set programmatically 

### ISSUE THREAD

**Issue by chriskyndrid** [primefaces/primeng#5403]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
I'd like to request that you a add a feature similar to:

[2253](https://github.com/primefaces/primeng/issues/2253).

Use case scenarios:

1) Activating a tab arbitrarily without the user clicking on the tab. 
2) Preventing a user from activating a tab and routing them to the previous tab based on arbitrary conditions. 
3) Many more....

Let me know if I'm missing something or there is another way to dynamically set the displayed tab in code. ActiveItem is useful only in setting the initial loaded tab it appears. 

Thank you.

Chris

**Comment by cagataycivici** [comment]
You can do it using the activeItem property.
