### ISSUE TITLE
DataTable Global filter needs to work with Pipe Transformed column data.  

### ISSUE THREAD

**Issue by hlaghari** [primefaces/primeng#5405]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/qtZi5lB3DjkNt7Kdivg9?p=preview

**Current behavior**
Currently the DataTable global filter doesn't work if you are using Pipe transformation or a function based transformation, because the data that is bound with the table is now transformed. the table still understand the bound data but not the transformed one.

**Expected behavior**
Can we add some sort of property or a PIPE attribute to the column so we don't have to do {{data | pipe}} in a template column and the data table picks the pipe transforms the column data and also use the same pipe while applying filtering on that particular column through global filter. 

**Minimal reproduction of the problem with instructions**
`<ng-template let-row="rowData"  pTemplate="body">
           <div *ngIf="col.field.indexOf('TimeCreated')!=-1" >
            <div>{{row.TimeCreated ? (row.TimeCreated | date) : ''}}</div>        
          </div> 
</ng-template> `
 and now as this inside my p-column and the template is also using the pipe to transform the data the filter would work .

**What is the motivation / use case for changing the behavior?**
Everyday we come across this issue where that data coming through the api need some transformation so it is displayed nicely on the front end, but then the global filter doesn't work on that column. :(

**Please tell us about your environment:**

* **PrimeNG version:**
5.2.3

**Comment by JacobSiegle** [comment]
Can't you just pipe the data in your model before you put it into the table? Why make the primeNG component do it?
