### ISSUE TITLE
Your codebase doesn't build and run

### ISSUE THREAD

**Issue by Neutrino-Sunset** [primefaces/primeng#5409]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Following the build instructions does not successfully build the software.

**Expected behavior**
Following the build instructions would successfully build the software.

**Minimal reproduction of the problem with instructions**
Clone or donwload your codebase from https://github.com/primefaces/primeng

Open in VSCode.

Run 'npm i'

Following your wiki instructions here https://github.com/primefaces/primeng/wiki/Building-From-Source attempt to run 'sass --update src/assets/components' which will fail because there is no 'sass' command in package.json and no sass executable in node_modules/.bin

Run 'ng serve'

None of the showcase components have any visual representation.

**What is the motivation / use case for changing the behavior?**
I'm trying to the run the showcase components from source in order to test styling them, which also does not seem to work as described in the documentation. Specifically setting [style] on p-progressBar is ignored.

**Please tell us about your environment:**

Win7
VSCode 1.21.1

* **Angular version:** 5.X
@angular/core@5.2.9

* **PrimeNG version:** 5.X
primeng@5.2.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome

* **Node (for AoT issues):** `node --version` =  v8.10.0

**Comment by Neutrino-Sunset** [comment]
If you don't have an executable called 'sass' installed your codebase can be built as follows.

npm i node-sass --save-dev
./node_modules/.bin/node-sass ./src/assets/components -o ./src/assets/components

Since this is a nodejs build environment I think it would make sense to build your sass in nodejs and add this to your build step instead of assuming your users have additional third-party binaries installed.

**Comment by cagataycivici** [comment]
Not a valid issue ticket.

**Comment by Neutrino-Sunset** [comment]
Why is the fact that your codebase doesn't build using your own build instructions not an issue?

I have even gone to the trouble to show you how to fix it. So why not just fix it? Or give me permissions to edit the Wiki and I'll even do it for you.

Stuff that doesn't build cleanly when following its own build instructions is the scourge of Open Source.
