### ISSUE TITLE
Alert Message When Click on outside primeng sidebar or 'X'

### ISSUE THREAD

**Issue by ramukodandapuram** [primefaces/primeng#5411]
I wanted  go back to parent route when click on either outside primeng sidebar or Cross 'X' .  I put some alert messages by calling **close($event)** but no response. please help me out of this.

**Comment by JacobSiegle** [comment]
There is no close event emitted? Use onShow and onHide. Read https://www.primefaces.org/primeng/#/sidebar.

**Comment by diegosilva13** [comment]
Call 
```html
<p-sidebar [(visible)]="display" (onHide)="myCloseEvent();">
    Content
</p-sidebar>
```

Name | Parameters | Description
-- | -- | --
onShow | event: Event object | Callback to invoke when dialog is shown.
onHide | event: Event object | Callback to invoke when dialog is hidden.

[Docs](https://www.primefaces.org/primeng/#/sidebar)

**Comment by ramukodandapuram** [comment]
Thanks @diegosilva13. Now it's working.
