### ISSUE TITLE
Body scrolls on touch devices when p-dialog is open, even with blockScroll="true"

### ISSUE THREAD

**Issue by dhniels** [primefaces/primeng#5413]
The newly added `[blockScroll]="true"` property for p-dialog works excellently on desktop. However mobile/touch devices (in this case, an iPhone 7+ on the latest version of iOS) don't seem to honor this requirement. When I open a dialog with overflowing content and try to scroll down (swiping my finger up/down), it scrolls the body (the content _behind_ the dialog) instead of the dialog content itself.

Inside the chrome/safari/firefox dev tools, this issue is not present. It only happens on physical touch devices. I don't have an android device to test this on, but right now I'm able to confirm this behavior on ipad/iphone with the latest version of iOS, Angular, and PrimeNG .

**Comment by danteorlando-acgov** [comment]
I can also confirm that this is an issue with my iPhone 6. I have the latest version of iOS and am using Angular 5.2.0 and PrimeNG 5.2.0.

**Comment by pedrotcm** [comment]
It still occurs in the last version of ios e primeng 5.2.6. On any android works properly.

**Comment by nagarjunacts** [comment]
Facing the same issue (swiping my finger up/down), it scrolls the body ,the content behind the dialog)  in IPad. Is this issue getting fixed.

**Comment by mmavko** [comment]
Wait, guys, you can't do this!

This breaks normal behavior. See here: http://jsfiddle.net/mmavko/hLu25v63/4/

**Comment by jari-thiels** [comment]
Reopen this issue after revert in [5b41a3b](https://github.com/primefaces/primeng/commit/5b41a3bf18dcdbdd0b112c19c9aad803470e835b)?
Still got the problem on PrimeNG 6.1.4 (tested on iPad Air 2 - iOS 12.0)

**Comment by danteorlando-acgov** [comment]
Is this going to be re-opened or has it been addressed by another issue?

**Comment by mmavko** [comment]
Looks like this was fixed in 6.1.3: https://github.com/primefaces/primeng/blob/6.1.3/src/app/components/common/common.css#L157-L159
