### ISSUE TITLE
TurboTable sort icon

### ISSUE THREAD

**Issue by pantonis** [primefaces/primeng#5423]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
Sort icon in turbotable cannot be changed

**Expected behavior**
It would be nice to be able to specify the sorting icon for the turbotable

**Comment by cagataycivici** [comment]
You can change it with CSS, it is a font icon.

```
.ui-sortable-column-icon.fa-sort-asc:before {
        content: "\f09b";
}
```

**Comment by pantonis** [comment]
OK that works but I think you got ascending and descending opposite. Desending should show the up-arrow and ascending down-arrow

**Comment by pantonis** [comment]
@cagataycivici This is no longer valid for TurboTable 6.0.0. Can you suggest how to do it now?
