### ISSUE TITLE
Dropdown keyboard navigation

### ISSUE THREAD

**Issue by Mysame** [primefaces/primeng#5426]
**I'm submitting a ...**  (check one with "x")
```
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
```

Currently on roadmap:
Keyboard based search to highlight an item based on intervals between typing.

Requested improvement:
Imagine you have a dropdown containing:
Abraham
Bruno
Mark
Sara

Pressing "M" should select "Mark".

**Comment by vpnocsen** [comment]
I also want that. For currently, i enable the filter feature so user can type what they want, but still have an issue of the keyboard event up and down after filtering the list:
-  should have select the first option of the list when hit enter
- when up and down by keyboard in the empty filtered list, it will empty the selected data also

**Comment by Mysame** [comment]
Seems to have been stealth-added.
Thanks.
