### ISSUE TITLE
Missing padding for ui-inputgroup-addon in overlayPanel

### ISSUE THREAD

**Issue by skappler** [primefaces/primeng#5428]
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When placing an inputgroup with an addon inside a p-overlayPanel the icon in the addon is missing padding on the left and right. The reason seems to be the `.ui-widget, .ui-widget * {
    box-sizing: border-box;}` css class. I noticed the same behavior in a p-dialog.

![screenshot_2018-03-26_19-57-46](https://user-images.githubusercontent.com/2983995/37923917-ab824384-3130-11e8-869f-e659b3f33ace.png)

**Expected behavior**
The padding should be normal

* **Angular version:** 5.X
5.0.0

* **PrimeNG version:** 5.X
5.2.3

* **Browser:** 
Chromium 63

**Comment by cagataycivici** [comment]
Unable to replicate with 6.1.0.
