### ISSUE TITLE
TurboTable - Filtering on columns with multiple values

### ISSUE THREAD

**Issue by Kazul28** [primefaces/primeng#5430]
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap

**Current behavior**
TurboTable only allows filtering based on the following filterConstraint: startsWith, contains, endsWith, equals, notEquals, in, gt, lt. 

None of these modes allows you to filter on a column that displays multiple values in it. 
Example
**Color // Contains These**
Red // Red
Blue // Blue
Yellow // Yellow
Green // Blue, Yellow
Orange // Red, Yellow
Purple // Red, Blue
Black // Red, Blue, Yellow

I want to filter on all colors that contain Blue

Yes, "contains" would technically work in this situation but what if the values were IDs - "contains" would would then think that 5 would match 55 cause it's comparing string values.

**Requested behavior**
Create an new filterConstraint:

```javascript
<insert_name_here>(value any[], filter: any[]): boolean {
            if (filter === undefined || filter === null || filter.length === 0) {
                return true;
            }

            if (value === undefined || value === null) {
                return false;
            }

            for (let i = 0; i < value.length; i++) {
                for (let j = 0; j < filter.length; j++) {
                     if (value[i] === filter[j])
                         return true;
                }
            }

            return false;
}
```

**Comment by yigitfindikli** [comment]
Fixed with [ColumnFilter.](https://primefaces.org/primeng/showcase/#/table/filter)
