### ISSUE TITLE
Please add custom class property to growl for each message using the options

### ISSUE THREAD

**Issue by shahard** [primefaces/primeng#5432]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Please add an option to add a custom class for each growl message opened using a service.
This will allow styling each message specifically depending on its' class.

**Current behavior**

Using the styleClass like this:
`<p-growl styleClass="notification-warning"></p-growl>`

and opening multiple growl(s) using the service:
`this.messageService.add({
			severity: 'success',
			summary: 'Title',
			detail: 'message'
		});`

severity class 'success' does apply to each message specifically, but the optional values are limited only to 'success' / 'warn' / 

**Expected behavior**

Using the styleClass like this:
`<p-growl styleClass="notification-warning"></p-growl>`

and opening multiple growl(s) using the service:
`this.messageService.add({
			severity: 'success',
			msgClass: 'my-msg-class',
			summary: 'Title',
			detail: 'message'
		});`

should add the class specified in 'msgClass' (or rename this property to anything else that makes sense) thus allowing more customisation for each message specifically.

**What is the motivation / use case for changing the behavior?**
Currently it's not possible to change each growl message's class.
Instead, changing p-growl's 'styleClass' attribute changes the container's class for all the messages.
In case I want to override the default styles and add an icon depending on the class, for example, I have to use one of the four preset classes that the messages options support: success, info, warn or error.

* **Angular version:** 5.X

Angular CLI: 1.7.1
Angular: 5.2.6

* **PrimeNG version:** 5.X

5.2.0
 
* **Language:** [TypeScript X.X]
2.4.2

**Comment by cagataycivici** [comment]
Growl is deprecated in favor of toast.
