### ISSUE TITLE
sortMode doesn't work in DataTable

### ISSUE THREAD

**Issue by gtzinos** [primefaces/primeng#5434]
Hello,

I faced an issue in your DataTable  documentation. The parameter sortMode = 'multiple' doesn't work.

https://www.primefaces.org/primeng/#/datatable/sort

**Comment by sridhark158** [comment]
+1

**Comment by JacobSiegle** [comment]
Datatable is deprecated. It looks like it does work in the example doc. You won't get support for the old data table anymore.

This is a question not an issue from what I can tell, post here - https://forum.primefaces.org/viewforum.php?f=35
