### ISSUE TITLE
Feature request: Add 'optionValue' to multiselect

### ISSUE THREAD

**Issue by coffeymatt** [primefaces/primeng#5435]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request 
```

Can you add an option to multiselect to include 'optionValue'. There is currently an optionLabel property but no way to choose a property to represent value so you end up with the whole object.

**Comment by shamoh19** [comment]
Team any update on this? this is really needful feature

**Comment by coffeymatt** [comment]
Bump?

**Comment by cagataycivici** [comment]
We'll reconsider if more users demand it, currently optionValue is the object itself so you have full access already.

**Comment by coffeymatt** [comment]
@cagataycivici You have access to the object, but you can't bind a value from said object to your ngModel so it adds a bunch of onchange code to use it which is rather inflexible. Seems like low hanging fruit, please reconsider.

**Comment by yelhouti** [comment]
@cagataycivici I wanted this for so long, here are others: #4295 #6630 #4465 #4879 and this one.
Do you mind me making a pull request? Also I'm working on this: https://github.com/elhoutico/jhipster-primeng-blueprint and this will greatly help

**Comment by yelhouti** [comment]
@cagataycivici https://github.com/primefaces/primeng/pull/7279 please accept it. And by the way, very clean code, loved it !!!

**Comment by cghislai** [comment]
you can still create an array of SelectItem if you want to use any arbitrary value/label pairs, this is covered in the docs. You can extend the SelectItem inteface if you need more information to display the item options in the template.

**Comment by yelhouti** [comment]
@cghislai Indeed, I didn't say I couldn't work at all, the code is just cleaner the other way.
You often need your array of objects for another reason don't want to have to handle it twice one in the form: `SelectItem[]` and one like `myObject[]`.
Also, the Dropdown could work without OptionLabel by using SelectItem but they added it for the same reason.
