### ISSUE TITLE
Upload File button accepting tab key press twice in IE

### ISSUE THREAD

**Issue by deveshsinghal22** [primefaces/primeng#5438]
I am submitting an Bug Report. 
in upload file, when we navigate through TAB key in IE. browse button is holding tab for twice.
ideally it should be accepting tab single time only. 
This issue is coming on file upload example on primeng as well.

open below url in IE and try to navigate page using TAB.

https://www.primefaces.org/primeng/#/fileupload

**Comment by cetincakiroglu** [comment]
Hi,

If the issue still exists with the latest PrimeNG version, please provide a StackBlitz example by using [PrimeNG Issue Template ](https://stackblitz.com/github/primefaces/primeng-issue-template) and re-open the issue.

Regards
