### ISSUE TITLE
Can't pass a row expansion template to p-dataTable with ng-content

### ISSUE THREAD

**Issue by ryanwawr** [primefaces/primeng#544]
I currently have a custom component wrapping a general implementation of the p-dataTable component. I would like to be able to pass in a row expansion template for the table by using an ng-content directive so that I can easily specify different templates for each table.

This is the setup I'd like to have:

Template including a directive for the custom component wrapping p-dataTable:

```
<my-custom-component [rows]="data">
    <my-custom-component-template>
        <template let-row>
            <div *ngIf="row != null">
                <div *ngIf="row.text == ''">No text</div>
                <div *ngIf="row.text != null">{{row.text}}</div>
            </div>
        </template>
    </my-custom-component-template>
<my-custom-component>
```

Template for my-custom-component, the component wrapping p-dataTable:

```
<p-dataTable [value]="rows" [otherAttributes]="etc">
    <ng-content select="my-custom-component-template"></ng-content>
    ...
</p-dataTable>
```

If I directly replace the ng-content block in the custom component's HTML with the <template let-row> element and it's children, everything works as expected. However, if I use the setup shown above, nothing is displayed in the expanded area when I toggle a row. It seems like whatever is binding "let-row" to the data in the associated row doesn't work when the template is projected in using ng-content. 

I've worked around this for now by listening to the onRowExpand event, but this solution only allows me to have one row expanded at a time, which is manageable, but not ideal. Would love to see this functionality in the future.

**Comment by gnovotny** [comment]
How did you solve this using the onRowExpand event? It's been a while so maybe you've found a better solution by now?

**Comment by ryanwawr** [comment]
Haven't really looked at it since then, as I didn't need anything more than what I got with the workaround. summary of what I did is below.

Custom component wrapping p-dataTable:
```
<p-dataTable [value]="rows" [otherAttributes]="etc">
    <ng-content select="my-custom-component-template"></ng-content>
    ...
</p-dataTable>
```

Instance of custom component where I am defining a template for that instance:
```
<custom-component [rows]="notes" [isExpandable]="true" (rowExpanded)="onRowExpanded($event)">
    <my-custom-component-template>
        <div *ngIf="expandedRow != null">
            <div>
                <span>Label: </span>
                <span *ngIf="expandedRow.someContent == ''">[None]</span>
                <span *ngIf="expandedRow.someContent != null">{{expandedRow.someContent}}</span>
            </div>
        </div>
    </my-custom-component-template>
    ...
</custom-component>
```

Then the workaround is mostly in the component file for the instance of the custom component: 
```
onRowExpanded(expandedItem: Item) {
        // Toggle expanded/collapsed state of row if: 
        //    1) not null
        //    2) not the row being expanded (to avoid simultaneous collapse/ expand)
        //    3) not already collapsed
        if (this.expandedRow != null && this.expandedRow !== expandedItem && this.customComponent.dataTable.findExpandedRowIndex(this.expandedRow) !== -1) {
            this.customComponent.dataTable.toggleRow(this.expandedRow);
        }
        this.expandedRow = expandedItem;
    }
```

Basically just looking at the row object for the row being expanded, calling into dataTable to toggle it manually, then copying it to a local object that gets rendered in the template above. My solution only works for one row expanded at a time, which is a bit annoying, but that was all I needed. You could theoretically make it work for multiple rows, but I would imagine that would get quite messy.

**Comment by gnovotny** [comment]
Thanks for this.

My current workaround requires a service and involves dynamically loading a component so definitely messier than this but it does allow for multiple expanded rows.

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.

**Comment by AnthonyHache** [comment]
Using primeng 4.2.1 and this is still an issue. rowExpansion content cannot be passed from wrapper component to the <p-table> tag using ng-content.
