### ISSUE TITLE
Date support for Table filtering

### ISSUE THREAD

**Issue by greggyPL** [primefaces/primeng#5441]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Currently TurboTable offers only a few match modes ( "startsWith", "contains", "endsWith", "equals" and "in"). But none of them cooperate with date objects. So now there is no option to filter TurboTable results by dates and date ranges. 

**Expected behavior**
There should be option to add custom match mode or custom filter mode, which could be used to filter data in column. For example - I want to use Calendar component to select date range and use result of it to filter data in TurboTable.

**Comment by stuartwildcat** [comment]
I think overall TurboTable does not work with Date objects correctly.  I found this in trying to include dates in a multisort and not getting the behavior expected.  It is reported in the bug filed below:
https://github.com/primefaces/primeng/issues/5419

I don't think it is reasonable to expect TurboTable to be able to filter/sort on just any arbitrary object but I agree Date is a very common thing included in table data that should be able to sort/filter by.

**Comment by cosminadrianpopescu** [comment]
As a workaround, you can add a custom behavior quite simple for the moment. 

`template.html`:

```
<p-table #table ...>...</p-table>
```

Then, in your component you can do this:

```
import Table from 'primeng/table';
...
@Component({...})
export MyComponent implements OnInit {
    @ViewChild('table') private _table: Table;
    ngOnInit(){
        this._table.filterConstraints['my'] = (value, filter): boolean => {\
            // Make sure the value and the filter are Dates
            return value.getTime() == filter.getTime();
        }
    }
    private _filter(value, field){
        this._table.filter(value, field, 'my');  // Notice the "my" from match modes
    }
}
```

**Comment by skormel** [comment]
@cosminadrianpopescu I'm trying to used your solution using this code:
`
 @ViewChild('tt', undefined) turboTable: Table;
......
  ngOnInit() {
......
    this.turboTable.filterConstraints['date'] = (value: any, filter: any): boolean => {
      return value.getTime() === filter.getTime();
    };
  }
`

But I get this error:
`ERROR in src/app/dashboard/components/table-creator/table-creator.component.ts(194,5): error TS7017: Element implicitly has an 'any' type because type '{ startsWith(value: any, filter: any): boolean; contains(value: any, filter: any): boolean; endsW...' has no index signature.`

I've tested with prime 5.2.7 and 6.0.0.alpha1 with the same error

How can I solve this?

Thanks for all

**Comment by cosminadrianpopescu** [comment]
I would assume that this is because you are using --noImplicitAny. Check this out: https://stackoverflow.com/questions/32968332/how-do-i-prevent-the-error-index-signature-of-object-type-implicitly-has-an-an

If you cannot change the `--noImplicitAny` option, then try something like this:

```
(<any>this.turbuTable.filterConstraints)['date'] = ...
```

**Comment by skormel** [comment]
I solved declaring turboTable as any type.
