### ISSUE TITLE
PrimeNG Dialog not working with NgZones / SearchElementRef

### ISSUE THREAD

**Issue by Brenton30** [primefaces/primeng#5444]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Currently I have the newest version of PrimeNG installed with Angular 5. When I put the content for the google maps autocomplete inside the p-dialog the changes event dosen't seem to be firing off and it no longer works. However, it works as expected when not inside the p-dialog. Is there any reason why this is?

HTML:
![capture](https://user-images.githubusercontent.com/28558058/38027438-912d6d4e-3287-11e8-864a-30bdea441c43.PNG)

TS:

`  @ViewChild('search')
  public searchElementRef: ElementRef;

      this.mapsAPILoader.load().then(() => {
        const autocomplete = new google.maps.places.Autocomplete(this.searchElementRef.nativeElement, {
          types: ['geocode'],
          componentRestrictions: { country: this.plan.Country}
        });
        autocomplete.addListener('place_changed', () => {
          this.setLocMap.reset(this.plan.Lat, this.plan.Lng);
          this.ngZone.run(() => {
            //get the place result
            const place: google.maps.places.PlaceResult = autocomplete.getPlace();

            //verify result
            if (place.geometry === undefined || place.geometry === null) {
              return;
            }
            this.setLocMap.placeError = true;
            if (this.distance( place.geometry.location.lat(), place.geometry.location.lng(), this.plan.Lat, this.plan.Lng) * 1000 <= this.plan.TravelDistance) {
              this.setLocMap.placeError = false;
              this.setLocMap.lat = place.geometry.location.lat();
              this.setLocMap.lng = place.geometry.location.lng();
              this.setLocMap.placeName = place.name;
              this.setLocMap.validPlace = true;
            }
          });
        });
      });
`

![fdfdfs](https://user-images.githubusercontent.com/28558058/38027387-5c868292-3287-11e8-977c-355600d624cf.PNG)

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 
Most recent

* **PrimeNG version:** 
Most recent

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by Brenton30** [comment]
FIXED...

Found out this was nothing to do with the events not firing and actually to do with the Z index, I turned autoZIndex to false and then the autocomplete was shown.

**Comment by JAYiSON021** [comment]
Other solution: if you want to enable the modal mode, you still want to enable autoZIndex and you are using Google Maps Autocomplete then you can change the .pac-container css class of google maps to a much larger z-index value.
```
.pac-container {
    z-index: 10005000 !important;
}
```
