### ISSUE TITLE
Add hideOnSelect property to Calendar with selectionMode of range

### ISSUE THREAD

**Issue by DavidOs55** [primefaces/primeng#5445]
**Current behavior**
When I select the second date in the calendar with range selectionMode , the calendar doesn't close untill I click outside the calendar

**Expected behavior**
The calendar should close when I select the second date(to date) of a range or add a property with boolean value so I can choose between the two options : Calendar stay open after selecting the seconed date or should close after it. 

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.X
5.2.0

* **PrimeNG version:** 5.X
5.2.3

* **Browser:** [all | Chrome 64.0.3282.186 (Official Build) (64-bit) | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript 2.5.3 | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by lfongaroScp** [comment]
As workaround I add a method on onSelect event.

my code:

```
@ViewChild('calendarRange')
  calendarRange: Calendar;

//code

onSelect(event) {
    if (this.rangeDates && this.rangeDates.length == 2 && this.rangeDates[1] != null) {
      this.calendarRange.hideOverlay();
    } 
  }
```

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
