### ISSUE TITLE
TurboTable IE and Edge Resizable Columns Highlight

### ISSUE THREAD

**Issue by bwilfong3** [primefaces/primeng#5446]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
None

**Current behavior**
Resizing columns in the default resizing mode (fit) highlights table text in IE 11 and Edge.
IE 11 Example:
![tt-ie11-highlight](https://user-images.githubusercontent.com/16851699/38040997-ee63969c-326d-11e8-9d85-10962073b4c3.gif)

**Expected behavior**
Resizing column widths should not highlight text.

**Minimal reproduction of the problem with instructions**
1) Implement the resizable columns example (fit) from the PrimeNG documentation.
2) Resize columns in Edge or IE11. All column headers and table data past the drag handle (from left to right) will be highlighted.

**What is the motivation / use case for changing the behavior?**
The highlighting is quite distracting and not an issue in the deprecated p-datatable. If the text is highlighted and the user tries to drag again, the browsers will override the resizing logic to drag/drop the highlighted text.

**Please tell us about your environment:**
Windows 10, Atom

* **Angular version:** 5.X
Angular 5.2.9

* **PrimeNG version:** 5.X
PrimeNG 5.2.3

* **Browser:** 
IE 11
Edge
 
* **Language:**
Typescript 2.4.2

* **Node (for AoT issues):** `node --version` =   
N/A

**Comment by harshdevj** [comment]
+1

**Comment by hongyangsong** [comment]
The problem here. tried their demo web page for resizing the same issue on IE and Edge

**Comment by cagataycivici** [comment]
We can just call event.preventDefault.
