### ISSUE TITLE
Components inside of SharePoint SPFX and ChangeDetection

### ISSUE THREAD

**Issue by johnfabian** [primefaces/primeng#5447]
I'm trying to use some of the components (selectButton) inside of the SharePoint SPFX framework and need to call ChangeDetectionRef manually and notice I cannot set an initial value, the value does not set the selected item.

**Comment by cagataycivici** [comment]
This is not a valid issue ticket as a stackblitz template is missing to demonstrate the issue which is vital for us to provide assistance to your case. 

Please follow the issue guideline before creating new issues. If the issue still persists with the new version please create a new issue with our stackblitz template.
