### ISSUE TITLE
p-confirmDialog should support template

### ISSUE THREAD

**Issue by kapiladiyecha** [primefaces/primeng#5448]
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see 

**Current behavior**
p-confirmDialog does not have support for `ng-template` for header/message content, instead of just plain text message and header!

**Expected behavior**
It should support `ng-template`, so that user can design whatever way he wants.
Big advantage would be `ngx-translate`. (Alternative is to translate it from component ts file, but not recommended at all)

* **Angular version:** 5.2.6

* **PrimeNG version:** 5.2.3

* **Browser:** all
 
* **Language:** all

**Comment by grifin85** [comment]
This issue should be open, because didn't create `ng-template` for message.
