### ISSUE TITLE
Wrong default type of p-button

### ISSUE THREAD

**Issue by Zbulu** [primefaces/primeng#5453]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
Default type for standard html button is submit
same for 
```html
<button pButton>
```
however for some reason default type for 
```html
<p-button>
``` 
is button

**Expected behavior**
default type should be the same for pButton and p-button

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
To have consistent behavior for button element no matter which selector is used
  
* **PrimeNG version:** 5.2.3

* **Browser:** all

**Comment by Venthe** [comment]
I'm also having this issue, please look into it

**Comment by Zbulu** [comment]
Any response to that? Its been few months since reported...
