### ISSUE TITLE
p-button disabled attribute doesn't behave as expected on all browsers.

### ISSUE THREAD

**Issue by Wassim24** [primefaces/primeng#5454]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

https://stackblitz.com/edit/angular-zsuen9

**Current behavior**
When you use a p-button component and give it the attribute `[disabled]=true`, the button still works in Google Chrome, but in Firefox it is really disabled

**Expected behavior**
The button does nothing on all browsers when it has the disabled attribute.

**Minimal reproduction of the problem with instructions**
I posted a Stackblitz link where you can experience the same issue.

* **Browser:** [Chrome 65.0.3325.181 ]
 
* **Language:** [TypeScript 2.3]

**Comment by jupin-r** [comment]
If you use p-button component then right attribute is onClick (instead of click). See the documentation of the button component (chapter Properties of p-button) https://www.primefaces.org/primeng/#/button

**Comment by Wassim24** [comment]
Aw ! I missed it ! Sorry for posting this as a bug !
Thank you very much @jupin-r :)

**Comment by jupin-r** [comment]
@cagataycivici Could you close it?

**Comment by leopardy** [comment]
These type of issues which turn out to not be bugs are so important to post anyway because others will have the same issue. I'm so glad I found this! I was banging my head against the wall when my p-button would still trigger the click event when disabled.

**Comment by shafiquelislam** [comment]
Still happening this issue. One hack I did to prevent executing click event. Just return from function bound with (click) event as long as the condition for [disabled] attribute is true.

**Comment by Cedricgoubil** [comment]
Hi, I updaded my app to Angular 16 / PrimeNg 16, now all my button are <p-button> instead of <button> I also updated as a (onClick) method. The problem I am now facing is when I have a  <p-button> with a [routerLink] which need to be disabled it does work. Anyone knows how to fix this?
