### ISSUE TITLE
About Table(new)'s output event ---onRowClick and onRowDblclick

### ISSUE THREAD

**Issue by wangraoji** [primefaces/primeng#5456]
At datatable, it has onRowClick and onRowDblclick. But at the  table(new) ,it hasn't. I think, the two events is very important.

**Comment by wang-cola** [comment]
Yes, I have the same problem.It feels good to be able to return the rowdata when you click and double click.

**Comment by TishchenkoAlex** [comment]
@wangraoji @wang-cola 
```
<ng-template pTemplate="body" let-rowData>
        <tr [pSelectableRow]="rowData" (dblclick)=".....">
```

**Comment by bwilfong3** [comment]
@wangraoji @wang-cola I'd like to just add in here that if you are migrating from the old DataTable to the TurboTable, you may want to enable metaKeySelection , as it is now off by default. Double-clicking without metaKeySelection will select and deselect the row, which may not be your desired behavior. metaKeySelection will force the user to ctrl+click to deselect a row. Just food for thought.

**Comment by wangraoji** [comment]
@TishchenkoAlex thank you

**Comment by wangraoji** [comment]
@bwilfong3 thanks! I refer to TishchenkoAlex's suggestions

**Comment by wangraoji** [comment]
@bwilfong3 thanks ！ I used TishchenkoAlex suggestions。
