### ISSUE TITLE
p-table "first" input property not working

### ISSUE THREAD

**Issue by kwakiutlCS** [primefaces/primeng#5457]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/w2sYjEGr7q60Kvbix58H?p=preview

**Current behavior**
In a TurboTable with pagination, the "first" property doesn't seem to work.

**Expected behavior**
Changing the "first" property should change the first row displayed.

**Minimal reproduction of the problem with instructions**
Change the value of "first" property in app-component.ts file.

**What is the motivation / use case for changing the behavior?**
Use the table with OnPush change detection strategy

**Comment by kwakiutlCS** [comment]
please ignore
it works with 5.2.4, I had 5.2.3

**Comment by DropkickSteve** [comment]
I have updated to version 5.2.6 but [first] property still does not work
