### ISSUE TITLE
How can i change the background color for p-calendar icon on primefaceng ? I have been struggling for days on this issue. 

### ISSUE THREAD

**Issue by sree332** [primefaces/primeng#5459]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/qtZi5lB3DjkNt7Kdivg9?p=preview

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.X

* **PrimeNG version:** 5.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by diegosilva13** [comment]
Hello @sree332, you can  to redefine a new style for `.ui-button` class.
See this [example](http://plnkr.co/edit/NRl2XGkLmVhxadhF2FC4?p=preview).

**Comment by sree332** [comment]
Thank you for the response I figured it out by looking at some of the docs
but now I am hit with a different issue, I am using Omega theme and I am
having hard time fixing the radio button the inner icon would not center or
in each browser it appears little different and doesnt look good visually
any thoughts ?

Thanks
Sree

**Comment by JacobSiegle** [comment]
Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35.

If the button doesn't align it most likely is some of your other styles breaking it.

**Comment by sree332** [comment]
Thank you for the response, I just wrote custom component for the radio
button and this works for me.

Thanks again
Sree

**Comment by cagataycivici** [comment]
Please use forum for support requests.
