### ISSUE TITLE
primeng does not delivery a javascript object with all prototype methods reserved

### ISSUE THREAD

**Issue by bruceauyeung** [primefaces/primeng#546]
in my view:

```
<p-column styleClass="col-button" header="Operation">
        <template let-user="rowData">
            <button type="button" pButton (click)="onSelect(user);showDialog(true)" label="Edit" icon="fa-refresh"></button>
             <button type="button" pButton (click)="delete(user,$event)" label="Delete" icon="fa-trash"></button>
        </template>
    </p-column>
```

in my component:

```
onSelect(user: User) {
    this.selectedUser = user;
    this.selectedUser.clone(); // for illustration only
  }
```

and my User class:

```
export class Account {
  id: number;
  constructor(public name: string, public type: string, public password: string) { }

  clone() {
    // simple object clone
    return JSON.parse(JSON.stringify( this ));
  }
}
```

i expect an User object(an instance of typescript  User Class) to be transmitted into `onSelect` method when edit button is clicked, and then i can call `clone` method on this object directly. but this does not work because it says 

> this.selectedUser.clone is not a function

it seems the object transmitted into `onSelect` method by primeng is just a pure json object with only data fields.

angular2 version: 2.0.0-rc.4
primeng version: beta.9

**Comment by redhatlinux10** [comment]
is this a behavior by design?

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
