### ISSUE TITLE
Rxjs 6 support

### ISSUE THREAD

**Issue by markgoho-EDT** [primefaces/primeng#5462]
Support Rxjs 6

**Comment by cagataycivici** [comment]
What is the problem with 6 and PrimeNG?

**Comment by markgoho-EDT** [comment]
Imports are handled differently in 6. I'm getting linting errors from the way primeng is bringing in operators and things like Observable and Subject.

**Comment by gasparbarancelli** [comment]
Angular 6 now uses the new version of Rxjs, so PrimeNG does not work with the new version of Angular, there is an error in imports.

**Comment by markgoho-EDT** [comment]
@cagataycivici some library developers are choosing to release an rxjs/angular 6 compatible version of their pacakges so people who want to upgrade can, and those who don't can stay with ng5/rxjs5

Is that something you'd be willing to entertain?

**Comment by cagataycivici** [comment]
I think Angular 6 uses RxJS 6, so PrimeNG 6 will use RxJS6 and PrimeNG 5 on RX5.

**Comment by markgoho-EDT** [comment]
Fantastic idea!

**Comment by gasparbarancelli** [comment]
Many thanks, looking forward to testing the new version of the Angular and PrimeNG

**Comment by markgoho-EDT** [comment]
@cagataycivici I'd like to help with updating Rxjs -- how can I submit a PR for this? I saw you made a 6.0.0 snapshot 25 days ago, but I'm not sure how to access that branch. Did you see Ben Lesh's talk at ngConf? They've got a nice package to help upgrade the project:

Here's the relevant part of the talk: https://youtu.be/JCXZhe6KsxQ?t=20m22s

Here's the repo: https://github.com/ReactiveX/rxjs-tslint

For others looking to use Rxjs/Angular 6 with PrimeNg 5, make sure you've got the `rxjs-compat` package installed alongside and you'll be fine.

**Comment by gasparbarancelli** [comment]
Here is an official note of the angle that is on your blog https://blog.angular.io/version-6-of-angular-now-available-cc56b0efa7a4.

"For example, the command ng update @angular/core will update all of the Angular framework packages as well as RxJS and TypeScript, and will run any schematics available in these packages to keep you up to date. **we'll automatically install rxjs-compat in your application to make the adoption of RxJS v6 smoother**. "

So the version 5 of primeng would work perfectly with the Angular 6, I am already using in production without any problem.

**Comment by markgoho-EDT** [comment]
@gasparbarancelli the rxjs-compat package is meant as a temporary patch to cover any libraries that haven't updated to rxjs 6, so yes, it "works" -- but this shouldn't be seen as a solution.

NB: This issue is not to to make PrimeNG work with Angular 6, the goal here is to make it support Rxjs 6.

**Comment by rafa-as** [comment]
@markgoho-EDT totally agree.

**Comment by rafa-as** [comment]
You can check the migration steps here -> https://update.angular.io/

![screen shot 2018-05-04 at 16 09 13](https://user-images.githubusercontent.com/594574/39632576-c197f170-4fb5-11e8-9258-254dc57f0fb1.png)

**Comment by citizentim** [comment]
@gasparbarancelli as a long-term solution, it's bad as it needlessly inflates the output bundle size.  It really would be best to eliminate the dependency.

**Comment by Matmo10** [comment]
Looking forward to v6 - this is the last lib I use that depends on rxjs-compat :)

**Comment by unaor** [comment]
waiting as well

**Comment by hetal1110** [comment]
we are waiting as well.

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/issues/5758
