### ISSUE TITLE
The Showcase's free themes menu links are dead

### ISSUE THREAD

**Issue by MSeneadza** [primefaces/primeng#5463]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Go to the Showcase site and try to view one of the free themes via the menu.  When you click on a theme nothing happens.  All of their URLs point to `https://www.primefaces.org/primeng/#`

**Expected behavior**
The selected theme should load.

* **Browser:** I tried it in both desktop Chrome a Firefox

**Comment by JacobSiegle** [comment]
Works for me. When you click a free theme it changes the style in the docs, they don't have dedicated example pages like the others.

**Comment by MunazzahNawaz** [comment]
I am also facing the same issue tried chrome, IE, Firefox

**Comment by cagataycivici** [comment]
They just change the theme at showcase, make sure you have a component on page.
