### ISSUE TITLE
Undefined variable "child" in the template breaks the Megamenu 

### ISSUE THREAD

**Issue by h-arora** [primefaces/primeng#5466]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
The megamenu breaks if the model contains a value for **routerLink** at the top level menu item.
This happens because the ***ngIf="category.routerLink"** condition evaluates to true and the template which contains an undefined variable (child) is rendered.

**Expected behavior**
The megamenu should not break when this condition evaluates to true.

**Minimal reproduction of the problem with instructions**
Pass the following model to the megamenu to see this issue:

```
this.items = [
            {
                label: 'TV', 
                icon: 'fa-check',
                routerLink: ["/home"]
             }
    ]
```

**Comment by GuiF007** [comment]
[INFO] ERROR in node_modules\primeng\components\megamenu\megamenu.d.ts.MegaMenu.html(18,178): : Property 'child' does not exist on type 'MegaMenu'.
[INFO] node_modules\primeng\components\megamenu\megamenu.d.ts.MegaMenu.html(18,67): : Property 'child' does not exist on type 'MegaMenu'.
[INFO] node_modules\primeng\components\megamenu\megamenu.d.ts.MegaMenu.html(18,154): : Property 'child' does not exist on type 'MegaMenu'.
[INFO] node_modules\primeng\components\tabview\tabview.d.ts.TabPanel.html(6,31): : Property 'columns' does not exist on type 'TabPanel'.

**Comment by cagataycivici** [comment]
Fixed at

This is fixed already at; 5169
