### ISSUE TITLE
[Feature request] toogle button without text

### ISSUE THREAD

**Issue by spali** [primefaces/primeng#547]
using toggle button without text does end in strange formatting. (height of the element is wrong, because font-size does not apply without text). And also the width is to big (probably because of the padding).

I tried also to use the button as toggle, but there is a problem with the initial state of the button when used with [class.ui-state-active]="mystate" (did some css overrides for ui-state-active and ui-state-default to display my images). But indeed the button is not designed to be a togglebutton :)

So currently it does not seem to be possible with either button or togglebutton to get a image only toggle button.

Would be nice to have icon only support on the toggle button.

**Comment by sudheerj** [comment]
The width issue will be fixed with this PR https://github.com/primefaces/primeng/issues/1980 . The height issue need to be resolved.

**Comment by cagataycivici** [comment]
Yes, fixed via PR above.
