### ISSUE TITLE
PanelMenu Style Issue

### ISSUE THREAD

**Issue by itsmeks** [primefaces/primeng#5471]
Hi,
I have included PanelMenu and trying to bind it with its default example but issue is with its style. the child items are overlapping with parents. Please see attached file for understanding.

![panelmanu](https://user-images.githubusercontent.com/3659406/38227263-d9f761e0-3716-11e8-9d94-fe16bf9348a3.PNG)

**Comment by cagataycivici** [comment]
This is not a valid issue ticket as a stackblitz template is missing to demonstrate the issue which is vital for us to provide assistance to your case.

Please follow the issue guideline before creating new issues. If the issue still persists with the new version please create a new issue with our stackblitz template.
