### ISSUE TITLE
Autofill is breaking floating-label positioning

### ISSUE THREAD

**Issue by zhongdeliu** [primefaces/primeng#5472]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When (chrome) autofill happens, the label is not floating above the input field, unless any interaction on the page has taken place.
![screen shot 2018-04-03 at 08 12 11](https://user-images.githubusercontent.com/1384870/38232325-d7ae21da-3716-11e8-9c7d-3bbe02b61253.png)

**Expected behavior**
Label should be immediately above the input field after page load.

**Minimal reproduction of the problem with instructions**
- Take any form input field with a floating label styles as proposed in [https://www.primefaces.org/primeng/#/inputtext](https://www.primefaces.org/primeng/#/inputtext)
- Have autofill data in your browser
- Load the page

**What is the motivation / use case for changing the behavior?**
It a styling bug, when a page loads.

**Please tell us about your environment:**
macOS HighSierra, Chrome Browser 65, 

* **Angular version:** 5.2.4

* **PrimeNG version:** 5.2.3

* **Browser:** Chrome Browser (Autofill) XX
 
* **Language:** [all]

**Comment by REACT-DEVELOPER-IBROKHIM** [comment]
`input:-webkit-autofill + label`

**This solves the problem**
