### ISSUE TITLE
p-chart responsive attribute default value is misaligned between code and documentation

### ISSUE THREAD

**Issue by AndreaBarbasso** [primefaces/primeng#5475]
In code, it's `true`:  
https://github.com/primefaces/primeng/blob/f8a3c0d6e9bb4432c4772a36df4af66334d1f108/src/app/components/chart/chart.ts#L24
In docs, it's `false`:  
https://www.primefaces.org/primeng/#/chart

**Comment by cagataycivici** [comment]
Seems to be corrected already.
