### ISSUE TITLE
p-calendar doesn't show year in popup if it's outside of yearRange

### ISSUE THREAD

**Issue by ghost** [primefaces/primeng#5476]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/5R9OdTxgeG1tlJIoZz8y?p=preview

**Current behavior**
We would like to let the user select a month or a year. The only option is via the month or year dropdown in the calendar popup.
We need to specify a yearRange in order to let the user change the year.
If the user manually enters a date via the input field and he uses a year outside of the specified range, the model is set correctly but the year is set to the min year of the specified range.

**Expected behavior**
The user should be able to select whatever year he wants, by entering or selecting via the popup.
IMHO the best solution is to not enforce a yearRange to select a year via the popup because this restricts the input. Eg. show 5y in the past and 5y in the future in the year dropdown (and make this overridable via yearRange) + if the user selects the min year, add the 5y before to the dropdown + same for future years (+ make this '5' overridable as well)

**Minimal reproduction of the problem with instructions**
Enter a date via the input with a year before 2010 or after 2020. It will be set but you won't see the year selected in the year dropdown of the calendar poup.

**What is the motivation / use case for changing the behavior?**
YearRange is the only way to allow a user to select a year via the popup. But this restricts the years he can choose from AND the years he can manually enter, which is not the desired functionality.

**Please tell us about your environment:**
Windows 10 x64, Webstorm

* **Angular version:** 5.X
5.2.6

* **PrimeNG version:** 5.X
5.2.4

* **Browser:** [all]

 
* **Language:** [TypeScript 2.6.2]

* **Node (for AoT issues):** `node --version` =   v8.9.4

**Comment by yigitfindikli** [comment]
Unable to replicate with latest PrimeNG, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Comment by yogendermanral** [comment]
Hi,

I am using p-calendar version 7

<p-calendar  showButtonBar="true" [monthNavigator]="true" [yearNavigator]="true"
                yearRange="2000:2030" class="timeSheetCalendar" 
                dateFormat="dd.mm.yy" >
              </p-calendar>
Month and Year dropdown not coming in calendar
