### ISSUE TITLE
TurboTable - Varying row heights miscalculation of page offset for lazy scrolling

### ISSUE THREAD

**Issue by NordRagnarok** [primefaces/primeng#5478]
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Currently when a table has a non consistent row height (some rows are "taller" than others), TurboTable handle paging incorrectly - leading to double page offset size when scrolling.

[http://plnkr.co/hkfAZzgN8VYvIkm7FokA](http://plnkr.co/hkfAZzgN8VYvIkm7FokA)
Scrolling past VIN 39 - will continue in VIN larger then 40

**Expected behavior**
Correct page offset size on varying row heights
Or force strict row height across all rows

**Minimal reproduction of the problem with instructions**
Use TurboTable with lazy loading and virtual scrolling, with data that has different row heights.

**What is the motivation / use case for changing the behavior?**
Virtual scrolling in lazy loaded data is very useful.

**Please tell us about your environment:**
Windows 7, npm

* **Angular version:** 5.2.8

* **PrimeNG version:** 5.2.4

* **Browser:** [all]
 
* **Language:** [TypeScript 2.6.2 | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   6.10.3

**Comment by cagataycivici** [comment]
Plunkr does not work.

Please follow the issue guideline before creating new issues. If the issue still persists with the new version please create a new issue with our stackblitz template.
