### ISSUE TITLE
Modal dialog not compatible with Material2 sidenav

### ISSUE THREAD

**Issue by actimeo** [primefaces/primeng#548]
When a PrimeNG modal dialog is placed inside a Material2 sidenav layout, the modal dialog is covered with the rest of the page when opened.

A live demo is available at: http://ng2-material2-primeng-modal-debug.surge.sh/

Sources at: https://github.com/actimeo/ng2-material2-primeng-modal-debug

**Comment by cagataycivici** [comment]
If the overlay mask div is moved into md-content from body, problem is resolved. Looks like this;

<img width="579" alt="screen shot 2016-07-21 at 01 13 16" src="https://cloud.githubusercontent.com/assets/686247/17004969/5617e50e-4ee0-11e6-9150-aa0b25b27ab8.png">

Does that solve your issue, if so we need to provide an option to make the element to attach the overlay mask customizable. Right now it is always body.

**Comment by feloy** [comment]
Yes, that seems to resolve the issue. Thanks.

**Comment by actimeo** [comment]
Yes, that seems to resolve the issue. Thanks.

**Comment by chpasha** [comment]
there is no md-content element anymore in the sidenav. what should we do now?

**Comment by agusdutra** [comment]
Same issue here, couldn't get it working with primeng 2.0.3 and angular material 2.0.0. 
How should appendTo be used?

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
