### ISSUE TITLE
p-table emits lazy load event twice when initializing and multiSortMeta is provided

### ISSUE THREAD

**Issue by ctrl-brk** [primefaces/primeng#5480]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**Current behavior**
When multiSortMeta property is set for a lazy p-table the table will emit onLazyLoad event 2 times during initialization. Once from `ngOnInit` method here https://github.com/primefaces/primeng/blob/2838bcc4e50fd581457c7fbee9edc6ed6219ec8d/src/app/components/table/table.ts#L330
and another one when assigning `multiSortMeta` here https://github.com/primefaces/primeng/blob/2838bcc4e50fd581457c7fbee9edc6ed6219ec8d/src/app/components/table/table.ts#L464 by calling `sortMultiple` without checking `this.initialized` like it does for single sort here https://github.com/primefaces/primeng/blob/2838bcc4e50fd581457c7fbee9edc6ed6219ec8d/src/app/components/table/table.ts#L439

**Expected behavior**
onLazyLoad should be emitted only once during initialization

**Comment by bossqone** [comment]
`onLazyLoad` is also triggered multiple times when `sortField` and `sortMode` are specified.
For example, I parse state of application from URL query parameters to variable `state` in component, because router is my single source of truth.

Component's template looks like this:
```html
<p-table [value]="items"
         [rows]="state.pageSize"
         [first]="state.pageOffset"
         [sortMode]="'single'"
         [sortField]="state.sortField"
         [sortOrder]="state.sortOrder"
         [rowsPerPageOptions]="[10, 20, 50]"
         [paginator]="true"
         [lazy]="true"
         [totalRecords]="totalCount"
         [responsive]="true"
         (onLazyLoad)="onLazyLoad($event)"
         class="break-word table-columns-auto-width"
         [rowHover]="true">
.
.
.
</p-table>
```
Table has multiple sortable columns (e.g createdAt, updatedAt...).

On first load, `state.sortField` and `state.sortOrder` are `null`.
Then user clicks on column header to sort results by this column.
Click triggers `sort()` which triggers `sortSingle()` and therefore `onLazyLoad`.
What we do in `onLazyLoad` is simple redirect to same page, with updated query parameters.
New values from query parameters are set to `state` variable and this causes change of `sortField` and `sortOrder` inputs on TurboTable. These inputs are implemented as setters. Each of setters calls `sortSingle()` which triggers `onLazyLoad`.

So, sort triggered by user (click) results in 3 `onLazyLoad` events.

**Comment by bossqone** [comment]
@cagataycivici what do you think?

**Comment by filip12345678910** [comment]
maybe it would be nice if it was repaired

**Comment by cagataycivici** [comment]
With 6.1.1, you can do [lazyLoadOnInit]="false" which will prevent the load at ngOnInit.

**Comment by ManihtraA** [comment]
Any way to trigger lazy load event before last row reached on scroll?

**Comment by exitlol** [comment]
Upon sorting a lazy loaded p-table it still emitts the event more than once. At least for me. But I am not using mutiSort

**Comment by asheikh-alivia** [comment]
[lazyLoadOnInit]="false" doesn't work. I am using version 6.1.6.

**Comment by Maheshkale447** [comment]
> [lazyLoadOnInit]="false" doesn't work. I am using version 6.1.6.

its there in v9.1.0

**Comment by mfish0005** [comment]
@cagataycivici  Is the `[lazyLoadOnInit]` property possible with the virtual scroller component?  Because I'm having the same problem and it doesn't seem to be a known property of the virtual scroller

**Comment by chriswilley** [comment]
This issue was a real problem for me because the multiple lazy loading events meant multiple calls to the back end API. My workaround was to create a component property called `lastEvent` then in the onLazyLoad event handler:
```
onLazyLoad(event: LazyLoadEvent) {
    if (JSON.stringify(this.lastEvent) === JSON.stringify(event)) {
        return false;
    }
    this.lastEvent = event;
}
```
This prevents the `onLazyLoad` handler from running multiple times.

**Comment by cLandin** [comment]
> `onLazyLoad` is also triggered multiple times when `sortField` and `sortMode` are specified.
> For example, I parse state of application from URL query parameters to variable `state` in component, because router is my single source of truth.
> 
> Component's template looks like this:
> 
> ```
> <p-table [value]="items"
>          [rows]="state.pageSize"
>          [first]="state.pageOffset"
>          [sortMode]="'single'"
>          [sortField]="state.sortField"
>          [sortOrder]="state.sortOrder"
>          [rowsPerPageOptions]="[10, 20, 50]"
>          [paginator]="true"
>          [lazy]="true"
>          [totalRecords]="totalCount"
>          [responsive]="true"
>          (onLazyLoad)="onLazyLoad($event)"
>          class="break-word table-columns-auto-width"
>          [rowHover]="true">
> .
> .
> .
> </p-table>
> ```
> 
> Table has multiple sortable columns (e.g createdAt, updatedAt...).
> 
> On first load, `state.sortField` and `state.sortOrder` are `null`.
> Then user clicks on column header to sort results by this column.
> Click triggers `sort()` which triggers `sortSingle()` and therefore `onLazyLoad`.
> What we do in `onLazyLoad` is simple redirect to same page, with updated query parameters.
> New values from query parameters are set to `state` variable and this causes change of `sortField` and `sortOrder` inputs on TurboTable. These inputs are implemented as setters. Each of setters calls `sortSingle()` which triggers `onLazyLoad`.
> 
> So, sort triggered by user (click) results in 3 `onLazyLoad` events.
> From my point of view, setters should call `sortSingle()` only if new value differs from internal sort field/order.. **or even better, it shouldn't trigger events at all (for all inputs) in lazy mode.**
> 
> I would say, that our usecase is typical for other developers which use redux/ngrx architecture as well.

Was this bug addressed on the same PR? I think this is also reproducible using `customSort`

**Comment by sheikhajaz** [comment]
You can use the property as  [lazyLoadOnInit]="false"

**Comment by YogeshFullStack** [comment]
In my case on scroll call more than one time one's i reached last row it will be calling 0 to last row index api call

**Comment by petrkasnal** [comment]
Hello, is there any solution? I have same issue. I tried use  [lazyLoadOnInit]="false" and it still don't work. OnLazyLoad is still call twice on init

**Comment by buchatsky** [comment]
OnLazyLoad is called twice with both .first and .rows equal to zero. The first call allows to fetch totalCount from server and initialize virtualItems array, but the second is redundant.
