### ISSUE TITLE
Lazy p-table:  add option for disabling initial data load and allowing to force load event manually

### ISSUE THREAD

**Issue by ctrl-brk** [primefaces/primeng#5481]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```

**Current behavior**
p-table in lazy load mode always emits onLazyLoad event during initialization. But there are situations when the data might not be ready yet at this time.

**Expected behavior**
Provide an option for suppressing initial load and add a method to force it manually.

**Comment by bossqone** [comment]
This is critical for us, because we load initial data in route guard and we cannot use non-lazy mode due to server-side pagination/sorting.

**Comment by cagataycivici** [comment]
Added lazyLoadOnInit
