### ISSUE TITLE
P-Chart Not Responsive and Enlarged

### ISSUE THREAD

**Issue by jabaia** [primefaces/primeng#5483]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**

http://plnkr.co/edit/46mC0IopYLOhYUHWpAv6?p=preview

Created a plnkr but the chart wouldn't even init...

**Current behavior**
https://imgur.com/62aq7Zi

Chart is zoomed in at start and as screen is SHRUNK, the text becomes MORE legible. 

**Expected behavior**
The chart should be responsive and get set to a reasonable and legible size.

**Minimal reproduction of the problem with instructions**
Chart is in template like:
```
<div class="chart-container">
<p-chart type="bar" [data]="data"
                 [options]="options"
                 [responsive]="true"></p-chart></div>
```

With data being:
```
const data = {
      labels: labels,
       datasets: [{
               backgroundColor: colors,
               borderColor: colors,
               data: datas,
               barThickness: 48.3
      }]
   };
```

The options being: 
```
const options = {
      legend: {
          display: false
      },
      scales: {
        xAxes: [{
         display: false,
         categoryPercentage: 0.95,
         barPercentage: 0.99
        }],
       yAxes: [{
         ticks: {
           max: 100,
           min: 0,
           stepSize: 50
         }
       }]
      }
    };
```

And CSS that's being applied:
```
.chart-container{
      margin-bottom: 5px;
      canvas{
        height: 140px !important;
        width: 1024px !important;
      }
}
```

* **Angular version:** 5.8.0

* **PrimeNG version:** 5.8.0

**Comment by cagataycivici** [comment]
Try with the latest version please.
