### ISSUE TITLE
Custom Theme(scss) is not generating Turbo Table css properties

### ISSUE THREAD

**Issue by iArnoldo** [primefaces/primeng#5484]
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
Lets say i create a custom Theme with the following 

```
$primaryColor: #YOURCOLOR;
$primaryDarkColor: #YOURCOLOR;
$primaryLightColor: #YOURCOLOR;
$accentColor: #YOURCOLOR;
$accentDarkColor: #YOURCOLOR;
$accentLightColor: #YOURCOLOR;
$accentTextColor: #YOURCOLOR;

@import '../sass/theme/_theme';
```

Then i compile it with:

node-sass src/assets/theme/theme-myown.scss --output src/assets/theme/

It generates the css file --> theme-myown.css

Unfortunatly they css styles for the Turbo Table are not generated and therefor are not in the 
theme-myown.css file.

**Expected behavior**
The generated css File from the scss should contain css styles for the Turbo Table

**Minimal reproduction of the problem with instructions**
Create new scss file inside assets/theme folder.
Fill it with test Colors e.g:

```
$primaryColor: #YOURCOLOR;
$primaryDarkColor: #YOURCOLOR;
$primaryLightColor: #YOURCOLOR;
$accentColor: #YOURCOLOR;
$accentDarkColor: #YOURCOLOR;
$accentLightColor: #YOURCOLOR;
$accentTextColor: #YOURCOLOR;

@import '../sass/theme/_theme';
```
Compile it with node-sass [https://github.com/sass/node-sass](https://github.com/sass/node-sass
)
node-sass src/assets/theme/theme-myown.scss --output src/assets/theme/

Insert it into your Page

Open a Page which contains a Turbo Table module.

Primeng Documentation on how to create a custom theme can be found here.

[https://www.primefaces.org/ultima-ng/#/documentation](https://www.primefaces.org/ultima-ng/#/documentation)

* **Angular version:**
 5.2.6

* **PrimeNG version:** 
5.2.3

**Comment by cagataycivici** [comment]
An update to your theme should fix this already.
