### ISSUE TITLE
Frozen columns issue with when scrollable columns present

### ISSUE THREAD

**Issue by sky007** [primefaces/primeng#5485]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report 
[ ] feature request
[ ] support request 
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/turbotable

**Current behavior**
When you have an vertical scroll, the bottom of the frozen table doesn't display as much as the unfrozen table.

![image](https://user-images.githubusercontent.com/1032882/38296495-c71bf2bc-37f1-11e8-95a4-d5a543e3d2a0.png)

**Expected behavior**
frozen table displays the same amount of the rows as the unfrozen table

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/turbotable

**What is the motivation / use case for changing the behavior?**
Displaying the last row of the table more visible.

Please tell us about your environment:
- Angular version: 5.X
- PrimeNG version: 5.2.4
- Browser: All

**Comment by adama357** [comment]
Also, as pointed out in #5578, this issue can be seen[ in the PrimeNG documentation](https://www.primefaces.org/primeng/#/table/scroll):

![frozen_demo](https://user-images.githubusercontent.com/20462430/39143050-3d7612bc-46f2-11e8-99c3-00f02a509111.png)

**Comment by JacobSiegle** [comment]
Might see if I can PR it. Comment bookmark.

**Comment by simdevmon** [comment]
The problem still persists on PrimeNG 6.0.1

**Comment by cagataycivici** [comment]
Can't replicate this one, the one with groups have an error though so reopened #5578

**Comment by pierfreeman** [comment]
The bug still persists for 6.1.4. Open issue here -> https://github.com/primefaces/primeng/issues/6560
