### ISSUE TITLE
About paginator at Table-lazy（关于table-lazy中的分页问题）

### ISSUE THREAD

**Issue by wang-cola** [primefaces/primeng#5486]
懒加载分页，假设我现在在第二页，不刷新页面，只刷新数据，这时候数据回到了第一页，但是分页还处在第二页，并且我勾选的数据还在勾选中
Lazy loading paging, assuming I am in the second page, do not refresh the page, just refresh the data, this time the data returned to the first page, but the paging is still on the second page, and the data I checked is still checked

**Comment by wangraoji** [comment]
i think so

**Comment by GnefAm** [comment]
Me too.

**Comment by cagataycivici** [comment]
Should be fixed already. Also try [resetPageOnSort]="false" if you have sorting.
