### ISSUE TITLE
DataTable emptymessage template does not work

### ISSUE THREAD

**Issue by alpernakin** [primefaces/primeng#5487]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/C7BVkQZnJz4fzMnM1YpI?p=preview

**Current behavior**
Empty message template does not show anything

**Expected behavior**
Empty message shows the content

**Minimal reproduction of the problem with instructions**
Please see plnkr

* **Angular version:** 5.2.9

* **PrimeNG version:** 5.2.4

**Comment by Mysame** [comment]
I van vaguely recall having the same issue. However, you won't get a response because you're still using p-dataTable. Best choice is switching over to p-Table.

**Comment by alpernakin** [comment]
@Mysame Yeah you are right, it is what I have done at the end.
