### ISSUE TITLE
tri-state checkbox for tree

### ISSUE THREAD

**Issue by mahdiprog** [primefaces/primeng#5492]
Hi
I want to have tri-state checkbox for tree but not like current behavior of it. I expect it to checking parent node not change check state of child nodes and they act independently. like what implemented in [jqxTree](https://www.jqwidgets.com/angular/angular-tree/angular-tree-checkboxes.htm) when "Three Check States" is unchecked.

**Comment by cagataycivici** [comment]
Will reopen if more users demand it.
