### ISSUE TITLE
Datatable column name with dot

### ISSUE THREAD

**Issue by Hesesses** [primefaces/primeng#5495]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/YXI34crdqiR4hzXAmKaH?p=preview

**Current behavior**
Column name with dot is not showing data

**Expected behavior**
data would show

**Comment by noamichael** [comment]
The `p-dataTable` isn't supported anymore, but I don't think this will be supported even in the new turbo table.

The dot is a standard separator for both tables -[ it actually uses it to split the string](https://github.com/primefaces/primeng/blob/master/src/app/components/utils/objectutils.ts#L65). Unless some kind of escape character was added, the field name just has to be normalized, or you have to render the data manually:

    <p-column header="Question 1">
        <ng-template let-data="rowData" pTemplate="body">
            {{data['1. question']}
        </ng-template>
    </p-column>

**Comment by Hesesses** [comment]
Thank you for the reply!

Would it be possible to add a setting if you want to use the dot separator or not?

In our project all fields are dynamic, so currently only option seems to be to make a custom fork and override the `resolveFieldData`function?

**Comment by noamichael** [comment]
This can be done with the new `<p-table/>` if you don't mind switching to it. I modified the plunkr to show how it can be done:

http://plnkr.co/edit/WO4ICRHSIomIFKqwWoTy?p=preview

**Comment by Hesesses** [comment]
Awesome, thank you!

turbotable has the same features as datatable?

**Comment by noamichael** [comment]
No problem. Yes, turbo table has the same features as the datatable. If you need to do any sorting, because your column names have the dots, you'll have to use a custom sort function. [You can find out more in the docs](https://www.primefaces.org/primeng/#/table).

**Comment by Hesesses** [comment]
Ok, thank you very much! I hope we will see the excel export feature for the new turbo table soon :)

**Comment by Hesesses** [comment]
Hi, Updated to turbotable and wow, its so much easier to use than the old datatable, super good job!

I can now see the dot columns rendered on the table. Sorting is not working (as you said) and when exporting to csv the fields are not included... 

Just wondering would you consider to having a setting to turn off dot splitting the string?
