### ISSUE TITLE
Table - shiftKey multiple-selection when using checkbox

### ISSUE THREAD

**Issue by alecrt** [primefaces/primeng#5496]
shiftKey multiple-selection seems not to work as expected :

```
<p-table [columns]="cols" [value]="cars" [(selection)]="selectedCars" dataKey="vin">
    <ng-template pTemplate="header" let-columns>
        <tr>
            <th style="width: 2.25em">
                <p-tableHeaderCheckbox></p-tableHeaderCheckbox>
            </th>
            <th *ngFor="let col of columns">
                {{col.header}}
            </th>
        </tr>
    </ng-template>
    <ng-template pTemplate="body" let-rowData let-columns="columns" let-rowIndex="rowIndex">
        <tr [pSelectableRow]="rowData" [pSelectableRowIndex]="rowIndex">
            <td>
                <p-tableCheckbox [value]="rowData"></p-tableCheckbox>
            </td>
            <td *ngFor="let col of columns">
                {{rowData[col.field]}}
            </td>
        </tr>
    </ng-template>
</p-table>
```

**Comment by jaredmartinez** [comment]
I am looking for something similar to this. My users would like to be able to select multiple checkboxes with the shiftKey and everything between the indexes is automatically selected. Rows do not need to be selected with this.

This functionality is similar to how gmail works. Thanks!

**Comment by jaredmartinez** [comment]
@yigitfindikli any way we could prioritize this?

**Comment by OmarEnriqueCocaBuitrago** [comment]
@cagataycivici 

I solved it like this : 

do not forget to use the  "let-rowIndex="rowIndex"" and "[pSelectableRowIndex]="rowIndex""

```
<ng-template pTemplate="body" let-user let-columns="columns" let-rowIndex="rowIndex">
    <tr [pSelectableRow]="user" [pContextMenuRow]="user" (dblclick)="editUser()" [pSelectableRowIndex]="rowIndex">
        <td *ngIf="userMgmtService.multiMode" style="width: 3em">
            <p-tableCheckbox #checkboxTableP [value]="user" [index]="rowIndex" (click)="checkboxTable(checkboxTableP, $event)"></p-tableCheckbox>
        </td>
    </tr>
</ng-template>
```

and in the component :

````
checkboxTable(tableCheckBox: TableCheckbox, event: MouseEvent){
    if(event.button == 0 && event.shiftKey){
        this.mainTable.selectRange(event, tableCheckBox.index);
    }
}
````

**Comment by alinbujor** [comment]
Hi Omar,

It somehow works but for me it works only when you click on a row and not on the checkbox. Clicking on the checkbox doesn't do anything. Is it the same for you? Am I missing something?

Thanks,
Alin

**Comment by OmarEnriqueCocaBuitrago** [comment]
Hi @alinbujor , 

for me works in the checkbox, I have not implemented yet with the row. 
maybe you can post some of your code. 

did you use the function in the <p-tableCheckbox> tag ?

**Comment by jaredmartinez** [comment]
Could you post a atackblitz @OmarEnriqueCocaBuitrago ? I seem to have the same issue.

**Comment by OmarEnriqueCocaBuitrago** [comment]
hi @jaredmartinez 
In my comment above you find all the code. 

![](https://media.giphy.com/media/uKvS8PNqN5F6SjVEJd/giphy.gif)

**Comment by jaredmartinez** [comment]
@OmarEnriqueCocaBuitrago 

https://stackblitz.com/edit/primeng-tabledoc-demo-wmitv8

What is missing to make this work?

**Comment by OmarEnriqueCocaBuitrago** [comment]
you are missing the [selectionMode]="'multi'" in die `<p-table>`  so should be like this: 
`<p-table [selectionMode]="'multi'">`

**Comment by OmarEnriqueCocaBuitrago** [comment]
@lukasmatta great Job 

I did the same with my table but I did not post it because I am having the problem with the counter of the user selected after you unselect them. PrimeNG does not reconize that the list have less user selected but the table shows that you have successfully unselected users. 

![Alt Text](https://media.giphy.com/media/gMZc8V3eX6sm51z4YT/giphy.gif)

are you having the same  issue ?

**Comment by lukasmatta** [comment]
@OmarEnriqueCocaBuitrago I think that @jaredmartinez improved my solution and added logic for proper deselection. Have you tried the solution he posted above?

**Comment by mnhock** [comment]
There are any plans to support multiple selection with shiftkey in checkbox mode?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by Rhobal** [comment]
Behaviour is still the same on primeng 14.2.2 so issue is not closed

**Comment by vlad-iml** [comment]
I looked at the fix proposed by @OmarEnriqueCocaBuitrago, and for me the shift + click works by simply using ` [pSelectableRowIndex]="rowIndex"`, without having to add an additional method `checkboxTable` in the component. We're currently using PrimeNG v13.3. Hope this can help someone.
```ts
    <ng-template pTemplate="body" let-item let-rowIndex="rowIndex">
      <tr
        [pSelectableRow]="item"
        [pSelectableRowIndex]="rowIndex"
      >
```

**Comment by fttx** [comment]
But is this highlighting the whole row for you? I need it to work only by clicking the checkbox, like this:

![image](https://github.com/primefaces/primeng/assets/5663423/0e8f4a6f-c16f-4924-bfda-d3e0a69b7cfc)

**Comment by gianluca-moro** [comment]
Has this been feature been added to PrimeNG? I am currently trying to implement the same behaviour and it would be nice if it was already part of PrimeNG table.

**Comment by zachsteffens-wy** [comment]
I am also looking for a solution to this issue.
