### ISSUE TITLE
Table .reset() not resetting column sort style

### ISSUE THREAD

**Issue by tiagodws** [primefaces/primeng#5499]
**I'm submitting a ...** 
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/TkTjc5qjSEFDHj6K6cxt?p=preview

**Current behavior**
Sorted columns keep their sorting state after resetting the table.

**Expected behavior**
According to the docs, .reset should "Resets sort, filter and paginator state".

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/TkTjc5qjSEFDHj6K6cxt?p=preview

- Sort grid data by any column
- Call Table's .reset() function
- Observe that the sorted column still looks the same

**Please tell us about your environment:**

* **Angular version:** 5.2

* **PrimeNG version:** 5.2.3

**Comment by ericcastoldi** [comment]
:+1:

**Comment by ricardobfa** [comment]
+1

**Comment by sivnz** [comment]
+1

**Comment by sidneibiz** [comment]
+1

**Comment by dhuebes** [comment]
+1

**Comment by dhuebes** [comment]
+1

**Comment by felipexw** [comment]
+1

**Comment by rafaeldmpacheco** [comment]
+1

**Comment by knipers** [comment]
+1

**Comment by dudapraiagrande** [comment]
+1

**Comment by elSteenwijker** [comment]
+1

**Comment by M0Sharif** [comment]
+1

**Comment by harshdevj** [comment]
+1

**Comment by sanjoga** [comment]
+1

**Comment by carlosbridi** [comment]
+1

**Comment by TarikDaCosta** [comment]
+1

**Comment by VagnerFP** [comment]
+1

**Comment by knipers** [comment]
@cagataycivici Is it possible to prioritize this issue please?

**Comment by solael** [comment]
+1 Can't use turboTable in our application without it.

**Comment by cagataycivici** [comment]
Many comments, I'm in :)

**Comment by tiagodws** [comment]
@cagataycivici Thanks!

**Comment by knipers** [comment]
@cagataycivici tnks

**Comment by misan128** [comment]
+1

**Comment by shkarab** [comment]
+1

**Comment by admir86** [comment]
still not working in version 6.0.1 ?
header style is ok, but data is not resorted after reset

**Comment by Janatbek** [comment]
[I like this approach though](https://stackblitz.com/edit/github-vmghz6-bexlzn?file=src%2Fapp%2Fapp.component.html) all the work done in HTML

**Comment by MeMeMax** [comment]
I still have this problem. The header styles are resettet but the data is not resorted to the initial state. Anyone else has this issue?

**Comment by Prasham2407** [comment]
I still have this problem. Any workarounds?
