### ISSUE TITLE
Reset the fullCalendar (Schedule) in ngOnChanges

### ISSUE THREAD

**Issue by SteamWind** [primefaces/primeng#5502]
**I'm submitting a ...** 
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Some of the options can't be updated in ngOnChanges. (It's not implemented in fullCalendar for now)

> Dynamic setting of some options is simply not yet implemented:
> 
> - handleWindowResize
> - views

**Expected behavior**
A way to update the view of fullCalendar is, after changing options, **destroy and render** the view.
We could implement it in `ngOnChanges` or create a reset function.
A great way should be to add an input in `p-schedule` with something like `[resetOnChanges]="true"` and when true, reset on `ngOnChanges`. That way, somebody that don't want to overload his app make it false...

**Minimal reproduction of the problem with instructions**
Changing visibleRange of the view doesn't affect fullCalendar:
https://plnkr.co/edit/w9YDgjFMarUUteN4yVV8?p=preview

**What is the motivation / use case for changing the behavior?**
Provide a way to update the view after init. Useful if your view is dependent of an async service or a button in your interface.

* **PrimeNG version:** 5.2.3

Made this an issue as suggested here: https://github.com/primefaces/primeng/pull/5418

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/issues/6386
