### ISSUE TITLE
Color problem with south-street theme

### ISSUE THREAD

**Issue by bbuehrer** [primefaces/primeng#5504]
The selected page in paginator-control is not easy to read when I use the south-street theme. Can you change the background color or text color?

![unbenannt](https://user-images.githubusercontent.com/33655412/38408054-33eb88a4-397c-11e8-8360-b553204d9fbe.JPG)

I use the paginator-control in turbo-table with [paginator]="true"

**Comment by bbuehrer** [comment]
I use the paginator-control in turbo-table with  [paginator]="true"

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/pull/6033
