### ISSUE TITLE
Turbotable single column filter does not work if sorting is present on webkit based browser and Edge

### ISSUE THREAD

**Issue by MI53RE** [primefaces/primeng#5505]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/AIDY5eSkcdv9MoBxcT0V?p=preview

**Current behavior**

**NOTE: this is not the same as in #4910**

(In the exeption of Firefox which is having somewhat the expected behaviour)
In all browser I could have tested on (Chrome, Safari and Edge) if I'm setting both sorting and filtering on a column , if I am clicking the input to start filtering, I'm losing the focus immediately so I cannot enter the filter. On Chrome and Safari, it is somehow possible to enter the filter if I hold clicking the input. This 'hack' does not work on Edge.

Also if I manage to enter a filter, then the sorting is no longer working the filtering is set

**Expected behavior**

Like in Firefox, both sorting and filtering are working, I can enter filter in the input of the column.

**Minimal reproduction of the problem with instructions**

In the provided plunker above, just click on a Filter (is not workin) input in a column.
The cursor will disapear immediately and you are not able to enter any character.
On Chrome and Safari if you hold down the mouse left click after clicking on the input and start typing you will be able to use the filter, however all the sorting, for all column, will stop working .

As mentionned before this workarround is not working on Edge.

**What is the motivation / use case for changing the behavior?**

Multi-filtering while aving the capability to sort (exemple:  I want all black cars in the 20xx years and sor them DESC)

**Please tell us about your environment:**

Windows 10 pro x64
Mac OS

* **Angular version:** 5.X

Angular CLI: 1.7.3
Angular : 5.2.9

* **PrimeNG version:** 5.X

PrimeNG: 5.2.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Bug on
- Microsoft Edge 41.16299.15.0, Microsoft EdgeHTML 16.16299
- Chrome 65.0.3325.181 (64 bits)
- Safari

Work on
- Firefox: 59.0.2 (64 bits)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

* **Node (for AoT issues):** `node --version` =   
Node: 8.10.0

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
