### ISSUE TITLE
readonly support for MultiSelect

### ISSUE THREAD

**Issue by EleanorHughes** [primefaces/primeng#5506]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Plunkr shows p-dropdown read only functionality (working) and p-multiselect read only functionality (not working)
http://plnkr.co/edit/9XrAI2GCT6TTpbLlCfM0?p=preview

**Current behavior**
When readonly is set to true the p-multiselect is not read only.
Also the disabled property is not what I require.

**Expected behavior**
With readonly="true" set on the control it should be read only.

**Minimal reproduction of the problem with instructions**
 <p-multiSelect readonly="true" [options]="cars" optionLabel="label"></p-multiSelect>
as per plunkr

* **Angular version:** 5.2.3

* **PrimeNG version:** 5.2.2

* **Browser:** 
Chrome
 
* **Language:** 
Typescript 2.4.2

**Comment by Raviowitch** [comment]
Hello,

Like Eleanor, i need a readonly attribute.
Someone have a workaround ?

Thank you,

Mathieu
