### ISSUE TITLE
Vertical Tabs: Fixed height 300px;

### ISSUE THREAD

**Issue by MarcelCremer** [primefaces/primeng#551]
Hello,

if you're using the vertical tabs-element, the size is fixed to 300px which causes some ui problems when you've got more tabs.

As a workaround, I currently use

:host .ui-tabview-nav {
    height:initial !important;
}

Which makes it dependant on the amount of elements. Most likely, it should not be height:300px; in the CSS, but min-height:300px;

Regards
Marcel

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.

**Comment by emredenizozer** [comment]
I also faced this problem when I wanted to use left-oriented tabs with different-size components in them and I solved the issue by adding

body .ui-tabview.ui-tabview-left > .ui-tabview-nav {
  height: auto !important;
}

css code segment to all of my .css files (such as adding this code inside theme-blue.css) in Ultima 4.2.0.

Hope this helps!
