### ISSUE TITLE
Table is messing up array order with more than 10 items

### ISSUE THREAD

**Issue by zhongdeliu** [primefaces/primeng#5511]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/BQDWFVnhfgygflqyHvCf?p=preview

**Current behavior**
When putting an array with more than 10 items into a table, the (default) order is somehow messed up.

**Expected behavior**
When no sorting is enabled, the order of the array should be used

**Minimal reproduction of the problem with instructions**
Put an array with more than 10items into an table as data. See plunkr: 
http://plnkr.co/edit/BQDWFVnhfgygflqyHvCf?p=preview
First table has 10, second 11, third 12 items. See the listings...
<img width="625" alt="screen shot 2018-04-09 at 12 30 33" src="https://user-images.githubusercontent.com/1384870/38493269-e1f5abb0-3bf1-11e8-8de8-1d244365efa3.png">

**What is the motivation / use case for changing the behavior?**
Array order should be preserved, if no explicit sorting is defined...

**Please tell us about your environment:**
macOs High Sierra, 

* **Angular version:** 5.2.4

* **PrimeNG version:** 5.2.3

* **Browser:** Chrome 65,

**Comment by TMaster** [comment]
Happens to me as well very strange. I'm not sure but I think it always reorder the items in the same order (but sadly not the expected order).

**Comment by cnnicknick** [comment]
I met the same problem and hope to get help，thanks！

**Comment by cnnicknick** [comment]
In the file table.js @row 390: 'this.value.sort(...);' changed to 'if( _this.sortField ){this.value.sort(...);}' . because we do not want to sort if sortField is null or undefined.  Could you tell me that's right? @TMaster @zhongdeliu @ @TMaster @vincent

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
