### ISSUE TITLE
Remove the link displayed at bottom corner when hovering the accordion/tabview header

### ISSUE THREAD

**Issue by abidhmuhsin** [primefaces/primeng#5518]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting

```
**Current behavior**
Hovering on the accordion header displays the hyperlink on the page's left-bottom corner.
This is even visible in accordion the demo pages as the hypelink https://www.primefaces.org/primeng/#.

**Expected behavior**
Hovering on the accordion header should not display any hyperlink on the page's left-bottom corner.

**What is the motivation / use case for changing the behavior?**
Since accordion header content is wrapped in tag, hovering on the header displays the hyperlink on the page's left-bottom corner.
This looks weird in an angular app which itself doesnt have hyperlinks.
Also while trying to bind custom click events it triggered app reload due to href='#' (similar to angular/angular#7294)
Could disable this by styling 'pointer-events:none;', but that also disables any custom click events binding or anything on the header.

* **Browser:** [all ]

**Comment by abidhmuhsin** [comment]
I have submitted a pull request fixing the same [5517](https://github.com/primefaces/primeng/pull/5517)

**Comment by bbuehrer** [comment]
I have the same problem with the primeng "Slide-Menu".
I don't set "url" or "routerLink" in the meuItem. I use the "command", but an url is showing in the left bottom corner off my WebApp when o hover over the menuItems in the slidemenu.

**Comment by abidhmuhsin** [comment]
Just now found that similar issue is also present in <p-tabView>. It also has a href="#" included.
Slide menu has so many conditional implementation for href property. 
Ideally href attribute itself should be removed if href. url is blank.

**Comment by bbuehrer** [comment]
Yes, I agree too

**Comment by cagataycivici** [comment]
If we remove it, keyboard accessibility is gone, open to suggestions.

**Comment by bbuehrer** [comment]
I will use the slide-menu in a PWA.

For me it would be good if it were removed.

**Comment by cagataycivici** [comment]
Done!

**Comment by abidhmuhsin** [comment]
Thank you @cagataycivici .. 👍 Should be useful for further projects.. 
We ended up using a custom components for accordion and tabbed pane in our last project due to this issue..

**Comment by sebastiansinsin** [comment]
could you remove it from menuItem in datatable?

**Comment by sebastiansinsin** [comment]
@abidhmuhsin could you teach me how to make custom components? could you give me an example? how to custom this menuItem from primeng
