### ISSUE TITLE
Dropdown is unable to display current value as selected when using placeholder and arbitrary object

### ISSUE THREAD

**Issue by Neha-N** [primefaces/primeng#5519]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**

PROBLEM : Unable to show selected value in drop down when using arbitrary object. Instead of that it shows placeholder value. It is working fine if object is in { label: 'xyz', value: 1 } format. Also it started working fine if I remove placeholder.

**Expected behavior**
It should display current value of object as selected value, with the use of placeholder also.

**Minimal reproduction of the problem with instructions**
Code snippet:
<p-dropdown [options]="CompNameArray" [(ngModel)]="selectedCompObj" optionLabel="name" name="CompName" placeholder="Select company name" [showClear]="true"></p-dropdown>

Steps to reproduce:
1. Use p-dropdown with array of custom object (ex: CompNameArray) with the properties like : { name: 'abc', id: 1, compName:'xyz', desc: 'abcdef' }
2. Set the selected value (ex: selectedCompObj) in dropdown by binding it with ngModel. Set the placeholder value also.

**What is the motivation / use case for changing the behavior?**
This would allow the drop down to use with arbitrary object with placeholder property.

**Please tell us about your environment:**
OS : Windows

* **Angular version:** 5.X
5.2.9

* **PrimeNG version:** 5.X
5.2.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
