### ISSUE TITLE
TreeTable component ui-state-highlight class automatically added to rows 

### ISSUE THREAD

**Issue by bibidon** [primefaces/primeng#5522]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

**Current behavior**

TreeTable component.
When you add an additional row class via styleClass attribute to the existing (rendered) node ui-state-highlight class automatically added to this row. I think it looks like the same as  #3414.

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.2.9

* **PrimeNG version:** 5.2.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by code-junkie** [comment]
I am also seeing the same problem. I have noticed that it seems to only happen when I change the styleClass property on a TreeNode object the second time. The property starts out undefined, and when I change it to a string the first time it doesn't add the ui-state-highlight class. When I change it from one string to another string it adds the class. Even when I change the value to something like null or an empty string, it doesn't remove the class.

**Comment by cagataycivici** [comment]
Please try the new TreeTable of 6.0.0-alpha.2
