### ISSUE TITLE
Dialog Popup Causing Detached DOM Objects

### ISSUE THREAD

**Issue by nanoTitan** [primefaces/primeng#5524]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Creating a Dialog Popup nested inside a div with ngIf will leave detached DOM nodes when the ngIf evaluates to false. This issue is not resolved with the fix from #2976.

**Expected behavior**
The dialog popup should clean up after itself and not leave detached DOM nodes

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/sRslCo

To see this, please use chrome developer tools, and use a Memory heap snapshot. 
Garbage collect and take a snapshot before clicking the button. Then take one after closing the dialog and garbage collect again. View the comparison, and you will see detached DOM nodes that never get cleaned up

**What is the motivation / use case for changing the behavior?**
I don't want to crash my users or give them a bad experience because they ran out of memory

**Please tell us about your environment:**
Windows 7, Visual Studio Code, NPM, Chrome, using lite server with ng serve

* **Angular version:** 5.2.9
* **PrimeNG version:** 5.2.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome, IE
 
* **Language:** TypeScript 2.6.2, ES6

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.

**Comment by nanoTitan** [comment]
We're you able to produce it with the version I have laid out (5.2.4)? I submitted this bug almost 6 months ago, and it is kind of a big deal for us. Some of us haven't moved on to the "latest" version of PrimeNG.
