### ISSUE TITLE
Dynamic scrollHeight for turboTable

### ISSUE THREAD

**Issue by mseaman123** [primefaces/primeng#5528]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/qtZi5lB3DjkNt7Kdivg9?p=preview

**Current behavior**
If you change the scrollHeight dynamically in the turboTable which causes the scrollbar to show, it pushes the data to the left and then doesn't align with the header. This isn't the case on initiation or if it has a fixed scrollHeight.

**Expected behavior**
When the scrollHeight is dynamically changed, it should align the scrollbar. I was able to fix in the source code by adding this.alignScrollBar() as shown below:
`    Object.defineProperty(ScrollableView.prototype, "scrollHeight", {
        get: function () {
            return this._scrollHeight;
        },
        set: function (val) {
            this._scrollHeight = val;
            this.setScrollHeight();
            this.alignScrollBar();
        },
        enumerable: true,
        configurable: true
    });
`

**Minimal reproduction of the problem with instructions**
After initialization of a turbotable, change the scrollHeight.

**What is the motivation / use case for changing the behavior?**
Fix the mis-alignment of the scrollbar after changing scrollHeight

**Please tell us about your environment:**
Using VS with systemjs

* **Angular version:** 5.X
Angular 4.3.4

* **PrimeNG version:** 5.X
PrimeNG 5.2.4

* **Browser:** 
Chrome XX | IE XX 
 
* **Language:** 
Typescript 2.4.1.0

* **Node (for AoT issues):** `node --version` =   
Node 6.9.2

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
