### ISSUE TITLE
DataTable Column custom sorting by default

### ISSUE THREAD

**Issue by Coffee-Tea** [primefaces/primeng#553]
When I use default sorting my custom sorting function does not work.
On click it works perfect, but does not when table just loaded.

I thin that I should run .sort() function in dataTable after load table, but I don know how to do it?
Maybe I have to do something else?

Thank you!

**Comment by shahmirn** [comment]
I ran into the same issue, so I've created a pull request https://github.com/primefaces/primeng/pull/605 that should fix this

**Comment by ryanwawr** [comment]
Would be nice to see that fix pulled in sometime soon. I'm having the same issue with the initial custom sort not working. Worked around it for now by calling my custom sort function manually once the datatable is populated, but would prefer not to have to resort to such a messy solution.

**Comment by Samisama** [comment]
Hello, is there a way to fix that problem ? I'm also using sortable="custom" on one of my columns but the default sort on this column doesn't call my custom sort function.
Thank you

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with them and if issue persists drop a comment and we'll reopen.
