### ISSUE TITLE
Slider does not reflect initially bound value when OnPush strategy is used

### ISSUE THREAD

**Issue by shlangus** [primefaces/primeng#5530]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/pUnbPtz2cukMZEV8CtU7?p=preview

**Current behavior**
When a slider is used inside a component which uses `OnPush` change detection strategy it shows value 0 despite `ngModel` binding until first change detection

**Expected behavior**
Slider should show a value passed through `ngModel`

**Minimal reproduction of the problem with instructions**
Just put a slider into component that uses `OnPush`.

* **Angular version:** 5.2.0 
* **PrimeNG version:** 5.2.3 
* **Language:** TypeScript 2.5.3

**Comment by sgentile** [comment]
I'm having the same issue - it doesn't apply my ngModel until I click on the control
