### ISSUE TITLE
ScrollPanelDemo code incomplete

### ISSUE THREAD

**Issue by timmackey** [primefaces/primeng#5532]
**I'm submitting a [x] bug report.

It's pretty much impossible to replicate the online demo here....
[https://www.primefaces.org/primeng/#/scrollpanel](url)
... if you don't also post the code for styleClass="custombar1" and styleClass="custombar2" used here...
[https://github.com/primefaces/primeng/blob/master/src/app/showcase/components/scrollpanel/scrollpaneldemo.html](url)

**Comment by mertsincan** [comment]
Fixed now. Thanks a lot!
