### ISSUE TITLE
Add trackBy to PickList

### ISSUE THREAD

**Issue by queueseven** [primefaces/primeng#5536]
**I'm submitting a ...**  
```
[ ] bug report
[*] feature request
[ ] support request
```

**Current behavior**
The performance of the PickList component is bad when using a lot of items since it does not make use of Angular's ngForTrackBy (like e.g. the DataList component). You could also call it a bug.

**Expected behavior**
Use Angular's ngForTrackBy like in other components to improve the performace.

**What is the motivation / use case for changing the behavior?**
We make heavy use of the PickList component and it sucks when using a lot of items (like, 1000 or so).

**Comment by cagataycivici** [comment]
PR merged
