### ISSUE TITLE
Fileupload broken styleClass in basic mode

### ISSUE THREAD

**Issue by splincode** [primefaces/primeng#5539]
If you usage set [styleClass]="style", you usage only advanced mode

https://github.com/primefaces/primeng/blob/master/src/app/components/fileupload/fileupload.ts#L49

**Comment by egedarcin** [comment]
@splincode can you explain the problem in a detailed way? Can you show some bug examples?

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
