### ISSUE TITLE
p-calendar inside p-table filter z-index

### ISSUE THREAD

**Issue by sgentile** [primefaces/primeng#5542]
I believe this is a z-index issue : 

When using within a template

```
<p-calendar *ngSwitchCase="'termStartDate'" [showIcon]="true"></p-calendar>

```
When clicking on the calendar to open it - it is hidden under the table itself:
![image](https://user-images.githubusercontent.com/132404/38632930-286646a4-3d8c-11e8-94ae-d78dd550ab4b.png)

**Comment by sgentile** [comment]
Found a workaround here

https://github.com/primefaces/primeng/issues/3940

```
<p-calendar *ngSwitchCase="'termStartDate'" [style]="{'position': 'fixed', 'overflow': 'visible', 'z-index': '999'}" [showIcon]="true"></p-calendar>
```

**Comment by sgentile** [comment]
Actually that isn't a work around at all - it's a 'fixed' position so when you scroll it doesn't maintain it's position.

**Comment by rexorient** [comment]
Easier "fix" but similarly flawed: add appendTo="body" to p-calendar.

**Comment by sgentile** [comment]
adding appendTo="body" fixed this for me - thank you

**Comment by bonavida** [comment]
I'm sorry to open this after it has been already closed, but with the appendTo="body" workaround, when you scroll it still doesn't maintain its position...

Do you know any other solution for this?

**Comment by joelrlneto** [comment]
For me, I had to set `appendTo="body"` and `baseZIndex = 1050` because I have a navbar with z-index: 1020.
