### ISSUE TITLE
Spinner using input number doesn't respect value if using mousewheel

### ISSUE THREAD

**Issue by fernandaparisi** [primefaces/primeng#5544]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/Tiy0nzXPuGZjaj385oFQ?p=preview

**Current behavior**
PrimeNG spinner control (arrows) don't respect the value that was chosen for the input if it was done using the mousewheel or trackpad.

**Expected behavior**
PrimeNG should increment/decrement on top of the current value on the input, regardless of how it was selected (keyboard, mousewheel, trackpad or spinner control)

**Minimal reproduction of the problem with instructions**
1. Give focus to the input on the spinner and, using mousewheel or trackpad, change its value. 
2. Click on the spinner control arrows. You'll notice the value selected previously was not respected. 

![primeng-spinner](https://user-images.githubusercontent.com/1117355/38645991-9644f6b8-3dbc-11e8-96b7-c4658f13a780.gif)

**Please tell us about your environment:**
MacOS 10.12

* **Angular version:** 5.X
5.2.9

* **PrimeNG version:** 5.X
5.2.4

* **Browser:** 
Chrome 65 _(couldn't test in others)_

**Comment by cagataycivici** [comment]
type number is not supported as it duplicates the functionality.
