### ISSUE TITLE
Change event of p-table programmatically

### ISSUE THREAD

**Issue by lippomano** [primefaces/primeng#5547]
**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/angular-4qz1ye?file=app%2Fapp.component.ts

In my project I need to change the sortField and sortOrder programmatically, is it possible to change some of these events inside p-table, before a lazy table make a request?

I can change the event before making the http GET but of course the table does not render properly( for example sortIcon is incorrect)...maybe in old table there is a method that can help me like .paginate? now?

(the plunker is useless because the request does not have the sorting)

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.2.9

* **PrimeNG version:** 5.2.4

**Comment by cagataycivici** [comment]
Please use forum for questions and help requests.
