### ISSUE TITLE
[Calendar][Request] Allow date-only input when using showTime

### ISSUE THREAD

**Issue by Mysame** [primefaces/primeng#5553]
```
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
```

**Current behavior**
Date-only inputs (ex: 13/04/2018) do not get accepted as a Calendar value if that Calendar is using showTime.
This is because the populateTime() method calls parseTime() on an undefined value, causing an error, which gets catched and sets value to null.
Then in the onBlur, the null value gets discarded.

**Expected behavior**
Date input 13/04/2018 should default so 13/04/2018 00:00 on blur

**Minimal reproduction of the problem with instructions**
Create a p-calendar with showTime="true"
Input 13/04/2018
Tab/Click out of the control

**What is the motivation / use case for changing the behavior?**
Enable quick manual input without necessarily specifying time

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
