### ISSUE TITLE
Change p-dropdown css display property from inline to inline-block

### ISSUE THREAD

**Issue by broweratcognitecdotcom** [primefaces/primeng#5554]
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

The left border does not extend from top to bottom but stops short and looks weird.

.ng-valid[required], .ng-valid.required {
    border-left: 5px solid #42A948;
}

**Expected behavior**
Changing p-select css display from inline to inline-block solves the problem.

**What is the motivation / use case for changing the behavior?**
To be able to use build in Angular validation classes without having to change CSS in order to make it look good.

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
