### ISSUE TITLE
p-dropdown form set value not working

### ISSUE THREAD

**Issue by marcoberri** [primefaces/primeng#5556]
Hello,

I have a problem to set p-dropdown form value

` <p-dropdown [options]="specialita" formControlName="specialita" placeholder="Specialità" [style]="{'width':'100%'}" filter="true"></p-dropdown>` 

in my code:

` this.baseOrganizzazioneForm.controls['specialita'].setValue(specialita)`

not working!

primeng : 5.2.4

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
