### ISSUE TITLE
P-calendar minute selector not working on one day range

### ISSUE THREAD

**Issue by Bab0u** [primefaces/primeng#5557]
Hello,

I encountered a bug with the p-calendar.
- I put showTime at true
- I set min-date to 04/13/2018 10:00 for example
- max-date to the same date, but time at 19:10

When I use it I can't increment minutes to more than 10, even if hour is between 10 and 18.

Problem seems to be in the validateMinute(minute) function, in this example I'll be in the case where selected date === maxDate, and there is just a comparison between minutes, disregarding selected the hour.

Best regards,

**Comment by Jicmou** [comment]
Hello,

Thanks @Bab0u for opening this issue.
I encounter the exact same error. Plus, same behaviour is also present on seconds, when "showSeconds" is set to true.
Seems to appear especially when minDate and maxDate are on the same day.

**Comment by ccd2008** [comment]
Added a pull request with the change required.

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.

**Comment by ccd2008** [comment]
From what I have seen the calendar kinda falls apart on am/pm. Validation for all time changes often freeze and error out as it cannot tell the difference between 5pm and 5am. If you look at the code, it validates the time as military standard without adjusting the 5pm value to 17. You can bypass the min/max by using am/pm changes and cause an error. It also does not maintain am/pm on date change.
