### ISSUE TITLE
Easy and handy navigation from tabview using routerLink attribute

### ISSUE THREAD

**Issue by itwasnoteasy** [primefaces/primeng#5562]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
Under this file you can add routerLink attribute for anchor tag. This will be a very easy injection of routerLink rather than handling event and setting it under TS file.
https://github.com/primefaces/primeng/blob/master/src/app/components/tabview/tabview.ts

**What is the motivation / use case for changing the behavior?**
This will help developers. They may simply add the routerLink attribute under p-tabPanel tag rather than handling the event and using Router object to set the link.

* **Angular version:** 5.X

* **PrimeNG version:** 5.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Better to use p-tabMenu instead.
