### ISSUE TITLE
Change [paginator] attribute from DataTable in runtime.

### ISSUE THREAD

**Issue by upmauro** [primefaces/primeng#5568]
I'm submitting a
```
[X] feature request
```

**Plunkr Case (Bug Reports)**

http://plnkr.co/edit/pIHuiEKgaVzl009Xcd5j?p=preview

**Current behavior**

Can't change property [paginator] from datatable in runtime.  

**Expected behavior**

Enable two way data binding for this property.

**Minimal reproduction of the problem with instructions**
See plunkr

**What is the motivation / use case for changing the behavior?**
I know about data table depreciation, but the feature is very important when you need print the page.

**Comment by apphillipe** [comment]
+

**Comment by victorguimaraessilva** [comment]
+1

**Comment by cyberrranger** [comment]
problems:

1. window.print() stop the execution
2. datatable is deprecated

solution:
http://plnkr.co/edit/Vn7e0xelEF8j5UHTjToU?p=preview

**Comment by victorguimaraessilva** [comment]
I've resolved this issue with this approach 

startPrinting() {

    var promise = new Promise((resolve, reject) => {
      this.dt.paginator = false;
      this.dt.updatePaginator();
      this.dt.reset();
      this.dt.changeDetector.detectChanges();
      resolve();

    }).then((data) => {

      window.print();
      this.dt.paginator = true;
      this.dt.updatePaginator();
      this.dt.reset();
    });
  }

**Comment by cagataycivici** [comment]
DataTable is deprecated, please use TurboTable instead.
