### ISSUE TITLE
p-schedule throws ExpressionChangedAfterItHasBeenCheckedError when lazy loading events

### ISSUE THREAD

**Issue by stefandroog** [primefaces/primeng#5569]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/qtZi5lB3DjkNt7Kdivg9?p=preview

**Current behavior**
The component throws an exception:

`ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: '[object Object],[object Object],[object Object],[object Object],[object Object]'.`

I used the example of the documentation: https://www.primefaces.org/primeng/#/schedule

**Expected behavior**
No exception 

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/nBpBA6vSQcT06FePB8ID?p=preview

**What is the motivation / use case for changing the behavior?**
-

**Please tell us about your environment:**
-

* **Angular version:** 5.X
5.2.4

* **PrimeNG version:** 5.X
5.2.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
-

* **Node (for AoT issues):** `node --version` =   
-

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
