### ISSUE TITLE
Turbo Table : Row Expansion using row index and not dataKey

### ISSUE THREAD

**Issue by StewartJingga** [primefaces/primeng#5574]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

I'm using turbo table with rowexpansion. The problem is when I'm trying to combine it with reactive form because rowexpansion requires dataKey attribute to be presented. 

As far as i understand, dataKey has to be unique for single row expansion.

At this case and my several other cases, my data does not have a unique property.

Can we use index of the row as a mean to tell the expander which row it should expand?

**What is the motivation / use case for changing the behavior?**

To allow expansion without unique key/property on the data

**Please tell us about your environment:**

* **Angular version:** 5.X

* **PrimeNG version:** 5.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Index is not a good idea as it will change when data changes so still you need to provide or generate a unique key.

**Comment by cms-fc** [comment]
why not create Map or Set to track this by ref
i how now a case that using a key is not masking any sense
