### ISSUE TITLE
p-table Frozen column group does not align in 6.0.2 (works fine in 5.2.3)

### ISSUE THREAD

**Issue by simdevmon** [primefaces/primeng#5578]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
The frozen column height does not align with the content anymore. This is also visible in the showcase: https://www.primefaces.org/primeng/#/table/scroll

![2018-04-18_09h29_44](https://user-images.githubusercontent.com/16277781/38917478-37f150dc-42eb-11e8-9d96-9480ca44dcd5.png)

**Expected behavior**
Same behavior as in 5.2.3. It worked fine there so I assume it is a regression.

**Angular version:** 5.X
5.2.10

**PrimeNG version:** 5.X
5.2.4 - 6.0.2+

**Browser:**
Chrome 68

**Comment by sky007** [comment]
Already created an bug report of it [#5485](https://github.com/primefaces/primeng/issues/5485)

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/issues/5485
