### ISSUE TITLE
p-dropdown don't display selectedItem template content

### ISSUE THREAD

**Issue by tbalaye** [primefaces/primeng#5583]
`[x]` bug report => Search github for a similar issue or PR before submitting
`[ ]` feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
`[ ]` support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/bl5rMs?p=preview

**Current behavior**
I'm trying to display a template customized dropdown list with the example provided in the documentation : https://www.primefaces.org/primeng/#/dropdown ("Custom Content" section)

It works as expected for `pTemplate="item"` but not with `pTemplate="selectedItem"`. I've not found similar issues on this.

**Expected behavior**
I would like to customize the selected value as showed on documentation.

**Minimal reproduction of the problem with instructions**
Code snippets:

>`<p-dropdown`
>`  [options]="countries"`
>`  [(ngModel)]="selectedCountry"`
>`  [style]="{'width':'100px'}"`
>`  [panelStyle]="{'width':'400px'}">`
>`  <ng-template let-country pTemplate="selectedItem">`
>`      <img src="{{country?.flag}}"/>`
>`      <span>+{{country?.prefix}}</span>`
>`  </ng-template>`
>`  <ng-template let-country pTemplate="item">`
>`      <div class="ui-helper-clearfix" style="position: relative;height: 25px;">`
>`          <img src="{{country?.flag}}"/>`
>`          <span style="color: grey">+{{country?.prefix}}</span>`
>`      </div>`
>`  </ng-template>`
>`</p-dropdown>`

See Plunkr for more informations

* **Angular version:** 5.2

* **PrimeNG version:** 5.0.2

* **Browser:** all
 
* **Language:** TypeScript 2.7

**Comment by Pikadili83** [comment]
The problem is that let-country for pTemplate="selectedItem" is not country object, it is:
{
label: "optionLabel",
value: {...//country object
}

**Comment by tbalaye** [comment]
Thank you ! That's it, sorry for the inconvenience.

**Comment by teuf22** [comment]
This should be added to the documentation.
