### ISSUE TITLE
p-calendar dateFormat into locale

### ISSUE THREAD

**Issue by rubenns** [primefaces/primeng#5585]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
You need to put the date format like a input.

**Expected behavior**
set de date format into calendar locale settings.

**What is the motivation / use case for changing the behavior?**
It's necessary to create a settings by locale and the format depends of the locale, then it's a good improvement to set directly the format date, and if you want to rewrite this format, you can set the format from the input.

* **Angular version:** 5.2.0

* **PrimeNG version:** 5.2.4

**Comment by WouterBos** [comment]
I encountered this same issue in version 7.1.2 The got around this issue to use the separate [dateFormat] attribute.

`<p-calendar formControlName="expirationDate" id="expirationDate" [dateFormat]="locale.dateFormat" [locale]="locale"></p-calendar>`

**Comment by da5407** [comment]
no error message, just not work as locale setting, I need help.

**Comment by da5407** [comment]
<p-calendar [showIcon]="true" name="mdate" id="mdate" formControlName="mdate" [showTime]="false"  [locale]="locale" dateFormat="yy/mm/dd" [showButtonBar]="true" [monthNavigator]="true"  [yearNavigator]="true" yearRange="2000:2030"></p-calendar>
