### ISSUE TITLE
p-table export 2 files one time

### ISSUE THREAD

**Issue by una-chou** [primefaces/primeng#5587]
how to export 2 tables one time in one csv or excel? like 2 sheets in an excel ? If p-table can export the type of excel file with .xlsx or only can export the type of csv?

**Comment by unaJJJ** [comment]
how to export 2 tables one time in one csv or excel? like 2 sheets in an excel ?  If p-table can export the type of excel file with .xlsx or only can export the type of csv?

**Comment by cagataycivici** [comment]
Please use forum for questions and help requests.
