### ISSUE TITLE
Chips max property doesnt work correctly

### ISSUE THREAD

**Issue by greggyPL** [primefaces/primeng#5588]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

http://plnkr.co/edit/1cR3krC5TSuUCYFVfvhm?p=preview

**Current behavior**
Currently, when I assign max property to Chips components, I cant add more than X items, but also I cant add item with string length greater than X.

**Expected behavior**
Property max should be used only to limit number of items, not length of individual items.

**Comment by JacobSiegle** [comment]
Seems like it's been fixed, can you confirm and if it's fixed close the issue.
