### ISSUE TITLE
p-paginator: paginatorState is not being updated when totalRecords changes

### ISSUE THREAD

**Issue by pfms84** [primefaces/primeng#5589]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/jhHF1rfwAKxZWytyGstF?p=preview

**Current behavior**
When using a template with p-paginator, the paginatorState does not get updated when totalRecords changes.

**Expected behavior**
The paginatorState should reflect the internal state of the p-paginator.

* **PrimeNG version:** 5.2.3

**Comment by cagataycivici** [comment]
This should be fixed in 7.0 and latest 6.x
