### ISSUE TITLE
Refactor toggle button icon binding performance

### ISSUE THREAD

**Issue by AndreaBarbasso** [primefaces/primeng#5596]
https://github.com/primefaces/primeng/blob/10325e16c12e532172012cf3f05390547d1f2d9a/src/app/components/togglebutton/togglebutton.ts#L21

Easily fixable with `class="ui-button-icon-left fa fa-fw {{ checked ? onIcon : offIcon }}"`

**Comment by cagataycivici** [comment]
Added;

```xml
<span *ngIf="onIcon||offIcon" class="ui-button-icon-left" [ngClass]="checked ? this.onIcon : this.offIcon"></span>
```

**Comment by AndreaBarbasso** [comment]
@cagataycivici I think the code should be `[ngClass]="checked ? onIcon : offIcon"`, dropping `this`.
