### ISSUE TITLE
Can't bind to 'showClear' since it isn't a known property of 'p-dropdown'.

### ISSUE THREAD

**Issue by kalyan542** [primefaces/primeng#5597]
Getting issue when i add [showClear] = "true" property in primeNG dropdown
1. If 'p-dropdown' is an Angular component and it has 'showClear' input, then verify that it is part of this module.
2. If 'p-dropdown' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

**Comment by noamichael** [comment]
This usual means that the property in question isn't declared with an `@Input` annotation. [The `showClear` property was added in version 5.2.4](https://github.com/primefaces/primeng/commit/a950f8a927138f0ad0dc165ec1b666b828513c48). My guess is that you haven't imported `p-dropdown` properly, or you're using an older version of PrimeNG. Can you give us a Plunkr to confirm the behavior?

**Comment by kalyan542** [comment]
Working fine After upgrading my primeNG version from 4.3.0 to 5.2.4.Thanks noamichael
