### ISSUE TITLE
getting error "No value accessor for form control with unspecified name attribute" with table's toggle feature

### ISSUE THREAD

**Issue by yashpalsingh6840** [primefaces/primeng#5601]
Hi,

I am using prime  [ng trubo](https://www.primefaces.org/primeng/#/table/coltoggle). It really cool control, however I am getting error "No value accessor for form control with unspecified name attribute" while using toggle feature. Below is my HTML markup, can someone pls help me.

`<div class="row"><div class="col-md-12">    <p-table #dt [columns]="dataTableCols" [value]="data" [paginator]="true" [reorderableColumns]="true" rowHover="true" [rows]="10"
      [responsive]="true">      <ng-template pTemplate="caption">        <div style="text-align:left">          <p-multiSelect [options]="dataTableCols" [(ngModel)]="selectedColumns" optionLabel="header" selectedItemsLabel="{0} columns selected"            [style]="{minWidth: '200px'}" defaultLabel="Choose Columns"></p-multiSelect>        </div>        <div style="text-align: right">          <i class="fa fa-search" style="margin:4px 4px 0 0"></i>          <input type="text" pInputText size="50" placeholder="Global Filter" class="form-control" (input)="dt.filterGlobal($event.target.value, 'contains')"            style="width:auto">        </div>      </ng-template>      <ng-template pTemplate="header" let-columns>        <tr>          <th *ngFor="let col of columns" [pSortableColumn]="col.field">            {{col.header}}
            <p-sortIcon [field]="col.field"></p-sortIcon>          </th>          <th>            Action
          </th>        </tr>      </ng-template>      <ng-template pTemplate="body" let-rowData let-columns="columns">        <tr [pSelectableRow]="rowData">          <td *ngFor="let col of columns">
            {{rowData[col.field]}}          </td>          <td>
            <button class='btn btn-primary cs_bg_clr_blue' (click)="onVerifyClick(rowData)">Verify</button>
          </td>        </tr>
      </ng-template>    </p-table>  </div></div>`

**Comment by markgoho-EDT** [comment]
@yashpalsingh6840 when you paste in a code block, use three back-ticks at the top like this ` ``` [code-type]` and then three at the bottom,

so for example, your code above:

` ``` html`
code goes here
` ``` `

This will make it much easier for folks to help you!

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.
