### ISSUE TITLE
p-table inside a wrapper component

### ISSUE THREAD

**Issue by rizap** [primefaces/primeng#5605]
Hi I'm using p-table inside my wrapper component that looks like this.
**x-table.component:**
```
 <p-table>
       <ng-container ></ng-container> -----> template for the header
      <ng-container></ng-container> -----> template for the the body
   </ptable>
```

In other pages I call my x-table wrapper component like this:
```
<x-table [headerTemplate]="headerTemplate " [bodyTemplate]="bodyTemplate">
   <ng-template #headerTemplate let-columns="columns">
        <tr>
          <th *ngFor="let col of columns" [pSortableColumn]="col.field"> ---> how can I access pSortableColumn from x-table?
            {{col.name}}
          </th>
        </tr>
      </ng-template>
     <ng-template #bodyTemplate let-columns="columns" let-rowData>
        <tr>
          <td>
              {{rowData.name}}
          </td>
       </tr>
    </ng-template>
</x-table>
```

My problem is since the p-table is inside the x-table wrapper, I cannot access [pSortableColumn] as well as the other primeng attributes (pRowToggler and etc). Do you have idea on how to access it using my wrapper component? Thanks!

**Comment by markgoho-EDT** [comment]
@rizap I think you want to use `<ng-content>` instead of `<ng-container>`

**Comment by rizap** [comment]
Thanks @markgoho-EDT! will try that.

**Comment by Wassim24** [comment]
Hello @rizap did @markgoho-EDT  trick worked for you ? Thank you

**Comment by cagataycivici** [comment]
Please use forum for support requests and questions.
