### ISSUE TITLE
Message Styling

### ISSUE THREAD

**Issue by mousedown** [primefaces/primeng#5606]
The styling on the Messages component has changed in 5.2.4 . 

I presume that this is a bug 
<img width="93" alt="screen shot 2018-04-22 at 10 27 13" src="https://user-images.githubusercontent.com/491789/39093479-362aea30-4618-11e8-9212-9bc6ba3f779a.png">

<img width="250" alt="screen shot 2018-04-22 at 10 30 01" src="https://user-images.githubusercontent.com/491789/39093480-3f5112ce-4618-11e8-8dba-1b466467ec5f.png">

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/qtZi5lB3DjkNt7Kdivg9?p=preview

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.X

* **PrimeNG version:** 5.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
