### ISSUE TITLE
Support drag and drop between components

### ISSUE THREAD

**Issue by TKul6** [primefaces/primeng#5607]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Today we have a tree component.
This component allow to drag ans drop items from one tree to the other.

**Expected behavior**
It will be cool if we could drag and drop items **between different primeng controls**.
For example:
Have a data list with all the items and allow to drag item from the list to a specific node in the tree.

**What is the motivation / use case for changing the behavior?**
I need to share data between several components.
I know I can do this with a selected item and a button.
If I could drag and drop the items, however, it will give much better user experience. 

What do you say?
Thanks.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
