### ISSUE TITLE
MenuModel API: Access component functions

### ISSUE THREAD

**Issue by MarcelCremer** [primefaces/primeng#561]
Hello,

I would suggest to bind the MenuItems in the MenuModel API to Component fuctions just like the button for example does with it's event binding.

At the Moment, you can only provide an itemLink or an "command", which has access to native events but not to the angular components. That's why I'm currently doing many workarounds (e.g. Toolbar instead of MenuBar), so that I can access the functions.

A simple use case:
Click on a MenuItem, check if this.foo == true and then navigate somewhere (or not). This isn't possible atm, because there's no component scope for the callbacks.

A second idea that goes through my mind:
If you would make the menus more flexible (like the toolbar), problems like in #384 wouldn't occur and the whole framework would offer more options.

E.g:
- Eliminate Menubar (You can do this with the Toolbar - and you can do it better!)
- Make the other components "template" based, e.g. with an ul that will be rewritten to a menu

Then everyone could build menus much more flexible and you wouldn't have to maintain the MenuModel API which is too restricted.

**Comment by cagataycivici** [comment]
Thanks, we'll reopen if more users demand it, we need more feedback.

**Comment by dhniels** [comment]
This sounds like the same problem im facing, which is trying to use the .toggle function to open/close an OverlayPanel when clicking on a menu item.

**Comment by davpirelli** [comment]
Up
