### ISSUE TITLE
Paginator - can't move to next / previous page if [rows] is not defined.

### ISSUE THREAD

**Issue by TKul6** [primefaces/primeng#5610]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/f6bCgm5o3UPdTPRWHLpm?p=preview

**Current behavior**
When adding paginator with no [rows] / [first] and [totalRecords] properties defined I simply can not paginate anything.

The links are enabled, However when I click on them nothing happens. If I set the [rows] property so the links become disabled and I can't do anything.

Just a quick explanation about my use case: I have slices of data presented in my UI. I don't know how many records I have (Which means I can not set the total records) 

**Expected behavior**
I would like the paginator to emit events, even if the properties are not defined. (Maybe should add a [lazy] property).

**Minimal reproduction of the problem with instructions**
Just create a pagniator with no properties defined (as in the following plunker)
http://plnkr.co/edit/f6bCgm5o3UPdTPRWHLpm?p=preview

**What is the motivation / use case for changing the behavior?**
It is costly for me to figure out the total records property, and  either than the page links (which is not a must for me) I don't need it. 
**Please tell us about your environment:**
Winddows,
NPM 5.5.1
Node 9.0.0

* **Angular version:** 5.X
5.1.0

* **PrimeNG version:** 5.X
5.2.4
* **Browser:** All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
rows is mandatory.
