### ISSUE TITLE
Overlay panel doesn't shows in ng prime 5.2.4

### ISSUE THREAD

**Issue by ibtisamniche-vteams** [primefaces/primeng#5611]
Hi!
Currently I am using version 4.2.1, with this version overly panel is working fine but I can't find any import for side bar so I upgraded my version to latest and used side bar functionality. After upgrading to latest version the overlay panel functionality got disturbed and overlay panel is showing no more.
Can you tell what's wrong???
Thanks.

**Comment by bpbhat77** [comment]
May be issue with z-index? Any error on console ?

**Comment by ibtisamniche-vteams** [comment]
No there is no error on console.

**Comment by ibtisamniche-vteams** [comment]
When I use overlay in primeng 5.2.4 it adds inline style and in that style it adds the property display:none but when I call toggle event then it doesn't change that inline style of display:none that is being added by default by primeng.
If I use version 4.2.1 then the toggle event changed that inline style to display:block.

**Comment by bpbhat77** [comment]
Can you please print by calling method and print the value in console
 ` (click)="selectCar($event,car,op3);"`

You can also try with `(mouseenter)="op2.show($event)"`

**Comment by lasimone** [comment]
I am using primeng@5.2.6 and this is still occurring.

**Comment by ibtisamniche-vteams** [comment]
Any help on this?
I have to fix this please.

**Comment by cagataycivici** [comment]
Seems to be related to;

https://github.com/primefaces/primeng/issues/6467
