### ISSUE TITLE
Default animations for Row Expand in Turbo Table

### ISSUE THREAD

**Issue by ayush987goyal** [primefaces/primeng#5612]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

There is no animation when row expands/collapses in Turbo Table

**Expected behavior**

There can be a default transition animation for expanding the rows.

**Please tell us about your environment:**

* **Angular version:** 5.X

* **PrimeNG version:** 5.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   8.9.X

**Comment by cagataycivici** [comment]
It should better be handled on the application side to avoid enforcing a certain animation so that you can configure your own, I've added a sample animation to the demo.

**Comment by nasreddineskandrani** [comment]
@cagataycivici  can you send a link to point  where you added this?

**Comment by cmccoy98** [comment]
I too am curious as to where this sample animation is in the demo for row expansion?
