### ISSUE TITLE
SlideMenu autoWidth and nowrap

### ISSUE THREAD

**Issue by bbuehrer** [primefaces/primeng#5615]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/1ay5ShGuqPTYDOkQhUYU?p=preview

Is there a way to set SlideMenu to "autoWidth" and don't wrap the item-text?

When i set

.ui-menuitem {
    white-space: nowrap;
}

then the SlideMenu is to small !

**Comment by cagataycivici** [comment]
Please use forum for questions and help requests.
