### ISSUE TITLE
Editor: Unable to remove the tabindex on colour buttons

### ISSUE THREAD

**Issue by tleveque23** [primefaces/primeng#5616]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/github//tleveque23/primengeditortabbug

**Current behavior**
On every button element, we put the tabindex=-1 because we need the tab key to jump directly into the editor from the previous field. It work for every buttons, but not for the "ql-color" and "ql-background" ones (in fact for those two, we need to use a select element)

**Expected behavior**
tabindex=-1 work and the tab key send the cursor directly in the editor.

**Minimal reproduction of the problem with instructions**
Create an editor with a custom toolbar that include ql-color and ql-background button. Add tabindex=-1 on every button.
Have a input field juste before.

* **Angular version:** 5.X
5.2.9

* **PrimeNG version:** 5.X
5.2.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web All

**Comment by cagataycivici** [comment]
This is an issue with quill, not PrimeNG.
