### ISSUE TITLE
Non-frozen columns don't move or resize when frozen columns' width changes

### ISSUE THREAD

**Issue by adama357** [primefaces/primeng#5617]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

http://plnkr.co/edit/7Mns2fJdQ111mqHMVMS4?p=preview

**Current behavior**
When you have a table with some frozen columns, the div containing the second table (unfrozen) has the "left" property calculated once.  The left property doesn't get updated if the frozen columns' width changes.  (**EDIT:** The div containing the second table also needs to have its width updated to calc(100% - [frozenWidth])) 

Thus, in this Plunk, changing the window size results in situations like these: 

![frozen_demo_2](https://user-images.githubusercontent.com/20462430/39145080-4bbed38a-46f8-11e8-919f-46d3dd75b3bb.png)
![frozen_demo_3](https://user-images.githubusercontent.com/20462430/39145085-4ed8bdd8-46f8-11e8-8fc3-06496ea4fbb7.png)

**Expected behavior**
The second table should always appear directly next to the first table, even if the first table's width changes.  (This would most likely be accomplished by having "left" updated.)
**EDIT:** The div containing the second table also needs to have its width updated to calc(100% - [frozenWidth])

**Please tell us about your environment:**

* **Browser:** Chrome, Firefox

**Comment by sabithpocker** [comment]
This calculation is only done in [`ngAfterViewInit()` of `ScrollableView`](https://github.com/primefaces/primeng/blob/master/src/app/components/table/table.ts#L1782) and never updated again. Also, there is no `unfrozenWidth` anymore to handle it ourselves.

For me I have `frozenWidth` as a combined `Observable` stream of a calculation and window resize event. So whenever it changes, I am making a hack to do the calculation.

```

  setUnfrozenWidth(frozenWidth: number): void {
    const el  = this.dataTable ? this.dataTable.el.nativeElement: null;
    if(el && el.querySelector('.ui-table-unfrozen-view')) {
      if(frozenWidth > 0) {
        el.querySelector('.ui-table-unfrozen-view').style.width = `calc(100% - ${frozenWidth}px)`;
        el.querySelector('.ui-table-unfrozen-view').style.left = `${frozenWidth}px`;
      } else {
        el.querySelector('.ui-table-unfrozen-view').style.position = `static`;
        el.querySelector('.ui-table-frozen-view').style.display = `none`;
        
      }
    }
  }
```

The `else` condition is doing some style changes to accommodate `frozenColumns = []` and `frozenWidth=0px`. I have configurable columns and there can be cases where none are set to frozen.

**Comment by thedanielgray** [comment]
I've pushed a simpler fix to this issue at https://github.com/primefaces/primeng/pull/6627/files

**Comment by cagataycivici** [comment]
Should be fixed in 7.x.
