### ISSUE TITLE
Docs error on file upload

### ISSUE THREAD

**Issue by blackholegalaxy** [primefaces/primeng#5618]
**I'm submitting a ...**
```
[x] docs error 
[ ] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
On file upload events table, the `onProgress` description is `when files are selected` which is a duplicate from previous line.

Maybe the real callback explanation could be wrote here. 

By the way, using custom handler to upload using FileReader over websocket, how to send to component any progress information?

**Comment by Mynken** [comment]
1) How it now works:
https://ibb.co/fMUf1x
2) Expected behavior:
https://ibb.co/cWxB8c
