### ISSUE TITLE
The way to add event listener

### ISSUE THREAD

**Issue by LiTiang** [primefaces/primeng#562]
For example, if we have a 3rd component, and it looks like below

``` typescript
@Component({
  selector:'comp',
  template:`<div><a>JUST_TEST</a></div>`
})
export class ThreePartyComp {}
```

We use it in our component, and it works great.

But how can we listen click event on `<a>` of ThreePartyComp in Angular2 way if ThreePartyComp dont have API for us to do something once some event occur on it ?  

I know **PrimeNG** do a good job for us to such thing,
for example, if i want to do something after one of the **PrimeNG** Menubar's button (says, quit-icon button, anyway) is clicked, we can see there're API called `command` property on **PrimeNG** MenuItem,   then  we can easily write our action in `command` !!!

I think 3rd component need to do the same thing as **PrimeNG**, right ?
I'm so confuse about that ...

**Comment by MarcelCremer** [comment]
This is really an angular2 related question and has nothing to do with primeNG. However, you can bind events to native Web Events using ()-Operators (e.g. <a (click)="foo(event)"></a>).

Please think of taking the angular tutorial https://angular.io/docs/ts/latest/tutorial/ or other tutorials available on the web :)

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
