### ISSUE TITLE
p-table radiobutton

### ISSUE THREAD

**Issue by donriver** [primefaces/primeng#5620]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/UJ0HX6VGlMAC3QJe?preview

**Current behavior**
p-tableRadioButton stop working with [selectionMode] = "'single'"
wihtout this mode can't select row by clicking on data cells

**Expected behavior**
row can be selected by clicking on radiobutton ot data cells

**Minimal reproduction of the problem with instructions**
try to select row

**Please tell us about your environment:**

* **Angular version:** 5.2.0

* **PrimeNG version:** 5.2.3

* **Browser:** tested in Chrome 65X and Firefox 56.0.2

 
* **Language:** TypeScript 2.0.3

**Comment by JacobSiegle** [comment]
Fix #6552.

**Comment by cagataycivici** [comment]
It is not supported to use tableRadioButton and row selection at the same time, it should be one or the other.

**Comment by JacobSiegle** [comment]
You can probably close #5801 which is the same issue but for checkboxes.
