### ISSUE TITLE
Lazy loading doesn't work on the Accordion

### ISSUE THREAD

**Issue by Peilonrayz** [primefaces/primeng#5621]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**[Link to Plunkr][0]**

**Current behavior**

1. Open the page.
2. Open A, or B, and see "Content: ".
3. Wait 5 seconds.
4. Should see "non-lazy loaded" and "Content: content" load at the same time.
5. Open B, or A, and see "Content: content".
6. Open C and see nothing. Not even "Content: ".  
    (Assuming you'll make [lazy loading work the same way as Tab View][1]).

**Expected behavior**

1. Open the page.
2. Open A, or B, and see "Content: ".
3. Wait 5 seconds.
4. "non-lazy loaded" should show before "Content: content".
5. Open B, or A, and see "Content: ".
6. Wait 5 seconds.
7. You should now see "Content: content".
8. Open C and see "Content: ".
9. Wait 5 seconds.
10. You should now see "Content: content".

**What is the motivation / use case for changing the behavior?**

Not only does [Tab View do this][1], this feature was requested in the same change request (#1808).

It also means that you can have less data loaded on page load. And when you're storing slow operations in the accordion the page won't grind to a halt whilst loading.

  [0]: http://plnkr.co/edit/jroGnBefJmL3tlpdvZcp?p=preview
  [1]: https://www.primefaces.org/primeng/#/tabview

**Comment by rafa-as** [comment]
Same here!
