### ISSUE TITLE
add support for 3rd party modules to quill editor (image drop and resize)

### ISSUE THREAD

**Issue by jamjamg** [primefaces/primeng#5622]
<pre>
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
</pre>

The primeng editor component currently does not allow registering 3rd party modules. Especially [quill-image-resize-module](https://www.npmjs.com/package/quill-image-resize-module) and [quill-image-drop-module](https://www.npmjs.com/package/quill-image-drop-module) are very useful modules.

Please add support for registering 3rd party modules (or at least image resize and drop capabilities).

- related: #2050
- this topic is also discussed over here: https://forum.primefaces.org/viewtopic.php?t=51125

The current initilization code of quill inside [`editor.ts`](https://github.com/primefaces/primeng/blob/master/src/app/components/editor/editor.ts) would need to be enhanced similar to this:
<pre>
import { ImageResize } from 'quill-image-resize-module';
Quill.register('modules/imageResize', ImageResize);
// ...
var quill = new Quill(editor, {
    modules: {
        ImageResize: {}
    }
});
</pre>

current snippet from [`editor.ts`](https://github.com/primefaces/primeng/blob/master/src/app/components/editor/editor.ts):
<pre>
this.quill = new Quill(editorElement, {
    modules: {
        toolbar: toolbarElement
    },
    placeholder: this.placeholder,
    readOnly: this.readonly,
    theme: 'snow',
    formats: this.formats
});
</pre>

**Comment by marchino21** [comment]
Any updates on this?

**Comment by salem017** [comment]
Any updates ?

**Comment by cagataycivici** [comment]
Handled via;

https://github.com/primefaces/primeng/issues/5695

**Comment by Svancara** [comment]
It does not work.

I mean your 
> It has a new modules property to define your own modules.

This modules property of p-editor is **not enough**.
Modules have to be **registered** in Quill.
There is no "quill.register(...)" code in the PrimeNG editor code.
And - attempts to use some module fail.

**Comment by rogerex** [comment]
> It does not work.
> 
> I mean your
> 
> > It has a new modules property to define your own modules.
> 
> This modules property of p-editor is **not enough**.
> Modules have to be **registered** in Quill.
> There is no "quill.register(...)" code in the PrimeNG editor code.
> And - attempts to use some module fail.

And if you try to register modules before, you can't, because editor.js is importing quill again overwriting your registered modules. [primeng version: 8.0.3]

The unique solution is import the modules in the same component:

`
import * as ImageResize from 'quill-image-resize-module';
ngOnInit(): void {
    Quill.register('modules/imageResize', (quill: any, options: any) => {
      new (ImageResize.default as any)(quill, options);
    });
  }`
