### ISSUE TITLE
calander blur event - showButtonBar does not work

### ISSUE THREAD

**Issue by MosheMoualem** [primefaces/primeng#5623]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

http://plnkr.co/edit/qtZi5lB3DjkNt7Kdivg9?p=preview

**Current behavior**

Using Calander component - when blur event is set
and showButtonBar  is set to true - clear and today events does not work
If I remove the blur event the today and clear buttons works as expected

**Expected behavior**

use blur event and showButtonBar  together 
be able to catch the blur event and the today|clear actions.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

blur event  is critical - going to server only on blur event
**Please tell us about your environment:**

IDE - WebStorm, NPM, Node JS
* **Angular version:** 5.2.9

* **PrimeNG version:** 5.2.4

* **Browser:** [all]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.5.3
* **Node (for AoT issues):** `node --version` =   
node version 6.6

**Comment by MosheMoualem** [comment]
any update on this isssue ? 
it's still happening in version 6.1.2

**Comment by cagataycivici** [comment]
We're unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
