### ISSUE TITLE
'p-tabPanel' is not a known element

### ISSUE THREAD

**Issue by taiducnguyen** [primefaces/primeng#5626]
Hi,

Primeng not working in my project, I'm getting this error:
![image](https://user-images.githubusercontent.com/22149480/39204082-f12b16a2-4820-11e8-9617-fe223743a947.png)

I'm in angular 5, primeng v5.2.4 and wepack

Could you please help to check this?

**Comment by blackholegalaxy** [comment]
You have to `import` the proper `TabViewModule` in the module where the component which uses tabPanel (SharedModule as we can see on your error).

As stated in the doc, `TabViewModule` contains both `p-tabView` and `p-tabPanel` components.

**Comment by taiducnguyen** [comment]
Hi @blackholegalaxy 

I already imported TabViewModule in app.module but it's still not working

import { TabViewModule } from 'primeng/components/tabview/tabview';

![image](https://user-images.githubusercontent.com/22149480/39222381-9d5a6f28-4866-11e8-9822-1bd03753139f.png)

**Comment by nartc** [comment]
Looks like you have to import it in SharedModule

**Comment by taiducnguyen** [comment]
Thanks @nartc very much! It's working now

**Comment by 0101salman00** [comment]
my html file has below code :-

<p-panel>
<p-header>
Header content here
</p-header>
Body Content
</p-panel>
I have added imported required modules in my module from primeng :-

import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { MyComponent } from './my.component';
import { CommonModule } from '@angular/common';
import { SharedModule, PanelModule } from 'primeng/primeng';

`

@NgModule({
imports: [
CommonModule, SharedModule, PanelModule
],
declarations: [MyComponent],
schemas: [CUSTOM_ELEMENTS_SCHEMA ]
})
export class ThemeModule { }
This is throwing below error in console :-

EXCEPTION: Uncaught (in promise): Error: Template parse errors: 'p-header' is not a known element: 1. If 'p-header' is an Angular component, then verify that it is part of this module. 2. If 'p-header' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("

<a href="https://showbox.buzz/">showbox</a> <a href="https://vidmates.net/">vidmate</a> <a href="https://cartoonhds.com/">cartoonhds</a> <a href="https://popcorn-times.com/">popcorn time</a> <a href="https://mobdros.com/">mobdro</a> <a href="https://terrariumtv-download.com/">terrarium tv</a> <a href="https://videoderdownloads.com/">videoder</a> <a href="https://apktroll.com/gbwhatsapp/">gbwhatsapp</a> <a href="https://theshayari.in/sad-shayari-hindi/">sad shayari</a>

**Comment by vinodbalakumar** [comment]
ERROR in src/app/info/info.component.html:3:11 - error NG8001: 'p-table' is not a known element:
    1. If 'p-table' is an Angular component, then verify that it is part of this module.
    2. If 'p-table' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
    
    3           <p-table [value]="books">
                ~~~~~~~~~~~~~~~~~~~~~~~~~
    
      src/app/info/info.component.ts:6:16
        6   templateUrl: './info.component.html',
                         ~~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component InfoComponent.
    src/app/info/info.component.html:3:20 - error NG8002: Can't bind to 'value' since it isn't a known property of 'p-table'.
    1. If 'p-table' is an Angular component and it has 'value' input, then verify that it is part of this module.
    2. If 'p-table' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
    3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.
    
    3           <p-table [value]="books">
                         ~~~~~~~~~~~~~~~
    
      src/app/info/info.component.ts:6:16
        6   templateUrl: './info.component.html',
                         ~~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component InfoComponent.
    
    
    ERROR in src/app/info/info.component.html:3:11 - error NG8001: 'p-table' is not a known element:
    1. If 'p-table' is an Angular component, then verify that it is part of this module.
    2. If 'p-table' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
    
    3           <p-table [value]="books">
                ~~~~~~~~~~~~~~~~~~~~~~~~~
    
      src/app/info/info.component.ts:6:16
        6   templateUrl: './info.component.html',
                         ~~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component InfoComponent.
    src/app/info/info.component.html:3:20 - error NG8002: Can't bind to 'value' since it isn't a known property of 'p-table'.
    1. If 'p-table' is an Angular component and it has 'value' input, then verify that it is part of this module.
    2. If 'p-table' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
    3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.
    
    3           <p-table [value]="books">
                         ~~~~~~~~~~~~~~~
    
      src/app/info/info.component.ts:6:16
        6   templateUrl: './info.component.html',
                         ~~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component InfoComponent.

**Comment by aruyc** [comment]
> Looks like you have to import it in SharedModule

 @nartc - please explain this. unable to solve error for p-toolbar.
