### ISSUE TITLE
dropdown and autocomplete don't have p-header as a header template.

### ISSUE THREAD

**Issue by aminTiz** [primefaces/primeng#5627]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
currently components like dropdown and autocomplete don't have p-header as a header template.

**Expected behavior**
It would be very usefull to have header on these components to have be able to add customized template for header like filter buttons or add buttons or ....
Actually we created a custom component now but t would be very nice to have this feature built in.

**What is the motivation / use case for changing the behavior?**
in the project there is a search box that loads data from different sources and I need to have buttons for filtering them based on source name like(customers/companies)

**Comment by Serg-Mois** [comment]
+ I need 'Add new' button at the top of dropdown list.

**Comment by tommancini** [comment]
@Serg-Mois I need something similar and had to create a rig for now.  Did you come up with an elegant solution for this?

**Comment by gasparbarancelli** [comment]
@cagataycivici 
You can attribute this improvement to me, I can develop it.

**Comment by tommancini** [comment]
@aminTiz Would you mind sharing the custom component you created as a workaround for this?

**Comment by adopilot** [comment]
Sorry for jumping in but looks like this is solved,
I can define heder with 

```
 <ng-template  pTemplate="header" >
        <span>Kakav si mi šta se radi</span>
    </ng-template>
```
Inside p-autoComplete

**Comment by cetincakiroglu** [comment]
Solved, both components support header template
