### ISSUE TITLE
File upload onSelect returns no file

### ISSUE THREAD

**Issue by blackholegalaxy** [primefaces/primeng#5628]
**I'm submitting a ...**
```
[x] bug report
```

**Current behavior**
Selecting a file on the file-upload module doesn't return any file.

`event.files` is empty. 
originalEvent target files is also empty

**Expected behavior**
Have a list of selected files within `onSelect` event.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/prime-fileupload-bug-select-event?file=app%2Fapp.component.ts
* **PrimeNG version:** 5.2.4

* **Browser:** all

**Comment by zhongdeliu** [comment]
You do have the file information. However you have to directly access the file, analogue in the uploader handler.

![screen shot 2018-04-26 at 08 54 58](https://user-images.githubusercontent.com/1384870/39290391-b2597b8e-492f-11e8-902a-32172e68000c.png)

**Comment by blackholegalaxy** [comment]
Ok. sounds weird though since files appears as empt FileList on `event`.

**Comment by guanyuan** [comment]
@blackholegalaxy   I encountered the same issue. 
I'd like to do something after user select one file. However, onSelect callback returns nothing for me.

How do you deal with it? Do you have any other alternatives?

**Comment by blackholegalaxy** [comment]
The fact is the files are not displayed on console but can be used in the code. `event.files` is an actual file array... Weird console problem. So i used event.files as expected.

**Comment by hbsoftco** [comment]
I have same problem, it worked well in the previous version (5.2.0), but not working now (version 5.2.7).

**Comment by mim-narola** [comment]
I also have the same issue

**Comment by barocsi** [comment]
+1 why not fixing?

**Comment by p0rsche** [comment]
2k19 and the issue still exists - and event.files is 0-length FileList in both latest Firefox and Chrome. The code is as simple as `<p-fileUpload
                customUpload="true"
                multiple="false"
                mode="basic"
                chooseLabel="Upload"
                (uploadHandler)="onLineupsUpload($event)"
                (onSelect)="onLineupsSelect($event)"
            ></p-fileUpload>`
