### ISSUE TITLE
p-dialog Header ui issue

### ISSUE THREAD

**Issue by atruptoneatma** [primefaces/primeng#5630]
<p-dialog header="Title" [(visible)]="display">
    Content
</p-dialog>

<button type="text" (click)="showDialog()" pButton icon="fa-external-link-square" label="Show"></button>

![p-dialog issue](https://user-images.githubusercontent.com/5140324/39229125-0ed8c196-487f-11e8-8fab-b1fe5c5ab721.png)

**Comment by bpbhat77** [comment]
`<p-header> <div style="word-wrap: break-word;">sdfs sdfssdfssdfssdfssdfs- sdfs</div> </p-header>`

You can use word-wrap: break-word; CSS

**Comment by atruptoneatma** [comment]
Yes I used
**CSS**
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    width: 85%;
