### ISSUE TITLE
Change checkbox mode behavior in ListBox

### ISSUE THREAD

**Issue by Mynken** [primefaces/primeng#5638]
I'm submitting a...
```
[X ] bug report
[X ] feature request 
```
**Current behavior**
I am using pListBox Advanced with multiply flag, it "requires" to click exactly on the checkbox.
When I have some values selected and click on next value(on the text of this value or between checkbox and text) the ListBox value delete all previous values and have value only of the last element which I clicked.

**Expected behavior**
When click on "all" active zone for item => excpeted behavior is to add this item to ListBox, not to clear it and add last element.

**Minimal reproduction of the problem with instructions**

**Comment by Mynken** [comment]
1) How it now works:
https://ibb.co/fMUf1x
2) Expected behavior
https://ibb.co/cWxB8c

**Comment by POLAK93** [comment]
I have the same issue, it's annoying.
