### ISSUE TITLE
p-growl background always green

### ISSUE THREAD

**Issue by bbuehrer** [primefaces/primeng#5639]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**Current behavior**
With p-growl and south-street-theme the message-background is green with all severities!

**Comment by cagataycivici** [comment]
This is expected, free themes except Omega does not offer colors growl messages.

**Comment by bbuehrer** [comment]
With the MessagesModule the background color works, why not with the GrowlModule
<p-messages [(value)]="msgs"></p-messages>

**Comment by bbuehrer** [comment]
See issue #5141. I think this is the same problem.
