### ISSUE TITLE
Make the event optional in tabView.open()

### ISSUE THREAD

**Issue by alarive** [primefaces/primeng#564]
I would like to be able to use tabView.open() from my code without having to pass an event as a parameter.

So far I have been using the following workaround:
this.tabView.open({preventDefault: function() {}}, this.tabView.tabs[indexOfTabToOpen])

**Comment by sudheerj** [comment]
But what is the use of open() event callback without having event information.

**Comment by cagataycivici** [comment]
Done but I'd suggest using activeIndex property instead.
