### ISSUE TITLE
p-table with p-tableHeaderCheckbox, p-tableCheckbox and selectionMode="multiple" : checkbox is not clickable

### ISSUE THREAD

**Issue by Darnoj** [primefaces/primeng#5640]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

Stackblitz : https://stackblitz.com/edit/github-4vvqp4

**Current behavior**
I can select the line by clicking anywhere in the row **except** in the checkbox (a click in the checkbox have no effect)

**Expected behavior**
In order to select the line I can click anywhere in the row (**including** the checkbox)

**Minimal reproduction of the problem with instructions**
Use a p-table with p-tableHeaderCheckbox + p-tableCheckbox and selectionMode="multiple"
See Stackblitz : https://stackblitz.com/edit/github-4vvqp4

**What is the motivation / use case for changing the behavior?**
The p-tableHeaderCheckbox is interesting in order to select all rows which is not possible with only selectionMode="multiple".
The selectionMode="multiple" is also interesting in order to click anywhere in the row to make it selected (more user friendly).

* **Angular version:** 5.2.10

* **PrimeNG version:** 5.2.4

**Comment by Rachit-rkb** [comment]
Facing similar problem.

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/issues/6045
