### ISSUE TITLE
fullTemplateTypeCheck error with PrimeNG 5.2.3

### ISSUE THREAD

**Issue by Helayxa** [primefaces/primeng#5641]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When activating fullTemplateTypeCheck in tsconfig.json, it throws errors from PrimeNG code : 
ERROR in node_modules\primeng\components\datatable\datatable.d.ts.ColumnHeaders.html(7,17): : Property 'tabindex' does not exist on type 'ColumnHeaders'.
node_modules\primeng\components\datatable\datatable.d.ts.TableBody.html(38,103): : Expected 1 arguments, but got 2.
node_modules\primeng\components\datatable\datatable.d.ts.TableBody.html(40,103): : Expected 1 arguments, but got 2.
node_modules\primeng\components\multiselect\multiselect.d.ts.MultiSelect.html(45,43): : Property 'i' does not exist on type 'MultiSelect'.
node_modules\primeng\components\orderlist\orderlist.d.ts.OrderList.html(12,149): : Property 'disabled' does not exist on type 'OrderList'.
node_modules\primeng\components\orderlist\orderlist.d.ts.OrderList.html(17,162): : Expected 2 arguments, but got 1.
node_modules\primeng\components\orderlist\orderlist.d.ts.OrderList.html(26,152): : Expected 2 arguments, but got 1.
node_modules\primeng\components\tabview\tabview.d.ts.TabPanel.html(6,31): : Property 'columns' does not exist on type 'TabPanel'.
node_modules\primeng\components\megamenu\megamenu.d.ts.MegaMenu.html(18,178): : Property 'child' does not exist on type 'MegaMenu'.
node_modules\primeng\components\megamenu\megamenu.d.ts.MegaMenu.html(18,67): : Property 'child' does not exist on type 'MegaMenu'.
node_modules\primeng\components\megamenu\megamenu.d.ts.MegaMenu.html(18,154): : Property 'child' does not exist on type 'MegaMenu'.
node_modules\primeng\components\panelmenu\panelmenu.d.ts.PanelMenu.html(20,134): : Expected 0 arguments, but got 1.

**Expected behavior**
PrimeNg should compile with fullTemplateTypeCheck

**Comment by cagataycivici** [comment]
Always try the latest version before creating new issues please.
