### ISSUE TITLE
How to configure a TreeTable component properties (expandedIcon, collapsedIcon) for making them always visible.

### ISSUE THREAD

**Issue by bibidon** [primefaces/primeng#5644]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

**Current behavior**

If a node does not have a child his icon for an expand/collapse action disappear from a view.
![image](https://user-images.githubusercontent.com/6566786/39350033-a919aed2-4a05-11e8-8a73-b75d68e25430.png)

Now to have posibility for always show icons I use such a trick. I add empty class to the node with css properties:
```
:host >>> .empty a {
    visibility: visible !important; /*a toggle is always visible*/
}

:host >>> .empty ~ .ui-treetable-row {
    display: none !important; /*an empty node does not show*/
}
```

![image](https://user-images.githubusercontent.com/6566786/39350428-d4b0d54c-4a06-11e8-890c-757c8207555b.png)

**Expected behavior**
It will be nice to have a posibility to configure such behaiver.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.2.9

* **PrimeNG version:** 5.2.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Please try the new TreeTable of 6.0.0-alpha.2
