### ISSUE TITLE
Freeze the first column in treetable using position: sticky

### ISSUE THREAD

**Issue by potatolianyi** [primefaces/primeng#5647]
I appreciate if you can give me some help. Thanks.

**Current behavior**
Only the parent node of treetable data is sticky in the first column.

**Expected behavior**
All node of the first column should be frozen.

**What is the motivation / use case for changing the behavior?**
For large table, we want to make the first column always showing when scrolling.

**Comment by cagataycivici** [comment]
Please try the new TreeTable of 6.0.0-alpha.2
