### ISSUE TITLE
TurboTable Scroll cause with mismatch between header and columns

### ISSUE THREAD

**Issue by kombattriarii** [primefaces/primeng#5648]
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-rhgccx

**Current behavior**
scroll to the right notice the column widths are off. I have seen this with vertical scrolling  as well.

**Expected behavior**
column header and body widths should be the same and should always move together.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/github-rhgccx

**What is the motivation / use case for changing the behavior?**
data must scroll either vertically or horizontally. either case shows this issue.

**Please tell us about your environment:**
Win10, IIS

* **Angular version:** 
4.1.2

* **PrimeNG version:** 5.X
5.2.5

* **Browser:** 
chrome-lastest
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.2.2

* **Node (for AoT issues):** `node --version` =   
8.9.4

**Comment by JacobSiegle** [comment]
You need to set the width like the doc example.
