### ISSUE TITLE
terminal component not using line breaks \n

### ISSUE THREAD

**Issue by sdmoralesma** [primefaces/primeng#565]
Given a string like: `this is my text \nwith break \nlines`
terminal component is displaying it like: `this is my text with break lines`
but it should be: 
`this is my text` 
`with break`
`lines`

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.

**Comment by rmcdesign** [comment]
Can't get line breaks to work in the terminal response in the latest version 4.2.0

Is there a way to use \t and \n

**Comment by rmcdesign** [comment]
Adding white-space: pre-wrap; in CSS fixes it
