### ISSUE TITLE
Fileupload click on choose button icon doesn't trigger file select

### ISSUE THREAD

**Issue by blackholegalaxy** [primefaces/primeng#5652]
**I'm submitting a ...**
```
[x] bug report
```

**Stackblitz Case (Bug Reports)**
https://stackblitz.com/edit/prime-fileupload-bug-select-event?file=app%2Fapp.component.html

**Current behavior**

On file upload, clicking on `plus` icon on choose button doesn't actually trigger the file selector. It just do nothing. Clicking on the label works.

Sorry on my demo font-awesiome icons doesn't render correctly. But behavior still can be reproduced. Just click on square if icon is not rendered.

<img width="309" alt="screen shot 2018-04-27 at 10 02 53 pm" src="https://user-images.githubusercontent.com/11064123/39390718-c901f89c-4a66-11e8-869b-05c068f4bed8.png">

**Expected behavior**
Clicking anywhere on the button, icon included, should trigger the file selector to appear.

**Minimal reproduction of the problem with instructions**
Just use fileupload module.

* **Angular version:** 5.2
* **PrimeNG version:** 5.2.5
* **Browser:** chrome and all other tested

**Comment by thizzo** [comment]
+1 
same

**Comment by yigitfindikli** [comment]
You need to add the primeicons configuration.  You can look here https://www.primefaces.org/primeng/#/setup.

**Comment by J2BB** [comment]
It would be great to unclosed this issue and to resolve it ! 
The problem is quite urgent, this type of browse button is often use with advanced mode (compared to basic button).

Can a PrimeNg staff member tell us more about the date of the next release including this fix ?

Thanks ;)

**Comment by guardiannite** [comment]
I took @J2BB recommendation of applying CSS, and noticed my cursor wasn't a 'pointer' when I hovered over the _choose_ button.

So I also added this css:

```
::-webkit-file-upload-button {
  cursor: pointer;
}
```

https://stackoverflow.com/questions/7554845/the-cursorpointer-property-doesnt-apply-to-file-upload-buttons-in-webkit-brows

**Comment by J2BB** [comment]
Oh great !! It works perfectly ! Thank you @guardiannite ;)
