### ISSUE TITLE
Scrollbar get out of content

### ISSUE THREAD

**Issue by DmitryZevalev** [primefaces/primeng#5653]
When ScrollPanel contents large number of items. Scrollbar get out of content

**Comment by fabioscala** [comment]
Having the same issue. Would be glad if someone could help me work-around this for the time being.
Some debug info for you guys maybe (fully scrolled down, scrollbar handle goes out of content).

```
content.scrollTop / content.scrollHeight * 100
> 93.44532279314888
content.scrollTop 
> 5674
content.scrollHeight
> 6072
```

![image](https://user-images.githubusercontent.com/1829697/50382156-e1f05180-06d3-11e9-8447-056a2909cdd3.png)
