### ISSUE TITLE
PrimeNG growl overlapping components

### ISSUE THREAD

**Issue by anmoljainatcs** [primefaces/primeng#5655]
**I'm submitting a** ... (check one with "x")

[x] bug report => Search github for a similar issue or PR before submitting

**Current behavior**
PrimeNG growl overlapping components
I have an p-table in my application page with single row selection.
Table is right aligned. But when I do mouse over on the last two columns then the row highlighting as well as onRowSelect does not work.
It looks some issue with z-index of growl component.
Please help in fixing this. I have tried multiple values of z-index for p-table ans g-growl, but not able to fix it.

**Comment by bpbhat77** [comment]
Can you post screenshot or code snippet here?

**Comment by anmoljainatcs** [comment]
Hi Prashanth,
Please see the screenshot. The problem is in the shaded area of growl. This shaded area is overlapping the table component and any other component that is coming under.
![image](https://user-images.githubusercontent.com/22437704/39410333-d9b5a85a-4c14-11e8-838a-59eac0c3f9b0.png)

**Comment by anmoljainatcs** [comment]
Closing this issue. I resolved it myself. It was a simple html construction issue which I overlooked.
