### ISSUE TITLE
DropDown scrollHeight - any value leads to very long scroll section

### ISSUE THREAD

**Issue by gatapia** [primefaces/primeng#566]
In beta 9 - If you specify the scrollHeight on a p-dropdown then the viewport becomes very large, basically ignoring the scrollHeight value.

**Comment by gatapia** [comment]
In beta 11, scrollHeight is just ignored.  The generates html is always 200px

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with them and if issue persists drop a comment and we'll reopen.

**Comment by oscarlagatta** [comment]
Still this seems to be an issue with "primeng": "^5.2.0". Can you please confirm?
