### ISSUE TITLE
On p-sidebar component, you cannot block the closing of sidebar on some condition (when clicking X or when clicking the layer)

### ISSUE THREAD

**Issue by sTheCoder** [primefaces/primeng#5665]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
On p-sidebar component, you cannot block the closing of sidebar on some condition (either by clicking x or by clicking the layer). If for example the user is working on a form displayed on the sidebar and accidentally clicks the modal layer, the sidebar closes immediately and the work in progress is lost.

**Expected Behaviour**
There has to be a way to catch the closing event, and maybe block it on some condition. Or simply adding a property to block any kind of automatic closing of the sidebar.

**Comment by cagataycivici** [comment]
There is showCloseIcon in 6.0.1.
