### ISSUE TITLE
InputText no longer underlined in red on error in Ultima 5.2.2

### ISSUE THREAD

**Issue by kc13greiner** [primefaces/primeng#5666]
**I'm submitting a ...** 
```
[ X] bug report
```

**Current behavior**
In previous versions of Ultima when using the md-inputfield class for an input, the input would underline in red if it was in an error state, since Ultima 5.2.2 the label and error messages still turn red, but the line remains blue/gray.

**Expected behavior**
Underline should be red

* **Ultima version:** 5.2.2
<img width="500" alt="ultima_5 2 2" src="https://user-images.githubusercontent.com/21210601/39526756-c615360a-4ded-11e8-8782-90d203f7cb24.png">
<img width="503" alt="ultima_pre_5 2 2" src="https://user-images.githubusercontent.com/21210601/39526757-c6286f2c-4ded-11e8-94a5-f21fc8e83214.png">

**Comment by cagataycivici** [comment]
Use Ultima forum to report issues please, note the PrimeNG issue tracker.
