### ISSUE TITLE
Pagination buttons don't react  for DataView component

### ISSUE THREAD

**Issue by alexsintoni** [primefaces/primeng#5667]
I'm submitting a
```
[ x] bug report
[ x] feature request
[ ] support request
```

**Current behavior**
I am using the new [DataView](https://www.primefaces.org/primeng/#/dataview) compent with the following setting:
```
<p-dataView #dv
        paginatorPosition="both"
        filterBy="name"
        [value]="peopleList"
        [paginator]="true"
        [rows]="5"
        [sortField]="sortField" [sortOrder]="sortOrder">
</p-dataView>
```

Where ```peopleList``` is a an array of class Person which is inizialized inside the ```ngOnInit()``` method of my Angular component.

I give also the possibility to add a new person using an external button.
My final HTML template is somthing like:

```
<div class="row">
    <div class="col">
        <button type="button"
                      class="btn btn-success btn-semi-round btn-add-elements"
                      (click)="addIPerson()">
                         Add Service
        </button>
    </div>
</div>

<div class="row">
    <div class="col">
        <p-dataView #dv
                    paginatorPosition="both"
                    filterBy="name"
                    [value]="peopleList"
                    [paginator]="true"
                    [rows]="5"
                    [sortField]="sortField" [sortOrder]="sortOrder">
        </p-dataView>
    </div>
</div>
```

Inside the ```addIPerson()``` I simply show a popup with a form to add some imformation of a new Person and once the user submits such form, the new element Person is added to the array ```peopleList```.

In case at the inizialization the array ```peopleList``` as exactly 5 elements, everything is fine and the [Dataview](https://www.primefaces.org/primeng/#/dataview) compent shows such list perfectly.
The pagination buttons are disabled because ```peopleList.length === [rows]="5"```. So the number of element of the ```peopleList``` is equal to the number of element to be shown for each page in ```<p-dataView ... [rows]="5" ...></p-dataView>```.

The issue comes when I add a new Person to the ```peopleList``` and ```peopleList.length===6```.
Unfortunately, the pagination buttons remain disabled.

If I use the ```filterBy="name"``` feature of the DataView and I look for the new Person.name, I can find it which means that ```<p-dataView ... ></p-dataView>``` is able to see the updated ```peopleList``` array with the new element.

The funny thing is that when I clean the filter input text, then the pagination buttons are enabled and I can switch to the second page and see in the list the new Person.

To me, it seems that the pagination buttons don't react with the new imput
```
<p-dataView #dv
        ...
        [value]="peopleList"
        ...>
</p-dataView>
```

Would be possible to refresh them as well and make dynamically enabled?

**Expected behavior**
I would expect that the pagination buttons react with the change of the input list as the filter.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Operating system: Ubuntu, Windows
IDE: IntelliJ
package manager: yarn

* **Angular version:** 5.1.0

* **PrimeNG version:** 5.2.5

* **Browser:** all

**Comment by alexsintoni** [comment]
I have fix it

**Comment by gbrcmg** [comment]
How did you do ?!

**Comment by alexsintoni** [comment]
Well, the solution was much easier than I thought.

Inside the method "addIPerson()", after I save the changes in the backend, I simply do:
```
this.peopleList.push(newPerson);
this.peopleList = JSON.parse(JSON.stringify(this.peopleList));
```
The second statement triggers the update of the "p-dataView" component.

**Comment by gbrcmg** [comment]
man, this made work! you have a beer on me! 👏

**Comment by alexsintoni** [comment]
@centigaurav sorry man, but what do you mean with header sticky?

**Comment by centigaurav** [comment]
Like to freeze the header so that when the dataview items are scrolled the header section remain in tact 
its like excel freeze top row type I was thinking
