### ISSUE TITLE
Feature Request - enable index on the new DataView

### ISSUE THREAD

**Issue by anuragd7** [primefaces/primeng#5668]
**I'm submitting a ...**  (check one with "x")
```
[ X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
```
**Current behavior**
I am displaying a list using the new DataView. I am trying to access the index of the item being displayed like so
```
<p-dataView [value]="items" [paginator]="true" [rows]="20">
        <p-header>My List</p-header>
        <ng-template let-item let-i="index" pTemplate="listItem">
            <div>
                <childA *ngIf="item.type === 'typeA' " [item]="item" [index]="i"></childA>
                <childB *ngIf="item.type === 'typeB' " [item]="item" [index]="i"></childB>
        </ng-template>
    </p-dataView>
```
I expect to be able to access the the index i of each item as before in the dataList. However this does not work with the new dataView.

**Comment by egedarcin** [comment]
This is already a feature.
If you check the demo and change the code below like this, you can access and display the index.
```
<ng-template let-car pTemplate="listItem" let-i="rowIndex">
....
<h1>   
  {{i}}
</h1>

**Comment by sarikafiorano** [comment]
When paginator is used, rowIndex starts with "0" again for every page instead of index of the object in array. Say array has 4 elements and each page contains 2 elements.
`
   <ng-template let-car pTemplate="listItem" let-i="rowIndex">
      <h1>   
         {{i}}
     </h1>`

the above code results in 0,1 and 0,1 on pagination instead of 0,1,2,3

**Comment by madhav5589** [comment]
@cagataycivici Any update on this? As @sarikaK945 mentioned, this added feature has a bug when dataview is used with pagination.

**Comment by majid701** [comment]
@sarikaK945 @madhav5589 I found a workaround for this if you want the index of the current item you can use the `first` property on the dataView which represents the index of the first element shown in the current page to calculate the index of the current item. Just add up `rowIndex` to `dataView.first`.
Here is an example:

```
<p-dataView #dataView [value]="cars">
    <ng-template let-car let-index="rowIndex" pTemplate="gridItem">
        <div class="col-12 md:col-3" (onClick)="clickedOnItemWithIndex(dataView.first + index)">
            {{car.year}}
        </div>
    </ng-template>
</p-dataView>
```
