### ISSUE TITLE
DropDown broken in beta9 - cannot select item

### ISSUE THREAD

**Issue by gatapia** [primefaces/primeng#567]
The viewport opens but mouse click is ignored on the items of the list.

I am using Modena theme.

You can still select dropdown items using keyboard, i.e. use down arrow once the viewport is shown

**Comment by cagataycivici** [comment]
Can you replicate at live showcase?

**Comment by gatapia** [comment]
I assume this is the showcase:
http://www.primefaces.org/modena-primeng/#/forms

If so, then no it seems to work there.  Perhaps my upgrade to beta9 went wrong.  I'll investigate.

**Comment by gatapia** [comment]
Ouch, this one was nasty.  For reference:

Using the following template:
`
<p-dropdown options="options()></p-dropdown
`

This component method works:
```
opts = [{label: '1', value: '1'}];
options() { return this.opts; }
```

This does not:
`
options() { return [{label: '1', value: '1'}]; }
`

I assume its becuase the second is actually returning a new array on every request.  So just memoize the return value and all is ok.

I think I've been bitten by this in the past and it still took me hours to find.  Don't think its you guys but rather an NG2 issue so closing for now, however if you can work around this crazyness it would make it good for your users.
