### ISSUE TITLE
Charts do not update

### ISSUE THREAD

**Issue by Perezmarc** [primefaces/primeng#568]
I'm trying to update a chart, but not working just changing the values, and calling the function update fails since I don't know wha'ts the Chart.js instance:

```
//Template
<ul class="dropdown-menu" role="menu" aria-labelledby="simple-btn-keyboard-nav">
                                <li *ngFor="let item of volumeSalesFilter" role="menuitem"><a class="dropdown-item" (click)="volumesSalesFilterClicked(item, chartVolumeSales)">{{item.label}}</a></li>
                            </ul>
<p-chart type="line" height="50" [data]="volumeSalesData"  [options]="volumeSalesOptions" #chartVolumeSales></p-chart>

//Component
volumesSalesFilterClicked(item: SelectItem, chart:any) {
        this.volumeSalesData.labels = this.filterLabels[item.value];
        this.volumeSalesData.datasets[0].data = this.lineChartLabels;
        chart.reset();
        console.log(this.volumeSalesData.labels);
        console.log(this.volumeSalesData.datasets[0].data);
        this.volumeSalesFilterSelected = item.label;
    }
```

**Comment by Perezmarc** [comment]
@MarcelCremer ?

**Comment by Faigjaz** [comment]
+1 I really need this to be fixed.

**Comment by Faigjaz** [comment]
Any comment on this would be awesome!

**Comment by Perezmarc** [comment]
I haven't looked at it as deep as you have... Great job, maybe the developers can find out the solution easier...

**Comment by MStoehr** [comment]
Has anyone tried this with the latest Versions of Angular2? Does change detection work the way I described in the previous posts?

**Comment by pcafstockf** [comment]
@cagataycivici 
Really happy to see this going into RC5.  Thank you!   
It would be great if it also detected changes in the options, not just the dataset.
My old solution (prior to using primeng) was just to call chart.update()

**Comment by albertosramires** [comment]
@cagataycivici Has this been fixed? I'm dynamically pushing into the datasets array but the chart doesn't seem to update. I'm using RC7.

**Comment by MStoehr** [comment]
@albertosramires Yesterday I wanted to write that it indeed does work, but today it just stopped. I didn't actually change anything. I uninstalled/reinstalled primeng and tried it with chartjs@2.3.0 as well, but it seems to be defect again. I don't know what happened.

**Comment by albertosramires** [comment]
Thanks @MStoehr, just to clarify, you mean that pushing into the datasets work? How are you changing the datasets?

**Comment by MStoehr** [comment]
@albertosramires  I perform .pop() and .slice() on my datasets.data, not the datasets array itself. I am sorry, I missread you there.  You are right, pushing a completely new dataset into the datasets arrays doesnt work for me as well.
Have you tried other methods like pop, slice, shift?

**Comment by albertosramires** [comment]
@MStoehr Thanks for the update, but I don't think it'll be necessary after all. In case you want to update primeng to the latest (out of RC) here's how you can update the charts. Declare a ref in your chart component `<p-chart #chart type="bar" [data]="chartData" [options]="chartOptions"></p-chart>`,  then in your component import UIChart `import { UIChart } from "primeng/components/chart/chart";`, get the view ref (change "chart" to the name of your reference) `@ViewChild("chart") chart: UIChart;` and call `chart.refresh()` after changing your datasets.

**Comment by MStoehr** [comment]
@albertosramires That doesn't work for me. My charts are within different childcomponents, while my data gets updated in their parent. But it seems as if using the @ViewChild doesn't work here, it returns undefined.

**Comment by albertosramires** [comment]
@MStoehr Have you tried something like [this](http://stackoverflow.com/questions/40458191/angular-2-accessing-child-view)?

**Comment by MStoehr** [comment]
I did, but I can't get it to work. But thanks for your help!

**Comment by seanareed** [comment]
Similar issue:

Calling `chart.refresh()` from a separate, "manual" button function updates the chart immediately for me.

But calling it after changing the value of `datasets[0].data` within a `.subscribe()` block doesn't. Triggering the function with the `.subscribe()` block twice does update the chart the second time, though.

Am I missing an initialization step somewhere? 

```
export class GraphTest implements OnInit {
    @ViewChild("chart") chart: UIChart
    graphData: any;
	
    constructor(dataservice: DataService) {}
	
    ngOnInit (): void {
        this.graphData = {
            labels: ['a', 'b', 'c', 'd', 'e'],
            datasets: [{label: 'Label', data: [1, 2, 3, 4, 5]}]
        };
    }
	
    // This updates the chart immediately on button press
    update (chart: UIChart): void {
        this.graphData.datasets[0].data = [6, 7, 8, 9, 10];
        chart.refresh();
    }
	
    // I have to press this button twice for the chart to update
    getRemote (datsetId: number, chart: UIChart): void {
        // HTTP request to get data from remote server
        this.dataservice.getData(datasetId)
            .subscribe(res => {
                this.graphData.datasets[0].data = res.data;
                chart.refresh();
             });
    }
}
```

```
<p-chart #chart type="line" [data]="graphData"></p-chart>
<button pButton type="button" label="Update" (click)="update(chart)"></button>
<button pButton type="button" label="Get Remote" (click)="getRemote(17, chart)"></button>
```

**Comment by albertosramires** [comment]
@seanareed Calling getRemote works every second click (fourth, sixth et cetera) or it only works after the second click (third, fourth and so forth)?

**Comment by seanareed** [comment]
@albertosramires Every second (4th, 6th etc).

**Comment by albertosramires** [comment]
@seanareed Just for testing purposes, try setting a timeout on chart.refresh() with a second or two delay.

**Comment by seanareed** [comment]
@albertosramires That did it. Even just a delay of 50ms made the difference. Thanks.
