### ISSUE TITLE
TreeTable's td elements has a border in Firefox

### ISSUE THREAD

**Issue by gabrielnemeth** [primefaces/primeng#5682]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
When you are clicking on a triangle icon of the TreeTable component in Firefox, a border appears on `td` elements.

**In Firefox:**
![border](https://user-images.githubusercontent.com/11211316/39615032-36de5402-4f74-11e8-9f8e-72740a34a069.jpg)

**In Chrome:**
![border-chrome](https://user-images.githubusercontent.com/11211316/39615090-7cdf07c6-4f74-11e8-8689-b608b8a512c9.jpg)

**Expected behavior**
There shouldn't be a border.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.X

* **PrimeNG version:** 5.X

* **Browser:** [ Firefox XX ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
TreeTable will be reimplemented and current is not maintained anymore.
