### ISSUE TITLE
Feature Request - 'appendTo' for MegaMenu submenus

### ISSUE THREAD

**Issue by CorporateDog** [primefaces/primeng#5688]
**I'm submitting a ...**  (check one with "x")
```
[X ] feature request
```

**Current behavior**
There doesn't currently appear to be a way to attach a MegaMenu's submenus to a different element or the HTML body. As a result, if a MegaMenu is inside a containing div with hidden overflow, the popup menus get cut off.

**Expected behavior**
As with other existing Menu components, we should be able to provide an 'appendTo' property which will parent the submenu overlays to  a different component.

**Comment by cagataycivici** [comment]
Nested menus do not support appendTo, you need to find an alternative solution on your end like removing overflow.
