### ISSUE TITLE
InputText / InputTextArea missing onFocus/onBlur methods

### ISSUE THREAD

**Issue by TekSiDoT** [primefaces/primeng#569]
These components should be able to trigger onFocus/onBlur.

**Comment by sudheerj** [comment]
You can use native DOM events such as focus and blur callbacks. What would be the advantage with custom events. If I miss anything then please reopen or comment out here.

**Comment by TekSiDoT** [comment]
This issue was opened a long time ago. If I'm not mistaken the input element is encapsulated inside the PrimeNG directive and does not relay these events to their parent components.

**Comment by lixaotec** [comment]
Textarea doesnt have blur access
