### ISSUE TITLE
p-panel toggle on header click

### ISSUE THREAD

**Issue by rashnk** [primefaces/primeng#5694]
How can i toggle p-panel on header click, now it toggle only when i click plus and minus icon

**Comment by rafa-as** [comment]
Same here!

**Comment by rafa-as** [comment]
@cagataycivici if you want I can do the PR, it's very easy, just use the following code:

On the template:

```html
(@panelContent.start)="onToggleStart($event)"
```

On the component:
```javascript
onToggleStart(event: Event) {
  this.animating = true;
  this.onBeforeToggle.emit({originalEvent: event, collapsed: this.collapsed});
}
```

**Comment by cagataycivici** [comment]
Added toggler property;

```xml
<p-panel toggler="icon | header"
```

Setting it to header gives you the required behavior.

**Comment by sridhark158** [comment]
.ui-panel .ui-panel-titlebar .ui-panel-titlebar-icon{
width:100% !important;
}

after that 

 span.pi-minus{
  float:right !important;
}
span.pi-plus{
  float:right !important;
}
this css trick will work
