### ISSUE TITLE
More options for Editor

### ISSUE THREAD

**Issue by dennyak47** [primefaces/primeng#5695]
there are many cases that would use options in quill, such as:
--------------------------------
var options = {
  debug: 'info',
  modules: {
    toolbar: '#toolbar'
  },
  placeholder: 'Compose an epic...',
  readOnly: true,
  theme: 'snow'
};
var editor = new Quill('#editor', options);
-----------------------------------------
but in p-editor, options is defined afterViewInited and cannot be modify afterwards.

**Comment by jarinwhite** [comment]
You might want to look into using [ngx-quill](https://github.com/KillerCodeMonkey/ngx-quill), which can take a config object.

**Comment by dennyak47** [comment]
Yes, ngx-quill is a solution. I can use it perfectly.

**Comment by marchino21** [comment]
Any updates on this one? I don't want to include another library and apply styles again.

**Comment by cagataycivici** [comment]
Added all available options to p-editor.
