### ISSUE TITLE
Calendar broken in 24hr mode between 0:00 - 1:00

### ISSUE THREAD

**Issue by ijager** [primefaces/primeng#5705]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
```
**Current behavior**

In 24-hour mode, when the time is between 00:00 - 01:00 (at night) it will change to 12:XX. 
This is caused by the last 'fix', see commit 3fcdc802d805023936d99c80c7d616c7d0ed1a3b. 

**Expected behavior**

00:00 - 01:00 are valid times.

* **Angular version:** 5.2.10

* **PrimeNG version:** 5.2.5

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript 2.6 | ES6/7 | ES5]

**Comment by ivan-meridianbanc-com** [comment]
https://github.com/primefaces/primeng/pull/5658
