### ISSUE TITLE
[Feature][Table] Expand filtering (MatchMode)

### ISSUE THREAD

**Issue by Mysame** [primefaces/primeng#5708]
**I'm submitting a ...**  (check one with "x")
```
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
```

Current table filtering is really only enough for users filtering strings / numbers.
I would love to see this expanded to facilitate Date. Currently, "equals" is the only one capable of handling Date, and that's through sheer luck.

Suggestions of additional MatchModes
- greaterThan(OrEquals)
- lesserThan(OrEquals)
- in (is value in list)
- range ([start, end], like Calendar using selectionMode="range")

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
