### ISSUE TITLE
Pagination broken on Table when using custom sorting

### ISSUE THREAD

**Issue by markgoho-EDT** [primefaces/primeng#5709]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Use custom sorting
Try to use pagination by clicking on a new page
Data doesn't change in table (i.e. new page doesn't show).

**Expected behavior**
Page should change to next portion of data

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 6.0.0

* **PrimeNG version:** 5.3.0

* **Browser:** Chrome

 
* **Language:** Typescript, compiling to es5

**Comment by markgoho-EDT** [comment]
Might have been a sort function error.

**Comment by Devendera** [comment]
I Want Sort Data On The Basis Of Checkbox Using Procedural In Php. PLease Provide Me Code For sorting data on click .
![candidates_list php](https://user-images.githubusercontent.com/39025510/39864763-531f14d2-5468-11e8-8d5f-85feabd351a0.png)
![candidates_list php](https://user-images.githubusercontent.com/39025510/39864778-633f3234-5468-11e8-9aa5-dadcb0507bd8.png)
