### ISSUE TITLE
Dropdown component is not sized correctly when passing an empty array to [options]

### ISSUE THREAD

**Issue by jpicklyk** [primefaces/primeng#571]
Env:
PrimeNG 1.0.0-beta.9
Angular2: 2.0.0-rc.4

I have built a cached data service using Observables backed by HTTP to a rest endpoint.  On component load I have found that an empty SelectItem array is initially passed to the dropdown component.  After a very short delay, the data is then pushed through my subscription and the dropdown options are available for selection.  I am finding that the following warning is displayed when the SelectItem array is empty:
WARNING: sanitizing HTML stripped some content (see http://g.co/ng/security#xss).

Also, the width of the dropdown is not adjusted properly to the updated data and is cut off.  It would seem that the dimensions are calculated off of the initial empty array and not fixed when the backing data is updated.

I have attempted to set the size according to the class ui-grid-col-8 but that appears to be ignored.

**Comment by jpicklyk** [comment]
I believe this might be corrected by the following pull request:
https://github.com/primefaces/primeng/pull/543

Please double check.

**Comment by cagataycivici** [comment]
This is fixed in recent PrimeNG release, please try with them and if issue persists drop a comment and we'll reopen.
