### ISSUE TITLE
highlight on even row conflicts with row selection highlight

### ISSUE THREAD

**Issue by dolphinsd** [primefaces/primeng#5710]
In datatable when row is selected and its even, the highlight is overriden

See result at https://gyazo.com/68018d59442ec49acdec35f0a21da544

for this row
<tr class="ui-datatable-even ui-state-highlight ui-widget-content ng-star-inserted" ng-reflect-ng-class="ui-datatable-even,,ui-state-hi" style="">

which should be highlighted

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
