### ISSUE TITLE
Time should be "23:59:59" in end date while Date Range Picker

### ISSUE THREAD

**Issue by MrPardeep** [primefaces/primeng#5715]
... To be more advanced on this - https://github.com/primefaces/primeng/pull/4095

Feature request: If the user selected "Date Range Picker" then at the time of "End date " time should be "23:59:59" instead of "00:00:00" in the timestamp.

Currently, for both start and end date, it will be "00:00:00"

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
