### ISSUE TITLE
p-schedule throws typeerror t is not a function

### ISSUE THREAD

**Issue by luisabreu** [primefaces/primeng#5717]
[X ] bug report

When building an angular 6.0 project that is using prineg 5.2.6+rxjs compat with the --prod flag, the p-scheduler throws an error during startup saying that:

main.8b05c1cfc2d81551d8f8.js:1 ERROR TypeError: t is not a function
    at scripts.c59900c530f9bd736bbf.js:1
    at p (scripts.c59900c530f9bd736bbf.js:1)
    at f (scripts.c59900c530f9bd736bbf.js:1)
    at constructor.queryBoundingRect (scripts.c59900c530f9bd736bbf.js:1)
    at constructor.build (scripts.c59900c530f9bd736bbf.js:1)
    at function.e.constructor.updateSize (scripts.c59900c530f9bd736bbf.js:1)
    at scripts.c59900c530f9bd736bbf.js:1
    at constructor.iterChildren (scripts.c59900c530f9bd736bbf.js:1)
    at constructor.callChildren (scripts.c59900c530f9bd736bbf.js:1)
    at constructor.updateSize (scripts.c59900c530f9bd736bbf.js:1)

Btw, this happens when the schedule is used in a module that is lazy loaded. I'm assuming that the new compiler is being more agressive about removing "unused" references...
In practice, it does not render the time in the correct place, as can be seen in the following image

![image](https://user-images.githubusercontent.com/521086/39921630-8dfec650-5513-11e8-853c-42a2af4a900c.png)

**Comment by cagataycivici** [comment]
Unable to replicate, it works fine for me.

**Comment by luisabreu** [comment]
This bugs was also  mentioned here https://github.com/primefaces/primeng/issues/5724

the problem happens when you're using the control in a module  that is loaded lazily and only when it's buid in production mode

**Comment by hle09** [comment]
I've fixed this problem by **NOT** using the min version of moment.js and fullcalendar.js.
New scripts section in .angular-cli.json or angular.json depending on CLI version:
"scripts": [
"../node_modules/jquery/dist/**jquery.slim.js**",
"../node_modules/moment/**moment.js**",
"../node_modules/chart.js/dist/Chart.js",
"../node_modules/fullcalendar/dist/**fullcalendar.js**"
],

As opposed to the old one:
"scripts": [
"../node_modules/jquery/dist/**jquery.js**",
"../node_modules/moment/min/**moment.min.js**",
"../node_modules/chart.js/dist/Chart.js",
"../node_modules/fullcalendar/dist/**fullcalendar.min.js**"
],

Hope this helps.
