### ISSUE TITLE
Table filters do not reset on table.reset()

### ISSUE THREAD

**Issue by ChrisBadalucco** [primefaces/primeng#5719]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/github-cbada
**Current behavior**
Only the body of the table is reset on table.reset() while all filters remain stale.

**Expected behavior**
Reset all filters during table.reset()

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/github-cbada

1. enter filter criteria
2. click reset button

**What is the motivation / use case for changing the behavior?**
It doesn't make sense to keep stale filters if the data being displayed no longer matches.

* **Angular version:** 5.2.10

* **PrimeNG version:** 5.2.5

* **Browser:** all
 
* **Language:** all

**Comment by noamichael** [comment]
Just an FYI - if you need to get this working currently, you can modify the app to bind the filters to the component, and then reset those with the table. Example: https://stackblitz.com/edit/github-cbada-hjvus2

I wonder if we could implement this with a directive. For example, maybe we can have a `pTableFilter` directive that can be placed on any `ngModel` driven control which we can clear automatically when the table is reset. We may be able to scan the table using the `@ContentChildren` annotation.

**Comment by cagataycivici** [comment]
You have full control over the filter elements so one solution can be binding to value property;

```
<input *ngSwitchCase="'vin'" pInputText type="text" (input)="dt.filter($event.target.value, col.field, col.filterMatchMode)" [value]="dt.filters && dt.filters[col.field] ? dt.filters[col.field].value: ''">
```
