### ISSUE TITLE
P-Multiselect is removing previously selected values if select all is checked after search

### ISSUE THREAD

**Issue by venkatsub24** [primefaces/primeng#5722]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**

* Select any items from P-Multiselect

![image](https://user-images.githubusercontent.com/31303431/39981761-9304b700-576f-11e8-9650-cc615cd8e575.png)

* Type for search on Searchbar, it will show some results, Click on Select all.

![image](https://user-images.githubusercontent.com/31303431/39981801-bb129ee2-576f-11e8-9f69-de18ee675f0e.png)

In this case, I have previously selected two items, and now after my search result, I am selecting two more by selecting all. By doing so, it is replacing my old search values, and showing I have selected only two items. 

**Expected behavior**

Instead of two items, the dropdown should have four items as Selected. 

**Minimal reproduction of the problem with instructions**

This can be reproduced at https://www.primefaces.org/primeng/#/multiselect , from the basic example which is provided over there. 

**What is the motivation / use case for changing the behavior?**

Gives more flexibility to user for searching any values and select all of the matching items after the result. This will be helpful when dropdown is having more number of data. 

**Please tell us about your environment:**

* **Angular version:** 5.X
Angular: ^5.2.0

* **PrimeNG version:** 5.X
PrimeNG version: primeng-5.2.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by yigitfindikli** [comment]
Its fixed at latest PrimeNG version.

**Comment by yigitfindikli** [comment]
It will be fixed next release, sorry for the wrong info. You can track here https://github.com/primefaces/primeng/issues/7047

**Comment by bagariaankit** [comment]
Was this fixed?
I checked http://primefaces.org/primeng/#/multiselect and observed that its still breaking.

**Comment by taqi-cd** [comment]
Its still have the same issue

**Comment by taqi-cd** [comment]
> It will be fixed next release, sorry for the wrong info. You can track here #7047

Its been more than 1 year and it's not fixed
