### ISSUE TITLE
SplitButton with appendTo="body" not working in Ultima Theme

### ISSUE THREAD

**Issue by dbaines30** [primefaces/primeng#5723]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Using the Ultima 5.2.2 Template a p-splitbutton where the appendTo="body" is set the popup menu width is set to 100% which breaks the UI as this is too wide.

**Expected behavior**
p-splitbutton works in the standard PrimeNG framework where appendTo="body" is set.

**Minimal reproduction of the problem with instructions**
Install the sample Ultima application. On the FormsDemo component change the existing p-splitbutton to include the appendTo="body".

**What is the motivation / use case for changing the behavior?**
p-splitbutton is unusable in the theme

**Please tell us about your environment:**
Windows 10, , 

* **Angular version:** 5.X
Angular 5

* **PrimeNG version:** 5.X
PrimeNg/Ultima 5.2.0+

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome, IE11 and Edge

**Comment by cagataycivici** [comment]
Please use Ultima forum for Ultima related issues and our team will assist;

https://forum.primefaces.org/viewforum.php?f=45
