### ISSUE TITLE
Table column styling via colgroup is ignored

### ISSUE THREAD

**Issue by ChrisBadalucco** [primefaces/primeng#5725]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/github-cbada-3akzvj

**Current behavior**
Docs say to style table columns using `<colgroup>` however this does not work.

**Expected behavior**
Expect styling to be honored via colgroup definition. 

**Minimal reproduction of the problem with instructions**
Load stackblitz - https://stackblitz.com/edit/github-cbada-3akzvj

- Angular version: 5.2.10

- PrimeNG version: 5.2.5

- Browser: all

- Language: all

**Comment by zeatan** [comment]
I encountered same trouble.
It's perhaps because of `<tr>`  background-color style
(ref https://www.w3.org/TR/CSS21/tables.html#columns)

If want to fix by self, Set `<tr style="background-color: inherit">` (or transparent)
or Set color not to `<col>` but `<td>`

**Comment by cagataycivici** [comment]
It seems to be browser related not PrimeNG.
