### ISSUE TITLE
When using single selection on a tree if you don't setup two way binding, the selection is not made

### ISSUE THREAD

**Issue by JakeSummers** [primefaces/primeng#573]
Suppose that we use this: 

```
<p-tree 
    [value]="theData" 
    selectionMode="single"
    [(selection)]="selectedFile"
    ></p-tree>
```

When we click on one of the items in the tree, it will be highlighted (see image below).

Now suppose that we remove the two way binding: 

```
<p-tree 
    [value]="theData" 
    selectionMode="single"
    ></p-tree>
```

Now when we click on items in the tree the selected state is not highlighted.  

---

The behavior is demonstrated in the image below.  
- The first tree has no two way binding - the tree doesn't highlight nodes when they are selected - **This is a bug**
- The second tree has no two way binding but has multiple selection - the tree does highlight nodes when they are selected
- The third tree has two binding - the tree does highlight nodes when they are selected

![image](https://cloud.githubusercontent.com/assets/5657503/16635890/b33d8e08-43a2-11e6-9789-3523e10aa28d.png)

---

I have pushed an example of this behavior to here:

https://github.com/JakeSummers/primeng-quickstart/tree/treeSelectionBug/app

**Comment by cagataycivici** [comment]
Why do you need selection mode without selecting binding?

**Comment by JakeSummers** [comment]
You may decide to just update your internal state based on the following outputs: 

    @Output() onNodeSelect: EventEmitter<any> = new EventEmitter();
    @Output() onNodeUnselect: EventEmitter<any> = new EventEmitter();

I am not 100% sure that this should be supported behavior.  I am fine with you closing this issue without addressing it.  I mostly logged the issue as a _Should this work?_ excersise when picking up Angular2.

**Comment by cagataycivici** [comment]
Not sure, if more users demand it, we'll reconsider, please use it with a two-way binding.

**Comment by slyadams** [comment]
I've also encountered this problem. In general, I rarely do two-way data binding now, sticking to event driven, one-way data flows. Its not a problem to work around this by just sticking in an unused two-way binding, but its a bit 'ugly'.

**Comment by Alina131189** [comment]
I'm facing the issue again and the only option at the moment is to type with any or remove the two way binding. Is anyone else also again facing this issue in primeNGs tree?
