### ISSUE TITLE
Multiselect panel scrollbars in ie

### ISSUE THREAD

**Issue by Chazing** [primefaces/primeng#5734]
**I'm submitting a ...**  

[ x] bug report

**Stackblitz Case (Bug Reports)**

https://stackblitz.com/edit/github-rryjp8

**Current behavior**
when we have a long text in item in multiselect,
in ie 11 + there is horizontal scroll on the panel.

**Expected behavior**
the horizontal scroll wont appear

**Minimal reproduction of the problem with instructions**
Open the stackblizt example in internet explorer
open the multiselect  and see the horizontal scrollbars

**Please tell us about your environment:**
windows 7

* **Angular version:** 5.X
5.2

* **PrimeNG version:** 5.X
5.2.0

* **Browser:** 
IE 11 +

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
