### ISSUE TITLE
Feature request: make it compatible with Angular 6

### ISSUE THREAD

**Issue by rbatllet** [primefaces/primeng#5738]
Is there any possibility to have a new version compatible with Angular 6 in the near future, because now it returns errors related to RxJS:

```
ERROR in node_modules/rxjs/Subscription.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Subscription'.
node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.
node_modules/primeng/components/table/table.d.ts(8,10): error TS2305: Module '"/development/client/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
node_modules/primeng/components/table/table.d.ts(9,10): error TS2305: Module '"/development/client/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/primeng/components/common/messageservice.d.ts(1,10): error TS2305: Module '"/development/client/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/primeng/components/messages/messages.d.ts(4,10): error TS2305: Module '"/development/client/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
node_modules/primeng/components/growl/growl.d.ts(5,10): error TS2305: Module '"/development/client/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
node_modules/primeng/components/accordion/accordion.d.ts(4,10): error TS2305: Module '"/development/client/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
node_modules/primeng/components/common/treedragdropservice.d.ts(1,10): error TS2305: Module '"/development/client/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/primeng/components/common/confirmationservice.d.ts(1,10): error TS2305: Module '"/development/client/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/primeng/components/confirmdialog/confirmdialog.d.ts(5,10): error TS2305: Module '"/development/client/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
node_modules/primeng/components/datatable/datatable.d.ts(8,10): error TS2305: Module '"/development/client/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
node_modules/primeng/components/terminal/terminalservice.d.ts(1,10): error TS2305: Module '"/development/client/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/primeng/components/terminal/terminal.d.ts(4,10): error TS2305: Module '"/development/client/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
node_modules/primeng/components/tree/tree.d.ts(4,10): error TS2305: Module '"/development/client/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
node_modules/primeng/components/treetable/treetable.d.ts(4,10): error TS2305: Module '"/development/client/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
```

**Comment by PHuhn** [comment]
Please, ... I am having the same issue:
```
ERROR in node_modules/primeng/components/common/confirmationservice.d.ts(1,10): error TS2305: Module '"./ng/incident-mg/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/primeng/components/confirmdialog/confirmdialog.d.ts(5,10): error TS2305: Module '"./ng/incident-mg/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
node_modules/primeng/components/datatable/datatable.d.ts(8,10): error TS2305: Module '"./ng/incident-mg/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.
node_modules/rxjs/Subscription.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Subscription'.
```

**Comment by gtteamamxx** [comment]
How long do we have to wait for stable release with support of rxjs 6.0?

**Comment by rendy14s** [comment]
+1

**Comment by PHuhn** [comment]
Thanks ctrl-brk, rxjs-compat worked for me.

I have changed my small application from 5 to 6 and the changes are not trivial.

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/issues/5758

**Comment by chrisGH** [comment]
hello, sorry for the question but how i can add the rxjs-compat to the package.json? what part?

**Comment by ctrl-brk** [comment]
@chrisGH, to the "dependencies"

**Comment by chrisGH** [comment]
great just now i saw it on this page by extention of youtube, i just started with angular i develop a project of  the school of listcheck, apologize the molest but i have another question how do you do to dont lose the reference of a object by the id when you pass to other views when you run the app, somebody told me that with a @session but i dont know nothing about this

**Comment by gtteamamxx** [comment]
@chrisGH Read about localStorage and sessionStorage or navigating by data
i mean. eg. /todo?id=15

**Comment by PHuhn** [comment]
From the folder containing package.json:
```
    npm install --save-dev rxjs-compat
```
that will install rxjs comparability for the local project.

**Comment by apivaral** [comment]
+1

**Comment by palmurugan** [comment]
in node_modules/primeng/components/common/confirmationservice.d.ts(5,33): error TS1005: ';' expected

**Comment by SrikrushnaP** [comment]
ERROR in node_modules/primeng/components/common/messageservice.d.ts(5,28): error TS1005: ';' expected.

**Comment by abhishekp21** [comment]
I aslo Faced same issue today so I fixed by following commands

npm install primeng@^7.0.0-beta.1 --save 

in beta version this issue has been resolved.

**Comment by dilshad372** [comment]
npm install primeng@7.0.0-beta.1 --save

**Comment by SrikrushnaP** [comment]
> npm install primeng@7.0.0-beta.1 --save

Yes It resolved my problem. Thanks @dilshad

**Comment by eldho-mathew** [comment]
Getting the same error with version 7.1.0
`ERROR in node_modules/primeng/components/common/confirmationservice.d.ts(5,33): error TS1005: ';' expected.
node_modules/primeng/components/common/confirmationservice.d.ts(5,86): error TS1005: '(' expected.
node_modules/primeng/components/common/confirmationservice.d.ts(6,72): error TS1005: '(' expected.
node_modules/primeng/components/common/confirmationservice.d.ts(7,25): error TS1005: ',' expected.
node_modules/primeng/components/common/confirmationservice.d.ts(7,40): error TS1005: ';' expected.
node_modules/primeng/components/common/confirmationservice.d.ts(8,15): error TS1005: ';' expected.
node_modules/primeng/components/common/confirmationservice.d.ts(8,21): error TS1109: Expression expected.
node_modules/primeng/components/common/confirmationservice.d.ts(9,1): error TS1128: Declaration or statement expected.
node_modules/primeng/components/common/messageservice.d.ts(5,28): error TS1005: ';' expected.
node_modules/primeng/components/common/messageservice.d.ts(5,88): error TS1005: '(' expected.
node_modules/primeng/components/common/messageservice.d.ts(6,73): error TS1005: '(' expected.
node_modules/primeng/components/common/messageservice.d.ts(7,16): error TS1005: ',' expected.
node_modules/primeng/components/common/messageservice.d.ts(7,26): error TS1005: ';' expected.
node_modules/primeng/components/common/messageservice.d.ts(7,32): error TS1109: Expression expected.
node_modules/primeng/components/common/messageservice.d.ts(8,20): error TS1005: ',' expected.
node_modules/primeng/components/common/messageservice.d.ts(8,32): error TS1005: ';' expected.
node_modules/primeng/components/common/messageservice.d.ts(8,38): error TS1109: Expression expected.
node_modules/primeng/components/common/messageservice.d.ts(9,15): error TS1109: Expression expected.
node_modules/primeng/components/common/messageservice.d.ts(9,24): error TS1005: ';' expected.
node_modules/primeng/components/common/messageservice.d.ts(9,30): error TS1109: Expression expected.
node_modules/primeng/components/common/messageservice.d.ts(10,1): error TS1128: Declaration or statement expected.
node_modules/primeng/components/common/treedragdropservice.d.ts(5,23): error TS1005: ';' expected.
node_modules/primeng/components/common/treedragdropservice.d.ts(5,81): error TS1005: '(' expected.
node_modules/primeng/components/common/treedragdropservice.d.ts(6,80): error TS1005: '(' expected.
node_modules/primeng/components/common/treedragdropservice.d.ts(7,20): error TS1005: ',' expected.
node_modules/primeng/components/common/treedragdropservice.d.ts(7,40): error TS1005: ';' expected.
node_modules/primeng/components/common/treedragdropservice.d.ts(7,46): error TS1109: Expression expected.
node_modules/primeng/components/common/treedragdropservice.d.ts(8,19): error TS1005: ',' expected.
node_modules/primeng/components/common/treedragdropservice.d.ts(8,39): error TS1005: ';' expected.
node_modules/primeng/components/common/treedragdropservice.d.ts(8,45): error TS1109: Expression expected.
node_modules/primeng/components/common/treedragdropservice.d.ts(9,1): error TS1128: Declaration or statement expected.`
