### ISSUE TITLE
terminal component doesn't let to copy the output

### ISSUE THREAD

**Issue by sdmoralesma** [primefaces/primeng#574]
If I'm using the terminal component, and send a comand:
`prompt $ my-command`

and the output is for example:
`Unknown command: sdfasf`

If you try to select that text with the mouse it will impossible because as soon as you release the click button the selected part is not unselected.

Note: In the showcase you can replicate the behavior: http://www.primefaces.org/primeng/#/terminal
Note2: The bug is also present in the primeUI terminal: http://www.primefaces.org/primeui/#terminal

**Comment by cagataycivici** [comment]
Unable to replicate.
