### ISSUE TITLE
[Calendar] Input displays wrong time

### ISSUE THREAD

**Issue by fhaubold** [primefaces/primeng#5740]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
I have a calendar with 24 hour time activated. Whenever I choose 00:00 in the timepicker, the input field displays 12:00. See image attached.

**Expected behavior**
The input field should display either 00:00 (preferred) or 24:00, but not 12:00

**Please tell us about your environment:**
MacOS 10.13.4, tested with Safari, Chrome and Firefox

* **Angular version:** 6.0.0

* **PrimeNG version:** 5.2.6

* **Node (for AoT issues):** `node --version` =   v10.1.0

![bildschirmfoto 2018-05-15 um 22 07 37](https://user-images.githubusercontent.com/16214076/40081434-418de034-588e-11e8-8ae4-80ec8d37e347.png)

**Comment by Mysame** [comment]
Confirmed in my project, pretty big oversight.
