### ISSUE TITLE
p-calendar style

### ISSUE THREAD

**Issue by DaoFof** [primefaces/primeng#5742]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
I followed the tutorial on web site [https://www.primefaces.org/primeng/#/calendar](prime calendar) before that I applied the get started.
 When I run the app I am getting the error 

> **localhost/:1 Refused to apply style from 'http://localhost:4200/node_modules/primeng/resources/themes/omega/theme.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
localhost/:1 Refused to apply style from 'http://localhost:4200/node_modules/primeng/resources/primeng.min.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.**
Here is the index.html 
![capture](https://user-images.githubusercontent.com/26028753/40098678-5e26898c-58fa-11e8-8c28-fd03ee8784f2.JPG)

 And the style is not applying
![capture](https://user-images.githubusercontent.com/26028753/40098617-06d24b9e-58fa-11e8-9e87-ebda29ad3735.JPG)

**Expected behavior**
It should be like : 
![capture](https://user-images.githubusercontent.com/26028753/40098648-2862bb0e-58fa-11e8-8aba-29b38791c48d.JPG)

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.X

* **PrimeNG version:** 5.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DaoFof** [comment]
It was about styles in angular-cli.json, When adding the style there, I should re build the app to see effect, that I had forgotten 
![capture](https://user-images.githubusercontent.com/26028753/40099034-e0d41dc6-58fb-11e8-8a6b-ce131c3d6208.JPG)

**Comment by syedsaadqamar** [comment]
![image](https://user-images.githubusercontent.com/38069997/85559206-f1db4f80-b642-11ea-8e39-2ead6d500803.png)

I was facing that style issue on a small screen.
I have fixed it by giving the style
HTML:
`
<div class="main-container">
  <p-calendar showTime="true" [(ngModel)]="date" [showIcon]="true"></p-calendar>
</div>
`
CSS:
`.main-container ::ng-deep p-calendar .ui-datepicker {
  width: auto !important;
}`

![image](https://user-images.githubusercontent.com/38069997/85559935-9d849f80-b643-11ea-83ee-039992323a13.png)
