### ISSUE TITLE
Documentation per version

### ISSUE THREAD

**Issue by merlosy** [primefaces/primeng#5745]
Hi,
That would be great to be able to switch released version from the documentation website:
https://www.primefaces.org/primeng/#/

.. the same way you can do it with angular: https://angular.io/docs

I need to look into an old code using 2.0.0, and i'm really having a bad time digging into the code..

Thanks

**Comment by cagataycivici** [comment]
I'm afraid only way to retrieve docs for older versions is, running the docs from the tag. You need to clone and run it;

https://github.com/primefaces/primeng/tree/2.0.6
