### ISSUE TITLE
Accept multiple different date formats as input in p-calendar

### ISSUE THREAD

**Issue by orsolli** [primefaces/primeng#5746]
**I'm submitting a ...**
```
[ ] bug report
[x] feature request
[ ] support request
```

**Current behavior**
The input date must be written in the same format as the output format

**Expected behavior**
The input date can be written in any of the given formats and will be parsed to the first format that fits

**What is the motivation / use case for changing the behavior?**
The project I'm working on have a userbase that love to use the keyboard to fill out forms quickly, but also whant a readable date field. To meet the demand, a field that accepts a short date from user and displays a long readable date is needed.

* **Angular version:** 5.2.10

* **PrimeNG version:** 5.2.7

**Comment by cagataycivici** [comment]
If more users will demand it, we'll reconsider.

**Comment by dhughes-reward** [comment]
Another user requesting here. This is just good UX.

**Comment by randdusing** [comment]
This would help a lot. I may want to display a date as 01-Jan-2019 but want to store it as 2019-01-01.

**Comment by dydFreeman** [comment]
Same here, it would be a really usefull feature.

**Comment by MobackChetanKumar** [comment]
Is there any way we can use range date selection in <p-calendar> (PrimeNG) something like 01/08/2019 to 02/08/2019?

**Comment by Janine65** [comment]
What about this CR? Did nothing happen sinse so many years, but we need this :-(
