### ISSUE TITLE
Height in p-chart is not applied if the responsive parameter is true

### ISSUE THREAD

**Issue by fernandocode** [primefaces/primeng#5748]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/angular-zahjdv

**Current behavior**
If the responsive parameter is true (or default), the "height" property is not applied to the chart, and the default value 150 is applied. This also applies to "width".

**Expected behavior**
When you enter a value for height or width, it is expected to be applied to the component.
And in addition the only way to apply it, is putting "responsive" as false, which ends up causing the other property can not continue working responsively.

**Minimal reproduction of the problem with instructions**
Follow the comments in the example:
https://stackblitz.com/edit/angular-zahjdv
 
**If they find this correction to be valid, I can send a PR.**

**Comment by Danieleeee** [comment]
There are 5 releases that I report the problem of the height of the graphs and is always ignored
