### ISSUE TITLE
Add onMapDrag, onMapDragStart, onMapDragEnd, onCenterChange event handlers to Gmap

### ISSUE THREAD

**Issue by imichelakos** [primefaces/primeng#575]
Please include these important event handlers to next milestone.

**Comment by garethlewis** [comment]
Why don't you just use a viewchild for GMap and then add  the listeners yourself?

**Comment by garethlewis** [comment]
```
this.gmap.map.addListener("dragend", function() {
            console.log("dragend called");
        });
```

**Comment by imichelakos** [comment]
Thank you vary much for your answer....i will check it out soon

**Comment by yigitfindikli** [comment]
We'll reconsider if there is more community feedback on this. Thank you for your report.
