### ISSUE TITLE
 p-table (turbo table) frozenColumns + resize not working

### ISSUE THREAD

**Issue by siddhartha161** [primefaces/primeng#5751]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
throwing error 
Uncaught TypeError: Cannot read property 'nextElementSibling' of undefined

**Expected behavior**
resizableColumns should work with frozen coloumns

**Minimal reproduction of the problem with instructions**
use frozenColumns , resizableColumns = true

* **Angular version:** 5.2.6

* **PrimeNG version:** 5.2.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [TypeScript 2.4.2 ]

* **Node (for AoT issues):** `node --version` =   8.11.1

**Comment by amedvedsy** [comment]
https://github.com/primefaces/primeng/issues/5782
