### ISSUE TITLE
Add custom label for progressBar

### ISSUE THREAD

**Issue by danielinki** [primefaces/primeng#5753]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
I cannot change the decimal separator from dot into comma. Need a custom label property for it, because not every locale use dot as separator

**Expected behavior**
have custom label property for progressBar

**Please tell us about your environment:**
os: darwin x64

* **Angular version:** 5.X
5.2.8

* **PrimeNG version:** 5.X
5.2.6

* **Browser:**
all
 
* **Language:** 
all

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by hreimer** [comment]
I checked the documentation, this feature is not yet implemented, but it would be very useful. My usecase is: I want to display the available percentage, but use a different label (e.g. 1/6 should be visible, but 16% should be the value used for the width of the progress)
