### ISSUE TITLE
Sidebar property for close button

### ISSUE THREAD

**Issue by codetinker** [primefaces/primeng#5757]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Sidebar is nice to have especially when combining with full screen which give extra method to display content faster or easier to manipulate. 

But in some cases where I need to full screen content to be taken action before i can show other content. Currently close button is automatically visible. It would be great it you can add **closeButton property for sidebar** to control visibility of close button.

Thank you!

**Comment by cagataycivici** [comment]
Available already.
