### ISSUE TITLE
Unexpected value 'ChartModule' imported by the module 'e'. Please add a @NgModule annotation.

### ISSUE THREAD

**Issue by KobernykYura** [primefaces/primeng#5759]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
"dependencies": {
    "@angular/animations": "^6.0.1",
    "@angular/cdk": "^6.0.2",
    "@angular/cli": "^6.0.1",
    "@angular/common": "^6.0.1",
    "@angular/compiler": "^6.0.1",
    "@angular/compiler-cli": "^6.0.1",
    "@angular/core": "^6.0.1",
    "@angular/forms": "^6.0.1",
    "@angular/http": "^6.0.1",
    "@angular/material": "^6.0.2",
    "@angular/platform-browser": "^6.0.1",
    "@angular/platform-browser-dynamic": "^6.0.1",
    "@angular/platform-server": "^6.0.1",
    "@angular/router": "^6.0.1",
    "@auth0/angular-jwt": "^2.0.0",
    "@types/webpack-env": "1.13.6",
    "ajv": "^6.5.0",
    "angular-font-awesome": "^3.1.2",
    "angular2-template-loader": "0.6.2",
    "aspnet-prerendering": "^3.0.1",
    "aspnet-webpack": "^2.0.3",
    "awesome-typescript-loader": "^5.0.0",
    "bootstrap": "4.1.1",
    "chart.js": "^2.7.2",
    "css": "2.2.3",
    "css-loader": "0.28.11",
    "es6-shim": "0.35.3",
    "event-source-polyfill": "0.0.12",
    "expose-loader": "0.7.5",
    "extract-text-webpack-plugin": "^3.0.2",
    "file-loader": "1.1.11",
    "font-awesome": "^4.7.0",
    "html-loader": "0.5.5",
    "isomorphic-fetch": "2.2.1",
    "jquery": "3.3.1",
    "json-loader": "0.5.7",
    "ngx-toastr": "^8.6.0",
    "popper.js": "^1.14.3",
    "preboot": "^6.0.0-beta.4",
    "primeng": "^5.2.7",
    "raw-loader": "0.5.1",
    "reflect-metadata": "0.1.12",
    "rxjs": "^6.1.0",
    "rxjs-compat": "^6.1.0",
    "style-loader": "0.21.0",
    "to-string-loader": "1.1.5",
    "typescript": "^2.7.2",
    "url-loader": "1.0.1",
    "webpack-hot-middleware": "^2.22.1",
    "webpack-merge": "4.1.2",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@ngtools/webpack": "^6.0.1",
    "@types/chai": "4.1.3",
    "@types/chart.js": "^2.7.18",
    "@types/jasmine": "2.8.7",
    "chai": "4.1.2",
    "jasmine-core": "3.1.0",
    "karma": "^2.0.2",
    "karma-chai": "0.1.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-jasmine": "1.1.2",
    "karma-webpack": "3.0.0",
    "webpack": "^4.8.3",
    "webpack-dev-middleware": "^3.1.3"
  }

**Minimal reproduction of the problem with instructions**
I have error "Unexpected value 'ChartModule' imported by the module 'e'. Please add a @NgModule annotation." in browser.

My app is something like this.
https://stackblitz.com/edit/github-wdkze4-a8quvk

And don't understand what is the "e" module... I don't have "e" module in my application.

**Please tell us about your environment:**
dev environment

* **Angular version:** ^6.0.1

* **PrimeNG version:** ^5.2.7"

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

![error](https://user-images.githubusercontent.com/26679977/40228554-3189de6e-5a9a-11e8-8f9e-28000396f96b.PNG)

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
