### ISSUE TITLE
p-dropdown scroll jumps to top of the list

### ISSUE THREAD

**Issue by EleanorHughes** [primefaces/primeng#5760]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please see example here:
https://github-esrsde.stackblitz.io
and also in the 'Group' demo on the primeng site: https://www.primefaces.org/primeng/#/dropdown 

**Current behavior**
When you scroll to the bottom on a dropdown it automatically jumps to the top.

**Expected behavior**
When you scroll to the bottom of a dropdown it should not jump you to the top it should stay at the bottom

**Minimal reproduction of the problem with instructions**
Create a dropdown with scroll bar, scroll to the bottom of the dropdown

**Please tell us about your environment:**
win10, npm

* **Angular version:** 5.X
Anguar 5.2.3

* **PrimeNG version:** 5.X
5.2.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Only tested in Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.4.2

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
