### ISSUE TITLE
Click on menubar with autodisplay should not close its content

### ISSUE THREAD

**Issue by whiteblackkeys** [primefaces/primeng#5763]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Minimal reproduction of the problem with instructions**
Go to https://www.primefaces.org/primeng/#/menubar, 
if you click on the navbar with autodisplay true, why the content is hiding? I think it would be better to keep it open, or at least if you click it another time it would be nice to display it again.

**Comment by cagataycivici** [comment]
Will be reviewed at https://github.com/primefaces/primeng/issues/7085
