### ISSUE TITLE
Galleria makes protractor tests block

### ISSUE THREAD

**Issue by eamonnboyle** [primefaces/primeng#5764]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
- Protractor tests timeout / block if the page contains a Galleria component. Basically the same issue Growl had in Bug #4681. Just needs to run interval code outside of Angular zone. I have tested in local patch.

**Expected behavior**
- Test understands that cycling Galleria is outside of Angular zone

**Minimal reproduction of the problem with instructions**
- Run e2e test with protractor
- Visit a page with a running galleria component
- Protrector never returns as interval keeps Angular thinking it's busy

**What is the motivation / use case for changing the behavior?**
You can't write good e2e tests for pages with Galleria.

* **PrimeNG version:** 5.X
5.2.7. Looks like it is still an issue with 6.0.0_alpha.

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
