### ISSUE TITLE
Turbotable header misaligned with body when element in header receives focus.

### ISSUE THREAD

**Issue by denprokazov** [primefaces/primeng#5767]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-fv9ypd
 
**Current behavior**
Header is misaligned with table body when when something in header takes focus.

**Expected behavior**
Table body scrolls with table header and properly aligned.

**Minimal reproduction of the problem with instructions**
Make scrollable table with header and body and header with some input field in it(whatever primeng input component).
1) Scroll table till the end horizontally(or just till the column that was hidden by scroll)
2) Place cursor in the any input in header
3) Scroll table back so that cursor you just placed is not visible
4) start input
You'll see that table header is misaligned with table body.
Please check [this gif](https://imgur.com/LWYbHOb)

**Please tell us about your environment:**
Ubuntu 18.04, Visual studio code
Windows 10, Visual studio code

* **Angular version:** 5.2.10, 6.0.2

* **PrimeNG version:** 5.2.6

* **Browser:** [ all ]
 
* **Language:** [ all ]

* **Node (for AoT issues):** `node --version` =   v9.11.1

**Comment by shridhar-tl** [comment]
Facing the same issue. When data is more in some of the rows then the columns are mis-aligned. Also in most of the cases while scrolling towards the right end it was proper and when we scroll towards left having mis-alignment for few pixels equivalent to the width of vertical scrollbar at the end. Almost 95% of the times table with scrollable body doesn't work well for me.

**Comment by kaushikparmar** [comment]
I am also facing the same issue.

Header becomes miss aligned with body when the body gets a scrollbar.

Someone, please help as soon as possible.

**Comment by cagataycivici** [comment]
A technical limitation here, browser changes the scroll left of the header but does not invoke any scroll event that we bind so we have no chance to sync. Two quick workarounds until a real solution can be identified;

1) Add tabindex="-1" to inputs but this removes tab key based navigation

2) If vertical scroll is not needed, wrap the table in a div with overflow: auto and a fixed width instead of using the built-in scrollable table.

**Comment by wewedgeworth** [comment]
We have the same issue.

For our case, tab indexes are essential to our application. Also, our application's screens are complex, and the built-in scrollbars are necessary in most cases, so these workarounds do not work for us.

Is there any plan to implement a fix for this issue?

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG [11.2.2](https://stackblitz.com/edit/github-fv9ypd), if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
