### ISSUE TITLE
Dropdown: When options data change, data is filter based on last filter text but text is not visible in filter textbox

### ISSUE THREAD

**Issue by shaileshyadav24** [primefaces/primeng#5773]
There are 2 dropdown displaying country and state. When i select country and then after apply filter in state(i didn't select state) but then change country, filter is applied on new state data but filter text is not visible.

Expected behaviour:- Either text should be visible or filter should not be applied.

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
