### ISSUE TITLE
dismissableMask not working as intended

### ISSUE THREAD

**Issue by OvesAmad** [primefaces/primeng#5774]
I have been trying to get dismissableMask feature working with a variable in my component which is either set to true or false when uploading files. Initially the variable is set to false but when a user starts uploading the boolean variable is set to true in the component and when all files are done uploading the variable is set to false. But dismissableMask does not seem to react with the boolean value and lets me close the modal when it is set to false. My assumption was that it shouldn't let you close the modal until that boolean value is set not false. Is that not the case?

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
