### ISSUE TITLE
Screen reader support - Turbo Table Sortable Headers

### ISSUE THREAD

**Issue by wittdavid** [primefaces/primeng#5776]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

**Current behavior**
After change #5697, JAWS reads the unsorted column headers as "number link".  This is because it is now an anchor without an aria-label.  The only sortable column that ends up with an aria-label is the currently sorted column.

**Expected behavior**
Aria labels need to be applied to all generated links.  Perhaps an additional input of "ariaLabel" that would have a default of "Click to sort ascending".  

**Minimal reproduction of the problem with instructions**
JAWS required.

**What is the motivation / use case for changing the behavior?**
Section 508 compliance

**Please tell us about your environment:**

* **Angular version:** 5.X

* **PrimeNG version:** 5.X
Issue STARTS in 5.2.6.

* **Browser:** 
Detected in both IE11 and Chrome 63
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
See the new aria attributes of pSortableColumn please for screen readers.
