### ISSUE TITLE
floating images in p-table body are cropped by header

### ISSUE THREAD

**Issue by timmackey** [primefaces/primeng#5778]
**I'm submitting a ...**  
[X] bug report

**Current behavior**
Floating image in p-table "body" is hidden by p-table "header", as this image shows:
![image](https://user-images.githubusercontent.com/16199122/40402117-c0bb18ca-5dfe-11e8-9ded-926834d35824.png)

**Expected behavior**
Floating image should not be cropped.

**Minimal reproduction of the problem with instructions**
*.component.html (extraneous code omitted for clarity):

`<p-table [columns]="datagrid_cols" 

         [value]="datagrid_data" 
         [loading]="loading"
         [resizableColumns]="true"
         [scrollable]="true"
         scrollHeight="200px"
         [responsive]="true"
         styleClass="datagrid-header">
    <ng-template pTemplate="header" let-columns>
        
    </ng-template>
    <ng-template pTemplate="body"
                 let-rowData 
                 let-columns="columns"
                 let-rowIndex="rowIndex">
        <tr>
            <td *ngFor="let col of columns" class="ui-resizable-column">
                <span class="ui-column-title">
                    {{l(col.header)}}
                </span>
                <span *ngIf="col.field === 'photourl'; else ngElse_noPhotoUrl">
                    <img src="{{rowData[col.field]}}"
                    class="student-photo"
                    appendTo="body">
                </span>
                <ng-template #ngElse_noPhotoUrl>
                    {{rowData[col.field]}}
                </ng-template>
            </td>
        </tr>
    </ng-template>
</p-table>`
----------------------------------------
*.component.css:

:host >>> .ui-column-resizer {
    display: block !important;
    position: absolute !important;
    top: 0;
    right: 0;
    /* margin: 0; */
    /* width: .5em; */
    width: 1px !important;
    height: 100% !important;
    padding: 1px !important;
    cursor: col-resize !important;
    border-left: 1px solid red !important;
    border-right: 1px solid red !important;
}

.student-photo {
    height: 20px;
    z-index: 10000;
}

.student-photo:hover {
    transform: scale(8);
    transform-origin: bottom;
    z-index: 10000;
}

.student-photo:active {
    transform: scale(8);
    transform-origin: bottom;
    z-index: 10000;
}

.datagrid-header {
    background-color: transparent !important;
}

.datagrid-header .ui-widget-header {
    background-color: transparent !important;
}

----------------------------------------
 appendTo="body" and z-index: 10000; presence or absence makes no difference.

**Please tell us about your environment:**
Windows 10, localhost

Angular version:
Angular CLI: 1.7.4
Node: 9.3.0
OS: win32 ia32
Angular: 5.2.6
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router
@ angular/cli: 1.7.4
@ angular-devkit/build-optimizer: 0.3.2
@ angular-devkit/core: 0.3.2
@ angular-devkit/schematics: 0.3.2
@ ngtools/json-schema: 1.2.0
@ ngtools/webpack: 1.10.2
@ schematics/angular: 0.3.2
@ schematics/package-update: 0.3.2
typescript: 2.4.2
webpack: 3.11.0

PrimeNG version: 5.2.0

Browsers tested:
Google Chrome Version 66.0.3359.139 (Official Build) (64-bit)
Internet Explorer Version 11.371.16299.0
Microsoft Edge Version 41.16299.371.0
Firefox Quantum Version 59.0.2

Language: n/a

**Comment by cagataycivici** [comment]
Better to handle it on your side rather than we emposing css on table content representation.
