### ISSUE TITLE
InputMask - Email -> TLD limited to 3 characters

### ISSUE THREAD

**Issue by FuggyD** [primefaces/primeng#578]
when using InputMask for Email Input, it is only possible to use TLD with 3 or less characters (e.g. .com or .org)
It isn't possible to enter a valid email adress with TLDs like .info /.systems

**Comment by FuggyD** [comment]
Oh, i saw that it is possibile to conf how long the TLD in email-mask could be:

`<p-inputMask mask="*{1,20}@*{1,20}.*{1,3}" placeholder="Email"></p-inputMask>`

e.g. change `.*{1,3}` to `.*{1,4}` for TLD like .info (or even more for longer TLDs

**Comment by dan-madaket** [comment]
Is this still valid?  I'm not seeing anything in the documentation that indicates we can use a variable number of characters. It's not working in my app either.
