### ISSUE TITLE
Mask input on calendar

### ISSUE THREAD

**Issue by vmgranados** [primefaces/primeng#5780]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Calendar component can't use mask to input manually the date

**Expected behavior**
It would be very useful to have an input mask to complete the date manually

**What is the motivation / use case for changing the behavior?**
User experience improvement

**Comment by crissi** [comment]
+1

**Comment by williancorrea** [comment]
+1

**Comment by nuxf10ir** [comment]
+1

**Comment by cmdelg** [comment]
+1

**Comment by cagataycivici** [comment]
It is too complex to support.
