### ISSUE TITLE
primeng + ie9 + angular 5 - ERROR in Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by mdmota** [primefaces/primeng#5781]
**Angular 5 
Primeng 5.2.3
IE 9

Windows 7**

I created a page with component p-fileUpload. When I select a file it generates the error in the console
"Cannot read property 'length' of undefined"
[zip.zip](https://github.com/primefaces/primeng/files/2031018/zip.zip)

Attached zip with: 
.angular-cli.json
app.component.html 
app.component.ts
package.json
polyfills.ts
shims_for_IE.js

**Error in fileupload.js line 89. Files is undefined**
![error](https://user-images.githubusercontent.com/21266037/40431500-f0c23722-5e7d-11e8-8bfa-dc9dd26e1681.png)

**Comment by QiZZ121** [comment]
Because event.dataTransfer || event.target do not supported in IE9, and i don't have any  solutions.
