### ISSUE TITLE
Resizable doesn't work properly with "scrollable" and "frozenColumns"

### ISSUE THREAD

**Issue by druha95** [primefaces/primeng#5782]
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already
[ ] support request => Please do not submit support request here, instead see 

https://github-zum9ns.stackblitz.io

**Current behavior**
Resizable doesn't work if we have [scrollable]=true and frozenColumn="".
STEPS TO REPRODUCE
1. Table is loaded
2. Some columns are scrollable, some are frozen
3. Try to resize first column from scrollable area
4. Layout is broken
5. Try to resize 4th column from scrollable area.
6. Console error 
TypeError: Cannot read property 'nextElementSibling' of undefined
    at Table.resizeColGroup (table.ts:1460)
    at Table.onColumnResizeEnd (table.ts:1432)
    at ResizableColumn.onDocumentMouseUp (table.ts:2323)

**Expected behavior**
Scrollable columns should be resizable

* **Browser:** [all]
 
* **Language:** [TypeScript X.X]

* **Node (for AoT issues):** `node --version` = 8.9.1

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/issues/5751
