### ISSUE TITLE
InputGroup support for InputMask

### ISSUE THREAD

**Issue by venkateshgbabu** [primefaces/primeng#5783]
P-InputMask as rounded corners on all sides when an Addon is added.

**Comment by aliasbody** [comment]
As a workaround, just add this to the theme css:
```
body .ui-inputgroup p-inputMask {
  display: flex;
  padding: 0; }
body .ui-inputgroup p-inputMask .ui-inputtext {
  border: 0; }
```

**Comment by sonicwong** [comment]
For PrimeNg v11, add this style:
`.p-inputgroup .p-inputtext,
  .p-fluid .p-inputgroup .p-inputtext{
    &.p-inputmask{
      width: auto;
    }
  }`
