### ISSUE TITLE
FileUpload still upload same files also if it is disabled

### ISSUE THREAD

**Issue by lippomano** [primefaces/primeng#5784]
**I'm submitting a ```[X] bug report```

**Case (Bug Reports)**
[Video example](https://drive.google.com/open?id=1JrJaHq9v47h6HNyiai4Gy8Y81UdGaEgr)

**Current behavior**
As you can see in the Video I disable the fileInput
` onBeforeUpload(event) {
    this.fileInput.disabled = true;
  }`
But if I click on the button during the upload it starts another upload.

* **Angular version:** 5.2.9

* **PrimeNG version:** "5.2.4",

* **Browser:** [Tested in Chrome ]

**Comment by lippomano** [comment]
No one can help me?

**Comment by cagataycivici** [comment]
You need to use disabled property of the component instead so bind a prop to it;
,,,xml
<p-fileUpload [disabled]="yourDisabled"
```
