### ISSUE TITLE
p-fileupload + ie9 error

### ISSUE THREAD

**Issue by mdmota** [primefaces/primeng#5785]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/angular-cjkq6s

**Current behavior**

When i choose file, console show error : files is undefined  . fileupload.js line 89
```
var files = event.dataTransfer ? event.dataTransfer.files : event.target.files;
        for (var i = 0; i < files.length; i++) {	'}' esperado
```

**Expected behavior**

Show name of file choosed inside component p-fileupload

**Minimal reproduction of the problem with instructions**
Click 'choose' and select any file

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

VS Code 1.23.1

* **Angular version:** 5.2.0

* **PrimeNG version:** 5.2.3

* **Browser:** [all | Chrome XX | Firefox XX | IE 9 | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

IE9 dont work
Works in ie10+, chrome and firefox
 
* **Language:** [all | TypeScript 2.5.3 | ES5]

* **Node (for AoT issues):** `node --version` =   8.9.4
![error](https://user-images.githubusercontent.com/21266037/40439604-c859991a-5e91-11e8-8837-46b04c917817.png)

**Comment by cagataycivici** [comment]
FileUpload supports IE10+.
