### ISSUE TITLE
TurboTable not working correctly with autoLayout and scrollable

### ISSUE THREAD

**Issue by nwbrad** [primefaces/primeng#5788]
PrimeNG 5.2.7
Angular 5.2.11

I have created a basic p-table with:
       <p-table #tt
                 [value]="..."
                 scrollHeight="200px"
                 [autoLayout]="true"
        >
![table_works](https://user-images.githubusercontent.com/347477/40455319-49a2ebca-5ea1-11e8-80a6-cd923a5ce5df.png)

The table works fine.  BUT, if I want to make the table scrollable, by adding scrollable=true, it breaks:
       <p-table #tt
                 [value]="..."
                 scrollHeight="200px"
                 [autoLayout]="true"
                 [scrollable]="true"
        >
![table_broken](https://user-images.githubusercontent.com/347477/40455305-3b6d1044-5ea1-11e8-8fa7-a7459d11ba46.png)

**Comment by lebnic** [comment]
I've created another issue, with a plunkr to help them "reproduce" this bug
https://github.com/primefaces/primeng/issues/5922

**Comment by areveronmolina** [comment]
I'm having the same problem.

**Comment by cagataycivici** [comment]
autoLayout is not supported in scrollable and/or resizable columns.

**Comment by digaus** [comment]
> autoLayout cannot be supported in scrollable and/or resizable columns.

It can if you would use sticky for the header instead of creating another table (Angular Material does this very well) https://qlyexjqvqpn.angular.stackblitz.io/

**Comment by jtkDvlp** [comment]
Your link does not work for me. I suppose you meant following https://material.angular.io/components/table/overview#sticky-rows-and-columns and https://developer.mozilla.org/docs/Web/CSS/position
