### ISSUE TITLE
p-table: selection is not updated properly when value is updated

### ISSUE THREAD

**Issue by lebnic** [primefaces/primeng#5791]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-issues-5791

**Current behavior**

p-table selected rows not "handled" properly when data is updated.

**Expected behavior**

In a p-table, list of selected items should only contain items that are comprise in the table (even if item was previously present in table...).

**Minimal reproduction of the problem with instructions**

see plunkr

**Comment by yigitfindikli** [comment]
Hi,
I think it's not a bug. You can clear own selection already in your component. If we implement this might be create performance issues.

You can track headerCheckBox bug your mentioned in stackblitz template here https://github.com/primefaces/primeng/issues/7062

**Comment by gatschet** [comment]
I think this is realy a bug. Even if i clear the [(selection)] table, after select a new item, the "old" one are still in the list!
