### ISSUE TITLE
editor MaxLength

### ISSUE THREAD

**Issue by rsrPrabhu** [primefaces/primeng#5794]
hi buddies,
    i used the primeNg editor yesterday.I need to allow only 4000 characters  only. how should i ?
     I used the all built in functions like onmodelchange,ontextchange,keypress,paste,oncontentchange events. But nothing works i'm expected .pls tell valid way to use .

**Comment by cagataycivici** [comment]
Please use forum for questions and help requests. Also refer to quilljs to see if there is a way possible.
