### ISSUE TITLE
Feature Request: Allow customization of body for Confirm Dialog component 

### ISSUE THREAD

**Issue by ammar91** [primefaces/primeng#5795]
Right now, it is only possible to define customize html for footer section inside `p-footer ` element. 
It would be great to have more control where one can define customize html for body section as well.

One great example is  `Dialog Component` where one have a complete control to define the layout of dialog including header, body and footer.

**Comment by cagataycivici** [comment]
message property accepts html for body content.

**Comment by chasestory** [comment]
Not everyone likes putting templates in the controller.... It really is messy when you have multiple confirmDialogs... I would recommend reconsidering this response....
