### ISSUE TITLE
Sorting issue when Column has same data in Chrome browser.

### ISSUE THREAD

**Issue by punnepallivenkat** [primefaces/primeng#5798]
Hi Prime NG,

I have one issue occurring the  sorting in data table:

Description: when I have the column  has same data and I perform the sorting,

my expected result is not sorting (column has same data) and it is working fine in IE browser.

Thanks,
Venkat P

**Comment by cagataycivici** [comment]
Sorting is done by the browser which is Chrome so this is expected, it has been discussed couple of times;

http://codecoding.com/beware-chrome-array-sort-implementation-is-unstable/

Maybe customSort would be useful for your case.
