### ISSUE TITLE
Pressing enter when p-calendar input is blank or invalid causes value to revert to last selected date without updating input text

### ISSUE THREAD

**Issue by ryanwawr** [primefaces/primeng#580]
If you use a standard p-calendar component to select a date, then delete the text in the input or change it to an invalid string, hitting enter will revert the value of the selected date to the previously selected date without changing the text in the input to match. Link to video demonstrating bug on the PrimeNG demo page is below.

http://screencast.com/t/bMVtxwZPHdo

On a related note, it would be nice if hitting enter with a valid date in the input caused the calendar to close, as it does for the standard jQuery-ui date picker field. It's not too difficult to accomplish this with some simple javascript, but I'd like to have an option available through the p-calendar interface rather than relying on something like document.findElementById or using ViewChild to access the internals of p-calendar from the component that includes it.

**Comment by cagataycivici** [comment]
Wrong issue number, reopen.

**Comment by cagataycivici** [comment]
Does it still happen with new p-calendar which is native.

**Comment by ryanwawr** [comment]
Seems to be fixed now, as far as I can tell.
