### ISSUE TITLE
TurboTable issue with Multiple Row and Checkbox selections activated

### ISSUE THREAD

**Issue by kmataru** [primefaces/primeng#5801]
**I'm submitting a**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-rrsjqg

**Current behavior**
Activating `Multiple Row Selection` and `Checkbox Selection`, both on the same table causes it to fail, making selection via Checkboxes almost impossible if any Row is Selected/Clicked previously.

**Expected behavior**
Clicking on a row would not fail when clicking checkboxes.

**Minimal reproduction of the problem with instructions**
Activate `Single Row Selection` and `Checkbox Selection`.

**Please tell us about your environment:**
Windows 10, Visual Studio 2017, npm

* **Angular version:** 6.0

* **PrimeNG version:** 5.X

* **Browser:** Chrome 66, maybe all
 
* **Language:** TypeScript 2.8 | ES6

**Comment by JacobSiegle** [comment]
#6613

**Comment by cagataycivici** [comment]
Row selection and radio/checkbox column selection are not supported at the same time as conflicts occur.
