### ISSUE TITLE
RTL support for Table Pagination

### ISSUE THREAD

**Issue by ahmedhassanahmedwasfy** [primefaces/primeng#5802]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**

paginator cursors are reversed 
![image](https://user-images.githubusercontent.com/25501236/40579771-9a4aff62-6140-11e8-8fe8-2ef8b1dfc793.png)

**Expected behavior**

the cursor to be in the right order
**Minimal reproduction of the problem with instructions**

https://stackblitz.com/edit/github-ajh2b8?file=src/app/app.component.html

i opened the sample on prime ng site for p-table with pagination 
i put class ui-rtl
and dir=rtl
and got the attached image.
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

chrome
* **Angular version:** 5.X

angular 6
* **PrimeNG version:** 5.X

5.2.6
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by moshtarek** [comment]
مرحبا
قم بإضافة الكود التالي لل style.css الخاص بمشروعك
.pi-step-backward:before {
  content: "\e917";
}

.pi-step-forward:before {
  content: "\e916";
}

.pi-caret-left:before {
  content: "\e905";
}

.pi-caret-right:before {
  content: "\e904";
}

**Comment by guybi** [comment]
+1

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
