### ISSUE TITLE
MenuItem#styleClass suppport for Steps

### ISSUE THREAD

**Issue by dkrysiak** [primefaces/primeng#5805]
I'm submitting a **feature request**. Steps should honor styleClass attribute of MenuItem API.

**Plunkr Demo**
https://stackblitz.com/edit/github-33r1qg

**Current behavior**
MenuItem#styleClass is ignored.

**Expected behavior**
In the attached demo, styleClass attribute of MenuItem should result in applying the .step-base and .step-main classes to li.ui-steps-item elements, resulting in displaying their text in grey and red color.

**What is the motivation / use case for changing the behavior?**
Allowing to apply more advanced styles to particular steps.

In my case, when current state is 3 (of 5), I want to make steps 1-4 active (allowing to go to the next step, .step-active or not(.ui-state-disabled)), but only steps 1-3 displayed as "visited" (.step-visited).

**Additional/related**
Similarly, the style property of MenuItem support could be implemented.

**PrimeNG version:** 5.2.6

**Comment by MenezesVinicius** [comment]
I'm having the same issue, is there some solution for this?
