### ISSUE TITLE
p-dropdown: add a class to the ui-dropdown element if open

### ISSUE THREAD

**Issue by me-12** [primefaces/primeng#581]
I would like to add a different style to the .ui-dropdown element if the dropdown is open. Currently there is no way to tell if the dropdown is opened or not. A solution would be to add a class like ui-dropdown-open to the .ui-dropdown element if the dropdown is opened.

**Comment by Mrtcndkn** [comment]
When you opened the dropdown panel ui-state-focus is added to the component the sameway when you close it ui-state-focus is still there.Maybe you can style the focus?

**Comment by cagataycivici** [comment]
I've added "ui-dropdown-open" to the main outmost div container element.
