### ISSUE TITLE
DataScroller loads too many items when set to lazy-load

### ISSUE THREAD

**Issue by jonbarthol** [primefaces/primeng#5816]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/datascroller-bug

**Current behavior**
In the above StackBlitz example, the DataScroller should only load 20 items at a time. However, it loads much more than that.

**Expected behavior**
Only 20 items should be loaded at a time.

This issue is similar to issue #3906, which has been closed.

**Comment by Bohdan-Tereta** [comment]
See my pull request, https://github.com/primefaces/primeng/pull/4676, that's quite simple and fixed a similar problem for me. I use the modified version of datascroller now. Haven't checked how it works in latest revisions.

**Comment by rafa-as** [comment]
same here!

**Comment by pekevski** [comment]
@jonbarthol remove the setTimeout in the loadData event and it works fine?

**Comment by jonbarthol** [comment]
@pekevski yes, removing the 250 milliseconds from setTimeout resolves the issue.

**Comment by gourav1941** [comment]
@jonbarthol  250 millisec stimulates real time situation. It is bound to happen when some API will take time to return data. In this scenario datascroller fails. @pekevski  any thought on this

**Comment by gourav1941** [comment]
@pekevski **Thanks a lot for ur time and explanation.**
I added a loader as u suggested. But Still, scroller events are getting fired when a user scrolls rapidly.
Any other solution, or name or loader u r using plz

**Comment by cagataycivici** [comment]
DataScroller is deprecated in favor of VirtualScroller
