### ISSUE TITLE
error "property frozenValue does not exist on Type TreeTable"

### ISSUE THREAD

**Issue by QinTuCoding** [primefaces/primeng#5818]
You will get this error "property frozenValue does not exist on Type TreeTable" when running ng build --aot.

**Comment by QinTuCoding** [comment]
In TreeTable, I guess we need to add @Input() frozenValue: any[].

**Comment by cagataycivici** [comment]
Please try the new TreeTable of 6.0.0-alpha.2

**Comment by milanello2** [comment]
Hello @cagataycivici please how can i install the newest primeng because il i execute npm install primeng --save i have the 5.2.7 version

**Comment by milanello2** [comment]
Hello @cagataycivici please how can i install primeng V6.0.0 because if i execute npm install primeng@6.0.0-alpha.3-SNAPSHOT i have npm ERR! notarget No matching version found for primeng@6.0.0-alpha.3-SNAPSHOT

**Comment by QinTuCoding** [comment]
Do you upgrade you angular to version 6?

**Comment by QinTuCoding** [comment]
Hi @milanello2, My way of upgrading the primeng is like:
1. git clone the latest primeng;
2. go to this project folder and package it with "npm pack", it will generate primeng-6.0.0-alpha.3-SNAPSHOT.tgz
3. go to your project install this package locally.
