### ISSUE TITLE
[Feature] template based notification

### ISSUE THREAD

**Issue by ghost** [primefaces/primeng#5819]
Hello,

Wouldn't be nice if primeng has template based notification.

Thanks for the great UI lib.

**Comment by cagataycivici** [comment]
Please elaborate.

**Comment by mouradghafiri** [comment]
I mean the Growl : https://www.primefaces.org/primeng/#/growl

is it possible to have a template for the message to show (exemple show a Card in growl message).

Thank you in advance

**Comment by cagataycivici** [comment]
Toast component supports templating.
