### ISSUE TITLE
Object and subobject filter in the turbo table

### ISSUE THREAD

**Issue by salem017** [primefaces/primeng#5827]
Hi primefaces,
I'm submitting a bug on the turbo table. In fact , when I am trying to filter a object with his subobject , the filter doesn't work .

[ x] bug report
[x ] feature request 

**Plunkr Case (Bug Reports)**

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
For example, I have a json:
house 
{
                "idhouse": 6,
                "owner": [
                    {
                        "idowner": 1,
                        "nameowner": "momo"
                    }
                ],
}
If I try to filter idhouse, it work. But if I try to filter idowner or nameowner with the same methods, it will not work .
I use the dynamic filter with col.field.
I read the documentation and use the filter method in the columns header.

**Expected behavior**
I expected that the col.field with the filter methods will work .

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
It will be a great feature because it maybe concern a lot of people. The same people who use the deprecated table and not the turbo table because of this issue.

**Please tell us about your environment:**
I use intellij.

Angular version: 5

PrimeNG version: 5

Browser: [all]
Language: [all]

**Comment by salem017** [comment]
Up I revolve the issue . I "flat" the json but i have a other issue. It is about custum filter. In my case , one columns can have multiple response like idcategory:1,2,3,4 and  i want to filter it with a custum filter . 
Why ?
because with a dropselect, one person can see all the entities with his idcategory but he can select multiple idcategory and I have the display all the entities (like a OR)

**Comment by cagataycivici** [comment]
Please I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
