### ISSUE TITLE
TurboTable border is not showing in FF, Edge browser

### ISSUE THREAD

**Issue by sunnyyadav100** [primefaces/primeng#5829]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

**Current behavior**

Table border is not visible in Firefox and Microsoft Edge . We can look official page https://www.primefaces.org/primeng/#/table/colresize  in FireFox/Edge browser.
![image](https://user-images.githubusercontent.com/9139037/40826417-2b9f5746-6598-11e8-8f5c-a6ec0c600a01.png)

**Expected behavior**

Table border should show across browser
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.X

Angular 6.0.3
* **PrimeNG version:** 5.X

Prime Ng ^6.0.0-alpha.2
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

FF 60.0.1 (64-bit)
 Microsoft Edge 41.16299.248.0
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by sunnyyadav100** [comment]
This is due to 'border-collapse' property, after changing it to below, border is appearing
.ui-table table {
    border-collapse: separate;
    border-spacing: 0px;
}

**Comment by thaihacong** [comment]
@cagataycivici: The bug still happens on primeng v7.0.4 in Firefox and Edge browser. Could you please verify and re-open this again?

**Comment by dbelob** [comment]
@cagataycivici: Border still not showing on PrimeNG 13.0.2 in Firefox 95.0.2 when `[resizableColumns]="true"` (is showing in Chrome and Edge).

![image](https://user-images.githubusercontent.com/22131253/147364685-4917c73f-3a3b-4ff6-8d2c-c425f338f370.png)
