### ISSUE TITLE
Turbo table programmatically selection

### ISSUE THREAD

**Issue by alpernakin** [primefaces/primeng#5830]
I have a team edit form as I select the team to edit from a primeng turbo-table. In case of unsaved work on a selected team, I like to prevent selection of another team on the turbo-table. Therefore, I tried to programmatically select the previous one by setting the selection object and it did not work with me.

Note: this feature works with multiple selection, not with single.

**I'm submitting a ...**  (check one with "x")
```
[] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
`<p-table [value]="teamList" [(selection)]="selectedTeam" [resizableColumns]="true" selectionMode="single" [paginator]="teamList.length > 5"
            [rows]="5" [scrollable]="true" (onRowSelect)="onTeamSelected($event)"> ..... </p-table>`

```
private onTeamSelected(event: any) {

    if (this.team.unsavedWork) {
        if (!!this.prevSelectedTeam) {
            this.selectedTeam = this.prevSelectedTeam;
            return;
        }
    }

    // do implementation

    // in case of saved work, to select the team back
    // the previous selected team is being set
    this.prevSelectedTeam = this.selectedTeam;
}
```

**Current behavior**
The table does not recognise programmatically selected object and does not show it visually

**Expected behavior**
The table would be able to select the item and show it

* **Angular version:** 5.2.9

* **PrimeNG version:** 5.2.4

**Comment by anaq1** [comment]
I had the same scenario and I solved it with this dirty "setTimeout" workaround:
```
onRowSelect(event) {
    if(this.lastSelectedItem && !this.form.valid) {
      const self = this;
      setTimeout(function(){
        self.selectedItem = self.lastSelectedItem;
      }, 0);
    } else {
      this.lastSelectedItem = event.data;
      this.form.reset(event.data);
    }
  }
```
It seems to work, but it needs more tests.
