### ISSUE TITLE
Table: Selection and RowGroup do not work together (conflicting behavior)

### ISSUE THREAD

**Issue by nwkyom** [primefaces/primeng#5831]
**I'm submitting a ...** 
```
[X] bug report
[ ] feature request
[ ] support request
```

**Plunkr Case (Bug Reports)**
None

**Current behavior**
Using a table with RowGroup (of any kind: Toggleable, SubHeader or RowSpan) and Selection (single, multiple or checkbox) plugins: 
when the user clicks on one row, all the rows of the group are selected (the group must contain at least 2 rows...)

**Expected behavior**
Only the clicked row should be selected.

**Minimal reproduction of the problem with instructions**
cf. current behavior.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Linux Mint 18.3, VSCode, npm

* **Angular version:** 5.X
Angular 6.0.3

* **PrimeNG version:** 5.X
PrimeNG 5.2.7

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Opera, Chrome, Chromium, Firefox

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

* **Node (for AoT issues):** `node --version` =   
v8.11.2

**Comment by mvdicarlo** [comment]
I am also having this issue.
I believe this conflict occurs due to the use of dataKey in both RowGroup and Selection.
But that is just a hunch.

**Comment by JimmySalisbury** [comment]
Any update on this?

**Comment by cagataycivici** [comment]
These two features are not compatible by nature, suggestion is to use a button or a link per row.

**Comment by przemyslav** [comment]
Wouldn't an ability to pass a different dataKey used for selection or one for grouping solve this issue?
