### ISSUE TITLE
The exportFilename property of TurboTable is not working

### ISSUE THREAD

**Issue by MaribelPC** [primefaces/primeng#5833]
**I'm submitting a ...**
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
If the 'exportFilename' property of TurboTable is activated with the desired file name. By clicking the exportCSV button, download a file named 'undefined.csv'.

**Expected behavior**
The possibility to change the name of the .CSV file downloaded in the exportCSV() method.

**Minimal reproduction of the problem with instructions**
```
<p-table #sit class="tableInterviews" [columns]="cols" [value]="scheduledInverviews" [paginator]="true" [rows]="5" [rowHover]="true" [exportFilename]="Interviews">
    <ng-template pTemplate="caption">
        <div class="ui-helper-clearfix tableTitle">
            <div class="titleTable"> Scheduled Interviews </div>
            <button type="button" class="btn btn-outline-secondary" (click)="sit.exportCSV()" style="float: right;">
              <div class="fa-1.5x">
                  <i class="icon fas fa-file-excel"></i>
              </div>
            </button>
        </div>
    </ng-template>
</p-table>
```

**What is the motivation / use case for changing the behavior?**
Set a custom name to the downloaded file.

**Please tell us about your environment:**
Windows 10 Enterprise / Visual Studio Code v1.23.1 / npm Node v10.1.0

* **Angular version:**
v6.0.2

* **PrimeNG version:** 
v6.0.0-alpha.1

* **Browser:**
Vivaldi v1.15.1147.42
 
* **Language:** 
TypeScript v2.7.2

* **Node (for AoT issues):**
v10.1.0

**Comment by andrew-pb** [comment]
Seems to work if you remove brackets.  Example below
exportFilename="Interviews"

**Comment by cagataycivici** [comment]
or;

`[exportFilename]="'Interviews'"`
