### ISSUE TITLE
Tree - reusing pTemplate templates + catch-all template for typed nodes

### ISSUE THREAD

**Issue by chriswhite199** [primefaces/primeng#5836]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/github-dhzdfz?file=src%2Fapp%2Fapp.component.html

**Current behavior**
How would you go about adding a catch-all pTemplate and / or re-using the same template for multiple types for tree templating? 

I know you can use pTemplate="default" for those TreeNodes that don't have a typed defined, but i can't come up with anything if i want type different types to have the same template, without repeating the template block

```html
<p-tree [value]="nodes">
    <ng-template let-node  pTemplate="type1">
        type1: {{ node.label }}
    </ng-template>

    <!-- Ideally i don't want to have to repeat this template -->
    <!-- maybe something like pTemplate="type1|type2" -->
    <ng-template let-node  pTemplate="type2">
        type2|3: {{ node.label }}
    </ng-template>
    <ng-template let-node  pTemplate="type3">
        type2|3: {{ node.label }}
    </ng-template>

    <!-- Something like this for a catch-all non-null type -->
    <ng-template let-node  pTemplate="*">
        typed*: {{ node.label }}
    </ng-template>

    <!-- Still handle non-typed nodes -->
    <ng-template let-node  pTemplate="default">
        default: {{ node.label }}
    </ng-template>
</p-tree>
```

**Expected behavior**
Document how to match multiple types with the same template block (whether that be with some ng-container / ng-template magic thats beyond my angular-kung-fu skills, or via a code change to implement something like `pTemplate="*"`

**Minimal reproduction of the problem with instructions**
See stackblitz example

**What is the motivation / use case for changing the behavior?**
DRY principles

**Please tell us about your environment:**
N/A

* **Angular version:** 5.2.10

* **PrimeNG version:** 5.2.6

* **Browser:** all

* **Language:** all

* **Node (for AoT issues):** N/A

**Comment by sygitowiczp** [comment]
define variable in component like this

private nodeTypes = ["DOC","PPT","JPG","XLXS","BAT","TXT","PDF","XLS"];

then in template define one ng-template like this

<ng-template let-node *ngFor="let nodeType of nodeTypes" [pTemplate]="nodeType">
  ... your inner content
</ng-template>

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
