### ISSUE TITLE
I want apply a function on rowExpand but there are no such event i can find on prime ng documentation. please share if there is any solution for that !

### ISSUE THREAD

**Issue by maksof-kashif** [primefaces/primeng#5837]
<p-dataTable [value]="rollDataObj" expandableRows="true" class="appOmegaTable" [rows]="10" [paginator]="true" [pageLinks]="3" [rowsPerPageOptions]="[5,10,20]" onRowExpand="setRole()" >
					<p-column expander="true" styleClass="col-icon"></p-column>
					<p-column field="RoleId" header="Roll ID"></p-column>
					<p-column field="RoleName" header="Role Name"></p-column>
					<p-column field="OrganisationId" header="Organisation Id"></p-column>
					<p-column field="DB_LogisureApplication.AppName" header="Application Name"></p-column>
					<p-column field="" header="Delete">
						<ng-template let-rollDataObj="rowData" pTemplate="body" >
							<button pButton type ="button" (click)="deleteRoleById(rollDataObj.RoleId)" label="Delete" class="ui-button-danger"></button>
						</ng-template>
					</p-column>
					<ng-template let-rollDataObj pTemplate="rowexpansion">
						<div class="ui-grid ui-grid-responsive ui-fluid" style="font-size:16px;padding:20px">
							<div class="ui-grid-row">
								<table>
									<tr>
										<th>Permission Name</th>
										<th>Permission</th>
									</tr>
									<tr >
										<td></td>
										<td>
											<mat-slide-toggle></mat-slide-toggle>
										</td>
									</tr>
								</table>
							</div>
						</div>
					</ng-template>
				</p-dataTable>

**Comment by maksof-kashif** [comment]
This issue is solved sorry dude !

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.
