### ISSUE TITLE
PrimeNG Issue Template doesn't have PrimeNG

### ISSUE THREAD

**Issue by filip12345678910** [primefaces/primeng#5842]
When I tried to create a new issue, I clicked on:
https://stackblitz.com/github/primefaces/primeng-issue-template
to program my problem. But in app.module.ts, 'primeng/primeng' is red underlined and says cannot find module 'primeng/primeng'. So I can't use PrimeNG.

**Comment by cagataycivici** [comment]
It is an issue with stackblitz error highlighting, it works properly though.
