### ISSUE TITLE
IE 11: Placeholder text bug on focus, console error when text is changing

### ISSUE THREAD

**Issue by kandyba** [primefaces/primeng#5843]
I'm having trouble with the Placeholder in IE 11.  Console error when I try to edit text block
I'm using it with the Primeng (Angular6 components) which riches text editor component based on Quill.
Please have a look at my video:
https://www.screencast.com/t/ch3MaozO
https://www.screencast.com/t/QLInsJSNJ

Expected behavior: Placeholder should have the same behaviour as it has in chrome, ff and safari, without console errors

Actual behavior: The Placeholder in IE can be clicked without cursor: move; and cursor: resize; and resizing of existed text inside of editor, console errors

Platforms: Windows 10, Windows 7
Version: IE 11

**Comment by cagataycivici** [comment]
This is not a PrimeNG problem but seems to be the behavior of IE
