### ISSUE TITLE
p-autocomplete list items rendered outside of the Tag.

### ISSUE THREAD

**Issue by gsingara** [primefaces/primeng#5845]
I found issue with Primeng AutoComplete input control,
see the image from Primeng site,the highlighted "div"  rendered inside "p-autocomplete" tag.
![primeauto](https://user-images.githubusercontent.com/39909140/40920197-728389be-6829-11e8-824a-b2d3c1d48bda.png)
But in my Application it is rendered outside of the Tag.check below attached images

![otsite](https://user-images.githubusercontent.com/39909140/40920663-d86dd97c-682a-11e8-8b8e-eaeeb28d4fc5.png)
![otsiteauto](https://user-images.githubusercontent.com/39909140/40920666-dc08c54c-682a-11e8-8d2b-a9200477fe55.PNG)

Any Idea?

**Comment by cagataycivici** [comment]
Please use forum for support requests, check if you have appendTo body setting.
