### ISSUE TITLE
Styling TurboTable Scrollbar (for Firefox)

### ISSUE THREAD

**Issue by laijac** [primefaces/primeng#5846]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
Currently, in Firefox, because there is no way to style the scrollbars, TurboTable shows the default browser scrollbar.  In our other components, when possible, we are using the ScrollPanel to style the Firefox scrollbar.  It would be great if the TurboTable could also use the ScrollPanel or provide some way to styling the scrollbars.

**Comment by cagataycivici** [comment]
We rather not mess with the scrollbars of the browsers for Table due to performance issues and to avoid overcomplicating things.
