### ISSUE TITLE
need tooltip on p-dropdown options 

### ISSUE THREAD

**Issue by shashiakosha** [primefaces/primeng#5848]
p-dropdown options comes truncated, suppose i have option value as 
1- my first option of dropdown
its coming like ---
   my first option of...
i need to show full value of option on tooltip on hovering over that option.

**Comment by shashiakosha** [comment]
<img width="103" alt="screen shot 2018-06-05 at 1 31 11 pm" src="https://user-images.githubusercontent.com/8749750/40962987-c62d4140-68c4-11e8-848a-0e55fc41b05c.png">

**Comment by cagataycivici** [comment]
Issue is not clear and lacks the stackblitz template, please read the issue guideline before creating new issues.
