### ISSUE TITLE
Sort is scrambled when a column have duplicate values

### ISSUE THREAD

**Issue by run1t** [primefaces/primeng#5849]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Sorry I didn't succed to use table in stackblitz :/ 

**Current behavior**
Sort on the table component are not consistent. When we have multiples rows with the same values when we re-sort the array multiple times it kind of scramble the array. I thinks it come from this piece of code where you are resorting the values array itself. Instead of this you should have an base array and always sort from this one.
https://github.com/primefaces/primeng/blob/1eec41707be20c5a59f1ba1bda1e1c74e97c9d67/src/app/components/table/table.ts#L567

**Expected behavior**
Have the same sort every time we sort on a column.

**Comment by cagataycivici** [comment]
Sorry, issue it not clear and no template that reproduces it.
