### ISSUE TITLE
Cannot resolve module '@angular/forms' 

### ISSUE THREAD

**Issue by yonatannn** [primefaces/primeng#585]
Hi,

I'm receiving the following error message when trying to load primeng (beta 9) component in typical NG2 app. It used to work great not long ago.

ERROR in ./~/primeng/components/listbox/listbox.js
Module not found: Error: **Cannot resolve module '@angular/forms'** in C:\code solutions\projectname\node_modules\primeng\components\listbox
 @ ./~/primeng/components/listbox/listbox.js 13:14-39

Your help is appreciated

Yoni

**Comment by MarkPerryBV** [comment]
What version of Angular2 are you using. They recently changed the @angular/forms.

**Comment by garethlewis** [comment]
You need to reference this in your package.json if you are using rc.4 of Angular 2.

"@angular/forms": "0.2.0",

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
