### ISSUE TITLE
Remove UTC mode from Calendar

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#5853]
This property makes the calendar 2x complex, almost everything has to be coded again for UTC. Instead provide a demo to show how to work with UTC and potentially any time zone.

**Comment by Menecats** [comment]
The #5823 simplifies the code, you don't have to code twice because it access automatically to the UTC and non-UTC methods by using  the utc flag.

Eg:

```javascript

doSomething(): void {
    // Before
    const pm = this.utc ? this.date.getUTCHours() > 11 : this.date.getHours() > 11;
    // After
    const pm = this.getHours(this.date) > 11;

    // Before
    this.utc ? this.date.setUTCHours(13) : this.date.setHours(13);
    // After
    this.setHours(this.date, 13);
}

getHours(date: Date): number {
    if (this.utc) {
        return date.getUTCHours();
    }
    return date.getHours();
}

setHours(date: Date, hours: number): Date {
    if (this.utc) {
        date.setUTCHours(hours);
    }
    date.setHours(hours);

    return date
}
```

**Comment by Mysame** [comment]
This just completely broke my whole project, great.
You can't just pull functionality like this. An informative line in the console is definitely not enough.

I see no reason why @Menecats PR wasn't accepted. It fixes the concern of "double-logic", and allows us flexibility with timezones.

**Comment by kstruyven** [comment]
Why the hell would you remove this feature?? Is there at least a work around to have it back in UTC? Our project is UTC time only.

**Comment by sgentile** [comment]
ugh, same issue here, what happen to the utc flag ???

**Comment by mparker-ft** [comment]
guys any workarounds for this? it's broken our whole project as well

**Comment by mparker-ft** [comment]
@cagataycivici 

> Instead provide a demo to show how to work with UTC and potentially any time zone

Where can we find this demo?

**Comment by anaq1** [comment]
Broken project here as well... we use the utc flag for correct conversion of date without time part from p-calendar to LocalDate on java server. Now it's not working anymore and we have to face the "day minus one" issue. In our case the timezone has no meaning.

**Comment by mahald** [comment]
Removing such a core feature is silly. How about to provide a directive in the primeNg lib similar to anaq1 one's, but with time support ?

**Comment by MattiJarvinen-BA** [comment]
Just came through to check if I could update primeng 5 -> 7 ... apparently I can't this really sucks.

**Comment by MattiJarvinen-BA** [comment]
> Instead provide a demo to show how to work with UTC and potentially any time zone.

This was June 5, 2018... @cagataycivici could you provide that demo now that over 6 months have passed?

**Comment by kovax** [comment]
Could this be the requested example?

https://stackblitz.com/edit/how-to-handle-utc-date-in-primeng

**Comment by fitness23** [comment]
> For everyone having same problems as me, I have created a "dirty" directive to convert selected / inserted date to utc (ignoring time part). It's not very nice, but it's fast to replace utc="true" with a directive even in big project and it works. I think it can be modified to support time part in utc as well.
> 
> ```
> @Directive({
>   selector: '[useUtc]'
> })
> export class UseUtcDirective {
> 
>   constructor(@Host() @Self() private calendar: Calendar) { }
> 
>   @HostListener('onSelect', ['$event']) onSelect() {
>     this.toUtc();
>   }
> 
>   @HostListener('onInput', ['$event']) onInput() {
>     this.toUtc();
>   }
> 
>   private toUtc(){
>     this.calendar.value = new Date(Date.UTC(this.calendar.value.getFullYear()
>       , this.calendar.value.getMonth()
>       , this.calendar.value.getDate()
>       ,0, 0, 0));
>     this.calendar.updateModel(this.calendar.value);
>   }
> }
> ```
> 
> To apply replace
> `<p-calendar utc="true" ...`
> with
> `<p-calendar useUtc ...`

Thanks for this. What are we importing as Calendar in the constructor?

**Comment by SudhakarSanagar** [comment]
Hi,

Below Solution Worked For me.
localToUtc(date: Date): Date {
		if(date == null) {
			return null;
		} else {
			return new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate(),  date.getHours(), date.getMinutes(), date.getSeconds()));
		}
	}

**Comment by singhamit0002** [comment]
Hi @fitness23 Fron where you are including -calendar: Calendar     ?

**Comment by ccit-spence** [comment]
Where is the demo? " Instead provide a demo to show how to work with UTC and potentially any time zone"

**Comment by carcigenicate** [comment]
The best way I've found to avoid this is to avoid `Date` objects altogether. If you have two ISO strings, just pass them as a string to the model. If you have a `range`-type calendar, do

```html
<p-calendar
    [(ngModel)]="dateModel"
    selectionMode="range"
    dateFormat="yy/mm/dd"
></p-calendar>
```

```typescript
const primeNgFormattedStart = moment.utc(startIso, moment.ISO_8601).format('YYYY/MM/DD');
const primeNgFormattedEnd = moment.utc(endIso, moment.ISO_8601).format('YYYY/MM/DD');
dateModel = `${primeNgFormattedStart} - ${primeNgFormattedEnd}`
```
Where `startIso` and `endIso` are ISO strings.
