### ISSUE TITLE
Jumping p-dialog

### ISSUE THREAD

**Issue by filip12345678910** [primefaces/primeng#5855]
I have p-messages inside p-dialog and I can't close the dialog easily, because it jumps:
https://stackblitz.com/edit/github-xlugfq-q8zpyl

**Comment by filip12345678910** [comment]
I think it's confused about its height and it jumps when it tries to re-center vertically.

**Comment by JSeed** [comment]
Setting the `autoAlign` input to `false` should stop your window from moving after content changes:
https://stackblitz.com/edit/github-xlugfq-vfai6u 

The [documentation](https://www.primefaces.org/primeng/#/dialog) seems to suggest that `false` is the default value for this input, which is inconsistent with this behaviour.  Not sure if it is a mistake in the documentation or a bug in the code

**Comment by filip12345678910** [comment]
Thanks for the workaround. But "moving after content changes" - it doesn't move after content changes, it moves after I click on it, so I think it is a bug.

**Comment by JSeed** [comment]
Oh, I see that now... not sure how I missed it, whoops. 
That definitely does look like a bug.

If you need another workaround you can display the dialog at a fixed point with the `postitionTop` input, but I definitely agree that thats not something you should have to do.

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/issues/5387
