### ISSUE TITLE
p-dropdown: focus() method does not expand dropdown

### ISSUE THREAD

**Issue by lebnic** [primefaces/primeng#5857]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/primeng-issues-5857

**Current behavior**

calling the .focus() method on a dropdown does focus on the element, but it does not expand dropdown

**Expected behavior**

Dropdown sould also be expanded, as if it was clicked on

**Minimal reproduction of the problem with instructions**

In plunkr, observe different behavior when clicking on button vs clicking directly on dropdown

**What is the motivation / use case for changing the behavior?**

In order to improve UX, I want to add a "click-me" button next to a dropdown. This button serves as a signifier and shall expand the dropdown.

**Comment by lebnic** [comment]
Here's a workaroud (https://stackblitz.com/edit/github-g2rhqe-efbbab?file=src%2Fapp%2Fapp.component.html)
```
dropdownElement.focus()
```
becomes
```
dropdownElement.container.click()
```

**Comment by cagataycivici** [comment]
No plans to open it on focus, you can use alt+down shortcut though.

**Comment by cheezyXx** [comment]
is it possible open dropdown by default?
