### ISSUE TITLE
ptable validation style

### ISSUE THREAD

**Issue by ranjeetsinghr** [primefaces/primeng#5859]
recently switched to new p-table and facing two issues.

1.  invalid cell mark whole row dirty/touched.
2. error on a call disable all rows in table disabled untill error is fixed in one cell.

template:
<td pEditableColumn>
							<div [formGroupName]="rowData['tablename']">
								<p-cellEditor>
									<ng-template pTemplate="input">
										<input pInputText type="text" formControlName="primaryindex" >
									</ng-template>
									<ng-template pTemplate="output">
										
										{{editCatalogForm.controls[rowData['tablename']].controls['primaryindex'].value}}
									</ng-template>
								</p-cellEditor>
							</div>
							<div class="form-control-feedback"	 *ngIf="editCatalogForm.controls[rowData['tablename']].controls['primaryindex'] !=undefined && editCatalogForm.controls[rowData['tablename']].controls['primaryindex'].invalid">
								<p *ngIf="editCatalogForm.controls[rowData['tablename']].controls['primaryindex'].errors.pindexval"
								   class="textColorRed"> Select correct parent job type </p>

							</div>

						</td>

component:

  initEditCatalogForm() {
		const control = <FormGroup>this.editCatalogForm;
		for (const uploadCatalogVal of this.uploadedcatalog) {
		//	console.log("initForm  editCatalogForm --> " +  uploadCatalogVal.tablename);
			const uploadCatalogFb: FormGroup = this.fb.group({
				//tablename: [uploadCatalogVal.tablename, Validators.required],
				indextyp: [uploadCatalogVal.indextyp,this.validateIndexTyp()],
				primaryindex: [uploadCatalogVal.primaryindex, [this.validatePrimaryIndex()]],
				processtyp: [uploadCatalogVal.processtyp,[Validators.required]],
				plantarea: [uploadCatalogVal.plantarea,[Validators.required]],
				groupid: [uploadCatalogVal.groupid],
				//appName:[uploadCatalogVal.appName,[Validators.required]],
				//dbName: [uploadCatalogVal.dbName]
				}
			);
			control.setControl(uploadCatalogVal.tablename, uploadCatalogFb);
		}
	}

**Comment by cagataycivici** [comment]
You are using a deprecated theme, please migrate to newer ones.
