### ISSUE TITLE
Add disabled property to SelectItem interface

### ISSUE THREAD

**Issue by jpicklyk** [primefaces/primeng#586]
Would you please consider allowing the SelectItem class to specify a 'selectable' variable?  The use case would be for the first item I want to show a default value of "Select One Item" or something to that effect.  I don't want the user to be able to select that option in dropdowns etc.

Thanks

**Comment by caebeman** [comment]
SelectItem is actually an interface, so you can just implement the interface in a class that you create and then use that class for the dropdown.

**Comment by jpicklyk** [comment]
Yes, sure I can easily implement that interface but I can't change the component's behaviour to not select or highlight those items.  Maybe I'm missing something, but I don't see a way to alter the selectItem(event, item) function within the component to implement that logic.  If there is a better way to accomplish this, I'll be happy to close this FR.

**Comment by caebeman** [comment]
There is a disabled field for dropdowns. The documentation is kind of lacking for a lot of components, but if you look through you source you can find all of them The signature is:

@Input() disabled: boolean;

**Comment by jpicklyk** [comment]
Thanks for the suggestion, I did look at the dropdown component code and couldn't find a good way to do this hence the Feature Request.

Your suggestion won't work as it disables the component completely.  You can't even click on the dropdown if the component is disabled.
What I am looking for is similar behaviour to the JSF dropdown component where I am able to specify if the SelectItem is selectable or not.

e.g. Items:
- Please select one <-- Not selectable at all
- Item 1
- Item 2
- Item 3

**Comment by caebeman** [comment]
I only briefly looked through the source Looking at the component more indepth I don't really see a way to achieve what you want to do. I agree that this would be a very nice feature to have.

**Comment by upstreamosGH** [comment]
I agree with you both. Disabled Dropdown's options, which means disabled property on SelectItem, would be a great improvement. It's a quite big change because it would also affect Listbox, MultiSelect and SelectButton ;-)

**Comment by raxkaynan** [comment]
Any status update on this?

**Comment by bomberblue07** [comment]
This would be great to have. +1

**Comment by cagataycivici** [comment]
We can add itemDisabled property to SelectItem interface.

**Comment by Samisama** [comment]
It would be nice to add a style or styleClass property to. 
I can't figure out how to style options inside my dropdown (for example I would like to change the text color of a few items but not all options of the dropdown)

**Comment by andriy101** [comment]
I wrote a little workaround to add support for disabled options: https://stackoverflow.com/questions/43873162/prime-ng-dropdown-disable-certain-selectitems/45362622#45362622

**Comment by mconner** [comment]
Is there some way to work around this for SelectButton?  I tried writing get/set for the selected item, and prevent selection if disabled, It still highlights the clicked button.  Not being able to disable an option makes the use of this very limited.

**Comment by j1j** [comment]
+1. I'm running into this issue all the time. The use case is as follows: add item from a list of items, already added items(duplicate) are not allowed. Yes, already added items can be removed from the add list but from the users point of view it's unclear what is happening. Disabling instead of removing would provide additional clarity to the user what is happening.

**Comment by carlos-ruiz-bravo** [comment]
+1. I currently have a form array with dropdowns, will be useful to disable items previously selected with this.

**Comment by skormel** [comment]
+1. We need this feature to be compatible with SelectButtons.

**Comment by paveldayneko** [comment]
Voting for having it for MultiSelect +1

**Comment by paulswan** [comment]
SelectItem now has styleClass, icon and title but still no disabled property.  Any idea when this will happen as it's clearly something that many people need?

**Comment by hemanthbs12** [comment]
Agree @paulswan, disabled property is very much needed. or is there an alternative way of doing with?

**Comment by skormel** [comment]
@hemanthbs12 we solve it by using two buttons with padding 0px and we control enable and disabled individually based on the state of the other.

@cagataycivici another interest functionality is an event triggered before selectbutton change state occurs, so we can block the change of selected option.

**Comment by cagataycivici** [comment]
Set to 6.0, although I personally think not displaying the option would be a better UX.

**Comment by michael-veitch** [comment]
That sounds great @cagataycivici, do you have an idea when release is due? I've looked through the roadmap and can't find much, I also see the 6.0 milestone has no current due date.

**Comment by cagataycivici** [comment]
It will be synced with Angular 6 which I believe will be before Ng-Conf, mid april.

**Comment by hemanthbs12** [comment]
@cagataycivici Any idea when 6.0 will be out.

**Comment by cagataycivici** [comment]
SelectItem API gets disabled prop with 6.0.2 and now we're updating components such as ListBox that should utilize it;

https://github.com/primefaces/primeng/issues/6145

Each component that supports it has its own ticket.
