### ISSUE TITLE
DataTable doesn't clear it's dragging status on dragend

### ISSUE THREAD

**Issue by mroskamp** [primefaces/primeng#5864]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-exw6op

**Current behavior**
If you drag a column header and end the drag without dropping it on another header, the datatable doesn't clean up its dragging state, so the datatable appears as a valid drop zone for other draggable items.

**Expected behavior**
Ending a drag should always clean up its dragging state. This could likely be done with a simple dragend handler on the pColumnHeaders.

**Minimal reproduction of the problem with instructions**

1. Drag the button and try to drop it on a column in the data table. Notice how it's not valid.
2. Now, drag "Column 1" and, without dropping it, drag over the other columns. Notice how the indicators show that they're valid drop targets.
3. Still dragging "Column 1," move up to the page title and drop it. This is simply to stop dragging, without changing the column ordering.
4. Now, drag the button again and try to drop it on a column header. Notice how it appears as valid. In the browser console, you'll likely see a related error, too.

**What is the motivation / use case for changing the behavior?**
Showing the data table as a valid drop zone leads to a poor user experience. Additionally, the errors in the console make it more difficult to identify legitimate issues.

* **Angular version:** 5.2.10

* **PrimeNG version:** 5.2.6

**Comment by cagataycivici** [comment]
Sorry but p-dataTable is not maintained anymore in favor of p-table.
