### ISSUE TITLE
problem with p-tableRadioButton

### ISSUE THREAD

**Issue by Alebqto** [primefaces/primeng#5865]
When selecting a row as seen in the photo (Row Id 12), the entire table is selected.

[img]https://preview.ibb.co/h6UMno/row.jpg[/img]

Codigo:

<p-table [value]="data['entities'].values"  [(selection)]="objSelectd" dataKey="vin" [paginator]="true" [rows]="10">
						<ng-template pTemplate="header">
							<tr *ngFor="let th of data['entities'].header">
								<td width="5%"></td>
								<td *ngFor="let t of th">{{t}}</td>
								<td> Actions </td>
							</tr>
						</ng-template>

						<ng-template pTemplate="body" let-rowData >
							<tr [pSelectableRow]="rowData[1]">
								<td>
									<p-tableRadioButton  [value]="rowData[0]"></p-tableRadioButton>
								</td>
								<td *ngFor="let col of rowData">
									{{col}}
								</td>
							<td><a class="btn btn-light">Edit</a></td>
							</tr>
						</ng-template>
						<ng-template pTemplate="summary">
							<div style="text-align: left">
								Selected row: {{objSelectd}}
							</div>
						</ng-template>
					</p-table>

**Comment by JacobSiegle** [comment]
Whatever [pSelectableRow]="rowData[1]" and [value]="rowData[0]" are is probably always the same value. 

This is a question not an issue with the framework from a quick look. Try https://forum.primefaces.org/ if you need further assistance. Otherwise make a stackblitz if you still believe this is an error with the framework and not your code.

**Comment by flowfreeconsumer** [comment]
Can you explain more on this , what is wrong and what need to be done in this not an issue with the framework thing..

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.

**Comment by Justin020930** [comment]
I have the exact same problem. If I click on the radiobutton the hole radiobuttons will be selected.
