### ISSUE TITLE
p-dropdown with filter marked as touched onFocus

### ISSUE THREAD

**Issue by ktriek** [primefaces/primeng#5866]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
[Stackblitz](https://stackblitz.com/edit/github-k6rvma?file=src/app/app.component.html)

**Current behavior**
p-dropdown with filter marked as touched onFocus

**Expected behavior**
p-dropdown should be marked as touched onBlur (the default Angular behavior).

**Minimal reproduction of the problem with instructions**
Focus on a p-dropdown that has the filter enabled

**What is the motivation / use case for changing the behavior?**
Forms validation:
`<div *ngIf="fdd.touched && fdd.hasError('required')" class="invalid-feedback">Required</div>`, p-dropdown shouldn't show the error on first time focus.

**Please tell us about your environment:**
 Any

* **Angular version:** 5.X
6.X

* **PrimeNG version:** 5.X
5.x, 6.beta

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
 Any
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Any
* **Node (for AoT issues):** `node --version` =   
Any

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
