### ISSUE TITLE
PrimeNg Growl - Icons not visible after upgrading to Angular 6.0.4

### ISSUE THREAD

**Issue by lucabrasi83** [primefaces/primeng#5868]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
After upgrading to angular/core 6.0.4 and primeng 6.0.0-beta1 , the growl notification doesn't have the close and notification type icons as per below screenshot:

![screen shot 2018-06-07 at 08 03 58](https://user-images.githubusercontent.com/21274414/41072674-846a9666-6a29-11e8-9db6-029ea3b97599.png)

Tried to fallback to primeng 5.2.7 but issue is still there

**Expected behavior**
Icons should still be visible. This issue was not present on previous angular versions.

**Minimal reproduction of the problem with instructions**

* **Angular version:** 5.X
6.0.4

* **PrimeNG version:** 5.X
6.0.0-beta1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all

**Comment by ctrl-brk** [comment]
Did you install primeicons?

**Comment by lucabrasi83** [comment]
Thanks, should have looked at the blog post mentioning primeicons replacing font-awesome.

After installing it and added "node_modules/primeicons/primeicons.css" in angular.json then icons are displayed now.
