### ISSUE TITLE
OverlayPanel doesn't close on iPhone

### ISSUE THREAD

**Issue by Ajax-ua** [primefaces/primeng#5870]
When trying to close overlay panel clicking outside of panel on iphone (ios 11.x) it doesn't close.
While debugging I found out that document click listener isn't triggered for some reasons:
```
    bindDocumentClickListener() {
        if(!this.documentClickListener && this.dismissable) {
            this.documentClickListener = this.renderer.listen('document', 'click', () => {
                if(!this.selfClick && !this.targetClickEvent) {
                    this.hide();
                }
                
                this.selfClick = false;
                this.targetClickEvent = false;
                this.cd.markForCheck();
            });
        }
    }
```
Maybe it is related to 'click' event. Tried to replace event with 'touchend' and it worked properly for iphone.

**Comment by opetriienko** [comment]
Same for me. Can be reproduced even here: https://primefaces.org/primeng/#/overlaypanel

**Comment by opetriienko** [comment]
It seems it could be related to this issue: https://github.com/primefaces/primeng/issues/2380
