### ISSUE TITLE
New TreeTable programatic expand doesn't work without reassignment

### ISSUE THREAD

**Issue by JacobSiegle** [primefaces/primeng#5872]
PrimeNG - 6.0.0-Beta1

I have a drop down and the new tree table. 

If an item is selected in the dropdown I find the path from the root of the tree table to the selected item. 

In order for the user to quickly see / jump to the selected itemin the dropdown all nodes along that path must be expanded. 

In the previous version of the tree table setting expand on the node to true would open up the table. In the most recent version setting expand will change the state of the chevron but not open the nodes.

The nodes state will only be opened obj passed into the tree table is reassigned.

I'll try to make a stackblitz if I get more time.

```
dropDownSelected(event: any): void {
	if (event.value != null) {
		let find: string = event.value.label;
		let nodePath: TreeNode[] = this.findNodePathFromRoot(find, this.model[0], []);
		for (let node of nodePath) {
			node.expanded = true;
		}
                
                // Must be added in new tree table to have nodes open!!!
		this.model = [... this.model];
	}
}
```

**Comment by cagataycivici** [comment]
This is expected and documented at change detection section.

**Comment by john-melin** [comment]
node.expanded = true;
tree.cd.detectChanges()

does noting
