### ISSUE TITLE
G-Map - Mouse click on the marker, map is moving

### ISSUE THREAD

**Issue by nsksaisaravana** [primefaces/primeng#5873]
Mouse click on the below marker, the map is moving a little bit but the same is working fine in Circle and Polyline.

this.overlays = [
            new google.maps.Marker({position: {lat: 36.879466, lng: 30.667648}, title:"Konyaalti"}),
            new google.maps.Marker({position: {lat: 36.883707, lng: 30.689216}, title:"Ataturk Park"}),
            new google.maps.Marker({position: {lat: 36.885233, lng: 30.702323}, title:"Oldtown"})
]

**Comment by nsksaisaravana** [comment]
Can we able to assign ICON or Image for the marker? Similar to Circle, Polyline. 

My requirement is based on the Property type e.g. Commercial, Hospital I have to place the marker with different ICON.

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
