### ISSUE TITLE
Filter doesnt work properly with rowexpansion in turbotable

### ISSUE THREAD

**Issue by sarikafiorano** [primefaces/primeng#5875]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Waiting Time: ~8 weeks.

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-yoxwkv?file=src/app/app.component.ts

**Current behavior**
Using a table with rowgroup(toggleble, rowspan) and filter shows odd behaviour.. In rowspan case, when filtering is done, the entire column (based on grouping is done.. In this case 'brand') disappears.

**Expected behavior**
Even when filtering is done, all the columns should be visible

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Centos7, VSCode

* **Angular version:** 5.X
Angular Verson : 5.2.7

* **PrimeNG version:** 5.X
PrimenNG : 5.2.5

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypseScript

* **Node (for AoT issues):** `node --version` =   
Node : V6.11.3

**Comment by cagataycivici** [comment]
I think you need to call updateRowGroupMetaData at onFilter as well.
