### ISSUE TITLE
p-table sorting doesn't work with [pSortableColumn]

### ISSUE THREAD

**Issue by feder89** [primefaces/primeng#5876]
in p-table column can be sorted with pSortableColumn="field" without square brackets in 6.0.0-beta1. I noticed it migrating from 4.3.0 to 6.0.0 version and migrating from p-dataTable to p-table

**Comment by ctrl-brk** [comment]
When using square brackets use single quotes around your field name. [pSortableColumn]="'field'". Or make the `field` a member of your class.

**Comment by cagataycivici** [comment]
Invalid issue.
