### ISSUE TITLE
DataTable - How to Refresh the Data Source

### ISSUE THREAD

**Issue by ammar91** [primefaces/primeng#588]
In my datatable, there is a delete button in each row. When I press, it delete the object from the original data source but there is no change on ui. I'm wondering if there is a way to refresh the data source of table?

**Comment by seandsky** [comment]
two-way binding with angular2? Maybe you'd better copy your code here.

**Comment by ammar91** [comment]
Below is my code, item indeed removed from my data source but there is no change on ui.

```
<p-dataTable [value]="invoices | invoiceByCompany : selectedSite.id | invoiceByStatus : false"
                     [responsive]="true"
                     [contextMenu]="cm"
                     expandableRows="true">
<p-column header="Actions" [style]="{'width': '90px'}">
                <template let-currentInvoice="rowData">
                    <a style="color:red; cursor:pointer;" (click)="deleteInvoice( currentInvoice)"><i class="glyphicon glyphicon-remove"></i></a>
                </template>
</p-column>
</p-dataTable>
```

```
deleteInvoice(invoice: IInvoiceList): void {
      let invoiceToDeleteIndex: number = 0;
       invoiceToDeleteIndex = this.invoices.findIndex((item: IInvoiceList) => item.userName == invoice.userName);
        this.invoices.splice(invoiceToDeleteIndex, 1);
    }
```

**Comment by ammar91** [comment]
Any thoughts?

**Comment by ammar91** [comment]
similar issue when I do a custom sort. Changes not reflecting on the ui but the table data source changed when I do console log.

**Comment by jesseoren** [comment]
I believe the issue is with the Pipes you are using.  If they are custom pipes, you can go in and change the @Pipe decorator to include:  pure: false

I believe there may be a performance penalty for this, but I am not sure.

**Comment by vrcod** [comment]
I have a similar problem - how do I force a table refresh/reload? At the moment I'm using a hacky solution found [here](http://stackoverflow.com/questions/40077150/how-to-programmaticaly-trigger-refresh-primeng-datatable-when-a-button-is-clicke), but then the pagination doesn't refresh, so it's not exactly working.

**Comment by Mrtcndkn** [comment]
Please use forum for questions and support requests instead of issue tracker.
