### ISSUE TITLE
Checkboxes and Radio Buttons not rendering properly in Angular 6/PrimeNg 6

### ISSUE THREAD

**Issue by maplion** [primefaces/primeng#5883]
```
[x] bug report 
```

**Current behavior**
Upgraded from Angular 5.2.6 => 6.0.4 and primeng 5.2.4 => 6.0.0-beta.1.  While the checkboxes and radio buttons still render, select, and highlight, they fail to render the actual check within the box when selected, or the dot within the radio button when selected.  This was tested in `Firefox 60.0.1 (64-bit)`, `Microsoft Edge 42.17134.1.0`,  and `Chrome 66.0.3359.181 (Official Build) (64-bit)`.  No console errors are shown in the process of selecting (or deselecting in the case of the checkbox).

**Expected behavior**
I expect to see the checkbox and the dot of the radio button rendered.

**Minimal reproduction of the problem with instructions**
Create a checkbox or radio button in Angular 6.0.4 with primeng 6.0.0-beta.1 and check the box or make a selection to see that the check and/or dot are not being rendered.

**Please tell us about your environment:**
```
Angular CLI: 6.0.8
Node: 8.9.4
OS: win32 x64
Angular: 6.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3
```

Is anyone else experiencing this behavior and/or knows of a workaround?  Thank you.

**Comment by maplion** [comment]
I was able to resolve the checkbox issue by following the directions given by Flat Badger here: https://stackoverflow.com/questions/50802045/checkboxes-and-radio-buttons-not-rendering-properly-in-angular-6-primeng-6/50818071#50818071 or here: https://www.npmjs.com/package/kukko_primeng, which in short is to install primeicons and include the css in the styles within the angular.json.

Unfortunately, this did not resolve the radio buttons and they are still an issue; it could be there are still some icons missing since it is still in beta, but I am not certain.

**Comment by maplion** [comment]
If you go here: primefaces.org/primeng/#/radiobutton the radiobuttons don't fill there either. Perhaps this is intended? If it is, I think it is a terrible idea, but maybe my radio buttons are working just fine; it's just that they made a glyph without a center in it.

**Comment by maplion** [comment]
Hearing back from PrimgNg and from their point-of-view, they don't see a problem.  I am unclear if they don't see a problem because they're seeing what was intended as working as intended, or if they are seeing something different from me -- still some communication breakdown in that regard.

**Comment by maplion** [comment]
The issue was related to us using the Ultima theme and it overriding the glyph; it was resolved by updating the theme files with the newly-released Ultima sass files.

**Comment by jrcayetano** [comment]
How can do that?

**Comment by maplion** [comment]
@jrcayetano Copy the files in the assets/sass folder from your theme to your project (all of the files that start with an underscore) and that will replace all of the font awesome references.
