### ISSUE TITLE
p-messages from MessageService doesn't show messages in different severity css classes, if added messages has different severity.

### ISSUE THREAD

**Issue by sunnyyadav100** [primefaces/primeng#5884]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/github-fp33op?file=src%2Fapp%2Fapp.component.ts

**Current behavior**

this.messageService.add({severity : 'error', summary: 'Error !', detail: 'error detail.'});
this.messageService.add({severity : 'success', summary: 'Task !', detail: 'task has been completed.'});

As per above code, both messages show in red color box. As per code https://github.com/primefaces/primeng/blob/master/src/app/components/messages/messages.ts , ng-class is applied from first message.

**Expected behavior**

Messages should be group by as per severity level.

this.messageService.add({severity : 'error', summary: 'Error !', detail: 'error detail.'});
this.messageService.add({severity : 'success', summary: 'Task !', detail: 'task has been completed.'});
this.messageService.add({severity : 'error', summary: 'Error 2!', detail: 'error detail.'});
this.messageService.add({severity : 'success2', summary: 'Task 2!', detail: 'task has been completed.'});

means 
red color box should show 'Error !', 'Error 2!' messages 
and 
green color box should show 'Task !', 'Task 2!' messages.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.X

Angular 6.0.3

* **PrimeNG version:** 5.X

Prime Ng 6.0.0-alpha.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
I think you need to use different p:messages with keys so match severities.

**Comment by Jorg-w** [comment]
Could you elaborate on this?

I'm experiencing the same issue as described above. I also noticed that your documentation has this issue. When you go to https://www.primefaces.org/primeng/#/messages, select a basic message first and then click on the 'Use Service' button it will be styled in the same way as the basic message that is already displayed. In the code however the 'Use Service' button submits a success message and so I would expect that it is a green message.

Am I (and the documentation code) using the service wrong or is this a bug?

**Comment by jasonschmedes** [comment]
Why was this closed? Can you not stack different message types now? The bug is in the demo.

**Comment by koesper** [comment]
This issue is still there, but the workaround with different keys is rather ugly:

<p-messages enableService="true" key="success"></p-messages>
<p-messages enableService="true" key="info"></p-messages>
<p-messages enableService="true" key="warn"></p-messages>
<p-messages enableService="true" key="error"></p-messages>

and then each message with the same value in severity and key
 this.messageService.add({severity: 'warn',  key: 'warn', summary: 'app.component', detail: 'via sevice'});

if i'm not mistaken, the toast component does not have this problem?
