### ISSUE TITLE
placeholder style

### ISSUE THREAD

**Issue by gjhkael** [primefaces/primeng#5888]
how to set the placeholder's stype of pInputText.
the font of placeholder is similar with others. you can see the following image.

![1528771384452](https://user-images.githubusercontent.com/10809317/41267271-7527cb9e-6e2d-11e8-98ed-9406d7ca68c5.jpg)

**Comment by Pterrat** [comment]
Hello,

You can use ::placeholder pseudo element in your css

https://css-tricks.com/almanac/selectors/p/placeholder/

**Comment by gjhkael** [comment]
works for me. thanks.
