### ISSUE TITLE
Accessibility: [p-dropdown] Focus is moving on to hidden elements when windows narrator is running in scan mode.

### ISSUE THREAD

**Issue by paraskt** [primefaces/primeng#5889]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Waiting Time: ~8 weeks.

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
When the narrator is in scan mode, the focus moves to a couple of hidden elements before moving to the drop down.

**Expected behavior**
Focus should just move to the drop down. It should not move to hidden elements.

**Minimal reproduction of the problem with instructions**
Goto https://www.primefaces.org/primeng/#/dropdown.
Run narrator in scan mode. Try to navigate to the dropdown using arrow keys.
Notice that focus moves to p-dropdown's hidden elements.

**What is the motivation / use case for changing the behavior?**
Scan mode is the preferred mode to navigate through web page when using windows narrator. When the focus moves to hidden item, it confuses the users.

**Please tell us about your environment:**

* **Angular version:** 5.X
 5.1.3

* **PrimeNG version:** 5.X
5.2.5

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome, edge
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
