### ISSUE TITLE
Calendar shows NaN when clicking "Now" after manually choosing a date/time

### ISSUE THREAD

**Issue by mattgaffin** [primefaces/primeng#589]
Current behavior

On the Calendar, if you set a date/time manually first, then click Now, it sets the time to NaN. Also, occasionally it seems like Now just fails to set the date/time altogether. Not reliably reproduceable though.

It appears to be the same as the issue reported on the forums (which I replied to).
http://forum.primefaces.org/viewtopic.php?f=35&t=46168&p=143968&hilit=calendar+defect#p143968

Expected/desired behavior

Clicking Now should update the date/time correctly regardless of whether a manual date has first been set.

Reproduction of the problem
1. Open the Calendar
2. Click "Now" (should work correctly)
3. Select a date AND time manually
4. Click "Now"
5. Time shows NaN

Angular version: 2.0.0-rc.4 (also happened on rc.3)

Browser: [Chrome 51.0.2704.103 (Official Build) m (64-bit)]

Language: [TypeScript]

**Comment by Mrtcndkn** [comment]
It seems i cant replicate your issue i opened calendar then manually selected date and time than i clicked Now and it shows me the current date and time how can i replicate it?

**Comment by mattgaffin** [comment]
Here is how I have my calendar setup.

`<p-calendar  [(ngModel)]="date"
                showAnim="slideDown"
                [showIcon]="true"
                (onSelect)="onSelect($event)"
                dateFormat="mm/dd/yy"
                timeFormat="hh:mm tt" 
                timeControlType="select" 
                [horizontalTimeControls]="true"></p-calendar>`

1.) Click the calendar icon to open it.
2.) Click "Now". (Assuming that changes the currently selected date)
3.) In the Time dropdown, select a different hour.
4.) Click "Now" again.
 
The value of the calendar should now be mm/dd/yy aN:aN am

**Comment by names144** [comment]
I am also experiencing this problem with the calendar component. This seems to be an issue with the timepicker addon for jQuery UI.

See: [https://github.com/trentrichardson/jQuery-Timepicker-Addon/issues/845](url)

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
