### ISSUE TITLE
[calendar] disabled inputs can be deleted / backspaced in MS Edge

### ISSUE THREAD

**Issue by Mysame** [primefaces/primeng#5892]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**

https://github-sy2nls.stackblitz.io

**Current behavior**
Possible to delete the value of a disabled p-calendar

**Expected behavior**
Delete / backspace should do nothing.

**Minimal reproduction of the problem with instructions**
Open the stackblitz ( https://github-sy2nls.stackblitz.io ) in Edge
Select the date in the p-calendar and press backspace / delete

* **Angular version:** 6.X

* **PrimeNG version:** 6.X

* **Browser:** Microsoft Edge

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG and your stackblitz example. If the issue still persists with the new version please create a new issue with our stackblitz template.
