### ISSUE TITLE
p-message severity "warn" shows no icon (primeicons)

### ISSUE THREAD

**Issue by Laurensvdw** [primefaces/primeng#5894]
**I'm submitting a ...** 
```
[ x] bug report 
[ ] feature request
[ ] support request 
```
**Current behavior**
Message with sevirity "warn" does not show an icon. A wrong icon class is being added to the component being "pi-ex", this should be "pi-exclamation-triangle" as noted in the [documentation of the icons](https://www.primefaces.org/primeng/#/icons) 

**Expected behavior**
Message with serverity "warn" should show an icon

**Minimal reproduction of the problem with instructions**
It is visible on [the documentation page's messages section](https://www.primefaces.org/primeng/#/messages)
<p-message severity="warn" text="Are you sure?"></p-message>

* **Angular version:**
6.0.0

* **PrimeNG version:**
primeng 6.0.0-beta.1
primeicons 1.0.0-beta.7

**Comment by ctrl-brk** [comment]
Works for me in Omega theme
