### ISSUE TITLE
TurboTable shows no Loading Icon or a square 

### ISSUE THREAD

**Issue by MarMic1** [primefaces/primeng#5895]
**I'm submitting a Bug
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
TurboTable loading feature doesn't work. It only shows the blocked UI or a square. 

	<p-table [value]="exams" [loading]="loading">
		<ng-template pTemplate="header">
			<tr>
				<th>SubmissionDate</th>
				<th>Name</th>
			</tr>
		</ng-template>
		<ng-template pTemplate="body" let-exam>
			<tr>
				<td>{{exam.submissionDate}}</td>
				<td>{{exam.name}}</td>
			</tr>
		</ng-template>
	</p-table>

**Comment by ctrl-brk** [comment]
Did you install primeicons?

**Comment by MarMic1** [comment]
@ctrl-brk  
primeicons version 1.0.0-beta.7 is installed.

simply primeicon does not work either.

`<i class="pi pi-spin pi-spinner" style="font-size: 3em"></i>`

tested with primeng version 5.2.6 & 6.0.0-beta.1

**Comment by ctrl-brk** [comment]
Do you also load the primeicons css?

**Comment by MarMic1** [comment]
After loading the icons and adding loaders for eot/ttf it's working now thanks! @ctrl-brk
