### ISSUE TITLE
Access to ScrollableView from Turbotable instance

### ISSUE THREAD

**Issue by mlakhara** [primefaces/primeng#5897]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
I am developing customizations on top of turbotable for some virtualscrolling enhancements and need access to the ScrollableView object instance to call various methods and add hooks. 

**Current behavior**
Can not access the ScrollableView instance through Turbotable instance (access using @ViewChild)

**Expected behavior**
Allow to access ScrollableView by setting it as one of the properties or a getter in Turbotable

**What is the motivation / use case for changing the behavior?**
Allow additional customization on top of the current functionality

**Please tell us about your environment:**
All

* **Angular version:** 5.X
5.4

* **PrimeNG version:** 5.X
5.4.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All
* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
It is an internal component so no plans to expose it.

**Comment by Mysame** [comment]
Too bad. Sometimes the table lacks (specific) functionality which requires access to these components.
