### ISSUE TITLE
autocomplete: dropdownMode not working as expected

### ISSUE THREAD

**Issue by c17r** [primefaces/primeng#5899]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Waiting Time: ~8 weeks.

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://github-gwojti.stackblitz.io

**Current behavior**

Not specifying `dropdownMode` causes clicking the dropdown to fire both completeMethod() and onDropdownClick()

Setting `dropdownMode` to "blank" fires only onDropdownClick but with the current query value.

**Expected behavior**

Not specifying `dropdownMode` works the same as `[dropdownMode]="blank"` which fires only onDropdownClick() with $event.query set to empty string

**Minimal reproduction of the problem with instructions**

see stackblitz above

**Please tell us about your environment:**

- Windows 7
- Visual Studio Code 1.24
- npm
- running angular's dev server

* **Angular version:** 6.0.3

* **PrimeNG version:** 6.0.0-beta.1 on stackblitze, 5.2.7 locally

* **Browser:** Chrome Version 67.0.3396.79

 
* **Language:** TypeScript 2.7.2

* **Node (for AoT issues):** `node --version` =   v8.11.1

**Comment by cagataycivici** [comment]
This is the expected behavior.
