### ISSUE TITLE
p-table: autoLayout: dropdown column filter is truncated

### ISSUE THREAD

**Issue by lebnic** [primefaces/primeng#5900]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-issues-5900

**Current behavior**

![image](https://user-images.githubusercontent.com/6682795/41310508-b1da158e-6e4f-11e8-902f-48b1cee05bf2.png)

**Expected behavior**

![image](https://user-images.githubusercontent.com/6682795/41310518-b61bf4b4-6e4f-11e8-8448-d64e172bbbaf.png)

**Minimal reproduction of the problem with instructions**

see Plunkr ...

**Comment by mehmterim** [comment]
Set attribute appendTo="body"
`<p-dropdown [options]="dropdownOptions" appendTo="body"></p-dropdown>`

**Comment by lebnic** [comment]
@mehmterim awesome, thanks, it works (https://stackblitz.com/edit/primeng-issues-5900-workaround)

@cagataycivici  Is this "bug" report still relevant ? IE. is this behavior a bug, or is it normal ?

**Comment by bogacg** [comment]
In my case, while it works, the moment table gets filtered/refreshed I see `dropdown` options next to table:
![clipboard01](https://user-images.githubusercontent.com/5073927/44148897-bfb05094-a0a2-11e8-9d0b-8802909b47b5.jpg)
![clipboard02](https://user-images.githubusercontent.com/5073927/44148906-c37eb472-a0a2-11e8-8c06-d15b9acea800.jpg)

**Comment by sK-1005** [comment]
This was helpful. Thanks.
Hello, Where I can find the complete list of attributes/properties of <p-table> like autolayout, value, etc

**Comment by cagataycivici** [comment]
You need to use appendTo to the scrolling container element if it is inside a scrolling element.

**Comment by bhagatshubham1994** [comment]
Hi, what is the solution for the above issue faced by  https://github.com/primefaces/primeng/issues/5900#issuecomment-413187312  @bogacg 

cc: @cagataycivici
