### ISSUE TITLE
[bug] Version 6.0.0-beta.1 broke FontAwesome icons

### ISSUE THREAD

**Issue by guillaumegarcia13** [primefaces/primeng#5904]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

Icon is broken (6.0.0-beta.1)
https://prime-ng-600beta1.stackblitz.io
![image](https://user-images.githubusercontent.com/2786038/41316346-664bb85a-6e92-11e8-951c-1ce82a6f1368.png)

**Current behavior**

Font awesome icons are not showing correctly (I guess font-family: FontAwesome is not applied)

**Expected behavior**

Icon is OK (6.0.0-alpha.1)
https://prime-ng-600alpha1.stackblitz.io
![image](https://user-images.githubusercontent.com/2786038/41316283-3bfc9470-6e92-11e8-832c-445688674c6e.png)

* **PrimeNG version:** 6.0.0-beta.1

**Comment by guillaumegarcia13** [comment]
Thanks for your answer!
Oops, I missed that... (not referenced in https://www.primefaces.org/primeng though, kind of hard to find) 😅

Actually, as I didn't see this problem when upgrading to 6.0.0-alpha.1, I was not expecting breaking changes between alpha and beta.

I understand the Change of plan regarding FontAwesome even though I didn't understand why it was not possible to support both font libraries as earlier (without the 'fa' class addition).

By the way, regarding PrimeIcons, this looks odd:
![image](https://user-images.githubusercontent.com/2786038/41348576-5311998c-6f0d-11e8-8b3a-37952b842874.png)

**Comment by cagataycivici** [comment]
Not a PrimeNG issue.

**Comment by DivergentEuropeans** [comment]
"Not a PrimeNG issue", well it kind of is, seeing as Prime changed how to use icons the same way (unless Font Awesome did this? Then why would PrimeNG 5 still work?). I'm sure lots of applications temporarily broke because of this change, as using the original way was easy and simple.
