### ISSUE TITLE
Accessibility: Editable Drop-down focuses twice using keyboard navigation

### ISSUE THREAD

**Issue by djpmsft** [primefaces/primeng#5905]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

An editable drop-down has two separate focuses, one for the drop-down element and one for the text-box element. This requires two tabs to move through the element

**Expected behavior**

A user should only be able to focus on the element once. 

**Minimal reproduction of the problem with instructions**

Go to the dropdown example on primeng and navigate through the second example using a keyboard https://www.primefaces.org/primeng/#/dropdown

**What is the motivation / use case for changing the behavior?**

A user navigating with keyboard navigation may get confused when they are able to focus on a single element twice. 

**Please tell us about your environment:**

Windows 10, vscode, node

* **Angular version:** 5.1.3

* **PrimeNG version:** 5.2

* **Browser:** [all]

 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
It kinda makes sense since it is a composite component with both a select and an input.
