### ISSUE TITLE
why not reduce the requests?

### ISSUE THREAD

**Issue by CK110** [primefaces/primeng#591]
## 1
http://www.primefaces.org/primeng 

 there are 494 requests,it's too slow。

![5b151783-721b-4d96-a51c-f58be3947297](https://cloud.githubusercontent.com/assets/9956098/16797775/993a9b26-491b-11e6-96dd-6fc2f207c3e4.png)

## 2
for some reson, i need  a primeng-bundle-js , i dont want to use primeng by npm , i  want  to use it  likes ` <script src ='primeng-bundle-js '> `

What should I do ？

**Comment by Mrtcndkn** [comment]
We are aware of this situation and reviewing about solutions systemjs offers a solution for this and more commonly there is webpack but we are not sure yet i will keep you up to date about this.

**Comment by Mrtcndkn** [comment]
@CK110 I think the problem is solved now live showcase is now using webpack and its pretty fast according to the systemjs.
