### ISSUE TITLE
Editor adds unexpected breaklines

### ISSUE THREAD

**Issue by ngirot** [primefaces/primeng#5910]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Waiting Time: ~8 weeks.

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://wmaiojvq.github.stackblitz.io/

**Current behavior**
I create a pre-filled editor, the text must contains a heading tag, for example: 
`<p>test</p><h3>heading</h3>`

Problems:
- the editor display an break line between then "p" and the "h3"
- When i edit the text, the model is changed with a `<p><br/></p>` between the "p" and the "h3"

**Expected behavior**
The spacing between the tags must be smaller, and no additional tag should appear.

**Minimal reproduction of the problem with instructions**
See stackblitz above.

It looks like it comes from the "pasteHTML" function from Quill, i can fix this behaviour by adding 
```
    clipboard: {
      matchVisual: false
    }
```
in quill modules.
(see https://quilljs.com/docs/modules/clipboard/)

**Please tell us about your environment:**
Windows 7, IntelliJ IDEA, tomcat 

* **Angular version:** 4.3.6

* **PrimeNG version:** 4.3.0

* **Browser:** Firefox 60
 
* **Language:** TypeScript

* **Node (for AoT issues):** `node --version` =   v7.10.1

**Comment by chriskali** [comment]
same issue

**Comment by cagataycivici** [comment]
You can configure this behavior using options property of Editor which passes it to Quill.

**Comment by chinmaykelkar9141** [comment]
@cagataycivici: Is matchVisual deprecated? I tried everything but it is still adding <p><br></p>. Do you know if there is any solution to this?
