### ISSUE TITLE
resetFilterOnHide, p-dropdown do not clear filters on close

### ISSUE THREAD

**Issue by sai0009** [primefaces/primeng#5915]
I have set property [resetFilterOnHide]="true" on my p-dropdown but it does not seem to be working. If I type in the filter bar, click outside of the dropdown to close it, and then enter the dropdown again, the filter I entered is still there. Same issue occurs when i type in filter bar on one popup with separate model and then after closing it filter bar in another popup has already filtered dropdown options. I thought that resetFilterOnHide would remove my filter. ClearFilter() method doesnt work too. The description on primefaces says "Clears the filter value when hiding the dropdown." I am on primeng 5.2.4

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/commit/bbd66dfd15275761be9aa3e757825d32f0f6f531

**Comment by SRKdeveloper** [comment]
In version 5.2.7 how we can reset filter on hide in dropdown?
