### ISSUE TITLE
Change the path to import MessageService

### ISSUE THREAD

**Issue by sebaiona** [primefaces/primeng#5916]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

Put MessageService in api.ts (like ConfirmationService or other ones in 'primeng/src/app/components/common' for example)

**Current behavior**

Now we have to do `import {MessageService} from 'primeng/components/common/messageservice';`

**Expected behavior**

Be able to do `import {MessageService} from 'primeng/api';`

**Comment by smitpsanghavi** [comment]
The behaviour should be similar to that of ConfirmationService which is `import { ConfirmationService } from 'primeng/api';`

**Comment by opetriienko** [comment]
+1

**Comment by cagataycivici** [comment]
Seems to be available in recent releases already.
