### ISSUE TITLE
problem using sortFunction for datatable

### ISSUE THREAD

**Issue by piontec** [primefaces/primeng#592]
I'm using datatable with custom templates for each column. I'm trying to implement the custom sortFunction, but it's not working. My function looks like this

```
sortByLinkName(event: any) {
        this.links = this.links.sort((a: Link, b: Link) => {
            let aName = this.containerNameById(a[event.field].id);
            let bName = this.containerNameById(b[event.field].id);
            if (aName < bName) {
                return -1;
            }
            else if (aName > bName) {
                return 1;
            }
            else {
                return 0;
            }
        });       
    }
```

I tried to explicitly change `links` reference by first setting it to 'null' and back to array ref after a timeout - still the table doesn't get sorted.

**Comment by cagataycivici** [comment]
Should be fixed with recent PrimeNG releases. please drop a comment if issue persists and we'll reopen.

**Comment by chihab** [comment]
```javascript
 sortValuesTest(event) {
    this.data = this.data.sort((entry1, entry2) => {
      if (entry1[event.field] < entry2[event.field]) {
        return -event.order;
      }
      if (entry1[event.field] > entry2[event.field]) {
        return event.order;
      }
      return 0;
    });
    console.table(this.data.values);
  }
```
**On browser console/debug, data gets sorted while it is not on datatable.**

If I empty data array by doing this:
```javascript
 sortValuesTest(event) {
    this.data = []; 
  }
```
rows on datatable disappear.

**Explanation**

Since sort doesn't make a copy but returns the same array (reference),  We have to return a new reference. Notice the "[..." "]" surrounding sort function call.

```javascript
 sortValuesTest(event) {
    this.data = [...this.data.sort((entry1, entry2) => {
      if (entry1[event.field] < entry2[event.field]) {
        return -event.order;
      }
      if (entry1[event.field] > entry2[event.field]) {
        return event.order;
      }
      return 0;
    })];
  }
```

PrimeNg version: 4.0.3
