### ISSUE TITLE
P-Dialog with p-footer not showing

### ISSUE THREAD

**Issue by unaor** [primefaces/primeng#5920]
After upgrade to ^6.0.0-rc.1 noticed that the footer is no longer presenting itself (separating with line from the dialog body)
documentation is not clear on what has changed and what needs to be done

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
