### ISSUE TITLE
P-Calendar Multiple  didn't remove the selected date from dates array.

### ISSUE THREAD

**Issue by selva98** [primefaces/primeng#5921]
when we are selecting date from calendar the ngModel is updating(adding date) but when we deselect the selected date the ngModel didn't update by removing date. 
In ui it was updating but in ngModel Variable it was not.
` <p-calendar selectionMode="multiple" readonlyInput="true"  dateFormat="dd/mm/yy" (onBlur)="test($event)" 
                        [(ngModel)]="dateArray" (onSelect)="onSelect($event)" [inputStyle]="{'background-color':'#949494'}"
                        [formControl]="formGroup.controls['fromDate']">
                    </p-calendar>`
Can you please help me how the remove the date selected from array.

**Comment by MohaideenIsmail** [comment]
Did you get solution on this problem ?

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
