### ISSUE TITLE
p-table: autoLayout + scrollable: column width is not accurate

### ISSUE THREAD

**Issue by lebnic** [primefaces/primeng#5922]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/primeng-issues-5922

**Current behavior**

When both `autoLayout` & `scrollable` are used on a turbotable, column width are "broken"
![image](https://user-images.githubusercontent.com/6682795/41464041-bd0021ec-7066-11e8-97db-27fa13adbbdd.png)

**Expected behavior**

Column width should be the same as usual

**Minimal reproduction of the problem with instructions**

See plunkr

**Comment by digaus** [comment]
Imo the approach primeng took is not the best but it works in all browsers. If you do will not support Edge you can use this (just set scrollable to false and manuall set the height of the .ui-table-wrapper)

```
::ng-deep .ui-table table {
    border-spacing: 0 !important;
    border-collapse: separate !important;
}

::ng-deep .ui-table .ui-table-thead > tr > th {
    border-left: 1px solid #cacaca !important;
    border-top: 1px solid #cacaca !important;
    border-bottom: 1px solid #cacaca !important;
    border-right: none !important;
}
::ng-deep .ui-table .ui-table-thead > tr > th:last-child {
    border-right: 1px solid #cacaca !important;
}

::ng-deep .ui-table .ui-table-tbody > tr > td {
    border-left: 1px solid #cacaca !important;
    border-top: 1px solid #cacaca !important;
    border-bottom: none !important;
    border-right: none !important;
}
::ng-deep .ui-table .ui-table-tbody > tr:first-child > td {
    border-top: none !important;
}
::ng-deep .ui-table .ui-table-tbody > tr:last-child > td {
    border-bottom: 1px solid #cacaca !important;
}
::ng-deep .ui-table .ui-table-tbody > tr > td:last-child {
    border-right: 1px solid #cacaca !important;
}
```

And this to the `th` element `position: sticky; z-index: 1; top: 0;`

**Comment by cagataycivici** [comment]
auto layout is not supported in scrollable tables as stated in documentation.
