### ISSUE TITLE
Resize coulmn on TreeTable with scrollable and frozen feature doesnt work

### ISSUE THREAD

**Issue by yaroslav1988** [primefaces/primeng#5924]
Good time of the day !

I'm submitting a ...
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

!!! IMPORTANT. Bug connected with newest (15.06.2018) **primeng@6.0.0-rc.1** specifically !

**Plunkr Case (Bug Reports)**
Can be easily  observed with litte  Plunkr example:
https://stackblitz.com/edit/primeng-treetable-resize-bug

**Current behavior**

1. you resize any non frozen column
2. you get exception:

```
Uncaught TypeError: Cannot read property 'querySelector' of null
    at DomHandler.findSingle (domhandler.ts:60)
    at TreeTable.onColumnResizeEnd (treetable.ts:726)
    at TTResizableColumn.onDocumentMouseUp (treetable.ts:1612)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Zone.runTask (zone.js:188)
    at ZoneTask.invokeTask [as invoke] (zone.js:496)
    at invokeTask (zone.js:1540)
    at HTMLDocument.globalZoneAwareCallback (zone.js:1566)
```

**Expected behavior**
Column resized without errors

**Minimal reproduction of the problem with instructions**

To cut it short you must use treeTable with: scrollable feature, frozenColumns feature and resizable columns feature.

For more details see little plunker exmaple mentioned [above](https://stackblitz.com/edit/primeng-treetable-resize-bug)

**What is the motivation**

The error in treetable.ts(js) is connected with the fact, that method TreeTable.prototype.**findParentScrollableView** is not respecting actual dom structure when you use frozenColumns feature. What i mean is, the class name, which method is searching, is hardcoded in source with the value of '_ui-table-scrollable-view_', but when you use frozenColumns feature there is no any element containing that class. In that case method should search for '_ui-treetable-unfrozen-view_' for example. 

So, may be there is a chance to change **findParentScrollableView** method so it would accept correct scrollable table view class name as an argument, or something like that. 

I know that issue is connected with issues #5867, #5751 but its a whole new bug and its not fixed by commit 3a71940fb7f02f93d87d313286d725af2f5ab7cd.

**Please tell us about your environment:**
Windows, VS Code, vanila npm

* **Angular version:** ^6.0.3
* **PrimeNG version:** 6.0.0-rc.1
* **Browser:** Chrome would be fine (doesnt matter actually)
* **Language:** ts es5
* **Node** v8.9.0

Thanks !

**Comment by gesselbe** [comment]
You can see the same error in the demo section for scrollable and resizable TreeTables:
https://primefaces.org/primeng/#/treetable/colresize

**Comment by yaroslav1988** [comment]
Yes, there is no 'ui-table-scrollable-view' div in demo page DOM either.
But code acts like it has to be obligatory and fails with null reference.

**Comment by dhemonik** [comment]
+1

**Comment by MishaMykhalyukCogniance** [comment]
+1

**Comment by MishaMykhalyukCogniance** [comment]
Any estimations when it will be fixed?

**Comment by cagataycivici** [comment]
Just arrived here due to number of comments, reviewing now.

**Comment by achu107** [comment]
Is this issue fixed..
