### ISSUE TITLE
Context menu runs off edge of screen

### ISSUE THREAD

**Issue by ryanwawr** [primefaces/primeng#593]
The context menu runs off the screen if you right-click too close to the right edge. I would expect both the main context menu and its sub-menus to be aware of where they are on the screen and open to the left of the cursor if there is not enough available real estate to the right. 

![context_menu](https://cloud.githubusercontent.com/assets/6531664/16805459/52b8f6bc-48de-11e6-9a71-b0ca8cb1a3db.png)

**Comment by ammar91** [comment]
Yes, I'm having same issue. I had to manually adjust the pageX and pageY property so that it open to the left of cursor.

**Comment by cagataycivici** [comment]
Resolved the contextmenu position itself, will create a new issue for the subitem positioning.
