### ISSUE TITLE
Add support to enter time by hour/minute input

### ISSUE THREAD

**Issue by StickNitro** [primefaces/primeng#5930]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**

Current behaviour only support up/down to specify the time

**Expected behavior**

Add the ability to choose how to specify the time, default using the current up/down behaviour and option to use an hour/minute text input instead

* **Angular version:** 6.0.4

* **PrimeNG version:** 5.2.7

**Comment by cagataycivici** [comment]
If more users demand it, we'll reconsider, thank you.
