### ISSUE TITLE
Please autocomple atribute to p-autoComplete tag

### ISSUE THREAD

**Issue by mrjleo198901** [primefaces/primeng#5932]
Hi, I have an issue, I have a form, in which I have manually set the properties autocomplete to 'off' in each input. The problem is that i have a p-autoComplete tag but this component doesn't has the autocomplete property like:

input type="text" autocomplete="off"

And obviously I have problems with the chrome autocomplete.

Thanks for answer me..!!

**Comment by cagataycivici** [comment]
They are always off.

**Comment by mrjleo198901** [comment]
@cagataycivici 
Hi dude, this is the problem, in my chrome version (67) the "off" value doesn't work, instead of i used the autocomplete="new-password" and that's work for me.

To solve that issue, i modified the code of this component `<p-autoComplete>` adding a new property called autocomplete bringging the users the possibility to set the value of this.

![cataga](https://user-images.githubusercontent.com/20289928/41676339-b68c4c46-748a-11e8-8741-3ea888ae648a.JPG)


Greetings,
Jorge Muñoz

**Comment by kumards** [comment]
This problem still exists. Look at this screen grab. The autocomplete attribute does not exist.
Issue #701 is back?

![image](https://user-images.githubusercontent.com/4257005/41796364-367c30c4-7634-11e8-8ea2-0aa411288fd3.png)
