### ISSUE TITLE
p-Calendar does not call updateInputfield() when updating selectionMode

### ISSUE THREAD

**Issue by Mysame** [primefaces/primeng#5933]
p-Calendar does not call updateInputfield() when updating selectionMode.

This causes graphical bugs, the input-field will still use the "range" selectionMode display `[date1] - [date2]` instead of the extended input display `[date1], [date2]`

**Comment by cagataycivici** [comment]
Current selectionMode is not reactive, if more users demand it, we'll reconsider, thank you.

**Comment by Mysame** [comment]
🙄 Thank goodness `updateInputfield()` is exposed.
