### ISSUE TITLE
Get rows that are currently visualized from TurboTable

### ISSUE THREAD

**Issue by olivermue** [primefaces/primeng#5934]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When using a TurboTable with paginator, sorting and/or filtering it should be possible to get a list of the currently visualized rows. The `paginatorleft` gives out a state, but that returns just some numbers.
So how to get a list of the currently visualized rows?

**Expected behavior**
Get a list of the visualized rows (or their indices from the provided value array). I could get the list if I would use lazy loading and doing all the stuff on my own. But the table already does all these things (when not in lazy mode) and I'd like to access this result to get knowledge about which rows are currently shown to the user.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/github-lanzsm

**What is the motivation / use case for changing the behavior?**
We show a list of users within the table and the first column contains the profile picture of the user. These pictures are loaded lazy, after the list of users is received. Currently we simple iterate this list, checking which images are missing and async call to retrieve them. But if we would have a list of 1000 users, we would load all thousand pictures, but the user can only see a part of them one at a time (and is normally not interested to see them all).
If we could get a list of the currently shown rows (or the indices from the source list), we could iterate only this list for missing pictures and filter the image requests to the rows which are currently presented.

* **Angular version:** 5.2.11

* **PrimeNG version:** 5.2.7 and 6.0.0-rc.1

**Comment by cagataycivici** [comment]
onFilter gives the visible rows as filteredValue already.
