### ISSUE TITLE
Turbo Table Column Resize Is Ignored If Smaller Than minWidth

### ISSUE THREAD

**Issue by Dragsaw** [primefaces/primeng#5937]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
1. Set [style.minWidth] for a resizeable column
1. Try to resize the column to be narrower than its min-width
Result: resize is ignored, the column has the same width as before the resize.

**Expected behavior**
The column should be resized to its min-width.

**What is the motivation / use case for changing the behavior?**
This behavior is not user friendly.

**Comment by fhljys** [comment]
Why do I still see this behavior after this change has been merged?
