### ISSUE TITLE
how to install 3rd party dependencies with System.js?

### ISSUE THREAD

**Issue by vukhanhtruong** [primefaces/primeng#594]
My System Information:
angular-cli: 1.0.0-beta.9
node: 5.10.0
os: darwin x64 
## 

"primeng": "^1.0.0-beta.9",

"primeui": "^4.1.12"

---

Here's the way I config primeui with System.js. Unfortunately, It's still not work:

```

const packages: any = {
  'jquery': {
    main: 'jquery.js',
    format: 'global',
    exports: 'jquery',
    scriptLoad: true
  },
  'primeng':{
    main: 'primeng.js',
    format: 'cjs'
   },
  'primeui':{
    main: 'primeui-ng-all.min.js',
    format: 'global',
    scriptLoad: true,
    deps: ['jquery']
   }
};


```

primeui-ng-all.min.js was created in `dist/vendor/primeui/` , but I checked the network tab in Chrome, it wasn't loaded.

Please help me. Thanks so much for your work.
Regards,

**Comment by Mrtcndkn** [comment]
Please use forum for questions and support requests instead of issue tracker.
