### ISSUE TITLE
Using an OverlayPanel with a Tree Module throws errors.

### ISSUE THREAD

**Issue by darthmolen** [primefaces/primeng#5942]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/github-6jq8nu

**Current behavior**
When using an OverlayPanel with a Tree component, if you try and toggle the overlay panel on, it throws a bunch of "offsetHeight" errors in the console.

**Expected behavior**
No errors in the console when using an Overlay Panel with Tree control.

**Minimal reproduction of the problem with instructions**

*MINIMAL DEMO*

https://stackblitz.com/edit/github-6jq8nu

**What is the motivation / use case for changing the behavior?**

we are trying to show log file content in a panel based on a tree hierarchy

**Please tell us about your environment:**
Windows OS, Latest Chrome.

* **Angular version:** 5.X

* **PrimeNG version:** 6.0
 
* **Language:** [all]

**Comment by yigitfindikli** [comment]
Hi,
It's not a bug. onNodeSelect event gives ""originalEvent and node" . You need give originalEvent to overlayPanel not the onNodeSelect Event.

Here's example for you;
https://stackblitz.com/edit/github-6jq8nu-hc7xny
