### ISSUE TITLE
Turbotable - export function to include column id (or col.field) in addition to col.header

### ISSUE THREAD

**Issue by mmlitvin** [primefaces/primeng#5944]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Use case:
- table with data is displayed on the internationalized website 
- user A from Russia exports the data, headers are exported in russian
- user B from China would like to import this data, however since headers are in russian application cannot determine what column in CSV file maps to columns in p-table

If unique id (such as col.field) could be included into the export then import would work just fine

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
