### ISSUE TITLE
Turbotable - export function - provide ability to specify a name for downloaded file

### ISSUE THREAD

**Issue by mmlitvin** [primefaces/primeng#5945]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
p-dataTable had a property **exportFilename** allowing to specify the name for downloaded file. 
p-table is missing  this feature

**Comment by sunnyyadav100** [comment]
p-table has a property `exportFilename` to define download file name as per documentation https://www.primefaces.org/primeng/#/table (Properties section).

**Comment by mmlitvin** [comment]
sunnyyadav100 you are correct. My bad. How do I close this request as invalid?

**Comment by cghislai** [comment]
you should see a close button below the comment area

**Comment by mmlitvin** [comment]
=) too obvious
