### ISSUE TITLE
Expandable table with different child columns

### ISSUE THREAD

**Issue by nsksaisaravana** [primefaces/primeng#5947]
Kindly provide an expandable table with different child columns. Please check the screenshot.

![image](https://user-images.githubusercontent.com/17681573/41698858-047e4e02-7564-11e8-9d12-85c9fb874624.png)

**Comment by yigitfindikli** [comment]
Maybe this example help you
https://stackblitz.com/edit/angular-rzu7rt?file=src%2Fapp%2Fapp.component.ts

**Comment by nsksaisaravana** [comment]
> Maybe this example help you
> https://stackblitz.com/edit/angular-rzu7rt?file=src%2Fapp%2Fapp.component.ts

Thanks, I need parent and child columns should be different, your example having the same column names for parent and child rows.

**Comment by nsksaisaravana** [comment]
@yigitfindikli Please reopen this new feature, I am waiting for a long time. For reference please check the below link.

http://ui-grid.info/docs/#!/tutorial/Tutorial:%20216%20Expandable%20grid

**Comment by yigitfindikli** [comment]
I think it was a misunderstanding. Sorry for that. Issue is reopened!

**Comment by cagataycivici** [comment]
This is already possible to implement with row expansion feature.
