### ISSUE TITLE
Add Input binding for p-inputMask to set the html attribute "autocomplete"

### ISSUE THREAD

**Issue by 4kochi** [primefaces/primeng#5948]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
The Chrome browser shows a list of values for the `p-inputMask` which were entered in the past.

**Expected behavior**
I would like to set the html attribute `autocomplete` to `off` for the underlying `input` for `p-inputMask`, so the the browser shows no autocomplete suggestions for the field.
I would be nice to have an `@Input()` binding to control the attribute `autocomplete`.

**Please tell us about your environment:**

* **Angular version:** 6.X

* **PrimeNG version:** 5.X

**Comment by bethany-dawn** [comment]
This is an even bigger issue for the autocomplete component, as it hides results.
