### ISSUE TITLE
Dialog crashing after being dragged, closed, and reopened in Safari

### ISSUE THREAD

**Issue by dinohorvat** [primefaces/primeng#5949]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
You can see your bug on your website as well
https://primefaces.org/primeng/#/dialog

**Current behavior**
When you click on Show button, the dialog is displayed properly. Now when it's opened, try dragging it around the screen and then close it. Open it again and it will be gone, but the UI will remain blocked.

**Expected behavior**
The dialog shouldn't close on its own after previously being dragged around and closed. 

**Minimal reproduction of the problem with instructions**
1) Open https://primefaces.org/primeng/#/dialog
2) Click on `Show` button
3) Drag the dialog around the screen
4) Close it
5) Open it again

* **Angular version:** 6.0.0

* **PrimeNG version:** 6.0.0-beta.1

* **Browser:** Safari 11.0.3

**Comment by taylormartin-soltech** [comment]
I'm experiencing the exact same issue in Safari. It appears to have something to do with the way Safari is handling animations on the dialog. For now, we are using the code below as a temporary workaround. We are adding this as a styleClass on all of the affected dialogs.
```
.no-animation-dialog {
  /*CSS transitions*/
  -o-transition-property: none !important;
  -moz-transition-property: none !important;
  -ms-transition-property: none !important;
  -webkit-transition-property: none !important;
  transition-property: none !important;
  /*CSS transforms*/
  -o-transform: none !important;
  -moz-transform: none !important;
  -ms-transform: none !important;
  -webkit-transform: none !important;
  transform: none !important;
  /*CSS animations*/
  -webkit-animation: none !important;
  -moz-animation: none !important;
  -o-animation: none !important;
  -ms-animation: none !important;
  animation: none !important;
}
```

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
