### ISSUE TITLE
Header/Footer template for MultiSelect

### ISSUE THREAD

**Issue by michita** [primefaces/primeng#5950]
**I'm submitting a ...** 
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**What is the motivation / use case for changing the behavior?**

I would like to add a select to search item with logical operators (Look at the picture). 

![feature_select](https://user-images.githubusercontent.com/6960233/41723793-4a2a0d4e-756c-11e8-997a-4e3a0c1dbd94.png)

The idea is to be able to append a template to multiSelect or add a custom  \<p-header> like \<p-footer>

* **Angular version:** 6.0.3

* **PrimeNG version:** 6.0

**Comment by michita** [comment]
Thanks

**Comment by cagataycivici** [comment]
Waiting for more community requests to proceed.

**Comment by kasonjimLD** [comment]
I would definitely like to see this as a possibility for MultiSelects. In my case it would be for adding the text "Select All" next to the select all checkbox in the header
