### ISSUE TITLE
Picklist issue: On selection, partial text is selected when the text is long(when the scroll bar appears)

### ISSUE THREAD

**Issue by PrajwalGonsalves** [primefaces/primeng#5954]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Waiting Time: ~8 weeks.

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
I have created a simple pick list and provided values to the source and target. Make the source values long such that you see a scroll bar in the source table. Now, use the scroll bar and move to the right most corner of the scrolling space in the source table. Click(or select) a value in the source table. The text gets selected partially. 

**Expected behavior**
The complete text has to be selected.

* **Angular version:** 4.3.2

* **PrimeNG version:** 4.1.2

* **Browser:**  Chrome
 
* **Language:** TypeScript 2.4.2

* **Node (for AoT issues):** `node --version` =   8.0.17

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
