### ISSUE TITLE
Tree module :: primeng 6.0.0 :: children in tree nodes don't show up :: see stackblitz inside 

### ISSUE THREAD

**Issue by fbayanati** [primefaces/primeng#5958]
**I'm submitting a bug.**  

[x ] bug report 
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

Please see below stackblitz and the issue is the tree node children won't show up!
[https://stackblitz.com/edit/github-6jq8nu-tbji6d?file=src%2Fservices%2Fmock-files.ts](https://stackblitz.com/edit/github-6jq8nu-tbji6d?file=src%2Fservices%2Fmock-files.ts)

[https://stackblitz.com/edit/github-6jq8nu-tbji6d](https://stackblitz.com/edit/github-6jq8nu-tbji6d)
```

**stackblitz Case (Bug Reports)**
[https://stackblitz.com/edit/github-6jq8nu-tbji6d?file=src%2Fservices%2Fmock-files.ts](https://stackblitz.com/edit/github-6jq8nu-tbji6d?file=src%2Fservices%2Fmock-files.ts)

[https://stackblitz.com/edit/github-6jq8nu-tbji6d](https://stackblitz.com/edit/github-6jq8nu-tbji6d)

**Current behavior**
Tree node children don't show up

**Expected behavior**
Expected Tree shows the children

**Minimal reproduction of the problem with instructions**
Simply tried to add primeng 6.0.0 for an Angular 6 stackblitz

**Please tell us about your environment:**
Mac OS, VS Code, npm, stackblitz

* **Angular version:** 6.0.6

* **PrimeNG version:** 6.0.0

* **Browser:** Chrome 67.0.3396.87

**Comment by fbayanati** [comment]
Tried another stackblitz and fixed it, it works fine
[https://stackblitz.com/edit/angular-wqef8y](https://stackblitz.com/edit/angular-wqef8y)

**Comment by rashnk** [comment]
I dont want to create new issue for this, but + icon is not showing in horizontal tree
 [](https://stackblitz.com/edit/github-6jq8nu-qpkeo8?file=src%2Fapp%2Fapp.component.ts)
