### ISSUE TITLE
No way to set paginator icons

### ISSUE THREAD

**Issue by markgoho-EDT** [primefaces/primeng#5959]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

![image](https://user-images.githubusercontent.com/33099374/41810496-a0b03474-76cd-11e8-811f-71b37cb169a2.png)

**Expected behavior**
Provide a way to set these icons.

* **Angular version:** 6.0.5

* **PrimeNG version:** 6.0

**Comment by cagataycivici** [comment]
Invalid issue ticket.
