### ISSUE TITLE
Calendar [dateFormat] documentation is not accurate

### ISSUE THREAD

**Issue by gatapia** [primefaces/primeng#596]
I have found (in beta 9) that `[dateFormat]="yy-mm-dd"` does not work.  I must explicitly use a quotes, i.e. `[dateFormat]="'yy-mm-dd'"`. Which is not consistent with [docs](http://www.primefaces.org/primeng/#/calendar).

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
