### ISSUE TITLE
P-Carousel Feature request

### ISSUE THREAD

**Issue by CybrZr00** [primefaces/primeng#5960]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Unable to access next and previous methods of p-carousel.

**Expected behavior**
I would love to be able to activate next and previous methods from code, so I could then wire up swipeleft and swiperight... or just enable swipe :)

**What is the motivation / use case for changing the behavior?**
On mobile devices swiping is more intuitive, and the default buttons are quite small.

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/issues/3896
