### ISSUE TITLE
Fileupload in basic mode with multiple selection

### ISSUE THREAD

**Issue by kcsahoo** [primefaces/primeng#5961]
If you choose 
<p-fileUpload mode="basic" multiple="multiple" id="additionalSupportingDocuments" name="additionalSupportingDocuments[]" maxFileSize="5000000" (onSelect)="onBasicUpload($event)" chooseLabel="Browse">
</p-fileUpload>
all the file names are not listed. Only one filename is listed although it uploads all selected files.

**Comment by cagataycivici** [comment]
Not planned at the moment as there is advanced mode for it.
