### ISSUE TITLE
Button Bar not Showing in Calender

### ISSUE THREAD

**Issue by realvino** [primefaces/primeng#5963]
The button bar not showing after i set showButtonBar is true

<p-calendar [(ngModel)]="dateValue" showButtonBar="true"></p-calendar>

any help ! . it would be much appreciated

**Comment by Arnobhridoy** [comment]
use <p-calendar [(ngModel)]="dateValue" showButtonBar=true> or <p-calendar [(ngModel)]="dateValue" [showButtonBar]="true">
