### ISSUE TITLE
Change detection turbo-table

### ISSUE THREAD

**Issue by alpernakin** [primefaces/primeng#5966]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
I apply filters to turbo-table and I would love to update the filtered list, which is currently displayed while filtering, as values of the table data are updated

Note: The information which is given on the documentation did not make sense:

Table may need to be aware of changes in its value in some cases such as reapplying sort. For the sake of performance, this is only done when the reference of the value changes meaning a setter is used instead of ngDoCheck/IterableDiffers which can reduce performance. So when you manipulate the value such as removing or adding an item, instead of using array methods such as push, splice create a new array reference using a spread operator or similar.

Source: https://primefaces.org/primeng/#/table

**Current behavior**
Filtered list stays stable though the related values are updated

**Expected behavior**
Update related values on the filtered list

* **Angular version:** 6.0.8

* **PrimeNG version:** 6.0.0

**Comment by PabMendez** [comment]
+1, I'm having the same problem, the sorted data doesn´t detect the change on the [value] of the turboTable

**Comment by Mysame** [comment]
The documentation makes perfect sense; in order to update [value], the reference needs to be changed.

```
// Imagine you have a p-table somewhere with [value]="list"

list.push({name: "new item"}); // This does not update the [value] binding
list = [{name: "new item"}].concat(list); // This updates the list reference, and will trigger a [value] update
```

It's like this in pretty much all of Angular by default, this is no different.

**Comment by cagataycivici** [comment]
Comment above explains it perfectly.
