### ISSUE TITLE
External DragDrop feature for Tree

### ISSUE THREAD

**Issue by jmesa-sistel** [primefaces/primeng#5969]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[X] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
Try to drag a node to another div is not possible

**Expected behavior**
Be able to use `<ng-template let-node pTemplate="default">` to drag a node to another component.

The problem is in:
[tree.ts#L224](https://github.com/primefaces/primeng/blob/master/src/app/components/tree/tree.ts#L224)
```
if (this.tree.draggableNodes && this.node.draggable !== false) {
            event.dataTransfer.setData("text", "data");
            this.tree.dragDropService.startDrag({
                tree: this,
                node: this.node,
                subNodes: this.node.parent ? this.node.parent.children : this.tree.value,
                index: this.index,
                scope: this.tree.draggableScope
            });
        }
        else {
            event.preventDefault();  // <---- THIS LINE
        }
```
@cagataycivici 
is there any reason of this line?

At now I have set [draggableNodes]="true" to be able to drag the node but I can see errors on console log, and it is a workaround. I can also override the function `UITreeNode.prototype.onDragStart = function (event) { .... };` but it is a ugly hack.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
