### ISSUE TITLE
Calendar ignoring initial model value

### ISSUE THREAD

**Issue by gatapia** [primefaces/primeng#597]
I have the following template:

```
<p-dialog [(visible)]="showDateSelection" [width]="650" [modal]="true">
  <p-calendar [(ngModel)]="fromstr" [inline]="true" [dateFormat]="'yy-mm-dd'"></p-calendar>
  <p-calendar [(ngModel)]="tostr" [inline]="true" [dateFormat]="'yy-mm-dd'"></p-calendar>
  {{fromstr}} - {{tostr}}
</p-dialog>
```

And the following in my component

```
public fromstr: string = '01-01-2016';
public tostr: string = '01-08-2016';
```

These values are ignored the first time the calendars are shown (todays date is selected).  Not sure if this is a dialog issue or calendar.  Note: Labels below dates show correct dates. 

After date has been selected using pickers the dates displayed are correctly (so its only ignoring its initial model value).

**Comment by ypolosov** [comment]
I've the same problem

**Comment by ypolosov** [comment]
I had the same problem ...I've solved it using [defaultDate] 
`<p-calendar [defaultDate]="fromstr" [(ngModel)]="fromstr" [inline]="true" [dateFormat]="'dd-mm-yy'"></p-calendar>`

**Comment by rafaelcb21** [comment]
To work the variable `fromstr` and `tostr` must be of type **Date**:

    public fromstr: Date = new Date("01-01-2016"); //MM-DD-YYYY
    public tostr: Date = new Date("01-08-2016"); //MM-DD-YYYY

**Comment by adityaba** [comment]
On initial load calendar do not format the input(time part) when showTime attribute is set to true. 

I am having *.component.ts
====================
public value:date;

constructor (...) {
   var milliseconds = 1488195013000; //Assume epoch time of 02/24/2017 01:23 AM
    this.value= new Date(milliseconds)
} 

===================
<p-calendar [(ngModel)]="value" showTime="showTime" hourFormat="12"></p-calendar> 

It shows me something like  02/24/2017 0-11:23 PM

Any help solving this is highly appreciated.

**Comment by cagataycivici** [comment]
Should be fixed with recent PrimeNG releases. please drop a comment if issue persists and we'll reopen.

**Comment by PunkHaz4rd** [comment]
Still not working with ngModel.
