### ISSUE TITLE
Treetable row click and dbclick events

### ISSUE THREAD

**Issue by shayts** [primefaces/primeng#5970]
I'm submitting a
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already 
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Row click and row dbClick events can be set using ttSelectableRow or ttSelectableRowDblClick.

**Expected behavior**
In some cases both row click and row dbclick events are required. currently only one option is possible. It would be nice to be able to use both ttSelectableRow and ttSelectableRowDblClick together. 

* **Angular version:** 6.0
* **PrimeNG version:** 6.0
* **Browser:** [all] 
* **Language:** [TypeScript]

**Comment by cyberrranger** [comment]
same here

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
