### ISSUE TITLE
Disable animations or allow customization of animations

### ISSUE THREAD

**Issue by ksdev-pl** [primefaces/primeng#5971]
**I'm submitting a ...** 
[x] feature request

**Current behavior**
Animations are hard-coded (`400ms ease-in` etc).

**Expected behavior**
There are no animations or they are customizable. I'm referring specifically to the `p-calendar` component.

**Comment by nfdevil** [comment]
This should indeed be an input property on the component: 'disableAnimations'

**Comment by rafa-as** [comment]
+1 both: customization and disable

**Comment by mialy** [comment]
_Maybe_ a work-around for disabling animations with PrimeNG 6.1.2:

- In .ts file add ```@HostBinding('@.disabled') disabled = true;``` line to child components; adding it to parent component will disable animations on all child components too
- In .html (template) file add ```[@.disabled]="true"``` to child component, like ```<p-calendar [@.disabled]="true" ...></p-calendar>```

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/issues/6652
