### ISSUE TITLE
Add specific class for first and last day in calendar

### ISSUE THREAD

**Issue by juanchofelipe** [primefaces/primeng#5977]
**I'm submitting a ...** 
```
[ ] bug report 
[x] feature reques
[ ] support request
```
Hi! It would be nice to add a specific class for the first and last day of the calendar when it is used in range mode, in order to show those days with a different style as the example below:

![image](https://user-images.githubusercontent.com/13863062/41987943-5312f608-7a00-11e8-8004-fc7cf224c560.png)

**Comment by Subash-fourK** [comment]
+1

**Comment by kim-spotinst** [comment]
when do you think that this will be available?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
