### ISSUE TITLE
RTL support for TreeTable

### ISSUE THREAD

**Issue by shayts** [primefaces/primeng#5978]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
An arrow points in the opposite direction of the content.

**Expected behavior**
An arrow points in the direction of the content.

**Minimal reproduction of the problem with instructions**
Using the treetable with RTL, the chevron arrow points to the wrong direction.

**What is the motivation / use case for changing the behavior?**
To better support RTL. I consider this a bug and not a feature request since RTL is supposedly supported by this component.

* **Angular version:** 6.X
* **PrimeNG version:** 6.X
* **Browser:** [Chrome]
* **Language:** [TypeScript 2.7.2]

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
