### ISSUE TITLE
Recenter dialog

### ISSUE THREAD

**Issue by negberts** [primefaces/primeng#5979]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
Before 6.0.0 the dialog was recentering itself when response=true was set. With 6.0.0 the flickering has been disabled, which is a good thing, but the dialog now doesn't recenter when data is added. For instance a dialog with search functionality which opens without results and gets results when the search is entered now stays in the current position.

**Expected behavior**
If the content of the dialog changes, the dialog should recenter. Or, some function should be available to call this functionality. Now modal.visible = false and than modal.visible = true does the trick, but there should be some cleaner function to recenter without temporary hiding the dialog.* 

**Angular version:** 6.0.7

* **PrimeNG version:** 6.0.0

* **Browser:** Chrome

**Comment by negberts** [comment]
I've found another fix

ngAfterViewChecked() {
        this.modal.positionOverlay();
    }


But can't this just be done in the dialog itself?

**Comment by cagataycivici** [comment]
This has been discussed many times, even positioning at view check causes flickering in other cases. So we left it to the user, common workaround is using contentStyle with a max height so internally dialog content scrolls for big content and content size changes does not effect the position.
