### ISSUE TITLE
Draggable with child's element as drag handle

### ISSUE THREAD

**Issue by gatapia** [primefaces/primeng#598]
If the dragHandle is set to the class of a child component then dragging does not work.

This can be seen on the [demo](http://www.primefaces.org/primeng/#/dragdrop) in the Drag Only/Drag Header example.

If the drag handle is a direct child (i.e. in the same template) then it appears to work.

**Comment by cagataycivici** [comment]
Should be fixed with recent PrimeNG releases. please drop a comment if issue persists and we'll reopen.
