### ISSUE TITLE
filter on multiselect

### ISSUE THREAD

**Issue by SalimDr** [primefaces/primeng#5984]
Hello,

I find an issue on multiselect component filter. on my case, every time i add any sub string of the label, nothing is displayed and i looked on the code and find this method
`MultiSelect.prototype.isItemVisible = function (option) {

        if (this.filterValue && this.filterValue.trim().length) {
            for (var i = 0; i < this.visibleOptions.length; i++) {
                if (this.visibleOptions[i].value == option.value) {
                    return true;
                }
            }
        }
        else {
            return true;
        }
    }`

the issue is when you compare the 2 objects, if i try with the code below by putting the Json stringify it work normally:
`if (JSON.stringify(this.visibleOptions[i].value) == JSON.stringify(option.value))`
I have already compared the position of each properties on the compared object.

Could you please fix it.

Thanks

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
