### ISSUE TITLE
p-dialog minimize not working

### ISSUE THREAD

**Issue by anmoljainatcs** [primefaces/primeng#5986]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**

After maximizing dialog, the maximize icon does not change to Minimize icon and also I am not able to minimize the dialog.

**Expected behavior**

After mizimize, the icon should change to minimize icon and onclik of it dialog should be minimize.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10, npm, nodejs
* **Angular version:** 6.0.8

* **PrimeNG version:** 6.0.0

* **Browser:** [all]

 
* **Language:** [TypeScript 2.7.2 ]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Unable to replicate and there is no test case so had to close. Please attach a test-case that runs on stackblitz next time you're creating issue. If issue persists, please create a new ticket with a test case.
