### ISSUE TITLE
new feature: pgup/down navigation on dropdown lists

### ISSUE THREAD

**Issue by cghislai** [primefaces/primeng#5988]
When a dropdown/autocomplete suggestion list is open and focuses, keyboard navigation works using the up/down keys, but not using the pgup/pgdown keys.

If the list is appended to the body and the body height is greater than the view height, this makes the document - and the input field - scroll, but not the dropdown list, which looks weird.

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
