### ISSUE TITLE
p-dropdown not selectable in IE10

### ISSUE THREAD

**Issue by TekSiDoT** [primefaces/primeng#599]
Dropdown entries created in p-dropdown do not react to clicks when using IE10 (tested on Win7).

**Comment by Ov3rlo4d** [comment]
This happens because the method `onItemClick(option)` in dropdown.ts references the variable `event` which is not in scope.

It works in chrome because chrome create a global event object when some event is fired, but this is not something you can rely on.

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
