### ISSUE TITLE
p-table Lazy load and multiple select with Shift does not select all rows

### ISSUE THREAD

**Issue by Spac3JaM** [primefaces/primeng#5995]
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```


**Current behavior**
when <p-table> control is working with lazyloading, multiple selection with Shift + click is not working properly

**Expected behavior**
when <p-table> control is working with lazyloading, multiple selection with Shift + click to select all rows, regardless if they are loaded or not

**Minimal reproduction of the problem with instructions**
<!--
Have <p-table> with [lazy]="true" selectionMode="multiple". Have more records than the page size. Select the very first row, scroll to the last and mouse click with shift key pressed 
-->

**What is the motivation / use case for changing the behavior?**
Shift + click is not working properly for the end user. They have lots of rows, new pages are loaded as  the user scrolls. The end user does not know about our pagination, they just want multiple select with Shift + Mouse click on a table with many rows and large scroll. 

**Please tell us about your environment:**


* **Angular version:** 5.X
5.2

* **PrimeNG version:** 5.X
^5.2.5

* **Browser:** 
all
 
* **Language:** TypeScript

* **Node (for AoT issues):** `node --version` =

**Comment by chriswhite199** [comment]
Experiencing the same issue myself, with 5.2.7. I've traced the issue which appears to be in the `Table.selectRange` method.

When lazy loading data, and not on the first page, the values for `rangeStart` and `rangeEnd` local variables are numbered in relation to the first page. The `rangeRowData` local variable is then set to the value of `this.value[i]`, where` `i is in the range - while `this.value` is the current page of data.

From https://github.com/primefaces/primeng/blob/5.2.7/src/app/components/table/table.ts#L825
```
// for example with a page size of 20, lazy=true, second page in view
// rangeStart = 22, rangeEnd = 26
// but they should be offset to 2, 6
for(let i = rangeStart; i <= rangeEnd; i++) {
    // this.value has max length of pageSize, so i will be out of bounds
    let rangeRowData = this.value[i]; 
```

**Comment by chriswhite199** [comment]
Yeap, confirmed - by patching the table.js file in `node_modules/primeng/components/table/table.js` you can fix this:

```
         }
+        if (this.lazy) {
+            rangeStart -= this.first;
+            rangeEnd -= this.first;
+        }
         for (var i = rangeStart; i <= rangeEnd; i++) {
```

I can't see how i'd submit a PR for this, as there is only a branch for master, vs a branch for the base versions (5, 6, 7).

How can i go about getting this into a release (preferably a 5.2.x release for me)

**Comment by cagataycivici** [comment]
@mertsincan review please.

**Comment by mertsincan** [comment]
I think it's wrong to choose all rows. Some rows can be removed/added by users on the previous page. Therefore, the anchorRowIndex is reset on each event, such as sorting, filtering, page change, and virtual scrolling.
