### ISSUE TITLE
Can not do table rowspan in primeng treetable(Row Group)

### ISSUE THREAD

**Issue by potatolianyi** [primefaces/primeng#5996]
**I'm submitting a  feature.  

**Current behavior**
Table rows are not grouped.

**Expected behavior**
Table rows should be grouped.

**What is the motivation / use case for changing the behavior?**
Parent node and children node share the same table cell.

* **Angular version:** 5.X
Angular 5

* **PrimeNG version:** 6

**Comment by cagataycivici** [comment]
Please use forum for support requests, as you have control over the presentation you can implement it, there is an example in Table demos to give an idea.
