### ISSUE TITLE
Ultima Template: Generating Custom Theme will result in missing CSS Properties

### ISSUE THREAD

**Issue by iArnoldo** [primefaces/primeng#5997]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Waiting Time: ~8 weeks.

**I'm submitting a ...**  (check one with "x")
```
[ ^x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
So i own the ULTIMA Theme and recently migrated from Angular 5 and Primeng 5 to Angular 6 and Primeng 6. Following the Ultima theme Documentation i tried to create a custom theme.
After generating the css from the scss file i noticed there are a lot of CSS Properties missing resulting in an incomplete view. This is probably because there were changed in the Theme, Layout and Icon section of PrimeNg.

**Expected behavior**
Generating a new Custom Theme should generate all needed Css Properties for the Ultia Template!

**Minimal reproduction of the problem with instructions**
Create new Angular Projekt import PrimeNg include PrimeNg Ultima theme. Create new Custom theme according to Ultima Documente : https://www.primefaces.org/ultima-ng/#/documentation found under the Topic Theme

* **Angular version:** 5.X
Angular 6

* **PrimeNG version:** 5.X
PrimeNg 6

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Please use Ultima forum to require assitance.
