### ISSUE TITLE
Add functionality to have Turbo Table RowGroups expanded by default

### ISSUE THREAD

**Issue by glenr8** [primefaces/primeng#5999]
It would be nice if you could specify a group to be expanded by default, or have all groups expanded by default instead of all groups collapsed as the default. :)

**Comment by mmlitvin** [comment]
Very interested to see this as well

**Comment by cagataycivici** [comment]
There is no built-in expanded row groups, it is just a demo to show how it is done meaning you should be able to extend the demo to show a group as expanded.
