### ISSUE TITLE
Change module to CommonJS

### ISSUE THREAD

**Issue by bPopovska** [primefaces/primeng#60]
PrimeNG can not be used in webpack based projects because of the used module style (system).
As system.js can also consume commonJS modules, please switch to commonJS

**Comment by cagataycivici** [comment]
We'll discuss it this for next week's 0.5 release, thank you for the feedback.

**Comment by bPopovska** [comment]
Could I get some information about the status if this issue, since release 0.5 is already out, and this is still open?
Can I expect this change to be included in some upcoming release, if in any?

**Comment by cagataycivici** [comment]
Right now we are experimenting a webpack+primeng started based on commonjs, it will be ready in 1-2 weeks, it is likely that 0.6 will be based on systemjs before the switch. Note that PrimeNG releases are weekly.

**Comment by cagataycivici** [comment]
PrimeNG now compiles to commonjs. We also have plans to create a new starter sample alternative with webpack, as current one uses system.js
