### ISSUE TITLE
TreeTable manually selection dont work

### ISSUE THREAD

**Issue by cyberrranger** [primefaces/primeng#6001]
```
[X] bug report => Search github for a similar issue or PR before submitting
```
https://www.primefaces.org/primeng/#/treetable/selection
sry, i have not a stackblitz demo with working treetable

on a default p-table (in PrimeNg 6) and in the old TreeTable (PrimeNg 5)

show:

`<p-table [columns]="cols" [value]="cars" selectionMode="single" [(selection)]="selectedCar1" dataKey="vin">`

i can select a value in ts with:

`this.selectedCar1 = this.cars[0]`

but in the new TreeTable (PrimeNg 6) :/ is not working.

* **Angular version:** 6.0
* **PrimeNG version:** 6.0

**Comment by cyberrranger** [comment]
is working

**Comment by hadjsamadi** [comment]
Yes, this bug exists.
in treetable.ts => updateSelectionKeys function , replace these lines:
this.selectionKeys[String(this.objectUtils.resolveFieldData(data, this.dataKey))] = 1;
to:
this.selectionKeys[String(this.objectUtils.resolveFieldData(data.data, this.dataKey))] = 1;
and 
this.selectionKeys[String(this.objectUtils.resolveFieldData(this._selection, this.dataKey))] = 1;
To:
this.selectionKeys[String(this.objectUtils.resolveFieldData(this._selection.data, this.dataKey))] = 1;
