### ISSUE TITLE
p-calender minTime and maxTime Issue

### ISSUE THREAD

**Issue by vishu3011** [primefaces/primeng#6002]
Hi Team,
How can we restrict p-calendar for a specific set of time
Is there any attribute like minDate and maxDate for time too?
As I am getting error using minHour-maxHour minMinutes-maxMinutes.
Please help me out in this issue.
Thanks in Advance

**Comment by vishu3011** [comment]
Hi there,
I have done that one that you suggesting but it is not solving my issue.
I want to set min and max time for everyday same.
Ex: I will able to select time between 8 am to 9:45 pm everyday not any other time.

**Comment by kamaleshkrishnan** [comment]
Hi any update on the minTime and maxTime issue with the p-calendar.I am using the p-calendar and i am restricting the user with minDate and maxDate, with the minDate it is disabling the dates as per my calculation but when the calendar is disabled it is not disabling the time. Let me know how to do this.

**Comment by cagataycivici** [comment]
Please use forum for support requests.
