### ISSUE TITLE
TurboTable resize columns with colspan and scrollable="true"

### ISSUE THREAD

**Issue by eltigree** [primefaces/primeng#6004]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Waiting Time: ~8 weeks.

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
If you define rowspan an colspan then resize-mode for columns not works correct with scrollable=true

**What is the motivation / use case for changing the behavior?**
Can you please bring the following code into your table.js (see attacked print-screen).
Thanx a lot!

* **Angular version:** 5.2.3

* **PrimeNG version:** 6.0.0-beta.1
* **Browser:** [all]
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =   
![colspan](https://user-images.githubusercontent.com/38324113/42314734-fc38598a-8045-11e8-910b-25b7fec5e178.png)

**Comment by cagataycivici** [comment]
Grouping is not supported yet in resizable columns.
