### ISSUE TITLE
Chart feedback data is useless

### ISSUE THREAD

**Issue by ningacoding** [primefaces/primeng#6008]
Following showcase example
https://www.primefaces.org/primeng/#/chart/line

```
selectData(event) {
        this.msgs = [];
        this.msgs.push({severity: 'info', summary: 'Data Selected', 'detail': this.data.datasets[event.element._datasetIndex].data[event.element._index]});
    }
```

nothing under "event", or "this.data" is useful to click a dataSet and do another thing that show Value of already is shown in chart.

there is no way to click an "id" or anything to know if we need to show details of that selected Data.

**Comment by cagataycivici** [comment]
Event is actually;

{originalEvent: event, element: element[0], dataset: dataset}
