### ISSUE TITLE
Accessibility Screen Reader Incorrectly defines the p-sortIcon

### ISSUE THREAD

**Issue by leonliang33** [primefaces/primeng#6009]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When navigating to p-sortIcon using screenreader, it will read a link which will confuse users. If we can change this to a div instead then this problem can be easily mitigated.

**Expected behavior**
p-sortIcon to read a more descriptive label and not a link

**Minimal reproduction of the problem with instructions**
Use screenreader on edge and navigate to a p-sortIcon with tabs

**What is the motivation / use case for changing the behavior?**
Accessibility improvements

**Please tell us about your environment:**
OS: Windows 10

* **Angular version:** 5.X
Angular: 5.1.3

* **PrimeNG version:** 5.X
5.2.5

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
This is outdated as aria-props are now at the th element not sortIcon.
