### ISSUE TITLE
InputMask cannot bond ngModel.

### ISSUE THREAD

**Issue by qwding** [primefaces/primeng#601]
There is few docs about inputMask, When I try to bond ngModel, it come up with 'EXCEPTION: No value accessor for '''. 
with the version : 

```
"@angular/core": "2.0.0-rc.4",
"primeng": "1.0.0-beta.9",
```

**Comment by vishaltechreceptives** [comment]
I have same issue in InputMask, When i try to bound then it will gives error 'EXCEPTION: No value access for "".

PrimeNg version:
`"primeng": "^1.0.0-beta.11" `

**Comment by sudheerj** [comment]
I'am not able to replicate the issue with latest PrimeNG 2.X/4.x release.It works fine with ngModel.Please try with latest versions.

**Comment by cagataycivici** [comment]
Unable to replicate.
