### ISSUE TITLE
Multi level row grouping in Turbo Table

### ISSUE THREAD

**Issue by glenr8** [primefaces/primeng#6010]
Does anyone know if it's possible to have multi-level row grouping in the Turbo Table? Doesn't seem to be a native feature.

**Comment by egedarcin** [comment]
Check on "tree table" for multi-level grouping features.

**Comment by glenr8** [comment]
Hi, I did, but this does not support filtering. We need a table that supports full filtering capabilities and row grouping. Please correct me if I'm wrong about Tree Table not filtering!

**Comment by egedarcin** [comment]
Would "toggleable groups" on tables work for you? I'll try to implement a search to it and tell you if it is possible.

**Comment by glenr8** [comment]
Basically what I need to produce is the Tree Table, but with the full filtering capabilities of the Turbo Table. Essentially I need to combine the 2 modules into one super module!

**Comment by cagataycivici** [comment]
Please use forum for questions and discussions. Thankyou.
