### ISSUE TITLE
Calendar control with year selector doesn't work in Ultima

### ISSUE THREAD

**Issue by aschip** [primefaces/primeng#6011]
As mentioned here

https://forum.primefaces.org/viewtopic.php?p=168321#p168321

Use Ultima theme abd use the following in it:

`<p-calendar id="showIcon" [showIcon]="true" yearNavigator=true monthNavigator=true yearRange="1900-2017" placeholder="Button"></p-calendar>`

I have 2 issues:

1. The selected month text with longer names like "November, December" etc gets clipped

2. Year selector doesn't work.

![](https://image.ibb.co/dwgP9d/Prime_NGUltima_Calendar_No_Year_In_Selector_Error.jpg)

**Comment by cagataycivici** [comment]
Please use Ultima NG support forum instead of PrimeNG Core Issue tracker.

**Comment by AshishFreak** [comment]
hello @aschip  can you please PrimeNg Ultima Master theme ?
