### ISSUE TITLE
modal p-dialog is not scrollable with dynamic content

### ISSUE THREAD

**Issue by vmaerten** [primefaces/primeng#6013]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/github-fvtbzg

**Current behavior**

1. We open a modal dialog (`p-dialog`)
2. The dialog contains a button to hide/show some long text (using a `*ngIf`)
3. When we click on the button, the long text is cut and we cannot scroll down, there is no scrollbar.

**Expected behavior**
1. We open a modal dialog (`p-dialog`)
2. The dialog contains a button to hide/show some long text (using a `*ngIf`)
3. The text is shown and we can scroll down to the end.

**Minimal reproduction of the problem with instructions**

Please use the "Current behaviour scenario" with the app on https://stackblitz.com/edit/github-fvtbzg.

**What is the motivation / use case for changing the behavior?**

This is an unexpected behaviour on a `p-dialog` size. 

**Please tell us about your environment:**

* **Angular version:** 5.2.10

* **PrimeNG version:** 6.0.0

* **Browser:** Chrome | IE | Firefox

* **Language:** all

**Comment by cagataycivici** [comment]
You may use contentStyle with a maxHeight or disable blockScroll prop to resolve this.
