### ISSUE TITLE
Issue p-table multiselection (shift)+ filter - remains

### ISSUE THREAD

**Issue by mmlitvin** [primefaces/primeng#6018]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting

This defect has been previously reported under Issue 5195 here 
https://github.com/primefaces/primeng/issues/5195
and was closed as fixed. 
Unfortunately it is not fixed. I am running with 5.2.7 and bug is still there. 

Here is the plunker:
https://stackblitz.com/edit/github-j2p6gs?file=src/app/app.component.ts

Here is the steps to replicate:
Filter ID column with '2'
Trye to select from first row to last row with 'SHIFT'
Remove filter

**Comment by atecey** [comment]
Seeing the same in 6.0.0 and using a global filter

**Comment by mmlitvin** [comment]
Any news?

**Comment by atecey** [comment]
Fixed for me in version 6.1.0 though I'm using multi selection without 'SHIFT'

**Comment by mmlitvin** [comment]
I am still seeing it in 6.1.0 when using SHIFT
Surprised this is not getting  noticed by more users. In any large data application in order to perform any update in bulk user would use mutlirow select and filter often

**Comment by mmlitvin** [comment]
Any news? Timelines?

**Comment by amitkulgod** [comment]
Is it fixed in any of the latest versions ?

**Comment by yigitfindikli** [comment]
Hi, I’m unable to replicate with the latest PrimeNG and i'm updated your sample version to PrimeNG 7.1.0 seems to be fixed. You can look in
https://stackblitz.com/edit/github-j2p6gs-zp5sjo?file=src/app/app.component.ts
