### ISSUE TITLE
p-table - jumping to next page via pagination needs to scroll to 1st record on next page

### ISSUE THREAD

**Issue by mmlitvin** [primefaces/primeng#6019]
[ ] bug report => Search github for a similar issue or PR before submitting
[  x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

I am not sure if this is feature request or a defect. I would consider it actually a defect based on weak design. 
The whole point of pagination is to provide user with next sorted subset of records. If I am viewing the last record on the page 1, by going to page 2 I expect to see the very first record on page 2 and not the last one.

When next page is requested please autoscroll to first record of the table. 
Thank you

**Comment by mmlitvin** [comment]
Is there any outlook ?

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
