### ISSUE TITLE
Load jqery-datepicker localization in Calendar

### ISSUE THREAD

**Issue by PhilippRoessner** [primefaces/primeng#602]
We are loading the german localizations for the jquery-datepicker. When we select a date, the selected date shows up in the correct format. But when the p-calendar - component gets initialized, it shows the modelvalue in the default format.

On init:
![oninit](https://cloud.githubusercontent.com/assets/6959716/16835763/75fd5dca-49ba-11e6-94f0-3dee5641a4b6.PNG)

after selection:
![onselect](https://cloud.githubusercontent.com/assets/6959716/16835773/834acbc0-49ba-11e6-91d5-9e522dfe3dfb.PNG)

setting localization in my index.html:
`<script src="lib/localisation/datepicker-de.js"></script>`

loading p-calendar
`<p-calendar [(ngModel)]="klient.geburtsdatum" id="gebdatum" [showButtonPanel]="true" [showIcon]="true"></p-calendar>`

Is it possible to load the jquery localization by default?

**Comment by cagataycivici** [comment]
Calendar is a native components, does not use jquery, you need to use locale property instead.
