### ISSUE TITLE
P-table:  Horizoantal bar comes between the body and footer in the unfrozen view of table

### ISSUE THREAD

**Issue by JonaliDas** [primefaces/primeng#6021]
I am using primeng 6.0.0-beta.1. I have created a p-table with a frozen and unfrozen view. I have added frozenfooter and plain 'footer'. The issue is the horizontal bar comes between body and footer in unfrozen view. Can someone tell me how to make the horizontal bar come after the footer?

`<h3>Frozen Column Groups</h3>
<div style="width:800px">
    <p-table [value]="sales" [scrollable]="true" scrollHeight="200%" frozenWidth="200px" >
        <ng-template pTemplate="frozencolgroup">
            <colgroup>
                <col style="width:200px;">
            </colgroup>
        </ng-template>
        <ng-template pTemplate="colgroup">
            <colgroup>
                <col style="width:80px;">
                <col style="width:80px;">
                <col style="width:80px;">
                <col style="width:80px;">
                <col style="width:80px;">
                <col style="width:80px;">
                <col style="width:80px;">
                <col style="width:80px;">
            </colgroup>
            </ng-template>
        <ng-template pTemplate="frozenheader">
            <tr>
                <th style="height:84px">Brand</th>
            </tr>
        </ng-template>
        <ng-template pTemplate="frozenbody" let-sale>
            <tr>
                <td>{{sale.brand}}</td>
            </tr>
        </ng-template>
        <ng-template pTemplate="frozenfooter" let-sale>
            <tr>
                <td>One</td>
            </tr>
        </ng-template>
        <ng-template pTemplate="header">
            <tr>
                <th colspan="8">Sale Rate</th>
            </tr>
            <tr>
                <th colspan="2">Sales</th>
                <th colspan="2">Profits</th>
                <th colspan="1">A</th>
                <th colspan="1">B</th>
                <th colspan="1">C</th>
                <th colspan="1">Profits</th>
            </tr>
            <tr>
                <th>Last </th>
                <th>This </th>
                <th>Last </th>
                <th>This </th>
                <th colspan="1">A</th>
                <th colspan="1">B</th>
                <th colspan="1">C</th>
                <th colspan="1">Profits</th>
            </tr>
        </ng-template>
        <ng-template pTemplate="body" let-sale>
            <tr>
                <td>{{sale.lastYearSale}}</td>
                <td>{{sale.thisYearSale}}</td>
                <td>{{sale.lastYearProfit}}</td>
                <td>{{sale.thisYearProfit}}</td>
                <td>{{sale.lastYearSale}}</td>
                <td>{{sale.thisYearSale}}</td>
                <td>{{sale.lastYearProfit}}</td>
                <td>{{sale.thisYearProfit}}</td>
            </tr>
        </ng-template>
        <ng-template pTemplate="footer" let-sale>
                <tr>
                    <td>One</td>
                </tr>
        </ng-template>
    </p-table>           `

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
