### ISSUE TITLE
PrimaNG Paradise side menu shakes when scrolling in IE 11

### ISSUE THREAD

**Issue by jgosar** [primefaces/primeng#6023]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Test case**
https://www.primefaces.org/paradise-ng/#/

**Current behavior**
When scrolling up and down on the page in Internet Exporer 11 (11.492.16299.0), the side menu which should be fixed starts shaking. And on some computers with the same version of IE the topbar shakes as well.

**Expected behavior**
All HTML elements with fixed position should stay still while the user scrolls up and down on the page. This is what happens in all other browsers.

**Minimal reproduction of the problem with instructions**
Open https://www.primefaces.org/paradise-ng/#/ in IE 11
Scroll up and down with your mouse wheel.

**What is the motivation / use case for changing the behavior?**
Users expect fixed navigation elements on the page to stay still.

**Please tell us about your environment:**
Windows 10 64bit, Internet Explorer 11 (11.492.16299.0)

* **Angular version:**
5.0.3 (although the Paradise demo page seems to be 6.0.4)

* **PrimeNG version:** 
5.2.4

* **Browser:** [IE 11]

**Comment by cagataycivici** [comment]
Please use Paradise NG support forum instead of PrimeNG Core Issue tracker.
