### ISSUE TITLE
sort event triggers when click on table anywhere. occurs on checkbox and custom sort.

### ISSUE THREAD

**Issue by kartik468** [primefaces/primeng#6029]
"primeng": "^6.0.0"
---
in below code consists of turbo table with multi select and custom sort 
steps-
1. sort with one of the column
2. click anywhere on table

sort event and sortfunction gets called unnecessary while clicking on body of table.
while normal sort dose not triggers it.

<p-table #dqListDataTableRef [columns]="cols" [value]="paginatedRuleList" [(selection)]="selectedRules" (onSort)="onTableSort($event)"
    (sortFunction)="onSort($event)" [customSort]="true">
    <ng-template pTemplate="header">
        <tr>
            <th style="width: 2.25em">
                <p-tableHeaderCheckbox></p-tableHeaderCheckbox>
            </th>
            <th *ngFor="let col of cols" [pSortableColumn]="col.field">
                {{col.header}}
                <p-sortIcon [field]="col.field"></p-sortIcon>
            </th>
        </tr>
    </ng-template>
    <ng-template pTemplate="body" let-rowData let-rule>
        <tr [pSelectableRow]="rowData">
            <td>
                <p-tableCheckbox [value]="rowData"></p-tableCheckbox>
            </td>
            <td *ngFor="let col of cols">
                {{rowData[col.field]}}
            </td>
        </tr>
    </ng-template>
</p-table>

**Comment by cagataycivici** [comment]
Invalid ticket, please create an issue template and create a new issue.

https://stackblitz.com/github/primefaces/primeng-issue-template
