### ISSUE TITLE
Focus of p-dialog component can´t be applied to Title and jumps out of modal view after reaching last element.

### ISSUE THREAD

**Issue by HISeG-ME** [primefaces/primeng#6037]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
The current behaviour of the p-dialog component doesn´t offer any functionality to focus on the Title. It is mandatory to secure Accessibility for Screenreaders. Additionally, the focus jumps out of the modal Dialog. However its possible to set the focus on the dialog-buttons using focusOnShow.

**Expected behavior**
After the Dialog has been appeared, it should be possible to set the focus on the Title. 

**Minimal reproduction of the problem with instructions**
1. https://www.primefaces.org/primeng/#/dialog
2. Use the keyboard to tab until you reach the "show"-button
3. Push Enter to reach the open dialog
4. The Focus is on the first button.
5. Once you reach the end of the Overlay, the focus jumps out of the dialog, even in modal view.

**What is the motivation / use case for changing the behavior?**
It is mandatory for a modal dialog to have the focus on the Title while using screenreaders.(Like the focusOnShow for the first button). Furthermore it shouldn´t be possible to jump out of the dialog in the modal view but starting from the beginning of the dialog again. 

**Please tell us about your environment:**
Windows 10, Eclipse Oxygen 4.7

* **Angular version:** 5.X
version: 5.1.0

* **PrimeNG version:** 5.X
version: 5.2.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all
* **Node (for AoT issues):** `node --version` =   
version: 7.5.0

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/issues/4544
