### ISSUE TITLE
Custom tslint.json to prevent errors on every file

### ISSUE THREAD

**Issue by rafa-as** [primefaces/primeng#6044]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When you go to contribute, it's impossible to prevent to spent a lot of time reverting automatic TsLint fixes, to make a PR without more changes than the real changes.

This is an example of a **165 lines file**:
<img width="1680" alt="screen shot 2018-07-11 at 16 41 06" src="https://user-images.githubusercontent.com/594574/42579868-7f1050dc-8529-11e8-8a58-8f46aaa58207.png">

This screenshot is of WebStorm following your own tslint rules with the tslint installed by your own package.json.

**Expected behavior**
No errors on every file when you want to fix a bug and make a PR.

**What is the motivation / use case for changing the behavior?**
Develop normally without surprises when save a file in a decent IDE like Webstorm or VisualStudio.

**Comment by rafa-as** [comment]
@cagataycivici you have some news about this?

**Comment by MikeMatusz** [comment]
Also working on a PR, and the overwhelming amount of red squigglies forced me to disable most of my linting.  I definitely think that if the rules aren't going to be followed, they should be disabled, but alternately, would the maintainers actually prefer if they were followed? Would they accept a PR that was purely cleanup to follow their defined rules?

**Comment by abelet** [comment]
I thought tslint  is for better code. Unfortunately we don't see anything else just red squiggles, so we turn of the tslint  inspection, and write some code which will force others to turn of the tslint  inspection. :)

**Comment by cagataycivici** [comment]
We'll apply the tslint changes of the style guide instead.

**Comment by rafa-as** [comment]
Amazing!
