### ISSUE TITLE
Hardcoded values assume left justified styling

### ISSUE THREAD

**Issue by meteorainer** [primefaces/primeng#6046]
https://github.com/primefaces/primeng/blob/83e24869f82762b5d6e55fc97a336f26d1e40d30/src/app/components/megamenu/megamenu.ts#L113

I'm submitting a ... (check one with "x")

[X ] feature request
**Current behavior**
megaMenu assumes left justification with it's parent by hardcoding `left: 0px;` into element style.

**Expected behavior**
-  Add a justification Input() to allow switch left/right in horizontal orientation, or top/bottom in vertical orientation.
- OR remove this code entirely in favor or css styling

**Comment by cagataycivici** [comment]
We'll redo the menus and will review this as well.
