### ISSUE TITLE
How to use latest PrimeNg version(6.0.0) in Angular 5.2 version?

### ISSUE THREAD

**Issue by parth23** [primefaces/primeng#6047]
How to use latest PrimeNg version(6.0.0) in Angular 5.2 version?
My project is in Angular 5.2 version and I have installed PrimeNg 5.2 but now I want to install latest version of PrimeNG because of some new features are provided, so how I can upgrade primeNG without upgrading Angular version.

**Comment by AbhijitMuke** [comment]
Update PrimeNg dependency with new version in Package.json and run `npm install command`

**Comment by Mysame** [comment]
Quoting https://www.primefaces.org/primeng-6-0-0-released/ 
```
PrimeNG 6.0.0 is fully compatible with Angular 6 and RxJS 6, if you are using Angular 5 then you need to continue using PrimeNG 5.x instead.
```

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.

**Comment by mshemadarshini** [comment]
> Please use forum for questions and help requests.

where is the forum?

**Comment by Jimit09** [comment]
> > Please use forum for questions and help requests.
> 
> where is the forum?

https://forum.primefaces.org/viewforum.php?f=35&sid=bb4dd04826ceb656bf4d2e6dd88dc625
