### ISSUE TITLE
primeng datatable(p-table) is not sorting when we use onLazyLoad event 

### ISSUE THREAD

**Issue by TameezM** [primefaces/primeng#6053]
**Current behavior**
singleSort or customSort are working fine when we don't use (onLazyLoad) event ) 

**Expected behavior**
singleSort or customSort should work when we use onLazyLoad event. 

**Minimal reproduction of the problem with instructions**
use onLazyLoad to reproduce the problem in any of the sample given in primeNg or put [pSortableColumn]="col.field" in scroll demo lazyLoad to reproduce it.

**What is the motivation / use case for changing the behavior?**
I'm using onLazyLoad for lazy load of data in p-table. when Im onLazyLoad, singleSort and customSort are working fine. By my requirement is I should delay the load process and I'm using pagination feature of p-table as well, I discovered pagination is not the problem, but lazLoad is the problem. Even customSort is not firing when we use onLazyLoad.

**Please tell us about your environment:**
VSCode, any development server

* **Angular version:** 5.2

* **PrimeNG version:** 6.0

* **Browser:** [all 

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by ctrl-brk** [comment]
In case of lazy loading you have to do your sorting on the server side

**Comment by cagataycivici** [comment]
Invalid issue.
