### ISSUE TITLE
Spinner only change value on mouseup

### ISSUE THREAD

**Issue by scurk1415** [primefaces/primeng#6054]
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When we click and hold on an arrow button on Spinner, it changes the values until we release the click.

**Expected behavior**
It would be nice to have a feature to disable this behavior so that the value changes only on mouseUp and not all the time when the button is pressed. So a long click will only change the value once.

**What is the motivation / use case for changing the behavior?**

* **Angular version:** 5.X
6

* **PrimeNG version:** 5.X
5.2

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
