### ISSUE TITLE
rowGroupMode="rowspan" set fixed column to group

### ISSUE THREAD

**Issue by Danieleeee** [primefaces/primeng#6057]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[X] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Hi,
when I use rowGroupMode="rowspan" the grouped column is the sorted one ([sortField]="my_row_group").
![1](https://user-images.githubusercontent.com/22749175/42682372-b5bce8c2-868a-11e8-85b4-05484160a514.png)

Is possible to fix the target column to group even if I select sort of another column?
![2](https://user-images.githubusercontent.com/22749175/42682416-d0d3984a-868a-11e8-8d31-2f640244b9fc.png)

Thanks

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 6.X

* **PrimeNG version:** 6.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Please use forum for support requests.
