### ISSUE TITLE
 ERROR ReferenceError: FullCalendar is not defined

### ISSUE THREAD

**Issue by wakra** [primefaces/primeng#6062]
hi, I need a help.
I'm working on a project with angular and I have installed a library PrimeNG & when I want to use full calendar of this library I get this error:  ERROR ReferenceError: FullCalendar is not defined

**Comment by saillemuin** [comment]
Same problem here.
Installed PrimeNg 6.0.1 and FullCalendar 4.0.0-alpha through npm

**Comment by saillemuin** [comment]
I solved this by refering to fullcalendar/dist/fullcalendar.js in stead of fullcalendar/dist/fullcalendar.**min**.js

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.

**Comment by kingzuru** [comment]
try using the following cdn, `https://cdn.jsdelivr.net/npm/fullcalendar@6.1.4/index.global.min.js`
