### ISSUE TITLE
p-tree onNodeSelect unterschiede bei klick und touch

### ISSUE THREAD

**Issue by atmike** [primefaces/primeng#6063]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows, Visual Studio, NPM, IIS

* **Angular version:** 5.X
"@angular/core": "^5.2.0",

* **PrimeNG version:** 5.X
"primeng": "^5.2.3"

* **Browser:** [all]
 
* **Language:** [all]

hello 
I had to realize today that it makes a difference whether you select a node in the p-tree with the mouse or with your finger. With the mouse you can select a selected node again and it remains selected. With Touch, the node is deselcted at the second touch. Can I treat the two methods the same, because I want one node to remain selected if you press it again.
Regards
Michael

**Comment by Macadoshis** [comment]
please translate the issue's title to english as well :)

**Comment by cagataycivici** [comment]
Please use forum for questions.

**Comment by atmike** [comment]
@cagataycivici: this is a bug not a question???
