### ISSUE TITLE
p-autocomplete advanced: dropdown list should open when clicked on input

### ISSUE THREAD

**Issue by moma1806** [primefaces/primeng#6064]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap

```

**Current behavior**
We use p-autocomplete advanced as dropdown select element with autocomplete function and dropdown button. When clicking on the input field, dropdown does not open. 
Similar issue:
https://github.com/primefaces/primeng/issues/5306

**Expected behavior**
Usually, users expect dropdown selects to open when clicking on it. Of course, there should not be thousands of elements in the dropdown, in this case the typeahead function (p-autocomplete basic) would be much suitable.
For example, look at SelectOneMenu advanced from PrimeFaces:
https://www.primefaces.org/showcase/ui/input/oneMenu.xhtml
or at dropdown with filters:
https://www.primefaces.org/primeng/#/dropdown

**Minimal reproduction of the problem with instructions**
Autocomplete advanced, click on input field:
https://www.primefaces.org/primeng/#/autocomplete

**What is the motivation / use case for changing the behavior?**
On usability-tests, user first click on the input and afterwards on the opening button next the field. They expect something to happen when clicking on the input. It seems inefficient they have to click twice to open the dropdown list.

**Please tell us about your environment:**
Windows 10, Eclipse Oxygen 4.7

* **Angular version:** 5.X
version: 5.1.0

* **PrimeNG version:** 5.X
version: 5.2.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   
version: 7.5.0

**Comment by cagataycivici** [comment]
We'll consider it if there is more demand, thank you.

**Comment by cagriman** [comment]
Hi, 

Is SelectOneMenu advanced from PrimeFaces component developped or not?   

Thanks

**Comment by cagriman** [comment]
> Hi,
> 
> Is SelectOneMenu advanced from PrimeFaces component developped or not?
> 
> Thanks

I solved my problem as below using same text in placeHolder and selectedItem template.

Thanks


`<p-dropdown #dropdown [options]="optionList" [(ngModel)]="selectedOption" optionLabel="label" [filter]="true"
    filterBy="label" [showClear]="false" dropdownIcon="pi pi-plus" placeholder="**Add**"
    (onChange)="onChangeDropdown($event, dropdown)">
    <ng-template pTemplate="selectedItem">
        <div *ngIf="selectedOption">
            <div>**Add**</div>
        </div>
    </ng-template>
    <ng-template let-option pTemplate="option">
        <div>
            <div>{{option.text}}</div>
        </div>
    </ng-template>
</p-dropdown>`
