### ISSUE TITLE
avoid code duplication in p-table responsive 

### ISSUE THREAD

**Issue by moma1806** [primefaces/primeng#6065]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap

```
**Current behavior**
When you use the [responsive]="true" property at p-table, you need to program the column header in every table cell as span-element, so that it will display in responsive mode as label. 

**Expected behavior**
The component should add automatically the headers as label to the cells, because the headers are already set in table header

**Minimal reproduction of the problem with instructions**
See tableresponsivedemo
https://www.primefaces.org/primeng/#/table/responsive

**What is the motivation / use case for changing the behavior?**
Avoid code duplication, because we use only dynamic rows and not dynamic columns.

**Please tell us about your environment:**
Windows 10, Eclipse Oxygen 4.7

* **Angular version:** 5.X
version: 5.1.0

* **PrimeNG version:** 5.X
version: 5.2.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   
version: 7.5.0

**Comment by cagataycivici** [comment]
As you have full control over the presentation and markup, you can implement this the way you like, the responsive demo just shows only one way.
