### ISSUE TITLE
p-table: lazy + column with filter and order bug

### ISSUE THREAD

**Issue by Danieleeee** [primefaces/primeng#6067]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**

In turbo table with lazy loading and columns with sort + filter, is impossible to filter, sort fires always.
`<th [pSortableColumn]   = "'RCE_DATARIC'"> Data Rice         
                        <p-sortIcon [field] = "'RCE_DATARIC'"></p-sortIcon>
                        <div>
                        <input pInputText type="text" (input)="dt.filter($event.target.value, 'RCE_DATARIC', 'CONTAINS')"> 
                        </div>                                   
                    </th>
`

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 6.X

* **PrimeNG version:** 6.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by ctrl-brk** [comment]
It's unclear what the issue is. In lazy load mode sorting and filtering are on you to be done on the server site.

**Comment by Danieleeee** [comment]
I do sort in server side. The problem is sort column+filter as I show in the code.
If I click on filter, sort start. It seems that filter is covered by sort function.

**Comment by ctrl-brk** [comment]
When you perform either sort or search it should make a request to the server side and not sort locally. Seems to be working fine for me.

**Comment by ctrl-brk** [comment]
There should be only lazyLoad events, you don't need anything else.

**Comment by Danieleeee** [comment]
I know

**Comment by Danieleeee** [comment]
I solved.
The problem was that I put sort and filter in the same <tr>.
I made separate <tr></tr> for filters and now work.
