### ISSUE TITLE
Button causes dropdown to shift downward

### ISSUE THREAD

**Issue by adama357** [primefaces/primeng#6068]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-4vk1jc-7qwyrs

**Current behavior**
If there's a button next to a dropdown, the dropdown is shifted slightly downward. (I added the red line to show the alignment with and without the button.) 
Chrome:
![shifted_dropdown](https://user-images.githubusercontent.com/20462430/42707664-a0ea97e4-86a0-11e8-8364-589a9a337c6b.png)

Firefox:
![shifted_dropdown_ff](https://user-images.githubusercontent.com/20462430/42709138-221a510c-86a5-11e8-8dab-301fb93b9da9.png)

**Expected behavior**
The dropdown's position shouldn't be altered by having a button next to it; it should be aligned correctly with the button. 

* **Angular version:** ~6.0.4

* **PrimeNG version:** ~6.0.0

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
