### ISSUE TITLE
Virtual Scroll - local object- 250K Rows-without loading icon 20 rows on every scroll

### ISSUE THREAD

**Issue by SIVANAGARAJ** [primefaces/primeng#6069]
I have 500 records in local angular object and i wanted to **load n rows (20 rows) on every scroll smoothly without loading icon/delay and empty space**.i tried to implement angular2-virtual-scroll in primeng turbo table,but i cant able to do.Please implement smooth lazy loading like "angular2-virtual-scroll" npm.
![250k](https://user-images.githubusercontent.com/30038413/42727706-12d03502-87c9-11e8-82d9-b37ace6dc56e.JPG)
![angular2-virtual-scroll](https://user-images.githubusercontent.com/30038413/42727728-4173836e-87c9-11e8-88ee-e28f53ea76f7.JPG)

**Comment by yigitfindikli** [comment]
http://primefaces.org/primeng/#/virtualscroller active now. You can use Prepopulated List example.
