### ISSUE TITLE
[Enhancement] [Dialog] Dialog position attributes

### ISSUE THREAD

**Issue by gatapia** [primefaces/primeng#607]
I would like to position my dialog at the top of the screen however it appears at the bottom with my current page layer and there is no way to specify the top/left position.

CSS is hard as the .ui-dialog element has an attribute level style (top/left) which takes precedence over most non hacky css.

Please add [top] and [left] attributes to the Dialog. Or add better support for ngStyle={top/left}

Note: A workaround is putting in a global CSS (cannot be an encapsulated component css) with:

```
.ui-dialog {
  top: 60px !important;
}
```

**Comment by sievert** [comment]
This prevents the draggable in vertical directions

**Comment by shahidmau** [comment]
+1

**Comment by livindg** [comment]
+1

**Comment by stannynuytkens** [comment]
Seriously, ***Jul 14 2016***!
Also, people ( @shahidmau @livindg ) need to learn to upvote instead of commenting _+1_

**Comment by morganRotaStabelli** [comment]
I need it! My dialog has tabs and one of them is more tall than half page! For the moment the gatapia's patch works but it's not an acceptable solution....

**Comment by Mutmansky** [comment]
I'm using a different work-around, but it's not really any more desirable:

`    this.myDialog.container.style.left = openButton.nativeElement.offsetLeft + 'px';
     this.myDialog.container.style.top = openButton.nativeElement.offsetTop + pButton.nativeElement.offsetHeight + 'px';`

So I'm using an ElementRef to the button that opens the dialog to position the dialog directly beneath the button that opened it.  In some cases (where the button is near the bottom of the app), I'm positioning the dialog in relation to the top and left of the app.

**Comment by cagataycivici** [comment]
Via 1913
