### ISSUE TITLE
Add currentPageReport option to Paginator

### ISSUE THREAD

**Issue by pantonis** [primefaces/primeng#6070]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

In turbotable paginator must show or have an option to show what data are being currently shown. 99% of datatables out there offer this option. I know that there is an option to do that by adding custom paginator but in my scenarion that I have dozeons of tables is difficult to maintain this. See screenshot below:

![image](https://user-images.githubusercontent.com/3295086/42736044-643c0936-8867-11e8-94d9-fdea7e6c4a38.png)

**Comment by daphnecorrea** [comment]
I second this request. This as a usability issue in that users do not see a total number of items in their results.  What can I do to raise awareness on this issue?

**Comment by pantonis** [comment]
@daphnecorrea apparently no one cares :)
