### ISSUE TITLE
Menu position is not aligned properly when "appendTo" is added and issue when button position is fixed

### ISSUE THREAD

**Issue by sarikafiorano** [primefaces/primeng#6073]
**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-drd235-xxbc4d?embed=1&file=src/app/app.component.html

**Current behavior**
Case1. When "appendTo" property is added to menu, menu is appearing at some random position .
Case2. Make button position fixed and remove "appendTo" property for menu. Try scrolling the page, button doesnt scroll (since position is fixed) but menu will scroll

**Expected behavior**
For Case1. Menu should appear exactly above or below the button.
For Case2. When button position is fixed and "appendTo" property is removed, menu shouldn't scroll (should be aligned with button) 

* **Angular version:** 6.0.7

* **PrimeNG version:**  6.0.0

**Comment by cagataycivici** [comment]
You need to use appendTo to a scrolling container in this case not the body.
