### ISSUE TITLE
Paginator css doesn't allow a page with more than 3 numbers

### ISSUE THREAD

**Issue by lippomano** [primefaces/primeng#6075]
```
[X] bug report => Search github for a similar issue or PR before submitting
```

**Current behavior**
If the page in the paginator has more than 3 numbers css is broken:
![paginator](https://user-images.githubusercontent.com/27501745/42753280-b283b862-88f0-11e8-8dd9-2afcaac54ae5.PNG)

If I set `width: auto` it seems ok.

* **Angular version:** 6.X

* **PrimeNG version:** 6.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG (You can see in https://stackblitz.com/edit/github-xhsr5g ). If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
