### ISSUE TITLE
Tree table cell selection issue..

### ISSUE THREAD

**Issue by AravindBJ** [primefaces/primeng#6078]
**I wanted data from a particular cell to be used, on clicking that particular cell. 

Please suggest if there is some way to get the data from a particular cell, on clicking a particular cell.**

**Comment by mscud** [comment]
```typescript
<p-treeTable (onNodeSelect)="doSomething($event.node)">
```

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.
