### ISSUE TITLE
MultiSelect needs a dom flag when nothing is selected

### ISSUE THREAD

**Issue by kroeder** [primefaces/primeng#6079]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
MultiSelect has no "placeholder" property. Instead it uses a "defaultValue"

`
defaultLabel | string | Label to display when there are no selections.
`

When I inspect the multiSelect DOM-Element I can't see if it's a selected value or just a placeholder value. Therefore I can't style it as a placeholder

**Expected behavior**
1) It should behave like dropdown and offer a [placeholder] if `selectedItems.length === 0`. This would be more intuitive as well because both components would use the same placeholder api and more importantly, placeholder is a well-known term and HTML-Tag for inputs
2) If not possible it should at least show something like `<div title="defaultLabelXyz" no-selection="true"></div>` or something

**Minimal reproduction of the problem with instructions**
See documentation https://www.primefaces.org/primeng/#/multiselect

**What is the motivation / use case for changing the behavior?**
Make it possible to detect and style MultiSelect if no item is selected

* **Angular version:** 6.0.x

* **PrimeNG version:** 6.0.1

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
