### ISSUE TITLE
how to add other value to the input AutoComplete Multiple ?

### ISSUE THREAD

**Issue by ducduongtmb** [primefaces/primeng#608]
I want to use it like a tags input autocompete . But when I use the input AutoComplete Multiple of primeFace , I just enter defaut value text (what I config in code before ) , can't pass my text to the input AutoComplete Multiple . Thanks for any help .

**Comment by kamran-pervaiz** [comment]
did you find anything about it? because i want to use tag based dropdown as well

**Comment by schellmax** [comment]
also interested in a solution to this ('Tag input with autocomplete AND "add new" option'):
* 'AutoComplete' doesn't allow for adding new values
* 'Chips' doesn't have an autocomplete for existing values

**Comment by elega9t** [comment]
Hi,

I would like to use autocomplete multi with support for adhoc strings aswell. Is it possible?

**Comment by sourabh8003** [comment]
@elega9t  
@schellmax 

Hi Guys,

It is possible to add new values as chips in autocomplete multi. I have created a custom component with the help of chips and autocomplete components and its working fine for me. So you can also try to merge these two features in a single component or if you still need that feature then i can share my components with you guys. Just let me know in such case.

**Comment by elega9t** [comment]
@sourabh8003 

Wow, thats great news. Do you mind creating a github sample project and share your component.

Thanks

**Comment by sourabh8003** [comment]
@elega9t 

Sure

**Comment by sourabh8003** [comment]
Hi guys,

@elega9t  @ducduongtmb  @ducduongtmb 

Currently i am working on a downstream repository of prineNg. It will take some time so for now you can use below code to add new values in autocomplete with chips, tab click also adds chips. Follow the steps below and in case of any issue reply me: 

`import {NgModule, Component, ViewChild, ElementRef, AfterViewInit, AfterContentInit, AfterViewChecked, DoCheck, Input, Output, EventEmitter, ContentChildren, QueryList, TemplateRef, IterableDiffers, Renderer, forwardRef} from '@angular/core';
import {CommonModule} from '@angular/common';
import {InputTextModule} from '../../../../node_modules/primeng/components/inputtext/inputtext';
import {ButtonModule} from '../../../../node_modules/primeng/components/button/button';
import { ttTooltipModule } from './tt-tooltip.directive';
import {SharedModule, PrimeTemplate} from '../../../../node_modules/primeng/components/common/shared';
import {DomHandler} from '../../../../node_modules/primeng/components/dom/domhandler';
import {NG_VALUE_ACCESSOR, ControlValueAccessor} from '@angular/forms';

export const AUTOCOMPLETE_VALUE_ACCESSOR: any = {
  provide: NG_VALUE_ACCESSOR,
  useExisting: forwardRef(() => SAutocompleteWithChips),
  multi: true
};

@Component({
    selector: 's-autoComplete',
    template: `
        <span [ngClass]="{'ui-autocomplete ui-widget':true,'ui-autocomplete-dd':dropdown,'ui-autocomplete-multiple':multiple}" [ngStyle]="style" [class]="styleClass">
            <input *ngIf="!multiple" #in pInputText type="text" [ngStyle]="inputStyle" [class]="inputStyleClass" autocomplete="off"
            [value]="value ? (field ? resolveFieldData(value)||value : value) : null" (input)="onInput($event)" (keydown)="onKeydown($event,inputtext)" (focus)="onFocus()" (blur)="onBlur()"
            [attr.placeholder]="placeholder" [attr.size]="size" [attr.maxlength]="maxlength" [attr.tabindex]="tabindex" [readonly]="readonly" [disabled]="disabled"
            [ngClass]="{'ui-autocomplete-input':true,'ui-autocomplete-dd-input':dropdown}"
            ><ul *ngIf="multiple" class="ui-autocomplete-multiple-container ui-widget ui-inputtext ui-state-default ui-corner-all" [ngClass]="{'ui-state-disabled':disabled,'ui-state-focus':focus}" (click)="multiIn.focus()">
                <li #token *ngFor="let val of value" class="ui-autocomplete-token ui-state-highlight ui-corner-all">
                    <span class="ui-autocomplete-token-icon fa fa-fw fa-close" (click)="removeItem(token)"></span>
                    <span class="ui-autocomplete-token-label">{{field ? val[field] : val}}</span>
                </li>
                <li class="ui-autocomplete-input-token">
                    <input #multiIn type="text" [disabled]="disabled" pInputText [attr.placeholder]="placeholder" [attr.tabindex]="tabindex" (input)="onInput($event)" (keydown)="onKeydown($event)" (focus)="onFocus()" (blur)="onBlur()" autocomplete="off">
                </li>
            </ul
            ><button type="button" pButton icon="fa-fw fa-caret-down" class="ui-autocomplete-dropdown" [disabled]="disabled"
                (click)="handleDropdownClick($event)" *ngIf="dropdown" (focus)="onDropdownFocus($event)" (blur)="onDropdownBlur($event)"></button>
            <div class="ui-autocomplete-panel ui-widget-content ui-corner-all ui-shadow" [style.display]="panelVisible ? 'block' : 'none'" [style.width]="appendTo ? 'auto' : '100%'" [style.max-height]="scrollHeight">
                <ul class="ui-autocomplete-items ui-autocomplete-list ui-widget-content ui-widget ui-corner-all ui-helper-reset">
                    <li *ngFor="let option of suggestions" [ngClass]="{'ui-autocomplete-list-item ui-corner-all':true,'ui-state-highlight':(highlightOption==option)}"
                        (mouseenter)="highlightOption=option" (mouseleave)="highlightOption=null" (click)="selectItem(option)">
                        <span *ngIf="!itemTemplate">{{field ? option[field] : option}}12</span>
                        <template *ngIf="itemTemplate" [pTemplateWrapper]="itemTemplate" [item]="option"></template>
                    </li>
                </ul>
            </div>
        </span>
    `,
    host: {
        '[class.ui-inputwrapper-filled]': 'filled',
        '[class.ui-inputwrapper-focus]': 'focus'
    },
    providers: [DomHandler, AUTOCOMPLETE_VALUE_ACCESSOR]
})
export class SAutocompleteWithChips implements AfterContentInit,AfterViewInit,DoCheck,AfterViewChecked,ControlValueAccessor {
    
    @Input() minLength: number = 1;
    
    @Input() delay: number = 300;
    
    @Input() style: any;
    
    @Input() styleClass: string;
    
    @Input() inputStyle: any;
    
    @Input() inputStyleClass: string;
    
    @Input() placeholder: string;
    
    @Input() readonly: boolean;
        
    @Input() disabled: boolean;
    
    @Input() maxlength: number;
    
    @Input() size: number;
    
    @Input() suggestions: any[];

    @Input() appendTo: any;

    @Output() completeMethod: EventEmitter<any> = new EventEmitter();
    
    @Output() onSelect: EventEmitter<any> = new EventEmitter();
    
    @Output() onUnselect: EventEmitter<any> = new EventEmitter();
    
    @Output() onDropdownClick: EventEmitter<any> = new EventEmitter();

    @Output() onAdd: EventEmitter<any> = new EventEmitter();
    
    @Input() field: string;
    
    @Input() scrollHeight: string = '200px';
    
    @Input() dropdown: boolean;
    
    @Input() multiple: boolean;

    @Input() tabindex: number;
    
    @ContentChildren(PrimeTemplate) templates: QueryList<any>;
    
    public itemTemplate: TemplateRef<any>;
    
    value: any;
    
    onModelChange: Function = () => {};
    
    onModelTouched: Function = () => {};
    
    timeout: any;
    
    differ: any;
    
    panel: any;
    
    input: any;
    
    multipleContainer: any;
    
    panelVisible: boolean = false;
    
    documentClickListener: any;
    
    suggestionsUpdated: boolean;
    
    highlightOption: any;
    
    highlightOptionChanged: boolean;
    
    focus: boolean = false;
    
    dropdownFocus: boolean = false;
    
    filled: boolean;
    
    @ViewChild('in') inputEL: ElementRef;
    
    constructor(public el: ElementRef, public domHandler: DomHandler, differs: IterableDiffers, public renderer: Renderer) {
        this.differ = differs.find([]).create(null);
    }
    
    ngDoCheck() {
        let changes = this.differ.diff(this.suggestions);
        if(changes && this.panel) {
            if(this.suggestions && this.suggestions.length) {
                this.show();
                this.suggestionsUpdated = true;
            }
            else {
                this.hide();
            }
        }
    }
    
    ngAfterContentInit() {
        this.templates.forEach((item) => {
            switch(item.getType()) {
                case 'item':
                    this.itemTemplate = item.template;
                break;
                
                default:
                    this.itemTemplate = item.template;
                break;
            }
        });
    }
    
    ngAfterViewInit() {
        this.input = this.domHandler.findSingle(this.el.nativeElement, 'input');
        this.panel = this.domHandler.findSingle(this.el.nativeElement, 'div.ui-autocomplete-panel');
        
        if(this.multiple) {
            this.multipleContainer = this.domHandler.findSingle(this.el.nativeElement, 'ul.ui-autocomplete-multiple-container');
        }
        
        this.documentClickListener = this.renderer.listenGlobal('body', 'click', () => {
            this.hide();
        });

        if(this.appendTo) {
            if(this.appendTo === 'body')
                document.body.appendChild(this.panel);
            else
                this.domHandler.appendChild(this.panel, this.appendTo);
        }
    }
    
    ngAfterViewChecked() {
        if(this.suggestionsUpdated) {
            this.align();
            this.suggestionsUpdated = false;
        }
        
        if(this.highlightOptionChanged) {
            let listItem = this.domHandler.findSingle(this.panel, 'li.ui-state-highlight');
            if(listItem) {
                this.domHandler.scrollInView(this.panel, listItem);
            }
            this.highlightOptionChanged = false;
        }
    }
    
    writeValue(value: any) : void {
        this.value = value;
        this.filled = this.value && this.value != '';
    }
    
    registerOnChange(fn: Function): void {
        this.onModelChange = fn;
    }

    registerOnTouched(fn: Function): void {
        this.onModelTouched = fn;
    }
    
    setDisabledState(val: boolean): void {
        this.disabled = val;
    }

    onInput(event: any ) {
        let value = event.target.value;
        if(!this.multiple) {
            this.value = value;
            this.onModelChange(value);
        }
        
        if(value.length === 0) {
           this.hide();
        }
        
        if(value.length >= this.minLength) {
            //Cancel the search request if user types within the timeout
            if(this.timeout) {
                clearTimeout(this.timeout);
            }

            this.timeout = setTimeout(() => {
                this.search(event, value);
            }, this.delay);
        }
        else {
            this.suggestions = null;
        }
        this.updateFilledState();
    }
    
    search(event: any, query: string) {
        //allow empty string but not undefined or null
       if(query === undefined || query === null) {
           return;
       }
       
       this.completeMethod.emit({
           originalEvent: event,
           query: query
       });
    }
            
    selectItem(option: any) {
        if(this.multiple) {
            this.input.value = '';
            this.value = this.value||[];
            if(!this.isSelected(option)) {
                this.value.push(option);
                this.onModelChange(this.value);
            }
        }
        else {
            this.input.value = this.field ? this.resolveFieldData(option): option;
            this.value = option;
            this.onModelChange(this.value);
        }
        
        if(typeof option === "object"){
            this.onSelect.emit(option);
        }else{
            this.onSelect.emit(option);
            this.onAdd.emit({
                originalEvent: event,
                value: option
            });
        }

        
        this.input.focus();
    }
    
    show() {
        if(!this.panelVisible && (this.focus||this.dropdownFocus)) {
            this.panelVisible = true;
            this.panel.style.zIndex = ++DomHandler.zindex;
            this.domHandler.fadeIn(this.panel, 200);
        }        
    }
    
    align() {
        if(this.appendTo)
            this.domHandler.absolutePosition(this.panel, (this.multiple ? this.multipleContainer : this.input));
        else
            this.domHandler.relativePosition(this.panel, (this.multiple ? this.multipleContainer : this.input));
    }
    
    hide() {
        this.panelVisible = false;
    }
    
    handleDropdownClick(event: any) {
        this.onDropdownClick.emit({
            originalEvent: event,
            query: this.input.value
        });
    }
    
    removeItem(item: any) {
        let itemIndex = this.domHandler.index(item);
        let removedValue = this.value.splice(itemIndex, 1)[0];
        this.onUnselect.emit(removedValue);
        this.onModelChange(this.value);
    }
    
    resolveFieldData(data: any): any {
        if(data && this.field) {
            if(this.field.indexOf('.') == -1) {
                return data[this.field];
            }
            else {
                let fields: string[] = this.field.split('.');
                let value = data;
                for(var i = 0, len = fields.length; i < len; ++i) {
                    value = value[fields[i]];
                }
                return value;
            }
        }
        else {
            return null;
        }        
    }
    
    onKeydown(event:any , inputEL: HTMLInputElement) {
        if(this.panelVisible) {
            let highlightItemIndex = this.findOptionIndex(this.highlightOption);
            
            switch(event.which) {
                //down
                case 40:
                    if(highlightItemIndex != -1) {
                        var nextItemIndex = highlightItemIndex + 1;
                        if(nextItemIndex != (this.suggestions.length)) {
                            this.highlightOption = this.suggestions[nextItemIndex];
                            this.highlightOptionChanged = true;
                        }
                    }
                    else {
                        this.highlightOption = this.suggestions[0];
                    }
                    
                    event.preventDefault();
                break;
                
                //up
                case 38:
                    if(highlightItemIndex > 0) {
                        let prevItemIndex = highlightItemIndex - 1;
                        this.highlightOption = this.suggestions[prevItemIndex];
                        this.highlightOptionChanged = true;
                    }
                    
                    event.preventDefault();
                break;
                
                //enter
                case 13:
                    if(this.highlightOption) {
                        
                        this.selectItem(this.highlightOption);
                        this.hide();
                    }
                    event.preventDefault();
                break;
                
                //escape
                case 27:
                    this.hide();
                    event.preventDefault();
                break;

                
                //tab
                case 9:
                    if(this.highlightOption) {
                        this.selectItem(this.highlightOption);
                    }
                    this.hide();
                break;
            }
        } else {
            if(event.which === 40 && this.suggestions) {
                this.search(event, event.target.value);
            } else if(event.which === 13) {
                this.selectItem(event.target.value);
                event.preventDefault();
            } else if(event.which === 9) {
                this.selectItem(event.target.value);
            }
        }
        
        if(this.multiple) {
            switch(event.which) {
                //backspace
                case 8:
                    if(this.value && this.value.length && !this.input.value) {
                        let removedValue = this.value.pop();
                        this.onUnselect.emit(removedValue);
                        this.onModelChange(this.value);
                    }
                break;
            }
        }
    }
    
    onFocus() {
        this.focus = true;
    }
    
    onBlur() {
        this.focus = false;
        this.onModelTouched();
    }
    
    onDropdownFocus() {
        this.dropdownFocus = true;
        this.inputEL.nativeElement.focus();
    }
    
    onDropdownBlur() {
        this.dropdownFocus = false;
    }
    
    isSelected(val: any): boolean {
        let selected: boolean = false;
        if(this.value && this.value.length) {
            for(let i = 0; i < this.value.length; i++) {
                if(this.domHandler.equals(this.value[i], val)) {
                    selected = true;
                    break;
                }
            }
        }
        return selected;
    }
    
    findOptionIndex(option: any): number {        
        let index: number = -1;
        if(this.suggestions) {
            for(let i = 0; i < this.suggestions.length; i++) {
                if(this.domHandler.equals(option, this.suggestions[i])) {
                    index = i;
                    break;
                }
            }
        }
                
        return index;
    }
    
    updateFilledState() {
        this.filled = this.input && this.input.value != '';
    }
    
    ngOnDestroy() {
        if(this.documentClickListener) {
            this.documentClickListener();
        }

        if(this.appendTo) {
            this.el.nativeElement.appendChild(this.panel);
        }
    }
}

@NgModule({
    imports: [CommonModule,InputTextModule,ButtonModule,SharedModule,ttTooltipModule],
    exports: [SAutocompleteWithChips,InputTextModule,SharedModule],
    declarations: [SAutocompleteWithChips]
})
export class SAutocompleteWithChipsModule { }
`

Step 1> update the paths with your node_module folder path with primeNg in the above code

import {InputTextModule} from '../../../../node_modules/primeng/components/inputtext/inputtext';
import {ButtonModule} from '../../../../node_modules/primeng/components/button/button';
import { ttTooltipModule } from './tt-tooltip.directive';
import {SharedModule, PrimeTemplate} from '../../../../node_modules/primeng/components/common/shared';
import {DomHandler} from '../../../../node_modules/primeng/components/dom/domhandler';

Step 2> Import the custom autocomplete module "SAutocompleteWithChipsModule" in your module.

Step 3> use the compnent with the primeNg's original attributes but with new selector "<s-autoComplete></s-autoComplete>"

<s-autoComplete [(ngModel)]="text" [suggestions]="results" (completeMethod)="search($event)"></s-autoComplete>

Then Enjoy!

**Comment by doeringp** [comment]
My solution for having an autocomplete component (for multiple tags) with the the possibility of adding custom texts was using the onKeyUp-event. I've implemented an event handler that adds my custom text to the list, each time I press the Enter key.

Code sample: https://stackblitz.com/edit/angular-kfvj5p

**Comment by bkhushang** [comment]
@doeringp : Kudos.. You saved my so many hours.... Thanks.

**Comment by yagizozturk** [comment]
@doeringp : Thank you very much

**Comment by Antilamer1709** [comment]
@doeringp thanks, exactly what I have been looking for!

**Comment by PrathyushaRecherla** [comment]
> My solution for having an autocomplete component (for multiple tags) with the the possibility of adding custom texts was using the onKeyUp-event. I've implemented an event handler that adds my custom text to the list, each time I press the Enter key.
> 
> Code sample: https://stackblitz.com/edit/angular-kfvj5p
@doeringp can you help in fixing the same with outside click event. I have to add the value when user enter some letters and clicks outside of the input field.

**Comment by earshinov** [comment]
FYI, here is a request to have this feature built in: https://github.com/primefaces/primeng/issues/3211

**Comment by jncalderon** [comment]
thanks!! nice job!! helpful for me, regards!

**Comment by jBuchholz590** [comment]
I used a similar approach listening for changes to the autoComplete's value and then adding the current value to the list of entries:

Template
```
<p-autoComplete (keyup)=inputChanged($event)" [suggestions]="existingPlusCurrent" ...>
```

Controller
```
existing: [] // some list of values to be used
existingPlusCurrent: [] // array that is used by the autoComplete

inputChanged(event: KeyboardEvent): void {
    const value = event.srcElement.value;
    if (this.existing.indexOf(value) === -1) {
      this.existingPlusCurrentLabel = [value, ...this.existingLabels];
    } else {
      this.existingPlusCurrentLabel = this.existingLabels;
    }
}
```

**Comment by agm1984** [comment]
I just ported this @doeringp Angular solution over to Vue 3 if anyone needs it:

```vue
import Autocomplete from 'primevue/autocomplete';

const handleAddNewEmail = (event) => {
    const newVal = [
        ...props.sentTo,
        event.srcElement.value,
    ];

    v$.value.sent_to.$model = newVal;
    emit('update:sent-to', newVal);

    event.srcElement.value = '';
};

...

                <Autocomplete
                    v-model="v$.sent_to.$model"
                    :suggestions="[
                        'admin@example.com',
                        'hr@example.com',
                        'jason@friday13.com',
                        'vpsales@example.com',
                        'all@example.com',
                        'team@example.com',
                    ]"
                    multiple
                    @keydown.enter="handleAddNewEmail"
                />
```

The important thing is to hook into the `keydown` event with `.enter` event modifier. This will fire your function with the first parameter being the keyboard event.

Next, the critically important thing and really all you need is `event.srcElement.value`. You can push that value into your v-model value (which is an array), and then you can wipe the value by setting `event.srcElement.value` to `""`.

**Comment by faileon** [comment]
Zombie thread, I know, but in case anyone stumbles upon this and requires an easy solution - what you can do is prepend the query in the `completeMethod` handler. No need to fiddle with the `keyUp` event.

Modyfing the example from the docs it would look something like this:
```ts
filterCountry(event) {
        //in a real application, make a request to a remote url with the query and return filtered results, for demo we filter at client side
        let query = event.query;
        // also suggest the query itself
        let filtered: any[] = [query];

        for (let i = 0; i < this.countries.length; i++) {
            let country = this.countries[i];
            if (country.name.toLowerCase().indexOf(query.toLowerCase()) == 0) {
                filtered.push(country);
            }
        }

        this.filteredCountries = filtered;
    }
```
