### ISSUE TITLE
Frozen columns not getting exported

### ISSUE THREAD

**Issue by Liviano** [primefaces/primeng#6083]
I've created a p-table with frozen columns and export as CSV option, when i export the columns in frozen style columns are not getting exported.

Angular version: 6.0.3

PrimeNG version: 5.2.4

Browser:  Chrome XX | Firefox XX | IE XX | Safari XX 
 
Language: TypeScript 2.7.2 | ES6

Node : 9.7.1

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
