### ISSUE TITLE
NgModel supported by Tree component

### ISSUE THREAD

**Issue by ofekdeitch** [primefaces/primeng#6088]
Hello,

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
Would like to be able to use the Tree component within an `NgForm`.
(Requiring the Tree class to implement the `ControlValueAccessor` interface)

Thank you :smile:

**Comment by cagataycivici** [comment]
It is a data component not a form component.

**Comment by pwretmo** [comment]
@cagataycivici, can you elaborate on the difference between a data component and form component?

I don't understand why using a Tree using e.g. selectionMode="checkbox" would not be a valid use case for a NgForm?
