### ISSUE TITLE
table.reset() - not deleting the filters from input

### ISSUE THREAD

**Issue by attina-claudia** [primefaces/primeng#6089]
I'm submitting a bug report .

**Plunkr Case (Bug Reports)**
https://github-vmghz6.stackblitz.io 

**Current behavior**
Reset table method is not deleting the filters from UI

**Expected behavior**
Reset table method should delete the filters 

**Minimal reproduction of the problem with instructions**
Filter the Summary table (see example) by Failed field.
Press reset.

The example is with the basic table but it's also NOT working with dynamic cols.

  ```
<ng-template pTemplate="header" let-columns>
      <tr>
        <th *ngFor="let col of columns" [pSortableColumn]="col.field">
          {{col.header}}
          <p-sortIcon [field]="col.field"></p-sortIcon>
        </th>
      </tr>
      <tr>
        <th *ngFor="let col of columns">
          <input pInputText type="text" (input)="dt.filter($event.target.value, col.field, 'contains')">
        </th>
      </tr>
    </ng-template>

```

**Comment by attina-claudia** [comment]
code can be seen at [https://stackblitz.com/edit/github-vmghz6?file=src/app/app.component.html]

**Comment by attina-claudia** [comment]
fixed. https://stackblitz.com/edit/github-vmghz6-ytjegc?file=src/app/app.component.html

For input fields just add  [value]="dt.filters[<field>] ? dt.filters[<field>].value : ''" where <field> is the field send in the (input) method (input)="dt.filter($event.target.value,<field>, 'contains')".

For example:
 <th>
        <input pInputText type="text" (input)="dt.filter($event.target.value, 'date', 'contains')"
       [value]="dt.filters['date'] ? dt.filters['date'].value : ''">
    </th>

**Comment by cagataycivici** [comment]
As you define the filter elements, you need to implement it on your side using binding the value as you've done above.
