### ISSUE TITLE
Button stays dark after click in Ecuador 

### ISSUE THREAD

**Issue by intergleam** [primefaces/primeng#6090]
```
[x ] bug report 
```

The buttons in Ecuador template stay dark after clicking. Expected - button should regain color after releasing the mouse. 

![image](https://user-images.githubusercontent.com/2155554/42825772-2f864742-89fc-11e8-9a5e-1fae85a0784e.png)

**Comment by cagataycivici** [comment]
Should be fixed in next Ecuador release, @Merve7 ?

**Comment by Merve7** [comment]
of course 👍

**Comment by intergleam** [comment]
thanks guys for awesome work. Please note that other themes also have this issue

**Comment by cagataycivici** [comment]
We've fixed the ones that have it, 6.1.0 updates will start this week that contain this one as well.

**Comment by Merve7** [comment]
Fixed for Ecuador 6.1.0
