### ISSUE TITLE
editable treetable documentation error

### ISSUE THREAD

**Issue by asagajda** [primefaces/primeng#6092]
I'm submitting an error found in documentation: https://www.primefaces.org/primeng/#/treetable (Editing section)

* **PrimeNG version:** 6.0.1

Trying this is not working (tried according to documentation):
`<td [ttEditableColumn]="rowData" [ttEditableColumnField]="'year'">`

This example should be replaced with:
```
<p>If you require the edited row data and the field at onEditComplete event, bind the data to pEditableColumn and pEditableColumnField properties of ttEditableColumn directive</p>
<td ttEditableColumn [pEditableColumn]="rowData" [pEditableColumnField]="'year'">
```
After changing code like this I got expected behaviour

**Comment by asagajda** [comment]
Created PR [](https://github.com/primefaces/primeng/pull/6093)

**Comment by cagataycivici** [comment]
Merged
