### ISSUE TITLE
Dropdown with Tree Multiselect - New component

### ISSUE THREAD

**Issue by nsksaisaravana** [primefaces/primeng#6099]
Please provide a new drop-down component (current features) with tree multi-select. Please refer the below url for the futher details.

https://codepen.io/alanbriolat/pen/QjzNYV

![image](https://user-images.githubusercontent.com/17681573/42919202-206d4e8c-8b54-11e8-80f1-191de34af1dc.png)

**Comment by nsksaisaravana** [comment]
This component should be able to append to table and tree table, which helps to filter in the table.

**Comment by nsksaisaravana** [comment]
Please check the below url

https://github.com/leovo2708/ngx-treeview

https://leovo2708.github.io/ngx-treeview/#/components

![image](https://user-images.githubusercontent.com/17681573/45795898-761bd880-bce1-11e8-8fea-d4a69c61ad2f.png)

**Comment by cagataycivici** [comment]
You can use p-tree with p-overlayPanel to implement this.

**Comment by vaishnavravi33** [comment]
Hi is there any dropdown/select control which able to display the tree for selection, means tree inside the select. Like tree select of ant-design.
to see the example of TreeSelect click the URL below:-
https://ant.design/components/tree-select/
