### ISSUE TITLE
how this work

### ISSUE THREAD

**Issue by mostfa-ayad** [primefaces/primeng#61]
hi i think it's  good work

i  use primeFaces  but  i don't  know  how  can i use  primeNG  in  jsf  project
can you tell  me the  way to use  it 
thanks

**Comment by ecovaci** [comment]
I don't see how can be primeNG used in a JSF project. A RESTFUL architecture with let's say Spring framework on server-side and AngularJs with ng-prime on client-side is what you may be looking for.

**Comment by cagataycivici** [comment]
PrimeNG is not designed for JSF, PrimeFaces is exclusive for JSF and PrimeNG does the same for Angular2. For the other frameworks, there are generic PrimeUI with its PrimeElements companion.
