### ISSUE TITLE
Dropdown fails when items are loaded async

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#610]
When options are loaded from a remote url, the label is not updated.

**Comment by battmanz** [comment]
Does this mean that I can use the `async` pipe as the following example shows?

```typescript
export class DemoComponent implements OnInit {
  public items: Observable<{ label: string, value: string }>;
  constructor(private http: Http) { }

  ngOnInit() {
    this.items = this.http.get('some/url/that/returns/items').map(response => response.json());
  }
}
```

```html
<p-dropdown [options]="items | async"></p-dropdown>
```

I'm trying that, but it doesn't seem to work. I'm using primeng version 2.0.3.

**Comment by battmanz** [comment]
Nevermind, I must have been doing something wrong. The `async` pipe works great!

**Comment by cagataycivici** [comment]
Glad to hear.
