### ISSUE TITLE
Adding node to Treetable issue

### ISSUE THREAD

**Issue by mihajlo86** [primefaces/primeng#6101]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

After adding node to tree in Treetable module, it doesn't show up dynamically, although it is added to selected parent node. If the parent node is collapsed and expanded again it shows up. 

**Expected behavior**

It should be expected that added child node would show up dynamically like in Tree module

**Please tell us about your environment:**

* **Angular version:** 6.7

* **PrimeNG version:** 6.1

* **Browser:** [Chrome 67.0.3396.99 (Official Build) (64-bit) ]

 
* **Language:** [TypeScript 2.7.2]

**Comment by cagataycivici** [comment]
See the documentation please, important part is "Change Detection"
