### ISSUE TITLE
Improving Accessibility for Visually Impaired Users Via Aria Attributes

### ISSUE THREAD

**Issue by mattcfilbert** [primefaces/primeng#6103]
**I'm submitting a ...**
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Many input components can be made more accessible to the visually impaired by adding "aria-label" and "aria-required" attributes. The "required" attribute does a lot of what the "aria-required" attribute does, but the latter is still useful for user agents that do not yet support HTML5.

**Proposed improvement**
I am submitting a PR that adds "aria-label" and "aria-required" attributes to all applicable input components. 

**What is the motivation / use case for changing the behavior?**
This PR will improve PrimeNG's overall accessibility for visually impaired users who rely on screen readers.

**Comment by mattcfilbert** [comment]
My pleasure! Thank you for improving PrimeNG’s accessibility, I am a big
fan of your excellent library.

**Comment by maniiiit** [comment]
is aria-label enhancement added to the calendar component ??

**Comment by maniiiit** [comment]
is aria-label property included in calendar component ??

**Comment by cagataycivici** [comment]
The issue is too broad, please create per component tickets.
