### ISSUE TITLE
Custom loader component for TurboTable

### ISSUE THREAD

**Issue by Helayxa** [primefaces/primeng#6105]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Loader in TurboTable can be customized only using CSS classes.

**Expected behavior**
I would like to use a custom component as loader for the TurboTable. Can you implement the BlockableUI interface or add a new template type for the loader N

**Comment by smitpsanghavi** [comment]
Alternatively, we can have <p-progressSpinner> support for Table.

**Comment by cagataycivici** [comment]
You can use showLoader = false and implement your own loader.
