### ISSUE TITLE
addition to issue #1205 when we use appendTo="body"

### ISSUE THREAD

**Issue by viveksyadav** [primefaces/primeng#6115]
when we drag the dialog box while the dropbox is still open, the overlay of dropbox doesnt moves with dialog box, instead it goes to background of dialog box, and disapears as we realese the mouse.
same is the issue when we close the dialog box, while the dropdown overlay is still open, it goes to the top-left corner

**Comment by cagataycivici** [comment]
Please use the original issue instead of new tickets.
