### ISSUE TITLE
ConfirmDialog Safari problem

### ISSUE THREAD

**Issue by dawidrylko** [primefaces/primeng#6117]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://www.primefaces.org/primeng/#/confirmdialog

![safari-bug](https://user-images.githubusercontent.com/11761319/43017614-098b15a6-8c57-11e8-87fe-fd9be8f0f045.gif)

**Current behavior**

Confirm dialog not working at first time.

* **Angular version:** 6.0.9

* **PrimeNG version:** 6.0.1

* **Browser:** [ Safari 11.1.1 (13605.2.8]

 
* **Language:** [TypeScript]

**Comment by marmichalski** [comment]
This also happens in Safari version 12.0 (14606.1.30).

**Comment by dawidrylko** [comment]
Works in "primeng": "6.1.2",`

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
