### ISSUE TITLE
p-calendar Month Navigator error

### ISSUE THREAD

**Issue by eassymo** [primefaces/primeng#6118]
Month navigator is not working.

how to reproduce:

Go to showcase page:
https://www.primefaces.org/primeng/#/calendar

Select another month than January in "Navigator section", month navigator won't update.

PrimeNG 6.0.1

Occurs on Chrome and Opera and Firefox latest versions.

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/commit/17265b63c83699dd8653a706fb427f9bf3cb1013
