### ISSUE TITLE
[bug report]

### ISSUE THREAD

**Issue by ResioSoftware** [primefaces/primeng#6120]
[bug report]

hi, im using prime ng verona theme version 6.0.0

i want use component autocomplete advanced:
https://www.primefaces.org/primeng/#/autocomplete

it have option multiple, for select more one data, and the default is false. if i define false in code the system continue true, if i remove it be false, but the buttom of select, change position to bottom of input.
the buttom bug when i remove the tag multiple for can select only one data

**Comment by ResioSoftware** [comment]
![ac1](https://user-images.githubusercontent.com/26659895/43158626-830be8b8-8f56-11e8-8b42-6e8d45fad8b0.png)
 the buttom is normal here

![ac2](https://user-images.githubusercontent.com/26659895/43158750-dcc84e32-8f56-11e8-8f8f-4503d8dbff20.png)

here i remove the multiple option, for default be false. But the buttom go to bottom of input, and the right of input have space for it, im resize the input for all sizes, but it persist

**Comment by cagataycivici** [comment]
Please use Verona forum instead of Core Issue Tracker and our team will assist.
