### ISSUE TITLE
New Feature:  Pivot Grid

### ISSUE THREAD

**Issue by sachurao** [primefaces/primeng#6125]
Add a new excel-like pivot grid feature.

**Comment by bepi2002** [comment]
I support this request

**Comment by tbegsr** [comment]
Me too

**Comment by cagataycivici** [comment]
No plans at the moment.

**Comment by supermuka** [comment]
This is a great feature.

Are there plans to develop this pivot/cube table soon?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
