### ISSUE TITLE
Latest primeng is not supporting old tree tables.

### ISSUE THREAD

**Issue by MalliswariKP** [primefaces/primeng#6127]
I have recently upgraded primeng to latest version. Though it has introduced turbotables, it is still supporting p-datatable. But treetable is completely blank, i could not see even headers. Did they completely deprecated old treetable in primeng latest version?

Should i all my treetables with new template of primeng? Is this the only solution?

**Comment by cagataycivici** [comment]
TreeTable is rewritten and not backward compatible.
