### ISSUE TITLE
StopPropagation on drag

### ISSUE THREAD

**Issue by matthieu-D** [primefaces/primeng#613]
Hi,
I have been playing with your lib for the drag-drop.
I used a stop propagation on the event in onDragStart(), it didn't work.
Then I went to your code and used the stopPropagation in dragStart() and now it's working.
I haven't looked deep into your code, maybe you reset the event somewhere.
Any idea?

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
