### ISSUE TITLE
(feature) : reactive file upload

### ISSUE THREAD

**Issue by ghost** [primefaces/primeng#6130]
Hello;

It will be so nice if the upload file component is reactive :)
here is a series of tutos that explains how : https://www.youtube.com/watch?v=WtkxPe8sDU0&list=PLV1euzd9ziJJr_RD0v8BoXUz22f1HjGvG

Thank you in advance :)

**Comment by cagataycivici** [comment]
Currently no plans at the moment, if there is more demand, we'll reconsider.
