### ISSUE TITLE
Reimplement InputSwitch

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#6134]
Modernize it using a css only approach like we did in React;

https://www.primefaces.org/primereact/#/inputswitch

**Comment by solael** [comment]
@cagataycivici New InputSwitch implementation seems broken with Bootstrap theme, style was messed up, though the component works.

**Comment by osoDev** [comment]
Did you intentially remove onLabel and offLabel?
Is there some new approach to define custom texts?

**Comment by jkyoutsey** [comment]
Yeah, the removal of onLabel and offLabel is a breaking change that should have been communicated as part of a major release number, not 6.0.1 -> 6.0.2.  Spent a lot of time scrambling this morning to figure out what the heck happened!

**Comment by kt215** [comment]
The display text is now decoupled from the control. So you need to react to the InputSwitch state change and update your text accordingly.

**Comment by shorley** [comment]
The inputswitch style on bootstrap theme is still broken on update 6.1.3. It shows a plain blue background without the switch.

**Comment by lichao10424** [comment]
The inputswitch style on bootstrap theme is still broken on update 6.1.4.
So I have to trun to v6.0.0 to use this, wish it will work well soon.

**Comment by mgtskuntal** [comment]
I use current version v7 and inputswitch is still broken with bootstrap theme .
![untitled](https://user-images.githubusercontent.com/37828468/53659323-481fc480-3c81-11e9-9c81-9e358c7da227.png)

**Comment by obtdap** [comment]
The inputswitch style on bootstrap theme is still broken on update 7.1.0. It shows a plain blue background without the switch.
Any solutions planned ?

**Comment by solael** [comment]
> The inputswitch style on bootstrap theme is still broken on update 7.1.0. It shows a plain blue background without the switch.
> Any solutions planned ?

Bootstrap theme is not maintained any more. I find inputswitch styles in nova theme and apply it. Should fix the problem.
