### ISSUE TITLE
Don't work [(ng-model)] inside p-column (<p-dataTable> )

### ISSUE THREAD

**Issue by alex4033** [primefaces/primeng#614]
My question is if possible the following:

```
<p-dataTable  [value]="detailList">     
        <p-column header="idDetail">
            <template let-col let-detail="rowData" let-rowIndex="rowIndex">
                <input type="text" placeholder="Required" [(ng-model)]="detail.idDetail"/>
            </template>
        </p-column>
    </p-dataTable>
```

thanks for your help

**Comment by loic49** [comment]
+1, when I use this syntax "detail.idDetail" is set to null, I would like to see the value of "detail.idDetail" in my input contro, not null.

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
