### ISSUE TITLE
Disabled option support for SelectButton

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#6146]
SelectButton should utilize the disabled property of a SelectItem instance.

**Comment by despotgit** [comment]
OMG, this is exactly how I made this change. I had to go inside node_modules and change this. This should definitely go in. I added (anyway, to tell you exactly how I did it) the || option.disabled in one of the methods and the part for ui-disabled the similar part ||option.disabled in the template. Great! But the change is not yet implemented when npmpulls the package with the select button.
