### ISSUE TITLE
Calendar month navigator does not change and does not show current selected month

### ISSUE THREAD

**Issue by extic** [primefaces/primeng#6150]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Bug occurs in the PrimeNG Calendar page:
https://www.primefaces.org/primeng/#/calendar

**Current behavior**
When choosing to show navigators in the Calendar component, opening the calendar dropdown pane shows "January" in the month navigator no matter what month is actually chosen previously and cannot be changed (although days are modified).

**Expected behavior**
When the calendar dropdown opens, the month navigator should be populated with the month of the currently chosen date and changing the month will change the month input text.

**Minimal reproduction of the problem with instructions**
1. Open the calendar page in PrimeNG (https://www.primefaces.org/primeng/#/calendar)
2. Click the Navigators input
3. In the calendar dropdown pane, choose 1st of July 2018.
4. BUG - note that the month input does not change when choosing July, but the days pane does.
5. The input will contain "07/01/2018" and underneath the input the following text will appear: "Jul 1, 2018"
6. Press the Navigators input again
7. BUG - The month dropdown shows "January" instead of "July" (BTW, choosing a different month in the month dropdown will change the calendar days but not the month itself)

**What is the motivation / use case for changing the behavior?**
Users cannot view selected date correctly.

**Please tell us about your environment:**
Windows 7, Google Chrome Version 67.0.3396.99 (Official Build) (64-bit).
Maybe this issue is related to the system settings of date format. Specifically, on my Windows 7, the formats are:
Short date: "dd-MMM-yy"
Long date: "dddd, MMMM dd, yyyy"

* **Angular version:** 5.X
Bug occurs on PrimeNG site - current PrimgNG version 6.0.1 - probably latest Angular.

* **PrimeNG version:** 5.X
Bug occurs on PrimeNG site - current PrimgNG version 6.0.1

* **Browser:** 
The following have been tested, but could occur in others too:
Google Chrome Version 67.0.3396.99 (Official Build) (64-bit)
Firefox Quantum 60.0.2 (64-bit)
IE 11 (11.0.9600.19080)
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
N/A

* **Node (for AoT issues):** `node --version` =   
N/A

**Comment by narayn92** [comment]
I am also facing the same issue with angular 6. Do anyone have a fix for this ?

**Comment by extic** [comment]
No, I don't.
Currently, my users experience this perceived bug.

**Comment by extic** [comment]
I see from the github master sources that this issue has already been fixed:
https://github.com/primefaces/primeng/commit/17265b63c83699dd8653a706fb427f9bf3cb1013

Now awaiting PrimeNG release.

**Comment by cagataycivici** [comment]
Fixed and shipping now.
