### ISSUE TITLE
Ultima p-multiselect valid/invalid style bug

### ISSUE THREAD

**Issue by digaus** [primefaces/primeng#6151]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Waiting Time: ~8 weeks.

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://www.primefaces.org/ultima-ng/#/forms (add 'ng-invalid' class to multiselect )

**Current behavior**
![image](https://user-images.githubusercontent.com/15358538/43137009-cb1227a0-8f4a-11e8-8367-98266010fd2f.png)

Valid and invalid styles are not applied correctly (no animation for valid and invalid displays complete background in red)

**Expected behavior**

Like the dropdown component

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.X

* **PrimeNG version:** 5.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by digaus** [comment]
Also seems to be the case for the checkbox and radio options (might be intended but previously the behaviour was different)

![image](https://user-images.githubusercontent.com/15358538/43262678-484f1628-90e1-11e8-8ecc-f0e2ec595f02.png)

**Comment by Merve7** [comment]
Fixed for next release
