### ISSUE TITLE
Pagination Page Numbers Wrapping After 100 Pages

### ISSUE THREAD

**Issue by sut123** [primefaces/primeng#6153]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Paginator page numbers are wrapping outside of the display box (.ui-paginator-page) when going into the triple digits.

**Expected behavior**
Page numbers should be fully encompassed by the paginator page borders.

**Minimal reproduction of the problem with instructions**
Create any datatable with more than 100 pages of data. Once you get past the 100th page, you should see the page numbers starting to wrap outside of their parent containers.

Note that this **does not** happen for the page that's currently selected, although that simply hides the rest of the page number which isn't much better.

**Please tell us about your environment:**
* **Angular version:** 6.0.3
* **PrimeNG version:** 6.0.0
* **Browser:** all

**Comment by cagataycivici** [comment]
Provide a case please;

https://stackblitz.com/github/primefaces/primeng-issue-template

**Comment by ivan-meridianbanc-com** [comment]
```
<p-paginator [rows]="10" [totalRecords]="123456789123456789" [first]="123456789"></p-paginator>
```

**Comment by ivan-meridianbanc-com** [comment]
https://nbwiamqn.github.stackblitz.io/

**Comment by Steven-Harris** [comment]
Having the same issue when using lazy loading using ng 6 and primeng 6.1.5
![image](https://user-images.githubusercontent.com/7720242/47916714-1171a300-de75-11e8-9e1c-d48e3b2792a0.png)
