### ISSUE TITLE
Schedule control not showing events

### ISSUE THREAD

**Issue by pserafin** [primefaces/primeng#6154]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Control won't show/print events unless they are loaded with some delay (caused by e.g. service call to retrieve data) on ngOnInit() action or any action which will take place after control view initialization eg ngAfterViewInit()

**Expected behavior**
filling events with some initial data on ngOnInit() e.g.
 ngOnInit() { this.events = [ { title  : 'event1', start  : '2018-01-24', }; }
should result with printing them on layout

**Minimal reproduction of the problem with instructions**
Just replace:
    ngOnInit() { this.eventService.getEvents().then(events => {this.events = events;}); }
with some flat initialization
    ngOnInit() { this.events = [ { title  : 'event1', start  : '2018-01-24', }; }
it will cause not printing that that event on layout.
changing place of events initialization to e.g. ngAfterViewInit() - fixing this issue

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Tested on current version from github (6.0.1)

* **Angular version:** 5.X
6

* **PrimeNG version:** 5.X
6.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
checked on all newest versions of Edge/Firefox/Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
languages: pl/en , Typescript 2.7.2, ES6

**Comment by bellizio** [comment]
I have just encountered the same problem. 

Also seeing a similar issue where events will not be shown if the `<p-schedule>` component is wrapped with an *ngIf condition, regardless if the data is async or not.

**Comment by cagataycivici** [comment]
PR merged
