### ISSUE TITLE
Add onOptionClick event to p-listbox

### ISSUE THREAD

**Issue by jonbarthol** [primefaces/primeng#6161]
I'm submitting a ...
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
An onClick event in p-listbox would be very helpful. We created a complex dropdown control with several p-listboxes inside a p-overlayPanel. There's not an easy way to handle the case where an already-selected item in a p-listbox is selected a second time. Thanks.

**Comment by cagataycivici** [comment]
onClick of an item or anywhere in the listbox?

**Comment by jonbarthol** [comment]
onClick of an item. Thanks again.
