### ISSUE TITLE
looking for angular calendar which can satisfy below requirement

### ISSUE THREAD

**Issue by Naveenbillure** [primefaces/primeng#6162]
Looking for suggestions, need to implement below Grid in Angular 6. I looked up on few Angular Calendar/Schedulers available but they are not meeting requirement since they provide Grid in Either a day or a week or a month.
Where 1. W1, W2,.., etc are my week numbers in a year 2. Colored Horizontal Bars are my Objects which are active between those weeks. 3. The week numbers are not fixed, it should vary depending upon the User selection, the week numbers should changes if user selects the Month/Quarter/Year. Any suggestion how it can be implemented or if there are any Charts or Grids or Calendars or Scheduler available in opensource, most welcome.
Link for the screenshot is in this URL:[https://stackoverflow.com/questions/51530922/looking-for-angular-calendar-which-can-satisfy-below-requiement](url) 
![promotioncalendar](https://user-images.githubusercontent.com/33921884/43241732-86076ba4-90ba-11e8-9efb-0e614f09ea69.png)

**Comment by cagataycivici** [comment]
Please use forum for questions.
