### ISSUE TITLE
p-tree: onNodeDrop event is not invoked

### ISSUE THREAD

**Issue by ChenAlmost** [primefaces/primeng#6165]
**Current behavior**
  I have two p-tree components and  I drag node from p-tree A to p-tree B. But the onNodeDrop event on p-tree B is not invoked. It happens only when p-tree B has no data. onNodeDrop event will be invoked when p-tree B has data.

* **Angular version:** 5.1.1

* **PrimeNG version:** 5.2.7

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
