### ISSUE TITLE
Binding to event property 'onLabel' is disallowed for security reasons, please use (Label)=.

### ISSUE THREAD

**Issue by huineng** [primefaces/primeng#6166]
```
[x ] bug report
```
With the latest version of angular 6.1.0 (today 26/07) using prime 6.0.2 i'm now getting the following error in the inputSwitch element

```
Binding to event property 'onLabel' is disallowed for security reasons, please use (Label)=.
```

maybe change the onLabel and offLabel to labelON and labelOff

the prefix "on" seems to be confusing things here

**Comment by abadr82** [comment]
I have exactly the same issue with the inputSwitch.
With Angular 6 and prime 6.

**Comment by scurk1415** [comment]
Will this be fixed/implemented or did they drop support for labels?

**Comment by alecrt** [comment]
same problem here

**Comment by el7lme** [comment]
Same issue

**Comment by cagataycivici** [comment]
Which component is this? New InputSwitch does not have onLabel-offLabel

**Comment by huineng** [comment]
ok, true, it's no longer there the onLabel in 6.0.2  , must have been my component then not being adapted to these breaking changes.

I'll close it , maybe others if they still have a problem can reopen it

**Comment by chgc** [comment]
@cagataycivici  There is another component will cause the same error too. **ToggleButton**.
