### ISSUE TITLE
Events like chnage,focus,blur,input  working in prime Ng autocomplete

### ISSUE THREAD

**Issue by Akanksha-26** [primefaces/primeng#617]
I am trying to pass changes of autocomplete child component to parent component using event emitter,It is working fine when i use (onSelect) event of autocomplete I am able to pass changes in model to parent component but i also want to pass changes of ng model to parent on blur event also.Below is my child component code .I want to use (blur) event instead of (onSelect).

`@Component({
    selector: 'product-name-autoComplete',
    directives: [AutoComplete],
    template:`
    < p-autoComplete  (change)="setLabel(product)"  [(ngModel)]="product" [suggestions]="filteredData" (completeMethod)="filterData($event)" [size]="30"
        [minLength]="1" placeholder="Enter Product Name" [dropdown]="false"  field="name" >
        < template let-brand >
            < li class="ui-autocomplete-list-item ui-helper-clearfix">
                < div style="float:left">{{brand.name}}< /div >
            < /li >
        < /template >
    < /p-autoComplete >
    `,
    providers: [HTTP_PROVIDERS]
})
` 

`export class productAutocomplete {
    @Input() products: any[];
    @Output() onChange = new EventEmitter<any>();

```
filteredData : any[];
product: any;
code: number;

filterData (event) {
    this.filteredData = [];
    for (let i = 0; i < this.products.length; i++) {
        let brand = this.products[i].name;
        let code = this.products[i].id;
        if ( brand.toLowerCase().indexOf( event.query.toLowerCase() ) == 0) {
            this.filteredData.push ({
                name: brand,
                id: code,
            });
        }
    }
}
setLabel (product) {
    if (product.name) {
        this. onChange. emit(product);
    }
}
```

}
`

**Comment by cagataycivici** [comment]
Blur is fixed via;

https://github.com/primefaces/primeng/issues/2256
