### ISSUE TITLE
treetable : chrome overflow-anchor

### ISSUE THREAD

**Issue by huineng** [primefaces/primeng#6170]
Prime  6.0.2
Angular 6.1.0

max IOS 10.13.5
chrome 70  , firefox 61

Compare behaviour between the browsers

got https://www.primefaces.org/primeng/#/treetable/scroll

click on vertical scroll
click on "Applications"  data are loaded beneath
click on "cloud" data are loaded beneath 
scroll down and click on "desktop"  data are no longer loaded beneath but instead you are being scrolled to the bottom of the scroll

happens only in chrome,  other browsers are working as expected

This is a serious inconvenience as the user are loosing track what they expanded.

Doing some search, this is now a standard behaviour in chrome > 54 and it can be solved by setting overflow-anchor: none;

eg in css
.ui-treetable-scrollable-body : {overflow-anchor: none;}

but please check if this is something primeng needs to include in it's css or if we have to add this ourselves
thanks

**Comment by TyagiAnkit40** [comment]
I have the same issue but adding .ui-treetable-scrollable-body  {overflow-anchor: none;} does not work. If I inspect the element in chrome and add this property, it works fine but if I try to add this CSS class in my app.component.css, the primefaces theme takes precedence and my CSS setting is ignored. How did you make it work?

**Comment by huineng** [comment]
you can always add !important or combine it with another css element

**Comment by hupfaufnet** [comment]
@huineng Thanks a lot. I had the same issue today and your solution made my day :)

**Comment by yigitfindikli** [comment]
Fixed in https://github.com/primefaces/primeng/commit/f4863691ce98a568561ac5837a886d8957857770 .
