### ISSUE TITLE
p-table with p-multiSelect and custom cells

### ISSUE THREAD

**Issue by acarboni71** [primefaces/primeng#6171]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
<p-table> with "in" filter loops on the array checking for equality:

               for (var i = 0; i < filter.length; i++) {
                    if (filter[i] === value)
                        return true;
                }
This way, it is not possible to use custom classes as row elements

**Expected behavior**
It would be much better to use the same code as the "equals" filter. The fix, should be like this one:
               for (var i = 0; i < filter.length; i++) {
                    if (filter[i].toString().toLowerCase() == value.toString().toLowerCase())
                        return true;
                }

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
For each cell, I don't use a simple string/number/boolean but a generic class. This way, I can transcode the value (i.e. from a number to a better label) and set specific styles in each cell (done using the toString() method). 

**Please tell us about your environment:**

* **Angular version:** 5.X
Angular 6.0.9

* **PrimeNG version:** 5.X
PrimeNg 6.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Any
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   8.11.3

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
