### ISSUE TITLE
Primeng DataTable keep selected row in expanded state after store.dispatch action on Angular?

### ISSUE THREAD

**Issue by mramkumar-mani** [primefaces/primeng#6173]
I am using Primeng DataTable and would like to preserve the selected row in expanded state after the store dispatch action using angular?

Any idea to preserve the expanded row..?

I tried the below code but, it's not working...

`	preserveExpandedRows(datatableRef, id, tableData): void {
		try {
			const expandedIds = datatableRef.expandedRows.map(x => x[id]);
			datatableRef.expandedRows = tableData.filter(x => expandedIds.includes(x[id]));
		} catch (error) {
			if (error.name !== 'TypeError') {
				throw error;
			}
		}
	}`

Any clue ...

**Comment by cagataycivici** [comment]
Please use forum for questions, thank you.
