### ISSUE TITLE
Calendar not closing on first click when with onPush strategy

### ISSUE THREAD

**Issue by huineng** [primefaces/primeng#6174]
prime 6.0.2

when a component that use calendar component has an onPush strategy , the calendar is not closed on click. this is cause by a missing markForCheck

suggested solution is to add this to the timeout function 

https://github.com/primefaces/primeng/blob/master/src/app/components/calendar/calendar.ts#L719

```
if(this.isSingleSelection() && (!this.showTime || this.hideOnDateTimeSelect)) {
            setTimeout(() => {
                this.overlayVisible = false;

                if(this.mask) {
                    this.disableModality();
                }
                this.cd.markForCheck();
            }, 150);
        }
```

**Comment by huineng** [comment]
any update on this ?  commit looks good to me

**Comment by cagataycivici** [comment]
Dropdown works fine, Calendar change is merged.
