### ISSUE TITLE
Suggestion: "Loading" button

### ISSUE THREAD

**Issue by Spiral1401** [primefaces/primeng#6175]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
```
I've been using something in projects I've been working on for a few years now, called "Ladda". It's essentially just a button that displays a loading spinner integrated with the disabling of the button to indicate something is processing. I like the immediate feedback of it. Someone has extended it to be used with Angular 2+ (which I am currently using), but I thought it would be neat to have this as a primeNG native feature, with it's own style of loading spinners/bars and whatnot. I imagine it could just be an option/attribute on the p-button, essentially just an alternate style of "disabled".

https://lab.hakim.se/ladda/
https://www.npmjs.com/package/angular2-ladda

**Comment by rob4226** [comment]
FYI not sure when it was added but buttons have a loading attribute that displays a spinner and disables the button! Looks and works really nice.

#### Loading State
Button displays a `loadingIcon` when `loading` property is enabled.

```html
<button pButton type="button" label="Small" icon="pi pi-check" [loading]="isLoading" ></button>
<p-button label="Search" icon="pi pi-search" [loading]="isLoading"></p-button>
```

https://primefaces.org/primeng/showcase/#/button

**Comment by Spiral1401** [comment]
Indeed I have been using the loading attribute for a short while now and dropped my use of the ladda library for consistency. I forgot I made this ticket, but I think it can be closed now.

Thanks!

**Comment by ropoko** [comment]
From which version is the loading attribute available? I'm using 11.2 and it isn't working.

The code:
```
<p-button type="submit" label="Confirmar" icon="pi pi-check" [loading]="true"></p-button>
```

Also, I checked and the "ButtonModule" is imported correctly.

**Comment by Spiral1401** [comment]
Looks like 11.4: https://www.primefaces.org/primeng-11-4-0-released/

I am using 11.4.4, so that checks out.

**Comment by ropoko** [comment]
I have upgrade to 11.4.5 and it worked, thanks!
