### ISSUE TITLE
Unable to disable p-tableHeaderCheckbox in the table

### ISSUE THREAD

**Issue by vvvttt** [primefaces/primeng#6177]
Hello,

I want to disable the table header check box based on a variable. I tried to use the property "disabled", but its not recognized, I do see an @input defined in the github for it though. How can I disable it?

   <p-tableHeaderCheckbox [disabled] ="coldisabled" ></p-tableHeaderCheckbox>

Thanks

**Comment by dlarr** [comment]
Same problem :)

**Comment by dlarr** [comment]
@vvvttt : Did you progress on this 

@Anyone else : solution for this ?

**Comment by yigitfindikli** [comment]
I cannot replicate.
