### ISSUE TITLE
p-editor only uploads an image, the content is empty

### ISSUE THREAD

**Issue by SONASIDANTE** [primefaces/primeng#6178]
![image](https://user-images.githubusercontent.com/18680319/43352638-083c997e-9259-11e8-8f31-4f7778708e58.png)

       var text = _this.quill.getText().trim();
                if (text.length === 0) {
                    html = null;
                }

**Comment by dolphinsd** [comment]
Any resolutions to this issue?

**Comment by SONASIDANTE** [comment]
I use primeng 5.2.3. It doesn't have this issue.

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
