### ISSUE TITLE
Tree-table default scrollbar is invisible in Chrome

### ISSUE THREAD

**Issue by JJinLiu** [primefaces/primeng#6181]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Waiting Time: ~8 weeks.

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Tree-table default scrollbar is invisible in Chrome
```
**Current behavior**
Tree-table default scrollbar is invisible in Chrome, as the default scrollbar is covered by the webkit background color. (As long as this background color is removed, this can be figured out. But this is hard to achieve by resetting the background color in custom css, as "None" background color seems cannot override a specific color, and other background colors even transparent will also cover the scrollbar and make it invisible. )

![image](https://user-images.githubusercontent.com/28970032/43372127-80dd33fe-93f1-11e8-90d2-d62648d83bb0.png)

this is the css setting in theme file which may be the reason for this issue
body .ui-treetable .ui-treetable-scrollable-body::-webkit-scrollbar {
    background-color: #f0f3f5;
}

As I am not using the latest version of Primng(I am using 6.0.0), not sure if upgrading to the latest version can fix this issue or not.

**Expected behavior**
Show default scrollbar in Chrome 

**Minimal reproduction of the problem with instructions**
Make a tree-table scrollable with Chrome

**Please tell us about your environment:**
windows 10, npm

* **Angular version:** 6.0.5

* **PrimeNG version:** 6.0.0

* **Browser:** [ Chrome XX ]

* **Language:** [TypeScript X.X]

**Comment by mertsincan** [comment]
Thanks a lot for the screenshot. Please try latest PrimeNg version. If the problem persists, please re-open this issue with a stackblitz example. Sample template: https://stackblitz.com/github/primefaces/primeng-issue-template

Best Regards,
