### ISSUE TITLE
Strange positioning of OverlayPanel

### ISSUE THREAD

**Issue by pawelgniadek** [primefaces/primeng#6183]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/issue-primeng-template-pu5qap?embed=1&file=app/app.component.html

**Current behavior**

After clicking the button the overlay is aligned to the right, although there is enough space to place it on the left side of the page

**Expected behavior**

The overlay should be aligned to the left side of the button, which is the case when the sum of the widths of the button (the target element) and the overlay is less the the witdh of the document.

It seems that the problem is  with DomHandler.absolutePosition() function in which the left offset is calculated:
```
        if (targetOffset.left + targetOuterWidth + elementOuterWidth > viewport.width)
            left = targetOffset.left + windowScrollLeft + targetOuterWidth - elementOuterWidth;
        else
            left = targetOffset.left + windowScrollLeft; 
```
If the targetOuterWidth was removed from the if condition, the alignment is ok. 

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.X and 6.X

* **PrimeNG version:** 5.X and 6.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.

**Comment by jbermanwebguru** [comment]
I fixed this by creating a div element with a certain size, and using that as the target when opening the overlay. 

```html
<div
  #overlayTarget
  style="width: 200px; height: 30px; margin-top: -30px;"
></div>
```

```typescript
export class MyComponent {
  @ViewChild('overlayTarget')
  overlayTarget: ElementRef;

  @ViewChild('myDialog')
  myDialog: OverlayPanel;

  @HostListener('click', ['$event'])
  onClick(event: MouseEvent) {
    this.myDialog.show(event, this.overlayTarget.nativeElement);
  }
}
```
