### ISSUE TITLE
Schedule does not work after v6.0.1

### ISSUE THREAD

**Issue by kcsahoo** [primefaces/primeng#6185]
Schedule does not work from PrimeNg V6.0.1 onwards.
I upgraded fullcalendar to v4.0.0-alpha as was advised.
But does not work.
Gives 'fullcalendar' undefined error.
It works with PrimeNg V6.0.0 and fullcalendar v3.9.0 but only with Chrome and Firefox, not witrh IE 11.
Can anyone help?

**Comment by hidrogenos** [comment]
hello i update to 4.0.0-alpha and works fine, 

`"fullcalendar": "4.0.0-alpha",`

**Comment by kcsahoo** [comment]
Thanks.
I was missing the following entry in webpack.config.js
new webpack.ProvidePlugin({ FullCalendar: "FullCalendar" })

However it does not work in IE 11.
I get null reference error.
Have you tried with IE 11?

**Comment by JacobSiegle** [comment]
Schedule works with IE 11 for me.
