### ISSUE TITLE
p-autocomplete dropdown with multiselect

### ISSUE THREAD

**Issue by recaph** [primefaces/primeng#6186]
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
when using p-autocomplete with multiple true, dropdown closes immediately after one selection and needs to be opened to make another selection. 

**Expected behavior**
there should be an option to make multiple selections in the dropdown (something similar to how dropdown works for multiselect) before closing it.

**What is the motivation / use case for changing the behavior?**
This would eliminate the need to open dropdown multiple times to make all the selections. 

**Please tell us about your environment:**
Windows

* **Angular version:** 4.4.7

* **PrimeNG version:** 4.3.0

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
