### ISSUE TITLE
Angular Schematics support

### ISSUE THREAD

**Issue by sulco** [primefaces/primeng#6187]
**I'm submitting a ...** 
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Expected behavior**
Having a possibility to run `ng add primeng` that will do all the steps necessary to have PrimeNG in the project.

**What is the motivation / use case for changing the behavior?**
Instead of running two commands:
```
npm install primeng --save
npm install primeicons --save
```
plus filling the styles entry of `angular.json` file, a developer would only need to run one simple command.

**Comment by sulco** [comment]
If you are opened for contribution, I could add this schematic (Already did that on other projects).

**Comment by cagataycivici** [comment]
We've done it as well, will release it by mid august.

**Comment by doggy8088** [comment]
@cagataycivici Do you have any plan on Angular Schematics support?  Is this feature on roadmap?

**Comment by cagataycivici** [comment]
@sulco, we'd appreciate a PR.

**Comment by andriy101** [comment]
Her is my implementation of priming schematics:  https://www.npmjs.com/package/primeng-schematics

**Comment by doggy8088** [comment]
@cagataycivici Are you already have a offical schematics now?
