### ISSUE TITLE
PrimeNG incompatibilty in IE 11 

### ISSUE THREAD

**Issue by kcsahoo** [primefaces/primeng#6190]
PrimeNG team is doing a great job.
I have a suggestion for its wider acceptability.
Most corporates still use Windows 7 and IE 11.
They cannot install any other browser.
PrimeNG has some issues with IE 11.
Mostly null reference error.
I have issues with Dropdown and Schedule for example in V6.0.2.
I will request PrimeNG to be tested with IE 11 when a new version is released even with patches and minor versions.

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
