### ISSUE TITLE
dropdown does not close on selection when change detection is on push

### ISSUE THREAD

**Issue by abuscom-leonhard** [primefaces/primeng#6193]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Waiting Time: ~8 weeks.

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

If the dropdown component is used in a component with change detection onpush the dropdown does not collaps on selection. This bug has been introduced with version 6.0.2

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/angular-1kul2t

* **Angular version:** 6.1.0

* **PrimeNG version:** 6.0.2

* **Browser:** [Chrome 67 ]
 
* **Language:** [TypeScript]

* **Node (for AoT issues):** `node --version` =  8.9.0

**Comment by huineng** [comment]
https://github.com/primefaces/primeng/issues/6174

**Comment by cagataycivici** [comment]
Works for me using 6.1.2.
