### ISSUE TITLE
p-calendar needs to provide multi date formats

### ISSUE THREAD

**Issue by HISeG-ME** [primefaces/primeng#6194]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
p-calendar component can only take one dateformat at a time. 

**Expected behavior**
p-calendar component must be able to take several date formats since the user is expecting to work with several notations.

**Minimal reproduction of the problem with instructions**

PrimeNg Documentation page : https://www.primefaces.org/primeng/#/calendar

**What is the motivation / use case for changing the behavior?**

Due to the expectations of international users, it is necessary to have the p-calendar component with multiple date formates.

Please see this merge request by orsolli / https://github.com/orsolli
https://github.com/primefaces/primeng/pull/6043/commits/9d363cc5ca802983dadbae742a1b067f7fe133e5

**Please tell us about your environment:**

Windows 10, Eclipse Oxygen, Node js 7.5.0
* **Angular version:** 5.X

5.1.0

* **PrimeNG version:** 5.X

5.2.0

* **Browser:** [all]

 
* **Language:** [all ]

* **Node (for AoT issues):** `node --version` =

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
