### ISSUE TITLE
Double clicking on a calendar date causes the page to reload

### ISSUE THREAD

**Issue by sgentile** [primefaces/primeng#6195]
I was able to even duplicate this on the documentation page

1. click the icon, control comes up
2. double click a date 

Page reloads

**Comment by Mysame** [comment]
Confirmed.
Calendar has been having a LOT of regressions recently. I'm afraid of updating at this point. 
@cagataycivici

**Comment by LsKLele** [comment]
Same problem here, can you please check ASAP?
Thanks

**Comment by chrispinzaru** [comment]
The page reloads since they use '<a href="#" ' on rendered date-picker dates, thus double clicking them fast will make your Angular app (which uses Hash Navigation) to reset and jump to root page ("/#" page).

**Comment by chrispinzaru** [comment]
@cagataycivici Thank you very much for fast response/fix and release! If I can further help you somehow - please let me know. 
Everything is fine, yet the dates now don't have "cursor: pointer" style (Anchor <a> with "href" determined that style) - So we manualy have to add "cursor: pointer" to rules ".ui-datepicker td > span, .ui-datepicker td > a"
