### ISSUE TITLE
Calendar initial value not formatted

### ISSUE THREAD

**Issue by BAndonovski** [primefaces/primeng#620]
When selecting a value from the calendar pop up, the input field is properly formatted. 
However, on initial load (for example, editing a document), the input field is not properly formatted.

`<p-calendar id="tiralDate" [(ngModel)]="r.date" [readonlyInput]="true" required [ngModelOptions]="{standalone: true}" [disabled]="mutable?null:true" [locale]="mkd"></p-calendar>`

with mkd being properly defined: 

`    this.mkd = {
            //date
          closeText: "Крај",
            prevText: "<Пред",
            nextText: "След>",
            currentText: "Денес",
            monthNames: [ "јануари","февруари","март","април","мај","јуни",
            "јули","август","септември","октомври","ноември","декември" ],
            monthNamesShort: [ "јан","фев","март","апр","мај","јун",
            "јул","авг","сеп","окт","ное","дек" ],
            dayNames: [ "понеделник","вторник","среда","четврток","петок","сабота","недела" ],
            dayNamesShort: [ "пон","вто","сре","чет","пет","саб","нед" ],
            dayNamesMin: [ "П","В","С","Ч","П","С","Н" ],
            weekHeader: "Сед",
            dateFormat: "dd.mm.yy",
            firstDay: 1,
            isRTL: false,
            showMonthAfterYear: false,
            yearSuffix: "" 

```
    }`
```

Tried with date format directly, didn't help. 
The date's properly formatted only when selected through the pop up.

**Comment by JiroDan** [comment]
The calendar function, writeValue does not honor the showTime attribute.  It should be changed to use the updateInputField, like so:
    writeValue(value: any) : void {
        this.value = value;
        
        if(this.inputfield && value != null) {
            this.updateInputfield();
        }
    }

**Comment by cagataycivici** [comment]
Should be fixed with recent PrimeNG releases, can't remember the exact version. Please drop a comment if issue persists and we'll reopen.
