### ISSUE TITLE
p-spinner not allowing 0 after decimal

### ISSUE THREAD

**Issue by alokparikh16** [primefaces/primeng#6204]
**Current behavior**
Spinner component is  not allowing to enter 0 after decimal point.

**Expected behavior**
Spinner component should be able to add 0 after decimal number

**Minimal reproduction of the problem with instructions**
This can also be replicated on: https://www.primefaces.org/primeng/#/spinner

**note:
This happens because of parseFloat in parseValue() function which will remove leading 0 like parseFloat(12.20) will be 12.2
However, if I want to write 12.201 it becomes impossible

**Comment by cyberrranger** [comment]
show #5490

**Comment by cagataycivici** [comment]
Tracked at

https://github.com/primefaces/primeng/issues/5490
