### ISSUE TITLE
Ultima dropdown padding leads to missalignment (multiselect is off aswell)

### ISSUE THREAD

**Issue by digaus** [primefaces/primeng#6207]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

**Current behavior**
https://www.primefaces.org/ultima-ng/#/ (replace ui-g-12 with ui-g-6 of dropdown and next inputfield)

![image](https://user-images.githubusercontent.com/15358538/43545588-93db23d0-95d6-11e8-93d9-9c32bc624144.png)

Since the fancy new focus animation the dropdown got a padding-bottom of 2px (for whatever reason) this leads to it being missaligned if you have another normal input next to each other.
Same with multiselect

**Expected behavior**

Do not add that padding. Best solution would be to use a readonly pinputtext instead of the label. This way the behaviour would be consistent and the alignment would be corrent

**Minimal reproduction of the problem with instructions**

See above

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.X

* **PrimeNG version:** 5.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Use Ultima forum please, not the PrimeNG Core issue tracker.
