### ISSUE TITLE
TreeTable - different height body with frozen column

### ISSUE THREAD

**Issue by szymonworld** [primefaces/primeng#6208]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://www.primefaces.org/primeng/#/treetable/scroll

**Current behavior**
Frozen body has different height than scrollable body
![bug](https://user-images.githubusercontent.com/9286136/43551681-27b4d8ec-95e8-11e8-80b1-5a3247ec8f80.PNG)

**Expected behavior**
Frozen body has identical height like scrollable body

**Minimal reproduction of the problem with instructions**
Go to the last example 'Frozen Columns' and you will see the bug.

**What is the motivation / use case for changing the behavior?**
Not an expected behavior

**Please tell us about your environment:**
Windows 10

* **Angular version:** 6.0.7

* **PrimeNG version:** 6.0.1

* **Browser:** 
all 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
This is expected and documented solutions.
