### ISSUE TITLE
Editor: Expression has changed after it was checked.

### ISSUE THREAD

**Issue by MarcelCremer** [primefaces/primeng#621]
Hey everyone,

when the editor is instantiated with some @Input-Variable, it will throw the error message above when prod-mode is disabled. This is very disturbing while developing.

The problem is, angular looks in dev mode if the injected value is still the same (using a second round of change detection). However, quill.js changes the html of the inserted text (e.g. exchanges new lines with <p> and so on).

I see 2 possible solutions:
1. Somehow enforce quill.js to leave the html as it is (until it's changed)
2. Trigger a new round of change detection

However, I couldn't solve this problem on my own, so maybe someone else can have a look at it.

BR
Marcel

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
