### ISSUE TITLE
InputGroup buttons look compressed with Firefox

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#6214]
An icon only button inside an inputgroup look compressed with Firefox

**Comment by jsilveira2** [comment]
The same problem to me. 

My config:
- PrimeNg: ^6.1.2
- Firefox: 61.0.2 (64-bit)

Used template: paradise-ng-6.0.0

**Comment by foo42bar** [comment]
Hello.

The commit https://github.com/primefaces/primeng/commit/541ee5c leads to problems when the nova-theme is NOT used, the same layout problem in firefox (as described above) is the consequence of the now missing "width: 2em;".
Was the change in src/app/components/button/button.css needed?

Regards,
Martin

**Comment by Elanor-L** [comment]
@cagataycivici can you please check this when you've got time ? Thank you
