### ISSUE TITLE
Keep currentYear and currentMonth in sync with the control value

### ISSUE THREAD

**Issue by csabasimon** [primefaces/primeng#6217]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

When setting the calendar's value through the formControl (either calling setValue or typing in the input field), the calendar's currentMonth and currentYear don't get updated. This leads to an unexpected behavior when using previous/next month buttons. Since those buttons rely on the currentMonth/year, the calendar will jump to the previous/next month prior to today's date.

eg.:

1.  Set the formControl's value to 2010.01.01
2.  Open the calendar, it correctly shows the dates for 2010 january.
3.  Press 'next month' button
4.  Calendar will jump to 2018 september

As a workaround we're setting the calendar's currentYear and currentMonth on the onFocus event, but I think they should be kept automatically in sync with the control's value.

**Expected behavior**

Setting the date through the formControl should behave the same way as selecting a date from the calendar, so the currentMonth and year should be set.

eg.:

1. Set the formControl's value to 2010.01.01
2. Open the calendar, it correctly shows the dates for 2010 january.
3. Press 'next month' button
4. Calendar should jump to 2010 february

* **Angular version:** 6.0

* **PrimeNG version:** 6.0

* **Browser:** [all]
 
* **Language:** [all]

**Comment by csizii** [comment]
Be kell konfigolni!

**Comment by csizii** [comment]
Ilyen a történelemben nincs hogy ezt nem tudod megcsinálni.

**Comment by ctobe-eagleinvsys** [comment]
Any updates on this?  It would be great to have this fixed.  The calendar jumps when you try to use it after setting through the form.

**Comment by ctobe-eagleinvsys** [comment]
@csabasimon can you share your work-around code to set those values on focus?  From event.target how do i set those values?  Thanks!

**Comment by mparker-ft** [comment]
+1 any update on this? we need this resolved ASAP

**Comment by csabasimon** [comment]
@ctobe-eagleinvsys

**.ts file**

```
@ViewChild('calendar') calendar: Calendar;

setCurrentDate(calendar: Calendar): void {
    if (!isNull(calendar.value)) {
      calendar.currentYear = calendar.value.getFullYear();
      calendar.currentMonth = calendar.value.getMonth();
    }
}
```

**.html**

```
<p-calendar #calendar 
    ...
    (onFocus)="setCurrentDate(calendar)">
</p-calendar>

```

**Comment by ctobe-eagleinvsys** [comment]
@csabasimon you rock!  This was really helpful.  I got that problem fixed. Unfortunately, we have other problems with this new calendar as well.  Our old method of opening it up via underlined text causes the back and forward buttons to not work.  I'm assuming its a race condition on the initialization of those buttons :-(

**Comment by adienger** [comment]
We're also having this problem with the calendar widget.

**Comment by cagataycivici** [comment]
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Comment by cagataycivici** [comment]
#6393
