### ISSUE TITLE
p-inputswitch onLabel and offLabel are gone

### ISSUE THREAD

**Issue by jkyoutsey** [primefaces/primeng#6219]
```
[x ] bug report 
```

* **Angular version:** 6.X

* **PrimeNG version:** 6.0.1 -> 6.0.2
The onLabel and offLabel are now missing.  Verified in the current code on github.

If you're going to deprecate a feature you need to communicate that and not do it in a minor revision change number!

**Comment by Elanor-L** [comment]
There's another issue with an answer. #6392

**Comment by anoopchandranms** [comment]
whats the alternative for this any idea

**Comment by T3kstiil3** [comment]
+1

**Comment by cagataycivici** [comment]
See 6392 please.
