### ISSUE TITLE
ngModel is not updating on pasting (AutoComplete)

### ISSUE THREAD

**Issue by amarjeetkapoor1** [primefaces/primeng#6220]
[x ] bug report => Pasting using context menu doesn't update ngModel while using autoComplete.
https://stackblitz.com/github/gqaiqymw
How to reproduce:
1. Copy any content.
2. right click on input field and click on paste option.

**Current behavior**
 Pasting using context menu doesn't update ngModel. If any keyDown event is not emitter before this event.

**Expected behavior**
Pasting using context menu should update ngModel. If regardless whether any keyDown event is  emitted before or not this event.

Cause:
https://github.com/primefaces/primeng/blob/master/src/app/components/autocomplete/autocomplete.ts#L302
this expression evaluate to true.

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
