### ISSUE TITLE
Add Ability to Expand All Table Rows on Header Click

### ISSUE THREAD

**Issue by noamichael** [primefaces/primeng#6221]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

Currently, the turbo table only offers a way to expand one row at a time by using the `[pRowToggler]` directive. If the application wants to expand all rows, the developer has to add their own logic and use the `expandedRowKeys` property to set all row keys to `1` or `0`.

**Expected behavior**

We should add a `[pAllRowToggler]` directive which would allow the user to toggle all the rows at once with one header cell click:

```html
<p-table [columns]="cols" [value]="cars" dataKey="vin">
    <ng-template pTemplate="header" let-columns let-allExpanded="allExpanded"><!--allExpanded is now available on the header template-->
        <tr>
            <th style="width: 3em">
		<a href="#" [pAllRowToggler]><!--Click to toggle all rows open or closed-->
                    <i [ngClass]="allExpanded ? 'pi pi-chevron-down' : 'pi pi-chevron-right'"></i>
                </a>
	    </th>
            <th *ngFor="let col of columns">
                {{col.header}}
            </th>
        </tr>
    </ng-template>
    <ng-template pTemplate="body" let-rowData let-expanded="expanded" let-columns="columns">
        <tr>
            <td>
                <a href="#" [pRowToggler]="rowData">
                    <i [ngClass]="expanded ? 'pi pi-chevron-down' : 'pi pi-chevron-right'"></i>
                </a>
            </td>
            <td *ngFor="let col of columns">
                {{rowData[col.field]}}
            </td>
        </tr>
    </ng-template>
    <ng-template pTemplate="rowexpansion" let-rowData let-columns="columns">
        <tr>
            <td [attr.colspan]="columns.length + 1">
                <!--Expand Content Here-->
            </td>
        </tr>
    </ng-template>
</p-table>
```

Implementation of this feature is pretty simple. I would add a variable to the table component to hold the current global toggle state, and an event `onAllRowToggle: EventEmitter<{toggleAllState: boolean}>` to allow the application to listen for when the rows were toggled. 

**I could easily do a PR if anyone else has interest in the feature.**

**What is the motivation / use case for changing the behavior?**

My application has dozens of tables which the users like to compare the contents of the expanded rows against one another. To support this, I've been adding my own logic to expand all the rows on a header cell click, which is a lot of work for each component. I think this is an easy feature to implement and it very useful.

**Comment by noamichael** [comment]
[I created a branch which implements this feature](https://github.com/noamichael/primeng/tree/feat-table-expand-all). Please let me know if anyone has any feedback!

**Comment by cagataycivici** [comment]
You can implement this on your side since **expandedRowKeys** is a reactive input.

**Comment by noamichael** [comment]
> You can implement this on your side since **expandedRowKeys** is a reactive input.

@cagataycivici Like I said when I opened this bug, "If the application wants to expand all rows, the developer has to add their own logic and use the expandedRowKeys property to set all row keys to 1 or 0." However, this must be done for every table in a given app, which could be dozens. I was just trying to simplify the process.

**Comment by dajin-kingland** [comment]
@noamichael I'm doing a migration from JQuery datatables to PrimeNG table.
It has over 50 tables in my app. And dozens repeat work been done. I met your solution...
It's perfect. Saved my time and make my life better Lol.
