### ISSUE TITLE
[6.1.0-rc.1][CSS & Style][Theme Omega] Severity Buttons not working

### ISSUE THREAD

**Issue by visat09** [primefaces/primeng#6222]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
**theme Omega**
all css class not working 
.ui-button-secondary
.ui-button-success
.ui-button-info
.ui-button-warning
.ui-button-danger

* **Angular version:** 5.X

5.0.0

* **PrimeNG version:** 5.X

6.1.0-rc.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Version 67.0.3396.99 (Official Build) (64-bit)
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

* **Node (for AoT issues):** `node --version` =   
v8.9.1

## I found something
I checked css class in file "../node_modules/primeng/resources/primeng.min.css".
I not found button style class in primeng version 6.1.0-rc.1
but in version 5.2.6 it does not disappear.

**Comment by cagataycivici** [comment]
Omega free theme is deprecated, you need to migrate to newer themes like Nova. Severities are responsibility of the themes as of 6.1 which Omega does not support.

Note that for Omega Template users, Omega will be reimplemented with Designer.

**Comment by guialro** [comment]
So, once I cannot install these newer themes because I didn't found any documentation to this at [Document Setup](https://www.primefaces.org/primeng/#/setup), how can I revert my version through NPM?

**Comment by guialro** [comment]
`C:\Dev\Projetos\****\Desenvolvimento\WEB\vgos-web>npm uninstall primeng --save
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

up to date in 10.541s

C:\Dev\Projetos\****\Desenvolvimento\WEB\vgos-web>npm cache verify
Cache verified and compressed (~\AppData\Roaming\npm-cache\_cacache):
Content verified: 2218 (104157560 bytes)
Index entries: 3494
Finished in 3.266s

C:\Dev\Projetos\****\Desenvolvimento\WEB\vgos-web>npm install primeng@6.0.2 --save
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ primeng@6.0.2
updated 1 package in 12.499s`

**Comment by visat09** [comment]
@guialro  migrate to primeng 6.0+
