### ISSUE TITLE
New node on TreeTable is not show inmediately

### ISSUE THREAD

**Issue by alfredods** [primefaces/primeng#6225]
Hello,

in the new TreeTable, when I add programmatically Nodea, it does not appear inmediately. It is necessary to close and open the node again. When the nodes will be inserted on the root everything works correct.

The code I use is:

```
const nodes: TreeNode[] = [...this.selectedNode[tabIdx].children];
savedBalanceSheetItems.forEach(savedBalanceSheetItem => {
    nodes.push({ 'data': savedBalanceSheetItem, 'children': []});
});
this.selectedNode[tabIdx].children = nodes;
```

Regards

Alfredo

**Comment by cagataycivici** [comment]
Please read the change detection section at TreeTable docs, thank you.
