### ISSUE TITLE
Rename keyframes "fa-spin" to "pi-spin"

### ISSUE THREAD

**Issue by opetriienko** [primefaces/primeng#6231]
There is still old keyframes **fa-spin** even after Prime Icons introducing. I believe it should be **pi-spin**.

**Please tell us about your environment:**
* **Angular version:** 6.1.0
* **PrimeNG version:** 6.0.1

**Comment by JacobSiegle** [comment]
It seems like it been fixed besides in the old datatable component which is deprecated and should probably keep fa-spin. Can you confirm?

**Comment by cagataycivici** [comment]
Yes, DataTable is not maintained anymore and we use pi-spin for anywhere else.
