### ISSUE TITLE
DataView - Paginator : Add paginatorTemplateLeft and paginatorTemplateRight on DataView component

### ISSUE THREAD

**Issue by nblaudez** [primefaces/primeng#6232]
It's is possible to add [paginatorTemplateLeft]  [paginatorTemplateRight]  attributes on DataView component and apply them on Paginator component of DataView ?

**Comment by JacobSiegle** [comment]
Seems easy to add - adding comment to tag, maybe I will have time to put a quick PR in.

**Comment by cagataycivici** [comment]
Merged 6280
