### ISSUE TITLE
p-table: filtering doesn't work with ChangeDetection: OnPush

### ISSUE THREAD

**Issue by ghost** [primefaces/primeng#6236]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/angular-tgcclb?file=src/app/app.component.html

1. set Vin filter to `a1`
![image](https://user-images.githubusercontent.com/25089646/43674015-621a0b1c-97d5-11e8-9338-a67c381b1d35.png)
2. Remove entered value
![image](https://user-images.githubusercontent.com/25089646/43674012-53149d94-97d5-11e8-9095-ee04375bd323.png)

Workaround: https://stackblitz.com/edit/angular-cvqxne?file=src/app/app.component.html

* **Angular version:** 6.1.1
* **PrimeNG version:** 6.0.2
* **Browser:** all

**Comment by maxkorz** [comment]
@fxmfr the workaround provided in the first post still works

**Comment by jamieathans** [comment]
Looks like just the presence of an empty onFilter function will make on OnPush change detection work ...

https://stackblitz.com/edit/angular-jgeky3

**Comment by rafa-as** [comment]
This solution is not correct because the problem is the array.push solved in my PR https://github.com/primefaces/primeng/pull/7641/files

**Comment by lucioleandro** [comment]
Rafa, i tested your solution, it works, but with some bugs

**Comment by rafa-as** [comment]
@lucioleandro can you be more specific? thanks

**Comment by annnoo** [comment]
Any update on this? It still does not work for me ...

**Comment by lucioleandro** [comment]
> @lucioleandro can you be more specific? thanks

Your solution worked, but sometimes failed, not filtering the table or not filtering correctly.
As I had no time, I didn't investigate the cause and looked for another solution.

**Comment by rafa-as** [comment]
> > @lucioleandro can you be more specific? thanks
> 
> Your solution worked, but sometimes failed, not filtering the table or not filtering correctly.
> As I had no time, I didn't investigate the cause and looked for another solution.

I don't know exactly but seems another different bug. My approach only solves the onPush.
