### ISSUE TITLE
Ecuador forms are broken

### ISSUE THREAD

**Issue by intergleam** [primefaces/primeng#6237]
https://www.primefaces.org/ecuador-ng/#/forms
Invalid input doesn't show anything 
![image](https://user-images.githubusercontent.com/2155554/43674879-ef9fb786-97e2-11e8-82b8-04193a823ed9.png)
unlike Ultima for example

**Comment by intergleam** [comment]
`Enhanced focus` input also doesn't do anything

**Comment by Merve7** [comment]
Firstly, we fixed invalid form issue for next release (Ecuador 6.1.0)

Secondly, enhanced focus is the wrong usage because enhanced focus is not supported in Ecuador theme. Sorry for this wrong usage. We removed enhanced focus input.
