### ISSUE TITLE
Ecuador: RouterLink fragment is not supported in the menu

### ISSUE THREAD

**Issue by intergleam** [primefaces/primeng#6238]
[x ] feature request 

steps to reproduce: 
* download Ecuador.
* open app.menu.component.ts
* change the line `label: 'Dashboard', icon: 'fa fa-fw fa-home', routerLink: ['/']` to `label: 'Dashboard', icon: 'fa fa-fw fa-home', routerLink: ['/'] fragment:'test'`

expected behaviour - the generated link should be /#test

**Comment by Merve7** [comment]
We added fragment support for Ecuador 6.1.0
