### ISSUE TITLE
Customized date format for multiple date selection in p-calendar

### ISSUE THREAD

**Issue by bishu40010961** [primefaces/primeng#6241]
**I'm submitting a ...**  

[ ] bug report 
[ x ] feature request 
[ ] support request 

**Current behavior**
When selectionMode is set to "multiple" , the date format is applied for each selected date. Example if we select 4 dates, date format is applied 4 times.

**Expected behavior**
Should be able to show the format only once for multiple date selection

**What is the motivation / use case for changing the behavior?**
We have a requirement in our project where we should be able to customize the date format for multiple date selection. Example : if we select 4 dates in a month, should be able to set the format as "4 days in a month , Monday".

* **Angular version:** 4.4.4

* **PrimeNG version:** 5.2.7

**Comment by cagataycivici** [comment]
If there is more demand, we'll reconsider.
