### ISSUE TITLE
Overlay dialog not  maximize without footer template

### ISSUE THREAD

**Issue by hidrogenos** [primefaces/primeng#6246]
[X ] bug report 

**Current behavior**

when i try to maximizable a dialog without footer template "<p-footer>", it doesn't work generate this error:
![image](https://user-images.githubusercontent.com/4935507/43729884-4903d31a-996f-11e8-8a7d-d317151e907e.png)

And rdirect to "localhost:4200/#" 

**Expected behavior**
the overlay dialog must be maximizable with or without footer template.

* **Angular version:**  6.0.4

* **PrimeNG version:**  6.1.0

* **Browser:**  all

**Comment by anmoljainatcs** [comment]
Its still issue with PrimeNG 6.1.0. Please let me know when this fix be available.
