### ISSUE TITLE
Get-started guide uses wrong css file

### ISSUE THREAD

**Issue by Ketec** [primefaces/primeng#6247]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
I suggester primeng to someone, he followed the guide and end up with the deprecated omega theme.
I assume it should point to one of the nova themes by default.

**Comment by JacobSiegle** [comment]
For quick ref - https://www.primefaces.org/primeng/#/setup

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/commit/f723507f03bc64659ab1fa2a7c057df59a4e15f9
