### ISSUE TITLE
primeng doesn't have any unit tests

### ISSUE THREAD

**Issue by jefhu** [primefaces/primeng#6249]
**Current behavior**

I don't see any unit test code in primeng git. For example (primeng 6.1.0 rc-1)
/primeng/src/app/components/dropdown/dropdown.spec.ts does not have any unit test code.

**Expected behavior**

Professional software should include unit tests. IMO

Unit tests should pass both using GUI browser tests and Headless browser test.
  
**Minimal reproduction of the problem with instructions**

https://forum.primefaces.org/viewtopic.php?f=35&t=56538&p=169250#p169250

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.X

* **PrimeNG version:** 5.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Please use forum for discussions, the codebase has unit tests, see the spec files please.
