### ISSUE TITLE
PrimeNG Designer API | Nova-Light | Forces button margin 0

### ISSUE THREAD

**Issue by JacobSiegle** [primefaces/primeng#6250]
Any reason why a margin of 0 must be enforced on on the .ui-button class? The previous free templates did not have this restriction so any margin directly applied to buttons no longer works.

body .ui-button {
    margin: 0;

New theme looks very nice btw =)

**Comment by buchatsky** [comment]
I see that SplitButton consists of two elements, each of which has 'ui-button' style, so I can't consistently set margins between buttons on Toolbar if it contains SplitButton...

**Comment by JacobSiegle** [comment]
@buchatsky I just started doing overrides in my CSS which is why I closed this issue. I believe if you had a paid primeng style you would just omit the setting. If you would like I can reopen this issue but I don't think it's possible to contribute to CSS changes since the SASS file isn't available for the free theme (last I checked).

**Comment by buchatsky** [comment]
@JacobSiegle I've found a workaround to this issue. In my app.component.css:
