### ISSUE TITLE
Tree table filters feature request

### ISSUE THREAD

**Issue by TyagiAnkit40** [primefaces/primeng#6252]
It would be nice to have a filter in tree tables so that when user clicks the filter icon on any column, user can choose from the possible value(s) based on tree data for that column / enter text and the nodes are filtered based on the input values. It will be helpful to filter initial parents.

**Comment by lucasfrotam** [comment]
I'm waiting for this feature a long time. I already tried implement one function to filter the content in the tree table but the time to start interaction for filter one string until show result it's slow, has a delay to show the result

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/issues/1683

**Comment by lucasfrotam** [comment]
> #1683
but this link is another component. I'm using PrimeNG

**Comment by lucasfrotam** [comment]
> #1683
but this link is another component. I'm using PrimeNG
