### ISSUE TITLE
Calendar and touchUI display when viewport is not big enough

### ISSUE THREAD

**Issue by sebaiona** [primefaces/primeng#6254]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**

When we put `touchUI="true"` on the p-calendar component it doesn't fit the available height...
If the viewport is not big enough, a part of the calendar is not accessible.

**Expected behavior**

**Minimal reproduction of the problem with instructions**

Go on [https://www.primefaces.org/primeng/#/calendar](url) open the Touch UI calendar and then reduce the height of the viewport

**What is the motivation / use case for changing the behavior?**

Display correctly the calendar on all devices.

**Please tell us about your environment:**

* **Angular version:** 6.1

* **PrimeNG version:** 6.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
