### ISSUE TITLE
Turbo table - Finding last record in current page

### ISSUE THREAD

**Issue by vinothbabu** [primefaces/primeng#6255]
Is there a way to find the last row or record of the table in current page?  
https://www.primefaces.org/primeng/#/table

The documentation has a property first, but i don't see a property last or anything related to it.

**Comment by cyberrranger** [comment]
without paginator
`<p-table [columns]="cols" [value]="cars">`

`let last = cars[cars.length]`

with paginator
`<p-table [columns]="cols" [value]="cars" [paginator]="true" [rows]="10" [first]="first">`

```
let pos = first + rows

if (pos > cars.length) {
pos = cars.length
} 
let last = cars[pos];
```

**Comment by cagataycivici** [comment]
Please use forum for technical questions.
