### ISSUE TITLE
Month and Year dropdown sync issue in calendar

### ISSUE THREAD

**Issue by kcsahoo** [primefaces/primeng#6258]
The month and year dropdowns do not synchronize with the input textbox date.
This is from V 6.0.0 onwards.

**Comment by oliverfrost** [comment]
I added additional info to: [6261](https://github.com/primefaces/primeng/issues/6261)
Is it the issue you encountered? If yes I think we can consider this ticket a duplicate and close it.

**Comment by kcsahoo** [comment]
Yes Issue #6261 covers this bug.
So it can be closed as duplicate.
