### ISSUE TITLE
The examples of button @ https://primefaces.org/primeng/#/button have dependency on themes

### ISSUE THREAD

**Issue by tareshss** [primefaces/primeng#6260]
the css for ui-button-raised and ui-button-rounded are in themes. Some themes provided don't have these at all such as "Home."

It should be mentioned on the examples page.

**Comment by bomberblue07** [comment]
As of 6.1.0, the only free themes that will be supported going forward are the Nova family of themes; so try to use one of them in your app.

**Comment by cagataycivici** [comment]
This is by design, mentioned on release announcement. Home theme is deprecated.
