### ISSUE TITLE
TreeTable children nodes get selected automatically for different parents

### ISSUE THREAD

**Issue by fabki00** [primefaces/primeng#6262]
**I'm submitting a ...**  (check one with "x")
```
[*] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/angular-treetable-ctjuwq

**Current behavior**
If data that is to be displayed in the Treetable consists of parents that have same children, then selecting child for one parent will also select corresponding child for another parent. 

**Expected behavior**
Children for different parents should be selectable independently even if the children data are the same for different parents. 

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 6.X

* **PrimeNG version:** 6.X

* **Browser:** [ Chrome XX ]

 
* **Language:** [ TypeScript X.X ]

* **Node (for AoT issues):** `node --version` =   8.11.2

**Comment by GustavoLima93** [comment]
I'm really having trouble !!

**Comment by umdstu** [comment]
You need to specify a dataKey that lets treetable know how to uniquely identify one of your rows. As it stands you dont have enough information in your tree to uniquely identify a row. I would recommend adding a 'path' field to your data and using that as your dataKey. See https://www.primefaces.org/primeng/#/treetable

**Comment by RaviSambaraju** [comment]
> You need to specify a dataKey that lets treetable know how to uniquely identify one of your rows. As it stands you dont have enough information in your tree to uniquely identify a row. I would recommend adding a 'path' field to your data and using that as your dataKey. See https://www.primefaces.org/primeng/#/treetable

yes after ading another key with unique value its working fine.
