### ISSUE TITLE
Is primeng supports out of box feature for adding tooltips for previous and next page buttons?

### ISSUE THREAD

**Issue by deepakmhr** [primefaces/primeng#6266]
I didn't find any documentation for setting tooltip for previous and next page buttons on datatable.
https://www.primefaces.org/primeng/#/table/page

Is there any way to set custom tooltip for those buttons?

![image](https://user-images.githubusercontent.com/6562535/43823382-7ca580d0-9b0c-11e8-949a-cb9c059e27d6.png)

**Comment by JacobSiegle** [comment]
It seems like you could hack it by using paginatorright and paginatorleft while hiding the existing paginator buttons but it wouldn't really be the same.

New feature request from what I can see in the docs.

**Comment by cagataycivici** [comment]
Use forum for questions please.
