### ISSUE TITLE
Problems with components in absolutePosition

### ISSUE THREAD

**Issue by sebaiona** [primefaces/primeng#6268]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

When a component is in absolutePosition (because of a property `appendTo` or if it's the standard positioning), depending on the viewport sometimes it's misplaced.

**Expected behavior**

Correct positioning of components.

**Minimal reproduction of the problem with instructions**
Go on the  [overlayPanel page](https://www.primefaces.org/primeng/#/overlaypanel) and put the viewport at 620px of width.
You'll see that the picture goes out of the page whereas it shouldn't because there is enough space.

Same thing if you go on the [Tiered menu](https://www.primefaces.org/primeng/#/tieredmenu) and you open the popup when you have a viewport width of 280px (it's very tricky but it's just to show you the behavior)

For example I have this problem with a dropdown which has a `[appendTo]="body"`.

The problem is located in the DomHandler [here](https://github.com/primefaces/primeng/blob/3414be423b362a9d66df68c1320b52f83f8dd454/src/app/components/dom/domhandler.ts#L134)
It calculates the absolute position assuming that it has to be on the right of the target whereas it's not the case...

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 6.1

* **PrimeNG version:** 6.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
