### ISSUE TITLE
Frozen Columns for DataTable

### ISSUE THREAD

**Issue by KannanMuruganmony** [primefaces/primeng#627]
In PrimeNg data table , is it possible to freeze first few columns and have horizontal scroll-x for the rest ?
I want exactly similar to this :

https://datatables.net/extensions/fixed ... lumns.html

**Comment by KannanMuruganmony** [comment]
Is there any update on this, please? It would be great if you could help me on this or if any work around please let me know. Thanks in advance.

**Comment by KannanMuruganmony** [comment]
Hi Guys, Is this feature getting released any soon? It would be a great help if this feature is done. Please let me know any updates on this. Thanks in advance.

**Comment by cagataycivici** [comment]
#1742
