### ISSUE TITLE
[Calendar][PrimeIcons] - Chevrons lack tabindex which interrupts tabbing, empty href

### ISSUE THREAD

**Issue by Mysame** [primefaces/primeng#6270]
https://github.com/primefaces/primeng/blob/189a80d51fe2cc362db5252ef773ad7715ad6e16/src/app/components/calendar/calendar.ts#L45-L50

Chevrons get "tabbed" to, which makes tabbing out of a Calendar a 2-tab process.
Replicatable on https://www.primefaces.org/primeng/#/calendar , enter a Calendar, press "tab", you can breakpoint and/or notice the left chevron colouring blue.

Fix: Give the `<a>` a tabindex of `-1`

Additionally, empty href's should be replaced by appropriate cursor styling

**Comment by anfeloaiza** [comment]
+1

**Comment by Mysame** [comment]
@cagataycivici I regret to inform that this is *not* fixed by https://github.com/primefaces/primeng/issues/6760 .

A distinction should be made between what requires `tabindex="0"` and `tabindex="-1"`.
`-1` [will be ignored by browser](https://stackoverflow.com/questions/5192859/how-to-ignore-html-element-from-tabindex).

**Comment by AbhijeetGiram** [comment]
**appendTo** property of **p-calendar** interuppts tabbing in form. <br/>
Snippet: `[appendTo]="body"` <br/><br/>
So I updated value of appendTo with ng-template or removed that property and now the tabbing is working fine as expected. Appending the calendar popup to body was causing issue.
