### ISSUE TITLE
EditableCell styling issue

### ISSUE THREAD

**Issue by tiagodws** [primefaces/primeng#6271]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report
```

https://github.com/primefaces/primeng/commit/cf189662fb49abc4dd0591d41c22d310969eff24#diff-856fdbfee191a6d4d9b55443b08a2791R136

This change breaks the styling of every component that has an input inside of an editable cell. What if I'm using a p-autocomplete or p-select, or even a p-inputtext? They all become borderless and without padding.

This rule should only apply to the default editable cell input, or not exist at all.

* **Angular version:** 6.X
* **PrimeNG version:** 6.1.0

**Comment by csvinhal** [comment]
+1

**Comment by cagataycivici** [comment]
Cannot replicate with 7.1.2.
