### ISSUE TITLE
p-table rowsPerPageOptions dropdown does not position properly in new Nova theme

### ISSUE THREAD

**Issue by bomberblue07** [primefaces/primeng#6272]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
The dropdown looks like it doesn't mesh well with the new table CSS. It looks like its spilling out a little. Subtle, but noticeable.

**Comment by bomberblue07** [comment]
This is still an issue despite some of the style changes in 6.1.2. If you create a p-table with a [rowsPerPageOptions] and a summary template, you can definitely see what I see. The bottom of the dropdown spills over a bit into the summary.

**Comment by bomberblue07** [comment]
This is still an issue in 6.1.4. I have a screenshot of what I'm seeing. Until this is fixed, I don't feel right pushing out PrimeNG 6.1+ onto our users

![page_options](https://user-images.githubusercontent.com/20325268/46168020-4b8fc980-c265-11e8-8c02-5f0f5a4a0d93.png)

**Comment by bomberblue07** [comment]
I still see this in 7.0.0-rc.1

**Comment by cagataycivici** [comment]
Works for me using 7.1.2;

<img width="549" alt="Screen Shot 2019-05-10 at 14 41 27" src="https://user-images.githubusercontent.com/686247/57524857-c5c31900-7331-11e9-89ed-01b1c9141a7d.png">

**Comment by bomberblue07** [comment]
@cagataycivici It looks fine when your table doesn't have a summary template (i.e a bar at the bottom of the table), but if you add one, the dropdown spills over a bit onto the summary like in my example screenshot in 7.1.2

**Comment by smarza** [comment]
Hi guys,

I've solved with some css.

::ng-deep p-table {
    .ui-paginator {
        p-dropdown {
          display: inline-block;
        }
    }
}
