### ISSUE TITLE
double clicking the checkbox/radiobutton causes the label to highlight

### ISSUE THREAD

**Issue by SteveMattar** [primefaces/primeng#6278]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
in Chrome when clicking rapidly on the checkbox it highlights the checkbox label, or any other element outside of the component: label, span, input...
i tried to resolve the issue by disabling  the user-select in the css but the issue remains and jumps to the next element

**Expected behavior**
no highlight (just like in IE)

**Minimal reproduction of the problem with instructions**

https://www.primefaces.org/primeng/#/checkbox

**What is the motivation / use case for changing the behavior?**
better ux

**Please tell us about your environment:**

* **Angular version:** 6.0.6

* **PrimeNG version:** 6.0.1

* **Browser:** [Chrome Version 67.0.3396.99 ]

 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =   8.9

**Comment by JacobSiegle** [comment]
Not sure what you mean about it jumping to the next element or even if this is a regression from previous PrimeNG versions, but setting 'user-select: none' on '.ui-chkbox-label' does prevent the checkbox label from being selected on double click.

**Comment by SteveMattar** [comment]
try to set 'user-select: none' on '.ui-chkbox-label' in https://www.primefaces.org/primeng/#/checkbox using F12
Then click rapidly on "Los Angeles" or "Entertainment" check-boxes the label will not be highlighted but the next element which is the "Selected Cities: / Selected Catergories" will be highlighted instead

**Comment by JacobSiegle** [comment]
I see you have to spam click the checkbox not the label, can confirm.

**Comment by JacobSiegle** [comment]
Weird glitch, seems like it can be fixed by adding 'user-select: none' onto p-checkbox in chrome instead of the label.
