### ISSUE TITLE
[Calendar] buttonBar "Today" doesn't update navigators

### ISSUE THREAD

**Issue by Mysame** [primefaces/primeng#6279]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**
https://github-uggfuf-lc637d.stackblitz.io

**Current behavior**
Navigators don't update properly

**Expected behavior**
Navigators should properly update

**Minimal reproduction of the problem with instructions**
Go back/forth a couple of months, then press "Today"
The navigators will still show the month you came from

* **Angular version:** 6.1.2

* **PrimeNG version:** 6.1.0

**Comment by Mysame** [comment]
This because the otherMonth property of the DateMeta is always undefined.
Stil happens in 6.1.2

**Comment by cagataycivici** [comment]
Unable to replicate with 6.1.2.

**Comment by Mysame** [comment]
@cagataycivici , not entirely.
The navigators now update properly thanks to a latest fix, HOWEVER try pressing back / forward on the calendar control after clicking "Today". You'll be back at previous position (with 1 back or forward), NOT from the position of "Today"

https://stackblitz.com/edit/github-uggfuf-fuzz2b?file=src/app/app.component.html

1) Go forward 2 months (October)
2) Press "Today", you'll be at August, controll will close
3) Open control, press forward
4) You'll be at December. Expected result: September

Again, this is because "otherMonth" is undefined when clicking "Today". Only if otherMonth is true will the model be set properly.

https://github.com/primefaces/primeng/blob/master/src/app/components/calendar/calendar.ts#L715-L723
