### ISSUE TITLE
primeNg autocomplete-Problem in bind autocomplete value in *ngFOR

### ISSUE THREAD

**Issue by dharmmaurya563** [primefaces/primeng#6282]
HTML:
__________________________________________________________________________________________________________________
<app-header></app-header>
<style>
  @media print {
    body * {
      visibility: hidden;
    }
    #printableData{
      visibility: visible;
    }  
    .no-print
    {
      visibility: hidden;
    }
    #footer
    {
      visibility: hidden !important;
    }
    input[type=text]
    {
      border: none !important;
    }     
  }
  .ui-autocomplete-panel
  {
z-index: 9999 !important;
  }
  </style>  

<div id="content">
  <div id="content-header" class="no-print">
    <div id="breadcrumb"> <a href="/Dashboard" title="Go to Home" class="tip-bottom"><i class="icon-home"></i> Home</a> <a [routerLink]="['/AddSale']" class="current">Sale</a> </div>
  
  </div>
  <div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
      <div class="widget-content nopadding">
        <div class="widget-box">
          <div class="widget-title no-print"> <span class="icon"> <i class="icon-align-justify"></i> </span>
            <h5>Add Sale</h5>           
          </div>
          <div class="">
            <form action="#" method="get" class="form-horizontal" [formGroup]="saleForm" novalidate> 
               <div class="row-fluid"> 
                  <div class="span12">
                  <div class="control-group">
                      <label class="control-label">Client<small class="text-red">*</small></label>
                      <div class="controls" [ngClass]="displayFieldCss('ClientId')">
                      <p-autoComplete [suggestions]="clientList" placeholder=" Choose client" formControlName="ClientId" [scrollHeight]="200" [forceSelection]="true" [(ngModel)]="ClientId" class="form-control"  field="Name" (completeMethod)="search($event)">
                      </p-autoComplete>
                      <a [routerLink]="['/ClientMaster']" target="_blank"><i class="fa fa-plus-circle"></i>Add</a>
                      <app-field-error-display [displayError]="isFieldValid('ClientId')" errorMsg="Please select client">
                        </app-field-error-display> 
                    </div> 
                    </div> 
                 </div>
                 </div>
                
              <div class="table-responsive">
                <table class="table" id="purchaseList" style="width:100%;">
                    <thead>
                      <tr>
                        <th style="width:5%">SNo</th>
                        <th style="width:15%">Product Name</th>
                        <th style="width:10%">MRP</th>
                        <th style="width:10%">Selling Price</th>
                        <th style="width:10%">Quantity</th>
                        <th style="width:5%">Discount(%)</th> 
                        <th style="width:10%">SGST</th>
                        <th style="width:10%">CGST</th>
                        <th style="width:10%">IGST</th>                       
                        <th style="width:10%">Total</th> 
                        <th style="width:5%">Action</th>                       
                      </tr>
                    </thead>
                    <tbody>                      
                      <tr *ngFor="let product of ProductMList.Plist;let i = index;trackBy: i">
                          <td width="5%"><div class="control-group">{{i+1}}</div></td>     
                        <td  style="width:15%"><div class="control-group">
                        
                        <p-autoComplete [suggestions]="productAutoCompleteList" placeholder="Product Name" [scrollHeight]="200"  [(ngModel)]="product.productName" [ngModelOptions]="{standalone: true}" field="ProductName" class="form-control"  appendTo="body" (onSelect)="fn_SelectedProduct($event,i)"  (completeMethod)="productsearch($event)">
                          </p-autoComplete>
                        <span class='text-error' *ngIf="!product.productName">Required</span>
                      </div> 
                      </td>
                      <td style="width:10%"> 
                        <div class="control-group">                                                  
                          <input type="text" required tabindex="{{i}}2" class="width100" disabled pattern="[0-9]+"  [ngModel]="product.mrp  | number : '1.2-2'" id="mrp{{i}}" name="mrp{{i}}" [ngModelOptions]="{standalone: true}">
                        </div>
                    </td>     
                    <td style="width:10%"> 
                      <div class="control-group">                                                  
                    <input type="text" required tabindex="{{i}}3" class="width100" [disabled]="product.price==0"  [ngModel]="product.price  | number : '1.2-2'" id="price{{i}}" name="price{{i}}" [ngModelOptions]="{standalone: true}">
                      </div>
                  </td> 
                        <td style="width:10%"> 
                            <div class="control-group">
                          <input type="text" required tabindex="{{i}}2" class="width100" [disabled]="product.price==0" pattern="[0-9]+" (keyup)="onQuantityChange();" [(ngModel)]="product.quantity" id="quantity{{i}}" name="quantity{{i}}" [ngModelOptions]="{standalone: true}">
                            </div>
                        </td> 
                        <td width="5%">
                          <div class="control-group">
                        <input type="number" tabindex="{{i}}8" pKeyFilter="pnum"  class="width100" [disabled]="(product.price==0)"  [ngModel]="product.discount  | number : '1.2-2'" id="pdiscount{{i}}" name="pdiscount{{i}}" (blur)="CalculateTotalPrice();" placeholder="(%)"  [ngModelOptions]="{standalone: true}" />
                         </div>  
                      </td>
                        <td style="width:10%">
                            <div class="control-group">
                           <input type="text" required tabindex="{{i}}4" class="width100" [disabled]="product.price==0" [ngModel]="product.sgst  | number : '1.2-2'" id="sgst{{i}}" name="sgst{{i}}" (blur)="CalculateTotalPrice();"  [ngModelOptions]="{standalone: true}">
                            </div>
                          </td>
                          <td style="width:10%">
                              <div class="control-group">
                              <input type="text" required tabindex="{{i}}6" class="width100" disabled  [value]="product.sgst" [ngModel]="product.cgst  | number : '1.2-2'" id="cgst{{i}}" name="cgst{{i}}" (blur)="CalculateTotalPrice();"  [ngModelOptions]="{standalone: true}">
                              </div>
                            </td>
                            <td width="10%">
                                <div class="control-group">
                              <input type="text" required tabindex="{{i}}7" class="width100" [disabled]="((product.sgst && product.sgst>0)||product.price==0)"  [ngModel]="product.igst  | number : '1.2-2'" id="igst{{i}}" name="igst{{i}}" (blur)="CalculateTotalPrice();"  [ngModelOptions]="{standalone: true}">
                                </div>  
                            </td>                           
                         <td width="10%"> 
                            <div class="control-group">                          
                          <input type="text" required tabindex="{{i}}9" readonly class="width100"  [ngModel]="product.totalPrice  | number : '1.2-2'" id="totalPrice{{i}}" name="totalPrice{{i}}" [ngModelOptions]="{standalone: true}">
                            </div>
                        </td>                           
                        <td width="5%">
                          <a *ngIf="i!=0" type="button" class="btn btn-danger btn-sm" (click)="deleteProduct(i)"><i class="fa fa-trash"></i></a>
                         <a *ngIf="i==0" (click)="addProduct(productList)" class="btn btn-success btn-sm" href="javascript:void(0);"><i class="fa fa-plus"></i></a>
                        </td>               
                      </tr>                      
                    </tbody>                   
                  </table> 
                  </div>
                  <hr>
                  <div class="row-fluid">
                      <div class="span6">
                        <div class="widget-box">
                          <div class="widget-title">
                            <span class="icon">
                              <i class="icon-info-sign"></i>									
                            </span>
                            <h5>Bill Detail</h5>
                          </div>
                          <div class="widget-content nopadding"> 
                              <table class="table table-bordered data-table" id="taxList">
                                <thead>
                                  <tr><th>Total Price</th><th>IGST</th><th>SGST</th><th>CGST</th><th>Sub Total</th><th>Discount</th><th>Grand Total</th></tr>
                                </thead>
                                <tbody>
                                  <tr>                                    
                                    <td>{{PriceTotal}}</td>
                                    <td>{{IGST | number : '1.2-2'}}</td>
                                    <td>{{SGST | number : '1.2-2'}}</td>
                                    <td>{{CGST | number : '1.2-2'}}</td>
                                    <td>{{GrandTotal | number : '1.2-2'}}</td>  
                                    <td  width="30%"> 
                                        <input type="text" pKeyFilter="pnum" style="width:30%" max="{{GrandTotal}}" [attr.max]="GrandTotal" [(ngModel)]="ProductMList.Discount" name="discount" [ngModelOptions]="{standalone: true}">%
                                       <input type="text" disabled style="width:30%" value="{{(GrandTotal*(ProductMList.Discount/100))  | number : '1.2-2'}}" />
                                        
                                        
                                    </td>
                                    <td>{{GrandTotal-(GrandTotal*(ProductMList.Discount/100))  | number : '1.2-2'}}</td>                                  
                                  </tr>                                  
                                </tbody>
                                </table>   
                          </div>
                        </div>
                      </div>			
                    </div>      
                  <div class="form-actions no-print">
                      <button type="submit" class="btn btn-success" (click)="addSale(ProductMList)">Save</button>
                      <button type="reset" id="reset" class="btn btn-danger">Reset</button>
                      <button type="button" id="rough" (click)="roughInvoice()" class="btn btn-warning">Rough Invoice</button>
                    </div>           
             
                  </form>
          </div>
          </div>
          </div>
          </div>
          </div>
          </div>
          </div>
          

    </div>
  </div>
</div>
          

/**********************************  ts file */

import { Component, OnInit} from '@angular/core';
import { FormGroup,  FormBuilder,  Validators,  FormControl} from '@angular/forms';
import { WebApiObservableService } from 'app/utility/web-api-observable.service';
import { SaleModel } from 'app/models/Sale-Model';
import { SaleModelList } from 'app/models/Sale-Model';
import { DatePipe } from '@angular/common';
import { DecimalPipe } from '@angular/common';
import {Router,ActivatedRoute} from '@angular/router';

declare var $:any;
declare var swal: any;
@Component({
  selector: 'app-sale-add',
  templateUrl: './sale-add.component.html',
  styleUrls: ['./sale-add.component.css']
})
export class SaleAddComponent implements OnInit {
  public loading = false;
  saleForm: FormGroup; 
  title = 'Add Sale';
  id = 0;
  productSearchList=[];
  returnData=[];
  searchBox='';
  currentTextbox:any;
  GrandTotal: number=0;
  PriceTotal: number=0; 
  IGST: number=0;
  SGST: number=0;
  CGST: number=0; 
  TempGrandTotal: number=0;
  productModel = new SaleModel(0,0,'',0,0,0,0,0,0,0,0); 
  ProductMList=new SaleModelList([this.productModel],0,'',0);
  autoText:String;
  clientList=[];
  invoiceNo:String;
  discount:number=0;
  ClientId=[];
  productAutoCompleteList:any;
  constructor(private formBuilder: FormBuilder, private apiService: WebApiObservableService,private route: ActivatedRoute,
    private router: Router) { 
    this.route.queryParams.subscribe(params => {
      this.invoiceNo = this.route.snapshot.params.InvoiceNo;
   //   console.log(this.invoiceNo); 
  }); 

  }
  ngOnInit() {
    if(this.invoiceNo!=undefined && this.invoiceNo!="")
    {
    this.getInvoiceDetail();
    }
  }

/******************************* Get Invoice Detail ******************* */
/******************************* ****************** ******************* */
  getInvoiceDetail()
  {     
  this.apiService
  .createService('Sale/InvoiceDetail?InvoiceNo='+this.invoiceNo+'',null)
  .subscribe(
    result => 
    {  
      if(result!=undefined && result.status==1)
      {                  
        let invoiceData=result.data;
        this.PriceTotal=invoiceData.PriceTotal;
        this.IGST=invoiceData.IGST;
        this.SGST=invoiceData.SGST;
        this.CGST=invoiceData.CGST;
        
        this.ProductMList=new SaleModelList([],0,'',null);
        //console.log(invoiceData);        
        for (let i = 0; i <= invoiceData.SellList.length-1; i++) {
           let productsData = new SaleModel(
              i,
              invoiceData.SellList[i].ProductId,
              invoiceData.SellList[i].ProductName,
              invoiceData.SellList[i].Quantity,
              invoiceData.SellList[i].Price,
              invoiceData.SellList[i].MRP,
              invoiceData.SellList[i].GranTotal,
              invoiceData.SellList[i].IGST,
              invoiceData.SellList[i].SGST,
              invoiceData.SellList[i].CGST,
              invoiceData.SellList[i].Discount,
              invoiceData.SellList[i]
            );
         
            this.productAutoCompleteList=invoiceData.SellList[i];
            this.ProductMList.Plist.push(productsData);   
          }
          this.ProductMList.InvoiceNo= invoiceData.InvoiceNo;           
          this.ClientId= invoiceData.ClientModel;
          this.ProductMList.Discount=invoiceData.Discount;
        this.GrandTotal=invoiceData.GranTotal;  
        this.CalculateTotalPrice();
      }    
      else
      {
        swal({
          type: 'error',
          title: 'Oops...',
          text: "Something! went wrong."              
        })
      }  
    },
    error => 
    {           
      console.log("Error:"+<any>error);
      swal({
        type: 'error',
        title: 'Oops...',
        text:  <any>error              
      })
    }
  )
  }
  
/*******************************End  Get Invoice Detail ******************* */
/******************************* ****************** ******************* */
}

**Comment by C0dErBJ** [comment]
same problem

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
