### ISSUE TITLE
[Editor] The value is empty when there is only images in the Editor.

### ISSUE THREAD

**Issue by lhysrc** [primefaces/primeng#6284]
![image](https://user-images.githubusercontent.com/4969229/43946259-5016fa9c-9cb7-11e8-8921-2000be42f34b.png)

**Comment by lhysrc** [comment]
If there is only images, the textValue is empty but the htmlValue is not empty.
But this line set it to null.

https://github.com/primefaces/primeng/blob/f81c8c92e6c5d89b9b3533f452445a48c25c523e/src/app/components/editor/editor.ts#L121

**Comment by protonyx** [comment]
This seems to be a duplicate of #6178. I still see this issue in 6.1.4 with Quill 1.3.6

**Comment by cagataycivici** [comment]
#6178
