### ISSUE TITLE
New Component: Wizard

### ISSUE THREAD

**Issue by Neil12cross** [primefaces/primeng#6285]
[ ] bug report
[X] feature request

**Expected behavior**
p-Steps but with wizard functionality like making read only steps till you pass previous one etc.
Example for prime faces jsf : https://www.primefaces.org/showcase/ui/panel/wizard.xhtml

**What is the motivation / use case for changing the behavior?**
It is included in your other packages and can be beneficial for the ng suite as well.

**Comment by dennisahlin** [comment]
Duplicate? https://github.com/primefaces/primeng/issues/4174

**Comment by Neil12cross** [comment]
Yeah it seems so Apologies, Ill close the issue.
