### ISSUE TITLE
styleClass property of Tree is not applying directly to the Tree Node

### ISSUE THREAD

**Issue by monikasaran** [primefaces/primeng#6288]
styleClass property is getting applied to the table tag instead of the div tag(the node).
Hence, style is getting applied to the whole table instead of the node.

This is the issue screenshot:
![image](https://user-images.githubusercontent.com/25126984/43956236-063c45a8-9cc1-11e8-92c9-1e76f027eb8a.png)

Expected screenshot:
![image](https://user-images.githubusercontent.com/25126984/43956271-32a72888-9cc1-11e8-9a67-2217cbaef061.png)

**Comment by cagataycivici** [comment]
This is expected, style class applies to root element, you need to change your css to apply the content section only.
