### ISSUE TITLE
DEFECT: Karma/Jasmine Tests are broken after upgrade of version from 4.1.1 to ^6.0.1

### ISSUE THREAD

**Issue by Raneves** [primefaces/primeng#6293]
After I migrate from: 
``` 
primeng": "4.1.1",
    "primeui": "^4.1.15",
``` 
to 
``` 
 "primeicons": "^1.0.0-beta.9",
    "primeng": "^6.0.1",
``` 
The CSS classes on all my p-datatable changed and my karma tests are broken because some properties is not there anymore. 

Do you guys have some suggestion to put a new **p-table** in my system alongside the old **p-datatable**?

I have a lot of pages that use the old table and I can't change all tables in the same release, I need to change one by one so I have the two tables on my system and the css of the p-datatable was changed and it's affecting my karma tests.

**Comment by JacobSiegle** [comment]
Use the forums for questions - https://forum.primefaces.org/
