### ISSUE TITLE
[Calendar with touchUI and showButtonBar] It doesn't delete the mask-scrollblocker div when you delete the day

### ISSUE THREAD

**Issue by marticrespi** [primefaces/primeng#6294]
**I'm submitting a ...**

[x ] bug report
[ ] feature request
[ ] support request

**Plunkr Case (Bug Reports)**
https://gqaiqymw.github.stackblitz.io

**Current behavior**
I can't show it exactly in the plunkr, but with this configuration of calendar (same in app.component.html) when I choose any day it works well the UI it closes as expected, but when I click on Delete (Borrar) it doesn't delete the div that blocks all the main page. In the plunkr directly doesn't show any calendar and I have the same config as in localhost.

This div iis not deleted.
`    <div class="ui-widget-overlay ui-datepicker-mask ui-datepicker-mask-scrollblocker" style="z-index: 1003;"></div>`

This is the p-calendar configuration
`              <p-calendar [locale]="locale" [showIcon]="true" dateFormat="dd/mm/yy" [touchUI]="true"
                  (onSelect)="onSelectDate($event)" [(ngModel)]="selectedDay" [ngModelOptions]="{standalone: true}" 
                  dateFormat="dd-mm-yy" [disabledDays]="[0]" showButtonBar="true" [showTime]="false" readonlyInput="true">
              </p-calendar>`

**Expected behavior**
When you click on delete day it should delete the commented above div because it blocks all the main page. I'am using 6.1.0 version.

**Minimal reproduction of the problem with instructions**
https://gqaiqymw.github.stackblitz.io

**What is the motivation / use case for changing the behavior?**
Works as expected.

**Please tell us about your environment:**

* **Angular version:** 6.0.7

* **PrimeNG version:** 6.1.0

* **Browser:** Chrome 67.0.3396.99 (Build oficial) (64 bits)
 
* **Language:** TypeScript 2.7.2

**Comment by raymond-kolorbox** [comment]
in calendar.js onClearBUttonClick function, add following line would fix the issue

```
    Calendar.prototype.onClearButtonClick = function (event) {
        this.updateModel(null);
        this.updateInputfield();
        this.overlayVisible = false;
        if (this.mask) {
            this.disableModality();
        }
        this.onClearClick.emit(event);
    };
```
