### ISSUE TITLE
p-calendar not working 6.1.0

### ISSUE THREAD

**Issue by ikiraz18** [primefaces/primeng#6297]
I have upgrade primeng version 6.0.0 to 6.1.0 and p-calendar not working, when i clicked input nothing seems. 

I have Serenity layout.

Angular CLI: 6.0.8
Node: 10.4.1
OS: linux x64
Angular: 6.0.4
![imageedit_2_8108789853](https://user-images.githubusercontent.com/19906678/43992957-1a752fe8-9d8f-11e8-8c9f-39b4e0bc2781.png)

**Comment by cagataycivici** [comment]
This is not a valid issue ticket as a stackblitz template is missing to demonstrate the issue which is vital for us to provide assistance to your case.

Please follow the issue guideline before creating new issues. If the issue still persists with the new version please create a new issue with our stackblitz template.
