### ISSUE TITLE
IE9 Error

### ISSUE THREAD

**Issue by miguelangelorocha** [primefaces/primeng#63]
![debug-ie](https://cloud.githubusercontent.com/assets/6244223/13256067/eebbfe7c-da27-11e5-98ec-51edea99a124.png)

**Comment by cagataycivici** [comment]
We're investigating, could be an issue with angular beta as well.

**Comment by miguelangelorocha** [comment]
Thanks!

**Comment by cagataycivici** [comment]
Just wondering, have you tried running angular2-quickstart on IE9, we've based the showcase on it.

**Comment by miguelangelorocha** [comment]
I tried. The error was the same.

**Comment by Hyperparticle** [comment]
This is a known issue with all Angular Beta versions after Beta.0. You can probably use a temporary fix at https://github.com/angular/angular/issues/6501#issuecomment-176114820 to resolve it until a proper fix is released.

**Comment by cagataycivici** [comment]
Thanks, we'll add that one.

**Comment by cagataycivici** [comment]
Should be fixed now.
