### ISSUE TITLE
Style header of datatable

### ISSUE THREAD

**Issue by edangerfield** [primefaces/primeng#630]
I am looking to style the header of a Datatable.  However, using the following attributes on the header do not seem to be supported in Beta9:

<header [style]="{'font-size':'20px'}">My Header</header>

<header [styleClass]="myStyleClass">My Header</header>

How can I apply a style to a DataTable's Header?  The above is just an example of multiples styles I wish to apply.
- Ted

**Comment by edangerfield** [comment]
The attributes being styleClass and style.

**Comment by cagataycivici** [comment]
Yes, styleClass="yourClass" would help, you can do th.yourClass.
