### ISSUE TITLE
The problem of 6.1.0 Toast CSS

### ISSUE THREAD

**Issue by liuwenhaoCN** [primefaces/primeng#6302]
The angular 6.1.3 CSS style cannot be displayed properly.

**Comment by cagataycivici** [comment]
This is not a valid issue ticket as a stackblitz template is missing to demonstrate the issue which is vital for us to provide assistance to your case.

Please follow the issue guideline before creating new issues. If the issue still persists with the new version please create a new issue with our stackblitz template.

**Comment by liuwenhaoCN** [comment]
Sorry, this is my first feedback. I don't know how to respond.

It is normal to use stackblitz. But I tested it locally, and when I used version 6.1.0, the color didn't show up properly. I didn't change anything. It was normal when I changed to version 6.0.2.

This is the same way I used it locally:
https://stackblitz.com/edit/angular-wtltgd?file=src%2Fstyles.css

**Comment by cagataycivici** [comment]
bootstrap theme is not maintained anymore along with other older free themes. Nova and Premium themes have the official support.

**Comment by zatura33** [comment]
Heres a css template you might use to solve -->  the new p-toast(transparent bg)
`::ng-deep .ui-toast-message-warn{
	background: rgb(235, 235, 145);
}
::ng-deep .ui-toast-message-error{
  background: rgb(235, 145, 145);
}
::ng-deep .ui-toast-message-success{
	background: rgb(156, 235, 145);	
}
::ng-deep .ui-toast-message-info{
  background: rgb(145, 199, 235);
}`
