### ISSUE TITLE
Treetable: Expand icon from Rowtoggler is not visible

### ISSUE THREAD

**Issue by iArnoldo** [primefaces/primeng#6303]
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

I have a simple Treetable with dynamic columns just like in this example: https://www.primefaces.org/primeng/#/treetable
However whenever i expand a row, the expand icon disappears.
The anchor tag has a i Element as a child and in the browser inspector the i has the right icon class: 'pi pi-fw pi-chevron-down'. Anyone else had this issue before?
**NOTE: The Collapsed Icon is visible!**

**Expected behavior**
The Expanded Icon should be visible once a Treetable row has been expanded

* **Angular version:** 5.X

6.0.0

* **PrimeNG version:** 5.X
6.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   8.9.1

**Comment by bjarecki** [comment]
I had this issue as well had to define .pi-chevron-down in sass/theme/_icons.scss

`    &.pi-chevron-circle-up {@include icon-override("keyboard_arrow_up");}
    &.pi-chevron-right {@include icon-override("chevron_right");}
    /*Had to add pi.chevron.down to make p-treetable functional.*/
    &.pi-chevron-down {@include icon-override("keyboard_arrow_down");}
    &.pi-chevron-left {@include icon-override("chevron_left");}`

**Comment by cagataycivici** [comment]
Use forum for questions please.
