### ISSUE TITLE
Should we use p-table or p-datatable?? If I use p-table with the version 6.1.0 it doesn´t get recognized as opposed to p-datatable

### ISSUE THREAD

**Issue by juanlet** [primefaces/primeng#6305]
Which one should we be using. Any working example? Since the ones on the website are broken for the most part. Which is the correct import to be able to use p-table and leave behind p-datatable which is the only one that works? All the videos in youtube shows p-datatables as the main choice for constructing tables as well. The docs are terrible, they should be more complete

**Comment by ctrl-brk** [comment]
p-table (aka TurboTable) is the component to use. Datatable is deprecated and not supported anymore.

**Comment by juanlet** [comment]
but why I´m unable to use it using version 6.1.0....I´m importing the components as shown on the website. Do you have any fiddle or something showing the correct imports??

**Comment by juanlet** [comment]
Which is the difference if you mind to explain?

**Comment by JacobSiegle** [comment]
Read the first line of the docs - https://www.primefaces.org/primeng/#/table
