### ISSUE TITLE
PrimeNG Calendar with hourFormat=12 and utc=true BUG

### ISSUE THREAD

**Issue by TipsyFingers** [primefaces/primeng#6306]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/prime-ng-calendar

**Current behavior**
Currently user is unable to select date (or time) from date picker if hourFormat is set to 12 hour and utc flag to true;

**Expected behavior**
User should be able to select date (and time) with any hourFormat set even though utc is set to true as it is possible situation. I am having problems localizing my application for multiple clients because of this

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/prime-ng-calendar

Using this demo one can see that with default parameters set there everything is working fine and as expected.
Try setting hourFormat to 12 (hourFormat="12") an keep 'utc' flag to true and then try to select a date from picker and you get NaN:NaN:NaN:.........

**What is the motivation / use case for changing the behavior?**
It is not changing behavior, it is making control usable

**Please tell us about your environment:**
Windows 10, using primeng in angular version 5.2.5

* **Angular version:** 5.2.5

* **PrimeNG version:** 5.2.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
ALL

* **Node (for AoT issues):** `node --version` =   8.3

**Comment by TipsyFingers** [comment]
Is there any kind of workaround I could use?

**Comment by cagataycivici** [comment]
There is no utc property in calendar.

**Comment by TipsyFingers** [comment]
Is there any way to use Calendar with UTC? Is there any working example?
I would really like to use only primeng UI elements in my app.

**Comment by kminhtri** [comment]
@TipsyFingers Same for me, impossible to show UTC time :(
