### ISSUE TITLE
Wrong data offset when lazy scrolling with Turbo table

### ISSUE THREAD

**Issue by sautriai** [primefaces/primeng#6311]
With turbo-table, when using lazy scrolling, the scroll/data offset is miss-placed after the lazy loading completes: i.e. the the last visible data row from previous chunk jumps out of visible area when the new data chunk is loaded - this makes the scrolling unusable. This can be seen in demo as well: 
* https://www.primefaces.org/primeng/#/table/scroll
* Virtual Scroll - 250K Rows
* scroll downwards
* see data index ('Vin' column): e.g. index 39 jumps away after the lazy loading occurs
* reproducable with at least chrome and Firefox

```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Comment by RF77** [comment]
I've exactly the same problem here. Happens with v6.0.2 and also with v6.1.2. Additionally if I scroll down by keyboard (arrow down) focus get lost after first lazy load and scrolling stops.

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
