### ISSUE TITLE
has no exported member 'ToastModule'

### ISSUE THREAD

**Issue by rjoydip** [primefaces/primeng#6312]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**stackblitz Case (Bug Reports)**

https://stackblitz.com/edit/ng-prime-toaster-module-issue

**Current behavior**

I am getting below error in my angular 6.x project. But I am getting different issue during reproducing example over `stackblitz`

**My Application Issue**

> Currently getting Module '"/Volumes/../node_modules/primeng/primeng"' has no exported member 'ToastModule'

**Expected behavior**

To work `ToastModule` in angular 6.x project.

* **Angular version:** 6.1.2

* **PrimeNG version:** 6.1.0

 
* **Language:** [TypeScript 2.9.x]

**Comment by cagataycivici** [comment]
Not a valid issue ticket of core, it is just the current issue template doesn't have toast. Will add it though.

**Comment by sudheerj** [comment]
@cagataycivici How to import Toast module for now in the latest release

**Comment by adampenn** [comment]
@cagataycivici I also would like to know how to successfully import this module... Prime NG seems to be seriously lacking in the documentation department.
