### ISSUE TITLE
Overlay Panel goes behind Sidebar

### ISSUE THREAD

**Issue by kishor-p** [primefaces/primeng#6315]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Could not create the example since I could not import p-sidebar component on template created by stackblitz 

**Current behavior**
When a `p-overlayPanel` is added in `p-sidebar` component. The `p-overlayPanel` does not appear.
IT goes behind the Sidebar component.

**Expected behavior**
The `p-overlayPanel` should appear.

**Minimal reproduction of the problem with instructions**
Create a  `p-sidebar` component with  `p-overlayPanel` inside it.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.X

* **PrimeNG version:** 5.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
6.1.1 overlay has baseZIndex to solve this, you can also use baseZIndex of sidebar with 6.1.0 to solve this as well. [baseZIndex]="50", so that overlay panel zindex will be bigger. Still can't say much without a template.

**Comment by kishor-p** [comment]
@cagataycivici  Thanks and great full for your reply.


Actually the `p-overlayPanel` is inside a child component of `p-sidebar`.

```
<p-sidebar>
    <app-child-component>
      
          <!-- OverLay Component is inside the  "app-child-component"s template(html) -->     

    </app-child-component>
</p-sidebar>
```

So baseZIndex on Sidebar is not working. I guess I will have to wait till 6.1.1 arrives.

Is there any other trick, to achieve this in 6.1.0 ?

**Comment by gzapata90** [comment]
I'm having the same problem. My template looks similar to @kishor-p 's:
```
<p-sidebar>
  <app-my-component>
    <p-overlayPanel [baseZIndex]="9999"></p-overlayPanel>
  </app-my-component>
</p-sidebar>
```
No matter how high I set the baseZIndex on the overlay panel, it still doesn't show up because of the sidebar. Setting the style inline as
```
<p-overlayPanel style="z-index: 1010;"></p-overlayPanel>
```
doesn't work either.

Any pointers?

**Comment by KokolM** [comment]
Adding this to angular theme file worked for me:

`.p-sidebar-mask {
  z-index: 10 !important;
}

.p-sidebar {
  z-index: 20;
}
`

**Comment by rohitpatilblazeclan** [comment]
Thanks @KokolM  this also worked for me. Many thanks for saving lots of time.
