### ISSUE TITLE
ConfirmDialog works on 6.0.1 stopped work on update

### ISSUE THREAD

**Issue by ningacoding** [primefaces/primeng#6320]
i had to get back to 6.0.1 because on update ConfirmDialog stopped working.

**Comment by cagataycivici** [comment]
This is not a valid issue ticket as a stackblitz template is missing to demonstrate the issue which is vital for us to provide assistance to your case.

Please follow the issue guideline before creating new issues. If the issue still persists with the new version please create a new issue with our stackblitz template.
