### ISSUE TITLE
p-dialog error when closing a dialog in PrimeNG 6.1.1

### ISSUE THREAD

**Issue by ASK83** [primefaces/primeng#6321]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
This is a bug that has been introduced since the last update of PrimeNG. I have a wraper from p-dilaog and a parrent component that is being shown inside the dialog and whenever I close out of the dialog I get lost of calls to ngDestroy and error as bellow:
![dialog-issue](https://user-images.githubusercontent.com/17345249/44112936-2c3247f4-9fcc-11e8-84aa-41a61cd552ce.PNG)

I have added a log statement at each step of ngDestroy and that hook is being called more than 300 times and finally errors out. 

I tracked the bug in the code and found out that this.onHide.emit({}); has been added to onOverlayHide function. After moving that back to be called just once at onAnimationStart void step the issue was fixed. For now I am going to change the source code so I don't have to move back to the previous version. 

**Please tell us about your environment:**

* **Angular version:** 6.1.2

* **PrimeNG version:** 6.1.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
This is not a valid issue ticket as a stackblitz template is missing to demonstrate the issue which is vital for us to provide assistance to your case.

Please follow the issue guideline before creating new issues. If the issue still persists with the new version please create a new issue with our stackblitz template.
