### ISSUE TITLE
p-message severity icon covers message

### ISSUE THREAD

**Issue by maplion** [primefaces/primeng#6323]
```
[ x ] bug report
```

**Current behavior**
As you can see here:

https://stackoverflow.com/questions/51850744/primeng-p-message-severity-icon-covers-message-angular-6-primeicons

the severity icon on the message box covers the actual message. Has anyone else experienced this and/or knows of a way to resolve it (in a manner that doesn't require hacking on the source code)? Thank you.

**Expected behavior**
I expect the icon to be to the left/upper left of the message box as it seemed to be in previous versions.

**Minimal reproduction of the problem with instructions**
Create a PrimeNG message box using PrimeNG 6.1.0 and p-message.

```
Angular CLI: 6.0.8
Node: 8.9.4
OS: win32 x64
Angular: 6.1.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.7.2
@angular-devkit/build-optimizer   0.7.2
@angular-devkit/build-webpack     0.7.2
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  6.1.2
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.9.2
```

* **PrimeNG version:** 
"primeicons": "1.0.0-beta.10",
"primeng": "6.1.0",

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome (Version 68.0.3440.106 (Official Build) (64-bit)), Firefox, Edge.

**Comment by cagataycivici** [comment]
This is not a valid issue ticket as a stackblitz template is missing to demonstrate the issue which is vital for us to provide assistance to your case.

Please follow the issue guideline before creating new issues. If the issue still persists with the new version please create a new issue with our stackblitz template.
