### ISSUE TITLE
TurboTable with p-checkbox not working - PrimeNG

### ISSUE THREAD

**Issue by alexfcg** [primefaces/primeng#6328]
I developed a screen that has a TurboTable and one of the columns is checkbox. I made the TurboTable configuration as specified in the documentation but all checkboxes return marked when loading the data or do not appear at first, but if you click on the line the checkbox is displayed. Someone to instruct me to make when loading the data from the backend the checkboxes are loaded with the values marked or not, depending on the data loaded.

**Comment by cagataycivici** [comment]
Please use forum for questions and support requests.
