### ISSUE TITLE
DataView search clear button not restoring the original data

### ISSUE THREAD

**Issue by nsksaisaravana** [primefaces/primeng#6331]
DataView search is working fine but when we click the clear icon (x) it clear the search textbox but not restoring the whole dataview data. 

Please check the screenshot, i searched for honda and after clear the search value, still i am viewing only the honda related data not the whole data.

![image](https://user-images.githubusercontent.com/17681573/44183974-a5727f00-a150-11e8-8226-ed7033c7d675.png)

**Comment by yigitfindikli** [comment]
Hi,
When you pushing the clear icon keyup event is not firing. You can use input event like this;

```
<input type="search" pInputText placeholder="Search by brand" (input)="dv.filter($event.target.value)">
```
