### ISSUE TITLE
p-inputSwitch: readonly support request

### ISSUE THREAD

**Issue by sunnyyadav100** [primefaces/primeng#6332]
I am submitting a

```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

readonly support in p-inputSwitch component.

**Current behavior**

Either it is editable or disabled.

**Expected behavior**

Need a support of readonly , just to show the ngModel state

* **PrimeNG version:** 5.X

PrimeNG version: 6.0.0-rc.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 all

**Comment by JacobSiegle** [comment]
You can still set the model state when the switch is disabled?
https://github-tgxspa-62tzh6.stackblitz.io

**Comment by sunnyyadav100** [comment]
Somehow, I am not able to view above stack blitz URL.
Use case here is , I have a form which has two modes - editable and readonly.  I want to show p-inputSwitch value as readonly when form is readonly.

**Comment by JacobSiegle** [comment]
Not sure why stackblitz is broken. I guess my question is how is setting the ngModel state and disabled to true any different then readonly mode?
