### ISSUE TITLE
Tab key navigation should stay inside the modal scope

### ISSUE THREAD

**Issue by SteveMattar** [primefaces/primeng#6333]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Waiting Time: ~8 weeks.

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**

Tab key navigation goes outside of the modal scope. we should prevent this behavior.

**Expected behavior**

When pressing tab key the focus navigation should be kept inside the modal scope by default
especially when there are yes/no buttons in the footer.

**Minimal reproduction of the problem with instructions**

https://www.primefaces.org/primeng/#/dialog

**What is the motivation / use case for changing the behavior?**

better ux

**Please tell us about your environment:**

* **Angular version:** 6.0.6

* **PrimeNG version:** 6.1.2

* **Browser:** [Chrome Version 67.0.3396.99 ]

 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =   8.9

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/issues/4544
