### ISSUE TITLE
Styles not applied to pButtons in v6.1.2

### ISSUE THREAD

**Issue by DanielChicot** [primefaces/primeng#6336]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/github-umn5nl

**Current behavior**
The pbutton has the class "ui-button-secondary" but it has the default blue background colour.

**Expected behavior**
The pButton should have a white background

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
Not working as described in the documentation.

**Please tell us about your environment:**
Oracle linux 7, emacs, yarn. ng serve.

* **Angular version:** 5.X
6.1.2

* **PrimeNG version:** 5.X
6.1.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome, firefox

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 
* **Node (for AoT issues):** `node --version` =   
10.8.0

**Comment by DanielChicot** [comment]
Thank you @bomberblue07 ,  in future I'll read those release notes.

**Comment by timmackey** [comment]
Where are the release notes?

**Comment by DanielChicot** [comment]
@timmackey - it says [here](https://www.primefaces.org/primeng-6-1-0-released/) that the old styles are now deprecated.

**Comment by timmackey** [comment]
got it.  Thanks.  this issue can be closed.
