### ISSUE TITLE
p-tree doesn't expose the "ui-state-active" class on checkbox

### ISSUE THREAD

**Issue by Macadoshis** [primefaces/primeng#6341]
You can easily see the issue on the showcase : https://www.primefaces.org/primeng/#/tree

the checkbox doesn't expose the ``ui-state-active`` and thus the style of the checkbox will differ from the style of a ``<p-checkbox>``.

Is it a desired behavior or a mistake ?

Current version : 6.1.2

**Comment by rafa-as** [comment]
@cagataycivici some news here?

**Comment by cagataycivici** [comment]
This is by design to prioritize the content.
