### ISSUE TITLE
ConfirmDialog screen position not working properly

### ISSUE THREAD

**Issue by cleitondutra** [primefaces/primeng#6342]
[X] bug report 

**Current behavior**

Go to a page that has scroll, open the confirmDialog, example in attached image.

**Expected behavior**

After running confirmDialog the page position (that is in the background) should not go to the top of the page. The position of the screen should remain in the same position when the dialog was opened.

**Minimal reproduction of the problem with instructions**
Image

![primedialog](https://user-images.githubusercontent.com/17409145/44222959-94c80600-a15c-11e8-88fb-788dfc4e1098.gif)

* **Angular version:** 6.X

* **PrimeNG version:** 6.1.2

* **Browser:** [all]

 
* **Language:** [all]

**Comment by cagataycivici** [comment]
This is a regression caused by trying to support iOS block scroll, more info at;

https://medium.com/jsdownunder/locking-body-scroll-for-all-devices-22def9615177

I'll just revert it as it causes more problems and keep iOS issue as open.
