### ISSUE TITLE
Dateview components' search will not work properly in second pagination onwards

### ISSUE THREAD

**Issue by nsksaisaravana** [primefaces/primeng#6346]
Dateview search is working fine until you click the pagination button, as soon as you click the second pagination button and try to search, it is not working properly. Please check the below screenshot.

I suppose to get more results but I am getting only one result.

![image](https://user-images.githubusercontent.com/17681573/44248141-32d6d180-a22c-11e8-9f51-638d95aa6a14.png)

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
