### ISSUE TITLE
Cell editing stop working after updating table data with invalid field and closeCellEdit() error when no cell is being edited

### ISSUE THREAD

**Issue by leonardolessa** [primefaces/primeng#6350]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/github-vjv5qo-t6axmy

**Current behavior**
There are two behaviors in the stackblitz I linked here:

1. THIS IS NOT NECESSARILY A BUG: Edit an year column cell (that is required) and then click to update all table data. Remove closeCellEdit() (comment the code to see the behavior), after this point the table won't edit any other cell. Not sure if the closeEditCell is the correct way to solve it (but it solves)

2. Using closeCellEdit() will pop errors in the console if there is no cell being edited at the moment.
I've searched for a way to conditionally call closeCellEdit() but I guess there is no easy way to achieve it, and I believe it would be easier if this checking could be made in the function call itself.
The error:
`ERROR
Error: Cannot read property 'classList' of null`

So I'm not sure by default the table would have to handle the table data update (but here is my suggestion) and be able to edit the data again, but the only workaround that is the closeCellEdit() to solve that is giving errors or making it a little complex to handle.

**Expected behavior**
The table should show the data normally and edit the new values as default, (with closeCellEdit or not) with no complexity aside codes.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 6.1.2

* **PrimeNG version:** 6.1.2

* **Browser:** all

Sorry if it's not clear, I've choose to maintain both issues here to see the logic I'm trying to achieve.
Thanks.

**Comment by frabock** [comment]
What about simply disabling the update button (with angular form valiation) if nothing has changed?

**Comment by leonardolessa** [comment]
Hi @frabock,
Thanks for your suggestion.

This is just an example to show when this happens, in my project there is two ways to achieve the same problem.

In one case I have a tab panel that changes the table data, in another one is a couple of fields that filter the data, it doesn't seem to be nice to the user to block the tabs or the fields, you know? it would be too "blocking" the user to do something, and maybe the user just regretted to change the value, if he doesn't remember the initial value it would be required that he filled with anything else (or refresh the page).

**Comment by yigitfindikli** [comment]
Hi,
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.

You can check at https://www.primefaces.org/primeng/#/table/edit .
