### ISSUE TITLE
Maximise button not resetting upon close of dialog

### ISSUE THREAD

**Issue by hugonoro** [primefaces/primeng#6358]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Waiting Time: ~8 weeks.

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/github-jhuge4

**Current behavior**
When opening a dialog and maximising it, if the dialog is closed without being restored (revert maximisation), the state of the maximise button is not reset. The consequence is that when the dialog is opened again, it will be in the state of currently maximised. The user has to click it twice to be able to maximise again.

**Expected behavior**
Upon closing of a dialog the maximise button should always reset it's status to prevent the reported issue. One other possibility, if wanting to preserve the maximised status, would be to reopen the dialog maximised, but I believe that would be less obvious to the user. 
Nevertheless, the state of the button should always reflect the current state of the dialog (maximised or not)

**Minimal reproduction of the problem with instructions**

1. Load the application
2. Click the Dialog button
3. Click the maximise button in the top right corner of the dialog
4. Click the close button (x in the top right corner)
5. Click the Dialog button again

The maximise button will be in the incorrect state. The user has now to click it twice to maximise again.

**What is the motivation / use case for changing the behavior?**
The state of the maximise button should reflect the current state of the dialog (maximised or not) when open/visible

**Please tell us about your environment:**

* **Angular version:** 6.0.3

* **PrimeNG version:** 6.1.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   10.6.0

**Comment by cagataycivici** [comment]
This is expected and by design, user has closed the dialog so state has been reset. If there is more demand, we can reconsider.
