### ISSUE TITLE
frozenColumn on right side of p-table

### ISSUE THREAD

**Issue by gawielgo** [primefaces/primeng#6361]
**Current behavior**
frozenColumn is only in left side of all table

**Expected behavior**
a property or something for set frozenColumn in right side

**What is the motivation / use case for changing the behavior?**
I have an action column that is less important of the other columns and i want show it in right side of p-table

* **Angular version:** 6.X

* **PrimeNG version:** 6.X

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
