### ISSUE TITLE
Controlling the height of year dropdown on PrimeNg Calendar

### ISSUE THREAD

**Issue by 2421990vivek** [primefaces/primeng#6364]
Currently, there seems to be no parameter to control the height of the year. Also, the dropdowns and buttons on Edge browser seems to break. Below are the screenshots:

Calendar DropDown on Chrome:
![primengdatepickerissue](https://user-images.githubusercontent.com/42566798/44385396-ded63080-a53c-11e8-8e85-190891aa1cbc.png)

Calendar DropDown and Buttons on Edge Browser:
![primengdatepickerissue](https://user-images.githubusercontent.com/42566798/44385575-6de34880-a53d-11e8-8bc8-64c6a5b74121.png)

Buttons on Prime Ng Calendar Edge Browser:
![primengdatepickerissue](https://user-images.githubusercontent.com/42566798/44385632-9cf9ba00-a53d-11e8-9efe-edbdec1aa435.png)

Request your help on this.

Thanks,
Vivek

**Comment by cagataycivici** [comment]
That dropdown is native select so it is related to the browser.

**Comment by jperera84** [comment]
I think will be very helpful to set the size of the select
`size="10"`
That we can set with a property in the component

**Comment by gmerabishvili** [comment]
Can I set the max-height at this moment somehow?
