### ISSUE TITLE
PrimeNg Calendar- Clicking on Enabled Grayed out Date Disappears the Calendar Panel

### ISSUE THREAD

**Issue by 2421990vivek** [primefaces/primeng#6365]
Hi,

On clicking of enabled grayed out date disappears the calendar panel:

![primengdatepickerissue](https://user-images.githubusercontent.com/42566798/44385945-9e77b200-a53e-11e8-8045-8f643b8029f8.png)

Expected behaviour:- The Calendar Panel should close only on the below 3 scenarios:

1) Selecting a date
2) Clicking on Today Button
3) Clicking on Clear Button

Request your help here.

Thanks,
Vivek

**Comment by fperezgaliana** [comment]
Hi,

I also use the calendar module in a couple of apps and it works fine. Did you try to update primeng (I'm using version 6.1.2)?

Cheers,

**Comment by 2421990vivek** [comment]
I am using version 6.1.1.
I imported the calendar module into my dummy app(just to test), its behaving the same way.
The properties I am using from prime ng calendar is as below:
[dateFormat]
  [yearRange]
  [(ngModel)]
  [showIcon]
  [monthNavigator]
  [yearNavigator]
  [defaultDate]
  [maxDate] 
  (onSelect)
  (onMonthChange) 
  (onYearChange)
  (onClearClick)
  (onClose)
  (onInput)
  (onFocus)
  (onBlur)

**Comment by cagataycivici** [comment]
6.1.2 works fine;

https://www.primefaces.org/primeng/#/calendar
