### ISSUE TITLE
LazyLoadEvent not triggering properly

### ISSUE THREAD

**Issue by arjun-varrier** [primefaces/primeng#6366]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/github-dgmc8w

**Current behavior**

The LazyLoadEvent is not being triggered properly. As you can see in the console of the Plunkr link (above), the event is triggered only for the first 3 pages that is till record number 24 whereas, there are a total of 31 records. which means there should have been more pages.

We are facing a similar issue in our project where there are 48 records and the LazyLoadEvent is been triggered twice and we are getting 20 + 20 records. But the event is not getting triggered when we scroll beyond 40th row.  

**Expected behavior**

Expected behavior is that, the LazyLoadEvent must be triggered when we scroll beyond the 24th record (in case of plunkr) and beyond 40th record in my project's case

**Minimal reproduction of the problem with instructions**

Steps to reproduce:
1. Open the console.
2. Load the page.
3. Scroll on the table and notice the console logs 

* **Angular version:** 6.0.6

* **PrimeNG version:** 6.0.0

* **Browser:** Chrome 68.0.3440.106

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
