### ISSUE TITLE
Carousel - previous/next button to slide does nothing #4449

### ISSUE THREAD

**Issue by Foszcz** [primefaces/primeng#6367]
[x ] bug report => Search github for a similar issue or PR before submitting

**Current behavior**
I pass to the carousel a value, with a numVisible to 5. My value is an empty array for a short time and next is an array of objects. so if i click on the next button to slide the carousel it should be slide on the next visible items but the next button do nothing. 

**Expected behavior**
The carousel should be slided on the next visible items, even if the first value is an empty array

**Minimal reproduction of the problem with instructions**
Pass a value array with more items than the numVisible in an Observable with a pipe async to the carousel

I duplicate this issue because the problem is again present in version 6.0.0-rc1 , here is the stackblitz of the issue..
https://stackblitz.com/edit/github-trkjme .

Is there a solution? or a development in progress? there are no news since a moment and the first open issue is closed since november .

Thanks in advance 

* **PrimeNG version:** 6.0.0-rc.1

* **Browser:** [all]

**Comment by bechar-ce** [comment]
Also it's not start rotating after setup the autoPlay="true"

<p-carousel headerText="Book Detail From JSON" [value]="iBooksdatas" [responsive]="true" numVisible="1" autoplayInterval="3000" autoPlay="true">

Thanks
-Bechar

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
