### ISSUE TITLE
[p-chips]: How to set the dynamic background color for each chip

### ISSUE THREAD

**Issue by LinusLing0910** [primefaces/primeng#6376]
Current I only can set the background color for ui-chips-token-labels, but cannot set the background for ui-chips-token directly, so the UI shows as below:
![image](https://user-images.githubusercontent.com/35553852/44450323-3fee1a80-a5b6-11e8-972e-e6ce6a441cc1.png)

Any know how to achieve it?

**Comment by cagataycivici** [comment]
Please use forum for support requests and questions, thank you.
