### ISSUE TITLE
PrimeNG Calendar Issues V 6.0.2

### ISSUE THREAD

**Issue by 2421990vivek** [primefaces/primeng#6379]
Hi,

On Upgrading Prime Ng Version to 6.0.0 to 6.0.2, the functionality of the calendar seems to be breaking.
On providing DefaultDate parameter, the calendar panel seems to remember this itself.

Step1 - > The calendar panel updates only selecting the month and year dropdown and selecting the date.

Step2 ->  Now, when I click on Today Button, and hit on the next/prev month navigation button the calendar seems to be rotating from the one selected from the year and month dropdown, whereas it should be propagating from the current entered date.

Also the Css seems to break too. Below are some of the screenshots:

Step1 - >Selection of Date using Month and Year DropDown to 01-Jan-1937:

![calendar](https://user-images.githubusercontent.com/42566798/44465617-b7b25880-a63b-11e8-827f-7aa20986a86b.png)

Step2 - >Navigating to Today's Date on Clicking Today:
![calendar](https://user-images.githubusercontent.com/42566798/44465702-f6e0a980-a63b-11e8-886c-905fbab486e1.png)

Step3 - > Hit on Next/Prev navigation Button, the calendar navigates from the date selected from Step1:

![calendar](https://user-images.githubusercontent.com/42566798/44465813-46bf7080-a63c-11e8-8fbf-14269085fe7e.png)

Also the Css is bit broken. The Css I applied for Version 6.0.0 by overriding the CSS of Prime NG was working perfectly fine and it broke once I upgraded to 6.0.2. The functionalities too was working perfectly fine.
Below is the screenshot for calendar from version 6.0.0:

![calendar](https://user-images.githubusercontent.com/42566798/44465918-92721a00-a63c-11e8-96cd-226a825ccae0.png)

**Comment by cagataycivici** [comment]
Try the latest version please e.g. 6.1.2, worked fine for me.

**Comment by 2421990vivek** [comment]
Hi,

This will work fine until we give the default Date parameter.
Once we give the default date parameter the calendar wont navigate properly and the issue still persists.

The calendar panel isn't navigating from the date entered on the text box.

Thanks,
Vivek
