### ISSUE TITLE
Changing p-schedule option causes no refresh

### ISSUE THREAD

**Issue by bvica** [primefaces/primeng#6386]
**I'm submitting a ...
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
I'd like to set week's first date dynamically in a dropdown, because some user find default value unfit.
Since Schedule has no firstDate property, I set it in options:
 [options]="{'firstDay': this.config.calendarFirstDay}"
After I change dropdown value, the schedule is not refreshed, first day remains the same.

**Expected behavior**
Changing the first day of week the schedule displays calendar according to the selected value.
I think schedule should have firstDay property to be easy configurable, or the ngChange() method should listen to the option values too.

**Comment by noamichael** [comment]
So, I just created pull #6567, which, if accepted, will hopefully fix this. You would have to do something like this:

```typescript
@Component({
    template: `
        <select [(ngModel)]="calendarFirstDay" (ngModelChange)="onFirstDayChange($event)"><!--Options Here--></select>
        <p-schedule [events]="events" [options]="options"></p-schedule>
    `
})
export class MyComponent {
    options: any = {}
    calendarFirstDay: number
   
    onFirstDayChange($event: number) {
        this.options = {firstDay: $event};//have to create a new object to trigger change detection
    }
}

```
