### ISSUE TITLE
Initialize p-tree with selected checkboxes

### ISSUE THREAD

**Issue by gauravoodles** [primefaces/primeng#6391]
Hi, 
Initially, I want to show <p-tree> some of the checkboxes of p-tree to be selected, i.e. to store their state on check uncheck. How to do that?

**Comment by kdyzm** [comment]
我也想知道这个。。

**Comment by daqiang123** [comment]
How can p-tree select nodes? Thank you.

**Comment by cagataycivici** [comment]
Please use forum for questions and help requests.i
