### ISSUE TITLE
InputSwitch label broken in v6.1

### ISSUE THREAD

**Issue by whoknows** [primefaces/primeng#6392]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
p-inputSwitch label not displaying anymore since 6.1, on/off label api seems gone as well.

**Expected behavior**
p-inputSwitch with **onLabel="Yes" offLabel="No"** should display "yes" or "no" depending on the input state.

**Minimal reproduction of the problem with instructions**
Go to the demo page https://www.primefaces.org/primeng/#/inputswitch

* **Angular version:** 6.1

* **PrimeNG version:** 6.1

**Comment by cagataycivici** [comment]
Not supported anymore.

**Comment by aglaberson** [comment]
Please update your documentation @cagataycivici 
![image](https://user-images.githubusercontent.com/18406070/63371941-0da30480-c353-11e9-8528-f22f287398e5.png)
