### ISSUE TITLE
p-calendar's navigation (left/right) is not in sync with selected date, if date is not in current year

### ISSUE THREAD

**Issue by ChristianMetzner** [primefaces/primeng#6393]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-eewso5

**Current behavior**
When navigating forward/backward calendar is initially setting the wrong year when the selected date is not within the current year.

**Expected behavior**
When navigating forward/backward calendar is setting the previous/next month, relying on the current selected date (year).

**Minimal reproduction of the problem with instructions**
Set a date that is not within the current year. Then click on backward navigation. Calendar is now setting the previous month, but using the current year, instead of the year which is set by the selection. Same happens on forward navigation

* **Angular version:** 6.1.2

* **PrimeNG version:** 6.1.0

**Comment by cagataycivici** [comment]
#6393
