### ISSUE TITLE
Stronger Types

### ISSUE THREAD

**Issue by MikeMatusz** [primefaces/primeng#6394]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
Despite being developed in TypeScript, PrimeNG doesn't have much in the way of strong types.  Most component properties are untyped, and methods don't have return types or types on their arguments.  Even important configuration objects, like column definitions for tables, don't have interfaces to define the allowed/expected properties.  Developers have to rely on documentation (which is sometimes lacking or out of date, and inconvenient) or source code (which is time-consuming) to know what their options are and what values are allowed.  And it's easy to make a typo and have to waste time debugging.

**Expected behavior**
The "any" type would be rarely used, preferring interfaces or other strong types whenever possible.  All functions would have return types and types for parameters specified.

**What is the motivation / use case for changing the behavior?**
Better IntelliSense while developing.  Compile time error reporting.  Assurance when you upgrade to a new version whether contracts have changed.

* **PrimeNG version:** 6.1.2
 
* **Language:** TypeScript

**Comment by cagataycivici** [comment]
Issue is too broad, please create per component level issues.

**Comment by MikeMatusz** [comment]
That's fair, I'll create one more focused around TurboTable with more specific details.  I understand the need to be able to action and close an issue.

I do hope strong types could be more of a consideration in general for new development, as I feel like they're as beneficial to the developers themselves to the consumers of the API.  I can't count anymore the number of times I've been triaging a defect in an area without strong types, start to add some, and end up seeing the cause of the defect underlined in red.
