### ISSUE TITLE
Autocomplete mouse selection in suggestion can selects another element in multi-select mode

### ISSUE THREAD

**Issue by lavamen** [primefaces/primeng#6395]
**Current behavior**
If we started to type a text "car" in the search field and we have in suggestion list a few elements like "car, car1, car2, car3" and we select "car1" (or other car with number) by mouse, the component adds "car" to selection list. The bug is reproduced with forceSelection="true". It works with keyboard selection.

**Expected behavior**
The component should add selected element

* **Angular version:** 5.X
5.2.6

* **PrimeNG version:** 5.X
PrimeNG 5.2.6

* **Browser:**
Chrome Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by cagataycivici** [comment]
Provide stackblitz template with step by step instructions as I'm unable to replicate.

**Comment by lavamen** [comment]
I checked the latest version, it works, thank you !
