### ISSUE TITLE
new version of quill is not supported

### ISSUE THREAD

**Issue by dolphinsd** [primefaces/primeng#6396]
Quill have introduced new apis and changed others. Now it does not work with p-editor.

For example, pasteHTML is removed.

And old bug still there, if there is no text, only html, like image, it would not save the model.

Remove this code:
   if (text.length === 0) {
                  html = null;
}

**Comment by cagataycivici** [comment]
What is the version number you are referring to?

**Comment by rahul-winner** [comment]
could anyone please confirm which version of Quill is supported by PrimeNG:6.1.4 Editor?

**Comment by rafa-as** [comment]
@cagataycivici some news here? The actual Quill version 1.3.6 deprecate the pasteHTML function.

**Comment by yigitfindikli** [comment]
Hi,
Latest quill version 1.3.6 and PrimeNG uses 1.3.6 you can check at https://github.com/quilljs/quill/releases or https://www.npmjs.com/package/quill .
