### ISSUE TITLE
Could you remove jQuery?

### ISSUE THREAD

**Issue by ibufu** [primefaces/primeng#64]
:)

**Comment by cagataycivici** [comment]
In future, I guess we'll remove it but we've tuned PrimeUI widgets for PrimeNG so they work in harmony. So we'll keep it for the time being.  Please see jQuery section at setup page for details;

http://www.primefaces.org/primeng/#/setup

jQuery in enhanced mode only does low level things like positioning, class add remove, no dom manipulation. This ensures great level of compatibility.

Still we write some of the components natively, like datatable, checkbox, radio, messages and more will be native along the way.

**Comment by yelhouti** [comment]
only thing preventing me from using primeng is jquery, when are you planning to remove it please?
