### ISSUE TITLE
pKeyFilter ignore filter when paste text

### ISSUE THREAD

**Issue by upmauro** [primefaces/primeng#6401]
```
[X] bug report
```

**Minimal reproduction of the problem with instructions**
Use pKeyFilter in input with int filter and paste text with invalid caracteres.

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
I think fixed in https://github.com/primefaces/primeng/commit/d450d19bb7da80d362d42fe86d6f7cbb2aca3d68
