### ISSUE TITLE
Datatable pagination is not updating rows properly

### ISSUE THREAD

**Issue by G-Maan** [primefaces/primeng#641]
Hi,
I encountered something which might be a bug while using datatables with sorting and pagination.

[table.component.html.txt](https://github.com/primefaces/primeng/files/377888/table.component.html.txt)
[table.component.ts.txt](https://github.com/primefaces/primeng/files/377889/table.component.ts.txt)

When there is one type of data in a column (in my example it is only 'Pink Flamingo' in all rows in column 'customer' and I'm on page other than the first one I click sort then this bug happens. The button for first page is greyed out and it seems like it went to the first page(also buttons to go back once and to the very first are greyed out) but the page stays where it was (on second one) and data remains unchanged. Also even tho you are not supposed to be able to click on greyed out pagination arrows I am still able to click the very left arrow indicating going to first page. Same with clicking on page 1 while it is greyed out, it brings me to first page indeed while saying it already was on page 1.

Any thoughts on this issue?

**Comment by sambanthar** [comment]
me to facing issue
