### ISSUE TITLE
Cloning Ticket #6379, since the issue still persists on #6379 PrimeNg Calendar

### ISSUE THREAD

**Issue by 2421990vivek** [primefaces/primeng#6411]
Cloning this ticket #6379.

The PrimeNg V6.1.2 Calendar panel does not seems to navigate correctly when we assign the default date parameter.

Step1- Set default date to 01-01-1973
Step2 - Click on Today Button.(08-29-2018)
Step3:- Hit on next navigation button
             Expected - September Month should come
             Actual- Calendar is navigating to Feb 1973(1 month after the default date)

Whereas this worked as expected on PrimeNg V 6.0.0

Thanks,
Vivek

**Comment by cagataycivici** [comment]
#6393
