### ISSUE TITLE
Filter, multi sort, multi select filter, empty message for the table is not working with virtual scroll

### ISSUE THREAD

**Issue by MalliswariKP** [primefaces/primeng#6412]
Hi,

I am trying to implement virtual scroll for my table and found that few of the features are not working with this like filter, sorting, empty message and resize.

Did you guys already started implementing these features? Or Is there any plans to implement same in future?

Also, ctrl + click works for multi selection if we use metadata key. What if we want to select items using shift like in window. Is primeng supporting that feature as well??

**Comment by cagataycivici** [comment]
Please use forum for help requests. You need to use lazy loading.
