### ISSUE TITLE
Drop down selectedItems doesn't work.

### ISSUE THREAD

**Issue by vijaygawade18** [primefaces/primeng#6414]
Hi @cagataycivici, I am using primeng in my project and facing some issue while implementing the drop down which shows the content with filter.

**Current behavior**
selectedItem isn't working in dropdown.

**Expected behavior**
Drop down should show the selected item label in input field.

Angular version: 4X

PrimeNG version: 4.3.0

**Comment by cagataycivici** [comment]
Please use forum for help requests.
