### ISSUE TITLE
TimePicker (hh:mm:ss) in p-calendar is non editable. 

### ISSUE THREAD

**Issue by evilRash** [primefaces/primeng#6416]
**I'm submitting a ...**  
```
[ ] bug report 
[x] feature request 
[ ] support request 

Plunkr Case :
[https://github-eewso5-xiqsoh.stackblitz.io](https://github-eewso5-xiqsoh.stackblitz.io)

**Current behavior**
The time displayed in timepicker component is not editable .

**Expected behavior**
The user can only increase /decrease the hour,minute and seconds value in the timepicker component
using only the up/down arrows keys.This is really troublesome for the user. It would be great if
these  fields are editable.

**What is the motivation / use case for changing the behavior?**
Customer request.

**Angular version:** 4.0

**PrimeNG version:** PrimeNG 6.1.0

**Browser:** [ Chrome, Firefox, IE  , Safari  ]
 
**Language:** [TypeScript 3.0.1]

**Comment by mniederkofler** [comment]
Is this on the agenda somehow, as the restriction to mouse input renders the time selection variant of p-calendar practically useless. Users would need to click 30 times (or keep the button pressed for quite a while) to get from 15:00 to 15:30.

**Comment by mniederkofler** [comment]
Correction: component is not entirely useless as mentioned previously, as it is possible to enter the time directly into the linked input field. Nevertheless it is a bit more cumbersome for the user, as the user needs to pay attention to the format in the input field (e.g: separation characters)

**Comment by Chazing** [comment]
It really is not right UX, the time fields within the popup, should be open to typing.

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
