### ISSUE TITLE
p-fieldset collapsed status changes after closing overlay

### ISSUE THREAD

**Issue by ASK83** [primefaces/primeng#6418]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/github-eo7fcc

**Current behavior**
Above link is showing a gear icon which shows the overlay panel of collapsed fieldsets upon clicking. However, after click the collapsed status changes to true and all the fieldsets are showing which should not be happening. 

**Expected behavior**
The fieldset collapsed status should stay as we left the overlay panel and not try to open or close them without user interaction.

**Minimal reproduction of the problem with instructions**

To see the issue click on the gear to open the overlay and then click off the panel to close it, you can see that collapsed status is changing during the closing and remains that way the next time we open the overlay.

**What is the motivation / use case for changing the behavior?**
The fieldset status should not be depending on the parent container but interaction with the fieldset itself. 

**Please tell us about your environment:**
NA

* **Angular version:** 5.X
6.1.5

* **PrimeNG version:** 5.X
6.1.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
See 

https://github.com/primefaces/primeng/issues/6318
