### ISSUE TITLE
Strong Types for Turbo Table

### ISSUE THREAD

**Issue by MikeMatusz** [primefaces/primeng#6419]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Current behavior
A lot of the API for TurboTable uses "any" as the type for arguments, return values, and even column definitions.  Not all properties/methods are documented, and those that are could potentially become out of date.  Options could also change when updating to a newer version, and currently there would be no compile-time checking around this.

Expected behavior
Ideally, everything would have interfaces or other strong types, and "any" would be rarely aside from the row data itself, which should allow for anything.
Here are some specific cases I've encountered that have forced me to dig into source code, along with some low-hanging fruit encountered while looking through the source:
* Table.columns input property
** An interface that specified properties like header, field, exportable would be very helpful
* Table.filter method
* Table.contextMenu
** Presumable this has to be an instance of p-context-menu, but if you don't want to limit it to that, it definitely needs be something that implements a show() function.  Either should be typed as ContextMenu or some IContextMenu { show(event: Event): void; }
* LazyLoadMetadata (Table.onLazyLoad)
** Typing this event emitter would be provide intellisense when you go to handle the event. The createLazyLoadMetadata function uses a very specific contract.
* Table.exportCSV(options?: any)
** I think currently the only option is selectionOnly, but it would be nice to make that explicit.  And if you add additional options in the future, they'll become immediately apparent.
* Table.columnResizeMode is typed as string, but changing it to be 'fit' | 'expand' (or an enum) would better validate input and provide intellisense.
* Other event emitters that would benefit:
** onPage, sortFunction, onSort, selectionChanged (Array), onRowSelect, onRowUnselect, onContextMenuSelect, onHeaderCheckboxToggle, onFilter, onRowCollapse, onRowExpand, onColResize, onColReorder, onRowReorder, onEditInit, onEditComplete

What is the motivation / use case for changing the behavior?
Better IntelliSense while developing. Compile time error reporting for many possible mistakes. Assurance when you upgrade to a new version whether contracts have changed.  Potentially less defects created when changing the code.

PrimeNG version: 6.1.2 (still present in 14.2.1)

Language: TypeScript

**Comment by ciesielskico** [comment]
Can we get some update on this?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by MikeMatusz** [comment]
@mertsincan I don't appear to have permissions to re-open an issue closed by someone other than myself, but this issue has not been resolved and should be re-opened.  A couple properties have received better typings, and I'll update the initial comment to omit them, but for the most part `any` is still used in a lot of places where more specific types could easily be used to provide much more clarity and compile-time safety for developers.

**Comment by cetincakiroglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.

**Comment by kschlesselmann** [comment]
Looks like the table component still offers no specific types (e.g. `Column`). Is there any plan on adding them? After all this issue was originally opened 7 years ago.
