### ISSUE TITLE
[Bug] Button component error with [style] attribute

### ISSUE THREAD

**Issue by Onyphlax** [primefaces/primeng#6426]
Hi, 

**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When using the button component, an error is fired from platform-browser.js because the component is trying to apply the variable `style` on `[style]` instead of `[ngStyle]`.

I can use the directive instead of the component because it doesn't use `[style]` attribute but it's not a long term solution.
 
The issue doesn't happen in desktop browser.

**Expected behavior**

No error thrown.

**What is the motivation / use case for changing the behavior?**

On my case, i've a loader on my app until datas are loaded. The application creates the button component while datas are still loading and an error is fired at this moment which makes an infinite loader.

**Please tell us about your environment:**

* **Angular version:** 6.1.6

* **PrimeNG version:** 6.1.2

* **Browser:** [iOS 10.2/10.3 Safari]

 
* **Language:** [TypeScript 2.7.2]

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
