### ISSUE TITLE
Dropdown selects wrong item after update to beta.10

### ISSUE THREAD

**Issue by KonbOgonb** [primefaces/primeng#643]
Dropdown selects wrong item on bind from model. It selects first one. I have debuged code and seems that the issue is inside domHandler.equals(a,b). 
In my case it says that "1" is equal to "2".  The type of "value" property of items in options collection is integer. Also this worked fine in previous version (beta 9).

**Comment by cagataycivici** [comment]
Please provide sample code that replicates it.

**Comment by cagataycivici** [comment]
Maybe related to #651 ?

**Comment by KonbOgonb** [comment]
I don't think that it is directly related. To reproduce use [options] collection with numeric value, like 
        `this.cities.push({label:'New` York', value:1');
        this.cities.push({label:'Rome', value:2);
        this.cities.push({label:'London', value:3);`
And then let initially selected value be equal to 3 or 2. 
You are using domHandler to comare values, and look what it says when we are comparing two different numbers, like 1 and 5. http://bit.ly/2ai6y9n
