### ISSUE TITLE
DataScroller should be able to listen to scroll events of a specified element

### ISSUE THREAD

**Issue by gubo** [primefaces/primeng#6431]
DatScroller should have a property to specify an id of an element that it will listen to the scroll events for, and lazy-load based on that element's scroll ... because my content area scrolls in its own div, not the window

**Comment by gubo** [comment]
as a workaround i react to (scroll) on desired element and can call 
this.dataScroller.load();
where dataScroller is:
@ViewChild( DataScroller ) dataScroller: DataScroller;

**Comment by cagataycivici** [comment]
DataScroller is deprecated in favor of VirtualScroller.
