### ISSUE TITLE
p-calendar minDate not displaying year dropdown list

### ISSUE THREAD

**Issue by sarahm7** [primefaces/primeng#6433]
I'm encountering a bug when i implement the minDate in the calendar. The years are not displaying and when i click the left and right arrows the page reloads

![image](https://user-images.githubusercontent.com/27810542/44906448-7ca0db00-ad47-11e8-9f7f-9848165234c6.png)

`<p-calendar #calendar class="w-100" *ngIf="value" [inline]="isInline" [monthNavigator]="true" [showIcon]="true" [yearNavigator]="true"
    yearRange="2000:2050" (ngModelChange)="onChange($event)" [minDate]="minDate" [maxDate]="maxDate" name="value"
    [(ngModel)]="value" selectionMode="single" readonlyInput="true"></p-calendar>`

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
