### ISSUE TITLE
InputSwitch not firing change detection on external value change with Push Strategy

### ISSUE THREAD

**Issue by meeroslav** [primefaces/primeng#6434]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-kxjjv5?file=src%2Fapp%2Fapp.component.ts

**Current behavior**
The `writeValue` method does not fire change detection.
When using ChangeDetectionStrategy.OnPush value gets set later and change doesn't propagate.

**Expected behavior**
The component should work same with and without the OnPush change detection strategy.

**Minimal reproduction of the problem with instructions**
When you disable ChangeDetectionStrategy.OnPush it works, but with change detection on UI doesn't refresh, because `writeValue` doesn't trigger the change event.

**What is the motivation/use case for changing the behavior?**
InputSwitch used within components with OnPush strategy do not get value properly initialized. This is because the method `writeValue` is called after the component has been drawn and initialized, and change is never propagated.

**Please tell us about your environment:**
Linux Ubuntu, Yarn, Webstorm

* **Angular version:** 5.X
6.1.1

* **PrimeNG version:** 5.X
6.1.3

* **Browser:** all
 
* **Language:** all

**Comment by cagataycivici** [comment]
Here is an example that will work with upcoming 6.1.4

```html
<p-inputSwitch [(ngModel)]="checked"></p-inputSwitch>
```

```typescript
import {Component,ChangeDetectionStrategy,ChangeDetectorRef} from '@angular/core';

@Component({
    templateUrl: './inputswitchdemo.html',
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class InputSwitchDemo {

    checked: boolean = false;

     constructor(private cd: ChangeDetectorRef) {}

    ngOnInit() {
        setTimeout(() => {
            this.checked = true;
            this.cd.markForCheck();
        }, 2000);
    }
}
```
