### ISSUE TITLE
How to display options as group under labels using <p-autocomplete> "primeng": "6.1.2"

### ISSUE THREAD

**Issue by InvincibleViolet** [primefaces/primeng#6436]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Waiting Time: ~8 weeks.

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.X

* **PrimeNG version:** 5.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by InvincibleViolet** [comment]
Autocomplete shows a list of suggestions when a user search. I am trying to show the list of options as a grouped suggestions as shown below and the labels like Fruits/Vegetables should not be clickable or highlighted/selected by the user when user search for a word "Mi":

Label1 Mind Minimum Minute Label2 Mirror Mirrage

I am pushing all the items in list "allItems". html file looks like this:
<p-autoComplete  [suggestions]="allItems"
                    [ngModelOptions]="{standalone: true}"
                  [(ngModel)]="searchedItems"
                  (completeMethod)="onSearchFieldKeyUp($event)" 
                  [autoHighlight]="true">
    </p-autoComplete>

**Comment by lkhuoch** [comment]
Hi, PrimeNG Team,
I bought PrimeNG theme premium, I have some question, where can I place my question?
How many days PrimeNg Team reply?
Thanks,

**Comment by cagataycivici** [comment]
Please use the theme forums, usually between 3-5 days, our team responds;

https://forum.primefaces.org/viewforum.php?f=22

**Comment by vishalt5** [comment]
Hi, did u find any solution on this? I am also having this kind of requirement.

**Comment by vishalt5** [comment]
> Autocomplete shows a list of suggestions when a user search. I am trying to show the list of options as a grouped suggestions as shown below and the labels like Fruits/Vegetables should not be clickable or highlighted/selected by the user when user search for a word "Mi":
> 
> Label1 Mind Minimum Minute Label2 Mirror Mirrage
> 
> I am pushing all the items in list "allItems". html file looks like this:
> <p-autoComplete [suggestions]="allItems"
> [ngModelOptions]="{standalone: true}"
> [(ngModel)]="searchedItems"
> (completeMethod)="onSearchFieldKeyUp($event)"
> [autoHighlight]="true">

Did u find any answer on this? Please share any solution on this if u found one..
