### ISSUE TITLE
paginator dropdown is hidden by the data table layer

### ISSUE THREAD

**Issue by KennanDeng22** [primefaces/primeng#6439]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Waiting Time: ~8 weeks.

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**

The dropdown menu of paginator is hidden by the data table layer.
**Expected behavior**
It's better to provide the "dropdownAppendTo" property of paginator in datatable componnet, which can be defined by user.
If so, user can set it as "body" to solve this issue.

**Minimal reproduction of the problem with instructions**
datatable component with a paginator can reproduce this issue.

**What is the motivation / use case for changing the behavior?**
User can't see the dropdown menu, but a vertical scroll will appear, which is weird.

**Please tell us about your environment:**
Win 7. Chrome V67.

* **Angular version:** 5.X
V5.2.9

* **PrimeNG version:** 5.X
V5.2.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 67.0.3396.87 (Official Build) (32-bit)
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.6.2

* **Node (for AoT issues):** `node --version` =   8.9.4

**Comment by JacobSiegle** [comment]
There is no example of the issue given but I would assume you need to use appendTo and body. See the table docs.

**Comment by cagataycivici** [comment]
Or set overflow visible on td element.

**Comment by KennanDeng22** [comment]
@JacobSiegle There is no such a property provided by p-datatable, so that I can't use it.
