### ISSUE TITLE
Panelmenu - active state of submenu headers

### ISSUE THREAD

**Issue by Faigjaz** [primefaces/primeng#644]
Adding a ui-state-active to the submenu headers when active would be awesome, as for know you can't style submenu-headers depending on their state (like adding colored borders to show the user that this submenu is currently active). 
Or am I missing something?
And therefore callbacks on submenu-headers would be great , too

**Comment by supriya2992** [comment]
I am also facing the same issue.
@Faigjaz  Did you find any workaround for the same?
i tried to put this css in my file-
 .ui-menuitem:active {
	background:some-color;
}
i can see the color change when I click the link bt it goes away as soon as I release the mouse button.

**Comment by cagataycivici** [comment]
Shoud be fixed in recent releases, please drop a comment if issue still persists and we may reopen.

**Comment by Ketec** [comment]
Old bug, but apparently still there, submenu loses active state after click.

**Comment by micahcourey** [comment]
This issue is was not fixed.

**Comment by suraj021** [comment]
@JacobSiegle this issue is not resolved as of October, 2018. There is no way to highlight submenus in p-panelMenu. Please reply if I am missing something?

**Comment by suraj021** [comment]
@JacobSiegle wow! Thanks for the fast response. Are you the flash btw?

**Comment by suraj021** [comment]
@cagataycivici this issue is not fixed yet?

**Comment by JacobSiegle** [comment]
Seems like it needs an additional CSS class for controlling the submenu so you will have to wait for a maintainer since they are the only ones who can change the theme CSS. Otherwise it's just adding the missing active state onto the ngClass in the sub panel component.

**Comment by bogdanim36** [comment]
I have same issue with version 7.0.0-rc.2, and plus an wrong active ui state to other option:
<p-panelMenu [model]="items"></p-panelMenu>

and items:
export const MenuItems: MenuItem[] =
    [{
        label: "Administration",
        expanded: true,
        items: [
            {label: "Users", routerLink: "users" , icon:"pi pi-users"},
            {label: "Projects", routerLink: "projects", icon:"pi pi-folder"},
            {label: "Project Sections", icon: "pi pi-folder"}
        ]
    },
        {
            label: "Curent Project", expanded: true, items: [
                {
                    label: "Components", expanded: true, items: [
                        {label: "Plugins or add-ons"},
                        {label: "Routing"},
                        {label: "Tables"},
                        {label: "Pages"},
                        {label: "Functionalities"},
                    ]
                },
                {
                    label: "Resources", expanded: true, items: [
                        {label: "Documentation"},
                        {label: "Research"},
                        {label: "Nice to have"}
                    ]
                },
                {
                    label: "Tasks", expanded: true, items: [
                        {label: "Add/change components"},
                        {label: "Bugs"},
                        {label: "Issues"},
                    ]
                },
            ]
        }]
;
When Users is clicked, result three options with class ui-state-active: Adminstration, Users, and Current Project .Adminstration and Current Project are highlighted and  Users has class ui-state-active, but no css roules exists for a.ui-active-state.

**Comment by bogdanim36** [comment]
I found one mistake: all the parents which are expaned has ui-state-active, which is wrong: If I define one parent as expanded as default (like I did), will be shown as active, even when user doesn't click on this one:
in panelmenu.ts, template for p-panelMenu, 

```
 <div [ngClass]="{'ui-widget ui-panelmenu-header ui-state-default':true,'ui-corner-top':f,'ui-corner-bottom':l&&!item.expanded,
                    'ui-state-active':item.expanded,'ui-state-disabled':item.disabled}" [class]="item.styleClass" [ngStyle]="item.style">
```
Onather one is, like @JacobSiegle  said, missing css roules for a.ui-active-state.

**Comment by cagataycivici** [comment]
Tracked at #644

**Comment by buenos-dan** [comment]
this issue is not fixed yet?

**Comment by AhmedHashem94** [comment]
this issue is not fixed yet? date 2020 Nov

**Comment by farukgocgun** [comment]
is this issue still not solved?

**Comment by dharanhbk** [comment]
I have found a work around for making selected menu-item to be highlighted. Please let me know if it works for you.
Sample code:
 [{
        label: "Administration",
        expanded: true,
        items: [
            {label: "Users", routerLink: "users" , icon:"pi pi-users",command: (event) => { this.handleModuleClick(event.item)}
                     ,style:{}}
        ]
    }]

handleModuleClick(data){
    if(this.previoulsySelectedModule!=undefined)
      this.previoulsySelectedModule.style={};
    data.style=this.selectedModeuleStyle;
    this.previoulsySelectedModule=data;
}

**Comment by gianluca-moro** [comment]
We now have PrimeNG 21 and guess what. It's still not resolved.
