### ISSUE TITLE
rejectLabel doc not correct

### ISSUE THREAD

**Issue by mslourens** [primefaces/primeng#6440]
**I'm submitting a documentation error**
There is an error in the documentation on page [ConfirmDialog](https://www.primefaces.org/primeng/#/confirmdialog).  This property 

rejectLabel | boolean | true | Visibility of the reject button.

should be called `rejectVisible`, like `acceptVisible`

**Comment by cagataycivici** [comment]
Fixed a couple of days ago, thank you.
