### ISSUE TITLE
Dialog/OverlayPanel onHide triggered when destroying an hidden dialog

### ISSUE THREAD

**Issue by Silentscripter** [primefaces/primeng#6442]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://angular-3fwuct.stackblitz.io

**Current behavior**
The onHide event in p-dialog is always triggered when the p-dialog component is destroyed, whether the dialog is opened or not.

**Expected behavior**
The onHide event should trigger only when an open dialog is closed or destroyed. This was working normally in primeng v.5

**Minimal reproduction of the problem with instructions**
1. Add a p-dialog with an onHide callback associated.
2. Destroy the dialog container, whether by ngIf or by routing to another page
3. You should notice that the callback is executed even if the dialog has never been opened.
https://angular-3fwuct.stackblitz.io

**Please tell us about your environment:**
Windows 10 x64

* **Angular version:** 6.1.4

* **PrimeNG version:** 6.1.3

* **Browser:**all

**Comment by cagataycivici** [comment]
PR merged, thank you.
