### ISSUE TITLE
Turbotable not displaying any records after quick scroll

### ISSUE THREAD

**Issue by acabhishek9421** [primefaces/primeng#6444]
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap

**Current behavior**
I am using turbotable with lazy load for rendering the contents in table. Upon scrolling swiftly using the scroll-bar the table appears empty and the scroll bar goes back to its original position. By "scrolling swiftly" I mean that I drag the scroll bar quickly.

**Expected behavior**
 I expect the table to populate the corresponding data.

**Minimal reproduction of the problem with instructions**
I was able to reproduce this issue in Prime NG docs.
Please head to [PrimeNG table with Virtual Scroll - 250K Rows](https://www.primefaces.org/primeng/#/table/scroll)
and go the table with 250K rows and try the quick drag of the scroll-bar after some tries I managed to reproduce this issue.
![image](https://user-images.githubusercontent.com/33516710/44990800-d73c7000-afaf-11e8-8e65-5734799e075c.png)
It is little difficult to reproduce the same in PrimeNG docs but I can do it easily in my code.
Number of columns in my implementation is significantly large than the example

**What is the motivation / use case for changing the behavior?**
I believe solving this issue will improve turbotable's performance and surely it will help me solve an important bug at my workplace

**Please tell us about your environment:**

OS - Windows 8
IDE - VS Code
package manager _ npm
* **Angular version:** 5.

* **PrimeNG version:** 6.0.0

* **Browser:**  Chrome

 
* **Language:** all

* **Node (for AoT issues):** `node --version` =   8.2.1

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
