### ISSUE TITLE
Ratings - Show half units instead of integer

### ISSUE THREAD

**Issue by rafa-suagu** [primefaces/primeng#6445]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Rating component can only show integer units.

**Expected behavior**
Show half units.

**What is the motivation / use case for changing the behavior?**
This component can be used to show ratings and the ratings normally are allowed to get a half number.

**Comment by rafa-as** [comment]
@cagataycivici Would you accept a PR for this feature?

**Comment by JacobSiegle** [comment]
Useful ref - https://stackblitz.com/angular/nnjppodbojn?file=app%2Frating-decimal.ts

**Comment by rafa-as** [comment]
Thank you @JacobSiegle

**Comment by rafa-as** [comment]
@cagataycivici some news?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by rafa-as** [comment]
@mertsincan I can't reopen the issue and we're continuing with no option to display half units (or a concrete value)

**Comment by cetincakiroglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
