### ISSUE TITLE
Using pKeyFilter with pAutocomplete

### ISSUE THREAD

**Issue by Ludevik** [primefaces/primeng#6447]
**I'm submitting a ...**
```
[ ] bug report
[x ] feature request
[ ] support request
```
**Current behavior**
Autocomplete component currently doesn't expose native input and therefore there is no possibility to use `pKeyFilter` directive together with autocomplete.

**Expected behavior**
There should be a way how to compose other directives with components. Other frameworks usually expect the input as a content, so they are available for the clients (to add handlers, etc.). Something like:

```
<p-autoComplete>
    <input pKeyFilter>
</p-autoComplete>
```

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
Composition of different features.

* **Angular version:** 
6.1.1

* **PrimeNG version:**
6.1.0

* **Browser:**
all
 
* **Language:**
all

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by Ludevik** [comment]
@mertsincan there doesn't seem to be any change in latest version regarding this feature request.
i am not able to reopen this issue.

**Comment by cetincakiroglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.
