### ISSUE TITLE
datatable grouping with sortable headers not working

### ISSUE THREAD

**Issue by ASK83** [primefaces/primeng#645]
Hi all,

Thanks a lot for your great library, it's been fun playing with it. 
I have an issue with sorting a table that has groupings, I am not sure if I am using the component incorrectly or it is an issue. 
I have a table with the following format which is needed to be also sortable. 
![image](https://cloud.githubusercontent.com/assets/17345249/17059819/9b3a14ba-4fec-11e6-9d56-6a17de9c7664.png)
 
I have created the table by following code:

     `<p-dataTable [value]="bulkData" [sortable]="true" [headerRows]="headerRows" selectionMode="single" [(selection)]="selectedInd" (onRowSelect)="onRowSelect($event)" (onRowUnselect)="onRowUnselect($event)">
        <p-column *ngFor="let col of bulkCols" [field]="col" [header]="col" [sortable]="true" >         
        </p-column>
    </p-dataTable>`

If I don't have the groupings with setting the headerRows the columns will be sortable and everything works as needed. But if I add the header rows as bellow only the sortable icons will show but sort will not functioning.
 `this.headerRows.push({
                    columns: [
                        { header: 'Identification', colspan: 2 },
                        { header: 'Test Details', colspan: 3 }
                    ]
                },
                    {
                        columns: [
                            { header: this.bulkCols[0], colspan: 1, sortable: true },
                            { header: this.bulkCols[1], colspan: 1, sortable: true },
                            { header: this.bulkCols[2], colspan: 1, sortable: true },
                            { header: this.bulkCols[3], colspan: 1, sortable: true },
                            { header: this.bulkCols[4], colspan: 1, sortable: true }
                        ]
                    }
                );`

I don't know if this is the intended way to make a grouped table sortable, but I couldn't find anything online. Please guide me if I am using the library incorrectly and how to achieve this. 

Thanks for the great work!
Keep up the good work!
PS: I am using Angular2 RC4 and primeng 1.0.0-beta.10.

**Comment by ASK83** [comment]
I figured the problem when grouping the field name must be provided to the headersRows array.

**Comment by kutas04** [comment]
How you added the values to table? I used you example to group the table headers with headerRows, but after this changes I can't  add the values to the table. I adding the values as before as a list of object. 

`[ 
      {Date : '09/28/2016', Link : 'www.google.com',  Other : 'other'}         
      ]; `
I need to change something to make the values visible?

**Comment by ASK83** [comment]
My sample code here is using the old version of Primeng and the new one uses templates for column headers. 
Here is an example using the new one:
`<p-dataTable [value]="tableData" sortMode="single" >
		<header style="color: blue"> {{description}} </header>
		<p-headerColumnGroup>
			<p-row *ngFor="let headerRow of tableHeaders">
				<p-column *ngFor="let col of headerRow" [header]="col['text']" [colspan]="col['colspan']" [rowspan]="col['rowspan']" [sortable]="col['is_sortable'] == 1 ? true : false">
				</p-column>
			</p-row>
		</p-headerColumnGroup>

		<p-column *ngFor="let col of tableCols" [field]="col" >
		</p-column>
	</p-dataTable>`

Hope this helps and primeng website also has an example.

**Comment by kutas04** [comment]
For me is ok the old version because right now I'm using  primeng 1.0.0-beta.3. The headers are grouped correctly, but I have some problem with loading the datas in the table.
