### ISSUE TITLE
Week picker for p-calendar

### ISSUE THREAD

**Issue by kishor-p** [primefaces/primeng#6460]
**I'm submitting a ...**  
```
[x] feature request 
```

It would be good if `p-calendar` has option to pick WEEKS instead of dates.
In some scenarios we should be able to build `p-calendar` which just returns YEAR and WEEK.

Please add this to Feature Request if its not already been part of Roadmap

**Comment by dzagaduroska** [comment]
Any updates on this enhancement?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
