### ISSUE TITLE
Bug in date equality causes wrong initialization of dropdown with date value

### ISSUE THREAD

**Issue by cedricboidin** [primefaces/primeng#6469]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-dropdown-pvgyuu?file=app%2Fapp.component.html

**Current behavior**
I create a dropdown in which options values are dates. The associated formControl was set an initial value : jan 1 2003. However, when the dropdown is first displayed, it shows jan 1 2001.

**Expected behavior**
The dropdown should show the label corresponding to the formControl value, jan 1 2003.

**Minimal reproduction of the problem with instructions**
Start the stackblitz

**What is the motivation / use case for changing the behavior?**
This behavior is due to a bug in date equality in ObjectUtils.ts

**Please tell us about your environment:**
standard

* **Angular version:** 6.1.7

* **PrimeNG version:** 6.1.3

* **Browser:** all 
 
* **Language:** all

**Comment by cagataycivici** [comment]
PR merged, thank you.
