### ISSUE TITLE
p-dialog does not responsive in PrimeNG 6.1.3

### ISSUE THREAD

**Issue by lkhuoch** [primefaces/primeng#6479]
Hi, I have a problem with p-dialog does not response in PrimeNG 6.1.3.
Anyone can help me, please.
Thanks,

**Comment by cagataycivici** [comment]
Unable to replicate, please provide a stackblitz template demonstrating your issue.

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
