### ISSUE TITLE
No Background-Color with Messages

### ISSUE THREAD

**Issue by bbuehrer** [primefaces/primeng#6487]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**Current behavior**
The background-color  of a p-message with

severity="error" text="hello"

works only with the "nova-..."-theme, but not with the "south-street"- or the "omega"-theme.
With version < 6 it works perfect.

* **PrimeNG version:** 6.1.3

**Comment by cagataycivici** [comment]
You're using deprecated themes, please use an up-to-date theme instead. Older themes are not maintained anymore so this is expected.

**Comment by bbuehrer** [comment]
And now we tell our customers that the surface will look very different in the future, because the "south-street-theme" no longer exists ???
