### ISSUE TITLE
Spinner down/up buttons work incorrect when model value is string

### ISSUE THREAD

**Issue by dkrysiak** [primefaces/primeng#6490]
I'm submitting a bug report applying to PrimeNG Spinner component.

The Spinner works incorrectly when the model value bound (ngModel) is a **string** containing **correct number** value.

**Plunkr Example**
https://stackblitz.com/edit/github-utc5ey-zjjcot

The example contains two Spinner components. The first is bound to a number type variable, the second has a string value. Both contain zero as a start value.

When you use down/up buttons on the numeric spinner, everything works correctly. When you do the same on the spinner with the string value, weird things happen.

**Steps to reproduce the bug**
Use the attached Plunkr example.
1. Click the up button on the „Spinner on string”
2. Click the the down button on the „Spinner on string”
3. Click the the down button on the „Spinner on string”

**Current behavior**
1. After the first step – the value of the „Spinner on string” is „01”.
2. After the second step – the value of the „Spinner on string” is „01-1”.
3. After the 3rd step – the value of the „Spinner on string” is „01-1-1”.

**Expected behavior**
1. After the first step – the value of the „Spinner on string” is „1”.
2. After the second step – the value of the „Spinner on string” is „0” again.
3. After the 3rd step – the value of the „Spinner on string” is „-1”.

**What is the motivation / use case for changing the behavior?**
This is not a rare situation where the numeric value returned from the server is a string value actually. This is hard to identify as an error and an unexpected behaviour of the Spinner component.

**Environment:**
* **Angular version:** 5.0, 6.1.2
* **PrimeNG version:** 6.1.0
* **Browser:** Google Chrome 69, Mozilla Firefox 62

**Additional information:**
I'm not sure if it's a bug in component or incorrect usage. If it's expected behaviour and the Spinner value should always be of number type, please close this error and write this as it's stated clearly nowhere now. This will be the perfect reference place then :) Maybe spinner documentation should be enhanced with some warning/note.

**Comment by cagataycivici** [comment]
Modal value should be a number.
