### ISSUE TITLE
Calendar minDate, dont show previous month button and past months in select

### ISSUE THREAD

**Issue by frankpaap** [primefaces/primeng#6492]
[x] feature request 

Hi people,

I have a question about the minDate attribute of the calendar module.
I dont want to navigate in to the past with the month navigator and button previous, when those dates are disabled.
So now it's the month september 2018 than you can't click the previous month button and cant click in the select list january till august 2018.
Or is it possible to create a custom Navigator or is there any example of this?
If I'm not clear enough please ask me.

Kind regards,

Frank

**Comment by cagataycivici** [comment]
Please use forum for questions and help requests.
