### ISSUE TITLE
p-dialog is not hiding at all

### ISSUE THREAD

**Issue by krizic** [primefaces/primeng#6493]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Waiting Time: ~8 weeks.

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
p-dialog set to:

    [dismissableMask]="true"
    [modal]="true"
    [appendTo]="'body'"
    [styleClass]="'modal-dialog'"
    [draggable]="true"
    [closeOnEscape]="true"
    [visible]="isCustomerDialogShown"

Does not hide in no circumstances!

**Expected behavior**
Clicking the X button or overly should hide(close) modal 

**Minimal reproduction of the problem with instructions**

angular 6.1.7
primeng 6.1.3

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.X

* **PrimeNG version:** 5.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by jwelker110** [comment]
Does it close when you change `[visible]="isCustomerDialogShown"` to two-way binding with [banana-box syntax](https://angular.io/api/forms/NgModel#description) - `[(visible)]="isCustomerDialogShown"`?

Unless you are changing that value yourself somewhere, you should use two way binding to ensure the value is updated when the dialog is supposed to close, else it will remain open.

**Comment by cagataycivici** [comment]
Unable to replicate, please create a new issue ticket with a stackblitz template demonstrating the issue so that we can provide better assistance.
