### ISSUE TITLE
Clear icon for Table filter columns.

### ISSUE THREAD

**Issue by nsksaisaravana** [primefaces/primeng#6494]
Kindly provide a clear icon for Table filter columns text box, clear icon are available in the dropdown but it doesn't work. Once we click the clear icon, it should clear the textbox text and clear the filter in the table's json object.

![image](https://user-images.githubusercontent.com/17681573/45464054-23c34080-b752-11e8-9dae-d5a2ad059ea7.png)

**Comment by cagataycivici** [comment]
Filter elements are defined on your side so it would be better to implement this on your side as well.
