### ISSUE TITLE
Rewrite Spinner

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#6496]
Current implementation is not aligned with PrimeFaces and PrimeReact, align the component behavior with the other two which uses blur event to parse the value from string to a number, current spinner does on it on keyup which causes various issues like 5490.

**Comment by dkrysiak** [comment]
Hmmm. This change is backward incompatible as it removes thousandSeparator and decimalSeparator which were actually the only features why I have used this component.

Also, documentation hasn't been changed to reflect these changes – it still contains references to thousandSeparator and decimalSeparator properties, without any note about them being not supported
https://www.primefaces.org/primeng/#/spinner

Do not like it :(
