### ISSUE TITLE
Calendar button goes out of bounds in Nova

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#6498]
In fluid mode, calendar button goes out of the bounds of the calendar element.

**Comment by digeomel** [comment]
I can confirm. I will have to disable the icon until this is fixed.

![2018-09-14 10_56_04-devtools - localhost_4200_agora-search_advanced name greece 20last 20year](https://user-images.githubusercontent.com/3295889/45540627-33ec2600-b80d-11e8-8d94-ce0f2d630103.png)

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/commit/d80364885deaec392e40c3d76fcbc7682c81a934
