### ISSUE TITLE
Error on executing "npm install" just after download

### ISSUE THREAD

**Issue by pescamillam** [primefaces/primeng#65]
Executing "npm install" just after cloning the repo gives:

➜  primeng git:(master) npm install
npm WARN package.json primeng@v0.5.0-SNAPSHOT No repository field.

> primeng@0.5.0-SNAPSHOT postinstall /home/pescamillam/git/primeng
> npm run typings install

> primeng@0.5.0-SNAPSHOT prepublish /home/pescamillam/git/primeng
> tsc

components/accordion/accordion.ts(38,9): error TS2304: Cannot find name 'jQuery'.
components/accordion/accordion.ts(58,17): error TS2304: Cannot find name 'jQuery'.
components/accordion/accordion.ts(64,9): error TS2304: Cannot find name 'jQuery'.
components/breadcrumb/breadcrumb.ts(26,28): error TS2304: Cannot find name 'jQuery'.
components/button/button.ts(21,9): error TS2304: Cannot find name 'jQuery'.
components/button/button.ts(31,17): error TS2304: Cannot find name 'jQuery'.
components/button/button.ts(37,9): error TS2304: Cannot find name 'jQuery'.
components/carousel/carousel.ts(48,32): error TS2304: Cannot find name 'jQuery'.
components/chart/barchart/barchart.ts(83,21): error TS2304: Cannot find name 'LinearChartData'.
components/chart/barchart/barchart.ts(168,30): error TS2304: Cannot find name 'Chart'.
components/chart/doughnutchart/doughnutchart.ts(81,21): error TS2304: Cannot find name 'CircularChartData'.
components/chart/doughnutchart/doughnutchart.ts(154,30): error TS2304: Cannot find name 'Chart'.
components/chart/linechart/linechart.ts(85,21): error TS2304: Cannot find name 'LinearChartData'.
components/chart/linechart/linechart.ts(178,30): error TS2304: Cannot find name 'Chart'.
components/chart/piechart/piechart.ts(81,21): error TS2304: Cannot find name 'CircularChartData'.
components/chart/piechart/piechart.ts(154,30): error TS2304: Cannot find name 'Chart'.
components/chart/polarareachart/polarareachart.ts(79,21): error TS2304: Cannot find name 'CircularChartData'.
components/chart/polarareachart/polarareachart.ts(162,30): error TS2304: Cannot find name 'Chart'.
components/chart/radarchart/radarchart.ts(81,21): error TS2304: Cannot find name 'LinearChartData'.
components/chart/radarchart/radarchart.ts(180,30): error TS2304: Cannot find name 'Chart'.
components/datatable/datatable.ts(510,9): error TS2304: Cannot find name 'jQuery'.
components/datatable/datatable.ts(519,9): error TS2304: Cannot find name 'jQuery'.
components/datatable/datatable.ts(536,9): error TS2304: Cannot find name 'jQuery'.
components/datatable/datatable.ts(572,13): error TS2304: Cannot find name 'jQuery'.
components/dialog/dialog.ts(87,9): error TS2304: Cannot find name 'jQuery'.
components/dialog/dialog.ts(129,17): error TS2304: Cannot find name 'jQuery'.
components/dialog/dialog.ts(135,9): error TS2304: Cannot find name 'jQuery'.
components/fieldset/fieldset.ts(35,9): error TS2304: Cannot find name 'jQuery'.
components/fieldset/fieldset.ts(53,17): error TS2304: Cannot find name 'jQuery'.
components/fieldset/fieldset.ts(59,9): error TS2304: Cannot find name 'jQuery'.
components/galleria/galleria.ts(42,9): error TS2304: Cannot find name 'jQuery'.
components/galleria/galleria.ts(61,17): error TS2304: Cannot find name 'jQuery'.
components/galleria/galleria.ts(67,9): error TS2304: Cannot find name 'jQuery'.
components/growl/growl.ts(23,9): error TS2304: Cannot find name 'jQuery'.
components/growl/growl.ts(35,17): error TS2304: Cannot find name 'jQuery'.
components/growl/growl.ts(41,9): error TS2304: Cannot find name 'jQuery'.
components/inputswitch/inputswitch.ts(44,39): error TS2304: Cannot find name 'jQuery'.
components/inputtext/inputtext.ts(17,9): error TS2304: Cannot find name 'jQuery'.
components/inputtext/inputtext.ts(26,17): error TS2304: Cannot find name 'jQuery'.
components/inputtext/inputtext.ts(32,9): error TS2304: Cannot find name 'jQuery'.
components/inputtextarea/inputtextarea.ts(19,9): error TS2304: Cannot find name 'jQuery'.
components/inputtextarea/inputtextarea.ts(28,17): error TS2304: Cannot find name 'jQuery'.
components/inputtextarea/inputtextarea.ts(34,9): error TS2304: Cannot find name 'jQuery'.
components/lightbox/lightbox.ts(20,9): error TS2304: Cannot find name 'jQuery'.
components/lightbox/lightbox.ts(27,17): error TS2304: Cannot find name 'jQuery'.
components/lightbox/lightbox.ts(33,9): error TS2304: Cannot find name 'jQuery'.
components/listbox/listbox.ts(52,9): error TS2304: Cannot find name 'jQuery'.
components/listbox/listbox.ts(86,17): error TS2304: Cannot find name 'jQuery'.
components/listbox/listbox.ts(92,9): error TS2304: Cannot find name 'jQuery'.
components/megamenu/megamenu.ts(32,28): error TS2304: Cannot find name 'jQuery'.
components/menu/menu.ts(36,28): error TS2304: Cannot find name 'jQuery'.
components/menu/menu.ts(40,37): error TS2304: Cannot find name 'jQuery'.
components/menubar/menubar.ts(28,28): error TS2304: Cannot find name 'jQuery'.
components/panel/panel.ts(53,9): error TS2304: Cannot find name 'jQuery'.
components/panel/panel.ts(75,17): error TS2304: Cannot find name 'jQuery'.
components/panel/panel.ts(81,9): error TS2304: Cannot find name 'jQuery'.
components/panelmenu/panelmenu.ts(26,28): error TS2304: Cannot find name 'jQuery'.
components/password/password.ts(27,9): error TS2304: Cannot find name 'jQuery'.
components/password/password.ts(40,17): error TS2304: Cannot find name 'jQuery'.
components/password/password.ts(46,9): error TS2304: Cannot find name 'jQuery'.
components/rating/rating.ts(34,9): error TS2304: Cannot find name 'jQuery'.
components/rating/rating.ts(61,17): error TS2304: Cannot find name 'jQuery'.
components/rating/rating.ts(67,9): error TS2304: Cannot find name 'jQuery'.
components/selectbutton/selectbutton.ts(37,9): error TS2304: Cannot find name 'jQuery'.
components/selectbutton/selectbutton.ts(68,17): error TS2304: Cannot find name 'jQuery'.
components/selectbutton/selectbutton.ts(74,9): error TS2304: Cannot find name 'jQuery'.
components/slidemenu/slidemenu.ts(45,28): error TS2304: Cannot find name 'jQuery'.
components/slidemenu/slidemenu.ts(49,37): error TS2304: Cannot find name 'jQuery'.
components/slider/slider.ts(2,25): error TS2503: Cannot find namespace 'JQueryUI'.
components/slider/slider.ts(49,9): error TS2304: Cannot find name 'jQuery'.
components/slider/slider.ts(83,17): error TS2304: Cannot find name 'jQuery'.
components/slider/slider.ts(89,9): error TS2304: Cannot find name 'jQuery'.
components/spinner/spinner.ts(27,9): error TS2304: Cannot find name 'jQuery'.
components/spinner/spinner.ts(40,16): error TS2304: Cannot find name 'jQuery'.
components/spinner/spinner.ts(46,9): error TS2304: Cannot find name 'jQuery'.
components/tabview/tabview.ts(51,9): error TS2304: Cannot find name 'jQuery'.
components/tabview/tabview.ts(76,17): error TS2304: Cannot find name 'jQuery'.
components/tabview/tabview.ts(82,9): error TS2304: Cannot find name 'jQuery'.
components/tieredmenu/tieredmenu.ts(38,28): error TS2304: Cannot find name 'jQuery'.
components/tieredmenu/tieredmenu.ts(42,37): error TS2304: Cannot find name 'jQuery'.
components/togglebutton/togglebutton.ts(38,9): error TS2304: Cannot find name 'jQuery'.
components/togglebutton/togglebutton.ts(66,17): error TS2304: Cannot find name 'jQuery'.
components/togglebutton/togglebutton.ts(72,9): error TS2304: Cannot find name 'jQuery'.
node_modules/angular2/platform/browser.d.ts(77,90): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/application_ref.d.ts(83,60): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/application_ref.d.ts(83,146): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/application_ref.d.ts(96,51): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/application_ref.d.ts(96,147): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/application_ref.d.ts(133,90): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/application_ref.d.ts(171,81): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/change_detection/parser/locals.d.ts(3,14): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/core/change_detection/parser/locals.d.ts(4,42): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/core/debug/debug_node.d.ts(14,13): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/core/debug/debug_node.d.ts(24,17): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/core/debug/debug_node.d.ts(25,17): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/core/di/provider.d.ts(436,103): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/core/di/provider.d.ts(436,135): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/core/linker/compiler.d.ts(12,50): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/linker/compiler.d.ts(16,41): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/linker/dynamic_component_loader.d.ts(108,136): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/linker/dynamic_component_loader.d.ts(156,150): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/linker/dynamic_component_loader.d.ts(197,128): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/linker/dynamic_component_loader.d.ts(203,127): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/linker/dynamic_component_loader.d.ts(204,141): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/linker/dynamic_component_loader.d.ts(205,119): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/core/render/api.d.ts(13,13): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/core/render/api.d.ts(14,84): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/async.d.ts(27,33): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/async.d.ts(28,45): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/collection.d.ts(1,25): error TS2304: Cannot find name 'MapConstructor'.
node_modules/angular2/src/facade/collection.d.ts(2,25): error TS2304: Cannot find name 'SetConstructor'.
node_modules/angular2/src/facade/collection.d.ts(4,27): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(4,39): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(7,9): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(8,30): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(11,43): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(12,27): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(14,23): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(15,25): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(95,41): error TS2304: Cannot find name 'Set'.
node_modules/angular2/src/facade/collection.d.ts(96,22): error TS2304: Cannot find name 'Set'.
node_modules/angular2/src/facade/collection.d.ts(97,25): error TS2304: Cannot find name 'Set'.
node_modules/angular2/src/facade/lang.d.ts(13,17): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/lang.d.ts(14,17): error TS2304: Cannot find name 'Set'.
node_modules/angular2/src/facade/lang.d.ts(78,59): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/promise.d.ts(2,14): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(7,32): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(8,38): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(9,35): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(9,93): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(10,34): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(11,32): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(11,149): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(12,43): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/http/headers.d.ts(43,59): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/http/url_search_params.d.ts(11,16): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/platform/browser/browser_adapter.d.ts(75,33): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/platform/dom/dom_adapter.d.ts(85,42): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/router/instruction.d.ts(122,34): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/instruction.d.ts(146,25): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/instruction.d.ts(153,25): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/instruction.d.ts(163,34): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/instruction.d.ts(166,25): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/lifecycle_annotations.d.ts(29,100): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/route_registry.d.ts(52,66): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/router.d.ts(52,50): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/router.d.ts(58,46): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/router.d.ts(76,45): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/router.d.ts(89,34): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/router.d.ts(97,64): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/router.d.ts(102,85): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/router.d.ts(110,70): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/router.d.ts(118,43): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/router.d.ts(122,29): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/router.d.ts(128,19): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/router.d.ts(136,70): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/router_outlet.d.ts(25,54): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/router_outlet.d.ts(31,51): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/router_outlet.d.ts(36,56): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/router_outlet.d.ts(45,65): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/router/router_outlet.d.ts(56,60): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/CoreOperators.d.ts(35,67): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/CoreOperators.d.ts(50,66): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/CoreOperators.d.ts(89,67): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/CoreOperators.d.ts(94,38): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/CoreOperators.d.ts(94,50): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(46,62): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(47,42): error TS2304: Cannot find name 'Iterator'.
node_modules/rxjs/Observable.d.ts(103,74): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(103,84): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(143,66): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(158,65): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(201,66): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(206,38): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(206,50): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/observable/ForkJoinObservable.d.ts(6,50): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/observable/ForkJoinObservable.d.ts(7,58): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/observable/FromObservable.d.ts(7,38): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/observable/FromObservable.d.ts(7,51): error TS2304: Cannot find name 'Iterator'.
node_modules/rxjs/observable/PromiseObservable.d.ts(9,31): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/observable/PromiseObservable.d.ts(10,26): error TS2304: Cannot find name 'Promise'.
components/calendar/calendar.ts(2,21): error TS2503: Cannot find namespace 'JQueryUI'.
components/calendar/calendar.ts(74,13): error TS2304: Cannot find name 'jQuery'.
components/calendar/calendar.ts(105,17): error TS2304: Cannot find name 'jQuery'.
components/calendar/calendar.ts(111,9): error TS2304: Cannot find name 'jQuery'.
components/dropdown/dropdown.ts(67,30): error TS2304: Cannot find name 'jQuery'.
components/chart/barchart/barchart.ts(83,21): error TS4031: Public property 'value' of exported class has or is using private name 'LinearChartData'.
components/chart/doughnutchart/doughnutchart.ts(81,21): error TS4031: Public property 'value' of exported class has or is using private name 'CircularChartData'.
components/chart/linechart/linechart.ts(85,21): error TS4031: Public property 'value' of exported class has or is using private name 'LinearChartData'.
components/chart/piechart/piechart.ts(81,21): error TS4031: Public property 'value' of exported class has or is using private name 'CircularChartData'.
components/chart/polarareachart/polarareachart.ts(79,21): error TS4031: Public property 'value' of exported class has or is using private name 'CircularChartData'.
components/chart/radarchart/radarchart.ts(81,21): error TS4031: Public property 'value' of exported class has or is using private name 'LinearChartData'.
npm ERR! weird error 1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0

**Comment by cagataycivici** [comment]
Do you get typings folder created?

**Comment by psramkumar** [comment]
this worked for me without any issue: please retry

**Comment by pescamillam** [comment]
it seems to be working now thou now it doesn't work for me the "tsc" command...
