### ISSUE TITLE
unbale to import interface typescript with nested objects

### ISSUE THREAD

**Issue by PrajaktaMarde** [primefaces/primeng#6504]
Hi ,

I am using Prime NG Crud Table for my implementation. But i ma not able to create object as they have created for the car as my object has nested interaface.

export interface RowDetails {
  sourceInstrument: {[key : string]:SourceInstrument};
  sourcePercent: Number;
  destInstrument: {[key : string]:DestinationInstrument};
  destPercent: Number;
}

export interface SourceInstrument
{
   sourceInstrumentNumber: Number;
  sourceInstrumentName : String;
  sourceInstrumentValorCode : String;
  sourceInstrumentMancoNumber : Number;
  sourceInstrumentMancoName : String;
  sourceInstrumentDealingFrequency : String;

}

export interface DestinationInstrument
{
   destInstrumentNumber: Number;
  destInstrumentName : String;
  destInstrumentValorCode : String;
  destInstrumentMancoNumber : Number;
  destInstrumentMancoName : String;
  destInstrumentDealingFrequency : String

}

Getting error in the component where I am trying to export the object 

 RowObject: RowDetails = { sourceInstrument, sourcePercent, destInstrument, destPercent };
Cannot find name souceInstrument. and for all the members.

**Comment by cagataycivici** [comment]
Not related to PrimeNG.
