### ISSUE TITLE
Found the synthetic property @errorState. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule"

### ISSUE THREAD

**Issue by codehunter13** [primefaces/primeng#6505]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
adding 
`<p-message severity="error" text="Not a valid number" [@errorState]="form.dirty && !form.valid ? 'visible' : 'hidden'"></p-message>`

gives the error:
Found the synthetic property @errorState. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule"

I imported the BrowserAnimationsModule in my root app module:
`import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpClientModule } from '@angular/common/http';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { AppComponent } from './app.component';
import { NavMenuComponent } from './nav-menu/nav-menu.component';
import { HomeComponent } from './home/home.component';
import { CounterComponent } from './counter/counter.component';
import { FetchDataComponent } from './fetch-data/fetch-data.component';
import { AppRoutingModule } from './app-routing.module';
import { FwModule } from '../framework/fw.module';

@NgModule({
  declarations: [
    AppComponent,
    NavMenuComponent,
    HomeComponent,
    CounterComponent,
    FetchDataComponent,
  ],
  imports: [
    BrowserModule.withServerTransition({ appId: 'ng-cli-universal' }),
    HttpClientModule,
    FormsModule,
    BrowserAnimationsModule,//niet in shared zetten !
    AppRoutingModule,
    FwModule,
    FwModule.forRoot(),
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }`

**Expected behavior**
no errors :)

* **Angular version:** 5.X
* **PrimeNG version:** 5.X
`"dependencies": {
    "@angular/animations": "6.0.6",
    "@angular/common": "6.0.6",
    "@angular/compiler": "6.0.6",
    "@angular/core": "6.0.6",
    "@angular/forms": "6.0.6",
    "@angular/http": "6.0.6",
    "@angular/platform-browser": "6.0.6",
    "@angular/platform-browser-dynamic": "6.0.6",
    "@angular/platform-server": "6.0.6",
    "@angular/router": "6.0.6",
    "@nguniversal/module-map-ngfactory-loader": "6.0.0",
    "aspnet-prerendering": "^3.0.1",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "moment": "^2.22.2",
    "ngx-moment": "^3.0.1",
    "font-awesome": "^4.7.0",
    "primeicons": "^1.0.0-beta.10",
    "primeng": "^6.1.2",
    "rxjs": "^6.2.1",
    "zone.js": "^0.8.26"
  },`

**Comment by codehunter13** [comment]
Fixed. I had to add the errorstate trigger myself. 
Please provide us with adequate documentation. Check  https://www.primefaces.org/primeng/#/keyfilter:
no component attribute on class KeyFilterDemo

**Comment by vishalkrv** [comment]
Trigger sample taken from prime-ng repo
```
import { Component, OnInit } from '@angular/core';
import { trigger, state, style, transition, animate } from '@angular/animations';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss'],
  animations: [
    trigger('errorState', [
      state(
        'hidden',
        style({
          opacity: 0
        })
      ),
      state(
        'visible',
        style({
          opacity: 1
        })
      ),
      transition('visible => hidden', animate('400ms ease-in')),
      transition('hidden => visible', animate('400ms ease-out'))
    ])
  ]
})
export class LoginComponent implements OnInit {

  constructor() {
    console.log('login');
  }

  ngOnInit() {}
}

```
