### ISSUE TITLE
frozenColumns in turbo table not working

### ISSUE THREAD

**Issue by sunnyyadav100** [primefaces/primeng#6507]
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

[Stackblitz]

I have taken an example of 'Frozen Column' from PrimenNG website.

https://stackblitz.com/edit/github-pkeohg

**Current behavior**

Turbo table is not rendering.

**Expected behavior**

Turbot table should get rendered.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.X

6.1.3
* **PrimeNG version:** 5.X

6.1.0
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 ALL
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by sunnyyadav100** [comment]
Sorry, wrong issue.

**Comment by Melchipaul** [comment]
Hi @sunnyyadav100. Why do you think this is wrong issue? I have the same issue in Angular 8. I want many columns in frozenCols but it seems it takes only the first. Thank you.
