### ISSUE TITLE
Dialog inside another Dialog

### ISSUE THREAD

**Issue by Helayxa** [primefaces/primeng#6508]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/github-j1hpjw

**Current behavior**
When opening a Dialog with modal inside another Dialog with modal, the second Dialog is covered by its modal mask, and I can't do any action.

**Expected behavior**
When opening a Dialog inside a Dialog, the modal mask shouldn't block the whole application and the Dialog must be accessible.

**Comment by cagataycivici** [comment]
It is not a valid usage, please keep your dialogs separate or try to use appendTo="body".
