### ISSUE TITLE
p-multiSelect dropdown does not follow height of selected item header

### ISSUE THREAD

**Issue by laclac777** [primefaces/primeng#6511]
![multiselect1](https://user-images.githubusercontent.com/16359817/45669578-c6980800-bb20-11e8-90d0-0956915cc1f8.png)

![multiselect2](https://user-images.githubusercontent.com/16359817/45669586-cb5cbc00-bb20-11e8-9959-bfead3118c34.png)

**Current behavior**
Multiselect dropdown does not follow height of header

**Expected behavior**
By the change of header height its dropdown position should position to header bottom.

**Minimal reproduction of the problem with instructions**
https://www.primefaces.org/primeng/#/table/filter
Set the table size as small as attached pictures show. Select at least 3 items.

* **Angular version:** 6.X

* **PrimeNG version:** 6.1.3

* **Browser:** all

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
