### ISSUE TITLE
p-toast 'life' property not working

### ISSUE THREAD

**Issue by panikena** [primefaces/primeng#6513]
I'm submitting a 
[x ] bug report => Search github for a similar issue or PR before submitting

This is an example that reproduces the issue. Toast should stay for 30 seconds
https://github-rsbcv3.stackblitz.io/

**Current behavior**
Toast disappears after 3 seconds no matter what value of 'life' property is.
For IE, it tries to disappear after 3 seconds, but returns back and stays forever.

**Expected behavior**
Toast should stay for a specified amount of time

**Minimal reproduction of the problem with instructions**
Add a < p-toast life="XXX" >< /p-toast > component to the page and push some messages

**Please tell us about your environment:**
Windows 10 Pro, VS Code 1.25.1

* **Angular version:** 5.2.9

* **PrimeNG version:** 6.1.4

* **Browser:**
Probably all. Following browsers are confirmed to have this issue:
Firefox 61.0.2
Chrome 68.0.3440
IE 11.228.17134.0
Mobile Firefox 57.0.1 (on Android)
 
* **Language:** 
Typescript 2.9.2

**Comment by yigitfindikli** [comment]
Hi,
Its works fine. Can i see your code ?

Example
`showSuccess() {
        this.messageService.add({severity:'success', summary: 'Success Message', detail:'Order submitted', life:30000});
    }`

**Comment by panikena** [comment]
Hello!
Thank you for the response. 

Yes, this works fine, I am aware of this option.

I had an impression that defining  `<p-toast life='30000'>` should work as well. I think it is more convenient to have this value defined in the tag rather than adding it every time you push a message to the messageService.
