### ISSUE TITLE
frozenColumns in turbotable are not scrollable. Selection and table footer issue.

### ISSUE THREAD

**Issue by sunnyyadav100** [primefaces/primeng#6517]
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

[Stackblitz]
https://github-pkeohg.stackblitz.io

**Current behavior**

If frozen columns reached its max width then overflowing columns are hidden. 
If table has checkbox for selection then frozen and dynamic columns both has checkboxes.
If table has footer then there is separate footer for frozen and dynamic table.

![image](https://user-images.githubusercontent.com/9139037/45755941-41eedc00-bc3d-11e8-8d78-b2f5489c7017.png)

**Expected behavior**

Frozen column reached its max width then it should be scrollable.
Checkboxes should appear only one table i.e. frozen table
Table footer can be common for both frozen and dynamic table.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.X

6.1.3

* **PrimeNG version:** 5.X

6.1.0
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 ALL
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by alaksej** [comment]
Here's the workaround I've come up with:
https://stackblitz.com/edit/primeng-frozen-columns-vertical-scroll

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
