### ISSUE TITLE
Display of selected value in p-autocomplete in Edge browser

### ISSUE THREAD

**Issue by HISeG-ME** [primefaces/primeng#6519]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
If a value has been selected from the p-autocomplete list and it has a length of characters the exceeds
the input length, the begin of value won´t be shown and it jumps to the end of the text. 

**Expected behavior**
The begin of the value should be shown after selecting if from the dropdown as all others browsers do.

**Minimal reproduction of the problem with instructions**
The issue is also available at the Primeng showcase:

1. open the site via the Edge browser: https://www.primefaces.org/primeng/#/autocomplete
2. Examine the "Advanced" example and open it in Edge Developer tools
3. Examine the ui-inputtext
4. at the styles of .ui-autocomplete .ui-autocomplete-input add width:4em;
5. choose Mercedes from the list
6. you´ll see that only the end of the word is displayed.

**What is the motivation / use case for changing the behavior?**
Improve Usability to enable Edge users to see the begin of the selected value.

**Please tell us about your environment:**
Windows

* **Angular version:** 5.X
1.6.0

* **PrimeNG version:** 5.X
5.2.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Edge
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
