### ISSUE TITLE
onHide event not triggered in version 6.1.4 for dialog and overlayPanel

### ISSUE THREAD

**Issue by stefalda** [primefaces/primeng#6520]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
Current behavior**
The onHide event is NOT triggered anymore even if the panel/dialog is visible

**Expected behavior**
The onHide event should be  triggered as before.

**Minimal reproduction of the problem with instructions**
This simple code can be used tor reproduce the problem:

```
<p-overlayPanel [dismissable]="true" [showCloseIcon]="true" #op [style]="{'width':'320px'}" appendTo="body" (onHide)="hideTest()">
    <h1>CIAO</h1>
</p-overlayPanel>

<button type="text" pButton label="Basic" (click)="op.toggle($event)"></button>
```

and, of course, a hideTest() method should be defined in the Component.

Now click on the button and then close the OveralyPanel... the hideTest method is not called because the onHide event is not emitted.

**Comment by BearandYoon** [comment]
@stefalda 
I need to know the event when overlay has been hidden but p-overlayPanel's onHide is not working.
Do you have any solution?

**Comment by stefalda** [comment]
@BearandYoon stick with version 6.1.3 until the fix is released... I've forced it in the package.json
