### ISSUE TITLE
Calendar - Unexpected behaviour when date format contains whitespace characters and showTime is enabled

### ISSUE THREAD

**Issue by anett85** [primefaces/primeng#6521]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When the date format contains whitespace characters, changing the text in the input clears the value of the input. This happens only when "showTime" is true.

**Expected behavior**
The text won't be cleared if the date format contains whitespace characters.

**Minimal reproduction of the problem with instructions**
*STEPS TO REPRODUCE*
Pre-action: Set this format for p-calendar: M dd, y (Sep 19, 18) .
1. Select a date from the date picker.
2. Click into the input, and modify the day to a valid value (e.g.: Sep 19 to Sep 18) and close the date picker.
**Actual result**: The input is cleared.

I found the reason in your source code in calendar.ts#parseDateTime: 
This is the point where you should modify the code:
**let parts: string[] = text.split(' ');**
In my case, parseDate method gets only 'Sep' in the first parameter (this.parseDate(parts[0], this.dateFormat)).

* **Angular version:** 6.0.7

* **PrimeNG version:** 6.0.0

**Comment by vinlos** [comment]
I provided the fix in the attached [pull request](https://github.com/primefaces/primeng/pull/7788) and I was able to reproduce it on [stackblitz](https://stackblitz.com/edit/angular-primeng-calendar-spaces-date-format?file=src%2Fapp%2Fapp.component.html)
