### ISSUE TITLE
Chart X-Axis Scrollable

### ISSUE THREAD

**Issue by caglarturkurka** [primefaces/primeng#6522]
I want to learn that how can I add scrolling feature to primeng charts. Also I attached an image about this problem.
![screen shot 2018-09-19 at 15 21 53](https://user-images.githubusercontent.com/6197613/45752946-c5013980-bc1f-11e8-98cf-a7d7cbe288bd.png)

**Comment by JacobSiegle** [comment]
PrimeNG is only a thin wrapper around ChartJS. You can find many issues how to implement this by searching online for ChartJS.

This is a question not an issue and should be closed. Post questions on the primeng forum.
