### ISSUE TITLE
"ui-button-secondary" button not "visible" as a button when using inside a toolbar

### ISSUE THREAD

**Issue by AlainD-** [primefaces/primeng#6525]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://github-ctdghn.stackblitz.io

**Current behavior**
Since the default toolbar background and the ui-button-secondary button share (almost) the same background, it is not easy to realise that the button is a button/that there is a button there.

**Expected behavior**
I don't know what's best:
- or add a different background for any one (and only one) of the 2
- or add a border by default to the button
- or add a suggestion in the documentation of the toolbar if there is a workaround (like the usage of ui-button-raised in combination of ui-button-default

**Minimal reproduction of the problem with instructions**
* Create a toolbar for instance, or any other component which has a grey background
* Add a .ui-button-secondary to that component

**What is the motivation / use case for changing the behavior?**
UX

![primefaces-primeng-issue-6525](https://user-images.githubusercontent.com/5165564/46315296-5c29a200-c5cd-11e8-974e-a3281c09f243.png)

* **PrimeNG version:** 6.1.4

* **Browser:** all

**Comment by AlainD-** [comment]
Added a snapshot to the description for a better understanding.

**Comment by cagataycivici** [comment]
This is by design and depends on the theme (nova), you may use custom css to change the default behavior.
