### ISSUE TITLE
Datatable with expandable rows and template columns uses wrong template

### ISSUE THREAD

**Issue by kurigohan** [primefaces/primeng#653]
The datatable renders the wrong template when using templating for a column in addition to the expandable rows. Instead of adding the template for the expandable row to the table on row expansion, it adds the template for the column.

**Comment by cagataycivici** [comment]
This is a bug of Angular2;

https://github.com/angular/angular/issues/8292

Current workaround is moving expansion template before column templates, right after <p-datataTable tag.

```xml
<p-dataTable
   <template />
   <p-column><template />
```
