### ISSUE TITLE
dropdownIcon being overridden by Nova theme

### ISSUE THREAD

**Issue by bradyolson** [primefaces/primeng#6537]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**Current behavior**
MultiSelect `dropdownIcon` is overridden by theme CSS. The MultiSelect will always be  the `pi-caret-down` icon, regardless of `dropdownIcon` specification.

**Expected behavior**
`dropdownIcon` affects which icon is displayed for the MultiSelect dropdown

**Minimal reproduction of the problem with instructions**
This is a problem with at least the nova themes, via the selector 
`body .ui-multiselect .ui-multiselect-trigger .ui-multiselect-trigger-icon:before` [(here)](https://github.com/primefaces/primeng/blob/1a22735e844c494cbef33a55bd8088a1ddb561b7/src/assets/components/themes/nova-light/theme.css#L434)

**What is the motivation / use case for changing the behavior?**
Themes should be compatible with available options to customize components.

* **Angular version:** 6.1.0

* **PrimeNG version:** 6.1.4

* **Browser:** all
 
* **Language:** all

**Comment by yigitfindikli** [comment]
fixed in https://github.com/primefaces/primeng/issues/7168
