### ISSUE TITLE
support for filters in sortable column headers

### ISSUE THREAD

**Issue by bradyolson** [primefaces/primeng#6539]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
```

Looking for support for filters in header cells of sortable columns. #3694 was created and closed without real resolution. I've made a workaround https://stackblitz.com/edit/github-vktret, which is essentially the below code.
```
<p-multiSelect #multi [...] (click)="onMultiSelectClick($event, multi)"></p-multiSelect>
```
```
function onMultiSelectClick(event, multiSelect) {
  event.stopPropagation();
  multiSelect.selfClick = false;
}
```

**Current behavior**
Opening a multi select (or other input which can be used as a filter) activates the filter _and_ activates sort on the column.

**Expected behavior**
Opening the filter activates the filter and the sort is not affected.

**Minimal reproduction of the problem with instructions**
Use a `<p-multiSelect>` or similar in`<th>` with `pSortableColumn` set, inside `<ng-template pTemplate="header">`.

**What is the motivation / use case for changing the behavior?**
For simple filters, this visually cleans up the table (with the alternative being another header row with the filter beneath the column title).

**Please tell us about your environment:**
N/A

* **Angular version:** 6.1.0

* **PrimeNG version:** 6.1.4

* **Browser:** all

 
* **Language:** all

**Comment by cagataycivici** [comment]
Filter and Sortable columns cause problems like this so by design it is suggested to keep filters at a different row at headers.
