### ISSUE TITLE
Datatable column sorting does not work with global filter

### ISSUE THREAD

**Issue by kurigohan** [primefaces/primeng#654]
When a global filter used on the datatable, single column sorting stops working.

**Comment by Goldflow** [comment]
same issue here

**Comment by Shawson** [comment]
+1 with 1.0.0-beta.17

**Comment by mariahlynne** [comment]
Any chance we can get this fix included in RC5?

**Comment by anugoyal12** [comment]
Hello everyone,

any idea which release this fixed issue is available?
