### ISSUE TITLE
Schedule: Customisation on header options: prev, next, today (header buttons)

### ISSUE THREAD

**Issue by sudhirkumart** [primefaces/primeng#6547]
I am trying to use PRIMENG scheduler in Angular version 6.0.X and PRIMENG 6.0.1

The documentation in primeng schedule wasn't sufficient on header options.

Can someone throws some light on adding(execute) some operations, when I click prev, next, today or week in calendar.

https://www.primefaces.org/primeng/#/schedule

**Current behavior**
Not enough documentation on PRIMENG scheduler

**Expected behavior**
Documentation on header options

**Minimal reproduction of the problem with instructions**
Just bring up any primeng scheduler

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 6.0.2

* **PrimeNG version:** 6.0.1

* **Browser:** All
 
* **Language:** Typescript

**Comment by cagataycivici** [comment]
Please use forum for support requests.
