### ISSUE TITLE
primeng 6 compatibility with fullcalendar v3 (fullcalendar v4 alpha not ready!)

### ISSUE THREAD

**Issue by tencnivel** [primefaces/primeng#6548]
(https://github.com/primefaces/primeng/issues/6107) should not have been closed because as of today fullcalendar v4 (still in alpha) is not usable with primeng 6 because of this bug (https://github.com/fullcalendar/fullcalendar/issues/4221)

As soon as the window containing the calendar is scrolled, the time slots are shifted.

Here is a codepen to demonstrate the problem
(https://codepen.io/tencnivel/pen/EeJQXE)

How can we make primeng 6 work with fullcalendar v3?

**Comment by JacobSiegle** [comment]
The easiest way is to just copy the old version of schedule.ts that matches up with the V3 version and include/build it as your own component in your project.

**Comment by wkjesus** [comment]
Im still have the issue in console. Schedule.push../node_modules/primeng/components/schedule/schedule.js.Schedule.initialize, 
even with height assigned, any progress on this bug?

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
