### ISSUE TITLE
Context menu is not accessible in the treeview

### ISSUE THREAD

**Issue by srinivaskondisetty** [primefaces/primeng#6550]
Hi,

The context menu items inside the treeview is not accessible. Is this in your list?

**Comment by srinivaskondisetty** [comment]
And also the control types are improper as the narrator is not announcing the tree items properly

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
