### ISSUE TITLE
Property fields for accessibility are not defined properly in Time and Datepickers

### ISSUE THREAD

**Issue by srinivaskondisetty** [primefaces/primeng#6551]
Name property is defined as null in time and date pickers which causing narrator now announcing properly inside the time picker.

**Comment by srinivaskondisetty** [comment]
Also there is no options for pickers to close or toggle on key events

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
