### ISSUE TITLE
[Table][Bug] p-tableCheckbox doesn't stop the click event

### ISSUE THREAD

**Issue by Mysame** [primefaces/primeng#6552]
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

p-tableCheckbox doesn't stop the ClickEvent
A side effect of this is having a multiple selection table + p-tableCheckbox => Can't select a row using the checkbox. The checkbox selects the row, event propogates to row click, which in turn instantly deselects the row 

Example: https://stackblitz.com/edit/github-6hbnkl
Try selecting a row using the checkbox.
If you step through it, you can see it getting selected, and instantly deselected

**Expected behavior**
p-tableCheckbox stops the ClickEvent

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/github-6hbnkl

**Comment by cagataycivici** [comment]
This is by design, row select and checkbox select can't be used at the same time, it should either one of them. They implement different behaviors so should not be used together.
