### ISSUE TITLE
Table Paginator Out of Sync with Data on Navigate

### ISSUE THREAD

**Issue by ericrovtar** [primefaces/primeng#6553]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Waiting Time: ~8 weeks.

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
Currently, when you change pages on the Table, navigate away, then navigate back, the Paginator assumes you're back at Page 1.

We're manually tracking the Page number in our service, so the data returned from our API is for a different page. This causes the Paginator and the data to become out of sync.

There doesn't appear to be a way to set the current page on the Table of the Paginator.

**Expected behavior**
It'd be nice to have a property where we could tell the Table what the current Page is.

**Minimal reproduction of the problem with instructions**
Navigate to a different page of the Table. Navigate to a different page of the app. Click the back button.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 6.0.3

* **PrimeNG version:** 6.1.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by mscud** [comment]
You can use the first property?!?

**Comment by cagataycivici** [comment]
Try stateful feature so the pagination is saved/restored by the table, it would be much easier.
