### ISSUE TITLE
Selected date might differ depending on the time zone

### ISSUE THREAD

**Issue by huskerona** [primefaces/primeng#6554]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Waiting Time: ~8 weeks.

**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Technically I am not sure whether this would qualify as a bug or a feature request.
https://stackblitz.com/edit/typescript-uxmutj

**Current behavior**
When a date in the past is selected, p-calendar returns the date in the following format:
*Wed Sep 12 2018 00:00:00 GMT+0200 (Central European Summer Time)*
After calling `.toISOString()` the returned string is *2018-09-11T00:00:00*. The reason for this is that JavaScript `Date.parse()` takes time offset into account when generating the string representation of the date which might differ from the selection in the p-calendar component.

**Expected behavior**
p-calendar should allow output format to be specified rather than enforcing the above mentioned format. The output should allow formatting to be provided like for date pipe in angular, like `yyyy-MM-dd` that would actually return **2018-09-12**

**Minimal reproduction of the problem with instructions**
The problem will be best visible to those who live east of the UTC time zone. But for others, you can use the following string: *Wed Sep 12 2018 00:00:00 GMT+0200 (Central European Summer Time)*

1. In p-calendar register to listen to `onSelect` event. `(onSelect)="showDate($event)"`
2. In the function `
showDate(selectedDate: Date) {
    console.log(selctedDate.toISOString());
}`

The console output will produce different date.

**What is the motivation / use case for changing the behavior?**
The motivation is to get the proper date regardless of the time zone. If I am selecting a date in the past, I need to be sure that I would get the selected date in the past. Current date format is not adequate for all the cases. It would be great if the past dates are treated as GMT+0000 instead of determining the offset based on client's time zone.

At the moment, the only solution is to do read the first 28 characters of the date string, up to GMT, and drop the time zone offset and the rest of the string. This will return the proper date.

**Please tell us about your environment:**

OS: Windows 10, 
IDE: WebStorm, Visual Studio 2017 Community Edition, 
Web Server: Kestrel and IIS
Package manager: Yarn

* **Angular version:** 5.2.0

* **PrimeNG version:** 4.3.0

* **Browser:** [Chrome 69.0.3497.100 | Firefox 62.0 | Edge 40.15063.674.0 ]
 
* **Language:** [ TypeScript 2.6.2 | ES5]

* **Node (for AoT issues):** `node --version` =   v10.9.0

**Comment by cagataycivici** [comment]
Calendar does not handle timezone, it is up to the page author to convert based on client's using the hooks like value change or onSelect.
