### ISSUE TITLE
Slider ranged steps

### ISSUE THREAD

**Issue by bcneves13** [primefaces/primeng#6556]
Is there any chance that your slider step system support a custom range and percentage as you drag it?
something like 

`<p-slider [(ngModel)]="someRange" [min]="min" [max]="max" [step]="customSteps" [range]="true" (onChange)="onChange($event)"></p-slider>`

**where customSteps**
`
{
"2%":"0",
"4%":"5000",
"6%":"5001",
"8%":"10000",
"10%":"10001",
"12%":"20000",
"14%":"20001",
"16%":"30000",
"20%":"30001-40000",
"24%":"40001-50000",
"28%":"50001-100000",
"32%":"100001-200000",
"36%":"200001-300000",
"40%":"300001-400000",
"44%":"400001-500000",
"48%":"500001-1000000",
"52%":"1000001-2000000",
"56%":"2000001-3000000",
"60%":"3000001-4000000",
"64%":"4000001-5000000",
"68%":"5000001-10000000",
"72%":"10000001-20000000",
"76%":"20000001-30000000",
"80%":"30000001-40000000",
"84%":"40000001-50000000",
"88%":"50000001-100000000",
"92%":"100000001-200000000",
"96%":"200000001-300000000",
"100%":"300000001-total"
}
`

Or something like that?

**Comment by Spawnrad** [comment]
Have you found a solution about that ? I need to change the step value.
I have big value between 0 and 10Million and I don't know how to handle that.

**Comment by bcneves13** [comment]
I do not remember how i did about now, not even if it works.
but look on [my slider.js](https://github.com/bcneves13/primeng-slider/blob/master/slider/slider.js)
all the places that i use 
`this.range`, i replace several logics but i forgot to add the branch here or the primeng maintenner never saw the request.

i hope it helps

**Comment by bcneves13** [comment]
you do have to replace the archive in the node_modules/primeng/slider/slider.js for test or any improovements you have

**Comment by Spawnrad** [comment]
@bcneves13 Thanks very much for your answer  2 days i stuck with that :( 
I going to check your links <3
