### ISSUE TITLE
import FullCalendar

### ISSUE THREAD

**Issue by william-lohan** [primefaces/primeng#6558]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
`schedule.ts` expects [FullCalendar](https://github.com/primefaces/primeng/blob/3c5d2a76515ffcaeab27db21679b0765309ab7c5/src/app/components/schedule/schedule.ts#L4) to be global, this requires `fullcalendar.js` and `moment.js` to be loaded as global scripts, why not import like `import { Calendar } from 'fullcalendar';`, allowing the build system to module load it and properly tree shake.

**Expected behavior**
import FullCalendar, many users use `moment` and possibly `fullcalendar` in their code as well, this would result in duplicate moment code loaded in the browser (in the bundle and global script).

**Comment by gatimus** [comment]
fullcalendar is built with webpack and the dist has a webpackUniversalModuleDefinition so it can module load moment and only requires moment to be loaded globally if its self is loaded globally and listing them as peerDependencies would allow the developer to use which version of fullcalendar add moment they wish

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
