### ISSUE TITLE
Feature Request: MenuItem visible property as callback

### ISSUE THREAD

**Issue by Klinton90** [primefaces/primeng#6559]
[x] feature request 
It would be great if you can change `visible` property of `MenuItem` to accept callback. Useful, when split button used in Table row. 

Thanks.

**Comment by rhegner** [comment]
Yes!

Accepting a predicate for MenuItem.visible could safe a lot of boilerplate code with conditional menu items. Especially when a menu is opened directly from the template.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
