### ISSUE TITLE
Manipulating two dialogs on the component

### ISSUE THREAD

**Issue by kambalin** [primefaces/primeng#6563]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
```

**Case**
https://stackblitz.com/edit/two-dialogs-in-a-row

**Current behavior**
With a two (or more) dialogs on the component, if you trying to manipulate dialog after showing second (on the component markup) dialog, for example, maximize it 
```
window.setTimeout(() => { this.dialog.maximize(); });
```
(I have to do this manually, because centering dialog not working properly), you will get exception "ERROR TypeError: Cannot read property 'classList' of undefined". For the first dialog this working without exceptions.

**Expected behavior**
Manipulating any number of dialogs is possible within component.

**Minimal reproduction of the problem with instructions**
Place two dialogs to the component (see stackblitz example)

**What is the motivation / use case for changing the behavior?**
Can use dialog manipulation with multiple dialogs.

**Please tell us about your environment:**
VS Code, Windows 2012 R2

* **Angular version:** 6.1.7

* **PrimeNG version:**  6.1.3

* **Browser:** [Chrome 69.0.3497.100 x64]
 
* **Language:** [TypeScript 2.9.2]

**Comment by JacobSiegle** [comment]
It seems to me like it works if I change the code to -
@ViewChild("dialog1") dialog1;
@ViewChild("dialog2") dialog2;

Or am I mistaken and it's some other sort of error?

**Comment by kambalin** [comment]
> It seems to me like it works if I change the code to -
> @ViewChild("dialog1") dialog1;
> @ViewChild("dialog2") dialog2;
> 
> Or am I mistaken and it's some other sort of error?

This works, thanks. Closing.
