### ISSUE TITLE
Feature request: Equalize height of tab contents of TabView component

### ISSUE THREAD

**Issue by fperezgaliana** [primefaces/primeng#6564]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/github-rpw6uk

**Current behavior**
Right now, when a user clicks on a tab of a TabView component, the height adapts to it, moving up and down the content below. This is annoying sometimes, for example, inside dialogs, because changing the active tab resizes the dialog.

**Expected behavior**
Would it be possible to add a property to the component to force the height of the TabView to be the same as the first selected tab? For example, if the first tab has a height of 300px, set this height for all the other tabs (showing scrollbars in case that they have more content).

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
I think that it could be useful in some cases to keep a constant height of the TabView, to avoid modifying dialog sizes or move content up and down. A basic solution would be using CSS to force the height, but I've thought it would be great if the Tabview calculated the content's height and set it to all the tabs.

**Please tell us about your environment:**
Ubuntu 18.04

* **Angular version:** 5.X
Angular 6.1.8

* **PrimeNG version:** 5.X
v6.1.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
