### ISSUE TITLE
[BUG] primeNg version 4.3.0 - p-dialog keeps following mouse cursor after mouse click is released

### ISSUE THREAD

**Issue by NebojsaImpeo** [primefaces/primeng#6568]
Hello,

In one of our projects, we use Angular version 4.4.7 and primeng version 4.3.0. Updating these versions at the moment is **not possible**, so please, we need to find another solution for this problem.

**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-fnkf8x

**Current behavior**
Bug occurs only in **Internet Explorer** as far as i saw (i am using IE version 11.112.17134.0 atm). When we hold the mouse button, and move the dialog downwards, mouse cursor moves faster than dialog. Because of this, mouse cursor will leave the header part, while we are still moving the dialog, and it will not hover over it anymore. When we release mouse button, and if mouse cursor is not hovering over the header anymore, dialog will keep following the cursor indefinitely! 

**Expected behavior**
When mouse button is released, and if mouse cursor is not hovering over the header anymore, dialog should not keep following the cursor anymore at all! 

**Minimal reproduction of the problem with instructions**
Just open the dialog and move it around in the demo application I provided on stackblitz.com, using Internet Explorer.

**Please tell us about your environment:**
OS: Windows 10

* **Angular version:** 4.4.7
This is still the issue in newer versions! Demo i provided works with angular 6

* **PrimeNG version:** 4.3.0
This issue is fixed in the newer version, but we cannot update versions in our project at this time. This is not an option at the moment.

* **Browser:** Internet Explorer: 11.112.17134.0
Probably older version as well. Did not test this
 
* **Language:** all

* **Node (for AoT issues):** `node --version` =  8.11.1

My questions are:
1. Is it possible to request a hot-fix from primefaces developers specifically for version 4.3.0 to include this fix for p-dialog, considering that they already have this fix in versions 5+?
2. If not, can we take the source code, fix this by our self and then create a pull request on github for version 4.3.0? Would they consider this pull request at all?
3. Is there another way how can i fix this bug? I did not find anything about this in the documentation for primeng dialog, or here on github.

Thank you very much for reading!

**Comment by JacobSiegle** [comment]
Fork primeng and make the fix needed in your forked repo then publish to npm. I don't think you'll get any support for how old your primeng version is, they currently don't even take new feature PRs. 

This is a question and should be posted in the primeng forums it's not an issue. Consider closing and moving your post if you need more feedback.

**Comment by cagataycivici** [comment]
Try a newer version please.
