### ISSUE TITLE
columnSource is never subscribed because frozen is always undefined

### ISSUE THREAD

**Issue by mronus** [primefaces/primeng#6569]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
`ScrollableView#setScrollHeight` is never triggered after any change in columns because `frozen` is alwasy undefined in the constructor. So I think the following `if` block must be moved to `ngAfterViewInit`.

+ I think it would be really good to have it called after not only change in columns but also any column size change.

https://github.com/primefaces/primeng/blob/3c5d2a76515ffcaeab27db21679b0765309ab7c5/src/app/components/table/table.ts#L1890

**Expected behavior**
`ScrollableView#setScrollHeight` should be triggered after any change in columns and their sizes.

**What is the motivation / use case for changing the behavior?**
In case you have resizable columns + some frozen columns, the height of `ui-table-scrollable-body` is not re-calculated after a column size change that makes the grid scrollable horizontally.

* **Angular version:** 6.1.7

* **PrimeNG version:** 6.1.3

**Comment by yigitfindikli** [comment]
fixed in https://github.com/primefaces/primeng/commit/cdd333b7416e33761948b24499417086e412920c
