### ISSUE TITLE
Default sort when using multipleSort have no icon.

### ISSUE THREAD

**Issue by AizeLeOuf** [primefaces/primeng#6573]
**I'm submitting a bug.
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When using multiple sort with turbo table defaut sorting have no icon to specified current sort.

![image](https://user-images.githubusercontent.com/8999614/46087760-538b3300-c1ab-11e8-9cd6-cedee59f5ea5.png)

**Expected behavior**
When default sort specified using [multiSortMeta] object show arrow like single mode.

![image](https://user-images.githubusercontent.com/8999614/46087877-8503fe80-c1ab-11e8-99d0-c2a7ef272890.png)

**Minimal reproduction of the problem with instructions**
<p-table> with sortMode="multiple" and  [multiSortMeta]="sorts"

* **Angular version:** 5.3

* **PrimeNG version:** 6.1.3

* **Browser:** All
 
* **Language:** All

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
