### ISSUE TITLE
p-calendar: close button on button bar

### ISSUE THREAD

**Issue by tiagomsmagalhaes** [primefaces/primeng#6574]
**I'm submitting a ...**  (check one with "x")
```
[x] Feature Request
```

**What is the motivation / use case for changing the behavior?**

A close button on the button bar would be more intuitive to close the popup calendar when selecting multiple dates

**Comment by betosalvador** [comment]
This can be very useful!

**Comment by konum** [comment]
It would be alse very useful when showTime="true". I'm doing this while no official button present.

`<p-calendar #cal2 #last="ngModel" [(ngModel)]="vehicle.last_maintenance" name="maitenance" >
<p-footer>
<button pButton label="Close" (click)="cal2.overlayVisible = false"></button>
</p-footer>
</p-calendar>`

**Comment by cagataycivici** [comment]
@onursenture What do you think from UX point of view?

**Comment by cagataycivici** [comment]
We'll do it for 8.1.0.

**Comment by LukeHartcher** [comment]
Any update on this? 8.1.0 has been released and I believe we are now at 10.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by abidmaqbool20** [comment]
There is no close button available in the calendar in the documentation as well. Please reopen this issue and provide this functionality asap.
