### ISSUE TITLE
Treetable don't keep actual state of nodes after an update of the value 

### ISSUE THREAD

**Issue by UlricW** [primefaces/primeng#6577]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-ordi3f

**Current behavior**
When we uncollapse some nodes in the treetable, if we update an item and trigger the change of the treeTable, all nodes become collapsed. I use the trackBy which just change the item concerned in the dom .

**Expected behavior**
When we uncollapse some nodes in the treetable, if we update an item and trigger the change of the treeTable, the treetable state must be unchanged, just the line concerned must be updated

**Minimal reproduction of the problem with instructions**
Step to reproduce: 

- open the stackBlitz above
- open node of the treetable
- click on the change button
-the change is done but all node are collapsed

**What is the motivation / use case for changing the behavior?**
Users that use a treetable and made some change to update it want to keep the actual state of display nodes

* **Angular version:** 6.0.3

* **PrimeNG version:** 6.0.0-rc.1

* **Browser:** [all]

**Comment by yaroslav1988** [comment]
That's debatable, because TreeNode interface has **_expanded_** boolean field, which allows you to manage  the state of every node. Also there are **onNodeExpand** and **onNodeCollapse** output events to track state changes. So i doubt that we can call it a bug. Basically, in your example you always pass tree nodes with expanded = false (it just happens explicitly, because field is optional, and optional boolean field is false by default). 

So in your example treetable always displays exactly what you passed to it, i dont think its a bug.

But its just an opinion, no hate.

**Comment by UlricW** [comment]
Hi,
I understand your point of view, that's very good and I think you've right. 
But in my case my component has the changeDetectionStrategy to onPush to increase the perf of my application (there are a lot of data in the treetable), so in this case I have to change the reference of my object passed to my component that contains the treetable and not just change a value inside like your example. 
It means that I should keep all state for all data in the treetable and specify when I rebuild the object ? It's not a good thing for me, and that would mean that Treetable cannot be used in a strategy.Onpush component?

**Comment by yaroslav1988** [comment]
Ofcourse it can be used, but not as easy, as you probably wanted to. For example, you can notify your "pure" onPush component when it needs to manually refresh itself (when you shallow-modify your data and keeping reference the same).

Methods detectChanges() and markForCheck() are not hacks, i use them, i know a lot of guys who use them and you can use them too. It's totally ok. You can deal without them only, if your input data of primitive types, which is clearly is not the case here.

PS here is an example with manual notification of  "onPush" component, when it needs to refresh.
https://stackblitz.com/edit/github-ordi3f-wwkexe?file=src%2Fasd%2Fasd.component.ts
You can use observables, you can use direct templateReference variable, you can even use service to notify it or provide data to it, it doesnt matter, there are dozens of variants how to make onPush component refresh when data reference does not change.

Anyway, do TreeTableView has to implement all that or smth? I dont know .... i personally don't want it to, i prefer it to be just "dumb" view, who render what i gave it as it is.

**Comment by cagataycivici** [comment]
We've decided not to take any action as TreeNode has expanded property to keep state which can be done on page author's side.
