### ISSUE TITLE
Datascroller direction to be customizable: up/down

### ISSUE THREAD

**Issue by cuneytcalishkan** [primefaces/primeng#6579]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Datascroller component's load method is called upon scroll down event.

**Expected behavior**
It would be nice to change the direction of the scroll so that more data is loaded when the scroll reaches the top of the window or the element in case of inline scroll.

**What is the motivation / use case for changing the behavior?**
The way data is presented depends on the use case and there some cases where we might want to load more content when the scroll reaches the top of the container. e.g. a chat window where the latest messages are shown at the bottom and older messages are loaded when the scroll reaches the top.

**Comment by cagataycivici** [comment]
DataScroller is deprecated in favor of VirtualScroller
