### ISSUE TITLE
p-calendar doesn't display with correct styles

### ISSUE THREAD

**Issue by faisal-zulfiqar** [primefaces/primeng#6583]
**I'm submitting a ...** 
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Upon using p-calendar I expect to receive the same styled component as shown in the documentation. But in my case the calendar shown has a very weird styling even when all other UI components are working perfectly.

**Expected behavior**
Without this bug I'd get the same calendar dropdown as shown in the documentation.

**Minimal reproduction of the problem with instructions**
I've only put the most basic code to get the calendar: 
`<p-calendar [(ngModel)]="invoiceDate"></p-calendar>`
and I get this as a result:
![image](https://user-images.githubusercontent.com/17823377/46155221-3da36e00-c290-11e8-9e84-3908771ebde2.png)

**Please tell us about your environment:**

Ubuntu 18.04
VSCODE
NPM

* **Angular version:** 6.1.4

* **PrimeNG version:** 6.1.3

* **Browser:** Chrome 69, Firefox latest

 
* **Language:** Typescript

* **Node (for AoT issues):** `node --version` =   8.12.0

**Comment by cagataycivici** [comment]
You seem to be using Omega theme which is deprecated, migrate to Nova please if you need the same look as in showcase.

**Comment by faisal-zulfiqar** [comment]
@cagataycivici bless you! I changed the omega theme to nova but someone hardcoded the omega.css file in the assets directory, that was causing problems.
