### ISSUE TITLE
the Primeng Dialog Should not be Moved Off Screen 

### ISSUE THREAD

**Issue by OlenaTaras** [primefaces/primeng#6591]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/github-p8zwd8?file=src/app/app.component.html

**Current behavior**
When a user drags the dialog to the right or down, the dialog moves out of the screen.

**Expected behavior**
The dialog should move only inside the window, shouldn't be hidden out of the window border.

**Minimal reproduction of the problem with instructions**
Open the primeng dialog and drag it to the end of the window.
https://stackblitz.com/edit/github-p8zwd8?file=src/app/app.component.html

**What is the motivation / use case for changing the behavior?**
I don't know whether it is a bug or no. If it is as expected dialog behavior, then please help me to find a solution how to avoid such behavior and let dialog moves only inside the windows borders.

**Please tell us about your environment:**
 Windows 10, Webstorm, npm 5.6.0, HTTP server, ... 

* **Angular version:** 4.X

* **PrimeNG version:** 4.3.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript 2.5 | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   8.11.3

**Comment by keschra** [comment]
i would like to have this feature to

**Comment by cagataycivici** [comment]
Yes, I think it should not be moved off, we're checking this one out.

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
