### ISSUE TITLE
Expandable rows support for Frozen Columns

### ISSUE THREAD

**Issue by mronus** [primefaces/primeng#6596]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://github-chwamv.stackblitz.io

**Current behavior**
rowexpansion is not expanding to full width when we have frozen columns, but a duplicate rowexpansion is displayed under frozen column rows instead.
**Expected behavior**
rowexpansion expands to full width including frozen columns.

* **Angular version:** 6.1.7

* **PrimeNG version:** 6.1.3

**Comment by thedanielgray** [comment]
I would also like for it to be possible to define a frozen & non-frozen section of the rowexpansion template. I wonder whether it would be possible to accommodate both use-cases?

**Comment by mronus** [comment]
@thedanielgray I think it can be achieved by using `position: fixed` on a container `div`, and scrolling can be solve like it was done for independent two tables (frozen and unfrozen) that are scrolled together.

**Comment by cagataycivici** [comment]
Expandable rows and frozen columns combination is not supported due to technical reasons.

**Comment by thedanielgray** [comment]
It might be good to add some code which throws an explicit error (with a clear message) when the user attempts to enable both behaviors?
