### ISSUE TITLE
Tree Component

### ISSUE THREAD

**Issue by sdmoralesma** [primefaces/primeng#66]
There is a component that is useful for single page apps that manage files and is jquery based: jsTree (https://www.jstree.com/) this one is quite powerful. After looking for something similar on Angular2 there is nothing.

Could you provide a component like this one or is out of your scope?.
Thanks for your response

**Comment by attilacsanyi** [comment]
There is already similar from them in primeui or primefaces,  so perhaps it is also among @cagataycivici plan like those:
http://www.primefaces.org/primeui/#tree
http://www.primefaces.org/showcase/ui/data/tree/icon.xhtml

**Comment by cagataycivici** [comment]
Currently it is scheduled for 0.8;

https://github.com/primefaces/primeng/wiki/Roadmap

**Comment by cagataycivici** [comment]
Available in 0.8.0, will post the link here later today for the demo and docs.

**Comment by cagataycivici** [comment]
http://www.primefaces.org/primeng/#/tree

**Comment by JakeSummers** [comment]
@cagataycivici - Tree looks pretty great!  Are there plans to add any additional functionality?  These things in particular would be especially awesome: 

* #683 - Feature Request: Add drag and drop support to the tree 
* #682 - Feature Request: Tree should always expand to show the selected item 
* #261 - [New feature] TreeNode->expanded, tree, treeTable 

It could also be interesting to be able to provide a Template for each node, in the [same way that we can do so for the datatable](http://www.primefaces.org/primeng/#/datatabletemplating).  

Thanks!  Awesome toolkit.  Really liking it so far.

**Comment by attilacsanyi** [comment]
Drag and Drop would really a killing feature ;-) so +1 if you can do that somehow.

**Comment by JakeSummers** [comment]
@attilacsanyi - I think that you may be able to do drag and drop now using the method described in comment 2 of issue #683.

**Comment by cagataycivici** [comment]
DragDrop is available now for 4.0.RC1;

https://github.com/primefaces/primeng/issues/683

**Comment by mkseng** [comment]
Can anyone tell me about version of primeng in package.json for tree drag-drop? I am getting error while importing "DragDropModule". Currently, i am using "primeng": "^2.0.5" .

**Comment by cagataycivici** [comment]
4.0.0-RC2

**Comment by mkseng** [comment]
I am getting following error. And i did check with version 2.0.3, 4.0.0-rc.1, 2.0.4, 2.0.5, but i didn't find component "**TreeDragDropService**". 

npm ERR! notarget No compatible version found: primeng@4.0.0-RC2
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.9.1, 1.0.0-beta.1, 1.0.0-beta.2, 1.0.0-beta.3, 1.0.0-beta.4, 1.0.0-beta.5, 1.0.0-beta.6, 1.0.0-beta.7, 1.0.0-beta.8, 1.0.0-beta.9, 1.0.0-beta.10, 1.0.0-beta.11, 1.0.0-beta.12, 1.0.0-beta.13, 1.0.0-beta.14, 1.0.0-beta.15, 1.0.0-beta.16, 1.0.0-beta.17, 1.0.0-beta.19, 1.0.0-beta.20, 1.0.0-rc.1, 1.0.0-rc.2, 1.0.0-rc.3, 1.0.0-rc.4, 1.0.0-rc.5, 1.0.0-rc.6, 1.0.0-rc.7, 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 2.0.0-rc.1, 2.0.0-rc.2, 2.0.0-rc.3, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 4.0.0-rc.1, 2.0.4, 2.0.5
