### ISSUE TITLE
MessageService: clear() method not working

### ISSUE THREAD

**Issue by cquixada** [primefaces/primeng#6606]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
On the documentation page of the Growl component, you can not clear messages using the clear() method of the MessageService.

**Expected behavior**
The clear() method, with no specified parameters, should clear all messages displayed with the MessageService.

**Minimal reproduction of the problem with instructions**
Go to the "https://www.primefaces.org/primeng/#/growl" page, click the "Add with service" button and then the "Clear with service" button.

**What is the motivation / use case for changing the behavior?**
I'm experiencing this problem on a new system using PrimeNG 6.1.4.

**Please tell us about your environment:**
Ubuntu 16.04 LTS, VS Code, NodeJs, NPM, Angular.

* **Angular version:** 6.1.4

* **PrimeNG version:** 6.1.4

* **Browser:** all
 
* **Language:** TypeScript 2.9.2

* **Node (for AoT issues):** `node --version` =  8.9.4

**Comment by carlosearaujo** [comment]
I add

```
@ViewChild('growl') growl: Growl;

this.growl.messageService.clearObserver.subscribe(key => {
      this.growl.value = null;
})
```

in app.component while this issue is not solved. :)

**Comment by cquixada** [comment]
Great, thanks a lot.

**Comment by straiforos** [comment]
@carlosearaujo That did not solve the issue for me. So I am staying at 6.0.0~Alpha. thanks for the suggestion, will be looking to see when [#6606](https://github.com/primefaces/primeng/issues/6606) is merged
