### ISSUE TITLE
Galleria should allow customizing of filmstrip location to top, left, or right

### ISSUE THREAD

**Issue by danielthegray** [primefaces/primeng#6607]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
The Galleria component's thumbnail filmstrip can only be displayed at the bottom.

**Expected behavior**
The Galleria thumbnail filmstrip _should_ be able to be moved to the top, right, or left at the user's will and not only be set at the bottom of the image panel.

**What is the motivation / use case for changing the behavior?**
Better control of the look & feel of the Galleria component.

* **Angular version:**
6.1.4

* **PrimeNG version:**
6.1.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by EliranBarDavid** [comment]
Hi is there any update about this one?
Thanks
Eliran

**Comment by cagataycivici** [comment]
Please see;

https://github.com/primefaces/primeng/issues/3105
