### ISSUE TITLE
TurboTable with virtualscroll shows scrollbar when not needed

### ISSUE THREAD

**Issue by codehunter13** [primefaces/primeng#6614]
I'm submitting 
[x ] bug report 

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-e32bvg

**Current behavior**
when using  a TurboTable with virtual scroll and there are only a few items, the grid shows a scrollbar even when there is enough space. The last item in the grid is not fully displayed:

![2018-10-02 16_19_27-softwelngapp](https://user-images.githubusercontent.com/7559059/46354716-8e83df80-c65f-11e8-8de2-4613f618e250.png)

I tried to set virtual scroll only to true when there are a lot items. But setting this dynamicly does not seems to work

**Expected behavior**
No scrollbar :)

* **Angular version:
6.1.0
PrimeNG version:
6.1.4

**Comment by jayscheidt** [comment]
According to the docs you have to supply a` virtualRowHeight` input to the p-table as well as supply that same height to the table body rows. 

> In addition, to avoid performance problems row height is not calculated automatically and should be provided using virtualRowHeight property which defaults to 28px, in your row template also assign the height of the row with the same value for smooth scrolling. Note that variable row height is not supported due to the nature of the virtual scrolling behavior.

```
<p-table [columns]="cols" [value]="virtualCars" [scrollable]="true" [rows]="20" scrollHeight="200px" [virtualRowHeight]="30"
    [virtualScroll]="true" (onLazyLoad)="loadDataOnScroll($event)" [lazy]="true" [totalRecords]="totalRecords">
    <ng-template pTemplate="header" let-columns>
        <tr>
            <th *ngFor="let col of columns">
                {{col.header}}
            </th>
        </tr>
    </ng-template>
    <ng-template pTemplate="body" let-rowData let-columns="columns">
        <tr style="height:30px">
            <td *ngFor="let col of columns">
                {{rowData[col.field]}}
            </td>
        </tr>
    </ng-template>
</p-table>
```

Although I was still seeing issues with the scroll bar due to the border of the `<td>` being 1 extra pixel. From what I read, the td border shouldn't be calculated in the height, but it was. What I ended up doing was remove the border from the `<td>` and using a box-shadow to replicate the border
```
ui-table-tbody > tr > td {
    box-shadow: inset 0px -1px 0px #d6d6d6;
    border: none;
}
```
