### ISSUE TITLE
p-calendar 12 hour format doesn't reflect the time selected

### ISSUE THREAD

**Issue by nitishGE** [primefaces/primeng#6619]
_Originally posted by @nitishGE in https://github.com/primefaces/primeng/issue_comments#issuecomment-426571592_
Orignal issue marked as fixed but was not : https://github.com/primefaces/primeng/issues/2539

I am facing the same issue. At output += date.getHours() > 11 ? ' PM' : ' AM'; why are we not considering the user selected AM/PM value. Rather we are taking it from system time. This is where the issue comes.

During selection:
![image](https://user-images.githubusercontent.com/38280471/46402528-986c1800-c71d-11e8-8c5e-e6f16a1696a7.png)

Output:
![image](https://user-images.githubusercontent.com/38280471/46402552-a883f780-c71d-11e8-9693-fe99c4105227.png)

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
