### ISSUE TITLE
Dialog onHide method is never invoked

### ISSUE THREAD

**Issue by aleskurlovich** [primefaces/primeng#6623]
Version 6.1.4
Component: Dialog
Description:
onHide method is not invoked.

Usage:
`p-dialog id="id" header="Header" [(visible)]="isVisible" (onHide)="onHide()">`

Reason:
From dialog.js:
`onOverlayHide() {
        if (this.visible) {
            this.onHide.emit({});
        }
...
}`

this.visible is always false. Version 6.1.3 doesn't have this line and it works.

**Comment by cquixada** [comment]
I had the same problem. The workaround for me was to use "visibleChange" instead of "onHide".

**Comment by cagataycivici** [comment]
6520
