### ISSUE TITLE
PrimeNG: 6.1.4 - Editor "onTextChange" is not triggered when Quill.insertText() is called with source 'api'

### ISSUE THREAD

**Issue by rahul-winner** [primefaces/primeng#6624]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
We are consuming PrimeNG editor in our project. We are calling quill API for inserting text into editor something like below.
`this.quill.insertText(index, text, format, "api");`

Earlier we were using PrimeNG:4.2.0 and above api call was resulting into "onTextChange" event. However, this has been broken after we updated to version 6.1.4.

**Expected behavior**
onTextChange() should be emitted is we call insertText() with source 'api'.

**Minimal reproduction of the problem with instructions**
- use editor component in template something like below
```
      <p-editor [(ngModel)]="rich_text"
        (onTextChange)="onTextChange($event)"
        (onInit)="onEditorInit($event)">
```
- disable manual edit on editor within 'onEditorInit' function
`this.quill.enable(false);`
- call insertText() with source 'api'
`this.quill.insertText(index, text, format, "api");`
- check on 'onTextChange()' function. print something within this function
- Note that 'onTextChange' is not getting called

**What is the motivation / use case for changing the behavior?**

I'd like to describe the working of Quill API with respect to source input. Ref: https://quilljs.com/docs/api/#inserttext

> **insertText**
> Inserts text into the editor, optionally with a specified format or multiple formats. Returns a Delta representing the change. Source may be "user", "api", or "silent". Calls where the source is "user" when the editor is disabled are ignored.

In our case the editor is disabled (meant edit through keyboard is not allowed on editor) and we are supplying source as 'api'. 
Now let's take a look on PrimeNG code for Quill editor implementation https://github.com/primefaces/primeng/blob/master/src/app/components/editor/editor.ts
Please note below that "onTextChange" is emitted only when source is "user". And in our case when editor is disabled and source is 'api' the quill indeed emit the 'text-change' event but PrimeNG implementation does not do anything as it is expecting source as 'user'.
```
this.quill.on('text-change', (delta, oldContents, source) => {
            if (source === 'user') {
                let html = editorElement.children[0].innerHTML;
                let text = this.quill.getText().trim();
                if (text.length === 0) {
                    html = null;
                }

                this.onTextChange.emit({
                    htmlValue: html,
                    textValue: text,
                    delta: delta,
                    source: source
                });
                
                this.onModelChange(html);
                this.onModelTouched();
            }
        });
```

I hope I have explained the use case thoroughly. However, please let me know if you need elaboration at any step.

**Please tell us about your environment:**

Operating system: windows
IDE: MS VS Code
package Manager : npm
HTTP Server: Does not matter

* **Angular version:** 5.X

Angular : 6.x
**Note:** this is not related to Angular update

* **PrimeNG version:** 5.X

PrimeNG version : 6.1.4
Earlier we were using PrimeNG:4.2.0 and above api call was resulting into "onTextChange" event. However, this has been broken after we updated to version 6.1.4.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
This seems to be the expected behavior as derived from the Quill docs;

> Changes may occur through an API but as long as they originate from the user, the provided source should still be "user".

So suggested action is;
```js
this.quill.insertText(index, text, format, "api");
```
