### ISSUE TITLE
p-dropdown: Allow to choose OPTION_VALUE when arbitrary objects are used instead of SelectItems as options

### ISSUE THREAD

**Issue by kishor-p** [primefaces/primeng#6630]
**I'm submitting a ...**
```
[x] feature request
```
**Current behavior**
Currently when you use arbitrary objects instead of SelectItems as options, you can choose the label from object using `optionLabel` attribute. But the value has to be an arbitrary object.

**Expected behavior**
It would be good if we could some how choose one of the properties from arbitrary object as VALUE.
Like a new attribute `selectedValue` or `optionValue` or simply `value`.

**What is the motivation / use case for changing the behavior?**
In scenarios where I want to use arbitrary objects as `options` on `p-dropDown` but dont want entire arbitrary object as selected value. Just want one of the properties of arbitrary object to be a value.

* **Angular version:** 6.x

* **PrimeNG version:** 6.x

* **Browser:** 
ALL
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by JacobSiegle** [comment]
I don't really understand the value of the change here unless I don't understand correctly. 

To get this to work you would have to bind to the dropdown the prop you wanted like [dropdownPropToGet]="Pizza.Topping", it seems like just as much work compared to what you have to do now which is pulling the property out of the selected item yourself with code like selectedItem.value.Pizza.Topping.

**Comment by yelhouti** [comment]
You can find it implemented here in the meantime, I'll try to keep my branch up to date:
https://github.com/yelhouti/primeng/releases/tag/8.0.0-rc2

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/issues/4295
