### ISSUE TITLE
How to hide a column at initialization 

### ISSUE THREAD

**Issue by shopsoy** [primefaces/primeng#6633]
Hi,

How to hide a column when we are initializing the table?
Below i sthe columns array:
```
_cols: any[] = [
		{ field: 'fild1', header: 'Myheader1' },
		{ field: 'fild2', header: 'Myheader2' },
		{ field: 'fild4', header: 'Myheader3' },
		{ field: 'fild5', header: 'Myheader4' }
	];

```
Is there a way to set a key for each column that could indicate if the column should be visible for hidden?
Such:
```
_cols: any[] = [
		{ field: 'fild1', header: 'Myheader1', viseble: false},
		{ field: 'fild2', header: 'Myheader2', viseble: true},
		{ field: 'fild4', header: 'Myheader3', viseble: true },
		{ field: 'fild5', header: 'Myheader4', viseble: true }
	];

```
Or how can I do it?

Thanks in advance

**Comment by JacobSiegle** [comment]
This is a question not an issue you should post it to the PrimeNG forums not here. If you already know the cols you want just provide only them to the table and add the others later.

**Comment by cagataycivici** [comment]
Please use forum for help requests and questions.
