### ISSUE TITLE
onHide Event not working in 6.1.4

### ISSUE THREAD

**Issue by sharma-sahil** [primefaces/primeng#6636]
OnHide event is not working fine in the latest version 6.1.4. It was working fine the previous verison 6.1.3.
I have not made any changes in the code, but still after the latest verison it's not working anymore.

**Current behavior**
onHide event is not firing on the click of "X" link on the top right corner of modal.

**Expected behavior**
onHide event should fire on the click of "X" link on top right corner of modal.

**My HTML code is** 
`<div class="sm-modal sm-sl-pad">
  <p-dialog [modal]="true" [responsive]="true" [width]="500" [minWidth]="200" [minY]="70"
            [maximizable]="false" [baseZIndex]="10000"
            [(visible)]="isModalVisible" (onHide)="emitCancelEvent()"   >
      <p-header>
          {{headerText}}
      </p-header>
      <span>{{ messageText }}</span>
      <p-footer>
        <button type="button" pButton (click)="emitConfirmEvent()" > {{confirmButtonText}} </button>
        <button type="button" pButton (click)="emitCancelEvent()" class="ui-button-secondary"> {{cancelButtonText}} </button>
      </p-footer>
  </p-dialog>
</div>
`

**my ts code is** 

`  
  isModalVisible = false;

  headerText = '';

  messageText = '';

  confirmButtonText = '';

  cancelButtonText = '';

emitConfirmEvent() {
    this.confirm.emit('');
  }

  emitCancelEvent() {
    console.log('emitting cancel event')
    this.cancel.emit('');
  }
`

* **Angular version:** 6.0.3

* **PrimeNG version:** 6.1.4

* **Language:**  TypeScript 2.7.2

**Comment by cquixada** [comment]
Solved in #6520.
