### ISSUE TITLE
PrimeNg documentation page - add search box to the side bar

### ISSUE THREAD

**Issue by ishaan-shringi** [primefaces/primeng#6637]
Hello everyone,

I have been using PrimeNg for some time and I have been really impressed by the framework.

https://www.primefaces.org/primeng/

Almost everyone using PrimeNg uses [this web app](https://www.primefaces.org/primeng/) which has a very well written documentation. However, the only thing I find missing is a <b>search bar</b> which will make this documentation really easy to navigate.

One such example of a search bar can be seen in [Twitter bootstrap's official documentation page](https://getbootstrap.com/docs/4.1/getting-started/introduction/).

![1](https://user-images.githubusercontent.com/42369669/46518247-d89fd780-c890-11e8-931d-f3666de5dc0f.JPG)

I'm not sure If this is the right place to suggest this improvement, but this feature can really help beginners (including me apparently) to learn the framework faster.

Regards,
Ishaan Shringi

**Comment by dinesh-here** [comment]
@cagataycivici @yigitfindikli anyone started working on this?  Can we use router.config to get all configured routes and components list to build search bar items?
