### ISSUE TITLE
Can't multisort datatables that have columns with custom sort function defined

### ISSUE THREAD

**Issue by ryanwawr** [primefaces/primeng#664]
Custom column sort functions don't work when datatable is in multiple sort mode.

**Comment by cagataycivici** [comment]
Shoud be fixed in recent releases, please drop a comment if issue still persists and we may reopen.

**Comment by cguilhermef** [comment]
Same issue here. When I remove `sortMode="multiple"` from `<p-datatable>` tag, custom function for sorting works.

**Comment by idairen** [comment]
Hit same issue and my primeNG version is 4.1.2, if change sortMode to "single", the custom function works.
for sortMode="multiple", it doesn't work.

**Comment by ztgluis** [comment]
This doesn't seem to be resolved in PrimeNG version 4.3.0 yet, same issue as described by cguilhermef and idairen, this issue should be re-opened.
