### ISSUE TITLE
Where is PrimeNG documentation for previous versions?

### ISSUE THREAD

**Issue by artonio** [primefaces/primeng#6642]
PrimeNG has excellent documentation. But how do we read the docs for the previous primeng versions? For example: https://www.primefaces.org/primeng/#/table this is now a TurboTable, where do I find the docs for the regular p-datatable that existed in the previous versions?

**Comment by JacobSiegle** [comment]
You can still find datatable on the website but it's hidden - https://www.primefaces.org/primeng/#/datatable

I think the only way to pull an old version of the docs right now would to be to pull from git and load it up yourself on localhost.

**Comment by cagataycivici** [comment]
Please use forum for questions.

**Comment by sxt26** [comment]
But it doesn't open the previous version https://www.primefaces.org/primeng/#/datatable I tried,
