### ISSUE TITLE
Color Picker - Add input field to allow user to input Hex or RGBA

### ISSUE THREAD

**Issue by jiangyh1024** [primefaces/primeng#6649]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Waiting Time: ~8 weeks.

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
No Input fields

**Expected behavior**
 Add input field to allow user to input Hex or RGBA

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.X

* **PrimeNG version:** 5.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by dinesh-here** [comment]
Hi @jiangyh1024 

Color Picker component is already accepting hex color format as input.
`<p-colorPicker [(ngModel)]="color"></p-colorPicker>
color = "000000";
`
Checkout the below URL 
https://stackblitz.com/edit/github-rykzyn
https://www.primefaces.org/primeng/#/colorpicker

**Comment by jiangyh1024** [comment]
> Hi @jiangyh1024
> 
> Color Picker component is already accepting hex color format as input.
> `<p-colorPicker [(ngModel)]="color"></p-colorPicker> color = "000000"; `
> Checkout the below URL
> https://stackblitz.com/edit/github-rykzyn
> https://www.primefaces.org/primeng/#/colorpicker

Hi， I mean allowing user  to input rgb or hex. You can see https://zefoy.github.io/ngx-color-picker/, just like 'ngx-color-picker' does.

currently, I use the below code to allow user to input hex
```
      <div class="k-form-field">
        <span>Fore Color:</span>
        <p-colorPicker  formControlName="foreColor" #foreColor></p-colorPicker>
        <input type="text" class="k-textbox" (change)="onColorChanged(foreColor)" [(ngModel)]="foreColor.inputBgColor"
          [ngModelOptions]="{standalone: true}" />
      </div>

      <div *ngIf="formGroup.get('foreColor').dirty && formGroup.get('foreColor').hasError('pattern')" class="k-form-field">
        <span></span>
        <div class="a-invalid-message">
          Invalid color
        </div>
      </div>
```

```
  public onColorChanged(color: ColorPicker): void {
    // update form value manually
    color.writeValue(color.inputBgColor);
    color.onModelChange(color.inputBgColor);
  }
```

**Comment by jiangyh1024** [comment]
any other reply ??

**Comment by Jagan-P** [comment]
Please add this feature. Primefaces already has this feature. Then why isn't this available for Angular distribution alone?

![image](https://user-images.githubusercontent.com/31800888/169285618-e5d5f179-4a6c-48e3-b48d-93b61d7b114c.png)

Please add this feature. Primefaces already has this feature. Then why isn't this available for Angular distribution alone?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by tomanak500** [comment]
user input in hex or rgb is still not avaliable. I am checking current
- demo page at https://www.primefaces.org/primeng/colorpicker and 
- source code at https://github.com/primefaces/primeng/blob/master/src/app/components/colorpicker/colorpicker.ts

**Comment by Ali-hd** [comment]
we are closing on 5 years and this simple feature is still not implemented, we have to hack our own

**Comment by Gykonik** [comment]
Is there any new information about whether the feature will be implemented any time soon? :D
It would make the user experience and accessibility so much better by not relying on dragging the color, but entering exact values without a complicated workaround.

**Comment by mpuerto-paymefy** [comment]
Please, add this, it has to be simple...
