### ISSUE TITLE
datatable checkbox selection, select all

### ISSUE THREAD

**Issue by izll** [primefaces/primeng#665]
Hi,

If I use datatable with checkbox selection and I select all, the model not updating, because this.selectionChange.emit(this.selection); is missing from toggleRowsWithCheckbox(event) function.

Thanks,
izll

**Comment by tvblomberg** [comment]
I am running into this same issue. It would be awesome to get this fixed. Love the Datatable!

**Comment by sudheerj** [comment]
It was added in later releases.

**Comment by stacyjgu** [comment]
is this issue resolved?
