### ISSUE TITLE
p-Table lazy Loading not sorting or filtering

### ISSUE THREAD

**Issue by feder89** [primefaces/primeng#6651]
Hi, I'm upgrading  from 4 to 6 version of angular and also the last version of primeng, but I've a problem with the table:
Using lazyloading filter and sort don't work
thi is my code:
`<p-table [autoLayout]="true" [immutable]="false" [lazy]="true" [totalRecords]="totalRows" (onLazyLoad)="loadLazy($event)" [tableStyle]="{'overflow':'scroll'}" #dt [value]="assets" selectionMode="single" sortField="inventario" [paginator]="true" [rows]="15" (onRowExpand)="expandendRow($event)" [responsive]="true" [rowHover]="isAdmin.canActivate()" dataKey="id"  (onRowSelect)="openDialogUpdate($event)"><ng-template pTemplate="header">`
    

`<tr>
      <th [pSortableColumn]="'inventario'">Inventario <p-sortIcon [field]="'inventario'"></p-sortIcon></th>
      <th [pSortableColumn]="'classe'">Classe <p-sortIcon [field]="'classe'"></p-sortIcon></th>
      <th [pSortableColumn]="'modello'">Modello <p-sortIcon [field]="'modello'"></p-sortIcon></th>
      <th [pSortableColumn]="'reparto'">Reparto <p-sortIcon [field]="'repartiAssociati'"></p-sortIcon></th></tr>`

`<tr><th><input  style="width: 100%" pInputText type="text" (input)="dt.filter($event.target.value, 'inventario', 'contains')"></th><th><input style="width: 100%" pInputText type="text" (input)="dt.filter($event.target.value, 'classe', 'contains')"></th><th><input style="width: 100%" pInputText type="text" (input)="dt.filter($event.target.value, 'modello', 'contains')"></th><th><input style="width: 100%" pInputText type="text" (input)="dt.filter($event.target.value, 'repartiAssociati', 'contains')"></th></tr></ng-template>`

any solution about this behaviour?

**Comment by ctrl-brk** [comment]
With lazy load you need to do your sorting and filtering on the server side.

**Comment by feder89** [comment]
Thank you. I'm trying to make them custom. Custom filtering event is invoked when I digit in header input text, but if I use pTable option [customSort]="true", with (sortFunction)="cs($event)" isn't invoked, but it loades the first lazy call. Have you any idea about this?

**Comment by cagataycivici** [comment]
Please use forum for help requests and questions.

**Comment by dmastag** [comment]
@cagataycivici I was just checking the Forum and see that its not answering a similar question

https://forum.primefaces.org/viewtopic.php?f=35&t=57148&p=170883&hilit=lazy+loading+sort#p170883
