### ISSUE TITLE
Tooltip does'nt show when input text is disabled

### ISSUE THREAD

**Issue by ndci** [primefaces/primeng#6656]
I'm submitting a ...

**[ ] bug report**

PS : `errorMessage.length > 0`

_**Work when**_

`<input type="text"
           [class.borderRed]="errorMessage.length"
           [tooltipDisabled]="!errorMessage.length"
           pTooltip="{{errorMessage}}"
    />`

_**Nothing when**_

`<input type="text"
           [disabled]="true"
           [class.borderRed]="errorMessage.length"
           [tooltipDisabled]="!errorMessage.length"
           pTooltip="{{errorMessage}}"
    />`

* **Angular version:** 6.1.6

* **PrimeNG version:** 6.1.4

**Comment by cagataycivici** [comment]
This is expected, browser do not trigger the necessary events such as mouseover as a result tooltip cannot be attached. You may wrap the input inside a div and attach the tooltip to this wrapper as a workaround.
