### ISSUE TITLE
Menubar gets closed immediately after mouse enter on menu-item when AutoDisplay property as false

### ISSUE THREAD

**Issue by the-golden-girl** [primefaces/primeng#6657]
I am using PrimeNG Menubar v5.2.5 with AutoDisplay property as false.
The issue is, when you open a menu item and getting away from it, and then move the mouse over the same menu item, it gets closed.

But, this was not the case in v5.2.4. There it is working perfectly.

You can also check this issue on https://www.primefaces.org/primeng/#/menubar, in their without AutoDisplay Demo. It is also replicating there.

**Comment by himanshujain1985** [comment]
We are also facing this issue. Is there any update or workaround for this issue?

**Comment by Tryforce** [comment]
This is very frustrating. I'm experiencing the same thing. With auto display set to false, it's reasonable to assume that the menu should remain open until clicked elsewhere or until an item is clicked. Closing on mouseenter makes no sense.

**Comment by umdstu** [comment]
@cagataycivici - Could you please update the documentation to reflect the `autoDisplay` property for p-menubar? Thanks!
