### ISSUE TITLE
I can't find nova theme scss files in the primeng package

### ISSUE THREAD

**Issue by malbarmawi** [primefaces/primeng#6658]
**I'm submitting a ...**
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
Old version of **primeng** we use to have theme scss file but for nova we only get compiled css file that make any update to theme very hard , and writing custome style above nova css theme make style files extremely big

**Expected behavior**

make nova scss file available to be used not the compiled css file.

**Minimal reproduction of the problem with instructions**

* **Angular version:** 6.X

* **PrimeNG version:** 6.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by cagataycivici** [comment]
SCSS is a premium feature and requires a subscription of PrimeNG Designer.

https://www.primefaces.org/designer/primeng
