### ISSUE TITLE
misaligned table headers using scroll height with row expand

### ISSUE THREAD

**Issue by machfalcon** [primefaces/primeng#6662]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-ubzox2-ek8mke

**Current behavior**
Using row expand with scrolling causes the headers to become misaligned

**Expected behavior**
When row expand causes the viewport to scroll, the header should set appropriate margin so columns are aligned.

**Minimal reproduction of the problem with instructions**
1. Create a table with a scroll height and row expand
2. Add items to the table with total height less than the scroll height
3. Expand items in the table until the total height is greater than the scroll height

**What is the motivation / use case for changing the behavior?**
Misaligned column headers look really bad for the user.

**Please tell us about your environment:**

* **Angular version:** 6.X
* **PrimeNG version:** 6.X
* **Browser:** [all]
* **Language:** [all]

**Comment by thaihacong** [comment]
I am also facing the same issue.
Someone, please help as soon as possible.
Thanks,

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
