### ISSUE TITLE
Clicking close icon on the Confirm dialog is invoking reject action

### ISSUE THREAD

**Issue by eneskoroglu** [primefaces/primeng#6663]
This is a reported and closed (by telling should work on 4.2.2) issue on [link](https://github.com/primefaces/primeng/issues/3692), one year ago. Same issue still exists, unfortunately.

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When using confirm dialog clicking on close icon is taking the action as reject.

**Expected behavior**
It should just close the confirm dialog.

**Minimal reproduction of the problem with instructions**
The behaviour can be seen in your showcase link below. clicking close icon takes the action as reject.
https://www.primefaces.org/primeng/#/confirmdialog

**What is the motivation / use case for changing the behavior?**
For Yes/No/Cancel scenarios.

* **Angular version:** 6.1.1

* **PrimeNG version:** 6.1.2

* **Browser:** [all]

**Comment by vthomas13** [comment]
Unnecessary logic on a neutral action. Allow users to override this logic with extra parameters, at the very least.

**Comment by StanciuMarian** [comment]
Any news about this ? I am using 7.1.3 and still having this problem.

**Comment by lazarencomihai** [comment]
any updates on this? the component is very good and has a nice api but this logic is killing it for our project.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
