### ISSUE TITLE
"life" attribute for <p-toast>

### ISSUE THREAD

**Issue by cquixada** [primefaces/primeng#6664]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
It would be nice if p-toast had a "life" attribute, as in p-growl (deprecated).
Anyway, the "life" attribute, when defined in the message itself, would have priority.

**Expected behavior**
p-toast life="10000"

**What is the motivation / use case for changing the behavior?**
Avoid having additional code in the application to do so.

**Comment by cagataycivici** [comment]
Let's rather not duplicate the API, messages already have life in their API.
