### ISSUE TITLE
[Bug] Multiselect defaultLabel model binding does not work

### ISSUE THREAD

**Issue by simonnagl** [primefaces/primeng#6665]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

**Current behavior**
Changes to <p-multiselect [defaultLabel]="someValue"> are not presentated in the view

**Expected behavior**
Model binding should work as expected.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
In our app you can change the translation on the fly. Changes to the default label are not detected.

**Please tell us about your environment:**

* **Angular version:** 6.1.8

* **PrimeNG version:** 6.1.3

* **Browser:** [Chrome XX]

 
* **Language:** [TypeScript 2.9.1]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Do you mean defaultLabel?

**Comment by simonnagl** [comment]
> Do you mean defaultLabel?

Thanks. Edited above.

**Comment by cagataycivici** [comment]
Merged, thank you.
