### ISSUE TITLE
Selecting item from dropdown by using firefox

### ISSUE THREAD

**Issue by Eliador** [primefaces/primeng#667]
When i trying to select item in dropdown, selected item is changed, but "angular" throw exception in "zone.js". So panel with dropdown items is not hid.
For example you can look your examples: [http://www.primefaces.org/primeng/#/dropdown](http://www.primefaces.org/primeng/#/dropdown)

I use firefox 47.0.1 and last revision of release primeng (1.0.0-beta.11)

**Comment by Ov3rlo4d** [comment]
This happens because the method `onItemClick(option)` in `dropdown.ts` references the variable event which is not in scope.

It works in chrome because chrome create a global event object when some event is fired, but this is not something you can rely on.
