### ISSUE TITLE
p-Dropdown : ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ui-inputwrapper-focus: true'. Current value: 'ui-inputwrapper-focus: false'.

### ISSUE THREAD

**Issue by fxvits** [primefaces/primeng#6671]
[X ] bug report

Current behavior
--------------------
I have a dropdown in a div and when I select an option it raised the following error :ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ui-inputwrapper-focus: true'. Current value: 'ui-inputwrapper-focus: false'.

```
 <div *ngIf="!loading" >
            <div *ngIf="filterList">
                <label>Filters </label>
                <p-dropdown [(ngModel)]="selectedFilterItem"
                            optionLabel="filterTitle"
                            (onChange)="onFilterChanged($event.value)"
                            [options]="filterList"
                            [autoWidth]="false">
                </p-dropdown>
            </div>
</div>
```

FYI : loading =>  variable used to display a spinner during the loading of the data and hiding the dropdown until all the data are ready. 

Expected behavior
-------------------------
No error ;-)

Solution? : 
-----------
```
    Dropdown.prototype.onInputFocus = function (event) {
		setTimeout(() => {
        this.focused = true;
        this.onFocus.emit(event);
		});
    };
    Dropdown.prototype.onInputBlur = function (event) {
        setTimeout(() => {
        this.focused = false;
        this.onModelTouched();
        this.onBlur.emit(event);
   	});
    };

```
Angular version:** 6.1
PrimeNG version:** 61.4
Chrome Version 69.0.3497.100
TypeScript 2.9.2

**Comment by cagataycivici** [comment]
Provide a test case please if you'd like this be looked at;

https://stackblitz.com/github/primefaces/primeng-issue-template

**Comment by cuneytcalishkan** [comment]
I am facing the same issue while opening a modal dialog upon dropdown content selection.
"ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ui-inputwrapper-focus: true'. Current value: 'ui-inputwrapper-focus: false'."

**Comment by cuneytcalishkan** [comment]
@cagataycivici I am using 6.1.4 actually and indeed I saw the old issue that was closed and supposed to close this one. I tried to create test case on stackblitz but even the dropdown didn't open when I created a sample app. I will try again and provide with a sample code for this. Thanks for your time and reply
