### ISSUE TITLE
Feature Request: Trigger menu activation on (mousedown) || (mouseup) & menu item activation on (mouseup)

### ISSUE THREAD

**Issue by KeithGillette** [primefaces/primeng#6673]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Menus using MenuModel as well as Inputs displaying a menu trigger menu activation as well as menu item selection on `(click)`.

**Desired behavior**
Change (1) menu activation to trigger on `(mousedown)` and `(mouseup)` instead of on `(click)` and (2) menu item selection / MenuModel `command` handlers to trigger on `(mouseup)` instead of on `(click)`.

**What is the motivation / use case for changing the behavior?**
This change would allow PrimeNG to support MacOS-style menu/item selection mechanics as well as its current Windows-style mechanics, making applications built on the library more user-friendly and cross-platform.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by KeithGillette** [comment]
As testing the [PrimeNG Menu demo](https://www.primefaces.org/primeng/menu) shows, this feature request has not been implemented. It seems that supporting this menu interaction user interface mechanic should be a fairly straightforward change to which events are processed for menu and item activation that would make the PrimeNG library more user-friendly by supporting MacOS-style menu/item selection mechanics in addition to its current Windows-style mechanics, so I ask that this issue be reopened, @mertsincan, to be considered for the PrimeNG roadmap.

**Comment by cetincakiroglu** [comment]
Hi,

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 
For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
