### ISSUE TITLE
feat-request: Table Column Index for column toggle 

### ISSUE THREAD

**Issue by fuyucn** [primefaces/primeng#6675]
Add Table Column index feature for column toggle.
Currently, the column toggle will reorder the index of each column in table, but i want them to always shows in order.
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Comment by cagataycivici** [comment]
MultiSelect, the component used to implement column toggle demo passes index to its item template so you already have access to it in your item template.

**Comment by fuyucn** [comment]
I think i mislead-ed, from my topic. Already fix the topic.
I just try to add index for table columns.
Ex: As in demo, if you uncheck `vin` field, and then check it. The `vin` column will show at end. I want it shows as in order.
