### ISSUE TITLE
Overlay panel doesn't emits OnHide event (PrimeNG 6.1.4)

### ISSUE THREAD

**Issue by axinedy** [primefaces/primeng#6680]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report 
[ ] feature request
[ ] support request
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-kenj5h

**Current behavior**
Overlay panel emits onShow event, when panel becomes visible. 
But doesn't emits  onHide event, when the panel becomes hidden.
This bug is in PrimeNG 6.1.4, in 6.1.3 both events emits ok.

**Expected behavior**
Overlay panel will emit onShow event.

* **Angular version:** 6.1.2

* **PrimeNG version:** 6.1.4

* **Browser:** [ Chrome 69 | Firefox 62 ]

**Comment by bossqone** [comment]
Fixed in #6520

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/issues/6520
