### ISSUE TITLE
Breadcrumb - Last item should not be a link

### ISSUE THREAD

**Issue by cindoum** [primefaces/primeng#669]
Breadcrumb - Last item should not be a link as it is mean to be the current page. 
Be able to choose if we want a link or a simple text for each item would be a nice things too.

**Comment by jepsar** [comment]
Allowing a h:outputText in p:breadCrumb would be nice, or a current / last item text attribute on p:breadCrumb.

**Comment by sudheerj** [comment]
OutputText is a JSF tag which is not related to PrimeNG stuff at all.IMHO, textOnly or leaf attribute for breadcrumb specific component make sense.

**Comment by jepsar** [comment]
Oh, wait, PrimeNG.. thought this was PrimeFaces (JSF). Will check if this issue exists there.

**Comment by cagataycivici** [comment]
Thank you, we'll reopen if more users demand it and make it customizable. Right now we need more feedback and make sure backward compatibility is not broken.
