### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by dmytro-gokun** [primefaces/primeng#6699]
It might be me, but I cannot find anything like release notes anywhere. I see there is a new version out (6.1.5) and I'd like to know what exactly has been changed, which components were affected, are there any breaking changes etc. Is there any place to find this information?

**Comment by bossqone** [comment]
Only changelog available is github milestone - https://github.com/primefaces/primeng/milestone/109?closed=1

**Comment by dmytro-gokun** [comment]
@bossqone Got it. Well, at least it's something to look at.
However, if you think of using the lib in a commercial product, the most painful thing here is absence of the clear list of the breaking changes. That's always a concern when updating a library to a new version.

Anyways, thanks for your reply (Y)

**Comment by JacobSiegle** [comment]
The notes are on the blog - https://www.primefaces.org/blog/. This is a question not an issue please consider closing and using the primeng forum in the future for questions instead.

**Comment by cagataycivici** [comment]
Breaking changes are listed at;

https://github.com/primefaces/primeng/wiki/Migration-Guide

**Comment by dmytro-gokun** [comment]
Dare I suggest that these useful links are put in the README? :)

**Comment by cagataycivici** [comment]
Here is the initial version, we'll add more info about breaking changes as well so it will be maintained/updated from now on.

https://github.com/primefaces/primeng/blob/master/CHANGELOG.md

**Comment by dmytro-gokun** [comment]
@cagataycivici Wow, thanks a lot (Y)
