### ISSUE TITLE
p-multiselect overlay can be positioned off screen

### ISSUE THREAD

**Issue by digeomel** [primefaces/primeng#6702]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/ngprime-multiselect

**Current behavior**
If you have a multiselect control containing an option with a very long label, the width of the component is too wide. You can put max-width in the panelStyle attribute, but if the width of the window/browser is small, the overlay panel can still be rendered off-screen, as shown in the screenshot below:

![image](https://user-images.githubusercontent.com/3295889/47024241-92385b80-d161-11e8-9f55-1aabafa56027.png)

I've traced this down to the `relativePosition()` method of the `DomHandler` class. The lines:

```
if ((targetOffset.left + elementDimensions.width) > viewport.width)
            left = targetWidth - elementDimensions.width;
```

should be:

```
if ((targetOffset.left + elementDimensions.width) > viewport.width)
            left = Math.max(targetWidth - elementDimensions.width, 0);
```

**Expected behavior**
The multiselect overlay should never be rendered partially or wholy off-screen. Ideally it should also follow the window resizing event, but that's another issue.

**Please tell us about your environment:**
Windows 10

* **Angular version:**  6.1.7

* **PrimeNG version:** 6.1.4

* **Browser:** all
 
* **Language:** TypeScript

**Comment by rafa-as** [comment]
same here

**Comment by jainsamyak** [comment]
what's the solution to this?

**Comment by yigitfindikli** [comment]
fixed in https://github.com/primefaces/primeng/issues/6803
