### ISSUE TITLE
Rename title/subtitle properties of Card

### ISSUE THREAD

**Issue by AlainD-** [primefaces/primeng#6703]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
The card component has an input property named `title` used to set the title header of the card.

The fact that this property is named 'title' conflicts with the 'title' attribute of HTML, which makes the value passed in the title attribute displayed all over the card on mouse over, because title="My Title" is present in the DOM at the end.

**Expected behavior**
rename the `title` input property into something else, so that it is not displayed on mouse over over the card.

**Minimal reproduction of the problem with instructions**
- Access the online demo/documentation of primeNG.
- open the panels menu, and select the card menu
- mouse over on the 1st card 

![image](https://user-images.githubusercontent.com/5165564/47076664-84391800-d1ff-11e8-8a2e-69c0ad6289bd.png)

**What is the motivation / use case for changing the behavior?**
- very annoying when using the mouse to read or point the content of a card body

* **Angular version:** 6.1.10

* **PrimeNG version:** 6.1.5

* **Browser:** all

**Comment by arielgpe** [comment]
I agree with you. 
I can submit a PR with this. Would pTitle be a good name for it to keep naming convention?

**Comment by arielgpe** [comment]
I made the changes as specified by the pull request. 
the previous **title** and **subtitle** attributes are still available so we don't break previous users when merged. I put some comments specified deprecation as per jsdocs.

What are your opinions on this @Mrtcndkn. Can this be merged?

**Comment by cagataycivici** [comment]
Renamed to header and subheader
