### ISSUE TITLE
p-table force a re-render?

### ISSUE THREAD

**Issue by sgentile** [primefaces/primeng#6707]
This is less of a bug as a question:

In the application I'm building, we have p-tables inside tabs.  These p-tables all use lazyLoad.   In order to load the table on demand, I have it setup that when you select a tab, it passes in lazyLoad value to set it true.   Works great in Chrome.

However, with IE11 (which I must support), the p-table loads, and the data displays, but the columns are not rendered correctly.  If I click on a row, etc... it triggers an update and then it displays correctly.

Is there any function inside the table that I can invoke to basically tell it to re-render ?

Thanks!

**Comment by sgentile** [comment]
I've tried every change detection strategy that I can, to the point it's like a huge hack.

To reproduce, put the table inside a tab, fetch the data for it on tab select, fails to render correctly.

<img width="1295" alt="screen shot 2018-10-18 at 10 31 03 am" src="https://user-images.githubusercontent.com/132404/47161914-f45ba280-d2c0-11e8-8094-89312fad8fa5.png">

clicking on a row, or toggling a column, snaps right into place.   I call detect changes after the fetch

ie

```
this.dataTableService.fetchClientSideData(this.contactQueryUrl).subscribe(result => {
        this.customerContacts = result.items as [];
        this.changeDetectorRef.detectChanges();
      });
```

**Comment by sgentile** [comment]
fyi - this happens if I don't use lazyLoad as well - just tried it.

**Comment by cagataycivici** [comment]
Use forum for questions and support requests please, also a stackblitz template would help to replicate if you are sure this is a bug from our side.

**Comment by sgentile** [comment]
unfortunately stackblitz doesn't appear to support IE11 - code runs fine on chrome but not IE11

**Comment by sgentile** [comment]
ie  https://angular-6-primeng.stackblitz.io/

**Comment by JacobSiegle** [comment]
Seems OK to me - 
![ie-11-ok](https://user-images.githubusercontent.com/5766272/47598045-fc1fe480-d95b-11e8-85e0-5da034d49992.png)

**Comment by cagataycivici** [comment]
Please use forum for support requests and questions.
