### ISSUE TITLE
Datatable pageLinks not in sync when using both top & bottom paginators

### ISSUE THREAD

**Issue by tbertran** [primefaces/primeng#671]
When changing the selection on the `rowsPerPageOptions` dropdown on the top paginator, the number of `pageLinks` is adjusted on top paginator, but not on bottom one.  
 The reverse is also true (bottom paginator change not reflected in top paginator).

**Comment by cagataycivici** [comment]
@Mrtcndkn , review please.

**Comment by cagataycivici** [comment]
We're unable to replicate.

**Comment by tvblomberg** [comment]
I am seeing the exact same issue.

` <p-dataTable #dt [(selection)]="selectedCases" [paginatorPosition]="both" [value]="incidents" [rows]="1" [paginator]="true" 
            [pageLinks]="5" [responsive]="true" [rowsPerPageOptions]="[1, 2, 3, 4, 5]" [stacked]="stacked" [globalFilter]="gb"
            reorderableColumns="true">
            <header>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="table-controls pull-right">
                            <input #gb type="text" class="form-control input-sm" placeholder="Filter" />
                        </div>
                    </div>
                </div>
            </header>
            <p-column [style]="{'width':'38px'}" selectionMode="multiple"></p-column>
            <p-column styleClass="col-button" field="casenumber" header="Case #" [sortable]="true">
                <template let-case="rowData">
                    <a (click)="viewCase(case.casenumber)" style="color: #337ab7;">{{case.casenumber}}</a>
                </template>
            </p-column>
            <p-column field="facilitycompany" header="Company Name" [sortable]="true"></p-column>
            <p-column field="damageaddress" header="Address" [sortable]="true"></p-column>
            <p-column field="damagestreet" header="Street" [sortable]="true"></p-column>
            <p-column field="damagecity" header="City" [sortable]="true"></p-column>
            <p-column field="damagecountyid" header="County" [sortable]="true"></p-column>
            <p-column styleClass="col-button" field="damagedt" header="Incident Date" [sortable]="true">
                <template let-case="rowData">
                    <span>{{case.damagedt | customdate}}</span>
                </template>
            </p-column>
            <p-column field="status" header="Status" [sortable]="true"></p-column>
            <p-column styleClass="col-button">
                <template let-case="rowData">
                    <button (click)="viewReports(case.casenumber)" class="btn btn-success"><i class="fa fa-list" aria-hidden="true"></i> Reports</button>
                </template>
            </p-column>
        </p-dataTable>`

**Comment by rklempert** [comment]
I have the same issue. I am using [lazy]="true" and "both." Showing 10 links and on the first page of results and increasing rows from 10 to 100, changes to fewer number of links only in the paginator in which the dropdown was changed.  If selecting rows from 10 to 100 on a page other than first, like 2nd or 3rd page of results, everything works.
