### ISSUE TITLE
p-calendar: tab key should focus the next tabbable element

### ISSUE THREAD

**Issue by pfms84** [primefaces/primeng#6710]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Waiting Time: ~8 weeks.

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**

When using a non-inline p-calendar, the tab key focus the first anchor to switch months and then closes the overlay, leaving the application without any focused element.
 
**Expected behavior**

The tab key should focus the next tabbable element

**Minimal reproduction of the problem with instructions**

Use a p-calendar
Focus the input to show the calendar
Press the tab key

* **Angular version:** 6.1.2

* **PrimeNG version:** 6.1.2

**Comment by Pikadili83** [comment]
I have the same problem on Firefox (primeng 7.0.0-beta.1). It works fine on Chrome.

**Comment by Mysame** [comment]
Duplicates #6270

**Comment by kravda** [comment]
> 
> 
> Duplicates #6270

6270 is closed, but I've got it on last version

**Comment by bappana** [comment]
The issue exists in primeng version: 7.1.3 as well.

**Comment by cagataycivici** [comment]
Dup of 6270
