### ISSUE TITLE
Schedule: not working with Fullcalendar imported as ES6 module

### ISSUE THREAD

**Issue by sque89** [primefaces/primeng#6713]
**I'm submitting a
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-bonncn

**Current behavior**
* if the p-schedule module is used in combination with ES6 import of fullcalendar, the p-schedule is throwing an error "ERROR ReferenceError: FullCalendar is not defined"
* i assume the issue is caused by this fact, mentioned in the fullcalendar docs **"The above example assumes you are using a <script> tag that supplies the FullCalendar browser global. The following example is the same thing, but written as an ES6 module:"** (https://fullcalendar.io/docs/v4/initialization)

**Expected behavior**
* p-schedule is usable also with ES6 imported fullcalendar

**What is the motivation / use case for changing the behavior?**
PrimeNG Schedule is a great tool and i would love to continue using it in the latest version

**Please tell us about your environment:**
Window 7, Itellij PhpStorm, Yarn

**Angular version:**
6.1.9

**PrimeNG version:**
6.1.5

**Browser:**
all 

**Language:**
TypeScript 2.10.0

* **Node (for AoT issues):** `node --version` =  8.10.0

**Comment by DYudin** [comment]
@sque89 I have the same issue...
Is there any workaround for now ?

**Comment by sque89** [comment]
> @sque89 I have the same issue...
> Is there any workaround for now ?

I dont have one right now. As Fullcalendar 4 is in alpha-state currently, i cannot use it in production anyways, so i will wait until its finished and hope that this issue will be solved as well then.

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists wit|h the new version please create a new issue with our stackblitz template.
