### ISSUE TITLE
p-overlayPanel wrapping a p-panelMenu problem

### ISSUE THREAD

**Issue by crisev** [primefaces/primeng#6720]
**I'm submitting a bug report  

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/angular-jkw7bt

**Current behavior**
When I put p-panelMenu inside a p-overlayPanel it has this issue:

- as soon as the overlay gets hidden all the nodes with children inside the panelMenu are expanded even if "multiple=false"

- panelMenu seem to consider the nodes as collapsed as it takes two clicks on each node to make it display as closed

- the problem happens only on the first hiding of the overlay menu; If all nodes are closed by clicking them twice, the problem no longer happens after

**Expected behavior**
not to expand the entire menu on hiding the overlay

**Minimal reproduction of the problem with instructions**
On stackblitz example click Show--> hide the overlay --> click Show again

* **Angular version:** 6.X
* **PrimeNG version:** 6.X

I have also created a question here: https://stackoverflow.com/questions/52876264/primeng-overlaypanel-wrapping-panelmenu

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists wit|h the new version please create a new issue with our stackblitz template.
