### ISSUE TITLE
Toast component doesn't support hideTransitionOptions and showTransitionOptions properties (even though it is in the docs)

### ISSUE THREAD

**Issue by kito99** [primefaces/primeng#6725]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Waiting Time: ~8 weeks.

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 6.X

* **PrimeNG version:** 6.1.4

Documentation mentions hideTransitionOptions and showTransitionOptions properties, but they are not actually supported in the component.

**Comment by yigitfindikli** [comment]
Seems to be working, can i see your code ?

**Comment by aboros-mac** [comment]
@kito99 I had this issue as well. Make sure you update to the latest primeng. I had version primeng-6.1.4, and the tags were not supported, but after I updated to primeng-6.1.5, they were working.

**Comment by kito99** [comment]
Ah, that's probably it, @ambros-mac! Thanks!
