### ISSUE TITLE
Add rowSelectable property to DataTable

### ISSUE THREAD

**Issue by gregAnd** [primefaces/primeng#6736]
[x ] bug report => Search github for a similar issue or PR before submitting

I am facing a problem on PrimeNG TurboTable.

I started from the following example: https://www.primefaces.org/primeng/#/table/selection and more particularly from the Checkbox Selection example.

The only difference is that on some p-tableCheckbox I added a [disabled]="true"

> <p-tableCheckbox [value]="rowData" [disabled]="rowData.color==='orange'"></p-tableCheckbox>

![disabled checkbox](https://user-images.githubusercontent.com/40430885/47360318-856eb700-d6cf-11e8-8133-8948b22e5d4b.jpg)

This works very well if I select a disabled line it does not activate and can not be selected, but when I click on p-tableHeaderCheckbox all the lines are selected even the lines in disabled.

![all selected](https://user-images.githubusercontent.com/40430885/47360364-9c150e00-d6cf-11e8-9f34-2ac41d804223.jpg)

In addition, the selection also counts the lines in status disabled or it should only take lines with no status disabled I made an example on stackblitz : https://stackblitz.com/edit/angular-gnbsml?file=src%2Fapp%2Fapp.component.html

How to prevent tableHeaderCheckbox from also selecting disable lines?

Thank you in advance for your answers

**Comment by bomberblue07** [comment]
This issue persists in 7.0 and would help my users greatly if fixed please!

**Comment by ausshadu** [comment]
+1

Please add/fix this.

**Comment by francovegini** [comment]
+1

**Comment by falexandre** [comment]
+1

**Comment by jlwollinger** [comment]
+1

**Comment by knipers** [comment]
+1

**Comment by andersonbuzzi** [comment]
+1

**Comment by sidneibiz** [comment]
+1

**Comment by doomevaristo** [comment]
+1

**Comment by maxonweb** [comment]
+1

**Comment by HieuTrinh83** [comment]
+1

**Comment by grozdanova** [comment]
+1

**Comment by yelhouti** [comment]
+1

**Comment by yelhouti** [comment]
A PR has been made to fix this, in the meantime it's available here: https://github.com/yelhouti/primeng/releases/download/8.0.2/primeng-8.0.3-SNAPSHOT.tgz

**Comment by kramar** [comment]
Hi guys, can you please tell is there date when PR from @yelhouti plan to be merged?

**Comment by yelhouti** [comment]
@kramar they are not planning to merge it, looking for a better alternative

**Comment by tytusplanck** [comment]
Any updates on this issue?

**Comment by morula** [comment]
The setting "pSelectableRowDisabled" should also be taken into account.

**Comment by jyoti1904** [comment]
any updates on this issue?

**Comment by hilfor** [comment]
+1

**Comment by hilfor** [comment]
A workaround that we are using is to have an additional "selected" list in the component and updating it with `(onRowSelect)="rowSelected($event)"` and `(onRowUnselect)="rowUnselected($event)"`

While on the row checkbox we have the following:

```
<p-tableCheckbox
   [value]="rowData['disabled'] ? {} : rowData"
   [disabled]="rowData['disabled']">
</p-tableCheckbox>
```

But this workaround will not mark the header checkbox (select all) in case all of the enabled rows were selected

**Comment by bhavan0** [comment]
> A workaround that we are using is to have an additional "selected" list in the component and updating it with `(onRowSelect)="rowSelected($event)"` and `(onRowUnselect)="rowUnselected($event)"`
> 
> While on the row checkbox we have the following:
> 
> ```
> <p-tableCheckbox
>    [value]="rowData['disabled'] ? {} : rowData"
>    [disabled]="rowData['disabled']">
> </p-tableCheckbox>
> ```
> 
> But this workaround will not mark the header checkbox (select all) in case all of the enabled rows were selected



Any update on when this feature will be introduced?
 Or if any workaround is available currently without this drawback?

**Comment by ReinhardFreiler** [comment]
Hi, 
is there going to be a solution anytime soon?

**Comment by JulianFarhi** [comment]
Hi,
Any updates on this issue?

**Comment by maicongodinho1** [comment]
Hi,
any solution anytime soon?

**Comment by drvive** [comment]
Hi,
any update on this?

**Comment by guoshuke** [comment]
waiting......

**Comment by larreadg** [comment]
Hi,
Any updates?

**Comment by s0nnyhu** [comment]
Hello, up

**Comment by mertsincan** [comment]
Hi all,

You can use rowSelectable property for this issue.
```
<p-table [value]="products" [(selection)]="selectedProducts5" dataKey="code" responsiveLayout="scroll" [rowSelectable]="isRowSelectable">
    <ng-template pTemplate="header">
        <tr>
            <th style="width: 3rem">
                <p-tableHeaderCheckbox></p-tableHeaderCheckbox>
            </th>
            <th style="min-width:200px">Code</th>
            <th style="min-width:200px">Name</th>
            <th style="min-width:200px">Category</th>
            <th style="min-width:200px">Quantity</th>
        </tr>
    </ng-template>
    <ng-template pTemplate="body" let-product>
        <tr>
            <td>
                <p-tableCheckbox [value]="product" [disabled]="isOutOfStock(product)"></p-tableCheckbox>
            </td>
            <td>{{product.code}}</td>
            <td>{{product.name}}</td>
            <td>{{product.category}}</td>
            <td>{{product.quantity}}</td>
        </tr>
    </ng-template>
</p-table>
```
```
 isRowSelectable(event) {
        return !this.isOutOfStock(event.data);
    }

    isOutOfStock(data) {
        return data.inventoryStatus === 'OUTOFSTOCK';
    }
```
I added a new demo related to this.


https://user-images.githubusercontent.com/11868120/147199067-b973a051-3a8c-4a71-ae76-83f83165bcc5.mov


Best Regards,

**Comment by s0nnyhu** [comment]
Amazing, do you know when 13.0.4 will be available on npm?

**Comment by s0nnyhu** [comment]
what argument takes  [rowSelectable]="isRowSelectable(argument here)" ?

**Comment by alimdi** [comment]
Is it possible the have a row always selected, no matter what ?
