### ISSUE TITLE
DragDrop: ability to drag items over any input elements

### ISSUE THREAD

**Issue by Y-Taras** [primefaces/primeng#6738]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-nuk5s9

**Current behavior**

If I drag "pDraggable" div on any input,  then it adds value to input element and copy icon is is shown
on hover.

**Expected behavior**

If I drag draggable  div on any input,  then it emits no actions unless input is droppable element

**Minimal reproduction of the problem with instructions**

Move draggable item to input without pDroppable directive

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 6.1

* **PrimeNG version:** 6.1

* **Browser:** [ Chrome 70| Firefox 64|

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
