### ISSUE TITLE
Calendar with button - button is in position absolute

### ISSUE THREAD

**Issue by Etchelon** [primefaces/primeng#674]
Hello,
the following code:
`<div class="filters">
            <span class="label_">Dal</span>
            <p-calendar [(ngModel)]="fromDate" showAnim="slideDown" [showIcon]="true"></p-calendar>
            <span class="label_">al</span>
            <p-calendar [(ngModel)]="toDate" showAnim="slideDown" [showIcon]="true"></p-calendar>
        </div>
`
produces this:
![image](https://cloud.githubusercontent.com/assets/4141889/17207719/2249fa56-54b6-11e6-9c63-a9a0bbee969d.png)
instead of this, which I'd expect:
![image](https://cloud.githubusercontent.com/assets/4141889/17207760/4a446050-54b6-11e6-9e2e-4b5ad78ec9af.png)

I noticed the cause is that the blue icon is a button with display: absolute.

I thought: since Angular2 supports IE11+, and primeng is built for Angular2, and IE11 supports display flex...why don't you build your css using display flex? It would be much better and things like this would be very easy to fix.

**Comment by cagataycivici** [comment]
It should be resolved in recent releases, please try and drop a comment if issue persists, then we may reopen.

**Comment by sbley** [comment]
IMHO this is still an issue. The position of the calendar button should be `position: relative` instead of `position: absolute`. Absolute positioning makes it impossible to change the width of the input field as it produces the overlapping layout the original poster mentioned.
