### ISSUE TITLE
PrimeNG datatable infinite scroll issue.

### ISSUE THREAD

**Issue by kaushikdighe** [primefaces/primeng#6742]
I know there have been duplicates for this issue. Went through those but could not find an answer. 
**Problem:** facing problem while implementing infinite scroll for p-table. Not able to understand the calculation or formula(if any) used by primeNG to make infinite scroll work. So finally stuck to numbers given on their website. But my totalRecords are dynamic and always going to be different. So changed that. now i go to page 0, page 1 and then instead of going to page 2 i go to page 1 again. So basically the call for getting the data-set for page 1 is done twice. This was happening before as well but i stuck to their numbers now it is happening again coz my totalRecords changed. 

just for clarification this is my p-table tag if it helps:

**<p-table [columns]="tblCols" [value]="myReportsList" [scrollable]="true"
             [rows]="noOfRows" scrollHeight="200px" [virtualScroll]="true" (onLazyLoad)="getAdhocReportsList($event)"
             [lazy]="true" [virtualRowHeight]="28" [totalRecords]="totalRecords" [loading]="loading">
</p-table>**

with noOfRows = 20 and totalRecords are my totalRecords.

Kindly help me with this. Thank you.

**Comment by ammi1378** [comment]
can you provide a link, that forum is scary.

**Comment by asheikh-alivia** [comment]
And they don't event bother to reply on forum. I have seen a lot of questions and issues just lying there unanswered.
