### ISSUE TITLE
Draggable scope overwrites the clipboard in IE

### ISSUE THREAD

**Issue by mroskamp** [primefaces/primeng#6744]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-bm3bpj

**Current behavior**
In IE, when dragging an element with the pDraggable directive, whatever is on my clipboard gets replaced with the drag scope.

**Expected behavior**
Draggable elements in IE should behave the same way as in the other browsers. My drag item scope should not be placed on my clipboard.

**Minimal reproduction of the problem with instructions**
See: https://stackblitz.com/edit/github-bm3bpj

1. Copy something to your clipboard (maybe the active URL or something else on the page)
2. Paste it somewhere, to make sure the text is indeed on the clipboard
3. From the stackblitz, drag the "drag me" tile
4. Paste again and notice how it now pastes the drag scope, rather than what was previously on the clipboard

**What is the motivation / use case for changing the behavior?**
This leads to confusion and possibly lost data if the user copies something, then drags something in the UI. Users wouldn't expect dragging something to interfere with what's currently on the clipboard.

**Please tell us about your environment:**

* **Angular version:** 5.2.10
This is still reproducible in the stackblitz, on 6.1.2

* **PrimeNG version:** 5.2.6
This is still reproducible in the stackblitz, on 6.1.0

* **Browser:** [IE 11.345]

**Comment by cetincakiroglu** [comment]
Hi,

If the issue still exists with the latest PrimeNG version, please provide a StackBlitz example by using [PrimeNG Issue Template ](https://stackblitz.com/github/primefaces/primeng-issue-template) and re-open the issue.

Regards
