### ISSUE TITLE
Primeng p-dialog draggable and blockScroll does not work (primeng version 6.1.3)

### ISSUE THREAD

**Issue by quekqh** [primefaces/primeng#6745]
Anyone has an issue with the draggable and blockScroll options in primeng dialog? Doesn't seem to work, is it a bug?

<p-dialog header="Feedback" [(visible)]="displayFeedback" [blockScroll]="true" [draggable]="true">
</p-dialog>

**Comment by zfyzjzzl** [comment]
Similar problem, I use the 'maximizble' in my portal. It works fine till I click the maximize button, While the background scroll can not block again, and the content in the p-dialog is overflow.

<p-dialog header="work" [(visible)]="displayWork" [blockScroll]="true" [draggable]="true" [maximizable]="true">
content
</p-dialog>

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
