### ISSUE TITLE
Menubar diagonal selection

### ISSUE THREAD

**Issue by mcherb** [primefaces/primeng#6746]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-htgfyg

On the link above:
I cannot do this selection *File > New > Quit* directly (diagonal way). If i want to go to *Quit* item i have to travers all the items  *File > New > Project - Other - Open - Save -> Quit*

I tried to increase the hideDelay but it did not work.

**Please tell us about your environment:**
Linux/Mac; intellij idea

* **Angular version:** 5.2.11

* **PrimeNG version:** 5.2.7

* **Browser:** all

 
* **Language:** TypeScript 2.6.0

* **Node (for AoT issues):** `node --version` =   v10.0.0

**Comment by cagataycivici** [comment]
Menubar will be rewritten and we'll fix it along the way as behavior will be different.

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
