### ISSUE TITLE
Make TreeTable use expandedIcon and collapsedIcon

### ISSUE THREAD

**Issue by LGougerot** [primefaces/primeng#6747]
The `expandedIcon` and `collapsedIcon` in TreeNode are unused in TreeTable.

This feature was apparently implemented in previous version after issue #2269 but seems to have been lost in new 6.x TreeTable.

Can this behavior be reimplemented in new version ?

Thanks.

**Comment by namdien177** [comment]
I'm also facing this issue and eventually come up with a hardcore checking
`
<ng-container *ngIf="rowNode['level'] === 0 && !rowNode['node'].expanded">
     <i class="ml-1 pi pi-folder"></i>
</ng-container>
<ng-container *ngIf="rowNode['level'] === 0 && rowNode['node'].expanded">
     <i class="ml-1 pi pi-folder-open"></i>
</ng-container>
`
with
`<ng-template let-rowData="rowData" let-rowNode pTemplate="body">`
and
`<tr [ttRow]="rowNode" [ttSelectableRow]="rowNode">`

It's a bit late but hopefully newcomer won't be suffering from this simple task...

**Comment by cagataycivici** [comment]
New treetable is template based so these icon properties are not used. You may add them or any icon of your choice using template.

**Comment by sh977218** [comment]
Does the template support expandedIcon/collapsedIcon? i.e. When I try to use pTemplate, those expand/collapse icons are always default one, doesn't matter what I give.
