### ISSUE TITLE
p-schedule onViewRender is called twice on view change

### ISSUE THREAD

**Issue by makbari** [primefaces/primeng#6750]
**I'm submitting a bug**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

When view changed from Month to Day, onViewRender is called twice. on the first call, I get all the schedules, and I got the schedules. 
However, then it calls for second time, I got my schedules from api (schedules are the same as the previous) but on view all schedules are removed and there is nothing to show on p-schedule. 

**Expected behavior**

On view change, it should not called for second time.

* **Angular version:** 4.3.3

* **PrimeNG version:** 4.3.0

* **Fullcalendar version:** 3.7.0

**Comment by yigitfindikli** [comment]
Schedule is deprecated, you can use FullCalendar (https://www.primefaces.org/primeng/#/fullcalendar).
