### ISSUE TITLE
TurboTable responsive with colgroup breaks column width

### ISSUE THREAD

**Issue by zeatan** [primefaces/primeng#6757]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/primeng-table-responsive-with-colgroup

**Current behavior**

TurboTable  with colgroup(for column style, resizing)  in responsive mode, `td`'s width 100% style ignored.
So, column displayed narrowly.

**Expected behavior**

In responsive mode, remove colgroup automatically.

**Minimal reproduction of the problem with instructions**

See stackblitz

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 6.1.10

* **PrimeNG version:** 6.1.5

* **Browser:** [Chrome 69| Firefox 61]

 
* **Language:** [TypeScript 2.9]

* **Node (for AoT issues):** `node --version` =

**Comment by dlarr** [comment]
Same problem...

**Comment by ykoitzsch** [comment]
exactly...there is also a problem when using the template "caption". It removes 50% of the table header in small device mode.

**Comment by lbatistag80** [comment]
Same problem, any update???
