### ISSUE TITLE
[p-tree] Focus on a concrete node of the tree

### ISSUE THREAD

**Issue by mgutbor** [primefaces/primeng#6759]
Hi all,

and thanks in advance for this awesome library.

In [p-tree](https://www.primefaces.org/primeng/#/tree):

will be possible to focus on a concrete node? If that was possible, how could I do that?

Thanks again for your help.

**Comment by mgutbor** [comment]
could anyone help me with this one???

thanks in advance.

**Comment by cagataycivici** [comment]
Please use forum for support requests, thank you.
