### ISSUE TITLE
Calendar timepicker - how to change the hour/minute element to be an input to allow for keyboard input by the user

### ISSUE THREAD

**Issue by gkimpson** [primefaces/primeng#6764]
I am using PrimeNG 4.2.4 with the Calendar (with date & timepicker) and it works really well - however I would like to know if it possible to do the following :

When using the arrows above and below both the hour and minutes in the timepicker it changes the number accordingly - however I would like to make both of these hours and minutes inputs to make it easier for a user to change the number by typing this in rather than just clicking the arrows (as this can be tedious if you are trying to go from 00 mins to 30 mins you would need to click 30 times (which is not fun)

Is there any easy simple way to do this using the existing 4.2.4 plugin (or has anyone else found this problem and made a custom solution?

**Comment by cagataycivici** [comment]
Please use forum for support requests and questions, thank you.
