### ISSUE TITLE
p-dropdown doesn`t update options array

### ISSUE THREAD

**Issue by Mynken** [primefaces/primeng#6766]
I'm submitting a p-dropdown [options] bug:
```
[X ] bug report
[X ] feature request
```
**Stackblitz Case (Bug Reports)**
https://stackblitz.com/github/nbwiamqn

**Current behavior**
When I change the options array- p-dropdown didn`t see updated array.

**Expected behavior**
When I change the options array- p-dropdown must see updated array.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows, VS Code.

* **Angular version:**
6.1.10

* **PrimeNG version:**
 "primeng": "^6.1.5"

* **Browser:**: all 
 
* **Language:** 
 "typescript": "2.9.2",
 "module": "es2015"

* **Node (for AoT issues):** `node --version` = v8.12.0  

***stackblitz.com currently not working for me, so here is code:
App.component.ts:

```
import { Component, OnInit } from '@angular/core';
import {DropdownModule} from 'primeng/dropdown';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent implements OnInit {
  languages: any;
  language: any;
  test() {
    console.log(this.languages);
     this.languages[0].name = 'New language';
  }
  ngOnInit(): void {
    this.languages = [
      {name: 'English', value: 'en'},
      {name: 'Poland', value: 'pl'},
      {name: 'Ukrainian', value: 'ua'},
      {name: 'Russian', value: 'ru'}
  ];
  }
}
```
App.component.html:
```

<div>

 <p-dropdown [options]="languages" [(ngModel)]="language" optionLabel="name" (onHide)="test()"></p-dropdown>
</div>
<pre>{{languages | json}}</pre>
<button (onclick)="test()">Change language</button>
```

**Comment by cagataycivici** [comment]
You have to create a new array instead of modifying existing one, easiest way is using the spread operator so that change detection of angular is triggered.
