### ISSUE TITLE
Primeng Multiselect Scroll not working on focus out

### ISSUE THREAD

**Issue by jigsshah** [primefaces/primeng#6767]
Hi,

I am using following multiselect plugin as it is, without any modification. 

https://www.primefaces.org/primeng/#/multiselect

In my implementation, when the user clicks outside the dropdown, it gets closed as expected. But when the user opens the dropdown again, the scrollbar stays as it was. However I verified it on the official site and it is working fine. 

Here is pseudo code for the same:

 ```
<p-multiSelect [options]="optionslist" styleClass="customDropdown" [resetFilterOnHide]="true" name="preferences" 
            [(ngModel)]="selectedOption" defaultLabel="Select Option" [style]="{'minWidth':'14em'}"></p-multiSelect>
```
css for the same

`.customDropdown {
    background: #ffffff;
    border: 1px solid #bfb8af;
    border-radius: 0.25em;
    height: 35px !important;
    position: relative;
}`

Thanks & Regards,
Jigar

**Comment by JacobSiegle** [comment]
Please create a stack-blitz replicating the issue. I did not see the issue when pasting the code you provided in stack-blitz.

**Comment by jigsshah** [comment]
Hi JacobSiegle,
Thanks for taking time and looking into the issue. As per your comment I have created a sample stack-blitz for the same. Please take look into the same and share your thoughts, the issue is still reproducible.

[https://angular-primeng-multiselect.stackblitz.io](https://angular-primeng-multiselect.stackblitz.io)

Thanks & Regards,
Jigar

**Comment by JacobSiegle** [comment]
Thanks but you shared the embedded view meaning anyone using that link cannot see the code editor.

**Comment by jigsshah** [comment]
Hey, 
sorry my bad. Updated URL below:

[https://stackblitz.com/edit/angular-primeng-multiselect](https://stackblitz.com/edit/angular-primeng-multiselect)

Thanks

**Comment by JacobSiegle** [comment]
It seems like a bug with PrimeNG 6.0, I tried PrimeNG 6.1.5 and it works correctly. If you upgrade your PrimeNG version it will be fixed.

**Comment by jigsshah** [comment]
Hi,
Thanks for reply, just to confirm is there any workaround or so to achieve that apart from the version upgrade ?

Thanks,
jigar

**Comment by JacobSiegle** [comment]
I don't know an easy fix off the top of my head, I assume any fix would be a hacky workaround for this. 

The reason the scroll position resets in the newer version is that the panel popup is removed from the DOM. In the older versions the panel popup was just hidden and remained in the DOM.

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists wit|h the new version please create a new issue with our stackblitz template.
