### ISSUE TITLE
Disabled supports no function

### ISSUE THREAD

**Issue by enexusde** [primefaces/primeng#6769]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/nbwiamqn

**Current behavior**
disabled is not able to hold a function, disabled can only hold an static boolean.

**Expected behavior**
disabled can hold a function and evaluates the result in-time

**Minimal reproduction of the problem with instructions**
Step 1: create a component having a tab-menu
Step 2: in the tab-menu create two items: A and B
Step 3: disable item B using `disabled:true`.
Step 4: add this queryParam: 
  `id:()=>new Date()`
Step 5: change the `disabled:true` to `disabled: ()=>new Date().getDay()==0`
Compilation not possible!

**What is the motivation / use case for changing the behavior?**
The queryParams can change its value on tab-change. Also the disabled flag should change.

**Please tell us about your environment:**
Win64

* **Angular version:** 5.X
2

* **PrimeNG version:** 5.X
4.3.0

* **Browser:**
all
 
* **Language:** 
all

* **Node (for AoT issues):** 
8.12.0

**Comment by JacobSiegle** [comment]
I'm using the latest version of PrimeNG and the button component disabled but this works.

```
[disabled]="returnUserFn()">
returnUserFn(): boolean {
  return new Date().getDay() == 5;
} 
```

If it doesn't work for you please try to recreate your stack-blitz, it throws a 404 for me.

**Comment by enexusde** [comment]
Unable to move to latest version. Wontfix for 4.3 then.

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists wit|h the new version please create a new issue with our stackblitz template.
