### ISSUE TITLE
[p-tree] Expose an onNodeAdded and onNodeRemoved events

### ISSUE THREAD

**Issue by mcherb** [primefaces/primeng#6772]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
I want to scroll to the last element added/expended/selected on the p-tree component. Nowadays i put all the logic in a directive which works fine for expended and selected events. But for the new added nodes i have to do some special work in a business component (calling my directive to do the scroll manually after an element was added)

Having an onNodeAdded and onNodeRemoved events making things simple to reorganize

**Comment by cagataycivici** [comment]
Since you are adding and removing the nodes, it sounds better to handle it on your side rather than the component doing expensive calculations for change detection.
