### ISSUE TITLE
Active State for PanelMenu sub menus.

### ISSUE THREAD

**Issue by suraj021** [primefaces/primeng#6773]
I am submitting a 
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
I am just recreating this issue again to bring it to the notice. This issue was already created but was not solved but closed [#644](https://github.com/primefaces/primeng/issues/644l). 
It would be great if we have this feature in the next release.

**Comment by cagataycivici** [comment]
Added ui-state-active to the active submenus however with no default style as a design decision, still page authors may use "ui-state-active" class to apply styling.
