### ISSUE TITLE
dropdown width not correct when attachTo="body"

### ISSUE THREAD

**Issue by vimalraj-a** [primefaces/primeng#6776]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/primeng-dropdown-width-issue

**Current behavior**

Width includes a scroll bar width when `attachTo="body"`
**Expected behavior**

Before attaching to body add "overflow: hidden;" on body and then remove it after width is calculated

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

When I use it in forms not looking good with other controls
**Please tell us about your environment:**

* **Angular version:** 7.0.0

* **PrimeNG version:** 6.1.5

* **Browser:** all

 
* **Language:** TypeScript 3.1.3

* **Node (for AoT issues):** `node --version` =   NA

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
