### ISSUE TITLE
Numeric keypad (0-9) cannot be used for searching in dropdown

### ISSUE THREAD

**Issue by fbascheper** [primefaces/primeng#6777]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewEd in detail and assisted.

https://stackblitz.com/edit/stackblitz-primeng-dropdown-numpad

This is the simplest adaptation from the city dropdown in primeng demo.

**Current behavior**
A dropdown entry (e.g. city) beginning with a number cannot be selected from the numeric keypad, only from the main keyboard (i.e. those just below the function keys in a standard QWERTY keyboard).

**Expected behavior**
It should be possible to select an entry beginning with a number from a numeric keypad

**Minimal reproduction of the problem with instructions**
See stackblitz, selection is not possible with numeric keypad.

**What is the motivation / use case for changing the behavior?**
More flexible keyboard entry.

**Please tell us about your environment:**
Windows 8.x

* **Angular version:** 6.1.x

* **PrimeNG version:** 6.1.5

* **Browser:** all
 
* **Language:** all

* **Node (for AoT issues):** `node --version` =   8 LTS

**Comment by jasperbosch** [comment]
On row 821 of dropdown.ts it says:
`const char = String.fromCharCode(event.keyCode);`
this results in a wrong char when numpad0 is pressed.
Why not use `event.char`?!
