### ISSUE TITLE
Missing "readonly: boolean;" on class "MultiSelect" declaration

### ISSUE THREAD

**Issue by Macadoshis** [primefaces/primeng#6778]
Please add ``readonly: boolean;`` on class ``export declare class MultiSelect``.

It's delclared as ``@Input()`` in concrete implementation, but not on the declaration, mpaking the property invisible when extending PrimeNg's _MultiSelect_ for ``CustomMultiSelect`` purpose.

**Comment by yigitfindikli** [comment]
Unable to replicate with latest PrimeNG, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
