### ISSUE TITLE
pDefer support for scrollable elements

### ISSUE THREAD

**Issue by sachingiter** [primefaces/primeng#6781]
we are trying to use pDefer directive but it only works when there is a scroll on body if i remove the overflow: scroll from body and give scrolling to some div inside body then it does not works

**Comment by tibinvpaul** [comment]
Hey @cagataycivici - do we have a plan to support this feature? Thank you.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
