### ISSUE TITLE
Checkbox is missing `position: relative`

### ISSUE THREAD

**Issue by aanklewicz92** [primefaces/primeng#6785]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Waiting Time: ~8 weeks.

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
In my pretty much complicated components stack (that's why I can't provide example) I encountered issue related to scrolling and checkbox. When I click on checkbox, margin-top of main container gets broken - is ignored. My colleague found out that I can easily fix issue by adding `position: relative` to `.ui-chkbox`. Then I confirmed that radio button used in that exact place works, but when I disable it's `position: relative` it causes the same issue.

**Expected behavior**
Checkbox should not breake margin-top.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10, VS Code, npm, local project

* **Angular version:** 6.0.7

* **PrimeNG version:** 6.1.0

* **Browser:** all

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists wit|h the new version please create a new issue with our stackblitz template.
