### ISSUE TITLE
PrimeNG dropdown, scaling bug

### ISSUE THREAD

**Issue by AdamMalec** [primefaces/primeng#6790]
## There are some problems when scaling PrimeNG dropdown

Found a library level bug.
Can tell me how can I solve this problem?

![promengdrop](https://user-images.githubusercontent.com/25156746/47720742-a8651200-dc5f-11e8-9ffe-d87c957eb914.PNG)
![promengdrop2](https://user-images.githubusercontent.com/25156746/47720754-b0bd4d00-dc5f-11e8-9f5d-cd72ceb4de15.PNG)

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists wit|h the new version please create a new issue with our stackblitz template.
