### ISSUE TITLE
Error when use [(ngModel)] in <p-dropdown>

### ISSUE THREAD

**Issue by RicardoJCP** [primefaces/primeng#6801]
Please close this ticket!

**NOT A BUG**

Can't bind **ngModel** in the `p-dropdown` component.

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
It throws an error

**Expected behavior**
Should work properly, using **[(ngModel)]** for two way binding 

**Minimal reproduction of the problem with instructions**
Include `<p-dropdown [options]="cities1" [(ngModel)]="selectedCity1"></p-dropdown>`

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
 - Windows 10
 - Visual Studio Code 1.28.2
 - Google Chrome 70

* **Angular version:** 7.0.3
 - Angular CLI 7.0.3
 - Angular Modules 7.0.1

* **PrimeNG version:** 7.0.0-beta.1
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** 
```
"engines": {
    "node": "8.12.0",
    "npm": "6.4.1"
  }
```

**Comment by RicardoJCP** [comment]
It's not a bug, it was missing the import of **FormsModule from** `@angular/forms`

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.
