### ISSUE TITLE
Table: Dropdowns in header row hidden below grid rows when resizableColumns=true

### ISSUE THREAD

**Issue by nsarris** [primefaces/primeng#6806]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/angular-pnxnw8

**Current behavior**

Dropdowns in header row (to be used as filters) are hidden below grid rows when resizableColumns=true (works as expected when it's false)

**Expected behavior**

Dropdowns should float over the grid rows

**Minimal reproduction of the problem with instructions**

In the demo click the dropdown button the brand or color dropdown filter

**What is the motivation / use case for changing the behavior?**

We are evaluating switching from a competior product to primeng. Dropdown filters with resizing is a hard requirement

**Please tell us about your environment:**

Windows OS / VsCode or StackBlitz

* **Angular version:** 7.02

* **PrimeNG version:** 6.1.5 and 7.0.0-beta.1

* **Browser:** Chrome/ FireFox / IE
 
* **Language:** [TypeScript 2.7 and 3.1]

**Comment by gmarab** [comment]
the same problem also with scrollable = true

**Comment by cagataycivici** [comment]
This is expected, you may try removing overflow or set appendTo="body" on dropdown.
