### ISSUE TITLE
CalendarModule failing the Karma test ´[object ErrorEvent] thrown´

### ISSUE THREAD

**Issue by jorgekg** [primefaces/primeng#6807]
**I'm submitting **  (check one with "x")
```
[ x ] bug report => bug, ´[object ErrorEvent] thrown´ into CalendarModule
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
In the Karma test, when the component has CalendarModule, the test fails. However, the error reports nothing, just '[ErrorEvent object]'.
I already had components with the same error, but imports from the subcomponent were missing.

* **Angular version:** 6.1.2

* **PrimeNG version:** 6.1.3

* **Browser:** [all] 

* **Karma:** 1.7.1

**Comment by marlonrp** [comment]
+1

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG.
