### ISSUE TITLE
DataTable: sorting null not properly working

### ISSUE THREAD

**Issue by mleonhartsberger** [primefaces/primeng#681]
when sorting a column which contains some rows with "value is null", the sort algorythm just stops.

it could be solved by adding null checks at
https://github.com/primefaces/primeng/blob/master/components/datatable/datatable.ts#L575

![image](https://cloud.githubusercontent.com/assets/20722294/17245211/c0b2dc88-5585-11e6-97ae-8f9116098df0.png)

**Comment by edangerfield** [comment]
I experience the same.

**Comment by hzach** [comment]
+1

**Comment by ctrl-brk** [comment]
Same issue still exists int multisort mode

**Comment by afras21** [comment]
Yeah the actual problem is null property is string and others are numbers .... change them to string it ll work fine
