### ISSUE TITLE
Prime Ng p-table is not supporting virtual scroll and column filters

### ISSUE THREAD

**Issue by pranoycubane** [primefaces/primeng#6811]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[x] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://nbwiamqn.github.stackblitz.io

**Current behavior**
Filter dropdown is not working as expected like below demo

**Expected behavior**
https://www.primefaces.org/primeng/#/table/filter
Filter should work like All colors dropdown filter

**Minimal reproduction of the problem with instructions**
https://nbwiamqn.github.stackblitz.io
Click on the dropdown filter, and it should show options for that dropdown to filter data

**What is the motivation / use case for changing the behavior?**
Expected use case not working

**Please tell us about your environment:**
Ubuntu 16, MAC high sierra, Intellij, NPM, Tomcat

* **Angular version:** 5.X
Angular 6

* **PrimeNG version:** 5.X
Prime NG 6.1.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript : 2.9.2

* **Node (for AoT issues):** `node --version` =   9.5

**Comment by reneszabo** [comment]
+1

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists wit|h the new version please create a new issue with our stackblitz template.
