### ISSUE TITLE
Theming links are all broken on website

### ISSUE THREAD

**Issue by hughanderson4** [primefaces/primeng#6819]
Trying to get started theming PrimeNG.  There are numerous INVALID links on PrimeNG website.

From PrimeNG homepage: 
https://www.primefaces.org/primeng/#/

There is a THEMES menu item in top right.  Most of the options in this menu DO NOT WORK.

In there is a GUIDE link.  It does not function.  I cannot find any guide about Theming.

All of the themes listed in this menu seem to be links that do not function to do anything.  The theme of the demo site does not dynamically change when I select any theme in the menu.

Trying to see a DEMO of some of the FREE themes.  I cannot find any information about any free themes anywhere on PrimeNG website.

Please fix the THEMES section of PrimeNG website to be more user friendly to someone who is getting started to apply one of the stock themes to my application.  I need to demo the themes in order to make a selection.

**Comment by hughanderson4** [comment]
I noticed also on this page:

https://www.primefaces.org/primeng/#/dialog

Under the header for *Styling* it says "Following is the list of structural style classes, for theming classes visit theming page."

This links to the theming page but there is no list of structural style classes there, as implied by the link text.  Just the ads for PrimeNG paid products.

**Comment by cagataycivici** [comment]
You need to be on a page with PrimeNG components to see the difference between free themes.

**Comment by hughanderson4** [comment]
Is there not a theming guide?  As implied by the docs on the TurboTable page, I was hoping to find some list of classes for theming.  How is developer instructed to theme their app for their requirements?  The Guide page links not to a guide.
