### ISSUE TITLE
Feature Request: Tree should always expand to show the selected item

### ISSUE THREAD

**Issue by JakeSummers** [primefaces/primeng#682]
I am using the Tree widget, with single selection.  I have a tree that looks like this: 

```
├── breakfast
│   ├── bacon
│   ├── coffee
│   │   └── cream
│   └── eggs
├── diner
│   ├── beer
│   └── burger
│       ├── cheese
│       ├── ketchup
│       └── tomato
└── lunch
```

When my app opens, the tree is collapsed: 

```
├── breakfast
├── diner
└── lunch
```

Suppose I set the selection on the tree (using the selection input property), to ketchup.  

The selection will be properly applied, however, the tree is not expanded to show the selected node.  My expectation was that the tree would expand like this: 

```
├── breakfast
├── diner
│   ├── beer
│   └── burger
│       ├── cheese
│       ├── ketchup *selected*
│       └── tomato
└── lunch
```

How can I:

a) Expand the tree to show to the selected node? 
b) Expand and close arbitrary nodes?

**Comment by JakeSummers** [comment]
This issue seems related to this: https://github.com/primefaces/primeng/issues/261

**Comment by ZIOLele** [comment]
Hi,
i've solved this very issue extending the base tree and uitreenode, see attached files

[tree.zip](https://github.com/primefaces/primeng/files/399033/tree.zip)

**Comment by JakeSummers** [comment]
@ZIOLele - Any plans to submit a pull request to add this functionality?

**Comment by JakeSummers** [comment]
@ZIOLele - I am going to incorporate similar changes directly into the tree component and submit a merge request.  Started making my changes here: 

https://github.com/JakeSummers/primeng/tree/programaticTreeExpansion

Will submit a merge request when they are completed.

**Comment by cagataycivici** [comment]
The PR is merged so this issue should be fixed.
