### ISSUE TITLE
SplitButton & TieredMenu - double click on item reloads the page

### ISSUE THREAD

**Issue by aurelianv** [primefaces/primeng#6822]
**Current behavior**
Double click any of the splitbutton's items, it will reload the page.

**Expected behavior**
On both disabled and enabled items the double click should not trigger the refresh of the entire page.

**Minimal reproduction of the problem with instructions**
https://www.primefaces.org/primeng/#/splitbutton
Double click any of the splitbutton's items, it will reload the page.

**What is the motivation / use case for changing the behavior?**
SplitButton - double click on item reloads the page, for both enabled and disabled items.

**Please tell us about your environment:**
Win64

* **Angular version:** 6.1.0

* **PrimeNG version:** 6.1.5

* **Browser:** [all]
 
* **Language:** [all]

**Comment by shogogan** [comment]
Not only on Splitbutton, but on Tiered menu.
It doesn't just reloads the page, it sends the page back to the root of the application "/#/"

**Comment by tiagodws** [comment]
@cagataycivici Could you take a look, please? :)

**Comment by francovegini** [comment]
+1

**Comment by elizeugba** [comment]
+1

**Comment by brenonaraujo** [comment]
+1

**Comment by falexandre** [comment]
+1

**Comment by philipstefan** [comment]
+1

**Comment by shogogan** [comment]
Hmm, interesting, i opened a pull request with the solution, and it was completelly ignored.
