### ISSUE TITLE
autocomplete does not close on second dropdown click.

### ISSUE THREAD

**Issue by gustavomerini** [primefaces/primeng#6826]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Expected behavior**

i would expect that the first click on the dropdown would display the suggestions and if the user clicks the dropdown again, it would close the dropdown, maybe it should be an option within the component that would allow me to set enable or disable, would help me a lot for customization. 
In my opnion it should work just like the dropdown component: https://www.primefaces.org/primeng/#/dropdown, it already works this way.

**Minimal reproduction of the problem with instructions**

https://www.primefaces.org/primeng/#/autocomplete here there is an autocomplete with the dropdown,
Just click one time on the dropdown, than click another time to check out that it does not close on the second click

**What is the motivation / use case for changing the behavior?**

My client reported that he would like that the second click on the dropdown would close the search, like it already happens when you click outside the component.

**Please tell us about your environment:**

vscode

* **Angular version:** 6.X

* **PrimeNG version:** 6.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   8.12

**Comment by cagataycivici** [comment]
No plans to change the current behavior, if there is more demand we'll reconsider making this an option.

**Comment by tiagodws** [comment]
@cagataycivici I need it too. Having this option would be awesome from an usability perspective.

**Comment by ericcastoldi** [comment]
@cagataycivici pretty please?

**Comment by csvinhal** [comment]
+1

**Comment by elizeugba** [comment]
+1

**Comment by luankevinferreira** [comment]
@cagataycivici that's I'm talking about! :)

**Comment by falexandre** [comment]
+1

**Comment by francovegini** [comment]
+1

**Comment by sidneibiz** [comment]
+1

**Comment by matheushr97** [comment]
+1

**Comment by knipers** [comment]
@cagataycivici I need this too, please reconsider

**Comment by LeonardoHabitzreuter** [comment]
+1

**Comment by WagnerReetz** [comment]
+1

**Comment by WagnerReetz** [comment]
+1

**Comment by leoreichert** [comment]
+1

**Comment by jjaraujo** [comment]
+1

**Comment by elitonds** [comment]
+1

**Comment by jlwollinger** [comment]
+1

**Comment by viniciuskr** [comment]
+1

**Comment by wallacetm** [comment]
+1

**Comment by aliniribeiroo** [comment]
+1

**Comment by luisesch** [comment]
+1
