### ISSUE TITLE
How do i add a button inside the multiselect component template?

### ISSUE THREAD

**Issue by theNotoriousHxc** [primefaces/primeng#6828]
I would like to add a button somewhere in the multiselect component so user can click that button instead of relying on the onChange event of the multiselect.

On the documentation, there are only a couple of pre-defined directive.

`pTemplate="selectedItems"` and `pTemplate="item"` to edit the template. How to i add custom html aside from those two. I would like to add the button besides the search input form.

Any thoughts?

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.
