### ISSUE TITLE
Feature Request: Add drag and drop support to the tree

### ISSUE THREAD

**Issue by JakeSummers** [primefaces/primeng#683]
I am looking into how to add drag & drop support for the following two use cases: 
1. Drag an element from a [Tree](http://www.primefaces.org/primeng/#/tree) and drop it into another element in the Tree.  
2. Drag an element from a [DataTabe](http://www.primefaces.org/primeng/#/datatable) and drop it into an element in the Tree.

At the moment PrimeNg has a [Drag and Drop](http://www.primefaces.org/primeng/#/dragdrop) module that allows you to attach a draggable handle or droppable element onto an element.  Unfortunately, I don't think I can use this with Trees because the treeNodes  not exposed.  

I think that I can make items in the DataTable draggable by using the [templating functionality](http://www.primefaces.org/primeng/#/datatabletemplating).

**Comment by JakeSummers** [comment]
I think that this may now be possible with PrimeNG 1.0.0-beta.13.  

This release allows you to provide a template to render your nodes like this (using @ContentChildren):

    <p-tree
        [value]="...">
        <div>some content</div> 
    </p-tree>

I think that it may be possible to add a [primeNg drag handle](http://www.primefaces.org/primeng/#/dragdrop) inside the ContentChildren.  Haven't tried this yet, but I think this should work.

**Comment by cyberrranger** [comment]
hi jake,

i search a solution for "Drag an element from a Tree and drop it into another element in the Tree."

can you help?

**Comment by JakeSummers** [comment]
Hi @cyberrranger ,

Until this functionality is added into primeNg you can workaround by using something like this:

```
<p-tree
	[value]="displayedRootNodes"
	selectionMode="single"
	[selection]="selection"
>
	<template let-node pTemplate type="default">
		<span
			pDraggable="treedragdrop"
			pDroppable="treedragdrop"
			(onDragStart)="onDragStart($event, node)"
			(onDragEnd)="onDragEnd($event, node)"
			(onDrop)="onDrop($event, node)"
			(onDragEnter)="onDragEnter($event, node)"
			(onDragLeave)="onDragLeave($event, node)"
		>
			{{node.label}}
		</span>
	</template>
</p-tree>
```

Jake

**Comment by cyberrranger** [comment]
thx, is working

**Comment by vas4oo** [comment]
Can you give the TypeScript too? My Drag and drop tree doesn't working...

**Comment by cyberrranger** [comment]
hi @vas4oo,

You have to implement the methods "onDrop, onDragStart, ..." yourself.

i work with a own rest api

`	onDragStart(event, node) {
		this.moveFile = node;
	}

	onDrop(event, target) {
		if (!this.moveFile || target.leaf) {
			return;
		}

		if (!this.moveFile.leaf) {
			// dont move root
			if (!this.moveFile.parent) {
				return;
			}

			if (target.parent == this.moveFile.uuid) {
				return;
			} else {
				// TODO path
			}

			this.adminService.moveGroup(this.moveFile.uuid, target.uuid);
		} else {
			this.adminService.moveItem(this.moveFile.uuid, this.moveFile.parent, target.uuid);
		}
	}`

**Comment by vas4oo** [comment]
I have made them but still not working...

**Comment by cyberrranger** [comment]
You need to remove and add it in the tree itself

**Comment by bryanhaines** [comment]
@cyberrranger Hello, I'm hoping that you can help me get this to work in my project. I have (onDragStart)="onDragStart($event, node)" on my tree template and 
onDragStart($event, node): void {
        this.selectedEquipment = node;
        console.log('onDragStart');
        console.log(this.selectedEquipment);
    }
in my component. 
When I attempt to drag, the onDragStart never fires. Any ideas?

**Comment by cyberrranger** [comment]
@bryanhaines have you more example code?

my ts class

`export class AdminHierarchy extends PARENT {
      moveFile: Hierarchy;
       onDragStart(event, node) {
                this.moveFile = node;
        }
}`
html show answer from @JakeSummers from 18 Oct 2016

**Comment by bryanhaines** [comment]
@cyberrranger Thanks for getting back to me. Here is my ts file:
export class BOMTreeComponent {
    @Input()
    set ID(ID: string) {
        this.buildTree(ID);
    }

    public equipmentLibrary: any[];
    public selectedEquipment = {};

    constructor(private bomTreeService: BOMTreeService) {
        //this.designId = this.sessionCacheService.lastSelectedDesignId;
    }

    onSelect($event): void {
        if ($event.node.leaf === false) {
            return;
        }
        this.selectedEquipment = $event.node;
        console.log(this.selectedEquipment);
    }

    onDragStart($event, node): void {
        if (node.leaf === false) {
            return;
        }
        this.selectedEquipment = node;
        console.log('onDragStart');
        console.log(this.selectedEquipment);
    }

    onDragEnd($event, node): void {
        console.log('onDragEnd');
    }

    onDrop($event, node): void {
        console.log('onDrop');
    }

    onDragEnter($event, node): void {
        console.log('onDragEnter');
    }

    onDragLeave($event, node): void {
        console.log('onDragLeave');
    }
}

Here is my template:
<p-tree [style]="{'max-height': '400px', 'overflow':'auto'}" [value]="equipmentLibrary" selectionMode="single" [(selection)]="selectedEquipment" (onNodeSelect)="onSelect($event)">
        <template let-node pTemplate type="default">
            <span *ngIf="node.leaf === false">{{node.label}}</span>
            <span *ngIf="node.leaf === true"><img class="tree-icon" src="{{node.icon}}" /></span>
            <span *ngIf="node.leaf === true" 
                  pDraggable="true"
                  pDroppable="true"
                  (onDragStart)="onDragStart($event, node)"
                  (onDragEnd)="onDragEnd($event, node)"
                  (onDrop)="onDrop($event, node)"
                  (onDragEnter)="onDragEnter($event, node)"
                  (onDragLeave)="onDragLeave($event, node)">
                {{node.label}}
            </span>
        </template>
    </p-tree>

**Comment by cyberrranger** [comment]
you have no template

example:
`<p-tree
    [value]="displayedRootNodes"
    selectionMode="single"
    [selection]="selection"
>
    <template let-node pTemplate type="default">
        <span
            pDraggable="treedragdrop"
            pDroppable="treedragdrop"
            (onDragStart)="onDragStart($event, node)"
            (onDragEnd)="onDragEnd($event, node)"
            (onDrop)="onDrop($event, node)"
            (onDragEnter)="onDragEnter($event, node)"
            (onDragLeave)="onDragLeave($event, node)"
        >
            {{node.label}}
        </span>
    </template>
</p-tree>`

**Comment by bryanhaines** [comment]
@cyberrranger I really appreciate your help and your reply. Believe me when I say that I do have a template, but for some reason it didn't show up when I copied and pasted my markup. I will try again here:
<p-tree [style]="{'max-height': '400px', 'overflow':'auto'}" [value]="equipmentLibrary" selectionMode="single" (onNodeSelect)="onSelect($event)">
        <template let-node pTemplate type="default">
            
            <span *ngIf="node.leaf === true"><img class="tree-icon" src="{{node.icon}}" onerror="this.src = '/app/images/componenttypes/MissingIcon.png'" /></span>
            <span 
                  pDraggable="true"
                  pDroppable="true"
                  (onDragStart)="onDragStart($event, node)"
                  (onDragEnd)="onDragEnd($event, node)"
                  (onDrop)="onDrop($event, node)"
                  (onDragEnter)="onDragEnter($event, node)"
                  (onDragLeave)="onDragLeave($event, node)">
                {{node.label}}
            </span>
        </template>
    </p-tree>

**Comment by foxx9** [comment]
@bryanhaines Did you import the drag and drop module ?

`import { DragDropModule } from 'primeng/components/dragdrop/dragdrop';`

**Comment by bryanhaines** [comment]
@foxx9 Thank you for your reply. My import statement was "import { TreeModule, TreeNode, Draggable, Droppable } from 'primeng/primeng';". I added the import statement that you suggested, but still am not able to get the onDragStart event to fire. It seems as though no event will fire on my leaf nodes. I thought there was maybe some error in my template, but I can't see what it might be.

**Comment by cyberrranger** [comment]
8th of February is the planned date for 2.0-Final release. Then we’ll start working on the new features such as drag drop for tree, accessibility and rtl improvements, better touch support, live scrolling for datatable, spreadsheet component, captcha and server side rendering.

http://blog.primefaces.org/?p=4332

**Comment by cagataycivici** [comment]
Working on it for 4.0.RC1 which is next week.

**Comment by cagataycivici** [comment]
Available for 4.0.RC1

**Comment by cagataycivici** [comment]
DragDrop between multiple trees are also supported in addition to dragdrop within the same tree. They can choose if nodes can be draggable and/or droppable. So for example one tree can only give nodes whereas one can decided only to receive nodes. Also with draggableScope and droppableScope, a tree can decide whether to accept nodes from a certain tree.

<img width="982" alt="screen shot 2017-03-09 at 23 21 25" src="https://cloud.githubusercontent.com/assets/686247/23769065/c2e3dafc-0516-11e7-99bf-b46e307b0cc0.png">

**Comment by mkseng** [comment]
Can anyone tell about version of primeng in package.json for tree dragdrop. I am getting error while importing "DragDropModule". Currently, i am using "primeng": "^2.0.5" .

**Comment by lee-ji-eun** [comment]
I am getting an error while importing "TreeDragDropService". Currently, i am using "primeng": "^2.0.3" .

**Comment by ndmello** [comment]
Error importing  'TreeDragDropService'. Using primeng : 2.0.4

**Comment by KiransHub** [comment]
yeah it's missing!!!!

**Comment by cagataycivici** [comment]
You need to use PrimeNG 4 to get this feature, PrimeNG 2 only gets defect fixes, no new features as 4 does.

**Comment by Abhijeetkdev** [comment]
please help , i dont need drag drop inside a tree ,i need to drag an node from a tree and clone an object out of it and take the values out of the object like name/id based on the event i want fire a service get a json and fill a form  .basically i want to drag an node cloned object and drop it onto the form ....attached is the screen shot of the project which i am building

![drag and drop onto form](https://user-images.githubusercontent.com/25199817/27476194-5d504f4c-5825-11e7-8f19-a762d0e1a20e.PNG)

**Comment by Abhijeetkdev** [comment]
please help , i need to drag a node and drop it on to the form based on which a event should fire and cloned node/dragged node object will have a name/id property out of it .....i don't need to drag and drop inside a tree and that's my requirement of the project ...attached is the screen shot of the project am building in angular 4.0 .
![drag and drop onto form](https://user-images.githubusercontent.com/25199817/27476410-4b393912-5826-11e7-976e-898c703ce684.PNG)

**Comment by wugang33** [comment]
@bryanhaines When I fellow your steps and got the same problem of you got that the onDragStart callback can not fired. 
And finally I fix this problem by changing my App.module.ts and add DragDropModule in @NgModule(imports

`@NgModule({
  imports: [    TreeModule,DragDropModule,`

**Comment by kishor-p** [comment]
@cagataycivici  Is it possible to apply Drag and Drop functionality on HORIZONTAL   TREE ??

**Comment by wassim21** [comment]
hello
I have an issue with drag and drop tree nodes. I copied the code from PrimeNG website, but drag and drop dosen't work.
Can you help me ?

**Comment by umangsavaliya** [comment]
> @cagataycivici Is it possible to apply Drag and Drop functionality on HORIZONTAL TREE ??

https://stackblitz.com/edit/angular6-primeng-vtree

**Comment by Shanik09** [comment]
Is dragging a row data from P-table  to a tree view to different nodes and that drag data should be dropped  to that particular node only. Is it possible?

**Comment by LuisHenriqueJung** [comment]
Don't you forget to provide TreeDragDropService in your component module?
Try add like so:
`providers:[TreeDragDropService]` to the module that your using p-tree compoent

**Comment by alinbujor** [comment]
Hi,

Does anyone know if it's possible to drag a node on a different droppable section and not only inside the tree or on an other tree? I don't understand why this limitation to only rearrange nodes inside the tree or to move then on a different tree but not on a simple droppable section...
