### ISSUE TITLE
Add clear button on p-calendar like p-dropdown

### ISSUE THREAD

**Issue by Primith** [primefaces/primeng#6833]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report 
[ X ] feature request 
[ ] support request 
```

**Current behavior**
Currently, we can add a button bar to allow user to clear the date. But the button bar also contains a "today" button which can be incoherent with the minDate et maxDate values. 

**Expected behavior**
Add the same clear button as p-dropdown in order to clear the date.

**What is the motivation / use case for changing the behavior?**
There are 2 motivations : 
- To avoid incoherent button bar (see current behavior)
- To improve user experience => user will have only one click to clear date against two with button bar.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
