### ISSUE TITLE
Angular-cli issues

### ISSUE THREAD

**Issue by Zambiorix** [primefaces/primeng#684]
How do I get PrimeNG to work with the latest Angular-cli version. (i installed from github/master)

They moved the build-system to webpack recently (about a week ago?).

And the install instructions do not work anymore ...

**Comment by cemremengu** [comment]
Hello,

It's actually pretty easy. I built a template and still trying to finalize it (https://github.com/cemremengu/prime-ng-template) but you can get an idea of how to put it together.

**Comment by nomis89** [comment]
@cemremengu unfortunately your solution doesn't work with the angular-cli@webpack version.

**Comment by itsmeprasanjit** [comment]
Did anybody solve this issue ?

**Comment by nomis89** [comment]
I've tried the angular-cli@webpack2 version with PrimeNG version 13, but nothing new.
Does anybody got a working version of this combination? I'm thankful for every hint how to get this stuff to work

**Comment by benjamincharity** [comment]
AngularCLI: `1.0.0-beta.20-4`
PrimeNG: `1.1.0`

I was able to get it working in this manner:

```typescript
import { NgModule } from '@angular/core';
import { DataTableModule } from 'primeng/primeng';

@NgModule({
    imports: [
        DataTableModule,
    ],
})
export class MyModule { }

```

Then I was able to use it in my template as expected:

```html
<p-dataTable [value]="myData">
  <p-column
    field="name"
    header="Name"
  ></p-column>
</p-dataTable>
``

**Comment by sudheerj** [comment]
Please try with latest Angular-CLI quick start project. It works without issue.
