### ISSUE TITLE
Add Timezone Support to <p-calendar/>

### ISSUE THREAD

**Issue by noamichael** [primefaces/primeng#6841]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Currently, any date captured with the `<p-calendar/>` is considered to be entered with respect to the client's browser. If someone in the `America/Los_Angeles` zone selects `2018-01-01`, the component's value really is `2018-01-01T08:00:00.000Z`, while a user with the `America/New_York` zone would have the value `2018-01-01T05:00:00.000Z`:

| Selected Date  | Client Timezone | UTC |
| ------------- | ------------- |------------- |
| 2018-01-01 | America/New_York  | 2018-01-01T05:00:00.000Z  |
| 2018-01-01 | America/Chicago | 2018-01-01T06:00:00.000Z  |
| 2018-01-01 | America/Denver | 2018-01-01T07:00:00.000Z  |
| 2018-01-01 | America/Los_Angeles  | 2018-01-01T08:00:00.000Z |

There is a difference of an hour between each zone, and this is the standard and correct behavior by default because the user is most likely intending to enter the date in their own timezone.

**Expected behavior**
Support should be added to allow the timezone to be set as either an application wide value or perhaps as a property of the component instance. This would change the `<p-calendar/>` so that the entered date is in respect to the provided zone. Using the example from above, if someone in the `America/Los_Angeles` zone selects `2018-01-01`, and the component was set to the `America/New_York`  zone, the components absolute value would be `2018-01-01T05:00:00.000Z`.  

| Selected Date  | Client Timezone | Component Zone | UTC |
| ------------- | ------------- |------------- |------------- |
| 2018-01-01 | America/New_York | America/New_York  | 2018-01-01T05:00:00.000Z  |
| 2018-01-01 | America/Chicago | America/New_York | 2018-01-01T05:00:00.000Z  |
| 2018-01-01 | America/Denver | America/New_York | 2018-01-01T05:00:00.000Z  |
| 2018-01-01 | America/Los_Angeles | America/New_York  | 2018-01-01T05:00:00.000Z |

As you can see above, the value of the component is always the same regardless of the user's machine's zone.

**What is the motivation / use case for changing the behavior?**
In our application, the business rules dictate that all user entered datetimes are relative to the `America/New_York` zone and should be captured and displayed as such for consistency. (However, this can be modified at the application level to another zone). Currently, this is impossible with the `<p-calendar/>` as it stands and I've been Monkey Patching it:

```typescript
@Directive({
  selector: 'p-calendar'//only mount on p-calendars
})
export class ZonedDateComponent implements OnInit, OnDestroy {

  subscriptions: Subscription[]

  constructor(
    private appService: AppService,
    @Host() @Self() @Optional() private calendar: Calendar//the instance we're mounted on
  ) {

    //monkey patch internal methods :(
    calendar.formatDate = (date: Date, formatBinding: string) => {
      return moment(date).tz(this.timezone).formatWithJDF('MM/dd/yyyy');//ignoring formatBinding because it's a non-standard format
    };

    calendar.formatTime = (date: Date) => {
      let hourFormat = calendar.hourFormat == '12' ? 'hh a' : 'HH';
      return moment(date).tz(this.timezone).formatWithJDF(`${hourFormat}:mm`);
    };

  }

  ngOnInit() {
    this.subscriptions = [
      this.calendar.onSelect.subscribe((d) => this.transformDateToZone(d)),
      this.calendar.onInput.subscribe(event => {
        if (this.calendar.value) { //this means the input was accepted as valid
          this.transformDateToZone(this.calendar.value);//we should transform the date
        }
      })
    ];
  }

  ngOnDestroy() {
    this.subscriptions.forEach(s => s.unsubscribe());
  }

  transformDateToZone(capturedDate: Date) {//strip timezone from date and force into configured zone
    let zonedDate = dateUtil.convertToZone(capturedDate, this.timezone);
    this.calendar.updateModel(zonedDate);//this is a private api. In the future, we'll try to avoid using it.
  }


  get timezone(){
    return this.appService.timezone;
  }

}
```

This works for basic calendar inputs, but it's flawed, and the complexity of monkey patching is not ideal because we basically have to patch every method and we constantly have to maintain the patches between primeng versions. For example, I just discovered  the calendar's highlighted `today` date is currently[ dependent on the client's zone](https://github.com/primefaces/primeng/blob/826b909e7a699a05b29fce65bf6b7ab9f6be144c/src/app/components/calendar/calendar.ts#L1017). I would love to hear everyone's thoughts on the issue as I'm sure we're not the only ones dealing with timezones. I would also like to hear any ideas for an alternate implementation.

**Comment by MattiJarvinen-BA** [comment]
They had date UTC... and they chose to remove it #5853 Me personally, I hope I had never used primeng in the first place.

**Comment by emilytimer** [comment]
Oh, it's still open, how to work around it? i really don't like maintain a project with primeng.

**Comment by riorudo** [comment]
[This workaround](https://github.com/primefaces/primeng/issues/5853#issuecomment-416886129) works for me. So at least i get an UTC time from the calendar component.

**Comment by cagataycivici** [comment]
Due to complexity it brings, none of the datepickers (PrimeFaces, PrimeNG, PrimeReact, PrimeVue) have built-in support for timezones as it can be handled by the page author easier.

**Comment by johnmanko** [comment]
@cagataycivici With all due respect, you didn't address ANY of the concerns of the op.  We are all grateful for the work you do on this library, but to brush aside the real concerns of dev users is short-sighted.  Saying "it can be handled by the page author easier" is just flat out lazy, especially for a component library published with the intent of others using it.  This is a real problem.  Are you guaranteeing that `Calendar.updateModel()` will be always be available and never removed?  Are you going to put it in the documentation that zoned dates "can be handled by the page authors easier" by updating the model using `updateModel()`?  Will you publish a guide in the documentation on all intricacies (such as `today` using the clients zone) and what to do to handle it?  Devs drop libraries because of stuff like this.

**Comment by blubcow** [comment]
See https://github.com/primefaces/primeng/issues/13546#issuecomment-1974977744 for one possible solution converting timezones

**Comment by sergei202** [comment]
I created a simple component that will convert from a local timezone to any timezone, maybe it'll help someone:

```
<datepicker-timezone name="testDate" [(ngModel)]="testDate" timezone="UTC"></datepicker-timezone>
```

```
import { CommonModule }                                       from '@angular/common';
import { Component, EventEmitter, forwardRef, Input, Output } from '@angular/core';
import { NG_VALUE_ACCESSOR }                                  from '@angular/forms';
import { FormsModule }                                        from '@angular/forms';
import { DateTime }                                           from 'luxon';
import { DatePickerModule }                                   from 'primeng/datepicker';

@Component({
	selector: 'datepicker-timezone',
	imports: [DatePickerModule, CommonModule, FormsModule],
	template: `
		<p-datepicker [name]="name" [required]="required" [disabled]="disabled" [styleClass]="styleClass" [(ngModel)]="internalValue" (ngModelChange)="onDateChange()"></p-datepicker>
	`,
	providers: [
		{
			provide: NG_VALUE_ACCESSOR,
			useExisting: forwardRef(() => DatePickerTimezoneComponent),
			multi: true
		}
	],
	standalone: true
})
export class DatePickerTimezoneComponent {
	@Input() name: string;
	@Input('value') modelValue: Date;
	@Input() timezone: string;
	internalValue: Date;

	@Input() disabled: boolean;
	@Input() required: boolean;
	@Input() styleClass = 'form-control';

	@Output('blur') blurEvent = new EventEmitter();

	constructor() {}

	onChange: any = (value: Date) => {};
	onTouched: any = () => {};

	get value() {
		return this.modelValue;
	}
	set value(value: Date) {
		if(!value) return;

		const oldValue = this.modelValue;

		if(value && !(value instanceof Date)) value = new Date(value);
		this.modelValue = value;

		if(this.timezone && value) {
			const localOffset = DateTime.fromJSDate(value).offset;
			const timezoneOffset = DateTime.fromJSDate(value).setZone(this.timezone).offset;
			// console.log('localOffset=%o, timezoneOffset=%o, diff=%o', localOffset, timezoneOffset, localOffset - timezoneOffset);
			this.internalValue = DateTime.fromJSDate(value).minus({ minutes: localOffset - timezoneOffset }).toJSDate();
		} else {
			this.internalValue = value;
		}

		if(oldValue) this.onChange(this.internalValue);
		this.onTouched();
	}

	onDateChange() {
		// console.log('onDateChange: internalValue=%o', this.internalValue);
		if(this.timezone && this.internalValue) {
			const localOffset = DateTime.fromJSDate(this.internalValue).offset;
			const timezoneOffset = DateTime.fromJSDate(this.internalValue).setZone(this.timezone).offset;
			// console.log('localOffset=%o, timezoneOffset=%o, diff=%o', localOffset, timezoneOffset, localOffset - timezoneOffset);
			this.modelValue = DateTime.fromJSDate(this.internalValue).plus({ minutes: localOffset - timezoneOffset }).toJSDate();
		} else {
			this.modelValue = this.internalValue;
		}
		// console.log('onDateChange: modelValue=%o', this.modelValue);
		this.onChange(this.modelValue);
	}

	private writeValue(value) {
		this.value = value || null;
	}
	private registerOnChange(fn: (value: Date) => void) {
		this.onChange = fn;
	}
	private registerOnTouched(fn: () => void) {
		this.onTouched = fn;
	}
	private onBlur(event: Event) {
		this.blurEvent.emit(event);
	}
}
```
