### ISSUE TITLE
p-slider renders small

### ISSUE THREAD

**Issue by mcpierce** [primefaces/primeng#6849]
I have a simple case where I use p-slider in my app, added in a component like this:

```
  <div class='row w-100 justify-content-center pb-1'>
    <div class='field'>
      <label for='comic-sort-order'>Cover size:</label>
    </div>
    <div class='row w-100 justify-content-center pb-1'>
      <p-slider [(ngModel)]='cover_size' min='200' max='640'
        (onChange)='set_cover_size($event)'></p-slider>
    </div>
  </div>

```

But when the page renders, the slide is just a button that doesn't move but which covers the range entered, as this screen shot shows:

![image](https://user-images.githubusercontent.com/61601/48280121-b0bc0a80-e420-11e8-8c48-e5dae1ae61ba.png)

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.
