### ISSUE TITLE
Dropdown onModelChange is not executed when selecting value by arrows

### ISSUE THREAD

**Issue by KonbOgonb** [primefaces/primeng#685]
Seems that the only situation when onModelChange is executed is when item is selected by mouse click. If we use arrows to select value onModelChange is not executed.

**Comment by imfarhadk** [comment]
The above fix has broken the fixes done in previous version. beta11 
---The issue encountered is given below---
The model is not getting updated on selection. 
options - the value element is an object and not a string
e.g - {label:'New York', value:{id:1, name: 'New York', code: 'NY'}}
