### ISSUE TITLE
Dialog without footer has extra space at the bottom

### ISSUE THREAD

**Issue by adama357** [primefaces/primeng#6850]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-zxfsbh?file=src/app/app.component.html

**Current behavior**
If there's no footer for a dialog, there's (sometimes) an empty footer that appears.  The footer will randomly appear and change size as you change the viewport size. On our website, the empty footer is transparent, but in the above stackblitz it's white:  

![empty_footer](https://user-images.githubusercontent.com/20462430/48287132-6d1bcd80-e42d-11e8-90f8-ea085261d82e.png)

**Expected behavior**
If there's no footer defined, none should appear, and the resize grabber in the corner should just appear in the main dialog body. 

**Minimal reproduction of the problem with instructions**
In Chrome, simply open the Stackblitz, and you should see a small footer. It will change size as you adjust the viewport size. 

In Firefox, the footer doesn't appear until the dialog is either taking up 100% of the viewport width or you pull the dialog to make it wider and then adjust the viewport. 

**Please tell us about your environment:**
Windows 10

* **Angular version:** ~6.1.7

* **PrimeNG version:** ~6.1.5

* **Browser:** Chrome and Firefox have different behavior (see above)

**Comment by dinesh-here** [comment]
Hi @adama357 ,

It's not because of empty footer/div. minimum height for the dialog is 150px so lesser content is creating empty space set minHeight as auto will automatically resize the height based on content.

``<p-dialog header="Godfather I" [(visible)]="display" modal="modal" dismissableMask="true" [responsive]="true" [minHeight]="'auto'">``

**Comment by dinesh-here** [comment]
@adama357 Agreed. Default value for min height can be auto. Let keep this thread open for discussion.
