### ISSUE TITLE
6.1.6 doesn't contain .css files

### ISSUE THREAD

**Issue by wags1999** [primefaces/primeng#6851]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Version 6.1.6 npm package only contains .scss files in the node_modules/primeng/resources, which causes issues for projects that are referencing the css files.  This has broken our CI builds today.

**Expected behavior**
Versions prior to 6.1.6 contained .scss and .css files.

**Comment by mertsincan** [comment]
I couldn't replicate it. Please check it; https://unpkg.com/primeng@6.1.6/resources/

**Comment by DavidPLamas** [comment]
Hi @mertsincan,

I'm having the same problem. 
I was referencing "../node_modules/primeng/resources/themes/omega/theme.css" in my angular-cli file, and after updating to 6.1.6 my angular build started failing because the file does not exist anymore. 
I had to manually revert it to 6.1.5 in order to make it work again.

Is this an expected behavior ?

**Comment by wags1999** [comment]
It appears some themes in 6.1.6 have css files:
https://unpkg.com/primeng@6.1.6/resources/themes/nova-light/
https://unpkg.com/primeng@6.1.6/resources/themes/nova-dark/

While other themes only have scss files:
https://unpkg.com/primeng@6.1.6/resources/themes/omega/
https://unpkg.com/primeng@6.1.6/resources/themes/pepper-grinder/
https://unpkg.com/primeng@6.1.6/resources/themes/redmond/

**Comment by adrienverge** [comment]
We have the same problem: `node_modules/primeng/resources/themes/omega/theme.css` is missing in version 6.1.6.

**Comment by JACrazy** [comment]
It may have been removed on purpose as omega theme is deprecated:

https://unpkg.com/primeng@6.1.5/resources/themes/omega/theme.css

Not how they repeat twice at the top of the file:
> * Deprecated: Use nova instead

**Comment by cagataycivici** [comment]
Try with 6.1.7 please.
