### ISSUE TITLE
How to do row group if data structure is like [{[]}..{[]}..]

### ISSUE THREAD

**Issue by raviji** [primefaces/primeng#6852]
"data":[ {"vin":"AAA","brand":"VW","year":1998,"color":"White","price":10000, "item":[{"make": "Ford", "model": 2018}] }, {"vin":"AAA","brand":"Mercedes","year":1985,"color":"Green","price":25000, "item":[{"make": "Ford", "model": 2018}]}, {"vin":"BBB","brand":"VW","year":1993,"color":"Maroon","price":40000, "item":[{"make": "Ford", "model": 2018}]}, {"vin":"AAA","brand":"Fiat","year":1964,"color":"Blue","price":25000, "item":[{"make": "Ford", "model": 2018}]}, {"vin":"AAA","brand":"Renault","year":1983,"color":"Maroon","price":22000, "item":[{"make": "Ford", "model": 2018}]}, ] 
Any help would be appreciated, thanks in advance.

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.
