### ISSUE TITLE
p-dialog onHide event doesn't execute callback when closing the dialog with X button in the top-right corner

### ISSUE THREAD

**Issue by BjoernKW** [primefaces/primeng#6855]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://github-g4ddqf.stackblitz.io/

**Current behavior**
When closing a p-dialog with the X button in the top-right corner the provided callback function doesn't execute onHide.

**Expected behavior**
When closing a p-dialog with the X button in the top-right corner the provided callback function should execute onHide.

**Minimal reproduction of the problem with instructions**
https://github-g4ddqf.stackblitz.io/

**Please tell us about your environment:**
macOS Mojave 10.14.1
IntelliJ IDEA

* **Angular version:** 7.0.3

* **PrimeNG version:** 7.0.0-beta.1

* **Browser:** all
 
* **Language:** TypeScript 3.1.6

**Comment by cagataycivici** [comment]
I'm unable to replicate with the code in master, please try with RC1 which will be released tomorrow.

**Comment by BjoernKW** [comment]
Please see the linked StackBlitz project again. I've updated the PrimeNG dependencies to 7.0.0-rc.2 but the problem remains (i.e. when clicking the 'X' on the dialog shown you should see a string "test" logged to the browser console if everything works as expected. However, no such string is logged when clicking 'X').

**Comment by BjoernKW** [comment]
See new issue: https://github.com/primefaces/primeng/issues/6925
