### ISSUE TITLE
p-Multiselect defaultLabel/selectedItemsLabel not showing with selectedItems template

### ISSUE THREAD

**Issue by Biratus** [primefaces/primeng#6858]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When p-mutliSelect uses the 'selectedItems' template, the default label and default selected items label is not showing. Below is what is causing this problem.
component/multiselect/multiselect.ts l. 25:
```
 <div class="ui-multiselect-label-container" [title]="valuesAsString">
    <label class="ui-multiselect-label ui-corner-all">
        <ng-container *ngIf="!selectedItemsTemplate">{{valuesAsString}}</ng-container>
        <ng-container *ngTemplateOutlet="selectedItemsTemplate; context: {$implicit: value}"></ng-container>
    </label>
</div>
```

**Expected behavior**
When there are no selected values the 'defaultLabel' property should be displayed. If the values exceed the 'maxSelectedLabel' property the 'selectedItemsLabel' should be displayed. Like the dropdown component.

**Minimal reproduction of the problem with instructions**
```
<p-multiSelect [options]="someoptions" [(ngModel)]="somevalue" defaultLabel="Values..." maxSelectedLabels="5" selectedItemsLabel="{0} selected Items">
    <ng-template let-it pTemplate="item">
        <span *ngIf="it.value.tradKey">{{it.value.tradKey | translate}}</span>
        <span *ngIf="!it.value.tradKey">{{it.label}}</span>
    </ng-template>
    <ng-template let-sitem pTemplate="selectedItems">
        <span *ngFor="let item of sitem;last as isLast">
            <span *ngIf="item.tradKey">{{item.tradKey | translate}}</span>
            <span *ngIf="!item.tradKey">{{item.name}}</span>
            <span *ngIf="!isLast">, </span>
        </span>
    </ng-template>
</p-multiSelect>
```
**What is the motivation / use case for changing the behavior?**
If the normal behavior needs to be reproduce, all use cases have to be implemented in the <ng-template> tag

* **Angular version:** 5.X

* **PrimeNG version:** 6.1.6

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   

**Is this the wanted behavior? Do we need to implement the wanted behavior in the <ng-template> tag to display the default label and selected items label or will it be fixed in the future ?**

**Comment by JacobSiegle** [comment]
When you use `pTemplate="selectedItems"` it gives you full control of what is displayed in the multiselect which means defaultLabel and maxSelectedLabel props no longer apply. It seems like this is an intended feature. You could use a copy of their code to reproduce the same thing -

https://github.com/primefaces/primeng/blob/8a646356bb8f67f4d4275b3b954853dfe21e0d84/src/app/components/multiselect/multiselect.ts#L518

**Comment by cagataycivici** [comment]
This is the intended behavior.

**Comment by Dharma-DX** [comment]
same use happening for me,when use ng-model and  ng-template inside drop down,instead of ng-model using form Control work well. multi select dropwon value selected but selectedItem Label not showing.

**Comment by sumirolabs** [comment]
When using the `selectedItems` template, the `.p-multiselect-label-empty` class is applied and hides the template _**unless**_ you also have a `placeholder` value. This value is never used, but it prevents the `.p-multiselect-label-empty` class from being applied, so you can have code in the template to handle a placeholder value.

This seems like a bug - if the `selectedItems` template will never show the `defaultLabel` (now `placeholder`) props, then why is it also hiding the template if there are no results?

**Comment by alokraj68** [comment]
updatelabel is nto avaialble anymore :(
