### ISSUE TITLE
Tooltip - tooltipEvent support more than hover/focus events

### ISSUE THREAD

**Issue by justinotero** [primefaces/primeng#6862]
## Tooltip - tooltipEvent support more than hover/focus

**I'm submitting a ...**
```
[   ] Bug report
[ x ] Feature request
[   ] Support request
```

Currently tooltipEvent supports only `hover(default) | focus`. Would be really helpful if it supported at minimum `click` also. I can imagine minimum support for the following events:

- `hover` (default) 
- `focus`
- `click`
- `touchstart`

**Motivation/Use Case**
More usable on mobile
Click ensures the tooltip stays open until the user clicks on the element again, or anywhere else in the document.

**Comment by rafa-as** [comment]
@cagataycivici We also need this functionality

**Comment by SarahJane87** [comment]
@cagataycivici +1

**Comment by justinotero** [comment]
@cagataycivici Provided we get enough community support can I resubmit my PR, then go through the regular PR process?

**Comment by yaoquanyu** [comment]
Cool, useful functionality to have. Can't wait to see it in the Tooltip 👍 !

**Comment by cardeo** [comment]
I would love to see this!

**Comment by gregAnd** [comment]
@cagataycivici
Is this demand for new features available today ?

**Comment by ViniciusCaminhaDeveloper** [comment]
=1

**Comment by karabaesh** [comment]
+1

**Comment by nlappe** [comment]
would love to have to other events aswell. click for example

**Comment by moussa-b** [comment]
also needed

**Comment by vetoshk1n** [comment]
+1

**Comment by serega270** [comment]
+1

**Comment by codePitcher** [comment]
+1

**Comment by cdskill** [comment]
+1

**Comment by devfake** [comment]
+1

**Comment by ChiranjeeviKandukuri** [comment]
tooltip(version 11.1.0) not working on images in responsive, is the issue is exists? can u please help
thanks

**Comment by greg59650** [comment]
+1

**Comment by AlexanderVega** [comment]
+1

**Comment by D-Biela** [comment]
+1

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
