### ISSUE TITLE
Primeng Autocomplete Dropdown width not correct with appendTo

### ISSUE THREAD

**Issue by zoraizasif** [primefaces/primeng#6865]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
I'm using p-autoComplete with local ng-template with 3 columns, 'Name', 'Address' and 'Email' respectively. The problem is that the Address field requires more space as compared to other two fields, and usually the remaining text shifts to the next row. I'm using appendTo="body" so that the whole dropdown thing takes required width, but its not the case.

Image:
[https://i.stack.imgur.com/EUsuf.png](url)

**Expected behavior**
I'd like the dropdown to maximize in width so that the text doesn't shift to the next row, it should stay within single row.

**Minimal reproduction of the problem with instructions**
<p-autoComplete appendTo="body">

**Please tell us about your environment:**
MacOS 10.14

* **Angular version:** 6.1.4

* **PrimeNG version:** 6.1.3

* **Browser:** [all]

**Comment by shogogan** [comment]
+1

**Comment by shogogan** [comment]
Verifying the code, it is set the minWidth as the component`s width, but as the maxWidth and width isn't set it grows as much as it wants

**Comment by zoraizasif** [comment]
@shogogan I've found a fix. When using the appendTo="body" also use a panelStyleClass to give it a class and then give min-width css to this class inside angular main.css file since its appended to the body. It will override the minwidth style present on the overlay div.

**Comment by shogogan** [comment]
well, the problem is if you use this: https://www.primefaces.org/primeng/#/grid

What is the width that i should set?

I fixed this using a directive, but it looks like a hack fix :(
