### ISSUE TITLE
Dynamic data binding issue in dialog box when webpage ideal for 20 min

### ISSUE THREAD

**Issue by kumardevendra26** [primefaces/primeng#6866]
I am facing an issue related with p-dialog, When we are clicking the web-page continuously it is binding the dynamic content perfectly. 

I am facing this issue when web-page is ideal for more than 20 min and tries to open a dialog box. It shows the blank popup without any data binding.

Below are the version detail:-
Angular CLI: 6.2.3
Node: 8.11.3
OS: win32 x64
Angular: 6.1.8 
Primeng: 5.0.2

I am not able to figure out the actual scenario and how to fix.

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists wit|h the new version please create a new issue with our stackblitz template.
