### ISSUE TITLE
Add time axis support to p-chart

### ISSUE THREAD

**Issue by dhakehurst** [primefaces/primeng#6867]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Waiting Time: ~8 weeks.

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Expected behavior**
I want to create a chart with a time axis.
Chart.JS requires 'moment' to be installed, in-order for time axis to be available.

**Comment by JacobSiegle** [comment]
So why don't you include moment in your project then? This is a question not an issue, it shouldn't be posted here. Try the PrimeNG forums.

**Comment by dhakehurst** [comment]
I tried that.
It doesn’t work.

**Comment by JacobSiegle** [comment]
Your config is wrong then, I just tested in quickly in stack-blitz and it works to show dates and times using moment.

**Comment by cghislai** [comment]
yep i use with moment it works fine. Most probably a chart.js misconfiguration.

**Comment by cagataycivici** [comment]
You should be able to do this with the options property.
