### ISSUE TITLE
PickList MoveAllToLeft/Right should check item "display:none" too.

### ISSUE THREAD

**Issue by upondeep** [primefaces/primeng#6868]
I'm submitting a bug report
**Current behavior**
Move all action will move all items including which has "display:none" property.

**Expected behavior**
uh, treat those items as filtered and not move them?

**What is the motivation / use case for changing the behavior?**
I'm manually hiding those items base on other criteria and not using name filter.

**Please tell us about your environment:**

* **Angular version:** 5.X

* **PrimeNG version:** 5.X

**Comment by gasparbarancelli** [comment]
You are using the display property none, but you would only use an if.

**Comment by thedanielgray** [comment]
I agree... if you want to filter out elements, you should simply eliminate them from the DOM tree instead of just hiding it. Adding code to do that would make it more complicated, and I think it's best left as simple as possible
