### ISSUE TITLE
Carousel elements do not recalculate after changing screen orientation

### ISSUE THREAD

**Issue by tadamczak** [primefaces/primeng#6874]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

Elements of carousel do not recalculate its width after changing screen orientation on mobile devices.
Probably it should be resolved here: https://github.com/primefaces/primeng/blob/master/src/app/components/carousel/carousel.ts (line 250)

**Expected behavior**

Width of carousel elements should be recalculated after every screen change.

**Minimal reproduction of the problem with instructions**
Vertical screenshot of carousel (Before orientation change)
![vertical chosen 2nd variant](https://user-images.githubusercontent.com/11835592/48551120-e5263f80-e8d4-11e8-8869-8a6fa7374c03.png)

Horizontal screenshot of carousel (After orientation change)
![horizontal](https://user-images.githubusercontent.com/11835592/48551127-ea838a00-e8d4-11e8-97ca-9d6aa91bd4eb.png)

As you can see above the "left" paremeter is not recalculated after screen orientation change. From what i checked it's probably matter of invoking method https://github.com/primefaces/primeng/blob/master/src/app/components/carousel/carousel.ts (line 250) on screen change.

**What is the motivation / use case for changing the behavior?**
Carousel component should behave properly on all mobile browsers.

* **Angular version:** 6.1.*

* **PrimeNG version:** 6.1.*

* **Browser:** any mobile
 
* **Language:** TS 2.9.*

**Comment by MenchenFive** [comment]
> 
> 
> New carousel of 8.1.0 fixes this issue.

Sorry for the inconvenience.

Any ETA on when will that 8.1.0 version be released?
