### ISSUE TITLE
Export CSV table with format date

### ISSUE THREAD

**Issue by sourdoth** [primefaces/primeng#6875]
[X] feature request => Please check if request is not on the roadmap already 

in turbo table please add the option "formatDate" in export CSV for example: 

dt.exportCSV({formatDate:'dd-MM-yyyy HH:mm'})

thanks

**Comment by yogesh-mali44** [comment]
I have a similar problem with p-table. The date format in the table is in "dd/mm/yyyy hh:mm PM" format but when I export the data in CSV the date format is changed to "dd/mm/yyyy hh:mm". So basically I am loosing the "AM"/"PM" for the date.

**Comment by waratah** [comment]
I have a definition that gets converted into columns and this definition knows which one is a date.  When I export I match back the definitions and handle the format myself.  I cannot remember for the life one me why I added a tab to every field, think it breaks excel formatting numbers.

 exportFunction = (data: { field: string; data: any }) => {
    const def = find(this.tableSettings.tableColumns, x => x.field === data.field);
    if (def) {
      switch (def.dataType) {
        case DataTypeEnum.Date:
          if (data.data) {
            data.data = moment.tz(data.data, this.timezoneId).format('YYYY-MM-DD') + '\t';
          }
          break;

        case DataTypeEnum.TimeFromNow:
        case DataTypeEnum.DateTime:
          if (data.data) {
            data.data = moment.tz(data.data, this.timezoneId).format('YYYY-MM-DD HH:mm:ss') + '\t';
          }
          break;

        default:
          if (data.data && def.addTab) {
            data.data = data.data.toString() + '\t';
          }
          break;
      }
    }

    return data.data;
  };

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
