### ISSUE TITLE
Calendar displays AM even when the current time is PM

### ISSUE THREAD

**Issue by segun-transitiv** [primefaces/primeng#6878]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**

when i select a date, the time is displayed as AM but the time picker detects that is is PM, below is the code and screenshot:
 <p-calendar [(ngModel)]="bulkBasicEndDate" [showIcon]="true" [showTime]="true" [hourFormat]="12"></p-calendar>

![core app 90](https://user-images.githubusercontent.com/43682351/48572822-d490bc00-e90a-11e8-903e-378ad11f6ae6.png)

**Expected behavior**

The displayed time should correspond with the time shown on time picker

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.X

6.0.9

* **PrimeNG version:** 5.X

6.1.5

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome Version 70.0.3538.67 (Official Build) (64-bit)
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists wit|h the new version please create a new issue with our stackblitz template.
