### ISSUE TITLE
Programmatically load Gmap API Key

### ISSUE THREAD

**Issue by ethrock** [primefaces/primeng#6879]
**I'm submitting a ...**
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
When using the Gmap component one needs to put the script tag in their `index.html` file with the Google maps URL containing their API key:

`<script async defer src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap"
  type="text/javascript"></script>`

**Expected behavior**
Please implement an option to programmatically load the API key similar to how [angular-google-maps](https://github.com/SebastianM/angular-google-maps) accomplishes this:

`  imports: [
    AgmCoreModule.forRoot({
      apiKey: 'YOUR_KEY'
    })
  ],`

**What is the motivation / use case for changing the behavior?**
This will allow Gmaps users to encrypt their API key and/or keep it out of source control as it can now be loaded from another file instead of hard coded in the `index.html` file.

**Please tell us about your environment:**
N/A

* **Angular version:** 7.01

* **PrimeNG version:** 6.1.6

* **Browser:** [all]

**Comment by JacobSiegle** [comment]
I use a much thinner wrapper which does the same thing but allows you to load maps at any point - 
https://github.com/yuanqing/load-google-maps-api/blob/master/index.js

The exact page for referenced above functionality -
https://github.com/SebastianM/angular-google-maps/blob/master/packages/core/services/maps-api-loader/lazy-maps-api-loader.ts

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
