### ISSUE TITLE
Routing in Tabview Panel

### ISSUE THREAD

**Issue by anikets43** [primefaces/primeng#688]
Hi @cagataycivici 

Is it possible to maintain routing in tabview to enable on demand file download. I have around 20 tab view nav bar. All the files and ngOnit hooks are executed on page load. Could you please suggest how I can plug routing to it.

Thanks much,
Aniket

**Comment by cagataycivici** [comment]
So you need to open a tab based on url? Can you provide more details?

**Comment by joycollector** [comment]
Any updates on this?
I have 5 tabs in my app. I want to change route when I change tab and vice versa.

**Comment by cagataycivici** [comment]
Why not use tabMenu component?

**Comment by joycollector** [comment]
@cagataycivici because it doesn't reuse component on tab switch. it's heavy enough and it works slowly.

**Comment by cagataycivici** [comment]
I dont understand, we have created tabMenu to provide this feature so closing.

**Comment by joycollector** [comment]
@cagataycivici could you than at least add same functionality as tabview has to tabmenu? For example ability to close tabs?

**Comment by cagataycivici** [comment]
Why not? Please add a feature request ticket.

**Comment by rachelbr** [comment]
Is feature request opened already for this issue?

Is there an estimate of how long it will take?
I want to know if I need to develop myself or wait for you

Thank you very much for your good work

**Comment by joycollector** [comment]
@rachelbr No, that's something that needs to be done.
