### ISSUE TITLE
New feature: spellcheck attribute on p-autoComplete

### ISSUE THREAD

**Issue by michaelplavnik** [primefaces/primeng#6881]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Expected behavior**
Propagate spellcheck attribute to the internal input element used by p-autoComplete

**Notes**
I can create pull request with implementation if agreed.

**Comment by Cito** [comment]
I second that and am also willing to send a pull request.

Currently, `p-autocomplete` sets `autocomplete="off"` but it should optionally also set `autocorrect="off" autocapitalize="off" spellcheck="false"`. A single switch for all of these should be sufficient.

**Comment by jycr** [comment]
Any news?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by jycr** [comment]
I couldn't find any way to disable spell checking in the documentation (http://primefaces.org/primeng/autocomplete).
No way to set `autocorrect="off"` `autocapitalize="off"` `spellcheck="false"`

**Comment by tigrenok00** [comment]
Asking for the same feature for p-dropdown and multiselect

**Comment by cetincakiroglu** [comment]
Hi,

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 
For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
