### ISSUE TITLE
Column Re-sizer blue line is appearing even after the mouse click is released in Table 

### ISSUE THREAD

**Issue by NarayanCheerla** [primefaces/primeng#6884]
Click on the column expansion line by using both the mouse(right & left) clicks and drag the mouse. Then release the mouse clicks. The blue highlighter line is still present and not disappearing in prime ng p-table component.
![column-resize](https://user-images.githubusercontent.com/8089105/48697931-dbba1180-ec0b-11e8-864d-60b099bb7203.gif)

**Comment by asmith2306** [comment]
I'm also experiencing this issue.

**Comment by roslowry** [comment]
also experiencing this

**Comment by Charmi-webosmotic** [comment]
I'm also experiencing this issue. Any update on this issue?
