### ISSUE TITLE
p-dropdown not closed properly inside p-overlay

### ISSUE THREAD

**Issue by gibonu** [primefaces/primeng#6888]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/angular-wnx9nv?file=src%2Fapp%2Fapp.component.html

**Current behavior**
When clicked outside dropdown AND overlay it is not possible to use dropdown again after opening overlay. Same happens for other dismissable components such as modals.

Using appendTo=body it appears to work, but clicking any option inside dropdown dismisses the overlay

**Expected behavior**
should work. Either clicking outside should close only dropdown leaving overlay/modal visible or everything should be dismissed properly

**Minimal reproduction of the problem with instructions**
1. click basic button
2. open dropdown inside overlay
3. click anywhere outside an overlay
4. click Basic to open overlay again
5. try opening dropdown

* **Angular version:** 6.0.3
* **PrimeNG version:** 6.1.6

* **Browser:**  tested latest versions of Chrome, FF, Edge

**Comment by JacobSiegle** [comment]
I believe this is an issue with the state of the overlay panel which is described in the following issue - https://github.com/primefaces/primeng/issues/6921

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists wit|h the new version please create a new issue with our stackblitz template.
