### ISSUE TITLE
Ability to disable dialog mask

### ISSUE THREAD

**Issue by JacobSiegle** [primefaces/primeng#6889]
**Current behavior**
Whenever a dialog is used it always appends a div onto the DOM like -
`<div class="ui-widget-overlay ui-dialog-mask" style="z-index: 11002;"></div>`

**Expected behavior**
There should be a way to opt out of using the dialog mask. That way a user could open a dialog and continue to interact with the page while keeping the dialog open.

**Comment by ViceIce** [comment]
You should simply not use the `modal` flag. Then the mask won't be added to body. See https://github.com/primefaces/primeng/blob/3605d41de6534c489bf3a4ac7fd55bdf59d17fb1/src/app/components/dialog/dialog.ts#L588-L590

**Comment by JacobSiegle** [comment]
Makes sense, not sure how I overlooked that. Thanks!
