### ISSUE TITLE
Multiselect Filter Issue

### ISSUE THREAD

**Issue by MrBogue** [primefaces/primeng#6891]
Hello,
Gladly if someone could shed some light on this issue;
There seems to be a bug in the table filter (with a search option). 

1. Input a value that does not exist in the list
2. select the checkbox

we can see that the total no. of records selected is though we haven't specified the values in the list.
please find attached a screenshot of the issue reported.

Can you please help out?
Kind Regards,
Virish S.

![table filter issue](https://user-images.githubusercontent.com/37176169/48754514-2da57a80-ec92-11e8-9bfd-31ce0f0bea84.png)

**Comment by JacobSiegle** [comment]
Seems like a bug. Comment tagged.
