### ISSUE TITLE
ui-messages-* definitions missing from omega.scss

### ISSUE THREAD

**Issue by johnhall** [primefaces/primeng#6893]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

In the latest 6.1.x version, the ui-messages-error and ui-messages-info (at least) are missing from the omega.scss style sheet.  I tried several of the other new scss and found that it was missing from many (all?) of those as well.  As a result, all of our p-message widgets now display messages without color.

**Please tell us about your environment:**
* **Angular version:** 6.X
* **PrimeNG version:** 6.1.6
* **Browser:** all
* **Language:** all

**Comment by cagataycivici** [comment]
Yes, omega is one of the deprecated ones, please migrate to the newer ones like Nova.
