### ISSUE TITLE
p-dropdown value resets upon re render

### ISSUE THREAD

**Issue by faisal-zulfiqar** [primefaces/primeng#6894]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
I've a `p-table` inside my component to which I add/subtract products, hence its dynamic. For each product I add to the `p-table` I need a dropdown column as well to select the category of Tax I need to apply for an individual product. I add the dropdown like this:
`<p-dropdown name="taxOptions" [options]="taxOptions" [(ngModel)]="purchaseInvoiceDetail.tax"></p-dropdown>`
Each product is now bound with tax attribute of a separate instance of the interface. Hence I expect the dropdown to retain what tax category I chose.
The problem arises when I add a product, select a tax category from drop down and then add another product, the whole table rows re render and the dropdowns reset their values to the default state, the value in the `purchaseInvoiceDetail.tax` doesn't reset. It only fails to fetch the value from `purchaseInvoiceDetail.tax` and show it as the selected value in the dropdown. Why is this happening?

```
this.taxOptions = [
      { label: 'Sales Tax', value: '0' },
      { label: 'Purchase Tax', value: '1' },
      { label: 'General Tax', value: '2' }
];

export interface PurchaseInvoiceDetail {
  id: number,
  product: Product,
  quantity: number,
  unitPrice: number,
  discount: number,
  tax: string,
  purchaseInvoice: PurchaseInvoice
}
```

**Expected behavior**
Upon adding a new product, the previous product's dropdowns should retain their selected values instead of resetting.

**What is the motivation / use case for changing the behavior?**
It's bad design to reset the users selected value each time a new product is added.

**Please tell us about your environment:**

OS: Ubuntu 18.04
IDE: Visual Studio Code
Package Manager: NPM

* **Angular version:** 6.1.4

* **PrimeNG version:** 6.1.6

* **Browser:** all

* **Node (for AoT issues):** `node --version` =   v8.12.0

**Comment by KaceyGambill** [comment]
I am also having this issue. Did you find a way around this?

**Comment by faisal-zulfiqar** [comment]
Unfortunately no.

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists wit|h the new version please create a new issue with our stackblitz template.
