### ISSUE TITLE
p-autoComplete dropdown headers 

### ISSUE THREAD

**Issue by faisal-zulfiqar** [primefaces/primeng#6895]
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
The dropdown panel that opens from the `<ng-template>` doesn't include column headers for each column and there's no way to add one. It would be really helpful to be able to give header names to the columns inside the dropdown.

**What is the motivation / use case for changing the behavior?**
Better design for the user.

**Please tell us about your environment:**
OS: Ubuntu 18.04
IDE: Visual Studio Code
Package Manager: NPM

* **Angular version:** 6.1.4

* **PrimeNG version:** 6.1.6

* **Browser:** all

* **Node (for AoT issues):** `node --version` =  v8.12.0

**Comment by cagataycivici** [comment]
Issue is not clear, please provide more information and create a new ticket for review.
