### ISSUE TITLE
Turbotable export creates file with UTF-8-BOM instead of UTF-8

### ISSUE THREAD

**Issue by pantonis** [primefaces/primeng#6901]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Waiting Time: ~8 weeks.

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
Export data from a table into csv creates a csv file with UTF-8-BOM instead of UTF-8. This cause problems when the file is edited using excel and saved again in excel as the BOM breaks the csv into a tab csv
Check link with problem described [here](https://superuser.com/questions/1158036/excel-often-save-csv-files-as-tab-delimited-format-what-happened)

**Expected behavior**
csv export should be produce file with UTF-8

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
End users cannot use the csv files exported.

**Please tell us about your environment:**
Windows 10, VS Code, NPM

* **Angular version:** 5.X
Angular 7

* **PrimeNG version:** 5.X
Latest primeng

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All browsers
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by JacobSiegle** [comment]
I run into the the same issue. Ref for fix - https://github.com/primefaces/primeng/blob/3b54f9a517a6a41558c9e4eac8655bea0d5afde3/src/app/components/table/table.ts#L1408

**Comment by pantonis** [comment]
@JacobSiegle is this a pull request you have created?

**Comment by pantonis** [comment]
@cagataycivici ?

**Comment by cagataycivici** [comment]
What is the fix?

**Comment by pantonis** [comment]
@cagataycivici 
``` let csv = '; ```

**Comment by pantonis** [comment]
@cagataycivici Any news on this one?
