### ISSUE TITLE
Bug Report Calendar year range out

### ISSUE THREAD

**Issue by SoulMyke77** [primefaces/primeng#6902]
Hello,

I've got an issue with calendar's year range. I set it to 1900:2006 and when i navigate throught months i can go over this year range like january 2007 and the year range is now 2007:2112 with no reason and cannot be reset with onMonthChange. 

My calendar is supposed to set a birthdate so i don't want the user to navigate in the year range.

Have you got any information on this issues ? Is this normal or a bug ?

Thank you for your time

Informations : 
Angular : 7.0
Typescript: 3.1
p calendar is setted with Reactive Form

HTML : 
<p-calendar *ngIf="yearRange" id="patientBirthDate" formControlName="birthdate" [showIcon]="true"
                    dateFormat="dd/mm/yy" [yearNavigator]="true" [yearRange]="yearRange"
                    [maxDate]="maxDate" [minDate]="minDate" (onMonthChange)="onYear($event)"
                    [placeholder]="'add-patient.dob_input_placeholder'|translate"></p-calendar>

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists wit|h the new version please create a new issue with our stackblitz template.
