### ISSUE TITLE
Disabled in Model Driven Forms

### ISSUE THREAD

**Issue by sorcerb** [primefaces/primeng#6904]
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Angular show in debug console this warning, then I use [disabled] attribute.
Disable functional is work.
```
 It looks like you're using the disabled attribute with a reactive form directive. If you set disabled to true
      when you set up this control in your component class, the disabled attribute will actually be set in the DOM for
      you. We recommend using this approach to avoid 'changed after checked' errors.
       
      Example: 
      form = new FormGroup({
        first: new FormControl({value: 'Nancy', disabled: true}, Validators.required),
        last: new FormControl('Drew', Validators.required)
      });
```
Angular: 7.0.4
Primeng: 6.1.6
For example autocomplete:
```
<p-autoComplete formControlName="name" [suggestions]="results" [dropdown]="true"
                  [forceSelection]="true" (completeMethod)="search($event)" [disabled]="true"></p-autoComplete>
```

**Comment by cagataycivici** [comment]
It seems you need to remove [disabled]="true"

**Comment by sorcerb** [comment]
But in api there are:
Properties:
disabled | boolean | false | When present, it specifies that the component should be disabled.

So this component doesn't support disabled in driven forms.

I know that another desing framework add this attr: [attr.disabled]="true" to disable programmatic enable()/disable()

**Comment by huineng** [comment]
There's indeed a conflict with disabled when we're using reactive forms 
see also https://github.com/primefaces/primeng/issues/6527

**Comment by huineng** [comment]
But you can solve it by removing the [disabled] and handle it though the reactive form
this.form.controls['nameofcontrol'].disable();
