### ISSUE TITLE
p-table 'onRowReorder' event emits wrong dropindex value

### ISSUE THREAD

**Issue by sasestil** [primefaces/primeng#6910]
[x] bug report

On draging row from up to down in the table 'onRowReorder' event emits dropindex + 1 of actual drop index.

* **Angular version:** 
7.0.0

* **PrimeNG version:** 
Tested on 6.1.6 and 7.0.0-beta.1

* **Browser:**
All

**Comment by jsilveira2** [comment]
The same problem happen to me.

My primeng version is 6.1.4.
My Angular version is 6.1.3.

**Comment by BGBRWR** [comment]
**HOTFIX** until this PR #7726 is merged.
```typescript
onRowReordered(event) {
    event.dropIndex = (event.dragIndex > event.dropIndex) ? event.dropIndex : (event.dropIndex === 0) ? 0 : event.dropIndex - 1;
    ...
}
```
