### ISSUE TITLE
.ui-dropdown-label-empty & .ui-dropdown-item-empty added to a custom drawn dropdown

### ISSUE THREAD

**Issue by dmytro-gokun** [primefaces/primeng#6912]
angular: 7.1.0
primeng: 6.1.6 & 6.1.7

I have a dropdown with custom templates for items & selectedItem.
The markup looks like this:

`
<p-dropdown class="l-category-select" [options]="categories$ | async" optionLabel="name" [autoWidth]="false" [ngModel]="selectedCategory$ | async" (ngModelChange)="onSelectedCategoryIdChanged($event.id)">
    <ng-template let-category pTemplate="selectedItem">
        <div [ngStyle]="{backgroundColor: category.value.icon}" class="l-circle" title="{{category.value.name}}"></div>
    </ng-template>
    <ng-template let-category pTemplate="item">
        <div [ngStyle]="{backgroundColor: category.value.icon}" class="l-circle"></div>
    </ng-template>
</p-dropdown>
 `

Suddenly classes .ui-dropdown-label-empty (to the selected item) & .ui-dropdown-item-empty (to the dropdown items) are added. These classes in turn add "visiblity: hidden". So, everything becomes invisible. Is it a regression from previous versions or a breaking change which was never documented in changelog?

**Comment by cagataycivici** [comment]
Is there stackblitz template we can review?

**Comment by kavinnashi** [comment]
yeah even I face the issue so as a quick fix I have just overridden the css in the particular ts file

**Comment by kavinnashi** [comment]
make sure [options]="categories$ | async" optionLabel="name"  has values

**Comment by dmytro-gokun** [comment]
Just updated the strackblitz template to use the latest version of PrimeNg & Angular. The issue still exists.

**Comment by cagataycivici** [comment]
It works fine for me on 7.0.1;

```
<p-dropdown [options]="categories" optionLabel="value.color">
            <ng-template let-category pTemplate="item">
                <div [ngStyle]="{backgroundColor: category.value.color}" class="l-item">{{category.label}}</div>
            </ng-template>
        </p-dropdown>
```

**Comment by dmytro-gokun** [comment]
@cagataycivici That it is very cool that it works for you. But, if you'd take a look at the stackblitz i've made you will see the circumstance under which is does not work

**Comment by dmytro-gokun** [comment]
@cagataycivici Also, as far as I can see version 7.0.1 has never been released: https://www.npmjs.com/package/primeng

**Comment by dmytro-gokun** [comment]
@cagataycivici Okay, now when 7.0.1 was finally released, I've updated the stackblitz to use and the bug is still here :(

**Comment by cagataycivici** [comment]
Reopen for review

**Comment by cagataycivici** [comment]
Should be;

```
<ng-template let-category pTemplate="item">
          <div [ngStyle]="{backgroundColor: category.value.value.color}" class="l-item">{{category.value.value.color}}</div>
        </ng-template>
```

Upcoming optionValue will make it simpler.
