### ISSUE TITLE
Autocomplete with Selectize JS functionality

### ISSUE THREAD

**Issue by alokparikh16** [primefaces/primeng#6914]
Enhancement:

Needs to have Autocomplete with functionalities like Selectize js
Functionalities: 
For Multiple autocomplete: On left right click the input cursor should move between the tokens and on backspace should remove that item. 
It should also provide normal autocomplete functionalities as usual

https://selectize.github.io/selectize.js/
http://nicholasazar.github.io/

**Comment by tiagolisalves** [comment]
I'm interested on this also. 

Currently we are migrating our portal that has a visual identity. The legacy makes heavy use of selectize.js. 

I adjusted the dropdown to look like selectize with ViewChild and Css, but it's not a thing that I'm proud of.

**Comment by satish-pokala** [comment]
Nice to have
