### ISSUE TITLE
Data table: Paging selector no longer works in PrimeNG 6

### ISSUE THREAD

**Issue by roldengarm** [primefaces/primeng#6916]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
The paging selector dropdown does not work. When clicking it, nothing happens.

**Expected behavior**
The paging selector dropdown should appear, allowing me to select a paging size.
It worked fine in PrimeNG5.x

**Minimal reproduction of the problem with instructions**
https://github-g488e6.stackblitz.io

* **Angular version:** 5.X
7.1

* **PrimeNG version:** 5.X
6.1.0

* **Browser:** [Chrome ]

**Comment by cagataycivici** [comment]
Unable to replicate with 7.0.0-beta.1.
