### ISSUE TITLE
Horizontal Tree collapses after zoom level changed

### ISSUE THREAD

**Issue by Muralidharan-Kannappan** [primefaces/primeng#6917]
Issue is with the latest version of primeng, please go to the URL https://www.primefaces.org/primeng/#/tree and navigate to Horizontal Tree, expand all child nodes and reduce the zoom level to 90%,
![image](https://user-images.githubusercontent.com/29455518/49070962-db94c400-f252-11e8-9673-f96cd95df784.png)

**Comment by axell9641** [comment]
Any new on this? I still got the same problem.
@Muralidharan-Kannappan or anyone else found any workaround ?

**Comment by axell9641** [comment]
Please does anybody have a workaround for this? I tried increasing the width of the image that is used for those lines, but it didn't work. 
There's gotta be something we can do : (

**Comment by cetincakiroglu** [comment]
Hi,

We couldn't replicate the issue with the latest PrimeNG release, if the issue still exists with the latest PrimeNG version, please provide a StackBlitz example by using [PrimeNG Issue Template ](https://stackblitz.com/github/primefaces/primeng-issue-template) and re-open the issue.

Regards
