### ISSUE TITLE
[7.0.0-rc.1][TableState] nullpointer when ColumnResizeMode "expand"

### ISSUE THREAD

**Issue by Mysame** [primefaces/primeng#6919]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
```
**Current behavior**
When loading a table with `columnResizeMode='expand'`, the following error is presented:

```
TypeError: Cannot read property 'style' of null
at Table.push../node_modules/primeng/components/table/table.js.Table.saveColumnWidths (table.js:1508)
```

It's line 1975 in table.ts
https://github.com/primefaces/primeng/blob/826b909e7a699a05b29fce65bf6b7ab9f6be144c/src/app/components/table/table.ts#L1968-L1978

* **Angular version:** 7.1

* **PrimeNG version:** 7.0.0-rc.1

**Comment by Mysame** [comment]
Can no longer properly reproduce - was an edge case situation which I've refactored.

**Comment by andy200486** [comment]
I'm facing the same problem with the 7.0.5 version
