### ISSUE TITLE
OverlayPanel content projection causes bugs in numerous components

### ISSUE THREAD

**Issue by JacobSiegle** [primefaces/primeng#6921]
**Example**
![tooltip](https://user-images.githubusercontent.com/5766272/49091266-0d8f3180-f225-11e8-906e-425acb77d6b4.png)

I'll make a stackblitz later.

**Comment by JacobSiegle** [comment]
https://stackblitz.com/edit/github-jzz1ht

To replicate -
1) Open the overlay by clicking the button.
2)  Hover over the button in the overlay which will show the tooltip. 
3) Click outside the overlay on the right side.
4) The overlay will begin to close since you clicked outside.
5) Quickly move your mouse back on top of the button in the closing overlay.
6) The tooltip will still be showing (like the screenshot above) even when the overlay has been removed.

**Comment by JacobSiegle** [comment]
Upon further investigation it seems like this is caused due content projection by the overlayPanel (https://bit.ly/2zUW1h4) and the fix is to use ngTemplateOutlet like the turbo table does. Currently it seems like overlayPanel will leak memory from failure to call life cycle looks (correctly me if this is wrong) which is also why the tooltip will stick around because onDestory isn't being called. 

I don't think I can attempt to fix this any further due to significant changes it needs (new overlayPanel component).

**Comment by JacobSiegle** [comment]
I'm assuming this can happen with other components, but calendar is breaking when being used in overlay due to this bug.

Open the overlay, open the calendar, while both have the popup shown click on the page body -> calendar won't open again.
https://stackblitz.com/edit/github-wvne9h

**Comment by JacobSiegle** [comment]
Some other components i've tested - 
Dropdown, multiselect, color picker will require double click for it to open.
p-dialog perma breaks like calendar.

**Comment by cagataycivici** [comment]
Shouldn't this be fixed by Angular then, this means content projection is defective.

**Comment by cagataycivici** [comment]
Event with ngTemplateOutletContext, tooltip stays on quick mouse move, that should be fixed on tooltip side I guess. 

But lifecycle hooks being ignored is a problem, we've decided to migrate to ngTemplateOutlet and deprecate-drop content-projection.

https://github.com/primefaces/primeng/issues/8677

**Comment by cagataycivici** [comment]
We're migrating all ng-content to ngTemplateContext while maintaining backwards compatibility until PrimeNG 11.
