### ISSUE TITLE
Autocomplete should be able to show the options grouped in categories (in a tree, e.g.)

### ISSUE THREAD

**Issue by danielthegray** [primefaces/primeng#6922]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
The autocomplete only allows display of a flat list of items. 

**Expected behavior**
The autocomplete control should also allow the components to be organized in a tree, with collapsible levels.

**What is the motivation / use case for changing the behavior?**
Allowing the organization of objects into categories.

**Please tell us about your environment:**
any

* **Angular version:** 5.X
6.2

* **PrimeNG version:** 5.X
6.1.7

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
any
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
