### ISSUE TITLE
only upload a maximum of 2 files fileLimit="2"

### ISSUE THREAD

**Issue by azaddeveloper** [primefaces/primeng#6924]
<p-fileUpload 
          [files]="externalFiles" 
          required="true" 
          [multiple]="true" 
          accept="video/mp4"
          **fileLimit="2"** 
          maxFileSize="1000000000"
            [showUploadButton]="false" [showCancelButton]="false" (onSelect)="onUpladFile($event.files)" (onRemove)="onRemoveFile($event)">
          </p-fileUpload>

file limit not working

**Comment by dinesh-here** [comment]
Hi @azaddeveloper ,
There is no "fileLimit" option available in primeng. You can use **onSelect** output method event to get no of selected files and apply validation
