### ISSUE TITLE
p-dialog onHide event doesn't execute callback when closing the dialog with X button in the top-right corner

### ISSUE THREAD

**Issue by BjoernKW** [primefaces/primeng#6925]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Please see https://github.com/primefaces/primeng/issues/6855 . The issue has been closed but the problem remains with PrimeNG 7.0.0-rc.2 . I've updated the linked StackBlitz project to reflect the updated PrimeNG version.

**StackBlitz Case (Bug Reports)**
https://github-g4ddqf.stackblitz.io/

**Current behavior**
When closing a p-dialog with the X button in the top-right corner the provided callback function doesn't execute onHide.

**Expected behavior**
When closing a p-dialog with the X button in the top-right corner the provided callback function should execute onHide.

**Minimal reproduction of the problem with instructions**
https://github-g4ddqf.stackblitz.io/

**Please tell us about your environment:**
macOS Mojave 10.14.1
IntelliJ IDEA

* **Angular version:** 7.1.0

* **PrimeNG version:** 7.0.0-rc.2

* **Browser:** all
 
* **Language:** TypeScript 3.1.6

**Comment by BjoernKW** [comment]
Ok, I've found the cause of the issue: The code in the StackBlitz example contains an `*ngIf` in addition to the component's own `visible` parameter. Removing the `*ngIf` resolves the issue.

**Comment by stephanie-dm** [comment]
I don't want to remove the *ngIf, because I don't want to execute the dialog component's code when it's not visible... I just added `[closable]="false"` to make sure the X can't be used...

**Comment by lakhandeshpande** [comment]
I can't access the repository, Can you help?

Neither I am using ngif nor the closing popup is setting any event on close.

**Comment by dasch1886** [comment]
onHide still not working 
primeng: 14.2.3
angular: 14.0.0

**Comment by kazakevich-alexei** [comment]
Confirm. (onHide) still not working
primeng: 16.2.12
