### ISSUE TITLE
TreeTable horizontal scroll bar comes beween body and footer templates

### ISSUE THREAD

**Issue by grozdanova** [primefaces/primeng#6929]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
[https://stackblitz.com/edit/angular-lptzvr](https://stackblitz.com/edit/angular-lptzvr)

**Current behavior**
The issue is in that when we have horizontal scroll, the scroll bar position comes between body and footer templates.

Image:
![issue](https://user-images.githubusercontent.com/18315860/49223120-7f62a900-f3e6-11e8-8259-aaf035c8329a.png)

**Expected behavior**
Scrollbar bar to be after the footer.

**Minimal reproduction of the problem with instructions**
`<p-treeTable [value]="files" [columns]="columns" [scrollable]="true" >
                                        <ng-template pTemplate="colgroup" let-columns>
                                                <colgroup>
                                                    <col *ngFor="let col of columns" style="width:150px">
                                                </colgroup>
                                        </ng-template>
                                        <ng-template pTemplate="header" let-columns>
                                            <tr [ttRow]="rowNode">
                                                <th *ngFor="let col of columns" [ttSortableColumn]="col.field" >
                                                    {{col.header}}
                                                    <p-treeTableSortIcon [field]="col.field"></p-treeTableSortIcon>
                                                </th>
                                            </tr>
                                        </ng-template>
                                        <ng-template pTemplate="body" let-rowNode let-rowData="rowData" let-columns="columns">
                                            <tr>
                                                <td *ngFor="let col of columns; let i = index">
                                                    <p-treeTableToggler [rowNode]="rowNode" *ngIf="i == 0"></p-treeTableToggler>
                                                    {{rowData[col.field]}}
                                                </td>
                                            </tr>
                                        </ng-template>
                                        <ng-template pTemplate="footer">
                                                <tr>
                                                    <td>Totals</td>
                                                    <td>$3,283,772</td>
                                                    <td>$2,126,925</td>
                                                </tr>
                                        </ng-template>
                                    </p-treeTable>`

**Please tell us about your environment:**

* **Angular version:** 7.0.4

* **PrimeNG version:** 7.0.0-beta.1

* **Browser:** [all ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by mertsincan** [comment]
All of our projects like PrimeFaces, PrimeNg, PrimeReact, PrimeUI are the same by design. Exp;
https://www.primefaces.org/showcase/ui/data/datatable/scroll.xhtml

Therefore, unfortunately, we don't think of changing this structure. 

Best Regards,
