### ISSUE TITLE
VirtualScroller wrong behaviour with lazy loading

### ISSUE THREAD

**Issue by AndreaBarbasso** [primefaces/primeng#6931]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-virtualscroller-issues?file=src%2Fapp%2Fapp.component.html

**Current behavior**
The whole area that can be scrolled is a multiple of the `rows` attribute, and not defined by the `totalRecords` attribute, once the end of the dataset is reached.

Last but not least, if the whole dataset lenght is less than - but close enough to - a multiple of the `rows` attribute, lazy loading does not trigger for the last few items.

**Expected behavior**
VirtualScroller dataset container height should only be dependent on the `totalRecords` attribute.
All items should be loaded into VirtualScroller.

**Minimal reproduction of the problem with instructions**
Just scroll the stackblitz and look at the console.

**What is the motivation / use case for changing the behavior?**
This is both a template and logic broken behaviour.

**Please tell us about your environment:**
Win10, Webstorm.

* **Angular version:** 7.x

* **PrimeNG version:** 7.0.0

* **Browser:** Tested on Chrome.

* **Language:** Typescript.

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists wit|h the new version please create a new issue with our stackblitz template.
