### ISSUE TITLE
Autocomplete control does not validate properly when you empty the control

### ISSUE THREAD

**Issue by BobFleischman** [primefaces/primeng#6934]
I HAVE POSTED A PULL REQUEST WITH A ONE LINE FIX.

If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Waiting Time: ~8 weeks.

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**

When we start to type and then empty the field it does not throw the 'Required' error.

**Expected behavior**

It should throw the required error.

**Minimal reproduction of the problem with instructions**

Set up an autocomplete with form builder and a Required validator. Select something and then delete it.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows, Visual Studio Code

* **Angular version:** 6 and 7

* **PrimeNG version:** 6.X and 7X

* **Browser:** Chrome XX | Firefox XX | IE XX | 

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Fixed via PR
