### ISSUE TITLE
Re: OrderList does not highlight drop points

### ISSUE THREAD

**Issue by eloiqs** [primefaces/primeng#6936]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-ajd8d9

**Current behavior**
In 7.x when I drag a draggable orderlist item to a droppoint, the ui-orderlist-droppoint-highlight class does not add a background-color to the droppoint.

**Expected behavior**
In 6.x it would add the ui-state-highlight class and effectively change the style of the droppoint.

**Minimal reproduction of the problem with instructions**
Refer to the repro project on above stackblitz link.
> * the primeng version is 7.0
> * no theme is included in angular.json
> * ~primeicons/primeicons.css, ~primeng/resources/primeng.min.css, ~primeng/resources/themes/_theme.scss are imported in styles.css

**What is the motivation / use case for changing the behavior?**
Backward compatibility

**Please tell us about your environment:**
We do not want to use any of the provided free primeng themes because it adds complexity to our custom css (we would need to be super specific with the selectors for overriding certain styles). We prefer overriding some of the variables and applying custom styles on the primeng classes. The change in #6915 should not break our use case.

* **Angular version:** 5.X
7.1

* **PrimeNG version:** 5.X
7.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

* **Node (for AoT issues):** `node --version` =   8.12.0

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/issues/6915

**Comment by eloiqs** [comment]
@cagataycivici please, this is not _fixed_ by #6915, it is _caused_ by it as I explained in the issue.

**Comment by JACrazy** [comment]
The issue is that _theme.scss doesnt include styling for highlighting the drop point.
The nova-light theme is also missing this on PrimeNG 6.1.6 (the issue that brought me here), whereas 7.x does have it.

This can be fixed by adding this:

```
body .ui-orderlist .ui-orderlist-list .ui-orderlist-droppoint-highlight {
    background-color: #007ad9;
}
```
