### ISSUE TITLE
p-calendar with range and readonlyInput=false

### ISSUE THREAD

**Issue by braatzh** [primefaces/primeng#6937]
**I'm submitting a ...** 
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

I found the bug here:
In calendar.ts/onUserInput() there is a call to this.isSelectable(value.getDate(), ...
But in case of selectionMode="range" value is an array -> causes an error when try to call value.getDate().

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-fjpcup

**Current behavior**
not possible to edit a date-range via textfield

**Expected behavior**
like it was in primeng 6.X

**Minimal reproduction of the problem with instructions**
try to change the date-range via textfield here:
https://stackblitz.com/edit/github-fjpcup

* **Angular version:** 7.X

* **PrimeNG version:** 7.X

* **Browser:** [all ]
 
* **Language:** [all]

**Comment by Pikadili83** [comment]
I'm having the same problem, please fix...

**Comment by mateusz-klosinski** [comment]
We're having same issue. In docs range calendar has readonly input by default. If it is desired behaviour please secure it somehow because now it is throwing an error when calendar is using time picker additionaly.

`vendor.js:61083 ERROR TypeError: Cannot read property '1' of null
    at Calendar.push../node_modules/primeng/components/calendar/calendar.js.Calendar.validateHour (vendor.js:102157)
    at Calendar.push../node_modules/primeng/components/calendar/calendar.js.Calendar.incrementHour (vendor.js:102079)
    at Calendar.push../node_modules/primeng/components/calendar/calendar.js.Calendar.repeat (vendor.js:102114)
    at Calendar.push../node_modules/primeng/components/calendar/calendar.js.Calendar.onTimePickerElementMouseDown (vendor.js:102094)`.

Steps to reproduce:
1. Configure calendar selectionMode = 'range', readonlyInput = false, showTime = true
2. Assign date range using date picker
3. Change anything inside input using keyboard.
4. Try to change the hour/minute value using time picker arrows.

**Comment by codehunter13** [comment]
I have the same problem. When typeing a range in a calendar, the whole input gets cleared
Please fix

Thx

**Comment by serjstratu** [comment]
The same problem i have

                       <p-calendar
                            id="calendar"
                            selectionMode="range"
                            showButtonBar="true"
                            pattern="MM-dd-yyyy"
                            [readonlyInput]="true"
                            [numberOfMonths]="3"
                            [placeholder]="rangeDates"
                            [(ngModel)]="rangeDates"
                            (ngModelChange)="calendarDatesChange($event)"
                            [showIcon]="true"
                        >


then i try edit manual by keyboard i have null value

**Comment by piotrkorlaga** [comment]
I created PR for this bug #7580 :)
