### ISSUE TITLE
BUG: split button in a table - drop down menu is not visible

### ISSUE THREAD

**Issue by ivan-meridianbanc-com** [primefaces/primeng#6944]
I tried to make an example in stackblitz, but it is very difficult.

**Comment by ivan-meridianbanc-com** [comment]
The table is with resizable columns

**Comment by JacobSiegle** [comment]
I cannot tell for sure without a stackblitz, but try adding the "appendTo" property to the split button and append it to body.

**Comment by ivan-meridianbanc-com** [comment]
> I cannot tell for sure without a stackblitz, but try adding the "appendTo" property to the split button and append it to body.

I am using [appendTo]="body". It doesn't work.

Here is a example:
https://github.com/ivan-meridianbanc-com/primeng-splitbutton-bug

npm install
ng serve
http://localhost:4200/#/table/colresize

See attached screenshot:

![screenshot 2018-12-04 at 9 33 42](https://user-images.githubusercontent.com/23169794/49426015-dcc07680-f7a7-11e8-9ec2-5beb226ace53.png)

**Comment by ivan-meridianbanc-com** [comment]
Sorry, appendTo="body" works. You may close the issue
