### ISSUE TITLE
Sortable Column with deep parameters not working

### ISSUE THREAD

**Issue by dalesupa22** [primefaces/primeng#6946]
Sortable Column with deep parameters not working.

If you have the following structure PERSON.PERSONAL_INFORMATION.LEGAL_ID the sortable function triggers and exception....
Sort only works with simple attributes but not to references objects inside objects.

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template. 
And there is an example for deep parameters you can use like this; 
https://stackblitz.com/edit/github-cx3sxh
