### ISSUE TITLE
P-table replacing content of any section with component breaks Table CSS

### ISSUE THREAD

**Issue by s13571** [primefaces/primeng#6949]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/github-8u3dcp

**Current behavior**
Replacing content of for instance section header inside `<ng-template pTemplate="header" let-columns>` with angular component (for instance `<header-component>`) breaks CSS. Column headers doesn't get any default primeNG styling. 

**Expected behavior**
Custom component for header or any other section should get also styling.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/github-8u3dcp

* **Angular version:** 7

* **PrimeNG version:** 7

**Comment by cagataycivici** [comment]
You need to use ng-template here.
