### ISSUE TITLE
DynamicDialogModule Could not find a declaration file for module

### ISSUE THREAD

**Issue by sorcerb** [primefaces/primeng#6954]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
Can't import dynamicdialog in module file 
`import { DynamicDialogModule } from 'primeng/dynamicdialog';`

All another modules work fine.
[https://i.imgur.com/IyfcvwN.png](https://i.imgur.com/IyfcvwN.png)

Could not find a declaration file for module 'primeng/dynamicdialog'. '****/node_modules/primeng/dynamicdialog.js' implicitly has an 'any' type.
  Try `npm install @types/primeng` if it exists or add a new declaration (.d.ts) file containing `declare module 'primeng/dynamicdialog';` [7016]

* **Angular version:** 7.1.0
* **PrimeNG version:**  7.0.0

**Comment by yigitfindikli** [comment]
Can you try with PrimeNG version 7.0.0 ?

**Comment by sorcerb** [comment]
> Can you try with PrimeNG version 7.0.0 ?

Yes, I update version. 
Angular version: 7.1.0
PrimeNG version: 7.0.0

**Comment by madonkey** [comment]
I noticed dynamicdialog doesn't appear to have a d.ts file. Adding a _dynamic.d.ts_ file to your _node_modules/primeng/_ folder with the export fixes this.

`export * from 'primeng/components/dynamicdialog/dynamicdialog';`

**Comment by TheParad0X** [comment]
Same problem with ng build --prod here

**Comment by ruchi-ag** [comment]
Same issue . How can I get the fix ?
