### ISSUE TITLE
After pageload children of Tree Module have no parents

### ISSUE THREAD

**Issue by MeMeMax** [primefaces/primeng#6958]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-vnhelx

**Current behavior**

After Pageload the children of the Tree Module do not have parents. After you open a tree the children do have parents.

**Expected behavior**

The parent property should be already there on page load.

**Minimal reproduction of the problem with instructions**
Load the stackblitz. Click on Movies -> Selected Nodes will be empty. Open Movies Tree -> Selected Nodes will be filled.

**What is the motivation / use case for changing the behavior?**
Bugfix

**Please tell us about your environment:**
See Stackblitz

* **Angular version:** 5.X
7.1

* **PrimeNG version:** 5.X
7.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

* **Node (for AoT issues):** `node --version` =

**Comment by MeMeMax** [comment]
The Stackblitz doesn´t seem to work. I got a new one: https://stackblitz.com/edit/github-vnhelx

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
