### ISSUE TITLE
Nested confirmDialogs do not work

### ISSUE THREAD

**Issue by javajohnHub** [primefaces/primeng#6960]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
```
**Current behavior**
if you try to call confirmationService.confirm() inside another confirmationService.confirm() it does not work as expected. the function inside accept() never runs. this.jumpStep() never runs.

**Expected behavior**
after making a choice on the first confirmdialog a second confirm dialog pops up to confirm another condition. jumpStep() runs as expected.

**Minimal reproduction of the problem with instructions**
```
this._confirmationService.confirm({
				message: '4852',
				accept: () => {
					this.getRfuList();
				},
				reject: () => {
					this._messageService.add({
						severity: 'info',
						summary: 'NO RFU',
						detail: 'RFU after mix cancelled.'
					});
					this._checkNextStep();
				},
				cancel: () => {
					this._messageService.add({
						severity: 'warn',
						summary: 'NO RFU',
						detail: 'RFU after mix cancelled.'
					});
					this._checkNextStep();
				}
			});

private _checkNextStep() {
			this._confirmationService.confirm({
				message: `Continue to next step ?`,
				accept: () => {
					this.jumpStep(this._step.stepNmbr + 1);
					this._messageService.add({
						severity: 'info',
						summary: 'Next step',
						detail: `Next step ${this._step.stepNmbr}`
					});
				},
				reject: () => {
					this._messageService.add({
						severity: 'info',
						summary: 'Canceled',
						detail: 'Canceled.'
					});
				}
			});
	}
```
**What is the motivation / use case for changing the behavior?**
nested confirmation dialogs

**Please tell us about your environment:**
vsCode, node, angular 7

* **Angular version:** 7.0.2

* **PrimeNG version:** 6.0.0-beta.1

* **Browser:** chrome

**Comment by cagataycivici** [comment]
I’m unable to replicate with the latest PrimeNG 9. If the issue still persists with the new version please create a new issue with our stackblitz template.

**Comment by nateconq** [comment]
Can this be reopened?  7 is LTS and it is still an issue in 7.1.3

**Comment by nateconq** [comment]
Nested confirmations do work in a way. You have to create multiple <p-dialogConfirmation> with a different key value on each nested cofirmation you want.  If you want 3 nested confirmations, you need three html elements.  On your code side you would reference those keys appropriately.  Here is an example http://plnkr.co/edit/zT4F2SbdPzjl7Jfu2IdW?p=preview&preview
