### ISSUE TITLE
Pagination Support for Virtual Scrolling

### ISSUE THREAD

**Issue by alexwiese** [primefaces/primeng#6961]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-bncamg

**Current behavior**
When virtual scrolling is enabled with pagination, when scrolling, the page resets to the first page.

**Expected behavior**
When scrolling, the page does not reset to the first page.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/github-bncamg
Go to second or third page, scroll, notice that page resets to 1.

**Please tell us about your environment:**

* **Angular version:** 7.1.1

* **PrimeNG version:** 7.0

* **Browser:** Chrome, Edge
 
* **Language:** All

**Comment by alexwiese** [comment]
This bug is still present in 7.0.1

**Comment by philipebr** [comment]
@cagataycivici @alexwiese I'm with this problem too. I'm using Prime 7.1.0.

**Comment by alexwiese** [comment]
@yigitfindikli any update on this? I would think this is quite a major issue. Still happening on PrimeNG 7.1.0

**Comment by cagataycivici** [comment]
VirtualScrolling for Table is reimplemented from the ground up (#8855) and this particular case i no longer an issue with the new implementation.
