### ISSUE TITLE
Can't set values of Slider with ranged values programmatically

### ISSUE THREAD

**Issue by lippomano** [primefaces/primeng#6964]
**I'm submitting a ...** 
[X] bug report => Search github for a similar issue or PR before submitting

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-slider-range

try to click the button that increases the ranged values, you don't see any moves in the slider until you click on it.

**Current behavior**
If you change the value of slider values in the component I don't see any changes in the html.

**Comment by yigitfindikli** [comment]
This is about angular not PrimeNG. Ngmodel is  looking to reference for the changes. Reference not changing when updating array.

example code; 

`
next() {
    let min = this.val[0];
    let max = this.val[1];
    this.val = new Array<number>();

    min++;
    this.val = [min,max]
    console.log(this.val)
  }
`

**Comment by scorpion86** [comment]
Then what we should do?

**Comment by KubaJakubowski** [comment]
Faced the same issue.
If you want to set value of slider **instead** of doing it like this:
`values[0] = value;`

do it like this:
`values = [value, values[1]];`
You need to change whole array, not one value

**Comment by AnirudhWT** [comment]
valueChange(e: any, item: any) {
    this.array.forEach((element:{
    label: String;
    filterRange: Array<number>;
    minLimit: number;
    maxLimit:number;
    key:String
    }) => {
      if (item.key == element.key) {
        element.filterRange[0] = e.values[0];
        element.filterRange[1] = e.values[1];
        ------OR-----
        element.filterRange = e.values
      }
    });
  }

I am trying to update dynamically . 

Please help If anybody is having solution for setting values dynamically on slider .


ISSUE :: v1.js:1 ERROR Error: InvalidPipeArgument: '[object Object]' for pipe 'SlicePipe'
