### ISSUE TITLE
No right border by using inputgroup in combination with floating label

### ISSUE THREAD

**Issue by morula** [primefaces/primeng#6972]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/angular-inputgroup

**Current behavior**
No right border by using inputgroup in combination with floating label. 
Dropdown and Calendar control seems to works as expected.

**Expected behavior**
The right border should be visible.

** Environment
PrimeNg V 7.0.0 with Nova-light

**Comment by cagataycivici** [comment]
I’m unable to replicate with the latest PrimeNG 9. If the issue still persists with the new version please create a new issue with our stackblitz template.
