### ISSUE TITLE
p-Overlaypanel outside the viewport

### ISSUE THREAD

**Issue by P3tronius** [primefaces/primeng#6973]
Hello,

With primeng 6 the p-overlaypanel component had a onAfterShow method that was useful to reposition the panel inside the screen (for exemple when the height is big it can go outside the screen).
Would it be possible to re-add this hook?
Otherwise the https://github.com/primefaces/primeng/issues/2567 would be awesome!

**Comment by xexio** [comment]
Same problem with PrimeNG 7

**Comment by cagataycivici** [comment]
I’m unable to replicate with the latest PrimeNG 9. If the issue still persists with the new version please create a new issue with our stackblitz template.
