### ISSUE TITLE
SelectButton templating is not aligned with other Select components

### ISSUE THREAD

**Issue by Spiral1401** [primefaces/primeng#6974]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-yq1342

**Current behavior**
Pretty odd behavior. When the SelectItem has the "icon" property set, the item object for the template is set to the value of the "value" property of the SelectItem. When it has no "icon" property, the item object is the whole object.

**Expected behavior**
Template let-item object to always be the root SelectItem object

**Minimal reproduction of the problem with instructions**
In stackblitz change first selectitem "icon" property (for ex. "icon" to "iconx")

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/commit/81659ccd24cb1a15dc66ed424ab4d5d5221164b1
