### ISSUE TITLE
7.0.0 - can't tab off calendar in Firefox

### ISSUE THREAD

**Issue by joeberger** [primefaces/primeng#6975]
**I'm submitting a ...**  
```
[ x] bug report => Search github for a similar issue or PR before submitting

```

**Current behavior**
Can't tab off the calendar in Firefox

**Expected behavior**
User should be able to tab through the form

**Minimal reproduction of the problem with instructions**

Open https://www.primefaces.org/primeng/#/calendar in Firefox. Click on any calendar input.
Press TAB key. Nothing happens. Expected: next calendar input field is focused.

**Please tell us about your environment:**
Mac, with latest software.

* **PrimeNG version:** 7.0.0

* **Browser:** Firefox 63.0.3 (64-bit)

**Comment by kounelios13** [comment]
I can confirm this.It doesn't work on firefox.However chrome has no problem

**Comment by Pikadili83** [comment]
The same problem here...

**Comment by boisamazing** [comment]
**Update:**

- This problem exists still in PrimeNG version 8.

**Environment:**

- PrimeNG version: 8.0.4

- Browser: Firefox 71.0 (64-bit)

This issue should be considered by PrimeFaces team, but cannot wait for the official release. Is there a workaround to solve this problem, or any updates?

**Comment by yigitfindikli** [comment]
fixed in https://github.com/primefaces/primeng/issues/4695
