### ISSUE TITLE
Primeng p-autocomplete clear icon on single selection

### ISSUE THREAD

**Issue by SRICHANDANCHINNAM** [primefaces/primeng#6985]
I am using Primeng 6.1.7... I am not able to see clear icon in p-autocomplete for single selection..

I have used <p-autocomplete [type]="''search" ....></p-autocomplete>

But no luck....

Can you please resolve this issue...

Thanks
Srichandan
![capture](https://user-images.githubusercontent.com/39694828/49852585-9227a580-fe0a-11e8-98e2-a4602030254e.JPG)

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.
