### ISSUE TITLE
PrimeNg 7.0.0 build is failed AOT

### ISSUE THREAD

**Issue by druha95** [primefaces/primeng#6987]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Build is failed

ERROR in node_modules/primeng/components/table/table.d.ts(17,24): error TS1005: '=' expected.
node_modules/primeng/components/table/table.d.ts(17,86): error TS1005: '(' expected.
node_modules/primeng/components/table/table.d.ts(18,29): error TS1005: '=' expected.
node_modules/primeng/components/table/table.d.ts(18,72): error TS1005: '(' expected.
node_modules/primeng/components/table/table.d.ts(19,31): error TS1005: '=' expected.
node_modules/primeng/components/table/table.d.ts(19,75): error TS1005: '(' expected.
node_modules/primeng/components/table/table.d.ts(20,25): error TS1005: '=' expected.
node_modules/primeng/components/table/table.d.ts(20,69): error TS1005: '(' expected.
node_modules/primeng/components/table/table.d.ts(21,32): error TS1005: '=' expected.
node_modules/primeng/components/table/table.d.ts(21,76): error TS1005: '(' expected.
node_modules/primeng/components/table/table.d.ts(22,27): error TS1005: '=' expected.
node_modules/primeng/components/table/table.d.ts(22,70): error TS1005: '(' expected.

**Expected behavior**
Build is success

**Please tell us about your environment:**
Ubuntu

* **Angular version:** 5.X
Angular 5.0.3

* **PrimeNG version:** 5.X
7.0.0
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

* **Node (for AoT issues):** `node --version` =  
 v8.9.2

**Comment by cagataycivici** [comment]
You need to use Angular 7 with PrimeNG 7.

**Comment by AndJab** [comment]
Hi cagataycivici,

I have the same problem using version 7 with PrimeNG 7.

I fixed it changing table.d.ts file.

Changes in line 9 from:

`import { Subscription } from 'rxjs';`

to:

`import { Subscription, Observable } from 'rxjs';`

And lines 17-22 from:

`sortSource$: import("rxjs/internal/Observable").Observable<SortMeta | SortMeta[]>;
 selectionSource$: import("rxjs/internal/Observable").Observable<{}>;
 contextMenuSource$: import("rxjs/internal/Observable").Observable<any>;
 valueSource$: import("rxjs/internal/Observable").Observable<any>;
 totalRecordsSource$: import("rxjs/internal/Observable").Observable<any>;
 columnsSource$: import("rxjs/internal/Observable").Observable<{}>;`

to:

`sortSource$: Observable<SortMeta | SortMeta[]>;
 selectionSource$: Observable<{}>;
 contextMenuSource$: Observable<any>;
 valueSource$: Observable<any>;
 totalRecordsSource$: Observable<any>;
 columnsSource$: Observable<{}>;`

**Comment by cagataycivici** [comment]
Send us a github project for review please, unable to replicate on our side.

**Comment by ChekTek** [comment]
I'm having the same issue with angular 5 and primeNG 7 is this truly an angular version issue?

**Comment by Satheesh10173** [comment]
I also having same problem in angular 6 "primeng": "^7.0.4" 

ERROR in node_modules/primeng/components/common/confirmationservice.d.ts(5,33): error TS1005: ';' expected.
node_modules/primeng/components/common/confirmationservice.d.ts(5,86): error TS1005: '(' expected.
node_modules/primeng/components/common/confirmationservice.d.ts(6,72): error TS1005: '(' expected.
node_modules/primeng/components/common/confirmationservice.d.ts(7,25): error TS1005: ',' expected.
node_modules/primeng/components/common/confirmationservice.d.ts(7,40): error TS1005: ';' expected.
node_modules/primeng/components/common/confirmationservice.d.ts(8,15): error TS1005: ';' expected.
node_modules/primeng/components/common/confirmationservice.d.ts(8,21): error TS1109: Expression expected.
node_modules/primeng/components/common/confirmationservice.d.ts(9,1): error TS1128: Declaration or statement expected.
node_modules/primeng/components/common/messageservice.d.ts(5,28): error TS1005: ';' expected.
node_modules/primeng/components/common/messageservice.d.ts(5,88): error TS1005: '(' expected.
node_modules/primeng/components/common/messageservice.d.ts(6,73): error TS1005: '(' expected.
node_modules/primeng/components/common/messageservice.d.ts(7,16): error TS1005: ',' expected.
node_modules/primeng/components/common/messageservice.d.ts(7,26): error TS1005: ';' expected.
node_modules/primeng/components/common/messageservice.d.ts(7,32): error TS1109: Expression expected.
node_modules/primeng/components/common/messageservice.d.ts(8,20): error TS1005: ',' expected.
node_modules/primeng/components/common/messageservice.d.ts(8,32): error TS1005: ';' expected.
node_modules/primeng/components/common/messageservice.d.ts(8,38): error TS1109: Expression expected.
node_modules/primeng/components/common/messageservice.d.ts(9,15): error TS1109: Expression expected.
node_modules/primeng/components/common/messageservice.d.ts(9,24): error TS1005: ';' expected.
node_modules/primeng/components/common/messageservice.d.ts(9,30): error TS1109: Expression expected.
node_modules/primeng/components/common/messageservice.d.ts(10,1): error TS1128: Declaration or statement expected.
node_modules/primeng/components/common/treedragdropservice.d.ts(5,23): error TS1005: ';' expected.
node_modules/primeng/components/common/treedragdropservice.d.ts(5,81): error TS1005: '(' expected.
node_modules/primeng/components/common/treedragdropservice.d.ts(6,80): error TS1005: '(' expected.
node_modules/primeng/components/common/treedragdropservice.d.ts(7,20): error TS1005: ',' expected.
node_modules/primeng/components/common/treedragdropservice.d.ts(7,40): error TS1005: ';' expected.
node_modules/primeng/components/common/treedragdropservice.d.ts(7,46): error TS1109: Expression expected.
node_modules/primeng/components/common/treedragdropservice.d.ts(8,19): error TS1005: ',' expected.
node_modules/primeng/components/common/treedragdropservice.d.ts(8,39): error TS1005: ';' expected.
node_modules/primeng/components/common/treedragdropservice.d.ts(8,45): error TS1109: Expression expected.
node_modules/primeng/components/common/treedragdropservice.d.ts(9,1): error TS1128: Declaration or statement expected.

**Comment by amedvedsy** [comment]
@cagataycivici 
it is working in dev or JIT build mode(even with Angular 5.x), but for AOT is not

**Comment by bansalanjali** [comment]
I was facing the same issue. check your ngPrime version and your Angular version, they both should be same.
