### ISSUE TITLE
Tooltip can flash rapidly depending on hover position.

### ISSUE THREAD

**Issue by JacobSiegle** [primefaces/primeng#6988]
**Current behavior**
https://stackblitz.com/edit/github-yzcdym

If you hover on the bottom side of the checkbox the tooltip will continue to flash rapidly creating / destroying DOM elements.

Chrome is the easiest to do it on.
Firefox/Edge try the corners.

**Comment by KensingtonTech** [comment]
I am observing this also.

**Comment by IssueX** [comment]
I have the same issue.

**Comment by JacobSiegle** [comment]
Not really having luck replicating this anymore in the latest chrome or FF so closing. Feel free to open another issue if it still happens to you.
