### ISSUE TITLE
can you provide a example. I mean how to use local template variable. I am using primeng 5.x its not working for me. same problem.

### ISSUE THREAD

**Issue by bishu40010961** [primefaces/primeng#6995]
`<ng-template let-col let-car="rowData" pTemplate="editor" #ref>
                    <p-calendar [(ngModel)]="car[col.field]" [appendTo]="ref" name="test" dateFormat="dd/mm/yy" placeholder="DD/MM/YYYY">
                    </p-calendar>
</ng-template>`

I am getting the calendar at the boottom-right corner of data-grid.

_Originally posted by @bishu40010961 in https://github.com/_render_node/MDEyOklzc3VlQ29tbWVudDQ0NzIzMDE1MA==/timeline/issue_comment#issuecomment-447230150_

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.

**Comment by simplicitytrade** [comment]
Would be nice if someone could take a look at the forum. There is a discussion about that problem without any responses yet.

https://forum.primefaces.org/viewtopic.php?f=35&t=53214&p=173932

**Comment by JacobSiegle** [comment]
In the forum link you posted RollFizzlebeef posted the solution to his own question.
```
<div #attachHere></div>
<p-calendar [appendTo]="attachHere"></p-calendar>
```

The code by dlarrieu in the 3rd comment is all sorts of messed up please ignore that one.
