### ISSUE TITLE
primeng and angular version compatibility

### ISSUE THREAD

**Issue by krishna1990fis** [primefaces/primeng#6997]
I have installed latest primeng version 7.0.0, after which i have started getting below error : 

`ERROR in node_modules/primeng/components/picklist/picklist.d.ts(67,28): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/primeng/components/picklist/picklist.d.ts(68,28): error TS1039: Initializers are not allowed in ambient contexts.`

following are the dependencies used currently in my project 

` "primeng": "^7.0.0",
"@angular/cli": "~6.2.3",
 "typescript": "^2.9.2"`

Let me know the reason why i started getting above error after updating to latest primeng version 7.0.0

**Comment by cagataycivici** [comment]
See https://github.com/primefaces/primeng/issues/6998
