### ISSUE TITLE
Panel Menu - No Router link for top parent element.

### ISSUE THREAD

**Issue by mustafasadikot** [primefaces/primeng#700]
Considering the situation where the top parent element does not have any child items and itself needs to route to any specific page, then the control does not work in this scenario. I would like to have the panel menu setup so that even if the top parent does not have any child items, it should be able to use the router link and not to open as a blank element.

**Comment by cagataycivici** [comment]
This is available in recent PrimeNG releases, can't remember the exact version but I'd suggest trying 4.0.x.
