### ISSUE TITLE
p-textarea resize bug when used in an overlay + tabs

### ISSUE THREAD

**Issue by stevenvanryckeghem** [primefaces/primeng#7000]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-autoresize-textarea-bug

**Current behavior**

* Click on the button, an overlay opens
* Click somewhere in the page so the overlay disappears
* Click again on the button to see the overlay

The textarea gets "height: 0px"

If you remove the "autoResize" attribute, the bug doesn't manifest.
The same bug appears when the textarea is in a tab (and you switch tabs)

**Expected behavior**

The textarea doesn't resize to 0px height...

**What is the motivation / use case for changing the behavior?**

To have a bugfree PrimeNG :)

**Please tell us about your environment:**

* **Angular version:** 7.X

* **PrimeNG version:** 7.X

* **Browser:** 
Latest Chrome + Firefox

**Comment by Nawsen** [comment]
+1

**Comment by m-burger** [comment]
+1

**Comment by Arcturuss** [comment]
+1

**Comment by jimmycallaghan** [comment]
I'm seeing this exact problem. I am using primeng11.0.0-rc.1 and angular 11. Has this bug been reintroduced or am I doing something stupid? I have a textarea with autoResize="autoResize" in a tab. When the tab is opened, it has height: 0px. When I click into the field, it resizes correctly.

**Comment by testowy-uzytkownik-1** [comment]
Not fixed yet. 
Related to #9231
