### ISSUE TITLE
filter doesn't reset value in p-multiSelect 

### ISSUE THREAD

**Issue by kirillkorneenko** [primefaces/primeng#7002]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
resetFilterOnHide does not work correctly. After the panel is hidden , the visibleOptions is not cleared and after that the toggleAll does not correctly work

**Expected behavior**
The filter is cleared and all values are selected.

**Minimal reproduction of the problem with instructions**

Incorrect behavior occurs when you add resetFilterOnHide.
- Enter the filter
- Hide p-multiSelect (panelHide)
- Open p-multiSelect again and select all values (toggleAll)
Selects values suitable for the filter before cleaning

**What is the motivation / use case for changing the behavior?**
Need to clear the visibleOptions on the panelHide, and then toggleAll will work correctly

**Please tell us about your environment:**

* **Angular version:** 6.X

* **PrimeNG version:** 6.X

* **Browser:** all
 
* **Language:** all

* **Node (for AoT issues):** `node --version` = 6.4.1

**Comment by cagataycivici** [comment]
Can you try with 7.0.1 please.

**Comment by kirillkorneenko** [comment]
Component works correctly in version 7

> Можете ли вы попробовать с 7.0.1, пожалуйста.

**Comment by cagataycivici** [comment]
Glad to hear.
