### ISSUE TITLE
Calendar yearRange only works with literals (see #1125)

### ISSUE THREAD

**Issue by mfish0005** [primefaces/primeng#7006]
Reported this in #1125 a few months ago but it went unnoticed.  Reported again today but figured I would create another issue just in case.

Calendar's yearRange will only work if you pass it a literal e.g. `yearRange="1902:2012"`

Here is an example
```
this.yearRange: string = '';

this.yearRange = (this.minBirthdate.getFullYear()).toString() + ':' + (this.maxBirthdate.getFullYear().toString());

<p-calendar inputStyleClass="input" name="dob" [yearNavigator]="true" [monthNavigator]="true" yearRange="yearRange" required placeholder="Select birthdate..." [(ngModel)]="dob"></p-calendar>
```

I've tried everything I can think of but the year dropdown always shows up empty.  My solution was to use Angular Material's datepicker instead.

**Comment by davidda** [comment]
You'll have to put brackets around the property name in order for angular to evaluate that content instead of passing it as a literal.

`[yearRange]="yearRange"`

Works for me.

**Comment by mfish0005** [comment]
Yes that works thanks @davidda 

It's always something simple.  I just never took the time to understand the significance of brackets around properties in Angular.
