### ISSUE TITLE
Disable step in primeng component ( STEPS ) 

### ISSUE THREAD

**Issue by krishna1990fis** [primefaces/primeng#7012]
how to disable the step conditionally in p-step primeng component ?

`<p-steps [model]="items"  [readonly]="true"></p-steps>`
with the above readonly attribute we can disable the click functionality and enable it by dynamically changing the boolean value of readonly attribute.

Problem:
We can not do this enable/disable for each indivisual step, rather it gets applied to the whole step component. 
How to resolve this issue ?

**Comment by gasparbarancelli** [comment]
@krishna1990fis 
See the model property of the Steps class. It is an array of MenuItem and the MenuItem object has a property named disabled, in the click event of the step it checks whether the component as a whole is readonly or if the clicked item is disabled. So you just set the true value to the disabled property of the MenuItem object that you pass to the step component model.

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.
