### ISSUE TITLE
Changing columns in Table while using state saving breaks the table

### ISSUE THREAD

**Issue by krojew** [primefaces/primeng#7013]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When the table restores it saved state and tries to render the header, it doesn't check if the current column count matches the count from the saved state. This results in trying to access elements in the column array for the "header" template which do not exist.

**Expected behavior**
The table should recognize that saved column state doesn't match the number of current columns and not try to access non-existing elements.

**Minimal reproduction of the problem with instructions**
1. Create a table with dynamic columns (having a 'field' and 'header' properties) and state key. Use the following header template:

`<ng-template pTemplate="header" let-columns>
    <tr>
      <th *ngFor="let col of columns" [pSortableColumn]="col.field" pResizableColumn pReorderableColumn>
        {{ col.header }}
        <p-sortIcon [field]="col.field"></p-sortIcon>
      </th>
    </tr>
  </ng-template>`

2. Save the state.
3. Remove some columns in the code.
4. Refresh the page.
5. The table with throw an exception when rendering the "header" template (trying to access a property of 'undefined').

**What is the motivation / use case for changing the behavior?**
Sate saving should be compatible with dynamic columns.

**Please tell us about your environment:**
Chrome, WIndows

* **Angular version:** 7.1.2

* **PrimeNG version:** 7.0.0

* **Browser:** Chrome 70, but probably all
 
* **Language:** TypeScript 3.1.6

* **Node (for AoT issues):** `node --version` =   10.14.2

**Comment by cagataycivici** [comment]
I’m unable to replicate with the latest PrimeNG 9. If the issue still persists with the new version please create a new issue with our stackblitz template.
