### ISSUE TITLE
ConfirmDialog set width 

### ISSUE THREAD

**Issue by skormel** [primefaces/primeng#7017]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
```

**Current behavior**
I've just upgraded to primeNG 7.0.3, and notice that some inputs of Dialog and confirmDialog are deprecated (width, height, minWidth, minHeight) by style input. This works correctly with Dialog but not with confirmdialog. I can't set its width without width input (but this it's deprecated).

I notice that confirmDialog Component doesn't have style or ngStyle input, but dialog yes.

**Test case**
https://github-w4h5cc.stackblitz.io

**Expected behavior**
Set width with new style input.

**Comment by skormel** [comment]
Attached a test case

https://stackblitz.com/github/kkviokjk

**Comment by danteorlando-acgov** [comment]
It looks like the docs were updated incorrectly on this. The style and styleClass properties were added to the section that describes the properties that are on the Confirmation instance that is passed to the confirm method on ConfirmationService. They should be added to the section below that describes the properties for p-confirmDialog.
