### ISSUE TITLE
P-Calendar is very slow in interactions for IE.

### ISSUE THREAD

**Issue by srikant** [primefaces/primeng#7020]
The P-Calendar is very slow in interactions for IE.
After 10 seconds the calendar popups.
Is it expected behaviour or any optimization to do in angular app ?

**Comment by JacobSiegle** [comment]
Seems just as fast in IE 11 as any other browser. Please make a stackblitz to reproduce the issue and please report the version of IE you're attempting to use.

**Comment by cagataycivici** [comment]
I’m unable to replicate with the latest PrimeNG 9. If the issue still persists with the new version please create a new issue with our stackblitz template.
