### ISSUE TITLE
P-Dialog with reactive form very slow in IE, Chrome, FireFox 

### ISSUE THREAD

**Issue by srikant** [primefaces/primeng#7021]
P-Dialog with Reactive Form causing the app long running scripts and eventually crashing the browser.

In Reactive Form, we have FormArray where dynamically adding form groups on button click, each formgroup contains pInputText, p-calendar, p-autocomplete.
I have seen rapid JSHeap Memory spikes in Chrome when input key events fired.

The Parent component has p-table, p-dialog. No idea, what causing the app go slow terribly, Even I move p-dialog to new component, the p-calendar  still slow in IE Browser.
Is it fine to render p-dialog where component already have p-table ?
Is it fine to render reactive forms in p-dialog ?
and is it ok to render p-input, p-calender, p-autocomplete in p-dialog?

Right now, IE performance is very slow comparing with other browsers

**Comment by JacobSiegle** [comment]
Relates to #7020 which sounds like an issue with their app. Please provide a stackblitz otherwise.

**Comment by cagataycivici** [comment]
I’m unable to replicate with the latest PrimeNG 9. If the issue still persists with the new version please create a new issue with our stackblitz template.
