### ISSUE TITLE
Required Validator for File Upload

### ISSUE THREAD

**Issue by ssprajput** [primefaces/primeng#7028]
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

There is no required validator that exists today for File Upload control. 
**Expected behavior**

Without this bug I should be able to mark the control required and in that case
1. If a user has not selected the files to upload, the submit button would be disabled using the reactive form's validation logic/
2. If a user clears the file list or remove all files one by one selected before, form becomes invalid and user is unable to submit form.

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

Angular 7 with reactive forms
* **Angular version:** 5.X

* **PrimeNG version:** 5.X

7.0.3

**Comment by ben12** [comment]
+1

Workaround solution:

```html
<input
    type="hidden"
    id="files"
    name="files"
    ngModel
    #files="ngModel"
    required
    />
<p-fileUpload
   [showUploadButton]="false"
   (onClear)="files.control.setValue(null)"
   (onRemove)="files.control.setValue(fileUpload.files.length > 1 ? 'done' : null)"
   (onSelect)="files.control.setValue('done')"
 ></p-fileUpload>
```

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by mrkshx** [comment]
This is still not fixed in current versions.
