### ISSUE TITLE
Change month in calendar programtically.

### ISSUE THREAD

**Issue by mridul16g** [primefaces/primeng#7029]
I am using two primeng calendars. I want to change the month and year of one calendar when the other one changes

**Comment by JacobSiegle** [comment]
Seems like you can just use "onSelect" on the one calendar and then change the ngModel of the other? Seems like a question unless i'm missing something. Please consider closing or producing a stackblitz.

**Comment by cagataycivici** [comment]
Please use forum for questions and support requests.
