### ISSUE TITLE
android dropdown and multiselect with filter fails

### ISSUE THREAD

**Issue by CyleClone** [primefaces/primeng#7030]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
```
**Minimal reproduction of the problem with instructions**
https://www.primefaces.org/ultima-ng/#/forms

Open the url on an android device and try to select something with both the dropdown and the multiselect.
The multiselect should close as soon as the focus is lost to the filter in the multiselect, dropdown without a filter works.

**Please tell us about your environment:**
Android 6 up to Android 9, Built-in Chrome Browser

* **Angular version:** 7.0.0

* **PrimeNG version:** 7.0.2

* **Browser:** Mobile Chrome  71.0.3578.99 | Android X.X Web Browser

**Comment by KentMercier** [comment]
An additional issue experienced is that clicking the multi select dropdown opens the menu for  a split second only, then rapidly closes precluding the opportunity to use the filter or select an option.
Thanks

**Comment by theojinchiu** [comment]
May we know when this will be fixed?

**Comment by SSTPIERRE2** [comment]
I'm also seeing this, at least on Android, with multiselects the filter input field gets focus so the soft keyboard pops up, pushing the whole dropdown up and then it actually closes, making it unusable 🤔

**Comment by BlackfootPL** [comment]
I've added a reason and temporary workaround in #7260 if you want...

**Comment by cagataycivici** [comment]
There are duplicates so closing this one.

**Comment by lenard-a** [comment]
Still experiencing this issue, easiest way to reproduce is to open the https://www.primefaces.org/primeng/multiselect page on an Android Device.
