### ISSUE TITLE
P-multiselect fails to stay open on Android Chrome

### ISSUE THREAD

**Issue by laspero** [primefaces/primeng#7033]
I'm submitting a bug report...

**Current behavior**
multiselect overlay pops up then goes away immediately on its own.

Occurs on component open

**Expected behavior**
component should remain open until user interacts.

**Minimal reproduction of the problem with instructions**
Fails on V7 Sample Code viewed from Android Chrome on Galaxy S8:
https://www.primefaces.org/primeng/#/multiselect

**Please tell us about your environment:**

* **Angular version:** 5.X

* **PrimeNG version:** 5.X
7.0

* **Browser:** 
Android 8.X Web Browser

**Comment by SSTPIERRE2** [comment]
I'm doing some searching around this same issue and hits are recent (a month or so old). Trying to get this fixed for our users; maybe we'll have to work around and hide the search filter on mobile.

**Comment by Canos** [comment]
any update on this?

**Comment by kienvaser** [comment]
Same problem here. To reproduce it take your chrome mobile browser (tested with different mobile phones and Android versions) and go to https://www.primefaces.org/primeng/#/multiselect

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
