### ISSUE TITLE
Option to control placement of popup menu

### ISSUE THREAD

**Issue by ctaylor-osv** [primefaces/primeng#7034]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

A popup menu always displays below the target element.

**Expected behavior**

Have the configuration options available, similar to `tooltipPosition` on `pTooltip`, on `p-menu` to be able to optionally position the menu to the left, right, or above the target element.

**What is the motivation / use case for changing the behavior?**

We are using the Material vertical ellipse icon (more_vert) in a button in a `p-table` row and would like to have it trigger a popup menu to the left of the icon, instead of below as below covers the actions on other rows.

**Comment by dmagill89** [comment]
any updates on this one?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
