### ISSUE TITLE
Multiselect Header Checkbox is not working correctly

### ISSUE THREAD

**Issue by yigitfindikli** [primefaces/primeng#7047]
<img width="247" alt="screen shot 2018-12-28 at 13 08 11" src="https://user-images.githubusercontent.com/19997575/50512377-a3c3ab00-0aa2-11e9-976c-1a69a1a1fcc3.png">
<img width="247" alt="screen shot 2018-12-28 at 13 11 37" src="https://user-images.githubusercontent.com/19997575/50512380-a7efc880-0aa2-11e9-9818-5d85712f9240.png">

**Comment by bagariaankit** [comment]
Was this fixed? 
I checked http://primefaces.org/primeng/#/multiselect and observed that its still breaking.

**Comment by taqi-cd** [comment]
Multiselect still has the same issue.

**Comment by KunalD2** [comment]
https://www.primefaces.org/primeng/showcase/#/multiselect
The latest version still has this breaking behavior.

Please let us know in which version will the fix be included?

**Comment by lakshmi2716** [comment]
Still its not working https://primeng.org/multiselect#filter . on select all with filter, previously selected items are cleared

**Comment by kroger-renu** [comment]
Hi @cagataycivici @yigitfindikli, this issue hasn't been resolved yet in the latest version 17.11.0. Please have a look and resolved it, it's a very much needed feature in a multiselect dropdown component.

**Comment by nook24** [comment]
Why is this issue closed? It is still not working with PrimeNG v19.

https://primeng.org/multiselect#filter

Steps to reproduce:

1. Select Rome and London
2. Search for `Istan`
3. Select Istanbul using the "Select All" checkbox next to the input fiel
4. Rome and London will be removed from the selection :(
