### ISSUE TITLE
Empty tooltips are still displayed

### ISSUE THREAD

**Issue by mmikeyy** [primefaces/primeng#705]
I have conditional tooltips (some elements generated by a *ngFor loop need them, others do not). 

I tried assigning empty text or null value to the tooltip for items not requiring one. The arrow and a small empty container are still rendered.

I just added these few lines to the tooltip.js code and the problem is solved:

``` javascript
 Tooltip.prototype.show = function () {
        if (!this.text){              // start
            return
        }                             //end
        this.create();
```

This would be a minor but welcome enhancement to the component.

**Comment by dzhavat** [comment]
Fixed in  #1361
