### ISSUE TITLE
Captcha causes error - Uncaught (in promise): Timeout - Captcha lib bug

### ISSUE THREAD

**Issue by JacobSiegle** [primefaces/primeng#7051]
Ongoing issue with recaptcha -
https://github.com/DethAriel/ng-recaptcha/issues/123

I'll leave the issue open for anyone else who stumbles upon it. Maintainer can close if they would like.

**Bug reproduce**
1) Swap quickly back and forth between captcha component and another component for a few seconds.
2) Wait about 10 seconds and see if the error pops up.
3) If the error does not show up go to step 1.

![image](https://user-images.githubusercontent.com/5766272/50526130-9e1b9480-0aa5-11e9-9b05-361975c0f5ba.png)

**Comment by JacobSiegle** [comment]
Seems fixed

**Comment by JacobSiegle** [comment]
Lied, it still happens. Didn't wait long enough.

**Comment by cagataycivici** [comment]
Seems like an issue with recaptcha.

**Comment by benjamin-wilson** [comment]
I was able to fix this issue by removing the <script> tag in index.html and doing this in the component i'm using captcha:

Inject:
```
private _renderer2: Renderer2,
@Inject(DOCUMENT) private _document: Document
```
In constructor:
```
    let script = this._renderer2.createElement('script');
    script.type = 'text/javascript';
    script.src = 'https://www.google.com/recaptcha/api.js?render=explicit&onload=initRecaptcha';
    script.async = true;
    script.defer = true;
    this._renderer2.appendChild(this._document.body, script);
```

**Comment by Abdul-Salam93** [comment]
This answer is not useful..if you remove the script tag in index.html, then the captcha is not show.
