### ISSUE TITLE
Prime Ng treetable treeTableToggler not displays text provided between html bookmark

### ISSUE THREAD

**Issue by AndJab** [primefaces/primeng#7052]
I wanted to toggle table row using not only treeTableToggler icon but also text provided in table cell but when I use in treeTable:
`<p-treeTableToggler [rowNode]="rowNode">Some text</p-treeTableToggler>`
It doesn't displays value "Some text".

**Comment by cagataycivici** [comment]
It is designed to display an icon, if you need to add text, you may do the following;

```xml
<p-treeTableToggler [rowNode]="rowNode">Some text</p-treeTableToggler>
<span>Some Text</span>
```
