### ISSUE TITLE
Accordion tabs are not compliant with high contrast standards

### ISSUE THREAD

**Issue by manidevzen3** [primefaces/primeng#7054]
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior **
 Accordion tab items text are visible in "Hyperlink" color i.e. Yellow in black theme and blue color in white theme.

** Expected behavior **
 Accordion tab items should be visible in white color text with black background in black theme, and black color text with white back background in white theme.

* **Angular version:** 4.1.3

* **PrimeNG version:** 4.2.1

**Comment by JacobSiegle** [comment]
If you are using the old themes from an old primeng version (aka 4.2.1), I don't think you'll get any support.

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
