### ISSUE TITLE
TurboTable edit mode cell closing doesn't work correctly

### ISSUE THREAD

**Issue by dkitchen-auro** [primefaces/primeng#7055]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://github-vjv5qo-wfftj4.stackblitz.io

**Current behavior**
regression of https://github.com/primefaces/primeng/issues/5368 - closeCellEdit method on p-table is gone
related to https://github.com/primefaces/primeng/issues/6753 - clicking anywhere outside the currently edited cell does not fire close events (tab, esc, enter are the only ways to fire)

the commit for https://github.com/primefaces/primeng/issues/6753 causes both issues

**Expected behavior**
should be able to close cells programmatically per docs
events should always fire when an editable cell closes

**What is the motivation / use case for changing the behavior?**
undocumented breaking regressions are bad
events that don't work are bad

using latest of everything; happens on all browsers and environments, it's pretty obvious from the raw code paths that these are bugs

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
