### ISSUE TITLE
Add virtualScroll feature to treeTable component

### ISSUE THREAD

**Issue by qad84** [primefaces/primeng#7056]
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

I'm dealing with performance problem when using p-treeTable to generate a lot of items (more than 2000 items)

It will very help full if we have virtualscroller inside p-treeTable.

Thanks

**Comment by helkatz** [comment]
would be fine to have such a feature

**Comment by poser55** [comment]
Just to ensure we mean the same thing when we write "virtualscroller": the idea is to only have the visible part (or at least a much smaller part) of the whole table in the DOM.  The following article talks about the concept: https://netbasal.com/a-taste-of-angular-material-virtual-scroll-f173c5c70a1  .
