### ISSUE TITLE
PrimeNG Calendar Blending UI to match UX layout

### ISSUE THREAD

**Issue by srikant** [primefaces/primeng#7058]
![calendar sketch was given by UX team](https://user-images.githubusercontent.com/360666/50624735-0c9a9f80-0f49-11e9-8626-bfe1291b2c29.png)
I'm using PrimeNG Calendar/date picker with Angular and only have one complaint.

Our Calendar UI is somewhat different than default Primeng calendar UI. Is there any option to change the layout to match exactly given in UX team?

I searched through the documentation but didn't see anything about this issue.

**Comment by JacobSiegle** [comment]
This is not possible with the calendar. I don't think they will add it.

**Comment by srikant** [comment]
Creating new calendar component to match the exact look and feel using existing Primeng's calendar. Let's see how it goes.

**Comment by cagataycivici** [comment]
Please use forum for questions and seek technical support.
