### ISSUE TITLE
Time control in calendar control gets hanged

### ISSUE THREAD

**Issue by RuchiDhore** [primefaces/primeng#7061]
[ ] bug report => Search github for a similar issue or PR before submitting

**Link to the reproduced issue:**
https://stackblitz.com/edit/prime-ng-calendar-vz2ydp
https://prime-ng-calendar-vz2ydp.stackblitz.io

**Current behavior**
Set the minimum and maximum dates (maximum is today) with time. Go to any date between minimum / maximum dates. Change the time in such a way that it is beyond the present time in maximum date. Go to maximum date in calendar and try changing the hours, the arrows have no effect on hour.

**Expected behavior**
When calendar is set with maximum date and its corresponding time, we should be able to use the time (hour) control and block the respective hours according to time in maximum date object. The behaviour is expected same for the minimum date.

**Minimal reproduction of the problem with instructions**
1. Set the minDate and maxDate with time
2. Go to any day between minDate and maxDate
3. Change time in such a way it is beyond the time in maxDate's time or early time for time in minDate
4. Now go to min date / max date in calendar

**Example:**
1. Set the minDate and maxDate with time:
    minDate is 3 days back
    maxDate is today and the timestamp (may be 10 o'clock) at which calendar was loaded 
2. Go to any day between minDate and maxDate
3. Change time in such a way it is beyond the time in maxDate's time or early time for time in minDate
    Go to yesterday's date and change time to ( 11 o'clock )
4. Now go to min date / max date in calendar
   Go to today's date in calendar and try changing the hour

**Please tell us about your environment:**
Angular version: 4.4.6
Operating system: Windows
IDE: Visual Studio Code
package manager: NPM
Angular CLI version: 1.2.7
PrimeNG version: 4.3.0
Browser: Latest Chrome

**Comment by JacobSiegle** [comment]
PrimeNG version: 4.3.0 - Please confirm this is an issue in the latest version of PrimeNG. As far as I know they don't support older versions.

**Comment by RuchiDhore** [comment]
Checked, the issue does not occur in latest PrimeNG version however also requires latest angular/cdk and corresponding dependencies. For some reason I cannot move to upper versions of angular nor angular/cdk :(

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
