### ISSUE TITLE
p-table: scrollHeight=100% does not work propertly

### ISSUE THREAD

**Issue by dmytro-gokun** [primefaces/primeng#7064]
I've searched through past issues and it seems it was experienced a lot by people. But I was not able to find any clear solution that worked in my case.

Here I create a simple stackblitz reproduction:

https://stackblitz.com/edit/angular-d9narm

I expect the table to fit the parent's content area and show the scrollbar when its needed. This also should work properly when the parent is resized.

It is such a basic scenario and still I cannot find a clear solution... Can anybody give me a hand?

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
