### ISSUE TITLE
Any way to navigate programmatically to the last page on table / grid?

### ISSUE THREAD

**Issue by dmitrynovik** [primefaces/primeng#707]
I would like to navigate to the last page of the paginated table after the new object was added - to display the object. I saw Paginator component has changePageToLast(), but I failed to find the way to communicate with Paginator,

**Comment by cagataycivici** [comment]
Please use forum for questions, basically you can get do;

```
<p-dataTable #dt
```

Then after getting dt via ViewChild;

```
dt.paginate({first: 20, rows: 10})
```
