### ISSUE TITLE
Please update website. 

### ISSUE THREAD

**Issue by sorariver** [primefaces/primeng#7070]
Currently I am checking ngprime and realized that there are few wrong codes. please..update it.

1.  ngOnInit() { this.tr }  =>unable to find. 
https://www.primefaces.org/primeng/#/calendar

2.Editor is not working. please check with quill.
  also, <Dependencies>part...
  angular-cli.json  is for old angular version. not the latest one..
  Please update it...

https://www.primefaces.org/primeng/#/editor

I report this issue is because there are many beginners refer website instead of github.
PLease update.....

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
