### ISSUE TITLE
Context menu shouldn't close upon clicking an item with children

### ISSUE THREAD

**Issue by MaximeMorin** [primefaces/primeng#7076]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://www.primefaces.org/primeng/#/contextmenu

**Current behavior**
When clicking on the menu item in yellow, the whole context menu closes.

![image](https://user-images.githubusercontent.com/5142935/50693225-5c8a6c80-1004-11e9-8c72-bfa309fd1b94.png)

**Expected behavior**
The context menu should remain open.

**Minimal reproduction of the problem with instructions**
1. Go to Demo page
2. Right click on the white space beside the PrimeNG logo.
3. Mouse over edit.
4. Click on edit.

**What is the motivation / use case for changing the behavior?**
Never seen a context menu close upon click when sub-items are available.  (Mind you, mostly a windows guy...)

**Please tell us about your environment:**
Demo page.

* **Angular version:** 5.X
Demo version.

* **PrimeNG version:** 5.X
Demo version.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome

**Comment by jgill248** [comment]
bump
