### ISSUE TITLE
Website sourcecode demo isn't equal to preview code ( dropDown ).

### ISSUE THREAD

**Issue by luanraithz** [primefaces/primeng#7078]
The source code ends with the following code:

```html
<h3>Group</h3>
<p-dropdown [options]="groupedCars" [(ngModel)]="selectedCar3" [style]="{'width':'150px'}" placeholder="Select a Car" [group]="true">
    <ng-template let-group pTemplate="group">
        <img src="assets/showcase/images/demo/flag/{{group.value}}" style="width:20px;vertical-align:middle" />
        <span style="margin-left:.25em">{{group.label}}</span>
    </ng-template>
</p-dropdown>
```
While the preview code has an "Selected car" below it's preview.

**Comment by sudheerj** [comment]
It should be corrected. You can always get the example from showcase repo.

**Comment by luanraithz** [comment]
@sudheerj Can you see the pull request? You will see what is wrong, it's just the code demo in the website, the running code is right.

**Comment by luanraithz** [comment]
That is the preview:
![preview](https://user-images.githubusercontent.com/27583162/50736279-92655780-11a2-11e9-853f-b464e75e9d34.png)

The source code of the preview (right one):
![source_code](https://user-images.githubusercontent.com/27583162/50736284-9db88300-11a2-11e9-94e7-b818a16b4815.png)

And the code demo in the website:
![code_demo](https://user-images.githubusercontent.com/27583162/50736285-aad57200-11a2-11e9-896e-c6d402770e96.png)

**Comment by cagataycivici** [comment]
Fixed now
