### ISSUE TITLE
When use in aspnet core spa with angular app 

### ISSUE THREAD

**Issue by sargin48** [primefaces/primeng#7081]
When use in aspnet core spa with angular app 

<img width="1440" alt="screen shot 2019-01-05 at 23 41 04" src="https://user-images.githubusercontent.com/3220540/50728997-6961aa00-1143-11e9-8cfa-784787aebe81.png">

Version     "primeng": "^7.0.3",

`
info: Microsoft.AspNetCore.SpaServices[0]
      ERROR in node_modules/primeng/components/common/confirmationservice.d.ts(5,33): error TS1005: ';' expected.
      node_modules/primeng/components/common/confirmationservice.d.ts(5,86): error TS1005: '(' expected.
      node_modules/primeng/components/common/confirmationservice.d.ts(6,72): error TS1005: '(' expected.
      node_modules/primeng/components/common/confirmationservice.d.ts(7,25): error TS1005: ',' expected.
      node_modules/primeng/components/common/confirmationservice.d.ts(7,40): error TS1005: ';' expected.
      node_modules/primeng/components/common/confirmationservice.d.ts(8,15): error TS1005: ';' expected.
      node_modules/primeng/components/common/confirmationservice.d.ts(8,21): error TS1109: Expression expected.
      node_modules/primeng/components/common/confirmationservice.d.ts(9,1): error TS1128: Declaration or statement expected.
      node_modules/primeng/components/common/messageservice.d.ts(5,28): error TS1005: ';' expected.
      node_modules/primeng/components/common/messageservice.d.ts(5,88): error TS1005: '(' expected.
      node_modules/primeng/components/common/messageservice.d.ts(6,73): error TS1005: '(' expected.
      node_modules/primeng/components/common/messageservice.d.ts(7,16): error TS1005: ',' expected.
      node_modules/primeng/components/common/messageservice.d.ts(7,26): error TS1005: ';' expected.
      node_modules/primeng/components/common/messageservice.d.ts(7,32): error TS1109: Expression expected.
      node_modules/primeng/components/common/messageservice.d.ts(8,20): error TS1005: ',' expected.
      node_modules/primeng/components/common/messageservice.d.ts(8,32): error TS1005: ';' expected.
      node_modules/primeng/components/common/messageservice.d.ts(8,38): error TS1109: Expression expected.
      node_modules/primeng/components/common/messageservice.d.ts(9,15): error TS1109: Expression expected.
      node_modules/primeng/components/common/messageservice.d.ts(9,24): error TS1005: ';' expected.
      node_modules/primeng/components/common/messageservice.d.ts(9,30): error TS1109: Expression expected.
      node_modules/primeng/components/common/messageservice.d.ts(10,1): error TS1128: Declaration or statement expected.
      node_modules/primeng/components/common/treedragdropservice.d.ts(5,23): error TS1005: ';' expected.
      node_modules/primeng/components/common/treedragdropservice.d.ts(5,81): error TS1005: '(' expected.
      node_modules/primeng/components/common/treedragdropservice.d.ts(6,80): error TS1005: '(' expected.
      node_modules/primeng/components/common/treedragdropservice.d.ts(7,20): error TS1005: ',' expected.
      node_modules/primeng/components/common/treedragdropservice.d.ts(7,40): error TS1005: ';' expected.
      node_modules/primeng/components/common/treedragdropservice.d.ts(7,46): error TS1109: Expression expected.
      node_modules/primeng/components/common/treedragdropservice.d.ts(8,19): error TS1005: ',' expected.
      node_modules/primeng/components/common/treedragdropservice.d.ts(8,39): error TS1005: ';' expected.
      node_modules/primeng/components/common/treedragdropservice.d.ts(8,45): error TS1109: Expression expected.
      node_modules/primeng/components/common/treedragdropservice.d.ts(9,1): error TS1128: Declaration or statement expected.
      node_modules/primeng/components/terminal/terminalservice.d.ts(4,27): error TS1005: ';' expected.
      node_modules/primeng/components/terminal/terminalservice.d.ts(4,74): error TS1005: '(' expected.
      node_modules/primeng/components/terminal/terminalservice.d.ts(5,75): error TS1005: '(' expected.
      node_modules/primeng/components/terminal/terminalservice.d.ts(6,24): error TS1005: ',' expected.
      node_modules/primeng/components/terminal/terminalservice.d.ts(6,33): error TS1005: ';' expected.
      node_modules/primeng/components/terminal/terminalservice.d.ts(6,39): error TS1109: Expression expected.
      node_modules/primeng/components/terminal/terminalservice.d.ts(7,26): error TS1005: ',' expected.
      node_modules/primeng/components/terminal/terminalservice.d.ts(7,35): error TS1005: ';' expected.
      node_modules/primeng/components/terminal/terminalservice.d.ts(7,41): error TS1109: Expression expected.
      node_modules/primeng/components/terminal/terminalservice.d.ts(8,1): error TS1128: Declaration or statement expected.
      node_modules/primeng/components/treetable/treetable.d.ts(14,24): error TS1005: ';' expected.
      node_modules/primeng/components/treetable/treetable.d.ts(14,86): error TS1005: '(' expected.
      node_modules/primeng/components/treetable/treetable.d.ts(15,72): error TS1005: '(' expected.
      node_modules/primeng/components/treetable/treetable.d.ts(16,75): error TS1005: '(' expected.
      node_modules/primeng/components/treetable/treetable.d.ts(17,72): error TS1005: '(' expected.
      node_modules/primeng/components/treetable/treetable.d.ts(18,20): error TS1005: ',' expected.
      node_modules/primeng/components/treetable/treetable.d.ts(18,44): error TS1005: ';' expected.
      node_modules/primeng/components/treetable/treetable.d.ts(18,50): error TS1109: Expression expected.
      node_modules/primeng/components/treetable/treetable.d.ts(19,24): error TS1005: ';' expected.
      node_modules/primeng/components/treetable/treetable.d.ts(19,30): error TS1109: Expression expected.
      node_modules/primeng/components/treetable/treetable.d.ts(20,23): error TS1005: ',' expected.
      node_modules/primeng/components/treetable/treetable.d.ts(20,29): error TS1005: ';' expected.
      node_modules/primeng/components/treetable/treetable.d.ts(20,35): error TS1109: Expression expected.
      node_modules/primeng/components/treetable/treetable.d.ts(21,21): error TS1005: ',' expected.
      node_modules/primeng/components/treetable/treetable.d.ts(21,27): error TS1005: ';' expected.
      node_modules/primeng/components/treetable/treetable.d.ts(21,33): error TS1109: Expression expected.
      node_modules/primeng/components/treetable/treetable.d.ts(22,1): error TS1128: Declaration or statement expected.
`

**Comment by lordango** [comment]
Got similar errors. Updated to 7.0.4

ERROR in node_modules/primeng/components/common/confirmationservice.d.ts(5,33): error TS1005: ';' expected.
node_modules/primeng/components/common/confirmationservice.d.ts(5,86): error TS1005: '(' expected.
node_modules/primeng/components/common/confirmationservice.d.ts(6,72): error TS1005: '(' expected.
node_modules/primeng/components/common/confirmationservice.d.ts(7,25): error TS1005: ',' expected.
node_modules/primeng/components/common/confirmationservice.d.ts(7,40): error TS1005: ';' expected.
node_modules/primeng/components/common/confirmationservice.d.ts(8,15): error TS1005: ';' expected.
node_modules/primeng/components/common/confirmationservice.d.ts(8,21): error TS1109: Expression expected.
node_modules/primeng/components/common/confirmationservice.d.ts(9,1): error TS1128: Declaration or statement expected.
node_modules/primeng/components/common/messageservice.d.ts(5,28): error TS1005: ';' expected.
node_modules/primeng/components/common/messageservice.d.ts(5,88): error TS1005: '(' expected.
node_modules/primeng/components/common/messageservice.d.ts(6,73): error TS1005: '(' expected.
node_modules/primeng/components/common/messageservice.d.ts(7,16): error TS1005: ',' expected.
node_modules/primeng/components/common/messageservice.d.ts(7,26): error TS1005: ';' expected.
node_modules/primeng/components/common/messageservice.d.ts(7,32): error TS1109: Expression expected.
node_modules/primeng/components/common/messageservice.d.ts(8,20): error TS1005: ',' expected.
node_modules/primeng/components/common/messageservice.d.ts(8,32): error TS1005: ';' expected.
node_modules/primeng/components/common/messageservice.d.ts(8,38): error TS1109: Expression expected.
node_modules/primeng/components/common/messageservice.d.ts(9,15): error TS1109: Expression expected.
node_modules/primeng/components/common/messageservice.d.ts(9,24): error TS1005: ';' expected.
node_modules/primeng/components/common/messageservice.d.ts(9,30): error TS1109: Expression expected.
node_modules/primeng/components/common/messageservice.d.ts(10,1): error TS1128: Declaration or statement expected.
node_modules/primeng/components/common/treedragdropservice.d.ts(5,23): error TS1005: ';' expected.
node_modules/primeng/components/common/treedragdropservice.d.ts(5,81): error TS1005: '(' expected.
node_modules/primeng/components/common/treedragdropservice.d.ts(6,80): error TS1005: '(' expected.
node_modules/primeng/components/common/treedragdropservice.d.ts(7,20): error TS1005: ',' expected.
node_modules/primeng/components/common/treedragdropservice.d.ts(7,40): error TS1005: ';' expected.
node_modules/primeng/components/common/treedragdropservice.d.ts(7,46): error TS1109: Expression expected.
node_modules/primeng/components/common/treedragdropservice.d.ts(8,19): error TS1005: ',' expected.
node_modules/primeng/components/common/treedragdropservice.d.ts(8,39): error TS1005: ';' expected.
node_modules/primeng/components/common/treedragdropservice.d.ts(8,45): error TS1109: Expression expected.
node_modules/primeng/components/common/treedragdropservice.d.ts(9,1): error TS1128: Declaration or statement expected.
node_modules/primeng/components/table/table.d.ts(15,24): error TS1005: ';' expected.
node_modules/primeng/components/table/table.d.ts(15,86): error TS1005: '(' expected.
node_modules/primeng/components/table/table.d.ts(16,72): error TS1005: '(' expected.
node_modules/primeng/components/table/table.d.ts(17,75): error TS1005: '(' expected.
node_modules/primeng/components/table/table.d.ts(18,69): error TS1005: '(' expected.
node_modules/primeng/components/table/table.d.ts(19,76): error TS1005: '(' expected.
node_modules/primeng/components/table/table.d.ts(20,70): error TS1005: '(' expected.
node_modules/primeng/components/table/table.d.ts(21,20): error TS1005: ',' expected.
node_modules/primeng/components/table/table.d.ts(21,44): error TS1005: ';' expected.
node_modules/primeng/components/table/table.d.ts(21,50): error TS1109: Expression expected.
node_modules/primeng/components/table/table.d.ts(22,24): error TS1005: ';' expected.
node_modules/primeng/components/table/table.d.ts(22,30): error TS1109: Expression expected.
node_modules/primeng/components/table/table.d.ts(23,23): error TS1005: ',' expected.
node_modules/primeng/components/table/table.d.ts(23,29): error TS1005: ';' expected.
node_modules/primeng/components/table/table.d.ts(23,35): error TS1109: Expression expected.
node_modules/primeng/components/table/table.d.ts(24,24): error TS1005: ',' expected.
node_modules/primeng/components/table/table.d.ts(24,30): error TS1005: ';' expected.
node_modules/primeng/components/table/table.d.ts(24,36): error TS1109: Expression expected.
node_modules/primeng/components/table/table.d.ts(25,31): error TS1005: ',' expected.
node_modules/primeng/components/table/table.d.ts(25,40): error TS1005: ';' expected.
node_modules/primeng/components/table/table.d.ts(25,46): error TS1109: Expression expected.
node_modules/primeng/components/table/table.d.ts(26,28): error TS1005: ',' expected.
node_modules/primeng/components/table/table.d.ts(26,36): error TS1005: ';' expected.
node_modules/primeng/components/table/table.d.ts(26,42): error TS1109: Expression expected.
node_modules/primeng/components/table/table.d.ts(27,1): error TS1128: Declaration or statement expected.
node_modules/primeng/components/terminal/terminalservice.d.ts(4,27): error TS1005: ';' expected.
node_modules/primeng/components/terminal/terminalservice.d.ts(4,74): error TS1005: '(' expected.
node_modules/primeng/components/terminal/terminalservice.d.ts(5,75): error TS1005: '(' expected.
node_modules/primeng/components/terminal/terminalservice.d.ts(6,24): error TS1005: ',' expected.
node_modules/primeng/components/terminal/terminalservice.d.ts(6,33): error TS1005: ';' expected.
node_modules/primeng/components/terminal/terminalservice.d.ts(6,39): error TS1109: Expression expected.
node_modules/primeng/components/terminal/terminalservice.d.ts(7,26): error TS1005: ',' expected.
node_modules/primeng/components/terminal/terminalservice.d.ts(7,35): error TS1005: ';' expected.
node_modules/primeng/components/terminal/terminalservice.d.ts(7,41): error TS1109: Expression expected.
node_modules/primeng/components/terminal/terminalservice.d.ts(8,1): error TS1128: Declaration or statement expected.
node_modules/primeng/components/treetable/treetable.d.ts(12,24): error TS1005: ';' expected.
node_modules/primeng/components/treetable/treetable.d.ts(12,86): error TS1005: '(' expected.
node_modules/primeng/components/treetable/treetable.d.ts(13,72): error TS1005: '(' expected.
node_modules/primeng/components/treetable/treetable.d.ts(14,75): error TS1005: '(' expected.
node_modules/primeng/components/treetable/treetable.d.ts(15,72): error TS1005: '(' expected.
node_modules/primeng/components/treetable/treetable.d.ts(16,20): error TS1005: ',' expected.
node_modules/primeng/components/treetable/treetable.d.ts(16,44): error TS1005: ';' expected.
node_modules/primeng/components/treetable/treetable.d.ts(16,50): error TS1109: Expression expected.
node_modules/primeng/components/treetable/treetable.d.ts(17,24): error TS1005: ';' expected.
node_modules/primeng/components/treetable/treetable.d.ts(17,30): error TS1109: Expression expected.
node_modules/primeng/components/treetable/treetable.d.ts(18,23): error TS1005: ',' expected.
node_modules/primeng/components/treetable/treetable.d.ts(18,29): error TS1005: ';' expected.
node_modules/primeng/components/treetable/treetable.d.ts(18,35): error TS1109: Expression expected.
node_modules/primeng/components/treetable/treetable.d.ts(19,21): error TS1005: ',' expected.
node_modules/primeng/components/treetable/treetable.d.ts(19,27): error TS1005: ';' expected.
node_modules/primeng/components/treetable/treetable.d.ts(19,33): error TS1109: Expression expected.
node_modules/primeng/components/treetable/treetable.d.ts(20,1): error TS1128: Declaration or statement expected.

**Comment by Rayleigh3105** [comment]
Getting the same Error.

**Comment by ManzerAh-Kore** [comment]
Your global Angular CLI version (7.1.1) is greater than your local
version (6.0.8). The local Angular CLI version is used.

Angular CLI: 6.0.8
Node: 10.13.0
OS: win32 x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      7.2.1
@angular/cli                      6.0.8
@angular/material                 7.2.1
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.3.3
typescript                        2.7.2
webpack                           4.8.3


package.json
---------------
    "primeicons": "^1.0.0",
    "primeng": "^7.0.4",
    "rxjs": "^6.0.0",
    "rxjs-compat": "^6.2.1",

What should I do?

**Comment by Rayleigh3105** [comment]
> Your global Angular CLI version (7.1.1) is greater than your local
> version (6.0.8). The local Angular CLI version is used.
> 
> Angular CLI: 6.0.8
> Node: 10.13.0
> OS: win32 x64
> Angular: 6.1.10
> ... animations, common, compiler, compiler-cli, core, forms
> ... http, language-service, platform-browser
> ... platform-browser-dynamic, router
> 
> ## Package Version
> @angular-devkit/architect 0.6.8
> @angular-devkit/build-angular 0.6.8
> @angular-devkit/build-optimizer 0.6.8
> @angular-devkit/core 0.6.8
> @angular-devkit/schematics 0.6.8
> @angular/cdk 7.2.1
> @angular/cli 6.0.8
> @angular/material 7.2.1
> @ngtools/webpack 6.0.8
> @schematics/angular 0.6.8
> @schematics/update 0.6.8
> rxjs 6.3.3
> typescript 2.7.2
> webpack 4.8.3
> 
> ## package.json
> ```
> "primeicons": "^1.0.0",
> "primeng": "^7.0.4",
> "rxjs": "^6.0.0",
> "rxjs-compat": "^6.2.1",
> ```
> What should I do?

Upgrade you Angular. Use this tool https://update.angular.io/

**Comment by ManzerAh-Kore** [comment]
I can't upgrade now however I can degrade primeng but to which version? I want to use confirmdialog service?

**Comment by Rayleigh3105** [comment]
I would just try the versions, because I have no clue where it works.
1. Delete your node_modules folder
2. add dependency "primeng": "^5.0.0", to your package.json 
3. run npm install

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.

**Comment by vishuhanda001** [comment]
why you have closed this

**Comment by jaitley** [comment]
I have same error. Please suggest the fix.

**Comment by selvamp** [comment]
@Rayleigh3105 It's worked for me. Thanks..
