### ISSUE TITLE
RTL Support for Scrolling

### ISSUE THREAD

**Issue by webnegar** [primefaces/primeng#7082]
p-table scrolling problem in RTL mode:

![problem](https://user-images.githubusercontent.com/7112978/50732635-2bd93d00-1194-11e9-9b3b-c1b8b2f698ab.jpg)

**Comment by webnegar** [comment]
do you have any plan to solve this issue?

**Comment by hojjatzangeneh** [comment]
it's true, I had this problem too,

**Comment by kia9372** [comment]
i had this problem too

**Comment by gh-mohammadi** [comment]
I had this problem too

**Comment by mansoorbaba** [comment]
I had this problem too

**Comment by M-Rostami** [comment]
I faced this issue several times. Pls solve that.

**Comment by sharifian-m** [comment]
I had this problem , too.
Please solve it.

**Comment by mojganmahmoodian** [comment]
Yes,i have this problem too.please solve this issue.

**Comment by nkm96** [comment]
I had this problem and really need RTL scrolling. please solve it.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
