### ISSUE TITLE
Autocomplete / Autofill 

### ISSUE THREAD

**Issue by Mr-Sloth** [primefaces/primeng#7086]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

I would like to be able to set the autocomplete/autofill off to all input elements.
https://www.w3schools.com/tags/att_input_autocomplete.asp

Browsers often autofill wrong formular fields.

**Comment by sudheerj** [comment]
You can still pass default attributes for inputtext and inputGroup etc. Is it missing for any specific component?

**Comment by Mr-Sloth** [comment]
Tright it with spinner and it does not seem to work.

**Comment by imkremen** [comment]
It's problem with Chrome https://bugs.chromium.org/p/chromium/issues/detail?id=587466

**Comment by cagataycivici** [comment]
Seems like a problem with chrome.
