### ISSUE TITLE
p-tree validateDrop subscribe error

### ISSUE THREAD

**Issue by sourdoth** [primefaces/primeng#7087]
[X ] bug report => Search github for a similar issue or PR before submitting

Hi, when i validate Drop in p-tree event.accept() works find, but when i put into a "subscribe" event.accept() get error

![image](https://user-images.githubusercontent.com/29101756/50768905-e6367600-1260-11e9-9dad-0975b1a55421.png)

**Minimal reproduction of the problem with instructions**
*****NOT WORK*****
this.serve.get().subscribe(
ok=>{
if(ok != null)
event.accept();
})
********WORK********
if(condition){
event.accept();
}

***PrimeNG version: **7.0.3*****

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
