### ISSUE TITLE
Keyboard Navigation inside a Editable Treetable

### ISSUE THREAD

**Issue by iArnoldo** [primefaces/primeng#7088]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
When i have a Treetable with editable Cells the Keyboard navigation that you recently implemented is not working.

**Expected behavior**
When you edit a cell the Row of that Cell should be marked as Selected and you should be able to Navigate via Keyboard like in a TreeTable without Editable Cells

**Minimal reproduction of the problem with instructions**
Create 2 Treetables one should be editable one should not. In the editable Treetable you cant navigate via the Keyboard in the non editable Treetable you can.

**What is the motivation / use case for changing the behavior?**
I have a Editable Treetable which should also be navigateable via Keyboard

**Please tell us about your environment:**

* **Angular version:** 7.1.4

* **PrimeNG version:** 7.0.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =  8.9.1

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
