### ISSUE TITLE
Not able to filter frozen columns 

### ISSUE THREAD

**Issue by gauravoodles** [primefaces/primeng#7089]
Hi @cagataycivici , I am not able to use search filter in frozen table i.e. it's not searching in the frozen columns using filterGlobal($event.target.value, 'contains'). Is there any way to handle this ?

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.

**Comment by Dinesh102** [comment]
There is no opt solution for it

> Please use forum for questions and help requests.
