### ISSUE TITLE
DialogBox issue in IE 11

### ISSUE THREAD

**Issue by kcsahoo** [primefaces/primeng#7093]
DialogBox issue in IE 11

When the dialog box opens, the modal is false.
As a result, nothing can be done.

**Comment by JacobSiegle** [comment]
You're referring to https://www.primefaces.org/primeng/#/dialog ? It works fine for me in IE 11, can you reproduce in a stack-blitz?

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
