### ISSUE TITLE
Error: Unexpected value 'undefined' imported by the module ‘MultiSelectModule’  

### ISSUE THREAD

**Issue by GodKillerDandan** [primefaces/primeng#7095]
When I unload node_modules folder,  and run "npm install --save", this error occur. If anyone know how to hack ，please contact me.  Thank you very much!

* **Angular version:** 5.X

 "@angular/cli": "~6.2.4",
* **PrimeNG version:** 5.X

   "primeng": "^7.0.0-beta.1",

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 all
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all
* **Node (for AoT issues):** `node --version` =   
v 8.9.0

**Comment by yigitfindikli** [comment]
You need install @angular/cdk for virtualscroll property. https://www.primefaces.org/primeng/#/multiselect
`npm install @angular/cdk --save`
Please use forum for questions and help requests.
