### ISSUE TITLE
Menus on mobile devices

### ISSUE THREAD

**Issue by CyleClone** [primefaces/primeng#7098]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
```

**Current behavior**
Most of the menus that require hovering (Menubar, TieredMenu, MegaMenu) do not work on mobile devices. 

**Minimal reproduction of the problem with instructions**
https://www.primefaces.org/ultima-ng/#/menus

Please tell us about your environment:
Android 6 up to Android 9, Built-in Chrome Browser

Angular version: 7.0.0

PrimeNG version: 7.0.2

Browser: Mobile Chrome 71.0.3578.99 | Android X.X Web Browser

**Comment by JacobSiegle** [comment]
Duplicates - #6441, #4477, #4041

**Comment by JacobSiegle** [comment]
#7085 sounds like it could fix it also.

**Comment by cagataycivici** [comment]
Menus are mostly for desktop e.g. menubar, the menus of premium templates have proper support for responsive design. Still we have plans to add enhancements in the near future to align them with the React versions. There are already issues about this.
