### ISSUE TITLE
jquery dependency

### ISSUE THREAD

**Issue by JohannesLaier** [primefaces/primeng#710]
While starting the project the following error was thrown:

> primeng@1.0.0-beta.12-SNAPSHOT start /home/johannes/workspace/saasde/war/dev/tmp/primeng
> npm run tsc && npm run webpack-dev-server

> primeng@1.0.0-beta.12-SNAPSHOT tsc /home/johannes/workspace/saasde/war/dev/tmp/primeng
> tsc

components/calendar/calendar.ts(136,46): error TS2304: Cannot find name 'jQuery'.
components/calendar/calendar.ts(136,90): error TS2304: Cannot find name 'jQuery'.
components/inputmask/inputmask.ts(70,29): error TS2304: Cannot find name 'jQuery'.
components/inputmask/inputmask.ts(75,30): error TS2304: Cannot find name 'jQuery'.
components/inputmask/inputmask.ts(96,13): error TS2304: Cannot find name 'jQuery'.
components/inputmask/inputmask.ts(98,13): error TS2304: Cannot find name 'jQuery'.
components/inputmask/inputmask.ts(118,9): error TS2304: Cannot find name 'jQuery'.
components/schedule/schedule.ts(116,25): error TS2304: Cannot find name 'jQuery'.
components/schedule/schedule.ts(253,9): error TS2304: Cannot find name 'jQuery'.
components/slider/slider.ts(53,9): error TS2304: Cannot find name 'jQuery'.
components/slider/slider.ts(85,13): error TS2304: Cannot find name 'jQuery'.
components/slider/slider.ts(100,17): error TS2304: Cannot find name 'jQuery'.
components/slider/slider.ts(106,9): error TS2304: Cannot find name 'jQuery'.

Found the solution here:

https://github.com/primefaces/primeng/wiki/Building-From-Source

I forgot the typing install command.

Thanks

**Comment by youpage** [comment]
make sure you have the typings installed for jQuery and
in calendar.ts add at line 4:
`declare var jQuery:any;`
