### ISSUE TITLE
Documentation incorrect for MultiSelect

### ISSUE THREAD

**Issue by tidusjar** [primefaces/primeng#7100]
It seems that this commit: https://github.com/primefaces/primeng/commit/993f856

We have changed the event from `onItemClick()` to `onOptionClick()`, this is not reflected on the documentation: https://www.primefaces.org/primeng/#/multiselect

**Comment by cagataycivici** [comment]
I don't understand, onOptionClick is internal, what is to document? Where is wrong in docs?

**Comment by tidusjar** [comment]
Sorry my misunderstanding.
