### ISSUE TITLE
<p-table> inside <p-picklist>

### ISSUE THREAD

**Issue by ruchi-ag** [primefaces/primeng#7102]
I am trying the below . I basically need a p-table in my pick list source and target. The below code does not work . I see no data in the picklist . I see the pic attached. Is this not possible ? 
It would be a bummer if we had to simulate the pick list ourselves inspite of using prime ng heavily in our new product .

`<p-pickList [source]="sourceCars" [target]="targetCars"  showSourceControls="false" showTargetControls="false">
        <p-table [responsive]="true">
                <ng-template pTemplate="header">
                    <tr>
                        <th>Name</th>
                        <th>Type</th>
                    </tr>
                </ng-template>
            <ng-template let-car pTemplate="item">
                    <tr>
                        <td>{{car.label}}</td>
                        <td>{{car.value}}</td>
                    </tr>
                </ng-template>
        </p-table>
    </p-pickList>`

![image](https://user-images.githubusercontent.com/32071533/50923067-a6fb5700-1411-11e9-889e-252d6d51022d.png)

**Comment by gasparbarancelli** [comment]
Within the picklist component you must add a template to manipulate the content. I suggest you read the documentation again.

`<ng-template let-car pTemplate = "item">`

[Documentation](https://www.primefaces.org/primeng/#/picklist)

**Comment by ruchi-ag** [comment]
Thank you for your response. My code has that template added towards the later part. <p-table> does not work even after adding the template . How can we show the "car" data in a p-table within p-pickList ?

**Comment by gasparbarancelli** [comment]
@ruchi-ag 
I just tested here and it works perfectly, below the sources below.

#### Component TS
`sourceValue: any = [];
  targetValue: any = [];

  ngOnInit(): void {
    this.sourceValue = [
      {
        name: 'test-1',
        children: [
          {
            name: 'teste-children-1',
            age: 1
          },
          {
            name: 'teste-children-1',
            age: 2
          },
          {
            name: 'teste-children-1',
            age: 3
          }
        ]
      },
      {
        name: 'test-2',
        children: [
          {
            name: 'teste-children-2',
            age: 4
          },
          {
            name: 'teste-children-2',
            age: 5
          },
          {
            name: 'teste-children-2 ',
            age: 6
          }
        ]
      }
    ];
  }`

#### Component HTML
`<p-pickList [source]="sourceValue"
            [target]="targetValue"
            sourceHeader="Available"
            targetHeader="Selected">
  <ng-template let-value pTemplate="item">
    <p-table [value]="value.children" [responsive]="false">
      <ng-template pTemplate="header">
        <tr>
          <th>Name</th>
          <th>Age</th>
        </tr>
      </ng-template>
      <ng-template pTemplate="body" let-child>
        <tr>
          <td>{{child.name}}</td>
          <td>{{child.age}}</td>
        </tr>
      </ng-template>
    </p-table>
  </ng-template>
</p-pickList>
`

**Comment by ruchi-ag** [comment]
This is a step ahead from what I had and few things to learn the way you have defined your variables. But if you observe the headers are repeating . How can we avoid that ? I tried your code and inserted the image below.

![image](https://user-images.githubusercontent.com/32071533/50982348-9820ad00-14c2-11e9-8afb-979779bb33f5.png)

**Comment by gasparbarancelli** [comment]
From what I realized you do not need to use the table component, you just want to display the data in tabular form, but you can do this using divs.

`<p-pickList [source]="sourceCars" [target]="targetCars" sourceHeader="Available" targetHeader="Selected">
  <ng-template let-item pTemplate="item">
    <div class="columnLabel">
      {{item.label}}
    </div>
    <div class="columnValue">
      {{item.value}}
    </div>
  </ng-template>
</p-pickList>`

`.columnLabel,
.columnValue {
  display: inline-block;
}
.columnLabel {
  width: 70%;
}
.columnValue {
  width: 30%;
}
`

**Comment by ruchi-ag** [comment]
The reason I wanted to use p-table was because I have filters on the pick list data . And p-table has inbuilt filters that I could have leveraged. If there were no filters your suggestion works fine. But it looks like right now there is no way to show this kind of UI using prime ng's pick list. Below is the UI that I need to create .

![image](https://user-images.githubusercontent.com/32071533/50985356-bf2ead00-14c9-11e9-9628-994a5b44fc37.png)

**Comment by gasparbarancelli** [comment]
At this level of customization I believe it is not possible to use the talbe. I would use the filterby's own component picklist to be able to filter the items.

**Comment by ruchi-ag** [comment]
The p-table works fine with filters in the headers. I will implement my own GUI of the pick list using p-tables and filter headers. 
I do feel the primeng picklist should be flexible to show a table inside it . Could be a future enhancement. 

Thanks for sticking through and providing suggestions.

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.
