### ISSUE TITLE
Remove autocomplete inline-style

### ISSUE THREAD

**Issue by ubarevicius** [primefaces/primeng#7104]
**autocomplete panel** is decorated with inline style that goes against our **Content Security Policy style-src** rule that does not allow that. This also does not allow autocomplete panel from being customizable, thus it would make sense to remove it or make it possible to disable the behaviour through configuration of autocomplete in order not to break other people's websites that depend on it.

Example of inline style:
`<div class="ui-autocomplete-panel ui-widget ui-widget-content ui-corner-all ui-shadow ng-trigger ng-trigger-overlayAnimation ng-tns-c3-9 ng-star-inserted" style="max-height: 292px; z-index: 1001; top: 37px; left: 0px; transform: translateY(0px); opacity: 1;">
`

We get the following error in the browser console:

Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'nonce-...' ". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.

Even with refused application of a style autocomplete functions correctly as we styled it in our css, thus I see no reason to have it applied.

It's not easy to reproduce the issue as CSP has to be set up correctly for the environment.

primeng: 7.0.3
Angular: 7.1.4

Build system: Angular CLI

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
