### ISSUE TITLE
Cannot set 'min-height' on dialog

### ISSUE THREAD

**Issue by kmute90** [primefaces/primeng#7109]
Cannot set min-height on dialog, eg: <p-dialog [style]="{'min-height':'500px'}" />

The min-height stays at 150px, however I can set the max-height without any issue.

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.

**Comment by kmute90** [comment]
It wasn't a question :D

https://www.primefaces.org/primeng/#/dialog
The documentation says here - "minHeight (deprecated, use style property)" - however its not working so I assume it's a bug

**Comment by yigitfindikli** [comment]
You can use content style like this.

https://stackblitz.com/edit/github-2s4vgd

**Comment by codehunter13** [comment]
why is this closed???? height is NOT working as documented
```
<p-dialog header="Title" [(visible)]="isVisible" [resizable]="true" [style]="{width: '300px', height: '800px'}">
  Content
</p-dialog>
```
does not works

**Comment by JamesRArroyo** [comment]
As @yigitfindikli posted you can use content style like below. Posting so if someone else stumbles across the same problem they don't have to wait ages for the stackblitz to open.

`<p-dialog 
  header="Godfather I"
  [(visible)]="display"
  [modal]="true"
  [responsive]="true"
  [style]="{width: '250px', minWidth: '200px'}"
  [contentStyle]="{minHeight: '450px'}" 
>`

**Comment by Xample** [comment]
You can also use:
            style: {
                minWidth: '40rem',
                minHeight: '35rem',
            },
            contentStyle: {
                // force the content to take the available size
                display: 'grid',
            },
