### ISSUE TITLE
p-calendar month navigator and year navigator doesn't work

### ISSUE THREAD

**Issue by CamilleLochard** [primefaces/primeng#7111]
I'm submitting a ...

```
 [x] bug report => Search github for a similar issue or PR before submitting
 [ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
 [ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

We are using French as language in our application.
The dropdown from months navigator and year navigator are closing imediately after opening. So we are not able to select any month or year
Hovewer, sometimes after double click, the selector stays open but any selection does not change the months or year.
Plus, it seems to work fine when default language date (English) is used.

```
<p-calendar id="" dateFormat="dd/mm/yy" showTime="true" hourFormat="24"
          monthNavigator="true" yearNavigator="true" yearRange="2000:2099"
          [locale]="fr" appendTo="body" readonlyInput="true" [(ngModel)]="..." ></p-calendar>
```
configuration in angular.json:
"node_modules/moment/min/moment-with-locales.min.js"

Configuration in app.modules :
```
import {registerLocaleData} from '@angular/common';
import localeFr from '@angular/common/locales/fr';
        {provide: LOCALE_ID, useValue: 'fr'},
        {provide: LocationStrategy, useClass: HashLocationStrategy, useValue: "fr-FR"},
```

Configuration in service.ts :
```
get fr() {
    return {
         firstDayOfWeek: 1,
         dayNames: ["Dimanche", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi"],
         dayNamesShort: ["Dim", "Lun", "Mar", "Mer", "Jeu", "Ven", "Sam"],
         dayNamesMin: ["Di", "Lu", "Ma", "Me", "Je", "Ve", "Sa"],
         monthNames: ["Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"],
         monthNamesShort: ["Jan", "Fev", "Mar", "Avr", "Mai", "Jun", "Jul", "Aou", "Sep", "Oct", "Nov", "Dec"],
         today: 'Aujourdhui',
         clear: 'Reset'
        };
    }
```

**Expected behavior**
Selection of month or year by month Navigator and year Navigator.

* **Angular version:** 7.0

* **PrimeNG version:** 7.0.3

* **Browser:** [ Chrome | Firefox ]
 
* **Language:** [TypeScript 3.1.6 | ES6 ]

**Comment by Elanor-L** [comment]
I've got the same trouble. The component doesn't seem to work on a phone either (tried with the offical website).

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Comment by gmerabishvili** [comment]
> Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

Hello, Can I limit the height of year navigator somehow? Thank you.

**Comment by HITMANMK** [comment]
> 

Try this,

monthNavigator="true" yearNavigator="true" yearRange="2000:2099"
