### ISSUE TITLE
autoLayout not working on non resizeable and non scrollable turbo table p-table

### ISSUE THREAD

**Issue by ruchi-ag** [primefaces/primeng#7112]
I have this simple primeng 7.0 turbo table , p-table. It is non resizeable and non scrollable. Nothing I do seems to be affecting this table's layout. The autoLayout should work as it is first of all as per the documentation. Is this is a bug or I am doing something wrong ? 
`
    <p-table #availableTable [value]="sourceCars" selectionMode="multiple" 
    [(selection)]="selectedItemsSource" [autoLayout]="true">
            <ng-template pTemplate="header">
                <tr>
                    <th>Name</th>
                    <th>Type</th>
                </tr>            
            </ng-template>
            <ng-template pTemplate="body" let-car>
                <tr [pSelectableRow]="car">
                    <td>{{car.label}}</td>
                    <td>{{car.value}}</td>
                </tr>
            </ng-template>
        </p-table>
`

Here also is the image of my table.
![image](https://user-images.githubusercontent.com/32071533/51063514-f2a03300-15c0-11e9-93e0-22d2e394c52e.png)

**Comment by JacobSiegle** [comment]
Please create a stack-blitz recreating the issue.

**Comment by cagataycivici** [comment]
It is documented already;

> <p>For performance reasons, default table-layout is fixed meaning the cell widths do not depend on their content. If you require cells to scale based on their contents
                set <i>autoLayout</i> property to true. Note that Scrollable and/or Resizable tables do not support auto layout due to technical reasons.
            </p>
