### ISSUE TITLE
[consistency] Shouldn't '.ui-chkbox' and 'ui-chkbox-*' classes be renamed 'ui-checkbox' instead?

### ISSUE THREAD

**Issue by AlainD-** [primefaces/primeng#7118]
**I'm submitting a ...**
```
[ ] bug report
[x] feature request
[ ] support request
```

**Current behavior**
All the classes for checkboxes have 2 missing letters: `ec` in their names. Such as:
```scss
.ui-chkbox {...}
.ui-chkbox-label {...}
```

I don't understand teh *economy* of the 2 letters e and c.

**Expected behavior**
For consistency reasons with the rest of the other features, and/or searching reasons, shouldn't they all be properly renamed `ui-checkbox*` instead?
```scss
.ui-checkbox {...}
.ui-checkbox-label {...}
```

**What is the motivation / use case for changing the behavior?**

  - search in files/folder for `checkbox` and get relevant results
  - not be confused anymore by the naming :-)

**Please tell us about your environment:**

* **Angular version:** 7.X

* **PrimeNG version:** 7.0.4

**Comment by AlainD-** [comment]
One note though: I consider it as minor issue, not a bug really, as everything is currently working as it is. Once you know it, then OK, you'll find what you need.

Just maybe a *nice to have*, but with a high risk of *breaking changes* with all the the themes out there.

**Comment by cagataycivici** [comment]
We can't change them now, it will break many apps and our themes as well.
