### ISSUE TITLE
p-datatable - Any way to select a row programatically.

### ISSUE THREAD

**Issue by garethlewis** [primefaces/primeng#712]
I have a situation where on Google Maps, I select an overlay, which could be a polygon or circle.  When selected, is brings up a s floating div containing the list of objects that are on the map, but I can't see which one is selected.  Is there a way to pass the selected row so the table high lights it?

**Comment by garethlewis** [comment]
Blond moment, not a problem really.

**Comment by dereklin** [comment]
@garethlewis Have you found out how to select a row programmatically?

**Comment by garethlewis** [comment]
If you have a reference to the underlying model that represents the data that the table shows, you can set a reference to the selected item to one of these items and the table will update itself.
