### ISSUE TITLE
PickList filterBy only uses first entry in comma separated entries.

### ISSUE THREAD

**Issue by bogacg** [primefaces/primeng#7121]
```
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
PickList with multiple property names in **filterBy** (separated by comma) only takes account first one.

**Expected behavior**
Each entry in **filterBy** to be used for filtering.

* **Angular version:** 7.2.0

* **PrimeNG version:** 7.0.4

**Comment by vipatel03** [comment]
✅ Confirmed:
PickList filterBy only uses first entry in comma separated entries:

Minimal-Stackblitz: https://angular-primeng-hzh4vj.stackblitz.io

**Comment by eduardo704** [comment]
Remove the spaces between the fields

**Comment by cagataycivici** [comment]
Should be a comma separated list.
