### ISSUE TITLE
Keyboard not opening while using mulitselect on mobile devices.

### ISSUE THREAD

**Issue by thisisyash** [primefaces/primeng#7125]
I have been developing primeng application in which i was using multiselect option, it works fine on desktoop, but the multiselect with search bar is not working fine when viewed on mobile phone, It is because when the searchbar is associated with dropdown the keyboard of mobile comes and goes away, which inturn unable too choose an option form the selec.

**Comment by Pacek99** [comment]
Hello, I have the same problem in my project and my multiselect looks like this "<p-multiSelect id="showCols" [maxSelectedLabels]="200" [options]="columnModel.options" optionLabel="header"
                                    [(ngModel)]="columnModel.selected" [displaySelectedLabel]="true" [virtualScroll]="true" itemSize="30" (onChange)="resortColumns()"></p-multiSelect>"   but still when I am on mobile phone and click on multiselect it flashes open and then when keyboard comes and go away, multiselect closes,   just as described by @thisisyash . So even with virtualScroll set to true it is not working.

**Comment by rafa-as** [comment]
@cagataycivici you want a PR?

**Comment by BlackfootPL** [comment]
I've added a reason and temporary workaround in #7260 if you want...

**Comment by cagataycivici** [comment]
7030
