### ISSUE TITLE
Bad drag experience and performance when using large nodes tree - drag between nodes

### ISSUE THREAD

**Issue by mojo2405** [primefaces/primeng#7127]
```
[ X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://angular-yhs24k.stackblitz.io

**Current behavior**
It is really hard and has really bad user experience when trying to drag and drop node between 2 other nodes , this becomes even worst when using a tree with large number of nodes.

**Expected behavior**
User should be easily able to drag and drop nodes between 2 other nodes. one suggestion I had is to allow user to drop a node over other node which will drop the node in between . I had a pull request on this feature and you declined it. please try to fix this issue.

**Minimal reproduction of the problem with instructions**
create tree with large number of nodes that is draggable.
try to drag node in between 2 other nodes.

**What is the motivation / use case for changing the behavior?**
for now, this is really bad experience, sometimes there is a lag and the performance gets bad.

**Please tell us about your environment:**
using plunkr

* **Angular version:** 7

* **PrimeNG version:** 7.0.4

* **Browser:** Chrome 

 
* **Language:** all

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
