### ISSUE TITLE
Toast - missing styles in default and other themes

### ISSUE THREAD

**Issue by sgentile** [primefaces/primeng#7128]
Your sample showcase has these themes:

https://www.primefaces.org/primeng/assets/components/themes/nova-light/theme.css

ui-toast-message-success

ie.
body .ui-toast .ui-toast-message.ui-toast-message-success {
  background-color: #b7d8b7;
  border: 0 none;
  color: #212121;
}

But inside the default _theme these are missing, I think these styles should exist in the default and not be dependent on a certain particular theme.  ie. the bootstrap theme doesn't have these styles either.

**Comment by gasparbarancelli** [comment]
@sgentile some time ago I added the style in the bootstrap thema css, but it was disapproved because that thema was discontinued.

**Comment by cagataycivici** [comment]
Bootstrap theme is discontinued in favor of Avalon and Mirage themes.
