### ISSUE TITLE
Keyboard support for DataTable Selection

### ISSUE THREAD

**Issue by chromey** [primefaces/primeng#713]
Hi there,

are there any plans to support keyboard-based navigation in datatables? It looks as if this is supported in PrimeFaces, but not in PrimeNg.

**Comment by httpdigest** [comment]
I second this!
Navigation with keyboard in a data table (and also tree table) would be very useful.

**Comment by Ketec** [comment]
Is there any update on this feature? Planned in the near future or rather low priority?

**Comment by fritteli** [comment]
We had implemented a custom solution that worked with PrineNG 4.0.0, but after the upgrade to version 4.1.1 it stopped working. It seems like the new version doesn't sort the underlying array of values, whereas version 4.0.0 did just that. Can anybody confirm this?

**Comment by cagataycivici** [comment]
Planned for 4.2.

**Comment by filip12345678910** [comment]
Will it work with virtual scroll? When I scroll to some other "page", I want to press arrow down and get the next row after the selected one. Maybe it would be nice if the page with the selected one stayed loaded even if I scroll to other page.

**Comment by aaaaeinai** [comment]
It would be also nice if the Key navigation is an attribute directive.

**Comment by thenninger** [comment]
I am new to Angular, and I am considering using PrimeNG, and this is the make-or-break factor for us. It is not just an issue here; it is the most lacking feature of any Angular component package. There is a major lack of keyboard support for sorting and filtering, however many data table components do support some kind of keyboard row selection support.

**Comment by alannsiqueira** [comment]
waiting for this feature

**Comment by sudheerj** [comment]
It is good to change the subject to  generalized term "keyboard navigation support to DataTable component" or create a separate issue for other features such as sorting, filtering and so on.

**Comment by AurelSan** [comment]
waiting for this feature as well, would offer a large added value to dataTable component in terms of ergonomy

**Comment by alannsiqueira** [comment]
is there a preview for this feature?

**Comment by thenninger** [comment]
Has this been added to a newer milestone yet?

**Comment by kalmaredua** [comment]
I am also really interested if it is already added to a milestone. Thx!

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.

**Comment by kevole** [comment]
Is version 5.2.7 table supporting the keyboard row navigation?
