### ISSUE TITLE
Accept all messages feature for Toast

### ISSUE THREAD

**Issue by bruceauyeung** [primefaces/primeng#7131]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
for example, i have a p-toast without key set
`
<p-toast></p-toast>
`
i add a message like this:
`
this.messageService.add({
key:'key1',
severity:'info',
summary:'summary1',
detail:'detail1'
})
`
because message have a key, so p-toast doesn't accept this message.

**Expected behavior**
p-toast has a mechanism to accept all messages/messages with specified keys. for example:
`
<p-toast keys="all"></p-toast>
`
or
`
<p-toast keys="a,b,c"></p-toast>
`

**What is the motivation / use case for changing the behavior?**

i'd like place one and only one <p-toast> in app.component.html, and send messages in all other components

* **PrimeNG version:** 7.0.0

 
* **Language:** TypeScript

**Comment by madcapper2** [comment]
If you want all toasts to go to the same `<p-toast></p-toast>`, then just don't pass a key property on the object to the messageService.  The key property is only needed if you are going to have multiple locations/stylings of the `p-toast` element.

`this.messageService.add({ severity:'info', summary:'summary1', detail:'detail1' })`

**Comment by Arikael** [comment]
unless you want all messages in the same place but be able to clear just certain messages with a specified key.

Which is what I currently need to do.

**Comment by jszybisz** [comment]
Exactly. Currently this solution is missing very basic features.

**Comment by MortenKJ** [comment]
Any update on this? Having multiple p-toast with different keys in the same place and showing messages in both of them causes the messages to overlap, and only one is visible. If they did not overlap, the multiple keys for a single p-toast would not be a big issue.

**Comment by andi-dev** [comment]
I am facing the exact same limitations: I want to programmatically clear an individual toast, which I can only do when giving each message a unique key. Or is there any other suggestions how I could manually close a specific toast-item?

My use-case is that I have a button inside the toasts "message"-template. When this button is pressed, I want the toast to close.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
