### ISSUE TITLE
fileupload send the same name more than once in a multipart/form-data

### ISSUE THREAD

**Issue by Colin-b** [primefaces/primeng#7132]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When sending more than one file at once, the same name is used for each entry and multipart/mixed format is not used while it should.

**Expected behavior**
According to the related RFC (https://www.ietf.org/rfc/rfc2388.txt) it should not be the case.

> Each field has a name. Within a given form, the names are unique.
> If the value of a form field is a set of files rather than a single
> file, that value can be transferred together using the
> "multipart/mixed" format.

**Minimal reproduction of the problem with instructions**
Use the standard multiple file-upload from documentation:
https://www.primefaces.org/primeng/#/fileupload

**What is the motivation / use case for changing the behavior?**
It is not RFC compliant. Two solutions here:
 - Use a different name for each entry
 - Use a multipart/mixed entry

* **Angular version:** 7.0.2

* **PrimeNG version:** 7.0.0

* **Browser:** [Chrome | Vivaldi]
 
* **Language:** [TypeScript 3.1.6]

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
