### ISSUE TITLE
popup menu doesn't reposition itself on show()

### ISSUE THREAD

**Issue by digeomel** [primefaces/primeng#7133]
**I'm submitting a ...** 

[x] bug report 

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/github-7zf3ra

**Current behavior**
If you have a popup menu that can be triggered by clicking on one of multiple elements in the page, the menu position is not updated unless you toggle/hide the previous menu first (not programmatically, only by clicking somewhere outside the menu).

**Expected behavior**
I expect that whenever I call the show() method with an event, the menu position is updated to match the current event target.

* **Angular version:** 7.X

* **PrimeNG version:** 7.X

* **Browser:** [all]
 
* **Language:** [TypeScript]

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
