### ISSUE TITLE
How to handle custom button click event for p-fullCalendar?

### ISSUE THREAD

**Issue by aschip** [primefaces/primeng#7137]
I am using the `p-fullCalendar` control to display appointments.

I want to add a custom button in the header to add a new appointment.

I have done that by specifying it in the options [as per full calendar docs][1]:

    
```
export class AppointmentsComponent implements OnInit {

  events: any[];
  options: any;
  displayAddAppointment: boolean;

  constructor() { }

  ngOnInit() {

    this.options = {
      header: {
        left: 'prev,next today',
        center: 'title',
        right: 'addAppointmentButton, month,agendaWeek,agendaDay'
      },
      customButtons: {
        addAppointmentButton:{
          text:"New appointment",
          click: r=> {
            //this works but displayAddAppointment within the component is inaccessible.
            //I would like to display a modal dialog to add a new appointment from this.
          }
        }
      }
    };
```

the html being :

```
<div>
 <p-fullCalendar [events]="events" [options]="options"></p-fullCalendar>

 <p-dialog header="Schedule new appointment" 
         [(visible)]="displayAddAppointment" 
         modal="modal">
 </p-dialog>
<div>
```

The button is displayed fine and the click event gets fired too.

But how do I handle the click event of this button so that I can display the modal dialog?

`this` within the click event handler refers to the button:

![image](https://user-images.githubusercontent.com/13371053/51287721-cb80b000-1a5d-11e9-9559-3c0b3249dc45.png)

  [1]: https://fullcalendar.io/docs/v4/customButtons

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.
