### ISSUE TITLE
Trigger LazyLoadEvent before reaching last row.

### ISSUE THREAD

**Issue by ManihtraA** [primefaces/primeng#7138]
Hi,
Is any  way to trigger lazy load event in on scroll before reaching the last record. because I set the row size is 30 means when I scroll down when the 30th record reached after that only event is triggered and fetch remaining records. it tack some times. i need smooth scrolling. e.g if I set row size is 30 means if scroll after 15th record  on that time i want to trigger lazy load event fetch the 30 to 60th record. is this possible in p-table?

**Comment by cagataycivici** [comment]
Please use forum for support requests and questions.
