### ISSUE TITLE
Add p-toast 'life' property 

### ISSUE THREAD

**Issue by thornidlo** [primefaces/primeng#7139]
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
In p-growl there was a property life. In p-toast is this property for every message. I undertand someone would have lifetime differently for different messages, but what about global setttings? I need that globally. Its annoying to specify separatly the same or same kind of wrapper around messages, expecially when you use messageservice in many components.

**Comment by yigitfindikli** [comment]
Message supports life property. You can use like 
html;
`

    <p-toast [style]="{marginTop: '80px'}"></p-toast>

    <button type="button" pButton (click)="showSuccess()" label="Success" class="ui-button-success"></button>

`
component;

`
this.messageService.add({severity:'success', summary: 'Success Message', detail:'Order submitted',life:5000});
`
