### ISSUE TITLE
RouterLinkActiveOptions doesn't work with free themes

### ISSUE THREAD

**Issue by morula** [primefaces/primeng#7142]
```
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Example with obsolete theme 'omega':
https://stackblitz.com/edit/angular-routerlinkomega

Example with obsolete theme 'nova-light':
https://stackblitz.com/edit/angular-routerlinknova

**Current behavior**
The RouterLinkActiveOptions doesn't work with the new nova theme (and also the other free themes). The menus aren't selected.

**Expected behavior**

* **Angular version:** 7.X

* **Browser:**
Tested browsers:
- Chrome 71.0.3578.98 
- Firefox 64.0.2

**Comment by mdrafee03** [comment]
same issues..... any solution??
