### ISSUE TITLE
Notify after globalfilter is applied

### ISSUE THREAD

**Issue by harinikprabhu** [primefaces/primeng#7143]
I have a global filter in my `p-table` and it works just fine. 

Please let me know how to initiate a `p-toast` saying that the filter is applied after globalfilter is applied.

```
<p-table #dt [columns]="cols" [value]="cars" [paginator]="true" [rows]="10">
    <ng-template pTemplate="caption">
        <div style="text-align: right">        
            <i class="fa fa-search" style="margin:4px 4px 0 0"></i>
            <input type="text" pInputText size="50" placeholder="Global Filter" 
             (input)="dt.filterGlobal($event.target.value, 'contains')" style="width:auto">
        </div>
    </ng-template>

    <-- Table content-->
</p-table>
```

How can I initiate a `p-toast` right after globalfilter is applied?

Thanks

**Comment by yigitfindikli** [comment]
You can use onFilter event. 
`
<p-table (onFilter)="toastFunction" ...>
.
.
.
</p-table>
`
Please use forum for questions and help requests.
