### ISSUE TITLE
p-table single selection mode setting selection not updating paginator

### ISSUE THREAD

**Issue by sgentile** [primefaces/primeng#7147]
I'm allowing the user to click 'back' and 'next' buttons and selecting the record in the table.  It's selecting the correct item in the table but when you get to the end of a page, the paginator as part of the table is not updating.

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
