### ISSUE TITLE
p-fileUpload component has bug on select file

### ISSUE THREAD

**Issue by wszgrcy** [primefaces/primeng#7149]
Current Waiting Time: ~1weeks.

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

 When I click choose btn(like button but a span ),I click on icon but can't open select file.
so I saw the source ,I find the icon has keep out the input Tag,so I add css `z-index:1`,and click ,
success open dialog
**Expected behavior**

input `file` add css `z-index:1` 
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 

official website

* **PrimeNG version:** 

4.x 7.x (I think all version has this because the latest version has this bug)
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome latest
* **Language:** 
official website

* **Node (for AoT issues):** `node --version` =

**Comment by rafa-as** [comment]
@cagataycivici some news here?
