### ISSUE TITLE
Autocomplete Multiple model become empty string when delete digits

### ISSUE THREAD

**Issue by gr-adtype** [primefaces/primeng#7161]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/angular-f7xluh

**Current behavior**
On a multiple autocomplete, If i add  some value, and start typing a new on and delete all of my digits (so the input value become an empty string), the model/form control become an empty string

**Expected behavior**
The model/form control should be the list of value previously selected.

**Minimal reproduction of the problem with instructions**
Type 'a' and select Afghanistan, type 'b' and select Bahamas, type 'c' and backspace to delete.

**What is the motivation / use case for changing the behavior?**
It's a problem.
I think the error is on src/app/components/autocomplete/autocomplete.ts on line 333

this code
`this.onModelChange(value);`

should become
`if (!this.multiple) this.onModelChange(value);`

otherwise the model of multiple autocomplite become empty string and lose the previous values.

* **Angular version:** 7.0

* **PrimeNG version:** ^7.0.4

* **Browser:** all
 
* **Language:** all

* **Node (for AoT issues):**  1.6.0

**Comment by Tryforce** [comment]
I've been pulling my hair out with this all day. Found a workaround by modifying this line **(line 161)** here in `primeng/components/autocomplete/autocomplete.js`:

`
if (value.length === 0) {
`

becomes: 

`
if (value.length === 0 && !this.multiple) {
`
