### ISSUE TITLE
Dynamic Dialog Programatically

### ISSUE THREAD

**Issue by pknetdeveloper** [primefaces/primeng#7165]
How can we close the dynamic dialog programmatically on route navigation end.
We used to work like this with the material dialog 

`  Material Dialog Version

constructor(private router: Router, private dialogRef: MatDialog) {

        this.router.events.subscribe((event: Event) => {
            if (event instanceof ActivationEnd) {
                    this.dialogRef.closeAll();
            }   
        });
    }
`

But when we try to modify this is not working for primeng. 

`  
constructor(private router: Router, private dialogRef: DynamicDialogRef, private dialogService:  DialogService) { 

        this.router.events.subscribe((event: Event) => {
            if (event instanceof ActivationEnd) {
                console.log(this.dialogService);
                console.log(this.dialogRef);
                if (this.dialogRef) {
                    this.dialogRef.close();
                }
            }          
        });
    }
`

Is there any way we can close already opened dynamic dialog to close from another component?

**Comment by cagataycivici** [comment]
Please use forum for questions and support requests.
