### ISSUE TITLE
Calendar doesn't clean up modality

### ISSUE THREAD

**Issue by jensengar** [primefaces/primeng#7170]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Calendar with ui-touch enabled doesn't always `disableModality`. I noticed this when putting the calendar component in a ngbModal. With the calendar displayed, click outside the modal. You are left with just a dark overlay and can't interact with anything on the page. My suspicion is the ngbModal is destroying the components outright but the calendar doesn't fully clean up after itself.

**Expected behavior**
Calendar should clean up after itself (modality included) when it's destroyed. I suspect all you need to do is call `disableModality` in ngOnDestroy.

I have a workaround in my own code and don't have time to pr a fix right now. Workaround is to simply call the Calendar's `disableModality` fn when cleaning up the ngbModal.

**Comment by jonasvoelcker** [comment]
I've got the same issue and fixed it in my calendar.js according to the behaviour of "onInputKeydown".

I would really much appreciate it to merge in my pull request:

https://github.com/primefaces/primeng/pull/7175
