### ISSUE TITLE
HTML tags inside checkbox label

### ISSUE THREAD

**Issue by grzegorzbernat** [primefaces/primeng#7171]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Currently checkbox accepts only pure text as label. 

**Expected behavior**
Add posibility to render also HTML tags. 

**What is the motivation / use case for changing the behavior?**
Sometimes I want to put link inside checkbox label, for example "I acccept rules" - where "rules" is clickable link to another page.

**Comment by JacobSiegle** [comment]
Doesn't it make more sense in this scenario to not use the label property of the checkbox and just align text with a anchor tag next to the check box?

Additionally right now when you use the label with the checkbox clicking the label toggles the checkbox status and your request would conflict with this feature.

**Comment by cagataycivici** [comment]
Better to use your own element aligned with css next to the checkbox.
