### ISSUE TITLE
p-dialog primeng 7 autolayering fails

### ISSUE THREAD

**Issue by hakim-dc** [primefaces/primeng#7174]
Stackblitz Case (Bug Reports)
https://stackblitz.com/edit/angular-qyp5uw

**Current behavior**
Using the above stackblitz we can see that the second dialog appear behind the first dialog  instead of appearing on top of  it after click and drag, which is probably due to auto layering also when we try to click on it the z-index dosen't change. This was working in the primeng  6.

* **Angular version:** 7.X

* **PrimeNG version:** 7.0.5

* **Browser:** [ Chrome  | Firefox ]

**Comment by jiangyh1024** [comment]
same + 1

**Comment by jiangyh1024** [comment]
![image](https://user-images.githubusercontent.com/34930870/51815688-b9283100-22fd-11e9-94c3-d068c55e001f.png)

dragging top dialog over bottom does not change the z-index

**Comment by alkismavridis** [comment]
Also affected.

**Comment by cagataycivici** [comment]
auto layering is removed in favor of modal dialogs as it was causing more problems than it solves. Modal dialogs solve this problem as well.

**Comment by alkismavridis** [comment]
Ok I see... Pitty, I think this feature was really good.
Our app for example was based on the concept of having multiple dialogs side by side and eventually allow the user to do stuff in both of them..
Modals do not offer to us this option.

**Comment by hakim-dc** [comment]
alkismavridis same + 1.
also our app based on dialogs side by side. pleave give us a solution or an altirnative for that.
if any one wants to disable it, he can just use autoZIndex = false;
