### ISSUE TITLE
virtualscroller and print?

### ISSUE THREAD

**Issue by cyberrranger** [primefaces/primeng#7180]
**I'm submitting a ...**  (check one with "x")
```
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
```

Can i print (with CMD + P) the complete content from a virtualscroller?

https://www.primefaces.org/primeng/#/virtualscroller

**Comment by JacobSiegle** [comment]
I don't think it's possible to print without rending all the elements.

**Comment by cyberrranger** [comment]
@JacobSiegle we find a workaround, in our print.css

cdk-virtual-scroll-viewport {
		contain: none !important;
		overflow: visible !important;
	}
