### ISSUE TITLE
Ultima Theme: Chrome shows blue frame around selected elements

### ISSUE THREAD

**Issue by ThorstenKunz** [primefaces/primeng#7181]
I'm submitting a bug report
It happens on Ultima Theme Demo Site: https://www.primefaces.org/ultima-ng/#/panels
Browser: Chrome 71 on Windows 10

When you click on e.g. a tabview panel it renders a blue frame around it. Please see attached screenshot.
![2019-01-28 20_21_49-primeng - ultima](https://user-images.githubusercontent.com/30314770/51860576-69b42600-233a-11e9-9c8a-945d84baa233.png)
This happens to lots of other selectable components like e.g. sortable p-table headers, table paginator page numbers, accordion panel headers, etc.

**Comment by cuneytcalishkan** [comment]
This is not a bug, it is part of the accessibility system to highlight the selected elements to help screen readers. If you want to remove them, you can provide in CSS 'outline:none'

**Comment by ThorstenKunz** [comment]
Oh, I didn't know that. Thanks for clarification.
