### ISSUE TITLE
Setting styleclass on dropdown control doesn't work

### ISSUE THREAD

**Issue by AlejandroFlorin** [primefaces/primeng#7184]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
The control does not honor the style defined in the class specified via the [styleClass] properties. Specifically, the background color of the dropdown control when an option is selected isn't set to the per the defined class.

**Expected behavior**
The control should honor the style of the class

**Minimal reproduction of the problem with instructions**
Define the following css class accessible to the component containing the dropdown control

 .highlight-yellow {
    background-color: yellow !important;
}

Add dropdown controls to a component and set it as follows:
<p-dropdown [styleClass]="highlight-yellow" [options]="someOptions"></p-dropdown>
<p-dropdown styleClass="highlight-yellow" [options]="someOptions"></p-dropdown>
<p-dropdown panelStyleClass="highlight-yellow" [options]="someOptions"></p-dropdown>
<p-dropdown [panelStyleClass]="highlight-yellow" [options]="someOptions"></p-dropdown>

None of the above work

**What is the motivation / use case for changing the behavior?**
Control should honor the styleClass property

**Please tell us about your environment:**

Windows 10 Pro, Visual Studio 2017

* **Angular version:** 7.2

* **PrimeNG version:** 7.0.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 3.2.2

* **Node (for AoT issues):** `node --version` =

**Comment by plathub** [comment]
This is not a bug. It's a feature of Angular which is called [ViewEncapsulation](https://angular.io/guide/component-styles#view-encapsulation). If you want your parent component's styles to "bleed" into your child component, then you have to set ViewEncapsulation to `none`. An alternative approach would be to define your style class in your global `styles.css` or similar.
