### ISSUE TITLE
p-table horizontal scroll issue in Mac OS

### ISSUE THREAD

**Issue by shubhamghormade19** [primefaces/primeng#7185]
#**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => p-table horizontal scrollbar issue in Mac OS
```
**Current behavior**
In Mac Operating System the horizontal scrollbar comes inside the table itself, thus it hides last row.
In Windows Operating System it works fine. 
Check the bellow screenshots...

**MAC Operating System**
![mac_os_p-table_scroll](https://user-images.githubusercontent.com/30460603/51884862-06b0a680-23af-11e9-8c44-f5b14b9023a3.png)

**Windows Operating System**
![windows_os_p-table_scroll](https://user-images.githubusercontent.com/30460603/51884868-0d3f1e00-23af-11e9-9a50-4d01a982513c.png)

**Expected behavior**
The horizontal scrollbar should come at end of the table, so it will not hide the last row.
The scrollbar should be behave as per the windows OS or it should be virtual.

**Minimal reproduction of the problem with instructions**
You can directly visit to the PrimeNG site in Mac OS & in Windows OS.
https://www.primefaces.org/primeng/#/table/scroll
You will find out the difference in horizontal scrollbar.

**What is the motivation / use case for changing the behavior?**
Scrollbar control should be virtual.

**Please tell us about your environment:**
Operating System :- Mac , Windows 10 pro

* **PrimeNG version:** 7.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by shubhamghormade19** [comment]
Any update in this issue

**Comment by mertsincan** [comment]
It is not related to p-table. Please try it with only html elements. Mac and Windows have different implementations for scrollbar.  On windows, the scrollbar is inserted into the container as an element, but on mac, it does not interfere to the container. Please see this link; http://osxdaily.com/2011/08/03/show-scroll-bars-mac-os-x-lion/

Please try;
Show scroll bars : Always
