### ISSUE TITLE
RowReorder Feature for TreeTable

### ISSUE THREAD

**Issue by steve3d** [primefaces/primeng#7186]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
currently the tree table only support column reorder, but I also need a row reorder function.

**What is the motivation / use case for changing the behavior?**
row reorder in tree table should be different than the p-table, this type of reorder need to limit the row in same hierarchy, or it can be moved up/down to another hierarchy, both behavior should be supported.

For example. I have a company with many sub departments, which might also have a sub departments. so I'm using the tree table to display the relation of each departments, but I also need to set the order of departments, so I need to limit one department can only be reordered in same hierarchy level, it can not be moved up to another department.

But if this is a folder hierarchy, I also need to move one folder up/down a level.

**Comment by lkjx77** [comment]
I also need this feature in my current project.

**Comment by jbjhjm** [comment]
Would be quite useful to easily manage all kinds of hierarchical items!

**Comment by nkm96** [comment]
I also need this in my projects :(

**Comment by pablofloresrojas** [comment]
I also need it! please!

**Comment by dhaneshgosai** [comment]
Any progress or anything the team is planning to add this feature?

**Comment by uebelmar** [comment]
Would be a great feature

**Comment by NexPlex** [comment]
Any suggestion for a work around?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by steve3d** [comment]
@mertsincan are you kidding with us?

what we want is the row reorder feature for treetable, not column reorder, I've just searched the source code of treetable and the documentation, but here is nothing about the row reorder.

the feature is like this https://www.primefaces.org/primeng/table/reorder

please reopen this very old feature request.

**Comment by mertsincan** [comment]
Of course not. We are currently trying to create a roadmap and if the issue has been fixed in the new version, many users may have overlooked it. For this reason, if users are still persistent and following the subject they have created, we will add them to our roadmap and examine them in detail. Most users may have finished their app with PrimeNG and have unfollowed their issues(new feature or bug). As a team, I think it would be more logical to focus directly on the problems of the people in need instead of such issues. As you know PrimeNg Open Source is a project and it has a really big and nice community. That's why you deserve better quality support. We strive for this.

Thanks a lot for the update, I'll reopen this issue.

**Comment by eperrier** [comment]
@mertsincan any updates on timing for this feature request? Presumably it is relatively straightforward as the reoder (drag/drop) code already exists for both the datatable and tree components.

**Comment by nvynn** [comment]
@mertsincan , could you please add supporting `[pReorderableRow]` directive to `p-treeTable`?
just like this
```
<p-treeTable [value]="files">
  <ng-template pTemplate="header">...</ng-template>
  <ng-template pTemplate="body" let-rowNode let-rowData="rowData" let-index="rowIndex">
    <tr [ttRow]="rowNode" [pReorderableRow]="index">
      <td>
        <span class="pi pi-bars" pReorderableRowHandle></span>
      </td>
      <td>
        <p-treeTableToggler [rowNode]="rowNode"></p-treeTableToggler>
        {{ rowData.name }}
      </td>
    </tr>
  </ng-template>
</p-treeTable>
```

**Comment by cetincakiroglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog.

**Comment by 1Map** [comment]
I see this ticket is closed, but still cannot see how to reorder rows in a treetable?

**Comment by uebelmar** [comment]
> I see this ticket is closed, but still cannot see how to reorder rows in a treetable?
> 
> https://v3.primevue.org/treetable/#api.column.props.rowReorder
> 
> I also see that someone created another ticket on the same topic:
> 
> [primefaces/primevue#5660](https://github.com/primefaces/primevue/issues/5660)

primevue != primeng
