### ISSUE TITLE
Issue while performing production build 

### ISSUE THREAD

**Issue by samir-ware** [primefaces/primeng#7189]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Waiting Time: ~8 weeks.

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
When performing ng build --prod below error is getting thrown 

ERROR in node_modules/primeng/components/common/messageservice.d.ts(5,28): error TS1005: ';' expected.
node_modules/primeng/components/common/messageservice.d.ts(5,88): error TS1005: '(' expected.
node_modules/primeng/components/common/messageservice.d.ts(6,73): error TS1005: '(' expected.
node_modules/primeng/components/common/messageservice.d.ts(7,16): error TS1005: ',' expected.
node_modules/primeng/components/common/messageservice.d.ts(7,26): error TS1005: ';' expected.
node_modules/primeng/components/common/messageservice.d.ts(7,32): error TS1109: Expression expected.
node_modules/primeng/components/common/messageservice.d.ts(8,20): error TS1005: ',' expected.
node_modules/primeng/components/common/messageservice.d.ts(8,32): error TS1005: ';' expected.
node_modules/primeng/components/common/messageservice.d.ts(8,38): error TS1109: Expression expected.
node_modules/primeng/components/common/messageservice.d.ts(9,15): error TS1109: Expression expected.
node_modules/primeng/components/common/messageservice.d.ts(9,24): error TS1005: ';' expected.
node_modules/primeng/components/common/messageservice.d.ts(9,30): error TS1109: Expression expected.
node_modules/primeng/components/common/messageservice.d.ts(10,1): error TS1128: Declaration or statement expected.

**Expected behavior**
ng build --prod should run and create build artifacts

**Minimal reproduction of the problem with instructions**
I am using build ^7.0.5 . Issue does not exists with non production build script (ng build) . This occours only with production build. 

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.X
6.0.0

* **PrimeNG version:** 5.X
^7.0.5

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by AlanLopez22** [comment]
I have the same bug

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
