### ISSUE TITLE
Is p-menubar support localization or Globalization for label

### ISSUE THREAD

**Issue by anupmca007** [primefaces/primeng#7191]
**Problem based on :- Is p-menubar support localization or Globalization for label.**

We are facing a problem ,how to apply a localization in <p-menubar> component.
For localization ,we are using the **ngx-translate** .it is working fine with other place but in <p-menubar > we are not able to apply **translate pipe ( like :- {"key" | translate} )**. It is possible to apply translator type concept in particular component or not let me know.

**Comment by cagataycivici** [comment]
Please use forum for questions and support requests.
