### ISSUE TITLE
Turbo Table contains match mode does not work with Multi-Select

### ISSUE THREAD

**Issue by mlangwell** [primefaces/primeng#7192]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Waiting Time: ~8 weeks.

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**

Turbo Table 'contains' match mode does not handle comparing two arrays. If you use a multi-select drop down to filter the table and the column you filter against is an array of data, the filtrating fails in some cases. This is because the contains match mode function takes the two arrays, converts them to string values, and then tests the column's value with indexOf the filter's string value. If coincidentally the two arrays are in the same order the filter succeeds. However, in the event that they are not in the same order the filter fails.

**Expected behavior**

We should be able to filter with the multi-select array value against a table record object's property that is an array.

**Minimal reproduction of the problem with instructions**

Create a table that takes in an array of objects. The object should have a property that is an array. Use the multi-select drop down then onChange of the drop down call the tables filter function: (onChange)="tt.filter($event.value, col.field, 'contains')"

**What is the motivation / use case for changing the behavior?**

The table handles displaying arrays properly in the columns, but does not handle filtering by those arrays against a multi-select.

**Please tell us about your environment:**

Windows 10, VS Code, npm

* **Angular version:** 5.X

7.0.2

* **PrimeNG version:** 5.X

7.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

ALL
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ALL

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
