### ISSUE TITLE
Turbo Table Frozen Columns not working for RTL

### ISSUE THREAD

**Issue by WebStew** [primefaces/primeng#7195]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-turbo-table-frozen-columns
https://github.com/WebStew/primeng-turbo-table-rtl-issue

**Current behavior**
Frozen columns are not visible in right to left reading direction.
Looks as though .ui-table-unfrozen-view is incorrectly positioned from the left when it should be from the right.

**Expected behavior**
Frozen columns should be visible and on the opposite side from LTR reading direction.

**What is the motivation / use case for changing the behavior?**
Turbo table with frozen columns is not functional in RTL reading direction.

**Please tell us about your environment:**
MacOS 10.13.6
Coda 2
NPM 5.6.0

* **Angular version:** 5.X
Issue exists in Angular 7.2

* **PrimeNG version:** 5.X
Issue exists in PrimeNG 7.0.5

* **Browser:** 
All
 
* **Language:**
All

* **Node (for AoT issues):** `node --version` = 9.4.0

**Comment by cagataycivici** [comment]
There is an enhancement ticket already for ScrollableColumns and RTL.

**Comment by sreesilpa13** [comment]
> There is an enhancement ticket already for ScrollableColumns and RTL.

Any update on this as i am still facing some problems with scrolling the header but the rows are scrollable.
