### ISSUE TITLE
Add to FullCalendar nextYear and prevYear button icons

### ISSUE THREAD

**Issue by tuchorc** [primefaces/primeng#7197]
**I'm submitting a ...**
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When setting in fullcalendar options, the attributes prevYear and nextYear, the corresponding buttons shows without any icon.

**Expected behavior**
The previious year icon should be pi-angle-double-left
The next year icon should be pi-angle-double-right

**Minimal reproduction of the problem with instructions**
Starting from https://stackblitz.com/github/primefaces/primeng-issue-template, do the following changes: 
In app.component.ts:
```
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent {

  options: any;

  constructor() {
    this.options = {
            header: {
                left: '',
                center: 'prevYear,prev,next,nextYear',
                right: ''
            }
            // themeSystem: 'jquery-ui',
            // themeButtonIcons: {
            //     prev: 'circle-triangle-w',
            //     next: 'circle-triangle-e',
            //     prevYear: 'seek-prev',
            //     nextYear: 'seek-next'
            // },
    };
  }
}
```
In app.component.html:
```
<p-fullCalendar [options]="options">
</p-fullCalendar>
```

In angular.json:
```
...
"styles": [
               ...
                "node_modules/fullcalendar/dist/fullcalendar.min.css",
                ...
            ],
...
```

**What is the motivation / use case for changing the behavior?**
As you can see, in **primeng/resources/themes/_theme.scss**, you set
```
.fc {
    .fc-toolbar {
        .fc-prev-button {
            .ui-icon-circle-triangle-w {
                margin-top: .3em;
                @include icon_override("\e900");
            }
        }

        .fc-next-button {
            .ui-icon-circle-triangle-e {
                margin-top: .3em;
                @include icon_override("\e901");
            }
        }
    }
}
```

And you should also add:
```
...
    .fc-prevYear-button {
      .ui-icon-seek-prev {
        margin-top: .3em;
        @include icon_override("\e92d");
      }
    }

    .fc-nextYear-button {
      .ui-icon-seek-next {
        margin-top: .3em;
        @include icon_override("\e92e");
      }
    }
...
```

**Please tell us about your environment:**
* **Angular version:** 7.2.2
* **PrimeNG version:** 7.0.5
* **FullCalendar version:** 4.0.0-alpha.4
* **Browser:** all

**Comment by auzair92** [comment]
Thank you for this! I was facing a similar issue and using your hint, I modified the `nova-light\theme.css` file to include the icons for my custom header buttons like this:

```
body .fc .fc-toolbar .fc-button .fc-icon-plus {
  font-family: "PrimeIcons" !important;
  text-indent: 0;
  font-weight: 50;
}
body .fc .fc-toolbar .fc-button .fc-icon-plus:before {
  content: "\e954";
}
```

The unicode in `content` field for a button of your choice can be obtained from `primeicons.svg` file.

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
