### ISSUE TITLE
Checkbox component value returns item by user only and not all checked items

### ISSUE THREAD

**Issue by tjvg91** [primefaces/primeng#7199]
So I have a reactive form. Upon checking certain checkbox item the component returns only the item checked by user instead of all the checked items.

**Comment by JacobSiegle** [comment]
Sounds like an error with your code or I do not understand the issue. If you need further support please try the primeng forums.

![image](https://user-images.githubusercontent.com/5766272/52417993-b2927a00-2ab2-11e9-8857-594534435222.png)

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
