### ISSUE TITLE
Using p:checkbox as a boolean

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#72]
Checkbox requires a model property as an array to bind, there is also a case where a checkbox is used to provide a boolean value.

```xml
<p-checkbox [(checked)]="checked"></p-checkbox>
```

**Comment by ryildiz** [comment]
Hi Çağatay,
p-checkbox does not provide a boolean value with below config:
    "name": "sapphire",
    "version": "10.0.0",
    "license": "PrimeNG Commercial",
