### ISSUE TITLE
[Website Table Showcase] Table edit wrong URL

### ISSUE THREAD

**Issue by Mysame** [primefaces/primeng#7201]
1) Go to https://www.primefaces.org/primeng/#/table
2) Scroll down to section "Editing"
3) Click `Live example`

Result:
ERROR Error: "Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'table/editable'

You get redirected to
https://www.primefaces.org/primeng/#/table/editable

The correct url (used at the top) is
https://www.primefaces.org/primeng/#/table/edit

**Comment by yigitfindikli** [comment]
Thanks for the heads up!
