### ISSUE TITLE
Dropdown autoWidth issue on Ubuntu Chrome & Chromium

### ISSUE THREAD

**Issue by jdevreese** [primefaces/primeng#7204]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-jczj7f

**Current behavior**
![screenshot 2019-02-05 15-07-52](https://user-images.githubusercontent.com/13763578/52279904-e9ee1300-295a-11e9-8c92-244fd2b5ff0d.png)
The dropdown component gets a 30px width. This makes the label unreadable.

**Expected behavior**
Adjust width to fit content.

**Minimal reproduction of the problem with instructions**
- Go to https://www.primefaces.org/primeng/#/dropdown
- Take a look at the first example ("Single")

**What is the motivation / use case for changing the behavior?**
Selected option is not readable because component is too narrow.

**Please tell us about your environment:**
Ubuntu (16.04.5 LTS)

* **Angular version:** 7.1.0

* **PrimeNG version:** 7.0.5

* **Browser:** [ Chrome 72.0.3626.81 (64-bit) | Chromium 71.0.3578.98 (64-bit) ]
 
* **Language:** [ TypeScript 3.1.6 ]

Works on Firefox (65.0 64-bit) in Ubuntu and on Chrome (same version) in Windows 10.

**Comment by jdevreese** [comment]
I've since upgraded to Ubuntu 18.04 LTS and in this version of Ubuntu, I no longer have this problem.
I'll leave the issue open for others.

**Comment by JacobSiegle** [comment]
Auto width was removed in the latest version of primeng.
