### ISSUE TITLE
Table Scrollable - not scrolling headers (horizontal)

### ISSUE THREAD

**Issue by sgentile** [primefaces/primeng#7206]
This can be demonstrated on the example page:

https://www.primefaces.org/primeng/#/table

It only scrolls the 'data' - not the header row when scrolling horizontal (try to scroll the header to move the data, it only scrolls when over the table rows vs. header rows)

One major  impact is when you are scrolling and enter a filter where there is no data, you cannot scroll back to the header column and remove or change the filter

**Comment by sgentile** [comment]
My fix is the following, and not sure why this isn't how it's done in primeng?  

ui-table-scrollable-view  set this to overflow:auto;

remove overflow from ui-table-scrollable-header and ui-table-scrollable-body

**Comment by cagataycivici** [comment]
For horizontal scrolling, you need to have scrollWidth.

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Comment by UbaidurRehman1** [comment]
> My fix is the following, and not sure why this isn't how it's done in primeng?
> 
> ui-table-scrollable-view set this to overflow:auto;
> 
> remove overflow from ui-table-scrollable-header and ui-table-scrollable-body

@sgentile  Thank you very much, this works. 

For  PrimeNG,  just need to add the following sass:

```
:host ::ng-deep .p-datatable-scrollable-view {
    
     overflow: auto;

    .p-datatable-scrollable-header {
        overflow: unset;
    }

    .p-datatable-scrollable-body {
        overflow: unset;
    }
}
```
