### ISSUE TITLE
p-spinner trigger modelChange on input blur: remove or let disable it (bug?)

### ISSUE THREAD

**Issue by santino83** [primefaces/primeng#7208]
```
[x] bug report
[x] feature request
[ ] support request
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/angular-x45eua

**Current behavior**
Spinner component triggers form status change (by onModelChange function) on Input blur

**Expected behavior**
Form Status Changes (aka: value changes) must/should not be triggered on input blur

**Minimal reproduction of the problem with instructions**
Using the provided plunker, looking at the console you could see that "form status changed" is printed on input value changes (expected behavior) and on "input blur" (just click away onto the page), and it's not an expected behavior since the value has not be changed anymore

**What is the motivation / use case for changing the behavior?**
If you are listening to form statusChanges, for example to implement an auto-save behavior, triggering onModelChange (maybe onModelTouched too?) on input blur will lead you to have a duplicate/unusefull status change event and so a duplicate "save" action.  As you could see from the plunker, when plus/minus buttons are clicked, value changes and as expected form statusChange is trigger: adding a debounceTime to the subscription, we can easely implement the auto-save behavior, but if user click away from the input (maybe clicked something different from the current form for example, a navigation link, the page itself, whatever), onInputBlur method will trigger another statusChange and so another auto-save action, this time, however, unusefull/unwanted. That's why, onInputBlur should be removed or let be deactivated by an input configuration to disable the above mentioned behavior. 

**Please tell us about your environment:**
linux, node, npm, Webstorm, ng-serve

* **Angular version:** 7.X

* **PrimeNG version:** 7.X

* **Browser:** Chrome
 
* **Language:** Typescript

* **Node (for AoT issues):** `node --version` =   v11.5.0

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
