### ISSUE TITLE
Clicks on overlay panel from overlayPanel component when appendTo is set to 'body' are closing the overlay

### ISSUE THREAD

**Issue by miguelleite** [primefaces/primeng#7209]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://github-yrndzi.stackblitz.io/

**Current behavior**
If `appendTo` is set to `'body'`, overlay panel with `dismissable` set to `true` closes when the overlay panel container gets clicked. If `appendTo` is not set, clicking on the overlay panel does not close it.

**Expected behavior**
Either by setting  `appendTo` to `'body'` or leaving it as null, overlay panel with `dismissable` set to `true` does not close when the overlay panel container gets clicked.

**Minimal reproduction of the problem with instructions**
1. Open the plunkr case;
2. Click the button to show the overlay pannel;
3. Click inside the overlay panel that shows up;
4. It closes.
5. Remove appendTo property from the component view;
6. Click the button to show the overlay pannel;
7. Click inside the overlay panel that shows up;
8. It does not close.

**What is the motivation / use case for changing the behavior?**
Having consistency across the component.

* **Angular version:** 7.2.2

* **PrimeNG version:** 7.0.5

* **Browser:** all
 
* **Language:** TypeScript 3.2.4

* **Node (for AoT issues):** v10.15.1

**Comment by yigitfindikli** [comment]
fixed in https://github.com/primefaces/primeng/commit/14431f9e188dfbefd3c64625a703626755a9979b
