### ISSUE TITLE
Calendar value without ngModel

### ISSUE THREAD

**Issue by danillo10** [primefaces/primeng#7212]
How i set value manually(without ngModel) Ex: `<p-calendar value="2/6/2019"></p-calendar>`

**Comment by JacobSiegle** [comment]
This a generic angular question not an issue with primeng. Please ask on the primeng forums in the future.

<p-calendar [ngModel]="'1/1/2018'"></p-calendar>

**Comment by cagataycivici** [comment]
Please use forum for support requests and questions.
