### ISSUE TITLE
Add comma as separator for chips component

### ISSUE THREAD

**Issue by Sheraff** [primefaces/primeng#7213]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
*Chips* component only allows for a few keys to trigger the addition of a *chip*.

**Expected behavior**
Ideally we'd setup a new `@Input()` to allow user to set their own list of keys to trigger an addition of chips (or even add their own parsing on the text instead of key triggers). But the most requested one seems to be the *comma* key.  

**What is the motivation / use case for changing the behavior?**
Many apps using a similar component allow for a CSV type of input where separating your values by commas will be recognized as different chips.

**Comment by Sheraff** [comment]
For example, the comma was requested here: https://github.com/primefaces/primeng/issues/5333 (though in combination with a `(paste)` event).

Allowing the developer to define their own parsing was requested here: https://github.com/primefaces/primeng/issues/3419

**Comment by cagataycivici** [comment]
If more users demand it via this ticket, we'll consider, thank you.

**Comment by djdev** [comment]
I think having the option to paste comma separated values into the chip input and the input handling the transformation of the input based on separators will be an excellent piece for UX. Where can I upvote for it?

**Comment by tigrenok00** [comment]
We also wish there was support for pasting a list of values with custom delimiter (slash or comma)

**Comment by sweatC** [comment]
@cagataycivici I think there are a lot people who need this feature :+1:

**Comment by cagataycivici** [comment]
Set to 9.0.2

**Comment by cagataycivici** [comment]
#5333
