### ISSUE TITLE
Not able to style the p-accordionTab header in ngPrime v5.2.4. The default styling is producing underlined text with pointer cursor.

### ISSUE THREAD

**Issue by GitIamAbbas** [primefaces/primeng#7215]
Hi,

Not able to style the p-accordionTab header in ngPrime v5.2.4. The default styling is producing underlined text with pointer cursor. But we need to bold the text present in p-accordionTab header and also the cursor type should be arrow.

I have tried adding the below.

.ui-accordion .ui-accordion-header a {
        font-weight: bold !important;
        text-decoration: none !important;
        cursor: default !important;
     }

but not working. Please suggest.

P.S: We can't change the version. Want to fix the issue with the same version.

**Comment by JacobSiegle** [comment]
This is a question not an issue. Try the primeng forums instead.

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.
