### ISSUE TITLE
Bugs with Horizontal Tree Component #2557

### ISSUE THREAD

**Issue by RyuBcn** [primefaces/primeng#7216]
This issue #2557 it's closed but it's still not working.

1 year happened, there is a way to fix it ? thank you

You can see the same tree in horizontal and vertical layout in this simple stackblitz example:

https://stackblitz.com/edit/github-prccxt

You can see that in horizontal layout only first node (and his childs) is displayed and you can't drag&drop anything. No errors in console.

In vertical layout you can arrange the items with drag&drop and all nodes are shown

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Comment by axell9641** [comment]
> Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

The issue remains in July 2020, but as workaround you could add this to your styles.scss file :

`.ui-treenode-connector-line { margin: 0px -1px 0px 0px!important; padding: 0.1px!important; }`
