### ISSUE TITLE
 Prevent duplicates and Prevent open duplicates for Toast

### ISSUE THREAD

**Issue by distributev** [primefaces/primeng#7219]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

This could add value Prevent duplicates and Prevent open duplicates

like here https://foxandxss.github.io/angular-toastr/

**Comment by cagataycivici** [comment]
We'll consider if there is more demand, thank you.

**Comment by ankuradhey** [comment]
This is interesting feature and user can have an option to enable duplicates or disable.

**Comment by JacobSiegle** [comment]
Nice QOL feature I think, it might be nice if when a duplicate was found it reset the life on the existing message and gave some sort of signal you hit it again like highlight.

**Comment by ManzerHa-Kore** [comment]
How to prevent duplicates toast message in primeng?

**Comment by JacobSiegle** [comment]
You can pull the PR  https://github.com/primefaces/primeng/pull/7243 and include it in your project manually, otherwise there's currently no built in way.

**Comment by cagataycivici** [comment]
Planned for 9.0.2
