### ISSUE TITLE
showOtherMonths styling does not work

### ISSUE THREAD

**Issue by annesophien** [primefaces/primeng#7222]
Current Waiting Time: ~8 weeks.

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
Per the PrimeNG documentation, showOtherMonths should by default be set to true, then when we select a day at the beginning or end of the month, we should be able to see the selected date highlighted in the next month. However in the documentation, when we select 2/27/2019 and navigate to March, we don't see that 2/27 is selected. 

When I manually set showOtherMonths to true, it still does not show the previous month's selected day as selected in the next month.

We can see in the calendar.ts component that it expects css classes _ui-datepicker-other-month_, _ui-datepicker-current-day_, or _ui-datepicker-today_, but if you check calendar.css, there are no such classes.

**Expected behavior**
We should be able to see the previous date selected in the next/previous month like in PrimeNG v5.

**Minimal reproduction of the problem with instructions**
PrimeNG v5 calendar documentation **(Correct Behavior)**:
https://www.primefaces.org/primeng-5.2.7/#/calendar 
![image](https://user-images.githubusercontent.com/25231120/52507623-e9e25300-2ba6-11e9-9444-cf89c559b2c4.png)

PrimeNG v7 calendar documentation **(Wrong Behavior)**: https://www.primefaces.org/primeng/#/calendar 
![image](https://user-images.githubusercontent.com/25231120/52507120-7ab82f00-2ba5-11e9-9353-30a967f6ac99.png)

**What is the motivation / use case for changing the behavior?**
p-calendar in v6 and v7 should work like in v5.

* **Angular version:** 6.0

* **PrimeNG version:** 6.0 and 7.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome, IE
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

**Comment by ranjitkumarsingh** [comment]
+1
