### ISSUE TITLE
Primeng 7.0 turbo table row expansion not working with lazy load group data

### ISSUE THREAD

**Issue by vinodkolla** [primefaces/primeng#7225]
I am trying to create a shared table component using primeNg turbo tables. In which, I conditionally want to render the row expansions only when the required field exists. Here is the link for stackblitz with sample code: 

https://stackblitz.com/edit/angular-vqapwh.

I am not seeing the row expansion when I added conditional pTemplate. But when I remove the conditions (app.component.html has the instructions on the top), the row expansions are working fine. I couldn't understand why groups is always falsy in this case. Is the turbo table not re-rendering when the data changed?
* **Angular version:** 7.2.1

* **PrimeNG version:** 7.0.4

* **Language:** TypeScript

* **Node (for AoT issues):** `node --version` = 11.0.*

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
