### ISSUE TITLE
Table sorting with undefined values is not working as expected

### ISSUE THREAD

**Issue by dkiermeier** [primefaces/primeng#7227]
**I'm submitting a ...**
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
When the data source of the table contains some undefined values, then the sorting does not work as expected. The undefined values are sorted in between the other values. The sort order is also not correct.

**Expected behavior**
The undefined values should be placed on top (descending order) or at the bottom (ascending order) of the list.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/angular-kakovv?file=src%2Fapp%2Fapp.component.html
Just sort for the year 

**Please tell us about your environment:**
Win 10, VSCode

* **Angular version:** 
7.2.4

* **PrimeNG version:** 
7.0.5

* **Browser:** 
all
 
* **Language:**
Typescript

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
