### ISSUE TITLE
@component directives will be deprecated

### ISSUE THREAD

**Issue by zigzag95** [primefaces/primeng#723]
Are you going to use @ngModules ?

**Comment by amshim** [comment]
Is there somewhere I can read about these future changes?

**Comment by zigzag95** [comment]
https://docs.google.com/document/d/1isijHlib4fnukj-UxX5X1eWdUar6UkiGKPDFlOuNy1U/pub

**Comment by JakeSummers** [comment]
I think that this was addressed in PrimeNG 1.0.0-beta.13
