### ISSUE TITLE
Filtering for TreeTable

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primeng#7230]

**Comment by eltigree** [comment]
Thnx a lot!! Great work!

**Comment by raycola** [comment]
wow thanks

**Comment by begogna** [comment]
Hello,
is there an example of use for the filter in the TreeTable please ? Thanks a lot in advance, Begoña

**Comment by mertsincan** [comment]
I added sample pages for the TreeTable-Filter and Tree-Filter demos. We'll update live primeng page asap. Also, please see; https://github.com/primefaces/primeng/commit/3e9ed4e51cd3832c60593bc6a319e053e607849f
It is similar to p-table filter; https://www.primefaces.org/primeng/#/table/filter

**Comment by eltigree** [comment]
when is new release avaiable with this great change?

**Comment by syamanashi** [comment]
This is a GREAT feature.  Great work.  Thanks!  Any idea on when it will be released?

**Comment by namnhcntt** [comment]
Please add new feature that can be selected item on filter. Thanks

**Comment by jebashekh** [comment]
if i select parent then i should able to see only parent that's correct ,
we tried few approches as strict and lenient but we need viceversa. 

if we select child node then we should not able to see parent node after filtering ,
can we have some solution for this.

Thanks in advance
