### ISSUE TITLE
Using (keyup)/(keydown) event inside datatable column

### ISSUE THREAD

**Issue by amshim** [primefaces/primeng#724]
I am trying to initiate a function when the user starts typing inside a datatable column. I am able to successfully use (keyup) inside <input>, but inside <p-column> it doesn't work. Is there a workaround to this issue?

**Comment by igogu** [comment]
Do you find how to do it? I have the same problem

**Comment by amshim** [comment]
Nope, never found a solution to this. I don't ever think this functionality was added.

**Comment by cagataycivici** [comment]
A template can help here where you have full control over cell content including events.
