### ISSUE TITLE
Multiselect options not showing

### ISSUE THREAD

**Issue by tjvg91** [primefaces/primeng#7247]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Waiting Time: ~8 weeks.

**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
<Can't demonstrate in stackblitz since I can't recreate issue there>

**Current behavior**
Multi-select won't open options when I click on it. I'm using version 7.0.5.

**Expected behavior**
Options should show upon clicking. 

**What is the motivation / use case for changing the behavior?**
Multiselect is a form control within an angular form group

**Please tell us about your environment:**
I'm using VSCode for IDE.

* **Angular version:** 5.X
7.2.2

* **PrimeNG version:** 5.X
7.0.5

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 71.0.3578.98 | IE 11
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 3.2.4 | ES6+

* **Node (for AoT issues):** `node --version` =   6.4.1

**Comment by tjvg91** [comment]
I also tried downgrading to 6.1.0, but multiselect closes immediately upon clicking of option, which shouldn't be.

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
