### ISSUE TITLE
Change the CSS of the tree ie., color when the tree is partially changed.

### ISSUE THREAD

**Issue by ramyalatha-redpinesignals** [primefaces/primeng#7257]
When the tree is partially changed  then how can change the font color of the parent. When we select one node which is having two children then the checkbox will show with minus  if two nodes are selected then  checkbox will be checked . Like that I want to change the label if one node is selected then label should be red color then complete all the nodes is selected then label should be in green color.

**Comment by cagataycivici** [comment]
Please use forum for questions and help requests.
