### ISSUE TITLE
How to implement a component with DynamicDialogRef and without DynamicDialogRef

### ISSUE THREAD

**Issue by procidis** [primefaces/primeng#7264]
Hello everyone.

I'm trying to implement a component with dynamic dialog and there is a need to use a direct usage. With the DynamicDialog example, there is a constructor of the car demo list component.
`constructor(private carService: CarService, public ref: DynamicDialogRef, public config: DynamicDialogConfig) { }`

When I use directly `<carlist></carlist>,`  I have an error like this:

> ERROR Error: StaticInjectorError(AppModule)[CarslistdemoComponent -> DynamicDialogRef]: 
>  StaticInjectorError(Platform: core)[CarslistdemoComponent -> DynamicDialogRef]: 
>    NullInjectorError: No provider for DynamicDialogRef!
>    at NullInjector.push.../node_modules/@angular/core/fesm5/core.js.NullInjector.get 

Is there anyone can solve this problem or can you give advice to implement a different way?

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.
