### ISSUE TITLE
Cannot combine [min]="1" spinner value with [required]="false"

### ISSUE THREAD

**Issue by rubmz** [primefaces/primeng#7266]
Using the latest and greatest from both Angular (7) and PrimeNG 6.1.7 I want a <p-spinner> to allow me select only positive numbers, but also delete the value I already set and clear the box. Instead once a value has been entered into the spinner, it won't allow deleting it, and put a "1" value inside.
Since I put [required]="false" it is expected that the spinner allow me to:
1. Not set a value from the start (already allows me)
2. Delete a value that was set, and clear the text box / control value - **Not possible with current version.**

Looks to me like a wrong behavior of the control.

**Comment by rubmz** [comment]
Any update on this?

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
