### ISSUE TITLE
Keyboard trap in MultiSelect

### ISSUE THREAD

**Issue by saharso** [primefaces/primeng#7267]
There is an accessibility issue in <p-multiselect>.

When the user tries to choose items using the keyboard, he or she may experience difficulties in case of multiple items. 

There is no way to close the select box and return to the app without using the mouse.

This can be easily solved with an Esc key option to close the dropdown once the user finished interacting with it.

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

Currently escape key hides the overlay.
