### ISSUE TITLE
Managing tooltip independently

### ISSUE THREAD

**Issue by procidis** [primefaces/primeng#7268]
Hello. 
I had a question and @yigitfindikli answered. In the next versions of ngprime, tooltip can be managed from outher resources. Related ticket is below:
[https://forum.primefaces.org/viewtopic.php?f=35&t=58217](link)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
