### ISSUE TITLE
[feature request] virtualscroller inside p-tree

### ISSUE THREAD

**Issue by skormel** [primefaces/primeng#7269]
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

I'm dealing with performance problem when using p-tree to generate a lot of items
It will very help full if we have virtualscroller inside p-tree.

Thanks

**Comment by cagataycivici** [comment]
Tracked at 8257
