### ISSUE TITLE
p-table virtualization bug on scroll(found in your demo page)

### ISSUE THREAD

**Issue by Spac3JaM** [primefaces/primeng#7270]
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Virtualized p-table becomes empty when you use the scroller and move the mouse away from the table.

**Expected behavior**
Load expected page in the p-table

Steps to reproduce:
1. scroll down with the mouse holding the scroller
2. move the mouse pointer away from the table while holding the scroller
3. the scroller returns to its previous place and the table becomes empty

Video of your demo page reproducing this bug [https://drive.google.com/file/d/1-0DuEcuVqXtAu_UpYNgd5WSIz_UiCKmK/view](url)

**What is the motivation / use case for changing the behavior?**
It is very obvious bug

* **Angular version:** 5.X

* **PrimeNG version:** all

* **Browser:** [all]
<!-- All browsers where this could be reproduced -->
 
* **Language:** [TypeScript all]

**Comment by DelyanRaychev** [comment]
I have the same problem. Is there any solution to workaround this behaviour?

**Comment by Prince7195** [comment]
Hi team, I also facing the same issue, while scrolling the table, when it reaches the end of the table, scroller becoming small and loading the blank screen, creating the infinite scrolling loop, not able to stop it.

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

The live demo also works fine.
