### ISSUE TITLE
p-calendar does not use dateFormat from locale although the docs imply it

### ISSUE THREAD

**Issue by simhnna** [primefaces/primeng#7273]
the docs suggest that you can provide the dateFormat as part of the locale.
```typescript
export class MyModel {

    en: any;

    ngOnInit() {
        this.en = {
            firstDayOfWeek: 0,
            dayNames: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
            dayNamesShort: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
            dayNamesMin: ["Su","Mo","Tu","We","Th","Fr","Sa"],
            monthNames: [ "January","February","March","April","May","June","July","August","September","October","November","December" ],
            monthNamesShort: [ "Jan", "Feb", "Mar", "Apr", "May", "Jun","Jul", "Aug", "Sep", "Oct", "Nov", "Dec" ],
            today: 'Today',
            clear: 'Clear',
            dateFormat: 'mm/dd/yy'
        };
    }
}
```

However p-calendar uses a defined interface of localeSettings that doesn't include dateFormat. Instead it only uses the dateFormat from the direct input.

```typescript
export interface LocaleSettings {
    firstDayOfWeek?: number;
    dayNames: string[];
    dayNamesShort: string[];
    dayNamesMin: string[];
    monthNames: string[];
    monthNamesShort: string[];
    today: string;
    clear: string;
}
```

Either remove dateFormat from the docs and explicitly state that the dateFormat needs to be provided seperately or use the dateFormat from the LocaleSettings.

I personally would prefer the second option.

**Comment by mickeyjohn** [comment]
The same issue here when I use 'es' locale. It always displays date in the default dateFormat. So it would be better if it will pick the dateFormat from the locale if dateFormat was not specified. 

Cheers.

**Comment by rafa-as** [comment]
@cagataycivici some news here? Would you accept a PR for this bug or only the primeng team can do it?

**Comment by PunkHaz4rd** [comment]
any update ?

**Comment by Antilamer1709** [comment]
Same problem.

**Comment by cinnest** [comment]
I was struggling with the same issue 'til I found a solution of a colleague which used the dateFormat property, It seems PrimeNg has changed it in some point so that dateFormat does not belong to the LocaleSettings anymore.

`<p-calendar id="birth" [(ngModel)]="birth"  yearNavigator="true" [yearRange]="yearRange" [locale]="locale" [dateFormat]="locale.dateFormat"></p-calendar>`

> DateFormat
>
> Default date format is mm/dd/yy, to customize this use dateFormat property or define it at locale settings. Note that standalone property overrides the value in locale settings. 
> 
> `<p-calendar [(ngModel)]="dateValue" dateFormat="dd.mm.yy"></p-calendar>`
> 
> Following options can be a part of the format.
> 
> d - day of month (no leading zero)
> dd - day of month (two digit)
> o - day of the year (no leading zeros)
> oo - day of the year (three digit)
> D - day name short
> DD - day name long
> m - month of year (no leading zero)
> mm - month of year (two digit)
> M - month name short
> MM - month name long
> y - year (two digit)
> yy - year (four digit)
> @ - Unix timestamp (ms since 01/01/1970)
> ! - Windows ticks (100ns since 01/01/0001)
> '...' - literal text
> '' - single quote
> anything else - literal text
https://www.primefaces.org/primeng/#/calendar

It's sad though that PrimeNg uses different format patterns than the usual. For instance our solution has a form in which the customer gives his birthday and it is going to be shown in a table afterwards. In this case using the date pipe on the table to format it on the same locale.dateFormat value results on a different format because the date pipe understands the "yy" as 2 instead of 4 digits as the p-calender.

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

The current code is;

```
    getDateFormat() {
        return this.dateFormat || this.locale.dateFormat;
    }
```

**Comment by neergaard79** [comment]
> Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
> 
> The current code is;
> 
> ```
>     getDateFormat() {
>         return this.dateFormat || this.locale.dateFormat;
>     }
> ```

The issue is that the dateFormat has a default value so it is always preferred:

`@Input() dateFormat: string = 'mm/dd/yy';`
