### ISSUE TITLE
p-autoComplete requires two clicks to show selected value

### ISSUE THREAD

**Issue by k9yosh** [primefaces/primeng#7274]
**I'm submitting a ...**  
[X] bug report

**Current behavior**
When an option is selected, the selected value is not shown, although the value binds properly. In order to display the option properly, have to click on the same option once more.

**Expected behavior**
When an option is selected, the current selection should be displayed

**Minimal reproduction of the problem with instructions**
This issue comes when the **p-autoComplete** element is created dynamically using a ***ngFor**. 
Check following for more info : https://stackblitz.com/edit/github-zbphun

* **Angular version:** 7.2.0

* **PrimeNG version:** 7.0.5

* **Browser:** Chrome 72

 
* **Language:** TypeScript 3.2

* **Node (for AoT issues):** `node --version` =   v10.15.0

**Comment by osalas891123** [comment]
How was this solved?

**Comment by k9yosh** [comment]
> How was this solved?

use **onClick** instead of **onSelect** as the trigger inside **p-autoComplete**
