### ISSUE TITLE
button bar option for timeonly input

### ISSUE THREAD

**Issue by hmk18** [primefaces/primeng#7277]
Does Primeng calendar timeonly has buttonbar option ? 

<p-calendar [(ngModel)]="dateTime.calendarStartTime"
                      styleClass="date-field"
                      inputStyleClass="form-control"
                      [showIcon]="true"
                      [timeOnly]="true"
                      [stepMinute]="30"
                      showButtonBar="true"
                      [defaultDate]="defaultDate"
                      >
          </p-calendar>

showbuttonbar is set true but onclick its show 00:00 instead of current time

**Comment by cagataycivici** [comment]
Please use forum for questions and support requests.

**Comment by InjamulCSE15** [comment]
You can try this and please give me feedback on whether the code works.
Here is the code that I used for my project requirements. You can modify it.
### HTML Code (Angular Template)
`<p-calendar  [(ngModel)]="fieldValue"  [showIcon]="true"  icon="pi pi-clock"  [timeOnly]="true"  [showTime]="true"
  hourFormat="12"  #calendar>
  <ng-template pTemplate="footer">
    <div class="p-datepicker-buttonbar">
      <button pButton type="button" class="p-button-text" (click)="nowButtonClick(calendar)" >Now</button>
      <button pButton type="button" class="p-button-text" click)="clearButtonClick(calendar)" > Clear</button>
    </div>
  </ng-template>
</p-calendar>
` 
### TypeScript Code (Component)
`fieldValue: Date | string = '';

  nowButtonClick(calendar: any): void {
    this.fieldValue = new Date(); // Set the current date and time
    calendar.overlayVisible = false; // Manually close the overlay
  }

  clearButtonClick(calendar: any): void {
    this.fieldValue = ''; // Clear the field value
    calendar.overlayVisible = false; // Manually close the overlay
  }`
