### ISSUE TITLE
p-calendar barfs when dateFormat has slashes

### ISSUE THREAD

**Issue by nevster** [primefaces/primeng#728]
I have a p-calendar with
dateFormat="dd/mm/yy"

When the page tries to render, the browser console show:
EXCEPTION: Error: Uncaught (in promise): Template parse errors:
Unexpected closing tag "p-calendar" (" ..." inputStyleClass=form-control [formControl]="form.controls['startDate']" dateFormat=dd/mm/yyyy>[ERROR ->]</p-calendar>

IE, there are no quotes around the dateFormat field and the slashes stuff it up.
(Works fine if I use something like dd-mm-yy.)

Using single quotes doesn't help.

This problem also presents itself for the placeholder text, ie
placeholder="dd/mm/yyyy"

Until this is fixed, the workaround I've done is
placeholder="dd/mm/yyyy ..." to add a space to the text
and
dateFormat="{{dateFormat}}"
to get the dateFormat from the component

**Comment by cagataycivici** [comment]
I can't replicate with PrimeNG 4.0.1, please drop a comment if issue still persists.
