### ISSUE TITLE
Cannot force checkbox to stay unchecked when clicked

### ISSUE THREAD

**Issue by JacobSiegle** [primefaces/primeng#7281]
I have a checkbox that when checked it must run some code, all the code must pass, then the checkbox can become checked. The issue is that if I set ngModel (status in the example below)  when the code fails the checkbox will not update it's state to show that it's been unchecked. The only way I can get the state of the checkbox to stay unchecked is if I viewchild it and set it's internal 'checked' property.

https://stackblitz.com/edit/github-t1qf1w

**Comment by cghislai** [comment]
You can work around it by calling setTimeout() before overwriting the value, or by injecting the changeDetector and trigger it manually.
This is because you change the value when the value changed, creating an endless loop. Angular should warn you about this in dev mode.

**Comment by JacobSiegle** [comment]
Thanks i'll close the issue. My initial confusion was because if you change the example stackblitz to a string[] and turn off binary mode you can force the checkbox to stay checked / unchecked when performing nearly the same code. The flaw I didn't realize was when testing I was assigning a new array value which forces "writeValue" to run again since it will catch the change to the input. Change detection errors never popup for this, i'm assuming it has something to do with the way ControlValueAccessor works but would need to dig deeper to be sure of the exact cause.
