### ISSUE TITLE
primeng multiselect select all checkbox not refreshing properly angular 7

### ISSUE THREAD

**Issue by vignesharjhi** [primefaces/primeng#7283]
<select class="form-control" style="z-index: 0" #dt name="selectedRegion" [ngModel]="selectedRegion" (change)="querySelectedRegions(dt.value)">
    <option
      *ngFor="let item of regions"
        [(ngValue)]= "item.name">{{item.name}}</option>
       </select>
      </div>
   </div>
 </div>
	<div class="col-md-3">
    <div class="form-label-group">
    <label for="Area">*Area :</label>
     <div class="input-group" id="Area">
      <span class="input-group-addon"><span class="glyphicon glyphicon-list"></span></span>
     <span >
     <p-multiSelect  #selectedAreas [options]="regionArea"
					[(ngModel)]="selectedArea"
					name="regionArea"
                    defaultLabel="Select"
                    maxSelectedLabels = "1"
                    resetFilterOnHide=true
                    optionLabel="name"                     
                    [style]="{minWidth:'200px',height: '37px'}">
	</p-multiSelect>
					
					
Typescript code like:

	querySelectedRegions(selectedRegion_l: string) {		
    
    this.selectedRegion = selectedRegion_l;
    this.regionArea.length = 0;
    this.selectedArea.length = 0;
   
        this.regions = [{
					 "name":"Mile High Region",
					 "areaList":[
						{
						 
						   "name":"Airport"
						},
						{
						 
						   "name":"Colorado Springs"
						}
						.
						.
						.
					 ]
				  },
				  {
					 "name":"Portland",
					 "areaList":[
						{
						   "name":"Beaverton"
						},
						{
							"name":"East Portland"
						}
						.
						.
						.
						]
				  }
				}  
				]
    const region = _.find(this.regions, {'name': this.selectedRegion});
   	 this.regionArea = _.cloneDeep(region.areaList);
  }

The main functionality is ,whenever I am changing the region the area list need to be updated in multiselect drop down.It is updating in areaList drop down but while selecting all, it is adding to the area list of previously selected region.

This issue is coming after I changed my primeng version from 6.1.5 to 7.0.5
![stack1](https://user-images.githubusercontent.com/27808636/53287459-669a3300-374a-11e9-8ee9-d05f69d110aa.png)
![stack2](https://user-images.githubusercontent.com/27808636/53287460-669a3300-374a-11e9-9134-1260a2e58691.png)

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
