### ISSUE TITLE
Lazy Loading support for Dropdown and MultiSelect Filtering

### ISSUE THREAD

**Issue by olegbabkevich** [primefaces/primeng#7284]
**I'm submitting an enhancement**  (check one with "x")

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/lazy-load-filter

**Current behavior**
Now controls are not designed, that options could be loaded on filter input. There is client-side filtration happens on filter (input).

**Expected behavior**
I expect an option, that visible in filtration options might be loaded on filter input.

**What is the motivation / use case for changing the behavior?**
The case when we need to do such filtration on back-end.

**Please tell us about your environment:**

* **Angular version:** 5.X
 7.2.2

* **PrimeNG version:** 5.X
 7.0.5

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
* Chrome: 72.0.3626
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** * `node --version` =  8.9.1

**Comment by yelhouti** [comment]
I'm working on this on a local branch, but I don't think you can manage to convince the prime team to merge my code, any ways let's discuss it:
I think the options should resemble those of Table, ie:
```
 <p-multiSelect [lazy]="true" [lazyLoadOnInit]="false" (onLazyLoad)="onLazyLoadEvent($event)"
                               [options]="options" ....></p-multiSelect>
```
When lazy is true, infinit-scroll is set to true.

Implementation concerns:
For multiselect, the select/unselect all checkbox will not work as it should as not all elements are visible, it should be replaced with a clear button...

**Comment by yelhouti** [comment]
You can find it implemented here in the meantime, I'll try to keep my branch up to date:
https://github.com/yelhouti/primeng/releases/tag/8.0.0-rc2

**Comment by Walteann** [comment]
I also wanted to know. This PR would suit my scenario

**Comment by hanyska** [comment]
+1

**Comment by ashelest** [comment]
I Also wanted to know. Is it possible to extend MultiSelect with lazy loading functionality ?
All of us would appreciate you.

**Comment by Xriuk** [comment]
Any news? This would be very useful

**Comment by leandroheidemann** [comment]
+1

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by Logic-Bits** [comment]
still open...
