### ISSUE TITLE
Loading table every time on child expansion

### ISSUE THREAD

**Issue by nitish31** [primefaces/primeng#7286]
On expansion of row it is taking some time in ms to expand(I think because of making complete table again on expansion/collision). So, is there any way to stop making table again and again, as it is impacting my perfomance.

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
