### ISSUE TITLE
Bugs in the simultaneous use of yearRange and minDate in p-calendar

### ISSUE THREAD

**Issue by sweetzhang** [primefaces/primeng#7288]
<p-calendar name="holderBirthday" dateFormat="yy-mm-dd" [readonlyInput]="true [monthNavigator]="true"  [yearNavigator]="true" yearRange="{{this.holderAgeRangeYear}}" [minDate]="holderMinDate" [maxDate]="holderMaxDate"  selectOtherMonths="true"
  [locale]="zhCN"></p-calendar>

    let today = new Date();
    this.holderMaxDate = this.holderMinDate = new Date();
    (this.holderMinDate = new Date(today)).setFullYear(today.getFullYear() - 50);
    (this.holderMaxDate = new Date(today)).setFullYear(today.getFullYear() - 18);
    this.holderAgeRangeYear = this.holderMinDate.getFullYear() + ':' + this.holderMaxDate.getFullYear();

When i use p-calender,i find had a bug ，minDate does not take effect when yearRange and minDate are used simultaneously。But when I switched years, it came into effect again.

**Comment by sweetzhang** [comment]
The conditions for this situation to occur are as follows：
1. The maximum date of yearRange is less than today.
2.The minDate's  year is similar to yearRange's minmum
Forgive my bad english.
I am looking  forward to your answer.
thx~~

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
