### ISSUE TITLE
Turbotable gets rerendered if you click the dropdown generated by paginator and rowsPerPageOptions (without selecting any option)

### ISSUE THREAD

**Issue by stratos-vetsos** [primefaces/primeng#7292]
```
[ x] bug report
```
**Current behavior**
The table is getting rerendered multiple times when you click the dropdown to select rows per page (by passing [rowsPerPageOptions] input)

**Expected behavior**
The table shouldn't get rerendered in this case

**Minimal reproduction of the problem with instructions**
Inspect the rerenders of the table component when you click the dropdown (without selecting any different rows per page option)

* **Angular version:** 7.1.1

* **PrimeNG version:** 7.0.0

* **Browser:** Chrome

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
