### ISSUE TITLE
TAB MENU Active class not adding for Disabled Tab

### ISSUE THREAD

**Issue by nanihub** [primefaces/primeng#7294]
Using the Tab menu and Conditionally disabling Tabs by setting up with;    visible:FALSE

If I go back  and set visible:TRUE in code able to see the tab but
ACTIVE class is not adding.

By using activeItem, still facing the same issue

**Comment by sswebcoder** [comment]
@nanihub 

Hello.
Im trying to reproduce your problem but it's works properly.
Can you check example? https://stackblitz.com/edit/primeng-tab-menu?file=src%2Fapp%2Fapp.component.ts

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.3.0, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
