### ISSUE TITLE
TreeTable top level nodes not aligned

### ISSUE THREAD

**Issue by tony21921** [primefaces/primeng#7297]
I am using p-treeTable to show my data. It works fine when there is only one root node. However, when there are both leaf node and node with children at top level, they are not aligned like lower level ones: The top level leaf node text is left aligned with the toggler of other node, which make it looks strange.

You can refer to the sample: https://stackblitz.com/edit/github-pqwiqu

I checked the generated HTML in browser, and noticed the p-treeTableToggler element is empty for the top level nodes, while there is an invisible "A" element with margin left for other levels.

**Comment by arikkfir** [comment]
This happens to us as well.

**Comment by SaulFein** [comment]
I am having the same issue.

**Comment by smitpsanghavi** [comment]
I recently encountered this. Looks very weird.
