### ISSUE TITLE
How to open p-table paginator ui dropdown panel towards top always?

### ISSUE THREAD

**Issue by JayakarVangeti** [primefaces/primeng#7298]
Hello I have a requirement where I need to open the paginator dropdown upwards only like this.  It should never open downwards.

![image](https://user-images.githubusercontent.com/20511332/53407635-a418ed80-39e2-11e9-933b-9f64f6f020e7.png)

would you please help me in achieving this?

**Comment by JacobSiegle** [comment]
This isn't easily possible and I cannot really see them adding it as a new feature. 

To manually do it you would need to get a ref to the dropdown in the paginator and then override the functionality.

**Comment by nkescobar** [comment]
I need to do the same. Help me!

**Comment by cagataycivici** [comment]
Use forum for questions and help requests please.
