### ISSUE TITLE
Extend MenuModel with new Router Options

### ISSUE THREAD

**Issue by KeithGillette** [primefaces/primeng#7299]
**I'm submitting a ...**
```
[X] feature request
```

**Current behavior**
So far as I can tell, the [MenuModel API](https://www.primefaces.org/primeng/#/menumodel) does not include a way to pass [NavigationExtras](https://angular.io/api/router/NavigationExtras) options to the Angular Router.

This makes it impossible to specify routing arguments like `queryParamsHandling` or `preserveFragment` to preserve or merge query parameters or preserve a fragment when navigating.

**Expected behavior**
Add an optional `navigationExtras: NavigationExtras` property to `MenuModel` to be passed to the Angular Router when navigating.

**What is the motivation / use case for changing the behavior?**
We want to preserve query parameters when navigating via `BreadcrumbComponent`.

**Comment by cagataycivici** [comment]
We need to add;

```
    fragment?: string;
    queryParamsHandling?: QueryParamsHandling;
    preserveFragment?: boolean;
    skipLocationChange?: boolean;
    replaceUrl?: boolean;
    state?: {
        [k: string]: any;
    }
```
