### ISSUE TITLE
Menubar without collapse

### ISSUE THREAD

**Issue by dbrezoev** [primefaces/primeng#730]
How can I make menu bar not collapse when on narrow screen?

**Comment by abishek** [comment]
@dbrezoev how are you making it collapse in the first place. I guess we can exchange notes, I have the reverse of your situation.

**Comment by sudheerj** [comment]
Can you please elaborate your question. MenuBar will shrink based on view port size and that is the responsive nature of menubar.

**Comment by cagataycivici** [comment]
Please use forum for how-to like questions.
