### ISSUE TITLE
Add frozen property to static column

### ISSUE THREAD

**Issue by andy200486** [primefaces/primeng#7300]
* **Angular version:** 7.2.3

* **PrimeNG version:** 7.0.5

Hi everyone,

It's not a bug, rather a question.
I would like to know if is it possible to add the frozen property to static column ? 
Could someone help me ?

Thanks

**Comment by JacobSiegle** [comment]
This is a question not an issue. It should be posted to the primeng forum instead.

If you search the docs from the table you can find this code - 
`<p-table [value]="sales" [scrollable]="true" scrollHeight="150px" frozenWidth="200px">
    <ng-template pTemplate="frozenheader">
        <tr>
            <th style="width:200px;height:84px">Brand</th>
        </tr>
    </ng-template>
    <ng-template pTemplate="frozenbody" let-sale>
        <tr>
            <td>{{sale.brand}}</td>
        </tr>
    </ng-template>
    <ng-template pTemplate="header">
        <tr>
            <th colspan="4">Sale Rate</th>
        </tr>
        <tr>
            <th colspan="2">Sales</th>
            <th colspan="2">Profits</th>
        </tr>
        <tr>
            <th>Last Year</th>
            <th>This Year</th>
            <th>Last Year</th>
            <th>This Year</th>
        </tr>
    </ng-template>
    <ng-template pTemplate="body" let-sale>
        <tr>
            <td>{{sale.lastYearSale}}</td>
            <td>{{sale.thisYearSale}}</td>
            <td>{{sale.lastYearProfit}}</td>
            <td>{{sale.thisYearProfit}}</td>
        </tr>
    </ng-template>
</p-table>`
