### ISSUE TITLE
v7.0.5 has been broken, fileuploader doesn't have XHR

### ISSUE THREAD

**Issue by mydocs24** [primefaces/primeng#7303]
Just code issue, someone deleted xhr from the event, and not this doesn't work:
```
handleBeforeSend(event): void {
    event.xhr.setRequestHeader('Authorization', `Bearer ${this.authenticationService.getToken()}`);
  }
```

I can't send there headers https://github.com/primefaces/primeng/blob/master/src/app/components/fileupload/fileupload.ts#L317

**Comment by mydocs24** [comment]
And if this is expected, it is definitely not a bugfix, so it can't be 7.0.5, it is 8.0.0, sorry

**Comment by cagataycivici** [comment]
Since new upload uses HttpClient, I think you need to write an interceptor to do it; e.g.

https://medium.com/@ryanchenkie_40935/angular-authentication-using-the-http-client-and-http-interceptors-2f9d1540eb8
