### ISSUE TITLE
New Beta of Fullcalendar has some breaking changes

### ISSUE THREAD

**Issue by 4kochi** [primefaces/primeng#7305]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

According to the documentation (https://fullcalendar.io/docs/v4/release-notes) there is a new way to initialize the fullcalendar library. And the imports of the fullcalendar nom modules have changed. So in order to use the latest version of fullcalendar there needs to be slight changes in how the library is initialized in the p-fullcalendar component.

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
