### ISSUE TITLE
Adjustments for Angular version 8

### ISSUE THREAD

**Issue by gasparbarancelli** [primefaces/primeng#7306]
When running version 7.0.4 of Primeng with version 8.0.0-beta.6 of Angular the project does not compile, returning the following error.

ERROR in node_modules/primeng/components/table/table.d.ts(5,27): error TS2307: Cannot find module '@angular/core/src/metadata/lifecycle_hooks'.

**Comment by cagataycivici** [comment]
Angular 8 is in beta so issue is not valid.

**Comment by gasparbarancelli** [comment]
@cagataycivici 
Version 8 of the angle was released within 2 days.

The problem reported in this issue continues.

**Comment by marslan2037** [comment]
@cagataycivici Angular 8 is released and issue is still there

**Comment by mdkamrul** [comment]
After update to angular 8 i am facing this issue

ERROR in node_modules/primeng/components/table/table.d.ts(7,27)

Can anyone help me?

**Comment by jeffersonbezerra** [comment]
[look this workaround](https://github.com/primefaces/primeng/issues/7627#issuecomment-497721584)
