### ISSUE TITLE
Table filter not applied if sortField is set but sortOrder is not

### ISSUE THREAD

**Issue by digaus** [primefaces/primeng#7309]
https://github.com/primefaces/primeng/blob/eb2b0ede979aa6eddb04a8d05c4eb61468f1de01/src/app/components/table/table.ts#L457

Problem is  `if (this.sortMode == 'single' && this.sortField)` amd followed by `if(this.sortField && this.sortOrder)` which results in a case where the filter is not reapplied after value changed.

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
