### ISSUE TITLE
VirtualScroll don´t fix scrollbar size on totalRecords change if scrollposition out of new totalRecords range

### ISSUE THREAD

**Issue by jtkDvlp** [primefaces/primeng#7315]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
 https://stackblitz.com/edit/primeng-tables-utqb2u?file=src%2Fapp%2Fapp.component.html

**Current behavior**
Scrolling down to the middle or end of the list and setting a filter the scrollbar won´t fix its size.

**Expected behavior**
Scrolling down to the middle or end of the list and setting a filter the scrollbar will fix its size and show the same items as before or the scrollview will jump to top and show the beginning of the list.

**Minimal reproduction of the problem with instructions**
- Visit https://stackblitz.com/edit/primeng-tables-utqb2u?file=src%2Fapp%2Fapp.component.html
- Scroll down to middle or end of the list
- Set a filter via the button

**What is the motivation / use case for changing the behavior?**
Filtering and virtualscroll have to work together.

**Please tell us about your environment:**
Windows 10, Angular ~7.0.0, Chrome latest

* **Angular version:** ~7.0.0

* **PrimeNG version:** ~7.0.0

* **Browser:** Chrome

**Comment by philipebr** [comment]
@cagataycivici @jtkDvlp I'm with this problem too, using Prime 7.1.0

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
