### ISSUE TITLE
Problem with filterBy only filters by label

### ISSUE THREAD

**Issue by Alberto-Amo-Marin** [primefaces/primeng#7317]
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/primeng-input-multiselect-jjgb4k

**Current behavior**
when i filter by 'value.code' it does not display any city.
But if i filter by 'label' if I type New... it displays New York.

**Expected behavior**
if I type 'NY' then New York should be displayed.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
I'm testing a multi-select component with 2 different filters 

**Please tell us about your environment:**
Windows 10 and Visual Studio Code

* **Angular version:** 6.0

* **PrimeNG version:** 6.0

* **Browser:** [Latest Firefox & Chrome ]
 
* **Language:** [TypeScript 2.9 ]

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
