### ISSUE TITLE
angular-cli@webpack

### ISSUE THREAD

**Issue by itsmeprasanjit** [primefaces/primeng#732]
primeng not working with angular-cli@webpack. Anybody else facing the same problem ?

**Comment by codedumper** [comment]
+1
Cannot find source file 'columntemplateloader.ts': Error: Can't resolve './columntemplateloader.ts' in '/Users/cdurieux/Node/portal2/node_modules/primeng/components/column'
 @ ./~/primeng/components/datatable/datatable.js 16:29-70
 @ ./~/primeng/primeng.js
 @ ./src/app/routes/login/login.component.ts
 @ ./src/app/routes/login/index.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

I will try getting primeng from repo.

**Comment by ctkdev** [comment]
Having issues with the new angular-cli@webpack and primeng:
angular-cli@webpack
$ ng version --verbose
angular-cli: 1.0.0-beta.11-webpack.2
node: 6.2.2
os: linux x64

My angular version: 
angular: "2.0.0-rc.5"

Used the angular-cli: 1.0.0-beta.11-webpack.2 version of the angular-cli to create the project.  Then added the dependencies for primeng and primeui: 

$ npm install --save primeui primeng

This installed the following versions: 
    "primeng": "^1.0.0-beta.12",
    "primeui": "^4.1.14",

I added an import to my app.module.ts file for primeng/primeng:

`
/**
 * src/app/app.module.ts
 */
import {BrowserModule} from '@angular/platform-browser';
import {NgModule} from '@angular/core';
import {FormsModule, FormBuilder} from '@angular/forms';
import {AppComponent} from './app.component';
import {HttpModule} from '@angular/http';
import {RouterModule} from '@angular/router';
import {LoginFormComponent} from './login-form/login-form.component';
import {AppRoutes} from './app.routes';
import 'primeng/primeng';

@NgModule({
  declarations: [
    AppComponent,
    LoginFormComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    RouterModule.forRoot(AppRoutes)
  ],
  providers: [FormBuilder],
  entryComponents: [AppComponent],
  bootstrap: [AppComponent]
})
export class AppModule {

}
`

Attempted to run "ng serve" and I receive around 75 warnings of the following format: 

WARNING in ./~/primeng/components/tree/treenodetemplateloader.js
Cannot find source file 'treenodetemplateloader.ts': Error: Can't resolve './treenodetemplateloader.ts' in '/home/christopher/source/angular2-projects/angular2-rc5-project/node_modules/primeng/components/tree'
 @ ./~/primeng/components/tree/uitreenode.js 16:31-66
 @ ./~/primeng/components/tree/tree.js
 @ ./~/primeng/primeng.js
 @ ./src/app/app.component.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

**Comment by codedumper** [comment]
+1 same issue with angular-cli. 
basically i solved it in my original webpack config without angular-cli.

**Comment by codedumper** [comment]
It seems to be related to the webpack sourcemap plugin. 
Originally my webpack config contains : 
```
       /*
       * Source map loader support for *.js files
       * Extracts SourceMaps for source files that as added as sourceMappingURL comment.
       *
       * See: https://github.com/webpack/source-map-loader
       */
      {
        test: /\.js$/,
        loader: 'source-map-loader',
        exclude: [
          // these packages have problems with their sourcemaps
          helpers.root('node_modules/primeng'), ]
      }

    ],
```

**Comment by codedumper** [comment]
Still open with Beta.13

**Comment by caseyhoward** [comment]
I'm not very familiar with webpack, so just to be clear, is there no workaround? primeng is completely unusable?

**Comment by codedumper** [comment]
The problem is not webpack but the way angular-cli use it.
Le sam. 27 août 2016 à 19:58, Casey Howard <notifications@github.com> a
écrit :

**Comment by ctkdev** [comment]
@caseyhoward primeng is usable in development mode.  You will get a lot of warnings in the dev console if you run: 

ng serve 

and every change will result in all of the warnings re-appearing in your dev console.  There is a new version of primeng that is supposed to come out early next week.  I will post here if upgrading to the new version fixes the issue for me.

**Comment by marcusreese** [comment]
Any updates? I'm getting 75 (or however many) warnings in `ng test` console. E.g.,
```
WARNING in ./~/primeng/components/dom/domhandler.js
Cannot find source file 'domhandler.ts': Error: Can't resolve './domhandler.ts' in 'C:\Dev\mission\mashup\node_modules\primeng\components\dom'
 @ ./~/primeng/components/button/button.js 12:19-47
 @ ./~/primeng/primeng.js
 @ ./src/app/app.component.spec.ts
 @ ./src \.spec\.ts
 @ ./src/test.ts
```
Disclaimer: I'm just getting started. Still figuring out how to get the css etc. to work.

**Comment by pjain11** [comment]
I tried with latest version 19 and seeing same issue using ng test
Cannot find source file 'treetable.ts': Error: Can't resolve './treetable.ts'

Anyone know how to solve this?

**Comment by cagataycivici** [comment]
Please use forum for cases like these. Templates like Ultima-Posedion are based on CLI and they have TreeTable working, better to discuss at forum.
