### ISSUE TITLE
Table State improvement

### ISSUE THREAD

**Issue by grozdanova** [primefaces/primeng#7320]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Expected behavior**

Hi! Could you think about opportunity to adding other kind of storage. Like data from server. 
Also adding more properties in TableState model, like: frozenCols and scrollableCols (Table - Scroll), selectedColumns (Table - Column Toggle) and etc.

Thanks in advance!

**Comment by DanRic** [comment]
Hi,
is possible to use state methods?
Like saveState(), restoreState(), getStorage(), clearState()?

Thanks

**Comment by grozdanova** [comment]
Hi,
It is possible, but really I don`t want to do it. Storage has limit and I
use it already. I have app with for example with 20 pages. There are pages
where i have 2 tables or table with 18 columns. It would be much easier.
If i have about 30 tables, I have to use storage for all of them.

Could you think about this opportunity.
Thanks

На вт, 19.03.2019 г. в 12:28 ч. DanRic <notifications@github.com> написа:

**Comment by cagataycivici** [comment]
Not in our roadmap and this issue does not seem to get attention from community. Thank you for your understanding.
