### ISSUE TITLE
inputswitch is broken with bootstrap theme

### ISSUE THREAD

**Issue by mgtskuntal** [primefaces/primeng#7321]
I use current version v7 and [inputswitch](https://www.primefaces.org/primeng/#/inputswitch) is still broken with bootstrap theme .
![untitled](https://user-images.githubusercontent.com/37828468/53659656-1e1ad200-3c82-11e9-9708-077d6cfc1db9.png)

**Comment by cagataycivici** [comment]
Bootstrap theme is not maintained anymore, you'd need Avalon Theme for bootstrap UI.
