### ISSUE TITLE
issue tree DragDrop PrimeNG

### ISSUE THREAD

**Issue by wassim21** [primefaces/primeng#7325]
cannot drag the tree and nodes
![primeng - google chrome](https://user-images.githubusercontent.com/27426327/53694083-dee7a080-3da9-11e9-969f-d15bb41a8b25.jpg)

**Comment by yigitfindikli** [comment]
This is not an issue. You can give statements for drop options. This example files only can drop in server 2.
![dragdrop](https://user-images.githubusercontent.com/19997575/53718028-1d915f80-3e6b-11e9-861c-07a9ac538659.png)
