### ISSUE TITLE
Growl: ability to set different lifetime for messages.

### ISSUE THREAD

**Issue by AlexandrDobrovolskiy** [primefaces/primeng#7328]
**Current behavior**
```
this.msgs.push({severity:'success', summary:'Success Message', detail:'Order submitted'});
```

**Expected behavior**
```
this.msgs.push({
  severity:'success'
  summary:'Success Message',
  detail:'Order submitted',
  life: 2000,  // or 0 if message needs to be sticky
});
```

In many cases users want success and info messages to disappear, but error and warns to stay until user closes it manually.

**Comment by JacobSiegle** [comment]
Growl is deprecated. If you use p-toast it has this feature.

https://www.primefaces.org/primeng/#/toast

**Comment by AlexandrDobrovolskiy** [comment]
> Growl is deprecated. If you use p-toast it has this feature.
> 
> https://www.primefaces.org/primeng/#/toast

It sounds good but I wouldn't want to migrate the whole project from angular 4 only for this.

**Comment by JacobSiegle** [comment]
I don't think they PrimeNG supports older versions, maybe they do if you have primeng pro or something. I would assume you could fork primeng or manually pull and include toast as a separate import.

**Comment by cagataycivici** [comment]
Use Toast please.
