### ISSUE TITLE
Calendar showing over input on Mobile Devices

### ISSUE THREAD

**Issue by shogogan** [primefaces/primeng#7329]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Can be verified directly on the primeng showcase.
https://www.primefaces.org/primeng/#/calendar

**Current behavior**
When opening the calendar on mobile devices (tested on iPhone5s[Safari and Chrome], Moto z2 Play and Moto G2), the calendar is shown on top of the input field (sometimes on the android it displays corectly or just blinks in the page and hides again)

Gif showing the current behavior
![primeng](https://user-images.githubusercontent.com/7622581/53739117-c17d0a00-3e6f-11e9-9e7d-c0036da7a863.gif)

**Expected behavior**
Calendar should show at the bottom of the field or change to touchUi if on mobileDevices

**Minimal reproduction of the problem with instructions**
Open a any calendar (non-touchui) in a mobile device on the showcase https://www.primefaces.org/primeng/#/calendar

**What is the motivation / use case for changing the behavior?**
the input field gets hidden behind the calendar causing confusion to the user.

**Please tell us about your environment:**

* **Angular version:** 7.2.0

* **PrimeNG version:** 7.05

* **Browser:** [Mobile Chrome XX | Android X.X Web Browser | iOS  Safari | iOS  UIWebView | iOS  WKWebView ]

**Comment by JacobSiegle** [comment]
I think this is the intended behavior. If the calendar thinks it won't fit on the view it renders on top of the input to have more room. You can verify this by creating enough space for the calendar to fully fit on the page.

![image](https://user-images.githubusercontent.com/5766272/53965891-a56ba980-40b7-11e9-9c09-1aef183c3aca.png)

**Comment by shogogan** [comment]
maybe it is the intended behavior, but it's not constant, sometimes it doesn't show on top, or it flickers, (as shown on the gif, i had to press it 2-3 times to it show)

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
