### ISSUE TITLE
MaxLength in InputMask tag not working

### ISSUE THREAD

**Issue by patty-victor** [primefaces/primeng#733]
in official documentation of primeng InputMask, both size and maxlength tags are number typed and default null. When I try to use [size] to set a size for the textfield, it works fine. But in [maxlength] I got this error:
`ORIGINAL EXCEPTION: Invalid integer literal when parsing null in base 10`

This is my piece of HTML with this problem: 
`<p-inputMask [(ngModel)]="valorInput" [size]="50" [maxlength]="15" ></p-inputMask>`

Any other tag of InputMask that I used is working properly but maxlength. Anyone else is on this issue?

**Comment by cghislai** [comment]
Looks like the angular maxlength validator is kicking in when this attribute is present. Probably it should be renamed back to the camleCased 'maxLength'

**Comment by sudheerj** [comment]
I'am not able to replicate the issue.It works fine with PrimeNG 2.x releases.Please try with latest versions.
`<p-inputMask id="basic" mask="99-999999" name="simple" [size]="50" [maxlength]="9"
                         [(ngModel)]="simple" placeholder="99-999999">`

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
