### ISSUE TITLE
p-calendar Date format support yy and yyyy for  two and four digits of year

### ISSUE THREAD

**Issue by sandipchitale** [primefaces/primeng#7330]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
p-calendar

DateFormat

Following options can be a part of the format.
...
...
y - year (two digit)
yy - year (four digit)
...

**Expected behavior**

This is counter intuitive. Please support:

yy - year (two digit) 
yyyy - year (four digit)

i.e. number of y's is same as number of digits of the year.

**What is the motivation / use case for changing the behavior?**

Natural expectation for date format.

**Comment by crumhorn** [comment]
We need this as well. Here's a hacky workaround I did for Primeng 8.0.1:

In our case we have 3 possible date formats, but it'll be easy to see where you can manipulate the code. I put the call to this ngAfterViewInit() in app.component.ts

` private installHacks(): void {
    // straight copy from "calendar.js" under primeng, ensure this matches latest versions when updating!
    // this hack allows two-digit years to be entered (20+ year is applied)
    Calendar.prototype.parseValueFromString = function (text) {
      if (!text || text.trim().length === 0) {
        return null;
      }
      let value;
      if (this.isSingleSelection()) {
        let parts = text.split("-");
        let df = SettingsService.DisplayDateFormat.toUpperCase();
        if (parts.length == 3) {
          switch (df) {
            case DateUtils.YYYY_MM_DD:
              if (parts[0].length === 2) {
                text = "20" + parts[0] + "-" + parts[1] + "-" + parts[2];
              }
              break;
            case DateUtils.DD_MM_YYYY:
              if (parts[2].length === 2) {
                text = parts[0] + "-" + parts[1] + "-" + "20" + parts[2];
              }
              break;
            case DateUtils.MM_DD_YYYY:
              if (parts[2].length === 2) {
                text = parts[0] + "-" + parts[1] + "-" + "20" + parts[2];
              }
              break;
          }
        }
        value = this.parseDateTime(text);
      } else if (this.isMultipleSelection()) {
        let tokens = text.split(',');
        value = [];
        for (let _i = 0, tokens_1 = tokens; _i < tokens_1.length; _i++) {
          let token = tokens_1[_i];
          value.push(this.parseDateTime(token.trim()));
        }
      } else if (this.isRangeSelection()) {
        let tokens = text.split(' - ');
        value = [];
        for (let i = 0; i < tokens.length; i++) {
          value[i] = this.parseDateTime(tokens[i].trim());
        }
      }
      return value;
    }
  }`

**Comment by cagataycivici** [comment]
This will break backward compatibility and introduce some pain to restore it back.
