### ISSUE TITLE
Improve showcase/documentation for Responsive

### ISSUE THREAD

**Issue by Cito** [primefaces/primeng#7331]
Please have a look at the [showcase for the responsive interface](https://www.primefaces.org/primeng/#/responsive).

You will notice that the HTML source does not show the most crucial thing in this demo, namely that the `ui-fluid` class must be set somewhere on a higher level element to enable responsive mode.

Also, it would be nice if there was a switch in the showcase that allows toggling between normal and responsive mode so that you can see and explore the difference in behavior.

Motivation / use case for changing the behavior: Making the responsive mode in the documentation better understandable.

PrimeNG version: 7.1

**Comment by cagataycivici** [comment]
Not sure if we need a switch for responsive mode, still will update the docs to add ui-fluid. Thank you.
