### ISSUE TITLE
Remove autoWidth from Dropdown

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#7337]
autoWidth causes significant performance problems so remove the property and let the page author define the width of the dropdown.

**Comment by dmytro-gokun** [comment]
@cagataycivici I think CHANGELOG has to be updated, so this is listed as a breaking change

**Comment by mertsincan** [comment]
@dmytro-gokun, Thanks a lot for your suggestion. Fixed now. Please check it ;)

**Comment by dmytro-gokun** [comment]
@mertsincan I hate too be that pedantic, but i'd expect to see that under 7.1.0, not 7.1.0-rc.1 
You see, we use your great library in a stable product and we do not update to release candidates. So, the only time we update is when there is a new stable version out. And a changelog for that version is what we check to see if there any breaking changes that require our attention. And I think this is how the most of enterprise customers do it..
