### ISSUE TITLE
[p-calendar] Tabindex on IE is wrong

### ISSUE THREAD

**Issue by ndthien2911** [primefaces/primeng#7341]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When tab then p-calendar 2nd not focus and first element of page is focused.

**Expected behavior**
Be able focus p-calendar after current calendar.

Run link on IE: https://www.primefaces.org/primeng/#/calendar

PrimeNG version:
7.0.3
IE version:
11

![untitled](https://user-images.githubusercontent.com/12371733/53859737-35a2e380-4011-11e9-80ca-453c05caa5dd.png)

Press Tab and nothing:
![untitled1](https://user-images.githubusercontent.com/12371733/53859793-6c78f980-4011-11e9-826d-151d69c81308.png)

Press Tab and first element is focused:
![untitled2](https://user-images.githubusercontent.com/12371733/53859842-992d1100-4011-11e9-97e1-ea61cc4c03ec.png)

Thank everyone!

**Comment by Mysame** [comment]
Most likely side-affect of what's described in #6270

**Comment by ndthien2911** [comment]
> Most likely side-effect of what's described in #6270

thank you. This bug still happen on IE 11 :(

**Comment by kito99** [comment]
We have experienced this as well.

**Comment by boisamazing** [comment]
Update:

This problem still exists in PrimeNG 8.

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
