### ISSUE TITLE
Floating label not working properly on p-dropdown

### ISSUE THREAD

**Issue by decentaur** [primefaces/primeng#7343]
[x] bug report 
[ ] feature request 
[ ] support request 

**Plunkr Case (Bug Reports)**

**Current behavior**
When using the keyboard to select values from a p-dropdown and using tab to leave the field, the floating label stops floating.

**Expected behavior**
The label should start floating as a value was selected.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/github-1eat1m
Press down followed by tab. 

**What is the motivation / use case for changing the behavior?**
This breaks the logic of a floating label

* **Angular version:** 
Angular 7.2.3

* **PrimeNG version:** 
PrimeNG 7.0.5

* **Browser:** 
Chrome
 
* **Language:**
TypeScript 3.1.6

**Comment by leon-technolution** [comment]
I am experiencing the exact same issue as the OP. Please look into this.

**Comment by secorguy** [comment]
Same issue. Thank you.

**Comment by arkasaha2** [comment]
I am also facing same issue here.

**Comment by saul9402** [comment]
I am also facing same issue here, :(

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
