### ISSUE TITLE
Table default sort is lost after reset

### ISSUE THREAD

**Issue by speti43** [primefaces/primeng#7344]
[x ] bug report => Search github for a similar issue or PR before submitting

**Current behavior**
Table looses default sort when you call reset method. 

**Expected behavior**
According to the documentation:
"sortField -> Name of the field to sort data by default."
"reset -> Resets sort, filter and paginator state."
So I would expect, reset restores the default state, and should not delete already set default states.

**Minimal reproduction of the problem with instructions**

1. Open https://stackblitz.com/edit/p-table-primeng-default-sort-bug
2. You can see Vin column is presorted.
3. Click Reset
4. Then table looses presorting

* **Angular version:** 7.2.3

* **PrimeNG version:** 7.0.5

* **Browser:** Chrome

**Comment by cagataycivici** [comment]
The name of the function is misleading, reset should be clear.

**Comment by MassiveHiggsField** [comment]
Im confused, what should be used to restore the default state ( including the default sort)?
