### ISSUE TITLE
VirtualScroller is not working if inside a hidden container

### ISSUE THREAD

**Issue by qiyus** [primefaces/primeng#7345]
[x] bug report
[ ] feature request
[ ] support request

Plunkr Case (Bug Reports)

Current behavior
VirtualScroller in TabView row is not fully displayed

Expected behavior
VirtualScroller in TabView row is fully displayed

Angular version:
Angular 7.2.3

PrimeNG version:
PrimeNG 7.0.5

Browser:
Chrome

Language:
TypeScript 3.1.6

**Comment by skappler** [comment]
Having the same problem

**Comment by skappler** [comment]
I just found a workaround for the issue. The key is to load the virtual scroll using ngIf just when the tab is selected. For example:

```
<p-tabView (onChange)="changeTab($event)" >
  <p-tabPanel header="First Tab">
    ...
  </p-tabPanel>
  <p-tabPanel header="Virtual Scroll">
    <div *ngIf="scrollTabSelected">
      <p-virtualScroller></p-virtualScroller>
   </div>
 </p-tabPanel>
</p-tabView>
```
And in the component:

```
changeTab(ev) {
  this.scrollTabSelected = ev.index === 1;
}
```

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

I see that necessary checks are available in PrimeNG 9 to make it work when initially hidden.

**Comment by AlbaSS18** [comment]
Hello, this issue persists with Prime 10 and 11. I have done a stackblitz. 
https://stackblitz.com/edit/primeng-bug-tabview-demo?file=src/app/app.component.ts

As you can see, in the second header the data is loaded into the table but not into the virtualscroller.

I hope it helps @cagataycivici

**Comment by AbakumovAlexandr** [comment]
@cagataycivici I have the same issue with the latest PrimeNG (15.3.0). 

My `<p-table>`'s template declaration:
```
                                    <p-table
                                        [value]="dataSource"
                                        [scrollable]="true"
                                        [scrollHeight]="'10rem'"
                                        [virtualScroll]="true"
                                        [virtualScrollItemSize]="46">

```
If `dataSource` is updated and `<p-table>` is inside a `display: none;` parent element, `<p-table>` displays itself as an empty\transparent block when that parent element becomes visible.

Could you advice. please?
