### ISSUE TITLE
Dialog - CSS class media query sticks around in dialog - Minor

### ISSUE THREAD

**Issue by JacobSiegle** [primefaces/primeng#7349]
I have a css class passed into the dialog. The css class is only in a media query for mobile devices. The reason for this is I want the dialog to fill the screen for mobile devices. For desktop / tablet I am fine letting PrimeNG figure out how to size the dialog.

Open / close  the dialog in tablet / desktop mode to see it at full width - 
![dialog-tablet](https://user-images.githubusercontent.com/5766272/53964886-c501d280-40b5-11e9-974f-e8aebc53abee.png)

Open /close the dialog in mobile mode to see it with media query specific class applied - 
![dialog-mobile](https://user-images.githubusercontent.com/5766272/53964893-c9c68680-40b5-11e9-96d2-31674248ca6a.png)

Open the dialog in tablet / desktop mode again to see it now much smaller - 
![dialog-tablet-broken](https://user-images.githubusercontent.com/5766272/53964898-cb904a00-40b5-11e9-831a-459f2028f858.png)

This may naturally be fixed by - https://github.com/primefaces/primeng/issues/6992
PrimeNG - 7.0.5

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
