### ISSUE TITLE
PrimeNG themes leak global styling

### ISSUE THREAD

**Issue by kormide** [primefaces/primeng#7352]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-g1quqa

**Current behavior**
PrimeNG themes globally style links and make every element use border-box sizing. This can cause styling issues for custom or third party components that are outside of PrimeNG's control.
 
**Expected behavior**
PrimeNG themes only affect explicitly declared PrimeNG components/directives/classes.

* **Angular version:** 7.X

* **PrimeNG version:** 7.X

* **Browser:** [all]

**Comment by cagataycivici** [comment]
Invalid issue.

**Comment by kormide** [comment]
This is absolutely a valid issue. PrimeNG is assuming that it's the only component library in use. Other design systems (see material) are careful to isolate their styling and theming to the components they own.

**Comment by jbedard** [comment]
I'm having this issue too. I think this is a valid issue

**Comment by jbedard** [comment]
@cagataycivici can you explain why you don't think this is an issue? In my case this is breaking the use of other libraries alongside primeng.

**Comment by KensingtonTech** [comment]
For the benefit of others whose apps were broken by this behaviour, I un-broke this by adding this to my styles.css:

```
/* undo PrimeNG's global change */
* {
  -moz-box-sizing: content-box;
  -webkit-box-sizing: content-box;
  box-sizing: content-box;
}

/* re-apply only for PrimeNG elements */
[class^="ui-*"] {
  -moz-box-sizing: border-box;
  -webkit-box-sizing: border-box;
  box-sizing: border-box;
}
```

**Comment by antch** [comment]
@cagataycivici This is absolutely a valid issue, I honestly cannot believe that anyone would think it isn't. In my case (LESS) I had to create a custom plugin that removes the `body` top-level selectors from the `theme.css`, and then scoped the import inside of a top level element selector. I'm only using `p-table`, so it would be like:

```
p-table { /* more element selectors could be added here */
  @import (less) '~primeng/resources/primeng.min.css';
  @import (less) '~primeng/resources/themes/nova-light/theme.css';
}
```

**Comment by asmith2306** [comment]
Why is this issue closed??  I use a Material theme and the primeng nova-light theme in my app.  This broke a part of my app and I was scratching my head until I found it.  Don't apply global styles!

**Comment by mralbobo** [comment]
This "thing" gets even more ridiculous when you see that that primeng.min.css defines this rule:
`.ui-widget, .ui-widget * {
	box-sizing: border-box;
}`

...which for my app at least already seems to border-box everything it actually needs to.
It's just theme.css polluting for no obvious reason.

**Comment by ramtob** [comment]
Also having this problem

**Comment by waleedbintariq1** [comment]
Anybody found a solution for this yet? I'm using PrimeNG calendar component. For that I imported the styles in global scss file. But, this has conflicted with my custom css for buttons. Is there any way I can scope the PrimeNG imports to the calendar component?

**Comment by antch** [comment]
> Anybody found a solution for this yet? I'm using PrimeNG calendar component. For that I imported the styles in global scss file. But, this has conflicted with my custom css for buttons. Is there any way I can scope the PrimeNG imports to the calendar component?

I now use `patch-package` to patch the appropriate `theme.css`, replacing `:root` selectors with `.p-component`. The `*` selector gets replaced with `.p-component, .p-component *` for `box-sizing`.

**Comment by waleedbintariq1** [comment]
@antch Can you provide some more detail? With an example if possible?

**Comment by waleedbintariq1** [comment]
> > Anybody found a solution for this yet? I'm using PrimeNG calendar component. For that I imported the styles in global scss file. But, this has conflicted with my custom css for buttons. Is there any way I can scope the PrimeNG imports to the calendar component?
> 
> I now use `patch-package` to patch the appropriate `theme.css`, replacing `:root` selectors with `.p-component`. The `*` selector gets replaced with `.p-component, .p-component *` for `box-sizing`.

For how long have you been using this solution? I just want to know the feasibility of this solution considering any future updates for PrimeNG. Do you patch again whenever a new update rolls out (if required)?

**Comment by antch** [comment]
> > > Anybody found a solution for this yet? I'm using PrimeNG calendar component. For that I imported the styles in global scss file. But, this has conflicted with my custom css for buttons. Is there any way I can scope the PrimeNG imports to the calendar component?
> > 
> > 
> > I now use `patch-package` to patch the appropriate `theme.css`, replacing `:root` selectors with `.p-component`. The `*` selector gets replaced with `.p-component, .p-component *` for `box-sizing`.
> 
> For how long have you been using this solution? I just want to know the feasibility of this solution considering any future updates for PrimeNG. Do you patch again whenever a new update rolls out (if required)?

For at least 3 years; I just have to do a new patch for each version. It's very straightforward if you read up on `patch-package`.
