### ISSUE TITLE
Default button classes for ConfirmDialog

### ISSUE THREAD

**Issue by kartik468** [primefaces/primeng#7356]
**Current behavior**
It would be better if we have default classes for accept and reject buttons like "accept-button" and "reject-button" for confirmdialog default footer buttons

**Expected behavior**
No class present in order to differentiate between accept and reject button

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/github/vbwilqlo
https://vbwilqlo.github.stackblitz.io/

In confirmdialog.ts, there should be default values for acceptButtonStyleClass, rejectButtonStyleClass like this

@Input() acceptButtonStyleClass: string = "accept-button";
@Input() rejectButtonStyleClass: string = "reject-button";

**What is the motivation / use case for changing the behavior?**
It will be easier to style confirm dialog buttons across the app instead of setting acceptButtonStyleClass for every instance that are used.

**Please tell us about your environment:**
Windows

* **Angular version:** 5.X
"@angular/core": "~7.2.0",

* **PrimeNG version:** 5.X
"primeng": "^7.0.0",

* **Browser:** 
ALL

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
We decided to keep it as it is as props are already available for you to add classes.

**Comment by cagataycivici** [comment]
Change of plans, we're adding it.

**Comment by kartik468** [comment]
> Change of plans, we're adding it.

Thanks
