### ISSUE TITLE
P-Calendar fires onBlur event upon clicking a date in the calendar

### ISSUE THREAD

**Issue by wewedgeworth** [primefaces/primeng#7357]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
We have a p-calendar with an onBlur event. When we expand the calendar, and click a date to select it, the onBlur event is getting fired. Afterwards, the p-calendar field is re-focused. Then, once the field is actually blurred by the user, onBlur fires again.

**Expected behavior**
There is already a onSelect event which is meant to fire when the user selects a date through the calendar. Also, the field remains focused after the user selects a date. For these two reasons, it does not make sense for onBlur to fire upon clicking a date in the calendar. onBlur should only fire when the field is actually blurred by the user.

**Minimal reproduction of the problem with instructions**
Create a p-calendar with onBlur event.

* **Angular version:** 5.X
Angular 5.2.1

* **PrimeNG version:** 5.X
PrimeNg 5.2.5

* **Browser:** 
Chrome

**Comment by nitoloz** [comment]
Having the same problem with primeng 7.1.2 and angular 7.2.14.
This seems quite critical for me as I would like to set the "default" date if user has given incorrect date and leaves the input, but it turns out that I override user's input when he selects a date in calendar.

Please find steps to reproduce below:
* Put cursor in calendar input and erase the date
* Select any date in calendar
* (onBlur) event is fired and selected date in calendar gets overwritten with "default" date

**Comment by nitoloz** [comment]
Here are some results of a short investigation:
The `<p-calendar>` template contains an input that has `(blur)="onInputBlur($event)"` callback attached to it that leads to `onBlur` event being triggered if user leaves input to click smth in calendar dropdown (datepicker). The `onInputBlur` function code is following:
```
    onInputBlur(event: Event) {
        this.focus = false;
        this.onBlur.emit(event);
        if (!this.keepInvalid) {
            this.updateInputfield();
        }
        this.onModelTouched();
    }
```

However there is another function that might help us solve this problem in case of "input+datepicker" configuration - `bindDocumentClickListener()`. It basically watches every click use makes while datepicker dropdown is open and closes mentioned dropdown if click was made outside of component template (including datepicker). The code of the function is following:
```
    bindDocumentClickListener() {
        if (!this.documentClickListener) {
            this.documentClickListener = this.renderer.listen('document', 'click', (event) => {
                if (this.isOutsideClicked(event) && this.overlayVisible) {
                    this.hideOverlay();
                }

                this.cd.detectChanges();
            });
        }
    }
```

So I would propose to add another `@Output` called `onMouseOut()` that will be thrown after `this.hideOverlay();` function is called in `bindDocumentClickListener()`.

**Comment by rafa-as** [comment]
Same here! @cagataycivici some news?

**Comment by rafa-as** [comment]
@cagataycivici @yigitfindikli some news here?

**Comment by dariotortola** [comment]
When using a form with updateOn: 'blur', since p-calendar does not fire blur on select, the form group is not notified

**Comment by rmganesh6** [comment]
> 

Hi @dariotortola , I have used for group and set updateOn: 'blur' but still onblur is fired on select. do we need to apply any other settings?
