### ISSUE TITLE
Calendar touchUI on mobile devices - Cannot use due to keyboard popup

### ISSUE THREAD

**Issue by JacobSiegle** [primefaces/primeng#7358]
When using touch UI on the calendar input should not happen to prevent the keyboard from displaying.

![Screenshot_20190308-155439](https://user-images.githubusercontent.com/5766272/54058208-cd900100-41ba-11e9-8dd1-15f715810597.png)

**Comment by cyberrranger** [comment]
the same on ios, use demo https://www.primefaces.org/primeng/#/calendar to test ist

**Comment by cagataycivici** [comment]
Fixed via #7555

**Comment by cagataycivici** [comment]
I set inputmode="off" if touchui is on for 10.
