### ISSUE TITLE
Table columns become misaligned when scrollbars appear / disappear using frozen

### ISSUE THREAD

**Issue by JacobSiegle** [primefaces/primeng#7359]
Opened due to #6560 being closed.

First render with scroll - 
![first_render](https://user-images.githubusercontent.com/5766272/54039403-76713880-4188-11e9-9a92-cd0867a89627.png)

Opening a row to make the table have vertical scroll causes the RHS scrollbar to overlap the data - 
![rhs_scroll_added](https://user-images.githubusercontent.com/5766272/54047239-27350300-419c-11e9-89c2-c49a71baf320.png)

Resizing the columns to fit the screen causes extra space to exist on the bottom of the table when the horizontal scrollbar is removed - 
![resize_columns](https://user-images.githubusercontent.com/5766272/54039645-14650300-4189-11e9-9586-333fd40302d7.png)

First render fails when you have a scrollable table that happens to not scroll due to lack of rows. The padding is always put onto the bottom of the table no matter what.
![first_render_broken](https://user-images.githubusercontent.com/5766272/54040385-d072fd80-418a-11e9-9baf-1a2388c459b7.png)

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
