### ISSUE TITLE
[Dialog] When opening dialog if maximizable set to true and on mobile then default to maximised

### ISSUE THREAD

**Issue by chrizy** [primefaces/primeng#7360]
**feature request**

It would be great if a new option or default behaviour for Dialog would be to display full screen on small devices such as <576px if maximizable set to true.

We think this is a better user experience.

**PrimeNG version 7.0.4:** 

Thanks

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9 which has a new Dialog, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
