### ISSUE TITLE
TypeError: Cannot read property 'nodeName' of null at Table.handleRowClick

### ISSUE THREAD

**Issue by aspramsh** [primefaces/primeng#7363]
I get the following error when I click enter on p-table editable column cellEditor: TypeError: Cannot read property 'nodeName' of null at Table.handleRowClick. Could someone explainwhy? When I put the input inside html form, the error disappears.

**Comment by cagataycivici** [comment]
Provide a stackblitz template please.

**Comment by bennylava10100** [comment]
I'm getting the same thing when putting custom angular component inside a tr for turbo table.

```
 <td>
    <sn-player-game-history-button [playerId]="rowData.id"></sn-player-game-history-button>
 </td>
``` 

The code behind sn-player-game-history-button is:

`<button [disabled]="buttonDisabled" *ngIf="state === ViewState.None" pButton type="button" icon="fas fa-address-book"
  [label]="lookupStateLabel" (click)="loadHistory()"></button>
<div *ngIf="state === ViewState.Loading" style="padding: 4px 8px">
  <i class="fas fa-spinner fa-spin"></i>
</div>
<button [disabled]="buttonDisabled" *ngIf="state === ViewState.Loaded" pButton type="button" icon="fas fa-address-card"
  [label]="loadedStateLabel" (click)="showHistory()"></button>
<sn-player-game-history-dialog #gameHistoryDialog></sn-player-game-history-dialog>`

This is a mayor problem for us an we are yet to find a workaround. Problem seems to be in https://github.com/primefaces/primeng/blob/master/src/app/components/table/table.ts#L772 but I can't be sure.

**Comment by Rillist** [comment]
I have the same issue with pEditableColumn as well, here is a stackblitz example. Note that the error is intermittent, and occurs when the row selection fails.

https://stackblitz.com/edit/nodenameofnull

**Comment by Rillist** [comment]
Seems like a simple check for null/undefined fixes the issue, I made a PR if someone wants to take a look.
https://github.com/primefaces/primeng/pull/7443

Sorry if I am not following correct process, I didn't see any contribution guides but honestly I didn't look very hard either.
