### ISSUE TITLE
Overlay still displays when using `overlayVisible = false` in "range" `selectionMode`

### ISSUE THREAD

**Issue by SSTPIERRE2** [primefaces/primeng#7365]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://github-jryuuv.stackblitz.io

**Current behavior**
When in "range" selection mode, programmatically closing the calendar by setting the only currently exposed property `overlayVisible = false` closes the calendar, but does not close the opaque overlay, making it so you cannot click anywhere on the page anymore (due to its z-index).

**Expected behavior**
Setting `overlayVisible` to false (or expose a method to close the calendar?) should properly hide the calendar's opaque `ui-widget-overlay` as well as the calendar itself.

**Minimal reproduction of the problem with instructions**
* Open provided Stackblitz link, click on the input field to open the calendar
* select a date range
* observe that the calendar closes, yet the overlay does not, so you can't click anything anymore

**What is the motivation / use case for changing the behavior?**
This bug essentially breaks the page for most users, requiring a refresh unless you know how to hide elements via developer tools...

**Please tell us about your environment:**
* See Stack Blitz template.

* **Browser:** Chrome, FireFox, Safari, probably all of them because it seems related to programming logic, not the browser.

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
