### ISSUE TITLE
Virtual Scrolling not working well

### ISSUE THREAD

**Issue by neardreams** [primefaces/primeng#7366]
**Current behavior**
Virtual Scrolling on datatable and multiselect not working well.
The scroll won't stop after continuous fast scrolling (by mouse wheel or click the scroll bar and hold).
It will keep scrolling till the end of the list.
https://youtu.be/gPNAYrEOL5w

**Expected behavior**
Stop scrolling after mouse is released.

**Minimal reproduction of the problem with instructions**
Not quiet sure how it happened.

**Please tell us about your environment:**
Web Host:  1. Angular dev hosting  2. Azure App Service
OS: Windows 10 Pro 1809
Packages:
   "@angular/animations": "^7.2.8",
    "@angular/cdk": "^7.3.4",
    "@angular/common": "^7.2.8",
    "@angular/compiler": "^7.2.8",
    "@angular/core": "^7.2.8",
    "@angular/forms": "^7.2.8",
    "@angular/platform-browser": "^7.2.8",
    "@angular/platform-browser-dynamic": "^7.2.8",
    "@angular/router": "^7.2.8",
    "core-js": "^2.6.5",
    "firebase": "^5.8.4",
    "font-awesome": "^4.7.0",
    "primeflex": "^1.0.0-rc.1",
    "primeicons": "^1.0.0",
    "primeng": "^7.1.0-rc.1",
    "rxjs": "^6.4.0",
    "tslib": "^1.9.3",
    "zone.js": "^0.8.29"

* **Angular version:** 5.X
    "@angular/core": "^7.2.8",

* **PrimeNG version:** 5.X
    "primeflex": "^1.0.0-rc.1",
    "primeicons": "^1.0.0",
    "primeng": "^7.1.0-rc.1",

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chromium Version 72.0.3626.121 (Official Build) (64-bit)
Chrome Version 72.0.3626.121 (Official Build) (64-bit)
Cent Browser Version 3.8.5.69 (Official Build) (32-bit) (Chromium 71.0.3578.98)
Opera 58.0.3135.79

Edge, IE11 ,FIrefox 65.0.2 (64-bit) Works fine

**Comment by philipebr** [comment]
@cagataycivici @neardreams this happened with me too, using only the virtual scroller component and using virtual scroller with turbotable, both with lazy load.

I'm using primeng 7.1.0 and Angular 7 (core 7.2.12)

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
