### ISSUE TITLE
Unify style (horizontal alignment) for input components (dropdown, multiSelect)

### ISSUE THREAD

**Issue by thaihacong** [primefaces/primeng#7367]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request 
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-cfjspw?file=src%2Fapp%2Fapp.component.html

**Current behavior**
In the given Plunkr, I put p-multiSelect, p-dropdown, pInputText and p-calendar inputs next to each other in a row. Each input has the same width of 200px.
When I inspect HTML element, each main div (e.g. ".ui-widget") for each input has same size of 200x33 px.
![primeng-input-components-style](https://user-images.githubusercontent.com/8019304/54195748-c66d3980-44bf-11e9-9588-59c42fdffc10.png)
However, as we can see from the screenshot, those inputs are not  horizontally aligned.
- p-multiSelect is aligned much upper than the others.
- p-dropdown is, I think, 1px aligned lower then pInputText and p-calendar.

Therefore, I have to wrap each kind of input into an extra div and style differently in my code.

**Expected behavior**
Components should be aligned by default, without extra styles.

* **Angular version:** 7.2.2

* **PrimeNG version:** 7.1.0

* **Browser:** Chrome, Firefox

**Comment by RFMV34** [comment]
I see the same behavior in my project...

**Comment by godfryd** [comment]
I have the same problem:

![image](https://user-images.githubusercontent.com/176567/66624085-f237d580-ebee-11e9-8d78-34d1aec8282d.png)

It looks that height of p-multiSelect is 16px instead of 33px.

**Comment by pnlaera** [comment]
New style 'display: inline-flex' is broken for label greater than dropdown
