### ISSUE TITLE
p-radioButton, click on label fires click event twice

### ISSUE THREAD

**Issue by sunnyyadav100** [primefaces/primeng#7368]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

**Current behavior**

```
click { target: label.ng-star-inserted.ui-radiobutton-label.ui-label-active
, buttons: 0, clientX: 67, clientY: 36, layerX: 74, layerY: 44 }

click { target: input#inputtype0, buttons: 0, clientX: 67, clientY: 36, layerX: 74, layerY: 44 }
```

**Expected behavior**

One click event

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.X

7
* **PrimeNG version:** 5.X

7.1 RC1
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 All
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by dineshmaths1** [comment]
Am also facing this issue . How to fix?

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
