### ISSUE TITLE
[Table] Cell editing breaks under ChangeDetectionStrategy.OnPush

### ISSUE THREAD

**Issue by earshinov** [primefaces/primeng#7370]
**I'm submitting a ...**

[x] bug report

**Plunkr Case**

https://stackblitz.com/edit/primeng-table-changedetectiononpush

Note the `ChangeDetectionStrategy.OnPush` in the `AppComponent`.

**Current behavior**

Repro steps:
1. Click the date field to start editing
2. In the dropdown calendar, choose another date by clicking
3. Click somewhere in the page body outside the table

After that:
1. The date field cell editor remains present
2. Table cell paddings increase

![image](https://user-images.githubusercontent.com/52021/54235745-044f7980-4523-11e9-845e-8cc99362cd6f.png)

After clicking the date field again, the table returns to the initial state.

**Expected behavior**

After clicking somewhere outside the table, I would expect
1. The cell editor to deactivate
2. Table cell paddings to stay as they were

**Minimal reproduction of the problem with instructions**

See StackBlitz example and repro steps above.

**What is the motivation / use case for changing the behavior?**

Pages with data tables typically contain much data and are susceptible to performance problems, and `ChangeDetectionStrategy.OnPush` is a good way to solve them. I think it would be a worthy goal for PrimeNG data tables to support `ChangeDetectionStrategy.OnPush`. 

**Please tell us about your environment:**

- PrimeNG 7.0.5
- @angular/core 7.2.8
- Google Chrome 72.0.3626.121 (Official Build) (64-bit) (cohort: Stable)
- TypeScript 3.2.4

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
