### ISSUE TITLE
p-tree: Narrator reading incorrect Grouping order of tree items in tree

### ISSUE THREAD

**Issue by manidevzen3** [primefaces/primeng#7371]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**Current behavior**
Narrator reading tree item's Grouping order number incorrectly which will be an issue for visually impaired people

**Expected behavior**
Grouping order number of tree items in tree should be able to read by any screen reader correctly

**Minimal reproduction of the problem with instructions**
create any p-tree (or take demo tree UI from https://www.primefaces.org/primeng/#/tree)  and turn on Narrator, listen to the speech over for every tree item in tree

* **Angular version:** 4.1.3

* **PrimeNG version:** 4.2.1

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
