### ISSUE TITLE
PrimeNg Scroll panel

### ISSUE THREAD

**Issue by thirikudarajappan** [primefaces/primeng#7372]
Current behavior
I'm currently using Table with sort component , if I scroll down until the end of the table content and then I apply the sort scroll does not reset and stays at the  bottom of this table

Expected behavior
I would expect whenever I apply the filter scroll would move to top (the first time). 

Browser: all

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
