### ISSUE TITLE
Overlay panel adding display none style.

### ISSUE THREAD

**Issue by ibtisamniche-vteams** [primefaces/primeng#7374]
Hi!
I am using primeng version 4.3.0 in my project. The problem is when I use the overlay panel component of primeng and use the toggle function to show the overlay panel it adds the inline style of **display:none** due to that the overlay panel doesn't shows. Kindly help me to solve this issue and tell me why is that happening???
Thanks.

Here is the image manifesting the issue.
![imageedit_5_5652468539](https://user-images.githubusercontent.com/35001739/54286547-dec77c00-45c5-11e9-848a-82955182a339.png)

**Comment by balkrishnaincapsulate** [comment]
Hey!
I am also using primeng version 4.3.3 and the customize style is not displayed on overlay panel. @cagataycivici Please Look into it.

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Comment by sean-legitscript** [comment]
Just wanted to double-check on this one. Did there end up being a good solution for this one? Tried this on both 6.1.7 and 11.3.0 and haven't found a good alternative.
