### ISSUE TITLE
issue Tree

### ISSUE THREAD

**Issue by wassim21** [primefaces/primeng#7378]
filter is not displayed
![image](https://user-images.githubusercontent.com/27426327/54311285-8f3c7c80-45d4-11e9-9a58-f2337ee0d23a.png)
![image](https://user-images.githubusercontent.com/27426327/54311326-a4b1a680-45d4-11e9-8d8a-9c4aa830f1c8.png)

**Comment by mertsincan** [comment]
Which version are you using?

**Comment by wassim21** [comment]
I use V7

**Comment by mertsincan** [comment]
I couldn't replicate it with 7.1.0. Could you please attach a stackblitz link for us to replicate?

**Comment by wassim21** [comment]
I have updated primeng from 7.0.5 to 7.1.0 
the problem was resolved
