### ISSUE TITLE
Nova-light: Border-box sizing applied to all html elements

### ISSUE THREAD

**Issue by tunderhayDemisto** [primefaces/primeng#7383]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/github-g1quqa

**Current behavior**
Nova-light now globally applies border-box sizing to all HTML elements of an application. This causes styling issues for custom or third party components that are outside of PrimeNG's control.

You can say that this a duplicate of 7352, which was summarily closed without explanation.  I can think of no reason for PrimeNG to apply border-box sizing to * as it changes the sizing of all elements, even those elements which don't use PrimeNG.  If your inclination is to close this as well, I respectfully request a reason be provided for this behavior.

This breaks styling globally:

resources/themes/nova-light/theme.css
```
* {
  -moz-box-sizing: border-box;
  -webkit-box-sizing: border-box;
  box-sizing: border-box;
}
```

Before PrimeNG 7 (default content-box):
![BeforePrimeNG7](https://user-images.githubusercontent.com/44418498/54358510-f5f28200-4636-11e9-8c4c-ab3a624d0bfc.png)

After PrimeNG 7 (now with nova-light's border-box applied to *):
![AfterPrimeNG7](https://user-images.githubusercontent.com/44418498/54358514-f8ed7280-4636-11e9-860b-55782ee39838.png)

**Expected behavior**
PrimeNG themes only affect explicitly declared PrimeNG components/directives/classes.

**What is the motivation / use case for changing the behavior?**
Unbreak the styling of my application.

* **Angular version:** 7.x

* **PrimeNG version:** 7.x

* **Browser:** all

**Comment by KensingtonTech** [comment]
Why not change it to something like this?

```
[class^="ui-"] {
  -moz-box-sizing: border-box;
  -webkit-box-sizing: border-box;
  box-sizing: border-box;
}
```

**Comment by cagataycivici** [comment]
Almost all CSS libraries use border-box as default so it is default in our themes as well.

**Comment by KensingtonTech** [comment]
No one is arguing that you shouldn’t use border-box for PrimeNg. Other libraries don’t globally apply their styles to entire applications!  I’m sorry but that’s absurd.  Please take your fingers out of your ears, apply the border-box just to PrimeNg, and stop messing with global styles. 

And it is extremely rude of you to just close these cases without even hearing your users out.

**Comment by KensingtonTech** [comment]
I even gave you the css to do it. Why would you NOT use it?

**Comment by KensingtonTech** [comment]
@cagataycivici Why are you being so recalcitrant?  Are you even reading the issues?  Reopen the issues that you've appallingly closed summarily, and re-apply your change to just primeng elements, as you have elsewhere.

**Comment by razaqq** [comment]
4 years later and is still @TimUnderhay completely right, this is annoying as hell

**Comment by bogdanblunt** [comment]
@cagataycivici Let's accept the box-sizing style enforcing is unnecessary and let's allow/provide patch versions for all the stable versions.
