### ISSUE TITLE
Calendar TouchUI doesn't open

### ISSUE THREAD

**Issue by 2ne** [primefaces/primeng#7389]
[x] bug report

Bug can be reproduced on PrimeNG calendar demo for TouchUI in Chrome 73 - Windows and Mac
https://www.primefaces.org/primeng/#/calendar

**Current behaviour**
Click on the input to open calendar overlay - The overlay flickers then closes again.

**Expected behaviour**
The overlay should open as it does in any other browser or mode

**Comment by jaikishore08** [comment]
Now it's opening on chrome 73, but it is not appearing on first click. We need to click twice to get it appeared.
