### ISSUE TITLE
Table state not restored correctly

### ISSUE THREAD

**Issue by thatsmeta** [primefaces/primeng#7391]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://www.primefaces.org/primeng/#/table/state

**Current behavior**

When you filter, sort and paginate at the same time, table state is not restored correctly, because the page is always reset to the first page.

**Expected behavior**

Page should be restored correctly. If I was on page 3 before reload, I would like to return to page 3 after reload.

**Minimal reproduction of the problem with instructions**

Go to the link above (PrimeNg showcase). Sort the session storage table by VIN, type "19" into the search field for the column "Year" and paginate to page 3. Reload. Page is reset to page 1.

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
