### ISSUE TITLE
[Feature Request] Support buttons on AccordianTabs

### ISSUE THREAD

**Issue by ChuckIrvine** [primefaces/primeng#7392]
I would find it useful to be able to embed buttons on p-accordianTabs. I didn't see any way to do this. Hopefully, I didn't miss anything.

Attaching a screen shot from Visual Code Studio as an example:

![Screen Shot 2019-03-16 at 11 34 57 AM](https://user-images.githubusercontent.com/657002/54478386-8ec40180-47df-11e9-8654-c8a7eff9a44a.png)

**Comment by cagataycivici** [comment]
AccordionTab headers can accept templates so you can easily implement it on your side.
