### ISSUE TITLE
p-Tree Selection in filtered mode

### ISSUE THREAD

**Issue by MoxxiManagarm** [primefaces/primeng#7397]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Hi,

thank you for the new p-tree filter feature, just in time for my project, I love it. However...

**Current behavior**
While in filtered mode the onNodeSelect Event always contains the root node.

**Expected behavior**
The Event contains the actual selected Node.

Reproduce it here;
https://stackblitz.com/edit/angular-cpkeva
put "child" into filter box and see console always prints root

* **Angular version:** 7.2
* **PrimeNG version:** 7.1
* **Browser:** all
* **Language:** ES5
* **Node (for AoT issues):** v11.10.0

**Comment by MoxxiManagarm** [comment]
I checked the source code and I found the answer. I need to set the key for a node. However, this is not clear within the official docs. Kindly add a note in the filter-section of the p-tree docs. Thank you.

**Comment by BeelineDevelopers** [comment]
Noticed this issue too - for us it makes the filter function somewhat unusable.  What's strange is that it seems to work if you right-click and bring up a custom context menu.  MoxxiManagarm's solution above doesn't seem to be working for us out of the box (without drastic changes).
