### ISSUE TITLE
onFileSelect EventEmitter not returning files

### ISSUE THREAD

**Issue by hidigitech** [primefaces/primeng#7398]
onFileSelect event emitter is returning the variable `files` it should return `this.files`. The EventEmitter is not outputting the files. 

https://github.com/primefaces/primeng/blob/05e28dedfac6c3a11d50e60e4707ddb6b748ad24/src/app/components/fileupload/fileupload.ts#L214

**Comment by rafa-as** [comment]
Hi @hidigitech your fix seems to be incorrect because the onSelect emitter must emit only the new ones and your approach emit all the files.

I think that the solution should be something like:

Before

```typescript
if(!this.multiple) {
    this.files = [];
}

let files = event.dataTransfer ? event.dataTransfer.files : event.target.files;
for(let i = 0; i < files.length; i++) {
    let file = files[i];

    if(!this.isFileSelected(file)){
      if(this.validate(file)) {
          if(this.isImage(file)) {
              file.objectURL = this.sanitizer.bypassSecurityTrustUrl((window.URL.createObjectURL(files[i])));
          }

          this.files.push(files[i]);
      }
    }
}

this.onSelect.emit({originalEvent: event, files: files});
```

After

```typescript
const newFiles = Array.from(event.dataTransfer ? event.dataTransfer.files : event.target.files);
const selectedFiles = [];

newFiles.forEach(file => {
    if(!this.isFileSelected(file) && this.validate(file)){
        if(this.isImage(file)) {
            file.objectURL = this.sanitizer.bypassSecurityTrustUrl((window.URL.createObjectURL(file)));
        }

        selectedFiles.push(file);
    }
})

if(selectedFiles.length > 0) {
    if(!this.multiple) {
        this.files = selectedFiles;
    } else {
        this.files = [...this.files, ...selectedFiles];
    }
    this.onSelect.emit({originalEvent: event, files: selectedFiles});
}
```

**Comment by rafa-as** [comment]
@cagataycivici @mertsincan what do you think?

**Comment by hidigitech** [comment]
> @cagataycivici @mertsincan what do you think?
> 
> If you want, I can do the PR quickly.

I'll close my PR.

**Comment by hidigitech** [comment]
> > @cagataycivici @mertsincan what do you think?
> > If you want, I can do the PR quickly.
> 
> I'll close my PR.

Sorry, I thought you had done the PR. I'll make the changes and update my PR. Thanks @rafa-as

**Comment by rafa-as** [comment]
Thank you @hidigitech

**Comment by cagataycivici** [comment]
We just pass whatever is selected from the event so current behavior looks correct to me.
