### ISSUE TITLE
Dialog width is not responsive

### ISSUE THREAD

**Issue by buddyackerman** [primefaces/primeng#740]
When the dialog has the responsive attribute set to true, it's not responding to screen size differences. If the initial width is not specifically set the dialog defaults to 300px regardless of the content width and never changes size.   If the width is set it stays that width regardless of screen/window size.

**Comment by Azema** [comment]
+1

**Comment by michaelraypace** [comment]
Experiencing same issue

**Comment by buddyackerman** [comment]
I posted this issue on the PrimeNG forum prior to posting the issue here and it's received no attention.  Along with the other issue I posted about the dialog control the dialog is barely usable.  Also, I don't hink these are things that would be hard to get fixed.  In fact some on the PNG forum posted a fix to the manual resize issue that I have to apply every time I update to a new version.

**Comment by tobiasfiechter** [comment]
Yes we are experiencing the same issue!

**Comment by xyz765** [comment]
Same issue, it needs to be fixed

**Comment by cagataycivici** [comment]
1262 changes dialog width to auto, will this help this case where you can now add custom breakpoints;

```
@media screen and (max-width: 40em) {
    .ui-dialog.ui-dialog-responsive {
        width: 90% !important;
    }
}
```

**Comment by stannynuytkens** [comment]
imo _p-dialog_ is a joke, @whoever_is_maintaining_this

**Comment by dhniels** [comment]
Just switched over to p-dialog after using ng-bootstraps modal and im experiencing a whole host of issues, many of which i had to solve after much trial and error with extremely shoddy CSS hacks.  this component needs desperate and immediate attention

**Comment by pkharris** [comment]
This is still an issue.
