### ISSUE TITLE
[Table] Support ChangeDetectionStrategy.OnPush

### ISSUE THREAD

**Issue by earshinov** [primefaces/primeng#7400]
**I'm submitting a ...**
```
[x] bug report
```

**Plunkr Case**

https://stackblitz.com/edit/primeng-table-lags

**Current behavior**

Without `ChangeDetectionStrategy.OnPush` inline editing in tables becomes unbearably laggy even on my fairly powerful computer, let alone mobile devices.

And it is not possible to use `ChangeDetectionStrategy.OnPush`, because apparently it is not supported (for instance, #7370).

**Expected behavior**

Editing in a simple text field should **not** be laggy.

**Minimal reproduction of the problem with instructions**

Repro steps:
1. Open the demo https://stackblitz.com/edit/primeng-table-lags
2. Click any of the cells and start editing, ideally with Chrome DevTools performance profiler running so that you can see the results:

![devtools](https://user-images.githubusercontent.com/52021/54559798-ec1fa480-49d1-11e9-9192-035782449d6c.png)

**What is the motivation / use case for changing the behavior?**

For any data tables, it is **essential** to provide at least tolerable performance for datasets of moderate size (on the demo page, it is 10 columns + 150 rows).

**Environment:**

- Angular 7.2.8
- PrimeNG 7.1.0
- Browser: Google Chrome | 72.0.3626.121 (Official Build) (64-bit) (cohort: Stable)
- Language: TypeScript

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
