### ISSUE TITLE
DropDown cursor within filter jumps to end in IE11

### ISSUE THREAD

**Issue by steigerm** [primefaces/primeng#7401]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Waiting Time: ~8 weeks.

**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://angular-zzwwpv.stackblitz.io

**Current behavior**
IE11 only (works in Chrome):
DropDown with filter="true"
If I enter a filter string, place the cursor in the middle of the string and press "Del": The character is deleted but the cursor jumps to the end of the filter string.

**Expected behavior**
The cursor should stay at the correct position after deleting the character (like it does on Chrome).

**Minimal reproduction of the problem with instructions**
See above

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows 7/10

* **Angular version:** 5.X
7.2.9

* **PrimeNG version:** 5.X
7.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
IE11
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 

* **Node (for AoT issues):** `node --version` =

**Comment by mertsincan** [comment]
I couldn't replicate it. Please see test video;
![dropdown-IE11-test](https://user-images.githubusercontent.com/11868120/54608242-60edef80-4a61-11e9-8d1c-206b24ee86c9.gif)

**Comment by steigerm** [comment]
Thanks for trying.
One difference I can see is the version of IE
I am currently using 
Windows 7 x64
11.0.9600.19266 
11.0.110 (KB4486474)
or
Windows Server 2012 R2
11.0.9600.19204
11.0.100 (KB4470199)

This is an enterprise environment so I can not easily install different versions.

**Comment by steigerm** [comment]
I now found a way to record this problem.
Using 
Windows 7 x64
11.0.9600.19266
11.0.110 (KB4486474)

![cursorjumpstoend](https://user-images.githubusercontent.com/1550467/55407109-bb0cab80-555d-11e9-9326-de8baaa78212.gif)

**Comment by steigerm** [comment]
After installation of IE 
11.0.9600.19301
11.0.115 (KB4489873)
the problem is gone.

Therefore I am closing this issue

**Comment by steigerm** [comment]
Sorry, have to reopen this issue.
Using IE the correct cursor behavior only happens with Windows 10.
Using Windows 7 or 8.1 the cursor jumps to the end of the input field as described

**Comment by steigerm** [comment]
Still the same after upgrade to 
Angular 8.2.0
PrimeNG 8.0.2

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
