### ISSUE TITLE
DataTable single selection mode doesn't fire onRowUnselect when another row is selected.

### ISSUE THREAD

**Issue by ayushman1024** [primefaces/primeng#7403]
DataTable single selection mode doesn't fire onRowUnselect event when another row is selected.

Replication of issue in a single selection mode:

1. row-A is clicked then it got selected , onRowSelect event is fired.
2. Then I re-click this row A then onRowUnselect event is fired which is expected and correct
3. But then if I try to click row A to select it then click on row B then it should fire "onRowUnselect" event same as that in previous step, but it doesn't .

primeNg
"version": "6.1.6"

**Comment by cagataycivici** [comment]
This is expected. onRowUnselect is only called when it is unselected manually.
