### ISSUE TITLE
Add title to TreeNode when mouse on it.

### ISSUE THREAD

**Issue by AliceYangqian** [primefaces/primeng#7408]
Tree nodes display in limited width. The length of the node may exceed the width. Do not want to appear scrollbars in tree layout. Expected: Text exceeds the display ellipsis and displays all text when the mouse hovers over the node.

Angular version: 7.1.0

PrimeNG version: 7.0.5

**Comment by cagataycivici** [comment]
You have control over the markup since TreeNode supports templating so can be done on your side easily.
