### ISSUE TITLE
Missing dependency to @angular/cdk

### ISSUE THREAD

**Issue by krojew** [primefaces/primeng#7410]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
ERROR in ./node_modules/primeng/components/dropdown/dropdown.js
Module not found: Error: Can't resolve '@angular/cdk/scrolling' in '.../node_modules/primeng/components/dropdown'

**Expected behavior**
no error

**Minimal reproduction of the problem with instructions**
Update primeng from 7.0 to 7.1 and try to build your app.

* **Angular version:** 7.2.10

* **PrimeNG version:** 7.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests. You need install angular/cdk module, 
`npm install @angular/cdk --save`
You can look in https://www.primefaces.org/primeng/#/multiselect .

**Comment by krojew** [comment]
This bug shouldn't be closed because:

- I'm not using multiselect, hence I shouldn't be concerned with cdk
- this is a backwards-incompatible change, which breaks semver versioning
- if this is a required dependency, it should be explicitly specified for npm

**Comment by Astrophizz** [comment]
I agree with @krojew mostly for the second and third point. The other issue related to this was closed and has a commit associated with it to move `@angular/cdk` to the peer dependencies, but that commit was rejected by the CI tool and never entered the `master` branch.

**Comment by RenaudF** [comment]
duplicate of #6993
