### ISSUE TITLE
Dialog sizing fails if percentage used in contentStyle

### ISSUE THREAD

**Issue by WFTBruce** [primefaces/primeng#7413]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-e3reb3

**Current behavior**
In above case, click the "Show Dialog" button.  It will show the dialog too tall to fit in the window.  Every alternate window resize event will result in the window displaying the correct size (based on the [contentStyle]="{'max-height':'50%'}" value).

[Note that this was also a problem in primeNG 6, but wasn't as apparent because the initial dialog size was correct.  PrimeNG's addition of an onWindowResize() call in onAnimationStart() for responsive dialogs causes the size to be initially incorrect.]

**Expected behavior**
Dialog size should always be correct, based on the contentStyle with max-height = 50%.

**Minimal reproduction of the problem with instructions**
Open above StackBlitz example and click the "Show Dialog" button.

**What is the motivation / use case for changing the behavior?**
Want to use max-height = % to maximize dialog space in window without overflowing the window.

**Please tell us about your environment:**

* **Angular version:** 
7.2.2

* **PrimeNG version:** 
7.0.5

* **Browser:** 
Chrome, IE

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 3.1.1

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9 which has a new Dialog Impl, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
