### ISSUE TITLE
Tree filter - expand search result

### ISSUE THREAD

**Issue by singara-velan** [primefaces/primeng#7417]
Any way to expand the tree search results

**Comment by AliceYangqian** [comment]
Agree. I hope so too.

**Comment by Torquin** [comment]
That would be great !

**Comment by claudiuconstantin** [comment]
This would be a great improvement to the tree search functionality. Or at least to have an event which can be used to expand all nodes when filtering is on. Did somebody come up with a workaround for this?

**Comment by gs-smuthyam** [comment]
Hi There,

I have a different requirement here on the same topic. Thought you guys would be helpful here.

My use case is I have thousands of nodes to be displayed with max of 5 level nesting. Sometimes the data size goes beyond 50MB(nodes JSON size).

In this case the performance is worst to start with rendering it. 
Also, on search, all the nested nodes are getting expanded by default which I don't want to happen to avoid the damage on search. I tried with the lenient and strict mode but did not see any difference. 

Can you please help me understand on how can I achieve this ? 

1) lazy loading with nested selections retained.
2) Do not expand the child nodes on search

I'm using 7.x version of prime ng

**Comment by gs-smuthyam** [comment]
Hi @mertsincan ,

While this looks a good usability improvement in some case, it would be a bottleneck for tree with larger set of nodes. I think it would be ideal to make it configurable instead of defaulting the value to **true**.

Any thoughts ?

**Comment by johannes-wolf** [comment]
That would be a great feature to have! I think having it optionally is fine.
