### ISSUE TITLE
Lazy loaded modules in RC5 with error as: Type InputText is part of the declarations of 2 modules

### ISSUE THREAD

**Issue by maleet** [primefaces/primeng#742]
Plunker is here: http://plnkr.co/edit/Ji9Pf6kp4CJmDnLJJTkJ?p=preview

Open Crisis Center and you get error in console:
zone.js@0.6.12?main=browser:461 Unhandled Promise rejection: Type InputText is part of the declarations of 2 modules: ContactModule and CrisisModule!

**Comment by maleet** [comment]
Here's lot of talking about similar issue: https://github.com/angular/angular/issues/10646

**Comment by cagataycivici** [comment]
#739 should fix it. Please track there.
