### ISSUE TITLE
Drag p-dialog outside of viewport

### ISSUE THREAD

**Issue by toddsr** [primefaces/primeng#7420]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Issue #5713 fixed being able to drag a dialog outside of the viewport in version 7. But in our case, we require the ability to drag the dialog outside of the viewport which allows users to see/access content easily behind the dialog - especially for non modal dialogs.

We can use minX and minY to allow the dialog to be dragged off the viewport to the left and top by setting those to negative values, but we need the same ability to drag the dialog off the viewport to the right and bottom.

**Expected behavior**
Drag p-dialog outside of the viewport in any direction.

**Please tell us about your environment:**

* **Angular version:** 7.2.7

* **PrimeNG version:** 7.0.5

* **Browser:** [Chrome XX ]

 
* **Language:** [TypeScript 3.2.2]

**Comment by hakim-dc** [comment]
1+

**Comment by Yoranium238** [comment]
I concur with this request.  Those applications that require significant dialog interaction should be able to move those dialogs around to positions that extend beyond the viewport.  I think a valid approach to accommodate this would be to limit this movement to some configurable  boundary restriction where you cannot move the dialog completely out of view.

**Comment by hakim-dc** [comment]
@cagataycivici  Are there any plans to fix this in the incoming release?

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
