### ISSUE TITLE
Pass current files to FileUpload onSelect

### ISSUE THREAD

**Issue by nanihub** [primefaces/primeng#7421]
../fileupload/fileupload.ts

Line:214
 this.onSelect.emit({originalEvent: event, files: files});

should be

this.onSelect.emit({originalEvent: event, files: **this.files**});

**Comment by nanihub** [comment]
any workaround?
@cagataycivici

**Comment by rafa-as** [comment]
Duplicated: https://github.com/primefaces/primeng/issues/7398
