### ISSUE TITLE
feature request: TurboTable - real time update

### ISSUE THREAD

**Issue by ivan-meridianbanc-com** [primefaces/primeng#7425]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
I used TurboTable - Scroll Horizontal and Vertical.
I want to update the table with real time data.
The problem is that the table makes a copy of the data  and I cannot update the row directly.
I have to copy all rows and change the data source.
This forces the table to re-draw and if the table is scrolled it goes at the top or at the bottom (which is the nearest).

**Expected behavior**
Could it be added a behavior to make real time updates to the data?

**What is the motivation / use case for changing the behavior?**
I want to load the data and some columns needs to be refreshed in near real time.

**Please tell us about your environment:**
MacOS, Windows, npm, nginx

* **Angular version:** 7.1.1

* **PrimeNG version:** 7.0.0

* **Browser:**
Crome
 
* **Language:**
TpeScript 3.1.6

* **Node (for AoT issues):** `node --version` =  11.11.0

**Comment by cagataycivici** [comment]
Please use forum for support requests and questions.
