### ISSUE TITLE
<p-growl> sticky attribute is not working as expected

### ISSUE THREAD

**Issue by SvitlanaKozeletska** [primefaces/primeng#7427]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
Growl is not closed automatically. 

The problem appears when a growl with [sticky]="true" is invoked and after that, a growl with [sticky]="false" appears; the second growl is not closed automatically after the default time which was set.

**Expected behavior**
Growl should close automatically after the default time which was set. 

* **Angular version:** 7.X

* **PrimeNG version:** 6.0.0

Thanks!

**Comment by cagataycivici** [comment]
Growl is deprecated, use toast please.
