### ISSUE TITLE
p-table Column  Reorder and  Column Resize doesn't work 

### ISSUE THREAD

**Issue by ymasha** [primefaces/primeng#7428]
I have an issue with data table having Column  Reorder and  Column Resize doesn't work. 
Also i tried enable and disable one of them..    
project that reproduces  the problem 
https://stackblitz.com/edit/angular-ptable?file=src%2Fapp%2Fapp.component.html

**Comment by ymasha** [comment]
my mistake 
  <th *ngFor="let col of columns" pReorderableColumn pResizableColumn >

**Comment by Medmj** [comment]
> my mistake
> 
> >

Hello @ymasha can you tell me how you fixed it ?
