### ISSUE TITLE
TimePicker unusable in Cell Editor

### ISSUE THREAD

**Issue by Rillist** [primefaces/primeng#7429]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/resizable-breaks-calendar-edit

**Current behavior**
On p-table component when resizableColumns is used with pEditableColumn the p-calendar component does not work as expected. Any clicks in the popup cause it to close due to the loss of focus from the table cell. (I think)

**Expected behavior**
The calendar component should work as it does when resizableColumns is not used. Elements within the calendar should be clickable, and the user should be able to select a new date/time.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/resizable-breaks-calendar-edit

1. Click one of the 'time' columns
2. Try to use the spinners inside the calendar to change the time
3. Note how the calendar popup closes on the first click, not allowing you to change all 3 options
4. However, if you try the dropdown it works as expected

**What is the motivation / use case for changing the behavior?**
I have data in a table, with dates and times, and my users want to inline edit.

I have attempted to switch to p-inplace instead of p-cellEditor. While it does resolve this specific issue because inplace does not revert state when the cell is blurred, it introduces a bunch of other issues I have to deal with like toggling state and handling the changes.

In an older version of PrimeNG/Angular (6.1-ish) this used to work without issue.
https://stackblitz.com/edit/resizable-used-to-work

**Please tell us about your environment:**
Windows 10, VS Code

* **Angular version:** 7.1.1

* **PrimeNG version:** 7.1.0

* **Browser:** Chrome 71.0.3578.80
 
* **Language:** TypeScript 3.1.6

* **Node (for AoT issues):** 10.14.1

**Comment by Rillist** [comment]
I see now that in the older version the state never reverts, so once you start editing you will always have a field in edit mode.

I found 2 issues where people were complaining about that https://github.com/primefaces/primeng/issues/5352 and https://github.com/primefaces/primeng/issues/1924

There is even a comment on one of them that explains how fixing the issue would cause the exact issue I am describing with calendar and dropdown. 
https://github.com/primefaces/primeng/issues/5352#issuecomment-395668175

So hopefully someone has a workaround or something.

**Comment by Rillist** [comment]
For now we have implemented a check inside the documentEditListener of our company's primeng fork, per the recommendation in this comment: https://github.com/primefaces/primeng/issues/5352#issuecomment-403472384

I'm checking the event.path array to see if there is an element with 'ui-datepicker' in the classList, and if it's the index before the body node. If it is, then I assume it's appended to the body from the cell editor and do not allow the cell to exit edit mode.

It feels a little hacky to me, I am imagining a scenario where there is another calendar on the same page but not inside the editable cell and the user clicked on it but the table cell remains in edit mode. So I am not going to make a PR, but this "fix" seems to resolve the specific issue we are having and I don't plan to have any other calendars on the page in question. Maybe I am just overthinking it though.

If anyone is interested I added this private method to table.ts
```javascript
private eventPathContainsDatePickerAppendedToBody(event): boolean {
	const findLastIndex = (array, condition) => {
		return array.slice().reverse().findIndex(condition);
	}
	const bodyIndex = event.path.findIndex(p => p.nodeName === 'BODY');
	const datePickerIndex = findLastIndex(event.path, p => p.classList && p.classList.value.indexOf('ui-datepicker') > -1);
	return datePickerIndex > -1 && datePickerIndex === bodyIndex - 1;
}
```

And then I just added this method to the condition in bindDocumentEditListener like this.

```javascript
bindDocumentEditListener() {
	if (!this.documentEditListener) {
		this.documentEditListener = (event) => {
			if (this.editingCell && !this.editingCellClick && this.isEditingCellValid()
				&& !this.eventPathContainsDatePickerAppendedToBody(event)) {
				DomHandler.removeClass(this.editingCell, 'ui-editing-cell');
				this.editingCell = null;
				this.unbindDocumentEditListener();
			}

			this.editingCellClick = false;
		};
		
		document.addEventListener('click', this.documentEditListener);
	}
}
```

It would be better if I could add a custom class or attribute to the appended widgets (like the original comment suggested), and check for that instead, but that would require a bit more effort to figure out how to make the table or editable cell add the class/attribute.

**Comment by iso3000** [comment]
I'm using NgbInputDatepicker with TurboTable and it doesn't appear to matter if the columns are resizable or not- any click on the calendar would force it to close. This works for me:

`  @HostListener('document:click', ['$event'])
  documentClick(event:any) {
    let pathArr:HTMLElement[] = event.path;
    if(pathArr.find(cP => cP.nodeName == "NGB-DATEPICKER")){
      event.stopImmediatePropagation();
    }
  }`

**Comment by botondus** [comment]
There is the same problem with resizable columns as well. The problem is that when you click on something in the calendar the `blur` event of the inline editable cell is triggered and it destroys the input alongside the attached calendar.

**Comment by Rillist** [comment]
I looks like the calendar month changing was fixed per https://github.com/primefaces/primeng/issues/7441

But this did not fix the timepicker, I've updated the original post and my comment with a fix.

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
