### ISSUE TITLE
Accessibility: Screen readers not able to read search results count by global filter

### ISSUE THREAD

**Issue by manidevzen3** [primefaces/primeng#7433]
[x] bug report 

**Current behavior**
Screen reader not able to read search results count after searching a keyword on global filter

**Expected behavior**
Screen reader should able to read the search results count

**What is the motivation / use case for changing the behavior?**
Disabled people who are depend on screen reader should know the number of search results

* **Angular version:** 4.1.3

* **PrimeNG version:** 4.2.1

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
