### ISSUE TITLE
Submenu for SplitButton PopUpMenu

### ISSUE THREAD

**Issue by sgruessinger** [primefaces/primeng#7435]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
SplitButton does not support multiple depth menu-structure.

**Expected behavior**
SplitButton should be able to have submenus.

**What is the motivation / use case for changing the behavior?**
Versatility of the SplitButton. ContextMenu already supports the feature.

**Comment by tommancini** [comment]
I would really appreciate this feature as well

**Comment by cagataycivici** [comment]
You can use TieredMenu with the popup option to have this.

https://primefaces.org/primeng/showcase/#/tieredmenu
