### ISSUE TITLE
dropdown: setting dataKey breaks pre-selection

### ISSUE THREAD

**Issue by ThorstenKunz** [primefaces/primeng#7438]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/angular-gcmpnx

**Current behavior**
In the minimal stackblitz example above the dropdown element LAX should be pre-selected. However it doesn't work and the first element in the list is pre-selected. Now if you remove the "dataKey" attribute from the dropdown element it works as expected.

**Expected behavior**
The dropdown component should be able to use whatever "dataKey" you specify and determin what the pre-selected option is

* **Angular version: 7..2.10

* **PrimeNG version: 7.1.0

* **Browser:** Chrome | Firefox | Edge

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
