### ISSUE TITLE
p-calendar error

### ISSUE THREAD

**Issue by clcrca** [primefaces/primeng#744]
I have angular 2 rc5, and included following:

<script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
<script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ui-timepicker-addon/1.6.1/jquery-ui-timepicker-addon.min.js"></script>

When I try to use p-calendar, I got this error:
zone.js:461 Unhandled Promise rejection: Template parse errors:
Can't bind to 'showIcon' since it isn't a known property of 'p-calendar'.
1. If 'p-calendar' is an Angular component and it has 'showIcon' input, then verify that it is part of this module.
2. If 'p-calendar' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
 ("="col-md-12" ng-form="ddateform">
                                <p-calendar showAnim="slideDown" [ERROR ->][showIcon]="true"></p-calendar>
                            </div>
                        </div>
"): AppComponent@94:65 ; Zone: <root> ; Task: Promise.then ; Value: BaseException {message: "Template parse errors:↵Can't bind to 'showIcon' si…                   </div>
↵"): AppComponent@94:65", stack: "Error: Template parse errors:↵Can't bind to 'showI…calhost/node_modules/zone.js/dist/zone.js:356:38)"}consoleError @ zone.js:461_loop_1 @ zone.js:490drainMicroTaskQueue @ zone.js:494ZoneTask.invoke @ zone.js:426
zone.js:463 Error: Uncaught (in promise): Template parse errors:(…)

**Comment by buddyackerman** [comment]
This is an Angular RC5 issue with minification, check this link [https://github.com/angular/angular/issues/10618](url)

I posted the fix in this forum thread [http://forum.primefaces.org/viewtopic.php?f=35&t=46690](url)

**Comment by Hegde0209** [comment]
@buddyackerman Both of your link gives 404 (Page not found) error can u fix it?

**Comment by cagataycivici** [comment]
Links work for me.
