### ISSUE TITLE
Make scroll panel height responsive

### ISSUE THREAD

**Issue by aspramsh** [primefaces/primeng#7444]
How to make scroll panel height to fill all the remaining part of the div? Actually I am not able to find a way to make it responsive.

**Comment by leseb83** [comment]
Hi,
The only way I found is to set the height like this:
<p-table  [scrollHeight]="'calc(100vh - 310px)'"

Replace the 310 pixels with the appropriate value.

**Comment by Fridthjof** [comment]
Any success with this issues @aspramsh?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
