### ISSUE TITLE
Turbo table state custom storage

### ISSUE THREAD

**Issue by jtkDvlp** [primefaces/primeng#7446]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://www.primefaces.org/primeng/#/table/state

**Current behavior**
Stateful table allows keeping the state such as page, sort and filtering either at local storage or session storage so that when the page is visited again, table would render the data using its last settings.

**Expected behavior**
Stateful table allows keeping the state such as page, sort and filtering either at local storage, session storage **or own storage via given function or interface** so that when the page is visited again, table would render the data using its last settings.

**What is the motivation / use case for changing the behavior?**
For our project we need to keep the state in database via backend.

**Comment by cagataycivici** [comment]
Duplicate

https://github.com/primefaces/primeng/issues/7320
