### ISSUE TITLE
p-dropdown: emptyFilterMessage does not work with optionLabel

### ISSUE THREAD

**Issue by manasipandya7** [primefaces/primeng#7448]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-na45lx

**Current behavior**
If optionLabel is provided, default message or emptyFilterMessage does not work.

**Expected behavior**
Default message or emptyFilterMessage should work in any case.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/github-na45lx

**Please tell us about your environment:**
Operating system: Linux(Ubuntu 16)
IDE: Sublime Text Editor

* **Angular version:** 7.2.9

* **PrimeNG version:** 7.1.0

* **Browser:** [Chrome]
 
* **Language:** [TypeScript 3.2]

* **Node (for AoT issues):** `node --version` = v10.6.0

**Comment by beatrizCi** [comment]
no fix for this bug?
