### ISSUE TITLE
p-dropdown: in iOS is shown empty native dropdown

### ISSUE THREAD

**Issue by nilpaco** [primefaces/primeng#7452]
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://www.primefaces.org/primeng/#/dropdown

**Current behavior**
When opening the dropdown in a iOS device (iPhone X) the native select box is shown without any option. 

**Expected behavior**
When opening the dropdown in a iOS device (iPhone X) the native select box shouldn't be shown in any case.

**Minimal reproduction of the problem with instructions**
1. Go to https://www.primefaces.org/primeng/#/dropdown
2. Open the dropdown in an iPhone.
3. Check in the bottom bar the native list is shown without options.

**What is the motivation / use case for changing the behavior?**
Doesn't look right to have a native element in the bottom not being used in any case.

**Please tell us about your environment:**

* **Angular version:** 7.2.0

* **PrimeNG version:** 7.1.0

* **Browser:** iOS 12.1.4 Safari
 
* **Language:** TypeScript 3.2

* **Node (for AoT issues):** `node --version` = v10.14.2

**Comment by Txuso** [comment]
Same here!

**Comment by davidolivefarga** [comment]
I'm experiencing the same issue...

**Comment by rafa-as** [comment]
@nilpaco can you provide some graphic resource to see the error(like gif, video, images..)? Maybe other people can push for this issue if can understand it well.

Thank you

**Comment by JacobSiegle** [comment]
It's a real pain for me to work with iOS (emulator in emulator). Hopefully someone can PR or a maintainer has a device.

![ios1](https://user-images.githubusercontent.com/5766272/55334590-2885e280-545f-11e9-9d9a-41f3ed924819.png)
![ios2](https://user-images.githubusercontent.com/5766272/55334597-2b80d300-545f-11e9-8d4e-c06a71d0dece.png)

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
