### ISSUE TITLE
TurboTable - clicking on the resize icon sends negative delta on column resize subscription

### ISSUE THREAD

**Issue by stingher** [primefaces/primeng#7461]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-auem9m

**Current behavior**
The column resize event sends negative delta for clicking on the resize icon, without performing the actual resize.

**Expected behavior**
The column resize event SHOULD NOT send negative delta for clicking on the resize icon, without performing the actual resize. In case there was no drag operation performed, delta should be **zero**. Or at least there should be a way to differentiate between click and a negative resize. 

**Minimal reproduction of the problem with instructions**
1. Move the cursor to any column header of the test case as if you were to resize it
2. When the cursor changes to double arrow just click the mouse button, without drag
3. See received delta value for onColResize event listener.

**What is the motivation / use case for changing the behavior?**
Clicking on the resize icon sends same event as a resize to a width smaller then minimum. There's no possibility to make the difference between the two in case we want to customize current behavior. We reached to this issue trying to achieve the behavior which was before v7.1.0, when resizing to a very small width to set the minimum possible, and not to ignore the resize, like it happens now.

**Please tell us about your environment:**
Windows 10, VSCode

* **Angular version:** 7.X

* **PrimeNG version:** 7.1.0

* **Node (for AoT issues):** `node --version` =   10.15.3

**Comment by bartha-adam** [comment]
We're seeing the same behavior.

**Comment by conor-mac-aoidh** [comment]
Also seeing this issue using `primeng@8.0.4`

**Comment by conor-mac-aoidh** [comment]
I am using resize expand mode. I was able to work around the issue by adding the following logic to my resize event handler:

```javascript
let resizeHelper = document.querySelector('.ui-column-resizer-helper');
if (resizeHelper && resizeHelper.offsetLeft === 0) {
  return;
}
```
