### ISSUE TITLE
primeng with angular2 rc5 "(SystemJS) Unexpected token <

### ISSUE THREAD

**Issue by ovione** [primefaces/primeng#747]
When using the latest versions of "primeng" = "^1.0.0-beta.12" and "primeui": "^4.1.14" with "angularjs 2" = "2.0.0-rc.5"
Could the reason of the error be because this latest version of primeng doesnt work yet with the latest version of angulr2 rc5 ?

I receive the following error:

"(SystemJS) Unexpected token <
    SyntaxError: Unexpected token <
        at Object.eval (http://localhost:3000/node_modules/primeng/components/dropdown/dropdown.js:14:15)
        at eval (http://localhost:3000/node_modules/primeng/components/dropdown/dropdown.js:314:4)
        at eval (http://localhost:3000/node_modules/primeng/components/dropdown/dropdown.js:315:3)
    Evaluating http://localhost:3000/node_modules/@angular/forms
    Evaluating http://localhost:3000/node_modules/primeng/components/dropdown/dropdown.js
    Evaluating http://localhost:3000/src/tmp/app/components/common/i18n/ng2-translate-change-language.component.js
    Evaluating http://localhost:3000/src/tmp/app/components/app.component.js
    Evaluating http://localhost:3000/src/tmp/app/main.js
    Error loading http://localhost:3000/src/tmp/app/main.js"

My package.json dependencies are:

"dependencies": {
    "@angular/common": "2.0.0-rc.5",
    "@angular/compiler": "2.0.0-rc.5",
    "@angular/core": "2.0.0-rc.5",
    "@angular/forms": "0.3.0",
    "@angular/http": "2.0.0-rc.5",
    "@angular/platform-browser": "2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "2.0.0-rc.5",
    "@angular/router": "3.0.0-rc.1",
    "@angular/router-deprecated": "2.0.0-rc.2",
    "@angular/upgrade": "2.0.0-rc.5",
    "angular2-in-memory-web-api": "0.0.15",
    "angular2-jwt": "0.1.18",
    "bootstrap": "3.3.6",
    "bootstrap-sass": "^3.3.6",
    "core-js": "2.4.1",
    "es6-shim": "0.35.1",
    "font-awesome": "^4.6.1",
    "font-awesome-animation": "0.0.8",
    "jquery": "^2.2.3",
    "lodash": "^4.13.1",
    "moment": "^2.13.0",
    "ng2-translate": "2.4.1",
    "primeng": "^1.0.0-beta.12",
    "primeui": "^4.1.14",
    "reflect-metadata": "0.1.8",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "0.19.36",
    "zone.js": "0.6.14"
  },

**Comment by cagataycivici** [comment]
Please check with beta13 monday which officially supports RC5.

**Comment by lluisnieto** [comment]
Got Beta13, and still not working.

**Comment by garethlewis** [comment]
Have you updated you main.ts or wherever you define the main entry point for your angular application?  This has changed significantly with RC.5.  If you follow the example in the showcase Github page, you should be able to adapt your app in a short period of time.  It took me about 30 minutes to alter everything.

**Comment by ovione** [comment]
hi now everything is working
Here are the dependencies from package.json

```
    "@angular/common": "2.0.0-rc.5",
    "@angular/compiler": "2.0.0-rc.5",
    "@angular/core": "2.0.0-rc.5",
    "@angular/forms": "0.3.0",
    "@angular/http": "2.0.0-rc.5",
    "@angular/platform-browser": "2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "2.0.0-rc.5",
    "@angular/upgrade": "2.0.0-rc.5",
    "angular2-in-memory-web-api": "0.0.15",
    "@angular/router": "3.0.0-rc.1",
    "angular2-jwt": "0.1.15",
    "@ngstarter/systemjs-extension": "1.0.0-rc.4",
    "ng2-translate": "2.4.2",
    "bootstrap": "^3.3.6",
    "bootstrap-sass": "3.3.6",
    "font-awesome": "4.6.3",
    "font-awesome-animation": "0.0.8",
    "lodash": "4.15.0",
    "moment": "2.14.1",
    "primeng": "^1.0.0-beta.13",
    "primeui": "^4.1.15",
    "reflect-metadata": "^0.1.8",
    "core-js": "^2.4.1",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "^0.19.36",
    "zone.js": "^0.6.12"

now it works ike a sharm

cheers


```

**Comment by cagataycivici** [comment]
Glad to hear.
