### ISSUE TITLE
 PanelMenu is not closing panelmenu-header one after another.

### ISSUE THREAD

**Issue by kdbusiness90** [primefaces/primeng#7474]
**Current behavior**

**All panelmenu-headers are opened**
![panelmenu](https://user-images.githubusercontent.com/7038414/55293609-dbc9e980-5415-11e9-8a8a-6bf2b275aabb.png)

**Expected behavior**

**panelmenu-headers should be colsed one after another.**
![PrimeNGpanel](https://user-images.githubusercontent.com/7038414/55293630-1a5fa400-5416-11e9-9eea-bb5db72b682a.png)

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 7.1.0

* **PrimeNG version:** 7.1.0

* **Browser:** [Chrome XX ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =  v11.4.0

**Comment by JacobSiegle** [comment]
Set [multiple]="false"
