### ISSUE TITLE
TabMenu with routerLink issue

### ISSUE THREAD

**Issue by DetectiveBox** [primefaces/primeng#7475]
When the TabMenu is used with routerLink and link to another page(not active home page), refresh page will reset tab buttons' style but not home button style( home button and current button are both active style ).

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
