### ISSUE TITLE
Dialog can't be resized/dragged outside the viewport

### ISSUE THREAD

**Issue by hakim-dc** [primefaces/primeng#7476]
this issue is basically the original behavior of dialog before the modification that has been done in this issue #5713.

**I'm submitting a ...**
```
[ ] bug report
[X] feature request
[ ] support request
```

**What is the motivation / use case for changing the behavior?**
To make resizing and dragging dialogs outside the viewport optional.

**Please tell us about your environment:**
Operating system: ubuntu
IDE: Microsoft Visual Studio
Package manager: NPM

- **Angular version:** 7.2.11

- **PrimeNG version :** 7.1.0

- **Browser:** All

- **Language:** TypeScript 3.3.4

**Comment by JacobSiegle** [comment]
Please don't duplicate issues - #7420

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
