### ISSUE TITLE
p-dropdown: Using optionLabel, 'options' does not get updated when pushing elements

### ISSUE THREAD

**Issue by manasipandya7** [primefaces/primeng#7477]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/angular-oekcmz

**Current behavior**
If optionLabel is provided, "options" does not get updated when we push another element.

**Expected behavior**
"options" should be updated whenever an element is pushed in it, regardless of optionLabel.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/angular-oekcmz

**Please tell us about your environment:**
Operating system: Linux(Ubuntu 16)

* **Angular version:** 7.2.9

* **PrimeNG version:** 7.1.0

* **Browser:** [Chrome]
 
* **Language:** [TypeScript 3.2]

* **Node (for AoT issues):** `node --version` =  v10.6.0

**Comment by JacobSiegle** [comment]
You're supposed to do the following after push - 
`this.options = [...this.options];`

When optionsLabel is set it calls generateSelectItems which is causing the component to update (which has negative perf) on its own.

**Comment by manasipandya7** [comment]
Shouldn't "options" be updated as soon as changes are detected? However, we cannot always depend on re-assigning!
 Well, I will use this workaround and you can consider the issue to be closed if you say so.

**Comment by JacobSiegle** [comment]
No I believe the reason is because if it worked that way each time you pushed onto options it would trigger change detection. This way you can push 1k items and then trigger change detection only once. When using optionsLabel the component is doing some of the work for you, which is nice when the options are not changing in mass. You will see this same pattern used in other components in PrimeNG like turbo table.

**Comment by manasipandya7** [comment]
Okay. Thank you!!
