### ISSUE TITLE
PrimeNg Menu 

### ISSUE THREAD

**Issue by GhEllie** [primefaces/primeng#748]
Hi ,

I am using PrimeNg beta7 and I want to use Menu in my project.

I have an error : 
EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in ./ContextMenu class ContextMenu - inline template:3:12
ORIGINAL EXCEPTION: No provider for Router!

I am using other controls such as Multiselect, DataTable, Calendar ,... but I have  this error only with Menu 

Could you please guide me If you have any idea

**Comment by dvarnai** [comment]
getting the same, any fix?

**Comment by Gvin** [comment]
You should add `RouterModule.forRoot([])` in your module imports.

**Comment by cagataycivici** [comment]
Menu components require a Router.
