### ISSUE TITLE
Maximizable dialog container size.

### ISSUE THREAD

**Issue by ipuiu** [primefaces/primeng#7486]
**I'm submitting a ...**

```
[x] feature request
```

**Current behavior**
There is no way of setting different sizes (ex: height) for a dialog container depending on dialog maximized state.

There is a `ui-dialog-maximized` class added to the dialog when it is maximized but using that affects the not maximized state since the dialog in the maximize function first adds the `ui-dialog-maximized` class and only after computes the pre maximized height.

**Expected behavior**
There should be a way to set a custom height for the content (ex: 600px) when the dialog is not maximized and a height of 100% when it is maximized.

**Possible solution**
The dialog should first compute the pre maximized height based on container size and at the end add the `ui-dialog-maximized` class. This way we can set via CSS two different container sizes using the  `ui-dialog-maximized` class.

**What is the motivation / use case for changing the behavior?**
Im trying to use a component inside the modal that needs it's parent size specified.

**Comment by JacobSiegle** [comment]
Just to be sure I understand the issue correctly, you're saying if you set something like `[contentStyle]="{'max-height':'200px'}"` on a dialog it messes up the maximized view?

Normal - 
![image](https://user-images.githubusercontent.com/5766272/55408589-f25f6600-5525-11e9-85c8-a13b334aa3f7.png)

Max - 
![image](https://user-images.githubusercontent.com/5766272/55408621-030fdc00-5526-11e9-8f78-e16f52974fc1.png)

**Comment by ipuiu** [comment]
Yes, you can put the issue that way too.

Basically there is no way on setting a modal container height without messing the maximized version.
My fix would allow the following to work:

HTML:

<p-dialog [(visible)]="display">
    <div class="wrapper">
      Content
    </div>
    <p-footer>
        //buttons
    </p-footer>
</p-dialog>

CSS:

p-dialog  .wrapper {
    height: 600px;
}

p-dialog.ui-dialog-maximized .wrapper {
  height: 100%;
}



Sent from Mail for Windows 10

**Comment by ipuiu** [comment]
Basically there is no way on setting a modal container height without messing the maximized version.
My fix would allow the following to work:

HTML:
`<p-dialog [(visible)]="display">
    <div class="wrapper">
      Content
    </div>
    <p-footer>
        //buttons
    </p-footer>
</p-dialog>`

CSS:
`p-dialog  .wrapper {
    height: 600px;
}
p-dialog.ui-dialog-maximized .wrapper {
  height: 100%;
}`

**Comment by JacobSiegle** [comment]
Yep sorry I overlooked you had a PR so I deleted my comment, the PR cleared it up.
