### ISSUE TITLE
In IE 11 ,P-Calendar making form dirty when typing into text box even though readonlyinput attribute is  true  

### ISSUE THREAD

**Issue by sarath28pk** [primefaces/primeng#7489]
I am using Primeng 7 and ANGULAR 7. and Internet explorer 11
I have mentioned the readonly attribute as readonlyInput attribute as true.. 
but still my form is getting dirty if I manually type something in the text box.
the issue is with IE only.. working fine in all other 
and  blinking  icon is showing in IE only.

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
