### ISSUE TITLE
onPush detection for TreeTable component

### ISSUE THREAD

**Issue by boryskryvous** [primefaces/primeng#7490]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
There is to much ngFor calls, when where is no changes for `pTreeTableBody`

**Expected behavior**
ngFor should run only when changes detected

**Minimal reproduction of the problem with instructions**
To reproduce and also to analys perfomence of treetable just add this function into your component:
```
trackByFn(index, item) {
    console.log(`${index}`, item);
    return item.node.data.id; 
  }
```
and add this function into your template 

```
<p-treeTable
  #treeGrid
  class="tree-table flexcolumn"
  [value]="data"
  [columns]="columns"
  (onNodeCollapse)="collapsedRow($event)"
  (onNodeExpand)="expandedRow($event)"
  (onEditCancel)="returnFocus()"
  (onEditComplete)="returnFocus()"
  [selection]="currentRowNode"
  [scrollable]="true"
  scrollHeight="100%"
  [resizableColumns]="true"
  columnResizeMode="expand"
  dataKey="id"
  [rowTrackBy]="trackByFn">
```

**What is the motivation / use case for changing the behavior?**
I was working on data presentation into primeng treetable.  Because it was a lot of data i have had a bad perfomance and to solve it i'v added onPush detection to `pTreeTableBody` component. And now i have better perfomance with cell and row selection.
Given code just to be needed to add into treetable.ts file:
```
@Component({
    selector: '[pTreeTableBody]',
    template: `
        <ng-template ngFor let-serializedNode let-rowIndex="index" [ngForOf]="tt.serializedValue" [ngForTrackBy]="tt.rowTrackBy">
            <ng-container *ngIf="serializedNode.visible">
                <ng-container *ngTemplateOutlet="template; context: {$implicit: serializedNode, node: serializedNode.node, rowData: serializedNode.node.data, columns: columns}"></ng-container>
            </ng-container>
        </ng-template>
        <ng-container *ngIf="tt.isEmpty()">
            <ng-container *ngTemplateOutlet="tt.emptyMessageTemplate; context: {$implicit: columns}"></ng-container>
        </ng-container>
    `,
    changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TTBody implements OnDestroy {

    @Input("pTreeTableBody") columns: any[];

    @Input("pTreeTableBodyTemplate") template: TemplateRef<any>;

    private _uiUpdateSource: Subscription;

    constructor(
        public tt: TreeTable,
        private _cdr: ChangeDetectorRef,
     ) {
        this._cdr.detach();
        this._uiUpdateSource = this.tt.tableService.uiUpdateSource$.subscribe(() => this._cdr.detectChanges());
     }
     ngOnDestroy() {
         this._uiUpdateSource.unsubscribe();
     }
}
```

**Please tell us about your environment:**

macOs Mojave Version  10.14.3, VScode Version 1.32.3 
* **Angular version:** 7.1.0

* **PrimeNG version:** 7.1.1

* **Browser:** Chrome Version 73.0.3683.86 (Official Build) (64-bit)

 
* **Language:** TypeScript 3.3.3

* **Node (for AoT issues):** `node --version` = v10.15.0

**Comment by kayvanbree** [comment]
I'm in the team of @boryskryvous. Could the PrimeNG team maybe tell something about On Push change detection and PrimeNG treeTable? Would this be something worth implementing for PrimeNG?

(@boryskryvous update your formatting man!)

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
