### ISSUE TITLE
onNodeSelect emits root element after filtering.

### ISSUE THREAD

**Issue by DivneetS** [primefaces/primeng#7491]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
I have a PrimeNG tree component which works on observables. The root Node is an observable and the subsequent child nodes are also observables. The Data is loaded lazily. And since observables are used, it renders changes, thanks to Angular. I was trying out the Filter property in the PrimeNG tree, and I came across a case where, if the filtered item is found, clicking it would take the user to the root element in the tree. What i mean to say is that the (onNodeExpand) event provides an event in which the node to be expanded is always the root element in the tree.

**Expected behavior**
Ideally, if the filtered item is found, clicking it should take the user to the selecdted element in the tree. The (onNodeExpand) event should provide an event in which the node to be expanded is always the selected element in the tree and not the root element.

Create a PrmeNg Tree, setup a filter, associate with each element a onNodeExpand event and log the selected element after filtering.

**Please tell us about your environment:**
Operating system--> Windows 10,
IDE--> VSCode,
package manager--> yarn

Angular version: 7
PrimeNG version: 7.1.0-rc.1

Browser:** Chrome 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by Windowsz** [comment]
+1

**Comment by Windowsz** [comment]
add key to treedata and this useful

**Comment by lugipfupf** [comment]
Confirmed. The documentation has an inconspicuous link to issue #7237 . Problem solved for me.

**Comment by mertsincan** [comment]
I've added a description under 'Filtering' section on Tree doc.

Best Regards,
