### ISSUE TITLE
Overlay programmatically

### ISSUE THREAD

**Issue by DivyaArora-24** [primefaces/primeng#7492]
Is there a way to show an overlay at a dynamic position programmatically.
For ex: If we want to show an overlay when the user clicks on a map pin. If we get the click event of the map pin and tries to use "
 this.op1.toggle(featureEvent);"
or
" this.op1.show(featureEvent, featureEvent.target);"
An error is displayed in the console : 
OverlayPanel.html:2 ERROR TypeError: target.getBoundingClientRect is not a function
    at Function.push../node_modules/primeng/components/dom/domhandler.js.DomHandler.absolutePosition (domhandler.js:107)

**Comment by JacobSiegle** [comment]
Can you provide a stack-blitz?

**Comment by buseodaci** [comment]
+1

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template

**Comment by Somnathp10** [comment]
op2.show($event,i.target) add this one and [appendTo]="'body'" position issue fixed
