### ISSUE TITLE
[Parchment] Cannot insert block into block with p-editor in IE 11 when dragging text

### ISSUE THREAD

**Issue by jepzen** [primefaces/primeng#7494]
Found this error and able to reproduce it in the demo here:

https://www.primefaces.org/primeng/#/editor

Im using Internet Explorer 11

Steps to reproduce:
1 . Write to paragraphs and mark the first one as bold
2 . Writhe a another paragraph and mark it, pull it into the first one 

Or just write a lot of text and drag them around into other blocks

"[Parchment] Cannot insert block into block" in the console

And sometimes it brakes the bold buttons after

**Comment by JacobSiegle** [comment]
This sounds like a bug with quill not primeng but correct me if i'm wrong. You should report the bug here - https://github.com/quilljs/quill

**Comment by jepzen** [comment]
You are right. Thanks.
