### ISSUE TITLE
Customize p-dropdown and p-multiSelect selected, search and closed icon

### ISSUE THREAD

**Issue by lTyl** [primefaces/primeng#7495]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
p-multiSelect and p-dropdown have a hard-coded reliance on PrimeIcons. This is strange because both of those components provide the dropdownIcon input to customize the icon for the dropdown arrow, yet no such customization exists for the pi-search (Filter icon), pi-check (Selected icon) or pi-times (Close icon).

https://github.com/primefaces/primeng/blob/master/src/app/components/multiselect/multiselect.ts#L101

**Expected behavior**
So I propose that an input is introduced to allow the customization of the selected, search and close icons:
selectedIcon: default to "pi pi-check"
closeIcon: default to "pi pi-times"
searchIcon: default to "pi pi-search"

This will then allow you to choose the exact icon you wish to use for both dropdowns:
<p-dropdown selectedIcon="fa fa-check" closeIcon="fa fa-close" [options]="blahblah"></p-dropdown>

**What is the motivation / use case for changing the behavior?**
We can already customize the dropdown icon via the dropdownIcon input, yet we lack the same flexibility if we want to change the Search, Selected or close icons. This proposal aims to add additional flexibility to these two components.

* **Browser:** All.
 
* **Language:** All

**Comment by cagataycivici** [comment]
Icons can be overriden with css so you can override them with font awesome easily.

**Comment by lTyl** [comment]
The problem here is not overriding the icons but rather the inconsistency of the icons that you allow to be changed via a component input.

`p-multiSelect` and `p-dropdown` support an input `dropdownIcon` where you can customize the icon without doing CSS overrides. Why do you only allow this for this icon and not the other three I mentioned in the issue text?

The API should be consistent IMO.
