### ISSUE TITLE
P-FileUpload disabled property doesn't disable upload button

### ISSUE THREAD

**Issue by esbakker** [primefaces/primeng#7497]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-duhmqp

**Current behavior**
Setting the disabled property on the p-fileupload element doesn't disable the upload button, it only disables the select button. 
According to the documentation the disabled property 

> Disables the upload functionality.

but it only disables the select files functionality

This enables users to click the upload button multiple times, while the upload is still in progress.

**Expected behavior**
The upload button is disabled when disabled is true.

**What is the motivation / use case for changing the behavior?**
We want to prevent users from uploading the same fileset multiple times. We currently use a workaround were we hide the upload button using the showUploadButton property.

**Please tell us about your environment:**

* **Angular version:** 
7.2

* **PrimeNG version:** 
7.1.0

* **Browser:** 
Chrome
 
* **Language:** 
TypeScript 3.2

**Comment by runderworld** [comment]
#7753 is a duplicate of this.

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
