### ISSUE TITLE
DataTable with globalFilter; onLazyLoad event.filters has wrong value when filter is empty

### ISSUE THREAD

**Issue by gatapia** [primefaces/primeng#750]
A template with the following:

```
<input #globalfilter type="text" pInputText>    
<p-dataTable [value]="entities" 
      [lazy]="true" (onLazyLoad)="refresh($event)"
      [globalFilter]="globalfilter"
      #table>
```

If you enter something in the global filter the refresh methods event.filters contains the correct value entered.  However, if you clear the global filter input field then the refresh method gets called with the incorrect value (it has the last value not an empty string as expected).

Example:
Type "123" in the global filter.
refresh method receives event with `e.filters.global.value === '123'`

Now type "" in the global filter:
refresh method receives event with `e.filters.global.value === '123'`

This is obviously wrong, it should receive `e.filters.global.value === ''`

**Comment by cagataycivici** [comment]
Shoud be fixed in recent releases, please drop a comment if issue still persists and we may reopen.
