### ISSUE TITLE
New Component: LinkButton

### ISSUE THREAD

**Issue by smitpsanghavi** [primefaces/primeng#7508]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
For p-button, we have to provide an onClick event on which change window.href.location so that the user can navigate to a link.

**Expected behavior**
Provide a Component LinkButton (like PrimeFaces) so that a hyperlink can be styled as a button.

**What is the motivation / use case for changing the behavior?**
Reduces the instances of p-button components in the code

**Comment by cagataycivici** [comment]
This can be done via;

```xml
<a pButton label="Click" [routerLink]="['/table']"></a>
```

**Comment by ProfEibe** [comment]
I think this would be something great for the showcase/documention. I searched for it a few days.

**Comment by nicolasnevraumont** [comment]
This solution won't apply styles based on pseudo-class :enabled

Ex.:
.p-button.p-button-text:enabled:hover {
  background: rgba(0, 122, 217, 0.04);
  color: #007ad9;
  border-color: transparent;
}

**Comment by Gykonik** [comment]
Couldn't get it to work either because of the `enabled` selector - would really be interested in a solution!
