### ISSUE TITLE
When focus changed for filter using TAB button in horizontal scrollable turbotable, header is scrolling, not body.

### ISSUE THREAD

**Issue by shaileshyadav24** [primefaces/primeng#7509]
![Screenshot 2019-04-05 at 12 24 45 PM](https://user-images.githubusercontent.com/39512705/55609757-1f6a7d80-579f-11e9-80c2-d7ccf1760d0e.png)

**Current behavior**
Only header is scrolling when focus is changing using TAB button.

**Expected behavior**
Body should scroll along with header

* **Angular version:** 5.X
6.X
* **PrimeNG version:** 5.X
6.X
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by mertsincan** [comment]
Please try it with latest version. https://github.com/primefaces/primeng/issues/7375
