### ISSUE TITLE
closeIcon property not working on Dialog

### ISSUE THREAD

**Issue by ZackAfro** [primefaces/primeng#7510]
[X] bug report => Search GitHub for a similar issue or PR before submitting

**Current behavior**
Currently the closeIcon attribute on the Dialog component does not change the icon on the dialog.

**Expected behavior**
Change the Dialog closeIcon to the icon specified

* **Angular version:** 7.1

* **PrimeNG version:** 7.1

**Comment by DanielTianDan** [comment]
@ZackAfro , has the issue been fixed ?

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
