### ISSUE TITLE
Bugs in TreeTable

### ISSUE THREAD

**Issue by ol2ka** [primefaces/primeng#7511]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/github/ol2ka/primeng-issues

**Current behavior**
1. Toggle all (<p-treeTableHeaderCheckbox></p-treeTableHeaderCheckbox>) doesn't work if p-treeTable  dataKey property is used (e.g. <p-treeTable dataKey="name"). 
The root node is not selected in this case and nothing happens if I click second time.

2. Custom sorting of tree table doesn't seem to work at all. I just copied the sort function from the example in the documentation, and nothing happens when I try to sort.

**Expected behavior**
Works as designed.

**Minimal reproduction of the problem with instructions**
1. Just use "dataKey" property for the p-treeTable and try to use p-treeTableHeaderCheckbox
2. (sortFunction)="customSort($event)" [customSort]="true"
customSort(event: SortEvent) {
  	console.log('event', event)
        //event.data = Data to sort
        //event.mode = 'single' or 'multiple' sort mode
        //event.field = Sort field in single sort
        //event.order = Sort order in single sort
        //event.multiSortMeta = SortMeta array in multiple sort

        event.data.sort((data1, data2) => {
            let value1 = data1[event.field];
            let value2 = data2[event.field];
            let result = null;

            if (value1 == null && value2 != null)
                result = -1;
            else if (value1 != null && value2 == null)
                result = 1;
            else if (value1 == null && value2 == null)
                result = 0;
            else if (typeof value1 === 'string' && typeof value2 === 'string')
                result = value1.localeCompare(value2);
            else
                result = (value1 < value2) ? -1 : (value1 > value2) ? 1 : 0;

            return (event.order * result);
        });
        
	}

* **Angular version:** 7.1.1
* **PrimeNG version:** 7.1.0
* **Browser:** [all | Chrome | Firefox |Safari ]

**Comment by dregos** [comment]
I have a similar problem. Treetable customSort property does not bind. 

> Can't bind to 'customSort' since it isn't a known property of 'ng-template'.

Angular version : 8.0.1
PrimeNG version: 8.0.2

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Comment by nerg4l** [comment]
At my company we are using version 7.1.3 of PrimeNG. With some logging I could figure out that `data1` and `data2` are objects with the following structure:

```
{
  data: {/* row object here */},
  children: [],
  expanded: true,
}
```

Which means, instead of `data1[event.field]` you have to use `data1.data[event.field]`.
