### ISSUE TITLE
RTL support for InputGroup

### ISSUE THREAD

**Issue by afshin-z** [primefaces/primeng#7513]
[x] bug report
[x] feature request
[ ] support request

**Plunkr Case**
https://github-frrsth.stackblitz.io

**Current behavior**
styles like border and border-radius are only valid for LTR

**Expected behavior**
For example in RTL the right border of input should be empty (0) instead of left border.

**Minimal reproduction of the problem with instructions**
just put Input Groups in a container with `class="ui-rtl"` and `dir="rtl"`.

**What is the motivation / use case for changing the behavior?**
RTL languages can also benefit from Input Groups.

* **Angular version:** 7

* **PrimeNG version:** 7

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
