### ISSUE TITLE
Mouse up closing dropdown

### ISSUE THREAD

**Issue by JacobSiegle** [primefaces/primeng#7515]
When a user highlights the text in a dropdown filter and they highlight off of the dropdown (imagine a swipe to highlight it all quickly) it will close. It would be ideal if mouse up on dropdown would keep it open.

1) https://www.primefaces.org/primeng/#/dropdown
2) Open dropdown with filter
3) Type in text
4) Highlight text and go off of dropdown
5) Release click.
6) Dropdown closes.

![image](https://user-images.githubusercontent.com/5766272/55645524-72900080-579e-11e9-9a2a-3d5f45f62deb.png)

**Comment by markleppke** [comment]
@JacobSiegle was this issue fixed, or was it an issue that was chosen not to fix?
