### ISSUE TITLE
PrimeNG components do not mark DOM events handled

### ISSUE THREAD

**Issue by earshinov** [primefaces/primeng#7523]
**I'm submitting a ...**
```
[x] bug report
```

**Plunkr Case**

https://stackblitz.com/edit/primeng-event-preventdefault

**Current behavior**

Let's take the [dropdown](https://www.primefaces.org/primeng/#/dropdown) control and the Esc key as an example. When a dropdown control has its dropdown list open, it handles the Esc key, closing the dropdown list. When doing so, the control does not leave any information on the event object that the event has been handled.

**Expected behavior**

I would expect the dropdown control to call `event.preventDefault()` in order to:
- ~Cancel the built-in behavior of the browser~ (irrelevant for the dropdown+Esc example)
- Let other event handlers, which might be present on the page, know that the event has been handled

I do not insist on `preventDefault` / `stopPropagation` / `stopImmediatePropagation` etc. Perhaps, PrimeNG developers would find a more approproate implementation. What I need is a way to know if a PrimeNG component has handled the given event or not. 

**Minimal reproduction of the problem with instructions**

1. Open the demo page: https://stackblitz.com/edit/primeng-event-preventdefault
2. In the dropdown control, open the dropdown list by pressing the ▼
3. Press Esc. The dropdown list closes **and** the page prints 'Esc was pressed', indicating that a global Esc handler installed on the page has caught an event and acted upon it.

**What is the motivation / use case for changing the behavior?**

Suppose I have a [data table](https://www.primefaces.org/primeng/#/table) with row editing enabled. One of controls I employ for editing is a dropdown.

I would like to install a `@HostListener` to cancel row editing when the user presses Esc. Of course, I do not want this behavior to be triggered when the user uses Esc to close the dropdown list. However, when the dropdown is focused and the user presses Esc, but the dropdown list is closed, it is still safe to interpret this action as a command to cancel row editing.

There is no way of implementing this without throwing away or patching PrimeNG. In my `@HostListener` handler, I cannot know if the event has been handled by the dropdown.

If the expected behavior (see above) was implemented, I could check `event.defaultPrevented`.

**Please tell us about your environment:**

Not really relevant.

Angular version: 7.2.8
PrimeNG version: 7.1.0
Browser: 73.0.3683.86 (Official Build) (64-bit)
Language: TypeScript 3.2.4

**Comment by cagataycivici** [comment]
You need to access event.originalEvent for this.
