### ISSUE TITLE
Editor support floating label

### ISSUE THREAD

**Issue by rafa-as** [primefaces/primeng#7525]
**I'm submitting a ...**
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**What is the motivation / use case for changing the behavior?**
To have the same behaviour than the others inputs on PrimeNG.
Now when you try to use it combined you have the following behaviour.
![image](https://user-images.githubusercontent.com/594574/55713906-e9710780-59f1-11e9-92e0-125af08e5fb0.png)

**Comment by rafa-as** [comment]
@cagataycivici if you accept PR for this, I can do it.

**Comment by cagataycivici** [comment]
It is not in our roadmap as I'm not sure if it is a good UX design.
