### ISSUE TITLE
p-table doesn't work well together with state and lazy loaded row expansion content

### ISSUE THREAD

**Issue by ThorstenKunz** [primefaces/primeng#7526]
I'm submitting a 
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://angular-6uuq5h.stackblitz.io/

**Current behavior**
If I create a table with dynamic data in a rowexpansion I usually listen on a "onRowExpand" event to load the correct data. If you combine this with the new "state" features the row toggler keeps the state but the details are empty because I have no means to trigger the loading of the details data.

**Expected behavior**
There are multiple possible solutions:

a) if a toggler state is restored from state storage send some kind of event to allow for loading of dynamic content in the expanded row
b) allow to exclude toggler state from the persistent table state so that all rows are expanded=false all the time.
c) send some other event after state was restored in general for a table so that we can e.g. look at "expandedRowKeys" and itterate over it to populate dynamic data for the rows.

**Minimal reproduction of the problem with instructions**
- go to the stackblitz example above
- expand both rows
- enable sorting by ID desc
- click reload on the browser

The row with ID 2 is expanded and shows the details because they are hardcoded. Row with ID 1 is expanded but shows no details because row content fetching is triggered by onRowExpand event and that is never fired.

**What is the motivation / use case for changing the behavior?**
In bigger tables we may show data in row expansions that is costly to load so we only load it on demand on row expansion. This should either work with stateful tables as well or at least should be able to turn it off.

Angular version: 7.2.10

PrimeNG version: 7.1.0

Browser: all

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Comment by danielcollettepb** [comment]
@ThorstenKunz I see the same issue in version 10.0.3, wound up setting the the `expandedRowKeys` to an empty object on restore:

```
public onStateRestore(state) {
    this.dt.expandedRowKeys = {};
  }
```
