### ISSUE TITLE
pickList - drag and drop

### ISSUE THREAD

**Issue by MarcinPrzybylPGE** [primefaces/primeng#7530]
> [x] bug report => Search github for a similar issue or PR before submitting
> [ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
> [ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

1. Some times drag and drop is not working correctly. Sometimes picker is does not moving the same element as i drag, or is doesn't appear in right section.

2. There is also strange behave when you have selected part of site and pickerList, and then trying move one or few items. You will get error in the console.
<img width="547" alt="error" src="https://user-images.githubusercontent.com/49430547/55853400-40e1b580-5b61-11e9-9592-0cd156a6db5d.png">

for example for demo page, to trigger a error I selected pickList with both titles.
<img width="629" alt="error2" src="https://user-images.githubusercontent.com/49430547/55853482-a9c92d80-5b61-11e9-9893-0269bbefd16e.png">

**Comment by buinhansinh** [comment]
Hi. I am facing the same issue. How can I fix it ?

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
