### ISSUE TITLE
Spinner doesn't get the state filled

### ISSUE THREAD

**Issue by anjelchen** [primefaces/primeng#7532]
[x] bug report

**Current behavior**
The p-spinner component doesn't get the state filled when it has a value filled in. So it also doesn't get the ui-state-filled css class and when in an md-inputfield, the label stays in the input and doesn't go above the input.

this is a filled spinner with label "score":
![image](https://user-images.githubusercontent.com/45607087/55955471-d1072400-5c61-11e9-806c-9ba3fd355b42.png)

**Expected behavior**
In an md-inputfield the label for the spinner should go above when the spinner has value filled in.

**Minimal reproduction of the problem with instructions**
```
<div class="ui-g form-group ui-fluid">
  <div class="ui-g-12">
    <span class="md-inputfield">
        <p-spinner [(ngModel)]="spinnerValue"></p-spinner>
        <label>Spinner label</label>
    </span>
  </div>
</div>
```

**What is the motivation / use case for changing the behavior?**
Correct the behaviour

**Please tell us about your environment:**
PrimeNG Ultima theme

* **Angular version:**
Angular 7.3.7

* **PrimeNG version:**
PrimeNG 7.1.0

**Comment by mertsincan** [comment]
Fixed now ;)
