### ISSUE TITLE
Add resizable handles to all corners of a dialog

### ISSUE THREAD

**Issue by anjelchen** [primefaces/primeng#7534]
[x] feature request

**Current behavior**
A dialog can be resized only in the south east corner.

**Expected behavior**
Dialog be resizable in all corners.

**Minimal reproduction of the problem with instructions**
Resizable dialog is resizable only in the south east corner.

**What is the motivation / use case for changing the behavior?**
Usability for the user, being able to resize dialog in all diagonal directions.

* **Angular version:**
7.3.8

* **PrimeNG version:**
7.1.0

* **Browser:**
[all]

**Comment by cagataycivici** [comment]
Decided not proceed due to lack of demand
