### ISSUE TITLE
Add onShow and onHide @Output EventEmitter to ContextMenu

### ISSUE THREAD

**Issue by anjelchen** [primefaces/primeng#7536]
[x] feature request

**Current behavior**
No event emitters on context menu when showing or hiding it.

**Expected behavior**
Event emitters on show and hide of context menu.

**What is the motivation / use case for changing the behavior?**
Being able to know when the context menu is shown or hidden.

* **Angular version:**
7.3.8

* **PrimeNG version:**
7.1.0

**Comment by OskarsPakers** [comment]
As I can see, this is already done. The issue can be closed.

**Comment by anjelchen** [comment]
yes, thank you, done in https://github.com/primefaces/primeng/commit/2f3dd85bbd36f8915e5ab8c1eef311c16f3a4e32#diff-71ecd97be5773697a23711e122a54b33

**Comment by mcpierce** [comment]
I'm using PrimeNG 7.1.3 and I don't see the events being fired. I'm programmatically showing the menu, and then trying to respond when it's hidden. But I don't see the onHide emitter ever producing and event.
