### ISSUE TITLE
Call alignScrollbar on scrollHeight change in a scrollable table

### ISSUE THREAD

**Issue by anjelchen** [primefaces/primeng#7537]
[x] bug report

**Current behavior**
Having a scrollable table with a scrollHeight set and after that changing the scrollHeight, the scrollbar should be aligned with the table header automatically. The table data is not changed.
(I have a scrollable table with header in a resizable dialog, and when dialog resizes, the scrollHeight of the table changes accordingly, but the scrollbar of the table is not aligned to the new scrollHeight)

https://stackblitz.com/edit/github-8eos6v

**Expected behavior**
Align the scrollbar (call alignScrollbar() function) of a scrollable table when the scrollHeight changes (the table is not changed) so that it shows/hides in the header of the table according to the new scrollHeight and data height.

**Minimal reproduction of the problem with instructions**
Have a scrollable table with enough data to show the scrollbar, then change the scrollHeight property of the table to a bigger number high enough that the scrollbar shouldn't be shown (do not change the data, only the scrollHeight)

**What is the motivation / use case for changing the behavior?**
Correct display of the scrollbar on a scrollable table when changing the scrollHeight dynamically without chaning the data.

* **Angular version:**
7.3.8

* **PrimeNG version:**
7.1.0

**Comment by brian428** [comment]
Any update on this? It's not a huge problem but it does look strange.

**Comment by dineshbhavsar** [comment]
> Any update on this? It's not a huge problem but it does look strange.
are get any solution on this problem. if yes so please pin me on skype: 17dcb82d88777305

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Comment by gwaping** [comment]
using primeng 8 .. and headers / columns shifting where scrollbar is present

**Comment by gwaping** [comment]
any update on this? having the same issue with mirage primeng 8
