### ISSUE TITLE
Double Click Dropdown Option Should Close Dropdown

### ISSUE THREAD

**Issue by paulpoisson** [primefaces/primeng#7538]
Upon double clicking any Dropdown option in the dropdown panel, the dropdown panel remains open. The root problem could be the animation is preventing the dropdown panel from closing. The issue can be reproduced easily on the PrimeNG Dropdown Example.

Angular version: 7
PrimeNG version: 6.1.5
Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Language: [all | TypeScript X.X | ES6/7 | ES5]

**Comment by JacobSiegle** [comment]
It doesn't seem to happen on the latest version of PrimeNG - https://www.primefaces.org/primeng/#/dropdown. I don't think they support older PrimeNG versions.

**Comment by JacobSiegle** [comment]
EDIT - Nevermind i'm clicking too fast...

**Comment by cagataycivici** [comment]
There doesn't seem to be enough community demand to proceed so closing, thank you for your understanding.
