### ISSUE TITLE
p-button component in inputgroup has inconsistent border-radius

### ISSUE THREAD

**Issue by PlaidPhantom** [primefaces/primeng#7539]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://github-w8o9lt.stackblitz.io/
https://stackblitz.com/edit/github-w8o9lt

**Current behavior**
The CSS for `ui-inputgroup` does not properly account for a `<p-button>` component being a child and does not properly change the border radiuses for a `<p-button>` as opposed to a `<button>` with the `pButton` directive.

**Expected behavior**
A `<p-button>` should look identical to `<button pButton>` inside an input group.

**Minimal reproduction of the problem with instructions**

See how the `<p-button>` in this code has border-radius set on its right edge, when they should be removed so it appears connected to the other button.

```html
<div class="ui-inputgroup">
  <p-button label="button 1"></p-button>
  <button pButton label="button 2"></button>
</div>
```

I am able to work around this issue with this SCSS:

```scss
.ui-inputgroup {
    & > p-button:not(:first-child) > .ui-button {
        border-top-left-radius: 0;
        border-bottom-left-radius: 0;
    }

    & > p-button:not(:last-child) > .ui-button {
        border-top-right-radius: 0;
        border-bottom-right-radius: 0;
    }
}
```

**What is the motivation / use case for changing the behavior?**
Consistency

**Please tell us about your environment:**

* **Angular version:** 7.2.0

* **PrimeNG version:** 7.0.5

* **Browser:** Firefox 66
 
* **Language:** Typescript 3.2.2

**Comment by mertsincan** [comment]
The workaround looks good. Could you please attach a PR for this issue? If you send the PR, I'll merge it into core.

**Comment by JacobSiegle** [comment]
I think the same issue exists when using p-togglebutton I believe.
