### ISSUE TITLE
Default rows selected in datatables

### ISSUE THREAD

**Issue by jeffrysteven** [primefaces/primeng#754]
Hi, I tried to pass a default selected rows to datatables and doesn't work never. I found an error in your datatables component because you are comparing two objects (array item of the [(selected)] attribute with all the object of [value] attribute). It is impossible, see: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness#A_model_for_understanding_equality_comparisons.

I solved this with string comparisons with the help of JSON.stringify.

I created a pull request with this change: #753

**Comment by dereklin** [comment]
@jeffrysteven How do you pass in default selected rows?  If the default selected rows are on page 3 of a paginated table, will the table load page 3 automatically?
