### ISSUE TITLE
ui-slider background-color with border properties

### ISSUE THREAD

**Issue by LukSkywookie** [primefaces/primeng#7544]
https://github.com/primefaces/primeng/blob/f6f17cfaad2765eec974fb660c5d401031a5ec2c/src/assets/components/themes/nova-light/theme.css#L832

Hello. I've just found little issue with styling slider (above).

Regards,
Luk

**Comment by cagataycivici** [comment]
There doesn't seem to be enough community demand to proceed so closing, thank you for your understanding.
