### ISSUE TITLE
DataTable virtual scrolling with onLazyLoad: event.first is 0 when sorting

### ISSUE THREAD

**Issue by DominikStarke** [primefaces/primeng#7546]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-b7yuhg

**Current behavior**
If onLazyLoad is fired by sorting while the table is scrolled down to for example entry 500 the event.first property is 0.

**Expected behavior**
Either the table should scroll up or the event.first should reflect the current scrolling position

**Minimal reproduction of the problem with instructions**
See the stackblitz. Open the output console, scroll somewhere and press one of the sorting headers.

**What is the motivation / use case for changing the behavior?**
p-table with lazy loading and server side sorting

* **Angular version:** 7.2.12

* **PrimeNG version:** 7.1.0

**Comment by hnassr** [comment]
same problem, any solving ?

**Comment by johnfabian** [comment]
Is this fixed yet? I'm on page 3 in the table click sort and is reset to 0?? I'm using Primeng 8.1.1 and angular 8. Are there any workarounds for now?

**Comment by johnfabian** [comment]
Actually I remove the lazy loading, set paging off, added the paging component below the table and just implemented it manually and the global filter works better now since doesn't fire a server request on every keystroke.

**Comment by cagataycivici** [comment]
VirtualScrolling for Table is reimplemented from the ground up (#8855) and this particular case i no longer an issue with the new implementation. Thank you for the feedback.
