### ISSUE TITLE
In p-table, a column is not sortable if the column name has a '.'

### ISSUE THREAD

**Issue by SDvlpr** [primefaces/primeng#7547]
A column is not sortable in Turbotable if the title has a dot in it.

**Comment by JacobSiegle** [comment]
https://stackblitz.com/edit/github-dp4izx

https://github.com/primefaces/primeng/blob/3b6e6d52e5f452fdb2cfe2eb689e5a01666fd581/src/app/components/table/table.ts#L665

'.' in sort automatically looks for sub properties. One way to fix it asap would be apply your own sorting function (basically a link of above) and don't use the "resolveFieldData" part. To fix it I would assume sort needs an extra param that forces "resolveFieldData" to not be called.

**Comment by cagataycivici** [comment]
dot is a special character so cannot be supported. Following will work though;

```json
data: any[] = [
      { vin: {name: 1}, year: 1990, brand: "Acura", color: "red" },
    ];
```
