### ISSUE TITLE
ui-inputgroup is not working properly in firefox/Edge

### ISSUE THREAD

**Issue by ggarg-c** [primefaces/primeng#7548]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Waiting Time: ~8 weeks.

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.X

* **PrimeNG version:** 5.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by ggarg-c** [comment]
<div class="ui-g-12 ui-md-2">
          <div class="ui-g-12 ui-sm-12 ui-md-12 ui-inputgroup round-input-div" >
            <span class="ui-inputgroup-addon" style="border:none;background:transparent;"><i
                class="fa fa-lock round-input-icon"></i>
             </span>
            <input pInputText #confirmPassword type="password" class="round-input-element"
              formControlName="confirmPassword" placeholder="Confirm Password *" maxlength="15"
              (paste)="paste($event)" />
            <span class="ui-inputgroup-addon" style="border:none;background:transparent;"><i
                class="fa fa-eye round-input-icon"></i>
            </span>
          </div>
        </div>

**Comment by ggarg-c** [comment]
Using this control, eye icon is going out of ui-md-2 width in firefox/edge. however it iis working properly in chrome.
Even in primeng faces webiste if we inspect the input group element and make it ui-md-2 then it is not working as expected in firefox/edge.

**Comment by JacobSiegle** [comment]
It works fine in chrome, firefox, and edge for me - https://stackblitz.com/edit/github-fse6kp.

**Comment by JacobSiegle** [comment]
Try setting the input element to width: 100%, that should fix it for you.

**Comment by ggarg-c** [comment]
> Try setting the input element to width: 100%, that should fix it for you.

hi @JacobSiegle ,
Thanks for the reply. But still issue is there.
Please try adding below css in your stackblitz and check by reducing window size in firefox. 

.round-input-element:focus {
    box-shadow:none;
    border-color:transparent;
    outline: none !important;
 }
.round-input-div{
  background-color: white;
  border-radius:50px;
  border: 1px  solid black;
}
.round-input-element{
  border:none;
  background-color: white;
  color: black;
  outline: none !important;
  width:100%;
}
.round-input-icon{
  color:gray;
  background: transparent;
  border: none;
}

**Comment by JacobSiegle** [comment]
Thanks it's easier to see the issue with the provided CSS. You can use flex-grow to fix it with width 100%.
https://stackblitz.com/edit/github-fse6kp-jcmkrx

**Comment by ggarg-c** [comment]
Thanks alot @JacobSiegle for the fix.
