### ISSUE TITLE
p-table: Misaligned header on a scrollable table

### ISSUE THREAD

**Issue by AlexZanel** [primefaces/primeng#7549]
When the scroll bar appears the columns are shifted.
I tried the following:

.ui-table-scrollable-body {
	margin-right: 17px !important;
}

	
But when the scroll bar disappears the columns are shifted again.
Can I fix this somehow? Can I find out if the item has a scrollbar now?

Demo  - https://stackblitz.com/edit/table-editor-add-columns-psfrsx?file=src/app/app.component.ts

**Comment by JacobSiegle** [comment]
Duplicate - https://github.com/primefaces/primeng/issues/7537

**Comment by JacobSiegle** [comment]
If you're looking for a hack workaround for now just do `this.cars = [... this.cars];` after your change the scroll height.

**Comment by cagataycivici** [comment]
#7537
