### ISSUE TITLE
Multiple Selection support for Month Picker

### ISSUE THREAD

**Issue by ewacha** [primefaces/primeng#7551]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
not necessary

**Current behavior**
I use the month picker with [code]selectionMode="multiple"[/code] The selected months are not marked in the popover. 
After recalling them again, nothing is displayed in the popover. Only a hover at the places of the single months is visible. And they can be de/selected. But you mus guess the right places...

**Expected behavior**
Selected months remain highlighted, also after reopening the popover

**Minimal reproduction of the problem with instructions**
-

**What is the motivation / use case for changing the behavior?**
Correct function of the component

**Please tell us about your environment:**

* **Angular version:** 7.X

* **PrimeNG version:** 7.1.0-SNAPSHOT

* **Browser:** [all | Chrome 73 | IE Edge/11] 
 
* **Language:** [all]

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
