### ISSUE TITLE
'p-toast' is not a known element:

### ISSUE THREAD

**Issue by lfmeinecke** [primefaces/primeng#7554]
Hello,

I'm using angular v6.1.10 and primeng v6.1.7 and I'm trying to use the toast component, I made the import of it in app.module.ts, however the 'p-toast' error is not a known element.

can anybody help me?

**Comment by JacobSiegle** [comment]
This is a question not an issue, you should use the primeng forum for issues instead. Your import is not setup correctly if it doesn't work. Make sure you import the module and also include ToastModule in imports and exports in your module as needed.

**Comment by lfmeinecke** [comment]
Okay, I already posted on the forum.

The import is according to the tutorial of the site.

**Comment by JacobSiegle** [comment]
Make sure you import the module **and also include ToastModule in imports and exports in your module as needed.**

**Comment by lfmeinecke** [comment]
It worked! Thanks!

**Comment by JacobSiegle** [comment]
Please close the issue if you believe it's been resolved. Thanks.

**Comment by ericpesser** [comment]
This helped me also. Thank you !
