### ISSUE TITLE
Clear twice to clear selection format for table?

### ISSUE THREAD

**Issue by magicdict** [primefaces/primeng#7559]
Clear twice to clear selection format for table...Amazing,Why?
The first time,the selection is empty,but the style is not be removed..
The second time,style is removed..

    @ViewChild("dt")
    nametable: Table;
    clearSelection() {
        //Clear Twice to clear selection format
        this.nametable.selection = [];
        this.nametable.selection = [];
    }

**Comment by JacobSiegle** [comment]
Can you give anymore context to help understand the issue or provide a stack-blitz? If you are trying to clear selected items from the table why not use the table binding `[(selection)]="selectedCar"`?

**Comment by magicdict** [comment]
I want to not only remove the selection,but also remove the ui-state-highlight sytle.
When I first time clear selection,the selected items is empty,but the style is not clear.
But I find if I clear selection twice,the style is removed.

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
