### ISSUE TITLE
Rowgroup with rowexpansion not showing all rows for dynamic columns

### ISSUE THREAD

**Issue by naman1901** [primefaces/primeng#7560]
**I'm submitting a ...** 
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

I have implemented grouping with custom sort. Basically, I take one column as the grouping field and make the groupings appropriately. The group data itself is shown by expanding the row.

In the first case **TablegroupingComponent**, I fix "brand" as the group to group by and have a `groupField` boolean based on which grouping is enabled/disabled.

In the second case **TableDyanmicGroupingComponent**, `groupField` is a string variable that contains the column to group by.

In both cases I have implemented a custom sort function which sorts entries only within each group. I have logged the data variable after sorting to verify that my sorting function works correctly.

**Current behavior**
For the fixed column grouping, the working is as expected. 
For the dynamic column grouping, on expanding the rows, I can see only one row per expansion. If I then sort some other column by clicking the column header and then try to toggle row expansion, I see more rows but the original row does not collapse anymore.

**Expected behavior**
Expected behaviour for dynamic grouping should be the same as the current behaviour of fixed grouping.

**Minimal reproduction of the problem with instructions**
Please find the demo here: https://stackblitz.com/edit/angular-primeng-stack-55706959-1t8w8n

**What is the motivation / use case for changing the behavior?**
Grouping should not be fixed in the code, it should be modifiable dynamically

**Please tell us about your environment:**
Windows 10/Server

* **Angular version:** 6.1.9

* **PrimeNG version:** 6.1.7

* **Browser:** all (StackBlitz attached)
 
* **Language:** TypeScript 2.9.2

Tracking at StackOverflow [here](https://stackoverflow.com/questions/55744113/primeng-turbotable-p-table-rowgroup-with-rowexpansion-not-showing-all-rows-for)

**Comment by JacobSiegle** [comment]
You need to fix your code it has a bug see - https://stackblitz.com/edit/angular-primeng-stack-55706959-izubxl

**Comment by naman1901** [comment]
Thanks @JacobSiegle ! This fixed it.
Question: Would this not mess up row selection since the datakey is being changed?

**Comment by naman1901** [comment]
I can confirm that it does. I need rows to be individually selectable as well as groupable. Why is the same "datakey" binding being used everywhere? Separate bindings should be provided!

**Comment by JacobSiegle** [comment]
Toggle row requires using the datakey and since the datakey doesn't match I assume that's the issue - https://github.com/primefaces/primeng/blob/8675c67ebe411e8a5a03ad55c649b87dbc2eb790/src/app/components/table/table.ts#L1592

I would need to step through the entire thing to be 100% sure that's actually it, not sure when i'll have time. Otherwise a maintainer might be able to help.

**Comment by naman1901** [comment]
Yes, you're right about that. For now I have kept the `datakey` as `"id"` and implemented my own logic to handle row expansion (all in the body pTemplate). I have some issues where the rows do not seem to be aligned properly.
![image](https://user-images.githubusercontent.com/13290002/56560005-df89ff80-65c0-11e9-89c3-1dd5878592a8.png)
If I remove the `<tr>` that enables row expansion, things seem to work fine.
![image](https://user-images.githubusercontent.com/13290002/56560140-44ddf080-65c1-11e9-8745-04d50eab32b1.png)

**Comment by JacobSiegle** [comment]
Guessing without looking at the code but I would try to put in a colgroup - 
```
    <ng-template pTemplate="colgroup" let-columns>
        <colgroup>
            <col *ngFor="let col of columns">
        </colgroup>
    </ng-template>
```

If the table is misaligned due to a scrollbar appearing on expansion your need to call alignScrollBar() from a ViewChild of the table.

Hopefully changes to expansion can be made to prevent having to do a workaround.

**Comment by cagataycivici** [comment]
Not an issue on our side.

**Comment by naman1901** [comment]
Yes the alignment is not an issue on PrimeNg's side. I figured out using a colgroup just like @JacobSiegle.

@cagataycivici perhaps you can look into implementing support for multiple levels of row expansion rather than the user having to write custom code for it.
