### ISSUE TITLE
With focustrap for dialog you cannot tab past hidden or disabled elements

### ISSUE THREAD

**Issue by gwoplock** [primefaces/primeng#7561]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Waiting Time: ~8 weeks.

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/primeng-captive-tab-hidden-bug

**Current behavior**
using the dialog captive tab, if there is a hidden or disabled element that should be tabbed to next it won't move the focus.

**Expected behavior**
skip disabled and hidden elements when tabbing in dialog

**Minimal reproduction of the problem with instructions**

demo: 
https://stackblitz.com/edit/primeng-captive-tab-hidden-bug

using demo:
1. click button
2. try tabbing in dialog
3. notice that you can not tab to cancel

**Please tell us about your environment:**

windows 10

* **Angular version:** 7.2.8

* **PrimeNG version:** 7.1.1

* **Browser:** tested in chrome and firefox, both are reproducible with the stackblitz. haven't tried others

 
* **Language:** typescript 3.1.1

**Comment by cagataycivici** [comment]
Fixed via PR
