### ISSUE TITLE
Primeng Tooltip: Is there any way to add ptooltip declaration using Directive ?

### ISSUE THREAD

**Issue by shaileshyadav24** [primefaces/primeng#7565]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Need to declare on HTML for tooltip

**Expected behavior**
Can add tooltip declaration through Directive using ElementRef.

**What is the motivation / use case for changing the behavior?**
To show tooltip for ellipsis text only.

* **Angular version:** 6.X

* **PrimeNG version:** 6.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by JacobSiegle** [comment]
You would need to do something like this article to dynamically add tooltips - 
https://hackernoon.com/angular-pro-tip-how-to-dynamically-create-components-in-body-ba200cc289e6

You can search online for other ways to do this, I believe this is a question not an issue. Try posting questions to https://forum.primefaces.org/ instead.

**Comment by cagataycivici** [comment]
This is Angular related.
