### ISSUE TITLE
PrimeNG KeyFilter alphanum allows !#$%&( in Firefox and IE

### ISSUE THREAD

**Issue by jonhiga** [primefaces/primeng#7570]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://github-rzs7rm.stackblitz.io

**Current behavior**
<input [formControl]='control' pKeyFilter='alphanum' /> does not filter some punctuation.

**Expected behavior**
Only letters and numbers should appear in the input control.

**Minimal reproduction of the problem with instructions**

1. Import `KeyFilterModule`.
2. Define `control: FormControl`.
3. Use `<input [formControl]='control' pKeyFilter='alphanum' />` in the template.
4. Enter punctuation into the input control.

**What is the motivation / use case for changing the behavior?**
Some input fields should allow only letters and numbers.

**Please tell us about your environment:**
Fedora 28, npm 6.9.0

* **Angular version:** 7.2.4

* **PrimeNG version:** 7.0.5

* **Browser:** [ Firefox 66.0.2 | IE 11.1029.16299.0 ]
 
* **Language:** [ TypeScript 3.2.4 ]

* **Node (for AoT issues):** `node --version` =  v10.14.2

**Comment by RobinHames** [comment]
I'm getting the same issue with PrimeNg version 7.1.3 and Angular version 8.0.0

With pKeyFilter="int", an Input element allows !"$%&(

<input class="form-control input-md ng-valid ng-dirty ng-touched" type="number" ng-reflect-model="" pKeyFilter="num" ng-reflect-pattern="num" _ngcontent-rpm-c40="">

**Comment by bishoy-zaki** [comment]
I'm still getting this for pKeyFilter='noSpecial' on the following environment:

- Angular version: 8.3.23
- PrimeNG version: 8.1.1
- Browser: [ Firefox 68.4.2esr | IE 11.973.17763.0 ]
- Language: [ TypeScript 3.7.5 ]
- Npm version: 6.13.6
- Node version: v12.14.1
