### ISSUE TITLE
primeNG p-autocomplete autofocus 

### ISSUE THREAD

**Issue by policz** [primefaces/primeng#7571]
Hello i'm using p-autocomplete element tag ,which is not inside of p-dialog box,

i'm trying to implement autofocus to a particular area or element upon opening a model window
i have tried with different ways of implementation but nothing gets solve my issue.

From my investigation, when the onAutoShow() function triggers just (this.resourceSignum) gets undefined

Below is my code of html and component.
.html file

<p-autoComplete #resourceSignum
(onShow)= "onAfterShow()"
[suggestions]="resourceSuggestions"
(completeMethod)="searchRecoveries($event)"
formControlName="signum">

component.ts file

import { AutoComplete } from 'primeng/autocomplete';

@ViewChild('resourceSignum') private resourceSignum: AutoComplete;

onAfterShow() {
this.resourceSignum.focusInput();
}

**Comment by JacobSiegle** [comment]
Autocomplete doesn't have an (onShow) event, only dialog does.

**Comment by policz** [comment]
Hey JacobSiegle Thanks for your comment

Actually  i tried with (onFocus) to trigger an event but its not happening, so i tried with (onShow) but its useless any suggestion

**Comment by JacobSiegle** [comment]
You need to wait for the viewchild element in the primeng component to load. Here's a really quick example - https://stackblitz.com/edit/github-1n5qef?file=src/app/app.component.ts. You can probably find more elegant solutions by searching for this common problem.

**Comment by policz** [comment]
Thank you and i will try to implement in your way..!

**Comment by policz** [comment]
hey tired but i'm getting error please find the belo
<img width="623" alt="inputEl" src="https://user-images.githubusercontent.com/6464037/56588560-98e0d900-65b1-11e9-8fee-1e79e099b39b.PNG">
w screenshot

**Comment by JacobSiegle** [comment]
There's something in your code not being shown in the issue to get that error. I don't believe this is an issue but a help request. You can try to post to the primeng forums for help requests https://forum.primefaces.org/.

**Comment by policz** [comment]
ok here is my explanation and code:

Firstly, a model window should open with username field as autofocused, since i'm using p-autocomplete but simply [autofocus]="true" doesn't work, so i'm looking for the other way.


Below is the html code:


The **showAddResourceModal(resourcesModal)** using the parameter to populate the ng-template
---------------------------------------------------------------------------------------------------------------

<i class="icon icon-plus pointer" (click)="showAddResourceModal(resourcesModal)" ngbTooltip="Add></i>


<ng-template #resourcesModal let-c="close" let-d="dismiss">
  <form [formGroup]="resourceForm" class="add-resource"
        (submit)="isEditResourceMode ? updateResource() : addResource()">

    <div class="modal-header"></div>

    <div class="modal-body">
      <div class="row">
        <div class="col-lg-6 form-group">
          <label for="resourceSignum">Signum/Name</label>  
          <p-autoComplete #resourceSignum        
                          [suggestions]="resourceSuggestions"
                          (completeMethod)="searchRecoveries($event)"
                          formControlName="signum"
                          [inputStyleClass]="signum.invalid && signum.touched ? 'required form-control' : 'form- 
                           control'"
                          (onSelect)="processSignum(signum.value)"
                          (onBlur)="onBlur()"
                          id="resourceSignum"
                          [placeholder]="signum.disabled ? '' : 'Start typing'">
            <ng-template let-user pTemplate="item">
              <div [innerHTML]="user.suggestedResult"></div>
            </ng-template>
          </p-autoComplete>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn primary" type="submit">{{ isEditResourceMode ? "Edit" : "Add" }}</button>
    </div>
  </form>
</ng-template>


component.ts file

component.ts file

import { AutoComplete } from 'primeng/autocomplete';

@ViewChild('resourceSignum') resourceSignum: AutoComplete;


ngOnInit() {
this.waitForViewChildToLoadThenFocus();
}

  waitForViewChildToLoadThenFocus() {
    setTimeout(() => {
      if (this.resourceSignum.inputEL !== null) {
        this.resourceSignum.focusInput();
        console.log("Loaded");
      }
      else {
        this.waitForViewChildToLoadThenFocus();
        console.log("Waited");
      }
    }, 10)
  }

**Comment by JacobSiegle** [comment]
It seems like your code is using https://ng-bootstrap.github.io/#/components/modal/examples. You need to sync running your code when the dialog appropriately shows most likely. I don't use ng-bootstrap so I cannot assist you and this is not an issue with PrimeNG so it shouldn't be posted here.

**Comment by policz** [comment]
yes i'm using  ng-bootstrap for the model windows

**Comment by cagataycivici** [comment]
Please use forum for discussions.
