### ISSUE TITLE
Confirm Dialog IE 11 errors

### ISSUE THREAD

**Issue by johnfabian** [primefaces/primeng#7577]
I get the following error in V7 with IE 11, even on the primeng website I get the same error:

Uncaught (in promise): Error: The animation trigger "animation" has failed to build due to the following errors
 The provided animation property "-webkit-transform" is not a supported CSS property for animations

I rolled back to 7.1.0 with no issues

**Comment by dmoore1181** [comment]
Same here, simply commenting out the '-webkit-transform':'translateX(-50%) translateY(-50%)', line in confirmdialog.ts fixes the issue (though the animation is a bit jumpy in IE11, but still works properly in Chrome.

**Comment by mertsincan** [comment]
Fixed for 7.1.3. (Duplicate of #7597)

**Comment by mthor** [comment]
When is the release of 7.1.3, we need to out, getting complaints

**Comment by SeinopSys** [comment]
@mthor I've just ran `npm update` and it appears to have installed 7.1.3

**Comment by mthor** [comment]
yes, I have updated, not the break on ie11 is grids don't load, you have to click the mouse or scroll over something and it loads the grid one record at a time
