### ISSUE TITLE
Fix for #7453 doesn't resolve the issue but PR #7454 does

### ISSUE THREAD

**Issue by clpalmer** [primefaces/primeng#7582]
Please see #7453 for details on the issue. Submitting this duplicate as that issue was closed, but isn't resolved for me. The proposed fix in PR #7454 fixes the issue for me.

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
