### ISSUE TITLE
ContextMenu disabled menu item shows subitems

### ISSUE THREAD

**Issue by anjelchen** [primefaces/primeng#7585]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Current behavior**
having a context menu with a disabled item which has subitems, hovering over the item shows the subitems even if the item is disabled and should not show the subitems.
this problem comes from https://github.com/primefaces/primeng/pull/7488
wasn't in 7.1.0, but is in 7.1.1 after that PR was merged

**Expected behavior**
not show subitems of context menu item which is disabled

**Minimal reproduction of the problem with instructions**
context menu with a disabled item with subitems, hover over disabled item.

**What is the motivation / use case for changing the behavior?**
it is a bug that should be fixed.

* **Angular version:** 7.2.14

* **PrimeNG version:** 7.1.1

**Comment by mmlitvin** [comment]
I can see this problem too after we upgraded to primeng 8

**Comment by cagataycivici** [comment]
Should be fixed in 9.0.2+.
