### ISSUE TITLE
How to add the overlaypanel to follow the cursor on mouseover with appendTo body

### ISSUE THREAD

**Issue by arun-sukumar** [primefaces/primeng#7591]
[x] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

Primeng: 7.0.4

I am adding overlay as below, and this will be rendered on mouseover to a line item,
<p-overlayPanel #overlayPanel [appendTo]="'body'" [dismissable]="true" [showCloseIcon]="false">
    <div innerHtml="{{ overlayContent }}"></div>
  </p-overlayPanel>

My problem is, the overlaypanel sticks to the body and doesn't follow the cursor like tooltip. So kindly let me know how to implement follow cursor option for overlaypanel.

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.
