### ISSUE TITLE
Full Control over Tabindex in table

### ISSUE THREAD

**Issue by MeMeMax** [primefaces/primeng#7595]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://wmairglx.github.stackblitz.io

**Current behavior**
I can´t set tabindex if pSortableColumn or pSelectableRow is used. This is due to this line of code: '[attr.tabindex]': 'isEnabled() ? 0 : undefined',

**Expected behavior**
The developer should be able to set tabindex. Default value may stay 0.

**Minimal reproduction of the problem with instructions**
see stackblitz

**What is the motivation / use case for changing the behavior?**
The developer should be able to set tabindex.

**Please tell us about your environment:**
Windows

* **Angular version:** 5.X
7.2.0

* **PrimeNG version:** 5.X
7.1.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by Danieleeee** [comment]
I need [attr.tabindex]="-1" in p-sortIcon:
`<p-sortIcon *ngIf="tipoFile(col.TIPO)" [pSortableColumn]="col.FIELD" [field]="col.FIELD" [attr.tabindex]="-1"></p-sortIcon>`

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Comment by nironater** [comment]
#8822 is a new ticket for this issue that i created with a new stackblitz that shows how it's reproduced @cagataycivici  - Did what you asked... the ball is in your hands now

**Comment by flawesomesoft** [comment]
The issue still persists... 
What's the deal of creating new tickets which in the end will be simply ignored?!

Kind of feel sorry for people like @nironater who do their best describing an issue and then simply be ignored like that.

@cagataycivici I don't see it's not reproducible in PrimeNG 9. Anyway it's still the same behaviour for PrimeNG v13 and probably also beyond
