### ISSUE TITLE
Un-resizable column following resizable one is resizable

### ISSUE THREAD

**Issue by AbakumovAlexandr** [primefaces/primeng#7599]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/primeng-table-resize-col-issue

**Current behavior**
First un-resizable column which follows a resizable one is actually resizable.

In the Stackblitz above, `Unresizable Column 1` is resizable.

**Expected behavior**
Columns not marker with `pResizableColumn` directive must not be resizable regardless of whether neighboring column(s) marked with the `pResizableColumn` directive.

**Minimal reproduction of the problem with instructions**
In the Stackblitz above:
1. `Unresizable Column 2` is correctly un-resizable. Neither left, nor right border is draggable.
2. `Unresizable Column 1` can actually be resized by dragging its left border.

**What is the motivation / use case for changing the behavior?**
If a column is not marker with `pResizableColumn` directive, we don't want it to be resizable. Resizing it could lead to various issues starting from cosmetic ones to breaking the whole app layout in certaain ways, etc.

* **Angular version:** 7.2.14

* **PrimeNG version:** 7.1.2

* **Browser:** all
 
* **Language:** all

**Comment by cagataycivici** [comment]
Set resize mode to expand, unresizable column means it cannot be resized in fit mode.
