### ISSUE TITLE
Create a template for DynamicDialog footer

### ISSUE THREAD

**Issue by NathanAlcantara** [primefaces/primeng#7603]
** I'm submitting to ... **
[] bug report
[X] feature request
[] support request

** Current behavior **
Today it's only possible to put a string in footer

** Expected behavior **
It would be interesting put a template, where you can put anything there
Like the p-dialog where you can put a p-footer

** What is the motivation / use case for changing the behavior? **
I need to show a button on a p-dynamicdialog footer.

** Please tell us about your environment: **
I'm using Win10 and Yarn for my package manager

* ** Angular version: ** 7.2.6

* ** PrimeNG version: ** 7.0.0

* ** Browser: ** all

* ** Language: ** all

* ** Node (for AoT issues): ** `node --version` = 10.13.0

**Comment by BensonBen** [comment]
I would also like this feature, but update your issue to correctly reflect the class you're trying to reference

**Comment by praneeshc** [comment]
Is this available?

**Comment by BensonBen** [comment]
I've solved this issue on my own to see if it was possible, as well as, several other features that would be useful. Looks like there's an interest in it. I'll try and get a pull request out this weekend

**Comment by praneeshc** [comment]
@BensonBen, That would be really helpful. Please comment when you have this completed. Thanks

**Comment by Menyueru** [comment]
I needed this too but for the header, I patched it in on my end by changing the header to instead be a innerhtml binding and it seems to be working fine, still trying to find a more elegant solution though.

**Comment by 17797776321** [comment]
If you want to implement dynamic diaolog, you can do the following：
1、Write  <div class="p-dialog-footer" style="width:100%;position:fixed;left:0;bottom:0"><div> at the bottom of your component;
2、Configure the contentstyle parameter in your dialogservice.open method. Just like contentStyle:{
        "padding-bottom":"50px"
 }

**Comment by 17797776321** [comment]
If you want to implement dynamic diaolog, you can do the following：
1、Write<div class="p-dialog-footer" style="width:100%;position:fixed;left:0;bottom:0"></div> at the bottom of your component;
![image](https://user-images.githubusercontent.com/20875342/124736774-e905a500-df49-11eb-88dd-a5c17382fcd5.png)

2、Configure the contentstyle parameter in your dialogservice.open method. Just like contentStyle:{
"padding-bottom":"50px"
}
![image](https://user-images.githubusercontent.com/20875342/124736812-f589fd80-df49-11eb-8454-4dc079fa76e5.png)

**Comment by lucassalatiel1993** [comment]
Can anyone tell me if this improvement will be implemented?

**Comment by MrTob** [comment]
same here, need it very quickly

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by saramcicchi** [comment]
Hi @mertsincan - this feature has not been added. Can you please reopen the issue?

**Comment by toxaq** [comment]
My pull request https://github.com/primefaces/primeng/pull/12068 adds this feature. It's currently awaiting review.

**Comment by yBouzeliffa** [comment]
i just needed the feature, thank u @toxaq, hope it's will be deploy soon

**Comment by cetincakiroglu** [comment]
Hi,

You can use templating options of dynamic dialog https://primeng.org/dynamicdialog#api.dynamicdialog-ref.interfaces.DynamicDialogTemplates

Please also see the example: https://primeng.org/dynamicdialog#api.dynamicdialog-ref.interfaces.DynamicDialogTemplates

**Comment by RafalSzczuka** [comment]
> Hi,
> 
> You can use templating options of dynamic dialog https://primeng.org/dynamicdialog#api.dynamicdialog-ref.interfaces.DynamicDialogTemplates
> 
> Please also see the example: https://primeng.org/dynamicdialog#example

@cetincakiroglu  Is there any chance to support adding header/content/footer by referencing some specific directive (simply pass TemplateRef). The possibility to pass only the Footer or Header components is quite inconvenient. It would be nice to have an option, building dialog contents, to just put a directive over a element, and that directive would be checked in Prime Dialog component.
