### ISSUE TITLE
How to select dropdown value

### ISSUE THREAD

**Issue by dineshmaths1** [primefaces/primeng#7606]
I have multiple dropdown  like this  .Every loop different different status is available.  How to select the value ?
```
   <ng-container *ngFor="let res of p.value|keyvalue;let i=index">
  <p-dropdown [options]="status_list" placeholder="Status"></p-dropdown>
 </ng-container>
```

**Comment by JacobSiegle** [comment]
This is a question about your code not an issue with primeng. Try using the forum instead https://forum.primefaces.org/.

**Comment by cagataycivici** [comment]
Please use forum for support requests and questions.
