### ISSUE TITLE
p-panel, p-card not shown child component in body

### ISSUE THREAD

**Issue by volkanokcu** [primefaces/primeng#7609]
```
<p-card>
  <pg-dynamic-form-toolbar [formGroup]="formGroup"></pg-dynamic-form-toolbar>
  <form *ngIf="form | async as fromData; else loading" [formGroup]="formGroup" (ngSubmit)="submit()">
        <div *ngFor="let container of fromData.containers" class="ui-fluid">
            <div *ngFor="let input of container.inputs">
                    <pg-element-generator [input]="input" [formGroup]="formGroup"></pg-element-generator>
            </div>
        </div>
</form>
<form-component></form-component>
</p-card>
```

Generated (with selector) component doesnt rendering inside of card. First selector work well. But 2th selector doesnt rendrering correct . Import NoopAnimationsModule still same issue. Any solution? Thanks.
![image](https://user-images.githubusercontent.com/26742662/56868004-5a09b380-69f5-11e9-94da-99cd94df1fbb.png)

**Comment by mertsincan** [comment]
Thanks a lot for the screenshot. It has to be a HTML element has "ui-g" class wrapping your <div class="ui-g|md|lg-*"> element in DOM. The "ui-g" class clears the floating elements. Exp;
```
<div class="ui-g"> // pg-element-generator
    <div class="ui-g-12 ui-md-3">
        //pg-input-element
    </div>
</div>
```
Best Regards,

**Comment by volkanokcu** [comment]
Thank you for fast response. I now understand how primeng grid system works.

**Comment by mertsincan** [comment]
Glad to hear, thanks a lot for the update!
