### ISSUE TITLE
PrimeNG multiselect's Filter's checkbox selects all values even when filter search returns zero results

### ISSUE THREAD

**Issue by SDvlpr** [primefaces/primeng#7610]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**

Go to multiselect and type "test" in filter. when no match, select the checkbox next to the filter. It is selecting all the values of the multiselect. Where as it should not select any as there is no match for test.
![image](https://user-images.githubusercontent.com/30119190/56901793-f61fd300-6a66-11e9-99b4-6f358d62270c.png)

**Expected behavior**

When filter search returns zero results, checkbox next to filter should select NONE.
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:**7.0.0

* **PrimeNG version:** 7.0.5

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** TypeScript 3.1.6 

* **Node (for AoT issues):** `node --version` =   10.14.1

**Comment by peter-stoyanov** [comment]
I've made far from perfect monkey patch for this in case someone's looking for a quick fix here: https://gist.github.com/peter-stoyanov/dd2d52e1027395cff52a35b35801ba8c

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
