### ISSUE TITLE
how to add a value to Primeng auto complete on outside click event

### ISSUE THREAD

**Issue by PrathyushaRecherla** [primefaces/primeng#7614]
@doeringp I have a list of values that can be added to input filed using Primeng auto complete. I would like to add new values to the input filed and push it to texts array when I click outside of the input box.

In the below example I have keyboard event. It can add values to the texts array on pressing on Enter button. I would like to implement the similar functionality on clicking outside of the input box.
[https://stackblitz.com/edit/angular-kfvj5p](url)

**Comment by JacobSiegle** [comment]
This is a question not an issue and should be asked on the primeng forum instead. If you believe this is an issue with the PrimeNG framework please clarify.

**Comment by PrathyushaRecherla** [comment]
Used onBlur event to add values on outside click.
 ` OutsideClick(event: KeyboardEvent) {
    let tokenInputValue = event.srcElement as any;
      console.log("token input on Blur", tokenInputValue.value);
  }`
