### ISSUE TITLE
Adding table as rowexpansion of parent table breaks IDE HTML formatting

### ISSUE THREAD

**Issue by davisb10** [primefaces/primeng#7615]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Waiting Time: ~8 weeks.

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**

I think this is just an issue with how Tables are defined in html, but have a p-table inside of another p-table is breaks formatting in most IDEs. Webstorm, Visual Studio Code, Visual Studio Professional.

**Expected behavior**

**Minimal reproduction of the problem with instructions**

Add the following code to any .html file and it will start showing issues starting with the closing ```</td>``` after the inset p-table item
```
<p-table>
  <ng-template>
    <tr>
      <td>
        <p-table>
          <ng-template>
            <tr></tr>
          </ng-template>
        </p-table>
      </td>
    </tr>
  </ng-template>
</p-table>
```

**Comment by JacobSiegle** [comment]
Doesn't seem like a bug with PrimeNG. Let me know if i'm missing something here.

**Comment by davisb10** [comment]
I mean, it's not really a bug with PrimeNG as a whole. More as just how PrimeNG defines tables using base html table syntax. Is there any other way to define table items, without it have HTML formatters freak out? Old style p-dataTable had p-column that would kind of remove that problem
