### ISSUE TITLE
Left arrow press should focus parent on Tree

### ISSUE THREAD

**Issue by EcoFreak** [primefaces/primeng#7619]
**I'm submitting a feature request**
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

The keyboard navigation behavior does not allow an ease of navigation of tree nodes.
This is mainly due to the the left arrow behavior. 
When a node with expanded children is focused the left arrow key collapses them (which is an expected behavior).
However when a node as no children or the children are collapsed the left key does nothing.

**Initial state:**
![image](https://user-images.githubusercontent.com/3418386/57063157-33c86a00-6cba-11e9-8e25-80213fadb902.png)
**After left arrow press on Work node:**
![image](https://user-images.githubusercontent.com/3418386/57063188-50fd3880-6cba-11e9-88f4-40ce25bfbf82.png)
**After a second left arrow press on Work node:**
No changes

![image](https://user-images.githubusercontent.com/3418386/57063188-50fd3880-6cba-11e9-88f4-40ce25bfbf82.png)

**Expected behavior**
The left key should focus the parent node if the current focused node has no expanded children.

**After a second left arrow press on Work node:**
![image](https://user-images.githubusercontent.com/3418386/57063241-7a1dc900-6cba-11e9-8d68-24bb5dad715d.png)

This change would make the tree with many nodes more easy to navigate using the keyboards.

**Comment by cagataycivici** [comment]
Fixed via PR
