### ISSUE TITLE
MenuBar without AutoDisplay: menu doesn't close when clicked (again)

### ISSUE THREAD

**Issue by Pranen** [primefaces/primeng#7621]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
The menubar (without Autodisplay) is not closing the menu-action-item after the selection/click.

**Expected behavior**
The menu-action-item is closed after the user has clicked the entry
(similar to https://www.primefaces.org/primeng-6.1.6/#/menubar)

**Minimal reproduction of the problem with instructions**
1. Go to https://www.primefaces.org/primeng/#/menubar
2. Click on the "Without Autodisplay"-Menu the File > Quit

Reproduced using Chrome v.73.*

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
