### ISSUE TITLE
[Spinner] 7.1.2 introduces incompatible changes to spinner control

### ISSUE THREAD

**Issue by earshinov** [primefaces/primeng#7624]
**I'm submitting a ...**

[x] bug report

There are numerous issues with PrimeNG 7.1.2 w.r.t. the spinner control, all of which stem from the fact that the underlying input type was silently changed from 'text' to 'number'.

This change itself should have been announced in the [changelog](https://github.com/primefaces/primeng/blob/master/CHANGELOG.md), because it, even if implemented properly, might affect library users and end users.

Bugs introduced by 7.1.2:
- https://github.com/primefaces/primeng/issues/7616 Spinner max length does not work in version 7.1.2
- `[size]` input no longer works (because `size` attribute is not applicable to numeric HTML inputs)
- https://github.com/primefaces/primeng/issues/7625 PrimeNG fails to pass values of `[min]`, `[max]` and `[step]` attributes to the underlying control, which makes Firefox to highlight inputs with decimal values as invalid.

This list is probably incomplete, because it is just what we have encountered in our project after upgrading.

So, there are at least 3 new bugs for fixed https://github.com/primefaces/primeng/issues/7445. It seems to me that https://github.com/primefaces/primeng/issues/7445 could have been fixed without changing the input type and bringing in so many new issues.

I am very disappointed with PrimeNG. A high-quality framework should not allow such things to go public, especially because it was a PATCH-level (7.1.x) release.

I recommend everyone to revert to / stay on 7.1.0 until the spinner control issues mentioned above are fixed.

**Comment by mertsincan** [comment]
Thanks a lot for the info. I'll check them.
