### ISSUE TITLE
No width below 175px possible in p-dropdown for PrimeNG 7.1.2

### ISSUE THREAD

**Issue by simdevmon** [primefaces/primeng#7626]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report 
[ ] feature request
[ ] support request
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-qcsxdu

**Current behavior**
If I define a width manually in a p-dropdown, it is not applied if the width is below 175px.

```
<p-dropdown [options]="items" [(ngModel)]="item"></p-dropdown> Default
<p-dropdown [options]="items" [(ngModel)]="item" [style]="{'width': '50px'}"></p-dropdown> 50px
<p-dropdown [options]="items" [(ngModel)]="item" [style]="{'width': '150px'}"></p-dropdown> 150px
<p-dropdown [options]="items" [(ngModel)]="item" [style]="{'width': '500px'}"></p-dropdown> 500px
```

**Expected behavior**
I would like to have a width below 175px and would expect that the width, which is set gets applied.

**Minimal reproduction of the problem with instructions**
See Plunkr demo:

![2019-05-03_10h36_40](https://user-images.githubusercontent.com/16277781/57127022-59737300-6d8f-11e9-96ad-b335674d606f.png)

* **Angular version:** 5.X
7.2.14

* **PrimeNG version:** 5.X
7.1.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 73

**Comment by JacobSiegle** [comment]
Same problem, I just tossed in the following to work around it.

// Fixes primeng default min width being too large
.ui-dropdown {
    min-width: 50px !important;
}

**Comment by simdevmon** [comment]
Thank you, the workaround is working for me. However it would be nice to have this included in the product.

**Comment by viandanteoscuro** [comment]
Simply add minWidth: 50px:

[style]="{'minWidth':'50px', 'width': '50px'}

**Comment by cagataycivici** [comment]
You need to override minwidth.
