### ISSUE TITLE
Support Angular 8

### ISSUE THREAD

**Issue by igorgiovannini** [primefaces/primeng#7627]
Issue #7306 has been closed, now I'm going to submit the same issue. The difference is that when the person reported this issue, Angular 8 was a beta version.
As right now we are at RC2, I think it makes sense to fix this issue.
However, there is another reason to fix the issue, independently to support or not support Angular 8: the import statement is simply wrong.

The problem resides in the TableComponent (table.ts).

I already tested the built package with an Angular 7 & Angular 8 application and I can confirm that it works.

**Comment by JaePhoenix** [comment]
Hi.
Can we please get a new release for this feature?

**Comment by jeffersonbezerra** [comment]
I think they will publish the release 8.0.0, when those issues are fixed/implemented https://github.com/primefaces/primeng/milestone/116

**Comment by JaePhoenix** [comment]
Understandable.  Thanks.

**Comment by sabithpocker** [comment]
@JaePhoenix 
Adding an alias in `tsconfig.json` might help. 
```
    "paths": {
      "@angular/core/src/metadata/*": ["./node_modules/@angular/core"]
    },
```

**Comment by cagataycivici** [comment]
Please see;

#7761

**Comment by dmytro-gokun** [comment]
@cagataycivici What about fixing this in 7.1.3 and publishing 7.1.4. This way we can migrate to Angular 8 right now and not wait until PrimeNg 8.0 is out?

**Comment by igorgiovannini** [comment]
@dmytro-gokun LOL, I don’t understand, the import statement is simply wrong, regardless of Angular 7/8... imho this should be fixed and then we can wait for the upgraded version with full Angular 8/Ivy Compiler support

**Comment by yghandor** [comment]
> @JaePhoenix
> Adding an alias in `tsconfig.json` might help.
> 
> ```
>     "paths": {
>       "@angular/core/src/metadata/*": ["./node_modules/@angular/core"]
>     },
> ```

this is fixed by issue but with ../node , Thanks

**Comment by sabithpocker** [comment]
> > @JaePhoenix
> > Adding an alias in `tsconfig.json` might help.
> > ```
> >     "paths": {
> >       "@angular/core/src/metadata/*": ["./node_modules/@angular/core"]
> >     },
> > ```
> 
> this is fixed my issue but with ../node , Thanks

Make sure you remove the same after PrimeNG 8 or a version with corrected import becomes available.
Another possible option would be to point `packae.json` to primeng#master as this is fixed in master.

**Comment by Petronious** [comment]
There is a simple workaround i've come with:

in package.json
```
"scripts": {
    "postinstall": "bash ./dev-tools/patch-ngprime-for-ivy.sh && ivy-ngcc",
```

```
cat dev-tools/patch-ngprime-for-ivy.sh
#!/bin/bash

#Replace an invalid import
sed -i 's/\@angular\/core\/src\/metadata\/lifecycle_hooks/\@angular\/core/' node_modules/primeng/components/table/table.d.ts
```

**Comment by sergey-morenets** [comment]
@igorgiovannini When will PrimeNG suppose to support Ivy mode?

**Comment by igorgiovannini** [comment]
> @igorgiovannini When will PrimeNG suppose to support Ivy mode?

I don't know, honestly I didn't yet updated to PrimeNG 8. I needed only the table, so I copied and fixed the code in my project in order to get this part working with Ivy Renderer.
