### ISSUE TITLE
Dropdown/MultiSelect control should be marked as touched after hiding the list

### ISSUE THREAD

**Issue by vimalraj-a** [primefaces/primeng#7629]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/github-axrphz

**Current behavior**

ng-touched class added to p-dropdown control when user clicks the dropdown (filter enabled).
**Expected behavior**

n-touched class should be added after onHide event instead of onBlur when filter is enabled
**Minimal reproduction of the problem with instructions**

``` html
<form [formGroup]="mainForm">
	<p-dropdown [options]="list" placeholder="Select" formControlName="name" filter="true"></p-dropdown>
</form>
```
Add validation to form control
``` typescript
public mainForm = new FormGroup({
    name: new FormControl(null, [Validators.required])
})
```
**What is the motivation / use case for changing the behavior?**

Our form validation is being ruined because of dropdown with filter. 
**Please tell us about your environment:**

* **Angular version:** 7.01

* **PrimeNG version:** 7.1.2

* **Browser:** all

 
* **Language:** all

* **Node (for AoT issues):** `node --version` =  v10.15.3

**Comment by sushmit-oodles** [comment]
Yes, I have a similar issue. here's my code:

```
    <div>
        <p-dropdown name="enterpriseId" [options]="enterpriseIdList" [filter]="true" filterPlaceholder="Select Enterprise ID"
            autofocus="true" required="true" #enterpriseIdDrpdwn="ngModel" [(ngModel)]="selectedEnterpriseId" (onChange)="onEnterpriseIdChange($event)"></p-dropdown>
        <label class="select-label" *ngIf="enterpriseName">/&nbsp;&nbsp;{{enterpriseName}}</label>
    </div>
    <div *ngIf="!enterpriseIdDrpdwn.valid && (enterpriseIdDrpdwn.touched || enterpriseIdDrpdwn.dirty)">
        <span class="error-message">Please select Enterprise Id.</span>
    </div>
```

my problem is when the dropdown is clicked the list is shown with filter input on top, now as soon as I click inside the filter input box the dropdown loses its focus and the error-message behind the list is rendered as "enterpriseIdDrpdwn.touched" becomes true. The problem will be solved if the dropdown stays untouched until the user clicks outside the list and dropdown list hides.
Please provide a workaround meanwhile.

Thanks
