### ISSUE TITLE
Improve keyboard navigation performance of Table

### ISSUE THREAD

**Issue by Devereux-Henley** [primefaces/primeng#7632]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

All keydown events in a table are handled explicitly by @HostListener-mounted event handlers in EditableColumn and SelectableRow directives. This causes excessive dirty checking in cell editors due to all keydown events, including text input entry, going through the Angular's customized event handling.

This can be fixed by more handling events explicitly, through `@HostListener('keydown.enter', ['$event'])` style handling instead of a switch in a `@HostListener('keydown', ['$event'])` style handler.

**Expected behavior**

Only events that are explicitly handled by EditableColumn and SelectableRow directives go through Angular dirty checking.

**What is the motivation / use case for changing the behavior?**

Performance improvement.

**Please tell us about your environment:**

* **Angular version:** 7.X

* **PrimeNG version:** 7.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by mmlitvin** [comment]
Agree !!
