### ISSUE TITLE
[ConfirmDialog] Add third, Cancel button

### ISSUE THREAD

**Issue by earshinov** [primefaces/primeng#7633]
**I'm submitting a ...**
```
[x] feature request
```

**Minimal reproduction of the problem with instructions**

Currently ConfirmDialog only supports two buttons: Accept and Reject.

In several cases a third, Cancel button could be useful.

Take a look at options provided by WinAPI [MessageBox](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-messagebox) function:

```
MB_ABORTRETRYIGNORE
MB_CANCELTRYCONTINUE
...
MB_YESNOCANCEL
```

It is impossible to implement scenarios covered by these options using PrimeNG's ConfirmDialog, because it is limited to two buttons.

To illustrate, if I need to ask the user about unsaved changes when they are about to leave the page, I would like to display some sort of a MB_YESNOCANCEL dialog:

```
Unsaved changes
----------------------------

Do you want to save changes?

         [Yes] [No] [Cancel]
```

I have prepared a draft implementation:
https://stackblitz.com/edit/primeng-confirmdialog3

**Please tell us about your environment:**

* Angular version: 7.2.8
* PrimeNG version: 7.1.0
* Browser: all
* Language: TypeScript 3.3

**Comment by RobSchripsema** [comment]
I second this request!

**Comment by jacks-bush** [comment]
I third this request, but for the Confirm Popup as well. We use the Confirm Popup a lot in our UI and have a situation where we need two confirm buttons - 'Save', 'Save New Revision', and 'Cancel'. I'm surprised this hasn't gotten asked for more often. The Confirm popup is already super useful, but it would be even better if it were a bit more flexible with the number of buttons it can display.

**Comment by eXpertise7** [comment]
+1 @jacks-bush We need the same.

**Comment by gitadam0** [comment]
any solution?

**Comment by Zokky2e** [comment]
> any solution?
@gitadam0 

I found out you can add buttons to the p-footer of your p-confirmDialog, repopulating it with more than the 2 default buttons, and with your custom function based on value do what you need save it into a global variable, then calling confirmation.accept finish the accept function. Code bellow is a snippet of what I worked on:
```
//myconfirm.component.html
<p-confirmDialog #confirmation appendTo="body" header="Confirm delete">
	<p-footer>
		<div>
			<button type="button" (click)="acceptWithDelete(true)">Yes, and delete related events</button>		
			<button type="button" (click)="acceptWithDelete(false)">Yes, but keep related events</button>			
			<button type="button" (click)="confirmation.reject()">No</button>  
		</div>
	</p-footer>
</p-confirmDialog>

```

and codebehind:
```
//myconfirm.component.ts
//...
private shouldDeleteEvents: boolean;
private acceptWithDelete(value: boolean = true) {
	this.shouldDeleteEvents = value;
	this.confirmDialog.accept();
}

private async onDeleteEventsConfirm() {
	this.confirmationService.confirm({
		message: "Are you sure?",
		header: 'Confirm delete',
		rejectVisible: false, //this is important to override the default buttons
		acceptVisible: false, //this is important to override the default buttons
		acceptLabel: 'Yes',
		accept: () => {
			//delete logic using this.shouldDeleteEvents variable
		}
	});
}
//...
```
