### ISSUE TITLE
 Table Checkbox Selection plus pagination - inconsistent styling

### ISSUE THREAD

**Issue by lroitman** [primefaces/primeng#7635]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
The below plunker illustrates how to reproduce the bug

https://stackblitz.com/edit/github-bxjcox

**Current behavior**
I have a table with a paginator and multiple checkbox selection, pSelectableRowDisabled set to true. When I select row(s) with the checkbox the rows show as selected (ui-state-highlight is applied to the selected rows) 
Now, when I switch to the second page, and then go back to the first, the rows lose their ui-state-highlight, the rows show with default (non-selected) styling, while the selection is being preserved (all the correct checkboxes are checked). 
But, when I click on another checkbox, all the selected rows become highlighted again

**Expected behavior**
I expect some consistency. When the row is selected with checkbox its styling shouldn't change when I switch between pages

**Please tell us about your environment:**

* **Angular version:** latest

* **PrimeNG version:** latest

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by ctrl-d** [comment]
not that i like it, but for a hack for now i got it to work 

here is a sample

https://stackblitz.com/edit/github-bxjcox-ct1qcc

**Comment by cagataycivici** [comment]
Row Selection and Column Checkbox selection are not supported to be used together.
