### ISSUE TITLE
[ConfirmDialog] Make Confirmation.message optional

### ISSUE THREAD

**Issue by earshinov** [primefaces/primeng#7637]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```

In the `ConfirmationInterface`, https://github.com/primefaces/primeng/blob/9b05c25143aaca764d01627bda0e854479039c54/src/app/components/common/confirmation.ts#L4, the `message` field should be declared optional:

```diff
-    message: string;
+    message?: string;
```

The message can be set via the corresponding input of the ConfirmDialog component: https://github.com/primefaces/primeng/blob/9b05c25143aaca764d01627bda0e854479039c54/src/app/components/confirmdialog/confirmdialog.ts#L57

```
<p-confirmDialog key="test" header="Header" message="Message"></p-confirmDialog>
```

**Please tell us about your environment:**

* Angular version: 7.2.8
* PrimeNG version: 7.1.2
* Browser: all
* Language: TypeScript 3.2.4

**Comment by cagataycivici** [comment]
Added in 9.0.3
