### ISSUE TITLE
[Table] Filtering with ChangeDetectionStrategy.OnPush show the previous state

### ISSUE THREAD

**Issue by rafa-as** [primefaces/primeng#7640]
**I'm submitting a ...** 
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Stackblitz project: https://stackblitz.com/edit/table-error-onpush
Demo APP: https://table-error-onpush.stackblitz.io

The error is on the **src/app/components/table/table.ts:1234** :

``` Typescript
this.filteredValue.push(this.value[i]);
```

should be:

``` Typescript
this.filteredValue = [...this.filteredValue, this.value[i]];
```

**Current behavior**
When filter with ChangeDetectionStrategy.OnPush, the table shown inconsistent data (the previous state, not the current).

**Expected behavior**
The table show the new values properly without any extra implementation.

**Minimal reproduction of the problem with instructions**
Use the table component inside another one with **ChangeDetectionStrategy.OnPush** active

**Please tell us about your environment:**
MAC OS X Mojave 10.14.4
WebStorm 2019.1.2
Yarn 1.15.2

* **Angular version:** 7.2.1

* **PrimeNG version:** 7.1.2

* **Browser:** all
 
* **Language:** all

**Comment by cagataycivici** [comment]
Duplicate https://github.com/primefaces/primeng/issues/6236
