### ISSUE TITLE
hideOnDateTimeSelect is not respected when showTime is false

### ISSUE THREAD

**Issue by quasiunafantasia** [primefaces/primeng#7642]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/angular-jap4xx?file=src%2Fapp%2Fapp.component.html
as you can see, `hideOnDateTimeSelect` is not respected

**Current behavior**

Its impossible to keep the calendar opened after selecting a date when `showTime` is false
As you can see from https://github.com/primefaces/primeng/blob/master/src/app/components/calendar/calendar.ts#L744 the `hideOnDateTimeSelect` is not respected in case `showTime` is falsy
as a user i have no ability to open today`s date without closing the overlay. It would be a useful thing though.
**Expected behavior**

`hideOnDateTimeSelect` setting is respected even when `showTime` setting is false
**Minimal reproduction of the problem with instructions**
Open the demo, try to select today`s date/any date without closing the overlay

**What is the motivation / use case for changing the behavior?**

Like the job you do, expect some flexibility for this behavior though

**Please tell us about your environment:**

* **Angular version:** 5.X

* **PrimeNG version:** 5.X

* **Browser:** [all ]

 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =   irrelevant

**Comment by quasiunafantasia** [comment]
In case someone else needs a custom button to reset date, i am using the following code
```
  onTodayClick() {
    const date: Date = new Date();
    const dateMeta = {
      day: date.getDate(),
      month: date.getMonth(),
      year: date.getFullYear(),
      otherMonth:
        date.getMonth() !== this.pcalendar.currentMonth ||
        date.getFullYear() !== this.pcalendar.currentYear,
      today: true,
      selectable: true
    };
    if (dateMeta.otherMonth) {
      this.pcalendar.currentMonth = dateMeta.month;
      this.pcalendar.currentYear = dateMeta.year;
      this.pcalendar.createMonths(this.pcalendar.currentMonth, this.pcalendar.currentYear);
    }

    if (this.pcalendar.shouldSelectDate(dateMeta)) {
        this.pcalendar.selectDate(dateMeta);
    }
  }
```
which is a 90% copy-paste from original handling :(

**Comment by ratbeard** [comment]
I'm experiencing this too.

Debugging it, I'm seeing that

`this.el.nativeElement.contains(event.target)` is returning false on line https://github.com/primefaces/primeng/blob/6df9fd234dc9e93436cc7449761b0f0b210bd4c4/src/app/components/calendar/calendar.ts#L2103

The `<a>` day I clicked on which is the `event.target` seems to no longer be present in the DOM, so the that returns false.  I think a re-render has run since the initial event, causing a new `<a>` to be created in its place?

**Comment by cagataycivici** [comment]
Default value is also true now.
