### ISSUE TITLE
[Multiple Calendar] Calendar not pop up again if unselect all the dates

### ISSUE THREAD

**Issue by xp0515** [primefaces/primeng#7644]
**Current behavior**

In the Multiple Calendar. If I open the pop up and select a single day or several days, once I unselect all the dates and click the blank space on the page to close the pop up, I'm not able to open the pop up again. There is no response if I click the input area while the calendar is supposed to pop up again. It's not even working on the offical website. https://www.primefaces.org/primeng/#/calendar

**Expected behavior**

**Please tell us about your environment:**
I've tried chrome, safari, ie, none of them works.

**Comment by miacrd** [comment]
I have the same issue. I've figured it's because the component has a problem when the array is empty, instead of null. A work around: define a function for the close event, check for an empty array and sub for a null if so.

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
