### ISSUE TITLE
PrimeNG Dropdown and InputSwitch Unit Testing

### ISSUE THREAD

**Issue by jeraldstanislaus** [primefaces/primeng#7647]
Hi team,

I am struggled with Angular PrimeNg Test cases for Dropdown and InputSwitch. Can anyone give some basic Unit testing examples for those things?

InputSwitch :
<p-inputSwitch [(ngModel)]="wallboxData.enabled" class="settings-toggle-body-input" (onChange)="alterChargePointState($event, wallboxData.id)"></p-inputSwitch>

Dropdown  : 
<p-dropdown [options]="usageView" [(ngModel)]="selectedUsageView" optionLabel="name" class="usageView" (onChange)="plotMyWallboxesChart()"></p-dropdown>

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.
