### ISSUE TITLE
RC5- TypeError Cannot read property 'type' of null

### ISSUE THREAD

**Issue by ejcastillo** [primefaces/primeng#765]
Whenever I add the DataTable, Column or UIChart to the imports array of an ngModule I get the error message above.

**Comment by NDMO** [comment]
What was the solution here?

**Comment by ejcastillo** [comment]
PrimeNG had not updated their docs for ngModule. This issue is fixed when you add DataTableModule to your directives instead of DataTable. Thanks and apologies.
