### ISSUE TITLE
ScrollableView.prototype.hasVerticalOverflow() Threshold processing error。

### ISSUE THREAD

**Issue by qiyus** [primefaces/primeng#7650]
**Current behavior**
When horizontal scrollbar and vertical scrollbar exist, ScrollableView.prototype.hasVerticalOverflow() returns false.

**Expected behavior**
When horizontal scrollbar and vertical scrollbar exist, ScrollableView.prototype.hasVerticalOverflow() returns true.

* **Angular version:** 5.X

6.0.3

* **PrimeNG version:** 5.X
6.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 74.0.3729.131
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript ~2.8.4

* **Node (for AoT issues):** `node --version` =   
8.9.1

suggest：
 hasVerticalOverflow() {
        return DomHandler.getOuterHeight(this.scrollTableViewChild.nativeElement) > DomHandler.getOuterHeight(this.scrollBodyViewChild.nativeElement);
    }

=>

 hasVerticalOverflow() {
        return this.scrollBodyViewChild.nativeElement.scrollHeight > this.scrollBodyViewChild.nativeElement.clientHeight;
    }

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
