### ISSUE TITLE
Horizontal scrolling at the bottom of p-table (with virtual scroll) triggers lazyLoad event

### ISSUE THREAD

**Issue by filip12345678910** [primefaces/primeng#7657]
Horizontal scrolling at the bottom of p-table (with virtual scroll) triggers lazyLoad event for no reason. Preview:
https://stackblitz.com/edit/github-sxsjrz?file=src%2Fapp%2Fapp.component.html

It is especially painful, when the table has only one wide row, because the row always disappears for a while whenever I scroll horizontally.

This issue duplicates this issue: https://github.com/primefaces/primeng/issues/7207
I thought maybe you gave up on that issue, because the description was too complicated, so I created a new issue with example on stackblitz.com.

**Comment by fhljys** [comment]
Is there any update for this issue?

**Comment by filip12345678910** [comment]
no

**Comment by cagataycivici** [comment]
Tracked at https://github.com/primefaces/primeng/issues/7657
