### ISSUE TITLE
emptyMessage template is duplicated if table has frozen columns

### ISSUE THREAD

**Issue by thaihacong** [primefaces/primeng#7658]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-1rdwju

**Current behavior**
Given a turbo table with frozen columns.
Click "Empty cars" to remove all records from the table.
Then, emptyMessage template appears in both frozen and unfrozen parts of the table.

![turbotable-emptyMessage](https://user-images.githubusercontent.com/8019304/57456869-b3cc7200-726e-11e9-8ef8-46019862ecb8.png)

**Expected behavior**
emptyMessage template should appear only once, either in frozen part, or in unfrozen part.
It would be nice if this can be controllable via an user input boolean flag.

**Please tell us about your environment:**

* **Angular version:** 7.2.8

* **PrimeNG version:** 7.1.2

**Comment by cagataycivici** [comment]
8.0.2 passes frozen parameter so you can customize the message e.g.

```xml
<ng-template pTemplate="emptymessage" let-columns let-frozen="frozen">
        <tr>
            <td [attr.colspan]="columns.length">
                {{frozen ? 'No records found' : '&nbsp;'}}
            </td>
        </tr>
    </ng-template>
```

**Comment by MathanM** [comment]
Is it possible to fix same issue for tree table?
