### ISSUE TITLE
Only Angular 2.0.0-rc.5 is supported ?

### ISSUE THREAD

**Issue by StefH** [primefaces/primeng#766]
Only Angular 2.0.0-rc.5 is supported ?

When using the datagrid example from 'primeng-quickstart-webpack' inside a Angular 2.0.0-rc.4 project (https://github.com/AngularClass/angular2-webpack-starter) I get error.

**Comment by kartheininger** [comment]
If you cannot upgrade currently to Angular rc5, just use primeng version 1.0.0-beta.11. (This combination does work in our project)
I think it doesn´t make sense to make new releases of primeng compatible with older versions of angular 2.

**Comment by StefH** [comment]
No problems anymore, that related project has also been upgraded to 5
