### ISSUE TITLE
PrimeNg TreeTable ContextMenu and Checkbox selection issue

### ISSUE THREAD

**Issue by ymasha** [primefaces/primeng#7661]
I have a problem using ContextMenu and Checkbox. Context menu row selecting using right click not clearing after table row selection using the left click.

that's what I tried... there is the way to use mixing mode for context menu by passing contextMenuSelectionMode="joint"

<p-treeTable[columns]="cols" [value]="files"  [(selection)]="selectedNode" [contextMenu]="cm" **contextMenuSelectionMode="joint"**>
The problem with this approach is that I am losing row selection on the context menu and the requirements for this feature to show selection on Context menu row.

How to change table row selection on the left mouse click.

There is the link for stackblitz project:

https://stackblitz.com/edit/contextmenu-and-checkbox

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
