### ISSUE TITLE
WAI-ARIA support level of p-table, p-tableCheckbox and p-tableHeaderCheckbox

### ISSUE THREAD

**Issue by pshahidi** [primefaces/primeng#7662]
This is more like a question at this point, but these component not mentioned in the wiki:
p-table, p-tableCheckbox and p-tableHeaderCheckbox
https://github.com/primefaces/primeng/wiki/Accessibility
I was wondering if they where tested for accessibility. Also wondering what it means when it's stated that component such p-inputSwitch tested and complying and graded, how is it done, if I use aria-label on p-inputswitch  that would be all needed (I don't see that aria-label is applied to the hidden input element for example, I also use this chrome plugin to see accessibility issues on my pages: 
http://wave.webaim.org/
What do you recommend to test the pages with

**Comment by yigitfindikli** [comment]
fixed https://github.com/primefaces/primeng/commit/a8982fd7b57d1b24aee08f28a37271739874c9c7
