### ISSUE TITLE
Accessibility: SortIcon calculates aria text, but does not bind the template to it

### ISSUE THREAD

**Issue by matthiasblaesing** [primefaces/primeng#7669]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When setting `ariaLabel`, `ariaLabelAsc` and `ariaLabelDesc` properties on sortIcon, no `aria-label` is created.

**Expected behavior**
The `aria-label` attribute should show the text, that matches the associated property.

**What is the motivation / use case for changing the behavior?**
Support visible impaired users.

* **PrimeNG version:** 7.1.2

* **Browser:** all
 
* **Language:** all

**Comment by cagataycivici** [comment]
Focus is applied to the th element so aria props should be there.

https://github.com/primefaces/primeng/issues/7766
