### ISSUE TITLE
Can't bind to 'model' since it isn't a known property of 'p-menu'.

### ISSUE THREAD

**Issue by RaviMovva** [primefaces/primeng#767]
When I am trying to integrate the p-menu component into the new RC-5 version of beta-13 I am getting the following error :

polyfills.js:7225 Unhandled Promise rejection: Template parse errors:
Can't bind to 'model' since it isn't a known property of 'p-menu'.
1. If 'p-menu' is an Angular component and it has 'model' input, then verify that it is part of this module.
2. If 'p-menu' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
 ("
<p-menu [ERROR ->][model]="items"></p-menu>
"): AppComponent@5:8 ; Zone: <root> ; Task: Promise.then ; Value: 

Can some body help ?

**Comment by buddyackerman** [comment]
Check to see if your issue is the same as the one in [this thread](http://forum.primefaces.org/viewtopic.php?f=35&t=46690).

**Comment by RaviMovva** [comment]
Thanks for the reply will check and confirm.

**Comment by sbox99** [comment]
I have the exact some problem.
Did you get a resolution?

**Comment by buddyackerman** [comment]
@sbox99 did you check the thread that I referenced in my post?  Was your issue the result of upgrading from RC4 to a newer release?

**Comment by RaviMovva** [comment]
the datatable  is working fine. I think primeng group should respond what
is missing with this basic use cases.

**Comment by sbox99** [comment]
I have a project that was with RC4 and tried to use primeng but couldn't get anything to run. To troubleshoot the issue I though I would try a clean install and use the primeng quickstart app through npm install. Everthing installed nicely and I got the primeng datatable of cars no problem. However, as soon I as I tried to add another ui object such as a <p-menu> I got the "Can't bind to 'model' since it isn't a known property of 'p-menu'" message. I have checked that the modules are imported correctly and all seems good. I must be missing something obvious cuz I.m pretty new to this. Any help would be much appreciated.

**Comment by buddyackerman** [comment]
@sbox99 Can you create a plnkr that illustrates the problem?

**Comment by mmlitvin** [comment]
RaviMovva, 
Did you figure out the solution by chance? I have exact same problem. 
Thanks.

**Comment by mmlitvin** [comment]
Mine is: 
main.ts:8 Error: Template parse errors:
Can't bind to 'model' since it isn't a known property of 'p-autocomplete'.
1. If 'p-autocomplete' is an Angular component and it has 'model' input, then verify that it is part of this module.
2. If 'p-autocomplete' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("k">
                        <dbm-rcl-table></dbm-rcl-table>
                        <p-autocomplete [ERROR ->][(model)]="inputText"

**Comment by ctrl-brk** [comment]
Do you have AutoCompleteModule in your module's imports?

**Comment by mmlitvin** [comment]
I did. 
Upgrading to most recent versions of Angular2 and primeng solved it.

	"dependencies": {
		"@angular/core": "~2.1.0",
		"@angular/common": "~2.1.0",
		"@angular/platform-browser": "~2.1.0",
		"@angular/platform-browser-dynamic": "~2.1.0",		
		"@angular/compiler": "~2.1.0",
		"@angular/upgrade": "~2.1.0",
		"@angular/router": "~3.1.1",
        "@angular/forms": "~2.1.0",
        "@angular/http": "~2.1.0",
        
        "angular-in-memory-web-api": "~0.1.5",
		"primeng": "1.0.0-beta.20",
	........................
	},

**Comment by buckrogerz** [comment]
I am also seeing the same issue - tried updated the versions as specified by mmlitvin but still same thing

**Comment by nickraphael** [comment]
I'm getting this error in Karma

**Comment by elvinmeza** [comment]
same here

**Comment by Elitro** [comment]
I solved it by importing both PanelMenuModule and MenuModule and adding them to the imports in TestBed.

**Comment by fiee** [comment]
To make it more explicit: Add the conflicting module to `@NgModule`’s `imports`, like this:

    @NgModule({
        imports: [
            BrowserModule,
            FormsModule,
            ReactiveFormsModule,
            RouterModule.forRoot(routes),
            AccountsModule,
            Ng2PaginationModule,
            // PrimeNG
            InputTextModule, DataTableModule, ButtonModule, DialogModule,
            CheckboxModule, DataListModule, MenubarModule
        ],

This solved the problem for me.

**Comment by saurav12** [comment]
I am using MenuModule only, still getting the same issue. PrimeNG team please reply.

**Comment by saiidabs** [comment]
Anyone get the fix?

**Comment by TekSiDoT** [comment]
In my case, this error occured using Angular/Cli together with PrimeNG during karma unit tests. After a lot of fiddling I found that adding FormsModule within the respective tests enabled them to run properly:

add:
`import { FormsModule } from '@angular/forms';`

and:
```
TestBed.configureTestingModule({
  declarations: [
    AppComponent,
    YourComponent
  ],
  imports: [
    InputSwitchModule, // Or whatever PrimeNG Module you're attempting to use
    FormsModule
  ]
});
```

**Comment by billfranklin** [comment]
It's a simple fix for PrimeNG to add 
schemas: [ CUSTOM_ELEMENTS_SCHEMA ]
to the @NgModule declaration for each component.  This will fix testing for all of these components.

**Comment by billfranklin** [comment]
@TekSiDoT good find.  Was irritating having to add the Schemas: [CUSTOM_ELEMENTS_SCHEMA] for all the tests to pass.  Much more concise this way.

**Comment by lekhnath** [comment]
@TekSiDoT saved my day

**Comment by sudheerj** [comment]
Not able to replicate the issue in latest versions. Please comment out for any concerns.

**Comment by ravi-kadam** [comment]
import following items to your module 

```
import {StepsModule, MenuItem} from 'primeng/primeng';
@NgModule({
    imports: [....  , StepsModule],
```

**Comment by denismp** [comment]
I am running into this problem.  I don't understand the solution proposed in the link above.  Can someone give me the step by step instructions?

**Comment by sandeepshivathaya** [comment]
I am running on Angular 5 and primeNg 5. Tried all the solution mentioned above and still have the same problem.

**Comment by EleanorHughes** [comment]
I am having the same issue with Angular and PrimeNG 5

**Comment by niltonjacintho** [comment]
Me too!
The same issue  when i try to use p-panelMenu!

**Comment by sataqi** [comment]
Had same issue, solved it by moving the **`import`** from a sub module to imports of **`app.module.ts`**

**Comment by Stefaneek** [comment]
I have a problem to PrimeNg, I am using Angular: 5.2.9. I have installed PrimeNg according to this documentation https://www.primefaces.org/primeng/#/setup

I have already added dependencies and styles as they showed and when I am using for example `p-splitButton`

I get such error

> p-splitButton' is not a known element: or Can't bind to 'model' since it isn't a known property of 'p-splitButton'.


I can't even use the button because it's displayed as a normal grey button and I am not able to display a button with the fa-icon.

**Comment by Stefaneek** [comment]
Guys if you are using Shared module add your imports directly to that module to which your components belongs, not only to app.module in my case that was a key.

**Comment by yagizayer** [comment]
importing address has been changed from,
import { PanelModule } from 'primeng/primeng';
to,
import { PanelMenuModule } from 'primeng/panelmenu';

**Comment by simplecodeexamples** [comment]
the problem is specifically with FormModule if you does not import it no input element will be able to define [{ngModel}] in it

**Comment by oarrthur** [comment]
Same here...
Foi o primeiro componente que testei, já deu vontade de desistir...

**Comment by LeonardoWiest** [comment]
Não desista @oarrthur. PrimeNG é incrível.
