### ISSUE TITLE
Autocomplete won't emit onClear after erasing input value with forceSelection

### ISSUE THREAD

**Issue by FernandaGM** [primefaces/primeng#7672]
**I'm submitting a ...**
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-csy685

**Current behavior**
After some value is selected in the autocomplete component  and you erase the input value the onClear event won't emit. When writing something and losing focus the event is emitted but not if you erase everything.

**Expected behavior**
The onClear event should be emitted even if the input value is an empty string.

**Minimal reproduction of the problem with instructions**
1 - Select any option by typing or with dropdown;
2 - Erase the whole input string;
3 - The validation below the input should be true.

**What is the motivation / use case for changing the behavior?**
To be able to control the forms objects properly

Angular version: 7.2.12

PrimeNG version: 7.1.0

Browser: [all]

Language: [all]

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
