### ISSUE TITLE
Picklist Target container wrong height size.

### ISSUE THREAD

**Issue by Fridthjof** [primefaces/primeng#7673]
Current Waiting Time: ~8 weeks.

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
```
<p-pickList [responsive]="true" dragdrop="true" filterBy="label" [showTargetFilter]="false"
            [source]="listOfProductComparions" [target]="listOfTargetProductComparions" [showSourceControls]="false" [showTargetControls]="false">
                    <ng-template let-comparison pTemplate="item">
                        <div class="ui-helper-clearfix">
                            {{comparison.label}}
                        </div>
                    </ng-template>
</p-pickList>
```

**Current behavior**
When using picklist and setting a filter on the Source only, with responsive true. The target container is not filling out the height, so they are same size. (Not responsive) 

Note. Using serenity. 

**Expected behavior**
Expected it to be the same size as the source container, including the filter.

**Please tell us about your environment:**

Win 10, Jetbrains IDE.

* **Angular version:** 5.X
7.2

* **PrimeNG version:** 5.X
7.0
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript.

* **Node (for AoT issues):** `node --version` =

**Comment by Merve7** [comment]
Hi,
Please use "targetStyle" attribute for height size (like [targetStyle]="{'height':'250px'}"). You can use [targetStyle]="{'height':'210px'}" for default. Also, you can calculate height from .ui-picklist-list class height and filter container height (for default; .ui-picklist-list->height:12.5em + filter container height 35px)
