### ISSUE TITLE
p-autoComplete - ERROR TypeError: jit_nodeValue_19(...) is not a function

### ISSUE THREAD

**Issue by flaviomirandadesouza** [primefaces/primeng#7678]
Good morning, I'm implementing autocomplete in my application and it is displaying the following error:

> ERROR TypeError: jit_nodeValue_19(...) is not a function
>     at Object.eval [as handleEvent] (ng:///AppModule/AnuncianteFormularioComponent.ngfactory.js:278)
>     at handleEvent (vendor.js:70805)
>     at callWithDebugContext (vendor.js:71875)
>     at Object.debugHandleEvent [as handleEvent] (vendor.js:71602)
>     at dispatchEvent (vendor.js:68254)
>     at vendor.js:69744
>     at SafeSubscriber.schedulerFn [as _next] (vendor.js:61225)
>     at SafeSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub (vendor.js:125473)
>     at SafeSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next (vendor.js:125411)
>     at Subscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next (vendor.js:125354)

anunciante-formulario.component.html

`<p-autoComplete [(ngModel)]="document.name" [suggestions]="results" (completeMethod)="search($event)">`

anunciante-formulario.component.ts

```
results: string[];
search(event) {
   this.results = ['Flavio', 'Souza'];
}
```

Has anyone else had this problem that might help me?

Thank you.

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.
