### ISSUE TITLE
pTooltip

### ISSUE THREAD

**Issue by morozp** [primefaces/primeng#7679]
pTooltip   has not correct position when it set on svg.path
   <svg [attr.width]="width" [attr.height]="height">
          <g    style="transform: translate(50%,50%);">
            <path *ngFor="let arcItm of arcs"
             
              pTooltip="Enter your username"

Rendered but has ho correct position

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
