### ISSUE TITLE
DataTableModule should import InputTextModule

### ISSUE THREAD

**Issue by ilianiv** [primefaces/primeng#768]
`DataTableModule` should import `InputTextModule` because it uses `pInputText` directive for filters for example: [link](https://github.com/primefaces/primeng/blob/master/components/datatable/datatable.ts#L196)

The result is an ugly input:
![image](https://cloud.githubusercontent.com/assets/3925630/17886137/268eb700-6929-11e6-8a00-fa44ac9eded2.png)

**Comment by oxeno** [comment]
@cagataycivici was this fixed in the recent release?

**Comment by cagataycivici** [comment]
Added with your PR, thanks.
