### ISSUE TITLE
Checkbox binary property is treated like a boolean, declared as string and documented as boolean

### ISSUE THREAD

**Issue by plathub** [primefaces/primeng#7681]
Documentation for checkbox binary property should be consistent with the effective declaration type.

https://github.com/primefaces/primeng/blob/8863411311915af4d441fcbce0b7145ca8a21e07/src/app/components/checkbox/checkbox.ts#L38

**Comment by stonecourier** [comment]
Found the same problem. When you turn on angular strict checking, it raises this as an error.
