### ISSUE TITLE
p-fullCalendar, No available FullCalendar view plugins

### ISSUE THREAD

**Issue by alkismavridis** [primefaces/primeng#7682]
We get the following error message after trying to show p-fullcalender:

```
ERROR Error: No available FullCalendar view plugins.
at reduceDateProfile (main.js:5699)
    at reduce (main.js:5661)
    at Calendar.reduce (main.js:6790)
    at Calendar.dispatch (main.js:6748)
    at main.js:6721
    at Calendar.batchRendering (main.js:6811)
    at Calendar.hydrate (main.js:6718)
    at new Calendar (main.js:6620)
    at FullCalendar.push../node_modules/primeng/components/fullcalendar/fullcalendar.js.FullCalendar.initialize (fullcalendar.js:66)
    at FullCalendar.push../node_modules/primeng/components/fullcalendar/fullcalendar.js.FullCalendar.ngAfterViewChecked (fullcalendar.js:31)
```

Our json-package contains this:
```
"@fullcalendar/core": "^4.1.0",
"@fullcalendar/daygrid": "^4.1.0",
"@fullcalendar/interaction": "^4.1.0",
"@fullcalendar/timegrid": "^4.1.0",
"fullcalendar": "^4.0.0-alpha.2",
```

We use the following in our template:
`<p-fullCalendar [events]="events"></p-fullCalendar>
`

The error comes when the component is rendered on the page.

**Comment by ayushman1024** [comment]
You have to use [options] with p-fullCalenar .

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.

**Comment by alkismavridis** [comment]
I had used options too, I just thought that it would complicate more the issue description.
I was able to solve the problem by adding the following properties to my options:

`plugins: [dayGridPlugin, timeGridPlugin, interactionPlugin],`

where
```
import dayGridPlugin from '@fullcalendar/daygrid';
import timeGridPlugin from '@fullcalendar/timegrid';
import interactionPlugin from '@fullcalendar/interaction';
```
Before updating to version 7.1 this field was not necessary, but after updating it was.
I document this solution in case someone else faces the same problem.

**Comment by SoumayaBessifi** [comment]
Je suis bloqué dans le même problème et je voulais savoir où as-tu ajouter les propriétés des plugins?

**Comment by SoumayaBessifi** [comment]
Je suis bloqué dans le même problème et je voulais en savoir où as-tu ajouter la propriété des plugins ?.

**Comment by SoumayaBessifi** [comment]
Je suis bloqué dans le même problème et je voulais savoir où ajouter la propriété des plugins?.

**Comment by mertsincan** [comment]
Yes, please use plugins option with new fullCalendar API. Please see doc;
https://fullcalendar.io/docs/upgrading-from-v3

Exp;
````
import dayGridPlugin from '@fullcalendar/daygrid';
import timeGridPlugin from '@fullcalendar/timegrid';
import interactionPlugin from '@fullcalendar/interaction';

ngOnInit() {
        ...
        
        this.options = {
            plugins:[ dayGridPlugin, timeGridPlugin, interactionPlugin ],
            defaultDate: '2017-02-01',
            header: {
                left: 'prev,next',
                center: 'title',
                right: 'dayGridMonth,timeGridWeek,timeGridDay'
            },
            editable: true
        };
    }


<p-fullCalendar [options]="options"></p-fullCalendar>
```

**Comment by aprsn** [comment]
using [options] solved the problem, thanks
