### ISSUE TITLE
p-calendar can not set null value

### ISSUE THREAD

**Issue by DanielYKPan** [primefaces/primeng#7683]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Waiting Time: ~8 weeks.

**I'm submitting a ...**  (check one with "x")
```
[ *] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**

In the primeNG website (http://primefaces.org/primeng/#/calendar), the **'Basic'** example doesn't accept null value. This issue only exists on the latest primeNG version (7.1.3). ( The issue does not exist in prmeNG v7.1.2. )

**Expected behavior**

p-calendar accept null value

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 7.2.15

* **PrimeNG version:** 7.1.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by namnhcntt** [comment]
I faced same issue. Do we have plan for fix this?

**Comment by MakesNine** [comment]
The issue still exists with PrimeNG 8.0.0.  This is an annoying bug for users and it brakes our automated e2e tests for forms with PrimeNG Calendar components.

**Comment by epoch79** [comment]
yeah we are waiting...

**Comment by cagataycivici** [comment]
#7897
