### ISSUE TITLE
7.1.3 . ie-11

### ISSUE THREAD

**Issue by mthor** [primefaces/primeng#7687]
with the latest update, on ie 11, in order for a grid to load, you have to click the mouse, and each time then a row will load.

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Comment by mthor** [comment]
"mthor commented on May 14, 2019". 

 **impressive response time**.
