### ISSUE TITLE
p-table with lazy loading and multiple sort - behaves like a single sort

### ISSUE THREAD

**Issue by SaraPrager** [primefaces/primeng#7689]
**I'm submitting a bug report**

**Current behavior**
HTML:
`<p-table [columns]="cols" [value]="logRecords" [paginator]="true" [rows]="30" [totalRecords]="totalRecords"
 [lazy]="true" (onLazyLoad)="loadLogRecordsLazy($event)" [loading]="loading" [responsive]="true" sortMode="multiple">`

Type Script:
`sortBy = [];
  loadLogRecordsLazy(e) {
    this.sortBy = [];
    if (e.multiSortMeta) {
      e.multiSortMeta.forEach(sortElement => {
        let sortStr = sortElement.field;
        if (sortElement.order == -1) {
          sortStr = '-' + sortStr;
        }
        this.sortBy.push(sortStr);
      });
    }
// ... Request server sorting
  }
`
The problem: e.multiSortMeta always contains only one item - the last clicked column. No way to support multi sorting!

**Expected behavior**
e.multiSortMeta should contain all the sort fields, not only the last field.

* **Angular version:** 7.X
* **PrimeNG version:** 7.1.3

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

Please also make sure metaKey is pressed.
