### ISSUE TITLE
Hammer.js missing

### ISSUE THREAD

**Issue by zigzag95** [primefaces/primeng#769]
I'm using webpack 1 and angular rc5 and added 
 "@types/hammerjs": "^2.0.28" in my package.json

I get this error
EXCEPTION: Error in ./DataTable class DataTable - inline template
ORIGINAL EXCEPTION: Hammer.js is not loaded, can not bind dragstart event

**Comment by Efactor888** [comment]
I am getting a similar error. Not sure what to do, been trying to debug this for over a day...

angular rc5.

zone.js:461 Unhandled Promise rejection: EXCEPTION: Error in ./DataTable class DataTable - inline template:22:190
ORIGINAL EXCEPTION: Hammer.js is not loaded, can not bind dragstart event
ORIGINAL STACKTRACE:
Error: Hammer.js is not loaded, can not bind dragstart event
    at new BaseException (http://localhost:4200/vendor/@angular/platform-browser/src/facade/exceptions.js:27:23)
    at HammerGesturesPlugin.supports

**Comment by cagataycivici** [comment]
Duplicate of #784.

Do you experience same at live showcase?

**Comment by zigzag95** [comment]
Solved after adding hammer plugin in webpack config

**Comment by PYYuriy** [comment]
Can you sand example of solution, because I have the same error

**Comment by Efactor888** [comment]
Thank you.
