### ISSUE TITLE
AOT compile error, Table declared twice eventhough not importing TableModule

### ISSUE THREAD

**Issue by Tahiche** [primefaces/primeng#7691]
Original issue (closed): https://github.com/primefaces/primeng/issues/3122

Trying to customize the table paginator. It fails under AOT complaining about components being declared twice eventhough I removed every ref to "primeng/primeg" (which took a while ;( )

If i do this...

```
@NgModule({
    imports: [
         TableModule,
  ...],
exports: [TableModule],
    declarations: [
      MyCustomOverridePaginator
]
export class MyTableModule {}
```
p-table is not aware of my component... makes sense due to scopes.

But i try to declare PrimeNg´s components (plus my own)....

```
    declarations: [
         ...primengDeclared, // this includes Table, and so on.... 
        MyCustomOverridePaginator

    ],
    exports: [
     ...primengExported, // this includes Table, and so on.... 
    MyCustomOverridePaginator]
```
It complains about the components being declared twice...

_Originally posted by @Tahiche in https://github.com/primefaces/primeng/issues/3122#issuecomment-492323697_

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
