### ISSUE TITLE
Slider doesn't works properly with ChangeDetectionStrategy.OnPush / reactive forms

### ISSUE THREAD

**Issue by rafa-as** [primefaces/primeng#7692]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Stackblitz project: https://stackblitz.com/edit/slider-onpush-errors
Demo APP: https://slider-onpush-errors.stackblitz.io

**Current behaviour**
Using the slider inside a component with ChangeDetectionStrategy.OnPush the animation doesn't work unless add the onChange event (even if it is empty).
Using the range slider inside a reactive form the field getter doesn't have the updated value but the form it's ok. 

Value updated
```typescript
reactiveForm.getRawValue()
```

Value updated
```typescript
reactiveForm.get('price').value[0]
reactiveForm.get('price').value[1]
```

Value not updated
```typescript
reactiveForm.get('price').value
```

**Expected behaviour**
The animation works properly in all cases and the slider propagate the value to the reactive form.
The value is updated on the reactive form field getter using as range.

**Minimal reproduction of the problem with instructions**
Use slider inside a component with ChangeDetectionStrategy.OnPush without onChange event and animation set true.

**What is the motivation / use case for changing the behaviour?**
Make the component usable, consistent and configurable in all cases.

**Please tell us about your environment:**
MAC OS X Mojave 10.14.4
WebStorm 2019.1.2
Yarn 1.15.2

* **Angular version:** 7.2.1

* **PrimeNG version:** 7.1.2

* **Browser:** all
 
* **Language:** all

**Comment by chriszrc** [comment]
I can confirm, even with version 9.0.0 and angular 8, the control doesn't work unless you add the dummy function in [onChange] when the component is set to `  changeDetection: ChangeDetectionStrategy.OnPush,`

**Comment by chriszrc** [comment]
It appears reactive form support is broken in several ways here, the slider also does not update correctly when the formControl value is updated. I have to manually get the slider references and update them after changes:

```
rangeSliders:QueryList<Slider>;
...
this.rangeSliders.forEach(r=>{
        r.updateHandleValue();
        r.cd.markForCheck();
});
```
