### ISSUE TITLE
TreeTable Virtual Scrolling Enhancements

### ISSUE THREAD

**Issue by svelivala** [primefaces/primeng#7696]
Hi Team,

I am using PrimeNg treetable with a virtual scroll option, with this I can achieve a lazy loading in parent level. Is there any way I can lazy loading for children using the virtual scroll? 

Thanks In Advance,
Sudheer

**Comment by kranthi0099** [comment]
I'm also waiting for this feature from long back...

**Comment by cagataycivici** [comment]
#8257 

I'm working on it right now for 9.1.0.

**Comment by cagataycivici** [comment]
We are redoing the virtual scroll for table for 9.1.0, will port it to TreeTable as well.

**Comment by cagataycivici** [comment]
#8856
