### ISSUE TITLE
Programatically set pagination

### ISSUE THREAD

**Issue by lunaboona** [primefaces/primeng#7697]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**What is the motivation / use case for changing the behavior?**
I'd like to be able to call a method like setPagination(page) so I can return to page 1 after server-side filtering.

* **Browser:** all
 
* **Language:** all

**Comment by yelhouti** [comment]
```
table.first = 0;
table.ngOnInit();
```
does what you want

**Comment by calchuchesta** [comment]
@yelhouti thanks! I was missing the ngOnInit part

**Comment by cagataycivici** [comment]
There is a demo at;

https://primefaces.org/primeng/showcase/#/table/page
