### ISSUE TITLE
Datatable Restriction

### ISSUE THREAD

**Issue by pablo-moreira** [primefaces/primeng#77]
Hello,

It would be nice to have a filter mechanism like this:
https://pablo-moreira.github.io/angular-widgets/demo/#/datatable/datatableSimpleRestriction

PrimeNG is very good.

Thank you!!!

**Comment by cagataycivici** [comment]
Welcome to PrimeNG, there is column based filtering;

http://www.primefaces.org/primeng/#/datatablefilter

So you need a global filter as well like in PrimeFaces?

http://www.primefaces.org/showcase/ui/data/datatable/filter.xhtml

**Comment by cagataycivici** [comment]
Missing feedback so closing.
