### ISSUE TITLE
Restore initial cell value if DataTable inline edit was cancelled

### ISSUE THREAD

**Issue by ilianiv** [primefaces/primeng#770]
It would be useful if DataTable cell restores it's initial value when going back to view mode if edit was cancelled.

Yes, now it could be implemented (onEditCancel) event but I think restoring back to initial value as default behaviour makes more sense.

**Comment by cagataycivici** [comment]
Not sure how we can get the old value so there is a technical limitation to think about, if more users demand it, we'll reopen, thank you for the feedback.

**Comment by guntram** [comment]
It works if you remember what to restore (you can edit only 1 field at a time):
`onEditInit($event) {
        this.descriptionToEdit = UtilsService.getCloneFromObject($event.data.description);
    }
onEditCancel($event) {
        $event.data.description = UtilsService.getCloneFromObject(this.descriptionToEdit);
        this.descriptionToEdit = "";
    }`
But the event is not fired if the field loses focus. Losing focus also doesn't fire `onEditComplete`, so it is impossible to restore the value after cancelling (except for the escape key - which works).
