### ISSUE TITLE
p-overlayPanel causes error message when append to template in 7.1.3

### ISSUE THREAD

**Issue by simdevmon** [primefaces/primeng#7700]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report 
[ ] feature request
[ ] support request
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-lwwavd

**Current behavior**
When I use a p-overlayPanel inside a p-scrollPanel I append the p-overlayPanel to the parent container:

```
<p-scrollPanel [style]="{width: '100%', height: '200px'}">
	<div #container style="display:inline-block;position:relative">
		<button pButton label="PrimeNG" (click)="op.toggle($event)"></button>
    <p-overlayPanel #op appendTo="container">
      <span>Test</span>
    </p-overlayPanel>
  </div>
  <div style="height: 500px; background-color: blue;"></div>
</p-scrollPanel>
```

This works fine, I only get an error message in the console:

```
preview-4adb70f742b91f09679fb.js:1 ERROR Error: Cannot append container to [object HTMLDivElement]
    at viewWrappedDebugError (errors.ts:28)
    at callWithDebugContext (services.ts:638)
    at Object.debugHandleEvent [as handleEvent] (services.ts:376)
    at dispatchEvent (util.ts:134)
    at eval (element.ts:200)
    at eval (animation_renderer.ts:89)
    at Array.forEach (<anonymous>)
    at eval (animation_renderer.ts:87)
    at ZoneDelegate.invoke (zone.js:391)
    at Object.onInvoke (ng_zone.ts:273)
console.<computed> @ preview-4adb70f742b91f09679fb.js:1
View_OverlayPanel_1 @ OverlayPanel.html:2
DebugContext_.logError @ services.ts:588
ErrorHandler.handleError @ error_handler.ts:51
dispatchEvent @ util.ts:137
(anonymous) @ element.ts:200
(anonymous) @ animation_renderer.ts:89
(anonymous) @ animation_renderer.ts:87
ZoneDelegate.invoke @ zone.js:391
onInvoke @ ng_zone.ts:273
ZoneDelegate.invoke @ zone.js:390
Zone.run @ zone.js:150
NgZone.run @ ng_zone.ts:171
(anonymous) @ animation_renderer.ts:86
ZoneDelegate.invoke @ zone.js:391
Zone.run @ zone.js:150
(anonymous) @ zone.js:889
ZoneDelegate.invokeTask @ zone.js:423
Zone.runTask @ zone.js:195
drainMicroTaskQueue @ zone.js:601
ZoneTask.invokeTask @ zone.js:502
invokeTask @ zone.js:1744
globalZoneAwareCallback @ zone.js:1770
preview-4adb70f742b91f09679fb.js:1 Unable to display error. Open your browser's console to view.
console.<computed> @ preview-4adb70f742b91f09679fb.js:1
console.<computed> @ preview-4adb70f742b91f09679fb.js:1
View_OverlayPanel_1 @ OverlayPanel.html:2
DebugContext_.logError @ services.ts:588
ErrorHandler.handleError @ error_handler.ts:56
dispatchEvent @ util.ts:137
(anonymous) @ element.ts:200
(anonymous) @ animation_renderer.ts:89
(anonymous) @ animation_renderer.ts:87
ZoneDelegate.invoke @ zone.js:391
onInvoke @ ng_zone.ts:273
ZoneDelegate.invoke @ zone.js:390
Zone.run @ zone.js:150
NgZone.run @ ng_zone.ts:171
(anonymous) @ animation_renderer.ts:86
ZoneDelegate.invoke @ zone.js:391
Zone.run @ zone.js:150
(anonymous) @ zone.js:889
ZoneDelegate.invokeTask @ zone.js:423
Zone.runTask @ zone.js:195
drainMicroTaskQueue @ zone.js:601
ZoneTask.invokeTask @ zone.js:502
invokeTask @ zone.js:1744
globalZoneAwareCallback @ zone.js:1770
preview-4adb70f742b91f09679fb.js:1 ERROR CONTEXT DebugContext_ {view: {…}, nodeIndex: 0, nodeDef: {…}, elDef: {…}, elView: {…}}
```

**Expected behavior**
I would not expect any error message, since it seems to work fine.

**Minimal reproduction of the problem with instructions**

https://stackblitz.com/edit/github-lwwavd
Open console, click on button.

* **Angular version:** 
7.2.15

* **PrimeNG version:** 
7.1.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 74

**Comment by va5ili5** [comment]
I am facing the same issue with overlay panel and menu. it works fine but I also get same error

**Comment by GregKosmo** [comment]
Running into the same thing here with the popup `p-menu`. I noticed the documentation for `appendTo` says

> ...valid values are "body" or a local ng-template variable of another element.

so I tried wrapping the button in a `ng-template` tag but still got the same error. Here is our setup:

- **Angular version:**
7.2.7

- **PrimeNG version:**
7.1.0

**Comment by MisaGu** [comment]
Same here.

- Angular version:
7.2.7

- PrimeNG version:
7.1.0

**Comment by buseodaci** [comment]
Did u find any solution ?

**Comment by GregKosmo** [comment]
In my case, we removed `appendTo` by fixing the underlying issue which made us use it in the first place. If we had to use it we were going to create a custom global error handler and filter those errors out.

**Comment by buseodaci** [comment]
Thank you so much for explanation.  👍

**Comment by rolivares** [comment]
I am experiencing the same problem but in a very old version (4.7). I hoped that the error had been corrected or at least have a 'workaround'.

**Comment by arajay** [comment]
This is still an issue in Angular 8, PrimeNG 8.1.1

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

```xml
<button type="text" pButton label="Basic" (click)="op1.toggle($event)"></button>

<div #mydiv></div>
<p-overlayPanel #op1 [appendTo]="xxx">
    <img src="assets/showcase/images/demo/galleria/galleria1.jpg" alt="Galleria 1" />
</p-overlayPanel>
```

**Comment by cagataycivici** [comment]
Added to docs to avoid confusion.

**Comment by beatriz-bolado** [comment]
Hi!
I have the same issue with primeNg 11.4.0.
I use [appendTo] with a ngtemplate and the following error appears but it works fine:
ERROR Cannot append [object Object] to [object HTMLDivElement]

**Comment by elanioazul** [comment]
In my case, none of the solutions work.
[appendTo]="'myDiv'" (refering to a template variable of another component named #myDiv) does not work
[appendTo]="myDiv()" (being myDiv a signal supplying the ElementRef<HtmlDivElement>

**Comment by Sbenitez73** [comment]
this issue continues, any solution?
