### ISSUE TITLE
Keyboard navigation not working in IE11 after click on table row

### ISSUE THREAD

**Issue by Jaykob86** [primefaces/primeng#7703]
**I'm submitting a ... (check one with "x")**
[ x] bug report

**Current behavior**
Arrow keys do not navigate row selection up/down in IE11

**Expected behavior**
Allow arrow keys to change the focused row to the next/previous record in IE11.

**Minimal reproduction of the problem with instructions:**
On demo page of primeng table click on one of the rows and then press arrow down/up from IE11.
https://www.primefaces.org/primeng/#/table/selection

**Please tell us about your environment:**
IE11

Similar issue was probably fixed here, but for another component and it is not included in the issue description: https://github.com/primefaces/primeng/issues/6978

**My investigation:**
Seems that on following row 2792 should be used event.currentTarget instead of event.target, because in IE a cell is focused instead of the whole row and therefore event.target in this context is table cell instead of table row. Method for changing focus fails than. Event.currentTarget should be always table row.

https://github.com/primefaces/primeng/blob/ff9393ab3a35a1e7356c3c18db4e220ed3204483/src/app/components/table/table.ts#L2792

Sorry (and please let me know) if I missed any necessary details. 

Thank you

**Comment by mertsincan** [comment]
Good catch!!! Thanks a lot for your investigation!

Best Regards,
