### ISSUE TITLE
Some style is miss in some theme.

### ISSUE THREAD

**Issue by magicdict** [primefaces/primeng#7707]
I think the primeng is a wonderful UI component,but I found some style is miss in some theme.
ie. ui-toast-message-success is miss in omega theme.
I spend one hour to found this miss style problem.
Can you check the miss style problem for all theme again?Or only put the full style theme into npm package.

**Comment by yigitfindikli** [comment]
I I couldn't replicate it. You can look https://www.primefaces.org/omega-ng/#/messages .

**Comment by Merve7** [comment]
Hi, 
Could you specify miss style problem for us to fix it? Or could you send me a screenshot?

**Comment by cagataycivici** [comment]
Omega is deprecated and not maintained, please migrate to a newer theme.
