### ISSUE TITLE
Clear the search text in dropdown once the dropdown is closed and opened again

### ISSUE THREAD

**Issue by yogesh-mali44** [primefaces/primeng#7709]
Current behavior: 
In "Content with Filters" I search for something and then click on the dropdown again to close the filter. Then I open the filter again and the last search text is not removed. 

Expected behavior:
Once I close the filter and open the filter again, the text in the search field should be cleared.

Angular version: 7
PrimeNG version: 7.1.2
Browser: all
Language: TypeScript

**Comment by JacobSiegle** [comment]
Comment tagged.

**Comment by cagataycivici** [comment]
There is resetFilterOnHide.
