### ISSUE TITLE
Can't bind to 'rows' since it isn't a known property of 'p-paginator'.

### ISSUE THREAD

**Issue by ahuvafischer** [primefaces/primeng#771]

**Comment by cagataycivici** [comment]
Have you imported Paginator Module?

**Comment by pjurago** [comment]
to DataTable to work  - app.module has to import 
DataTableModule,PaginatorModule,SharedModule,FormsModule  
before beta.13 there was less dependencies I thing ?

**Comment by cagataycivici** [comment]
We not export PaginatorModule, FormsModule in DataTableModule so when you use DataTableModule, PaginatorModule will be available already meaning you don't need to import it manually anymore with beta14.
