### ISSUE TITLE
RTL support for charts

### ISSUE THREAD

**Issue by showkatgaffar** [primefaces/primeng#7710]
I want to know do you have worked RTL on Charts. I am currently learning to do RTL on full controls. But i face problem in doing RTL on charts and scrollable Grid

**Comment by JacobSiegle** [comment]
I would assume you need to use RTL support from the chartjs library and this is not something primeng supports. Try this - https://stackoverflow.com/a/39706986/3333134

**Comment by showkatgaffar** [comment]
> I would assume you need to use RTL support from the chartjs library and this is not something primeng supports. Try this - https://stackoverflow.com/a/39706986/3333134

Actually i have used PrimeNg in my English Version now i need to do rtl for this app, so i cannot change the theme now it will not be the replica of english version then
