### ISSUE TITLE
Position of selected item in p-dropdown with virtual scroll enabled not maintained

### ISSUE THREAD

**Issue by parky128** [primefaces/primeng#7712]
In the Virtual Scroll example of the primeNG `p-dropdown` component, the position of the selected item is not maintained after you re-open the drop down from making an earlier selection.

See https://www.primefaces.org/primeng/#/dropdown

The 'Content with Filters' does work however, so I can only assume this may be a limitation with virtual scrolling enabled?

Also, when using the keyboard controls to move up and down the list of options, the list does not auto scroll to follow the selections either.

See my example here where I am trying to use the virtual scroll with filtering enabled -> https://stackblitz.com/edit/angular-playground-f57jog

Has anyone else out there using primeNG encountered this and found any solution?

Thanks

**Comment by parky128** [comment]
Duplicate

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/issues/7892

**Comment by senp0105** [comment]
I am still facing this problem with "primeng": "9.1.0" and angular 9. Is this issue resolved?

**Comment by senp0105** [comment]
i have opened issue : https://github.com/primefaces/primeng/issues/9026
