### ISSUE TITLE
Change Dropdown scrollHeight from TurboTable or Paginator

### ISSUE THREAD

**Issue by csvinhal** [primefaces/primeng#7713]
**I'm submitting a ...**
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
The `scrollHeight` of the Dropdown component is 200px by default, but it can be only changed using the component Dropdown by itself.

**Expected behavior**
When using the TurboTable or Paginator components I want to be able to change the `scrollHeight` property of Dropdown.

**What is the motivation / use case for changing the behavior?**
When using a TurboTable with some rowsPerPage the dropdown options are generated with a scroll.

* **Angular version:** 7.1

* **PrimeNG version:** 7.1.X

* **Browser:** all
 
* **Language:** all

**Comment by sidneibiz** [comment]
+1

**Comment by francovegini** [comment]
+1

**Comment by andersonbuzzi** [comment]
+1

**Comment by DevGomes** [comment]
+1

**Comment by philipstefan** [comment]
+1
