### ISSUE TITLE
DialogComponent - TypeError: Cannot read property 'style' of undefined  at Dialog.maximize

### ISSUE THREAD

**Issue by KeithGillette** [primefaces/primeng#7715]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**StackBlitz Reproduction (Bug Reports)**
[https://stackblitz.com/edit/p-dialog-maximize-error](https://stackblitz.com/edit/p-dialog-maximize-error)

**Current behavior**
When attempting to call `maximize()` on an `@ViewChild(DialogComponent)` in `ngAfterViewInit`, the following error appears in the browser console:
```
ERROR TypeError: Cannot read property 'style' of undefined
    at Dialog.maximize (dialog.ts:340)
 ```

**Expected behavior**
`DialogComponent` would maximize without error without need for a `setTimeout()`.

**Minimal reproduction of the problem with instructions**
Follow instructions on linked [StackBlitz reproduction](https://stackblitz.com/edit/p-dialog-maximize-error).

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
