### ISSUE TITLE
FullCalendar documentation improvements

### ISSUE THREAD

**Issue by MakesNine** [primefaces/primeng#7719]
**I'm submitting a ...**  (check one with "x")

[ ] bug report => Search github for a similar issue or PR before submitting
[X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap

**Current behavior**
Upgrading to PrimeNG 7.1.1 or later generates breaking changes in the FullCalendar component as described in the release [note](https://www.primefaces.org/primeng-7-1-1-released/) that also directs the users to the FullCalendar [documentation ](https://www.primefaces.org/primeng/#/fullcalendar)for details.

Following the steps provided in the documentation of the FullCalendar worked, but only after making further changes in the angular.json file in the root of the project.  The required modifications were taken from the angular.json file in this repo where the relevant imports for the styles and scripts required for FullCalendar 4.1.0 can be found:

              "styles": [
                "node_modules/@fullcalendar/core/main.min.css",
                "node_modules/@fullcalendar/daygrid/main.min.css",
                "node_modules/@fullcalendar/timegrid/main.min.css",
                 ...
              ],
              "scripts": [
               "./node_modules/@fullcalendar/core/main.js",
                "./node_modules/@fullcalendar/daygrid/main.js",
                "./node_modules/@fullcalendar/timegrid/main.js",
                "./node_modules/@fullcalendar/interaction/main.js",
               ...
              ]

**Expected behavior**
Please provide an example setup with the Angular CLI that includes the required modifications in angular.json.  Such an example setup is provided in the [documentation ](https://www.primefaces.org/primeng/#/editor)of the Editor component that has a dependency on the Quill editor

**What is the motivation / use case for changing the behavior?**
Make it easier to use PrimeNG FullCalendar component

* **Angular version:** 8.0.0-rc.4

* **PrimeNG version:** 7.1.3

**Comment by geoffreybr** [comment]
Actually it seems to work without the scripts as they are already included in _vendor.js_ at compilation. However, to solve this problem, I had to add these imports :
```
import dayGridPlugin            from '@fullcalendar/daygrid';
import timeGridPlugin           from '@fullcalendar/timegrid';
import interactionPlugin        from '@fullcalendar/interaction';
```
and this minimal option value :
```
this.options = {
    plugins:[ dayGridPlugin, timeGridPlugin, interactionPlugin ]
};
```

The styles are mandatory or it looks quite bad.

**Comment by ForzaMark** [comment]
Actually ran exacty into the same problem as @MakesNine described.
After following the instructions on the documentation the FullCalendar looks like this 
![primeNg](https://user-images.githubusercontent.com/28750031/61577300-c91f1180-aae5-11e9-824b-cd271c417d0e.png)
It seems that there are some styles missing

After applying the changes suggested by @MakesNine everything works as expected and the fullcalendar look like this 
![prime](https://user-images.githubusercontent.com/28750031/61577312-0aafbc80-aae6-11e9-8c5a-c848873ebf55.png)

As @geoffreybr pointed out the styles are mandatory and this should be outlined in the documentation.
