### ISSUE TITLE
Can't bind to 'x' since it isn't a known property of 'y'.

### ISSUE THREAD

**Issue by ahuvafischer** [primefaces/primeng#772]
after upgrading to rc5, and reinstalling primeng with the new release, i receive the following error:

```zone.js?1472019041780:484 Unhandled Promise rejection: Template parse errors:
Can't bind to 'icon' since it isn't a known property of 'button'. ("ver':hovered,'ui-state-focus':focused,'ui-state-disabled':disabled}"
        ><button type="button" [ERROR ->][icon]="icon" pButton *ngIf="showIcon" (click)="onButtonClick($event,in)" 
                [ngClass]="): **Calendar@7:31** ; Zone: <root> ; Task: Promise.then ; Value: ```

i tried removing all references to calendar, so i can at least get the app up and running, and got another issue:

```
Can't bind to 'rows' since it isn't a known property of 'p-paginator'.
1. If 'p-paginator' is an Angular component and it has 'rows' input, then verify that it is part of this module.
2. If 'p-paginator' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
 ("              <ng-content select="header"></ng-content>
            </div>
            <p-paginator [ERROR ->][rows]="rows" [first]="first" [totalRecords]="totalRecords" [pageLinkSize]="pageLinks" styleClass="ui"): DataTable@6:25
Can't bind to 'first' since it isn't a known property of 'p-paginator'.
1. If 'p-paginator' is an Angular component and it has 'first' input, then verify that it is part of this module.
2. If 'p-paginator' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
 ("<ng-content select="header"></ng-content>
            </div>
```

**Comment by ahuvafischer** [comment]
adding dependancies: 

```import { NgModule, ElementRef }       from '@angular/core';
import { BrowserModule }  from '@angular/platform-browser';
import { FormsModule }    from '@angular/forms';
import { RouterModule } from '@angular/router';
import { HttpModule } from '@angular/http';
import { Calendar, DataTable, Column, InputMask } from 'primeng/primeng';
```

**Comment by MarkPerryBV** [comment]
@ahuvafischer Did you find a workaround for these errors?

**Comment by ahuvafischer** [comment]
there is this thread: https://github.com/angular/angular/issues/10618, which other developers may find helpful. hasn't resolved my issue.

**Comment by cagataycivici** [comment]
Try modules instead;

```
import { CalendarModule, DataTableModule, InputMaskModule } from 'primeng/primeng';
```

DataTable exports column and paginator so no need to import them.

**Comment by buddyackerman** [comment]
@ahuvafischer can you create a Plnkr to illustrate the problem.  This issue cropped up in RC5 because of a minification problem that breaks RC5 apps (has to do with function name collisions after minification).  If this is happening in unminified code then there might be other problems but if your app is only failing after minification then you just need to change the mangle property of your minification plugin.  The change is illustrated in the [this thread](http://forum.primefaces.org/viewtopic.php?f=35&t=46690) .

**Comment by MarkPerryBV** [comment]
Just in case others are having trouble with this error. Currently NG2 RC.5 does NOT minify correctly. If you minify NG2 RC.5 or your own components then these errors surface.

I had these exact same errors and resolved them by excluding my NG2 code from the minification process.

**Comment by buddyackerman** [comment]
@MarkPerryBV you can still minify, just need to change the mangle option as specified in the thread I posted.

**Comment by ahuvafischer** [comment]
Thanks guys. for now we decided to wait for a more stable release. I must say that i am disappointed, because this release includes some really great updates.

**Comment by MarkPerryBV** [comment]
@ahuvafischer This isn't a bug with PrimeNG but an issue with NG RC.5.

**Comment by MarkPerryBV** [comment]
@buddyackerman You are right. Minification works but mangling does not.

**Comment by ahuvafischer** [comment]
@MarkPerryBV, correct that is why i referred to the thread above.

**Comment by cagataycivici** [comment]
Kinda duplicate to #771
