### ISSUE TITLE
Table row disabled. Can't find the way to do that.

### ISSUE THREAD

**Issue by LukSkywookie** [primefaces/primeng#7723]
Hello.
I'm looking for a way to disable whole row in Primeng Table.
I'm not talking about selectable row but simple table without any fancy addons.
Can anyone help me?

Kind regards, 
Luk

**Comment by JacobSiegle** [comment]
I am not sure why you would need to disable a row on a normal table, but just change the CSS color of the row to emulate it's "disabled" - https://www.primefaces.org/primeng/#/table/style

This is a question not an issue, please close and try the primeng forum instead.

**Comment by LukSkywookie** [comment]
My project requires switching off several rows of the table (not all of them).
This is problematic when the row generates in a loop and I have to indicate a specific row to gray out.

But you are right; it's not the issue.

Regards

**Comment by JacobSiegle** [comment]
If you look at the demo table style link it shows you how to easily style specific rows. Just make the style grayed out to appear disabled and it will work in a loop as you specified in your requirement. Best of luck!

**Comment by LukSkywookie** [comment]
To be honest that did the trick :).
Thank you ;)
