### ISSUE TITLE
Add an interface for the EventEmitters events

### ISSUE THREAD

**Issue by qk7b** [primefaces/primeng#7725]
**I'm submitting a ...**  
```
[ ] bug report
[x] feature request
[ ] support request
```
**What is the motivation / use case for changing the behavior?**

In order to help with readability, autocomplete, and type checking, it would be great for the _events_ emitted by the components to be typed.
In the actual version, they are just _arbitrary objects_ so it is hard to use them. 
*Sometimes, they are not even described in the doc and we have to check the sources of the files to find the properties.*
This comes with the fact that a change in them (a property name for example) would not be detected before the integration tests.

_Here is an example of what I'm thinking:_
In the [rating](https://github.com/primefaces/primeng/blob/master/src/app/components/rating/rating.ts) component.
There is an [`@Output() onRate: EventEmitter<any> = new EventEmitter();`](https://github.com/primefaces/primeng/blob/946987d8f7dd073147aa55e33dc2159eef2c11ca/src/app/components/rating/rating.ts#L50) emitter.
And when triggered, [it is emitted like this](https://github.com/primefaces/primeng/blob/946987d8f7dd073147aa55e33dc2159eef2c11ca/src/app/components/rating/rating.ts#L76)
```
this.onRate.emit({
    originalEvent: event,
    value: (i+1)
});
```

What I'm thinking is a kind of `Rate` interface with a typed `originalEvent` and and a typed `value` properties. 
Then, the `@Output() onRate: EventEmitter<any>` can be updated to a 
`@Output() onRate: EventEmitter<Rate>`, and we can be sure of the type we are receiving in our code. 

* **PrimeNG version:** 7.X

* **Browser:** all
 
* **Language:** TypeScript

**Comment by quentin7b** [comment]
NB: If this is ok for you, I could try to work on it.
