### ISSUE TITLE
Dynamic Dialog doesn't animate on hide only when showing

### ISSUE THREAD

**Issue by Txuso** [primefaces/primeng#7728]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
Currently, it is not possible to add animations when hiding the Dynamic Dialog. 

**Expected behavior**
By default, if animations are added to the Dynamic Dialog the dialog should be able to hide applying an animation. For instance, if I have an animation to slide the dialog from the bottom to the top the hide animation should be a transition from the top to the bottom again. Therefore, transitionOptions object should include onHide animation options.

**What is the motivation / use case for changing the behavior?**
Make PrimeNG a good UI Framework option to develop PWA and improve UX in mobile view.

* **Angular version:** 7.2

* **PrimeNG version:** 7.1

* **Browser:** all
 
* **Language:** all

**Comment by grusso7** [comment]
I don't know if is a good practice, but as a workaround in my compoment instead of DynamicDialogRef I inject the DialogService and invoke close by:
this.dialogService.dialogComponentRef.instance.close();
The behavior is the same.

**Comment by Txuso** [comment]
Thanks for the answer Giuseppe, it works and it animates on hiding.
However, it sounds weird to me that I have to call
this.dialogService.dialogComponentRef.instance.close(); from the embed
component to have the animation... the documentation says we should use the
this.dynamicDialogRef.close(); Moreover using
this.dialogService.dialogComponentRef.instance.close(); we cannot send an
object, string, number or whatever as a payload. Anyway, many thanks for
your contribution and let's see if they implement/fix it soon.

Have a nice day,
Josu Rubio.

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Comment by cagataycivici** [comment]
Replicated.
