### ISSUE TITLE
How to set value of dropdown when using reactive forms

### ISSUE THREAD

**Issue by webrexRavi** [primefaces/primeng#7731]
![Screenshot from 2019-05-24 16-13-34](https://user-images.githubusercontent.com/34544558/58322596-0c8b3580-7e3f-11e9-86f6-801f294518ee.png)

not setting the vlaue of variable **selectedCli**

**Comment by davisb10** [comment]
Not sure if this is causing the issue, but you are mixing Model-Driven and Reactive Forms. You should use one or the other. You should be able to get the selected clinic by doing this.editAppointmentForm.get('clinic').value from your .ts file

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.
