### ISSUE TITLE
p-table paginator add template feature

### ISSUE THREAD

**Issue by mickeyjohn** [primefaces/primeng#7732]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
Paginator when in used with p-table does not support custom templates such as: templateLeft and templateRight.

**Expected behavior**
Should have a way to use custom template in paginator to display: total records or record ranges as mentioned before in #4329

**What is the motivation / use case for changing the behavior?**
I would be much more helpful to have this feature supported so we can display more useful information to the users along with the table.

* **Angular version:** 7.X
* **PrimeNG version:** 7.1.3

**Comment by davisb10** [comment]
There are currently "paginatorleft" and "paginatorright" as pTemplate types:
```html
<ng-template pTemplate="paginatorleft" let-state>
    {{state.first}}
    <button type="button" pButton icon="fa-refresh"></button>
</ng-template>
<ng-template pTemplate="paginatorright">
    <button type="button" pButton icon="fa-cloud-upload"></button>
</ng-template>
```

**Comment by mickeyjohn** [comment]
Thank you so much @davisb10 for your quick response. I did not know we can do this now.
