### ISSUE TITLE
Primeng datatable responsiveness issue 

### ISSUE THREAD

**Issue by Trustiser-Habiba** [primefaces/primeng#7738]
Hello,  i am currently  learning how to use primeng datatable in our project,  i have an issue about the responsiveness of this table. The table is responsive if the web page is in its normal size or when we decrease its size while having  separators such as space, hyphen between words. But,  we observe that if we have a long  text in one of  its columns, it will not be responsive anymore while we decrease the size of the web page. 

The web page with a normal size : 
 
![primeng datatable responsive 1](https://user-images.githubusercontent.com/51077905/58413742-d259a800-8079-11e9-95b8-10f89ec3c8f1.PNG)

The web page when i decrease its size : 

 
![primeng datatable responsive 2](https://user-images.githubusercontent.com/51077905/58413765-e2718780-8079-11e9-8280-2285e4e662da.PNG)

* My html code is : 

` <p-dataTable [value]="memberList" [responsive]="true" [stacked]="stacked" >
 <p-column *ngFor="let col of cols" [field]="col.field" [header]="col.header" >   </p-column ></p-dataTable> `

* My  typeScript  code is : 

`

import {Component, OnInit} from '@angular/core';
import {HttpClient, HttpErrorResponse} from "@angular/common/http";
import {AccordionModule} from "primeng/primeng";
import {MenuItem} from 'primeng/api' ;
import {DataTableModule} from "primeng/datatable";

export interface Member
{
    userName;
    email;
    jobTitle;
    status;
    phoneNumber;
    joinDate;
}

@Component({
    selector: 'app-member-liste',
    templateUrl: './member-liste.component.html',
    styleUrls: ['./member-liste.component.css']
})
export class MemberListeComponent implements OnInit {
    memberList: string[] ;
    members: Member[] ;
    cols: any[] ;

    displayedColumns = ['userName', 'email' , 'status', 'phoneNumber', 'joinDate'];

    constructor( private httpService: HttpClient) {

    }

    ngOnInit() {

        this.httpService.get('./assets/membresTable.json').subscribe(
            data => {
                this.memberList = data as string [];
            },
            (err: HttpErrorResponse ) => {
                console.log(err.message);
            }
        );

        this.cols = [
            {field: 'userName', header: 'UserName'},
            {field: 'email', header: 'Email'},
            {field: 'jobTitle', header: 'JobTitle'},
            {field: 'status', header: 'Status'},
            {field: 'phoneNumber', header: 'PhoneNumber'},
            {field: 'joinDate', header: 'JoinDate'}
        ] ;

    }

}
`
I will be very grateful if you can help me resolving this issue.

Thank you in advance.

**Comment by JacobSiegle** [comment]
Hyphens are supposed to break, it's native CSS functionality and nothing to do with primeng. I would suggest looking into https://developer.mozilla.org/en-US/docs/Web/CSS/white-space, this is not a bug with primeng you will not get support.

View the line in the provided link - 
`Note: To make words break within themselves, use overflow-wrap, word-break, or hyphens instead.`

**Comment by Trustiser-Habiba** [comment]
> Hyphens are supposed to break, it's native CSS functionality and nothing to do with primeng. I would suggest looking into https://developer.mozilla.org/en-US/docs/Web/CSS/white-space, this is not a bug with primeng you will not get support.
> 
> View the line in the provided link -
> `Note: To make words break within themselves, use overflow-wrap, word-break, or hyphens instead.`

Thank you so much for replying me.

i will try to do what you had suggested me.

**Comment by Trustiser-Habiba** [comment]
> Hello, i am currently learning how to use primeng datatable in our project, i have an issue about the responsiveness of this table. The table is responsive if the web page is in its normal size or when we decrease its size while having separators such as space, hyphen between words. But, we observe that if we have a long text in one of its columns, it will not be responsive anymore while we decrease the size of the web page.
> 
> The web page with a normal size :
> 
> ![primeng datatable responsive 1](https://user-images.githubusercontent.com/51077905/58413742-d259a800-8079-11e9-95b8-10f89ec3c8f1.PNG)
> 
> The web page when i decrease its size :
> 
> ![primeng datatable responsive 2](https://user-images.githubusercontent.com/51077905/58413765-e2718780-8079-11e9-8280-2285e4e662da.PNG)
> 
> * My html code is :
> 
> `<p-dataTable [value]="memberList" [responsive]="true" [stacked]="stacked" > <p-column *ngFor="let col of cols" [field]="col.field" [header]="col.header" > </p-column ></p-dataTable>`
> 
> * My  typeScript  code is :
> 
> `
> 
> import {Component, OnInit} from '@angular/core';
> import {HttpClient, HttpErrorResponse} from "@angular/common/http";
> import {AccordionModule} from "primeng/primeng";
> import {MenuItem} from 'primeng/api' ;
> import {DataTableModule} from "primeng/datatable";
> 
> export interface Member
> {
> userName;
> email;
> jobTitle;
> status;
> phoneNumber;
> joinDate;
> }
> 
> @component({
> selector: 'app-member-liste',
> templateUrl: './member-liste.component.html',
> styleUrls: ['./member-liste.component.css']
> })
> export class MemberListeComponent implements OnInit {
> memberList: string[] ;
> members: Member[] ;
> cols: any[] ;
> 
> ```
> displayedColumns = ['userName', 'email' , 'status', 'phoneNumber', 'joinDate'];
> 
> constructor( private httpService: HttpClient) {
> 
> }
> 
> 
> 
> ngOnInit() {
> 
>     this.httpService.get('./assets/membresTable.json').subscribe(
>         data => {
>             this.memberList = data as string [];
>         },
>         (err: HttpErrorResponse ) => {
>             console.log(err.message);
>         }
>     );
> 
>     this.cols = [
>         {field: 'userName', header: 'UserName'},
>         {field: 'email', header: 'Email'},
>         {field: 'jobTitle', header: 'JobTitle'},
>         {field: 'status', header: 'Status'},
>         {field: 'phoneNumber', header: 'PhoneNumber'},
>         {field: 'joinDate', header: 'JoinDate'}
>     ] ;
> 
> }
> ```
> 
> }
> `
> I will be very grateful if you can help me resolving this issue.
> 
> Thank you in advance.

i have resolved the issue by adding "word-break : break-all" to the file.css of the component.

i read the following document : https://developer.mozilla.org/en-US/docs/Web/CSS/word-break.
