### ISSUE TITLE
Event onHide is never called when closing the dialog

### ISSUE THREAD

**Issue by tleveque23** [primefaces/primeng#7739]
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When closing a dialog using the close button (in the header) the bound onHide method is not called.
```
<p-dialog *ngIf="display"
            [header]="'GLOBAL_SEARCH.DIALOG_HEADER'|translate"
            [(visible)]="display"
            (onHide)="onDialogHide()">
```
Here my method onDialogHide() is not called when closing the dialog.

**Expected behavior**
The bound method is called

In your code, the onHide event emitter is only called in the onAnimationStart method....

* **Angular version:** 7.2.15

* **PrimeNG version:** 7.1.3

**Comment by JacobSiegle** [comment]
Seems like it works to me, can you reproduce? - https://stackblitz.com/edit/github-nufwqv

onAnimationStart runs when the dialog opens or closes.

**Comment by tleveque23** [comment]
Well... I was able to reproduce it but when doing so, I realize what was the cause of it. It was because there was an `*ngIf="display"` on a div surrounding the dialog. That display property is the same that is used for the "visible" attribute on the dialog.
I found a work around for that, but... it could still be a bug I think... not sure.

**Comment by JacobSiegle** [comment]
So the question is if onHide should trigger when dialog is being destroyed also instead of only when the close animation is run. I think that is up to a maintainer, you can make a PR if you believe it should work that way. Making a PR will help get your issue resolved much quicker.

**Comment by yigitfindikli** [comment]
It is not a bug. ngIf will be destroy the dialog and some events cant be called.
