### ISSUE TITLE
Checkbox issue on p-table with group

### ISSUE THREAD

**Issue by namnhcntt** [primefaces/primeng#7740]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/primeng-table-grouping-selection

**Current behavior**
When check  on a checkbox row, it also checks all the row on same group.

**Expected behavior**
When check on a checkbox row, it only check that row.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

 **Angular version:** 7.1

* **PrimeNG version:** 7.1.3

* **Browser:** Chrome 74

 
* **Language:** TypeScript 3.1.6

* **Node (for AoT issues):** `node --version` =   v10.14.2

**Comment by namnhcntt** [comment]
I found the issue. 

![1](https://user-images.githubusercontent.com/4961896/58953464-c760ef00-87c0-11e9-839a-41b512aa90ec.PNG)

In this function, if we group by dataKey field, the condition of function isSelected() just check the dataKey in each rowData is equal. And so all the rowData in same group is selected. I think in this case, we should check equal rowData

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
