### ISSUE TITLE
table column resize issue

### ISSUE THREAD

**Issue by miliardopiscrat** [primefaces/primeng#7742]
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/column-resize-issue?file=src/app/app.component.html

**Current behavior**
When user scrolled to right column resize behave strange and column resize helper is not with mouse cursor position

**Expected behavior**
Column resize helper is with mouse cursor position

* **Angular version:**
7.2.3
7.2.10

* **PrimeNG version:**
7.1.0
7.1.3

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
