### ISSUE TITLE
Wrong import. Angular 8 wont work.

### ISSUE THREAD

**Issue by tomaszwawrzyniakit** [primefaces/primeng#7745]
**I'm submitting a ...**  (check one with "x")

[X] bug report
[ ] feature request
[ ] support request

**Current behavior**
It's not possible to build application with Angular 8 throughwrong import in **table.d.ts**:
 **import { OnDestroy } from '@angular/core/src/metadata/lifecycle_hooks';**

**Expected behavior**
Application should work, and  **table.d.ts** should have an import:
import {  OnDestroy } from '@angular/core';

**Minimal reproduction of the problem with instructions**
Build application with latest version of Angular 8.
Console log:
 ERROR in node_modules/primeng/components/table/table.d.ts(5,27): error TS2307: Cannot find module '@angular/core/src/metadata/lifecycle_hooks'.

Similar to #7306  #7355

**Comment by yigitfindikli** [comment]
fixed in https://github.com/primefaces/primeng/commit/97ffa3fb902598044442e8dcb377e65b0e6729b0 . (For PrimeNG 8)

**Comment by anamilos** [comment]
Will this fix be available in Primeng 7?
If not, is there a workaround?

**Comment by atruptoneatma** [comment]
When PrimeNG8 is going to release

**Comment by armved** [comment]
+1

**Comment by PHuhn** [comment]
+1
