### ISSUE TITLE
Menubar baseZindex doesn't work

### ISSUE THREAD

**Issue by hakim-dc** [primefaces/primeng#7746]
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-j6jj2y

**Current behavior**
i set the menu bar basezindex to 3000 and i have a dialog with 2000 base zindex, so i move the dialog below the menu and try to open menu item, the drop down appears behind the dialog. 
**Expected behavior**
menu item has a higher base zindex than dialog it must be on the front of the dialog

* **Angular version:** 7.X

* **PrimeNG version:** 7.X

* **Browser:** [all]

**Comment by JacobSiegle** [comment]
I think the z-index is only supposed to work on the popup sub menu items for layering, not the entire menu bar.

If you want to make the entire menu appear over the dialog you would need to apply the z-index to the div with class ui-menubar give it relative position. 
![image](https://user-images.githubusercontent.com/5766272/58563291-782f2300-81f0-11e9-98ec-757386d954b8.png)

**Comment by hakim-dc** [comment]
what i mean is that only the sub menu items appear over the dialog, i think the is bug in the code, when user mose over menubar item the generated zindex of sub items start from container base zindex and dosen't add the user baseZindex.

**Comment by JacobSiegle** [comment]
OK thanks for clarification, I misunderstood. It does seem bugged testing only the sub items against the dialog.
