### ISSUE TITLE
Not compatible with Angular 8 

### ISSUE THREAD

**Issue by md-shahnawaz08** [primefaces/primeng#7748]
Error
----------
```node_modules/primeng/components/table/table.d.ts(5,27): error TS2307: Cannot find module '@angular/core/src/metadata/lifecycle_hooks'```

Solution
---------
In ```primeng/components/table/table.d.ts```
Replace 
```import { OnDestroy } from '@angular/core/src/metadata/lifecycle_hooks';```
With
```import { OnDestroy } from '@angular/core';```

**Comment by JacobSiegle** [comment]
Please resolve this is a duplicate - https://github.com/primefaces/primeng/issues/7745

**Comment by jmesa-sistel** [comment]
Duplicate. Already fixed in master. [#7627](https://github.com/primefaces/primeng/issues/7627)

**Comment by lotar94** [comment]
> ## Error
> `node_modules/primeng/components/table/table.d.ts(5,27): error TS2307: Cannot find module '@angular/core/src/metadata/lifecycle_hooks'`
> 
> ## Solution
> In `primeng/components/table/table.d.ts`
> Replace
> `import { OnDestroy } from '@angular/core/src/metadata/lifecycle_hooks';`
> With
> `import { OnDestroy } from '@angular/core';`

so i need simply inside of node_modules go to primeng/components/table/table.d.ts and change it. So whatshappend when i make the npm i.  and when a push to mi repo node_modules is in gitignore

**Comment by JacobSiegle** [comment]
Use a newer version of primeng which already has it patched.

**Comment by lotar94** [comment]
@JacobSiegle  thanks. Now work
