### ISSUE TITLE
primeng is failing the build angular 8 update. 

### ISSUE THREAD

**Issue by jaggi510** [primefaces/primeng#7749]
Angular build is throwing error after upgrading to Angular 8. 

ERROR in node_modules/primeng/components/table/table.d.ts(5,27): error TS2307: Cannot find module '@angular/core/src/metadata/lifecycle_hooks'.

Looks like table component's OnDestroy import is wrong. 
import { OnDestroy } from '@angular/core/src/metadata/lifecycle_hooks';
it should be imported from @angular/core.

**Comment by JacobSiegle** [comment]
Please search for duplicate issues. This issue is listed right below yours - https://github.com/primefaces/primeng/issues/7748

**Comment by jaggi510** [comment]
closing as it is duplicate.
