### ISSUE TITLE
treeTable clear filters and table totalRecords issue

### ISSUE THREAD

**Issue by ymasha** [primefaces/primeng#7751]
I am using treeTable and I have two problems:
1. when the filter is used on the column the totalRecords value is not updated.
2.    reset() method on TreeTable  clears the filters but doesn't set data to the table 

see the repro: 
https://stackblitz.com/edit/treetableissue

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
