### ISSUE TITLE
[p-table] Border of last frozen column disappears when scrolling

### ISSUE THREAD

**Issue by thaihacong** [primefaces/primeng#7755]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**
https://www.primefaces.org/primeng/#/table/scroll > Frozen Columns

**Current behavior**
Scroll the scrollable columns a little bit to the right, the border between the (last) frozen column and the scrollable columns (**Vin** and **Year**) is hidden (disappears).

![primeng-table-frozen-columns-scroll](https://user-images.githubusercontent.com/8019304/58714376-e62c4380-83c4-11e9-9ddd-0ceec591cfc4.png)

**Expected behavior**
The border should not disappear when scrolling.

**What is the motivation / use case for changing the behavior?**
Missing border makes two columns look like one with mixed/messed up data, which then makes user confuses in some cases.

* **Angular version:** 7.2.15

* **PrimeNG version:** 7.1.3

* **Browser:** Firefox, Chrome

**Comment by mertsincan** [comment]
Hi,

It is by design. For your issue, please try the following css code;
```
<style>
    .ui-table .ui-table-frozen-view {
        border-right: 1px solid #c8c8c8;
    }
    .ui-table .ui-table-frozen-view + .ui-table-unfrozen-view .ui-table-thead > tr > th:first-child,
    .ui-table .ui-table-frozen-view + .ui-table-unfrozen-view .ui-table-tbody > tr > td:first-child {
        border-left: 0 none;
    }
</style>
```

**Comment by bjelajac93** [comment]
Hi,

Please try the following css code:

<style>
    .ui-table-tbody {
       border: 1px solid #c8c8c8 !important;
       display: table-row-group;
     }
</style>
