### ISSUE TITLE
p-treetable not filtering when only one parent is present

### ISSUE THREAD

**Issue by jorgefgm** [primefaces/primeng#7757]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Waiting Time: ~8 weeks.

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
p-treetable filter option doesn't work when you only have one parent, it doesn't filter through the childs

**Expected behavior**
Filter data even when you only have one parent.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/github-3dtpnj

**What is the motivation / use case for changing the behavior?**
Missing functionality

**Please tell us about your environment:**

* **Angular version:** 7.2.9
* **PrimeNG version:** 7.1.3
* **Browser:** all

**Comment by mertsincan** [comment]
Hi @Gretam11,

Thanks a lot for the PR! Unfortunately, your fix does not work in some cases. Could you please try my fix?

Thanks again.

**Comment by Gretam11** [comment]
Hi @mertsincan,
I've checked new version and it works well there, thank you for fixing it!
I will close my PR then.

**Comment by mertsincan** [comment]
Glad to hear, thanks a lot for the update!

Best Regards,
