### ISSUE TITLE
Calendar dataType string range not working

### ISSUE THREAD

**Issue by yelhouti** [primefaces/primeng#7758]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template **stackblitz share problems pasting code below**
```
<p-calendar [(ngModel)]="deadlineRange" selectionMode="range" dataType="string"></p-calendar>


import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent {

  // should also work with empty array
  deadlineRange = ['2019-06-06'];

}
```
**Current behavior**

Exception is thrown when trying to initialize calendar when dataType is string and selection mode is multiple or range.
check should be added here, and if range do same operation to all elements of array.
https://github.com/primefaces/primeng/blob/master/src/app/components/calendar/calendar.ts#L1691
I can make a pull request with tests if you allow it.
**Expected behavior**

should initalize properly

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
