### ISSUE TITLE
Angular 8 Compatibility

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#7761]
Update to Angular 8

**Comment by cagataycivici** [comment]
Ready for PrimeTime! Please note that Ivy is not yet supported. We'll tackle it with 8.x releases.

**Comment by jmesa-sistel** [comment]
@cagataycivici Hello
Can you create and issue for Ivy support? So we can track the progress or when it is implemented when you close it.
I guess you know already but maybe help, you should try to use [https://github.com/ng-packagr/ng-packagr](https://github.com/ng-packagr/ng-packagr) when you publish to npm
