### ISSUE TITLE
Remove deprecated themes

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#7762]
It is time to remove them in favor of the next gen themes and designer.

**Comment by supamax** [comment]
Hello, we used theme scss files directly to override variables for our needs. Now it version 8 it was deleted. What is workaround for overriding some aspect of existing themes??
We are stuck now because of it in migrating the whole project to angular 8.

**Comment by chrizSer** [comment]
Is there a new way to customize color?
