### ISSUE TITLE
 Editor has stopped working after upgrade to primeng 8.0.0-rc.1

### ISSUE THREAD

**Issue by fernandogomesdf** [primefaces/primeng#7767]
Editor has stopped working after upgrade to primeng 8.0.0-rc.1

ng:///ComponentesModule/CriareventoComponent.ngfactory.js:339 ERROR TypeError: quill_1.default is not a constructor
    at Editor.push../node_modules/primeng/components/editor/editor.js.Editor.ngAfterViewInit (vendor.js:171549)
    at callProviderLifecycles (vendor.js:74555)
    at callElementProvidersLifecycles (vendor.js:74520)
    at callLifecycleHooksChildrenFirst (vendor.js:74502)
    at checkAndUpdateView (vendor.js:84713)
    at callViewAction (vendor.js:85069)
    at execComponentViewsAction (vendor.js:84997)
    at checkAndUpdateView (vendor.js:84710)
    at callViewAction (vendor.js:85069)
    at execComponentViewsAction (vendor.js:84997)

With angular 8.0.0 and primeng 7.1.3 it works fine.

My code:
https://github.com/fernandogomesdf/rennova-web.git
(disable login guard)

Any suggestions?

**Comment by Vendium** [comment]
Angular 8.0.0
primeng 8.0.0-rc.1


TypeError: quill_1.default is not a constructor
    at Editor.push../node_modules/primeng/components/editor/editor.js.Editor.ngAfterViewInit (vendor.js:225551)
    at callProviderLifecycles (vendor.js:86238)
    at callElementProvidersLifecycles (vendor.js:86212)
    at callLifecycleHooksChildrenFirst (vendor.js:86202)
    at checkAndUpdateView (vendor.js:94132)
    at callViewAction (vendor.js:94364)
    at execComponentViewsAction (vendor.js:94306)
    at checkAndUpdateView (vendor.js:94129)
    at callViewAction (vendor.js:94364)
    at execEmbeddedViewsAction (vendor.js:94327)
    at checkAndUpdateView (vendor.js:94124)
    at callViewAction (vendor.js:94364)
    at execEmbeddedViewsAction (vendor.js:94327)
    at checkAndUpdateView (vendor.js:94124)
    at callViewAction (vendor.js:94364)

**Comment by McGiogen** [comment]
[Source code is correct](https://github.com/primefaces/primeng/blob/8.0.0-rc.1/src/app/components/editor/editor.ts#L111) but not the distributed code ( `this.quill = new quill_1.default(editorElement, {` ). Manually executing the following code works:

```
this.quill = new quill_1(editorElement, {
            modules: modules,
            placeholder: this.placeholder,
            readOnly: this.readonly,
            theme: 'snow',
            formats: this.formats,
            bounds: this.bounds,
            debug: this.debug,
            scrollingContainer: this.scrollingContainer
        });
```

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with a stackblitz template that demontrates the problem.

Live demo also runs on 8

**Comment by dmastag** [comment]
Hi @cagataycivici 
Here is the Stackblitz with the same exact error

https://stackblitz.com/edit/angular-nzene1

Its using Angular 8 and primeng 8.0.0-rc.1

![image](https://user-images.githubusercontent.com/5745805/59419255-b5043800-8df4-11e9-8495-0cc21e20011d.png)

**Comment by dmastag** [comment]
I was changing the source in 
node_modules/primeng/components/editor/src/app/components/editor/editor.js 

from
```
this.quill = new quill_1.default(editorElement, {
```

into
```
this.quill = new quill_1(editorElement, {
```

And got it working, which is weird

**Comment by dmastag** [comment]
@cagataycivici 
Tried with the latest 8.0.0 Release

https://stackblitz.com/edit/angular-u48wcb
Still not working

All, do I need to open a new Ticket since this one has been Closed by @cagataycivici  ?

**Comment by dmastag** [comment]
New update
I tried to update my project that had the problem from primeng@8.0.0-rc.1 to primeng@8.0.0
And the issue went away

Though it is not working on the stackblitz I sent earlier.

@fernandogomesdf @Vendium @McGiogen 
Would you mind to test also ?

**Comment by EngAhmedShehatah** [comment]
I have the same error in a project of mine 

The output of `ng version` is :
Angular CLI: 8.0.2
Node: 12.4.0
OS: linux x64
Angular: 8.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.2
@angular-devkit/build-angular     0.800.2
@angular-devkit/build-optimizer   0.800.2
@angular-devkit/build-webpack     0.800.2
@angular-devkit/core              8.0.2
@angular-devkit/schematics        8.0.2
@angular/cli                      8.0.2
@angular/http                     7.2.15
@ngtools/webpack                  8.0.2
@schematics/angular               8.0.2
@schematics/update                0.800.2
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0

---------------------------------------------
I am using charts in my projects as well, when I install primeng@8.0.0, the charts had been corrupted with ugly background. On the previous solution of modifying the editor/editor.js file, the charts and everything else is working fine in my project.

So, I don't think that the perfect solution is to remove primeng@8.0.0-rc.1 and install primeng@8.0.0 instead.
