### ISSUE TITLE
Add showAll option for rowsPerPage to Paginator

### ISSUE THREAD

**Issue by krojew** [primefaces/primeng#7770]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Paginator only seems to support integer rows per page.

**Expected behavior**
In addition to current behavior, it would be great to also support the 'All' option.

**What is the motivation / use case for changing the behavior?**
There is currently no way to show all data on a single page which uses pagination.

* **PrimeNG version:** 7.1.2

* **Browser:** all
 
* **Language:** all

**Comment by PavelMetelsky** [comment]
@mertsincan Сould you add this feature to the some version PrimeNG for angular 7?
