### ISSUE TITLE
Horizontal scrollbar on the top and on the bottom of primeng/table.

### ISSUE THREAD

**Issue by StPaulis** [primefaces/primeng#7776]
[ ] bug report 
[X ] feature request 
[ ] support request 
---

I am submitting a feature request for supporting horizontal scrollbar on the top and on the bottom of primeng/table.

**Comment by mertsincan** [comment]
Unfortunately, we don't think of adding these feature to core. I think you can do it yourself. Exp; https://stackoverflow.com/a/3935190

Best Regards,

**Comment by StPaulis** [comment]
Because I didn't wanted to use JQuery, the solution that worked for me was some lines below.

[https://stackoverflow.com/questions/3934271/horizontal-scrollbar-on-top-and-bottom-of-table/47038108#47038108](url)

Thank you,

**Comment by StPaulis** [comment]
Sorry the link was broken :/ 

I edited my previous comment.
