### ISSUE TITLE
Textarea AutoResize Improvements

### ISSUE THREAD

**Issue by JacobSiegle** [primefaces/primeng#7778]
1) If you add multiple new lines to auto resize and then remove them it does not properly size down.

2) Since the auto resize doc says [rows] is a required parameter. The rows parameter should be respected as the min that auto resize can shrink to.

**Comment by yigitfindikli** [comment]
Fixed in https://github.com/primefaces/primeng/commit/fc1fa72ceb84dbc6707ffbad5e5b6a2d6bf6e296 .
