### ISSUE TITLE
p-dropdown letter key typing search not support international letter

### ISSUE THREAD

**Issue by apicpich** [primefaces/primeng#7779]
I have use p-dropdown with international (Thai) language options lists but it seem not to support for first letter key typing search in that language. When I change options to english options lists it's work perfectly.

PS. I look in dropdown.ts at search(event) function and see -
"const char = String.fromCharCode(event.keyCode);"
Is this String.fromCharCode() not support for international letter?

**Comment by mertsincan** [comment]
> Is this String.fromCharCode() not support for international letter?
I researched this issue and found the following issue;
https://stackoverflow.com/questions/31475747/convert-this-unicode-to-string-with-javascript-thai-language/31475889#31475889
Could you please try the solution in the above link? Then, you can send a PR about it.

For now, the github label is "cannot replicate" for this issue.

Best Regards,

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
