### ISSUE TITLE
Narrator is not able to read performed sort action on sortable turbo table column header

### ISSUE THREAD

**Issue by manidevzen3** [primefaces/primeng#7782]
[ x ] bug report 

**Current behavior**
after performing sorting action on turbo table column header, narrator is not reading action performed

**Expected behavior**
after sorting a column narrator should read the action performed

**Minimal reproduction of the problem with instructions**

- Start the narrator
- focus to the sortable column header (try on defined ariaLabel, ariaLabelDesc, ariaLabelAsc columns)
- perform sort action and observe the narrator is able to read sort action 

**What is the motivation / use case for changing the behavior?**
Visually impaired users might not known that column headers got sorted if narrator does not announce action performed​

* **Angular version:** 6.1.9

* **PrimeNG version:** 6.1.7

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mertsincan** [comment]
Hi,

Which screen reader are you using? JAWS, NVDA or the another ?? Sometimes screen readers may behave differently in this case.

Best Regards,

**Comment by manidevzen3** [comment]
I am using Narrator Screen reader

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
