### ISSUE TITLE
Add onRowFocus event to Table

### ISSUE THREAD

**Issue by filip12345678910** [primefaces/primeng#7783]
Currently, you can use keyboard arrows to navigate through p-table. In the first example here, you focus on the rows with arrows and then you press enter:
https://www.primefaces.org/primeng/#/table/selection

But I want to be able to navigate through the rows directly, without the need to press Enter. I think a general solution might be to add (onRowFocus) which would emit the newly focused row. And I would react to it by assigning the emitted value to the selection.

(we are currently hacking p-table, going inside the html, but it's not a nice workaround)

**Comment by filip12345678910** [comment]
although the enter would still emit onRowSelect which would be annoying, so maybe it would be better to add something like "typeOfSelection"

**Comment by filip12345678910** [comment]
or maybe [typeOfSelection]

**Comment by mertsincan** [comment]
Hi @filip12345678910,

Maybe, the "onRowFocus" callback can be added for this issue. Users can decide the selected rows with it. Otherwise, selecting directly on focus can cause confusion on multiple row selection.

Best Regards,

**Comment by filip12345678910** [comment]
It could also be a new selectionMode ("single-direct") which besides direct selection by arrows, would disallow unselection. We are currently using metaKeySelection true and don't use the meta key to make it look that unselection is forbidden.

**Comment by cagataycivici** [comment]
If there is more demand, we'll reconsider the request, thank you.
