### ISSUE TITLE
Accessibility: Scrollable table: Narrator not able to read table data appropriately

### ISSUE THREAD

**Issue by manidevzen3** [primefaces/primeng#7784]
[ x ] bug report

**Current behavior**

- When the narrator focus comes to table header it is announcing as x columns and 1 rows
- When the narrator focus at any of the cell in table, it is not announcing appropriate column header name

**Expected behavior**
any screen reader should able to announce the appropriate number of rows and corresponding column header of the cell

**Minimal reproduction of the problem with instructions**

- Navigate to https://www.primefaces.org/primeng-6.1.6/#/table/scroll
- Start the narrator and move focus through scroll table header cells and body cells

**What is the motivation / use case for changing the behavior?**
Visually impaired users finds difficult in understanding about the table data if narrator does not read its corresponding column header​

* **Angular version:** 6.1.9

* **PrimeNG version:** 6.1.7

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
