### ISSUE TITLE
How to set a default value in multiSelect?

### ISSUE THREAD

**Issue by idjosinei** [primefaces/primeng#7786]
I am using multiSelect in a form, I need to do CRUD. I have no problems creating the data, my difficulty is in updating the data, because I can not set a default value in multiselect ... Can anyone help me?

I'm sorry if I have not expressed myself correctly in English; I am Brazilian.

**Comment by JacobSiegle** [comment]
Please explain the issue more in depth or read https://www.primefaces.org/primeng/#/multiselect.  You can set [(ngModel)]="selectedCities1" or set the form control value. Sounds like a question not an issue, should be closed.
