### ISSUE TITLE
PrimeNG calendar not supporting manual edition of dates if date format contains commas

### ISSUE THREAD

**Issue by vinlos** [primefaces/primeng#7787]
**I'm submitting a...**
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**stackblitz Case (Bug Reports)**
https://stackblitz.com/edit/primeng-calendar-date-comma
it defines a PrimeNG calendar with **multiple selection** and a date format contianing **commas 'MM d, yy'**

**Minimal reproduction of the problem with instructions**
PrimeNG calendar has some issues in handling date formats containing commas. Try to reproduce the issue with the following steps

1.  Select some dates
2.  Manually edit one of the selected dates
3.  Click outside the calendar input

**Current behavior**
Once the input looses the focus the old date is reset in the text input and the model is not updated

**Expected behavior**
If the new date respects the new format, the model should be updated accordingly and the text input should not change 

**What is the motivation / use case for changing the behavior?**
Date formats with commas, like 'MM d, yy'

**Please tell us about your environment:**
- Windows 10
- Visual Studio Code

* **Angular version:** 7.2.5 (but there's no relation with Angular version)

* **PrimeNG version:** 7.1.3

* **Browser:** [ all ]
 
* **Language:** [ all ]

**Comment by yigitfindikli** [comment]
fixed in https://github.com/primefaces/primeng/commit/be6e4e5750dc2f58a0245719a1d11dae83031c30
