### ISSUE TITLE
Cannot find name 'MenuItem'

### ISSUE THREAD

**Issue by chakradharib** [primefaces/primeng#779]
**menu.component.ts(13,27): error TS2304: Cannot find name 'MenuItem'**

```
import {Component} from '@angular/core';
//import {MenuItem} from 'primeng/components/common';
import {PanelMenu} from 'primeng/primeng';
import {HTTP_PROVIDERS} from '@angular/http';
import {MenuItem} from 'primeng/primeng';

@Component({
    selector:'menu-app',
    templateUrl:'./app/menu.component.html',
    directives:[PanelMenu,MenuItem],
    providers:[HTTP_PROVIDERS]
})
```

How can we fix this?

**Comment by StefH** [comment]
This should just work fine for latest primeng.
Maybe use 
`import { PanelMenu, MenuItem } from 'primeng/primeng';` ?

And I don't think you need to use **directives** for these 2 items. They are just classes?

**Comment by chakradharib** [comment]
Thanks, it is working
