### ISSUE TITLE
Different styling for AutoComplete EmptyMessage

### ISSUE THREAD

**Issue by labbe-d** [primefaces/primeng#7791]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**What is the motivation / use case for changing the behavior?**
When using a template with p-autoComplete that brings its own styling, it is impossible to apply a similar styling to the EmptyMessage element only. The li element has the same classes whether it's used for suggested items or for EmptyMessage which impacts the templated elements.

A unique class for EmptyMessage or the ability to use a template instead of a string would allow different styling.

* **Angular version:** 7.X

* **PrimeNG version:** 7.X

**Comment by mertsincan** [comment]
You're right! Fixed now.

Best Regards,
