### ISSUE TITLE
Drag and Drop is not working in OrderList in Firefox web browser

### ISSUE THREAD

**Issue by knavadiya** [primefaces/primeng#7793]
I am using OrderList from here [https://www.primefaces.org/primeng/#/orderlist](url) in my project. Drag and Drop item is working in chrome, Safari, IE but not working in Firefox Browser. 

If you open above link in chrome, item will reorder using Drag and Drop but in Firefox it will not work.

**following is my environment:**

* **Angular version:** 7.2.2

* **PrimeNG version:** 7.0.0

**Comment by dARKaRK** [comment]
Not working for me too.... Not working in primefaces site also when using firefox.... v6 is working... only difference is the property dragdropScope property which is absent in v7

**Comment by zLAs3R** [comment]
Hi,
still have the very same issue with PickList in v8.1.1

**Comment by dmartinezzm** [comment]
Hi, still having this issue in v16.3.1, any solution?? Thanks in advance
