### ISSUE TITLE
p-treetable rows not rendering above 1000 columns

### ISSUE THREAD

**Issue by pradish-p** [primefaces/primeng#7794]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Waiting Time: ~8 weeks.

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
Minimal reproduction of the problem with instructions
![treeTable1000](https://user-images.githubusercontent.com/14366078/59184940-d7941800-8b8c-11e9-8acf-b177d9c49d67.png)

**Current behavior**
Columns that are above 1000 does not render properly.
some of the rows of columns above 1000 are missing.

**Expected behavior**
should render columns above 1000 with its rows.

**Please tell us about your environment:**
Angular version: 4.3.0
PrimeNG version: 4.3.0
Browser: all
Node: 7.10.0

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
