### ISSUE TITLE
Times between 12:00AM-12:59AM save as PM when defaulted or typed in

### ISSUE THREAD

**Issue by stanglersm** [primefaces/primeng#7799]
**I'm submitting a ...** 
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
You type an AM time into the field after a PM time exists or no time is selected and the time in PM is maintained and saved.
You have a default time of 12:00AM and you select any date and the time saved is in PM
![image](https://user-images.githubusercontent.com/32472795/59215623-4bc7bf00-8b7f-11e9-818a-f2f9e2b1a57e.png)

**Expected behavior**
You type an AM time into the field after a PM time exists or no time is selected and the AM time is maintained and saved.
You have a default time of 12:00AM and you select any date and the time saved is in AM

**Minimal reproduction of the problem with instructions**
Either
- Prepare a defaultDate attribute with the time set to midnight (12:00AM) by using .setHours(0, 0, 0)
- Open p-calendar and select any date
- See that the time displayed in the text field is in PM time

OR
- Open p-calendar and select any date
- Select a time between 12:00AM and 12:59AM (using arrow selectors)
- Click off calendar (at this point, you could save the form or whatever you'd like to get back to editing, or just simply click off)
- Reopen calendar and select another date
- See that the time displayed in the text field has changed to PM time

**What is the motivation / use case for changing the behavior?**
So that we can default a date to have a time of midnight that day if a time is not identified by the user

**Please tell us about your environment:**
Windows, IntelliJ, HTTP, p-calendar is in a drawer and within a form

* **Angular version:** 6.0

* **PrimeNG version:** 6.1

* **Browser:** [ Chrome 75 ]
 
* **Language:** [ TypeScript 3.2.4 ]

* **Node (for AoT issues):** `node --version` =

**Comment by yukelele** [comment]
@mertsincan Can this fix be applied for PrimeNg version 7.3.9? If so, when can it be done? We are using Angular 7 for our app.

**Comment by stanglersm** [comment]
@mertsincan We upgraded our app to the latest primeng and have found that the issue is still not resolved.

Is the scenario that is breaking here clear?

To be clear:
- Create a date & time picker in 12 hour format
- Use date & time picker in input field that displays dynamically (not a static calendar)
- Open date & time picker in application
- Select a time between 12:00AM-12:59AM
- Click off calendar & see that the time displayed in the input field is in PM

Please let me know if you are not able to reproduce the issue.

**Comment by stanglersm** [comment]
After some further investigation, we see that the problem persists with TYPING in 12:00AM-12:59AM times, but it is fixed for the time selector in the popup. 

My apologies for not clarifying that in my initial comment.

**Comment by stanglersm** [comment]
One of my colleagues is working on a PR of his own that we believe will resolve the typing problem.
