### ISSUE TITLE
eventDataTransform callback for Schedule

### ISSUE THREAD

**Issue by yehudag** [primefaces/primeng#780]
The Schedule component is missing the eventDataTransform callback. This hook allows you to pass in arbitrary objects to Fullcalendar and transform it into the type of data FullCalendar accepts. More info at [http://fullcalendar.io/docs/event_data/eventDataTransform/](http://fullcalendar.io/docs/event_data/eventDataTransform/)

**Comment by cagataycivici** [comment]
Reviewed this and decided to keep it as it is, there are to ways to use this anyway;

1) Options property where you can use eventDataTransform as schedule provides a way to define any fullCalendar property using the options property.

2) Schedule is a wrapper anyway, you can do the transform at your angular component and then pass it to the schedule.
