### ISSUE TITLE
Draggable and Resizable DynamicDialog

### ISSUE THREAD

**Issue by sgentile** [primefaces/primeng#7811]
Is there a property that can be set to allow the dynamic dialog to be draggable in the same way the dialog is draggable ?

**Comment by Vendium** [comment]
Yes should be very nice!

**Comment by Ox01** [comment]
Are there any updates on this?

**Comment by djay1977** [comment]
For Angular 9 & Ivy, Dialog has been rewritten.
Is-it possible to rewrite DynamicDialog in order to have the same functionality as the classic dialog ?
Thanks

**Comment by DReiser7** [comment]
I'm also looking forward to see the DyanmicDialog with the same functionality as the classic Dialog.

**Comment by armandQ** [comment]
Here is a piece of code on Medium that responds exactly to this use case : [medium.com draggable-directive-and-how-to-make-angular-material-dialog-draggable](https://medium.com/@OlegVaraksin/draggable-directive-and-how-to-make-angular-material-dialog-draggable-b112fa588bca).
the implementation uses an Angular Directive. The code has to be a little bit adjusted: it uses the old syntax of ngrx and the dragHandle/dragTarget should be .p-dynamic-dialog

I hope this helps :)

**Comment by eliassparagis** [comment]
> Here is a piece of code on Medium that responds exactly to this use case : [medium.com draggable-directive-and-how-to-make-angular-material-dialog-draggable](https://medium.com/@OlegVaraksin/draggable-directive-and-how-to-make-angular-material-dialog-draggable-b112fa588bca).
> the implementation uses an Angular Directive. The code has to be a little bit adjusted: it uses the old syntax of ngrx and the dragHandle/dragTarget should be .p-dynamic-dialog
> 
> I hope this helps :)

thank you helped me!
I made a change `dragTarget=".p-dynamic-dialog" dragHandle=".p-dialog-header"` because I had an issue with textarea.

**Comment by jonnomk** [comment]
+1

**Comment by ThoSap** [comment]
+1

**Comment by djay1977** [comment]
I hope this feature will be developed for a 13.x version because it has been postponed since release 9

**Comment by RodolfoXDR** [comment]
+1

**Comment by duongminhthuan1478** [comment]
I hope you support draggable in thiss year :(

**Comment by RodolfoXDR** [comment]
Any updates on this feature request?

**Comment by KiranPurbey1993** [comment]
with Directive we can able to make Prime ng  Dynamic Dialog draggable.
It is working perfectly in my project

**Comment by sgentile** [comment]
Thanks - this was posted in 2019

**Comment by djay1977** [comment]
Why closed this issue ?
We still don't have a component-level solution to maximize, collapse and move the dialog like the classic Dialog.
Why not implement the same functionality for the DynamicDialog

**Comment by sgentile** [comment]
I’m no longer using primeng and they haven’t addressed this issue in 2 years so maybe someone else can push them to provide this feature.

**Comment by jonnomk** [comment]
> with Directive we can able to make Prime ng Dynamic Dialog draggable. It is working perfectly in my project

But what happens when you close the dialog? This directive uses transforms to move the draggable item around, but the dialog uses left/right positioning. This means when you close the dialog, it shoots back to the center and then animates out.

**Comment by ThoSap** [comment]
Please reopen this issue @cetincakiroglu @yigitfindikli @mertsincan

**Comment by RodolfoXDR** [comment]
+2

**Comment by Infy2020** [comment]
Primeng v15.2.0 available draggable properties. but we should enable dynamic dialog header. I tried other draggable plugin, it's not working in primeng. the requirement is should draggable dynamic dialog without enable header.

**Comment by Infy2020** [comment]
Also we can draggable dynamic dialog using header. if move the mouse to body content then draggable icon disappeared.

**Comment by JimTudeski** [comment]
Any updates on this feature request? Why closed this?
