### ISSUE TITLE
Customizable hideTimeout for Menubar

### ISSUE THREAD

**Issue by irekBudzowski** [primefaces/primeng#7814]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
Currently, there is no option to set hideTimeout for the p-menubar onItemMouseLeave.
That would be great to have the submenu visible a bit longer time.

**Comment by johanehm** [comment]
Is there any solution to this? I have a problem with the time the menu hides after the mouse leaves the zone in Firefox & Edge, but not on Chrome. Basically when the mouse goes to the second line of the submenu on Firefox and Edge, the submenu dissapears. the only way that I can let the menu open is to move the mouse really really fast befor it dissapears. It's not dissapearing/hiding if I leave the mouse hovering the first Item of the menu, but if i go to the next one, it works as if I moved outside of the submenu. 

this is my model for the menubar
`this.items = [
          {
            label: 'Action Types',
            items: [
              {
                label: 'Action 1',
                routerLink: ['/action/type1'],
                routerLinkActiveOptions: {
                  exact: true
                },
                styleClass: 'menucus'
              },
              {
                label: 'action 2',
                routerLink: ['/action/type1'],
                routerLinkActiveOptions: {
                  exact: true
                },
                styleClass: 'menucus'
              }
            ],
          },
          {
            label: 'Options',
            routerLink: ['/options'],
            routerLinkActiveOptions: {
              exact: true
            },
            styleClass: 'menucus',
          },
          {
            label: 'About',
            routerLink: ['/about'],
            routerLinkActiveOptions: {
              exact: true
            },
            styleClass: 'menucus',

		}
    ];`

this is my template: 
`<section>
  <div id="menu-box2">
    <div class="container menucus">
      <div class="row">
        <div class="col-12">
          <p-menubar #menu [model]="items" StyleClass="menucus"></p-menubar>
        </div>
      </div>
    </div>
  </div>
</section>

<router-outlet></router-outlet>`

This is my css (had to change the colors to match the rest of the app)
`::ng-deep .ui-menu,.ui-menu .ui-menu-child{
    border: 0px;
    background:#5393bc 0 0 repeat-x !important;
}
::ng-deep .ui-menu .ui-menuitem .ui-menuitem-link:hover{
    background-color: #5393bc;
    border: none;
}
::ng-deep .ui-menu .ui-menuitem .ui-state-active{
    background-color: #5393bc;
}
::ng-deep .ui-menu .ui-menuitem.ui-menuitem-active>.ui-menuitem-link,
.ui-menu .ui-menuitem .ui-menuitem-link:hover{
    background-color:#186ba0;
    border: none;
}
::ng-deep .menucus{
    background: #5393bc !important;
}
::ng-deep .ui-menu .ui-menuitem-parent, .ui-menu .ui-menuitem{
    margin: auto;
}  
::ng-deep .ui-menuitem .ui-widget .ui-corner-all { 
    border-radius:0;
}

::ng-deep .ui-menu .ui-menu-parent .ui-menu-child{
    padding: 0;
}`

is it something wrong I'm doing here? i know it is an old version but at my place we can't update to newer versions, so I need to find a solution with this version. 

The other thing i see is that maybe I'm using the submenu wrongly, cause if I don't use the css, the only subitem that gets a background is the first one of the submenu and the others get a trasparent background, as if those are not part of the subitem. 

Thanks for your time.

**Comment by cagataycivici** [comment]
Menubar does not hide the menus at mouseleave since PrimeNG 8.
