### ISSUE TITLE
 Autocomplete overriding input value from hovered value of suggestions (on enter)

### ISSUE THREAD

**Issue by i-amn** [primefaces/primeng#7817]
**MAYBE ITS ACTUALLY CODED LIKE IT BUT I WANT A SOLUTION**

My problem : I'm using autocomplete like drop down because of this issue in drop down

https://github.com/primefaces/primeng/issues/6913

In autocomplete when some suggestion is populated (suggestion is not hiding itself on type of new keywords in the text field) and I am entering some text in the text input box in autocomplete and my mouse pointer is at some suggestion, now when I'm hitting enter then the mouse pointer / hovered value overrides the entered value in the text box.

Is there any solution?.

You can check the behaviour here

Steps to reproduce

type something in input box

2 hover on any suggestion

3 type enter

you will see : the input box text value exchange itself from hovered text

https://www.primefaces.org/primeng/#/autocomplete

I have tried lots of thing, i thought on hover of mouse it is setting its model to its internal model but that is not the case, onenter it is somehow copying the hovered variable to the input box internally

**Comment by cagataycivici** [comment]
This is by design, highlighted item is selected with keyboard. There is no different hover state.
