### ISSUE TITLE
p-table onRowReorder I can drop the row on Field with Text

### ISSUE THREAD

**Issue by piotpap663** [primefaces/primeng#7818]
**Current behavior**
I can drop the row on the field with text and it adds 'b' to string

**Expected behavior**
I can't drop the row on text fields

* **Angular version:** 7.1.4

* **PrimeNG version:** 7.1.3

**Comment by GoGoris** [comment]
Confirmed: still present in PrimeNG 8.0.0

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
