### ISSUE TITLE
PrimeNG table lazy loading not working properly on setting the property first

### ISSUE THREAD

**Issue by msmani** [primefaces/primeng#7819]
We are using PrimeNG `<p-table>` component with `virtualScroll = true` & `lazy = true`. But it is not working in the following scenario.

Assume there are 100 records in total and the limit is 10. The user scrolls and sees an item at the offset 50 and he clicks the item and taken to the detail page of that item. Now when the user clicks the back button in the browser I need to bring him back to the same page he was looking in `<p-table>`, to do that I am setting the property `[first] = 50` and it is showing the correct page but when I scroll the event that is emitted contains offset 10 instead of 60, why is that?

**Comment by saurajit** [comment]
+1
When I and using server side pagination and I am setting `[lazy]="true" (onLazyLoad)="loadData($event)"` setting the `first` property does not make any sense as the data is coming from the APIs.

I need to be able to set the pagination programmatically.

**Comment by yuri1969** [comment]
Basically, now we are unable to perform a simple *data refresh* of a lazy table. The old `DataTable` had `dataChanged: boolean`  property which could be used for that. Now using `Table` even forcing table's paginator to `first = 0` doesn't trigger a lazy load.

**Comment by epoch79** [comment]
i think the problem here

 isFirstPage() {
        return this.getPage() === 0;
    }
it has to be 
 return this.getPage() === first;

**Comment by yuri1969** [comment]
@epoch79 Can you create a new PR featuring this fix?

**Comment by codehunter13** [comment]
+1 
setting first does nothing in our lazy loaded tables with virtual scroll. 
Our users have to scroll to see the selected item...

**Comment by cagataycivici** [comment]
VirtualScrolling for Table is reimplemented from the ground up (#8855) and this particular case i no longer an issue with the new implementation.

New implementation provides a method called **scrollToVirtualIndex** which should be preferred over **first** in scrolling.
