### ISSUE TITLE
Carousel: property access on undefined 'viewportViewChild' member.

### ISSUE THREAD

**Issue by cghislai** [primefaces/primeng#7825]
After upgrade to angular 8/primeng 8, the carousel threw exceptions:
```
TypeError: Cannot read property 'nativeElement' of undefined
    at Carousel.setPage (carousel.js:162)
    at Carousel.handleDataChange (carousel.js:65)
    at Carousel.set [as value] (carousel.js:53)
    at updateProp (core.js:19547)
    at checkAndUpdateDirectiveInline (core.js:19318)
    at checkAndUpdateNodeInline (core.js:27597)
    at checkAndUpdateNode (core.js:27559)
    at debugCheckAndUpdateNode (core.js:28193)
    at debugCheckDirectivesFn (core.js:28153)
    at Object.eval [as updateDirectives] (BankAccountsBalancesCarouselComponent.html:10)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:28145)
    at checkAndUpdateView (core.js:27541)
    at callViewAction (core.js:27782)
    at execEmbeddedViewsAction (core.js:27745)
    at checkAndUpdateView (core.js:27542)
```

It has to be noted that this carousel is used in dynamic components, similar to the setup described there: https://angular.io/guide/dynamic-component-loader

The parent component creates/detach/destroy/insert rendered ViewRefs depending on some user actions. The Carousel component may thus not be attached to the dom when instanciated.

**Comment by cghislai** [comment]
This seems to occur when the [value] is bound asynchronously. 
I had trouble reproducing the exact same single issue that occurs locally, but there it is: https://stackblitz.com/github/primefaces/primeng-issue-template?file=src%2Fapp%2Fapp.component.ts

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template

**Comment by tonnguyen** [comment]
I have created a new issue, with reproducible stackblitz: https://github.com/primefaces/primeng/issues/8009

**Comment by ranaivomahaleo** [comment]
FIX:
Let us consider the following component:
```
<p-carousel [value]="carouselitems" breakpoint="1200" numVisible="2">
...
</p-carousel>
```
The error I had is below when loading carouselitems from Observable (asynchronously).
```
ERROR TypeError: "this.viewportViewChild is undefined"
    setPage carousel.js:162
    handleDataChange carousel.js:65
    set carousel.js:53
    Angular 6
    View_UserlistComponent_0 UserlistComponent.html:55
    Angular 29
    RxJS 5
    Angular 8
```
To fix the above error, init first outside the observable pipe the carouselitems with at least one item. See the code below

```
ngOnInit() {

  // Init with at least one item outside the observable subscribe
  this.carouselitems = [
    oneitem
  ];
  ...
  // Re-init with data from observable
  obs.subscribe( (data) => {
    ...
    this.carouselitems = data;
    ...
  }
  ...
}
```
