### ISSUE TITLE
Provide all injectable in root injector

### ISSUE THREAD

**Issue by FabienDehopre** [primefaces/primeng#7826]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
You have to provide all the injectables manually in the module or component where you need them because there are not provided by any module in the primeng library.

**Expected behavior**
You should provide all the injectables in the root injector by using the `{ providedIn: 'root' }` meta data on the `@Injectable()` decorator (i.e.: `@Injectable({ providedIn: 'root' })`).
This way, your services are always available and will be tree-shakeable when not used.

**What is the motivation / use case for changing the behavior?**
Make the life of the developers easier ;-)

**Please tell us about your environment:**
N/A

* **Angular version:** 5.X
7.x and later

* **PrimeNG version:** 5.X
All compatible with Angular 7.x and later

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

* **Node (for AoT issues):** `node --version` =   
N/A

**Comment by cagataycivici** [comment]
This may cause backward compatibility issue we rather not do a change here.

**Comment by rafa-as** [comment]
> This may cause backward compatibility issue we rather not do a change here.

maybe in a major release?
