### ISSUE TITLE
Way to choose when the overlay will appears in Autocomplete

### ISSUE THREAD

**Issue by NathanAlcantara** [primefaces/primeng#7827]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**What is the motivation / use case for changing the behavior?**
There are sometimes that it's more convenient i choose the position of overlay (top, or bottom) but i can't today

* **Angular version:** 7.X

* **PrimeNG version:** 7.X

* **Browser:** all

* **Language:** all

* **Node (for AoT issues):** `node --version` =  v10.13.0

**Comment by yigitfindikli** [comment]
We'll reconsider if there is more community feedback on this. Thank you for your report.
