### ISSUE TITLE
Problem with setting the width of a p-dialog

### ISSUE THREAD

**Issue by filip12345678910** [primefaces/primeng#7830]
We used [width]="3000", but width is deprecated, so we wanted to change it to [style.width]="3000", but that doesn't work. 

[style]="{width: '3000px'}" works
width="3000" works
[style.width]="'3000px'" doesn't work
[style.width.px]="3000" doesn't work

The [style]="{width: '3000px'}" is not very pretty, the width="3000" looked better. Can you make [style.width] (and minWidth) work or undeprecate [width]?

Examples:
https://stackblitz.com/edit/github-yyeq1x
You have to make the show screen bigger, otherwise the p-dialog takes the width of the screen.

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
