### ISSUE TITLE
Overlay panel arrow displayed on the wrong side in IE

### ISSUE THREAD

**Issue by AlekKj** [primefaces/primeng#7832]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior:** 
1. Open the link in Internet Explorer: https://www.primefaces.org/primeng/#/overlaypanel
2. Click on any search icon you want.
3. Notice that the arrow has been display on the wrong side.

**Expected behavior:** 
Expect to have the arrow on the correct place, as it behaves on the other browsers (Chrome,  Edge...)

**What is the motivation / use case for changing the behavior?**
Consistency and better looking design! It should behave like it is in the other browsers. 

**- Angular version: 8.X**
**- PrimeNG : 7.X**
**- Browser: Internet Explorer 11**
**- Language: all**

**Comment by surensubhu** [comment]
Any workaround for this issue?

**Comment by surensubhu** [comment]
@cagataycivici Is it possible to push this change to 7.x.x? As we are still using Angular 7 and no plans to use Angular 8 near soon.
