### ISSUE TITLE
PrimeNG p-table column resize not working in Mobile and tablet devices

### ISSUE THREAD

**Issue by NimmyValsan** [primefaces/primeng#7835]
I am using PrimeNG p-table to display a table of data in my Angular 6 project. Column resizing of the table works perfectly in the desktop version. But in Mobile and Tablet view , it does not give me the option to resize. Below is my code :
       
	<p-table #dtTable [columns]="selectedColumns" resizableColumns="true" (sortFunction)="customSort($event)" [customSort]="true" [style]="{width:'100%'}" [(selection)]="selectedItem" [rowHover]="true" [dataKey]="tableKey" [value]="tableData" [scrollable]="true" [ngClass]="!headerExpandFlag?'ptable-main-expand-cls':'ptable-main-cls'" scrollHeight="250px" >
      <ng-template pTemplate="colgroup" let-columns>
        <colgroup>
          <col *ngFor="let col of columns" >
        </colgroup>
      </ng-template>

      <ng-template pTemplate="header" let-columns>
        <tr>
          <th>
            <p-tableHeaderCheckbox (click)="toggleSelect(rowData,$event)"></p-tableHeaderCheckbox>
          </th>
          <th *ngFor="let col of columns" pResizableColumn pReorderableColumn  [pSortableColumn]="col.field" >
            {{col.header}}
            <p-sortIcon [field]="col.field" ariaLabel="Activate to sort" ariaLabelDesc="Activate to sort in descending order" ariaLabelAsc="Activate to sort in ascending order"></p-sortIcon>
          </th>

        </tr>
      </ng-template>

      <ng-template pTemplate="emptymessage">
        <div class="empty-message-week" >
          <span class="empty-txt"> No Record Found </span>
        </div>
      </ng-template>

      <ng-template pTemplate="body" let-rowData let-rowIndex="rowIndex" let-columns="columns" class="ui-resizable-column">
        <tr [pSelectableRow]="rowData" (click)="onRowClick($event,rowData)">
          <td>
            <p-tableCheckbox (click)="toggleSelect(rowData,$event)" [value]="rowData"></p-tableCheckbox>
          </td>

          <td *ngFor="let col of columns" [ngClass] = "displayColor(col.field, rowData)"  (click)="openLink(rowData,col.field,$event)">
            <span  pTextEllipsis matTooltipClass="tool-tip" [matTooltip]="rowData[col.field]" [matTooltipPosition]="'above'" >
              {{rowData[col.field]}}
            </span>
          </td>
        </tr>
      </ng-template>
      <ng-template pTemplate="footer" >
        <div fxLayout="row" class="caption-style"></div>
      </ng-template>

    </p-table>

**Comment by cagataycivici** [comment]
In mobile, table should go in responsive mode as a best practice so resizable columns are not supported.
