### ISSUE TITLE
p-spinner min validator works only for first time

### ISSUE THREAD

**Issue by SaraPrager** [primefaces/primeng#7839]
**I'm submitting a bug report**

**Current behavior**
`<p-spinner class="ui-spinner" min="30" max="999" maxlength="3"></p-spinner>`
When typing 22 it becomes 30, then when updating it again to 22 it stays 22.

**Expected behavior**
It should be fixed to 30 for each less than min numbers.

* **Angular version:** 7.X
* **PrimeNG version:** 8.0.0

**Comment by yigitfindikli** [comment]
Hi,
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
