### ISSUE TITLE
Table filter change detection race condition

### ISSUE THREAD

**Issue by krojew** [primefaces/primeng#7842]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
When table filters data, especially restoring filter from state, it explicitly triggers change detection (`this.cd.detectChanges();` in `_filter()`). This can cause detection on views which were just destroyed, e.g. the sidebar being just hidden, which results in "change detection on destroyed view" error. This is a typical race condition which is very hard to replicate, yet it happens from time to time. It's better to postpone change detection with a timeout.

**Expected behavior**
Change detection is triggered asynchronously, thus giving views time to settle.

**Minimal reproduction of the problem with instructions**
Create a table and a sidebar. Make the table remember filter state and make the sidebar going from visible to hidden when the table gets created and restores state. The error can sometimes happen.

**What is the motivation / use case for changing the behavior?**
Triggering change detection properly.

* **Angular version:** 8.0.1

* **PrimeNG version:** 8.0.0

* **Browser:** all
 
* **Language:** TypeScript

* **Node (for AoT issues):** `node --version` =   v12.4.0

**Comment by GoGoris** [comment]
Calling markForCheck instead should also prevent this from happening, I don't think that a timeout is needed.

**Comment by tytusplanck** [comment]
Is anyone aware of a work around for this in test files? We are having tests fail after upgrading to PrimeNG 8.0 that fail because of this issue. We are attempting to make sure our filtering functionality works.

**Comment by krojew** [comment]
Any chance of this being fixed? I get a ton of errors each time table is used with any kind of overlay panel. This fix is a one-liner.

**Comment by ribizli** [comment]
@cagataycivici could you please prioritize this issue?
