### ISSUE TITLE
ConfirmDialog is not centred at the beginning in safari browser

### ISSUE THREAD

**Issue by piotpap663** [primefaces/primeng#7845]
How to reproduce ?
Go to [https://www.primefaces.org/primeng/#/confirmdialog](https://www.primefaces.org/primeng/#/confirmdialog) in safari browser
click Delete button
![modalbugfin](https://user-images.githubusercontent.com/15015936/60094235-c7169c80-974b-11e9-952b-2a034de5144a.gif)

Current behaviour
At first ConfirmDialog opened somewhere in the right corner then it is centered

Expected behaviour
ConfirmDialog is centred
Angular version: 7.1.4

PrimeNG version: 7.1.3

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
