### ISSUE TITLE
Add event listener dynamically

### ISSUE THREAD

**Issue by dsilvestregil** [primefaces/primeng#7846]
There is a way to add an event Listener in p-table dynamically?
Only is working for original events.

**For example, this works fine:**

    **HTML:** 
        <p-table id="table"></p-table>
    **TS:**
        const tableElement = document.getElementById('table');
        tableElement.addEventListener('click', () => console.log('I print this'));

**But this doesn't work:**

    **HTML:** 
        <p-table id="table"></p-table>
    **TS:**
        const tableElement = document.getElementById('table');
        tableElement.addEventListener('onRowUnselect', () => console.log('I don\'t print this'));

I try to do it in HTML directly too like this:

**HTML:** 
    <p-table id="table" (onRowUnselect)="contidtion ? onRowUnselect($event) : undefined"></p-table>

This works fine, if condition is false doesn't execute any code but the listener is created anyway, and consumes memory. I can check it by this:
    getEventListeners(document.getElementsById('table'))

How can I do it? Any way¿?

**Comment by cagataycivici** [comment]
Please use forum for support requests and questions.
