### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError with autocomplete

### ISSUE THREAD

**Issue by Amosar** [primefaces/primeng#7849]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

I've done a small example to reproduce the issue, write 'user' into the box and click on one of the item displayed and it will trigger the error in the console
https://stackblitz.com/edit/github-thqtnx

**Current behavior**

The bug appear when I call another component and the autocomplete lose the focus

**Expected behavior**

no error

**Minimal reproduction of the problem with instructions**
You can reproduce the issue with this small project : 
https://stackblitz.com/edit/github-thqtnx
write 'user' into the box and click on one of the item displayed and it will trigger the error in the console

**What is the motivation / use case for changing the behavior?**
Remove an annoying error in the console

**Please tell us about your environment:**
Windows 10, Visual studio code, npm

* **Angular version:** 7.2.15

* **PrimeNG version:** tested with 7.1.0-rc.1 and 8.0.0

* **Browser:** Chrome 75 
 
* **Language:** TypeScript 3.1.6

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
