### ISSUE TITLE
Calendar with [timeOnly]="true" - cannot type the time in Chrome

### ISSUE THREAD

**Issue by mmalolepszy** [primefaces/primeng#785]
When you try to type into the input field of a calendar control with timeOnly parameter set to true, the input field loses focus after you type one character. The popup with sliders doesn't close, but the cursor disappears from input.

It can be reproduced on http://www.primefaces.org/primeng/#/calendar in Chrome 52.0.2743.116 m
Firefox 47.0.1 and IE 11 are both ok.

**Comment by ats17** [comment]
Also, in both Chrome and IE, entering a time and then clicking the Now button produces aN:aN:aN in the textbox, which cannot be removed without refreshing the browser.

Also, in IE, onmouseover and onmouseout events cause an annoying css flash that includes shrinking by a few pixels, which can affect layout of other elements.

Both of these behaviors can also be seen in the Time Only input on the Showcase calendar page.

**Comment by ats17** [comment]
A couple more issues:

Populating the control's value from code will display times that don't match the specified timeFormat if any of the hours, minutes, or seconds values is a single digit.
For example, in a control created with:
`<p-calendar class="filing-time-input" name="filingTime" [(ngModel)]="filingTime" ngDefaultControl dateFormat="mm/dd/yy" timeFormat="HH:mm:ss" [timeOnly]="true"></p-calendar>`
... setting filingTime to 09:05:34 will display 9:5:34 in the control.

Also, when opening, the control doesn't default to the value shown in the text box.

**Comment by mmalolepszy** [comment]
Looks like this issue comes from jQuery-Timepicker-Addon
https://github.com/trentrichardson/jQuery-Timepicker-Addon/issues/848

**Comment by cagataycivici** [comment]
Shoud be fixed in recent releases, please drop a comment if issue still persists and we may reopen. Note that we are not using jQuery for a long time for calendar so issue seems obselete.
