### ISSUE TITLE
p-spinner in reactive form is marked as valid before the invalid value is changed

### ISSUE THREAD

**Issue by SaraPrager** [primefaces/primeng#7852]
**HTML:**
`<form [formGroup]="myForm"><p-spinner class="ui-spinner" formControlName="myControlName" [min]="30" [max]="999" maxlength="3"></p-spinner><p-button type="button" label="Save" (click)="onSubmit()"></p-button></form>`

**TypeScript:**

`onSubmit() {
        if (this.myForm.invalid) {
            return;
        }
// Send http post request...
}`

**Current behavior**
When I type '20' (which is less than the minimum) -
'myForm' is marked as valid, the save works - and only then the visible value in the spinner is updated to the minimum value: 30.

**Expected behavior**
myForm should be marked as invalid as long as the visible value is not valid.

* **Angular version:** 7.X
* **PrimeNG version:** 7.1.0

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
