### ISSUE TITLE
Table saves 0 column widths and breaks layout

### ISSUE THREAD

**Issue by krojew** [primefaces/primeng#7853]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Table sometimes (not sure when) saves column width state as 0. This then causes problems when the state gets restored and someone changes with column width - the resized colum suddenly fills whole table width.

**Expected behavior**
Table never stores 0 column width state.

**Minimal reproduction of the problem with instructions**
Unsure what the circumstances are for 0 widths.

**What is the motivation / use case for changing the behavior?**
Fix column sizing.

* **Angular version:** 8.0.1

* **PrimeNG version:** 8.0.0

* **Browser:** Chrome
 
* **Language:** TypeScript

* **Node (for AoT issues):** `node --version` =   12.4.0

**Comment by mertsincan** [comment]
Hi,

Could you please attach a stackblitz link for us to replicate?

**Comment by krojew** [comment]
Unfortunately not, because I don't know under what circumstances 0 widths get saved. Currently I working around this bug by removing column widths from saved state before it gets loaded when any is 0. Maybe the solution would be not to save it when there are 0s present?

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
