### ISSUE TITLE
[Feature Request] DialogService ( Dynamic Dialogs) feature request resize, maximize, drag

### ISSUE THREAD

**Issue by mustafaerdogmus** [primefaces/primeng#7854]
```
[ x ] feature request => Please check if request is not on the roadmap already 
```

**Please tell us about your environment:**

* **Angular version:** 7.3.6

* **PrimeNG version:** 7.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =    11.1.0

Hi, I am using dialogservice. I think it would be wonderful
if you could have the features for resize, maximize, drag as p-dialog.  Do you consider add these  features

**Comment by cagataycivici** [comment]
#7811
