### ISSUE TITLE
Character Count

### ISSUE THREAD

**Issue by markleppke** [primefaces/primeng#7857]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
Having a twitter style or medium style character counter directive would be a great misc tool to add to the library. I see some Angular 1 options out there (http://sufiiiyan.github.io/Angular-character-count/) but I don't see many angular 2+ versions that are well done.

From a UX perspective, this might be some of the use cases (hope it helps):

1) Provide a user with an idea of how long before they reach the end of the characters that they can use
2) Help them know when they are getting close to the limit.
3) Let them know when they have exceeded the limit (that way they can finish their thought and then go back and revise their message, input text, etc.)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
