### ISSUE TITLE
DataTable: selecting a cell

### ISSUE THREAD

**Issue by nikita-perestoronin** [primefaces/primeng#786]
We are using PrimeNG DataTable and what we are missing is a functionality for working with a single cell. Selection works only with rows, there is no way to select a single cell, e.g.:

![cellselection](https://cloud.githubusercontent.com/assets/10209367/17969388/8424b704-6ada-11e6-9fdf-a486242e343c.png)

Also, there is no event like onCellClick which may allow to attach some custom logic to cell.

Is such feature considered or planned, or may be there is some easy workaround for such cases?

**Comment by lx1036** [comment]
Yeah, event on cell like onCellClick is important, but such feature is not fulfilled now. Hope such feature can be considered.

**Comment by cagataycivici** [comment]
We'll add this to upcoming spreadsheet component.

**Comment by mbuchner** [comment]
Could you be so kind and give us here an update? 
As far as I could see there is still no primeng spreadsheet component - is this still in development or do you suggest to use handsome table (like primefaces extensions spreadsheet does)  

Further more you state in the actual roadmap (https://github.com/primefaces/primeng/wiki/Roadmap) that TurboTable should get a cell selection - is there a known target version?

Anyway - Thanks for your good work
