### ISSUE TITLE
Name property is blank for checkbox present in multi select table

### ISSUE THREAD

**Issue by manidevzen3** [primefaces/primeng#7860]
**I'm submitting a ...**  (check one with "x")
```
[ x  ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
 
**Current behavior**
Name/Label property is blank for checkbox present in multi select table

**Expected behavior**
Name property should have an appropriate value

* **Angular version:** 6.1.9

* **PrimeNG version:** 6.1.7

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
