### ISSUE TITLE
Multiselect table's select all checkbox taking two key strokes to select all rows

### ISSUE THREAD

**Issue by manidevzen3** [primefaces/primeng#7862]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

to select all rows in multiselect table, we need to press space key two times when the focus is on select all checkbox

**Expected behavior**

when the focus is on select all checkbox and on pressing space key, for the first time itself rows selection event should happen

**Minimal reproduction of the problem with instructions**
navigate to https://www.primefaces.org/primeng-6.1.6/#/table/selection
reach the Check box selection table by pressing tab
when the focus is at select all checkbox, press the space key and observe
first time it will not select the rows, but second time it is able to select

* **Angular version:** 6.1.9

* **PrimeNG version:** 6.1.7

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
