### ISSUE TITLE
removeAllEvents is not a function primeng fullcalendar

### ISSUE THREAD

**Issue by burptheissue** [primefaces/primeng#7865]
I am working p-fullcalendar and i am not able to access any function from the calendar object.
When accessing any function in the calendar object i get "is not a function" error.

**Component file**
import { Calendar } from '@fullcalendar/core';

  @ViewChild('calendar')
    calendar: Calendar;

this.calendar.removeAllEvents()   ==> error says removeAllEvents is not a function

I am using   "@fullcalendar/core": "4.0.2" and "primeng": "7.1.2"

I am breaking my head over this for the past 2 days. please help.

**Comment by yigitfindikli** [comment]
I assume your html like this;

`
<p-fullCalendar #calendar [events]="events" [options]="options"></p-fullCalendar>
`

ViewChild returning FullCalendar component from PrimeNG. You need to use calendar inside in the FullCalendar, like this;
```
import {FullCalendar} from '../../../components/fullcalendar/fullcalendar';


@ViewChild('calendar') calendar: FullCalendar;
this.calendar.calendar.removeAllEvents();
```

And please use forum for questions and help requests.
Best Regards.
