### ISSUE TITLE
Error in tree.css file

### ISSUE THREAD

**Issue by faisalbd21** [primefaces/primeng#7866]
I am working with PrimeNG tree and got this build error.
![image](https://user-images.githubusercontent.com/14268328/60392709-855e6b00-9b2a-11e9-9d74-e3405191c469.png)

it's from css file of tree component which have two css class with incorrect image path. 
Current path is  _'./images/line.gif'_ and it should be _'../../images/line.gif'_.
I already fixed it on my code and its working... :) 

I am using "primeng": "8.0.0".

**Comment by mertsincan** [comment]
Fixed for 8.1.0.
