### ISSUE TITLE
Galleria not updating as expected

### ISSUE THREAD

**Issue by feardarkness** [primefaces/primeng#7868]
**I'm submitting a bug report**

Stackblitz:  https://stackblitz.com/edit/angular-cqgi9z

**Current behavior**
Galleria controls aren't updated correctly after images array is modified.

**Expected behavior**
Galleria UI should update when images array are changed.

**Minimal reproduction of the problem with instructions (https://stackblitz.com/edit/angular-cqgi9z)**
1. Navigate through the galleria with three images (works nice)
2. Press the button (will update the images array to one image only)
3. Navigate through the galleria images again (the image is updated, but the controls aren't updated, the arrow thinks that we have four items, one for the new array and three of the older array)

**Angular version:** 7.X
**PrimeNG version:** 7.X
**Browser:** Chrome, Chromium and Firefox Developer Edition (not tested in others)
**Language:** Typescript
**Node Version:** 10

The not so good solution:), setting timeout on ngAfterViewChanged (galleria.js) (probably there is a better solution and that's why I'm opening this issue):
```
Galleria.prototype.ngAfterViewChecked = function () {
        if (this.imagesChanged) {
            this.stopSlideshow();
           // added setTimeout
            setTimeout(() => {
                this.render();
                this.imagesChanged = false;
            }, 0);
            // this.render();
            // this.imagesChanged = false;
        }
    };
```

**Comment by JacobSiegle** [comment]
Another way to fix it is to safe check a valid index is passed in and if not valid reset to 0.
```
    select(index, reposition) {
        if (index >= this.images.length) {
            index = 0;
        }
```

Another bug exists where if you scroll past the limit (to like element 15) and then reset the images the bottom bar vanishes until you scroll back around.

**Comment by feardarkness** [comment]
Hi, maybe I should create a PR for this issue?

**Comment by JacobSiegle** [comment]
You can if you would like. I'm not sure what the best solution is, it's a bit tricky to figure out with the way this component is working without making larger changes.

**Comment by feardarkness** [comment]
I've fixed the issue and added an small feature to the component :)

**Comment by wranchundia** [comment]
HTML
 <p-galleria #galeri [images]="images"  [showCaption]="true" ></p-galleria>



TS
 @ViewChild("galleri")
  galleria: Galleria;

  this.galeria.stopSlideshow();
  this.galeria.autoPlay = false;
  setTimeout(() => {
     this.galeria.render();
     this.galeria.autoPlay = true;
     this.galeria.startSlideshow();
  }, 10);
