### ISSUE TITLE
FilterMatchMode for Dropdown

### ISSUE THREAD

**Issue by billdwhite** [primefaces/primeng#787]
Currently, a filter field in a drop down only matches based on the startsWith result:

Line 382 of dropdown.ts

``` javascript
option.label.toLowerCase().startsWith(val)
```

It would be great if this component could use the same 'FilterMatchMode' setting similar to the Column component so varying types of filter matching could be applied.

**Comment by yigitfindikli** [comment]
fixed in https://github.com/primefaces/primeng/issues/953
