### ISSUE TITLE
source-map-loader warnings 

### ISSUE THREAD

**Issue by william-lohan** [primefaces/primeng#7872]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
In angular cli with browser builder option `sourceMap.vendor` set to true source-map-loader warnings are produced like: 

>WARNING in path/to/my/project/node_modules/primeng/components/growl/growl.js
Module Warning (frompath/to/my/project/node_modules/source-map-loader/index.js):                                                                                                                                        meng\components\growl'
(Emitted value instead of an instance of Error) Cannot find source file '../../src/app/components/growl/growl.ts': Error: Can't resolve '../../src/app/components/growl/growl.ts' in 'path\to\my\project\node_modules\primeng\components\growl'

Looks like `path\to\my\project\node_modules\primeng\components\growl\growl.js.map` lists `"sources":["../../src/app/components/growl/growl.ts"]` when `../../src/app/components/growl/growl.ts` doesn't exist there/isn't published.

**Expected behavior**
no warnings

**Minimal reproduction of the problem with instructions**
In angular cli project follow https://www.primefaces.org/primeng/#/setup > Angular CLI Integration, then in `angular.json` add:

```json
"sourceMap": {
  "scripts": true,
  "styles": true,
  "hidden": true,
  "vendor": true
},
```

to `projects.my-app.architect.build.options` _vendor is the important one_

**What is the motivation / use case for changing the behavior?**
To have correct source maps for debugging and error reporting.

**Please tell us about your environment:**
win10, vscode, npm

* **Angular version:** 8.X
<pre><code>
Angular CLI: 8.0.3
Node: 10.16.0
OS: win32 x64
Angular: 8.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.800.3
@angular-devkit/build-angular      0.800.3
@angular-devkit/build-ng-packagr   0.800.3
@angular-devkit/build-optimizer    0.800.3
@angular-devkit/build-webpack      0.800.3
@angular-devkit/core               8.0.3
@angular-devkit/schematics         8.0.3
@angular/cdk                       8.0.1
@angular/cli                       8.0.3
@angular/flex-layout               8.0.0-beta.26
@angular/http                      7.2.12
@angular/material                  8.0.1
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.0.3
@schematics/angular                8.0.3
@schematics/update                 0.800.3
ng-packagr                         5.3.0
rxjs                               6.4.0
typescript                         3.4.5
webpack                            4.30.0
</code></pre>

* **PrimeNG version:** 8.X & 7.X

* **Browser:** [ all ]

 
* **Language:** [ TypeScript 3.4.5 ]

* **Node (for AoT issues):** `node --version` = v10.16.0

**Comment by beleta** [comment]
Same problem here. Very annoying!

**Comment by rafa-as** [comment]
@cagataycivici please can you check this issue?

**Comment by andgest** [comment]
Same problem here also

**Comment by pburgmer** [comment]
I also have this problem

**Comment by rafa-as** [comment]
@yigitfindikli can you check this issue?

**Comment by lTyl** [comment]
Same problem here. This appears to be a problem with _source-map-loader_. Might find some more information on the AngularCLI issue for this: https://github.com/angular/angular-cli/issues/7115

**Comment by andgest** [comment]
No news about this issue ?

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
