### ISSUE TITLE
Not centered circle in Selected state Radiobutton

### ISSUE THREAD

**Issue by maeserje** [primefaces/primeng#7873]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://www.primefaces.org/primeng/#/radiobutton

**Current behavior**
The circle icon inside a selected radio button is not centered.
![image](https://user-images.githubusercontent.com/18160206/60508867-df4a6680-9ccb-11e9-89b0-5c2e231298f2.png)

**Expected behavior**
The circle icon inside a selected radio button is  centered.

**Minimal reproduction of the problem with instructions**
On Chrome or IE11 even on the official primeng demo page the selected circel inside of a radio button is not centered.

**What is the motivation / use case for changing the behavior?**
If I use the radio button as is without any custom styles it should look proper.

**Please tell us about your environment:**
windows 10

* **PrimeNG version:** 5.X
as seem on the official primeng demo page https://www.primefaces.org/primeng/#/radiobutton

* **Browser:** 
chrome 75.0.3770.100 
IE 11

**Comment by JacobSiegle** [comment]
It looks fine to me at 100% zoom but is off center at other zoom levels. Can you confirm that's the issue you're seeing?

**Comment by maeserje** [comment]
At 100% zoom on a resultion of 2736 x 1824 it is off center as well at lower resolution it is centered.

**Comment by JonahNye** [comment]
I'm also running into this problem

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
