### ISSUE TITLE
Icons do not render, despite the usage of various import possibilities

### ISSUE THREAD

**Issue by Django987** [primefaces/primeng#7882]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://rlmiyral.github.stackblitz.io

**Current behavior**
Icons do not get rendered

**Expected behavior**
The icons e.g. `<i class="pi pi-check"></i>` get rendered as check-icon.

**Minimal reproduction of the problem with instructions**
I used 
```
npm install primeng --save
npm install primeicons --save
```
which threw no npm-errors or sth. similar, and included the styles in the angular.json as:

```
"styles": [
 "node_modules/primeicons/primeicons.css",
 "node_modules/primeng/resources/themes/nova-light/theme.css",
 "node_modules/primeng/resources/primeng.min.css",
 "src/styles.scss"
],
```

**Please tell us about your environment:**

* **Angular version:** 8.0.3

* **PrimeNG version:** ^8.0.0
* **PrimeNGIcons version:** ^1.0.0

* **Browser:** [Chrome 75]

 
* **Language:** [TypeScript ~3.4.4]

* **Node (for AoT issues):** `node --version` =   10.15.3

**Comment by JacobSiegle** [comment]
The stackblitz never loads it must be broken. Are you having trouble getting the icons to show up in stackblitz, your project, or both?

**Comment by Django987** [comment]
the failure is reproducable / solvable by changing a CSS-selector for the font-family-definition in the styles.scss on root-level

with the selector `body` the Icons **render** (and it would not even be necessary to add the @import-statement here)
```
@import '~primeicons/primeicons.css';

body {
  font-family: sans-serif !important;
}
```
whilst the following option somehow overrides the Icons provided by primengicons-library and makes them **not render**; I did not put much research in it, but it seems that it is not a bug by the framework resp. the library but by the way I wanted to combine different font-familys resp. Icons from different sources; a feedback would still be nice
```
@import '~primeicons/primeicons.css';

* {
  font-family: sans-serif !important;
}
```
