### ISSUE TITLE
Dropdown does not hide upon scrolling outside its boundaries.

### ISSUE THREAD

**Issue by Yoranium238** [primefaces/primeng#7883]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
The requested functionality can be seen using PrimeNG's documentation of the dropdown component.  https://www.primefaces.org/primeng/#/dropdown

**Current behavior**
When scrolling outside of an open dropdown's list boundary, the list remains visible.

**Expected behavior**
When you CLICK outside of the dropdown's boundaries, the list is hidden.  In a manner similar to this, it is requested that SCROLLING outside the dropdown's boundaries also hides the list.  If scrolling within the boundaries of the dropdown, the list should remain open and the contents scrolled accordingly.

**Minimal reproduction of the problem with instructions**
Open a dropown from one of the examples.  While the dropdown is open, position the cursor outside of the dropown's boundaries.  Begin scrolling.  Notice the dropdown remains open.

**What is the motivation / use case for changing the behavior?**
Current application exhibits the requested behavior

**Please tell us about your environment:**

* **Angular version:** 7.2

* **PrimeNG version:** 7.05

* **Browser:** [all]

 
* **Language:** [TypeScript 3.2]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Works as expected, it will be a terrible UX to hide the overlay when boundaries are extended.
