### ISSUE TITLE
Is chart.js and quill mandatory?

### ISSUE THREAD

**Issue by TheParad0X** [primefaces/primeng#7887]
I just installed primeNg 8.0.0 and I only need one component: triStateCheckbox.

I am getting the following error:

ERROR in ./node_modules/primeng/components/chart/chart.js
Module not found: Error: Can't resolve 'chart.js' in 'C:\dev\[...]\node_modules\primeng\components\chart'
ERROR in ./node_modules/primeng/components/editor/editor.js
Module not found: Error: Can't resolve 'quill' in 'C:\dev\[...]\node_modules\primeng\components\editor'

Why do I need chart.js and quill for the checkbox to work? Is it mandatory?

Cheers,
Para

**Comment by cagataycivici** [comment]
Please use forum for questions and help requests.

Also do not import anything from primeng/primeng.

**Comment by ekulabuhov** [comment]
Apart from fixing primeng/primeng imports check that you're not importing primeng/chart as that will pull in chart.js. 

This is the error for future searches: 
`ERROR in ./node_modules/primeng/fesm5/primeng-chart.js`
`Module not found: Error: Can't resolve 'chart.js' in '<path>\node_modules\primeng\fesm5'`
