### ISSUE TITLE
BUG - Dropdown with virtual scroll enabled not keeping selection in view

### ISSUE THREAD

**Issue by parky128** [primefaces/primeng#7892]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Stackblitz Case (Bug Reports)**

https://stackblitz.com/edit/angular-playground-s5zlt3

**Current behavior**
After scrolling to an item in the drop down list thats not already visible and selecting it, upon re-opening the drop down list, the selected item is not scrolled to automatically in the list.

**Expected behavior**
The last selected item should be automatically visible when re-opening the drop down list of items

**Minimal reproduction of the problem with instructions**

- Go to https://stackblitz.com/edit/angular-playground-s5zlt3
- Open the drop down
- Scroll down the list to bring new items into view
- Select an item
- Re-open the drop down
- Note that the selected item is no longer in view, list scrolls back to the top by default

**What is the motivation / use case for changing the behavior?**

To improve the user experience for this component

**Please tell us about your environment:**

* **Angular version:** 7.X

* **PrimeNG version:** 7.X

* **Browser:** Chrome

**Comment by JacobSiegle** [comment]
https://github.com/primefaces/primeng/issues/7712 is the same issue?

**Comment by parky128** [comment]
Yes I have just closed it off, I wanted to make a more detailed case

**Comment by yigitfindikli** [comment]
duplicate https://github.com/primefaces/primeng/issues/7718

**Comment by senp0105** [comment]
I am still facing this problem with "primeng": "9.1.0" and angular 9. Is this issue resolved?

**Comment by senp0105** [comment]
I have opened issue : https://github.com/primefaces/primeng/issues/9026
