### ISSUE TITLE
[BUG] p-table on state restore doesn't apply width of table footer.

### ISSUE THREAD

**Issue by KonstantinsS** [primefaces/primeng#7894]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/angular-vkijjf

**Current behavior**
When you resize columns and refresh the page columns width stays the same as it was after resize but footer columns width doesn't stay as it was after resize (default width is applied)

**Expected behavior**
Footer column width should be the same as column width after resize.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/angular-vkijjf
Go to stackblitz.
Make Brand and Color column smaller (resize).
Verify footer columns width (with label 'total brands 100,000' and 'total colors 100,000')
Refresh the page.
Verify footer columns width. It should be the same as before refresh.

**Please tell us about your environment:**

* **Angular version:** 8.X

* **PrimeNG version:** 8.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
