### ISSUE TITLE
Use css files in lazy loaded routes

### ISSUE THREAD

**Issue by vahidvdn** [primefaces/primeng#7899]
I use **lazy loaded routes and modules** in my project. I created a shared module to use primeNG modules when I need. But about css files, I should load them in once in `angular.json` file. Is it a good idea? Any alternative?

**Comment by cagataycivici** [comment]
Please use forum for support requests and questions.

**Comment by vahidvdn** [comment]
@cagataycivici Hi. Is it a support request or feature request?
