### ISSUE TITLE
MegaMenu - MenuModel API

### ISSUE THREAD

**Issue by pieterlouw1974** [primefaces/primeng#790]
Hi New to github.

This could be the wrong place to add this.

can a event be added to top level on the menu?

 this.items = [{
            label: 'File', ***\*  command: (event) => {   //process event }  ****
            items: [
                {label: 'New', icon: 'fa-plus': command: (event) => {
                    //process event

```
        ]
    }
```

**Comment by cagataycivici** [comment]
If the item has no children, yes. otherwise it is not possible right now. If more users demand it, we'll reopen for sure.
