### ISSUE TITLE
FileUpload inital files preview is not working

### ISSUE THREAD

**Issue by yelhouti** [primefaces/primeng#7901]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/github-cozx3n

**Current behavior**

When files are initialized in the fileUpload component the preview doesn't work for image
**Expected behavior**

Preview should work for images on init
**Minimal reproduction of the problem with instructions**
Check stackblitz, the image is broken

**What is the motivation / use case for changing the behavior?**

Preview already saved image using the same form
**Please tell us about your environment:**

* **Angular version:** 8.0.0

* **PrimeNG version:** 8.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   

The problem happens since `file.createObjectURL` is not called in the files setter.

**Comment by cagataycivici** [comment]
Fixed via https://github.com/primefaces/primeng/pull/7914
