### ISSUE TITLE
Multi line chart tooltip does not display all the dataset info

### ISSUE THREAD

**Issue by sadikshae** [primefaces/primeng#7903]
The prime ng line chart with multiple datasets shows only on data information when hovering over the datapoint https://www.primefaces.org/primeng/#/chart/line. For instance, in the link provided if i hover over the green line chart it shows only "January/ First Dataset: 65". However when I hover over the datapoint, no matter on green or black, I want to see the tooltip as: "January/ First Dataset: 65/ Second Dataset:25". How can I achieve this?

**Comment by JacobSiegle** [comment]
You need a customize your chart JS config or add in plugins to get this functionality. This is a question and not an issue with PrimeNG. You should post this to the primeng forum instead.
