### ISSUE TITLE
FileLimit on FileUpload

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#7906]
Add a new fileLimit prop to restrict the number of files that can be uploaded. Disable the upload button to prevent selecting new files and display a message if multiple files selected and it exceeds the overall limit.

**Comment by JO3-W3B-D3V** [comment]
Hey @cagataycivici, with regards to the message, do you plan to utilise a growl/toast/etc component? Or do you plan to include a prop so that the developer can specify? 

I'm simply asking out of curiosity, I love the work you guys are doing & thank you for doing such an awesome job!

**Comment by codenode22** [comment]
you choose

**Comment by codenode22** [comment]
if you choose files more than fileLimit you see an alert message, but when you remove a file and the fileLimit is correct now, the alert message stays.It should go but it is not.
