### ISSUE TITLE
DataTable: event.sortOrder returns a string instead of a number on lazyload-event

### ISSUE THREAD

**Issue by riscie** [primefaces/primeng#791]
Hi there

First of all, great work with your library! Many really really good components in here!

I have found a small issue which I wanted to let you know. As the title says, event.sortOrder returns a string instead of a number when the lazyLoad-Method is getting trigered. This is no big issue, as a simple parseInt can fix it, just wanted to let you know.

I have shortly looked into the code, but could not figure out why this happens.

Regards

**Comment by cagataycivici** [comment]
Unable to replicate with 4.0.1, please drop a comment if issue still persists and we may reopen.
