### ISSUE TITLE
Frozen Columns and Rows should be exportable to CSV as well

### ISSUE THREAD

**Issue by gcioran** [primefaces/primeng#7916]
I'm submitting a ... (check one with "x")

[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

Current behavior
Export CSV is not exporting frozen columns and frozen rows

Expected behavior
Export CSV should exporting frozen columns and frozen rows

Minimal reproduction of the problem with instructions
Try to export to csv a table with frozen rows or frozen columns. the frozen part of the table is not exported in csv file

What is the motivation / use case for changing the behavior?
Export the entire table. frozen rows/columns usually are very important in tables

Please tell us about your environment:

    Angular version: 7.2.3

    PrimeNG version: 8.0.1

    Browser: [all]

    Language: [TypeScript 3.2.4 ]

    Node (for AoT issues): node --version =8.12

**Comment by gcioran** [comment]
code reproducing the bug
https://stackblitz.com/edit/github-b4aknz

**Comment by iftekharkhan09** [comment]
Is this issue fixed now and if yes then which version of Angular has the fix?

**Comment by angelina220** [comment]
Is this fix available in latest version ?
