### ISSUE TITLE
png and gif files are added to published folder even when their components are not used

### ISSUE THREAD

**Issue by davisb10** [primefaces/primeng#7918]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

The following files are added to the published folder, even when their calling component are not in the project:
- color.png
- hue.png
- line.gif
- loading.gif
- password-meter.png

**Expected behavior**

These files should only be added to the output when they are actually needed.

**Minimal reproduction of the problem with instructions**

run ng build --prod and look in the output directory

**What is the motivation / use case for changing the behavior?**

Not to add unnecessary files to the output folder

**Comment by rafa-as** [comment]
@cagataycivici some news?

**Comment by cagataycivici** [comment]
See;

https://github.com/primefaces/primeng/issues/8651
