### ISSUE TITLE
FocusTrap for DynamicDialog

### ISSUE THREAD

**Issue by eric-kearney** [primefaces/primeng#7921]
I'm submitting a ...
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already 

**Plunkr Case (Bug Reports)**
Here is a basic demonstration of the issue:
https://github-rifn3w.stackblitz.io/

Or see the Dynamic Dialog demo on the PrimeNG site:
https://www.primefaces.org/primeng/#/dynamicdialog

**Current behavior**
The Dynamic Dialog but does not prevent keyboard interaction on the background/calling page.  Once you click a button to open the dialog, if you press the Enter key (before selecting anything in the dialog) the same dialog will be opened again , and again, (from the calling page) each time making the background darker as the opaque overlay is re-applied over again.  Even if you manually or programmatically move the focus into the dialog, the tab key allows the focus to move in and out of the dialog, allowing the user to access any functionality in the calling page while the dialog is open (in the demo provided, you can trigger the Add and Delete buttons even when the dialog is open).

**Expected behavior**
The Dynamic Dialog should be opened in a "modal" state or at least have the option to specify modal or not, similar to how the regular Dialog control works.  Also the focus should be automatically moved into the Dialog and should stay within the dialog until it is closed (similar to how the regular Dialog control works (i.e. focusOnShow and focusTrap properties).

**Minimal reproduction of the problem with instructions**
Here is a basic demonstration of the issue:
https://github-rifn3w.stackblitz.io/

Or see the Dynamic Dialog demo on the PrimeNG site:
https://www.primefaces.org/primeng/#/dynamicdialog

Click on the Show (or Show Dialog) button.
Once the dialog is displayed, without clicking anywhere, press the Enter key.
The same dialog will be displayed a second time (and a third if you press it again).

In the stackblitz demo above, if you move the focus into the dialog you can shift-tab your way back to the other buttons on the screen (Add or Delete) and press Enter to activate them.  This should not be allowed.

**What is the motivation / use case for changing the behavior?**
A dialog box should be able to be opened in modal mode with the tabbing contained within the dialog box.  This is not usable the way it is because it allows the user to navigate out of the dialog and access functionality that should be blocked until the user closes the dialog box.  The regular dialog box already behaves this way, but we need to use the Dynamic Dialog since we are creating dynamic content at run time.

**Please tell us about your environment:**
Windows 7 and Windows 10, Microsoft Visual Studio 2017, .NET 4.7, asp.net core 2.2

* **Angular version:** 7.2

* **PrimeNG version:** 7.1.3

* **Browser:** Chrome 75 and IE 11  (only browsers this attempted on)
 
* **Language:** TypeScript 3.2

**Comment by twopelu** [comment]
Same problem here, the dialog is open but you can click in any part of the screen, this is not working as a modal dialog as it should.

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9 with has a new Dialog impl, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

Also please see;

https://forum.primefaces.org/viewtopic.php?f=35&t=61349&p=180984#p180984

**Comment by ChengzhiXue** [comment]
the fixing not solve the problem, if you press 'enter' key, the dialog still will be opened again and again

**Comment by ChengzhiXue** [comment]
maybe added  "event.which === 13" check also to on onKeydown

**Comment by TomMettam** [comment]
It would be really nice if this was fixed upstream, but here's how you do it:

```
@HostBinding('tabindex') public tabindex = 0;

public constructor(public element: ElementRef)
{

}

public ngAfterViewInit(): void
{
    this.element.nativeElement.focus();
}
```

**Comment by Oznaprazzi** [comment]
I'm having the issue as well with pressing the enter key or space
