### ISSUE TITLE
Accordion ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by fabioscala** [primefaces/primeng#7923]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-9wu8er
You might need to reload the side-browser a few times as it's likely a race-condition and doesn't always manifest.

**Current behavior**

Setting the accordion tab using `[activeIndex]` contains race conditions that can lead to `ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ui-accordion-content-wrapper-overflown: true'. Current value: 'ui-accordion-content-wrapper-overflown: false'.`

**Expected behavior**
No error to occur

**Minimal reproduction of the problem with instructions**

1. `activeIndex` is undefined
2. An HTTP callback (or any callback..) after a few ms within page load is triggered
3. This sets `activeIndex` to 0
4. The error will occur

**Please tell us about your environment:**
Issue was not present in PrimeNG 8.0.0

* **Angular version:** 8.1.0

* **PrimeNG version:** 8.0.1

**Comment by JacobSiegle** [comment]
Seems like it can be avoided by doing the following but should be patched - 
```
    someHttpCallBack$.subscribe(() => {
      this.expanded = true;
      this.cd.detectChanges();
    });
```

**Comment by fabioscala** [comment]
For the time being, workaround works, thanks!

**Comment by cagataycivici** [comment]
Merged PR
