### ISSUE TITLE
how i can remove all value in list row edit?

### ISSUE THREAD

**Issue by nguyenhathu2594** [primefaces/primeng#7926]
Hi,

I use the row editing method in the table. In the example there is a method to delete 1 record that I do not want to edit as shown below:

![image](https://user-images.githubusercontent.com/17545684/60963962-591dc800-a33c-11e9-8625-42ea55219a6a.png)

So, how can I delete all the records that I don't want to fix in just one command?

Thanks

**Comment by JacobSiegle** [comment]
You should be able to accomplish this with the editingRowKeys setting. Try reading the doc at https://www.primefaces.org/primeng/#/table searching for editingRowKeys. This is a question not an issue, it should not be opened here.

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.
