### ISSUE TITLE
p-dropdown with filter true tab does not focus next element

### ISSUE THREAD

**Issue by chravikishore** [primefaces/primeng#7928]
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
Dropdown with filter enabled, after selecting item, and then hitting tab does not focus to next element in the region

**Expected behavior**
After hitting tab, focus should be moved to next element in the region.

**Minimal reproduction of the problem with instructions**
1. Place a text box, then p-dropdown with filter=true, then again a text box.
2. move cursor to first text box. then hit tab.
3. Focus moved to p-dropdown. Now select one item using keyboard and hit tab.
4. Now observe focus did not moved to second textbox.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:7.3.3

* **PrimeNG version:7.1.3

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
