### ISSUE TITLE
Keyboard support to close icon of Tabs

### ISSUE THREAD

**Issue by Da13Harris** [primefaces/primeng#7933]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**StackBlitz Case (Bug Reports)**
https://stackblitz.com/edit/github-uzvc4p

**Current behavior**

Pressing the tab key with the keyboard cycles through the tab links, but doesn't cycle through the close icons. This means a keyboard only user can't close the tabs.

**Expected behavior**

Pressing the tab key should also focus on the close icons, not just the tab links.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/github-uzvc4p

**What is the motivation / use case for changing the behavior?**

Accessibility is a critical (and often government mandated) requirement.

**Please tell us about your environment:**

Windows 10, VS Code, NPM, .NET Web API back-end

* **Angular version:** 7.2.0  (still an issue in Angular 8)

* **PrimeNG version:** 7.0.4 (still an issue in PrimeNG 8)

* **Browser:** all

 
* **Language:** all

**Comment by Chazing** [comment]
Not yet fixed in the current version either, is it in the planning?
Thanks

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
