### ISSUE TITLE
Auto close on date time picker

### ISSUE THREAD

**Issue by jorgekg** [primefaces/primeng#7937]
When you use Prime's date and time components, they simply close on a tablet. We can see in the video below.
https://www.youtube.com/watch?v=YGmUm-mwiAM&feature=youtu.be

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When using an input date or time on a tablet, it simply closes when focused.

**Expected behavior**
Do not close information when using on a tablet

**Minimal reproduction of the problem with instructions**
The problem occurs in Prime examples on the official website

* **Angular version:** 7.X

* **PrimeNG version:** 7.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =  v8.9.4

**Comment by JacobSiegle** [comment]
Can you provide the tablet specs? What browser is being used, what android version, etc?

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
