### ISSUE TITLE
Handle ctrl/meta keys for datatable multiple selection

### ISSUE THREAD

**Issue by jayeffaar** [primefaces/primeng#794]
Right now, when using the multiple selection mode of the datatable, groups of rows can only be selected/unselected by left clicking on them, instead of using the more standard methods of selecting a range of rows with the shift key, and selecting/unselecting single rows with the control key. The current system is very confusing for anyone used to multi-selection in just about any other UI widget.

I see that as of fix #109, the datatable code was still handling the ctrl/meta key (but not the shift key), but strangely, that was dropped since then in favor of simply toggling the selection on single rows on and off on a click. 

It would be useful to have that back, as well as adding handling for a range of rows with shift-clicking. Along with those changes, clicking on an already selected row should never deselect it, but should deselect any other selected rows.

**Comment by JakeSummers** [comment]
This is the commit that the functionality was dropped:

43581862c023ce7ebfedb7a4d2421349bd6da6e3

**Comment by jayeffaar** [comment]
I see now that it was dropped at the request of a user (https://github.com/primefaces/primeng/issues/284), but that seems like a strange move to not have made that behaviour optional. As far as I can tell, toggling a selection in a table without the use of the ctrl key is very non-standard. Having to individually click on every selected element to turn them off is a pain, instead of being able to simply click on one to reset the multiple selection.

**Comment by cagataycivici** [comment]
PrimeFaces uses the approach you've described, at PrimeNG we've changed it to be more mobile friendly as there are no shift or metakeys, but we are open to suggestions such as customizable behavior with an attribute to choose between behaviors although it'll make it complex.

**Comment by jayeffaar** [comment]
I wasn't thinking about mobile, and I can see now why you would need a simple click-based selection mode in that case.

In our case though, we really need the selection to behave like a desktop app, and we have an outstanding story to bypass the datatable's selection logic and handle the Shift and Ctrl/Meta keys ourselves in onRowClick events. We haven't gotten to it yet, and obviously, it would be nicer if the datatable offered that functionality as an option. It already has so many (useful) options that one more wouldn't make it more confusing.

Can you see that as something that could be added soon-ish, or should we go ahead with our plans to write our own selection logic? (Something we expect to get to around mid to late September)

**Comment by cagataycivici** [comment]
I think we can introduce an attribute to configure this behavior for sure in 1.0 final due end of october.

**Comment by JakeSummers** [comment]
That would be awesome!  Thanks!

**Comment by AngularPadawan** [comment]
I am considering to switch to the primeng DataTable (because mostly it is quite awesome!), but would definitely require this feature (the desktop version). Is this still planned for 1.0 final, and what is the expected release date for this? Thanks!

**Comment by cagataycivici** [comment]
We've decided to enable key based multiple selection by default and on touch enabled devices, switch to tap based multiple selection targeting RC4.

**Comment by cagataycivici** [comment]
We left the shift for post 1.0 but the behavior is implemented now, tap for mobile and metakey-ctrlkey for others.

**Comment by ARandomDude** [comment]
@cagataycivici: Hey there, is there any update on the range selection with shift key?

**Comment by cagataycivici** [comment]
In our near future roadmap.

**Comment by middoors** [comment]
can multiple sorting work also without the metakey pressed?
