### ISSUE TITLE
Export data on Treetable component

### ISSUE THREAD

**Issue by MoxCrox** [primefaces/primeng#7942]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Hey!
I had a look at the roadmap and I saw the good news about more export options for Turbotable!

Is there any plans on adding the export feature on **Treetable** as well in the near future?
It's  a critical feature for one of our project (espacally .xls)...
That'd be great to see that coming up soon!

**Comment by JacobSiegle** [comment]
More export options has been on the roadmap for a long time so i'm not sure it's being actively being worked.

How do you expect treetable to look in the export csv? Possibly it just has spaces padded in the first col to show the offset and the table is full expanded (with no option to collapse)?

**Comment by MoxCrox** [comment]
Oh ok, that's a bummer!

Yes, the end result is pretty much as you said, just an export of my treetable's data fully expanded.
I'm gonna give it a shot and see if I can work something out for now. 
That'd be great if the feature would get released sometime in the future though!  :)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by AjCreations195** [comment]
Is it a way to exporting tree-table to excel and pdf in Angular.
