### ISSUE TITLE
pContextMenuRow does not provide styling like pSelectableRow and pSelectableRowDblClick

### ISSUE THREAD

**Issue by davisb10** [primefaces/primeng#7943]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**

When a Context Menu is attached to a table, it provides now styling to let the user know that there are possibly actions that could be performed with a given row.

**Expected behavior**

To show the same row hover styling as pSelectableRow and pSelectableRowDblClick

**Comment by cagataycivici** [comment]
See;

https://github.com/primefaces/primeng/issues/8680
