### ISSUE TITLE
'appendTo="body" will scroll the dropdown menu along with the body/container scroll. Can this be made fixed?

### ISSUE THREAD

**Issue by Jooooooooooey** [primefaces/primeng#7952]
![Screen Shot 2019-07-16 at 2 49 23 PM](https://user-images.githubusercontent.com/31805701/61332396-f6637b00-a7d8-11e9-9aeb-09a7574ac61b.png)

In the beginning, the issue was the hidden dropdown menu. I solved this by adding 'appendTo="body"' within p-dropdown. Now the dropdown options are showing up,  however, it will scroll the dropdown menu along with the body/container scroll. Can someone help me with this problem? Thanks in advance!

					<td class="ui-resizable-column" [class.lookup-column]="col.editFieldType === 'Lookup'" [pEditableColumn]="rowData" [pEditableColumnField]="col.field"
						*ngIf="isEditable(rowData, col.editable, col.field); else readOnlyCell">
						<span class="ui-column-title">{{col.label}}</span>
						<p-cellEditor [style]=" {'overflow':'visible' }">
							<ng-template pTemplate="input">
								<input type="text" [(ngModel)]="rowData[col.field]" *ngIf="col.editFieldType === 'String'" (change)="onEditComplete(rowData, col.field)" maxlength="{{!col.maxlength}}">
								<textarea rows="3" type="textarea" [(ngModel)]="rowData[col.field]" *ngIf="col.editFieldType === 'TextArea'" (change)="onEditComplete(rowData, col.field)" maxlength="{{col.maxlength}}"></textarea>
								<oneip-calender [(dateField)]="rowData[col.field]" (selectedDate)="rowData[col.field] = $event; onEditComplete(rowData, col.field);" *ngIf="col.editFieldType === 'Date'"></oneip-calender>
								<oneip-user-picker *ngIf="col.editFieldType === 'UserLookUp'" [placeholder]="'Enter name'" [qcguids]="rowData" (userSelection)="rowData[col.field] = $event; onEditComplete(rowData, col.field);"></oneip-user-picker>
								<p-dropdown appendTo="body" [autoWidth]="false" *ngIf="col.editFieldType === 'Lookup'" placeholder="Select" (onChange)="onSelect($event, rowData, col.field)" [options]="getLookupValues(col.field)"></p-dropdown>
							</ng-template>
							<ng-template pTemplate="output">
								<span [innerHTML]="!!rowData[col.field] ? format(col, rowData[col.field], rowData): '&nbsp;'" class="editable-icon" title="Click to Edit"></span>
							</ng-template>
						</p-cellEditor>
					</td>

**Comment by hakim-dc** [comment]
1+

**Comment by hakim-dc** [comment]
@cagataycivici any future fixes for this.

**Comment by morozp** [comment]
+ that is realy terrible. The same for Menu + popup="true"

**Comment by wiesnery** [comment]
+1 for https://www.primefaces.org/primeng/#/tieredmenu in popup mode

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Comment by nironater** [comment]
@cagataycivici, can you please reopen & fix this?
I've reproduced this on your latest PrimeNG 9.1.3 ---> [HERE ](https://stackblitz.com/edit/primefaces-dropdown-append-to-body-scroll-issue)<---

**Comment by Abhishek2kr** [comment]
@cagataycivici This issue is still there in 9.0.6. Please reopen this ticket.

**Comment by Abhishek2kr** [comment]
Or Atleast share when this fix gonna come. @cagataycivici

**Comment by Walteann** [comment]
I've some problem.

**Comment by Abhishek2kr** [comment]
@Walteann Can you share the style which you are applying?

**Comment by Abhishek2kr** [comment]
And share how your dropdown is coming

**Comment by Walteann** [comment]
@Abhishek2kr I simuled my problem in [Stackblitz](https://stackblitz.com/edit/angular-gnrwkx?file=src%2Fapp%2Fapp.component.html)

when I've appentTo=Body, 
![image](https://user-images.githubusercontent.com/24998960/90424889-3c9ea400-e095-11ea-84e0-8bfb49c0fe6a.png)

In example 1 it would solve if I remove the appendTo and the styles overflow-y and max-height, but I need that there is maximum height

**Comment by AjeetEppa** [comment]
I'm getting this issue even on "11.0.0-rc.1" release

**Comment by Abhishek2kr** [comment]
Hey I debug my codebase and I found z-index was applied from parent template after removing that it got fixed. So pls check once.

**Comment by ChellappanRajan** [comment]
I am also facing similar issue in 11.0.0. Any workaround?

**Comment by AjayPolke6817** [comment]
Same issue here.

**Comment by Fx73** [comment]
Same issue !

**Comment by Bonbons** [comment]
Hello!
Still the issue on v15.0.0 :
https://stackblitz.com/edit/primeng-dropdown-arrow-navigation

**Comment by medemi68** [comment]
I'm getting this issue in PrimeVue as well.

**Comment by saver711** [comment]
Why is this closed ? @cagataycivici 
it still exists

**Comment by nironater** [comment]
So sad it still exists 4 years after I reproduced and gave code samples here. So happy I work in a different place that doesn't depend on this library. Good luck guys...

**Comment by gamoreli** [comment]
closed without a resolution?

**Comment by jh-alamonde** [comment]
This still exists in 19, and breaks in other ways too... appendTo body is a minefield
