### ISSUE TITLE
block scrolling is not working in the ipad

### ISSUE THREAD

**Issue by khaled3wad** [primefaces/primeng#7955]
the [blockscroll] property of the sidebar is not working on IPad , when i am opening the sidebar with setting the blockscroll property to true , still scrolling in the background .
this issue only happened in the Ipad , it's working in the rest of the browers / devices .

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
