### ISSUE TITLE
"no file chosen" tooltip appears after selecting file

### ISSUE THREAD

**Issue by harry9876** [primefaces/primeng#7957]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

"no file chosen" tooltip appears although a file is selected
https://www.primefaces.org/primeng/#/fileupload
![no_file_chosen](https://user-images.githubusercontent.com/46155251/61363141-2881e500-a88c-11e9-8d0c-21a6783a95a5.png)

**Expected behavior**

The "no file chosen" tooltip will not appear because a file is selected

**Please tell us about your environment:**

* **Angular version:** 7.X

* **PrimeNG version:**8.X

* **Browser:** [all ]

**Comment by davisb10** [comment]
That tooltip is actually a browser defined tooltip for input elements with type="file".
To remove this, others suggest CSS hacks:
- [StackOverflow Post 1](https://stackoverflow.com/questions/18398135/html-how-to-remove-text-in-fileupload-field)
- [StackOverflow Post 2](https://stackoverflow.com/questions/16001586/change-the-no-file-chosen)
- ... any plenty others
