### ISSUE TITLE
Lightbox content mode doesn't close on iOS safari or chrome

### ISSUE THREAD

**Issue by paulyipkh** [primefaces/primeng#7958]
https://www.primefaces.org/primeng/#/lightbox

The demo of content mode doesn't close on iOS safari or chrome, though works on Android and PC.

Furthermore, can content mode allow addition of Title and Close icon as well ?

**Comment by JacobSiegle** [comment]
Second request overlaps with https://github.com/primefaces/primeng/issues/4789

**Comment by cagataycivici** [comment]
Lightbox will be deprecated in favor of the upcoming modern Galleria so closing.
