### ISSUE TITLE
Aria label properties removed from p-sortIcon?

### ISSUE THREAD

**Issue by botondus** [primefaces/primeng#7959]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
I've upgraded my project to Angular 8 and PrimeNG 8.0.1. And I'm getting a compile error about the `ariaLabel` attribute of p-sortIcon component. If I remove all the ariaLabel properties then it compiles fine.

Error on compile
```
ERROR in : Can't bind to 'ariaLabel' since it isn't a known property of 'p-sortIcon'.
1. If 'p-sortIcon' is an Angular component and it has 'ariaLabel' input, then verify that it is part of this module.
2. If 'p-sortIcon' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("s.Sorting"
                                [field]="column.field"
                                [ERROR ->]ariaLabel="{{ l('Grid.SortActivate') }}"
                                ariaLabelDesc="{{ l('Grid.S")

```
**Expected behavior**
No errors on compile.

**Minimal reproduction of the problem with instructions**
Simply having `p-sortIcon` in a template with the ariaLabel properties. If I removed the ariaLabel properties then it compiles fine? But I don't see any mention in the changelog about this.

```
<p-sortIcon
          *ngIf="settings.features.Sorting"
           [field]="column.field"
           ariaLabel="{{ l('Grid.SortActivate') }}"
           ariaLabelDesc="{{ l('Grid.SortActivateDesc') }}"
           ariaLabelAsc="{{ l('Grid.SortActivateAsc') }}"
></p-sortIcon>
```

**What is the motivation / use case for changing the behavior?**
Upgrading project to latest version.

**Please tell us about your environment:**
Windows 10, Visual Studio Code

* **Angular version:** 8.0
* **PrimeNG version:** 8.0.1

* **Browser:** [all |

 
* **Language:** [| TypeScript 3.4.5 ]

* **Node (for AoT issues):** `node --version` =   10.16.0

**Comment by tytusplanck** [comment]
I'm having the exact same issue when upgrading PrimeNG to 8.0.2.

**Comment by cagataycivici** [comment]
They are moved to th element since it is the one that receives focus.
