### ISSUE TITLE
Graph with buttons

### ISSUE THREAD

**Issue by candorthor** [primefaces/primeng#7962]
I need the line graph as below, where it contains buttons "Hourly", "Day" etc. And when clicked on it,  the graph should show the corresponding requirement. When clicked on "Day", graph  should display based on Day, when clicked on "Hourly", graph should display Hourly basis etc.

How can I do that? Could you please help me in this.

Screenshot attached.
![graph](https://user-images.githubusercontent.com/49184671/61394451-c1dae680-a8e0-11e9-9444-35dadd858a1f.png)

**Comment by JacobSiegle** [comment]
This is a question about using chartjs and primeng. Only issues should be posted here. You can look for chartjs support online or try the primeng forums.

https://www.chartjs.org/docs/latest/axes/cartesian/time.html

**Comment by candorthor** [comment]
@JacobSiegle 

I have posted it in forums. But I have not received any update.
https://forum.primefaces.org/viewtopic.php?f=35&t=59431

**Comment by cagataycivici** [comment]
Please use forum for support requests and questions.
