### ISSUE TITLE
BlockUI failed if nested in *ngIf/*ngFor

### ISSUE THREAD

**Issue by passerbyid** [primefaces/primeng#7965]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-kegvvs?embed=1&file=src/app/app.component.html

**Current behavior**
If `<p-blockUI>` is nested in `*ngIf` or `*ngFor`, it won't be appended to the `target` or `body`(default) and set auto-Zindex. It because of the `ViewChild` static is false, the `#mask` query will be resolved after change-detection runs and couldn't be queried in `blocked` setter in the first time.

**Expected behavior**
It should be appended to the `target` and set auto-Zindex if needs.

**Minimal reproduction of the problem with instructions**
As the stackblitz case.

* **Angular version:** 5.X
8.0.0~8.1.2

* **PrimeNG version:** 5.X
8.0.1

**Comment by flobiber** [comment]
Having the same problem! 
It looks like that is fixing the problem:
https://github.com/primefaces/primeng/issues/8247

**Comment by passerbyid** [comment]
I have sent a PR in #7966 to fix it.

**Comment by yigitfindikli** [comment]
Seems to be fixed https://github.com/primefaces/primeng/blob/master/src/app/components/blockui/blockui.ts .

**Comment by milad-navabi** [comment]
I have the same problem!!!
I have used -----ngif------ in the box that I want to lock and this has made it not work.
Unfortunately it does not work. Darkens the entire screen!
Thank you for explaining step by step.

Sample My Code:

<p-blockUI [target]="pnl" [blocked]="blockedPanel">
    <i class="fa fa-lock fa-5x" style="position:absolute;top:25%;left:50%"></i>
</p-blockUI>

<p-panel #pnl   *ngif="infoPanel"   header="Panel Header">
    Content of Panel
</p-panel>
