### ISSUE TITLE
Appears empty space between frozen part and scrollable part after resizing column of primeng table

### ISSUE THREAD

**Issue by JobayerAhmmed** [primefaces/primeng#7968]
**Demo**
https://stackblitz.com/edit/primeng-table-empty-space-2ns5cy

**Current behavior**

Above is a p-table which has frozen columns and scrollable columns. All the columns are also resizable and table is in expand mode. When one of the frozen columns is resized left, there appears empty space between frozen columns and scrollable columns.

Table before column width is resized:
![1](https://user-images.githubusercontent.com/12273111/61428422-dc927700-a943-11e9-8f37-d89d5cffc083.png)

Table after Year column is resized by dragging left border of Year: 
![2](https://user-images.githubusercontent.com/12273111/61428480-0fd50600-a944-11e9-82e4-b9d27ca0e1f9.png)

**Expected behavior**
- No empty space between frozen part and scrollable part should be appeared when the column is resized.
- 'Brand' column should also move left while dragging 'Year' column left.

**Minimal reproduction of the problem with instructions**
- Drag 'Year' column by left border.
- Empty space will appear between 'Year' column and 'Brand' column.

**What is the motivation / use case for changing the behavior?**
- It is normal expectation that the table will not split in two in any case. User should not know whether we use multiple tables or single table for displaying data in our implementation.

**Environment:**
* **OS:** Linux
* **IDE:** Visual Studio Code

* **Angular version:** 8.1.1

* **PrimeNG version:** 8.0.1

* **Browser:**  Chrome 75, Firefox 68 
* **Language:** TypeScript 3.2.4 | ES7

* **Node (for AoT issues):** `node --version` =   v10.16.0

**Comment by cagataycivici** [comment]
Please use forum for support requests and questions.
