### ISSUE TITLE
Unable to turn on Edit Mode in Row or Cell Editing 

### ISSUE THREAD

**Issue by mshemadarshini** [primefaces/primeng#7973]
- [ ] **I'm submitting a ...**  (check one with "x")

[x ] bug report => Search github for a similar issue or PR before submitting

**Current behavior**

It is not enabling the edit option in the pInputText. 
- already include {dataKey="id" editMode="row"} in the p-table. 
 

**Expected behavior**

Allow Edit option to enable the user to edit into the existing data

**Minimal reproduction of the problem with instructions**
 ```
<p-table  [columns]="maintanenceDaysColumn" [value]="maintanenceDayModel"  [responsive]="true"  dataKey="id" editMode="row"
          scrollHeight="200px" [rows]="5" [paginator]="true" [(selection)]="selectedMaintenanceDay" [tableStyle]="{'table-layout':'auto'}">
          <ng-template pTemplate="header" let-columns>
 <td >
        <p-cellEditor>
            <ng-template pTemplate="input">
                <input pInputTextarea type="text" 
                placeholder="Add Remarks"
                 [(ngModel)]="rowData.remarks" [ngStyle]="{'width':'100%'}" >
            </ng-template>
            <ng-template pTemplate="output">
                {{rowData.remarks}}
            </ng-template>
          </p-cellEditor>
              
    </td>
```

**What is the motivation / use case for changing the behavior?**
To allow user to edit the existing remarks upon click the edit button within the same row. 

**Please tell us about your environment:**

Angular CLI: 8.1.1
Node: 10.16.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.801.1
@angular-devkit/core         8.1.1
@angular-devkit/schematics   8.1.1
@schematics/angular          8.1.1
@schematics/update           0.801.1
rxjs                         6.4.0

* **Angular version:** 5.X

* **PrimeNG version:** 5.X

"version": "7.1.0-rc.1",

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome 
Firefox 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES7
* **Node (for AoT issues):** `node --version` =   
Node: 10.16.0

**Comment by mshemadarshini** [comment]
Hello is there anyone has solution for this

**Comment by anjelchen** [comment]
hi,
check your input editor code - either use <textarea> with pInputTextarea or use <input type="text"> with pInputText.

also your minimal code is unclear - you don't use ng-template pTemplate="body" and where is your rowData variable defined?

clean up your code and create a stackblitz example, so that it is runnable by others.

**Comment by cagataycivici** [comment]
Please use forum for support requests and questions.
