### ISSUE TITLE
Typing times between 12:00AM-12:59AM save as PM

### ISSUE THREAD

**Issue by stanglersm** [primefaces/primeng#7977]
**I'm submitting a ...** 
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When using a p-calendar with both a date & time selector with text entry enabled & 12hr format used, using the text input to select a time between 12:00AM - 12:59AM is switched to PM on blur of the field. 

**Expected behavior**
The time's morning/afternoon indicator (AM/PM) should be maintained.

One of my colleagues made a fix in this PR: https://github.com/RLijewski/primeng/commit/d76d575492961ad741d0861dab3b4998f3508888

**Minimal reproduction of the problem with instructions**

1. Open calendar date & time chooser
2. In the text input field, type in any date with a time of 12:00 AM
3. Select away from the field

**What is the motivation / use case for changing the behavior?**
So that we can default a date to have a time of midnight that day if a time is not identified by the user

**Please tell us about your environment:**
Windows, IntelliJ, HTTP, p-calendar is in a drawer and within a form

* **Angular version:** 6.0

* **PrimeNG version:** 6.1

* **Browser:** [ Chrome 75 ]
 
* **Language:** [ TypeScript 3.2.4 ]

* **Node (for AoT issues):** `node --version` =

**Comment by RLijewski** [comment]
PR here - https://github.com/primefaces/primeng/pull/7960

**Comment by cagataycivici** [comment]
PR merged, thank you.
