### ISSUE TITLE
p-inputMask with angular 8 doesn't set value

### ISSUE THREAD

**Issue by truadeveloper** [primefaces/primeng#7979]
in ngOnInit

`this.formGroup.setValue(value); `

doesn't set p-inputMask value with angular 8 and following p-inputMask code;

` @ViewChild('input', { static: false }) inputViewChild: ElementRef; `

changing to

` @ViewChild('input', { static: true }) inputViewChild: ElementRef; `

fix the problem,
also

```
 setTimeout(() => {
   this.formGroup.setValue(value);
}, 0);
```

works.

**Comment by adelcioml** [comment]
I have the same problem.

<p-inputMask formControlName="ini" mask="99/99/9999"></p-inputMask>


this.formulario.controls['ini'].setValue(moment(Date.now()).format('L'));

they set but doesnt show...

any solution?

**Comment by sergiogoncalves** [comment]
I'm having the same problem.

**Comment by kt215** [comment]
Probably a separate issue, but: I upgraded to Angular 8 and I use p-inputMask with ngrx-forms. Values are set but I see lots of ExpressionChangedAfterItHasBeenCheckedError in the console for the p-inputMask control. These errors did not occur with Angular 7.

**Comment by leonetosoft** [comment]
Same problem here, I had to do the hack method below:
```
setTimeout(() => {
        this.formGroup.patchValue({
          descricao: rs.data.prestadorPorId.descricao,
          cnpj_cpf: rs.data.prestadorPorId.cnpj_cpf,
          tipo: rs.data.prestadorPorId.tipo,
          fone: rs.data.prestadorPorId.fone,
          grupoProcedimento: rs.data.prestadorPorId.grupoProcedimentos.map((el) => ({ descricao: el.descricao, value: el.id })),
          prestadorProfissional: rs.data.prestadorPorId.profissionaisExecutantes.map((el) => ({ nome: el.nome, crm: el.codigo_conselho, value: el.id }))
        });
      }, 0);

```

**Comment by cagataycivici** [comment]
Is ivy enabled?

**Comment by truadeveloper** [comment]
ivy not enabled

**Comment by kt215** [comment]
Commit 35ba346 fixed my ExpressionChangedAfterItHasBeenCheckedError issue too.

**Comment by zakharenkov** [comment]
I have the same problem on Angular 9 and PrimeNG 9.04

**Comment by ZVARKO** [comment]
> I have the same problem on Angular 9 and PrimeNG 9.04

I created issue yesterday https://github.com/primefaces/primeng/issues/8727

**Comment by lmorelato** [comment]
I have the same issue on Angular 9.1.4 and PrimeNG 9.1.0.
