### ISSUE TITLE
Autocomplete onKeydown event

### ISSUE THREAD

**Issue by arushijain-va** [primefaces/primeng#7987]
Allow flexibility to override onKeydown event of autocomplete.

I want to disable the functionality of selecting highlighted option on tab.

```
 //tab
                case 9:
                    if (this.highlightOption) {
                        this.selectItem(this.highlightOption);
                    }
                    this.hide();
                    break;
```

**Comment by cagataycivici** [comment]
That should be an option like selectOnTab instead, feel free to create a new ticket please.
