### ISSUE TITLE
Error in table module while loading in Universal mode

### ISSUE THREAD

**Issue by vahidvdn** [primefaces/primeng#7988]
When I load with `ng serve`, table works fine without any errors. But when I run it in ssr mode with Universal, I get the following errors:

```
ERROR { NullInjectorError: StaticInjectorError(AppServerModule)[ScrollableView -> Table]:
  StaticInjectorError(Platform: core)[ScrollableView -> Table]:
    NullInjectorError: No provider for Table!
```

Angular Version: 8.0.2

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
