### ISSUE TITLE
Dynamic Dialog Inside dynamic dialog can't close

### ISSUE THREAD

**Issue by imaa** [primefaces/primeng#7989]
Hi Dears , 

I see there is a bug when i open dynamic dialog inside dynamic dialog i cant close the first dialog programming 

APP----> click "show Modal" ----> click "show inner Modal" ---> click "close" ----> click "close"(HERE NOT WORKING  :oops: )

sample :" 

https://stackblitz.com/edit/angular-1rikds

**Comment by imaa** [comment]
@vincent @DerekLiang @csokun @Skyr

**Comment by imaa** [comment]
@cagataycivici

**Comment by wmc3721** [comment]
I alse met the problem, and solved it by #7077

**Comment by wmc3721** [comment]
@imaa

**Comment by cagataycivici** [comment]
Please use forum for support requests and questions.
