### ISSUE TITLE
Abiltity to set minimal offset on positionoverlay on dialog

### ISSUE THREAD

**Issue by negberts** [primefaces/primeng#7992]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
We call in the ngAfterViewInit of our component the positionOverlay method of the dialog to make sure it stays centered when changes in the content of the dialog occur. But sometimes these changes are minimal, for example when opening a material select. The dialog starts flickering because it moves a pixel up and then down again.

**Expected behavior**
 It would be nice if it is possible to set a minimal offset at which recentering should occur. So for example 5px, that when the repositioning is within the margin of 5px no recentering occurs but only when it exceeds the minimal offset.

**What is the motivation / use case for changing the behavior?**
Prevent flickering of the dialog because of moving 1px up and down during positioning.

* **Angular version:** 5.X
8.1.3

* **PrimeNG version:** 5.X
8.0.2

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9 which has a new Dialog implementation, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
