### ISSUE TITLE
Dialog center does not reset styles properly

### ISSUE THREAD

**Issue by zsoltgyongyosi** [primefaces/primeng#7994]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-dtm6xx

**Current behavior**
Dialog container has `display: none`.

**Expected behavior**
Dialog should be visible.

**What is the motivation / use case for changing the behavior?**
The change is safe and solves some edge cases.

**Comment by yigitfindikli** [comment]
fixed in https://github.com/primefaces/primeng/issues/8472
