### ISSUE TITLE
dropdown throws "event is not defined" error in PrimeNG v8.0.2 on Firefox

### ISSUE THREAD

**Issue by thaihacong** [primefaces/primeng#8003]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-tlabav?file=package.json
or,
https://www.primefaces.org/primeng/#/dropdown

**Current behavior**
Click on the dropdown, then click outside.
Firefox throws error `ReferenceError: event is not defined` in console
The error does not happen on Chrome.

**Expected behavior**
There should be no console errors on all browsers.

* **Angular version:** 8.1.3

* **PrimeNG version:** 8.0.2
The error does not happen on PrimeNG v8.0.1.
It could be because of this commit https://github.com/primefaces/primeng/commit/2944fce30e8beac5e8152e829bdb1be9a29a78db

![dropdown-event-not-defined-2](https://user-images.githubusercontent.com/8019304/62151401-84268680-b300-11e9-9477-e309e267e589.png)

![dropdown-event-not-defined-1](https://user-images.githubusercontent.com/8019304/62151411-8ab4fe00-b300-11e9-8e79-eab641c31d8d.png)

* **Browser:** Firefox 40.0.3 on MacOS, Firefox 60.6.1esr (64-bit) on CentOS Linux release 7.6.1810

**Comment by benoitbb** [comment]
Same problem here

**Comment by yigitfindikli** [comment]
Hi @thaihacong ,
I couldn't replicate it with Firefox 67.0.4. What is your Firefox version?

**Comment by thaihacong** [comment]
@yigitfindikli Thank you for your fast response.
I could also not reproduce it on
- Firefox 68.0.1 (64-Bit) on Windows 10
- Firefox 68.0.1 (64-Bit) on MacOS

But the error happens on
- Firefox 40.0.3 on MacOS
- Firefox 60.6.1esr (64-bit) on CentOS Linux release 7.6.1810
