### ISSUE TITLE
Content is not completely visible and scrollbar is enabled for table with one row

### ISSUE THREAD

**Issue by alexandraFlavia9** [primefaces/primeng#8006]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-tb-search?file=src/app/app.component.ts

**Current behavior**
When I filter the data from a data table and a single result row is found, the scrollbar remains enabled and the content of this row is not completely visible. This behavior makes it difficult to manage the content of the row in case there is an input inside a cell.

![wrapped-row](https://user-images.githubusercontent.com/15904072/62290195-67599280-b469-11e9-95eb-e3d43031a206.PNG)

**Expected behavior**
When only one row is displayed in the data table, a scrollbar is not necessary and the content of this should be fully visible.

**Minimal reproduction of the problem with instructions**
       Introduce "Odonnell" in the input.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 7.X

* **PrimeNG version:**7.X

* **Browser:** [Chrome XX | Firefox XX | IE XX ]
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   10.15.3

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
