### ISSUE TITLE
Lazy Loaded Table should have the ability to not be reloaded on .reset()

### ISSUE THREAD

**Issue by davisb10** [primefaces/primeng#8008]
_Not sure if this is a bug or something that should be added._

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**

In trying to use a Lazy Loaded table for a search form, that also has a clear function, if you use the .reset() method on the table, the table is reloaded via the onLazyLoad() event.

**Expected behavior**

The ability to completely clear a lazy loaded table without it being reloaded.

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Comment by davisb10** [comment]
@cagataycivici This is caused by this if statement https://github.com/primefaces/primeng/blob/master/src/app/components/table/table.ts#L1371

When the table is set as lazy, this onLazyLoad event is emitted, thus causing data to be reloaded as it appears that something changed with the data
