### ISSUE TITLE
Carousel: Cannot read property 'nativeElement' of undefined error

### ISSUE THREAD

**Issue by tonnguyen** [primefaces/primeng#8009]
**I'm submitting a bug**
```
[x ] bug report => Search github for a similar issue or PR before submitting. There is a similar one but it has been closed https://github.com/primefaces/primeng/issues/7825
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Live demo: https://stackblitz.com/edit/carousel-7825?file=src%2Fapp%2Fapp.component.html

**Current behavior**
The error occurs when using Carousel with an async value.

**Expected behavior**
Should not throw any error at the console.

**Minimal reproduction of the problem with instructions**
Setting an async value for the Carousel and load the page, then you will see the error in the developer console.

* **Angular version:** 8.0.3

* **PrimeNG version:** 8.0.0

* **Browser:** Chrome, I did not test on other browsers.

**Comment by mertsincan** [comment]
Could you please try it with the new Carousel component? PrimeNg v8.1.0+
https://github.com/primefaces/primeng/issues/3896

Best Regards,
