### ISSUE TITLE
More than one Autocomplete inputs bound to same model in a form nulls whole model if one gets edited

### ISSUE THREAD

**Issue by bogacg** [primefaces/primeng#801]
I have a form where 3 autocomplete inputs bound to different properties of that same model. When I type and select model, all 3 inputs got populated from model properties as defined by "field" attributes in each respectively.

![image](https://cloud.githubusercontent.com/assets/5073927/18033216/d4097762-6d25-11e6-9670-887be43a65e6.png)

However, if I delete/edit one of the inputs, because typed/edited text assigned as whole model, other inputs become that same text.

![image](https://cloud.githubusercontent.com/assets/5073927/18033217/dead120a-6d25-11e6-8658-c109668d7f93.png)

It would be better if there is an directive attribute to make Autocomplete act as "field" defined property of model becomes typed/edited text or null and not whole model object.
Therefore other Autocomplete inputs bound to same object keeps their value (assigned model keeps whole properties as first selected except one edited)

**Comment by cagataycivici** [comment]
Please provide a plunkr, issue is not clear on our side.
