### ISSUE TITLE
showing exception nextElementSibling when resizing the column in primeng table 

### ISSUE THREAD

**Issue by SRICHANDANCHINNAM** [primefaces/primeng#8010]
If you have a PrimeNG PRO Support subscription please post your issue at;

Hi Folks,

I am using primeng(7Version) with resizable column with scroll  behaviour..

I have followed the primeng site and gone through google as well..
Still i am facing 

 Cannot read property 'nextElementSibling' of undefined
    at Table.push../node_modules/primeng/components/table/table.js.Table.resizeColGroup (table.js:1296)
    at Table.push../node_modules/primeng/components/table/table.js.Table.onColumnResizeEnd 

The above exception..

I have used in my project like below

                              <ng-template pTemplate="colgroup" let-columns="columns">
                                <colgroup>
                                    <col *ngFor="let col of columns" [style.width]="col.width">
                                </colgroup>
                            </ng-template>

and i have also used  [resizableColumns]="true" columnResizeMode="expand"

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG (https://stackblitz.com/edit/github-gz9jd3). If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
