### ISSUE TITLE
Ability to unsort Data aka Removable Sort

### ISSUE THREAD

**Issue by ranthonissen** [primefaces/primeng#8013]
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

I have created a directive that is a possible solution to a previously reported bug (#6609) and feature request (#4493) to "undo" sorting on a third click on the table header.
It overrides the sort(event) method from the table to allow for this behavior.

This is what it looks like:

    import { Directive, Host, Self, Optional } from '@angular/core';
    import { Table } from 'primeng/table';

    @Directive({
        selector: '[withUnsort]'
    })
    export class TableUnsortDirective {

        defaultSortOrderInitialized = false;

        constructor(@Host() @Self() @Optional() public pTable: Table) {

            pTable.tableService.valueSource$.subscribe((val: any[]) => {
                if (val != null && val.length > 0 && !this.defaultSortOrderInitialized) {
                    let i = 0;
                    val.forEach(v => {
                        v['_defaultSortOrder'] = i++;
                    });
                    this.defaultSortOrderInitialized = true;
                }
            });

            pTable.sort = (event: any) => {
                const originalEvent = event.originalEvent;

                if (pTable.sortMode === 'single') {
                    if (pTable.sortField === event.field && pTable.sortOrder === -1) {
                        event.field = '_defaultSortOrder';
                    }

                    pTable._sortOrder = (pTable.sortField === event.field) ? pTable.sortOrder * -1 : pTable.defaultSortOrder;
                    pTable._sortField = event.field;
                    pTable.sortSingle();
                }
                if (pTable.sortMode === 'multiple') {
                    const metaKey = originalEvent.metaKey || originalEvent.ctrlKey;
                    const sortMeta = pTable.getSortMeta(event.field);

                    if (sortMeta) {
                        if (!metaKey) {
                            if (pTable._multiSortMeta.length > 1) {
                                pTable._multiSortMeta =  [{ field: event.field, order: pTable.defaultSortOrder }];
                            } else {
                                if (sortMeta.order === -1) {
                                    pTable._multiSortMeta = [];
                                } else {
                                    pTable._multiSortMeta =  [{ field: event.field, order: sortMeta.order * -1 }];
                                }
                            }
                        } else {
                            for (let i = 0; i < pTable._multiSortMeta.length; i++) {
                                if (pTable._multiSortMeta[i].field === sortMeta.field) {
                                    pTable._multiSortMeta.splice(i, 1);
                                }
                            }
                            if (sortMeta.order === 1) {
                                sortMeta.order = sortMeta.order * -1;
                                pTable.multiSortMeta.push(sortMeta);
                            }
                        }
                    } else {
                        if (!metaKey || !pTable.multiSortMeta) {
                            pTable._multiSortMeta = [];
                        }
                        pTable.multiSortMeta.push({ field: event.field, order: pTable.defaultSortOrder });
                    }

                    pTable.sortMultiple();
                }

                if (pTable.isStateful()) {
                    pTable.saveState();
                }

                pTable.anchorRowIndex = null;
            };
        }
    }

And add a "withUnsort" attribute to the table.

    <p-table [columns]="cols" [value]="cars1" withUnsort>
        ...
    </p-table>

**Comment by ProfEibe** [comment]
Are there any plans to implement this in the near future?
I would be interrested too!

**Comment by loxy** [comment]
It is already implemented in #8072, but the guys want to use their "own" implementation, which never comes. This is open source in action...

**Comment by then3rdman** [comment]
Good to see this has progressed. I am sure their 'own' solution will be MUCH better.......

**Comment by szandra-homonnai** [comment]
We started to use PrimeNG not long ago and our clients really love it, but their first concern was that this basic feature is missing from the table :/  So yes, this is a really needed feature and it would be really nice if the Prime team would address this issue.

**Comment by loxy** [comment]
Yeah, close it and the problem is gone...

**Comment by bgl3317** [comment]
Why was this closed? Is there an official solution?

**Comment by loxy** [comment]
No, there isn't. And there will never be. Move to https://taiga-ui.dev/. Much better library!

**Comment by bgl3317** [comment]
@cagataycivici, you mentioned that the PrimeNG team prefers implementing this particular feature on your side in April of last year. I see that @ranthonissen closed on July 6th of this year. If the team had plans for this and no longer sees this as an open issue, what was the resolution?

**Comment by then3rdman** [comment]
Gave up on this library long ago for basically this reason. So many glaring omissions that they have no intent of adding and won't take the help when people give it. 

On 23 Sep 2021, 4:23 am, at 4:23 am, bgl3317 ***@***.***> wrote:
***@***.***, you mentioned that the PrimeNG team prefers

**Comment by ranthonissen** [comment]
@bgl3317 I closed the issue myself, because PrimeNg showed no interest in the feature.
I have my own solution for it.

**Comment by bgl3317** [comment]
@ranthonissen, it may be worth reopening even though you have developed your own directive just so that the PrimeNG developers still have this as a visible issue in their backlog. It seems there are enough people with this need that it warrants at least a chance of getting an official solution in a PrimeNG release.

**Comment by then3rdman** [comment]
@bgl3317 this has been an issue for2 years. A pull request was created that solved it and that was closed by the devs. 2 years later they have not solved the issue..... Hell its not an issue, its completely missing functionality! 

I like many other have long dropped this library in favour  of others

**Comment by buchatsky** [comment]
As for me, it should be Ctrl+Click which unsort the column, not the third Click.

**Comment by gianluca-moro** [comment]
It still baffles me how primeng in 2024 still does not support this basic feature natively.

**Comment by gianluca-moro** [comment]
It's 2024 and this is still not available natively by primeng, is it?

**Comment by staplKody** [comment]
@gianluca-moro it would appear so. There is a 'removable' sort in their documentation, however you may notice that the third click in their example will always result in no sort, regardless if it was on an already sorted column. It's factually incorrect code and I thought I had messed up somewhere in my project.

**Comment by staplKody** [comment]
I was able to achieve this functionality via some vanilla angular mixed in with the pTable component. It's not nearly as straightforward as using the pTable's built in sort stuff, but it gets the job done and you can alternate back to unsorted unlike what is default supported. 

```
//Typescript side:

  //object showing what fields are sorted
  //-1 is desc (biggest at top), 1 is asc (smallest at top), 0 is no sort (default)
  sortStates = {
    RCVDATE: 0,
    WAREHOUSE: 0,
    EWIB_ERROR_CODE: 0,
    BALE_COUNT: 0
  }

customSortNew(event: SortEvent){
    console.log('Entered the customSortNew function with event: ', event);
    this.toggleSortNew(event.field);
  }

  toggleSortNew(field: string){

    //set all other fields of sortStates to 0 before manipulating the selected field's state
    Object.keys(this.sortStates).forEach(key => {
      if(key !== field){
        this.sortStates[key] = 0;
      }
    });

    switch (this.sortStates[`${field}`]) {
      case -1:
        this.sortStates[`${field}`] = 0
        this.sortedSuspenseGroups = [...this.suspenseGroups]; //resets the order back to the original array  
        break;

      case 1:
        this.sortStates[`${field}`] = -1
        this.sortedSuspenseGroups = [...this.suspenseGroups].sort((a, b) => {
          if (a[field] < b[field]) return 1;
          if (a[field] > b[field]) return -1;
          return 0;
        }); // sort in descending order by the provided field
        break;

      case 0:
        this.sortStates[`${field}`] = 1
        this.sortedSuspenseGroups = [...this.suspenseGroups].sort((a, b) => {
          if (a[field] < b[field]) return -1;
          if (a[field] > b[field]) return 1;
          return 0;
        }); // sort in ascending order by the provided field
        break;

      default:
        console.log('error, field was not valid', field);
        break;
    }
  }

```


in the typescript, I have an object which stores the sort order as an integer for each column I have in my table. I use this 'state' (not technically but it's what I called it) in the 'toggleSortNew()' function as well as in the angular html to show how a column is currently sorted. 

Here is where the magic happens in the HTML
```
<tr>
                <th pColumn="RCVDATE" (click)="toggleSortNew('RCVDATE')">
                    Recieve Date 
                        @if(sortStates.RCVDATE === 0){
                            NO SORT
                        }
                        @if(sortStates.RCVDATE === 1){
                            ASCENDING
                        }
                        @if(sortStates.RCVDATE === -1){
                            DESCENDING
                        }
                </th>
                
                <th pColumn="WAREHOUSE" (click)="toggleSortNew('WAREHOUSE')">
                    Warehouse 
                    @if(sortStates.WAREHOUSE === 0){
                        NO SORT
                    }
                    @if(sortStates.WAREHOUSE === 1){
                        ASCENDING
                    }
                    @if(sortStates.WAREHOUSE === -1){
                        DESCENDING
                    }
                </th>
                <th pColumn="EWIB_ERROR_CODE" (click)="toggleSortNew('EWIB_ERROR_CODE')">
                    Error Code 
                    @if(sortStates.EWIB_ERROR_CODE === 0){
                        NO SORT
                    }
                    @if(sortStates.EWIB_ERROR_CODE === 1){
                        ASCENDING
                    }
                    @if(sortStates.EWIB_ERROR_CODE === -1){
                        DESCENDING
                    }
                </th>
                <th pColumn="BALE_COUNT" (click)="toggleSortNew('BALE_COUNT')">
                    Number of Bales 
                    @if(sortStates.BALE_COUNT === 0){
                        NO SORT
                    }
                    @if(sortStates.BALE_COUNT === 1){
                        ASCENDING
                    }
                    @if(sortStates.BALE_COUNT === -1){
                        DESCENDING
                    }
                </th>
                <th></th>
            </tr>
```
Using Angular's @if control flow decorator, you can inspect the sortState for each column and display something different. 

This is just for any folks coming across this issue in 2024 who are looking for a simple solution.
