### ISSUE TITLE
Table Row Group Selections

### ISSUE THREAD

**Issue by Anand249** [primefaces/primeng#8014]
**Row Group Table Selection Issue**
The Implementation for the issue related to the table row group selection is mentioned in the below stackblitz link.

https://stackblitz.com/edit/tablewithbadselect

**Current behavior**
Issue 1 :  I implemented a table using the row group functionality of primeNg table but during the (onRowSelect) event we are unable to achieve select operation in single click.  It works only on double click.

Issue 2 : Also when ever i select a specific row all the rows are Highlighted.

**Expected behavior**
Issue 1 : The Row Selection should work with single click.
Issue 2 : Also only specific row get highlighted when we click. 

https://stackblitz.com/edit/tablewithbadselect
NGX Prime Theme : 3.0.2

**Please tell us about your environment:**
Visual Studio Code

* **Angular version:** 
      6.1.7

* **PrimeNG version:**
      6.0.1
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X |

* **Node (for AoT issues):** `node --version` =   v8.9.4

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
