### ISSUE TITLE
p-dropdown not closing when clicking outside of component (iPad)

### ISSUE THREAD

**Issue by teuf22** [primefaces/primeng#8020]
I**Current behavior**
Dropdown list doesn't close when clicking outside of component - iPad (works ok on desktop and works on Android)

**Expected behavior**
Dropdown list closes when clicking outside of component

**Minimal reproduction of the problem with instructions**
On a iPad, go to:   https://www.primefaces.org/primeng/#/dropdown
and use the example provided

* **Angular version:** 7.2
* **PrimeNG version:** 8.0.2
* **Browser:** Mobile Chrome 75 or  iOS Safari 12.1.1 on IOS 12

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
