### ISSUE TITLE
Frozen columns should be scrollable

### ISSUE THREAD

**Issue by HoneyBadgerSeeker** [primefaces/primeng#8021]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
No need of a plunkr case because the bug is present at https://www.primefaces.org/primeng/#/table/scroll in the example "Frozen Columns".

**Current behavior**
Use the mouse wheel to scroll down and up inside of a frozen column. 
Nothing happen.

**Expected behavior**
The rows scroll up and down (exactly like when we put the cursor inside of a non frozen column)

**Minimal reproduction of the problem with instructions**
Have a p-table with 1 or more frozen column and enough rows to have a vertical scrollbar inside the table.
Put the cursor inside of a frozen column.
Use the mouse wheel to scroll up and down.

**Please tell us about your environment:** Windows 10
* **Angular version:** 7.2
* **PrimeNG version:** 8.0.1
* **Browser:** Firefox 68, Chrome Canary 78, Chrome 51

_____________________________________________________________________

**Workaround** (a very bad one but an effective one...)

**index.html** 

Inside the index.html we catch all scroll event by overriding EventTarget.prototype.addEventListener.

` <script>
         var scrollEvents = [];
        var f = EventTarget.prototype.addEventListener;
         EventTarget.prototype.addEventListener = function(type, fn, capture) {
             this.f = f;
             this.f(type, fn, capture);
             if (type === 'scroll') {
                scrollEvents.push(fn);
            }
         }
     </script>`

**component.ts** 

Inside the component.ts we remove the scroll from  https://github.com/primefaces/primeng/blob/3f8da6f7dcdf74cc2acd4393d644e4a0487593af/src/app/components/table/table.ts#L2443
and we scroll manually the table. 
We have to remove it because it blocks us from adding a scrollable event on the frozen column.

If we don't remove it, this is what happen after we add the scroll event on the frozen column:
we scroll the non frozen column 
=> the non frozen scroll event triger (ie. bodyScrollListener)  and scroll the row inside the non frozen and frozen column 
=> the frozen scroll event trigger  (ie. the one we added)  and scroll the row inside the frozen and non frozen column 
=> the non frozen scroll event triger (ie. bodyScrollListener)  and scroll the row inside the non frozen and frozen column 
=> etc. 

the result of that is a very very slow scroll on the non frozen side which make it unusable in reality.

And now the code of the component (sorry for the formatting)

Some attributes
`private _isSyncingLeftScroll = false;
    private _isSyncingRightScroll = false;
    private _classNamesScrollableTableBody = 'ui-table-scrollable-body';
    private _frozenName = 'FROZEN';
    private _nonFrozenName = 'NONFROZEN';`

Sync the scroll between the non frozen rows and the frozen rows
` https://stackoverflow.com/a/54005290/10691359
    scroll = (event: any): void => {
        const tableBodies = document.getElementsByClassName(this._classNamesScrollableTableBody);
        const frozenScroll = tableBodies[0] as HTMLElement;
        const nonfrozenScroll = tableBodies[1] as HTMLElement;
        // https://stackoverflow.com/a/41998497/10691359
        if (event.srcElement.getAttribute('name') === this._nonFrozenName) {
            if (!this._isSyncingRightScroll) {
                this._isSyncingLeftScroll = true;
                frozenScroll.scrollTop = event.srcElement.scrollTop;
            }
            this._isSyncingRightScroll = false;
        } else if (event.srcElement.getAttribute('name') === this._frozenName) {
            if (!this._isSyncingLeftScroll) {
                this._isSyncingRightScroll = true;
                nonfrozenScroll.scrollTop = event.srcElement.scrollTop;
            }
            this._isSyncingLeftScroll = false;
        }
// header scroll
        const tableNonFrozenHeader = document.getElementsByClassName(this._CLASSNAMES_SCROLLABLE_HEADER_TABLE);
        (tableNonFrozenHeader[1] as HTMLElement).style.marginLeft = -1 * nonfrozenBody.scrollLeft + 'px';
    };`

We remove the bodyScrollListener + we catch the global scroll event  + we add our own scroll event 
`private ngAfterViewInit() {
        const tableBodies = document.getElementsByClassName(this._classNamesScrollableTableBody);
        let scrollEvents = window[scrollEvents];
        tableBodies[0].setAttribute('name', this._frozenName);
        tableBodies[1].setAttribute('name', this._nonFrozenName);
        scrollEvents.forEach((fn, i) => {
            if (i === 2) {
                tableBodies[1].removeEventListener('scroll', fn);
            }
        });
        window.addEventListener('scroll', this.scroll, true); 
    }
    ngOnDestroy(): void {
        window.removeEventListener('scroll', this.scroll, true); 
    }`

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
