### ISSUE TITLE
P-slider pointers fails at set min and max value dynamically

### ISSUE THREAD

**Issue by juandsan91** [primefaces/primeng#8023]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
After set dynamically min and max values of p-slider component the pointer of max value only moves to the rigth starting its value on max value and next value at min value +1, and the pointer of min value moves to max value outside of the component view.

[https://imgur.com/aiAXHAC](url)
[https://imgur.com/g7DukIv](url)
[https://imgur.com/DvQCFyb](url)

I checked forum and there is'nt any solution

**Expected behavior**
Min and Max pointer moves correctly inside the component.

**Minimal reproduction of the problem with instructions**
I have 3 variables in component and call a function on constructor where I fill them, they are only numeric data, in array (rangeValues) set copies of variables.
code on component

`egresadoService.getMaxSalario().subscribe(max=>{
      egresadoService.getMinSalario().subscribe(min=>{
        this.salMin=min.min;
        this.salMax=max.max;
        this.rangeValues=[JSON.parse(JSON.stringify(this.salMin)),JSON.parse(JSON.stringify(this.salMax))];
      },err=>{  
      }); 
    },err=>{
    });`

There is the code in html

`<div class="my-auto align-self-center col-12">
                <p-slider class="" [(ngModel)]="rangeValues" [range]="true" [min]="salMin" [max]="salMax"></p-slider>
            </div> `

**Please tell us about your environment:**
Windows 10
primeng 6.1.4
angular/cli 6.1.5

* **Browser:** 
Firefox: 68.0.1

**Comment by misterjaffacakes** [comment]
The same issue can be reproduced without enabling the range attribute. If the min and max values are equal, the handle goes out of the slider boundaries. I know that having equal values defeats the purpose of the slider, but it just so happens we have such an use case.

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 9.0.5, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
