### ISSUE TITLE
FileUpload performance issues on android devices

### ISSUE THREAD

**Issue by fritzbauer** [primefaces/primeng#8024]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

Editor URL: https://stackblitz.com/edit/github-vyswwe
App URL: https://github-vyswwe.stackblitz.io

**Current behavior**
When a file has been uploaded using the FileUpload any other UI interaction becomes really slow. I was observing this for the customUpload functionality, however it seems it also happens for non-custom uploads.
While it is running fine on Chrome on Windows it is getting really slow on Chrome on Android.

**Expected behavior**
No performance issues after a file upload.

**Minimal reproduction of the problem with instructions**
Editor URL: https://stackblitz.com/edit/github-vyswwe
App URL: https://github-vyswwe.stackblitz.io

1. Create the app
* Adding p-fileupload & p-toggleButton & p-dropdown to the stackblitz template.
* Add an import of HttpClient to the app.module.ts and the HttpClientModule to the imports array.
* Add some testing variables in app.component.ts.
2. Open the App with Chrome on an Android device
3. Try to use the dropdown and toggle components --> They will work fine
4. Upload a file ~1MB (e.g. https://www.pexels.com/photo/bare-tree-in-the-middle-field-covered-in-snow-1909331/ )
5. Try to use the dropdown and toggle components again --> They will work really slow
Optional:
6. Delete the uploaded file
7. Try to use the dropdown and toggle components --> They will work fine again

**What is the motivation / use case for changing the behavior?**
Being able to use the FileUpload component on mobile devices.

**Please tell us about your environment:**
Android 9 EMUI 9.0.1 on Huawei Mate 20 Lite
Was able to reproduce with: Chrome, Opera, Edge
Was not able to reproduce with: Firefox

* **Angular version:** 8.0.3

* **PrimeNG version:** 8.0.0

* **Browser:** Mobile Chrome | Mobile Edge | Mobile Opera

Not occuring in: Desktop Browsers | Mobile Firefox
 
* **Language:** all

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
