### ISSUE TITLE
Radial option for color picker

### ISSUE THREAD

**Issue by LukeTOBrien** [primefaces/primeng#8026]
Hello,

I come from a jQuery background and I I am currently using [Farbtastic Color Picker](https://acko.net/blog/farbtastic-jquery-color-picker-plug-in/) In my project because I think it looks cool.  
I am now looking at switching over to use your components, but I will miss the Radial picker.  
So I would suggest that perhaps you could add an option something like `[radial]="true"`.

Thanks ;-)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
