### ISSUE TITLE
Feature request: Prompt overlay panel

### ISSUE THREAD

**Issue by LukeTOBrien** [primefaces/primeng#8028]
Hello,

Currently if I want to promt for a input string I would have to use [Dynamic Panel](https://www.primefaces.org/primeng/#/dynamicdialog).  
What I would ideall like is something like the [window.prompt](https://www.w3schools.com/jsref/met_win_prompt.asp), so I could do something like:

```HTML
<button type="text" (click)="prompt()" pButton icon="pi pi-check" label="Prompt"></button>
```
```JavaScript
    prompt() {
        this.promptService.prompt({
            message: 'Please enter your name',
            default: 'Harry Potter',
            accept: () => {
                //Actual logic to perform a confirmation
            }
        });
    }
```

;-)

**Comment by cagataycivici** [comment]
You can use confirm dialog instead.
