### ISSUE TITLE
confirmDialog transform is causing dialog to sit behind the mask

### ISSUE THREAD

**Issue by johnfabian** [primefaces/primeng#8029]
The confirmDialog transform is causing the dialog to sit behind the mask causing the text to look blurry. If you uncheck the transform in chrome dev tools you will see and is also like that on the demo site as well. appendTo="body" does not fix the issue. Is there some scss I can edit to fix this?

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9 which has a new Dialog implementation, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
