### ISSUE TITLE
InputMask always setting class ui-inputwrapper-focus

### ISSUE THREAD

**Issue by ctaylor-osv** [primefaces/primeng#8032]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-p2ummj

**Current behavior**
The `p-inputMask` component always has the class `ui-inputwrapper-focus` applied whether the input has focus or not.

**Expected behavior**
The `ui-inputwrapper-focus` class should be applied only when the input has focus.

The commit [Fixed #5874 - Focus method for Input Mask component](https://github.com/primefaces/primeng/commit/045cc657d5da2ccab7e9b26342f8c29513d86a11#diff-d9e950d7e43e31e8f32aa65b698dcf42) switched the internal flag from `focus` to `focused` and added a `focus()` method. However, the host binding for `ui-inputwrapper-focus` is still pointing to `focus` which is always defined.

**Minimal reproduction of the problem with instructions**
Add a p-inputMask component.

* **Angular version:** 8.X

* **PrimeNG version:** 8.X

* **Browser:** [all]
 
* **Language:** [all]

**Comment by ctaylor-osv** [comment]
@cagataycivici Any chance at getting this looked at? It's a pretty trivial fix for something that was introduced 9 ago.

**Comment by yigitfindikli** [comment]
Fixed in https://github.com/primefaces/primeng/commit/078f21b7ca631c86a2c65aed8080f0b3062a4dd6
