### ISSUE TITLE
Autocomplete has wrong width when using appendTo body

### ISSUE THREAD

**Issue by plevko** [primefaces/primeng#8033]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/angular-euhmsr

**Current behavior**
In case of long strings in suggestions, the autocomplete has wrong width and is out of expected bounds. This happens when using option appendTo="body".

**Expected behavior**
Autocomplete has maxWidth the same as minWidth

**Minimal reproduction of the problem with instructions**

* **Angular version:** 8.X

* **PrimeNG version:** 8.X

* **Browser:** [all]

 
* **Language:** [all]

**Comment by JacobSiegle** [comment]
I'm not sure I follow what is incorrect here. Can you possibly post a screenshot of how you're expecting it to work?

**Comment by plevko** [comment]
![image](https://user-images.githubusercontent.com/6647984/62886897-c14d3880-bd44-11e9-8bf3-f27c19814d25.png)

I am expecting the autocomplete dropdown to have max width the same as input (the green lines). Current behaviour you can see highlighted in red.

**Comment by JacobSiegle** [comment]
If the word is too long it's going to go over the length of the popup no matter what, you can limit this by setting a width of 100% on .ui-autocomplete .ui-autocomplete-panel and it will put a scroll bar on the bottom of the popup. 

When you use appendTo you're moving the popup HTML element outside of the autocomplete element which causes it to lose context of what the width of the input element is. The only way to sync up the width of this currently would be to set the width manually.

I'm not sure a maintainer would change the way appendTo works to allow syncing the width state, I assume the way it's working now is the desired effect but i'm not entirely sure.

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
