### ISSUE TITLE
Multiple Selection Using Shift Key for Tree Table

### ISSUE THREAD

**Issue by lurames** [primefaces/primeng#8035]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

You can test here by doing the 'current behavior' example http://primefaces.org/primeng/#/treetable/selection

**Current behavior**
Select one node + shift + select other node = first node selected, last node selected but nodes between not selected

**Expected behavior**
Select one node + shift + select other node = everything selected between first selected node and the second 

Primefaces TreeTable works fine https://www.primefaces.org/showcase/ui/data/treetable/selection.xhtml

* **Angular version:** 7.2.15

* **PrimeNG version:** 7.1.2

**Comment by ekremkucuk** [comment]
Feature has not been implemented yet as PrimeNG version : v.11.3.2

Is there any roadmap plan for this feature?

**Comment by Mohamed-Ibrahim-M** [comment]
Hi, is there any idea when this feature will be implemented

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by kylemwhite** [comment]
It looks like this improvement has not yet been implemented. This can be seen by testing the showcase here: [https://primeng.org/treetable/selection](https://primeng.org/treetable/selection)
Scroll to the section titled `Multiple Selection with MetaKey`. Notice that multiple select with the ctl key works as expected but the shift key does not. Please re-open.

**Comment by ossandust** [comment]
> Please re-open.

+1 !

**Comment by lk-granit** [comment]
Could you please reopen it. 
Multiple selection in Tree table with metaKeySelection  = "true" is not working for Shift key. 
https://primeng.org/treetable#selectionmultiple

**Comment by polygonov** [comment]
Agree, multiple selection with shift isn't working now

**Comment by autonomobil** [comment]
Please reopen, also doesn't work for the normal tree
https://primeng.org/tree#multiple
