### ISSUE TITLE
The left and right arrow keys not working on input elements inside Tree

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primeng#8039]
Reported By PRO User;
> The issue is we have the Input box inside the PrimeNg Tree, earlier when we press the left and right arrow keys while inside the input, cursor inside the input used to move the left and right.
But now when we press the left and right arrow keys inside the input then it is collapsing the node and expanding the node.

**Comment by gauravp-dev** [comment]
Right arrow key and space keys still not working in input added inside a tree.
