### ISSUE TITLE
p-calendar overlay closes unexpectedly in p-cellEditor

### ISSUE THREAD

**Issue by nhnb** [primefaces/primeng#8042]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report (regression)
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/github-yxy3bm

**Current behavior**

If a calendar is used inside an editable table cell:

- The calendar overlay disappears when the dropdown-list for months is clicked on Firefox.
- The calendar overlay disappears when the dropdown-list for months is clicked a second time on Chrome.

**Expected behavior**

The calendar overlay stays open when a month is going to be selected.

**Minimal reproduction of the problem with instructions**

Put a `p-calendar [monthNavigator]="true" [yearNavigator]="true"` inside of a `p-cellEditor` as seen on https://stackblitz.com/edit/github-yxy3bm

- click the table cell to open the calendar overlay
- click on the dropdown list for month: Overlay disappears on Firefox, works on Chrome
- click on the dordownn list for month again (not an entry): Overlay disappears on Chrome

**What is the motivation / use case for changing the behavior?**

I like to continue to use dates in editable table cells after updating to PrimeNG 8.0.2. The issue was introduced by commit 8f439c35de07abcad01a680c70a7a635583404ff

**Please tell us about your environment:**

* **Angular version:** 8.1.2
* **PrimeNG version:** 8.0.2
* **Browser:** Chrome 76.0.3809.87 | Firefox 68.0.1
* **Language:** TypeScript

**Comment by nhnb** [comment]
Any news?

**Comment by nibosoft** [comment]
I have the same problem. Can it be fixed?

**Comment by rroex** [comment]
@nhnb Maybe you can start a pull request for your changes?

**Comment by nhnb** [comment]
> @nhnb Maybe you can start a pull request for your changes?

@rroex I did a pull request last August: https://github.com/primefaces/primeng/pull/8043

**Comment by rroex** [comment]
@cagataycivici Can you have a look?

**Comment by cagataycivici** [comment]
If you remove appendTo body it works, when the overlay is appended to body, table thinks outside is clicked and closes the cell so the calendar is removed. Without appendTo="body" no such problem occurs. One of the tricky parts of cell selection and overlays.

**Comment by Srinath-R395** [comment]
@ cagataycivici is it possible by any means to use appendTo=body without overlay closing? Because, just  having any of the behaviours inside a datatable results in a bad UX.. its been a year, any workaround as such ??
