### ISSUE TITLE
How to import css that component need?

### ISSUE THREAD

**Issue by keyiis** [primefaces/primeng#8045]
I only use Calendar & Menu module,but i need import all of css files,
![image](https://user-images.githubusercontent.com/7766085/62820547-3a5b5d00-bb98-11e9-87f6-6833454b97c8.png)
it will increase the volume of packaged，so how to  import css that component need?

**Comment by JacobSiegle** [comment]
I think you need to buy a premium theme to get access to the scss file or deminify the the CSS file and remove whatever you don't use to make your own version.

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.
