### ISSUE TITLE
pTable cell editing: onEditComplete not triggered when clicking other cells.

### ISSUE THREAD

**Issue by nbjohan** [primefaces/primeng#8049]
**I'm submitting a ...** (check one with "x")

```
[x] bug report = Search github for a similar issue or PR before submitting
[ ] feature request = Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request = Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

The issue that seems to have been solved in #6349 has reappeared in 8.0.3 (or earlier).
I copied the problem description and added a new stackblitz which shows the events as they are being fired.

**Plunkr Case (Bug Reports)**
 Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.
 
https://stackblitz.com/edit/github-rume1v
 
**Current behavior**
When using the event onEditComplete  the event isn't triggered by using the mouse to move to another field, when you press tab or esc the onEditCancel is triggered, when you press enter the onEditComplete is triggered, but there is no event when you change to another field through mouse.
 
 
**Expected behavior**
I think onEditComplete should be triggered when stopping the edit using the mouse to move to another field, 
 
**Minimal reproduction of the problem with instructions**
 
**What is the motivation / use case for changing the behavior?**
The problem here is the inconsistency, because if you need something to happen everytime you finish editing, you'll never gonna use onEdit events because it will not apply to every case (the user will have the possibility to skip part of the process)
 
**Please tell us about your environment:**
indifferent
 
* **Angular version:**
  8.0.3
* **PrimeNG version:**
  8.0.2
* **Browser:** all
* **Language:** all
* **Node (for AoT issues):** `node --version` =

**Comment by clearillusion** [comment]
I'm finding the same problem, which is really annoying as we need to rely on some 'hacks' to record the cell previously being edited.

**Comment by michaelferry** [comment]
Same issue here.

**Comment by daleclements** [comment]
Same issue and it's especially frustrating to work around. If I use (change) on the input, it isn't fired on ENTER. If I use (onEditComplete), it isn't fired on click away. If I use (change) AND (onEditComplete), then TAB fires both. Best solution I can see so far is listening to (change) and catching ENTER in (keydown)

**Comment by sanchis** [comment]
Same issue here. i make a pull request (#8391) with some changes to allow emit onComplete when change between cells.

**Comment by bobbydowling** [comment]
Possible workaround for now:

<ng-template pTemplate="body" let-item>
                    <tr>
                        <td pEditableColumn>
                            <p-cellEditor>
                                <ng-template pTemplate="input">
                                    <input (blur)="save({ data: item })"
                                           (keydown.tab)="save({ data: item })"
                                           (keydown.enter)="save({ data: item })">
                                </ng-template>

**Comment by bobbydowling** [comment]
Possible workaround for now:

``` HTML
<ng-template pTemplate="body" let-item>
     <tr>
          <td pEditableColumn>
               <p-cellEditor>
                    <ng-template pTemplate="input">
                                 <input (blur)="save({ data: item })"
                                 (keydown.tab)="save({ data: item })"
                                 (keydown.enter)="save({ data: item })">
</ng-template>
```
