### ISSUE TITLE
Open Submenu of TieredMenuModule using Keyboard arrows up and bottom

### ISSUE THREAD

**Issue by SRICHANDANCHINNAM** [primefaces/primeng#8052]
Hi Team,

I am using primeng  7.x version..  For menus, i am using p-tieredmenu module..

I want to open submenus of Tieredmenu using keyboard arrows up and bottom..

As i have seen in primeng official site, it seems there is no support for this even after latest version(8.x)..

Can you please check it as high priority..

Thanks

**Comment by JacobSiegle** [comment]
It works on prime react https://www.primefaces.org/primereact/#/tieredmenu.

There's an issue to bring the menu up to date with prime react, meaning this is a duplicate - https://github.com/primefaces/primeng/issues/7085.

**Comment by mertsincan** [comment]
Maybe, we can add an attribute named autoDisplay for this issue.
autoDisplay: boolean = true; //Defines whether the first level of submenus will be displayed on mouseover or not. When set to false, click event is required to display.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
