### ISSUE TITLE
Calendar view="month" does not highlight month unless manually clicked

### ISSUE THREAD

**Issue by PrestonJordan** [primefaces/primeng#8055]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => Search github for a similar issue or PR before submitting
```
**Current behavior**
When using the calendar with view="month", upon setting the value on the calendar using [(ngModel)], when the overlay is opened the selected month is not highlighted. The selection will not be highlighted until the month is manually selected.
![Screen Shot 2019-08-13 at 5 31 36 PM](https://user-images.githubusercontent.com/12367749/62981925-39246d00-bdf0-11e9-9b87-1f0be3ce8c8c.png)

**Expected behavior**
Upon programmatically setting the value on the calendar via ngModel when using view="month", the selection should automatically be highlighted without the need for a manual click.
![Screen Shot 2019-08-13 at 5 32 19 PM](https://user-images.githubusercontent.com/12367749/62981966-5d804980-bdf0-11e9-9880-bce8422008b7.png)

**Minimal reproduction of the problem with instructions**
1. html: <p-calendar [(ngModel)]="myDate" view="month"></p-calendar>
2. ts: myDate = new Date()
3. Load application and open browser
4. Calendar field should show the date in the input field
5. Click the input field to show overlay
6. The overlay should appear, but the date displayed in the input field is not highlighted in the overlay

**Please tell us about your environment:**
PrimeNG master branch

**Comment by JacobSiegle** [comment]
+1 - works in 8.0.1 but does not in 8.0.2, https://stackblitz.com/edit/github-l74jvz

**Comment by ridy01-backup** [comment]
Hey, this does not seem to work anymore with PrimeNG 15.0.1, it worked with PrimeNG Ver. 12. 

So if you select the date when the calendar selectionMode is set to "multiple" or "range" and view="month", the selected date won't show up (it does not become blue). I replicated it here: https://stackblitz.com/edit/primeng-calendar-demo-ub5muf?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts. 

thank you in advance.

**Comment by mcrtricolor** [comment]
Having the same problem, doesn't work on primeng 15.1.1

**Comment by Csukadatasquare** [comment]
Fixed it for me by overriding the function like in the commit here
https://github.com/JacobSiegle/primeng/commit/a539de4da41a49883f99c6f31bf56a3840c61bec
I did it with a directive like in this guide here
https://medium.com/angular-in-depth/changing-the-behavior-of-a-3rd-party-angular-component-91f84fb9af28

Annoying that every calendar component then needs this directive -.-
If someone can tell me a cleaner way i would appreciate it :)

**Comment by marticrespi** [comment]
Can anyone say exactly if this issue has been resolved? In which version? @mertsincan
