### ISSUE TITLE
Feat(ng-packagr): use ng-packagr to build library

### ISSUE THREAD

**Issue by leo6104** [primefaces/primeng#8057]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

primeng use gulp & ts compile for angular library build. But Angular recommend ng-packagr as library build system. 

**Expected behavior**

Please change primeng build system to ng-packagr build. It will make primeng compatible with Angular Ivy compile.

**Comment by cagataycivici** [comment]
PrimeNG 9 uses ng-packagr.
