### ISSUE TITLE
[Request] Add checkbox column to TreeTable component

### ISSUE THREAD

**Issue by janjp** [primefaces/primeng#806]
Hi,
it would be very helpful to add selection funtionality using checkbox for TreeTable,
as it is implemented for PrimeFaces TreeTable: http://www.primefaces.org/showcase/ui/data/treetable/selection.xhtml

Thanks in advance!

Jan

**Comment by janjp** [comment]
Also possible change of icons would be really nice,
because right now it is not possible:

expandedIcon 	string 	null 	Icon to use in expanded state. Not used by TreeTable.
collapsedIcon 	string 	null 	Icon to use in collapsed state. Not used by TreeTable.

Thanks!

Jan

**Comment by vishal3007** [comment]
I am also looking for this feature..
Any plan to release it soon?

**Comment by jisqaqov** [comment]
I also need these features.

**Comment by vijosoco** [comment]
Having the ability to add custom icons would be very helpful.

**Comment by bshectman-crestron** [comment]
Any update on plans to add multi-selection using checkboxes to TreeTable in PrimeNG?

**Comment by cagataycivici** [comment]
https://www.primefaces.org/primeng/#/treetable
