### ISSUE TITLE
rowHover not working - .ui-selectable-row 

### ISSUE THREAD

**Issue by capesean** [primefaces/primeng#8064]
Adding the `.ui-selectable-row` to this row:

https://github.com/primefaces/primeng/blob/1c6e7b85b74277b3d1aa3ccf0c35f4b9c6477587/src/assets/components/themes/nova-light/theme.css#L1883

Means that a `rowHover="true"` table will not show the highlight on the hovered row as that class is not necessarily present.

**Comment by capesean** [comment]
This was changed in https://github.com/primefaces/primeng/issues/6751

This might be by design? If so, might be worth updating your documentation to say you need the pSelectableRow directive.

**Comment by cagataycivici** [comment]
Due to a recent change, ui-selectable-row needs to be added to the tr element to make it function.  Documentation is updated.

```xml
<p-table [value]="cars" [rowHover]="true">
        <ng-template pTemplate="header">
            <tr>
                <th>Vin</th>
                <th>Year</th>
                <th>Brand</th>
                <th>Color</th>
            </tr>
        </ng-template>
        <ng-template pTemplate="body" let-car>
            <tr class="ui-selectable-row">
                <td>{{car.vin}}</td>
                <td>{{car.year}}</td>
                <td>{{car.brand}}</td>
                <td>{{car.color}}</td>
            </tr>
        </ng-template>
    </p-table>
```

**Comment by Wurthma** [comment]
PrimeNG needs to fix the documentation that says the class to work would be "p-selectable-row" 👀
