### ISSUE TITLE
change <p-spinner> type does not work

### ISSUE THREAD

**Issue by leonetosoft** [primefaces/primeng#8066]
My Code: 
```
<p-spinner [formatInput]="true" type="number" formControlName="id" [min]="0" [step]="1"></p-spinner>
```
It does not change the input type ... see:

![image](https://user-images.githubusercontent.com/3596786/63233283-61033e80-c1fd-11e9-9638-9e42d8be82c0.png)

The documentation says that you must change the "type" element of the input:

![image](https://user-images.githubusercontent.com/3596786/63233306-82fcc100-c1fd-11e9-86d1-3344796834b2.png)

Angular: 8.0.0
Primeng: 8.0.0

**Comment by AliceYangqian** [comment]
![image](https://user-images.githubusercontent.com/23236491/63248889-e426a200-c29a-11e9-9a53-5b43f4bed655.png)
The documentation needs update.

**Comment by leonetosoft** [comment]
@AliceYangqian ok, tanks!

**Comment by leonetosoft** [comment]
@AliceYangqian ok, tanks!
