### ISSUE TITLE
Add unique attribute to Autocomplete

### ISSUE THREAD

**Issue by StevenSwitten** [primefaces/primeng#8067]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When using the Autocomplete component with [multiple]="true", when the user submits a value for the second time, it is not added to the list of values.

**Expected behavior**
It would be useful to have an Input named allowDuplicate, similar to the Chips component

**Comment by mertsincan** [comment]
Please use [unique]="false" with 8.0.3 version.

**Comment by StevenSwitten** [comment]
Thank you!
