### ISSUE TITLE
Slide Menu

### ISSUE THREAD

**Issue by DarienF** [primefaces/primeng#8069]
[*] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

If component is located in `<div>` block which has `display: none` style:

```
<div style="display: none;">
<p-slideMenu [model]="items" [viewportHeight]="250"></p-slideMenu>
</div> 
```
code (inside lib) working not properly:
```
updateViewPort() {
        this.slideMenuContentViewChild.nativeElement.style.height = this.viewportHeight - DomHandler.getHiddenElementOuterHeight(this.backwardViewChild.nativeElement) + 'px';
    }
```
This specific function return 0px for backward:
`DomHandler.getHiddenElementOuterHeight(this.backwardViewChild.nativeElement)`

As result scroll in main content block working not properly when main `div` which contain slide menu become visible (dislpay: block).

**Comment by JacobSiegle** [comment]
Instead of making the slideMenu display none can't you just use an *ngIf instead or does something prevent you from doing this? This isn't only with the p-slideMenu, other components can have the same issue.

**Comment by cagataycivici** [comment]
Use *ngIf instead please.
