### ISSUE TITLE
Chart.js and moment.js in vendor bundle

### ISSUE THREAD

**Issue by miliardopiscrat** [primefaces/primeng#8070]
[* ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

according to documentation: https://www.primefaces.org/primeng/#/chart

chart.js is included in script option as external script file but also appears in vendor file with peer dependency moment.js 

primeng before 8.0.0 does not import chart.js and it's peer dependencies.

problem checked on:
primeng 8.0.0
primeng 8.0.2

**Comment by cagataycivici** [comment]
Avoid using primeng/primeng, otherwise the whole lib will be bundled, use primeng/chart.
