### ISSUE TITLE
The FocusTrap directive throws a JS exception on browsers

### ISSUE THREAD

**Issue by meeCnu** [primefaces/primeng#8075]
press tab on focustrap enabled child controls getting following error in Firefox browser 

columnNumber: 215
​
fileName: "https://www.primefaces.org/primeng/22-es2015.b3f70586312af077c880.js"
​
lineNumber: 1
​
message: "event is not defined"
​
stack: "onkeydown@https://www.primefaces.org/primeng/22-es2015.b3f70586312af077c880.js:1:215\nk/<@https://www.primefaces.org/primeng/22-es2015.b3f70586312af077c880.js:1:1605\nhandleEvent@https://www.primefaces.org/primeng/main-es2015.e59da9ecf425701e6c44.js:1:101503\nhandleEvent@https://www.primefaces.org/primeng/main-es2015.e59da9ecf425701e6c44.js:1:122029\njr@https://www.primefaces.org/primeng/main-es2015.e59da9ecf425701e6c44.js:1:57523\nEo/<@https://www.primefaces.org/primeng/main-es2015.e59da9ecf425701e6c44.js:1:94890\nj/<@https://www.primefaces.org/primeng/main-es2015.e59da9ecf425701e6c44.js:1:211691\ninvokeTask@https://www.primefaces.org/primeng/polyfills-es2015.295561ab085ffc739b55.js:1:53671\nonInvokeTask@https://www.primefaces.org/primeng/main-es2015.e59da9ecf425701e6c44.js:1:79561\ninvokeTask@https://www.primefaces.org/primeng/polyfills-es2015.295561ab085ffc739b55.js:1:53584\nrunTask@https://www.primefaces.org/primeng/polyfills-es2015.295561ab085ffc739b55.js:1:49162\ninvokeTask@https://www.primefaces.org/primeng/polyfills-es2015.295561ab085ffc739b55.js:1:54676\nv@https://www.primefaces.org/primeng/polyfills-es2015.295561ab085ffc739b55.js:1:66658\ny@https://www.primefaces.org/primeng/polyfills-es2015.295561ab085ffc739b55.js:1:66902\n"

![image](https://user-images.githubusercontent.com/1768749/63496868-46241900-c4e0-11e9-8a9c-dae7291a9d72.png)

**Comment by JacobSiegle** [comment]
I don't see the same error. Can you specify which version of firefox you're using?

**Comment by meeCnu** [comment]
We are facing issue with 
FireFox : 68.0.2 (32-bit) 
OS: Windows 10

**Comment by mertsincan** [comment]
Fixed now!

**Comment by meeCnu** [comment]
Thanks for the Fix @mertsincan
