### ISSUE TITLE
sub menu of p-contextMenu in p-table go off screen when right click on the bottom of screen

### ISSUE THREAD

**Issue by connorlufei** [primefaces/primeng#8077]
**I'm submitting a bug report  (check one with "x")

**Plunkr Case (Bug Reports)**
```
<p-table [contextMenu]="cm" [value]="tableData">
  ...
</p-table>
<p-contextMenu #cm [model]="menuItems" [global]="true"></p-contextMenu>
```
demo url:
https://rlmiyral.github.stackblitz.io

**Current behavior**
For a table(rows go beyond screen) with 2-level context menu attached to it, right click on the center of table and hover on the level-1 menu to show the sub menu, and then right click on the table row in bottom of screen, the sub menu position shows in the bottom and go off screen(instead of showing on top), part of the sub menu has transparent background. Then it stays that way no matter where you right click unless refreshing.

**Expected behavior**
The context sub menu always shows on right position and is not broken in style(transparent background).

**Minimal reproduction of the problem with instructions**
1. right click on center of table and move mouse over menu(the sub menu should show in the bottom)
2. right click on the row in the bottom and hover over menu(the sub menu show in bottom and go off screen instead of in the top where there is room for display)
3. click anywhere on the table, the sub menu behaves the same way as step 2.

**What is the motivation / use case for changing the behavior?**
bug

**Please tell us about your environment:**

* **Angular version:** 7.X

* **PrimeNG version:** 7.X

* **Browser:** all
 
* **Language:** all

* **Node (for AoT issues):** `node --version` =   10.16.2

**Comment by apolgesek** [comment]
Having exactly the same issue. #8813 is the same fix, though it's more explicit than this solution. Is it going to be patched any time soon?

**Comment by cagataycivici** [comment]
Merged via PR
