### ISSUE TITLE
Unconsistent resetPage API for sorting/filtering on table component

### ISSUE THREAD

**Issue by npoirey** [primefaces/primeng#8079]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
The correction of issue #7795 in 8.0.2 force the return to offset 0 when changing filters and there is no equivalent of `resetPageOnSort` for filters.
Before 8.0.2, we could go around this limitation by setting table.restoringFilter = true before changing the input.

**Expected behavior**
Table should offer the same capabilities regarding resetPage for sorting and filtering

**What is the motivation / use case for changing the behavior?**
I expect to stay on the same page when adding a filter that has no effects / removing a filter.
I also want be able to detect that the current page has no elements and choose to either go back to first page or last available page.

* **PrimeNG version:** 8.0.2

* **Browser:** all
 
* **Language:** typescript

**Comment by szh** [comment]
This is a critical issue for me. I am manually restoring table state and it's not possible to restore the page number and the filters, because the page is reset after the filter is set.

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
