### ISSUE TITLE
RowGrouping support for VirtualScroll

### ISSUE THREAD

**Issue by Martin-Hogge** [primefaces/primeng#8080]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

>>> I tried replicating the issue with the provided template but their is an additional issue when using the template: rows aren't expanded by default (which they are when testing locally). So I replicated using another Stackblitz: https://stackblitz.com/edit/angular6-primeng-8mtvwc **BUT** if you really need your template, here is the link of what I've done using that template: https://stackblitz.com/github/rlmiyral

**Current behavior**
When scrolling the table: (1) the table becomes white for a moment and (2) the lazy loading display previous rows.

**Expected behavior**
Lazy loading display a loading indicator and when finished, display the next rows.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/angular6-primeng-8mtvwc
Scroll down the table to see the bug in action.

**What is the motivation / use case for changing the behavior?**
Getting grouped rows and virtual scroll working together.

**Please tell us about your environment:**
OS: Windows 10 (64 bits)
IDE: VSCode

* **Browser:** Chrome & Firefox
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
