### ISSUE TITLE
Autocomplete does not work using Firefox Mobile browser

### ISSUE THREAD

**Issue by jacorre** [primefaces/primeng#8082]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
[https://github-qpyv5t.stackblitz.io](https://github-qpyv5t.stackblitz.io)

**Current behavior**
When using the Firefox browser on a mobile device (in this case Android), no autocomplete values appear while typing. 

**Expected behavior**
I would expect the matched values to appear while typing.

**Minimal reproduction of the problem with instructions**
Visit [https://github-qpyv5t.stackblitz.io](https://github-qpyv5t.stackblitz.io) on your mobile device using the Firefox browser. Begin typing in the autocomplete field and notice no matches appear. Entries available in example are: one, two, three, four, five.

You can also reproduce this issue using the [example on the PrimeNG website](https://www.primefaces.org/primeng-7.1.3/#/autocomplete).

* **Angular version:** 
7.2.10

* **PrimeNG version:** 
7.1.3

* **Browser:**
Firefox Mobile Browser v68.0.2

* **Node (for AoT issues):** 
8.14.10

**Comment by JacobSiegle** [comment]
Testing it a bit the autocomplete does work if you click on, click off, then click on it again. The first click on load doesn't show the auto complete box.

**Comment by jacorre** [comment]
I tried clicking in the field, outside of it, then in the field again and typing, but still don't see anything happening?

I haven't had any success using the [example on the PrimeNG website](https://www.primefaces.org/primeng-7.1.3/#/autocomplete) either.

**Comment by JacobSiegle** [comment]
Sorry I updated my comment you have to type on the first click also.
