### ISSUE TITLE
Autocomplete with keeping invalid value with foceSelection active

### ISSUE THREAD

**Issue by vinicius-lds** [primefaces/primeng#8084]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
The component is keeping an invalid value even with the property foceSelection set to true.

**Expected behavior**
This value should be removed.

**Minimal reproduction of the problem with instructions**
To reproduce this you'll need to follow a few steps:
1st: select any option of the suggestions list;
2nd: without losing focus of the component override the selected value with anything;
3rd: while you're overriding the value, do something to lose focus of the component, it has to be done really fast to work;
If you do that it should keep the value in the input field.

https://cdn1.imggmi.com/uploads/2019/8/23/74a350bd286dcb93826298d96ffb47e2-full.png
https://cdn1.imggmi.com/uploads/2019/8/23/52ab78e57010be6a7e5fc3da9639922d-full.png
https://cdn1.imggmi.com/uploads/2019/8/23/4f31eba609e2b8a63e911a0b605beb25-full.png
https://cdn1.imggmi.com/uploads/2019/8/23/1f4ab48f7e65c8aa7a14c77325f076f7-full.png

**What is the motivation / use case for changing the behavior?**
This is a bug that can result in some unhandled exception being caught in the client side of the application.

**Please tell us about your environment:**
It was done using windows, visual studio code and npm.

* **Angular version:** 5.X
 angular 7.2.4

* **PrimeNG version:** 5.X
primeng 7.1.2.

* **Browser:** Chrome.
 
* **Language:** TypeScript 3.2.4

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
