### ISSUE TITLE
non editable Dropdown should be invalid if the model value is not one of the options

### ISSUE THREAD

**Issue by DaltonNotetech** [primefaces/primeng#8086]
**I'm submitting a bug report**

**Current behavior**

The form is valid when model value is not one of the options specified 

**Expected behavior**

The form should be invalid when model value is not one of the options specified 

**Minimal reproduction of the problem with instructions**
The below form will be valid even though the model value is not one of the options specified 
```
<form #form="ngForm">
    <p-dropdown name="dd" [(ngModel)]="modelWithValueNotInOptions" [options]="options" [autoDisplayFirst]="false"></p-dropdown>
</form>
```

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 7.X

* **PrimeNG version:** 7.X

* **Browser:** all

**Comment by cagataycivici** [comment]
AutoComplete with dropdown mode and forceSelection should be a better for your case.
