### ISSUE TITLE
FileUpload control no longer accessible via ViewChild in primeng 8.0.2

### ISSUE THREAD

**Issue by AlejandroFlorin** [primefaces/primeng#8088]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

I tried but couldn't get the plunkr template to use the FileUpload control.

**Current behavior**
ViewChild doesn't provide access to the FileUpload control

**Expected behavior**
You should be able to use ViewChild to call methods of the FileUpload control

**Minimal reproduction of the problem with instructions**
```
<p-fileUpload #fileUploadControl
	name="documentFile[]"
	[url]="uploadUrl"></p-fileUpload>

import { FileUpload } from 'primeng/fileupload'

@ViewChild('fileUploadControl', { static: true }) fileUploadControl: FileUpload;
```

With the above, fileUploadControl is always undefined, even well after the page loads (i'm trying to access it via another control's event handler).

I rolled both angular and primeng back to 7 and it all works again. I didn't see any ViewChild issues with any other controls, just FileUpload.

**What is the motivation / use case for changing the behavior?**
Need to call the upload() method of the FileUpload control

**Please tell us about your environment:**
Windows 10,
Visual Studio 2019

* **Angular version:** 8.2.2

* **PrimeNG version:** 8.0.2

* **Browser:** [all]

 
* **Language:** [TypeScript 3.2.4]

* **Node (for AoT issues):** `node --version` =

**Comment by yigitfindikli** [comment]
Hi, @AlejandroFlorin 
I couldn't replicate it, can you provide a stackblitz case using with;

https://stackblitz.com/github/primefaces/primeng-issue-template

**Comment by AlejandroFlorin** [comment]
This was an angular issue after upgrading to 8. This solved it for me:

https://stackoverflow.com/a/57508471/3547170
