### ISSUE TITLE
Carousel items comes in two rows

### ISSUE THREAD

**Issue by mubashshir-uneecops** [primefaces/primeng#8090]
I have 200 items in my carousel and visibility is 4 but it shows 8 item. 4 item in one row and the other 4 are in bottom.

`<p-carousel headerText="Wishes" [value]="wishlist" numVisible="4">
    <ng-template let-wish pTemplate="item">
        <div class="ui-grid ui-grid-responsive">
           {{wish.employeeName}}
           <div>{{wish.wishesType}}</div>
        </div> 
    </ng-template>
</p-carousel>`

![image](https://user-images.githubusercontent.com/50190870/63743591-5bbb8900-c8ba-11e9-87f9-fe995a5e7283.png)

**Comment by mubashshir-uneecops** [comment]
Still the same problem occurs. And on small screen it reduces to 3 item.
Please refer to below stackblitz

https://stackblitz.com/edit/angular-mzr7u7

**Comment by anjelchen** [comment]
the problem is in the carousel.css of primeng. there is a fixed width of 32000px for the .ui-carousel-items.
but you have 181 items and at some point their overall width exceeds those 32000px and then it wraps to 2nd row.

**Comment by mertsincan** [comment]
Hi,

We are working on the new carousel component now. I added it to PrimeReact. Please examine; https://github.com/primefaces/primereact/issues/1030
New Carousel'll not use width for items. Full flexbox ;)

Coming soon :D
Best Regards,
