### ISSUE TITLE
New feature: filter tables on blank values

### ISSUE THREAD

**Issue by AlainD-** [primefaces/primeng#8099]
**I'm submitting a ...**
```
[ ] bug report
[x] feature request
[ ] support request
```

**Current behavior**
In a table, when activating the filtering on columns (with the usage of a <p-multiselect> for instance) it is not possible to filter on blank values.
This is a serious limitation for our project because some rows has empty values on certain columns, and it is currently not possible to filter on those empty values (`null` values).

**Expected behavior**
Allow table->filter to filter on blank values. 
**Add a new option to bypass the test `isFilterBlank(value)`**

Current implementation to be improved:
```
filter(value, field, matchMode) {
       ...
        if (!this.isFilterBlank(value)) {
            this.filters[field] = { value: value, matchMode: matchMode };
        } else if (this.filters[field]) {
            delete this.filters[field];
        }
        ...
    }
```

**Minimal reproduction of the problem with instructions**
(not provided)

**What is the motivation / use case for changing the behavior?**

- Be able to filter all the possibilities of the data in the table

**Please tell us about your environment:**

* **Angular version:** 8.x

* **PrimeNG version:** 8.0.2

* **Browser:** all

**Comment by stephanie-dm** [comment]
This is NOT a duplicate of #6808 : 6808 is already fixed in 10.0.3, but that fix is specific for the "in" filtering, while the current issue is about allowing filtering on "null" by bypassing the `isFilterBlank` check mentioned in the code above.

**Comment by fmaillard35** [comment]
Have you any news about this ?
We have the same problem

Thanks

**Comment by juulian98** [comment]
Any news on this?

**Comment by hschindler** [comment]
Why this feature is not implemented yet? It is so important to handle database data! We need this so urgent

**Comment by literakl** [comment]
I need this too. I have  many records with a value but I am seeking for records that are still blank.
