### ISSUE TITLE
width for calendar component

### ISSUE THREAD

**Issue by glivolsi** [primefaces/primeng#810]
Please add the witdh property to inputfield of calendar control to correctly size it forms

**Comment by bella92** [comment]
Yeah, I have problems setting it's width, too :(

**Comment by nicovanbelle** [comment]
+1. I have a solution for global component width settings, but that is not desired.

**Comment by greggalbreath** [comment]
+1

**Comment by cagataycivici** [comment]
inputStyle and inputStyleClass can help;

```
<p-calendar [inputStyle]="{'width':'100px'"} ...
```

**Comment by Ganeshpoloju** [comment]
<p-calendar [inputStyle]="{'width':'100px'}"

**Comment by villanuevacarlos14** [comment]
<p-calendar [style]="{'width':'95%'}" [inputStyle]="{'width':'95%'}"

**Comment by watkinst** [comment]
Using PrimeNG version 5.2.6, I ended up needing only:

<p-calendar [inputStyle]="{'width': '100%', 'min-width': '100%'}"

**Comment by AnkitBajpaii** [comment]
Using [inputStyle]="{'width':'100px'}" on <p-calendar> worked for me.

**Comment by kraravind167** [comment]
input style , style class is not working for me

**Comment by kraravind167** [comment]
at some threshold size it's forcestopping to reduce

**Comment by vijayragaw** [comment]
is thare any possible to change p-calender size

**Comment by vijayragaw** [comment]
i want to change calender not input field

**Comment by nugrohotanjo** [comment]
how to change calendar size? it's to big..

**Comment by alwinaugustin** [comment]
any solutions ?

**Comment by dhuebes** [comment]
Probably you are using appendTo="body", unless it was my case.
It's change the context of monthpicker. To fix, I used a div in appendTo.

**Comment by velykov** [comment]
No solution?

**Comment by had99** [comment]
Anyone has a solution yet?

**Comment by Marwenwill** [comment]
One workaround is to set **display** to **initial** on .p-datepicker td>span, like this:
```
.p-datepicker td>span {
    display: initial;
  }
```

Then you change the font-size as you which so it changes the width.

**Comment by selcukaltas** [comment]
Hi guys i used this CSS 

  .p-datepicker table td {
    padding: 0.1rem !important;
  }
  
  hope this helps

**Comment by ilmoralito** [comment]
A workaround its working for me

```
:host ::ng-deep {
  .layout-calendar-wrapper > div:first-of-type {
    width: 100%;
  }

  .p-calendar {
    width: 100%;
  }
}
```

**Comment by ahmadalmaaz** [comment]
This worked for me 

`
::ng-deep .p-datepicker td span {
    width: 2.2rem;
    height: 2.2rem;    
}

::ng-deep .p-datepicker table td{
    margin: 0 !important;
    padding: 0 !important;
}
`
