### ISSUE TITLE
Calendar overlay doesn't disappear in OnPush components.

### ISSUE THREAD

**Issue by Hapcy** [primefaces/primeng#8102]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/github-zpt3km

**Current behavior**
Calendar overlay only disappears in ChangeDetectionStrategy.OnPush components, when another change detection runs because the markForCheck on calendar.ts:2077 is outside of zone and doesn't trigger change detection.

**Expected behavior**
Calendar should work like in ChangeDetectionStrategy.Default components.

**Minimal reproduction of the problem with instructions**
The provided stackblitz shows a calendar in a default and an onpush component side by side.

* **Angular version:** >=8
* **PrimeNG version:** 8.0.2

**Comment by yigitfindikli** [comment]
Hi,
Thanks for contributing.
Best Regards.

**Comment by sebastienv** [comment]
Hi @yigitfindikli,
Shouldn't this same fix also be done on OverlayPanel ?
We currently facing a similar issue but with OverlayPanel and adding making the same fix make it works correctly.

**Comment by charlatan154** [comment]
I have the same issue with OverlayPanel.
