### ISSUE TITLE
Improve treenode CSS

### ISSUE THREAD

**Issue by atillabaspinar** [primefaces/primeng#8106]
**I'm submitting a 
[x ] feature request 

**Current behavior**
In p-tree 'toggler' and 'label' are <span> elements. The parent is a div with class .ui-treenode-content. In this setup label cannot be changed easily.

My recommendation is to have this:

```
.ui-treenode-content {
    display: flex;  
    align-items: center;  
    .ui-treenode-label {
        flex-grow: 1;
    }
}
```

In this way, the label of a tree node will have all remaining width. 

**What is the motivation / use case for changing the behavior?**
Better flexibility

**Please tell us about your environment:**
Windows 10

* **Angular version:** 8.2.3

* **PrimeNG version:** 8.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

* **Node (for AoT issues):** `node --version` =   
Node 10+

**Comment by cagataycivici** [comment]
I'll review this with our flex expert @mertsincan

**Comment by cagataycivici** [comment]
As label is inline span, size will grow anyway, so no need for flex-grow.
