### ISSUE TITLE
PrimeNG Dropdown resetFilter method not clearing if dropdown is closed

### ISSUE THREAD

**Issue by dileepyelleti** [primefaces/primeng#8107]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-dropdownresetfilter

**Current behavior**
PrimeNG Dropdown resetFilter method is not working if dropdown is in closed state

**Expected behavior**
PrimeNG Dropdown resetFilter method should clear even if dropdown is closed

**Minimal reproduction of the problem with instructions**
Click on dropdown and filter with some text
Click outside so that dropdown closes
Click clear button
Open dropdown. Filter text will be there.

**What is the motivation / use case for changing the behavior?**
Maintaining filter value until some external event.

**Please tell us about your environment:**
IOS, VS code, Angular cli

* **Angular version:** 5.X
8.0.3

* **PrimeNG version:** 5.X
8.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

* **Node (for AoT issues):** `node --version` =

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
