### ISSUE TITLE
Upgrade gulp to v4 (gulp 3 is no longer supported in node 12)

### ISSUE THREAD

**Issue by huineng** [primefaces/primeng#8112]
when building components on node 12 './node_modules/.bin/gulp build-assets'

you get this error https://github.com/gulpjs/gulp/issues/2324

gulp 3 is no longer support from node 12.

Can we move primeng gulp to v4 ?

**Comment by cagataycivici** [comment]
We haven't decided to upgrade yet, we'll do it on our side when decided, thank you.
