### ISSUE TITLE
InputTextArea not shrink properly when auto resized

### ISSUE THREAD

**Issue by connorlufei** [primefaces/primeng#8113]
Suppose I resize text area to 5 rows, then I press backspace to move cursor to 4th row, the height of text area is not the height of 4 rows(more than 4 rows and less than 5 rows)

**Comment by JacobSiegle** [comment]
Duplicate of https://github.com/primefaces/primeng/issues/7778 which is fixed in https://github.com/primefaces/primeng/pull/7785. Please close or let me know if this is different.

**Comment by connorlufei** [comment]
@JacobSiegle  I'll close it. By the way, is there a way to limit the max rows to auto resize?

**Comment by yigitfindikli** [comment]
duplicate of #7778

**Comment by JacobSiegle** [comment]
@connorlufei I think that would be a new feature request. I would open a new issue.
