### ISSUE TITLE
p-spinner does not clear when [(ngModel)] is assign to null or undefined

### ISSUE THREAD

**Issue by FabienDehopre** [primefaces/primeng#8114]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Stackblitz Case (Bug Reports)**
https://stackblitz.com/edit/angular-ejtl12

**Current behavior**
When the `ngModel` (or the `FormControl`) value is set to `null` or `undefined`, the formatted value is not cleared in the spinner input text control.

**Expected behavior**
The spinner input text control should be clear when the `ngModel` (or the `FormControl`) value is set to `null` or `undefined`.

**Minimal reproduction of the problem with instructions**
See the above Stackblitz url

**Please tell us about your environment:**
Windows 10

* **Angular version:** 
```
Angular CLI: 8.1.3
Node: 10.16.0
OS: win32 x64
Angular: 8.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.801.3
@angular-devkit/build-angular      0.801.3
@angular-devkit/build-ng-packagr   0.801.3
@angular-devkit/build-optimizer    0.801.3
@angular-devkit/build-webpack      0.801.3
@angular-devkit/core               8.1.3
@angular-devkit/schematics         8.1.3
@angular/cdk                       8.0.2
@ngtools/webpack                   8.1.3
@schematics/angular                8.1.3
@schematics/update                 0.801.3
ng-packagr                         5.5.0
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.35.2
```

* **PrimeNG version:** 8.0.2

* **Browser:** all
 
* **Language:** TypeScript

* **Node (for AoT issues):** `node --version` =   10.16.0

**Comment by JacobSiegle** [comment]
One workaround is to go against the type and set the value to an empty string. It needs to be patched to work with null and undef.
