### ISSUE TITLE
Reorderable Tabs in TabView

### ISSUE THREAD

**Issue by davisb10** [primefaces/primeng#8117]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Tabs can not be moved around within a given TabView component

**Expected behavior**
Ability to move / reorder components by clicking on the header and dragging left or right

**Comment by davisb10** [comment]
@yigitfindikli Is this something that is open to a pull request, or would it need to be done in-house?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by dannycg1996** [comment]
Hi, I believe that this issue is still present - there is no way of reordering the tabs within a TabView via drag and drop. 
Please could this issue be reopened?
