### ISSUE TITLE
Collision detection for tooltip positioning to keep inside viewport

### ISSUE THREAD

**Issue by mdonato7** [primefaces/primeng#812]
To reproduce place an element near the left or right edge of the screen and set the `pTooltip` attribute to a long text value with `tooltipPosition` = "top" or "bottom". The tooltip flows off the edge of the screen.

**Comment by cagataycivici** [comment]
Yes, we should add collision detection.

**Comment by cagataycivici** [comment]
Reopening for code review.

**Comment by cagataycivici** [comment]
Complete rewrite.
