### ISSUE TITLE
Documentation Cleanup for component properties

### ISSUE THREAD

**Issue by davisb10** [primefaces/primeng#8120]
This is not really a bug nor a feature request.

**I'm submitting a ...**  (check one with "x")
```
[?] bug report => Search github for a similar issue or PR before submitting
[?] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When looking at the Properties Table for a given component, the values are not in any particular order, making it difficult to locate certain items to view their type / default / description. Also there is nothing denoting what are the 'minimum required' properties. 
Example: 
- Table Component -> 'values'
- Dropdown Component -> 'options'

**Expected behavior**
Properties should be in some type of order (possibly alphabetically).
There should be something denoting what are the 'minimum' requirements for a given component.

I will gladly work on this and create a PR if you view this as a good idea.

**Comment by cagataycivici** [comment]
Please feel free to create PRs.

**Comment by chao813** [comment]
@davisb10 Did you ever end up working on this? I had the exact same thought when looking at the Properties Table, ideally it should be in alphabetical order.
