### ISSUE TITLE
Toast blocks protractor

### ISSUE THREAD

**Issue by yelhouti** [primefaces/primeng#8122]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

Toast uses setTimeout blocking protractor test framework

**Expected behavior**

Toasts should not block protractor.

This bug https://github.com/primefaces/primeng/issues/4681 had been fixed for growl using this PR: https://github.com/primefaces/primeng/pull/5636/commits/26506f95796c1d7237ab33b05654e81dbe571fa0

And could be fixed the exact same way

**Comment by cagataycivici** [comment]
Review for 9.0.4
