### ISSUE TITLE
[Feature Request] TurboTable - add Vertical Headings and both Horizontal and Vertical Headings option

### ISSUE THREAD

**Issue by grozdanova** [primefaces/primeng#8128]
**I'm submitting a ...**  (check one with "x")
```
[ x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
```

**Comment by cagataycivici** [comment]
Issue is not clear.

**Comment by grozdanova** [comment]
Hi,
For Vertical Headings -example:
https://www.w3schools.com/html/tryit.asp?filename=tryhtml_table_headers

and both Horizontal and Vertical Headings
https://www.w3.org/WAI/tutorials/tables/multi-level/

         header1 header2 header3 
header1    1        1      1
header2    2        2      2 
header3    3        3      3 
Thanks!
