### ISSUE TITLE
Adding Templates and styles to Column dynamically in data table

### ISSUE THREAD

**Issue by braino15** [primefaces/primeng#813]
Business case: I have column collection which keeps on changing for users. and some of the columns have custom templates associated with. 

While trying to define the datatable in html like

<p-dataTable [value]="rows" [(selection)]="selectedVehicles" expandableRows="true" [totalRecords]="totalRecords"
[lazy]="true" (onLazyLoad)="loadDataLazy($event)" (onRowSelect)="onRowSelect($event)" (onRowUnselect)="onRowUnselect($event)"
[rows]="100" [paginator]="true" [pageLinks]="3" [rowsPerPageOptions]="[100,200, 500]" 
scrollable="true" scrollHeight="300px"
[responsive]="true">

<p-column *ngFor="let col of columnDefs" [field]="col.fieldName" [header]="col.key" [filter] = "true">
<template *ngIf="col.hasTemplate" let-col let-row="rowData">

<div style="color:red;">{{row[col.field]}}</div>

</template>

</p-column></p-dataTable>

it doesn't work. hasTemplate is boolean property on the columnDefs collection which has structure like 
[
{key: "interior color", fieldName: "intColor.colorDisplayName", style: " ", hasTemplate: false, template:""},
{key: "vin", fieldName: "vin", style: "", hasTemplate: true, template:"<div class='ui-grid-cell-contents grid-align-text-center'><a ui-sref='app.vehicledetail({vin: row.entity.vin})'>{{row.entity.vin}}</a></div>"}].

The data table loads blank without any errors, with or without "template" property being used.
1. How to add templates dynamically based on model property?
2. how to set style with attributes like min-width and other classes, dynamically like form model.className property?

Any help?

Thanks.

**Comment by Goldflow** [comment]
personally i created ColumnData objects, (which contain fieldname & Header etc.)
than i can possibly pass through style which should be an object with keys & values e.g.

              [style]="{'width':'38px'}" but you could replace that by an object that is: {{'width':object.width}}

**Comment by bpbhat77** [comment]
+1

**Comment by Nattujessy** [comment]
+1

**Comment by cagataycivici** [comment]
Please use forum for "how-to" like cases.

**Comment by bpbhat77** [comment]
+1

**Comment by rana3012** [comment]
+1
