### ISSUE TITLE
Error message when building for tests with puppeteer:  Can't resolve 'chart.js' 

### ISSUE THREAD

**Issue by theS3ns** [primefaces/primeng#8131]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
```
import { CheckboxModule } from 'primeng/checkbox';
import { TreeModule } from 'primeng/tree';
```

Testfile:

```
describe('..', () => {
  beforeEach(async(() => {
    TestBed.configureTestingModule({
      imports: [
        HttpClientTestingModule,
        CheckboxModule,
        TreeModule,
        FormsModule
      ],
      declarations: [ ... ]
    })
    .compileComponents();
  }));
});
```

`ng test` 

Module not found: Error: Can't resolve 'chart.js' in '....\node_modules\primeng\components\chart' resolve 'chart.js' in '...\node_modules\primeng\components\chart'

"dependencies": {
    "@angular/animations": "^8.2.5",
    "@angular/common": "^8.2.5",
    "@angular/compiler": "^8.2.5",
    "@angular/core": "^8.2.5",
    "@angular/forms": "^8.2.5",
    "@angular/platform-browser": "^8.2.5",
    "@angular/platform-browser-dynamic": "^8.2.5",
    "@angular/router": "^8.2.5",
    "primeicons": "^2.0.0",
    "primeng": "^8.0.3",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },

```
browsers: ['ChromiumHeadlessNoSandbox'], // local use Chrome ChromiumHeadlessNoSandbox
    customLaunchers: {
      ChromiumHeadlessNoSandbox: {
        base: 'ChromiumHeadless',
        flags: ['--no-sandbox']
      }
    },
```

The Project is totally new....

**Comment by miliardopiscrat** [comment]
This is related to that:
https://github.com/primefaces/primeng/issues/8070

**Comment by cagataycivici** [comment]
Please see my comment at https://github.com/primefaces/primeng/issues/8070
