### ISSUE TITLE
Component Number

### ISSUE THREAD

**Issue by ReginaldoPL** [primefaces/primeng#8134]
Sorry, my english is bad.
I Need a input with number from lay-out PT-BR (Brazil) equal 'R$ 10.000,00', but dont matter I do, the input accept 10.00,000.00,000.000,000. I Try use "input  type="text"", spinner and keyFilter, but 
both dont work appropriately.

Thanks

**Comment by cagataycivici** [comment]
Please use forum for questions and help requests.
