### ISSUE TITLE
frozenColumns and tableHeaderCheckbox

### ISSUE THREAD

**Issue by MassiveHiggsField** [primefaces/primeng#8135]
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ x ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://github-gvyvtp.stackblitz.io/
https://stackblitz.com/edit/github-gvyvtp

**Current behavior**

If i use freezeColumns and tableHeaderCheckbox together it gets some weird results.

**Expected behavior**

Checkbox column and freeze columns are frozen together and checkbox is only added once.

Any help appreciated, thanks in advance.

**Comment by MassiveHiggsField** [comment]
found it myself, see stackblitz. was just an css issue.

**Comment by MassiveHiggsField** [comment]
Okay, but still a small problem, is there a way to disable the second checkbox column?

**Comment by JacobSiegle** [comment]
You should be able to use the prop frozenbody to fix it.

**Comment by MassiveHiggsField** [comment]
Thanks that did the trick
