### ISSUE TITLE
Toast - allow to configure translation direction

### ISSUE THREAD

**Issue by Grauen** [primefaces/primeng#8136]
When a toast gets displayed, the translation direction is currently hardcoded, 
moving the toast upwards to the target position.

`animations: [
        trigger('messageState', [
            state('visible', style({
                transform: 'translateY(0)',
                opacity: 1
            })),
            transition('void => *', [
                style({transform: 'translateY(100%)', opacity: 0}),
                animate('{{showTransitionParams}}')
            ]),
            transition('* => void', [
                animate(('{{hideTransitionParams}}'), style({
                    height: 0,
                    opacity: 0,
                    transform: 'translateY(-100%)'
                }))
            ])
        ])
    ]
 `

It would be great if the toast animation could be edited, so toast messages could fade in from top to bottom.

**Comment by cagataycivici** [comment]
Added showTransformOptions and hideTransformOptions along with a demo that appears from left to right.
