### ISSUE TITLE
Datatable reorder via drag/drop does not work as indicated by guide arrows

### ISSUE THREAD

**Issue by ryanwawr** [primefaces/primeng#814]
The arrows that indicate where a datatable column will be dropped during a drag/drop are only correct half the time. The arrows point to the nearest divider between columns, as one would expect, but the dragged column is always inserted to the left of whichever column the pointer is over when the mouse button is released. Therefore, the column drop location will be different from the location indicated by the arrows anytime the mouse is released on the right half of a column. 

Screen capture below shows this happening on primeng demo site. Arrows indicate that Brand column will be dropped between Year and Vin, but it ends up to the left of Year. 

http://screencast.com/t/adbcur7Ws5

**Comment by wk198553** [comment]
I had similar problems, but displayed quite bad.

1. When I use style to adjust width, the guide arrows do not know and will point to wrong places. My p-column is as below:
<p-column *ngFor="let header of headers" [style]="{'width': reportsService.getWidth(header,stacked)}" field="{{header}}" header="{{header}}" sortable="custom" (sortFunction)="sortData($event)"></p-column>

2. Ignore problem 1, guide arrows are correct when I only have 4 columns, but have problems when I have more columns, say 10 columns, see attached screenshot, where I drag the 7th column "Gain" and move my mouse to the 3rd column, where guide arrows stays in the 5th column.
![primeng_datatable_reorder_issue](https://cloud.githubusercontent.com/assets/10444954/20725101/ac18c8ee-b6d5-11e6-809b-fd87c1f516f4.png)

**Comment by f-teixeira** [comment]
I'm having the same problem, it's doesn't matter if the guide arrows are shown to the left or the right side of the column, event.dropIndex on the onColReorder callback will be the same value

**Comment by cagataycivici** [comment]
Please provide a plunkr that replicates, this issue was fixed in earlier versions.
