### ISSUE TITLE
bug in dropdown : TypeError: Cannot read property 'measureScrollOffset' of undefined

### ISSUE THREAD

**Issue by huineng** [primefaces/primeng#8140]
angular 8.2
Prime 8.0.3

Maybe you can solve this [Dropdown.js] (https://github.com/primefaces/primeng/blob/61aff233fdf50b8abd545bcceb56b312b1aeb11b/src/app/components/dropdown/dropdown.ts#L426) line

```
if (this.virtualScroll) {
                setTimeout(() => {
                    this.viewPortOffsetTop = this.viewPort.measureScrollOffset();
                }, 1);
            }
```

with 

```
if (this.virtualScroll) {
                setTimeout(() => {
                    this.viewPortOffsetTop = this.viewPort ? this.viewPort.measureScrollOffset() : 0;
                }, 1);
            }
```

**Comment by bobbyinsane** [comment]
I'm also getting this, when the virtual scroll is enabled & the items are added/removed dynamically based on selection.

**Comment by george-oakling** [comment]
Having the same problem when keyboard selecting filtered dropdown

**Comment by michaelbeland** [comment]
Same thing here, happens when setting a value using the tab key to reach the control and the the arrows to select a value
