### ISSUE TITLE
[bug report] Listbox <p-listbox> select all and search is slow in IE 11, Firefox

### ISSUE THREAD

**Issue by harikrishnan-u01** [primefaces/primeng#8141]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Listbox select all and search is slow in IE 11 and Firefox browsers.

Please find below the plunkr which replicates the issue:
https://plnkr.co/edit/sL44j1f2nn859Mm6WKAJ?p=preview

**Current behavior**
1. Click on select all checkbox in the header which will select all the records.
2. Type any search keywords for eg: "New York".
3. Now delete (backspace) one character at a time from above keyword.
4. The search is lagging in IE 11 browser.

**Expected behavior**
The select all checkbox with search should be fast in all browsers.

Kindly help in providing a fix or a work around for this issue.

**What is the motivation / use case for changing the behavior?**
The users use IE 11 and Firefox as primary browsers.

**Please tell us about your environment:**

* **Browser:** IE 11, Firefox 
* **Language:** TypeScript 
* **PrimeNG version :** 5.2.0-rc.2
* **Angular version :** 7.1.4

**Comment by harikrishnan-u01** [comment]
The same issue exists in Angular version 8 and primeng version 8.

Please find below the stackblitz url:
https://github-llanhy.stackblitz.io/

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
