### ISSUE TITLE
Table column resize does not work for last column 

### ISSUE THREAD

**Issue by prasanna-5796** [primefaces/primeng#8145]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Issue with column resize for a scrollable table with variable width. When trying to resize the last column, the resize helper (blue line) get struck and does not disappear after resize or on mouse up. 

**Expected behavior**
As it works with other columns, the resize helper should go off after column is resized

* **Angular version:** 7

* **PrimeNG version:** 7.1.2

 
* **Language:** [TypeScript 3.1.3]

**Comment by niran-manandhar** [comment]
I am also having same issue , any updates?

**Comment by zipiliderman** [comment]
It happens because you provided columns and added a column in the template that's not included in the columns.
It doesn't even reach the onColResize event.

**Comment by aakashbumiya-ucsf** [comment]
Any update on this?
