### ISSUE TITLE
Calendar hour/minute fields loop infinitely

### ISSUE THREAD

**Issue by poyrazus** [primefaces/primeng#8148]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://github-tzemfw.stackblitz.io

**Current behavior**
When you have a calendar component with time enabled, when you open the picker and click and hold hour(or minute) increment button, when you release the button outside the increment button, the hour(or minute) field keeps goes into an infinite loop.

**Expected behavior**
Increment (or decrement) of the time values should stop when you release the mouse button.

**Minimal reproduction of the problem with instructions**
You can use the following instance 
https://github-tzemfw.stackblitz.io

or just check the showcase for time enabled calendar
https://www.primefaces.org/primeng/#/calendar

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows 10, Visual Studio Code, npm

* **Angular version:** 5.X
7.2.3

* **PrimeNG version:** 5.X
7.1.2
Problem still exists in the current showcase

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 76, Firefox Developer 70
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all
* **Node (for AoT issues):** `node --version` =

**Comment by yigitfindikli** [comment]
fixed in https://github.com/primefaces/primeng/issues/8296
