### ISSUE TITLE
Filtering support for templated columns

### ISSUE THREAD

**Issue by ajrauen** [primefaces/primeng#815]
If I have a column that is using a template and that template is run thru a pipe, then the filter should use the output of that pipe.
Example:
data = some date in milliseconds
<template>
   <span>{{data | dateParser}}</span>
....

I would expect the filter to search the output of the dateParser. It does not.

**Comment by bogacg** [comment]
I wouldn't expect it works out of the box, since there might be many different pipes doing different type of format change, yet I'm having exactly same date in miliseconds issue and I'd expect a way given to developers to custom code a filter for such situation at least.

**Comment by ajrauen** [comment]
Yea , in my app I just pre-processed the data before handing it off to the datatable. Its ok enough but it defeats the point of pipes. I'm glad it's already being thought about though!

**Comment by tobiasfiechter** [comment]
At out datatable we have pipes added in <template> Tags, but they are completely ignored...

**Comment by fis-dan-wnuk** [comment]
I opened an issue for this as well back in May - #413 - anyone know if this is on the dev teams radar?

I know I could format the data prior to passing it into the datatable, but would prefer to go this route if possible. It would nice to be know if/when this is planned to be supported so that I could know if I need to spend time working around it.

**Comment by bogacg** [comment]
Seems they are doing some work on this subject:
[Customizable Filtering feature of DataTable is ready for 1.0.2. Allows using any component as a filter element via templating.](https://twitter.com/prime_ng/status/806465115218477056)

**Comment by fis-dan-wnuk** [comment]
I'm not sure that those changes will address the issue I'm reporting.  That looks like they are adding additional components as alternatives to the text box - so you could put a dropdown instead of a text box for the filter field. But I would like to keep the text box, but instead of filtering on the value in the object, it would filter on the value that is rendered in the column.

It seems like there should be some event they can use to trigger storing a collection of the rows and their rendered values for each column, and use that collection when filtering.

**Comment by veb82** [comment]
Hi guys we faced the same problem and found this workaround. Not ideal but it works and will be easy to cut it off when PrimeNg fix the issue.

`export namespace PrimeNg.Helpers {
    export module DataTable {
        /**
         * This is how the onSort callback (on the whole table level) event argument looks like.
        */
        export interface IOnSortEventArgs extends SortMeta {
            multisortmeta: SortMeta[];
        }

        /**
         * Workaround for the know issue (https://github.com/primefaces/primeng/issues/815)
         * with sorting/filtering of the datatable which has templated columns.
         * To use this fix do this:
         * 1) Add onSort callback on the table like this: <p-dataTable #dt (onSort)="onSort($event, dt)">
         * 2) Decorate the component which backs up the template which uses the table with @see FixTemplatedTableSortingIssue() or
         *    add the onSort function on your component and call this function from there.
         * @param event
         * @param dataTable
         */
        export function onSort(event: IOnSortEventArgs, dataTable: DataTable): void {

            let templatesBackup: { [id: string]: any } = {};

            // remove all the templates from columns
            dataTable.columns.forEach(column => {
                templatesBackup[column.field] = column.bodyTemplate;
                column.bodyTemplate = undefined;
            });

            // put the templates back after this callback is processed
            setTimeout(() => {
                dataTable.columns.forEach(column => {
                    column.bodyTemplate = templatesBackup[column.field];
                });
            }, 1);

            // why does this work? hahaha
        }

        /**
         * Decorator which can be used to fix the templated table sorting issue without implementing the onSort function on your component.
         * (it adds the function).
         */
        export function FixTemplatedTableSortingIssue() {
            return function (target) {
                target.prototype.onSort = onSort;
            }
        }
    }
}
`

**Comment by cagataycivici** [comment]
Not sure how to implement it, upcoming filterFunction could be a solution as we can't know what is inside column so need to ask the page author to see if filter value applies the data/content displayed.

**Comment by Aymsu** [comment]
Any chance that this will be implemented soon? :)
Until then I'm going to try the solution above !

**Comment by skormel** [comment]
Any estimated date for this feature?

**Comment by cagataycivici** [comment]
p-dataTable is deprecated and will be removed in favor of the new p-table (aka TurboTable) of 5.1.0 so closing the issue. Please try the new p-table once 5.1.0 is released.
