### ISSUE TITLE
Add/expose "activeItem" for TabMenu component

### ISSUE THREAD

**Issue by gwartnes** [primefaces/primeng#8150]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
_Component: TabMenu_

The only template available for customizing tabs is via the "item" template. This allows customization of all tabs, and given its MenuItem and index.

**Expected behavior**
In addition to the above, I would also like to be able to customize the "active item" or "selected item".

I could see this being done a few different ways:

1. a new pTemplate type (maybe called "activeItem" or "selectedItem"), which would get the same variables as the "item" template.
2. a new variable added to the "item" template, called  something like "isActive".
3. exposed via the "activeItem" property that is already an @Input() on the component.

**Minimal reproduction of the problem with instructions**
https://activetabmenu.stackblitz.io/

In this simple example, I've tried to implement this behavior by using method 3 described above. The user is routed to the first tab by default, and you can see that it is active. However, the "activeItem" property doesn't work initially - it only works if you click another tab, and click back. Then you can see the icon appearing for the active item.

**What is the motivation / use case for changing the behavior?**
In my use case, only on the selected tab, I would like to show an extra icon. This icon will be clickable to trigger an options panel or something, but I want to only show this icon button on the active tab. Users will be coming to this tab menu component via the router, and so will always see an initial tab selected based on their route. This active tab should show an extra icon, as well as any tabs subsequently clicked.

**Please tell us about your environment:**
Windows 10, VS Code

* **Angular version:** 7

* **PrimeNG version:** 7

**Comment by cagataycivici** [comment]
tabmenu has activeItem property.
