### ISSUE TITLE
calendar not work in IOS (NaN-NaN-NaN)

### ISSUE THREAD

**Issue by kushanz** [primefaces/primeng#8154]
when it open in iphones(IOS) it gives input as NaN-NaN-NaN
dateFormat ="dd-mm-yy"

Please tell us about your environment:

Angular version: 7.2.7
PrimeNG version: 8.0.0
Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Language: [TypeScript 3.2.4]

Node (for AoT issues): node --version = 8.15.1

**Comment by gokselb** [comment]
I have the same isssue. Using p-calender with Firefox and IE throws this exception by momentjs
`Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 2020-01-15t00:00:00.000z, _f: undefined, _strict: undefined, _locale: [object Object]
deprecate/<@http://localhost:4200/vendor.js:195891:98
configFromString@http://localhost:4200/vendor.js:197956:15
configFromInput@http://localhost:4200/vendor.js:198182:29
prepareConfig@http://localhost:4200/vendor.js:198165:28
createFromConfig@http://localhost:4200/vendor.js:198132:44
createLocalOrUTC@http://localhost:4200/vendor.js:198219:16
createLocal@http://localhost:4200/vendor.js:198223:16
hooks@http://localhost:4200/vendor.js:195583:29
./node_modules/@bilis…`

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9.0.5, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Comment by chrisford-vcreative** [comment]
Is there a workaround in Primeng 8? We aren't ready to upgrade to Angular 9 yet.

**Comment by mangelo123** [comment]
This continues to happen in 9.0.5 with reactive forms trying to set a default value for a 'new' form. Setting a default value for editing works fine.

```
<p-calendar formControlName="dataEntryCutoffDate" [showIcon]="true"></p-calendar>

dataEntryCutoffDate: [new Date(), Validators.required],
```

When used with [(ngModel]="dateEntryCutoffDate", the NaN/NaN/NaN does not happen.
