### ISSUE TITLE
Expose Activate/Deactivate functionality for Inplace

### ISSUE THREAD

**Issue by smitpsanghavi** [primefaces/primeng#8155]
**I'm submitting a ...**
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
Currently, we have to use ViewChild and execute activate()/deactivate() method to activate/deactivate in-place editing respectively

**Expected behavior**
Expose API to Activate/Deactivate Inplace editing using input parameter or some other way.

**What is the motivation / use case for changing the behavior?**
Easier than using ViewChild. Also, user will not have to use such workarounds for such simple functionality

* **Angular version:** 7.2.15

* **PrimeNG version:** 7.1.3

* **Browser:** all

 
* **Language:** all

**Comment by dev-thinks** [comment]
Hello @cagataycivici, can you please show some light on how to call activate and deactivate methods on this component?

Thanks.
