### ISSUE TITLE
Infinite time increase/decrease at p-calendar with negative hourStep

### ISSUE THREAD

**Issue by loukas-kotas** [primefaces/primeng#8157]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/github-hhtcbz

**Current behavior**

Changing the time using the calendar UI, with hourFormat= 24 and stepsHour=-1, will cause the following 

* Clicking the hour up-arrow will decrease the time. Although it won't rotate back to 00 and will keep decreasing infinitely. So it will become 0-1, 0-2, 0-3, ...

* Clicking the hour down-arrow will increase the time. Although it won't rotate back to 00 and will keep increasing infinitely. So it will become  24, 25, 26, 27, ...

**Expected behavior**

* While clicking the hour up-arrow and reaching 01 should rotate back to 00
* While clicking the hour down-arrow and reaching 23 should rotate back to 00.

**Minimal reproduction of the problem with instructions**

* set stepHour = -1
* click arrow-up to decrease hour using calendar UI till it reach 0
* click once more and observe the displayed hour
* click arrow-down to increase hour using calendar UI till it reach 23
* click once more and observe the displayed hour

**What is the motivation / use case for changing the behavior?**

Step's sign (positive, negative) should not affect the functionality of calendar. 

**Please tell us about your environment:**

* **Angular version:** 8.X

* **PrimeNG version:** 8.X

* **Browser:** [all ]

 
* **Language:** [all]

**Comment by cagataycivici** [comment]
You should use [stepHour]
