### ISSUE TITLE
Close button for Sidebar does not show the pointer when hovering

### ISSUE THREAD

**Issue by davisb10** [primefaces/primeng#8159]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Visible from the showcase

https://www.primefaces.org/primeng/#/sidebar

**Current behavior**
- Open any of the sidebar elements
- Hover over the 'X' close button
- The color changes with the theme, however the cursor does not switch to be a pointer

**Expected behavior**
Close Button should have a cursor: pointer when it is hovered over

**Comment by yigitfindikli** [comment]
Hi,
Thanks for contributing.
Best Regards.
