### ISSUE TITLE
Feature Request: Parameterize DynamicDialogConfig

### ISSUE THREAD

**Issue by baetheus** [primefaces/primeng#8162]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**What is the motivation / use case for changing the behavior?**
When importing DynamicDialogConfig the data property has type of any, which is generally not true. The ideal typing for the property should either be unknown or parameterized. Since the current type any, changing the type to unknown is a breaking change, which is unnecessary. Parameterization seems like a better option. ie:

```typescript
export class DynamicDialogConfig<D = any> {
	data?: D;
	header?: string;
	footer?: string;
	width?: string;
	height?: string;
	closeOnEscape?: boolean;
	baseZIndex?: number;
	autoZIndex?: boolean;
	dismissableMask?: boolean;
	rtl?: boolean;
	style?: any;
	contentStyle?: any;
	styleClass?: string;
	transitionOptions?: string;
	closable?: boolean;
	showHeader?: boolean;
}

```

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
