### ISSUE TITLE
Datepicker allow future time even though you set the [maxDate] to today's date and time

### ISSUE THREAD

**Issue by vc6753** [primefaces/primeng#8164]
The maxDate in the date picker is set to today's date and time.
However, when user use the date picker, it allows future time to be entered.
This bug only occurs when you open the date picker, select the time only without choosing a date.
You can't enter a future date or time in the box or if you select a date first in the date picker, it will work fine.

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
