### ISSUE TITLE
Dropdown Focus goes on hidden element

### ISSUE THREAD

**Issue by josephrexme** [primefaces/primeng#8169]
**I'm submitting a ...** 
```
[x] bug report
```

**Test Cases (Bug Reports)**
https://angular-cktoav.stackblitz.io/ (Full Screen to prevent iFrame focus obstructions)
https://stackblitz.com/edit/angular-cktoav (With Code Panes)

**Current behavior**
When using `<p-dropdown>`, if a reference is made to it with a `.focus()` method, that focus gets applied to the hidden `<input>` element encapsulated in the component. In the reduced test cases linked above, you'd see it act like the dropdowns are actually focused for a bit but if you head over to dev tools, simply clicking devtools makes the element lose visual focus. Furthermore, when you run `document.activeElement` in the JS console, you will see the focus is placed on that hidden input element associated with current dropdown.

**Expected behavior**
The focused element `pDropdown.focusViewChild` should be the `<div class="ui-state-default">` directly nested in `<p-dropdown>`. That div happens to be focusable right now and we might also add `tabindex="-1"` to ensure it's focusable. That way we still have a focus like we would have on a semantic input element.

**What is the motivation / use case for changing the behavior?**
I want to imperatively focus on new p-dropdowns that appear on the page.

**Please tell us about your environment:**

MacOS Mojave, Chrome 77

* **Angular version:** 7.2.15
This is still an issue with current stable angular version as shown in the stackblitz test case.

* **PrimeNG version:** 8.0.3
 
* **Language:** Typescript 3.2.4

* **Node (for AoT issues):** `node --version` =   v10.16.0  on local machine

**Comment by josephrexme** [comment]
I'll be willing to create a PR for this if it is looked into

**Comment by josephrexme** [comment]
Ignore that PR. It achieves visual focus but loses interactive focus. I might make another

**Comment by cagataycivici** [comment]
That is on purpose, the focusable element is not visible.
