### ISSUE TITLE
[Bug report] selected items not updating correctly when table content changes

### ISSUE THREAD

**Issue by danielhiguerasgoold** [primefaces/primeng#8171]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Plunkr Case (Bug Reports)**
[https://stackblitz.com/edit/angular-lb1tz1](https://stackblitz.com/edit/angular-lb1tz1)

**Current behavior**
When selecting a single or multiple elements in the table, and then the table value is updated without one of the selected elements, this one still remains in the selection list. Also no selectionChange is triggered. This happens in both selection modes.

**Expected behavior**
I select one or more items in the table.
I update the table with new data which does not contain one of the selected items.
The deleted element is removed from the selection list.

**Minimal reproduction of the problem with instructions**
[https://stackblitz.com/edit/angular-lb1tz1](https://stackblitz.com/edit/angular-lb1tz1)
I select the 3 first items in the table.
I delete the first item in the table.
The deleted element is not removed from the selection list.

**What is the motivation / use case for changing the behavior?**
When data is updated in the table, selection should also be updated (in the setter).

* **Angular version:** 8.X

* **PrimeNG version:** 8.X

* **Browser:** Tried in Chrome 77 | Firefox 70.0b9

**Comment by cagataycivici** [comment]
Since you delete the element, it is on your side to remove it from selection as well.
