### ISSUE TITLE
InputMask moves the cursor to the end of the mask when the characterPattern is set to '.' or '#'

### ISSUE THREAD

**Issue by Lukiian** [primefaces/primeng#8172]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-3imt33

**Current behavior**
The `p-inputMask` component moves cursor to the end of the mask when you write there symbols such as '#', '$', '&' etc.

**Expected behavior**
The `p-inputMask` component shouldn't move cursor to the end of the mask when you write special symbols. The cursor should stay after the inputed symbol

**Minimal reproduction of the problem with instructions**
Add the `p-inputMask` component. Set there any of `mask`, `[characterPattern]` (for example '.' or '[#]'), any `slotChar`. Then try to write special symbols like #, $, &.

* **Angular version:** 8.X

* **PrimeNG version:** 8.X

* **Browser:** [all]
 
* **Language:** [all]

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
