### ISSUE TITLE
OrderList "disabled" parameter

### ISSUE THREAD

**Issue by adama357** [primefaces/primeng#8176]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
There's no way to disable the order-list component to prevent selecting rows or clicking the arrow buttons.

**Expected behavior**
Takes in "disabled" parameter

**What is the motivation / use case for changing the behavior?**

**Comment by JacobSiegle** [comment]
https://github.com/primefaces/primeng/pull/8220

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
