### ISSUE TITLE
TristateCheckbox issue on mobile phone

### ISSUE THREAD

**Issue by obitohub** [primefaces/primeng#8177]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
On mobile phone (using primeng 8) if you click on TristateCheckbox component it will bring keyboard to type some text (but there is no input, just checkbox). It is not an expected behavior as TristateCheckbox should not be treated as input but as checkbox.

**Expected behavior**
While clicking on TristateCheckbox keyboard should not appear.

**Minimal reproduction of the problem with instructions**
Try TristateCheckbox with primeng 8 version on mobile phone: https://www.primefaces.org/primeng/#/tristatecheckbox - it will produce an issue.
Try TristateCheckbox with primeng 7 version on mobile phone: https://www.primefaces.org/primeng-7.1.3/#/tristatecheckbox - it will behave correctly.

Temporary fix for me is to override ui-helper-hidden-accessible input tag with type="checkbox" instead of type="text" or in your case changing tristatecheckbox.js input #input type="text" into input #input type="checkbox".

* **Angular version:** 8.2.5

* **PrimeNG version:** 8.0.3

* **Browser:** Mobile Chrome

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
