### ISSUE TITLE
How can I point my project's package.json at a fork of primeNg?  What are the prepublish steps?

### ISSUE THREAD

**Issue by JakeSummers** [primefaces/primeng#818]
PrimeNg is missing some key functionality that I require so I have forked the repo (and [submitted a pull request](https://github.com/primefaces/primeng/pull/781) ).  I am trying to point my project at my fork until the PR is accepted.  

I have read through the [devDependencies](https://docs.npmjs.com/files/package.json#devdependencies) and [GitHub URLs](https://docs.npmjs.com/files/package.json#github-urls) section of the package.json doc, but I can't figure out how to do the prepublish step.  

This is what I have done so far...

I tried updating my package.json (in my project) from this:

```
"dependencies": {
    ...
    "primeng": "1.0.0-beta.13",
    ...
}
```

To this:

```
"dependencies": {
    ...
    "primeng": "JakeSummers/primeng.git#d35f5635a216005018bed89d249816e0f65f68f6
    ...
}
```

Looking in my node_modules directory we see that it is essentially empty:

```
[Aug-30 18:04][node_modules]$ tree primeng/
primeng/
├── LICENSE.md
├── package.json
└── README.md

0 directories, 3 files
```

Before the change to my package.json, the directory contained the following:

```
primeng/
├── components
│   ├── accordion
│   │   ├── accordion.d.ts
│   │   ├── accordion.js
│   │   └── accordion.js.map
│   ├── autocomplete
│   │   ├── autocomplete.d.ts
│   │   ├── autocomplete.js
│   │   └── autocomplete.js.map
│   ├── breadcrumb
│   │   ├── breadcrumb.d.ts
│   │   ├── breadcrumb.js
│   │   └── breadcrumb.js.map
│   ├── button
│   │   ├── button.d.ts
│   │   ├── button.js
│   │   └── button.js.map
│   ├── calendar
│   │   ├── calendar.d.ts
...
├── LICENSE.md
├── package.json
├── primeng.d.ts
├── primeng.js
├── primeng.js.map
├── prod
│   ├── application.js
│   ├── polyfills.js
│   └── vendor.js
└── README.md

62 directories, 195 files
```

Any pointers or examples would be appreciated. Thanks!

[_I cross posted this question to stackoverflow._](http://stackoverflow.com/questions/39237953/how-to-point-my-package-json-at-my-fork-of-primeng)

**Comment by JakeSummers** [comment]
*Update - but not a full solution*

One reason that I am not getting anything when I try to pull in my repo is that the .npmignore file contains the following: 

```
[Aug-31 11:28][primeng]$ cat .npmignore 
# dependencies
node_modules

# demo
showcase
index.html

# typescript
*.ts
!*.d.ts

# git
.git
.gitignore

# type definition
typings
typings.json

# config
tsconfig.json
webpack.config.js

# misc
*.log
```

Removing the contents of this file causes the the entire repo to get pulled into the node_modules folder.  Great.  

I think now there are two options...  

* Build the primeNg package as part of my project
* (or the better option) Add a `prepublish` hook into the package.json of primeNg.

I would still be very interested to see how the PrimeFaces team is publishing this.

**Comment by cagataycivici** [comment]
Please use forum for cases like these, thank you.
