### ISSUE TITLE
Script Error when user clicks on SVG element inside Tree node template

### ISSUE THREAD

**Issue by AwadMaharoof** [primefaces/primeng#8183]
[X ] bug report
[ ] feature request
[ ] support request

**Current behavior**
If the template of a Tree Node contains an SVG, a script error is thrown from the Tree.prototype.onNodeClick method when the user clicks exactly on top of the SVG element. 

This happens because the onNodeClick function attempts to access the indexOf property of a SVGAnimatedString.

**Expected behavior**
Users should be able to use SVG icons inside Tree templates and click anywhere within the node without primeng throwing any errors

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/angular-hlqzve

If you click exactly on the icon you can see a script error on the browser console.

**Comment by cagataycivici** [comment]
Seems to be fixed in 9.x.
