### ISSUE TITLE
onRowSelect callback function doesn't get called after selection change

### ISSUE THREAD

**Issue by coriumalpha** [primefaces/primeng#8186]
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Plunkr Case (Bug Reports)**

[https://stackblitz.com/edit/github-by7uh9](https://stackblitz.com/edit/github-by7uh9)

**Current behavior**

Manual selection: When a row gets clicked, the element is successfully selected and "(onRowSelect)" callback function gets called.
Programatical selection: When an element is assigned to the "[(selection)]", it shows as selected in the table but the "(onRowSelect)" callback function does not get called

**Expected behavior**
In both cases, there is a row selection, so the "(onRowSelect)" callback function needs to get called. If the "(onRowSelect)" behavior is designed to be called only when clicking a row, the name must be updated to "(onRowClick)".

**Minimal reproduction of the problem with instructions**
Navigate to the provided [StackBlitz example](https://stackblitz.com/edit/github-by7uh9)
Manual selection: When selecting an element by clicking a table row, the onRowSelect callback will get called and, consecuently, the "Selected index: {{value}}" will update its value to the selected element index.
Programatical selection: Click the "Select Random" blue button. It will assign a random object from the table array to the "[(selection)]", the table will highlight the selected element but the onRowSelect callback won't get called and, therefore, no value will be shown in "Selected index: {{value}}"

**What is the motivation / use case for changing the behavior?**
Getting the selected element row index. After programatically selecting an element, I wish to update the page (first, index) in the paginator to show the user the selected element at first.

**Please tell us about your environment:**
Visual Studio Code, npm, webpack

* **Angular version:** 7.2

* **PrimeNG version:** ^7.1.3

* **Browser:** [all]
 
* **Language:** [TypeScript 3.2.2]

* **Node (for AoT issues):** `node --version` =

**Comment by davisb10** [comment]
onRowSelect() event is for the selection, there is a corresponding negation event onRowUnselect() that is called when you 'unselect' a row via the table row click / double-click, etc.

For the onRowSelect() event to be emitted upon adding a value to the selection property, the emitter would need to be called from the `@Input` setter at https://github.com/primefaces/primeng/blob/master/src/app/components/table/table.ts#L586

**Comment by coriumalpha** [comment]
> For the onRowSelect() event to be emitted upon adding a value to the selection property, the emitter would need to be called from the `@Input` setter

From my perspective it is not consistent behavior. That selection property should be being listened and the emitter being called upon adding (or changing) a value in the selection property.

**Comment by cagataycivici** [comment]
Events are called with user changes not on programmatic changes, since you do the programmatic changes, you can call the method handler manually.
