### ISSUE TITLE
new `fileupload` component not exported from the barrel making the TypeScript compiler all sad

### ISSUE THREAD

**Issue by tbertran** [primefaces/primeng#819]
Loving the new `fileupload` component but it seems `/primeng.d.ts` is missing this crucial one-liner:
`export * from './components/fileupload/fileupload';`

This obviously makes it impossible to import `FileExportModule` into applications. 
Related to #104

**Comment by ammar91** [comment]
same error here.

**Comment by ammar91** [comment]
After adding an entry in primeng.d.ts and primeng.js make the build successful

> primeng.d.ts - export * from './components/fileupload/fileupload';
> primeng.js export * from './components/fileupload/fileupload';
