### ISSUE TITLE
p-treetable filter doesn't expand the results of the filter

### ISSUE THREAD

**Issue by begogna** [primefaces/primeng#8192]
**I'm submitting a**
[x] bug report 
[ ] feature request 
[ ] support request 

**Current behavior**
p-treetable filter doesn't expand the results when found, the tree gets collapsed

**Expected behavior**
When you search by global or local filter, expand the results in order to see them

**Minimal reproduction of the problem with instructions**
I took the same as for #7757 -> https://stackblitz.com/edit/github-3dtpnj

**What is the motivation / use case for changing the behavior?**
It is confusing and not user friendly if we have to expand the nodes manually after filtering. It looks like there are no results.

**Please tell us about your environment:**
Angular version: 7.2.0
PrimeNG version: 8.0.3
Browser: all

Thanks in advance !
Begoña

**Comment by shrknt35** [comment]
@cagataycivici @mertsincan is it still not part of 9.0.7 or 9.1.0? or was the milestone changed for this defect?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
