### ISSUE TITLE
readonly input should have the same design as disabled (grey...)

### ISSUE THREAD

**Issue by yelhouti** [primefaces/primeng#8196]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
readonly input should have the same design as disabled (grey...)

**Current behavior**

We can't visually distinguish a readonly input

**Expected behavior**

 it should look like a disabled input

**Comment by JacobSiegle** [comment]
It is intended - https://stackoverflow.com/a/7730719/3333134

**Comment by yelhouti** [comment]
@JacobSiegle I want readonly (submitted...) not disabled. I'm talking about design, I want to be able to differentiate visually. what are you talking about?

**Comment by JacobSiegle** [comment]
Please read the link.

**Comment by yelhouti** [comment]
@JacobSiegle I did...

**Comment by JacobSiegle** [comment]
`Browsers provide no default overridden visual feedback that the form element is read only. (This can be a problem… see below.)`

`Some browsers may override or provide default styling for disabled form elements. (Gray out or emboss text) Internet Explorer 5.5 is particularly nasty about this.`

They have designed the framework to this.

**Comment by yelhouti** [comment]
@JacobSiegle where can you read that this was an active decision from primeng? And even if it is the case, I can respectfully disagree here if they say it's the case and provide arguments. I don't anderstand what you are trying to tell me

**Comment by JacobSiegle** [comment]
OK you can just wait for a maintainer then, best of luck.

**Comment by cagataycivici** [comment]
No plans to mix disabled state and readonly as they should look different.
