### ISSUE TITLE
Visualize with an icon that Dialog is resizable 

### ISSUE THREAD

**Issue by mmlitvin** [primefaces/primeng#8199]
[x] feature request

Current behavior
There is no visual cue that dialog could be resized unless you try hovering over the bottom left corner. 

Expected behavior
Visualize with an icon that Dialog is resizable 

What is the motivation / use case for changing the behavior?
Usability for the user, 

Angular version:
7.3.8

PrimeNG version:
7.1.0

Browser:
[all]

**Comment by JacobSiegle** [comment]
It's a CSS fix so a maintainer would have to do it, a prime icons doesn't exist also from a quick scan for me to manually put it in.

Anyway all you need to do to put it in yourself is to override the class like ui-icon-gripsmall-diagonal-se in your CSS and set the icon. That class is already in the correct spot, it's almost like it's left out on purpose.

**Comment by cagataycivici** [comment]
No plans to do it as we based our dialog on mac os windows which do not have a resize indicator.
