### ISSUE TITLE
Dropdown preselection fails for objects with null values

### ISSUE THREAD

**Issue by caebeman** [primefaces/primeng#820]
I have an object with some null properties on it that I am trying to use to preselect an item from a dropdown. This issue is that domhandler.equals() always returns false for an object with null properties. For example if I have 2 objects that look like this:
    {name:'Name', exceptionMessage: null, id:0}
domhandler.equals is going to return false because of the exceptionMessage field. This happens because typeof null === object and the switch for object recursively calls domhandler.equals which always returns false for any null value.

**Comment by loic49** [comment]
I have object with "undefined" properties and the problem still exists.

the problem is on line 313/314 in domhandler.ts

we've got this code :

```
            for (var p in obj2) {
                if (typeof (obj1[p]) == 'undefined') return false;
            }
```

But we have to check obj2 property too, because if it's "undefined" too we should not return false. Here what's working for me :

```
            for (var p in obj2) {
                if (typeof (obj1[p]) == 'undefined' && typeof (obj2[p]) != 'undefined') return false;
            }
```
