### ISSUE TITLE
[Bug Report] Multiselect onBlur event is getting fired when the control is in focus

### ISSUE THREAD

**Issue by skotrik** [primefaces/primeng#8200]
MultiSelect V8.0.3 onBlur event is working fine if the overlay is not visible. But if the overlay is visible, then its getting fired when the focus moves to filter, which is incorrect because the focus is still on the Multiselect and you are still in the same control. onBlur event supposed to be executed when the user leaves Multiselect control.

**Comment by sahvineet** [comment]
@skotrik  you can use `onPanelHide` event instead of `onBlur`.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
