### ISSUE TITLE
p-calendar manual input does not work when date format contains two y

### ISSUE THREAD

**Issue by tomsk13** [primefaces/primeng#8201]
Calendar.prototype.parseDate
Function getNumber
you set year size with this condition:
`match === "y" && isDoubled ? 4`
So you force a year on 4 digit
But my dateFormat is 'dd.mm.yy'

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
