### ISSUE TITLE
p-calendar : it will be nice if it could parse date according to several format

### ISSUE THREAD

**Issue by tomsk13** [primefaces/primeng#8202]
Now, p-calendar only parse string input according to the only dateFormat parameter

But users have multiple ways to enter date in my application...
Can you manage that ?

**Comment by JacobSiegle** [comment]
Can you elaborate on the use case a bit more? If it's internationalization you would detect the language and swap the calendar settings. Otherwise why wouldn't the user just use the calendar UI or enter the date format it forces?

**Comment by tomsk13** [comment]
It's not internationalization.

According to the habits of an accountant who has to encode a lot of data ... the date can be written in many different ways and the user does not understand that his own way (which is necessarily the best) is not supported.
e.g. separator can be dots or slash ... year can be on 2 digits ...

**Comment by cagataycivici** [comment]
Please see;

https://github.com/primefaces/primeng/issues/6194
