### ISSUE TITLE
p-table emptymessage column not available to template

### ISSUE THREAD

**Issue by levinzz** [primefaces/primeng#8204]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/issue-primeng-template-tguxnq

**Current behavior**
The emptymessage is not displayed on the whole table width.
Error in the console :
`ERROR TypeError: Cannot read property 'length' of undefined`

**Expected behavior**
Emptymessage displayed on the whole table width (colspan = column.length) and no error

**Minimal reproduction of the problem with instructions**
Just copy the emptymessage example from https://www.primefaces.org/primeng/#/table to a project.

**Comment by JacobSiegle** [comment]
[columns]="cols" needs to be set on the table for [attr.colspan]="columns.length" to work. I can make a quick PR to update the docs.

**Comment by levinzz** [comment]
Adding [columns]="cols" to p-table doesn't solve the problem.

I updated the stackblitz so you can check.

**Comment by cagataycivici** [comment]
There is a confusion, you are using static columns in your example. If you are using static columns you can apply [colspan]="4" since you know the columns, for dynamic columns, it can be like;

```xml
<p-table [columns]="cols" [value]="cars">
    <ng-template pTemplate="header" let-columns>
        <tr>
            <th *ngFor="let col of columns">
                {{col.header}}
            </th>
        </tr>
    </ng-template>
    <ng-template pTemplate="body" let-rowData let-columns="columns">
        <tr>
            <td *ngFor="let col of columns">
                    {{rowData[col.field]}}
            </td>
        </tr>
    </ng-template>
    <ng-template pTemplate="emptymessage" let-columns>
        <tr>
            <td [attr.colspan]="columns.length">
                No records found
            </td>
        </tr>
    </ng-template>
</p-table>
```
