### ISSUE TITLE
Dialog modal="true" breaks tabbing behavior

### ISSUE THREAD

**Issue by Spiral1401** [primefaces/primeng#8205]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-985hs2

**Current behavior**
When modal = true, tabbing stops working normally. For my situation, I've mostly noticed this with the editor component - you tab to the first format header button/icon, and it just stops. I definitely don't have a strong grasp of what's going on, but it's easily repeated in the stackblitz.

**Expected behavior**
Normal tabbing

**Minimal reproduction of the problem with instructions**
in stackblitz:
1. set modalEnabled = false
2. show dialog. click subject, tab through. You tab through all the editor icons, to the text entry.
3. set modalEnabled = true
4. show dialog. try tabbing through - you get to the font size selector and it just stops.

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
