### ISSUE TITLE
Providing p-tree node filter value as property

### ISSUE THREAD

**Issue by normchenjk** [primefaces/primeng#8206]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
Would like to be able to filter tree nodes based on a value specified as a property passed to `p-tree`, instead of only via user input into the default search bar provided by the component as it currently is. This allows better programmatic control over tree node filtering.

For example:
`<p-tree [value]="files" filter="true" [filterValue]="myFilterValue"></p-tree>`

Whenever there are changes to the `myFilterValue` variable caused elsewhere, the `p-tree` component will automatically be filtered.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
