### ISSUE TITLE
Table cell navigation should allow moving to footer

### ISSUE THREAD

**Issue by yelhouti** [primefaces/primeng#8207]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

if the footer contains an editable cell (ex: "+ with dropdown" to add a new line), the tab does't move to it, this can easily be fixed and I can provide a PR if you want.

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9.0.5, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Comment by yelhouti** [comment]
@cagataycivici  here it is: https://stackblitz.com/edit/angular-vdpmyx
try using tab to get to the last cell
