### ISSUE TITLE
Original browser event of p-checkbox is not exposed

### ISSUE THREAD

**Issue by rafa-as** [primefaces/primeng#8221]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
I don't think it's necessary.

**Current behavior**
The callback function onChange doesn't receive the original event.

**Expected behavior**
The callback function onChange receive the original event.

**Minimal reproduction of the problem with instructions**
Add a p-checkbox, set the onChange function and check the parameters.

**What is the motivation / use case for changing the behavior?**
1. Access to originalEvent to call the special functions like: stopPropagation / eventPrevendDefault
2. To have the same behaviour on every input, like: https://github.com/primefaces/primeng/issues/1571 , https://github.com/primefaces/primeng/issues/1581 

* **Angular version:** 8.X.X

* **PrimeNG version:** 8.X.X

**Comment by fredericojesus** [comment]
@cagataycivici This was a breaking changed and it was not mentioned as such...
You should not bump a minor version with breaking changes...
And the binary input now does nothing, we always receive an object instead of simple boolean now.
