### ISSUE TITLE
Turbo Table Show Selected Rows Only

### ISSUE THREAD

**Issue by JacobSiegle** [primefaces/primeng#8224]
You have a table of 1000 rows and 12 of them are selected. It's very difficult for the user to find all 12 selected rows. It would be neat if turbo table had a mode where a button could be pressed to show only the selected rows.

There's ways you can do this manually by setting props in rowdata and using filtering / sorting or making another table / display or selected rows. It would be nice to save doing that extra work every single time and have it built into the table.

**Comment by cagataycivici** [comment]
Good idea but it does not seem to receive much demand so we'll reconsider if there is more feedback.
