### ISSUE TITLE
p-calendar not working for reactive form with validation

### ISSUE THREAD

**Issue by fedeolto** [primefaces/primeng#8225]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

I created this Stackblitz but unluckily I'm experiencing issues sharing it
https://stackblitz.com/github/bnmiyyqv
I pasted below my code

You can see the errors here: https://bnmiyyqv.github.stackblitz.io

**Current behavior**
In a reactive form if I declare the p-calendar related form control with a validator, like this:
`expirationDate: new FormControl({ value: new Date() }, [Validators.required])`
 the page loads with error saying: "Error: date.getDate is not a function". Debugging I see my date as an object but not a Date object. 
If I declare the p-calendar related form control without a validator, like this:
`expirationDate: new FormControl(new Date())`
everything works fine
**Expected behavior**
I would like to add validators to p-calendar form control when declaring its FormGroup

**Minimal reproduction of the problem with instructions**
`import { Component } from '@angular/core';
import { FormGroup, FormControl, Validators } from '@angular/forms';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent {
  testForm: FormGroup;

  ngOnInit() {
    this.testForm = new FormGroup({
      expirationDate: new FormControl({ value: new Date() }, [Validators.required])
    });
  }
}

// If I substitute line 13 with: 
// expirationDate: new FormControl(new Date())
// works like a charm
`

`<h2>PrimeNG Issue Template</h2>
<p>Please create a test case and attach the link of the plunkr to your github issue report.</p>

  <form [formGroup]="testForm">
    <label>Calendar input: </label>
    <p-calendar [ngClass]="{
      'invalid-field': testForm.controls['expirationDate'].invalid && ( testForm.controls['expirationDate'].dirty || testForm.controls['expirationDate'].touched)
      }"
      formControlName="expirationDate" 
      dateFormat="dd/mm/yy"
      [keepInvalid]="true"
      [showIcon]="false">
  </p-calendar>
  </form>
`

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
node: 10.16.3

* **Angular version:** 8.0.2

* **PrimeNG version:** 8.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** TypeScript 3.4.5

* **Node (for AoT issues):** `node --version` =

**Comment by JacobSiegle** [comment]
```
    this.testForm = new FormGroup({
      expirationDate: new FormControl(new Date(), Validators.required)
    });
```

The form state docs say you need disabled state -
formState | any | Initializes the control with an initial value, **or an object that defines the initial value and disabled state**. Optional. Default is null.

Question not an issue please close.

**Comment by fedeolto** [comment]
My bad, I was ignoring this!!! Adding `disabled: false` everything started working. Thanks a lot

**Comment by BT-ICD** [comment]
Thank you team, this helped me a lot.

Sorry to update on closed issue.
