### ISSUE TITLE
P-table: Cannot read property 'nativeElement' of undefined

### ISSUE THREAD

**Issue by filip12345678910** [primefaces/primeng#8227]
Hi, we "solved" the issue of unnecessary triggering of lazy load event (https://github.com/primefaces/primeng/issues/7657)
by turning off virtual scroll when there is a small number of rows. We react to change of totalRecords, but p-table also reacts to change of totalRecords, by trying to setVirtualScrollerHeight, but this ends up throwing 
P-table Cannot read property 'nativeElement' of undefined
because in the meantime, we set virtualScroll false and I think that it causes your virtualScrollerViewChild to be undefined.
Can you please repair 

> ScrollableView.prototype.setVirtualScrollerHeight = function () {
        if (this.virtualScrollerViewChild.nativeElement) {
            this.virtualScrollerViewChild.nativeElement.style.height = this.dt.totalRecords * this.dt.virtualRowHeight + 'px';
        }
    };
so that it doesn't throw error when this.virtualScrollerViewChild is undefined? Or repair the original issue https://github.com/primefaces/primeng/issues/7657

**Comment by cagataycivici** [comment]
76657 is fixed.
