### ISSUE TITLE
[Bug Report] Multiselect arrow keys on IE 11

### ISSUE THREAD

**Issue by skotrik** [primefaces/primeng#8229]
Up/down arrow keys don't work on Multiselect. This can be replicated on PrimeNG website on IE 11.

Click on the MultiSelect to open overlay. 
Click on the checkbox to select an item and try to use up/down arrow keys to move to the next/previous item. Arrow keys don't work in this scenario.

Click on one of the items in the list(click on the text not the space) to select an item then try to use arrow keys to move up/down. Arrow keys don't work in this scenario.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
