### ISSUE TITLE
id property on PanelMenu

### ISSUE THREAD

**Issue by kosjak95** [primefaces/primeng#8233]
**[x ] bug report** => Search github for a similar issue or PR before submitting
[] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Current behavior**
Passing MenuItem[] as model into PanelMenu not render given ids. In situation if elements have childs elements ids of childs are rendered.

**Expected behavior**
Rendered ids on both: parent and childs elements of model array.

**Minimal reproduction of the problem with instructions**
Create a menu item array in the component ts file.
Bind this to a panel menu.
Examine html, notice there is no id attribute on parents elements of the menu items.

**What is the motivation / use case for changing the behavior?**
I would like ids so I can find elements easier when running automated testing.

Please tell us about your environment:
Windows 10, VS Code, NPM

Angular version: 8.3.5.

PrimeNG version: 8.0.3

Browser: [**all** | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Language: [**all** | TypeScript X.X | ES6/7 | ES5]

**Comment by anjelchen** [comment]
I agree and reported it already here: https://github.com/primefaces/primeng/issues/7533

**Comment by yigitfindikli** [comment]
Duplicate https://github.com/primefaces/primeng/issues/7533
