### ISSUE TITLE
AutoComplete vs Dropdown button tabstop

### ISSUE THREAD

**Issue by Laoujin** [primefaces/primeng#8235]
**I'm submitting a ...** 
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
1) Tab into an AutoComplete with `[dropdown]="true"`
2) Tab while in the AutoComplete
--> Tabs into the AutoComplete dropdown button

**Expected behavior**
Does not focus the button but focuses the next control in the form.

**Minimal reproduction of the problem with instructions**
1) Goto: http://primefaces.org/primeng/#/autocomplete
2) Click into the "Advanced" example AutoComplete.
3) Press tab.

**What is the motivation / use case for changing the behavior?**
This behavior is different from the Dropdown button behavior.

**Please tell us about your environment:**
Happens in the PrimeNG demo app.

--------------

If you guys decide that
1) The AutoComplete dropdown button should not gain focus
or 2) The Dropdown button should gain focus

Then I will create a PR to align the behavior for the two controls.

**Comment by cagataycivici** [comment]
These are different components, ac dropdown has functionality where dropdown is only a visual indicator for p-dropdown.

**Comment by waratah** [comment]
Work around:


  @ViewChild('ac', { static: true })
  private autoComplete: AutoComplete;

  ngOnInit() {
    timer(40).subscribe(() => {
      if (this.autoComplete.dropdownButton) {
        this.autoComplete.dropdownButton.nativeElement.setAttribute('tabindex', -1);
      }
    });
  }
