### ISSUE TITLE
p-tree lazy loading not working as arrow icon not showing despite marking leaf false

### ISSUE THREAD

**Issue by fijas** [primefaces/primeng#8237]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
In the `p-tree` component for nodes whose children are to be lazy loaded, even if the `leaf` property is set to `false`, the arrow icon does not show. This makes it impossible to lazy load the children.

Edit: I think this PR is what is causing this issue: https://github.com/primefaces/primeng/pull/8173/commits/df95b7fbdecce4e4bafad1a2200f499d79465a93
It was merged in order to fix this issue: https://github.com/primefaces/primeng/issues/6743

**Expected behavior**
For nodes with `leaf` property set to `false`, the arrow icon should appear irrespective of whether there are children present?

**Minimal reproduction of the problem with instructions**
On latest [8.0.4] version of primeng, lazy loading doesn't work. This can be seen / reproduced in the docs at: https://www.primefaces.org/primeng/#/tree, the lazy loading example doesn't work.

* **Angular version:** 8.2.10

* **PrimeNG version:** 8.0.4

* **Browser:** all
 
* **Language:** all

**Comment by AJBauwens** [comment]
Slightly worse than reported here, even if the filtered node already has children but they have not been displayed prior to setting the filter, they will not show when the filter is set.

See here:
https://stackblitz.com/edit/angular-7lmtup?embed=1&file=src/app/app.component.ts

drop down child 1
set filter to 1, the grandchildren of child 1 still show but you cannot dropdown child 10

**Comment by jmesa-sistel** [comment]
My temporal fix:
```
// HACK to fix https://github.com/primefaces/primeng/issues/8237
Tree.prototype.isNodeLeaf = (node) => node.leaf;
```

**Comment by AJBauwens** [comment]
Hi Julian,

This looks promising. Unfortunately I do not know how to implement this
hack.
Do you have more instructions as to how and where to put this code?

thanks

**Comment by jmesa-sistel** [comment]
@AJBauwens 
For example in app.component.ts add
`import { Tree } from 'primeng/tree';`
and in constructor() or ngOnInit() add the code
`Tree.prototype.isNodeLeaf = (node) => node.leaf;`

Nothing else to do. Hope it works for you.

**Comment by jmesa-sistel** [comment]
@AJBauwens 
After read your problem, I think your bug is not related to this change.

**Comment by AJBauwens** [comment]
@jmesa-sistel 
Thanks for clear instructions. Sadly, you are correct this change did not solve my problem.
I am using lenient filtering which, I think, does not apply to child nodes.
Also that was my first use of stackblitz. I will review the entry and learn!
