### ISSUE TITLE
Click and Double Click events for Toast

### ISSUE THREAD

**Issue by davisb10** [primefaces/primeng#8240]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

Clicking or Double-Clicking the body section of either a Toast or Messages item provides no feedback / event.

**Expected behavior**

An event emitter that emits the current clicked-on message object when the body is either clicked or double-clicked.

**What is the motivation / use case for changing the behavior?**
The ability to act upon a user clicking or double-clicking on a given item. 
Example, Toast message is shown stating that a given action needs to be performed. User either clicks or double-click on the message, and based on some metadata stored in the _data_ property a route change is performed, dynamically created tab component is opened, etc.

**Comment by natechiarello** [comment]
is there any update on this item? or any temporary workaround? this feature was present in v6 growl component and was removed when swapping for toast component.
