### ISSUE TITLE
Resizable Columns enhancement with Frozen Columns

### ISSUE THREAD

**Issue by elDrimm** [primefaces/primeng#8241]
**I'm submitting a ...** 
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

[https://stackblitz.com/edit/angular-stmx3d](https://stackblitz.com/edit/angular-stmx3d)

**Current behavior**
When having frozenColumns enabled and resizableColumns set to true with the columnResizeMode to expand it wrongly sets the width of the `ui-table-scrollable-header` and the `ui-table-scrollable-body`. When resizing this will create a scrollbar on the page itself and not within the table, but when expanding a column even more, it sets the width to `auto` allowing the scroll to be within the table. Resize the column back to a smaller width and the scrollbar on the table is gone but back on the page.

**Expected behavior**
I expected the scrollbar to be in the table-body and not on the page.

**Minimal reproduction of the problem with instructions**
[https://stackblitz.com/edit/angular-stmx3d](https://stackblitz.com/edit/angular-stmx3d)

Open the stackblitz link and make for example the year column first smaller, allowing the scrollbar to be visible on body level, afterwards make the year column wider allowing the scrollbar to be visible on table level. See example images below.

**What is the motivation / use case for changing the behavior?**
The scrollbar should never be on body level (x-axis), because this does not only scroll the table content, but the entire page content.

* **Angular version:** 
Angular 8.2.10

* **PrimeNG version:**
8.0.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Tested this in FireFox 69.0, Edge 42.17134.1.0 and Chrome 77.0.3865.120

* **Quick fix**
`
.ui-table-scrollable-header.ui-widget-header,  
.ui-table-scrollable-body {  
  width: auto !important;  
}
` 

First load of application: looks correct.
![start](https://user-images.githubusercontent.com/34384541/66904851-163b5280-f005-11e9-91cf-5db06ee63be1.PNG)

Making the year column smaller, but the content is still bigger than the body element, showing a scrollbar on body level and not on table level.
![part 1](https://user-images.githubusercontent.com/34384541/66904852-163b5280-f005-11e9-8a0c-121dd9590d9f.PNG)

Make the year column wider again and it is back to the correct overflow on the table.
![part 2](https://user-images.githubusercontent.com/34384541/66904854-163b5280-f005-11e9-8a4b-7dc7e8027010.PNG)

**Comment by MikeMatusz** [comment]
I think this is a defect, as this worked correctly in v9.  It appears to be tied to [this calculation](https://github.com/primefaces/primeng/blob/fb856561e4cf102f05682351a56211cadb911fae/src/app/components/table/table.ts#L1771) comparing the offsetWidth of the entire `p-table`, including frozen columns, to the width of just the unfrozen body.  If you resize the column further, so the unfrozen body exceeds the total table width, then the scrollbar appears as expected.

**Comment by MikeMatusz** [comment]
@cagataycivici Can you take a look at this issue/my PR when you get a chance and provide some feedback? Considering how it used to behave, and looking at the code, I think it's pretty clear this was what was originally intended.  I think this should be prioritized as a defect, not an enhancement, and I'd happily amend my PR to address any concerns you might have about the fix.

**Comment by MikeMatusz** [comment]
@cagataycivici Checking back in on this.  The PR shouldn't take long to review, please let me know what you think.

**Comment by bornes** [comment]
Hi, @cagataycivici 

Do we have some updates about the review of this PR? 

Thanks

**Comment by MikeMatusz** [comment]
@yigitfindikli Looks like you've most recently been involved with the table component, (although it's been nearly a year since there's been any activity).  Can you take a look at this PR and provide any feedback or comment on its status?

**Comment by yigitfindikli** [comment]
Fixed in https://github.com/primefaces/primeng/issues/10310.

Thanks for caution @MikeMatusz.
