### ISSUE TITLE
Input mask with no mask

### ISSUE THREAD

**Issue by JacobSiegle** [primefaces/primeng#8245]
The ability to have an input mask component which can have the mask set to null and work like a normal input. This would allow toggling the input mask for special scenarios.

Made up example since I cannot share my use case - I have 20 products with 20 mask formats. A new product comes out which doesn't match any of the codes. I want to allow free input for the user to enter the code.

The current workaround is to replace the input mask with a normal input using an *ngIf.

**Comment by Un1xMida** [comment]
any updates regarding this ?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
