### ISSUE TITLE
BlockUI is blocked all element except the target

### ISSUE THREAD

**Issue by syamsu-smansa** [primefaces/primeng#8247]
in `set blocked(val: boolean) `

`this.mask` always `undefined`

code;

`@ViewChild('mask', { static: false }) mask: ElementRef;`

changing to

`@ViewChild('mask', { static: true}) mask: ElementRef;`

fix the problem

**Comment by yigitfindikli** [comment]
Seems to be fixed https://github.com/primefaces/primeng/blob/master/src/app/components/blockui/blockui.ts .

**Comment by Skayona** [comment]
the problem is still actual `this.mask` always `undefined`
i'm using  `"primeng": "^9.1.0"`
