### ISSUE TITLE
Menubar with autodisplay bug in Chrome with small Displays

### ISSUE THREAD

**Issue by telion2** [primefaces/primeng#8248]
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

Goto: https://www.primefaces.org/primeng/#/menubar  in Chrome
set the display size low (e.g. S5) 
Click on the menuitems with autodisplay. 
**Current behavior**
The menu items in a dropdown will not open. 

**Expected behavior**
They should open if clicked with small display sizes that usually dont have hover event.

**Comment by esaesa** [comment]
autodisplay is depreciated now

**Comment by cagataycivici** [comment]
Obselete now
