### ISSUE TITLE
Table: filters do not always update the local store

### ISSUE THREAD

**Issue by abruegit** [primefaces/primeng#8249]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
We have a table with filters and using localStorage. Every now and then, editing the filters does not update the stored state (resulting in an out-of-sync stored state which then leads to problems when reloading the page). 

**Expected behavior**
The stored state should always be updated when filters are changed or cleared.

**Minimal reproduction of the problem with instructions**

*STEPS TO REPRODUCE*
Obviously it is hard to reproduce but when you play around in the following stackblitz you'll eventually see it happen.

- type into the filter fields
- watch the state below the table and check for inconsistencies

*MINIMAL DEMO*
https://stackblitz.com/edit/github-jayhwn

**Please tell us about your environment:**

* **Angular version:** 8.1.0

* **PrimeNG version:** 8.0.1

* **Browser:** [all? | Chrome 77.0.3865.120 ]

 
![stackblitz filter state out of sync](https://user-images.githubusercontent.com/50319066/67022182-1de02180-f101-11e9-8111-c4b602a08c55.jpg)

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
