### ISSUE TITLE
Header Checkbox is not update with page change if page is more than 2

### ISSUE THREAD

**Issue by himanshuchauhan1252** [primefaces/primeng#8252]
I am using PrimeNG table and i have a problem with Header checkbox . Header checkbox is not update on page change if pages is more than 2. Please solve this issue as soon as possible.

**Comment by JacobSiegle** [comment]
Please make a stack-blitz so the issue can be confirmed.

**Comment by kramar** [comment]
@JacobSiegle I've created example where you can take a look on issue
https://stackblitz.com/edit/angular-5xawcx

From my point of view the problem is in header checkbox state. It doesn't react on page change

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
