### ISSUE TITLE
p-calendar should use accept an Unicode locale identifier and FormatWidth to format date and time

### ISSUE THREAD

**Issue by thomasesh** [primefaces/primeng#8253]
Currently p-calendar accepts a "dateFormat" property to specify the format of the date and a  "locale" property for a custom object to allow for localization.   This requires the user to create their own custom locale object for every language they support.    

The localization of both date and time is already handled in Angular by i18n as described at https://angular.io/guide/i18n.    

p-calendar should allow the specification of a Unicode locale property and a FormatWidth property (from @angular/common) to control the formatting of both the date and time.  Then p-calendar can use Angular methods ( `getLocaleDateFormat()`, `getLocaleTimeFormat()`, `getLocaleDateTimeFormat()`) to format the date and time without requiring the user to create custom locale objects.  

For example: 

<p-calendar  formControlName="startDate" [angularLocale]="angularLocale" [formatWidth]="formatWidth" showTime="true" [showIcon]="true" > </p-calendar>

     angularLocale would be set to "en-US" for United States English locale.
     formatWidth could be set the FormatWidth.Short

If showTime && !timeOnlyi, p-calendar would use the 'getLocaleDateTimeFormat()' method.
if timeOnly, p-calendar would use the 'getLocaleTimeFormat()' method.
if !showTime, it would use the `getLocaleDateFormat()` method.

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Unable to localize the time format to specify between 24 hr format and 12 hr format

**Expected behavior**
Use Angular's i18n locale specification and a FormatWidth to specify the format of the date and time.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
