### ISSUE TITLE
VirtualScrolling for Tree

### ISSUE THREAD

**Issue by gs-smuthyam** [primefaces/primeng#8257]
Hi There,

We have started using p-tree to display the tree structured data. While we are doing so figured out that there are instances where we need to work with large amount of nodes with nesting levels involved.

This is hitting the performance. Figured out that virtual scrolling would help in this case. 

Would like to know if it is already implemented or it is planned in near future. Any suggestions on handling such scenarios is appreciated.

**Comment by skormel** [comment]
I opened a issue some time ago #7269, but no response from primeng team.

**Comment by kranthi0099** [comment]
I'm also waiting for this feature in tree

**Comment by cagataycivici** [comment]
Planned for 9.1.0;

https://www.primefaces.org/primeng-q2-2020-roadmap/

**Comment by cagataycivici** [comment]
Implemented for 9.1.0.

**Comment by cagataycivici** [comment]
Screencast:

https://youtu.be/iY4JHdwB6fk
