### ISSUE TITLE
ariaLabelAsc and ariaLabelDesc do not work for p-TreeTableSortIcon and p-sortIcon

### ISSUE THREAD

**Issue by ranjanmicrosoft** [primefaces/primeng#8261]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
Unable to get sorting information for a table using a screenreader

**Expected behavior**
When a screen reader lands on a table column header, it should get the sorting information using these fields 

**Minimal reproduction of the problem with instructions**
The [ariaLabelAsc] and [ariaLabelDesc] fields were removed from p-SortIcon with a recent commit. They are still present in p-TreeTableSortIcon, but they no longer appear in the template for these 

**What is the motivation / use case for changing the behavior?**
Accessibility support for screen-reader. 

**PrimeNG version:** 
This is a regression in recent PrimeNG versions. Previously, these properties were specifiable. 

This PR appears to be the culprit, which adds keyboard accessibility for the sortIcon, but simultaneously removes the ariaLabel specification. Restoring `[attr.aria-label]=" sortOrder === 1 ? ariaLabelAsc : sortOrder === -1 ? ariaLabelDesc : '' "` should fix this issue. 
https://github.com/primefaces/primeng/commit/2928f6117fe458935a1a242ca5e884e10ddeb1b8#diff-fc10cdf52c8d5add93682bdd37ee3653

**Comment by eyassud** [comment]
I have the same issue.

**Comment by cagataycivici** [comment]
aria is moved to th element with pSortableColumn;

https://github.com/primefaces/primeng/issues/8684
