### ISSUE TITLE
Turbo Table Column Resize Is Ignored If Smaller Than minWidth [expand mode]

### ISSUE THREAD

**Issue by fhljys** [primefaces/primeng#8262]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
Set [style.minWidth] for a resizeable column
Try to resize the column to be narrower than its min-width
Result: resize is ignored, the column has the same width as before the resize.

There is a closed issue similar to this one. https://github.com/primefaces/primeng/issues/5937
But that only solved the issue in fit mode. The issue is still there in Expand mode. Can we fix expand mode as well? You can easily repro it even in the documentation

**Expected behavior**
The column should be resized to its min-width.

**What is the motivation / use case for changing the behavior?**
This behavior is not user friendly.

* **Angular version:** 5.X
7

* **PrimeNG version:** 5.X
7.10

**Comment by fhljys** [comment]
Any update on this?

**Comment by fhljys** [comment]
Any update?

**Comment by KimAlexander** [comment]
Still waiting for the solution
