### ISSUE TITLE
Counts of Items in Treetable are incorrect when using screenreader

### ISSUE THREAD

**Issue by ranjanmicrosoft** [primefaces/primeng#8263]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When tabbing through a p-treeTable, a screen reader will read that the table has one row regardless of how many rows it has. This happens because p-treeTable uses a separate table for the header and the rest of the content. 

**Expected behavior**
correct number of rows read by screenreader. 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Reproduces in Chrome/Edge using Narrator/Jaws/NVDA

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
