### ISSUE TITLE
p-multiSelect (onPanelHide) should be called if panel is open on component destroy

### ISSUE THREAD

**Issue by P3tronius** [primefaces/primeng#8264]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Currently, if the p-multiSelect component is opened, then (onPanelHide) is called when closing it.
If the component is embedded in a sidepanel for example, and the sidepanel destroy its content on close, then (onPanelHide) is not called on destroy if it was opened.

**Expected behavior**
(onPanelHide) should be called if component is opened before destroy.

**What is the motivation / use case for changing the behavior?**
It seems normal that the event would be called, as the multiSelect should be closed during destroy.

* **Angular version:** 8.X

* **PrimeNG version:** 8.0.3

* **Browser:** [all]
 
* **Language:** [TypeScript 3.4.5 | ES6]

* **Node (for AoT issues):** `node --version` =  v10.15.0

**Comment by cagataycivici** [comment]
Hide and destroy are different, hide is called when the user hides it, destroy removes it from dom.

**Comment by P3tronius** [comment]
Are you kidding me? If the panel is opened and being destroyed (for example because the route changes and the current component is destroyed), then it throws an undefined error.
So clearly this behaviour should be avoided.
And we are just talking about adding an if or two in the code here...
