### ISSUE TITLE
PrimeNG 8.1.0 Couldn't resolve resource ./carousel.css

### ISSUE THREAD

**Issue by 12Eddy12** [primefaces/primeng#8267]
After upgrade to 8.1.0 version got error:
"Couldn't resolve resource ./carousel.css relative to /build/node_modules/primeng/components/carousel/carousel.d.ts"

Angular 8.

**Comment by yigitfindikli** [comment]
Fixed https://github.com/primefaces/primeng/commit/3461b4570bd250a59a9b89c1ad41587f1f7c83c9 . Fixed for 8.1.1 and 8.1.1 available.
