### ISSUE TITLE
Filters column not working with srcollable and reorder 

### ISSUE THREAD

**Issue by jindovu** [primefaces/primeng#8270]
Hi Team,
      I have use p-table with filter reorder column but it's not working the control of top header always display behind rows data, I had set z-index for control (datepicker, dropdown) but it's not working,
Please help me resovle this issue, Thank you very much!
![image](https://user-images.githubusercontent.com/19401173/67466400-37d5b300-f671-11e9-9458-b6aa67811986.png)
![image](https://user-images.githubusercontent.com/19401173/67466438-491ebf80-f671-11e9-8df8-55093d403aa2.png)

**Comment by JacobSiegle** [comment]
You need to use appendTo="body".

**Comment by jindovu** [comment]
That's worked for me, Thanks
