### ISSUE TITLE
roles not defined for p-multiselect (accessibility issue)

### ISSUE THREAD

**Issue by ranjanmicrosoft** [primefaces/primeng#8274]
**Current behavior**
Role is not defined for the controls 'X' and 'Check box' present on the 'p-multiselect' flyout.

**Expected behavior**
1. Role should be defined as button for 'X'.
2. Role should be defined as checkbox for checkboxes

Effects programmatic accessibility of the control.

**Comment by yigitfindikli** [comment]
fixed in https://github.com/primefaces/primeng/issues/8439
