### ISSUE TITLE
change theme runtime

### ISSUE THREAD

**Issue by rajeshmuraleedharan** [primefaces/primeng#8277]
Is there way to change theme dynamically. Please let me know

**Comment by JacobSiegle** [comment]
In the primeng website demo you can go to a page and click the themes and see it swap. Clone primeng and see how it's done, as far as I know there's no doc that will tell you the exact steps you need to take. This is a question not an issue please consider closing or formatting it into a request.

**Comment by rajeshmuraleedharan** [comment]
thank you
