### ISSUE TITLE
ui-inputwrapper-filled is not removed when multi-select options are deseleced

### ISSUE THREAD

**Issue by markleppke** [primefaces/primeng#8279]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
When using `ui-inputwrapper-filled` to style inputs to highlight when a selection has been made, the class isn't removed when the input is no longer filled by the process of deselecting the option.

**Current behavior**
Select an option, then deselect. .ui-inputwrapper-filled still applies even though there is nothing "filled" in the input anymore

**Expected behavior**
.ui-inputwrapper-filled would no longer be present as the input is no longer filled out. 

**Minimal reproduction of the problem with instructions**
https://github-jmrqwa.stackblitz.io

Select an option, then deselect that option. 

**What is the motivation / use case for changing the behavior?**
To help make the multiselect more usable for filtering, having a "highlight" state to indicate if an option is selected helps a user see that this input has a value.

**Comment by yigitfindikli** [comment]
fixed in https://github.com/primefaces/primeng/commit/e136149662641f4fe25f8fca21d606fe643d6b62
