### ISSUE TITLE
Some image files are missing in PrimeNG 1.0.0-beta.14

### ISSUE THREAD

**Issue by cesarrew** [primefaces/primeng#828]
When I use primeng.min.css instead of primeui-ng-all.min.css, the browser complains that the files loading.gif, loadingbar.gif and rating.png are missing. I've checked in primeng/resources/images and these files are not there indeed.

**Comment by eddbog** [comment]
+1 here. btw, the theme switching is not working in the showcase application because of this issue.

**Comment by Provson** [comment]
+1
