### ISSUE TITLE
p-calendar should accept ISO 8601 formatted date strings

### ISSUE THREAD

**Issue by riorudo** [primefaces/primeng#8282]
**Current behavior**
Currently p-calendar accepts formatted strings or JavaScript date object as input but not ISO 8601 formatted strings. [See the example on stackblitz.](https://stackblitz.com/edit/github-p78je2?file=src%2Fapp%2Fapp.component.ts)

**Expected behavior**
p-calendar should accept ISO 8601 formatted date strings.
If the passed string can be parsed as a date can be checked as follow:
`!isNan(Date.parse('2019-11-11T00:00:00Z'))`

**What is the motivation / use case for changing the behavior?**
Getting a date from the backend in a ISO 8601 formatted string such as '2019-11-11T00:00:00Z' is a common use case. However, before this value can be passed to the p-calendar, it must be parsed or a date object must be created from it.

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Comment by Steven-Harris** [comment]
@riorudo, I believe my PR would handle this too

**Comment by nileshsoni1994** [comment]
Scenario 1  When you pass the new Date object.
![image](https://user-images.githubusercontent.com/31268978/129378575-6364a9b9-2f7c-4007-9f42-7005c7c7ba36.png)

Scenario 2 When you pass the same date string (ISO/JSON string) from the control.
![image](https://user-images.githubusercontent.com/31268978/129380307-16cb5420-c557-4d0e-b21e-ae8388507889.png)

Whereas, if go to the control source code, there is a "WriteValue" function where it is trying to convert the string to the date object. 

we tried various string formats but it is not working and this.value is becoming null for the control.

**Comment by nileshsoni1994** [comment]
the current scenario is tested in the PrimeNG hosted Stackblitz environment.
https://stackblitz.com/edit/primeng-calendar-demo?file=src%2Fapp%2Fapp.component.ts
Version: 
![image](https://user-images.githubusercontent.com/31268978/129381632-3f0448a0-bce5-49d1-9c9f-5925916b1610.png)

**Comment by davidboothe** [comment]
@cagataycivici you closed @Steven-Harris PR to add this. Is this still the plan to drop string support?

It's not super hard to convert dates I get from my API to Date(), but it would be really nice to pass a string in this format directly to calendar component since it's a pretty common date format.

**Comment by Triskae** [comment]
Same here too, our use case doesn't need time, so we want to only use string date to have date only ISO date string.
It would be really nice to add support of ISO date strings... 
Is it something planned in your side ?

**Comment by Triskae** [comment]
Same here, it would be nice to bring ISO string date support ... An API will give us an ISO string not a JS Date object ... We have to add new Date() everywhere we use p-calendar ...

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by penihel** [comment]
what about this?

**Comment by pit999** [comment]
It would be really beneficial to support this feature.
