### ISSUE TITLE
[p-table] editable table with formarray caused some problems

### ISSUE THREAD

**Issue by nuaamns** [primefaces/primeng#8284]

**Comment by nuaamns** [comment]
I'm using editable table with form and async validation.

`results` is a list from database.

`formarray` is initiate from this,results.

table data is from formarray.

when editing a cell and trigger save action, it will do form async validation. If the validation failed, all other fields cannot be edited anymore.

The real situation is much more difficult than my description. Is there any one has the similar problem?

**Comment by cagataycivici** [comment]
Please use forum for support requests and questions.

**Comment by aleq** [comment]
@nuaamns Can you share example of using p-table with reactive form (FormArray), I couldn't find any working solution so far.
