### ISSUE TITLE
Primeng Lazy Loading issue; event multi firing with `NAN` and `Infinity` as event.first value

### ISSUE THREAD

**Issue by dontboyle** [primefaces/primeng#8285]
**I'm submitting a ...**  (check one with "x")
```[x] bug report => Search github for a similar issue or PR before submitting
```
**Plunkr Case (Bug Reports)**
[stackBlitz_Example](https://stackblitz.com/edit/angular-8-primeng-virtscroll-not-working)

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
2. The lazy loading event parameter carries null values, and infinity value when at bottom of list

**Expected behavior**
event param not to carry nan/infinity values

**Please tell us about your environment:**

* **Angular version:** 8.0.0
* **PrimeNG version:** 8.1.1

* **Browser:** [Chrome XX (only tested here)]
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by dontboyle** [comment]
I wanted to note, my implementation works just fine using `<p-table>`

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
