### ISSUE TITLE
DataTable HTML id attribute

### ISSUE THREAD

**Issue by manosxviii** [primefaces/primeng#829]
Hi. Is there any way I can give my <p-dataTable> tag an html id attribute, so that the final html generated code has this id assigned to the table? thanks in advance.

**Comment by cagataycivici** [comment]
It could be possible, why do you need the id for?

**Comment by manosxviii** [comment]
I made it work by adding an id variable to the module. I'll post it when i make sure it works smoothly. I want to use a jquery plugin, witch requires the id attribute, in order to export the data table in excel and pdf.

**Comment by larsduelfer** [comment]
Would also be nice for testing tools using a WebDriver like Selenium etc. to identify a table column.

**Comment by rajhubgit** [comment]
I'm facing a similar issue. Need id attribute on the column header to automate testing related to sorting. Could you please post if there is any way to specify it?

**Comment by vsm** [comment]
We are using data tables in multiple places for different features. We need id's to differentiate the same. Is this "id" attribute is available to use. If yes, please suggest with an example.

**Comment by vsm** [comment]
Also, is it possible to define seperate row id's and cell id's in data table?

**Comment by cagataycivici** [comment]
Please create a separate topic like "id attribute for datatable" so we can track and implement these requests one by one.
