### ISSUE TITLE
Add autoDisplay to MenuBar and TieredMenu

### ISSUE THREAD

**Issue by nhnb** [primefaces/primeng#8293]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report (regression)
```

**Current behavior**

Moving the mouse above a menubar entry does not open the menu anymore.

**Expected behavior**

Moving the mouse above a menubar entry should popup the menu as it did in the past.

**What is the motivation / use case for changing the behavior?**

Restore the previous behavior because it made it easier for users to discover submenu entries.

* **PrimeNG version:** master  (regression from 8.0)

* **Browser:**
all 
 

The regression seems to have been introduced intentionally as part of issue #8256 and issue #8266

**Comment by tobymurray** [comment]
Adding on to this, approaching this from a developer perspective, it looks like it was deprecated in 8.1.0 and is now non-functional - "deprecated" is generally used to describe the process of discouraging the use of a feature, not removing it entirely. E.g. you deprecate functionality for some amount of time, then remove it some time later - this allows people making use of the work an opportunity to accommodate the deprecation. It also provides an opportunity for discussion about how to handle the deprecation. If "autodisplay" is intentionally no longer functional I personally find it misleading to describe it as "deprecated". 

Secondly, #8266 contains virtually no information and no associated commits, but it does link to #8214. Going to that ticket there is nothing indicating what's going on with "autodisplay" (other than it "should behave like their PrimeReact cousins", which is not something that means anything to me).

I know it's a lot of work to introduce documentation anywhere, but it's not clear how I (as a developer looking at PrimeNG) am supposed to use the project when I come across "deprecations" like this. There is effectively no information, so the status quo appears to be unexpected functional regressions from minor releases.

**Comment by esaesa** [comment]
Any alternative to open the menu on hover?

**Comment by cagataycivici** [comment]
autoDisplay is deprecated and removed in older versions.

**Comment by abashmak** [comment]
You should not simply close an issue when the ask is to provide parity with deprecated functionality. As mentioned in the request and follow up comment, there was no reason given for the deprecation, no warning period, and no alternative solution. Please address this issue properly, as it is preventing people from upgrading.

**Comment by armved** [comment]
+1 to @abashmak

**Comment by antsteyer** [comment]
Anybody found a workaround for this ?

**Comment by xinmoveware** [comment]
Would also like to know

**Comment by cagataycivici** [comment]
Due to popular demand, we'll reintroduce it for 10.0.4 and 9.x.

**Comment by MariemBADIS** [comment]
The same problem on version 9 primeNg. any one find a solution for this issues?
