### ISSUE TITLE
invalid stepMinute logic

### ISSUE THREAD

**Issue by sevenwind** [primefaces/primeng#8294]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template
component code:
<p-calendar formControlName="datetime" dateFormat="dd.mm.yy" showTime="true" hourFormat="24" [readonlyInput]="true" inputStyleClass="form-control" class="d-block" placeholder="Дата начала" stepMinute=5></p-calendar>

**Current behavior**

![image](https://user-images.githubusercontent.com/3108605/68028078-5e2ccb80-fccd-11e9-9850-66ca9d6905ff.png)
=>
![image](https://user-images.githubusercontent.com/3108605/68028096-671d9d00-fccd-11e9-88bb-ec0320123259.png)

**Expected behavior**

![image](https://user-images.githubusercontent.com/3108605/68028161-8fa59700-fccd-11e9-9c64-417ba00ae214.png)
=> 
![image](https://user-images.githubusercontent.com/3108605/68028168-959b7800-fccd-11e9-97e1-fe87a2da5b4b.png)

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Win10, vscode, npm

* **Angular version:** 8.X

* **PrimeNG version:** 8.1.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 78.0.3904.70
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5] typescript

* **Node (for AoT issues):** `node --version` = v10.15.3

**Comment by morula** [comment]
Look https://github.com/primefaces/primeng/issues/2058

You have to use [stepMinute]="5" instead of stepMinute=5

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template

**Comment by MJBGO** [comment]
Indeed, @morula's response solves the issue on my side
