### ISSUE TITLE
Virtual Drop Down Issue 

### ISSUE THREAD

**Issue by poosarla** [primefaces/primeng#8299]
When ever we focus on virtual drop down and click on up and down arrow , it is showing Error, u can see live error in your live PrimeNg Website itself.
![image](https://user-images.githubusercontent.com/17002856/68213987-93edef00-0002-11ea-8319-c868923da642.png)

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
