### ISSUE TITLE
Data Table Template footer don' workt

### ISSUE THREAD

**Issue by cyberrranger** [primefaces/primeng#830]
hy,

i use
`"primeui": "^4.1.15",
    "primeng": "^1.0.0-beta.14"`

one example from:
http://www.primefaces.org/primeng/#/datatable

> A template inside a column must be decorated with pTemplate directive along with the type property to indicate where the template belongs to. Possible values are "header", "body" and "footer".

work (type="header"):

 `<p-column>
    <template pTemplate type="header">
        <button type="button" pButton (click)="selectAllCars()" icon="fa-check"></button>
    </template>
    <template let-car="rowData" pTemplate type="body">
        <button type="button" pButton (click)="selectCar(car)" icon="fa-search"></button>
    </template>
</p-column>`

don't work :/ ( type="footer")
`<p-column>
    <template let-car="rowData" pTemplate type="body">
        <button type="button" pButton (click)="selectCar(car)" icon="fa-search"></button>
    </template>
<template pTemplate type="footer">
        <button type="button" pButton (click)="selectAllCars()" icon="fa-check"></button>
    </template>
</p-column>`

can somebody please help?

Patrick

**Comment by maleet** [comment]
Try this:
<p-column footer="true"> <template let-car="rowData" pTemplate type="body"> <button type="button" pButton (click)="selectCar(car)" icon="fa-search"></button> </template> <template pTemplate type="footer"> <button type="button" pButton (click)="selectAllCars()" icon="fa-check"></button> </template> </p-column>

**Comment by cyberrranger** [comment]
thy, is working

**Comment by maleet** [comment]
@cagataycivici Still would look better if this would be attribute on p-datatable
