### ISSUE TITLE
Issue in Carousel component. Click events or href does not work on touch on mobile devices

### ISSUE THREAD

**Issue by sukhminderx** [primefaces/primeng#8302]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**

I added a simple carousel component. In the content of the carousel, I added anchor tag with href that navigates to other website. In desktop, the click events work and the navigation is successful. But in mobile, the touch events work for slide process and the click for href is not executed.

**Expected behavior**

In mobile, if the content of the carousel contains the href, it should be navigate on the touch/click of the anchor /button.

**Minimal reproduction of the problem with instructions**

The app can be seen here:
https://llqiwwpyb.github.stackblitz.io/

**What is the motivation / use case for changing the behavior?**

There can be anchors or button in carousel content and mobile devices should execute the click events of the content.

**Please tell us about your environment:**

* **Angular version:** 8.X

8.X

* **PrimeNG version:** 8.X

8.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all. I did on chrome 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

* **Node (for AoT issues):** `node --version` =

**Comment by Eldrisch** [comment]
Hi, 
My team also encountered this problem. The problem lies here, in carousel.js:410:
```
Carousel.prototype.changePageOnTouch = function (e, diff) {
        if (diff < 0) {
            this.navForward(e);
        }
        else {
            this.navBackward(e);
        }
    };
```
Easiest way is to comment out if statements to remove defect and make carousel work properly.
Removal of this function requires to remove/change logic in Carousel.prototype.onTouchEnd method.

**Comment by sukhminderx** [comment]
@Eldrisch , will this work if I override the changePageOnTouch  in my code??

**Comment by Eldrisch** [comment]
> @Eldrisch , will this work if I override the changePageOnTouch in my code??

Yeah, should work, you can do it via ViewChild for exact element or just override whole prototype for every Carousel element in ngOnInit or constructor

**Comment by sukhminderx** [comment]
worked.. thanks! Closing this.

**Comment by biscuitboy** [comment]
Hi @sukhminderx , @Eldrisch, 

Can you please post an example for the fix provided? I am not sure how to "override" the changePageOnTouch() in my component.

P.S: I am new to Angular ecosystem. Thanks!

**Comment by tavadur** [comment]
Hello @biscuitboy,
try it this way:

`import {ElementRef, NgZone } from '@angular/core';
import { Carousel } from 'primeng/carousel';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent extends Carousel {

  constructor(public el:ElementRef,
    public zone: NgZone) {
    super(el,zone);
    Carousel.prototype.changePageOnTouch = (e,diff) => {}
}`

Hope this will help. :)

**Comment by MarcinListkowski** [comment]
@sukhminderx Could you please reopen? I know the issue is fixed for you, but it's still there for others to rediscover (IMO #8377 is a duplicate) and yet it somehow got into 9.0 changelog as fixed. @tavadur's code is a great workaround, I believe there is more that can be done.

**Comment by nimbusparis** [comment]
> Hello @biscuitboy,
> try it this way:
> 
> ```
> import {ElementRef, NgZone } from '@angular/core';
> import { Carousel } from 'primeng/carousel';
> 
> @Component({
>   selector: 'app-root',
>   templateUrl: './app.component.html',
>   styleUrls: ['./app.component.scss']
> })
> export class AppComponent extends Carousel {
> 
>   constructor(public el:ElementRef,
>     public zone: NgZone) {
>     super(el,zone);
>     Carousel.prototype.changePageOnTouch = (e,diff) => {}
> }
> ```
> 
> Hope this will help. :)

Could you detail what is there in the html template? I can't make it work

**Comment by murtuzamacdev** [comment]
> Hello @biscuitboy, try it this way:
> 
> ```
> import { ElementRef, NgZone } from '@angular/core';
> import { Carousel } from 'primeng/carousel';
> 
> @Component({
>   selector: 'app-root',
>   templateUrl: './app.component.html',
>   styleUrls: ['./app.component.scss']
> })
> export class AppComponent extends Carousel {
> 
>   constructor(public el:ElementRef,
>     public zone: NgZone) {
>     super(el,zone);
>     Carousel.prototype.changePageOnTouch = (e,diff) => {}
> }
> ```
> 
> Hope this will help. :)

This worked but now the swipe gesture on carousel is not working.

**Comment by xSentry** [comment]
For anyone wondering how to fix this without breaking the swiping of the carousel:

Use your Carousel with the CarouselModule as usual.
Import Carousel as well.
In the constructor set `Carousel.prototype.onTouchMove = (e) => {};`

A Code example with a standalone component would be:
```
import { Carousel, CarouselModule } from 'primeng/carousel';

@Component({
  selector: 'app-my-component',
  standalone: true,
  imports: [
    CarouselModule,
  ],
  templateUrl: './my-app.component.html',
  styleUrls: ['./my-app.component.scss']
})
export class MyComponent {
   constructor() {
    Carousel.prototype.onTouchMove = (e) => {};  //Overwrites function for all Carousels
  }
}
```

**Comment by pziacek** [comment]
In my case, none of the fixes mentioned worked. I needed to disable all touch events on the carousel.
This helped:

```
import { Carousel } from 'primeng/carousel';

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  standalone: false
})
export class AppComponent {
   constructor() {
    //Overwrites functions for all Carousels
    Carousel.prototype.onTouchStart = () => {};
    Carousel.prototype.onTouchMove = () => {};
    Carousel.prototype.onTouchEnd = () => {};   
  }
}
```

**Comment by pziacek** [comment]
It is possible to also use directive to target all carousel instances in the app. 
Create directive e.g. carousel-touch-fix.directive.ts 

```
import { Directive, Self, Optional, OnInit } from "@angular/core";
import { Carousel } from "primeng/carousel";

@Directive({
  selector: "p-carousel", // Targets all instances of p-carousel
  standalone: false
})
export class CarouselTouchFixDirective implements OnInit {
  constructor(@Self() @Optional() private carousel: Carousel) {}

  ngOnInit() {
    if (!this.carousel) return;

    // override onTouchStart of the carousel
    this.carousel.onTouchStart = (event) => {
      const INTERACTIVE_SELECTOR = 'button, a, img, div, input, select, textarea, [role="button"]';

      // Get the actual element that was touched (e.g., button)
      const target = event.target as HTMLElement;

      // Find the nearest "meaningful" interactive parent (or the element itself)
      const interactiveElement = target.closest(INTERACTIVE_SELECTOR) as HTMLElement;

      // If we found one, trigger the click
      if (interactiveElement) {
        interactiveElement.click();
      }
    };

    // Reassigning to an empty function kills the default internal logic
    this.carousel.onTouchMove = () => {};
    this.carousel.onTouchEnd = () => {};
  }
}
```

Then import it in the app.module.ts 

```
import { CarouselTouchFixDirective } from "./carousel-touch-fix.directive";

@NgModule({
  declarations: [
    ...
    CarouselTouchFixDirective
  ],
  imports: [],
  exports: [
    ....
    CarouselTouchFixDirective
  ]
})
```

This directive will be applied automatically to all carousel elements in the app. You don’t have to change your existing HTML code.
