### ISSUE TITLE
How to update defaultLabel dynamically in primeNg multiselect

### ISSUE THREAD

**Issue by praveenjm** [primefaces/primeng#8307]
someComponent.html

<p-multiSelect [options]="cities1" maxSelectedLabels=0 selectedItemsLabel="{0} 
items selected" [(ngModel)]="selectedCities1"></p-multiSelect><div *ngFor="let city in selectedCities1 let i=index">
   <button (click)="delete(i)">{{city}}</button>
</div>

someComponent.ts
delete(i){
  //using splice method to remove item from selectedCities1 array
}
Question is when I select and unselect from dropdown I am able to see the output like "1 item selected" "2 item selected" etc and vice-versa.

But when I do it from delete function I can unselect dropdown but unable to update the defaultLabel with "1 item selected" "2 item selected" etc and vice-versa.

**Comment by cagataycivici** [comment]
Please use forum for support requests and questions.
