### ISSUE TITLE
Why I am getting dates also while using Month only picker

### ISSUE THREAD

**Issue by tmtanzeel** [primefaces/primeng#8309]
`<button type="text" pButton label="Basic" (click)="op.toggle($event)"></button>

    <p-overlayPanel #op>
        <div id="comp-render" name="fieldName" ngDefaultControl>
            <div class="all-container">
                <p>Time selection</p><br>
                <div class="ui-g-12 ui-md-4">
                    <p-calendar view="month" dateFormat="mm/yy" [yearNavigator]="true" yearRange="2018:2022" [readonlyInput]="true" placeholder="Year-to-date"></p-calendar>
                </div>
                <br>
                <div class="custom-control custom-switch">
                <input type="checkbox" class="custom-control-input" id="customSwitches">
                <label class="custom-control-label" for="customSwitches">Comparing</label>
                </div>
                <br>
                <p-dropdown [options]="cities1" [(ngModel)]="selectedCity1" ></p-dropdown>
                <br><br>
                <div>
                    <p-calendar view="month" dateFormat="mm/yy" [yearNavigator]="true" yearRange="2018:2022" [readonlyInput]="true" placeholder="Previous Year-to-date"></p-calendar>
                </div>
            </div>
        </div>
    </p-overlayPanel>`

**Comment by dinohorvat** [comment]
Resolved on [Stackoverflow](https://stackoverflow.com/questions/58873996/why-i-am-getting-dates-also-while-using-month-only-picker-primeng/58875089#58875089).

The OP was using PrimeNG v5 which does not support this feature.

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.
