### ISSUE TITLE
The Choose button of the file upload component has wrong title in advanced mode when file is selected.

### ISSUE THREAD

**Issue by andrush001** [primefaces/primeng#8310]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
The title of the Choose button says "No file chosen" even though I did choose a file.

**Expected behavior**
No title, or on other message or make it configureable

**Minimal reproduction of the problem with instructions**
The bug is reproducable in primeng showcase: https://www.primefaces.org/primeng/#/fileupload
(Primeng 8.1.0)
![Annotation 2019-11-12 085106](https://user-images.githubusercontent.com/14335021/68652804-8e286a00-052a-11ea-8637-1f4c253946a3.jpg)

* **PrimeNG version:** 5.X
8.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Tested on: Google Chrome  78.0.3904.97 (Official Build) (64-bit)

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/issues/7957
