### ISSUE TITLE
Site Example X Github Example (table/export)

### ISSUE THREAD

**Issue by evertonbatini** [primefaces/primeng#8316]
Site: https://www.primefaces.org/primeng/#/table/export

columns: any[];
...
this.exportColumns = this.cols.map(col => ({title: col.header, dataKey: col.field}));

Example on github is OK

**Comment by infroger** [comment]
Where is exportColumns defined? Didn't find it in documentation.

**Comment by evertonbatini** [comment]
![image](https://user-images.githubusercontent.com/46816210/72443882-c8fa8880-378d-11ea-8b77-07fcacebe365.png)

**Comment by evertonbatini** [comment]
should be:

exportColumns: any[];
...
this.exportColumns = this.cols.map(col => ({title: col.header, dataKey: col.field}));
