### ISSUE TITLE
Extra space for simple header compared to p-header

### ISSUE THREAD

**Issue by Marooned-MB** [primefaces/primeng#8317]
I'm using accordion in my project with both - simple header (1) and template header (5). Unfortunately, simple header (1) [and one version of template header (2)] renders additional space between chevron and the text. For template header it's usually some complex HTML or custom components so it renders without this space. However, there is no way to trim that when using simple header.
This is due to the fact that simple header is done in [3 separate lines](https://github.com/primefaces/primeng/blob/e234008c77300966ee82b7ab8ea507d7125bf845/src/app/components/accordion/accordion.ts#L18):
```html
<span class="ui-accordion-header-text" *ngIf="!hasHeaderFacet">
   {{header}}
</span>
```

One possible solution would be to make it less readable but without those extra spaces:
```html
<span class="ui-accordion-header-text" *ngIf="!hasHeaderFacet">{{header}}</span>
```
Adding `display: inline-block` to `.ui-accordion-header-text` and `p-header` also looks like fixing this issue, maybe in a more elegant way. Not sure if that won't break anything. (I'm using it currently as a workaround)

**Current behavior**
```html
<p-accordion>
  <p-accordionTab header="(1) Simple header [extra space]">
    Lorem
  </p-accordionTab>
  <p-accordionTab>
    <p-header>
      (2) Template header [extra space]
    <p-header>
    Ipsum
  </p-accordionTab>
  <p-accordionTab>
    <p-header>(3) Template header [no extra space]<p-header>
    Dolor
  </p-accordionTab>
  <p-accordionTab>
    <p-header><span>(4) Template header  [no extra space]</span><p-header>
    Sit
  </p-accordionTab>
  <p-accordionTab>
    <p-header>
      <span>(5) Template header [no extra space]</span>
    <p-header>
    Amet
  </p-accordionTab>
</p-accordion>
```
and it renders like this:
![obraz](https://user-images.githubusercontent.com/716018/68772604-5f91b880-062a-11ea-8937-b41d6573493a.png)

**Expected behavior**
Consistent header no matter how it was provided.

* **Angular version:** 7.2.11

* **PrimeNG version:** 7.1.x

* **Browser:** Chrome 76

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
