### ISSUE TITLE
Radiobutton and checkox label template

### ISSUE THREAD

**Issue by rafa-suagu** [primefaces/primeng#8318]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
There are no options to templatize the radiobutton and checkbox label

**Expected behavior**
Have an option to templatize the radiobutton and checkbox label

**What is the motivation / use case for changing the behavior?**
Sometimes you want to add some link or span inside the label to apply styles or create an anchor.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by cetincakiroglu** [comment]
Hi,

We apologize for the delayed response. Our team began implementation for accessibility with version 16.5x and successfully completed the accessibility implementation with version 16.9.1 after intensive work and meticulous study. The mentioned issue might have been resolved between these versions. If the problem persists in PrimeNG v17, please feel free to open a new issue without hesitation.

Thanks for reporting the issue!
