### ISSUE TITLE
Dialog height

### ISSUE THREAD

**Issue by codehunter13** [primefaces/primeng#8319]
Hi ,

i dont get dialoag height working.

Directly from your documentation and adjusting height to 800px:
```
<p-dialog header="Title" [(visible)]="isVisible" [resizable]="true" [style]="{width: '300px', height: '800px'}">
  Content
</p-dialog>
```

Height is not 800px but just contains the content?

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
