### ISSUE TITLE
Multiple Custom Sort for columns

### ISSUE THREAD

**Issue by ibtisamniche-vteams** [primefaces/primeng#8321]
Hi! I have upgraded my project to angular8 and primeng too. There was a requirement in my project to apply multiple custom sort on table columns. Like for sorting column A there was a function A and for sorting column B there was a function B. I want to achieve the same functionality with primeng version 8 but unfortunately I couldn't found something like that in new documentation. 
How can I achieve this functionality to add multiple sort functions associated with multiple columns.
Looking forward to answer.
Thanks.

**Comment by cagataycivici** [comment]
Please use forum for support requests and questions.
