### ISSUE TITLE
Delete deprecated components

### ISSUE THREAD

**Issue by yigitfindikli** [primefaces/primeng#8328]

**Comment by Da13Harris** [comment]
I didn't realize the Toast was going to lead to deprecating the Growl. Did I miss documentation about this on the PrimeNG website somewhere? We use the Growl throughout our production system, so hopefully the Toast will snap in easily without too much refactoring.

**Comment by jdhunt** [comment]
- Issues regarding deprecated components can be found in the[ PrimeNG change log](https://github.com/primefaces/primeng/blob/master/CHANGELOG.md) or by searching through [PrimeNG issues list](https://github.com/primefaces/primeng/issues).

- It was announced that Growl would be removed after PrimeNG 8 in this issue: [Deprecate Growl #6156](https://github.com/primefaces/primeng/issues/6156). 

- It was also mentioned in the announcement for the [PrimeNG 6.0.2 Release](https://www.primefaces.org/primeng-6-0-2-released/).

**Comment by Da13Harris** [comment]
Thanks for the links. I must have just missed it when I read the announcement for 6.
