### ISSUE TITLE
TreeView select doesn't work with filtering

### ISSUE THREAD

**Issue by viktor-mezhenskyi** [primefaces/primeng#8329]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://llqiwwpyb.github.stackblitz.io
https://stackblitz.com/edit/github-jzd9ly

**Current behavior**
Console log  contains message _Documents Folder_

**Expected behavior**
Console log should contains message
_Invoices for this month_

**Minimal reproduction of the problem with instructions**

1) Filter by 'Home'
2) Collapse Home
3) Select Invoices.txt

**What is the motivation / use case for changing the behavior?**
It is a very common case when you need to use selection with filtering

**Please tell us about your environment:**
Local environment, Windows, node.js, IDE:Visual studio code

* **Angular version:** 8.0

* **PrimeNG version:** "8.1.1"

* **Browser:** all 
 
* **Language:** [all]

**Comment by dmitry-moscow** [comment]
it worked the same way for me until I did not set a unique key for each node, which, I suppose, is not a bug, but an intended behavior, just not documented well

hope this helps

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
