### ISSUE TITLE
Update to RC6

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#833]
Update dependencies to RC6

**Comment by ammar91** [comment]
what is an ETA for beta 15?
Also, can we update to Angular RC6 before beta 15?

**Comment by edoardoVD** [comment]
@ammar91 
I guess nope.... your last question (can we update to Angular RC6 before beta 15?)
I get this once my app loads on the browser

`metadata_resolver.js:230Uncaught Error: Unexpected value 'MenuModule' imported by the module 'AppModule'`

**Comment by cagataycivici** [comment]
beta15 is due early next week, we'll start the update today and I'll have more information about share. From the changelog I read, we shouldn't have too much troubles.

**Comment by Svrkota-S** [comment]
Thanks for giving us a time frame, cagataycivici.

**Comment by cagataycivici** [comment]
All seems to be fine now after today's changes.

**Comment by LukeNZ** [comment]
How can I use & build the current beta.15 snapshot in my app? Including it from source doesn't include the output.

**Comment by jhoncue7** [comment]
@cagataycivici with beta 15 completed do you think you will be able to push beta.15 soon?

**Comment by edoardoVD** [comment]
@jhoncue7 

https://www.npmjs.com/package/primeng
Running angular RC6 and primeng beta 15 with no problems so far

**Comment by edoardoVD** [comment]
@ammar91, @jhoncue7 , @LukeNZ 

https://www.npmjs.com/package/primeng

Running angular RC6 with primeng beta 15, all good
