### ISSUE TITLE
The mitiselect  And the Dropdown components filter in the Chrome V49 not surpport Chinese

### ISSUE THREAD

**Issue by wqj1991** [primefaces/primeng#8330]
## source code:
```
<div class="ui-multiselect-filter-container" *ngIf="filter">
  <input #filterInput type="text" role="textbox" [value]="filterValue||''" (input)="onFilter()" class="ui-inputtext ui-widget ui-state-default ui-corner-all" [attr.placeholder]="filterPlaceHolder" [attr.aria-label]="ariaFilterLabel">
  <span class="ui-multiselect-filter-icon pi pi-search"></span>
</div>
```

## new code:
```
<div class="ui-multiselect-filter-container" *ngIf="filter">
  <input #filterInput type="text" role="textbox" [value]="filterValue||''" (keyup)="onFilter()" class="ui-inputtext ui-widget ui-state-default ui-corner-all" [attr.placeholder]="filterPlaceHolder" [attr.aria-label]="ariaFilterLabel">
  <span class="ui-multiselect-filter-icon pi pi-search"></span>
</div>
```
Aftet I changed the input event to keyup event, the filter working right.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
