### ISSUE TITLE
MultiSelect Filter not working when selecting Inputs Randomly (TurboTable)

### ISSUE THREAD

**Issue by vamsibandarupalli** [primefaces/primeng#8332]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
When tried to filter the turbo table with multiselect filter, It's not working as expected. Where Colors column is an array of strings and p-multiselect is using filterMode 'contains'. 

https://stackblitz.com/edit/angular-turbotable-filter

**Current behavior**
When filtering the turbo table by selecting 'Silver, Maroon, Red' in this order it is filtering and giving only one row as expected. But when changed the order of selection like, 'Maroon, Red, Silver' it is not giving the expected row.

**Expected behavior**
Independent of selection order table should filter if the items are there in the array.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.X
Angular 8.2.14

* **PrimeNG version:** 5.X
PrimeNG 8.1.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
