### ISSUE TITLE
Dynamic dialog doesn't open after a drag event

### ISSUE THREAD

**Issue by directcuteo** [primefaces/primeng#8333]
I have a list of components. Each component has a button that will open a dynamic PrimeNG `p-dynamicdialog`. The dialog opens using the open() method:
```
const ref = this.dialogService.open(NewItemComponent, {
      header: 'New'
    });
```
These components are draggable and sortable (I am doing this using `SortableJS`). After an item is being dragged, the button of that item will no longer open the dialog, but somehow the dialog waits for the next `tick()` (or something) and it will open when I do another drag (I guess this is triggering some movement which awakes the dialog?). 
I point out that I triggered `changeDetectorRef.detectChanges()` on the drag's end event (or in the onClick() function right before opening the dialog) but seems that I can't wake it up.
The function applied to the `(click)` event is executed but the dialog is not shown...

```
onClick() {
    console.log('open dialog');  /* <- This is actually printed! */
    const ref = this.dialogService.open(NewItemComponent, {
      header: 'New'
    });
    ref.onClose.subscribe((componentName: string) => {
     //on close
    });
  }
```

The result that I have when the dialog is not shown:
![image](https://user-images.githubusercontent.com/37619567/69032770-f0c7ad00-09e5-11ea-9d8b-a28d830a4b2d.png)

 I am facing this on all browsers, Angular 8, Windows 10 and Detection Strategy is not configured, so it's the default one.

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
