### ISSUE TITLE
Tooltip flickering

### ISSUE THREAD

**Issue by csvinhal** [primefaces/primeng#8335]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
It can be simulated on PrimeNG showcase, so I didn't create a stackblitz.
![tooltip_flickering](https://user-images.githubusercontent.com/5657910/69084149-63ef1480-0a22-11ea-819c-44a6ed66bab9.gif)

**Current behavior**
When mouse hover on input border the input starts to flicker not showing the tooltip. It only happens using tooltip with hover event and it can be simulated on PrimeNG showcase.

**Expected behavior**
When mouse hover on input border it should open tooltip and don't flicker.

**Minimal reproduction of the problem with instructions**
It can be simulated on PrimeNG showcase doing the same as the gif above.

* **Angular version:** 8.X
* **PrimeNG version:** 8.1.1

* **Browser:** Chrome 78.0.3904.97

**Comment by r1x3l** [comment]
We have had the same problem within table cells. It seems that an equal issue existed already in primefaces (https://github.com/primefaces/primefaces/pull/2373).


Adding "pointer-events" to the CSS should fix the problem:
```
ui-tooltip {
  pointer-events: none;
}
```

**Comment by csvinhal** [comment]
That worked to me, thank you @r1x3l. I also submitted one PR to correct this issue to everyone.  #8505

**Comment by ajsaraujo** [comment]
I still get this error when using tooltip on `pButton`.
