### ISSUE TITLE
Improvements to existing carousel 

### ISSUE THREAD

**Issue by quekqh** [primefaces/primeng#8336]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Thanks for adding in the carousel for primeng! It looks splendid. However, I've realised that the dots spill over to the next line in web responsive view.  So let's say if there are 20 images or more, there would probably be a long paragraph of dots at the bottom of the carousel. 

![image](https://user-images.githubusercontent.com/12732739/69120016-5ba2e200-0ad3-11ea-96ed-c1279fb23541.png)

Would it be possible to introduce a swipe function for the dots such that only 5 are shown at a time (for example) and if the user would like to view more dots, he/she could swipe to the right?

Appreciate your help!

**Comment by mertsincan** [comment]
Hi @quekqh,

Thanks a lot for your feedback. I think you can do it. The carousel is fully customizable. Please try;
```
...
        @ViewChild('customcarousel', { static: false }) carouselEl: Carousel;

	onPage(e) {
		let activeEl = this.carouselEl.el.nativeElement.querySelectorAll('.ui-carousel-dot-item')[e.page];

		if (activeEl) {
			activeEl.scrollIntoView({behavior: 'smooth', block: 'nearest'});
		}
	}
...

/* CSS */
       @media (max-width: 560px) { /* the mobile breakpoint is 560px in our demo */
		.custom-carousel .ui-carousel-dots-container {
			justify-content: flex-start;
			-ms-flex-wrap: nowrap;
			flex-wrap: nowrap;
			overflow-x: scroll;
			overflow-y: hidden;
			padding: .1em;
			width: 125px;
			justify-self: center;
			align-self: center;
		}
	}
```

```
<p-carousel #customcarousel [value]="cars" styleClass="custom-carousel" .../>
```

Best Regards,
