### ISSUE TITLE
Virtual Scroll table doesn't load when scrolling quickly

### ISSUE THREAD

**Issue by boarder2** [primefaces/primeng#8338]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
N/A, happens on the examples at https://www.primefaces.org/primeng/#/table/scroll

**Current behavior**
![Screen-Recording-2019-11-19-at-1 31 43-PM](https://user-images.githubusercontent.com/19351/69184436-192cd580-0ad2-11ea-8483-58e02356d8ee.gif)

**Expected behavior**
Data should load

**Minimal reproduction of the problem with instructions**
Grab scrollbar, scroll down quickly then back up and release scrollbar

**Browser:** [Chrome 78, 79 | Chromium Edge 80 ]
Didn't test any others

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
