### ISSUE TITLE
Add option to hide autocomplete dropdown when visible

### ISSUE THREAD

**Issue by MetallIdea** [primefaces/primeng#8343]
**I'm submitting a ...**
```
[ X ] bug report
[ ] feature request
[ ] support request
```

**Plunkr Case (Bug Reports)**

https://www.primefaces.org/primeng/#/autocomplete

**Current behavior**
Autocomplete component with dropdown='true'
When i first click on dropdown icon overlay is open.
Second click on dropdown icon not hide overlay menu.

**Expected behavior**
Second click on dropdown icon hide overlay.

**Minimal reproduction of the problem with instructions**

* **Angular version:** 8.2.11

* **PrimeNG version:** 8.0.4

* **Browser:** all
 
* **Language:** TypeScript

**Comment by IronGremlin** [comment]
FWIW, I am also experiencing this issue -

I don't think this is a bug though, it seems like the component was not designed to do this. But it'd solve some problems for my project if there was an option to configure this behavior.

**Comment by cagataycivici** [comment]
This intended but an option could be added to make it customizable.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
