### ISSUE TITLE
Allow external template for p-paginator's page links and navigation 

### ISSUE THREAD

**Issue by sunnyyadav100** [primefaces/primeng#8344]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Allow external `ng-template` for pagination links and navigation. https://github.com/primefaces/primeng/blob/master/src/app/components/paginator/paginator.ts#L17-L36 

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.X

8.2.7

* **PrimeNG version:** 5.X

8.0.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Thank you for the feedback however due to lack of demand from the community to this we've decided not to proceed, if there is more demand in the future, we'll reconsider.
