### ISSUE TITLE
Provide option to show table summary at top in TuroTable

### ISSUE THREAD

**Issue by sunnyyadav100** [primefaces/primeng#8345]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Provide an option/flag to show table summary at the top in TuroTable
https://github.com/primefaces/primeng/blob/master/src/app/components/table/table.ts#L99-L100

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.X

8.2.7

* **PrimeNG version:** 5.X

8.0.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
In TurboTable you have full control over the representation so you may choose to display it on top depending on your row templating.
