### ISSUE TITLE
p-dropdown requires two clicks on options when options array is dynamic

### ISSUE THREAD

**Issue by antialiasis** [primefaces/primeng#8346]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-md1pfk

**Current behavior**
When the options property for a p-dropdown is a dynamic value (e.g. a dynamically filtered version of some list stored on the component), and we set the optionLabel and dataKey options, clicking an option in the dropdown will not actually select the option. (In my actual app it just doesn't work at all and completely breaks the dropdown; in this minimal test case, it seems to work if I click the option again, but that's still clearly abnormal behaviour.) If I don't use optionLabel and dataKey, the same dropdown with the same dynamic options works fine.

**Expected behavior**
Items should be selected normally.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/github-md1pfk

Click the upper dropdown with a mouse and try to select an item. It doesn't do anything until you click it again.

**What is the motivation / use case for changing the behavior?**
This is obviously buggy.

**Please tell us about your environment:**
See the Stackblitz link.

* **Angular version:** 8.0.3

* **PrimeNG version:** 8.1.1

* **Browser:** Tested in Chrome and Firefox on Mac.

* **Language:** TypeScript

**Comment by Mysame** [comment]
Every time Angular's change detection runs (on hover, click, ...), it re-runs the `dynamicOptions()` function, and re-populated the options. 
In essence, what you clicked, no longer exists.
This shouldn't be something Prime "needs" to "fix", as it's expected behavior, and and bad-practice.

**Comment by antialiasis** [comment]
@Mysame I know that it reruns the dynamicOptions() function; that's why it's dynamic. I'm not buying this as an explanation for the current behaviour. It should be perfectly possible to have simple things that are calculated dynamically in a component, and given it already works fine if I just don't use optionLabel and dataKey, I'm definitely not buying that it's "expected behaviour" that it doesn't work if I do.

My actual real-world use case is that I want the dropdown to not include items that have previously been selected. It's a filter operation with a single simple condition, on a list that's going to contain maybe a dozen items at the most. Am I supposed to be keeping two separate lists on the component, one from my data source including all the items and one without the already-selected ones, and manually do the work of keeping this completely redundant second list in sync when either the items or the selection change, just so that Angular won't have to run a dead-simple, lightning-fast filter operation on a dozen items when it runs change detection? That's ridiculous.

**Comment by crystalized2** [comment]
this bug does not cater only to dynamic options, even regular options dont work with change detection in angular and not only p-dropdown, p-menu as well...

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
