### ISSUE TITLE
Row grouping summary on Table

### ISSUE THREAD

**Issue by radharamana** [primefaces/primeng#8353]
It seems the old datatable had a row summary and now the new table component doesn't
![image](https://user-images.githubusercontent.com/7437734/69548896-e76bb100-0fa0-11ea-9bce-6fe51fc0c16c.png)
[https://github.com/primefaces/primeng/issues/403](url)

**Comment by cagataycivici** [comment]
You can implement it with p-table as well as you have full control over markup.

https://www.primefaces.org/primeng/#/table/rowgroup
