### ISSUE TITLE
p-dropdown: events fired are strange and inconsistent

### ISSUE THREAD

**Issue by antialiasis** [primefaces/primeng#8355]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr case (bug reports))**
https://stackblitz.com/edit/github-md1pfk-prqg79

**Current behavior**
Right now, the `onChange` event of the p-dropdown component fires _every time the user highlights a new item_ with the keyboard. This seems counterintuitive, since merely highlighting a new item does not indicate the user actually intends to select it, and seems to make the behaviour of the dropdown inconsistent between mouse and keyboard users. In order to do something when the user has actually selected a value, this can be gotten around by using the `onHide` event rather than `onChange`, but this seems a silly workaround.

Meanwhile, the `onBlur` event simply fires all over the place, with no relation to when the user is actually unfocusing the component; clicking the dropdown to open it when it is already focused will fire onBlur for some reason, as well as any time an option is clicked with a mouse to select it. This makes it impossible to use the onBlur event for any useful purpose.

**Expected behavior**
Either the `onChange` event should fire for keyboard users only when they actually select the item (this seems more sensibly equivalent to clicking and selecting an item with the mouse), or (probably more reasonable for backwards compatibility) there should be some other event that fires only when the user has made an actual selection and not when they merely highlight a new item.

The `onBlur` event should only fire when the user actually unfocuses the component. I can't imagine how the current implementation of this event could possibly be useful to anyone.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/github-md1pfk-prqg79

**What is the motivation / use case for changing the behavior?**
I am creating a dynamic form where a dropdown is created and focused when an element is clicked, allowing the user to select a different item. The dropdown should then be hidden again (with the new value saved) when the user makes a selection or clicks away. This would be easy to achieve with a regular HTML select element and its onChange and onBlur events, but has been a huge headache with primeng.

* **Angular version:** 8.0.3

* **PrimeNG version:** 8.1.1

* **Browser:** Tested in Chrome and Firefox on Mac.
 
* **Language:** TypeScript

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
