### ISSUE TITLE
I am facing version mismatch for which i am not able to do "Ng Serve"

### ISSUE THREAD

**Issue by devz14** [primefaces/primeng#8361]
**Please tell us about your environment:**
Windows 10 64 bit

* **Angular version:** 5.X
8.X

* **PrimeNG version:** 5.X
8.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES

**"Error Code in Terminal"**

You seem to not be depending on "@angular/core" and/or "rxjs". This is an error.

**Comment by cagataycivici** [comment]
Please use forum for questions and support requests.
