### ISSUE TITLE
Custom sort on multiple column support in missing in primeNG 8

### ISSUE THREAD

**Issue by ibtisamniche-vteams** [primefaces/primeng#8362]
Hi!
I'm posting this issue again by hoping that this would be addressed asap.
I'm using p-table in angular 8 application and previously when I was on older versions I was using the p-datatable with multiple columns sort with different functions associated to different columns for sorting, but now I can't see that functionality with primeNG 8. I'm using this in a live application so please let me know how can I achieve that functionality again?

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
