### ISSUE TITLE
p-messages styleClass being ignored

### ISSUE THREAD

**Issue by sonicwong** [primefaces/primeng#8365]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
p-messages styleClass being ignored
<p-messages [(value)]="msgs" styleClass="myclass"></p-messages>

**Expected behavior**
myclass class added to child element.

**Please tell us about your environment:**

* **Angular version:** 8.2.13

* **PrimeNG version:** 8.1.1

* **Browser:** all
 
* **Language:** TypeScript

* **Node (for AoT issues):** `node --version` =   12.7.0

DOM:
<a href="https://ibb.co/SN5q6vN"><img src="https://i.ibb.co/SN5q6vN/2019-12-06-12-02-49.png" alt="2019-12-06-12-02-49" border="0"></a>

**Comment by yigitfindikli** [comment]
styleClass added to ui-message div.

**Comment by sonicwong** [comment]
@yigitfindikli Did you give a try before close my issue?
As I already post a capture of dom.
There are no "style class" copy to ui-message div.

**Comment by sonicwong** [comment]
<a href="https://ibb.co/nQ744mq"><img src="https://i.ibb.co/NW9ffCg/ng.jpg" alt="ng" border="0"></a>
