### ISSUE TITLE
Tree table with lazyload filters 

### ISSUE THREAD

**Issue by jindovu** [primefaces/primeng#8373]
Hi Everyone,
    I use tree-table with lazyload and filters for my project, but the filters not working when I keyin on text search or dropdownlist, and when I clear some text it's throw exception I captured bellow, 
doesn't those working well?

![image](https://user-images.githubusercontent.com/19401173/69925365-618cc000-14e2-11ea-9ae9-8ad4d509b48a.png)

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
