### ISSUE TITLE
Calendar input field width with showIcon

### ISSUE THREAD

**Issue by MassiveHiggsField** [primefaces/primeng#8385]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/ngx-formly-ui-primeng-wpgu3i

**Current behavior**

There is no way to only make the input of the calendar span 100% of the width without affecting the calendar size. Also, the icon ruins any relative width size. 

**Expected behavior**

If i set inputStyle to width:100%, the input should span 100% width but the calendar should not be affected. Also 100% with showIcon=true should incorporate the width of the icon.

**Minimal reproduction of the problem with instructions**

https://stackblitz.com/edit/ngx-formly-ui-primeng-wpgu3i

**What is the motivation / use case for changing the behavior?**

Setting the input to 100% width.

Thanks in advance.

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
