### ISSUE TITLE
problem grid grouping & paging

### ISSUE THREAD

**Issue by malkaGed** [primefaces/primeng#8387]
I have a grouped table and I need to have 10 rows per page.
The problem sometimes appears 2 or three lines
Because it does not compute the ungrouped rows as part of the rows on the page
How do I do I have 10 rows grouped on each page, each of which can have several rows that are hidden
![image](https://user-images.githubusercontent.com/48654245/70515591-45220080-1b3e-11ea-9d0c-c601ebfcf339.png)

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.
