### ISSUE TITLE
How to show files in p-fileupload when I am getting files data from API 

### ISSUE THREAD

**Issue by Sankey28** [primefaces/primeng#8388]
I'm submitting a feature request

**Current behavior**
I have created a file attachment model like 
{ name: string;
    type: string;
    size: string;
    content: string;
    metadata: Metadata[] = [];}
From API I am getting content, objectURL which I am storing files on azure.

**Expected behavior**
I would like to show files in ngFor having 1 p-fileupload controls per row.

**Minimal reproduction of the problem with instructions**
No implementation can be provided. Customer specific code.

**What is the motivation / use case for changing the behavior?**
Multiple file-upload controls per row and should be used to show uploaded files in uploaded itself.

**Please tell us about your environment:**
OS: Windows 10,
Angular-Cli : 1.7.4
* **Angular version:** 5.2.11

* **PrimeNG version:** 5.2.7

* **Browser:** all
 
* **Language:** all

* **Node (for AoT issues):** `node --version` =   v10.15.3

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.
