### ISSUE TITLE
Highlight matching text in tree table when using filter

### ISSUE THREAD

**Issue by zkBounty** [primefaces/primeng#8392]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Minimal reproduction of the problem with instructions**
Entering text in the pInputText box in tree table results in the rows being filtered accordingly, but no indication of where in the row the text exists.

**What is the motivation / use case for changing the behavior?**
Filtering in tree table is very useful, but can be made better by highlighting the matching text in the rows that match the text being filtered over, instead of showing the entire row in the same font color.

**Please tell us about your environment:**

* **Angular version:** 8.X

* **PrimeNG version:** 8.X

* **Browser:** [all ]

 
* **Language:** [all]

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
