### ISSUE TITLE
FrozenColumns on the Right Side

### ISSUE THREAD

**Issue by divyachandana** [primefaces/primeng#8393]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**

showing frozen column in left side of the table

**Expected behavior**

I should be able to froze column at right side of table

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

I just want stick action buttons edit/delete icons there and let other columns flow

**Please tell us about your environment:**

* **Angular version:** 8.0

* **PrimeNG version:** 6.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   12.13.1

**Comment by wederer** [comment]
I would second this feature. We want to build a column with Actions similar to Jira.
This is currently not possible with the primeNG table as far as I can tell.
I could post a pull request, but am unsure how best to implement it.

Probably here?
https://github.com/primefaces/primeng/blob/6ab7223b3b214c87f71ebcd5a40e7b6dca004d18/src/app/components/table/table.ts#L93

**Comment by BhupathiGaddam** [comment]
We also need the same behavior that needs to show the frozen action column always right to the table:

**Current behavior**
When we try to set the freeze option to any column of the table, then it is trying to set the freeze column always left of the table and making the frozen column as the first column of the table.

**Expected behavior**
Wanted to set the freeze option to the last column(action column) of the table and whenever we set the freeze option to the last column, then it should always show right to the table as a last column.

**Comment by danbord** [comment]
I'd also like to see that feature

**Comment by jamendub** [comment]
Me too !
I would love to see this.
I'll try to make a suitable workaround for my needs.
If I succeed I'll share it here and / or try to create a pull-request, if I have enough time

**Comment by DevFlash33** [comment]
i had the Problem too, i just figured an easy way with scss 
`:host ::ng-deep .p-datatable {
    .p-datatable-scrollable-wrapper {
      display: flex;
      flex-direction: row-reverse;
      .p-datatable-scrollable-view.p-datatable-unfrozen-view {
        position: initial;
      }`
     the only problem you will have, that you need to set the height on the td and th to archive the same layout with the standard table

**Comment by norbeqr89** [comment]
Hi, this solution work for me. The stick value for position is similar to fixed and relative. So you can use this for fix in the hrizontal scroll but not in vertical in this case.

```
.p-datatable .p-datatable-scrollable-body td:last-child{
    background: #fff;
    position: sticky;
    position: -webkit-sticky;
    position: -moz-sticky;
    position: -ms-sticky;
    position: -o-sticky;
    right: 0;
}
```

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
