### ISSUE TITLE
TypeError: Cannot set property scrollHeight of [object Element] which has only a getter

### ISSUE THREAD

**Issue by mledour** [primefaces/primeng#8394]
**I'm submitting a ...** 
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
I'm having this error when testing with jest when trying to pass variable to `p-treeTable` `scrollHeight` property:

`TypeError: Cannot set property scrollHeight of [object Element] which has only a getter` 

It work when passing a string: `scrollHeight="300px"`but fail when passing `[scrollHeight]="height"` or even `scrollHeight="{{'300px'}}"`.

**Expected behavior**
`p-treeTable` `scrollHeight` input should work with variable when testing.

* **Angular version:** 
8.X

* **PrimeNG version:** 5.X
8.X

* **Browser:**
all 

* **Language:**
TypeScript 3.5
Jest 24.9

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.

**Comment by vemareddy** [comment]
Still I am getting above issue
<img width="740" alt="Capture" src="https://user-images.githubusercontent.com/14240028/126334873-6f89c415-9c51-4271-b886-421ac51c4a00.PNG">

**Comment by CodersExpo** [comment]
Was there ever a fix or work around for this. I get the same thing in test runner Karma v 6.3.4.

**Comment by aironhight** [comment]
Guys, you have to import the table module (in my case it was the 'DropdownModule') in your .spec file.
