### ISSUE TITLE
Primeng breaks new Angular 9 project

### ISSUE THREAD

**Issue by mehmet-erim** [primefaces/primeng#8396]
```
[x] bug report
[ ] feature request
[ ] support request
```
Angular version: 9.0.0-rc.6
Primeng version: 9.0.0-rc.2

I created a new Angular 9 project and installed the `primeng` package with the following command:
```
yarn add primeng
```
Primeng has been installed with 9.0.0-rc.2 version. Is it a problem right? Why rc version comes as default? 

After, I imported the some modules to `AppModule` like this:
```ts
import { TableModule, ToastModule, CalendarModule } from 'primeng';
@NgModule({
  ...
  imports: [BrowserModule, AppRoutingModule, TableModule, ToastModule, CalendarModule],
  ...
```

I ran the `yarn start` and I faced an error as shown below:

```
ERROR in The target entry-point "primeng" has missing dependencies:
 chart.js
```

I installed the chart.js with following line and then I ran `yarn start` again.
`yarn add chart.js`

Then, I faced an error again

```
ERROR in The target entry-point "primeng" has missing dependencies:
 quill
```

I installed the quill and then ran the project again.

Occurred an error again.

```
ERROR in The target entry-point "primeng" has missing dependencies:
 @fullcalendar/core
```

Installed `@fullcalendar/core` and that was it. No more error...

**Comment by piotrbrzuska** [comment]
Did you use in your project some charts, calendar or Rich Text Editor ?

**Comment by mehmet-erim** [comment]
> Did you use in your project some charts, calendar or Rich Text Editor ?

No, I didn't. It was a new project reproduction.

**Comment by jackoliveira** [comment]
Hello, @mehmet-erim

I have tested on this version.
Angular version: ~9.0.0-rc.7
Primeng version: ^9.0.0-rc.2

the imports from _"primeng"_ or _"primeng/primeng"_ were **deprecated**, so, please use like below

`import { TableModule } from "primeng/table";`
`import { ToastModule } from "primeng/toast";`
`import { CalendarModule } from "primeng/calendar";`

**Comment by mehmet-erim** [comment]
Thanks @jackoliveira

**Comment by daddyschmack** [comment]
As a note, if you import the primeNG components into your component(s), ensure that the path is correct, Webstorm doesn't include the entire path with auto-import

**Comment by kuriel-trivu** [comment]
what about this message?

> ERROR in The target entry-point "primeng" has missing dependencies:
>  - @fullcalendar/core

we not ussing fullcalendar module/component.

How can we solve it?

**Comment by spelbreker** [comment]
full calender error in https://github.com/fullcalendar/fullcalendar-angular/issues/270

**Comment by jespergothe** [comment]
I think it feels a bit dirty to include things you do not use. But the dependencies are actually mentioned here: https://primefaces.org/primeng/#/setup

**Comment by FabienDehopre** [comment]
It seems this error occurs during the Ivy compatibility compiler phase (ngcc).
Ngcc pre-compile all the entry points of primeng and complains about missing dependencies of each one:
- primeng/chart
- primeng/fullcalendar
- primeng/editor

```
Compiling primeng/chart : es2015 as esm2015
Compiling primeng/fullcalendar : es2015 as esm2015
Compiling primeng/editor : es2015 as esm2015
Compiling primeng : es2015 as esm2015
```

**Comment by 09walido** [comment]
npm install chart.js --save

**Comment by xeleoss** [comment]
How do I make WebStorm use long paths? and the automatic imports lead to this error!

**Comment by x3igh7** [comment]
> How do I make WebStorm use long paths? and the automatic imports lead to this error!

this might do it:
![forbid_import](https://user-images.githubusercontent.com/3804066/81122695-0f1f5780-8ef7-11ea-83f9-1452a16355a9.png)

**Comment by Naono** [comment]
I got the same error. And I found
`import {SelectItem} from 'primeng';`
in my code. The problem is "from 'primeng';". The correct code should be "from 'primeng/api'".

**Comment by Azemoten** [comment]
@Naono Did you find solution for this bug ?

**Comment by Naono** [comment]
@Azemoten I don't know, there is nothing need to import from 'primeng', and we should think primeng is a folder, every module is a standalone plug-in, it's good for improving packaging performance and just need to install one package. but the IDEs follow the export structure and find the shortest.

**Comment by bjansen** [comment]
@x3igh7's answer is almost correct, to force IntelliJ/WebStorm to ban `import { xxx } from 'primeng'`, you should go to "File | Settings | Editor | Code Style | **TypeScript**" and add `primeng,primeng/public_api` to the "Do not import exactly from" list.

Now automatic imports will be like `import {TableModule} from "primeng/table";`

**Comment by wsimf** [comment]
I think there still is an issue when trying to use `DynamicDialog`
My imports are:
```typescript
import {DialogModule} from 'primeng/dialog';
import {DynamicDialogModule} from 'primeng/dynamicdialog';
import {ButtonModule} from 'primeng/button';
import {TooltipModule} from 'primeng/tooltip';
import {InputTextModule} from 'primeng/inputtext';
import {DropdownModule} from 'primeng/dropdown';
import {TableModule} from 'primeng/table';
```

but I still get
> ERROR in The target entry-point "primeng" has missing dependencies:
>  - chart.js
