### ISSUE TITLE
github sample code needs cleaning 

### ISSUE THREAD

**Issue by msinghm** [primefaces/primeng#8397]
to see the issue plz check [link](
https://github.com/primefaces/primeng/blob/master/src/app/showcase/components/table/tablesortdemo.html)

Refer screenshot too
![prieng_1](https://user-images.githubusercontent.com/45700566/70813833-2a76b280-1df0-11ea-99b9-4e9391055d89.JPG)

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
