### ISSUE TITLE
InnerHTML causing the XSS vulnerability in Messages

### ISSUE THREAD

**Issue by yigitfindikli** [primefaces/primeng#8398]
> I’m viewing messages from the server with MessageService. If this message contains html tags, MessageService displays it as html. This causes the XSS vulnerability.

**Comment by gurshafriri** [comment]
Hi Yiğit, I couldn't find your contact details. Can you please contact me at gur.shafriri@snyk.io, regarding this issue? 
Thanks, Gur from Snyk.
