### ISSUE TITLE
Turbo Table : Fix row hover and row selection highlight with row groups

### ISSUE THREAD

**Issue by samdidos** [primefaces/primeng#8402]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Stackblitz Case (Bug Reports)**
https://stackblitz.com/edit/primeng-turbo-table-fofmd3

**Current behavior**

Multiple selection mode : Selection by clicking on the grouped element select only the first row of the related row stack.
![issue-primeng-select-1st](https://user-images.githubusercontent.com/7490081/70941050-99831f80-2019-11ea-8ab0-0bc295c8f3d9.png)

Both selection modes : Selection by clicking on a single element from a related row stack (except the first one) doesn't highlight the grouped element.
![issue-primeng-current-select-2nd](https://user-images.githubusercontent.com/7490081/70940672-d995d280-2018-11ea-8f5f-bf1510c589f4.png)

**Expected behavior**
Multiple selection mode : Selection by clicking on the grouped element must select *all rows* of the related row stack.
![issue-primeng-selectall](https://user-images.githubusercontent.com/7490081/70941091-b881b180-2019-11ea-9172-3a3344687917.png)

Both selection modes : Selection by clicking on a single element from a related row stack (except the first one) must highlight the grouped element.
![issue-primeng-expected-select-2nd](https://user-images.githubusercontent.com/7490081/70941120-c6cfcd80-2019-11ea-925f-40bbcec198c7.png)

**What is the motivation / use case for changing the behavior?**
UX : Feels like the row isn't selected properly.

**Please tell us about your environment:**
* **Angular version:** 7.0.0^

* **PrimeNG version:** 7.0.0^ (also tested on 9.0.0-rc.2)

* **Browser:** [all]
 
* **Language:** [TypeScript]

* **Related issue** : https://github.com/primefaces/primeng/issues/3184

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9.0.5, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
