### ISSUE TITLE
Inputmask autoclear, but formcontrol still holds the invalid value

### ISSUE THREAD

**Issue by kk1687** [primefaces/primeng#8404]
**Current behavior**
< p-inputMask > with reactive form control, mask is set to have a*9999. Whenever a value out of the mask scope is entered and focus is moved, as autoclear is set by default the field will be cleared off. But the thing is if the form is submitted, the value is getting packed in the rawValue of the form.

**Expected Behavior**
Here as the field is cleared, the model also should be updated so as the form value.

** fix **
line#540 inputmask.ts
#add 
this.updateModel(event);

Windows10
Angular 6
typescript 2.9.2

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
