### ISSUE TITLE
Table - edited cell not closed properly

### ISSUE THREAD

**Issue by lf-novelt** [primefaces/primeng#8405]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/github/parigzjjo (see console output)

**Current behavior**
`onRowEditComplete` is not reliable.
![primetable-onrowedit-bug](https://user-images.githubusercontent.com/46479127/70991961-ef62d080-20c8-11ea-9b9c-18e2cf10359b.gif)

**Expected behavior**
Should display a log `onRowEditComplete` right after a cell loses focus, not only if Enter key is pressed.

**Minimal reproduction of the problem with instructions**
Click on any cell to edit it, then **click** on another one, the onEditComplete event is not triggered

**What is the motivation / use case for changing the behavior?**
More consistent behavior, improved change detection in table

**Please tell us about your environment:**

* **Angular version:** 5.X

* **PrimeNG version:** 9.0.0-rc2

* **Browser:** all

### Proposed fix 
Line to fix
https://github.com/primefaces/primeng/blob/76efe8e83f71e2fe1507eca8e869cd8c939f213a/src/app/components/table/table.ts#L3089

should call `this.closeEditingCell()` instead to properly trigger all actions related to edited cells.

Else `onEditComplete` in never called when you change edited cell using the mouse rather than pressing `Enter`

**Comment by bobbydowling** [comment]
Possible workaround for now:

``` HTML
<ng-template pTemplate="body" let-item>
     <tr>
          <td pEditableColumn>
               <p-cellEditor>
                    <ng-template pTemplate="input">
                                 <input (blur)="save({ data: item })"
                                 (keydown.tab)="save({ data: item })"
                                 (keydown.enter)="save({ data: item })">
     ....
</ng-template>
```

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9.0.5, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
