### ISSUE TITLE
Feature to select a whole month, year and week with one click

### ISSUE THREAD

**Issue by swagner30** [primefaces/primeng#8406]
**I'm submitting a feature request** 

In the (inline) date-view of the calender component I would like to be able to select an entire week, every monday of a month, a whole year or a month with just one click. 

Maybe by adding click-listeners on week numbers, month names and year display

**Comment by cagataycivici** [comment]
If more users demand it, we'll consider this, thank you.

**Comment by waratah** [comment]
I created a date range component and added buttons that I wanted below the prime  date range component which set my range.   This works well.   Although the buttons I want are pretty simple ie:  this month,  last month,   today

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
