### ISSUE TITLE
[Feature request] Attribute to disable mask on dialogs

### ISSUE THREAD

**Issue by misterjaffacakes** [primefaces/primeng#8413]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**What is the motivation / use case for changing the behavior?**

I have the situation where I generate a Dynamic Dialog when clicking on an item. The size of the generated dialog covers the whole body of the application, but not the header and footer. So the header and footer, which are behind the dialog, are still visible, but covered by the mask.

Right now there is no way to disable the mask.

* This feature should be available on all dialogs: Dialog, ConfirmDialog, Dynamic Dialog.

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9.0.5, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
