### ISSUE TITLE
Calendar getting focus

### ISSUE THREAD

**Issue by chravikishore** [primefaces/primeng#8415]
I am using PrimeNG controls in my project. After upgrade to 8.xxx I am facing a problem with calendar control used with in focus trap. I am using calendar control and editable grid with in a focustrap directive. When I tabbed in editable grid, focus is going to calendar control and calendar is showing up then coming to respective cell in editable grid. I have created a sample stackblitz for reproducing the issue.
https://stackblitz.com/edit/primeng-calendar-focus?embed=1&file=src/app/app.component.html

**Comment by yigitfindikli** [comment]
fixed in https://github.com/primefaces/primeng/commit/ea9596bf6831270a708633be0a40aadecf92ff15
