### ISSUE TITLE
Datatable Performance Issues for 10000+ records in IE only

### ISSUE THREAD

**Issue by sathishkumarsivalingam** [primefaces/primeng#8420]
**Current behavior**
Browser took long time to load 10000+ records in IE but not in chrome

**Expected behavior**
Would expect to load the data table minimal time as it works in chrome

**Minimal reproduction of the problem with instructions**

 $(document).ready(function () {
            
            if ($.fn.DataTable.isDataTable("#itemWebGrid")) {
                $('#mytable').DataTable().clear().destroy();
            }
            
            $("#itemWebGrid thead").find("tr:gt(0)").remove();
            
            $('#itemWebGrid thead tr').clone(true).appendTo('#itemWebGrid thead');
            
            $('#itemWebGrid thead tr:eq(1) th').each(function (i) {
                var title = $(this).text();
                if (i != 0) {
                    $(this).html('<input type="text" style="width:100%; font-size:11px;" placeholder=" ' + title + '" />');
                }
                else {
                    $(this).html('<input type="text" style="display:none; width:100%; font-size:11px;" placeholder=" ' + title + '" />');
                    $(this).removeClass('sorting_asc');
                }
                $('input', this).on('keyup change', function () {
                    if (table.column(i).search() !== this.value) {
                        table.column(i).search(this.value, true, false, true).draw();
                    }
                });
            });
            
            var table = $('#itemWebGrid').DataTable({
                deferRender: true,
                orderCellsTop: true,
                fixedHeader: true,
                search: false
            });
        });

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Visual studio 2017

* **Angular version:** 5.X
N/A

* **PrimeNG version:** 5.X
N/A

* **Browser:** [all | IE 11
 
* **Language:** [all | MVC, asp.net, DataTables 1.10.18 js

**Comment by cagataycivici** [comment]
Invalid issue ticket.
