### ISSUE TITLE
Dropdown requires optionLabel for arbitrary collection even when item display is customized

### ISSUE THREAD

**Issue by daleclements** [primefaces/primeng#8423]
This is on the line between a bug report and a feature request

In a dropdown, the optionLabel must be specified in order to use a non-SelectItem collection of options even when the display is customized with templates.

It's not a big deal, but I would not expect the optionLabel to be necessary in order to use an arbitrary option collection as long as the display of the options is being controlled by templates.

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-fwhheb

**Comment by johnmanko** [comment]
Either it's a bug, or it's usage is undocumented.  For those running into this, the items will be of the format:

```
{
  label: 'Some Label',
  value: { /* This is your object */  }
}
```

So, referencing the object in the template:

```html
<p-dropdown [options]="cars" optionLabel="name">

  <ng-template let-car pTemplate="item">
      {{car.value.name}}
  </ng-template>

  <ng-template let-car pTemplate="selectedItem">
      {{car.value.name}}
  </ng-template>
</p-dropdown>
```

@daleclements Thanks for that example.  Helped a lot.

**Comment by cagataycivici** [comment]
optionValue will clear this up.

https://github.com/primefaces/primeng/issues?q=is%3Aissue+is%3Aopen+optionValue

9.1.0 will include improvements.
