### ISSUE TITLE
fix document

### ISSUE THREAD

**Issue by vankiemthanh001** [primefaces/primeng#8426]
Dynamic Dialog

import {DialogService} from 'primeng/api';
I think it must be:
import { DialogService } from 'primeng/dynamicdialog/dialogservice';

**Comment by vankiemthanh001** [comment]
sr

**Comment by LeanKhan** [comment]
When I do that I am getting a `Module not found: Error: Can't resolve 'primeng/dynamicdialog/public_api' in...`
DialogService is not found in `primeng/api` what did you manage to do?

**Comment by vankiemthanh001** [comment]
import { DialogService } from 'primeng/dynamicdialog';

Vào Th 6, 3 thg 1, 2020 vào lúc 16:27 LeanKhan <notifications@github.com>
đã viết:

**Comment by LeanKhan** [comment]
Thank you! It works now 👍
