### ISSUE TITLE
p-toast hideTransitionOptions is not working

### ISSUE THREAD

**Issue by maurice85** [primefaces/primeng#8427]
The p-toast fades in nicely but it does not show the fade-out animation when the p-toast (automatically) closes. It just simply disappears. I tried forcing this behaviour by setting 
hideTransitionOptions explicity in the <p-toast> tag, but that doesn't alleviate the problem. I don't have any special settings or overrides. On the primeng example page for p-toast the fade-out animation works nicely so its not a browser related issue. I am working with Angular 9 RC7 and primeng version ^9.0.0-rc.2

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9.0.5, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
