### ISSUE TITLE
Cannot import DialogService 

### ISSUE THREAD

**Issue by LeanKhan** [primefaces/primeng#8430]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.
Here is the link to a reprodcution:
https://stackblitz.com/edit/github-xz82dx-m9xgk3

**Current behavior**

There is no exported member called `DialogService` in `primeng/api`. I can;t import DialogService from `primeng/api`

**Expected behavior**

I expect to import `DialogService` from `primeng/api` like it says in the docs

**Minimal reproduction of the problem with instructions**
Please just check this Stackblitz code inside the open.component.ts, I am getting an error when trying to import `DialogService` how do I import it please?

**What is the motivation / use case for changing the behavior?**
I can't use DynamicDialogs without it

**Please tell us about your environment:**
Windows 10,
VSCode
NPM

* **Angular version:** 5.X
Angular 8

* **PrimeNG version:** 5.X
PrimeNG 8
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by LeanKhan** [comment]
`Import { DialogService } from primeng/dynamicdialog` 
 #8426 

Should really be in the documentation tbh

**Comment by asifbherani** [comment]
import { DialogService } from 'primeng/dynamicdialog';
