### ISSUE TITLE
P-table - Column Resize Issue in 'expand' Mode

### ISSUE THREAD

**Issue by rhtvma** [primefaces/primeng#8432]
- columnResizeMode="expand"
 - Table Min-Width 100% [say 1200px] -  and we don't want to reduce the table width while shrinking the column size.

Issue : while shrinking column size p-table is misbehaving {assigning dynamic width to random columns}

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9.0.5, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
