### ISSUE TITLE
[Table] defaultSortOrder should be configurable per-column

### ISSUE THREAD

**Issue by earshinov** [primefaces/primeng#8434]
**I'm submitting a ...**

[ ] bug report
[x] feature request
[ ] support request

This is a follow-up to https://github.com/primefaces/primeng/issues/4199.

New data tables still do not provide per-column default sort order.

**StackBlitz**

https://stackblitz.com/edit/primeng-table-defaultsortorder-per-column

**What is the motivation / use case for changing the behavior?**

@miguelleite gave a nice example in https://github.com/primefaces/primeng/issues/4199#issuecomment-337592610:

> As a use case, consider the following:
> I have a table with 3 columns: cars, rating and co2 emissions. On the first click on:
>
> * cars th, I want the column to be sorted in ascending order, alphabetically;
> * co2 emissions th, I want the column to be sorted in ascending order, because the less emissions, the better, and therefore, more relevant;
> * rating th, I want the column to be sorted in descending order, because the higher the ranking, the better, and therefore, more relevant.
> 
> Right now this is impossible to achieve.

**Applicability**

* PrimeNG version: 8.1.1 (applies to 9.x RCs as well)
* Browser: all
* Angular version: all
* Language: all

**Comment by cagataycivici** [comment]
Duplicate #4199

**Comment by earshinov** [comment]
But that ticket was closed on the assumption that this feature would be available in p-table... :-(

**Comment by denversynchro** [comment]
Can we reopen this ticket? I agree with @earshinov's comment that this feature is not in p-table.

**Comment by earshinov** [comment]
@denversynchro , if you need this, I would recommend filing a new ticket. Chances for this one being reopened look slim.

**Comment by waltzonice** [comment]
Can we reopen this ticket? The "Duplicate #4199" that @cagataycivici  referenced is for the old datatable, not the p-table. That ticket was closed with the assumption that the feature will be in p-table, but it is not.
