### ISSUE TITLE
Fire onNodeExpand of Tree after DOM update

### ISSUE THREAD

**Issue by mcherb** [primefaces/primeng#8435]
```
[x] feature request
```
**What is the motivation / use case for changing the behavior?**
I want to get the `getBoundingClientRect` of the expanded node.

**Current behavior**
`onNodeExpand` is fired before the view terminates expanding => I get wrong informations by calling `getBoundingClientRect` I have to wait some milliseconds before asking for the dimentions.

`tree.onNodeExpand.pipe(delay(100)).subscribe(/*...*/)`

**Expected behavior**
I want to write to code without the pipe by introducing a new event `onNodeExpanded`

`tree.onNodeExpand.subscribe(/*...*/)`

**Please tell us about your environment:** 
ubuntu, intellij
* **Angular version:** 7.1
* **PrimeNG version:** 7.1
* **Browser:** [all | Chrome XX | Firefox XX | 
* **Language:** [all | TypeScript 3.1.6]
* **Node (for AoT issues):** `node --version` =   10.15.0

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
