### ISSUE TITLE
Angular Ivy issue with PrimeNG Components (UIChart, RadioButton, Slider, Tooltip and Table) During ng build --prod

### ISSUE THREAD

**Issue by faheemj** [primefaces/primeng#8437]
![PrimeNg Angular Ivy issue](https://user-images.githubusercontent.com/59648302/71973654-76711780-3235-11ea-89d4-771584f18180.png)

Using PrimneNg 9.0.0-rc.2 version 

ERROR in No suitable injection token for parameter 'el' of class 'UIChart'.
no type or decorator

ERROR in No suitable injection token for parameter 'cd' of class 'RadioButton'.
no type or decorator

ERROR in No suitable injection token for parameter 'el' of class 'Slider'.
no type or decorator

ERROR in No suitable injection token for parameter 'el' of class 'Tooltip'.
no type or decorator

ERROR in Node does not exist: E:/prodv20/node_modules/primeng/table

**Comment by kodze** [comment]
Same issue when trying to serve angular app with ivy enabled !

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9.0.5, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
