### ISSUE TITLE
Improve reactive form support for Table Cell Editing

### ISSUE THREAD

**Issue by DuffyScottC** [primefaces/primeng#8438]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When you insert a `p-table` element within an Angular reactive form's `form` element, you must specify a `formControlName` value for the `p-table`'s cell editing feature to work. 

**Expected behavior**
I would expect to be able to edit the cell without having to link it to the form by specifying a `formControlName` for the cell editor's `input` template. Adding other sorts of inputs (not cell editor templates) works fine, and they serve their purpose even if they have no `formControlName` attribute. 

**Minimal reproduction of the problem with instructions**
This is my stackblitz project demonstrating the issue. There is no debug output, only faulty results. 
[https://stackblitz.com/github/parigzjjo](https://stackblitz.com/github/parigzjjo)

In case that didn't work, here is a bare-bones implementation:

If you do not include a `formControlName` attribute, as in **Case 1** in the code below (note the lack of a `formControlName` on line 23 of `app.component.html`). 

**app.component.ts**
```typescript
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder } from '@angular/forms';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent implements OnInit {

  projectForm: FormGroup;
  cars = [
    {data: "edit me" },
  ];

  constructor(private fb: FormBuilder) {}

  ngOnInit() {
    this.projectForm = this.fb.group({
      //this dummy FormControl must be added for the workaround, which I will describe later
      dummy: ['', []],
    });
  }
}
```

**app.component.html**
```html
<form *ngIf="toggle" [formGroup]="projectForm" (onSubmit)="onSubmit()">
  <p-table [value]="cars">
    <ng-template pTemplate="header">
        <tr>
            <th>Data</th>
        </tr>
    </ng-template>
    <ng-template pTemplate="body" let-rowData>
        <tr>
            <td pEditableColumn>
                <p-cellEditor>
                    <ng-template pTemplate="input">
                      <!-- There is no "formControlName" attribute -->
                        <input pInputText type="text" [(ngModel)]="rowData.data">
                    </ng-template>
                    <ng-template pTemplate="output">
                        {{rowData.data}}
                    </ng-template>
                </p-cellEditor>
            </td>
        </tr>
    </ng-template>
</p-table>
</form>
```

- When you click to edit any cell, the "input" template displays a blank `<input/>` element (e.g. an empty textbox) as opposed to displaying a textbox with the words "edit me" in it.
- When you edit the cell, the changes are not kept, and the `cars` list is not changed.

In order to work around this issue, you must add a `formControlGroup` to the input textbox. I've set it equal to the dummy FormControl here:

```html
<input pInputText formControlName="dummy" type="text" [(ngModel)]="rowData.data">
```

With this single change, the edit feature works. you can click inside the cell and change the data, and that change is persisted and reflected in the `cars` array.

*Note: Even with the workaround, submitting the form does not fill the FormGroup with the cell's data. Instead, the value for `dummy` is listed as null.*

**What is the motivation / use case for changing the behavior?**
If this behavior were changed, then you could include an editable table within an angular reactive form without having to work around and create dummy values. Also, angular and primeng are depreciating the ability to use a `formControlName` in the same element as an `[(ngModel)]`. This means that soon the workaround will not be valid, and you will be unable to have an editable form within an angular reactive form. 

**Please tell us about your environment:**
The environment has little-to no impact on this. I was working on linux, but the same issue happened when I replicated it on stackblitz, which is platform agnostic (just to be sure, I ran it on a different computer). 

* **Angular version:** 8

* **PrimeNG version:** 8

* **Browser:** Chrome | Safari
 
* **Language:** TypeScript

* **Node (for AoT issues):** `node --version` =   10

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by Picoquio** [comment]
From the documentation alone, it seems impossible (or way too complicated) to use this funcionality with reactive forms. This sure could do with some improvement

**Comment by jayyren** [comment]
Defintely missing feature, I can't use formControlName properly when rendering table with checkboxes (p-tableCheckbox)
