### ISSUE TITLE
Editor component documentation is confusing/incorrect

### ISSUE THREAD

**Issue by hhubik** [primefaces/primeng#844]
I am trying to customize the Editor toolbar.  If I follow the instructions in the Documentation, I end up with this code, which does not work (the bold and italic buttons do not show up on the editor):

```
<span class="ql-format-group">
       <span title="Bold" class="ql-format-button ql-bold"></span>
        <span title="Bold" class="ql-format-button ql-italic"></span>
</span>
```

If I copy the code I see in the "Source" tab in the Editor documentation, like this

```
<span class="ql-format-group">
     <button class="ql-bold"></button>
      <button class="ql-italic"></button>
</span>
```

This code seems to work. The editor shows with the bold and italic button.  However, the code is not valid HTML(5) as the span element is not supposed to contain button elements.

Please fix the documentation so that it shows only one (the correct) way for customizing the toolbar.

**Comment by cagataycivici** [comment]
New docs should clear this up
