### ISSUE TITLE
Multiple Lists Feature for PickList

### ISSUE THREAD

**Issue by sarwin-github** [primefaces/primeng#8441]
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

We're trying to customize the picklist [**(see sample)**](https://picklist-tst.herokuapp.com/) for our Angular project such as:

- Modify the styling of picklist items
- Adding a border to the source list and target list
- Hiding all buttons and filters 

However, we encountered a limitation. 

Is it possible for a picklist to have multiple sources and a single target? Let's say I have 2 sources and 1 target where the user can select from source_1 and source_2 while sharing 1 target  [**(see screenshot)**](https://prnt.sc/ql5b2e) ?

If it's not available it would be a nice feature to have.

**What is the motivation/use case for changing the behavior?**
- To allow a user to select from multiple sources or target when using picklist

- PrimeNG version: 9.X

- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All

- Language: [all | TypeScript X.X | ES6/7 | ES5]
All

**Comment by mkmeric** [comment]
Any update?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
