### ISSUE TITLE
Table Horizontal scroll  is FAULTY

### ISSUE THREAD

**Issue by HalaSalameh** [primefaces/primeng#8445]
When i copy the code for the table horizontal scroll exactly as it is written in the tutorial, the table scrolls the body and not the header of the body with it, which is totally unacceptable.
please give me a solution.

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9.0.5, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
