### ISSUE TITLE
Multiple property doesn't work on PanelMenu submenu items. 

### ISSUE THREAD

**Issue by gmerabishvili** [primefaces/primeng#8446]
**Current behavior**
I use  ```<p-panelMenu [multiple]="false"></p-panelMenu>``` but it doesn't work for submenu items and always multiple submenu items are activated at the same time. How can I fix this issue asap please?

**Expected behavior**
 Control multiple submenu items to be activated at the same time or not. Currently "multiple" property works only for parent menu items.

**Comment by cagataycivici** [comment]
It is by design, only works on root.
