### ISSUE TITLE
Carousel SSR broken

### ISSUE THREAD

**Issue by rafa-as** [primefaces/primeng#8447]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
I can't do the Plunkr because is a SSR related issue.

**Current behavior**
SSR build are broken because the carousel access to window and document objects.

document
carouse.ts: 288 and 290

window
carouse.ts: 337, 605 and 611

**Expected behavior**
SSR works properly

**Minimal reproduction of the problem with instructions**
Add carousel with responsiveOptions to app and build for SSR.

**What is the motivation / use case for changing the behavior?**
Make SSR builds works.

* **Angular version:** 8.2.9

* **PrimeNG version:** 8.1.1

* **Browser:** all
 
* **Language:** all

**Comment by rafa-as** [comment]
@cagataycivici some news here?

**Comment by nitedani** [comment]
The carousel works for me, I'm using domino to define the window object on the server. There is another issue with the carousel though. On the server render, the following style is missing:
```
        .p-carousel-item {
          flex: 1 0 100%;
        }
```
It causes the carousel content to jump around once the javascript has downloaded and the style is applied.
Adding these lines to the scss fixes the issue for me.
