### ISSUE TITLE
Maximized `p-dialog` not calculating height correctly (truncated content) on iOS Safari

### ISSUE THREAD

**Issue by KeithGillette** [primefaces/primeng#8449]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://www.primefaces.org/primeng/#/dialog

**Current behavior**
`p-dialog` footer content is cut off when maximizing a `p-dialog` on iOS Safari unless the application is a PWA running in `standalone` mode, as demonstrated on these screenshots of an iPhone 8 running iOS 13.3 under Simulator:

***Auto (footer buttons shown)***
![Screen Shot 2020-01-14 at 12 57 26](https://user-images.githubusercontent.com/19915029/72369187-8ffadf00-36cd-11ea-961e-1544b3556748.png)
***Maximized (footer buttons truncated)***
![Screen Shot 2020-01-14 at 12 57 42](https://user-images.githubusercontent.com/19915029/72369210-9d17ce00-36cd-11ea-9871-22dd72d83a31.png)

**Expected behavior**
`p-dialog` footer content should be visible on all browsers when `p-dialog` is maximized.

In limited testing with dialogs appended to the body, the following overrides correct the sizing issue:
```scss
.ui-dialog-maximized {
	height: 100% !important;

	.ui-dialog-content {
		height: calc(100% - 116px) !important;
	}
}
```

**Minimal reproduction of the problem with instructions**

1. Visit the [PrimeNG Dialog Demo](https://www.primefaces.org/primeng/#/dialog) on an iOS device (or Simulator) using Safari
2. Press the _Show_ button
3. Maximize the dialog

**What is the motivation / use case for changing the behavior?**

Access maximized `p-dialog` footer content from iOS Safari clients.

**Please tell us about your environment:**
Tested under iOS 12.4 & iOS 13.3 on iPhone 6 & iPhone 8

* **Angular version:** N/A

* **PrimeNG version:** N/A

* **Browser:** [iOS 12.4 & 13.3 Safari]

 
* **Language:** [N/A]

* **Node (for AoT issues):** N/A

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
