### ISSUE TITLE
Update Input Control Value Accessors to RC5+ forms

### ISSUE THREAD

**Issue by mko** [primefaces/primeng#845]
Old format of custom input control value accessor creation:

``` typescript
const CUSTOM_INPUT_CONTROL_VALUE_ACCESSOR: Provider = new Provider(NG_VALUE_ACCESSOR, {
    useExisting: forwardRef(() => CustomInputComponent),
    multi: true
});
```

New format of custom input control value accessor creation:

``` typescript
export const CUSTOM_INPUT_CONTROL_VALUE_ACCESSOR: any = {
    provide: NG_VALUE_ACCESSOR,
    useExisting: forwardRef(() => CustomInputComponent),
    multi: true
};
```

This affects most of the form components. More details of the RC5/6 forms implementation for Custom Input Control Value Accessors: http://almerosteyn.com/2016/04/linkup-custom-control-to-ngcontrol-ngmodel

**Comment by Coffee-Tea** [comment]
@mko Tell me please if you know, can I fix that and use these most of the form components if now I use RC5? Or I need to upgrade my angular to release version for good working with these components?

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
