### ISSUE TITLE
Set styleClass to TreeTable TreeNode

### ISSUE THREAD

**Issue by IreshikaAluthSahalge-EH** [primefaces/primeng#8451]
Currently TreeNode has a property called styleClass and requirement is to use styleClass property in TreeNode with a TreeTable.
There isn't any examples in documentation for this. 

Tried to override 

`.ui-treenode-content{
  background-color: red !important;
}`

like this. But in source code ,for tree table there isn't any style for TreeNode for TreeTable

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9.0.5, note.styleClass is added, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
