### ISSUE TITLE
Inline calendar not visible inside overlay-panel

### ISSUE THREAD

**Issue by uodriozola** [primefaces/primeng#8452]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-iuvxea

**Current behavior**

When you open the inline calendar inside an overlay-panel for the first time it works okey. If you try to open it more than once it opens the calendar but it is not visible

**Expected behavior**

The calendar should be visible every time you open it.

**Minimal reproduction of the problem with instructions**

DEMO: https://stackblitz.com/edit/github-iuvxea

STEPS:
**_1. Press the button "Show calendar"._**
      The calendar will be shown: 
![image](https://user-images.githubusercontent.com/34504311/72439342-0ddee900-37a7-11ea-9526-c381bf7c22a3.png)
**_2. Click outside the calendar._**
    The calendar will be hidden.
**_3. Press the button "Show calendar" another time._**
    The calendar will be invisible:
![image](https://user-images.githubusercontent.com/34504311/72439494-55657500-37a7-11ea-97ee-3faf1878ece7.png)

**Please tell us about your environment:**

* **Angular version:** 8.2.9

* **PrimeNG version:** 8.0..2

* **Browser:** all

 
* **Language:** all

* **Node (for AoT issues):** v10.18.0

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9.0.5, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Comment by R3JMW** [comment]
It could be reproduced.

**- Angular version: 13.3.0
- PrimeNG version: 13.3.1
- Browser: all
- Language: all
- Node (for AoT issues): v14.18.2**

https://github.com/primefaces/primeng/issues/10978 This works for me to use the calendar with inline mode into a <ng-template>
