### ISSUE TITLE
FileUtils does not exist in path specified in Docs

### ISSUE THREAD

**Issue by prahaladbelavadi** [primefaces/primeng#8453]
**I'm submitting a BUG REPORT  (check one with "x")
```
[*] bug report => Search github for a similar issue or PR before submitting

**Current behavior**

FilterUtils does not exist at primeng/api
`import {FilterUtils} from 'primeng/api'; `
renders an error saying that there's no exported member called FilterUtils

![image](https://user-images.githubusercontent.com/16673094/72439263-99b73c00-37cc-11ea-9601-fc35cec08359.png)


**Expected behavior**
The import path should be corrected. The path is available at `primeng/utils`;
This import works: `import {FilterUtils} from 'primeng/utils'; `

The FilterUtils section does not work as expected.

**Please tell us about your environment:**
<!-- Operating system, IDE, package manager, HTTP server, ... -->
Running Windows 10; VisualStudioCode

Angular CLI: 8.0.6
Node: 10.15.3
OS: win32 x64
Angular: 8.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.6
@angular-devkit/build-angular     0.800.6
@angular-devkit/build-optimizer   0.800.6
@angular-devkit/build-webpack     0.800.6
@angular-devkit/core              8.0.6
@angular-devkit/schematics        8.0.6
@angular/cdk                      8.2.3
@angular/cli                      8.0.6
@ngtools/webpack                  8.0.6
@schematics/angular               8.0.6
@schematics/update                0.800.6
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0

My package.json Dependendcies: 

  "dependencies": {
    "@angular/animations": "~8.0.0",
    "@angular/cdk": "^8.2.3",
    "@angular/common": "~8.0.0",
    "@angular/compiler": "~8.0.0",
    "@angular/core": "~8.0.0",
    "@angular/forms": "~8.0.0",
    "@angular/platform-browser": "~8.0.0",
    "@angular/platform-browser-dynamic": "~8.0.0",
    "@angular/router": "~8.0.0",
    "primeicons": "^2.0.0",
    "primeng": "^9.0.0-rc.2",
    "rxjs": "~6.4.0",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
}
Running Chrome

**Comment by prahaladbelavadi** [comment]
I was using 9.0 that came with the npm install directly instead of the stable release on 8.0.1
![image](https://user-images.githubusercontent.com/16673094/72515371-ca9f7b80-3875-11ea-802f-dc4451489fb3.png)

I should've changed it from the package.json file.
 on installing primeng  with 
`
npm install primeng --save
npm install primeicons --save`

it was automatically as the latest version instead of the latest stable release.
changed it to 8.0.0 after
"dependencies": {
  //...
  "primeng": "^8.0.0",
  "primeicons": "^2.0.0"
},

**Comment by thaihacong** [comment]
@prahaladbelavadi: Can you reopen this issue again, as `import { FilterUtils } from 'primeng/api';
` does not work in primeng v9.0.0 stable release?

**Comment by thaihacong** [comment]
It should now be `import {FilterUtils} from 'primeng/utils';`

**Comment by prahaladbelavadi** [comment]
Reopened issue @thaihacong 
I solved this by using stable release using 8.0.1

Let me know if this issue still exists @thaihacong

**Comment by PaoloPerroneJdk** [comment]
Moorning , i m using Angular version 11 but have the same error : 

import {FilterUtils} from 'primeng/utils'

CONSOLE: Error: ./src/app/app.component.ts 146:8-19
"export 'FilterUtils' was not found in 'primeng/utils'

thanks guys...

**Comment by devopsfriends** [comment]
I am also having same issue.
version 11.2.0
export 'FilterUtils' was not found in 'primeng/utils'

**Comment by devopsfriends** [comment]
@cagataycivici please reopen the issue.

**Comment by Pinka30** [comment]
`import {FilterUtils} from 'primeng/utils';`
This doesn't work with version 13 of primeng, I am getting below error,
`Module '"primeng/utils"' has no exported member 'FilterUtils'.`

**Comment by robinmetro1** [comment]
what's the solution ?

**Comment by myrtlingo** [comment]
In version 11 the hacky FilterUtils is replaced with FilterService API. _See custom constraint [here](http://primefaces.org/primeng/filterservice)._
