### ISSUE TITLE
p-confirmDialog not openining when clicked from p-dialog open box content

### ISSUE THREAD

**Issue by monikaxx** [primefaces/primeng#8456]
Requirement
When p-table is open and having list , when clicked on any record delete button it should ask for confirmation (yes/no) .

**Issue** - p-confirmDialog box not opening on top of / along with p-dialog

R&D : Tried with adding appendTo="body" attribute to both p-dialog and p-confirmDialog but it wont worked
Please suggest way to resolve it.

Angular version: 8

PrimeNG version: 8.0.2

Browser: [Chrome] latest stable

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9.0.5, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
