### ISSUE TITLE
Multiple instances of the same Modal Dialog may be opened at a time

### ISSUE THREAD

**Issue by davisb10** [primefaces/primeng#8462]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Behavior is visible from showcase website
https://www.primefaces.org/primeng/#/dynamicdialog

**Current behavior**

Click on Show button. Modal Dialog appears.
Click on the Space or Enter key on your keyboard. Another instance of the dialog appears.

**Expected behavior**

Keyboard presses should not be able to trigger the creation of new dialogs while one is currently active and set as modal.

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9.0.5, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Comment by SoyDiego** [comment]
Have the same problem here. Any solution? Thanks

**Comment by venkata82** [comment]
I too have same issue with V13.4.1
