### ISSUE TITLE
p-dialog hide without destroy DOM object

### ISSUE THREAD

**Issue by jotae1e** [primefaces/primeng#8463]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

p-dialog destroy the DOM object on hide. 

Is it posible to show or hide disabling this feature?  I tried to use [style], but didn't work.

(I use fullcalendar.io inside p-dialog and is not updating correctly, because I think that p-dialog and fullcalendar must be rendered, but I can control this)

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9.0.5, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Comment by jotae1e** [comment]
It's easy.  When you hide p-dialog, DOM object disappears.  It's deleted.
