### ISSUE TITLE
Primeng table with row expand having nested table

### ISSUE THREAD

**Issue by HasKob** [primefaces/primeng#8464]
Hello all,
I have a table and on its rowExpand it has a nested table.
The columns and data of the nested table depend on the parent row Type (I have 3 different Types 1, 2 and 3).
Let say if the type is 1, the columns of the nested table are (Client, Service, Country, Operator).
Else if the type is 2, the columns of the nested table are (Name, Age, Area, Building) and so on.

The problem is when I'm expanding a row, all previous expanded rows updates there columns and data to be like the last expanded.

Is it possible to expand a row and display its nested table without updating the previous nested tables?

**Comment by johnmanko** [comment]
Can you add code demonstarting how you're using the tables? html and ts.

**Comment by cagataycivici** [comment]
Please use forum for support requests and questions.
