### ISSUE TITLE
p-menu , clicking outside not working when angular onPush enabled

### ISSUE THREAD

**Issue by crystalized2** [primefaces/primeng#8469]
latest stable version of prime-ng 8.1.1 used

p-menu will not close itself when clicking outside when onPush is enabled, you can try to force detectChanges with an hostListener but you will still need to close twice to close it

here is a clean env to reproduce: https://stackblitz.com/edit/angular-n89afp

thank you

**Comment by yigitfindikli** [comment]
Duplicate https://github.com/primefaces/primeng/issues/8226
