### ISSUE TITLE
Table EditableColumn crashing on Tab key when loose ui-editing-cell

### ISSUE THREAD

**Issue by dankatanka** [primefaces/primeng#8470]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

```
ERROR TypeError: Cannot read property 'parentElement' of null
    at EditableColumn.push../node_modules/primeng/components/table/table.js.EditableColumn.moveToNextCell (table.js:3096)
    at EditableColumn.push../node_modules/primeng/components/table/table.js.EditableColumn.onKeyDown (table.js:3068)
    at Object.eval [as handleEvent] (RulesViewComponent.html:152)
    at handleEvent (core.js:23107)
    at callWithDebugContext (core.js:24177)
    at Object.debugHandleEvent [as handleEvent] (core.js:23904)
    at dispatchEvent (core.js:20556)
    at core.js:21003
    at HTMLTableCellElement.<anonymous> (platform-browser.js:993)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
```

**Current behavior**
`EditableColumn.findCell` can return `null` but `moveToPreviousCell`/`moveToNextCell` doesn't process them. If all editable cell closed but focus still in table they crashing on each `Tab` press until EditableColumn will initialized. 
This behaviour still presents in latest PrimeNG 8.1.1.

**Expected behavior**
Filter possible `null` value from `findCell` method.

* **Angular version:** 7.2.15

* **PrimeNG version:** 7.1.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 79.0.3945.130 (probably any browser)

**Comment by yigitfindikli** [comment]
Can you provide a stackblitz sample using with https://stackblitz.com/github/primefaces/primeng-issue-template ? @dankatanka

**Comment by ivpadim** [comment]
I have the following scenario:

Grid with 4 columns, the last one is only editable depending of what the user entered on 2nd column.

By default is disabled but if I try to use the tab I cannot enter into that last column. If I enter to the cell with a click the editing is triggered.

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Comment by cagataycivici** [comment]
Still there might be a case so added a check.
