### ISSUE TITLE
Can't get sorting and filtering to work together for each column

### ISSUE THREAD

**Issue by EuniceB** [primefaces/primeng#8480]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
I have a p-table with sorting and filtering on each column. When I click the text input used for filtering, two things happen:
- the input loses focus instantaneously (so I can't write in it)
- the table gets sorted

Stackblitz reproduction:

https://primeng-table-vlhv5w.stackblitz.io/

**Expected behavior**

- the text input should remain focused. 
- the table should NOT be sorted

**Angular version:** 8.0.0

**PrimeNG version:** 8.0.0

**Browser:** [Chrome 79.0.3945.130 | Firefox 72.0.2]
On Firefox I notice that the input remains focused, so I can write in it. But the table stills gets sorted and it shouldn't.

**Comment by EuniceB** [comment]
As a workaround, I just stopped the propagation of the click event on the filter input.
```
clickOnFilter(event: Event) {
   event.stopPropagation();
}
```

**Comment by cagataycivici** [comment]
Filtering should be in its own row as in;

https://www.primefaces.org/primeng/showcase/#/table
