### ISSUE TITLE
Setting focus for dialog close button doesn't work

### ISSUE THREAD

**Issue by kredki** [primefaces/primeng#8481]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/github-vur22c

**Current behavior**
When I set focus to close button of dialog it's set to another element (after I set it to close button).

**Expected behavior**
Should set focus to close button.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/github-vur22c
-->

* **Angular version:** 8.0.6

* **PrimeNG version:** 8.1.1

* **Browser:** [all]

**Comment by cagataycivici** [comment]
Set [focusOnShow] as false.
