### ISSUE TITLE
DataView does not sort when populated (no filtering involved).

### ISSUE THREAD

**Issue by mcpierce** [primefaces/primeng#8483]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
In my application we have a shared component that displays comics that uses a DataView for output. The SortField and SortOrder values are set programmatically based on stored preferences before the data is loaded.

However, when the comics are first displayed the sort field and sort order are not honored (we've hard coded them into the HTML and don't see it working).

But if the sort is changed *after* they are displayed, then the sort field and order are honored. But if the data changes the sort does 

**Expected behavior**

The sorting should be honored even after the data changes.

**Minimal reproduction of the problem with instructions**
1. Create a data component that uses a DataView component.
1. Set the sort field and order programmatically or by assigning them.
1. Set the data to be displayed.
1. The sorting is not honored.

**Please tell us about your environment:**

* **Angular version:** 7.2.0

* **PrimeNG version:** 7.1.3

* **Browser:** all

* **Language:** all-

* **Node (for AoT issues):** v10.16.3

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
