### ISSUE TITLE
Enhancement request: Expose panelVisible field and show method in p-dropdown

### ISSUE THREAD

**Issue by ryanwawr** [primefaces/primeng#849]
It would be nice if the panelVisible property in the Dropdown class was public (or at least had a public getter) so that I could easily determine the state of the dropdown from code. 

Would also be nice if the show() method, which is already public, did not require two private fields as input. There really doesn't seem to be any reason for it to require any input arguments at all, since panel and container are already accessible from within the method anyway. Allowing show to be called without arguments would make it much easier for users to customize the shortcut for opening the dropdown, which would be a nice alternative to only allowing Alt+DownArrow.

**Comment by ryanwawr** [comment]
Looks like this isn't an issue anymore since these fields were recently made public.

**Comment by mmubasher** [comment]
@ryanwawr on upgrading from primeng 6 to version 8, panelVisible has been removed. Is there any other feature added for this?
