### ISSUE TITLE
Tabindex for sortIcon in primeng

### ISSUE THREAD

**Issue by rama401** [primefaces/primeng#8492]
**I'm submitting a ...**  (check one with "x")
```
```

**Current behavior**
I've added tab index manually for <p-sortIcon>, it's getting focus but sorting is not working when I press enter key.

**Expected behavior**
I want to use the keyboard to control all the fields inside the data table so I've given tab index manually for all fields including the sort icon. So sorting should work on pressing the enter key.

**Comment by cagataycivici** [comment]
th elements are sortable with keyboard e.g. enter. Please test;

https://www.primefaces.org/primeng/showcase/#/table/sort
