### ISSUE TITLE
Dialog - contentHeight Vs contentStyle

### ISSUE THREAD

**Issue by AAAboutajedyne** [primefaces/primeng#8495]
I read on the doc about contentStyle and I used it to set color, it doesn't wok. I search on github and I found that 'constentStyle' was called 'contentHeight' and is intended for handling min/max height.

If the contentStyle is intended to accept any css object, please tell me what I'm missing here ?
otherwise if it's intended to handle the height the name "contentStyle" is not significant and must be changed to something more concise.

```html
<p-dialog header="A dialog with dynamic height" [contentStyle]="{ 'height': 'auto !important' , 'color': 'red' }">
       ... my dynamic content here if(prop) display full content otherwise min content...
</p-dialog
```

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.
