### ISSUE TITLE
dialog.visible is not in correct value when dialog is closed by pressing 'Esc'

### ISSUE THREAD

**Issue by Vincent-Pang** [primefaces/primeng#85]
reproduce procedures:
1) goto showcase website
http://www.primefaces.org/primeng/#/dialog

2) click the 'Show' button  (dialog shown)

3) press 'Esc' (dialog closed)

4) click the 'Show' button again (dialog should be shown, but nothing happen)

After have a look, I found that dialog.visible == true after step 3, which I think the correct value should be false.

Sounds right?

Thanks.

**Comment by cagataycivici** [comment]
We've managed to replicate and will be fixed for 0.7.0.
