### ISSUE TITLE
Calendar gets focus on inline grid edit cell tab

### ISSUE THREAD

**Issue by chravikishore** [primefaces/primeng#8502]
I have calendar p-control and a p-table with inline edit. When I tab with in p-table edit cells, p-calendar getting focus. I have created a sample with my scenario and mentioned below.

https://stackblitz.com/edit/primeng-calendar-focus

**Reproduction instructions**
I placed form control with pFocustrap and added a p-calendar and p-table with inline edit.

**Please tell us about your environment:**
* **Angular version:** 8.2.14

* **PrimeNG version:** 9.0.0-rc.4

* **Browser:** all

**Comment by johnmanko** [comment]
@chravikishore When I set the `tabindex="-1"` on `p-calendar`, no focus happens.  So, the problem is really how your browser sees where it need to table to next. 

`<p-calendar tabindex="-1"></p-calendar>`

You can also set the tabindex on the other entry component `input`/`p-dropdown` fields.

**Comment by chravikishore** [comment]
I need the tab index for the control. I have placed another control before calendar. Now that input control is getting focus. I think there seems as issue with pFocusTrap in calculating next focusable control.

**Comment by cagataycivici** [comment]
Please use forum for support requests and questions.
