### ISSUE TITLE
[p-confirmdialog] Transparency problem since 9.0.0-rc.3

### ISSUE THREAD

**Issue by jmesa-sistel** [primefaces/primeng#8504]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**

Now the confirm dialog is transparent. The issue is the reimplementation of the component in 9.0.0-rc.3. The child inherits the parent opacity.

@yigitfindikli 
To fix it just use alpha in background-color instead opacity. Ex:
`background-color: #424242b2`

My workaround in styles.scss:
```
.ui-dialog-wrapper.ui-widget-overlay.ui-dialog-mask.ui-dialog-mask-scrollblocker {
    background-color: #424242b2 !important;
    opacity: unset !important;
}
```
**Expected behavior**

No opacity in child component

**Minimal reproduction of the problem with instructions**

Just create a p-confirmdialog using  9.0.0-rc.3 or  9.0.0-rc.4

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 9.0.0-rc.12

* **PrimeNG version:** 9.0.0-rc.3 / 9.0.0-rc.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by yigitfindikli** [comment]
Hi @jmesa-sistel,

I’m unable to replicate with the latest PrimeNG. Can you create example using with https://stackblitz.com/github/primefaces/primeng-issue-template .

**Comment by jmesa-sistel** [comment]
You are right, the problem is on my side, I was using the old bootstrap theme which use opacity instead background alpha, sorry for wasting your time.

**Comment by yigitfindikli** [comment]
Not a problem @jmesa-sistel, always happy to help!
