### ISSUE TITLE
set default time using default date

### ISSUE THREAD

**Issue by FallenRiteMonk** [primefaces/primeng#851]
Is it possible to somehow set the default time in a calendar?
I tried setting defaultTime to something like "2016-09-01 18:45" with a dateFormat like "yy-mm-dd" and a timeFormat like "HH:mm" but it diddn't work

**Comment by ahelord** [comment]
I also had the same problem but I solved it by doing this:
in this template :
`   <p-schedule [events]="events" [header]="header" [defaultDate]="defaultDate" [eventLimit]="4" [editable]="true"
/* only add [] to defaultDate*/
`
in this component:
` ngOnInit(): void {
       

        /* start Load Default Day of Prime Ng Schedule */
        this.eventService.getToday()
            .then(today => {
                this.today = today[0]
                console.log(this.today)

                this.defaultDate = this.today.today;
                console.log(this.defaultDate)
            });
        /* end Load Default Day of Prime Ng Schedule */

/* here others load of primeng for example header, events*/
`

in this service:


`    getToday(): Promise<Today> {
        return this.http.get(this.todayUrl)
            .toPromise()
            .then(response => response.json()as Today)
            .catch(this.handleError);
    }
/* this service get date in this format 2017-01-05T15:34:19.402Z */
`

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
