### ISSUE TITLE
After upgrading to V9.x, getting build errors no exported member in primeng/api for Dialog service.

### ISSUE THREAD

**Issue by jaggi510** [primefaces/primeng#8512]
After upgrading we are getting below errors during ng serve or ng build --prod commands

/node_modules/primeng/api/primeng-api"' has no exported member 'DynamicDialogRef'.

import { DynamicDialogConfig, DynamicDialogRef } from 'primeng/api'; 

/node_modules/primeng/api/primeng-api"' has no exported member 'DialogService'.

 import { DialogService } from 'primeng/api';

**Comment by EddyNll** [comment]
Getting the same issue

**Comment by Rjitendra** [comment]
Getting same issue.Can any one please post,what is the issue

**Comment by jaggi510** [comment]
Afther changing the import from 
import { DialogService } from 'primeng/api';
import { DynamicDialogConfig, DynamicDialogRef } from 'primeng/api';

to 

import { DialogService } from 'primeng/dynamicDialog';
import { DynamicDialogConfig, DynamicDialogRef } from 'primeng/dynamicDialog';

We are able to build and did not see any issues with the behavior.

**Comment by Rjitendra** [comment]
> Afther changing the import from
> import { DialogService } from 'primeng/api';
> import { DynamicDialogConfig, DynamicDialogRef } from 'primeng/api';
> 
> to
> 
> import { DialogService } from 'primeng/dynamicDialog';
> import { DynamicDialogConfig, DynamicDialogRef } from 'primeng/dynamicDialog';
> 
> We are able to build and did not see any issues with the behavior.

Thanks Bro..working now

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.

**Comment by maimia71** [comment]
import { PrimeNGConfig } from 'primeng/api';
error: -> Module '"primeng/api"' has no exported member 'PrimeNGConfig'.ts(2305)

//image URL👇🏼👇🏼👇🏼 for better understanding... Thanks in advance...

![Screenshot (96)_LI](https://user-images.githubusercontent.com/50349531/111944943-c10b4680-8afe-11eb-8981-80cf48bdd0ec.jpg)

**Comment by zahrahvn** [comment]
you can use of 
import { DynamicDialogConfig, DynamicDialogRef } from 'primeng/dynamicdialog';
