### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError when using primeng controls in modal

### ISSUE THREAD

**Issue by MeMeMax** [primefaces/primeng#8513]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/angular-juwbdm

**Current behavior**
When an PrimeNG element is the first focusable element in a modal there is a "ExpressionChangedAfterItHasBeenCheckedError" Error.

ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ui-inputwrapper-focus: undefined'. Current value: 'ui-inputwrapper-focus: true'.

**Expected behavior**
No Error

**Minimal reproduction of the problem with instructions**
See Stackblitz / Current behavior

**What is the motivation / use case for changing the behavior?**
No Error

**Please tell us about your environment:**

* **Angular version:** 8.2.4

* **PrimeNG version:** 8.1.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome (didnt test others)

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9.0.5, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
