### ISSUE TITLE
Tree - onNodeExpand event not fired when filtering

### ISSUE THREAD

**Issue by saramcicchi** [primefaces/primeng#8518]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-nvj9wt

**Current behavior**
When filtering over a tree, nodes automatically get expanded yet the onNodeExpand event doesn't get fired.

**Expected behavior**
The onNodeExpand event should be fired when nodes are expanded as a result of matching during filtering.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/github-nvj9wt

**What is the motivation / use case for changing the behavior?**
The onNodeExpanded event is documented as a "Callback to invoke when a node is expanded". This implies it should be triggered whenever a node is expanded, no matter the action triggering the expansion. 

**Please tell us about your environment:**
* **Angular version:** 8.X
* **PrimeNG version:** >= 8.1

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template

**Comment by cagataycivici** [comment]
onNodeExpand is reserved for user interactions.

**Comment by cagataycivici** [comment]
9.0.6 will bring onFilter which you may use instead.
