### ISSUE TITLE
npm installing 9rc4

### ISSUE THREAD

**Issue by mikegoodstadt** [primefaces/primeng#8522]
Hi PrimeNG,
Installing via `npm i primeng` is serving up `^9.0.0-rc.4`.
Surely the default / `@latest` (as of today) is `^8.1.1`?
Saludos!

**Comment by mikegoodstadt** [comment]
P.s. I noticed the difference as the `ui-widget-overlay` class is being applied to the dialog wrapper rather than just the overlay div, causing the whole overlay to be given whatever opacity the overlay class has... :(

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.
