### ISSUE TITLE
p-autoComplete dropdown menu does not toggle closed on click of menu disclosure button

### ISSUE THREAD

**Issue by KeithGillette** [primefaces/primeng#8523]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
N/A

**Current behavior**
Pressing dropdown menu disclosure button does not hide the dropdown menu when the menu is visible.

**Expected behavior**
Pressing dropdown menu disclosure button should hide the dropdown menu when the menu is visible.

**Minimal reproduction of the problem with instructions**
Twice press the menu disclosure button on the [PrimeNG showcase for the AutoComplete component](https://www.primefaces.org/primeng/#/autocomplete).

**What is the motivation / use case for changing the behavior?**

Per the similar [JavaServer Faces forum thread](https://forum.primefaces.org/viewtopic.php?t=57648), to match the show/hide menu toggling behavior of  similar components with menu disclosures:

- [Dropdown](https://www.primefaces.org/primeng/#/dropdown)
- [MultiSelect](https://www.primefaces.org/primeng/#/multiselect)
- [SplitButton](https://www.primefaces.org/primeng/#/splitbutton)
- [Menu (Popup)](https://www.primefaces.org/primeng/#/menu)
- [Menubar](https://www.primefaces.org/primeng/#/menubar)
- [Tiered Menu](https://www.primefaces.org/primeng/#/tieredmenu)

**Please tell us about your environment:**
N/A

**Comment by cagataycivici** [comment]
It was by design but I guess we can align it with other components.
