### ISSUE TITLE
prime icons doesn't show in tree component

### ISSUE THREAD

**Issue by narimanmandi** [primefaces/primeng#8529]
i am using primeng tree module in my ngg project 
the problem is when the tree loads it does not show pi-caret icon that have used for expanding tree levels.
when i use primeicons clas in an <i> element everything is ok
but tree component uses primeicons in <span> element.
i am using these versions in my package .json

```
"primeicons": "^1.0.0",

 "primeng": "^7.1.3",
```

i import styles in my angular.json

```
"node_modules/primeicons/primeicons.css",

"node_modules/primeng/resources/themes/nova-light/theme.css",

"node_modules/primeng/resources/primeng.min.css",

"node_modules/@fortawesome/fontawesome-free/css/all.min.css"

even import it in my app.scss
```

`
@import '~primeicons/primeicons.css';
`
even i tried to add it directly in my index.html but nothing works for me .

any idea ?

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.

**Comment by narimanmandi** [comment]
finally i got it 
i have changed span element font family in my css class though the problem solved by removing span from css style .
