### ISSUE TITLE
Nested multiple sort support for TreeTable

### ISSUE THREAD

**Issue by ben-abraham** [primefaces/primeng#8530]
Can be reproduced in [example](https://www.primefaces.org/primeng/#/treetable/sort) by sorting first by **Name**, and then ctrl+clicking on **Size**. If you continue to ctrl+click on **Size**, you can see only the ordering of **Documents**/**Documents(folder)** changes, when you'd expect the **note-meetings.txt** and **note-todo.txt** records to change order as well.

**Comment by cagataycivici** [comment]
Fixed via https://github.com/primefaces/primeng/pull/8531
