### ISSUE TITLE
Tree onNodeDrop never fires for first node drop

### ISSUE THREAD

**Issue by vimalraj-a** [primefaces/primeng#8536]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Dropping node on empty tree never emits `onNodeDrop` event.

**Expected behavior**
`onNodeDrop` event should be fired on any node drop event for the empty tree

**Minimal reproduction of the problem with instructions**
1. Create 2 tree components
2. Make sure one tree has some nodes and other is empty
3. Listen onNodeDrop event on second tree component
3. Drag node from first tree to second tree when empty
4. See onNodeDrop event not fired.
5. When tree has some node onNodeDrop always fired

`onDrop` should fire `onNodeDrop` event. [see here](https://github.com/primefaces/primeng/blob/4e19f726f9b18d3298978e94a0c60fc513eed773/src/app/components/tree/tree.ts#L919)

**What is the motivation / use case for changing the behavior?**

It's blocking our design where users should be able to prompted whenever new node dropped on tree

**Please tell us about your environment:**
Basic dev environment nothing excellent.

* **Angular version:** 8.2.14

* **PrimeNG version:** 8.1.1

* **Browser:** all

* **Language:** Typescript

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9.0.5, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
