### ISSUE TITLE
Pinnable Sidebar

### ISSUE THREAD

**Issue by lucasdesiderio** [primefaces/primeng#8537]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Expected behavior**
It would be nice to have a "pinnable" property on Sidebar Module, so when could pin and unpin it like a side bar menu.
When pinned, the overlayed part of the screen should be fitted on the screen slice available.
When unpinned, the sidebar should have the same behavior it has now.

**What is the motivation / use case for changing the behavior?**
This request is motivated to use it as a side menu.

**Comment by cagataycivici** [comment]
This feature is available in premium templates like Mirage, Manhattan or Serenity

https://www.primefaces.org/mirage-ng/
https://www.primefaces.org/manhattan-ng/
https://www.primefaces.org/serenity-ng/

**Comment by lucasdesiderio** [comment]
> This feature is available in premium templates like Mirage, Manhattan or Serenity
> 
> https://www.primefaces.org/mirage-ng/
> https://www.primefaces.org/manhattan-ng/
> https://www.primefaces.org/serenity-ng/

Thank you @cagataycivici !
