### ISSUE TITLE
ConfirmationDialog and Dialog leaves screen grayed on rejection

### ISSUE THREAD

**Issue by dmytro-gokun** [primefaces/primeng#8538]
I'm trying to update my app to Angular 9 & PrimeNg 9.0.0-rc.4 and have faced this issue (which did not exists in Angular 8/PrimeNg 8):

**I'm submitting a ...**  (check one with "x")

```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

Plz find the reproduction project in the attachment. [demo.zip](https://github.com/primefaces/primeng/files/4182672/demo.zip)
It is a simple Angular 9 project created by Angular CLI with Prime Ng added to it. The actual code is in app.component.ts/html.

I've also tried reproducing the problem using the issue template:
https://stackblitz.com/edit/github-llfw9v

but was not able to reproduce it. I cannot figure out why is that.

**Current behavior**

When using OnPush change detection the screen stays grayed after the confirmation dialog is dismissed (rejected).

**Expected behavior**

Screen should not be grayed after the confirmation dialog is dismissed.

**Minimal reproduction of the problem with instructions**

1. Click 'Delete' button
2. Confirmation dialog is shown
3. Click 'No'
4. Observer that the screen is grayed.
5. Comment out line 7 in app.component.ts (so that the component does not use OnPush change detection strategy) and repeat the test. Now it works as expected.

**Please tell us about your environment:**
Windows 10, Chrome 80

* **Angular version:** 5.X
9.0.0

* **PrimeNG version:** 5.X
9.0.0-rc.4

**Comment by digitalcraftco** [comment]
I'm seeing this too. Angular 9 & PrimeNg 9.0.0-rc.4. Even when not using onPush strategy,  if you have multiple p-dialogs in one template.... there is a significant delay before .ui-dialog-mask gets dismissed. Compared to previous versions.

**Comment by dmytro-gokun** [comment]
@yigitfindikli Do you know why it was not reproducible in stackblitz?

**Comment by yigitfindikli** [comment]
@dmytro-gokun probably about ivy engine.
