### ISSUE TITLE
Error with PrimeNG Imports in Angular2 RC6

### ISSUE THREAD

**Issue by taohd** [primefaces/primeng#854]
Receiving the following error when trying to import PrimeNG with Angular RC6

![image](https://cloud.githubusercontent.com/assets/17514589/18225844/d62e2c86-71cb-11e6-8bfe-7631d8badc4d.png)

I am using a feature module to declare my PrimeNG imports and directives.

`import { NgModule }      from '@angular/core';
import { CommonModule }      from '@angular/common';

//PrimeNG Imports
import {InputTextModule} from 'primeng/primeng';
import {ButtonModule} from 'primeng/primeng';
import {DataTableModule, DataGridModule, PaginatorModule, Column} from 'primeng/primeng';
import {SplitButtonModule} from 'primeng/primeng';
import {SpinnerModule} from 'primeng/primeng';
import {RatingModule} from 'primeng/primeng';
import {ToolbarModule} from 'primeng/primeng';
import {TabViewModule} from 'primeng/primeng';
import {TabPanel} from 'primeng/primeng';
import {AccordionModule, AccordionTab} from 'primeng/primeng';
import {TreeModule} from 'primeng/primeng';
import {TreeNode} from 'primeng/primeng';
import {PanelModule, OverlayPanelModule} from 'primeng/primeng';
import {MenuModule, MenubarModule} from 'primeng/primeng';

@NgModule(
{

```
imports: [ 

        ],
declarations: [
                InputTextModule, 
                ButtonModule, 
                RatingModule,
                Column,
                DataTableModule, 
                DataGridModule,
                PaginatorModule,
                SplitButtonModule, 
                ToolbarModule, 
                TabViewModule, 
                TabPanel, 
                TreeModule,
                AccordionModule, 
                AccordionTab,
                PanelModule,
                OverlayPanelModule,
                SpinnerModule
            ],
 exports: [

                InputTextModule, 
                ButtonModule, 
                RatingModule,
                Column,
                DataTableModule, 
                DataGridModule,
                PaginatorModule,
                SplitButtonModule, 
                ToolbarModule, 
                TabViewModule, 
                TabPanel, 
                TreeModule,
                AccordionModule, 
                AccordionTab,
                PanelModule,
                OverlayPanelModule,
                SpinnerModule
            ]
```

})

export class PrimeNGModule {}

this is imported into my AppModule like so

`//Angular Imports
import { NgModule }      from '@angular/core';
import { BrowserModule, platformBrowser } from '@angular/platform-browser';

//===[ PRIMENG MODULE ]=============================================
import {PrimeNGModule} from './modules/primeng_module';

//===[ TAO IMPORTS ]==================================================================
import {TaoComponentsModule} from './modules/taocomponents_module';
import {TaoServicesModule} from './modules/taoservices_module';
import {TaoAppComponent} from './components/tao_appcomponent/tao_appcomponent';

@NgModule(
{

```
imports: [ 
            BrowserModule, 
            TaoServicesModule,
            TaoComponentsModule,
            PrimeNGModule
         ],

declarations: [
                TaoAppComponent
              ],

bootstrap: [
            TaoAppComponent
           ]
```

})

export class TaoAppModule {}

 ``

**Comment by StefH** [comment]
I've same error. I guess the best would be that primeng is also using RC.6

**Comment by ersandeepranjit** [comment]
@taohd  Didn't you face Provider is Undefined issue with RC 6 ?

**Comment by AndreyKotofotoff** [comment]
When there is a new version?

**Comment by ersandeepranjit** [comment]
@AndreyKotofotoff , as per their Forum the new RC6 version will be available on 7th sep.

**Comment by edoardoVD** [comment]
Working like a champ for me
@taohd  the npm package has been updated (beta 15)
https://www.npmjs.com/package/primeng

I updated the the package on my project

my custom **primengAll.ts** file
```

import { NgModule } from '@angular/core';

import {
    AccordionModule, AutoCompleteModule, ProgressBarModule, RadioButtonModule, RatingModule, ScheduleModule, SelectButtonModule, SharedModule, SlideMenuModule, SliderModule
BLA BLA BLA ................
} from 'primeng/primeng'

const PRIMENG_MODULES = [
      AccordionModule, AutoCompleteModule, ProgressBarModule, RadioButtonModule, RatingModule, ScheduleModule, SelectButtonModule, SharedModule, SlideMenuModule, SliderModule
BLA BLA BLA ................
];

@NgModule({
    imports: PRIMENG_MODULES,
    exports: PRIMENG_MODULES    
})
export class PrimeNgModules { }
```
Project file **app.module.ts**

```
import { PrimeNgModules } from  '../appbarrels/primengAll'

@NgModule({
  declarations: [
    .....
  ],
  imports: [
    .. .. 
    **PrimeNgModules**
 . .. . 
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```


All good : D

I guess we can put this to sleep now (CLOSE)

**Comment by StefH** [comment]
I was also able to verify. (version 15 fixes indeed this issue)

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
