### ISSUE TITLE
Listbox filter width problem when showToggleAll=false

### ISSUE THREAD

**Issue by scorpion86** [primefaces/primeng#8541]
When i set [showToggleAll]="false" filter's input width is not become 100%. Is that a bug and is there any workaround? Thx for help.

Example code:
`<p-listbox [options]="cities" [(ngModel)]="selectedCity" multiple="multiple" [showToggleAll]="false" checkbox="checkbox" filter="filter" optionLabel="name">
                        <p-header>
                            Cities
                        </p-header>
                    </p-listbox>`

**Comment by scorpion86** [comment]
i tried to add some css. But still same.
 `.ui-listbox-filter-container {
    width: 100%;
}`

**Comment by cagataycivici** [comment]
Should be fixed with 10.
