### ISSUE TITLE
ng update @angular/core &@angular/cli to latest fails

### ISSUE THREAD

**Issue by coreboarder** [primefaces/primeng#8542]
When running "ng update @angular/core &@angular/cli" I get the following error.

Package "primeng" has an incompatible peer dependency to "zone.js" (requires "^0.9.1", would install "0.10.2").

Package.json is:

  "dependencies": {
    "@angular/animations": "~8.2.14",
    "@angular/cdk": "^9.0.0",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "bootstrap": "^4.4.1",
    "moment": "^2.24.0",
    "ngx-bootstrap": "^5.3.2",
    "primeicons": "^2.0.0",
    **"primeng": "^9.0.0-rc.4",**
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },

**Comment by websterKAT** [comment]
Getting the same error when update angular 11 to 12 from the command 
`npx @angular/cli@12 update @angular/core@12 @angular/cli@12`

Package "primeng" has an incompatible peer dependency to "zone.js" (requires "^0.10.2", would install "0.11.5").

Any workarounds ?
