### ISSUE TITLE
p-dialog not centered in IE and overflows on maximize

### ISSUE THREAD

**Issue by keschr** [primefaces/primeng#8545]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
No plunkr needed, you can just visite the primeng page https://www.primefaces.org/primeng/#/dialog

**Current behavior**
Open the dialog inside IE, it floats to the right. 

**Expected behavior**
Should be centered like in all other browsers. This issue was still fixed in version 8

**Minimal reproduction of the problem with instructions**
![image](https://user-images.githubusercontent.com/60967123/74329340-ea9c5f00-4d8f-11ea-8aca-8b7b083cd5f6.png)

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 
9.0.0

* **PrimeNG version:** 
9.0.0-rc.4

* **Browser:** 
 IE 11

**Comment by MeForThis** [comment]
Confirmed with PrimeNG 9.0.4 and Angular 9.1.0 and IE11

The upper left edge of the dialog is in the center.
All other positions, e.g. top, work like they should.

**Comment by keschr** [comment]
@MeForThis realy? But you can see the difference between chrome/Firefox and IE?

**Comment by MeForThis** [comment]
Yes, in the current Firefox and Chrome it works fine. In IE11 it's not in the center.

**Comment by uyt95** [comment]
I have a similar issue on IE and on other browsers (chrome/firefox) on production builds. the overlay also doesn't appear, so the user can still interact with the other buttons on the page.
