### ISSUE TITLE
Multiple DynamicDialogs are not closing programmatically

### ISSUE THREAD

**Issue by mrdlink** [primefaces/primeng#8547]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When I open multiple DynamicDialogs from a single injected DialogService, the top most dialog closes as expected, but all the following dialogs do not close when calling the close() function on the DynamicDialogRef.

**Expected behavior**
When I open multiple DynamicDialogs from one single injected DialogService, I expect that all Dialogs can be closed programmatically by calling the close() function on the DynamicDialogRef.
I expect a behavior like with the Angular Material Dialogs.

**What is the motivation / use case for changing the behavior?**
I want to dynamically show info, error or confirmation messages as those messages are dynamically received from a backend service without queuing them like one has to do with the ConfirmationDialog.

**Please tell us about your environment:**
The Angualr app is backed by a database. The database can send messages to the app and the app has then to bring up a message no matter what state the application is in.

Angular Version: 8.2.9

PrimeNG Version: 8.1.1

* **Browser:** [all]
 
* **Language:** [all]

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9.0.5, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Comment by fredericojesus** [comment]
Not working for me as well with PrimeNG 9.0.5. I basically add to always close one and then open another. Cannot have two open at the same time because I can't close them later.

**Comment by FabienDehopre** [comment]
Some here with PrimeNG 9.0.6. The upper most dialog close programmatically but not the others.
