### ISSUE TITLE
Message Component, Confirm Dialog ... not working with Angular 9 (Stable release) - Primeng 9 RC4 (latest)

### ISSUE THREAD

**Issue by tranthoai** [primefaces/primeng#8549]
Confirm box only black:

![image](https://user-images.githubusercontent.com/2963050/74400993-75459280-4e52-11ea-9314-b787478e1694.png)

Message lost CSS: 

![image](https://user-images.githubusercontent.com/2963050/74400952-3f081300-4e52-11ea-83fb-92d99904c767.png)

And so many other issues, please fix it. Thank you ^^

**Comment by yigitfindikli** [comment]
Confirm dialog issue fixed at https://github.com/primefaces/primeng/issues/8538 . Css issues will be fixed next angular release (Angular issue: https://github.com/angular/angular/issues/35335). And you can track css issue at https://github.com/primefaces/primeng/issues/8557 .

**Comment by tranthoai** [comment]
Thank you all ^^

**Comment by tranthoai** [comment]
I just tested p-confirmDialog with latest Primeng and latest Angular. Without option appendTo="body" it work OK. But with option appendTo="body" it show only gray background on screen without any confirmDialog content.

<p-confirmDialog
        appendTo="body"
        [style]="{width: '50vw'}">
      </p-confirmDialog>

**Comment by weiwdc** [comment]
I have the exact the same problem. I have 9.0.0 for Angular, and 9.1.0 primeNG. It only works in development mode. The confirmation dialog flash on the screen, then disappear. The screen grayed out in PRODUCTION mode, unusable.
