### ISSUE TITLE
project cannot be build and start

### ISSUE THREAD

**Issue by hoswey** [primefaces/primeng#855]
It seems the project cannot be build and start for the latest soucre, and I notice that all the dependency are removed. how to fix it?
below is the commit of remove all dependency.
https://github.com/primefaces/primeng/commit/c0b9d3807f87528fab304c4e73679c4e60dc4689

**Comment by moxival** [comment]
There is a guide about building from source https://github.com/primefaces/primeng/wiki/Building-From-Source
Also there is an ongoing discussion about the removal of the dependencies but i cannot find it...
