### ISSUE TITLE
Pager visual glitch

### ISSUE THREAD

**Issue by Svancara** [primefaces/primeng#8550]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

I see this pager glitch in several themes. Pager buttons are slightly misaligned.

![image](https://user-images.githubusercontent.com/109393/74414006-d19fb680-4e40-11ea-9d91-ed25d9ad7003.png)

**Comment by cagataycivici** [comment]
Please use Avalon forum to report issues to our team;

https://forum.primefaces.org/viewforum.php?f=70

@Merve7 Could you please review this?
