### ISSUE TITLE
Can't bind to 'width' since it isn't a known property of p-dialog

### ISSUE THREAD

**Issue by graphicsxp** [primefaces/primeng#8551]
primeng version : 9.0.0-rc.4
Angular version: 9.0.1

error when compilig: Can't bind to 'width' since it isn't a known property of p-dialog

    `<p-dialog header="Unavailability" #unavailabilityPanel appendTo="body" [(visible)]="visible" [modal]="true" [width]="420" >`

This works with primeng 8. What should we do to make this work ? 

**Note that this code works when using Angular 9 + primeng 8 + disabling Ivy**

**Comment by rwetzel273** [comment]
Angular 8.2.14 does seem to compile fine with the [width] property on the p-dialog but viewing/browsing the page with p-dialog and the [width] property, there will be a console warning:
_width property is deprecated, use style to define the width of the Dialog_

Applying the width in the style has worked for me for properly sizing the dialog in Angular 8.2.14.  Hopefully, this will work for the 9x versions you are running.

`<p-dialog header="Unavailability" #unavailabilityPanel appendTo="body" [(visible)]="visible" [modal]="true" [style]="{'width':'420px'}">`

**Comment by yigitfindikli** [comment]
Width property removed. You can use style instead of width.

**Comment by imoitra007** [comment]
> Width property removed. You can use style instead of width.
<p-dialog [style]="{'width':'420px'}">  -- If I use like this it is working.

When I am getting the width value after calculation how do I use it?
Below was my code:
<p-dialog  [width]="width"  [height]="height"">

here width and Height value I am getting from component. How to Bind in Primeng 9.0?
