### ISSUE TITLE
missing dependencies when upgrading to Angular 9 and PrimeNg 9

### ISSUE THREAD

**Issue by timfogarty1549** [primefaces/primeng#8554]
After upgrading to Angular 9 and PrimeNg 9 (rc.4), I get

ERROR in The target entry-point "primeng" has missing dependencies:
 - chart.js

after manually installing chart.js I get same error but with
 - quill

after installing quill I get same error with
 - @fullcalendar/core

Finally it then compiles.

If primeng needs these dependencies, then it should install them.

**Comment by swagner30** [comment]
How did you install them? Thanks.

**Comment by yigitfindikli** [comment]
Hi @timfogarty1549, you can track at https://github.com/primefaces/primeng/issues/8560 .

**Comment by TIMORHIM** [comment]
the imports from "primeng" or "primeng/primeng" were deprecated, so, please use like below

import { TableModule } from "primeng/table";
import { ToastModule } from "primeng/toast";
import { CalendarModule } from "primeng/calendar";

**Comment by aruni445** [comment]
@TIMORHIM Thanks man.
