### ISSUE TITLE
virtual scroller not working in angular 9 

### ISSUE THREAD

**Issue by abhijatyatewari** [primefaces/primeng#8555]
**Angular version:** PrimeNg 9.0.0-rc.4
* **PrimeNG version:** 9.0.0-rc.4
* **Browser:** all | Chrome 80.0.3987.87 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5] TypeScript 3.7

* **Node (for AoT issues):** `node --version` =   v12.13.1

**Comment by yigitfindikli** [comment]
Hi @abhijatyatewari, I couldn't replicate it with https://stackblitz.com/edit/github-cqgrhw. Can you provide sample using with https://stackblitz.com/github/primefaces/primeng-issue-template .

**Comment by abhijatyatewari** [comment]
Hi @yigitfindikli ,
Please find the tmplate https://stackblitz.com/edit/github-cqgrhw-eqfa2x. 

It works fine when ivory is off. But on enabling it it dos not renders any rows

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9.0.5, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
