### ISSUE TITLE
Error after angular 9 migration

### ISSUE THREAD

**Issue by Shelmy-pp** [primefaces/primeng#8557]
hi,
i am using primeng 7 template and After upgrading to angular 9, I received an error saying that ERROR in Host Resource Loader: loader(E:/Angular9/myapp/src/assets/css/theme-indigo.css) returned a Promise It was working when I was using Angular 7 Angular 8, and I received it only after upgrading to 9.

**Comment by Rotzbua** [comment]
primeng version must be equal to angular version, primeng 9 is not released yet

**Comment by Shelmy-pp** [comment]
> primeng version must be equal to angular version, primeng 9 is not released yet

 It was working when I was using Angular 8

**Comment by Rotzbua** [comment]
> It was working when I was using Angular 8

You are funny. Just because it works it does not mean that it should work for other combinations. Primeng is designed to work with a certain other angular version. If it works with other angular versions, it is ok but it's not guaranteed.

BTW there is a bug in angular 9 which causes problems #8540. Until it is resolved in angular no primeng 9.

**Comment by alienjedi** [comment]
But why should angular release a buggy version in the first place. I saw a preview issue dating all the way back to June of 2019 when they were testing the latest release and that same issue focused on NG5006 that we are seeing today. They should have fixed that by now. Don't you think so?

**Comment by Shelmy-pp** [comment]
Updated  primeng,
   "primeng": "^9.0.0-rc.4",  and added "@fullcalendar/angular": "^4.4.5-beta",
But the error still exists
`ERROR in HostResourceLoader: loader(E:/Angular9/myapp/src/assets/css/theme-indigo.css) returned a Promise`

**Comment by yigitfindikli** [comment]
Hi @Shelmy-pp, can you provide sample project ?

**Comment by cmario92** [comment]
any updates on the above? just updated to Angular 9 and I have the below error showing:

ERROR in The target entry-point "primeng" has missing dependencies:
 **- @fullcalendar/core** 

package.json
"dependencies": {
    "@angular/animations": "^9.1.0",
    "@angular/cdk": "^9.2.0",
    "@angular/common": "^9.1.0",
    "@angular/compiler": "^9.1.0",
    "@angular/core": "^9.1.0",
    "@angular/flex-layout": "^9.0.0-beta.29",
    "@angular/forms": "^9.1.0",
    "@angular/http": "^7.2.16",
    "@angular/material": "^9.2.0",
    "@angular/platform-browser": "^9.1.0",
    "@angular/platform-browser-dynamic": "^9.1.0",
    "@angular/platform-server": "^9.1.0",
    "@angular/router": "^9.1.0",
    "@ng-bootstrap/ng-bootstrap": "^6.0.2",
    "@ngx-translate/core": "^12.1.2",
    "bootstrap": "^4.4.1",
    "chart.js": "^2.9.3",
    "core-js": "^3.6.4",
    "cuppa-ng2-slidemenu": "^2.0.0",
    "font-awesome": "^4.7.0",
    "jquery": "^3.4.1",
    "lodash": "^4.17.15",
    "ngx-loading": "^8.0.0",
    "primeicons": "^2.0.0",
    "primeng": "^9.0.2",
    "quill": "^1.3.7",
    "rxjs": "^6.5.4",
    "rxjs-compat": "^6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.0",
    "@angular/cli": "^9.1.0",
    "@angular/compiler-cli": "^9.1.0",
    "@angular/language-service": "^9.1.0",
    "@types/jasmine": "^3.5.10",
    "@types/jasminewd2": "^2.0.8",
    "@types/jquery": "^3.3.34",
    "@types/node": "^12.11.1",
    "@typescript-eslint/eslint-plugin": "^2.25.0",
    "@typescript-eslint/eslint-plugin-tslint": "^2.25.0",
    "@typescript-eslint/parser": "^2.25.0",
    "codelyzer": "^5.1.2",
    "eslint": "^6.8.0",
    "eslint-config-prettier": "^6.10.1",
    "eslint-plugin-prettier": "^3.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.1",
    "karma": "^4.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-cli": "~2.0.0",
    "karma-coverage-istanbul-reporter": "^2.1.1",
    "karma-jasmine": "^3.1.1",
    "karma-jasmine-html-reporter": "^1.5.3",
    "prettier": "^2.0.2",
    "protractor": "^5.4.3",
    "ts-node": "~8.8.1",
    "typescript": "3.8.3"
  }

**Comment by dolphinsd** [comment]
same issue for quill and chart.js, compile requires those installed, even they are not used in project

**Comment by cagataycivici** [comment]
Please use forum for support requests and questions.

```
compile requires those installed, even they are not used in project
```
Avoid importing from the deprecated 'primeng/primeng' to avoid this.

**Comment by eduardoolimpiodev** [comment]
> mesmo problema para quill e chart.js, a compilação requer aqueles instalados, mesmo que não sejam usados ​​no projeto

Sorry, I didn't understand. Could you please explain?
