### ISSUE TITLE
Table loading template available also without virtual scroll

### ISSUE THREAD

**Issue by alex88** [primefaces/primeng#8558]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Right now the `loadingbody` template is only shown when virtual scroll is enabled, it would be nice to be able to customize table tbody in full (not wrapped around a single row) every time the table is in loading state.

This way we can customize and create our own skeleton loader placeholder

**Comment by cagataycivici** [comment]
Please see;

https://github.com/primefaces/primeng/issues/8633
