### ISSUE TITLE
export the template data instead of the original data to csv

### ISSUE THREAD

**Issue by hoswey** [primefaces/primeng#856]
I use the below template to format the table cell, but when I export to csv, the csv data keep its original data, is it possible to export the template data to csv as this behaviour is not consistent between the look and the export.

```
     <p-column field="end_time" header="end_time">
        <template let-col let-row="rowData" pTemplate type="body">
          <span>{{row[col.field] | date:"HH:mm:ss"}}</span>
        </template>
      </p-column>
```

**Comment by bomberblue07** [comment]
I'd like this exact feature as well. Exporting dates to CSV is not human readable by default.

**Comment by zummach** [comment]
And export the header name instead the field's name

**Comment by bomberblue07** [comment]
With 4.0.1 letting filters apply to CSV export, adding this would still be awesome

**Comment by cagataycivici** [comment]
But we can't know what is inside templates so there is a technical limitation, will reopen if we can find a way.

**Comment by digaus** [comment]
Posted a working solution here: 
https://github.com/primefaces/primeng/issues/3552
