### ISSUE TITLE
PrimeNG Schematics

### ISSUE THREAD

**Issue by yigitfindikli** [primefaces/primeng#8560]

**Comment by dregos** [comment]
Same problem

`ERROR in The target entry-point "primeng" has missing dependencies: - chart.js`

**Comment by EddieBenji** [comment]
Hi

I had to install these libraries manually:

`npm i --save primeng/chart primeng/fullcalendar primeng/editor`

Then, the ng 9 project was able to run without any issue. 

Any update on the schematics for this?

thanks

**Comment by P3tronius** [comment]
What if I don't want to add this dependencies? My build time is already way too long and I need to add --max-old-space-size=4096 for the build to succeed.

**Comment by DineshSPatil** [comment]
any updates on this? facing same issue.

**Comment by dregos** [comment]
> any updates on this? facing same issue.

I fixed it by installing everything manualy. Every dependency. And also reinstalled angular. Then it started to work.

**Comment by felipealvesgnu** [comment]
The same problem here !!!

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
