### ISSUE TITLE
pKeyFilter - wrong pattern for positive numbers

### ISSUE THREAD

**Issue by george-oakling** [primefaces/primeng#8561]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Using keyFilter with pnum, inputs allow multiple dots e.g. 1234...4567

**Expected behavior**
Should be disabled

**Minimal reproduction of the problem with instructions**
`<input pInputText pKeyFilter="pnum">`

**What is the motivation / use case for changing the behavior?**
Should only allow one dot per number, e.g. 1234.456
As found, this regexp should solve the problem:

/^[+]?([0-9]+(?:[\.][0-9]*)?|\.[0-9]+)$/

* **Angular version:** 8.2.1

* **PrimeNG version:** 8.1.1

**Comment by cagataycivici** [comment]
This is expected because key filter does not validate this, it only validates keystrokes. Upcoming inputNumber component will have this feature.

**Comment by george-oakling** [comment]
> This is expected because key filter does not validate this, it only validates keystrokes. Upcoming inputNumber component will have this feature.

perfect! thanks a lot!
