### ISSUE TITLE
Add autoDisplay property to the documentation

### ISSUE THREAD

**Issue by umdstu** [primefaces/primeng#8562]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
N/A - See https://www.primefaces.org/primeng/#/menubar

**Current behavior**
No documentation for the `autoDisplay` option for `<p-menubar></p-menubar>` on https://www.primefaces.org/primeng/#/menubar

**Expected behavior**
The entry in the table indicates the optional setting and it's type.

**Minimal reproduction of the problem with instructions**
Visit link above, scroll to Properties, and look for `autoDisplay`. It's not on the page.

**What is the motivation / use case for changing the behavior?**
So people know what is available.

**Please tell us about your environment:**
N/A

* **Angular version:** 5.X
7.2

* **PrimeNG version:** 5.X
Latest

* **Browser:** 
All
 
* **Language:** 
N/A

* **Node (for AoT issues):**
N/A

**Comment by yigitfindikli** [comment]
Hi @umdstu,
MenuBar doesn't have a AutoDisplay property, MenuBarSub does.
