### ISSUE TITLE
ng-template not working when node-data has "type" property set

### ISSUE THREAD

**Issue by gschafra** [primefaces/primeng#8565]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Stackblitz Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/primeng-tree-type-bug

**Current behavior**
Node/item template (input) is not used/shown if "type" property of node is set

**Expected behavior**
Show item template even if type property is set

**Minimal reproduction of the problem with instructions**
See Stackblitz

**Please tell us about your environment:**

* **Angular version:** v8.2.12

* **PrimeNG version:** v8.1.1

* **Browser:** Chrome 80

 * **Language:** TypeScript  >= v3.4

**Comment by cagataycivici** [comment]
You need to define a template for "type", type is used for multiple templating. Please review the documentation.
