### ISSUE TITLE
Extend calendar component

### ISSUE THREAD

**Issue by LucasAlumni** [primefaces/primeng#8571]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[x] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
I try to extend p-calendar but i got an error: 

> Property 'zone' is private and only accessible within class 'Calendar'

**Expected behavior**
Change property private to public for NgZone ?

**Minimal reproduction of the problem with instructions**
`
export class MyCalendarComponent extends Calendar {
  constructor(
    @Inject(forwardRef(() => Calendar)) pcalendar: Calendar
  ) {
    super(pcalendar.el, pcalendar.renderer, pcalendar.cd, pcalendar.zone)
  }
}
`

**What is the motivation / use case for changing the behavior?**
Migrate my project(NG:7.2, PRIMENG:7) to Angular 8 and Primeng 8

* **Angular version:** 8.2

* **PrimeNG version:** 8.1.1

 
* **Language:** [TypeScript 3.5.x]

**Comment by cagataycivici** [comment]
Please use forum for support requests and questions.
