### ISSUE TITLE
p-dialog and p-confirmDialog not centered when set appendTo body

### ISSUE THREAD

**Issue by nguyenhoangphuc289** [primefaces/primeng#8573]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Dialog and ConfirmDialog appendTo body not center

**Expected behavior**
Dialog and ConfirmDialog appendTo body must be centered.

**Please tell us about your environment:**

* **Angular version:** 8.2.11

* **PrimeNG version:** 9.0.0-rc.3

* **Browser:** Chrome

**Comment by ThorstenKunz** [comment]
Angular version: 9.0.4

PrimeNG version: 9.0.0

Browser: Chrome

I have a very similar issue. If I create a modal dialog with appendTo="body" the dialog doesn't event show. The screen gets locked with the mask but that is it. Not dialog appears.

**Comment by sven42** [comment]
Angular version: 9.0.4
PrimeNG version: 9.0.0
Browser: Chrome

I have the same issue as ThorstenKunz: the dialog is not visible with appendTo="body".

Without this being set, the dialog is visible, but with [modal]="true" it has an opacity of 0.5 due to parent divs class "ui-widget-overlay"

**Comment by jakub-tucek** [comment]
Angular version: 9.0.2
PrimeNG version: 9.0.0
Browser: Chrome

Same issues - if appended to body, dialog position must be styled manually. If not appended, opacity is 0.5. This would be ok workaround, except overlay is missing for modal in production build, which is kinda strange.

**Comment by dloprodu** [comment]
I have the same issue. It seems that the dialog mask is kept in the local component meanwhile the content is appended to the body. In previous versions, dialog-mask and dialog were appended to the body.

**Comment by lxrave** [comment]
Hi. I have the same issue. All dialogs broken ( displaying only overlay without any content) after App upgraded to PrimeNG 9.0.0

Angular version: 9.0.5
PrimeNG version: 9.0.0
Browser: Chrome

**Comment by zakharenkov** [comment]
Hi. I have the same issue after I was upgraded MyApp to PrimeNG 9.0.5
