### ISSUE TITLE
TurboTable reload data automaticly scrolls down

### ISSUE THREAD

**Issue by codehunter13** [primefaces/primeng#8574]
**I'm submitting a ...**  (check one with "x")
[ x] bug report => Search github for a similar issue or PR before submitting
**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-fuw6qf

**Current behavior**
if you scroll down in a Turbotable (with virtual scrolling), then reload the data , the table automaticly scrolls further down instead of staying on the same record.
In the plunkr case: scroll a little down. Then each press on the reload button performs a scroll down

**Expected behavior**
Stay on the same row after new data is assigned to the table

* **Angular version:** 9.0.1

* **PrimeNG version:** 9.0.0-rc.4

**Comment by cagataycivici** [comment]
VirtualScrolling for Table is reimplemented from the ground up (#8855) and this particular case i no longer an issue with the new implementation.
