### ISSUE TITLE
Max Date allowing hours more than specified

### ISSUE THREAD

**Issue by xDouglasx** [primefaces/primeng#8577]
Hi, im trying to use the calendar with range dates, and range of business hours as well
example: 8h to 20h.

i have this 2 methods:

```
getMaxDate(): Date {
      const maxDate = new Date();
      maxDate.setHours(20);
      maxDate.setDate(maxDate.getDate() + 15);   
      console.log(maxDate);   
      return maxDate;
}

getMinDate(): Date {
      const minDate = new Date();
      minDate.setHours(8);
      console.log(minDate);
      return minDate;
 }
```
and the calendar:

```
<p-calendar
            id="date"
            [locale]="locale"
            [minDate]="getMinDate()"
            [maxDate]="getMaxDate()"
            [showButtonBar]="showButtonBar"
            [showTime]="showTime"
</p-calendar>
```
it works with the min date, the minimum hour i can select its 8.
but doesnt work for the maximum date i can select any hours that i want.
i would expect the same behaviour of minimum date. (allow me to select hours until 20)

also when you select the hour 00: it blocks the time and i cant change the hours or the minutes.
i think it is possibly a bug.

but i would suggest a option for time.
something like "timeRange" or "maxHour" and "minHour" and maybe for minutes as well
it can be usefull for a lot of use cases.

* **PrimeNG version:** 9.0.0-rc4

* **Browser:** [all | Chrome XX |
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by cagataycivici** [comment]
#7381
