### ISSUE TITLE
"Unexpected value 'CalendarModule' imported by the module"

### ISSUE THREAD

**Issue by lukeify** [primefaces/primeng#858]
Using PrimeNG 1.0.0-beta.14 with Angular 2 RC.6:

Given the following project setup:

**app.module.ts**:

```
...
import {CalendarModule} from 'primeng/components/calendar/calendar';

@NgModule({
    imports: [FormsModule, BrowserModule, CalendarModule],
    declarations: [SupportAppComponent],    
    providers: [SupportService],
    bootstrap: [SupportAppComponent]
})
export class SupportAppModule { }
```

**main.ts**:

```
...
platformBrowserDynamic().bootstrapModule(SupportAppModule);
```

I receive the following error in the browser:
`Uncaught Error: Unexpected value 'CalendarModule' imported by the module 'SupportAppModule'`

from compiler.umd.js:14118.

**Comment by moxival** [comment]
This should be fixed on master branch https://github.com/primefaces/primeng/issues/833#issuecomment-244219999

**Comment by edoardoVD** [comment]
@LukeNZ 

Check out: 
https://github.com/primefaces/primeng/issues/854#issuecomment-245437564
Barrel up the primeNg components

**Comment by bradseefeld** [comment]
@edoardoVD, is that still the expected workflow? To barrel up all the components?

I am running into the same error, but using primeng 1.1.3 and angular 2.3.1

**Comment by bradseefeld** [comment]
Barreling is not required. See #1627

**Comment by edoardoVD** [comment]
@bradseefeld Hi there

Barrelling is not required, agree, the reported issues had to do with a change on angular (ng modules), prime ng was subsequently updated/fixed. 

Barrelling I just use it, to avoid importing directives/classes on several modules, I just do it once and that is it, all of them are available on my entire app.

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.

**Comment by siddharthgpatel** [comment]
Yes, Issue still persists...
In my package.json...
Uncaught Error: Unexpected value 'undefined' imported by the module 'DropdownModule'
    at syntaxError (compiler.js:1021)
    at compiler.js:10589
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata (compiler.js:10558)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleSummary (compiler.js:10493)
    at compiler.js:10580
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata (compiler.js:10558)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleSummary (compiler.js:10493)
    at compiler.js:10580

**Comment by Marooned-MB** [comment]
`Uncaught Error: Unexpected value 'undefined' imported by the module 'DropdownModule'`
I have the same issue while using Angular 6.1. No issue when using 7.2.
Issue is only for some modules.. for example, ButtonModule or MenuModule is working while TableModule or DropdownModule causes this error.
