### ISSUE TITLE
closeOnEscape  - Stop working

### ISSUE THREAD

**Issue by uthakkar91** [primefaces/primeng#8580]
if a p-dialog component contains a form input like a drop down or calendar, interacting with the form input in any way causes closeOnEscape to stop working.

**Comment by cmario92** [comment]
any updates on when we should expect this?

**Comment by FabienDehopre** [comment]
I have the same issue but with the dynamic dialogs which contain input fields of all sort (input, select, etc...)

**Comment by cmario92** [comment]
any updates or workarounds for `closeOnEscape` for `p-dialog`?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
