### ISSUE TITLE
Drag does not work on Dialogs with position set

### ISSUE THREAD

**Issue by mconner** [primefaces/primeng#8581]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

[Stackblitz simple dialog with position and draggable](https://stackblitz.com/edit/github-vxhfov)

**Current behavior**

When you drag a dialog that has a position set to 'top', it snaps over to the right partly outside the window, and moves down to the bottom as you continue dragging the mouse in any direction. 

**Expected behavior**

When you drag a dialog, it moves with the mouse.   I would expect that if the dialog had a position, it starts there, but if draggable, allows you to drag it to a new position.

Related:  I tried using the documented positionTop and positionLeft, instead of position, and they don't seem to work at all.

**Minimal reproduction of the problem with instructions**

1. Click on the stackblitz example link, above,
2 Enlarge the window so you have some dragging room, if necessary
2. Click ToggleVisible to open the dialog
3. Try to drag the dialog to the left
You will see that the dialog moves over to the right and down the screen as you drag.

**What is the motivation / use case for changing the behavior?**

Drag should work

**Please tell us about your environment:**

Windows 10, IntelliJ, npm 

* **Angular version:**
 9.0.1

* **PrimeNG version:** 9.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Google Chrome: Version 79.0.3945.130 (Official Build) (64-bit)
Microsoft Edge:  44.17763.831.0, 

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5] 
TypeScript 3.5.7

* **Node (for AoT issues):** `node --version` =   
12.16.1

**Comment by mconner** [comment]
I've found the following workaround. (Or maybe this is how it should be done, but I didn't find good documentation).  

- First the positionTop and positionLeft dont seem to work. Don't use them.
- Use the style for the position, as well as the dimension(s)
- Don't set the position (i.e no top, left, bottom, right, etc)

This allows you to set an initial top (and/or left), and drag still works properly.  Unfortunately the enter/leave animations still work as if no position is set.  but you can get a ViewChild on the dialog, and set the transformOptions directly.  It would be nice if this was and Input, but it works.
[Here's a stackblitz](https://stackblitz.com/edit/github-vxhfov-hy5hx7)

In fact, it works quite nicely, because if you resize when top is set, it keeps it centered until you actually move the dialog.

**Comment by ayselmehmetzade** [comment]
Is there a detailed document about this problem. I have the same problem even though I am not using a position set
