### ISSUE TITLE
onColReOrder does not fire. no data emitted

### ISSUE THREAD

**Issue by gshock** [primefaces/primeng#8583]
[X ] bug report => Search github for a similar issue or PR before submitting

I also reviewed [the source of table.ts](https://github.com/primefaces/primeng/blob/master/src/app/components/table/table.ts), where 
Line 1776: 
`this.onColReorder.emit({
 dragIndex: dragIndex,
 dropIndex: dropIndex,
 columns: this.columns
 });`

I reviewed issues below, which have been closed. 
- [#2399](https://github.com/primefaces/primeng/issues/2399)
- [#3910](https://github.com/primefaces/primeng/issues/3910)

I created the simplest example (not scrollable) using OnColReorder and OnColResize, with reorderableColumns and resizableColumns = true, OnColResize works as expected, but still can't figure out what's wrong with OnColReorder, or how to get the data from the event onColReOrder 

StackBlitz:
[link to issue demo on StackBlitz](https://stackblitz.com/edit/github-qzqvjb)

**Current behavior**
p-table onColReOrder event does not emit anything

**Expected behavior**
per v8 Table documentation, it should emit: 
event.dragIndex: Index of the dragged column
event.dropIndex: Index of the dropped column
event.columns: Columns array after reorder

**Minimal reproduction of the problem with instructions**
1. Go to the StackBlitz editor and wait for sample to load
2. Open editor console
3. Resize a column, observe console for data emitted 
4. Reorder a column, observe no data in console

**What is the motivation / use case for changing the behavior?**
I need to save the new column order as a user preference

**Please tell us about your environment:**
Windows 10, VS Code. It also does not work in StackBlitz

* **Angular version:** 8.2.14
I updated my main project to NG version 8.2.14, and it still doesn't work 

* **PrimeNG version:** 8.1.1
I updated my main project to primeng version 8.1.1, and it still doesn't work

* **Browser:** 
Chrome, Edge (latest)
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
My typescript is at version 3.7.5 

* **Node (for AoT issues):** `node --version` =   
my Node is at version 12.14.1

**Comment by gshock** [comment]
Hi, I am trying to fix this bug, but how do you normally debug this source? 
I git-cloned the source, and npm install... but I use VS CODE and I'm getting an error, and when I look at the sources in Chrome debugger they are already transpiled JS. 

What is your setup? Any tips would help a lot since this is my first time debugging an npm package source. Thanks in advance for any helpful tips. 

G-

**Comment by gshock** [comment]
I have observed, in my local debug, that as soon as the this.onColResize.emit() gets hit in table.ts, the debugger jumps directly to the event handler configured to handle the resize event. 

It doesn't do the same thing when the line this.onColReorder.emit() gets hit.

**Comment by yigitfindikli** [comment]
You need to use (onColReOrder)="onColReOrder($event)" not (onColReOrder)="onColReOrder($event)"

**Comment by gshock** [comment]
Hmmm, that's my error in the StackBlitz. It still doesn't work in my main project, but I know for sure now that it is on my end. Thanks!!
