### ISSUE TITLE
Hovering on timepicker arrows acting like select

### ISSUE THREAD

**Issue by dck5132** [primefaces/primeng#8584]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewed in detail and assisted.

<https://primefaces.org/primeng/#/calendar> 

**Current behavior**
When hovering over the time picker's arrows it selects that time and date without a user explicitly clicking on an arrow

**Expected behavior**
Hovering over the time picker's arrows should not select a time and date - user explicitly clicking on the arrow should select a time and date

**Minimal reproduction of the problem with instructions**
1. Select the example calendar for time 
![image](https://user-images.githubusercontent.com/18180081/75562322-63e5b400-5a16-11ea-82d4-3ec264d58796.png)
2. Hover mouse cursor over one of the time picker arrows
![image](https://user-images.githubusercontent.com/18180081/75562535-bc1cb600-5a16-11ea-85f4-af3a1378a02d.png)

**What is the motivation / use case for changing the behavior?**
Previously only explicitly selecting one of the time picker arrows or selecting a date on the calendar would add a date and time - as it stands now the functionality is unexpected and there is no way to disable it.

**Please tell us about your environment:**
Windows 10, VS Code.

* **Angular version:** 9.0.2

* **PrimeNG version:** 9.0.0

* **Browser:** [Chrome Latest| Firefox Latest| IE 11]
 
* **Language:** [TypeScript 3.7.5]

* **Node (for AoT issues):** `node --version` =   12.3.1

**Comment by phamnhat1995** [comment]
I'm also facing this issue.
https://stackblitz.com/edit/primeng-calendar-show-time-mouseout-issue
The problem is mousing in and out the timepicker arrows also fire the onSelect event which actually not right. The 'onSelect' event should only be fired when we click the arrows not hover it.

**Comment by dck5132** [comment]
As of 9.0.6 this issue still occurs after selecting one of the time picker arrows.

Steps to reproduce on primeng website <https://www.primefaces.org/primeng/showcase/#/calendar> 

1. Select the Calendar labeled Time
2. Select one of the time picker arrows
3. Delete the existing date in the input bar
4. Hover over any of the time picker arrows and the unexpected functionality manifests

**Comment by jonnomk** [comment]
Hello.  This still happens in version 11.2.3.
