### ISSUE TITLE
Table cannot handle % scrollHeight with Frozen Columns

### ISSUE THREAD

**Issue by daleclements** [primefaces/primeng#8586]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-ighhxb

**Current behavior**
When a Table has a frozen column, "scrollHeight=100%", or any % for that matter will result in bad height calculation. When you switch the scrollHeight in the stackblitz above between "100px" and "100%" you can clearly see that the height calculations are wrong in the % version.

More specifically:
Within "setScrollHeight" in table.ts, the "staticHeight" is calculated. This variable is supposed to be the height of the static content (headers, footers, etc). It is calculated by subtracting 100 from the containerHeight, which is the height of the first div inside the p-table node (the ".ui-table" div). Why 100? It looks like because the "scrollBodyViewChild" was set to be 100px height, so anything extra would be static.

However when there is a frozen column, this function gets called for both the frozen view and then scrollable view. When it gets called for the scrollable view, the "ui-table" div is no longer only as big as the static content + the 100px of the "scrollBodyViewChild" because the frozen view has a height which has caused the ".ui-table" div to grow to fit it. Since we're still only subtracting 100 from the "containerHeight" to get the staticHeight, we get a very large staticHeight, which results in a very small scrollBodyHeight.

ADDITIONALLY: the size of the horizontal scroll bar is subtracted from the scrollBodyHeight if (this.frozen=true) but just because this.frozen=true does not mean that a horizontal scroll bar is actually displayed. If there were not enough columns to force a horizontal scroll, the bar would not be displayed but its size is still subtracted from the scrollBodyHeight

* **Angular version:** 8.X

* **PrimeNG version:** 8.X

**Comment by cagataycivici** [comment]
See

https://github.com/primefaces/primeng/issues/8618

Will be available in PrimeNG 7-8 for LTS subscribers as well.
