### ISSUE TITLE
I can't Import primng9 with systemjs@0.21.6

### ISSUE THREAD

**Issue by zornic84** [primefaces/primeng#8589]
I'm submitting a ...

[ ] bug report
[ ] feature request
[X ] support request

Current behavior
With primeng8 i can import with systemjs@0.21.6
`/**
 * System configuration for Angular samples
 * Adjust as necessary for your application needs.
 */
(function (global) {
    System.appVersion = '1.0.0';
    System.config({
        transpiler: 'typescript',
        typescriptOptions: {
            "target": "es5",
            "module": "commonjs",
            "moduleResolution": "node",
            "sourceMap": true,
            "emitDecoratorMetadata": true,
            "experimentalDecorators": true
        },
        paths: {
            // paths serve as alias
            'npm:': 'node_modules/'
        },
        // map tells the System loader where to look for things
        map: {
            // our app is within the app folder
            'app': 'CientApp/app',

            // angular bundles
            '@angular/core': 'npm:@angular/core/bundles/core.umd.js?v=' + System.appVersion,
            '@angular/common': 'npm:@angular/common/bundles/common.umd.js?v=' + System.appVersion,
            '@angular/common/http': 'npm:@angular/common/bundles/common-http.umd.js?v=' + System.appVersion,
            '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js?v=' + System.appVersion,
            '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js?v=' + System.appVersion,
            '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js?v=' + System.appVersion,
            '@angular/http': 'npm:@angular/http/bundles/http.umd.js?v=' + System.appVersion,
            '@angular/router': 'npm:@angular/router/bundles/router.umd.js?v=' + System.appVersion,
            '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js?v=' + System.appVersion,

            '@angular/animations': 'npm:@angular/animations/bundles/animations.umd.js?v=' + System.appVersion,
            '@angular/animations/browser': 'npm:@angular/animations/bundles/animations-browser.umd.js?v=' + System.appVersion,
            '@angular/platform-browser/animations': 'npm:@angular/platform-browser/bundles/platform-browser-animations.umd.js?v=' + System.appVersion,

            '@angular/cdk': 'npm:@angular/cdk/bundles/cdk.umd.js?v=' + System.appVersion,
            '@angular/cdk/a11y': 'npm:/@angular/cdk/bundles/cdk-a11y.umd.js?v=' + System.appVersion,
            '@angular/cdk/bidi': 'npm:/@angular/cdk/bundles/cdk-bidi.umd.js?v=' + System.appVersion,
            '@angular/cdk/observers': 'npm:/@angular/cdk/bundles/cdk-observers.umd.js?v=' + System.appVersion,
            '@angular/cdk/overlay': 'npm:/@angular/cdk/bundles/cdk-overlay.umd.js?v=' + System.appVersion,
            '@angular/cdk/portal': 'npm:/@angular/cdk/bundles/cdk-portal.umd.js?v=' + System.appVersion,
            '@angular/cdk/scrolling': 'npm:/@angular/cdk/bundles/cdk-scrolling.umd.js?v=' + System.appVersion,
            '@angular/cdk/platform': 'npm:/@angular/cdk/bundles/cdk-platform.umd.js?v=' + System.appVersion,
            '@angular/cdk/keycodes': 'npm:/@angular/cdk/bundles/cdk-keycodes.umd.js?v=' + System.appVersion,
            '@angular/cdk/coercion': 'npm:/@angular/cdk/bundles/cdk-coercion.umd.js?v=' + System.appVersion,
            '@angular/cdk/collections': 'npm:/@angular/cdk/bundles/cdk-collections.umd.js?v=' + System.appVersion,
            '@angular/cdk/rxjs': 'npm:/@angular/cdk/bundles/cdk-rxjs.umd.js?v=' + System.appVersion,
            '@angular/cdk/table': 'npm:/@angular/cdk/bundles/cdk-table.umd.js?v=' + System.appVersion,

            // other libraries
            'rxjs': 'npm:rxjs',
            'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js',

            'primeng': 'npm:primeng'
        },
        // packages tells the System loader how to load when no filename and/or no extension
        packages: {
            app: {
                defaultExtension: 'js',
                meta: {
                    './*.js': {
                        loader: 'CientApp/systemjs-angular-loader.js'
                    }
                }
            },
            'rxjs': { main: 'index', defaultExtension: 'js?v=' + System.appVersion },
            'rxjs/ajax': { main: 'index', defaultExtension: 'js?v=' + System.appVersion },
            'rxjs/operators': { main: 'index', defaultExtension: 'js?v=' + System.appVersion },
            'rxjs/testing': { main: 'index', defaultExtension: 'js?v=' + System.appVersion },
            'rxjs/webSocket': { main: 'index', defaultExtension: 'js?v=' + System.appVersion },
            'primeng': { defaultExtension: 'js?v=' + System.appVersion, },
        }
    });
})(this);`

Expected behavior
I would expect the import works with primeng9.

Please tell us about your environment:
Angular version: 9.0.4
PrimeNG version: 9.0.0
Browser: Chrome
Language: TypeScript 3.7.5

**Comment by cagataycivici** [comment]
PrimeNG 9 uses ng-packagr, so you may want to check how to use System.js with ng-packagr.
