### ISSUE TITLE
Datatable scrollable="true" breaks column template header

### ISSUE THREAD

**Issue by mcfin** [primefaces/primeng#859]
Hi PrimeNG Team,

I've found that when setting `scrolling="true"`, the datatable does not properly apply the template using `pTemplate type="header"`. 
The template using `pTemplate type="body"` does work though.

**Comment by erlopezh** [comment]
Same problem here.

**Comment by kethan** [comment]
Please how to resolve this... i am using it in production...

**Comment by idanmalka** [comment]
am i missing something? i cant find a way to fix the header allignment too

**Comment by ctrl-brk** [comment]
There's kind of hack to fix it. See this post:
http://forum.primefaces.org/viewtopic.php?f=35&t=48781
