### ISSUE TITLE
DialogService import does not work

### ISSUE THREAD

**Issue by jaworek** [primefaces/primeng#8590]
```
[X ] bug report
```

**Current behavior**
I'm trying to update my project from Angular 8 to 9. I updated `primeng` package and other related packages. In the migration guide it is stated that this update is "Drop-in replacement".
https://github.com/primefaces/primeng/wiki/Migration-Guide

In my project I'm using DialogService. In PrimeNG 8 it was imported using this path `import { DialogService } from 'primeng/api'`. In PrimeNG 9 it seems that this import does not work and the path needs to be shortened to just 'primeng'.

I checked documentation of `DynamicDialog` and I found that old version of import is mentioned:
https://www.primefaces.org/primeng/#/dynamicdialog

**Expected behavior**
I expect that old way of importing should work as I did not find this problem occur with other services.

**Minimal reproduction of the problem with instructions**

https://stackblitz.com/edit/github-rvt1kj

**Please tell us about your environment:**

OS: MacOS 10.15.2
Package manager: npm

* **Angular version:** 9.0.4

* **PrimeNG version:** 9.0.0

* **Browser:** [all]

* **Language:** [TypeScript 3.7]

* **Node (for AoT issues):** `node --version` =   12.14.1

**Comment by jaworek** [comment]
I noticed that if I do import of entire `primeng` package it also causes problem that you have to install all peer dependencies, even if they are not used, e.g. `quill`, `@fullcalendar/core` and `chart.js`.

**Comment by yigitfindikli** [comment]
Hi, @jaworek you can use "import { DialogService } from 'primeng/primeng'". Thanks for the report, we'll update the documentation.

**Comment by jaworek** [comment]
I think it is better to use 'primeng/dynamicdialog', as it only imports needed stuff.
