### ISSUE TITLE
[bug] ConfirmDialog closed if there is a previous ConfirmDialog in transition to void (and possible solution)

### ISSUE THREAD

**Issue by jmesa-sistel** [primefaces/primeng#8593]
Hello @yigitfindikli 

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**

If you launch 2 ConfirmDialogs in cascade the second one is closed

**Expected behavior**

Show the 2 ConfirmDialogs

**Minimal reproduction of the problem with instructions**

Just launch another ConfirmDialog in onAccept of another ConfirmDialog 

**What is the motivation / use case for changing the behavior?**

The easy solution is modify onAnimationEnd function in confirmdialog.ts. But not sure if it is the right approach.
```
onAnimationEnd(event) {
        switch (event.toState) {
            case 'void':   
                if (!this.visible) { // <-- do not hide if is visible because ConfirmDialog is being showed
                    this.onOverlayHide();
                }
                break;
        }
    }

```
**Please tell us about your environment:**

* **Angular version:** 9.0.4

* **PrimeNG version:** 9.0.0

**Comment by yigitfindikli** [comment]
Hi, 
You need to use key property like this; https://stackblitz.com/edit/github-mhmh2w

**Comment by jmesa-sistel** [comment]
@yigitfindikli 
I do not want 2 'confirm dialogs', I use only one.
You launch the confirm dialog then you close it and if you try to launch it again before animation is finished (about 150ms) then the second time you launch the dialog this dialog will be closed immediately.
I use a service to show different messages/dialogs using the same 'confirm dialog'.

I have fixed it locally using the hack explained in op.
My hack:
```
constructor(.....) {
..........
        // TODO: delete when https://github.com/primefaces/primeng/issues/8593 is fixed
        ConfirmDialog.prototype.onAnimationEnd = this.onAnimationEndFixed;
    }

    // TODO: delete when https://github.com/primefaces/primeng/issues/8593 is fixed
    onAnimationEndFixed(event) {
        const self: ConfirmDialog = this as any;
        switch (event.toState) {
            case 'void':
                if (!self.visible) { // <-- do not hide if is visible because ConfirmDialog is being showed
                    self.onOverlayHide();
                }
                break;
        }
    }
```

Hope I have described the bug better.

**Comment by yigitfindikli** [comment]
Thanks for the new description @jmesa-sistel. I'll review it again.

**Comment by cagataycivici** [comment]
It is suggested to use two confirm dialogs in cases like these.

**Comment by jmesa-sistel** [comment]
@cagataycivici I think I do not explain myself.
In this case there is a service that manages one dialog, so in a case like this there is one dialog only.
The problem is the service cannot trigger the dialog while is being closed due the closing animation (about 150ms), so if I have to use the service again I have to wait 150ms.
It is a common service to all my app, so I have not to create a lot of confirm dialogs, just use the service. The little patch fix the issue.
For me this is a bug, not a important bug but it is.
If you want to show the same dialog twice you have to wait for the closing animation. You have a var (visible) to control if the object is being showing, so when the animation end just do not hide the overlay if the object is visible.
