### ISSUE TITLE
Table don't search in values

### ISSUE THREAD

**Issue by sdns** [primefaces/primeng#8594]
Hi, I am using primeng "table" module to show my user's list. I get the user's status from the server. It is 0 or 1. and I show user status in the `<td>` similar this:
```
<ng-template pTemplate="body" let-ngpRow let-rowIndex="rowIndex" let-columns="columns">
<tr>
    ...
    <td>
        <span *ngIf="ngpRow.user_status=='0'">deactive</span>
        <span *ngIf="ngpRow.user_status=='1'">active</span>
    </td>
    ...
</tr>
```
And I define columns similar this:
```
this.ngpCols = [
    { field: 'user_fullname', header: 'Full Name' },
    //...
    { field: 'user_status', header: 'Status' },
];
```

Now when I search in the table for the word `active`, it doesn't show anything. The search works with `0` or `1`, and don't work with `active` or `deactive`.

What I can do?

**Comment by cagataycivici** [comment]
Please use forum for support requests and questions.
