### ISSUE TITLE
Position property do not exist in ConfirmDialog

### ISSUE THREAD

**Issue by Yorkfv** [primefaces/primeng#8595]
I'm submitting a ... (check one with "x")

`
[x] error 
`

**Plunkr Case (Bug Reports)**
https://www.primefaces.org/primeng/#/confirmdialog

**Html section code**
`
<p-confirmDialog [style]="{width: '25vw'}" [position]="'bottom'" [baseZIndex]="10000"></p-confirmDialog>
`

**Current behavior**
System crash, error on console `Error: Template parse errors: Can't bind to 'position' since it isn't a known property of 'p-confirmDialog'.`

**Expected behavior**
Show confirmation dialog at bottom on the page (like a documentation page sample).

- **Angular version:** 8.0.0
- **PrimeNG version:** primeng-lts
- **Theme installed:** ultima-ng-8.0.0

**Comment by yigitfindikli** [comment]
You need to use PrimeNG V9.
