### ISSUE TITLE
Datatable scrollable="true" breaks selectionMode="multiple"

### ISSUE THREAD

**Issue by mcfin** [primefaces/primeng#860]
Hi PrimeNG Team,

I've found that when setting  `scrolling="true"` , the datatable does not properly apply the behavior for `selectionMode="multiple"` - no checkboxes appear and selection events don't fire.

Everything works as expected without the `scrolling="true"` attribute, but would like to use the component's built in scrolling.

Thanks

**Comment by jlin21** [comment]
+1

**Comment by Gauravkr** [comment]
+1

**Comment by vvvttt** [comment]
Did you get the scrolling working along with selecitonmode?

**Comment by SaravananSeenivasan** [comment]
Any possible workaround available?

**Comment by ctrl-brk** [comment]
Scrollable also breaks resizable and reordable functionality.
Here's the issue I created:
[https://github.com/primefaces/primeng/issues/1005](https://github.com/primefaces/primeng/issues/1005)

**Comment by nkagarw** [comment]
Please fix it. Waiting for it.
