### ISSUE TITLE
Enhance shiftkey support for Table

### ISSUE THREAD

**Issue by hallidev** [primefaces/primeng#8600]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

primeng 7:
https://stackblitz.com/edit/github-yphbz7-zbghod

primeng 8:
https://stackblitz.com/edit/angular-pqjhcr

**Current behavior**
Row selection does not persist across pages

**Expected behavior**
Row selection should persist across pages (behavior from version 7 or earlier)

**Minimal reproduction of the problem with instructions**
In the version 7 sample, click a row on the first page, go to the second page, and shift-click a row. You will see that all rows between the first and second selection are highlighted, even across pages.

In the version 8 sample, performing the same steps entirely loses the selection and simply selects the last row clicked.

This behavior is also broken on the latest version (9.0.0)

**Please tell us about your environment:**

* **Angular version:** 9.0.3

* **PrimeNG version:** 9.0.0

* **Browser:** all

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/issues/5496
