### ISSUE TITLE
readonly modifier for options at p-dropdown and model at p-splitButton

### ISSUE THREAD

**Issue by IgorMenshikov** [primefaces/primeng#8609]
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Dropdown (p-dropdown) has input "options: any[]".
Splitbutton (p-splitButton) has input "model: MenuItem[]".

**Expected behavior**
These components do not change input values, so it would be good to make them readonly:
- options: readonly any[]
- model: readonly MenuItem[]

**What is the motivation / use case for changing the behavior?**
Right now, we cannot pass readonly arrays with the new strictTemplates Angular 9 mode.

* **Angular version:** 5.X
Angular 9.0.5

* **PrimeNG version:** 5.X
PrimeNG 0.0

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 3.7

**Comment by papb** [comment]
I have the same issue, I believe fixing it is quite straightforward, I will try to do a PR

**Comment by papb** [comment]
This problem also exists for `p-multiselect`

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
