### ISSUE TITLE
Unable to scroll/view filtered column with horizontal scroll in p-table 

### ISSUE THREAD

**Issue by prabu-durairaj** [primefaces/primeng#8612]
<p-table  #dt1  [columns]="cols" [scrollable]="true"   [value]="cars" selectionMode="single" [(selection)]="selectedCar" (onRowSelect)="onRowSelect($event)" [paginator]="true" rows="10">
    <ng-template pTemplate="header" let-columns>
        <tr>
            <th *ngFor="let col of columns" style="width:200px">
                {{col.header}}
            </th>
        </tr>
        <tr>
            <th *ngFor="let col of columns" [ngSwitch]="col.field" class="ui-fluid">
                <input pInputText type="text" (input)="dt1.filter($event.target.value, col.field, col.filterMatchMode)" [value]="dt1.filters[col.field]?.value">
            </th>
        </tr>
    </ng-template>
    <ng-template pTemplate="body" let-rowData let-columns="columns">
        <tr [pSelectableRow]="rowData">
            <td *ngFor="let col of columns" style="width:200px">
                {{rowData[col.field]}}
            </td>
        </tr>
    </ng-template>
    <ng-template pTemplate="emptymessage" let-columns>
        <tr>
            <td [attr.colspan]="columns.length">No Data</td>
        </tr>
    </ng-template>
</p-table>

![table2](https://user-images.githubusercontent.com/4317824/76412836-5b985c00-63ba-11ea-8c03-968e5c91cdd3.png)
After filtering the value in the last column, If there is no match then scroll bar is not available to reset the filter again
![table1](https://user-images.githubusercontent.com/4317824/76412831-59360200-63ba-11ea-8935-0f139d680b28.png)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
