### ISSUE TITLE
p-calendar is not supported keyboard accessibility.

### ISSUE THREAD

**Issue by ssranjith** [primefaces/primeng#8621]
When p-calendar get opened i cannot traverse using keyboard. Because all elements like anchor and button have tabindex="-1".  I do not know why they are setting up tabindex="-1"  for all accessible elements.

**Comment by cagataycivici** [comment]
See;

https://github.com/primefaces/primeng/issues/4695

Use tab and arrow keys go inside the panel, this is implemented according to the section 508 standards.
