### ISSUE TITLE
SelectButtonModule dependency on chart.js seems unnecessary (but maybe a documentation issue)

### ISSUE THREAD

**Issue by ajjensen13** [primefaces/primeng#8622]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
After using SelectButtonModule in my project, I receive an NPM error saying that primeng is missing a dependency on chart.js. I wasn't expecting SelectButton to depend on chart.js and it doesn't seem to be documented https://primefaces.org/primeng/showcase/#/selectbutton or https://primefaces.org/primeng/showcase/#/setup

**Expected behavior**
I was expecting either
1. SelectButton to work without chart.js
2. OR chart.js to be documented as a dependecy for the SelectButton component.

**Minimal reproduction of the problem with instructions**
create an angular-cli application, import SelectButtonModule into the app module, run ng serve

**What is the motivation / use case for changing the behavior?**
Make setup easier.

**Please tell us about your environment:**
Windows 10, WebStorm,

* **Angular version:** 5.X
```
DocDrop> ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 7.3.8
Node: 10.15.3
OS: win32 x64
Angular: <error>
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.13.8 (cli-only)
@angular-devkit/build-angular   <error>
@angular-devkit/core            7.3.8 (cli-only)
@angular-devkit/schematics      7.3.8 (cli-only)
@schematics/angular             7.3.8 (cli-only)
@schematics/update              0.13.8 (cli-only)
rxjs                            6.3.3 (cli-only)
typescript                      3.2.4 (cli-only)
```

* **PrimeNG version:** 5.X
 ```
   "primeicons": "^2.0.0",
    "primeng": "^9.0.0",
```

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
ALL
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 3 ES 5

* **Node (for AoT issues):** `node --version` =   
v10.15.3

**Comment by cagataycivici** [comment]
Probably you are using primeng/primeng to import components, it is deprecated and should be avoided, suggested way is importing from primeng/*

```js
import {SelectButtonModule} from 'primeng/selectbutton';
```

**Comment by ajjensen13** [comment]
I can confirm that this was the issue. Thank you for the reply.
