### ISSUE TITLE
Pressing arrow up key in drag and drop enabled tree selects wrong node

### ISSUE THREAD

**Issue by vendi95** [primefaces/primeng#8623]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-sxgb5x

**Current behavior**
If drag and drop is enabled on the tree pressing arrow up key does not jump to the right node.

![image](https://user-images.githubusercontent.com/14855067/76659978-2174b900-6578-11ea-9046-161e119a9bf9.png)

After arrow up key press Node 1 is selected instead of Node 1.2:

![image](https://user-images.githubusercontent.com/14855067/76660127-79abbb00-6578-11ea-8c22-23488a4756c1.png)

**Expected behavior**
When pressing arrow up key focus should jump to the previous line regardless of node depth. This is the current behavior if drag and drop is not used.

**Comment by vendi95** [comment]
I think this line is wrong:
https://github.com/primefaces/primeng/blob/72c6d2057a7192504e5a84d04fffa08ab289581f/src/app/components/tree/tree.ts#L446

Should be similar to this:
https://github.com/primefaces/primeng/blob/72c6d2057a7192504e5a84d04fffa08ab289581f/src/app/components/tree/tree.ts#L361

Maybe it worth extracting this expression to a function.

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/commit/1a3641d6bc53d75a83e8156344256c9036a1bc65
