### ISSUE TITLE
Can't bind to 'autoWidth' since it isn't a known property of 'p-dropdown'.

### ISSUE THREAD

**Issue by neerajjain92** [primefaces/primeng#8625]
primeng version : ^9.0.0
Angular version: 9.0.6

error when compiling: Can't bind to 'autoWidth' since it isn't a known property of 'p-dropdown'.

```
<p-dropdown  [options]="programs" [autoWidth]="false" [filter]="true" 
        placeholder="{{translationData?.translations | 
        translatePipe: 'webadmin.placeholder.select'}}" 
formControlName="program" required></p-dropdown>
```

This works with an earlier version of prime-ng. What changes are required to make this work?

**Comment by cagataycivici** [comment]
It was removed a year ago I think during 7.

https://github.com/primefaces/primeng/issues/7337

**Comment by EmmanuelKontcheu** [comment]
> primeng version : ^9.0.0
> Angular version: 9.0.6
> 
> error when compiling: Can't bind to 'autoWidth' since it isn't a known property of 'p-dropdown'.
> 
> ```
> <p-dropdown  [options]="programs" [autoWidth]="false" [filter]="true" 
>         placeholder="{{translationData?.translations | 
>         translatePipe: 'webadmin.placeholder.select'}}" 
> formControlName="program" required></p-dropdown>
> ```
> 
> This works with an earlier version of prime-ng. What changes are required to make this work?

I have the same issue, please tell me how to get it work :(
