### ISSUE TITLE
Remove deprecated style classes

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#8630]
Classes that belong to the older styling should be removed;

- ui-state-default
- ui-state-hover
- ui-state-active
- ui-corner-all
- ui-widget-header
- ui-widget-content

**Comment by Rotzbua** [comment]
@cagataycivici Should be reopended. They still show up in code.

**Comment by kellyprankin** [comment]
@cagataycivici What should be used in place of corners classes? The code I inherited is using it quite a bit.
