### ISSUE TITLE
Use loadingbody in regular table according to loading property

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#8633]
loadingbody is only used in VirtualScroll, we should reuse it [loading] is enabled as well.

**Comment by deepakyadav-prilient** [comment]
@cagataycivici This is not working for treetable. Template inside loadingbody/loadingBody (tried with both) not working according to loading property.

**Comment by deepakyadav-prilient** [comment]
> @cagataycivici This is not working for treetable. Template inside loadingbody/loadingBody (tried with both) not working according to loading property with virtualScroll

Edit: without virtual scroll
