### ISSUE TITLE
pCellEditor not triggering edit when clicking on any element inside cell

### ISSUE THREAD

**Issue by jacqueslareau** [primefaces/primeng#8638]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/github-ztjjul

**Current behavior**

Before version 9.0.1, clicking on a whatever element inside the output of the pCellEditor was working. Now it only works on text. Even a simple span element will not trigger the editor.

**Expected behavior**
pCellEditor should trigger the input on click on whatever is inside the cell.

**Minimal reproduction of the problem with instructions**

See stackblitz example. Click on the text saying NOT WORKING and click on the text saying WORKING.

**What is the motivation / use case for changing the behavior?**

We use custom element like badges inside cells to trigger edit and show a dropdown.

**Please tell us about your environment:**

All env

* **Angular version:** 5.X

9.0.7

* **PrimeNG version:** 5.X

9.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Tried on Chrome only.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

* **Node (for AoT issues):** `node --version` =   
v12.12.0

**Comment by cagataycivici** [comment]
Reviewing for today's 9.0.2 hotfix.

**Comment by cagataycivici** [comment]
4.0.2 is released with the fix.

**Comment by jacqueslareau** [comment]
Nice job. Working now. Thank you!
