### ISSUE TITLE
forceSelection for AutoComplete

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#864]
To restrict user only to select values from AutoComplete instead of adding free text.

**Comment by tomaszzmuda** [comment]
+1

**Comment by haykavagyan** [comment]
+1

**Comment by deneshr** [comment]
+1

**Comment by s-nesbigall** [comment]
+1

**Comment by dags** [comment]
+1 Any chance to reactivate this ?

**Comment by cagataycivici** [comment]
This is planned for 4.1.1

**Comment by Menecats** [comment]
Hi, will this feature be available in the 4.1.3?

**Comment by dags** [comment]
Any news about this one ?

**Comment by cagataycivici** [comment]
Set to 4.1.4.
