### ISSUE TITLE
Using latest Primeng 9.0.2 with Ultima theme cause dialog opacity 

### ISSUE THREAD

**Issue by algurov** [primefaces/primeng#8644]
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/angular-9-0-0-rc-1-lpyypp

**Current behavior**
I'm using Angular 9 and Primeng 9 with Ultima theme. After updating to Primeng 9 dialogs are transparent due to .ui-widget-overlay style

**Expected behavior**
Dialogs should not be transparent

**Minimal reproduction of the problem with instructions**
You can reproduce issue on https://stackblitz.com/edit/angular-9-0-0-rc-1-lpyypp

**Please tell us about your environment:**

* **Angular version:** 9.0.6

* **PrimeNG version:** 9.0.2

**Comment by mthor** [comment]
I think it is the same with all themes

**Comment by mthor** [comment]
Don't expect a speedy response, I got a response today on a post from May 2019

**Comment by yigitfindikli** [comment]
Hi @algurov , Ultima v9 not released yet. It will be released this week. If you want quick fix you can simply override with;
_common.scss
```
.ui-widget-overlay {
    background-color: rgb(0,0,0,0.4);
}
```
And please use forum for premium template issues and help requests.
