### ISSUE TITLE
Toast custom template close button

### ISSUE THREAD

**Issue by Michael881188** [primefaces/primeng#8647]
[x ] feature request 

**Current behavior**
I am not able to create my own close button in custom toast because there is no close method i could use.

**Expected behavior**
Add method to message service that removes toast by id or something like that.

* **Angular version:** 8

* **PrimeNG version:** 8.1.1

* **Browser:** all

**Comment by rg1220** [comment]
I'm running into this issue now as well. We were going to use toasts for a long running operation to keep the user informed of the current status of the job. In theory multiple jobs could be performed so I can't clear all toasts before updating a job by creating a new toast.

**Comment by rg1220** [comment]
Just opened up PR https://github.com/primefaces/primeng/pull/10057 to fix this. It adds a function to the message service that allows you to remove a message/toast.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
