### ISSUE TITLE
table Checkbox Selection and Multiple Row Selection conflict

### ISSUE THREAD

**Issue by luoxiao-xy** [primefaces/primeng#8649]
我在table中使用了Checkbox Selection 也使用了Multiple Row Selection。两者应该是可以同时使用。但是实际上，使用Multiple Row Selection选择，两者都能正常选择。全选也能正常工作。但是，使用Checkbox Selection选择的时候是无效的，会产生多个事件，多次选中，然后取消。希望能够修复这个问题。

I used Checkbox Selection and Multiple Row Selection in table. Both should be used at the same time. But in fact, with Multiple Row Selection choice, both can be selected normally. All selections work. However, the selection with Checkbox Selection is invalid. Multiple events will be generated, selected multiple times, and then cancelled. Hope to fix this problem.

**Comment by cagataycivici** [comment]
I'm afraid it is by design they are not compatible at the moment to be used together. In the future we may decide to implement compatibility if there is more demand.
