### ISSUE TITLE
Incorrect Sorting in Datatable (beta13-beta14)

### ISSUE THREAD

**Issue by codedumper** [primefaces/primeng#865]
Sorting function in datatable is not correct : 
- Lowercase & Uppercase are not in correct order (Due to ascii sorting)
- Accent (ÉÈéè and probably others) are at the end.

It probably works correctly for English people but not for other country.
Sorting in angular (RC5) is working fine using localCompare on string.

Temporary workaround is to externalize sorting using compare function : 
myArray.sort(function (a, b) { return a.name.localeCompare(b.name); });

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with them and if issue persists drop a comment and we'll reopen.

**Comment by doramcalderon** [comment]
The issue persists in version 13.3.2.
