### ISSUE TITLE
Dropdown Causing Detached DOM Objects

### ISSUE THREAD

**Issue by t-denis** [primefaces/primeng#8650]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/angular-9-starter-vcarpa

**Current behavior**

Creating a Dropdown nested inside a div with ngIf will leave detached DOM nodes when the ngIf evaluates to false.

**Expected behavior**

The dropdown should clean up after itself and not leave detached DOM nodes

**Minimal reproduction of the problem with instructions**
Click 'Open in a new window' in the editor or use this direct link https://angular-9-starter-vcarpa.stackblitz.io
Toggle visibility few times.
DOM Nodes count will increase.
Chrome develop tools shows that there are detached DOM nodes that never get cleaned up.

**What is the motivation / use case for changing the behavior?**
I don't want to crash my users or give them a bad experience because they ran out of memory.

**Please tell us about your environment:**

Windows 10, VS Code, NPM, Chrome, ng serve

* **Angular version:** 9.0.7

* **PrimeNG version:** 9.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
I don't see a part where dropdown leaves detached objects. Feel free to provide a PR.

**Comment by cagataycivici** [comment]
Provide more instructions on how you use the profile of chrome so we can do the same on our end.

**Comment by t-denis** [comment]
![image](https://user-images.githubusercontent.com/5320360/79765461-53272f80-832f-11ea-859c-6fb0e4bb9aa3.png)

- Open https://angular-9-starter-vcarpa.stackblitz.io
- start developer tools
- open performance monitor (1)
- check DOM Nodes counter is enabled (2)
- run GC (3)
- toggle visibility few times
- run GC (3)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
