### ISSUE TITLE
DialogService bug: ref.onClose.subscribe trigger twice

### ISSUE THREAD

**Issue by WoooTer** [primefaces/primeng#8652]
Hi,
I've just updated my project to Angular 9 and PrimeNG 9.0.0-rc.4.
After the update, the ref.onClose.subscribe(myFunction()) of DialogService library,
myFunction() is called twice.
This didn't happen before the update.
Does anyone know this problem?

Thx
Angelo
- [DialogService bug](https://forum.primefaces.org/viewtopic.php?t=61169）

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Comment by WoooTer** [comment]
@cagataycivici  this bug only appears when calling DynamicDialogRef.close(someData) manually in dynamicComponent.like:

**Comment by alekk84** [comment]
I Get same bug.
Angualr 9.1.0, primeng 9.0.2
On press esc key "onClose" triggered once,  on call this.ref.close() "onClose" triggered twice

**Comment by alekk84** [comment]
https://github.com/alekk84/DynamicDialog

**Comment by mertsincan** [comment]
I think this issue is fixed with https://github.com/primefaces/primeng/issues/8652.

Best Regards,
