### ISSUE TITLE
p-table custom-paginator state.first shows wrong value after rowsPerPage change

### ISSUE THREAD

**Issue by Michael881188** [primefaces/primeng#8654]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report 
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/github/qgnirxral
https://qgnirxral.github.stackblitz.io

**Current behavior**
state.first in paginator doesn't change after rows per page change

**Expected behavior**
state.first should be 0

**Minimal reproduction of the problem with instructions**
Change page to 2 -> change pagination per row to 20
state.first remains 10 instead of change to 0

* **Angular version:** 8

* **PrimeNG version:**8.1.2

* **Browser:** all
 
* **Language:** all

**Comment by cagataycivici** [comment]
You need two-way binding;

https://primefaces.org/primeng/showcase/#/table/page

Also the stackblitz gives 404.

**Comment by Michael881188** [comment]
We are talking about different templates.
Updated stackblitz:
https://stackblitz.com/edit/github-ljitiv
