### ISSUE TITLE
Error when upgrade angular from 8 to 9

### ISSUE THREAD

**Issue by frintezadev** [primefaces/primeng#8657]
Hello, I upgrade angular 8 to 9 and I have issues with primeng : 
1. This likely means that the library (primeng/components/calendar/calendar) which declares CalendarModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

2. This likely means that the library (primeng/components/tree/tree) which declares TreeModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

I use primeng version 9.0.2

**Comment by cagataycivici** [comment]
Please use forum for support requests and questions.

PrimeNG 9 is fully compatible with Angular 9 with or without Ivy
