### ISSUE TITLE
DataTable sorting issue; Date fields not sorting as expected

### ISSUE THREAD

**Issue by JiroDan** [primefaces/primeng#866]
Data table with date columns, formatted for output, sorting on said columns loops through four states.  Expect two states, ascending and descending.  None of four states are as expected.

First sort intermixes blanks with sorted dates - most blanks at end,
Second sort reverses date sort, changes mix of blanks - most blanks at end,
Third sort reverses date sort, most blanks at the end,
Forth sort reverses dates, blanks at the beginning.

Issue:
Blanks should not be mixed into valid data rows, all empty values should be grouped together.
Sorting should be consistent, either empty values part of sort as either lower or higher, or ignored in sort and always after valid values.

**Comment by zlatkovtv** [comment]
I can confirm the issue as explained by the author of the topic. This needs to be fixed as soon as possible.

**Comment by Danieleeee** [comment]
up

**Comment by digitalcraftco** [comment]
Also related to #815. Any pipes used in datatables breaks column sorting.

**Comment by zlatkovtv** [comment]
Edited a workaround in the sourcecode. In datatable.js, In the method "sortSingle", I added `if(value1 == null) {
                        value1 = "";
                    }
                    if(value2 == null) {
                        value2 = "";
                    }` after `var value1 = _this.resolveFieldData(data1, _this.sortField);
                    var value2 = _this.resolveFieldData(data2, _this.sortField);`. This way it compares the null values like empty strings. If you can't find it, it is after line 333.

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
