### ISSUE TITLE
dynamicDialog error primeng 9

### ISSUE THREAD

**Issue by dineshmaths1** [primefaces/primeng#8660]
ERROR in node_modules/primeng/dynamicDialog/dialogservice.d.ts:2:40 - error TS1149: File name '/Users/apple/Documents/sra-admin/node_modules/primeng/dynamicDialog/dynamicdialog.d.ts' differs from already included file name '/Users/apple/Documents/sra-admin/node_modules/primeng/dynamicdialog/dynamicdialog.d.ts' only in casing.

2 import { DynamicDialogComponent } from './dynamicdialog';
                                         ~~~~~~~~~~~~~~~~~
node_modules/primeng/dynamicDialog/dynamicdialog.d.ts:3:38 - error TS1149: File name '/Users/apple/Documents/sra-admin/node_modules/primeng/dynamicDialog/dynamicdialogcontent.d.ts' differs from already included file name '/Users/apple/Documents/sra-admin/node_modules/primeng/dynamicdialog/dynamicdialogcontent.d.ts' only in casing.

3 import { DynamicDialogContent } from './dynamicdialogcontent';
                                       ~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/primeng/dynamicDialog/dynamicdialog.d.ts:4:37 - error TS1149: File name '/Users/apple/Documents/sra-admin/node_modules/primeng/dynamicDialog/dynamicdialog-config.d.ts' differs from already included file name '/Users/apple/Documents/sra-admin/node_modules/primeng/dynamicdialog/dynamicdialog-config.d.ts' only in casing.

4 import { DynamicDialogConfig } from './dynamicdialog-config';
                                      ~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/primeng/dynamicDialog/dynamicdialog.d.ts:5:34 - error TS1149: File name '/Users/apple/Documents/sra-admin/node_modules/primeng/dynamicDialog/dynamicdialog-ref.d.ts' differs from already included file name '/Users/apple/Documents/sra-admin/node_modules/primeng/dynamicdialog/dynamicdialog-ref.d.ts' only in casing.

5 import { DynamicDialogRef } from './dynamicdialog-ref';
                                   ~~~~~~~~~~~~~~~~~~~~~
node_modules/primeng/dynamicDialog/primeng-dynamicdialog.d.ts:4:15 - error TS1149: File name '/Users/apple/Documents/sra-admin/node_modules/primeng/dynamicDialog/public_api.d.ts' differs from already included file name '/Users/apple/Documents/sra-admin/node_modules/primeng/dynamicdialog/public_api.d.ts' only in casing.

4 export * from './public_api';
                ~~~~~~~~~~~~~~
node_modules/primeng/dynamicDialog/public_api.d.ts:1:15 - error TS1149: File name '/Users/apple/Documents/sra-admin/node_modules/primeng/dynamicDialog/dialogservice.d.ts' differs from already included file name '/Users/apple/Documents/sra-admin/node_modules/primeng/dynamicdialog/dialogservice.d.ts' only in casing.

1 export * from './dialogservice';
                ~~~~~~~~~~~~~~~~~
node_modules/primeng/dynamicDialog/public_api.d.ts:4:15 - error TS1149: File name '/Users/apple/Documents/sra-admin/node_modules/primeng/dynamicDialog/dynamicdialog-injector.d.ts' differs from already included file name '/Users/apple/Documents/sra-admin/node_modules/primeng/dynamicdialog/dynamicdialog-injector.d.ts' only in casing.

4 export * from './dynamicdialog-injector';
                ~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/dialog/comment-dialog-edit/comment-dialog-edit.component.ts:3:55 - error TS1149: File name '/Users/apple/Documents/sra-admin/node_modules/primeng/dynamicDialog/primeng-dynamicdialog.d.ts' differs from already included file name '/Users/apple/Documents/sra-admin/node_modules/primeng/dynamicdialog/primeng-dynamicdialog.d.ts' only in casing.

3 import { DynamicDialogConfig, DynamicDialogRef } from 'primeng/dynamicDialog';

while production build am getting this error .
                                                        ~~~~~~~~~~~~~~~~~~~~~~~

**Comment by cagataycivici** [comment]
Not PrimeNG Related, you seem to have a configuration issue in your project, also it should be,

primeng/dynamicdialog'

Please use forum for support requests, questions and cases like these.
