### ISSUE TITLE
feature request: disable months

### ISSUE THREAD

**Issue by Duke-Rong** [primefaces/primeng#8664]
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Add a disable month feature to month picker

**What is the motivation / use case for changing the behavior?**
<!-- Describe the motivation or the concrete use case -->
If the user only have data in certain months, we don't want them to select the months that have no data

**Comment by cagataycivici** [comment]
#8182
