### ISSUE TITLE
DialogService bug: ref.onClose.subscribe trigger twice

### ISSUE THREAD

**Issue by alekk84** [primefaces/primeng#8665]
Angualr 9.1.0, Primeng 9.0.2
On press esc key "onClose" triggered once, on call this.ref.close() "onClose" triggered twice

https://github.com/alekk84/DynamicDialog

**Comment by mertsincan** [comment]
Thanks a lot for the sample project.  I think this issue is fixed with https://github.com/primefaces/primeng/issues/8652.

Note: for now, I'll close this issue. Please let us know if you encounter this problem after this version is released.

Best Regards,
