### ISSUE TITLE
Add default column width option at p-table in case of resizable Columns

### ISSUE THREAD

**Issue by biegeeinheit** [primefaces/primeng#8670]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Minimal reproduction of the problem with instructions**

If you set the option `[resizableColumns]= true`. The user is able to change the width of the table. However, the current implemantation uses equal widths for each column as initial value.
My feature request is to provide the option of setting default widths to the colums that are used instead of the equal widths approch if they are given.

**What is the motivation / use case for changing the behavior?**
It should be possible to use the resizeableColumns function of the p-table with given default widths.
Resizablility is a nice feature, but it does not imply that the columns should have eqaul width in the first place.

**Please tell us about your environment:**
Windows 10

* **Angular version:** 8

* **PrimeNG version:** 8.0.4

* **Browser:** [all]

 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Issue is not clear, please feel free to reopen with a stackblitz example.
