### ISSUE TITLE
RowGroup are not grouped when click on expand row at p-table

### ISSUE THREAD

**Issue by michita** [primefaces/primeng#8673]
**I'm submitting a **
```
[X] bug report => No issues before.
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/angular-1l29ft

**Current behavior**
When I clicked on expand row, the row are not grouping. 
I take the identical example (the first example) on the website of PrimeNG (https://primefaces.org/primeng/showcase/#/table/rowgroup) and I put it on stackblitz and I have the same behavior. 
So I think it's a bug.

**Expected behavior**
When I click to expand row, I'am expected to have rows grouping.

**Minimal reproduction of the problem with instructions**

Look at: https://stackblitz.com/edit/angular-1l29ft

* **Angular version:** 9.0.2

* **PrimeNG version:** 9.0.2

* **Browser:** [all]
 
* **Language:** [all | TypeScript 3.7.5 | ES6]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Please use forum for support requests and questions. The demo works fine.
