### ISSUE TITLE
Latest Angular support?

### ISSUE THREAD

**Issue by cmario92** [primefaces/primeng#8675]
Any ETA for latest Angular support?

package.json
"dependencies": {
"@angular/animations": "^9.1.0",
"@angular/cdk": "^9.2.0",
"@angular/common": "^9.1.0",
"@angular/compiler": "^9.1.0",
"@angular/core": "^9.1.0",
"@angular/flex-layout": "^9.0.0-beta.29",
"@angular/forms": "^9.1.0",
"@angular/http": "^7.2.16",
"@angular/material": "^9.2.0",
"@angular/platform-browser": "^9.1.0",
"@angular/platform-browser-dynamic": "^9.1.0",
"@angular/platform-server": "^9.1.0",
"@angular/router": "^9.1.0",
"primeicons": "^2.0.0",
"primeng": "^9.0.2"
},
"devDependencies": {
"@angular-devkit/build-angular": "~0.901.0",
"@angular/cli": "^9.1.0",
"@angular/compiler-cli": "^9.1.0",
"@angular/language-service": "^9.1.0",
"typescript": "3.8.3"
} 

Sorry for asking, I just wondering if I need to downgrade my Angular version to a primeng compatible version.

Thanks in advance 👍

**Comment by seangwright** [comment]
Angular 9 has been supported for awhile now.

https://github.com/primefaces/primeng/blob/master/CHANGELOG.md#900-rc1-2019-11-26

Angular 9.1 works just fine - I've been using the lastest Prime and Angular 9.1 since it was release 2 days ago.

**Comment by cmario92** [comment]
> Angular 9 has been supported for awhile now.
> 
> https://github.com/primefaces/primeng/blob/master/CHANGELOG.md#900-rc1-2019-11-26
> 
> Angular 9.1 works just fine - I've been using the lastest Prime and Angular 9.1 since it was release 2 days ago.

when I updated to the above dependencies I get the below error:
**- @fullcalendar/core**

Does this need to installed manually? is this part of primeng calendar?
