### ISSUE TITLE
Issue on Datatable with resize and reorder at same time

### ISSUE THREAD

**Issue by fedemarengo** [primefaces/primeng#868]
Datatable with resize and reorder enabled at the same time is not working properly.
If i have enabled both and i try to resize the column to the right the table takes the reorder event as well, so the grid is trying to drag the column (change order) and resize the column. Is working fine when i resize the column to the left.

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with them and if issue persists drop a comment and we'll reopen.
