### ISSUE TITLE
modal-Defines if background should be blocked when dialog is displayed -> Not working on latest version

### ISSUE THREAD

**Issue by cmario92** [primefaces/primeng#8685]
**modal | boolean | false | Defines if background should be blocked when dialog is displayed**

This functionality on latest primeng + Angular

 _"dependencies": {
    "@angular/animations": "^9.1.0",
    "@angular/cdk": "^9.2.0",
    "@angular/common": "^9.1.0",
    "@angular/compiler": "^9.1.0",
    "@angular/core": "^9.1.0",
    "@angular/flex-layout": "^9.0.0-beta.29",
    "@angular/forms": "^9.1.0",
    "@angular/http": "^7.2.16",
    "@angular/material": "^9.2.0",
    "@angular/platform-browser": "^9.1.0",
    "@angular/platform-browser-dynamic": "^9.1.0",
    "@angular/platform-server": "^9.1.0",
    "@angular/router": "^9.1.0",
    "@ng-bootstrap/ng-bootstrap": "^6.0.2",
    "@ngx-translate/core": "^12.1.2",
    "bootstrap": "^4.4.1",
    "chart.js": "^2.9.3",
    "core-js": "^3.6.4",
    "font-awesome": "^4.7.0",
    "jquery": "^3.4.1",
    "lodash": "^4.17.15",
    "ngx-loading": "^8.0.0",
    "primeicons": "^2.0.0",
    "primeng": "^9.0.2",
    "quill": "^1.3.7",
    "rxjs": "^6.5.4",
    "rxjs-compat": "^6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.0",
    "@angular/cli": "^9.1.0",
    "@angular/compiler-cli": "^9.1.0",
    "@angular/language-service": "^9.1.0",
    "@types/jasmine": "^3.5.10",
    "@types/jasminewd2": "^2.0.8",
    "@types/jquery": "^3.3.34",
    "@types/node": "^12.11.1",
    "@typescript-eslint/eslint-plugin": "^2.25.0",
    "@typescript-eslint/eslint-plugin-tslint": "^2.25.0",
    "@typescript-eslint/parser": "^2.25.0",
    "codelyzer": "^5.1.2",
    "eslint": "^6.8.0",
    "eslint-config-prettier": "^6.10.1",
    "eslint-plugin-prettier": "^3.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.1",
    "karma": "^4.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-cli": "~2.0.0",
    "karma-coverage-istanbul-reporter": "^2.1.1",
    "karma-jasmine": "^3.1.1",
    "karma-jasmine-html-reporter": "^1.5.3",
    "prettier": "^2.0.2",
    "protractor": "^5.4.3",
    "ts-node": "~8.8.1",
    "typescript": "3.8.3"
}_

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

See the modal demo at;

https://primefaces.org/primeng/showcase/#/dialog
