### ISSUE TITLE
I have Upgraded the Project from Angular 7 to Angular 9, but Prime-ng give the error (error NG8001: 'p-header' is not a known element:)

### ISSUE THREAD

**Issue by Abhilashtiwari0301** [primefaces/primeng#8686]
Hi Everyone, 

I am facing the Problem after upgrading the Project from Angular 7 to Angular 9. the same thing is worked in Angular 7 , 
Please help.
i have changed the import statement as given below in Angular 9, still facing the same problem.
import { DialogModule } from '../../node_modules/primeng/dialog';

The Errors :- 
error NG8001: 'p-header' is not a known element:
error NG8001: 'p-footer' is not a known element:
If 'p-header' is an Angular component, then verify that it is part of this module.
2. If 'p-header' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
 If 'p-dropdown' is an Angular component and it has 'ngClass' input, then verify that it is part of this module.
If 'p-table' is an Angular component and it has 'sortOrder' input, then verify that it is part of this module.

Package.json

 "dependencies": {
    "@angular/animations": "~9.1.0",
    "@angular/cdk": "^7.2.2",
    "@angular/common": "~9.1.0",
    "@angular/compiler": "~9.1.0",
    "@angular/core": "^9.1.0",
    "@angular/forms": "~9.1.0",
    "@angular/localize": "^9.1.0",
    "@angular/platform-browser": "~9.1.0",
    "@angular/platform-browser-dynamic": "~9.1.0",
    "@angular/router": "~9.1.0",
    "@fullcalendar/core": "^4.4.0",
    "@ng-bootstrap/ng-bootstrap": "^5.3.0",
    "@ng-idle/core": "^8.0.0-beta.4",
    "@swimlane/ngx-charts": "^13.0.1",
    "@types/jquery": "^3.3.34",
    "angular-formio": "^3.12.0",
    "babel-polyfill": "^6.26.0",
    "bootstrap": "4.0.0-beta.2",
    "chart.js": "^2.9.3",
    "core-js": "^2.5.7",
    "date.js": "^0.3.3",
    "flatpickr": "4.5.7",
    "font-awesome": "^4.7.0",
    "fullcalendar": "^3.10.1",
    "jquery": "^3.2.1",
    "lodash": "^4.17.11",
    "moment": "^2.22.2",
    "oidc-client": "^1.6.1",
    "popper.js": "^1.14.4",
    "primeicons": "^2.0.0",
    "primeng": "^9.0.2",
    "quill": "^1.3.7",
    "rxjs": "^6.3.3",
    "rxjs-compat": "6.3.3",
    "tslib": "^1.10.0",
    "xml-js": "^1.6.11",
    "zone.js": "~0.10.2"
  },

**Comment by cagataycivici** [comment]
Please use forum for support requests and questions.
