### ISSUE TITLE
Dialog styleClass - not working on latest primeng

### ISSUE THREAD

**Issue by cmario92** [primefaces/primeng#8687]
**Latest Angular and primeng**
"primeng": "^9.0.2",
"@angular/core": "^9.1.0",

**<p-dialog [(visible)]="displayAddNewEventManuallyModal" (onHide)="onHideDialog()" [dismissableMask]="true"
  styleClass="addModal">**

.addModal {
 width: 50vw;
 border: 2px solid black;
}

@media screen and (max-width: 40em) {
 .addModal {
     width: 75vw;
 }
}

Dialog styleClass, as defined in the docs, is not working.

Am I doing something wrong here?

**Comment by cagataycivici** [comment]
The style class is added and you can see it in dom's inspector, it may not be applied due to viewencapsulation in your case. Try;

```
    styles: [`
        :host ::ng-deep .addModal {
            width: 50vw;
            border: 2px solid black;
        }
    `]
```

**Comment by iHazCode** [comment]
I'm encountering same issue, this worked prior to updating to Prime 9.0.6 and Angular 9. I attempted setting viewEncapsulation to None but no luck. 
My team has resorted to doing everything inline with the style attribute in the meantime until we can figure out what we're doing wrong

**Comment by Jacques-eMediaIT** [comment]
I don't even see the style class being added to the DOM.
