### ISSUE TITLE
table demo multiselect filtering by representatives does not work

### ISSUE THREAD

**Issue by juri-sinitson** [primefaces/primeng#8689]
https://github.com/primefaces/primeng/blob/master/src/app/showcase/components/table/tabledemo.ts
```javascrript
  onRepresentativeChange(event) {
    debugger;
    this.table.filter(event.value, 'representative', 'in')
  }
```
Doesn't work because of object comparison, which is not yet implemented in the in-operator. 
String comparison should be used instead. So this works:
```javascrript
  onRepresentativeChange(event: {value: Representative[]}) {
    const values = event.value.map( (val: Representative) => val.name );
    this.table.filter(values, 'representative.name', 'in');
  }
```
You can see this when you debug the code above, especially when you set a breakpoint in _node_modules/primeng/__ivy_ngcc__/fesm2015/primeng-utils.js_ in the funtion "in". 

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request
```

**Plunkr Case (Bug Reports)**
https://qgnirxral.github.stackblitz.io

**Current behavior**
Unable to filter representatives, the list is empty when filtering

**Expected behavior**
Able to filter representatives. Only the records with those representatives are shown.

**Minimal reproduction of the problem with instructions**
Just copy the source of the general demo, where repsentatives are filtered by the multiselect. This multiselect consists of avatars and names.
https://primefaces.org/primeng/showcase/#/table

**What is the motivation / use case for changing the behavior?**
Usage of multiselect filtering in production. Get rid of needing to correct errors and debug.

**Please tell us about your environment:**
Ubuntu 18.04, VsCode, npm, ng serve and deployment to nodejs

* **Angular version:** ~9.0.6 (currently unable to use 9.1.0 because of issues with @angular-builders/custom-webpack)

* **PrimeNG version:** ^9.0.2

* **Browser:** [Chrome]

 * **Language:** [TypeScript ~3.7.5 | ES6/7 ]

* **Node (for AoT issues):** `node --version` =   v10.13.0

**Comment by cagataycivici** [comment]
Live demo runs on 9.0.3-snapshot as stated at the footer, tomorrow we'll release 9.0.3 so if you upgrade, it should work, sorry for the confusion, we were really excited about the new table demo so put it live before releasing 9.0.3 which is required for the "in" filter.
