### ISSUE TITLE
TurboTable - Multiple rows range selection includes disabled rows

### ISSUE THREAD

**Issue by naitik95** [primefaces/primeng#8690]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Stackblitz case
https://stackblitz.com/edit/github-wxwiqx?file=src%2Fapp%2Fapp.component.html

**Current behavior**
TurboTable multiple rows range selection also includes rows disabled by pSelectableRowDisabled.

**Expected behavior**
Range selection should not include disabled rows.

**Minimal reproduction of the problem with instructions**

 *STEPS TO REPRODUCE*
1. Select 2nd row
2. Select last row using Shift key

You should now be able to see all rows in between selected, even though alternative rows are disabled.

* **PrimeNG version:** I'm using 7.1.3. It's reproducible on 9 as well.

**Comment by naitik95** [comment]
Is it possible to accept a function - rowSelectableFn: (row: any) => boolean - as an Input that could possibly take care of this issue and other similar isssues like header check box toggle selecting all rows instead of only selecting rows with visible checkboxes. I understand checkbox and clickable rows are mutually exclusive at this point.. but it might allow them to be inclusive.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
