### ISSUE TITLE
Tree selection should highlight whole content not just label

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#8691]
e.g.

https://primefaces.org/primereact/showcase/#/tree/selection

**Comment by murieletrentini** [comment]
Hello. Is it possible that in version 9.0.2 not even the label itself get's highlighted on 'single' selection mode or am I duing something wrong?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
