### ISSUE TITLE
Galleria caption cannot be hidden

### ISSUE THREAD

**Issue by jyte** [primefaces/primeng#870]
Setting false to showCaption attribute has no effect.

Edit:
actually, it works, the documentation on the showcase website is incorrect though.
`<p-galleria [images]="images" panelWidth="500" panelHeight="313" showCaption="true"></p-galleria>`
from http://www.primefaces.org/primeng/#/galleria 

this doesn't work `<p-galleria [images]="images" panelWidth="500" panelHeight="313" showCaption="false"></p-galleria>` 

but this does work `<p-galleria [images]="images"  [panelWidth]="500" [panelHeight]="313" [showCaption]="false"></p-galleria>`

**Comment by pauly815** [comment]
Just ran into this as well in 2.0.0.  The square brackets did the trick.  Thanks!
