### ISSUE TITLE
Alignment issue with p-multiseslect

### ISSUE THREAD

**Issue by crazyjavatricks** [primefaces/primeng#8700]
https://www.primefaces.org/primeng/showcase/#/multiselect

Getting an alignment issue in p-multiselect with ng-template.
![image](https://user-images.githubusercontent.com/11722540/78106464-1394b400-7411-11ea-8052-7fb62cc3f2cc.png)

**Expected :**
![image](https://user-images.githubusercontent.com/11722540/78106736-a2093580-7411-11ea-8072-ae108438bbe4.png)
Selected values should be aligned with the component width.

Without using the ng-template , its showing the total number of items selected .
**Sample From PrimeNg documentation.**
![image](https://user-images.githubusercontent.com/11722540/78107268-c7e30a00-7412-11ea-97b0-53f88df7c91b.png)

**Comment by cagataycivici** [comment]
Provide a stackblitz sample that replicates the issue for review please.

**Comment by cagataycivici** [comment]
There is a new built-in token mode in 11.0.0 that resolves this.
