### ISSUE TITLE
question on ngStyle / style for p-button

### ISSUE THREAD

**Issue by sorariver** [primefaces/primeng#8703]
**I'm submitting a ...**  (check one with "x")

[x ] bug report => Search github for a similar issue or PR before submitting

**Plunkr Case (Bug Reports)**
https://qgnirxral.github.stackblitz.io

brief code

 ```
<p-button type="button" styleClass="ui-button-info" [style]="{'float' : 'right'}" label="Print"></p-button>  //doesnt work
 
 <p-button type="button" styleClass="ui-button-info" [ngStyle]="{'float' : 'right'}" label="Print"></p-button>   //work

```

**Current behavior**
[style] doesn't work for float attribute, but ngStyle works.
however primgNG doc only mention style. why? 

**Expected behavior**
[style] suppose to work like [ngStyle]

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**
visual studio
* **Angular version:** 8.

* **PrimeNG version:** 8.

* **Browser:**  Chrome XX 

* **Language:** all 

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Please use forum for support requests and questions.
