### ISSUE TITLE
Add MomentDateAdapter feature to support Persian(Jalali),Hijri calendars

### ISSUE THREAD

**Issue by webnegar** [primefaces/primeng#8706]
[*] feature request  

PrimeNg Calendar does not support Internationalization features to implement Persian(jalali) / Hijri / ...  Calendars.

For example Angular material components supports this feature:
[Internationalization](https://material.angular.io/components/datepicker/overview#internationalization
) and [Setting the selected date](https://material.angular.io/components/datepicker/overview#setting-the-selected-date)  

This features is based on this issues in angular repository:
[Add aditional DateAdapters](https://github.com/angular/components/issues/5972
)

Further resources are: 
[Momentjs library](https://github.com/moment/moment/
)  and [jalali monent github](https://github.com/fingerpich/jalali-moment
)

And finally somone added this feature to Primeng Calendar in this repository:
[PrimeNg-Persian-Calendar github](https://github.com/MasoudBimar/PrimeNg-Persian-Calendar)

But we need native support for this feature in PrimeNg Calendar.

Thanks

**Comment by gh-mohammadi** [comment]
it's true, please add this feature to primeng calendar

**Comment by mojganmahmoodian** [comment]
I have this problem tooo,please solve the problem.thanks

**Comment by mehrta** [comment]
Please redesign p-calendar component to be culture agnostic (like google material date-picker) by writing custom date adapters.

**Comment by RezaMakvandi** [comment]
Please add Persian(Jalali) calendar to primeng

**Comment by PooriaShariatzadeh** [comment]
+1 it will be awesome if we have this features on p-calendar

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by mahmoudparandeh** [comment]
Hi there I cannot find any documentation for <p-calendar> that support Persian (Jalali), if you believe you cover this request, please send documentation or something that we can follow for localizing the calendar not in terms of labels but also the date system.

**Comment by SalehAhmadi** [comment]
Hi there, any update on this? I've searched documents and I couldn't find any info on this. Thanks.
