### ISSUE TITLE
[Feature Request] - TreeTable : Get current selected cell data using context menu

### ISSUE THREAD

**Issue by prawin-s** [primefaces/primeng#8707]
It would be nice if we can get current selected cell data (in addition to getting current selected row data) using context menu. 

Please let me know in case if anyone knows any way or workaround to get a data of the right clicked cell.

**Comment by FahadAnwarHussain** [comment]
@prawin-s  use onNodeSelect event for selecting the selected node value.

**Comment by cagataycivici** [comment]
Please use forum for questions and help requests.
