### ISSUE TITLE
p-fullCalendar inside p-dialog not showing events when resize browser

### ISSUE THREAD

**Issue by roqueorts** [primefaces/primeng#8708]
**I'm submitting a ...**  
```
[x ] bug report 
```

**Plunkr Case (Bug Reports)**
https://qgnirxral.github.stackblitz.io
https://angular-krjydi.stackblitz.io
https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
I have a p-fullCalendar inside p-dialog. When I open dialog, the fullcalendar show the events, also if I close the dialog and open again. But, if I close dialog and then resize window browser, and open dialog, the full calendar shows empty.

**Expected behavior**
show events

**Please tell us about your environment:**
Windows 10

* **Angular version:** 9

* **PrimeNG version:** 9

* **Browser:** Chrome 
 
* **Language:** Typescript: "~3.1.1"

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
