### ISSUE TITLE
issue with default css styles

### ISSUE THREAD

**Issue by dolphinsd** [primefaces/primeng#8713]
with upgrade to v9 we observed ugly shadows across numerous controls. 

For example this demo
https://primefaces.org/primeng/showcase/#/dropdown

shows extra outline around dropdown as in image attached
![43bb58af9cd3df1a2674c9abe4a296f8](https://user-images.githubusercontent.com/3460517/78463185-caea2e80-768e-11ea-9f6d-349e62193be4.png)

**Comment by dolphinsd** [comment]
removing padding on body .ui-inputtext  fixes the issue

**Comment by dolphinsd** [comment]
this css fixes the issue as a workaround 
body .ui-dropdown {
    border: 1.3px solid #a6a6a6 !important;
}

**Comment by cagataycivici** [comment]
Unable to see this, sorry.
