### ISSUE TITLE
dismissableMask not working in dynamic dialog

### ISSUE THREAD

**Issue by IVmostafa** [primefaces/primeng#8714]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
clicking in the modal background not closing the dialog

**Expected behavior**
if clicking the modal background should hide the dialog.

**Minimal reproduction of the problem with instructions**
Call a method to open dynamic dialog with `dismissableMask` set to true and try to close it by click on the background

**What is the motivation / use case for changing the behavior?**
We want to close the dialog when user click on the background

**Please tell us about your environment:**
Mac OS, VS Code but should be reproducible in all environments

* **Angular version:** 5.X
9.0.7

* **PrimeNG version:** 5.X
9.0.5

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome but should be reproducible in all browsers

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 3.7.5

* **Node (for AoT issues):** `node --version` =   
12.16.0

* **Note:** 
in `https://github.com/primefaces/primeng/blob/master/src/app/components/dynamicdialog/dynamicdialog.ts` the method `onMaskClick` was called in line 21 in previous version `8.1.1` now it isn't
change `<div #mask class="ui-widget-overlay ui-dialog-mask ui-dialog-visible ui-dialog-mask-scrollblocker">` 
to `<div #mask class="ui-widget-overlay ui-dialog-mask ui-dialog-visible ui-dialog-mask-scrollblocker" (click)="onMaskClick()">`
in line 21 in the mentioned link

i have created PR for the fix, tested it and it's working check my PR https://github.com/primefaces/primeng/pull/8715

**Comment by Grauen** [comment]
@cagataycivici  this might be related to https://github.com/primefaces/primeng/issues/8720 :)

**Comment by fredericojesus** [comment]
Having the same issue, dismissable mask is not working at all in dynamic dialog.

**Comment by KissBalazs** [comment]
Having the same issue, but I am not using p-table in my project.

**Comment by andras-gyarmati** [comment]
+1

**Comment by Source424** [comment]
Hopefully this can help someone else but I found if you add [modal]="true" with [dismissableMask]="true" then the functionality works as intended.

Sample code:
<p-dialog  [modal]="true" [dismissableMask]="true" header="Apps" [(visible)]="showApps" [position]="'top-right'"
  [breakpoints]="{'960px': '40vw', '640px': '50vw'}" [style]="{width: '20vw'}" overlay="true" [responsive]="true"></p-dialog>

**Comment by andras-gyarmati** [comment]
I open the modal from TypeScript like:
`const ref = this.dialogService.open(MyComponent, {
      data: {
        ...
      },
      header: 'My Header',
      dismissableMask: true,
      modal: true,
    });
    `
but it does not work like this.

**Comment by Source424** [comment]
> I open the modal from TypeScript like:
> 
> ```
> const ref = this.dialogService.open(MyComponent, {
>       data: {
>         ...
>       },
>       header: 'My Header',
>       dismissableMask: true,
>       modal: true,
>     });
> ```
> 
> but it does not work like this.

When using the dialog service in this way this is working for me in terms of being able to close the dialog by clicking outside of it:

`  openSummaryDialog = (args: any[]): void =>{
    this.dialogService.open(PatientSummaryComponent, {
      header: 'Patient Summary',
      data: args[1],
      dismissableMask: true,
      width: '70%'
    });
  };`

I'm using Angular 12 and primeng 12.1.0

**Comment by andras-gyarmati** [comment]
i updated to 13.1 and now it works

**Comment by mineralf** [comment]
For me using Version 12.2.3 the CSS was "broken" not capturing the clicks to the dialog mask. Effectivly making it transparent so the user could even interact with the background. After overriding the styles it works like expected for me. Not sure if it was due to some special theme used in the project or if that's a general issue.

```
div.p-dialog-mask {
	//"none" does not prevent interaction with the background and also doesn't capture the click for closing the modal dialog
	pointer-events: auto;
}
```

Maybe this helps somebody who cannot yet upgrade to 13.x
