### ISSUE TITLE
P-Dialog containing P-Table:  initRowEdit() will automatically close P-Dialog when dismissableMask is set to true

### ISSUE THREAD

**Issue by Grauen** [primefaces/primeng#8720]
If you put a **p-table inside of an p-dialog**, the **dialog will automatically close** when you trigger `_initRowEdit() or cancelRowEdit()_ .` <-- ( I don't know if other methods are affected, too ...)

But this happens only, if the dialog is modal and the parameter dismissableMask is set like: `[dismissableMask]="true" `

**Comment by dmytro-gokun** [comment]
It actually happens even when i have a dialog with a button and click that button. The dialog is dismissed. If [dismissableMask]="false" this does not happen.

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
