### ISSUE TITLE
pTooltip: collision detection is wrong when placed in corners

### ISSUE THREAD

**Issue by j0hnwhyte** [primefaces/primeng#8722]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request 
[ ] support request
```
[Here's the plunkr](https://stackblitz.com/github/qgnirxral)

**Current behavior**
The tooltip glitches the page and the scrollbar is shown

**Expected behavior**
It should align correctly on the top of the element, and show the arrow in the correct place.

* **Angular version:** 9.1.0

* **PrimeNG version:** 9.0.5

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Comment by j0hnwhyte** [comment]
For future readers I solved using the package sat-popover
