### ISSUE TITLE
Enhanced keyboard support for Dropdown

### ISSUE THREAD

**Issue by rafaelodon** [primefaces/primeng#873]
Once you focus on a Dropdown you should be able to type something hiddenly and see the corresponding option being selected without using the mouse. Primefaces OneMenu and native browsers alternatives have always worked like that. I'm not suggesting to enrich this basic component to visually work like its filtered version, but I really believe that this type/select behaviour is the affordance whose Internet users have developed when they have both hands over the keyboard and just "tab" to a dropdown.

**Comment by smarty77** [comment]
Same here. 
Any news about this issue?
Keyboard typing on focused dropdown should select the corresponding option.
At least by the first letter.

**Comment by cot-dkirolos** [comment]
Can we add to it Keyboard up and down buttons?
User should be able to navigate between dropdown menu using keyboard up and down buttons.
This feature should be working all times when the dropdown is hidden or shown and also with dropdown filter.

Thank you for this great framework.

**Comment by EleanorHughes** [comment]
Any update on this enhancement? This is also required in my project

**Comment by RichardMcElroy** [comment]
+1 for this enhancement.
It would help with accessibility and better conform to user-expected functionality.

**Comment by bsweedler-pavlov** [comment]
My use case address forms, specifically the state field. Most websites have a classic <select> dropdown with all the states listed, in which the user selects the state by typing the first letter in the state code. I think it would be useful to replicate this behavior in the PrimeNG dropdown component.

**Comment by unaor** [comment]
same he we need a filter related event

**Comment by bohms27** [comment]
Any updates on this issue? I saw it was added to a milestone but then removed?

**Comment by bohms27** [comment]
Again... would like to hear an update on this issue. It's been almost 2 years and many people seem to want this. I really wish the default behavior of the native html select would apply to your dropdown.

**Comment by cagataycivici** [comment]
This is available already since 6.1.4
