### ISSUE TITLE
Accessibility- p-table blocks keyboard navigation

### ISSUE THREAD

**Issue by Pikadili83** [primefaces/primeng#8732]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please use table from documentation and turn on JAWS
https://www.primefaces.org/primeng/showcase/#/table/selection

**Current behavior**
When [scrollable]="false" (it works correctly with [scrollable]="true" but I'm not using [scrollable]="true" because in that case p-table is rendered as two tables - that's not acceptable for accessibility users), selectionMode="single" and JAWS is running, after selecting a row, user can't use keyboard shortcuts for navigation (these shortcuts are essential for blind users). For example, pressing B should go to the next button on that page but that's not working.
This was working fine before, the problem appeared in the last couple of PrimeNG versions (after 9.0.0 I think)

**Expected behavior**
Accessibility shortcuts should work with [scrollable]="false" after selecting a row.

**What is the motivation / use case for changing the behavior?**
Accessibility users reported this issue as a major problem.

* **Angular version:** 9.0.2

* **PrimeNG version:** 9.0.5

* **Browser:** [all]
 
* **Language:** TypeScript 3.7.5

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
