### ISSUE TITLE
Animate unrolling/folding of Tree component

### ISSUE THREAD

**Issue by ptrwis** [primefaces/primeng#8734]
**Feature request**
Please make unrolling/folding of Tree component animatable. My request aims in particular vertical tree.
**Motivation**
Improve user experience
**Expected behaviour**
https://mdbootstrap.com/snippets/jquery/pjoter-2-0/766806

**Comment by mouazAlkhodari** [comment]
i think animation like the one in the accordion component would be a good addition

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by ptrwis** [comment]
@mertsincan  I cannot reopen the issue. From what I can see, this feature is still unavailable and I'd love to see it.

**Comment by cetincakiroglu** [comment]
Hi,

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 
For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
