### ISSUE TITLE
show custom preview while draging item

### ISSUE THREAD

**Issue by Rjitendra** [primefaces/primeng#8737]
Hello,

I would like to know one functionality about dragon drop

Current behavior
in my case i am using dragon a row of table and drop to one div

Expected behavior
when i do dragon ,in my case i am selected multiple row and dragon ,it should show custom preview like "2 row move to drop" while draging.
 and when drop over div,my div  should show some animation effect.

What is the motivation / use case for changing the behavior?
Need to know this feature is available or not?

Angular version: 9.0.0.X

PrimeNG version: 9.0.0

Browser: [Chrome | Firefox ]

Thank you !

**Comment by cagataycivici** [comment]
Please use forum for questions and help requests.
