### ISSUE TITLE
p-chips separator is not working on latest version?

### ISSUE THREAD

**Issue by dineshmaths1** [primefaces/primeng#8738]
this is my code 

> <p-chips  separator="," (onAdd)="emailInvitieesCount()" (onRemove)="emailInvitieesCount()"
>                                 formControlName="emailinvitees"></p-chips>

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 9.0.5, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
