### ISSUE TITLE
Paginator should be accessible from the parent component.

### ISSUE THREAD

**Issue by fernandogomesdf** [primefaces/primeng#874]
It is not possible to access paginator from DataGrid/DataList. It should be possible to get the current page, and the pageChange event from the parent component, even if it is not using lazy loading. The reason for that is to keep the previous paginator state after detail a row in a new route. It should also be possible to change the page programatically from the parent component. Thank you guys for the awesome work! Fernando. #412

**Comment by fernandogomesdf** [comment]
I could use the property 'first' from the DataGrid, but it is protected...

**Comment by huineng** [comment]
#945

**Comment by garthmason** [comment]
Agree this would be very useful - we have a similar scenario, where select a row item from say page 3, and navigate to a child route to edit that item. Then on routing back to the grid page we want to select page 3 again by default.

Currently working around this by accessing the DataTable as a ViewChild and calling the paginate function (with first/rows parameters) to select the desired page.

**Comment by cagataycivici** [comment]
First and Rows properties should allow access already.
