### ISSUE TITLE
Please add documentation to dropdown component in showcase

### ISSUE THREAD

**Issue by borisheithecker** [primefaces/primeng#8741]
Dropdown component requires ```BrowserAnimationsModule``` to be added to the Angular platform. Do everybody a favour and add a note to your documentation at https://primefaces.org/primeng/showcase/#/dropdown

* **Angular version:** 9.1.1

* **PrimeNG version:** 9.0.0

**Comment by cagataycivici** [comment]
Please see;

https://primefaces.org/primeng/showcase/#/setup
