### ISSUE TITLE
TabMenu RouterLinkActive doesn't work since @9.0.3

### ISSUE THREAD

**Issue by serjvirchenko** [primefaces/primeng#8748]
Since primeng@9.0.3 highlight for active tab TabMenu component with routerLink doesn't work.

9.0.2 example: https://stackblitz.com/edit/angular-ahzds6
9.0.3 example: https://stackblitz.com/edit/angular-lxoeoi

**Comment by yigitfindikli** [comment]
Fixed in https://github.com/primefaces/primeng/commit/6ab3d5b6581e8bc3c9468b72ed3a241312069be2
