### ISSUE TITLE
p-scrollpanel issues in production build

### ISSUE THREAD

**Issue by yntelectual** [primefaces/primeng#8751]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
After prod build, when trying to call `moveBar` method on `p-scrollpanel` the invocation fails with
```
main.d3c6c74a55f52534de41.js:1 ERROR TypeError: this.layoutMenuScrollerViewChild.moveBar is not a function
    at main.d3c6c74a55f52534de41.js:1
```

**Expected behavior**
`moveBar` should work as it does work in development mode

**Minimal reproduction of the problem with instructions**
Ultima theme, which uses p-scrollpanel , using `@ViewChild` and then tries to call `.moveBar` on it to reveal the menu items. In development mode `ng-serve` it works ok, when compiled with `--prod` it stops working. 

* **Angular version:** 9.1.1

* **PrimeNG version:** 9.0.5

* **Browser:** [all ]

 
* **Language:** [ ES6/7 ]

* **Node (for AoT issues):** `node --version` =   v12.16.2

![image](https://user-images.githubusercontent.com/1354787/79543512-e17c8680-808d-11ea-8d62-6e262d3704fc.png)

**Comment by cagataycivici** [comment]
Does it happen on Ultima 9?
