### ISSUE TITLE
Issue with p-dropdown programmatic select when dataKey attribute is set.

### ISSUE THREAD

**Issue by devstartshop** [primefaces/primeng#8752]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/angular9-primeng9-dropdown-reactive-form

**Current behavior**

When the dataKey attribute is set as datakey="value", then programmatic select of dropdown value is not working. and shows the first option always

**Expected behavior**

Programmatic select of p-dropdown should work with dataKey attribute set.

**Please tell us about your environment:**

Windows 10, Webstorm, npm, angular cli server.
Angular CLI: 9.0.7
Node: 12.13.0
OS: win32 x64

Angular: 9.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.7
@angular-devkit/build-angular     0.900.7
@angular-devkit/build-optimizer   0.900.7
@angular-devkit/build-webpack     0.900.7
@angular-devkit/core              9.0.7
@angular-devkit/schematics        9.0.7
@angular/cdk                      9.1.3
@ngtools/webpack                  9.0.7
@schematics/angular               9.0.7
@schematics/update                0.900.7
rxjs                              6.5.4
typescript                        3.7.4
webpack                           4.41.2

* **Angular version:** 9.0.7

* **PrimeNG version:** 9.0.5

* **Browser:** [all]

 
* **Language:** TypeScript 3.7.4

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
This is expected, dataKey works on the option value not the option object itself e..g {label, value}, since your option value is a string, it has no property.
