### ISSUE TITLE
p-calendar with selectionMode="range" does not allow manually typing in same start and end date

### ISSUE THREAD

**Issue by spmorganjr** [primefaces/primeng#8763]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/github-7a9aey

**Current behavior**
Using p-calendar with selectionMode="range". Need to be able to type in a date range with the same start and end date. This can be selected from the UI picker by clicking the same day twice. However, if a date range of the same day is typed in manually then the input is rejected and calendar reverts to its previous selection. 

This is due to isValidSelection() function checking value[1] > value[0] instead of value[1] >= value[0] when isRangeSelection() is true. 

**Expected behavior**
Since a date range with the same start and end date is valid from the UI picker, it should also be valid when typed in manually. 

**Minimal reproduction of the problem with instructions**
See plunkr demo above with p-calendar and selectionMode="range". Select same start and end date on UI picker, no issue. Clear selection. Then try and type the same date range into the input (or just cut and paste), entry is rejected.

**What is the motivation / use case for changing the behavior?**
We have scenarios where the start and and date both fall on the same day. Sometimes this date falls well into the future, and it's easier to type it in.

**Please tell us about your environment:**

    Angular version: 9.1.0

    PrimeNG version: 9.0.0

    Browser: Chrome 80.0.3987.163

    Language: TypeScript

**Comment by oberbeck** [comment]
In addition, the date range picker allows to select a start day only without specifying an end date. However, when manually entering only a start date without an end date, it is not valid as well.

**Comment by ssavchuk** [comment]
I have the same problems.
```
"primeng@9.1.3"
```
This is due to validation in **src/app/components/calendar/calendar.ts**
```
isValidSelection(value) {
...
            if (this.isRangeSelection()) {
                isValid = value.length > 1 && value[1] > value[0] ? true : false;
            }
...
}
```

This method invokes only from **onUserInput(event)**

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by aymeninfosim** [comment]
problem still exists
