### ISSUE TITLE
Remove or implement selectId

### ISSUE THREAD

**Issue by Michael-Ziluck** [primefaces/primeng#8764]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
There is a documented input field called `selectId` that exists on the dropdown component. It says it is for the native HTML element. However, that field is never used. Please either remove it from the inputs/documentation or actually use it.

Link: https://github.com/primefaces/primeng/blob/master/src/app/components/dropdown/dropdown.ts#L183

**Comment by cagataycivici** [comment]
Removed in 11.x
