### ISSUE TITLE
Custom toasts not stacked

### ISSUE THREAD

**Issue by Michael881188** [primefaces/primeng#8765]
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-huxlmn
Just click :'Click me'

**Current behavior**
I implemented two custom p-toast templates with different keys, when i call both of them there are not stacked.
Custom toasts do not stack.

**Expected behavior**
Stacked toasts.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/github-huxlmn
Just click :'Click me'

* **Angular version:** 8

* **PrimeNG version:** 5.X

* **Browser:** all

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
