### ISSUE TITLE
p-dropdown select row programmatically not working

### ISSUE THREAD

**Issue by danielserrao** [primefaces/primeng#877]
Hey, I'm trying to change the selected row programmatically after a click on a p-calendar but for some reason, this just works the first time.

My html file:

```
    <p-dropdown [options]="timeSpan" [(ngModel)]="selectedTimeSpan"                                                                                                (onChange)="OnChange()" [hidden]="showCalendar"></p-dropdown>
    <p-calendar dateFormat="dd-mm-yy" showAnim="slideDown" [(ngModel)]="calendarValue" (onSelect)="OnChangeCal()" (onBlur)="OnBlurCal()" [hidden]="!showCalendar"></p-calendar>
```

My component file is the following:

```
OnChange(){
    let selections: string[] = [this.selectedType, this.selectedTimeSpan];

    if(this.selectedTimeSpan == "0"){

        if(this.calendarValue != null){
            this.selectedTimeSpan = "101";
        }

        this.showCalendar = true;

    }else if (this.selectedTimeSpan != "101") {

        this.calendarValue = null;

        if(this.timeSpan.length > 5){
            this.timeSpan.pop();
        }

    }

    this.notify.emit(selections);

    console.log("ON CHANGE()!");
    console.log("this.selectedTimeSpan: " + this.selectedTimeSpan);
    console.log("this.calendarValue: " + this.calendarValue);
}

OnChangeCal(){
    if(this.timeSpan.length > 5){
        console.log("POP!");
        this.timeSpan.pop();
    }
    this.timeSpan.push({label:'Since ' + this.calendarValue, value:"101"});
    this.selectedTimeSpan = "101";
    this.showCalendar = false;

    console.log("ON CHANGECAL!");
    console.log("this.selectedTimeSpan: " + this.selectedTimeSpan);
    console.log("this.calendarValue: " + this.calendarValue);
}
```

My timeSpan is a SelectItem[] array which have the following rows:

```
    {label:'Last 7 days', value:7},
        {label:'Last 15 days', value:15},
        {label:'Last 30 days', value:30},
        {label:'Last 60 days', value:60},
    {label:'Custom', value:0}
```

When I click at the "Custom" row, I hide the component p-dropdown and change to the p-calendar component, where I click on a date and then I change to the p-dropdown component again and add the row with the selected date. This happens succesfully the first time but after, if I go to Custom and select another date, the date changes successfully but  the selected row keep being the "Custom" row. I don't understand why because on my [(ngModel)], I have the selectedTimeSpan and I changed it to the new date value.

Any idea why this is not working atfer the first time?

**Comment by meeximum** [comment]
I also try to set the selected value in the constructor or in the ngInit method, both without any effect :-/

**Comment by cagataycivici** [comment]
What is your version?

**Comment by meeximum** [comment]
1.0.0beta.8

Çağatay Çivici <notifications@github.com> schrieb am Mo., 12. Sep. 2016 um
16:57 Uhr:

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with them and if issue persists drop a comment and we'll reopen.

**Comment by death47** [comment]
This issue still persists, it works successfully for the first time then stops working.
I am using "primeng": "5.0.2".
