### ISSUE TITLE
Table cell navigation should allow moving to footer

### ISSUE THREAD

**Issue by yelhouti** [primefaces/primeng#8772]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

 https://stackblitz.com/edit/angular-vdpmyx

**Current behavior**

if the footer contains an editable cell (ex: "+ with dropdown" to add a new line), the tab does't move to it, this can easily be fixed and I can provide a PR if you want.

**Expected behavior**

tab should move to footer

**Minimal reproduction of the problem with instructions**

select a cell in the sutuckblitz
click tab many times
it stops a the last cell of body instead of moving to footer

**What is the motivation / use case for changing the behavior?**
global navigation to add new lines for example...

stackblitz added as suggested here: https://github.com/primefaces/primeng/issues/8207 by @cagataycivici

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
