### ISSUE TITLE
Accordion open all taps in the first few seconds if its in a Dynamic Dialog

### ISSUE THREAD

**Issue by KingPin2** [primefaces/primeng#8773]
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/github-9ccs9k?mbed=1&file=src/app/app.component.ts&view=preview

**Current behavior**
Accordion open all taps in the first few seconds if its in a Dynamic Dialog. After that it will collapse again. This looks strange.

**Expected behavior**
Accordion taps should be closed per default if I open a dialog which contains a accordion as it was in the versions before.

**What is the motivation / use case for changing the behavior?**
<!-- Describe the motivation or the concrete use case -->
We use the Accordion in a Dynamic Dialog in our business application and it is no good look and feel for the customer.

* **Angular version:** 9.X
<!-- Check whether this is still an issue in the most recent Angular version -->

* **PrimeNG version:** 9.X
<!-- Check whether this is still an issue in the most recent Angular version -->

**Comment by UlricW** [comment]
We're facing the same issue since PrimeNG 9 and still present in the version 10.0.3.
I agree with @KingPin2 it's not smooth and the client is feeling frustrated with this open/close behaviour

**Comment by Bogasudheer** [comment]
<p-dialog [(visible)]="display">
<innercomponent *ngIf="display">

It will works

**Comment by cetincakiroglu** [comment]
Hi,

If the issue still exists with the latest PrimeNG version, please provide a StackBlitz example by using [PrimeNG Issue Template ](https://stackblitz.com/github/primefaces/primeng-issue-template) and re-open the issue.

Regards
