### ISSUE TITLE
p-table columns are misaligned when number of rows changes with filter

### ISSUE THREAD

**Issue by jacqueslareau** [primefaces/primeng#8778]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/github-hq13wf

**Current behavior**
Columns are out of alignment when filtering. Also the scrollbar still appears even if there is nothing to scroll.

**Expected behavior**
Column headers must be aligned with body.

**Minimal reproduction of the problem with instructions**

View stackblitz example. Enter a Z in one of the filter.

**What is the motivation / use case for changing the behavior?**

It's not that bad in the example with 3 columns, but with 10 or 20 it's really bad.

**Please tell us about your environment:**
Windows 10

* **Angular version:** 5.X
Angular 9.1.1

* **PrimeNG version:** 5.X
9.0.5

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 3.8.3

* **Node (for AoT issues):** `node --version` =   
12.16.2

**Comment by kirandas82** [comment]
Any solution on this issue ?

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
