### ISSUE TITLE
Paste delimited text into multiple editable Table cells [Feature Request]

### ISSUE THREAD

**Issue by KeithGillette** [primefaces/primeng#8779]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Pasting (tab) delimited text into an editable cell in the `p-table` component pastes the entire string including delimiter into the single cell input.

**Expected behavior**
Pasting delimited text into a cell in the Table component would paste the text into multiple cells in an editable row, split on the delimiters.

**What is the motivation / use case for changing the behavior?**
* Data entry would be greatly speeded with the ability to paste into multiple editable cells.
* UX would match behavior of similar grids such as spreadsheets and word processor tables.

**Comment by alirizadikici** [comment]
+1

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by KeithGillette** [comment]
@mertsincan — Authors cannot reopen their issues when they are closed by a repository collaborator, so I ask that you reopen this feature request issue, which I think would be an extremely useful enhancement to the Table component.

**Comment by cetincakiroglu** [comment]
Hi,

Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 
For enhancement requests and other topics, you can open a new topic in [PrimeNG Discussions](https://github.com/orgs/primefaces/discussions/categories/primeng).
