### ISSUE TITLE
Open p-calendar programmatically

### ISSUE THREAD

**Issue by danielserrao** [primefaces/primeng#878]
Hey, I tried the solution in [http://stackoverflow.com/questions/36639486/angular2-manually-firing-click-event-on-particular-element](url) to open the p-calendar programmatically but nativeElement is not defined. I also tried many other javascript solutions that are in the internet but nothing working. Can you tell me if there is any way to do it?

**Comment by danielordonez** [comment]
Anyone working on this feature? It would be very very useful

**Comment by NynaPykulska** [comment]
Hi, if anyone is still looking for a solution, I've managed to do this with the following directive:

`@Directive({
    selector: "[jflCalendarFocusOnInit]"
})
export class CalendarFocusOnInitDirective implements AfterViewInit {

    constructor(private elementRef: ElementRef) {}

    ngAfterViewInit() {
        window.setTimeout(() =>
            this.elementRef.nativeElement.children[0].children[1].click()
        );
    }}`
In your calendar just add the selector:
`<p-calendar [(ngModel)]="calendarModel" jflCalendarFocusOnInit ></p-calendar>`

**Comment by cagataycivici** [comment]
You can also use showOverlay() method.

**Comment by danielordonez** [comment]
showOverlay method is not working, any special considerations with usage @cagataycivici ?

**Comment by danielordonez** [comment]
Never mind. I was doing an on click event which at the end closed the overlay. Method is working properly.
