### ISSUE TITLE
DynamicDialog suddenly closes in 9.0.6 & 9.1.0

### ISSUE THREAD

**Issue by dmytro-gokun** [primefaces/primeng#8784]
**I'm submitting a ...** 
```
[X] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/sudden-dialog-close

**Current behavior**
1. Click "Show dialog" so the dialog is open.
2. In the dialog click "CLICK ME" button. The dialog is suddenly closed.

**Expected behavior**

The dialog should not close

**Minimal reproduction of the problem with instructions**

This issue does not exist if the dialog is open with dismissableMask=false

**Angular version:** 9.1.3

**PrimeNG version:** 9.0.6

**Comment by serjvirchenko** [comment]
also another thing that now `dismissableMask` is `true` by default unlike documentation

**Comment by dmytro-gokun** [comment]
Still is not fixed in 9.1.0

**Comment by ZVARKO** [comment]
> also another thing that now `dismissableMask` is `true` by default unlike documentation

this issue is reported here https://github.com/primefaces/primeng/issues/8891

**Comment by DennisAMenace** [comment]
+1

**Comment by yigitfindikli** [comment]
Fixed in https://github.com/primefaces/primeng/issues/8934
