### ISSUE TITLE
Dropdown text overflow, 9.0.6 & 9.1.0

### ISSUE THREAD

**Issue by dmytro-gokun** [primefaces/primeng#8785]
**I'm submitting a ...**
```
[X] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-dropdown-label-overflows-clear-button

**Current behavior**
1.  Select first item from the drop down
2. Label text flows outside of the dropdown, all over the clear button, down button and further.

**Expected behavior**
Text should be truncated (perhaps using ellipsis).

**Angular version:** 9.1.3

**PrimeNG version:** 9.0.6

**Comment by irakligogiashvili** [comment]
I have the same problem

PrimeNG version: 9.0.1

**Comment by gabrielrevilla** [comment]
I have the same problem

PrimeNG version: 9.1.0
Angular version: 9.1.4

**Comment by dmytro-gokun** [comment]
The problem still exists in 9.1.0

**Comment by sohaib-khan** [comment]
I have the same issue using PrimeNG version 9.1.0. 

Were you guys able to find a work around. Adding text-overflow:ellipsis did not solve the issue.

**Comment by sohaib-khan** [comment]
I changed the following class and it gave me a desired effect for now.

.ui-dropdown-label-container {
  width: 100%;
}
.ui-dropdown.ui-dropdown-clearable .ui-dropdown-label {
  text-overflow: ellipsis;
  padding-right: 2em !important;
}
.ui-dropdown .ui-dropdown-label {
  text-overflow: ellipsis;
  padding-right: 1em !important;
}
![Screen Shot 2020-06-06 at 10 33 49](https://user-images.githubusercontent.com/13437078/83938937-79bb0000-a7e1-11ea-8178-bf7448e58c87.png)

**Comment by dmytro-gokun** [comment]
@sohaib-khan Thanks for sharing a workaround. Hopefully, primeng folks will find some time and fix the bug permanantly though :).

**Comment by franciscoghansen** [comment]
I'm also facing this issue... thans @sohaib-khan for the workaround!

**Comment by beinto** [comment]
Can we know when there is an issue regarding this bug?

**Comment by dmytro-gokun** [comment]
@beinto No. That's against Primefaces's policy :). I have reported like a dozen of bugs, they have fixed a couple of them. But they never promised any dates. I guess, i'll be transitioning away from this library. It's a pity, coz overall it's quite good. But they have to few resources to fix all the numerous bug + they do not seem to have any regerssion testing set up. Sometimes, a minor update, like 9.0.5 => 9.0.6 ruins have of your app and re-introduces bugs that were already fixed ages ago. Very sad.

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Comment by pragmat1c** [comment]
> I changed the following class and it gave me a desired effect for now.
> 
> .ui-dropdown-label-container {
> width: 100%;
> }
> .ui-dropdown.ui-dropdown-clearable .ui-dropdown-label {
> text-overflow: ellipsis;
> padding-right: 2em !important;
> }
> .ui-dropdown .ui-dropdown-label {
> text-overflow: ellipsis;
> padding-right: 1em !important;
> }
> ![Screen Shot 2020-06-06 at 10 33 49](https://user-images.githubusercontent.com/13437078/83938937-79bb0000-a7e1-11ea-8178-bf7448e58c87.png)

You are the real MVP. 

One minor change I made.

```
.page-filter-bar ::ng-deep .ui-dropdown .ui-dropdown-label {
    text-overflow: ellipsis;
    padding-right: 2em !important;
}

```

We cannot at this time jump to version 11 or whatever, do to all the changes that were made in 10.
