### ISSUE TITLE
Dropdown does not size to the flexbox container properly, 9.0.6 & 9.1.0

### ISSUE THREAD

**Issue by dmytro-gokun** [primefaces/primeng#8786]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-dropdown-label-overflows-clear-button-y6b3hc

**Current behavior**
Since the dropdown is placed in the flexbox with "flex:  auto", it should occupy the whole parent width (100px). But it does not. Moreover, its width changes when different items are selected.

**Expected behavior**
Since the dropdown is placed in the flexbox with "flex:  auto", it should occupy the whole parent width (100px). 

**Angular version:** 9.1.3

**PrimeNG version:** 9.0.6

**Comment by dmytro-gokun** [comment]
The problem still exists in 9.1.0

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
