### ISSUE TITLE
Slider has problem

### ISSUE THREAD

**Issue by SShushmintcev** [primefaces/primeng#8787]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
```

**Current behavior**
I have a problem with slider when I made build with key aot. 

ERROR in node_modules/primeng/slider/primeng-slider.d.ts.Slider.html(14,44): Element implicitly has an 'any' type because expression of type '0' can't be used to index type 'Number'.
  Property '0' does not exist on type 'Number'.
node_modules/primeng/slider/primeng-slider.d.ts.Slider.html(17,44): Element implicitly has an 'any' type because expression of type '1' can't be used to index type 'Number'.
  Property '1' does not exist on type 'Number'.

**I think maybe it is property handleValues[0] and handleValues[1].
I commented on p-slider throughout the project. And I made build with key aot. I had problem.
When I commented SliderModule I did not have problem**

**Minimal reproduction of the problem with instructions**
npm run build --aot

* **Angular version:** 9.1.3

* **PrimeNG version:** 9.0.2

 
* **Language:** [all | TypeScript 3.8.3 | ES5]

* **Node (for AoT issues):** `node --version` =   12.10.0

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
