### ISSUE TITLE
Error in p-table doc: pEditableColumnRowIndex

### ISSUE THREAD

**Issue by jacqueslareau** [primefaces/primeng#8793]
In documentation for p-table
https://github.com/primefaces/primeng/blob/5c59beb25ad515847f837dd6eb9f4e89260e2d11/src/app/showcase/components/table/tabledemo.html#L1466

To get the row index, it should say pEditableColumnRowIndex instead of pEditableRowIndex.

**Comment by joanManuel** [comment]
Thanks! @jacqueslareau
