### ISSUE TITLE
Floating label does not come down when you clear the items inside chips.

### ISSUE THREAD

**Issue by tarekz** [primefaces/primeng#8794]
**I'm submitting a ...** 
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/github-qvkimx?embed=1&file=src/app/app.component.html

**Current behavior**

If you clear the model the label remains floating. The only way to make the label come back inside the chips input, is by adding an item and clicking on the X, or pressing backspace to delete the item.

**Expected behavior**

The floating label should detect the items have been removed and comback inside the chips input when the array is cleared.

**Minimal reproduction of the problem with instructions**

Create a floating label for a chips control.
Add a button to clear all the items from the control.
Add an item to the chips, and then press on the button.
Notice the label remains above the chips control.
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:**
@angular-devkit/architect         0.901.3
@angular-devkit/build-angular     0.901.3
@angular-devkit/build-optimizer   0.901.3
@angular-devkit/build-webpack     0.901.3
@angular-devkit/core              9.1.3
@angular-devkit/schematics        9.1.3
@ngtools/webpack                  9.1.3
@schematics/angular               9.1.3
@schematics/update                0.901.3
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

* **PrimeNG version:**

9.0.6

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome Version 81.0.4044.122 (Official Build) (64-bit) 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
