### ISSUE TITLE
p-steps in p-dialog closes the dialog

### ISSUE THREAD

**Issue by pyrarhum1** [primefaces/primeng#8796]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report 
```

**Current behavior**

if i use an ngIf in button to display next step, it closes the dialog.
see : https://stackblitz.com/edit/github-w5wjy2

**Expected behavior**

Going to next step does not have to close the dialog !

**Minimal reproduction of the problem with instructions**

https://stackblitz.com/edit/github-w5wjy2

**Please tell us about your environment:**
Angular 9.1.2, Primeng 9.06

* **Browser:** 
Chrome

* **Language:**

Typescript 3.6.4

* **Node (for AoT issues):** `node --version` =   10.16

**Comment by dmytro-gokun** [comment]
I think its the same underlying reason as for this bug: https://github.com/primefaces/primeng/issues/8784

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
