### ISSUE TITLE
InputMask tabindex

### ISSUE THREAD

**Issue by ksatzkmr** [primefaces/primeng#8798]
Cursor is not setting to the control if I use tabindex property. 

When I move between controls through tab key, when it comes to the inputmask control. the control is highlighted but the cursor doesn't set to the control. I need to press tab key twice to set the cursor.

I want to set the cursor to the inputmask control when I press the tab key once not twice. 

My Code:
<p-inputMask slotChar='yyyy/mm/dd'  tabindex="2"></p-inputMask>

Could anyone please help me on this?

**Comment by mxttbennett** [comment]
Did you ever figure out this problem? I'm running into a very similar one
