### ISSUE TITLE
OverlayPanel does not adjust its position to target when content and the size of the panel changes

### ISSUE THREAD

**Issue by godfryd** [primefaces/primeng#8799]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

There is a search panel displayed using OverlayPanel. It should be aligned with search box.

The first panel with results is aligned with search box, but then when user types the content of results is changing and results panel adapts its size to content but the position is wrong.

![obraz](https://user-images.githubusercontent.com/176567/80574281-d7e60d80-8a01-11ea-8ead-852260a954e1.png)

![obraz](https://user-images.githubusercontent.com/176567/80574299-e03e4880-8a01-11ea-8f2f-6037cab51e27.png)

![obraz](https://user-images.githubusercontent.com/176567/80574313-e502fc80-8a01-11ea-9124-bdce6e47af08.png)

**Expected behavior**

Panel with results is always aligned with search box. I tried to use align() function of OverlayPanel but it works only sometimes.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 9.1.2

* **PrimeNG version:** 9.0.5

* **Browser:** Firefox 74

 
* **Language:** TypeScript 3.8

* **Node (for AoT issues):** `node --version` =  v12.16.2

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
