### ISSUE TITLE
Dropdown panel is too big when using virtual scroll

### ISSUE THREAD

**Issue by dmytro-gokun** [primefaces/primeng#8802]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/primeng-dropdown-virtualscroll-size

**Current behavior**

When virtual scroll is enabled and dropdown has few items, the panel is too big and has a lot of free space at the bottom:

![image](https://user-images.githubusercontent.com/580460/80689786-80fe3800-8ad6-11ea-8661-fdaf335144ae.png)

**Expected behavior**
The panel should be big enough to fit available options. Just the way it works w/o virtual scrolling enabled.

* **Angular version:** 9.1.1
* **PrimeNG version:** 9.0.6

**Comment by dmytro-gokun** [comment]
The problem still exists in 9.1.0

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
