### ISSUE TITLE
Dinamic selected tab problem

### ISSUE THREAD

**Issue by giovannicandido** [primefaces/primeng#8807]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/angular-8zsilk

**Current behavior**
* Add new tab
* last tab is selected
* Click on other tab
* Add a new tab
* Last tab keeps selected and current tab is both the clicked one and the last
* Last tab stops being "selectable"

**Expected behavior**
Only one tab is selected, last tab can be change to selected

**Minimal reproduction of the problem with instructions**
There is a gift of the problem in:  
![2020-04-30_16-43-57](https://user-images.githubusercontent.com/915892/80753172-31823100-8b03-11ea-887e-9fb335a4e7ee.gif)

**What is the motivation / use case for changing the behavior?**

Dinamic tabs with programatic selected item.

**Please tell us about your environment:**

* **Angular version:**
9.x

* **PrimeNG version:**
9.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All browsers, tested with chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
