### ISSUE TITLE
Wrong org chart icons

### ISSUE THREAD

**Issue by martheli** [primefaces/primeng#8808]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

I am trying to set up an org chart and the icons that are used to click on to expand each node are not correct. I have ViewEncapsulation set to none on my component. I have included the following in my styles: 

```
"styles": [
  "node_modules/primeicons/primeicons.css",
  "node_modules/primeng/resources/themes/nova-light/theme.css",
  "node_modules/primeng/resources/primeng.min.css",
],
```

I also have included these two in my dependencies:

```
  "primeng": "^9.050",
  "primeicons": "^2.0.0" 
```

When my  org chart loads the drop down icon is a snowflake instead of a down arrow.

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
