### ISSUE TITLE
Multiple templates for Tree

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#881]
Add type attribute to TreeNode that matches the pTemplate's type option to provide multiple templates.

**Comment by cagataycivici** [comment]
Templating
By default label of a treenode is displayed inside a tree node, in case you need to place custom content define a pTemplate that gets the treenode as an implicit variable. Example below places an input field to create editable treenodes.

```xml
<h3>Template</h3>
<p-tree [value]="files">
    <template let-node  pTemplate type="default">
        <input [(ngModel)]="node.label" type="text" style="width:100%">
    </template>
</p-tree>
```

Multiple templates are supported by matching the type property of the TreeNode with the type of pTemplate

```xml
<h3>Template</h3>
<p-tree [value]="files">
    <template let-node  pTemplate type="picture">
        <img [attrs.src]="picture.path">
    </template>
    <template let-node  pTemplate type="default">
        <input [(ngModel)]="node.label" type="text" style="width:100%">
    </template>
</p-tree>
```

**Comment by JakeSummers** [comment]
What is the benefit of using this instead of `ngif` inside the template?

**Comment by cagataycivici** [comment]
A PrimeNG PRO customer were using the ngIf approach but they requested multiple template as it gets complex when you have more node types, multiple templates are cleaner and easier to maintain, instead of multiple *ngIfs.

**Comment by JakeSummers** [comment]
Thanks

**Comment by santoshsas** [comment]
@cagataycivici How do i add my styleClass to TreeNode? I want to change style of Node  ie. ui-treenode. I want to change entire background of TreeNode when node is selected instead of just name of node as in demo.
I see in documentation there is styleClass property for TreeNode but in common/api.d.ts there is no such property.
Thanks in advance

export interface TreeNode {
    label?: string;
    data?: any;
    icon?: any;
    expandedIcon?: any;
    collapsedIcon?: any;
    children?: TreeNode[];
    leaf?: boolean;
    expanded?: boolean;
    styleClass?: string;
    type?: string;
    parent?: TreeNode;
    partialSelected?: boolean;
}

**Comment by olaisen81** [comment]
Hi, as per Docs multiple templates are supported but no more than 2?

`<p-tree [value]="files">
    <template let-node  pTemplate type="picture">
        <img [attrs.src]="picture.path">
    </template>
<template let-node  pTemplate type="image">
Image
    </template>
    <template let-node  pTemplate type="default">
        <input [(ngModel)]="node.label" type="text" style="width:100%">
    </template>
</p-tree>`
