### ISSUE TITLE
Time picker won't allow changes when open/close is the same date and while using the hourFormat="12" with the maxDate & minDate parameters.

### ISSUE THREAD

**Issue by rtsinc** [primefaces/primeng#8810]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/github-b6f2a2-abtuhq

**Current behavior**
Time picker won't allow changes when open/close is the same date and while using the hourFormat="12" with the maxDate & minDate parameters. It seems like the close time can't be changed if the close date is the same as the open date. This is especially noticeable when the dates are after 12 noon.

**Expected behavior**
The hourFormat="12" should behave exactly like hourFormat="24"; you should be able to change the time of the close date using the arrows to be a few hours later than the open time.

**Minimal reproduction of the problem with instructions**
Data setup (anytime is good, but after 12 noon is better)
- Set the open date to now, hour to now, minute to after now
- Set the close date to now, hour to now, minute to before or after now
Steps to duplicate:
Try to change the time of the close date using the arrows to be a few hours later than the open time. It seems like the close time can't be changed if the close date is the same as the open date.

**What is the motivation / use case for changing the behavior?**
Michigan Medicine's Medical School needs to be able to change the dates when setting up tests. Again, hourFormat="12" should behave exactly like hourFormat="24".

**Please tell us about your environment:**
https://stackblitz.com/edit/github-b6f2a2-abtuhq

* **Angular version:** 5.X
We use 7.2.6, but the Primeng template I used is 9.0.4.

* **PrimeNG version:** 5.X
We use 7.0.4, but the Primeng template I used is 9.0.0.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android 
Mac: Chrome 81.0.4044.122, Safari 12.1.2
Windows: IE 11.11558
 
[github-b6f2a2-abtuhq.zip](https://github.com/primefaces/primeng/files/4566264/github-b6f2a2-abtuhq.zip)

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
