### ISSUE TITLE
P-Sidebar modal property doens't work

### ISSUE THREAD

**Issue by GuzzoLM** [primefaces/primeng#8811]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-dgxb24

**Current behavior**
The overlay mask is displayed disregarding the `modal="false"` option.

**Expected behavior**
When `modal="false"` the overlay mas shouldn't be displayed.

**Minimal reproduction of the problem with instructions**
Add a p-sidebar and use the modal option, like in the test case
https://stackblitz.com/edit/github-dgxb24

* **Angular version:** 9.1.4

* **PrimeNG version:** 9.0.6

* **Browser:** [all]

**Comment by desirelabs** [comment]
I guess you shall use `[modal]="false"` (see the brackets around modal).
