### ISSUE TITLE
p-table virtual scroll event is triggering even on scroll up

### ISSUE THREAD

**Issue by pachu4u** [primefaces/primeng#8812]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**

The virtual scroll event gets triggered even when scrolled up with lazy loading. The same can be seen in official demo of the scroll functionality.
**Expected behavior**

Event should be triggered only while scrolling down
**Minimal reproduction of the problem with instructions**
Scroll up and down on the official demo 

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.X

angular 8.2.3
* **PrimeNG version:** 5.X

latest 9.0.6
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by pachu4u** [comment]
I also tried a work around like this. Unfortunately with this the loading-body /loading text doesn't disappear. Does it expect the total records to be increased every time the function is called? 

loadDataOnScroll(event: LazyLoadEvent) {
        console.log(event);
        if(this.scrollOffset < event.first) {
            this.scrollOffset = event.first;
            this.getNextPage();
        }
    }

I see no use of setting this.loading to true or false.

**Comment by cagataycivici** [comment]
VirtualScrolling for Table is reimplemented from the ground up (#8855) and this particular case i no longer an issue with the new implementation. Thank you for the feedback.

**Comment by brayanL** [comment]
Hello guys, this is still present in the latest version, even in your demo:
https://www.primefaces.org/primeng/table/virtualscroll

**Comment by mertsincan** [comment]
Hi, you can use appendOnly:true option in virtualScrollerOptions property or you need to write a cache algorithm yourself in lazy method.
https://www.primefaces.org/primeng/scroller

**Comment by brayanL** [comment]
@mertsincan thanks for your reply but that property is not present in virtualScrollerOptions:

`export interface ScrollerOptions {
    id?: string | undefined;
    style?: any;
    styleClass?: string | undefined;
    tabindex?: number | undefined;
    items?: any[];
    itemSize?: any;
    scrollHeight?: string | undefined;
    scrollWidth?: string | undefined;
    orientation?: ScrollerOrientationType;
    delay?: number | undefined;
    lazy?: boolean;
    disabled?: boolean;
    loaderDisabled?: boolean;
    columns?: any[] | undefined;
    showSpacer?: boolean;
    showLoader?: boolean;
    numToleratedItems?: any;
    loading?: boolean;
    autoSize?: boolean;
    trackBy?: any;
    onLazyLoad?: Function | undefined;
    onScroll?: Function | undefined;
    onScrollIndexChange?: Function | undefined;
}`
