### ISSUE TITLE
p-paginator display in IE bug since PrimeNG version 9.0.3

### ISSUE THREAD

**Issue by piotr-zysk** [primefaces/primeng#8816]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

The bug occurs only in Internet Explorer and as Stackblitz is not working in IE, it is not helpful in reproducing this, unfortunately.

The bug occurs in each component when we use such paginator:
<p-paginator [first]="0" [rows]="20" [totalRecords]="100" [rowsPerPageOptions]="[20,50,100]" ></p-paginator>

**Current behavior**

The look of paginator is broken in IE 11. The vertival position of page changing buttons is incorrect. There are a few pixels lower then the rest of elements (Rows Per Page Select and Custom Content from [templateLeft] is displayed properly but the panel with buttons for chenging current page are too low).

Bug started to occur after upgraded the version of PrimeNg from 9.0.2 to 9.0.3.

**Expected behavior**

We just need to have all elements of paginator properly aligned vertically. Currently the only workaround for this is to downgrade PrimeNg version to 9.0.2, as the bug occurs in all newer versions (tested with 9.0.3, 9.0.4, 9.0.5, 9.0.6)

**Minimal reproduction of the problem with instructions**

To reproduce the issue, it should be sufficient if you run the paginator config below in Internet Explorer 11:

<p-paginator [first]="0" [rows]="20" [totalRecords]="100" [rowsPerPageOptions]="[20,50,100]" ></p-paginator>

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10 Pro 64bit
Visual Studio Code
npm 6.13.4
IIS

* **Angular version:** 5.X

9.1.2

* **PrimeNG version:** 5.X

Issue occurs since PrimeNg version 9.0.3 (bug exists in 9.0.3 and all later version, including 9.0.6)
The last properly working version is 9.0.2.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
IE 11

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

Typescript 3.8.3

* **Node (for AoT issues):** `node --version` =   
v13.5.0

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
