### ISSUE TITLE
Document limitation of Table/TreeTable scrollHeight calc support

### ISSUE THREAD

**Issue by dtaylor84** [primefaces/primeng#8818]
The [Table](https://github.com/primefaces/primeng/blob/a5d8a98e82100fdba4b7b2e90575824f06d9c88f/src/app/showcase/components/table/tabledemo.html#L2239) (and [TreeTable](https://github.com/primefaces/primeng/blob/a5d8a98e82100fdba4b7b2e90575824f06d9c88f/src/app/showcase/components/treetable/treetabledemo.html#L1825)) documentation says scrollHeight can be:

> Height of the scroll viewport in fixed pixels, percentage or a calc expression.

But the actual code does not handle arbitrary CSS calc expressions. It supports only calc expressions of the form:

> calc(x% - y)

This is not clear from the documentation.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
