### ISSUE TITLE
server side pagination event.first return 0 instead of 1

### ISSUE THREAD

**Issue by MohamedSahir** [primefaces/primeng#8820]
I have currently implemented pagination with ngprime datatable.on click on page 1 , it returns event.first as 0 value . how i will write a custom logic by using 0.

instead of that, it returns 1 mean will write logic as follows.
1* 5 =5, 2* 5 =10,3*5 =15 etc.

I don't know whether it is a bug on implementation is like that.

version used:
   "primeicons": "~2.0.0",
    "primeng": "~9.0.6",:

created a stackoverflow:still no response thats what i created an issue here.

https://stackoverflow.com/questions/61616955/ngprime-server-side-pagination-issue-event-first-returns-0-instead-of-1-in-pag

![image](https://user-images.githubusercontent.com/20682302/81090700-c5953380-8f1b-11ea-9883-14fa48260208.png)
![image](https://user-images.githubusercontent.com/20682302/81090769-d8a80380-8f1b-11ea-9314-cc7944bbf3d8.png)

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
