### ISSUE TITLE
TieredMenu does not hide on document click when parent uses OnPush change detection

### ISSUE THREAD

**Issue by brian428** [primefaces/primeng#8821]
Much like other similar issues that have been dealt with over time. `TieredMenu` doesn't hide immediately on document click when parent uses OnPush change detection. I think the `TieredMenu` just needs the ChangeDetectorRef injected into it, and `hide()` should call `detectChanges()`.

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
