### ISSUE TITLE
Tabindex in table header is overridden when using pSortableColumn option

### ISSUE THREAD

**Issue by nironater** [primefaces/primeng#8822]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-8rqdc3

**Current behavior**
I can´t set tabindex if pSortableColumn is used.

**Expected behavior**
The developer should be able to set tabindex. Default value may stay 0.

**Minimal reproduction of the problem with instructions**
open stackblitz, inspect elements and see for yourself.

**What is the motivation / use case for changing the behavior?**
The developer should be able to set tabindex.

**Please tell us about your environment:**
Windows 10, VS Code

* **Angular version:** 9.X
9.0.4

* **PrimeNG version:** 9.X
9.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by nironater** [comment]
After seeing this issue below I thought i'd open a new ticket because it surely is reproduce-able and causing me trouble:
[https://github.com/primefaces/primeng/issues/7595](url)

**Comment by cetincakiroglu** [comment]
Hi,

If the issue still exists with the latest PrimeNG version, please provide a StackBlitz example by using [PrimeNG Issue Template ](https://stackblitz.com/github/primefaces/primeng-issue-template) and re-open the issue.

Regards

**Comment by nironater** [comment]
@cetincakiroglu, it's sad that you didn't even look on my last stack blitz so why bother create another one for you to ignore?
Just state that there is no intent to fix this and that's it.
What a waste of time that was...

**Comment by flawesomesoft** [comment]
@cetincakiroglu what's the deal? An example was provided and it's the exact same behaviour as in PrimeNG v13 and beyond.

The issue was already described in 2019 ([HERE](https://github.com/primefaces/primeng/issues/7595)) and back then it was also mentioned it's not reproducible and we simply should use the new version of PrimeNG.

The issue still persists. How can we convice you guys to take a look at it if a perfect description of the problem plus provided example is not enough?

**Comment by gianluca-moro** [comment]
So, I just stumbled on this issue. I am trying to set `[tabindex]="-1"` on the column headers because I don't want them to get focus. However, it does not seem to work: [Stackblitz Reproducer](https://stackblitz.com/edit/fnkxxb?file=src%2Fapp%2Ftable-single-column-sort-demo.html)
