### ISSUE TITLE
p-steps - not return previously value a style of button

### ISSUE THREAD

**Issue by bear-wolf** [primefaces/primeng#8824]
Hi.
I use your library for angular, and I have a component like <p-steps> which does not have basically feature
like a validation of data on the current step before your switch steps.

[ ] bug report => 
[ x] feature request => set validation and return back css style on step buttons.
[ ] support request => 

My example
https://prnt.sc/sbsby8

> {
                label: 'Согласование с АКАМ',
                styleClass: 'step1',
                command: (event: any) => { 
                    if (!this.checkStep()) {
                        event.index = this.stepActiveIndex; // not working for me
                        return false;
                    }
                    this.stepActiveIndex = 1;
                }
            }

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
