### ISSUE TITLE
When override scrollbar width, Table header not layout correctly 

### ISSUE THREAD

**Issue by mix5003** [primefaces/primeng#8825]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-sgy1ej?file=src%2Fapp%2Fapp.component.ts

**Current behavior**
When css override scrollbar width (in Webkit base browser and Firefox only) . table header not layout correctly.

**Expected behavior**
It should layout correctly

* **Browser:** Chrome / Firefox

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
