### ISSUE TITLE
Wild clicking breakes PrimeNGs Picklist

### ISSUE THREAD

**Issue by VelizarD** [primefaces/primeng#8829]
```
[x] bug report
[ ] feature request
[ ] support request
```
Hi its possible to "break" PrimeNGs Picklist on Chrome, please see attached Youtube video:
https://www.youtube.com/watch?v=C5VF0MY9RF0

I was able to "add" a new empty item and to remove all others.

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
