### ISSUE TITLE
In server side data table p-calendar filtering not working in (onLazyLoad)="nextPage($event)"

### ISSUE THREAD

**Issue by MohamedSahir** [primefaces/primeng#8831]
i am working a server side using ngprime datatable ,all other column filter have dropdown and textbox controls get a filtered a values in (onLazyLoad)="nextPage($event)" events.filters.property.

for calendar , datepicker have not getting a values in this event call.

refer:
https://stackoverflow.com/questions/61659729/ngprime-datatable-lazyloading-p-calender-column-filtering-selected-values-proble

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
