### ISSUE TITLE
p-table inline edit bug when checked clicked

### ISSUE THREAD

**Issue by PHuhn** [primefaces/primeng#8835]
```
[X] bug report => Search github for a similar issue or PR before submitting
```
**PrimeNG Showcase**
https://www.primefaces.org/primeng/showcase/#/table/edit

**Current behavior**
1. go to the **Row Editing** example
1. click pencil on the first row,
1. change the year value to 0,
1. click the check.

The year is now an illegal value.

**Expected behavior**

The grid could stay in edit mode or could revert the edit row.

**What is the motivation / use case for changing the behavior?**

Currently incorrect behavior.

**Please tell us about your environment:**

Chrome browser,
Windows 10 Pro

**Comment by yigitfindikli** [comment]
Editable cells are under your control. You can validate on your side.

Regards.
