### ISSUE TITLE
statekey not stateful to restrictive causing errors

### ISSUE THREAD

**Issue by waratah** [primefaces/primeng#8838]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
stateKey in tables of emtpty string stores in localstorage causing empty columns to display when multiple tabole with differnt keys uuse it.

**Expected behavior**
Should not store state

**Minimal reproduction of the problem with instructions**

https://github.com/primefaces/primeng/blob/master/src/app/components/table/table.ts

in tables.ts it has the following function:
 isStateful() {
        return this.stateKey != null;
    }

I recommend a change to

 isStateful() {
        return !this.stateKey;
    }

This will handle undefined, empty string as well.

**What is the motivation / use case for changing the behavior?**

I have a wrapper and I am sending the state key in always by default I had ''.   I expected this to not store a state.   On my second table there was a total clash of keys giving me anull columns in the p-table due to mismatches on the sort keys.

**Please tell us about your environment:**
Windows,

* **Angular version:** 7

* **PrimeNG version:** 7.1.3

* **Browser:**Chrome 
 
* **Language:**  TypeScript 3.2.4

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
