### ISSUE TITLE
Contents duplicating on dragging and dropping items from a div container to a p-table. 

### ISSUE THREAD

**Issue by akash1525** [primefaces/primeng#8841]
I have a div container which is an ng2-Dragula div container. I am using the DragulaService to drag n drop contents from the container to the p-table. The issue I am having is when I drag n drop contents, the contents are getting duplicated. This issue does not happen when I use a regular HTML table. 

You can emulate my issue on Stack-blitz. You will see a div container having elements of characters 1 to 21 which is a scrollable div. If you drag and drop 1 on the table, you get 1 as output. Now drag character 2, you get 2 1 2 1 on the table. Drag 3 and you get 9 elements in the table and for 4 I get 16, etc. I see this is returning square of the elements in the table but I don't know how to stop it. It maybe a simple fix but any advice is appreciated. Thank you in Advance. 

Here is my Stackblitz link where you can replicate the issue I am having.   

https://qgnirxral.github.stackblitz.io/
<img width="1654" alt="Screen Shot 2020-05-13 at 6 18 49 PM" src="https://user-images.githubusercontent.com/26127178/81871792-8895f600-9546-11ea-97cb-83fff7005031.png">

Steps to reproduce --> 
1. Drag elements from the div container (blue border) and drag it to the table (It has First Name, Last Name as a <th>, black border)
2. Now Drag another element and see rows getting duplicated. Drag more elements and you shall see the issue.  

My Dev Environment : 
ng-cli v9
Primeng version 9
Here are my dependencies (Package.json)

"dependencies": {
    "@angular/animations": "~9.1.4",
    "@angular/cdk": "^9.2.3",
    "@angular/common": "~9.1.4",
    "@angular/compiler": "~9.1.4",
    "@angular/core": "~9.1.4",
    "@angular/forms": "~9.1.4",
    "@angular/platform-browser": "~9.1.4",
    "@angular/platform-browser-dynamic": "~9.1.4",
    "@angular/router": "~9.1.4",
    "@fullcalendar/core": "^4.4.0",
    "chart.js": "^2.9.3",
    "core-util-is": "^1.0.2",
    "dom-autoscroller": "^2.3.4",
    "ng2-dragula": "^2.1.1",
    "primeicons": "^3.0.0-rc.1",
    "primeng": "^9.0.6",
    "quill": "^1.3.7",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
}

Below is the source code. 
[qgnirxral.github.zip](https://github.com/primefaces/primeng/files/4625003/qgnirxral.github.zip)

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
