### ISSUE TITLE
Accesibility issue with scrollable Table - td-has-header

### ISSUE THREAD

**Issue by sandipchitale** [primefaces/primeng#8845]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
Use scrollable p-table. You may use the sample page: https://www.primefaces.org/primeng/showcase/#/table

**Expected behavior**
Accessibility report from Axe extension in Chrome Devtools should be clean.

**Minimal reproduction of the problem with instructions**

- Use the sample page: https://www.primefaces.org/primeng/showcase/#/table 

- Run Chrome Devtools extension like Axe (for accessibility).

The following two issues happen.

td-has-header - All non-empty td element in table larger than 3 by 3 must have an associated table header (Please see: https://dequeuniversity.com/rules/axe/3.5/td-has-header?application=axeAPI)

**What is the motivation / use case for changing the behavior?**

To get clean accessibility report.

**Please tell us about your environment:**
yarn, angular 9

* **Angular version:** 5.X

9.x
* **PrimeNG version:** 5.X

9.0.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

* **Node (for AoT issues):** `node --version` =   
12.x

**Comment by sandipchitale** [comment]
I guess because of the use of two separate tables for the header and body section there is not much that can be done about this.

**Comment by antsteyer** [comment]
Accesibility must be considered for p-table, many business needs this critera in production

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
