### ISSUE TITLE
Error compiling ScrollPanelModule module on Linux

### ISSUE THREAD

**Issue by ChicoMetal** [primefaces/primeng#8851]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
Compile version 9 angular application for production while implementing the ScrollPanelModule module.
I implemented the module being in version 7 and had the same problem but managed to solve it by importing the module not from: import {ScrollPanelModule} from 'primeng / scrollpanel'; as indicated in the documentation if not from: import {ScrollPanelModule} from 'primeng / components / scrollpanel / scrollpanel';
In this way I achieved that the compilation was successful and that the functionality was normal, but when updating to version 9 of angular this import was not valid and in the original way as it is in the documentation it works normally in a development environment and at compiling locally, the problem lies in compiling from Jenkins.
Perform tests with different modules and the result was successful, both locally and from Jenkins.

**Expected behavior**
Successful compilation.

**Minimal reproduction of the problem with instructions**
When compiling the project by continuous deployment in jenkins, on a server with Linux OS, an error occurs in the compilation of the module.

**What is the motivation / use case for changing the behavior?**
Achieve the use of module implementation in a productive environment

**Please tell us about your environment:**
The operating system that I use for local development is Windows, the deployment is done through Jenkins installed on Linux servers

* **Angular version:**
Upgrade from angular 7 to version 8 and then 9

* **PrimeNG version:**
9.0.6

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
does not apply
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
"typescript": "3.8.3"

* **Node (for AoT issues):** `node --version` =   
![bug](https://user-images.githubusercontent.com/5455480/82244573-0b340200-9907-11ea-9716-cf7a2d93b5c3.png)

I tried various versions of Node on Jenkins job, 10.13, 12.14.1, 12.16.1

**Comment by cagataycivici** [comment]
Should be primeng/scrollpanel

**Comment by ChicoMetal** [comment]
if indeed that was the problem.
Thank you.
