### ISSUE TITLE
Optional UTF-8-BOM parameter for exportCsv

### ISSUE THREAD

**Issue by piero1903** [primefaces/primeng#8853]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
I think this functionality has changed a few times in last years. We should have the possibility to choose between UTF-8-BOM and UTF-8 and it can be default UTF-8. Opening the dowloaded file with Excel causes encoding Problems.

**Expected behavior**
Table can be exported with UTF-8-BOM.

**Minimal reproduction of the problem with instructions**
* Table with special characters(language=de)
* Click csv export button
* Open file with Excel
* The content is not properly encoded

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:**  9.1.4

* **PrimeNG version:** 9.0.6

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
