### ISSUE TITLE
File Upload Advanced Mode not allowing dropdown file picker, basic works though.

### ISSUE THREAD

**Issue by a1g0rithm** [primefaces/primeng#8858]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**

File Upload on latest version advanced mode is not working properly.  Basic works fine.

**Expected behavior**

When using template code in file upload example the expected behavior is after clicking "choose" for file a modal dropdown to the file system should appear.  This is not the case with the latest version on any browser.  Basic mode does work properly for this.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Mac OSX Catalina 10.15.4,  Visual Studio Code 1.45.0, NPM 

* **Angular version:** 5.X

9.1.1

* **PrimeNG version:** 5.X

9.0.6

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 All

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 3.8.3
* **Node (for AoT issues):** `node --version` =

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
