### ISSUE TITLE
Autocomplete: force suggestion list to remain visible once we clear the input field

### ISSUE THREAD

**Issue by dsebastien** [primefaces/primeng#8862]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

When we clear out the input associated with the autocomplete, the list of suggestions hidden/removed from the DOM.

**Expected behavior**
 In our application, we would like to keep that list visible while the input has focus

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
N/A

* **Angular version:** 5.X
9.1.0

* **PrimeNG version:** 5.X
9.0.6

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 3.8.3

* **Node (for AoT issues):** `node --version` =

**Comment by dsebastien** [comment]
We've tried various things using hide, show, focusInput, etc but to no avail. When the user removes the last character from the input, then the suggestion box disappears.

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.
