### ISSUE TITLE
p-multiselect (accessibility issue): The semantic usage of < ul > and < li > is incorrect .

### ISSUE THREAD

**Issue by qiong253112** [primefaces/primeng#8866]
**Current behavior**
< ul > and < li > are not direct parent-child relationships. If we use the accessibility insight for web tool to test then will get the following issue:
![image](https://user-images.githubusercontent.com/29710072/82646137-a221f680-9c46-11ea-9735-380765dee281.png)

**Expected behavior**
`< li >` has a direct parent item `< ul >/<ol>`

Reference Links
[Accessibility Insights!](https://nam06.safelinks.protection.outlook.com/?url=https://accessibilityinsights.io/&data=02%7c01%7cv-poyad%40microsoft.com%7cc11478591b5a474f6d9d08d7199726c0%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637006009300301864&sdata=ZTWYamT1yE7yko5QU35ZJLf/5ZydtDeGAKrQGUiugJs%3D&reserved=0) - Identify accessibility bugs before check-in and make bug fixing faster and easier.

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
