### ISSUE TITLE
p-menu => Customize content

### ISSUE THREAD

**Issue by sagarwtca** [primefaces/primeng#8868]
Is there any way to write custom template with *ngFor for menu items,

i want like this
<p-menu styleClass="main-menu" class="main-menu" [model]="menus">
    <ng-template let-menus pTemplate>
        {{menus.label}} <span>otherStuff</span>
    </ng-template>
</p-menu>

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
