### ISSUE TITLE
Autocomplete: completeOnFocus doesn't work properly on mobile devices 

### ISSUE THREAD

**Issue by JacksonFaller** [primefaces/primeng#8869]
I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
On mobile devices when you click on an input dropdown is displayed and then hidden.

**Expected behavior**
On mobile devices when you click on an input dropdown is displayed and stays this way till focus is lost.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/angular-wqkhc6
Open link on any mobile device. 
Click on the input field.

**What is the motivation / use case for changing the behavior?**
Behaviour is clearly incorrect.

* **Angular version:** 9.X

* **PrimeNG version:** 9.06

* **Browser:** [Chrome XX | Firefox XX ]

**Comment by yigitfindikli** [comment]
Stackblitz example is broken. Please feel free to reopen with a new stackblitz example.

**Comment by joaosouz91** [comment]
This issue still happens. Any ideas as workaround?
