### ISSUE TITLE
Dropdown does not disable items if the optionLabel is set.

### ISSUE THREAD

**Issue by michaelakin** [primefaces/primeng#8871]
https://github.com/primefaces/primeng/blob/302912c07be16991df3b98c308009d53d3fe1f5a/src/app/components/dropdown/dropdown.ts#L373

Please enable the ability to disable items in the dropdown list even if the [optionLabel] is set.

**Comment by yigitfindikli** [comment]
Fixed in v11.0.0-rc.1
