### ISSUE TITLE
FileUpload - No invalid file size message displayed in basic mode and no callback is called

### ISSUE THREAD

**Issue by cesarrew** [primefaces/primeng#8879]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-eqpxu8?file=src%2Fapp%2Fapp.component.html

**Current behavior**
The invalid file size message is not displayed in fileUpload in basic mode.

**Expected behavior**
The message should be displayed or the onError event method should be called with the configured error message.

**Minimal reproduction of the problem with instructions**
Using the demo in https://stackblitz.com/edit/github-eqpxu8?file=src%2Fapp%2Fapp.component.html, try to upload a file with 1mb or more. Nothing happens.

* **Angular version:** 9.1.0

* **PrimeNG version:** 9.0.0

* **Browser:** [all]

**Comment by aminTiz** [comment]
I have the same issue. I wonder if you found a solution for this.

**Comment by cesarrew** [comment]
Unfortunately not.

Em qui., 19 de nov. de 2020 20:45, Amin <notifications@github.com> escreveu:

**Comment by matusko89** [comment]
Any progress? I would be grateful if onError event method would be called with the configured error message.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
