### ISSUE TITLE
FileUpload - No file choose modal appears if I try to upload another file in auto basic mode

### ISSUE THREAD

**Issue by cesarrew** [primefaces/primeng#8880]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-eqpxu8-lodzid?file=src%2Fapp%2Fapp.component.html

**Current behavior**
After uploading a file, if I try to upload another file, the file choose modal is not displayed and the same first file is uploaded again.

**Expected behavior**
The file choose modal should appear and let me choose another file.

**Minimal reproduction of the problem with instructions**
Using the demo in https://stackblitz.com/edit/github-eqpxu8-lodzid?file=src%2Fapp%2Fapp.component.html, upload a file and than try to upload another.

* **Angular version:** 9.1.0

* **PrimeNG version:** 9.0.0

* **Browser:** [all]

**Comment by jamesXG** [comment]
how to save

**Comment by yigitfindikli** [comment]
You need to call the clear method from fileupload. Because you're using customUpload. You can check at (documentation)[https://primefaces.org/primeng/showcase/#/fileupload].
