### ISSUE TITLE
Typo in the documentation of inputNumber

### ISSUE THREAD

**Issue by dominikfilkus** [primefaces/primeng#8882]
Here: https://www.primefaces.org/primeng/showcase/#/inputnumber

In the Documentation section the example looks like this: 
`<p-inputnumber [(ngModel)]="val"></p-inputnumber>`

It should be

`<p-inputNumber [(ngModel)]="val"></p-inputNumber>`

The Source tab has the correct version already.

**Comment by crumhorn** [comment]
Just to add, there's also typos in the currency section, the United States Locale has EUR in the code, and so on.

```
United State Locale
<p-inputnumber [(ngModel)]="value2" mode="currency" currency="EUR" locale="de-DE"></p-inputnumber>

German Locale
<p-inputnumber [(ngModel)]="value3" mode="currency" currency="INR" locale="en-IN"></p-inputnumber>

Indian Locale
<p-inputnumber [(ngModel)]="value4" mode="currency" currency="JPY" locale="jp-JP"></p-inputnumber>
```
