### ISSUE TITLE
Consider renaming onLabel and onIcon attributes

### ISSUE THREAD

**Issue by Cito** [primefaces/primeng#8884]
The `ToggleButton` component uses attributes `onLabel` and `onIcon`, which is a bit unfortunate since they can be mistaken for event handlers because of the `on` prefix, and causes some IDEs to mark templates with these attributes as erroneous.

My suggestion is to add aliases `labelOn`, `labelOff`, `iconOn`, `iconOff` for the existing attribute names, and deprecate the current attribute names.

Somebody else already mentioned this in #8436. Maybe you should consider renaming these in PrimeNG 10 so that no workaround is necessary in the future.

**Comment by lwestfall** [comment]
I'd like to throw in support for this issue. This is causing my vscode to show errors unneccessarily. Binding is an ugly work around (but a workaround nonetheless).

Any chance we can get this in 10?

**Comment by adama357** [comment]
After upgrading from Angular 8 and PrimeNG 8 to Angular 10 and PrimeNG 9, many pages on our site break with this console error: 

`Error: Binding to event attribute 'onLabel' is disallowed for security reasons, please use (Label)=...`

I'm going to try changing every instance of this in our code to binding, but it would certainly be nice if they'd be renamed. 

Thanks!

**Comment by adama357** [comment]
Actually binding is somewhat problematic, because it means the `i18n-onLabel` properties won't work correctly. Thankfully we only support English at the moment, but this will become a headache when we add support for other languages.

**Comment by DnlCYan** [comment]
I agree with @Cito , this is an annoying conflict.
It's great to have a workaround with binding, but it's unnecessary extra work that could be avoided every time we use the component.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
