### ISSUE TITLE
p-table: filter not working on 9.1.0

### ISSUE THREAD

**Issue by jacqueslareau** [primefaces/primeng#8888]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/github-yjs23x

**Current behavior**
Does not filter.

**Expected behavior**
Should filter.

**Minimal reproduction of the problem with instructions**
Try a filtering.

**What is the motivation / use case for changing the behavior?**
Filter table data.

**Please tell us about your environment:**
Windows 10

* **Angular version:** 5.X
9.1.9

* **PrimeNG version:** 5.X
9.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

* **Node (for AoT issues):** `node --version` =   
12+

**Comment by yigitfindikli** [comment]
Hi,
Built-in filter doesn't work with lazy tables.  You can use the onLazyLoad event when filtering. There is an example usage onLazyLoad event: https://stackblitz.com/edit/github-yjs23x-vpcjtp . 
A little tip: If you want to use PrimeNG built-in filters you can use with PrimeNG FilterUtils https://primefaces.org/primeng/showcase/#/filterutils

**Comment by mvelyov** [comment]
Hi, the filter table data is not working in your case, because _virtualScroll_ property is set to true. This is causing an error (ExpressionChangedAfterItHasBeenCheckedError) in cdkVirtualScrollViewport component (see the screenshot) and that's why filtering and sorting of the table is not working correct. I saw the error when started PrimeNg project and set this property to true, but in your demo I can't see the error. Still I think that your issue is caused by the same error.

![error](https://user-images.githubusercontent.com/33877925/83872206-30fc3c00-a73a-11ea-858e-40099536d01d.PNG)

When _virtualScroll_ property is set to false, then filtering and sorting of the table is working fine, but you are losing the virtual scroll functionality.

**Comment by MickeyMiner** [comment]
Is there any fix to this one?

**Comment by jacqueslareau** [comment]
> Hi,
> Built-in filter doesn't work with lazy tables. You can use the onLazyLoad event when filtering. There is an example usage onLazyLoad event: https://stackblitz.com/edit/github-yjs23x-vpcjtp .
> A little tip: If you want to use PrimeNG built-in filters you can use with PrimeNG FilterUtils https://primefaces.org/primeng/showcase/#/filterutils

Not sure what happened here? Why is it closed? The example I provided does not use the lazy functionnality. Still not working.

**Comment by ralscha** [comment]
Same problem. I have a p-table with `[virtualRowHeight]="33" [virtualScroll]="true"` and sort no longer works.
Removing virtualScroll restores sort functionality.

**Comment by jacqueslareau** [comment]
@yigitfindikli this has been wrongfully closed. I think the issue was misunderstood. Should I create a new issue?

**Comment by markvdkerkhof** [comment]
Same problem:
I don't use lazy tables.


<p-table *ngIf="orders != null" #tt [columns]="orderColums" [value]="orders" contextMenuSelectionMode="joint" filterDelay="500"
  selectionMode="single" (onRowSelect)="onRowSelect($event)" [(selection)]="selectedOrder"
  [scrollable]="true"
  [scrollHeight]="'calc(100vh - 301px)'"  [rows]="orders.length"
  [virtualRowHeight]="34"
  [virtualScroll]="true">

Filter doesn't work anymore. Also get error 
handleError Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value for 'height': '18938px'. Current value: '612px'.

**Comment by jacqueslareau** [comment]
@cagataycivici this issue should not be closed.

**Comment by rfrancisco** [comment]
This is still not working. Please reopen the issue.

**Comment by markvdkerkhof** [comment]
A better title for my problem is "p-table: **sort** not working on 9.1.0"

**Comment by markvdkerkhof** [comment]
I (re)created an issue for it: 
https://github.com/primefaces/primeng/issues/9154 : p-table: when virtualScroll enabled sort not working on 9.1.0
