### ISSUE TITLE
PrimeNG 9.1.0: New problem with resolving of './images/color.png' in '...\node_modules\primeng\resources'

### ISSUE THREAD

**Issue by mlc-mlapis** [primefaces/primeng#8889]
```
[x] bug report
```
**Current behavior**
After updating to PrimeNG 9.1.0, the following problem appeared in our environment when trying to run: **ng serve**
```
ERROR in C:/.../node_modules/primeng/resources/primeng.min.css (C:/.../node_modules/css-loader/dist/cjs.js??ref--12-1!C:/.../node_modules/postcss-loader/src??embedded!C:/.../node_modules/primeng/resources/primeng.min.css)
Module Error (from C:/.../node_modules/postcss-loader/src/index.js):
(Emitted value instead of an instance of Error) CssSyntaxError: C:\...\node_modules\primeng\resources\primeng.min.css:1:15962: Can't resolve './images/color.png' in 'C:\...\node_modules\primeng\resources'
```
Not sure what happened in PrimeNG 9.1.0 or what affected the CSS compilation, but it's evident that
```
'./images/color.png'
```
in not located directly in
```
'C:\...\node_modules\primeng\resources'
```
but in
```
'C:\...\node_modules\primeng\resources\components\colorpicker'
```
The strange is, that in the comparison between PrimeNG 9.1.0 and 9.0.6 (CSS sources and so) I didn't find any relevant difference that would explain the reason why the problem happens with 9.1.0 and not with 9.0.6.

**Expected behavior**
 The previously latest version of PrimeNG 9.0.6 didn't have that problem at all.

**Please tell us about your environment:**
Angular CLI: 9.1.7
Nx: 9.3.0 (but it shouldn't affect the things)
Node: 12.13.1
OS: win32 x64

Angular: 9.1.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package Version
-----------------------------------------------------------
@angular-devkit/architect 0.901.6
@angular-devkit/architect-cli 0.901.7
@angular-devkit/build-angular 0.901.7
@angular-devkit/build-optimizer 0.901.7
@angular-devkit/build-webpack 0.901.7
@angular-devkit/core 9.1.6
@angular-devkit/schematics 9.1.6
@angular-devkit/schematics-cli 0.901.7
@angular/cdk 9.2.4
@angular/cli 9.1.7
@ngtools/webpack 9.1.7
@schematics/angular 9.1.6
@schematics/schematics 0.901.7
@schematics/update 0.901.7
rxjs 6.5.5
typescript 3.8.3
webpack 4.42.0

**Comment by mlc-mlapis** [comment]
Nobody has the same problem? It has been working since ages till 9.1.0. It stopped without any change in code, just only with updating to 9.1.0. We had to downgrade to the previous latest working version of 9.0.6.

**Comment by mlc-mlapis** [comment]
I tried once more after installing Angular 9.1.11 and CLI 9.1.8 and now it works normally as before. I didn't try to find out what was the origin of the problem before. Closing the issue as solved.

**Comment by edwingr93** [comment]
tengo problema en que no puedo enviar una url desde un string a src no me lo acepta

**Comment by waguirre** [comment]
Validte .yarnclean no has images folder for clean

**Comment by NicoHackCode** [comment]
I have the same problem with react, did you manage to solve it?
