### ISSUE TITLE
Calendar component's now-button gives wrong date after sliding the time sliders

### ISSUE THREAD

**Issue by raaaste** [primefaces/primeng#889]
The calendar component's now-button gives wrong date after sliding the time sliders. This is reproduceable on the demo page http://www.primefaces.org/primeng/#/calendar 'DateTime' demo.
1. click now
2. the date is correct
3. slide the minute or hour slider
4. click now
5. observe the wrong date

**Comment by raaaste** [comment]
I tested this furher and noticed that the "Custom time" demo on the same demo page as the "DateTime" demo doesn't have the same bug. It seems to have something to do with the time zone in the timeFormat attribute. If for example I have a component with

`<p-calendar [(ngModel)]="startDate" [readonlyInput]="true" dateFormat="dd.mm.yy" timeFormat="HH:mm:ss z" timeControlType="select" [horizontalTimeControls]="true" maxDate="+0d" </p-calendar>`

there is no problem. However, if I remove the "z" in timeFormat, it breaks again as described in the comment above.

**Comment by cagataycivici** [comment]
Obselete now as calendar is rewritten.
