### ISSUE TITLE
 [PR] Fix 9.1.0 p-dialog resize bug miscalculates drag position

### ISSUE THREAD

**Issue by eberling** [primefaces/primeng#8892]
```
[X] bug report with pull request 
```
* **Current Behavior**:
Resizing container before dragging the container miscalculates resize as it doesn't account for the centering behavior of flexbox. The container resizes half as fast as the mouse distance travelled
* **Expected Behavior**:
The corner of dragging container follows the mouse, increasing container size based on mouse position. 
* **Fix with Pull Request**:
Until container has been dragged (as in moved), container maintains centering on resize due to flexbox parent, causing it to resize in each direction, thus doubling size increase (as the right side is being resized, the left side also expands, maintaining centering). Therefore we add a second ```deltaX``` and ```deltaY``` distance, accounting for the other side.
Once dragged, resize behavior changes and resizing causes only one side to resize. Dragging causes the container to add css style ```"top"``` and  ```"left"```. Based on this we can assess whether centered resizing behavior is active, storing it in ```"hasBeenDragged"```.
**[proposed Fix pull request](https://github.com/primefaces/primeng/pull/8910)**

**Behavior can be demoed here** 
https://stackblitz.com/edit/github-ff9yv1

**or naturally, here**
https://www.primefaces.org/primeng/showcase/#/dialog

* **What is the motivation / use case for changing the behavior?**
expected UI changes based on mouse position to improve User experience

* **PrimeNG version:**  9.1.0

* **Browser:** all

**Comment by yigitfindikli** [comment]
Fixed in https://github.com/primefaces/primeng/commit/40af6550f530f108775ffa136418ac4c9f59e97a
