### ISSUE TITLE
SlideMenu should be able to use the expanded MenuModel attribute to expand the menu programmatically

### ISSUE THREAD

**Issue by jorgefgm** [primefaces/primeng#8893]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
The only way to expand or go to the submenu when using a SlideMenu is by clicking the menu item. If we set the expanded attribute to true within the MenuItem that is being passed to the SlideMenu nothing happens.

**Expected behavior**
Since the SlideMenu is using the MenuModel, and the objective of the expanded attribute is to expand/view the submenus, we should be able to use the expanded attribute to display a submenu programatically.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
You could have router links that point to different URL's. Some of them could be related to a submenu within a SlideMenu. The idea behind this is that when the user goes directly to the URL that is part of a submenu, the user should be able to see the submenu on the SlideMenu and not the main menu.

**Please tell us about your environment:**
Windows

* **Angular version:** 5.X
Angular 9.1.0

* **PrimeNG version:** 5.X
PrimeNG 9.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
