### ISSUE TITLE
issue with table column filter 

### ISSUE THREAD

**Issue by Rajemajji** [primefaces/primeng#8894]
I'm using Ng grid table and in that i have applied column filters, which is in type of text, date and decimal columns, once i applied column filter, for some rows expansions , data is not coming for some rows it is working. if im not applying any filter, then row expansion is working fine for all rows

**Comment by JacobSiegle** [comment]
Can you provide an example via stackblitz?

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
