### ISSUE TITLE
javascript error in gallery

### ISSUE THREAD

**Issue by dolphinsd** [primefaces/primeng#8897]
Latest version 9.1.0 gallery produces error:

core.js:4115 ERROR TypeError: Cannot read property 'forEach' of undefined
    at GalleriaItemSlot.set [as item] (primeng-galleria.js:619)
    at setInputsForProperty (core.js:9097)
    at elementPropertyInternal (core.js:8116)
    at Module.ɵɵproperty (core.js:14438)
    at GalleriaThumbnails_div_6_Template (primeng-galleria.js:211)
    at executeTemplate (core.js:7731)
    at refreshView (core.js:7600)
    at refreshDynamicEmbeddedViews (core.js:8696)
    at refreshView (core.js:7624)
    at refreshComponent (core.js:8771)

line 619 is 
  this.templates.forEach(function (item) {
                if (item.getType() === _this.type) {
                    switch (_this.type) {
                        case 'item':
                        case 'caption':
                        case 'thumbnail':
                            _this.context = { $implicit: _this.item };
                            _this.contentTemplate = item.template;
                            break;
                    }
                }
            });

the following code:
  <p-galleria #galleria
                        [(value)]="images"
                        [numVisible]="5"
                        [containerStyle]="getGaleryStyle()"
                        [responsiveOptions]="responsiveOptions"
                        [hidden]="!(images.length > 0)"
                        [autoPlay]="false"
                        [(activeIndex)]="activeIndex"
                        [showThumbnails]="showThumbnails"
                        [showItemNavigators]="true"
                        [showItemNavigatorsOnHover]="true"
                        thumbnailsPosition="left"
                        [circular]="true">
                <ng-template pTemplate="caption" let-item>
                    <h4 *ngIf="item.title" style="margin-bottom: .5rem; color: #ffffff;">{{item.title}}</h4>
                    <p *ngIf="item.alt">{{item.alt}}</p>
                </ng-template>
                <ng-template pTemplate="item" let-item>
                    <a [href]="item.url" target="_blank"><img alt="{{item.alt}}" [src]="item.source" style="width: 100%; display:block" /></a>
                </ng-template>
                <ng-template pTemplate="thumbnail" let-item>
                    <div class="p-grid p-nogutter p-justify-center">
                        <img [src]="item.source" style="max-width:60px" />
                    </div>
                </ng-template>
            </p-galleria>

**Comment by birdcw** [comment]
I'm also getting an error at primeng-galleria.js:211 (v. 9.1.0). My implementation follows the examples in the documentation. Wish I could be of more help, but definitely +1 on this issue.

`this.templates is undefined`

**Comment by ndouli** [comment]
Latest version 9.1.0 gallery
Same error here. Following examples in documentation

this.templates is undefined

**Comment by dolphinsd** [comment]
9.1.0 has a number of issues across various controls. including paging tables.

**Comment by asabzi** [comment]
I'am getting this error too.

**Comment by saigithub1** [comment]
what is the solution, should we live with it?
