### ISSUE TITLE
Error on use filter with p-dropdown: Can't bind to 'options'

### ISSUE THREAD

**Issue by NayanaRavi94** [primefaces/primeng#8898]
When I use p-dropdown in mycomponent and compile , I get below compilation error.  I have imported FormsModule, DropdownModule in app.module.ts .  Please help to fix this issue. 
 error NG8002: Can't bind to 'filter' since it isn't a known property of 'p-dropdown'.
1. If 'p-dropdown' is an Angular component and it has 'filter' input, then verify that it is part of this module.
2. If 'p-dropdown' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.     
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

**Comment by yigitfindikli** [comment]
Import DropdownModule in your app.module
