### ISSUE TITLE
Problem with toggeable components using material2 

### ISSUE THREAD

**Issue by erlopezh** [primefaces/primeng#890]
Hi, sorry my bad english.
I'm newest and I have a problem with the components renderization in my project that uses PrimeNG and Material2.
First, the components look great:

![captura de pantalla 2016-09-12 a las 9 03 57 a m](https://cloud.githubusercontent.com/assets/16109226/18438665/f012246a-78c7-11e6-91cd-901eebb7abbf.png)

But, when the "fieldset" (or anyone toggleable component) is collapsed then , the following occurs:

<img width="338" alt="captura de pantalla 2016-09-11 a las 11 03 53 p m" src="https://cloud.githubusercontent.com/assets/16109226/18438797/7010c0fe-78c8-11e6-9a26-fa765d734e6f.png">

Please, any idea ?? 
Thanks.

**Comment by cagataycivici** [comment]
Do you use css from primeui or primeng? You need to use;

<link rel="stylesheet" type="text/css" href="/node_modules/primeng/resources/primeng.min.css" />

**Comment by erlopezh** [comment]
I was using css from primeui instead primeng.  Thank you very much, @cagataycivici
