### ISSUE TITLE
Inputnumber, decimal numbers

### ISSUE THREAD

**Issue by MarkusKuepper** [primefaces/primeng#8900]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://www.primefaces.org/primeng/showcase/#/inputnumber

**Current behavior**
With Locale DE it is impossible to enter the fractional part of a number easily. (You have to switch the cursor position behind the comma and then can change digits there).

**Expected behavior**
I would expext by typing something like 1,23  to get a value of 1,23 and not of 123.
It also did not work with a ".". This might even be locale independent?!

**Minimal reproduction of the problem with instructions**
Try entering a fractional number on the Showcase side. 

**What is the motivation / use case for changing the behavior?**
User want to enter form data quickly and without much fuzz. Need to use cursor position or mouse input to enter a simple number kills UX.

**Please tell us about your environment:**
Not applicable as it is already evident in Showcase.

* **Angular version:** 5.X
Showcase.

* **PrimeNG version:** 5.X
9.1.0

* **Browser:** 
Tested:
Chrome & Firefox

**Comment by epoch79** [comment]
+1

**Comment by clevelandcs** [comment]
+1 Experiencing the same issue with mode="decimal" locale="en-US" AND with mode="currency" currency="USD"

**Comment by franciscoghansen** [comment]
Same here with mode decimal and locale="pt-BR". Also with currency mode and currency="BRL". v9.1.0 and angular 9.1.8

**Comment by Timmeeeey** [comment]
@mertsincan Hi,

there are still some issues with inputNumber.

- pasting a number with fractional digits does't work. If you paste 123,45 you get 12.345,00.
- when you select an existing number with fractional digits and try to replace it by typing 123 you get 1,0023.

**Comment by striebhz** [comment]
I don't know how this will be solved but maybe it's worth to take a look at https://github.com/autoNumeric/autoNumeric ?

**Comment by mertsincan** [comment]
Thanks a lot for the feedbacks, @brunokrebs and @Timmeeeey !

@Timmeeeey 
> pasting a number with fractional digits does't work. If you paste 123,45 you get 12.345,00.
Could you please create a new ticket for this issue on PrimeNg Github? 

Other problems are solved. Fixed in https://github.com/primefaces/primeng/commit/1258ca4d4b7a15575fa950fc83af980f2107d3d5

Best Regards,

**Comment by Timmeeeey** [comment]
@mertsincan 
I created a new issue #9219 for the pasting problem.

**Comment by Guilmeer** [comment]
I'm using primeng 12.2.3, angular 12.2.16, and still got this issue. If I type 1234 I want "12.34", not "1234". I'm with decimal mode on and tested w/wo locale="pt-BR". How can I fix it?
