### ISSUE TITLE
p-inputNumber ignores disabled state in reactive forms

### ISSUE THREAD

**Issue by crumhorn** [primefaces/primeng#8901]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/github-1svgpy

**Current behavior**
Form field does not disable

**Expected behavior**
Form field is disabled when it is set to be disabled.

**Minimal reproduction of the problem with instructions**

See Stackblitz above for functional example.

If the reactive form uses p-inputNumber and it's set to disabled, the control does not disable.

HTML
```<p-inputNumber id="limit" formControlName="limit" mode="decimal" [minFractionDigits]="selectedTradedInstrument?.sgfntPriceDecimals"></p-inputNumber>```

Form creation
```limit: [{value: 0, disabled: true}, [Validators.required]],```

* **Angular version:** 5.X
8.2.3

* **PrimeNG version:** 5.X
9.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome Latest
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 3.5.3

**Comment by epoch79** [comment]
+1
