### ISSUE TITLE
Commit #6e26377 broke p-sortIcon display when using Material themes

### ISSUE THREAD

**Issue by beleta** [primefaces/primeng#8904]
Commit [#6e26377](https://github.com/primefaces/primeng/commit/6e2637729e18e169b740ae4864532945222a5274) broke p-sortIcon display when using purchased Material themes like Ultima or Barcelona.

**Current behavior**
p-sortIcon does not show any icon when using Material themes like Ultima or Barcelona 

**Expected behavior**
p-sortIcon should display an icon

* **Angular version:** 
9.1.9

* **PrimeNG version:** 
9.1.0

The problem shows because 'pi-sort-amount-up-alt',  'pi-sort-amount-down' and 'pi-sort-alt' icons are not defined in theme-xxxx.css.

**Comment by yigitfindikli** [comment]
Hi @beleta, 
Thanks for reporting this issue. Fixed for next theme releases. If you want a quick fix, you can change _icons.scss to this:


    &.pi-sort{@include icon-override("sort");} to &.pi-sort-alt {@include icon-override("sort");}

    &.pi-sort-up{@include icon-override("keyboard_arrow_up");} to &.pi-sort-amount-up-alt {@include icon-override("keyboard_arrow_up");}

    &.pi-sort-down {@include icon-override("keyboard_arrow_down");} to &.pi-sort-amount-down {@include icon-override("keyboard_arrow_down");}
