### ISSUE TITLE
galleria v. 9.1.0 - thumbnails update with async data, but not the currently displayed item.

### ISSUE THREAD

**Issue by birdcw** [primefaces/primeng#8911]
I'm submitting a bug report

**Current behavior**
When I give p-galleria a new value array (using `| async`), the thumbnails update, as you'd expect. But the item image above remains the same. It is still the last active image of the previous value array.

**Expected behavior**
When I give p-galleria a new value array, I expect the active index to reset to the default, and the active image to be sampled from the new value array.

**Minimal reproduction of the problem with instructions**
```
<ng-container *ngIf="(value$ | async) as value">

<p-galleria [value]="value" [showThumbnails]="true [numVisible]="3">
    
    <ng-template pTemplate="item" let-item>
      <img [src]="item.itemSrc" />
    </ng-template>
    
    <ng-template pTemplate="thumbnail" let-item>
      <div class="p-grid p-nogutter p-justify-center">
        <img [src]="item.thumbnailSrc" />
      </div>
    </ng-template>

  </p-galleria>

</ng-container>
```
**What is the motivation / use case for changing the behavior?**
Expected behavior is essential for any case where the collection of images to be displayed might change after the page has loaded. It must be assumed that the currently displayed image is obsolete as soon as a change is detected in `<p-galleria [value] >`

**Please tell us about your environment:**
macOS, webpack, localhost:4200
* **Angular version:** 9.1.9
* **PrimeNG version:** 9.1.0
* **Browser:** [Chrome 83 | Firefox 76 | Safari 13.1 ]
* **Language:** [ TypeScript 3.8.3 | ES6/7 | ES5]
* **Node:** `node --version` = 6.14.5

**Comment by yigitfindikli** [comment]
Duplicate #8897

**Comment by birdcw** [comment]
I updated my primeng-galleria.js with the #8897 fix to check. I can confirm no more console errors👍 But still, the behavior described above persists, and is not related.
