### ISSUE TITLE
FileUpload as a ControlValueAccessor 

### ISSUE THREAD

**Issue by irbian** [primefaces/primeng#8913]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Expected behavior**
Hi! I was wondering if is planned to have FileUpload as a ControlValueAccesor. I mean:

- Bind to model
- Attach validation properties (errors, dirty, invalid)
- Blur, Change events

**What is the motivation / use case for changing the behavior?**
Better integration on complex forms

* **Angular version:**
 9.1.6

* **PrimeNG version:** 
9.1.0

**Comment by yigitfindikli** [comment]
Thanks for link @souhailharrati .

**Comment by irbian** [comment]
My point being: if angular is not going to provide it, maybe it´s a feature on the primeng hands?
