### ISSUE TITLE
ToggleButton bug: incorrect background color when not checked (value=false) PrimeNG 9.0.6-9.1.2

### ISSUE THREAD

**Issue by tanis138** [primefaces/primeng#8915]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Checked and unchecked ToggleButton has blue background color:
https://www.primefaces.org/primeng/showcase/#/togglebutton

**Expected behavior**
Unchecked ToggleButton should be gray:
https://www.primefaces.org/primeng/v8.2.5-lts/#/togglebutton

**Minimal reproduction of the problem with instructions**
Reproduced here:
https://www.primefaces.org/primeng/showcase/#/togglebutton
**Bug was introduced in PrimeNG 9.0.6**

* **Angular version:** 9.1.3

* **PrimeNG version:** 9.1.0

**ToggleButton v8-v9.0.5:**
![ToggleButton v8](https://user-images.githubusercontent.com/42606462/83751695-ee6e2d00-a66f-11ea-9434-a9461e66e4f2.jpg)

**ToggleButton v9.0.6-v9.1.0:**
![ToggleButton v9 1 0](https://user-images.githubusercontent.com/42606462/83751698-ef06c380-a66f-11ea-8bfb-266903864d0b.jpg)

**Comment by MaxiAringoli** [comment]
The same

**Comment by tanis138** [comment]
Still not working in PrimeNG 9.1.2:
https://www.primefaces.org/primeng/showcase/#/togglebutton
Button is blue in both states (checked and unchecked) By the way, on hover button colors are correct: blue when checked and gray when unchecked.
It is obviously a bug and I regret that it is ignored by developers.

**Comment by mikela** [comment]
I suspect this is very low prio for them (seeing there are 600+ open issues) but, until a PR fixes this, we can style the button manually:
CSS:
```
.toggle-button-patch {
  border: 1px solid #c8c8c8 !important;
  .ui-button-text.ui-unselectable-text {
    background-color: #c8c8c8;
    color: #333333;
  }
}
```
HTML:
`<p-toggleButton [styleClass]="isActive ? '' : 'toggle-button-patch'" ...
`

**Comment by yigitfindikli** [comment]
Fixed in https://github.com/primefaces/primeng/commit/2fb9cec91ca7fef80feda2cd0f485ca151fccbfa
