### ISSUE TITLE
9.1.0 InputNumber node_modules errors

### ISSUE THREAD

**Issue by thimma11** [primefaces/primeng#8916]
**I'm submitting a**
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

I have updated Primeng from 9.0.5 to 9.1.0. I can serve the application with _ng serve_, but as soon as I import the new **InputNumber** Component in app.module.ts I get the below node_module errors.

### Import
`import {InputNumberModule} from 'primeng/inputnumber';`

### Error output
`node_modules/primeng/dropdown/primeng-dropdown.d.ts.Dropdown.html(17,83): Expected 0 arguments, but got 1.
node_modules/primeng/table/primeng-table.d.ts.ScrollableView.html(18,63): This condition will always return 'true' since the types 'boolean' and 'string' have no overlap.
node_modules/primeng/table/primeng-table.d.ts.ScrollableView.html(27,75): This condition will always return 'true' since the types 'boolean' and 'string' have no overlap.
node_modules/primeng/treetable/primeng-treetable.d.ts.TTScrollableView.html(13,67): This condition will always return 'true' since the types 'boolean' and 'string' have no overlap.
node_modules/primeng/treetable/primeng-treetable.d.ts.TTScrollableView.html(14,66): Property 'tableStyle' does not exist on type 'TreeTable'.
node_modules/primeng/treetable/primeng-treetable.d.ts.TTScrollableView.html(14,37): Property 'tableStyleClass' does not exist on type 'TreeTable'.
node_modules/primeng/treetable/primeng-treetable.d.ts.TTScrollableView.html(22,75): This condition will always return 'true' since the types 'boolean' and 'string' have no overlap.
node_modules/primeng/treetable/primeng-treetable.d.ts.TTScrollableView.html(24,66): Property 'tableStyle' does not exist on type 'TreeTable'.
node_modules/primeng/treetable/primeng-treetable.d.ts.TTScrollableView.html(24,37): Property 'tableStyleClass' does not exist on type 'TreeTable'.
node_modules/primeng/inputnumber/primeng-inputnumber.d.ts.InputNumber.html(12,68): Expected 0 arguments, but got 1.
node_modules/primeng/inputnumber/primeng-inputnumber.d.ts.InputNumber.html(12,106): Expected 0 arguments, but got 1.
node_modules/primeng/inputnumber/primeng-inputnumber.d.ts.InputNumber.html(12,188): Expected 0 arguments, but got 1.
node_modules/primeng/inputnumber/primeng-inputnumber.d.ts.InputNumber.html(14,70): Expected 0 arguments, but got 1.
node_modules/primeng/inputnumber/primeng-inputnumber.d.ts.InputNumber.html(14,110): Expected 0 arguments, but got 1.
node_modules/primeng/inputnumber/primeng-inputnumber.d.ts.InputNumber.html(14,196): Expected 0 arguments, but got 1.
node_modules/primeng/inputnumber/primeng-inputnumber.d.ts.InputNumber.html(17,64): Expected 0 arguments, but got 1.
node_modules/primeng/inputnumber/primeng-inputnumber.d.ts.InputNumber.html(17,102): Expected 0 arguments, but got 1.
node_modules/primeng/inputnumber/primeng-inputnumber.d.ts.InputNumber.html(17,184): Expected 0 arguments, but got 1.
node_modules/primeng/inputnumber/primeng-inputnumber.d.ts.InputNumber.html(19,66): Expected 0 arguments, but got 1.
node_modules/primeng/inputnumber/primeng-inputnumber.d.ts.InputNumber.html(19,106): Expected 0 arguments, but got 1.
node_modules/primeng/inputnumber/primeng-inputnumber.d.ts.InputNumber.html(19,192): Expected 0 arguments, but got 1.
`

**Expected behavior**

Import InputNumberModule in app.module.ts and use it with p-inputnumber in template.

**Minimal reproduction of the problem with instructions**

Update primeng from version 9.0.5 to 9.1.0 and try to import InputNumberModule.

**Please tell us about your environment:**

* **Angular version:** 9.0.4

* **PrimeNG version:** 9.1.0

* **TypeScript version:** 3.7.5

* **Node (for AoT issues):** `node --version` =   v12.14.1

**Comment by davitnutsubidze** [comment]
I have the same problem, what should i do?
