### ISSUE TITLE
Negative sign with InputNumber

### ISSUE THREAD

**Issue by loicCQAM** [primefaces/primeng#8919]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/github-uobpvs

**Current behavior**
If you enter a negative sign (-) as the first character in the input, nothing happens.
The only way to set a negative sing, without using the keyboard arrows, is to :
- Enter a number
- Go at the beginning of the input
- Enter the negative sign

**Expected behavior**
You should be able to enter a negative sign to start a negative number.

**Minimal reproduction of the problem with instructions**
Use an InputNumber and try entering a negative number.

**What is the motivation / use case for changing the behavior?**
Would like to be able to enter a negative number

* **Angular version:** 9

* **PrimeNG version:** 9.0.1

* **Browser:** Chrome 83.0.4XXX
 
* **Language:** TypeScript

**Comment by zakharenkov** [comment]
Additionally:
If you go to the beginning and press the minus sign twice, then the value will be cleared.

**Comment by loicCQAM** [comment]
Still an issue

**Comment by zakharenkov** [comment]
> Thanks a lot for your feedbacks! Could you please test these issues on PrimeReact inputNumber?
> https://primefaces.org/primereact/showcase/#/inputnumber
> if it works fine for you, I can add new improvements to PrimeNg. This component is open to user experiences. Therefore, feedback is important to us.
> 
> Thanks again!
> Best Regards,

Still an issue: If you go to the beginning and press the minus sign twice, then the value will be cleared.

**Comment by mertsincan** [comment]
Thanks a lot for your feedbacks! 
@zakharenkov I'll check and get back to you.

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primeng/commit/1258ca4d4b7a15575fa950fc83af980f2107d3d5

Thanks a lot for the feedbacks,
Best Regards,
