### ISSUE TITLE
Possibility to do Client-side FileUpload

### ISSUE THREAD

**Issue by glubbert** [primefaces/primeng#892]
As far as I can tell the FileUpload component is meant to work with a backend. A basic client-side version would be great.

**Comment by cagataycivici** [comment]
What is the use case for it?

**Comment by glubbert** [comment]
Manipulating text/image files on the client side. 
For example, choosing an xml file, converting the contents to json and displaying the stringified object (Something I currently need to do).
Also uploading image files and using them with a 2d/3d context on a canvas, or just appending them to the page for one purpose or another. Stuff like that.
So just a regular html5 file input but with the cool things ng FileUpload does, listing/removing files, automatic dragndrop and such.

**Comment by mike-nyllabs** [comment]
Also using your own method with a file upload, for example using your own service to upload to amazon. I don't want to have to use a route to upload my files.

**Comment by islemus** [comment]
Also parsing a csv file to automatically fill up a form for instance

**Comment by cagataycivici** [comment]
We've added showUploadButton and showCancelButton, to do client side only, you need to set these two attributes to false and then use (onSelect) callback to implement client side only logic, so it would be just a nice rich file selector without upload.

@mike-nyllabs, your case is #3040
