### ISSUE TITLE
grid.css wrong syntax @@ -1,776 +0,0 @@

### ISSUE THREAD

**Issue by DebuggerAK** [primefaces/primeng#8920]
File:  src/app/components/grid/grid.css 

@@ -1,776 +0,0 @@  <--- What is that?
/* Deprecated Grid CSS */
.ui-grid {

...
"file": "../node_modules/primeng/resources/primeng.css",
  "line": 1983,
  "column": 2,
  "message": "Invalid CSS after \"}\": expected 1 selector or at-rule, was \"@@ -1,776 +0,0 @@\"",
...

Best regards!

**Comment by JanST123** [comment]
Please accept this pull request, the issue breaks our build pipeline :(

**Comment by DebuggerAK** [comment]
1+

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/issues/9161
