### ISSUE TITLE
Table scrollHeight="flex" messes columns' width

### ISSUE THREAD

**Issue by dmytro-gokun** [primefaces/primeng#8921]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-table-flex-column-width-issue

**Current behavior**
When resizing a table so that scroll bar appears or disappears, width of columns & corresponding column headers become misaligned.

**Expected behavior**
Width of columns & corresponding column headers should be equal.

Case 1 (initially the scrollbar is not visible):

![case-1](https://user-images.githubusercontent.com/580460/83885180-aa9e2500-a74e-11ea-8486-eae9412b79ad.gif)

Case 2 (initially the scrollbar is visible):

![case-2](https://user-images.githubusercontent.com/580460/83885268-c7d2f380-a74e-11ea-8d92-9eb18dfcaab2.gif)

**Comment by dmytro-gokun** [comment]
To be honest, this bug always existed (and i reported it). There was a known workaround: 
https://stackoverflow.com/a/54218853/7232025

But, unfortunatelly, it stopped working recently (I presume, after Angular 9). I've updated it (see "UPDATE (June 6th 2020)") so that it works again.

**Comment by projectX21** [comment]
I've fixed it in this way:

```
.ui-table-flex-scrollable .ui-table-scrollable-body,
.ui-table-flex-scrollable .ui-table-virtual-scrollable-body {
  flex: 1 1 0;
  overflow-y: scroll;
}

.ui-table-scrollable-header-box {
  padding-right: 17px !important;
}
```

The vertical scrollbar will however displayed all the time, but on the positive side there will no miss alignments any more

**Comment by mickeyjohn** [comment]
@projectX21 this .ui-table-scrollable-header-box {
  padding-right: 17px !important;
} will make the header box over right padded for 7px in FireFox. In my project I have 2 scroll-able flex height tables. One of them auto added with padding-right: 15px in Chrome and 10px in FireFox but the other always has padding-right: 0px. I think this must be all addressed within the code for p-table.

**Comment by projectX21** [comment]
hm, I think the 17px are quite ok, because they will be set automatically by primeng in an inital scrollable body, too. See this image: [https://ibb.co/tY48XLy](https://ibb.co/tY48XLy)
I don't understand why it doesn't work in your Firefox? If a run the example above and decrease the width, so that the table body is scrollable initially, everthing works fine in all of my browsers (chrome, firefox, IE).

**Comment by mickeyjohn** [comment]
I tested in with latest Chrome and FireFox in a Ubuntu 16.04 PC. May it is different with your environment. If I removed all the workaround css: .ui-table-flex-scrollable .ui-table-scrollable-body,
.ui-table-flex-scrollable .ui-table-virtual-scrollable-body {
  flex: 1 1 0;
  overflow-y: scroll;
}, It would work OK in Chrome only but Firefox.

**Comment by projectX21** [comment]
Do you have a screenshot for me how your scrollbar looks like? Now I've tested it in a debian VM (Firefox 60.4.0esr, Chrome Version 84.0.4147.105) and the scrollbar and the columns appear in the correct align. I want only to be sure that I havn't forgotten any use case for my solution in my project. Thank you very much!

**Comment by mickeyjohn** [comment]
@projectX21 Here are the screenshots
https://ibb.co/30xj0Jb: in Chrome version 84.0.4147.105 (Official Build) (64-bit)
https://ibb.co/NnRptVL: in FireFox version 78.0.2 (64-bit)
Be noticed that FireFox esr and normal FireFox might have some different behavior

**Comment by cagataycivici** [comment]
Part of https://github.com/primefaces/primeng/issues/9218

**Comment by matigarowel** [comment]
Below solve my issue using overflow-y: overlay

::ng-deep .p-datatable-scrollable-header-box {
  padding-right: unset !important;
}

::ng-deep .p-datatable-virtual-scrollable-body {
  overflow-y: overlay;
}
