### ISSUE TITLE
Add Scrollable in TabView

### ISSUE THREAD

**Issue by john182** [primefaces/primeng#8922]
**I'm submitting a ..
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Minimal reproduction of the problem with instructions**
Tabview Scrollable

![image](https://user-images.githubusercontent.com/10438644/83897127-8bda6700-a72b-11ea-9303-5b53bd9c6637.png)

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 9

* **PrimeNG version:** 9.1.0

* **Browser:**  Chrome 83 

 
* **Language:** TypeScript

**Comment by yigitfindikli** [comment]
duplicate https://github.com/primefaces/primeng/issues/1701
