### ISSUE TITLE
Disabled property doesn't work on p-button

### ISSUE THREAD

**Issue by lud42** [primefaces/primeng#8923]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/github-7ap5c9

**Current behavior**

I want to use the `disabled` property on  `<p-button>` but it doesn't work, only the css is set. I can click on it and my method is called.

**Expected behavior**

Normally I should not be able to click on my button, my method is not supposed to be called.

I'm using Primeng 8 with Angular 8

**Comment by JacobSiegle** [comment]
You have the wrong "click" for p-button it's supposed to be "onClick"

**Comment by lud42** [comment]
Oh yeah you're right @JacobSiegle, it works with the `onClick` property  but I don't think it's still normal.

It should work with `click` as well I think right? Or instead they can rename their output `onClick` by `click` like this there is no difference for us.

**Comment by yigitfindikli** [comment]
Hi @lud42,
You can use with pButton directive with click event.
