### ISSUE TITLE
Carousel is blurred for next pages

### ISSUE THREAD

**Issue by anton-nikitsiuk** [primefaces/primeng#8924]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Text is blurred

**Expected behavior**
Should be a clear(sharp) text presentation

**Minimal reproduction of the problem with instructions**
After the carousel was moved to the next item all items become blurred. Can be reproduced even on Demo
![image](https://user-images.githubusercontent.com/36010202/83969897-3cd33400-a8db-11ea-81d1-12b382f8ed51.png)
Here all text is well visible, but in the next one is blurred. It becomes a bigger problem is we have a lot of text under the tile.
![image](https://user-images.githubusercontent.com/36010202/83969907-49f02300-a8db-11ea-9776-5819e545007e.png)

**What is the motivation / use case for changing the behavior?**
Text is not well readable

* **Angular version:** 9.1.9

* **PrimeNG version:** 9.1.0

* **Browser:** At least Chrome Version 83.0.4103.97 (Official Build) (64-bit)

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =  v12.17.0.

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
