### ISSUE TITLE
p-inputNumber not intuitive handling of fraction digits/Currency input, not suitable for productive use

### ISSUE THREAD

**Issue by keschr** [primefaces/primeng#8926]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Just use the primeNG Showcase: https://www.primefaces.org/primeng/showcase/#/inputnumber

**Current behavior**
For example, if I want to enter the number 4.55, the following happens: After I press 4, it will automatically refill to 4.00. If I press "." "5" and "5" nothing happens. To enter 55 in the fraction, I have to mark the single digits with the mouse and then enter them with the keyboard. You can't expect a user to do something like that, the input should be possible in one stroke via the keyboard.

Also if i want to type the number 100, after pressing "1" the cursor jumps to the end of the number input, i can't type digits anymore. I need to set the right position of the cursor with the mouse, than i can continue. 

**Expected behavior**
It should be possible to type in numbers in one stroke, formating should just happen after editing finished or formating musst whatch for for the input of decimal seoarators and so on.

**Minimal reproduction of the problem with instructions**
just open the showcase https://www.primefaces.org/primeng/showcase/#/inputnumber and try to type some float numbers or try to use the currency input.

**What is the motivation / use case for changing the behavior?**
I was realy happy about this new component but at the moment it is not possible to use it in production

**Please tell us about your environment:**
Windows 10

* **Angular version:** 
Angular 9.1.9
* **PrimeNG version:** 
9.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
8900

**Comment by HiteshWork13** [comment]
any solution available ?
