### ISSUE TITLE
Dynamically check a checkbox in a Table with checkbox using P-Table

### ISSUE THREAD

**Issue by TheLastVector** [primefaces/primeng#8927]
Hi, 

I'm trying to create a table with checkboxes and wanted to dynamically disable or check a checkbox.

It was easy for me to disable a checkbox due to the TableCheckbox's input decorator. On the other hand, it isn't possible for me to check a checkBox in the same manner that I disabled it because there is no Input decorator for the value/attribute "checked".

Is it possible to add the @Input decorator for the value/attribute "checked" so it can be dynamically updated ?

If not, could you provide a way to dynamically check a checkbox inside a table (p-table) ?

P-Table : 
https://github.com/primefaces/primeng/blob/master/src/app/components/table/table.ts

TableCheckbox attributes : 
![image](https://user-images.githubusercontent.com/47110674/84050271-7fe4e400-a97b-11ea-82ee-010bf79c6b85.png)

**Comment by yigitfindikli** [comment]
You can use selection property for dynamically control.
`
<p-table [(selection)]="selection"...
`
