### ISSUE TITLE
Can't bind to 'pFocusTrapDisabled' since it isn't a known property of 'div'.

### ISSUE THREAD

**Issue by PHuhn** [primefaces/primeng#8928]
```
[X] bug report => Search github for a similar issue or PR before submitting
```

**Current behavior**

Running 9.0.2 PrimeNG and problem does not occur.
Installed latest version 9.1.0 of PrimeNG and now when running my Jasmine tests in the developer console it say may times the following warning message in yellow:
```
context.js:265 Can't bind to 'pFocusTrapDisabled' since it isn't a known property of 'div'.
```
I found the following indicating pFocusTrapDisabled was added in 9.0.3
[https://github.com/primefaces/primeng/issues/8678](url)

**Expected behavior**

I do not expect to get the above warning message.

**Minimal reproduction of the problem with instructions**

The project was originally written in Angular 4 and I have upgraded the project to each new version.

**Please tell us about your environment:**

```
Angular CLI: 9.1.0
Node: 12.15.0
OS: win32 x64

Angular: 9.1.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.7
@angular-devkit/build-optimizer   0.901.7
@angular-devkit/build-webpack     0.901.7
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@angular/cdk                      9.0.1
@angular/cli                      9.1.0
@ngtools/webpack                  9.1.7
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.42.1
```

* **Browser:** 

Chrome
 
* **Language:**

typescript                        3.7.5

* **Node (for AoT issues):**

Node: 12.15.0

**Comment by TheLastVector** [comment]
This error is pretty self explanatory. The "div" element does not possess a pFocusTrapDisabled property. There is a good chance your were trying to call this property from a PrimeNg component which "div" isn't a part of.

**Comment by yigitfindikli** [comment]
I couldn't replicate the error but probably you need to add FocusTrapModule to your imports.
