### ISSUE TITLE
Dialog - positionLeft and positionTop aren´t working anymore

### ISSUE THREAD

**Issue by ProfEibe** [primefaces/primeng#8929]
**I'm submitting a ...** 
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Since PrimeNG 9 the attributes positionLeft and positionTop from p-dialog aren´t recognized anymore. I can define position="left" for example but not the x and y coordinates of the dialog like before.

**Expected behavior**
Define left and top coordinate value of the dialog with positionLeft and positionTop

* **Angular version:** 9.1

* **PrimeNG version:** 9.1

* **Browser:** Chrome, Edge, Firefox
 
* **Language:** all

* **Node (for AoT issues):** `node --version` =  10.16.0

**Comment by yigitfindikli** [comment]
positionLeft and positionTop property is deprecated. You can use position property.

**Comment by ProfEibe** [comment]
Ah alright, I missed that,
than we should probably remove them from the doc and showcase.
#8930

**Comment by TheILPlace** [comment]
@yigitfindikli 
so how do you open the dialog in a specific location like before?
