### ISSUE TITLE
File Upload Chunking

### ISSUE THREAD

**Issue by JacobSiegle** [primefaces/primeng#8933]
The ability to chunk files that are being uploaded. This allows users to more easily upload large files.

Chunk size - How large of chunks we should transmit to the server.
Chunk retry attempts - If the chunk fails to upload how many times to retry it.

Some code for ref - 
https://www.dropzonejs.com/ (Doesn't work angular HTTP interceptor)
https://github.com/PauloPeres/ng2-chunk-file-upload (Missing some basic stuff like retry and out of date)

I understand I could add chunking in myself and only use the primeng file upload as UI with customUpload="true" and (uploadHandler)="myUploader($event)" but I think this is a pretty common requirement that no other file uploader currently fills perfectly.

Would you consider a PR or too large of a feature?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
