### ISSUE TITLE
DynamicDialog and Dialog Closed by clear button on drop down or chips inside

### ISSUE THREAD

**Issue by junyuan** [primefaces/primeng#8934]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/primeng-dynamicdialog-dropdown-issue

**Current behavior**
If there is a drop down with showClear=true inside opened dynamic dialog. click of clear buton on the drop down will close the dynamic dialog as well.

**Expected behavior**
This is not happen in previous 8. I have to set closeable=false on dyanmic dialog open parameters to prevent this. looks like the dynamic dialog catch the click event from the drop down clear button and treat it as the close button of dynamic dialog.

**Please tell us about your environment:**
Stakblitz

* **Angular version:** 9.0.4

* **PrimeNG version:** 9.1.0

* **Browser:** [Chrome 83]

 
* **Language:** [TypeScript 3.8.3]

* **Node (for AoT issues):** `node --version` =  v10.16.3

**Comment by junyuan** [comment]
This is not only happened on drop down inside. but also the chips. I have update the stackblitz sample to add a chips, the clear button on chips will close the dialog as well.

**Comment by ZVARKO** [comment]
@yigitfindikli there are more issues with dynamic dialog on version 9.1. Will this fix also work for these issues?
https://github.com/primefaces/primeng/issues/8784
https://github.com/primefaces/primeng/issues/8891

**Comment by yigitfindikli** [comment]
@ZVARKO Not for the #8891 but it fixed another commit.

**Comment by franciscoghansen** [comment]
The issue happens also with the calendar component with showButtonBar=true... When I click on the clear button of the calendar overlay, the dialog closes.

**Comment by Ravatsaas** [comment]
> The issue happens also with the calendar component with showButtonBar=true... When I click on the clear button of the calendar overlay, the dialog closes.

I think the fix for this issue will also address the calendar clear button. So should my workaround above.
