### ISSUE TITLE
TreeTable propagateSelectionUp and propagateSelectionDown input parameter request

### ISSUE THREAD

**Issue by gokhancelik** [primefaces/primeng#8935]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Available in component Tree but TreeTable does not have propagateSelectionDown and propagateSelectionUp.

**Expected behavior**
We need propagateSelectionDown and propagateSelectionUp inputs in TreeTable.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
We need these inputs to select only parent nodes.

**Please tell us about your environment:**

* **Angular version:** 5.X
9.1.4

* **PrimeNG version:** 5.X
9.0.6

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 3.8.3

* **Node (for AoT issues):** `node --version` =

**Comment by murarinayak** [comment]
Is this feature to be available anytime soon? 
We require to control the propagation behavior in a custom manner. 
Is it possible to not propagate the selection in any other way?

**Comment by DiegoSestito** [comment]
Since we don't have this functionality yet, what would be the recommended way to control parent selection independently of children?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
