### ISSUE TITLE
Ability to change dynamic dialog position

### ISSUE THREAD

**Issue by junyuan** [primefaces/primeng#8937]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[*] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/primeng-dynamicdialog-dropdown-issue

**Current behavior**
I've seen the dyanmicdialog layout changed from transform to flex to make the dialog display center of screen. This is better than transform which sometime make the dialog blurry when document height is an odd number. But the new layout lost the ability to change the dialog position like on top of screen. because there is no option for the dialog-mask element to change it's default style justify-content: center;

**Expected behavior**
Better have parameter on dyanmic dialog to change dialog-mask styles via class

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
Sometimes we want the small dialog place on top of the screen instead of center

**Please tell us about your environment:**
Stackblitz

* **Angular version:** 9.0

* **PrimeNG version:** 9.1.0

* **Browser:** [Chrome 83 ]
 
* **Language:** [TypeScript 3.8.3]

* **Node (for AoT issues):** `node --version` = v10.16.3

**Comment by in-vbonilla** [comment]
@junyuan as a workaround you can pass some styles to the configuration object, it worked for me, and could be of some help for others too.

`const ref = this.dialogService.open(CustomModalComponent, {
      dismissableMask: true,
      width: '50%',
      closable: true,
      style: { 
        'align-self': 'flex-start', 
        'margin-top': 'var(--spacing-xxl)' 
      }
    });`

**Comment by icedream2linxi** [comment]
@in-vbonilla Sticking to the top is done, but how to do it to the right?

**Comment by in-vbonilla** [comment]
Being a flex item, just add to the style:
```'margin-left': 'auto',
'margin-right': 'var(--spacing-xxl)' ```

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by hekmatshak** [comment]
Hello @mertsincan @cagataycivici @cetincakiroglu 
Can you provide us with a fix for this issue ASAP, please?

My application was using 'positionTop' property, and after migrating to the latest version I found that the property was deprecated without providing any alternative as mentioned https://github.com/primefaces/primeng/issues/9089

So adding the [maskStyle] input to the dialog could be a workaround to match the old behavior!
