### ISSUE TITLE
Unable to use virtual scroll with other combinations in p-tree

### ISSUE THREAD

**Issue by gs-smuthyam** [primefaces/primeng#8938]
Have a situation

That is where I need to use lazy load in combination with virtual scrolling. Tried with examples they doesn't seem to work. Any help on this is appreciated.

Reproduce steps add `[virtualScroll]="true" [virtualNodeHeight]="33" scrollHeight="200px"` to below example
https://stackblitz.com/edit/primeng-treelazy-demo?file=src%2Fapp%2Fapp.component.html

**Comment by brian428** [comment]
The workaround is to manually trigger `updateSerializedValue()` on the tree after the node is populated.

Demo: https://stackblitz.com/edit/primeng-treelazy-demo-d44qza?file=src%2Fapp%2Fapp.component.ts

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
