### ISSUE TITLE
Accessibility: Dialog close button needs aria- label

### ISSUE THREAD

**Issue by T-jain1995** [primefaces/primeng#8947]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

When tabbing through the paging controls with a screen reader, the dialog close button is not readout.

**Expected behavior**
The screen reader should speak (vi aria-label) when tabbed to each control i.e "Close button".
add aria-label to the button. Ex: aria-label = "close",

**Minimal reproduction of the problem with instructions**

<img width="750" alt="Capture" src="https://user-images.githubusercontent.com/22454085/84711033-081e4700-af83-11ea-8f76-d98437521015.PNG">

**What is the motivation / use case for changing the behavior?**
 This will be helpful by the specially-abled people. 

**Please tell us about your environment:**
Windows, NPM, Angular, VSCode

* **Angular version:**  - 9.1.9

* **PrimeNG version:** - 9.0.6

* **Browser:** [ chrome, edge]
 
* **Language:** [TypeScript - 3.8.3]

* **Node (for AoT issues):** `node --version` =

**Comment by XxOsirisxX77** [comment]
The commit that was done in here to close this issue, only adds aria-label to the approve / reject buttons, but not the close icon at the top right, which should be aria-labeled as well.
