### ISSUE TITLE
Datatable column header missing ui-state-active class after sort using custom sortFunction

### ISSUE THREAD

**Issue by hhubik** [primefaces/primeng#895]
This is with Beta 15. I have a table with a few sortable columns.  One of the columns uses a custom sort function. (sortable="custom").  When I sort a column that uses the built-in sorting, the column header is selected after the sort.  When I sort the custom sortable column, the header is not selected (highlighted) after the sort.  The column header seems to be missing the `ui-state-active` class.

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with them and if issue persists drop a comment and we'll reopen.
