### ISSUE TITLE
Why pTemplate="rowgroupfooter" does not work with rowGroupMode="rowspan" ?

### ISSUE THREAD

**Issue by whatneuron** [primefaces/primeng#8953]
Why pTemplate="rowgroupfooter" does not work with rowGroupMode="rowspan" ?

It works perfectly with rowGroupMode="subheader".

All I want to do is to add total row for a rowspan.

      <p-dataTable [value]="cars"  sortField="brand" rowGroupMode="rowspan" groupField="brand" >
        <p-column field="brand" header="Brand"></p-column>
        <p-column field="name" header="Name"></p-column>
        <ng-template pTemplate="rowgroupfooter" let-car>
          <td colspan="5" style="text-align: end;">Total Price: 10000000</td>
        </ng-template>
      </p-dataTable>

Problem is that it doesn't shows  "Total price" at all.

I am using PrimeNG 4.3.0 - https://www.primefaces.org/primeng-4.3.0/#/datatable/rowgroup

All I want is to add a total price to this example,

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/tdcZB.png

**Comment by whatneuron** [comment]
I think the problem is with pTemplate and rowgroupfooter doesn't work with subheader, I am not sure what is equvilent for rowspan

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.

**Comment by whatneuron** [comment]
> Please use forum for questions and help requests.

On forum they are not even approving my post let alone answering it..

The way you are treating people who use your product, just wait for time when no one uses it anymore ! and it won't be far !

**Comment by whatneuron** [comment]
I will let everyone know how bad your support is and not use primeng, it's a dead end.
