### ISSUE TITLE
Remove Add all/Remove all button from Picklist

### ISSUE THREAD

**Issue by NakkaVijayaKumar** [primefaces/primeng#8954]
HI Can some some help me to hide the Add/Remove all  buttons
![image](https://user-images.githubusercontent.com/65212327/84871753-8b808b00-b09e-11ea-9f44-6afcb306fb09.png)
my code
<p-pickList [source]="availablemetrics" [target]="mappaedmetrics" sourceHeader="Metrics Available"
                    targetHeader="Metrics Mapped" [responsive]="true" filterBy="DisplayMetricName" dragdrop="true"
                    sourceFilterPlaceholder="Search by Metric" targetFilterPlaceholder="Search by Metric"
                    [sourceStyle]="{'height':'300px','width':'400px','border':'groove'}" showCheckbox="true"
                    [targetStyle]="{'height':'300px','width':'400px','border':'groove'}" [showSourceControls]="false"
                    [showTargetControls]="false" class="ui-picklist" (onMoveToTarget)="addMetrics($event)"
                    (onMoveToSource)="removeMetrics($event)">
                    <ng-template let-metric pTemplate="item">
                      <div class="ui-helper-clearfix">
                        <div style="font-size:14px;float:left;margin:15px 5px 0 0">{{metric.DisplayMetricName}}</div>
                      </div>
                    </ng-template>
                  </p-pickList>
                  <div style="float: left;margin-left: 10px;">
                    <div style="height:130px;"></div>
                  </div>

And I have added in .ts page 
 styles: [`
      button[icon="pi pi-angle-double-right"],
      button[icon="pi pi-angle-double-left"] {
        display: none !important;
      }
  `]
and added in css

      .ui-picklist button[icon="pi-angle-double-left"] {
        display: none !important;
      }

      .ui-picklist.ui-button ui-button-icon-only ui-corner-all ui-state-default ui-widget button[icon="pi pi-angle-double-right"] {
        display: none !important;
      }

      button[icon="pi pi-angle-double-right"],
      button[icon="pi pi-angle-double-left"] {
        display: none !important;
      }

      .ui-picklist button[icon="fa-angle-double-left"] {
        display: none !important;
      }

      .ui-picklist button[icon="fa-angle-double-right"] {
        display: none !important;
      }

      .ui-picklist .ui-picklist-buttons {
        display: none !important;
      }

but still no solution. Can someone please help me on this?

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.

**Comment by NakkaVijayaKumar** [comment]
how can I use that?

**Comment by linhfpt** [comment]
button[icon="pi pi-angle-double-right"],
  button[icon="pi pi-angle-double-left"] {
    display: none !important;
  }
  add these things to style.scss or style.css, that's work for me

**Comment by Adailton-Lima** [comment]
tancks linhfpt =)

**Comment by pekora-tech** [comment]
The buttons in PrimeNG's PickList lack textual descriptions or tooltips, making them appear abstract and difficult for users to understand. This has resulted in frequent instances of users clicking the wrong buttons due to the lack of clear guidance. It would be beneficial to have an option to either remove these buttons or enhance them with more descriptive labels or tooltips.

**Comment by gehaktmolen** [comment]
¯\_(ツ)_/¯

```
styles: [
    `
      :host {
        ::ng-deep {
          div[data-pc-section="targetControls"],
          div[data-pc-section="sourceControls"],
          button[data-pc-section="moveAllToTargetButton"],
          button[data-pc-section="moveAllToSourceButton"] {
            display: none !important;
          }
        }
      }
    `,
  ],
```

**Comment by LedAzdak** [comment]
It baffles me after all this time, there is still no way to simply disable these addAll/RemooveAll buttons in a p-pickList.
You still have to make a css fix, like the previous response, and it angers me in a way you can't imagine.
