### ISSUE TITLE
How to clear the search text after selecting the value in multi select.

### ISSUE THREAD

**Issue by AbhijeetGiram** [primefaces/primeng#8958]
How to clear the search text after selecting the value and also to clear the text in search filed when closing the multi select dropdown after selecting value. 

Example:
`<p>Primeng multiselect Example ngModel 2</p>
        <p-multiSelect [options]="newCars" [(ngModel)]="selectedCars2" [filterPlaceHolder]="filterPlaceHolder"
            [filter]="true" filterBy="value" (onChange)="onChangeMultiSelect1($event)" 
            [inputId]="inputIdNew" (onPanelHide)="onPanelHide($event)" (onPanelShow)="onPanelShow($event)" [name]="nameInputNew">
            <ng-template let-value pTemplate="selectedItems">
                <span *ngFor="let val of value">{{val}} </span>
                <span *ngIf="!value || value.length === 0">Choose X</span>
            </ng-template>
            <ng-template let-hello pTemplate="item"><span>{{hello.value}}</span></ng-template>
        </p-multiSelect>
        <p>Selected Cars: {{selectedCars2}}</p>`

ng version: 9.0.1
primeng:  9.1.0
Need help.

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.
