### ISSUE TITLE
ContextMenu support for TabViewNavigation

### ISSUE THREAD

**Issue by ghaege** [primefaces/primeng#8959]
[ ] bug report => Search github for a similar issue or PR before submitting
[ x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Expected behavior**
Possibility to add a context menu to the TabViewNavigation.

**What is the motivation / use case for changing the behavior?**
Menuitem examples: 'close all', 'close all TabPanelTypes', ..

* **PrimeNG version:** 9.X

**Comment by davisb10** [comment]
+1

This would be a great feature to have on https://primefaces.org/primeng/showcase/#/tabview
That way you can do things like 'Close All', 'Close Others', ...

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
