### ISSUE TITLE
Filtered out multiselect items should be hidden using a specific CSS class instead of using a style

### ISSUE THREAD

**Issue by dsebastien** [primefaces/primeng#8960]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When a multiselect has filter="true" and we type some text, filtered out elements are hidden using a simple `display: none` style on the `<li>` of the corresponding `p-multiselectitem` elements.

In our app, we're customizing the styles and this behavior is problematic.

**Expected behavior**
Hiding elements could be done by adding/removing a specific CSS class, so that customizations are not broken.

**Please tell us about your environment:**

* **Angular version:** 9.1.1

* **PrimeNG version:** 9.1.0

**Comment by cagataycivici** [comment]
They are removed from the dom, not hidden with css with 10.0.0-rc.3.
