### ISSUE TITLE
Turbo Table: select all row except the first checkbox column

### ISSUE THREAD

**Issue by puyab** [primefaces/primeng#8969]
Hi all,

there is a way or a property that allows to select the row except the first column. In my case the first column is a checkbox column. The problem is that when I click on the row(in the other cells), it checked also the checkbox. And when I check on the checkbox it highlight all the row. Is there any way to separate this two behaviours. When I check the checkbox just make a check and when I click on the row doesn't check the checkbox?

`<ng-template pTemplate="body" let-rowData let-columns="columns" let-expanded="expanded" 
 let-rowIndex="rowIndex">`
`<tr *ngIf="config.checkboxes && config.singleSelectable" [pSelectableRow]="rowData"`
` [pSelectableRowIndex]="rowData.index" (click)="handler($event, rowData)">`
` <!-- checkbox column-->`
`<td class="dyn-table-column" style="width: 3em;">`
`<p-tableCheckbox #tableCheckbox [value]="rowData" `
`[disabled]="rowData.checkboxDisabled"`
`(click)="$event.stopPropagation()"></p-tableCheckbox>`
`</td>`
` <!-- others columns-->`
` <ng-template [ngTemplateOutlet]="blockBody"></ng-template>`
`</tr>`

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
