### ISSUE TITLE
Listbox width to abide by Grid Css

### ISSUE THREAD

**Issue by glubbert** [primefaces/primeng#897]
Listbox's width seems to be fixed and can only be changed through [style]. I think it would make sense if it were to work with grid classes.
![image](https://cloud.githubusercontent.com/assets/17081475/18507681/000e185c-7a7a-11e6-9b02-302dc9a6702d.png)
![image](https://cloud.githubusercontent.com/assets/17081475/18507845/b5d48040-7a7a-11e6-91e1-f625ca4c7bb8.png)

**Comment by cagataycivici** [comment]
You need to place them inside ui-g-*, if you add ui-fluid to outmost ui-g then listbox will be 100% so will work well within grids.
