### ISSUE TITLE
Add AccessKey property to MenuItem Api - New Feature Request

### ISSUE THREAD

**Issue by TasneemGhorayeb** [primefaces/primeng#8970]
It is not currently possible to add an access key value to the menu item interface like this.
label: 'Edit',
          ```
  icon: 'pi pi-fw pi-save',
            command: (event) => {
            },
            **accesskey: 'XXX'**
```
Then in the html of the Menu Items we could just bind to that value, be that context menu, menu bar, etc...

I believe this is a small change for a relatively important feature.

Thank you.
Tasneem Ghorayeb

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
