### ISSUE TITLE
Feature request: a footer template for autocomplete results list

### ISSUE THREAD

**Issue by cghislai** [primefaces/primeng#8971]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

I think it might be a nice addition to be able to add custom p-header/p-footer template to the autocomplete element, besides the existing pTemplate="item".

My use case was to display a 'Create new'  link below the result list, but there are others: displaying some context information to understand the result list, presenting information like 'x out of y records match your search', headers when items are presented as columns, etc.

**Comment by LukeHartcher** [comment]
Create New is my exact use case also!

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
