### ISSUE TITLE
Tooltips not dismissed on mouse out

### ISSUE THREAD

**Issue by pete-otaqui** [primefaces/primeng#898]
From the showcase page here:

http://www.primefaces.org/primeng/#/tooltip

Using Safari 9.1.3

The tooltips are not dismissed when one mouses-out of the four first inputs.  They are cumulatively created on every mouseover (visible since the shadow gets darker and darker).

![screen shot 2016-09-14 at 15 44 21](https://cloud.githubusercontent.com/assets/132719/18516815/3cf65046-7a92-11e6-8c82-e9c0ca931d1c.png)

(Note the very hard shadow on the second input, which has been moused-over repeatedly)

**Comment by pete-otaqui** [comment]
There is also an exception being thrown,

![screen shot 2016-09-14 at 15 47 28](https://cloud.githubusercontent.com/assets/132719/18516924/9fd8957a-7a92-11e6-851b-27309344faea.png)

**Comment by cagataycivici** [comment]
Unable to replicate with RC4.
