### ISSUE TITLE
(onFilter) Event not triggered in p-tree (primeNg)

### ISSUE THREAD

**Issue by NadeshNR** [primefaces/primeng#8980]
Angular version: 8.X
PrimeNG version: 8.X

Code Snippet : 
    <p-tree [value]="filterHelper.filterGroups[moduleName][type].file" selectionMode="checkbox"
        [(selection)]="filterHelper.filterGroups[moduleName][type].selected" [propagateSelectionUp]="true"
        [propagateSelectionDown]="true" [filter]="true" (onNodeSelect)="nodeSelect($event)"
        (onNodeUnselect)="nodeUnSelect($event)" (onFilter)="filterResults($event)">
        <ng-template let-node pTemplate="default">
            <div [title]="node.label" class="filterLabel">{{ node.label }}</div>
        </ng-template>
    </p-tree>

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
