### ISSUE TITLE
Add Del key support to InputNumber

### ISSUE THREAD

**Issue by dongenar** [primefaces/primeng#8981]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
When updating a value in an inputnumber field by only using the delete key, then the display value is updated but the formvalue is not, also display of grouping characters is not updated 

**Expected behavior**
when using the delete key the value should be updated just like when using the backspace

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 9.1.9

* **PrimeNG version:** 9.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome, FireFox
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by ikanters** [comment]
This issue can be reproduced on the [primeng showcase inputNumber](https://www.primefaces.org/primeng/showcase/#/inputnumber). Change the field "Integer Only" on windows by selecting te **7** from the **42,723** and hit the delete button (NOT backspace) the value is changed in **42,23**.  The expected value woud be **4,223** (which is the result if you hit the backspace).

**Comment by ikanters** [comment]
Yes! It works good on PrimeReact. Would be great if this could be applied on primeNG!

Thanks,
Ivar

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primeng/commit/1258ca4d4b7a15575fa950fc83af980f2107d3d5

Thanks a lot for the feedbacks,
Best Regards,
