### ISSUE TITLE
AutoComplete with Object ngModel remains as a string if input is cleared and no value is selected

### ISSUE THREAD

**Issue by franciscoghansen** [primefaces/primeng#8982]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/github-jqw2py

**Current behavior**
After clearing the input of a p-autoComplete where the ngModel is a Object without selecting a value, the ngModel turns into an empty string, instead of going back to undefined.

**Expected behavior**
ngModel becomes undefined after clearing the input

**Minimal reproduction of the problem with instructions**
Usage of the autocomplete as described in the documentation of the showcase

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows 10
VSCode
npm

* **Angular version:** 9.1.8

* **PrimeNG version:** 9.1.0

* **Browser:** Tested in chrome only

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
