### ISSUE TITLE
inputnumber : "maxlength" property doesn't work 

### ISSUE THREAD

**Issue by priyanhsu10** [primefaces/primeng#8983]
ngular version: 9.1.1
PrimeNG version: 9.1.0

Code Snippet :
 <p-inputNumber  [(ngModel)]="inputValue"  [maxlength]="maxlength" 
    [formControl]="decimalControl" #inputcontrol [disabled]="isDisabled" ></p-inputNumber>

currenntly managening by min max range calculation but it not the correct way to handle the length of input control

**Comment by LeonardoHenriqueOliveira** [comment]
i have the same problem. My input with maxlength is not functioning

**Comment by andreyshedko** [comment]
Do you understand that `maxlength` is not a valid input property for numeric input?
