### ISSUE TITLE
inputnumber : not able to type "."(dot) or comma"with"(respective locale) for decimal point. Need to move the cursor manually to enter digit after decimal point

### ISSUE THREAD

**Issue by priyanhsu10** [primefaces/primeng#8985]
ngular version: 9.1.1
PrimeNG version: 9.1.0

snapshot
![image](https://user-images.githubusercontent.com/63138939/85938693-242fca00-b92d-11ea-98d9-e2e690f82ad2.png)

User is getting frustrated due to to this.

**Comment by franciscoghansen** [comment]
Got the same issue with v9.1.0 and Angular 9.1.8... Also happens with the components on the showcase page of the inputNumber

**Comment by Celebes** [comment]
OMG this is so infuriating. Another problem is that for example in showcase page when you select whole "Currency -> United Stateas" value and input something it puts "$1,00" and cursor moves to the end of input and you are unable to write... ok I am switching to ngx-mask for now.

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primeng/commit/1258ca4d4b7a15575fa950fc83af980f2107d3d5

Similar issue; https://github.com/primefaces/primeng/issues/8900

Thanks a lot for the feedbacks,
Best Regards,

**Comment by JordanMunroe** [comment]
This still seems to be an issue.

I'm using version 11.3.1 and if I try to type a decimal in an input, it doesn't allow me to type the decimal separator.
The workaround I've found is setting minFractionDigits to 1 but you'd expect an input in decimal mode to allow you to actually type decimals into it regardless of the minimum fraction digits.

Example code: 
`<p-inputNumber mode="decimal" max="100" [step]="2.5" suffix="%">`

**Comment by MigeruDev** [comment]
Hi everyone, 

I am working on version 17.12.0, and it did not let me use decimal punctuation marks even though I selected the decimal mode. As Greg said, the problem lies in how to input min and max are treated when entering a decimal number. Since I don't want to force my user always to enter decimal numbers I have found this way to enable the decimal '.' using [minFractionDigits] and [maxFractionDigits].

`<p-inputNumber 
                                        class="text-center"
                                        formControlName="weighting"
                                        mode="decimal"
                                        [size]="7"
                                        [maxlength]="6"
                                        [step]="0.1"
                                        inputId="weighting"
                                        [minFractionDigits]="0"
                                        [maxFractionDigits]="3"
                                        [min]="0.00"
                                        [max]="100.00" />`
                                        
It could be useful to someone, or I'm giving it a lot of thought and it seems easier than it is. Regards!
