### ISSUE TITLE
Flex table in Firefox scroll on p-table container instead of ui-table-scrollable-body 

### ISSUE THREAD

**Issue by shyallegro** [primefaces/primeng#8986]
this line https://github.com/primefaces/primeng/blob/e327e8408dd9b133d6a87d909cf3f84f20892d5b/src/app/components/table/table.css#L92 should change to
`flex: 1 1 0`

**Comment by mickeyjohn** [comment]
Thanks @shyallegro.
Doing this make p-table flexscroll works both in Firefox and Chrome on dynamic divs and also a temporarily fix for #8921.
```
.ui-table-flex-scrollable .ui-table-scrollable-body,
.ui-table-flex-scrollable .ui-table-virtual-scrollable-body {
    flex: 1 1 0;
}
```
PrimeNg: 9.1.2
Angular: 9.1.11.

**Comment by shyallegro** [comment]
You have a great product, happy that I could help

**Comment by projectX21** [comment]
@mickeyjohn:
I don't think that #8921 is fixed with this css adjustment? 
I had forked the example from #8921 and added the css part, but the misalignment still exists:
https://stackblitz.com/edit/primeng-table-flex-column-width-issue-euc7rg?embed=1&file=src/styles.css

**Comment by projectX21** [comment]
In v10 the css class names have changed:
```
.p-datatable-flex-scrollable .p-datatable-scrollable-body,
.p-datatable-flex-scrollable .p-datatable-virtual-scrollable-body {
    flex: 1 1 0 !important;
}

```

And now it seems that the !important is needed, too.

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.1.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
