### ISSUE TITLE
p-panel [showHeader]=false removes content top border

### ISSUE THREAD

**Issue by nicohell** [primefaces/primeng#8987]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**

When showHeader property is set to false, the content top border is not displayed because of CSS property : 
body .ui-panel .ui-panel-content -> border-top: 0 none.

**Expected behavior**

Display all content's border when header not displayed.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 9.X

* **PrimeNG version:** 9.X

* **Browser:** all

 
* **Language:** TypeScript 3.8.3

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by danilofd** [comment]
Still with the problem reported.
