### ISSUE TITLE
9.1.0 - Table not restoring footer column widths

### ISSUE THREAD

**Issue by eronyck** [primefaces/primeng#8988]
**Current behavior**
The column widths are not set for footer in Table.restoreColumnWidths, but only for header and body.
When resizing a column, the footer cell is resized properly.

**Expected behavior**
The column widths should also be set for footer in restoreColumnWidths.

* **PrimeNG version:** 9.1.0

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
