### ISSUE TITLE
Ensure text remains visible during webfont load

### ISSUE THREAD

**Issue by joris-calvat** [primefaces/primeng#8989]
Hi, We are currently testing performances with lighthouse tool.
It appears that the loaded webfonts shoud use the font-display property set to 'swap' value.

@font-face {
  **font-display: swap;**
  font-family: "Open Sans";
  font-style: normal;
  font-weight: 700;
  src: url("./fonts/open-sans-v15-latin-700.eot");
  /* IE9 Compat Modes */
  src: local("Open Sans Bold"), local("OpenSans-Bold"), url("./fonts/open-sans-v15-latin-700.eot?#iefix") format("embedded-opentype"), url("./fonts/open-sans-v15-latin-700.woff2") format("woff2"), url("./fonts/open-sans-v15-latin-700.woff") format("woff"), url("./fonts/open-sans-v15-latin-700.ttf") format("truetype"), url("./fonts/open-sans-v15-latin-700.svg#OpenSans") format("svg");
  /* Legacy iOS */
}

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
