### ISSUE TITLE
Deprecated keyCode used when checking for pressed key

### ISSUE THREAD

**Issue by RepentAndBelieveTheGospel** [primefaces/primeng#8995]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

We are using the TreeTable component with ttEditableColumn and the onEditComplete event. While writing test cases for the update method bound to the onEditComplete event, we decided to follow with the normal user behaviour, instead of just feeding the update method the test data. I simulated a click on the td cell which has the ttEditableColumn directive, changed the value of the input and then tried to simulate an Enter keypress to complete the editing process.

Initially I couldn't get the onEditComplete event triggered and it seemed like the KeyboardEvent wasn't working. I looked through the TreeTable code and found this method:

**node_modules/primeng/esm2015/treetable/treetable.js**
```
onKeyDown(event) {
        if (this.isEnabled()) {
            //enter
            if (event.keyCode == 13) {
                if (this.tt.isEditingCellValid()) {
                    DomHandler.removeClass(this.tt.editingCell, 'ui-editing-cell');
                    this.closeEditingCell();
                    this.tt.onEditComplete.emit({ field: this.field, data: this.data });
                }
                event.preventDefault();
            }
...
```
As you can see, it checks for the value of the keyCode property on the event. Unfortunately, since keyCode is deprecated, I can't add this property to the KeyboardEvent, because the KeyboardEventInit interface used in the constructor doesn't have it defined:

**node_modules/typescript/lib/lib.dom.d.ts**
```
declare var KeyboardEvent: {
    prototype: KeyboardEvent;
    new(type: string, eventInitDict?: KeyboardEventInit): KeyboardEvent;
    readonly DOM_KEY_LOCATION_LEFT: number;
    readonly DOM_KEY_LOCATION_NUMPAD: number;
    readonly DOM_KEY_LOCATION_RIGHT: number;
    readonly DOM_KEY_LOCATION_STANDARD: number;
};

interface KeyboardEventInit extends EventModifierInit {
    code?: string;
    isComposing?: boolean;
    key?: string;
    location?: number;
    repeat?: boolean;
}
```

I have to use @ts-ignore in order to add the deprecated keyCode when creating a new KeyboardEvent:

```
const keyboardEvent = new KeyboardEvent('keydown', {
            cancelable: true,
            composed: true,
            bubbles: true,
            code: 'Enter',
            key: 'Enter',
            // @ts-ignore
            keyCode: 13
        });
```

Please consider replacing the conditions in all places were the keyCode property is used to check for the pressed key. Use something else, like code or key.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
