### ISSUE TITLE
p-dynamicdialog will not take 100% screen height

### ISSUE THREAD

**Issue by mickeyjohn** [primefaces/primeng#8998]
**I'm submitting a 

[x] bug report 

https://stackblitz.com/edit/github-v7agfm-1cxwqb

**Current behavior**
p-dynamicdialog does not take 100% screen height but only 90%.

**Expected behavior**
p-dynamicdialog should take 100% screen height when set in the properties according to the documentation.

```
this.dialogService.open(FullFormComponent, {        
      header: "Full Form",      
      width: '100vh',    // or   width: '100%',
      height: '100vh',  // or    height: '100%',
      closable: true
});
```

with the inspection, you will find It was set by the child .ui-dialog with max-height: 90% 

* **Angular version:** 9.1.X

* **PrimeNG version:** 9.1.0

* **Browser:** [all]

**Comment by mickeyjohn** [comment]
A workaround is to:
```
body .ui-dynamicdialog {
    max-height: 100%; // or unset  
}
```
I am not sure whether this is a good workaround.

**Comment by DwieDima** [comment]
I have the same issue

It seems that the property `max-height` from the class `p-dialog` won't change, so it stays on 90% height.

```

.p-dialog {
    display: flex;
    flex-direction: column;
    pointer-events: auto;
    max-height: 90%;
    transform: scale(1);
    position: relative;
}
```

Also the property `modal=true` for dialogService wont be applied (no darker backdrop and backdrop content is clickable behind modal).

My workaround is to set max-height to unset

```
::ng-deep {
  .p-dialog {
    max-height: unset;
  }
```
