### ISSUE TITLE
p-picklist drag and drop error "l.target.blur is not a function at s.onDragStart"

### ISSUE THREAD

**Issue by mickeyjohn** [primefaces/primeng#9000]
[x ] bug report => Searched github for a similar issue or PR before submitting

I could create a stackbitz but it does happening consitently on the showcase page:
https://www.primefaces.org/primeng/showcase/#/picklist

**Current behavior**
Drag and drop on items from each list to the others works most of the time. 

With special case like: drag to select text on a source list header then continue dragging the mouse to an item; release the mouse then click on that item then try to drag then drop on the target list. The error will emit. I knows this has been mentioned in #7530 but may be it is not clear on how to reproduce the error.

Here is the shared video: https://www.dropbox.com/s/9mbcdjuqcspasmz/p-picklist_drag_n_drop_error.wmv?dl=0

**Expected behavior**
It should not emits the errors and work normally.

**What is the motivation / use case for changing the behavior?**
Sometimes, the user might drag from outside then drag an item on the source list then drag to the target list.

* **Angular version:** 9.1.X

* **PrimeNG version:** 9.1.2

* **Browser:** Chrome, FireFox

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
