### ISSUE TITLE
p-Dropdown not displaying number 0 or boolean false (zero)

### ISSUE THREAD

**Issue by WZSE** [primefaces/primeng#9001]
**I'm submitting a 
[x] bug report => Search github for a similar issue or PR before submitting

Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/primeng-dropdown-demo-u4izbz?embed=1

**Current behavior**
0 or false is not displayed in the dropdown if they set in their type.

**Expected behavior**
It should display the actual value or provide a way to avoid falsely conversion.

* **Angular version:** 9.x & 8.x

* **PrimeNG version:** 9.x & 8.x

* **Browser:** 
Chromium 83

**Comment by cetincakiroglu** [comment]
Hi,

If the issue still exists with the latest PrimeNG version, please provide a StackBlitz example by using [PrimeNG Issue Template ](https://stackblitz.com/github/primefaces/primeng-issue-template) and re-open the issue.

Regards

**Comment by kishoresahas** [comment]
The issue still persists.
https://stackblitz.com/edit/github-2wf6do?file=src/app/app.component.html
