### ISSUE TITLE
{first} in currentPageReportTemplate always resolves to "1" even when no rows match

### ISSUE THREAD

**Issue by amithkk** [primefaces/primeng#9002]
**I'm submitting a ...** 
```
[x] bug report 
```

**Plunkr Case (Bug Reports)**

Official Stackblitz for table component:
https://stackblitz.com/edit/primeng-tabledoc-demo

**Current behavior**
When there are no records loaded/no records matched on filtering, when using a template like "Showing {first} to {last} of {totalRecords} entries", {first} resolves to 1, leading to a rendered string "Showing 1 to 0 of 0 entries" which isn't technically correct

![current behaviour](https://user-images.githubusercontent.com/1029727/86438335-f7f8bc80-bd23-11ea-92da-b2d0a4b7e3a4.png)

**Expected behavior**

When no suitable records are loaded, {first} resolves to 0 instead of 1, leading to the string "Showing 0 to 0 of 0 entries" which is accurate

Currently, a workaround to achieve this is to instead use your own template for the page report by using the paginatorright ng-template

**Minimal reproduction of the problem with instructions**

1. Open the table-demo stackblitz: https://primeng-tabledoc-demo.stackblitz.io/
2. Filter with a term that does not exist in the table

**What is the motivation / use case for changing the behavior?**
When there are no suitable records loaded into the table body, "0 to 0 of 0 records" is technically accurate

* **Angular version:** 9.1.X

* **PrimeNG version:**  9.1.0

* **Browser:** all
 
* **Language:** all

**Comment by pookdeveloper** [comment]
There's an other error, only replace the variables: {currentPage},{totalPages}

![image](https://user-images.githubusercontent.com/3384734/86585190-5fae4200-bf86-11ea-90cc-ac1bc39bc299.png)

Thanks!

**Comment by meta-vinod-sahu** [comment]
how to resolve this issue currently??

**Comment by tj-boyle** [comment]
This is an issue for our team as well.

**Comment by magemi** [comment]
I created #9729 which should resolve this issue.

In the meantime, one workaround I was able to get to work is to use a `ViewChild` decorator and then manually manipulate the table's `currentPageReportTable` string in `ngAfterViewInit()`:

```html
<p-table #table currentPageReportTemplate="Showing {first} to {last} of {totalRecords} entries"></p-table>
```

```typescript
export class TableComponent {
  @ViewChild("table") table: Table

  ngAfterViewInit(): void {
    if (this.table.totalRecords === 0) {
      this.table.currentPageReportTemplate = this.table.currentPageReportTemplate.replace("{first}", "0")
    }
  }
}
```

**Comment by meta-vinod-sahu** [comment]
> ```ts
> ngAfterViewInit
> ```

according to your code suggestion this issue has not been resolved..when table has one row.According to your code it's showing 0 out of 1 of total record..in short your code has failed

**Comment by meta-vinod-sahu** [comment]
issue not resolved according to your code suggestion..please give me
another way
*Thanks & Regards*
*Vinod Kr. Sahu*
*Software Engineer*

Meta*cube** Software Pvt. Ltd.*
SP-6, Phase IV, EPIP Sitapura, Jaipur, Rajasthan
Mobile: +91-
*9001857136*

**Comment by anuragsadhu** [comment]
1) import - import { ChangeDetectorRef } from '@angular/core';
2) update constructor - constructor(private cdRef: ChangeDetectorRef)
2) use below code - 

  ngAfterViewChecked() {
    if (this.table._totalRecords === 0) {
      this.table.currentPageReportTemplate = this.table.currentPageReportTemplate.replace("{first}", "0")
    } else {
      this.table.currentPageReportTemplate = this.table.currentPageReportTemplate.replace("0", "{first}")
    }
    this.cdRef.detectChanges();
  }

**Comment by meta-vinod-sahu** [comment]
Ok, I will check.
*Thanks & Regards*
*Vinod Kr. Sahu*
*Software Engineer*

Meta*cube** Software Pvt. Ltd.*
SP-6, Phase IV, EPIP Sitapura, Jaipur, Rajasthan
Mobile: +91-
*9001857136*

**Comment by naveenjr7** [comment]
> 1. import - import { ChangeDetectorRef } from '@angular/core';
> 2. update constructor - constructor(private cdRef: ChangeDetectorRef)
> 3. use below code -
> 
> ngAfterViewChecked() {
> if (this.table._totalRecords === 0) {
> this.table.currentPageReportTemplate = this.table.currentPageReportTemplate.replace("{first}", "0")
> } else {
> this.table.currentPageReportTemplate = this.table.currentPageReportTemplate.replace("0", "{first}")
> }
> this.cdRef.detectChanges();
> }

Do I need to replace this.table with my this.mytableData one.  If yes, then I'm getting  currentPageReportTemplate is undefined.
