### ISSUE TITLE
Resize columns and reorder rows not working together with virtual scroll(without lazy load)

### ISSUE THREAD

**Issue by SaranshBogati1997** [primefaces/primeng#9003]
[x] bug report 
[ ] feature request 
[ ] support request 
`

Primeng table is not supporting reorder of rows and also column resize . Below is the link for the stackblitz demonstrating the 
issue .
https://stackblitz.com/github/SaranshBogati1997/Primeng-issue

**Current behavior**
-when resizing only the column header gets resized and not the whole column.
-when reordering rows the rows are not reordered

**Expected behavior**
column should be resized  and rows should be able to be reordered as in the case when virtual scroll is disabled 

**Minimal reproduction of the problem with instructions**
Add in virtual scroll to the table containing reorder and resize enabled and the bug appears.

**Please tell us about your environment:**
Windows 10 
* **Angular version:** 9.X

* **PrimeNG version:** 9.X

Browser
Chrome 83

**Comment by pav0999** [comment]
#8885 seems like here can be a solution for resizing

**Comment by SaranshBogati1997** [comment]
> #8885 seems like here can be a solution for resizing

Thank you. This fixes the resize issue however the row reorder still doesn't work. I think the row index in case of virtual scroll is not changing on drag drop

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
