### ISSUE TITLE
Loading spinner is not displayed on p-table

### ISSUE THREAD

**Issue by shridharSynerzip** [primefaces/primeng#9005]
`<p-table #dataTable (onLazyLoad)="getRecords($event)" [value]="primengTableHelper.records"
                                rows="{{primengTableHelper.defaultRecordsCountPerPage}}" [paginator]="false"
                                [loading]="primengTableHelper.isLoading" [lazy]="true"
                                [responsive]="primengTableHelper.isResponsive">`

I used above primeng table and try to show loading spinner on table, but with above HTML code table is been disabled until my api is called or value of "primengTableHelper.isLoading" is true, so at same time I want to show the spinning wheel on the same table.
Please help.

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
