### ISSUE TITLE
After Update to Angular 9 error

### ISSUE THREAD

**Issue by profeciak** [primefaces/primeng#9006]
After I've updated Angular version to 9. I've got a problem with the GrowlModule. it's not in the primeng/primeng folder any more. Neither is in primeng/api. Where should I look for it, so I could import it properly again? I have version 9.1.2 of primeng

**Comment by yigitfindikli** [comment]
Growl is deprecated you can use toast instead of growl. And primeng/primeng path is removed you can use like this;
`primeng/toast`. Please use forum help requests and questions.

**Comment by sridhar7601** [comment]
So when I updated the toast but I'm not sure if this code is working or do I have to change this 
someone help me out 

Html
<p-toast [severity]="alertMsg.severity" [summary]="alertMsg.summary" [detail]="alertMsg.detail" [life]="3000">
</p-toast>

.ts
 showToast(severity: string, summary: string, detail: string) {

        this.messageService.add({ severity, summary, detail });

        this.alertMsg = [];

        this.alertMsg.push({ severity, summary, detail });

      }
