### ISSUE TITLE
Virtual Scroll with Row Expand Error

### ISSUE THREAD

**Issue by ninjavis** [primefaces/primeng#9008]
[x] bug report => Search github for a similar issue or PR before submitting

**Stackblitz Example Case (Bug Reports)**
https://aonirnbpm.github.stackblitz.io/

**Current behavior**
When creating a duplicate of the Virtual Scroll with Lazy Loading example here: https://www.primefaces.org/primeng/showcase/#/table/virtualscroll

as soon as I add the [pRowToggler]="rowData" button and <ng-template pTemplate="rowexpansion" let-rowData let-columns="columns"> section from your example here:
https://www.primefaces.org/primeng/showcase/#/table/rowexpansion

**Dev Console reports this error:** 
ERROR TypeError: Cannot read property 'vin' of undefined

**Browser reports this error:**
Error in /turbo_modules/primeng@9.1.0/bundles/primeng-table.umd.js (2209:48)
Cannot read property 'getDataLength' of undefined

If I replace <p-table [value]="virtualCars" 
with <p-table [value]="cars" 
the row expansion works as expected, but of course, there is then immediately 10000 cars in the table, which defeats the purpose of lazy loading. However, I can't seem to make it work on stackblitz, the "Cannot read property 'vin' of undefined" error remains.

**Expected behavior**
Row expansion should work with VIrtual scroll and lazy loading.

**What is the motivation / use case for changing the behavior?**
To be able to use row expansion with virtual scroll and lazy loading

**Please tell us about your environment:**
Windows 10, VSCode

* **Angular version:** 
9.1.9

* **PrimeNG version:** 
9.1.0

* **Browser:**
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 3.8.3

* **Node (for AoT issues):** `node --version` =  12.6.0

**Comment by cagataycivici** [comment]
Row expand + Virtual scroll is not a supported combination I'm afraid.
