### ISSUE TITLE
Icons are only showing outlines? 

### ISSUE THREAD

**Issue by ISimplifyComplexity** [primefaces/primeng#9009]
The icons currently look different to your documentation. 

for example https://www.primefaces.org/primeng/showcase/#/icons states that the folder open icon should look like this: 
![image](https://user-images.githubusercontent.com/4026553/86570246-e9064a00-bf6f-11ea-9bbd-1a5f88d8f222.png)

however when looking at the treeview docs on your site and clicking the stackblitz example here: https://stackblitz.com/edit/primeng-tree-demo

it looks like this: 

![image](https://user-images.githubusercontent.com/4026553/86570350-1521cb00-bf70-11ea-9d0e-7a2502af3c1a.png)

**Comment by yigitfindikli** [comment]
Hi @ISimplifyComplexity,

Stackblitz samples using PrimeIcons v4. PrimeIcons will be available with PrimeNG v10.
