### ISSUE TITLE
New ConfirmDialog Component

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#901]
Subset of Dialog to make it easier to create a confirm dialog with backed by a confirm service for reuse so could be fired from any action.

**Comment by KumarGovindh** [comment]
I want some more functionality in dialog like button label text because I have more confirmation dialog in a a single template.
I want to pass the button labels text, like message header and icon from confirm() function.
Is this confirmDialog module support that functionality? If yes, what could be the right format of the code structure.

**Comment by ebosantos** [comment]
What I think could fit nicely is allow html messages.

Instead of

`<span class=\"ui-confirmdialog-message\">{{message}}</span>`

We do

<span class=\"ui-confirmdialog-message\" [innerHTML]="message"></span>

What do you think, @cagataycivici ?

**Comment by igogu** [comment]
@KumarGovindh Did you find how to customize acceptLabel and rejectLabel?

**Comment by igogu** [comment]
Hi again, 

I found how to do it, you just have to defined in you p-confirmDialog acceptLabel=""; for example:

`<p-confirmDialog id="popupBorrar" header="Confirmation" width="425" acceptLabel="Add" #cd>`

**Comment by barocsi** [comment]
Why cant we simply pass the confirmdialog template to the service?
Why cant we define multiple confirmdialogs per page identified by #id or something like that so we can target it with the .confirm() function?
What the hell?

**Comment by ebosantos** [comment]
@barocsi Take a look at p-dialog.

**Comment by barocsi** [comment]
Thanks, but this is not the way it should work. Why would I pollute my static dom with dialogs instead of having generic templates that I can display dynamically? It smells like an anti-pattern.

**Comment by sajalsuraj** [comment]
Has anyone found the proper solution ?

**Comment by pierfreeman** [comment]
Any news about this feature? Should we open an issue for creating more confirmDialog on the same page?

**Comment by cristianVergaraSepulveda** [comment]
the solution for my is  appendTo="body"

 <p-confirmDialog header="Confirmation" icon="fa fa-question-circle" width="425"  appendTo="body" #cd> </p-confirmDialog >

**Comment by prakashpixels** [comment]
Did you have any possible in multi line of content in confirmation box ?

**Comment by ningacoding** [comment]
@shaungrady use normal dialog with modal=true
