### ISSUE TITLE
[Primeicons v4] Abnormal icons size

### ISSUE THREAD

**Issue by Gretam11** [primefaces/primeng#9010]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

When the latest primeng (v 9.1.x) & primeicons(v 4.x.x) versions are used together, icons look huge everywhere.
**Comparison on file upload component:**
**Primeicons v2:**
![image](https://user-images.githubusercontent.com/19823838/86571780-aac25800-bf7a-11ea-9943-53ef9d68b9e0.png)

**Primeicons v4:**
![image](https://user-images.githubusercontent.com/19823838/86571828-c4639f80-bf7a-11ea-8628-0c9578dfd448.png)

Maybe primeicons v4 is not supposed to be used with primeng, but since v4 is the latest version and I didn't find any information about not using it, i consider that as an issue.

**Comment by yigitfindikli** [comment]
Hi @Gretam11,

PrimeIcons v4 will be available with PrimeNG v10.
