### ISSUE TITLE
Static messages are not disappearing on close "x" button click

### ISSUE THREAD

**Issue by yieldinov** [primefaces/primeng#9012]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Case available on documentation website and stackblitz
https://stackblitz.com/edit/primeng-messages-demo

<img width="1141" alt="Screen Shot 2020-07-06 at 17 50 54" src="https://user-images.githubusercontent.com/929834/86606923-4bcc0580-bfb1-11ea-8947-6564ee475045.png">

**Current behavior**
Static message is not closable

**Expected behavior**
When I click x button static message disappears

* **Angular version:** 9.1.3 

* **PrimeNG version:** 9.1.2

* **Browser:** all

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
