### ISSUE TITLE
Table Reset does not clear state entry

### ISSUE THREAD

**Issue by flkeller** [primefaces/primeng#9015]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/primeng-tabledoc-demo-peuryk

**Current behavior**
When using table.reset() method with stateStorage enabled, the state is not update in the storage (tested with local and session)

**Expected behavior**
state object should be cleared in storage

**Minimal reproduction of the problem with instructions**

1. Enter any filter/sorting in the stackblitz example
2. Click 'Reset Filters' btn, table is reloaded with no filtes/sorting as expected
3. Reload page, the filters/sorting from step 1. are applied again

**Comment by mickeyjohn** [comment]
@flkeller  According to the [documentation](https://www.primefaces.org/primeng/showcase/#/table), I think you might need to call dt.clearState() to clear your table state. dt.reset() does reset the filters in your example.

**Comment by flkeller** [comment]
@mickeyjohn thx for the information

i think this should be done on reset too.  I can not see a reason why a a different state as seen by the user should be saved. 
So probably not a bug but an enhancement

**Comment by waratah** [comment]
Please note that reset() in V8 cleared filters.    In V12 reset clears filters and it immediately resets to the original filters.  I trapped onsavestate and the filters are not cleared (the screen flickers, clear filters and then immediately resets the filters again.

I worked around my issue using this.table.fitlers = {} to clear the filters manually and the problem is now resolved.

note that reset() in V12 calls clear() so they are the same code.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by Rhobal** [comment]
`table.clearState()` should be included both in `table.clear() `and `table.reset()`

The current behaviour where `reset()` and `clear()` do not clear state do not meet use expectations of getting the same state when navigating away and back in the following use case:
- User applies filter
- User clears filters (`table.clear()` is used without `clearState()`)
- User navigates away and navigate back
- Expected: User gets the unfiltered state displayed before navigation
- Actual: User gets the state with the filter as it was before `table.clear()`

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
