### ISSUE TITLE
Autocomplete Search Suggestions reappear after selection when using Firefox Mobile Browser

### ISSUE THREAD

**Issue by jacorre** [primefaces/primeng#9016]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When using the Firefox browser on a mobile device (in this case Android), the autocomplete search suggestions reappear after selecting an entry.

**Expected behavior**
Once a selection is made, the search suggestions should not reappear.

**Minimal reproduction of the problem with instructions**
Visit [https://www.primefaces.org/primeng/v8.2.6-lts/#/autocomplete](https://www.primefaces.org/primeng/v8.2.6-lts/#/autocomplete) on your mobile device using the Firefox browser.

Under the Basic demo, enter United. You'll see search suggestions appear. Select United States. Notice the search suggestions reappear after making the selection. This does not occur in any other browser I've tried.

* **Angular version:** 
8.3.26

* **PrimeNG version:** 5.X
8.1.1

* **Browser:**
Firefox Mobile Browser v68.0.2

* **Node (for AoT issues):**
12.14.1

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
