### ISSUE TITLE
p-Treetable accessibility issue (ngPrime + Angular)

### ISSUE THREAD

**Issue by shubhamp090** [primefaces/primeng#9017]
Hi All & @cagataycivici 

We are currently using TreeTable(**primeNG control**) with frozen columns feature in our application.
It seems in the demo example of frozen column feature that it is not responding to the screen reader in the expected way.
Eg. - 
1) Screen reader should read table headers with defined keystrokes **(Alt + Ctrl + ArrowKeys)**
2) All td’s should be read along with the respective column headers when traversed in scan mode.

I've noticed ‘p-treetable’ is dividing entire structure in **_4 parts and creating 4 different tables_** resulting in disturbed screen reader behavior.

Is there any way to fix this on accessibility part?
Please let me know if any inputs.
Please find the images for reference - 

**Table Structure -** 
![tablesctrucure](https://user-images.githubusercontent.com/67959162/86904114-da659180-c12d-11ea-8f46-a14fea2461f2.png)

**Table in UI -** 
![tableview](https://user-images.githubusercontent.com/67959162/86903531-13513680-c12d-11ea-8f88-16cdc43112dc.png)

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
