### ISSUE TITLE
Programmatically expand all nodes on Treetable not working

### ISSUE THREAD

**Issue by filipduarte** [primefaces/primeng#9021]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/github-rjujei

**Current behavior**
I'm trying to recursively expand all nodes on a Primeng TreeTable component but without success. The row icons change and nothing more happens, except when i manualy click on the expand/colapse icon and all nodes are expanded/collapsed accordingly.

**Expected behavior**
Expand/collapse all nodes accordingly.

**Minimal reproduction of the problem with instructions**

1. Press "Expand all" or "Collapse all" button in the stackblitz example
2. Click on expand/collapse icon on any TreeTable row
3. See all rows expand/collapse

**What is the motivation / use case for changing the behavior?**
Meeting a user requirement, expand or collapse all rows.

**Please tell us about your environment:**

- Windows 10
- Angular version: 9.0.7
- PrimeNG version: 9.0.6
- Browser: Chrome 83.0.4103.116
- Language: TypeScript 3.9.4
- Node: v13.11.0

**Comment by FahadAnwarHussain** [comment]
@filipduarte just add this one  **this.files1 = [...this.files1];**  in expandCollapseRecursive function, it will worked fine,

**Comment by filipduarte** [comment]
Thanks @FahadAnwarHussain, worked.
