### ISSUE TITLE
'OverlayPanelModule' is missing import/export for 'SharedModule'

### ISSUE THREAD

**Issue by MaKCbIMKo** [primefaces/primeng#9023]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
`OverlayPanelModule` doesn't import/export `SharedModule` which makes `pTemplate` not working out of the box (but documentation proposes it as an option to use it)

**Expected behavior**
`OverlayPanelModule` imports and exports `SharedModule`.

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Comment by pete-mcwilliams** [comment]
https://github.com/primefaces/primeng/issues/9033

**Comment by pete-mcwilliams** [comment]
https://github.com/primefaces/primeng/commit/be716658eda996d34613f5010167facd7603f845
