### ISSUE TITLE
Dropdown appendTo body scrolling issue

### ISSUE THREAD

**Issue by nironater** [primefaces/primeng#9024]
**I'm submitting a ...** 
[ x ] bug report => Search github for a similar issue or PR before submitting

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primefaces-dropdown-append-to-body-scroll-issue

**Current behavior**
opened dropdown is detached from the location it's supposed to be

**Expected behavior**
Opened dropdown moves along and doesn't get detached

**Minimal reproduction of the problem with instructions**
1. Go to https://stackblitz.com/edit/primefaces-dropdown-append-to-body-scroll-issue
2. Scroll to bottom of Page
3. Open the right dropdown
4. Scroll the page when dropdown is open

**What is the motivation / use case for changing the behavior?**
When you want the dropdown not to be cut because of `overflow: hidden` of it's ancestor you add `[appendTo]="'body'"` but you still want it to move when you scroll the page

* **Angular version:** 9

* **PrimeNG version:** 9.1.3 (latest)

**Comment by TanayBhalani** [comment]
This issue is still present, and have been a while, can we get a solution for this or at least a workaround.
The mentioned issue #7952 is closed and many have asked to reopen it, even provided a stackblitz example with persistent issue.
Please provide a workaround at earliest.

**Comment by mertsincan** [comment]
Hi,
Please see this enhancement;
https://github.com/primefaces/primeng/issues/9324

Best Regards,
