### ISSUE TITLE
p-table scrollHeight="flex" requires virtualScroll in flex layout

### ISSUE THREAD

**Issue by remackgeek** [primefaces/primeng#9025]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

In a pure flex layout, where the p-table containing element has no fixed size, just something like "flex:1", setting scrollHeight="flex" does not set scrolling on the body, renders all the rows.

For an example, see :  [this stackblitz](https://stackblitz.com/edit/github-tdjyup-wvvika)

Adding [virtualScroll]="true" causes the table to scroll correctly, see: this [this stackblitz](https://stackblitz.com/edit/github-tdjyup)

**Expected behavior**

A scrollable table with fixed data should not require virtualScroll in a flex layout to properly size to the parent container

**Minimal reproduction of the problem with instructions**
see  [this stackblitz](https://stackblitz.com/edit/github-tdjyup-wvvika)

**What is the motivation / use case for changing the behavior?**

requiring virtualScroll for fixed data complicates sorting and searching

**Please tell us about your environment:**

* **Angular version:** 9.x

* **PrimeNG version:** 9.1.3

* **Browser:** [Chrome  ]

**Comment by chetakagrawal** [comment]
I am seeing the same problem. Do we have an update on this issue?

**Comment by vds-simon-lapointe** [comment]
We have this problem as well. I'd like an update as well.

**Comment by PotatoesMaster** [comment]
I have a workaround in place for this problem (I am using Angular 12 and PrimeNG 12, but I don't think this it matters in this case).

I added a min-height to the "datatable-scrollable-wrapper" internal element of the table :
```scss
// here in root styles.(s)css
// (this could alternatively be added in a component style, in which case ng-deep is required)
.p-datatable-scrollable-wrapper {
  min-height: 0;
}
```
I also made sure to have a min-height on flex-sized parent elements of the table.

The scrollbar appears as expected and as needed with a `p-table` having `[scrollable]="true"` and `scrollHeight="flex"`, without the need to enable virtual scrolling.

**Comment by ErikPhilips** [comment]
The only way I've gotten it to work within other flex elements is by overriding some of the defaults:

```
.p-datatable-flex-scrollable .p-datatable-wrapper {
  flex-basis: auto !important;
  height: 0 !important;
}
```

**Comment by leonardoporro** [comment]
> The only way I've gotten it to work within other flex elements is by overriding some of the defaults:
> 
> ```
> .p-datatable-flex-scrollable .p-datatable-wrapper {
>   flex-basis: auto !important;
>   height: 0 !important;
> }
> ```

works for me, this should be added to source

**Comment by mertsincan** [comment]
Hi,

We changed our virtualScroll implementation. We designed a new scroller API instead of Angular cdk and used it in all components. So, I think this issue has already been fixed.
https://github.com/primefaces/primeng/issues/11656

If the problem persists, please reopen this ticket. Thanks a lot for your understanding!

Best Regards,

**Comment by philippwaller** [comment]
@mertsincan: Thanks for the update. I am using v14.0.1 and the problem still persists. Fortunately, @leonardoporro's fix still works. 

@remackgeek: I would suggest to reopening this ticket.

**Comment by buchatsky** [comment]
Really it is enough to change `flex: 1;` for `flex: 1 1 0;` in table.css for `.p-datatable-flex-scrollable > .p-datatable-wrapper`

**Comment by vcucchiara** [comment]
> > The only way I've gotten it to work within other flex elements is by overriding some of the defaults:
> > ```
> > .p-datatable-flex-scrollable .p-datatable-wrapper {
> >   flex-basis: auto !important;
> >   height: 0 !important;
> > }
> > ```
> 
> works for me, this should be added to source

I have been battling this for a while. This suggestion worked for me. Thx for the fix!

**Comment by andreasreinkeivoflow** [comment]
in Version 19.x.x it kind of worked (for the moment, not sure yet) with this css overwrite:
    :host ::ng-deep .p-virtualscroller.p-virtualscroller-inline {
      height: 100% !important;
    }

but not very happy with this approach

**Comment by rc14193** [comment]
Nudging again as I'm seeing this issue with 19.1.2 and none of the listed solutions worked for me

**Comment by lukakuder** [comment]
I had the same problem in v21, but it turns out i was being dumb and didn't include [scrollable]=true in the p-table definition, which is needed if you have scrollHeight="flex", this is the definition that worked for me, also make sure you have all the parent containers set to flex and 100% height
```
<p-table
      [value]="matters"
      [lazy]="true"
      [scrollable]="true"
      [virtualScroll]="true"
      [virtualScrollItemSize]="58"
      [rows]="50"
      scrollHeight="flex"
      [totalRecords]="totalRecords"
      (onLazyLoad)="loadMattersLazy($event)"
      >
```
