### ISSUE TITLE
Position of scroll in p-dropdown with virtual scroll enabled not maintained 

### ISSUE THREAD

**Issue by senp0105** [primefaces/primeng#9026]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://github-ekx7a5.stackblitz.io

**Current behavior**
In dropdown i have 10000 items first i select "item 9999" using search textbox then remove the selected text from search textbox. since selected item is "item 9999" Position of scroll is near to item 9999 with blue highlight.

Now i select "item 0" by using scroll without using search textbox  and selecting  it. Now selected item is "item 0". Now if i again reopen the dropdown. Position of scroll is still near to "item 9999" but blue highlight is at "item 0"

**Expected behavior**
if selected item is "item 0" then scroll position should be near "item 0" as well as "item 0" should be blue highlighted.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:**9.0.4

* **PrimeNG version:** 9.1.0

* **Browser:** Chrome latest

 
* **Language:** [all | TypeScript 3.8.3 | ES5]

* **Node (for AoT issues):** `node --version` = 12.16.3

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
