### ISSUE TITLE
Regression styling bug on pButton directive in versions 9.1.1 - 9.1.3

### ISSUE THREAD

**Issue by mlc-mlapis** [primefaces/primeng#9029]
**I'm submitting a ...**
```[x] bug report => Search GitHub for a similar issue or PR before submitting```

**Plunkr Case (Bug Reports)**
Demo working correctly: https://stackblitz.com/edit/mlc-primeng-button-910
Demo NOT working correctly: https://stackblitz.com/edit/mlc-primeng-button-913

**Current behavior**
Because of changes in TS code in version 9.1.1 -> by introducing `setStyleClass()` and its running in `label` and `icon` setters, the defined classes from a template like `class="ui-button-rounded ui-button-secondary"` are overwritten in any change detection refresh on any component that is using `pButton` directive.

**Expected behavior**
Version 9.1.0 doesn't have the implementation of `setStyleClass()` yet, so it works as expected. It's expected that version 9.1.1 till 9.1.3 till the latest will work as before from the UI point of view. It means that the applied `class` on `<button>` component still works.

**Minimal reproduction of the problem with instructions**
Run the Stackbitz above and after the first initial rendering press REFRESH button to re-render the component.

**Alternative solution**
If property `cornerStyleClass` is used like `cornerStyleClass="ui-button-rounded ui-button-secondary"` instead of `class`, then it works because of the actual code implementation, but this way is probably unexpected. The documentation doesn't say anything about it; also no breaking changes notification.

* **PrimeNG version with the bug:** 9.1.1 - 9.1.3
* **Browser:** all

**Comment by jacqueslareau** [comment]
Experiencing the same issue.

**Comment by mlc-mlapis** [comment]
Because of the already merged #9020, I am closing this issue.
