### ISSUE TITLE
What happened to the premium themes (RIO etc?)

### ISSUE THREAD

**Issue by kevinhaeni** [primefaces/primeng#903]
Hi, I'm very interested in the premium theme RIO for PrimeNG, but see they disappeared a day ago.

Will they be coming back?

**Comment by sudheerj** [comment]
I think it reached EOS for few Premium templates like RIO. There are next generation layouts and templates available.Please check PrimeStore https://www.primefaces.org/store/

@cagataycivici Correct me If i'am wrong.
