### ISSUE TITLE
virtualScroll onLazyLoad is triggered twice onInit 

### ISSUE THREAD

**Issue by rgalapate** [primefaces/primeng#9030]
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Please see:
https://stackblitz.com/edit/primeng-tablevirtualscroll-demo-g6vlbi

**Current behavior**
virtualScroll onLazyLoad is triggered twice onInit 

**Expected behavior**
should be triggered once

**Minimal reproduction of the problem with instructions**
See stackblitz attached

* **Angular version:** 5.X
9

* **PrimeNG version:** 5.X
9

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by tiagomartins91** [comment]
Same issue https://github.com/primefaces/primeng/issues/9080

**Comment by rfrancisco** [comment]
I made a workaround for this. I have a couple of samples in [this sample app](https://github.com/rfrancisco/demo-primeng) if you want to check it out.

**Comment by soumyakp** [comment]
I'm also facing the same issue.

**Comment by middoors** [comment]
I have the same problem with p-table. It calls the onLazyLoad twice at initial.

**Comment by middoors** [comment]
@rfrancisco can you please be more specific and tell us where in your code would do the workaround? Thanks :)

**Comment by cagataycivici** [comment]
Tracked at 9080.
