### ISSUE TITLE
Help with the internationalization of p-calendar

### ISSUE THREAD

**Issue by AlbaSS18** [primefaces/primeng#9032]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

I am using the internationalization-framework called i18next. One of my components is a p-calendar but I don't know how to internationalize it with this framework. Does anyone know how I can internationalize this component with i18next? If someone knows another solution without using i18next, I can also use.

**Please tell us about your environment:**

* **Angular version:** 8.2

* **PrimeNG version:** 8.1.1

**Comment by yigitfindikli** [comment]
You can use new i18n api with v11.0.0-rc.1
