### ISSUE TITLE
p-messages doesn't show static content

### ISSUE THREAD

**Issue by fenixrom** [primefaces/primeng#9033]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Case available on documentation stackblitz
https://stackblitz.com/edit/primeng-messages-demo

![Meesages static content](https://user-images.githubusercontent.com/7842496/87320471-a62a1080-c533-11ea-913c-9f5f28df650b.PNG)

**Current behavior**
Static template for p-massages doesn't work. I tried `pTemplate="content" ` or just `pTemplate` and in both cases it doesn't show static messages with custom content. Moreover, when you click on 'User Service' button in stackblitz it will add the message in 2 places - where we plan to show message via service and to empty message where I want to have custom static content.

**Expected behavior**
Static template works correct.

* **Angular version:** 9.1.3

* **PrimeNG version:** 9.1.3

* **Browser:** ALL

**Comment by fenixrom** [comment]
I figured out, that it works if I add ToastModule to AppModule. However, it's not clear why there is a dependency on ToastModule, I didn't find any docs which said that we have to include ToastModule to have MessagesModule work correct. 
By the way, there is the same behavior with OverlayPanelModule, if I don't import ToastModule, it will not work

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 10.0.0-rc.3, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Comment by pete-mcwilliams** [comment]
Exactly same as @fenixrom in "primeng": "^10.0.3", needed to import ToastModule to get static messages to show.

**Comment by pete-mcwilliams** [comment]
Will raise another issue but I saw the same issue with lazy loading a module with OvelayPanelModule, if I included ToastModule it worked...

ToastModule is including SharedModule, which the others are not... swapping the ToastModule for SharedModule in the lazy loaded module allow the pTemplate to be recognised in the overlay panel.

Suspect adding SharedModule to lazy loaded MessageModule packages would also fix this issue.

**Comment by pete-mcwilliams** [comment]
https://github.com/primefaces/primeng/commit/be716658eda996d34613f5010167facd7603f845

**Comment by divyanshrana** [comment]
Workaround for this can be by using the prime classes.

```
<div class="p-message p-message-info p-component">
    <div class="p-message-wrapper p-d-flex p-flex-row p-ai-center">
        <span class="p-message-icon pi pi-info-circle"></span>
        <span>
            <ul>
                <li>ITEM 1</li>
                <li>ITEM 2</li>
                <li>ITEM 3</li>
            </ul>
        </span>
    </div>
</div>
```
![image](https://user-images.githubusercontent.com/19736433/128504108-471c1382-fa20-4c31-98b7-e8fbe66edb03.png)

Stackblitz demo: https://stackblitz.com/edit/primeng-messages-demo-ggrxna?file=src%2Fapp%2Fapp.component.html

**Comment by cdskill** [comment]
I'm still facing this... primeNG 12.2.x

this piece of code is not working
```
<p-messages severity="info">
  <ng-template pTemplate>
    <div class="ml-2">Always bet on Prime.</div>
  </ng-template>
</p-messages>
```

**Comment by mikehutter** [comment]
This is still happening in v16.x and as @cdskill mentioned, the SharedModule is still not re-exported in the MessagesModule.

**Comment by jlevot** [comment]
I have the same issue with v17.x
I have to import the `SharedModule` in my standalone components which use a custom template.

**Comment by The-Real-1** [comment]
@cagataycivici 
Is there any reason for not re-exporting the SharedModule inside the MessagesModule ? 
It would be nice to have the official documentation explaining how to enable templates management by importing the SharedModule inside the MessagesModules to make the static behavior operationnal .

**Comment by MAN-Sendance** [comment]
Like @jlevot said, `SharedModule` has to be imported to get it working.
