### ISSUE TITLE
Table - context menu selection is incorrect when dataKey is specified

### ISSUE THREAD

**Issue by saramcicchi** [primefaces/primeng#9035]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When the following attributes are specified on a table, the selected item does not get updated appropriately.
```
selectionMode="single" [(selection)]="selectedItem" [contextMenu]="cm" contextMenuSelectionMode="joint" dataKey="<something>"
```
After right clicking on more than one row, if you try to right click on any of the rows that have already been clicked on, the selected item will be the last newly clicked row, instead of the last clicked row.

This *only* happens if the dataKey attribute is specified. If it is not specified, the expected row is selected.

**Expected behavior**
The row that is right-clicked on should be the selected row.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/primeng-tablecontextmenu-demo-hnmnux

**What is the motivation / use case for changing the behavior?**
Right clicking on a row should select that row.

**Please tell us about your environment:**

* **Angular version:** 9.1.9

* **PrimeNG version:** 9.1.0

* **Browser:** Chrome and Firefox (and probably others)
 
* **Language:** all

* **Node (for AoT issues):** `node --version` =  12.16.3

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Comment by saramcicchi** [comment]
Hi @yigitfindikli, I was able to replicate it in stackblitz with PrimeNG 11.0.0-rc.1. Please see https://stackblitz.com/edit/primeng-tablecontextmenu-demo-v11. Thanks!
