### ISSUE TITLE
Issues with server side rendering in these three components (button, inputmask, & keyfilter)

### ISSUE THREAD

**Issue by lightbulb110** [primefaces/primeng#9036]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Build fails with navigator and document error

**Expected behavior**
Should be able to SSR and prerender

**Minimal reproduction of the problem with instructions**
latest version of angular & universal. run command npm run prerender with these components in your app and build will fail

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.X
9x

* **PrimeNG version:** 5.X
9x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

* **Node (for AoT issues):** `node --version` =

**Comment by GerkinDev** [comment]
Same for `Ripple` and `Carousel` (according to #8447) directives. And probably many others.

So sad, I thought about buying a licence, but I won't because for now I have to rewrite almost everything for SSR to work.

Related to #8447, #8817 and probably many others.

Hey guys, you're missing some sells here.

**Comment by lightbulb110** [comment]
> Same for `Ripple` (according to my own experience right now) and `Carousel` (according to #8447) directives. And probably many others.
> 
> So sad, I thought about buying a licence, but I won't because for now I have to rewrite almost everything for SSR to work.
> 
> Related to #8447, #8817 and probably many others.
> 
> Hey guys, you're missing some sells here.

What version are you working on? Not sure about the ones you mentioned but the ones I found were easily fixed.

**Comment by GerkinDev** [comment]
I used the latest one available on NPM.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by camilo-mujica** [comment]
Same here with table and carousel components :(
