### ISSUE TITLE
Closing dialog fails in Edge browser

### ISSUE THREAD

**Issue by jdcrutchley** [primefaces/primeng#904]
1. Go to the showcase with Edge browser:  http://www.primefaces.org/primeng/#/dialog
2. Click "Show" button.  Dialog will pop up.
3. Click either "Yes" or "No" in dialog - doesn't matter which.
4.  Get "Expression has changed after it was checked" error in console and can no longer show dialog by clicking "Show" button.

I get the same thing in my test app with latest Angular (RC7) and zone.js (0.6.23).

**Comment by garethlewis** [comment]
Which version of Edge are you using?  I've got the version in the release 1511.

**Comment by jdcrutchley** [comment]
Edge version 28.14393.0.0, EdgeHTML 14.14393.  This is in Windows build 14393 (anniversary update).

**Comment by garethlewis** [comment]
That is a newer version than I have.  I have 25.10586.0.0.  And our application uses dialogs and panels everywhere.

Looking at the text you have displayed, that only occurs when the change detection throws an error.  It is stating that a variable you have asked it to look after with binding, has been changed, but the control didn't change it.  That will definitely not be true in this case.  Pressing either button causes the bound variable to change and the change detection is expecting that.

**Comment by jdcrutchley** [comment]
I agree, it shouldn't happen.  It does though, even just on the sample app on primefaces.org.

**Comment by jdcrutchley** [comment]
I can no longer reproduce this.  Going to close for now.
