### ISSUE TITLE
table virtual scroll with  selectionMode - Incorrect  selected on scroll

### ISSUE THREAD

**Issue by yuyinjun** [primefaces/primeng#9043]
when the table is  selectionMode =true and selected one row ,then the row selected highlight is Incorrect   on scrolling

[demo](https://stackblitz.com/edit/primeng-tablevirtualscroll-demo-gwib2u?file=src%2Fapp%2Fapp.component.html)

**Comment by GretchenGit** [comment]
Same problem here - would be great if selection works on single and multiple combined with virtual scrolling

**Comment by mfig** [comment]
I think it's same issue with #8952

**Comment by MdShahrukh** [comment]
The same Selection issue i am facing with treatable as well while having virtual-scroll implemented 
https://stackblitz.com/edit/primeng-treetablescroll-demo-xu176e?file=src%2Fapp%2Fapp.component.html

**Comment by cagataycivici** [comment]
Please see;

https://github.com/primefaces/primeng/issues/8952
