### ISSUE TITLE
Horizontal Tree: An extra line is added to all leaf nodes if I expand all of the nodes programmatically

### ISSUE THREAD

**Issue by axell9641** [primefaces/primeng#9046]
I'm trying to use the PrimeNG Horizontal Tree and it works great until I try to expand all of the nodes programmatically.
If I try to do so, then all of the leaf nodes end up with and extra horizontal connector:

![image](https://user-images.githubusercontent.com/637311/87733358-3fa42d00-c795-11ea-9052-8312f65c0baa.png)

This doesn't happen if I expand the node manually, one by one.
I tried to create [**a demo in stackblitz**](https://stackblitz.com/edit/primeng-treehorizontal-demo-hcruwb) but there's seems to be a problem with external images, so if you want see the problem I described above you're going to have to use the chrome developer tool to add an image of a line like this :

![image](https://user-images.githubusercontent.com/637311/87733800-6dd63c80-c796-11ea-9993-0ae3080dcaaa.png)

Here's [the link of the line I used](https://lh3.googleusercontent.com/proxy/WysWyBu9pEfk1O643qGR817sI8ug5tEzsRx3-PvtdPyUYIfW-XW3gwLEP-RXoBFdU2Bw7I9M3bmo4rofs01jvURj)

If you add that image, then you'll be able to see what I'm talking about: 

![image](https://user-images.githubusercontent.com/637311/87733880-a1b16200-c796-11ea-8ad3-07310fd439dc.png)

Do you have any idea what might be going on here?

These are the version of relevant packages I'm using : 

"@angular/core": "~9.1.4",
"primeicons": "^4.0.0",
"primeng": "^9.1.3",

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Comment by linhfpt** [comment]
have anyone can fix this bug?

**Comment by linhfpt** [comment]
the idea for this is expand some node of it. done expand all of them.

**Comment by axell9641** [comment]
Sorry, I should have posted the solution earlier.
The problem was that the method (expandAll) showed [in the docs](https://www.primefaces.org/primeng/showcase/#/tree) marks a node as expanded without checking first whether it has children or not. 

private expandRecursive(node:TreeNode, isExpand:boolean){
        
        if (node.children){
            node.expanded = isExpand; // move this line inside the if condition
            node.children.forEach( childNode => {
                this.expandRecursive(childNode, isExpand);
            } );
        }
    }

Note that you can get the same result using the leaf property of the node, you just need to negate the property like this:

if (!node.leaf) {

}

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
