### ISSUE TITLE
Table filters won't fit the column width when viewpoint gets smaller

### ISSUE THREAD

**Issue by projectX21** [primefaces/primeng#9058]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-tablefilter-demo (official example)

**Current behavior**

The filters for the columns will overflow and won't fit the header width, when the browser width is smaller than ~1000px.

**Expected behavior**

The filters should be resize based on the parents th.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

I think it can only be a styling problem in those particular tables and not a real PrimeNG Bug. 
But nevertheless should the example work in the correct way, because the most users (me included) will reuse the code.
Even with the developer tools I couldn't do it. Only for the input tags with the style width: 100% but not for the dropdown.

**Please tell us about your environment:**

OS: Debian Buster, NPM v6.14.6

* **Angular version:**

9.0.4

* **PrimeNG version:**

9.1.0

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.2.2, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
