### ISSUE TITLE
Website Alignment Enhancement

### ISSUE THREAD

**Issue by PardeepJain** [primefaces/primeng#906]
In order to make website center aligned please add this css code to them main parent `div having class named as PC`

Css Code 

`{ 
   max-width: 1300px;
   margin-right: auto;
   margin-left: auto;
}`

Before :- 

![priemng1](https://cloud.githubusercontent.com/assets/15938178/18546339/06e5503c-7b5b-11e6-808d-7b864b54b4c6.png)

After :- 

![primeng2](https://cloud.githubusercontent.com/assets/15938178/18546343/1149f99c-7b5b-11e6-847e-6fa103f3b4a0.png)

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.

**Comment by sudheerj** [comment]
Not sure why we need to make it center aligned.Is it something need for mobile site?

**Comment by PardeepJain** [comment]
@Mrtcndkn yeah tried with latest version too, still same issue.

@sudheerj no need to make it center aligned , just because center aligned website looks more cool than disordered website.
