### ISSUE TITLE
Disabling draggable does not work properly

### ISSUE THREAD

**Issue by Cito** [primefaces/primeng#9061]
It should be possible to disable the draggable behavior of a `pDraggable` element by setting `pDraggableDisabled="true"`.

Unfortunately, this does not work properly because the `draggable` property of the HTML element is not reset.

The [code](https://github.com/primefaces/primeng/blob/99d9947688971b7d91c0f5dcf70c2a4d280b818a/src/app/components/dragdrop/dragdrop.ts#L40) looks like this:

```js
 set pDraggableDisabled(_pDraggableDisabled:boolean) {
        this._pDraggableDisabled = _pDraggableDisabled;
        if (this._pDraggableDisabled) {
            this.unbindMouseListeners();
        }
        else {
            this.el.nativeElement.draggable = true;
            this.bindMouseListeners();
        }
    }
```

As you see, the `draggable` property is not set to false when `_pDraggableDisabled` is false. This can cause problems because in this case e.g. Firefox is still firing drag start events, and e.g. text inputs inside draggables won't work properly (I'm using this feature to implement a workaround for [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1189486)).

**Comment by maxfriedmann** [comment]
@Cito I get the same error. How come this is isn't a major issue for anyone else?

In Angular, setting `[p-dialog component].nativeElement.draggable = false;` right before opening the dialog solves the issue

**Comment by cetincakiroglu** [comment]
Hi,

We couldn't replicate the issue with the latest PrimeNG (v13).
If the issue still exists with the latest PrimeNG version, please provide a StackBlitz example by using [PrimeNG Issue Template ](https://stackblitz.com/github/primefaces/primeng-issue-template) and re-open the issue.

Regards

**Comment by maxfriedmann** [comment]
Hi @cetincakiroglu, is there a backport planned for 12.x versions?

**Comment by Cito** [comment]
Hi @cetincakiroglu!

The code listed above was not changed in v13, so unfortunately, this is still not solved.

[Here is a StackBlitz demonstration](https://stackblitz.com/edit/primeng-issue-9061).

But the problem should be really obvious from the code listed above already.

Setting ` this.el.nativeElement.draggable = true` in the `if`-block should fix this.
