### ISSUE TITLE
Do we have Source code Edit (HTML) or code view button ?

### ISSUE THREAD

**Issue by srikanthchitla** [primefaces/primeng#9063]
1) Do we have Source code Edit (HTML) or code view in p-editor? if yes, is there any example?

2) Can we show the html code in p-editor when it loads? Right now it is converting HTML code to text.

_**Example;**_ 
**app.component.html**
<p-editor [(ngModel)]="text"></p-editor>

**app.component.ts**
export class EditorDemo {
    text: `<div>Hello World!</div><div>PrimeNG <b>Editor</b> Rocks</div><div><br></div>`;
}

**Result in Editor**
Hello World!
PrimeNG **Editor** Rocks

Can I expect the result as html code in result in Editor ??
**Ex:** 
`<div>Hello World!</div><div>PrimeNG <b>Editor</b> Rocks</div><div><br></div>`

**Comment by cagataycivici** [comment]
Please use forum for questions and support requests.
