### ISSUE TITLE
Use Calendar Component with Custom Date Library

### ISSUE THREAD

**Issue by timaebi** [primefaces/primeng#9064]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**What is the motivation / use case for changing the behavior?**
As far as I know, PrimeNG's Calendar Component only works with native JS Date objects or strings. However, for simpler date manipulation developers usually choose a date library such as [js-joda](https://js-joda.github.io/js-joda/) or [moment.js](https://momentjs.com/). It would be nice if the Calendar widget could store such date objects in the data model and not just native JS Date objects.

Concerning the implementation of such a feature, I really like the approach that the angular-material team has chosen where the consumer of PrimeNG can implement a [DateAdapter](https://github.com/angular/components/blob/master/src/material/core/datetime/date-adapter.ts) interface which handles the conversion between library date objects and primeng.

**Comment by pschaffl** [comment]
This would definitely make the calendar widget more useful.

**Comment by pschaffl** [comment]
Could we have a progress update on this issue, please?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
