### ISSUE TITLE
Chips Comma Seperator - comma on num block side doesn't work

### ISSUE THREAD

**Issue by projectX21** [primefaces/primeng#9065]
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://primefaces.org/primeng/showcase/#/chips

**Current behavior**

The example "Comma Separator" doesn't listen to the comma on the num block side:
In the attached image blue works, but red doesn't.
[tastatur layout](https://i.ibb.co/84VnG2P/tastatur.png)

**Expected behavior**

The comma on the num block side should work exactly as the "normal" one.

**Minimal reproduction of the problem with instructions**

The example "comma Seperator" works with the "normal" comma, but it doesn't work with the comma on the num bock side.

**Comment by cetincakiroglu** [comment]
Hi,

We couldn't replicate the issue with the latest PrimeNG (v13).
If the issue still exists with the latest PrimeNG version, please provide a StackBlitz example by using [PrimeNG Issue Template ](https://stackblitz.com/github/primefaces/primeng-issue-template) and re-open the issue.

Regards
