### ISSUE TITLE
Dynamic dialog is buggy when it opens multiple dialogs

### ISSUE THREAD

**Issue by mikaelboff** [primefaces/primeng#9069]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/primeng-dynamicdialog-bug

**Current behavior**
I am opening 2 dynamic dialogs, one after another, on the same file. When I close the first, everything is ok; but, when I close the second one, the p-dynamicDialog component isn't destroyed and the backdrop doesn't disappear.

**Expected behavior**
It should be able to close all the dialogs and it's backdrop too.

**Minimal reproduction of the problem with instructions**

- Click on the "Show" button

- Close the first dialog modal and then close the second one

**What is the motivation / use case for changing the behavior?**
The application is becoming buggy with this behavior.

* **Angular version:** 9.1.1

* **PrimeNG version:** 9.1.0

* **Browser:** all
 
* **Language:** all

**Comment by mikaelboff** [comment]
@yigitfindikli @cagataycivici

**Comment by tisys-parceiros** [comment]
was this problem resolved?

**Comment by cetincakiroglu** [comment]
Hi,

We couldn't replicate the issue with the latest PrimeNG (v13).
If the issue still exists with the latest PrimeNG version, please provide a StackBlitz example by using [PrimeNG Issue Template ](https://stackblitz.com/github/primefaces/primeng-issue-template) and re-open the issue.

Regards
