### ISSUE TITLE
Replace plain string label in MultiSelect with <ul> list like in autocomplete widget

### ISSUE THREAD

**Issue by Dema** [primefaces/primeng#907]
Is it possible to replace plain comma-separated label with "ul>li list the same way  autocomplete component does? The idea is that I need to have onClick events on individual selected items.

**Comment by cagataycivici** [comment]
Interesting idea, we'll consider this.

**Comment by cagataycivici** [comment]
We've decided to keep it as it is and will reconsider if more users demand it.

**Comment by PrajwalGonsalves07** [comment]
Hi,

I would like to change the label in a Multiselect. Not the defaultLabel, but the label when items are selected. I don't want to see the list of the selected items as a label, but I want to put a default label everytime.

Any idea on how to do this ?

Thanks in advance !
