### ISSUE TITLE
Icon within messages panel (p-messages) are wrong formatted

### ISSUE THREAD

**Issue by araklefeistel** [primefaces/primeng#9070]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/primeng-messages-demo

**Current behavior**
The size of icons within the p-messages are to big. Within the showcase (https://www.primefaces.org/primeng/showcase/#/messages) they pick up the correct css.

**Expected behavior**
Size of the icons within the message panel should be same as in the showcase.

**Minimal reproduction of the problem with instructions**
1. Open https://stackblitz.com/edit/primeng-messages-demo
2. Click on Success
3. Take a look on the icons

**What is the motivation / use case for changing the behavior?**
Layout of the message panel should be cleaned up

**Please tell us about your environment:**
Chrome Version 84.0.4147.89  on Mac 10.15.5
Chrome Version 83.0.4103.116 on Windows 10  

* **Angular version:** 5.X
9.1.12

* **PrimeNG version:** 5.X
9.1.3

* **Browser:** 
Chrome Version 84.0.4147.89  on Mac 10.15.5
Chrome Version 83.0.4103.116 on Windows 10  

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES5

* **Node (for AoT issues):** `node --version` =   
12.18.1

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
