### ISSUE TITLE
SplitButton: completely customizable without MenuModelApi

### ISSUE THREAD

**Issue by projectX21** [primefaces/primeng#9071]
[ ] bug report => Search github for a similar issue or PR before submitting
[ x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Current behavior**

The SplitButton needs an items-array. These items will be created in the SplitButton automatically.

**Expected behavior**

For better customization a completely customizable SplitButton is highly needed. In my case for example every row in a table should get an own SplitButton (e.g. with the options edit, delete, ...) The options can be used with the (onClick) event to pass the clicked table row: 
```
<CustomButtonListOption (onClick)="update(tableRow)">Update</CustomButtonListOption>
<CustomButtonListOption (onClick)="delete(tableRow)">Delete</CustomButtonListOption>
```

NG-Bootstrap for example has such a feature:
https://ng-bootstrap.github.io/#/components/dropdown/examples

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
