### ISSUE TITLE
InputTextarea onResize callback is not working

### ISSUE THREAD

**Issue by mmlitvin** [primefaces/primeng#9074]
I'm submitting a bug report in "primeng": "9.1.0",

Use Case:
https://stackblitz.com/edit/primeng-inputtextarea-demo-d5pou8?file=src%2Fapp%2Fapp.component.html

**Current behavior**
onResize() is not called when user is resizing the textarea (when autoResize=false)

**Comment by cetincakiroglu** [comment]
Hi,

If the issue still exists with the latest PrimeNG version, please provide a StackBlitz example by using [PrimeNG Issue Template ](https://stackblitz.com/github/primefaces/primeng-issue-template) and re-open the issue.

Regards
