### ISSUE TITLE
Table component tries to restore non-existing state

### ISSUE THREAD

**Issue by Cito** [primefaces/primeng#9076]
**I'm submitting a [x] bug report**

**Current behavior**

Situation: You have a Table component that stores state using a stateKey. This table does not use a paginator, but other stateful properties like selectable rows.

When the state of the table is saved, the saved state value will not contain properties `rows` or `first` because the table does not use a paginator. But the saved state value could still be not empty, e.g. it could be `{"selection":123}`.

Later you add a paginator to the table.

Now when the state of the table is restored, the table also tries to restore `rows` and `first` from the state because the table now has a paginator. Since these values have not been saved in the stateKey, they will now be `undefined`. Nothing is displayed any more, even when the table contains rows, because the `rows` property of the table is undefined.

**Expected behavior**

The Table component should restore only those properties of the state that are actually defined. E.g. when there is no `rows` property in the saved state, the `rows` property of the table should not be altered.

Then the table would use the default value for `rows` and everyting would show up even if the paginator was only added later.

**What is the motivation / use case for changing the behavior?**

Two reasons why you may want to add a paginator only later:

1. You ship a new version of an app. The first version did not have a paginator, but the second version has one. Users still have table state of the first version stored in local storage.
2. You may want to suppress the paginator while the table is small. Once the table size reaches a certain limit, you activate the paginator. Users still have state of the table without paginator in session storage.

**PrimeNG version:** 10.0.0-beta.1

**Cause and suggestested solution**

The problematic code is [here](https://github.com/primefaces/primeng/blob/7082648db5a25aff1579fff4cf6f838efece210b/src/app/components/table/table.ts#L2027) in `table.ts`:

```js
    restoreState() {
        const storage = this.getStorage();
        const stateString = storage.getItem(this.stateKey);

        if (stateString) {
            let state: TableState = JSON.parse(stateString);

            if (this.paginator) {
                this.first = state.first;
                this.rows = state.rows;
                this.firstChange.emit(this.first);
                this.rowsChange.emit(this.rows);
            }
```

As you see, `this.first` is set to `state.first` without checking whether `state.first` exists. So suggested fix would be to do this:

```js
    restoreState() {
        const storage = this.getStorage();
        const stateString = storage.getItem(this.stateKey);

        if (stateString) {
            let state: TableState = JSON.parse(stateString);

            if (this.paginator) {
                if (this.first !== undefined) {
                    this.first = state.first;
                    this.firstChange.emit(this.first);
                }
                if (this.rows !== undefined) {
                    this.rows = state.rows;
                    this.rowsChange.emit(this.rows);
                }
            }
```

The same checks should be added for other properties in this method before restoring their values.

**Comment by mwinds375** [comment]
@cagataycivici Why you check `this.first` but not `state.first`?
