### ISSUE TITLE
p-autocomplete not aligned with ui-inputgroup-addon using ui-fluid p-formgrid p-grid

### ISSUE THREAD

**Issue by Skellyus** [primefaces/primeng#9077]
The alignment of the input field of p-autoComplete is not consistent with the ui-inputgroup-addon. Expected behavior would be the same as input of pInputText.

Code to reproduce
```
<div class="ui-fluid p-formgrid p-grid">
  <div class="p-field p-col-12 p-md-6">
    <label for="owner">Owner</label>
    <div class="ui-inputgroup">
      <span class="ui-inputgroup-addon"><i class="pi pi-user"></i></span>
      <p-autoComplete id="owner">
      </p-autoComplete>
    </div>
  </div>
</div>
```
Version of modules
nodejs -v
v12.18.3

"@angular/animations": "~10.0.3",
"@angular/cdk": "^10.1.1",
"@angular/common": "~10.0.3",
"@angular/compiler": "~10.0.3",
"@angular/core": "~10.0.3",
"@angular/forms": "~10.0.3",
"@angular/platform-browser": "~10.0.3",
"@angular/platform-browser-dynamic": "~10.0.3",
"@angular/router": "~10.0.3",
"@fullcalendar/core": "^5.1.0",
"bootstrap": "^4.5.0",
"chart.js": "^2.9.3",
"primeflex": "^2.0.0-rc.1",
"primeicons": "^4.0.0",
"primeng": "^9.1.3",
"quill": "^1.3.7",
"rxjs": "~6.5.5",
"tslib": "^2.0.0",
"zone.js": "~0.10.3",

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
