### ISSUE TITLE
Incorrect change of FilleUpload label by pipe

### ISSUE THREAD

**Issue by dbelob** [primefaces/primeng#9078]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/github/dbelob/primeng-fileupload-error

**Current behavior**
![Screenshot - 28 07 2020 , 20_55_21](https://user-images.githubusercontent.com/22131253/88703666-aa4e5480-d115-11ea-9aa6-b243aef0136d.png)
When the **Choose** button label is set (by **chooseLabel** property) using a pipe (_TranslatePipe_ from @ngx-translate), the button is invalid. **uploadLabel** and **cancelLabel** properties are used without errors.

**Expected behavior**
The **Choose** button should not be distorted when using _TranslatePipe_.

**Minimal reproduction of the problem with instructions**
In the **FileUpload** component set **chooseLabel** property by pipe.

**Please tell us about your environment:**
* **Windows 8.1**

* **npm 6.14.5**

* **Angular version:** 10.0.9

* **PrimeNG version:** 9.1.3

* **Browser:** all
 
* **Language:** all

* **Node (for AoT issues):** `node --version` = v12.16.1

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
