### ISSUE TITLE
Compatibility Check with Angular 2.0 Final

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#908]
Check the entire components with NG2 final.

**Comment by AloeDream** [comment]
@cagataycivici  at least dependencies must be updated to match Angular 2 final version. At this moment I can't install priming package because of peer dependencies.

**Comment by garethlewis** [comment]
@AloeDream I'm on Angular 2.0 Final and I am using PrimeNG Beta 15 with no problems.  There should be warnings, as the packages Prime uses are earlier than the Angular 2 version referenced and the rxjs version will be newer, but it won't stop it working.

If your build tools are failing that, you've got a problem with your build tools.

**Comment by Floppynator** [comment]
p-calender isnt working for me, jquery issue

**Comment by AloeDream** [comment]
@garethlewis, primeng package has peer dependencies incompatible to Angular 2 final. Rxjs is one of them. So it can't be installed.

**Comment by garethlewis** [comment]
@AloeDream I have Angular 2 Final and PrimeNG.  PrimeNG can be installed.

**Comment by cagataycivici** [comment]
But beta15 has no dependencies or peerDependencies in the npm package.

**Comment by vinnybrown** [comment]
I'm getting this:
Error in ./TieredMenu class TieredMenu - inline template:3:12 caused by: No provider for Router!

**Comment by cagataycivici** [comment]
Currently menu components depend on Router but we'll consider breaking that dependency in a future version. Overall we've tested upcoming beta16 with NG 2.0 and have no issues.

**Comment by sktzoootech** [comment]
PrimeNG pretty much works on angularjs2 final except for p-calendar which works outside of a form but inside requires me to add a name to the input field.  Is adding a name attribute to p-calendar possible? Not sure if this is covered by Compatibility Check.
