### ISSUE TITLE
p-virtualScroller lazy load event fires twice

### ISSUE THREAD

**Issue by mfish0005** [primefaces/primeng#9080]
Is there a way to prevent the lazy loading from firing twice on the virtual scroller component?   @cagataycivici said in  #5480 that `p-table` has a property that prevents it: `[lazyLoadOnInit]="false" ` .  But it doesn't seem like virtual scroller has that and I can't find a way to prevent it.

Here is a full example of a working `<p-virtualScroller>` but it loads the first 10 rows *twice*:

home.component.html: 
```html 
             <p-virtualScroller
              [value]="virtualContacts"
              scrollHeight="500px"
              [itemSize]="150"
              [rows]="10"
              [lazy]="true"
              (onLazyLoad)="lazyLoadContacts($event)">

                <ng-template pTemplate="item" let-contact>
                  <div class="columns is-vcentered is-flex contact-info">

                    <div class="column is-6">
                      <p class="is-size-5">
                        Name: {{contact.name}}
                      </p>
                      <p class="is-size-5">
                        Email: {{contact.email}}
                      </p>
                    </div>

                    <div class="column is-6">
                      <p class="is-size-5">
                        Phone: {{contact.phone}}
                      </p>
                      <p class="is-size-5">
                        Address: {{contact.address}}
                      </p>
                    </div>
                  </div>
                </ng-template>

                <ng-template let-contact pTemplate="loadingItem">
                    Loading...
                </ng-template>
              </p-virtualScroller>
```

home.component.ts: 
```typescript 
ngOnInit() {
    this.contactService.getContactCount().subscribe(res => {
      this.contactCount = res;
      this.virtualContacts.length = this.contactCount;
    })
  }

  lazyLoadContacts(event: LazyLoadEvent): void {
    this.contactsPageNumber = event.first <= 10 ? 1 : this.contactsPageNumber + 1;

    this.contactService.getPagedContacts(this.contactsPageNumber, event.rows).subscribe(contacts => {

      this.contacts = contacts;
      this.loadedContacts = this.contacts;

      Array.prototype.splice.apply(this.virtualContacts, [...
      [event.first, event.rows], ...this.loadedContacts]);

      this.virtualContacts = [...this.virtualContacts];
    });
  }
```

contact.service.ts: 
```typescript
getContactCount(): Observable<object> {
    const url = `${this.baseUrl}/count`;

    return this.http.get(url);
  }

  getPagedContacts(pageNumber: number, pageSize: number) {
    const httpParams: HttpParams = new HttpParams()
    .set('pageNumber', pageNumber.toString())
    .set('pageSize', pageSize.toString());

    const httpOptions: object = {
      params: httpParams,
      responseType: 'json'
    }

    return this.http.get<Contact[]>(this.baseUrl, httpOptions);
  }
```

**Comment by mfish0005** [comment]
To anyone that finds this post with a similar problem here's a hacky workaround until p-virtualScroller has an option not to fire the lazy load event twice when the component loads:  

I added a workaround in my API that makes page 0 = page 1, page 10 = page 2, page 20 = page 3, etc.

So basically my urls now look like this: http://localhost:1234/contacts?pageNumber=30&pageSize=10.  That will return the 4th page of results from the db containing 10 items.  

I then changed my `lazyLoadContacts()` function to use `event.first` as the page number in my  `getPagedContacts(event.first, event.rows)` call.  Full lazy load method is now: 
``` lazyLoadContacts(event: LazyLoadEvent): void {
    this.contactService.getPagedContacts(event.first, event.rows).subscribe(contacts => {
      
      this.contacts = contacts;

      this.loadedContacts = this.contacts;

      Array.prototype.splice.apply(this.virtualContacts, [...
      [event.first, event.rows], ...this.loadedContacts]);

      this.virtualContacts = [...this.virtualContacts];
    });
  }
```

This is obviously a sub-optimal solution but it does work...although it won't work if you don't have the option to modify the API you're calling.  It wouldn't be necessary at all if primeNG's lazy load event didn't fire twice `onLoad`.  I wouldn't mind opening a PR to address this if someone wants to point me in the right direction...

**Comment by tiagomartins91** [comment]
Confirm! I have the same problem.. A small tricky fix for my side without BE changes.

Waiting for a fix on the 10 release version.

```
loadData(event) {

    const requestPage = event.first / event.rows;

    const nextPage = requestPage > 0 ? requestPage + 1 : 0;

    if (nextPage < requestPage) {
      return;
    }

    this.restService.queryUserProducts({ page: requestPage, per_page: 10 }).subscribe(
      (res: HttpResponse<any[]>) => {
        this.hotProducts = res.body;
        this.filteredHotProducts = this.hotProducts;
      },
    );
  }
```

**Comment by cagataycivici** [comment]
Can't replicate with 10.0.0-rc3, yes onLazyLoad is called twice on page load however, it loads the next page as well for smooth scrolling so it is by design not to await the user. In first call, event.first should be 0, in second one it should be first + rows.

Please create a new ticket with a reproducible demo if issue still persists for you.
