### ISSUE TITLE
I would like to know the intention of converting scss variables to css variables

### ISSUE THREAD

**Issue by fernandocode** [primefaces/primeng#9081]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
variables scss

**Expected behavior**
[variables css](https://developer.mozilla.org/pt-BR/docs/Web/CSS/var)

**What is the motivation / use case for changing the behavior?**

I looked at the roadmap and saw that if there are flat plans for "Smaller primeng.css", I would like to know if there is any conversation behind the scenes for the use of [css variables](https://developer.mozilla.org/pt-BR/docs/Web/CSS/var) which is more flexible than the SASS variables, and which would also allow you to change themes without having to change the css file with today, with pre-compiled files css for the available themes.
Not to mention other facilities like the use in custom components the same colors used in the components of the primeng (which is very complicated as it is, if I was wrong please let me know, as I have this need), I saw that this is practically impossible using style/styleUrls.
Another facility would be to be able to have more control over the exchange of each variables, individually.

I would like to know the plans for this, as it seems to me something very important to maintain the flexibility of using the theme. Today we are designing the use of the Ultima theme, but we are evaluating the integration with our existing components, mainly the issue of the current colors theme.

**Comment by cagataycivici** [comment]
Please use forum for questions and support requests, thank you.
