### ISSUE TITLE
with pSortableColumn and onLazyLoad (server side sorting) only one call is made instead of two

### ISSUE THREAD

**Issue by middoors** [primefaces/primeng#9082]
**I'm submitting a bug report:

**Current behavior**
After clicking on the header, the sorting emits just one event. This event asks the server to sort the data, but since there are "first" and "rows" properties then only that specific chunk of data is requested and the server serves up the UI with that part only.

**Expected behavior**
After clicking on the header, the sorting should emit two events as if it is a new report being loaded. This way the right amount of data would be asked from the server to display.

Environment:

- Windows 10
- VS Code
- Angular 9

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
