### ISSUE TITLE
Trigger onClose event when click close button in the DynamicDialog

### ISSUE THREAD

**Issue by GavinWu1991** [primefaces/primeng#9083]
I'm submitting a ...

[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Bug Report**
https://stackblitz.com/edit/primeng-dynamicdialog-demo-bsdvt1

**Current behavior**
When users click "X" icon in a dynamic dialog, the `onClose` event does not trigger.

**Expected behavior**
When users click "X" icon in a dynamic dialog, the `onClose` event should be triggered with an empty event object.

**Environment**
Angular version: 9.1
PrimeNG version: 9.1
Browser: Chrome, Edge, Firefox

Language: all

Node (for AoT issues): node --version = 10.16.0

**Comment by GavinWu1991** [comment]
This issue may caused by `DynamicDialogComponent.close` method does not trigger `onClose` event, but only sets the current dialog to invisible. I will commit for fixing this issue.

**Comment by lenichols** [comment]
this is still broken. inClose does nit. emit any event.

**Comment by rolivares** [comment]
same here, any workaround abot this?

**Comment by tirthgodhni98** [comment]
I want close event of dialog box without closing dialog box , I want to prevent closing dialog , Any Idea ???

**Comment by shubhu2893** [comment]
Any updates on this above request. I am also looking for an event which will get triggered when we click on close(X) button on dynamic dialog prime ng

**Comment by Devorah-S** [comment]
Is there a way to prevent the dialog box from closing out onClick of 'X'.

**Comment by vohrahul** [comment]
Is it still not working? Default close button is triggering `onClose` event. However, if we do `this.ref.close()`, this doesn't trigger onClose?

**Comment by kormanm** [comment]
Same question as @vohrahul
