### ISSUE TITLE
[TriStateCheckbox] Keyboard gets opened on mobile devices on use

### ISSUE THREAD

**Issue by KlausHans** [primefaces/primeng#9085]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report
[ ] feature request
[ ] support request 
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/primeng-tristatecheckbox-demo

**Current behavior**
If i use the tristate checkbox on a mobile touch device, the virtual keyboard is opened every time.

**Expected behavior**
If i use the tristate checkbox on a mobile touch device, the virtual keyboard is NOT opened every time.

**Minimal reproduction of the problem with instructions**
Open https://www.primefaces.org/primeng/showcase/#/tristatecheckbox on a mobile device and use the checkbox. iOs or Android should not matter.

**What is the motivation / use case for changing the behavior?**
The keyboard adds no value, instead it's very annoying and covers content.

**Please tell us about your environment:**
Shouldn't matter as the issue is present in your own documentation/demo

* **Angular version:** 9

* **PrimeNG version:** 9

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Mobile Firefox (Android) and mobile Safari (iOS) at least.

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
Fixed via PR, thanks.
