### ISSUE TITLE
Dynamically changing the button (pButton directive) label via ngx-translate overwrites the styles class.

### ISSUE THREAD

**Issue by NVS89** [primefaces/primeng#9086]
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already
[ ] support request => Please do not submit support request here, instead see

**Current behavior**
Dynamically changing the button (pButton directive) label via ngx-translate overwrites the styles class.

**Expected behavior**
custom css classes should not be overwritten

**Minimal reproduction of the problem with instructions**

- create project with lazy loaded module (SharedModule)
- add instance of the translation service in your injector tree of main module with TranslateModule.forRoot()
- add instance of the translation service in your injector tree of SharedModule with TranslateModule.forChild()
- start project
- check "set label": 
      first invoke set empty label (label = '');
      second provide new value of label and  this.setStyleClass() method overwrite custom css classes;

**Please tell us about your environment:**
**Dependencies**
```
  "dependencies": {
    "@angular/animations": "~9.1.12",
    "@angular/cdk": "^9.2.4",
    "@angular/cli": "^9.1.12",
    "@angular/common": "~9.1.12",
    "@angular/compiler": "~9.1.12",
    "@angular/core": "~9.1.12",
    "@angular/forms": "~9.1.12",
    "@angular/platform-browser": "~9.1.12",
    "@angular/platform-browser-dynamic": "~9.1.12",
    "@angular/router": "~9.1.12",
    "@aspnet/signalr": "^1.1.2",
    "@fortawesome/fontawesome-free": "^5.14.0",
    "@ngrx/effects": "^9.2.0",
    "@ngrx/store": "^9.2.0",
    "@ngx-translate/core": "^13.0.0",
    "@ngx-translate/http-loader": "^6.0.0",
    "@types/fhir": "0.0.30",
    "core-js": "^3.2.1",
    "jwt-decode": "^2.2.0",
    "lodash": "^4.17.19",
    "moment": "^2.27.0",
    "ngx-matomo": "^0.1.4",
    "ngx-pipes": "^2.7.5",
    "primeflex": "^1.3.1",
    "primeicons": "^4.0.0",
    "primeng": "^9.1.3",
    "rxjs": "^6.6.0",
    "tslib": "^1.10.0",
    "webdatarocks": "^1.2.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.12",
    "@angular/compiler-cli": "^9.1.12",
    "@angular/language-service": "^9.1.12",
    "@ngrx/store-devtools": "^9.2.0",
    "@types/jasmine": "^3.5.11",
    "@types/jasminewd2": "^2.0.8",
    "@types/lodash": "^4.14.158",
    "@types/node": "^12.11.1",
    "chance": "^1.1.6",
    "codelyzer": "^5.1.2",
    "cypress": "^3.8.3",
    "husky": "^3.1.0",
    "jasmine-core": "^3.6.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^4.4.1",
    "karma-chrome-launcher": "^3.1.0",
    "karma-coverage-istanbul-reporter": "^2.1.1",
    "karma-edge-launcher": "^0.4.2",
    "karma-firefox-launcher": "^1.3.0",
    "karma-ie-launcher": "^1.0.0",
    "karma-jasmine": "^2.0.1",
    "karma-jasmine-html-reporter": "^1.5.4",
    "protractor": "^5.4.4",
    "sonar-scanner": "^3.1.0",
    "ts-node": "^8.10.2",
    "tslint": "^5.20.0",
    "typescript": "3.8.3"
  },
```
**main module:**
```
// AoT requires an exported function for factories
export function HttpLoaderFactory(http: HttpClient) {
    return new TranslateHttpLoader(http, './assets/i18n/general/', '.json');
}
@NgModule({
    declarations: [
        AppComponent
    ],
    imports: [
        TranslateModule.forRoot({
            loader: {
                provide: TranslateLoader,
                useFactory: HttpLoaderFactory,
                deps: [HttpClient]
            }
        }),
...........................
```
**shared module:** 
```
// AoT requires an exported function for factories
export function HttpLoaderFactory(http: HttpClient) {
    return new TranslateHttpLoader(http, './assets/i18n/share/', '.json');
}


@NgModule({
    imports: [
        ButtonModule,
        TranslateModule.forChild({
            loader: {
                provide: TranslateLoader,
                useFactory: HttpLoaderFactory,
                deps: [HttpClient]
            },
            isolate: true
        }),
    ],
    exports: [
        TranslateModule
    ]
})
```

**Comment by bschnabel** [comment]
Hey, it has nothing todo with ngx. I had the same problem. it's a bug in primeng9.

I could find to options to solve it:

1. *Use p-button element instead of pButton directive.*
See https://stackblitz.com/edit/pbuttonbug

2. update to angular10 and primeNg 10.
There it has been fixed. See: https://stackblitz.com/edit/github-q7ygre

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
