### ISSUE TITLE
Autoscrolling with pInputTextarea with `autoResize` when 2 or more textareas on the page.

### ISSUE THREAD

**Issue by medcenter24** [primefaces/primeng#9087]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When the page has 2 elements `pInputTextarea` with `autoResize` property enabled. Make the page so large to have scroll, then place cursor to any of textarea and enter any symbol: after that page will be autoscrolled and it is really confusing behaviour, you don't see the element where you're trying to enter the text.

**Expected behavior**
no autoscrolling on the textarea changing

**What is the motivation / use case for changing the behavior?**
`autoResize` doesn't work when you have more than 1 element on the page.

**Please tell us about your environment:**
any environment, chrome browser

* **Angular version:** 5.X
Angular 10

* **PrimeNG version:** 5.X
Primeng 9.1.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript es6 es5

* **Node (for AoT issues):** `node --version` =   
no AoT

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
