### ISSUE TITLE
Alternatives to PositionLeft PositionTyp (p-dialog)

### ISSUE THREAD

**Issue by TheILPlace** [primefaces/primeng#9089]
as per #8730  These properties of the p-dialog were deprecated.
what are the alternatives to open the dialog in a very specific location (the new position property is not good enough)

**Comment by jorgematosa** [comment]
I'd also like to know this. I don't think these properties can be removed until there's a viable solution.

**Comment by jorgematosa** [comment]
I wonder if a viable alternative was created for this issue. As for version 11 of primeng the positionLeft and Top and still deprecated

**Comment by greardrear** [comment]
So, still no updates on this?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
