### ISSUE TITLE
Color Picker

### ISSUE THREAD

**Issue by garethlewis** [primefaces/primeng#909]
Is there a timeline of when the team will be able to port the ColorPicker from Primefaces over to PrimeNG?  I'm using the angular2-color-picker at the moment but it does have some odd behaviours, and causes tsc to throw a fit when using outDir

**Comment by cagataycivici** [comment]
In our near future plans.

**Comment by cagataycivici** [comment]
Available for 4.1.RC1.
<img width="245" alt="screen shot 2017-06-03 at 12 49 29" src="https://cloud.githubusercontent.com/assets/686247/26752781/6bb49e5a-4860-11e7-8a05-da82195b9782.png">
