### ISSUE TITLE
Migrate to PrimeOne Design Architecture

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#9094]
Migrate PrimeNG to new PrimeOne Design of PrimeTek that is utilized by PrimeVue and PrimeReact, this will unify the styling of our libraries and make maintenance easier.

Note that this is a breaking change and as PrimeOne uses the p-* prefix for the styles instead of the legacy ui-* PrimeNG 9 and older has.

**Comment by woppa684** [comment]
@cagataycivici Can this please be marked as a breaking change in the CHANGELOG as well? We tried to upgrade to version 10 and then our entire custom theme broke (of course). Looking through the changes this came as a bit of a surprise. Also, is there a specific method of updating our theme that should work? Just global search and replace? Is there, or will there be, an upgrade guide?

**Comment by canyetim** [comment]
@cagataycivici  I also need a comprehensive upgrade guide. What should we do to switch to primeone?
