### ISSUE TITLE
Dropdown should select first filtered item when typing 

### ISSUE THREAD

**Issue by davidsramos** [primefaces/primeng#9110]
I'm submitting a ... (check one with "x")

[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Stackblitz**
[https://stackblitz.com/edit/primeng-issue-first-filtered-item-issue](https://stackblitz.com/edit/primeng-issue-first-filtered-item-issue)

**Current behavior**
Dropdowns do not allow typing to select items like a normal html select does. Filtering helps, but it still does not select the first filtered item for you when starting to type

**Expected behavior**
Dropdowns should allow typing to select items, and default to the first item of that letter. For instances if I have Ab, Ac, Ad, Bb, Bc in a dropdown as options, I should be able to type Ac and it picks that one for me, like a normal select html dropdown would. When using filters, it filters it down, but I still have to do another mouse click or use arrow keys to select which one. I would love for it to automatically select and set it for me.

**Minimal reproduction of the problem with instructions**
see Stackblitz

**What is the motivation / use case for changing the behavior?**
User suggestion to minimize the amount of clicks required to perform their job. Our users operate quickly and any extra clicks or key strokes hinder their production.

**Please tell us about your environment:**
N/A

- Angular version: 10.0.7
- PrimeNG version: 9.1.3
- Browser: all
- Language: all
- Node (for AoT issues): n/a

**Comment by SDVII** [comment]
This is also something I've been trying to achieve for a while now. So far, I've come up with the following:

in `select.component.ts`:
```js
import { Component, Input, ViewChild, EventEmitter, Output, HostListener } from '@angular/core';
import { Dropdown } from 'primeng';

@Component({
    selector: 'app-select',
    templateUrl: './select.component.html',
    styleUrls: ['./select.component.scss'],
})

export class SelectComponent {
    @ViewChild('input') input: Dropdown;

    @Output() onFilter = new EventEmitter<any[]>();

    currentFilter = '';

    constructor() { }

    /**
     * Handle filter detection because PrimeNG Dropdown doesn't support it
     *
     * @param {KeyboardEvent} event
     * @memberof SelectComponent
     */
    @HostListener('keyup')
    onKeyUp() {
            if (this.currentFilter !== this.input.filterValue) {
                this.currentFilter = this.input.filterValue;
                this.onFilter.emit(this.input.optionsToDisplay)
            }
    }
}
```

and in the parent component something like this:
```js
this._subs$.add(this.debouncer
            .pipe(debounceTime(600))
            .pipe(filter(searchRes => !!searchRes && searchRes.length > 0))
            .subscribe((searchRes) => {
                this.control.setValue(searchRes[0].value);
}));
```

I am using debounce in order to avoid too many events, then I am setting the value automatically.
With that being said, there are issue with this method. It clears the filter after assigning the value and it doesn't focuses the selected value correctly either for Enter event
