### ISSUE TITLE
Ripple effect is not working

### ISSUE THREAD

**Issue by diegoarantes** [primefaces/primeng#9111]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Stackblitz**
https://stackblitz.com/edit/primeng-bug-ripple

**Current behavior**
When apply ripple effect the buttons, it is not working.

**Please tell us about your environment:**

* **Angular version:** 10.0.7

* **PrimeNG version:** 10.0.0-rc.1

* **Browser:** all

**Comment by fattazzo** [comment]
Confirm, same situation

- Angular version: 10.0.7
- PrimeNG version: 10.0.0-rc.1
- Browser: all

**Comment by cagataycivici** [comment]
Try with RC2 please.

**Comment by likwidgames** [comment]
Still not working as of RC3

**Comment by ragusmech** [comment]
Make sure you are import and mention the ripple module in you app.module.ts file.

Can you please refer the  [Link](https://primefaces.org/primeng/showcase/#/button)

 [Reference Image to find the solution](https://i.stack.imgur.com/KuU93.png)
