### ISSUE TITLE
[TreeNode] Add selected property

### ISSUE THREAD

**Issue by RepentAndBelieveTheGospel** [primefaces/primeng#9112]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**What is the motivation / use case for changing the behavior?**

I found myself several times in the situation where I need to know  if a TreeNode is selected and I have to search through the selected nodes to see if it's present there. Example:

File upload component has total selected files property which is used for additional logic. When removing a node, I have to check if it is selected, so instead of checking a selected property on the TreeNode, I have to use one of the JS methods on the selected nodes to check if the TreeNode is there.

! This has nothing to do with the selectable property, which is used to disable the select functionality for a TreeNode.

**Comment by axell9641** [comment]
Sorry to bother you, but since you mention node selection, do you happen to know how to deselect a node programatically ?

**Comment by misterjaffacakes** [comment]
> Sorry to bother you, but since you mention node selection, do you happen to know how to deselect a node programatically ?

No bother at all. You have to remove the node from the selected nodes array (the property you bind to **[(selection)]**). So just use one of the methods for removing a value from an array (like filter or indexOf with splice).

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
