### ISSUE TITLE
p-treeTable cell editing: onEditComplete not triggered when clicking other cells.

### ISSUE THREAD

**Issue by gkalmar** [primefaces/primeng#9113]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
The issue is very similar to #8049. The only difference is the component: p-treeTable instead of p-table.
I copied the problem description and added a new stackblitz which shows the onEditComplete events in the console as they are being fired.

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/primeng-treetableedit-demo-3pp2jr

**Current behavior**
When using the event onEditComplete the event isn't triggered by using the mouse to move to another field, when you press tab or esc the onEditCancel is triggered, when you press enter the onEditComplete is triggered, but there is no event when you change to another field through mouse.

**Expected behavior**
I think onEditComplete should be triggered when stopping the edit using the mouse to move to another field or just click away.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
onEditComplete should do the same as in p-table.

**Please tell us about your environment:**
not relevant

* **Angular version:** 9.0.4

* **PrimeNG version:** 9.1.0

* **Browser:** all
 
* **Language:** all

* **Node (for AoT issues):** `node --version` =

**Comment by Fakerinc** [comment]
This issue does not seem to be resolved

**Comment by ThoSap** [comment]
Nope, it is not :(

**Comment by gayatriraichandani** [comment]
Still not resolved.. :(

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by mohammadaajo** [comment]
I have the same issue on 15.4.1.
