### ISSUE TITLE
Safari mobile iOS can't swipe right when position thrid...

### ISSUE THREAD

**Issue by henrytran9x** [primefaces/primeng#9115]
Hi I used primeNG which intested for my. But I had issues for mobile iOS in component [Cousel](https://www.primefaces.org/primeng/showcase/#/carousel) . When item stay postion third I can't swipe right to continue.

Anyone had issues same me ?

**Comment by yigitfindikli** [comment]
Issue is not clear, please feel free to reopen with a stackblitz example.
