### ISSUE TITLE
unwanted reordering by scrolling up and down

### ISSUE THREAD

**Issue by middoors** [primefaces/primeng#9117]
[ x ] bug report => Search github for a similar issue or PR before submitting

There is a strange behavior with the PrimeNG table. It reorders as I scroll up and down. You can even see this on the PrimeNG website [Here](https://primefaces.org/primeng/showcase/#/table/virtualscroll). If you look closely you see that every time you scroll up and back down again, there is a different item at the bottom of the page. This is happening even when all data or at least that portion of the table is already fetched and cached in the table's memory.

![unwanted reordering](https://user-images.githubusercontent.com/68664559/89283802-149f5180-d64e-11ea-8062-48b388536f6e.gif)

**Current behavior**
The PrimeNG table with lazy loading and virtual scrolling enabled reorders the table as I scroll up and down to the bottom of the table. BUT this works fine in the Stackblitz sample. When I integrate the table into my application, it again reorders unexpectedly like on the PrimeNG website.

**Expected behavior**
The table should not reorder once the data are cached and not fetched anymore even when it is integrated into an application.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
