### ISSUE TITLE
Table Header - No border in Firefox/Edge if resize is enabled

### ISSUE THREAD

**Issue by projectX21** [primefaces/primeng#9118]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://www.primefaces.org/primeng/showcase/#/table/colresize
It appears with all themes but best to recognize is nova.

**Current behavior**

The table header cells have no border in Firefox / Edge. In Chrome it works as aspected.

**Expected behavior**

The table header cells should have a border as in v9.1.3

**Minimal reproduction of the problem with instructions**

**Comment by bjansen** [comment]
Confirmed in v10 as well, for example on https://www.primefaces.org/primeng/v10.0.5-lts/#/table/colresize.

Here's how it looks in Firefox:

![image](https://user-images.githubusercontent.com/281528/100363515-2477e280-2ffd-11eb-810e-8e7e4cd97ab8.png)

And in Brave:

![image](https://user-images.githubusercontent.com/281528/100363474-14600300-2ffd-11eb-8d88-4e1548043caf.png)

**Comment by bjansen** [comment]
Bottom and right borders reappear when I uncheck `position: relative` from the `.p-datatable-resizable .p-resizable-column` rule in the web inspector.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
