### ISSUE TITLE
TimePicker - Formatting is broken

### ISSUE THREAD

**Issue by projectX21** [primefaces/primeng#9119]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://www.primefaces.org/primeng/showcase/#/calendar

**Current behavior**

The time picker has some visibility problems.

**Expected behavior**

**Minimal reproduction of the problem with instructions**

Click on "Time only"

**Comment by benjamindobravec** [comment]
Calendar Time component is showing 3 '<' characters and 2 ':', which shouldnt be there.
PrimeNG version 10.0.0-rc.2.

**Comment by benjamindobravec** [comment]
![prine_ng_10_time](https://user-images.githubusercontent.com/9054763/89624910-435c3880-d897-11ea-8051-e2a2df8ff4e0.png)

**Comment by cagataycivici** [comment]
#9195
