### ISSUE TITLE
panel and accordion cannot close after upgrade to angular2 2.0.0 version

### ISSUE THREAD

**Issue by BTC2014** [primefaces/primeng#912]
after I upgrade to angular2 2.0.0 version
i tried with panel, when I un-select the panel, the content will not disappear, it will show over the other content.
 <p-panel header="Dashboard" [toggleable]="true" [collapsed]=panelCollapsed (onBeforeToggle)="onToggle()">
            <div>...</div>
</p-panel>

same thing also happen with accordion tab. first tab will not close and show over the second tab. 

I use angular2-seed project to build.

**Comment by garethlewis** [comment]
I have upgraded my project from RC.5 to the final release of 2.0.0, where final is used loosely by Google, and have not had any problems with those components.  They render fine.

Out of interest, what browser are you using and what messages, if any do you get in the console output of the developer tools?

**Comment by BTC2014** [comment]
I am using chrome and it did not show any message in the console.

**Comment by garethlewis** [comment]
I think your problem lies with the angular2-seed project.  Angular 2 isn't the issue and I built my project from scratch.

**Comment by BTC2014** [comment]
which part of component make the content hide? maybe css is not working right.

**Comment by BTC2014** [comment]
do a fix in css solve this issue
.ui-accordion-content-wrapper.ui-accordion-content-wrapper-overflown {
	overflow: hidden;
}

it seems the overflow property is missing.

**Comment by cagataycivici** [comment]
I guess you still use old resources from PrimeUI, you need to include css from PrimeNG instead as we don't use PrimeUI anymore in PrimeNG.

```html
<link rel="stylesheet" type="text/css" href="/node_modules/primeng/resources/themes/omega/theme.css" />
<link rel="stylesheet" type="text/css" href="/node_modules/primeng/resources/primeng.min.css" />
```

**Comment by BTC2014** [comment]
after i use css from PrimeNG, css/fonts/roboto-v15-latin-regular.ttf 404 (Not Found)
I did not find this font from primeng folder. 
where can i find this font?

**Comment by ils-Priyesha** [comment]
use ngx-bootstrap accordian
