### ISSUE TITLE
IE 11 Example Page: Some components doesn't work as expected

### ISSUE THREAD

**Issue by projectX21** [primefaces/primeng#9120]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://primefaces.org/primeng/showcase/#/autocomplete

https://www.primefaces.org/primeng/showcase/#/toast

**Current behavior**

At first I want to say that the page isn't shown correctly in IE 11. The font family for example isn't right and the theme selection dialog is transparent (So is the navigation bar).

The autocomplete  for example doesn't show the correct results if the search string gets changed. For example in the basic one:
type 'alb' and Albania gets found (which is correct). But if you remove the lb and type it again, Andorra gets found amongst other countries which shouldn't be displayed.

The accordion animation doesn't work as expected, because the text overflows on expanding/collapsing.

Toast: If you click the success toast three times, one of them can't be removed.

**Expected behavior**

All problems can be repuduced in IE 11 in the showcases.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
