### ISSUE TITLE
Unable to close p-messages on Firefox

### ISSUE THREAD

**Issue by fingust** [primefaces/primeng#9123]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Not necessary, bug can be reproduced in official documentation. 
https://www.primefaces.org/primeng/showcase/#/messages

**Current behavior**
Unable to close message box (p-messages component) - X button does nothing, neither does clearing the array in ts.

**Expected behavior**
Messages would be able to close.

* **PrimeNG version:** 10.0.0-rc1

* **Browser:** [Firefox 79.0 ]

**Comment by leandrofaria** [comment]
Doesn't work correctly on Microsoft Edge either. Same issues as mentioned by @fingust 

- PrimeNG version: 10.0.0-rc1
- Microsoft Edge 44.19041.423.0
