### ISSUE TITLE
Primeng input number min and max not working on V10.0.0-rc.1

### ISSUE THREAD

**Issue by sreejithrkylm** [primefaces/primeng#9124]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
``` I have updated primeng form 9.0.0 to V10.0.0-rc.1 input number min and max was working on v9.0.0 but when I updated to v10 it is not working
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**

user can enter beyond the limit of max, min
**Expected behavior**

User should not cross the limit of min and max
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.X

Angular 9.1
* **PrimeNG version:** 5.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by sreejithrkylm** [comment]
![image](https://user-images.githubusercontent.com/36000928/89383787-bee4ab00-d71a-11ea-9c99-f42de5cb67ce.png)

**Comment by sreejithrkylm** [comment]
Any update on this?

**Comment by mertsincan** [comment]
Hi,

This is an expected behavior in the current structure. The value is validated when you click out. Please see details;
https://github.com/primefaces/primeng/issues/9223

You can use onInput event for this issue;
```
//ts
onInput(event) {
        let newValue = event.value;
       /* Maybe you can add your validation code in this event. Exp; */
        if (newValue < -100000) {
            newValue = -100000;
        }
        else if (newValue > 100000) {
            newValue = 100000;
        }
        /****/

        this.value = newValue;
    }

//html
<p-inputNumber [(ngModel)]="value" [min]="-100000" [max]="100000" (onInput)="onInput($event)"></p-inputNumber>
```

Best Regards,
