### ISSUE TITLE
inputNumber with numeric prefix is not working as expected

### ISSUE THREAD

**Issue by stephanecot** [primefaces/primeng#9125]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
With primeng version 9 & 10.
Impossible to have any number in prefix property.
By exemple, I wanted to have (+33) in prefix (for phone number) but it doesn't work at all:

- Impossible to type the number 3

- the cursor is missplaced

- the typing is inversed

**Comment by maicongodinho1** [comment]
@stephanecot do you have a stackblitz example or github repo with the problem?

**Comment by stephanecot** [comment]
Sorry I was on holiday with no computers... I am back...

For the stackblitz, I just fork yours:
https://stackblitz.com/edit/primeng-inputnumber-demo-waa6xv?file=src%2Fapp%2Fapp.component.html

I change the prefix in:

        <div class="p-col-12 p-md-3">
            Percent
            <p-inputNumber [(ngModel)]="value14" prefix="+33">
            </p-inputNumber>
        </div>

If, I set +33:
- I can't type "3"
- When I type another, the cursor is missplaced

**Comment by mertsincan** [comment]
Thanks a lot @stephanecot, I'll check and get back to you.

Best Regards,

**Comment by vstiebe** [comment]
Hello! On v10 final the typing behaviour is better. Thanks for improving it a lot. 
But I found one last issue. Maybe is as designed.
Tested on https://www.primefaces.org/primeng/showcase/#/inputnumber on Windows 10 with Chrome.

If you select all field value and clear it with a backspace or a delete button. The cursor stay behind the first character when typing.
So when select all value and clearing with backspace or delete and typing 123 we get:
* United States - $231,00
* Germany - 123,00 €
* India - INR 321.00
* Japan - ¥231

On United States and India field, if I position the cursor at the end of value and clear it with various backspace keystrokes, the mask isn't cleared like the Germany field. So it is odd that a zero stays in front of typing.

On Japan field, the mask is cleared, but it behaves like the select all clear with delete.

**Comment by mertsincan** [comment]
Hi @vstiebe,

Sorry for the delayed reply. I just noticed your message. Your issue has been fixed in https://github.com/primefaces/primeng/issues/9372

Best Regards,

**Comment by AFFIN-vblazquez** [comment]
Hello!
With primeng version 17.18.8 and angular version 17.3.11 it is impossible to have any number in the prefix property.
For example, I wanted to have (0) in prefix (for hours 00) but it doesn't work at all:

Impossible to type the number 0

Example:
    <p-inputNumber [(ngModel)]="value1" prefix="0">
    </p-inputNumber>

If, I set 0:
I can't type "0"

Best Regards
