### ISSUE TITLE
KeyFilter: On paste, invalid chars should be ignored instead of preventing paste

### ISSUE THREAD

**Issue by Jonas-Marty** [primefaces/primeng#9126]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Behavior can bee tested in the docs: https://www.primefaces.org/primeng/showcase/#/keyfilter
Lines in SourceCode: https://github.com/primefaces/primeng/blob/master/src/app/components/keyfilter/keyfilter.ts#L187-L199

**Current behavior**
If clipboard content does not match the regex (e.g. `12'345.67` for builtin `num`), pasting is prevent completely. (`12345.67` works)

**Expected behavior**
Occasionally, my clients copy a number from a document or website formatted with a thousand separator (e.g. `'` or `,`, depending on region) and want to paste them to a field protected with `pKeyFilter="pnum"`.  The key filter should only remove invalid chars instead of preventing the paste completely.
Optionally this behavior could be enabled with an attribute e.g. `pasteBehavior="default || removeInvalidChars"`

**Minimal reproduction of the problem with instructions**
Copy `12'345.67` and try to paste it into a `pKeyFilter="pnum"` protected filed.

**What is the motivation / use case for changing the behavior?**
Better usability.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
