### ISSUE TITLE
Menubar not working on mobile devices

### ISSUE THREAD

**Issue by diegoarantes** [primefaces/primeng#9127]
**I'm submitting a ...** 
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
Menu does not show the 'hamburger menu' on mobile devices
![image](https://user-images.githubusercontent.com/5193643/89420176-b8e5ce80-d708-11ea-85b1-34880f99a618.png)

**Expected behavior**
See in Primevue
![image](https://user-images.githubusercontent.com/5193643/89420373-fe0a0080-d708-11ea-90d8-b9fed4703fce.png)

* **Angular version:** 10.X

* **PrimeNG version:** 10.0.0-rc.1

* **Browser:** all

**Comment by PHuhn** [comment]
Hey:
I am hoping that this fixes an issue that I am having where when I decrease the screen size to 864px, the menu virtually disappears (becomes about 30px tall with no menu items).  Please update the docs per the new mobileActive property and how to use it.

**Comment by certifirm** [comment]
Hamburguer is not shown under 960px with 10.0.0-rc.3

**Comment by PHuhn** [comment]
PrimeNG 10.0.0-rc.4 fixed it for me.
