### ISSUE TITLE
Drag and Drop : onDrop and onDragOver don't fire when using camelCase in pDraggable / pDroppable attributes

### ISSUE THREAD

**Issue by An0d** [primefaces/primeng#913]
Hi,

After struggling with onDrop and onDragOver events which did not fire. I noticed that when I used
`pDraggable="draggableObject"` and `pDroppable="draggableObject"` then `onDrop` and `onDragOver` events did not fire.

After debugging I noticed that in "dragdrop.js" the `allowDrop` function was comparing `draggableobject` with `draggableObject` and returned false. Then onDrop and onDragOver don't fire.

When using only lower case characters in pDraggable and pDroppable, onDrop and onDragOver events properly fire.

Kind regards

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/VZbdZfQ7SuTV87tTkbYR

**Comment by dhakehurst** [comment]
So,
the example panel / drag-drop does not work!

http://plnkr.co/edit/CbgnVfs6SuMgnuXe46jf

whats wrong
