### ISSUE TITLE
Dropdown option Accessibility Issue.

### ISSUE THREAD

**Issue by mahip-bhatt** [primefaces/primeng#9130]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
** NVIDIA works best with Chrome, While Narrator works best with Edge. So, we use these tools specific to browsers.
1. When we use Windows 10 Narrator on Edge browser the drop-downs the options are narrated as “Option contains 0 items”.
2. The Enter key and the arrow keys doesn't work for accessibility when using NVIDIA tool on Chrome.
3. While using the Narrator the Enter doesn't work when focus is on the drop-down we have to use the arrow key to go to the expand icon and then enter works.

**Expected behavior**
1. When we use Windows 10 Narrator on Edge browser the drop-downs the options should be narrated as “Option 1 of 5” or something like that.
2. The Enter key and the arrow keys should work when using NVIDIA tool on Chrome.
3. While using the Narrator the Enter should work when focus is on the drop-down.
We have been following https://www.w3.org/TR/wai-aria-practices-1.1/#Listbox to validate the drop-down accessibility.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
By getting this fix the Narrator user or NVIDIA user can access the tool seamlessly.

**Please tell us about your environment:**

* **Angular version:** 5.X
Angular 8

* **PrimeNG version:** 5.X
PrimeNG 9.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Mentioned already.
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by capivaramu** [comment]
I have same problem .....
This problem have a solution or need change component?

**Comment by sachinkaralay** [comment]
I face the same issue, is there any resolution?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
