### ISSUE TITLE
Primeng input number not updating (onchange) on V10.0.0-rc.1

### ISSUE THREAD

**Issue by stephanecot** [primefaces/primeng#9132]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://primeng-inputnumber-demo-caoz8h.stackblitz.io

**Current behavior**

When using p-inputNumber, the value type in the input is not "updated" in the model on typing.
We must "foscuout" to update the value.
Work in the 9.x version
`
  <p-inputNumber [useGrouping]="false"
                 [(ngModel)]="toto"
                 autocomplete="none"
                 placeholder="+81999999999"
                 maxlength="16"></p-inputNumber>

  {{ toto }}
`

==> toto is not updated before "clicking somewhere else"

**Comment by mertsincan** [comment]
Hi,

This is an expected behavior. The working structure of InputNumber is different. If you want to get new value every time you add a new character, please use onInput event. Please see details;
https://github.com/primefaces/primeng/issues/9223

```
//ts
onInput(event) {
   // maybe, you can add some validations
   this.value = event.value;
}

//html
<p-inputNumber [(ngModel)]="value" (onInput)="onInput($event)">
```

Best Regards,

**Comment by steigerm** [comment]
But this "different" logic also changes the default validation behaviour in Reactive Forms!
The default is 
`updateOn: 'change'`
which does not work.
Form validation only happens after the p-InputNumber field loses focus.

**Comment by oixan** [comment]
totaly agree with @mertsincan

**Comment by ffex** [comment]
Hi, yes I agree with @steigerm

**Comment by alehro** [comment]
Why the issue was closed? Look at the amount of up-votes.

**Comment by thedavidhoffman** [comment]
The proposed workaround for this has issues in Safari. On any other browser it gets you the behavior you want, but on Safari, after you type one number, you can't enter anything else in the prime control unless put focus back to the control with a mouse click.

onInput(event) {
   // maybe, you can add some validations
   this.value = event.value;
}

**Comment by PointSingularity** [comment]
Any update on this?

**Comment by childersd** [comment]
Also just came across this. I also think this component should simply respect the setting `updateOn` of the attached control.

**Comment by steigerm** [comment]
@cagataycivici @mertsincan 
Almost two years after closing as "closed this as completed" which is just wrong.
And no feedback on all the comments since then.

**Comment by childersd** [comment]
Here's a (very) dirty quickfix for those interested. Assuming the attached control is called `amount`,

```html
<p-inputNumber
  formControlName="amount"
  [min]="0"
  [max]="32767"
  (onInput)="
    form.patchValue({
      amount:
        $event.value >= 0 && $event.value <= 32767
          ? $event.value
          : form.controls.amount.value
    })
  "
></p-inputNumber>
```

This will patch the form that holds the `amount` control with every input, but only if the min/max boundaries are respected.

**Comment by steigerm** [comment]
Correct. It's a fix but really dirty.
A pity we need such dirty constructs because primeng does not want to fix the underlying issue.
When using reactive forms validators should be used and not check values (0, 32767) needed in multiple locations of the code.

**Comment by thedavidhoffman** [comment]
@mertsincan... this issue continues to have people requesting it be fixed/changed. I understand the "work around" is to use the "onInput" hook, but that causes issue in Safari that essentially breaks the p-inputNumber... after entering a single digit (in Safari), the cursor is positioned at the end of the input, any further keystrokes are not accepted as a result. This then causes me to track the cursor position and reset it, which can be flaky at best...

```
    public onInput = (e: {originalEvent: KeyboardEvent, value: any}): void => {
        
        // primeng doesn't respect the updateOn setting of the control and defaults to onBlur
        // hooking this event and setting the value if updateOn is 'change' which is the default for Reactive Forms

        // https://github.com/primefaces/primeng/issues/9132
        // https://github.com/primefaces/primeng/issues/10283

        if (!this.disabled) {
            if (!this.ngControl?.control?.updateOn || this.ngControl?.control?.updateOn === 'change') {
                
                const pInputNumber = this.viewChildInput as unknown as InputNumber;
                const input = pInputNumber.input.nativeElement;
        
                // track the current cursor position in the input
                const selectionStart = input.selectionStart;

                // update the value
                this.value = e.value;

                // in Safari, after entering a single digit, the cursor is positioned at
                // the end of the input, any further keystrokes are not accepted as a result.
                // this will reposition the cursor to allow for additional keystrokes
                setTimeout(() => {
                    input.selectionStart = selectionStart;
                });               
            }
        }
    } 
```

**Comment by damian-kociszewski** [comment]
This is clearly a bug and should be fixed

**Comment by Kombuchelada** [comment]
Risible how this ignores reactive forms properties and thats “not bug it’s a feature”.

**Comment by sdykae** [comment]
> Any update on this? This is how I go around this issue, but this does make you lose the functionality of 'maxlength':
> 
> ```
> <p-inputNumber
>     (onInput)="patchPrimeNgInputValue($event, 'input1')"
>     type="number"
>     [maxlength]="2"
>     id="input1"
>     [min]="0"
>     formControlName="input1"
> ></p-inputNumber>
> ```
> 
> ```ts
>   patchPrimeNgInputValue(event: { orignalEvent: InputEvent; value: number }, formInputName: string) {
>     this.configLayoutForm.patchValue({ [formInputName]: event.value });
>   }
> ```

good fix, for multiple inputs, thanks
