### ISSUE TITLE
components search field

### ISSUE THREAD

**Issue by Kiramuxa** [primefaces/primeng#9134]
Please return the search for components in the components section.

![component-list](https://user-images.githubusercontent.com/16748657/89611008-adb7ad80-d884-11ea-9bfb-a67c3be14e68.jpg)

**Comment by Rotzbua** [comment]
Hacker tip: press `Ctrl` and `F`   👀

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
