### ISSUE TITLE
Autocomplete for multiple="true" Selection not aligned with no css

### ISSUE THREAD

**Issue by umeshmishra099** [primefaces/primeng#9138]
Using below code . I am getting autocomplete dropdown not aligned and no css.
<p-autoComplete
          id="status-filter-id"
          name="status-filter-name"
          [minLength]="1"
          [(ngModel)]="selected"
          [suggestions]="suggestion"
          (completeMethod)="search($event)"
          (onSelect)="filter()"
          (onUnselect)="filter()"
          [multiple]="true"
          [forceSelection]="true"        >
 </p-autoComplete>

![image](https://user-images.githubusercontent.com/13854413/89654515-6235eb80-d8e6-11ea-850d-f469a84134d0.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/13854413/89654591-7ed22380-d8e6-11ea-99f8-a646791a9317.png)

* **Angular version:** 8.X

* **PrimeNG version:** ^8.1.1

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 10, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
