### ISSUE TITLE
Improve calendar tabbing behavior

### ISSUE THREAD

**Issue by Spiral1401** [primefaces/primeng#9139]
**I'm submitting a ...**  (check one with "x")
[x ] feature request

**Plunkr Case (Bug Reports)**
This is viewable on the PrimeNG Showcase/Demo page

**Current behavior**
After manually typing in a date, tabbing to the next field begins tabbing through the overlay. Users of our application are mostly data-entry folks and it breaks tab flow. It actually appears that you are never able to tab through, your tab focus just remains stuck inside the overlay. But even tabbing through would not really be workable.

**Expected behavior**
Tab key goes to the next field in the UI (tabindex=-1 on the overlay container, probably)

**Minimal reproduction of the problem with instructions**
PrimeNG Calendar Demo, type a full date in basic field, hit tab

**What is the motivation / use case for changing the behavior?**
Breaks tab navigation. I could hack something on using onShow but this is a really clumsy solution

* **Angular version:** 5.X
9.1.4

* **PrimeNG version:** 5.X
9.1.3

**Comment by Spiral1401** [comment]
It occurs to me now that maybe this is just a bug and tabbing in the overlay was never intended to begin with. If so, then... well, you know.

**Comment by digitalcraftco** [comment]
This is similar to #9136 which implemented focusTrap attribute but didn't solve the issue. 

When a date is manually entered and validates with correct format, is it possible (on tab) to close calendar overlay and tab to next input or tabIndex? And avoid having to tab through all the calendar buttons. This would support fast keyboard entry users who mostly need the visual of the calendar to verify correct day/week/date.

**Comment by cagataycivici** [comment]
Tabbing inside the overlay was added per accessibility guidelines, now down arrow moves the focus inside the overlay and tab just moves to the next field with the shift-tab going previous.
