### ISSUE TITLE
Text inside p-carousel is blurred.

### ISSUE THREAD

**Issue by sumit-matic** [primefaces/primeng#9142]
Text inside p-carousel appears blurry in chrome browser. 
primeNg version - 8.1.1
node version - 10.16.0
Language- Typescript.

**Comment by maicongodinho1** [comment]
@sumit-matic do you have a example for us?

Some stackblitz code or github repo with the problem?

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 10, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
