### ISSUE TITLE
p-inputNumber Currency only works for one digit when entered with tabulator

### ISSUE THREAD

**Issue by ProfEibe** [primefaces/primeng#9144]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Does not work in primeng showcase 9.1.3 and 10.0.0rc1

**Current behavior**
Input-caret jumps to the end after writing first digit, additional inputs are not working

**Expected behavior**
write digits before point/comma until i type point/comma and then write two digits after it.

* **PrimeNG version:**
primeng showcase 9.1.3 & 10.0.0rc1

* **Browser:** [ new Edge| Chrome | Firefox ]

**Comment by ProfEibe** [comment]
Yeah it has the same problem.

Just focus on one input and jump with tabulator into the next one (one with comma-decimal). If you now start typing new numbers it will try to add them at the end of the decimals where free space is.

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primeng/commit/1258ca4d4b7a15575fa950fc83af980f2107d3d5
Similar issue: https://github.com/primefaces/primeng/issues/8900
Thanks a lot for the feedbacks,
Best Regards,
