### ISSUE TITLE
Horizontal scroll is not working, when table data is empty

### ISSUE THREAD

**Issue by deferenty** [primefaces/primeng#9148]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-tablescroll-demo

**Current behavior**
if table data is empty (`cars2=[]`) horizontal scroll is not working.

**Expected behavior**
The horizontal scroll should work because we have column headers.

**Minimal reproduction of the problem with instructions**
Just set `cars2=[]` in line 33 of app.component.ts

**Comment by projectX21** [comment]
You can use the following:

```
        <ng-template pTemplate="emptymessage" let-columns>
        <tr>
            <td [attr.colspan]="columns.length">
                No records found
            </td>
        </tr>
    </ng-template>
```

See documentation: Table-> Documentation -> Empty Message

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
