### ISSUE TITLE
Margin right, unnecessary in the calendar title - v10.0.0-rc.3

### ISSUE THREAD

**Issue by diegoarantes** [primefaces/primeng#9149]
![image](https://user-images.githubusercontent.com/5193643/89811282-d229b900-db14-11ea-9ac8-585c8c4c379d.png)

https://github.com/primefaces/primeng/blob/59f12df6bbfdf9ac54f15e79713b80a81436b123/src/assets/components/themes/saga-blue/theme.css#L200

**Comment by cagataycivici** [comment]
It is necessary, the live demo runs in preserveWhitespaces: true mode, if you set it to false which is the default then it will be August2020 so becomes broken.

**Comment by cagataycivici** [comment]
I've set the global setting as false, when it is live with RC4 next week, it would be more evident and displayed more correct.
