### ISSUE TITLE
When the editor is used in the form, there is a problem with the style, and the line break of the content of the editor will also be invalid

### ISSUE THREAD

**Issue by zouchengtao** [primefaces/primeng#9152]
![image](https://user-images.githubusercontent.com/20035635/89870919-28682c00-dbe9-11ea-8ec5-8852f4798365.png)
this is the editor is used in the form
`<p-editor formControlName="courseDesc" [style]="{'height':'320px'}"></p-editor>`

![image](https://user-images.githubusercontent.com/20035635/89870996-47ff5480-dbe9-11ea-8937-91faa0d3dfdb.png)
this is normal style
`<p-editor [(ngModel)]="text" [style]="{'height':'320px'}"></p-editor>`

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
