### ISSUE TITLE
Carousel - set page does not work for first and last page

### ISSUE THREAD

**Issue by VILLAN3LL3** [primefaces/primeng#9153]
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
[stackblitz editor](https://stackblitz.com/edit/github-rzoqqm?file=src/app/app.component.html)
[stackblitz app](https://github-rzoqqm.stackblitz.io)

**Current behavior**
If I set the page property of a carousel to the first or last page it doesn't jump to that page. It works correctly for all other pages.

**Expected behavior**
Should also jump to the right page if the first or last page index is set

**Minimal reproduction of the problem with instructions**
See stackblitz

Snipped from primeng carousel code:

```
set page(val:number) {
		if (this.isCreated && val !== this._page) {
			if (this.autoplayInterval) {
				this.stopAutoplay();
				this.allowAutoplay = false;
			}

			if (val > this._page && val < (this.totalDots() - 1)) {
				this.step(-1, val);
			}
			else if (val < this._page && val !== 0) {
				this.step(1, val);
			}
		} 

		this._page = val;
	}
```
--> this.step is not called for the first and last page index

**Comment by BalamuruganSaravanan** [comment]
Primeng v8 still have this issue. I'm using Angular v8 and Primeng v8 and if I update the Angular or Primeng version, it is causing lot of errors and SCSS styling issues in my existing application. Is it possible to fix this in the older versions as well?

**Comment by francoeder** [comment]
I managed to work around this problem as follows:

```
currentPage?: number;

...

setPage(page: number) {
     this.currentPage = undefined;
     setTimeout(() => this.currentPage = page, 0);
}
```

In my scenario, the setPage method is the method I use to manage the carousel page change.

I hope it helps.
