### ISSUE TITLE
Sort and Filter support for VirtualScrolling

### ISSUE THREAD

**Issue by markvdkerkhof** [primefaces/primeng#9154]
**I'm submitting a bug report **

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-f1jpot-knw3nx

**Current behavior**
Clicking on sort of virtual scrollable table doesn't do anything

**Expected behavior**
Clicking on sort of virtual scrollable table should sort the table

**Minimal reproduction of the problem with instructions**

Angular version: 9.1.9
PrimeNG version: 9.1.0
Browser: [all]
Language: [all]

* **Angular version:** 9.0.4

* **PrimeNG version:** 9.1.0

* **Browser:** only tried Chrome

**Comment by rodolfojnn** [comment]
same here!! https://stackblitz.com/edit/primeng-tablevirtualscroll-demo-3pdmjy

**Comment by ralscha** [comment]
As a workaround until this is fixed you can register a click listener on the th tag
```
    <ng-template pTemplate="header">
        <tr>
            <th pSortableColumn="vin" (click)="refreshData()">    <-------------
                vin <p-sortIcon field="vin"></p-sortIcon>
            </th>
            <th>
                year
            </th>
        </tr>
    </ng-template>
``` 

And in the `refreshData` method you assign a new reference to the value object
```
  refreshData(): void {
    this.cars = [...this.cars];
  }
```

**Comment by markvdkerkhof** [comment]
Thanks Ralscha, we used your workaround with success

**Comment by kongshu612** [comment]
I got a little confusing about this bug. p-table already use the `[cdkVirtualForTrackBy]="dt.rowTrackBy"` to track changes, and `dt.rowTrackBy` is `@Input() rowTrackBy: Function = (index: number, item: any) => item;`,  **Why do we need this.value=[...value]** to refresh *CD*, It is not reasonable, is it something wrong with the *CDK virtual scroll*?
```
 <ng-template cdkVirtualFor let-rowData let-rowIndex="index" [cdkVirtualForOf]="dt.value" [cdkVirtualForTrackBy]="dt.rowTrackBy">
                <ng-container *ngTemplateOutlet="rowData ? template: dt.loadingBodyTemplate; context: {$implicit: rowData, rowIndex: dt.paginator ? (dt.first + rowIndex) : rowIndex, columns: columns, editing: (dt.editMode === 'row' && dt.isRowEditing(rowData))}"></ng-container>
            </ng-template>
```

**Comment by kievsash** [comment]
I found related issue for 9.1.3 with virtualScroll+lazyLoading+sorting
If I sort by column (press column header) - virtualScroll does not reset loadedPages to start from the begining
Solution - in onSort handler I reset (this.pTableInstance as Table).scrollableViewChild.loadedPages = [0]; 

<p-table #pTableInstance (onSort)="onSort()"...

ViewChild('pTableInstance ') pTableInstance: Table;

onSort() {
   (this.pTableInstance as Table).scrollableViewChild.loadedPages = [0]; 
}
