### ISSUE TITLE
p-megamenu display issue with more than 4 columns

### ISSUE THREAD

**Issue by xinmoveware** [primefaces/primeng#9156]
**I'm submitting a ...** 
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-megamenu-demo-5nnag2?file=src/app/app.component.ts

**Current behavior**
Mega menu with 5 or more columns do not display properly as per the stackblitz example, only the first column is shown correctly, the rest of the columns are shifted far to the right outside of the dropdown panel.

**Expected behavior**
5 or more columns should be displayed next to each other as per normal.

**Minimal reproduction of the problem with instructions**
As per stackblitz example, if the submenus come in more than 4 columns, they are not properly displayed.

**What is the motivation / use case for changing the behavior?**
We need to display menu items in more than 4 columns

* **Angular version:** 9.1.12

* **PrimeNG version:** 9.1.3

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by Rdevc** [comment]
Hi @mertsincan,

This issue is still present in version 19.

<img width="1968" height="600" alt="Image" src="https://github.com/user-attachments/assets/4e1905ef-440f-4300-ba68-4b09921eb553" />

**Reproduction**
https://stackblitz.com/edit/1gx7nyna-5atqo62d?file=src%2Fapp%2Fmega-menu-basic-demo.ts

Could you please reopen this issue?

Kind regards,
