### ISSUE TITLE
p-datatable headerRows doesn't support scroll attributes

### ISSUE THREAD

**Issue by quahkj** [primefaces/primeng#916]
Hi There,

At the moment I am doing some testing with p-dataTable. This table is really useful and powerful. Now I am facing a problem when headerRows attribute used along with scrollable attribute. Below please find my current code:

```
<p-dataTable [value]="timeAllocationSummary" [headerRows]="headerRows" scrollable="true"        scrollHeight="200px" scrollWidth="100%" [globalFilter]="gb2" selectionMode="multiple" [(selection)]="selectedRec" (onRowSelect)="onRowSelect($event)" (onRowUnselect)="onRowUnselect($event)">
        <p-column *ngFor="let col of cols" [field]="col.field" [header]="col.header" [style]="col.style" [sortable]="true"></p-column>
 </p-dataTable>
```

This codes display everything as expected except the column grouping is lost that specified by the headerRows attribute. I got the scroll bar but there is no grouping on the column.

If I removed **"scrollable="true"  scrollHeight="200px" scrollWidth="100%"** attributes from p-dataTable. The grouping column came back but I have to give up the scroll bar.

Is there a way for the two attribute to co-exist? I would be appreciated if someone can guide me on this issue. Thank you.

KJ

**Comment by GopiAnnan** [comment]
I do have the same issue, when scrollable is true, and if the Scrollbar is not appearing, columns header alignment having issue.

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with them and if issue persists drop a comment and we'll reopen.

**Comment by tpmehta96** [comment]
I am using the latest version of Google chrome browser, Angular and PrimeNG, but this issue still persists. 
Using scrollHeight works well, but using scrollWidth does work with scrollable = true. 
Please reopen the ticket.
