### ISSUE TITLE
p-inputNumber ngModelChange not working

### ISSUE THREAD

**Issue by hoaminhit** [primefaces/primeng#9160]
I am using primeng 10.0.0-rc.3
`<p-inputNumber  [(ngModel)]="price" (ngModelChange)="calcFee()"></p-inputNumber>`
Thank you!

**Comment by hoaminhit** [comment]
p-spinner is work fine but it deprecated on primeng 10.0.0-rc.3

**Comment by hoaminhit** [comment]
And on the p-autoComplete multiple mode, when it has selected value it not show still I click to UI input it show, I change file `autocomplete.ts`:
`changeDetection: ChangeDetectionStrategy.OnPush`
to:
`changeDetection: ChangeDetectionStrategy.Default` look like primeng ver 9.1.3 it work!

**Comment by mertsincan** [comment]
Hi,

This is an expected behavior. The working structure of InputNumber is different. If you want to get new value every time you add a new character, please use onInput event. Please see details;
https://github.com/primefaces/primeng/issues/9223

```
//ts
onInput(event) {
   // maybe, you can add some validations
   this.value = event.value;
}

//html
<p-inputNumber [(ngModel)]="value" (onInput)="onInput($event)">
```

Best Regards,
