### ISSUE TITLE
p-overlayPanel outside of the window, TypeError: target.getBoundingClientRect is not a function

### ISSUE THREAD

**Issue by marcin-nejf** [primefaces/primeng#9166]
```
[ X ] bug report
```

Case at stackblitz: 
https://stackblitz.com/edit/github-yjer6t

When you select 'Custom range' from dropdown, in console you see an error and p-overlay outside the widnow (with horizontal scroll)

```
preview-8079e088a5819580c54db.js:1 ERROR TypeError: target.getBoundingClientRect is not a function
    at Function.DomHandler.absolutePosition (domhandler.ts:134)
    at OverlayPanel.align (overlaypanel.ts:180)
    at OverlayPanel.onAnimationStart (overlaypanel.ts:195)
```

Overlay panel should be attached to input of dropdown.
Also the option [dismissible] = "true" does not work.
I use a similar mechanism in another place and there is no error in console.

* **Browser:** Chrome

**Comment by cagataycivici** [comment]
This is expected, overlayPanel requires a dom element existing on the page, in your example the target leaves the dom so an error is occured.
