### ISSUE TITLE
p-treeTable with VirtualScroll only header is resizing

### ISSUE THREAD

**Issue by KimAlexander** [primefaces/primeng#9170]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/primeng-treetablescroll-demo-hatiny?file=src/app/app.component.html

**Current behavior**
Columns resize in tree table with virtualScroll=[true] not working

**Expected behavior**
columns resize should work 

**Minimal reproduction of the problem with instructions**

Scroll down to the _Virtual Scroll with 100000 Nodes_ section 
Then, try to resize any columns vertical blue line stays 

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.X

* **PrimeNG version:** 5.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by yigitfindikli** [comment]
Hi @KimAlexander,

You need to use colgroup. You can find detailed information under the  [Column Resize](https://primefaces.org/primeng/showcase/#/treetable). There is an issue with resizing but your report is wrong. I'm gonna edit your issue.

**Comment by khushbupatel2** [comment]
<p-virtualScroller #virtualScroller [value]="conversations" scrollHeight="500px" autosize
		[rows]="conversations.length" [cache]="false" [lazy]="false">
			<ng-template let-row pTemplate="item" let-i="index">
			<div class="ui-g car-item">
	<p [innerHTML]="row?.message "></p>
		</div>
		</ng-template>
	</p-virtualScroller>
	
	@ViewChild('virtualScroller', { static: false }) public virtualScroller!: VirtualScroller;
	 public scrollTo(i:any): void {
     
      try {
        this.virtualScroller.scrollTo(i);
      } catch (error) {}
    } when I use autosize that time  this.virtualScroller.scrollTo(i); not work
