### ISSUE TITLE
Overlaypanel: Content is not displayed

### ISSUE THREAD

**Issue by projectX21** [primefaces/primeng#9175]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

I havn't found any primeng 10.0.0.rc3 template.

But it is enough to copy the following code from the documentation:

```
<p-overlayPanel #op>
    <ng-template pTemplate>
        Content
    </ng-template>
</p-overlayPanel>

<button type="text" pButton label="Basic" (click)="op.toggle($event)"></button>
```

Clicking on the button, the border of the overlaypanel will be displayed, but not the content:

![image](https://user-images.githubusercontent.com/11422553/90758602-92ff2300-e2df-11ea-9918-f881bf7799f0.png)

![image](https://user-images.githubusercontent.com/11422553/90758782-cfcb1a00-e2df-11ea-81b2-76f663600cdb.png)

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 10.0.9

* **PrimeNG version:** 10.0.0.rc3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by projectX21** [comment]
I've found out, that the angular cdk is needed?!
After I have imported the cdk:
`npm install @angular/cdk --save`
it works.

If so, and it's not a bug, it should be noted in the documentation.

**Comment by baranovskyi** [comment]
> I've found out, that the angular cdk is needed?!
> After I have imported the cdk:
> `npm install @angular/cdk --save`
> it works.
> 
> If so, and it's not a bug, it should be noted in the documentation.

angular cdk is installed. however, if it is p-colorPicker inside p-overlayPanel, on the second opening of overlay colorPicker is not displayed correctly 
![image](https://user-images.githubusercontent.com/33638516/96725656-c0d51680-13b9-11eb-99a0-99b677ea1703.png)
