### ISSUE TITLE
Primeng p-table re-order items in virtual scrolling by fast scrolling

### ISSUE THREAD

**Issue by pedy711** [primefaces/primeng#9176]
**I'm submitting a bug** 

If you go to the demo page of virtual scrolling for [p-table](https://primefaces.org/primeng/showcase/#/table/virtualscroll) and scroll to the end of the table and scroll quickly back up a little and then all the way back down again, you see the last item changes now and then. How to avoid this? any help would be appreciated!

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.

**Comment by liniwalid** [comment]
how did you solve the issue, thxs
