### ISSUE TITLE
(bug) ConfirmDialog template has wrong binding

### ISSUE THREAD

**Issue by moxival** [primefaces/primeng#918]
The cancel button of the ConfirmDialog template has the wrong binding for the cancel icon https://github.com/primefaces/primeng/blob/master/components/confirmdialog/confirmdialog.ts#L29

Pull request comming

**Comment by fernandogomesdf** [comment]
+1

**Comment by fernandogomesdf** [comment]
The reject icon bind to 'reject':
<button type="button" pButton [icon]="reject" [label]="rejectLabel" (click)="reject()"></button>
It should bind to 'rejectIcon' : @Input() rejectIcon: string = 'fa-close';
