### ISSUE TITLE
p-blockUI does not work with p-terminal (it blocks the whole document, even if target is specified)

### ISSUE THREAD

**Issue by distributev** [primefaces/primeng#9180]
Following code is blocking the whole document when it was supposed to block only pnlTerminal

```
<p-blockUI [blocked]="readOnly" [target]="pnlTerminal">
    <i class="pi pi-lock" style="font-size: 3rem"></i>
</p-blockUI>

<p-panel #pnlTerminal header="Commands">
 
    <p-terminal id='p-terminal' prompt="$ "></p-terminal>

</p-panel>
```

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
