### ISSUE TITLE
TreeTable children detaches from respective parent and wobbles

### ISSUE THREAD

**Issue by kingringc** [primefaces/primeng#9187]
Is an issue with treatable.

Please check the primeng demo page for treatable virtual scroll [example](https://www.primefaces.org/primeng/v9.1.4-lts/#/treetable/scroll)

change this below code
from:
this.virtualFiles = Array.from({length: 1000}).map((_,i) => this.createNode(i, 100));
to:
this.virtualFiles = Array.from({length: 2}).map((_,i) => this.createNode(i, 100));

Now start to expand the second item in the table, the children of second parent detaches and floats above the parent just below first parent.

eg: https://stackblitz.com/edit/primeng-treetablescroll-demo-twlzz1

**Comment by kingringc** [comment]
Can someone please confirm this issue?

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
