### ISSUE TITLE
p-treeTableHeaderCheckbox doesn't select/unselect all when TreeTable has dataKey property

### ISSUE THREAD

**Issue by kingmakeryao** [primefaces/primeng#9188]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-treetableselection-demo-vbfsum

**Current behavior**
The top select-all checkbox doesn't work if p-treeTable dataKey property is used (e.g. <p-treeTable dataKey="name").
The root nodes are not selected and nothing happens if I click the second time. Only child nodes are selected

**Expected behavior**
Click the top select-all checkbox should select or unselect all the nodes.

**Minimal reproduction of the problem with instructions**
Just use "dataKey" property for the p-treeTable and try to use p-treeTableHeaderCheckbox

* **Angular version:** 9.X

* **PrimeNG version:** 9.X

* **Browser:** [all | Chrome 84 | Firefox 79 | IE Edge]

**Comment by kingmakeryao** [comment]
This issue was mentioned in #7511 but it was closed. I'm still able to replicate it by using the current treetable demo.

Please let me know if anything else is needed. It's my first time opening a ticket here.

**Comment by MrBogue** [comment]
p-treeTableHeaderCheckbox doesn't select/unselect all when TreeTable has dataKey property 

+1 issue
not able to select/unselect all when TreeTable has dataKey property 

Please advise when will be the next fix..

**Comment by cetincakiroglu** [comment]
Hi,

If the issue still exists with the latest PrimeNG version, please provide a StackBlitz example by using [PrimeNG Issue Template ](https://stackblitz.com/github/primefaces/primeng-issue-template) and re-open the issue.

Regards

**Comment by andrerauer** [comment]
Hi,

the issue still exists. Here the StackBlitz example: 

https://stackblitz.com/edit/github-bcnczx?file=src/app/app.component.html

If you remove the `dataKey`-Attribute, the select-all toggle works.

**Comment by ABiBE** [comment]
Hi @psarno.
I have the same problem. Here last exemple fork with latest Prime and Angular versions :
https://stackblitz.com/edit/github-bcnczx-uak4ao?file=src%2Fapp%2Fapp.component.html
