### ISSUE TITLE
selectButton styling & alignment does not match other controls

### ISSUE THREAD

**Issue by Calidus** [primefaces/primeng#9189]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/primeng-selectbutton-demo-gvaddl

**Current behavior**
pSelectButton component does to align with other common control components like pDropdown, pButton and pInputText with additional CSS.

**Expected behavior**
Select button to naturally align with other controls with additional css

**Minimal reproduction of the problem with instructions**
Add a selectButton and other controls like a button or dropdown inline

**What is the motivation / use case for changing the behavior?**
Controls from the same component package should align by default.

**Please tell us about your environment:**

* **Angular version:** 5.X
9.1.4

* **PrimeNG version:** 5.X
9.0.6

* **Browser:**  [all]

* **Language:** [all]

* **Node (for AoT issues):** `node --version` =

**Comment by cagataycivici** [comment]
This is theme related, check out the nextgen themes like Saga.
