### ISSUE TITLE
Slider handle not working correctly with model driven forms

### ISSUE THREAD

**Issue by raphibolliger** [primefaces/primeng#9192]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Stackblitz Demo**

https://stackblitz.com/edit/primengdemo

**Current behavior**

The slider handlers behavior is not reactive on a Model Driven implementation. The slider handler jumps only a the end of the action to the correct position. This behavior is only in Model Driven mode. With the old Two-way binding there is no problem and the slider is reactive.

**Expected behavior**

The slider should be also reactive with Model Driven implementation like in Two-way binding implementation.

**Minimal reproduction of the problem with instructions**
Slide both of the slider in the Stackblitz demo. Also see the behavior in the following GIF.

![PrimeNgSliderBug](https://user-images.githubusercontent.com/6289764/91284652-7bff7b80-e78c-11ea-8cab-31fb6547058f.gif)

**Angular version:** 10.0.12

**PrimeNG version:** 10.0.0-rc.3

**Browser:** [Chrome | Safari | Edge Chromium | maybe more (not tested any others)]

**Comment by Gretam11** [comment]
As a workaround you can add `(onChange)="0"` to model driven forms slider
