### ISSUE TITLE
triStateCheckbox style broken in 10.0.0-rc.3

### ISSUE THREAD

**Issue by mklaury** [primefaces/primeng#9194]
Hi. We're using 10.0.0-rc.3. In this version, no visual update of the triStateCheckbox when switching from checked to unchecked.

Downgrading to 9.1.3 make it work as expected.

**Comment by cagataycivici** [comment]
Live one works fine;

https://primefaces.org/primeng/showcase/#/tristatecheckbox

A stackblitz would help. Are you using reactive forms?

**Comment by mklaury** [comment]
Not using reactive forms. I'm using it like in documentation. The functionnality is ok. It's just the visual appearence not working like in the example. When downgrading to 9.1.3, then everything works just fine.

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 10.0.0-rc.3 and the live demo works fine, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
