### ISSUE TITLE
Add a demo for TreeTable row grouping

### ISSUE THREAD

**Issue by ymasha** [primefaces/primeng#9198]
It will be very useful to have row group support in tree table like the one in p-table 
https://primefaces.org/primeng/showcase/#/table/rowgroup

I was able to add some custom code to tree table to show row group but then filters and sort column no longer works.

**Comment by cagataycivici** [comment]
We can add a demo I guess, since with Table row grouping is presented as a demo as well.

**Comment by smunir** [comment]
@ymasha Can you please share code for rowGroup in treatable. I tried to do it following table but it's not working. I don't need sort and filtering.

**Comment by shahrishabhptechnical** [comment]
Is there any update on this?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
