### ISSUE TITLE
On pRowToggler, [value]="getProducts(rowData)" getProducts method is hitting multiple times.

### ISSUE THREAD

**Issue by yedidisatya** [primefaces/primeng#9200]
In my case when user expands any doc row, we use getProducts(rowData) to get specific detailed data from service:

But there are two problems:

on every click on expand icon , getProducts(rowData) repeats more than 10 times...
if user expanded another table getProductsbefore, then multiple row rowIndex recieved.
console log samples

the example in the below link and you see the reputation in the console when expanding the row

https://stackblitz.com/edit/primeng-tablerowexpansion-demo-1jcrdh?file=src/app/app.component.html

Hoping will get resolved quickly thank you.

**Comment by cagataycivici** [comment]
It is because of Angular change detection, we're not calling that method.
