### ISSUE TITLE
FullCalendar 5 Support

### ISSUE THREAD

**Issue by frankieta** [primefaces/primeng#9201]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Currently latest FullCalendar supported version is 4 (4.4.2 i guess)

**Expected behavior**
Any ETA for a support of FullCalendar v5?

**Please tell us about your environment:**
Windows

* **Angular version:** 5.X
9

* **PrimeNG version:** 5.X
9.1.3

**Comment by tbegsr** [comment]
Version 11.3.1 still use "@fullcalendar/core": "4.1.0",
Is there a plan for an update fullcalendar to 5.4.0?

**Comment by davidda** [comment]
@cagataycivici  Could this be reopened please given the rollback in January?
