### ISSUE TITLE
Treetable column resize breaks when columnResizeMode="expand" in combination with [virtualScroll]="true"

### ISSUE THREAD

**Issue by zy-serguei** [primefaces/primeng#9202]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://github-ypv2wr.stackblitz.io

**Current behavior**
Exception is raised when trying to resize a column: **Cannot read property 'style' of null.**

**Expected behavior**
Columns gets resized

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 10.0.14

* **PrimeNG version:** 10.0.0-rc.3

* **Browser:** all

 
* **Language:** all

**Comment by yigitfindikli** [comment]
Fixed in https://github.com/primefaces/primeng/commit/3d9cacf56851e3618f7c6b9e1385ecd524b5eaa0 .
