### ISSUE TITLE
ConfirmDialog on close should act as reject

### ISSUE THREAD

**Issue by moxival** [primefaces/primeng#921]
When closing a confirmation dialog (via close button or ESC) i think that it should act as if the cancel button was clicked.

**Comment by ova2** [comment]
Solution is here #2757

**Comment by QuentinLeGoff** [comment]
I think the escape button and the reject button should not have the same behavior because to click on the 'No' button means reject the action however escape the dialog means go back to the previous state.

So the escape button should not start the reject method. No ?
