### ISSUE TITLE
p-multiselect filtering seems broken since 10.0.0 RC2

### ISSUE THREAD

**Issue by dsebastien** [primefaces/primeng#9211]
**I'm submitting a pre-release bug**
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**Current behavior**
The multiselect items don't get removed when they don't match the search filter. This means that the filtering is broken.

**Expected behavior**
The p-multiselect hides elements that don't match the current search filter by adding display: none on the p-multiselect items
Ideally using a better method as requested here: https://github.com/primefaces/primeng/issues/8960

The filtering would work.

* **Angular version:** 10.1.0

* **PrimeNG version:** 10.0.0-RC3

**Comment by cagataycivici** [comment]
Live demo seems to work fine, how can we replicate the issue?

https://primefaces.org/primeng/showcase/#/multiselect

**Comment by dsebastien** [comment]
Probably because the change was introduced after rc1?
I think this is the source of the issue: https://github.com/primefaces/primeng/commit/d68d1addaccd93755eee940bd172b770b85dd253

It does match the behavior we observe with RC2 and RC3: elements remain in the DOM and don't get the ng-reflect-visible="true" when they're not filtered out

**Comment by cagataycivici** [comment]
We should remove the visible prop yes, but can you replicate your initial problem with RC3? As I've mentioned live one works for me. Can we close this ticket?

**Comment by dsebastien** [comment]
Hello @cagataycivici 

We confirm that it works perfectly with 10.0.0 final.

Thanks!
