### ISSUE TITLE
p-treetable editable fields with ttRow arrow key navigation issue

### ISSUE THREAD

**Issue by SenthilRG** [primefaces/primeng#9215]
I am using below code to navigate nodes through arrow key. 

```
<p-treeTable #tt [value]="files" [columns]="cols">
    <ng-template pTemplate="header" let-columns>
        <tr>
            <th *ngFor="let col of cols" style="width:30px">
                {{col.header}}
            </th>
        </tr>
    </ng-template>
    <ng-template pTemplate="body" let-rowNode let-rowData="rowData"  let-columns="columns">
        <tr [ttRow]="rowNode">
            <td width="30" class="text-right" ttEditableColumn> 
              <p-treeTableToggler [rowNode]="rowNode">
                    </p-treeTableToggler>
                <p-treeTableCellEditor>
                    <ng-template pTemplate="input">
                        <input type="text" pInputText [(ngModel)]="rowData['name']" />
                    </ng-template>
                    <ng-template pTemplate="output">
                        <input type="text" pInputText [(ngModel)]="rowData['name']">
                     </ng-template>
                </p-treeTableCellEditor>
             </td> 
             <td width="30" class="text-right">
                <span>
                    {{rowData['size']}}
                </span>
             </td>
             <td width="30" class="text-right" ttEditableColumn>
                <p-treeTableCellEditor>
                    <ng-template pTemplate="input">
                        <input type="text" pInputText [(ngModel)]="rowData['type']" />
                    </ng-template>
                    <ng-template pTemplate="output">
                        <input type="text" pInputText [(ngModel)]="rowData['type']">
                     </ng-template>
                </p-treeTableCellEditor>
             </td>
        </tr>
    </ng-template>
</p-treeTable>
```  
I am getting below error while navigating one node to another node. Please help me to resolve this issue.

> core.js:4117 ERROR TypeError: Cannot read property 'parentElement' of null
>     at TTEditableColumn.push../node_modules/primeng/__ivy_ngcc__/fesm5/primeng-treetable.js.TTEditableColumn.moveToNextCell (primeng-treetable.js:3393)
>     at TTEditableColumn.push../node_modules/primeng/__ivy_ngcc__/fesm5/primeng-treetable.js.TTEditableColumn.onKeyDown (primeng-treetable.js:3366)
>     at TTEditableColumn_keydown_HostBindingHandler (primeng-treetable.js:3461)
>     at executeListenerWithErrorHandling (core.js:14935)
>     at wrapListenerIn_markDirtyAndPreventDefault (core.js:14970)
>     at HTMLTableCellElement.<anonymous> (platform-browser.js:615)
>     at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
>     at Object.onInvokeTask (core.js:28122)
>     at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
>     at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)

**StackBlitz Demo:** https://stackblitz.com/edit/primeng-treetable-hte3gta?file=src%2Fapp%2Fapp.component.html

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
