### ISSUE TITLE
Error DropdownModule and PaginatorModule. Angular/cli: 10.0.0; Primeng:^10.0.0-rc.3

### ISSUE THREAD

**Issue by Vladislav-wn** [primefaces/primeng#9216]
Hi
Text error:
> ng run mysite:serve 
Compiling primeng/dataview : es2015 as esm2015
Compiling primeng/paginator : es2015 as esm2015
Error: Failed to compile entry-point primeng/paginator (es2015 as esm2015) due to compilation errors:
node_modules/primeng/dropdown/dropdown.d.ts:168:22 - error NG6002: Appears in the NgModule.imports of PaginatorModule, but could not be resolved to an NgModule class.

This likely means that the library (primeng/dropdown) which declares DropdownModule has not been processed correctly by ngcc, or is not compatible with 
Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

168 export declare class DropdownModule {
                         ~~~~~~~~~~~~~~
node_modules/primeng/dropdown/dropdown.d.ts:168:22 - error NG6003: Appears in the NgModule.exports of PaginatorModule, but could not be resolved to an NgModule, Component, Directive, or Pipe class.

This likely means that the library (primeng/dropdown) which declares DropdownModule has not been processed correctly by ngcc, or is not compatible with 
Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

168 export declare class DropdownModule {
                         ~~~~~~~~~~~~~~

Error: Failed to compile entry-point primeng/dataview (es2015 as esm2015) due to compilation errors:
node_modules/primeng/paginator/paginator.d.ts:46:22 - error NG6002: Appears in the NgModule.imports of DataViewModule, but could not be resolved to an NgModule class.

This likely means that the library (primeng/paginator) which declares PaginatorModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

46 export declare class PaginatorModule {

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 10-rc3, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Comment by Vladislav-wn** [comment]
ok
