### ISSUE TITLE
InputNumber: pasting doesn't work correctly

### ISSUE THREAD

**Issue by Timmeeeey** [primefaces/primeng#9219]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When pasting a number with fractional digits like 1.234,56 the decimal separator is ignored and the number 123.456,00 is entered instead.

**Expected behavior**
When pasting a number with fractional digits the number should not change.

**Minimal reproduction of the problem with instructions**
Paste the number 1.234,56 in the inputNumber "Min-Max Fraction Digits" in the PrimeNg Showcase.
https://primefaces.org/primeng/showcase/#/inputnumber

**What is the motivation / use case for changing the behavior?**
When pasting a number with fractional digits the wrong number is entered in the input.

**Please tell us about your environment:**

* **Angular version:** 10.X

* **PrimeNG version:** 10.0.0-rc.3

* **Browser:**
Tested in Chrome, Firefox

**Comment by mertsincan** [comment]
Hi,

Fixed now. 

Please see these cases;
copied text: 1.234,56
range selection: all value in the current input

_**locale="de-DE"**_
current inputValue: **_555,55_** (dummy value)
_decimalChar: '**,**' groupChar: '**.**'_ 
- new input value: **_1.234,56_** (decimal chars are same.)


_**locale="en-US"**_
current inputValue: **_555.55_** (dummy value)
_decimalChar: '**,**' groupChar: '**.**'_ 
- new input value: **_123,456.00_** (decimal chars are different.)

Please pay attention to the decimal characters of both locale and copied values.

Best Regards,

**Comment by Timmeeeey** [comment]
@mertsincan 
Hi,

unfortunately it doesn't work if the inputValue is empty.

copied text: 1.234,56
current inputValue: null

If you try to paste the value nothing happens and the inputValue stays empty.

**Comment by mertsincan** [comment]
Thanks a lot for the update and new ticket! I'll check it.

Best Regards,

**Comment by Timmeeeey** [comment]
@mertsincan
Hi,
should I create a new ticket for the pasting issue?
