### ISSUE TITLE
Flex Grid is not working with Angular 10

### ISSUE THREAD

**Issue by Someshkotni** [primefaces/primeng#9221]
I am using the prime flex style for my angular 10 projects. Flex is not working 

Here is my HTML code for the flex grid.

<h3 class="first">Basic</h3>
<div class="p-grid">
<div class="p-col">
<div class="box">1</div>
</div>
<div class="p-col">
<div class="box">2</div>
</div>
<div class="p-col">
<div class="box">3</div>
</div>
</div>

Rather getting in flex style. it's displaying the following
Basic
1 2 3

Also, I included  primeflex.css in angular.json file

"styles": [
              ..some other styles
              "node_modules/primeng/resources/primeng.min.css",
              "node_modules/primeicons/primeicons.css",
              "src/styles/styles.scss",
              "node_modules/primeflex/primeflex.css"
            ],

**Comment by cagataycivici** [comment]
Please use forum for support requests and also a stackblitz sample would help.
