### ISSUE TITLE
Add onInput event to InputNumber

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primeng#9223]
The **onInput** event parses the value in the current input field and returns it to model. The value that comes to the model is the value that is **not validated**. This event is called every time one presses a key.

**In current behavior**, the model is updated in two ways;
1. Clicking outside to validate the change after changing something in inputNumber.
2. Changing the value using spinner's button/arrow keys

And the value that comes to the model is the value that is **validated**.

**Comment by nagarjun-tech** [comment]
Can someone please confirm if this issue is already resolved in the recent release.
