### ISSUE TITLE
scrollHeight="flex" and [virtualScroll]="true",wrong when i change height 

### ISSUE THREAD

**Issue by lifront** [primefaces/primeng#9227]
**Plunkr Case (Bug Reports)**
scrollHeight="flex" not work right when  [virtualScroll]="true"

demo: https://stackblitz.com/edit/primeng-tablescroll-demo-f7zivi

**Current behavior**

![image](https://user-images.githubusercontent.com/20509009/91983075-bef9ba00-ed5d-11ea-8749-635b98b4dce3.png)

**Expected behavior**

when i delete [virtualScroll]="true",scrollHeight="flex" working good,like this
![image](https://user-images.githubusercontent.com/20509009/91983163-dfc20f80-ed5d-11ea-9ece-41378c54fe3a.png)

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 9.X

* **PrimeNG version:** 9.1.3

* **Browser:** Chrome XX

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =  12.16.3

**Comment by nsaini-05** [comment]
Hi 
Do you have any solution to this issue ?
