### ISSUE TITLE
MenuBar not showing items at hover, MegaMenu does

### ISSUE THREAD

**Issue by antsteyer** [primefaces/primeng#9228]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-menubar-demo

**Current behavior**
Need a click to show the items of a MenuItem in MenuBar

**Expected behavior**
Open the menu at hover

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/primeng-menubar-demo

**What is the motivation / use case for changing the behavior?**

Behaviour needs to be the same as MegaMenu

**Please tell us about your environment:**
PrimeNg Documentation

* **Angular version:** 5.X
Any version

* **PrimeNG version:** 5.X
9 LTS, all 10.0.0.rc

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
