### ISSUE TITLE
InputNumber: overwriting doesn't work correctly

### ISSUE THREAD

**Issue by Timmeeeey** [primefaces/primeng#9229]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
Try to overwrite an existing value.
After you type the first digit the inputNumber inserts the fractional digits (e.g. ",00") and the cursor jumps at the end .
When you try to insert a value with more than one digit the resulting value will be wrong, e.g. when your try to insert 123 you will get 1,0023.

**Expected behavior**
The value is entered correctly.

**Minimal reproduction of the problem with instructions**
PrimeNg Showcase: inputNumber "Min-Max Fraction Digits"
https://primefaces.org/primeng/showcase/#/inputnumber

* select the existing value (2.351,35) by tabbing into the component or by selecting with your mouse.
* try to type the value 123. After you type the first digit, ",00" is inserted and the cursor jumps at the end
* the resulting value will be 1,0023

**Please tell us about your environment:**
* **Angular version:** 10

* **PrimeNG version:** 10.0.0-rc.4

* **Browser:** Tested in Chrome, Firefox

**Comment by srivindhyagithub** [comment]
The Above fix is not working if you enter the -Ve Number.
Minimal reproduction of the problem with instructions
PrimeNg Showcase: inputNumber  take any locale like United States Locale or German Locale
https://www.primefaces.org/primeng/showcase/#/inputnumber


try to type the value -123. After you type the first digit, ",00" is inserted and the cursor jumps at the end
the resulting value will be -1,0023
 The above was tested in the Primeng  site https://www.primefaces.org/primeng/showcase/#/inputnumber
