### ISSUE TITLE
Basic UI mode for FileUpload

### ISSUE THREAD

**Issue by ammar91** [primefaces/primeng#923]
Thanks for adding a way to customize UI. However, I'm still looking for something really simple.

I would like to have single button with auto upload support which is now working as intended. But wonder if I can hide upload and cancel button. Also, in my case I don't want to show File List UI, so I want to hide this as well.

Basically, if we could switch between Basic and Advance UI, that would be great. Something like this https://blueimp.github.io/jQuery-File-Upload/basic-plus.html , but again, the File List UI should be optional so one can hide it easily if not needed.

And finally, there should a Label property to change the default text "Choose" of file selection input.

**Comment by andfs** [comment]
It would be great if you put a should a Label property to change the default text "Choose" of file selection input.

**Comment by cagataycivici** [comment]
Like we had in PrimeFaces;

https://www.primefaces.org/showcase/ui/file/upload/basic.xhtml
