### ISSUE TITLE
ConfirmDialog: Allow pass a param in accept and reject methods

### ISSUE THREAD

**Issue by mlc-mlapis** [primefaces/primeng#9230]
**I'm submitting a ...**

```
[x] feature request
```

**Current behavior**

Actually it's not possible to pass any param in `accept()` or `reject()` methods for the following processing in their hooks code. As a workaround, it's possible to communicate indirectly via some public class property, like `options.type` in the below example.

```
<p-confirmDialog #confirmationDialog>
    <p-footer>
        <button type="button" pButton label="Only headers" (click)="options.type = 1; confirmationDialog.accept()"></button>
        <button type="button" pButton label="All records" (click)="options.type = 2; confirmationDialog.accept()"></button>
    </p-footer>
</p-confirmDialog>
```

**Expected behavior**

It would very useful to have the possibility to pass that param directly and have the ability to get it directly back in the hook code `accept: (id: number) => {...}` like in example below:

```
<p-confirmDialog #confirmationDialog>
    <p-footer>
        <button type="button" pButton label="Only headers" (click)="confirmationDialog.accept(1)"></button>
        <button type="button" pButton label="All records" (click)="confirmationDialog.accept(2)"></button>
    </p-footer>
</p-confirmDialog>
```

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
