### ISSUE TITLE
Progress Spinner doesn't have a customization example

### ISSUE THREAD

**Issue by mbondoso** [primefaces/primeng#9232]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

`  @keyframes p-progress-spinner-color {
    
    0%,to {
        stroke: $blue !important;
    }
    40% {
        stroke: $blue !important;
    }
    66% {
        stroke: $lightGreen !important;
    }
    80%,
    90% {
        stroke: $lightGreen !important;
    }
}`

This is not working. Also Documentation for version 10 is still showing the classes from version 9.

**Comment by yigitfindikli** [comment]
Hi @mbondoso,
If you want to customize progressspinner you need to do overwrite p-progress-spinner-circle's animation like this;

HTML:
`
<p-progressSpinner styleClass="custom-spinner"...></p-progressSpinner>
`
CSS:
`
:host ::ng-deep .custom-spinner .p-progress-spinner-circle {
    animation: custom-progress-spinner-dash 1.5s ease-in-out infinite, custom-progress-spinner-color 6s ease-in-out infinite;
}

@keyframes custom-progress-spinner-color {
    100%,
    0% {
        stroke: #16697A;
    }
    40% {
        stroke: #489FB5;
    }
    66% {
        stroke: #82C0CC;
    }
    80%,
    90% {
        stroke: #FFA62B;
    }
}

@keyframes custom-progress-spinner-dash {
    0% {
        stroke-dasharray: 1, 200;
        stroke-dashoffset: 0;
    }
    50% {
        stroke-dasharray: 89, 200;
        stroke-dashoffset: -35px;
    }
    100% {
        stroke-dasharray: 89, 200;
        stroke-dashoffset: -124px;
    }
}
`
