### ISSUE TITLE
Dynamic Dialog: custom header template

### ISSUE THREAD

**Issue by projectX21** [primefaces/primeng#9235]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

**Current behavior**

imho it isn't possible to define a custom p-header in a dynamic dialog. Instead the specified component will be rendered into the dialog body and you are only able to set the header text via the DynamicDialog properties.

**Expected behavior**
You should be able to define a custom header template as it is possible for the normal dialog.

**Comment by projectX21** [comment]
Maybe there is a workaround to archive custom headers in a dynamic dialog?
I think this is a much needed feature.. For clean code I want to outsource the dialogs from the components.
This isn't possible with normal dialogs, because their code is in the same parent component, isn't it?

**Comment by igority** [comment]
If I may suggest this feature to be extended to 'Custom header and footer'. I believe custom footer is even more needed, since a common UI convention is to add the Save/Dismiss buttons to the footer of the modal. Currently that is not possible, and achieving a workaround with the current implementation is very hackish

**Comment by teland94** [comment]
It's awful for such great library.. Header and Footer buttons are must be customizable with ng-template..

**Comment by kareljuricka** [comment]
+1

**Comment by idanielsteven** [comment]
+1

This is a  big gap. need very much.

**Comment by benshabatnoam** [comment]
+1
Will you guys accept a PR for that?

**Comment by marchrenno** [comment]
+1
Very much needed. A possible workaround in the mean time is to use a div in the body of the Dynamic Dialog, with absolute position.

**Comment by tapoinde** [comment]
+1, and you should also be able to customize the footer. A similar approach to how Angular Material does this would be ideal.

```
example.component.html

<h2 pDialogTitle>The Title</h2>
<p-dialog-content>
   ... 
</p-dialog-content>
<p-dialog-actions>
   <button>Close</button>
   <button>Save</button>
</p-dialog-actions>
 ```

**Comment by bmizepatterson** [comment]
+1
Much needed!

**Comment by NarjesSharafi** [comment]
+1
DynamicDialog has some defects in maximizing, minimizing, and dragging dialog too.

**Comment by lucassalatiel1993** [comment]
+1
Cabeçalho e rodapé personalizados em DinamicDialog Deve existir, pois é algo comum.

**Comment by jonnomk** [comment]
+1

**Comment by Kallaran** [comment]
+1 

Big gap :(

**Comment by parid0kht** [comment]
+1

**Comment by JBottelsen** [comment]
+1

**Comment by schlagi123** [comment]
+1

**Comment by luketanner** [comment]
+1

**Comment by mycahmason** [comment]
+1

**Comment by pkalkman** [comment]
+1

**Comment by frank71336** [comment]
+1
Seems to me, too, that the customizable footer is needed even more than a customizable header.

Btw: If you do not provide a footer text (and you can't provide a customizable footer) there is no border radius at the bottom of the dialog - even when looking at the official example: https://www.primefaces.org/primeng/showcase/#/dynamicdialog

**Comment by jonnomk** [comment]
I noticed that too and fixed it myself with CSS. The most frustrating issue though is not being able to specify a header and footer template that appear outside of the dialog content which means there's no scrolling body.

**Comment by Fichtengucker** [comment]
I would also really love that feature, just found a little workaround for now. Maybe this helps for someone else.

You can hide the header with the parameter "showHeader". If you do so, you can design your own one and template it.

**Comment by Muzummil** [comment]
+1

**Comment by vtozkan** [comment]
+1

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by saramcicchi** [comment]
Hi @mertsincan - this feature has not been implemented yet. Can you please reopen?

**Comment by toxaq** [comment]
I've submitted a pull request that resolves this:  https://github.com/primefaces/primeng/pull/12068 it is currently awaiting review.

**Comment by ARBS23** [comment]
> I would also really love that feature, just found a little workaround for now. Maybe this helps for someone else.
> 
> You can hide the header with the parameter "showHeader". If you do so, you can design your own one and template it.

Yes we can but, other features like dragging can't be find if we use `showHeader` as `false`

**Comment by nathan7432** [comment]
I also stumbled upon this thread looking for this feature.

**Comment by vborutenko** [comment]
One workaround - https://stackoverflow.com/a/77330067/2021019

**Comment by shaka-b** [comment]
+1

**Comment by trantoi99** [comment]
+1

**Comment by cetincakiroglu** [comment]
Added in v17, please check the example for usage https://primeng.org/dynamicdialog#example and also please check the templating options of dynamic dialog https://primeng.org/dynamicdialog#api.dynamicdialog-ref.interfaces.DynamicDialogTemplates

**Comment by jason1004156** [comment]
Is Possible to let header width fit the dialog?
I tried use width: 100% in headerTemplate.scss file but not working, because it will fit the <ng-component class="ng-star-inserted"> but this element can't be set style directly

**Comment by SandorDavid** [comment]
@jason1004156 
`display: flex` on the dialog header sets the width of header to fit the content.
A workaround like this gets around this issue:
`  .p-dialog-header {
    display: block !important;
  }`
