### ISSUE TITLE
Table scrolls to top when filter is enabled

### ISSUE THREAD

**Issue by HaraldStiwa** [primefaces/primeng#9236]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-fsvjx3?file=src/app/app.component.ts

**Current behavior**
When a user scrolls down in a p-table and a filter is enabled then an update of the table's value will discard any user scrolling

**Expected behavior**
Scroll position should be preserved

**Minimal reproduction of the problem with instructions**
a.) Click "Scroll down in table" button. Click "Add data to table" button. Previous scroll position is thrown away.
b.) Enable the switch in the provided example above and try to scroll down manually. It is not possible.

**What is the motivation / use case for changing the behavior?**
The scroll position was preserved in PrimeNG 8.x versions. This was changed in https://github.com/primefaces/primeng/commit/ba2f4d3dda3766642f0e746e297764bd4b83d769#diff-fc10cdf52c8d5add93682bdd37ee3653R1493

If I remove the call to this.resetScrollTop(); manually the scroll position is preserved.

**Please tell us about your environment:**
Windows 10, VS Code 1.148.2
Independent of OS or IDE.

* **Angular version:** 9.1.12
Independent of Angular version

* **PrimeNG version:** 9.1.3
Still present in newer PrimeNG source code.

* **Browser:** Chrome 85.0.4183.83
Should be browser independent
 
* **Language:** TypeScript 3.8.3

* **Node (for AoT issues):** `node --version` =   v12.18.3

**Comment by cagataycivici** [comment]
This is expected, similar to pagination, when filtering is done, data display should move to top by design.

**Comment by melnikov77** [comment]
I think you misunderstood the problem.
I agree that the scroll should move to the top when a user changes the filter or sorting and it is expected behavior.
But this case is different, you reset the scroll when data is updated and it is not expected behavior. 
As an example a user creates a filter and scroll down, then we receive an event that a data was changed (a record is updated, added or removed), the  table will render the changes and reset scroll instead of just rendering the changes.
In result the view became unusable because the scroll jumps all the time when we receive data change event.

**Comment by victornek** [comment]
"when filtering is done, data display should move to top by design"

But when filtering stays the same and not changing between data update, it makes scrolling impossible, which doesn't make sense. Please consider fixing it after all.

**Comment by bgl3317** [comment]
I'm looking for a solution to this too. It's a big problem for us.

**Comment by kaspaddy** [comment]
I'm also looking for a solution for this topic. Need to update filtered Table data and the scroll position shouldn't go to the top.

is there any solution to avoid this or can you add the option to disable the auto scroll behaviour?
