### ISSUE TITLE
ConfirmDialog closes parent DynamicDialog

### ISSUE THREAD

**Issue by aznarepse** [primefaces/primeng#9237]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://github-nuqe9e.stackblitz.io

**Current behavior**
When the confirmationdialog closes (even on reject), it also closes the DynamicDialog.

**Expected behavior**
The confirm dialog should be able to close without closing the DynamicDialog

**Minimal reproduction of the problem with instructions**
See
https://github-nuqe9e.stackblitz.io

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Any OS

* **Angular version:** 5.X
Angular 9.1.9

* **PrimeNG version:** 5.X
9.1.7

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
