### ISSUE TITLE
p-table footer disappears when [responsive]='true' and grid is responsive, 10.0.0-rc.4

### ISSUE THREAD

**Issue by PHuhn** [primefaces/primeng#9238]
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**Example**
html
```
<p-table id='weekTotals-grid' [value]='items'  dataKey='ExpenseTypeId' [responsive]='true'>
  <ng-template pTemplate='header'>
    <tr>
      <th style='width: 170px;'></th>
      <th><div style='width: 100px;'>Total</div></th>
    </tr>
  </ng-template>
  <ng-template pTemplate='body' let-rowData>
    <tr>
      <td>
        <span class='p-column-title'>Expense Type</span>
        {{ rowData['ExpenseType'] }}
      </td>
      <td>
        <span class='p-column-title'>Total</span>
        <div style='width: 80px;' class='nsg-wet-numeric'>
          {{ rowData['ExpenseTotal'] }}
        </div>
      </td>
    </tr>
  </ng-template>
  <ng-template pTemplate='footer' style='border-top: 1px solid black;'>
    <tr>
      <td>Totals</td>
      <td>
        <span class='p-column-title'>Grand Total</span>
          {{ grandTotal }}
      </td>
    </tr>
  </ng-template>
</p-table>
```
Code
```
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent implements OnInit {

  items: any[];
  grandTotal: number;
  ngOnInit() {
    this.items = [
      {ExpenseTypeId: 1, ExpenseType: 'Gas', ExpenseTotal: 20.0},
      {ExpenseTypeId: 2, ExpenseType: 'Food', ExpenseTotal: 12.88},
      {ExpenseTypeId: 3, ExpenseType: 'Mileage', ExpenseTotal: 5.50}
      ];
    this.grandTotal = 38.38;
  }
}
```
**Current behavior**

1. The footer is displayed with the p-column-title with the words 'Grand Total'
2. When the table is responsive the footer disappears

**Expected behavior**

1. The footer should not displayed with the p-column-title with the words 'Grand Total'
2. When the table is responsive the footer should be displayed with the 'Grand Total' label.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

All of the table should be responsive, header, footer, expansion row, caption and summary.  All should be displayed.

**Please tell us about your environment:**

Windows 10 Pro

* **Angular version:**

10.0.8

* **PrimeNG version:** 5.X

    "bootstrap": "^4.5.2",
    "primeicons": "^4.0.0",
    "primeng": "^10.0.0-rc.4",

**Comment by cagataycivici** [comment]
Please see;

#8611

Since you'll have full control with the css media queries in your own impl, you can easily add print support as well.

**Comment by PHuhn** [comment]
Hey:
I am confused.  This is not the @print media request.  The footer disappears if the screen is responsive in the browser.
Phil

**Comment by PHuhn** [comment]
My solution:
[https://stackoverflow.com/questions/63816628/primeng-v10-0-0-p-table-footer-disappears-when-responsive-true-and-grid-is/64230741#64230741](https://stackoverflow.com/questions/63816628/primeng-v10-0-0-p-table-footer-disappears-when-responsive-true-and-grid-is/64230741#64230741)
