### ISSUE TITLE
Calendar popup won't open ever when showOnFocus is disabled

### ISSUE THREAD

**Issue by Tisho-Angelov** [primefaces/primeng#9240]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-wtztvk?file=src/app/app.component.html

**Current behavior**
The calendar is not being opened on click when `showOnFocus` is set to false

**Expected behavior**
I would expect that `showOnFocus` flag should control only the case when you are focusing the calendar. So it should still be opened when you click the input. Correct me if my understanding is wrong.

**Please tell us about your environment:**
Windows 10

Any OS

* **Angular version:** 9.1.9

* **PrimeNG version:** 9.0.6

* **Browser:** [ Chrome 85 but I suppose it would be valid everywhere ]
 
* **Language:** [ TypeScript 3.8.3 ]

![image](https://user-images.githubusercontent.com/45821204/92253468-35222c00-eed8-11ea-823d-ef7918dc1ac1.png)

**Comment by cagataycivici** [comment]
This is by design, showOnFocus="false" is usually used with [showIcon]="true" so that the calendar icon is used to open the overlay and input is just used for manual input.
