### ISSUE TITLE
PrimeNg - Dropdown with grouping option

### ISSUE THREAD

**Issue by AlbaSS18** [primefaces/primeng#9241]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
In my project, I'm using the dropdown element of PrimeNG. In the official PrimeNG documentation ([dropdown](https://www.primefaces.org/primeng/v8.2.6-lts/#/dropdown)) it says that it is possible to group elements using SelectItemGroup and SelectItem. However, that page only teaches how to do it with two levels. I would like to know how to add one more level.

My idea would be the following and I would like to know how I can get it:

```
this.groupedCars = 
[
    {
        label: 'Germany', 
        items: 
            [
                {
                    label: 'Audi', 
                    items: 
                        [   
                            {
                                label: 'Audi A1',
                                value: 'Audi A1'
                            },
                            {
                                label: 'Audi A3',
                                value: 'Audi A3'
                            }
                        ]
                },
                {
                    label: 'BMW', 
                    value: 'BMW'
                },
                {
                    label: 'Mercedes',
                    value: 'Mercedes'
                }
            ]
    }
]
```
Below I show the interfaces of SelectItemGroup and SelectItem.

The SelectItemGroup interface:

```
export interface SelectItemGroup {
    label: string;
    value?: any;
    items: SelectItem[];
}
```
The interface SelectItem:

```
export interface SelectItem {
    label?: string;
    value: any;
    styleClass?: string;
    icon?: string;
    title?: string;
    disabled?: boolean;
}
```
I have tried to convert SelectItem to SelectItemGroup but I get an error that it is not possible because SelectItem does not have the Item property.

**Please tell us about your environment:**

* **Angular version:** 8.2.14

* **PrimeNG version:** 8.1.1

**Comment by AdityaToke** [comment]
Hey, @AlbaSS18  Can you elaborate more on what does level means? It would be great more clarity on the issue.

**Comment by AlbaSS18** [comment]
> Hey, @AlbaSS18 Can you elaborate more on what does level means? It would be great to have more clarity on the issue.

Hey, @AdityaToke , look at the image. When I talk about levels, I mean that underneath 'Audi' there is another SelectItem called 'Audi A1'.  However, a SelectItemGroup does not have an array of SelectItemGroup but of SelectItem and I don't know how to do it. Do you have any ideas?
![image](https://user-images.githubusercontent.com/46462037/92303129-5f282c80-ef72-11ea-930f-4e3a251d2eeb.png)

**Comment by AdityaToke** [comment]
@AlbaSS18  No I don't have any idea regarding it, also checked code they have not implemented where we have SelectItemGroup inside SelectItemGroup or any other kind of group nesting. Also in the doc link, you provided was not able to figure it out where its mentioned that we can use them both (selectItemGroup and selectItem).

**Comment by cagataycivici** [comment]
Only one level is supported, you might be interested in Tree component if you have a nested structure. Btw I'm not sure if native optgroup supports nesting.
