### ISSUE TITLE
Mobile/Touch screen - Swipe left and and Swipe right is not working in Galleria

### ISSUE THREAD

**Issue by noteme-io** [primefaces/primeng#9243]
**Current behavior**
 Mobile/Touch screen - Swipe left and Swipe right is not working in Galleria

**Expected behavior**
In Mobile/Touch screen, swiping images  should work like Carousel 

* **PrimeNG version:** 10.0.0-rc.4

**Comment by apicpich** [comment]
I found the same issue.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by riticulus** [comment]
Any chance to put that feature on the roadmap? Swiping is the most intuitive way to use the gallery on mobile devices.

Thanks for consideration.
