### ISSUE TITLE
I am not found nova-light Them in prime ng 10 Update

### ISSUE THREAD

**Issue by Rjitendra** [primefaces/primeng#9248]
Current behavior

After Upgarde Prime ng to 10 i didn't find nova-light/theme.css.

Expected behavior

nova-light/theme.css.

Angular version: 10.1.0

PrimeNG version: 10.0.0

Browser: all

Language: all

**Comment by PHuhn** [comment]
Hey:
It no longer exists.  Try 'nova'  The themes are now:
```
arya-blue, arya-green, arya-orange, arya-purple,
bootstrap4-dark-blue, bootstrap4-dark-purple, bootstrap4-light-blue, bootstrap4-light-purple,
luna-amber, luna-blue, luna-green, luna-pink,
md-dark-deeppurple, md-dark-indigo, md-light-deeppurple, md-light-indigo,
mdc-dark-deeppurple, mdc-dark-indigo, mdc-light-deeppurple, mdc-light-indigo,
nova, nova-accent, nova-alt, 
rhea,
saga-blue, saga-green, saga-orange, saga-purple,
vela-blue, vela-green, vela-orange, vela-purple
```

**Comment by ruchiagrawal2** [comment]
I have the same issue. I try other themes in prime ng 10 but they change the look and feel of application tremendously. 
Can you please advise which prime ng 10  theme will be closest to nova-light ?

**Comment by PHuhn** [comment]
Hey:
I am a fellow user.  I was nova-light, I am now using nova.  That said, much seems to have been changed.  The ui grid stuff is gone.  You can move to Primefaces flex grid, but I went with **bootstrap grid**.  **bootstrap grid** does not require jquery. I globally replaced the following:
```
	ui-grid-row -> row
	nsg-content	-> container
	ui-grid-col-	-> col-md-
	ui-button-	-> p-button-
	 ui-inputgroup	-> ''
	 ui-inputtext	-> ''
```
I moved from importing the theme from style.css and in the angular.json file the following:
```
  "styles": [
    "node_modules/bootstrap/dist/css/bootstrap-grid.min.css",
    "node_modules/primeng/resources/themes/nova/theme.css",
    "node_modules/primeng/resources/primeng.min.css",
    "node_modules/primeicons/primeicons.css",
    "src/styles.css"
  ],
```
I then globally searched for ui- to clean up the remaining.  I had to relearn bootstrap.  I eventually went with something more like **class='col-lg-8 col-md-7 col-sm-12'**.

I personally think this is a better design, that I am not using the proprietary ui-grid stuff.  The p- CSS is for the specific PrimeNG controls.

Phil

**Comment by ruchiagrawal2** [comment]
@PHuhn , Thanks for your response. That sounds like quite a few changes .  Is there a theme which comes very close to nova-light and needs minimum changes. We want to take that route for some time before we are ready to make bigger changes.

**Comment by PHuhn** [comment]
Hey:

I am not familiar with any minimum update theme.

The major change was the ui- CSS theme.  If you have not used PrimeNG's ui-grid stuff just then just change things like ui-button to p-button.

You can review what was available under PrimeNG 9 CSS and compare it to 10.
9.1
ui-button | Button element
ui-button-icon | Icon element
ui-button-text | Label element of the button

10.0
p-button | Button element
p-button-icon | Icon element
p-button-text | Label element of the button

Phil

**Comment by MasoodEsmaeili37** [comment]
In package.json unter Dependecies stand ein aktuellerer primeNG 11.4.0
Dies habe ich auf ältere geändert, dann hat es funktioniert:
primeNG 8.0.0

**Comment by PHuhn** [comment]
I am a fellow user.  Yes, nova-light is no longer available.  I moved to nova, but you will need to change from CSS starting with ui- to p-.  The current themes are as follows:


theme | theme | theme
-- | -- | --
arya-blue | luna-green | nova-accent
arya-green | luna-pink | nova-alt
arya-orange | md-dark-deeppurple | rhea
arya-purple | md-dark-indigo | saga-blue
bootstrap4-dark-blue | md-light-deeppurple | saga-green
bootstrap4-dark-purple | md-light-indigo | saga-orange
bootstrap4-light-blue | mdc-dark-deeppurple | saga-purple
bootstrap4-light-purple | mdc-dark-indigo | vela-blue
fluent-light | mdc-light-deeppurple | vela-green
luna-amber | mdc-light-indigo | vela-orange
luna-blue | nova | vela-purple

**Comment by TotzkePaul** [comment]
# Migrate From Nova-Light
## Nova Themes - Nova Light is just Nova now
They have been reimplemented along with Luna and Rhea for backward compatibility with the new styling. To sync with PrimeReact and PrimeVue, they are renamed.

nova-light => nova
nova-dark => nova-alt
nova-colored => nova-accent

https://forum.primefaces.org/viewtopic.php?t=63372

## Update ui classes
https://github.com/primefaces/primeng/wiki/PrimeOne-Migration

* ui-widget to p-widget
* ui-button to p-button 
* ui-* to p-* updates are needed in general

I'll update this post if I learn more.

**Comment by muhydeen95** [comment]
> 

this works for me, thank you
