### ISSUE TITLE
Controlling autocomplete via directive

### ISSUE THREAD

**Issue by lachty** [primefaces/primeng#9249]
**I'm submitting a ... (check one with "x")**

[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/angular-ivy-jbmlqr

**Current behavior**
When using directive (AutocompleteDirective in example) to control autocomplete component, autocomplete doesn't work correctly - prompts don't show up after first user input. It shows up when user writes second input. Also loading icon is showing randomly.

**Expected behavior**

Prompts should show up immediately after first user input.

**Minimal reproduction of the problem with instructions**
1) Insert "t" into autocomplete first in example - prompt doesn't show up
2) Insert second letter after some time (default component timeout) - the prompt show up

The prompt is possible to made visible also in the first step - insert "t" and press arrow down.
The loading icon is showing randomly during editing input.

* **Angular version:**
Angular 10

* **PrimeNG version:**
Version 8.x.x is OK
Version 9 is affected by this bug
Version 10 is affected by this bug

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome, Firefox
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
