### ISSUE TITLE
p-InputMask gets marked as dirty without value change

### ISSUE THREAD

**Issue by gonozalviii** [primefaces/primeng#9251]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Behavoir can be observed in the official show case: https://primefaces.org/primeng/showcase/#/inputmask

**Current behavior**

An InputMask gaining and losing focus gets marked as dirty, even though no value was changed.

**Expected behavior**

The InputMask only gets marked as dirty when the value was changed.

**Minimal reproduction of the problem with instructions**

- goto official showcase
- click into an InputMask
- click somewhere else
- InputMask has class "ng-dirty"

**What is the motivation / use case for changing the behavior?**

Validation should only be shown when the user changed the value.
InputMask should behave like the other components.

* **Angular version:** 10.1.0

* **PrimeNG version:** 10.0.0-rc.4

* **Browser:** all
 
* **Language:** all

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
