### ISSUE TITLE
Translation issues with ngx-translate and Menubar component after update to PrimeNG 10

### ISSUE THREAD

**Issue by Pryanishnik** [primefaces/primeng#9256]
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

I have a menubar component 
```
<p-menubar [model]="items">
</p-menubar>
```

Also, I provided a translator, that perfectly worked with Angular 9 + Primeng 9.1.4

```
 translate.onLangChange.subscribe((event: LangChangeEvent) => {
      this.processMenuTranslation(this.items);
    })
```
Where 
 ```
processMenuTranslation( children:MenuItem[]){
    for (let item of children){
        if(item.separator)
          continue;
      item.label = this.translate.instant(item.id);
      if(item.items){
        this.processMenuTranslation(item.items);
      }
    }
  }
```

After I`d updated PrimeNG and angular to version 10, component is not rerendered. So, translation applies only when hover is triggered. How can I overcome this issue?

**Comment by cagataycivici** [comment]
PrimeNG components switched to OnPush detection so you need to create a new reference to trigger change detection;

```typescript
translate.onLangChange.subscribe((event: LangChangeEvent) => {
      this.processMenuTranslation(this.items);
      this.items = {...this.items}
    })

```

More info at;

https://www.google.com/search?client=safari&rls=en&q=onpush+blog-university&ie=UTF-8&oe=UTF-8

**Comment by Pryanishnik** [comment]
Oh, thank you

**Comment by sotoh** [comment]
Interesting, that's solve my issue with p-table, editing the source array doesn't refresh. Thank you, this made my day. Glad to be in the discord group.
