### ISSUE TITLE
p-table with Row Grouping doesn't work with column filter  and column sorting

### ISSUE THREAD

**Issue by ymasha** [primefaces/primeng#9261]
I am using p-table with Row Group, filters, and column sort.
Using any column sort or filter breaks the row grouping. 
See a sample project for repro. 
Try to filter by year "1990" you will get 2 rows as a result but the brand group is lost. Sorting makes compete mass by putting rows on the top without any group

https://stackblitz.com/edit/primeng-tablerowgroup-demo-vp1wjb?file=src%2Fapp%2Fapp.component.html

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Comment by ymasha** [comment]
this so unprofessional, closing the issue without fixing it.
