### ISSUE TITLE
p-steps: RouterLink works although steps are readonly

### ISSUE THREAD

**Issue by VILLAN3LL3** [primefaces/primeng#9263]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
app: https://github-mtd9jd.stackblitz.io
editor: https://stackblitz.com/edit/github-mtd9jd?file=src/app/app.component.html

**Current behavior**
the p-steps component is readonly by default. The activeIndexChange event doesn't fire which is correct.
But routerLinks that are defined in the model work anyway, which shouldn't.

**Expected behavior**
If the p-steps component is readonly the routerLinks shouldn't work as well

**Minimal reproduction of the problem with instructions**
see stackblitz example

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
n.a.

* **Angular version:** 5.X
10.1.0

* **PrimeNG version:** 5.X
9.1.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
n.a.
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
