### ISSUE TITLE
p-autoComplete bug with forceSelection=true

### ISSUE THREAD

**Issue by stephanecot** [primefaces/primeng#9266]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/primeng-autocomplete-demo-6nf352?file=src/app/app.component.html

**Current behavior**
When I used [forceSelection]="true" and I select the value with my keyboard, on focus out, the value is cleaned.
It doesn't appened with the mouse selection.

* **Angular version:** 10.X

* **PrimeNG version:** 10.X

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
