### ISSUE TITLE
p-dialog closes on resize when modal and disssmissableMask are set to true.

### ISSUE THREAD

**Issue by schoenp711** [primefaces/primeng#9267]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/primeng-dialog-demo-t1k97a?file=src%2Fapp%2Fapp.component.html

**Current behavior**
When the `modal` and `dissmissableMask` properties are set to true on a `p-dialog` if you resize the dialog and your cursor ends up outside of the dialog the dialog will close rather than resizing. 

**Expected behavior**
The dialog resizes rather than closing and only closes if you full click outside of the dialog. 

**Minimal reproduction of the problem with instructions**
![primedialogissue](https://user-images.githubusercontent.com/49349524/92745086-0977c980-f350-11ea-9a0c-77fe7adaf1f3.gif)

**What is the motivation / use case for changing the behavior?**
You should be able to resize the dialog without it closing even if you have `modal` and `dissmissableMask` set to true.

**Please tell us about your environment:**

* **Angular version:** 10.X

* **PrimeNG version:** 10.X

* **Browser:** [all Chrome | Firefox]

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
