### ISSUE TITLE
Can't bind to 'chooseIcon' since it isn't a known property of 'p-fileUpload'.

### ISSUE THREAD

**Issue by soyiatgit** [primefaces/primeng#9270]
I was trying to modify the default icon (pi pi-plus) for the` p-fileUpload.` The documentation [here](https://www.primefaces.org/primeng/showcase/#/fileupload) says that the icon can be modified by using the` [chooseIcon] `property. However, while using the aforementioned property in the basic mode of `p-fileUpload`, I get the following error:

`<h5>Basic</h5>
    <p-fileUpload mode="basic" name="demo[]" url="./upload.php" accept="image/*" maxFileSize="1000000" (onUpload)="onBasicUpload($event)"></p-fileUpload>
`

```
[exception-handler.service.ts:32 Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'chooseIcon' since it isn't a known property of 'p-fileUpload'.
1. If 'p-fileUpload' is an Angular component and it has 'chooseIcon' input, then verify that it is part of this module.
2. If 'p-fileUpload' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.]
```
Can you please get it checked. Meanwhile is there any workaround to alter the icon. I would rather use `pi pi-arrow-up` but I am not sure how to override the default `pi pi-plus` class.

P.S: This only occurs in mode="basic" and works fine in mode="advanced". Since the docs do not specify this, I believe this is a miss.

**Comment by soyiatgit** [comment]
Ok, I checked the code and apparently the implementation for basic mode is entirely different from the advanced mode. However, it would be better if all the properties for choose button should be applicable to basic mode as well. 

In any case, the docs should specify the correct behavior of the properties.

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.
