### ISSUE TITLE
InputNumber: cannot insert fractional digits when minFractionDigits=0

### ISSUE THREAD

**Issue by Timmeeeey** [primefaces/primeng#9272]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-cshg3y

**Current behavior**
If `minFractionDigits` = 0 and `maxFractionDigits` > 0 you cannot insert any fractional digits.

**Minimal reproduction of the problem with instructions**
`<p-inputNumber mode="decimal" [minFractionDigits]="0" [maxFractionDigits]="5"></p-inputNumber>`

* **Angular version:** 10

* **PrimeNG version:** 10.0.2

**Comment by pete4dev** [comment]
I also encountered this issue.

**Comment by anujtrehan** [comment]
got any solution for this?

**Comment by FabienDehopre** [comment]
this issue also exists in primeng 9.x

**Comment by anujtrehan** [comment]
it the issue fixed in primeng 10.x ??

**Comment by FabienDehopre** [comment]
I cloned their stackblitz from the official documentation page: https://stackblitz.com/edit/primeng-inputnumber-demo-4apujo?file=src%2Fapp%2Fapp.component.html
There is one example with the minFractionDigits set to 0 and one bigger than 0. So, you can see that the first one does not allow entering decimal digits by hand or by pasting (it works when bound to a value with decimals). 
The second one (with minFractionDigits set to 2) allows entering decimal value by hand but has really strange behavior when pasting (if you copy/paste a value in the second input, the value becomes 100 when clicking outside the input or pressing enter).

**Comment by evandouglas** [comment]
I am experiencing this as well. 
`<p-inputNumber mode="decimal" [minFractionDigits]="0" [maxFractionDigits]="5">`
does not allow me to input any decimal points, but this:
`<p-inputNumber mode="decimal" [minFractionDigits]="1" [maxFractionDigits]="5">`
does. The downside here is that it always displays '.0' on my numbers if no other decimal is put in.

**Comment by serdarceran** [comment]
Hello @yigitfindikli,

We'd be appreciated if the possible fix is applied to the primeng 9.1.3 as well?

**Comment by FabienDehopre** [comment]
> 
> 
> Hello @yigitfindikli,
> 
> We'd be appreciated if the possible fix is applied to the primeng 9.1.3 as well?

Indeed, it would be really nice

**Comment by Sun3** [comment]
Any updates? This feature is very important to be able to allow the user to not enter any fractions or enter them if necessary.

Thanks.

**Comment by jvdyck** [comment]
I have the same problem! Would be nice if this gets fixed.

**Comment by jmynes** [comment]
Same problem, any acknowledgement?
The behavior I'm seeking is to support decimals, but not necessarily append one until the user has actually input a decimal.

This is communicated to the user via a placeholder I've set of 0.00, without actually enforcing a decimal on all inputs

**Comment by OPunktSchmidt** [comment]
Any news? From our perspective, the error is very critical. For us, PrimeNG is useless if it doesn't work.

**Comment by ThorstenKunz** [comment]
Same issue here

**Comment by saul-lopez** [comment]
This issue is also present in 11.3.1.

**Comment by danbord** [comment]
Seriously?  This is still opened?  Bug is still in 11.3.2

**Comment by Anubarak** [comment]
> Seriously? This is still opened? Bug is still in 11.3.2

Yeah and it is closed and ignored in other prime projects as well

**Comment by mertsincan** [comment]
Sorry for the delayed response! Fixed now ;) 

Best Regards,

**Comment by nascarjake** [comment]
This does not appear to be fixed in primeng 11.4.5
Could we get the same fix applied for angular so that the number inputs work like normal allowing me to type a decimal in myself?

**Comment by gschafra** [comment]
Issue still exists in 11.4.9 LTS

**Comment by brano-p** [comment]
No solution for this after 2 years? Why is this closed anyway? It's a regular bug.

**Comment by theophile-wallez** [comment]
The bug is still there

**Comment by Raphzor** [comment]
Issue still exists on 14.0.1 ...

**Comment by Mihai-MCW** [comment]
Issue still exists on 15.0.0

**Comment by glenndejaeger** [comment]
We have an issue with PrimeVue and I think it's the same as described or strongly related.
- InputNumber with minFractionDigits set (for example to 2)
- Default value after the decimal point is 00
**- When clicking after the decimal point and typing 0, nothing happens while I would expect the cursor to shift 1 position to the right**
- When clicking after the decimal point and typing any number other than 0, the 0 is replaced by the entered number and the cursor does shift 1 position to the right. That is expected behaviour.

When entering 0 before the decimal point, the 0 is just inserted at that position, which is expected behaviour as well.

See https://stackblitz.com/edit/gagodi-sjvwmv?file=src%2FApp.vue
