### ISSUE TITLE
AutoComplete not autoresize

### ISSUE THREAD

**Issue by certifirm** [primefaces/primeng#9274]
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
AutoComplete not autoresize.  

**Expected behavior**
Autocomplete autoresize in more than one line.

**Minimal reproduction of the problem with instructions**
Test in the official page.

* **Angular version:** 5.X
<!-- Check whether this is still an issue in the most recent Angular version -->
Angular 10

* **PrimeNG version:** 5.X
<!-- Check whether this is still an issue in the most recent Angular version -->
PrimeNg 10.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 3.9

* **Node (for AoT issues):** `node --version` =   
node10

**Comment by ecologicrecicla** [comment]
It's incredible that not works

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
