### ISSUE TITLE
InputNumber: maxFractionDigits not working when prefix/suffix is set

### ISSUE THREAD

**Issue by Timmeeeey** [primefaces/primeng#9275]
**I'm submitting a ...** 
```
[x] bug report
[ ] feature request
[ ] support request
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-inputnumber-demo-fcuk7c

**Current behavior**
When `prefix` or `suffix` is set `maxFractionDigits` doesn't work. If you type more than `minFractionDigits` then the input is cleared.

**Minimal reproduction of the problem with instructions**
see stackblitz.
Try to type a number with more than 2 fractional digits.

* **Angular version:** 10.1

* **PrimeNG version:** 10.0.2

* **Browser:** Chrome 85 | Firefox 80

**Comment by loicCQAM** [comment]
Also, if you start with a negative sign, the cursor automatically goes at the end of the input. 
Happens without prefix/suffix as well.

**Comment by anton-brass** [comment]
same for us

**Comment by martin1ehm** [comment]
The problem still exists with Primeng 12.0.0.

I noticed that the problem with `minFractionDigits` only exists when the suffix starts with a whitespace character. (space, non-breaking space, tab...)

The problem with negative values (minus sign) is reproducible with and without the suffix attribute.

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primeng/commit/d172c58b500dca66c378accad478ad1a09021ce0

Best Regards,
