### ISSUE TITLE
p-calendar: onSelect triggered when blur time selection

### ISSUE THREAD

**Issue by hokutoNoDiego** [primefaces/primeng#9276]
Hi,
using **p-calendar**, i emit an output when **(onSelect)** event is triggered (date selected). The fact is that this event is triggered even when **blur the arrows for time selection**. I don't know if this is wanted, but i think it is a bug because the date don't change, is only a blur event.

I'm using **primeng vers. 9.1.3**

Thank you!

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
