### ISSUE TITLE
Splitbutton broken, if word-wrap: break-word; is set

### ISSUE THREAD

**Issue by JacobSonnichsen** [primefaces/primeng#9278]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**
Splitbutton design is broken, if "word-wrap: break-word;" is set

**Expected behavior**
Splitbutton looks normal.

**Minimal reproduction of the problem with instructions**
place style "word-wrap: break-word;" in the html code

**What is the motivation / use case for changing the behavior?**
PrimeNg version 9, does not break the design, if word-wrap: break-word; is set.

**Please tell us about your environment:**
Windows 10, Windows Server 16

* **Angular version:** 5.X
9 and 10

* **PrimeNG version:** 5.X
10

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Firefox, Chrome, Edge
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

* **Node (for AoT issues):** `node --version` =

**Comment by maicongodinho1** [comment]
Hi @JacobSonnichsen, i cannot see the problem in the stackblitz example you put in. You can send a new one please?

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
