### ISSUE TITLE
Lenient filtering does not work with Tree Table

### ISSUE THREAD

**Issue by RomainLefeuvre** [primefaces/primeng#9281]
**I'm submitting a ...**
```
[ x] bug report 
[ ] feature request
[ ] support request 
```

**Plunkr Case (Bug Reports)**
https://primeng-treetablefilter-issue.stackblitz.io/

**Current behavior**
When a parent node matches the filtered global term and contains several children one of which also matches the filtered term, this results in filtering the other children.

Initial table :
![image](https://user-images.githubusercontent.com/33905216/93111218-9b683500-f6b6-11ea-9006-b696f2186c0c.png)

Filtered table :
Type "Marie" on the global filter area.
![image](https://user-images.githubusercontent.com/33905216/93111385-d23e4b00-f6b6-11ea-9973-7e03116acf65.png)
We can see that a child of the first node is not displayed while it matches with the filter.

**Expected behavior**
"In lenient mode when the query matches a node, children of the node are not searched further as all descendants of the node are included. On the other hand, in strict mode when the query matches a node, filtering continues on all descendants."

The child "Hugues Dupis" should also be displayed.

**Minimal reproduction of the problem with instructions**
To reproduce the bug the following conditions must be met: 
- the filtered term is contained in the parent node .
- one of the child nodes contains an attribute that contains the term. (it must not be the attribute corresponding to the first column).
- The parent must contain child nodes that do not match the filter.

**Please tell us about your environment:**

* **Angular version:** 9.1.0
This is still an issue in the most recent Angular version

* **PrimeNG version:** 9.1.0
This is still an issue in the most recent Angular version 

* **Browser:** [all ]

 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =   v12.18.1

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
