### ISSUE TITLE
PrimengX Float Textarea Filled

### ISSUE THREAD

**Issue by cheesgno** [primefaces/primeng#9283]
**I'm submitting a ...**
```
[X ] bug report => Search github for a similar issue or PR before submitting
```

**Current behavior**
After update to Primeng X all the textarea elements  with existing values inside a form comes without the css class "p-filled".
In this case the label of the textarea is superimposed with the text

**Expected behavior**
the float label for textarea must not superimposed text when it is present on form load

PrimeNG X: 10.0.0 
* **Angular version:** 10.1.1

* **PrimeNG version:** 10.0.0

* **Browser:** Chrome  Firefox  IE  Safari

* **Node (for AoT issues):**   14.4.0

**Comment by cheesgno** [comment]
After more tests the problem persist only on textarea with existing values populate via reactive form.

**Comment by lisuizhe** [comment]
+1
same issue happened only for reactive form, no problem for template-driven form

**Comment by ProfEibe** [comment]
I can confirm this issue. Prefilled reactive form textarea labels are not floating initially.

**Comment by averath** [comment]
Temporary workaround is to add class conditionally:
```html
<textarea [class.p-filled]="form.controls.CONTROL_NAME.value"
              formControlName="CONTROL_NAME" pInputTextarea></textarea>
```

**Comment by mishellnovosel** [comment]
I would report the same behavior for the input text field ( pInputText ) on Reactive form:
` <span class="p-float-label">
 <input id="float-input" type="text" pInputText formControlName="providerName">
        <label for="float-input">Provider name</label>
      </span>`

when calling a components with prefilled values, _.p-filled_ class is missing and therefore placeholder is not floating.
temp fixed from @averath seems to fix this issue:  _[class.p-filled]="form.controls.providerName.value"_

"primeng": "10.0.3"
"@angular/core": "10.1.4"

**Comment by jonnomk** [comment]
I can confirm this is still an issue - I used averath's suggestion to resolve for now.  Thanks averath.

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.3.0, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

v11.3.0 example for reactive forms: https://stackblitz.com/edit/primeng-inputtextarea-demo-xvaesv
