### ISSUE TITLE
Calendar - Keyboard Navigation Support

### ISSUE THREAD

**Issue by NileshJariya** [primefaces/primeng#9287]
p-calendar is not supported by keyboard accessibility.

Need to use the arrow key in the calendar component but not able to use the up, down, left-right keyboard arrow key in the component.

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
