### ISSUE TITLE
Dropdown virtual scroll white-space

### ISSUE THREAD

**Issue by kylecooleylba** [primefaces/primeng#9291]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
A nowrap was added to p-dropdown-item which when using virtual scroll causes an x scroll bar to appear instead of the PrimeNg 9 and prior line breaks for any text longer than the component width. There is no issue when not using virtual scroll as the max width seems to be calculated before render.

![image](https://user-images.githubusercontent.com/62561537/93527819-6bfc3700-f907-11ea-99a9-d16c6522ce45.png)

![image](https://user-images.githubusercontent.com/62561537/93528104-cf866480-f907-11ea-8a24-11ce65aa4a90.png)

I'm requesting that when using virtual scroll and the max width is not known, enable wrapping to prevent x scroll bars

**Current behavior**
With virtual scroll enabled the selection box is a fixed width of the dropdown component width with both x and y scroll bars.

**Expected behavior**
White space wrapping to prevent x scroll bar when using virtual scroll

**Minimal reproduction of the problem with instructions**

Any virtual scroll dropdown component

**What is the motivation / use case for changing the behavior?**

Retain old functionality for virtual scroll.

* **Angular version:**  10

* **PrimeNG version:** 10

* **Browser:** all
 
* **Language:** all

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
