### ISSUE TITLE
Slider 0.0 t 1.0 step 0.01 error on maximum

### ISSUE THREAD

**Issue by bluepanter** [primefaces/primeng#9293]
[ x] bug report => Search github for a similar issue or PR before submitting

**Plunkr Case (Bug Reports)**

https://github-e3boxr.stackblitz.io

Works also at https://www.primefaces.org/primeng/showcase/#/slider sample if you add min=0 max=1 step=0.01 attributes to first slider.

**Current behavior**
A Slider with min 0.0, max 1.0 and step size of 0.01 creates an error as soon as it reaches maximum of 1.0
`
Error in /turbo_modules/primeng@10.0.0/bundles/primeng-slider.umd.js (336:29)
val.toFixed is not a function
`

**Expected behavior**
It should be possible to reach 1.0 without error.

**What is the motivation / use case for changing the behavior?**
For sliders that should generate a percentage value as a fraction 0-1

**Minimal reproduction of the problem with instructions**
Open https://github-e3boxr.stackblitz.io and set the slider to the maximum.

**Please tell us about your environment:**
Chrome and Firefox, Win10

* **Angular version:
10.0.14

* **PrimeNG version:
V10.0.0

* **Browser:** 
[Chrome, Firefox, probably all ]

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
