### ISSUE TITLE
After upgrading from 9 to 10 frozen columns ceased to be synchronized with scrollable columns in case on virtual scroll

### ISSUE THREAD

**Issue by florin-f-manea** [primefaces/primeng#9294]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
[https://stackblitz.com/edit/angular-fxbcfy]((https://stackblitz.com/edit/angular-fxbcfy))

**Current behavior**

After upgrading from 9 to 10 frozen columns ceased to be synchronized with scrollable columns in case on virtual scroll

**Comment by yigitfindikli** [comment]
https://github.com/primefaces/primeng/commit/c85676603d8480f74060598d561a63de6933aac4
