### ISSUE TITLE
exportCSV to use header instead of field for column name

### ISSUE THREAD

**Issue by tengel92** [primefaces/primeng#930]
When opening a CSV in Excel column name is based on field and shows as "BizType" but it would be nice for it to based upon the header field "Business Type". 

<p-column hidden="true" field="BizType" header="Business Type" [sortable]="true" [filter]="true" filterMatchMode="contains"></p-column>

**Comment by madthad91** [comment]
i believe this has been fixed. I'm not sure where, but I use export on my table and the headers are used.

**Comment by sudheerj** [comment]
The current version is displaying as per header values.So we are closing this issue.
