### ISSUE TITLE
Undesirable dialog closure with dismissableMask = true

### ISSUE THREAD

**Issue by nnfedorov** [primefaces/primeng#9300]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-xznj2r?file=src/app/app.component.html

**Current behavior**
Assume we have a modal dialog with dismissableMask option equal to 'true'. If user hits mouse down inside dialog, then moves cursor outside it and releases mouse (mouse up) on dialog mask, 'click' event is still fired causing undesirable dialog closure.

**Expected behavior**
Dialog shouldn't be closed.

**What is the motivation / use case for changing the behavior?**
Dialog can contain some input field. User tries to select its value but occasionally releases mouse outside dialod that leads to its unexpected closure.

**Please tell us about your environment:**

* **Angular version:** 10.0.14

* **PrimeNG version:** 10.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome Latest. 
In Firefox this issue is not reproduced

**Comment by cagataycivici** [comment]
Duplicate;

#9282
