### ISSUE TITLE
p-autoComplete multiple delayed rendering

### ISSUE THREAD

**Issue by leblancmeneses** [primefaces/primeng#9301]
my template
https://stackblitz.com/edit/angular-ivy-primeng?file=src%2Fapp%2Fapp.component.html

your template
https://stackblitz.com/edit/github-mzxk6c?file=src%2Fapp%2Fapp.component.html

**Current behavior**
p-autoComplete  [multiple]="true" delays rendering bound items

**Expected behavior**
bound properties should be visible immediately

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/angular-ivy-primeng?file=src%2Fapp%2Fapp.component.html
verify [(ngModel)]="tags"  items do not appear on input 
click on input
watch bound items appear

using latest on npm, on chrome.

Thanks

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
