### ISSUE TITLE
Regression issue #9154

### ISSUE THREAD

**Issue by MartinBaptiste** [primefaces/primeng#9302]
**I'm submitting a bug
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
With fix update this._value in Table with new table referance (ex: https://github.com/primefaces/primeng/blame/master/src/app/components/table/table.ts#L830) but model only on input and if update model with another process (ex: Dynamic add element in table), after sort your referance (of this_value) changed and your update don't work.

**Bypass**
Add update your model in onSort (ex: onSort="model = table.value") for bypass bug

**Expected behavior**
Add @Output on value or remove unreferance internal model

* **Angular version:** 10.0.12

* **PrimeNG version:** 10.0.0

* **Browser:** all

**Comment by lucini** [comment]
Same here

**Comment by yigitfindikli** [comment]
I couldn't replicate it with v11.3.0. 

Stackblitz example: https://stackblitz.com/edit/primeng-tablevirtualscroll-demo-eihkdb
