### ISSUE TITLE
Serenity Layout not work in primeng version 10.0.0

### ISSUE THREAD

**Issue by darckyn** [primefaces/primeng#9303]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

The CSS Serenity Layout theme not work in primeng 10.0.0

**Expected behavior**

The CSS Serenity Layout theme work

**Minimal reproduction of the problem with instructions**

Just uptade to version 10.0.0 and the Serenity Layout stop working.
no console error is show.
Works normal in version  9.1.3

**What is the motivation / use case for changing the behavior?**

To use Serenity Layout

**Please tell us about your environment:**

Linux Mint 19.3 Cinnamon
Visual Studio Code 1.49.1

* **Angular version:**  10.1.2

* **PrimeNG version:** 10.0.0

* **Browser:** [all]

* **Language:** [all | TypeScript 4.0.3]

* **Node (for AoT issues):** `node --version` =   v10.22.1

**Comment by cagataycivici** [comment]
Please see;

https://github.com/primefaces/primeng/wiki/Template-Updates
