### ISSUE TITLE
TreeTable onEditComplete not triggered

### ISSUE THREAD

**Issue by zhq3k** [primefaces/primeng#9307]
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Using TreeTable and edit the binding data, when input the value on one cell and using mouse click to another cell, onEditComplete event not triggered.

**Current behavior**
onEditComplete event not triggered.

**Expected behavior**
onEditComplete will be triggered when click to another cell




**Please tell us about your environment:**

Angular version: 10

PrimeNG version: 10.0.0

Browser: Chrome 85

Language: TypeScript 3.9

**Comment by faheemworkspace** [comment]
any fix to this ??

**Comment by Krustie101** [comment]
Comparing the code between "treeTable" and "table" regarding editability, I see the code in "table" is a little bit more sophisticated in handling editability. I think some fixes/features still need to be ported from "table" to "treetable".

- This particular problem seems to be situated in the bindDocumentListener but I see that also tabbing 
-  I see also differences regarding tabbing that probably allow to close an invalid cell that is being edited.

**Comment by InfoCharlesM** [comment]
I think this is the same issue than https://github.com/primefaces/primeng/issues/9113

I got the same issue, hope it will be fixed soon :D

**Comment by InfoCharlesM** [comment]
@yigitfindikli 
Is the review still planned ?
I can't use prime-tree-tables because of this and the bug on p-calendars inside tables.

**Comment by InfoCharlesM** [comment]
I'm still facing the issue on this stackblitz @yigitfindikli is it normal ?
https://stackblitz.com/edit/primeng-treetableedit-demo-c2brq1?file=src/app/app.component.html

**Comment by InfoCharlesM** [comment]
@yigitfindikli could you please give me an answer ?

**Comment by yigitfindikli** [comment]
@InfoCharlesM You need to use v11.3.1 or higher.

**Comment by Fakerinc** [comment]
same here. I still have this problem. 
onEditComplete event ist not fired when clicking another cell.

**Comment by gayatriraichandani** [comment]
It's still not working. Any idea when will it be available?

**Comment by mohammadaajo** [comment]
I have the same issue on 15.4.1.
