### ISSUE TITLE
p-table -> thead and tbody are overlapping to each other which causing the focus issue in accessibility.

### ISSUE THREAD

**Issue by prasadkhegade** [primefaces/primeng#9308]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
This issue is easily reproduce in https://www.primefaces.org/primeng/v9.1.5-lts/#/table

**Current behavior**
On focus tbody -> tr -> td top border hide in case of accessibility for the first row of table because of overlapping thead and tbody and because of that we can not highlight properly.

![image](https://user-images.githubusercontent.com/9951007/93990371-a99a0d80-fda8-11ea-9693-ef0e95b4a23c.png)

**Expected behavior**
The focus border should be visible properly.

**Minimal reproduction of the problem with instructions**
Steps:
1.  goto https://www.primefaces.org/primeng/v9.1.5-lts/#/table
2.  Enable focus on developer tool for tobody -> tr -> td and thead

**What is the motivation / use case for changing the behavior?**
This will bring better usability, visual representation in terms of accessibility for user

**Please tell us about your environment:**
Window, Linux

* **Angular version:** 5.X
9.1.11

* **PrimeNG version:** 5.X
9.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Version 84.0.4147.89
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript: 3.8.8

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
