### ISSUE TITLE
Date format with local setting not work beacause dateFormat set by default in component

### ISSUE THREAD

**Issue by MartinBaptiste** [primefaces/primeng#9309]
**Current behavior**
This default value not corect to documentation :
https://github.com/primefaces/primeng/blob/1956b6d680b7c711570e1b1fb8c580f98ab7ce98/src/app/components/calendar/calendar.ts#L219

**Expected behavior**
Change doc or set empty or null by default

**Comment by yigitfindikli** [comment]
Hi @MartinBaptiste,

You can check [at](https://www.primefaces.org/primeng/showcase/#/calendar).

Regards.
