### ISSUE TITLE
Dropdown filter issue with Windows 10 on tablet mode

### ISSUE THREAD

**Issue by jprichad** [primefaces/primeng#9310]
If the application is opened using Windows 10 on tablet mode then the dropdown with filter is not working as expected. To reproduce this issue please open this [link](https://primefaces.org/primeng/showcase/#/dropdown) using tablet mode and try to select an option from _Advanced with Templating, Filtering and Clear Icon_ with the tactile screen. As soon as the dropdown expands, focus moves to search field and keyboard comes up. As soon as the keyboard gets visible, search field loses its focus and dropdown is closed. Now, as the search field loosed its focus, the keyboard is also getting closed. In this whole loop, a user cannot select an item in the dropdown at all.

**Comment by Schles** [comment]
I get the same behaviour on all iPad's and Android Devices with the "Show Desktop Version" User Agent activated.

**Comment by heniAbdmouleh** [comment]
I have the same issue. Any updates !

**Comment by eddhib** [comment]
I have the same issue.

**Comment by odaper** [comment]
Hello
We have the same issue in the dropdown component even when the filter is disabled, you can easily reproduce the problem by accessing the showcase app of Primeng by Tablet IOS and try to open a dropdown list or multiselect list, the keyboard will be displayed instead of the list 

Thanks

**Comment by ammannai** [comment]
Hello , 
Same issue here where i'm trying to open a MultiSelect component on tablet mode , a keyboard will be displayed instead of the list.
Thanks ,
