### ISSUE TITLE
Again problem with twice load init in virtualscroll

### ISSUE THREAD

**Issue by ja74687** [primefaces/primeng#9311]
Sorry for my english XD 

I have problem, I use table with lazy loading and virtualscroll but lazyload method init twice, i see you fix it in 10 verstion I update my primeNG but problem no fix :)

**Comment by EricWagnerJr** [comment]
Potentially related, currently in 10.0.0 lazyLoadOnInit=false sends a scroll event onInit.

**Comment by cagataycivici** [comment]
This is related to;

https://github.com/primefaces/primeng/issues/9316
