### ISSUE TITLE
p-virtualScroller lazy load event.first is NaN or Infinity

### ISSUE THREAD

**Issue by chief1234dima** [primefaces/primeng#9314]
**Current behavior:**
After component initialization: LazyLoadEvent is {first: NaN, rows: 20}, VirtualScroller.loadedPages: [NaN].
After list scrolling: LazyLoadEvent is {first: Infinity, rows: 20}, VirtualScroller.loadedPages: [NaN, Infinity].
After that, the LazyLoadEvent is not triggered no matter how much scrolling.
**Expected behavior:** Work as expected

```
<p-virtualScroller
  #scroller
  [value]="content"
  [rows]="20"
  [lazy]="true"
  (onLazyLoad)="onLazyLoad($event)"
  scrollHeight="450px"
>
  <ng-template let-item pTemplate="item" let-i="index">
    <ng-container
      *ngTemplateOutlet="
        listItemTemplate;
        context: { $implicit: getItemData(item, i) }
      "
    ></ng-container>
  </ng-template>
</p-virtualScroller>
```

**Angular version**: 10.1.1
**PrimeNG version**: 10.0.0
**Browser**: Chrome
**Language**: English

**Comment by arni1981** [comment]
I can confirm this happening for me to.

**Comment by lilacdev** [comment]
I can too confirm. But for me, I have a warning saying first is now deprecated. But documentation does not explain how to use it in 10.0.3 ...
