### ISSUE TITLE
Typo in InputNumber documentation: maxFracionDigits

### ISSUE THREAD

**Issue by boszormenyip** [primefaces/primeng#9315]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
There is a typo in the documentation of the InputNumber component (https://primefaces.org/primeng/showcase/#/inputnumber). 

**Current behavior**
In the decimal mode part one of the examples contains maxFracionDigits. Note the missing t letter.

**Expected behavior**
It should be minFractionDigits.

**Minimal reproduction of the problem with instructions**
* Open https://primefaces.org/primeng/showcase/#/inputnumber).
* Search for maxFracionDigits.

**Comment by cagataycivici** [comment]
This was fixed last week. Thank you.
