### ISSUE TITLE
PrimeNG P-table seperate selection for row and checkbox in single row selection mode.

### ISSUE THREAD

**Issue by faheemworkspace** [primefaces/primeng#9317]
Hi there, 

I m using PrimeNG version 8 for angular app. I am trying to enable single row selection mode with checkbox multiple selection. But I m having problem in doing so. I have seen the source, apparently it seems that Primeng 8 is not giving this feature. Can anybody please share the fix. 

Thanks

**Comment by faheemworkspace** [comment]
any body ???

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
