### ISSUE TITLE
p-tree onNodeDrop event dropIndex incorrect when dragging after final node   

### ISSUE THREAD

**Issue by LukeHartcher** [primefaces/primeng#9320]
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/primeng-treedragdrop-demo-wnssd9
(Fork of https://stackblitz.com/edit/primeng-treedragdrop-demo)

**Current behavior**
Drag "Documents" to AFTER "Movies"
Console: dropIndex = 2

**Expected behavior**
Drag "Documents" to AFTER "Movies"
Console: dropIndex = 3

**Minimal reproduction of the problem with instructions**
Run StackBLitz Demo
Drag "Documents" to between "Pictures" and "Movies"
Console: dropIndex = 2 (correct)
Restart StackBLitz Demo
Drag "Documents" to AFTER "Movies"
Console: dropIndex = 2 (INCORRECT)

**What is the motivation / use case for changing the behavior?**
Currently the dropIndex=2 when dropped either before or after the final item, so you are unable to determine the exact drop without investigation the new tree. 

**Please tell us about your environment:**
Your current stackblitz demo https://stackblitz.com/edit/primeng-treedragdrop-demo PrimeNG 10.0.0

* **Browser:** [all ]

 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =

**Comment by hkjeffchan** [comment]
Please merge this ASAP. The inability to determine the exact drop position makes the tree drag and drop function basically unusable.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
