### ISSUE TITLE
Improvement in behavior of components that have overlay panels in scrollable containers

### ISSUE THREAD

**Issue by mertsincan** [primefaces/primeng#9324]
When the page or scrollable container is scrolled or window is resized, all open overlay panels will be closed.

- [ ] AutoComplete
- [ ] Calendar
- [ ] ColorPicker
- [ ] Dropdown
- [ ] Menu (SplitButton)
- [ ] MultiSelect
- [ ] OverlayPanel
- [ ] Password
- [ ] SlideMenu
- [ ] TieredMenu

**Comment by ChekTek** [comment]
Is there any workaround for this if I can't update to this release?

**Comment by YD1722** [comment]
What about the p-contextMenu ? I have a scrollable grid and the context menu is not hidden on scroll.

**Comment by YD1722** [comment]
> Is there any workaround for this if I can't update to this release?

Yes. I had the same problem ( Angular 9 ).  I copied only changed classes  ( connectedoverlayscrollhandler.ts and domhandler.ts )
in this enhancement and used them in my project
