### ISSUE TITLE
Duration selector feature

### ISSUE THREAD

**Issue by pmo1948** [primefaces/primeng#9327]
**I'm submitting a ...**  
```
[X ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
```

It would be nice to have something to set a duration - allow the user to input different options (hh mm ss, dd MM yyyy ...) 
Similar to calendar, but without specific dates, just a timespan / duration equivalent

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
