### ISSUE TITLE
Toolbar with icons set to be aligned to the right are aligned to the left when no left container is present

### ISSUE THREAD

**Issue by gustavobmichel** [primefaces/primeng#9328]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/primeng-toolbar-demo-8x2lmj

**Current behavior**
When using the toolbar with icons only aligned to the right, the icons are still aligned to the left. The workaround is to add an empty div for the left even when you don't have icons for the left. <div class="p-toolbar-group-left"></div>

**Expected behavior**
Icons would aligned to the right.

**Minimal reproduction of the problem with instructions**
Open https://stackblitz.com/edit/primeng-toolbar-demo and remove the container on the left.

* **Angular version:** 5.X
10.0.1

* **PrimeNG version:** 5.X
10.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
