### ISSUE TITLE
Datatable - Can't have column styled widths and column resize together

### ISSUE THREAD

**Issue by garthmason** [primefaces/primeng#933]
Hi,

In the datatable if we set the width of a column (via style) to e.g. 100px, then that width isn't used if we also have _resizableColumns_ set to true.  

So at the moment if we want resizing columns, we can only have equal width (auto). It'd be good to have some default widths specified in styles, but still allow the user to resize after that.

Thanks!

Same issue is mentioned here on the forum:
http://forum.primefaces.org/viewtopic.php?f=35&t=46449
http://forum.primefaces.org/viewtopic.php?f=35&t=47041&p=146093&hilit=column+width#p146093

**Comment by jtesser** [comment]
+1 on this.

**Comment by devangvt** [comment]
+1

**Comment by cagataycivici** [comment]
This is discussed a couple of times, datatable has 100% width so even you give 100px browser will scale it, it works best if you give percentages. Also please try with latest version as there are various improvements.
