### ISSUE TITLE
Angular PrimeNG FocusTrap Tabbing Fix Issue

### ISSUE THREAD

**Issue by BuslinesAU** [primefaces/primeng#9332]
Hi, you fixed most of the issues in #9139 for my request #9199.

However, there is still one case which doesn't work and the fix is simple which I have implemented locally.

If you attempt to enter a time by performing the following, it doesn’t work:

1. Completely clear the time field
2. Enter a time
3. Press tab

The field won't tab to the next field, because the **contentViewChild** is undefined and you cannot get the **nativeElement**.
This is because the **popup** disappears when the field is cleared.

Adding a **if (this.contentViewChild)** around the **DomHandler.getFocusableElements(...)** fixes the problem.

Cheers.

**Comment by mtrefzer** [comment]
Seams to be also the same problem with my issue [#9257](https://github.com/primefaces/primeng/issues/9257)

**Comment by yigitfindikli** [comment]
fixed in https://github.com/primefaces/primeng/commit/90bbc21276730ab2ef6e11a28d21c093958448ad
