### ISSUE TITLE
InputNumber with spinner mode throws a JS exception

### ISSUE THREAD

**Issue by RealNumberX** [primefaces/primeng#9337]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report 
[ ] feature request 
[ ] support request
```

**Current behavior**
TypeError gets thrown when text-field of input-number component is empty and the value is about to be incremented or decremented via buttons.

**Expected behavior**
TypeError does not get thrown. New value of the field should be 0 +/- [step] if no minimum or maximum boundaries are set.

**Minimal reproduction of the problem with instructions**

- Go To PrimeNG Documentation InputSpinner Component
- In the example with buttons delete the value of the input field
- open Dev-Tools in browser
- try to increment or decrement the value

**Comment by mertsincan** [comment]
Hi,

Thanks a lot for the PR! However, it had some conflict problems. I guess this was about my previous commits. Sorry for noticing your PR late.

Thanks again for your PR,
Best Regards,
