### ISSUE TITLE
P-Table with resizeableColumns and autoLayout not wrapping cell text, imposes minimum column width

### ISSUE THREAD

**Issue by lwestfall** [primefaces/primeng#9338]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
For p-table with resizeableColumns=true and autoLayout=true, the minimum column width is the width of the longest cell text (with no wrapping).

**Expected behavior**
In 9.1.3, there was no limit on the minimum column width. If the cell text width < column width, the text would wrap.

**Minimal reproduction of the problem with instructions**
See stackblitz: https://stackblitz.com/edit/primeng-tablecolresize-demo-5rgv9h?file=src/app/app.component.html and try to resize "Name" column as small as possible. It only goes as small as the longest cell text.

* **Angular version:** 10.2.0

* **PrimeNG version:** 10.0.1

* **Browser:** Chrome, untested on others

Not sure if related to #8991 because that was reported on 9.1.0, but I didn't have this problem in 9.1.3

If this behavior is intentional, is there a css trick I can use to restore the cell text wrapping functionality so there is no minimum column width?

Thanks!

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
