### ISSUE TITLE
Customizable accordion icons

### ISSUE THREAD

**Issue by glivolsi** [primefaces/primeng#934]
Please add:
- a property to change the expand/collapse fontawesome icons...!! 
- a little (switchable on/off ) icon on the left off the accordion-tab to indicate that something inside the tab is changed as in the image below

![image](https://cloud.githubusercontent.com/assets/5219941/18700206/473ff3d8-7fd6-11e6-85f1-c4bbf69831e7.png)

```
export class AccordionTab {
    @Input() changed: boolean;


<span class="fa fa-circle" style="left:1.2em; top:2.55em; right:initial; color:#357ebd; font-size: 0.6em; text-shadow: 1px 1px 2px" *ngIf="changed"></span>
```

**Comment by sudheerj** [comment]
1. The customized property for expand/collapse fa icons make sense.
2. This is purely use case specific feature. It is not a common requirement.You can use p-header to indicate changes in the content.

**Comment by ajmair01** [comment]
:+1: Would love to be able to specify the expand/collapse fa icons with an `openIcon` and `closedIcon` property, similar to the way you can change the `icon`, `acceptIcon`, and `rejectIcon` properties of the `ConfirmDialog` component.

**Comment by nartc** [comment]
I've made a modification to the source accordion.js to take in openIcon and closeIcon Input. How do I contribute?

**Comment by nartc** [comment]
<img width="958" alt="screen shot 2017-11-30 at 10 17 45 am" src="https://user-images.githubusercontent.com/25516557/33441245-d5d60bc2-d5b7-11e7-8f83-96bc5e51c6cb.png">

`<p-accordionTab *ngFor="let faq of FAQS; let i = index" [header]="faq?.title" openIcon="fa-plus" closeIcon="fa-minus">
                        <span [innerHTML]="faq?.content"></span>
                    </p-accordionTab>`

**Comment by IRCraziestTaxi** [comment]
What's going on with this? It looks like the changes to allow setting `[openIcon]` and `[closeIcon]` were never merged. Why not? I could really use that functionality.

**Comment by nartc** [comment]
Although not stated in the docs, expandIcon and collapsedIcon are parts of the Accordion’s API https://github.com/primefaces/primeng/blob/master/src/app/components/accordion/accordion.ts#L171

**Comment by IRCraziestTaxi** [comment]
Ah, I see. I was trying to find such a prop on the Accordion Tab, not the Accordion itself. I would like to have a different icon per accordion tab so the above code looked promising, but I guess it was ditched? :/
