### ISSUE TITLE
Spread sheet navigation like with arrow keys in primeng table

### ISSUE THREAD

**Issue by alexesca** [primefaces/primeng#9341]
**I'm submitting a ...**  
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Primeng table does not support arrow keys navigation. 

**Expected behavior**
I would like to be able to move up,down,rigth, and left with keys. Like when using google sheets or MS Excel.

**Minimal reproduction of the problem with instructions**
Everyone uses spread sheets. It should be a default behavior.

**What is the motivation / use case for changing the behavior?**
This functionality would enhance the use of primeng tables in financial applications. 

<img width="182" alt="Screen Shot 2020-09-30 at 7 35 53 PM" src="https://user-images.githubusercontent.com/11186399/94756236-29e5e300-0354-11eb-843a-ced2ab6cf734.png">

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
