### ISSUE TITLE
Send globalFilterFields to the server in p-table lazy mode 

### ISSUE THREAD

**Issue by nabildridi** [primefaces/primeng#9348]
Please, can you add globalFilterFields and its value if exist to the LazyLoadEvent interface? it can be useful in the server side filtering. Thank you.

**Comment by lilacdev** [comment]
Hi, did you achieve to get it working ? I tried pTable (lazy one) and virtualscroller, both can't nor filter or sort results without bugs.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
