### ISSUE TITLE
P-autoComplete component not showing the values in Primeng version 10.0.1

### ISSUE THREAD

**Issue by ljupchoristovski** [primefaces/primeng#9352]
**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/github-2skexm-znjtos?file=src/app/app.component.html

**Current behavior**
When we use p-autoComplete component, saved values are not shown in the field. You need to click in the field in order to show the values.

**Expected behavior**
When component is loaded the values should also be shown in the field (as previous versions < 10), without clicking in the field.

**What is the motivation / use case for changing the behavior?**
To fix the issue with the p-autoComplete component

**Please tell us about your environment:**
OS: Windows 10, IDE: Visual Studio Code

* **Angular version:** 5.X
Angular 10.1.2

* **PrimeNG version:** 5.X
PrimeNG 10.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome Version 85.0.4183.121
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 4.0.3

Issue is easy to reproduce. Load some data to be shown in the p-autoComplete field. Data should be shown, but instead it's not. User should click in the field in order to show the data in the field, which is not the correct behavior.

**Comment by aminkosh** [comment]
I have also the same issue.

**Comment by montelyno** [comment]
Same here after upgrade! Would appreciate a short bugfix.

**Comment by noteme-io** [comment]
I am also facing the same issue..
