### ISSUE TITLE
inputnumber validation does not work while typing

### ISSUE THREAD

**Issue by anujtrehan** [primefaces/primeng#9360]
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/primeng-inputnumber-demo-vnfueg?file=src%2Fapp%2Fapp.component.html

**Current behavior**
Input number validation works only when the focus is out of the text box, but does not work while typing invalid number.
Reproduced the error in stackbliz: if primeng num 1 is typed with value more than 3000, an error would not appear unless the focus is out of the text box. In case of Num 2 text box without primeng component, validation works even while typing invalid value

**Expected behavior**
Validation should work in inputnumber text box even while typing invalid test

* **Angular version:** 10.0.0

* **PrimeNG version:** 10.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by mertsincan** [comment]
Hi,
Thanks a lot for the sample! You need to use onInput event for such issues. Then, you can add custom validations into it. Please see this ticket; https://github.com/primefaces/primeng/issues/9223

Best Regards,

**Comment by masalinas** [comment]
Using the version 14.2.3 the same problem persist

**Comment by Kbdq** [comment]
15.2.0 - problem still exists
