### ISSUE TITLE
Table - moving down with arrow stop working using virtualscroll

### ISSUE THREAD

**Issue by venash** [primefaces/primeng#9361]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-tablevirtualscroll-demo

**Current behavior**
- click on some row in table
- press arrow key down repeatedly
- scroll will stop working after few clicks (if dom element is removed from virtual scroll)

**Expected behavior**
Scroll will not stop working using arrow keys.

* **Angular version:** 10.1.2

* **PrimeNG version:** 10.0.2

* **Browser:** [all]

**Comment by curciot** [comment]
i got the same problem there's a fix or a workaround for this bug?

**Comment by jupin-r** [comment]
I think that this is bug. Scrolling by keys (UP and DOWN) are impossible, because table lost focus. The scrolling by keyboard is basic function of web applications.

**Comment by mauriziocolica** [comment]
I have the same issue. Could you please release a rapid fix?

**Comment by sswebcoder** [comment]
In current master branch it's working properly if you use selectionMode and pSelectableRow.

**Comment by cagataycivici** [comment]
Please see;

https://github.com/primefaces/primeng/issues/9365

**Comment by jupin-r** [comment]
@cagataycivici  This issue is not resolved. I can reproduce it on version 10.0.3. If I click on the table and several times press key arrow down, then focus is lost and I can not continue scrolling of table by keys.

**Comment by sswebcoder** [comment]
> @cagataycivici This issue is not resolved. I can reproduce it on version 10.0.3. If I click on the table and several times press key arrow down, then focus is lost and I can not continue scrolling of table by keys.

Do you use selectionMode and pSelectableRow?

**Comment by jupin-r** [comment]
I don't set selectionMode or pSelectableRow. This issue is not addressed to selection behavior.
