### ISSUE TITLE
How to filter the default dropdown value of a column, on change is working fine but the problem is with default value dropdown

### ISSUE THREAD

**Issue by aletisw** [primefaces/primeng#9369]
https://www.primefaces.org/primeng/showcase/#/table/filter 

Referring to this link , i need for the status column a default value should selected and that value related row should display, How can we do this.

                   
                    <p-dropdown [options]="statuses" (onChange)="dt.filter($event.value, 'status', 'equals')" styleClass="p-column-filter" placeholder="Select a Status" [showClear]="true">
                        <ng-template let-option pTemplate="item">
                            <span [class]="'customer-badge status-' + option.value">{{option.label}}</span>
                        </ng-template>
                    </p-dropdown>
               
  

![Filtercolumn_table](https://user-images.githubusercontent.com/70217491/95342476-1945e780-08d5-11eb-81f4-5a8282182b3e.png)

**Comment by cagataycivici** [comment]
Please use the forum for support requests and questions.

**Comment by sahil1207** [comment]
Even , I am facing the same issue and no where this has been documented in documentation ,were you able to find the solution for the same?
