### ISSUE TITLE
p-inputMask doesn't clean itself when model value is set to "undefined"

### ISSUE THREAD

**Issue by rafaelodon** [primefaces/primeng#937]
There's this p-inputMask two-way binded to a "number" variable via [(ngModel)]. If this variable is set to "undefined" by some event, I expect to see this input empty. But the inputmask keeps displaying the last value.

I managed to hack a solution by copying the InputMask code to my project and intercepting the get/set of the component value, thus changing it's display value to '' when 'undefined' is informed in this property setter:

```
...
export class InputMask implements AfterViewInit,OnDestroy,ControlValueAccessor {
    ...
    /* BEGIN - Fix for setting undefined value on input-mask*/        
    innerValue:any; //rename 'value' property to 'innerValue' and use it within get/set value

    get value(): any {        
        return this.innerValue;
    };

    set value(v: any) {            
        if (v !== this.getUnmasekd) {
            if(v == undefined){
                this.el.nativeElement.children[0].value = "";
                this.innerValue = undefined;
            }else{
                //maybe there's more things to care about here... (store unmasked ou masked value?)
                this.innerValue = v;
            }
            this.onModelChange(v);
        }
    }
    /* END - Fix for setting undefined value on input-mask*/
}
```

It worked for my case, but I don't think it's the best solution.

I'm using: angular "2.0.0", primeng": "1.0.0-beta.16", "jquery": "2.2.4", "jquery.inputmask": "3.3.3".

**Comment by cagataycivici** [comment]
Mask is reimplemented as a native components instead of jquery, so will check this for beta17.

**Comment by gilsondev** [comment]
This still ocorring in PrimeNG 1.1.4, with properties this value:

```typescript
clear(event) {
  this.inputTest = "";
}
```

Something `undefined` and `null` works.
