### ISSUE TITLE
(overridden classes): Style classes are broken when upgraded primeNg version from 9.0.6 to 10.0.2

### ISSUE THREAD

**Issue by muralikrishh** [primefaces/primeng#9373]
Hi,

I was using the primeNg version : 9.0.6 till now and  i upgraded now to the 10.0.2 version.
I noticed that there are some changes in the classes and  due to which the class names that i have overridden in my project are all broken now with this upgrade.

I looked at the change list and did not find much information.One of the changes i observed was all the classes that has the prefix "ui" has now changed to "p". I also noticed that few of the other classes were also renamed.

It's really difficult for me to manually change all the class name which were supported in 9.0.6. 

Below are the list of the components i am over-riding in my project: 

**p-autocomplete
p-checkbox
p-radio
p-dialog
input
paginator
listbox
panel
table
toast
p-dropdown
toggle
tree-table**

Please help me to get the styles change-list for the above mentioned components.
Or please suggest an approach that will help me to rename all the changed classes from 9.06 version to 10.0.2

**Comment by cagataycivici** [comment]
Please use the forum for questions and support requests, also review the migration guide;

https://github.com/primefaces/primeng/wiki/PrimeOne-Migration
