### ISSUE TITLE
Autocomplete clears selected item on blur

### ISSUE THREAD

**Issue by luboslav** [primefaces/primeng#9378]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
If user picks item by pressing enter and [forceSelection]="true", the selected item is cleared on blur event.

**Expected behavior**
The selected item should not be cleared.

**Comment by cyprianno** [comment]
Workaround:
`<p-autoComplete [forceSelection]="true" #autocomplete></p-autoComplete>`
`@ViewChild('autocomplete') autocomplete: AutoComplete;`
and in ngOnInit
`this.autocomplete.onOverlayAnimationDone = ()=>{}`

**Comment by cyprianno** [comment]
Workaround based on autocomplete showcase stackblitz:
html (added [forceSelection]="true" #autocomplete):
`<h5>Basic</h5>
<p-autoComplete [(ngModel)]="selectedCountry" [suggestions]="filteredCountries" (completeMethod)="filterCountry($event)" field="name" [minLength]="1"></p-autoComplete>

<h5>Dropdown and Templating</h5>
<p-autoComplete [(ngModel)]="selectedCountryAdvanced" [suggestions]="filteredCountries" (completeMethod)="filterCountry($event)" field="name" [dropdown]="true" [forceSelection]="true" #autocomplete>
    <ng-template let-country pTemplate="item">
        <div class="country-item">
            <div>{{country.name}}</div>
        </div>
    </ng-template>
</p-autoComplete>

<h5>Multiple</h5>
<span class="p-fluid">
    <p-autoComplete [(ngModel)]="selectedCountries" [suggestions]="filteredCountries" (completeMethod)="filterCountry($event)" field="name" [multiple]="true">
    </p-autoComplete>
</span>`

ts (added viewchild and AfterViewInit):
`import { AfterViewInit, OnInit, Component, ViewChild } from '@angular/core';
import {MenuItem} from 'primeng/api';
import {SelectItem} from 'primeng/api';
import {SelectItemGroup} from 'primeng/api';
import {AutoComplete} from 'primeng/autocomplete';
import { CountryService } from './countryservice';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  providers: [CountryService]
})
export class AppComponent implements AfterViewInit, OnInit { 
    selectedCountry: any;
    @ViewChild('autocomplete') autocomplete: AutoComplete;
         
    countries: any[];
        
    filteredCountries: any[];

    selectedCountries: any[];

    selectedCountryAdvanced: any[];

    filteredBrands: any[];

    constructor(private countryService: CountryService) { }

    ngOnInit() {     
        this.countryService.getCountries().then(countries => {
            this.countries = countries;
        });
        console.log(this.autocomplete);

    }

    ngAfterViewInit(){
      this.autocomplete.onOverlayAnimationDone = (event)=>{};
   }

    filterCountry(event) {
        //in a real application, make a request to a remote url with the query and return filtered results, for demo we filter at client side
        let filtered : any[] = [];
        let query = event.query;
        for(let i = 0; i < this.countries.length; i++) {
            let country = this.countries[i];
            if (country.name.toLowerCase().indexOf(query.toLowerCase()) == 0) {
                filtered.push(country);
            }
        }
        
        this.filteredCountries = filtered;
    }
}
`

**Comment by luboslav** [comment]
Thanks for workaround.

**Comment by yashjangid1** [comment]
I am facing the same issue. Thanks, @cyprianno for the workaround.

**Comment by Lx** [comment]
Thanks, @cyprianno!  For posterity and convenience, I'm copying the workaround to the issue's comments:

1.  Assign a **template reference variable** to the affected `<p-autoComplete>`:

    ```html
    <p-autoComplete #autocomplete ...>
    ```

2.  Get a reference to the component in the code:

    ```typescript
    @ViewChild('autocomplete') autocomplete: AutoComplete;
    ```
3.  In `ngAfterViewInit`, erase one of its event handlers:

    ```typescript
    ngAfterViewInit() {
      this.autocomplete.onOverlayAnimationDone = (event) => {};
    }
    ```

**Comment by picoloto** [comment]
I'm curently working on a project that have too many autocompletes, making the workaround unviable.
Any news about fixing this bug?

**Comment by gasparbarancelli** [comment]
We have the same problem, the worst of it is that we have more than 10000 autocompletes in the application, the palliative solution does not help us

**Comment by luboslav** [comment]
I hope that this bug gets fixed soon. We are also using more than few autocompletes.

**Comment by meursj** [comment]
It is fixed in 11.0.0 with fixing issue #8740

**Comment by luboslav** [comment]
Thanks, closing.

**Comment by symc-shilpa** [comment]
I tried the solution, or me the autocomplete resolves to undefined

**Comment by lala81996** [comment]
The issue remains in V14.1.1. Unfortunately, the workaround doesn't work either since there seems to have been an update on `onOverlayAnimationDone`. 

Would appreciate any suggestions or alternative workarounds ... Or even better an update.
