### ISSUE TITLE
Tab key in p-dialog with p-InputNumber

### ISSUE THREAD

**Issue by hugograf** [primefaces/primeng#9380]
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-dialog-tab?embed=1&file=src/app/app.component.html

**Current behavior**
* Click Button Show
* Set cursor on first input field
* Move cursor by pressing tab or shift+tab key
* Try to override or to correct values of the input fields

**Expected behavior**
The whole value of a input should be selected in a p-dialog, easier to override

* **Angular version:** 10.X 
* **PrimeNG version:** 10.0.2 (Possibly any version)
* **Browser:** [all]

**Comment by dcbroad3** [comment]
I also see this issue in the latest version of PrimeNG (14.1.2)

**Comment by dcbroad3** [comment]
Opened PR #12124 to resolve this issue, the root issue is that the `FocusTrap` directive used by the `Dialog` only focuses the chosen element, and does not `select` it if it is an `HTMLInputElement`.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by dcbroad3** [comment]
@mertsincan @cetincakiroglu I can confirm that this issue still exists in PrimeNG/Angular version 15. 

PR #12124 still contains a viable fix.

**Comment by cetincakiroglu** [comment]
> @mertsincan @cetincakiroglu I can confirm that this issue still exists in PrimeNG/Angular version 15.
> 
> PR #12124 still contains a viable fix.

Hi @dcbroad3,

I've reviewed your pr and requested some changes.

Thank you for your support and effort!
