### ISSUE TITLE
table wrong hover color in some themes

### ISSUE THREAD

**Issue by codehunter13** [primefaces/primeng#9385]
**I'm submitting a ...**  (check one with "x")
[ x] bug report => Search github for a similar issue or PR before submitting

Hover over table header or cells gives a white background color in some themes.
vela-blue has this problem but others too.

if you check the documentation:
https://www.primefaces.org/primeng/showcase/#/table/crud with that theme applied: color is ok
but open the stackblitz (https://stackblitz.com/edit/primeng-tablecrud-demo)
in angular.json change "node_modules/primeng/resources/themes/saga-blue/theme.css", to
"node_modules/primeng/resources/themes/vela-blue/theme.css"
and hovering gets a white color

**Expected behavior**
color as in documentation page

* **Angular version:** 10.0.3

**Comment by cagataycivici** [comment]
It works for me on showcase;

https://www.primefaces.org/primeng/showcase/#/table/crud

Just change it to vela and it works fine.

Could be an issue with stacbklitz.

**Comment by cagataycivici** [comment]
<img width="1502" alt="Screen Shot 2020-10-11 at 19 45 09" src="https://user-images.githubusercontent.com/686247/95684412-49092e00-0bfa-11eb-8800-26549e251ce0.png">

**Comment by codehunter13** [comment]
for me too in the showcase but in my dev environment AND not in stackblitz:
![image](https://user-images.githubusercontent.com/7559059/95687305-fed87a80-0c02-11eb-8a70-2dbc8d57983e.png)

**Comment by codehunter13** [comment]
if i put the table in a card, the problem goes away. Probably, in the showcase, the grid has a parent that also solves it.
Please check your own stackblitz.  It also has the same problem.. And no thats not the fault of stackblitz itself....

**Comment by SergeyMell** [comment]
This issue still takes place. Here is your own stackblitz example with accordion where I've just changed the theming from `saga` to `vela`
https://stackblitz.com/edit/primeng-accordion-demo-xdqhxn

And we get a white row on hover
<img width="654" alt="Снимок экрана 2021-11-16 в 18 03 17" src="https://user-images.githubusercontent.com/12133261/142020999-98fefa55-bf1c-494d-bb38-ff19727c764b.png">

**Comment by SergeyMell** [comment]
Well, actually the solution comes from this topic
https://forum.primefaces.org/viewtopic.php?t=63315
and consists in proper defining `body` background properties
```
body {
  background-color: var(--surface-a);
  font-family: var(--font-family);
  color: var(--text-color);
}
```
Maybe I missed this configurations in the setup instructions or they worth to be added there
