### ISSUE TITLE
Repo unit tests appear to be inaccurate

### ISSUE THREAD

**Issue by Pompeoar** [primefaces/primeng#9388]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
In the context of p-checkbox
Implementing your unit tests exactly as is results in a compilation error (no closing element for p-checkbox for example, which your documentation agrees is necessary). All examples of how to query the debugElement or nativeElement to get a reference to the checkbox do not return an instance of the checkbox to interact with. 

**Expected behavior**
Duplicating tests would result in successful examples of how to unit test prime ng elements. 

**Minimal reproduction of the problem with instructions**
Navigate to [checkbox tests ](https://github.com/primefaces/primeng/blob/master/src/app/components/checkbox/checkbox.spec.ts)and simply mimic the implementation as is. Use a test runner of your choice.

* **Angular version:** 9.X
* **PrimeNG version:** 9.X

Feature Request:
Better Unit Testing documentation and examples.

The primary pain point our team has found in using primeng has been the unit testing aspect. Any documentation or examples (beyond digging through the repo files which doesn't appear to work as noted above) would be incredibly helpful. Getting a hold of elements to interact with (form fill, click buttons, select checkbox, initiate dialogs etc) to observe behaviors (ngIfs honored, dynamic components loaded, routing initialized, etc) is very difficult relative to using and styling vanilla elements.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
