### ISSUE TITLE
p-fileUpload (onUpload) not called for http success codes other than 200.  201 raises (onError)

### ISSUE THREAD

**Issue by kmcnamee** [primefaces/primeng#939]
This is with Angular2 2.0.0 final, and PrimeNg 1.0.0-beta.16  p-fileUpload onUpload event is not called for http success codes other than 200.  IE doing a POST often returns http status code 201 in this case the wrong event is raised, onError instead of onUpload...   Workaround was to modify old legacy system to return 200 vs 201 status code...

> If a resource has been created on the origin server, the response SHOULD be 201 (Created)

[https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.5](https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.5)

problem is here:
[https://github.com/primefaces/primeng/blob/master/components/fileupload/fileupload.ts#L187](https://github.com/primefaces/primeng/blob/master/components/fileupload/fileupload.ts#L187)

if(xhr.status == 200)
       onUpload.emit({xhr: xhr, files: this.files});
  else
      this.onError.emit({xhr: xhr, files: this.files});`

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with them and if issue persists drop a comment and we'll reopen.
