### ISSUE TITLE
Critical Issue: onSelect Event Trigger when hover on changed time button

### ISSUE THREAD

**Issue by taiducnguyen** [primefaces/primeng#9398]
Primeng v10.0.0 & also did a testing with v10.0.3
The calendar issue as the attached gif below:
![ezgif com-gif-maker](https://user-images.githubusercontent.com/22149480/95699996-1b5ecc00-0c70-11eb-89bb-a5911ba57b26.gif)

**onSelect** event trigger once hovering on change time button

Please help to fix this.

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
