### ISSUE TITLE
PrimeNG 10.0.3 - Mobile/Touch screen - Swipe left and and Swipe right is not working in Galleria

### ISSUE THREAD

**Issue by noteme-io** [primefaces/primeng#9400]
Current behavior
Mobile/Touch screen - Swipe left and Swipe right is not working in Galleria

Expected behavior
In Mobile/Touch screen, swiping images should work like Carousel

PrimeNG version: 10.0.3

**Comment by yigitfindikli** [comment]
duplicate of https://github.com/primefaces/primeng/issues/9243
