### ISSUE TITLE
Accordion Header background color?

### ISSUE THREAD

**Issue by meminsahin** [primefaces/primeng#9401]
Hi,

How can I change the background color of the Accordion Header?
I searched on google a lot and the results I found did not work for me.

**Comment by souhailharrati** [comment]
hi,

you can overwrite background color of accordion header by using:

:host /deep/ .ui-accordion .ui-accordion-header {
    background-color: red;
}

**Comment by cagataycivici** [comment]
Please use forum for support requests.
