### ISSUE TITLE
DynamicDialog with simple text content

### ISSUE THREAD

**Issue by graphicsxp** [primefaces/primeng#9403]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ *] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**

Currently, the DynamicDialog service allows creating a dialog with dynamic content set to null or to a Component. This is great when you want to have complex UI in the dialog. But in some cases I just want to display plain text in the body of the dialog. There is no way to achieve that other than creating some dumb component that displays text.

**Expected behavior**

It would be great if the dialogService, similarly to ConfirmService, could take a string parameter such as Message.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
