### ISSUE TITLE
Scrollbar's Color can't be customized

### ISSUE THREAD

**Issue by mingoal** [primefaces/primeng#9404]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Offical example:
https://stackblitz.com/edit/primeng-scrollpanel-demo?file=src%2Fapp%2Fapp.module.ts

**Current behavior**
the scroll bar color can't be customized.

**Expected behavior**
The color of scrollbar can be customized.

**Minimal reproduction of the problem with instructions**
Please check the example code on scrollpanel page.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 10

* **PrimeNG version:** 10

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

* **Node (for AoT issues):** `node --version` =

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
