### ISSUE TITLE
Accordion tab [selected]="true" not working when [cache]="true"

### ISSUE THREAD

**Issue by konuch** [primefaces/primeng#9405]
**I'm submitting a ...**
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/github-bqnfxn-6jete5?file=src%2Fapp%2Fapp.component.html

**Current behavior**
Hello I expect accordion to show my content with [selected]="true", however it doesn't. If I switch [cache]="false", it's working properly.

**Expected behavior**
Initial display of active accordion tab is working even with lazy loading enabled.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows 10, VS Code, npm

* **Angular version:** 5.X
10.0.14

* **PrimeNG version:** 5.X
10.0

* **Browser:** 
All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by pmo1948** [comment]
I have had a similar issue, but nothing to do with cache. If I used a template for content, as the example above does, and selected is true, there is only a small empty rectangle until accordion tab is closed and reopened. only upon reopening is desired content visible

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
