### ISSUE TITLE
DataView - Add selection capabilities for grid and row items

### ISSUE THREAD

**Issue by Phil-DS** [primefaces/primeng#9407]
**I'm submitting a ...** 
```
[ ] bug report => Search github for a similar issue or PR before submitting
[X] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
No item selection available for DataView

**Expected behavior**
Have the ability to select items in the DataView in both row and item format. The same selection variable would work for both, and the items would have a default style for selection and hover, and if selected or not exposed as a variable in the template, like the Table module. 

**What is the motivation / use case for changing the behavior?**

For a selectable grid of items, DataView would be the likely candidate. However, there is no 'selectable' option. For a tabular version, you have the Table module, but the DataView lacks the ability to do so. It could be achieved manually with list/forms, but a built in option would be better

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
