### ISSUE TITLE
Read-only MultiSelect component doesn't give access to view all selected items

### ISSUE THREAD

**Issue by sbs101** [primefaces/primeng#9409]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-tphhnv?file=src/app/app.component.html

**Current behavior**
For a MultiSelect component in read-only mode with more than maxSelectedLables items selected one cannot figure out which items have been selected, because the "arrow down" is disabled.

**Expected behavior**
For a MultiSelect component one should be able to get the full information about the items currently selected at all times, even if the MultiSelect component is set to read-only mode and if there are more than maxSelectedLabels items selected. The "arrow down" should not be disabled in read-only mode, but only the toogling of the check marks should be disabled.

**Minimal reproduction of the problem with instructions**
- select more than maxSelectedLabels for a MultiSelect component, so that the display reads like "4 selected items"
- switch the component to read-only mode 
- you have no chance to figure out what the items are which have been selected by the component as the "arrow down" is disabled in read-only mode

**What is the motivation / use case for changing the behavior?**
We are using the same dialog for two user groups. One user group should be able to maintain the data, the other user group should not be able to change the data but should be able to audit the data. We are switching all the components to read-only for the second user group which makes it impossible to audit the selected data for a MultiSelect component.

* **Angular version:** 10.0.14

* **PrimeNG version:** 10.0.3, but behaviour is the same for latest version 9

* **Browser:** Firefox 81.0.1, Chrome 86

**Comment by yigitfindikli** [comment]
You can use chip or elipsis mode for this.
