### ISSUE TITLE
Table ScrollHeight Flex doesn't work with max-height

### ISSUE THREAD

**Issue by nedredmond** [primefaces/primeng#9412]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

**Current behavior**
When using `max-height` on the div containing a table, the rows overflow when they exceed the limit rather than scrolling.

**Expected behavior**
I would expect the table to become scrollable once it reaches the designated `max-height`.

**Minimal reproduction of the problem with instructions**
[See the stackblitz
](https://stackblitz.com/github/bnmiongjw?file=src/app/app.component.html
)
Looks like I may not have saved the StackBlitz, but basically using min-height on the table container. That's it.

**What is the motivation / use case for changing the behavior?**
This is important when the tables can have varying amounts of data, ranging from having rows longer than the view can contain to one or two. This is also important when dynamically displaying multiple tables of varying row lengths in a column. I want tables of any size that do not exceed the height of the viewport.

**Please tell us about your environment:**

Windows 10 Enterprise
Visual Studio Code 1.50.0
Chrome 83.0.4103.122

* **Angular version:** 9.1.12

* **PrimeNG version:** 9.1.3

* **Browser:** [all]

 
* **Language:** [TypeScript 4.0.3 | ES6/7 | ES5]

**Comment by yigitfindikli** [comment]
Flex scroll needs a certain height. You can find more info at https://primefaces.org/primeng/showcase/#/table .
