### ISSUE TITLE
[feature] dropdown allow selection of items with tab

### ISSUE THREAD

**Issue by capc0** [primefaces/primeng#9415]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

It would be great to allow selection of items within an opened ```p-dropdown``` to be selected with tab key (like in the multiselect component).

Currently tab closes the overlay.

This could be easily implemented as an optional @Input property and if set, handle Keycode of Tab (9) the same as the arrow down key (40) in https://github.com/primefaces/primeng/blob/master/src/app/components/dropdown/dropdown.ts#L745

**Comment by AnTiiK** [comment]
The best solution for me is to add an option called "autoHighlight" like AutoComplete component, to select the first element on opened p-dropdown and on filtered p-dropdown

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
