### ISSUE TITLE
Error while integrating messages component in the project in api.ts

### ISSUE THREAD

**Issue by PoojaVM** [primefaces/primeng#942]
Hi, I am trying to integrate the messages component in my project. I have created the messages folder containing messages.ts and messages.css. Also I have created the common folder to use api.ts. However in api.ts I am getting error for this.acceptConfirmationSource.next(); function and that is why I am unable to integrate it.

**Comment by cagataycivici** [comment]
Hi, please use forum for how-to like questions and support requests.
