### ISSUE TITLE
Advanced Filtering for Table

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#9420]
Implement new advanced filtering with;

- Built-in filters via p-columnFilter
- numeric, date, boolean, switch, slider, text based filters
- And Or operator support
- Row and Menu UI options
- Custom filter UI support
- Dynamic filter match modes
- Multiple constraint option for a field

**Comment by souravsaraf** [comment]
Thanks a lot for building this feature.  🤩 ❤❤

Question ==> Can sort and filter be used together (in Primeng version 11.0.0 rc-1) ?

I tried something below in a `<p-table>` tag

```HTML
<ng-template pTemplate="header">
    <tr>
        <!-- Order Id -->
        <th [pResizableColumn] [pSortableColumn]="order_id">
            <span>Order Id</span>
            <p-sortIcon [field]="order_id"></p-sortIcon>
            <p-columnFilter type="text" field="order_id" display="menu"></p-columnFilter>
        </th>

        <!-- Design No -->
        <th [pResizableColumn] [pSortableColumn]="design_no">
            <span>Design No</span>
            <p-sortIcon [field]="design_no"></p-sortIcon>
            <p-columnFilter type="text" field="design_no" display="menu"></p-columnFilter>
        </th>
    </tr>
</ng-template>
```

My multi-filters are working as expected, but multiple sort (which used to work before) are not working.

Please see attached gif : 

![Primeng Version 11 0 0-rc 1 Sort not working after New Filter](https://user-images.githubusercontent.com/3005625/99888851-d027d800-2c75-11eb-8dc4-42439c70fcd4.gif)

Any help would be appreciated 😀

**Comment by smunir** [comment]
Couldn't really get reason to change 
`filters?: {[s: string]: FilterMetadata;};` 
to 
`filters?: {[s: string]: FilterMetadata | FilterMetadata[];};`

Can you please elaborate?
