### ISSUE TITLE
Can't create custom handlers throw modules propery

### ISSUE THREAD

**Issue by Exlord** [primefaces/primeng#9421]
**I'm submitting a ...**  
```
[X] bug report 
```

**Current behavior**
Can't add custom handlers to toolbar using `modules` property

**Expected behavior**
add custom handlers to toolbar using `modules` property

**Minimal reproduction of the problem with instructions**

```
<p-editor [(ngModel)]="text"
          [style]="{'height':'200px'}"
          (onInit)="onEditorInit($event)"
          [modules]="modules"
          (onTextChange)="textChange.emit($event.htmlValue)">
  <ng-template pTemplate="header">
    <span class="ql-formats">
      <select class="ql-font"></select>
      <select class="ql-size"></select>
    </span>
    <span class="ql-formats">
      <button class="ql-bold"></button>
      <button class="ql-italic"></button>
      <button class="ql-underline"></button>
      <button class="ql-strike"></button>
    </span>
    <span class="ql-formats">
      <select class="ql-color"></select>
      <select class="ql-background"></select>
    </span>
    <span class="ql-formats">
      <button class="ql-script" value="sub"></button>
      <button class="ql-script" value="super"></button>
    </span>
    <span class="ql-formats">
      <button class="ql-header" value="1"></button>
      <button class="ql-header" value="2"></button>
      <button class="ql-blockquote"></button>
      <button class="ql-code-block"></button>
    </span>
    <span class="ql-formats">
      <button class="ql-list" value="ordered"></button>
      <button class="ql-list" value="bullet"></button>
      <button class="ql-indent" value="-1"></button>
      <button class="ql-indent" value="+1"></button>
    </span>
    <span class="ql-formats">
      <button class="ql-direction" value="rtl"></button>
      <select class="ql-align"></select>
    </span>
    <span class="ql-formats">
      <button class="ql-link"></button>
      <button class="ql-image"></button>
      <button class="ql-video"></button>
      <button class="ql-formula"></button>
    </span>
    <span class="ql-formats">
      <button class="ql-clean"></button>
    </span>
  </ng-template>
</p-editor>
```

```
this.modules = {
      toolbar: {
        handlers: {
          image: function () {            
            
          },
        }
      }
    };
```

**What is the motivation / use case for changing the behavior?**
This will messup the toolbar, becuse of this https://github.com/primefaces/primeng/blob/8bac0ee87c9d793095c393030387ab65e7d5b7a7/src/app/components/editor/editor.ts#L116

```
        let defaultModule  = {toolbar: toolbarElement};
        let modules = this.modules ? {...defaultModule, ...this.modules} : defaultModule;
```

The container is getting overriden when `modules.toolbar` is customized .
` let defaultModule  = {toolbar: toolbarElement};` this should be changed to ` let defaultModule  = {toolbar: {container:toolbarElement}};`

* **Angular version:** 5.X
Angular CLI: 10.1.6
Node: 12.18.3
OS: win32 x64

Angular: 10.1.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.6
@angular-devkit/build-angular   0.1001.6
@angular-devkit/core            10.1.6
@angular-devkit/schematics      10.1.6
@angular/cdk                    10.2.4
@angular/cli                    10.1.6
@angular/material               10.2.4
@schematics/angular             10.1.6
@schematics/update              0.1001.6
rxjs                            6.6.3
typescript                      3.9.7

* **PrimeNG version:** 5.X
10.0.3

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
