### ISSUE TITLE
Paginator in PrimeNG datatable is Not looking fine

### ISSUE THREAD

**Issue by sgda021992** [primefaces/primeng#9422]
I have created a simple webpage 

     <div class="container">
       <div class="row">
         <div class="container aos-init aos-animate" data-aos="fade-up">
           <div class="mt-7">
             <div>
              <img class="logoPos" src="assets/img/faculty.png">
              <img class="textPos" src="assets/img/userm.png">
            </div>
          </div>
        </div>
     </div>
     <div class="row">
        <div class="card">
      <p-table #dt [value]="users" dataKey="_id" [resizableColumns]="true" styleClass="p-datatable-gridlines" [paginator]="true" [rows]="10" [showCurrentPageReport]="true" currentPageReportTemplate="Showing {first} to {last} of {totalRecords} entries" [rowsPerPageOptions]="[10,25,50]" [scrollable]="true" scrollHeight="300px">
        <ng-template pTemplate="colgroup">
          <colgroup>
              <col style="width: 130px;">
              <col style="width: 140px;">
              <col style="width: 150px;">
              <col style="width: 130px;">
              <col style="width: 130px;">
              <col style="width: 180px;">
              <col style="width: 130px;">
          </colgroup>
        </ng-template>
        <ng-template pTemplate="header" >
          <tr>
            <th pResizableColumn pSortableColumn="assigned_role.title">User Type<p-sortIcon field="assigned_role.title"></p-sortIcon></th>
            <th pResizableColumn pSortableColumn="username">User Name<p-sortIcon field="username"></p-sortIcon></th>
            <th pResizableColumn pSortableColumn="email">Email<p-sortIcon field="email"></p-sortIcon></th>
            <th pResizableColumn pSortableColumn="mobile">Contact<p-sortIcon field="mobile"></p-sortIcon></th>
            <th pResizableColumn pSortableColumn="createdOn">DOJ<p-sortIcon field="createdOn"></p-sortIcon></th>
            <th pResizableColumn pSortableColumn="account_is_verified">Account Verified<p-sortIcon field="account_is_verified"></p-sortIcon></th>
            <th pResizableColumn pSortableColumn="is_active">Active<p-sortIcon field="is_active"></p-sortIcon></th>
            <th pResizableColumn>Action</th>
          </tr>
        </ng-template>
        <ng-template pTemplate="body" let-user let-ri="rowIndex">
          <tr>
            <td class="ui-resizable-column">{{user.assigned_role.title}}</td>
            <td class="ui-resizable-column">{{user.username}}</td>
            <td class="ui-resizable-column">{{user.email}}</td>
            <td class="ui-resizable-column">{{user.mobile}}</td>
            <td class="ui-resizable-column">{{user.createdAt | date: 'mediumDate'}}</td>
            <td class="ui-resizable-column">{{user.account_is_verified}}</td>
            <td class="ui-resizable-column">{{user.is_active}}</td>
            <td>
              <div class="custom-control custom-switch">
                <input type="checkbox" class="custom-control-input" id="customSwitches" [checked]="user.is_active" (click)="switchUser(user, ri)">
                <label class="custom-control-label" for="customSwitches">Active</label>
              </div>
            </td>
          </tr>
        </ng-template>
        <ng-template pTemplate="emptymessage" >
          <div class="watermark" >No results found</div>
        </ng-template>
      </p-table>
    </div>
  </div>
</div>

but in the browser it is not looking well aligned in the latest release
![Capture](https://user-images.githubusercontent.com/50076693/96411888-d81fd280-1206-11eb-8b2c-e847ea456a11.JPG)

**Comment by yigitfindikli** [comment]
Please use forum for questions and help requests.
