### ISSUE TITLE
Dialog is not draggable for touch devices

### ISSUE THREAD

**Issue by aakashnebhani** [primefaces/primeng#9423]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
p-dialog is draggable for desktop browsers but on touch devices not able to drag p-dialog component

**Expected behavior**
Behavior should be same on touch devices also and p-dialog should be draggable.

**What is the motivation / use case for changing the behavior?**
p-dialog should be allowed to drag on touch devices

**Please tell us about your environment:**
safari on iPad

* **Angular version:** 9.X

* **PrimeNG version:** 9.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all browsers on touch devices
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by andrew-potachits** [comment]
@yigitfindikli  Do you have any idea whether this issue is going to be addressed in the nearest release?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by Enlumis** [comment]
up

**Comment by NamesMT** [comment]
Could we get a re-open on this?

**Comment by aakashnebhani** [comment]
Please re-open this issue as it still does not work.
