### ISSUE TITLE
Checkbox Disabled don't work

### ISSUE THREAD

**Issue by cyberrranger** [primefaces/primeng#9424]
```
[X] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/github-1dobes?file=src%2Fapp%2Fapp.component.ts

**Minimal reproduction of the problem with instructions**
show
https://stackblitz.com/edit/github-1dobes?file=src%2Fapp%2Fapp.component.ts

and click on the disabled checkbox

**What is the motivation / use case for changing the behavior?** Bug

* **Angular version:** 10.x

* **PrimeNG version:** 10.x

* **Browser:** [all]
 
* **Language:** [all]

**Comment by pmo1948** [comment]
Hi, I do not think this is a bug. (click) is an html event that would even work on a header tag, for instance. The event you are probable looking for is the (onChange) event exposed by primeNg
![image](https://user-images.githubusercontent.com/69136429/96722028-997c4a80-13b5-11eb-83e6-32ce522d9c58.png)
try making this change, it should solve your issue.
https://stackblitz.com/edit/github-1dobes-r8f1wa?file=src%2Fapp%2Fapp.component.html

**Comment by cyberrranger** [comment]
oh thx
