### ISSUE TITLE
Dropdown/MultiSelect control should be marked as touched after onchange

### ISSUE THREAD

**Issue by BGBRWR** [primefaces/primeng#9425]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/github-zbxy9m

**Current behavior**
On input blur (mousedown) onModelTouched is ran. On input change (mouseup) a value is set to the form control. This will run and show validation before a value is set.

**Expected behavior**
When a value is selected (mouseup) onModelTouched is ran. Same for focusout of dropdown component (not internal input element). Mirroring event behaviors of a native select would be ideal. Previewing options and closing dropdown while still in focus should not run onModelTouched. Only input change and focusout should mark model as touched.

**Minimal reproduction of the problem with instructions**
1. Select Primeng dropdown.
2. Click and hold on a value.
3. See validation error until mouseup.
4. Repeat without holding and see a flash of validation errors. 

**What is the motivation / use case for changing the behavior?**
This will have a better user experience without flashing validation errors and work more like a extension of a select element.  While this is similar to #7629, that ticket is only a fix for search while not addressing same issue at the root level.

**Please tell us about your environment:**

* **Angular version:** 10.0.14

* **PrimeNG version:** 10.0.0

* **Browser:** all

 
* **Language:** all
* **Node (for AoT issues):** `node --version` =   v10.16.0

**Comment by BGBRWR** [comment]
Previewing options and closing dropdown while still in focus should not run onModelTouched would fix #9305.

**Comment by BGBRWR** [comment]
This is parent issue of this #3809. Unlike dropdown, multiselect shouldn't mark as touched until previewing options is closed.

**Comment by bmcilw1** [comment]
As an extension to this issue, IMO Dropdown/MultiSelect control should ALSO be marked as touched after an attempted submit, especially if the control is in an invalid state. If a control is marked as required, it should highlight as red if submit is clicked before all needed values are present.

**Comment by davidediak** [comment]
Did anyone found a workaround for this?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
