### ISSUE TITLE
ColorPicker is not displayed inside overlayPanel correctly after the second open of overlay

### ISSUE THREAD

**Issue by baranovskyi** [primefaces/primeng#9429]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

The following example is here https://stackblitz.com/edit/angular-cbsdqf?file=src/app/app.component.html

**Current behavior**
On the first overlayPanel opening everything is okay, but on the all next opening the content is now shown
![image](https://user-images.githubusercontent.com/33638516/96728380-bbc59680-13bc-11eb-9161-326018ac12ad.png)

**Expected behavior**
The content should be displayed
![image](https://user-images.githubusercontent.com/33638516/96728336-b10b0180-13bc-11eb-8465-27aa8cd1f50c.png)

**Minimal reproduction of the problem with instructions**
just click on this ( https://stackblitz.com/edit/angular-cbsdqf?file=src/app/app.component.html ) URL and click the 'show panel' button. then hide overlay and click this button again

* **Angular version:** 8.2.0

* **PrimeNG version:** 8.1.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Comment by baranovskyi** [comment]
> Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

I attached stackblitz link with the issue https://stackblitz.com/edit/angular-cbsdqf?file=src/app/app.component.html
you can try and you will notice that if you open overlay panel the second time the color picker is not visible for some reasons
