### ISSUE TITLE
Customize p-sortIcon icon

### ISSUE THREAD

**Issue by scriptom** [primefaces/primeng#9431]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

When using SortIcon component in a Datatable, the icon used to display sorting direction and capability is forced to pi-sort-alt family of icons. Sometimes it is desired that these icons vary (merely for visual purposes as this has no functional influence).
**Expected behavior**

One should be able to customize icons based on input parameters as such:
`<p-sortIcon sortAscIcon="pi-sort-up" sortDescIcon="pi-sort-down" sortNoneIcon="pi-sort"></p-sortIcon>`

**What is the motivation / use case for changing the behavior?**

Sometimes it is desired to use a different set of icons, like the non-alt sort icons, or even chevron icons (Depends entirely on the business).

**Please tell us about your environment:**

OS: Windows 10 x64
IDE: PhpStorm 2020.2
Package manager: NPM v6.14.5
* **Browser:** [all]

 
* **Language:** [all]

**Comment by cagataycivici** [comment]
This should better be done from PrimeNGConfig globally or with css, it would be a pain to do this over and over again for every table with many columns.

**Comment by tiagolisalves** [comment]
@scriptom I've changed these icons on my project  with CSS : 

 ```
    .pi-sort-alt:before {
		content: '\e903 \A \e902';
	}

	.pi-sort-amount-up-alt:before {
		content: '\e903';
	}

	.pi-sort-amount-down:before {
		content: '\e902';
	}
```

**Comment by Theinfinix500** [comment]
> 

Yes you can get the codes from their icons they show you the correct code in their website

**Comment by nicholasirsyad** [comment]
what is someone needs to use a custom <i class='pi pi-arrow-down'> for example?
