### ISSUE TITLE
table state not working for dropdowns filter

### ISSUE THREAD

**Issue by MohamedSahir** [primefaces/primeng#9433]
I am using primeng table and save the filter state by using localstorage based on documentation.

Table State
`stateStorage="local" stateKey="statedemo-local"`

once set the filter, refresh the page , the selected filter is persist in the filterbox and results,

But for dropdown , filter result is working fine and not set in filter dropdown,
eg) consider i select nokia in dropdown menu and doing the refresh, i get nokia results in table, but filter dropdown its not selected.

textBox working based on doc example.

```
<th>
                    <input pInputText type="text" (input)="dt1.filter($event.target.value, 'name', 'contains')" [value]="dt2.filters['name']?.value" placeholder="Search by Name" class="p-column-filter">
                </th>
```
Dropdown not working.
```

**tried with below  3 options**
-- there is no value property binding

  [value]="dt2.filters['status']?.value"
---- so  i tried ngModel
[(ngModel)]="dt2.filters['status']?.value" - ngmodel does nt support null operators.
[(ngModel)]="dt2.filters['status'].value"  - ui cosole error and breaks  by using this options getting undefined 

Here i need to use ngIf statement to achieve this else any other ways as textbox
-----
3rd
[filterBy]="dt2.filters['status']?.value"

   <p-dropdown [options]="statuses" (onChange)="dt.filter($event.value, 'status', 'equals')" 
                     [value]="dt2.filters['status']?.value"
                 
                    styleClass="p-column-filter" placeholder="Select a Status" [showClear]="true">
                        <ng-template let-option pTemplate="item">
                            <span [class]="'customer-badge status-' + option.value">{{option.label}}</span>
                        </ng-template>
                    </p-dropdown>
```
![image](https://user-images.githubusercontent.com/20682302/96759182-52ae4500-13f5-11eb-95ed-59f1bf628088.png)

[demo:](https://stackblitz.com/edit/primeng-tablefilter-demo-w9m7jc?file=src%2Fapp%2Fapp.component.html)

**Comment by MohamedSahir** [comment]
any  updates on this

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.3.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
