### ISSUE TITLE
Performance issues with p-autocomplete component. Loading large set of data in p-autocomplete dropdown takes more than 8 seconds to open

### ISSUE THREAD

**Issue by ljupchoristovski** [primefaces/primeng#9438]
Plunkr Case (Bug Reports)

https://stackblitz.com/edit/angular-ivy-mxtgae?file=src%2Fapp%2Fproduct.service.ts

Current behavior
When we load large set of data in p-autoComplete dropdown component, it takes more than 8 seconds to open.

Expected behavior
Loading large set of data in p-autocomplete dropdown component should have better performance.

What is the motivation / use case for changing the behavior?
To fix the issue with loading large set of data in p-autoComplete dropdown component

Please tell us about your environment:
OS: Windows 10, IDE: Visual Studio Code

Angular version: 5.X
Angular 10.1.2

PrimeNG version: 5.X
PrimeNG 10.0.3

Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome Version 85.0.4183.121

Language: [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 3.1.1

Issue is easy to reproduce. Load large set of data in the p-autoComplete dropdown. When you click to open the dropdown with values it takes couple of seconds to load the values.

**Comment by montelyno** [comment]
Same issue, maybe the virtual scrolling feature can be connected to not render everything directly.

**Comment by leykov** [comment]
I have the same problem.

**Comment by btopukov** [comment]
I am facing the same issue.

**Comment by Saura81** [comment]
Same problem here

**Comment by noteme-io** [comment]
Facing the same issue.

**Comment by flkeller** [comment]
same issue here

**Comment by cagataycivici** [comment]
Can only be solved with;

https://github.com/primefaces/primeng/issues/7442
