### ISSUE TITLE
table filter multiple values in a single columns

### ISSUE THREAD

**Issue by thorizer** [primefaces/primeng#9439]
**I'm submitting a ...** 
```
[ ] bug report 
[X] feature request 
[ ] support request 
```
**Minimal reproduction of the problem with instructions**

I want to filter a table with multiple customer tags : 
this is how the table looks like

![msedge_3S1Y8dGk3d](https://user-images.githubusercontent.com/13587810/96889944-0a3b6980-147f-11eb-9280-d761fc1d691a.png)

i have a tags column in customer table . depending on the tags selected on the filter, the table will show only the customers that have at least these tags ("contains" but not for strings) , (I've added the json structures in the column)

> this.table.filter(tags, 'tags', 'contains');

sadly, this table.filter only accepts strings. what I'd like to achieve is a filter of array of object with a particular field ( field called name in this example ) 

![msedge_adqHCsQapn](https://user-images.githubusercontent.com/13587810/96889097-2b4f8a80-147e-11eb-984f-60500ecc1a86.png)

![msedge_v94lDZiBxq](https://user-images.githubusercontent.com/13587810/96888818-ecb9d000-147d-11eb-9991-8b876b6b7652.png)
)

**Comment by malcomm** [comment]
+1 for this feature as well. I have a pretty similar case where a column is represented by an array of object (I'm using p-listbox on the edit of the row) and I would like the ability to filter on this column ... I don't see a way to do this.

**Comment by lwestfall** [comment]
If I'm understanding the issue correctly, you can register a custom filter mode. I have done similar using the below, where `array-some` will match a row if its array field contains any one of the selected filters, and `array-every` will only match the row if all of the array items match the selected filters:

```js
// register filter type for array items, when filter has one or more of values
FilterUtils['array-some'] = (value: any[], filters) => {
  if (filters === undefined || filters === null || filters.length === 0) {
      return true;
  }

  return value.some(v => filters.includes(v));
};

// register filter type for array items, when filter has every value
FilterUtils['array-every'] = (value: any[], filters) => {
  if (filters === undefined || filters === null || filters.length === 0) {
      return true;
  }

  return value.every(v => filters.includes(v));
};
```

HTH

**Comment by thorizer** [comment]
@lwestfall  I made a little changes and it works. I can't find this in the docs thought.

**Comment by malcomm** [comment]
@lwestfall - thank you for the assistance here. I got this to work for my scenario as well, but agree I'm not seeing this documented. Would be great to see a section for **Custom Filters** and a reference to [FilterUtils](https://www.primefaces.org/primeng/showcase/#/filterutils) on these two pages:

- https://www.primefaces.org/primeng/showcase/#/table/filter
- https://www.primefaces.org/primeng/showcase/#/table

Something like:
----

### Custom Filters

- See: [FilterUtils](https://www.primefaces.org/primeng/showcase/#/filterutils)

```
<input pInputText type="text"
  (input)="dataTable.filter($event.target.value, 'containerObject.items', 'includes-site-name')"
  placeholder="Search by Site" class="p-column-filter">
```

```
  async ngOnInit() {
    this.initCustomFilter();
  }

  async initCustomFilter() {
    FilterUtils['includes-object-name'] = (values: any[], filter: string) => {
      if (filter === undefined || filter === null || filter.length === 0) {
        return true;
      }

      if (values === undefined || values === null) {
        return false;
      }

      let match = false;
      for (const v of values) {
        const name: string = v.object.name;
        if ((name !== undefined && name !== null)) {
          const filterUpper = filter.toUpperCase();
          const nameUpper = name.toUpperCase();
          if (nameUpper.includes(filterUpper)) {
            match = true;
            break;
          }
        }
      }
      return match;
    };
  }
```

**Comment by lwestfall** [comment]
I agree the documentation could be improved/expanded on for FilterUtils in general. It would be nice if there was more of a tutorial on writing your own filter functions.

**Comment by cagataycivici** [comment]
We need a new built-in filter for this, currently there is "in" but that won't help here.

**Comment by GRDtechlab** [comment]
I have similar case, Where I want to filter data using custom filter-service like below is data type..

```javascript
this.allClients = [
      {
        id: '1',
        clientName: 'Client 1',
        city: 'string',
        nit: 'string',
        bills: [
          {
            billCode: 'cb01',
            total: 200,
            subtotal: 100,
            iva: 122,
            retention: 4,
            creationDate: new Date(),
            status: 'status',
            isPaid: false,
            paymentDate: new Date(),
          },
          {
            billCode: 'cb02',
            total: 400,
            subtotal: 500,
            iva: 122,
            retention: 4,
            creationDate: new Date(),
            status: 'status',
            isPaid: false,
            paymentDate: new Date(),
          },
          {
            billCode: '8',
            total: 400,
            subtotal: 500,
            iva: 122,
            retention: 4,
            creationDate: new Date(),
            status: 'status',
            isPaid: false,
            paymentDate: new Date(),
          },
        ],
      },
    ]; 
```
So, as per above data structure, `bills : [ ]` is inner array fields. Now, I am implementing column filter using filter - service and register custom filter like below, 

```javascript
this.filterService.register('isPrimeNumber', (value, filter): boolean => {
      console.log(value, filter);
      if (filter === undefined || filter === null || filter.trim() === '') {
        return true;
      }

      if (value === undefined || value === null) {
        return false;
      }
     return value.some((v) =>
        filter.toString().includes(v[this.currentFilterColumnField].toString())
      ); 
});
```
so, this will not filter the data like as implemented as per above code filter.
Here is demo, Inside demo when you click type first column like `c` then all three data will remain same, Rather I want to filter bills data which are started with `c` and so on.. You can see this in stackblitz demo Please suggests me the way for this. Thanks!
[https://stackblitz.com/edit/primeng-tabledoc-demo-lleesp?file=src%2Fapp%2Fapp.component.ts](url)

**Comment by ssaiffullahh** [comment]
> I have similar case, Where I want to filter data using custom filter-service like below is data type..
> 
> ```js
> this.allClients = [
>       {
>         id: '1',
>         clientName: 'Client 1',
>         city: 'string',
>         nit: 'string',
>         bills: [
>           {
>             billCode: 'cb01',
>             total: 200,
>             subtotal: 100,
>             iva: 122,
>             retention: 4,
>             creationDate: new Date(),
>             status: 'status',
>             isPaid: false,
>             paymentDate: new Date(),
>           },
>           {
>             billCode: 'cb02',
>             total: 400,
>             subtotal: 500,
>             iva: 122,
>             retention: 4,
>             creationDate: new Date(),
>             status: 'status',
>             isPaid: false,
>             paymentDate: new Date(),
>           },
>           {
>             billCode: '8',
>             total: 400,
>             subtotal: 500,
>             iva: 122,
>             retention: 4,
>             creationDate: new Date(),
>             status: 'status',
>             isPaid: false,
>             paymentDate: new Date(),
>           },
>         ],
>       },
>     ]; 
> ```
> 
> So, as per above data structure, `bills : [ ]` is inner array fields. Now, I am implementing column filter using filter - service and register custom filter like below,
> 
> ```js
> this.filterService.register('isPrimeNumber', (value, filter): boolean => {
>       console.log(value, filter);
>       if (filter === undefined || filter === null || filter.trim() === '') {
>         return true;
>       }
> 
>       if (value === undefined || value === null) {
>         return false;
>       }
>      return value.some((v) =>
>         filter.toString().includes(v[this.currentFilterColumnField].toString())
>       ); 
> });
> ```
> 
> so, this will not filter the data like as implemented as per above code filter. Here is demo, Inside demo when you click type first column like `c` then all three data will remain same, Rather I want to filter bills data which are started with `c` and so on.. You can see this in stackblitz demo Please suggests me the way for this. Thanks! [https://stackblitz.com/edit/primeng-tabledoc-demo-lleesp?file=src%2Fapp%2Fapp.component.ts](url)

did you find a solution to this?

**Comment by GRDtechlab** [comment]
> 

Hi ssaiffullahh, Please connect with me by email `grdtechlab@gmail.com` and we will discuss about the same. Looking forward to hear from you. Thanks!

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by khaldi-yass** [comment]
Hello I don't think this feature has been added, at least it's not in the documentation version "V15.4.1".
I will reopen this issue as you suggested.

**Comment by MarlonKrauseOpitzConsulting** [comment]
Hi,

i have created a solution for the problem that you wanna have some kind of range filter, a filter with filter values, to filter on one column.

First of all you need a custom filter registered in the filter services of primeng that can recieve a filter with an element.


this.filterService.register('isRangeFilter', (value, filter: {start: any, end: any}): boolean => {
    if (filter === undefined || filter === null) {
        return true;
    }

    if (value === undefined || value === null) {
        return false;
    }

    return value >= filter.start && value <= filter.end;
});

https://primeng.org/filterservice

than you need a component where u hold your custom template. 
There you inject the the Table as 'dt' from PrimeNg and then u can bind the values from dt.filters['fieldname] to a local ref.

i would use an IF statement in NgOnInit bc first time the filter is null and you get maybe an error later when u wanna accessing nested object in null.

when u wanna bind the range filter object back to the dt.filter u only need to hook up at the Value Change listener at your filter model and call some methode that do at least this = 

    (<any>this.dt.filters[<string>this.field])[0].value = this.filterValue;
    
  that binds your filter values back to the primeng datatable filter values and when you press the primeng apply button your filter should work as expected.
