### ISSUE TITLE
Radio buttons do not get unselected on the same group, with Reactive Forms

### ISSUE THREAD

**Issue by tuchorc** [primefaces/primeng#9440]
**I'm submitting a ...**
```
[x] bug report
```

**Plunkr Case (Bug Reports)**
Using PrimeNG current Template
https://stackblitz.com/edit/github-f2wj15?file=src/app/app.component.html

**Current behavior**
When using p-radiobutton element with ReactiveFroms, once a radio button gets selected, it never gets unselected. However the form value updates properly.

**Expected behavior**
Only the current value should be selected on screen

**Minimal reproduction of the problem with instructions**
Just create a reactive form, with a form control, and a group of radiobuttons. This is a minimal reproduction of the problem, NOT from PrimeNG template on Stackblitz.
https://stackblitz.com/edit/angular-ivy-qc5lgc?file=src%2Fapp%2Fapp.component.html

**What is the motivation / use case for changing the behavior?**
It doesn't behave as the Template Driven Froms, and as it is expected to behave

* **Angular version:**
Angular 10.2.0

* **PrimeNG version:**
PrimeNG 10.0.3 

* **Browser:** 
all
Chrome Version 86.0.4240.80 (Official Build) (x86_64)
Firefox 81.0.2 (64-bit)
Safari Version 14.0 (15610.1.28.1.9, 15610)

**Comment by jurt** [comment]
I believe this is related to [this issue](https://github.com/primefaces/primeng/issues/9162), not sure however why its closed if merge request fixing it titled "Fixed radiobutton with **template-driven forms**"

**Comment by miheyinfo** [comment]
+1

**Comment by miguelarcjr** [comment]
I'm also having the same problem.

**Comment by karol93** [comment]
same...

**Comment by rafparedis** [comment]
I also have this issue

**Comment by jurt** [comment]
Workaround suggested by @keschr in related topic worked for me:

`
control.valueChanges.subscribe(e => {
  control.setValue(e, {emitEvent: false});
});
`

**Comment by cagataycivici** [comment]
Please see;

https://github.com/primefaces/primeng/issues/9162
