### ISSUE TITLE
Request for TREE add/remove and show TREE structure demo code

### ISSUE THREAD

**Issue by weilies** [primefaces/primeng#9445]
**I'm submitting a ...**  (check one with "x")
```
[x ] feature request => Able to add/remove tree node (official code) and list out TREE structure in JSON format
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-tree-da8r?

**Current vs Expected behavior**

- Able to append new tree node to selected node. But if i try to add more child node, all the previously added node will change to the same name. It would be great if developer could share a working code to add new node dynamically

- Unable to delete the top level of node. Appreciated if developer could provide a demo

- I am creating an advance security customization page using primeNG tree. The tree structure is needed to be convert to JSON with 'role' tag to 'data' property in tree. Later when the user login, the JSON should be call out and build primeNG navItem after login. But my current challenge, i couldn't find an available API to call in order to return the whole TREE.

**Please tell us about your environment:**
StackBlitz

* **Angular version:** 10.0

* **PrimeNG version:** 10.0

* **Browser:** Chrome

 
* **Language:** TypeScript, Angular

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
