### ISSUE TITLE
overlayPanel - hide on selected dropdown and datepicker

### ISSUE THREAD

**Issue by WoocashSilesia** [primefaces/primeng#9447]
Hi.
I have created a form in p-overlayPanel. The form contains dropdowns and datepickers. When i have an option [dismissable]="true" and for example i pick element in dropdown, the overlayPanel with whole form hides.

Current behavior
An overlayPanel with option [dismissable]="true"  hides when selected dropdown or date in datepicker.

Expected behavior
 hide overlayPanel only when clicked outside, but prevent from hiding when dropdown or datepicker is closing ?

Angular version: 10.0
PrimeNG version: 10.0.3
Browser: Chrome
Language: TypeScript, Angular

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Comment by tripathiarpit** [comment]
I am using primeng 9.1.3 and this issue is still there.

<button (click)="op.toggle($event)">Show Panel<button>
<p-overlayPanel
    [dismissable]="true"
    [showCloseIcon]="true"
    #op"
>
    <ng-template pTemplate="cp">
         <p-dropdown
          [options]="cities"
          [(ngModel)]="selectedCity"
          optionLabel="name"
          [appendTo]="'body'"
        >
        </p-dropdown>
    </ng-template>
</p-overlayPanel>

**Comment by bkj281** [comment]
Issue is reproducible with version 17.18.0 too.
