### ISSUE TITLE
TimeOnly Calendar traps keyboard focus

### ISSUE THREAD

**Issue by bmayen** [primefaces/primeng#9449]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Using keyboard to access TimeOnly Calendar traps the focus in the panel. While hitting enter will increment/decrement the time in the panel, there appears to be no way to close the panel and apply the time to the input.

**Expected behavior**
Opened panel should not trap focus. Keyboard selections should either immediately apply to input so user can then use escape key to close panel, or user should be able to tab out of panel and have selections applied to input then.

* **PrimeNG version:** 9.X

Still an issue in 10.x

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
