### ISSUE TITLE
p-autoComplete cleared when forceSelection enabled and using the enter to select (then tab out)

### ISSUE THREAD

**Issue by LukeHartcher** [primefaces/primeng#9460]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/primeng-autocomplete-demo-c9hk6w

**Current behavior**

- Run stackblitz sample
- Type "aus" in the dropdown
- Use Down Arrow to highlight Australia
- Use ENTER key to select Australia
- Use TAB key to move to next field
- Dropdown is cleared!!!

**Expected behavior**

- Run stackblitz sample
- Type "aus" in the dropdown
- Use Down Arrow to highlight Australia
- Use ENTER key to select Australia
- Use TAB key to move to next field
- Dropdown retains the selected Australia item

**Minimal reproduction of the problem with instructions**

- Set [forceSelection]="true" on the component
- Follow steps above

**What is the motivation / use case for changing the behavior?**

- It is broken

**Please tell us about your environment:**
- Your Stackblitz autocomplete sample forked/modified

* **Angular version:** 10.0.1

* **PrimeNG version:** 10.0.0

**Comment by luboslav** [comment]
Duplicate of [9378](https://github.com/primefaces/primeng/issues/9378) that contains [workaround](https://github.com/primefaces/primeng/issues/9378#issuecomment-706982815)

**Comment by LukeHartcher** [comment]
Workaround resolved the issue. Will close this issue and follow #9378 .
