### ISSUE TITLE
p-table - table.ts not handling missing filter function 

### ISSUE THREAD

**Issue by waratah** [primefaces/primeng#9461]
In table.ts the following function will resolve filterConstraint to null if the filtering code is not set up properly on restart.   the in turn crashes the table and I get no results.

If the filterMatchMode is invalid it should return a function so that it does not filter at all (always true) or always strips data (always false) in this way the table would at least show and we could reset the filtering.

My actual problem of course is that the filtering code is not installed on start up and that is my issue,  just want to protect the guilty when things like this go wrong.

executeLocalFilter(field: string, rowData: any, filterMeta: FilterMetadata): boolean {
        let filterValue = filterMeta.value;
        let filterMatchMode = filterMeta.matchMode || FilterMatchMode.STARTS_WITH;
        let dataFieldValue = ObjectUtils.resolveFieldData(rowData, field);
        let filterConstraint = FilterUtils[filterMatchMode];

  ****   filterConstraint is null due to badly configured filter logic.

        return filterConstraint(dataFieldValue, filterValue, this.filterLocale);
    }

**Comment by cagataycivici** [comment]
I think it should be handled on application side. Also please check out the new FilterService;

https://github.com/primefaces/primeng/issues/9547
