### ISSUE TITLE
p-table collapsible

### ISSUE THREAD

**Issue by likefurnis** [primefaces/primeng#9463]
**I'm submitting a ...**
[ x ] feature request

**Current behavior**
The table is not collapsible (toggleable).

![image](https://user-images.githubusercontent.com/18721359/97491778-ed150800-1962-11eb-932e-65533e5ff291.png)

**Expected behavior**
Make the table collapsible as the PrimeNG component `p-panel` if the user specifies that it needs it. It should appear at the caption bar.

**I've already developed this feature for PrimeNG 10.0.3 and created a related PR #9464.**

![image](https://user-images.githubusercontent.com/18721359/97495609-1edc9d80-1968-11eb-947b-b470ae73aec3.png)

**What is the motivation / use case for changing the behavior?**
You don't need to combine two components, which makes it harder to read, needs to import more stuff, and it looks way better if the table can toggle by itself.

* **Angular version:** 10.2.0

* **PrimeNG version:** 10.0.3

* **Browser:** all
 
* **Language:** all

**Comment by yigitfindikli** [comment]
You can use inside of the [p-panel](https://www.primefaces.org/primeng/showcase/#/panel).

**Comment by likefurnis** [comment]
The point of this was to integrate both of them in one so it wouldn't look as bad as it does when you put the table inside the panel lol
