### ISSUE TITLE
Dynamic Dialog after close ngOnDestroy component  primeng-toast error

### ISSUE THREAD

**Issue by luoxiao-xy** [primefaces/primeng#9465]
Because the dynamic dialog will not be in the Ref.onClose Return the data I want, but return undefined. So I use ngondestroy in the dynamic dialog component to make onclose return the data I want.
![image](https://user-images.githubusercontent.com/49856280/97518084-7f53f500-19d1-11eb-9359-089503b6f0f9.png)

Then in the onclose subscription, filter out undefined and return only the data I want

![image](https://user-images.githubusercontent.com/49856280/97518318-ed98b780-19d1-11eb-88c0-da5a74ccb7b9.png)

In the components that need to use dynamic dialog, I use the form of service to make dynamic dialog public call. By subscribing, I return the data I want. But I didn't do anything. Only in the return subscription, toast is added. It was a mistake. Toast can be displayed normally.
![image](https://user-images.githubusercontent.com/49856280/97518483-394b6100-19d2-11eb-87c9-dc22fa5bae02.png)

As shown in the figure, this is the error thrown by angular.

![image](https://user-images.githubusercontent.com/49856280/97518686-b8409980-19d2-11eb-9f7b-cbcb3609dcae.png)

my app      angular 10.1.3
                 primeng 10.0.3

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
