### ISSUE TITLE
Issue with menu-bar not showing active item after upgrade to v10.0.3

### ISSUE THREAD

**Issue by chrizy** [primefaces/primeng#9473]
[X ] bug report => Search github for a similar issue or PR before submitting

After upgrading from v9 to 10.0.3 and using sage-blue theme.

The p-menubar no longer shows the active item based on router config.

`    <p-menubar [model]="menu">`

Old V9 style applied to text 
```
body .ui-menubar .ui-menuitem-link.ui-menuitem-link-active .ui-menuitem-icon, body .ui-menubar .ui-menuitem-link.ui-menuitem-link-active .ui-menuitem-text {
    color: #007ad9;
}
```
v10 no longer gets a colour selection applied to the active item.

Angular version: 10.1.7 (also tested and failed in v11.0.0)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
