### ISSUE TITLE
p-tabPanel does not detect changes when "disabled" binding is changed

### ISSUE THREAD

**Issue by kali-dali** [primefaces/primeng#9475]
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Demo on Stackblitz**
https://stackblitz.com/edit/primeng-tabview-disbale-bug?file=src/app/app.component.html

**Current behavior**
When I change the [disabled] binding of a `p-tabPanel` component, the change is only detected when I click on the changed tab.

**Expected behavior**
When I change the [disabled] binding of a `p-tabPanel` component, I expect the component to change to disabled/enabled state immediately.

**Please tell us about your environment:**
OS: Windows 10
Browser: Chrome
Angular Version: 10.2.0
PrimeNG: Version 10.0.3

**Comment by StevenFischerWI** [comment]
I'm having the same non-change-detection issue with basic properties like [header] and [leftIcon]. 

https://primeng-tabview-disbale-bug-qjzcja.stackblitz.io

Windows 10/Chrome/Angular 11.02, PrimeNG Version 11.0.0-rc.1

**Comment by carlos-hs** [comment]
Also facing the same issue.

OS: Windows 10
Browser: Chrome
Angular Version: 13.1.0
PrimeNG: Version 13.0.4

**Comment by MightyMorpheus** [comment]
Same issue here. headerStyleClass is not updating neither.

I'd like to highlight tab with form validation errors, but it does not update: [headerStyleClass]="submitAttempted && form.get('basicInfo').invalid ? 'ng-dirty ng-invalid' : ''"

I tried to use getter and put there console.log. The getter is called as usual and returns css classes as expected, but component does not update the header style.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by gstokesRev** [comment]
Hi Folks

Could this issue be reopened please, we have the very same problem as described and have updated to the latest version of PrimeNG and its doesn't solve the problem. This is quite  a major blocker for us

Thanks

**Comment by cetincakiroglu** [comment]
Hi,

Couldn't replicate the issue with the latest PrimeNG. Here is the stackblitz example of the same code with the primeng v16.3.1: https://stackblitz.com/edit/mfhtwi?file=src%2Fapp%2Fdemo%2Ftab-view-disabled-demo.html,src%2Fapp%2Fdemo%2Ftab-view-disabled-demo.ts

TabPanel works as expected, closing the issue.

**Comment by Feher-Zsofia** [comment]
Hi,

Please look up the follow-up bugs on this very same issue: https://github.com/primefaces/primeng/issues/9475#issuecomment-1050816830

It is still an issue, and it is a very important one for big forms.
