### ISSUE TITLE
p-calendar does not work on multi select when initially passing an empty array

### ISSUE THREAD

**Issue by mrdlink** [primefaces/primeng#9476]
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Stackblitz Demo**
https://stackblitz.com/edit/primeng-calendar-multiple-empty-array-bug?file=src/app/app.component.ts

**Current behavior**
When I set the `p-calendar` to `selectionMode="multiple"` and initially pass an empty array as `[(ngModel)]` the component does not work at all.

**Expected behavior**
When I set the `p-calendar` to `selectionMode="multiple"` and initially pass an empty array as `[(ngModel)]`, the component should behave like an `undefined` value was passed to it and show the date picker.

**Please tell us about your environment:**
OS: Windows 10
Browser: Chrome
Angular version: 10.2.0
PrimeNG version: 10.0.3

**Comment by mvandak** [comment]
The same, using <p-calendar> `multiple` and `inline` mode when empty array initially. Then after observable with data received, nothing changes in calendar as it was not correctly initialised

Console output
```console
core.js:6479 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'getMonth')
TypeError: Cannot read properties of undefined (reading 'getMonth')
    at Calendar.updateUI (primeng-calendar.js:1416)
    at Calendar.writeValue (primeng-calendar.js:1558)
    at onChange (forms.js:1734)
    at forms.js:2872
    at Array.forEach (<anonymous>)
    at FormControl.setValue (forms.js:2872)
    at forms.js:4590
    at ZoneDelegate.invoke (zone.js:372)
    at Object.onInvoke (core.js:28672)
    at ZoneDelegate.invoke (zone.js:371)
    at resolvePromise (zone.js:1213)
    at zone.js:1283
    at ZoneDelegate.invokeTask (zone.js:406)
    at Object.onInvokeTask (core.js:28659)
    at ZoneDelegate.invokeTask (zone.js:405)
    at Zone.runTask (zone.js:178)
    at drainMicroTaskQueue (zone.js:582)
```

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
