### ISSUE TITLE
Using appendTo (or omitting) on anything other than body leads to incorrectly positioned elements.

### ISSUE THREAD

**Issue by jonnomk** [primefaces/primeng#9480]
**I'm submitting a ...**  (check one with "x")

[x ] bug report

**Stackblitz example: https://github-zey1ui.stackblitz.io/**

**Please tell us about your environment:**
Windows 10, npm

* **Angular version:** 5.X
9.1.9

* **PrimeNG version:** 5.X
10.0.2

* **Browser:**
Google Chrome v86
 
* **Language:**
TypeScript

* **Node (for AoT issues):**
14.7

Please check this example of an overlay component in a positioned div.  This scenario is very common and please don't reply and say appendTo="body" is the fix, because it isn't, it's a workaround.

**https://github-zey1ui.stackblitz.io/**

Full StackBlitz here: https://stackblitz.com/edit/github-zey1ui?file=src/app/app.component.html

This issue happens in your overlay and menu components, and likely more.

I'm not even sure you need to call _DomHandler.absolutePosition_ in most scenarios as the overlay is correctly positioned before this is called.

I've tried setting the position of .p-overlay to fixed, but this doesn't work unless you change it after all the component calculations have been made.

appendTo="body" works great in dialogs and any scenario where the menu needs to position outside of overflow hidden, for example, but if I want to append to a template reference or simply want to omit appendTo then the alignment is all messed up.

What if I want to click some button and append the overlay to another element in my component.  So I use [appendTo]="whatever" and the overlay appears off the page, somewhere to the right.

The calculations your components make are more suited to fixed positioning than absolute...

It's a continuous stumbling block/frustration for me using your framework!

**Comment by montella1507** [comment]
i can confirm this issue.

**Comment by jonnomk** [comment]
Hello @cagataycivici.  I wonder if you can help.  We're using PrimeNG in our application - it's an enterprise app and we're making use of quite a few of your components, which all work really well.  I'm having trouble with a few components though, particularly since updating to v11.  The issues relate to Menu's and the fact that I'm having to use appendTo="body" to resolve an issue where the menu position isn't calculated correctly.  In previous versions, you had a nice behaviour where the menu would disappear on scroll which worked around the issue, but this was removed in V11 and now the issues are being picked up in testing and we're due to release an MVP in March.  Can we open up a dialog and look at the potential issue?  I would very much appreciate it.

**Comment by waratah** [comment]
This is still an issue across the board in version 13.   I have coded appendTo='body' on all my dropdowns and autocompletes to ensure they work correctly.  They were often chopped off or create scroll bars.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
