### ISSUE TITLE
Button | Renders empty label when the label is not defined

### ISSUE THREAD

**Issue by paulyipkh** [primefaces/primeng#9482]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When no label is assigned to pButton, text `&nbsp;` is rendered.

**Expected behavior**
When no label is assigned to pButton, the text should be empty, not space nor `&nbsp;`

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/github-7rxhpm?file=src/app/app.component.html

https://github.com/primefaces/primeng/blob/master/src/app/components/button/button.ts
e.g. line 45        `labelElement.appendChild(document.createTextNode(this.label||'&nbsp;'));`
the expression     `this.label||'&nbsp;'`    should be replaced with  `this.label === undefined || this.label === null ? '': this.label`

**Comment by jonnomk** [comment]
I totally agree with this.

**Comment by paulyipkh** [comment]
In PrimeNg 9, I could center align the content projected into the `<p-button>Content</p-button>`? Is there anybody know how this can be achieved in PrimeNg10 ?

![image](https://user-images.githubusercontent.com/12554293/97998355-f3a0f500-1e24-11eb-8c26-5eb2d89b073e.png)

**Comment by rsilva1959** [comment]
workaround -> define label= "Edit", but include classes p-button-icon-only no-label where
::ng-deep .no-label>.p-button-label {
  display: none;
}
<button *ngIf="config.actions.edit" label="Edit" pButton pRipple icon="pi pi-pencil" class="p-button-rounded p-button-success p-button-icon-only no-label p-mr-2"  (click)="editItem(item)"></button>
ugly, but works!

**Comment by jonnomk** [comment]
Yeah, you can solve most things by applying custom styles, but you shouldn't really have to.  The problem with a bunch of these components is that people have been using work-arounds to solve other issues too, and as a result the issues have been hanging around for years.

**Comment by SternBreeze** [comment]
any updates?

**Comment by h1ghland3r** [comment]
Any news?

**Comment by MaKCbIMKo** [comment]
I'm sorry, but I don't think it solved.

You closed this issue, but it still inserts `&nbsp` if you have no label.

I don't understand why it can't just render nothing if there is no label/icon?

**Comment by mycahmason** [comment]
I'm using 12.1.1 and still have this issue.

Is it possible to reopen this?

**Comment by AlexanderVega** [comment]
Any news about this bug?

**Comment by AlexanderVega** [comment]
> https://stackblitz.com/edit/github-bd8xy8?file=src%2Fapp%2Fapp.component.html <--- example showing the bug.  
> 
> &nbsp is added in the 'label'  `<span>` when no label is defined.  
> 
> 
> 
> ```
> 
> <button pButton (click)="onClick()"></button>
> 
> ```
> 
> 
> 
> renders
> 
> 
> 
> ```
> 
> <button pbutton class="p-element p-button p-component">
> 
> <span class="p-button-label">&nbsp;</span>
> 
> </button>
> 
> ```
> 
> 
> 
> expected render
> 
> 
> 
> ```
> 
> <button pbutton class="p-element p-button p-component">
> 
> <span class="p-button-label"></span>
> 
> </button>
> 
> ```

What I did to solve this bug is get the class of element span inside the button tag and "display: none". Use this to a specific element, cause' maybe later you will need this element in another button

**Comment by DanilVezmenov** [comment]
Still not resolved!!! I HATE THIS BUG 
NEED USE 
```
 ::ng-deep .p-button-label {
        display: none !important;
      }
```
For hardcode resolve

**Comment by DanilVezmenov** [comment]
![image](https://user-images.githubusercontent.com/107387472/184827506-3316bc04-48e2-4072-b323-5c0315901513.png)
&nbsp; span when  label is empty

**Comment by Alhajras** [comment]
The bug still exists!
