### ISSUE TITLE
p-calendar has problems with IOS

### ISSUE THREAD

**Issue by scurk1415** [primefaces/primeng#9487]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-calendar-demo-y1eoby?file=src/app/app.component.html

(I dont have an ios device so i hope it works here)

**Current behavior**
There is a problem with IOS devices closing the calendar modal when you want to change the year or month (if you have monthNavigator or yearNavigator set to true). My guess is that it is because of the default select behavior of IOS which opens the options in the bottom of the screen (like it is a keyboard)

Edit: Found out that its probably not because of the select, but because of scrolling. When scroll happens the modal gets closed. So basically if you open it on ios the default behavior of IOS select resizes the screen which makes your scrollHandler close the modal

**Expected behavior**
Dont close the calendar modal when you want to select month/year from the dropdown

* **Angular version:** 5.X
10.1.6

* **PrimeNG version:** 5.X
10.0.3

* **Browser:**
IOS all browsers

**Comment by scurk1415** [comment]
Here is a hacky solution for those that have the same issue as me and don't have an option to wait before they fix it
```
@Directive({
  selector: '[scrollHandlerHack]'
})
export class ScrollHandlerDirective implements AfterContentInit {

  constructor(private calendar: Calendar) {
  }

	ngAfterContentInit(): void {
		this.calendar.bindScrollListener = () => {
			console.log('test');
		};
	}

}
```

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
