### ISSUE TITLE
Could md-inputfield be ported back to Ultima Theme ?

### ISSUE THREAD

**Issue by paulyipkh** [primefaces/primeng#9492]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**What is the motivation / use case for changing the behavior?**
Our project's layout is depending heavily on md-inputfield but it is removed from Ultima 10. A boxed input field will break the design and feel of the UI.

Is there any plan to port md-inputfield back to Ultima in the future version. Otherwise, we will get stuck at Ultima 9 or have to consider developing a custom component using cdk.

**Comment by cagataycivici** [comment]
Please use Ultima forum for questions. md-inputfield is deprecated in favor of the p-float-label. Our team may provide custom css for compatibility in Ultima forum.
