### ISSUE TITLE
Table: Changing page then sorting does not update first property when resetPageOnSort=true

### ISSUE THREAD

**Issue by ksCookj** [primefaces/primeng#9493]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://primeng-tablelazy-demo-rtklap.stackblitz.io/

**Current behavior**
As described in #7453 and #7453 the issue persist in primeng 10

changing page then sorting keeps lazyload event first property still set to the page you first selected, even though the page has changed to the first.

**Expected behavior**
 lazyload event first property should reflect change to page on sorting if resetPageOnSort =true

**Minimal reproduction of the problem with instructions**
1. Change page to page 3 for example
2. sort first column
3. see page is changed to the first
4. see lazyload event first property still set to the page you first selected

* **PrimeNG version:** 10.x

* **Browser:** [all]

**Comment by grozdanova** [comment]
+1. It was OK in version 8.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
