### ISSUE TITLE
p-dataView not updating view after [layout] change

### ISSUE THREAD

**Issue by makkaronis4e** [primefaces/primeng#9494]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
```

**Plunkr Case (Bug Reports)**

https://stackblitz.com/edit/primeng-dataview-demo-6xq8gk?file=src%2Fapp%2Fapp.component.ts

click on button "switch to list"

**Current behavior**
When changing [layout] value, view is not updating. At the same time wrapper class and p-dataViewLayoutOptions updating fine.

<img width="941" alt="d" src="https://user-images.githubusercontent.com/33792090/98169724-772a1700-1ef5-11eb-8d0e-6c22ed6ed972.png">

**Comment by Detrasoft** [comment]
I have a similar problem. The cause can be the same as reported.
When adding items to the array, the dataview component is not updated until an iteration is triggered manually by the user.
![captured-min](https://user-images.githubusercontent.com/46575134/101231720-e711f580-368b-11eb-9ea0-99957659ef8a.gif)

https://stackblitz.com/edit/primeng-dataview-demo-pnyzqa?file=src/app/app.component.ts

**Comment by michael-expedito** [comment]
Exactly as reported I am having the same problem in the most current versions of primeng.

When adding a record to the array through typescript the dataview component is not updated automatically. It needs an iteration of the user for it to be updated with the record that was added.

Simulated problem in my repository:
https://github.com/michael-expedito/teste-data-view
