### ISSUE TITLE
prime ng 10.0.3: pTable - ng template RowExpansion is not working with virtual scroll and lazy loading 

### ISSUE THREAD

**Issue by karunalpuria** [primefaces/primeng#9498]
Trying to upgrade prime ng 9.0.6 to 10.0.3
https://stackblitz.com/edit/primeng-tablevirtualscroll-demo - Virtual scroll demo from prime ng

https://stackblitz.com/edit/primeng-tablevirtualscroll-demo-1tbw9a?file=src%2Fapp%2Fapp.component.html - My attempt to incorporate row expansion ng template within the virtual scroll demo

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Comment by karunalpuria** [comment]
the issue still persists and can be observed in example created on  
https://stackblitz.com/edit/primeng-tablevirtualscroll-demo-63ji5r?file=src%2Fapp%2Fapp.component.html

In example,
I have added a column expand for accordion feature. Its click event doesn't work
Also, when I inspect the rendered elements 
expected: should render only approximately 10 rows of data
actual: rendering all the rows at once approximately 30000 rows
