### ISSUE TITLE
Add keyboard support to ContextMenu

### ISSUE THREAD

**Issue by yigitfindikli** [primefaces/primeng#9499]
ContextMenu may be more accessible with keyboard.

Key | Description
--| --
Up | Navigates to the previous menu item.
Down | Navigates to the next menu item.
Left | Close the current submenu and navigates to the parent menu.
Right | Open the next submenu and navigates to it.
Esc | Closes the contextMenu.
Enter | Select the menu item and then calls its command callback.

**Comment by lennybakkalian** [comment]
Does not work if several context dialogs are opened one above the other
