### ISSUE TITLE
When inspecting the selected files FileList is empty if the selected file type is different from an image

### ISSUE THREAD

**Issue by ilmoralito** [primefaces/primeng#9501]
**Current behavior**
When trying to upload a file using customUpload, when checking event.files it is empty when the file type is different from images, if for example in my case I select .xml or .pdf files the list of files to upload is empty.

I attach the following [repository](https://github.com/ilmoralito/primeng-custom-fileupload-scenario) with the minimum configuration to reproduce the problem

In template
```
<p-fileUpload
  name="file[]"
  mode="basic"
  customUpload="true"
  (uploadHandler)="upload($event)"
></p-fileUpload>
```

Method

```
upload(event: any): void {
  alert(JSON.stringify(event, null, 2));
}
```

When I select a file other than an image I get the following output

```
{
  "files": [
    {}
  ]
}
```

When I select to upload some image the output is

```
{
  "files": [
    {
      "objectURL": {
        "changingThisBreaksApplicationSecurity": "blob:http://localhost:4200/9d6b15a3-765d-429e-b944-6c410875847c"
      }
    }
  ]
}
```

**Expected behavior**

Get a list of files regardless of the type of file you are trying to upload

**Please tell us about your environment:**

Angular CLI: 10.2.0
Node: 12.18.3
OS: win32 x64
"primeicons": "^4.0.0",
"primeng": "^10.0.3",

* **Angular version:**
Angular CLI: 10.2.0

* **PrimeNG version:**
"primeng": "^10.0.3",

* **Browser:**
Firefox, Chrome

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
