### ISSUE TITLE
Support focus-within states for checkbox and radio button

### ISSUE THREAD

**Issue by 2ne** [primefaces/primeng#9503]
Check box and radio button currently support focus events and pass a p-focus class. Could this be extended to handle focus-within so that the user only sees the focus styles when using the keyboard? For inputtext and many other components, the focus-within state can be handled with CSS but these 2 components don't allow for that.

[x] feature request

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
