### ISSUE TITLE
Deprecate SelectItem

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#9506]
Because of latest enhancements e.g. 4295, we no longer need SelectItem or SelectItemGroup.

**Comment by bendehghan** [comment]
I'm not seeing info about SelectItem in the docs. Is it actually deprecated? I'm still using it in 16.6.0 but it's not behaving properly after that starting in 16.7.0

But I don't see any deprecation warnings or anything about a way forward. 

What is the path forward for SelectItem? It seems like a good API to me so not sure why the support if falling.
