### ISSUE TITLE
I hope tieredmenu can support closing the menu after clicking the menu option

### ISSUE THREAD

**Issue by luoxiao-xy** [primefaces/primeng#9507]
I hope tieredmenu can support closing the menu after clicking the menu option。After clicking, the menu is always displayed under the button, which is very unfriendly. I think it should be allowed to close the menu after clicking, and to hide the menu by clicking on other blanks.

**Comment by cagataycivici** [comment]
Issue is not clear, please create a new one with a stackblitz template or a video that explains the case.
