### ISSUE TITLE
File upload dialog openging on any keydown 

### ISSUE THREAD

**Issue by avsrinivasa** [primefaces/primeng#9508]
The issue with p-fileUpload with the "basic" mode
When we have a focus on p-fileUpload and on pressing any key Os file upload dialog is opening. Where it should open only on the press of Enter. Also, the focus is going to the choose button when we specify [disabled] =true to the p-fileUpload component.

**Comment by avsrinivasa** [comment]
The fix could be, we need to modify (keydown)="onBasicUploaderClick()" to (keydown.enter)="onBasicUploaderClick()" in case of "mode === 'basic'"

**Comment by Gykonik** [comment]
I have the same problem, a fix would be really awesome!
I also think that, @avsrinivasa's fix would be ok (only this small change on line 59 I guess).
Atm if the basic file uploader has focus and we e.g. tab out of the window, the dialog opens like 5 more times, which is really anoying! :)

**Comment by avsrinivasa** [comment]
Any tentative timeline for this fix?
