### ISSUE TITLE
TieredMenu cannot scroll or get to overflow items - primeng10.0.3

### ISSUE THREAD

**Issue by Thorski** [primefaces/primeng#9511]
**I'm submitting a ...**  (check one with "x")
[X ] bug report => Search github for a similar issue or PR before submitting

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-r9gjq2?file=src%2Fapp%2Fapp.component.ts

**Current behavior**
If you have a number of items in a TieredMenu popup such that they overflow, they are hidden and there is no way to scroll.
The scrollbar appears, but if an attempt is made to scroll either by dragging the scrollbar OR by scrolling the mousewheel,
the TieredMenu popup disappears.

This only happens in 10.0.3.

If you change the dependency in the stackblitz to 10.0.0 it allows scroll.

**Expected behavior**
Don't hide the menu on scroll, this makes the TieredMenu useless for items that overflow.

**Minimal reproduction of the problem with instructions**
See stackblitz above.

**What is the motivation / use case for changing the behavior?**
Make TieredMenu useful again.

* **PrimeNG version:** 10.0.3

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
