### ISSUE TITLE
Not able to select default value in p-dropdown with  template driven approach

### ISSUE THREAD

**Issue by sahil1207** [primefaces/primeng#9514]
<p-dropdown [options]="countryModel" [virtualScroll]="true"
                                        styleClass="form-control border-primary" 
                                        optionLabel="itemName" name="countryname"
                                        [(ngModel)]="paymentService.datas.country"
                                         filter="true" placeholder="Select Country" >
                                        </p-dropdown>

countryModel =[ {id: 40, itemName: "Tuvalu"},
{id: 39, itemName: "India",},
 {id: 38, itemName: "Singapore"}]

I want to show the default value of dropdown as "Singapore" id = 38

Currently , I amusing angular 8

**Comment by yigitfindikli** [comment]
Issue is not clear, please feel free to reopen with a stackblitz example.
