### ISSUE TITLE
PrimeNG 9 showcase not found

### ISSUE THREAD

**Issue by adama357** [primefaces/primeng#9515]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
If I go to https://primefaces.org/primeng/showcase/#/ and select v9.1.7-lts, I get a page that says "The page you are looking for is not found"

**Please tell us about your environment:**

Windows 10

* **Browser:** Chrome 86

**Comment by Rotzbua** [comment]
Seems you got cached data oder website was rebuilding. Current is: https://www.primefaces.org/primeng/v9.1.8-lts/#/

**Comment by adama357** [comment]
Cool, well that solves that!
