### ISSUE TITLE
p-calendar: correct month should be displayed if date falls outside current month range

### ISSUE THREAD

**Issue by quekqh** [primefaces/primeng#9518]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
If showOtherMonths and selectOthermonths in p-calendar is set to true, user is able to select dates outside the range of the month display. For example, in Oct 2020, user will be able to select 31st September.

However, the month navigator is not updated and remains at October when a date in September is selected.

**Expected behavior**

Month navigator should be updated to display the relevant month if the user selects date that falls outside the range of the current month shown

![image](https://user-images.githubusercontent.com/12732739/99031061-15cb0d80-25b1-11eb-8789-95d01772d5bd.png)

**Comment by yigitfindikli** [comment]
Select element always shows the main month. So it's expected behavior.

Regards.
