### ISSUE TITLE
p-tree should reapply filter when new array of tree nodes is set

### ISSUE THREAD

**Issue by bozjator** [primefaces/primeng#9519]
**I'm submitting a ...** 
```
[ x ] bug report 
[ ] feature request 
[ ] support request 
```

**Current behavior**
1. User apply filter to search for tree nodes.
2. Then user changes some data (eg. through context menu)
3. New tree nodes are structured with updated data and new array of tree nodes is passed to p-tree.
4. Data that is shown is old filtered data.

**Expected behavior**
1. User apply filter to search for tree nodes.
2. Then user changes some data (eg. through context menu)
3. New tree nodes are structured with updated data and new array of tree nodes is passed to p-tree.
4. Filter is triggered on new array of tree nodes.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/primeng-treefilter-demo-nktgnb?file=src/app/app.component.ts

* **Angular version:** 10.0.11

* **PrimeNG version:** 10.0.3

**Comment by averath** [comment]
I've made probably a duplicate: https://github.com/primefaces/primeng/issues/10518

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
