### ISSUE TITLE
Dropdown should scroll to selected item when overlay gets opened

### ISSUE THREAD

**Issue by loic49** [primefaces/primeng#952]
Hi,

I use dropdown component with bindings. When dropdown is opened for the first time, the scroll is not on selected item, I've to scroll manually to see it. Perhaps I'm missing something ?

Thanks

**Comment by Dalirik** [comment]
Hi,
any progress with this issue?
Thanks

**Comment by cagataycivici** [comment]
We'll review, we have scrollInView property that we can call on open to fix this.
