### ISSUE TITLE
FullCalendar docs, Location of main css file incorrect

### ISSUE THREAD

**Issue by razinj** [primefaces/primeng#9522]
**I'm submitting a bug report**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
Incorrect location of main css file : `"node_modules/@fullcalendar/core/main.min.css"`

**Expected behavior**
Correct location of core css file : `"node_modules/@fullcalendar/common/main.min.css"`

**Minimal reproduction of the problem with instructions**
Simple FullCalendar implementation following te official docs for the latest version.

**What is the motivation / use case for changing the behavior?**
Proper installation guide, Beginners how are not experienced won't bother to look into the package in the node_modules folder which may lead them to abandon the integration and look else where + possibility talking bad about PrimeNG (makes reputation goes down).

**Please tell us about your environment:**
OS : MacOS Big Sur
Node JS : 12.18.2
NPM : 6.14.5

* **Angular version:** 10.1.5

* **PrimeNG version:** 10.0.3

* **Browser:**
Chrome 86.0.4240.198
 
* **Language:**
TypeScript 4.0.2

* **Node (for AoT issues):** `node --version` =   12.18.2

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Comment by sasynkamil** [comment]
@razinj FullCalendar main.css (main.min.css) path has changed in FullCalendar v5. But PrimeNG (11.2) is still using v4. You can see it e.g. here in PrimeNG repo - [package.json](https://github.com/primefaces/primeng/blob/master/package.json):
```json
    "@fullcalendar/core": "4.1.0",
    "@fullcalendar/daygrid": "4.1.0",
    "@fullcalendar/interaction": "4.1.0",
    "@fullcalendar/timegrid": "4.1.0",
```
