### ISSUE TITLE
p-contextMenu for p-tree goes off the screen when right click on the bottom of screen if context menu items are dynamically created

### ISSUE THREAD

**Issue by pavelserov** [primefaces/primeng#9523]
**I'm submitting a bug report**

```
<p-tree [value]="files" selectionMode="single" [(selection)]="selectedFile" [contextMenu]="cm" (onNodeContextMenuSelect)="nodeContextMenuSelect($event)">
  <ng-template let-node pTemplate="default">
    <span [ngClass]="{ 'has-changes' : node.hasChanges }">{{node.label}}</span>
  </ng-template>
</p-tree>
<p-contextMenu #cm [model]="items" appendTo="body"></p-contextMenu>
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/primeng-treecontextmenu-demo-zsbes7
https://primeng-treecontextmenu-demo-zsbes7.stackblitz.io

**Current behavior**
I have a p-tree with many nodes and sub-nodes in my project. There are different nodes types, so context menu for each node is created dynamically at the moment of node right clicked. So when I right click at the last node in the tree, context menu appears "down" to the screen (instead of "up") and vertical scroll appears. After that if I right click to the same node again - context menu has correct position (it is opened to the "up"), but first time open is incorrect and it requires the user to scroll down.

**Expected behavior**
Context menu is opened to the "up" each time where it is necessary.

**Minimal reproduction of the problem with instructions**
1. Please open https://primeng-treecontextmenu-demo-zsbes7.stackblitz.io
2. Expand last node (Movies)
3. Expand last sub-node (Robert De Niro)
4. Right click on last sub-tree node (Untouchables)
5. See context menu position

**What is the motivation / use case for changing the behavior?**
This confuses user and requires to scroll down. This is a problem in case of content is automatically adjusted to the full screen of the browser and no scroll appears on the page.

**Please tell us about your environment:**
Windows 10

* **Angular version:** 10.X, 11.X

* **PrimeNG version:** 10

* **Browser:** all
 
* **Language:** all

* **Node (for AoT issues):** `node --version` =   12.18.4

**Comment by zachariaellaham** [comment]
We have a similar issue is there any updates ?

**Comment by AlexMartigny** [comment]
I'm facing the same problem here. Is there anything being done for this issue?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by zachariaellaham** [comment]
@mertsincan  Hello I was wondering if there was any update on this issue.

Best regards, 🙏

**Comment by m-wheeler** [comment]
I'm having the same problem. My workaround is to create the menu with all of the menu items before it's shown for the first time, so it will know how big it should be. Fortunately for me, the layout of the menu doesn't change, just what it's bound to and what commands it will fire.
