### ISSUE TITLE
Overflow-y in table.ts shouldn't be scroll

### ISSUE THREAD

**Issue by Gadziu1** [primefaces/primeng#9525]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/primeng-tablescroll-demo-xhllzd?file=src%2Fapp%2Fapp.component.html

**Current behavior**
using scrollHeight="flex" with p-table leave scroll on screen, even there are not so many items in list

**Expected behavior**
scroll is gone for not overflowing items

**Minimal reproduction of the problem with instructions**
check stackblitz

**What is the motivation / use case for changing the behavior?**
I found the problem is putting `overflow-y: scroll` to `p-datatable-scrollable-body`. It should be set for auto, or undifined. This change was done in this  #commit a365b7a360f16cfb3bd44ba018e9c6fa1626222e . When you switch the primeNG to version 10.0.0 problem is gone.

**Please tell us about your environment:**

* **Angular version:** 10.2.7

* **PrimeNG version:** 10.0.3

* **Browser:** [all]

 
* **Language:** [ TypeScript 4.0.3 ]

**Comment by cagataycivici** [comment]
This is required to prevent misalignment issues, we'll consider this when we try to reimplement scrollable tables with position sticky instead of separate tables. There is no other clean solution other than enforcing a scrollbar.

**Comment by Gadziu1** [comment]
Thanks for replay @cagataycivici 
Is there any possibility to override this styling, because it looks awful when this scroll is forced there? You've set this styling on element level so I can't override it...
