### ISSUE TITLE
p-calendar: In the mode box, open pop up. Open for the first time, it can open normally. Close the mode box and open it again. It will not open normally.

### ISSUE THREAD

**Issue by luoxiao-xy** [primefaces/primeng#9527]
In the mode box, open pop up. Open for the first time, it can open normally. Close the mode box and open it again. It will not open normally.

**Comment by luoxiao-xy** [comment]
Recurrence prompt: the problem has been repeated. When the calendar control pops up, close the modal box directly. Then open the modal box again, click the calendar control, it will not pop up normally!

**Comment by yigitfindikli** [comment]
Issue is not clear, please feel free to reopen with a stackblitz example.
