### ISSUE TITLE
p-panel with toggler="header" should not toggle when custom icons are clicked

### ISSUE THREAD

**Issue by rastarubio** [primefaces/primeng#9528]
I'm submitting a
[x ] bug report 

Issue applies to p-panels with toggler set to "header".

Example Code: 
```
<p-panel toggler="header">
  <ng-template pTemplate="icons">
      <button pButton class="p-panel-header-icon p-link" (click)="menu.toggle($event)">
          <span class="pi pi-cog"></span>
      </button>
      <p-menu #menu id="config_menu" [model]="items" [popup]="true"></p-menu>
  </ng-template>
</p-panel>
```

https://stackblitz.com/edit/primeng-panel-demo-ie5nrk

**Current behavior**
1. When clicking panel header the panel is toggled
2. When clicking icon (pi pi-cog) in header:
- the menu appears
- **the panel is toggled** 

**Expected behavior**
When clicking an icon in the header the panel **should not be toggled**

**Comment by yigitfindikli** [comment]
You can prevent this action on your side. Like [this](https://stackblitz.com/edit/primeng-panel-demo-ucqhvz?file=src/app/app.component.html).

Regards.

**Comment by rastarubio** [comment]
thanks!
