### ISSUE TITLE
More search filters for searchable components (Dropdown Multiselect Listbox etc)

### ISSUE THREAD

**Issue by loic49** [primefaces/primeng#953]
Hi,

Is it possible to define a seacrh filter function ? Today, search is done with startsWith function, but we could imagine we want to do a contains search.

Do you think you could plan such fonctionnality in the future ?

Thanks

**Comment by An0d** [comment]
+1

**Comment by Samisama** [comment]
Hi, I would like to know if it's possible to have a custom filter function with the dropdown ? 
Indeed I display some data in my dropdown as "Mrs. XXX, Mr. YYY, ..." and I would like the filter to search only on names and not on "Mrs" and "Mr".
Thank you

**Comment by carlos-ruiz-bravo** [comment]
It would be a good option to be able to define out own filter function, contains search is not always the desired behavior.
