### ISSUE TITLE
empty and emptyFilter template for components

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#9532]
For components that support filtering, add support for emptyFilter template in addition to emptyFilterMessage. Examples are dropdown, multiselect, listbox ...

**Comment by dancornilov** [comment]
Hey, can I help you with this feature? If I am not wrong should be the similar approach to all of component which u meantioned.

**Comment by yigitfindikli** [comment]
for dropdown https://github.com/primefaces/primeng/commit/ae9d47feab80072e1c195702092c8edd8ff09b0a

**Comment by yigitfindikli** [comment]
for multiselect https://github.com/primefaces/primeng/commit/3c485fac56084066eb270d3e8fa44aabc5f5e157
