### ISSUE TITLE
P-table Paginator aligns to the left if you also use a paginator right. It should remain in the center.

### ISSUE THREAD

**Issue by evandouglas** [primefaces/primeng#9533]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/primeng-tablebasic-demo-ue5gte?file=src/app/app.component.html

**Current behavior**
Having 
`[paginator]="true"`
on a p-table, and also including a paginatorright template will left-align the paginator. This is new in PrimeNG v10. In v9, it remained in the center.
One way of re-centering the paginator is to include an empty paginatorleft.

**Expected Behavior**
The paginator should stay center-aligned even if you have a separate paginatorright or paginatorleft.

**Minimal reproduction of the problem with instructions**
`<p-table [value]="products" [paginator]="true" [rows]="5">`
`	<ng-template pTemplate="paginatorright" let-state>
		Total Records: {{ state.totalRecords }}
	</ng-template>
`
**What is the motivation / use case for changing the behavior?**
This seems to be a regression from PrimeNG v9

* **Angular version:** 10

* **PrimeNG version:** 10.0.3

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
