### ISSUE TITLE
Slider range issue when max values on the right

### ISSUE THREAD

**Issue by aochocki** [primefaces/primeng#9538]
If you have a PrimeNG PRO Support subscription please post your issue at;

https://pro.primefaces.org 

where our team will respond within 4 business hours.

If you do not have a PrimeNG PRO Support subscription, fill-in the report below. Please note that
your issue will be added to the waiting list of community issues and will be reviewed on a first-come first-serve basis, as a result, the support team is unable to guarantee a specific schedule on when it will be reviewed. Thank you for your understanding.

Current Queue Time for Review
Without PRO Support: ~8-12 weeks.
With PRO Support: 1 hour

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://primefaces.org/primeng/showcase/#/slider

**Current behavior**
When you have range slider with initial values for example 20-80 try to set values maximum to the right to be 100-100. 
Then you can't change any more values.

**Expected behavior**
Ability to set values in range slider when both values are in max

**Minimal reproduction of the problem with instructions**

When you have range slider with initial values for example 20-80 try to set values maximum to the right to be 100-100. 
Then you can't change any more values.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 5.X
9

* **PrimeNG version:** 5.X
10.0.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 all
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by yaoxiantong** [comment]
@aochocki 
> If it is PC side, you can use this method to repair temporarily and wait for the official repair
   
```
<p-slider #progressSlider [(ngModel)]="rangeValues" [range]="true" (onChange)="handleChange($event)"></p-slider>

export class SliderDemo {
    @ViewChild("progressSlider") progressSlider: Slider;
    rangeValues: number[] = [20,80];

    handleChange(ev): void {
        if (ev.values[0] === 100 && ev.values[1] === 100){
            this.progressSlider.handleIndex = 0;
        }
    }
}
```
