### ISSUE TITLE
Multi selection drag and drop in primeng Tree

### ISSUE THREAD

**Issue by Arun-93** [primefaces/primeng#9539]
In angular, any suggestion for PrimeNg multi selection Drag and Drop. I have two trees, I'm dragging records from Tree A and dropping it in Tree B. I want to choose multiple records in Tree A and have to drop it at once in Tree B. By pressing ctrl I'm able to choose multiple records in Tree A but able to drag and drop only one record at time.

Is there any possible way where I can choose multiple records in Tree A and drop the same in Tree B at the same time

**Comment by Arun-93** [comment]
Code: 

<p-tree [value]="SenderFiles" [filter]="true" draggableNodes="true"
                                selectionMode={{SenderSelectionmode}} [(selection)]="senderNode" 
                               (onFilter)="modifyNodeFilter($event)" (onNodeSelect)="senderNodeSelect($event)"  
                               (onNodeUnselect)="senderNodeSelect($event)">
</p-tree>

<p-tree [value]="ReceiverFiles" [filter]="true" droppableNodes="true"
                                      selectionMode={{SenderSelectionmode}} [(selection)]="ReceiverNode"
                                      (onNodeDrop)="onDrop($event)" [validateDrop]="true" (onFilter)="modifyNodeFilter($event)"
                                      (onNodeSelect)="receiverNodeSelect()" (onNodeUnselect)="receiverNodeSelect()">
 </p-tree>

**Comment by Arun-93** [comment]
Hi Team,

Could you please advice on the above issue or any workaround as a temporary fix.

Thank you.

**Comment by sumitdhungana14** [comment]
Any updates on this?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by tylorngo** [comment]
Is there any update on this please? I managed to have a workaround but it's very inconvenient to develop additional feature on top of this (for example, redo/undo).

**Comment by tbaro** [comment]
I am also interested in hearing when this feature (multi-select drag & drop) will be available. It is an obvious requirement for any drag & drop feature and without it, the existing drag/drop functionality is not much use. (Also drag & drop on a TreeTable  would be extremely useful.)

**Comment by Mnaaz** [comment]
The multi selection drag and drop would very much be appreciated for the picklist as well. The behaviour of transferring items is a bit inconsistent at the moment. Transferring multiple items via the arrow buttons works, but it does not when using drag&drop.

**Comment by tarockx** [comment]
I second the suggestion. Being able to select multiple nodes but then not being able to drag them around is quite limiting and also not intuitive, no other everyday application works like that.
